### ISSUE TITLE
Pubblicazione: Errore in fase di recupero dell'esito della verifica

### ISSUE THREAD

**Issue by EnzoMaietta** [ministero-salute/it-fse-support#10]
Buongiorno, abbiamo validato con successo
`{"healthDataFormat":"CDA","mode": "ATTACHMENT","activity":"VALIDATION"} `

un cda (referto di laboratorio) ricevendo in output dal Gateway:
`{"traceID":"d8114e651fd2f04f","spanID":"d8114e651fd2f04f","workflowInstanceId":"2.16.840.1.113883.2.9.2.30.4.4.ed39d060f7769c14aa2f1909816888f87be7a9628ff888411be6eb722d5554e6.8d33dd2808^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

Ma quando successivamente proviamo a pubblicarlo con il seguente requestBody:
[{"workflowInstanceId": "2.16.840.1.113883.2.9.2.30.4.4.ed39d060f7769c14aa2f1909816888f87be7a9628ff888411be6eb722d5554e6.8d33dd2808^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","healthDataFormat": "CDA","mode": "ATTACHMENT","tipologiaStruttura": "Ospedale","attiCliniciRegoleAccesso": [  "P99"],"identificativoDoc": "2.16.840.1.113883.2.9.2.30.4.4^030703.MTTNZE84E02A509G.20220715145811","identificativoRep": "2.16.840.1.113883.2.9.2.30.4.5.1","tipoDocumentoLivAlto": "REF","assettoOrganizzativo": "AD_PSC001","dataInizioPrestazione": "20141020110012","dataFinePrestazione": "20141020110012","tipoAttivitaClinica": "CON","identificativoSottomissione": "2.16.840.1.113883.2.9.2.30.4.3.d8114e651fd2f04f","priorita": false}](url)

Ci viene risposto in output l'errore:
`{"traceID":"87c59065d509af7a","spanID":"87c59065d509af7a","type":"/msg/cda-element","title":"Errore in fase di recupero dell'esito della verifica.","detail":"Il CDA non risulta validato","status":400,"instance":"/msg/cda-element"}`

Dove stiamo sbagliando? Grazie in anticipo per il supporto.

**Comment by zukka77** [comment]
Ciao, state mandando lo stesso identico cda? viene fatto l'hash del cda in attachment al pdf e deve essere bit a bit lo stesso.

**Comment by EnzoMaietta** [comment]
Buongiorno, confermiamo che il pdf è il medesimo ed è stato generato con il tool "PDFGenerator" fornito. 
Lo alleghiamo: [elab.pdf](https://github.com/ministero-salute/it-fse-support/files/9382010/elab.pdf)

Le chiamate sono state fatte con curl utilizzando gli esempi nella documentazione. Per sicurezza abbiamo generato un nuovo tentativo, e adesso abbiamo ricevuto l'errore _"Verifica hash fallita."_
Vi forniamo di seguito il log di output completo dei "GovWay-Transaction-ID" se possono servire per recuperare le transazioni sui vostri log.


**_VALIDAZIONE:_**
_output:_
```
< HTTP/1.1 201 Created
HTTP/1.1 201 Created
< X-Backside-Transport: OK OK
X-Backside-Transport: OK OK
< Connection: Keep-Alive
Connection: Keep-Alive
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< Set-Cookie: 894d46ecfc124039ee218b63c12a3329=a12a888f575775e85809a139b3ad1f5f; path=/; HttpOnly; Secure; SameSite=None
Set-Cookie: 894d46ecfc124039ee218b63c12a3329=a12a888f575775e85809a139b3ad1f5f; path=/; HttpOnly; Secure; SameSite=None
< Server: GovWay-SOGEI
Server: GovWay-SOGEI
< GovWay-Message-ID: 1234
GovWay-Message-ID: 1234
< GovWay-Transaction-ID: 47b6ec93-1fb7-11ed-931a-005056ae7395
GovWay-Transaction-ID: 47b6ec93-1fb7-11ed-931a-005056ae7395
< Content-Type: application/json
Content-Type: application/json
< Date: Fri, 19 Aug 2022 12:05:56 GMT
Date: Fri, 19 Aug 2022 12:05:56 GMT
< X-Global-Transaction-ID: 3f7e3e2d62ff7ca31ef6f10d
X-Global-Transaction-ID: 3f7e3e2d62ff7ca31ef6f10d

< 
* Connection #0 to host 127.0.0.1 left intact
{"traceID":"9fb6b1a610e7982f","spanID":"9fb6b1a610e7982f","workflowInstanceId":"2.16.840.1.113883.2.9.2.30.4.4.ed39d060f7769c14aa2f1909816888f87be7a9628ff888411be6eb722d5554e6.8c90238a36^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}
```

**_PUBBLICAZIONE:_**
`requestBody={"workflowInstanceId": "2.16.840.1.113883.2.9.2.30.4.4.ed39d060f7769c14aa2f1909816888f87be7a9628ff888411be6eb722d5554e6.8c90238a36^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","healthDataFormat": "CDA","mode": "ATTACHMENT","tipologiaStruttura": "Ospedale","attiCliniciRegoleAccesso": [ "P99"],"identificativoDoc": "2.16.840.1.113883.2.9.2.30.4.4^030703.MTTNZE84E02A509G.20220715145811","identificativoRep": "2.16.840.1.113883.2.9.2.30.4.5.1","tipoDocumentoLivAlto": "REF","assettoOrganizzativo": "AD_PSC001","dataInizioPrestazione": "20141020110012","dataFinePrestazione": "20141020110012","tipoAttivitaClinica": "CON","identificativoSottomissione": "2.16.840.1.113883.2.9.2.30.4.3.1234","priorita": false}`

_output:_
```
< HTTP/1.1 400 Bad Request
HTTP/1.1 400 Bad Request
< X-Backside-Transport: FAIL FAIL
X-Backside-Transport: FAIL FAIL
< Connection: Keep-Alive
Connection: Keep-Alive
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< Set-Cookie: 894d46ecfc124039ee218b63c12a3329=a12a888f575775e85809a139b3ad1f5f; path=/; HttpOnly; Secure; SameSite=None
Set-Cookie: 894d46ecfc124039ee218b63c12a3329=a12a888f575775e85809a139b3ad1f5f; path=/; HttpOnly; Secure; SameSite=None
< Server: GovWay-SOGEI
Server: GovWay-SOGEI
< GovWay-Message-ID: 1234
GovWay-Message-ID: 1234
< GovWay-Transaction-ID: 87e03f91-1fb7-11ed-931a-005056ae7395
GovWay-Transaction-ID: 87e03f91-1fb7-11ed-931a-005056ae7395
< Content-Type: application/problem+json
Content-Type: application/problem+json
< Date: Fri, 19 Aug 2022 12:07:44 GMT
Date: Fri, 19 Aug 2022 12:07:44 GMT
< X-Global-Transaction-ID: 3f7e3e2d62ff7d0f1ef745ed
X-Global-Transaction-ID: 3f7e3e2d62ff7d0f1ef745ed

* HTTP error before end of send, stop sending
< 
* Closing connection 0
{"traceID":"cb043668fe6f48b2","spanID":"cb043668fe6f48b2","type":"/msg/document-hash","title":"Verifica hash fallita.","detail":"Verifica hash fallita.","status":400,"instance":"/msg/document-hash"}
```

**Comment by zukka77** [comment]
Questo ultiimo errore è dato dal fatto che nel jwt di signature ci deve essere lo sha256,  claim "**attachment_hash**", del pdf inviato. 
Nel caso specifico dovrebbe essere: **31f1fbd0053db651cb77afa101b35c523c984f42953c53157402ec55d71fad9f**

**Comment by EnzoMaietta** [comment]
Grazie mille, confermiamo che aggiungendo nel jwt il claim _"attachment_hash"_ anche la pubblicazione è andata a buon fine!

`{"traceID":"7d0c13e59d66637a","spanID":"7d0c13e59d66637a","workflowInstanceId":"2.16.840.1.113883.2.9.2.30.4.4.ed39d060f7769c14aa2f1909816888f87be7a9628ff888411be6eb722d5554e6.9e5afff8b5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

Buona giornata.
