### ISSUE TITLE
"Received request is not conform to the required interoperability profile" facendo la chiamata a /documents/validation

### ISSUE THREAD

**Issue by zaknet** [ministero-salute/it-fse-support#1000]
Buonasera,

sto provando a chiamare la funzione di validazione (/documents/validation) ma continuo ad avere questo errore:

{
    "type":
"https://cas5-0-urlprotect.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgovway.org%2fhandling%2derrors%2f400%2fInteroperabilityInvalidRequest.html%22&umid=cd5f28d4-3dee-4d75-afdd-3b31110335fb&auth=71a13bea07be23dc94f0190f69b0bbb0f54ab581-db99630e89a6f9faaabd2b2adbb51f6c98901db7,
    "title":
"InteroperabilityInvalidRequest",
    "status":
400,
    "detail":
"Received request is not conform to the required interoperability profile",
    "govway_id":
"8ebf38d4-74f9-11ef-b8bd-005056ae54fa"
}

eppure mi pare di aver seguito alla lettera le indicazioni, passando questo body dal mio progetto postman:
![immagine](https://github.com/user-attachments/assets/6b71301d-d927-41b9-8236-61a44d54e7e4)

é  possibile avere un aiuto in merito?
Grazie mille!

**Comment by zaknet** [comment]
Sistemando i valori di code e codesystem nel jwt, adesso mi esce questo errore, sempre con postman, stessa chiamata:

```
{
    "type": "https://govway.org/handling-errors/400/InvalidRequestContent.html",
    "title": "InvalidRequestContent",
    "status": 400,
    "detail": "Request content not conform to API specification: Validation error(s) :\nAn error occurred when getting the body content from type 'multipart/form-data'.\njava.io.IOException: org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found (code: 201)\n",
    "govway_id": "1b11f51c-7511-11ef-a6bf-005056ae7395"
}
```

però devo dire che come si vede nell'immagine sopra, il file è impostato direttamente da Postman.
Grazie per l'aiuto che vorrete darmi

**Comment by vigliottim** [comment]
Buongiorno,
potrebbe gentilmente dirci se tra gli _Headers_ ha inserito manualmente _"Content-Type"_ valorizzandolo con _multipart/form-data_?

![image](https://github.com/user-attachments/assets/4717dc2f-cec8-49c3-a56e-49968eb2a56c)

Grazie.

**Comment by zaknet** [comment]
Buongiorno!
ecco i miei header:
![immagine](https://github.com/user-attachments/assets/9b6e7e11-5bf9-4bb3-b425-1cdb86e61ad5)

**Comment by vigliottim** [comment]
Potrebbe riprovare rimuovendo la spunta da _Content-Type_ e informarci se l'errore si ripresenta? 
Grazie.

**Comment by zaknet** [comment]
Sembra che vada in default su un altro formato in questo modo:
```
{
    "type": "https://govway.org/handling-errors/400/InvalidRequestContent.html",
    "title": "InvalidRequestContent",
    "status": 400,
    "detail": "Request content not conform to API specification: Validation error(s) :\nContent type 'application/octet-stream' is not allowed for body content. (code: 203)\n",
    "govway_id": "bc405651-7593-11ef-a6bf-005056ae7395"
}
```

**Comment by LucaRogledi** [comment]
> Buongiorno! ecco i miei header: ![immagine](https://private-user-images.githubusercontent.com/7643841/368463444-9b6e7e11-5bf9-4bb3-b425-1cdb86e61ad5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQ3MTUsIm5iZiI6MTcyNjY0NDQxNSwicGF0aCI6Ii83NjQzODQxLzM2ODQ2MzQ0NC05YjZlN2UxMS01YmY5LTRiYjMtYjQyNS0xY2RiODZlNjFhZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMDcyNjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWFkODk5ZGUwOTZjOGJkOWU4ZTU4YzliM2FiZGZkZTNhNzFjMzM5NjdjNzYyZTlmMjY2NDA3NGJjMjMyN2MyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ICL5k1PsehhaMrHZ0MHOSTSahcNiZhY6gzS7nLq9tO0)

Buongiorno, la invitiamo a riprovare con i seguenti headers dopo aver selezionato la check-box indicata nel seguente screenshot:
![image](https://github.com/user-attachments/assets/21c2dbaa-7d26-4202-9fa5-2def4dd1de7a)
Restiamo a disposizione in caso l'errore dovesse ripresentarsi. Grazie

**Comment by zaknet** [comment]
Grazie ora funziona.
Ora ho dei problemi con i dati del payload del jwt ma nel caso apro un altro ticket.
Grazie ancora.

**Comment by vigliottim** [comment]
Grazie a lei per il gentile feedback.
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
