### ISSUE TITLE
Discrepanza descrizioni errori validazione

### ISSUE THREAD

**Issue by Axloide** [ministero-salute/it-fse-support#1001]
Buongiorno,
in data 16 Settembre riceviamo una mail di mancato accreditamente per errori su alcuni test per l'accreditamento dei documenti PSS (Fornitore [A1#111080XXXXXXXX] - Vendor:[Lepida] - ID: [Lepida_CVPI] - Version: [2.0.1]), nello specifico nella risposta con sha 430cd63741f9b30d07caad5510ad9b344232da62 in riferimento al test 444 viene segnalato che:

`"description" : "<error code='168' attribute='displayName' actual = 'Storia d'uso di dispositivi medici' expected = 'Storia di uso di dispositivi medici'>ClinicalDocument/component/structuredBody/component/section[ID=Protesi_impianti_ausili]/code</error>"`

Provvediamo quindi a correggere il testo, facciamo una nuova pull request e nella validazione test del pomeriggio del 17 Settembre, risposta con sha 070827993215c7fbbe6794b62e9dde46d9bea9e4 in riferimento al test 445 viene segnalato che:

`<error code='424' attribute='displayName' actual = 'Storia di uso di dispositivi medici' expected = 'Storia d'uso di dispositivi medici'>ClinicalDocument/component/structuredBody/component/section[ID=Protesi_impianti_ausili]/code</error>`

E' possibile un chiarimento a riguardo?
In attesa di un gentile riscontro
Grazie

**Comment by Axloide** [comment]
Buongiorno,
avete aggiornamenti in merito alla segnalazione?

Grazie

**Comment by Axloide** [comment]
Buongiorno,
avete aggiornamenti a riguardo? Purtroppo data la problematica non riusciamo a procedere con la procedura di accreditamento

Grazie

**Comment by vigliottim** [comment]
Buongiorno,
è stato rilasciato un aggiornamento.
Potreste cortesemente riprovare e darci riscontro?
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
è stato rilasciato un aggiornamento.
Le chiediamo di aggiornare i wii ed effettuare nuovamente la procedura poiché sono scaduti.
Grazie per la collaborazione.
