### ISSUE TITLE
Errore semantico in documento RSA

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#1002]
Buongiorno,
dopo aver ottenuto l'accreditamento, siamo passati all'implementazione nei programmi, ma riceviamo un errore di semantica che non riusciamo ad individuare.
L'errore ricevuto è questo:
**{
  "traceID": "283d8a9617b899de",
  "spanID": "283d8a9617b899de",
  "type": "/msg/semantic",
  "title": "Errore semantico.",
  "detail": "Error while executing validation on sch schematron",
  "status": 422,
  "instance": "/validation/error",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.160.4.4.77c16e8fad8c512becbe2e8edd1c88d6361e0d8eaf7072049c41027076ad6a3d.5755287b41^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "warning": null
}**
Ed il CDA in questione è in allegato. Potete aiutarci a capire dove sbagliamo?
Grazie mille.
[cdarsa.zip](https://github.com/user-attachments/files/17042338/cdarsa.zip)

**Comment by vigliottim** [comment]
Buongiorno,
a seguito di diversi controlli relativamente al CDA2 da lei fornito, abbiamo verificato che il file presenta un carattere nascosto di tipo Byte Order Mark (BOM).
Per individuare ed eliminare tali caratteri è possibile utilizzare un editor di testo che individua i caratteri nascosti. 
Infatti, in alcuni casi questi caratteri vengono interpretati come caratteri speciali e possono creare dei problemi in fase di validazione del CDA2.
Rimaniamo a disposizione per chiarimenti.

**Comment by infoserviceonline** [comment]
Risolto, non avevamo fatto caso che diverse versioni di linguaggio usavano diverse codifiche anche sullo stesso codice. Adesso è tutto a posto.
Grazie infinite. Chiudo
