### ISSUE TITLE
Mancata ricezione di chiamata da parte del Gateway

### ISSUE THREAD

**Issue by federicolau** [ministero-salute/it-fse-support#1003]
Ciao,

stiamo riscontrando problemi con la chiamta al **servizio di pubblicazione** utilizzando il seguente codice fiscale **FSEPGL01E41A145J**. Il servizio risponde con esito positivo ma non riceviamo nessuna chiamata al nostro endpoint da parte del Gateway.

A seguire gli step che abbiamo conseguito:

**1. Chiamata al servizio di validazione:**

```
POST https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation

POST data:
--rY8eLnt4ilaInNKQeMFLMmtXisy-V1p2
Content-Disposition: form-data; name="requestBody"
Content-Type: application/json; charset=UTF-8
Content-Transfer-Encoding: 8bit

{"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VALIDATION"}
--rY8eLnt4ilaInNKQeMFLMmtXisy-V1p2
Content-Disposition: form-data; name="file"; filename="output.pdf"
Content-Type: application/pdf
Content-Transfer-Encoding: binary

<actual file content, not shown here>
--rY8eLnt4ilaInNKQeMFLMmtXisy-V1p2--
```

ottenendo la seguente la seguente risposta:

`{"traceID":"6a58bc2004c322cb","spanID":"6a58bc2004c322cb","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.6777319a0e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","warning":"[SIGN_WARN - Attenzione il documento risulta firmato in validazione]"}`

**2. Chiamata al servizio di pubblicazione:**

```
POST https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents

POST data:
--00BKkWdIxudQqSH_Vr9XkMg5Cdx9uHexPTRut
Content-Disposition: form-data; name="requestBody"
Content-Type: multipart/form-data; charset=UTF-8
Content-Transfer-Encoding: 8bit

{   "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.6777319a0e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",   "healthDataFormat": "CDA",   "mode": "ATTACHMENT",   "tipologiaStruttura": "Ospedale",   "attiCliniciRegoleAccesso": [     "PUBLICPOL"   ],   "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^290816",   "identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.1",   "tipoDocumentoLivAlto": "REF",   "assettoOrganizzativo": "AD_PSC001",   "dataInizioPrestazione": "20141020110012",   "dataFinePrestazione": "20141020110012",   "tipoAttivitaClinica": "CON",   "identificativoSottomissione": "2.16.840.1.113883.2.9.2.120.4.3.489592",   "priorita": false,   "descriptions": [     "019655^Bentelan^2.16.840.1.113883.2.9.6.1.5"   ],   "administrativeRequest":[ "SSN"] }
--00BKkWdIxudQqSH_Vr9XkMg5Cdx9uHexPTRut
Content-Disposition: form-data; name="file"; filename="output.pdf"
Content-Type: application/pdf
Content-Transfer-Encoding: binary

<actual file content, not shown here>
--00BKkWdIxudQqSH_Vr9XkMg5Cdx9uHexPTRut--

```

ottenendo la seguente la seguente risposta:

`{"traceID":"24e066e35a648e3d","spanID":"24e066e35a648e3d","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.6777319a0e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

**3. Chiamata al servizio di status:**

`GET https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/status/2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.6777319a0e%5E%5E%5E%5Eurn%3Aihe%3Aiti%3Axdw%3A2013%3AworkflowInstanceId`

ottenendo la seguente la seguente risposta:

`{"traceID":"046af97da394dc5b","spanID":"d422721c37ff1571","transactionData":[{"eventType":"VALIDATION","eventDate":"2024-09-18T08:48:03.956+00:00","eventStatus":"SUCCESS","subject":"FSEPGL01E41A145J","organizzazione":"160","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.6777319a0e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","traceId":"6a58bc2004c322cb","issuer":"integrity:S1#160#REGIONEPUGLIATEST","expiringDate":"2025-09-18T08:48:03.964+00:00"},{"eventType":"PUBLICATION","eventDate":"2024-09-18T08:48:04.406+00:00","eventStatus":"SUCCESS","identificativoDocumento":"2.16.840.1.113883.2.9.2.120.4.4^290816","subject":"FSEPGL01E41A145J","tipoAttivita":"CON","organizzazione":"160","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.6777319a0e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","traceId":"24e066e35a648e3d","issuer":"integrity:S1#160#REGIONEPUGLIATEST","expiringDate":"2025-09-18T08:48:04.416+00:00"}]}`

In allegato:

- [auth-token.txt](https://github.com/user-attachments/files/17042246/auth-token.txt)
- [fse-jwt-token.txt](https://github.com/user-attachments/files/17042247/fse-jwt-token.txt)
- [output.pdf](https://github.com/user-attachments/files/17042248/output.pdf)

Chiediamo quindi se il codice fiscale sia stato censito correttamente o se la problematica dipende da altri fattori.

Grazie.

**Comment by g-maugeri-sogei** [comment]
Buonasera,
a noi risulta un soap fault quando INI chiama 160.
Se  siamo nel caso RDE=RDA=160, potete verificare se vi arriva la chiamata?
Altra cosa. Potete fornirci l'enpoint per il messaggio di comunicazione notifica metadati? 
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:wsrf-bf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsrf-r="http://docs.oasis-open.org/wsrf/r-2"><env:Header>
<wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
<wsa:Action>http://www.w3.org/2005/08/addressing/soap/fault</wsa:Action>
<wsa:MessageID>urn:uuid:da5afd5c-f44d-41b3-9a8c-403d3743084d</wsa:MessageID>
<wsa:RelatesTo>7a214551-92c9-464a-81f5-62e7dc4d506d</wsa:RelatesTo></env:Header><env:Body>
<env:Fault><env:Code>
<env:Value>env:Sender</env:Value></env:Code><env:Reason>
<env:Text xml:lang="en">
					env
				</env:Text></env:Reason><Detail xmlns="http://www.w3.org/2003/05/soap-envelope">
<wsrf-r:ResourceUnknownFault>
<wsrf-bf:Timestamp>2024-09-18T09:31:16.305Z</wsrf-bf:Timestamp>
<wsrf-bf:Description>
					Servizio non disponibile
				</wsrf-bf:Description></wsrf-r:ResourceUnknownFault></Detail></env:Fault></env:Body></env:Envelope>

**Comment by federicolau** [comment]
Grazie per la risposta.

abbiamo comunicato i nuovi endpoint che dovranno essere richiamati (quelli che avevamo fornito non erano validi).
Tuttavia, stiamo riscontrando alcuni problemi di irraggiungibilità per i quali stiamo già lavorando interamente affinchè vengano risolti.

**Comment by LucaRogledi** [comment]
Buonasera, ringraziamo per il feedback e le chiediamo gentilmente un nuovo riscontro a problema risolto. Grazie

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue. 
La informiamo che è possibile riaprirla nel caso in cui necessiti di ulteriore supporto. 
Grazie.
