### ISSUE TITLE
info validazione - documento CDA firmato Xades (e poi iniettato)

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#1005]
Buongiorno

E' possibile firmare XADES il documento CDA prima di iniettarlo nel referto? Il referto PDF così composto passerebbe la validazione?

**Comment by vigliottim** [comment]
Buongiorno, 
il documento può essere firmato con la firma PAdES, non XAdES.
Nel caso in cui effettuerà una validazione con un documento già firmato riceverà il seguente warning _"[SIGN_WARN - Attenzione il documento risulta firmato in validazione]"_.
Specifichiamo che è previsto che la firma PAdES venga applicata tra la validazione e la pubblicazione.
Pertanto, la firma applicata ad un file allegato in validazione, sebbene non produca un errore bloccante, determina il warning in questione.
Rimaniamo a disposizione per chiarimenti.

**Comment by ds-tommaso** [comment]
Con FSE1.0 - Puglia, ricevo l'errore "FSE-10001 - Il documento CDA non e' firmato digitalmente" quando il CDA non è firmato.

Di fatto, quando eseguo una addDocument devo:

1. produrre il documento CDA
2. firmare il documento CDA (Xades)
3. iniettare il documento CDA firmato nel PDF
4. firmare il nuovo PDF (Pades)

Con la domanda e nell'ottica di FSE2.0, mi chiedevo se la validazione fatta tra il punto 3 e 4 potesse produrre errore.

**Comment by vigliottim** [comment]
Per svolgere indagini più approfondite, potrebbe cortesemente inviarci un documento firmato XAdES? Grazie.

**Comment by ds-tommaso** [comment]
buonasera

eseguo delle verifiche interne - nel caso apro una nuova issue

**Comment by ds-tommaso** [comment]
Qui, un esempio di CDA firmato (specifiche tecniche Basilicata).

L'elemento _legalAuthenticator_ prevede un _signatureText_ tra _signatureCode_ e _assignedEntity_.

[cda_Referto_Firmato.xml.txt](https://github.com/user-attachments/files/17059352/cda_Referto_Firmato.xml.txt)

**Comment by vigliottim** [comment]
Buongiorno,
dalle verifiche effettuate, è emerso che il CDA2 presenta diversi errori di tipo semantico che non permettono la validazione.
Se necessita di alcuni esempi li può trovare al seguente link: [it-fse-support/doc/esempi/CDA at main · ministero-salute/it-fse-support (github.com)](https://github.com/ministero-salute/it-fse-support/tree/main/doc/esempi/CDA). 
Infine, secondo le [Linee Guida per l'attuazione di FSE 2.0](https://www.gazzettaufficiale.it/eli/id/2022/07/11/22A03961/sg) è ammessa solo la firma PAdES.

**Comment by ds-tommaso** [comment]
d'accord - sentirò le controparti. magari elimineranno la firma Xades del CDA con l'adozione del nuovo schema

ringrazio per la disponibilità
