### ISSUE TITLE
tracciato NotifyCommunicationMetadata - errore formale nella definizione del tipo ErrorType

### ISSUE THREAD

**Issue by andrea-elmi** [ministero-salute/it-fse-support#1008]
Buongiorno,
abbiamo notato un errore nel tracciato del servizio NotifyCommunicationMetadata condiviso nel file del crash program fase 2 (path crash_program.zip\Crash Program 2.0\Documentazione\Notifiche\wsdl.zip\wsdl\)

Lo schema  typeSchemaNotifyCommunicationMetadata.xsd contiene questa definizione:

```xml
  <xsd:complexType name="ErrorType">
		<xsd:attribute name="codeContext" maxOccurs="1" minOccurs="1" type="xsd:string" use="required"/>
		<xsd:attribute name="errorCode" maxOccurs="1" minOccurs="1" type="xsd:string" use="required"/>
	</xsd:complexType>
```

Generando gli stub java con questo schema, abbiamo i seguenti warning:

```
[WARNING] s4s-att-not-allowed: l'attributo 'maxOccurs' non può apparire nell'elemento "attribute".
  riga 20 di file:NotifyCommunicationMetadata/typeSchemaNotifyCommunicationMetadata.xsd

[WARNING] s4s-att-not-allowed: l'attributo 'minOccurs' non può apparire nell'elemento "attribute".
  riga 20 di file:NotifyCommunicationMetadata/typeSchemaNotifyCommunicationMetadata.xsd

[WARNING] s4s-att-not-allowed: l'attributo 'maxOccurs' non può apparire nell'elemento "attribute".
  riga 21 di file:NotifyCommunicationMetadata/typeSchemaNotifyCommunicationMetadata.xsd

[WARNING] s4s-att-not-allowed: l'attributo 'minOccurs' non può apparire nell'elemento "attribute".
  riga 21 di file:NotifyCommunicationMetadata/typeSchemaNotifyCommunicationMetadata.xsd
```
Gli stessi warning diventano errori bloccanti quando utilizziamo lo schema per configurare un interceptor di validazione per il servizio soap che esponiamo.

Si risolve eliminando gli attributi che danno errore

```xml
 <xsd:complexType name="ErrorType">
        <xsd:attribute name="codeContext"  type="xsd:string" use="required"/>
        <xsd:attribute name="errorCode" type="xsd:string" use="required"/>
</xsd:complexType>
```

Potete correggere il file originale?
grazie

**Comment by g-maugeri-sogei** [comment]
Buonasera,
abbiamo aggiornato il tracciato.

**Comment by andrea-elmi** [comment]
Grazie del feedback.
Colgo l'occasione di chiedere, se possibile, di condividere il tracciato aggiornato su github (magari con i tracciati degli altri servizi di tipo Notify che ho difficoltà a reperire in un luogo unico),
grazie

**Comment by g-maugeri-sogei** [comment]
Buongiorno, la versione ufficiale dei tracciati WSDL e relativi XSD del servizio di Notifica Comunicazione Metadati, andrebbero richiesti al DTD.

**Comment by LucaRogledi** [comment]
Buongiorno, procediamo con la chiusura della segnalazione e restiamo a disposizione in caso fosse necessario ulteriore supporto. Grazie
