### ISSUE TITLE
CRASH PROGRAM - Aggiornamento metadati - id metadati

### ISSUE THREAD

**Issue by angeloceloni** [ministero-salute/it-fse-support#1010]
Buongiorno
nella ITI-57 gli id dei vari metadati (Classification, ExternalIdentifier) sono valorizzati in parte con id simbolici ed in parte con UUID mentre, a quanto ci risulta dovrebbero essere id simbolici o comunque diversi da quelli restituiti dalla ITI-18.

**Comment by vigliottim** [comment]
Buongiorno, potrebbe fornirci un esempio di response completa comprensiva di traceid?
Grazie.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
La informiamo che sarà possibile riaprirla nel caso in cui abbia bisogno di ulteriore supporto.
Grazie.
