### ISSUE TITLE
CRASH PROGRAM - Aggiornamento metadati - Description

### ISSUE THREAD

**Issue by angeloceloni** [ministero-salute/it-fse-support#1011]
Buongiorno,
nella ITI-57 nel metadato XDSDocumentEntry.Slot – description non viene riportato il valore inviato al gateway nel campo descriptions

**Comment by IStacchiotti** [comment]
Buonasera, al fine di indirizzare correttamente la richiesta, le chiederemmo di:

1. fornirci una response completa comprensiva di traceid;
2. indicarci la Regione nel ruolo di RDA.

Grazie per la collaborazione

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue. 
La informiamo che è possibile riaprirla nel caso in cui necessiti di ulteriore supporto. 
Grazie.
