### ISSUE TITLE
The API Implementation is temporary unavailable

### ISSUE THREAD

**Issue by marco-volpe** [ministero-salute/it-fse-support#1013]
Buongiorno

è da questa mattina che notiamo l'errore in oggetto.

Avete informazioni su quando il Gateway di test sarà nuovamente disponibile?

Grazie

**Comment by vigliottim** [comment]
Buongiorno,
grazie per la segnalazione.
La informiamo che stiamo registrando dei disservizi e la invitiamo a monitorare il canale Slack per aggiornamenti in merito.
Grazie.
