### ISSUE TITLE
Dichiarazione versione equivalente non visibile

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#1014]
Buongiorno, qualche giorno fa ho eseguito una pull request https://github.com/ministero-salute/it-fse-accreditamento/pull/1621 per una versione equivalente ma, al contrario delle altre volte, non vedo niente nell'apposita pagina:
https://github.com/ministero-salute/it-fse-accreditati/blob/main/RESULTS/results.csv
L'unica comunicazione che ho ricevuto è un Merged.
Posso sapere se ci sono problemi o devo solo attendere?
Grazie mille.

**Comment by vigliottim** [comment]
Buongiorno,
grazie per la segnalazione.
La informiamo che la sua pull request è stata presa in carico e dovrà attendere per vedere i [results](https://github.com/ministero-salute/it-fse-accreditati/blob/main/RESULTS/results.csv) aggiornati.
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
