### ISSUE TITLE
Crash Program - Regione Molise - UC1 - Richiesta chiarimenti

### ISSUE THREAD

**Issue by marlagatta** [ministero-salute/it-fse-support#1016]
Salve, si é provveduto ad inviare un referto al gateway ottenendo come response

`HTTP/1.1 201 Created
X-Backside-Transport: OK OK
Connection: Keep-Alive
Transfer-Encoding: chunked
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
set-cookie: 894d46ecfc124039ee218b63c12a3329=9c62788caf0fe4a977db8e11a8d1653d; path=/; HttpOnly; Secure; SameSite=None
Server: GovWay-SOGEI
Pragma: no-cache
GovWay-Message-ID: 549349d6-9cce-4da7-9274-180a9db2039f
GovWay-Transaction-ID: 303ed310-7a84-11ef-b8bd-005056ae54fa
server-timing: intid;desc=e085826d76c19a1b
Date: Tue, 24 Sep 2024 14:56:24 GMT
Vary: *
X-Content-Type-Options: nosniff
Content-Type: application/json
X-Global-Transaction-ID: 6026e6bc66f2d317898c5b8f

{"traceID":"b8b62ce25407f5f4","spanID":"b8b62ce25407f5f4","workflowInstanceId":"2.16.840.1.113883.2.9.2.140.4.4.82683c378e3c77e42839bf1f447eea9bb923f34043f95f6521f51f500d33daf1.fa7e138c15^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}
`

Si rileva che non é stata ricevuta la comunicazione metadati per tramite di INI, 
ed effettuando il getStatus si é  ottenuto il response

`{
   "traceID": "3701117826105b8d",
   "spanID": "f2c98835ebd18d01",
   "transactionData":    [
            {
         "eventType": "VALIDATION_FOR_PUBLICATION",
         "eventDate": "2024-09-24T14:56:24.348+00:00",
         "eventStatus": "SUCCESS",
         "subject": "PRSTZN75L52B519D^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
         "organizzazione": "140",
         "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.82683c378e3c77e42839bf1f447eea9bb923f34043f95f6521f51f500d33daf1.fa7e138c15^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "traceId": "b8b62ce25407f5f4",
         "issuer": "integrity:S1#111ENGINNERING",
         "expiringDate": "2025-09-24T14:56:24.360+00:00"
      },
            {
         "eventType": "PUBLICATION",
         "eventDate": "2024-09-24T14:56:24.550+00:00",
         "eventStatus": "SUCCESS",
         "identificativoDocumento": "2.16.840.1.113883.2.9.2.140.4.4^ELIOT_202478965_1727188682402",
         "subject": "PRSTZN75L52B519D^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
         "tipoAttivita": "DIS",
         "organizzazione": "140",
         "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.82683c378e3c77e42839bf1f447eea9bb923f34043f95f6521f51f500d33daf1.fa7e138c15^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "traceId": "b8b62ce25407f5f4",
         "issuer": "integrity:S1#111ENGINNERING",
         "expiringDate": "2025-09-24T14:56:24.559+00:00"
      },
            {
         "eventType": "SEND_TO_INI",
         "eventDate": "2024-09-24T14:56:24.615+00:00",
         "eventStatus": "SUCCESS",
         "message": "Regime di mock abilitato",
         "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.82683c378e3c77e42839bf1f447eea9bb923f34043f95f6521f51f500d33daf1.fa7e138c15^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "expiringDate": "2025-09-24T14:56:24.678+00:00"
      }
   ]
}`

In particolare si richiede il significato del messaggio "Regime di mock abilitato" per l'event SEND_TO_INI,
da specifiche ci saremmo aspettati di ricevere i metadati direttamente da INI.

Grazie mille

**Comment by vigliottim** [comment]
Buongiorno,
le chiediamo se sta utilizzando i certificati ricevuti per Crash Program.
In caso contrario, la invitiamo a riprovare i certificati corretti.
Se non sono stati richiesti, per ottenerli può seguire la procedura descritta in documentazione al link: https://ministero-salute.github.io/it-fse-support/crashprogram/
Grazie.

**Comment by marlagatta** [comment]
Salve,

stamattina è stato effettuato un nuovo test con i certificati ricevuti per il Crash Program, 
la validazione ha avuto esito positivo, relativamente al 

`workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.82683c378e3c77e42839bf1f447eea9bb923f34043f95f6521f51f500d33daf1.1bc6d52348^^^^urn:ihe:iti:xdw:2013:workflowInstanceId`

ed anche il passo di create ha avuto esito positivo, relativamente al "traceID":"cefe5165e79a1fd2"

Ma effettuando la chiamata alla funzione status/{workflowInstanceId}, si riscontra un errore nell'evento "SEND_TO_INI", che qui riporto:
`{
         "eventType": "SEND_TO_INI",
         "eventDate": "2024-09-25T10:29:54.745+00:00",
         "eventStatus": "BLOCKING_ERROR",
         "message": "500 : \"{\"traceID\":\"1810731849247dac\",\"spanID\":\"1810731849247dac\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: Patient validation error Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}\"",
         "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.82683c378e3c77e42839bf1f447eea9bb923f34043f95f6521f51f500d33daf1.1bc6d52348^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "expiringDate": "2025-09-25T10:29:54.755+00:00"
      }
`

Il paziente utilizzato era uno dei due concordati per il Crash Program.
Potreste cortesemente darci un supporto?

Grazie mille

**Comment by vigliottim** [comment]
Buonasera,
potrebbe gentilmente riprovare?
Grazie.

**Comment by marlagatta** [comment]
Salve.
Riprovando si ha lo stesso errore.

`            {
         "eventType": "SEND_TO_INI",
         "eventDate": "2024-09-25T14:24:17.255+00:00",
         "eventStatus": "BLOCKING_ERROR",
         "message": "500 : \"{\"traceID\":\"f9f05af58c231c5c\",\"spanID\":\"f9f05af58c231c5c\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: Patient validation error Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}\"",
         "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.580867f1f583572c016763cffae448c86a2140ab6cb7e8f921db567f587160fc.d4194c1d9e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "expiringDate": "2025-09-25T14:24:17.319+00:00"
      }`

**Comment by ds-tommaso** [comment]
Ciao @marlagatta,

mi scuso per l'intromissione, ma il titolo dell'issue ha catturato la mia attenzione.

Vorremmo attivare la pubblicazione di referti lab/rad in Regione Molise per i clienti accreditati al SSN. Potrebbe fornirmi le specifiche di integrazione o un contatto a cui fare richiesta?

Ho già scritto a fse@regione.molise.it, ma non ho ricevuto risposta.

**Comment by g-maugeri-sogei** [comment]
Buonasera,
ieri ci sono stati disservizi sul nostro ambiente. Vi chiedo di riprovare.
In caso di errore, vi chiedo pure di indicarci CF dell'assistito utilizzato e il timestamp del tentativo.

**Comment by avlp** [comment]
> Ciao @marlagatta,
> 
> mi scuso per l'intromissione, ma il titolo dell'issue ha catturato la mia attenzione.
> 
> Vorremmo attivare la pubblicazione di referti lab/rad in Regione Molise per i clienti accreditati al SSN. Potrebbe fornirmi le specifiche di integrazione o un contatto a cui fare richiesta?
> 
> Ho già scritto a [fse@regione.molise.it](mailto:fse@regione.molise.it), ma non ho ricevuto risposta.

Salve,
la invito a contattare il direttore dei lavori FSE, ing. Nicola Zappone alla mail nicola.zappone@molisedati.it

**Comment by marlagatta** [comment]
Salve.

Riprovando oggi il caso di test per lo stesso paziente, la pubblicazione ha avuto di nuovo esito positivo, ma l'evento SEND_TO_INI ha restituito nuovamente l'errore boccante riscontrato il 25 settembre scorso, 

`            {
         "eventType": "SEND_TO_INI",
         "eventDate": "2024-09-30T12:26:39.959+00:00",
         "eventStatus": "BLOCKING_ERROR",
         "message": "500 : \"{\"traceID\":\"8e6e20904244e017\",\"spanID\":\"8e6e20904244e017\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: Patient validation error Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}\"",
         "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.d4451f2d3ae9f6536514548d3dc9cabb1cf0d58015695ebb1b7c39d2c094ec09.bacee4ee52^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "expiringDate": "2025-09-30T12:26:40.134+00:00"
      }
`
Potreste cortesemente assisterci nell'individuarne le cause?

Grazie mille
