### ISSUE TITLE
CRASH PROGRAM - Errore metadato creationTime

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#1018]
Buongiorno,
ci siamo accorti che il metadato creationTime non è compilato correttamente.
In particolare sembra coincidere con il submissionTime, ci aspettiamo che invece coincida con la data del documento. Proponiamo o la data della firma (se firmato) o effectiveTime del CDA2

A titolo ti esempio portiamo:
{"traceID":"45601d2417492dbd","spanID":"45601d2417492dbd","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.41201.4.4.1.87ec0918f5dec0f45e19d2e82833b2b92672f2a1f80f4799f734a439370aafee.db364aa729^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

CreationTime ricevuta sul registro -> 20240925071717
Data Firma -> 19.07.2024 16:53:00 (UTC)
effectiveTime del CDA -> "20240719164642+0200"

Grazie

**Comment by vigliottim** [comment]
Buonasera,
è stato rilasciato un aggiornamento.
Potreste cortesemente riprovare e darci un riscontro?
Grazie.

**Comment by SonnyMate** [comment]
Ok, per documentazione che data avete deciso di usare?

**Comment by LucaRogledi** [comment]
Buongiorno, è stato utilizzato il campo del cda "ClinicalDocument > effectiveTime".

**Comment by SonnyMate** [comment]
OK, Grazie
