### ISSUE TITLE
Richiesta oscuramento dati

### ISSUE THREAD

**Issue by rondellimediam** [ministero-salute/it-fse-support#1019]
Buongiorno, volevo sapere se nel CDA è presente un campo che indica la volontà del paziente di oscurare i propri dati. Se sì, avrei bisogno delle specifiche per compilarlo. Grazie!

**Comment by vigliottim** [comment]
Buonasera,

all’interno del documento CDA2 può esplicitare il _Grado di Riservatezza_ del documento che discrimina la tipologia dello stesso.
In particolare:
- **_N, “Normal”_**: questo livello di riservatezza può essere associato a documenti che contengono dati sanitari di varia natura;
- _**V, “Very Restriced”**_: questo livello di riservatezza può essere associato a documenti che contengono dati sanitari fortemente confidenziali.
 
Non viene esplicitata la volontà del paziente di oscurare i propri dati. 
Infine, da IG HL7 ITALIA si riporta che:
 “Le informazioni riportate nel _confidentialityCode_, che sono di tipo statico, non necessariamente coincidono con le impostazioni dinamiche inerenti all’oscuramento e alla consultazione del documento che verranno definite a livello di servizi”.

Inoltre, come descritto in Affinity Domain V2.5, per il metadato _XDSDocumentEntry.eventCodeList_, si ha che:
 “La politica di visibilità può essere specificata dall’assistito all’atto della creazione del documento, al momento del contatto con la struttura della RDE, e inoltre, l'assistito potrà modificare (o richiedere di modificare) l'oscuramento di un proprio documento in una fase successiva”.

Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
Grazie.
