### ISSUE TITLE
Info GTW Lazio

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#1020]
Buongiorno 

Conclusa la fase di collaudo con il middleware regionale, abbiamo fatto richiesta del certificato di un cliente. 

Con l'endpoint di produzione, riesco a validare il referto. 

Posso già procedere con la pubblicazione? Se si, il referto sarà effettivamente inviato al FSE degli assistiti, siano essi Inter o extra regionali?

**Comment by vigliottim** [comment]
Buongiorno,
l'endpoint di produzione con cui riesce a validare il referto si riferisce a FSE 1.0?
Grazie.

**Comment by ds-tommaso** [comment]
https://fse-services.regione.lazio.it/fse-middleware/gateway/v1/documents/validation

`
{
    "timestamp": "2024-09-25T13:00:44.1764379+02:00",
    "traceID": "202409251300449b",
    "spanID": "202409251300449b",
    "status": 200,
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.0.20240925130044.eb7ee024^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
`

**Comment by ds-tommaso** [comment]
https://fse-services.regione.lazio.it/fse-middleware/gateway/v1/documents/validation

```
{
    "timestamp": "2024-09-25T13:00:44.1764379+02:00",
    "traceID": "202409251300449b",
    "spanID": "202409251300449b",
    "status": 200,
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.0.20240925130044.eb7ee024^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```

**Comment by vigliottim** [comment]
Buonasera,
poiché il gateway non è in produzione, è possibile chiamare i servizi di validazione e/o pubblicazione in testing.
Pertanto, il referto pubblicato non sarà effettivamente inviato al FSE degli assistiti ma agli ambienti di test.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by ds-tommaso** [comment]
okay, grazie - nel mentre che attendevo, ho eseguito una prova con un mio referto.
Sono riuscito ad avere esito OK dalla pubblicazione seppur non fosse disponibile sul mio profilo FSE.
Anche lo status tramite tramite workflowistanceid non ha prodotto alcun risultato.
Per sicurezza, l'ho cancellato.

Ad ogni modo, i clienti hanno ricevuto una mail in cui FSE sarà obbligatorio entro aprile 2025.
Non abbiamo mai sviluppato servizi FSE1.0 in questa regione: contate di mettere in produzione il gateway per tale data?

**Comment by vigliottim** [comment]
La ringraziamo per il feedback.
Al momento non sono disponibili informazioni in merito alla sua ultima richiesta.
Eventuali aggiornamenti saranno pubblicati sui canali dedicati.
