### ISSUE TITLE
CRASH PROGRAM - Non riceviamo le chiamate

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#1021]
Buongiorno,
da questo pomeriggio su alcuni servizi non riceviamo più le chiamate da INI.
Il gateway ci risponde:
{
    "traceID": "9f463c03e7557ad2",
    "spanID": "bab0e19bd5bd29b6",
    "type": "/errors",
    "title": "Generic",
    "detail": "RDA generated an internal error.",
    "instance": "error/generic"
}

Questo vale per replace, delete e metada update

GRazie

**Comment by vigliottim** [comment]
Buonasera,
potreste indicare quale RDA state cercando di contattare?
Grazie.

**Comment by SonnyMate** [comment]
Sempre la nostra 041

**Comment by g-maugeri-sogei** [comment]
Buonasera,
ieri ci sono stati disservizi sul nostro ambiente. 
Al momento l'ambiente di Interoperabilita' e' disponibile solo per chiamate tra regioni non in sussidiarieta'.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue. La informiamo che sarà possibile riaprirla nel caso in cui abbia bisogno di ulteriore supporto. Grazie
