### ISSUE TITLE
errore parsing data

### ISSUE THREAD

**Issue by izamberlan** [ministero-salute/it-fse-support#1022]
Buongiorno, da stamattina (o da ieri pomeriggio) abbiamo un problema di parsing di una data nei metadati inviati da GW/INI al nostro nodo regionale - dato che ieri, per altra issue, è stata modificata la modalità con cui il gateway popola la data di creazione del documento, ci chiediamo se non ne sia stato incidentalmente modificato il formato.

grazie

**Comment by vigliottim** [comment]
Buongiorno,
potrebbe gentilmente allegare la response completa?
Grazie.

**Comment by izamberlan** [comment]
allego la response
[resp.txt](https://github.com/user-attachments/files/17147822/resp.txt)

**Comment by FSESardegna** [comment]
Buongiorno,
anche noi come Regione Sardegna stiamo riscontrando il medesimo errore.
Rimaniamo in attesa di un vostro riscontro,
Grazie

**Comment by vigliottim** [comment]
Buonasera,
è stato rilasciato un aggiornamento.
Le chiediamo cortesemente di riprovare e darci un riscontro.
Grazie.

**Comment by izamberlan** [comment]
La data sembra OK, abbiamo un problema in ambiente di test che ci impedisce al momento di dare una risposta definitiva. Ripetiamo la prova appena possibile.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
La invitiamo a riaprirla nel caso in cui dovesse avere bisogno di supporto.
Grazie.

**Comment by izamberlan** [comment]
confermiamo che ora la pubblicazione passa

**Comment by izamberlan** [comment]
Confermiamo che il problema è risolto dal nostro punto di vista.
