### ISSUE TITLE
Validazione

### ISSUE THREAD

**Issue by gruppomaxed** [ministero-salute/it-fse-support#1024]
Buongiorno da ieri inviando richiesta di Validazione  ottengo questa risposta
{"traceID":"99d15a45ffaa13e3","spanID":"99d15a45ffaa13e3","type":"/msg/generic-error","title":"Errore generico.","detail":"it.finanze.sanita.fse2.ms.gtw.dispatcher.exceptions.BusinessException: it.finanze.sanita.fse2.ms.gtw.dispatcher.exceptions.BusinessException: java.util.concurrent.ExecutionException: org.springframework.kafka.core.KafkaProducerException: Failed to send; nested exception is org.apache.kafka.common.errors.NotEnoughReplicasException: Messages are rejected since there are fewer in-sync replicas than required.","status":500,"instance":""} 
sapreste indicarmi dovè l'errore o cosa significa.
Grazie

**Comment by vigliottim** [comment]
Buongiorno, 
stiamo registrando dei temporanei disservizi. 
La informeremo non appena si avranno aggiornamenti.
Grazie.

**Comment by vigliottim** [comment]
Potrebbe cortesemente riprovare e darci un feedback?
Grazie.

**Comment by gruppomaxed** [comment]
Ora risulta funzionante ho inviato 
Response Content: {"traceID":"b21f3424127e1368","spanID":"b21f3424127e1368","workflowInstanceId":"2.16.840.1.113883.2.9.2.80.3.1.4.4.1142d4ef95daa6992373c1db873c8bb96c83c2731e0535751042bd46bab8e36a.2efb7b5503^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","warning":"[W005 | Sezione Esame Eseguito: l'entry/act/code può essere valorizzato secondo i sistemi di codifica\n\t\t\tLOINC @codeSystem='2.16.840.1.113883.6.1'\n\t\t\tICD-9-CM @codeSystem='2.16.840.1.113883.6.103'],[W005 | Sezione Esame Eseguito: l'entry/act/code può essere valorizzato secondo i sistemi di codifica\n\t\t\tLOINC @codeSystem='2.16.840.1.113883.6.1'\n\t\t\tICD-9-CM @codeSystem='2.16.840.1.113883.6.103']"}
Response Status: OK 

aggiungo una domanda per il Worning W005  IDC-9 .   Per l'accreditamento è essenziale che sia compilato o si può evitare?
Grazie

**Comment by vigliottim** [comment]
Per le specifiche richieste per l'accreditamento deve far riferimento ai test case contenuti nella cartella [test-case-validazione](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione).
Infatti, l'accreditamento prevede dei controlli più stringenti rispetto a quelli previsti in validazione.
Pertanto, non è detto che ad un esito positivo da parte del Gateway (con o senza warning) corrisponderà ad un esito positivo in fase di accreditamento.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by gruppomaxed** [comment]
Ok grazie
