### ISSUE TITLE
FSE 2.0 - VALIDAZIONE CDA ERRORE 400

### ISSUE THREAD

**Issue by alessiopiccioni1981** [ministero-salute/it-fse-support#1025]
Buongiorno
durante la fase di validazione con gateway nazionale ottengo il seguente errore, avete qualche indicazione in più in merito a questo errore?

{\"traceID\":\"2e11c04a832e3602\",\"spanID\":\"2e11c04a832e3602\",\"type\":\"/msg/cda-element\",\"title\":\"Errore in fase di estrazione del CDA.\",\"detail\":\"Error while extracting CDA from PDF document\",\"status\":400,\"instance\":\"/cda-extraction\",\"workflowInstanceId\":\"UNKNOWN_WORKFLOW_ID\"}\n\tat i.e.h.b.f.s.c.FseSogeiRequestException.exceptionFromCode(FseSogeiRequestException.java:68)\n\tat i.e.h.b.f.s.c.FSEClientExceptionFactory.getException(FSEClientExceptionFactory.java:15)\n\tat i.e.h.b.f.s.c.FSEClientRestErrorHandler.handleError(FSEClientRestErrorHandler.java:55)\n\tat o.s.w.c.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat o.s.w.c.ResponseErrorHandler$$FastClassBySpringCGLIB$$5470f765.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:752)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.i.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)\n\tat i.e.h.b.f.s.c.FSEClientRestErrorHandler$$EnhancerBySpringCGLIB$$402234f2.handleError(<generated>)\n\tat o.s.w.c.RestTemplate.handleResponse(RestTemplate.java:774)\n\tat o.s.w.c.RestTemplate.doExecute(RestTemplate.java:732)\n\tat o.s.w.c.RestTemplate.execute(RestTemplate.java:666)\n\tat o.s.w.c.RestTemplate.exchange(RestTemplate.java:604)\n\tat i.e.h.b.f.s.s.FSEGatewayServiceImpl.validateDocument(FSEGatewayServiceImpl.java:174)\n\tat i.e.h.b.f.s.s.FSEGatewayServiceImpl$$FastClassBySpringCGLIB$$d19562b5.invoke(<generated>)\n\tat o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)\n\tat o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:752)\n\tat o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat o.s.a.f.a.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdvi...\n"}

**Comment by LucaRogledi** [comment]
Buongiorno, 
dalle analisi sulla chiamata effettuata risulta che il pdf contiene il cda iniettato in modalità resource, mentre il parametro `"mode"` della requestBody è stato valorizzato con `"ATTACHMENT"`.
La invitiamo a modificare la requestBody della chiamata utilizzando `"mode":"RESOURCE"` e riprovare.
Grazie

**Comment by alessiopiccioni1981** [comment]
ok grazie mille del riscontro, proviamo a rismulare con questa modalità

Buon lavoro

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
La invitiamo a riaprirla nel caso in cui dovesse avere bisogno di supporto.
Grazie.
