### ISSUE TITLE
Crash-program, Test pubblicazione documento regione Abruzzo

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#1026]
buonasera,
ho pubblicato oggi un documento con esito positivo alle 11:42 utilizzano i servizio comunicazioneMetati (regione Abruzzo)
se interrogo lo status del Gtw , nella risposta non risulta la pubblicazione

```
{
"spanID": "53c47f61e67787a9",
"traceID": "c004bd6bd4415d56",
"transactionData":
    [
        {
        "eventDate": "2024-09-27T09:42:01.186+00:00",
        "eventStatus": "SUCCESS",
        "eventType": "VALIDATION",
        "expiringDate": "2025-09-27T09:42:01.417+00:00",
        "issuer": "integrity:S1#130#ABRUZZO_ASL1_TEST",
        "organizzazione": "130",
        "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
        "traceId": "658ccc65846f39e0",
        "workflowInstanceId": "2.16.840.1.113883.2.9.2.130202.4.4.51102bf12cf33dee565e07ed2f3887ef53baf8d1c21bf8673f0121a1b77d31c2.8fd57a0006^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
        }
    ]
}
```

Come mai?

**Comment by LucaRogledi** [comment]
Buongiorno, potrebbe fornirci la response completa ricevuta dalla chiamata di pubblicazione ? Grazie

**Comment by alessandropassamonti** [comment]
```

<?xml version="1.0" encoding="utf-16"?>
<ComunicazioneMetadatiRicevuta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Esito xmlns="http://comunicazionemetadatiricevuta.xsd.fse.ini.finanze.it">0000</Esito>
  <ElencoErrori xmlns="http://comunicazionemetadatiricevuta.xsd.fse.ini.finanze.it">
    <Errore xmlns="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it">
      <codEsito>0000</codEsito>
      <esito>Operazione eseguita correttamente</esito>
      <tipoErrore>Success</tipoErrore>
      <fonte>FSE-INS-FE</fonte>
    </Errore>
  </ElencoErrori>
  <IdentificativoDocumento xmlns="http://comunicazionemetadatiricevuta.xsd.fse.ini.finanze.it">TEMP_130_2323864</IdentificativoDocumento>
</ComunicazioneMetadatiRicevuta>
```

**Comment by LucaRogledi** [comment]
Potrebbe gentilmente fornirci la risposta del gateway ottenuta in seguito alla pubblicazione e contenente govway_id, traceID, workflowinstanceId se disponibili? Grazie

**Comment by alessandropassamonti** [comment]
non ho queste informazioni perchè ho usato il servizio in sussidiarietà ComunicazioneMetdati come specificato da precedente mail di Sogei che afferma che per la creazione/sostituzione documento bisogna invocare FSE-INI


> Fondamentalmente se si invoca una comunicazione metadati o una replace , dopo aver effettuato la fase di validazione verso il gateway ed essere andata a buon fine, dovete invocare il servizio di comunicazione o di replace (a seconda) che risponde sempre alla stessa url e con le caratteristiche indicate nel documento di specifica, questo è necessario perché poi sarà il sistema centrale della sussidiarietà ad occuparsi della fase di pubblicazione per questi due servizi.
> 
> Se invece dovete invocare i restanti servizi (aggiornamento, cancellazione) dovete colloquiare direttamente con il Gateway
>

**Comment by LucaRogledi** [comment]
Buonasera, 
La pubblicazione potrebbe non essere presente in quanto è INS che effettua la richiesta, prima che la pubblicazione venga effettuata dal Gateway.
Dato che sta passando per i servizi di sussidiarietà le segnaliamo che è necessario contattare il servizio di esitoCaricamentoDocumento invece del servizio di status del Gateway, per conoscere lo stato della pubblicazione. 
Grazie

**Comment by alessandropassamonti** [comment]
purtroppo esitoCaricamentoDocumento  mi restituisce sempre lo stato ELAB, per questo ho provato a vedere se avevo qualche informazione con status del Gtw. Quindi c'è qualche problema con INS? Questo purtroppo blocca l'esecuzione dei test

**Comment by LucaRogledi** [comment]
Buonasera, 
dalle nostre analisi non risultano comunicazioni in quanto sembrerebbe che la richiesta è ferma su un altro sistema. Essendo regione in sussidiarietà la invitiamo a contattare il servizio di esitoCaricamentoDocumenti per la verifica dello stato. 
Per maggiori informazioni può contattare direttamente gestionets@sogei.it.
Grazie

**Comment by g-maugeri-sogei** [comment]
Buonasera,
potete fornirci il CF dell'assistito utilizzato nel tentativo sopra riportato (timestamp 2024-09-27T09:42:01.186+00:00) ?

**Comment by alessandropassamonti** [comment]
buonasera,
DNNBZZ60A43A345K

**Comment by g-maugeri-sogei** [comment]
Buonasera,
potete ripetere il test ?

**Comment by alessandropassamonti** [comment]
eseguito un nuovo test ma l'esitocaricamento restituisce sempre ELAB

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
le informazioni che vengono passate in fase di pubblicazione non sono complete.
Questo l'errore che INS riceve dal GTW in fase di pubblicazione.

= {"traceID":"6091d8d3b0bcb70f","spanID":"6091d8d3b0bcb70f","type"
:"/msg/jwt-validation","title":"Campo token JWT non valido.","detail":"Il campo Locality non è valorizzato correttamente","status":403,"instance":"/jwt-mandatory-field-malfo
rmed"}

**Comment by alessandropassamonti** [comment]
Buongiorno,
qual è il problema?
nell'attributo locality è stato passato il valore
PRONTO SOCCORSO DEMO VST^^^^^&2.16.840.1.113883.2.9.4.1.3&ISO^^^^130204123457
formattato come indicato nella documentazione

**Comment by g-maugeri-sogei** [comment]
Stiamo verificando internamente.

**Comment by LucaRogledi** [comment]
Buon pomeriggio @alessandropassamonti, verificando il token di signature utilizzato per la chiamata indicata "traceID":"6091d8d3b0bcb70f", il campo locality risulta valorizzato con "locality": "204123456". 

![image](https://github.com/user-attachments/assets/57945b79-8f3b-4057-bb89-3519c710db54)

La invitiamo a riprovare utilizzando una valorizzazione corretta per il campo locality, come da lei indicata e riportata in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt). Grazie

**Comment by alessandropassamonti** [comment]
Buongiorno,
questo traceid non mi risulta comunque i test fatti dal 30/09 in poi hanno la locality formattata correttamente.
Questo è il token della pubblicazione fatta poco fa e la locality è corretta

```
{
  "iss": "integrity:S1#130#ABRUZZO_ASL2_TEST",
  "iat": "1728305536",
  "exp": "1728306136",
  "jti": "46035ccc-4296-4b02-aa79-05a43eaecdf7",
  "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
  "sub": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "subject_organization_id": "130",
  "subject_organization": "Regione Abruzzo",
  "locality": "OSPEDALE CLINICIZZATO - SS.ANNUNZIATA CHIETI (EC)^^^^^&2.16.840.1.113883.2.9.4.1.3&ISO^^^^130202130026",
  "subject_role": "DRS",
  "person_id": "DNNBZZ60A43A345K^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "patient_consent": "true",
  "purpose_of_use": "TREATMENT",
  "action_id": "CREATE",
  "subject_application_id": "SISWeb",
  "subject_application_vendor": "IASI S.r.l",
  "subject_application_version": "2.4.8",
  "resource_hl7_type": "('11488-4^^2.16.840.1.113883.6.1')",
  "attachment_hash": "3f3c6488b637a3056ec9db96add098ffbe7c9390a6cb730a949d9b00d17f2566"
}
```
"traceID":"d527831bddd3eaa0"
"workflowInstanceId":"2.16.840.1.113883.2.9.2.130202.4.4.1d1121b383b144b2d689b272aded1f3fd965a0fcdf036210452e33c9dd63e8c5.3fb5dd2670^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"

Lo stato restituito da esitoCaricamento è in ELAB

**Comment by alessandropassamonti** [comment]
buongiorno,
anche oggi esitoCaricamento rimane in ELAB

**Comment by vigliottim** [comment]
Buonasera,
le chiediamo gentilmente di effettuare un nuovo test e darci un riscontro.
Grazie.

**Comment by alessandropassamonti** [comment]
buongiorno,
l'esito caricamento rimane in stato ELAB. Il documento è stato pubblicato ieri.

IDENTIFICATIVOASSISTITO:    DNNBZZ60A43A345K  
IDENTIFICATIVOTEMPORANEODOC : TEMP_130_2372992
WORKFLOWINSTANCEID: 2.16.840.1.113883.2.9.2.130202.4.4.4168c5ec0c08c6b3de1e691b2d1e916f790eb7dfa058cd00d6ae4f0639756ea1.588ef10a1d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
TRACEID: 25acee51af3b084c 
SPANID: 25acee51af3b084c

**Comment by g-maugeri-sogei** [comment]
Buongiorno, 
per indagare il problema ci occorre loggare maggiori informazioni. Potete svolgere un nuovo tentativo  e darci riscontro ?

**Comment by alessandropassamonti** [comment]
Fatto,

> Gtw response:
> `{"spanID":"d36c1457542dcfba","traceID":"d36c1457542dcfba","workflowInstanceId":"2.16.840.1.113883.2.9.2.130202.4.4.fdf05e9e5a4d50b5596cac465c6b9f8e2d95685c0ae14c312a89db19bda3b356.c84e25a609^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","Success":true}`
> 

> Dati di pubblicazione
> IDENTIFICATIVOASSISTITO: DNNBZZ60A43A345K
> IDENTIFICATIVOTEMPORANEODOC : TEMP_130_2373049
> 

La pubblicazione è stata seguita con il servizio comunicazioneMetadati di FSE 1.0 come da indicazioni di sogei

Grazie

**Comment by vigliottim** [comment]
Grazie per il gentile feedback.
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per altre richieste di supporto.

**Comment by alessandropassamonti** [comment]
scusate ma non è completato, mi avete chiesto di riprovare

**Comment by alessandropassamonti** [comment]
scusate ma non è completato, mi avete chiesto di riprovare, il problema c'è ancora



[cid:44a21d4e-2c68-4ec9-b032-8f731c51056b]

[cid:c0ad1da0-9991-4919-9804-643efd653230]<https://mapsgroup.it/>

HEALTHCARE MARKET

ALESSANDRO PASSAMONTI

Software Developer


E: ***@***.***

T: +39 0854458739

iasi.it<https://www.iasi.it/it/> company of mapsgroup.it





MAPS S.p.A.

Sede Legale:

Via Paradigna 38/A, 43122 Parma (PR)

C.F. e P.IVA 01977490356

Iasi S.r.l.

Società soggetta a direzione e coordinamento Artexe S.p.A.

Sede Operativa:

C.so Umberto I 332, 65015 Montesilvano (PE)
C.F. e P.IVA 01114770660

Segui Maps Group:


 [cid:c81ce270-7490-4a29-9b48-829b86c89388] </Users/alegiu/Desktop/Maps%20Group/mapsgroup.it>                        [cid:a75041b7-0f3f-4ed1-a6cb-c29f9c1e5fcc] <https://it.linkedin.com/company/maps-group>        [cid:362c345f-e532-4940-8d25-e6f71208827c] <https://twitter.com/MapsGroup>        [cid:f3474540-dad2-4fd2-8665-6138382cbff2] <https://www.facebook.com/pagesMapsGroup/>


Segui Iasi:


[cid:807a3e27-baa3-46a0-8f53-9d0764af5829]<https://www.iasi.it/it/>       [cid:276b6f28-2a4c-4137-8e88-1a001ed78a37] <https://www.linkedin.com/company/artexe/about/>        [cid:3828625a-b009-42ca-a93f-de2caf628611] <https://twitter.com/ArtexeHealth>       [cid:1c82e5de-901d-4339-9e66-99b7678da52a] <https://www.facebook.com/ArtexeHealth/>        [cid:1402c33a-8d51-45da-8acb-72eac7620d5f] <https://www.youtube.com/channel/UCIvImbrm7J2oBdXj5KEFPaA>



[Immagine che contiene testo  Descrizione generata automaticamente]





AVVISO DI RISERVATEZZA PER LA POSTA ELETTRONICA / CONFIDENTIALITY NOTICE

Le informazioni contenute nella presente comunicazione sono di carattere strettamente confidenziale e sono riservate alla sola persona o società identificata come destinataria. Nel caso non siate la persona destinataria, vi informiamo che ogni divulgazione, copia o azione intrapresa sulla base delle informazioni contenute nella presente mail è vietata e sarà perseguita nei termini di legge. Qualora riceviate questa mail per errore, siete pregati di darcene immediata comunicazione rispondendo a questo stesso indirizzo e di cancellarla definitivamente dal vostro computer, pena la violazione della normativa vigente.



The contents of this message, as well as any enclosures, are addressed personally to the addressee. They may contain information regarding a third party. A recipient who is neither the addressee, nor empowered to receive this message on behalf of the addressee, is kindly requested to immediately inform the sender of receipt replying to this e-mail and to delete it from your system. Any use of the contents of this message and/or of the enclosures by any other person than the addressee is illegal towards the sender and the aforementioned third party.





________________________________
Da: Michela Vigliotti ***@***.***>
Inviato: giovedì 10 ottobre 2024 12:06
A: ministero-salute/it-fse-support ***@***.***>
Cc: Alessandro Passamonti ***@***.***>; Mention ***@***.***>
Oggetto: [External] Re: [ministero-salute/it-fse-support] Crash-program, Test pubblicazione documento regione Abruzzo (Issue #1026)


Grazie per il gentile feedback.
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per altre richieste di supporto.

**Comment by g-maugeri-sogei** [comment]
Buonasera, 
sembra esserci lato nostro una corsa critica causata dal fatto che inviate una nuova richiesta di pubblicazione con lo stesso codice documento prima che la precedente completi. In attesa di risolvere il problema vi chiedo di attendere il completamento (esito OK o KO) di una richiesta richiesta di pubblicazione prima di procedere a una successiva. Se vi occorre lanciare chiamate in parallelo usate documenti diversi. Ho bonificato la base dati, vi chiedo di riprovare e darmi riscontro.

**Comment by alessandropassamonti** [comment]
i documenti che pubblico dovrebbero avere tutti codici diversi perchè sono tutti nuovi referti (nessuna sostituzione)
a quale codice documento si riferisce? mi può indicare il valore?

**Comment by g-maugeri-sogei** [comment]
La pubblicazione e' andata. Ho perso i riferimenti dei vecchi documenti.

**Comment by g-maugeri-sogei** [comment]
Se possibile svolgete piu' tentativi (con documenti diversi) perche' non mi e' completamente chiaro cosa sia successo con i precedenti tentativi.

**Comment by alessandropassamonti** [comment]
confermo che la pubblicazione ha dato esito OK
{
"spanID": "ef305b06dd101041",
"traceID": "783e1267477e197f",
"transactionData":
    [
        {
        "eventDate": "2024-10-10T15:39:03.202+02:00",
        "eventStatus": "SUCCESS",
        "eventType": "VALIDATION",
        "expiringDate": "2025-10-10T15:39:03.216+02:00",
        "issuer": "integrity:S1#130#ABRUZZO_ASL2_TEST",
        "organizzazione": "130",
        "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
        "traceId": "16eecc17911dc45b",
        "workflowInstanceId": "2.16.840.1.113883.2.9.2.130202.4.4.2ee9bbbf4cfdeb952db95c76c3fabade36087b53c4d504567f57ed1492e6c1b6.363fc1509b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
        },
        {
        "eventDate": "2024-10-10T15:53:09.747+02:00",
        "eventStatus": "SUCCESS",
        "eventType": "PUBLICATION",
        "expiringDate": "2025-10-10T15:53:09.756+02:00",
        "identificativoDocumento": "2.16.840.1.113883.2.9.2.130.4.4^497136",
        "issuer": "integrity:S1#130#Middleware130",
        "organizzazione": "130",
        "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
        "tipoAttivita": "ERP",
        "traceId": "ca74c9c03b8a5f17",
        "workflowInstanceId": "2.16.840.1.113883.2.9.2.130202.4.4.2ee9bbbf4cfdeb952db95c76c3fabade36087b53c4d504567f57ed1492e6c1b6.363fc1509b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
        },
        {
        "eventDate": "2024-10-10T15:53:11.673+02:00",
        "eventStatus": "SUCCESS",
        "eventType": "SEND_TO_INI",
        "expiringDate": "2025-10-10T15:53:11.805+02:00",
        "workflowInstanceId": "2.16.840.1.113883.2.9.2.130202.4.4.2ee9bbbf4cfdeb952db95c76c3fabade36087b53c4d504567f57ed1492e6c1b6.363fc1509b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
        }
    ]
}

Verrà mandata una comunicazione al referente regionale?

**Comment by g-maugeri-sogei** [comment]
Buongiorno, 
il problema non e' ancora risolto.
Potete allegare qui la chiamata con cui verificate l'esito della pubblicazione ?
Mi occorre pure l'endpoint e il timestamp della chiamata.

**Comment by alessandropassamonti** [comment]
esitoCaricamentoDocumento 2024-10-10T16:03:55

endpoint: https://fseservicetest.sanita.finanze.it/FseInsServicesWeb/services/fseEsitoCaricamentoDocumento


```
<EsitoCaricamentoDocumentoRichiesta >
  <IdentificativoUtente >PROVAX00X00X000Y</IdentificativoUtente>
  <pinCode >XiyGHtg908TS2CwrmpCWdNB5nL0hxDLKQNV7r6FUHtRXJHSOpm2NIPzobCESwD6d
D0aF9t0PaDNqjFaB/wCeCLHz1M9wt6xjxQ9Po7wjTmPNnGJkBX0ZKROpG3x4cSd8
+Uh9fV858BbEl0H25VCH6x+tV0jrdcon+Dz98R9PSr8=
</pinCode>
  <IdentificativoOrganizzazione >130</IdentificativoOrganizzazione>
  <StrutturaUtente >202123456</StrutturaUtente>
  <RuoloUtente >DRS</RuoloUtente>
  <IdentificativiTemporaneiDocumenti >TEMP_130_2373070</IdentificativiTemporaneiDocumenti>
  <DataRicercaDA >20241010154000</DataRicercaDA>
  <DataRicercaA >20241010154000</DataRicercaA>
</EsitoCaricamentoDocumentoRichiesta>

```

```
<EsitoCaricamentoDocumentoRicevuta ">
  <Esito >0000</Esito>
  <EsitoCaricamentoDocumento >
    <IdentificativoTemporaneoDocumento >TEMP_130_2373070</IdentificativoTemporaneoDocumento>
    <StatoElaborazione >OK</StatoElaborazione>
    <IdentificativoDocumento >2.16.840.1.113883.2.9.2.130.4.4^497136</IdentificativoDocumento>
  </EsitoCaricamentoDocumento>
  <ElencoErrori >
    <Errore >
      <codEsito>0000</codEsito>
      <esito>Operazione eseguita correttamente</esito>
      <tipoErrore>Success</tipoErrore>
      <fonte>FSE-INS-FE</fonte>
    </Errore>
  </ElencoErrori>
</EsitoCaricamentoDocumentoRicevuta>
```

**Comment by alessandropassamonti** [comment]
buongiorno, 
ci sono delle novità? devo aggiornare i referenti regionali per il sal di questo pomeriggio

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
stiamo ancora indagando il problema.

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
il problema e' stato risolto.

**Comment by alessandropassamonti** [comment]
buongiorno,
posso considerare il documento pubblicato?

**Comment by g-maugeri-sogei** [comment]
Se vi occorre un documento per ulteriori test meglio rifare la pubblicazione.

**Comment by alessandropassamonti** [comment]
buongiorno
ho fatto una nuova pubblicazione ma lo stato rimane in ELAB

> workflowInstanceId: 2.16.840.1.113883.2.9.2.130202.4.4.fc1538aac55b643f75c6a4ad86df40c2263dd4b6ecbf2e8a967ef99d9a96a151.dde5b571a9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

```
esitoCaricamentoRichiesta:
<EsitoCaricamentoDocumentoRichiesta >
  <IdentificativoUtente >PROVAX00X00X000Y</IdentificativoUtente>
  <pinCode >qkmVJEixQ1REhUvImCWG96H8sH0iMJovBuXbXg4XjdYXkla5dFRetD6E3Io3E1Jn
tKLJjE/DEtc/s60qIu35owdhzgMoVWcyuyUziYbwMETmqgug1HM4/pu6bch+k7By
7FwQGWi4Y2Y8qNKguhytQVHlMLygF/DAair9MIFJyfU=
</pinCode>
  <IdentificativoOrganizzazione >130</IdentificativoOrganizzazione>
  <StrutturaUtente >202123456</StrutturaUtente>
  <RuoloUtente >DRS</RuoloUtente>
  <IdentificativiTemporaneiDocumenti >TEMP_130_2377185</IdentificativiTemporaneiDocumenti>
  <DataRicercaDA >20241023103000</DataRicercaDA>
  <DataRicercaA >20241023103000</DataRicercaA>
</EsitoCaricamentoDocumentoRichiesta>
```
Grazie

**Comment by g-maugeri-sogei** [comment]
Buonasera, 
potere effettuare un nuovo tentativo?

**Comment by alessandropassamonti** [comment]
Buonasera,
fatto e l'esito è OK. Posso considerarlo correttamente pubblicato?

**Gwt**

`{"spanID":"6cccec9264c7b978","traceID":"6cccec9264c7b978","workflowInstanceId":"2.16.840.1.113883.2.9.2.130202.4.4.af40962fdbdd5393082721d07089b0b64d23b5a431dfbc9ff61b74fea5a5f0ff.2228d15618^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","Success":true}
`

**esitocaricamentoDocumento**

```
<EsitoCaricamentoDocumentoRicevuta >
  <Esito >0000</Esito>
  <EsitoCaricamentoDocumento >
    <IdentificativoTemporaneoDocumento >TEMP_130_2377356</IdentificativoTemporaneoDocumento>
    <StatoElaborazione >OK</StatoElaborazione>
    <IdentificativoDocumento>2.16.840.1.113883.2.9.2.130.4.4^497255</IdentificativoDocumento>
  </EsitoCaricamentoDocumento>
  <ElencoErrori >
    <Errore >
      <codEsito>0000</codEsito>
      <esito>Operazione eseguita correttamente</esito>
      <tipoErrore>Success</tipoErrore>
      <fonte>FSE-INS-FE</fonte>
    </Errore>
  </ElencoErrori>
</EsitoCaricamentoDocumentoRicevuta>
```

**Comment by vigliottim** [comment]
Buon pomeriggio,
le confermiamo la corretta pubblicazione del documento.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
