### ISSUE TITLE
Il campo Locality non è valorizzato correttamente

### ISSUE THREAD

**Issue by mariogoodbread** [ministero-salute/it-fse-support#1028]
Non riusciamo a capire il motivo dell'errore in oggetto.

traceID: "60172398b2b4a2a6"
spanID: "60172398b2b4a2a6"
workflowInstanceId: 2.16.840.1.113883.2.9.2.120.4.4.46c0e586beeb8d1d8cb983b0951310079104dbbc2f25be96c64d5b79cd7ab101.8e165dee9a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

FSE-JWT: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGcURDQ0JCQ2dBd0lCQWdJVUdXdXhMbytXUXhPdXU3K2JWRHBZZlZ4WWhpb3dEUVlKS29aSWh2Y05BUUVMQlFBd1JqRWhNQjhHQTFVRUF3d1lURUZhU1U5RGNtVmhJRkp2YjNRZ1EwRWdMU0JEVDB4TU1SUXdFZ1lEVlFRS0RBdERiMnhzWVhWa2J5QkRRVEVMTUFrR0ExVUVCaE1DU1ZRd0hoY05Nak13TXpFMU1qSTFNelV6V2hjTk1qVXdNekUwTWpJMU16VXlXakNCMURFNk1EZ0dBMVVFRFF3eFEyVnlkR2xtYVdOaGRHOGdSbWx5YldFZ0xTQkZiblJsSURFeU1ESXdNQ2hVUlZOVUtTQXRJRUZ3Y0ZSbGMzUXdNVEVvTUNZR0ExVUVBd3dmVTBsSE1USXdNakF3WHpBd09UZzNOalUwTXpJeExVRndjRlJsYzNRd01URW9NQ1lHQTFVRUN3d2ZSbUZ6WTJsamIyeHZJRk5oYm1sMFlYSnBieUJGYkdWMGRISnZibWxqYnpFV01CUUdBMVVFQ2d3TlVtVm5hVzl1WlNCTVlYcHBiekVOTUFzR0ExVUVCd3dFVW05dFlURU9NQXdHQTFVRUNBd0ZUR0Y2YVc4eEN6QUpCZ05WQkFZVEFrbFVNSUlDSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQTVOK2pheEVXeDJRYlBCbGpvdW05aE9OSFRqRHlyS1dzYmtDT1pHNXNxL0wzenJxc28xWUVIbE9KcjQvUHAwRmpVOVhuK3dDS0NpMS9XZnFKQlhoWEZTUm0zd0EzUkJFTmMvTEJVSHRsaFUrRTU3YmhWRkc3YVdQWkZtbnFvODRwMklTczBOOGdDaThhZVlPS3lPa2puZEhoOWlVZGZHR0dCdWIvZWxxOVlkb2ltUUNFaXROandhVitUMUphSmdqaHBuTk5XbHpkemFMcExPZWVzd2h0eUdJUFZteTFLM05kZU1sN2FkakdvVnV0MC9XcS9tZXhTUVQyalF5ZVh1ZGkrRlF5K2ZPRVdKbEN4MVJ3cXlKdEhsSXcxUnBkYU1uMmp1NzdCOVpUMnAvb042ZnNjTmF3K2dwZjN3TTdMa2tOTElSbFFKM2V3Ulk1dXR0OUF0YThTL1BwZTFBL2FKc0Mva3lwSk80VUNSSlhyN04wRHdsVG0yRmpxblZMM3lpbmpHd09lKytycGxrMmYvOFVNTkFVMllKOHowQ2hpWnk3alZ2Y1YvU0RWeG14QmwrMXEwbzMwVmVrSHV5Ly9HOTU3UUE0K3NCdTg3MHVBVFdVeXpsM0doRm5JOTBnZkpZQjRwWmZkcStNZjVsYUd2NDNxM3hSMXhNRkdYZ2VJbTFRZUhwNTFLeUJnVmgzWWE2SEJydFB5Q0NURnF6NzY4SHl1ME1pOUtIREVVTDgveGRrOGZ3c3h2clErNUNSa2lzZW9xZE5SVVZPRnZqaDhaWFpNVGRlN1lnYUlEVWljdVB1cHpSM0cvMFhKVDFOUStzbEtWT1ZJaFFXT0dXdTMzMjIxMzZKaW9pLzBnNGlaR0c1WkJYSEk4bzkvSXA5Z2JiajJ0d0lZT0lRcTEwQ0F3RUFBYU4vTUgwd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JSUy91RktiR1ByV2JNSWY5U09tcDdPZnl5V1lqQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBZ1lJS3dZQkJRVUhBd1F3SFFZRFZSME9CQllFRk4xa0s3VTl6aUpnS1BwMnZPMDlqNm52R0NWcU1BNEdBMVVkRHdFQi93UUVBd0lGNERBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVlFQW1VRWQ2ZWZPVjAzakhlM216bnA2RnY4R1g5bnVZZFFJOE9hT2IwUGdnMkVFSzE4WFhML2ZGY1pIaU83T3U2MzF6Rnk2ZXFGVlE1ditiNlNzZGRBYUFTNFV6Vm01RENwV2lpdTRzWVZ4RkZ6cWorVmhmNzdPcmdOSzRZREorZmF1NnBWNWhOazNEbnhSaVhPSklJQjhXeEVBYW9PNGY4c3NmVndvQUU5em5iQy84MkcrYXp3RkQrODc5OGJBZ3pybzNTeVVKTVdYWUhQUFk5ZUVnc2l2Mk5UTEJpOUVMb3YrVHBCeGE5Zkcra3NpMmhWUUtvVlljZWVod3hVRWRKZFg5WmtzZzBDQUY2cElaYkxEUTZKZzArYkxTNmRxK0sxWWt5bGpSQXpsVTZHNG5STEZCT2tuLy90QnNXZ0hLdHQyU3VnVUJHSUxjQ1dGRHByRkJOWm9kZUNnQUh6djIyUS95U3FuNSs5N2NCR05XbmdBcHZFK0NRYUdxRUlPN2x0MVpNVzZJNzRVUFNBRTdVLzcvVVc2cnpGRGhXUTZSdzZYS3pUYjBEOU01NDBJQWFXZXBNV3pPbVhXQ2dwUERpTHYwM28vcXNtV0E5ZGlVNHA1WEptSmxzSUpTS0ZwZWNicGVNNURTL3N4cDJJVm43RGw3bUdjdkRCRDJ2S29FTmIzIl19.eyJpc3MiOiJpbnRlZ3JpdHk6U0lHMTIwMjAwXzAwOTg3NjU0MzIxLUFwcFRlc3QwMSIsInN1YiI6Ik1aWk1ITDg3RTcxSDUwMU1eXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyIsInN1YmplY3Rfcm9sZSI6IkFBUyIsInB1cnBvc2Vfb2ZfdXNlIjoiVFJFQVRNRU5UIiwibG9jYWxpdHkiOiIyMDExMjAwMjYiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlcnNpb24iOiIyLjAiLCJzdWJqZWN0X29yZ2FuaXphdGlvbiI6IlJlZ2lvbmUgTGF6aW8iLCJzdWJqZWN0X29yZ2FuaXphdGlvbl9pZCI6IjEyMCIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInBhdGllbnRfY29uc2VudCI6ZmFsc2UsImFjdGlvbl9pZCI6IkNSRUFURSIsInJlc291cmNlX2hsN190eXBlIjoiKCczNDEwNS03Xl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsInN1YmplY3RfYXBwbGljYXRpb25faWQiOiJhZHR3ZWIiLCJleHAiOjE3MzExMzg2MzgsInN1YmplY3RfYXBwbGljYXRpb25fdmVuZG9yIjoibmlzYXRlayIsImlhdCI6MTcyNzUzODYzOCwianRpIjoiYWRlMTNiOTEtMTE0My00MmJhLWE3YzktZTE1YTFhMzQzZDVhIiwicGVyc29uX2lkIjoiUExMR1BQNDdCNDNINTAxTF5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIiwiYXR0YWNobWVudF9oYXNoIjoiNGQxNDk1NWNiYjRjNmUzMDA1YzQ1NWZmZTQ4YjdjZTA3NzdlOTU1MzIwNDJjYTA3MWU1NDVjOTZjYTIzYWIxYiJ9.1jNE7-b4eBDTHK2VHt9DKIbQTBiDTZ8fwKmim9DoFRWrfThNGUCJVNJ519nqn9G2XdQx-4mBn8XcAtAEr9fMcNpil_SRNrqvSEbOKxY-Y5tn4wIywYn-1I0MB9wXY3lVRh3i53_UGjGBowUK3J_6KtytLeJxhQp3vBy9NEG2Am8leInnuRAGNntscrIDhbLhJObVXw4P8thX6WsLi_R0c2GK0fYitWCM7LJdfKU7TUwgZ1-v-d8bt3UclUA0b8nV4y33eMTluorY3Qhxyl0xLa8jf5zThOBXPoZt-b3IqDAPZtxVqhuALNo-NewrRS8pGT1hcgOV6dHpafu89tNzpDQ2oFnpQJ5cnZXT99uMRParcJ1GaTebp7qUibVSrXvHHQZI39iwY5NxlMSAMMw84PJSii7glySQ1DF_tegG7qyBONYToq7xKavy43YBkMPiXFD_CAk0mHxksy9tUJZX-uslerrK1ekKwYBCehE0OC5tODlPkO7SN2wwEA6nGIoSOBpLqp-k9OtRjUk6gUarKMlGHnKC7zRnNctIg7xs274FhKvBipioo4m56O40i-SMYt41DmSs5_uBJsupTtzK6x-k3OzGA_6vg-r9Qo5QW-M2LEiiEd_9GzstVdGcI7LFnFP2CUbbQa58p9Hqu5izkky_pzPPFeHxYfz5bBivhVs

**Comment by vigliottim** [comment]
Buonasera,
come comunicato sul canale Slack dedicato, è stato rilasciato un nuovo aggiornamento che riguarda il claim _locality_.
La invitiamo a consultare le nuove specifiche aggiornate in documentazione al link: 
https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt
Rimaniamo a disposizione per chiarimenti.
Grazie.

**Comment by mariogoodbread** [comment]
Buongiorno,
grazie per la risposta. La seguente modifica è stata rilasciata solo in ambiente di test o anche in produzione?

**Comment by LucaRogledi** [comment]
Buongiorno,
Il gateway è disponibile in ambiente di test, riguardo l'avvio del gateway in produzione verranno rilasciati aggiornamenti sul canale Slack [fse](https://developersitalia.slack.com/archives/C03RDT88FSM). Rimaniamo a disposizione per chiarimenti.
Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto. Grazie
