### ISSUE TITLE
Mancata ricezione chiamate Gateway

### ISSUE THREAD

**Issue by federicolau** [ministero-salute/it-fse-support#1029]
Buongiorno,

mi ricollego ad un [issue](https://github.com/ministero-salute/it-fse-support/issues/1003#issuecomment-2367819130) che aprimmo pochi giorni fa.

Abbiamo corretto e fornito i nostri endpoint affinchè ci arrivano le chiamate dal Gateway:

- Comunicazione metadati: https://fse-preprod.sanita.regione.rsr.rupar.puglia.it/FSE/DocumentRegistry_Service
- Cancellazione metadati: https://fse-preprod.sanita.regione.rsr.rupar.puglia.it/FSE/XDSDeletetWS_Service
- Recupero riferimenti documento: https://fse-preprod.sanita.regione.rsr.rupar.puglia.it/FSE/DocumentRegistry_Service

Al momento, però, non stiamo ancora ricevendo alcuna richiesta. A voi cosa risulta?

Grazie.

**Comment by LucaRogledi** [comment]
Buonasera, La informiamo che è corretto non ricevere chiamate dal Gateway. Al momento sono in corso verifiche sugli endpoint indicati lato INI da cui potrebbe ricevere chiamate. Grazie

**Comment by vigliottim** [comment]
Buonasera,
la presente issue risulta essere stata gestita via e-mail.
Pertanto, procediamo alla sua chiusura.
In caso contrario sarà possibile riaprirla.
Grazie.
