### ISSUE TITLE
Richiesta Informazioni su Accreditamento GPI

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#103]
Buongiorno, 
abbiamo sottomesso in questi giorni le pull request dei primi casi di test effettuati:

https://github.com/ministero-salute/it-fse-accreditamento/pull/23
https://github.com/ministero-salute/it-fse-accreditamento/pull/25
https://github.com/ministero-salute/it-fse-accreditamento/pull/26
**https://github.com/ministero-salute/it-fse-accreditamento/pull/36**

attualmente solo l'ultima contiene tutti i test effettuati ad oggi, le altre le abbiamo rimosse.

Quali sono le tempistiche per la verifica e l'eventuale approvazione?

Grazie, Saluti Elisabetta Tecchio

**Comment by Elisabetta-Tecchio-GPI** [comment]
https://github.com/ministero-salute/it-fse-accreditamento/pull/39

Grazie

**Comment by Elisabetta-Tecchio-GPI** [comment]
Buongiorno, notifichiamo l'ultima pull request effettuata:

https://github.com/ministero-salute/it-fse-accreditamento/pull/44

Grazie

**Comment by Ser-ena** [comment]
Buonasera, ricordiamo che la richiesta di pull deve essere effettuata solo alla fine della sessione di test. Possiamo considerare la versione nella commit #44 come completa e definitiva e quindi procedere con le verifiche? Altrimenti le chiederemo di richiedere la pull solo al completamento della fase di test.

**Comment by Elisabetta-Tecchio-GPI** [comment]
Grazie per l'informazione, procediamo nella giornata di domani a caricare la versione completa e definitiva e notificarla qui.

**Comment by Elisabetta-Tecchio-GPI** [comment]
Buongiorno, volevo confermare che https://github.com/ministero-salute/it-fse-accreditamento/pull/44
contiene tutti i test di LDO e sono completati. Possono essere verificati?

La catena di test VPS sarà completata successivamente.

Grazie

**Comment by IStacchiotti** [comment]
Buon pomeriggio. Le confermiamo che la pull request è stata presa in carico. Le chiediamo pertanto la cortesia di chiudere il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
