### ISSUE TITLE
Errore in creazione non ritornato in validazione

### ISSUE THREAD

**Issue by mariogoodbread** [ministero-salute/it-fse-support#1030]
Salve,
abbiamo risontrato diversi casi in cui in fase di validazione non vengono ritornati gli errori ritornati in fase di creazione di un documento su FSE.
Tanto per fare un esempio, la richiesta di creazione con workflowInstanceId: 2.16.840.1.113883.2.9.2.120.4.4.46c0e586beeb8d1d8cb983b0951310079104dbbc2f25be96c64d5b79cd7ab101.8e165dee9a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId.

E' un comportamento normale?

**Comment by mariogoodbread** [comment]
{
        "traceID": "60172398b2b4a2a6",
        "spanID": "60172398b2b4a2a6",
        "type": "/msg/jwt-validation",
        "title": "Campo token JWT non valido.",
        "detail": "Il campo Locality non è valorizzato correttamente",
        "status": 403,
        "instance": "/jwt-mandatory-field-malformed"
      }

**Comment by LucaRogledi** [comment]
Buonasera, il campo locality viene verificato solo rispetto agli endpoint creazione e sostituzione come specificato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt). La invitiamo gentilmente ad indicarci gli altri errori riscontrati in pubblicazione e non presenti in validazione per ulteriore supporto. Grazie

**Comment by vigliottim** [comment]
Buonasera,
il controllo non è stato anticipato in validazione per non avere impatti sull'accreditamento.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by mariogoodbread** [comment]
Buongiorno,
quale è il senso di accreditarsi in una modalità che poi non funziona in produzione?

**Comment by IStacchiotti** [comment]
Per scelte tecniche alcuni controlli, come quello sul campo "locality", sono stati demandati alla fase di pubblicazione piuttosto che a quella di validazione (entrambe le fasi sono oggetto di accreditamento). Ricordiamo inoltre che non ci sono differenze di controlli tra gli ambienti (validazione vs produzione).

**Comment by mariogoodbread** [comment]
Buongiorno,
onestamente ritengo che le scelte tecniche non dovrebbero influenzare quelle funzionali. Dal mio punto di vista, la fase di validazione serve a verificare se, con un determinato set di dati, è possibile procedere alla pubblicazione di un documento. Tuttavia, sembra che questo non accada, poiché lo stesso set di dati che ha superato con successo la validazione non riesce a superare la fase di pubblicazione.
Detto ciò, se i requisiti funzionali che sono stati forniti sono questi, non possiamo fare altro che accettarli così come sono.

**Comment by vigliottim** [comment]
Grazie per la sua segnalazione.
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per altre richieste di supporto.
