### ISSUE TITLE
Consultazione documenti FSE

### ISSUE THREAD

**Issue by mariogoodbread** [ministero-salute/it-fse-support#1031]
Salve,
esistono delle API per consultare i documenti creati su FSE o per consultare i documenti di un paziente? In caso positivo dove trovo la documentazione?

**Comment by vigliottim** [comment]
Buonasera,
la invitiamo a consultare le specifiche dell'Affinity Domain 2.5 per trovare le informazioni richieste:
https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20interoperabilit%C3%A0/FrameworkEDatasetDeiServiziBase_v2-5_20231212_0.pdf
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto. Grazie
