### ISSUE TITLE
Chiarimenti sulla pubblicazione 

### ISSUE THREAD

**Issue by ub2012** [ministero-salute/it-fse-support#1032]
Buonasera, a seguito dell'accreditamento della validazione, abbiamo dei clienti in Lombardia e Veneto che ci chiedono la pubblicazione nel repository. 

Potreste gentilmente indicarci le specifiche tecniche per la pubblicazione in queste 2 regioni?

Grazie.

**Comment by vigliottim** [comment]
Buonasera,
potrebbe indicarci a quale repository fa riferimento?
Grazie.

**Comment by vigliottim** [comment]
Di seguito può trovare la documentazione con gli endpoint per chiamare il servizio di pubblicazione:
https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by ds-tommaso** [comment]
perdonate l'intromissione

è possibile interrogare i servizi di pubblicazione, ignorando le infrastrutture regionali?
i referti saranno disponibili sui profili FSE del cittadino? il gateway è ora pubblicato in ambiente di produzione?

Ogni regione che abbiamo interfacciato ha sviluppato un proprio ambiente e propri servizi - penso a sogei per le regioni in sussidiarietà, LazioCrea in Lazio, progetto SOLE in Emilia, Innovapuglia in Puglia ecc.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto. Grazie
