### ISSUE TITLE
Errore pubblicazione Regione 020 - Patient validation error per CF censito in crash-program

### ISSUE THREAD

**Issue by assistenza-fsevda** [ministero-salute/it-fse-support#1034]
Buongiorno,
in data odierna abbiamo provato a pubblicare un documento relativo al CF che come regione Valle d'Aosta (020) abbiamo censito per il crash program e che è presente nel file issuers.json pubblicato su GitHub.
Interrogando lo stato tramite il Gateway risulta però un errore di _Patient validation error_ nell'event "SEND_TO_INI".

```
{
	"traceID": "cdff869569e01f1d",
	"spanID": "313cb79010bb23cc",
	"transactionData": [
		{
			"eventType": "VALIDATION",
			"eventDate": "2024-09-30T15:10:47.854+00:00",
			"eventStatus": "SUCCESS",
			"subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"organizzazione": "020",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.32b78ceb5e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "b8abe121be2d4b2e",
			"issuer": "integrity:S1#020#020VALDAOSTATEST",
			"expiringDate": "2025-09-30T15:10:47.865+00:00"
		},
		{
			"eventType": "PUBLICATION",
			"eventDate": "2024-09-30T15:12:24.772+00:00",
			"eventStatus": "SUCCESS",
			"identificativoDocumento": "2.16.840.1.113883.2.9.2.20.4.4^001.TRAKTEST.TESTRSA-ADD000001-0",
			"subject": "CRCMRC80E28A326S^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"tipoAttivita": "CON",
			"organizzazione": "020",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.32b78ceb5e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "9ebf4f7735994d80",
			"issuer": "integrity:S1#020#020VALDAOSTATEST",
			"expiringDate": "2025-09-30T15:12:24.802+00:00"
		},
		{
			"eventType": "SEND_TO_INI",
			"eventDate": "2024-09-30T15:12:25.106+00:00",
			"eventStatus": "BLOCKING_ERROR",
			"message": "500 : \"{\"traceID\":\"20b5077234a27a41\",\"spanID\":\"20b5077234a27a41\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: Patient validation error Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}\"",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.32b78ceb5e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"expiringDate": "2025-09-30T15:12:25.115+00:00"
		}
	]
}
```

Il CF in questione è PZNTTF75H27E379B. Può essere che manchi qualche configurazione lato INI? Se può essere utile otteniamo la stessa tipologia di errore "Patient validation error" utilizzando il servizio di recupero consenso esposto da INI in ambiente di validazione.

Grazie anticipatamente per il supporto

**Comment by LucaRogledi** [comment]
Buongiorno, 
La informiamo che il Codice fiscale da lei indicato "PZNTTF75H27E379B" è stato censito ed è ora possibile assegnare i consensi e procedere con una nuova prova. Grazie

**Comment by assistenza-fsevda** [comment]
Buongiorno,
confermo che siamo riusciti ad assegnare i consensi e a comunicare con il Gateway in merito a validazione e pubblicazione. Come per tutti gli altri CF che abbiamo provato, continuiamo a ricevere l'errore "RDA generated an internal error" nell'event "SEND_TO_INI". Per questa problematica abbiamo già aperto l'issue #1027 di cui stiamo aspettando riscontro.

Grazie per il supporto fornito.

**Comment by LucaRogledi** [comment]
Ringraziamo per il feedback e procediamo con la chiusura della presente segnalazione. Grazie
