### ISSUE TITLE
FSE ambiente TEST - Errore di pubblicazione generico 500

### ISSUE THREAD

**Issue by rdellacasa** [ministero-salute/it-fse-support#1035]
Buongiorno,

dopo aver effettuato la validazione del documento in fase di pubblicazione ci viene restituito "500-Errore generico":

{"traceID":"ca22af7c74927e89","spanID":"ca22af7c74927e89","type":"/msg/generic-error","title":"Errore generico.","detail":"Errore generico","status":500,"instance":""}

questo il body quella richieste:

{"workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.b6131811e60f6368c864d8174b58454f23a9e37512527bd3366341c7fc72c5a6.3b064114f1^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","mode":"ATTACHMENT","tipologiaStruttura":"Ospedale","identificativoDoc":"2.16.840.1.113883.2.9.2.120.4.4^12011001900.3.4158319306485984684.2","identificativoRep":"2.16.840.1.113883.2.9.2.120.4.5.120110","tipoDocumentoLivAlto":"LDO","assettoOrganizzativo":"AD_PSC032","tipoAttivitaClinica":"DIS","identificativoSottomissione":"2.16.840.1.113883.2.9.2.120.4.3^12011001900.3.20240930102434943.25472.4158319306485984684"}

Sapreste indicarmi eventuali problemi ?

**Comment by vigliottim** [comment]
Buongiorno,
le chiediamo se sta partecipando al Crash Program.
Se sì, dovrebbe usare i certificati che le sono stati inviati poiché quelli che sta utilizzando sono in regime di mock.
Grazie.

**Comment by rdellacasa** [comment]
Non sto partecipando al crash program, sto effettuando dei test di invio di LDO e RSA per l'azienda sanitaria locale di Rieti (Lazio). con gli stessi certificati utilizzati per la pubblicazione è stata effettuata anche la validazione.

**Comment by rdellacasa** [comment]
Buongiorno,

sapreste darmi maggiori informazioni su come procedere con i miei test?

**Comment by vigliottim** [comment]
Buongiorno,
la informiamo che sono in corso delle verifiche.
Le faremo sapere non appena avremo aggiornamenti.
Grazie.

**Comment by rdellacasa** [comment]
Grazie mille!

**Comment by vigliottim** [comment]
Buongiorno,
è stato effettuato un aggiornamento.
Potreste cortesemente riprovare?
Grazie.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
E' possibile riaprirla nel caso in cui abbia bisogno di ulteriore supporto.
Grazie.
