### ISSUE TITLE
Crash Program - Regione Molise - UC1 - Errore Pubblicazione

### ISSUE THREAD

**Issue by marlagatta** [ministero-salute/it-fse-support#1037]
Salve. 
A seguito dell'esito positivo di pubblicazione di un documento, il nodo regionale riceve correttamente una chiamata  di ITI-42, che però non riesce a superare il passo di validazione effettuato dal registry regionale, con la seguente motivazione:

`    <ns2:RegistryErrorList>
        <ns2:RegistryError codeContext="Wrong format data of display name for DocumentEntry.confidentialityCode (Document1)" errorCode="R31" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"/>
    </ns2:RegistryErrorList>
`

Abbiamo estratto dalla request di chiamata la seguente classification, da cui si evince la NON corretta valorizzazione della descrizione del confidentialitiCode secondo le specifiche dell'Affinity Domain:
`
					<ns2:Classification
						classificationScheme="urn:uuid:f4f85eac-e6cb-4883-b524-f2705394840f"
						classifiedObject="Document1" id="ConfidentialityCode01"
						nodeRepresentation="N"
						objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification">
						<ns2:Slot name="codingScheme">
							<ns2:ValueList>
								<ns2:Value>2.16.840.1.113883.5.25</ns2:Value>
							</ns2:ValueList>
						</ns2:Slot>
						<ns2:Name>
							<ns2:LocalizedString charset="UTF-8" value=""
								xml:lang="en-US" />
						</ns2:Name>
					</ns2:Classification>
`
Essendo questo un controllo bloccante, siamo impossibilitati a proseguire i test previsti dal Crash Program.
Potreste cortesemente assisterci?

Grazie mille

**Comment by vigliottim** [comment]
Buongiorno, 
al fine di svolgere indagini più approfondite, le chiederemmo di allegare una response completa comprensiva di traceid/govwayid e indicare la regione nel ruolo di RDA.
Grazie per la collaborazione.

**Comment by marlagatta** [comment]
Salve,
la regione RDA é il Molise, e 
la response alla pubblicazione é la seguente:

`
HTTP/1.1 201 Created
X-Backside-Transport: OK OK
Connection: Keep-Alive
Transfer-Encoding: chunked
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
set-cookie: 894d46ecfc124039ee218b63c12a3329=9c62788caf0fe4a977db8e11a8d1653d; path=/; HttpOnly; Secure; SameSite=None
Server: GovWay-SOGEI
Pragma: no-cache
GovWay-Message-ID: e97d9faf-255f-475a-9b4b-2c355a6861e9
GovWay-Transaction-ID: a89db446-8093-11ef-b8bd-005056ae54fa
server-timing: intid;desc=404781e93709f6d7
Date: Wed, 02 Oct 2024 08:16:09 GMT
Vary: *
X-Content-Type-Options: nosniff
Content-Type: application/json
X-Global-Transaction-ID: 6026e6bc66fd01499b12105f

{"traceID":"cd4b69f53e0c866c","spanID":"cd4b69f53e0c866c","workflowInstanceId":"2.16.840.1.113883.2.9.2.140.4.4.d4451f2d3ae9f6536514548d3dc9cabb1cf0d58015695ebb1b7c39d2c094ec09.2dfe86d350^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}
`

In allegato la request ricevuta da INI e nostra relativa response
[REQUESTINI_20241002.xml.txt](https://github.com/user-attachments/files/17224990/REQUESTINI_20241002.xml.txt)
[RESPONSE_TO_INI_20241002.xml.txt](https://github.com/user-attachments/files/17224993/RESPONSE_TO_INI_20241002.xml.txt)

**Comment by vigliottim** [comment]
Buongiorno, è stato rilasciato un aggiornamento.
Potreste gentilmente riprovare e darci un riscontro?
Grazie.

**Comment by marlagatta** [comment]
Salve.
L'aggiornamento ha avuto l'esito positivo:

Dopo un nuovo tentativo di invio, si ottiene success dal passo SEND_TO_INI, come risulta dal response del serizio getStatus per workflowInstanceId:

`{
   "traceID": "9c1405ff7d2f843a",
   "spanID": "123cda5efeb60b6f",
   "transactionData":    [
            {
         "eventType": "VALIDATION_FOR_PUBLICATION",
         "eventDate": "2024-10-07T11:41:26.766+02:00",
         "eventStatus": "SUCCESS",
         "subject": "PRSTZN75L52B519D^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
         "organizzazione": "140",
         "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.ce4df2e285fa325dbe93d4a59c321daf18c90ad51041a1520a8c985f41729a53.bd42598e81^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "traceId": "ceea6c9ea48e29bf",
         "issuer": "integrity:S1#140#REGIONEMOLISETEST",
         "expiringDate": "2025-10-07T11:41:26.781+02:00"
      },
            {
         "eventType": "PUBLICATION",
         "eventDate": "2024-10-07T11:41:27.069+02:00",
         "eventStatus": "SUCCESS",
         "identificativoDocumento": "2.16.840.1.113883.2.9.2.140.4.4^20241007002",
         "subject": "PRSTZN75L52B519D^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
         "tipoAttivita": "DIS",
         "organizzazione": "140",
         "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.ce4df2e285fa325dbe93d4a59c321daf18c90ad51041a1520a8c985f41729a53.bd42598e81^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "traceId": "ceea6c9ea48e29bf",
         "issuer": "integrity:S1#140#REGIONEMOLISETEST",
         "expiringDate": "2025-10-07T11:41:27.082+02:00"
      },
            {
         "eventType": "SEND_TO_INI",
         "eventDate": "2024-10-07T11:41:27.954+02:00",
         "eventStatus": "SUCCESS",
         "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.ce4df2e285fa325dbe93d4a59c321daf18c90ad51041a1520a8c985f41729a53.bd42598e81^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "expiringDate": "2025-10-07T11:41:28.029+02:00"
      }
   ]`
   
   
Notiamo però che non viene contattato il servizio di NotificaMetadati, pur avendo noi comunicato l'url a cui risponde in ambiente di TEST:

`https://inigtwtest.regione.molise.it/api/xdsnotify`    

Potreste cortesemente controllare? Se il servizio non viene contattato, la pubblicazione non può essere perfezionata da parte nostra.
Grazie mille per il supporto

**Comment by g-maugeri-sogei** [comment]
Buonasera,
endpoint configurato.

**Comment by marlagatta** [comment]
Salve, 
è stato effettuato un nuovo test, ma comunque non viene contattato il servizio di NotificaMetadati.
Potreste cortesemente visionare i vostry log? 

La regione RDA è il Molise,
il traceId di PUBLICATION è 145e33db795edf9a
il workflowInstanceId è

2.16.840.1.113883.2.9.2.140.4.4.8f414746177f9fbafad1edd80e19a64a9c822757c6fb4b5a552bd74836e0b449.b131b3fd94^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

Grazie mille

**Comment by marlagatta** [comment]
Salve.

Dopo un nuovo tentativo di pubblicazione, per cui si è avuto esito positivo, si deve comunque riscontrare che l'endpoint di NotifyCommunicationMetadata  non é stato contattato.

La regione interessata è il  Molise, l'output  del getStatus è
````
{
   "traceID": "1c172b5f28d5c2f1",
   "spanID": "2d0271bb62b4d8e3",
   "transactionData":    [
            {
         "eventType": "VALIDATION",
         "eventDate": "2024-10-14T12:59:17.861+02:00",
         "eventStatus": "SUCCESS",
         "subject": "PRSTZN75L52B519D^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
         "organizzazione": "140",
         "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.d991a1c3734fd957033fe7c81fb9cb215c3241e75a01ecc142cd6bafaf93fca7.ebe9f1e847^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "traceId": "5ad210e3380727b8",
         "issuer": "integrity:S1#140#REGIONEMOLISETEST",
         "expiringDate": "2025-10-14T12:59:17.934+02:00"
      },
            {
         "eventType": "PUBLICATION",
         "eventDate": "2024-10-14T13:01:10.606+02:00",
         "eventStatus": "SUCCESS",
         "identificativoDocumento": "2.16.840.1.113883.2.9.2.140.4.4^20241014002",
         "subject": "PRSTZN75L52B519D^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
         "tipoAttivita": "DIS",
         "organizzazione": "140",
         "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.d991a1c3734fd957033fe7c81fb9cb215c3241e75a01ecc142cd6bafaf93fca7.ebe9f1e847^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "traceId": "82fca883de44b0fb",
         "issuer": "integrity:S1#140#REGIONEMOLISETEST",
         "expiringDate": "2025-10-14T13:01:10.617+02:00"
      },
            {
         "eventType": "SEND_TO_INI",
         "eventDate": "2024-10-14T13:01:11.546+02:00",
         "eventStatus": "SUCCESS",
         "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.d991a1c3734fd957033fe7c81fb9cb215c3241e75a01ecc142cd6bafaf93fca7.ebe9f1e847^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "expiringDate": "2025-10-14T13:01:11.623+02:00"
      }
   ]
}
````

**Comment by marlagatta** [comment]
Salve.
Sono stati eseguiti dall'ultimo commento diversi casi di test UC2, UC4, UC6, UC10, UC12, con RDE=Molise e RDA=Lazio, e per NESSUNO di essi è stato mai contattato il servizio NotifyCommunicationMetadata .
Sollecitiamo cortesemente una verifica delle motivazioni

**Comment by g-maugeri-sogei** [comment]
Buonasera,
potete riprovare e darci riscontro?

**Comment by marlagatta** [comment]
Salve. 
Il problema permane inalterato:

Appena provata una UC1, RDE=RDA=Molise. Non è stato contattato NotifyCommunicationMetadata ,

La chiamata alla api di Esito per workflowInstanceId restituisce

```
{
   "traceID": "0edc4cda4caa4e98",
   "spanID": "e7210f11ad1029e5",
   "transactionData":    [
            {
         "eventType": "VALIDATION",
         "eventDate": "2024-10-18T17:35:34.566+02:00",
         "eventStatus": "SUCCESS",
         "subject": "PRSTZN75L52B519D^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
         "organizzazione": "140",
         "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.5d4761a5b273c2b6d57a68c1774ee40479c797e16d39ddcced72551cdba0647f.d5068a4c0e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "traceId": "b5d9c1ce4bc352fb",
         "issuer": "integrity:S1#140#REGIONEMOLISETEST",
         "expiringDate": "2025-10-18T17:35:34.630+02:00"
      },
            {
         "eventType": "PUBLICATION",
         "eventDate": "2024-10-18T17:36:48.633+02:00",
         "eventStatus": "SUCCESS",
         "identificativoDocumento": "2.16.840.1.113883.2.9.2.140.4.4^202410160011401",
         "subject": "PRSTZN75L52B519D^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
         "tipoAttivita": "DIS",
         "organizzazione": "140",
         "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.5d4761a5b273c2b6d57a68c1774ee40479c797e16d39ddcced72551cdba0647f.d5068a4c0e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "traceId": "0c48024b3cda66d1",
         "issuer": "integrity:S1#140#REGIONEMOLISETEST",
         "expiringDate": "2025-10-18T17:36:48.644+02:00"
      },
            {
         "eventType": "SEND_TO_INI",
         "eventDate": "2024-10-18T17:36:49.690+02:00",
         "eventStatus": "SUCCESS",
         "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.5d4761a5b273c2b6d57a68c1774ee40479c797e16d39ddcced72551cdba0647f.d5068a4c0e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "expiringDate": "2025-10-18T17:36:49.698+02:00"
      }
   ]
}

```

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
vi ritrovate nei log la chiamata sotto riportata?

2024-10-21 09:37:13.551 ERROR : EndpointEsterno: https://inigtwtest.regione.molise.it/api/xdsnotify
2024-10-21 09:37:13.551 ERROR : RegioneInvocata: 140
2024-10-21 09:37:13.552 ERROR :  SOAP outbound Message :<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><NotifySubmitObjectsRequest xmlns="http://www.fascicolosanitario.gov.it/schema/typeSchemaNotifySubmitObjects"><HomeCommunityId>urn:oid:2.16.840.1.113883.2.9.2.140</HomeCommunityId><RepositoryUniqueId>2.16.840.1.113883.2.9.2.140.4.5.1</RepositoryUniqueId><DocumentUniqueId>2.16.840.1.113883.2.9.2.140.4.4^202410160011401</DocumentUniqueId><PatientId>ZCCSBT75C05I282D^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</PatientId></NotifySubmitObjectsRequest></soapenv:Body></soapenv:Envelope>
2024-10-21 09:37:13.552 ERROR :  SOAP fault :<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:wsrf-bf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsrf-r="http://docs.oasis-open.org/wsrf/r-2"><env:Header>
<wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
<wsa:Action>http://www.w3.org/2005/08/addressing/soap/fault</wsa:Action>
<wsa:MessageID>urn:uuid:e1e706d1-06f2-49d7-88f4-403d3743cd12</wsa:MessageID>
<wsa:RelatesTo/></env:Header><env:Body>
<env:Fault><env:Code>
<env:Value>env:Receiver</env:Value></env:Code><env:Reason>
<env:Text xml:lang="en">General Failure</env:Text></env:Reason><Detail xmlns="http://www.w3.org/2003/05/soap-envelope">
<wsrf-r:ResourceUnknownFault>
<wsrf-bf:Timestamp>2024-10-21T07:37:13.548Z</wsrf-bf:Timestamp>
<wsrf-bf:Description>Internal Server Error</wsrf-bf:Description></wsrf-r:ResourceUnknownFault></Detail></env:Fault></env:Body></env:Envelope>

**Comment by marlagatta** [comment]
Salve. 

Notiamo che la chiamata riportata in precedenza non contiene nell'header le informazioni sull'addressing, che il servizio richiede come obbligatorie.

Abbiamo disabilitato l'opzione che richiede l'obbligatorieta' dell'Addressing.

Potreste riprovare la chiamata per cortesia? 

Grazie mille

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
abbiamo riprovato a scodare la chiamata.
Riceviamo ancora un fault.

2024-10-22 08:51:54.821 ERROR : Endpoint: https://fseservicetest.sanita.finanze.it/FSEININotificheWeb/NotifyCommunicationMetadata_Service_esterno
2024-10-22 08:51:54.821 ERROR : EndpointEsterno: https://inigtwtest.regione.molise.it/api/xdsnotify
2024-10-22 08:51:54.821 ERROR : RegioneInvocata: 140
2024-10-22 08:51:54.821 ERROR :  SOAP outbound Message :<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><NotifySubmitObjectsRequest xmlns="http://www.fascicolosanitario.gov.it/schema/typeSchemaNotifySubmitObjects"><HomeCommunityId>urn:oid:2.16.840.1.113883.2.9.2.140</HomeCommunityId><RepositoryUniqueId>2.16.840.1.113883.2.9.2.140.4.5.1</RepositoryUniqueId><DocumentUniqueId>2.16.840.1.113883.2.9.2.140.4.4^202410160011401</DocumentUniqueId><PatientId>ZCCSBT75C05I282D^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</PatientId></NotifySubmitObjectsRequest></soapenv:Body></soapenv:Envelope>
2024-10-22 08:51:54.821 ERROR :  SOAP fault :<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:wsrf-bf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsrf-r="http://docs.oasis-open.org/wsrf/r-2"><env:Header>
<wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
<wsa:Action>http://www.w3.org/2005/08/addressing/soap/fault</wsa:Action>
<wsa:MessageID>urn:uuid:b0766c26-55ab-490f-a407-403d37438a29</wsa:MessageID>
<wsa:RelatesTo/></env:Header><env:Body>
<env:Fault><env:Code>
<env:Value>env:Receiver</env:Value></env:Code><env:Reason>
<env:Text xml:lang="en">General Failure</env:Text></env:Reason><Detail xmlns="http://www.w3.org/2003/05/soap-envelope">
<wsrf-r:ResourceUnknownFault>
<wsrf-bf:Timestamp>2024-10-22T06:51:54.816Z</wsrf-bf:Timestamp>
<wsrf-bf:Description>Internal Server Error</wsrf-bf:Description></wsrf-r:ResourceUnknownFault></Detail></env:Fault></env:Body></env:Envelope>

**Comment by marlagatta** [comment]
Salve.
Potreste cortesemente ri-configurare l'endpoint da contattare, per RDE=Molise,  per il servizio NotifyCommunicationMetadata  con il seguente:

https://inigtwtest.regione.molise.it/XDSNotify
 
 e riprovare ?
 Grazie mille

**Comment by g-maugeri-sogei** [comment]
Da ancora errore.

2024-10-22 14:21:37.269 ERROR : Endpoint: https://fseservicetest.sanita.finanze.it/FSEININotificheWeb/NotifyCommunicationMetadata_Service_esterno
2024-10-22 14:21:37.269 ERROR : EndpointEsterno: https://inigtwtest.regione.molise.it/XDSNotify
2024-10-22 14:21:37.269 ERROR : RegioneInvocata: 140
2024-10-22 14:21:37.269 ERROR :  SOAP outbound Message :<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><NotifySub
mitObjectsRequest xmlns="http://www.fascicolosanitario.gov.it/schema/typeSchemaNotifySubmitObjects"><HomeCommunityId>urn:oid:2.16.840.1.113883.2.9.2.140</HomeCommunityId><Re
positoryUniqueId>2.16.840.1.113883.2.9.2.140.4.5.1</RepositoryUniqueId><DocumentUniqueId>2.16.840.1.113883.2.9.2.140.4.4^202410160011401</DocumentUniqueId><PatientId>ZCCSBT7
5C05I282D^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</PatientId></NotifySubmitObjectsRequest></soapenv:Body></soapenv:Envelope>
2024-10-22 14:21:37.269 ERROR :  SOAP fault :<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsrf-bf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:w
sa="http://www.w3.org/2005/08/addressing" xmlns:wsrf-r="http://docs.oasis-open.org/wsrf/r-2"><env:Header>
<wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
<wsa:Action>http://www.w3.org/2005/08/addressing/soap/fault</wsa:Action>
<wsa:MessageID>urn:uuid:dbce0444-a8f6-4a4c-95c3-403d37430212</wsa:MessageID>
<wsa:RelatesTo/></env:Header><env:Body>
<env:Fault><faultcode>env:Server</faultcode><faultstring>General Failure</faultstring><detail>
<wsrf-r:ResourceUnknownFault>
<wsrf-bf:Timestamp>2024-10-22T12:21:37.256Z</wsrf-bf:Timestamp>
<wsrf-bf:Description>Internal Server Error</wsrf-bf:Description></wsrf-r:ResourceUnknownFault></detail></env:Fault></env:Body></env:Envelope>
2024-10-22 14:21:37.270 ERROR : ==========> INIZIO STACK TRACE
Exception: javax.xml.ws.soap.SOAPFaultException
Message: General Failure

**Comment by marlagatta** [comment]
Salve. L'errore sembra essersi risolto. Ringrazio per l'assistenza e chiudo l'issue

**Comment by marlagatta** [comment]
Salve.
La chiamata al servizio di NotifyCommunicationMetadata risulta poi essere stata effettuata alle 12:19, con un ritardo di due ore e trenta minuti.
Si richiude l'issue.
