### ISSUE TITLE
CDA RAD, Test Valorizzazione campi incongruenza con schematronFSE_RAD.sch 

### ISSUE THREAD

**Issue by marcomontelatfujifilm** [ministero-salute/it-fse-support#104]
Sto validando i Test KO. In diversi casi lo schematron in oggetto valida la presenza del tag e non la valorizzazione.

**Test 8**
Per il Test 8 nel file Excel si dice: "Il comune di residenza del paziente non valorizzato".

Passando però il seguente addr nel CDA in validazione non si hanno errori nonostante il campo city non sia valorizzato.

Sembra anche che lo schematron verifichi solo la presenza del tag city e non il contenuto. In secondo luogo non tiene conto del campo use="H" (dove H sarebbe appunto residenza).

`
<addr use="H">
  <country>ITA</country>
  <county>TE</county>
  <city></city>
  <censusTract>067025</censusTract>
  <postalCode>64021</postalCode>
  <streetAddressLine>STRADA DI PROVA 36/A</streetAddressLine>
</addr>
`

**Test 9**
Nel caso del paziente il seguente frammento è considerato valido, mentre nel foglio Excel il Test 9 dice: "Il nome del paziente non valorizzato."

`
<name><given></given><family>DIVXXXX</family></name>
`

**Test 10**

Nel Test 10 si dice "Il sesso del paziente valorizzato con un valore diverso da "male", "female" o "undifferentiated". Es: campo valorizzato con codice"NB" (Non Binary)"

Lo schematron verifica solo la presenza del tag administrativeGenderCode e non effettua alcuna introspezione dei valori. Infatti il seguente caso viene validato senza problemi:

`
<administrativeGenderCode code="NB" codeSystem="2.16.840.1.113883.5.1" codeSystemName="HL7 AdministrativeGender" displayName="Not Binary"/>
`

**Test 13**
Nel Test 13 in relazione a ClinicalDocument/inFulfillmentoOf/order/id (e attributi) si dice "Non viene valorizzato l'identificativo della prescrizione".

La validazione passa comunque anche senza id:
`
  <inFulfillmentOf>
    <order classCode="ACT" moodCode="RQO">
      <priorityCode code="R" codeSystem="2.16.840.1.113883.5.7" codeSystemName="HL7 ActPriority" displayName="Normale"/>
    </order>
  </inFulfillmentOf>
`

**Comment by nturri1306** [comment]
ho lo stesso problema  con VPS ho messo anche ultimo schematron ma errore  scatta solo quando il tag viene completamente rimosso , ho fatto delle verifiche anche con un ide esterno come oxigen si comporta uguale.

**Comment by IStacchiotti** [comment]
Buongiorno, per quanto concerne i casi di test 8 e 9, si genererà un errore semantico con l'eliminazione degli elementi rispettivamente addr/city e name/given. Mentre per il caso di test 10, lo schematron vincola l'elemento administrativeGender
al dizionario codeSystem="2.16.840.1.113883.5.1", perciò l'elemento code dovrà essere valorizzato con i valori presenti all'interno del dizionario.
La valorizzazione erratta del code ovvero con un valore non presente nel dizionario, 
genererà  un errore terminologico. Se così non fosse, le chiediamo di allegare il CDA2 con cui è stato effettuato il test per maggiori dettagli. Grazie.

**Comment by IStacchiotti** [comment]
In merito invece al caso di test 13, ci conferma che l'elemento "inFulfillmentOf/order/id" è stato cancellato dal CDA? Il test in questione infatti prevede la generazione di un errore per assenza di un campo obbligatorio: se il campo in questione viene mantenuto e lasciato vuoto, il sistema non lo interpreta come assente e il test fallisce. In caso positivo, la invito ad allegare i CDA. Grazie

**Comment by marcomontelatfujifilm** [comment]
Ho generato il CDA.xml relativo al TEST-10. Il tag administrativeGenderCode è:

`<administrativeGenderCode code="NB" codeSystem="2.16.840.1.113883.5.1" codeSystemName="HL7 AdministrativeGender" displayName="Not Binary"/>`

In allegato il CDA.xml (estensione cambiata in txt)

[TEST-10.txt](https://github.com/ministero-salute/it-fse-support/files/10754588/TEST-10.txt)

**Comment by marcomontelatfujifilm** [comment]
Allego il CDA.xml relativo al TEST-13. Nel tag inFulfillmentOf manca id:

`
  <inFulfillmentOf>
    <order classCode="ACT" moodCode="RQO">
      <priorityCode code="R" codeSystem="2.16.840.1.113883.5.7" codeSystemName="HL7 ActPriority" displayName="Normale"/>
    </order>
  </inFulfillmentOf>
`

[TEST-13.txt](https://github.com/ministero-salute/it-fse-support/files/10754675/TEST-13.txt)

**Comment by marcomontelatfujifilm** [comment]
Nel Test 14 si dice "Codice dell'esame eseguiro non  valorizzato." Nel foglio Excel il riferimento ai tag del CDA è: ClinicalDocument/component/structuredBody/component/section[@ID=Esame_eseguito]/entry/act/code

In tutti questi casi la validazione va a buon fine mentre non dovrebbe:

Manca completamente code:

          <entry>
            <act classCode="ACT" moodCode="EVN">
              <text><reference value="#Esame1"/></text>
              <statusCode code="active"/>
              <effectiveTime value="20221107113710+0100"/>
            </act>
          </entry>

Il campo code di code è vuoto:

          <entry>
            <act classCode="ACT" moodCode="EVN">
              <code code="" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="TAC angiografia art. coronariche">
                <originalText><reference value="#EsameDesc1"/></originalText>
              </code>
              <text><reference value="#Esame1"/></text>
              <statusCode code="active"/>
              <effectiveTime value="20221107113710+0100"/>
            </act>
          </entry>

L'unico modo per far fallire la validazione è togliere il tag entry. In quel caso viene sollevata la seguente eccezione che però è relativa alla entry e non al /entry/act/code

"ERRORE-b3| Sezione Esame Eseguito: La sezione deve contenere un elemento 'entry'."

**Comment by IStacchiotti** [comment]
Per quanto riguarda l'elemento inFulfillmentOf/order, è necessario eliminare l'elemento id per generare l'errore sintattico in modo da eseguire correttamente il test case KO 13.
Abbiamo scaricato anche il CDA.xml relativo al test case 13 e validandolo, genera l'errore atteso poiché non è presente l'id di inFulfillmentOf/order.
Per quanto riguarda invece il test case 10, analizzando il CDA.xml in allegato e validandolo, viene generato l'errore terminologico poiché il code="NB" non è un codice presente all'interno del dizionario HL7 AdministrativeGender con codeSystem="2.16.840.1.113883.5.1".
In merito al test case KO 14, commentando o eliminando l'elemento code dell'entry/act della section Esame Eseguito, ed eseguendo la validazione viene generato l'errore sintattico atteso poiché il code è obbligatorio come elemento all'interno dell'entry/act.

**Comment by marcomontelatfujifilm** [comment]
Ho verificato che il Test 10 ora effettivamente fallisce con l'errore: "Almeno uno dei seguenti vocaboli non è censito: [CodeSystem: 2.16.840.1.113883.5.1 v2.1.0, Codes: NB]". Questo quando si invoca il servizio di validazione via REST. 

Nella mia implementazione dei test però faccio riferimento anche allo schematron pubblicato su it-fse-supporto (https://github.com/ministero-salute/it-fse-support/blob/main/validazione/schematron/schematronFSE_RAD.sch) che evidentemente non è aggiornato perché questo errore (e altri) non viene sollevato.

**Comment by marcomontelatfujifilm** [comment]
Per quanto riguarda gli altri test a mio avviso la validazione dovrebbe controllare si la presenza del tag, ad esempio <given> ma anche la sua valorizzazione come dice ad esempio il Test 9: "Il nome del paziente non valorizzato."

Perché se il CDA contiene il tag <given> vuoto comunque il dato manca e la validazione dovrebbe a mio avviso fallire. In sostanza potrei passare tutti i tag vuoti ?

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
