### ISSUE TITLE
[Regione Toscana] Gestione CERT_VACC UNK

### ISSUE THREAD

**Issue by Gianpr0** [ministero-salute/it-fse-support#1042]
Buongiorno,

in regione toscana stiamo implementando il documento cert_vacc e quando effettuiamo la create, a seguito di una verifica con il metodo status riscontriamo il seguente errore bloccante nel tipo evento SEND_TO_INI:
 {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-10-03T15:09:32.232+02:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 1089",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.f5f17456a62e3ad4619944093a9617b089afc3c42eae9ed04efa5e4b903c5491.b944375bfe^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-10-03T15:09:32.286+02:00"
        }

ci potreste fornire supporto? alleghiamo cda.
[certVaccUNK.zip](https://github.com/user-attachments/files/17244720/certVaccUNK.zip)

**Comment by vigliottim** [comment]
Buonasera,
seppure è corretto inserire un autore "unknown" ai fini della corretta validazione del CDA2, per l'Affinity Domain tale valore non è ammesso. 
Per questo motivo riceve un errore bloccante in _SEND_TO_INI_. 
Attendiamo un suo riscontro per sapere se può valorizzare l'elemento in esame oppure se è necessario richiedere una eventuale modifica.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso abbia bisogno di ulteriore supporto.
Grazie.
