### ISSUE TITLE
rsa - practiceSettingCode

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#1043]
Buongiorno

Sono in procinto di accreditare il referto di specialità ambulatoriale (RSA).
E' corretto assumere il valore AD_PSC107 (Poliambulatorio - Tabella 2.12-1) per il dato XDSDocumentEntry/@practiceSettingCode?

```
Assetto Organizzativo: AD_PSC107
Titolo: Nota di consulto
Tipologia Documento:
- Alto: REF
- Medio: 11488-4
- Basso: 2.16.840.1.113883.2.9.10.1.9.1 v. 1.1
```

**Comment by ds-tommaso** [comment]
Preciso che tali strutture sono viste come proprio poliambulatorio.
Potrebbero generare un referto unico con visita oculistica + sportiva non agonistica

**Comment by vigliottim** [comment]
Buonasera,
le confermiamo che è corretto adottare il valore _AD_PSC107_ per il metadato _XDSDocumentEntry.practiceSettingCode_ nel caso di _Poliambulatorio_, come riportato nella relativa tabella dell'Affinity Domain 2.5:

<img width="417" alt="image" src="https://github.com/user-attachments/assets/6db2763a-3a43-4821-b571-75e2d54a78b7">

Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by ds-tommaso** [comment]
Riapro l'issue, chiedendo una cnferma sulla valorizzazione dell'elemento componentOf, obbligatorio per i referti RAD/RSA.

componentOf->encompassingEncounter

id/@assigningAuthorityName Azienda (fisso)
id/@extension: 129950 (idenificativo richiesta)
id/@root: 2.16.840.1.113883.2.9.2.120202.4.6 (dove 120 codice regione, 202 codice asl)

componentOf->encompassingEncounter->location->healthCareFacility

id/@extension: 020000 (codice struttura)


```
<componentOf>
	<encompassingEncounter>
		<id assigningAuthorityName="Azienda" extension="129950" root="2.16.840.1.113883.2.9.2.120202.4.6"/>
		<code code="IMP" codeSystem="2.16.840.1.113883.1.11.13955" codeSystemName="ActEncounterCode" displayName="inpatient encounter"/>
		<effectiveTime value="20241003170541+0200"/>
		<location>
			<healthCareFacility>
				<id extension="020000" root="2.16.840.1.113883.2.9.4.1.3"/>
				<location>
					<name>EMATOLAB SNC</name>
				</location>
				<serviceProviderOrganization>
					<id assigningAuthorityName="Ministero della Salute" extension="020000" root="2.16.840.1.113883.2.9.4.1.3"/>
					<asOrganizationPartOf>
						<id extension="202" root="2.16.840.1.113883.2.9.4.1.1"/>
					</asOrganizationPartOf>
				</serviceProviderOrganization>
			</healthCareFacility>
		</location>
	</encompassingEncounter>
</componentOf>
```

**Comment by vigliottim** [comment]
Potrebbe cortesemente allegare il CDA2 completo?
Grazie.

**Comment by ds-tommaso** [comment]
[129950-cda.xml.txt](https://github.com/user-attachments/files/17246900/129950-cda.xml.txt)

**Comment by ds-tommaso** [comment]
Di seguito il documento CDA

[129950-cda.xml.txt](https://github.com/user-attachments/files/17246956/129950-cda.xml.txt)

**Comment by vigliottim** [comment]
Buonasera,
secondo le specifiche Hl7 Italia per la [Guida Implementativa del Referto di Specialistica Ambulatoriale (RSA)](https://www.hl7.it/realm-italiano/referto-di-specialistica-ambulatoriale-rsa/) il campo _ComponentOf/encompassingEncounter/id_ può essere definito nei seguenti modi:

- Nel caso in cui si tratti, come riportato nell’esempio, di un ricovero si necessità di compilare i campi come riportato nel seguente esempio
![image](https://github.com/user-attachments/assets/3f92657c-d1c4-4cc0-9c80-b3a2ab3aaf17)

- Nel caso in cui si tratti di referto redatto a seguito di un accesso ambulatoriale, si necessita di compilare i campi come riportato nel seguente esempio
![image](https://github.com/user-attachments/assets/3f92657c-d1c4-4cc0-9c80-b3a2ab3aaf17)

Per una corretta valorizzazione del campo _root_, si consiglia di utilizzare come riferimento l’OID Registry di HL7 Italia reperibile al seguente [link](https://www.hl7.it/wp-content/uploads/2024/04/OID.pdf).

Relativamente al campo _ComponentOf/encompassingEncounter/location/healthCareFacility/id/@extension_ si può fare riferimento alla seguente tabella
![image](https://github.com/user-attachments/assets/29bd9284-5bfd-45fb-bdc6-0e393036df1f)

Relativamente al campo _ComponentOf/encompassingEncounter/location/healthCareFacility/serviceProviderOrganization/id/@extension_ si può fare riferimento alle seguenti tabelle relativamente alle due casistiche
![image](https://github.com/user-attachments/assets/8851e8cd-5660-4ca6-bfd8-e0cb5b38a456)
![image](https://github.com/user-attachments/assets/ac3d7001-cadc-4a79-9f78-f7eb7687c64b)

Relativamente al campo _ComponentOf/encompassingEncounter/location/healthCareFacility/serviceProviderOrganization/asOrganizationPartOf/id/@extension_ si può fare riferimento alla seguente tabella:
![image](https://github.com/user-attachments/assets/b05ecf56-6f1e-44d8-a89f-e6973f76c269)

Rimaniamo a disposizione per ulteriori chiarimenti.
