### ISSUE TITLE
validazione CDA - referto in base64

### ISSUE THREAD

**Issue by rondellimediam** [ministero-salute/it-fse-support#1044]
Buongiorno, 
vorremmo per favore sapere se, all'interno del comando curl che invoca la validazione di un referto e del CDA allegato, sia possibile, al posto di passare il percorso dove è salvato il file (**-F "file=@C:/provaCDA.pdf;type=application/pdf"**), passare già il file in base64.

Lo chiediamo perchè abbiamo alcune realtà nelle quali i file dei referti sono salvati su dei server che non sono nella stessa rete dal quale viene lanciato il comando di validazione e potrebbero quindi esserci dei problemi di raggiungibilità dei file.

Grazie per l'attenzione!

**Comment by LucaRogledi** [comment]
Buongiorno, 
Dalle nostre verifiche il file in base64 non è idoneo per le chiamate ed è necessario specificare il percorso del file PDF in cui è iniettato il CDA.
Grazie

**Comment by rondellimediam** [comment]
Grazie per la risposta!
