### ISSUE TITLE
REGIONE BASILICATA UC1_Creazione: Comunicazione metadati non avvenuta 

### ISSUE THREAD

**Issue by BasilicataCrashProgramFSE** [ministero-salute/it-fse-support#1046]
Buongiorno,
relativamente al test case **UC1_Creazione,** abbiamo pubblicato con successo questi due documenti:

`"workflowInstanceId" : "2.16.840.1.113883.2.9.2.170201.4.4.fec6d56ebd9ff893eae5e0e647b896f232fc8d69006a644a17572d3267480d53.1377ad381b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
` 

`  "workflowInstanceId" : "2.16.840.1.113883.2.9.2.170201.4.4.aec574bafaae85bba4210a3039040342750a454f8150a0952e19e38b5e7053ba.1571807374^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
`

In seguito alla pubblicazione (STEP 1) non abbiamo ricevuto la comunicazione dei metadati da INI (STEP 3):

> _INI, previe verifiche sulla validità della richiesta e sull'identificativo dell'assistito, inoltra il messaggio  di comunicazione metadati al Registry Regionale_

**Comment by LucaRogledi** [comment]
Buongiorno, potreste cortesemente effettuare un nuovo test e informarci qualora il problema sia ancora presente?
Grazie.

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,

Abbiamo effettuato un altro test con esito positivo ma senza ricevere la transazione Comunica Metadati sul Registry Regionale, di seguito un caso di esempio:

{
 
    "traceID": "b8e4681a8b2888d9",
    "spanID": "b8e4681a8b2888d9",
    **"workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.2c7f7da7392dd9def48a19f713f2ecef0d411a0a1687ca42437a1420aa6abf99.4a38d5ddcb^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",**
    "timestamp": "2024-10-07T12:41:46.267Z",
}

Grazie mille

**Comment by LucaRogledi** [comment]
Buongiorno,
La informiamo che il Codice fiscale da lei utilizzato "PRVPVT81E03F052W" è stato censito ed è ora possibile assegnare i consensi e procedere con una nuova prova. 
Inoltre le segnaliamo che la comunicazione verso INI non risultava visibile perché lo step "SEND_TO_INI" riscontrava un errore bloccante. Per la verificare lo stato dello step SEND_TO_INI può utilizzare il servizio di status tramite workflowInstanceId riportato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#10-servizio-di-recupero-stato-transazione-per-workflowinstanceid). Restiamo a disposizione per ulteriore supporto. Grazie.

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,
E' possibile censire anche il Codice fiscale "PRVSST76A10G942K"?

**Comment by vigliottim** [comment]
Buonasera,
la informiamo che il codice fiscale "PRVSST76A10G942K" è stato attivato e può procedere a fornire i consensi.

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,

i codici fiscali PRVSST76A10G942K e PRVPVT81E03F052W, sono stati censiti come utenti?

Invocando i servizi ci viene restituito il seguente errore:

```
<Errore>
             <codEsito>1001</codEsito>
             <esito>Identificativo utente non valido</esito>
             <tipoErrore>Bloccante</tipoErrore>
             <fonte>FSE-INS-FE</fonte>
  </Errore>
```

E' possibile effettuare una verifica e nel caso censire le utenze?

Grazie

**Comment by vigliottim** [comment]
Potrebbe cortesemente allegare i workflowIstanceId delle chiamate effettuate? Grazie.

**Comment by vigliottim** [comment]
Potrebbe riprovare usando l'utente: PROVAX00X00X000Y?
Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, 
Le confermiamo che è corretto non trovare un indicizzazione sul regisrty regionale in quanto verificando tramite il servizio di Status viene riscontrato l'errore:

```
{
"eventType":"SEND_TO_INI",
"eventDate":"2024-10-10T17:07:58.000+02:00",
"eventStatus":"BLOCKING_ERROR",
"message":"SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 9000",
"workflowInstanceId":"2.16.840.1.113883.2.9.2.170201.4.4.b181cc1e5e9b4f441464d965890d77ef7883ce147ab0dafdf9f5c21afe87e2d1.16399fc4f8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
"expiringDate":"2025-10-10T17:07:58.016+02:00"
}
```

La pubblicazione è asincrona e per conoscere il risultato direttamente dal GTW è necessario effettuare una chiamata di Status.
L'errore potrebbe essere dovuto dal mancato utilizzo degli XSD aggiornati con le ultime modifiche presenti nel kit di sviluppo allinterno del drive del Dipartimento condiviso con le regioni.
Restiamo a disposizione, Grazie.

**Comment by BasilicataCrashProgramFSE** [comment]
Buonasera,
abbiamo aggiornato gli XSD,  ma non riceviamo le transazioni di comunica metadati sul Registry di test.
Potreste condividerci l'errore che state ricevendo per capire se magri l'errore può essere legato ai certificati?
Per permetterci di sbloccare la situazione, sarebbe possibile organizzare a stretto giro un test congiunto?
Grazie

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,

come già ripetuto continuiamo a ricevere lo stesso errore nonostante la modifica XSD.

Di seguito l'ultimo test effettuato:

`{
    "code": "SUCCESS",
    "userMessage": "Operazione conclusa con successo",
    "systemMessage": "",
    "status": 200,
    "traceID": "01b66a17ad7ee061",
    "spanID": "03caaac4e7e26583",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-10-17T12:18:32.625+02:00",
            "eventStatus": "SUCCESS",
            "message": null,
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "120",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.1fd010a7e7fd293201672f4257468619e614df61c80054ccf754b280bc31e857.dec76ae30e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "a16b110dce35b140",
            "issuer": "integrity:S1#170#REGIONEBASILICATATEST",
            "expiringDate": "2025-10-17T12:18:32.634+02:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-10-18T08:59:24.308+02:00",
            "eventStatus": "SUCCESS",
            "message": null,
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "120",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.1fd010a7e7fd293201672f4257468619e614df61c80054ccf754b280bc31e857.dec76ae30e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "8b082dd3b6c55a50",
            "issuer": "integrity:S1#170#REGIONEBASILICATATEST",
            "expiringDate": "2025-10-18T08:59:24.398+02:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-10-18T08:59:25.673+02:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 9000",
            "subject": null,
            "organizzazione": null,
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.1fd010a7e7fd293201672f4257468619e614df61c80054ccf754b280bc31e857.dec76ae30e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": null,
            "issuer": null,
            "expiringDate": "2025-10-18T08:59:25.740+02:00"
        }
    ],
    "timestamp": "2024-10-18T07:59:19.322Z"
}`

Riusciamo ad organizzare un test congiunto?

Grazie.

**Comment by g-maugeri-sogei** [comment]
Buonasera,
per l'ultimo tentativo (timestamp2024-10-18T07:59:19.322Z) il flusso si interrompe nell'unmarshalling della richiesta di comunicazione metadati fatta verso 
l'endpoint: https://fseservicetest.sanita.basilicata.it/services/RegFseComunicazioneMetadatiProxyTest.

Riuscite a recuperare la response che mandate come risposta in modo da poterla validare?
In allegato la request.
[request.txt](https://github.com/user-attachments/files/17436620/request.txt)

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,

Abbiamo simulato l'invio con la request.txt in allegato nell'ultima risposta verso l'endpoint di test https://fseservicetest.sanita.basilicata.it/services/RegFseComunicazioneMetadatiProxyTest  e otteniamo la risposta positiva.

In allegato la risposta che otteniamo 
[[BASILICATA]_ComunicaMetadatiRisposta.txt](https://github.com/user-attachments/files/17460865/BASILICATA._ComunicaMetadatiRisposta.txt)

Successivamente abbiamo provato un'altra pubblicazione che va in errore BLOCKING_ERROR sempre nello step SEND_TO_INI
Di seguito il dettagli del caso: 
{
        "code": "SUCCESS",
        "userMessage": "Operazione conclusa con successo",
        "systemMessage": "",
        "status": 200,
        "traceID": "e75a5b24c5a28d36",
        "spanID": "21b6865aff12ff55",
        "transactionData": [
            {
                "eventType": "VALIDATION",
                "eventDate": "2024-10-21T14:08:16.981+02:00",
                "eventStatus": "SUCCESS",
                "message": null,
                "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
                "organizzazione": "170",
                "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.ea9bd3911a161ad0c4b73517b84065728931f4ed466f0c47b69a88ffac1f2d53.e13bc6f979^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
                "traceId": "d13e619fc228befa",
                "issuer": "integrity:S1#170#REGIONEBASILICATATEST",
                "expiringDate": "2025-10-21T14:08:16.993+02:00"
            },
            {
                "eventType": "PUBLICATION",
                "eventDate": "2024-10-21T14:17:26.653+02:00",
                "eventStatus": "SUCCESS",
                "message": null,
                "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
                "organizzazione": "170",
                "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.ea9bd3911a161ad0c4b73517b84065728931f4ed466f0c47b69a88ffac1f2d53.e13bc6f979^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
                "traceId": "378363b57971682d",
                "issuer": "integrity:S1#170#REGIONEBASILICATATEST",
                "expiringDate": "2025-10-21T14:17:26.662+02:00"
            },
            {
                "eventType": "SEND_TO_INI",
                "eventDate": "2024-10-21T14:17:27.403+02:00",
                "eventStatus": "BLOCKING_ERROR",
                "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 9000",
                "subject": null,
                "organizzazione": null,
                "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.ea9bd3911a161ad0c4b73517b84065728931f4ed466f0c47b69a88ffac1f2d53.e13bc6f979^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
                "traceId": null,
                "issuer": null,
                "expiringDate": "2025-10-21T14:17:27.477+02:00"
            }
        ],
        "timestamp": "2024-10-21T12:17:45.930Z"
    }

Grazie

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
mockkando in locale la richiesta riportata in alto la chiamata funziona.
Potete verificare che la risposta che riceviamo e' effettivamente quella in allegato ?
Inoltre potete riprovare sul vostro server a lanciare la chiamata tradotta 
come vi arriva da INI che allego e girarmi la response ?

[log.txt](https://github.com/user-attachments/files/17472857/log.txt)

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,


Abbiamo trovato errori di SSLHandshakeException che coincide con l'orario della richiesta effettuata da INI.

Chiedo gentilmente di inviarci il certificato pubblico (o indicarci dove scaricarlo) da includere nel truststore del middleware regionale.

--Errore sul middleware Regionale:
2024-10-22 10:22:40,810 [-] [HTTPS-Listener I/O dispatcher-4] ERROR SourceHandler I/O error: General SSLEngine problem
javax.net.ssl.SSLHandshakeException: General SSLEngine problem..
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)

Inviando la request nel log otteniamo questa risposta:

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:com="http://comunicazionemetadatiricevuta.xsd.fse.ini.finanze.it" xmlns:tip="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it">
   <soapenv:Header/>
   <soapenv:Body>
      <com:ComunicazioneMetadatiRicevuta>
         <com:Esito>0000</com:Esito>
         <com:IdentificativoDocumento>urn:uuid:aa003118-fa8e-4315-9878-5bcc9c3a6ff1</com:IdentificativoDocumento>
      </com:ComunicazioneMetadatiRicevuta>
   </soapenv:Body>
</soapenv:Envelope>

Grazie mille

**Comment by lGiulianiSogei** [comment]
Buon pomeriggio, 
possiamo inviare il certificato della CA Sogei di Test a questo indirizzo mail?
crashprogram.FSE@regione.basilicata.it
 
grazie saluti

**Comment by BasilicataCrashProgramFSE** [comment]
Buon pomeriggio,

gentilmente chiediamo di inviare il certificato della CA Sogei di Test all'indirizzo **giuliano.garofalo@gpi.it**, con in copia i seguenti indirizzi: **nicola.mazzeo@regione.basilicata.it**, **rocco.ronca@gpi.it**.

Grazie.

**Comment by lGiulianiSogei** [comment]
Salve,
ho inviato la CA Sogei di test alle mail indicate, fateci sapere se serve altro per il test.

grazie saluti

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,

Grazie dei certificati, ora riceviamo la comunica metadati sul registry regionale.
Di seguito il caso che ha avuto successo.

Non abbiamo pero ricevuto la NofityComunicaMetadati in test su questo endpoint: 
**https://fseservicetest.sanita.basilicata.it/services/NotifyCommunicationMetadata_Service?wsdl**

Grazie mille

{
    "code": "SUCCESS",
    "userMessage": "Operazione conclusa con successo",
    "systemMessage": "",
    "status": 200,
    "traceID": "602d05c0296e6f46",
    "spanID": "de133b9c342e73f8",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-10-22T17:43:07.297+02:00",
            "eventStatus": "SUCCESS",
            "message": null,
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "170",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.2403a2e2496955f1a115eed617879baa7cb667684e794ad8ac198b4784b9505a.f37babea3d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "ff8e69eed80ccf58",
            "issuer": "integrity:S1#170#REGIONEBASILICATATEST",
            "expiringDate": "2025-10-22T17:43:07.306+02:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-10-22T17:45:54.809+02:00",
            "eventStatus": "SUCCESS",
            "message": null,
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "170",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.2403a2e2496955f1a115eed617879baa7cb667684e794ad8ac198b4784b9505a.f37babea3d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "600efc6d73ba7d53",
            "issuer": "integrity:S1#170#REGIONEBASILICATATEST",
            "expiringDate": "2025-10-22T17:45:54.819+02:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-10-22T17:45:56.500+02:00",
            "eventStatus": "SUCCESS",
            "message": null,
            "subject": null,
            "organizzazione": null,
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.2403a2e2496955f1a115eed617879baa7cb667684e794ad8ac198b4784b9505a.f37babea3d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": null,
            "issuer": null,
            "expiringDate": "2025-10-22T17:45:56.508+02:00"
        }
    ],
    "timestamp": "2024-10-22T16:05:50.070Z"
}

**Comment by g-maugeri-sogei** [comment]
Buonasera,
potete fornirmi il CF dell'assistito del tentativo sopra riportato?

**Comment by BasilicataCrashProgramFSE** [comment]
Buon pomeriggio,
il CF utilizzato è il seguente PRVPVT81E03F052W

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,
ci sono novità in merito all'analisi?

**Comment by g-maugeri-sogei** [comment]
Buonasera, 
il problema dovrebbe essere risolto. Qui l'invio di una vecchia richiesta:

2024-10-25 16:49:42.410 INFO  :  SOAP outbound Message :<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><NotifySubmitObjectsRequest xmlns="http://www.fascicolosanitario.gov.it/schema/typeSchemaNotifySubmitObjects"><HomeCommunityId>urn:oid:2.16.840.1.113883.2.9.2.170</HomeCommunityId><RepositoryUniqueId>2.16.840.1.113883.2.9.2.170.4.5.0002</RepositoryUniqueId><DocumentUniqueId>2.16.840.1.113883.2.9.2.170.4.4^201.AIRO.006012024000006_1</DocumentUniqueId><PatientId>PRVPVT81E03F052W^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</PatientId></NotifySubmitObjectsRequest></soapenv:Body></soapenv:Envelope>
2024-10-25 16:49:42.410 INFO  :  SOAP inbound Message :<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header xmlns:wsa="http://www.w3.org/2005/08/addressing"><wsa:MessageID>urn:uuid:bdad6001-9972-440e-8cb2-d823796bfd1b</wsa:MessageID><wsa:Action>http://www.fascicolosanitario.gov.it/wsdl/NotifyCommunicationMetadata/NotifyCommunicationMetadata_PortType/NotifySubmitObjectsResponse</wsa:Action><wsa:RelatesTo>urn:uuid:a45e4c3b-526d-4946-9c7d-82f04ad5f559</wsa:RelatesTo></soap:Header><soap:Body><NotifySubmitObjectsResponse xmlns="http://www.fascicolosanitario.gov.it/schema/typeSchemaNotifySubmitObjects"><Status>Success</Status></NotifySubmitObjectsResponse></soap:Body></soap:Envelope>

**Comment by BasilicataCrashProgramFSE** [comment]
Buon pomeriggio.

Perfetto grazie. 

Il test case UC1 può quindi considerarsi completato? Se si, procediamo con la chiusura della issue.

Grazie

**Comment by vigliottim** [comment]
Buon pomeriggio,
le confermiamo che il test case UC1 può considerarsi completato.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
