### ISSUE TITLE
Validazione Refererto di radiologia

### ISSUE THREAD

**Issue by rangemasterd** [ministero-salute/it-fse-support#1049]
La chiamata di validazione di un documento di tipo RAD ritorna la seguente eccezione

```json
{
  "traceID": "66ffae242b162c0b367de2c1f42746db",
  "spanID": "5f259350a93c0985",
  "type": "/msg/vocabulary",
  "title": "Errore vocabolario.",
  "detail": "È stata trovata almeno una versione non gestita di un dizionario: [2.16.840.1.113883.6.1 v2.73]",
  "status": 400,
  "instance": "/validation/error",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.100.4.4.1bd31321f02ce5dc8ceac44df8158ad06f6471a627f7378cabd4dce369281a50.acedd800e1^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```
Il pdf di test inviato per la validazione: [CDA.pdf](https://github.com/user-attachments/files/17255894/CDA.pdf)

**Comment by vigliottim** [comment]
Buongiorno,
l'errore ricevuto potrebbe essere causato dalla valorizzazione dell'attributo _section[ID="Quesito_Diagnostico"]/code/@codeSystemVersion_:

<img width="630" alt="image" src="https://github.com/user-attachments/assets/d5151565-92be-45d4-b070-8f9b119e0a87">

Infatti, consultando il file [terminology-2.16.840.1.113883.6.1.csv](https://raw.githubusercontent.com/ministero-salute/it-fse-catalogs/refs/heads/main/terminology/2.16.840.1.113883.6.1.csv), il _codeSystemVersion_ corretto da associare all'elemento in esame è _2.77_:

![image](https://github.com/user-attachments/assets/84433326-3ada-4a3a-9033-cada6c7432f2)

La invitiamo a riprovare modificando il CDA2 come indicato di seguito:

<img width="504" alt="image" src="https://github.com/user-attachments/assets/cf14b6d6-953f-4b0e-a4c3-88a67d0f4432">


Rimaniamo a disposizione nel caso in cui abbia bisogno di ulteriore supporto.

**Comment by rangemasterd** [comment]
Confermo che aggiornando il codeSystemVersion la validazione passa correttamente.
Grazie per il supporto
