### ISSUE TITLE
Errori di tipo "VERIFICA_NON_SUPERATA" in validazione LDO

### ISSUE THREAD

**Issue by Beatrice164** [ministero-salute/it-fse-support#105]
Chiediamo delucidazioni sugli errori ricevuti in fase di acceditamento del CDA di LDO.
il primo punto riguarda questo errore : "<error code='067' attribute='code' actual = '' expected = '46241-6'>ClinicalDocument/component/structuredBody/component /section[id='Motivo_Ricovero']/code</error>"
Il validatore sembra basarsi sul valore dell'attributo id del tag &lt;section&gt;. Questo attributo non è documentato nelle specifiche HL7.
Mi confermate che l'attributo è comunque obbligatorio per la validazione ?
Il secondo punto riguarda le lettere accentuate:
Riceviamo l'errore &lt;error code='026' attribute='displayName' actual = 'Obiettivit� Clinica' expected = 'Obiettività Clinica Clinical Finding Criticality Stato'&gt;
Nell'xml del nostro CDA abbiamo inserito _displayName="Obiettività Clinica"_ come nell'esempio pubblicato su github (https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/LDO.xml)
L'ultimo punto riguarda l'errore &lt;error code='031' attribute='displayName' actual = 'Esami diagnostici e/o di laboratorio significativi' expected = 'Esami diagnostici e/o di laboratorio significativi.'&gt;
La specifica HL7 non prevede il punto finale.
Grazie per il supporto

**Comment by IStacchiotti** [comment]
Grazie per aver aperto la segnalazione. Potrebbe cortesemente allegare il cda che sta tentando di validare?

**Comment by Beatrice164** [comment]
In allegato quanto richiesto
Beatrice

Da: IStacchiotti ***@***.***>
Inviato: giovedì 16 febbraio 2023 12:18
A: ministero-salute/it-fse-support ***@***.***>
Cc: Beatrice Clemente ***@***.***>; Author ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Errori di tipo "VERIFICA_NON_SUPERATA" in validazione LDO (Issue #105)

Grazie per aver aperto la segnalazione. Potrebbe cortesemente allegare il cda che sta tentando di validare? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message
ZjQcmQRYFpfptBannerStart
CAUTION: This email might originate from outside the organization.
ZjQcmQRYFpfptBannerEnd

Grazie per aver aperto la segnalazione. Potrebbe cortesemente allegare il cda che sta tentando di validare?

**Comment by IStacchiotti** [comment]
Il caso OK fornito non è conforme e in linea con l'excel che abbiamo fornito per potersi accreditare.
In dettaglio:
- l'id della section è scritto erroneamente poiché nel cda fornito è Motivo_del_Ricovero;
- l'errore relativo al primo displayName è sulla dicitura dei possibili displayName associati ai code col seguente path ClinicalDocument/component/structuredBody/component/section[@ID="Allergie"]/entry/act/entryRelationship/observation/entryRelationship/observation/code, ovvero:
    - Obiettività Clinica;
    - Clinical Finding;
    - Criticality;
    - Stato.
- l'errore relativo al secondo displayName è sempre sulla dicitura errata nel cda fornito associato al code del seguente path ClinicalDocument/component/structuredBody/component /section[@ID="Esami_eseguiti_durante_il_ricovero"]/code, ovvero:
 - Esami diagnostici e/o di laboratorio significativi. 
Pertanto si chiede di accreditarsi nuovamente con la generazione di un nuovo cda conforme all'excel fornito.

**Comment by Beatrice164** [comment]
La questione degli id era chiara ma volevamo solo una vostra conferma in quanto nelle specifiche HL7 Italia non sono indicati e per segnalare che sono sbagliati anche nel modello di test da voi fornito (https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/LDO.xml)
In merito alla segnalazione sul valore "obiettività" il CDA da noi fornito ci risulta corretto in un editor di testo ma non da browser, potrebbe essere un problema di Encoding delle lettere accentate.
infine in merito all'ultimo punto seguendo le indicazioni del file Excel abbiamo capito che deve quindi essere inserito il punto finale, ma solo per questa descrizione.

**Comment by IStacchiotti** [comment]
Buongiorno Beatrice, le chiediamo cortesemente di verificare di aver impiegato come sistema di codifica l'utf8 (e non eventuali altri sottosistemi). Ci faccia sapere se il problema persiste. Grazie.

**Comment by Beatrice164** [comment]
Problema risolto
Grazie

Inviato da Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: IStacchiotti ***@***.***>
Inviato: Thursday, March 16, 2023 9:46:34 AM
A: ministero-salute/it-fse-support ***@***.***>
Cc: Beatrice Clemente ***@***.***>; Author ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Errori di tipo "VERIFICA_NON_SUPERATA" in validazione LDO (Issue #105)

Buongiorno Beatrice, le chiediamo cortesemente di verificare di aver impiegato come sistema di codifica l'utf8 (e non eventuali altri sottosistemi). Ci faccia sapere se il problema persiste. Grazie. — Reply to this email directly, view
ZjQcmQRYFpfptBannerStart
CAUTION: This email might originate from outside the organization.

ZjQcmQRYFpfptBannerEnd

Buongiorno Beatrice, le chiediamo cortesemente di verificare di aver impiegato come sistema di codifica l'utf8 (e non eventuali altri sottosistemi). Ci faccia sapere se il problema persiste. Grazie.

**Comment by IStacchiotti** [comment]
Grazie per il feedback, procediamo alla chiusura del presente.
