### ISSUE TITLE
[ITI-57] lid errato nella transazione Update

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#1050]
Buongiorno,
eseguendo i test su un update reiterato ci ritorna indietro una ITI-42 con l'elemento "lid" valorizzato in maniera errata, in quanto presenta il valore dell' "id" della transazione precedente e non quello della prima versione. 

Grazie, rimaniamo a disposizione

**Comment by FSESardegna** [comment]
Buongiorno,
alleghiamo per maggior comprensione le seguenti request e response:
[1-ITI42-request_submit.txt](https://github.com/user-attachments/files/17279155/1-ITI42-request_submit.txt)
[2-ITI18_response_before_first_update.txt](https://github.com/user-attachments/files/17279156/2-ITI18_response_before_first_update.txt)
[3-ITI42-request_first_update.txt](https://github.com/user-attachments/files/17279157/3-ITI42-request_first_update.txt)
[4-ITI18-response_before_second_update.txt](https://github.com/user-attachments/files/17279159/4-ITI18-response_before_second_update.txt)
[5-ITI42-request_second_update.txt](https://github.com/user-attachments/files/17279160/5-ITI42-request_second_update.txt)

Si segnala che, nella risposta alla ITI18 antecedente il secondo aggiornamento, comunichiamo correttamente il valore **lid**="urn:uuid:341dbfc1-e449-494e-89db-7df369e386b7". Tuttavia, nella successiva richiesta ITI42 di aggiornamento, il valore **lid** viene assegnato con l'identificativo dell'ExtrinsicObject relativo all'aggiornamento precedente (lid="urn:uuid:341dbfc1-e449-494e-89db-7df369e386b7"), facendo quindi riferimento alla seconda versione. Il valore **lid** all'interno del tag ExtrinsicObject dovrebbe invece riferirsi all' **id** della prima  versione del documento.



Grazie, restiamo in attesa di un vostro riscontro.

**Comment by assistenza-fsevda** [comment]
Buongiorno,
ci sono delle novità o delle previsioni di tempistica in merito a questo issue? Anche dalla Regione Valle d'Aosta stiamo riscontrando la stessa anomalia.
Se può essere comodo vi allego il log delle transazioni ricevute ed inviate da INI:
[Regione_020_MetadataUpdate.txt](https://github.com/user-attachments/files/17305348/Regione_020_MetadataUpdate.txt)

Anche nel nostro caso nel lid del secondo update inviato da INI troviamo l'id della precedente versione.
In caso di bisogno rimaniamo a disposizione.

Grazie anticipatamente

**Comment by vigliottim** [comment]
Buonasera,
è stato appena rilasciato un aggiornamento.
Le chiediamo gentilmente di riprovare e darci un feedback.
Grazie.

**Comment by ldelcol** [comment]
buongiorno,
Regione 020 in qualità di RDE=RDA conferma risoluzione dell'anomalia.
grazie

**Comment by vigliottim** [comment]
Grazie per il gentile riscontro.
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per altre richieste di supporto.
