### ISSUE TITLE
403 AuthorizationContentDeny

### ISSUE THREAD

**Issue by acolzi** [ministero-salute/it-fse-support#1051]
Buongiorno,
sto effettuando dei test di validazione.
Sto ricevendo il seguente errore tramite applicativo
{
  "govway_id": "7f88e786-8460-11ef-a6bf-005056ae7395",
  "detail": "Unauthorized request content",
  "type": "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
  "title": "AuthorizationContentDeny",
  "status": 403
}

la stessa richiesta effettuata con gli stessi token fatta con postman mi da il seguente errore
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "df9363e4-8460-11ef-b8bd-005056ae54fa"
}

E' possibile avere i dettagli di questi 2 errori?
Grazie

**Comment by vigliottim** [comment]
Buongiorno,
dalle analisi svolte sui log delle chiamate da lei effettuate, l'errore ricevuto sembrerebbe essere causato dalla valorizzazione del claim _iss_:

![image](https://github.com/user-attachments/assets/ce1e049d-6a23-4ba5-bf90-c5d504324f49)

Infatti, il _common name_ adottato non risulta coerente e differisce tra il _X-Security-Token_ e i token _Authorization Bearer_ e _FSE-JWT-Signature_:

_X-Security-Token:_
<img width="248" alt="image" src="https://github.com/user-attachments/assets/4ffc2f21-471f-479c-9d33-82c9c5c33130">

_Authorization Bearer Token:_
<img width="285" alt="image" src="https://github.com/user-attachments/assets/2a3bab42-9c7f-43ae-b5c9-e18ac3fcc6f3">

_FSE-JWT-Signature Token:_
<img width="277" alt="image" src="https://github.com/user-attachments/assets/867804bb-934b-416c-9687-e9b84ded466b">

Le chiediamo effettuare la correzione e riprovare.
Grazie.

**Comment by acolzi** [comment]
Buongiorno,
Ho fatto diverse prove, alla fine mettendo in iss
auth:S1#111#ABLIASRLXX
integrity:S1#111#ABLIASRLXX
non ho più l'errore 403, altri errori che verifico prima di eventualmente chiedere aiuto.
In ogni caso ho utilizzato il certificato S1, non A1 per iss

il common name pensavo fosse comunque quello dei csr, ovvero
S1#090201REFABLIA e
A1#090201REFABLIA
grazie

**Comment by vigliottim** [comment]
Grazie a lei, rimaniamo a disposizione se dovesse avere bisogno di ulteriore supporto.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
Grazie.
