### ISSUE TITLE
UNKNOWN_WORKFLOW_ID

### ISSUE THREAD

**Issue by acolzi** [ministero-salute/it-fse-support#1053]
Stiamo effettuando delle chiamate di validazione con la seguente requestbody
{
    "mode": "ATTACHMENT",
    "activity": "VALIDATION",
    "healthDataFormat": "CDA"
}
L'errore che riceviamo è il seguente:
{
  "traceID": "64ee3203379daead",
  "spanID": "64ee3203379daead",
  "instance": "/request-missing-field",
  "detail": "Errore durante la conversione da json a oggetto it.finanze.sanita.fse2.ms.gtw.dispatcher.dto.request.ValidationCDAReqDTO",
  "type": "/msg/mandatory-element",
  "title": "Campo obbligatorio non presente.",
  "workflowInstanceId": "UNKNOWN_WORKFLOW_ID",
  "status": 400
}
Andando quindi sulla documentazione, paragrafo 13.2, effettivamente vedo workflowInstanceId come obbligatorio.
Effettuiamo quindi nuova richiesta con request body
{
    "mode": "ATTACHMENT",
    "activity": "VALIDATION",
    "healthDataFormat": "CDA",
    "workflowInstanceId": "1728300948065117"
}
ed otteniamo l'errore
{
  "govway_id": "ac2f56f8-849d-11ef-a6bf-005056ae7395",
  "detail": "Request content not conform to API specification: Validation error(s) :\nbody.requestBody: Additional property 'workflowInstanceId' is not allowed. (code: 1000)\nFrom: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.<additionalProperties>\n",
  "type": "https://govway.org/handling-errors/400/
Non riusciamo quindi a capire dove è esattamente l'errore.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
analizzando i log della chiamata da lei effettuata, è emerso che la section contenente la _requestBody_ non è stata strutturata correttamente:

_Content-Disposition: form-data; name="requestBody" <s>; filename="{%22mode%22:%22ATTACHMENT%22,%22activity%22:%22VALIDATION%22,%22healthDataFormat%22:%22CDA%22}"</s>
Content-Type: application/json<s>; charset=utf-8</s>
{"mode":"ATTACHMENT","activity":"VALIDATION","healthDataFormat":"CDA"}_

_--7f091106-207f-44b1-a407-4ac75be2cae0
Content-Disposition: form-data; name="file"; filename="20665492_referto.pdf"
Content-Type: application/pdf_

La invitiamo a riprovare dopo aver effettuato le correzioni riportate sopra.
Grazie.

**Comment by acolzi** [comment]
ok, risolto cambiando alcuni dettagli in chiamata, grazie
