### ISSUE TITLE
Error while executing validation on xsd schema

### ISSUE THREAD

**Issue by acolzi** [ministero-salute/it-fse-support#1056]
Buonasera,
siamo arrivati credo alla sintassi cda.xml.
Ho fatto il test tramite fse certifier ed ho 
[TEST SUPERATI]
Test case OK con ids: [1]
[TEST NON VERIFICABILI]
Test case KO con ids: []
[TEST FALLITI]
Test case KO con ids: []
se invio il pdf con il cda, ottengo il seguente errore
{
  "traceID": "478c40ee0a9f5a31",
  "spanID": "478c40ee0a9f5a31",
  "instance": "/validation/error",
  "detail": "Error while executing validation on xsd schema",
  "type": "/msg/syntax",
  "title": "Errore di sintassi.",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.e15bd24a959bcf9d4e463a6c9a0862bd15d215f2935e4ce671cf8c0f6528ed9c.08ab5c4138^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "status": 400
}
Come faccio a sapere l'errore? C'è un qualcosa che mi permette di verificare la sintassi senza sottomettervi tutte le volte il risultato?
Grazie in anticipo

**Comment by vigliottim** [comment]
Buonasera,
l'errore da lei ricevuto è un errore sintattico generico e non è possibile risalire facilmente alla sua causa.
Può allegare il CDA2 utilizzato in modo da fornirle supporto in merito?
Grazie.

**Comment by acolzi** [comment]
[20665492_CDA.xml.zip](https://github.com/user-attachments/files/17280530/20665492_CDA.xml.zip)
Buonasera,
in allegato il cda. Il nome allegato sul pdf è comunque cda.xml

**Comment by vigliottim** [comment]
Da una prima analisi effettuata sul CDA2 da lei inviato, alcuni elementi obbligatori risultano valorizzati con caratteri speciali oppure non risultano valorizzati:
<img width="613" alt="image" src="https://github.com/user-attachments/assets/636b4faa-50ab-4d93-9e2c-36847486158d">
<img width="505" alt="image" src="https://github.com/user-attachments/assets/8af5278d-eb15-41bf-bdbb-9f9281c216b3">
<img width="532" alt="image" src="https://github.com/user-attachments/assets/e8a0c0ac-4b61-4977-a809-3c791dbc382f">
<img width="534" alt="image" src="https://github.com/user-attachments/assets/a3d8b76f-48a9-45cd-ba1c-90876bf8fd25">
La preghiamo di riprovare rimuovendo i caratteri speciali e valorizzando opportunamente tali elementi.
Grazie.

**Comment by acolzi** [comment]
Buongiorno,
 ho corretto tutto il file CDA. Alla fine arrivo al seguente errore:
[20665492_CDA.xml.zip](https://github.com/user-attachments/files/17290117/20665492_CDA.xml.zip)

 {
  "traceID": "fc9b92349f097780",
  "spanID": "fc9b92349f097780",
  "instance": "",
  "detail": "Duplicate key 2.16.840.1.113883.2.9.4.3.2",
  "type": "/msg/generic-error",
  "title": "Errore generico.",
  "status": 500
}
A cosa si riferisce?
grazie

**Comment by LucaRogledi** [comment]
Buongiorno,
L'errore da lei indicato viene riscontrato quando si utilizza lo stesso valore in entrambi gli id contenuti nel tag PatientRole.
Secondo quanto riportato nella [documentazione HL7 RAD](https://www.hl7.it/wp-content/uploads/2024/04/HL7IT-IG_CDA2_RAD-v1.1-S.pdf) il secondo id/@extension dovrebbe essere valorizzato con "Il numero di identificazione dell’assistito nel sistema PACS in cui sono custodite le immagini."

![image](https://github.com/user-attachments/assets/f40b4bba-1973-4d91-a50e-edfd239b1248)

![image](https://github.com/user-attachments/assets/249d67c3-33ae-4bfe-b967-7ff3fb65499e)

![image](https://github.com/user-attachments/assets/91fa4f14-a2e1-4a34-b5a8-c3d9b3b93ce8)

La invitiamo a riprovare utilizzando la valorizzazione corretta per il secondo id.
Grazie

**Comment by acolzi** [comment]
Buongiorno,
ok, torna quello che c'è scritto.. solo che non saprei cosa mettere come OID. Il pacs è interno alla azienda, ovvero l'azienda deve avere un suo OID che devo richiedere? Oppure è dell'azienda che fornisce l'apparato ?
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, 
l'OID corrisponde allo spazio di identificazione usato nell’Azienza che custodisce il PACS nel quale sono contenute le immagini.
Pertanto per la valorizzazione corretta degli attributi del secondo tag id contenuto in PatientRole dovrebbe fare richiesta all’Azienza che custodisce il PACS.
Grazie

**Comment by acolzi** [comment]
OK. Perdonatemi la domanda... il mio cliente effettua sia radiografie che ecografie. Le immagini radiografiche sono gestite da una macchina che effettua l'rx e che poi invia  al visualizzatore Iqview tramite il quale il medico visualizza le immagini e compila il referto. Tutte le immagine, con la sua numerazione e identificazione, vengono registrate su più unità di backup, oltre ad essere inviate ad un robot per la registrazione su cd. Di fatto sono loro stessi che custodiscono le immagini.

Questa è stata una loro scelta, ovvero affidarsi a copie interne di tutte le immagini e non ad un sistema pacs. 
Da quanto capisco però sembra che un sistema pacs diventi obbligatorio per l'invio del fascicolo sanitario, possibile?

In ogni caso,  è possibile immettere un codice OID che mi permetta di proseguire con i miei test?
grazie

**Comment by vigliottim** [comment]
Buon pomeriggio,
per proseguire con i suoi test può usare un placeholder, come mostrato nell'esempio: [RAD.xml]([https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/RAD.xml)](https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/RAD.xml).), se non ha a disposizione gli identificativi dell'assistito nel sistema PACS in cui sono custodite le immagini associate al referto. 
In alternativa, può usare un _nullFlavor_, come specificato sulla [guida HL7 Italia per RAD](https://www.hl7.it/wp-content/uploads/2024/04/HL7IT-IG_CDA2_RAD-v1.1-S.pdf):
<img width="493" alt="image" src="https://github.com/user-attachments/assets/7a7306a9-ffc5-4e6d-ba50-d4b257b2e5b5">
Inoltre, specifichiamo che avere un sistema pacs non è obbligatorio ma consigliabile per l'integrazione con FSE.
Rimaniamo a disposizione per chiarimenti.

**Comment by acolzi** [comment]
ok. sono arrivato in fondo. Mi sono fermato alla codifica dell'esame eseguito (5.5.4.1). Non sarebbe un problema utilizzare la codifica ICD-9-CM ma ho trovato a giro una serie di excel con una codifica che non torna ad esempio con l'esempio della documentazione (codifica 87.3). 
Una per tutti sul sito 
https://www.eumed.it/icd9cm/index.php?
trovo delle codifiche e potrebbero anche essere plausibili. Altrimenti c'è un altro riferimento preciso?
il code system è quello definito nella documentazione (2.16.840.1.113883.6.103)?
Grazie

**Comment by vigliottim** [comment]
Buongiorno,
per codificare gli esami di RAD si consiglia di utilizzare le codifiche LOINC o ICD-9-CM che comunque non vengono regolati da linee guida.
Condividiamo di seguito il link al sito Ministeriale dove poter scaricare il manuale ICD-9-CM:
https://www.salute.gov.it/portale/assistenzaOspedaliera/dettaglioContenutiAssistenzaOspedaliera.jsp?id=1278&area=ricoveriOspedalieri&menu=classificazione.
Nel caso della codifica ICD-9-CM, il codesystem da adottare è _"2.16.840.1.113883.6.103"_, come indicato nella [guida HL7 Italia per RAD](https://www.hl7.it/wp-content/uploads/2024/04/HL7IT-IG_CDA2_RAD-v1.1-S.pdf):
![image](https://github.com/user-attachments/assets/21a8a38c-850b-45b1-a9fd-0a1b3c36211c)
![image](https://github.com/user-attachments/assets/f16c082a-fbd6-4019-ae6a-1a94aac1af2e)

**Comment by acolzi** [comment]
Buongiorno, ok.... validazione andata a buon fine. Grazie!

**Comment by vigliottim** [comment]
Grazie per il suo gentile feedback.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
