### ISSUE TITLE
Errore purposeofuse TREATMENT

### ISSUE THREAD

**Issue by federicolau** [ministero-salute/it-fse-support#1057]
Ciao,

stiamo ricevendo errore dal Gateway sulle richieste di aggiornamento metadati, sostituzione documento e cancellazione.
Dalle [dalle request di recupero riferimenti documento](https://github.com/user-attachments/files/17280482/RecuperoRiferimenti.txt)  ricevute da INI ci siamo accorti che l'attributo **urn:oasis:names:tc:xspa:1.0: subject:purposeofuse** è valorizzato con la stringa **TREATMENT** mentre ci aspettiamo il valore **UPDATE**, come da specifiche INI:

<img width="484" alt="immagine" src="https://github.com/user-attachments/assets/88e0c92f-d9cb-40c7-8b87-071440c08828">

Rimaniamo in attesa di un vostro feedback.

Grazie

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
è stato rilasciato un aggiornamento.
Le chiediamo gentilmente di riprovare e darci un feedback.
Grazie.

**Comment by vigliottim** [comment]
@federicolau 
Le chiediamo gentilmente di effettuare un nuovo test e confermarci che l'errore segnalato non si ripresenta.
Grazie.

**Comment by NicoRomb** [comment]
Buongiorno, sono un collega di **@federicolau**, le confermo che a seguito dell'aggiornamento, l'errore segnalato non si ripresenta più per i servizi di cancellazione e sostituzione documento, ma continua a persistere per quello di aggiornamento metadati.
Grazie.

**Comment by vigliottim** [comment]
Grazie per il gentile feedback.
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per altre richieste di supporto.
