### ISSUE TITLE
Crash Program - Regione Lazio - Pubblicazione documento AAAEEE01A01H501Q

### ISSUE THREAD

**Issue by giosil** [ministero-salute/it-fse-support#1059]
Salve, a fronte della pubblicazione di un documento per il CF AAAEEE01A01H501Q otteniamo una risposta di success:

{"traceID":"417dd62a63485a39","spanID":"417dd62a63485a39","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.fe950b061168e1e4cd1990f36925d21f40f17ce24a5913e16ba60fcf9451d0f8.731407d549^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

tuttavia ai servizi XDS esposti per INI non è arrivata la comunicazione di metadati né la corrispondente notifica.
Questo ha dato luogo al fallimento della delete:

{"traceID":"e4f962ae87eadc5d","spanID":"e4f962ae87eadc5d","type":"/msg/ini-error","title":"Ini error.","detail":"{\"traceID\":\"e4f962ae87eadc5d\",\"spanID\":\"2bf1fb2d72346694\",\"type\":\"/errors/fields\",\"title\":\"Missing\",\"detail\":\"Non è stato possibile recuperare i riferimenti con i dati forniti in input\",\"instance\":\"/ini\"}","status":404,"instance":"/msg/service-error/ini"}

Poiché i metadati non sono stati comunicati, i servizi XDS non hanno potuto restituire alcun riferimento.
Gli stessi problemi si sono presentati nella sostituzione e nell'aggiornamento dei metadati:

{"traceID":"4fa3db2fcf213aa1","spanID":"4fa3db2fcf213aa1","type":"/msg/ini-error","title":"Ini error.","detail":"{\"traceID\":\"4fa3db2fcf213aa1\",\"spanID\":\"2f2f0fb812230925\",\"type\":\"/errors/fields\",\"title\":\"Missing\",\"detail\":\"Non è stato possibile recuperare i riferimenti con i dati forniti in input\",\"instance\":\"/ini\"}","status":404,"instance":"/msg/service-error/ini"}

{"traceID":"28c536423211b74f","spanID":"28c536423211b74f","type":"/errors/fields","title":"Missing","detail":"Non è stato possibile recuperare i riferimenti con i dati forniti in input","instance":"/ini"}

Avevamo comunicato già ieri, nel corso della call plenaria, di aver riscontrato tale problema.
Restiamo in attesa di un vostro gentile riscontro. Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
interrogando il servizio status per la chiamata di pubblicazione con _"workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.fe950b061168e1e4cd1990f36925d21f40f17ce24a5913e16ba60fcf9451d0f8.731407d549^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"_ si nota un errore bloccante in _SEND_TO_INI_:

_{
    "traceID": "1765cd6cacd78dcf",
    "spanID": "49878cc7b71cfd47",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-10-07T18:00:34.139+02:00",
            "eventStatus": "SUCCESS",
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "120",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.fe950b061168e1e4cd1990f36925d21f40f17ce24a5913e16ba60fcf9451d0f8.731407d549^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "91306d5aa00c9695",
            "issuer": "integrity:S1#120#REGIONELAZIOTEST",
            "expiringDate": "2025-10-07T18:00:34.155+02:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-10-07T18:00:35.867+02:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.120.4.4^120.20241007180028",
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "CON",
            "organizzazione": "120",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.fe950b061168e1e4cd1990f36925d21f40f17ce24a5913e16ba60fcf9451d0f8.731407d549^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "417dd62a63485a39",
            "issuer": "integrity:S1#120#REGIONELAZIOTEST",
            "expiringDate": "2025-10-07T18:00:35.877+02:00"
        },
        **{
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-10-07T18:00:36.195+02:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R166CODE CONTEXT:Wrong value of referenceIdList",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.fe950b061168e1e4cd1990f36925d21f40f17ce24a5913e16ba60fcf9451d0f8.731407d549^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-10-07T18:00:36.256+02:00"
        }**
    ]
}_

La rimandiamo al seguente commento per controllare che abbia valorizzato correttamente il campo _referenceIdList_: https://github.com/ministero-salute/it-fse-support/issues/1033#issuecomment-2383498836
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by giosil** [comment]
Buongiorno, nella risposta alla segnalazione riferita è riportato:

"INI verifica il valore dell'NRE. Pertanto, è necessario usare un NRE reale attivo in validazione.
In alternativa, se non dovesse possederlo, può eliminare le sezione inFulfillmentOf nel CDA2."

Togliendo tuttavia la sezione inFulfillmentOf  la validazione non passa.
Come procedere? Nei test non disponiamo di NRE validi.

**Comment by LucaRogledi** [comment]
Buongiorno, potrebbe gentilmente riportare la response completa ricevuta dal gateway dopo la chiamate senza la sezione inFulfillmentOf all'interno del CDA? Inoltre se possibile le chiediamo di allegare il CDA utilizzato. Grazie

**Comment by giosil** [comment]
Togliendo la sezione inFulfillmentOf, in validazione otteniamo:

{"traceID":"cd8ba2a73ca0cbbb","spanID":"cd8ba2a73ca0cbbb","type":"/msg/semantic","title":"Errore semantico.","detail":"[ERRORE-31| In ClinicalDocuemnt DEVE essere presente almeno un elemento 'inFulfillmentOf'. ]","status":422,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.0d666bc93a44d720f052ff6e43877df2ebfaca1f7cf73996cf2c3f8c96784767.e8e55fe8f9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

Non andando a buon fine la validazione la procedura non prosegue con la pubblicazione.
Di seguito il CDA (derivato dai vostri esempi pubblicati togliendo la sezione inFulfillmentOf):

<ClinicalDocument xmlns="urn:hl7-org:v3" xmlns:mif="urn:hl7-org:v3/mif" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:lab="urn:oid:1.3.6.1.4.1.19376.1.3.2" xmlns:sdtc="urn:hl7-org:sdtc">
	<realmCode code="IT"/>
	<typeId root="2.16.840.1.113883.1.3" extension="POCD_MT000040UV02"/>
	<templateId root="2.16.840.1.113883.2.9.10.1.1" extension="1.3" assigningAuthorityName="HL7 Italia"/>
	<id root="2.16.840.1.113883.2.9.2.120.4.4" extension="120.20241008145608" assigningAuthorityName="Regione Lazio"/>
	<code code="11502-2" codeSystem="2.16.840.1.113883.6.1"  codeSystemName="LOINC" displayName="Referto di laboratorio"/>
	<title>Referto di Laboratorio</title>
	<effectiveTime value="20241008145608+0200"/>
	<confidentialityCode code="N" codeSystem="2.16.840.1.113883.5.25" codeSystemName="HL7 Confidentiality" displayName="Normal"/>
	<languageCode code="it-IT"/>
	<setId root="2.16.840.1.113883.2.9.2.120.4.4" extension="120.20241008145608" assigningAuthorityName="Regione Lazio"/> 
	<versionNumber value="1"/> 
	<recordTarget typeCode="RCT" contextControlCode="OP">
		<patientRole classCode="PAT">
			<id root="2.16.840.1.113883.2.9.4.3.2" extension="AAAEEE01A01H501Q" assigningAuthorityName="MEF"/>
			<addr use="H">
				<country>100</country>
				<state>120</state>
				<county>RM</county>
				<city>Roma</city>
				<censusTract>058091</censusTract>
				<postalCode>00187</postalCode>
				<streetAddressLine>Via Prova 12</streetAddressLine>
			</addr> 
			<addr use="WP">
				<country>100</country>
				<state>120</state>
				<county>RM</county>
				<city>Roma</city>
				<censusTract>058091</censusTract>
				<postalCode>00138</postalCode>
				<streetAddressLine>Via Prova 12B</streetAddressLine>
			</addr>
			<telecom use="WP" value="mailto:prova.provax@example.com"/>
			<telecom use="MC" value="tel:3340000000"/>
			<patient>
				<name>
					<family>Paziente</family>
					<given>Test</given>
				</name>
				<administrativeGenderCode code="M" codeSystem="2.16.840.1.113883.5.1" codeSystemName="HL7 AdministrativeGender" displayName="MASCHIO"/> 
				<birthTime value="19220101"/>
				<birthplace>
					<place>
						<addr>
							<country>100</country>
							<state>120</state>
							<county>RM</county>
							<city>Roma</city>
							<censusTract>058091</censusTract>
						</addr>
					</place>
				</birthplace>
			</patient>
		</patientRole>
	</recordTarget>
	<author>
		<time value="20241008145608+0200"/>
		<assignedAuthor classCode="ASSIGNED">
			<id root="2.16.840.1.113883.2.9.4.3.2" extension="PROVAX00X00X000Y" assigningAuthorityName="MEF"/>
			<addr>
				<country>100</country>
				<state>120</state>
				<county>RM</county>
				<city>Roma</city>
				<censusTract>058091</censusTract>
				<postalCode>00184</postalCode>
				<streetAddressLine>Via Prova 7</streetAddressLine>
			</addr>
			<telecom use="WP" value="mailto:prova.provax@example.com"/>
			<telecom use="MC" value="tel:3340000000"/>
			<assignedPerson>
				<name>
					<family>Prova</family>
					<given>Provo</given>
					<prefix>Dr</prefix>
				</name> 
			</assignedPerson>
		</assignedAuthor>
	</author>
	<dataEnterer typeCode="ENT">
		<time value="20241008145608+0200"/>
		<assignedEntity>
			<id root="2.16.840.1.113883.2.9.4.3.2" extension="PROVAX00X00X000Y" assigningAuthorityName="MEF"/>
			<assignedPerson>
				<name>
					<family>Prova</family>
					<given>Test</given>
				</name>
			</assignedPerson>
		</assignedEntity>
	</dataEnterer>
	<custodian>
		<assignedCustodian>
			<representedCustodianOrganization>
				<id root="2.16.840.1.113883.2.9.4.1.2" extension="120202120267" assigningAuthorityName="Ministero della Salute"/>
				<name>Ospedale Sandro Pertini</name>
				<telecom use="MC" value="tel:3340000000"/>
				<addr>
					<country>100</country>
					<state>120</state>
					<county>RM</county>
					<city>Roma</city>
					<censusTract>058091</censusTract>
					<postalCode>00157</postalCode>
					<streetAddressLine>Via Monti Tiburtini 385</streetAddressLine>
				</addr>
			</representedCustodianOrganization>
		</assignedCustodian>
	</custodian>
	<informationRecipient>
		<intendedRecipient>
			<id root="2.16.840.1.113883.2.9.4.3.2" extension="PROVAX00X00X000Y" assigningAuthorityName="MEF"/>
			<telecom use="WP" value="mailto:prova.provax@example.com"/>
			<informationRecipient>
				<name>
					<family>Prova</family>
					<given>Test</given>
				</name> 
			</informationRecipient>
		</intendedRecipient>
	</informationRecipient>
	<legalAuthenticator>
		<time value="20241008145608+0200"/>
			<signatureCode code="S"/>
			<assignedEntity>
				<id root="2.16.840.1.113883.2.9.4.3.2" extension="PROVAX00X00X000Y" assigningAuthorityName="MEF"/>
				<addr>
					<country>100</country>
					<state>120</state>
					<county>RM</county>
					<city>Roma</city>
					<censusTract>058091</censusTract> 
					<postalCode>00164</postalCode> 
					<streetAddressLine>Via Monti Tiburtini 385</streetAddressLine>
				</addr> 
				<telecom use="WP" value="mailto:prova.provax@example.com"/>
				<telecom use="MC" value="tel:3300000000"/>
				<assignedPerson> 
					<name>
						<family>Prova</family> 
						<given>Test</given>
						<prefix>Dttr.</prefix>
					</name> 
				</assignedPerson>
			</assignedEntity> 
	</legalAuthenticator>
	<authenticator>
		<time value="20241008145608+0200"/>
		<signatureCode code="S"/>
		<assignedEntity>
			<id root="2.16.840.1.113883.2.9.4.3.2" extension="PROVAX00X00X000Y" assigningAuthorityName="MEF"/>
			<addr>
				<country>100</country>
				<state>120</state>
				<county>RM</county>
				<city>Roma</city>
				<censusTract>058091</censusTract>
				<postalCode>00164</postalCode>
				<streetAddressLine>Via Monti Tiburtini 385</streetAddressLine>
			</addr>
			<telecom use="WP" value="mailto:prova.provax@example.com"/>
			<telecom use="MC" value="tel:3300000000"/>
			<assignedPerson>
				<name>
					<family>Prova</family>
					<given>Test</given>
				</name>
			</assignedPerson>
		</assignedEntity>
	</authenticator>
	<participant typeCode="REF" contextControlCode="OP">
		<functionCode code="PRE" codeSystem= "2.16.840.1.113883.2.9.5.1.88"/>
		<time value="20241008145608+0200"/>
		<associatedEntity classCode="QUAL">
			<id root="2.16.840.1.113883.2.9.4.3.2" extension="PROVAX00X00X000Y" assigningAuthorityName="MEF"/>
			<addr>
				<country>100</country>
				<state>120</state>
				<county>RM</county>
				<city>Roma</city>
				<censusTract>058091</censusTract>
				<postalCode>00187</postalCode>
				<streetAddressLine>Via Monti Tiburtini 385</streetAddressLine>
			</addr>
			<telecom use="WP" value="mailto:prova.provax@example.com"/>
			<associatedPerson>
				<name>
					<family>Prova</family>
					<given>Test</given>
				</name>
			</associatedPerson>
			<scopingOrganization>
				<id root="2.16.840.1.113883.2.9.4.1.2" extension="120202120267" assigningAuthorityName="Ministero della Salute"/>
				<name>Ospedale Sandro Pertini</name>
				<telecom use="WP" value="tel:3340000000"/>
				<addr>
					<country>100</country>
					<state>120</state>
					<county>RM</county>
					<city>Roma</city>
					<censusTract>058091</censusTract>
					<postalCode>00137</postalCode>
					<streetAddressLine>Via Monti Tiburtini 385</streetAddressLine>
				</addr>
			</scopingOrganization>
		</associatedEntity>
	</participant>
	<documentationOf>
		<serviceEvent moodCode="EVN">
			<statusCode code="completed"/>
			<effectiveTime value="20241008145608+0200"/>
			<performer typeCode="PRF">
				<assignedEntity>
					<id root="2.16.840.1.113883.2.9.4.3.2" extension="PROVAX00X00X000Y" assigningAuthorityName="MEF"/>
					<assignedPerson>
						<name>
							<family>Prova</family>
							<given>Test</given>
						</name>
					</assignedPerson>
					<representedOrganization>
						<id root="2.16.840.1.113883.2.9.4.1.3" extension="120202120267" assigningAuthorityName="Ministero della Salute"/>
						<name>Ospedale Sandro Pertini</name>
						<asOrganizationPartOf>
							<id root="2.16.840.1.113883.2.9.4.1.1" extension="120202" assigningAuthorityName="Ministero della Salute"/>
						</asOrganizationPartOf>
					</representedOrganization>
				</assignedEntity>
			</performer>
		</serviceEvent>
	</documentationOf>
	<componentOf>
		<encompassingEncounter>
			<effectiveTime value="20241008145608+0200"/>
			<responsibleParty>
				<assignedEntity>
					<id root="2.16.840.1.113883.2.9.4.3.2" extension="PROVAX00X00X000Y" assigningAuthorityName="MEF"/>
					<assignedPerson>
						<name>
							<family>Prova</family>
							<given>Test</given>
						</name>
					</assignedPerson>
				</assignedEntity>
			</responsibleParty>
			<location>
				<healthCareFacility>
					<id root="2.16.840.1.113883.2.9.4.1.6" extension="120200.01.50" assigningAuthorityName="Ministero della Salute"/>
					<serviceProviderOrganization>
						<id root="2.16.840.1.113883.2.9.4.1.2" extension="120202120267" assigningAuthorityName="Ministero della Salute"/>
						<name>Ospedale Sandro Pertini</name>
						<telecom use="MC" value="tel:3340000000"/>
						<asOrganizationPartOf>
							<id root="2.16.840.1.113883.2.9.4.1.1" extension="120202" assigningAuthorityName="Ministero della Salute"/>
						</asOrganizationPartOf>
					</serviceProviderOrganization>
				</healthCareFacility>
			</location>
		</encompassingEncounter>
	</componentOf>
	<component>
		<structuredBody>
			<component>
				<section ID="ESAMI_URINE">
					<code code="18729-4" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="ESAMI DELLE URINE"/>
					<title>Esami delle Urine</title>
					<component>
						<section ID="ALBUMINA_URINE">
							<code code="14957-5" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Microalbumin Massa/Volume in Urine">
								<translation code="0090334.02" codeSystem="2.16.840.1.113883.2.9.2.30.6.11" codeSystemName="SISS" displayName="Microalbumina nelle urine"/>
							</code>
							<title>Albumina nelle Urine</title>
							<text>
								<list>
									<item>
										<table ID="nota1">
											<thead>
												<tr>
													<th>Esame</th>
													<th>Metodo utilizzato per l'esame</th>
													<th>Materiale utilizzato per l'esame</th>
													<th>Risultato dell'esame</th>
													<th>Commenti e note</th>
													<th>Unita' di Misura</th>
													<th>Range di Riferimento</th>
													<th>Criteri per il range di riferimento</th>
													<th>Interpretazione</th>
													<th>Allegati multimediali</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td>Microalbumina massa/volume in urine</td>
													<td></td>
													<td>Urine</td>
													<td>20</td>
													<td></td>
													<td>mg/L</td>
													<td>0 - 20</td>
													<td></td>
													<td>N</td>
													<td/>
												</tr>
											</tbody>
										</table>
									</item>
								</list>
							</text>
							<entry typeCode="DRIV">
								<act moodCode="EVN" classCode="ACT">
									<code code="14957-5" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Microalbumin Massa/Volume in Urine"/>	
									<statusCode code="active"/>
									<specimen>
										<specimenRole>
											<specimenPlayingEntity>
												<code code="UR" codeSystem="2.16.840.1.113883.5.129" codeSystemName="SpecimenType " displayName="Urine"/>
											</specimenPlayingEntity>
										</specimenRole>
									</specimen>
									<entryRelationship typeCode="SUBJ">
										<act moodCode="EVN" classCode="ACT">
											<code code="48767-8" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Annotazioni e commenti"/>
											<text>
												<reference value="#nota1"/>
											</text>
										</act>
									</entryRelationship>
									<entryRelationship typeCode="COMP">
										<observation moodCode="EVN" classCode="OBS">
											<code code="14957-5" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Microalbumin Massa/Volume in Urine">
												<translation code="0090334.02" codeSystem="2.16.840.1.113883.2.9.2.30.6.11" codeSystemName="SISS" displayName="Albumina nelle urine"/>
											</code>
											<statusCode code="completed"/>
											<effectiveTime value="20241008145608+0200"/>
											<value xsi:type="PQ" value="16.00" unit="mg/L"/>
											<interpretationCode code="N" codeSystem="2.16.840.1.113883.5.83" codeSystemName="HL7 Observation Interpretation" displayName="Normal"/>
											<specimen typeCode="SPC">
												<specimenRole classCode="SPEC">
													<specimenPlayingEntity>
														<code code="UR" codeSystem="2.16.840.1.113883.5.129" codeSystemName="SpecimenType" displayName="Urine"/>
													</specimenPlayingEntity>
												</specimenRole>
											</specimen>
											<referenceRange>
												<observationRange>
													<value xsi:type="IVL_PQ">
														<low value="0.00" unit="mg/L"/>
														<high value="20.00" unit="mg/L"/>
													</value>
													<interpretationCode code="N" codeSystem="2.16.840.1.113883.5.83" codeSystemName="HL7 Observation Interpretation" displayName="Normal"/>
													<lab:precondition> 
														<lab:criterion>
															<lab:code code="30525-0" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Età"/>
															<lab:value xsi:type="IVL_PQ">
																<high value="60" unit="a"/>
															</lab:value>
														</lab:criterion>
													</lab:precondition>
												</observationRange>
											</referenceRange>
										</observation>
									</entryRelationship>
								</act>
							</entry>
						</section>
					</component>
				</section>
			</component>
		</structuredBody>
	</component>
</ClinicalDocument>

**Comment by vigliottim** [comment]
Buon pomeriggio,
il CDA2 da lei utilizzato è un referto di laboratorio e, per essere validato con successo, è obbligatorio inserire almeno un elemento _inFulfillmentOf_. 
Per procedere con i test, evitando di inviare NRE non validi ad INI, è possibile popolare l'attributo _inFulFillmentOf/order/id@root_ usando un codice diverso da quello previsto per le ricette (ossia "2.16.840.1.113883.2.9.4.3.9"), come, ad esempio, "2.16.840.1.113883.2.9.4.3.4".
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by giosil** [comment]
Buon pomeriggio, abbiamo cambiato il tipo di order per evitare il controllo su NRE fitti e ora tutti i casi di test vengono eseguiti correttamente. Potete chiudere la segnalazione. Grazie.

**Comment by vigliottim** [comment]
Grazie per il gentile feedback.
Procediamo alla chiusura della presente segnalazione come da lei richiesto.
Rimaniamo a disposizione per altre richieste di supporto.
