### ISSUE TITLE
Creazione errore generico 500

### ISSUE THREAD

**Issue by acolzi** [ministero-salute/it-fse-support#1064]
Buongiorno,
è possibile avere un dettaglio di questa chiamata che ritorna con errore 500?
grazie
{
  "traceID": "0024833617a879d4",
  "spanID": "0024833617a879d4",
  "instance": "",
  "detail": "Errore generico",
  "type": "/msg/generic-error",
  "title": "Errore generico.",
  "status": 500
}

**Comment by vigliottim** [comment]
Buongiorno,
è stato rilasciato un aggiornamento.
Potrebbe cortesemente riprovare e informarci se il problema persiste? 
Grazie.

**Comment by acolzi** [comment]
ancora stesso errore. La validazione va a buon fine, la successiva pubblicazione no..
{
  "traceID": "4b35940a5667ee32",
  "spanID": "4b35940a5667ee32",
  "instance": "",
  "detail": "Errore generico",
  "type": "/msg/generic-error",
  "title": "Errore generico.",
  "status": 500
}

**Comment by vigliottim** [comment]
Buon pomeriggio, dalle analisi svolte sui log della sua ultima chiamata al servizio di pubblicazione, l'errore ricevuto potrebbe essere causato dall'errata valorizzazione del campo _identificativoRep_ nella _requestBody_:

```
{"mode":"ATTACHMENT",
"identificativoSottomissione":"2.16.840.1.113883.2.9.2.90.4.3^20665492",
"healthDataFormat":"CDA",
"identificativoDoc":"2.16.840.1.113883.2.9.2.90.4.4^20665492",
****"identificativoRep":"2.16.840.1.113883.2.9.2.90.4.5^20665492"****,
"tipoAttivitaClinica":"ERP",
"tipologiaStruttura":"SistemaTS",
"assettoOrganizzativo":"AD_PSC103",
"tipoDocumentoLivAlto":"REF"}
```

Infatti, come riportato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#41-request), tale campo corrisponde al metadato _XDSDocumentEntry.repositoryUniqueId_:

![image](https://github.com/user-attachments/assets/332cfe2c-f784-4a92-9ec5-96aa729a28f5)

Per la sua corretta valorizzazione, può consultare il _paragrafo 2.15_ del documento [AffinityDomain - v2.5](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20interoperabilit%C3%A0/AffinityDomainItalia_v2-5_v20231212.pdf):
![image](https://github.com/user-attachments/assets/fd949feb-acfd-48b2-966c-5dabaae607a4)

La preghiamo di riprovare valorizzando correttamente il campo indicato.
Grazie.

**Comment by acolzi** [comment]
altra domanda su repositoryUniqueId.. sto utilizzando 2.16.840.1.113883.2.9.2.90.4.5.1 , ovvero istanza n. 1 regione toscana.
Ha senso oppure c'è una anagrafica dei repository per ogni regione? 
grazie

**Comment by acolzi** [comment]
Altra domanda, scusate
... ho implementato anche la cancellazione... mi da ok tutte le volte... non c'è un controllo se il referto è stato già cancellato?
grazie

**Comment by vigliottim** [comment]
> ok, pubblicazione ok. per quanto riguarda la firma pades del pdf, sto utilizzando il certificato S1 che mi avete fornito. E' corretto? grazie

La firma PaDES può essere applicata al PDF utilizzando il certificato di firma tramite il tool online messo a disposizione: [pdf-generator](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/pdf-generator)
_Esempio:_
`java -jar pdf-generator.jar -c CDA_OK.xml -s Certificato_Firma_S1.p12 -pwd password

> altra domanda su repositoryUniqueId.. sto utilizzando 2.16.840.1.113883.2.9.2.90.4.5.1 , ovvero istanza n. 1 regione toscana.
Ha senso oppure c'è una anagrafica dei repository per ogni regione?
grazie

Stiamo verificando.

> Altra domanda, scusate
... ho implementato anche la cancellazione... mi da ok tutte le volte... non c'è un controllo se il referto è stato già cancellato?
grazie

Potrebbe allegare la response completa comprensiva di traceid/govwayid? Grazie.
`

**Comment by vigliottim** [comment]
> altra domanda su repositoryUniqueId.. sto utilizzando 2.16.840.1.113883.2.9.2.90.4.5.1 , ovvero istanza n. 1 regione toscana.
Ha senso oppure c'è una anagrafica dei repository per ogni regione?
grazie

La informiamo che all'interno del metadato _2.16.840.1.113883.2.9.2.[REGIONE oppure INI].4.3.**X**_ è necessario inserire al posto di **_X_** l'istanza reale del repository regionale in produzione. 
La invitiamo a contattare la sua regione per avere informazioni sull'esistenza di un'anagrafica dei repository regionali.

> per quanto riguarda la firma pades, il problema non è la firma (sto utilizzando il vs. tool) ma mi domandavo se è corretto utilizzare il certificato S1 che mi è stato inviato e che utilizzo anche per il token o, eventualmente, un p12 del dottore che redige il referto.

E' corretto usare il p12 del medico che redige il referto.

> Altra domanda, scusate
... ho implementato anche la cancellazione... mi da ok tutte le volte... non c'è un controllo se il referto è stato già cancellato?
grazie

Chiamando il servizio _status_ con i wii da lei forniti, entrambe le cancellazioni hanno successo:

**_1. "workflowInstanceId": "27e5ff2fe14e0b6757445f1cb65b52deb965d8367097f8e6076307812c3face2.1b0ce07549^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"_**
```
{
    "traceID": "d59f0d6490956c2c",
    "spanID": "644b1fd3f14a764e",
    "transactionData": [
        {
            "eventType": "RIFERIMENTI_INI",
            "eventDate": "2024-10-09T18:26:26.573+02:00",
            "eventStatus": "SUCCESS",
            "message": "Riferimenti trovati: UUID_MOCKATO",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.90.4.4^20665492",
            "subject": "BSCRTT45E66L874H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "090",
            "workflowInstanceId": "27e5ff2fe14e0b6757445f1cb65b52deb965d8367097f8e6076307812c3face2.1b0ce07549^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "4c1c57daee372bc9",
            "issuer": "integrity:S1#111#ABLIASRLXX",
            "expiringDate": "2025-10-09T18:26:26.583+02:00"
        },
        {
            "eventType": "INI_DELETE",
            "eventDate": "2024-10-09T18:26:26.605+02:00",
            "eventStatus": "SUCCESS",
            "message": "Delete effettuata su ini",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.90.4.4^20665492",
            "subject": "BSCRTT45E66L874H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "090",
            "workflowInstanceId": "27e5ff2fe14e0b6757445f1cb65b52deb965d8367097f8e6076307812c3face2.1b0ce07549^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "4c1c57daee372bc9",
            "issuer": "integrity:S1#111#ABLIASRLXX",
            "expiringDate": "2025-10-09T18:26:26.617+02:00"
        }
    ]
}
```

**_2. "workflowInstanceId": "27e5ff2fe14e0b6757445f1cb65b52deb965d8367097f8e6076307812c3face2.19286e5d55^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"_**
```
{
    "traceID": "baab48a4ca75e5aa",
    "spanID": "c730940d09717280",
    "transactionData": [
        {
            "eventType": "RIFERIMENTI_INI",
            "eventDate": "2024-10-09T18:25:45.227+02:00",
            "eventStatus": "SUCCESS",
            "message": "Riferimenti trovati: UUID_MOCKATO",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.90.4.4^20665492",
            "subject": "BSCRTT45E66L874H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "090",
            "workflowInstanceId": "27e5ff2fe14e0b6757445f1cb65b52deb965d8367097f8e6076307812c3face2.19286e5d55^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "b83278821c89548b",
            "issuer": "integrity:S1#111#ABLIASRLXX",
            "expiringDate": "2025-10-09T18:25:45.237+02:00"
        },
        {
            "eventType": "INI_DELETE",
            "eventDate": "2024-10-09T18:25:45.349+02:00",
            "eventStatus": "SUCCESS",
            "message": "Delete effettuata su ini",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.90.4.4^20665492",
            "subject": "BSCRTT45E66L874H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "090",
            "workflowInstanceId": "27e5ff2fe14e0b6757445f1cb65b52deb965d8367097f8e6076307812c3face2.19286e5d55^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "b83278821c89548b",
            "issuer": "integrity:S1#111#ABLIASRLXX",
            "expiringDate": "2025-10-09T18:25:45.358+02:00"
        }
    ]
}
```

Tuttavia, si nota che sono state effettuate a distanza di un minuto.
La invitiamo a riprovare attendendo almeno 15 minuti tra una chiamata e l'altra.

**Comment by acolzi** [comment]
_La informiamo che all'interno del metadato 2.16.840.1.113883.2.9.2.[REGIONE oppure INI].4.3.X è necessario inserire al posto di X l'istanza reale del repository regionale in produzione.
La invitiamo a contattare la sua regione per avere informazioni sull'esistenza di un'anagrafica dei repository regionali._

Suppongo che questo dato mi sia fornito prima di andare in produzione....  proverò comunque a sentire qualcuno preventivamente....


_Tuttavia, si nota che sono state effettuate a distanza di un minuto.
La invitiamo a riprovare attendendo almeno 15 minuti tra una chiamata e l'altra._


in realtà quel documento era stato cancellato anche ore prima.......

**Comment by vigliottim** [comment]
Buonasera, 
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
