### ISSUE TITLE
Crash Program - Regione Piemonte - Errore aggiornamento metadati

### ISSUE THREAD

**Issue by marco-volpe** [ministero-salute/it-fse-support#1066]
Buongiorno

stiamo procedendo con i test ed abbiamo rilevato un problema con il servizio di aggiornamento metadati
Abbiamo pubblicato con successo un documento con OID

`
2.16.840.1.113883.2.9.2.010.4.4^1728486952684
`
e seguente workflowInstanceID

`
2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.c9c7eafdb6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
`

Dopo aver ricevuto la ComunicazioneMetadati , abbiamo provato ad eseguire un aggiornamento dei metadati invocando la seguente url

`
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.010.4.4%5E1728486952684/metadata
`

con il seguente payload

```json
{
  "tipologiaStruttura": "Ospedale",
  "tipoDocumentoLivAlto": "REF",
  "assettoOrganizzativo": "AD_PSC001",
  "dataInizioPrestazione": "20241008110100",
  "dataFinePrestazione": "20241008110100",
  "tipoAttivitaClinica": "CON",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.2.010.4.3.1728486960477",
  "administrativeRequest": [
    "SSN"
  ]
}
```

La risposta ottenuta è stata la seguente

```json
{
  "traceID": "b3a785c9c234e934",
  "spanID": "e1c3633766887b40",
  "type": "/errors",
  "title": "Generic",
  "detail": "Internal Error 9000",
  "instance": "error/generic"
} 
```

Potete indicarci il motivo del problema?

Grazie, a disposizione

**Comment by marco-volpe** [comment]
Buongiorno

ci sono aggiornamenti in merito all'aggiornamento dei metadati?

Grazie

**Comment by g-maugeri-sogei** [comment]
Buonasera,
ci occorre il CF dell'assistito e timestamp per indagare. Visto che si tratta di un vecchio tentativo suggerisco di ripetere il test e indagare su quest'ultimo in caso si ripresenti l'errore.

**Comment by marco-volpe** [comment]
Buongiorno

la richiesta è datata anche per noi, ma dovrebbe essere stata fatta come RDE = RDA. In tal caso il CF utilizzato dovrebbe essere
**SCLSCL00A55G273T**

Grazie, a disposizione

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
potete riprovare, la richiesta e' troppo vecchia.

**Comment by g-maugeri-sogei** [comment]
Che workflowInstanceId la chiamata d'aggiornamento?

**Comment by marco-volpe** [comment]
Buongiorno

seguendo le specifiche per la chiamata di Aggiornamento Metadati non risulta dover inviare un workflowInstanceID.
La URL che invochiamo contiene l'OID del documento generato ed è la seguente

`
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.010.4.4%5E1729496516137/metadata
`

Lo stesso modello di chiamata viene utilizzato anche nei test come RDE che invece hanno esito positivo

**Comment by g-maugeri-sogei** [comment]
Per il tentativo con timestamp 21-OTT-24 09:41:58,25000
[request.txt](https://github.com/user-attachments/files/17460699/request.txt)
[response.txt](https://github.com/user-attachments/files/17460712/response.txt)
 il flusso si interrompe quando INI inoltra una richiesta di ricerca documenti relativo al documento da aggiornare perche' il documento non viene trovato.
In allegato request / response. Potete verificare perche' il documento non viene trovato ?

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.

**Comment by marco-volpe** [comment]
Si chiedo scusa, mi ero perso questa issue
Il problema è stato risolto e l'aggiornamento ora va a buon fine

Grazie
