### ISSUE TITLE
Crash Program - Regione Abruzzo - Errore 1054 IdentificativoOrganizzazione e/o StrutturaUtente non compatibile con l'utente richiedente

### ISSUE THREAD

**Issue by marlagatta** [ministero-salute/it-fse-support#1068]
Salve

Facendo delle prove di create per Regione Abruzzo, usando come dati relativi all'author

```
<com:IdentificativoUtente>PROVAX00X00X000Y</com:IdentificativoUtente>                                                   <com:StrutturaUtente>201130201</com:StrutturaUtente>                                                            
<com:IdentificativoAssistito>DNNBZZ60A43A345K</com:IdentificativoAssistito>                                     

```

si ottiene l'errore bloccante 
        
 `<?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><a:ComunicazioneMetadatiRicevuta xmlns:a="http://comunicazionemetadatiricevuta.xsd.fse.ini.finanze.it" xmlns="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it" xmlns:b="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it"><a:Esito>9999</a:Esito><a:ElencoErrori><Errore><codEsito>1054</codEsito><esito>IdentificativoOrganizzazione e/o StrutturaUtente non compatibile con l'utente richiedente</esito><tipoErrore>Bloccante</tipoErrore><fonte>FSE-INS-FE</fonte></Errore></a:ElencoErrori></a:ComunicazioneMetadatiRicevuta></soapenv:Body></soapenv:Envelope>`

Potreste cortesemente indicarci quale Utente e Struttura Utente utilizzare per i test relativi alla Regione Abruzzo?

Grazie mille

**Comment by vigliottim** [comment]
Buongiorno, 
le chiediamo gentilmente di riprovare e darci riscontro.
Grazie.
