### ISSUE TITLE
Checklist accreditamento CDA Patient Summary

### ISSUE THREAD

**Issue by millenniumsrl** [ministero-salute/it-fse-support#107]
Buongiorno,
nel documento accreditamento-checklist_V4.2.xlsx non troviamo i test case per l'accreditamento del CDA di Patient Summary.
Potete darci indicazioni in merito?
Grazie in anticipo

**Comment by millenniumsrl** [comment]
Potete cortesemente rispondere anche indicando eventualmente anche solo i tempi in cui prevedete di poter mettere a disposizione la checklist per il documento in oggetto, poichè alcune regioni ci richiedono i tempi per il nostro accreditamento.
Grazie in anticipo

**Comment by IStacchiotti** [comment]
Buongiorno, le comunichiamo che a questo [link](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case) è stata appena pubblicata la checklist di validazione per PSS. Grazie.

**Comment by IStacchiotti** [comment]
Buonasera, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
