### ISSUE TITLE
Errore metadata update Regione Valle d'Aosta su assistito Regione Umbria

### ISSUE THREAD

**Issue by assistenza-fsevda** [ministero-salute/it-fse-support#1074]
Buongiorno,
abbiamo effettuato con successo una pubblicazione di un documento associato al CF CRSMRM80A01G478X appartenente a Regione Umbria.
In fase di metadata update otteniamo però il seguente errore:

```
{
  "traceID": "00fbbf9e889f8a6b",
  "spanID": "00fbbf9e889f8a6b",
  "type": "/msg/ini-error",
  "title": "Ini error.",
  "detail": "{\"traceID\":\"00fbbf9e889f8a6b\",\"spanID\":\"3711d19b747a7994\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R221CODE CONTEXT:The version number included in the update request did not match the existing object\",\"instance\":\"error/generic\"}",
  "status": 500,
  "instance": "/msg/service-error/ini"
}
```

Per completezza riporto anche i dati riguardanti la validazione + pubblicazione:
```
{
	"traceID": "666cee112236bfee",
	"spanID": "5084ad65b8dd7488",
	"transactionData": [
		{
			"eventType": "VALIDATION_FOR_PUBLICATION",
			"eventDate": "2024-10-09T14:39:05.181+02:00",
			"eventStatus": "SUCCESS",
			"subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"organizzazione": "020",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.da7e330d03^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "a4b67fb08ede6e31",
			"issuer": "integrity:S1#020#020VALDAOSTATEST",
			"expiringDate": "2025-10-09T14:39:05.192+02:00"
		},
		{
			"eventType": "PUBLICATION",
			"eventDate": "2024-10-09T14:39:05.250+02:00",
			"eventStatus": "SUCCESS",
			"identificativoDocumento": "2.16.840.1.113883.2.9.2.20.4.4^001.TRAKTEST.TESTRSA:CPUMBRIA01-0",
			"subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"tipoAttivita": "CON",
			"organizzazione": "020",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.da7e330d03^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "a4b67fb08ede6e31",
			"issuer": "integrity:S1#020#020VALDAOSTATEST",
			"expiringDate": "2025-10-09T14:39:05.259+02:00"
		},
		{
			"eventType": "SEND_TO_INI",
			"eventDate": "2024-10-09T14:39:06.746+02:00",
			"eventStatus": "SUCCESS",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.da7e330d03^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"expiringDate": "2025-10-09T14:39:07.798+02:00"
		}
	]
}
```
In questo caso in cui nel processo è coinvolta una RDA diversa dalla nostra, come possiamo procedere per la risoluzione dell'issue? È previsto un particolare flusso per il quale le rergioni interessate vengono coinvolte?

Grazie anticipatamente per l'aiuto.

**Comment by rangemasterd** [comment]
Salve, ad oggi l'aggiornamento dei metadati non funziona correttamente, siamo in attesa di una modifica da parte del fornitore.

**Comment by assistenza-fsevda** [comment]
> Salve, ad oggi l'aggiornamento dei metadati non funziona correttamente, siamo in attesa di una modifica da parte del fornitore.

Grazie mille per il feedback. Attendiamo aggiornamenti prima di tentare nuovamente.
Buon lavoro.

**Comment by assistenza-fsevda** [comment]
Buongiorno,
leggendo l'issue #1106 in cui Regione FVG segnala la nostra stessa tipologia di errore, ho visto che @rangemasterd ha indicato che è stato fatto un aggiornamento ed ha chiesto di riprovare. Se può essere utile, vi segnalo che questa mattina da Regione VdA abbiamo fatto un nuovo tentativo ma abbiamo ottenuto lo stesso errore:
```
{
	"traceID": "85d26f1f0ea89f28",
	"spanID": "85d26f1f0ea89f28",
	"type": "/msg/ini-error",
	"title": "Ini error.",
	"detail": "{\"traceID\":\"324bfa80ea2b3785\",\"spanID\":\"2287f00f5483ef3d\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R221CODE CONTEXT:The version number included in the update request did not match the existing object\",\"instance\":\"error/generic\"}",
	"status": 500,
	"instance": "/msg/service-error/ini"
}
```
Grazie per il supporto

**Comment by angeloceloni** [comment]
Buongiorno
abbiamo segnalato il problema al fornitore e siamo in attesa di risoluzione. L'errore segnalato al fornitore è relativo al messaggio di errore errato, a fix rilasciato restituiremo comunque l'errore XDSRegistryError perché l'attuale request inviata da INI è errata come da issue [1136](https://github.com/ministero-salute/it-fse-support/issues/1136).
Direi di riprovare dopo la risoluzione della issue indicata.

**Comment by angeloceloni** [comment]
Buonasera
la request inviata da INI è stata aggiornata e l'attuale viene gestita correttamente dal registry di Regione Umbria.
Potete riprovare?

**Comment by vigliottim** [comment]
@assistenza-fsevda @angeloceloni @rangemasterd 

Buonasera,
potreste cortesemente informarci se il problema è stato risolto?
Grazie.

**Comment by assistenza-fsevda** [comment]
buongiorno,
abbiamo eseguito in data 30/10, intorno orario 17:20, una nuova iterazione sui 4 servizi verso Regione Umbria:

CREATE - ESITO OK
REPLACE DOC - ESITO OK
METADATA UPDATE - ESITO OK
DELETE - ESITO OK

Notifiche da INI pervenute a RDA 020 correttamente. 
Non riscontriamo al momento anomalie.

saluti

**Comment by vigliottim** [comment]
Buongiorno,
grazie per il suo gentile feedback.
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per altre richieste di supporto.
