### ISSUE TITLE
Tipologia documento diversa dalla tipologia di CDA

### ISSUE THREAD

**Issue by acolzi** [ministero-salute/it-fse-support#1075]
Buongiorno,
ho ripreso il db del cliente e provato a rifare una verifica. Adesso mi da questo errore
{
  "traceID": "0b35a772a05794f3",
  "spanID": "0b35a772a05794f3",
  "instance": "/jwt-document-type",
  "detail": "JWT payload: Tipologia documento diversa dalla tipologia di CDA (code - codesystem)",
  "type": "/msg/jwt-validation",
  "title": "Campo token JWT non valido.",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.427fd8f5875704945fd96fd3babb4cfc04e90227497dd39b254c63c9f5870923.6aadd21b80^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "status": 403
}
il jwt dovrebbe contenere
resource_hl7_type: ('11502-2^^2.16.840.1.113883.6.1')

Non riesco a capire allora cosa c'è che adesso non va... probabilmente ho dimenticato di riempire qualche parametro ma non riesco a trovarlo
grazie

**Comment by vigliottim** [comment]
Buongiorno,
il campo _resource_hl7_type_ contenuto nel JWT è ottenuto dal concatenamento dei campi _code_ e _codesystem_ secondo il seguente formato:
`"resource_hl7_type": "('CODE^^CODESYSTEM')"`
La invitiamo a controllare che il valore del campo `CODE` inserito in resource_hl7_type del JWT sia coerente con quello inserito nel tag _code_ contenuto all'interno del CDA (relativo alla tipologia di documento in esame):

![image](https://github.com/user-attachments/assets/86df1460-6e58-49d8-b2e7-cfbadac20335)

Restiamo a disposizione nel caso in cui il problema persista. 
Grazie.

**Comment by acolzi** [comment]
grazie
