### ISSUE TITLE
Fallimento chiamata web service validazione documenti

### ISSUE THREAD

**Issue by fmatraxiafse** [ministero-salute/it-fse-support#1076]
Salve, richiamando il web service https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation otteniamo come output 
{
    "type": "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
    "title": "AuthorizationContentDeny",
    "status": 403,
    "detail": "Unauthorized request content",
    "govway_id": "04c0a586-87b1-11ef-a4d1-005056ae54fa"
}
I certificati ci sembrano ancora validi, riuscite a darci supporto? 
Grazie in anticipo.

**Comment by LucaRogledi** [comment]
Buongiorno,
Dalle analisi effettuate sulla chiamata con identificativo "govway_id":"04c0a586-87b1-11ef-a4d1-005056ae54fa" risulta che l'errore è dovuto all'utilizzo di un certificato S1*** per il canale di comunicazione.

![image](https://github.com/user-attachments/assets/3fe77b49-26a7-428f-a202-dba1e9395d8b)

Per il canale di comunicazione e X-Security-Token è necessario utilizzare il certificato A1*** mentre per il token di bearer e signature è corretto utilizzare il certificato di firma S1***.
La invitiamo gentilmente a riprovare la chiamata dopo aver rigenerato i token utilizzando il certificato di firma S1*** e utilizzando il certificato di Autenticazione A1*** all'interno del X-Security-Token per la comunicazione.
Restiamo a disposizione per eventuali chiarimenti e ringraziamo per la collaborazione.

**Comment by fmatraxiafse** [comment]
Abbiamo riprovato utilizzando il certificato A1*** ma l'output restituito è sempre
{
    "type": "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
    "title": "AuthorizationContentDeny",
    "status": 403,
    "detail": "Unauthorized request content",
    "govway_id": "7438f62d-87cd-11ef-a4d1-005056ae54fa"
}

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
