### ISSUE TITLE
Regione Valle d'Aosta - Problema pubblicazione con Gateway

### ISSUE THREAD

**Issue by assistenza-fsevda** [ministero-salute/it-fse-support#1077]
Buongiorno,
effettuando delle validazioni e pubblicazioni stiamo riscontrando dei problemi. Le prese in carico da parte del gateway sono positive ma successivamente non riceviamo le comunicazioni metadati.
Interrogando lo status per workflowInstanceId la risposta che otteniamo è "No Record Found".
Di seguito la risposta della presa in carico da parte del gateway dell'operazione di validazione e creazione contestuale:
```
{
	"traceID": "fe3ff5d60da60243",
	"spanID": "fe3ff5d60da60243",
	"workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.2c926c1d35^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```

E la risposta ottenuta nell'interrogazione per status:
```
{
    "traceID": "5a9e733341dab9b7",
    "spanID": "5a9e733341dab9b7",
    "type": "/msg/record-not-found",
    "title": "Record non trovato.",
    "detail": "No Record Found",
    "instance": "/record-not-found"
}
```

Le stesse transazioni erano funzionanti fino a ieri. Oggi ci sono problemi lato gateway?

Grazie anticipatamente.

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
dalle nostre verifiche utilizzando il servizio di status tramite workflowInstanceId otteniamo la response con esito 200 e i dati relativi alla "VALIDATION_FOR_PUBLICATION" e "PUBLICATION" .
Potrebbe gentilmente riprovaree darci un riscontro ? 
Grazie

**Comment by assistenza-fsevda** [comment]
Buongiorno,
confermiamo che adesso i servizi rispondono in maniera corretta.
Grazie per l'aiuto.

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Grazie
