### ISSUE TITLE
Errore Tipo Documento Basso non valido invio PSS (Regione Sicilia)

### ISSUE THREAD

**Issue by dkkzzz** [ministero-salute/it-fse-support#1078]
Inviando un PSS in produzione con pdf firmato con cda2 iniettato in regione sicilia stiamo ricevendo l’errore “Tipo Documento Basso non valido”. Stiamo utilizzando il tipo presente nell’ultima versione dell’affinity domain (2.5) che ha il valore 2.16.840.1.113883.2.9.10.1.4.1.1.
 
Abbiamo anche provato con il valore della versione 2.4 che era 2.16.840.1.113883.2.9.10.2.4.1.1 ma in quel caso riceviamo l’errore Tipo documento allegato non ammesso.

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
Potrebbe gentilmente riportare la response completa ricevuta dal gateway comprendendo govway_id, traceID, workflowinstanceId e il messaggio di errore ricevuto, in caso siano disponibili? Grazie

**Comment by dkkzzz** [comment]
Buonpomeriggio, ho scritto una mail al fse_support@sogei.it che mi ha richiesto di inoltrare la domanda qui. Il problema non è sul gateway di validazione, ma utilizzando i metodi INI di pubblicazione in produzione con i servizi WCF

**Comment by vigliottim** [comment]
Buonasera,
potrebbe gentilmente indicare a quale metadato dell'Affinity Domain sta facendo riferimento con i codici indicati? 
Grazie.

**Comment by dkkzzz** [comment]
Il metadato è XDSDocumentEntry.formatCode

**Comment by vigliottim** [comment]
Grazie per la risposta.
I valori ammessi per questo metadato sono riportati nella _Tabella 2.6-1_ dell'[Affinity Domain 2.5](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20interoperabilit%C3%A0/AffinityDomainItalia_v2-5_v20231212.pdf):

![image](https://github.com/user-attachments/assets/44f6f125-39d0-4030-bf12-571576660ddd)
![image](https://github.com/user-attachments/assets/a9c92551-a3c6-40bc-a811-59d17ddb76bc)

Nessuno dei due valori da lei adottati è ammesso.
La invitiamo a riprovare scegliendo uno tra quelli ammessi.
Grazie.

**Comment by dkkzzz** [comment]
Noi stiamo utilizzando 2.16.840.1.113883.2.9.10.1.4.1.1 che dovrebbe essere quello del PSS

![image](https://github.com/user-attachments/assets/bf217dfa-7e2d-4a58-8e9f-1dc58af71b31)

**Comment by vigliottim** [comment]
Buongiorno, potrebbe cortesemente allegare il pdf utilizzato per effettuare la chiamata? Grazie.

**Comment by dkkzzz** [comment]
[testpss.pdf](https://github.com/user-attachments/files/17360679/testpss.pdf)

in allegato quanto richiesto

**Comment by vigliottim** [comment]
Buongiorno,
dalle analisi svolte il pdf generato risulta corrotto e non passa la validazione.
La invitiamo a riprovare iniettando il CDA2 all'interno di un pdf tramite il tool online messo a disposizione: [pdf-generator](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/pdf-generator)
Rimaniamo a disposizione nel caso in cui il problema non dovesse risolversi.
Grazie.

**Comment by dkkzzz** [comment]
scusi ma perchè risulta corrotto? aprendolo con adobe reader riesco a vedere la firma e a scaricare il cda2 correttamente. mi può specificare il problema cosi da poterlo risolvere con i componenti che già utilizziamo?

**Comment by dkkzzz** [comment]
che metodo di validazione state chiamando? io non sto utilizzando il metodo di validazione, sto utilizzando i servizi SOAP di FSE 1 forniti dal sistemats per la pubblicazione del documento. A quando mi era stato detto i documenti non passano dal servizio di validazione. Tra l'altro l'errore che mi viene segnalato da tali servizi riguarda i metadati forniti e non il documento stesso.

**Comment by dkkzzz** [comment]
Volevo anche segnalare che la nostra integrazione ha sempre funzionato, solo con questo cliente stiamo avendo problemi, e l'unica differenza rispetto agli altri clienti è il fatto che utilizzi l'aruba key per firmare i documenti

**Comment by LucaRogledi** [comment]
Buongiorno, per le richieste riguardanti FSE 1.0 le chiediamo gentilmente di inoltrare la sua richiesta alla seguente mail: gestionets@sogei.it.
Procediamo alla chiusura della issue, e la invitiamo a riaprirla in caso fosse necessario ulteriore supporto.
Grazie
