### ISSUE TITLE
Errore pubblicazione "Error while perform transform cda to bundle..."

### ISSUE THREAD

**Issue by alessiomaggiori** [ministero-salute/it-fse-support#108]
Buongiorno,
stiamo testando la pubblicazione di un documento in modalità attached. Dopo aver superato la validazione, otteniamo questa risposta dalla chiamata di pubblicazione:

{
   "traceID":"a0773301a67d9506",
   "spanID":"a0773301a67d9506",
   "type":"/msg/fhir-mapping-type",
   "title":"Mapping fhir fallito.",
   "detail":"Error while perform transform cda to bundle:Rule 'Observation3' OUTPUT variable 'specimenp' named as 'specimen' has no value (vars = source variables [cda: (http://hl7.org/fhir/cda/StructureDefinition/Act), entryRelationship: (Element), observation: (http://hl7.org/fhir/cda/StructureDefinition/Observation)], target variables [pat: (Patient), ac: (DiagnosticReport), enc: (Encounter), bundle: (Bundle), e12: (BackboneElement), request: (BackboneElement), obs: (Observation), uuid13: (string), reference: (Reference)], shared variables [])",
   "status":400,
   "instance":"/fhir-resource"
}

Potete darci indicazione sulla causa?
Grazie per l'attenzione

**Comment by Ser-ena** [comment]
Buongiorno, potrebbe cortesemente allegare il CDA utilizzato?

**Comment by alessiomaggiori** [comment]
[30240939461.txt](https://github.com/ministero-salute/it-fse-support/files/10765144/30240939461.txt)

Allego il documento richiesto
Grazie per l'attezione
Saluti

**Comment by francescobus83** [comment]
Buongiorno, pur restando invariati CDA e PDF rispetto ai precedenti invii effettuati con successo, da stamattina anche io sul medesimo invio ho questo ritorno di errore

**Comment by IStacchiotti** [comment]
Buon pomeriggio, potrebbe cortesemente riprovare? Ci faccia sapere se l'errore persiste.
Grazie mille.

**Comment by IStacchiotti** [comment]
Buonasera, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
