### ISSUE TITLE
rad test

### ISSUE THREAD

**Issue by acolzi** [ministero-salute/it-fse-support#1081]
Buongiorno,
sto effettuando i test per l'accreditamento. Ho però alcuni dubbi:
1. tra test0 e test1 le uniche differenze che vedo sono nel passaggio da opzionale a obbligatori di alcune voci, con cambio della cardinalità (0...1 vs 1..1). la colonna opzionale in genere, come la devo intendere, che posso anche non metterla?
ma esattamente, cosa dovrei cambiare? le parti opzionali le devo mettere? come devono differire il cda tra i due test?

2. il caso di test 2 fondamentalmente prevede semplicemente l'aggiunta della parte opzionale delle conclusioni... giusto? Poi l'esempio deve essere ovviamente specifico ad un rx per avere il dettaglio delle radiazioni ionizzanti, 

3. il caso di test 3 prevede ulteriori campi opzionale come il test 4 prevede tutti i campi possibili immaginabili......ok, si farà...
suppongo che il file cda di esempio fornito sia quello relativo al test 4, possibile?

grazie

**Comment by vigliottim** [comment]
Buonasera,
rispondiamo in linea alle sue domande.

> tra test0 e test1 le uniche differenze che vedo sono nel passaggio da opzionale a obbligatori di alcune voci, con cambio della cardinalità (0...1 vs 1..1). la colonna opzionale in genere, come la devo intendere, che posso anche non metterla?
ma esattamente, cosa dovrei cambiare? le parti opzionali le devo mettere? come devono differire il cda tra i due test?

Il caso di test 0 è sempre applicabile e prevede la presenza solo dei campi obbligatori secondo HL7 Italia (colonna _Obbligatorietà da IG_).
Il caso di test 1 prevede la presenza di elementi/attributi non obbligatorii per HL7 Italia ma che lo sono per il caso di test (colonna _Obbligatorietà per Test case 1_), come quelli indicati in figura:

![image](https://github.com/user-attachments/assets/965ed720-4c10-4ade-a6b5-9393e0ac2014)

> il caso di test 2 fondamentalmente prevede semplicemente l'aggiunta della parte opzionale delle conclusioni... giusto? Poi l'esempio deve essere ovviamente specifico ad un rx per avere il dettaglio delle radiazioni ionizzanti,

Il caso di test 2 prevede la presenza di elementi che non sono obbligatori per HL7 Italia ma che lo sono per il caso di test, come, ad esempio, quelli evidenziati in figura:

![image](https://github.com/user-attachments/assets/e9923d47-e69c-4485-857c-2cd6d9513acb)

La sezione con ID="Conclusioni" è opzionale, pertanto può essere omessa:

![image](https://github.com/user-attachments/assets/420e3fe6-7643-4bcd-b888-6667516b8b2c)

La invitiamo a consultare con attenzione il file excel contenente le specifiche per eseguire correttamente il caso di test in esame.

> il caso di test 3 prevede ulteriori campi opzionale come il test 4 prevede tutti i campi possibili immaginabili......ok, si farà...
suppongo che il file cda di esempio fornito sia quello relativo al test 4, possibile?

I casi di test 3 e 4 non sono presenti:

![image](https://github.com/user-attachments/assets/28698c9c-33da-46a2-b757-8fc1409a3397)

Può consultare la documentazione aggiornata ai seguenti link:

- File excel checklist accreditamento: https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/accreditamento-checklist_V8.2.1.xlsx
- File excel casi di test OK per RAD: https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/1-Referto%20di%20Radiologia/CDA2_Referto_di_Radiologia_OK.xlsx
- File excel casi di test KO per RAD: https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/1-Referto%20di%20Radiologia/CDA2_Referto_di_Radiologia_KO.xlsx
- File word con tutti i casi di test per RAD: https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/1-Referto%20di%20Radiologia/casi%20di%20test%20RAD.docx

Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by acolzi** [comment]
Ok grazie. Avevo un file word ed excel con 4 casi di test... non so dove li avevo trovati. Adesso è chiaro cosa mettere e non mettere. grazie

**Comment by acolzi** [comment]
altra domanda.. nel caso in cui gli esami eseguiti siano + di uno, non è chiaro come impostare gli elementi entry. Nel mio caso, radiografica piede dx e sn la parte entry è la seguente:
                    <entry>
                        <act classCode="ACT" moodCode="EVN">
                            <code code="88.28" codeSystem="2.16.840.1.113883.6.103" codeSystemName="ICD-9CM" displayName="Altre radiografie dell'arto inferiore">
                                <originalText>
                                    <reference value="#EsameDesc1"/>
                                </originalText>
                            </code>
                            <text>
                                <reference value="#Esame1"/>
                            </text>
                            <statusCode code="active"/>
                            <effectiveTime value="20241009091321+0200"/>
                        </act>
                        <act classCode="ACT" moodCode="EVN">
                            <code code="88.28" codeSystem="2.16.840.1.113883.6.103" codeSystemName="ICD-9CM" displayName="Altre radiografie dell'arto inferiore">
                                <originalText>
                                    <reference value="#EsameDesc2"/>
                                </originalText>
                            </code>
                            <text>
                                <reference value="#Esame2"/>
                            </text>
                            <statusCode code="active"/>
                            <effectiveTime value="20241009091321+0200"/>
                        </act>
                    </entry>

ma da errore che scompare se mi fermo solo al primo <act></act>
{
  "traceID": "aa6a957b42188750",
  "spanID": "aa6a957b42188750",
  "instance": "/validation/error",
  "detail": "ERROR: -1,-1 cvc-complex-type.2.4.d: Invalid content was found starting with element 'act'. No child element is expected at this point.",
  "type": "/msg/syntax",
  "title": "Errore di sintassi.",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.65210317c66281242a6dcbe1859e6fb61b3c4a9916bd950c9dd1dc625ad72689.620d4f2137^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "status": 400
}
grazie

**Comment by acolzi** [comment]
ancora sui casi di test:
test1 risulta quindi con dicom, quesito diagnostico e suggerimenti obbligatori.
test2  risulta dicom, quesito diagnostico, storia clinica e suggerimenti obbligatori.
ma se vedo il foglio xls di test 2, in riferimento alle informazioni da inserire su storia clinica, mi risulterebbe che stato clinico, cronicità, età insorgenza siano comunque opzionali (età decesso non lo trovo nemmeno)
come per la sezione allergie, sempre sul file xls test 2, risulta tutto opzionale.

quindi?

grazie

**Comment by vigliottim** [comment]
> altra domanda.. nel caso in cui gli esami eseguiti siano + di uno, non è chiaro come impostare gli elementi entry. Nel mio caso, radiografica piede dx e sn la parte entry è la seguente: ` ` ` `
> 
> ma da errore che scompare se mi fermo solo al primo { "traceID": "aa6a957b42188750", "spanID": "aa6a957b42188750", "instance": "/validation/error", "detail": "ERROR: -1,-1 cvc-complex-type.2.4.d: Invalid content was found starting with element 'act'. No child element is expected at this point.", "type": "/msg/syntax", "title": "Errore di sintassi.", "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.65210317c66281242a6dcbe1859e6fb61b3c4a9916bd950c9dd1dc625ad72689.620d4f2137^^^^urn:ihe:iti:xdw:2013:workflowInstanceId", "status": 400 } grazie
 
Potrebbe allegare il CDA2 completo dove indica più esami eseguiti in un file? Grazie.

> ancora sui casi di test:
test1 risulta quindi con dicom, quesito diagnostico e suggerimenti obbligatori.
test2 risulta dicom, quesito diagnostico, storia clinica e suggerimenti obbligatori.
ma se vedo il foglio xls di test 2, in riferimento alle informazioni da inserire su storia clinica, mi risulterebbe che stato clinico, cronicità, età insorgenza siano comunque opzionali (età decesso non lo trovo nemmeno)
come per la sezione allergie, sempre sul file xls test 2, risulta tutto opzionale.

quindi?

grazie

Sono elementi opzionali, per la corretta esecuzione del caso di test deve attenersi a quanto riportato nel test. Grazie.

**Comment by acolzi** [comment]
[42501_CDA.xml.zip](https://github.com/user-attachments/files/17360505/42501_CDA.xml.zip)
e questa è la risposta negativa
{
  "traceID": "b4623e29e8aac92f",
  "spanID": "b4623e29e8aac92f",
  "instance": "/validation/error",
  "detail": "ERROR: -1,-1 cvc-complex-type.2.4.d: Invalid content was found starting with element 'act'. No child element is expected at this point.",
  "type": "/msg/syntax",
  "title": "Errore di sintassi.",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.92e3e7af46f81fa14c27697748eab2e526ddc0d98c2bd8701f69b384b068e7d1.7132b588e9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "status": 400
}

**Comment by vigliottim** [comment]
> Domanda sui casi di test per RSA: anche in questo caso i casi di test OK vanno da 0 a 4. Non vorrei anche in questo caso aver preso il file docx sbagliato. In ogni caso da test2 in poi non sono applicabili nel mio caso, non fanno test di sforzo ne tantomeno visite ginecologiche. Posso mettere come non applicabili, giusto?

E' corretto che siano 4.
Può trovare la documentazione aggiornata al link:
https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/7-Referto%20Specialistico%20Ambulatoriale
Le confermiamo che, nel caso in cui non è possibile eseguire un caso di test, è possibile indicare NO nell’apposita colonna "Applicabilità", avendo cura di giustificarlo opportunamente nella colonna "razionale di applicabilità".

**Comment by LucaRogledi** [comment]
> [42501_CDA.xml.zip](https://github.com/user-attachments/files/17360505/42501_CDA.xml.zip) e questa è la risposta negativa { "traceID": "b4623e29e8aac92f", "spanID": "b4623e29e8aac92f", "instance": "/validation/error", "detail": "ERROR: -1,-1 cvc-complex-type.2.4.d: Invalid content was found starting with element 'act'. No child element is expected at this point.", "type": "/msg/syntax", "title": "Errore di sintassi.", "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.92e3e7af46f81fa14c27697748eab2e526ddc0d98c2bd8701f69b384b068e7d1.7132b588e9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId", "status": 400 }

Buongiorno, 
L'errore da lei riscontrato si risolve utilizzando un solo tag `<act>` all'interno della sezione `<entry>` di"Esame_eseguito".
Come indicato nel excel dei casi di test è possibile inserire n `<entry>`
![image](https://github.com/user-attachments/assets/2b7554fb-87aa-4e42-9250-d194bdc17cbd)
 
che conterrano al massimo una singola sezione `<act>`
![image](https://github.com/user-attachments/assets/75309620-9acb-49a9-b5a5-5d9d7f253dc4)

Grazie

**Comment by acolzi** [comment]
Buongiorno,
Sto provando a fare il pull dei test. sto considerando come indirizzo del repository il seguente:
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/A1#111#ABLIASRLXX/ABLIA/STAN/1.0
è corretto?
Mi da errore ssl. ho quindi configurato il file .git/config con la seguente configurazione:
[https]
    sslCert = /Users/acolzi/Documents/_ablia/work/fascicoloSanitario/certificati/fse.ablia.net/A1#090201REFABLIA/A1#111#ABLIASRLXX.pem
    sslKey = /Users/acolzi/Documents/_ablia/work/fascicoloSanitario/certificati/fse.ablia.net/A1#090201REFABLIA/A1#090201REFABLIA.key

adesso l'errore è
fatal: refusing to work with credential missing host field

e qui mi sono fermato... cosa manca?

grazie

**Comment by vigliottim** [comment]
Il link del repository da lei riportato non è corretto.
La invitiamo a consultare le istruzioni riportate nei commenti seguenti per creare correttamente la pull request:

_Esecuzione fork e commit:_
https://github.com/ministero-salute/it-fse-support/issues/853#issuecomment-2124107085

_Pull request:_
https://github.com/ministero-salute/it-fse-support/issues/695#issuecomment-2022834466


Grazie.

**Comment by acolzi** [comment]
ok, grazie... avevo proprio capito tutto.... 
grazie, pull effettuata.. vediamo un po'

**Comment by acolzi** [comment]
per la cronaca, nemmeno 
https://github.com/ministero-salute/it-fse-accreditamento/tree/main/GATEWAY/A1%23111%23ABLIASRLXX/ABLIA/STAN/1.0/

**Comment by LucaRogledi** [comment]
Buonasera,
i file presenti nella Pull Request che ha aperto https://github.com/ministero-salute/it-fse-accreditamento/pull/1651 non sono visibili all'interno del repository https://github.com/ministero-salute/it-fse-accreditamento/tree/main/GATEWAY in quanto non è ancora avvenuto il merge della Pull Request.
Rimaniamo a disposizione per ulteriore supporto.
Grazie

**Comment by acolzi** [comment]
ok, quindi riappariranno suppongo?

grazie

**Comment by LucaRogledi** [comment]
Corretto

**Comment by acolzi** [comment]
mi è appena arrivata la mail con le modifiche da fare sul file xls ma ancora non vedo il repository... possibile?
https://github.com/ministero-salute/it-fse-accreditamento/tree/main/GATEWAY/A1%23111%23ABLIASRLXX/ABLIA/STAN/1.0/

**Comment by LucaRogledi** [comment]
Buonasera,
questo è il link del suo repository dove può trovare i suoi file per cui ha fatto la richiesta di pull request: https://github.com/acolzi/it-fse-accreditamento/tree/main/GATEWAY/A1%23111%23ABLIASRLXX/ABLIA/STAN/1.0
questo è il repository del ministero-salute dove potrà trovare i file una volta che la PR da lei aperta sarà stata mergiata: https://github.com/ministero-salute/it-fse-accreditamento/tree/main/GATEWAY
Grazie

**Comment by acolzi** [comment]
ok.. sto perdendo un po' la bussola... grazie

**Comment by acolzi** [comment]
ok, una volta aggiornato il file non devo fare altro?

**Comment by LucaRogledi** [comment]
Buonasera,
le confermiamo che le modifiche sono state effettuate correttamente. 
Riceverà aggiornamenti sull'esito delle elaborazioni via e-mail.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
Grazie

**Comment by acolzi** [comment]
Buongiorno,
ho inviato un nuovo aggiornamento. E' possibile sapere se il processo di accreditamento sta proseguendo?

**Comment by vigliottim** [comment]
> Buongiorno, ho inviato un nuovo aggiornamento. E' possibile sapere se il processo di accreditamento sta proseguendo?

Le abbiamo risposto nel thread #1100
