### ISSUE TITLE
Crash Program - Regione Marche - Pubblicazione documento - ERRORE: "Il campo Locality non Ã¨ valorizzato correttamente"

### ISSUE THREAD

**Issue by Didi22515** [ministero-salute/it-fse-support#1082]
Buongiorno, 
effettuando un test di pubblicazione del documento (a seguito della validazione) nell'ambito del Crash program per regione Marche, riceviamo il seguente errore: 
{"traceID":"1669ee6809e04ed8","spanID":"1669ee6809e04ed8","type":"/msg/jwt-validation","title":"Campo token JWT non valido.","detail":"Il campo Locality non Ã¨ valorizzato correttamente","status":403,"instance":"/jwt-mandatory-field-malformed","workflowInstanceId":"UNKNOWN_WORKFLOW_ID"}

il valore inviato è il seguente: 2.16.840.1.113883.2.9.4.1.2 

Questo quanto da specifiche
[CampoLocalitydocx.docx](https://github.com/user-attachments/files/17363487/CampoLocalitydocx.docx)

**Comment by vigliottim** [comment]
Buongiorno, 
dalle analisi effettuate sui log della chiamata con "traceID":"1669ee6809e04ed8", è emerso che il claim _locality_ è stato valorizzato nel modo seguente:
`"locality": "AOU Ospedali Riuniti^^^^^&2.16.840.1.113883.2.9.4.1.2^^^^11090501"`
Esso non rispetta le specifiche descritte in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt).
La invitiamo a riprovare dopo aver corretto il campo in questione come indicato di seguito:
AOU Ospedali Riuniti^^^^^&2.16.840.1.113883.2.9.4.1.2**&ISO**^^^^11090501
Rimaniamo a disposizione nel caso in cui il problema non dovesse risolversi.

**Comment by Didi22515** [comment]
Grazie per il riscontro. Abbiamo appena provato così come indicato sotto, ed ora non riceviamo più l'errore. 
Ne approfitto per chiedere altre info rispetto al seguente errore: {"traceID":"09faccaac36a36eb","spanID":"09faccaac36a36eb","type":"/msg/sign-error","title":"Sign error","detail":"La firma del pdf non risulta valida","status":400,"instance":"/msg/sign-error"}
potreste indicarci i casi in cui si ricevere quest'errore? (il documento in oggetto non è stato firmato da un medico ma da un amministratore, potrebbe essere questo il problema?)
Grazie

**Comment by vigliottim** [comment]
L'errore ricevuto _"La firma del pdf non risulta valida"_ può avere molteplici cause.
Per effettuare indagini più approfondite le chiediamo di allegare il pdf utilizzato.
Grazie.

**Comment by Didi22515** [comment]
Grazie. In allegato il file richiesto per le verifiche 
[base64 1.txt](https://github.com/user-attachments/files/17375050/base64.1.txt)

**Comment by vigliottim** [comment]
Potrebbe allegare anche il file pdf firmato con il CDA2 iniettato? Grazie.

**Comment by Didi22515** [comment]
[Uploading document.pdf…]()

**Comment by LucaRogledi** [comment]
Buongiorno,
dalle analisi sul pdf è emerso il seguente errore relativo alla firma:
![image](https://github.com/user-attachments/assets/b95dfc4c-eab8-4c8b-90aa-2129e248a1b4)

Aprendo un pdf firmato correttamente per verificare la firma tramite adobe reader il risultato è il seguente:
![image](https://github.com/user-attachments/assets/ec586252-c687-4595-9e9e-762d58b5f521)

Inoltre estraendo il cda all'interno del pdf non risulta formattato correttamente 
![image](https://github.com/user-attachments/assets/7b55cd13-4192-401c-ae6a-709c1da87214)

potrebbe gentilmente verificare quanto riportato e riprovare l'invocazione del servizio?
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.

**Comment by Didi22515** [comment]
Buonasera, 
abbiamo riprovato ma abbiamo lo stesso problema sulla firma 
[2.16.840.1.113883.2.9.2.110.4.4^201.BiMind_D3839_43_0.pdf](https://github.com/user-attachments/files/17620975/2.16.840.1.113883.2.9.2.110.4.4.201.BiMind_D3839_43_0.pdf)
[Request 2.txt](https://github.com/user-attachments/files/17620976/Request.2.txt)

di seguito la risposta 
{
   "traceID":"f18ddcee185a1241",
   "spanID":"f18ddcee185a1241",
   "type":"/msg/sign-error",
   "title":"Sign error",
   "detail":"La firma del pdf non risulta valida",
   "status":400,
   "instance":"/msg/sign-error"
}
