### ISSUE TITLE
Crash Program - Regione Veneto CDA non validato

### ISSUE THREAD

**Issue by ppalmerini** [ministero-salute/it-fse-support#1083]
Buongiorno
abbiamo provato ad inviare una richiesta di creazione con il seguente requestBody

{"assettoOrganizzativo": "AD_PSC130", "dataInizioPrestazione": "20240927000000", "healthDataFormat": "CDA", "identificativoDoc": "2.16.840.1.113883.2.9.2.50.4.4^123456", "identificativoRep": "2.16.840.1.113883.2.9.2.50.4.5.3", "identificativoSottomissione": "2.16.840.1.113883.2.9.2.50.4.3.489593", "mode": "ATTACHMENT", "priorita": true, "tipoAttivitaClinica": "OBS", "tipoDocumentoLivAlto": "SUM", "tipologiaStruttura": "Territorio", "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.5721bf93cd748cc87970b5f6ed060c83e2a7d980256096ab332a03bc16d146e8.ca5a81f159^^^^urn:ihe:iti:xdw:2013:workflowInstanceId" }

ma otteniamo il seguente errore 
{
    "traceID": "8b6b169d294efa5c",
    "spanID": "8b6b169d294efa5c",
    "type": "/msg/cda-match",
    "title": "Errore in fase di recupero dell'esito della verifica.",
    "detail": "Il CDA non risulta validato",
    "status": 400,
    "instance": "/cda-validation"
}

in allegato il file pdf validato
Attendiamo un vostro gentile riscontro
grazie
[cda_signed.pdf](https://github.com/user-attachments/files/17374138/cda_signed.pdf)

**Comment by vigliottim** [comment]
Buongiorno,
la informiamo che il pdf deve essere validato prima di procedere alla sua pubblicazione.
Le chiediamo di riprovare ad effettuare la pubblicazione del documento dopo averlo validato o di usare il servizio validate-and-create, verificando che il _workflowInstanceId_ utilizzato nella _requestBody_ di pubblicazione corrisponda a quello ricevuto nell'ultima _response_ di validazione.
Inoltre, specifichiamo che la validazione viene bruciata dopo la chiamata al servizio di pubblicazione.
Restiamo a disposizione per ulteriore supporto o chiarimenti.
Grazie.

**Comment by ppalmerini** [comment]
ok grazie,
ma anche il workflowInstanceId ha una scadenza anche se non viene pubblicato il documento?
grazie

**Comment by LucaRogledi** [comment]
Buongiorno,
La scadenza prevista per la validazione è 5 giorni, il relativo workflowInstanceId rimane visibile tramite il servizio di status.
Per eseguire la pubblicazione correttamente superati i 5 giorni dalla validazione è necessario quindi rieseguire la validazione e poi la pubblicazione, oppure in alternativa richiamare il servizio di validazione e pubblicazione contestuale.
Grazie

**Comment by ppalmerini** [comment]
Ringrazio per le informazioni fornite, a fronte di una nuova validazione siamo riusciti ad ottenere esito positivo dal servizio di creazione.

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Grazie
