### ISSUE TITLE
Anatomia Patologica

### ISSUE THREAD

**Issue by OmarLorenzini** [ministero-salute/it-fse-support#1084]
è possibile avere nella cartella git [it-fse-support]/doc/esempi/CDA/ un xml di esempio per anatomia patologia?

**Comment by vigliottim** [comment]
Buongiorno, 
gli esempi disponibili sono quelli presenti al link: 
https://github.com/ministero-salute/it-fse-support/tree/main/doc/esempi/CDA
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.

**Comment by vigliottim** [comment]
Buonasera,
di seguito le alleghiamo i link relativi alla tipologia documentale RAP:

- File excel e word con casi di test: https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/12-Referto%20di%20Anatomia%20Patologica

- Esempi Casi di test OK: https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/Documenti%20XML%20Casi%20OK/12%20-%20Casi%20OK%20Referto%20di%20Anatomia%20Patologica

Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by OmarLorenzini** [comment]
sarebbe grato avere anche un esempio xml di CDA come esiste per tutte le altre tipologie di documenti in https://github.com/ministero-salute/it-fse-support/tree/main/doc/esempi/CDA

**Comment by OmarLorenzini** [comment]
grazie

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo e procediamo con la chiusura della presente issue. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
