### ISSUE TITLE
FSE 2.0 - Regioni in sussidiarietà

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#1085]
Buongiorno

È confermato il passaggio dalle api FSE1.0 per la prima pubblicazione dei referti, previa validazione sul GTW?

Se sì, potreste prevedere l'autenticazione tramite certificato SSL (magari lo stesso del GTW), offrendo un'alternativa alla Ts-CNS? Sarebbe utile per invii automatici in orario notturno.

**Comment by vigliottim** [comment]
Buongiorno,
rispondiamo in linea alle sue domande.

> È confermato il passaggio dalle api FSE1.0 per la prima pubblicazione dei referti, previa validazione sul GTW?

Sì, è confermato.

> Se sì, potreste prevedere l'autenticazione tramite certificato SSL (magari lo stesso del GTW), offrendo un'alternativa alla Ts-CNS? Sarebbe utile per invii automatici in orario notturno.

No, non è previsto.

Rimaniamo a disposizione per ulteriori chiarimenti.
