### ISSUE TITLE
firma pades e certificato p12

### ISSUE THREAD

**Issue by acolzi** [ministero-salute/it-fse-support#1086]
Buongiorno,

per la firma del referto, utilizzando il vs. tool e un certificato p12, tutto fila liscio e tutto è molto comodo.
Il problema è che il referto, da quanto ho capito, deve essere firmato dal dottore. 
Ora, a meno di non utilizzare i vari token o carte di aruba infocert e company, quindi creare il pdf, farlo scaricare il locale, firmarlo e reinserirlo e poi inviarlo, cosa che vorrei evitare, la soluzione proposta da aruba e infocert è la firma remota, che potrebbe anche andare bene ma ha costi di gestione, per piccoli studi, spropositati.

In realtà infocert potrebbe anche darmi un certificato p12 ma, da quello che mi dicono, sarebbe un certificato "non qualificato" e, secondo loro, non è corretto utilizzarlo per la firma digitale dei referti.

Ha ragione infocert? Possiamo richiedere il certificato p12 per i dottori a sogei o altri che mi permetta di utilizzare la soluzione p12?
grazie

**Comment by acolzi** [comment]
Buongiorno,
non ho ancora ricevuto una risposta alla domanda. Potete verificare quanto richiesto?
grazie in anticipo

**Comment by vigliottim** [comment]
Buongiorno,
la informiamo che sono in corso delle verifiche in merito alla sua richiesta.
Grazie.

**Comment by pFonziSogei** [comment]
Buongiorno,

le logiche di firma del documento non sono a carico del Gateway e sono ampiamente conosciute dalle softwarehouse oltre che dagli utilizzatori. 

Se servono informazioni potete provare a chiedere alla Regione di riferimento, purtroppo non possiamo aiutarla sulla tematica

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
Grazie.
