### ISSUE TITLE
Crash Program - Errore nello status 

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#1088]
Buongiorno,
noi abbiamo restituito un errore XDSDuplicateUniqueIdInRegistry. per completezza:
 
<rs:RegistryResponse xmlns:rs="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0"                           status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure">         <rs:RegistryErrorList highestSeverity="urn:oasis:names:tc:ebxmlregrep:ErrorSeverityType:Error">            <rs:RegistryError codeContext="Duplicated uniqueId (uniqueId - hash - repositoryId)"                              errorCode="XDSDuplicateUniqueIdInRegistry"                              location="2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_032656928463"                              severity="oasis:names:tc:ebxmlregrep:ErrorSeverityType:Error"/>         </rs:RegistryErrorList>      </rs:RegistryResponse>

ma nello status riceviamo
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-10-15T14:49:12.336+02:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_032656928463",
            "subject": "VVNMSM75B01A703D^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "ERP",
            "organizzazione": "041",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.41201.4.4.1.87ec0918f5dec0f45e19d2e82833b2b92672f2a1f80f4799f734a439370aafee.5b3168c6fc^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "fd6587f0d0f62542",
            "issuer": "integrity:S2#041#PABOLZANOTEST",
            "expiringDate": "2025-10-15T14:49:12.370+02:00"
        }

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
La pubblicazione è asincrona e per conoscere il risultato direttamente dal GTW è necessario effettuare una chiamata di [STATUS](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#10-servizio-di-recupero-stato-transazione-per-workflowinstanceid) utilizzando il workflowInstanceId ricevuto in risposta dal servizio di pubblicazione. 

`"workflowInstanceId": "2.16.840.1.113883.2.9.2.41201.4.4.1.87ec0918f5dec0f45e19d2e82833b2b92672f2a1f80f4799f734a439370aafee.5b3168c6fc^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"`

Dalla nostra verifica tramite il servizio di STATUS si riscontra l'errore bloccante da lei riportato.

```
{
"eventType":"SEND_TO_INI",
"eventDate":"2024-10-15T14:49:14.356+02:00",
"eventStatus":"BLOCKING_ERROR",
"message":"SEVERITY:oasis:names:tc:ebxmlregrep:ErrorSeverityType:ErrorERROR_CODE:XDSDuplicateUniqueIdInRegistryCODE CONTEXT:Duplicated uniqueId (uniqueId - hash - repositoryId)",
"workflowInstanceId":"2.16.840.1.113883.2.9.2.41201.4.4.1.87ec0918f5dec0f45e19d2e82833b2b92672f2a1f80f4799f734a439370aafee.5b3168c6fc^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
"expiringDate":"2025-10-15T14:49:14.367+02:00"
}
```

Restiamo a disposizione per ulteriore supporto. Grazie

**Comment by SonnyMate** [comment]
Ok, grazie con il tracertID non viene restituito il "SEND_TO_INI".
