### ISSUE TITLE
Crash program - Problemi con la Delete

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#1089]
Buongiorno,
stiamo analizzando il caso che prevede:
 1. Creazione
 2. Sostituzione
 3. Cancellazione

Ora per il punto 1 e 2 tutto OK. Quando facciamo la richiesta di Cancellazione INI correttamente ci chiede la lista degli oggetti (che in questo caso sono due), ma poi viene fatta la delete solo sul primo elemento della lista, violando secondo noi le specifiche.

ID dell'eliminazione

{
    "traceID": "26bc9323a32e46ae",
    "spanID": "26bc9323a32e46ae",
    "workflowInstanceId": "d6ac05fa750dd32e846257f1af0a25308f86771b97efb3478e27d7da132773aa.841ec2a2e7^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

**Comment by vigliottim** [comment]
Buonasera,
potrebbe cortesemente allegare:

- request e response complete relative al servizio creazione
- request e response complete relative al servizio sostituzione
- request e response complete relative al servizio cancellazione

Grazie.

**Comment by SonnyMate** [comment]
Ciao ma da e verso INI?

**Comment by LucaRogledi** [comment]
Buonasera, con response e request facciamo riferimento a quanto ricevuto in risposta ed inviato verso il gateway dove sono riportati "traceID", "workflowInstanceId" e "govway_id" . Grazie

**Comment by SonnyMate** [comment]
Ora il servizio di cancellazione non ci risponde più...

**Comment by SonnyMate** [comment]
Creazione / pubblicazione
{"traceID":"42f1a74bac75e012","spanID":"42f1a74bac75e012","workflowInstanceId":"2.16.840.1.113883.2.9.2.41201.4.4.1.87ec0918f5dec0f45e19d2e82833b2b92672f2a1f80f4799f734a439370aafee.5acbb99335^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

Replace / sostituzione
{"traceID":"63e0fb5422c0923e","spanID":"63e0fb5422c0923e","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.41201.4.4.1.87ec0918f5dec0f45e19d2e82833b2b92672f2a1f80f4799f734a439370aafee.9396442b2e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

Delete / cancellazione
{
    "traceID": "5da1becccf7b2e55",
    "spanID": "5da1becccf7b2e55",
    "workflowInstanceId": "d6ac05fa750dd32e846257f1af0a25308f86771b97efb3478e27d7da132773aa.9a59b0c3b9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Metto anche lo status della delete il quale conferma che
Riferimenti trovati: urn:uuid:398ecc0a-d38f-4185-ab54-09c3c130d269

Ma nella iti-18 ritorniamo 2 oggetti da cancellare:
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><env:Header xmlns:env="http://www.w3.org/2003/05/soap-envelope"><wsa:MessageID xmlns:wsa="http://www.w3.org/2005/08/addressing">urn:uuid:a5c1ba6b-04c3-431e-b74a-fff971c5fcfb</wsa:MessageID><wsa:Action env:mustUnderstand="true" xmlns:wsa="http://www.w3.org/2005/08/addressing">urn:ihe:iti:2007:RegistryStoredQueryResponse</wsa:Action><wsa:RelatesTo xmlns:wsa="http://www.w3.org/2005/08/addressing">6cd28247-e49c-473a-84fb-5ededb63c792</wsa:RelatesTo></env:Header><soap:Body><ns3:AdhocQueryResponse xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns4="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns5="urn:hl7-org:v3" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Success" totalResultCount="2"><RegistryObjectList><ObjectRef id="urn:uuid:398ecc0a-d38f-4185-ab54-09c3c130d269"/><ObjectRef id="urn:uuid:c8dcf302-e900-4adb-897b-69e270182c6c"/></RegistryObjectList></ns3:AdhocQueryResponse></soap:Body></soap:Envelope>

**Comment by LucaRogledi** [comment]
Buongiorno, potrebbe gentilmente indicarci perchè sono stati inviati due riferimenti nella ITI-18? Grazie

**Comment by SonnyMate** [comment]
Nella replace viene creato un nuovo object e quindi nella iti-18 per recuperare i riferimenti viene restituita una lista

**Comment by LucaRogledi** [comment]
Buongiorno, 
è stato rilasciato un aggiornamento.
Le chiediamo gentilmente di riprovare e darci un feedback.
Grazie.

**Comment by SonnyMate** [comment]
Verifichiamo settimana prossima

**Comment by vigliottim** [comment]
@SonnyMate 
Buongiorno, attendiamo un suo gentile riscontro.
Grazie.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
La invitiamo a riaprirla nel caso in cui fosse necessario ulteriore supporto.
Grazie.
