### ISSUE TITLE
Errore metodo di eliminazione documento pubblicato

### ISSUE THREAD

**Issue by osinfocer** [ministero-salute/it-fse-support#109]
Ho pubblicato con successo il documento con codice 25146 per il quale vi allego:

- file richiesta pubblicazione (25146-req-create.txt)
- file esito pubblicazione (25146-resp-create.txt)
- file PDF inviato (25146-pdf-create.pdf)
- file esisto Get Status (25146-resp-getstatus.txt) 

L'operazione di delete effettuta è la seguente:

`DELETE https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.120.4.4%5E25146`

e l'esito è il seguente:
```
{
  "traceID": "fae5ed66ed168be0",
  "spanID": "fae5ed66ed168be0",
  "type": "/msg/eds-error",
  "title": "Eds error.",
  "detail": "Document cannot be found on the Server FHIR",
  "status": 404,
  "instance": "/msg/eds-document-missing"
}
```

Il problema può dipendere dal fatto che nella getstatus p in errore l'ultimo evento?

```
    {
      "eventType": "EDS_WORKFLOW",
      "eventDate": "2023-02-16T15:10:10.500+00:00",
      "eventStatus": "BLOCKING_ERROR",
      "message": "Error: failed to publish bundle",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.50502.4.4.1.c8e50e1957586fd4b90477e0ad0d3cf4e6b834211297ae45a4441978ce2dbe07.15bb89adc4^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2024-02-16T15:10:10.510+00:00"
    }

```

Per quest'ultima problematica ho già aperto l'issue [https://github.com/ministero-salute/it-fse-support/issues/93](https://github.com/ministero-salute/it-fse-support/issues/93)

Di seguito gli allegati sopra indicati

[25146-req-create.txt](https://github.com/ministero-salute/it-fse-support/files/10757954/25146-req-create.txt)
[25146-resp-create.txt](https://github.com/ministero-salute/it-fse-support/files/10757955/25146-resp-create.txt)
[25146-pdf-create.pdf](https://github.com/ministero-salute/it-fse-support/files/10757956/25146-pdf-create.pdf)
[25146-resp-getstatus.txt](https://github.com/ministero-salute/it-fse-support/files/10757958/25146-resp-getstatus.txt)

**Comment by IStacchiotti** [comment]
Buonasera, l'errore della cancellazione è corretto poichè la pubblicazione, come si evince dalla get status, non è avvenuta con successo.

**Comment by osinfocer** [comment]
Salve. Per cortesia è possibile sapere perché la pubblicazione non è avvenuta con successo? (come dicevo ho aperto ticket #93 per la medesima domanda.

**Comment by IStacchiotti** [comment]
Le faremo sapere quanto prima: il problema è già in analisi con il ticket #93. Essendo un ticket dipendente dal #93, le chiederemmo cortesemente di procedere alla chiusura del presente. Grazie.
