### ISSUE TITLE
Crash program - Errore DELETE

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#1090]
Buon pomeriggio non riusciamo a capire perchè la nostra chiamata DELETE riceve un 404 richiesta inviata da Tue Oct 15 14:18:39 UTC 2024:

DELETE https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.41.4.4%5EIKIS-LAB-PDFCDA2_032656928463

FSE-JWT-Signature: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1YyI6WyJNSUlGYlRDQ0ExV2dBd0lCQWdJVUdockVBVVM4ZDB3T0pzR3hDQXJLc2ptMTF3NHdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlOREEzTWpRd056TTBNRFZhRncweU56QTNNalV3TnpNME1EUmFNRzR4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVI4d0hRWURWUVJoREJaRFJqcEpWQzFRVWs5V1FWZ3dNRmd3TUZnd01EQlpNUjB3R3dZRFZRUUREQlJUTWlNd05ERWpVRUZDVDB4YVFVNVBWRVZUVkRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjBvV1A1L1NVSXlHaWJSeWQ3TkJZYUFiYnp4am9qSDJlR3l0RTVINnJrUExCVlkvUW5ja2tNTnRzYTdJcXhOeExBMENSM1gzbVZ3RjVXcy9OSXlFOVJ1UGY0MnZvZUNZb2d3bk9MOXljMXlJdzNZcm9icnF5MFJBZ3Y2elVmQ0VCZnNGM1l5S1ZxSXFjSTZwUmEwanhHdW5vOHdrTUtZUGZSMHhEWVovcU9aS0RqSUNhR0tSckVycndIcUNyUHJtdXI3ZkUwTHJtWXAxMTBXeU04UktTa1k2M0tsdGFmTkIvanR0VVBocVlaYkdtZlgyVXc3TFlwcURRZG5MdzVVb2JNOFhYa3g1TzFuRWd1TWMvQlhMNSt6ZjJ3ajhFVEEyWnp6cHJ1RDc1QnRPM3BiRE8vQjNJZjJYS3EzYzQ5QkJhNGxNZ0l0Y2lvbmFNOU01dWpoNzBFQ0F3RUFBYU9DQVJnd2dnRVVNQjhHQTFVZEl3UVlNQmFBRkJZNXFSb0ZpYmNQTGJJMTdjSUptc1VEZ3lJL01CSUdBMVVkSUFRTE1Ba3dCd1lGSzB3ZEFRc3dnYTBHQTFVZEh3U0JwVENCb2pDQm42Q0JuS0NCbVlhQmxtaDBkSEJ6T2k4dlkyRnpiMmRsYVhOMmFXd3VjMjluWldrdWFYUXZaV3BpWTJFdmNIVmliR2xqZDJWaUwzZGxZbVJwYzNRdlkyVnlkR1JwYzNRL1kyMWtQV055YkNacGMzTjFaWEk5UTA0bE0wUkRRU3ROYVc1cGMzUmxjbThyWkdWc2JHRXJVMkZzZFhSbEsxUmxjM1FsTWtOUEpUTkVUV2x1YVhOMFpYSnZLMlJsYkd4aEsxTmhiSFYwWlNVeVEwTWxNMFJKVkRBZEJnTlZIUTRFRmdRVVU3OTd6cWM2Q1ZWaERwODhORlpTSENVZ20vRXdEZ1lEVlIwUEFRSC9CQVFEQWdaQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQ3AySStPd1JmQzJPRnFvUEhENjdPU0VIclh2clZvOUJMTFl5eGJhTXpmaHJIdW9rRXNSb1FtNm5PNzR2WWp2citoY1BCRGFxV0ZGVzZqQlVZOGpBUkcyclZhY2JaQ3BSeENqcTlUZmUrTlNLbVVrdmd2bTdTVnZiUngxTXhJVldiL3J4ZzFvZDU3VThlNjI0d3U4ZTg1VkN4Vk5MSlNYaE0xaThKOFJMWFY2VEFIUENNU2FVRmdYYlRpRU96VEQzbUNsb3dlOENXbU5GejJSazBGU21pSWUrZmJabFRsSmR5anB6UDBmWFVzR1JXZ1krUERLYmdPdmhzd1Y1N1BndGg4aVZKcll2THlGaDFhOHZDTlZDZEVhSWhkdHg1QklkZ2QrOFdHL1p5SGxGbEJCc0RaeFdreWNyNkk4OTE0Z1JMNDFxZ2JZV2tLeFV5MlJhMW9tT014WTFxWFAxQWdPM2ZhQktBSmlsRGxTV2VscmNxTTVRMTY3NjNkbXhEUmVJTlNkOHhnUkdMTWtFTC85UHhPL2NLbkUyZ3NnVFNvaHBpQkVPbjlOZU0zeWdhWVlPVFVPZC9iRCs4dlBBUy9rTWxwN2g1WEh0SkxPQTBPQVUyLzVYTlRQNUs0UStCUzVPeUZVQUJoVGh5b3ZIZ3JZVnNvUGxHRS9xVmF1RHJEVG1WYTYxMXJTWExWVGM4YklRQUNYWjNSNDdHOFdQUXJLdm04ZDZCTGJnSURPODlzMWVmRXhPODdpMy9TbHRCZFRoeTI2U1BFZHRyR2hIMU9SeHBOOG1ZYWg1c3ZBbXdQS1JhcytBa25QQlY3S1Z0b0QxVWtvV3lyL1NQbVBBeDhack53T1d4SVYxdDJwZThQRS9kRE1SNU1qQkRtYUxHNjFuZHZENllWS0NIWnZBPT0iXX0.eyJpc3MiOiJpbnRlZ3JpdHk6UzIjMDQxI1BBQk9MWkFOT1RFU1QiLCJpYXQiOiIxNzI5MDAxOTE5IiwiZXhwIjoiMTcyOTAwNTUxOSIsImp0aSI6IjAwMDAwMDAwMDAwMjkzIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwic3ViIjoiVlZOTVNNNzVCMDFBNzAzRF5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIiwic3ViamVjdF9vcmdhbml6YXRpb25faWQiOiIwNDEiLCJzdWJqZWN0X29yZ2FuaXphdGlvbiI6IlAuQS4gQm9semFubyIsImxvY2FsaXR5IjoiTEFCT1JBVE9SSU8gREkgUFJPVkFeXl5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4xLjMmSVNPXl5eXjExMTEwMTEyMzQ1NiIsInN1YmplY3Rfcm9sZSI6IkFBUyIsInBlcnNvbl9pZCI6IlBSVkZTTjcwUzA0QTk1MlpeXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyIsInBhdGllbnRfY29uc2VudCI6InRydWUiLCJwdXJwb3NlX29mX3VzZSI6IlVQREFURSIsInJlc291cmNlX2hsN190eXBlIjoiKCcxMTUwMi0yXl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsImFjdGlvbl9pZCI6IkRFTEVURSIsImF0dGFjaG1lbnRfaGFzaCI6ImYzODU1M2FjMmE4YWM4NTExY2QzNDBlMTQ1OWZhNzcwYTg5ZTFiZTU0YzdhZmI4ODBlMGUwMzUyNWJlMWIxNmUiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiQ09OQ0VSVE8iLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlbmRvciI6IkRFREFMVVMgU1BBIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiMjIuMS4xIn0.DlnF8_F1PnhUGdjC59A-JT6ceTQhzS4lThuJxPg2ptG8HAVbA6hwZxJrJYUAudWz1mjcesFWXb1NlJn5y2KzmWHcyQ_gZizYRY8z8dxGGkFlyTs_G4BGSeoF6-W1OvYAbK_9sGKL5XooQtuHsUiOxdH96jrWLCJGA7FkFrLlvDBADfG369AEEraDpAPX2QJmH8nfM1KEOT6bGTBTonHyNNjSAqf3prJSD4K0aheZMC-ycPL-a51Rj1-fLHdNBR7e7boltE6-VoTCpJ69tgcPwffoD2lQdtgjpZazLbD3oOxVIWcfV_cPabEkuRe7FH5a4mEq_Gh3frEzgpIWTKhnnA

Facendo la stessa richiesta da Postman sembra andare a buon fine... 

Grazie

**Comment by vigliottim** [comment]
Buonasera,
le chiediamo di allegare le response complete comprensive di traceId/govwayId di entrambi i casi. 
Grazie.

**Comment by SonnyMate** [comment]
Buongiorno se mi risponde 404 non ci sono il traceId/govwayId

Per quella andata a buon fine
{
    "traceID": "de3eab5182c108e7",
    "spanID": "de3eab5182c108e7",
    "workflowInstanceId": "d6ac05fa750dd32e846257f1af0a25308f86771b97efb3478e27d7da132773aa.a65efcfad9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

**Comment by LucaRogledi** [comment]
Buongiorno, 
Potrebbe gentilmente indicarci l'applicativo che sta utilizzando per la chiamata e la response completa in cui ha ricevuto il codice 400 se possibile? Grazie

**Comment by SonnyMate** [comment]
SAP IntegrationSuite, è un servizio gestito nella cloud di SAP BTP

**Comment by SonnyMate** [comment]
Si confermo tutto ok
