### ISSUE TITLE
CDA Anatomia Patologica (RAP) :  Richiesta di copertura funzionale al di fuori del campo di competenza

### ISSUE THREAD

**Issue by rocco-pecoraro** [ministero-salute/it-fse-support#1091]
Salve,
Nella mia azienda ci stiamo occupando dell'analisi e dello sviluppo del CDA2 per Anatomia Patologica (RAP).
Quindi abbiamo analizzato i casi di TEST(doc+excel) presenti sul repository  e ART-DECOR di HL7italia. Riporto di seguito le seguenti problematiche:

**1.** Le informazioni richieste obbligatoriamente nel caso di TEST N°1,2,3, in particolare mi riferisco alla gestione delle informazioni di _Anamnesi Familiare, Fisiologica, Patologica Remota, Patologica Prossima_ soprattutto in un formato strutturato sembra che il CDA2 RAP sia stato pensato per la gestione di uno screening-oncologico e\o per una cartella clinica, oncologica e/o chirurgica. Per esempio la sezione delle allergie ha senso nel caso l'assisto debba affrontare un intervento chirurgico o affrontare un ciclo di cura di chemio-terapia o di radio terapia ma penso che da nessuna informazione. L'anatomia patologica ha come input un materiale ottenuto da un prelievo ottenuto tramite una procedura  con lo scopo di individuare un morfologia (un tumore se presente per esempio). Tutte le informazioni di anamnesi richieste molto probabilmente non influiscono sull’individuazione della morfologia ma influirebbero su una diagnosi generale fatta guardando l’intera cartella clinica dell’assistito e quindi non direttamente da un patologo del laboratorio. L’informazione se l’assistito sia o meno un fumatore è una informazione del tutto statistica richiesta da software che effettuano per esempio uno screening-oncologico. Infatti lo scenario plausibile è che un paziente entri sala operatoria per la rimozione/campionamento di materiale in quel caso c’è bisogno di un anamnesi ma una volta estratto il materiale e portato nel laboratorio di anatomia patologica tali informazioni non danno alcun aiuto al patologo. 

2. Dato che i dati di anamnesi sono richiesti comunque in un formato strutturato con un dettaglio elevato una applicazione verticale di anatomia patologica per raccogliere tutte queste informazioni deve contenere al suo interno delle funzioni raccolta delle anamnesi pari al sistema di refertazione dei verticali che hanno generato gli stessi dati di anamnesi. Se bisogna inserire un anamnesi che riguarda un emocromo, marcatori tumorali o un indagine microbiologica nell’anamnesi  bisogna inserire un CDA di laboratorio?  Se la risposta è si bisogna tenere conto di tutte possibili informazioni di anamnesi ? quali sono i casi d’uso possibili?

**3.**Altro problema che sottopongo è l’utilizzo dei codici SNOMED-CT, le anatomie di riferimento su cuoi lavoriamo utilizzano ampiamente codici SNOMED V3 oppure NAP ampiamente diffusi nella bibliografia dei patologi.

**4.**L’assenza di casi di test verticali sull’anatomia patologica gli esempi XML e della documentazione in formato PDF che  spieghi in modo accurato una specifica. ART-DECOR per i non addetti ai lavori richiede di “interpretare” e quindi sarà fonte di molti errori.

Rocco

**Comment by vigliottim** [comment]
Buon pomeriggio,
rispondiamo per punti relativamente alla sua issue:

**_Risposta Domande 1-2:_** No, non è necessario riportare un CDA di Laboratorio ma le informazioni atte a fornire un inquadramento generale dello stato di salute del paziente, della sua storia clinica e della motivazione che ha scaturito l’esigenza di sottoporre il paziente all’esame diagnostico sono riportabili all’interno della sezione “Notizie Cliniche” che contiene al suo interno delle sottosezioni atte a descrivere: precedenti esami eseguiti, terapie farmacologiche pregresse, Precedenti trattamenti e procedure chirurgiche e diagnostiche pregresse, Indagini Radiologiche, etc.

_**Risposta Domanda 3:**_ Secondo le Linee Guida HL7 Italia, dove richiesto, è necessario utilizzare la codifica SNOMED-CT.

_**Risposta Domanda 4:**_ Di seguito le alleghiamo i link relativi alla tipologia documentale RAP:
- _File excel e word con Casi di Test:_ https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/12-Referto%20di%20Anatomia%20Patologica
- _Esempi Casi di Test OK:_ https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/Documenti%20XML%20Casi%20OK/12%20-%20Casi%20OK%20Referto%20di%20Anatomia%20Patologica

Rimaniamo a disposizione per chiarimenti.

**Comment by rocco-pecoraro** [comment]
Salve,
Da dove possiamo reperire i vocabolari SNOMED-CT, LOINC, e ICD9-CM di riferimento per la costruzione del CDA.

Rocco

**Comment by vigliottim** [comment]
Buongiorno, 
il caso di test 3 (non obbligatorio) è un caso d’uso sviluppato per il processo di accreditamento in conformità con il decreto del 7 settembre 2023. 
Per quanto riguarda la struttura delle "informazioni necessarie a fornire un inquadramento generale", e di eventuali altre informazioni, a seconda delle sue necessità ed esigenze, sono disponibili le specifiche HL7
Italia. 
Inoltre, vengono riportati i link relativamente ai dizionari:
- Loinc Download LOINC
- SNOMED
- ICD9CM Il
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
