### ISSUE TITLE
Chiarimenti su nullFlavour

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#1093]
Buongiorno, mi scuso in anticipo se la domanda è banale o peggio, ma per non sbagliare avrei bisogno di un chiarimento.
Nella documentazione dei documenti RAD, a pagina 26, leggo che se non si possiedono, come in molti casi, i dati del PACS si possono usare i valori @nullFlavour.
Ho letto quella che credo sia la documentazione di riferimento [QUI](https://terminology.hl7.org/CodeSystem-v3-NullFlavor.html)  ma, non avendo mai avuto a che fare con questa tipologia di valori, ho dei dubbi sull'utilizzo: in mancanza dei dati, in ogni campo dovrei inserire il valore 10610? Potete aiutarmi?
Grazie mille.

**Comment by vigliottim** [comment]
Buongiorno, 
è possibile inserire un _nullFlavor_ quando non sono disponibili le informazioni relative a un elemento/attributo. 
Le modalità di valorizzazione dipendono dalla tipologia di elemento/attributo in esame. 
Le riportiamo di seguito alcuni esempi:

`<code nullFlavor="NA"/>`

```
<effectiveTime>
<low nullFlavor="UNK"/>
</effectiveTime>
```

Rimaniamo a disposizione per ulteriori chiarimenti

**Comment by infoserviceonline** [comment]
Nel mio caso riguarderebbe pagina 27, i valori id del PACS, che riporto sotto, ma vorrei capire qual è il principio da applicare e dove posso apprenderlo.
**Esempio di implementazione secondo <id>:
<id root="[OID_SPAZIO_IDENTIFICAZIONE__AZIENDA_CUSTODE_PACS]"
extension="[NUMERO_IDENTIFICATIVO__PERSONALE]"
assigningAuthorityName="[NOME_SPAZIO_IDENTIFICAZIONE_
AZIENDA_CUSTODE_PACS]"/>**
Grazie ancora.

**Comment by vigliottim** [comment]
Può fare riferimento allo schematron relativo a RAD per capire dove e come può inserire un _nullFlavor_: 
https://github.com/ministero-salute/it-fse-catalogs/blob/main/schematron/schematronFSE_RAD_v3.8.sch

Per le possibili valorizzazioni, spesso sono prescritte dalla stessa guida HL7 Italia:

![image](https://github.com/user-attachments/assets/4552af45-b68d-4c8d-b62d-4f539ec07241)

In caso contrario, può consultare [hl7.org](https://www.hl7.org/).
Inoltre, specifichiamo che per la valorizzazione corretta degli attributi del secondo tag _id_ contenuto in _PatientRole_ dovrebbe fare richiesta all’Azienza che custodisce il PACS.
Rimaniamo a disposizione.

**Comment by infoserviceonline** [comment]
Grazie mille per la disponibilità, chiudo il ticket.

**Comment by vigliottim** [comment]
Grazie a lei.
Rimaniamo a disposizione per altre richieste di supporto.
