### ISSUE TITLE
Reportistica riepilogativa chiamate al gateway

### ISSUE THREAD

**Issue by assistenza-fsevda** [ministero-salute/it-fse-support#1096]
Buongiorno,
durante il SAL del Crash Program che si è tenuto lunedì è stato presentato l'excel che riepiloga per ogni issuers il numero di chiamate effettuate verso il gateway, sia come RDE=RDA che come RDE<>RDA. Si sa quando verrà reso disponibile sullo sharepoint? Al momento non lo abbiamo trovato ma ci sarebbe utile per capire quali chiamate vengono "intercettate" e quali no. Inoltre se abbiamo capito bene verrà aggiornato giornalmente in quanto si tratta di un automatismo. È corretto?

Grazie anticipatamente per il supporto.

**Comment by IStacchiotti** [comment]
Buonasera, Il merito al report al quale fa riferimento, le modalità di condivisione sono ancora in corso di valutazione da parte del dipartimento.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
Grazie.
