### ISSUE TITLE
errore validazione documento gateway

### ISSUE THREAD

**Issue by fmatraxiafse** [ministero-salute/it-fse-support#1097]
Buongiorno,

nel richiamare il servizio di validazione https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation passando da un middleware ottengo l'errore

{
    "type": "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
    "title": "AuthorizationContentDeny",
    "status": 403,
    "detail": "Unauthorized request content",
    "govway_id": "d216b45b-8ba6-11ef-a4d1-005056ae54fa"
}

Quali potrebbero essere le problematiche legate all'errore?

**Comment by vigliottim** [comment]
Buon pomeriggio,
dalle analisi effettuate è emerso un errore nell'utilizzo dei certificati:

![image](https://github.com/user-attachments/assets/2f65ca9c-70f6-4f63-8abd-70ebf615a5f7)

In particolare, analizzando i token con il tool online [jwt.io](url), sembra che siano stati usati due diversi certificati per la generazione dei JWT e per il canale di comunicazione (i common name, infatti, non sono coerenti):

_X-Security-Token:_
<img width="231" alt="image" src="https://github.com/user-attachments/assets/0f06066b-1c1c-4129-b8d2-dae17ac38cd1">

_Authorization Bearer Token:_
<img width="265" alt="image" src="https://github.com/user-attachments/assets/5a1390f2-9a0b-4fce-a093-e21e64cbf593">

_FSE-JWT-Signature Token:_
<img width="276" alt="image" src="https://github.com/user-attachments/assets/0b72a4ae-5216-4bb8-bba5-66e2b17c1cff">

La preghiamo di verificare e riprovare ad effettuare la chiamata dopo aver rigenerato i token con la coppia di certificati corretta.
Grazie.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto riscontri, procediamo alla chiusura della presente issue.
La invitiamo a riaprirla nel caso in cui sia necessario ulteriore supporto.
Grazie.
