### ISSUE TITLE
Errore 403 in validazione

### ISSUE THREAD

**Issue by nspazzoli** [ministero-salute/it-fse-support#110]
Buongiorno,

vi scrivo per avere informazioni in merito ad un tentativo di validazione pdf tentato ieri 2023-02-16 14:24

Otetngo la seguente risposta:
{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","detail":"Unauthorized request content","status":"403"}

GovWay-Transaction-ID=eb09e07a-adf1-11ed-a9a6-005056ae7395

Allego file con la coppia di token
[jwt.txt](https://github.com/ministero-salute/it-fse-support/files/10764827/jwt.txt)

Cosa vi risulta sbaglliato? 
Grazie.

Nicola Spazzoli

**Comment by zukka77** [comment]
@masciamariotti stanno provando il middleware regionale e quindi l' "incongruenza" è normale:
il fornitore firma col suo, manda alla regione che "trasporta" con altro certificato e govWay scarta.
Va verificata e probabilmente rivista la configurazione di govWay per l'ambiente di test.
@nspazzoli ti teniamo aggiornato.

**Comment by IStacchiotti** [comment]
Buongiorno, segnaliamo che l’errore dipende dal fatto che si sta utilizzando un certificato non corretto per la chiamata tramite Middleware: è necessario chiedere un certificato regionale sotto la regione fittizia 111.

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
