### ISSUE TITLE
accreditamento

### ISSUE THREAD

**Issue by acolzi** [ministero-salute/it-fse-support#1100]
Buongiorno,
dopo aver  inviato un nuovo aggiornamento il processo di controllo e accreditamento riparte in automatico?
E' possibile sapere se il processo di accreditamento sta proseguendo?

**Comment by vigliottim** [comment]
Buongiorno, 
ieri dovrebbe aver ricevuto una comunicazione all'e-mail indicata in fase di registrazione con il seguente errore: 
_"Informazioni Fornitore malformati.Assicurarsi che i campi appVendor,appId,appVersion risultino valorizzati"_.
La invitiamo a correggere il file _data.json_ tramite nuova pull request correttiva. 
Rimaniamo a dispozione per chiarimenti

**Comment by acolzi** [comment]
ok, effettuata nuova pull request

**Comment by vigliottim** [comment]
Grazie per il gentile feedback.
Riceverà l'esito delle elaborazioni come di consueto via e-mail.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
