### ISSUE TITLE
WorkflowInstanceId - durata in test

### ISSUE THREAD

**Issue by ppalmerini** [ministero-salute/it-fse-support#1101]
Buongiorno, 
ci è stato indicato che la validità del workflowInstanceId è di 5 giorni (salvo il caso in cui sia stata fatto un invio al servizio di creazione), dopodichè serve eseguire una nuova validazione del documento.
Tale durata è prevista solo in ambiente di test o verrà mantenuta anche in ambiente di prod?
Rimango in attesa di vostro gentile riscontro
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno,
Al momento risulta che la validità della validazione in ambiente di produzione rimarrà di 5 giorni come in ambiente di test.
Grazie

**Comment by ppalmerini** [comment]
Buonasera, ringrazio per le delucidazioni
Ringrazio per le delucidazioni.

**Comment by vigliottim** [comment]
Grazie a lei per il gentile feedback.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
