### ISSUE TITLE
Errore in fase di validazione Cda2 RAD

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#1102]
Buongiorno, nelle more dell'implementazione operativa, sto facendo alcuni test di code review.
Nello specifico ho generato un Cda2 Rad INCOMPLETO, ma ricevo già un errore  che non capisco:
{
  "traceID": "7b94fe73edc98f16",
  "spanID": "7b94fe73edc98f16",
  "type": "/msg/generic-error",
  "title": "Errore generico.",
  "detail": "Duplicate key **2.16.840.1.113883.2.9.4.3.2**",
  "status": 500,
  "instance": "",
  "workflowInstanceId": null,
  "warning": null
}
La chiave duplicata alla quale si riferisce è l'OID del MEF che, secondo la documentazione, DEVE essere inserita nel patientRole, nell'assignedAuthor e nel legalAuthenticator, cosa che ho fatto. Gli ultimi due hanno la stessa  extension, dal momento che è semppre lo stesso medico. Perchè mi dice che è duplicata? 
E' ovvio che mi sta sfuggendo qualcosa, visto che i test case sono a posto, ma non capisco cosa. Potreste aiutarmi?
Grazie mille.
(Allego CDA utilizzato
[cdarad.zip](https://github.com/user-attachments/files/17409506/cdarad.zip)
)

**Comment by LucaRogledi** [comment]
Buongiorno, 
valorizzando `PatientRole/id/@root` con `2.16.840.1.113883.2.9.4.3.2` sta facendo riferimento alla sezione **"Cittadino italiano o straniero residente, iscritto SSN (Codice Fiscale)"** indicata sul [pdf hl7](https://www.hl7.it/wp-content/uploads/2024/04/HL7IT-IG_CDA2_RAD-v1.1-S.pdf) in cui viene indicata la valorizzazione corretta da utilizzare per i due tag `id`.

![image](https://github.com/user-attachments/assets/78fbc633-92c5-4c89-991f-e2ebe2dd73bf)
![image](https://github.com/user-attachments/assets/71e5f739-e904-44dd-a501-d0fc4ae34a71)

l'OID da utilizzare per il secondo tag `id` corrisponde allo spazio di identificazione usato nell’Azienza che custodisce il PACS nel quale sono contenute le immagini.
Pertanto per la valorizzazione corretta degli attributi del secondo tag id contenuto in PatientRole dovrebbe fare richiesta all’Azienza che custodisce il PACS.
Grazie

**Comment by infoserviceonline** [comment]
Grazie mille per il supporto, come sempre puntuale ed esaustivo. In effetti, riagganciandomi ad un altro mio ticket, basta inserire null nei campi se non si hanno i dati del pacs. Chiudo e proseguo.
Grazie ancora.
