### ISSUE TITLE
Crash Program - Regione Molise - UC6 - Problema nella validazione documento di sostituzione

### ISSUE THREAD

**Issue by marlagatta** [ministero-salute/it-fse-support#1103]
Salve.

In seguito a validazione di un documento che sara' oggetto di UC6 (sostituzione documento per RDE=! RDA), dove RDE e' Molise e RDA e' Lazio, documento di tipo Referto di laboratorio, 
si ottiene l'errore
```
{
   "traceID": "76a024fad9429da9",
   "spanID": "76a024fad9429da9",
   "type": "/msg/syntax",
   "title": "Errore di sintassi.",
   "detail": "Error while executing validation on xsd schema",
   "status": 400,
   "instance": "/validation/error",
   "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.a0003ce46b7184c938f3e2d075bea1702a9d08174cae7d8b0f914f36304a4687.358a2d4501^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```

Potreste cortesemente aiutarci a capire la problematica?
Grazie mille

**Comment by LucaRogledi** [comment]
Buongiorno, 
Potrebbe gentilmente allegare il pdf utilizzato per la chiamata?
Grazie

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
Dalle nostre verifiche effettuate sulla chiamata con "traceID": "76a024fad9429da9", risulta che l'errore è stato generato a causa di una malformazione del cda iniettato nel pdf.
Segnaliamo che è presente la chiusura di alcune sezioni che non sono state aperte e risultano obbligatorie secondo hl7:

![image](https://github.com/user-attachments/assets/f09ae0f4-c8cd-4fdd-a867-a819c8ad0c61)

![image](https://github.com/user-attachments/assets/4ddc6551-7241-44f9-95a0-4650f97aad8c)

La invitiamo a riprovare dopo aver corretto il cda e generato un nuovo pdf, seguendo le indicazioni [hl7 LAB](https://www.hl7.it/wp-content/uploads/2024/04/HL7IT-IG_CDA2_RefertoMedicinaLab-v1.3-S.pdf) o il cda di esempio messo a disposizione online [LAB.xml](https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/LAB.xml). 
Restiamo a disposizione per ulteriore supporto.
Grazie

**Comment by marlagatta** [comment]
Grazie mille per il supporto
