### ISSUE TITLE
Crash Program - Informazioni circa l'avanzamento dei test

### ISSUE THREAD

**Issue by marco-volpe** [ministero-salute/it-fse-support#1104]
Buongiorno

ci potete indicare se i vostri batch di monitoraggio degli esiti dei risultati siano già in funzione e stiano generando dei report?

Nei nostri test ci risultano delle notify comunicazione metadati per le regioni Lazio, Umbria e Puglia e vorremmo sapere questi risultino anche nei vostri report.

Secondo la documentazione i risultati e le issue degli errori dovrebbero essere pubblicati sul repo [https://github.com/ministero-salute/it-fse-gtw-crash-program](https://github.com/ministero-salute/it-fse-gtw-crash-program) ma al momento non vediamo ancora nulla.

Ci sono degli avanzamenti in merito?

Grazie

**Comment by LucaRogledi** [comment]
Buongiorno,
il riscontro positivo viene fornito con il censimento dell'RDE nel file “issuers_success.json”, nel momento in cui vengono svolte le chiamate (creazione, aggiornamento metadati, sostituzione e cancellazione) considerando come RDA ciascuna delle regioni censite nel file "issuers.json".
La rimandiamo anche alla [documentazione ](https://ministero-salute.github.io/it-fse-support/)disponibile a questo link per maggiori dettagli, e rimaniamo a disposizione per ulteriori chiarimenti.
Grazie

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
