### ISSUE TITLE
Crash Program (fase2) - Aggiornamento metadati da FVG verso Regione Umbria - ERRORE R221

### ISSUE THREAD

**Issue by ChiaraCeccottiFVG** [ministero-salute/it-fse-support#1106]
Buongiorno,
eseguendo un aggiornamento metadati verso la regione Umbria di un Patient Summary otteniamo il seguente errore
```
{
    "traceID": "39f1291da53a81e8",
    "spanID": "39f1291da53a81e8",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "status": 500,
    "detail": "{\"traceID\":\"39f1291da53a81e8\",\"spanID\":\"793d386542517071\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R221CODE CONTEXT:The version number included in the update request did not match the existing object\",\"instance\":\"error/generic\"}",
    "instance": "/msg/service-error/ini",
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}
```
Vi chiediamo cortesemente una verifica per aiutarci a capire il problema. 
Rimaniamo a disposizione e ringraziamo anticipatamente.

**Comment by LucaRogledi** [comment]
Buonasera,
Chiediamo gentilmente la verifica da parte della regione di riferimento.
Restiamo a disposizione per ulteriore supporto, grazie

**Comment by angeloceloni** [comment]
Buonasera
è stato rilasciato un aggiornamento, potete riprovare?

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
abbiamo riprovato una metadata update, purtroppo otteniamo il seguente errore:
```
{
    "traceID": "9ee83c1ae2cc63e3",
    "spanID": "9ee83c1ae2cc63e3",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "status": 500,
    "detail": "{\"traceID\":\"9ee83c1ae2cc63e3\",\"spanID\":\"e5a8a68fd917e6a3\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R221CODE CONTEXT:The version number included in the update request did not match the existing object\",\"instance\":\"error/generic\"}",
    "instance": "/msg/service-error/ini",
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}
```
Essendo che la metadata update andrà comunque rivista secondo quanto emerso nei SAL del Crash program diteci pure voi se ha senso testare ora questo scenario o se attendere.
Rimaniamo in ogni caso a disposizione e ringraziamo.

**Comment by angeloceloni** [comment]
Buongiorno
abbiamo segnalato il problema al fornitore e siamo in attesa di risoluzione. L'errore segnalato al fornitore è relativo al messaggio di errore errato, a fix rilasciato restituiremo comunque l'errore XDSRegistryError perché l'attuale request inviata da INI è errata come da issue [1136](https://github.com/ministero-salute/it-fse-support/issues/1136).
Direi di riprovare dopo la risoluzione della issue indicata.

**Comment by angeloceloni** [comment]
Buonasera
la request inviata da INI è stata aggiornata e l'attuale viene gestita correttamente dal registry di Regione Umbria.
Potete riprovare?

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno, abbiamo riprovato una transazione di metadata update verso la regione Umbria ed è stata eseguita con successo.
Ringrazio per la collaborazione e auguro una buona giornata.

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback, e procediamo con la chiusura della presente issue. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
