### ISSUE TITLE
Crash Program (fase2) - Aggiornamento metadati da FVG verso Regione Emilia-Romagna - ERRORE CRF2

### ISSUE THREAD

**Issue by ChiaraCeccottiFVG** [ministero-salute/it-fse-support#1107]
Buongiorno,
eseguendo un aggiornamento metadati verso la regione Umbria di un Patient Summary otteniamo il seguente errore
```
{
    "traceID": "ba30c1e953972c9e",
    "spanID": "ba30c1e953972c9e",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "status": 500,
    "detail": "{\"traceID\":\"ba30c1e953972c9e\",\"spanID\":\"63ec2f0c38011b38\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.\",\"instance\":\"error/generic\"}",
    "instance": "/msg/service-error/ini",
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}
```
Vi chiediamo cortesemente una verifica per aiutarci a capire il problema. 
Rimaniamo a disposizione e ringraziamo anticipatamente.

**Comment by LucaRogledi** [comment]
Buonasera,
Chiediamo gentilmente la verifica da parte della regione di riferimento.
Restiamo a disposizione per ulteriore supporto, grazie

**Comment by daniele-gubellini** [comment]
Buongiorno, 
confermiamo il problema sull'aggiornamento metadati. 
Siamo in attesa che venga chiusa la #761

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
Ringrazio molto @daniele-gubellini per la conferma.
Ricordavamo la issue 761 dalla fase 1, era per conferma che il problema fosse legato.
Grazie ancora e Buon pomeriggio.

**Comment by vigliottim** [comment]
Buonasera, 
chiudiamo il presente ticket dal momento che le regioni Friuli-Venezia Giulia e Emilia-Romagna sono esonerate dal Post Crash Program.
Rimaniamo a disposizione per altre richieste di supporto.
