### ISSUE TITLE
Regione Valle d'Aosta - Errore pubblicazione Basilicata

### ISSUE THREAD

**Issue by assistenza-fsevda** [ministero-salute/it-fse-support#1109]
Buongiorno,
segnaliamo che tentando la pubblicazione di un documento sul CF PRVPVT81E03F052W di Regione Basilicata la presa in carico da parte del Gateway è positiva ma, verificando la transazione per status, è presente un errore in "SEND_TO_INI" che riporta un _Internal Error 9000_

Di seguito la risposta completa della verifica per WII:

```
{
	"traceID": "0520a15db0633154",
	"spanID": "d32ac057946fd692",
	"transactionData": [
		{
			"eventType": "VALIDATION_FOR_PUBLICATION",
			"eventDate": "2024-10-18T11:40:05.185+02:00",
			"eventStatus": "SUCCESS",
			"subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"organizzazione": "020",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.31fe73ed14^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "e3a162a689ca3ca5",
			"issuer": "integrity:S1#020#020VALDAOSTATEST",
			"expiringDate": "2025-10-18T11:40:05.193+02:00"
		},
		{
			"eventType": "PUBLICATION",
			"eventDate": "2024-10-18T11:40:05.245+02:00",
			"eventStatus": "SUCCESS",
			"identificativoDocumento": "2.16.840.1.113883.2.9.2.20.4.4^001.CRASHPRG.TESTRSA:BAS0001-0",
			"subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"tipoAttivita": "CON",
			"organizzazione": "020",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.31fe73ed14^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "e3a162a689ca3ca5",
			"issuer": "integrity:S1#020#020VALDAOSTATEST",
			"expiringDate": "2025-10-18T11:40:05.253+02:00"
		},
		{
			"eventType": "SEND_TO_INI",
			"eventDate": "2024-10-18T11:40:05.703+02:00",
			"eventStatus": "BLOCKING_ERROR",
			"message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 9000",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.31fe73ed14^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"expiringDate": "2025-10-18T11:40:05.710+02:00"
		}
	]
}
```

Ci servirebbe un supporto per la risoluzione della problematica.
Grazie anticipatamente per l'aiuto.

**Comment by vigliottim** [comment]
Buon pomeriggio,
chiediamo gentilmente alla regione di riferimento di svolgere le opportune verifiche.
Restiamo a disposizione per ulteriore supporto.
Grazie.

**Comment by assistenza-fsevda** [comment]
buongiorno
abbiamo iterato nuova sequenza dei 4 servizi su PRVPVT81E03F052W coN i seguenti esiti:

CREATE : ESITO OK

{"traceID":"62799c5ee2b702b4","spanID":"62799c5ee2b702b4","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.7718ace647^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}


{"traceID":"9446eecfa818b6b3","spanID":"9446eecfa818b6b3","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.b086880634^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

{"traceID":"c207395346b6610b","spanID":"c207395346b6610b","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.cbe0be0526^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

--------------------------------------
REPLACE DOC: ESITO KO
  {
    "codice": "500",
    "descrizione": "{\"traceID\":\"99186174f9ef4718\",\"spanID\":\"99186174f9ef4718\",\"type\":\"/msg/generic-error\",\"title\":\"Errore generico.\",\"detail\":\"Index: 0, Size: 0\",\"status\":500,\"instance\":\"\"}",
    "esito": "KO",
    "tipo": "replace"
  },
  {
    "codice": "-1",
    "descrizione": "WorkflowInstanceId non valido per richiesta getStatus",
    "esito": "KO",
    "tipo": "replace status"

----------------------------------------------
METADATA UPDATE: ESITO KO

"codice": "500",
    "descrizione": "{\"status\":500}",
    "esito": "KO",
    "tipo": "update"
  },
  {
    "codice": "-1",
    "descrizione": "WorkflowInstanceId non valido per richiesta getStatus",
    "esito": "KO",
    "tipo": "update status"

------------------------------------
DELETE: ESITO OK

Restiamo in attesa delle controverifiche da parte della RDA.
grazie

**Comment by vigliottim** [comment]
@BasilicataCrashProgramFSE 

Chiediamo alla regione RDA di svolgere le opportune verifiche.
Grazie.

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,

L'errore "**WorkflowInstanceId non valido per richiesta getStatus**" non viene restituito dal Registry della Regione Basilicata. 
Potrebbe essere necessario rivalidare il documento prima di procedere con i test case.

Potete gentilmente indicarci lo uniqueId usato per i test case e l'orario indicativo dei test?
Grazie

**Comment by assistenza-fsevda** [comment]
buongiorno
questi gli uniqueID dei documenti creati e notificati verso la vs RDA, intorno orario 12:50 del 31/10:

2.16.840.1.113883.2.9.2.20.4.4^001.TRAKTEST.20241031125131401-0
2.16.840.1.113883.2.9.2.20.4.4^001.TRAKTEST.20241031125131401-1
2.16.840.1.113883.2.9.2.20.4.4^001.TRAKTEST.20241031125131401-2
2.16.840.1.113883.2.9.2.20.4.4^001.TRAKTEST.20241031125131401-3

saluti

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,

Tutti i 4 documenti risultano registrati correttamente sul nostro registry di test in questo ordine:
2.16.840.1.113883.2.9.2.20.4.4^001.TRAKTEST.20241031125131401-1 -->	2024-10-31 16:56:52.752
2.16.840.1.113883.2.9.2.20.4.4^001.TRAKTEST.20241031125131401-2	--> 2024-10-31 16:55:58.529
2.16.840.1.113883.2.9.2.20.4.4^001.TRAKTEST.20241031125131401-0	--> 2024-10-31 16:55:57.172
2.16.840.1.113883.2.9.2.20.4.4^001.TRAKTEST.20241031125131401-3	--> 2024-10-31 16:52:37.253

A disposizione
Grazie

**Comment by assistenza-fsevda** [comment]
Grazie per la controverifica. Visto il buon esito dell'evento di creazione chiudiamo l'issue.
