### ISSUE TITLE
Regione Valle d'Aosta - Pubblicazione verso Prov.Autonoma Bolzano:  "RDA generated an internal error."

### ISSUE THREAD

**Issue by assistenza-fsevda** [ministero-salute/it-fse-support#1110]
buongiorno
**abbiamo eseguito alcune pubblicazioni documenti con successo verso RDA 041. Data 18/10/24, intorno orario 11:38**

2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.7885f66d73^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.339a3ff2e3^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.568127e1dc^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.0d4ad122a0^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

**I servizi di sostituzione documento (RPCL) e cancellazione** invece restituiscono:

"codice": "500",
    "descrizione": "{\"traceID\":\"09fd1d2990c62538\",\"spanID\":\"09fd1d2990c62538\",\"type\":\"/msg/ini-error\",\"title\":\"Ini error.\",\"detail\":\"{\\\"traceID\\\":\\\"09fd1d2990c62538\\\",\\\"spanID\\\":\\\"a00467e1bd7fa3e0\\\",\\\"type\\\":\\\"/errors\\\",\\\"title\\\":\\\"Generic\\\",\\\"detail\\\":\\\"**RDA generated an internal** error.\\\",\\\"instance\\\":\\\"error/generic\\\"}\",\"status\":500,\"instance\":\"/msg/service-error/ini\"}",
    "esito": "KO",
    "tipo": "replace"

  "codice": "500",
    "descrizione": "{\"traceID\":\"4b83d8189bbbb2d9\",\"spanID\":\"4b83d8189bbbb2d9\",\"type\":\"/msg/ini-error\",\"title\":\"Ini error.\",\"detail\":\"{\\\"traceID\\\":\\\"4b83d8189bbbb2d9\\\",\\\"spanID\\\":\\\"d65b0aaa5239e527\\\",\\\"type\\\":\\\"/errors\\\",\\\"title\\\":\\\"Generic\\\",\\\"detail\\\":\\\"**RDA generated an internal** error.\\\",\\\"instance\\\":\\\"error/generic\\\"}\",\"status\":500,\"instance\":\"/msg/service-error/ini\"}",
    "esito": "KO",
    "tipo": "delete"

Restiamo in attesa di verifica e riscontro lato INI-RDA.

grazie

**Comment by assistenza-fsevda** [comment]
buon pomeriggio
abbiamo eseguito poco fa come RDE 020 nuova iterazione sui 4 servizi verso RDA 041 con esito KO complessivo.
Di seguito gli errori ricevuti verificando lo status su wid:

2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.7f19c702ef^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.b9f43d27b8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId


  "httpResponseCode": 500,
  "httpResponse": "{\"traceID\":\"3fcb1eb432eefe43\",\"spanID\":\"3fcb1eb432eefe43\",\"type\":\"/msg/generic-error\",\"title\":\"Errore generico.\",\"detail\":\"Errore generico\",\"status\":500,\"instance\":\"\"}"

  "httpResponseCode": 502,
  "httpResponse": "{\"type\":\"https://govway.org/handling-errors/502/InvalidResponse.html\",\"title\":\"InvalidResponse\",\"status\":502,\"detail\":\"Invalid response received from the API Implementation\",\"govway_id\":\"dfa01d0d-9610-11ef-a4d1-005056ae54fa\"}"

Restiamo in attesa di un riscontro dalla RDA
grazie

**Comment by SonnyMate** [comment]
Buongiorno,
Questi due non sono generati dalla nostra regione:
"httpResponseCode": 500,
"httpResponse": "{"traceID":"3fcb1eb432eefe43","spanID":"3fcb1eb432eefe43","type":"/msg/generic-error","title":"Errore generico.","detail":"Errore generico","status":500,"instance":""}"

"httpResponseCode": 502,
"httpResponse": "{"type":"[https://govway.org/handling-errors/502/InvalidResponse.html\",\"title\":\"InvalidResponse\",\"status\":502,\"detail\":\"Invalid](https://govway.org/handling-errors/502/InvalidResponse.html%5C%22,%5C%22title%5C%22:%5C%22InvalidResponse%5C%22,%5C%22status%5C%22:502,%5C%22detail%5C%22:%5C%22Invalid) response received from the API Implementation","govway_id":"dfa01d0d-9610-11ef-a4d1-005056ae54fa"}" @vigliottim chiedo di verificare sul gateway

Per le altre due verifichiamo

**Comment by assistenza-fsevda** [comment]
Buongiorno @ngaraventa,
abbiamo appena rieseguito una sessione di test e gli esiti sono stati positivi. Le operazioni di create, replace e delete hanno tutte stato "SUCCESS".
Vi riporto i relativi WII nel caso in cui vogliate fare delle controverifiche

```
Create (4 documenti) 
- 2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.74133ccdea^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
- 2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.c0e99189ea^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
- 2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.7a3bad44fe^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
- 2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.f04419f682^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
```

```
Replace
- 2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.74590f9960^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
```

```
Delete
- 03898931d29e57eb90ec8e9eea79ed71488ce62ff349816976f1e66f1afd63e4.b0e011c82c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
```

Per le operazioni di metadata update aspetteremo le future implementazioni della ITI-57

Grazie per l'aiuto.

**Comment by LucaRogledi** [comment]
Buongiorno @assistenza-fsevda @ngaraventa @SonnyMate,
Ringraziamo per il feedback e procediamo con la chiusura della presente issue.
Grazie
