### ISSUE TITLE
Regione Valle d'Aosta - Pubblicazione verso Regione Liguria: Errore Invalid time format

### ISSUE THREAD

**Issue by assistenza-fsevda** [ministero-salute/it-fse-support#1111]
Buongiorno,
nei vari tentativi di pubblicazione sul CF CQTDLT66H01Z356V di Regione Liguria abbiamo ottenuto saltuariamente degli errori _Invalid time format_
Al momento abbiamo riscontrato l'errore in fase di Create e di Update.

Esempio di errore in fase di create nell'event "SEND_TO_NI":
```
{
    "traceID": "d45262743d38d47b",
    "spanID": "2f594d1b052a03d4",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-10-18T12:10:59.996+02:00",
            "eventStatus": "SUCCESS",
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "020",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.462dfb5c1b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "cadef45cca388426",
            "issuer": "integrity:S1#020#020VALDAOSTATEST",
            "expiringDate": "2025-10-18T12:11:00.003+02:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-10-18T12:11:00.806+02:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.20.4.4^001.TRAKTEST.20241018121053738-3",
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "CON",
            "organizzazione": "020",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.462dfb5c1b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "184ddbb80bada39c",
            "issuer": "integrity:S1#020#020VALDAOSTATEST",
            "expiringDate": "2025-10-18T12:11:00.814+02:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-10-18T12:11:02.803+02:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:Invalid time format: 20241018121100039CODE CONTEXT:Internal Error",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.462dfb5c1b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-10-18T12:11:02.813+02:00"
        }
    ]
}
```
Esempio di errore in update:
```
{
	"traceID": "bb1efd986408bee3",
	"spanID": "171d8e88f4f4ade2",
	"type": "/errors",
	"title": "Generic",
	"detail": "it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:Invalid time format: 20241018124938483CODE CONTEXT:Internal Error",
	"instance": "error/generic"
}
```

Si segnala che altre pubblicazioni hanno invece dato esito "SUCCESS" senza nessun problema.

Esempio di WII per creazione OK:
2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.0d549465c3^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

Esempio di WII per update OK:
1ad6405b3711dfec240456754c111b3a79b2b3a36787f785d86b95b887ceb276.084213a6de^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

Sarebbe possibile avere una verifica in merito agli errori segnalati?
Grazie anticipatamente per l'aiuto.

**Comment by izamberlan** [comment]
Il tentativo non risulta nei nostri log, chiedo @vigliottim se può verificare che non sia un errore direttamente tornato da INI.

**Comment by izamberlan** [comment]
Faccio comunque notare che in https://profiles.ihe.net/ITI/TF/Volume3/ch-4.2.html#4.2.3.1.7 la regexp del tipo dati DTM non include i millisecondi.

**Comment by izamberlan** [comment]
A nuova verifica: il problema dipende dal nostro parser che, nel rispetto di quanto al messaggio precedente, sul DTM si ferma alla precisione del secondo e restituisce errore su precisioni maggiori; in questo caso il problema è su serviceStartTime e serviceStopTime (dataInizioPrestazione e dataFinePrestazione)

**Comment by assistenza-fsevda** [comment]
Buongiorno @izamberlan,
grazie mille per il riscontro e le verifiche fatte. Procediamo ad effettuare una fix alla procedura di invio così da fermarci ai secondi senza inserire i millisecondi.
Non appena abbiamo sistemato il tutto procediamo con dei nuovi invii e riportiamo gli esiti.
Grazie ancora per l'aiuto.

**Comment by assistenza-fsevda** [comment]
Abbiamo corretto la procedura e confermo che adesso gli esiti sono stati tutti positivi.
Ringrazio ancora @izamberlan per l'aiuto e procedo con la chiusura dell'issue.
Buon lavoro.
