### ISSUE TITLE
Crash Program (fase2) - Aggiornamento metadati, Sostituzione, Cancellazione da FVG verso Bolzano - RDA generated an internal error

### ISSUE THREAD

**Issue by ChiaraCeccottiFVG** [ministero-salute/it-fse-support#1114]
Buongiorno,
eseguendo i test del Crash Program di fase2 otteniamo un errore "RDA generated an internal error" per gli scenari di 
- Aggiornamento Metadati
- Sostituzione
- Cancellazione
dalla regione FVG verso la Provincia Autonoma di Bolzano.
Il documento è un Patient Summary.
Di seguito riportiamo i dettagli per chiedervi cortesemente se potete aiutarci a capire il problema.

AGGIORNAMENTO METADATI:
L'errore riscontrato è il seguente:
```
{
    "traceID": "57919eb8347af43f",
    "spanID": "0def79c16fa0d5db",
    "type": "/errors",
    "title": "Generic",
    "status": 500,
    "detail": "RDA generated an internal error.",
    "instance": "error/generic",
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}
```
SOSTITUZIONE (REPLACE):
```
{
    "traceID": "ed602c0b20a88583",
    "spanID": "ed602c0b20a88583",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "status": 500,
    "detail": "{\"traceID\":\"ed602c0b20a88583\",\"spanID\":\"b56e48e52a57a594\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"RDA generated an internal error.\",\"instance\":\"error/generic\"}",
    "instance": "/msg/service-error/ini",
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}
```
CANCELLAZIONE:
```
{
    "traceID": "152e96c615c22d0b",
    "spanID": "152e96c615c22d0b",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "status": 500,
    "detail": "{\"traceID\":\"152e96c615c22d0b\",\"spanID\":\"8e863530efc33e11\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"RDA generated an internal error.\",\"instance\":\"error/generic\"}",
    "instance": "/msg/service-error/ini",
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}
```
Ringraziando anticipatamente per la collaborazione rimaniamo a disposizione e auguriamo un buon pomeriggio.
Per comodità provo a taggare (non so se correttamente) il referente github @carlo.stefanini@siag.it per conoscenza.

**Comment by vigliottim** [comment]
Buon pomeriggio,
chiediamo gentilmente alla regione di riferimento di svolgere le opportune verifiche.
Restiamo a disposizione per ulteriore supporto.
Grazie.

**Comment by SonnyMate** [comment]
Buongiorno, l'aggiornamento metadati è sospeso fino alla distribuzione su INI della ITI-57

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
La ringrazio.
Per completezza, segnalo solo che il problema si verifica anche su sostituzione (replace) e cancellazione.
Buona giornata.

**Comment by ngaraventa** [comment]
Buongiorno,
l'errore è dovuto alla verifica dell'issuer nell'asserzione che ora è stato configurato.
potreste cortesemente riprovare?

Grazie.

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
ringrazio molto per la risposta.
Dopo il vostro intervento confermo che la sostituzione e la cancellazione vengono eseguite con successo.
Rimarrebbe l'aggiornamento metadati che restituisce questo errore:
```
{
    "traceID": "712835c09b02e0cd",
    "spanID": "7167a2349a4942a7",
    "type": "/errors",
    "title": "Generic",
    "status": 500,
    "detail": "it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:oasis:names:tc:ebxmlregrep:ErrorSeverityType:ErrorERROR_CODE:XDSDuplicateUniqueIdInRegistryCODE CONTEXT:Duplicated uniqueId (uniqueId - hash - repositoryId)",
    "instance": "error/generic",
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}
```
Vista però la ITI-57 chiedo se dobbiamo comunque indagare il caso o meno. 
Eventualmente, se va comunque verificato, chiederei un aiuto per comprendere da cosa possa essere dovuto l'errore.
Come transazioni eseguiamo: validazione di un documento, pubblicazione con ID doc nuovo/univoco, generiamo i token per l'aggiornamento, chiamiamo la sostituzione dei metadati passando l'id del doc e impostando un P99. 

Ringrazio e auguro una buona giornata.

**Comment by ngaraventa** [comment]
Buongiorno, per approfondire l'aggiornamento metadati si dovrà attendere la distribuzione su INI della ITI-57.

Grazie
