### ISSUE TITLE
Crash Program (fase2) - Creazione da FVG verso Regione BASILICATA - Error 9000

### ISSUE THREAD

**Issue by ChiaraCeccottiFVG** [ministero-salute/it-fse-support#1116]
Buongiorno,
eseguendo una Pubblicazione verso la regione Basilicata di un Patient Summary otteniamo il seguente errore:
```
{
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-10-18T14:20:20.949+02:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 9000",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.6f741c46fa145e57ec5478f266d45af88b0749801bfd79ced438a3004d5a43dd.1600df4f62^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-10-18T14:20:20.957+02:00"
        }
```
Vi chiediamo cortesemente una verifica per aiutarci a capire il problema.
Per comodità taggo @BasilicataCrashProgramFSE per conoscenza. 
Rimaniamo a disposizione e ringraziamo anticipatamente.
Buon pomeriggio

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno, 
abbiamo riprovato oggi e la creazione, la sostituzione e la cancellazione vanno a buon fine.
L'aggiornamento metadati invece fallisce con questo errore:
{
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "status": 502,
    "detail": "Invalid response received from the API Implementation",
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException",
    "govway_id": "37738855-9508-11ef-808a-005056ae7395"
} 
Ringrazio e auguro una buona giornata.

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,

Chiediamo gentilmente di riprovare.
Grazie

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
abbiamo rieseguito un test di ciascun scenario con successo.
Ringraziamo per la collaborazione.

**Comment by vigliottim** [comment]
Grazie per il gentile feedback.
Procediamo alla chiusura della presente issue.
