### ISSUE TITLE
Regione Valle d'Aosta - Pubblicazione verso Regione Puglia: "RDA generated an internal error"

### ISSUE THREAD

**Issue by assistenza-fsevda** [ministero-salute/it-fse-support#1117]
Buongiorno,
in fase di pubblicazione di un documento per il CF FSEPGL01E41A145J di Regione Puglia nell'evento "SEND_TO_INI" otteniamo l'errore "RDA generated an internal error".
Ci servirebbe supporto per capire l'origine del problema e provvedere alla risoluzione dello stesso. Per comodità aggiungo il tag del referente di Regione Puglia @lninnova

Di seguito un esempio di pubblicazione in errore:

```
{
	"traceID": "f4f7689b5882cc10",
	"spanID": "0a0d92951c3f9860",
	"transactionData": [
		{
			"eventType": "VALIDATION",
			"eventDate": "2024-10-18T15:03:25.914+02:00",
			"eventStatus": "SUCCESS",
			"subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"organizzazione": "020",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.8127daad01^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "e4ceba1df5e254c6",
			"issuer": "integrity:S1#020#020VALDAOSTATEST",
			"expiringDate": "2025-10-18T15:03:25.922+02:00"
		},
		{
			"eventType": "PUBLICATION",
			"eventDate": "2024-10-18T15:03:26.765+02:00",
			"eventStatus": "SUCCESS",
			"identificativoDocumento": "2.16.840.1.113883.2.9.2.20.4.4^001.TRAKTEST.20241018150320624-2",
			"subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"tipoAttivita": "CON",
			"organizzazione": "020",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.8127daad01^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "cce095884237c8f1",
			"issuer": "integrity:S1#020#020VALDAOSTATEST",
			"expiringDate": "2025-10-18T15:03:26.774+02:00"
		},
		{
			"eventType": "SEND_TO_INI",
			"eventDate": "2024-10-18T15:03:48.080+02:00",
			"eventStatus": "BLOCKING_ERROR",
			"message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.8127daad01^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"expiringDate": "2025-10-18T15:03:48.087+02:00"
		}
	]
}
```

Grazie anticipatamente.

**Comment by vigliottim** [comment]
Buon pomeriggio,
chiediamo gentilmente alla regione di riferimento di svolgere le opportune verifiche.
Restiamo a disposizione per ulteriore supporto.
Grazie.

**Comment by lninnova** [comment]
Buongiorno, la Puglia ha restituito l'errore R56 (Wrong format data of display name for DocumentEntry.typeCode)
Nella request di comunicazione metadati è infatti presente un displayName non previsto da Affinity Domain.

`<ns2:Classification classificationScheme="urn:uuid:f0306f51-975f-434e-a61c-c59651d33983"
				   classifiedObject="Document1"
				   id="IdTypeCode"
				   nodeRepresentation="11488-4"
				   objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification">
  <ns2:Slot name="codingScheme">
	 <ns2:ValueList>
		<ns2:Value>2.16.840.1.113883.6.1</ns2:Value>
	 </ns2:ValueList>
  </ns2:Slot>
  <ns2:Name>
	 <ns2:LocalizedString charset="UTF-8" value="Nota di consulto" xml:lang="en-US"/>
  </ns2:Name>
</ns2:Classification>
`

Resto a disposizione per ulteriori verifiche.

**Comment by GiuseppeMaiulli** [comment]
Buongiorno,

approfitto di questa issue aperta da VdA per segnalare che anche da Liguria verso Puglia abbiamo ricevuto lo stesso errore sulla pubblicazione sul CF FSEPGL01E41A145J.

Riporto di seguito il log chiedendovi la cortesia di verificare anche questa transazione.

{
    "traceID": "c552b312f94aafa3",
    "spanID": "f88efd7d96e0879c",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-10-25T14:45:33.969+02:00",
            "eventStatus": "SUCCESS",
            "subject": "MRLGPP92E22C589Q^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "070",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.70.4.4.5861903e2bcba35dd431903753d8304b61ca56199ae81fde5bcf6d0f4db7f599.8b81963512^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "4e3f560ee65df84a",
            "issuer": "integrity:S1#070#REGIONELIGURIATEST",
            "expiringDate": "2025-10-25T14:45:33.980+02:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-10-25T14:45:54.631+02:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.70.4.4^RAD.16076724109.1",
            "subject": "MRLGPP92E22C589Q^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "CON",
            "organizzazione": "070",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.70.4.4.5861903e2bcba35dd431903753d8304b61ca56199ae81fde5bcf6d0f4db7f599.8b81963512^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "412cbfb2c1ae149b",
            "issuer": "integrity:S1#070#REGIONELIGURIATEST",
            "expiringDate": "2025-10-25T14:45:54.740+02:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-10-25T14:45:58.146+02:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.70.4.4.5861903e2bcba35dd431903753d8304b61ca56199ae81fde5bcf6d0f4db7f599.8b81963512^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-10-25T14:45:58.163+02:00"
        }
    ]
}

Grazie

**Comment by assistenza-fsevda** [comment]
Buongiorno,
se può essere utile noi abbiamo ricondotto questa casistica all'issue #1147 in cui viene riportato che verrà informata AGID in merito al disallineamento tra Affinity Domain e HL7.

**Comment by assistenza-fsevda** [comment]
buongiorno
riproponiamo verso Regione PUGLIA l'anomalia in oggetto.
Su CF FSEPGL01E41A145J abbiamo reiterato in data 28/10 sequenza di Test sui servizi che hanno avuto il seguente esito:

-- CREATE, esito OK

-- UPDATE DOC --
  "codice": "500",
    "descrizione": "{\"status\":500}",
    "esito": "KO",
    "tipo": "update"

-- REPLACE DOC -- 
 "codice": "500",
    "descrizione": "{\"traceID\":\"d7ffe80db511ffb9\",\"spanID\":\"d7ffe80db511ffb9\",\"type\":\"/msg/ini-error\",\"title\":\"Ini error.\",\"detail\":\"{\\\"traceID\\\":\\\"d7ffe80db511ffb9\\\",\\\"spanID\\\":\\\"f8b726bdae3bc262\\\",\\\"type\\\":\\\"/errors\\\",\\\"title\\\":\\\"Generic\\\",\\\"detail\\\":\\\"\\\",\\\"instance\\\":\\\"error/generic\\\"}\",\"status\":500,\"instance\":\"/msg/service-error/ini\"}",
    "esito": "KO",
    "tipo": "replace"

-- DELETE --
"codice": "500",
    "descrizione": "{\"traceID\":\"a482e266192cf8ab\",\"spanID\":\"a482e266192cf8ab\",\"type\":\"/msg/ini-error\",\"title\":\"Ini error.\",\"detail\":\"{\\\"traceID\\\":\\\"a482e266192cf8ab\\\",\\\"spanID\\\":\\\"55a1a6805dd03095\\\",\\\"type\\\":\\\"/errors\\\",\\\"title\\\":\\\"Generic\\\",\\\"detail\\\":\\\"\\\",\\\"instance\\\":\\\"error/generic\\\"}\",\"status\":500,\"instance\":\"/msg/service-error/ini\"}",
    "esito": "KO",
    "tipo": "delete"

Nella verifica dello status su un WID di documento che ci risulta pubblicato (ma senza notifica da INI) otteniamo:

{\"eventType\":\"SEND_TO_INI\",\"eventDate\":\"2024-10-28T14:31:54.300+01:00\",\"eventStatus\":\"BLOCKING_ERROR\",\"message\":\"SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.\",\"workflowInstanceId\":\"2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.0fe5095867^^^^urn:ihe:iti:xdw:2013:workflowInstanceId\",\"expiringDate\":\"2025-10-28T14:31:54.376+01:00\"}]}"

Chiediamo controverifiche alla RDA.
grazie

**Comment by assistenza-fsevda** [comment]
buongiorno
chiediamo un riscontro a @lninnova (RDA puglia) sull'anomalia segnalata per poter rieseguire sessione di test.
grazie

**Comment by lninnova** [comment]
buongiorno @assistenza-fsevda abbiamo rilasciato la modifica in ambiente di test.
Fateci sapere se il problema persiste.
Grazie

**Comment by assistenza-fsevda** [comment]
Buon pomeriggio @lninnova, grazie per il riscontro.
Abbiamo rieseguito batteria di test su FSEPGL01E41A145J ma con riscontri negativi.

Questi i riferimenti a seguito delle CREATE (esito OK):

{"traceID":"6c6a4749c73f0ff4","spanID":"6c6a4749c73f0ff4","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.803c8a1b00^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

{"traceID":"508b7f96eaa82c9c","spanID":"508b7f96eaa82c9c","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.838a19db8d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

{"traceID":"2c1bc1099349cb76","spanID":"2c1bc1099349cb76","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.dd8f597609^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

{"traceID":"94f2dfa387eb44f3","spanID":"94f2dfa387eb44f3","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.ec1ff8d0d7^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

Verifica status OK, ma nessuna notifica da INI verso RDE 020.

Per gli altri servizi invece abbiamo i seguenti esiti:

------ UPDATE ---------

   "codice": "500",
    "descrizione": "{\"status\":500}",
    "esito": "KO",
    "tipo": "update"

------ REPLACE --------

"codice": "500",
    "descrizione": "{\"traceID\":\"991cdd6889571e31\",\"spanID\":\"6a953c10d5619978\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"\",\"instance\":\"error/generic\"}",
    "esito": "KO",
    "tipo": "replace"


------ DELETE ----------

    "codice": "500",
    "descrizione": "{\"traceID\":\"8a5aafeed205640d\",\"spanID\":\"2b84fe4076bc7a12\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"\",\"instance\":\"error/generic\"}",
    "esito": "KO",
    "tipo": "delete"

Restiamo in attesa di vostre controverifiche e a disposizione per successiva iterazione del test.
Saluti.

**Comment by lninnova** [comment]
Buongiorno, le ultime request di comunicazione metadati sono relative a RAD.
Anche in questo caso abbiamo restituito l'errore R56 (Wrong format data of display name for DocumentEntry.typeCode) poiché come nome mnemonico del typeCode è stato indicato il valore "Referto Radiologico", non previsto da Affinity Domain.
Per quanto riguarda i RSA, abbiamo rilasciato temporaneamente e verificato in ambiente di test una versione che accetta "Nota di consulto" tra i valori ammessi.
Prima di procedere ad ulteriori modifiche, è opportuno attendere l'evoluzione della issue #1147 .
@assistenza-fsevda ricevete lo stesso errore per altre tipologie documentali?

**Comment by assistenza-fsevda** [comment]
Buongiorno,
al momento abbiamo superato il problema utilizzando diverse tipologie documentali. Chiudiamo l'issue.

Grazie per il supporto fornito.
