### ISSUE TITLE
Status 400 "govway_id": "92da2499-8d59-11ef-a4d1-005056ae54fa"

### ISSUE THREAD

**Issue by NAMURSRL** [ministero-salute/it-fse-support#1118]
Buongiorno,
da pochi minuti ricevo un errore dall'apparato di frontiera in richiesta validazione 
Vi allego i dati:

Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im51bGwiLCJ4NWMiOlsiTUlJRmFqQ0NBMUtnQXdJQkFnSVVaNXdCZ1pteHZTY2FJOUk4K3VFbGxEYnROR1F3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TkRBMk1qQXhOakV3TUROYUZ3MHlOekEyTWpFeE5qRXdNREphTUdzeEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVJvd0dBWURWUVFEREJGVE1TTXhNVEVqVGtGTlZWSlRVa3hZV0RDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSjFPaU0vaDFxdEw0Z085YzJKWEZ1NWF1Z0lBWDJ4Mno3cmtQVkxJaGRaR2tUK3VSQnVKUy8zVmZ6M2I1RGx6NGp3OGREc051aWRNUDdyY1NNMmx0cTBCZ3JOS1pRa29hMlJoejBaMW9EVU5wQXpDaFFZOURMWmpLNWlwZjRUVlZFZXNzbGkzVE0reFE5eHpzbkJ2WDhvb3NXbVpvM3FXakREQ1hucElXTlZmaUpKR0ZTc000bUFKSzFuMTVCNmJQVUp4MzNrNTV4endCbm5hcjczbjlWQnBCRG5QZlh6T2RrTS9ZUGwzN0gvYW5qMUVrdlp6alpPNS9jWVluSTJWaGNvTjVZWFV6YjFSRk1ONXR2K0E1QTluaERpUCszSHd0cVdZTG8wb3Ewbi9nWDdNNHQwKzRiak9lRmFsNExQbXMyN0Uwc3FsQXNIb3Rqa0hESG5FWmZVQ0F3RUFBYU9DQVJnd2dnRVVNQjhHQTFVZEl3UVlNQmFBRkJZNXFSb0ZpYmNQTGJJMTdjSUptc1VEZ3lJL01CSUdBMVVkSUFRTE1Ba3dCd1lGSzB3ZEFRc3dnYTBHQTFVZEh3U0JwVENCb2pDQm42Q0JuS0NCbVlhQmxtaDBkSEJ6T2k4dlkyRnpiMmRsYVhOMmFXd3VjMjluWldrdWFYUXZaV3BpWTJFdmNIVmliR2xqZDJWaUwzZGxZbVJwYzNRdlkyVnlkR1JwYzNRL1kyMWtQV055YkNacGMzTjFaWEk5UTA0bE0wUkRRU3ROYVc1cGMzUmxjbThyWkdWc2JHRXJVMkZzZFhSbEsxUmxjM1FsTWtOUEpUTkVUV2x1YVhOMFpYSnZLMlJsYkd4aEsxTmhiSFYwWlNVeVEwTWxNMFJKVkRBZEJnTlZIUTRFRmdRVXlLU3NHdUU2Wi9Id3RqYndlVitsdlYyY05sY3dEZ1lEVlIwUEFRSC9CQVFEQWdaQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRRE5hOXVWak1EelczT3FEL2VmSWRQbnlraXRvOEV1c3R4MENZVEtoZ2xYOTBkb3NKeDltVGhyYTUwZGJ0M0lGNDYra3hXSUczMzRQQzN3aWp1TzJrTm9yejF4QzlrbWpUZHQrekJhWjVxMFcwQVdLano0aUlYYmJETjVOUFhRUHRsU0lreVZYZlZNZGcrUjJrMW1rOGRJRWdMZTZQMWtxZlRVWkJiZmlqS1YyZFJXYzFhcDFLN0hySkxLOWZvY1JHY2tuYXpzQmdHanBsYjVVaVg2eUNBUW5icEFiTmtuRHVIQWx2UEFXbFQzL214Y1B2M0gwUXdMcEhBYnM4VGtmM1JWQVhrOGtmNFVrM3N2cUxTRGM0UFFIdnRUeG01RmRXeTN4QmN0M3hCTUF5NStpcEpQZWNnVWdPbnFGUUZPTUZmVFZoMHBlUFNjanBDSCtQQ1Q2NVZuTi9HakJyR1E2UHo0Sm40M2pyd3hzdm1LWnc3YWZqbldad3pkK25OemI0UlR4ZXc4dXVRc2RMUjBZNEt1bVZXWkw2NGhYenpUSW5zaVJERTdUeEhvclZOdW9OZ1dvTmRzQ21JTFpxNkNhNDBLNVRpSHNmMjgxWjVZRVh1OElMV2Y2TkZXNEYwcHFMUEdJRklsZW8yVldZNHEwNitVeDFoVWREaitrV2VDTG42dGxya3FNWXk1d3A5cnBtTkNhTUhjTE5oa2o1Y0Z0VjQ1NnU4bU1lWU9wWUQ4SWdTUFl2QjA2N0k1Yi9HRExhU2FGak9ZdHBNdXVNK3pBaWhGQzdPVVJvcHRpMU1sU2t6Um1iWHg0WlR0MmgxVytzNXZ3NklOT1p2UkoyWXF4NlJHUDRadDM2M1Bjb3F0WENqc09MV2lpZ0o0clRPd1BoaUxKMHZrN09HMlBnPT0iXX0.eyJpc3MiOiJhdXRoOlMxIzExMSNOQU1VUlNSTFhYIiwiaWF0IjoxNzI5MjYwOTE2LCJleHAiOjE3MjkyNjQ1MTYsImp0aSI6ImE1YjAxOWU2LWIyYTAtNDVhMC1hYzNjLTQyNDRkM2ZiZDFjMCIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInN1YiI6IlBST1ZBWDAwWDAwWDAwMFleXl5cdTAwMjYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjJcdTAwMjZJU08ifQ.Ay2gSrQ7p1eyD9ySa_ssd-MPT7EB6634IwKka4RGS26Wp-9-_3NEZZ6H990bXJ3rn1CZuNsk5013XMoAA6QdZRKgsGsMfR3-_lJDtrSygSC9bMIEUS3-Mo1RLmN6XgBxStyE0BrpSS0A-Y6NWGr0GyHTYkONaEgN5rO-JosDykgCc0qxPwZi9sjoNR3rMDI3iLsVIqSx3S56n5ylnBxNbZrKP__NynIHgwDmlTFo69j8hBX6r7PaM7W3rfyqu3aBJVxAzyaKPZEqKRUOtta2-FwlyIrdgUNDJCtUH5361Nyqrrvyrz2cDYptiZpKD-FTnUsxEmHjzmf5-vwbLT12lA
  Accept: application/json
  FSE-JWT-Signature: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im51bGwiLCJ4NWMiOlsiTUlJRmFqQ0NBMUtnQXdJQkFnSVVaNXdCZ1pteHZTY2FJOUk4K3VFbGxEYnROR1F3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TkRBMk1qQXhOakV3TUROYUZ3MHlOekEyTWpFeE5qRXdNREphTUdzeEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVJvd0dBWURWUVFEREJGVE1TTXhNVEVqVGtGTlZWSlRVa3hZV0RDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSjFPaU0vaDFxdEw0Z085YzJKWEZ1NWF1Z0lBWDJ4Mno3cmtQVkxJaGRaR2tUK3VSQnVKUy8zVmZ6M2I1RGx6NGp3OGREc051aWRNUDdyY1NNMmx0cTBCZ3JOS1pRa29hMlJoejBaMW9EVU5wQXpDaFFZOURMWmpLNWlwZjRUVlZFZXNzbGkzVE0reFE5eHpzbkJ2WDhvb3NXbVpvM3FXakREQ1hucElXTlZmaUpKR0ZTc000bUFKSzFuMTVCNmJQVUp4MzNrNTV4endCbm5hcjczbjlWQnBCRG5QZlh6T2RrTS9ZUGwzN0gvYW5qMUVrdlp6alpPNS9jWVluSTJWaGNvTjVZWFV6YjFSRk1ONXR2K0E1QTluaERpUCszSHd0cVdZTG8wb3Ewbi9nWDdNNHQwKzRiak9lRmFsNExQbXMyN0Uwc3FsQXNIb3Rqa0hESG5FWmZVQ0F3RUFBYU9DQVJnd2dnRVVNQjhHQTFVZEl3UVlNQmFBRkJZNXFSb0ZpYmNQTGJJMTdjSUptc1VEZ3lJL01CSUdBMVVkSUFRTE1Ba3dCd1lGSzB3ZEFRc3dnYTBHQTFVZEh3U0JwVENCb2pDQm42Q0JuS0NCbVlhQmxtaDBkSEJ6T2k4dlkyRnpiMmRsYVhOMmFXd3VjMjluWldrdWFYUXZaV3BpWTJFdmNIVmliR2xqZDJWaUwzZGxZbVJwYzNRdlkyVnlkR1JwYzNRL1kyMWtQV055YkNacGMzTjFaWEk5UTA0bE0wUkRRU3ROYVc1cGMzUmxjbThyWkdWc2JHRXJVMkZzZFhSbEsxUmxjM1FsTWtOUEpUTkVUV2x1YVhOMFpYSnZLMlJsYkd4aEsxTmhiSFYwWlNVeVEwTWxNMFJKVkRBZEJnTlZIUTRFRmdRVXlLU3NHdUU2Wi9Id3RqYndlVitsdlYyY05sY3dEZ1lEVlIwUEFRSC9CQVFEQWdaQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRRE5hOXVWak1EelczT3FEL2VmSWRQbnlraXRvOEV1c3R4MENZVEtoZ2xYOTBkb3NKeDltVGhyYTUwZGJ0M0lGNDYra3hXSUczMzRQQzN3aWp1TzJrTm9yejF4QzlrbWpUZHQrekJhWjVxMFcwQVdLano0aUlYYmJETjVOUFhRUHRsU0lreVZYZlZNZGcrUjJrMW1rOGRJRWdMZTZQMWtxZlRVWkJiZmlqS1YyZFJXYzFhcDFLN0hySkxLOWZvY1JHY2tuYXpzQmdHanBsYjVVaVg2eUNBUW5icEFiTmtuRHVIQWx2UEFXbFQzL214Y1B2M0gwUXdMcEhBYnM4VGtmM1JWQVhrOGtmNFVrM3N2cUxTRGM0UFFIdnRUeG01RmRXeTN4QmN0M3hCTUF5NStpcEpQZWNnVWdPbnFGUUZPTUZmVFZoMHBlUFNjanBDSCtQQ1Q2NVZuTi9HakJyR1E2UHo0Sm40M2pyd3hzdm1LWnc3YWZqbldad3pkK25OemI0UlR4ZXc4dXVRc2RMUjBZNEt1bVZXWkw2NGhYenpUSW5zaVJERTdUeEhvclZOdW9OZ1dvTmRzQ21JTFpxNkNhNDBLNVRpSHNmMjgxWjVZRVh1OElMV2Y2TkZXNEYwcHFMUEdJRklsZW8yVldZNHEwNitVeDFoVWREaitrV2VDTG42dGxya3FNWXk1d3A5cnBtTkNhTUhjTE5oa2o1Y0Z0VjQ1NnU4bU1lWU9wWUQ4SWdTUFl2QjA2N0k1Yi9HRExhU2FGak9ZdHBNdXVNK3pBaWhGQzdPVVJvcHRpMU1sU2t6Um1iWHg0WlR0MmgxVytzNXZ3NklOT1p2UkoyWXF4NlJHUDRadDM2M1Bjb3F0WENqc09MV2lpZ0o0clRPd1BoaUxKMHZrN09HMlBnPT0iXX0.eyJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExI05BTVVSU1JMWFgiLCJpYXQiOjE3MjkyNjA5MTcsImV4cCI6MTcyOTI2NDUxNywianRpIjoiM2RjNjU5YjItNWVhNy00NTgxLWFkZTgtY2FmOTk0ZjYxNTJmIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwic3ViIjoiUFJPVkFYMDBYMDBYMDAwWV5eXlx1MDAyNjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMlx1MDAyNklTTyIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMTIwIiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb25lIExhemlvIiwibG9jYWxpdHkiOiJOQU1VUiBzcmxeXl5eXlx1MDAyNjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjEuM1x1MDAyNklTT15eXl4xMjAyMDIwMTYwMDAiLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwZXJzb25faWQiOiJWTkNMU043MlQwNEg1MDFXXl5eXHUwMDI2Mi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yXHUwMDI2SVNPIiwicGF0aWVudF9jb25zZW50IjoidHJ1ZSIsInB1cnBvc2Vfb2ZfdXNlIjoiVFJFQVRNRU5UIiwicmVzb3VyY2VfaGw3X3R5cGUiOiIoXHUwMDI3MTE1MDItMl5eMi4xNi44NDAuMS4xMTM4ODMuNi4xXHUwMDI3KSIsImFjdGlvbl9pZCI6IkNSRUFURSIsImF0dGFjaG1lbnRfaGFzaCI6ImI5NDE5YWQ4Y2UzZjhkODE3NmEwZTdlZDNkMDFlYmZmMTQ2Yjg4ZDQwMGI1YzcyNDE0Y2ZjYWFmMTllYWMwYTYiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiR0xQWCIsInN1YmplY3RfYXBwbGljYXRpb25fdmVuZG9yIjoiTmFtdXIgc3JsIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiMS4wIn0.VV6DA7B8lcxWnJ5H0VeuMHFif3l6ArIRceIa2AXGRIZ3VbYPh4SZd0D7QrGrHqaUYwSp_sv9_untMrfFcVriWiOMO0cqG5TntJttNRdUoDm6gm-iWPXaZIkHZzEqnhztevDXzqD5-U2KVZlrgjPpRuKVlf_vwCauZ_qe1Ro-RJ4FkKtCU-vJTG__-tCsvb1HQCsPT5dtpC6j-GJ_ozMILUg0iWDpZNKimDOXTWLbw0e-yz9eVwNWO2sJn-gKEjYd6fu8DaJSt5YodlhwL2amyrodpD3tu3EQovypT_RJvscVCDIq0fRzCTrLYdyD6l7IFZ11k8VEYBSkkZtqC3vQHQ
  Content-Type: multipart/form-data; boundary="41374c06-dbf3-471b-bccf-3ba1f1284668"
  Content-Length: 316219

Grazie

**Comment by vigliottim** [comment]
Buonasera,
la informiamo che stiamo registrando dei temporanei disservizi.
La invitiamo a monitorare il canale Slack dedicato per avere aggiornamenti.
Grazie.

**Comment by vigliottim** [comment]
Buonasera,
potrebbe cortesemente riprovare ad effettuare nuovamente la chiamata?
Grazie.

**Comment by vigliottim** [comment]
Grazie per il suo gentile feedback.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
