### ISSUE TITLE
Domanda sui codici prestazioni RAD

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#1119]
Buongiorno,
in un CDA di test, nella sezione **ESAME_ESEGUITO**, tag **entry->act->code**, sono stati inseriti questi valori, che sono risultati corretti sia per l'accreditamento che adesso per i nostri test interni.
<code code="87.3" codeSystem="2.16.840.1.113883.6.103" codeSystemName="ICD-9-CM" displayName="Soft tissue x-ray of thorax" />
Ma nella documentazione relativa, leggo:
![image](https://github.com/user-attachments/assets/7d8f0a8e-cfca-4c67-9a3c-39e2bf8eb256)
**Per la codifica possono essere utilizzati i sistemi di codifica (LOINC, ICD9-CM)** e possono essere inserite eventuali altre codifiche derivanti da Nomenclatura Ministeriale e/o Regionale mediante l’elemento translation, ma non mi interessa.
Il codice 87.3 utilizzato non mi risulta in nessun elenco ammesso, LOINC o  ICD9-CM.
Se l'accoppiata code/codeSystemName deve essere coerente, in questo caso 87.3 DEVE essere un codice ICD-9-CM, quindi non capisco cosa mi stia sfuggendo.
Potreste chiarirmi le idee, cortesemente?
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, potrebbe cortesemente allegare il cda2 utilizzato?
Ha indicato i valori usati ma non risultano leggibili. 
Grazie.

**Comment by infoserviceonline** [comment]
[cdarad.zip](https://github.com/user-attachments/files/17456886/cdarad.zip)
Certamente.

**Comment by infoserviceonline** [comment]
Grazie per il riscontro, quindi io dovrò usare i codici di assistenza ospedaliera (ho scaricato il csv) anche per le altre tipologie documentali, in questo caso RAD. Ho capito bene?

**Comment by vigliottim** [comment]
Esatto.

> Grazie per il riscontro, quindi io dovrò usare i codici di assistenza ospedaliera (ho scaricato il csv) anche per le altre tipologie documentali, in questo caso RAD. Ho capito bene?

**Comment by infoserviceonline** [comment]
Grazie mille, chiudo il ticket
