### ISSUE TITLE
TokenAuthenticationFailed non comprensibile

### ISSUE THREAD

**Issue by gianlucasenocb** [ministero-salute/it-fse-support#1120]
Sto sviluppando per CB Sistemi i servizi per Insiel e FSE Friuli per la gestione dei referti: in ambiente transitorio tutti i servizi hanno funzionato correttamente ora, in ambiente gateway, stiamo provado ad inviare un referto di laboratorio ma ci torna errore token. 
Premetto che la validazione per lo stesso documento ha funzionato correttamente.
 Riporto messaggio di errore, header e payload di entrambi i token. Se dovesse servire, fornirò anche la signature

_**Errore**_
{"type":"https://govway.org/handling-errors/401/TokenAuthenticationFailed.html","title":"TokenAuthenticationFailed","status":401,"detail":"Invalid token","classError":"it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException","govway_id":"bda716d6-8fa3-11ef-a4d1-005056ae54fa"}

_**Token "authorization"**_

_header_
{
  "alg": "RS256",
  "typ": "JWT",
  "x5c": [
    "MIIFKzCCAxOgAwIBAgIUC73xc3uQxmp/Kn4sUObAhh9POyAwDQYJKoZIhvcNAQEL\rBQAwVzEnMCUGA1UEAwweQ0EgTWluaXN0ZXJvIGRlbGxhIFNhbHV0ZSBUZXN0MR8w\rHQYDVQQKDBZNaW5pc3Rlcm8gZGVsbGEgU2FsdXRlMQswCQYDVQQGEwJJVDAeFw0y\rMzAzMTYyMjAxMzZaFw0yNjAzMTYyMjAxMzVaMGkxCzAJBgNVBAYTAklUMR8wHQYD\rVQQKDBZNaW5pc3Rlcm8gZGVsbGEgU2FsdXRlMR0wGwYDVQRhDBRDRjpJVC0xMTFD\rQlNJU1RFTUlYWDEaMBgGA1UEAwwRUzEjMTExQ0JTSVNURU1JWFgwggEiMA0GCSqG\rSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDHUGjlzLzRrc/P37hi3XkuAAV8sYWzE7RI\rZTLuDTSqto8XlXsf73JXDxfg+zanibBhDYt3nfB5C8VL6EvWcFTcJF/rM3UOKtkE\r3UC0hrt3tK4avQ2Cm132BynkLIQFb8Ef8xQzEPPW4moXu6pHlDox5+BxCKls4LJM\rTNiShAS2vrFsQMaSLsh5k7V72Ba6pyiYXuV5FSRz/3Y8+jYuO+ETszttim3dMuFS\r+mKORqotQU+Oz1A9HeY3Jx/AgQq4/KlrDO+YZyGVMTdwU8mPE70+KFUUHSgm6qTb\rf0xjasNgHawjpsFDYkPOnZ8uDfC3ghUDFNVFKMdySK61waBEx/WXAgMBAAGjgdww\rgdkwHwYDVR0jBBgwFoAUFjmpGgWJtw8tsjXtwgmaxQODIj8wEgYDVR0gBAswCTAH\rBgUrTB0BCzBzBgNVHR8EbDBqMGigZqBkhmJsZGFwOi8vY2Fkcy5maW5hbnplLml0\rL0NOPUNBJTIwTWluaXN0ZXJvJTIwZGVsbGElMjBTYWx1dGUlMjBUZXN0LE89TWlu\raXN0ZXJvJTIwZGVsbGElMjBTYWx1dGUsQz1JVDAdBgNVHQ4EFgQUu2NhOEttkIAc\rsYKRQTBtpoh5SmowDgYDVR0PAQH/BAQDAgZAMA0GCSqGSIb3DQEBCwUAA4ICAQB/\reuM3UPHwz7/WlOIexhtuLDjgR9YyLka6cncT3cUu28u7bHdq0f3ceKEY19zukahu\roAFVOF5QRg7nbLDjVzvZZjLYCuSZV8Z6asO+loF+8iFoGINC3GinwWb0XvZhxDLt\ryE6zqQKMyEaBvUqpv/+IP393xOzER1bI5bWGbaruWsRO9voei/N2sYMMY67FDjGY\rJjpF1Isg3ECbG2dfZCysSFbQsTol7EZPULP424nxE45TrTrFF0G8oV6jsQznGUM2\rJ4WEWxQFu4bnCRkt4l+Y7/+qFXVNiFjhPRRnPHULiJcfCvVuCM7TbwPVkUO0y0Yj\r5P8qnZWlqeyXbS4rixfVSN0XqSrwd6P4/z6C8OuxL0Bwf0X8OCWp4nGyIpZZmwub\rEl8e98GTEVt8LGFz4wc3TIoNJA60vntmx0HDl+W30yHAn3PQePCfzs42NQIWKPKc\r3QKbnR7OKA43kms2P38+LtPIn70yuwjtFCu8yUkCZY8EqrA79gjFzPokhR41rfFb\rR3+QLPsIEQpO7EJVYqvV2ueomMtqNhhpk3ZWQ8Jm3wayFVUX4ogqwwyF0CjmtDEt\rqI3bvseIX5IHGki3UGORwQSqhJZbH6xULTJGxAD5zlP3Uoqwye7DF2FkTQNRTtvR\rwO69OYd+ANZl+R0xkw0rqaVgveZ13anFQC1XdSKPuA=="
  ]
}
_Payload_
{
  "sub": "RSSMRA22A01A399Z^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "jti": "36b53efc-42bd-4022-9c35-7af039ba0c99",
  "exp": 1729513735,
  "iss": "auth:S1#111CBSISTEMIXX",
  "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
  "iat": 1729512835
}

_**Token "fse-jwt-signature"**_
_Header_
{
  "alg": "RS256",
  "typ": "JWT",
  "x5c": [
    "MIIFKzCCAxOgAwIBAgIUC73xc3uQxmp/Kn4sUObAhh9POyAwDQYJKoZIhvcNAQEL\rBQAwVzEnMCUGA1UEAwweQ0EgTWluaXN0ZXJvIGRlbGxhIFNhbHV0ZSBUZXN0MR8w\rHQYDVQQKDBZNaW5pc3Rlcm8gZGVsbGEgU2FsdXRlMQswCQYDVQQGEwJJVDAeFw0y\rMzAzMTYyMjAxMzZaFw0yNjAzMTYyMjAxMzVaMGkxCzAJBgNVBAYTAklUMR8wHQYD\rVQQKDBZNaW5pc3Rlcm8gZGVsbGEgU2FsdXRlMR0wGwYDVQRhDBRDRjpJVC0xMTFD\rQlNJU1RFTUlYWDEaMBgGA1UEAwwRUzEjMTExQ0JTSVNURU1JWFgwggEiMA0GCSqG\rSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDHUGjlzLzRrc/P37hi3XkuAAV8sYWzE7RI\rZTLuDTSqto8XlXsf73JXDxfg+zanibBhDYt3nfB5C8VL6EvWcFTcJF/rM3UOKtkE\r3UC0hrt3tK4avQ2Cm132BynkLIQFb8Ef8xQzEPPW4moXu6pHlDox5+BxCKls4LJM\rTNiShAS2vrFsQMaSLsh5k7V72Ba6pyiYXuV5FSRz/3Y8+jYuO+ETszttim3dMuFS\r+mKORqotQU+Oz1A9HeY3Jx/AgQq4/KlrDO+YZyGVMTdwU8mPE70+KFUUHSgm6qTb\rf0xjasNgHawjpsFDYkPOnZ8uDfC3ghUDFNVFKMdySK61waBEx/WXAgMBAAGjgdww\rgdkwHwYDVR0jBBgwFoAUFjmpGgWJtw8tsjXtwgmaxQODIj8wEgYDVR0gBAswCTAH\rBgUrTB0BCzBzBgNVHR8EbDBqMGigZqBkhmJsZGFwOi8vY2Fkcy5maW5hbnplLml0\rL0NOPUNBJTIwTWluaXN0ZXJvJTIwZGVsbGElMjBTYWx1dGUlMjBUZXN0LE89TWlu\raXN0ZXJvJTIwZGVsbGElMjBTYWx1dGUsQz1JVDAdBgNVHQ4EFgQUu2NhOEttkIAc\rsYKRQTBtpoh5SmowDgYDVR0PAQH/BAQDAgZAMA0GCSqGSIb3DQEBCwUAA4ICAQB/\reuM3UPHwz7/WlOIexhtuLDjgR9YyLka6cncT3cUu28u7bHdq0f3ceKEY19zukahu\roAFVOF5QRg7nbLDjVzvZZjLYCuSZV8Z6asO+loF+8iFoGINC3GinwWb0XvZhxDLt\ryE6zqQKMyEaBvUqpv/+IP393xOzER1bI5bWGbaruWsRO9voei/N2sYMMY67FDjGY\rJjpF1Isg3ECbG2dfZCysSFbQsTol7EZPULP424nxE45TrTrFF0G8oV6jsQznGUM2\rJ4WEWxQFu4bnCRkt4l+Y7/+qFXVNiFjhPRRnPHULiJcfCvVuCM7TbwPVkUO0y0Yj\r5P8qnZWlqeyXbS4rixfVSN0XqSrwd6P4/z6C8OuxL0Bwf0X8OCWp4nGyIpZZmwub\rEl8e98GTEVt8LGFz4wc3TIoNJA60vntmx0HDl+W30yHAn3PQePCfzs42NQIWKPKc\r3QKbnR7OKA43kms2P38+LtPIn70yuwjtFCu8yUkCZY8EqrA79gjFzPokhR41rfFb\rR3+QLPsIEQpO7EJVYqvV2ueomMtqNhhpk3ZWQ8Jm3wayFVUX4ogqwwyF0CjmtDEt\rqI3bvseIX5IHGki3UGORwQSqhJZbH6xULTJGxAD5zlP3Uoqwye7DF2FkTQNRTtvR\rwO69OYd+ANZl+R0xkw0rqaVgveZ13anFQC1XdSKPuA=="
  ]
}
_Payload_
{
  "sub": "RSSMRA22A01A399Z^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "jti": "b583e0d1-5a36-4dbc-aa2a-a6b57440bcd8",
  "exp": 1729513735,
  "iss": "integrity:S1#111CBSISTEMIXX",
  "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
  "iat": 1729512835,
  "subject_organization_id": "060",
  "subject_organization": "Regione Friuli Venezia Giulia",
  "locality": "206",
  "subject_role": "DRS",
  "person_id": "PRVNSL72B68L101R^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "purpose_of_use": "TREATMENT",
  "action_id": "CREATE",
  "attachment_hash": "BFF04B52357F1307B80C70E8AB809B297CB3B1C3828EF7AB7E00E47BBC542E0C",
  "subject_application_id": "StudioLAB",
  "subject_application_vendor": "CB Sistemi",
  "subject_application_version": "3.3.0.0",
  "resource_hl7_type": "('11502-2^^2.16.840.1.113883.6.1')",
  "patient_consent": true
}

**Comment by vigliottim** [comment]
Buonasera,
dalle analisi svolte sui log della chiamata indicata, è emerso un errore nel campo _x5c_:

![image](https://github.com/user-attachments/assets/ed6ca957-34a3-4355-b638-f4b12b2b18c9)

**Comment by vigliottim** [comment]
Buonasera,
dalle analisi svolte sui log della chiamata indicata, è emerso un errore nel campo _x5c_ contenuto nei JWT:

![image](https://github.com/user-attachments/assets/ed6ca957-34a3-4355-b638-f4b12b2b18c9)

![image](https://github.com/user-attachments/assets/26b4294b-cb04-4267-8365-1eb36da99d36)

Effettuando l'encoding dei token tramite il tool online [jwt.io](jwt.io), il token _FSE-JWT-Signature_ non risulta valido:

<img width="222" alt="image" src="https://github.com/user-attachments/assets/44413114-5d14-482a-ba1a-96ab0570c1c4">

In particolare, il claim _x5c_ presenta molti carriage return (\r) che potrebbero pregiudicare la corretta decodifica:

<img width="179" alt="image" src="https://github.com/user-attachments/assets/1365ed6a-260e-4c5c-bdf2-f0f5082cddcf">

La invitiamo a riprovare dopo aver rigenerato e validato i token.
Rimaniamo a disposizione qualora l'errore dovesse ripresentarsi.

**Comment by gianlucasenocb** [comment]
Abbiamo corretto la problematica e questo errore è stato passato ma ora viene generato il seguente errore

{
	"traceID": "3fff04d4e84d125e",
	"spanID": "3fff04d4e84d125e",
	"type": "/msg/jwt-validation",
	"title": "Campo token JWT non valido.",
	"status": 403,
	"detail": "Il campo Locality non è valorizzato correttamente",
	"instance": "/jwt-mandatory-field-malformed",
	"classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}

l'header è il seguente

{
  "alg": "RS256",
  "typ": "JWT",
  "x5c": [
    "MIIFKzCCAxOgAwIBAgIUC73xc3uQxmp/Kn4sUObAhh9POyAwDQYJKoZIhvcNAQELBQAwVzEnMCUGA1UEAwweQ0EgTWluaXN0ZXJvIGRlbGxhIFNhbHV0ZSBUZXN0MR8wHQYDVQQKDBZNaW5pc3Rlcm8gZGVsbGEgU2FsdXRlMQswCQYDVQQGEwJJVDAeFw0yMzAzMTYyMjAxMzZaFw0yNjAzMTYyMjAxMzVaMGkxCzAJBgNVBAYTAklUMR8wHQYDVQQKDBZNaW5pc3Rlcm8gZGVsbGEgU2FsdXRlMR0wGwYDVQRhDBRDRjpJVC0xMTFDQlNJU1RFTUlYWDEaMBgGA1UEAwwRUzEjMTExQ0JTSVNURU1JWFgwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDHUGjlzLzRrc/P37hi3XkuAAV8sYWzE7RIZTLuDTSqto8XlXsf73JXDxfg+zanibBhDYt3nfB5C8VL6EvWcFTcJF/rM3UOKtkE3UC0hrt3tK4avQ2Cm132BynkLIQFb8Ef8xQzEPPW4moXu6pHlDox5+BxCKls4LJMTNiShAS2vrFsQMaSLsh5k7V72Ba6pyiYXuV5FSRz/3Y8+jYuO+ETszttim3dMuFS+mKORqotQU+Oz1A9HeY3Jx/AgQq4/KlrDO+YZyGVMTdwU8mPE70+KFUUHSgm6qTbf0xjasNgHawjpsFDYkPOnZ8uDfC3ghUDFNVFKMdySK61waBEx/WXAgMBAAGjgdwwgdkwHwYDVR0jBBgwFoAUFjmpGgWJtw8tsjXtwgmaxQODIj8wEgYDVR0gBAswCTAHBgUrTB0BCzBzBgNVHR8EbDBqMGigZqBkhmJsZGFwOi8vY2Fkcy5maW5hbnplLml0L0NOPUNBJTIwTWluaXN0ZXJvJTIwZGVsbGElMjBTYWx1dGUlMjBUZXN0LE89TWluaXN0ZXJvJTIwZGVsbGElMjBTYWx1dGUsQz1JVDAdBgNVHQ4EFgQUu2NhOEttkIAcsYKRQTBtpoh5SmowDgYDVR0PAQH/BAQDAgZAMA0GCSqGSIb3DQEBCwUAA4ICAQB/euM3UPHwz7/WlOIexhtuLDjgR9YyLka6cncT3cUu28u7bHdq0f3ceKEY19zukahuoAFVOF5QRg7nbLDjVzvZZjLYCuSZV8Z6asO+loF+8iFoGINC3GinwWb0XvZhxDLtyE6zqQKMyEaBvUqpv/+IP393xOzER1bI5bWGbaruWsRO9voei/N2sYMMY67FDjGYJjpF1Isg3ECbG2dfZCysSFbQsTol7EZPULP424nxE45TrTrFF0G8oV6jsQznGUM2J4WEWxQFu4bnCRkt4l+Y7/+qFXVNiFjhPRRnPHULiJcfCvVuCM7TbwPVkUO0y0Yj5P8qnZWlqeyXbS4rixfVSN0XqSrwd6P4/z6C8OuxL0Bwf0X8OCWp4nGyIpZZmwubEl8e98GTEVt8LGFz4wc3TIoNJA60vntmx0HDl+W30yHAn3PQePCfzs42NQIWKPKc3QKbnR7OKA43kms2P38+LtPIn70yuwjtFCu8yUkCZY8EqrA79gjFzPokhR41rfFbR3+QLPsIEQpO7EJVYqvV2ueomMtqNhhpk3ZWQ8Jm3wayFVUX4ogqwwyF0CjmtDEtqI3bvseIX5IHGki3UGORwQSqhJZbH6xULTJGxAD5zlP3Uoqwye7DF2FkTQNRTtvRwO69OYd+ANZl+R0xkw0rqaVgveZ13anFQC1XdSKPuA=="
  ]
}

Payload

{
  "sub": "RSSMRA22A01A399Z^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "jti": "6ac6c16a-d23b-45f0-8c93-b7953b545f9a",
  "exp": 1729521505,
  "iss": "integrity:S1#111CBSISTEMIXX",
  "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
  "iat": 1729520605,
  "subject_organization_id": "060",
  "subject_organization": "Regione Friuli Venezia Giulia",
  "locality": "206",
  "subject_role": "DRS",
  "person_id": "PRVNSL72B68L101R^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "purpose_of_use": "TREATMENT",
  "action_id": "CREATE",
  "attachment_hash": "BFF04B52357F1307B80C70E8AB809B297CB3B1C3828EF7AB7E00E47BBC542E0C",
  "subject_application_id": "StudioLAB",
  "subject_application_vendor": "CB Sistemi",
  "subject_application_version": "3.3.0.0",
  "resource_hl7_type": "('11502-2^^2.16.840.1.113883.6.1')",
  "patient_consent": true
}

Abbiamo sempre inserito il codice del laboratorio ed ha sempre funzionato, dobbiamo cambiarlo? Cosa dobbiamo inserire?

Grazie

**Comment by vigliottim** [comment]
Buonasera,
per valorizzare correttamente il campo _locality_, che è stato recentemente oggetto di un aggiornamento, la invitiamo a consultare la documentazione al link: [campi-contenuti-nei-jwt](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt):

![image](https://github.com/user-attachments/assets/37efd556-987a-4a9c-8631-dd7ad349c852)

Rimaniamo a disposizione per ulteriori chiarimenti.
