### ISSUE TITLE
Errore servizio sostituzione (http status 400)

### ISSUE THREAD

**Issue by ppalmerini** [ministero-salute/it-fse-support#1121]
Buonasera,
stiamo ricevendo un http status 400 a fronte di tentativi di sostituire un documento precedentemente validato e pubblicato correttamente, qui la response dal servizio di creazione
{
    "spanID": "f9ec787d296a4982",
    "traceID": "f9ec787d296a4982",
    "warning": "",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.5721bf93cd748cc87970b5f6ed060c83e2a7d980256096ab332a03bc16d146e8.3f8e277e01^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

per la sostituizione, la validazione del documento dà risposta:
{
    "traceID": "558e96b522bd6930",
    "spanID": "558e96b522bd6930",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.5721bf93cd748cc87970b5f6ed060c83e2a7d980256096ab332a03bc16d146e8.6bb6ed4f6b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

mentre la risposta dal servizio https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.50.4.4^123458
ritorna un http status 400
data invio: 2024-10-21 14:47:10.292

jwt utilizzati per la sostituzione:
auth
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGY1RDQ0ExbWdBd0lCQWdJVUlhZlpoeHMyMmx3NjZNTV9QUGRxNUFJS2tXUXdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlOREE0TWpBeE5UUXlNRE5hRncweU56QTRNakV4TlRReU1ESmFNSEl4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVI4d0hRWURWUVJoREJaRFJqcEpWQzFRVWs5V1FWZ3dNRmd3TUZnd01EQlpNU0V3SHdZRFZRUUREQmhUTVNNd05UQWpVa1ZIU1U5T1JWWkZUa1ZVVDFSRlUxUXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEV2p3cG1UOVVVV21lR3FVMi1HN1ByZFdTbEdObXFxeVlkQ19rWHVKeGllUS1oVkNPa3cwNWZ0Z0Jfelkxd3RBTkNaVDU2RFFhVElkc29RRWJ2RjdIMmx2RzZ4YlNkNEFJUDMteUtyVzFiQnVsY3J5bUlOd0RDVmI2bm5LaFdDektLTy1pNTYzb0ZqMVhDN29nNFl5WDZmM0IyRTJycVNSbUVjbU8tMDVKYkRDZEg2c1FTam1fdUw5WlRUSUhKVWg1TlNEMUxnMkVOZF8zTFlubEtvY1ppR1Ita1IxZzgwV1NCSkNjR1ZPSDBkVFVVTHZtT3hYXzE3N1U1MHd1U0lvb3RrbnFnRjJFUnBZaGx4Y0FCaUVRekVYSUw5NHpLYW1aUnZoSUMwRW9BWUl2VVNFNFRhQ2k1cTY0MmZNVWYyTGZzaVRMRXUwd1ZRZmxiQlA2Q20zWE5BZ01CQUFHamdnRVlNSUlCRkRBZkJnTlZIU01FR0RBV2dCUVdPYWthQlltM0R5MnlOZTNDQ1pyRkE0TWlQekFTQmdOVkhTQUVDekFKTUFjR0JTdE1IUUVMTUlHdEJnTlZIUjhFZ2FVd2dhSXdnWi1nZ1p5Z2dabUdnWlpvZEhSd2N6b3ZMMk5oYzI5blpXbHpkbWxzTG5OdloyVnBMbWwwTDJWcVltTmhMM0IxWW14cFkzZGxZaTkzWldKa2FYTjBMMk5sY25Sa2FYTjBQMk50WkQxamNtd21hWE56ZFdWeVBVTk9KVE5FUTBFclRXbHVhWE4wWlhKdksyUmxiR3hoSzFOaGJIVjBaU3RVWlhOMEpUSkRUeVV6UkUxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVWxNa05ESlRORVNWUXdIUVlEVlIwT0JCWUVGSjNkVmpzR3dBdEpIbGRwX3BPT2ZVSll4QzdmTUE0R0ExVWREd0VCX3dRRUF3SUdRREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBeUdOdUtLQVlfbnNDUkxNX0tsMlpYSmN6dXJic3R4LUItMjFMcjhjNDdROGpscVdSZ0dxb1llbTRkS1k2dGd2bTdrNkhLeUxqWUVSVVh4QmVXUWZCRUczZG5YZzNvZGpVOV83TzJJTjdJZXBCZk0tbDhzZk9KWU95NDRtYVJXVjlfNldPQUxWSl96cWNEbVZaS1o2czRFdkxHc3dCRERGT2V1WmVsRURUTEQ2OFhQTHJObTVEU1F0RzNSeklpVkwxNFgtOElHR3I5V19aaGExaDVYYy1FLTRQOGVkOUtJMVJKb3FESDhrbzQ1VjV1c0RfVUF5cHZkU1cyUU9MQjZWdlNyUkhrX3cwRnlKLTl4U0RQUEpWX1ctZmlxRlI2aTczMzVlNzNnTm5VakdUZWVtVU1vODU1THRZZkFyNFozdk0wU2JqRmlhZGdqYUJ4X2NEZnZ0WUNLcV8yUjVYMWNSSlhLeTdwT1d5dk1CbmNBb3ZlNkNZNjVJX3BMeFVkbGsxOF9Gb05aMkxIOEpoM254cjJwLUFYc2dSRUgxMXhRU2RNWFRLOXVnYldxM1o3ek40aUFfUTdMRXVucmpBdFV2dFhHUllPN3BFR2R5Y2pUdEJkYkxPcHpWVjNCT2ExaFRRcVlKUWhwXzMzYTEtOVcxVlZJMUJYb0hBQm1ST0Qtc1hpVldFQzBGaEdpVWZhT1M1QWwwUHFLUFZScGU5Mk5tcjZkUWNyM0lYd0g3VnBPZEdocG1JcEsxeFYxYURNeGFtN3NEODRkczhxdlE3OHNaSWF1MFIyYThuOHJUSUpnRUFuTXA4Y2dEek14WktDa0dyb3V4WUJOdEhKb3RPQjN6Tl8wbkRBWXhSQjBaT0E3bURnb1NnaExhQ0xvTWRqakxuMUhRYUlLVmE5YWsiXX0.eyJqdGkiOiI5NjZBNTkzOS04RkFBLTExRUYtOTRBMC0wMDUwNTZCNjNGMEEiLCJpc3MiOiJhdXRoOlMxIzA1MCNSRUdJT05FVkVORVRPVEVTVCIsInN1YiI6IkdSTE1TTTYwUjMxRjc3MFleXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyIsImV4cCI6MTcyOTUzMjgzMCwiaWF0IjoxNzI5NTE0ODMwLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEifQ.Rizad5K1WWepPluqhrDr1Ofs3abrVo5l3IuemkSAOVo10Y5ryY2nWmImbaky9VU2RIwKcaQcC-9nbPkn_HfpZy7jUUJj7OpPutjxAtrQ9JE5HVVB8Yey5Xp7yY3tAr3xuK_Qi8Z055Qu7s_sa4pra0UW-DL9RynbfW6MUpE9PG0YXEnUai-YSMHfryZwv712_rvo61nQB2r93hlov4fAQEFPQQga-ctIZyERXqIr_8-TNnf6OovGinMuQBgYNIRO3lJ5pkikrmjzKT9-oNpDj--acPtlDz0WT-wYzs-ZrqvZnTN-1p2bavRLUlG5k13FwAwibzP9RbxysRWkEVZnbw

sign
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGY1RDQ0ExbWdBd0lCQWdJVUlhZlpoeHMyMmx3NjZNTV9QUGRxNUFJS2tXUXdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlOREE0TWpBeE5UUXlNRE5hRncweU56QTRNakV4TlRReU1ESmFNSEl4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVI4d0hRWURWUVJoREJaRFJqcEpWQzFRVWs5V1FWZ3dNRmd3TUZnd01EQlpNU0V3SHdZRFZRUUREQmhUTVNNd05UQWpVa1ZIU1U5T1JWWkZUa1ZVVDFSRlUxUXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEV2p3cG1UOVVVV21lR3FVMi1HN1ByZFdTbEdObXFxeVlkQ19rWHVKeGllUS1oVkNPa3cwNWZ0Z0Jfelkxd3RBTkNaVDU2RFFhVElkc29RRWJ2RjdIMmx2RzZ4YlNkNEFJUDMteUtyVzFiQnVsY3J5bUlOd0RDVmI2bm5LaFdDektLTy1pNTYzb0ZqMVhDN29nNFl5WDZmM0IyRTJycVNSbUVjbU8tMDVKYkRDZEg2c1FTam1fdUw5WlRUSUhKVWg1TlNEMUxnMkVOZF8zTFlubEtvY1ppR1Ita1IxZzgwV1NCSkNjR1ZPSDBkVFVVTHZtT3hYXzE3N1U1MHd1U0lvb3RrbnFnRjJFUnBZaGx4Y0FCaUVRekVYSUw5NHpLYW1aUnZoSUMwRW9BWUl2VVNFNFRhQ2k1cTY0MmZNVWYyTGZzaVRMRXUwd1ZRZmxiQlA2Q20zWE5BZ01CQUFHamdnRVlNSUlCRkRBZkJnTlZIU01FR0RBV2dCUVdPYWthQlltM0R5MnlOZTNDQ1pyRkE0TWlQekFTQmdOVkhTQUVDekFKTUFjR0JTdE1IUUVMTUlHdEJnTlZIUjhFZ2FVd2dhSXdnWi1nZ1p5Z2dabUdnWlpvZEhSd2N6b3ZMMk5oYzI5blpXbHpkbWxzTG5OdloyVnBMbWwwTDJWcVltTmhMM0IxWW14cFkzZGxZaTkzWldKa2FYTjBMMk5sY25Sa2FYTjBQMk50WkQxamNtd21hWE56ZFdWeVBVTk9KVE5FUTBFclRXbHVhWE4wWlhKdksyUmxiR3hoSzFOaGJIVjBaU3RVWlhOMEpUSkRUeVV6UkUxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVWxNa05ESlRORVNWUXdIUVlEVlIwT0JCWUVGSjNkVmpzR3dBdEpIbGRwX3BPT2ZVSll4QzdmTUE0R0ExVWREd0VCX3dRRUF3SUdRREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBeUdOdUtLQVlfbnNDUkxNX0tsMlpYSmN6dXJic3R4LUItMjFMcjhjNDdROGpscVdSZ0dxb1llbTRkS1k2dGd2bTdrNkhLeUxqWUVSVVh4QmVXUWZCRUczZG5YZzNvZGpVOV83TzJJTjdJZXBCZk0tbDhzZk9KWU95NDRtYVJXVjlfNldPQUxWSl96cWNEbVZaS1o2czRFdkxHc3dCRERGT2V1WmVsRURUTEQ2OFhQTHJObTVEU1F0RzNSeklpVkwxNFgtOElHR3I5V19aaGExaDVYYy1FLTRQOGVkOUtJMVJKb3FESDhrbzQ1VjV1c0RfVUF5cHZkU1cyUU9MQjZWdlNyUkhrX3cwRnlKLTl4U0RQUEpWX1ctZmlxRlI2aTczMzVlNzNnTm5VakdUZWVtVU1vODU1THRZZkFyNFozdk0wU2JqRmlhZGdqYUJ4X2NEZnZ0WUNLcV8yUjVYMWNSSlhLeTdwT1d5dk1CbmNBb3ZlNkNZNjVJX3BMeFVkbGsxOF9Gb05aMkxIOEpoM254cjJwLUFYc2dSRUgxMXhRU2RNWFRLOXVnYldxM1o3ek40aUFfUTdMRXVucmpBdFV2dFhHUllPN3BFR2R5Y2pUdEJkYkxPcHpWVjNCT2ExaFRRcVlKUWhwXzMzYTEtOVcxVlZJMUJYb0hBQm1ST0Qtc1hpVldFQzBGaEdpVWZhT1M1QWwwUHFLUFZScGU5Mk5tcjZkUWNyM0lYd0g3VnBPZEdocG1JcEsxeFYxYURNeGFtN3NEODRkczhxdlE3OHNaSWF1MFIyYThuOHJUSUpnRUFuTXA4Y2dEek14WktDa0dyb3V4WUJOdEhKb3RPQjN6Tl8wbkRBWXhSQjBaT0E3bURnb1NnaExhQ0xvTWRqakxuMUhRYUlLVmE5YWsiXX0.eyJzdWIiOiJHUkxNU002MFIzMUY3NzBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBUFIiLCJwdXJwb3NlX29mX3VzZSI6IlVQREFURSIsImlzcyI6ImludGVncml0eTpTMSMwNTAjUkVHSU9ORVZFTkVUT1RFU1QiLCJsb2NhbGl0eSI6IlVMU1MgMiBNYXJjYSBUcmV2aWdpYW5hXl5eXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMS4zJklTT15eXl4wNTA1MDIiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlcnNpb24iOiIwNi4xOCIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBWZW5ldG8iLCJzdWJqZWN0X29yZ2FuaXphdGlvbl9pZCI6IjA1MCIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInBhdGllbnRfY29uc2VudCI6dHJ1ZSwiYWN0aW9uX2lkIjoiVVBEQVRFIiwicmVzb3VyY2VfaGw3X3R5cGUiOiIoJzYwNTkxLTVeXjIuMTYuODQwLjEuMTEzODgzLjYuMScpIiwic3ViamVjdF9hcHBsaWNhdGlvbl9pZCI6Ik1FRElDTzIwMDAiLCJleHAiOjE3Mjk1MzI4MzAsInN1YmplY3RfYXBwbGljYXRpb25fdmVuZG9yIjoiTWVkaWF0ZWMgSW5mb3JtYXRpY2EgUy5yLmwuIiwiaWF0IjoxNzI5NTE0ODMwLCJqdGkiOiI5NjZCMUE1OS04RkFBLTExRUYtOTRBMC0wMDUwNTZCNjNGMEEiLCJwZXJzb25faWQiOiJTUVRQUlY4MEE1NEk3OTlUXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdHRhY2htZW50X2hhc2giOiIyMTQ1YjA2NThiYWEzYjNhODhhMzJkODYzZDI0NTFiZDJhYTA1ZjJiOWFlZTgyNTdhODg0OTQ5ZTQxYmIxZDgwIn0.Lyc3id4sHcuM6yEUkZ8J2MYZGUy7I0Cn3Bp7-0cPUVrsIR5ODJAbSKNQYslNj2sabOsmFuZufJ7Xhl-c1H_J1Z5LSy6vrtUL1IgmWsbQlVRSfjGtG1lc3FT0c-CT6ILVzqwn-MPC7ijTNcesP1NzRwVoQ0PqMP_BT8QaiXwjiBrY8K1WxnggT1sI8dkBe0fo1yBSdaEYAo3P4N_okbzskqkUd1kjerKgUMOVbwPKHNfm30MqN4SiL1ry89UvO1KECyXaZPkFI94yR0zyB3pZ6Vm_3bsEzLzbFaRMwNPP7RVpUfUGWPOiNV42cQYbNGooJOCiOjksezLpfgYS5j7Ubg

rimaniamo in attesa di un vostro gentile riscontro, grazie

**Comment by vigliottim** [comment]
Buon pomeriggio,
L'url da lei riportato per chiamare il [servizio di sostituzione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#61-request) non risulta corretto.
La invitiamo a riprovare effettuando l'url encode dell'_identificativoDocUpdate_:


https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.50.4.4%5E123458

Restiamo a disposizione in caso l'errore non dovesse risolversi.
Grazie.

**Comment by ppalmerini** [comment]
grazie, abbiamo apportato la modifica suggerita, ora l'errore è strutturato ma ancora non risolutivo:
{"traceID":"a1a4ede29b504cf3","spanID":"7ec433cf3fff09cc","type":"/errors","title":"Generic","detail":"RDA generated an internal error.","instance":"error/generic"}
vi chiediamo assistenza
grazie

**Comment by LucaRogledi** [comment]
Buongiorno, 
Potrebbe gentilmente riprovare la chiamata utilizzando il seguente valore PZNTTF20T30L219R per il codice fiscale del paziente e darci un riscontro in caso l'errore si ripresenti?
Grazie

**Comment by ppalmerini** [comment]
Buongiorno,
abbiamo riprovato seguendo la vostra indicazione e usando il cf che ci avete indicato.
Il servizio di sostituzione ci restituisce questo errore:

{
    "detail": "{\"timestamp\":\"2024-10-22T10:39:26.114+00:00\",\"status\":500,\"error\":\"Internal Server Error\",\"path\":\"/v1/get-reference/2.16.840.1.113883.2.9.2.50.4.4%5E000011\"}",
    "instance": "/msg/service-error/ini",
    "spanID": "613e1c6c402961e8",
    "status": 500,
    "title": "Ini error.",
    "traceID": "613e1c6c402961e8",
    "type": "/msg/ini-error"
}

indagando sullo status del documento precedentemente validato e pubblicato (che si voleva andare a sostituire), osserviamo che nella risposta, l'eventType SEND_TO_INI riporta un soapfault (di seguito il json integrale).
Ci chiediamo se le due cose siano correlate

L'endpoint per lo status:
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/status/2.16.840.1.113883.2.9.2.50.4.4.5721bf93cd748cc87970b5f6ed060c83e2a7d980256096ab332a03bc16d146e8.5d70aece49%5E%5E%5E%5Eurn%3Aihe%3Aiti%3Axdw%3A2013%3AworkflowInstanceId


La risposta ottenuta
{
    "traceID": "663211fbe7581e61",
    "spanID": "ea8d91490b1ef8c2",
    "transactionData": [
        {
            "eventType": "VALIDATION_FOR_PUBLICATION",
            "eventDate": "2024-10-22T12:33:42.903+02:00",
            "eventStatus": "SUCCESS",
            "subject": "GRLMSM60R31F770Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "050",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.5721bf93cd748cc87970b5f6ed060c83e2a7d980256096ab332a03bc16d146e8.5d70aece49^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "5da95dcf791b07d3",
            "issuer": "integrity:S1#050#REGIONEVENETOTEST",
            "expiringDate": "2025-10-22T12:33:42.912+02:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-10-22T12:33:43.028+02:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.50.4.4^000011",
            "subject": "GRLMSM60R31F770Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "OBS",
            "organizzazione": "050",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.5721bf93cd748cc87970b5f6ed060c83e2a7d980256096ab332a03bc16d146e8.5d70aece49^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "5da95dcf791b07d3",
            "issuer": "integrity:S1#050#REGIONEVENETOTEST",
            "expiringDate": "2025-10-22T12:33:43.036+02:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-10-22T12:33:43.617+02:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "500 : \"{\"traceID\":\"cb3e283ce0ba6997\",\"spanID\":\"cb3e283ce0ba6997\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: Missing upload consent Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}\"",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.5721bf93cd748cc87970b5f6ed060c83e2a7d980256096ab332a03bc16d146e8.5d70aece49^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-10-22T12:33:43.762+02:00"
        }
    ]
}


In attesa di un vostro gentile riscontro, ringraaziamo

**Comment by vigliottim** [comment]
Buonasera,
il codice fiscale utilizzato presenta un errore sui consensi a causa di un problema presente nel file contenente i CF condivisi tra le regioni.
Verrà aggiornato a breve e la informeremo non appena sarà fatto.
Grazie.

**Comment by ppalmerini** [comment]
Buongiorno,
abbiamo provato nuovamente ad inviare una richiesta di sostituzione utilizzando il CF condiviso ma riceviamo ancora un errore di questo tipo:

{"traceID":"7a8b432ff6cd348c","spanID":"7a8b432ff6cd348c","type":"/msg/ini-error","title":"Ini error.","detail":"{\"traceID\":\"7a8b432ff6cd348c\",\"spanID\":\"b5daeb7f441f3d3b\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"\",\"instance\":\"error/generic\"}","status":500,"instance":"/msg/service-error/ini"}

Potete fornirci qualche delucidazione in merito?
Grazie

**Comment by LucaRogledi** [comment]
Buonasera, 
Sembrerebbe un errore generato dalla RDA, pertanto chiediamo gentilmente se può effettuare una verifica interna con la regione di riferimento.
Restiamo a disposizione per ulteriore supporto, grazie

**Comment by ppalmerini** [comment]
Ringrazio per il feedback; chiediamo gentilmente se potete fornirci maggiori dettagli sugli errori che vedete in modo da sottoporre la questione alla regione con maggiori dettagli su quanto riscontrato.
Restiamo in attesa di vostro gentile riscontro.

**Comment by vigliottim** [comment]
Buon pomeriggio,
la informiamo che su INI, in fase di recupero riferimenti, si vede che l'RDA (050) risponde con questo errore: 
"ERRORE #5002: Errore di ObjectScript: &lt;CLASS DOES NOT EXIST&gt;CSPDispatch+589^%SYS.cspServer *(No name)"
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
@ppalmerini 
Buonasera,
le chiediamo se ha effettuato le verifiche opportune e se ha bisogno di supporto.
Grazie.

**Comment by ppalmerini** [comment]
Buonasera,
stiamo ancora procedendo con le verifiche ma per non ridondare le richieste di assistenza chiedo di chiudere questo thread in quanto stiamo portando avanti la stessa problematica in questo issue https://github.com/ministero-salute/it-fse-support/issues/1170
grazie

**Comment by vigliottim** [comment]
Come da sua richiesta, chiudiamo la presente issue.
Grazie.
