### ISSUE TITLE
Crash Program - Aggiornamento Metadati da Piemonte verso Puglia: Errore 500

### ISSUE THREAD

**Issue by marco-volpe** [ministero-salute/it-fse-support#1122]
Buongiorno

in fase di aggiornamento metadati otteniamo il seguente problema

```json
{
  "status": "500"
}
```

La url invocata è la seguente

`
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.010.4.4%5E1729518844763/metadata
`

il workflowInstanceID di creazione è il seguente

`
2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.c93f75ac5f^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
`

Grazie, a disposizione

**Comment by vigliottim** [comment]
Buon pomeriggio,
invitiamo a svolgere le opportune verifiche con la regione di riferimento.
Grazie.

**Comment by lninnova** [comment]
Buongiorno, si tratta di un bug già noto che stiamo risolvendo.
Aggiorno tutti sulle evoluzioni.
Grazie

**Comment by vigliottim** [comment]
@lninnova
Buonasera,
chiediamo gentilmente se ci sono aggiornamenti.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno @lninnova,
le chiediamo cortesemente un riscontro.
Grazie.

**Comment by lninnova** [comment]
Buon pomeriggio, chiedo gentilmente di chiudere la issue in attesa del rilascio della ITI-57

**Comment by vigliottim** [comment]
Buonasera,
come da sua richiesta chiudiamo la issue in attesa del rilascio della ITI-57.
Grazie.
