### ISSUE TITLE
Risposta di errore a Regione Piemonte per pubblicazione

### ISSUE THREAD

**Issue by izamberlan** [ministero-salute/it-fse-support#1128]
Buongiorno,

guardando i log noto che restituiamo errore a Regione Piemonte per la pubblicazione. Ciò dipende dal fatto che riceviamo, come root del documento e come identificativo repository, dei valori che non soddisfano la regular expression degli oid; la parte che determina la regione, è inserita come "010", deve essere invece "10" (gli 0 non sono ammessi negli oid dopo il punto se non nel caso in cui siano l'unica cifra).
Esempio della root del documento come ora inviato:
2.16.840.1.113883.2.9.2.010.4.4
Esempio di come dovrebbe essere:
2.16.840.1.113883.2.9.2.10.4.4

Per quanto riguarda la parte comune degli oid del repository, attualmente ci arriva:
2.16.840.1.113883.2.9.2.010.4.5.[id_interno_repository]
Dovrebbe essere
2.16.840.1.113883.2.9.2.10.4.5,[id_interno_repository]

Faccio notare che nell'attuale implementazione (produzione via INI) le root corrispondono a quelle che passano i nostri test

grazie

**Comment by izamberlan** [comment]
Con la correzioen effettuata da Regione Piemonte, come riportato da @marco-volpe nella issue #1130 il problema è risolto.

**Comment by vigliottim** [comment]
Grazie per il gentile feedback.
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per altre richieste di supporto.
