### ISSUE TITLE
Regione Valle d'Aosta - Pubblicazione verso Regione Veneto

### ISSUE THREAD

**Issue by assistenza-fsevda** [ministero-salute/it-fse-support#1129]
Buongiorno,
nel tentativo di pubblicare un documento sul CF PZNTTF20T30L219R di Regione Veneto otteniamo un errore nell'evento "SEND_TO_INI" che riporta _"Missing upload consent"_
Effettuando delle verifiche tramite i servizi di INI sembrerebbe che il CF PZNTTF20T30L219R non abbia rilasciato il consenso all'alimentazione. È possibile procedere con il rilascio dei consensi? Non appena viene sistemata questa parte tentiamo nuovamente con le pubblicazioni.

Grazie per l'aiuto.

**Comment by assistenza-fsevda** [comment]
Buongiorno @vigliottim,
ricontrollando i casi di test eseguiti ci siamo accorti che il CF PZNTTF20T30L219R  assegnato a Regione Veneto nel file issuers.json è in realtà uno di nostri pazienti VdA. Probabilmente il disguido è dovuto al fatto che il file "DTD_FSE 2.0 Censimento_CF_CP2.0v01.xlsx" presente nello sharepoint si è disallineato durante qualche aggiornamento. Come si può vedere dallo screenshot appena qui sotto è stata erroneamente inserita una cella vuota sotto il CF di Regione Toscana che ha fatto spostare tutti i valori successivi verso il basso.

![image](https://github.com/user-attachments/assets/a6195840-99dc-43e1-996f-2e07f4b608e9)
Riuscite a correggere il file xlsx ed il file json?

Grazie per l'aiuto.

**Comment by pFonziSogei** [comment]
Buonasera,

per la regione Veneto abbiamo sostituito il CF "PZNTTF20T30L219R" con "SQTPRV80A54I799T".

Di seguito il link al file https://github.com/ministero-salute/it-fse-gtw-crash-program/blob/main/issuers.json

**Comment by assistenza-fsevda** [comment]
Buongiorno, 
grazie per il riscontro. La creazione adesso è andata a buon fine.
Chiudiamo l'issue.
Grazie ancora per l'aiuto.
