### ISSUE TITLE
Status 400: InvalidRequestContent

### ISSUE THREAD

**Issue by EbitFSE** [ministero-salute/it-fse-support#113]
Buonasera, 
ad una richiesta di validazione  otteniamo il seguent errore:
"Request content not conform to API specification: Validation error(s) :\nAn error occurred when getting the body content from type 'multipart/form-data; boundary=esa_e1f2f69f-50b2-41ee-99c2-b8d0870fb9c2'.\ncom.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value\n at [Source: (org.apache.commons.fileupload.MultipartStream$ItemInputStream); line: 1, column: 3] (code: 201)\n",

Questo l'id della chiamata: "govway_id" : "be9c554e-b136-11ed-adb9-005056ae54fa"

Potreste gentilmente indicarci la problematica riscontrata nella request multipart?
Grazie

**Comment by masciamariotti** [comment]
Buongiorno,
da una prima analisi abbiamo notato che forse sta inviando dei caratteri sporchi nella request:

_--esa_e1f2f69f-50b2-41ee-99c2-b8d0870fb9c2
 Content-Disposition: form-data; name="requestBody"**;**
 Content-Type: application/json; charset=UTF-8
{"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VALIDATION"}_

Provi a rimuovere il ";" dopo il requestBody e, se questo non dovesse risolvere, provi anche a rimuovere il charset.
Ci faccia sapere se il problema persiste.

**Comment by EbitFSE** [comment]
Grazie per la pronta risposta.
Ci sono state anche altre piccoli aggiustamenti da fare.
Riporto qui la soluzione che ha dato esito positivo per chi sta ancora affrontando questo sviluppo sottolienando che sono importanti anche i CR.

[HEADERS]
Authorization: Bearer eyJ4NWM...
Host: modipa-val.fse.salute.gov.it
FSE-JWT-Signature: eyJ4NWMiOlsi...
Content-Type: multipart/form-data; boundary=esa_f229c1e9-fc31-42af-84b6-7730a687a9d5


[BODY]
--esa_f229c1e9-fc31-42af-84b6-7730a687a9d5
 Content-Disposition: form-data; name="requestBody"

{"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VALIDATION"}

--esa_f229c1e9-fc31-42af-84b6-7730a687a9d5
 Content-Disposition: form-data; name="file"; filename="FSERIS3359-1.pdf"
Content-Type: application/pdf 

%PDF-1.4
%öäüß
......
......
%%EOF


--esa_f229c1e9-fc31-42af-84b6-7730a687a9d5--
