### ISSUE TITLE
Crash Program - Creazione documento da Piemonte verso Friuli: BLOCKING_ERROR

### ISSUE THREAD

**Issue by marco-volpe** [ministero-salute/it-fse-support#1130]
Buongiorno

riceviamo il seguente errore in fase di pubblicazione

```json
{
      "eventType": "PUBLICATION",
      "eventDate": "2024-10-21T16:29:47.767+02:00",
      "eventStatus": "SUCCESS",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.010.4.4^1729520986983",
      "subject": "PROVAX00X00X000Y^^^\u00262.16.840.1.113883.2.9.4.3.2\u0026ISO",
      "tipoAttivita": "CON",
      "organizzazione": "010",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.431db89105^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "a36e6b0233757df3",
      "issuer": "integrity:S1#010#REGIONEPIEMONTETEST",
      "expiringDate": "2025-10-21T16:29:47.776+02:00"
    },
    {
      "eventType": "SEND_TO_INI",
      "eventDate": "2024-10-21T16:29:49.319+02:00",
      "eventStatus": "BLOCKING_ERROR",
      "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:OID contains invalid characters: 2.16.840.1.113883.2.9.2.010.4.5.1CODE CONTEXT:Internal Error",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.431db89105^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-10-21T16:29:49.327+02:00"
    }
```

Restiamo a disposizione

**Comment by izamberlan** [comment]
Il problema è quello che abbiamo appena segnalato in
[https://github.com/ministero-salute/it-fse-support/issues/1128](url)

**Comment by marco-volpe** [comment]
Grazie @izamberlan  per l'immediata risposta

correggendo i valori di repository ID e documenti OID creazione e aggiornamento metadati sono OK

Ottengo ora questo errore per la sostituzione

```json
{
      "eventType": "REPLACE",
      "eventDate": "2024-10-21T16:50:43.414+02:00",
      "eventStatus": "SUCCESS",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.010.4.4^1729522241459",
      "subject": "PROVAX00X00X000Y^^^\u00262.16.840.1.113883.2.9.4.3.2\u0026ISO",
      "tipoAttivita": "CON",
      "organizzazione": "010",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.b6ec5f28ef^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "2d361622ea8e0797",
      "issuer": "integrity:S1#010#REGIONEPIEMONTETEST",
      "expiringDate": "2025-10-21T16:50:43.423+02:00"
    },
    {
      "eventType": "SEND_TO_INI",
      "eventDate": "2024-10-21T16:50:43.897+02:00",
      "eventStatus": "BLOCKING_ERROR",
      "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryDeprecatedDocumentErrorCODE CONTEXT:XDS Deprecated Document Error:\n The following registry objects were referenced by this submission but are not present, as Approved documents, in the registry: [urn:uuid:0ea6d01b-b1ce-4a62-ac8b-f7bc36e4f58b]",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.b6ec5f28ef^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-10-21T16:50:43.905+02:00"
    }
```

Precedentemente, lo status di pubblicazione è stato il seguente

```json
{
      "eventType": "PUBLICATION",
      "eventDate": "2024-10-21T16:50:22.528+02:00",
      "eventStatus": "SUCCESS",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.10.4.4^1729522219679",
      "subject": "PROVAX00X00X000Y^^^\u00262.16.840.1.113883.2.9.4.3.2\u0026ISO",
      "tipoAttivita": "CON",
      "organizzazione": "010",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.768368ce7f^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "9a847eee23bd0616",
      "issuer": "integrity:S1#010#REGIONEPIEMONTETEST",
      "expiringDate": "2025-10-21T16:50:22.537+02:00"
    },
    {
      "eventType": "SEND_TO_INI",
      "eventDate": "2024-10-21T16:50:24.444+02:00",
      "eventStatus": "SUCCESS",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.768368ce7f^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-10-21T16:50:24.452+02:00"
    }
```

Resto a disposizione

**Comment by izamberlan** [comment]
Temo ci sia un problema, ci siamo incrociati - parlavo di FSE Liguria, non FVG (la issue originariamente si riferiva a Liguria). Quando è stato editato il titolo ho rimosso, infatti, il mio commento.

**Comment by marco-volpe** [comment]
> Temo ci siamo incrociati - io parlavo di FSE Liguria, non FVG (la issue originariamente si riferiva a Liguria). Quando è stato editato il titolo ho rimosso, infatti, il mio commento. Evidentemente anche FVG rifiutava l'indicizzazione per lo stesso problema. Noi (Liguria) non abbiamo ricevuto l'indicizzazione del documento indicato

Errore mio, @izamberlan 
Il post era riferito al Friuli e non alla Liguria come inizialmente indicato
A seguito della correzione sui valori di repositoryId e document OID tutti i test con la Ligura sono andati a buon fine.

Attendo ora indicazioni da parte del Friuli per l'errore indicato

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
abbiamo verificato.
Il caso si è verificato perchè la transazione di replace è stata eseguita con l'URN urn:uuid:0ea6d01b-b1ce-4a62-ac8b-f7bc36e4f58b che risulta Deprecato anzichè sull'urn urn:uuid:7e4ced36-9bff-4d73-9dcd-7c02c6d3b114 che risulta Approved con versione 1.2
Abbiamo visto che questo accade perchè il documento ha subito questo iter:
- Creazione/Pubblicazione
- Aggiornamento dei metadati
- Replace
e il registry vi ha restituito quello deprecato anzichè quello approved.
Volevamo chiedervi se riuscivate a testare un caso di Pubblicazione e poi replace (senza una metadata update per lo stesso documento) e farci sapere l'esito in questo caso. 
Ad ogni modo applichiamo una modifica per gestire questa casistica Metadataupdate con successiva sostituzione per fare in modo che il registry restituisca sempre l'ultimo con lo stato aggiornato (quindi quello approved).
Ringraziando molto per la collaborazione auguriamo una buona giornata. 
p.s. chiedo a @vigliottim @LucaRogledi se per cortesia possono taggarmi nel caso di eventuali altre issue che richiedano una verifica del Friuli Venezia Giulia. 
Grazie mille.

**Comment by marco-volpe** [comment]
Buongiorno @ChiaraCeccottiFVG 

confermo che senza l'aggiornamento, la sostituzione e la cancellazione vanno a buon fine

Lascio decidere al team FSE se lasciare il thread aperto in attesa della fix sull'aggiornamento o se considerare chiuso il flusso con FVG

Buona giornata

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno @marco-volpe,
ringrazio molto per il riscontro.
Auguro una buona giornata.
