### ISSUE TITLE
Crash Program - Creazione documento da Piemonte verso Veneto: BLOCKING_ERROR

### ISSUE THREAD

**Issue by marco-volpe** [ministero-salute/it-fse-support#1132]
Buongiorno

otteniamo il seguente errore in fase di pubblicazione

```json
  {
      "eventType": "PUBLICATION",
      "eventDate": "2024-10-21T17:14:22.193+02:00",
      "eventStatus": "SUCCESS",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.10.4.4^1729523661526",
      "subject": "PROVAX00X00X000Y^^^\u00262.16.840.1.113883.2.9.4.3.2\u0026ISO",
      "tipoAttivita": "CON",
      "organizzazione": "010",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.a5070f6b52^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "f227d10a5229ef8b",
      "issuer": "integrity:S1#010#REGIONEPIEMONTETEST",
      "expiringDate": "2025-10-21T17:14:22.201+02:00"
    },
    {
      "eventType": "SEND_TO_INI",
      "eventDate": "2024-10-21T17:14:22.482+02:00",
      "eventStatus": "BLOCKING_ERROR",
      "message": "500 : \"{\"traceID\":\"a0704247ab2c9093\",\"spanID\":\"a0704247ab2c9093\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: Missing upload consent Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}\"",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.a5070f6b52^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-10-21T17:14:22.489+02:00"
    }
```

Restiamo a disposizione

**Comment by rangemasterd** [comment]
Salve, stesso problema anche da Regione Umbria

**Comment by marco-volpe** [comment]
Buongiorno

con il cambio del codice fiscale la creazione è OK

```json
{
      "eventType": "PUBLICATION",
      "eventDate": "2024-10-23T07:19:09.899+02:00",
      "eventStatus": "SUCCESS",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.10.4.4^1729660748446",
      "subject": "PROVAX00X00X000Y^^^\u00262.16.840.1.113883.2.9.4.3.2\u0026ISO",
      "tipoAttivita": "CON",
      "organizzazione": "010",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.8548594cb9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "5045c5f697bdc577",
      "issuer": "integrity:S1#010#REGIONEPIEMONTETEST",
      "expiringDate": "2025-10-23T07:19:09.951+02:00"
    },
    {
      "eventType": "SEND_TO_INI",
      "eventDate": "2024-10-23T07:19:11.103+02:00",
      "eventStatus": "SUCCESS",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.8548594cb9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-10-23T07:19:11.279+02:00"
    }
```

L'aggiornamento, la sostituzione e la cancellazione invece restituiscono errore 500

###  Aggiornamento

```json
 {
  "status": "500"
}
```

### Sostituzione

```json
{
  "traceID": "38d5b934db509a89",
  "spanID": "38d5b934db509a89",
  "type": "/msg/ini-error",
  "title": "Ini error.",
  "detail": "{\"traceID\":\"38d5b934db509a89\",\"spanID\":\"42baf05688cc4cf3\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"\",\"instance\":\"error/generic\"}", 
  "status": "500",
  "instance": "/msg/service-error/ini"
}
```

### Cancellazione

```json
{
  "traceID": "e62e09fe755edb14",
  "spanID": "e62e09fe755edb14",
  "type": "/msg/ini-error",
  "title": "Ini error.",
  "detail": "{\"traceID\":\"e62e09fe755edb14\",\"spanID\":\"7fc95d5f9378f593\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"\",\"instance\":\"error/generic\"}", 
  "status": "500",
  "instance": "/msg/service-error/ini"
}
```

Restiamo a disposizione

**Comment by marco-volpe** [comment]
Buongiorno

ci sono aggiornamenti?

**Comment by vigliottim** [comment]
@azienda-zero

Buon pomeriggio,
chiediamo cortesemente alla regione Veneto di fornire supporto.
Grazie.

**Comment by amarconS** [comment]
@azienda-zero 

Buonasera,
ci sono aggiornamenti? 

Grazie.

**Comment by mikeben89** [comment]
Buongiorno,
purtroppo non abbiamo più i log delle transazioni.
Riuscireste ad effettuare un altro tentativo? Indicando anche i document uniqueid utilizzati e il timestamp del test, per agevolare le verifiche.

Grazie

**Comment by marco-volpe** [comment]
Buongiorno @mikeben89 

abbiamo riprovato ora,  l'aggiornamento restituisce questo errore

```json
{
  "traceID": "3e3cc634ce5b068a",
  "spanID": "4dbf78990cb1e939",
  "type": "/errors",
  "title": "Generic",
  "detail": "it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSDuplicateUniqueIdInRegistryCODE CONTEXT:The Unique ID: 2.16.840.1.113883.2.9.2.10.4.4^CRASH_PROGRAM_1731593111483 received for a submission set or folder was not unique within the registry",
  "instance": "error/generic"
}
```

L'OID del documento è stato generato in fase di pubblicazione ed è sicuramente unico rispetto a qualsiasi altra comunicazione precedente proveniente da Regione Piemonte

Creazione, sostituzione e cancellazione sono OK

Resto a disposizione

**Comment by vigliottim** [comment]
Buongiorno @mikeben89,
le chiediamo gentilmente di fornire supporto.
Grazie.

**Comment by mikeben89** [comment]
Buon pomeriggio,
in data 14/11 vediamo essere arrivate due transazioni, ma entrambe sono di tipo create. La prima in ordine temporale è arrivata alle 15:05:13  con document uniqueid 2.16.840.1.113883.2.9.2.10.4.4^CRASH_PROGRAM_1731593111483, la seconda alle 15:05:34 con stesso document uniqueid della prima, da cui l'errore.

La seconda transazione avrebbe dovuto essere la sostituzione immagino, ma nella richiesta non ci risulta essere presente nessuna associazione di replace con un documento precedente. Chiediamo quindi di verificare:
- che la sostituzione abbia i corretti parametri, e che non si stia per errore inviando due volte una create
- l'univocità degli uniqueid inviati

Grazie.

**Comment by vigliottim** [comment]
@marco-volpe 

Buongiorno,
le chiediamo gentilmente un riscontro.
Grazie.

**Comment by marco-volpe** [comment]
Buongiorno @mikeben89 

In generale i test che facciamo sono sempre nella sequenza creazione, aggiornamento, sostituzione, cancellazione
L'OID del documento è sempre nuovo ad ogni test, quindi è impossibile avere dei duplicati

Abbiamo riprovato a fare un nuovo test ed abbiamo ottenuto i seguenti risultati

- Creazione :OK
- Aggiornamento: KO
- Sostituzione: OK
- Cancellazione: OK

Per l'aggiornamento l'errore avuto è il seguente

```json
{
  "traceID": "508a0fe569f6f796",
  "spanID": "db36b557e91d6edc",
  "type": "/errors",
  "title": "Generic",
  "detail": "it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSDuplicateUniqueIdInRegistryCODE CONTEXT:The Unique ID: 2.16.840.1.113883.2.9.2.10.4.4^CRASH_PROGRAM_1732524150567 received for a submission set or folder was not unique within the registry",
  "instance": "error/generic"
}
```

L'aggiornamento fa riferimento al documento **2.16.840.1.113883.2.9.2.10.4.4^CRASH_PROGRAM_1732524150567**

Chiedo anche a @vigliottim  di verificare all'interno dei loro sistemi

Restiamo a disposizione

**Comment by mikeben89** [comment]
Buongiorno,
sulla base dell'ultimo commento vedo quindi che il problema è nella transazione di aggiornamento metadati.
@vigliottim lato Veneto non vediamo arrivare nessuna ITI-57 ma solamente una sequenza di ITI-18 e ITI-42.

E' possibile verificare?

**Comment by LucaRogledi** [comment]
Buonasera,
chiudiamo la presente issue poiché in attesa del rilascio della ITI-57.
Sarà possibile riaprire la presente issue oppure aprirne una nuova, una volta che saranno aperte le verifiche riguardanti la ITI-57, in caso si dovessero riscontrare problemi. 
Grazie
