### ISSUE TITLE
Errore servizio Eliminazione

### ISSUE THREAD

**Issue by ppalmerini** [ministero-salute/it-fse-support#1134]
Buonasera, 
stiamo riscontrando errori sul servizio di eliminazione inviando a questo endpoint:
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.50.4.4%5E000007

la risposta che otteniamo è:
{
    "traceID": "3641d62cc5370a5a",
    "spanID": "3641d62cc5370a5a",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "detail": "{\"traceID\":\"3641d62cc5370a5a\",\"spanID\":\"f0c777c81624e22b\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"RDA generated an internal error.\",\"instance\":\"error/generic\"}",
    "status": 500,
    "instance": "/msg/service-error/ini"
}

Chiediamo vostra gentile assistenza per capire quale sia il problema, grazie

**Comment by LucaRogledi** [comment]
Buonasera, potrebbe gentilmente indicare la RDA in questione ? Grazie

**Comment by ppalmerini** [comment]
Chiedo scusa,
regione veneto

**Comment by LucaRogledi** [comment]
Buongiorno, 
Potrebbe gentilmente riprovare la chiamata utilizzando il seguente valore PZNTTF20T30L219R per il codice fiscale del paziente e darci un riscontro in caso l'errore si ripresenti?
Grazie

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
Grazie.

**Comment by ppalmerini** [comment]
Buongiorno,
abbiamo riprovato ad interrogare il servizio a questo endpoint:
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.50.2.50.4.4.2%5E20241030121740 e continuiamo ad ottenere un errore generico di questo tipo:
{"traceID":"b6ffeeaea225b0da","spanID":"882c8758dbecaf04","type":"/errors","title":"Generic","detail":"","instance":"error/generic"}

Il documento che stiamo tentando di eliminare è stato prima validato e poi correttamente pubblicato; lo status che viene restituito interrogando https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/status/2.16.840.1.113883.2.9.2.50.4.4.5721bf93cd748cc87970b5f6ed060c83e2a7d980256096ab332a03bc16d146e8.8d64fcad3d%5E%5E%5E%5Eurn%3Aihe%3Aiti%3Axdw%3A2013%3AworkflowInstanceId
è il seguente:
[...]
{
            "eventType": "PUBLICATION",
            "eventDate": "2024-10-30T12:20:30.590+01:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.50.2.50.4.4.2^20241030121740",
            "subject": "GRLMSM60R31F770Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "OBS",
            "organizzazione": "050",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.5721bf93cd748cc87970b5f6ed060c83e2a7d980256096ab332a03bc16d146e8.8d64fcad3d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "6a79161e3de6406a",
            "issuer": "integrity:S1#050#REGIONEVENETOTEST",
            "expiringDate": "2025-10-30T12:20:30.599+01:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-10-30T12:20:31.401+01:00",
            "eventStatus": "SUCCESS",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.5721bf93cd748cc87970b5f6ed060c83e2a7d980256096ab332a03bc16d146e8.8d64fcad3d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-10-30T12:20:31.411+01:00"
        }
[...]

Chiediamo cortesemente la vostra assistenza, grazie

**Comment by vigliottim** [comment]
Buongiorno,
le chiediamo gentilmente di confermarci che sta chiamando il servizio di cancellazione seguendo le indicazioni riportate in documentazione al link: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#5-servizio-di-eliminazione-documento
In particolare, i parameters da inviare nella request, che sarà di tipo DELETE, sono i seguenti:

![image](https://github.com/user-attachments/assets/e03ebed6-dee9-4aa9-8a59-6d7c6dd4fa39)

Grazie.

**Comment by ppalmerini** [comment]
Buonasera, confermo quanto indicato nei suggerimenti.
Riprovando per scrupolo otteniamo sempre l'errore 
{
    "traceID": "702513b7b1a16155",
    "spanID": "b1ffd8cabac7ea49",
    "type": "/errors",
    "title": "Generic",
    "detail": "",
    "instance": "error/generic"
} 
ottenuto interrogando il servizio con una DELETE verso https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.50.2.50.4.4.2%5E20241030121740

**Comment by LucaRogledi** [comment]
Buongiorno, 
dalle verifiche tramite [jwt.io](https://jwt.io/) sui token utilizzati sembrerebbe, come riportato negli screenshot di seguito, che la firma non sia valida ottenendo "Invalid Signature" probabilmente causato da alcuni caratteri presenti nel campo "x5c".

Signature
![image](https://github.com/user-attachments/assets/77fb7bec-7792-43e1-af6c-cf1fe1177bc4)

Bearer
![image](https://github.com/user-attachments/assets/062852b0-d9a1-478c-acc0-57eca796e657)

Le chiediamo gentilmente di riprovare le chiamate di pubblicazione e cancellazione utilizzando token con signature verificata.
Se può esserle utile è disponibile online al link [jwt-generator](https://github.com/ministero-salute/it-fse-gtw-tools) il tool per la generazione dei token.
Restiamo a disposizione per ulteriore supporto.
Grazie

**Comment by ppalmerini** [comment]
Buongiorno, abbiamo riprovato sempre con lo stesso enpoint inviando una DELETE: https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.50.2.50.4.4.2%5E20241030121740
Otteniamo ora una risposta di questo tipo:
{
    "status": 500
}

Potete darci supporto?
Grazie

**Comment by vigliottim** [comment]
Buongiorno,
potrebbe gentilmente fornirci i seguenti dati:

- traceID/govwayID della pubblicazione del documento che sta tentando di cancellare
- response completa della chiamata delete

Grazie.

**Comment by ppalmerini** [comment]
Certo, eccoli:
{"traceID":"6a79161e3de6406a","spanID":"6a79161e3de6406a","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.50.4.4.5721bf93cd748cc87970b5f6ed060c83e2a7d980256096ab332a03bc16d146e8.8d64fcad3d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

risposta completa cancellazione:
{
    "status": 500
}

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
In data 31/10 sono stati segnalati sul canale Slack possibili disservizi dovuti al rilascio di un aggiornamento.
Potrebbe gentilmente riprovare con un giro pulito di chiamate?
Dove con l'esecuzione di un "giro pulito" intendiamo:

- la chiamata del servizio di validazione per un nuovo documento mai pubblicato in precedenza. 
- la chiamata di pubblicazione per il documento validato utilizzando un identificativoDoc originale, in modo da evitare errori riguardanti Documenti già esistenti.
- la chiamata di cancellazione del documento pubblicato.

Le chiediamo cortesemente di riprovare così e rimaniamo in attesa di un vostro gentile riscontro.
In caso l'errore dovesse ripresentarsi le chiediamo di riportare l'esito delle chiamate di pubblicazione e cancellazione per effettuare ulteriori verifiche.
Grazie

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
La invitiamo a riaprirla nel caso necessiti di ulteriore supporto.
Grazie.
