### ISSUE TITLE
Crash Program - Creazione documento da Piemonte verso Molise: BLOCKING_ERROR

### ISSUE THREAD

**Issue by marco-volpe** [ministero-salute/it-fse-support#1135]
Buongiorno

segnalo il seguente problema in fase di creazione

```json
{
      "eventType": "PUBLICATION",
      "eventDate": "2024-10-21T17:25:48.639+02:00",
      "eventStatus": "SUCCESS",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.10.4.4^1729524347854",
      "subject": "PROVAX00X00X000Y^^^\u00262.16.840.1.113883.2.9.4.3.2\u0026ISO",
      "tipoAttivita": "CON",
      "organizzazione": "010",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.d677195177^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "b33eca5a33a95378",
      "issuer": "integrity:S1#010#REGIONEPIEMONTETEST",
      "expiringDate": "2025-10-21T17:25:48.651+02:00"
    },
    {
      "eventType": "SEND_TO_INI",
      "eventDate": "2024-10-21T17:25:50.142+02:00",
      "eventStatus": "BLOCKING_ERROR",
      "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R91CODE CONTEXT:Wrong value of SubmissionSet.author (SubmissionSet1)SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R25CODE CONTEXT:Wrong value of DocumentEntry.author (Document1)",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.d677195177^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-10-21T17:25:50.152+02:00"
    }
```

Restiamo a disposizione

**Comment by marlagatta** [comment]
Salve.

Dai log della regione Molise risulta che il metadato DocumentEntry.author e' stato valorizzato con 
AAAAAA00B77B000F^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO
e la stringa "AAAAAA00B77B000F" non risulta essere un codice fiscale valido, da cui  gli errori di validazione previsti dalle specifiche di interoperabilita':

R25 Wrong value of DocumentEntry.author
R91 Wrong value of SubmissionSet.author

**Comment by marco-volpe** [comment]
Buongiorno @marlagatta 

faremo un nuovo tentativo modificando il codice fiscale. Segnalo che l'attuale è usato in tutti i test che stiamo eseguendo e ci risulta formalmente valido anche se fisicamente non esistente.

Avete bisogno di un CF di una persona reale?

**Comment by marco-volpe** [comment]
Buongiorno @marlagatta 

ho eseguito un test usando un codice fiscale reale come medico. Creazione / Aggiornamento e Sostituzione sono OK

Per la cancellazione ho questo errore

```json
 {
      "eventType": "INI_DELETE",
      "eventDate": "2024-10-22T10:34:00.029+02:00",
      "eventStatus": "ASYNC_RETRY",
      "message": "Transazione presa in carico",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.10.4.4^1729586014713",
      "subject": "PROVAX00X00X000Y^^^\u00262.16.840.1.113883.2.9.4.3.2\u0026ISO",
      "tipoAttivita": "PHR",
      "organizzazione": "010",
      "workflowInstanceId": "ac142af92632cf1071d066b99091f6b135b57baaf630ad6f7e6d419f2fda6169.5d335ac0ee^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "7891f92cbb9449a4",
      "issuer": "integrity:S1#010#REGIONEPIEMONTETEST",
      "expiringDate": "2025-10-22T10:34:00.038+02:00"
    },
    {
      "eventType": "SEND_TO_INI",
      "eventDate": "2024-10-22T10:34:00.835+02:00",
      "eventStatus": "BLOCKING_ERROR_MAX_RETRY",
      "message": "Massimo numero di retry raggiunto: 500 : \"{\"traceID\":\"663e551cf6d36f02\",\"spanID\":\"663e551cf6d36f02\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: Missing mandatory attributes in the attribute assertion Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}\"",
      "workflowInstanceId": "ac142af92632cf1071d066b99091f6b135b57baaf630ad6f7e6d419f2fda6169.5d335ac0ee^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-10-22T10:34:00.843+02:00"
    }
```

Resto a disposizione

**Comment by marlagatta** [comment]
> Buongiorno @marlagatta
> 
> faremo un nuovo tentativo modificando il codice fiscale. Segnalo che l'attuale è usato in tutti i test che stiamo eseguendo e ci risulta formalmente valido anche se fisicamente non esistente.
> 
> Avete bisogno di un CF di una persona reale?

Salve. 
Da sito dell'agenzia delle entrate il codice fiscale non risulta valido, e non viene accettato dalla Regione Molise,
a meno che non sia il codice fiscale utilizzato per i test con INI, e cioe' "PROVAX00X00X000Y".
Dal momento che vediamo che utilizzate questo valore  come asserzione di attributo "urn:oasis:names:tc:xacml:1.0:subject:subject-id", suggeriamo di usare PROVAX00X00X000Y come author

**Comment by marlagatta** [comment]
Salve @marco-volpe.
Potreste cortesemente riprovare? 
Abbiamo innalzato il livello di log per intercettare l'errore in modo specifico.
Riteniamo che il problema possa essere legato alla non presenza nell'asserzione girata da INI dei tre attributi SubjectApplicationId, SubjectApplicationVendor e SubjectApplicationVersion, che sono facoltativi solo in caso di cancellazione a seguito di trasferimento indice (quindi per purposeofuse SYSADMIN).  A questo proposito abbiamo richiesto informazioni sul canale slack [https://developersitalia.slack.com/archives/C03RDT88FSM/p1729616943476289]

Grazie mille

**Comment by marco-volpe** [comment]
Buongiorno @marlagatta 

rieseguendo il test (due volte) la cancellazione è andata a buon fine

Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. 
Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
