### ISSUE TITLE
Aggiornamento metadati da Sardegna verso Regione Puglia 

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#1139]
Buongiorno,
procedendo con un aggiornamento dei metadati verso Puglia del seguente documento `2.16.840.1.113883.2.9.4.3.8^200106FSEPGL01E41A145J20241022101408759799 `
con workflowInstanceId:`2.16.840.1.113883.2.9.2.120.4.4.64513e1beb68b46434823a6ffaa0ac4662165b4f0be95e69239e0f1d30fb1aa0.b96f3ddf03^^^^urn:ihe:iti:xdw:2013:workflowInstanceId,

e traceId : `6717601ac0213044670d20dcd9022c52`,

abbiamo riscontrato che, al momento del recupero della versione precedente dei metadati (ITI-18) otteniamo la seguente risposta positiva ma vuota 
```
<soapenv:Body>
        <ns5:AdhocQueryResponse xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns4="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns6="urn:hl7-org:v3" startIndex="0" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Success">
            <ns2:RegistryObjectList/>
        </ns5:AdhocQueryResponse>
    </soapenv:Body>
```
Attendiamo un riscontro per capire il problema,
aggiungo il tag al referente della regione Puglia @lninnova per conoscenza.

**Comment by pFonziSogei** [comment]
Salve, confermiamo la necessità di verifica lato regionale @lninnova

**Comment by lninnova** [comment]
Buongiorno, confermo che si tratta di un bug noto che stiamo risolvendo in questi giorni.

**Comment by ds-tommaso** [comment]
Buongiorno @lninnova, approfitto di questa issue aperta in materia di FSE data la mancata risposta a mail precedenti.
Se preferisce, possiamo spostare la conversazione su un canale differente.

In breve, viene sollevato l'errore "FSE-10001 - Il documento CDA non è firmato digitalmente" a seguito di pubblicazione di referti in ambiente di produzione. Il referto - avente documento "cda.xml" iniettato - risulta firmato Pades.
Ultimo timestamp: 2024-10-28T16:10:40Z
