### ISSUE TITLE
Aggiornamento metadati da assistito

### ISSUE THREAD

**Issue by izamberlan** [ministero-salute/it-fse-support#1140]
È ovvio che per comunicare oscuramenti al gateway è necessario che il ruolo ASS possa effettuare modifiche metadati.

Tuttavia chiamando il gateway otteniamo

 {     "traceID":"eda880daf27f6253",

"spanID":"eda880daf27f6253",

"type":"/msg/ini-error",

“title":"Ini error.",

"detail":"{\"traceID\":\"eda880daf27f6253\",\"spanID\":\"7aa3c59cbad9bb6b\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: This role has not the rights to access the service Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}",

"status":500,

"instance":"/msg/service-error/ini"

}

A noi la chiamata non arriva.

**Comment by LucaRogledi** [comment]
Buongiorno,
l'impossibilità di fare una comunica da parte dell'assistito è stato già posta all'attenzione di chi si occupa dell'aggiornamento delle specifiche. Al momento è in lavorazione e non abbiamo evidenza riguardo le tempistiche. 
Procediamo con la chiusura della presente issue e la invitiamo a monitorare la issue #712 . 
Restiamo a disposizione per ulteriore supporto.
Grazie
