### ISSUE TITLE
Richiesta: tempo di retenion delle informazioni

### ISSUE THREAD

**Issue by marco-volpe** [ministero-salute/it-fse-support#1141]
Buongiorno

Sapete già indicarci quale sarà il periodo di retention delle informazioni relative allo stato di pubblicazione / aggiornamento / cancellazione di un documento dato un workflowInstanceId?

Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, 
Per l'ambiente di test può fare riferimento al parametro `expiringDate` riportato nella response della status per workflowInstanceId. 
Grazie

**Comment by marco-volpe** [comment]
Buongiorno @LucaRogledi 

grazie, in test vedo che il tempo di vita è di un anno. Sapete già indicarci se in produzione sarà lo stesso oppure minore o maggiore?

Grazie

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
Al momento, tali informazioni riguardanti il gateway in produzione, non sono ancora disponibili.
Grazie

**Comment by marco-volpe** [comment]
Perfetto, grazie per il supporto

**Comment by LucaRogledi** [comment]
Ringraziamo per il feedback e procediamo con la chiusura della presente issue. Restiamo a disposizione per ulteriore supporto. Grazie
