### ISSUE TITLE
Accreditamento

### ISSUE THREAD

**Issue by zaknet** [ministero-salute/it-fse-support#1142]
Buongiorno,
volevo solo sapere se, dopo aver compilato e spedito il survey [https://ec.europa.eu/eusurvey/runner/FSE-raccolta-id-applicativo](https://ec.europa.eu/eusurvey/runner/FSE-2-validazione)), devo aspettare una vostra conferma per iniziae a caricare i test.
Inoltre volevo capire se come certificati uso gli stessi che ho utilizzato per i test in autonomia.
Geazie mille, buona giornata.

**Comment by vigliottim** [comment]
Buongiorno,
può procedere a caricare i test e può utilizzare gli stessi certificati già in suo possesso. 
Grazie.

**Comment by zaknet** [comment]
Grazie per l'info.
Cordiali saluti

**Comment by zaknet** [comment]
Buongiorno, avrei bisogno di un chiarimento.
Per quanto riguarda la validazione RSA, per il test case 0, non vedo nel repository un file xml per fare il test, mentre c'è per gli altri 3 casi. 
Questo significa che posso usare l'xml del case 1 per esempio per passare il case 0?

Leggendo la documentazione ho capito bene che devo usare questi xml come file da incoporare nell'invio dei test? o questi xml hanno un altro scopo?
Grazie mille,
Cordiali saluti

**Comment by vigliottim** [comment]
Buongiorno, 
nella cartella [Documenti XML Casi OK - RSA](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/Documenti%20XML%20Casi%20OK/7%20-%20Casi%20OK%20Referto%20Specialistico%20Ambulatoriale) sono riportati alcuni xml di esempio a scopo dimostrativo. 
Ai fini dell'accreditamento sarà necessario sottomettere i propri CDA2, costruiti secondo le specifiche contenute nei file excel all'interno della cartella [Test Case Validazione - RSA](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/7-Referto%20Specialistico%20Ambulatoriale).
Successivamente dovrà effettuare i test di validazione dei pdf con i CDA2 iniettati al loro interno e caricare i risultati come indicato in [documentazione](https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#accreditamento-fse-20-draft).
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.

**Comment by zaknet** [comment]
Buongiorno, riparo per questo motivo:
Ho caricato i files per l'accreditamento, mail sistema mi ha ritornato l'errore:

[ {
  "error" : "DATA_JSON_RESULT_NOT_FOUND",
  "description" : "Informazioni risultati test non trovate."
} ]

eppure a me pare tutto a posto, il json è presente. Cosa c'è di sbagliato?
Grazie mille!
Cordiali saluti

**Comment by vigliottim** [comment]
Buongiorno,
il nome del _vendor_ deve essere lo stesso di quello indicato nella cartella.
Pertanto, la invitiamo a correggere JOKER_SRL con JOKER SRL e riprovare:

<img width="376" alt="image" src="https://github.com/user-attachments/assets/d3f52fcb-fd44-4175-b893-89baf768bf9c">

Grazie.

**Comment by zaknet** [comment]
Grazie, in effetti nella documentazione era scritto di sostituire gli spazi con un underscore, e così ho fatto.
Ho ricaricato il tutto come da lei indicato e fatto la pull request, vediamo come va, grazie!
Cordiali saluti

**Comment by vigliottim** [comment]
Buon pomeriggio,
stiamo effettuando delle verifiche.
Le faremo sapere non appena avremo aggiornamenti.
Grazie.

**Comment by vigliottim** [comment]
Buon pomeriggio,
ora la cartella di destinazione è corretta. 
Le chiediamo di correggere nel file _data.json_ tutti i campi che hanno la lettera maiuscola iniziale usando la lettera minuscola.
Grazie.

**Comment by zaknet** [comment]
Fatto le modifiche, e fatto la nuova pull request. Attendo notizie, grazie, chiudo.

**Comment by zaknet** [comment]
Buongiorno, riapro perchè finalmente mi sono arrivati gli errori sul file CDA.
Nello specifico non riesco a capire dove sia l'errore indicato da questa sezione:
```
{
  "id" : 148,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='142' attribute='code' actual = '' expected = '93126-1'>ClinicalDocument/component/structuredBody/component/section[ID='Confronto_con_Precedenti_Esami_Eseguiti']/code</error>"
}
```
e altre simili sempre della sezione indicata: Confronto_con_Precedenti_Esami_Eseguiti, in quanto il section id da usare, indicato solo nei vari file di esempio di tipo RSA come:

<section ID="CONFRONTO_PRECEDENTI_ESAMI_ESEGUITI">

a mio parere non è corretto, ma non ho trovato altre indicazioni in merito.
Quale può essere quindi il problema? 
Esiste una tabella con gli id sezione corretti? sono stati messi errati appositamente negli esempi?
Grazie mille,
cordiali saluti

**Comment by vigliottim** [comment]
Buongiorno,
l'errore riportato di seguito riferito al CT2 OK per RSA (_id = 148_):

```
{
  "id" : 148,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='142' attribute='code' actual = '' expected = '93126-1'>ClinicalDocument/component/structuredBody/component/section[ID='Confronto_con_Precedenti_Esami_Eseguiti']/code</error>"
}
```

![image](https://github.com/user-attachments/assets/8c32869d-e337-4334-989a-492f4d93c02d)

potrebbe essere causato dal fatto che non è prevista la presenza della sezione con _id = "Confronto_con_Precedenti_Esami_Eseguiti"_.

Inoltre, le facciamo presente che il nome di tale sezione è errato:

![image](https://github.com/user-attachments/assets/6333f51f-3cd9-4d81-b58f-772bd5c62b9b)

Infatti, le specifiche prevedono che sia _"Confronto_con_Precedenti_Esami_Eseguiti"_ e non _"CONFRONTO_PRECEDENTI_ESAMI_ESEGUITI"_:

![image](https://github.com/user-attachments/assets/cb947ce0-9bb7-405c-8ce8-17d7d4b5a381)

Anche la sezione "Accertamenti_e_Controlli_Consigliati" non è prevista nel CT2 OK e la sua presenza causa gli errori ad essa correlati:

```
{
  "id" : 148,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='172' attribute='code' actual = '' expected = '80615-8'>ClinicalDocument/component/structuredBody/component/section[ID='Accertamenti_e_Controlli_Consigliati']/code</error>"
}
....
```

La invitiamo a controllare la documentazione e strutturare nuovamente il CDA2 rispettando le specifiche riportate nell'excel.
Può usare il tool messo a disposizione [gtw-certifier](https://github.com/ministero-salute/it-fse-gtw-tools/tree/31b609b0fc4dfee9f5afab46d2215ef7c2ef057e/gtw-certifier) per la verifica offline dei casi di test OK.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by zaknet** [comment]
Grazie, ma quindi dove trovo la documentazione con i codici di sezione corretti?
Inoltre nel file CDA2_Referto_Specialistica_Ambulatoriale_OK che contiene i dati da mettere nel test non è molto chiaro l'utilizzo: devo mettere solo le righe segnate come "obbligatorie"? quindi nel caso nel test 2 (148) mettere solo la sezione "Storia_clinica" ?
Grazie mille,

**Comment by vigliottim** [comment]
> Buongiorno, nella cartella [Documenti XML Casi OK - RSA](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/Documenti%20XML%20Casi%20OK/7%20-%20Casi%20OK%20Referto%20Specialistico%20Ambulatoriale) sono riportati alcuni xml di esempio a scopo dimostrativo. Ai fini dell'accreditamento sarà necessario sottomettere i propri CDA2, costruiti secondo le specifiche contenute nei file excel all'interno della cartella [Test Case Validazione - RSA](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/7-Referto%20Specialistico%20Ambulatoriale). Successivamente dovrà effettuare i test di validazione dei pdf con i CDA2 iniettati al loro interno e caricare i risultati come indicato in [documentazione](https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#accreditamento-fse-20-draft). Rimaniamo a disposizione per ulteriori chiarimenti.

I link le sono stati indicati nel commento sopra.
Gli elementi segnati come obbligatori devono essere inseriti, quelli opzionali possono non essere inseriti e non inficiano l'esito del test se strutturati correttamente.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso fosse necessario ulteriore supporto. Grazie.

**Comment by zaknet** [comment]
Buongiorno, riapro per una domanda di procedura: ammettiamo che a questi giro il test passi, poi noi per attivare il servizio dovremo fare altri passaggi oppure possiamo partire subito con la trasmissione di dati reali? Quanto tempo può passare dall'accreditamento ai primi invii di dati reali con il sistema del cliente? Ho visto che ci sono altri 2 step, ma non è indicata una durata.
Grazie mille!
Buona giornata

**Comment by vigliottim** [comment]
> Buongiorno, riapro per una domanda di procedura: ammettiamo che a questi giro il test passi, poi noi per attivare il servizio dovremo fare altri passaggi oppure possiamo partire subito con la trasmissione di dati reali? Quanto tempo può passare dall'accreditamento ai primi invii di dati reali con il sistema del cliente? Ho visto che ci sono altri 2 step, ma non è indicata una durata. Grazie mille! Buona giornata

Buongiorno, attualmente è possibile completare esclusivamente la fase 1 del processo di accreditamento poiché il gtw ha solo l'ambiente di test disponibile. La invitiamo a monitorare i canali dedicati per futuri aggiornamenti. Grazie.

**Comment by zaknet** [comment]
Ah quindi mi sta dicendo che nessuno attualmente può utilizzare questo sistema FSE in produzione? cioè tutti quelli che hanno mandato i test per passare l'accreditamento non hanno in funzione nessun sistema in ambiente reale?
Grazie mille per la delucidazione.
Cordiali saluti

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
Confermiamo che al momento non è possibile utilizzare FSE 2.0 per aggiornare l'ambiente di produzione, contenente dati reali, in quanto i servizi esposti dal gateway fse2.0 sono disponibili in ambiente di test.
La invitiamo a monitorare il canale [Slack fse](https://developersitalia.slack.com/archives/C03RDT88FSM) per aggiornamenti riguardo l'avvio in produzione del gateway fse 2.0 e restiamo a disposizione per eventuale supporto.
Grazie
