### ISSUE TITLE
Quesito su corrispondenze esami

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#1148]
Buongiorno, nelle more di creazione delle tabelle di corrispondenza tra tariffario e codici ICD9, prelevati dove mi avete detto, trovo alcune incongruenze.
Ne cito una per tutte: la mammografia.
Nel nomenclatore, ma anche nella realtà, esistono (oltre ad altri tipi) la mammografia monolaterale (87.37.2) e quella bilaterale (87.37.1) che, ovviamente, non sono la stessa cosa.
Nei codici ICD9 trovo SOLO **87.37** **Altra mammografia**.
Tecnicamente potrei far comparire nel referto (entry->act->code/displayName) questi valori ad ogni mammografia, ma mi chiedo se sia corretto, oppure se aggiungere ogni volta un tag **translation**, ma anche in questo caso non sono sicuro che sia corretto.
Cosa potete dirmi in proposito?
Grazie mille.

**Comment by vigliottim** [comment]
Buongiorno,
potrebbe cortesemente indicare a quale tipologia documentale fa riferimento?
Grazie.

**Comment by infoserviceonline** [comment]
Certamente, RAD, ma credo che il problema riguardi tutto il sistema, perciò non l'avevo indicata.
Saluti.

**Comment by vigliottim** [comment]
Buongiorno,
per la tipologia documentale RAD e tenendo in considerazione il path da lei indicato, secondo le specifiche HL7 Italia riportiamo la seguente considerazione:

_Nel caso della sezione “Esame Eseguito”, section/entry/act/ l’elemento Act risulta essere un “Elemento OBBLIGATORIO atto a descrivere l’esame eseguito mediante un codice e una descrizione e la data nella quale è stato effettuato l’esame.” 
L’elemento < code > contenuto al suo interno può essere valorizzato utilizzando i sistemi di codifica LOINC, ICD9-CM o eventuali altre tipologie di codifica. Nel caso in cui si ritiene opportuno si può valorizzare l’elemento < code > con le codifiche LOINC e ICD9-CM e si potrà utilizzare l’elemento <translation> per eventuali altre codifiche._

**Comment by infoserviceonline** [comment]
Ok, farò dei test per capirci qualcosa, visto che oggi mi sta validando qualunque cosa, mentre la regione puglia non valida più niente.
Grazie
