### ISSUE TITLE
Crash Program: pubblicazione excel per avanzamento test

### ISSUE THREAD

**Issue by marco-volpe** [ministero-salute/it-fse-support#1149]
Buongiorno

allo scopo di dover documentare l'avanzamento dei test, avreste modo di pubblicare nell'area Sharepoint condivisa il documento excel con i numeri dei test eseguiti per ogni regione? Lo stesso che condividete nelle call del lunedi

Grazie

**Comment by LucaRogledi** [comment]
Buonasera, procediamo con la chiusura della segnalazione in quanto l'excel a cui si fa riferimento viene condiviso su uno Sharepoint del DTD. 
Restiamo a disposizione per ulteriore supporto.
Grazie
