### ISSUE TITLE
VALIDAZIONE CDA2 LAB - Problemi schematron e specifiche

### ISSUE THREAD

**Issue by lorenzasoverini** [ministero-salute/it-fse-support#115]
Buongiorno,
nel provare a validare tramite schematron e xsd il referto di laboratorio prodotto dal nostro software (D4CLIS - Dedalus) ci siamo scontrati con alcune problematiche per le quali avremmo bisogno di supporto, in particolare:
1. il nostro CDA avrebbe un suo namespace, correttamente dichiarato xmlns:c="urn:hl7-org:v3" usato per la maggioranza dei tag del CDA ma ci viene rifiutato con errore generico 500, eliminando il namespace e lasciando quindi i tag "puri" con dichiarazione xmlns="urn:hl7-org:v3" funziona. Come mai non possiamo utilizzare un namespace differente se correttamente dichiarato? La validazione da xsd non restituiva alcun problema in tal senso, il namespace c era correttamente interpretato.
2. Sempre per i namespace, ci viene restituito un errore in validazione tramite xsd qualora uno o più tag abbiano un secondo namespace diverso dal precedente, teoricamente è consentito avere più namespace no?
3. Errore nel valore del ClinicalDocument.typeId --> secondo le specifiche il valore dell'extension dovrebbe essere <c:typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040"/>, ciò è quanto presente nella documentazione hl7 standard e nel documento specifico dell'header. Ci risulta però un errore 400 relativo a questo campo che si risolve mettendo il valore POCD_MT000040UV02, quale valore va usato?
4. In validazione schematron viene richiesto l'attributo use obbligatorio per tutti i tag telecom nonostante da specifiche tale attributo sia obbligatorio solo per i telecom del paziente, come mai?
5. Perchè il tag specimen è obbligatorio (stando agli esempi richiesti, non alla validazione xsd) pur essendo un tag opzionale?
6. Perchè vengono indicate come obbligatorie, negli esempi richiesti, la section di specialità e la section foglia quando da specifiche è indicato che le section foglia POSSONO essere inserite o meno come ulteriore livello? Relativamente a questo punto c'è un errore probabilmente poi nello schematron che interpreta non correttamente la struttura cercando le section foglia. 
[EsempioD4CLIS.pdf](https://github.com/ministero-salute/it-fse-support/files/10803284/EsempioD4CLIS.pdf)

Mi scuso per il lungo elenco ma ho cercato di riassumere tutto in un unico post, il pdf allegato contiene il cda di esempio relativo a quanto indicato.
Grazie
Lorenza Soverini

**Comment by IStacchiotti** [comment]
Buongiorno, i namespace utilizzati nel CDA2 devono necessariamente richiamare quelli dichiarati nell'xsd altrimenti si generano errori sia nella validazione che durante la trasformazione FHIR di un documento che contiene dei tag "non puri". Pertanto non bisogna dichiarare un namespace personalizzato, anche per consentire una gestione efficace in fasi successive. Grazie per la segnalazione. Si conferma inoltre che è consentito avere più namespace nel CDA2 purché questi siano dichiarati a livello di xsd. Dal CDA2 fornito, il tag <lab:statusCode code="completed"/> è correttamente valorizzato all'interno del documentationOf. Verrà pertanto modificato l'xsd. Si ricorda che, per l'elemento ClinicalDocument/typeId/@extension, il valore corretto da utilizzare è POCD_MT000040UV02, che rappresenta l'ultima versione del POCD. Ci teniamo a precisare che il valore riportato nell'esempio di implementazione nella guida HL7 del referto di laboratorio, è solo a titolo di esempio e non è da considerarsi una regola di conformità. Il controllo sull'attributo "@use" nell'elemento "telecom" è essenziale per garantire una corretta interpretazione dell'elemento.-6. Per superare i test case e conseguire l'accreditamento è necessario generare esempi CDA2 che soddisfino le richieste dei casi di test.

**Comment by lorenzasoverini** [comment]
Salve!
grazie per la risposta, ho ancora qualche dubbio in merito però.
In particolare per i namespace indicate che non si può dichiarare un namespace personalizzato ma va bene però usare il namespace "lab", il namespace c del nostro esempio comunque fa riferimento a  xmlns:c="urn:hl7-org:v3"  che è quello standard, non qualcosa di custom e l'xsd lo valida tranquillamente infatti ma ci ritorna errore quando lanciamo la validazione al vostro servizio, non con l'xsd diretto.
Per quanto riguarda invece l'extension POCD_MT... esiste un documento di riferimento dove ciò sia specificato? per verificare se vi sono anche altre indicazioni diverse rispetto a quanto presente nelle specifiche? (quella extension nel documento di specifiche dell'header viene indicata non come esempio ma come valore obbligatorio da inserire e vorremmo essere certi di non avere sbagliato anche con altri valori del CDA).
Per l'attributo @use dei telecom quindi le specifiche verranno aggiornate specificandolo come obbligatorio per tutti i telecom e non solo quelli del paziente, giusto?
Per quanto riguarda invece per esempio il discorso sezione foglia, anche nel vostro excel di riferimento per i test trovo che è marcata come opzionale la presenza della sezione foglia (come da specifiche), nel documento word invece è indicata come necessaria, quale documento va quindi preso come riferimento per la creazione dei test?

**Comment by IStacchiotti** [comment]
Buongiorno, la validazione online del CDA2 genera un errore riguardante il jwt resource_hl7_type inerente all'elemento `ClinicalDocument/code` in quanto non riconosce l'elemento `<c:code`. Il namespace "lab" richiama una estensione "labExtension" già definita nell'xsd per identificare l'elemento observationRange/precondition, pertanto è corretto utilizzarlo. Inoltre intendiamo correggere la risposta fornita precedentemente riguardante l'elemento `<lab:statusCode code="completed"/>` presente all'interno del documentationOf. In realtà, il nuovo POCD già prevede l'elemento statusCode, quindi non è necessario utilizzare l'estensione "lab" per quel particolare elemento.
Nel paragrafo relativo all'elemento typeId della guida implementativa, non viene indicato di fare riferimento alla guida dell'header per la sua valorizzazione.
A questo [link ](https://github.com/ministero-salute/it-fse-support/tree/main/validazione/xsd) è possibile trovare l'xsd completo.
Per quanto riguarda l'attributo @use di telecom, la guida implementativa non fornisce indicazioni specifiche sulla valorizzazione di tutti gli attributi. Tuttavia, nel caso in cui l'utilizzo di tale elemento venga richiesto (ad esempio il telecom presente nell' "author"), la guida indica di fare riferimento alla struttura dell'elemento telecom associato al paziente per determinare la corretta valorizzazione.
Per quanto riguarda l'ultimo punto, secondo le specifiche, la sezione foglia è opzionale (come anche indicato dalla cardinalità nell'excel), ma può diventare obbligatoria se richiesta per un particolare caso di test quindi evidenziata in verde nell'Excel di riferimento. Questo viene indicato nel documento Word associato, dove si richiede di inserire la sezione foglia per fornire informazioni aggiuntive e rendere il caso di test il più completo possibile. Per creare i casi di test, quindi, è necessario fare riferimento sia all'Excel che al documento Word, seguendo le istruzioni fornite per ogni caso di test.

**Comment by IStacchiotti** [comment]
Buonasera, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
