### ISSUE TITLE
Nuova ITI-57 (aggiornamento metadati)

### ISSUE THREAD

**Issue by daniele-gubellini** [ministero-salute/it-fse-support#1154]
Salve,

in merito alla nuova ITI-57 per l'aggiornamento dei metadati, avremmo una richiesta da fare: vi chiediamo di poter indicare a INI un URL dedicato alla nuova messaggistica di aggiornamento metadati.
Si avrebbero cosi' due URL: 

1. uno per le comunicazioni e sostituzioni
2. uno per l'aggiornamento metadati

grazie

**Comment by angeloceloni** [comment]
Buonasera
anche Regione Umbria è favorevole all'indicazione di un endpoint separato per la ITI-57

**Comment by assistenza-fsevda** [comment]
Buongiorno,
oltre al wsdl, chiediamo a @SOGEI che sia condivisa anche una request/response di esempio.
grazie

**Comment by g-maugeri-sogei** [comment]
Buonasera,
[daniele-gubellini](https://github.com/daniele-gubellini)
possiamo chiusa questa segnalazione? Il nuovo servizio risponde su un URL differente.
