### ISSUE TITLE
Regione Toscana gestione p98

### ISSUE THREAD

**Issue by Gianpr0** [ministero-salute/it-fse-support#1157]
Buongiorno,

apriamo la seguente issue per porre delle domande sulla gestione delle regole di accesso p98.

In fase di fruizione del documento, dovrà essere visibile a tutti i medici o solo all'author del documento?
Inoltre abbiamo letto che non dovrà essere inviato verso INI e quindi immaginiamo anche verso il gtw?
Sarà sbloccata questa situazione?

Grazie

**Comment by assistenza-fsevda** [comment]
Buongiorno,
anche come Regione Valle d'Aosta siamo interessati a questo argomento.

Grazie

**Comment by vigliottim** [comment]
Buongiorno,
l'Affinity Domain 2.4.1 prevede 3 codici di oscuramento (_P99_, _P98_ e _P97_) ma, non essendo validati da nessun decreto, non possono essere effettivamente utilizzati.
Infatti, nell'[Affinity Domain 2.5](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20interoperabilit%C3%A0/AffinityDomainItalia_v2-5_v20231212.pdf) è presente la seguente nota:

![image](https://github.com/user-attachments/assets/2a38ab58-9e61-4f1a-be85-a64bbfaafff7)

Pertanto, salvo aggiornamenti, non è possibile usare il codice di oscuramento _P98_.

**Comment by assistenza-fsevda** [comment]
Buongiorno @vigliottim, 
grazie per il feedback. Quello che volevamo sapere è se ci sono novità in merito alle tempistiche di un loro possibile "sblocco" e conseguenti regole di utilizzo (soprattutto del valore P98).

Grazie mille.

**Comment by vigliottim** [comment]
La informiamo che non ci sono novità in merito.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue e rimaniamo a disposizione per altre richieste di supporto.
