### ISSUE TITLE
Regione Toscana gestione STP PS

### ISSUE THREAD

**Issue by Gianpr0** [ministero-salute/it-fse-support#1158]
Buongiorno,

stiamo provando ad inviare un verbale di pronto soccorso con all'interno un STP al posto del codice fiscale.
L'stp è nazionale e ha OID 2.16.840.1.113883.2.9.4.3.17.

Al momento ci blocca il jwt con il seguente errore:
{
    "traceID": "0ab8b48fde0dcd6a",
    "spanID": "0ab8b48fde0dcd6a",
    "type": "/msg/jwt-validation",
    "title": "Campo token JWT non valido.",
    "detail": "Il codice fiscale nel campo person_id non è corretto",
    "status": 403,
    "instance": "/jwt-mandatory-field-malformed",
    "workflowInstanceId": "UNKNOWN_WORKFLOW_ID"
}

Attualmente il gtw gestisce questa casistica? come possiamo procedere?

Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, 
dalle verifiche sui token utilizzati per la chiamata con `"traceID": "0ab8b48fde0dcd6a"` risulta che è il campo:
`"person_id": "STP000909090945^^^&2.16.840.1.113883.2.9.4.3.2&ISO"` 
all'interno del token di signature non è valorizzato correttamente.
La invitiamo a riprovare utilizzando la valorizzazione corretta: `"person_id":"STP000909090945^^^&2.16.840.1.113883.2.9.4.3.17&ISO"`
e restiamo a disposizione in caso l'errore dovesse ripresentarsi. 
Grazie

**Comment by vigliottim** [comment]
Buonasera,
analizzando i token utilizzati tramite il tool [jwt.io](jwt.io), è emersa la presenza di campi non previsti dalle [specifiche](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt):

**_Authorization Bearer Token:_**
<img width="226" alt="image" src="https://github.com/user-attachments/assets/0b2dbef2-2852-4c16-ae7b-9cd9f42409c7">

**_FSE-JWT-Signature Token:_**
<img width="238" alt="image" src="https://github.com/user-attachments/assets/57e6de12-ac82-4795-bf1b-7f756c75c59f">

La invitiamo a riprovare dopo aver rimosso i claim non ammessi.
Grazie.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso in cui avesse bisogno di ulteriore supporto.
Grazie.
