### ISSUE TITLE
Regione Valle d'Aosta - XDSDocumentEntry.Slot - Conservazione a norma

### ISSUE THREAD

**Issue by assistenza-fsevda** [ministero-salute/it-fse-support#1159]
Buongiorno,
volevamo avere informazioni in merito allo slot "XDSDocumentEntry.Slot - Conservazione a norma". Abbiamo notato che a fronte di una pubblicazione effettuata con il gateway, nella comunicazione metadati che riceviamo da INI ci viene sempre inviato lo slot "urn:ita:2017:repository-type" che corrisponde alla conservazione a norma. Dato che nelle varie pubblicazioni che abbiamo fatto non abbiamo mai specificato il parametro "conservazioneANorma" nel body della request, ci chiedevamo se questo metadato venisse valorizzato di default dal Gateway o da INI.

Vi riporto di seguito gli elementi relativi ad un caso di pubblicazione.

ITI-42 ricevuta da INI: [ITI-42 INI to VdA.txt](https://github.com/user-attachments/files/17518378/ITI-42.INI.to.VdA.txt)
CDA2 contenuto nel documento pubblicato: [cda.txt](https://github.com/user-attachments/files/17518398/cda.txt)

Parametri nel body della request di creazione verso il Gateway:
```
{
	"assettoOrganizzativo": "AD_PSC075",
	"dataFinePrestazione": "20241030090000",
	"dataInizioPrestazione": "20241030090000",
	"healthDataFormat": "CDA",
	"identificativoDoc": "2.16.840.1.113883.2.9.2.20.4.4^001.TRAKTEST.TESTRSA:APIMC0023-0",
	"identificativoRep": "2.16.840.1.113883.2.9.2.20.4.5.1",
	"identificativoSottomissione": "2.16.840.1.113883.2.9.2.20.4.3.20241024.133000",
	"mode": "ATTACHMENT",
	"tipoAttivitaClinica": "CON",
	"tipoDocumentoLivAlto": "REF",
	"tipologiaStruttura": "Ospedale"
}
```
Tracciatura dello status della pubblicazione:
```
{
    "traceID": "16eefac9dddad9a9",
    "spanID": "80cdd2d9f50f6945",
    "transactionData": [
        {
            "eventType": "VALIDATION_FOR_PUBLICATION",
            "eventDate": "2024-10-24T14:55:22.825+02:00",
            "eventStatus": "SUCCESS",
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "020",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.9ad2da13de^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "c6d87bb9780c5341",
            "issuer": "integrity:S1#020#020VALDAOSTATEST",
            "expiringDate": "2025-10-24T14:55:22.835+02:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-10-24T14:55:22.895+02:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.20.4.4^001.TRAKTEST.TESTRSA:APIMC0023-0",
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "CON",
            "organizzazione": "020",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.9ad2da13de^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "c6d87bb9780c5341",
            "issuer": "integrity:S1#020#020VALDAOSTATEST",
            "expiringDate": "2025-10-24T14:55:22.904+02:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-10-24T17:19:09.138+02:00",
            "eventStatus": "SUCCESS",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.20101.4.4.5.e21c1196ad1cec9f893978e29f730dcc09cda62f889a138da36f930edb31b268.9ad2da13de^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-10-24T17:19:09.146+02:00"
        }
    ]
}
```
Ci fate avere informazioni in merito?

Grazie anticipatamente

**Comment by vigliottim** [comment]
Buongiorno,
attualmente il metadato "XDSDocumentEntry.Slot - Conservazione a norma" viene popolato in maniera hard coded dal GTW. Esso dovrà essere ribaltato e si attende una conferma per il rilascio della modifica.

**Comment by vigliottim** [comment]
Buonasera,
la informiamo che è appena stato rilasciato un aggiornamento.
Il metadato "XDSDocumentEntry.Slot - Conservazione a norma" non viene impostato hard coded ma ribaltato.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by assistenza-fsevda** [comment]
Grazie per il riscontro. A seguito degli ultimi test che abbiamo effettuato confermiamo che adesso il metadato _"XDSDocumentEntry.Slot - Conservazione a norma"_ non viene più inviato da INI. Non appena possibile effettueremo ulteriori test per valorizzarlo tramite richiesta di pubblicazione al Gateway.

Grazia ancora per il supporto.

**Comment by vigliottim** [comment]
Grazie a lei per il gentile feedback.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
