### ISSUE TITLE
Creazione documento RSA per visita fisiatrica

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#1160]
Buongiorno,
pur rientrando, a quanto pare, nella categoria documentale RSA, la visita fisiatrica ha delle caratteristiche atipiche.
Si compone di una serie di voci che per il CDA sono opzionali, e su questo non ci sono problemi, e di altro:
**diagnosi**: la inserisco nella sezione 5.8, diagnosi. Anche se non è obbligatoria qualcosa devo pur inserire, se no resta tutto vuoto.
**prescrizioni**: si tratta di EVENTUALI terapie prescritte in fase di visita, coerenti con la diagnosi, con contestuale emissione di ricette ROSSE.
Queste ultime dove le dovrei inserire? Leggo e rileggo la documentazione ma non riesco ad individuare il posto corretto.
La sezione 5.5, Prestazioni, si riferisce a prestazioni erogate, non prescritte.
Preciso che lavoro in Puglia.............purtroppo!
Grazie.

**Comment by infoserviceonline** [comment]
Aggiungo che anche gli odontoiatri sono nella stessa situazione. Il referente della Regione mi dice che manca completamente la parte per le prescrizioni.

**Comment by angeloceloni** [comment]
Buongiorno
scrivo da Regione Umbria perché siamo interessati all'argomento dato che stiamo implementando la specialistica ambulatoriale con diversi software. Probabilmente nella redazione delle specifiche non è stato preso in considerazione il caso della prescrizione diretta dello specialista perché in molte regioni può prescrivere solo la specialistica e per la i farmaci è previsto l'invio al MMG/PLS. 
Per indicare la terapia prescritta non si può utilizzare la sezione "5.12 Sezione Terapia Farmacologica Consigliata"?
Posso chiedere come mai indica l'emissione di ricette rosse e non dematerializzate? L'invio delle ricette dema completerebbe il contenuto informativo perché alimentano il FSE.

**Comment by infoserviceonline** [comment]
Salve collega, gli errori sulle tipologie documentali sono innumerevoli e questo è solo uno dei tanti, esisteva una tipologia documentale prescrittiva, mai attivata, ma nessuno ha previsto il fatto che esistono strutture sanitarie che non refertano, ma redigono piani di cura con relativa prescrizioni. Ciò mi è stato confermato per le vie brevi proprio ieri.
_->Per indicare la terapia prescritta non si può utilizzare la sezione "5.12 Sezione Terapia Farmacologica Consigliata"?_
Probabilmente si, anche se bisognerebbe codificare e gestire praticamente tutto il prontuario farmaceutico, per quanto ne so, per poi costringere i Fisiatri ad utilizzarlo, se pensa che qui usano ancora carta e penna..............
_->Posso chiedere come mai indica l'emissione di ricette rosse e non dematerializzate? L'invio delle ricette dema completerebbe il contenuto informativo perché alimentano il FSE._
Questa domanda dovrebbe farla ad Innovapuglia & C., che gestisce il sistema. Ad oggi sono riusciti a produrre le ricette "bianche" solo nel pubblico per motivi che non posso esporre. 
Per qualsiasi cosa resto a disposizione. Saluti: Francesco Leo info@infoserviceonline.it.

**Comment by LucaRogledi** [comment]
Buongiorno,

Rispondiamo per punti:

1. In merito alle informazioni della Diagnosi, possono essere inserite all'interno della specifica sezione OPZIONALE "Diagnosi";
2. Per l'inserimento delle ricette, siano esse elettroniche e/o cartacee, come riportato all’interno delle Guide Implementative di HL7 Italia, per la tipologia documentale RSA, si può fare riferimento al campo  <inFulfillmentOf> dell'Header.

Grazie

**Comment by infoserviceonline** [comment]
Buongiorno, non riesco a capire a quale campo dell'Header si riferisce. Se intende il tag inFulfillmentOf non è quello corretto poichè, riporto dalla documentazione:
4.1.18 Prescrizione: <inFulfillmentOf>
Elemento CONSIGLIATO che identifica la richiesta **che ha determinato la produzione del documento** di Referto di Specialistica Ambulatoriale od agni altro tipo di ordine ad esso relativo. 

Il caso d'uso sottoposto, invece, riguarda **esattamente il contrario**, ossia il Medico redige un piano di cura, NON UN REFERTO, e, se necessario, prescrive le prestazioni su ricetta. Quindi non è la ricetta che genera il documento, che, ripeto, non è un referto, ma è il documento che, all'occorrenza, viene completato con  la prescrizione di una o più ricette.
Spero di essere stato sufficientemente chiaro.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
se sta cercando di creare un CDA2 di Referto di Specialistica Ambulatoriale relativa ad una prestazione fisiatrica è OBBLIGATORIO inserire le seguenti sezioni:

- _Prestazioni_: dove è necessario specificare le prestazioni erogate (ES: visita fisiatrica);
- _Referto_: dove è necessario specificare quanto emerso nel corso della/e prestazione/i, riporta quindi al proprio interno una
descrizione delle valutazioni del medico e dell’esito della prestazione.

Infine, rispetto alla documentazione da lei condivisa, se si vuole inserire all’interno del referto eventuali terapie prescritte in fase di visita, si può fare riferimento alla sezione OPZIONALE "Accertamenti e Controlli Consigliati".
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by infoserviceonline** [comment]
Salve, credevo fosse chiaro che il mio (e non solo mio, visto i contatti ricevuti), caso d'uso è questo:

Infine, rispetto alla documentazione da lei condivisa, se si vuole inserire all’interno del referto eventuali terapie prescritte in fase di visita, si può fare riferimento alla sezione OPZIONALE "Accertamenti e Controlli Consigliati".

Quindi lei mi sta dicendo che eventuali RICETTE MEDICHE DEL S.S.N. dovranno essere considerate come "Accertamenti e Controlli Consigliati", pur trattandosi realmente di PRESCRIZIONI? Inoltre, se ho capito bene, posso omettere completamente le ricette? A me sembra assurdo, ma se lo dite voi per me va bene, chiedo solo conferma.

**Comment by vigliottim** [comment]
Buongiorno,
non possiamo scendere nelle specificità delle singole regioni.

**Comment by infoserviceonline** [comment]
Buongiorno, prendo atto delle risposte e mi regolerò di conseguenza.
Grazie.
