### ISSUE TITLE
REGIONE BASILICATA UC7_EliminazioneDocumento: - Step 1

### ISSUE THREAD

**Issue by BasilicataCrashProgramFSE** [ministero-salute/it-fse-support#1163]
A seguito di una chiamata di delete, riceviamo un errore 500 Internal Server Error.

Di seguito i dettagli della richiesta e della risposta

**Request**
```
URL: https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.170.4.4%5E201.AIRO.006012024000006_1
METHOD: DELETE
[HEADERS]
Authorization: Bearer
************
Accept: application/json
FSE-JWT-Signature: eyJ4NWMiOlsiTUlJRmRUQ0NBMTJnQXdJQkFnSVVFd1dyMDB2VHJpT1FyU3BxbkpTQkZiWEE0UTB3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TkRBM01qSXdPVEUyTURSYUZ3MHlOekEzTWpNd09URTJNRE5hTUhZeEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVNVd0l3WURWUVFEREJ4VE1TTXhOekFqVWtWSFNVOU9SVUpCVTBsTVNVTkJWRUZVUlZOVU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBekRBM1NUOTJIclgrTUx4Y1doaEFYb2M2UTRNY0FpM2VJNWNsYjAya1NQSFoxZ0JFb1owQlhyd3pvS3pnTERiVmoyRkxWcmhTV3JjVlRacWJpRlprSktoM2NBS0k2WWRUNEFVQWhBbWhJV3hvK2hZbTgxSzU3NEdteTFraDZYdlJ3RVNDMHZHTGxQcE00TnhuTlhJbmNSdFc4VlBFNE9Sb0NNN3YzaTRNSTM0RUU1YWx2QWVwVWVKYjFMZnJoa3dYZHBsV2hGcmRyMUdYR29vOUloY2hLcnVlS0RoQmJzNFpYZG9sV2pGRndHeU1uN0p3U2dyUTFLbTd0aU1qZXJJZGZnOHNsZlc2YmhtVFJPSFdGN2RrWU0yZ2tEMzR4VVpPSUVjVWhZc0s3OXJmMWZhaVJ3QkdUa05INjY0Y2Rwa1FaLytDTXdWakpkdkRuSDNtcVE0a0N3SURBUUFCbzRJQkdEQ0NBUlF3SHdZRFZSMGpCQmd3Rm9BVUZqbXBHZ1dKdHc4dHNqWHR3Z21heFFPRElqOHdFZ1lEVlIwZ0JBc3dDVEFIQmdVclRCMEJDekNCclFZRFZSMGZCSUdsTUlHaU1JR2ZvSUdjb0lHWmhvR1dhSFIwY0hNNkx5OWpZWE52WjJWcGMzWnBiQzV6YjJkbGFTNXBkQzlsYW1KallTOXdkV0pzYVdOM1pXSXZkMlZpWkdsemRDOWpaWEowWkdsemREOWpiV1E5WTNKc0ptbHpjM1ZsY2oxRFRpVXpSRU5CSzAxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVXJWR1Z6ZENVeVEwOGxNMFJOYVc1cGMzUmxjbThyWkdWc2JHRXJVMkZzZFhSbEpUSkRReVV6UkVsVU1CMEdBMVVkRGdRV0JCVHhvdWRtNThsSjNqL1BnRHFJcDJ2eGQ1ZURPREFPQmdOVkhROEJBZjhFQkFNQ0JrQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBS3BCa0g1bWZlTjZkSGtlWFZpbmhwcEJ1WEFyZGlodUF4UmZUekt4MmlPNVZaaC9yYUZmc0IxMHVMSGt3S0tlK1Eyd1MxYXRIQ0M1NDJJaE5jMzRtNUVDMGFtSEdBcURXQS9xcjQxWlJvR2kzVFNwV3JwNU1WNGN2aVg0dFRPSmFBQWgyaHBkcWdtUDFwU1BQbjVJQWhLekc5QzI2c290QkI3SXlyT3VHTk9JbkZ4ZjBBVFVMbVBGY3RlaEFtbGl1cWlZUUdhQlRYNCtwLzlXNTNyUjRUeStwZWRLMGQrcUdWV3FSNFJmSFo0VFNJQStmcHF4WWVVaFY0K1p2MTZTU3hSSEMreENSQWpCOERBaVF1bG5aL3JpdHJDdlhXOUZBd1RqYnVPZCtjM2Y4RUUyamJrcEZuR1pKOHI3eERiNWo4cWp6TU5VSWd3V21hOThac3ZoVkRlanp6OE9kK1A2WG5MQVRmemxoNzRUNThyQ3FoMFJDWGlkbVVOL3I3RkR5ZEt0dlVyYm5wNGdQYnhGSCtBbGh0cmQ0cmRHM2c4Wkc3SHgzQXAwVnFwMXNIR0swS3d5U3ZEam5UbzlIQVcxRHZZQ0RZUWZCVkREcFJSZWtpcElYQXU0YnNhUVR0UGl2V2gvcXhJMW44UzZSYXhlWUQ2cGFQSkZ5blp1ZlN5QTJFY0p4a05BTEtWMGNVcW12UlJyK3BJeVdMVVcxSmtyZWxYeFF6SG03TysrTU4rdzB6c3lXdUNwMWtnVjgrOWpHQm1uRnJmbDN2by9USmpNcThyeDY2WXFzNFVLNks3ak82bGFETGtFUndWQThBZnlPOXduWkNqTXpOQkhBRG9NbkQ3RkhVcUUzOGhtTU4yR0FhRzlJVE9reGdkMjVZQisvRTA5dkYza2g3RWEiXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJQUk9WQVgwMFgwMFgwMDBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwdXJwb3NlX29mX3VzZSI6IlVQREFURSIsImlzcyI6ImludGVncml0eTpTMSMxNzAjUkVHSU9ORUJBU0lMSUNBVEFURVNUIiwibG9jYWxpdHkiOiJBWklFTkRBIFNBTklUQVJJQSBMT0NBTEUgREkgUE9URU5aQSBBU1BeXl5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4xLjMmSVNPXl5eXjE3MDIwMSIsInN1YmplY3RfYXBwbGljYXRpb25fdmVyc2lvbiI6IjIuMjIuMCIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBMYXppbyIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMTIwIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJhY3Rpb25faWQiOiJERUxFVEUiLCJyZXNvdXJjZV9obDdfdHlwZSI6IignXl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsImF0dGFjaG1lbnRfaGFzaCI6ImRhMzlhM2VlNWU2YjRiMGQzMjU1YmZlZjk1NjAxODkwYWZkODA3MDkiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiQU1JQ08iLCJleHAiOjE3Mjk4NzI4OTksInN1YmplY3RfYXBwbGljYXRpb25fdmVuZG9yIjoiR1BJX1NQQSIsImlhdCI6MTcyOTg2OTI5OSwianRpIjoiYmYxZjdjYmUtMzZmMS00NTYxLTg3ZjYtMzhlMzBhYTUyNjRjIiwicGVyc29uX2lkIjoiUFJWUFZUODFFMDNGMDUyVyJ9.eEUjHGKZNx4pKl4FCqUCNTkFWq1wvjha_ZMbqTQ9ozIIH0JSMsu1h3Kpq29DN5tk4Tb27Nw2iGUjpqDW_SrnQcZ9Wx1yyheD78O4dXuYLwxzQzUTQq5LZxqNyLKqfwGQlFt2O4drfKCtE-dQ6lrsEfE9vlzP6zFkhpTQymCnIkpivvHCyFDEZ3OPavQHTsasf_mWZJw-fuBTpLdBWhLNBRKZwsgAFS4sq9nCcRL5YjTccGbtrm807DBr-yg-a5MaQ6upYRUhNPVT2Awj4QqJbZrTrVsZ4lIeDSdv9EfUku0FuxnB7qdTateMgoZbQsioLy6IqI8yKpxze2Px5lYdAA

[PARAMETERS]

[CONTENT]
```

**Response:**

`{
"traceID" : "708e426dd39ca1c2",
"spanID" : "708e426dd39ca1c2",
"type" : "/msg/ini-error",
"title" : "Ini error.",
"detail" : "{\"timestamp\":\"2024-10-25T15:15:19.792+00:00\",\"status\":500,\"error\":\"Internal Server Error\",\"path\":\"/v1/get-reference/2.16.840.1.113883.2.9.2.170.4.4%5E201.AIRO.006012024000006_1\"}",
"status" : 500,
"instance" : "/msg/service-error/ini"
}`

E' possibile indagare sulla causa dell'errore?

**Comment by vigliottim** [comment]
Buongiorno,
da una analisi preliminare sono emersi i seguenti errori relativi al token _FSE-JWT-Signature_:

_**FSE-JWT-Signature Token**_

<img width="239" alt="image" src="https://github.com/user-attachments/assets/dced9170-e7f9-44f2-b794-8fdf00756cff">

In particolare:

- _subject_organization_id/subject_organization_: rappresentano l'identificativo e la descrizione del dominio dell’utente. Nel suo caso devono essere valorizzati come segue:
```
"subject_organization": "Regione Basilicata"
"subject_organization_id": "170"
```
- _resource_hl7_type_: rappresenta il tipo di documento da registrare - codifica LOINC nel formato _('code1^^coding-scheme1')_. 
Es. `"resource_hl7_type":"('11502-2^^2.16.840.1.113883.6.1')"`

- _person_id_: contiene il codice identificativo dell’assistito a cui si riferisce la richiesta o del genitore/tutore che ha richiesto l’operazione/codice identificativo dell’assistito, del genitore o del tutore, codificato secondo il tipo di dato CX HL7 V2.5 (per come indicato alle specifiche IHE TF-3)
Es. `"person_id": "RSSMRA75C03F839K^^^&2.16.840.1.113883.2.9.4.3.2&ISO"`

Inoltre, le facciamo presente che il campo _attachment_hash_ non è obbligatorio per la cancellazione:

![image](https://github.com/user-attachments/assets/7e45a536-d080-4b11-bd46-d1441292cb2d)

La invitiamo a correggere i campi indicati e riprovare.
Può trovare la relativa documentazione al seguente link: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,

Abbiamo effettuato un altro test di cancellazione con esito positivo.

Di seguito i dettagli:
CF: PRVPVT81E03F052W
uniqueId=2.16.840.1.113883.2.9.2.170.4.4^201.AIRO.006012024000011_1 

{
    "traceID": "82af567f48ef9238",
    "spanID": "82af567f48ef9238",
    "workflowInstanceId": "dd9beaad566a7f055a068b86ddbd188aa4c7c37befbf2601eb2f58f5fe3bc5bf.8d8dc54099^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
    "timestamp": "2024-10-30T11:00:03.635Z"
}

Potete gentilmente confermare se il test case risulta positivo?

Grazie

**Comment by vigliottim** [comment]
Buongiorno,
le confermiamo che il test eseguito ha avuto esito positivo.

Inoltre, la informiamo che può verificare autonomamente lo stato della transazione tramite i seguenti servizi:

- _Servizio di Recupero Stato Transazione per WorkflowInstanceId_: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#10-servizio-di-recupero-stato-transazione-per-workflowinstanceid
- _Servizio di Recupero Stato Transazione per TraceId_: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#11-servizio-di-recupero-stato-transazione-per-traceid

Rimaniamo a disposizione per ulteriori chiarimenti.
