### ISSUE TITLE
REGIONE BASILICATA UC3_Aggiornamento_Metadati: - Step 1

### ISSUE THREAD

**Issue by BasilicataCrashProgramFSE** [ministero-salute/it-fse-support#1164]
A seguito di una chiamata di update, riceviamo un errore **500 Internal Server Error**.

Di seguito i dettagli della richiesta e della risposta:

**Request**

```
URL: https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.170.4.4%5E201.AIRO.006012024000006_1/metadata
METHOD: PUT

[HEADERS]
Authorization: Bearer ************
Accept: application/json
FSE-JWT-Signature: eyJ4NWMiOlsiTUlJRmRUQ0NBMTJnQXdJQkFnSVVFd1dyMDB2VHJpT1FyU3BxbkpTQkZiWEE0UTB3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TkRBM01qSXdPVEUyTURSYUZ3MHlOekEzTWpNd09URTJNRE5hTUhZeEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVNVd0l3WURWUVFEREJ4VE1TTXhOekFqVWtWSFNVOU9SVUpCVTBsTVNVTkJWRUZVUlZOVU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBekRBM1NUOTJIclgrTUx4Y1doaEFYb2M2UTRNY0FpM2VJNWNsYjAya1NQSFoxZ0JFb1owQlhyd3pvS3pnTERiVmoyRkxWcmhTV3JjVlRacWJpRlprSktoM2NBS0k2WWRUNEFVQWhBbWhJV3hvK2hZbTgxSzU3NEdteTFraDZYdlJ3RVNDMHZHTGxQcE00TnhuTlhJbmNSdFc4VlBFNE9Sb0NNN3YzaTRNSTM0RUU1YWx2QWVwVWVKYjFMZnJoa3dYZHBsV2hGcmRyMUdYR29vOUloY2hLcnVlS0RoQmJzNFpYZG9sV2pGRndHeU1uN0p3U2dyUTFLbTd0aU1qZXJJZGZnOHNsZlc2YmhtVFJPSFdGN2RrWU0yZ2tEMzR4VVpPSUVjVWhZc0s3OXJmMWZhaVJ3QkdUa05INjY0Y2Rwa1FaLytDTXdWakpkdkRuSDNtcVE0a0N3SURBUUFCbzRJQkdEQ0NBUlF3SHdZRFZSMGpCQmd3Rm9BVUZqbXBHZ1dKdHc4dHNqWHR3Z21heFFPRElqOHdFZ1lEVlIwZ0JBc3dDVEFIQmdVclRCMEJDekNCclFZRFZSMGZCSUdsTUlHaU1JR2ZvSUdjb0lHWmhvR1dhSFIwY0hNNkx5OWpZWE52WjJWcGMzWnBiQzV6YjJkbGFTNXBkQzlsYW1KallTOXdkV0pzYVdOM1pXSXZkMlZpWkdsemRDOWpaWEowWkdsemREOWpiV1E5WTNKc0ptbHpjM1ZsY2oxRFRpVXpSRU5CSzAxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVXJWR1Z6ZENVeVEwOGxNMFJOYVc1cGMzUmxjbThyWkdWc2JHRXJVMkZzZFhSbEpUSkRReVV6UkVsVU1CMEdBMVVkRGdRV0JCVHhvdWRtNThsSjNqL1BnRHFJcDJ2eGQ1ZURPREFPQmdOVkhROEJBZjhFQkFNQ0JrQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBS3BCa0g1bWZlTjZkSGtlWFZpbmhwcEJ1WEFyZGlodUF4UmZUekt4MmlPNVZaaC9yYUZmc0IxMHVMSGt3S0tlK1Eyd1MxYXRIQ0M1NDJJaE5jMzRtNUVDMGFtSEdBcURXQS9xcjQxWlJvR2kzVFNwV3JwNU1WNGN2aVg0dFRPSmFBQWgyaHBkcWdtUDFwU1BQbjVJQWhLekc5QzI2c290QkI3SXlyT3VHTk9JbkZ4ZjBBVFVMbVBGY3RlaEFtbGl1cWlZUUdhQlRYNCtwLzlXNTNyUjRUeStwZWRLMGQrcUdWV3FSNFJmSFo0VFNJQStmcHF4WWVVaFY0K1p2MTZTU3hSSEMreENSQWpCOERBaVF1bG5aL3JpdHJDdlhXOUZBd1RqYnVPZCtjM2Y4RUUyamJrcEZuR1pKOHI3eERiNWo4cWp6TU5VSWd3V21hOThac3ZoVkRlanp6OE9kK1A2WG5MQVRmemxoNzRUNThyQ3FoMFJDWGlkbVVOL3I3RkR5ZEt0dlVyYm5wNGdQYnhGSCtBbGh0cmQ0cmRHM2c4Wkc3SHgzQXAwVnFwMXNIR0swS3d5U3ZEam5UbzlIQVcxRHZZQ0RZUWZCVkREcFJSZWtpcElYQXU0YnNhUVR0UGl2V2gvcXhJMW44UzZSYXhlWUQ2cGFQSkZ5blp1ZlN5QTJFY0p4a05BTEtWMGNVcW12UlJyK3BJeVdMVVcxSmtyZWxYeFF6SG03TysrTU4rdzB6c3lXdUNwMWtnVjgrOWpHQm1uRnJmbDN2by9USmpNcThyeDY2WXFzNFVLNks3ak82bGFETGtFUndWQThBZnlPOXduWkNqTXpOQkhBRG9NbkQ3RkhVcUUzOGhtTU4yR0FhRzlJVE9reGdkMjVZQisvRTA5dkYza2g3RWEiXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJQUk9WQVgwMFgwMFgwMDBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwdXJwb3NlX29mX3VzZSI6IlVQREFURSIsImlzcyI6ImludGVncml0eTpTMSMxNzAjUkVHSU9ORUJBU0lMSUNBVEFURVNUIiwibG9jYWxpdHkiOiJBWklFTkRBIFNBTklUQVJJQSBMT0NBTEUgREkgUE9URU5aQSBBU1BeXl5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4xLjMmSVNPXl5eXjE3MDIwMSIsInN1YmplY3RfYXBwbGljYXRpb25fdmVyc2lvbiI6IjIuMjIuMCIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBMYXppbyIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMTIwIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJhY3Rpb25faWQiOiJVUERBVEUiLCJyZXNvdXJjZV9obDdfdHlwZSI6IignXl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsImF0dGFjaG1lbnRfaGFzaCI6ImRhMzlhM2VlNWU2YjRiMGQzMjU1YmZlZjk1NjAxODkwYWZkODA3MDkiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiQU1JQ08iLCJleHAiOjE3Mjk4NzUwODcsInN1YmplY3RfYXBwbGljYXRpb25fdmVuZG9yIjoiR1BJX1NQQSIsImlhdCI6MTcyOTg3MTQ4NywianRpIjoiMTc4YjUyNGEtMzA5Ni00NWQyLWE4YzMtM2I4NDA4YTA4MWNmIiwicGVyc29uX2lkIjoiUFJWUFZUODFFMDNGMDUyVyJ9.ZRXPm1zY68SymXLAf7vzcid7uM-InufqdYZELh0z6Lw3F6JPFrO_W0rI1eXNmwrv3KDKvi-kESS-MaePGk4o37foo7YKFsEphEF-XhoDmBm87b_ZRpAg3YGW994RSHJ2gBV20Cjde-3EZGuMTVo2efS85W0FcBQsKpiwTy5vAjgaPWaCrw5yaI8R-0bmRGP66n0q2r6DTiYeMuQ0-FsQXTZr9PU7Wmy0e6J2ND5N84D1NmOMnWCYB5JD5eZ87-zq2kHWHnH2rcZr7RZ5-LShBdXUCRzj3nmIJNw07FR9eeVPkoFQfHVDEt_8WVv6uXPZy90Q7FeyJT6kSRMs164BtQ
Content-Type: application/json

[PARAMETERS]

[CONTENT]
{
"tipologiaStruttura" : "Ospedale",
"tipoDocumentoLivAlto" : "LDO",
"assettoOrganizzativo" : "AD_PSC001",
"dataInizioPrestazione" : "20241003110128",
"dataFinePrestazione" : "20241003110128",
"conservazioneANorma" : "",
"tipoAttivitaClinica" : "DIS",
"identificativoSottomissione" : "2.16.840.1.113883.2.9.2.170.4.3.170201.70347.0",
"attiCliniciRegoleAccesso" : [
    "P99"
]
}

```
**Response:**

`{
"status" : 500
}
`

E' possibile indagare sulla causa dell'errore?

**Comment by amarconS** [comment]
Salve, vi chiediamo se possibile di girarci timestamp e traceId della chiamata effettuata sul GTW.
Dalle chiamata da noi individuate ci risultano diversi errori nel token:

{
"type" : "validated_token",
  "valid" : true,
  "iss" : "integrity:S1#170#REGIONEBASILICATATEST",
  "sub" : "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "aud" : [ "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1" ],
  "exp" : 1729871413000,
  "iat" : 1729867813000,
  "userInfo" : { },
  "claims" : {
    "sub" : "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
    "subject_role" : "AAS",
    "purpose_of_use" : "UPDATE",
    "iss" : "integrity:S1#170#REGIONEBASILICATATEST",
    "locality" : "AZIENDA SANITARIA LOCALE DI POTENZA ASP^^^^^&2.16.840.1.113883.2.9.4.1.3&ISO^^^^170201",
    "subject_application_version" : "2.22.0",
    **"subject_organization" : "Regione Lazio",
    "subject_organization_id" : "120",**
    "aud" : "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
    "patient_consent" : "true",
    "action_id" : "UPDATE",
    **"resource_hl7_type" : "('^^2.16.840.1.113883.6.1')",**
    "attachment_hash" : "da39a3ee5e6b4b0d3255bfef95601890afd80709",
    "subject_application_id" : "AMICO",
    "exp" : "1729871413",
    "subject_application_vendor" : "GPI_SPA",
    "iat" : "1729867813",
    "jti" : "9dbd222d-5a36-44cc-a380-b9eb285d8ef1",
    **"person_id" : "PRVPVT81E03F052W"**
  },
  "rawResponse" : "{\"sub\":\"PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO\",\"subject_role\":\"AAS\",\"purpose_of_use\":\"UPDATE\",\"iss\":\"integrity:S1#170#REGIONEBASILICATATEST\",\"locality\":\"AZIENDA SANITARIA LOCALE DI POTENZA ASP^^^^^&2.16.840.1.113883.2.9.4.1.3&ISO^^^^170201\",\"subject_application_version\":\"2.22.0\",\"subject_organization\":\"Regione Lazio\",\"subject_organization_id\":\"120\",\"aud\":\"https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1\",\"patient_consent\":true,\"action_id\":\"UPDATE\",\"resource_hl7_type\":\"('^^2.16.840.1.113883.6.1')\",\"attachment_hash\":\"da39a3ee5e6b4b0d3255bfef95601890afd80709\",\"subject_application_id\":\"AMICO\",\"exp\":1729871413,\"subject_application_vendor\":\"GPI_SPA\",\"iat\":1729867813,\"jti\":\"9dbd222d-5a36-44cc-a380-b9eb285d8ef1\",\"person_id\":\"PRVPVT81E03F052W\"}",
  "sourceType" : "JWT"
}

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,


Abbiamo effettuato un altro test di aggiornamento metadato con esito positivo.

Di seguito i dettagli:
CF: PRVPVT81E03F052W
"identificativoDoc": "2.16.840.1.113883.2.9.2.170.4.4^201.AIRO.006012024000013_1",


{
    "traceID": "baf92eda6d5ddbc2",
    "spanID": "baf92eda6d5ddbc2",
    "workflowInstanceId": "ca0d3ddf826a70e9f31bd3dae00883033fef82b0284d5b88fb2275eeb2f0fddc.37b1f6cbaa^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
    "timestamp": "2024-10-30T10:51:27.936Z"
}

Potete gentilmente confermare se risulta positivo?
Grazie

**Comment by vigliottim** [comment]
Buongiorno,
le confermiamo che il test eseguito ha avuto esito positivo.

Inoltre, la informiamo che può verificare autonomamente lo stato della transazione tramite i seguenti servizi:

- _Servizio di Recupero Stato Transazione per WorkflowInstanceId_: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#10-servizio-di-recupero-stato-transazione-per-workflowinstanceid
- _Servizio di Recupero Stato Transazione per TraceId:_ https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#11-servizio-di-recupero-stato-transazione-per-traceid

Rimaniamo a disposizione per ulteriori chiarimenti.
