### ISSUE TITLE
nuova pull request

### ISSUE THREAD

**Issue by acolzi** [ministero-salute/it-fse-support#1166]
Buongiorno,

ho fatto una nuova pull request 4 giorni fa e ancora non vedo l'eleborazione.
grazie

**Comment by LucaRogledi** [comment]
Buongiorno, 
Le confermiamo che la pr è stata presa in carico e seguiranno aggiornamenti sull'esito delle elaborazioni via e-mail.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
Grazie
