### ISSUE TITLE
REGIONE LAZIO - Chiarimento su cancellazione documento di sostituzione

### ISSUE THREAD

**Issue by giosil** [ministero-salute/it-fse-support#1169]
Buongiorno, si sottopone un quesito rispetto alla cancellazione di un documento di sostituzione.
In particolare si è proceduto alla creazione di un documento con esito positivo:

{"traceID":"220852a35d673e2c","spanID":"220852a35d673e2c","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.301e0ae649a72fd42d875dc7403238a29710486ed33bade49edbbe5643460186.aafd3dfd68^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

Successivamente il documento è stato sostituito tramite una operazione di replace con esito positivo:

{"traceID":"617c3c562444d91e","spanID":"617c3c562444d91e","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.19097f79387771468e1a6331b349c8d2289ed84acddbaca01c847ee35b760de1.5286ec8a61^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

Infine è stato cancellato quest'ultimo documento con esito positivo:

{"traceID":"80c96846fc181797","spanID":"80c96846fc181797","workflowInstanceId":"1b9ada4534523f188efacac9a38b2f6d0e9b6ad70c7bc4ba2a80151fe45f2b31.e2c6a07506^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

Avendo usato il CF AAAEEE01A01H501Q (RDA=RDE) sui servizi XDS esposti ad INI di test sono state riscontrate le conseguenti transazioni XDS.
Abbiamo notato che è giunta una sola richiesta di cancellazione che interessava solo del documento di sostituzione e non anche la cancellazione del documento originario.
Si chiede conferma circa la correttezza del fatto che sia stato cancellato solo il documento di sostituzione non anche il documento originario.
Grazie. Saluti,

**Comment by giosil** [comment]
No, per il documento originario non è stata riscontrata una richiesta di cancellazione. Saluti,

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
La invitiamo a riaprirla nel caso in cui abbia bisogno di ulteriore supporto.
Grazie.
