### ISSUE TITLE
Errore in sostituzione documento (http 500)

### ISSUE THREAD

**Issue by mikeben89** [ministero-salute/it-fse-support#1170]
Buongiorno,
abbiamo il seguente errore nel servizio di sostituzione documento:
{
    "traceID": "8bdba8b6c7942636",
    "spanID": "8bdba8b6c7942636",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "detail": "{\"traceID\":\"8bdba8b6c7942636\",\"spanID\":\"f2d1b16bc01b5d3a\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"\",\"instance\":\"error/generic\"}",
    "status": 500,
    "instance": "/msg/service-error/ini"
}

Il servizio di sostituzione è stato invocato per sostituire un documento che in precedenza era stato correttamente pubblicato verso Gateway, con notifica ITI-42 verso il registry, terminata con successo.

Per questo tentativo di sostituzione al registry non è arrivata nessuna notifica. E' possibile che vi sia una discrepanza di endpoint (la pubblicazione arriva al registry corretto, e la sostituzione no?)

Grazie.

**Comment by vigliottim** [comment]
Buon pomeriggio,
sta partecipando al Crash Program?
Se sì, può indicare RDA e RDE?
Grazie.

**Comment by mikeben89** [comment]
Posso anche chiedervi conferma degli endpoint che state usando? Così possiamo fare un controllo.
Grazie

**Comment by g-maugeri-sogei** [comment]
Buonasera,
potete fornirci il timestamp e il CF dell'assistito relativo al tentativo andato in errore?

**Comment by mikeben89** [comment]
Buonasera,
non avendo il dettaglio del timestamp della prova precedente, abbiamo provveduto poco fa a rifare un invio pulito, ottenendo lo stesso errore.

Di seguito alcuni dettagli:
doc uniqueid documento "originale": 2.16.840.1.113883.2.9.2.50.2.50.4.4.2^20241030121740
doc uniqueid sostitutivo: 2.16.840.1.113883.2.9.2.50.4.4^20241031152103
risposta del gateway per la sostituzione: {"traceID":"ea0e7cabb7dd09c2","spanID":"2525490c732bcaa8","type":"/errors","title":"Generic","detail":"","instance":"error/generic"}
timestamp invio sostituzione: 2024-10-30 15:27:48.315

**Comment by mikeben89** [comment]
Il codice fiscale del paziente utilizzato è SQTPRV80A54I799T

**Comment by g-maugeri-sogei** [comment]
Trovo un soap fault nei log. Confermate che siete voi  a mandarlo ( ci sono diversi apparati tra INI e il vostro endpoint) ?

```
2024-10-30 15:27:48,968 ERROR [it.sogei.fseinteroperabilita.servicemanager.util.ErrorLogUtils] - ********************************************************************** 
2024-10-30 15:27:48,968 ERROR [it.sogei.fseinteroperabilita.servicemanager.util.ErrorLogUtils] - SOAP FAULT ENVELOPE :  
2024-10-30 15:27:48,968 ERROR [it.sogei.fseinteroperabilita.servicemanager.util.ErrorLogUtils] - <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><SOAP-ENV:Body>
    <SOAP-ENV:Fault><SOAP-ENV:Code><SOAP-ENV:Value>SOAP-ENV:Receiver</SOAP-ENV:Value></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text xml:lang="it">Errore interno server</SOAP-ENV:Text></SOAP-ENV:Reason><Detail xmlns="http://www.w3.org/2003/05/soap-envelope">
    <axis2ns7740:error xmlns:axis2ns7740="http://tempuri.org">
     <axis2ns7740:text>ERRORE #5002: Errore di ObjectScript: &lt;CLASS DOES NOT EXIST&gt;CSPDispatch+589^%SYS.cspServer *(No name)</axis2ns7740:text>
    </axis2ns7740:error>
</Detail></SOAP-ENV:Fault>
  </SOAP-ENV:Body></SOAP-ENV:Envelope> 
```

**Comment by amarconS** [comment]
Si, confermiamo l'endpoint.

**Comment by ppalmerini** [comment]
Buongiorno, 
abbiamo riprovato a fare un invio verso il servizio di sostituzione con un PUT a questo endpoint
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.50.2.50.4.4.2%5E20241030121740

usando i jwt
auth
eyJ4NWMiOlsiTUlJRmNUQ0NBMW1nQXdJQkFnSVVJYWZaaHhzMjJsdzY2TU0vUFBkcTVBSUtrV1F3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TkRBNE1qQXhOVFF5TUROYUZ3MHlOekE0TWpFeE5UUXlNREphTUhJeEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVNFd0h3WURWUVFEREJoVE1TTXdOVEFqVWtWSFNVOU9SVlpGVGtWVVQxUkZVMVF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFdqd3BtVDlVVVdtZUdxVTIrRzdQcmRXU2xHTm1xcXlZZEMva1h1SnhpZVEraFZDT2t3MDVmdGdCL3pZMXd0QU5DWlQ1NkRRYVRJZHNvUUVidkY3SDJsdkc2eGJTZDRBSVAzK3lLclcxYkJ1bGNyeW1JTndEQ1ZiNm5uS2hXQ3pLS08raTU2M29GajFYQzdvZzRZeVg2ZjNCMkUycnFTUm1FY21PKzA1SmJEQ2RINnNRU2ptL3VMOVpUVElISlVoNU5TRDFMZzJFTmQvM0xZbmxLb2NaaUdSK2tSMWc4MFdTQkpDY0dWT0gwZFRVVUx2bU94WC8xNzdVNTB3dVNJb290a25xZ0YyRVJwWWhseGNBQmlFUXpFWElMOTR6S2FtWlJ2aElDMEVvQVlJdlVTRTRUYUNpNXE2NDJmTVVmMkxmc2lUTEV1MHdWUWZsYkJQNkNtM1hOQWdNQkFBR2pnZ0VZTUlJQkZEQWZCZ05WSFNNRUdEQVdnQlFXT2FrYUJZbTNEeTJ5TmUzQ0NackZBNE1pUHpBU0JnTlZIU0FFQ3pBSk1BY0dCU3RNSFFFTE1JR3RCZ05WSFI4RWdhVXdnYUl3Z1orZ2daeWdnWm1HZ1pab2RIUndjem92TDJOaGMyOW5aV2x6ZG1sc0xuTnZaMlZwTG1sMEwyVnFZbU5oTDNCMVlteHBZM2RsWWk5M1pXSmthWE4wTDJObGNuUmthWE4wUDJOdFpEMWpjbXdtYVhOemRXVnlQVU5PSlRORVEwRXJUV2x1YVhOMFpYSnZLMlJsYkd4aEsxTmhiSFYwWlN0VVpYTjBKVEpEVHlVelJFMXBibWx6ZEdWeWJ5dGtaV3hzWVN0VFlXeDFkR1VsTWtOREpUTkVTVlF3SFFZRFZSME9CQllFRkozZFZqc0d3QXRKSGxkcC9wT09mVUpZeEM3Zk1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQXlHTnVLS0FZL25zQ1JMTS9LbDJaWEpjenVyYnN0eCtCKzIxTHI4YzQ3UThqbHFXUmdHcW9ZZW00ZEtZNnRndm03azZIS3lMallFUlVYeEJlV1FmQkVHM2RuWGczb2RqVTkvN08ySU43SWVwQmZNK2w4c2ZPSllPeTQ0bWFSV1Y5LzZXT0FMVkovenFjRG1WWktaNnM0RXZMR3N3QkRERk9ldVplbEVEVExENjhYUExyTm01RFNRdEczUnpJaVZMMTRYKzhJR0dyOVcvWmhhMWg1WGMrRSs0UDhlZDlLSTFSSm9xREg4a280NVY1dXNEL1VBeXB2ZFNXMlFPTEI2VnZTclJIay93MEZ5Sis5eFNEUFBKVi9XK2ZpcUZSNmk3MzM1ZTczZ05uVWpHVGVlbVVNbzg1NUx0WWZBcjRaM3ZNMFNiakZpYWRnamFCeC9jRGZ2dFlDS3EvMlI1WDFjUkpYS3k3cE9XeXZNQm5jQW92ZTZDWTY1SS9wTHhVZGxrMTgvRm9OWjJMSDhKaDNueHIycCtBWHNnUkVIMTF4UVNkTVhUSzl1Z2JXcTNaN3pONGlBL1E3TEV1bnJqQXRVdnRYR1JZTzdwRUdkeWNqVHRCZGJMT3B6VlYzQk9hMWhUUXFZSlFocC8zM2ExKzlXMVZWSTFCWG9IQUJtUk9EK3NYaVZXRUMwRmhHaVVmYU9TNUFsMFBxS1BWUnBlOTJObXI2ZFFjcjNJWHdIN1ZwT2RHaHBtSXBLMXhWMWFETXhhbTdzRDg0ZHM4cXZRNzhzWklhdTBSMmE4bjhyVElKZ0VBbk1wOGNnRHpNeFpLQ2tHcm91eFlCTnRISm90T0Izek4vMG5EQVl4UkIwWk9BN21EZ29TZ2hMYUNMb01kampMbjFIUWFJS1ZhOWFrPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJHUkxNU002MFIzMUY3NzBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJpc3MiOiJhdXRoOlMxIzA1MCNSRUdJT05FVkVORVRPVEVTVCIsImV4cCI6MTczMDQ1ODUyMCwiaWF0IjoxNzMwMzcyMTIwLCJqdGkiOiIxNzI3OTYyNzg1In0.sBOLkish70nwTIkz5-KnvMpfPTd49enD21vJFYnM9FnLVQmr5i7bWuI7N6vSVCkGJ_NT0L_-TIzIWijFOkQE_9n0auK-3DF7yh5ZOGEUZ7vNuMPEzQrcpRuNudccQzzvedcP1tNegTlTE8yyNTG9jN_l8fOm3E6YBc_c9MqR7cJxN3POZXAU31-oxVjyH3AK_KQckgWIC9rx1s-_w60kk88cezTKw3iOjcdT21d6JSkmiCjwjPdec9QpwCcj2oQV8Yo64ZyLMUXLq0cbJvrc4bZTQbUEmaLNroyV4Js8wA-LawoptWEquhcSK9ETlWvZe5VVGJDDFXErStBaPoRPdA

e sign
eyJ4NWMiOlsiTUlJRmNUQ0NBMW1nQXdJQkFnSVVJYWZaaHhzMjJsdzY2TU0vUFBkcTVBSUtrV1F3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TkRBNE1qQXhOVFF5TUROYUZ3MHlOekE0TWpFeE5UUXlNREphTUhJeEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVNFd0h3WURWUVFEREJoVE1TTXdOVEFqVWtWSFNVOU9SVlpGVGtWVVQxUkZVMVF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFdqd3BtVDlVVVdtZUdxVTIrRzdQcmRXU2xHTm1xcXlZZEMva1h1SnhpZVEraFZDT2t3MDVmdGdCL3pZMXd0QU5DWlQ1NkRRYVRJZHNvUUVidkY3SDJsdkc2eGJTZDRBSVAzK3lLclcxYkJ1bGNyeW1JTndEQ1ZiNm5uS2hXQ3pLS08raTU2M29GajFYQzdvZzRZeVg2ZjNCMkUycnFTUm1FY21PKzA1SmJEQ2RINnNRU2ptL3VMOVpUVElISlVoNU5TRDFMZzJFTmQvM0xZbmxLb2NaaUdSK2tSMWc4MFdTQkpDY0dWT0gwZFRVVUx2bU94WC8xNzdVNTB3dVNJb290a25xZ0YyRVJwWWhseGNBQmlFUXpFWElMOTR6S2FtWlJ2aElDMEVvQVlJdlVTRTRUYUNpNXE2NDJmTVVmMkxmc2lUTEV1MHdWUWZsYkJQNkNtM1hOQWdNQkFBR2pnZ0VZTUlJQkZEQWZCZ05WSFNNRUdEQVdnQlFXT2FrYUJZbTNEeTJ5TmUzQ0NackZBNE1pUHpBU0JnTlZIU0FFQ3pBSk1BY0dCU3RNSFFFTE1JR3RCZ05WSFI4RWdhVXdnYUl3Z1orZ2daeWdnWm1HZ1pab2RIUndjem92TDJOaGMyOW5aV2x6ZG1sc0xuTnZaMlZwTG1sMEwyVnFZbU5oTDNCMVlteHBZM2RsWWk5M1pXSmthWE4wTDJObGNuUmthWE4wUDJOdFpEMWpjbXdtYVhOemRXVnlQVU5PSlRORVEwRXJUV2x1YVhOMFpYSnZLMlJsYkd4aEsxTmhiSFYwWlN0VVpYTjBKVEpEVHlVelJFMXBibWx6ZEdWeWJ5dGtaV3hzWVN0VFlXeDFkR1VsTWtOREpUTkVTVlF3SFFZRFZSME9CQllFRkozZFZqc0d3QXRKSGxkcC9wT09mVUpZeEM3Zk1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQXlHTnVLS0FZL25zQ1JMTS9LbDJaWEpjenVyYnN0eCtCKzIxTHI4YzQ3UThqbHFXUmdHcW9ZZW00ZEtZNnRndm03azZIS3lMallFUlVYeEJlV1FmQkVHM2RuWGczb2RqVTkvN08ySU43SWVwQmZNK2w4c2ZPSllPeTQ0bWFSV1Y5LzZXT0FMVkovenFjRG1WWktaNnM0RXZMR3N3QkRERk9ldVplbEVEVExENjhYUExyTm01RFNRdEczUnpJaVZMMTRYKzhJR0dyOVcvWmhhMWg1WGMrRSs0UDhlZDlLSTFSSm9xREg4a280NVY1dXNEL1VBeXB2ZFNXMlFPTEI2VnZTclJIay93MEZ5Sis5eFNEUFBKVi9XK2ZpcUZSNmk3MzM1ZTczZ05uVWpHVGVlbVVNbzg1NUx0WWZBcjRaM3ZNMFNiakZpYWRnamFCeC9jRGZ2dFlDS3EvMlI1WDFjUkpYS3k3cE9XeXZNQm5jQW92ZTZDWTY1SS9wTHhVZGxrMTgvRm9OWjJMSDhKaDNueHIycCtBWHNnUkVIMTF4UVNkTVhUSzl1Z2JXcTNaN3pONGlBL1E3TEV1bnJqQXRVdnRYR1JZTzdwRUdkeWNqVHRCZGJMT3B6VlYzQk9hMWhUUXFZSlFocC8zM2ExKzlXMVZWSTFCWG9IQUJtUk9EK3NYaVZXRUMwRmhHaVVmYU9TNUFsMFBxS1BWUnBlOTJObXI2ZFFjcjNJWHdIN1ZwT2RHaHBtSXBLMXhWMWFETXhhbTdzRDg0ZHM4cXZRNzhzWklhdTBSMmE4bjhyVElKZ0VBbk1wOGNnRHpNeFpLQ2tHcm91eFlCTnRISm90T0Izek4vMG5EQVl4UkIwWk9BN21EZ29TZ2hMYUNMb01kampMbjFIUWFJS1ZhOWFrPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJHUkxNU002MFIzMUY3NzBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBUFIiLCJwdXJwb3NlX29mX3VzZSI6IlVQREFURSIsImlzcyI6ImludGVncml0eTpTMSMwNTAjUkVHSU9ORVZFTkVUT1RFU1QiLCJsb2NhbGl0eSI6IlVMU1MgMiBNYXJjYSBUcmV2aWdpYW5hXl5eXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMS4zJklTT15eXl4wNTA1MDIiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlcnNpb24iOiIwNi4xOCIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUkVHSU9ORSBWRU5FVE8iLCJzdWJqZWN0X29yZ2FuaXphdGlvbl9pZCI6IjA1MCIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInBhdGllbnRfY29uc2VudCI6dHJ1ZSwiYWN0aW9uX2lkIjoiVVBEQVRFIiwicmVzb3VyY2VfaGw3X3R5cGUiOiIoJzYwNTkxLTVeXjIuMTYuODQwLjEuMTEzODgzLjYuMScpIiwiYXR0YWNobWVudF9oYXNoIjoiMjE0NWIwNjU4YmFhM2IzYTg4YTMyZDg2M2QyNDUxYmQyYWEwNWYyYjlhZWU4MjU3YTg4NDk0OWU0MWJiMWQ4MCIsInN1YmplY3RfYXBwbGljYXRpb25faWQiOiJNRURJQ08yMDAwIiwiZXhwIjoxNzMwNDU4NTIwLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlbmRvciI6Ik1lZGlhdGVjIEluZm9ybWF0aWNhIFMuci5sLiIsImlhdCI6MTczMDM3MjEyMCwianRpIjoiMTcyNzk2Mjc4NSIsInBlcnNvbl9pZCI6IlNRVFBSVjgwQTU0STc5OVReXl4mYW1wOzIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZhbXA7SVNPIn0.Bs0gKFCOpo_c9VhV327uPBxdC44aFhouki3wZj0XfCK_qUn-QAOX3ap9EAtr0K0nAy4riuit5ZTk9zeEU5GdQ3GB1xcU8kgRmcgF7rN6oHNh4CPiUMlrfZD4Qck-3Ibq0tFJpWM2UhqIfkEzUSy66wguZ8R5iqQHi_ZxDZXDFJoqDuJ23gA5l9zqm2VzYob5mhUCIFI_xN3o3xY8ysbygxsOlRv8gqFVax-SZvPY9iF7daaE_D4Y_4hJbCu570hDTRMQ60GPsMP8cYH5OF7cVIOIZ3k5EndSXiRzoJ2uDTzEJk2Dr6tKbzq8t2Ewl9e14Gj-CKVe-lOLN4XAcpJFjA

request body
{"assettoOrganizzativo": "AD_PSC130", "dataInizioPrestazione": "20240927000000", "healthDataFormat": "CDA", "identificativoDoc": "2.16.840.1.113883.2.9.2.50.4.4^20241031115520",  "identificativoRep": "2.16.840.1.113883.2.9.2.50.4.5.3", "identificativoSottomissione": "2.16.840.1.113883.2.9.2.50.4.20.20241031115550", "mode": "ATTACHMENT", "tipoAttivitaClinica": "OBS", "tipoDocumentoLivAlto": "SUM", "tipologiaStruttura": "Territorio", "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.5721bf93cd748cc87970b5f6ed060c83e2a7d980256096ab332a03bc16d146e8.0b35c5682a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId" }

ma otteniamo una risposta fuori standard:
{
    "status": 500
}

potete darci qualche informazione su quale possa essere il problema?
grazie

**Comment by vigliottim** [comment]
@ppalmerini 

Buongiorno,
riceviamo un esito negativo dalla chiamata di recupero riferimenti. 
Sono stati effettuati più tentativi: il primo con un errore interno, il secondo con PIT29. 
Vi chiediamo una verifica interna in quanto RDA.
Grazie.

**Comment by amarconS** [comment]
Confermiamo l'endpoint.

**Comment by ppalmerini** [comment]
Buonasera,
nonostante i diversi tentativi vediamo che l'ultima comunicazione ricevuta arrivata da questo IP 217.175.52.47  è delle 13:20 di oggi.
Potete darci un riscontro con maggiori dettagli?
Grazie

**Comment by g-maugeri-sogei** [comment]
Buonasera,
vedo divese chiamate sui log che ricevono soap fault.
 Qui un esempio:

```
2024-10-31 13:16:23,231 INFO [it.finanze.sogei.fse.client.headerHandler.HeaderHandler] - ---Header http--- 
2024-10-31 13:16:23,231 INFO [it.finanze.sogei.fse.client.headerHandler.HeaderHandler] - regione-rda : 050  
2024-10-31 13:16:23,231 INFO [it.finanze.sogei.fse.client.headerHandler.HeaderHandler] - endpoint-esterno : https://fser-test.regione.veneto.it/ini/recuperoRiferimentiDocume
nto  
2024-10-31 13:16:23,231 INFO [it.finanze.sogei.fse.client.headerHandler.HeaderHandler] - cache-control : no-store, no-cache, post-check=0, pre-check=0  
2024-10-31 13:16:24,294 INFO [it.finanze.sogei.fse.client.headerHandler.HeaderHandler] - HANDLE FAULT SOAP :
 
2024-10-31 13:16:24,296 INFO [it.finanze.sogei.fse.client.headerHandler.HeaderHandler] - <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:s=
"http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><SOAP-ENV:Body>
    <SOAP-ENV:Fault><SOAP-ENV:Code><SOAP-ENV:Value>SOAP-ENV:Receiver</SOAP-ENV:Value></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text xml:lang="it">Errore interno server</SOA
P-ENV:Text></SOAP-ENV:Reason><Detail xmlns="http://www.w3.org/2003/05/soap-envelope">
    <axis2ns9387:error xmlns:axis2ns9387="http://tempuri.org">
     <axis2ns9387:text>ERRORE #5002: Errore di ObjectScript: &lt;CLASS DOES NOT EXIST&gt;CSPDispatch+589^%SYS.cspServer *(No name)</axis2ns9387:text>
    </axis2ns9387:error>
</Detail></SOAP-ENV:Fault>
  </SOAP-ENV:Body></SOAP-ENV:Envelope> 


```

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta.
@ppalmerini La invitiamo a procedere con la riapertura in caso fosse necessario ulteriore supporto.
Grazie.
