### ISSUE TITLE
REGIONE BASILICATA UC9_Validazione e Pubblicazione: Notifica no ricevuta

### ISSUE THREAD

**Issue by BasilicataCrashProgramFSE** [ministero-salute/it-fse-support#1178]
Buongiorno,

Abbiamo effettuato un test di validate e pubblicazione (**UC_9**) contestuale ricevendo correttamente lo status 201 di presa in carico, pero non è ancora arrivata la notifica da ieri.

Di seguito i dettagli del caso di test: 
"identificativoDoc": "2.16.840.1.113883.2.9.2.170.4.4^201.AIRO.006012024000011_1",
"personFiscalCode": "PRVPVT81E03F052W",

{
    "code": "SUCCESS",
    "userMessage": "Operazione conclusa con successo",
    "systemMessage": "",
    "status": 201,
    "traceID": "91e3dbb34ea3d307",
    "spanID": "91e3dbb34ea3d307",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.1fd010a7e7fd293201672f4257468619e614df61c80054ccf754b280bc31e857.c6618346bf^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
    "timestamp": "2024-10-28T16:58:59.617Z" ...
}

Grazie mille

**Comment by vigliottim** [comment]
Buongiorno,
le confermiamo che il test ha avuto esito positivo.
In merito alla ricezione delle notifiche, sono in corso delle verifiche.
Grazie.

**Comment by g-maugeri-sogei** [comment]
Buonasera,
dovreste ripetere il test.
In caso d'errore ci occorre il CF, il timestamp e l'RDA verso cui pubblicate.

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,

Abbiamo riprovato con esito 201 ma la notifica non è arrivata.
Test case UC9: RDE=RDA
RDE: 170, Regione Basilicata
CF: PRVPVT81E03F052W
"identificativoDoc": "2.16.840.1.113883.2.9.2.170.4.4^201.AIRO.020022024000006_1",


{
    "traceID": "4e8360938b82c4ce",
    "spanID": "4e8360938b82c4ce",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.c90505716a36a7c1d81ec2dfa6d8f36f48d35c789587cc58b3db80f5c745b328.2a7f90b225^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
    "timestamp": "2024-10-30T14:54:32.062Z"
}

Grazie mille

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
a noi risulta che la transazione  con WIID=2.16.840.1.113883.2.9.2.170201.4.4.c90505716a36a7c1d81ec2dfa6d8f36f48d35c789587cc58b3db80f5c745b328.2a7f90b225^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

ha RDE=120. La natifica va verso il Lazio.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. 
@BasilicataCrashProgramFSE La invitiamo a procedere con riapertura in caso fosse necessario ulteriore supporto.
Grazie.
