### ISSUE TITLE
Risposta 400 BadRequest dal Gateway

### ISSUE THREAD

**Issue by gavesani-arbitek** [ministero-salute/it-fse-support#118]
Buongiorno, sono Giovanni Avesani di Arbitek, stiamo facendo i primi tentativi di connessione al Gateway per la validazione del cda.

Inviando una richiesta di verifica ricevo il seguente errore non meglio specificato {"type":"https://govway.org/handling-errors/400/BadRequest.html","title":"BadRequest","status":400,"detail":"Bad request","govway_id":"7cbe743c-b382-11ed-adb9-005056ae54fa"}

Per cortesia è possibile avere maggiori dettagli sull'errore riscontrato? 

Allego il file del log della request, contenente headers e body
[log.txt](https://github.com/ministero-salute/it-fse-support/files/10815621/log.txt)

A disposizione per chiarimenti

grazie
saluti

**Comment by masciamariotti** [comment]
Buon pomeriggio Giovanni,
da una prima analisi sembrerebbe che non stia inviando correttamente i dati contenuti nei JWT:
Authorization:
- sub: formato errato. esempio: "VRDMRC67T20I257E^^^&2.16.840.1.113883.2.9.4.3.2&ISO";
- aud: valore errato. valore corretto: "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1";
- iss: controllare il common name, sembra stia usando il certificato di autorizzazione (auth:**A1**#111ARBITEKXXXX). Per i token occorre utilizzare il certificato di signature (dovrebbe essere auth:**S1**#111ARBITEKXXXX)

FSE-JWT-Signature:
- locality: dovrebbe riportare solo una codifica;
- person_id: formato errato. Esempio: "RSSMRA75C03F839K^^^&2.16.840.1.113883.2.9.4.3.2&ISO";
- resource_hl7_type: formato errato. Esempio: "('11502-2^^2.16.840.1.113883.6.1')";
- iss: valore errato. Dovrebbe essere valorizzato con integrity (auth:S1#111ARBITEKXXXX --> integrity:S1#111ARBITEKXXXX);
- aud: valore errato. valore corretto: "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1";
- patient_consent: è un booleano, invece sta arrivando come stringa;
- sub: campo obbligatorio mancante;
- subject_application_id: campo obbligatorio mancante;
- subject_application_vendor: campo obbligatorio mancante;
- subject_application_version: campo obbligatorio mancante.

Per ulteriori dettagli la invitiamo a far riferimento alla [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#111-campi-contenuti-nei-jwt).
Ci faccia sapere se il problema persiste.

**Comment by gavesani-arbitek** [comment]
Buongiorno, 
grazie per le indicazioni, ho corretto tutti i punti ma permane l'errore
{"type":"https://govway.org/handling-errors/400/BadRequest.html","title":"BadRequest","status":400,"detail":"Bad request","govway_id":"b9193651-b41a-11ed-a9a6-005056ae7395"}

Allego nuovamente il log
[log.txt](https://github.com/ministero-salute/it-fse-support/files/10822681/log.txt)

Attendo cortese riscontro
grazie

**Comment by masciamariotti** [comment]
Buongiorno Giovanni,
potrebbe fornire il timestamp di quando è stato effettuato il test?
Grazie.

**Comment by gavesani-arbitek** [comment]
è stato effettuato oggi 24/02/2023 alle 10:29:55

**Comment by IStacchiotti** [comment]
Buongiorno, grazie per il riscontro. Potrebbe cortesemente ritentare e comunicarci il nuovo govway id restituito dal sistema? Grazie mille.

**Comment by gavesani-arbitek** [comment]
buongiorno, provato alle 11:27:48, la risposta è la seguente

{"type":"https://govway.org/handling-errors/400/BadRequest.html","title":"BadRequest","status":400,"detail":"Bad request","govway_id":"664a6e40-b686-11ed-adb9-005056ae54fa"}

allego il log
[log.txt](https://github.com/ministero-salute/it-fse-support/files/10838631/log.txt)

grazie

**Comment by masciamariotti** [comment]
Buon pomeriggio Giovanni,
da ulteriori analisi abbiamo riscontrato 2 errori:
1. Nell' header c'è un typo nel parametro Content-Type: multipart/form-data; boundary==--dd1679c0fdf68d1b1ccc6ac9b41f429ca763af43 (c'è un doppio "=" dopo boundary, mentre dovrebbe essere soltanto 1);
2. Nel requestBody sta inviando parametri non accettati dal servizio di validazione. Gli unici consentiti, come da [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#3-servizio-di-validazione), sono
 - healthDataFormat
 - mode
 - activity
 
 Ci faccia sapere se il problema persiste.

**Comment by gavesani-arbitek** [comment]
Buongiorno, ha fatto un nuovo tentativo alle 27/02/2023 15:38:41 con risposta {"traceID":"193b62c56379883e","spanID":"193b62c56379883e","type":"/msg/generic-error","title":"Errore generico.","detail":"Index: 0, Size: 0","status":500,"instance":""}

Allego il log
[log.txt](https://github.com/ministero-salute/it-fse-support/files/10840751/log.txt)


grazie

**Comment by IStacchiotti** [comment]
Grazie per il feedback. Potrebbe cortesemente allegare il file pdf con il cda iniettato che è stato utilizzato nella chiamata?

**Comment by gavesani-arbitek** [comment]
Certo, allego il pdf richiesto
[R202302070813.5.pdf](https://github.com/ministero-salute/it-fse-support/files/10841161/R202302070813.5.pdf)

**Comment by gavesani-arbitek** [comment]
Buongiorno, ho provato correggendo il parametro filename ma mi veniva comunque rispostoi lo stesso errore generico. Levando invece del tutto il paremetro filename, nel tentativo delle 10:15:47 mi è stato risposto

28/02/2023 10:15:47: SendVerificaGateway - RISPOSTA: {"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"e8f7f0f2-b73b-11ed-a9a6-005056ae7395"}

allego il log
[log.txt](https://github.com/ministero-salute/it-fse-support/files/10848501/log.txt)


Il parametro filename è necessario? Se si, deve essere valorizzato con @ o senza?
Il file pdf vi risulta correttamente inviato nella request?

grazie

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che il parametro _filename_ è necessario e deve essere valorizzato senza "@". Le chiediamo cortesemente di riprovare popolando il parametro come indicato di seguito filename="R202302070813.5.pdf" e di allegare successivamente sia la request che la response se il problema persiste.

**Comment by gavesani-arbitek** [comment]
grazie per le indicazioni

nuovo tentativo delle 10:59:29 con filename "202302070813.005.pdf", risposta {"traceID":"7fcd5be3fa2e8aaa","spanID":"7fcd5be3fa2e8aaa","type":"/msg/generic-error","title":"Errore generico.","detail":"Index: 0, Size: 0","status":500,"instance":""}

allego il log
[log.txt](https://github.com/ministero-salute/it-fse-support/files/10848948/log.txt)

grazie

**Comment by IStacchiotti** [comment]
Buon pomeriggio, riportiamo di seguito l'esito delle analisi svolte:

1. L'allegato cda.xml (estratto dal .pdf) dichiara nel prologo una codifica ISO-8859-1 ma il suo contenuto è stato codificato in UTF-16LE, questo non permette una corretta lettura dei dati. Il file DEVE essere codificato come dichiarato nell'intestazione XML, consigliamo, come nota, l'utilizzo della codifica UTF-8 per essere sicuri di una compatibilità piena.
2. Il file allegato utilizza uno schema sintattico ad oggi non gestito, ovvero "POCD_HD000040", è necessario adeguare il CDA all'utilizzo dello schema "POCD_MT000040UV02" il quale è attualmente in uso sul gateway.
3. Abbiamo ragione di credere che il codice fiscale utilizzato nella richiesta non coincida con quello dichiarato nel CDA, invitiamo a ricontrollare.

Grazie

**Comment by gavesani-arbitek** [comment]
buongiorno

L'invio del referto utilizzato fin qui è andato a buon fine, grazie per l'analisi.

Ho però provato poco fa con un referto più complesso ed ho ricevuto l'errore
{
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "status": 502,
    "detail": "Invalid response received from the API Implementation",
    "govway_id": "4781fa82-c192-11ed-a9a6-005056ae7395"
}


Allego log di comunicazione
[log.txt](https://github.com/ministero-salute/it-fse-support/files/10957732/log.txt)

Resto in attesa di un cortese riscontro,
grazie

**Comment by IStacchiotti** [comment]
Buongiorno, riportiamo in allegato gli errori che sono stati registrati a sistema. 
[Log_#118.txt](https://github.com/ministero-salute/it-fse-support/files/10988869/Log_.118.txt)

**Comment by IStacchiotti** [comment]
Buon pomeriggio, non avendo ricevuto ulteriori feedback, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
