### ISSUE TITLE
crash-program. errore ricerca e sostituzione documento

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#1184]
Buonasera,
sto eseguendo la sostituzione di un documento con il servizio FSE1.0 con l'endpoint
**https://fseservicetest.sanita.finanze.it/FseInsServicesWeb/services/fseComunicazioneMetadati**

Ho avuto degli errori  e dalle 15:40 non riesco più ad accedere al vecchio documento. La ricerca documento mi risponde:
_"Il recupero riferimenti non ha prodotto risultati"_

Questa la request:
```
<RicercaDocumentiRichiesta >
  <IdentificativoUtente >PROVAX00X00X000Y</IdentificativoUtente>
  <pinCode >dr2IvMmfXB+uJFxN6YOy1UMP4DQmeFKMLZagwfRlXO8Vc4SHC6XDPTr/SdB2W79L
2Z8oxFrobcJAtchH9ZVyFt3d/Urc3lzzwRotdVKLaPDUoaYlPt6dunL6xTXCHsgE
uh5AeeYV15O6nhGwTXZQJOsmH+98rWL3RP5yyntrgi8=
</pinCode>
  <IdentificativoOrganizzazione >130</IdentificativoOrganizzazione>
  <StrutturaUtente >202123456</StrutturaUtente>
  <RuoloUtente >DRS</RuoloUtente>
  <ContestoOperativo >UPDATE</ContestoOperativo>
  <IdentificativoAssistito >DNNBZZ60A43A345K</IdentificativoAssistito>
  <PresaInCarico >true</PresaInCarico>
  <IdentificativoDocumento >2.16.840.1.113883.2.9.2.130.4.4^497255</IdentificativoDocumento>
  <IdentificativoApplicativoRichiedente >SISWeb</IdentificativoApplicativoRichiedente>
  <FornitoreApplicativoRichiedente >IASI S.r.l</FornitoreApplicativoRichiedente>
  <VersioneApplicativoRichiedente >2.4.8</VersioneApplicativoRichiedente>
  <OpzioniRisposta >ObjectRef</OpzioniRisposta>
</RicercaDocumentiRichiesta>
```
endpoint:
**https://fseservicetest.sanita.finanze.it/FseInsServicesWeb/services/fseRicercaDocumenti**

Fino alle 12:00 di questa mattina non avevo problemi e la ricerca mi restituiva il documento.
Potete verificare?
Grazie

**Comment by vigliottim** [comment]
Buonasera, per errori relativi al FSE 1.0 dovrebbe scrivere al seguente indirizzo e-mail: gestionets@sogei.it
Poiché nel titolo ha indicato "crash program", la informiamo che le chiamate vanno indirizzate ai servizi esposti dal FSE 2.0 (deployato in ambiente di test), secondo le riportate specifiche al link: [Documentazione Crash Program](https://ministero-salute.github.io/it-fse-support/crashprogram/)
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by alessandropassamonti** [comment]
Aggiungo anche che il servizio di esitoCaricamentoDocumento impiega molto tempo prima di dare un esito, anche ore.
In questo modo i tempi si allungano notevolmente.

Inoltre, in risposta alla mail delle 16:31, preciso che le regioni in sussidiarietà che partecipano al crash-program devono utilizzare i servizi FSE 1.0  per i servizi di creazione e sostituzione come da specifiche avute da sogei 

Grazie

**Comment by alessandropassamonti** [comment]
buonasera,
Grazie provo con una nuova pubblicazione e sostituzione sperando che non si verifiche nuovamente il problema.

Per l'esitoCaricamentoDocumento intendo precisare che  il servizio risponde in tempi brevi mentre  l'esito OK  non torna in tempi ragionevoli. 

Questa richiesta
```
<EsitoCaricamentoDocumentoRichiesta 
  <IdentificativoUtente >PROVAX00X00X000Y</IdentificativoUtente>
  <pinCode >SkNGpmJrKY179+SIfuz5TXXohPqvnGLx5YnzObdIGf291M1PEGMYEk+8SICcElv7
LjHH6Y4T5aBPATn9NaVhnGuV1Do/mX/+mLqTWGuQSHKSyTz0w3eEfaE0SNuk9Edl
dcAE8+FlvkUViVbTkDOS6dZK+Qm5RE3t3Nq+0EKLC6E=
</pinCode>
  <IdentificativoOrganizzazione >130</IdentificativoOrganizzazione>
  <StrutturaUtente >202123456</StrutturaUtente>
  <RuoloUtente >DRS</RuoloUtente>
  <IdentificativiTemporaneiDocumenti >TEMP_130_2377434</IdentificativiTemporaneiDocumenti>
  <DataRicercaDA >20241029163600</DataRicercaDA>
  <DataRicercaA >20241029163600</DataRicercaA>
</EsitoCaricamentoDocumentoRichiesta>

```
continua a restituire l'esito ELAB da oltre 2 giorni. Perché?

Grazie

**Comment by g-maugeri-sogei** [comment]
"Per l'esitoCaricamentoDocumento intendo precisare che il servizio risponde in tempi brevi mentre l'esito OK non torna in tempi ragionevoli."

Confermo che dipende dai test di carico.

**Comment by alessandropassamonti** [comment]
allora riproverò lunedì perchè ho provato pochi minuti fa e l'esito è ancora ELAB

**Comment by alessandropassamonti** [comment]
Buongiorno
l'esito del documento pubblicato il 29/10 restituisce ancora ELAB

```
<EsitoCaricamentoDocumentoRichiesta 
  <IdentificativoUtente >PROVAX00X00X000Y</IdentificativoUtente>
  <pinCode >SkNGpmJrKY179+SIfuz5TXXohPqvnGLx5YnzObdIGf291M1PEGMYEk+8SICcElv7
LjHH6Y4T5aBPATn9NaVhnGuV1Do/mX/+mLqTWGuQSHKSyTz0w3eEfaE0SNuk9Edl
dcAE8+FlvkUViVbTkDOS6dZK+Qm5RE3t3Nq+0EKLC6E=
</pinCode>
  <IdentificativoOrganizzazione >130</IdentificativoOrganizzazione>
  <StrutturaUtente >202123456</StrutturaUtente>
  <RuoloUtente >DRS</RuoloUtente>
  <IdentificativiTemporaneiDocumenti >TEMP_130_2377434</IdentificativiTemporaneiDocumenti>
  <DataRicercaDA >20241029163600</DataRicercaDA>
  <DataRicercaA >20241029163600</DataRicercaA>
</EsitoCaricamentoDocumentoRichiesta>
```

**Comment by alessandropassamonti** [comment]
Buongiorno,
ho pubblicato un nuovo documento e dopo circa 20 minuti è tornato esito OK (TEMP_130_2464586,2.16.840.1.113883.2.9.2.130.4.4^497285).

Ho provato la sostituzione del documento (che fallisce) e ora non trovo più il vecchio documento

Questa la richiesta di ricercaDocumento:
```
<RicercaDocumentiRichiesta >
  <IdentificativoUtente >PROVAX00X00X000Y</IdentificativoUtente>
  <pinCode >La2OmUrLyweTW8v5y4/5bQsin7h5mnZZx0vRKkJS2/SeQyMFgEPp0GvLcSDbJqSu
y7/m1HlTnwUvlomHH99TVr+njxLkQigNALpqbg5pnsh/Ia4t6Xq6SvGGDlugF/0c
s52DRtJoj1X6cM9Fpxn9bhYxcoyo0BAkudhgxnMmh20=
</pinCode>
  <IdentificativoOrganizzazione >130</IdentificativoOrganizzazione>
  <StrutturaUtente >202123456</StrutturaUtente>
  <RuoloUtente >DRS</RuoloUtente>
  <ContestoOperativo >TREATMENT</ContestoOperativo>
  <IdentificativoAssistito >DNNBZZ60A43A345K</IdentificativoAssistito>
  <PresaInCarico >true</PresaInCarico>
  <IdentificativoDocumento >2.16.840.1.113883.2.9.2.130.4.4^497285</IdentificativoDocumento>
  <IdentificativoApplicativoRichiedente >SISWeb</IdentificativoApplicativoRichiedente>
  <FornitoreApplicativoRichiedente >IASI S.r.l</FornitoreApplicativoRichiedente>
  <VersioneApplicativoRichiedente >2.4.8</VersioneApplicativoRichiedente>
</RicercaDocumentiRichiesta>
```
Grazie

**Comment by g-maugeri-sogei** [comment]
Buonasera,
potete allegare qui la request e la response relativa alla pubblicazione del documento che va in sostituzione ?

**Comment by alessandropassamonti** [comment]
buonasera, 
allego la request ma non ho la response perchè mi viene restituito un errore del tipo 

> "**Parte MIME con Content-ID '&lt;http://tempuri.org/0&gt;' non trovata**"

sto cercando di capire l'origine di questo errore.
[REQ.txt](https://github.com/user-attachments/files/17633926/REQ.txt)

**Comment by g-maugeri-sogei** [comment]
Nella request non trovo il tag <tip:IdentificativoDocumento> che dovrebbe contenere il riferimento al documento da sostituire, esempio:
 <tip:IdentificativoDocumento>2.16.840.1.113883.2.9.2.130.4.4^475633</tip:IdentificativoDocumento>.

Non credo che l'errore sopra riportato sia dovuto a questo. Riuscite a verificare cosa vi arriva in response a basso livello sul socket TCP ?
Tra i controlli eseguiti sulla request ci sono anche quelli posizionali sui campi del messaggio. Se i controlli falliscono,
il reverse proxy che valida la request potrebbe semplicemente chiudere il socket.

**Comment by alessandropassamonti** [comment]
buongiorno.
ci sono novità?

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
non vedo in RES_replace.txt il campo IdentificativoDocumento.
Allego un esempio completo funzionate.
[replace_request_example.txt](https://github.com/user-attachments/files/17675866/replace_request_example.txt)

**Comment by alessandropassamonti** [comment]
Buongiorno.
Grazi, ho modificato il messaggio seguendo la request di esempio ma ho ancora errore 500
```
<env:Envelope xmlns:env='http://schemas.xmlsoap.org/soap/envelope/'>
<env:Body>
<env:Fault>
<faultcode>env:Client</faultcode>
<faultstring>Internal Error</faultstring>
</env:Fault>
</env:Body>
</env:Envelope>
```
allego la request usata

[request_replace_abruzzo.txt](https://github.com/user-attachments/files/17677031/request_replace_abruzzo.txt)

Grazie

**Comment by alessandropassamonti** [comment]
Sono riuscito a sostituire il documento
Grazie

**Comment by alessandropassamonti** [comment]
buonasera, potete darmi riscontro su questo problema? é bloccante

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
l'errore 1173 indica che la struttura dell'autore del documento non coincide con la struttura dell'utente.

**Comment by alessandropassamonti** [comment]
Buongiorno,
non capisco, ho sempre usato il codice 130202123456, e infatti la pubblicazione funziona. Come ma i la sostituzione no? 
Potete darmi maggiori informazioni? il problema è bloccante.

**Comment by alessandropassamonti** [comment]
buongiorno.
Ci sono novità?

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
abbiamo individuato il problema. Stiamo lavorando alla risoluzione.

**Comment by alessandropassamonti** [comment]
buongiorno,
ci sono novità?

**Comment by g-maugeri-sogei** [comment]
Buonasera,
abbiamo rilasciato un aggiornamento che dovrebbe risolvere il problema.
Potere svolgere un nuovo test e darci conferma ?

**Comment by alessandropassamonti** [comment]
buongiorno.
ho eseguito una nuova pubblicazione perchè il precedente documento sembra non esistere più.
la pubblicazione sembrerebbe ok, come confermato dalla status del Gtw, ma lo stato rimane ancora in ELAB
Potete controllare?

allego la status del Gtw

grazie
[status_pubblicazione_regione_abruzzo.json](https://github.com/user-attachments/files/17867436/status_pubblicazione_regione_abruzzo.json)

**Comment by alessandropassamonti** [comment]
buonasera,
ho fatto una nuova pubblicazione

allego la comunicazione metadati
[pubblicazione_primodocumento_regione_abruzzo.txt](https://github.com/user-attachments/files/17871071/pubblicazione_primodocumento_regione_abruzzo.txt)

**Comment by alessandropassamonti** [comment]
@g-maugeri-sogei  ora lo stato dell'ultimo documento pubblicato è OK.
ora provo con la sostituzione

**Comment by alessandropassamonti** [comment]
@g-maugeri-sogei  la sostituzione restituisce errore
```
ComunicazioneMetadatiRicevuta >
  <Esito xmlns="http://comunicazionemetadatiricevuta.xsd.fse.ini.finanze.it">9999</Esito>
  <ElencoErrori xmlns="http://comunicazionemetadatiricevuta.xsd.fse.ini.finanze.it">
    <Errore >
      <codEsito>9000</codEsito>
      <esito>9999 - </esito>
      <tipoErrore>Bloccante</tipoErrore>
      <fonte>FSE-INS-GATEWAY</fonte>
    </Errore>
  </ElencoErrori>
</ComunicazioneMetadatiRicevuta>
```

stesso errore ricevuto per le sostituzioni verso Basilicata  e Calabria

allego la comunicazioneMetadati
[pubblicazione_sostituzione_regione_abruzzo.txt](https://github.com/user-attachments/files/17871598/pubblicazione_sostituzione_regione_abruzzo.txt)

**Comment by g-maugeri-sogei** [comment]
@alessandropassamonti sto provando a testare il documento in locale.
Ti aggiorno appena trovo il problema.

**Comment by alessandropassamonti** [comment]
buongiorno @g-maugeri-sogei ,
in realtà l'errore lo restituisce la ricercaDocumenti utilizzata per il recupero del riferimentoDocumento

```
<RicercaDocumentiRichiesta >
  <IdentificativoUtente>PROVAX00X00X000Y</IdentificativoUtente>
  <pinCode>P+8pEQVP5asLKjr7V7SHp6K2FOFvc/UkVC1bmOb4cL8XEBaE6WWGw3qnjbpt6hcK
Sm+jrPSIijnNen12e2bde+Xgsf/vXDIEBmmCs80GSmGHaw+HpCSZihGyHK3SOS9+
tSihYwnzu4o6IxCvWFeI4MVyuOG86XHNw97ymyoIB6M=
</pinCode>
  <IdentificativoOrganizzazione>130</IdentificativoOrganizzazione>
  <StrutturaUtente>202123456</StrutturaUtente>
  <RuoloUtente>DRS</RuoloUtente>
  <ContestoOperativo>UPDATE</ContestoOperativo>
  <IdentificativoAssistito>CRSMRM80A01G478X</IdentificativoAssistito>
  <PresaInCarico>true</PresaInCarico>
  <IdentificativoDocumento>2.16.840.1.113883.2.9.2.130.4.4^497304</IdentificativoDocumento>
  <IdentificativoApplicativoRichiedente>SISWeb</IdentificativoApplicativoRichiedente>
  <FornitoreApplicativoRichiedente>IASI S.r.l</FornitoreApplicativoRichiedente>
  <VersioneApplicativoRichiedente>2.4.8</VersioneApplicativoRichiedente>
  <OpzioniRisposta>ObjectRef</OpzioniRisposta>
</RicercaDocumentiRichiesta>
```



```
<RicercaDocumentiRicevuta  >
  <Esito >9999</Esito>
  <ElencoErrori >
    <Errore >
      <codEsito>2061</codEsito>
      <esito>Internal Error - Impossibile contattare RDA</esito>
      <tipoErrore>Bloccante</tipoErrore>
      <fonte>FSE-INS-BE</fonte>
    </Errore>
  </ElencoErrori>
</RicercaDocumentiRicevuta>
```

**Comment by alessandropassamonti** [comment]
buongiorno @g-maugeri-sogei ,
ora la ricercaDocumenti restituisce i riferimenti ma ho errore in pubblicazione.
di seguito request e response:

```
<ComunicazioneMetadatiRichiesta >
  <IdentificativoUtente >PROVAX00X00X000Y</IdentificativoUtente>
  <pinCode >L176DJFx0REnJ3neVr14wQO25lrmUEMZJJJPN1W7lTzff2+2zdOFN7313Lar+RcJ
4lWu8KyO0Japs5VSZA524ed/mt3dKTmbc2uLuyosJ37B8qqYnsWJ+x/T/c7kTHSt
wpzOsoc4u4o0R5yjYQuXtNy8mG0kHv77O39N4bTdldk=
</pinCode>
  <IdentificativoOrganizzazione >130</IdentificativoOrganizzazione>
  <StrutturaUtente >202123456</StrutturaUtente>
  <RuoloUtente >DRS</RuoloUtente>
  <ContestoOperativo >TREATMENT</ContestoOperativo>
  <IdentificativoAssistito >DNNBZZ60A43A345K</IdentificativoAssistito>
  <PresaInCarico >true</PresaInCarico>
  <TipoAttivita >CREATE</TipoAttivita>
  <Metadato >
    <TipologiaStrutturaProdDoc >Territorio</TipologiaStrutturaProdDoc>
    <TipoMime >application/pdf+text/x-cda-r2+xml</TipoMime>
    <LivelloConfidenzialita >N</LivelloConfidenzialita>
    <TipologiaDocumentoAlto >REF</TipologiaDocumentoAlto>
    <TipologiaDocumentoMedio >11488-4</TipologiaDocumentoMedio>
    <TipologiaDocumentoBasso >2.16.840.1.113883.2.9.10.1.9.1</TipologiaDocumentoBasso>
    <RiferimentoDocumento >urn:uuid:urn:uuid:859708f7-80ee-4258-88aa-bdce9e3b2407</RiferimentoDocumento>
    <Associazione >
      <associationType>urn:ihe:iti:2007:AssociationType:RPLC</associationType>
      <sourceObject>doc1</sourceObject>
      <targetObject>urn:uuid:urn:uuid:859708f7-80ee-4258-88aa-bdce9e3b2407</targetObject>
      <submissionSetStatus>Original</submissionSetStatus>
    </Associazione>
    <IdentificativoUnivocoDocumento >doc1</IdentificativoUnivocoDocumento>
    <DataValidazioneDocumento >20241122152800</DataValidazioneDocumento>
    <RuoloAutore >DRS</RuoloAutore>
    <IstituzioneAutore >130202123456</IstituzioneAutore>
    <CodiceFiscaleAutore >PROVAX00X00X000Y</CodiceFiscaleAutore>
    <SpecialitaAutore >Spec</SpecialitaAutore>
    <AssettoOrganizzativo >AD_PSC008</AssettoOrganizzativo>
    <TipoAttivitaClinica >ERP</TipoAttivitaClinica>
    <DataInizioPrestazione >20241122000000</DataInizioPrestazione>
    <DataFinePrestazione >20241122000000</DataFinePrestazione>
    <DocumentoFirmato >true^Documento firmato</DocumentoFirmato>
  </Metadato>
  <documento ></documento>
  <IdentificativoApplicativoRichiedente >SISWeb</IdentificativoApplicativoRichiedente>
  <FornitoreApplicativoRichiedente >IASI S.r.l</FornitoreApplicativoRichiedente>
  <VersioneApplicativoRichiedente >2.4.8</VersioneApplicativoRichiedente>
  <OpzioniRequest >
    <chiave >GATEWAY</chiave>
    <valore >true</valore>
  </OpzioniRequest>
  <OpzioniRequest >
    <chiave >WORKFLOWINSTANCEID</chiave>
    <valore >2.16.840.1.113883.2.9.2.130202.4.4.d84d0220c308350152c77418d2a5ee5d9f08179d2f58084eb185ec510f42ea14.6c5f33cde1^^^^urn:ihe:iti:xdw:2013:workflowInstanceId</valore>
  </OpzioniRequest>
  <OpzioniRequest >
    <chiave >MODE</chiave>
    <valore >ATTACHMENT</valore>
  </OpzioniRequest>
</ComunicazioneMetadatiRichiesta>

```

```
<ComunicazioneMetadatiRicevuta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Esito xmlns="http://comunicazionemetadatiricevuta.xsd.fse.ini.finanze.it">9999</Esito>
  <ElencoErrori xmlns="http://comunicazionemetadatiricevuta.xsd.fse.ini.finanze.it">
    <Errore xmlns="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it">
      <codEsito>9000</codEsito>
      <esito>9999 - </esito>
      <tipoErrore>Bloccante</tipoErrore>
      <fonte>FSE-INS-GATEWAY</fonte>
    </Errore>
  </ElencoErrori>
</ComunicazioneMetadatiRicevuta>
```
grazie

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
abbiamo risolto il problema relativo alla sostituzione documento.

**Comment by alessandropassamonti** [comment]
Buongiorno,
confermo che ora la sostituzione non da più errore.
Ora il documento è in stato ELAB. 
Attendo  l'esito OK prima di chiudere la issue

@g-maugeri-sogei  posso provare anche vero le altre regioni?
Grazie

**Comment by g-maugeri-sogei** [comment]
Direi di si.

**Comment by alessandropassamonti** [comment]
ho provato con le altre regioni ma continuo ad avere l'errore nella ricercaDocumenti per il recupero del riferimentoDocumento
```
<RicercaDocumentiRichiesta>
  <IdentificativoUtente >PROVAX00X00X000Y</IdentificativoUtente>
  <pinCode >qux//AthobhKhlMmtEpa0JBj9aZidtzZ0j9LaZbZJf0aCrsiPhfGYuxWS4GYSZpU
oA4sIDtudiNd3yYknHjAVfDRZHRJaC+BRdmWk17qvR+PqTsrGlaBYqoT61VHys0A
vLBpkmkKtepp/LfiBinKmsORamb5Fa0wUxRrlzdbxKI=
</pinCode>
  <IdentificativoOrganizzazione >130</IdentificativoOrganizzazione>
  <StrutturaUtente >202123456</StrutturaUtente>
  <RuoloUtente >DRS</RuoloUtente>
  <ContestoOperativo >UPDATE</ContestoOperativo>
  <IdentificativoAssistito >CRSMRM80A01G478X</IdentificativoAssistito>
  <PresaInCarico >true</PresaInCarico>
  <IdentificativoDocumento >2.16.840.1.113883.2.9.2.130.4.4^497304</IdentificativoDocumento>
  <IdentificativoApplicativoRichiedente >SISWeb</IdentificativoApplicativoRichiedente>
  <FornitoreApplicativoRichiedente >IASI S.r.l</FornitoreApplicativoRichiedente>
  <VersioneApplicativoRichiedente >2.4.8</VersioneApplicativoRichiedente>
  <OpzioniRisposta >ObjectRef</OpzioniRisposta>
</RicercaDocumentiRichiesta>
```

```
<RicercaDocumentiRicevuta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Esito xmlns="http://ricercadocumentiricevuta.xsd.fse.ini.finanze.it">9999</Esito>
  <ElencoErrori xmlns="http://ricercadocumentiricevuta.xsd.fse.ini.finanze.it">
    <Errore xmlns="http://tipodatiricercadocumenti.xsd.fse.ini.finanze.it">
      <codEsito>2061</codEsito>
      <esito>Internal Error - Impossibile contattare RDA</esito>
      <tipoErrore>Bloccante</tipoErrore>
      <fonte>FSE-INS-BE</fonte>
    </Errore>
  </ElencoErrori>
</RicercaDocumentiRicevuta>
```

questo per tutte le regioni ad eccezione di Regione Abruzzo e Regione Piemonte

**Comment by alessandropassamonti** [comment]
@g-maugeri-sogei  aggiungo che da circa un'ora non riesco più a pubblicare con utente PROVAX00X00X000Y ma solo con la mia CNS

**Comment by g-maugeri-sogei** [comment]
Il servizio di ricerca documenti e' stato ripristinato.

**Comment by alessandropassamonti** [comment]
confermo, sono riuscito a pubblicare le sostituzioni
