### ISSUE TITLE
Crash Program - Regione Molise - UC6  HTTP/1.1 500 Internal Server Error

### ISSUE THREAD

**Issue by marlagatta** [ministero-salute/it-fse-support#1185]
Salve.

Eseguendo dei test UC6 sostituzione documento, con RDA=Molise ed RDE=Sardegna oppure Lazio, stiamo ricevendo dal gateway una risposta d'errore generica

```
HTTP/1.1 500 Internal Server Error
X-Backside-Transport: FAIL FAIL
Connection: Keep-Alive
Transfer-Encoding: chunked
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
set-cookie: 894d46ecfc124039ee218b63c12a3329=23a2f3f923947b3a8799547752028714; path=/; HttpOnly; Secure; SameSite=None
Server: GovWay-SOGEI
Pragma: no-cache
GovWay-Message-ID: afca1b6e-ba94-4bf4-9eb8-0dc6fc113865
GovWay-Transaction-ID: 996c17bb-9607-11ef-808a-005056ae7395
server-timing: intid;desc=c84965f6225ea0df
content-disposition: inline;filename=f.txt
Date: Tue, 29 Oct 2024 15:22:16 GMT
Vary: *
X-Content-Type-Options: nosniff
Content-Type: application/problem+json
X-Global-Transaction-ID: 6026e6bc6720fda7e474f0ff
{"status":500}


```

**Comment by FSESardegna** [comment]
Buongiorno,
anche noi stiamo rilevando difficoltà nell'interrogazione del gateway. Procederemo con l'apertura di una issue per verificare se questa possa essere la causa dell'errore che state riscontrando anche voi.
Se desiderate, potete inoltrarci ulteriori dettagli (ad esempio DocumentEntry.uniqueId) così da consentirci di verificare i nostri log e approfondire la situazione.
@marlagatta

**Comment by marlagatta** [comment]
Salve. La transazione UC6 riprovando ha avuto esito positivo,
l'uniqueId e' 2.16.840.1.113883.2.9.2.140.4.4^202410270012002
Ora pero' e' la verifica stato per workflowInstanceId che non funziona: 

per "workflowInstanceId":"2.16.840.1.113883.2.9.2.140.4.4.bb756c52fb26d93963040d73e3721e169011809e7160024dc1be2a69aefb88d6.d5e24b9142^^^^urn:ihe:iti:xdw:2013:workflowInstanceId" 

restituisce 

`{"traceID":"d53ded93e72093cf","spanID":"d53ded93e72093cf","type":"/msg/generic-error","title":"Errore generico.","detail":"Errore generico","status":500,"instance":""}`

mentre per "traceId": "05d7af2585a25c75"

restituisce

```
{
   "traceID": "be84f3d22581d943",
   "spanID": "823892bb4028b5f9",
   "transactionData": [   {
      "eventType": "REPLACE",
      "eventDate": "2024-10-29T17:12:16.677+01:00",
      "eventStatus": "SUCCESS",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.140.4.4^202410270012002",
      "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "tipoAttivita": "DIS",
      "organizzazione": "140",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.140.4.4.bb756c52fb26d93963040d73e3721e169011809e7160024dc1be2a69aefb88d6.d5e24b9142^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "05d7af2585a25c75",
      "issuer": "integrity:S1#140#REGIONEMOLISETEST",
      "expiringDate": "2025-10-29T17:12:16.709+01:00"
   }]
}

```

**Comment by marlagatta** [comment]
Ora la verifica esito restituisce 

{"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"4b792c32-9610-11ef-a4d1-005056ae54fa"}

**Comment by vigliottim** [comment]
Buonasera,
potreste cortesemente riprovare?
Grazie.

**Comment by marlagatta** [comment]
Riprovato, funziona perfettemente. Grazie.
