### ISSUE TITLE
Errore Verifica stato transazione

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#1186]
Buongiorno,
segnaliamo che, invocando il servizio di esito stato transazione per workflowInsaceId, riscontriamo il seguente errore:

`ErrorMessage: ErrorDto(traceID=f295716c59a31aec, spanID=f295716c59a31aec, workflowInstanceId=null, type=/msg/generic-error, title=Errore generico., status=500, detail=Errore generico, instance=, govwayId=null)`

Potete fornirci maggiori dettagli in merito?
Grazie.

**Comment by vigliottim** [comment]
Buonasera,
la invitiamo a riprovare, l'anomalia dovrebbe essere rientrata.
In caso contrario, restiamo a disposizione.
Grazie.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso in cui sia necessario ulteriore supporto.
Grazie.
