### ISSUE TITLE
Compilazione Checklist e Pull Request

### ISSUE THREAD

**Issue by PieroDal** [ministero-salute/it-fse-support#1187]
Salve, dove trovo l'informazione per riempire la colonna "Timestamp" della Checklist ?
Per caricare il risultato del test ho letto che bisogna fare una pull request ma anche leggendo la documentazione non riesco a capire come fare, prostete aiutarmi con esempi semplici ?

**Comment by vigliottim** [comment]
Buonasera, 
può riempire la colonna _"Timestamp"_ della checklist inserendo il valore contenuto in _eventDate_.
Può recuperarlo chiamando, ad esempio, il servizio _status_: 

- _Servizio di Recupero Stato Transazione per TraceId:_ https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#11-servizio-di-recupero-stato-transazione-per-traceid
- _Servizio di Recupero Stato Transazione per WorkflowInstanceId:_ https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#10-servizio-di-recupero-stato-transazione-per-workflowinstanceid

<img width="306" alt="image" src="https://github.com/user-attachments/assets/17728074-a97a-4d0a-9a95-a09425f82e06">

Di seguito le alleghiamo dei link con indicazioni relative alla creazione della pull-request:

- _Documentazione pull-request:_ https://github.com/ministero-salute/it-fse-accreditamento#pull-request
- _Pull-request:_ https://github.com/ministero-salute/it-fse-support/issues/695#issuecomment-2022834466
- _Esecuzione fork e commit:_ https://github.com/ministero-salute/it-fse-support/issues/853#issuecomment-2124107085

Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Potrà riaprirla nel caso in cui fosse necessario ulteriore supporto.
Grazie.

**Comment by vigliottim** [comment]
Rispondiamo in linea alle sue domande:

> riguardo la checklist nel file excel ci sono 6 casi test OK (da 0 a 5) ma nel file excel parte da 1 a 5, lo 0 quindi non và compilato, giusto ? 

Il caso di test 0 non è descritto poiché prevede esclusivamente gli elementi obbligatori secondo HL7 Italia. E' necessario compilarlo poiché è sempre applicabile.

> Nella sezione degli esempi xml https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/Documenti%20XML%20Casi%20OK/5%20-%20Casi%20OK%20Referto%20di%20Medicina%20di%20Laboratorio il contenuto degli XML non corrisponde a quanto scritto nel file doc. Ad esempio, per il caso 1 nel file word si parla di esame microbiologico delle vie aeree ma nell'esempio xml c'è ALBUMINA_URINE. Come mi devo comportare ?

I file di esempio sono stati inseriti a scopo dimostrativo. Dovrà seguire le specifiche contenute nei file riportati nella cartella [TestCase/Validazione/LAB](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/5-Referto%20di%20Medicina%20di%20Laboratorio)
per eseguire correttamente i casi di test.

Rimaniamo a disposizione per chiarimenti.

**Comment by PieroDal** [comment]
Buona sera, dopo aver ottenuto la validazione dei cinque casi OK (Referto di Laboratorio),
ho cominciato a vedere i casi KO ma ho dei dubbi.

Nel file Word (casi di test LAB.docx) dice di fare un test non compilando il confidentialityCode e così ho fatto ma la validazione và comunque a buon fine ottenendo il TraceID, il workflowInstanceId ecc. Vi allego il pdf con all'interno il CDA ed il log
[Cda e Log Mancata compilazione confidentialityCode.zip](https://github.com/user-attachments/files/17737235/Cda.e.Log.Mancata.compilazione.confidentialityCode.zip)

Seguendo, invece, il file excel accreditamento-checklist_V8.2.1.xlsx, il test successivo che riguarda la sezione LAB è ID 28 (token jwt mancante di campi obbligatori). 
Devo seguire solo quanto scritto nella sezione Summary, cioè i test con ID 28,36,44,52,53,54,55,56,57,58,59,60,61,62 ?

**Comment by vigliottim** [comment]
Buongiorno,
il caso di test 6 (KO) prevede di non inserire l'informazione sul livello di riservatezza del campo _confidentialityCode_:

![image](https://github.com/user-attachments/assets/41faf868-9da4-4a21-801e-f1d7015e4159)

![image](https://github.com/user-attachments/assets/aaf09c87-e9ae-4d4b-bc05-5884d7d91550)

Nel CDA2 da lei utilizzato da lei, pertanto, non valorizzando solo l'attributo _code_, come indicato di seguito:

_As is:_ `<confidentialityCode code="" codeSystem="" codeSystemName="HL7 Confidentiality" displayName="Normal" />`

_To be:_ `<confidentialityCode code="" codeSystem="2.16.840.1.113883.5.25" codeSystemName="HL7 Confidentiality" displayName="Normal" />`

otterrà un errore sintattico come da caso di test:

![image](https://github.com/user-attachments/assets/64b6b773-ebb4-4b5b-9519-cd9c08a84372)

Per l'esecuzione del caso di test con ID = 28 può seguire le indicazioni riportate in "DESCRIZIONE CASO DI TEST":

![image](https://github.com/user-attachments/assets/b81e05b2-ea01-404e-b8cf-e088a28dfbf8)

Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by PieroDal** [comment]
un'altra cosa.
Devo seguire i casi scritti nel file Word (casi di test LAB.docx) o quelli del dile excel accreditamento-checklist_V8.2.1.xlsx ??
Chiedo poichè i casi di test sono differenti e perchè, per esempio, l'errore di sintassi relativo confidentialityCode non c'è nel file excel.

**Comment by vigliottim** [comment]
> <confidentialityCode code="" codeSystem="2.16.840.1.113883.5.25" codeSystemName="HL7 Confidentiality" displayName="Normal" />

Le chiediamo di effettuare una nuova prova di validazione inserendo l'elemento _confidentialityCode_ come indicato:
`<confidentialityCode code="" codeSystem="2.16.840.1.113883.5.25" codeSystemName="HL7 Confidentiality" displayName="Normal" />`
e inviarci la response completa ottenuta.
Grazie.

**Comment by PieroDal** [comment]
> <confidentialityCode code="" codeSystem="2.16.840.1.113883.5.25" codeSystemName="HL7 Confidentiality" displayName="Normal" />

niente da fare, ecco qui:
`{"traceID":"aee49b5d99c38ed9","spanID":"aee49b5d99c38ed9","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.2a9435177c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`
[Validate.log](https://github.com/user-attachments/files/17747975/Validate.log)
[RefertoDEC_CDA.pdf](https://github.com/user-attachments/files/17747976/RefertoDEC_CDA.pdf)

**Comment by LucaRogledi** [comment]
Buongiorno,
dalle verifiche effettuate sulla chiamata con traceId:
 
`"traceID":"aee49b5d99c38ed9"`

Risulta che il cda utilizzato contiene:

`<confidentialityCode code="N" codeSystem="2.16.840.1.113883.5.25" codeSystemName="HL7 Confidentiality" displayName="Normal"/>`

La invitiamo a verificare il pdf utilizzato per la chiamata, effettuando una nuova prova seguendo le correzioni indicate precedentemente.
Dalle nostre verifiche tramite la chiamata di validazione utilizzando il pdf da lei riportato [RefertoDEC_CDA.pdf](https://github.com/user-attachments/files/17747976/RefertoDEC_CDA.pdf) si ottiene "Errore di sintassi."
Grazie

**Comment by PieroDal** [comment]
Grazie per la segnalazione che ha fatto venir fuori un errore!

> Buongiorno, dalle verifiche effettuate sulla chiamata con traceId:
> 
> `"traceID":"aee49b5d99c38ed9"`
> 
> Risulta che il cda utilizzato contiene:
> 
> `<confidentialityCode code="N" codeSystem="2.16.840.1.113883.5.25" codeSystemName="HL7 Confidentiality" displayName="Normal"/>`
> 
> La invitiamo a verificare il pdf utilizzato per la chiamata, effettuando una nuova prova seguendo le correzioni indicate precedentemente. Dalle nostre verifiche tramite la chiamata di validazione utilizzando il pdf da lei riportato [RefertoDEC_CDA.pdf](https://github.com/user-attachments/files/17747976/RefertoDEC_CDA.pdf) si ottiene "Errore di sintassi." Grazie

Grazie per la segnalazione. In effetti c'era un errore sul file che veniva realmente inviato.

**Comment by LucaRogledi** [comment]
Buonasera, 
ringraziamo per il feedback, e procediamo con la chiusura della presente issue. 
Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. 
Grazie

**Comment by PieroDal** [comment]
Un'altra domanda.
Per i casi KO che vengono prevenuti dall'applicativo, tipo mancanza di parte dell'anagrafica, sesso, ecc, posso impostare la NON applicabilità ?

**Comment by PieroDal** [comment]
> Di seguito le alleghiamo dei link con indicazioni relative alla creazione della pull-request:
> 
>     * _Documentazione pull-request:_ https://github.com/ministero-salute/it-fse-accreditamento#pull-request
> 
>     * _Pull-request:_ [Prima pull request #695 (comment)](https://github.com/ministero-salute/it-fse-support/issues/695#issuecomment-2022834466)
> 
>     * _Esecuzione fork e commit:_ [Problemi per creazione repository per accreditamento #853 (comment)](https://github.com/ministero-salute/it-fse-support/issues/853#issuecomment-2124107085)
> 
> 
> Rimaniamo a disposizione per ulteriori chiarimenti.

Buonasera, sto cercando di seguire la procedura di caricamento risultati ma non riesco a creare il repository.
 
Se clicco su https://github.com/ministero-salute/it-fse-accreditamento appare la seguente videata

![immagine](https://github.com/user-attachments/assets/dcca6e5d-f4cd-49a1-8f3b-0f1b7c7bdf07)

e forse a seguito di altri tentativi sbagliati, se clicco su Create New Fork  (come da documentazione) appare la seguente videata

![immagine](https://github.com/user-attachments/assets/a3d19bf3-c712-42e6-9cda-d23ee908f8c9)

come devo proseguire ?

**Comment by LucaRogledi** [comment]
Buongiorno, 
L'errore da lei riscontrato potrebbe essere dovuto dal fatto che il repository è gia stato generato da una fork precedente.
Pertanto suggeriamo di:

1. Aprire il repository forkato https://github.com/PieroDal/it-fse-accreditamento se conferma essere il repository da lei forkato precedentemente.

2. Partendo dal repository indicato (se le modifiche erano gia state applicate a questo repository, assicurarsi di avere un backup offline per evitare di perderle) effettuare una Sync come indicato nel seguente commento https://github.com/ministero-salute/it-fse-support/issues/794#issuecomment-2095963176

![image](https://github.com/user-attachments/assets/f6176bdd-ef87-4084-b09e-ecd05beef0fd)

3. verificare che le modifiche desiderate siano presenti o applicarle nuovamente tramite commit.

4. cliccare su contribute - open pull request

![image](https://github.com/user-attachments/assets/89ecd3e7-b0ed-40d1-a10b-6de0e9a06fc8)

5. assicurarsi che base sia `ministero-salute/it-fse-accreditamento` e head repository il repository forkato contenente le nuove modifiche.

![image](https://github.com/user-attachments/assets/8f613e78-0217-486d-ac04-0af6457c80ba)

6. aggiungere la descrizione e cliccare su Create Pull Request.

Grazie

**Comment by LucaRogledi** [comment]
Salve,
è corretto che siano presenti i file da lei riportati nello screenshot, in quanto, a questi andranno ad aggiungersi i dati che desidera caricare. 
Può procedere caricando i risultati da lei ottenuti all'interno della cartella `GATEWAY` seguendo quanto indicato in [documentazione - Procedura di caricamento dei risultati](https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#procedura-di-caricamento-dei-risultati) per quanto riguarda la struttura corretta.  
Grazie

**Comment by PieroDal** [comment]
Ma in questa fork, creata per errore, non c'è il percorso corretto GATEWAY/A1#111#DECSISTEMISRLX1/DEC_Sistemi_Srl/LABNET/1\.4 ( la barra al contrario và messa davanti al punto, giusto ?? ).
Non posso/riesco ad eliminarla ma posso fare L'Upload dei file, ho provato con uno a caso e me l'ha consentito ma non riesco/posso creare le cartelle (p.e. files)
Mi consente anche di creare la Pull Request ma non ho proseguito per evitare di fare altri "casini"
che faccio ?

**Comment by LucaRogledi** [comment]
Buongiorno, 
Riportiamo di seguito una segnalazionein cui sono riportati gli step da seguire per la creazione del struttura necessaria per l'accreditmaneto e il caricamento dei file: #853 .

Lasciamo inoltre gli step da seguire in caso volesse eliminare il repository forkato per errore:

1. Aprire il repository forkato che desidera eliminare
2. Cliccare impostazioni

![image](https://github.com/user-attachments/assets/53632258-42b8-4daf-8839-cf36e5085901)

3. Nella schermata settings - general aperta scorrere fino alla fine e cliccare delete this repository

![image](https://github.com/user-attachments/assets/a88cf2f6-8207-4f27-ad36-72c6542a8b87)

Grazie

**Comment by PieroDal** [comment]
Grazie, repository eliminato e ricreato correttamente (ho scorperto che bisogna dare i nomi delle cartelle uno alla volta, p.e. gateway\ e solo dopo proseguire un passo alla volta, io invece prima facevo il copia ed incolla dell'intero percorso).
Ho caricato anche i file al posto giusto ma mi sono accorto che uno di questi, giusto il data.json, aveva un errore all'interno. 
Come faccio a cancellare il file e rifare l'upload di quello corretto ?

**Comment by LucaRogledi** [comment]
Buongiorno,
Per eliminare il file desiderato può utilizzare la sezione indicata per esempio:

![image](https://github.com/user-attachments/assets/905fc020-9f64-4f9f-a935-40724e0c3886)

Effettuare successivamente il commit

![image](https://github.com/user-attachments/assets/55fe022d-8e55-43bb-bccf-ba63004e94e7)

Ottenendo il seguente risultato

![image](https://github.com/user-attachments/assets/2e1760e6-022a-409a-9a67-7fad9577a5c0)

Riportiamo anche la documentazione github in caso possa essere d'aiuto https://docs.github.com/en/repositories/working-with-files/managing-files/deleting-files-in-a-repository.
Mentre per l'upload del file corretto può trovare l'opzione nella sezione di add file:

![image](https://github.com/user-attachments/assets/ce0a0534-2b41-4859-b507-d39f02a16f23)

Grazie

**Comment by PieroDal** [comment]
Grazie, probabilmente sbaglio nel modo in cui arrivo ai file poichè da qui:
![immagine](https://github.com/user-attachments/assets/76bd8dcd-3a17-4c6e-a298-29614af421a1)
la possibilità di Eliminare non c'è.
Qual'è il percorso che devo seguire ?

**Comment by vigliottim** [comment]
Buon pomeriggio,
le chiediamo di controllare se esiste una scrollbar nel menu a tendina e l'opzione "Delete file" è presente in basso, come mostra la seguente figura:

![image](https://github.com/user-attachments/assets/85d499b1-2a7d-46cb-a794-f8e177b42fd4)

**Comment by PieroDal** [comment]
sottilissima ma c'era 🤦🏻‍♂️
Grazie ho fatto!

Ho creato anche la PR 
[https://github.com/ministero-salute/it-fse-accreditamento/pull/1705](https://github.com/ministero-salute/it-fse-accreditamento/pull/1705)

La richiesta è corretta ?

**Comment by vigliottim** [comment]
La informiamo che la pull request è stata correttamente creata.

**Comment by PieroDal** [comment]
Grazie
Vuoto.pdf eliminato come anche il file json con le maiuscole.
Riguarda alla tripletta la differenza sta in DEC Sistemi Srl e DEC_Sistemi_Srl ?
(ho messo "_" al posto dello spazio perchè l'ho letto nella documentazione) 

Devo modificare la descrizione della PR ed il file excel ?
Nella richiesta di accreditamento come "subject_application_vendor" è stato definito "DEC Sistemi Srl" (con gli spazi)

**Comment by vigliottim** [comment]
Buongiorno,
l'underscore va inserito solo nel nome della directory di sottomissione.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by PieroDal** [comment]
Buongiorno e grazie,
ho modificato la descrizione della Pull Request eliminando gli underscore
ma i file che avevo eliminato (vuoto.pdf e Data.Json) da qui: [Link](https://github.com/PieroDal/it-fse-accreditamento/tree/12419f2976a1a611779e72e0f8c8c349e7dec03e/GATEWAY/A1%23111%23DECSISTEMISRLX1/DEC_Sistemi_Srl/LABNET/1.4) nella PR ci sono ancora e non riesco ad eliminarli. Potreste guidarmi ?

**Comment by LucaRogledi** [comment]
Buongiorno, Le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email entro qualche giorno lavorativo. Grazie.

**Comment by PieroDal** [comment]
Buonasera, ho aggiornato il report-checklist, devo effettuare una nuova Pull Request ?

**Comment by LucaRogledi** [comment]
Buongiorno, 
Essendo presente una PR aperta da parte sua, non ancora, elaborata è possibile applicare modifiche su quella ( https://github.com/ministero-salute/it-fse-accreditamento/pull/1705 ) come dalle nostre verifiche risulta lei abbia già fatto.
Restiamo a disposizione per ulteriore supporto.
Grazie

**Comment by PieroDal** [comment]
Grazie a voi per il prezioso supporto

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Grazie

**Comment by PieroDal** [comment]
Buongiorno, scrivo solo per avvisarvi (non so se sia necessario) che ho aggiornato il report-checklist

**Comment by vigliottim** [comment]
> Buongiorno, scrivo solo per avvisarvi (non so se sia necessario) che ho aggiornato il report-checklist

Grazie per la segnalazione.
La sua PR è stata correttamente creata.
Riceverà l'esito delle elaborazioni via e-mail nel giro di qualche giorno lavorativo.

**Comment by PieroDal** [comment]
Buonasera, a seguito della vostra segnalazione ho nuovamente modificato il file data.json (mancava la "," dopo la parentesi graffa di ogni caso di test)
ma la Pull Request è chiusa. 
La dovete riaprire o devo farne un'altra ?

**Comment by vigliottim** [comment]
Buonasera,
per apportare delle modifiche può effettuare una PR correttiva.
Grazie.

**Comment by PieroDal** [comment]
> Buonasera, per apportare delle modifiche può effettuare una PR correttiva. Grazie.

Buongiorno, potreste gentilmente scrivermi come ?
Grazie

**Comment by vigliottim** [comment]
Buongiorno,
deve creare una nuova pull request facendo commit esclusivamente dei file che intende modificare.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by PieroDal** [comment]
> Buongiorno, deve creare una nuova pull request facendo commit esclusivamente dei file che intende modificare. Rimaniamo a disposizione per ulteriori chiarimenti.

Grazie, ho fatto. 
E' corretta la procedura e sopratutto, è corretto il Json ?

**Comment by vigliottim** [comment]
Buongiorno,
le confermiamo che il nuovo file data.json caricato è corretto.

**Comment by PieroDal** [comment]
Bene grazie.
Inoltre, vi chiedo, sempre se possibile, di accellerare i tempi di controllo poichè abbiamo una scadenza regionale da rispettare, grazie.

**Comment by PieroDal** [comment]
Buonasera, potreste gentilmente indirizzarmi verso il documento di riferimento per il vocabolario ObservationMethod (OID 2.16.840.1.113883.5.84) ?
Grazie

**Comment by PieroDal** [comment]
Buongiorno, in attesa del vocabolario per inserire la tabella corretta nell'applicativo, ho apportato le modifiche alla PR [https://github.com/ministero-salute/it-fse-accreditamento/pull/1725](https://github.com/ministero-salute/it-fse-accreditamento/pull/1725) con data.json, report-checklist aggiornati ed il nuovo PDF il cui CDA contiene la riga `<methodCode code="0272" codeSystem="2.16.840.1.113883.5.84" codeSystemName="ObservationMethod" displayName="Minimum Inhibitory Concentration (MIC)" />` utilizzando il codice 0272 che fà riferimento alla metodica utilizzata utilizzando la tabella di riferimento del link precedente.

**Comment by vigliottim** [comment]
> Buonasera, potreste gentilmente indirizzarmi verso il documento di riferimento per il vocabolario ObservationMethod (OID 2.16.840.1.113883.5.84) ?
> Questo và bene https://terminology.hl7.org/ValueSet-v3-ObservationMethod.html ?
> Grazie

Buongiorno,
può trovare il file _terminology_ al seguente link: https://github.com/ministero-salute/it-fse-catalogs/tree/main/terminology

**Comment by PieroDal** [comment]
> 2.16.840.1.113883.5.84

Graz

> Buongiorno,
> può trovare il file csv relativo al vocabolario 2.16.840.1.113883.5.84.csv nella cartella _terminology_ al seguente link: https://github.com/ministero-salute/it-fse-catalogs/tree/main/terminology

Grazie, molto utile!
