### ISSUE TITLE
REGIONE BASILICATA RDE (Nessuna RDA) - PROBLEMA REGISTRAZIONE CONSENSI

### ISSUE THREAD

**Issue by BasilicataCrashProgramFSE** [ministero-salute/it-fse-support#1189]
Buonasera,
stiamo riscontrando un problema nella registrazione dei consensi sul codice Fiscale **PRVSST76A10G942K**

Dettagli richiesta e risposta ricevuta:

**Request**
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:stat="http://statoconsensirichiesta.xsd.fse.ini.finanze.it" xmlns:tip="http://tipodatistatoconsensi.xsd.fse.ini.finanze.it">
   <soapenv:Header/>
   <soapenv:Body>
      <stat:StatoConsensiRichiesta>
         <stat:IdentificativoUtente>PROVAX00X00X000Y</stat:IdentificativoUtente>
         <stat:pinCode></stat:pinCode>
         <stat:IdentificativoOrganizzazione>170</stat:IdentificativoOrganizzazione>         
         <stat:DescrizioneOrganizzazione></stat:DescrizioneOrganizzazione>         
         <stat:StrutturaUtente>------</stat:StrutturaUtente>         
         <stat:RuoloUtente>ASS</stat:RuoloUtente>         
         <stat:ContestoOperativo>CONSENT</stat:ContestoOperativo>
         <stat:IdentificativoAssistitoGenitoreTutore></stat:IdentificativoAssistitoGenitoreTutore>         
         <stat:PresaInCarico>true</stat:PresaInCarico>         
         <stat:TipoAttivita>READ</stat:TipoAttivita>
         <stat:IdentificativoAssistitoConsenso>PRVSST76A10G942K</stat:IdentificativoAssistitoConsenso>
      </stat:StatoConsensiRichiesta>
   </soapenv:Body>
</soapenv:Envelope>`

**Response**
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <a:StatoConsensiRicevuta xmlns="http://tipodatistatoconsensi.xsd.fse.ini.finanze.it" xmlns:b="http://statoconsensirichiesta.xsd.fse.ini.finanze.it" xmlns:a="http://statoconsensiricevuta.xsd.fse.ini.finanze.it">
         <a:Esito>9999</a:Esito>
         <a:ElencoErrori>
            <Errore>
               <codEsito>1075</codEsito>
               <esito>Identificativo assistito consenso non valido</esito>
               <tipoErrore>Bloccante</tipoErrore>
               <fonte>FSE-INS-FE</fonte>
            </Errore>
         </a:ElencoErrori>
      </a:StatoConsensiRicevuta>
   </soapenv:Body>
</soapenv:Envelope>`

Abbiamo necessità che tale assistito venga inserito in Basilicata in modo da poter registrare i consensi ed iniziare i test: RDE (Nessuna RDA)

Grazie.

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
per il CF PRVSST76A10G942K non risultano consensi.
Potete fornirci la request e la response relative alla chiamata con cui provate e registrare i consensi?

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno, 

di seguito i dettagli richiesti:

**Request:**
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:com="http://comunicazioneconsensirichiesta.xsd.fse.ini.finanze.it" xmlns:tip="http://tipodaticomunicazioneconsensi.xsd.fse.ini.finanze.it">
   <soapenv:Header/>
   <soapenv:Body>
      <com:ComunicazioneConsensiRichiesta>
         <com:IdentificativoUtente>PROVAX00X00X000Y</com:IdentificativoUtente>
         <com:pinCode/>
         <com:IdentificativoOrganizzazione>170</com:IdentificativoOrganizzazione>       
         <com:DescrizioneOrganizzazione/>       
         <com:StrutturaUtente>------</com:StrutturaUtente>       
         <com:RuoloUtente>ASS</com:RuoloUtente>       
         <com:ContestoOperativo>CONSENT</com:ContestoOperativo>
         <com:IdentificativoAssistitoGenitoreTutore/>       
         <com:PresaInCarico>true</com:PresaInCarico>       
         <com:TipoAttivita>UPDATE</com:TipoAttivita>
         <com:IdentificativoAssistitoConsenso>PRVSST76A10G942K</com:IdentificativoAssistitoConsenso>       
         <com:IdentificativoGenitoreConsenso/>       
         <com:ListaConsensi>
            <!--1 or more repetitions:-->
            <tip:Consenso>
               <tip:CodiceConsenso>C1</tip:CodiceConsenso>
               <tip:ValoreConsenso>true</tip:ValoreConsenso>             
               <tip:Data>20241008112607</tip:Data>             
               <tip:Note/>
            </tip:Consenso>
             <tip:Consenso>
               <tip:CodiceConsenso>C2</tip:CodiceConsenso>
               <tip:ValoreConsenso>true</tip:ValoreConsenso>             
               <tip:Data>20241008112607</tip:Data>             
               <tip:Note/>
            </tip:Consenso>
            <tip:Consenso>
               <tip:CodiceConsenso>C3</tip:CodiceConsenso>
               <tip:ValoreConsenso>false</tip:ValoreConsenso>             
               <tip:Data>20241008112607</tip:Data>             
               <tip:Note/>
            </tip:Consenso>
            <tip:Consenso>
               <tip:CodiceConsenso>C4</tip:CodiceConsenso>
               <tip:ValoreConsenso>true</tip:ValoreConsenso>             
               <tip:Data>20241008112607</tip:Data>             
               <tip:Note/>
            </tip:Consenso>
         </com:ListaConsensi>
         <com:IdentificativoInformativa>170^0094</com:IdentificativoInformativa>
      </com:ComunicazioneConsensiRichiesta>
   </soapenv:Body>
</soapenv:Envelope>

```

**Response:**
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
<soapenv:Body>
     <a:ComunicazioneConsensiRicevuta xmlns="http://tipodaticomunicazioneconsensi.xsd.fse.ini.finanze.it" xmlns:b="http://comunicazioneconsensirichiesta.xsd.fse.ini.finanze.it" xmlns:a="http://comunicazioneconsensiricevuta.xsd.fse.ini.finanze.it">
         <a:Esito>9999</a:Esito>
         <a:ElencoErrori>
            <Errore>
             <codEsito>1075</codEsito>
             <esito>Identificativo assistito consenso non valido</esito>
             <tipoErrore>Bloccante</tipoErrore>
             <fonte>FSE-INS-FE</fonte>
            </Errore>
         </a:ElencoErrori>
     </a:ComunicazioneConsensiRicevuta>
</soapenv:Body>
</soapenv:Envelope>
```
Ad ogni modo il dubbio da chiarire è il seguente:

Vanno effettuati i test UC13, UC14, UC15, UC16, UC17, UC18 descritti nel foglio Summary ma non riportati nel foglio TestCase?

Se si, il codice fiscale PRVSST76A10G942K può essere utilizzato per effettuare questi test, o essendo un codice effettivamente registrato qui in Basilicata, per portare a termine i test UC13 etc.. abbiamo bisogno che ci forniate un altro codice fiscale?

Grazie.

**Comment by g-maugeri-sogei** [comment]
Buonasera,
potete riprovare valorizzando la struttura utente?

**Comment by BasilicataCrashProgramFSE** [comment]
Buon pomeriggio,

prima di riprovare, riuscite a smarcare i dubbi sopra citati? Per comodità riporto i punti da chiarire:

1. Vanno effettuati i test UC13, UC14, UC15, UC16, UC17, UC18 descritti nel foglio Summary ma non riportati nel foglio TestCase (documento: https://governoit.sharepoint.com/:x:/r/sites/DTD-PrjM6_C2_1.3.1_FSE-extFSE-RTILotto6/_layouts/15/Doc.aspx?sourcedoc=%7B91F067D8-591B-4112-BFA6-F13E3D4903F7%7D&file=DTD_FSE%202.0_CrashProgram-UseCase_V0.5_Example.xlsx&action=default&mobileredirect=true)?

2. Se si, il codice fiscale PRVSST76A10G942K può essere utilizzato per effettuare questi test, o essendo un codice effettivamente registrato qui in Basilicata, per portare a termine i test UC13 etc.. abbiamo bisogno che ci forniate un altro codice fiscale?

Grazie.

**Comment by g-maugeri-sogei** [comment]
Rispondo per il punto 2): confermo che il CF puo' essere utilizzato.
Per il punto 1) rimando ai colleghi che gestiscono il piano di test.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
La informiamo che sarà possibile riaprirla nel caso in cui necessiti di ulteriore supporto.
Grazie.
