### ISSUE TITLE
Regione Sardegna pubblicazione verso P.A. Trento

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#1190]
Buongiorno,
abbiamo effettuato un  tentativo di pubblicazione verso la vostra P.A.
```
traceId: 6720c5207d1f873d3c556b63ee3250ff
DocumentEntry.uniqueId: 2.16.840.1.113883.2.9.4.3.8^200106TRCTST70A01L378S20241029121740787679
workflowInstanceId: 2.16.840.1.113883.2.9.2.120.4.4.599b15dc1051eb03e126b38b141b757d2aa2ee848fa3afcbd66dabc08c0a2b56.26a0fd93bc^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
```
successivamente, controllando l'esito stato transazione otteniamo il seguente errore:

`SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error`

Vi chiediamo gentilmente di eseguire una verifica sul problema riscontrato per identificare le cause dell’errore e supportarci nella risoluzione, al fine di consentire il corretto completamento della pubblicazione.

Rimaniamo a disposizione

**Comment by vigliottim** [comment]
@apsstn

Buongiorno,
chiediamo gentilmente alla provincia autonoma di Trento di fornire supporto alla regione Puglia.
Grazie.

**Comment by FSESardegna** [comment]
precisiamo che  in questa Issue è la regione Sardegna che ha necessità di supporto.
Grazie

**Comment by nicola-ferrari-threadsolutions** [comment]
Buonasera
Abbiamo avuto dei problemi in fase di storicizzazione documenti.

Potete gentilmente procedere con una nuova pubblicazione ed in seguito gli altri UC?

Grazie

cc @apsstn

**Comment by FSESardegna** [comment]
Buongiorno,
a seguito di nuove prove di cui riporto i dettagli di seguito :
Pubblicazione:
```
DocumentId: 2.16.840.1.113883.2.9.2.200.4.4^200106TRCTST70A01L378S20241120102112642596
WII: 2.16.840.1.113883.2.9.2.200.4.4.21669385c45493e632a503937a1c33c79f4b4d51386b78671c5ef861a0bccca9.cddf2f9ab6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
TraceId: 673daa90fe33d0f5cd6c61bbcaa43afb
```
otteniamo un success nella verifica stato transazione
`VerificaTransazione:  SUCCESS`

ma di seguito eseguendo la seguente sostituzione

```
DocumentId:  2.16.840.1.113883.2.9.2.200.4.4^200106TRCTST70A01L378S20241120104649311589
WII: 2.16.840.1.113883.2.9.2.200.4.4.8678e417171fe27aea4985e923ee5c188a0d18dfc247c0da87734e941481f402.a1ea7c3553^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
TraceId: 673db068bb187c195adf3f8f074c0ee3
```
otteniamo un errore 
`500 - Id documento non presente`.

Potete verificare, grazie.

**Comment by nicola-ferrari-threadsolutions** [comment]
Ciao @FSESardegna 

Da un primo controllo sembra che la sostituzione documento sia stata fatta su un documento non precedentemente registrato. 

Vedo una chiamata di registrazione stamane alle 10:22 con id 2.16.840.1.113883.2.9.2.200.4.4^200106TRCTST70A01L378S20241120102112642596

Mentre una RegistryStoredQuery alle 10:58 con id 2.16.840.1.113883.2.9.2.200.4.4^200106TRCTST70A01L378S20241120105731708581

E quest ultima chiamata non trova quindi il documento sul quale effettuare una sostituzione. 

Potete verificare?

Grazie

**Comment by LucaRogledi** [comment]
Buonasera @FSESardegna @nicola-ferrari-threadsolutions  potreste gentilmente riprovare le chiamate andate in errore e darci un feedback? 
Grazie

**Comment by FSESardegna** [comment]
Buongiorno, abbiamo eseguito una nuova prova completa 
Pubblicazione: 
```
DocumentId: 2.16.840.1.113883.2.9.2.200.4.4^200106TRCTST70A01L378S20241122093904058915
WII: 2.16.840.1.113883.2.9.2.200.4.4.971a4f0b6e3303a34b11f187ba76a536f7e518583764d9a9272f39f0c4ce99b8.028bd8304d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
TraceId: 6740437230b97d2b44687329c670f142
VerificaTransazione:  SUCCESS
```
mentre per la REPLACE:
```
DocumentId:  2.16.840.1.113883.2.9.2.200.4.4^200106TRCTST70A01L378S20241120104649311589
WII: 2.16.840.1.113883.2.9.2.200.4.4.dfbe8ec428e576bf9cbd2ce5d3426d79dcee5f59792d1d4347cfff73d35ff73e.9de807cac8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
TraceId: 674044aa1a9b4066f1c2e80fb3767e50
```
otteniamo : 
`500 Id documento non presente`

**Comment by nicola-ferrari-threadsolutions** [comment]
Ciao @FSESardegna 

Potete riprovare per favore? 

Grazie

**Comment by vigliottim** [comment]
> Ciao @FSESardegna
> 
> Potete riprovare per favore?
> 
> Grazie

Buongiorno @FSESardegna,
chiediamo un gentile riscontro.
Grazie.

**Comment by FSESardegna** [comment]
Buongiorno, le prove sono andate in success. Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Grazie
