### ISSUE TITLE
Regione Valle d'Aosta - Pubblicazione verso Regione ER: KO su Replace/metadata update/delete

### ISSUE THREAD

**Issue by assistenza-fsevda** [ministero-salute/it-fse-support#1194]
buongiorno
abbiamo iterato oggi su RDA 080 i 4 servizi su CF PRVPRV59T16L424B.

CREATE - ESITO OK (presa in carico del GTW ma nessuna notifica di INI verso RDE 020)

Questi i riferimenti con status che ci risulta OK:

{"traceID":"4a296e38316e7108","spanID":"4a296e38316e7108","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.c3ddef87ff^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

{"traceID":"c2f8160daa49e858","spanID":"c2f8160daa49e858","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.a107351556^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

{"traceID":"01a0450848c1a917","spanID":"01a0450848c1a917","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.6f0e85794b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

{"traceID":"01a0450848c1a917","spanID":"01a0450848c1a917","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.20.4.4.415c9c65a3189db4b0fb609c2e46bfaf2c1bc80ba68b520f100ce48d9b360d71.6f0e85794b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

-------------------
REPLACE DOCUMENT: ESITO KO

  "codice": "404",
    "descrizione": "{\"traceID\":\"9c1e7e6e4f4d1af5\",\"spanID\":\"9c1e7e6e4f4d1af5\",\"type\":\"/err/resource\",\"title\":\"Resource error\",\"detail\":\"Id documento non presente\",\"status\":404,\"instance\":\"/not-found\"}",
    "esito": "KO",
    "tipo": "replace"

-------------------------
METADATA UPDATE: ESITO KO

"codice": "500",
    "descrizione": "{\"traceID\":\"11113992ab2ea397\",\"spanID\":\"2eb7dfcec25e5c40\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"\",\"instance\":\"error/generic\"}",
    "esito": "KO",
    "tipo": "update"

-------------------------
DELETE: ESITO KO

"codice": "500",
    "descrizione": "{\"traceID\":\"0b291ca2baf474e1\",\"spanID\":\"d3f749cb4da30405\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"\",\"instance\":\"error/generic\"}",
    "esito": "KO",
    "tipo": "delete"

Restiamo in attesa delle controverifiche da parte della RDA.
Grazie

**Comment by vigliottim** [comment]
@daniele-gubellini

Buongiorno,
chiediamo gentilmente alla regione Emilia-Romagna di fornire supporto.
Grazie.

**Comment by daniele-gubellini** [comment]
Buongiorno,

potreste comunicarci gli identificativi dei documenti?

Per la replace e delete chiediamo di riprovare e di avvisarci subito.
L'update non sarà funzionante fino all'implementazione della ITI-57 da parte di INI.

**Comment by assistenza-fsevda** [comment]
Buongiorno @daniele-gubellini,
abbiamo effettuato una nuova serie di test - creazione, replace e delete - e non abbiamo riscontrato anomalie, le transazioni sembrano tutte concluse con successo.
Di seguito i dettagli per una controverifica.

Create
```
documento 2.16.840.1.113883.2.9.2.20.4.4^001.CRASHPRG.TESTRIS:ER0001-0
documento 2.16.840.1.113883.2.9.2.20.4.4^001.CRASHPRG.TESTRIS:ER0002-0
documento 2.16.840.1.113883.2.9.2.20.4.4^001.CRASHPRG.TESTRIS:ER0003-0
```

Replace
`documento 2.16.840.1.113883.2.9.2.20.4.4^001.CRASHPRG.TESTRIS:ER0002-1 ha sostituito documento 2.16.840.1.113883.2.9.2.20.4.4^001.CRASHPRG.TESTRIS:ER0002-0`

Delete
`cancellato documento 2.16.840.1.113883.2.9.2.20.4.4^001.CRASHPRG.TESTRIS:ER0003-0`

Se servono altre informazioni siamo a disposizione.

Grazie per il supporto fornito.

**Comment by daniele-gubellini** [comment]
Le operazioni di create, replace e delete indicate risultano correttamente applicate sul nostro indice.
