### ISSUE TITLE
Crash Program - Regione Veneto - Errore non standard servizio Aggiornamento Metadati

### ISSUE THREAD

**Issue by ppalmerini** [ministero-salute/it-fse-support#1195]
Buongiorno, 
abbiamo fatto un tentativo di aggiornamento metadati per il documento con unique id 2.16.840.1.113883.2.9.2.50.2.50.4.4.2^20241030121740
Il documento risulta correttamente validato e pubblicato, ma inviando la richiesta a questo endpoint
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.50.2.50.4.4.2%5E20241030121740/metadata
con i seguenti token:
auth
eyJ4NWMiOlsiTUlJRmNUQ0NBMW1nQXdJQkFnSVVJYWZaaHhzMjJsdzY2TU0vUFBkcTVBSUtrV1F3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TkRBNE1qQXhOVFF5TUROYUZ3MHlOekE0TWpFeE5UUXlNREphTUhJeEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVNFd0h3WURWUVFEREJoVE1TTXdOVEFqVWtWSFNVOU9SVlpGVGtWVVQxUkZVMVF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFdqd3BtVDlVVVdtZUdxVTIrRzdQcmRXU2xHTm1xcXlZZEMva1h1SnhpZVEraFZDT2t3MDVmdGdCL3pZMXd0QU5DWlQ1NkRRYVRJZHNvUUVidkY3SDJsdkc2eGJTZDRBSVAzK3lLclcxYkJ1bGNyeW1JTndEQ1ZiNm5uS2hXQ3pLS08raTU2M29GajFYQzdvZzRZeVg2ZjNCMkUycnFTUm1FY21PKzA1SmJEQ2RINnNRU2ptL3VMOVpUVElISlVoNU5TRDFMZzJFTmQvM0xZbmxLb2NaaUdSK2tSMWc4MFdTQkpDY0dWT0gwZFRVVUx2bU94WC8xNzdVNTB3dVNJb290a25xZ0YyRVJwWWhseGNBQmlFUXpFWElMOTR6S2FtWlJ2aElDMEVvQVlJdlVTRTRUYUNpNXE2NDJmTVVmMkxmc2lUTEV1MHdWUWZsYkJQNkNtM1hOQWdNQkFBR2pnZ0VZTUlJQkZEQWZCZ05WSFNNRUdEQVdnQlFXT2FrYUJZbTNEeTJ5TmUzQ0NackZBNE1pUHpBU0JnTlZIU0FFQ3pBSk1BY0dCU3RNSFFFTE1JR3RCZ05WSFI4RWdhVXdnYUl3Z1orZ2daeWdnWm1HZ1pab2RIUndjem92TDJOaGMyOW5aV2x6ZG1sc0xuTnZaMlZwTG1sMEwyVnFZbU5oTDNCMVlteHBZM2RsWWk5M1pXSmthWE4wTDJObGNuUmthWE4wUDJOdFpEMWpjbXdtYVhOemRXVnlQVU5PSlRORVEwRXJUV2x1YVhOMFpYSnZLMlJsYkd4aEsxTmhiSFYwWlN0VVpYTjBKVEpEVHlVelJFMXBibWx6ZEdWeWJ5dGtaV3hzWVN0VFlXeDFkR1VsTWtOREpUTkVTVlF3SFFZRFZSME9CQllFRkozZFZqc0d3QXRKSGxkcC9wT09mVUpZeEM3Zk1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQXlHTnVLS0FZL25zQ1JMTS9LbDJaWEpjenVyYnN0eCtCKzIxTHI4YzQ3UThqbHFXUmdHcW9ZZW00ZEtZNnRndm03azZIS3lMallFUlVYeEJlV1FmQkVHM2RuWGczb2RqVTkvN08ySU43SWVwQmZNK2w4c2ZPSllPeTQ0bWFSV1Y5LzZXT0FMVkovenFjRG1WWktaNnM0RXZMR3N3QkRERk9ldVplbEVEVExENjhYUExyTm01RFNRdEczUnpJaVZMMTRYKzhJR0dyOVcvWmhhMWg1WGMrRSs0UDhlZDlLSTFSSm9xREg4a280NVY1dXNEL1VBeXB2ZFNXMlFPTEI2VnZTclJIay93MEZ5Sis5eFNEUFBKVi9XK2ZpcUZSNmk3MzM1ZTczZ05uVWpHVGVlbVVNbzg1NUx0WWZBcjRaM3ZNMFNiakZpYWRnamFCeC9jRGZ2dFlDS3EvMlI1WDFjUkpYS3k3cE9XeXZNQm5jQW92ZTZDWTY1SS9wTHhVZGxrMTgvRm9OWjJMSDhKaDNueHIycCtBWHNnUkVIMTF4UVNkTVhUSzl1Z2JXcTNaN3pONGlBL1E3TEV1bnJqQXRVdnRYR1JZTzdwRUdkeWNqVHRCZGJMT3B6VlYzQk9hMWhUUXFZSlFocC8zM2ExKzlXMVZWSTFCWG9IQUJtUk9EK3NYaVZXRUMwRmhHaVVmYU9TNUFsMFBxS1BWUnBlOTJObXI2ZFFjcjNJWHdIN1ZwT2RHaHBtSXBLMXhWMWFETXhhbTdzRDg0ZHM4cXZRNzhzWklhdTBSMmE4bjhyVElKZ0VBbk1wOGNnRHpNeFpLQ2tHcm91eFlCTnRISm90T0Izek4vMG5EQVl4UkIwWk9BN21EZ29TZ2hMYUNMb01kampMbjFIUWFJS1ZhOWFrPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJHUkxNU002MFIzMUY3NzBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJpc3MiOiJhdXRoOlMxIzA1MCNSRUdJT05FVkVORVRPVEVTVCIsImV4cCI6MTczMDQ3Mzg0NiwiaWF0IjoxNzMwMzg3NDQ2LCJqdGkiOiIxNzI3OTYyNzg1In0.06khFAm5Y48AnXOMCeKn-ftcuBvhC3omc4U7Qp83dBrJVtN5ieQWIM7KG1EciBUMfebfvSl-Zk7IlIjgRm6WJzXPH2G5rKOIYpasJmElh8iwnOWMyThK_fx-_x9kCL74E9lNSWe4vwFoPJXc_VyNCcfd5hK57MKMDLi9HfyY_JiZPkAL1X69blTBMf0x76XxdD-Q9QuQ26CrfO7j-BSoctq4nJLvWGhRVpiH0i9Aet3UBhuTQF5owjVLmMN6iaa9bjPuMGwgvXcYBTJKXuRGiDB5bA3VV6JIqPTQRTm4FrXh8KNUU7NxbcVQRqXCl0TvvP4qjzGNRPehUJE8jMW2Mg

sign
eyJ4NWMiOlsiTUlJRmNUQ0NBMW1nQXdJQkFnSVVJYWZaaHhzMjJsdzY2TU0vUFBkcTVBSUtrV1F3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TkRBNE1qQXhOVFF5TUROYUZ3MHlOekE0TWpFeE5UUXlNREphTUhJeEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVNFd0h3WURWUVFEREJoVE1TTXdOVEFqVWtWSFNVOU9SVlpGVGtWVVQxUkZVMVF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFdqd3BtVDlVVVdtZUdxVTIrRzdQcmRXU2xHTm1xcXlZZEMva1h1SnhpZVEraFZDT2t3MDVmdGdCL3pZMXd0QU5DWlQ1NkRRYVRJZHNvUUVidkY3SDJsdkc2eGJTZDRBSVAzK3lLclcxYkJ1bGNyeW1JTndEQ1ZiNm5uS2hXQ3pLS08raTU2M29GajFYQzdvZzRZeVg2ZjNCMkUycnFTUm1FY21PKzA1SmJEQ2RINnNRU2ptL3VMOVpUVElISlVoNU5TRDFMZzJFTmQvM0xZbmxLb2NaaUdSK2tSMWc4MFdTQkpDY0dWT0gwZFRVVUx2bU94WC8xNzdVNTB3dVNJb290a25xZ0YyRVJwWWhseGNBQmlFUXpFWElMOTR6S2FtWlJ2aElDMEVvQVlJdlVTRTRUYUNpNXE2NDJmTVVmMkxmc2lUTEV1MHdWUWZsYkJQNkNtM1hOQWdNQkFBR2pnZ0VZTUlJQkZEQWZCZ05WSFNNRUdEQVdnQlFXT2FrYUJZbTNEeTJ5TmUzQ0NackZBNE1pUHpBU0JnTlZIU0FFQ3pBSk1BY0dCU3RNSFFFTE1JR3RCZ05WSFI4RWdhVXdnYUl3Z1orZ2daeWdnWm1HZ1pab2RIUndjem92TDJOaGMyOW5aV2x6ZG1sc0xuTnZaMlZwTG1sMEwyVnFZbU5oTDNCMVlteHBZM2RsWWk5M1pXSmthWE4wTDJObGNuUmthWE4wUDJOdFpEMWpjbXdtYVhOemRXVnlQVU5PSlRORVEwRXJUV2x1YVhOMFpYSnZLMlJsYkd4aEsxTmhiSFYwWlN0VVpYTjBKVEpEVHlVelJFMXBibWx6ZEdWeWJ5dGtaV3hzWVN0VFlXeDFkR1VsTWtOREpUTkVTVlF3SFFZRFZSME9CQllFRkozZFZqc0d3QXRKSGxkcC9wT09mVUpZeEM3Zk1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQXlHTnVLS0FZL25zQ1JMTS9LbDJaWEpjenVyYnN0eCtCKzIxTHI4YzQ3UThqbHFXUmdHcW9ZZW00ZEtZNnRndm03azZIS3lMallFUlVYeEJlV1FmQkVHM2RuWGczb2RqVTkvN08ySU43SWVwQmZNK2w4c2ZPSllPeTQ0bWFSV1Y5LzZXT0FMVkovenFjRG1WWktaNnM0RXZMR3N3QkRERk9ldVplbEVEVExENjhYUExyTm01RFNRdEczUnpJaVZMMTRYKzhJR0dyOVcvWmhhMWg1WGMrRSs0UDhlZDlLSTFSSm9xREg4a280NVY1dXNEL1VBeXB2ZFNXMlFPTEI2VnZTclJIay93MEZ5Sis5eFNEUFBKVi9XK2ZpcUZSNmk3MzM1ZTczZ05uVWpHVGVlbVVNbzg1NUx0WWZBcjRaM3ZNMFNiakZpYWRnamFCeC9jRGZ2dFlDS3EvMlI1WDFjUkpYS3k3cE9XeXZNQm5jQW92ZTZDWTY1SS9wTHhVZGxrMTgvRm9OWjJMSDhKaDNueHIycCtBWHNnUkVIMTF4UVNkTVhUSzl1Z2JXcTNaN3pONGlBL1E3TEV1bnJqQXRVdnRYR1JZTzdwRUdkeWNqVHRCZGJMT3B6VlYzQk9hMWhUUXFZSlFocC8zM2ExKzlXMVZWSTFCWG9IQUJtUk9EK3NYaVZXRUMwRmhHaVVmYU9TNUFsMFBxS1BWUnBlOTJObXI2ZFFjcjNJWHdIN1ZwT2RHaHBtSXBLMXhWMWFETXhhbTdzRDg0ZHM4cXZRNzhzWklhdTBSMmE4bjhyVElKZ0VBbk1wOGNnRHpNeFpLQ2tHcm91eFlCTnRISm90T0Izek4vMG5EQVl4UkIwWk9BN21EZ29TZ2hMYUNMb01kampMbjFIUWFJS1ZhOWFrPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJHUkxNU002MFIzMUY3NzBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBUFIiLCJwdXJwb3NlX29mX3VzZSI6IlVQREFURSIsImlzcyI6ImludGVncml0eTpTMSMwNTAjUkVHSU9ORVZFTkVUT1RFU1QiLCJsb2NhbGl0eSI6IlVMU1MgMiBNYXJjYSBUcmV2aWdpYW5hXl5eXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMS4zJklTT15eXl4wNTA1MDIiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlcnNpb24iOiIwNi4xOCIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUkVHSU9ORSBWRU5FVE8iLCJzdWJqZWN0X29yZ2FuaXphdGlvbl9pZCI6IjA1MCIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInBhdGllbnRfY29uc2VudCI6dHJ1ZSwiYWN0aW9uX2lkIjoiVVBEQVRFIiwicmVzb3VyY2VfaGw3X3R5cGUiOiIoJzYwNTkxLTVeXjIuMTYuODQwLjEuMTEzODgzLjYuMScpIiwic3ViamVjdF9hcHBsaWNhdGlvbl9pZCI6Ik1FRElDTzIwMDAiLCJleHAiOjE3MzA0NzM4NDYsInN1YmplY3RfYXBwbGljYXRpb25fdmVuZG9yIjoiTWVkaWF0ZWMgSW5mb3JtYXRpY2EgUy5yLmwuIiwiaWF0IjoxNzMwMzg3NDQ2LCJqdGkiOiIxNzI3OTYyNzg1IiwicGVyc29uX2lkIjoiU1FUUFJWODBBNTRJNzk5VF5eXiZhbXA7Mi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJmFtcDtJU08ifQ.DU_E36gA59kEhGq1MG63pGrHL0aFzl89NFzL9Ro0hNu-KczJ3SN8D9AngL77d4BQMGT_BDiHaNee7OGg0Ecl2orJwZMNLnpLrLzIZ-w1LI_8-jUoH8KmLM_ZGCbXxbl4uOgL9tp5IMfJ4ASR_T9vRqiWT_jGR9g1YgWHXgEsD_Idpf-RUSAk4IxCcdY6QLExcXIDsU-7QlajMk2sLKq29OumkmgNd1RZH86RlCmshTcksybYcRuO8eE9GCC1q0HjecIBpV-t6ESCFB4NMZOEV4-Wjtx_3Qjserif-5ICwai9DVwggCSA6ugVQkSjzB0ifXTAMbthzOTDoqiPi22QIw

request body
{
    "tipologiaStruttura": "Territorio",
    "tipoDocumentoLivAlto": "SUM",
    "assettoOrganizzativo": "AD_PSC130",
    "dataInizioPrestazione": "20240927000000",
    "dataFinePrestazione": "20240928000000",
    "tipoAttivitaClinica": "OBS",
    "identificativoSottomissione": "2.16.840.1.113883.2.9.2.50.4.3.20241031152015"
}

otteniamo una risposta fuori standard
{
    "status": 500
}

chiediamo la vostra assistenza, grazie

**Comment by LucaRogledi** [comment]
Buonasera, 
dalle verifiche è emerso che è stato riscontrato un errore PIT29.
Vi chiediamo una verifica interna in quanto RDA.
Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta.
@ppalmerini  La invitiamo a procedere con la riapertura in caso fosse necessario ulteriore supporto.
Grazie.
