### ISSUE TITLE
richiesta incontro: servizio di Validazione esposto da INI

### ISSUE THREAD

**Issue by azienda-zero** [ministero-salute/it-fse-support#1196]
Buongiorno, 
in merito al sistema di approvvigionamento dei certificati (per l’autenticazione e la firma delle asserzioni da parte degli operatori) ed all'architettura approvata dal DTD per la regione del Veneto, vi chiediamo se è possibile organizzare un incontro in modo da dipanare alcuni dubbi necessari per lo sviluppo delle componenti previste.
Grazie e cordiali saluti
Andrea Garato (andrea.garato@azero.veneto.it)

**Comment by vigliottim** [comment]
Buonasera,
la chiediamo gentilmente di inoltrare la sua richiesta all'indirizzo e-mail: [FSE-PNRR@innovazione.gov.it](mailto:FSE-PNRR@innovazione.gov.it)
Grazie.
