### ISSUE TITLE
Crash Program - Errore sostituzione e pubblicazione contestuale

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#1197]
Buona sera non campiamo l'errore

{"traceID":"14dee048a1e92148","spanID":"14dee048a1e92148","type":"/msg/generic-error","title":"Errore generico.","detail":"Index: 0, Size: 0","status":500,"instance":""}

**Comment by LucaRogledi** [comment]
Buongiorno, 
l'errore potrebbe essere dovuto alla mancanza di `Content-Type: application/json` all'interno della sezione requestBody.
Dalle nostre verifiche il sistema riceve quanto riportato per la requestBody:

![image](https://github.com/user-attachments/assets/629f6b66-d987-4f1e-9fcf-3f92a04c0f45)

La invitiamo a riprovare la chiamata con la modifica riportata di seguito assicurandosi inoltre di allegare il file pdf ad ogni nuova  chiamata:
![image](https://github.com/user-attachments/assets/86d46a2b-aa13-401a-9c92-57ce47e255e7)

Restiamo a disposizione in caso l'errore dovesse ripresentarsi. 
Grazie

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
La invitiamo a riaprirla nel caso necessiti di ulteriore supporto.
Grazie.

**Comment by SonnyMate** [comment]
Buongiorno,
scusate ma per molte altre regioni funziona correttamente...

{"traceID":"d426970d1ad81c08","spanID":"d426970d1ad81c08","type":"/msg/generic-error","title":"Errore generico.","detail":"Index: 0, Size: 0","status":500,"instance":""}

**Comment by SonnyMate** [comment]
Ciao,
al momento solo sardegna e piemonte ci rispondono in questo modo

**Comment by vigliottim** [comment]
> Ciao, al momento solo sardegna e piemonte ci rispondono in questo modo

@FSESardegna @marco-volpe 

Chiediamo alle regioni RDA di riferimento di svolgere le verifiche in merito all'errore segnalato.
Grazie.

**Comment by marco-volpe** [comment]
Buongiorno

potreste rifare un test e dirci gli estremi del documento provato a pubblicare in modo da verificare cosa accade sui nostri sistemi?

Grazie

**Comment by SonnyMate** [comment]
Pubblicazione
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-13T10:59:53.610+01:00",
            "eventStatus": "SUCCESS",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.41201.4.4.1.5fd81643bdb18b727b0362f85b8e0c5b68c7b09899b9c5347001645a9f1f780d.95189fe739^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-13T10:59:53.620+01:00"
        }
    ]

Id del documento pubblicato: 2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_000000000104

Id del documento per la replace: 2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_000000000105

{"traceID":"cfe668d501e553ad","spanID":"cfe668d501e553ad","type":"/msg/generic-error","title":"Errore generico.","detail":"Index: 0, Size: 0","status":500,"instance":""}

**Comment by SonnyMate** [comment]
Sardegna -> OK
Piemonte -> ancora KO

**Comment by SonnyMate** [comment]
{
            "eventType": "DESERIALIZE",
            "eventDate": "2024-11-13T14:22:50.188+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "{\"idDoc\":\"2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_000000000001\",\"uuid\":[\"urn:uuid:0589fd7a-0743-44a6-b78e-9cd76c445c1b\"],\"sub\":\"PSCRNI82B64A952I^^^&2.16.840.1.113883.2.9.4.3.2&ISO\",\"iss\":\"integrity:S2#041#PABOLZANOTEST\",\"subject_organization\":\"P.A. Bolzano\",\"subject_organization_id\":\"041\",\"locality\":\"LABORATORIO DI PROVA^^^^^&2.16.840.1.113883.2.9.4.1.3&ISO^^^^111101123456\",\"subject_role\":\"AAS\",\"person_id\":\"SCLSCL00A55G273T^^^&2.16.840.1.113883.2.9.4.3.2&ISO\",\"purpose_of_use\":\"UPDATE\",\"action_id\":\"DELETE\",\"resource_hl7_type\":\"('11502-2^^2.16.840.1.113883.6.1')\",\"patient_consent\":true,\"documentType\":\"UNKNOWN_DOCUMENT_TYPE\",\"subject_application_id\":\"CONCERTO\",\"subject_application_vendor\":\"DEDALUS SPA\",\"subject_application_version\":\"22.1.1\",\"workflow_instance_id\":\"9e1848dbe38cbaf788813b468a6a6847123eaa06a847d5180a98b4d05295cf92.5c3053681d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId\",\"administrative_request\":[],\"author_institution\":\"UNKNOWN_AUTHOR_INSTITUTION\"}",
            "workflowInstanceId": "9e1848dbe38cbaf788813b468a6a6847123eaa06a847d5180a98b4d05295cf92.5c3053681d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-13T14:22:50.202+01:00"
        }
        
ID doc 2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_000000000001

**Comment by marco-volpe** [comment]
Buongiorno @SonnyMate 
per il doc **2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_000000000001** abbiamo ricevuto una comunicazione metadati.

L'errore l'avete avuto in fase di aggiornamento o di cancellazione? Noto nel json serializzato questa informazione

`
"author_institution\":\"UNKNOWN_AUTHOR_INSTITUTION\"
`

State provando con l'utente **PSCRNI82B64A952I**, potrebbe non essere censito correttamente all'interno del GTW come autore.
Potete provare usando come autore **PROVAX00X00X000Y** ?

Grazie, resto a disposizione

**Comment by vigliottim** [comment]
Buon pomeriggio @SonnyMate,
potrebbe gentilmente offrire supporto?
Grazie.
