### ISSUE TITLE
Crash Program - Chiarimenti replace

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#1199]
Buona sera,
ci siamo accorti che una regione nel servizio di replace del documento non accetta lo stesso uniqueID

        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-10-31T23:09:42.776+01:00",
            "eventStatus": "SUCCESS",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.41201.4.4.1.889e4fc661c3a9eb0093ebe1bd5962d0d4833129112f799d544533a9473526f4.31241ade5c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-10-31T23:09:42.787+01:00"
        }

**Comment by LucaRogledi** [comment]
Buongiorno,
dalle nostre verifiche sembrerebbe che la chiamata di replace è avvenuta con successo.
Potrebbe gentilmente verificare e riportare l'errore se presente?
Grazie

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
La invitiamo a riaprirla nel caso necessiti di ulteriore supporto.
Grazie.
