### ISSUE TITLE
SCHEMATRON LDO- ERRORE 122 Stato clinico Problema (allergia)

### ISSUE THREAD

**Issue by giuseppe-fasulo** [ministero-salute/it-fse-support#12]
ERRORE-122| Sezione Allergie: l'elemento 'value' all'interno di entryRelationship/observation (Stato dell'allergia) deve essere valorizzato secondo il value set "StatoClinicoAllergia" (@codesystem='2.16.840.1.113883.6.1')

La segnalazione è analoga ad un caso esposto in precedenza, Il value set Stato clinico problema  OID 2.16.840.1.113883.2.9.77.22.11.7
https://art-decor.org/art-decor/decor-valuesets--hl7it-?id=2.16.840.1.113883.2.9.77.22.11.7
L'asserzione di controllo
assert test="count(hl7:observation/hl7:value[@codeSystem='2.16.840.1.113883.6.1'])=1"
 verifica che sia utilizzato OID del value set estensivo LOINC  e non  l'oID 2.16.840.1.113883.2.9.77.22.11.7
Così facendo non si rischia che siano accettati anche codici LOINC che non dovrebbero passare?

**Comment by LeonardoAlcaro** [comment]
Ciao Giuseppe, nel caso in questione viene controllato il codice LOINC a monte 33999-4 inerente allo stato.
Di conseguenza permette di accettare solo quella codifica, sul value Set si fa riferimento ad un OID 2.16.840.1.113883.2.9.77.22.11.7 che e' del PSS ed in status draft e non active. 
Sicuramente potrebbe, successivamente(in active)essere un controllo di miglioria sul value Set del code LOINC in questione.

Grazie della segnalazione
