### ISSUE TITLE
errore "PDF_UNEXPECTED_CDA"

### ISSUE THREAD

**Issue by g-polverini** [ministero-salute/it-fse-support#120]
Buongiorno,
il nostro primo tentativo di accreditamento (pull request 13, `accreditamento SID srl - SICO`) non è andato a buon fine, ma ci sono due cose che non capisco:
1. della pull request è stato fatto il merge, facendomi pensare che fosse tutto a posto, poi è arrivata la mail di mancato accreditamento;
2. tra gli errori segnalati c'era il seguente
```json
{
  "id": 6,
  "error": "PDF_UNEXPECTED_CDA",
  "description": "CDA contenuto nel PDF non conforme a quello associato al TraceID"
}
```
I dati nella checklist e in data.json sono però inseriti direttamente a partire dalla risposta del gateway, quindi l'errore è abbastanza inaspettato. Da che può derivare?
Gli altri errori segnalati erano invece giusti e li ho corretti, aprendo nel frattempo un'altra pull request, la 49 (l'errore in questione mi era sfuggito, e pensavo di aver corretto tutto), quindi spero non si verifichi di nuovo.

**Comment by Ser-ena** [comment]
Buongiorno, in relazione alla prima domanda la merge viene effettuata quando risultano ok le verifiche preliminari sulla compilazione della checklist. A valle di queste si passa poi alla fase delle verifiche automatizzate che controllano puntualmente i test dichiarati e il contenuto dei json caricati. L'errore segnalato è relativo proprio a questa fase e dipende dal fatto che risultano delle incongruenze tra il cda con il quale ha invocato il gtw e quello con cui ha fatto la push su github.

**Comment by g-polverini** [comment]
Buongiorno,
allora si vede che è andato storto qualcosa nella composizione dei risultati dei test della prima volta.
Comunque adesso, con la nuova pull request, mi trovo con un solo errore:
```
[ {
  "error" : "TEST_NON_PRESENTE",
  "description" : "Test mancanti rispetto alla checklist:[9]"
} ]
```
Nella checklist il test con Id 9 ha "NO" nella colonna K (APPLICABILITA'), e una spiegazione nella M (RAZIONALE DI APPLICABILITA'), quindi non penso di dover fornire altro. Infatti per gli altri test non applicabili ho fatto altrettanto e non mi sono segnalati come errori.
Cosa mi sfugge?

**Comment by masciamariotti** [comment]
Buongiorno,
da ulteriori verifiche risulta che in data 9 Marzo dovrebbe aver ricevuto nuovo esito dei test con i seguenti errori:
`{\n  \"id\" : 6,\n  \"error\" : \"FILE_DICHIARATO_NON_PRESENTE\",\n  \"description\" : \"File dichiarato nel test non presente nella folder FILES.:VALIDAZIONE_CDA2_LDO_CT1_signed.pdf\"\n}, {\n  \"id\" : 7,\n  \"error\" : \"FILE_DICHIARATO_NON_PRESENTE\",\n  \"description\" : \"File dichiarato nel test non presente nella folder FILES.:VALIDAZIONE_CDA2_LDO_CT2_signed.pdf\"\n}, {\n  \"id\" : 8,\n  \"error\" : \"FILE_DICHIARATO_NON_PRESENTE\",\n  \"description\" : \"File dichiarato nel test non presente nella folder FILES.:VALIDAZIONE_CDA2_LDO_CT3_signed.pdf\"\n}`

Potrebbe verificare se ha ricevuto la mail, ed effettuare nuova pull request correttiva?
Grazie

**Comment by g-polverini** [comment]
Buongiorno,
la mail l'ho ricevuta, ed è il motivo per il quale ho chiesto su slack se i
file firmati dovessero allora essere indicati in data.json con il path (es:
SIGNED/VALIDAZIONE_CDA2_LDO_CT1_signed.pdf) o se non dovessero essere
indicati nel json, ma dovessero avere il nome del file identico alla
versione non firmata (quindi ad es: VALIDAZIONE_CDA2_LDO_CT1.pdf)
Quindi per procedere devo togliere i nomi dei file e anche la cartella
SIGNED?
I file firmati serviranno solo quando ci sarà la fase di pubblicazione?
Grazie

Il giorno mar 14 mar 2023 alle ore 12:41 masciamariotti <
***@***.***> ha scritto:

**Comment by IStacchiotti** [comment]
Buongiorno, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
