### ISSUE TITLE
Firma documento in fase di pubblicazione

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#1200]
Buongiorno, leggo e riporto dalla documentazione:
![image](https://github.com/user-attachments/assets/63b086ab-5ff6-4e6e-a5e9-8dc10a1b0bdf)
La domanda è: la firma del file Pdf deve essere del Medico che ha redatto il documento o può essere della Struttura a cui appartiene il Medico?
Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, 
Come riportato nella [issue 1086](https://github.com/ministero-salute/it-fse-support/issues/1086#issuecomment-2428839025),
le logiche di firma del documento non sono a carico del Gateway e sono ampiamente conosciute dalle softwarehouse oltre che dagli utilizzatori.

Se servono informazioni potete provare a chiedere alla Regione di riferimento, purtroppo non possiamo aiutarla sulla tematica.
Grazie!
