### ISSUE TITLE
Regione Sardegna pubblicazione documento - Regione veneto

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#1203]
Buongiorno,
abbiamo effettuato un tentativo di pubblicazione verso la vostra regione sul CF SQTPRV80A54I799T

traceId: 6728a379b25ccbb63fcf79ded3147f2e
DocumentEntry.uniqueId: 2.16.840.1.113883.2.9.4.3.8^200106SQTPRV80A54I799T20241104113041958800

workflowInstanceId:  2.16.840.1.113883.2.9.2.120.4.4.b8f8b6c64fcf87949cd78a214dfe92b95036e0e3411714e954c29c6d689fa19a.915e8a6743^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

successivamente, controllando l'esito stato transazione otteniamo il seguente errore:
 message=SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.

Vi chiediamo gentilmente di eseguire una verifica sul problema riscontrato per identificare le cause dell’errore,

Rimaniamo a disposizione

**Comment by vigliottim** [comment]
@azienda-zero

Buongiorno,
chiediamo cortesemente alla regione Veneto di fornire supporto.
Grazie.

**Comment by mikeben89** [comment]
Buonasera,
abbiamo effettuato alcune verifiche. Potete riprovare la pubblicazione?

Grazie.

**Comment by FSESardegna** [comment]
Buongiorno,
abbiamo eseguito nuove prove e sono andate tutte in SUCCESS.
grazie
