### ISSUE TITLE
Regione Sardegna - Pubblicazione - verso Regione Liguria

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#1204]
Buongiorno,
abbiamo effettuato un tentativo di pubblicazione verso la regione

traceId: 6720bc4398fed11ba73a7ed946f87323
DocumentEntry.uniqueId: 2.16.840.1.113883.2.9.4.3.8^200106CQTDLT66H01Z356V20241029114046695244

workflowInstanceId: 2.16.840.1.113883.2.9.2.120.4.4.4b68a45d8440b544ebb28a2a6f2559d76caf7fbea747a3c5cd121921fcde9cef.b48810e5fa^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
successivamente, controllando l'esito stato transazione otteniamo il seguente errore:
SEVERITY: message=SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.

Vi chiediamo gentilmente di eseguire una verifica sul problema riscontrato per identificare le cause dell’errore e supportarci nella risoluzione, al fine di consentire il corretto completamento della pubblicazione.

Rimaniamo a disposizione

**Comment by izamberlan** [comment]
salve,

come comunicato in altre issue e in sede di SAL, il nostro sistema controlla che il codice fiscale autore sia valido e quello utilizzato non è formalmente un codice fiscale valido. Potete riprovare con un qualsiasi codice fiscale formalmente corretto, anche fittizio, come autore del documento? Grazie!

**Comment by FSESardegna** [comment]
Buongiorno,

durante una nuova pubblicazione di un documento abbiamo inserito un Codice Fiscale formalmente corretto, come da voi suggerito, e la transazione è stata eseguita con successo. Ecco i dettagli:
```
DocumentID: 2.16.840.1.113883.2.9.4.3.8^200106CQTDLT66H01Z356V20241104152625014417
WII: 2.16.840.1.113883.2.9.2.120.4.4.f1d0891a68d1a90dfff2e0d2cf7519d7dc4af355c2c63312c2c14b8d9bd0589a.d42ccac82c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
TraceId: 6728da7a51c1f3243ad2c4a4d40536f9
Esito Stato transazione: SUCCESS
```
Successivamente, abbiamo effettuato una transazione di tipo Replace per sostituire il documento pubblicato in precedenza, ma questa operazione ha generato un errore. Di seguito i dettagli:

```
DocumentID: 2.16.840.1.113883.2.9.4.3.8^200106CQTDLT66H01Z356V20241104153727996269
WII: 2.16.840.1.113883.2.9.2.120.4.4.de1d7ce6e67532ff074ee055b63f224d66b82e0e10f8416b86b373fdb2a29439.c864cf5e0e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
TraceId: 6728dcf241f99b25432337f087645449
Esito verifica stato transazione: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error ERROR_CODE:CRF2 CODE_CONTEXT: RDA generated an internal error.
```

@izamberlan

**Comment by izamberlan** [comment]
Molto strano, i due documenti risultano correttamente processati lato nostro. Chiedo a @vigliottim @LucaRogledi se il fatto che l'ambiente di test nostro abbia risposto in oltre otto secondi possa essere il problema.

**Comment by izamberlan** [comment]
Aggiungo: neanche l'ipotesi del timeout è plausibile, la risposta alla GetDocuments ObjectRef di recupero riferimenti è sotto il secondo. Dai nostri log abbiamo risposto con l'uuid del documento da sostituire come nei casi funzionanti.

**Comment by vigliottim** [comment]
Buonasera,
il timestamp della comunicazione della replace è il seguente: 04/11/2024 15:40:53,775000
A sistema tale chiamata va in errore.
Effettueremo maggiori approfondimenti lato INI.
Grazie.

**Comment by izamberlan** [comment]
salve,
il CF assistito è quello configurato per il crash program:
CQTDLT66H01Z356V
L'authnInstant dell'asserzione SAML per la ricerca è 2024-11-04T14:40:51.804Z

La replace NON è fallita lato nostro (Liguria, RDA).

**Comment by g-maugeri-sogei** [comment]
Buonasera,
su INI risulta un SAOP FAULT in risposta alla request in allegato.Puo' la Liguria fornire la response con esito positivo in risposta lalla chiamata?

```
2024-11-04 15:40:59,238 INFO [it.finanze.sogei.fse.client.headerHandler.HeaderHandler] - HANDLE FAULT SOAP :
 
2024-11-04 15:40:59,239 INFO [it.finanze.sogei.fse.client.headerHandler.HeaderHandler] - <S:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:S="http://www.w3.org/2003/05/soap-envelope"><S:Header><To xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</To><Action xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/fault</Action><MessageID xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:3d77bc9e-709e-c764-a559-db51887725a4</MessageID><RelatesTo xmlns="http://www.w3.org/2005/08/addressing">ef20deee-75c9-4995-8955-1eec778e6886</RelatesTo></S:Header><S:Body><S:Fault xmlns:ns4="http://schemas.xmlsoap.org/soap/envelope/"><S:Code><S:Value>S:Sender</S:Value></S:Code><S:Reason><S:Text xml:lang="en">An unexpected error occurred</S:Text></S:Reason><Detail xmlns="http://www.w3.org/2003/05/soap-envelope"><wsse:SecurityTokenUnavailable xmlns:wsse="http://docs.oasisopen.org/wsrf/r-2" xmlns:wsrf-bf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:schemaLocation="http://docs.oasisopen.org/wsrf/bf-2 bf-2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><wsrf-bf:Timestamp>2024-11-04T15:40:59.259</wsrf-bf:Timestamp><wsrf-bf:ErrorCode dialect="http://www.fascicolosanitario.gov.it/interop-errorcodes">101504</wsrf-bf:ErrorCode><wsrf-bf:Description>Send timeout</wsrf-bf:Description></wsse:SecurityTokenUnavailable></Detail></S:Fault></S:Body></S:Envelope> 
2024-11-04 15:40:59,241 ERROR [it.finanze.sogei.fse.client.facade.Me
```

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, la presente issue viene chiusa.
Sarà possibile riaprirla nel caso in cui sia necessario ulteriore supporto.
Grazie.

**Comment by izamberlan** [comment]
salve,

non so se rispondere riapra la issue, non trovo il tasto per riaprire.
Abbiamo riscontrato un nostro timeout interno, probabilmente dovuto ad una condizione transiente. Chiederei a @FSESardegna di riprovare.
Non capiamo però la sequenza e chiediamo a @vigliottim @LucaRogledi . Apparentemente vengono fatte due ricerche , una objectRef sull'interfaccia di recupero riferimenti e una LeafClass sull'interfaccia normale di ricerca. Quella che fallisce è la LeafClass. Ma in questo contesto la LeafClass è evidentemente inutile, dato che poi (anche se la trace riporta una failure) la sequenza procede e il documento viene sostituito con l'uuid ritornato dalla objectRef inserito correttamente nella association di tipo RPLC.
Crediamo sarebbe importante ritornare failure se effettivamente la transazione è fallita.

**Comment by vigliottim** [comment]
@izamberlan

Buonasera,
in fase di replace il GTW effettua solo il recupero dei riferimenti.
Può inviarci ulteriori dettagli per svolgere le verifiche.
Grazie.

**Comment by izamberlan** [comment]
Scusate, avete ragione. La failure è relativa ad una request precedente la transazione.

A questo punto però non mi spiego l'errore su questa transazione. Nei log più "di frontiera" di cui dispongo trovo questa response alla richiesta di recupero riferimenti:
<?xml version='1.0' encoding='utf-8'?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Header><To xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</To><Action xmlns="http://www.w3.org/2005/08/addressing">urn:ihe:iti:2007:RegistryStoredQueryResponse</Action><MessageID xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:0a638b72-1264-bcec-9592-c9df2fdb30c3</MessageID><RelatesTo xmlns="http://www.w3.org/2005/08/addressing">08a0d7d1-d049-4e82-93ea-dac0a64e6aac</RelatesTo></soap:Header><soap:Body><ns3:AdhocQueryResponse xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns4="urn:ihe:iti:xds-b:2007" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Success"><RegistryObjectList><ObjectRef id="urn:uuid:eca68507-9b86-4ecb-95dc-072eae44ec8d"/></RegistryObjectList></ns3:AdhocQueryResponse></soap:Body></soap:Envelope>

Al che ripropongo la domanda: dato che la sostituzione avviene, perché c'è una failure?

**Comment by izamberlan** [comment]
Aggiungo anche la request come risulta a noi:
'<?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"><soapenv:Header xmlns:wsa="http://www.w3.org/2005/08/addressing"><wsa:Action>urn:ihe:iti:2007:RegistryStoredQuery</wsa:Action><wsa:MessageID>08a0d7d1-d049-4e82-93ea-dac0a64e6aac</wsa:MessageID><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xs="http://www.w3.org/2001/XMLSchema" ID="_7f21d05c-008f-4e07-bd4f-b14ae76aad4d" IssueInstant="2024-11-04T14:40:51.804Z" Version="2.0"><saml2:Issuer>integrity:S1#200#FSESARDEGNA-TEST</saml2:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><ds:Reference URI="#_7f21d05c-008f-4e07-bd4f-b14ae76aad4d"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="xs"/></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><ds:DigestValue>O5r+kikKESTS+sSbv8UPVyuwnQg=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>GyFwj4rp5FpJ/r2EVFlg0iQOUWffJ2k/JqaOdUtVPN/KUMxzJEQSEb6N+yK+5U8z2W3kg+gM4Enhr9EYNdm1h6O+1nwR1ZhPuE9bGovJ3YW5cwlSdgaYMpUtSPF3srQZ8N4v/UWoyU1B20bnUKxsJMt45AkOr6Un7+EWyl9BcMuBMBoFHF51ms5eFhk4p5zwLmie5SsGI0u2lxzSSINA1PU9gfC8zsEBTy9P+2G1YGhzdHm/3GX68EYGS/3stQ+cX07MFS6grP3ZGiI45UhN5vQCQrTG32Htp9kOWgWBEtEZfuuCkKwCHZOmX/bnpXmTPjkIfAKVAEvZ6U6vl3Z+sA==</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIE+TCCAuGgAwIBAgIIRHtGTdUftugwDQYJKoZIhvcNAQELBQAwSjELMAkGA1UEBhMCSVQxDjAMBgNVBAoMBVNvZ2VpMSswKQYDVQQDDCJTb2dlaSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eSBUZXN0MB4XDTI0MDExNjE1NTEzN1oXDTI3MDExNjE1NTEzNlowXTELMAkGA1UEBhMCSVQxDjAMBgNVBAoMBVNvZ2VpMRAwDgYDVQQLDAdTYW5pdMOgMSwwKgYDVQQDDCM5OTk5NTAwMDAwMDAvRlNFIEZEIEdBVEVXQVkgVEVTVC8wMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALdoiNc/iZEnW7/dQF0BsLJv73WhmCUK6/wdUvxcUBTayOaw1l34mZESFLmC2d/8JeMzkkRotCDhD+gzMkyOI47Zh/zdBdxmaRQgE8WMIASgFl14gkx/HHdzOKBS75TW2R3mcHJZHtCHfFbkzBm88loo6/HOrzZ1Zyd7U6OAJT/Is8S2rPUkrxXcsR82t2LeuIuuefkPxaF2+cmEJ2nbGCT0XxmBmaF93Mqme+BME2k3BekjFlTuqR37KSO3kPVdea3yOeo6hCfkTc+qwy1Md0RyWkEAJDWYpuLrBWVY1le42f9YIInSIvVzT1NgoAsjGeBgRGHSpFzvVBcIK3jhvVECAwEAAaOBzzCBzDAfBgNVHSMEGDAWgBTGllMVsxcbeaMSZu3K1vRBVTTxITB6BgNVHR8EczBxMG+gbaBrhmlsZGFwOi8vY2Fkcy5maW5hbnplLml0L0NOPVNvZ2VpJTIwQ2VydGlmaWNhdGlvbiUyMEF1dGhvcml0eSUyMFRlc3QsTz1Tb2dlaSxDPUlUP2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3QwHQYDVR0OBBYEFEooXAIW+Ze8P51pHUaLK08+iF6eMA4GA1UdDwEB/wQEAwIGQDANBgkqhkiG9w0BAQsFAAOCAgEAfVooERvZUeBQC+ICC3+Xtn5DU+nZv3sjEcd4Bqfyd1cOM14mYDsvFRO8ibDFZUT2DN2dqksH0D+qLALsuvoOHapZgN46nZwrBlVKFsYNqnVyym5+gArUEDcEhbD00O3fBFRR2UZuJZh4XVPln7pDX73aM34grFM4zyd0tmsWjxdYXph65Xi2o2mKf7wFLSJ8+meODPHWeXzcLBYouZ0BqafNpUa4J9BkzVQ5Bam7rR+x10txDz5+RjjfpvzpKC1eP4qECmv2zjeTkpyS5kXmcUUCrZhgZSFWV+gzZlYtj5ZBcJgcvjbRSdQLpSr1s1SySSG+QW2A4VoipdXId9lPp8LU0ltIWVji2MY8KW5PqmNBULSHCjax+LvDXrUSpJ3geC3LZCMdY+nylPjJKtCWvscSW7p5caz+dY6pXA07TNwfME5SS7UmyJTVI7GKSbuTIW8KQzCSDj6rKUsl1A6UdvF6bJ2eBgJTKKAk4W9cecLNM9FybzGby0jOd9dccl9ZD4zk1o8PDTpt+xB/+M4Gn1qMpHE79s1ZhLMvTR7FzqgnChFH160BXuGm8pvTfoQkJ53RM2+zfMRrUiOtfRHG8PfsWBNvIWipQ1n2bUiVlgT32wX+unZduZHy8NyV0mouBXCNjaQsH9rexY0C7Tq8ce26cykXiTbUGuMLuK1io0U=</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature><saml2:Subject><saml2:NameID>CGNNMO37L20F592Z^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</saml2:NameID></saml2:Subject><saml2:Conditions NotBefore="2024-11-04T14:40:51.804Z" NotOnOrAfter="2025-11-04T14:40:51.804Z"/><saml2:AuthnStatement AuthnInstant="2024-11-04T14:40:51.804Z"><saml2:AuthnContext><saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:X509</saml2:AuthnContextClassRef></saml2:AuthnContext></saml2:AuthnStatement><saml2:AttributeStatement><saml2:Attribute Name="urn:oasis:names:tc:xspa:1.0:resource:patient:consent" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"><saml2:AttributeValue xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">true</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name="urn:oasis:names:tc:xspa:1.0:resource:hl7:type" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"><saml2:AttributeValue xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">('60591-5^^2.16.840.1.113883.6.1')</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name="urn:oasis:names:tc:xacml:2.0:subject:role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"><saml2:AttributeValue xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">AAS</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name="urn:oasis:names:tc:xspa:1.0:environment:locality" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"><saml2:AttributeValue xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">2.16.840.1.113883.2.9.4.1.3.200201</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name="urn:oasis:names:tc:xspa:1.0:subject:purposeofuse" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"><saml2:AttributeValue xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">UPDATE</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name="urn:oasis:names:tc:xspa:1.0:subject:organization-id" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"><saml2:AttributeValue xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">200</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name="urn:oasis:names:tc:xacml:1.0:subject:subject-id" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"><saml2:AttributeValue xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">CGNNMO37L20F592Z^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name="urn:oasis:names:tc:xspa:1.0:subject:organization" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"><saml2:AttributeValue xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">Regione Sardegna</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name="urn:oasis:names:tc:xacml:1.0:resource:resource-id" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"><saml2:AttributeValue xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">CQTDLT66H01Z356V^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name="urn:oasis:names:tc:xacml:1.0:action:action-id" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"><saml2:AttributeValue xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">READ</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name="SubjectApplicationId" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml2:AttributeValue xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">Middleware200</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name="SubjectApplicationVendor" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml2:AttributeValue xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">Regione Sardegna</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name="SubjectApplicationVersion" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml2:AttributeValue xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">V.1.0</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name="SubjectAuthenticator" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml2:AttributeValue xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">GTW_950</saml2:AttributeValue></saml2:Attribute></saml2:AttributeStatement></saml2:Assertion></wsse:Security><wsa:To>https://fseservicetest.sanita.finanze.it/FSEFindDocumentReferencesWeb/DocumentRegistry_Service_esterno</wsa:To></soapenv:Header><soapenv:Body><ns5:AdhocQueryRequest xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns6="urn:hl7-org:v3" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns4="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" federated="false" maxResults="-1" startIndex="0"><ns5:ResponseOption returnComposedObjects="true" returnType="ObjectRef"/><ns2:AdhocQuery id="urn:uuid:5c4f972b-d56b-40ac-a5fc-c8ca9b40b9d4"><ns2:Slot name="$XDSDocumentEntryUniqueId"><ns2:ValueList><ns2:Value>('2.16.840.1.113883.2.9.4.3.8^200106CQTDLT66H01Z356V20241104152625014417')</ns2:Value></ns2:ValueList></ns2:Slot></ns2:AdhocQuery></ns5:AdhocQueryRequest></soapenv:Body></soapenv:Envelope>
'

**Comment by izamberlan** [comment]
Scusate, ho individuato ora il problema. E' un nostro timeout, la response in errore non era relativa alla recupero riferimenti ma alla comunicazione fra due apparati nella transazione di indicizzazione.

Chiedo a Regione Sardegna di riprovare.

**Comment by FSESardegna** [comment]
Buongiorno,

a seguito dell’esecuzione di una nuova prova, riporto di seguito i relativi dettagli:

```
DocumentId: 2.16.840.1.113883.2.9.2.200.4.4^200106CQTDLT66H01Z356V20241113110229176719
WII: 2.16.840.1.113883.2.9.2.200.4.4.9962e6ef57974b068b736a757a27a4e9572cad08d29592f3f58c3ff01bd1f272.3cf1d77e16^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
TraceId: 67347b802c7b03c0fb8ed4a4a83d233d
VerificaTransazione: SUCCESS
```
Procedendo con una richiesta ITI-18 getDocumenti di tipo LeafClass per controllo, otteniamo il seguente esito: `PFA11 Missing Consultation Consent.`

Successivamente, effettuando una sostituzione con i seguenti parametri:

```
DocumentId: 2.16.840.1.113883.2.9.2.200.4.4^200106CQTDLT66H01Z356V20241113111901387645
WII: 2.16.840.1.113883.2.9.2.200.4.4.8f2f684966a955c1467fc9f4b8c2b9f508c5ac19e28aabd8a6019263f11786e4.9f7c3deb61^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
TraceId: 67347e6ce29dc9486b61978ae1338e20
```
riceviamo la seguente risposta:

```
{
  "spanID": "315599d31dae5fd3",
  "type": "/err/resource",
  "title": "Resource error",
  "detail": "Id documento non presente",
  "status": 404,
  "instance": "/not-found"
}
```
Rimango a disposizione per ulteriori chiarimenti.

**Comment by izamberlan** [comment]
E' tutto piuttosto strano, il documento risulta inserito in FSE lato nostro. La response sul documento non trovato non sembra essere la nostra.
Il consenso alla consultazione era stato effettivamente revocato. Ora dovrebbe essere di nuovo OK

**Comment by izamberlan** [comment]
> ```
> DocumentId: 2.16.840.1.113883.2.9.2.200.4.4^200106CQTDLT66H01Z356V20241113110229176719
> WII: 2.16.840.1.113883.2.9.2.200.4.4.9962e6ef57974b068b736a757a27a4e9572cad08d29592f3f58c3ff01bd1f272.3cf1d77e16^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

deve esserci qualche disallineamento, indagando abbiamo interrogato lo status per il workflowInstanceId di cui sopra troviamo solo la validazione e non la pubblicazione (nessuno step). Il che è strano perché da noi un documento con quell'identificativo risulta indicizzato.

@LucaRogledi @vigliottim potete fare altre verifiche?

**Comment by izamberlan** [comment]
OK, resta da capire perché ha risposto 404.
@FSESardegna potete riprovare query e sostituzione?

**Comment by FSESardegna** [comment]
Abbiamo eseguito nuovamente la Sostituzione ma non è andata a buon fine,  la query ci ritorna l'errore precedente `"PFA11 Missing Consultation Consent"`

**Comment by izamberlan** [comment]
scusate, c'è stato un disguido interno, il consenso era stato nuovamente portato a false. Ora dovrebbe essere stato ripristinato.

**Comment by FSESardegna** [comment]
Buongiorno,
abbiamo eseguito delle nuove prove, si seguito i dettagli:
ITI-41
```
DocumentId: 2.16.840.1.113883.2.9.2.200.4.4^200106CQTDLT66H01Z356V20241114093828570049
WII: 2.16.840.1.113883.2.9.2.200.4.4.377ee703a71e7d17d8044858b064dcea0cd196d8fcfb3555311e59c6aecb45d5.c24934c016^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
TraceId: 6735b7caab501529101bef6e1a2cc9dd
VerificaTransazione: SUCCESS```
eseguendo la ITI-18 getDocument di tipo LeafClass  otteniamo `"RDA generated an internal error." errorCode="CRF2"`

Prova di sostituzione: 
```
DocumentId: 2.16.840.1.113883.2.9.2.200.4.4^200106CQTDLT66H01Z356V20241114094716708434
WII: 2.16.840.1.113883.2.9.2.200.4.4.d108c92e19dbf12525273df85de698f0a2ce36b4549e241bc6c5b6ab62fca316.be671c9f28^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
TraceId: 6735b99ccd4cc93ea5dd0c99b8dc3172
VerificaTransazione: SUCCESS
```
ma eseguendo la ITI-18 getDocument di tipo LeafClass  otteniamo `"RDA generated an internal error." errorCode="CRF2"`

Prova di cancellazione:
```
DocumentId:  2.16.840.1.113883.2.9.2.200.4.4^200106CQTDLT66H01Z356V20241114094716708434
TraceId: 6735ba28e401b07b9415dbe02c8a4627
VerificaTransazione: SUCCESS
```
ma eseguendo la ITI-18 getDocument di tipo LeafClass  otteniamo `"RDA generated an internal error." errorCode="CRF2"`.

Potete verificare se le tre transazioni sono andate a buon fine?
Rimaniamo a disposizione.

**Comment by izamberlan** [comment]
Pubblicazione 200106CQTDLT66H01Z356V20241114093828570049 OK (scusate se metto solo l'extension)
Pubblicazione (per sostituzione) di 200106CQTDLT66H01Z356V20241114094716708434 OK
Sua cancellazione OK
Le ricerche per recupero riferimenti (ovviamente) OK
Non trovo traccia nell'audit log delle ricerche leafClass, eventualmente faccio avere notizie in seguito a controlli anche sui sistemi di frontiera.

**Comment by izamberlan** [comment]
Se potete, riprovate la query eliminando i "mustUnderstand".

grazie

**Comment by vigliottim** [comment]
Buongiorno @FSESardegna,
chiediamo gentilmente di fornire supporto.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso fosse necessario ulteriore supporto. Grazie.
