### ISSUE TITLE
Regione Sardegna - cancellazione documento- vs Regione Puglia

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#1206]
Buongiorno,

in seguito alla cancellazione del seguente documento:

```
DocumentEntry.uniqueId 2.16.840.1.113883.2.9.4.3.8^200106FSEPGL01E41A145J20241021155436612127
tracedId: 6728af2d7f1718e28554d80c02025037
```
 otteniamo il seguente errore
`500 unexpected Error`

Potete supportarci?
Rimaniamo a disposizione.

**Comment by lninnova** [comment]
Buongiorno, potete riprovare a pubblicare un nuovo documento e successivamente procedere alla cancellazione?
Grazie

**Comment by FSESardegna** [comment]
Buongiorno,

è stata effettuata una nuova pubblicazione, i cui dettagli sono riportati di seguito:
```
DocumentID: 2.16.840.1.113883.2.9.4.3.8^200106FSEPGL01E41A145J20241107092740137751
WII: 2.16.840.1.113883.2.9.2.120.4.4.b914fc3c8fd2b8bfa6b3da327fb20cc7f83c26f60f010cdbb2df40ac08ff97ed.f251716faf^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
TraceId: 672c7b19e8de092af4f1269b1a70e3ff
VerificaTransazione: SUCCESS
```
A seguito dell’esito positivo della verifica dello stato della transazione, abbiamo eseguito una richiesta ITI-18 getDocument di tipo LeafClass, che ha restituito un risultato positivo (success), tuttavia con una lista vuota.

Successivamente, è stata effettuata l’operazione di cancellazione (delete). I dettagli sono riportati di seguito:

```
TraceId: 672c7c0fbe1e97d83069fc54913c5dad
VerificaTransazione: SUCCESS,
```

L'operazione sembra essersi conclusa con esito positivo.

**Comment by lninnova** [comment]
Confermo che il documento risulta deprecato sul nostro Registry.
Grazie

**Comment by vigliottim** [comment]
Ringraziamo per il gentile feedback e procediamo alla chiusura della presente issue.
