### ISSUE TITLE
Unauthorized request content

### ISSUE THREAD

**Issue by fnicoletti** [ministero-salute/it-fse-support#121]
in fase di validazione del cda2 riceviamo questo errore:
{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"84780ce1-a6cd-11ed-84b0-005056ae7395"}

**Comment by masciamariotti** [comment]
Buongiorno,
per velocizzare l'analisi, potrebbe allegare i jwt contenuti nell'header della chiamata? Grazie
