### ISSUE TITLE
Regione Basilicata - UC2 Errore Pubblicazione verso RDA=Regione Puglia

### ISSUE THREAD

**Issue by BasilicataCrashProgramFSE** [ministero-salute/it-fse-support#1211]
Buongiorno,

Chiediamo gentilmente una verificare della transazione di pubblicazione dalla Regione Basilicata verso RDA=Regione Puglia che da un errore **CRF2CODE CONTEXT:RDA generated an internal error.**.

Di seguito il caso.
Grazie

{
    "code": "SUCCESS",
    "userMessage": "Operazione conclusa con successo",
    "systemMessage": "",
    "status": 200,
    "traceID": "c0619b972ffb673f",
    "spanID": "f5616c8a52233d4a",
    "transactionData": [
        {
            "eventType": "INI_CREATE_SOAP",
            "eventDate": "2024-11-04T13:14:14.592+0000",
            "eventStatus": null,
            "message": "SOAP_REQUEST:<S:Envelope xmlns:S=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:env=\"http://www.w3.org/2003/05/soap-envelope\"><S:Header><wsa:Action xmlns:wsa=\"http://www.w3.org/2005/08/addressing\">urn:ihe:iti:2007:RegisterDocumentSet-b</wsa:Action><wsa:MessageID xmlns:wsa=\"http://www.w3.org/2005/08/addressing\">9e919800-057b-456d-9d0e-370bebb76dbe</wsa:MessageID><wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"><saml2:Assertion xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" ID=\"_074baa1e-4560-4053-bb68-f85e315f12df\" IssueInstant=\"2024-11-04T13:14:14.598Z\" Version=\"2.0\"><saml2:Issuer>integrity:S1#170#REGIONEBASILICATATEST</saml2:Issuer><ds:Signature xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"/><ds:SignatureMethod Algorithm=\"http://www.w3.org/2001/04/xmldsig-more#rsa-sha256\"/><ds:Reference URI=\"#_074baa1e-4560-4053-bb68-f85e315f12df\"><ds:Transforms><ds:Transform Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"/><ds:Transform Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"><ec:InclusiveNamespaces xmlns:ec=\"http://www.w3.org/2001/10/xml-exc-c14n#\" PrefixList=\"xs\"/></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/><ds:DigestValue>i6KabnruUrwWaZzPafd0PR6Fkro=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>SK9VzAMD8zK622MoD/qm69L0kueqexjFtl+FI1BhsLD7qSCyObwBaKQtCEURXPZLILhtyDVv9hkKkJeXZGBkFJbW18xLy5iWvCPfabtsdbgMLwcrwzl+xC0tvGH4bF4GpcVCNndaRvmMBJru0ODSp6zzbgO1xyiZ0Ewx7fDuOv2CCwV+DdOwQMBkM/O2DGj5wA1i2+hK1TXNgfyBPJl2Ldh9Z1LNuIx22NnoPwkOiqdpIsm/+RM2zJTzhiie2i9jgrWJb9VVCvF5U11XD5HeghuU/D0b4sz5pxNPhfqX+PuRUzMk+IeJz1o7mcv2yZP0eYtQ0A04xiKozCW/2o2Pew==</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIE+TCCAuGgAwIBAgIIRHtGTdUftugwDQYJKoZIhvcNAQELBQAwSjELMAkGA1UEBhMCSVQxDjAMBgNVBAoMBVNvZ2VpMSswKQYDVQQDDCJTb2dlaSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eSBUZXN0MB4XDTI0MDExNjE1NTEzN1oXDTI3MDExNjE1NTEzNlowXTELMAkGA1UEBhMCSVQxDjAMBgNVBAoMBVNvZ2VpMRAwDgYDVQQLDAdTYW5pdMOgMSwwKgYDVQQDDCM5OTk5NTAwMDAwMDAvRlNFIEZEIEdBVEVXQVkgVEVTVC8wMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALdoiNc/iZEnW7/dQF0BsLJv73WhmCUK6/wdUvxcUBTayOaw1l34mZESFLmC2d/8JeMzkkRotCDhD+gzMkyOI47Zh/zdBdxmaRQgE8WMIASgFl14gkx/HHdzOKBS75TW2R3mcHJZHtCHfFbkzBm88loo6/HOrzZ1Zyd7U6OAJT/Is8S2rPUkrxXcsR82t2LeuIuuefkPxaF2+cmEJ2nbGCT0XxmBmaF93Mqme+BME2k3BekjFlTuqR37KSO3kPVdea3yOeo6hCfkTc+qwy1Md0RyWkEAJDWYpuLrBWVY1le42f9YIInSIvVzT1NgoAsjGeBgRGHSpFzvVBcIK3jhvVECAwEAAaOBzzCBzDAfBgNVHSMEGDAWgBTGllMVsxcbeaMSZu3K1vRBVTTxITB6BgNVHR8EczBxMG+gbaBrhmlsZGFwOi8vY2Fkcy5maW5hbnplLml0L0NOPVNvZ2VpJTIwQ2VydGlmaWNhdGlvbiUyMEF1dGhvcml0eSUyMFRlc3QsTz1Tb2dlaSxDPUlUP2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3QwHQYDVR0OBBYEFEooXAIW+Ze8P51pHUaLK08+iF6eMA4GA1UdDwEB/wQEAwIGQDANBgkqhkiG9w0BAQsFAAOCAgEAfVooERvZUeBQC+ICC3+Xtn5DU+nZv3sjEcd4Bqfyd1cOM14mYDsvFRO8ibDFZUT2DN2dqksH0D+qLALsuvoOHapZgN46nZwrBlVKFsYNqnVyym5+gArUEDcEhbD00O3fBFRR2UZuJZh4XVPln7pDX73aM34grFM4zyd0tmsWjxdYXph65Xi2o2mKf7wFLSJ8+meODPHWeXzcLBYouZ0BqafNpUa4J9BkzVQ5Bam7rR+x10txDz5+RjjfpvzpKC1eP4qECmv2zjeTkpyS5kXmcUUCrZhgZSFWV+gzZlYtj5ZBcJgcvjbRSdQLpSr1s1SySSG+QW2A4VoipdXId9lPp8LU0ltIWVji2MY8KW5PqmNBULSHCjax+LvDXrUSpJ3geC3LZCMdY+nylPjJKtCWvscSW7p5caz+dY6pXA07TNwfME5SS7UmyJTVI7GKSbuTIW8KQzCSDj6rKUsl1A6UdvF6bJ2eBgJTKKAk4W9cecLNM9FybzGby0jOd9dccl9ZD4zk1o8PDTpt+xB/+M4Gn1qMpHE79s1ZhLMvTR7FzqgnChFH160BXuGm8pvTfoQkJ53RM2+zfMRrUiOtfRHG8PfsWBNvIWipQ1n2bUiVlgT32wX+unZduZHy8NyV0mouBXCNjaQsH9rexY0C7Tq8ce26cykXiTbUGuMLuK1io0U=</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature><saml2:Subject><saml2:NameID>PROVAX00X00X000Y^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</saml2:NameID></saml2:Subject><saml2:Conditions NotBefore=\"2024-11-04T13:14:14.598Z\" NotOnOrAfter=\"2025-11-04T13:14:14.598Z\"/><saml2:AuthnStatement AuthnInstant=\"2024-11-04T13:14:14.598Z\"><saml2:AuthnContext><saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:X509</saml2:AuthnContextClassRef></saml2:AuthnContext></saml2:AuthnStatement><saml2:AttributeStatement><saml2:Attribute Name=\"urn:oasis:names:tc:xspa:1.0:resource:patient:consent\" NameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:uri\"><saml2:AttributeValue xmlns:type=\"xs:string\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"xs:string\">true</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name=\"urn:oasis:names:tc:xspa:1.0:resource:hl7:type\" NameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:uri\"><saml2:AttributeValue xmlns:type=\"xs:string\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"xs:string\">('34105-7^^2.16.840.1.113883.6.1')</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name=\"urn:oasis:names:tc:xacml:2.0:subject:role\" NameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:uri\"><saml2:AttributeValue xmlns:type=\"xs:string\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"xs:string\">AAS</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name=\"urn:oasis:names:tc:xspa:1.0:environment:locality\" NameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:uri\"><saml2:AttributeValue xmlns:type=\"xs:string\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"xs:string\">2.16.840.1.113883.2.9.4.1.3.170201</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name=\"urn:oasis:names:tc:xspa:1.0:subject:purposeofuse\" NameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:uri\"><saml2:AttributeValue xmlns:type=\"xs:string\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"xs:string\">TREATMENT</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name=\"urn:oasis:names:tc:xspa:1.0:subject:organization-id\" NameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:uri\"><saml2:AttributeValue xmlns:type=\"xs:string\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"xs:string\">170</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name=\"urn:oasis:names:tc:xacml:1.0:subject:subject-id\" NameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:uri\"><saml2:AttributeValue xmlns:type=\"xs:string\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"xs:string\">PROVAX00X00X000Y^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name=\"urn:oasis:names:tc:xspa:1.0:subject:organization\" NameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:uri\"><saml2:AttributeValue xmlns:type=\"xs:string\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"xs:string\">Regione Basilicata</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name=\"urn:oasis:names:tc:xacml:1.0:resource:resource-id\" NameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:uri\"><saml2:AttributeValue xmlns:type=\"xs:string\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"xs:string\">FSEPGL01E41A145J^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name=\"urn:oasis:names:tc:xacml:1.0:action:action-id\" NameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:uri\"><saml2:AttributeValue xmlns:type=\"xs:string\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"xs:string\">CREATE</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name=\"SubjectApplicationId\" NameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:basic\"><saml2:AttributeValue xmlns:type=\"xs:string\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"xs:string\">AMICO</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name=\"SubjectApplicationVendor\" NameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:basic\"><saml2:AttributeValue xmlns:type=\"xs:string\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"xs:string\">GPI_SPA</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name=\"SubjectApplicationVersion\" NameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:basic\"><saml2:AttributeValue xmlns:type=\"xs:string\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"xs:string\">2.22.0</saml2:AttributeValue></saml2:Attribute><saml2:Attribute Name=\"SubjectAuthenticator\" NameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:basic\"><saml2:AttributeValue xmlns:type=\"xs:string\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"xs:string\">GTW_950</saml2:AttributeValue></saml2:Attribute></saml2:AttributeStatement></saml2:Assertion></wsse:Security></S:Header><S:Body><ns3:SubmitObjectsRequest xmlns=\"urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0\" xmlns:ns2=\"urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0\" xmlns:ns3=\"urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0\" xmlns:ns4=\"urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0\" xmlns:ns5=\"urn:hl7-org:v3\"><RegistryObjectList><ExtrinsicObject id=\"Document1\" isOpaque=\"false\" mimeType=\"application/pdf+text/x-cda-r2+xml\" objectType=\"urn:uuid:7edca82f-054d-47f2-a032-9b2a5b5186c1\" status=\"urn:oasis:names:tc:ebxml-regrep:StatusType:Approved\"><Slot name=\"languageCode\"><ValueList><Value>it-IT</Value></ValueList></Slot><Slot name=\"repositoryUniqueId\"><ValueList><Value>2.16.840.1.113883.2.9.2.170.4.5.0002</Value></ValueList></Slot><Slot name=\"sourcePatientId\"><ValueList><Value>FSEPGL01E41A145J^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</Value></ValueList></Slot><Slot name=\"urn:ita:2022:documentSigned\"><ValueList><Value>true^Documento firmato</Value></ValueList></Slot><Slot name=\"size\"><ValueList><Value>108986</Value></ValueList></Slot><Slot name=\"hash\"><ValueList><Value>041ce943477849a4b277b44a0eefaa733c103d3b</Value></ValueList></Slot><Slot name=\"creationTime\"><ValueList><Value>20241031102754</Value></ValueList></Slot><Slot name=\"serviceStartTime\"><ValueList><Value>20241031112843</Value></ValueList></Slot><Slot name=\"serviceStopTime\"><ValueList><Value>20241031112843</Value></ValueList></Slot><Classification classificationScheme=\"urn:uuid:41a5887f-8865-4c09-adf7-e362475b143a\" classifiedObject=\"Document1\" id=\"ClassCode\" nodeRepresentation=\"LDO\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification\"><Slot name=\"codingScheme\"><ValueList><Value>2.16.840.1.113883.2.9.3.3.6.1.5</Value></ValueList></Slot><Name><LocalizedString value=\"Lettera di dimissione ospedaliera\"/></Name></Classification><Classification classificationScheme=\"urn:uuid:f4f85eac-e6cb-4883-b524-f2705394840f\" classifiedObject=\"Document1\" id=\"ConfidentialityCode01\" nodeRepresentation=\"N\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification\"><Slot name=\"codingScheme\"><ValueList><Value>2.16.840.1.113883.5.25</Value></ValueList></Slot><Name><LocalizedString value=\"Normal\"/></Name></Classification><Classification classificationScheme=\"urn:uuid:a09d5840-386c-46f2-b5ad-9c3699a4309d\" classifiedObject=\"Document1\" id=\"FormatCode_1\" nodeRepresentation=\"2.16.840.1.113883.2.9.10.1.5\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification\"><Slot name=\"codingScheme\"><ValueList><Value>2.16.840.1.113883.2.9.3.3.6.1.6</Value></ValueList></Slot><Name><LocalizedString value=\"Lettera di Dimissione Ospedaliera\"/></Name></Classification><Classification classificationScheme=\"urn:uuid:f33fb8ac-18af-42cc-ae0e-ed0b0bdb91e1\" classifiedObject=\"Document1\" id=\"IdHealthcareFacilityTypeCode\" nodeRepresentation=\"Ospedale\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification\"><Slot name=\"codingScheme\"><ValueList><Value>2.16.840.1.113883.2.9.3.3.6.1.1</Value></ValueList></Slot><Name><LocalizedString value=\"Ospedale\"/></Name></Classification><Classification classificationScheme=\"urn:uuid:cccf5598-8b07-4b77-a05e-ae952c785ead\" classifiedObject=\"Document1\" id=\"IdPracticeSettingCode\" nodeRepresentation=\"AD_PSC001\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification\"><Slot name=\"codingScheme\"><ValueList><Value>2.16.840.1.113883.2.9.3.3.6.1.2</Value></ValueList></Slot><Name><LocalizedString value=\"Allergologia\"/></Name></Classification><Classification classificationScheme=\"urn:uuid:f0306f51-975f-434e-a61c-c59651d33983\" classifiedObject=\"Document1\" id=\"IdTypeCode\" nodeRepresentation=\"34105-7\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification\"><Slot name=\"codingScheme\"><ValueList><Value>2.16.840.1.113883.6.1</Value></ValueList></Slot><Name><LocalizedString value=\"Lettera di dimissione ospedaliera\"/></Name></Classification><Classification classificationScheme=\"urn:uuid:93606bcf-9494-43ec-9b4e-a7748d1a838d\" classifiedObject=\"Document1\" id=\"Author_1\" nodeRepresentation=\"\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification\"><Slot name=\"authorRole\"><ValueList><Value>AAS</Value></ValueList></Slot><Slot name=\"authorInstitution\"><ValueList><Value>AZIENDA SANITARIA LOCALE DI POTENZA ASP^^^^^&amp;2.16.840.1.113883.2.9.4.1.3&amp;ISO^^^^170201</Value></ValueList></Slot><Slot name=\"authorPerson\"><ValueList><Value>MCCLVT88H20F104W^^^^^^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</Value></ValueList></Slot></Classification><ExternalIdentifier id=\"patientId_1\" identificationScheme=\"urn:uuid:58a6f841-87b3-4a3e-92fd-a8ffeff98427\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:ExternalIdentifier\" registryObject=\"Document1\" value=\"FSEPGL01E41A145J^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO\"><Name><LocalizedString value=\"XDSDocumentEntry.patientId\"/></Name></ExternalIdentifier><ExternalIdentifier id=\"uniqueId_1\" identificationScheme=\"urn:uuid:2e82c1f6-a085-4c72-9da3-8640a32e42ab\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:ExternalIdentifier\" registryObject=\"Document1\" value=\"2.16.840.1.113883.2.9.2.170.4.4^201.AIRO.006012024000016_1\"><Name><LocalizedString value=\"XDSDocumentEntry.uniqueId\"/></Name></ExternalIdentifier></ExtrinsicObject><RegistryPackage id=\"SubmissionSet1\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:RegistryPackage\" status=\"urn:oasis:names:tc:ebxml-regrep:StatusType:Approved\"><Slot name=\"submissionTime\"><ValueList><Value>20241104131414</Value></ValueList></Slot><Classification classificationScheme=\"urn:uuid:aa543740-bdda-424e-8c96-df4873be8500\" classifiedObject=\"SubmissionSet1\" id=\"IdContentTypeCode\" nodeRepresentation=\"DIS\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification\"><Slot name=\"codingScheme\"><ValueList><Value>2.16.840.1.113883.2.9.3.3.6.1.4</Value></ValueList></Slot><Name><LocalizedString value=\"Discharge\"/></Name></Classification><Classification classificationScheme=\"urn:uuid:a7058bb9-b4e4-4307-ba5b-e3f0ab85e12d\" classifiedObject=\"SubmissionSet1\" id=\"SubmissionSet1_ClassificationAuthor\" nodeRepresentation=\"\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification\"><Slot name=\"authorRole\"><ValueList><Value>AAS</Value></ValueList></Slot><Slot name=\"authorInstitution\"><ValueList><Value>AZIENDA SANITARIA LOCALE DI POTENZA ASP^^^^^&amp;2.16.840.1.113883.2.9.4.1.3&amp;ISO^^^^170201</Value></ValueList></Slot><Slot name=\"authorPerson\"><ValueList><Value>MCCLVT88H20F104W^^^^^^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</Value></ValueList></Slot></Classification><ExternalIdentifier id=\"SubmissionSet1_SourceId\" identificationScheme=\"urn:uuid:554ac39e-e3fe-47fe-b233-965d2a147832\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:ExternalIdentifier\" registryObject=\"SubmissionSet1\" value=\"2.16.840.1.113883.2.9.2.170\"><Name><LocalizedString value=\"XDSSubmissionSet.sourceId\"/></Name></ExternalIdentifier><ExternalIdentifier id=\"SubmissionSet1_UniqueId\" identificationScheme=\"urn:uuid:96fdda7c-d067-4183-912e-bf5ee74998a8\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:ExternalIdentifier\" registryObject=\"SubmissionSet1\" value=\"2.16.840.1.113883.2.9.2.170.4.3.170201.70602.0\"><Name><LocalizedString value=\"XDSSubmissionSet.uniqueId\"/></Name></ExternalIdentifier><ExternalIdentifier id=\"SubmissionSet1_PatientId\" identificationScheme=\"urn:uuid:6b5aea1a-874d-4603-a4bc-96a0a7b38446\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:ExternalIdentifier\" registryObject=\"SubmissionSet1\" value=\"FSEPGL01E41A145J^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO\"><Name><LocalizedString value=\"XDSSubmissionSet.patientId\"/></Name></ExternalIdentifier></RegistryPackage><Association associationType=\"urn:oasis:names:tc:ebxml-regrep:AssociationType:HasMember\" id=\"urn:uuid:45a28931-b3b7-4e42-9367-19cca28193d3\" sourceObject=\"SubmissionSet1\" targetObject=\"Document1\"><Slot name=\"SubmissionSetStatus\"><ValueList><Value>Original</Value></ValueList></Slot></Association><Classification classificationNode=\"urn:uuid:a54d6aa5-d40d-43f9-88c5-b4633d873bdd\" classifiedObject=\"SubmissionSet1\" id=\"Classification1\" objectType=\"urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification\"/></RegistryObjectList></ns3:SubmitObjectsRequest></S:Body></S:Envelope> SOAP_RESPONSE:<soapenv:Envelope xmlns:soapenv=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:env=\"http://www.w3.org/2003/05/soap-envelope\"><soapenv:Header xmlns:wsa=\"http://www.w3.org/2005/08/addressing\"><wsa:Action>urn:ihe:iti:2007:RegisterDocumentSet-bResponse</wsa:Action><wsa:RelatesTo>9e919800-057b-456d-9d0e-370bebb76dbe</wsa:RelatesTo></soapenv:Header><soapenv:Body><ns3:RegistryResponse xmlns:ns2=\"urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0\" xmlns:ns3=\"urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0\" xmlns:ns4=\"urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0\" xmlns:ns5=\"urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0\" xmlns:ns6=\"urn:hl7-org:v3\" status=\"urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure\"><ns3:RegistryErrorList><ns3:RegistryError codeContext=\"RDA generated an internal error.\" errorCode=\"CRF2\" severity=\"urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error\"/></ns3:RegistryErrorList></ns3:RegistryResponse></soapenv:Body></soapenv:Envelope>",
            "subject": null,
            "organizzazione": null,
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.82beb3ea5a3ff5cc27aabd093b5d2f43f454ccc08b45c5de82efa5b84141bd28.eece59a784^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": null,
            "issuer": null,
            "expiringDate": "2025-11-04T13:14:14.652+0000"
        },
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-11-04T14:13:45.179+01:00",
            "eventStatus": "SUCCESS",
            "message": null,
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "170",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.82beb3ea5a3ff5cc27aabd093b5d2f43f454ccc08b45c5de82efa5b84141bd28.eece59a784^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "f105f83161ee246c",
            "issuer": "integrity:S1#170#REGIONEBASILICATATEST",
            "expiringDate": "2025-11-04T14:13:45.189+01:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-11-04T14:14:14.566+01:00",
            "eventStatus": "SUCCESS",
            "message": null,
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "170",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.82beb3ea5a3ff5cc27aabd093b5d2f43f454ccc08b45c5de82efa5b84141bd28.eece59a784^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "ecc282e2f7971d1c",
            "issuer": "integrity:S1#170#REGIONEBASILICATATEST",
            "expiringDate": "2025-11-04T14:14:14.578+01:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-04T14:14:15.504+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.",
            "subject": null,
            "organizzazione": null,
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.82beb3ea5a3ff5cc27aabd093b5d2f43f454ccc08b45c5de82efa5b84141bd28.eece59a784^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": null,
            "issuer": null,
            "expiringDate": "2025-11-04T14:14:15.644+01:00"
        }
    ],
    "timestamp": "2024-11-04T13:14:35.556Z"
}

**Comment by BasilicataCrashProgramFSE** [comment]
Chiedo scusa, l'**RDA corretto è Regione Puglia**

**Comment by lninnova** [comment]
Buongiorno, la richiesta di comunicazione metadati per il documento avente uniqueId: **2.16.840.1.113883.2.9.2.170.4.4^201.AIRO.006012024000016_1** ci e arrivata solamente in data **05-NOV-2024 10:20:45**
I metadati sono stati correttamente salvati sul nostro registry.
Resto a disposizione per ulteriori verifiche.
