### ISSUE TITLE
Crash Program (fase2) - Creazione da FVG a Provincia Autonoma di Trento - CRF2 RDA generated an internal error

### ISSUE THREAD

**Issue by ChiaraCeccottiFVG** [ministero-salute/it-fse-support#1212]
Buongiorno,
eseguendo lo use case di creazione di un documento dalla regione FVG verso la Provincia Autonoma di Trento otteniamo nell'event type SEND TO INI un errore bloccante - CRF2 RDA generated an internal error.
```
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-04T14:42:16.532+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.4645caad874f60fe53a014a55efb1c695f62795e4e432d29e70a62f3b86cf048.fb86410e3a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-04T14:42:16.646+01:00"
        }
```
Potreste aiutarci a capire il problema?
Ringrazio per la collaborazione e auguro una buona giornata. 
Per comodità taggo @apsstn referente github della Provincia Autonoma di Trento altrimenti non credo possa accorgersi della issue.

**Comment by apsstn** [comment]
Buongiorno, la comunicazione metadati è fallita a causa di un errore nella validazione SAML. Nello specifico sembra che il problema sia legato al nostro mancato aggiornamento della lista degli Issuer, che in FSE 1.0 era limitato ai codici regionali (più quelli nazionali e.g. '999' e '000'). 

Non appena verrà completata la configurazione avviseremo commentando questa issue

Buona giornata

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
ringrazio molto.

**Comment by nicola-ferrari-threadsolutions** [comment]
@ChiaraCeccottiFVG 

Potete riprovare?

cc @apsstn

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno @nicola-ferrari-threadsolutions,
conferiamo che siamo riusciti a pubblicare con successo il documento 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_PATSUM_1731593410954

Otteniamo invece errore in cancellazione, sostituzione e aggiornamento metadati.
CANCELLAZIONE:
{
    "traceID": "628136ac67835b7e",
    "spanID": "169294c92e8ff676",
    "type": "/errors",
    "title": "Generic",
    "status": 500,
    "detail": "",
    "instance": "error/generic",
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}
SOSTITUZIONE:
{
    "traceID": "628136ac67835b7e",
    "spanID": "169294c92e8ff676",
    "type": "/errors",
    "title": "Generic",
    "status": 500,
    "detail": "",
    "instance": "error/generic",
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}
AGGIORNAMENTO METADATI:
{
    "traceID": "95007bf1c46c5f9c",
    "spanID": "d82d225a730a810c",
    "type": "/errors",
    "title": "Generic",
    "status": 500,
    "detail": "",
    "instance": "error/generic",
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}
Ringraziamo molto per la collaborazione e auguriamo un buon pomeriggio.

**Comment by nicola-ferrari-threadsolutions** [comment]
@ChiaraCeccottiFVG 

Questi mi sembrano errori che torna il GTW e non legati ad errori "nostri"
Potete verificare con Sogei? 

@apsstn

**Comment by ChiaraCeccottiFVG** [comment]
@nicola-ferrari-threadsolutions 
si penso anche io siano errori del GTW. 
@LucaRogledi è possibile eseguire una verifica per capire meglio la problematica?
Ringrazio molto.

**Comment by vigliottim** [comment]
@nicola-ferrari-threadsolutions

Buonasera,
tutte le chamate vanno in errore poiché falliscono la ricerca e il recupero dei riferimenti.
Le segnaliamo, ad esempio, la chiamata al recupero riferimenti che va in errore alle ore 15:27:24.

**Comment by nicola-ferrari-threadsolutions** [comment]
Buonasera
Abbiamo avuto dei problemi in fase di storicizzazione documenti.

Potete gentilmente procedere con una nuova pubblicazione ed in seguito gli altri UC?

Grazie

cc @apsstn

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
confermo che la creazione avviene con successo (siamo riusciti a pubblicare il documento 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_PATSUM_1732098469666).
Otteniamo errore nell'aggiornamento metadati e nella sostituzione (replace) e cancellazione.
Aggiornamento metadati:
{
    "traceID": "fec775035fcdc894",
    "spanID": "a8a131cf13c5e811",
    "type": "/errors",
    "title": "Generic",
    "status": 500,
    "detail": "it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.",
    "instance": "error/generic",
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}
Sostituzione:
{
    "status": 500,
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}
Cancellazione:
{
    "status": 500,
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}

Vi ringraziamo per la collaborazione e auguriamo una buona giornata.

**Comment by nicola-ferrari-threadsolutions** [comment]
Ciao @ChiaraCeccottiFVG 

Abbiamo fatto delle verifiche e, ad esempio, abbiamo ricevuto una richiesta alle 11:33 di registrazione (positiva) alla quale abbiamo risposto 

```

<?xml version='1.0' encoding='UTF-8'?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
  <soap:Header>
    <wsa:Action xmlns:wsa="http://www.w3.org/2005/08/addressing">urn:ihe:iti:2007:RegisterDocumentSet-bResponse</wsa:Action>
    <wsa:MessageID xmlns:wsa="http://www.w3.org/2005/08/addressing">urn:uuid:a0c36cf8-2f7a-46fa-8f64-70959dd42473</wsa:MessageID>
    <wsa:To xmlns:wsa="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
    <wsa:RelatesTo xmlns:wsa="http://www.w3.org/2005/08/addressing">354dc919-aa50-4f26-8260-31c0d7ff94fd</wsa:RelatesTo>
  </soap:Header>
  <soap:Body>
    <ns2:RegistryResponse xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Success"/>
  </soap:Body>
</soap:Envelope>


```

Successivamente abbiamo ricevuto una RegistryStoredQuery alla quale abbiamo risposto positivamente 

```

<?xml version='1.0' encoding='UTF-8'?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
  <soap:Header>
    <wsa:Action xmlns:wsa="http://www.w3.org/2005/08/addressing">urn:ihe:iti:2007:RegistryStoredQueryResponse</wsa:Action>
    <wsa:MessageID xmlns:wsa="http://www.w3.org/2005/08/addressing">urn:uuid:47c39cd1-bd93-48f6-8dd0-195c7313d5e6</wsa:MessageID>
    <wsa:To xmlns:wsa="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
    <wsa:RelatesTo xmlns:wsa="http://www.w3.org/2005/08/addressing">9d8f476d-7360-4f84-b3b8-768b52c5016f</wsa:RelatesTo>
  </soap:Header>
  <soap:Body>
    <ns0:AdhocQueryResponse xmlns:ns0="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Success">
      <RegistryObjectList xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0">
        <ObjectRef id="urn:uuid:1eb503e6-da3c-4e87-ba19-3d68a18fee47"/>
      </RegistryObjectList>
    </ns0:AdhocQueryResponse>
  </soap:Body>
</soap:Envelope>


```

Chiedo quindi a @vigliottim  se puo indicarci cosa ci sia di sbagliato nella risposta.
Grazie

cc @apsstn

**Comment by nicola-ferrari-threadsolutions** [comment]
Ciao @vigliottim @LucaRogledi 

Riuscite a fornirci qualche dettaglio per favore?

Grazie

**Comment by vigliottim** [comment]
Buonasera,
le chiediamo gentilmente di riprovare.
Restiamo in attesa di un suo gentile riscontro.
Grazie.

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
confermo che la sostituzione e la cancellazione avvengono con successo.
(Rimane errore 500 per la metadata update ma in vista della ITI-57 sarà da ritestare).
Ringrazio molto, buona giornata.

**Comment by vigliottim** [comment]
Buonasera,
chiudiamo la presente issue poiché in attesa della rilascio della ITI-57.
Verrà riaperta non appena sarà possibile procedere con i test.
Grazie.
