### ISSUE TITLE
Regione Basilicata - UC4 Errore Generico Aggiornamento metadata verso RDA=Bolzano

### ISSUE THREAD

**Issue by BasilicataCrashProgramFSE** [ministero-salute/it-fse-support#1213]
Buongiorno,

Chiediamo gentilmente una verifica nella transazione di aggiornamento metadati verso RDA=Bolzano.
Di seguito il caso di test:

cf paziente: PRVFSN70S04A952Z^^^&2.16.840.1.113883.2.9.4.3.2&ISO
"identificativoDoc": "2.16.840.1.113883.2.9.2.170.4.4^201.AIRO.006012024000020_1",
 "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.56e4d49978e7f6d5885567814ef51cc6769f8010fb99b776d182c2f46c6b77aa.bdaf0281fb^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",

Errore aggiornamento metadati:
{
    "traceID": "d7e3057ef866b078",
    "spanID": "3b4e8f79bb353ff3",
    "workflowInstanceId": null,
    "type": "/errors",
    "instance": "error/generic",
    "timestamp": "2024-11-04T14:39:41.583Z"
}

Grazie

**Comment by ngaraventa** [comment]
Buongiorno, l'aggiornamento metadati è sospeso fino alla distribuzione su INI della ITI-57
