### ISSUE TITLE
Regione MARCHE - CRASH PROGRAM - ERRORE PUBBLICAZIONE

### ISSUE THREAD

**Issue by Didi22515** [ministero-salute/it-fse-support#1214]
Buonasera, 
abbiamo riprovato ma abbiamo lo stesso problema sulla firma 
[2.16.840.1.113883.2.9.2.110.4.4^201.BiMind_D3839_43_0.pdf](https://github.com/user-attachments/files/17620975/2.16.840.1.113883.2.9.2.110.4.4.201.BiMind_D3839_43_0.pdf)
[Request 2.txt](https://github.com/user-attachments/files/17620976/Request.2.txt)

di seguito la risposta 
{
   "traceID":"f18ddcee185a1241",
   "spanID":"f18ddcee185a1241",
   "type":"/msg/sign-error",
   "title":"Sign error",
   "detail":"La firma del pdf non risulta valida",
   "status":400,
   "instance":"/msg/sign-error"
}

La validazione è andata a buon fine 

_Originally posted by @Didi22515 in https://github.com/ministero-salute/it-fse-support/issues/1082#issuecomment-2455145036_

**Comment by LucaRogledi** [comment]
Buongiorno,
l'errore potrebbe essere dovuto dall'utilizzo di un certficato non corretto per la firma del pdf.
La invitiamo a riprovare utilizzando il certificato S1 di firma emesso da Sogei (utilizzato anche per la generazione dei token Bearer e Signature) e il tool disponibile online [pdf-generator](https://github.com/ministero-salute/it-fse-gtw-tools) con il quale è possibile iniettare il cda all'interno di pdf e firmarli.
Restiamo a disposizione per ulteriore supporto.
Grazie

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
La informiamo che sarà possibile riaprirla nel caso in cui necessiti di ulteriore supporto.
Grazie.
