### ISSUE TITLE
Mancato accreditamento (checklist)

### ISSUE THREAD

**Issue by NAMURSRL** [ministero-salute/it-fse-support#1215]
Ho eseguito una modifica alla pull request.
a seguito di una vostra segnalazione:
_in seguito alla richiesta di accreditamento per namur_srl/glpx_/1.0, abbiamo verificato che nel file “report-checklist.xlsx”  sono presenti degli errori che elenchiamo:

44: È necessario valorizzare le seguenti colonne: M, N, P, Q, R, S
44: È necessario valorizzare la colonna K con uno dei valori disponibili nel menù a tendina__

Ho chiesto l'accreditamento per i soli documenti di LABORATORIO e ho valorizzato le colonne come richiesto.
Mi potete spiegare in dettaglio dove sbaglio ?
[report-checklist.xlsx](https://github.com/user-attachments/files/17629516/report-checklist.xlsx)

Cordiali saluti

**Comment by vigliottim** [comment]
Buongiorno, 
chiediamo cortesemente di ignorare l'errore segnalato relativo alle colonne M, N, P, Q, R, S, che risultano correttamente compilate. 
L'errore segnalato sulla colonna K, invece, indica che, in caso di applicabilità = NO, è necessario compilare la colonna K (nel vostro file blank) con uno dei valori disponibili nel menu a tendina.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by NAMURSRL** [comment]
Buongiorno,
vi ho inviato nuovamente il file corretto
Resto in attesa di sapere se è compilato correttamente.
Cordiali saluti

**Comment by vigliottim** [comment]
Buongiorno,
la informiamo che il file è stato compilato correttamente.
Riceverà l'esito delle elaborazioni via e-mail come di consueto.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
