### ISSUE TITLE
crash-program. errore aggiornamento metadati

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#1219]
buongiorno,
sto tentando di modificare i metadati di un documento pubblicato ma ricevo errore:

{"type":"https://govway.org/handling-errors/401/TokenAuthenticationFailed.html","title":"TokenAuthenticationFailed","status":401,"detail":"Invalid token","govway_id":"245c6844-9c35-11ef-a4d1-005056ae54fa"}

url:

```
PUT 
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.130.4.4^497293/metadata

```
questi i token:

```
{
  "iss": "auth:S1#130#ABRUZZO_ASL2_TEST",
  "iat": "1730894271",
  "exp": "1730894871",
  "jti": "412f1538-1668-49f5-b350-852c7227c66e",
  "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
  "sub": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO"
}
```
```
{
  "iss": "integrity:S1#130#ABRUZZO_ASL2_TEST",
  "iat": "1730894272",
  "exp": "1730894872",
  "jti": "5b0caa04-24f5-4280-b6af-da308dc7036d",
  "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
  "sub": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "subject_organization_id": "130",
  "subject_organization": "Regione Abruzzo",
  "locality": "OSPEDALE^^^^^&2.16.840.1.113883.2.9.4.1.3&ISO^^^^202123456",
  "subject_role": "DRS",
  "person_id": "DNNBZZ60A43A345K^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "patient_consent": "true",
  "purpose_of_use": "UPDATE",
  "action_id": "UPDATE",
  "subject_application_id": "SISWeb",
  "subject_application_vendor": "IASI S.r.l",
  "subject_application_version": "2.4.8",
  "resource_hl7_type": "('11488-4^^2.16.840.1.113883.6.1')",
  "identificativoDoc": "2.16.840.1.113883.2.9.2.130.4.4^497293",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.2.130.4.3.2464654",
  "assettoOrganizzativo": "AD_PSC008",
  "tipoDocumentoLivAlto": "REF"
}

```

**Comment by vigliottim** [comment]
Buongiorno,
dalle analisi dei log della chiamata con "govway_id":"245c6844-9c35-11ef-a4d1-005056ae54fa", è emerso un errore durante la validazione del X-Security-Token:

![image](https://github.com/user-attachments/assets/f7611a97-3241-410f-acca-f504b7cf8bdf)

Infatti, decodificando i token con il tool online [jwt.io](jwt.io), appare l'errore _"Invalid Signature"_:

- **_X-Security-Token:_**

<img width="454" alt="image" src="https://github.com/user-attachments/assets/7cfbc165-567a-44d8-9644-d374c2fc0dc1">

- _**Authorization Bearer Token:**_

<img width="457" alt="image" src="https://github.com/user-attachments/assets/13504b41-7227-4c28-8880-945d275821f5">

- _**FSE-JWT-Signature Token:**_

<img width="304" alt="image" src="https://github.com/user-attachments/assets/cc89f86e-f1fd-465a-9838-25e3e3477668">

Inoltre, come riportato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt), i campi del _FSE-JWT-Signature token_ evidenziati in figura non sono ammessi:

<img width="245" alt="image" src="https://github.com/user-attachments/assets/ece047fa-b9b6-4a3e-82f4-a31979f8ee4c">

La preghiamo di effettuare le modifiche indicate e riprovare.
Rimaniamo a disposizione nel caso in cui sia necessario ulteriore supporto.
Grazie.

**Comment by alessandropassamonti** [comment]
Grazie.
ho corretto i token e ora mi viene restituito questo errore:

```
{
"detail": "it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 1173",
"instance": "error/generic",
"spanID": "d162d40fa07deae6",
"title": "Generic",
"traceID": "440ced36854ae5bb",
"type": "/errors"
}
```
Approfitto anche per chiedere come capire quali sono i custom claim obbligatori per i vari servizi (ad eccezione delle validazione) perché francamente faccio fatica a capirlo

Grazie

**Comment by vigliottim** [comment]
Buonasera,
l'errore 1173 riporta il seguente messaggio: "struttura dell'utente diversa da quella del documento".

**Comment by alessandropassamonti** [comment]
effettivamente erano diversi.
li ho sistemati ma ho sempre lo stesso errore

nel campo locality del jwt c'è  "STRUTTURA DI PROVA^^^^^&2.16.840.1.113883.2.9.4.1.3&ISO^^^^130202123456"

nel document/authorInstitution c'è "STRUTTURA DI PROVA^^^^^&amp;2.16.840.1.113883.2.9.4.1.3&amp;ISO^^^^130202123456"

nell'asserzione SAML/locality c'è "2.16.840.1.113883.2.9.4.1.3.130202123456"

**Comment by alessandropassamonti** [comment]
buongiorno,
ci sono novità?

**Comment by alessandropassamonti** [comment]
aggiungo che interrogando lo status per traceId, sembra che l'operazione sia conclusa correttamente

```
{
"spanID": "f8177d8c6fe6a133",
"traceID": "db3bf3fd943fc33b",
"transactionData":
    [
        {
        "eventDate": "2024-11-08T14:22:27.315+01:00",
        "eventStatus": "SUCCESS",
        "eventType": "RIFERIMENTI_INI",
        "expiringDate": "2025-11-08T14:22:27.373+01:00",
        "identificativoDocumento": "2.16.840.1.113883.2.9.2.130.4.4^497293",
        "issuer": "integrity:S1#130#ABRUZZO_ASL2_TEST",
        "message": "Merge metadati effettuato correttamente",
        "organizzazione": "130",
        "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
        "traceId": "baa436cb9e5c22fb",
        "workflowInstanceId": "2b5f3e81faa91a7f456446f39d604fd752bfdfe919ddf47e84de9624f0020aaf.7c0ddf60c5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
        }
    ]
}
```

**Comment by LucaRogledi** [comment]
Buongiorno @alessandropassamonti ,
Per la risoluzione dell'errore da lei riscontrato e riportato anche nella #1221 è stata richiesta la seguente verifica
[commento 1221](https://github.com/ministero-salute/it-fse-support/issues/1221#issuecomment-2468268985).
Restiamo a disposizione per ulteriore supporto.
Grazie

**Comment by vigliottim** [comment]
Buongiorno @alessandropassamonti,
le chiediamo cortesemente un riscontro.
Grazie.

**Comment by alessandropassamonti** [comment]
buongiorno,
la issue #1221 è stata chiusa pertanto penso si possa chiudere anche questa
