### ISSUE TITLE
Errore validazione referto Radiologia - sezione Allergie : agente non codificato

### ISSUE THREAD

**Issue by luciatrama** [ministero-salute/it-fse-support#122]
Buongiorno 
riscontro problemi nella validazione della sezione allergie, in particolare nella descrizione dell'agente non codificato.
Per la compilazione dell'elemento <participant>, ho seguito le indicazioni delle specifiche (documento "Implementation Guide - Clinical Document Architecture (CDA) Rel. 2 per il Referto di Radiologia v. 1.1 di Marzo 2022) "CONF - RAD - 124", ma in fase di validazione viene restituito il seguente errore :
[ERRORE-b58| Sotto sezione Allergie: L'elemento participant/participantRole/playingEntity deve avere l'attributo code/@codeSystem valorizzato come segue: '2.16.840.1.113883.6.73' codifica \"WHO ATC\"  '2.16.840.1.113883.2.9.6.1.5' codifica \"AIC\"- '2.16.840.1.113883.2.9.77.22.11.2' value set \"AllergenNoDrugs\" (- per le allergie non a farmaci –)]".

Potreste verificare, per favore?
Grazie.

**Comment by IStacchiotti** [comment]
Grazie della segnalazione. Si chiede cortesemente di allegare il cda2 che è stato validato per effettuare l'analisi richiesta.

**Comment by luciatrama** [comment]
[testAllergie.txt](https://github.com/ministero-salute/it-fse-support/files/11037855/testAllergie.txt)
Nella sezione delle allergie ho inserito il dettaglio degli agenti non codificati in questo modo:                               

> _<participant typeCode="CSM">
>                                                 <participantRole>
>                                                     <playingEntity>
>                                                         <code nullFlavor="UNK">
>                                                             <originalText>
>                                                                 <reference value="#allergia graminacee"/>
>                                                             </originalText>
>                                                         </code>
>                                                     </playingEntity>
>                                                 </participantRole>
>                                             </participant>_

seguendo le indicazioni "CONF - RAD - 124" (Se l’agente che ha causato la reazione allergica non è noto, DEVE essere valorizzato solo l’attributo @nullFlavor=“UNK” di <participant>/<participantRole>/<playingEntity>/<code>).

Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno. Grazie per aver allegato il cda2, è stata apportata la modifica lato schematron per includere la possibilità di inserire un code valorizzato con @nullFlavor='UNK' nel caso in cui non sia noto l'agente che ha scatenato la reazione. Sarà pubblicata in documentazine una versione aggiornata dello schematron.
La invitiamo pertanto a riprovare la validazione.

**Comment by IStacchiotti** [comment]
Buonasera, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
