### ISSUE TITLE
Crash Program (fase2) - Creazione da FVG verso regioni Abruzzo - Calabria e Sicilia - Internal Error 1166

### ISSUE THREAD

**Issue by ChiaraCeccottiFVG** [ministero-salute/it-fse-support#1220]
Buongiorno,
nello scenario di creazione verso le regioni Abruzzo Calabria e Sicilia otteniamo un errore bloccante nel send_to_ini (dal registry della RDA):
```
{
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-06T15:40:45.231+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 1166",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.88c5a182cd7a7acc05ff2e999fa485e3374d6ba4540948b16e7096ac20dcad7f.6adf31dd24^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-06T15:40:45.301+01:00"
}
```
Riporto i workflowinstanceID delle tre transazioni:
Abruzzo: 
2.16.840.1.113883.2.9.2.60.4.4.24d077236f0ecdb3054bd11664a1df7622f243737278c56c4be19d1411a3949e.db6c348be0^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
Calabria:
2.16.840.1.113883.2.9.2.60.4.4.88c5a182cd7a7acc05ff2e999fa485e3374d6ba4540948b16e7096ac20dcad7f.6adf31dd24^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
Sicilia:
2.16.840.1.113883.2.9.2.60.4.4.cf06872a62b6f59f1963b618717708de8f0bc405cad5b838a24d80685b5f4143.49cf3cef26^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

Potreste aiutarci a capire l'errore?
Ringraziamo per la collaborazione e auguriamo una buona giornata.

**Comment by vigliottim** [comment]
@alessandropassamonti, @bamuroso-git
Chiediamo cortesemente alle regioni RDA di dare supporto. 
Grazie.

**Comment by LucaRogledi** [comment]
Buonasera @ChiaraCeccottiFVG ,
L'errore sembrerebbe essere causato dalla tipologia documentale utilizzata.
Potrebbe gentilmente riprovare la chiamata utilizzando un'altra tipologia documentale?
Grazie

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno, abbiamo richiesto la produzione di tipologie diverse di documento.
Non appena abbiamo a disposizione un doc diverso da PSS riproviamo e vi facciamo sapere. 
Grazie.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri procediamo alla chiusura della presente issue.
La invitiamo a riaprirla nel caso ci fossero aggiornamenti.
Grazie.
