### ISSUE TITLE
Regione Sicilia - Crash-program - Internal Error 1173 per servizio di Aggiornamento Metadati (UC3)

### ISSUE THREAD

**Issue by bamoruso-git** [ministero-salute/it-fse-support#1221]
Buonasera,
provando ad aggiornare i metadati di un documento, mediante il servizo di aggiornamento metadati, viene restituito l'errore 1173:
```
{
  "traceID" : "5876b97791238191",
  "spanID" : "aa3af5f3374e5c54",
  "type" : "/errors",
  "title" : "Generic",
  "detail" : "it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 1173",
  "instance" : "error/generic"
}
```

L'URL è:
`PUT /govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.190.4.4%5E497295/metadata`

Com'è possibile vedere, l'OID del documento è 2.16.840.1.113883.2.9.2.190.4.4^497295 mentre l'UUID è urn:uuid:94cf3692-7a06-4fdd-908d-d3f430bba53a.
La struttura è 190207123456.

Tuttavia, utilizzando il servizio di recupero stato transazione per TraceId, sembra che l'aggiornamento metadati abbia avuto esito positivo:
`GET /govway/rest/in/FSE/gateway/v1/status/search/5876b97791238191`

la risposta è:
```
{
  "spanID": "6e8b2d16f9d7be7e",
  "traceID": "b76a588bf2db2878",
  "transactionData": [
    {
      "eventDate": "2024-11-06T20:07:30.887+01:00",
      "eventStatus": "SUCCESS",
      "eventType": "RIFERIMENTI_INI",
      "expiringDate": "2025-11-06T20:07:30.949+01:00",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.190.4.4^497295",
      "issuer": "integrity:S1#190#ASP_RG_TEST",
      "message": "Merge metadati effettuato correttamente",
      "organizzazione": "190",
      "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "traceId": "5876b97791238191",
      "workflowInstanceId": "b44524a69f04fa110df8c8fa5c3d533efc7d794617794a5ca64d2cb79a30578a.4074dd374a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
    }
  ]
}
```

Qual è la versione giusta? Sembra che non ci sia coerenza tra i servizi.

Grazie

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
potete fornirci il CF e il timestamp della transazione con errore 1173 ?

**Comment by bamoruso-git** [comment]
Buongionro,

1. CF: FSESCL81A01H163L
2. timestamp: purtroppo non abbiamo più il log dell'evento. Di sicuro è il giorno 06/11/2024, ore 20:00 circa 

Grazie

**Comment by g-maugeri-sogei** [comment]
Buonasera,
c'e' una comunicazione metadati con timestamp   06-NOV-24 20:07:31,208 con esito->Struttura dell'utente diversa da quella del documento

**Comment by bamoruso-git** [comment]
Buonasera,
a scanso di equivoci, è stato eseguita una nuova richiesta di aggiornamento metadati. Questi i dati:

- timestamp: 08/11/2024 15:17:56.432
- CF: FSESCL81A01H163L
- autore: PROVAX00X00X000Y
- struttura: 190207123456

Questa la risposta del servizio:
```
{
  "traceID" : "81d8d3ee9b9149d5",
  "spanID" : "e97dcc4c1dc4c9a1",
  "type" : "/errors",
  "title" : "Generic",
  "detail" : "it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 1173",
  "instance" : "error/generic"
}
```

La risposta del servizio TraceId è (come si vede ha esito positivo):
```
{
  "spanID": "7bc539f060bdaceb",
  "traceID": "7c3a05bf19302941",
  "transactionData": [
    {
      "eventDate": "2024-11-08T15:17:59.669+01:00",
      "eventStatus": "SUCCESS",
      "eventType": "RIFERIMENTI_INI",
      "expiringDate": "2025-11-08T15:17:59.727+01:00",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.190.4.4^497295",
      "issuer": "integrity:S1#190#ASP_RG_TEST",
      "message": "Merge metadati effettuato correttamente",
      "organizzazione": "190",
      "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "traceId": "81d8d3ee9b9149d5",
      "workflowInstanceId": "b44524a69f04fa110df8c8fa5c3d533efc7d794617794a5ca64d2cb79a30578a.8ddb8cf3fb^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
    }
  ]
}
```

Grazie

**Comment by g-maugeri-sogei** [comment]
Buonasera,
il servizio che da esito OK e' riferito al solo recupero dei riferimenti del documento. Questo non significa che tutto il flusso di replace abbia completato correttamente. Nel caso della replace il flusso e' sincrono quindi dovete fare riferimento all'esito che ricevete in risposta alla chiamata sincrona. Nel vostro caso specifico ricevete errore 1173 perche' il codice della struttura non coincide con quello presente nel documento.

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
l'errore 1173 indica che la struttura dell'autore del documento non coincide con la struttura dell'utente.

**Comment by LucaRogledi** [comment]
Buongiorno @bamoruso-git ,
Chiediamo gentilmente di la verifica di quanto riportato.
Restiamo a disposizione per eventuale supporto.
Grazie

**Comment by bamoruso-git** [comment]
Buongionro,
il test in questione è stato annullato. Pertanto chiudo l'issue.
Grazie
