### ISSUE TITLE
crash-program. Errore pubblicazione verso regione Puglia

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#1225]
Buongiorno
ho eseguito una pubblicazione di un documento del CF FSEPGL01E41A145J che appartiene alla regione Puglia e ricevo un errore interrogando lo status del Gtw:

> SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.

ovviamente esitoCaricamentoDocumento rimane in stato ELAB

allego log della transazione
[pubblicazione_cf_regione_puglia.json](https://github.com/user-attachments/files/17659669/pubblicazione_cf_regione_puglia.json)

**Comment by lninnova** [comment]
Buon pomeriggio,
alla request di comunicazione metadati abbiamo restituito l'errore R56 Wrong format data of display name for DocumentEntry.typeCode poiché il valore "Nota di consulto" presente nel displayName del typeCode non è previsto da AffinityDomain.
Sulla questione attendiamo riscontro alla issue #1147
Poiché il problema è emerso su RSA e RAD, potreste tentare la pubblicazione di altre tipologie documentali.

**Comment by alessandropassamonti** [comment]
buongiorno
ho pubblicato una LDO. Se interrogo lo status del Gtw sembra tutto ok ora, ma il servizio esitoCaricamentoDocumento rimane in stato ELAB.
allego transazioni ricavate dallo status del Gtw
[pubblicazione_cf_regione_puglia_ldo.json](https://github.com/user-attachments/files/17676089/pubblicazione_cf_regione_puglia_ldo.json)

**Comment by lninnova** [comment]
Confermo che il documento indicato è stato indicizzato correttamente sul nostro Registry.

**Comment by alessandropassamonti** [comment]
Grazie,
rimane da capire come mai l'esito del caricamento  rimane in ELAB

**Comment by lninnova** [comment]
> Grazie, rimane da capire come mai l'esito del caricamento rimane in ELAB

Dallo status che hai pubblicato sembrerebbe che tutti gli eventi siano in stato SUCCESS. A cosa ti riferisci con esito ELAB?

**Comment by alessandropassamonti** [comment]
le regioni in sussidiarietà completano la pubblicazione andando ad interrogare un servizio FSE1.0 che restituisce lo stato dell'elaborazione che in questo caso rimane in ELAB mentre dovrebbe essere OK. Penso sia un problema di sogei

**Comment by g-maugeri-sogei** [comment]
Buonasera,
per indagare il problema ci serve il codice fiscale dell'assistito e il timestamp della transazione.

**Comment by alessandropassamonti** [comment]
buongiorno
FSEPGL01E41A145J
2024-11-08 08:46:00.000

**Comment by alessandropassamonti** [comment]
buongiorno.
Ci sono novità?

**Comment by alessandropassamonti** [comment]
buongiorno,
oggi lo stato della pubblicazione è OK quindi chiudo la issue
grazie

**Comment by alessandropassamonti** [comment]
buongiorno,
oggi lo stato della pubblicazione è OK quindi chiudo la issue
grazie
