### ISSUE TITLE
Invalid Authorization header 401

### ISSUE THREAD

**Issue by nbssrl** [ministero-salute/it-fse-support#1226]
Buon pomeriggio 

stiamo riscontrando problemi  nel cercare di chiamare il servizio di Validazione.
Allego il Jwt token e il bearer che stiamo generando
BEARER VALIDAZIONE:
eyJ4NWMiOlsiTUlJRHFUQ0NBcEdnQXdJQkFnSVVCeElpWldtMXM3d1RZblNJaDVwU0c3RitMajR3RFFZSktvWklodmNOQVFFTkJRQXdJekVoTUI4R0ExVUVBd3dZVW1WbmFXOXVaU0JNWVhwcGJ5QlRaWEoyYVdObElFTkJNQjRYRFRJME1Ea3lOakEzTXpJeE5Wb1hEVEkyTURreU5qQTNNekl4TkZvd2VURkJNRDhHQTFVRUF3dzRVekVqTVRJd01qQXhNVEl3TWprek1EQkpWQzB3TURrMU9EWTNNVEF3TUY5T1FsTmZjM0pzTFc1bGRIZHZjbXR6WVc1cGRHRnlhVzh4RHpBTkJnTlZCQXNNQmtaVFJUSXVNREVXTUJRR0ExVUVDZ3dOVW1WbmFXOXVaU0JNWVhwcGJ6RUxNQWtHQTFVRUJoTUNTVlF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGRzNUdlZXFCQ2lJd2JCelQ4MWI1bm54cnUzNzJnSDhhM1JvSS9VMkJ0Ykl2bnY1L0l1S2doNDZuOG1qdTR1eFlWZVM4akQ1MzNycUZaOVNWVjkvbTdnZUhTd3FtNnBJNnN6RUtBb1luM29rUjZMc3dQVXYxN1dUeTFONzQwMTAvSll5WmhUYnRKS2I0Q1BqYzZYQVNVTmJWeFp5OXBGNDZPenVVSVRKdGQvWTRTYUFCTnhJYzJLMTk1TGNkdXFFV1B5ODhwbWZxQ1FQRkpvWGxMWE53dUhuUGtnVi95YWZSQTRBSjJVK0ZuemhiUkNNSEtZakFzcXpyOTBFdEI5dUN6SWpDT1NUV0J2d0o5eTZhVjcwOFZXZ2M3SEJSbVBCcllhWkhTdGNKbUJ2cEZmN1BFVUFVMlk4aGJWZFNlZ3Nyc2xZQmFETkQ0c1AvSUVYQzFtVzZYQWdNQkFBR2pmekI5TUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVREJ5R1EvaXZObFdFaVdpbGZsUXdyUnk5d0hrd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3SUdDQ3NHQVFVRkJ3TUVNQjBHQTFVZERnUVdCQlRGZWI3UzFWWHliWk1JL2VManVqQkpKWU1JNGpBT0JnTlZIUThCQWY4RUJBTUNCZUF3RFFZSktvWklodmNOQVFFTkJRQURnZ0VCQUxrYmxlMnJrczZjNy85TzlGd0lwWDN4S0xGYzJvNW5wQlJ6K0JNZEh2cG12Mnd2cVByL1lDNlMrL2N0VVViRms2MThuc0tMdWRZdzAwdmVySGllL2lYUEdVMnJHbDF5ekZPc1VOaWhZUVBvdkU4eDlvb3dmQTV4eTl3S0EwWFRyaUU3VytEbzJ6VEdCMThoL3pqRzlXcUk5T3VkZGhydnFKWFJibDlCbVZXZSswUnBKRUx0ME8yUkdhZFlON2NYMVlhNTRkZFpkT3l5Zm93RjNiYW82SFdiMWVCV3RhbCtHU0ZQNUFRYnprNnlSbVZaYWF0K0RkQWY5VHgrU2srdU96bmZIWEtYR0p1YU5WejhvQUw2Uy9hOXBkazRNUUJ5TlB1Y0JreUVvR0YzdVF4U3M1V2lYV1RxZXFIdEx4VjBITlF4Vzh2RWYwNUFMcTJOcUpVMFlXND0iXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJHWlpGTkM4NFI0OEg1MDFJXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL2ZzZS1zZXJ2aWNlcy5yZWdpb25lLmxhemlvLml0L2ZzZS1taWRkbGV3YXJlL2dhdGV3YXkvdjEvZG9jdW1lbnRzL3ZhbGlkYXRpb24iLCJpc3MiOiJhdXRoOlMxIzEyMDIwMTEyMDI5MzAwSVQtMDA5NTg2NzEwMDBfTkJTX3NybC1uZXR3b3Jrc2FuaXRhcmlvIiwiZXhwIjoxNzMwOTk1MjE5LCJpYXQiOjE3MzA5ODgwMTksImp0aSI6Il8yMDI0MTEwNzE1MDAxOF8ifQ.2acqH2JQsqUJ-BB4Y4WaR1H0aSUSwY5FLAHrecl0LfxqMzaupT8h1T4wIhG2ygRni8Kau5p7QQMfNuIlgQOADDDuaYmA8MibNUGJ5xVyvoR385IluKAq8qRCIQ52ZMjgJFRjVox9ZzRyN5L1UURb6bNIhrwXa0hCksvlTVGZ7i-Oppu0IOFytlmsbKwY3H7rowuqsLLWBRiIqJkzTlV9IdyfNKGCmGMix_j8JhKrhuxeM4592oDfp97d8GbmkxFMXEBTgVIdfA6i7dE-QvT6AaBThY4z2fia3R466S_bZGQ2TW8b-o_h7jTkKteKKYbmtvSPqjwX5mlNWES2cbcTXA
FSE_JWT VALIDAZIONE:
eyJ4NWMiOlsiTUlJRHFUQ0NBcEdnQXdJQkFnSVVCeElpWldtMXM3d1RZblNJaDVwU0c3RitMajR3RFFZSktvWklodmNOQVFFTkJRQXdJekVoTUI4R0ExVUVBd3dZVW1WbmFXOXVaU0JNWVhwcGJ5QlRaWEoyYVdObElFTkJNQjRYRFRJME1Ea3lOakEzTXpJeE5Wb1hEVEkyTURreU5qQTNNekl4TkZvd2VURkJNRDhHQTFVRUF3dzRVekVqTVRJd01qQXhNVEl3TWprek1EQkpWQzB3TURrMU9EWTNNVEF3TUY5T1FsTmZjM0pzTFc1bGRIZHZjbXR6WVc1cGRHRnlhVzh4RHpBTkJnTlZCQXNNQmtaVFJUSXVNREVXTUJRR0ExVUVDZ3dOVW1WbmFXOXVaU0JNWVhwcGJ6RUxNQWtHQTFVRUJoTUNTVlF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGRzNUdlZXFCQ2lJd2JCelQ4MWI1bm54cnUzNzJnSDhhM1JvSS9VMkJ0Ykl2bnY1L0l1S2doNDZuOG1qdTR1eFlWZVM4akQ1MzNycUZaOVNWVjkvbTdnZUhTd3FtNnBJNnN6RUtBb1luM29rUjZMc3dQVXYxN1dUeTFONzQwMTAvSll5WmhUYnRKS2I0Q1BqYzZYQVNVTmJWeFp5OXBGNDZPenVVSVRKdGQvWTRTYUFCTnhJYzJLMTk1TGNkdXFFV1B5ODhwbWZxQ1FQRkpvWGxMWE53dUhuUGtnVi95YWZSQTRBSjJVK0ZuemhiUkNNSEtZakFzcXpyOTBFdEI5dUN6SWpDT1NUV0J2d0o5eTZhVjcwOFZXZ2M3SEJSbVBCcllhWkhTdGNKbUJ2cEZmN1BFVUFVMlk4aGJWZFNlZ3Nyc2xZQmFETkQ0c1AvSUVYQzFtVzZYQWdNQkFBR2pmekI5TUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVREJ5R1EvaXZObFdFaVdpbGZsUXdyUnk5d0hrd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3SUdDQ3NHQVFVRkJ3TUVNQjBHQTFVZERnUVdCQlRGZWI3UzFWWHliWk1JL2VManVqQkpKWU1JNGpBT0JnTlZIUThCQWY4RUJBTUNCZUF3RFFZSktvWklodmNOQVFFTkJRQURnZ0VCQUxrYmxlMnJrczZjNy85TzlGd0lwWDN4S0xGYzJvNW5wQlJ6K0JNZEh2cG12Mnd2cVByL1lDNlMrL2N0VVViRms2MThuc0tMdWRZdzAwdmVySGllL2lYUEdVMnJHbDF5ekZPc1VOaWhZUVBvdkU4eDlvb3dmQTV4eTl3S0EwWFRyaUU3VytEbzJ6VEdCMThoL3pqRzlXcUk5T3VkZGhydnFKWFJibDlCbVZXZSswUnBKRUx0ME8yUkdhZFlON2NYMVlhNTRkZFpkT3l5Zm93RjNiYW82SFdiMWVCV3RhbCtHU0ZQNUFRYnprNnlSbVZaYWF0K0RkQWY5VHgrU2srdU96bmZIWEtYR0p1YU5WejhvQUw2Uy9hOXBkazRNUUJ5TlB1Y0JreUVvR0YzdVF4U3M1V2lYV1RxZXFIdEx4VjBITlF4Vzh2RWYwNUFMcTJOcUpVMFlXND0iXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJHWlpGTkM4NFI0OEg1MDFJXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImlzcyI6ImludGVncml0eTpTMSMxMjAyMDExMjAyOTMwMElULTAwOTU4NjcxMDAwX05CU19zcmwtbmV0d29ya3Nhbml0YXJpbyIsImxvY2FsaXR5IjoiMTIwMTYzIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoidi40LjEwLjEwNiIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBMYXppbyIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMTIwIiwiYXVkIjoiaHR0cHM6Ly9mc2Utc2VydmljZXMucmVnaW9uZS5sYXppby5pdC9mc2UtbWlkZGxld2FyZS9nYXRld2F5L3YxL2RvY3VtZW50cy92YWxpZGF0aW9uIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJhY3Rpb25faWQiOiJDUkVBVEUiLCJyZXNvdXJjZV9obDdfdHlwZSI6IignMzQxMDUtN15eMi4xNi44NDAuMS4xMTM4ODMuNi4xJykiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoibmV0d29ya3Nhbml0YXJpbyIsImV4cCI6MTczMDk5NTIxOSwic3ViamVjdF9hcHBsaWNhdGlvbl92ZW5kb3IiOiJOQlMiLCJpYXQiOjE3MzA5ODgwMTksImp0aSI6Il8yMDI0MTEwNzE1MDAxOF8iLCJwZXJzb25faWQiOiJERERHTk4zOU0yOEE2NzdVXl5eJmFtcDsyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImYW1wO0lTTyJ9.xnGECpQE9wT6ecjU5-WHSQ-Yoj7uKo5n4Wi3zg2USfv0lndacbWVFAodEqS1fj1AjsR3Dk6QAPIPJLb9PLp6MKfpseRYHuTdLboV9JZlmKjsgKz8SpJwSiWAVDnmqYgmUL35shg4B5dKRYPUhWEgl0maqMUYQBGNr598KZ5RzegA4UPhyiJV4xebC8d8iXpceLYAAOVUOAB2XZO78FzEokecxOzUtqDFAUogdHpOfCPRtB-3wC2qy3LbUq_lkyLEGF2A8xhLzNmCyQwUYOF8UlMXNf6Vf4ESWLQ-4IuRN0EWAa6gP_obw3fIuf1A13cbGnwn4D3LWVImHwO88-vFLw

Grazie

**Comment by nbssrl** [comment]
il govway_id è 20241107150019

**Comment by nbssrl** [comment]
e la response è : 
{
  "govway_id" : "20241107150019",
  "detail" : "Invalid Authorization header",
  "title" : "Error",
  "type" : "midlleware-401",
  "status" : 401
}

**Comment by vigliottim** [comment]
Potrebbe cortesemente controllare di aver riportato la response corretta?
Il _govway_id_ è un codice alfanumerico composto da 4 serie di caratteri/numeri intervallati da trattini.
_Es._ 5a370b09-bce7-11fd-adb0-004056ae54fa
In alternativa, può allegare il _trace_id_ se disponibile?
Grazie per la collaborazione.

**Comment by nbssrl** [comment]
Siamo riusciti a risolvere la problematica potete chiudere la Issue

**Comment by vigliottim** [comment]
Grazie per il suo gentile feedback.
Chiudiamo la issue come da sua richiesta.
Rimaniamo a disposizione per altre richieste di supporto.
