### ISSUE TITLE
Crash Program - RDE (Veneto) <> RDA (Toscana) SEND_TO_INI Blocking Error

### ISSUE THREAD

**Issue by ppalmerini** [ministero-salute/it-fse-support#1228]
Buonasera,
provando ad interrogare il servizio di validazione e pubblicazione creazione contestuale otteniamo un workflowInstanceId:
{
    "traceID": "23569cdbd18afb95",
    "spanID": "23569cdbd18afb95",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.8.4e8e041d67b51a92948c5983e55f2058f71f48af5a200dc05b261ef94c06368d.80e35ee15c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
Andando ad interrogare lo status https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/status/2.16.840.1.113883.2.9.2.50.4.4.8.4e8e041d67b51a92948c5983e55f2058f71f48af5a200dc05b261ef94c06368d.80e35ee15c%5E%5E%5E%5Eurn%3Aihe%3Aiti%3Axdw%3A2013%3AworkflowInstanceId
l'eventType SEND_TO_INI ci restituisce un errore bloccante:
{
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-07T16:50:32.910+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Parallel processing failed for number 0. Exchange[ID-rt-sanita-tc11-s1-rtpc-sct-toscana-it-60251-1730803927365-2-317]. Caused by: [java.lang.reflect.InvocationTargetException - null]",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.8.4e8e041d67b51a92948c5983e55f2058f71f48af5a200dc05b261ef94c06368d.80e35ee15c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-07T16:50:32.971+01:00"
        }
Chiediamo gentile riscontro e vostra assistenza, grazie

**Comment by mikeben89** [comment]
Buongiorno, 
abbiamo effettuato un altro tentativo verificando di utilizzare come person_id il paziente corretto (MNTMRA03M71C615V), ma otteniamo ancora un blocking error.
Questi i riferimenti dell'ultimo invio:

Request:
{ "assettoOrganizzativo": "AD_PSC131", "dataInizioPrestazione": "20241112151524", "healthDataFormat": "CDA", "identificativoDoc": "2.16.840.1.113883.2.9.2.50.4.4^202411121548", "identificativoRep": "2.16.840.1.113883.2.9.2.50.4.5.3.1", "identificativoSottomissione": "2.16.840.1.113883.2.9.2.50.4.3.202411121550", "mode": "ATTACHMENT", "priorita": true, "tipoAttivitaClinica": "OBS", "tipoDocumentoLivAlto": "VAC", "tipologiaStruttura": "Prevenzione" }

Response:
{
    "traceID": "50f60b993b9e472c",
    "spanID": "50f60b993b9e472c",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.8.43ba738c9df73ebc00f600176bc31d117fbd8d346584b35f22dcc4218a10f9c0.5e2130067b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

get status:
{
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-12T15:52:51.098+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Parallel processing failed for number 0. Exchange[ID-rt-sanita-tc11-s1-rtpc-sct-toscana-it-48875-1731340156422-2-270]. Caused by: [java.lang.reflect.InvocationTargetException - null]",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.8.43ba738c9df73ebc00f600176bc31d117fbd8d346584b35f22dcc4218a10f9c0.5e2130067b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-12T15:52:51.170+01:00"
        }

**Comment by OmarLorenzini** [comment]
ci risulta però nel messaggio il tag “authorPerson” non è valorizzato
<Slot name=\"authorPerson\"><ValueList><Value>^^^^^^^^&amp;&amp;ISO</Value></ValueList></Slot> 
potete provare a mettere nel “authorPerson” il CF PROVAX00X00X000Y

**Comment by ppalmerini** [comment]
Buonasera, possiamo chiudere l'issue per duplicazione problema qui: https://github.com/ministero-salute/it-fse-support/issues/1277

**Comment by vigliottim** [comment]
Procediamo alla chiusura dell'issue come richiesto. Grazie.

> Buonasera, possiamo chiudere l'issue per duplicazione problema qui: #1277
