### ISSUE TITLE
[400 BAD REQUEST] Sostituzione documento

### ISSUE THREAD

**Issue by apsstn** [ministero-salute/it-fse-support#123]
Buongiorno,
stiamo facendo delle prove per capire l`integrazione di tutte le API.

Abbiamo provato a fare una sostituzione ma il servizio ci risponde con il seguente messaggio

`HTTP/1.1 400 Bad Request
X-Backside-Transport: FAIL FAIL
Connection: Keep-Alive
Transfer-Encoding: chunked
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
Server: GovWay-SOGEI
Pragma: no-cache
GovWay-Transaction-ErrorType: InvalidRequestContent
GovWay-Transaction-ID: 3d720a16-b686-11ed-adb9-005056ae54fa
Date: Mon, 27 Feb 2023 10:24:21 GMT
Vary: *
X-Content-Type-Options: nosniff
Content-Type: application/problem+json
X-Global-Transaction-ID: 3f7e3e2d63fc84d54ae61a5d

{"type":"https://govway.org/handling-errors/400/InvalidRequestContent.html","title":"InvalidRequestContent","status":400,"detail":"Request content not conform to API specification: Validation error(s) :\nbody.requestBody: Additional property 'priorita' is not allowed. (code: 1000)\nFrom: body.requestBody.<#/components/schemas/PublicationUpdateReqDTO>.<additionalProperties>\nbody.requestBody: Additional property 'workflowInstanceId' is not allowed. (code: 1000)\nFrom: body.requestBody.<#/components/schemas/PublicationUpdateReqDTO>.<additionalProperties>\n","govway_id":"3d720a16-b686-11ed-adb9-005056ae54fa"}
`

Da documentazione però sembrano dei campi "non mandatory" ma inviabili.
Anche perchè immagino che il documento che sostituirà il vecchio, dovrà avere una validazione (quindi serve il campo workflowInstanceId) no?

allego la parte di requestBody invia

`{
  "healthDataFormat": "CDA",
  "mode": "ATTACHMENT",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.04946f51ea^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "tipologiaStruttura": "Ospedale",
  "attiCliniciRegoleAccesso": [
    "PUBLICPOL"
  ],
  "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^290701",
  "identificativoRep": "ID_REPOSITORY",
  "tipoDocumentoLivAlto": "WOR",
  "assettoOrganizzativo": "AD_PSC001",
  "tipoAttivitaClinica": "PHR",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.4.3.2",
  "priorita": true
}`

**Comment by IStacchiotti** [comment]
Buongiorno @apsstn, grazie della segnalazione. Si tratta di un bug già riscontrato in un issue precedente, seguirà una versione aggiornata della documentazione. Pertanto le chiediamo cortesemente di non passare i due campi in questione (sebbene siano citati dalla documentazione) e di procedere con la chiusura del presente, trattandosi di un duplicato del [#64](https://github.com/ministero-salute/it-fse-support/issues/64). Grazie mille.

**Comment by apsstn** [comment]
@IStacchiotti 

Grazie della risposta.
Ma quindi il documento che sostituirà il vecchio, non serve che venga validato come per la pubblicazione?

**Comment by apsstn** [comment]
@IStacchiotti 

Ho tolto i 2 campi (priorità e workflowInstanceId) e torna

`DEBUG 2023-02-27 12:25:01,423 [[gtw-fse-s-api].http.requester.HTTP_gtw_configuration.02 SelectorRunner] [processor: implementations.request/processors/0; event: 5cb607e0-b691-11ed-92e3-bcd0746b7ce1] org.mule.service.http.impl.service.HttpMessageLogger.http.requester.HTTP_gtw_configuration: REQUESTER
HTTP/1.1 400 Bad Request
X-Backside-Transport: FAIL FAIL
Connection: Keep-Alive
Transfer-Encoding: chunked
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
Set-Cookie: 894d46ecfc124039ee218b63c12a3329=14c1e046c320896bad1160a57b6f1772; path=/; HttpOnly; Secure; SameSite=None
Server: GovWay-SOGEI
Pragma: no-cache
GovWay-Message-ID: bf3e7c9a-7027-4d76-9487-f1fc3320afcc
GovWay-Transaction-ID: 20a2eff2-b688-11ed-a9a6-005056ae7395
Content-Disposition: inline;filename=f.txt
Date: Mon, 27 Feb 2023 11:25:01 GMT
Vary: *
X-Content-Type-Options: nosniff
Content-Type: application/problem+json
X-Global-Transaction-ID: 3f7e3e2d63fc930b4aef4f6d

e3
{"traceID":"43e6cb85a766b585","spanID":"43e6cb85a766b585","type":"/msg/cda-match","title":"Errore in fase di recupero dell'esito della verifica.","detail":"Il CDA non risulta validato","status":400,"instance":"/cda-validation"}
`

Puoi verificare per favore?

**Comment by IStacchiotti** [comment]
Rispondiamo in primo luogo alla prima domanda, confermando che la validazione è sempre necessaria e propedeutica alla pubblicazione e alla sostituzione. Il campo workflowInstanceId non è necessario in questo caso dal momento che viene utilizzato l'hash del cda per riconciliare il file validato con quello sostituente. Pertanto, l'ultimo errore segnalato si verifica dal momento che non è stata eseguita la validazione del file. Non esiti a ricontattarci se il problema persiste, in caso contrario le chiediamo la cortesia di chiudere il presente, trattandosi di un duplicato del https://github.com/ministero-salute/it-fse-support/issues/64. Grazie mille.
