### ISSUE TITLE
 Servizio di Recupero Stato Transazione, nuovi eventType

### ISSUE THREAD

**Issue by nspazzoli** [ministero-salute/it-fse-support#1232]
Salve,

ci siamo accorti che il servizio in oggetto riporta degli avent Type "nuovi".
Una osservazione è sul formato data del eventDate dove la rappresentazione dell'offset del fuso orario e nel valore dell'orario non è deifferente dei precendenti.

> {
>     "spanID": "906d84f7017edbf3",
>     "traceID": "2ed1b504770dfb9f",
>     "transactionData": [
>         {
>             **"eventDate": "2024-11-08T09:38:41.807+0000",**
>             "eventType": "INI_CREATE_SOAP",
>             "expiringDate": "2025-11-08T09:38:41.908+0000",
>             "message": "SOAP_REQUEST:<S:Envelope xmlns:S=\"http://</ns3:RegistryResponse></soapenv:Body></soapenv:Envelope>",
>             "workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.0cbc28155abdac08fa0d30def1a8222d0491a89161736326de80ccab44a237f5.2f4ba3a827^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
>         },
>         {
>             **"eventDate": "2024-11-08T10:38:34.365+01:00",**
>             "eventStatus": "SUCCESS",
>             "eventType": "VALIDATION",
>             "expiringDate": "2025-11-08T10:38:34.451+01:00",
>             "issuer": "integrity:S1#080#EMILIAROMAGNA",
>             "organizzazione": "080",
>             "subject": "MDCBGN54A01A944D^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
>             "traceId": "88af1ea674111d3c",
>             "workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.0cbc28155abdac08fa0d30def1a8222d0491a89161736326de80ccab44a237f5.2f4ba3a827^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
>         },
>         {
>             "eventDate": "2024-11-08T10:38:41.777+01:00",
>             "eventStatus": "SUCCESS",
>             "eventType": "PUBLICATION",
>             "expiringDate": "2025-11-08T10:38:41.785+01:00",
>             "identificativoDocumento": "2.16.840.1.113883.2.9.2.80.4.4^105LAB1731058710873MFFBGZ",
>             "issuer": "integrity:S1#080#EMILIAROMAGNA",
>             "organizzazione": "080",
>             "subject": "MDCBGN54A01A944D^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
>             "tipoAttivita": "ERP",
>             "traceId": "6975b97ae372f6bf",
>             "workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.0cbc28155abdac08fa0d30def1a8222d0491a89161736326de80ccab44a237f5.2f4ba3a827^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
>         },
>         {
>             "eventDate": "2024-11-08T10:38:42.713+01:00",
>             "eventStatus": "BLOCKING_ERROR",
>             "eventType": "SEND_TO_INI",
>             "expiringDate": "2025-11-08T10:38:42.777+01:00",
>             "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R166CODE CONTEXT:Wrong value of referenceIdList",
>             "workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.0cbc28155abdac08fa0d30def1a8222d0491a89161736326de80ccab44a237f5.2f4ba3a827^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
>         }
>     ]
> }

 "eventDate": "2024-11-08T09:38:41.807+0000",
"eventDate": "2024-11-08T10:38:42.713+01:00",

Grazie

**Comment by vigliottim** [comment]
Buongiorno,
è stato rilasciato un aggiornamento. 
Potreste cortesemente riprovare? Grazie.
