### ISSUE TITLE
Mancato accreditamento A1#111#NAMURSRLXX - Namur srl - GLPX - 1.0

### ISSUE THREAD

**Issue by NAMURSRL** [ministero-salute/it-fse-support#1233]
Buongiorno,
a seguito della ricezione del file errors.json ,
abbiamo provveduto a inviare i files corretti 

potete darci conferma dell'avvenuta ricezione ?

Grazie

**Comment by vigliottim** [comment]
Buonasera,
potrebbe gentilmente indicare il numero della pull-request con le correzioni?
Grazie.

**Comment by vigliottim** [comment]
Gli ultimi commit della pull-request #1676 di cui è stato fatto il merge risalgono a 3 giorni fa: https://github.com/ministero-salute/it-fse-accreditamento/pull/1676/commits

![image](https://github.com/user-attachments/assets/58659230-012f-49f8-9b30-a9d60586f65f)

Deve effettuare una nuova pull-request correttiva, caricando i file modificati.
Rimaniamo a disposizione.

**Comment by NAMURSRL** [comment]
Grazie,
ho inviato ora  la pull request 1693
è corretto ?

**Comment by IStacchiotti** [comment]
Buonasera, Le confermiamo che la pr è stata aperta correttamente, riceverà gli esiti delle verifiche via email. Grazie

**Comment by NAMURSRL** [comment]
Buonasera,
avete novità in merito agli esiti delle verifiche ?
Grazie

**Comment by NAMURSRL** [comment]
Buongiorno,

non ho ricevuto via e-mail l’esito.

sebbene sul repository è presente l’informazione di accreditamento

https://github.com/ministero-salute/it-fse-accreditamento/blob/main/GATEWAY/A1%23111%23NAMURSRLXX/Namur%20srl/GLPX/1.0/accreditation_2024_11_12T16_58_30.txt

 

Per poter visualizzare il software sulla lista dei convalidati devo fare qualcosa?

 

Vi ringrazio

Michele Gambelunghe

 

 

Da: Michela Vigliotti ***@***.***> 
Inviato: martedì 12 novembre 2024 18:43
A: ministero-salute/it-fse-support ***@***.***>
Cc: NAMURSRL ***@***.***>; Author ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Mancato accreditamento A1#111#NAMURSRLXX - Namur srl - GLPX - 1.0 (Issue #1233)

 

Buonasera, avete novità in merito agli esiti delle verifiche ? Grazie

Buonasera,
dovrebbe aver ricevuto l'esito delle elaborazioni via e-mail.
Rimaniamo a disposizione.

**Comment by LucaRogledi** [comment]
Buongiorno, 
una volta ricevuto l'esito delle verifiche tramite e-mail, dovrà attendere le verifiche da parte del DTD ed eventualmente integrare la checklist come richiesto. 
Grazie
