### ISSUE TITLE
Regione Sardegna pubblicazione Vs Regione Abruzzo

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#1234]
Buongiorno,
abbiamo effettuato un tentativo di pubblicazione verso la regione

```
traceId: 672cf1581f768eef096e196864cf4b05

DocumentEntry.uniqueId: 2.16.840.1.113883.2.9.4.3.8^200106TRCTST70A01L378S20241107174500050949
workflowInstanceId: 2.16.840.1.113883.2.9.2.120.4.4.eabb3393edd82ba92bb7bb49ad660dee719c4857d53faba35c5107447946d6ac.212e666481^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
```
successivamente, controllando l'esito stato transazione otteniamo il seguente errore:
`BLOCKING_ERROR message=SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 1166`

Vi chiediamo gentilmente di eseguire una verifica sul problema riscontrato per identificare le cause dell’errore e supportarci nella risoluzione, al fine di consentire il corretto completamento della pubblicazione.

Rimaniamo a disposizione

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, la presente issue viene chiusa.
Sarà possibile riaprirla nel caso in cui sia necessario ulteriore supporto.
Grazie.
