### ISSUE TITLE
Regione Sardegna pubblicazione vs Regione Calabria

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#1235]
Buongiorno,
abbiamo effettuato un tentativo di pubblicazione verso la regione

```
traceId: 672dd368a5b2781d0e938266f35fb47c

DocumentEntry.uniqueId:2.16.840.1.113883.2.9.4.3.8^200106MLRFNC62C25F112I20241108095843195886
workflowInstanceId: 2.16.840.1.113883.2.9.2.120.4.4.133ff0e22d0d0d8aeebd1b422a1a52b7e4a76615ded04f98953715ff32dd46d0.c35092960a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
```
successivamente, controllando l'esito stato transazione otteniamo il seguente errore:
`BLOCKING_ERROR message=SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 1166`

Vi chiediamo gentilmente di eseguire una verifica sul problema riscontrato per identificare le cause dell’errore e supportarci nella risoluzione, al fine di consentire il corretto completamento della pubblicazione.

Rimaniamo a disposizione

**Comment by LucaRogledi** [comment]
Buongiorno @FSESardegna , 
L'errore sembrerebbe essere causato dalla tipologia documentale utilizzata.
Potrebbe gentilmente riprovare la chiamata utilizzando un'altra tipologia documentale?
Grazie

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, la presente issue viene chiusa.
Sarà possibile riaprirla nel caso in cui sia necessario ulteriore supporto.
Grazie.
