### ISSUE TITLE
Regione Sardegna pubblicazione vs Regione Sicilia

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#1236]
Buongiorno,
abbiamo effettuato un tentativo di pubblicazione verso la regione

```
traceId: 672dd4b4ab5a140e58ceae72a0970219
DocumentEntry.uniqueId:2.16.840.1.113883.2.9.4.3.8^200106FSESCL80A41H163O20241108100416943370
workflowInstanceId: 2.16.840.1.113883.2.9.2.120.4.4.1f76f4e81e0d9f65b321462132a00cead8d86828dfd81962e684c052608b4e02.cec2b2332b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
```
successivamente, controllando l'esito stato transazione otteniamo il seguente errore:
`BLOCKING_ERROR message=SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 1166`

Vi chiediamo gentilmente di eseguire una verifica sul problema riscontrato per identificare le cause dell’errore e supportarci nella risoluzione, al fine di consentire il corretto completamento della pubblicazione.

Rimaniamo a disposizione

**Comment by LucaRogledi** [comment]
Buongiorno @FSESardegna , 
L'errore sembrerebbe essere causato dalla tipologia documentale utilizzata.
Potrebbe gentilmente riprovare la chiamata utilizzando un'altra tipologia documentale?
Grazie

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, la presente issue viene chiusa.
Sarà possibile riaprirla nel caso in cui sia necessario ulteriore supporto.
Grazie.
