### ISSUE TITLE
Regione Basilicata - UC6 Replace Errore SOAP 1.2 verso RDA=VALLE_AOSTA

### ISSUE THREAD

**Issue by BasilicataCrashProgramFSE** [ministero-salute/it-fse-support#1237]
Buongiorno,

Segnaliamo un errore "Adding text to SOAP 1.2 Fault is not legal" nella transazione di replace verso RDA Valle D'Oasta.
Di seguito i dettagli del caso:

Versione 1: 2.16.840.1.113883.2.9.2.170.4.4^201.AIRO.CRASHPROGRAM.20241107084340 --> OK
workFlowInstanceId=2.16.840.1.113883.2.9.2.170201.4.4.7825e58caf99ea216e3d4223bb789acd7aa7e74223fa833a36e81e85de9c1e65.365e79cac9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

Versione 2: 2.16.840.1.113883.2.9.2.170.4.4^201.AIRO.CRASHPROGRAM.20241108155150 --> KO
workFlowInstanceId=2.16.840.1.113883.2.9.2.170201.4.4.7825e58caf99ea216e3d4223bb789acd7aa7e74223fa833a36e81e85de9c1e65.ae6236981c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

Errore:
{
  ..
    "userMessage": "Generic",
    "systemMessage": "it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: javax.xml.ws.WebServiceException: com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Adding text to SOAP 1.2 Fault is not legal",
    "status": 500,
    "traceID": "d24712445c41b8eb",
    "spanID": "ae84e04dd5f16a29",
    "workflowInstanceId": null,
    "type": "/errors",
    "instance": "error/generic",
    "timestamp": "2024-11-08T15:37:46.893Z",
    "validatedBase64": null
}

Grazie

**Comment by ChiaraCeccottiFVG** [comment]
Buonasera,
solo ai fini di fornire un'indicazione aggiuntiva sperando sia utile per l'analisi del caso, anche da FVG confermiamo lo stesso errore. Vediamo che ci viene restituito anche su transazioni che in precedenza avevano dato success (ad es. la pubblicazione da FVG verso Lazio che funzionava restituisce un errore analogo a questo segnalato dalla regione Basilicata):
```
{
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-08T17:23:25.281+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "500 : \"{\"traceID\":\"d5a1ca3ec83dd56f\",\"spanID\":\"d5a1ca3ec83dd56f\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"javax.xml.ws.WebServiceException: it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: javax.xml.ws.WebServiceException: com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Adding text to SOAP 1.2 Fault is not legal\",\"instance\":\"error/generic\"}\"",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.d7167e48dbec3e83315fef97b3d664952f12c9475b20e46d8f1e1db5a683fa85.bba17b21b8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-08T17:23:25.364+01:00"
}
```
Grazie per le verifiche e buona serata.

**Comment by assistenza-fsevda** [comment]
Buongiorno,
stiamo riscontrando anche noi diversi problemi tutti rilevati nell'eventType "SEND_TO_INI". Vedo che è stata aperta la segnalazione  #1239 in merito ai servizi di INI. @vigliottim e @LucaRogledi - attendiamo l'esito di questo issue prima di procedere con altri test?

Grazie e buon lavoro.

**Comment by vigliottim** [comment]
> Buongiorno, stiamo riscontrando anche noi diversi problemi tutti rilevati nell'eventType "SEND_TO_INI". Vedo che è stata aperta la segnalazione #1239 in merito ai servizi di INI. @vigliottim e @LucaRogledi - attendiamo l'esito di questo issue prima di procedere con altri test?
> 
> Grazie e buon lavoro.

Buongiorno,
sono in corso delle verifiche.
Vi daremo aggiornamenti non appena disponibili.
Nel mentre potete sospendere l'esecuzione dei test.
Grazie.

**Comment by vigliottim** [comment]
> Buongiorno, stiamo riscontrando anche noi diversi problemi tutti rilevati nell'eventType "SEND_TO_INI". Vedo che è stata aperta la segnalazione #1239 in merito ai servizi di INI. @vigliottim e @LucaRogledi - attendiamo l'esito di questo issue prima di procedere con altri test?
> 
> Grazie e buon lavoro.

Vi informiamo che il problema è stato risolto.
Restiamo a disposizione.
Grazie.

**Comment by assistenza-fsevda** [comment]
Buongiorno @vigliottim e grazie per il riscontro.
Confermiamo che dai primi test eseguiti il problema sembra rientrato.

@BasilicataCrashProgramFSE avete modo di riprovare i casi verso regione 020 (VdA) andati in errore? In caso di ulteriori anomalie procederemo con un'analisi sui nostri sistemi.

Grazie e buon lavoro

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,

Abbiamo rifatto il test di replace: la prima versione va a buon fine, mentre la replace da un errore.

versione1: 2.16.840.1.113883.2.9.2.170.4.4^201.AIRO.CRASHPROGRAM.20241111155421  --> OK
workflowInstanceId=2.16.840.1.113883.2.9.2.170201.4.4.7825e58caf99ea216e3d4223bb789acd7aa7e74223fa833a36e81e85de9c1e65.4a2ca9ad34^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

versione2: 2.16.840.1.113883.2.9.2.170.4.4^201.AIRO.CRASHPROGRAM.20241111162618  --> KO
workflowInstanceId=2.16.840.1.113883.2.9.2.170201.4.4.7825e58caf99ea216e3d4223bb789acd7aa7e74223fa833a36e81e85de9c1e65.e249837809^^^^urn:ihe:iti:xdw:2013:workflowInstanceId,



--replace
PUT /documents/replace/2.16.840.1.113883.2.9.2.170.4.4%5E201.AIRO.CRASHPROGRAM.20241111155421


{
    "code": "ERROR",
    "userMessage": "Errore in fase di comunicazione con Gateway Nazionale",
    "status": 500,
    "traceID": "f6c9850cd1837e05",
    "spanID": "f6c9850cd1837e05",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.170201.4.4.7825e58caf99ea216e3d4223bb789acd7aa7e74223fa833a36e81e85de9c1e65.e249837809^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
    "timestamp": "2024-11-11T15:34:16.957Z"
 
}

A disposizione
Grazie

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,

Confermo che vediamo tutti eventi positivi nella risposta dello status.
La transazione era andato in timeout nello stratto di middleware nostro che comunica con il gateway nazionale. 
Procediamo con la chiusura della issue.
Grazie del supporto
