### ISSUE TITLE
Regione Sicilia - Crash Program - Test Case UC10 e UC12

### ISSUE THREAD

**Issue by bamoruso-git** [ministero-salute/it-fse-support#1238]
Buonasera,
visto che le regioni in sussidiarietà, come la Regione Sicilia, continuano ad utilizzare il servizio di "creazione metadati" per la pubblicazione di un documento, non è chiaro come verificare i casi di test UC10 e UC12 che, rispettivamente, riguardano i servizi:

1. Servizio di validazione pubblicazione creazione contestuale
2. Servizio di validazione pubblicazione sostituzione contestuale

esposti dal Gateway.
Grazie

**Comment by vigliottim** [comment]
Buongiorno,
i casi di test UC10 e UC12 non interessano il Post Crash Program.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
Grazie.
