### ISSUE TITLE
Crash Program - INI KO?

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#1239]
Buongiorno per molte le regioni ci viene restituito un errore 500

        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-08T21:16:15.137+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "500 : \"{\"traceID\":\"c80a7050836eb23d\",\"spanID\":\"c80a7050836eb23d\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.server.UnsupportedMediaException: Unsupported Content-Type: application/soap-xml Supported ones are: [application/soap+xml]\",\"instance\":\"error/generic\"}\"",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.41201.4.4.1.2b806b44e6b34853d7e1e9a4113f1209af92c6f3564d2e88d2f80d3d6c5f6ba9.9ac2d87276^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-08T21:16:15.148+01:00"
        }

**Comment by SonnyMate** [comment]
Mi pare sia ancora tutto KO

**Comment by vigliottim** [comment]
Buongiorno,
grazie per la segnalazione.
Le daremo aggiornamenti non appena disponibili.
