### ISSUE TITLE
Richiesta riapertura

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#1244]
per cortesia potete riaprire
https://github.com/ministero-salute/it-fse-support/issues/1197

**Comment by vigliottim** [comment]
> per cortesia potete riaprire #1197

Buonasera,
come da sua richiesta abbiamo riaperto l'issue #1197.
La informiamo che, se desidera, può riaprire le issue autonomamente cliccando sul bottone in basso a destra "Reopen issue", indicandone la motivazione in un commento:

<img width="676" alt="image" src="https://github.com/user-attachments/assets/bec9e3d9-b66d-448b-8326-3e39c37debd7">

Grazie.
