### ISSUE TITLE
Crash program - Bolzano vs piemonte eliminazione

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#1245]
Chiediamo indicazione per questo errore:
        {
            "eventType": "INI_DELETE",
            "eventDate": "2024-11-11T16:01:47.345+01:00",
            "eventStatus": "ASYNC_RETRY",
            "message": "Transazione presa in carico",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_000000000102",
            "subject": "PSCRNI82B64A952I^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "041",
            "workflowInstanceId": "faf23612f94da5334a35f179e79b854c3739c06d16f82f48fe20d027998953dc.a743875b58^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "6ba3823164037976",
            "issuer": "integrity:S2#041#PABOLZANOTEST",
            "expiringDate": "2025-11-11T16:01:47.354+01:00"
        },
        {
            "eventType": "DESERIALIZE",
            "eventDate": "2024-11-11T16:01:47.352+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "{\"idDoc\":\"2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_000000000102\",\"uuid\":[],\"sub\":\"PSCRNI82B64A952I^^^&2.16.840.1.113883.2.9.4.3.2&ISO\",\"iss\":\"integrity:S2#041#PABOLZANOTEST\",\"subject_organization\":\"P.A. Bolzano\",\"subject_organization_id\":\"041\",\"locality\":\"LABORATORIO DI PROVA^^^^^&2.16.840.1.113883.2.9.4.1.3&ISO^^^^111101123456\",\"subject_role\":\"AAS\",\"person_id\":\"SCLSCL00A55G273T^^^&2.16.840.1.113883.2.9.4.3.2&ISO\",\"purpose_of_use\":\"UPDATE\",\"action_id\":\"DELETE\",\"resource_hl7_type\":\"('11502-2^^2.16.840.1.113883.6.1')\",\"patient_consent\":true,\"documentType\":\"UNKNOWN_DOCUMENT_TYPE\",\"subject_application_id\":\"CONCERTO\",\"subject_application_vendor\":\"DEDALUS SPA\",\"subject_application_version\":\"22.1.1\",\"workflow_instance_id\":\"faf23612f94da5334a35f179e79b854c3739c06d16f82f48fe20d027998953dc.a743875b58^^^^urn:ihe:iti:xdw:2013:workflowInstanceId\",\"administrative_request\":[],\"author_institution\":\"UNKNOWN_AUTHOR_INSTITUTION\"}",
            "workflowInstanceId": "faf23612f94da5334a35f179e79b854c3739c06d16f82f48fe20d027998953dc.a743875b58^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-11T16:01:47.405+01:00"
        }

**Comment by SonnyMate** [comment]
Otteniamo stesso errore anche da sardegna

**Comment by marco-volpe** [comment]
Buongiorno

ci sono problemi con la cancellazione di documenti oscurati.
Potreste fare dei test con documenti non oscurati?

Grazie, restiamo a disposizione

**Comment by marco-volpe** [comment]
Buongiorno @SonnyMate 

dovremmo aver risolto il problema, potete provare a fare un nuovo test?

Grazie

**Comment by vigliottim** [comment]
Buongiorno @SonnyMate,
chiediamo gentilmente di dare un riscontro alla regione Piemonte.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso fosse necessario ulteriore supporto. Grazie.
