### ISSUE TITLE
Crash Program - Bolzano vs Veneto

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#1247]
Riceviamo il seguendo errore chiediamo indicazione

        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-11-11T16:22:19.740+01:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_000000000103",
            "subject": "PSCRNI82B64A952I^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "ERP",
            "organizzazione": "041",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.41201.4.4.1.5d94f81989e8a4c933ec0914167c2caf187711e7db4a669de93bafa3faea281c.8b967c774a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "f3000f1a9e42111a",
            "issuer": "integrity:S2#041#PABOLZANOTEST",
            "expiringDate": "2025-11-11T16:22:19.791+01:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-11T16:22:20.870+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryMetadataErrorCODE CONTEXT:ERRORE #5001: SubmissionSet uniqueId is already present in the registry",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.41201.4.4.1.5d94f81989e8a4c933ec0914167c2caf187711e7db4a669de93bafa3faea281c.8b967c774a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-11T16:22:20.884+01:00"
        }
    ]

**Comment by mikeben89** [comment]
Buonasera,
l'errore è dovuto al fatto che l'invio è stato effettuato indicando un XDSSubmissionSet.uniqueId che è già stato utilizzato in precedenza. Ci risulta infatti già presente e associato al documento 2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_000000000027

Chiediamo quindi di effettuare un altro tentativo indicando un XDSSubmissionSet.uniqueId diverso.

Grazie.

**Comment by vigliottim** [comment]
@SonnyMate 

Buongiorno,
chiediamo cortesemente un riscontro.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso fosse necessario ulteriore supporto. Grazie.
