### ISSUE TITLE
crash-program. errore pubblicazione LDO vs Provincia Autonoma di Trento

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#1248]
Buongiorno,
lo status del Gtw restituisce un errore in pubblicazione di una LDO verso provincia di Trento. 

> SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.

Il CF utilizzato è TRCTST70A01L378S

Allego risposta dello status
[pubblicazione_cf_provincia_trento.json](https://github.com/user-attachments/files/17715791/pubblicazione_cf_provincia_trento.json)

Grazie

**Comment by vigliottim** [comment]
@apsstn

Chiediamo gentilmente alla regione RDA di riferimento di fornire supporto.
Grazie.

**Comment by alessandropassamonti** [comment]
buongiorno.
Ci sono novità?

**Comment by nicola-ferrari-threadsolutions** [comment]
@alessandropassamonti potete riprovare?

cc @apsstn

**Comment by alessandropassamonti** [comment]
posso provare con un documento di RSA o c'è il problema del display name del typeCode?

**Comment by alessandropassamonti** [comment]
Buongiorno,
ora lo status del Gtw mi dice ha la pubblicazione è OK
@LucaRogledi @vigliottim rimane il problema già noto dello stato di esitoCaricamentoDocumento che rimane in **ELAB**

Grazie

**Comment by nicola-ferrari-threadsolutions** [comment]
Buonasera
Abbiamo avuto dei problemi in fase di storicizzazione documenti.

Potete gentilmente procedere con una nuova pubblicazione ed in seguito gli altri UC?

Grazie

cc @apsstn

**Comment by alessandropassamonti** [comment]
buongiorno,
ho pubblicato un nuovo documento

CF
TRCTST70A01L378S

XDSDocumentEntry.uniqueId
2.16.840.1.113883.2.9.2.130.4.4^501092

workflowInstanceId
2.16.840.1.113883.2.9.2.130202.4.4.5a94b417f977f6f5408d46eed6cd00f2ed80f44829dd8582e9bd7936945918d0.2a49a4a2e9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

vi risulta indicizzato?

**Comment by apsstn** [comment]
Buongiorno, indicizzato alle ore 09:48 di oggi 20/11

Curiosità: come RDE non vi è arrivata la notifica di avvenuta comunicazione metadati?

**Comment by alessandropassamonti** [comment]
buongiorno grazie,
siamo in sussidiarietà e passa tutto tramite INI

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
