### ISSUE TITLE
Regione Liguria - Blocking Error in Pubblicazione verso Sicilia

### ISSUE THREAD

**Issue by GiuseppeMaiulli** [ministero-salute/it-fse-support#1250]
Buongiorno,

riceviamo errore 1062 in pubblicazione verso Sicilia:

        {
            "eventType": "VALIDATION",
            "eventDate": "2024-11-07T12:04:17.391+01:00",
            "eventStatus": "SUCCESS",
            "subject": "MLLGPP81M29D969N^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "070",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.70.4.4.0c0d2a5412dfd3e9ae1d5b0733c09dcacf2cb1c0dfaac11f400d4f17444c58e1.f5d5429360^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "a343a373a8c9b63b",
            "issuer": "integrity:S1#070#REGIONELIGURIATEST",
            "expiringDate": "2025-11-07T12:04:17.400+01:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-11-07T12:04:32.989+01:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.70.4.4^RAD.19076724110.1",
            "subject": "MLLGPP81M29D969N^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "CON",
            "organizzazione": "070",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.70.4.4.0c0d2a5412dfd3e9ae1d5b0733c09dcacf2cb1c0dfaac11f400d4f17444c58e1.f5d5429360^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "76cec698ce996a4c",
            "issuer": "integrity:S1#070#REGIONELIGURIATEST",
            "expiringDate": "2025-11-07T12:04:32.999+01:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-07T12:04:33.796+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 1062",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.70.4.4.0c0d2a5412dfd3e9ae1d5b0733c09dcacf2cb1c0dfaac11f400d4f17444c58e1.f5d5429360^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-07T12:04:33.868+01:00"
        }

Potete verificare per cortesia?
Grazie

**Comment by vigliottim** [comment]
@bamoruso-git

Chiediamo gentilmente alla regione RDA di riferimento di fornire supporto.
Grazie.

**Comment by bamoruso-git** [comment]
Buon pomeriggio,
la Regione Sicilia è in sussidiarietà. Quindi va coinvolto direttamente Sogei

**Comment by vigliottim** [comment]
Buonasera,
l'errore 1062 è descritto come "Conservazione sostitutitva non valida".
Esso è causato dal fatto che la regione RDE ha valorizzato il campo conservazione a norma con "string":

![image](https://github.com/user-attachments/assets/696944f9-7a3b-4a73-8eb9-8c078532c770)

![image](https://github.com/user-attachments/assets/fe634048-30ba-4d28-a78a-574e6bf2c568)

Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by GiuseppeMaiulli** [comment]
Corretto il campo ConservazioneANorma e la pubblicazione è andata a buon fine

**Comment by vigliottim** [comment]
Grazie per il gentile riscontro.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
