### ISSUE TITLE
Regione Liguria - Blocking Error "RDA generated an internal error" in pubblicazione verso Emilia Romagna

### ISSUE THREAD

**Issue by GiuseppeMaiulli** [ministero-salute/it-fse-support#1251]
Buongiorno,

riceviamo errore "RDA generated an internal error" in pubblicazione verso Emilia Romagna:

        {
            "eventType": "VALIDATION_FOR_PUBLICATION",
            "eventDate": "2024-11-12T13:44:25.697+01:00",
            "eventStatus": "SUCCESS",
            "subject": "MLLGPP81M29D969N^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "070",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.70.4.4.fedc71f95c3fa05a5db4461d2fdac1b0c46e08fbe379392f194dc1fbe12e071e.2868018586^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "5baa246a3bceed1e",
            "issuer": "integrity:S1#070#REGIONELIGURIATEST",
            "expiringDate": "2025-11-12T13:44:25.752+01:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-11-12T13:44:25.839+01:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.70.4.4^LDO.8394895201.1",
            "subject": "MLLGPP81M29D969N^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "CON",
            "organizzazione": "070",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.70.4.4.fedc71f95c3fa05a5db4461d2fdac1b0c46e08fbe379392f194dc1fbe12e071e.2868018586^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "5baa246a3bceed1e",
            "issuer": "integrity:S1#070#REGIONELIGURIATEST",
            "expiringDate": "2025-11-12T13:44:25.847+01:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-12T13:44:26.949+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.70.4.4.fedc71f95c3fa05a5db4461d2fdac1b0c46e08fbe379392f194dc1fbe12e071e.2868018586^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-12T13:44:26.997+01:00"
        }
    ]
}

Potete verificare per cortesia?
Grazie

**Comment by vigliottim** [comment]
@daniele-gubellini

Chiediamo gentilmente alla regione RDA di riferimento di fornire supporto.
Grazie.

**Comment by daniele-gubellini** [comment]
Buonasera,
il dato "repository type" contiene il valore anomalo "string":

```
          <ns2:Slot name="urn:ita:2017:repository-type">
            <ns2:ValueList>
              <ns2:Value>string</ns2:Value>
            </ns2:ValueList>
          </ns2:Slot>
```

**Comment by LucaRogledi** [comment]
Buonasera, ringraziamo per il feedback, e procediamo con la chiusura della presente issue. Grazie
