### ISSUE TITLE
Regione Liguria - Blocking Error "Internal Error 9000" in pubblicazione verso Piemonte

### ISSUE THREAD

**Issue by GiuseppeMaiulli** [ministero-salute/it-fse-support#1252]
Buongiorno,

riceviamo l'errore "Internal Error 9000" in pubblicazione verso Piemonte:

        {
            "eventType": "VALIDATION_FOR_PUBLICATION",
            "eventDate": "2024-11-12T15:54:25.474+01:00",
            "eventStatus": "SUCCESS",
            "subject": "MLLGPP81M29D969N^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "070",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.70.4.4.61893e9fc27ea2f880c08a6970ec97c22338d66f65e005ea226e8152c00c4f3c.edde66cd25^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "e4a72d110866258b",
            "issuer": "integrity:S1#070#REGIONELIGURIATEST",
            "expiringDate": "2025-11-12T15:54:25.591+01:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-11-12T15:54:25.718+01:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.70.4.4^RAD.01073725206.1",
            "subject": "MLLGPP81M29D969N^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "CON",
            "organizzazione": "070",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.70.4.4.61893e9fc27ea2f880c08a6970ec97c22338d66f65e005ea226e8152c00c4f3c.edde66cd25^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "e4a72d110866258b",
            "issuer": "integrity:S1#070#REGIONELIGURIATEST",
            "expiringDate": "2025-11-12T15:54:25.731+01:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-12T15:54:26.653+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 9000",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.70.4.4.61893e9fc27ea2f880c08a6970ec97c22338d66f65e005ea226e8152c00c4f3c.edde66cd25^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-12T15:54:26.721+01:00"
        }

Potete verificare per cortesia?
Grazie

**Comment by marco-volpe** [comment]
Buongiorno @GiuseppeMaiulli 

non vediamo in ingresso la comunicazione metadati relativa al documento **2.16.840.1.113883.2.9.2.70.4.4^RAD.01073725206.1**
Pensiamo che l'errore possa essersi verificato prima che INI provasse a contattarci.

Potreste eseguire un altro test? Chiedo anche a @vigliottim di fare delle verifiche all'interno del GTW

Resto a disposizione

**Comment by GiuseppeMaiulli** [comment]
Eseguito nuovamente il test. La pubblicazione è andata a buon fine

**Comment by vigliottim** [comment]
Grazie per il gentile riscontro, chiudiamo la presente issue e rimaniamo a disposizione.
