### ISSUE TITLE
riapertura issue

### ISSUE THREAD

**Issue by izamberlan** [ministero-salute/it-fse-support#1253]
Mi scuso, ma io non trovo il tasto per riaprire una issue chiusa. Eì possibile riaprire la #1204 ?
grazie

**Comment by vigliottim** [comment]
Buonasera, 
abbiamo riaperto l'issue #1204 come da sua richiesta.
Può trovare il bottone "Reopen issue" in fondo sotto la textarea "Add a comment":

<img width="689" alt="image" src="https://github.com/user-attachments/assets/42c77abf-5863-41b2-b339-4965f7c3f250">

Chiudiamo la presente issue.
Grazie.

**Comment by vigliottim** [comment]
> Boh, da me non c'è ![addacomment](https://private-user-images.githubusercontent.com/108079288/385349019-9a38a72e-1fc3-4816-9b6e-a136af368c68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjU4MjgsIm5iZiI6MTczMTQyNTUyOCwicGF0aCI6Ii8xMDgwNzkyODgvMzg1MzQ5MDE5LTlhMzhhNzJlLTFmYzMtNDgxNi05YjZlLWExMzZhZjM2OGM2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQxNTMyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTRjMTM3Mzk5ZmQ3MWFmM2E0MTE0ZWZjYjM2YTM4MTc5OTg5MGE2ZGQ1M2M0MWIzZGYyMWY3NzQ4ODNhNmRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UVX25KIMUdSrwvh2Af4T9nS6mEmWaLIzHXR8kdkNwqQ)

In questo caso, se vuole evitare di aprire una issue, può taggarci in un commento sotto l'issue chiusa che vuole riaprire.
Grazie per la collaborazione.
