### ISSUE TITLE
Crash program - Validate and create error - RDA (Sardegna) <> RDE (Veneto)

### ISSUE THREAD

**Issue by mikeben89** [ministero-salute/it-fse-support#1255]
Buongiorno, 
abbiamo provato ad inviare una validate and create nelle condizioni come da titolo.
Il timestamp del tentativo è 2024-11-12 17:03:19

A fronte della request
{ "assettoOrganizzativo": "AD_PSC131", "dataInizioPrestazione": "20241112151524", "healthDataFormat": "CDA", "identificativoDoc": "2.16.840.1.113883.2.9.2.50.4.4^202411121701", "identificativoRep": "2.16.840.1.113883.2.9.2.50.4.5.3.1", "identificativoSottomissione": "2.16.840.1.113883.2.9.2.50.4.3.202411121703", "mode": "ATTACHMENT", "priorita": true, "tipoAttivitaClinica": "OBS", "tipoDocumentoLivAlto": "VAC", "tipologiaStruttura": "Prevenzione" }

Abbiamo ottenuto un success
{
    "traceID": "3ee630dca6e6ba90",
    "spanID": "3ee630dca6e6ba90",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.8.75724fc20e57d9179224320851aaa570d19484a06e1906ad541d2b09aff94d53.3bbe8a421c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

ma la Get Status segnala un errore da parte della RDA in SEND_TO_INI:
{
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-12T17:02:55.233+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.8.75724fc20e57d9179224320851aaa570d19484a06e1906ad541d2b09aff94d53.3bbe8a421c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-12T17:02:55.359+01:00"
        }
        
Potete darci supporto?

Grazie

**Comment by vigliottim** [comment]
@FSESardegna

Chiediamo gentilmente alla regione Sardegna di offrire supporto alla regione Veneto.
Grazie.

**Comment by vigliottim** [comment]
Grazie per il gentile riscontro.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
