### ISSUE TITLE
Crash program - Validate and create error - RDA (Bolzano) <> RDE (Veneto)

### ISSUE THREAD

**Issue by mikeben89** [ministero-salute/it-fse-support#1256]
Buongiorno,
abbiamo provato ad inviare una validate and create nelle condizioni come da titolo.
Il timestamp del tentativo è 2024-11-12 17:34:44

A fronte della request
{"assettoOrganizzativo": "AD_PSC131", "dataInizioPrestazione": "20241112151524", "healthDataFormat": "CDA", "identificativoDoc": "2.16.840.1.113883.2.9.2.50503.4.4.8^202411121732", "identificativoRep": "2.16.840.1.113883.2.9.2.50.4.5.3", "identificativoSottomissione": "2.16.840.1.113883.2.9.2.50503.4.4.8^202411121734", "mode": "ATTACHMENT", "priorita": true, "tipoAttivitaClinica": "OBS", "tipoDocumentoLivAlto": "VAC", "tipologiaStruttura": "Prevenzione"}

Abbiamo ottenuto un success
{
    "traceID": "75bfd7626fbb7aae",
    "spanID": "75bfd7626fbb7aae",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.8.360c0acb2443981b8d76747f8cfa7bc2fa0d61fa0fb24eb1ce7334cd0d0ab3c5.c38ab0c59d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

ma la Get Status segnala un errore da parte della RDA in SEND_TO_INI:
{
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-12T17:34:47.342+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.8.360c0acb2443981b8d76747f8cfa7bc2fa0d61fa0fb24eb1ce7334cd0d0ab3c5.c38ab0c59d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-12T17:34:47.351+01:00"
        }

Potete darci supporto?

Grazie

**Comment by vigliottim** [comment]
Buonasera @SonnyMate ,
chiediamo gentilmente di fornire supporto in quanto RDA di riferimento.
Grazie.

**Comment by mikeben89** [comment]
Buongiorno, 
abbiamo effettuato un altro invio, stavolta con esito positivo.

Grazie del supporto.
