### ISSUE TITLE
Richiesta informazioni per casi di test relativi a "Referto di Specialistica Ambulatoriale"

### ISSUE THREAD

**Issue by andreasantori** [ministero-salute/it-fse-support#126]
Buongiorno,
noi dovremmo procedere all'accreditamento relativamenta alla fase di validazione di un CDA2 di "Referto di Specialistica Ambulatoriale".
Nel modulo di richiesta accreditamento è possibile selezionare tale voce, ma nella sezione dei casi di test non vi sono quelli relativi a tale tipologia di documento.
Potete darci indicazioni in merito?

Grazie,
Andrea Santori

**Comment by IStacchiotti** [comment]
Buongiorno, le comunichiamo che a questo [link](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case) è stata appena pubblicata la checklist di validazione per RSA. Grazie.

**Comment by andreasantori** [comment]
Buongiorno, grazie per il feedback.
Un'altra cosa, nel Processo di accreditamento al FSE 2.0, relativamente all'aderenza dei documenti CDA alle specifiche nazionali, ad un certo punto si menziona

"terminologiche applicando le specifiche e i dizionari pubblicati su git FSE Salute;"

Mi potreste indicare dove si trovano queste informazioni?
Grazie

**Comment by andreasantori** [comment]
Grazie per il feedback.
chiudo il ticket
