### ISSUE TITLE
Errore Validazione Schematron Anamnesi (REGIONE LAZIO)

### ISSUE THREAD

**Issue by Infordatadhs** [ministero-salute/it-fse-support#1263]
Buonasera,
stiamo effettuando i casi di test per RSA. Tuttavia durante la validazione con Schematron del CDA ci viene restituito un errore sul campo Età decesso dell'anamnesi famigliare (failed-assert /Q{urn:hl7-org:v3}ClinicalDocument[1]/Q{urn:hl7-org:v3}component[1]/Q{urn:hl7-org:v3}structuredBody[1]/Q{urn:hl7-org:v3}component[2]/Q{urn:hl7-org:v3}section[1]/Q{urn:hl7-org:v3}entry[1]/Q{urn:hl7-org:v3}organizer[1]/Q{urn:hl7-org:v3}component[1] ERRORE-b43| Sezione Storia Clinica: l'elemento entry/organizer/component/observation/entryRelationship/observation deve avere il code valorizzato con @code='39016-1' e deve contenere un elemento 'value') in quanto lo Schematron prevede che sia compilato obbligatoriamente il valore: code code="39016-1" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Età decesso"
Se il famigliare non è deceduto e quindi lo stato è attivo, come dovrebbe essere compilato il campo Età decesso?
Grazie

**Comment by vigliottim** [comment]
Buon pomeriggio,
potrebbe cortesemente allegare la response completa ricevuta (comprensiva di trace_id/govway_id) e il CDA2 utilizzato?
Grazie.

**Comment by Infordatadhs** [comment]
Il problema è solo durante la validazione del CDA con lo Schematron. Quando eseguiamo l'invio non dà nessun errore.
Alleghiamo CDA, TRACE e SCHEMATRON.
[cdaanamnesi.xml.txt](https://github.com/user-attachments/files/17734051/cdaanamnesi.xml.txt)
[FSETrace_VALIDATE_20241113153127.txt](https://github.com/user-attachments/files/17734052/FSETrace_VALIDATE_20241113153127.txt)
[schematron_RSA (1).sch.txt](https://github.com/user-attachments/files/17734069/schematron_RSA.1.sch.txt)

**Comment by LucaRogledi** [comment]
Buonasera, 
La sezione entryRelationsip in caso di famigliare non deceduto può essere valorizzata come indicato in [documentazione HL7 RSA](https://www.hl7.it/wp-content/uploads/2024/04/HL7IT-IG_CDA2_RSA-v1.1-S.pdf) nella sezione `<!—Età di insorgenza`.

![image](https://github.com/user-attachments/assets/7ed8a5d4-b081-43c0-832a-23ad18434de6)

la invitiamo gentilmente a riprovare secondo quanto indicato.
Grazie

**Comment by Infordatadhs** [comment]
Buonasera,

Grazie per la risposta ma il problema non è questo.

Il problema è nello schematron che impone almeno una presenza del codice 39016-1 relativo alla età di decesso.

 

<assert ***@***.***!='35267-4']])=1 and 

                                               ***@***.***='39016-1']])=1 and 

                                               ***@***.***='39016-1']]/hl7:value)=1"

 

Validation failed.

Validation messages:

failed-assert /Q{urn:hl7-org:v3}ClinicalDocument[1]/Q{urn:hl7-org:v3}component[1]/Q{urn:hl7-org:v3}structuredBody[1]/Q{urn:hl7-org:v3}component[2]/Q{urn:hl7-org:v3}section[1]/Q{urn:hl7-org:v3}entry[1]/Q{urn:hl7-org:v3}organizer[1]/Q{urn:hl7-org:v3}component[1] ERRORE-b43| Sezione Storia Clinica: l'elemento entry/organizer/component/observation/entryRelationship/observation deve avere il code valorizzato con @code='39016-1' e deve contenere un elemento 'value'

 

Saluti

Alberto Macrì

 

 

Da: LucaRogledi ***@***.***> 
Inviato: mercoledì 13 novembre 2024 16:29
A: ministero-salute/it-fse-support ***@***.***>
Cc: Infordatadhs ***@***.***>; Author ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Errore Validazione Schematron Anamnesi (REGIONE LAZIO) (Issue #1263)

 

Buonasera,
La sezione entryRelationsip in caso di famigliare non deceduto può essere valorizzata come indicato in documentazione HL7 RSA <https://www.hl7.it/wp-content/uploads/2024/04/HL7IT-IG_CDA2_RSA-v1.1-S.pdf>  nella sezione <!—Età di insorgenza.

image.png (view on web) <https://github.com/user-attachments/assets/7ed8a5d4-b081-43c0-832a-23ad18434de6> 

la invitiamo gentilmente a riprovare secondo quanto indicato.
Grazie

**Comment by vigliottim** [comment]
Buonasera,
lo schematron aggiornato per RSA è disponibile al link:
https://github.com/ministero-salute/it-fse-catalogs/blob/main/schematron/schematron_RSA_v8.1.sch
Le chiediamo gentilmente di informarci se sta usando lo schematron corretto.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Potrà riaprirla nel caso in cui avesse bisogno di ulteriore supporto.
Grazie.
