### ISSUE TITLE
Regione Sardegna cancellazione vs P.A. Bolzano

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#1265]
Buongiorno,

abbiamo eseguito una nuova serie di test per la cancellazione, e di seguito riportiamo i dettagli:

DocumentId: 2.16.840.1.113883.2.9.2.200.4.4^200106PRVFSN70S04A952Z20241113153450159009
traceId: 6734ba824e25953575a72cea42e4ace8
Durante la verifica dello stato della transazione, otteniamo la seguente risposta: ASYNC_RETRY.
Inoltre, eseguendo una ITI-18 di tipo LeafClass, recuperiamo i metadati. Potreste effettuare una verifica per confermarci se il documento è stato cancellato correttamente?

**Comment by LucaRogledi** [comment]
Buonasera @SonnyMate ,
chiediamo gentilmente alla regione di riferimento di verificare la corretta eliminazione.
Grazie

**Comment by FSESardegna** [comment]
Buongiorno,
ci sono aggiornamenti?

**Comment by vigliottim** [comment]
> Buonasera @SonnyMate , chiediamo gentilmente alla regione di riferimento di verificare la corretta eliminazione. Grazie

Buongiorno @SonnyMate,
invitiamo nuovamente la PA di Bolzano a fornire supporto.
Grazie.

**Comment by FSESardegna** [comment]
Buongiorno,
abbiamo eseguito delle nuove prove autonomamente e ora otteniamo un success.
Grazie

**Comment by vigliottim** [comment]
Grazie per il gentile riscontro.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
