### ISSUE TITLE
Disallineamento tra specifiche VPS e ritorno Validazione

### ISSUE THREAD

**Issue by rangeletti** [ministero-salute/it-fse-support#127]
Ciao,
abbiamo riscontrato un errore in validazione del CDA VPS, sull'elemento di seguito riportato:
__ClinicalDocument/component/structuredBody/component/section[@ID="Interventi_Prestazioni_Consulenze_Richieste"]/entry/act/statusCode/@code__ 

Da specifiche viene il valore che può assumere sono i seguenti:
_Tale campo può essere valorizzato con: - "Completed": elemento completato -"Aborted": elemento non completato_

Validando il CDA però, la validazione va in errore per il seguente errore:

_[CDATA[ERRORE-b172| Sezione Interventi Prestazioni Consulenze e Richieste: l'elemento entry/act DEVE contenere un elemento statusCode valorizzato con l'attributo @code='completed' o @code='aborted'.  ]]_

Viene quindi richiesto di inserire i valori con la lettera iniziale minuscola, quando da specifiche viene riportata la maiuscola.
Sarebbe possibile un chiarimento?

Grazie.

**Comment by Ser-ena** [comment]
Grazie per la segnalazione. Si richiede di far riferimento alla CONF-VPS-208: 
"CONF-VPS-208: L’elemento <act> DEVE contenere un elemento <statusCode> dove 
l’attributo @code DEVE assumere uno dei valori costanti ““aborted” o “completed”.

**Comment by PRAFFO72** [comment]
Salve, per quanto riguarda questo specifico errore, potrebbe essere dovuto a un refuso nello Schematron VPS,
 che non permette l'inserimento del valore "aborted".
Nello specifico, l'errore potrebbe essere nella sezione 8 (Interventi Prestazioni Consulenze e Richieste) alla riga 1002:

https://github.com/ministero-salute/it-fse-support/blob/main/validazione/schematron/schematron_VPS.sch#L1002

<assert test="count(hl7:act/hl7:statusCode[@code='completed'])=1 or count(hl7:observation/hl7:statusCode[@code='aborted'])=1"

La prima parte del test è correttamente riferita alla sottosezione "act",
 la seconda parte fa riferimento a una sotto sezione "observation", non presente in questo specifico contesto.

**Comment by rangeletti** [comment]
Buongiorno, 

l'estratto del CDA inviato è il seguente: 


          <entry>
            <act classCode="ACT" moodCode="EVN">
              <templateId root="2.16.840.1.113883.2.9.10.1.6.62"/>
              <code code="8826D" codeSystem="2.16.840.1.113883.2.9.2.1.6.11" codeSystemName="Catalogo Aurora" displayName="BACINO - RX"/>
              <text>BACINO - RX</text>
              <statusCode code="Completed"/>
              <performer>
                <time value="20230203162617"/>
                <assignedEntity>
                  <id extension="MDCDRP00A00X000C" root="2.16.840.1.113883.2.9.4.3.2"/>
                  <assignedPerson>
                    <name>
                      <given>OSPEDALE</given>
                      <family>MEDICO</family>
                    </name>
                  </assignedPerson>
                </assignedEntity>
              </performer>
            </act>
          </entry>

L'errore ritornato dal validatore sembra essere sul valore "Completed", che è riportato con la "C" maiuscola (come da specifiche), mentre il validatore richiede la "c" minuscola

**Comment by IStacchiotti** [comment]
Buongiorno, si chiede gentilmente di far riferimento alla CONF-VPS-208, dove è esplicitata la corretta valorizzazione dell'attributo code dell'elemento statusCode ovverro: <statusCode code="completed"/>

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
