### ISSUE TITLE
Regione Sardegna pubblicazione vs Regione Marche

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#1272]
Buongiorno,

abbiamo eseguito una pubblicazione verso la vs. Regione, di seguito i dettagli:
```
DocumentId: 2.16.840.1.113883.2.9.2.200.4.4^200106PRFSRA93C69A252A20241114095719978081
WII: 2.16.840.1.113883.2.9.2.200.4.4.576b13ce987ec18cd820ea727df9260645d770a370f06924dff70fbc33c5e3f0.6296ff7bc1^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
TraceId: 6735bc3d0a4fcc11331939107abf42c5
```
ma abbiamo ottenuto il seguente errore dallo verifica stato transazione:
`BLOCKING_ERROR message=SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.`

Potete  darci supporto?
Grazie

**Comment by vigliottim** [comment]
@Didi22515

Chiediamo gentilmente alla regione Marche in quanto regione RDA di riferimento di fornire supporto.
Grazie.

**Comment by FSESardegna** [comment]
Buongiorno,
ci sono aggiornamenti?

**Comment by vigliottim** [comment]
> @Didi22515
> 
> Chiediamo gentilmente alla regione Marche in quanto regione RDA di riferimento di fornire supporto. Grazie.

@Didi22515
Invitiamo nuovamente la regione Marche a dare supporto.
Grazie.

**Comment by Didi22515** [comment]
@vigliottim è possibile conoscere l'endpoint usato ?

**Comment by Didi22515** [comment]
Buon pomeriggio, 
@FSESardegna  è possibile riprovare?

**Comment by FSESardegna** [comment]
Buongiorno,
a seguito di una nuova pubblicazione con i seguenti dettagli:

```
DocumentId: 200106PRFSRA93C69A252A20241122094907162706
WII: 2.16.840.1.113883.2.9.2.200.4.4.d1ff4c66b77b1b1e42dcb3d97e69f77a161fb2996e28ca9c193812e83c3d3717.0ff66affb6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
TraceId: 6740459ed84bcc15b9846f6fe0f12880
VerificaTransazione: SUCCESS
```
ma non riusciamo ad eseguire una sostituzione, poichè eseguendo una ITI-18 come primo step otteniamo 
`
getDocument LeafClass:  "RDA generated an internal error." errorCode="CRF2"`

**Comment by Didi22515** [comment]
è possibile sapere quando è stata fatta la prova?

**Comment by vigliottim** [comment]
> è possibile sapere quando è stata fatta la prova?

La informiamo che chiamando il servizio status è possibile recuperare la lista di tutti gli eventi di una transazione associati a un determinato wii/traceid con relativo timestamp.
Di seguito i link alla documentazione:

- Servizio di Recupero Stato Transazione per WorkflowInstanceId: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#10-servizio-di-recupero-stato-transazione-per-workflowinstanceid
- _Servizio di Recupero Stato Transazione per TraceId:_ https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#11-servizio-di-recupero-stato-transazione-per-traceid

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso in cui sia necessario ulteriore supporto.
Grazie.
