### ISSUE TITLE
Regione Liguria - Blocking Error "Error processing request" in pubblicazione verso Bolcano

### ISSUE THREAD

**Issue by GiuseppeMaiulli** [ministero-salute/it-fse-support#1273]
Buongiorno,

riceviamo l'errore "Error processing request" in pubblicazione verso Bolzano.

        {
            "eventType": "VALIDATION_FOR_PUBLICATION",
            "eventDate": "2024-11-14T11:12:49.773+01:00",
            "eventStatus": "SUCCESS",
            "subject": "MLLGPP81M29D969N^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "070",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.70.4.4.0c47e45abcb8a83d2c16cb0cdd543d6bf1e60429231735167f9df7ba95afa66e.92b59d80a8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "45aa70667dc13c56",
            "issuer": "integrity:S1#070#REGIONELIGURIATEST",
            "expiringDate": "2025-11-14T11:12:49.816+01:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-11-14T11:12:50.035+01:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.70.4.4^RAD.04176824221.1",
            "subject": "MLLGPP81M29D969N^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "CON",
            "organizzazione": "070",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.70.4.4.0c47e45abcb8a83d2c16cb0cdd543d6bf1e60429231735167f9df7ba95afa66e.92b59d80a8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "45aa70667dc13c56",
            "issuer": "integrity:S1#070#REGIONELIGURIATEST",
            "expiringDate": "2025-11-14T11:12:50.091+01:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-14T11:12:51.360+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:JavaException: java.lang.Exception: java.lang.Exception: javax.xml.ws.soap.SOAPFaultException: Error processing request",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.70.4.4.0c47e45abcb8a83d2c16cb0cdd543d6bf1e60429231735167f9df7ba95afa66e.92b59d80a8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-14T11:12:51.368+01:00"
        }

Potete verificare per cortesia?
Grazie

**Comment by vigliottim** [comment]
Buonasera @SonnyMate ,
chiediamo gentilmente di fornire supporto in quanto RDA.
Grazie

**Comment by ngaraventa** [comment]
Buongiorno,
sarebbe possibile fare un'altra prova per piacere?
Mancava una parte di configurazione sull'issuer

Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Grazie
