### ISSUE TITLE
Regione Liguria - Blocking Error in Cancellazione verso Piemonte

### ISSUE THREAD

**Issue by GiuseppeMaiulli** [ministero-salute/it-fse-support#1274]
Buongiorno,

riceviamo il seguente errore in cancellazione del documento 2.16.840.1.113883.2.9.2.70.4.4^RAD.01076724210.1 verso Piemonte

         {
            "eventType": "RIFERIMENTI_INI",
            "eventDate": "2024-11-14T11:30:19.673+01:00",
            "eventStatus": "SUCCESS",
            "message": "Riferimenti trovati: [urn:uuid:58cb98d9-ced3-436f-9333-99c31d7e6a43]",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.70.4.4^RAD.01076724210.1",
            "subject": "MLLGPP81M29D969N^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "070",
            "workflowInstanceId": "762727db96b5a2efc82de0a12a751b9d5d88dd7d41f31cba51dfcde8e254f4a3.58a5e0f77a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "57fbf58d63cb93e0",
            "issuer": "integrity:S1#070#REGIONELIGURIATEST",
            "expiringDate": "2025-11-14T11:30:19.682+01:00"
        },
        {
            "eventType": "INI_DELETE",
            "eventDate": "2024-11-14T11:30:21.996+01:00",
            "eventStatus": "ASYNC_RETRY",
            "message": "Transazione presa in carico",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.70.4.4^RAD.01076724210.1",
            "subject": "MLLGPP81M29D969N^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "070",
            "workflowInstanceId": "762727db96b5a2efc82de0a12a751b9d5d88dd7d41f31cba51dfcde8e254f4a3.58a5e0f77a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "57fbf58d63cb93e0",
            "issuer": "integrity:S1#070#REGIONELIGURIATEST",
            "expiringDate": "2025-11-14T11:30:22.003+01:00"
        },
        {
            "eventType": "DESERIALIZE",
            "eventDate": "2024-11-14T11:30:21.998+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "{\"idDoc\":\"2.16.840.1.113883.2.9.2.70.4.4^RAD.01076724210.1\",\"uuid\":[\"urn:uuid:58cb98d9-ced3-436f-9333-99c31d7e6a43\"],\"sub\":\"MLLGPP81M29D969N^^^&2.16.840.1.113883.2.9.4.3.2&ISO\",\"iss\":\"integrity:S1#070#REGIONELIGURIATEST\",\"subject_organization\":\"Regione Liguria\",\"subject_organization_id\":\"070\",\"locality\":\"RADIOLOGIA PROVA ASL3^^^^^&2.16.840.1.113883.2.9.4.1.3&ISO^^^^220103010025\",\"subject_role\":\"AAS\",\"person_id\":\"SCLSCL00A55G273T^^^&2.16.840.1.113883.2.9.4.3.2&ISO\",\"purpose_of_use\":\"UPDATE\",\"action_id\":\"DELETE\",\"resource_hl7_type\":\"('68604-8^^2.16.840.1.113883.6.1')\",\"patient_consent\":true,\"documentType\":\"UNKNOWN_DOCUMENT_TYPE\",\"subject_application_id\":\"Middleware070\",\"subject_application_vendor\":\"Regione Liguria\",\"subject_application_version\":\"0.1\",\"workflow_instance_id\":\"762727db96b5a2efc82de0a12a751b9d5d88dd7d41f31cba51dfcde8e254f4a3.58a5e0f77a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId\",\"administrative_request\":[],\"author_institution\":\"UNKNOWN_AUTHOR_INSTITUTION\"}",
            "workflowInstanceId": "762727db96b5a2efc82de0a12a751b9d5d88dd7d41f31cba51dfcde8e254f4a3.58a5e0f77a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-14T11:30:22.168+01:00"
        }

Potete verificare per cortesia?
Grazie

**Comment by vigliottim** [comment]
Buonasera @marco-volpe,
chiediamo gentilmente alla regione Piemonte, RDA di riferimento, di fornire supporto.
Grazie.

**Comment by marco-volpe** [comment]
potete riprovare la cancellazione?

**Comment by GiuseppeMaiulli** [comment]
Grazie mille. Abbiamo riprovato la cancellazione ed è andata a buon fine

**Comment by vigliottim** [comment]
Grazie per il gentile riscontro.
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per altre richieste di supporto.
