### ISSUE TITLE
Errore Middleware Regionale

### ISSUE THREAD

**Issue by danielepecoraro** [ministero-salute/it-fse-support#1276]
Salve,
abbiamo eseguito dei test per la validazione su sistema nazionale con esito positivo. Abbiamo successivamente integrato il Middleware Regionale seguendo le procedure indicate, ma il sistema ritorna questo errore:

`{"type":"https:\/\/govway.org\/handling-errors\/400\/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":false,"detail":"Received request is not conform to the required interoperability profile","govway_id":"6e67f4b6-a273-11ef-808a-005056ae7395","log_id":1387} `

Avete info in merito?
Vi ringrazio.

**Comment by vigliottim** [comment]
Buongiorno,
i log della chiamata da lei effettuata mostrano il seguente errore:

![image](https://github.com/user-attachments/assets/0f9db43f-5070-441c-a219-20f539aa6dd2)

Decodificando i JWT con [jwt.io](jwt.io), è emerso che l'url usata per valorizzare il claim _aud_ non è corretta:

_FSE-JWT-Signature Token:_
![image](https://github.com/user-attachments/assets/4e903755-95f8-42b2-a0c9-d97ff3aaad5a)


_Authorization Bearer Token:_
![image](https://github.com/user-attachments/assets/4af8b5f2-8485-4c72-88f1-839aa21615fb)

Le chiediamo di correggere il claim _aud_ come segue e riprovare:
`"aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1"`
Grazie.

**Comment by danielepecoraro** [comment]
Ciao.

Sarebbe possibile accedere al messaggio di errore tramite il nostro govway-id?
Questo ci aiuterebbe nel capire dove stiamo sbagliando nelle procedure.

Attendo risposta in merito, grazie.

**Comment by vigliottim** [comment]
> Ciao.
> 
> Sarebbe possibile accedere al messaggio di errore tramite il nostro govway-id? Questo ci aiuterebbe nel capire dove stiamo sbagliando nelle procedure.
> 
> Attendo risposta in merito, grazie.

No, purtroppo non è possibile.

**Comment by vigliottim** [comment]
L'errore mostrato sui log per la chiamata con "govway_id":"fc779113-a28c-11ef-808a-005056ae7395" è il seguente:

![image](https://github.com/user-attachments/assets/40bd00a9-3f00-459c-a7e2-1dbe875c0620)

Dalle analisi svolte è emerso che nell'_Authorization Bearer Token_ manca il claim _iss_ che risulta obbligatorio da [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt).

![image](https://github.com/user-attachments/assets/132e9e13-d02c-4744-bd7c-2092ccb2fc94)
![image](https://github.com/user-attachments/assets/02bd67d0-1cd3-4cfb-a897-cead835ea354)

Le chiediamo di aggiungerlo e riprovare. 
Grazie.

**Comment by danielepecoraro** [comment]
Perfetto, abbiamo risolto.
Grazie mille.

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback, e procediamo con la chiusura della presente issue. Grazie
