### ISSUE TITLE
Crash test - RDA (Toscana) <> RDE (Veneto) - Errore in validate and create

### ISSUE THREAD

**Issue by mikeben89** [ministero-salute/it-fse-support#1277]
Buongiorno,
abbiamo effettuato un tentativo di validate and create con un documento di tipo patient summary. Validazione e pubblicazione passano, ma abbiamo un errore in indicizzazione su ini: 

{
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-14T14:26:25.411+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Parallel processing failed for number 0. Exchange[ID-rt-sanita-tc11-s1-rtpc-sct-toscana-it-48875-1731340156422-2-817]. Caused by: [java.lang.reflect.InvocationTargetException - null]",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.2.12345.4.4.2.8ba0fb2271510b5ef1e03f4ca0b874c9db25ad3279b38a6cdc121a6d7a3050f5.efd83a0d91^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-14T14:26:25.462+01:00"
        }
        
Per controllo, visti casi simili anche per altri test, abbiamo verificato che la richiesta di ini avesse il tag authorPerson valorizzato, e risulta corretto:

`<Slot name=\"authorPerson\"><ValueList><Value>GRLMSM60R31F770Y^^^^^^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</Value>`

Potete darci supporto per l'errore su SEND_TO_INI?

Grazie.

**Comment by mgirardello** [comment]
@vigliottim chiedo cortesemente di attivare RDA toscana per un riscontro

**Comment by vigliottim** [comment]
@Gianpr0 @OmarLorenzini 

Chiediamo alla regione Toscana, RDA di riferimento, di fornire supporto.
Grazie.

**Comment by mgirardello** [comment]
l'alternativa è, riuscite voi a fornirci voi un documento firmato che abbia al suo interno (CDA) il firmatario che viene da voi riconosciuto? così nel caso procediamo ad indicizzare quello

saluti

**Comment by cdezorzi** [comment]
Buonasera in allegato il documento firmato [20240415_LAB_STG_MNTMRA03M71C615V_signed.pdf](https://github.com/user-attachments/files/17754243/20240415_LAB_STG_MNTMRA03M71C615V_signed.pdf)
Grazie

**Comment by ppalmerini** [comment]
Buonasera,
abbiamo riprovato con il documento che avete messo a disposizione ma riceviamo ancora errore:

request body:
```
{"assettoOrganizzativo": "AD_PSC130", "dataInizioPrestazione": "20240927000000", "healthDataFormat": "CDA", "identificativoDoc": "2.16.840.1.113883.2.9.2.50.4.4^20241115172013", "identificativoRep": "2.16.840.1.113883.2.9.2.50.4.5.3", "identificativoSottomissione": "2.16.840.1.113883.2.9.2.50.4.3.20241115172056", "mode": "ATTACHMENT", "priorita": true, "tipoAttivitaClinica": "OBS", "tipoDocumentoLivAlto": "SUM", "tipologiaStruttura": "Territorio" }
``` 

repsonse:
```
{
    "traceID": "ca1f374983b758b7",
    "spanID": "ca1f374983b758b7",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.7539dfefdf^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
``` 

e status:
```
{
            "eventType": "VALIDATION_FOR_PUBLICATION",
            "eventDate": "2024-11-15T17:20:49.852+01:00",
            "eventStatus": "SUCCESS",
            "subject": "PROVAX00X00X000Y^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "050",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.7539dfefdf^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "ca1f374983b758b7",
            "issuer": "integrity:S1#050#REGIONEVENETOTEST",
            "expiringDate": "2025-11-15T17:20:49.959+01:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-11-15T17:20:50.053+01:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.50.4.4^20241115172013",
            "subject": "PROVAX00X00X000Y^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "OBS",
            "organizzazione": "050",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.7539dfefdf^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "ca1f374983b758b7",
            "issuer": "integrity:S1#050#REGIONEVENETOTEST",
            "expiringDate": "2025-11-15T17:20:50.150+01:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-15T17:20:50.799+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R166CODE CONTEXT:Wrong value of referenceIdList",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.7539dfefdf^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-15T17:20:50.807+01:00"
        }
``` 

Attendiamo vostro riscontro, grazie

**Comment by ppalmerini** [comment]
Buonasera, riprovando con la stessa casistica e con il documento che ci avete fornito otteniamo ancora un errore:

request body:
```
{
    "assettoOrganizzativo": "AD_PSC100",
    "dataInizioPrestazione": "20240927000000",
    "healthDataFormat": "CDA",
    "identificativoDoc": "2.16.840.1.113883.2.9.2.50.4.4^20241115175823",
    "identificativoRep": "2.16.840.1.113883.2.9.2.50.4.5.3",
    "identificativoSottomissione": "2.16.840.1.113883.2.9.2.50.4.3.20241115175856",
    "mode": "ATTACHMENT",
    "priorita": true,
    "tipoAttivitaClinica": "ERP",
    "tipoDocumentoLivAlto": "REF",
    "tipologiaStruttura": "Ospedale"
}
```

response:
```
{
    "traceID": "239864aee30f04c5",
    "spanID": "239864aee30f04c5",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.7655eaae1b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```

lo status
```
{
            "eventType": "VALIDATION_FOR_PUBLICATION",
            "eventDate": "2024-11-15T17:58:17.571+01:00",
            "eventStatus": "SUCCESS",
            "subject": "PROVAX00X00X000Y^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "050",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.7655eaae1b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "239864aee30f04c5",
            "issuer": "integrity:S1#050#REGIONEVENETOTEST",
            "expiringDate": "2025-11-15T17:58:17.619+01:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-11-15T17:58:17.797+01:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.50.4.4^20241115175823",
            "subject": "PROVAX00X00X000Y^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "ERP",
            "organizzazione": "050",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.7655eaae1b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "239864aee30f04c5",
            "issuer": "integrity:S1#050#REGIONEVENETOTEST",
            "expiringDate": "2025-11-15T17:58:17.889+01:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-15T17:58:18.527+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R166CODE CONTEXT:Wrong value of referenceIdList",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.7655eaae1b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-15T17:58:18.593+01:00"
        }
```   

Chiediamo vostro supporto, grazie

**Comment by claudiodemarzo** [comment]
Salve, guardando il messaggio di errore inoltrato da voi, noto che l'errore riscontrato è R166. Stando alla documentazione ufficiale di AGID per R166 si riscontra il seguente errore: 

> Questo errore è generato nel caso in cui nel messaggio SOAP di richesta l’elemento referendIdList non è valido. Quest’errore può essere generato dal sistema regionale di FSE.

Si prega quindi di rivedere il messaggio e di effettuare un'altro tentativo.

**Comment by IsabellaSgro** [comment]
Buongiorno,
l'NRE del referenceIdList viene inserito dal gateway @pFonziSogei , ma nel documento fornito da Regione Toscana, all'interno del CDA, nell'inFulfillmentOf non è presente un codice NRE ma un placeholder "[NRE]" e presumiamo sia per questo che il documento non passa il controllo sul referenceIdList.
Chiediamo di avere quindi un documento valido per il paziente toscano MNTMRA03M71C615V al fine di riuscire ad effettuare il test @claudiodemarzo @cdezorzi @OmarLorenzini , grazie

**Comment by claudiodemarzo** [comment]
Salve, potete effettuare una prova con il documento mandato dal collega @cdezorzi nella issue #1288

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Grazie
