### ISSUE TITLE
Delete RDA=RDE

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#1279]
Segnaliamo che, effettuando una richiesta di delete attraverso una ITI-62 nella casistica RDA=RDE per un documento inesistente, riceviamo dal Gateway la seguente risposta:

`
{"traceID":"6736170defccbc50dad3dfded4826348","spanID":"3f526a40eaeb1170","warning":"Attenzione, transazione presa in carico. Nuovo tentativo in corso","workflowInstanceId":"5349b1b67efe0b953749573c0ff47afba54a76c2f1cd573c6e13d962fdc6cb82.5945b33954^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}
`
Abbiamo inoltre osservato che, prima di ricevere una risposta dal Gateway, sui nostri servizi arriva una richiesta ITI-18, alla quale rispondiamo con il seguente messaggio:

`<ns6:AdhocQueryResponse xmlns:ns10="http://docs.oasis-open.org/wsn/t-1" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns4="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns5="urn:ihe:iti:xds-b:2007" xmlns:ns6="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns7="http://www.w3.org/2005/08/addressing" xmlns:ns8="http://docs.oasis-open.org/wsn/b-2" xmlns:ns9="http://docs.oasis-open.org/wsrf/bf-2" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Success" totalResultCount="0"><ns2:RegistryObjectList/></ns6:AdhocQueryResponse>
`
Nonostante ciò, riceviamo successivamente un’ulteriore richiesta ITI-62 con una ObjectRefList vuota, alla quale rispondiamo con un errore D4, specificando che la ObjectRefList è vuota.

E' normale che anche in casi di delete verso documenti inesistenti la risposta sia in success e si riscontri l'errore solo a seguito della verifica esisto stato transazione? 
E' normale che dopo aver subito ricevuto un nostro KO,  il gateway dia una risposta con flusso asincrono invece che sincrono?

**Comment by LucaRogledi** [comment]
Ringraziamo per la segnalazione e procediamo con le verifiche.
Come descritto da framework dataset in caso di lista vuota, nella recupero riferimenti, è atteso un messaggio di warning `QND1`.
Grazie

**Comment by LucaRogledi** [comment]
Buonasera @FSESardegna ,
è stato rilasciato un aggiornamento.
Le chiediamo gentilmente di riprovare e darci un feedback.
Grazie.

**Comment by vigliottim** [comment]
Grazie per il gentile riscontro.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
