### ISSUE TITLE
Errore 404 "Operation undefined in the API specification" chiamata di sostituzione documento

### ISSUE THREAD

**Issue by alessiomaggiori** [ministero-salute/it-fse-support#128]
Buongiorno, 

stiamo effettuando i test di sostituzione documento ed otteniamo il seguente errore:

{"type":"https://govway.org/handling-errors/404/UndefinedOperation.html","title":"UndefinedOperation","status":404,"detail":"Operation undefined in the API specification","govway_id":"a4d92e7c-b834-11ed-a9a6-005056ae7395"}

L'url chiamata è la seguente:
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/44cdd9cf-5077-475d-a985-e556ca326cd9

Allego gli header, la requestBody e file pdf con cda attached.

Potete indicarci la causa dell'errore?
Grazie
Saluti

[requestBody.txt](https://github.com/ministero-salute/it-fse-support/files/10862332/requestBody.txt)
[REF3028828593-1.pdf](https://github.com/ministero-salute/it-fse-support/files/10862333/REF3028828593-1.pdf)
[header.txt](https://github.com/ministero-salute/it-fse-support/files/10862334/header.txt)

**Comment by masciamariotti** [comment]
Buongiorno Alessio,
da una prima analisi sembrerebbe che stia chiamando il servizio di sostituzione documento in POST, mentre il method corretto è PUT, come definito in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#6-servizio-di-sostituzione-documento).
Potrebbe verificare?

**Comment by alessiomaggiori** [comment]
Sì è esatto. Con la PUT funziona correttamente.
Segnalo che la chiamata PUT restituisce errore se la requestBody contiene il parametro "priorita", che da specifiche è previsto anche se non obbligatorio.
Grazie per l'aiuto
