### ISSUE TITLE
Crash program RDA Liguria RDE Sicilia, sostituzione documento

### ISSUE THREAD

**Issue by izamberlan** [ministero-salute/it-fse-support#1281]
Abbiamo notato nella segnalazione #1280 che c'è un errore nel caso di sostituzione con RDA Liguria e RDE Sicilia. Apriamo questa issue per non portare off-topic la precedente.

Nel caso del documento per la transazione in oggetto, la situazione non è molto lineare, visto che il documento è stato pubblicato più volte.

Chiediamo a Regione Sicilia di procedere con un caso pulito:

creazione di un documento con identificativo uniqueId non utilizzato
sostituzione del documento con un documento con identificativo uniqueId diverso dal documento da sostituire, come da specifica IHE.

grazie

**Comment by vigliottim** [comment]
@bamoruso-git

Buongiorno,
chiediamo gentilmente alla regione Sicilia di fornire supporto.
Grazie.

**Comment by vigliottim** [comment]
Grazie per il gentile riscontro.
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per altre richieste di supporto.
