### ISSUE TITLE
Problemi Validazione CDA2 VPS (possibile refuso nello Schematron)

### ISSUE THREAD

**Issue by PRAFFO72** [ministero-salute/it-fse-support#129]
Salve, abbiamo riscontrato problemi di validazione nella sezione Interventi Prestazioni Consulenze e Richieste, sottosezione entry/act/statusCode .
Secondo la [documentazione](http://www.hl7italia.it/sites/default/files/Hl7/SuperUser/docs/pubblicati/IG-CDA2-VPS/1.1.1/HL7IT-IG_CDA2_VPS-v1.1.1-S.pdf) a pag.131, i valori possibili per "code" sono 'completed' e 'aborted', ma il secondo genera questo errore:

ERRORE-b172: Sezione Interventi Prestazioni Consulenze e Richieste: l'elemento entry/act DEVE contenere un elemento statusCode valorizzato con l'attributo @code='completed' o @code='aborted'.

Ciò potrebbe essere dovuto a un refuso nello Schematron VPS, alla riga [1002](https://github.com/ministero-salute/it-fse-support/blob/main/validazione/schematron/schematron_VPS.sch#L1002): nella seconda parte del test viene interrogata la sezione "observation" (non presente in questo contesto) invece della sezione "act".

**Comment by IStacchiotti** [comment]
Grazie della segnalazione. Prendiamo in carico la modifica, causa refuso, da effettuare sul controllo lato schematron.

**Comment by IStacchiotti** [comment]
Buon pomeriggio, come da comunicazione su Slack, è stata aggiornata la documentazione. Per questo motivo la invitiamo a riprovare. Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
