### ISSUE TITLE
Eliminazione documento in errore - RDA (Puglia) <> RDE (Veneto)

### ISSUE THREAD

**Issue by abovo-13** [ministero-salute/it-fse-support#1290]
cf: FSEPGL01E41A145J 
timestamp: 2024-11-15 15:48:51.268 
traceid: f3c11e4fdc64172e wid: e19303c9cac1553a10e6405a334e2e5bc384e2bdc8fd9eaf5211e1663a64639b.be9abe4fad^^^^urn:ihe:iti:xdw:2013:workflowInstanceId | 
docid: 2.16.840.1.113883.2.9.2.50.4.4^20241115154323

otteniamo un errore di questo tipo

`{
            "eventType": "DESERIALIZE",
            "eventDate": "2024-11-15T15:48:51.179+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "{\"idDoc\":\"2.16.840.1.113883.2.9.2.50.4.4^20241115154323\",\"uuid\":[\"Document1\"],\"sub\":\"GRLMSM60R31F770Y^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO\",\"iss\":\"integrity:S1#050#REGIONEVENETOTEST\",\"subject_organization\":\"Regione Veneto\",\"subject_organization_id\":\"050\",\"locality\":\"ULSS 2 Marca Trevigiana^^^^^&2.16.840.1.113883.2.9.4.1.3&ISO^^^^050502\",\"subject_role\":\"APR\",\"person_id\":\"FSEPGL01E41A145J^^^&2.16.840.1.113883.2.9.4.3.2&ISO\",\"purpose_of_use\":\"UPDATE\",\"action_id\":\"DELETE\",\"resource_hl7_type\":\"\",\"patient_consent\":true,\"documentType\":\"UNKNOWN_DOCUMENT_TYPE\",\"subject_application_id\":\"ADL\",\"subject_application_vendor\":\"ARIA\",\"subject_application_version\":\"2.99.2\",\"workflow_instance_id\":\"e19303c9cac1553a10e6405a334e2e5bc384e2bdc8fd9eaf5211e1663a64639b.be9abe4fad^^^^urn:ihe:iti:xdw:2013:workflowInstanceId\",\"administrative_request\":[],\"author_institution\":\"UNKNOWN_AUTHOR_INSTITUTION\"}",
            "workflowInstanceId": "e19303c9cac1553a10e6405a334e2e5bc384e2bdc8fd9eaf5211e1663a64639b.be9abe4fad^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-15T15:48:51.193+01:00"
        }`

**Comment by mgirardello** [comment]
@vigliottim avete novità?

**Comment by vigliottim** [comment]
Buon pomeriggio @linnova,
chiediamo gentilmente alla regione Puglia, RDA di riferimento, di fornire supporto.
Grazie.

**Comment by lninnova** [comment]
Buon pomeriggio, la cancellazione in oggetto risulta effettuata su un documento precedentemente sostituito. 
Poiché sulla sostituzione abbiamo in corso la correzione di un bug noto ( vedi #1123 ), fallisce anche la successiva cancellazione.
Non dovreste riscontrare problemi in caso di cancellazione di un nuovo documento.

**Comment by ppalmerini** [comment]
Buongiorno,
abbiamo riprovato utilizzando un nuovo documento correttamente pubblicato:
```
{
            "eventType": "PUBLICATION",
            "eventDate": "2024-11-20T10:13:29.443+01:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.50.4.4^20241120100923",
            "subject": "GRLMSM60R31F770Y^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "OBS",
            "organizzazione": "050",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.2.12345.4.4.2.01716a7f8f417d5cb283c3517e2bb0c680734f042eacf7cebc2448e2d21f5820.e8d071daaa^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "2bea02cfc56357f3",
            "issuer": "integrity:S1#050#REGIONEVENETOTEST",
            "expiringDate": "2025-11-20T10:13:29.450+01:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-20T10:13:36.410+01:00",
            "eventStatus": "SUCCESS",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.2.12345.4.4.2.01716a7f8f417d5cb283c3517e2bb0c680734f042eacf7cebc2448e2d21f5820.e8d071daaa^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-20T10:13:36.480+01:00"
        }
``` 
tentando la cancellazione verso https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.50.4.4%5E20241120100923
otteniamo un errore non standard:
```
{
    "status": 500
}
``` 

Vi chiediamo delucidazioni in merito, grazie

**Comment by lninnova** [comment]
Buongiorno,
lato Puglia ritroviamo la richiesta di recupero riferimento documento, alla quale abbiamo risposto correttamente.
Però non ritroviamo la successiva richiesta di Delete.

**Comment by LucaRogledi** [comment]
Buonasera @abovo-13 @ppalmerini  potreste gentilmente riprovare le chiamate andate in errore e darci un feedback? 
Grazie

**Comment by ppalmerini** [comment]
Buongiorno @LucaRogledi, abbiamo riprovato una cancellazione su un nuovo documento e abbiamo ottenuto un success.
Riporto per completezza lo status e si può chiudere l'issue, grazie.
```
{
            "eventType": "RIFERIMENTI_INI",
            "eventDate": "2024-11-21T11:23:19.716+01:00",
            "eventStatus": "SUCCESS",
            "message": "Riferimenti trovati: [urn:uuid:270a000e-3dfd-4bf3-8cd9-c1f23e95979d]",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.50.4.4^20241121112123",
            "subject": "GRLMSM60R31F770Y^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "050",
            "workflowInstanceId": "a9c7773dedba5189b2de25a24b81d1f22ff6245d87a39a30bf68a40f4e8978b1.d3e43de3f4^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "2fa25484dc74a4cc",
            "issuer": "integrity:S1#050#REGIONEVENETOTEST",
            "expiringDate": "2025-11-21T11:23:19.726+01:00"
        },
        {
            "eventType": "INI_DELETE",
            "eventDate": "2024-11-21T11:23:37.999+01:00",
            "eventStatus": "SUCCESS",
            "message": "Delete effettuata su ini",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.50.4.4^20241121112123",
            "subject": "GRLMSM60R31F770Y^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "050",
            "workflowInstanceId": "a9c7773dedba5189b2de25a24b81d1f22ff6245d87a39a30bf68a40f4e8978b1.d3e43de3f4^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "2fa25484dc74a4cc",
            "issuer": "integrity:S1#050#REGIONEVENETOTEST",
            "expiringDate": "2025-11-21T11:23:38.008+01:00"
        }
```

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Grazie
