### ISSUE TITLE
Crash program - Validate and replace in errore - RDA (Trento) <> RDE (Veneto)

### ISSUE THREAD

**Issue by ppalmerini** [ministero-salute/it-fse-support#1292]
Buonasera, abbiamo provato ad inviare una validate and replace di un documento correttamente validato e pubblicato usando questo endpoint: `https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validate-and-replace/2.16.840.1.113883.2.9.2.50.4.4%5E20241115160934`
otteniamo tuttavia questo errore in risposta:

```
{
    "traceID": "7dfd66fdce311722",
    "spanID": "7a6dbdaa73d10ca8",
    "type": "/errors",
    "title": "Generic",
    "detail": "",
    "instance": "error/generic"
}
``` 
indagando sullo status inserendo il traceID si vede che la validazione è in success ma non si trova altro:

```
{
            "eventType": "VALIDATION_FOR_REPLACE",
            "eventDate": "2024-11-15T16:18:26.599+01:00",
            "eventStatus": "SUCCESS",
            "subject": "GRLMSM60R31F770Y^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "050",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.50.2.12345.4.4.2.b67ff794920507545eef3d33509ba75c748fa3601b9f84f82e6974ee4ff7667b.77c7a9e4d6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "7dfd66fdce311722",
            "issuer": "integrity:S1#050#REGIONEVENETOTEST",
            "expiringDate": "2025-11-15T16:18:26.655+01:00"
        }
``` 

Chiediamo vostro supporto, grazie

**Comment by vigliottim** [comment]
@apsstn @mikeben89

Chiediamo gentilmente alla provincia autonoma di Trento di fornire supporto.
Grazie.

**Comment by IsabellaSgro** [comment]
Buongiorno @vigliottim ci sono novità? è possibile risollecitare? grazie

**Comment by vigliottim** [comment]
> @apsstn @mikeben89 @nicola-ferrari-threadsolutions
> 
> Chiediamo gentilmente alla provincia autonoma di Trento di fornire supporto. Grazie.

@apsstn @mikeben89 @nicola-ferrari-threadsolutions

Buon pomeriggio,
sollecito nuovamente la regione Veneto a fornire il supporto richiesto.
Grazie.

**Comment by IsabellaSgro** [comment]
Buongiorno @vigliottim , chiediamo a PA Trento di fornire supporto. Non risultano richieste in carico a Regione Veneto

**Comment by nicola-ferrari-threadsolutions** [comment]
Buonasera @IsabellaSgro 
Abbiamo avuto dei problemi in fase di storicizzazione. 
Potete gentilmente procedere con una nuova pubblicazione ed in seguito gli altri UC?

@apsstn

**Comment by mikeben89** [comment]
Buongiorno,
abbiamo provato di nuovo una validate and replace su un nuovo documento, ma il gateway risponde con errore:

{
    "status": 500
}

il documento padre ha document uniqueid 2.16.840.1.113883.2.9.2.50.4.4^20241120122136
il documento sostitutivo ha document uniqueid 2.16.840.1.113883.2.9.2.50.4.4^20241120122636
il tentativo di validate and replace è stato effettuato oggi alle 11:30:14.

Potete darci supporto? 
Grazie.

**Comment by LucaRogledi** [comment]
Buonasera @mikeben89 @ppalmerini potreste gentilmente riprovare le chiamate andate in errore e darci un feedback? 
Grazie

**Comment by mikeben89** [comment]
Buongiorno @LucaRogledi 
abbiamo riprovato la validate and replace con successo.

Grazie per il supporto.

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Grazie
