### ISSUE TITLE
Crash program - Cancellazione in errore - RDA (Trento) <> RDE (Veneto

### ISSUE THREAD

**Issue by ppalmerini** [ministero-salute/it-fse-support#1293]
Buonasera,
provando una cancellazione di un documento precedentemente validato e pubblicato con successo, inviando a questo endpoint:
`https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.50.4.4%5E20241115160934`
otteniamo un errore:

```
{
    "traceID": "d7a47af55ee230c8",
    "spanID": "77232088da2178bc",
    "type": "/errors",
    "title": "Generic",
    "detail": "",
    "instance": "error/generic"
}
``` 
indagando sullo status per traceID otteniamo come risultato:

```
{
    "traceID": "360aeacd657ec752",
    "spanID": "360aeacd657ec752",
    "type": "/err/resource",
    "title": "Resource error",
    "detail": "Record non trovato",
    "status": 404,
    "instance": "/not-found"
}
``` 
Chiediamo vostro supporto, grazie

**Comment by nicola-ferrari-threadsolutions** [comment]
Ciao @vigliottim 
Ci sono problemi in fase di pubblicazione documento sulle quali stiamo lavorando. 

Non appena sistemato comunichiamo.

Grazie

@apsstn

**Comment by nicola-ferrari-threadsolutions** [comment]
Buonasera. 
Potete gentilmente procedere con una nuova pubblicazione ed in seguito gli altri UC?

Grazie 

cc @apsstn

**Comment by nicola-ferrari-threadsolutions** [comment]
@vigliottim 

Potete gentilmente verificare che chiamata è stata effettuata in seguito alla richiesta di cancellazione datta da @mikeben89 ? 

Perchè mi sembra non esser arrivata alcuna richiesta (quindi non so se sia fallita lato GTW).

Grazie

**Comment by mikeben89** [comment]
Buongiorno,
abbiamo riprovato, stavolta ottentiamo un workfllow instance id:

Tuttavia la get-status per workfllow instance id mostra un corretto recupero dei riferimenti ma una "Transazione presa in carico" per INI_DELETE e un BLOCKING_ERROR per DESERIALIZE

{
            "eventType": "RIFERIMENTI_INI",
            "eventDate": "2024-11-21T09:40:45.327+01:00",
            "eventStatus": "SUCCESS",
            "message": "Riferimenti trovati: [urn:uuid:6b29758c-9183-481a-84c2-b3e96b5c748e]",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.50.4.4^20241120112736",
            "subject": "GRLMSM60R31F770Y^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "050",
            "workflowInstanceId": "66233d12fe3f51f94860d45f6533f434bcb9eb092ad7d258c3eca04407cec82d.31cb2ea267^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "9521829e96baa1d0",
            "issuer": "integrity:S1#050#REGIONEVENETOTEST",
            "expiringDate": "2025-11-21T09:40:45.338+01:00"
        },
        {
            "eventType": "INI_DELETE",
            "eventDate": "2024-11-21T09:40:57.001+01:00",
            "eventStatus": "ASYNC_RETRY",
            "message": "Transazione presa in carico",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.50.4.4^20241120112736",
            "subject": "GRLMSM60R31F770Y^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "050",
            "workflowInstanceId": "66233d12fe3f51f94860d45f6533f434bcb9eb092ad7d258c3eca04407cec82d.31cb2ea267^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "9521829e96baa1d0",
            "issuer": "integrity:S1#050#REGIONEVENETOTEST",
            "expiringDate": "2025-11-21T09:40:57.011+01:00"
        },
        {
            "eventType": "DESERIALIZE",
            "eventDate": "2024-11-21T09:40:57.006+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "{\"idDoc\":\"2.16.840.1.113883.2.9.2.50.4.4^20241120112736\",\"uuid\":[\"urn:uuid:6b29758c-9183-481a-84c2-b3e96b5c748e\"],\"sub\":\"GRLMSM60R31F770Y^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO\",\"iss\":\"integrity:S1#050#REGIONEVENETOTEST\",\"subject_organization\":\"Regione Veneto\",\"subject_organization_id\":\"050\",\"locality\":\"ULSS 2 Marca Trevigiana^^^^^&2.16.840.1.113883.2.9.4.1.3&ISO^^^^050502\",\"subject_role\":\"APR\",\"person_id\":\"TRCTST70A01L378S^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO\",\"purpose_of_use\":\"UPDATE\",\"action_id\":\"DELETE\",\"resource_hl7_type\":null,\"patient_consent\":true,\"documentType\":\"UNKNOWN_DOCUMENT_TYPE\",\"subject_application_id\":\"ADL\",\"subject_application_vendor\":\"ARIA\",\"subject_application_version\":\"2.99.2\",\"workflow_instance_id\":\"66233d12fe3f51f94860d45f6533f434bcb9eb092ad7d258c3eca04407cec82d.31cb2ea267^^^^urn:ihe:iti:xdw:2013:workflowInstanceId\",\"administrative_request\":[],\"author_institution\":\"UNKNOWN_AUTHOR_INSTITUTION\"}",
            "workflowInstanceId": "66233d12fe3f51f94860d45f6533f434bcb9eb092ad7d258c3eca04407cec82d.31cb2ea267^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-21T09:40:57.057+01:00"
        }
        
  E' possibile verificare?
  Grazie

**Comment by LucaRogledi** [comment]
@nicola-ferrari-threadsolutions @apsstn 

Buongiorno, 
Chiediamo gentilmente di verificare in quanto RDA interessata.
Restiamo a disposizione per ulteriore supporto, grazie.

**Comment by nicola-ferrari-threadsolutions** [comment]
Ciao @LucaRogledi @mikeben89 

Stiamo verificando il problema. 

Appena sistemato vi facciamo sapere (verosimilmente bisognerà fare una nuova registrazione e una nuova cancellazione).

Vi aggiorniamo

Graize
@apsstn

**Comment by nicola-ferrari-threadsolutions** [comment]
Ciao @LucaRogledi @mikeben89 

Potete gentilmente effettuare una nuova pubblicazione e successivamente una cancellazione?
Grazie

@apsstn

**Comment by mikeben89** [comment]
Buongiorno @nicola-ferrari-threadsolutions 
abbiamo pubblicato un nuovo doc e correttamente cancellato. Questo il doc id: 2.16.840.1.113883.2.9.2.50.4.4^20241121142836

Una get status conferma la corretta cancellazione: 
`{
            "eventType": "RIFERIMENTI_INI",
            "eventDate": "2024-11-21T14:40:03.173+01:00",
            "eventStatus": "SUCCESS",
            "message": "Riferimenti trovati: [urn:uuid:7ee9780b-e1ab-46ab-83c0-f09f084e911b]",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.50.4.4^20241121142836",
            "subject": "GRLMSM60R31F770Y^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "050",
            "workflowInstanceId": "912f60cb23e65dd37bf160d4fac5807d8c5c1fa7cd0dac35b3fb3df5fd32f31f.c3648e221b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "c02d1f196d5098b6",
            "issuer": "integrity:S1#050#REGIONEVENETOTEST",
            "expiringDate": "2025-11-21T14:40:03.185+01:00"
        },
        {
            "eventType": "INI_DELETE",
            "eventDate": "2024-11-21T14:40:05.757+01:00",
            "eventStatus": "SUCCESS",
            "message": "Delete effettuata su ini",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.50.4.4^20241121142836",
            "subject": "GRLMSM60R31F770Y^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "050",
            "workflowInstanceId": "912f60cb23e65dd37bf160d4fac5807d8c5c1fa7cd0dac35b3fb3df5fd32f31f.c3648e221b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "c02d1f196d5098b6",
            "issuer": "integrity:S1#050#REGIONEVENETOTEST",
            "expiringDate": "2025-11-21T14:40:05.766+01:00"
        }`


Si può chiudere l'issue. Grazie a tutti per il supporto.

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Grazie
