### ISSUE TITLE
Validazione xml CDA

### ISSUE THREAD

**Issue by GranataCrescenzo** [ministero-salute/it-fse-support#1295]
Buongiorno, 
ho creato i miei files xml, come posso validarli ? 
Esiste un repository con i file xsd per la validazione ?

**Comment by vigliottim** [comment]
Buongiorno,
di seguito le riportiamo alcuni link che possono esserle utili:

- _Lista degli xsd:_ https://github.com/ministero-salute/it-fse-catalogs/tree/main/schema/POCD_MT000040UV02
- _Documentazione con le istruzioni per chiamare gli endpoint dei servizi disponibili:_ https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway

Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by GranataCrescenzo** [comment]
buongiorno, 
allegando al file pdf il file xml (https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/RAD.xml) 
Ottengo il seguente errore: 
{
    "traceID": "b7d80f62bd9868cd",
    "spanID": "b7d80f62bd9868cd",
    "type": "/msg/cda-element",
    "title": "Errore in fase di estrazione del CDA.",
    "detail": "Error while extracting CDA from PDF document",
    "status": 400,
    "instance": "/cda-extraction",
    "workflowInstanceId": "UNKNOWN_WORKFLOW_ID"
}

Anche se riesco ad estralo tranquillamente dal pdf.

**Comment by vigliottim** [comment]
Buongiorno,
le facciamo presente che il nome del file CDA2 allegato al pdf deve essere cda.xml, come riportato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway):

![image](https://github.com/user-attachments/assets/e11e13cd-5198-4452-8e95-472c1a9b7c75)

Inoltre, le chiediamo se sta usando il tool [pdf-generator](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/pdf-generator) per iniettare il CDA2 all'interno del pdf.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso sia necessario ulteriore supporto.
Grazie.
