### ISSUE TITLE
Servizio notifica comunicazione metadati

### ISSUE THREAD

**Issue by angeloceloni** [ministero-salute/it-fse-support#1299]
Buonasera
il 4 novembre abbiamo comunicato, tramite mail inviata a gestionets@sogei.it, l'endpoint di test per il servizio di notifica comunicazione metadati ma ad oggi ancora non riceviamo le notifiche.
Potete verificare?

**Comment by g-maugeri-sogei** [comment]
Buonasera,
potete riportare qui l'endpoint?

**Comment by g-maugeri-sogei** [comment]
Buonasera,
l'endpoint e' stato aggiornato.

**Comment by angeloceloni** [comment]
Buongiorno
abbiamo ricevuto la prima notifica comunicazione metadati.

Chiudo la issue, grazie per la collaborazione
