### ISSUE TITLE
SCHEMATRON  Referto Radiologia- elemento Patient Errore 10

### ISSUE THREAD

**Issue by giuseppe-fasulo** [ministero-salute/it-fse-support#13]
Si segnala quanto segue
La linea guida HL7 Italia indica come obbligatorio l'item patient (pag 35 )
CONF - RAD - 24 Il documento DEVE contenere l’elemento <recordTarget>/<patientRole>/<patient>.

L'asserzione assert test="**count($patient)=0** or count($patient/hl7:name)=1 in corrispondenza dell'ERRORE 10 invece ammmette la possibilità che non ci sia l'elemento; il controllo di obbligatorietà del name quindi mi pare sia eseguito solo se presente il patient.

In tal caso non è conforme. D'altra parte faccio presente che nello schematron della LDO il controllo 10 verifica esplicitamente la presenza dell'item patient.  I controlli sull'header dovrebbero essere più o meno standard

**Comment by LeonardoAlcaro** [comment]
Ciao Giuseppe,
grazie della segnalazione, il controllo nel RAD penso sia un refuso in quanto come evidenziato correttamente da te sugli altri schematron il controllo sull'item patient è esplicitato.

Grazie ancora
