### ISSUE TITLE
schematronFSE_LAB e code="86467-8"

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#130]
Buongiorno,
eseguendo dei test sul gateway lite in locale con un Referto di Laboratorio che ha un elemento
```
<component><section>
  <code code="86467-8" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Report comment Narrative"/>
```

si verifica un errore
ERRORE-b1| L'elemento code della section DEVE essere valorizzato con uno dei seguenti codici LOINC individuati:...
			
In effetti guardando il file schematronFSE_LAB.sch pubblicato, il codice 86467-8 non compare tra quelli previsti.

Non è quindi possibile avere nei referti delle section "Report comment Narrative"?
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, grazie della segnalazione. L'elemento da lei evidenziato riguarda il code della section
di specialità. Viene generato l'errrore b1 poiché quel codice inserito non è presente nelle codifiche internazionali ammesse per valorizzare il code della section di specialità.
I codici ammessi per tale sezione sono presenti nella guida implementativa del Referto di Medicina di Laboratorio in APPENDICE 2 a pagina 86-87.

**Comment by ponsilva** [comment]
Grazie, 
rivedo i casi di test in modo da utilizzare la corretta valorizzazione di code.
