### ISSUE TITLE
servizio notifica operazione su metadati

### ISSUE THREAD

**Issue by izamberlan** [ministero-salute/it-fse-support#1300]
buonasera,
in data 24/10 abbiamo comunicato alla casella gestioneTS (per errore anche alla casella fse_support) l'endpoint per la notifica operazione su metadati, ma non abbiamo avuto notizie e le notifiche non arrivano. Potete verificare se c'è qualche problema?

grazie

**Comment by g-maugeri-sogei** [comment]
Buonasera,
potete aggiungere l'endpoint anche qui?

**Comment by izamberlan** [comment]
Certo
https://fse-ini-test.liguriadigitale.it/services/fse2_ini_NotifyUpdateMetadataProxy

modalità di autenticazione e certificati comuni agli altri servizi INI in ambiente di test Liguria

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
abbiamo aggiornato l'endpoint.

**Comment by izamberlan** [comment]
grazie, verifichiamo il funzionamento nei prossimi test

**Comment by izamberlan** [comment]
le notifiche arrivano, se riscontreremo problemi di altro tipo (es. notifiche non pervenute a fronte di operazioni in success) apriremo un'altra issue. Grazie.
