### ISSUE TITLE
piano di adeguamento

### ISSUE THREAD

**Issue by acolzi** [ministero-salute/it-fse-support#1301]
Buongiorno,,
ho ricevuto la mail per l'adeguamento al piano di adeguamento a fse2.0. Mi vengono indicate delle date in cui effettuiamo l'adeguamento, ma avendo passato il test adesso, il flusso dei dati che mando non è già conforme al 2.0?
Inoltre nel campi Azienda sanitaria  suppongo debba mettere Toscana Centro, ma nel presidio, dato che il software verrà utilizzato da strutture private cosa metto?
grazie

**Comment by vigliottim** [comment]
Buongiorno,
la invitiamo a inoltrare la sua richiesta alla seguente e-mail: [FSE-PNRR@innovazione.gov.it](mailto:FSE-PNRR@innovazione.gov.it)
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
