### ISSUE TITLE
Errore del codice esame durante la validazione del CDA

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#1302]
Buongiorno, 
sto provando a validare un CDA RSA inserendo come codice esame una visita, ma ricevo sempre un errore di mancato censimento, sia col codice nazionale che con quello regionale:
**Almeno uno dei seguenti vocaboli non è censito: [CodeSystem: 2.16.840.1.113883.6.1 v2.77, Codes: 89.7]**
Credo che sia dovuto all'OID e non al codice, ma se così fosse non saprei dove reperire i vari OID richiesti nel codeSystem.
Di seguito l'errore completo, potete dirmi se ho individuato correttamente l'errore e come risolverlo? Grazie.
{
  "traceID": "fff05e5d1bb004a7",
  "spanID": "fff05e5d1bb004a7",
  "type": "/msg/vocabulary",
  "title": "Errore vocabolario.",
  "detail": "Almeno uno dei seguenti vocaboli non è censito: [CodeSystem: 2.16.840.1.113883.6.1 v2.77, Codes: 89.7]",
  "status": 400,
  "instance": "/validation/error",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.160.4.4308605000001.cc5fba59f12d47fc90da0db4b43dae44b715a8002bf370343c2a83d2873aa1e1.7c9ddd39e7^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "warning": null
}

**Comment by vigliottim** [comment]
Buonasera,
da una prima verifica effettuata, rispetto al documento CDA2 condiviso, risulta che il l'attributo @code inserito appartiene al dizionario ICD9CM e non LOINC, è necessario quindi inserire all'interno del @codesystem l'OID relativo all'ICD9CM (2.16.840.1.113883.6.103). Se si vuole utilizzare la codifica LOINC è necessario correggere l'attributo @code.

**Comment by infoserviceonline** [comment]
Perfetto, ora va tutto bene, grazie mille. Chiudo.
Saluti.
