### ISSUE TITLE
Regione Liguria - Blocking Error in Cancellazione verso Toscana

### ISSUE THREAD

**Issue by GiuseppeMaiulli** [ministero-salute/it-fse-support#1303]
Buongiorno,

riceviamo il seguente errore in cancellazione del documento 2.16.840.1.113883.2.9.2.70.4.4^RAD.09076724404.1 verso Toscana

{
            "eventType": "RIFERIMENTI_INI",
            "eventDate": "2024-11-19T14:50:38.689+01:00",
            "eventStatus": "SUCCESS",
            "message": "Riferimenti trovati: [Document1]",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.70.4.4^RAD.09076724404.1",
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "070",
            "workflowInstanceId": "36c3d9948d0b51b25a0b7d2a4ed775fcf9863eb30aa268728ac6c003ccb7c3df.0f7a4bb504^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "711489ff966344ca",
            "issuer": "integrity:S1#070#REGIONELIGURIATEST",
            "expiringDate": "2025-11-19T14:50:38.743+01:00"
        },
        {
            "eventType": "INI_DELETE",
            "eventDate": "2024-11-19T14:50:39.528+01:00",
            "eventStatus": "ASYNC_RETRY",
            "message": "Transazione presa in carico",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.70.4.4^RAD.09076724404.1",
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "070",
            "workflowInstanceId": "36c3d9948d0b51b25a0b7d2a4ed775fcf9863eb30aa268728ac6c003ccb7c3df.0f7a4bb504^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "711489ff966344ca",
            "issuer": "integrity:S1#070#REGIONELIGURIATEST",
            "expiringDate": "2025-11-19T14:50:39.538+01:00"
        },
        {
            "eventType": "DESERIALIZE",
            "eventDate": "2024-11-19T14:50:39.538+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "{\"idDoc\":\"2.16.840.1.113883.2.9.2.70.4.4^RAD.09076724404.1\",\"uuid\":[\"Document1\"],\"sub\":\"PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO\",\"iss\":\"integrity:S1#070#REGIONELIGURIATEST\",\"subject_organization\":\"Regione Liguria\",\"subject_organization_id\":\"070\",\"locality\":\"RADIOLOGIA PROVA ASL3^^^^^&2.16.840.1.113883.2.9.4.1.3&ISO^^^^220103010025\",\"subject_role\":\"AAS\",\"person_id\":\"MNTMRA03M71C615V^^^&2.16.840.1.113883.2.9.4.3.2&ISO\",\"purpose_of_use\":\"UPDATE\",\"action_id\":\"DELETE\",\"resource_hl7_type\":\"('68604-8^^2.16.840.1.113883.6.1')\",\"patient_consent\":true,\"documentType\":\"UNKNOWN_DOCUMENT_TYPE\",\"subject_application_id\":\"Middleware070\",\"subject_application_vendor\":\"Regione Liguria\",\"subject_application_version\":\"0.1\",\"workflow_instance_id\":\"36c3d9948d0b51b25a0b7d2a4ed775fcf9863eb30aa268728ac6c003ccb7c3df.0f7a4bb504^^^^urn:ihe:iti:xdw:2013:workflowInstanceId\",\"administrative_request\":[],\"author_institution\":\"UNKNOWN_AUTHOR_INSTITUTION\"}",
            "workflowInstanceId": "36c3d9948d0b51b25a0b7d2a4ed775fcf9863eb30aa268728ac6c003ccb7c3df.0f7a4bb504^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-19T14:50:39.551+01:00"
        }

Potete verificare per cortesia?
Grazie

**Comment by cdezorzi** [comment]
Buonasera,
facendo una ulteriore analisi dei ns log abbiamo visto che l'errore viene generato in fase di ricerca (ITI 18), tuttavia abbiamo riscontrato che altre regioni riescono ad invocare corrttamente tale servizio.
Abbiamo notato alcune differenze , tra una richiesta di ricerca andata a buon fine e una non, negli atributi presenti nell'header: 
Encoding
 campo action e altre differenze
In allegato 2 file , 1) inviato da REGIONEBASILICATATEST che si è conclusa con esito positivo, 2) KO della Vs richiesta.
Attendiamo Vs gentile riscontro.
Grazie


[DocumentRegistry-KO-Liguria.xml.txt](https://github.com/user-attachments/files/17872754/DocumentRegistry-KO-Liguria.xml.txt)
[DocumentRegistry-OK per Liguria.xml.txt](https://github.com/user-attachments/files/17872755/DocumentRegistry-OK.per.Liguria.xml.txt)

**Comment by izamberlan** [comment]
non è chiaro perché esca che si tratta di un'altra action quando nella request c'è
		<wsa:Action>urn:ihe:iti:2007:RegistryStoredQuery</wsa:Action>
il problema sicuramente non è dal nostro lato (a quesl punto lì siamo abbastanzsa fuori gioco).

non capisco neanche il charset, sicuro non lo mettiamo noi, l'encoding della request soap è utf-8 in ambedue i casi.
@vigliottim @LucaRogledi qualche idea?

**Comment by izamberlan** [comment]
Riguardando, il messaggio d'errore è
body should be of type it.toscana.regione.sisorchestrator.fseinterop.artifact.registry.MCCIIN000002UV01, not it.toscana.regione.sisorchestrator.fseinterop.artifact.registry.PRPAIN201304UV02
che si riferisce proprio al diverso schema, ma la mia sensazione è che quelli allegati siano log del vostro sistema, prodotti dopo che un componente ha già "deciso" che la soapAction è urn:hl7-org:v3:PRPA_IN201304UV02 (mentre in realtà la wsa:action della request SOAP è quella di cui al messaggio sopra) e fatto message enrichment (nella request ci sono elementi XML che non sono parte dello standard).

**Comment by cdezorzi** [comment]
Buon pomeriggio, 
abbiamo attivato un log più "parlante" per capire la problematica,
potete fare un nuovo test ?
Grazie

**Comment by Gianpr0** [comment]
Buongiorno,
abbiamo revisionato i log e non troviamo alcuna operazione di delete verso i nostri sistemi. Abbiamo richiesto verifica url nella issue #1339 
Cordiali saluti

**Comment by izamberlan** [comment]
Non funzuionerà mai sino a quando la recupero riferimenti non tornerà un uuid (e non Document1: ovviamente la cancellazione di Document1 non può che fallire).

**Comment by vigliottim** [comment]
> Buongiorno, abbiamo revisionato i log e non troviamo alcuna operazione di delete verso i nostri sistemi. Abbiamo richiesto verifica url nella issue #1339 Cordiali saluti

Buonasera,
come comunicato nella issue #1339, l'url non è stato modificato.
Attendiamo un vostro riscontro.
Grazie.

**Comment by izamberlan** [comment]
Ho una domanda: ma l'evento DESERIALIZE sul quale falliscono tutte queste operazioni è prima o dopo la chiamata di delete verso INI/RDA? Il problema non potrebbe essere che il gateway o INI non può comporre la request di delete perché verifica di usare uno uuid, ma in realtà la recupero riferimenti ritorna un id simbolico (Document1) che evidentemente non è uno uuid?

@vigliottim @LucaRogledi

**Comment by LucaRogledi** [comment]
Buonasera, 
Le confermiamo che l'evento "DESERIALIZE" contenente l'errore bloccante è generato in seguito al tentativo di una chiamata di delete che utilizza un id simbolico invece di uno uuid.
Grazie

**Comment by izamberlan** [comment]
Quindi è normale che Toscana non veda nulla sul suo log, perché il problema è a precedente ed è la response della recupero riferimenti che dovrebbe contenere uno uuid - se ho capito bene.

grazie a voi

**Comment by LucaRogledi** [comment]
Esatto, chiediamo gentilmente una nuova verifica utilizzando uno uuid invece di un id simbolico per la chiamata di delete. Grazie

**Comment by izamberlan** [comment]
Ma noi non possiamo:
- il processo è completamente gestito dal gateway, noi chiamiamo la API di cancellazione, che richiede lo uniqueId. A fronte dello uniqueId è il gateway che fa la ITI-18 ObjectRef sulla recupero riferimenti documento di Toscana, che dovrebbe rispondere con uno uuid, ma risponde invece con un id simbolico
- anche volendo forzare la transazione via INI, non potremmo farlo perché lo uuid è noto al solo registry (Toscana) e se non ce lo restituisce la cancellazione fallisce, non possiamo certo indovinarlo

**Comment by Gianpr0** [comment]
Perfetto, grazie del chiarimento.
Ora è chiaro il motivo per cui noi non visualizziamo alcuna chiamata nei log per l'operazione di delete.
Siamo noi che dobbiamo restituire un uuid e non Document1 nella ITI-18, risolveremo il bug dell'uuid quanto prima.

Cordiali saluti

**Comment by Gianpr0** [comment]
Buongiorno,
abbiamo rilasciato la fix sull'uuid per l'iti-18.
Vi richiediamo di fare un nuovo giro di test dalla create.
Grazie

**Comment by vigliottim** [comment]
Buonasera @GiuseppeMaiulli,
chiediamo cortesemente di effettuare un nuovo test dopo la fix rilasciata dalla regione Toscana.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Potrà essere riaperta nel caso in cui sia necessario ulteriore supporto.
Grazie.
