### ISSUE TITLE
Crash Program - Regione Trento - RDE=RDA - missing mandatory information

### ISSUE THREAD

**Issue by nicola-ferrari-threadsolutions** [ministero-salute/it-fse-support#1304]
Buongiorno. 
Ieri sera abbiamo effettuato un test UC1 con esito positivo 

```
{
  "traceID": "26bde25cc3f40fc2",
  "spanID": "0b4189ada6235c05",
  "transactionData": [
    {
      "eventType": "INI_CREATE_SOAP",
      "eventDate": "2024-11-19T19:02:02.043+0000",
      "message": "SOAP_REQUEST:xxxxx",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.42.4.4.2f0c485bf4f491c84793c5295cbe737e7aae1ad58f13c3af4bc3ae4af3a03446.d4292e3163^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-11-19T19:02:02.180+0000"
    },
    {
      "eventType": "VALIDATION",
      "eventDate": "2024-11-19T19:54:59.204+01:00",
      "eventStatus": "SUCCESS",
      "subject": "PRVMDC70A01H501L^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "organizzazione": "042",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.42.4.4.2f0c485bf4f491c84793c5295cbe737e7aae1ad58f13c3af4bc3ae4af3a03446.d4292e3163^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "ddf8dba06ff4ae3d",
      "issuer": "integrity:S1#042#PATRENTOTEST",
      "expiringDate": "2025-11-19T19:54:59.225+01:00"
    },
    {
      "eventType": "PUBLICATION",
      "eventDate": "2024-11-19T20:02:02.008+01:00",
      "eventStatus": "SUCCESS",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.42.4.4^SIO.REF.2024.9000000001.1",
      "subject": "PRVMDC70A01H501L^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "tipoAttivita": "CON",
      "organizzazione": "042",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.42.4.4.2f0c485bf4f491c84793c5295cbe737e7aae1ad58f13c3af4bc3ae4af3a03446.d4292e3163^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "56fc0cfd655f6bb3",
      "issuer": "integrity:S1#042#PATRENTOTEST",
      "expiringDate": "2025-11-19T20:02:02.059+01:00"
    },
    {
      "eventType": "SEND_TO_INI",
      "eventDate": "2024-11-19T20:02:06.132+01:00",
      "eventStatus": "SUCCESS",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.42.4.4.2f0c485bf4f491c84793c5295cbe737e7aae1ad58f13c3af4bc3ae4af3a03446.d4292e3163^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-11-19T20:02:06.193+01:00"
    }
  ]
}
```

Successivamente abbiamo effettuato un UC3 (aggiornamento metadata) ma abbiamo ricevuto errore

```{"traceID":"fb772b9c6ced7c76","spanID":"2abfd5fba21f1dfe","type":"/errors","title":"Generic","detail":"it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.","instance":"error/generic"}```

Verificando la chiamata inoltrataci sembra mancare l 'attribute documentSigned che da affinity domain sembra essere mandatory. 

![Screenshot 2024-11-20 alle 09 21 50](https://github.com/user-attachments/assets/50c588f0-050b-469a-a669-6084d5ab587d)

Potete gentilmente verificare?

Grazie
cc @apsstn

**Comment by nicola-ferrari-threadsolutions** [comment]
Ciao @LucaRogledi 

Potete gentilmente verificare?

Grazie

@apsstn

**Comment by vigliottim** [comment]
Buon pomeriggio,
il campo _"XDSDocumentEntry.slot - documentSigned"_ viene popolato a partire dalle informazioni ricevute dalla ricerca documenti. 
Nel caso specifico da lei riportato il campo non è presente in response e per tale motivo non è stato popolato.

**Comment by nicola-ferrari-threadsolutions** [comment]
Ciao @vigliottim 

Posso chiedere dove andrebbe ritornato il valore nella ricerca documenti? (un esempio)

Percvhè abbiamo cercato nelle specifiche 2.5 e anche nelle specifiche ITI-18 ma non troviamo nulla.

Grazie

@apsstn

**Comment by nicola-ferrari-threadsolutions** [comment]
@LucaRogledi @vigliottim 

Giusto per conferma.
Le informazioni sul doc firmato vanno tornate solamente per una richiesta LeafClass e non per una ObjectRef, corretto?

cc @apsstn

**Comment by nicola-ferrari-threadsolutions** [comment]
@LucaRogledi 

Chiudo il case in quanto funziona
