### ISSUE TITLE
Error 400 cda-extraction in Validazione

### ISSUE THREAD

**Issue by EbitFSE** [ministero-salute/it-fse-support#131]
Buonasera, otteniamo in fase di validazione un errore 400 "Errore in fase di estrazione del CDA.".
Di seguito il vostro traceID:
{
  "traceID" : "22d3a7b18663b4e0",
  "spanID" : "22d3a7b18663b4e0",
  "type" : "/msg/cda-element",
  "title" : "Errore in fase di estrazione del CDA.",
  "detail" : "Error while extracting CDA from PDF document",
  "status" : 400,
  "instance" : "/cda-extraction",
  "workflowInstanceId" : "UNKNOWN_WORKFLOW_ID"
}

Non riusiamo a capire quale sia la problematica perchè abbiamo testato che:
- Se utilizziamo lo stesso PDF e lo inviamo tramite Postman otteniamo la validazione del file e del CDA iniettato come potete verificare in questo traceID:
{
    "traceID": "73465e8c44658225",
    "spanID": "73465e8c44658225",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.3a83e6b6063b5214b5d4d97ba8c0f18d446bb5d0be63c85b84a00bcb654bdba1.c257d0fefd^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
    "warning": "[W005 | Sezione Esame Eseguito: l'entry/act/code può essere valorizzato secondo i sistemi di codifica\n\t\t\tLOINC @codeSystem='2.16.840.1.113883.6.1'\n\t\t\tICD-9-CM @codeSystem='2.16.840.1.113883.6.103']"
}

- Inoltre la stessa procedura se utilizza il PDF di test fornito nella documentazione ottiene la validazione come potete verificare dal traceID:
{
  "traceID" : "df5cb97cd5725287",
  "spanID" : "df5cb97cd5725287",
  "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.8fe46b71d98546dc779f4a7f4859b056b254bbe56b59baa550333b2c46441c87.b6a0e1b718^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Quindi la struttura della richiesta è corretta altrimenti non avremmo l'esito positivo utilizzando il vostro pdf. Allo stesso tempo se fosse il nostro pdf il problema avremmo errore anche utilizzando Postman. 
Grazie per il vostro auto.

**Comment by IStacchiotti** [comment]
Buonasera, per velocizzare le analisi, potreste allegare cortesemente il pdf? Grazie

**Comment by EbitFSE** [comment]
Buonasera, allego il pdf trasmesso sia con il "traceID" : "22d3a7b18663b4e0" che con il "traceID": "73465e8c44658225".
Grazie

[refertoEstensafirmatoFINALE.pdf](https://github.com/ministero-salute/it-fse-support/files/10883717/refertoEstensafirmatoFINALE.pdf)

**Comment by masciamariotti** [comment]
Buongiorno,
potrebbe verificare che il pdf che sta allegando alla richiesta abbia lo stesso nome di quanto dichiarato nel parametro "filename" nella requestBody? Sembrerebbe infatti che il file che ha allegato in questo ticket abbia un nome diverso da quanto arrivato in request.
Inoltre, potrebbe verificare se effettivamente l' InjectionMode (attachment o resource) del CDA contenuto nel pdf sia la stessa dichiarata nella requestBody?

**Comment by EbitFSE** [comment]
Buonasera, il nome del file non è un problema visto che il file viene inviato in binario. Ad ogni modo abbiamo risolto modificando la libreria che utilizzavamo per la creazione della request HTTP multipart.
Grazie per l'aiuto.
