### ISSUE TITLE
Test id 32 e id 40 accreditamento RSA (Referto Specialistica Ambulatoriale)

### ISSUE THREAD

**Issue by ebneuro** [ministero-salute/it-fse-support#1310]
Buongiorno,

Stiamo procedendo con i test per la fase di accreditamento abbiamo un problema nello svolgere i test id 32 e id 40 che rispettivamente sono i test KO per il token JWT mancante di un dato e con un dato errato.

Dalla documentazione vediamo che il gateway dovrebbe ritornarci un errore 403.
A noi invece arriva un errore 401 e nella risposta non abbiamo il codice TraceId che dobbiamo inserire nella documentazione ( report_checklist ), possiamo indicarvi il gowayid della risposta:

Risposta:
{"type":"https://govway.org/handling-errors/401/TokenRequiredClaimsNotFound.html","title":"TokenRequiredClaimsNotFound","status":401,"detail":"Required token claims not found","govway_id":"025f43fb-a729-11ef-808a-005056ae7395"}

Quindi riceviamo un 401 invece di un 403 e non abbiamo un TraceId in risposta, sarebbe possibile cortesemente richiedere un controllo?

Grazie

**Comment by vigliottim** [comment]
Buongiorno,
dalle analisi svolte sui log della chiamata da lei riportata, è emerso che nel token _FSE-JWT-Signature_ non è stato valorizzato il campo _sub_:

<img width="249" alt="image" src="https://github.com/user-attachments/assets/8e4a7c11-4e73-4774-a97d-d0d314ef788b">

La invitiamo a ripetere i test valorizzando il campo _sub_ opportunamente e attendendosi alle istruzioni riportate nelle descrizioni del TC con _id = 32_ e con _id = 40_: 
- _TC id = 32_: il campo _purpose_of_use_ non deve essere valorizzato nel JWT.
- _TC id = 40_: il campo _action_id_ deve essere valorizzato con la stringa "TEST" (valore non ammesso).
Grazie.

**Comment by ebneuro** [comment]
Grazie provvediamo

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso in cui sia necessario ulteriore supporto.
Grazie.
