### ISSUE TITLE
Crash Program - Anagrafica FVG PRVNSL72B68L101R risulta per INI assistito della P.A. di Bolzano

### ISSUE THREAD

**Issue by ChiaraCeccottiFVG** [ministero-salute/it-fse-support#1312]
Buongiorno,
ci siamo accorti che, sull’ambiente di collaudo, l'anagrafica FVG PRVNSL72B68L101R   INSIEL  PROVA 28/02/1972 F usata sia per il crash program sia per i collaudi delle integrazioni delle strutture private che si stanno svolgendo nella nostra regione, per INI risulta assistita della provincia autonoma di Bolzano (041). Sarebbe possibile riportare il CF ad un assistito FVG in modo che possiamo procedere con le casistiche di test in modo corretto?
Abbiamo inviato una mail in data 18/11 a gestionets@sogei.it ma apro anche una issue non sapendo quale canale fosse preferibile per la segnalazione.
Ringraziamo molto e auguriamo una buona giornata.

**Comment by vigliottim** [comment]
Buongiorno,
la informiamo di aver effettuato la correzione richiesta.
Grazie.
