### ISSUE TITLE
GTW HTTP 500 cancellazione, replace

### ISSUE THREAD

**Issue by rangemasterd** [ministero-salute/it-fse-support#1315]
Buongiorno,

il gateway nazionale sta rispondendo con HTTP 500 alle chiamate di replace di documento e/o cancellazione documento ma solo verso alcune regioni.

La pubblicazione sembra andare correttamente.

Non capiamo se il problema è la richiesta che effettuiamo, ci potete dare supporto?
Di seguto il dettaglio della risposta

```
HTTP/1.1 500  - Internal Server Error
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
cache-control: no-cache, no-store, must-revalidate
content-disposition: inline;filename=f.txt
content-type: application/problem+json
date: Wed, 20 Nov 2024 08:00:39 GMT
expires: 0
govway-message-id: 181a091f-77ec-4e4d-bd1a-1198ec741f52
govway-transaction-id: 7bd55e73-a714-11ef-808a-005056ae7395
pragma: no-cache
server-timing: intid;desc=5b43bae6bd7e7c35
server: GovWay-SOGEI
set-cookie: 894d46ecfc124039ee218b63c12a3329=6d2a4221fc6036c1cddd923b80440c82; path=/; HttpOnly; Secure; SameSite=None
transfer-encoding: chunked
vary: *
via: 1.1 google
x-backside-transport: FAIL FAIL
x-content-type-options: nosniff
x-global-transaction-id: 6026e6bc673d972301a48aef

{
  "status": 500
}
```

**Comment by marlagatta** [comment]
La regione Molise riscontra lo stesso problema, come si evince dalle issue [1175](https://github.com/ministero-salute/it-fse-support/issues/1175), [1108](https://github.com/ministero-salute/it-fse-support/issues/1108)

**Comment by vigliottim** [comment]
Buonasera,
è stato rilasciato un aggiornamento.
Potreste cortesemente riprovare?
Grazie.

**Comment by rangemasterd** [comment]
Buongiorno, abbiamo riprovato ed ora sembra andare correttamente.

Grazie per il supporto

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Grazie
