### ISSUE TITLE
Crash Program - Regione Trento - RDE=RDA - errore UC5 (sostituzione)

### ISSUE THREAD

**Issue by nicola-ferrari-threadsolutions** [ministero-salute/it-fse-support#1316]
Buongiorno, 

abbiamo fatto una chiamata di sostituzione con esito positivo 
```

{
  "traceID": "4f183156c33b6bd7",
  "spanID": "4f183156c33b6bd7",
  "warning": "",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.42.4.4.ca82e244e33627544f31d8d198b95995a33b80abdc60f1b1e004bd0074d6cc65.d0e63cd315^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

```

Facendo però una verifica (get status) ci da un errore. 
```

{
  "traceID": "8abf12f57810335a",
  "spanID": "e63687720d96c6c7",
  "transactionData": [
    {
      "eventType": "INI_RIFERIMENTO_SOAP",
      "eventDate": "2024-11-21T08:25:21.277+0000",
      "message": "SOAP_REQUEST:XXXXXX",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.42.4.4.ca82e244e33627544f31d8d198b95995a33b80abdc60f1b1e004bd0074d6cc65.d0e63cd315^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-11-21T08:25:21.419+0000"
    },
    {
      "eventType": "INI_REPLACE_SOAP",
      "eventDate": "2024-11-21T08:25:22.621+0000",
      "message": "SOAP_REQUEST:XXXXX",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.42.4.4.ca82e244e33627544f31d8d198b95995a33b80abdc60f1b1e004bd0074d6cc65.d0e63cd315^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-11-21T08:25:22.768+0000"
    },
    {
      "eventType": "VALIDATION",
      "eventDate": "2024-11-21T09:25:15.899+01:00",
      "eventStatus": "SUCCESS",
      "subject": "PRVMDC70A01H501L^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "organizzazione": "042",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.42.4.4.ca82e244e33627544f31d8d198b95995a33b80abdc60f1b1e004bd0074d6cc65.d0e63cd315^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "5fb6bd5e7af7df9e",
      "issuer": "integrity:S1#042#PATRENTOTEST",
      "expiringDate": "2025-11-21T09:25:15.906+01:00"
    },
    {
      "eventType": "REPLACE",
      "eventDate": "2024-11-21T09:25:22.588+01:00",
      "eventStatus": "SUCCESS",
      "identificativoDocumento": "SIO.REF.2024.9000000001.2",
      "subject": "PRVMDC70A01H501L^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "tipoAttivita": "CON",
      "organizzazione": "042",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.42.4.4.ca82e244e33627544f31d8d198b95995a33b80abdc60f1b1e004bd0074d6cc65.d0e63cd315^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "4f183156c33b6bd7",
      "issuer": "integrity:S1#042#PATRENTOTEST",
      "expiringDate": "2025-11-21T09:25:22.597+01:00"
    },
    {
      "eventType": "SEND_TO_INI",
      "eventDate": "2024-11-21T09:25:26.776+01:00",
      "eventStatus": "BLOCKING_ERROR",
      "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.42.4.4.ca82e244e33627544f31d8d198b95995a33b80abdc60f1b1e004bd0074d6cc65.d0e63cd315^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-11-21T09:25:26.784+01:00"
    }
  ]
}

```

Potete farci sapere cosa indica quel blocking error? 

cc @apsstn

**Comment by nicola-ferrari-threadsolutions** [comment]
CIao @LucaRogledi 

Hai per caso avuto modo di verificare?

Grazie

**Comment by LucaRogledi** [comment]
Buonasera,
Le riportiamo di seguito la request per cui risulta una vostra risposta con internal error:

`<S:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:S="http://www.w3.org/2003/05/soap-envelope">
	<S:Header>
		<wsa:Action xmlns:wsa="http://www.w3.org/2005/08/addressing">urn:ihe:iti:2007:RegisterDocumentSet-b</wsa:Action>
		<wsa:MessageID xmlns:wsa="http://www.w3.org/2005/08/addressing">c0eafe27-58fe-4af6-95ee-d045a7ea7293</wsa:MessageID>
		<wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
			<saml2:Assertion ID="_494a357a-685c-46e4-b637-54cf6a02a333" IssueInstant="2024-11-21T08:25:22.629Z" Version="2.0" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xs="http://www.w3.org/2001/XMLSchema">
				<saml2:Issuer>integrity:S1#042#PATRENTOTEST</saml2:Issuer>
				<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
					<ds:SignedInfo>
						<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
						<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
						<ds:Reference URI="#_494a357a-685c-46e4-b637-54cf6a02a333">
							<ds:Transforms>
								<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
								<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
									<ec:InclusiveNamespaces PrefixList="xs" xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"/>
								</ds:Transform>
							</ds:Transforms>
							<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
							<ds:DigestValue>Xv94UD5sX5P0Hs02YytT7qmHuKE=</ds:DigestValue>
						</ds:Reference>
					</ds:SignedInfo>
					<ds:SignatureValue>ZwxFb1Hnn4EyohcQKt9EamWeTrhJKAYTtPRoF5UWkjH01KJNNenTxm9vQGrmQ9NThuNuaJpM21G1VqDGAYHGQTeIkgJuzsC+iJlVxaVerDMxnXr+U2CiO6jsjaZxpfH3748+QrOwUUZZ9aJwvp/eoRDSRGwzxVwBxJngpNPPtXtZHjMoARHHWTc0YAbA3b7rTHPLgeJhh87RUPNwby3TximDsyKs82FZLXMfvmR8KuWC0HpWdg6P6N4ukWxW85BZsnzCJkTWNI78hvsFWAZH0dE/FanT6cdSVf38tB20qFCvpDIYUbSsaIZIqhtRvwuVZU6M9T/0kThBmI9+P3AvjQ==</ds:SignatureValue>
					<ds:KeyInfo>
						<ds:X509Data>
							<ds:X509Certificate>MIIE+TCCAuGgAwIBAgIIRHtGTdUftugwDQYJKoZIhvcNAQELBQAwSjELMAkGA1UEBhMCSVQxDjAMBgNVBAoMBVNvZ2VpMSswKQYDVQQDDCJTb2dlaSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eSBUZXN0MB4XDTI0MDExNjE1NTEzN1oXDTI3MDExNjE1NTEzNlowXTELMAkGA1UEBhMCSVQxDjAMBgNVBAoMBVNvZ2VpMRAwDgYDVQQLDAdTYW5pdMOgMSwwKgYDVQQDDCM5OTk5NTAwMDAwMDAvRlNFIEZEIEdBVEVXQVkgVEVTVC8wMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALdoiNc/iZEnW7/dQF0BsLJv73WhmCUK6/wdUvxcUBTayOaw1l34mZESFLmC2d/8JeMzkkRotCDhD+gzMkyOI47Zh/zdBdxmaRQgE8WMIASgFl14gkx/HHdzOKBS75TW2R3mcHJZHtCHfFbkzBm88loo6/HOrzZ1Zyd7U6OAJT/Is8S2rPUkrxXcsR82t2LeuIuuefkPxaF2+cmEJ2nbGCT0XxmBmaF93Mqme+BME2k3BekjFlTuqR37KSO3kPVdea3yOeo6hCfkTc+qwy1Md0RyWkEAJDWYpuLrBWVY1le42f9YIInSIvVzT1NgoAsjGeBgRGHSpFzvVBcIK3jhvVECAwEAAaOBzzCBzDAfBgNVHSMEGDAWgBTGllMVsxcbeaMSZu3K1vRBVTTxITB6BgNVHR8EczBxMG+gbaBrhmlsZGFwOi8vY2Fkcy5maW5hbnplLml0L0NOPVNvZ2VpJTIwQ2VydGlmaWNhdGlvbiUyMEF1dGhvcml0eSUyMFRlc3QsTz1Tb2dlaSxDPUlUP2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3QwHQYDVR0OBBYEFEooXAIW+Ze8P51pHUaLK08+iF6eMA4GA1UdDwEB/wQEAwIGQDANBgkqhkiG9w0BAQsFAAOCAgEAfVooERvZUeBQC+ICC3+Xtn5DU+nZv3sjEcd4Bqfyd1cOM14mYDsvFRO8ibDFZUT2DN2dqksH0D+qLALsuvoOHapZgN46nZwrBlVKFsYNqnVyym5+gArUEDcEhbD00O3fBFRR2UZuJZh4XVPln7pDX73aM34grFM4zyd0tmsWjxdYXph65Xi2o2mKf7wFLSJ8+meODPHWeXzcLBYouZ0BqafNpUa4J9BkzVQ5Bam7rR+x10txDz5+RjjfpvzpKC1eP4qECmv2zjeTkpyS5kXmcUUCrZhgZSFWV+gzZlYtj5ZBcJgcvjbRSdQLpSr1s1SySSG+QW2A4VoipdXId9lPp8LU0ltIWVji2MY8KW5PqmNBULSHCjax+LvDXrUSpJ3geC3LZCMdY+nylPjJKtCWvscSW7p5caz+dY6pXA07TNwfME5SS7UmyJTVI7GKSbuTIW8KQzCSDj6rKUsl1A6UdvF6bJ2eBgJTKKAk4W9cecLNM9FybzGby0jOd9dccl9ZD4zk1o8PDTpt+xB/+M4Gn1qMpHE79s1ZhLMvTR7FzqgnChFH160BXuGm8pvTfoQkJ53RM2+zfMRrUiOtfRHG8PfsWBNvIWipQ1n2bUiVlgT32wX+unZduZHy8NyV0mouBXCNjaQsH9rexY0C7Tq8ce26cykXiTbUGuMLuK1io0U=</ds:X509Certificate>
						</ds:X509Data>
					</ds:KeyInfo>
				</ds:Signature>
				<saml2:Subject>
					<saml2:NameID>PRVMDC70A01H501L^^^&2.16.840.1.113883.2.9.4.3.2&ISO</saml2:NameID>
				</saml2:Subject>
				<saml2:Conditions NotBefore="2024-11-21T08:25:22.629Z" NotOnOrAfter="2025-11-21T08:25:22.629Z"/>
				<saml2:AuthnStatement AuthnInstant="2024-11-21T08:25:22.629Z">
					<saml2:AuthnContext>
						<saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:X509</saml2:AuthnContextClassRef>
					</saml2:AuthnContext>
				</saml2:AuthnStatement>
				<saml2:AttributeStatement>
					<saml2:Attribute Name="urn:oasis:names:tc:xspa:1.0:resource:patient:consent" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
						<saml2:AttributeValue xsi:type="xs:string" xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">true</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute Name="urn:oasis:names:tc:xspa:1.0:resource:hl7:type" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
						<saml2:AttributeValue xsi:type="xs:string" xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">(&apos;11488-4^^2.16.840.1.113883.6.1&apos;)</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute Name="urn:oasis:names:tc:xacml:2.0:subject:role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
						<saml2:AttributeValue xsi:type="xs:string" xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">AAS</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute Name="urn:oasis:names:tc:xspa:1.0:environment:locality" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
						<saml2:AttributeValue xsi:type="xs:string" xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">2.16.840.1.113883.2.9.4.1.2.42101042001</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute Name="urn:oasis:names:tc:xspa:1.0:subject:purposeofuse" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
						<saml2:AttributeValue xsi:type="xs:string" xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">UPDATE</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute Name="urn:oasis:names:tc:xspa:1.0:subject:organization-id" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
						<saml2:AttributeValue xsi:type="xs:string" xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">042</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute Name="urn:oasis:names:tc:xacml:1.0:subject:subject-id" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
						<saml2:AttributeValue xsi:type="xs:string" xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">PRVMDC70A01H501L^^^&2.16.840.1.113883.2.9.4.3.2&ISO</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute Name="urn:oasis:names:tc:xspa:1.0:subject:organization" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
						<saml2:AttributeValue xsi:type="xs:string" xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">P.A. Trento</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute Name="urn:oasis:names:tc:xacml:1.0:resource:resource-id" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
						<saml2:AttributeValue xsi:type="xs:string" xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">TRCTST70A01L378S^^^&2.16.840.1.113883.2.9.4.3.2&ISO</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute Name="urn:oasis:names:tc:xacml:1.0:action:action-id" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
						<saml2:AttributeValue xsi:type="xs:string" xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">UPDATE</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute Name="SubjectApplicationId" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
						<saml2:AttributeValue xsi:type="xs:string" xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">SIO</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute Name="SubjectApplicationVendor" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
						<saml2:AttributeValue xsi:type="xs:string" xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">APSS</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute Name="SubjectApplicationVersion" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
						<saml2:AttributeValue xsi:type="xs:string" xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">2.13.0</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute Name="SubjectAuthenticator" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
						<saml2:AttributeValue xsi:type="xs:string" xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">GTW_950</saml2:AttributeValue>
					</saml2:Attribute>
				</saml2:AttributeStatement>
			</saml2:Assertion>
		</wsse:Security>
	</S:Header>
	<S:Body>
		<ns3:SubmitObjectsRequest xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns5="urn:hl7-org:v3" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns4="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0">
			<RegistryObjectList>
				<ExtrinsicObject id="Document1" isOpaque="false" mimeType="application/pdf+text/x-cda-r2+xml" objectType="urn:uuid:7edca82f-054d-47f2-a032-9b2a5b5186c1" status="urn:oasis:names:tc:ebxml-regrep:StatusType:Approved">
					<Slot name="languageCode">
						<ValueList>
							<Value>it-IT</Value>
						</ValueList>
					</Slot>
					<Slot name="repositoryUniqueId">
						<ValueList>
							<Value>2.16.840.1.113883.2.9.2.42.4.5.0001</Value>
						</ValueList>
					</Slot>
					<Slot name="sourcePatientId">
						<ValueList>
							<Value>TRCTST70A01L378S^^^&2.16.840.1.113883.2.9.4.3.2&ISO</Value>
						</ValueList>
					</Slot>
					<Slot name="urn:ita:2022:documentSigned">
						<ValueList>
							<Value>true^Documento firmato</Value>
						</ValueList>
					</Slot>
					<Slot name="size">
						<ValueList>
							<Value>128842</Value>
						</ValueList>
					</Slot>
					<Slot name="hash">
						<ValueList>
							<Value>bc29d394643dfa2bcb7ab8a197c6f6e5e54cde77</Value>
						</ValueList>
					</Slot>
					<Slot name="creationTime">
						<ValueList>
							<Value>20241120125624</Value>
						</ValueList>
					</Slot>
					<Classification classificationScheme="urn:uuid:41a5887f-8865-4c09-adf7-e362475b143a" classifiedObject="Document1" id="ClassCode" nodeRepresentation="REF" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification">
						<Slot name="codingScheme">
							<ValueList>
								<Value>2.16.840.1.113883.2.9.3.3.6.1.5</Value>
							</ValueList>
						</Slot>
						<Name>
							<LocalizedString charset="UTF-8" value="Referto" xml:lang="en-US"/>
						</Name>
					</Classification>
					<Classification classificationScheme="urn:uuid:f4f85eac-e6cb-4883-b524-f2705394840f" classifiedObject="Document1" id="ConfidentialityCode01" nodeRepresentation="N" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification">
						<Slot name="codingScheme">
							<ValueList>
								<Value>2.16.840.1.113883.5.25</Value>
							</ValueList>
						</Slot>
						<Name>
							<LocalizedString charset="UTF-8" value="Normal" xml:lang="en-US"/>
						</Name>
					</Classification>
					<Classification classificationScheme="urn:uuid:a09d5840-386c-46f2-b5ad-9c3699a4309d" classifiedObject="Document1" id="FormatCode_1" nodeRepresentation="2.16.840.1.113883.2.9.10.1.9.1" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification">
						<Slot name="codingScheme">
							<ValueList>
								<Value>2.16.840.1.113883.2.9.3.3.6.1.6</Value>
							</ValueList>
						</Slot>
						<Name>
							<LocalizedString charset="UTF-8" value="Referto di Specialistica Ambulatoriale" xml:lang="en-US"/>
						</Name>
					</Classification>
					<Classification classificationScheme="urn:uuid:f33fb8ac-18af-42cc-ae0e-ed0b0bdb91e1" classifiedObject="Document1" id="IdHealthcareFacilityTypeCode" nodeRepresentation="Ospedale" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification">
						<Slot name="codingScheme">
							<ValueList>
								<Value>2.16.840.1.113883.2.9.3.3.6.1.1</Value>
							</ValueList>
						</Slot>
						<Name>
							<LocalizedString charset="UTF-8" value="Ospedale" xml:lang="en-US"/>
						</Name>
					</Classification>
					<Classification classificationScheme="urn:uuid:cccf5598-8b07-4b77-a05e-ae952c785ead" classifiedObject="Document1" id="IdPracticeSettingCode" nodeRepresentation="AD_PSC052" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification">
						<Slot name="codingScheme">
							<ValueList>
								<Value>2.16.840.1.113883.2.9.3.3.6.1.2</Value>
							</ValueList>
						</Slot>
						<Name>
							<LocalizedString charset="UTF-8" value="Dermatologia" xml:lang="en-US"/>
						</Name>
					</Classification>
					<Classification classificationScheme="urn:uuid:f0306f51-975f-434e-a61c-c59651d33983" classifiedObject="Document1" id="IdTypeCode" nodeRepresentation="11488-4" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification">
						<Slot name="codingScheme">
							<ValueList>
								<Value>2.16.840.1.113883.6.1</Value>
							</ValueList>
						</Slot>
						<Name>
							<LocalizedString charset="UTF-8" value="Nota di consulto" xml:lang="en-US"/>
						</Name>
					</Classification>
					<Classification classificationScheme="urn:uuid:93606bcf-9494-43ec-9b4e-a7748d1a838d" classifiedObject="Document1" id="Author_1" nodeRepresentation="" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification">
						<Slot name="authorRole">
							<ValueList>
								<Value>AAS</Value>
							</ValueList>
						</Slot>
						<Slot name="authorInstitution">
							<ValueList>
								<Value>SIOTEST^^^^^&2.16.840.1.113883.2.9.4.1.2&ISO^^^^042101042001</Value>
							</ValueList>
						</Slot>
						<Slot name="authorPerson">
							<ValueList>
								<Value>PRVMDC70A01H501L^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO</Value>
							</ValueList>
						</Slot>
					</Classification>
					<ExternalIdentifier id="patientId_1" identificationScheme="urn:uuid:58a6f841-87b3-4a3e-92fd-a8ffeff98427" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:ExternalIdentifier" registryObject="Document1" value="TRCTST70A01L378S^^^&2.16.840.1.113883.2.9.4.3.2&ISO">
						<Name>
							<LocalizedString charset="UTF-8" value="XDSDocumentEntry.patientId" xml:lang="en-US"/>
						</Name>
					</ExternalIdentifier>
					<ExternalIdentifier id="uniqueId_1" identificationScheme="urn:uuid:2e82c1f6-a085-4c72-9da3-8640a32e42ab" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:ExternalIdentifier" registryObject="Document1" value="SIO.REF.2024.9000000001.2">
						<Name>
							<LocalizedString charset="UTF-8" value="XDSDocumentEntry.uniqueId" xml:lang="en-US"/>
						</Name>
					</ExternalIdentifier>
				</ExtrinsicObject>
				<RegistryPackage id="SubmissionSet1" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:RegistryPackage" status="urn:oasis:names:tc:ebxml-regrep:StatusType:Approved">
					<Slot name="submissionTime">
						<ValueList>
							<Value>20241121082521</Value>
						</ValueList>
					</Slot>
					<Classification classificationScheme="urn:uuid:aa543740-bdda-424e-8c96-df4873be8500" classifiedObject="SubmissionSet1" id="IdContentTypeCode" nodeRepresentation="CON" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification">
						<Slot name="codingScheme">
							<ValueList>
								<Value>2.16.840.1.113883.2.9.3.3.6.1.4</Value>
							</ValueList>
						</Slot>
						<Name>
							<LocalizedString charset="UTF-8" value="Consulto" xml:lang="en-US"/>
						</Name>
					</Classification>
					<Classification classificationScheme="urn:uuid:a7058bb9-b4e4-4307-ba5b-e3f0ab85e12d" classifiedObject="SubmissionSet1" id="SubmissionSet1_ClassificationAuthor" nodeRepresentation="" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification">
						<Slot name="authorRole">
							<ValueList>
								<Value>AAS</Value>
							</ValueList>
						</Slot>
						<Slot name="authorInstitution">
							<ValueList>
								<Value>SIOTEST^^^^^&2.16.840.1.113883.2.9.4.1.2&ISO^^^^042101042001</Value>
							</ValueList>
						</Slot>
						<Slot name="authorPerson">
							<ValueList>
								<Value>PRVMDC70A01H501L^^^^^^^^&2.16.840.1.113883.2.9.4.3.2&ISO</Value>
							</ValueList>
						</Slot>
					</Classification>
					<ExternalIdentifier id="SubmissionSet1_SourceId" identificationScheme="urn:uuid:554ac39e-e3fe-47fe-b233-965d2a147832" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:ExternalIdentifier" registryObject="SubmissionSet1" value="2.16.840.1.113883.2.9.2.42">
						<Name>
							<LocalizedString charset="UTF-8" value="XDSSubmissionSet.sourceId" xml:lang="en-US"/>
						</Name>
					</ExternalIdentifier>
					<ExternalIdentifier id="SubmissionSet1_UniqueId" identificationScheme="urn:uuid:96fdda7c-d067-4183-912e-bf5ee74998a8" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:ExternalIdentifier" registryObject="SubmissionSet1" value="2.16.840.1.113883.2.9.2.42.4.3.SIO.REF.2024.9000000001.1">
						<Name>
							<LocalizedString charset="UTF-8" value="XDSSubmissionSet.uniqueId" xml:lang="en-US"/>
						</Name>
					</ExternalIdentifier>
					<ExternalIdentifier id="SubmissionSet1_PatientId" identificationScheme="urn:uuid:6b5aea1a-874d-4603-a4bc-96a0a7b38446" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:ExternalIdentifier" registryObject="SubmissionSet1" value="TRCTST70A01L378S^^^&2.16.840.1.113883.2.9.4.3.2&ISO">
						<Name>
							<LocalizedString charset="UTF-8" value="XDSSubmissionSet.patientId" xml:lang="en-US"/>
						</Name>
					</ExternalIdentifier>
				</RegistryPackage>
				<Association associationType="urn:oasis:names:tc:ebxml-regrep:AssociationType:HasMember" id="urn:uuid:c13ed2f7-9393-44a7-82f1-940cefafb1cd" sourceObject="SubmissionSet1" targetObject="Document1">
					<Slot name="SubmissionSetStatus">
						<ValueList>
							<Value>Original</Value>
						</ValueList>
					</Slot>
				</Association>
				<Association associationType="urn:ihe:iti:2007:AssociationType:RPLC" id="SubmissionSet1_Association_1" sourceObject="Document1" targetObject="urn:uuid:56c74f8f-a90b-4421-97be-a7fe82f03b83"/>
				<Classification classificationNode="urn:uuid:a54d6aa5-d40d-43f9-88c5-b4633d873bdd" classifiedObject="SubmissionSet1" id="Classification1" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification"/>
			</RegistryObjectList>
		</ns3:SubmitObjectsRequest>
	</S:Body>
</S:Envelope>`

Restiamo a disposizione per eventuale supporto.
Grazie
