### ISSUE TITLE
Regione Puglia: Repository distribuito

### ISSUE THREAD

**Issue by enzocap** [ministero-salute/it-fse-support#1317]
Buongiorno,
la Regione Puglia ha comunicati di aver adottato il modelo regionale distribuito:
“Nel modello regionale distribuito i documenti sanitari prodotti da un soggetto alimentante sono memorizzati in un repository di responsabilità del medesimo soggetto che li ha prodotti.”
Volevo sapere cosa cambia dal punto di vista dei conferimenti al FSE 2.0 e a quali specifiche tecniche fare riferimento.
Grazie

**Comment by vigliottim** [comment]
Buongiorno,
al momento non sono disponibili informazioni in merito.
La invitiamo a seguire i canali dedicati per aggiornamenti.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.

**Comment by enzocap** [comment]
Grazie, ma cosa intendete per "canali dedicati"?

**Comment by vigliottim** [comment]
> Grazie, ma cosa intendete per "canali dedicati"?

I canali Slack e GitHub dedicati a FSE 2.0.

**Comment by IStacchiotti** [comment]
Buongiorno @enzocap ,
Il fascicolo 2.0 prevede che i documenti risiedano sul repository che ha svolto la pubblicazione e l'acquisizione dei metadati a livello centrale.
Per le specifiche del gateway può fare riferimento alla documentazione ai link [1](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway),[2](https://developers.italia.it/it/fse/#resourcecontent-3). 
 
Le segnaliamo anche questo [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/middleware-regionale#modello-middleware-regionale) che riporta i modelli di interazione con il gateway a seconda della presenza o meno del middleware regionale.
 
Per eventuali dettagli sulla specifica architettura regionale, la invitiamo a chiedere direttamente alla Regione di riferimento.
 
Rimaniamo a disposizione per eventuali ulteriori chiarimenti. Grazie

**Comment by ds-tommaso** [comment]
Perdonate l'intrusione...


Allo stato attuale, abbiamo il GTW nazionale da integrare ai fini dell'accreditamento. Ogni regione dispone di un servizio tutto suo (i servizi di Molise, Puglia ed Emilia sono tutti diversi, Lazio segue il GWT, le regioni in sussidiarietà useranno il canale FSE1.0 per pubblicazione e FSE2.0 per validazione/modifica/cancellazione). 

I referti pubblicati dove confluiscono? Solo la regione Puglia ha scelto la soluzione con repository distribuito?

**Qui, alcune perplessità:**

Come può ogni struttura esporre delle API? C'è chi ha ancora la linea ADSL, chi spegne i computer alla sera o chi utilizza server non potenti. Non tutti hanno un IP pubblico di tipo statico e non tutti vorrebbero esporre i propri dati all'esterno. 

Ad oggi, esistono repository (Aruba, Reevo, TIM, Amazon, altro?)? Non so, il referto viene inviato a questi e poi su FSE.

**Comment by enzocap** [comment]
Io trovo semplicemente assurdo che si facciano dei progressi per rendere un servizio omogeneo e fruibile in tutta Italia (vedi FSE 2.0), e poi alcune regioni vanificano il tutto imponendo le loro regole, penalizzando così le software house e soprattuto le strutture private, già tartassate dalle continue riduzioni dei tariffari.

**Comment by infoserviceonline** [comment]
Mi accodo precisando che, a quanto mi risulta, ad oggi solo la Puglia ha optato per Repository distribuito, di cui mancano diverse specifiche tecniche, la parte amministrativa ed altro.
Per rispondere a @ds-tommaso non mi risulta che nessuno abbia ancora implementato il Repository, nemmeno i soliti noti. Oltretutto non si è ancora capito se è lecito o meno offrirlo come Saas in cloud. Ne vedremo delle belle, viste le **minacce** di non rinnovo del contratto di accreditamento, anche se c'è in atto una revisione in tal senso.

**Comment by LucaRogledi** [comment]
Buongiorno,
Chiediamo gentilmente alla regione Puglia di fornire supporto per la richiesta delle specifiche tecniche @lninnova .
Al momento non disponibili maggiori informazioni riguardo il rilascio del gateway in produzione, riceverà aggiornamenti non appena disponibili tramite i canali dedicati. 
Grazie

**Comment by ds-tommaso** [comment]
Salve @Ininnova

Oltre alle specifiche tecniche, chiederei se la messa in atto del repository è strettamente legata a FSE2.0, nonché al GTW pubblicato in ambiente di produzione. Al momento, diversi clienti stanno richiedendo il modulo FSE ed altri lo stanno già utilizzando (dato che è ormai obbligatorio ai fini dell'accreditamento).

Ps. Il repository può essere inteso come servizio Saas? Sarà sempre necessario disporre della VPN con Edotto?

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso in cui sia necessario ulteriore supporto.
Grazie.

**Comment by vigliottim** [comment]
Buonasera, procediamo alla chiusura della presente issue in assenza di ulteriori aggiornamenti.
Sarà possibile riaprirlo se necessario.
Grazie.
