### ISSUE TITLE
crash-program. errore pubblicazione sostituzione verso Provincia Bolzano

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#1319]
buonasera,
tentando di pubblicare una sostituzione documento del CF PRVFSN70S04A952Z verso la provincia di Bolzano ricevo l'errore

`Impossibile contattare RDA. fonte FSE-INS-BE`

Grazie

**Comment by vigliottim** [comment]
Buonasera @SonnyMate,
chiediamo gentilmente alla PA di Bolzano di fornire supporto.
Grazie.

**Comment by alessandropassamonti** [comment]
workflowInstanceId:

2.16.840.1.113883.2.9.2.130202.4.4.9feef4aea63e9a28cf8e2ca2d9521536bb8bef2ade18390c8a11392253745e23.9e7e36d41a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

**Comment by alessandropassamonti** [comment]
buongiorno,
il problema
Impossibile contattare RDA. fonte FSE-INS-BE
viene restituito da ricercaDocumenti e non da comunicazioneMetadati

**Comment by ngaraventa** [comment]
Buongiorno,
non risulta aver ricevuto la iti-18 è possibile fare una verifica lato gateway?

Grazie

**Comment by vigliottim** [comment]
Buongiorno,

@alessandropassamonti 
La informiamo che verranno svolte delle verifiche lato INI in merito all'errore "Impossibile contattare RDA".

@ngaraventa 
La chiamata non è stata effettuata utilizzando i servizi del GTW ma quelli INS. 
Infatti, sul GTW non è presente alcuna chiamata e su INI non sono presenti informazioni che evidenzano che la chiamata proviene dal GTW.

**Comment by alessandropassamonti** [comment]
buongiorno,

@g-maugeri-sogei 
come comunicato in altre issue, continua il problema

Impossibile contattare RDA fonte: FSE-INS-BE codEsito: 2061

utilizzando endpoint
INS https://fseservicetest.sanita.finanze.it/FseInsServicesWeb/services/fseRicercaDocumenti

Questo non permette di continuare con i test di sostituzione
Grazie
