### ISSUE TITLE
Mancato accreditamento S1#111THEMIX00000

### ISSUE THREAD

**Issue by cap-nic** [ministero-salute/it-fse-support#132]
Buongiorno,
nella fase di verifica accreditamento ci è stato segnalato anche il seguente errore:
```
{
  "id" : 3,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='004' attribute='code' actual = '48767-8' expected = '33882-2'>ClinicalDocument/component/structuredBody/component/section/component/section/entry/act/entryRelationship/act/code</error>"
}
```
nell'xml generato il campo entryRelationship con code="33882-2" è regolarmente presente. Il campo entryRelationship con code="48767-8" è quello relativo alle "Annotazioni e commenti", da specifiche la presenza di molteplici campi entryRelationship è consentito:
```
<xs:complexType name="POCD_MT000040UV02.Act">
      <xs:sequence>
        ...
         <xs:element name="entryRelationship" type="POCD_MT000040UV02.EntryRelationship"
                     minOccurs="0"
                     maxOccurs="unbounded"/>
        ...
</xs:complexType>
```
Riporto per semplicità i riferimenti del caso di test:
```
{
   "id": 3,
   "ts":"2023-02-24T14:59:17Z",
   "traceId": "b4cb9c81e4ac1673",
   "workflowInstanceId":
"2.16.840.1.113883.2.9.2.120.4.4.844058695c9ddd088f3afdc4e917d64d482c293dd8036cae4e45ccf935df5fb4.ca84f797b0^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
   "files": [
                "TC_3.PDF"
              ]
}
```
Rimango in attesa di riscontro così da poter effettuare una nuova pull request con tutte le correzioni effettuate.

Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, dovrebbe ricevere a breve comunicazioni via email sull'esito delle verifiche sulla pull request. Ci faccia sapere se il problema persiste. 
Grazie

**Comment by IStacchiotti** [comment]
Buon pomeriggio, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
