### ISSUE TITLE
crash-program. errore pubblicazione sostituzione verso Sardegna

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#1320]
buonasera,
tentando di pubblicare una sostituzione documento del CF CGNCTD93M22B354R verso la provincia di Bolzano ricevo l'errore
`
Impossibile contattare RDA. fonte FSE-INS-BE`

Grazie

**Comment by vigliottim** [comment]
Buonasera @FSESardegna
chiediamo gentilmente alla regione Sardegna di fornire supporto.
Grazie.

**Comment by FSESardegna** [comment]
Buongiorno,
per potervi fornire supporto abbiamo necessità di maggiori dettagli della transazione andata in errore. Sarebbe necessario almeno workflowInstanceId e/o traceId.

Rimaniamo a disposizione.

**Comment by alessandropassamonti** [comment]
buongiorno,

workflowInstanceId :
2.16.840.1.113883.2.9.2.130202.4.4.b96bba349686bba54b5b9e8c0b3fcad48a2d683048ecd4506ae5baae4553e510.7e29504662^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

**Comment by alessandropassamonti** [comment]
buongiorno,
il problema
Impossibile contattare RDA. fonte FSE-INS-BE
viene restituito da ricercaDocumenti e non da comunicazioneMetadati

**Comment by FSESardegna** [comment]
Buongiorno,
a seguito di un controllo dello stato transazione otteniamo il seguente messaggio:

`[TransactionData(eventType=VALIDATION, eventDate=2024-11-21T14:47:53.293Z, eventStatus=SUCCESS, subject=PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO, organizzazione=130, workflowInstanceId=2.16.840.1.113883.2.9.2.130202.4.4.b96bba349686bba54b5b9e8c0b3fcad48a2d683048ecd4506ae5baae4553e510.7e29504662^^^^urn:ihe:iti:xdw:2013:workflowInstanceId, traceId=4af8a2d9df6561d1, issuer=integrity:S1#130#ABRUZZO_ASL2_TEST, expiringDate=2025-11-21T14:47:53.299Z, message=null, identificativoDocumento=null)]`

Quindi analizzando l'errore possiamo notare che non è stato pubblicato nessun documento.
E' possibile eseguire una nuova prova?

**Comment by g-maugeri-sogei** [comment]
Buonasera,
problema rientrato.

**Comment by alessandropassamonti** [comment]
buongiorno,

@g-maugeri-sogei 
come comunicato in altre issue, continua il problema

Impossibile contattare RDA fonte: FSE-INS-BE codEsito: 2061

utilizzando endpoint
INS https://fseservicetest.sanita.finanze.it/FseInsServicesWeb/services/fseRicercaDocumenti

Questo non permette di continuare con i test di sostituzione
Grazie

**Comment by alessandropassamonti** [comment]
sono riuscito a pubblicare la sostituzione. attendo esito della comunicazione metadati
Grazie
