### ISSUE TITLE
crash-program. errore pubblicazione sostituzione verso valle d'aosta

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#1321]
buonasera,
tentando di pubblicare una sostituzione documento del CF PZNTTF75H27E379B verso Valle D'Aosta ricevo l'errore

`Impossibile contattare RDA. fonte FSE-INS-BE`

stesso problema riscontrato in #1306, #1319, #1320 

Grazie

**Comment by vigliottim** [comment]
Buonasera @assistenza-fsevda,
chiediamo gentilmente alla regione Valle d'Aosta di fornire supporto.
Grazie.

**Comment by assistenza-fsevda** [comment]
buonasera
nella giornata odierna abbiamo avuto alcuni down sul ns middleware regionale, ambiente di Stage, a seguito di aggiornamenti applicativi. Vi aggiorniamo appena possibile per eseguire una nuova prova.
saluti

**Comment by assistenza-fsevda** [comment]
Buongiorno @alessandropassamonti,
abbiamo terminato le attività. Potete riprovare una nuova pubblicazione?
Grazie mille per la disponibilità.

**Comment by alessandropassamonti** [comment]
buongiorno,
ancora stesso errore.

workflowInstanceId:
2.16.840.1.113883.2.9.2.130202.4.4.7fd68355fe2d25c2000180353c107a87efc1fd6057295519e7aa9c437a0101c6.1ea3a4df28^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

**Comment by assistenza-fsevda** [comment]
Buongiorno,
abbiamo provato ad analizzare il caso legato al workflowInstanceId indicato ma non vediamo l'evento di pubblicazione. Effettuando una ricerca dello stato abbiamo visto che è stato effettuato solo il processo di validazione. C'è stato un errore lato gateway nella pubblicazione?

@alessandropassamonti @vigliottim riuscite a verificare come mai il processo si ferma alla validazione?

Di seguito il dettaglio delle stato recuperato da Gateway:
```
{
    "traceID": "4185d2c99b342aab",
    "spanID": "4752a8eebf3e1e47",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-11-21T15:53:54.799+01:00",
            "eventStatus": "SUCCESS",
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "130",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.130202.4.4.7fd68355fe2d25c2000180353c107a87efc1fd6057295519e7aa9c437a0101c6.1ea3a4df28^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "f0ccc631a88d7a60",
            "issuer": "integrity:S1#130#ABRUZZO_ASL2_TEST",
            "expiringDate": "2025-11-21T15:53:54.808+01:00"
        }
    ]
}
```

Rimaniamo in attesa per proseguire l'analisi.

**Comment by vigliottim** [comment]
Buonasera,
la pubblicazione viene completata una volta che la richiesta viene elaborata dal sistema centrale della sussidiarietà.
Effettueremo delle verifiche in merito.
Grazie.

**Comment by alessandropassamonti** [comment]
buongiorno,
il problema
Impossibile contattare RDA. fonte FSE-INS-BE
viene restituito da ricercaDocumenti e non da comunicazioneMetadati

**Comment by assistenza-fsevda** [comment]
Buongiorno,
abbiamo visto che il problema della ricerca documenti è stato segnalato in diversi issues. In questo commento https://github.com/ministero-salute/it-fse-support/issues/1320#issuecomment-2497745590 è stato richiesto un approfondimento a @vigliottim per verificare eventuali problemi lato INI. Aspetterei l'esito di queste verifiche prima di procedere con altri test.
@alessandropassamonti se intanto mi fate avere lo uniqueid del documento che volete sostituire verifico che effettivamente sia presente nel nostro registry.

**Comment by alessandropassamonti** [comment]
buongiorno,
lo uniqueId è 2.16.840.1.113883.2.9.2.130.4.4^497322, CF PZNTTF75H27E379B

grazie

**Comment by assistenza-fsevda** [comment]
Buongiorno,
confermo che il documento indicato è presente nel nostro registry. Lo abbiamo ricevuto ed indicizzato sul paziente PZNTTF75H27E379B in data 11/11/2024.
Attendiamo l'esito della verifica lato INI per proseguire.
Buon lavoro.

**Comment by alessandropassamonti** [comment]
buongiorno,

@g-maugeri-sogei 
come comunicato in altre issue, continua il problema

Impossibile contattare RDA fonte: FSE-INS-BE codEsito: 2061

utilizzando endpoint
INS https://fseservicetest.sanita.finanze.it/FseInsServicesWeb/services/fseRicercaDocumenti

Questo non permette di continuare con i test di sostituzione
Grazie

**Comment by alessandropassamonti** [comment]
sono riuscito a pubblicare la sostituzione. attendo esito della comunicazione metadati
Grazie
