### ISSUE TITLE
Compilazione richiesta accreditamento e riferimenti email

### ISSUE THREAD

**Issue by pierpa68** [ministero-salute/it-fse-support#1328]
Buongiorno,
ho cercato di comunicare a Sogei il mancato riscontro alla ns richiesta di accreditamento (compilata tramite modulo online all'indirizzo https://ec.europa.eu/eusurvey/runner/FSE-raccolta-id-applicativo come indicato  nella documentazione).
Ho provato a mandare una mail all'indirizzo di supporto indicato nella stessa pagina ( fse-support@sogei.it ) ma il messaggio è stato respinto dal postmaster di Sogei dicendo che l'indirizzo non è valido.

Esiste un canale per comunicare queste problematiche?

**Comment by vigliottim** [comment]
Buongiorno,
le chiediamo gentilmente di riprovare.
Grazie.

**Comment by pierpa68** [comment]
La procedura di registrazione o l'invio della mail?

**Comment by vigliottim** [comment]
> La procedura di registrazione o l'invio della mail?

Ci riferiamo alla procedura di registrazione, grazie.

**Comment by ds-tommaso** [comment]
Buonasera @vigliottim e perdonate l'ingresso nel thread

Ad oggi, è ancora ferma la compilazione del questionario per l'attività di pubblicazione giusto?
Faccio seguito la nota "_Le fasi 2 e 3 del processo di accreditamento vengono rimandate ad un momento successivo, cioè quando il gateway sarà disponibile in produzione_" (rif. https://github.com/ministero-salute/it-fse-support/tree/main/doc/transitorio#3-processo-di-accreditamento-convalida).

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso fosse necessario ulteriore supporto. Grazie.

**Comment by pierpa68** [comment]
Buongiorno,
abbiamo rifatto la procedura di registrazione in data 22/11 ma ad oggi ancora nessun riscontro.
Non so se possiamo considerare chiusa la issue... almeno per quanto riguarda la nostra posizione.

Grazie

**Comment by pierpa68** [comment]
@vigliottim possiamo riaprire questa issue visto che non si risolve? Non possiamo neppure cominciare il progetto...

Grazie

**Comment by LucaRogledi** [comment]
Buonasera, 
La informiamo che non è necessario attendere riscontro in merito all'avvenuta sottoscrizione dell'applicativo su EuSurvey e che può procedere con l'esecuzione dei [test di accreditmento](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione) per i cda di interesse, dopo aver effettuato la richiesta dei certificati come indicato in [documentazione - richiesta certificati](https://github.com/ministero-salute/it-fse-support#richiesta-certificati-x509).
Riportiamo inoltre la documentazione di supporto per l'invocazione dei servizi esposti dal Gateway [Documentazione - integrazione-gateway](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway).
Grazie

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso necessiti di ulteriore supporto in merito all'oggetto del ticket.
Grazie.
