### ISSUE TITLE
Mancato accreditamento - TEST MANCANTI RISPETTO ALLA CHECKLIST

### ISSUE THREAD

**Issue by insielFse** [ministero-salute/it-fse-support#133]
Salve,
dopo vari passaggi, abbiamo ricevuto una mail di mancato accreditamento:
"_Con la presente si comunica per il Fornitore [S1#060000000000XX] - Vendor:[INSIEL] - ID: [SEI] - Version: [SEI 03.00.02.01] la fase preliminare per il processo di accreditamento non è stata rispettata. Si prega di effettuare una nuova push correttiva._" 

il JSON in allegato riporta: 
_[ {
 "error" : "TEST_NON_PRESENTE",
 "description" : "Test mancanti rispetto alla checklist:[25, 26, 27]"
 } ]_

test che nel file report-checklist.xlsx abbiamo dichiarato come NON APPLICABILI.

**Come mai viene segnalata la mancanza dei test, quando le sezioni e le entry richieste sono dichiarate facoltative nelle specifiche? Non essendo informazioni gestite dai nostri applicativi, si è ritenuto necessario contrassegnare i test come "Non Applicabili".**

Analogamente per l'applicativo CLINICO:
"_Con la presente si comunica per il Fornitore [S1#060000000000XX] - Vendor:[INSIEL] - ID: [CLINICO] - Version: [G4.3.0] la fase preliminare per il processo di accreditamento non è stata rispettata. Si prega di effettuare una nuova push correttiva."
[ {
  "error" : "TEST_NON_PRESENTE",
  "description" : "Test mancanti rispetto alla checklist:[7, 8, 9, 12, 13, 14]"
} ]_

Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che il problema segnalato in questo ticket è stato risolto. Infatti ci risulta che è andato avanti, riscontrando nuovi messaggi di errore, segnalati nel ticket #146. Per questo motivo procediamo alla chiusura del presente ticket e le confermiamo che il #146 è in corso di analisi. Le risponderemo appena possibile.
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che il problema segnalato in questo ticket è stato risolto. Infatti ci risulta che è andato avanti, riscontrando nuovi messaggi di errore, segnalati nel ticket #146. Per questo motivo procediamo alla chiusura del presente ticket e le confermiamo che il #146 è in corso di analisi. Le risponderemo appena possibile.
Grazie
