### ISSUE TITLE
Specifiche tecniche repository Calabria

### ISSUE THREAD

**Issue by SaxosD** [ministero-salute/it-fse-support#1330]
Dove si trovano le specifiche tecniche per l'integrazione con il repository in un contesto di sussidiarietà ?
In particolare, in seguito alla validazione sul gateway, dovremmo inviare il documento al repository Calabria, secondo quanto illustrato al [punto 2](https://github.com/ministero-salute/it-fse-support/raw/main/doc/middleware-regionale/img/modello_senza_mw.png).

Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno,
Per informazioni riguardo i servizi in contesto di sussidiarietà può inoltrare la richiesta direttamente a gestionets@sogei.it.
Grazie

**Comment by SaxosD** [comment]
Grazie
