### ISSUE TITLE
crash-program. Errore sostituzione documento verso regione Calabria

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#1331]
Buongiorno,
il tentativo di pubblicazione di una sostituzione documento del CF MLRFNC62C25F112I genera l'errore

```
ComunicazioneMetadatiRicevuta >
  <Esito xmlns="http://comunicazionemetadatiricevuta.xsd.fse.ini.finanze.it">9999</Esito>
  <ElencoErrori xmlns="http://comunicazionemetadatiricevuta.xsd.fse.ini.finanze.it">
    <Errore >
      <codEsito>9000</codEsito>
      <esito>9999 - </esito>
      <tipoErrore>Bloccante</tipoErrore>
      <fonte>FSE-INS-GATEWAY</fonte>
    </Errore>
  </ElencoErrori>
</ComunicazioneMetadatiRicevuta>
```

allego la request della comunicazione metadati
[request_replace_documento_calabria.txt](https://github.com/user-attachments/files/17870783/request_replace_documento_calabria.txt)

**Comment by alessandropassamonti** [comment]
il documento è stato pubblicato.
L'esito è in Elaborazione.

**Comment by g-maugeri-sogei** [comment]
Il documento risulta in stato OK.

**Comment by alessandropassamonti** [comment]
@g-maugeri-sogei come indicato anche in altre issue, non riesco più ad utilizzare i servizi con la basic authentication , ma solo con la CNS e questo non mi permette di proseguire con i test.
inoltre se interrogo lo status del Gtw il documento risulta ancora in validazione. 

2.16.840.1.113883.2.9.2.130202.4.4.9d0e6e332744a674d86b84190e6d90535442a2de53c9ed8c4a4db73264c62756.c0bc03bb57^^^^urn:ihe:iti:xdw:2013:workflowInstanceId


```
{
"spanID": "d38c544c3558fff7",
"traceID": "398e2efaf81eafb8",
"transactionData":
    [
        {
        "eventDate": "2024-11-22T14:20:16.123+01:00",
        "eventStatus": "SUCCESS",
        "eventType": "VALIDATION",
        "expiringDate": "2025-11-22T14:20:16.130+01:00",
        "issuer": "integrity:S1#130#ABRUZZO_ASL2_TEST",
        "organizzazione": "130",
        "subject": "PSSLSN76B20G482T^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
        "traceId": "6d4af6582f99bed5",
        "workflowInstanceId": "2.16.840.1.113883.2.9.2.130202.4.4.9d0e6e332744a674d86b84190e6d90535442a2de53c9ed8c4a4db73264c62756.c0bc03bb57^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
        }
    ]
}
```

**Comment by g-maugeri-sogei** [comment]
Oggi ci sono problemi sul nostro LDAP.
