### ISSUE TITLE
Crash Program Abruzzo - Errore Replace verso Piemonte

### ISSUE THREAD

**Issue by avlp** [ministero-salute/it-fse-support#1335]
Nel tentativo di effettuare una replace di un documento già acquisito con identifier 2.16.840.1.113883.2.9.2.130.4.4^497377 (TEMP_130_2470445) si ottiene l'errore: Riferimento documento non valido
Step eseguiti:
1. Ricerca riferimento documento:
 `<ric:RicercaDocumentiRichiesta xmlns:ric="http://ricercadocumentirichiesta.xsd.fse.ini.finanze.it">
	<ric:IdentificativoUtente>PROVAX00X00X000Y</ric:IdentificativoUtente>
	<ric:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</ric:pinCode>
	<ric:IdentificativoOrganizzazione>130</ric:IdentificativoOrganizzazione>
	<ric:StrutturaUtente>204123456</ric:StrutturaUtente>
	<ric:RuoloUtente>DRS</ric:RuoloUtente>
	<ric:ContestoOperativo>UPDATE</ric:ContestoOperativo>
	<ric:IdentificativoAssistito>SCLSCL00A55G273T</ric:IdentificativoAssistito>
	<ric:PresaInCarico>true</ric:PresaInCarico>
	<ric:StatoDocumento>Approved</ric:StatoDocumento>
	<ric:IdentificativoDocumento>2.16.840.1.113883.2.9.2.130.4.4^497377</ric:IdentificativoDocumento>
	<ric:IdentificativoApplicativoRichiedente>AREAS AMBWEB</ric:IdentificativoApplicativoRichiedente>
	<ric:FornitoreApplicativoRichiedente>Engineering Ingegneria Informatica SpA</ric:FornitoreApplicativoRichiedente>
	<ric:VersioneApplicativoRichiedente>20.15.00</ric:VersioneApplicativoRichiedente>
	<ric:OpzioniRisposta>ObjectRef</ric:OpzioniRisposta>
</ric:RicercaDocumentiRichiesta>`
Response: a9d94779-e543-46ef-97fb-ce3fbf1131b4
2. Request Replace:
`<com:ComunicazioneMetadatiRichiesta xmlns:com="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it" xmlns:tip="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it">
	<com:IdentificativoUtente>PROVAX00X00X000Y</com:IdentificativoUtente>
		<com:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</com:pinCode>
	<com:IdentificativoOrganizzazione>130</com:IdentificativoOrganizzazione>
		<com:StrutturaUtente>204123456</com:StrutturaUtente>
	<com:RuoloUtente>DRS</com:RuoloUtente>
	<com:ContestoOperativo>TREATMENT</com:ContestoOperativo>
	<com:TipoDocumento/>
	<com:IdentificativoAssistito>SCLSCL00A55G273T</com:IdentificativoAssistito>
	<com:PresaInCarico>true</com:PresaInCarico>
	<com:TipoAttivita>CREATE</com:TipoAttivita>
	<com:Metadato>
		<tip:TipologiaStrutturaProdDoc>Ospedale</tip:TipologiaStrutturaProdDoc>
		<tip:TipoMime>application/pdf+text/x-cda-r2+xml</tip:TipoMime>
		<tip:LivelloConfidenzialita>N</tip:LivelloConfidenzialita>
		<tip:TipologiaDocumentoAlto>REF</tip:TipologiaDocumentoAlto>
		<tip:TipologiaDocumentoMedio>11488-4</tip:TipologiaDocumentoMedio>
		<tip:TipologiaDocumentoBasso>2.16.840.1.113883.2.9.10.1.9.1</tip:TipologiaDocumentoBasso>
		<tip:RiferimentoDocumento>a9d94779-e543-46ef-97fb-ce3fbf1131b4</tip:RiferimentoDocumento>
			<tip:Associazione>
				<tip:associationType>urn:ihe:iti:2007:AssociationType:RPLC</tip:associationType>
				<tip:sourceObject>doc1</tip:sourceObject>
				<tip:targetObject>a9d94779-e543-46ef-97fb-ce3fbf1131b4</tip:targetObject>
				<tip:submissionSetStatus>Original</tip:submissionSetStatus>
				<tip:previousVersion/>
            </tip:Associazione>
          <tip:IdentificativoUnivocoDocumento>doc1</tip:IdentificativoUnivocoDocumento>
		<tip:DataValidazioneDocumento>20241113053650</tip:DataValidazioneDocumento>
		<tip:RuoloAutore>DRS</tip:RuoloAutore>
<tip:IstituzioneAutore>130204123456</tip:IstituzioneAutore>
			<tip:CodiceFiscaleAutore>PROVAX00X00X000Y</tip:CodiceFiscaleAutore>
		<tip:AssettoOrganizzativo>AD_PSC010</tip:AssettoOrganizzativo>
		<tip:TipoAttivitaClinica>DIS</tip:TipoAttivitaClinica>
		<tip:DataInizioPrestazione>20241113053650</tip:DataInizioPrestazione>
		<tip:DataFinePrestazione>20241113053650</tip:DataFinePrestazione>
<tip:IdentificativoSottomissione/>
			<tip:DocumentoFirmato>true^Documento firmato</tip:DocumentoFirmato>
	</com:Metadato>
	<com:IdentificativoApplicativoRichiedente>AREAS AMBWEB</com:IdentificativoApplicativoRichiedente>
	<com:FornitoreApplicativoRichiedente>Engineering Ingegneria Informatica SpA</com:FornitoreApplicativoRichiedente>
	<com:VersioneApplicativoRichiedente>20.15.00</com:VersioneApplicativoRichiedente>
	<com:OpzioniRequest>
		<tip:chiave>GATEWAY</tip:chiave>
		<tip:valore>true</tip:valore>
	</com:OpzioniRequest>
	<com:OpzioniRequest>
		<tip:chiave>WORKFLOWINSTANCEID</tip:chiave>
		<tip:valore>2.16.840.1.113883.2.9.2.130.4.4.43ec9700c7f511f17c402316988a1a02bbf068197a0f4b9b97a9f84664b5141e.a3db13bb57^^^^urn:ihe:iti:xdw:2013:workflowInstanceId</tip:valore>
	</com:OpzioniRequest>
	<com:OpzioniRequest>
		<tip:chiave>MODE</tip:chiave>
		<tip:valore>ATTACHMENT</tip:valore>
	</com:OpzioniRequest>
</com:ComunicazioneMetadatiRichiesta>`
Response: `<?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><a:ComunicazioneMetadatiRicevuta xmlns:a="http://comunicazionemetadatiricevuta.xsd.fse.ini.finanze.it" xmlns="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it" xmlns:b="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it"><a:Esito>9999</a:Esito><a:ElencoErrori><Errore><codEsito>1144</codEsito><esito>Riferimento documento non valido</esito><tipoErrore>Bloccante</tipoErrore><fonte>FSE-INS-FE</fonte></Errore><Errore><codEsito>1144</codEsito><esito>Riferimento documento non valido</esito><tipoErrore>Bloccante</tipoErrore><fonte>FSE-INS-FE</fonte></Errore></a:ElencoErrori></a:ComunicazioneMetadatiRicevuta></soapenv:Body></soapenv:Envelope>`

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
La invitiamo a riaprirla nel caso in cui fosse necessario ulteriore supporto.
Grazie.

**Comment by avlp** [comment]
Salve,
ho appena riprovato, stesso esito:
`<com:ComunicazioneMetadatiRichiesta xmlns:com="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it" xmlns:tip="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it">
	<com:IdentificativoUtente>PROVAX00X00X000Y</com:IdentificativoUtente>
		<com:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</com:pinCode>
	<com:IdentificativoOrganizzazione>130</com:IdentificativoOrganizzazione>
		<com:StrutturaUtente>204123456</com:StrutturaUtente>
	<com:RuoloUtente>DRS</com:RuoloUtente>
	<com:ContestoOperativo>TREATMENT</com:ContestoOperativo>
	<com:TipoDocumento/>
	<com:IdentificativoAssistito>SCLSCL00A55G273T</com:IdentificativoAssistito>
	<com:PresaInCarico>true</com:PresaInCarico>
	<com:TipoAttivita>CREATE</com:TipoAttivita>
	<com:Metadato>
		<tip:TipologiaStrutturaProdDoc>Ospedale</tip:TipologiaStrutturaProdDoc>
		<tip:TipoMime>application/pdf+text/x-cda-r2+xml</tip:TipoMime>
		<tip:LivelloConfidenzialita>N</tip:LivelloConfidenzialita>
		<tip:TipologiaDocumentoAlto>REF</tip:TipologiaDocumentoAlto>
		<tip:TipologiaDocumentoMedio>11488-4</tip:TipologiaDocumentoMedio>
		<tip:TipologiaDocumentoBasso>2.16.840.1.113883.2.9.10.1.9.1</tip:TipologiaDocumentoBasso>
		<tip:RiferimentoDocumento>a9d94779-e543-46ef-97fb-ce3fbf1131b4</tip:RiferimentoDocumento>
			<tip:Associazione>
				<tip:associationType>urn:ihe:iti:2007:AssociationType:RPLC</tip:associationType>
				<tip:sourceObject>doc1</tip:sourceObject>
				<tip:targetObject>a9d94779-e543-46ef-97fb-ce3fbf1131b4</tip:targetObject>
				<tip:submissionSetStatus>Original</tip:submissionSetStatus>
				<tip:previousVersion/>
            </tip:Associazione>
          <tip:IdentificativoUnivocoDocumento>doc1</tip:IdentificativoUnivocoDocumento>
		<tip:DataValidazioneDocumento>20241113053650</tip:DataValidazioneDocumento>
		<tip:RuoloAutore>DRS</tip:RuoloAutore>
<tip:IstituzioneAutore>130204123456</tip:IstituzioneAutore>
			<tip:CodiceFiscaleAutore>PROVAX00X00X000Y</tip:CodiceFiscaleAutore>
		<tip:AssettoOrganizzativo>AD_PSC010</tip:AssettoOrganizzativo>
		<tip:TipoAttivitaClinica>DIS</tip:TipoAttivitaClinica>
		<tip:DataInizioPrestazione>20241113053650</tip:DataInizioPrestazione>
		<tip:DataFinePrestazione>20241113053650</tip:DataFinePrestazione>
			<tip:DocumentoFirmato>true^Documento firmato</tip:DocumentoFirmato>
	</com:Metadato>
	<com:IdentificativoApplicativoRichiedente>AREAS AMBWEB</com:IdentificativoApplicativoRichiedente>
	<com:FornitoreApplicativoRichiedente>Engineering Ingegneria Informatica SpA</com:FornitoreApplicativoRichiedente>
	<com:VersioneApplicativoRichiedente>20.15.00</com:VersioneApplicativoRichiedente>
	<com:OpzioniRequest>
		<tip:chiave>GATEWAY</tip:chiave>
		<tip:valore>true</tip:valore>
	</com:OpzioniRequest>
	<com:OpzioniRequest>
		<tip:chiave>WORKFLOWINSTANCEID</tip:chiave>
		<tip:valore>2.16.840.1.113883.2.9.2.130.4.4.43ec9700c7f511f17c402316988a1a02bbf068197a0f4b9b97a9f84664b5141e.a3db13bb57^^^^urn:ihe:iti:xdw:2013:workflowInstanceId</tip:valore>
	</com:OpzioniRequest>
	<com:OpzioniRequest>
		<tip:chiave>MODE</tip:chiave>
		<tip:valore>ATTACHMENT</tip:valore>
	</com:OpzioniRequest>
</com:ComunicazioneMetadatiRichiesta>`

Response:
1144-Riferimento documento non valido; 1144-Riferimento documento non valido

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
la request utilizzata e' incompleta.
In allegato un esempio funzionante.
[request.txt](https://github.com/user-attachments/files/18019872/request.txt)

**Comment by avlp** [comment]
Salve, la request è stata corretta e la replace è stata accettata con ID TEMP_130_2995079. Si attende elaborazione esito.

**Comment by g-maugeri-sogei** [comment]
Buonasera,
la request non risulta valida.
