### ISSUE TITLE
Crash Program - Abruzzo Replace verso Basilicata

### ISSUE THREAD

**Issue by avlp** [ministero-salute/it-fse-support#1336]
Salve,
si riporta response di errore con codice 9999 nella replace in oggetto.
Ecco i dettagli:
RICERCA:
`<ric:RicercaDocumentiRichiesta xmlns:ric="http://ricercadocumentirichiesta.xsd.fse.ini.finanze.it">
	<ric:IdentificativoUtente>PROVAX00X00X000Y</ric:IdentificativoUtente>
	<ric:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</ric:pinCode>
	<ric:IdentificativoOrganizzazione>130</ric:IdentificativoOrganizzazione>
	<ric:StrutturaUtente>204123456</ric:StrutturaUtente>
	<ric:RuoloUtente>DRS</ric:RuoloUtente>
	<ric:ContestoOperativo>UPDATE</ric:ContestoOperativo>
	<ric:IdentificativoAssistito>PRVPVT81E03F052W</ric:IdentificativoAssistito>
	<ric:PresaInCarico>true</ric:PresaInCarico>
	<ric:StatoDocumento>Approved</ric:StatoDocumento>
	<ric:IdentificativoDocumento>2.16.840.1.113883.2.9.2.130.4.4^497378</ric:IdentificativoDocumento>
	<ric:IdentificativoApplicativoRichiedente>AREAS AMBWEB</ric:IdentificativoApplicativoRichiedente>
	<ric:FornitoreApplicativoRichiedente>Engineering Ingegneria Informatica SpA</ric:FornitoreApplicativoRichiedente>
	<ric:VersioneApplicativoRichiedente>20.15.00</ric:VersioneApplicativoRichiedente>
	<ric:OpzioniRisposta>ObjectRef</ric:OpzioniRisposta>
</ric:RicercaDocumentiRichiesta>`

Response ricerca: urn:uuid:2ff8b040-0206-426e-b685-190c8d9eb7f9

Invio Replace:
`<com:ComunicazioneMetadatiRichiesta xmlns:com="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it" xmlns:tip="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it">
	<com:IdentificativoUtente>PROVAX00X00X000Y</com:IdentificativoUtente>
	<com:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</com:pinCode>
	<com:IdentificativoOrganizzazione>130</com:IdentificativoOrganizzazione>
	<com:StrutturaUtente>204123456</com:StrutturaUtente>
	<com:RuoloUtente>DRS</com:RuoloUtente>
	<com:ContestoOperativo>TREATMENT</com:ContestoOperativo>
	<com:TipoDocumento/>
	<com:IdentificativoAssistito>PRVPVT81E03F052W</com:IdentificativoAssistito>
	<com:PresaInCarico>true</com:PresaInCarico>
	<com:TipoAttivita>CREATE</com:TipoAttivita>
	<com:Metadato>
		<tip:TipologiaStrutturaProdDoc>Ospedale</tip:TipologiaStrutturaProdDoc>
		<tip:TipoMime>application/pdf+text/x-cda-r2+xml</tip:TipoMime>
		<tip:LivelloConfidenzialita>N</tip:LivelloConfidenzialita>
		<tip:TipologiaDocumentoAlto>REF</tip:TipologiaDocumentoAlto>
		<tip:TipologiaDocumentoMedio>11488-4</tip:TipologiaDocumentoMedio>
		<tip:TipologiaDocumentoBasso>2.16.840.1.113883.2.9.10.1.9.1</tip:TipologiaDocumentoBasso>
		<tip:RiferimentoDocumento>urn:uuid:2ff8b040-0206-426e-b685-190c8d9eb7f9</tip:RiferimentoDocumento>
		<tip:Associazione>
			<tip:associationType>urn:ihe:iti:2007:AssociationType:RPLC</tip:associationType>
			<tip:sourceObject>doc1</tip:sourceObject>
			<tip:targetObject>urn:uuid:2ff8b040-0206-426e-b685-190c8d9eb7f9</tip:targetObject>
			<tip:submissionSetStatus>Original</tip:submissionSetStatus>
			<tip:previousVersion/>
		</tip:Associazione>
		<tip:IdentificativoUnivocoDocumento>doc1</tip:IdentificativoUnivocoDocumento>
		<tip:DataValidazioneDocumento>20241113053650</tip:DataValidazioneDocumento>
		<tip:RuoloAutore>DRS</tip:RuoloAutore>
		<tip:IstituzioneAutore>130204123456</tip:IstituzioneAutore>
		<tip:CodiceFiscaleAutore>PROVAX00X00X000Y</tip:CodiceFiscaleAutore>
		<tip:AssettoOrganizzativo>AD_PSC010</tip:AssettoOrganizzativo>
		<tip:TipoAttivitaClinica>DIS</tip:TipoAttivitaClinica>
		<tip:DataInizioPrestazione>20241113053650</tip:DataInizioPrestazione>
		<tip:DataFinePrestazione>20241113053650</tip:DataFinePrestazione>
		<tip:IdentificativoSottomissione/>
		<tip:DocumentoFirmato>true^Documento firmato</tip:DocumentoFirmato>
	</com:Metadato>
	<com:IdentificativoApplicativoRichiedente>AREAS AMBWEB</com:IdentificativoApplicativoRichiedente>
	<com:FornitoreApplicativoRichiedente>Engineering Ingegneria Informatica SpA</com:FornitoreApplicativoRichiedente>
	<com:VersioneApplicativoRichiedente>20.15.00</com:VersioneApplicativoRichiedente>
	<com:OpzioniRequest>
		<tip:chiave>GATEWAY</tip:chiave>
		<tip:valore>true</tip:valore>
	</com:OpzioniRequest>
	<com:OpzioniRequest>
		<tip:chiave>WORKFLOWINSTANCEID</tip:chiave>
		<tip:valore>2.16.840.1.113883.2.9.2.130.4.4.e5800a888d60c23b6f1961d3fb36f0fab18005a4c951dbeec407a8d0598647ea.648e87839b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId</tip:valore>
	</com:OpzioniRequest>
	<com:OpzioniRequest>
		<tip:chiave>MODE</tip:chiave>
		<tip:valore>ATTACHMENT</tip:valore>
	</com:OpzioniRequest>
</com:ComunicazioneMetadatiRichiesta>`

Response:
`<?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><a:ComunicazioneMetadatiRicevuta xmlns:a="http://comunicazionemetadatiricevuta.xsd.fse.ini.finanze.it" xmlns="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it" xmlns:b="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it"><a:Esito>9999</a:Esito><a:ElencoErrori><Errore><codEsito>9000</codEsito><esito>9999 - </esito><tipoErrore>Bloccante</tipoErrore><fonte>FSE-INS-GATEWAY</fonte></Errore></a:ElencoErrori></a:ComunicazioneMetadatiRicevuta></soapenv:Body></soapenv:Envelope>`

**Comment by vigliottim** [comment]
@BasilicataCrashProgramFSE

Buongiorno,
chiediamo gentilmente alla regione Basilicata, RDA di riferimento, di fornire supporto.
Grazie.

**Comment by vigliottim** [comment]
> @BasilicataCrashProgramFSE
> 
> Buongiorno, chiediamo gentilmente alla regione Basilicata, RDA di riferimento, di fornire supporto. Grazie.

Buonasera @BasilicataCrashProgramFSE,
invitiamo nuovamente la regione Basilicata a fornire supporto.
Grazie.

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,

Vediamo nei log solo la transazione di ricerca ITI-18 per lo uniqueID=2.16.840.1.113883.2.9.2.130.4.4^497378 con esito positivo.
Non troviamo traccia della transazione del replace: quindi l'errore sembra essere prima dell'invocazione del registry regionale come esplicita anche questo errore "**<fonte>FSE-INS-GATEWAY</fonte>**"

Notiamo un errore nella request della replace:

- manca Metadato.IdentificativoDocumento che deve essere valorizzato con DocumentEntry.UniqueID del nuovo documento che va a sostituire il vecchio (2.16.840.1.113883.2.9.2.130.4.4^497378)


A disposizione
Grazie

**Comment by vigliottim** [comment]
> Buongiorno,
> 
> Vediamo nei log solo la transazione di ricerca ITI-18 per lo uniqueID=2.16.840.1.113883.2.9.2.130.4.4^497378 con esito positivo. Non troviamo traccia della transazione del replace: quindi l'errore sembra essere prima dell'invocazione del registry regionale come esplicita anche questo errore "**FSE-INS-GATEWAY**"
> 
> Notiamo un errore nella request della replace:
> 
> * manca Metadato.IdentificativoDocumento che deve essere valorizzato con DocumentEntry.UniqueID del nuovo documento che va a sostituire il vecchio (2.16.840.1.113883.2.9.2.130.4.4^497378)
> 
> A disposizione Grazie

Buonasera @avlp,
potrebbe cortesemente darci un feedback?
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso in cui sia necessario ulteriore supporto.
Grazie.
