### ISSUE TITLE
Errore sul tentativo di Validazione CDA su VPN

### ISSUE THREAD

**Issue by rondellimediam** [ministero-salute/it-fse-support#1337]
Buongiorno,
premesso che il nostro software ha già superato l'accreditamento (prima fase) al FSE (Fornitore A1#111#MEDIAMX2 - Mediam Servizi srl - Linfa - 1.7.0.0), abbiamo la necessità di testare di testare la validazione del CDA sulla VPN di un cliente, in particolare su quella di Asl1 Liguria, questo perchè ci è stato imposto che il flusso sia il seguente:

1. Autenticazione al repository di Liguria Digitale
2. Invio dei dati di validazione a Liguria Digitale, che si occupa di interrogare il gateway
3. Risposta da Liguria Digitale

Il repository di Liguria Digitale è solo un tramite e quindi invia il messaggio che prepariamo noi, che differisce da quello "standard" solo per l'aggiunta del token di autenticazione verso loro. 
Allego il referto che inviamo, il messaggio CURL, mentre questo è il dettaglio dell'errore:

**Host fascicolosanitario-api-test.regione.liguria.it:443 was resolved.
* IPv6: (none)
* IPv4: 10.4.16.43
*   Trying 10.4.16.43:443...
* schannel: disabled automatic use of client certificate
* Recv failure: Connection was reset
* schannel: failed to receive handshake, SSL/TLS connection failed
* closing connection #0
curl: (35) Recv failure: Connection was reset**

Potreste aiutarci a capire il problema per favore?
[CURL validazione Liguria Digitale.txt](https://github.com/user-attachments/files/17901132/CURL.validazione.Liguria.Digitale.txt)
[XKR.pdf](https://github.com/user-attachments/files/17901135/XKR.pdf)

**Comment by vigliottim** [comment]
Buongiorno,
per risolvere il problema segnalato deve interfacciarsi con Liguria Digitale.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
