### ISSUE TITLE
Domanda generale sull'utilizzo da parte di laboratori privati

### ISSUE THREAD

**Issue by zaknet** [ministero-salute/it-fse-support#1338]
Buongiorno,
il nostro committente ci chiede come funziona questo sistema per quanto riguarda l'utilizzo da parte di laboratori privati. 
Mi spiego meglio: noi stiamo producendo l'interfaccia FSE per soddisfare l'apertura all'utilizzo del sistema FSE in Regione Toscana nell'ambito della sperimentazione per l'utilizzo da parte non di enti pubblici ma appunto di laborati privati.
La mia domanda è: secondo voi ci saranno differenze per quanto riguarda il contenuto dei file CDA, in considerazione del fatto che per esempio le prestazioni potrebbero essere non quelle classiche ospedaliere, o almeno non avere la stessa codifica? 
Magari, mi viene da pensare, potrebbero contenere anche minori informazioni? Mi viene per esempio in mente l'indicazione del reparto ospedaliero dove è stato eseguito l'esame, che credo che non sia una informazione rilevante per il laboratorio specialistico privato.
In linea generale quindi, ci sono delle differenze?

Grazie mille e cordiali saluti.

**Comment by vigliottim** [comment]
Buongiorno,
i CDA2 devono essere costruiti secondo le specifiche HL7 Italia anche nel caso di laboratori privati.
E' possibile fare riferimento alla colonna _"Obbligatorietà da IG"_ contenuta negli excel con le specifiche per l'accreditamento.
Ad esempio, nel caso di CDA2 di tipo LAB, all'interno del file [Test Case/Validazione/5-Referto di Medicina di Laboratorio/CDA2_Referto Medicina di Laboratorio_OK.xlsx](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/5-Referto%20di%20Medicina%20di%20Laboratorio/CDA2_Referto%20Medicina%20di%20Laboratorio_OK.xlsx) può trovare le indicazioni necessarie per strutturare il CDA2 con i campi obbligatori secondo HL7 Italia facendo riferimento alla colonna evidenziata in figura:

<img width="649" alt="image" src="https://github.com/user-attachments/assets/2637cf29-6272-4765-90d9-1be20be6b9ea">

Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by zaknet** [comment]
D'accordo grazie, nel caso la disturbo ancora.
Cordiali saluti
