### ISSUE TITLE
Errore Accreditamento FILE_DICHIARATO_NON_PRESENTE del Fornitore [S1#111ONIT0000000] - Vendor:[OnitGroup] - ID: [OnVac] - Version: [V.4.43.0.0] 

### ISSUE THREAD

**Issue by Fusarolia** [ministero-salute/it-fse-support#134]
Buongiorno
nell'accreditamento otteniamo il seguente errore
  "error" : "FILE_DICHIARATO_NON_PRESENTE",
  "description" : "File dichiarato nel test non presente nella folder FILES.:CERT_VAC_CT1.PDF"

il problema può essere dovuto alla scrittura del nome file in data.json e nome della cartella Files?
Mi spiego nel file data.json è  CERT_VAC_CT1.PDF mentre nella cartella files il file è CERT_VAC_CT1.pdf (differenza di scrittura dell'estensione? o altro

Attendo un riscontro al più presto, grazie

**Comment by IStacchiotti** [comment]
Buongiorno, la modifica è stata recepita. Seguiranno nuovi aggiornamenti via email. Grazie

**Comment by masciamariotti** [comment]
Procediamo alla chiusura della presente issue, in quanto è stata aperta la #142
