### ISSUE TITLE
crash-program. stato documento ancora in elaborazione

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#1348]
buonasera,
il documento pubblicato la settimana scorsa afferente al CF CQTDLT66H01Z356V (regione liguria) con 
workflowInstanceId
2.16.840.1.113883.2.9.2.130202.4.4.313184f9cde5335757df7c0195c1f432bb38a398c86081f90605e464e1d6b8d4.5d80ff9f2b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId e pubblicato il 22/11/2024 risulta ancora in stato di elaborazione, mentre dallo status del Gtw risulta correttamente pubblicato
Questo non permette di procedere con il test di sostituzione.

grazie

**Comment by izamberlan** [comment]
Se l'id documento è 2.16.840.1.113883.2.9.2.130.4.4^501132 da noi risulta indicizzato

**Comment by alessandropassamonti** [comment]
@LucaRogledi può controllare?

**Comment by alessandropassamonti** [comment]
buonasera
anche se lo status del Gtw indica che il documento è pubblicato, Il problema c'è ancora perchè
lo stato dell'elaborazione della comunicazioneMetadati risulta in ELAB


```
<EsitoCaricamentoDocumentoRicevuta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Esito xmlns="http://esitocaricamentodocumentoricevuta.xsd.fse.ini.finanze.it">0000</Esito>
  <EsitoCaricamentoDocumento xmlns="http://esitocaricamentodocumentoricevuta.xsd.fse.ini.finanze.it">
    <IdentificativoTemporaneoDocumento xmlns="http://tipodatiesitocaricamentodocumento.xsd.fse.ini.finanze.it">TEMP_130_2471111</IdentificativoTemporaneoDocumento>
    <StatoElaborazione xmlns="http://tipodatiesitocaricamentodocumento.xsd.fse.ini.finanze.it">ELAB</StatoElaborazione>
  </EsitoCaricamentoDocumento>
  <ElencoErrori xmlns="http://esitocaricamentodocumentoricevuta.xsd.fse.ini.finanze.it">
    <Errore xmlns="http://tipodatiesitocaricamentodocumento.xsd.fse.ini.finanze.it">
      <codEsito>0000</codEsito>
      <esito>Operazione eseguita correttamente</esito>
      <tipoErrore>Success</tipoErrore>
      <fonte>FSE-INS-FE</fonte>
    </Errore>
  </ElencoErrori>
</EsitoCaricamentoDocumentoRicevuta>

```
https://fseservicetest.sanita.finanze.it/FseInsServicesWeb/services/fseEsitoCaricamentoDocumento

Questo non permette di eseguire i test di sostituzione
Dovreste controllare perchè non ritorna stato OK,
Vi prego di riaprire la issue

Grazie

**Comment by g-maugeri-sogei** [comment]
Anche per questa issue il documento risulta correttamente pubblicato.

**Comment by alessandropassamonti** [comment]
buongiorno,
@g-maugeri-sogei  purtroppo esitoCaricamentoDocumento ritorna ancora ELAB

**Comment by g-maugeri-sogei** [comment]
Posso avere la request e la response con cui viene fatta la verifica?
Sul DB lo stato del documento e' corretto.

**Comment by alessandropassamonti** [comment]
@g-maugeri-sogei  risulta pubblicato, ho confuso i documenti
grazie
