### ISSUE TITLE
Crash Program - Bolzano vs Toscana

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#1349]
Buongiorno,
come detto in riunione trovo difficile capire come possa essere fatto un controllo sull'autore del documento.
Ad ogni buon conto, se l'author person viene prelevato dal CDA non abbiamo modo di produrre un documento con il CF richiesto. Prego quindi la toscana di girarci un documento con il body coerente per la richiesta di pubblicazione.

Grazie

**Comment by vigliottim** [comment]
Buongiorno @Gianpr0, @OmarLorenzini,
chiediamo cortesemente alla regione Toscana, RDA di riferimento, di fornire supporto.
Grazie.

**Comment by cdezorzi** [comment]
Buon pomeriggio
in allegato il file.
Attendiamo Vs riscontro.
Grazie

[LAB-MNTMRA03M71C615V-PROVAX00X00X000Y_signed.pdf](https://github.com/user-attachments/files/17949020/LAB-MNTMRA03M71C615V-PROVAX00X00X000Y_signed.pdf)

**Comment by SonnyMate** [comment]
Grazie ora va in errore la delete

        {
            "eventType": "INI_DELETE",
            "eventDate": "2024-12-02T15:14:51.457+01:00",
            "eventStatus": "ASYNC_RETRY",
            "message": "Transazione presa in carico",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_111000000001",
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "041",
            "workflowInstanceId": "0668b2dd4a9dea9e71bfcc0fbc3d509f36a86e1017dcea9995edbdd73ca38bd0.1e1f5ac0b6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "8285dbfbdbd3f0af",
            "issuer": "integrity:S2#041#PABOLZANOTEST",
            "expiringDate": "2025-12-02T15:14:51.486+01:00"
        },
        {
            "eventType": "DESERIALIZE",
            "eventDate": "2024-12-02T15:14:51.468+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "{\"idDoc\":\"2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_111000000001\",\"uuid\":[\"Document1\"],\"sub\":\"PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO\",\"iss\":\"integrity:S2#041#PABOLZANOTEST\",\"subject_organization\":\"P.A. Bolzano\",\"subject_organization_id\":\"041\",\"locality\":\"LABORATORIO DI PROVA^^^^^&2.16.840.1.113883.2.9.4.1.3&ISO^^^^111101123456\",\"subject_role\":\"AAS\",\"person_id\":\"MNTMRA03M71C615V^^^&2.16.840.1.113883.2.9.4.3.2&ISO\",\"purpose_of_use\":\"UPDATE\",\"action_id\":\"DELETE\",\"resource_hl7_type\":\"('11502-2^^2.16.840.1.113883.6.1')\",\"patient_consent\":true,\"documentType\":\"UNKNOWN_DOCUMENT_TYPE\",\"subject_application_id\":\"CONCERTO\",\"subject_application_vendor\":\"DEDALUS SPA\",\"subject_application_version\":\"22.1.1\",\"workflow_instance_id\":\"0668b2dd4a9dea9e71bfcc0fbc3d509f36a86e1017dcea9995edbdd73ca38bd0.1e1f5ac0b6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId\",\"administrative_request\":[],\"author_institution\":\"UNKNOWN_AUTHOR_INSTITUTION\"}",
            "workflowInstanceId": "0668b2dd4a9dea9e71bfcc0fbc3d509f36a86e1017dcea9995edbdd73ca38bd0.1e1f5ac0b6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-12-02T15:14:51.690+01:00"
        }
    ]
}

**Comment by vigliottim** [comment]
Buonasera @Gianpr0, @OmarLorenzini, @cdezorzi,
chiediamo nuovamente alla regione Toscana, RDA di riferimento, di fornire supporto. Grazie.

**Comment by Gianpr0** [comment]
Buongiorno,
abbiamo rilasciato la fix sull'uuid per l'iti-18.
Vi richiediamo di fare un nuovo giro di test dalla create.
Grazie

**Comment by vigliottim** [comment]
Buonasera @SonnyMate,
chiediamo cortesemente di effettuare un nuovo test dopo il rilascio della fix.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Potrà essere riaperta nel caso in cui sia necessario ulteriore supporto.
Grazie.
