### ISSUE TITLE
Mancato Accreditamento - TEST_NON_PRESENTE

### ISSUE THREAD

**Issue by ALEsposito-MCI** [ministero-salute/it-fse-support#135]
Buongiorno,

in seguito alla richiesta di accreditamento abbiamo ricevuto come risposta questo log di errore:

```
[ {
  "error" : "TEST_NON_PRESENTE",
  "description" : "Test mancanti rispetto alla checklist:[9]"
} ]
```

Questo nonostante avessimo specificato la non applicabilità del caso (test case ID 9, LDO) per il nostro applicativo in quanto non vengono gestiti alcuni campi opzionali (inserito "NO" nella colonna Applicabilità e dato una spiegazione in "Razionale di applicabilità").

Come suggerito inoltro anche relativi dati della nostra richiesta di accreditamento:

subject_application_vendor: MEDIACLINICS ITALIA
subject_application_id: MargheritaTre
subject_application_version: V.3.3.0

Come dobbiamo muoverci?

Vi ringrazio in anticipo per la disponibilità e pazienza.

**Comment by masciamariotti** [comment]
Grazie della segnalazione. I casi di test sviluppati per la fase di accreditamento lato validazione sono stati pensati nel seguente modo:
• Caso di test 1 -> solo le sezioni obbligatorie da specifiche HL7
• Caso di test 2 – Caso di test 3 -> sezioni obbligatorie da specifiche HL7 e per questi casi specifici inserite sezioni opzionali da specifiche ma che sono necessarie e che devono essere inserite per poter superare la fase di validazione
• Caso di test 4 -> sezioni obbligatorie da specifiche HL7 e tutte le sezioni opzionali per questo caso specifico che è quello completo e le prevede tutte
Di conseguenza nel word si ha il dettaglio degli elementi ad un livello alto, mentre nel file excel fornito si ha l’intero dataset, con tutti i path che vengono controllati e la corretta valorizzazione degli elementi, pur mantenendo le cardinalità e le obbligatorietà espresse nelle specifiche poiché la completezza delle informazioni rimane affine alle specifiche HL7 Italia ma per i nostri test cases vengono evidenziate in verde per sottolineare il loro inserimento.

**Comment by ALEsposito-MCI** [comment]
Grazie mille per la risposta.

Ne approfitto per chiedere quindi come dovremmo muoverci. Dobbiamo segnarli come non applicabili e non passarli al gateway (andando a modificare file json di risposte ed excel)?

Per quanto riguarda invece la questione dei codici ICD9, invece?

Vi ringrazio ancora per la pazienza e disponibilità.

**Comment by IStacchiotti** [comment]
Buon pomeriggio, come spiegato nei word forniti per ciascuna tipologia documentale, i casi di test 2 e 3 sono casi d’uso specifici pensati per la realizzazione di casi reali. La riproduzione di questi ultimi comporta l’inserimento sia delle sezioni obbligatorie da specifiche HL7 Italia sia di alcune sezioni opzionali che consentono di fornire ulteriori informazioni e consentire un caso d’uso completo.
Nei file excel, le sezioni opzionali sono state evidenziate in verde per sottolineare la necessità di inserirle e di conseguenza di valorizzarle come indicato.

Per quanto riguarda l’errore generato per la valorizzazione errata del codice (Cercando anche online risulta che il codice ICD9 per la broncopneumopatia è 491.21, mentre il codice 300.01 fa riferimento ai disturbi di panico), non sono presenti i codici da lei menzionati nell’excel fornito per la valorizzazione dell’elemento value dell’entry/observation della sezione Motivo_Ricovero. Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
