### ISSUE TITLE
Delete Sardegna vs Marche

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#1354]
Buongiorno,

a seguito di una Delete, di cui riportiamo i dettagli:
```
traceId : 6749d2a8745c1aa7408ae0c3bc25b2b0
DocumentID: 2.16.840.1.113883.2.9.2.200.4.4^200106PRFSRA93C69A252A20241129153652426956
```
otteniamo come esito stato transazione : 
`ASYNC_RETRY `

Potete verificare, grazie

**Comment by vigliottim** [comment]
@Didi22515

Buonasera,
invitiamo gentilmente la regione Marche a fornire supporto.
Grazie.

**Comment by FSESardegna** [comment]
Buongiorno,

abbiamo effettuato una nuova operazione di eliminazione. Di seguito i dettagli:

Trace ID: 6756ad7c6e502537a4bc6a69d38df4b2
Doc ID: 2.16.840.1.113883.2.9.2.200.4.4^200106PRFSRA93C69A252A20241209093807693732
L'operazione si è conclusa con esito positivo.

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Grazie
