### ISSUE TITLE
crash-program. errore sostituzione documento verso regione LAzio

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#1355]
Buonasera,
la sostituzione del documento del CF AAAEEE01A01H501Q genera l'errore

`SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:ORA-01653: unable to extend table FSEOWNR.XDS_REGISTRY by 1024 in tablespace TSD_FSEOWNR_`

il workflowInstanceId
2.16.840.1.113883.2.9.2.130202.4.4.3ef082de90b934c301462cb8800864b4b7a55badc059f9ab87c529cce88dc0be.3d13569c64^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
l'errore sembrerebbe sul DB della RDA. Puo' la regione Lazio verificare e darci riscontro?

**Comment by vigliottim** [comment]
Buonasera @giosil ,
chiediamo gentilmente alla regione Lazio, RDA interessata, di fornire supporto.
Grazie

**Comment by giosil** [comment]
Il problema è stato risolto.

**Comment by vigliottim** [comment]
Grazie per il gentile riscontro.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
