### ISSUE TITLE
Modifica vendor di un applicativo accreditato

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#1357]
Buongiorno, avrei bisogno di un chiarimento.
Se un integratore, dopo aver regolarmente accreditato uno o più applicativi, modifica la propria ragione sociale, per esempio da ditta individuale ad Srl, cosa deve fare per mantenere l'accreditamento ottenuto, fermo restando che tutto il resto rimane invariato?
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, 
per modificare la propria ragione sociale dovrà inviare una richiesta, come nell'issue #910.
Grazie.

**Comment by infoserviceonline** [comment]
Buongiorno, nella issue indicata c'è solo una conferma di avvenuta modifica, ma nello specifico come va redatta la richiesta ed a chi va inviata?
Nel caso citato era un passaggio da Srl a Spa, nel mio caso non potrà essere da ditta individuale a Srl, poichè Infoservice Srl esiste già, quindi sarà da Infoservice di Francesco Leo a Pinco Pallino S.r.l..
Grazie.

**Comment by vigliottim** [comment]
Può aprire una issue e inoltreremo la sua richiesta al team di competenza.
Grazie.
