### ISSUE TITLE
Errore Accreditamento FILE_DICHIARATO_NON_PRESENTE del Fornitore [A1#111INFONEXT000] - Vendor:[Infonext S.r.l] - ID: [eVac] - Version: [V.3.0.0]

### ISSUE THREAD

**Issue by amathos80** [ministero-salute/it-fse-support#136]
Salve,
durante la procedura di accreditamento non è stato possibile procedere in quanto abbiamo ricevuto da voi un report riguardante files mancanti.
Nel report tutti gli errori sono di questo tipo:
"error" : "FILE_DICHIARATO_NON_PRESENTE",
"description" : "File dichiarato nel test non presente nella folder FILES.:CERT_VAC_CT1_OK.PDF"

I files risultano però essere presenti. L'unica differenza è il lower case nell'estensione dei files contenuti nella cartella rispetto alla medesima in upper case nel file data.json.
E' questo il problema che genera l'errore o c'è altro? 

Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno,
potrebbe cortesemente eseguire una nuova commit modificando le estensioni dei file in UPPERCASE nel data json?
Seguirà un'evolutiva del software per prevenire problematiche analoghe.
Grazie.

**Comment by amathos80** [comment]
Grazie mille, corretto ed aperta nuova PR.

**Comment by IStacchiotti** [comment]
Buon pomeriggio, la presente viene chiusa come risolta. Seguiranno aggiornamenti via email in merito alla pull request. Si può procedere con la riapertura del ticket nel caso fosse necessario ulteriore supporto. Grazie
