### ISSUE TITLE
ProvAutoTrento - Crash Program - UC5 con RDA=Valle D'Aosta

### ISSUE THREAD

**Issue by nicola-ferrari-threadsolutions** [ministero-salute/it-fse-support#1362]
Buongiorno,

abbiamo fatto una chiamata UC5 ma riceviamo il seguente errore
```

{
  "traceID": "250873a6e8376257",
  "spanID": "250873a6e8376257",
  "type": "/msg/generic-error",
  "title": "Errore generico.",
  "detail": "Index: 0, Size: 0",
  "status": 500,
  "instance": ""
}

```

Potete verificare per favore?

Grazie 
CC @apsstn

**Comment by vigliottim** [comment]
Buonasera @assistenza-fsevda,
chiediamo gentilmente alla regione Valle d'Aosta di verificare effettuando il recupero riferimenti.
Grazie.

**Comment by assistenza-fsevda** [comment]
Bongiorno @nicola-ferrari-threadsolutions,
sarebbe possibile effettuare una nuova prova per poi fornirci gli uniqueId dei documenti coinvolti (originale e quello con cui lo si vuole sostiruire)? Ieri abbiamo in effetti avuto dei disservizi a causa di alcuni rilasci nell'ambiente di test e sarebbe utile avere dei casi puliti da verificare.

Grazie mille.

**Comment by apsstn** [comment]
Buonasera, siamo riusciti a chiudere tutti gli UC verso di voi. Chiedo scusa per non aver visto la comunicazione prima

Grazie per la collaborazione

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Grazie
