### ISSUE TITLE
ProvAutoTrento - Crash Program - UC3 con RDA=Friuli Venezia Giulia

### ISSUE THREAD

**Issue by nicola-ferrari-threadsolutions** [ministero-salute/it-fse-support#1363]
Buongiorno,

abbiamo appena effettuato una chiamata verso il GTW ma riceviamo la seguente

```

{
  "status": 500
}

```
La request effettuata è la sequente
```


PUT /govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.42.4.4%5ESIO.REF.2024.900001910.1/metadata

Content-Type: application/json; charset=UTF-8
Content-Length: 371

{
  "tipologiaStruttura": "Ospedale",
  "attiCliniciRegoleAccesso": [
    "P99"
  ],
  "tipoDocumentoLivAlto": "REF",
  "assettoOrganizzativo": "AD_PSC052",
  "dataInizioPrestazione": "20241119102300",
  "dataFinePrestazione": "20241119105300",
  "tipoAttivitaClinica": "CON",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.2.42.4.3.SIO.REF.2024.900001910.1.1"
}

```

Potete verificare?
Grazie
cc @apsstn

**Comment by vigliottim** [comment]
Buongiorno,
potrebbe allegare la response completa comprensiva di trace_id/govway_id dove presente?
Grazie.

**Comment by nicola-ferrari-threadsolutions** [comment]
Ciao @vigliottim 

La response è esattamnente quella fornita ovvero 

{
  "status": 500
}


Grazie

**Comment by vigliottim** [comment]
Buongiorno,
chiudiamo la presente issue in quanto considerata duplicata della #1361.
L'errore riscontrato dovrebbe essere causato dalla chiamata effettuata e non dalla regione RDA.
Ulteriori aggiornamenti saranno pubblicati nel thread #1361.
Grazie.
