### ISSUE TITLE
ProvAutoTrento - Crash Program - UC5 con RDA=Friuli Venezia Giulia

### ISSUE THREAD

**Issue by nicola-ferrari-threadsolutions** [ministero-salute/it-fse-support#1364]
Buongiorno,

abbiamo fatto una chiamata UC5 ma riceviamo il seguente errore
```

{
  "traceID": "ca3c789a68a75821",
  "spanID": "ca3c789a68a75821",
  "type": "/msg/generic-error",
  "title": "Errore generico.",
  "detail": "Index: 0, Size: 0",
  "status": 500,
  "instance": ""
}

```

Potete verificare per favore?

Grazie
CC @apsstn

**Comment by LucaRogledi** [comment]
Buonasera @ChiaraCeccottiFVG ,
chiediamo gentilmente alla regione Friuli Venezia Giulia di verificare effettuando il recupero riferimenti.
Grazie.

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
sarebbe possibile avere il doc id del documento per agevolare le verifiche?
Grazie mille, buona giornata.

**Comment by apsstn** [comment]
Salve, chiuderei questa issue per passare su quella attiva: https://github.com/ministero-salute/it-fse-support/issues/1379

**Comment by LucaRogledi** [comment]
Buongiorno, procediamo con la chiusura della presente issue come richiesto. Grazie
