### ISSUE TITLE
ProvAutoTrento - Crash Program - UC3 con RDA=Liguria

### ISSUE THREAD

**Issue by nicola-ferrari-threadsolutions** [ministero-salute/it-fse-support#1367]
Buongiorno,

abbiamo appena effettuato una chiamata verso il GTW ma riceviamo la seguente
```

{
  "traceID": "5c4356092472b0f6",
  "spanID": "45f0730a291d9de2",
  "type": "/errors",
  "title": "Generic",
  "detail": "",
  "instance": "error/generic"
}

```
La request effettuata è la sequente
```

PUT /govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.42.4.4%5ESIO.REF.2024.900001906.1/metadata

Content-Type: application/json; charset=UTF-8
Content-Length: 371

{
  "tipologiaStruttura": "Ospedale",
  "attiCliniciRegoleAccesso": [
    "P99"
  ],
  "tipoDocumentoLivAlto": "REF",
  "assettoOrganizzativo": "AD_PSC052",
  "dataInizioPrestazione": "20241119102300",
  "dataFinePrestazione": "20241119105300",
  "tipoAttivitaClinica": "CON",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.2.42.4.3.SIO.REF.2024.900001906.1.1"
}

```

Potete verificare?

cc @apsstn

**Comment by izamberlan** [comment]
Verificate che l'identificativo del repository sia un oid, i gruppi di numeri non possono iniziare per 0 (zero) a meno che non siano costituiti dal solo 0. Non so se sia questo il caso, ma vedo che abbiamo rifiutato indicizzazioni da 042 perché l'id del repository è 2.16.840.1.113883.2.9.2.42.4.5.0001 (lo 0001 non è conforme alla specifica degli oid).

**Comment by apsstn** [comment]
Buongiorno, grazie per l'hint proveremo modificandolo. Non capiamo però perché UC1 (inserimento) sia stato accettato mentre UC3 no

**Comment by izamberlan** [comment]
Credo di vedere UC1, che mi risulta in errore alle 11:35 del 30/11 su id documento 2.16.840.1.113883.2.9.2.42.4.4^SIO.REF.2024.900001906.1.
Non mi pare ci siano altre richieste pervenute al layer applicativo.
In ogni caso, se state tentando la sostituzione di un documento con uno con lo stesso identificativo il nostro sistema rifiuta questo tipo di transazione, in conformità con le specifiche IHE, ma è un altro problema.

**Comment by apsstn** [comment]
Buongiorno, abbiamo ripubblicato UC1 che ci risulta ora essere indicizzato correttamente. Potreste confermarcelo per favore?

Per UC3 (aggiornamento) manteniamo lo stesso identificativo, che invece viene cambiato in caso di UC5 (sostituzione)

**Comment by izamberlan** [comment]
Ahm, sì, mi si erano incrociati i casi d'uso. Confermo indicizzazione OK lato nostro.

**Comment by izamberlan** [comment]
Confermo UC3 OK
Grazie a voi
