### ISSUE TITLE
ProvAutoTrento - Crash Program - UC3 con RDA=Emilia Romagna

### ISSUE THREAD

**Issue by nicola-ferrari-threadsolutions** [ministero-salute/it-fse-support#1368]
Buongiorno,

abbiamo appena effettuato una chiamata verso il GTW ma riceviamo la seguente
```

{
  "traceID": "59ed6d56f980e41b",
  "spanID": "a74247222662e2ab",
  "type": "/errors",
  "title": "Generic",
  "detail": "it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.",
  "instance": "error/generic"
}

```

La request effettuata è la sequente

```

PUT /govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.42.4.4%5ESIO.REF.2024.900001911.1/metadata

Content-Type: application/json; charset=UTF-8
Content-Length: 371

{
  "tipologiaStruttura": "Ospedale",
  "attiCliniciRegoleAccesso": [
    "P99"
  ],
  "tipoDocumentoLivAlto": "REF",
  "assettoOrganizzativo": "AD_PSC052",
  "dataInizioPrestazione": "20241119102300",
  "dataFinePrestazione": "20241119105300",
  "tipoAttivitaClinica": "CON",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.2.42.4.3.SIO.REF.2024.900001911.1.1"
}

```

Potete verificare?

Grazie CC @apsstn

**Comment by apsstn** [comment]
Aggiornamento: abbiamo riprovato inserimento UC1 e aperto issue: https://github.com/ministero-salute/it-fse-support/issues/1376

**Comment by vigliottim** [comment]
@FSE-Emilia-Romagna @daniele-gubellini

Buon pomeriggio,
chiediamo cortesemente alla regione Emilia Romagna, RDA di riferimento, di fornire supporto.
Grazie.

**Comment by daniele-gubellini** [comment]
Salve,
prevediamo di implementare l'aggiornamento metadati solo con la nuova ITI 57.

**Comment by LucaRogledi** [comment]
Buonasera,
chiudiamo la presente issue poiché in attesa del rilascio della ITI-57.
Sarà possibile riaprire la presente issue oppure aprirne una nuova, una volta che saranno aperte le verifiche riguardanti la ITI-57, in caso si dovessero riscontrare problemi.
Grazie
