### ISSUE TITLE
ProvAutoTrento - Crash Program - UC3 con RDA=Molise

### ISSUE THREAD

**Issue by nicola-ferrari-threadsolutions** [ministero-salute/it-fse-support#1371]
Buongiorno,

abbiamo appena effettuato una chiamata verso il GTW ma riceviamo la seguente
```

{
  "traceID": "f8864673f68633c3",
  "spanID": "353c1fc581ff636d",
  "type": "/errors",
  "title": "Generic",
  "detail": "",
  "instance": "error/generic"
}

```

Potete verificare?

Grazie

cc @apsstn

**Comment by vigliottim** [comment]
Buongiorno,
chiudiamo la presente issue in quanto considerata duplicata della https://github.com/ministero-salute/it-fse-support/issues/1367.
Ulteriori aggiornamenti saranno pubblicati nel thread https://github.com/ministero-salute/it-fse-support/issues/1367.
Grazie.
