### ISSUE TITLE
ProvAutoTrento - Crash Program - UC1 con RDA=Lazio

### ISSUE THREAD

**Issue by apsstn** [ministero-salute/it-fse-support#1372]
Buongiorno, l'inserimento documento previsto da UC1 ci torna questo errore, credo dalla RDA:

`SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:ORA-01653: unable to extend table FSEOWNR.XDS_REGISTRY by 1024 in tablespace TSD_FSEOWNR_1`

Potreste verificare per favore?

**Comment by LucaRogledi** [comment]
Buongiorno @giosil ,
chiediamo gentilmente alla regione Lazio, RDA interessata, di fornire supporto.
Grazie

**Comment by giosil** [comment]
Il problema riscontrato è stato risolto.

**Comment by LucaRogledi** [comment]
Buonasera, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Grazie
