### ISSUE TITLE
ProvAutoTrento - Crash Program - UC1 con RDA=Molise

### ISSUE THREAD

**Issue by apsstn** [ministero-salute/it-fse-support#1373]
Buongiorno, l'esecuzione del UC1 verso Regione Molise ma la chiamata get status per il "SEND_TO_INI" ci torna questo errore:

`SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R56CODE CONTEXT:Wrong format data of display name for DocumentEntry.typeCode (Document1)`

Potreste verificare cortesemente?

**Comment by marlagatta** [comment]
Salve.
La motivazione dell'errore di validazione ritornato dalla ITI-42 e' lo stesso di cui all'issue [1147](https://github.com/ministero-salute/it-fse-support/issues/1147), ancora aperta e per cui siamo in attesa di aggiornamenti:

Da specifiche [Affinity Domain](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20interoperabilit%C3%A0/AffinityDomainItalia_v2-5_v20231212.pdf) il metadato XDSDocumentEntry.typeCode, Tabella 2.19-1 a pagina 29, prevede per il loinc "11488-4" la descrizione "Referto specialistico", e da specifiche di [Interoperabilità](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20interoperabilit%C3%A0/FrameworkEDatasetDeiServiziBase_v2-5_20231212_0.pdf) Tabella 54 a pagina 152, è prevista l'emissione dell'errore R56 per un valore errato di detta descrizione.

Per effettuare con successo il caso di Test verso il Molise, si suggerisce di cambiare tipologia documentale

**Comment by apsstn** [comment]
Buongiorno, abbiamo cambiato tipologia documentale inviando un VRB di Pronto Soccorso. L'esito però è negativo, questa la response tornata ai nostri sistemi:

`{
    "workflowInstanceId": null,
    "spanID": null,
    "codFiscaleRichiedente": "PRVMDC70A01H501L",
    "errorMessage": "/assettoOrganizzativo AD_PSC004 is not a valid enum value",
    "errorDescription": null,
    "trackingId": "8210cb38-64a0-4215-9bba-174b1e77510f",
    "esito": "KO",
    "request": "POST /documenti"
}`

AD_PSC004 è definito dal documento di Affinity Domain, per quale motivo non viene accettato? Abbiamo provato anche con AD_PSC106, ha generato un errore diverso ma sempre esito KO.

**Comment by apsstn** [comment]
Buongiorno @vigliottim abbiamo provato con un verbale di pronto soccorso ma ora ci torna un nuovo errore. Ci aiutereste a capire per cortesia?

- workflowInstanceId: 2.16.840.1.113883.2.9.2.42.4.4.08273c1aeec76c450c5f1348c67e22a816687c0a0ca065a9caa279e3d0928c7a.0f44379f15^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
- errore: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R55CODE CONTEXT:Wrong value of DocumentEntry.practiceSettingCode (Document1

Abbiamo indicato AD_PSC004 essendo il AD_PSC106 ora deprecato

**Comment by vigliottim** [comment]
Buonasera,
chiediamo una gentile verifica alla regione Molise, RDA di riferimento.
Grazie.

**Comment by marlagatta** [comment]
Salve. 
Potreste cortesemente riprovare? Il practiceSettingCode  AD_PSC004  e' ora gestito.

**Comment by apsstn** [comment]
Salve, inserimento andato a buon fine. Grazie per la collaborazione
