### ISSUE TITLE
ProvAutoTrento - Crash Program - UC1 con RDA=Puglia

### ISSUE THREAD

**Issue by apsstn** [ministero-salute/it-fse-support#1374]
Buongiorno, l'esecuzione del UC1 verso Regione Puglia ma la chiamata get status per il "SEND_TO_INI" ci torna questo errore:

`SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.`

Potreste verificare cortesemente?

**Comment by lninnova** [comment]
Buonasera, abbiamo rilasciato nuovamente la versione con il workaround che risolve provvisoriamente il problema esposto nella issue #1147 
Potete riprovare e darci conferma che la pubblicazione va a buon fine?
Grazie

**Comment by nicola-ferrari-threadsolutions** [comment]
Buonasera @lninnova 

Funziona
```

{
                "tipologia": "SEND_TO_INI",
                "data": "2024-12-03T18:04:22.929+01:00",
                "stato": "SUCCESS",
                "message": null,
                "identificativoDocumento": null,
                "soggetto": null,
                "ruoloSoggetto": null,
                "tipoAttivita": null,
                "organizzazione": null,
                "workflowInstanceId": "2.16.840.1.113883.2.9.2.42.4.4.e116b43d2276f7e326b8cc8bb271e794a12bea4c2c211b72ba1b809bac482fa9.d4e2270649^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
                "traceId": null,
                "issuer": null,
                "dataScadenza": "2025-12-03T18:04:22.939+01:00"
            }


```

Grazie 

@apsstn

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Grazie
