### ISSUE TITLE
PA Trento - Errore UC1 con RDA=Regione Emilia Romagna

### ISSUE THREAD

**Issue by apsstn** [ministero-salute/it-fse-support#1376]
Buongiorno, questa mattina abbiamo inviato un documento per l'indicizzazione come da UC1 ottenendo però un errore.

- trackingID: 2ee80e4c-18e2-4eca-b976-14a69fe281d3	
- spanID: f734fdd48afe814c	workflowInstanceId: 2.16.840.1.113883.2.9.2.42.4.4.972b7fbec4faa6c65f754301255f23c2f8476ca19ccb7b47e18012f404f54829.df39774ecc^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

L'errore ritornato è il seguente:

> SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R80CODE CONTEXT:Wrong value of DocumentEntry.uniqueId

Potreste verificare per cortesia?

**Comment by vigliottim** [comment]
@FSE-Emilia-Romagna @daniele-gubellini

Buon pomeriggio,
chiediamo cortesemente alla regione Emilia Romagna, RDA di riferimento, di fornire supporto.
Grazie.

**Comment by daniele-gubellini** [comment]
Salve,
è stata fatta una comunicazione metadati per il documento con codice 2.16.840.1.113883.2.9.2.42.4.4^SIO.REF.2024.900001911.1 che è già sul nostro indice (inserito il 30-NOV-24 11:35:45)

**Comment by apsstn** [comment]
Salve, grazie per la collaborazione. Abbiamo provveduto ad indicizzare un nuovo documento su cui proveremo poi UC5
