### ISSUE TITLE
PA Trento - Errore UC5 con RDA=Regione FVG

### ISSUE THREAD

**Issue by apsstn** [ministero-salute/it-fse-support#1379]
Buongiorno, UC5  provato questa mattina fallisce con errore:

`SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryDeprecatedDocumentErrorCODE CONTEXT:XDS Deprecated Document Error: The following registry objects were referenced by this submission but are not present, as Approved documents, in the registry: [urn:uuid:e64676f3-9895-4dea-8e58-8001ebcd76c4]`

UC1 ed UC3 sembrano essere andati a buon fine.
Potreste verificare per cortesia ed aiutarci a comprendere il motivo dell'errore?

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
abbiamo verificato il caso. 
Il documento che si sta cercando di sostituire (document ID 2.16.840.1.113883.2.9.2.42.4.4^SIO.REF.2024.900002006.1) è stato in precedenza versionato.
E' presente quindi una versione Deprecata del documento e una versione in stato Approved, e successivamente si sta cercando di sostituire il documento. 
Andando ad eseguire la query per la sostituzione con il document id 2.16.840.1.113883.2.9.2.42.4.4^SIO.REF.2024.900002006.2 vengono restituiti entrambi sia l'UUID del deprecato che quello in stato approved.
Quello con urn:uuid:e64676f3-9895-4dea-8e58-8001ebcd76c4 è deprecato
quello con urn:uuid:872a4e0c-0470-4294-b473-d9ae5fc54ddd è approved.
In questo caso restituiamo entrambi, possiamo prevedere una modifica per restituire solamente quelli in stato approved ma probabilmente sarebbe meglio prima condividere e valutare con tutte le regioni la soluzione per questa casistica specifica in modo da applicare tutte un comportamento omogeneo. 
Grazie e buona giornata.

**Comment by apsstn** [comment]
Buongiorno @ChiaraCeccottiFVG ma è stato versionato a seguito del UC3 (aggiornamento metadati)?

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno, 
ci sembrerebbe di si. 
Ci corregga pure se non le sembra corretto.
Grazie

**Comment by apsstn** [comment]
Chiedo a @LucaRogledi se il Gateway effettui la ITI-18 ricercando solo i documenti in stato 'Approved'. A memoria dovrebbe essere possibile specificando il parametro $XDSDocumentEntryStatus o sbaglio?

**Comment by ChiaraCeccottiFVG** [comment]
Mi scusi @apsstn, chiedo solo per sicurezza, se provate lo use case di sostituzione con un documento pubblicato nuovo e sul quale non sia stata eseguita metadata update in precedenza la replace va a buon fine? 
Ringrazio e Rimaniamo a disposizione per ulteriori necessità.

**Comment by LucaRogledi** [comment]
> Chiedo a @LucaRogledi se il Gateway effettui la ITI-18 ricercando solo i documenti in stato 'Approved'. A memoria dovrebbe essere possibile specificando il parametro $XDSDocumentEntryStatus o sbaglio?

Buonasera @apsstn ,
Confermiamo che il gateway restituisce i documenti in stato 'Approved'.
Grazie

**Comment by izamberlan** [comment]
lo Status però non fa parte dei parametri di ricerca nella GetDocuments (utilizzata per la recupero riferimenti documento):
[https://profiles.ihe.net/ITI/TF/Volume2/ITI-18.html#3.18.4.1.2.3.7.5](url)

**Comment by apsstn** [comment]
> Mi scusi @apsstn, chiedo solo per sicurezza, se provate lo use case di sostituzione con un documento pubblicato nuovo e sul quale non sia stata eseguita metadata update in precedenza la replace va a buon fine? Ringrazio e Rimaniamo a disposizione per ulteriori necessità.

Buongiorno @ChiaraCeccottiFVG abbiamo effettuato un nuovo invio di UC1 ed UC5 che è andato a buon fine

WorkflowInstanceId: `2.16.840.1.113883.2.9.2.42.4.4.dec306b6120ce557d2e744b5dfa3ae9c4cc6ec7ada19ea3c2c128131d2ab8091.6c923b24c2^^^^urn:ihe:iti:xdw:2013:workflowInstanceId`

Abbiamo verificato con esito positivo anche UC7

Chiuderei questa issue dato che è stata correttamente aperta una [nuova issue](https://github.com/ministero-salute/it-fse-support/issues/1384) per discutere della questione recupero documenti in stato approved evitando quelli deprecati

Grazie a tutti per la collaborazione

**Comment by ChiaraCeccottiFVG** [comment]
Grazie mille per il riscontro.
Concordo con la chiusura per mantenere il tema attivo sulla nuova issue.
Auguro una buona giornata.
