### ISSUE TITLE
Accreditamento nuova versione equivalente

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#1381]
Buongiorno,
abbiamo già accreditato due versioni di un nostro programma. Ora vorremmo accreditarne un'altra versione.
Nel file versione.json dobbiamo riportare solo la nuova versione oppure anche quelle già accreditate, quindi inserire, in questo caso, 3 record?
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
il file _versions.json_ deve essere caricato e popolato unicamente nel caso in cui si voglia dichiarare l’equivalenza tra una versione di software già validata ed una sua release successiva se questa non ha subito modifiche al codice nei moduli relativi alla gestione dei CDA2 e al colloquio col gateway.
In tal caso sarà necessario popolare il file con:
1. in corrispondenza dei campi _"appVendor", "appID", "appVersion",_ le informazioni relative all'applicativo già accreditato; 
2. in corrispondenza del campo _"equiv_releases"_: le informazioni relative a tutte le versioni successive equivalenti e successive rispetto a quella accreditata. 
Invece, nel caso in cui si voglia procedere con l'accreditamento di un nuova nuova versione o di un ulteriori applicativi (come nel caso di _INFOSERVICE/FLY/2.0_, da voi accreditato successivamente rispetto all'applicativo _INFOSERVICE/GESCON/5_), il file _versions.json_ non dovrà essere compilato.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by infoserviceonline** [comment]
Ho provveduto ad aggiornare il file json e ad effettuare la relativa Pull Request.
Grazie.
