### ISSUE TITLE
Cancellazione documento

### ISSUE THREAD

**Issue by GranataCrescenzo** [ministero-salute/it-fse-support#1382]
Buongiorno, 
sto provando a fare una cancellazione documento ma ottengo questo messaggio. 
{"traceID":"a83f39e319654bd6","spanID":"a83f39e319654bd6","type":"/msg/jwt-validation","title":"Campo token JWT non valido.","detail":"Il campo purpose_of_use non coerente con operazione richiesta","instance":"/jwt-mandatory-field-malformed"}

questo è il mio token
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGYXpDQ0ExT2dBd0lCQWdJVVlXL2NlWXphMGcxVXhuVFkxS1h3UmcyOWRmTXdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlOREV4TURZeE5EUTBNREZhRncweU56RXhNRGN4TkRRME1EQmFNR3d4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVI4d0hRWURWUVJoREJaRFJqcEpWQzFRVWs5V1FWZ3dNRmd3TUZnd01EQlpNUnN3R1FZRFZRUUREQkpUTVNNeE1URWpSMFZPU1ZWVFUxSk1XRmd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGttQlAyNnpwOXZCdDEyRmRSbGF1cmgzc3dqbUp0Q2JUQ2oyQS9vbXk2Mk9DaWNFNFhaTnNaRmRlakNWWFpHeVN5dVJwdHhiRm01Z0MzRUNxUUlsZGlWYnlzSjQzQTBFL044dDcyUHVQdm9HOVRUMnhsMnlKVUkvM2dQelRPM01yUlVwMHNNakxmenJGdVNvM3lRY1V1YVl5Q1N6LzlBUmVHQlR0M3AySGx1NS81dzlmMjY5allGZDVlL05TOVROUTI4RXNzSWtUU3ZTRVdWbTJGUWJXbSs2djFLLzhuVXlNZ1ZCbjlzTWVRbjdhQzlvMEYrWmJmenVvUHh6MHZGSTczQ2lEMjVzbk5sRXJFNDNqZUJ3c3d4RksxblpDWW15UjVzdUF2VzdFL3RGT2RvbHBNTFNKZUk1Smg4SkFhbG50dVdkZFAvRUh2bFhKaStzY0l3YlR6QWdNQkFBR2pnZ0VZTUlJQkZEQWZCZ05WSFNNRUdEQVdnQlFXT2FrYUJZbTNEeTJ5TmUzQ0NackZBNE1pUHpBU0JnTlZIU0FFQ3pBSk1BY0dCU3RNSFFFTE1JR3RCZ05WSFI4RWdhVXdnYUl3Z1orZ2daeWdnWm1HZ1pab2RIUndjem92TDJOaGMyOW5aV2x6ZG1sc0xuTnZaMlZwTG1sMEwyVnFZbU5oTDNCMVlteHBZM2RsWWk5M1pXSmthWE4wTDJObGNuUmthWE4wUDJOdFpEMWpjbXdtYVhOemRXVnlQVU5PSlRORVEwRXJUV2x1YVhOMFpYSnZLMlJsYkd4aEsxTmhiSFYwWlN0VVpYTjBKVEpEVHlVelJFMXBibWx6ZEdWeWJ5dGtaV3hzWVN0VFlXeDFkR1VsTWtOREpUTkVTVlF3SFFZRFZSME9CQllFRkt0QW1HeVY3R0IwSkFwT2tCSnovMllvUnVBWk1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQU1Sc1MvS0h3K3E4cktKZFIzMnVvaitRZDhRR2p1alV1dFMwVmJBYlNmdmFkbkRwZEh4NTlXNHNLRnVQMysxa2VBcXJaeGgwK1d5RWk5aElzY21ndjRMOHFJdW5VSUVhUHdNUzQ2ODkyQk9hUlI5K0Q0Qm5xNE15NEE2VGJrN0o0cjE1bW9Rb1NGT2U5ck1iUHBlbEdIN1RkbmVjQ1M3VlhvbmllRG5qTkYwWjNlQlVwbHAvdHdLczlCNlJqQktqTzgvd2FNcTBjVXJjaUJmc3lKOThhNnpPWmZDWlhHbEdFY0JyOG5ScVBYRWk4UWZEKzQ5VklLK2dQTUZ0RTFvOHNWOTlzUUs3ZVFRTFljY0NqSkZZVXUyV0F6dVI2ZlJWVWZJSjBEYzFiUXdrWHk5Um5EVWpRL3dqbk1JSnZ4VzlreEk0OGtZc3BmNHlzUVVPQWs5OThvTVpkcTdheGJ1dThWR2VOQXNMTGd3WXc1RmRBcnRoSC9LV3crQVVWcjNJeC9mbi93YmhyakxSa3IwSExpTGs5MERWdWExb3hyYmkvRGFVUERjd2hNZGtKbzQwMDlaandHTktsL0RxQzZxR2lYakdnSnYzaHVsMFdCdEZrMHpIWGJYa3BzUVRGbFFvRWZkTU1yT1RoY3h0Rlh3bG9vZjJ5T0t5LzFYZncvYTAybzVWN2ZPZXVtYmZha3dEbWVoZFJnc3JHTXByWmV6b3l5ZmFkQ2FBVGpiTVc4TEdKUmVqMFgxVVB3SThYSGx6YThDb1pDVXBXbXZNWFB2YXYzbXRCWEs5K1FBd0o5SitPYzZCQ0JyY0U4TExCNnYrZGVkZlhMN3g5M0dUMTlDMWxjck4xakcwc2MwZzFOVmorTCthdStDU3htaHNzSUd3ZlM5OWg1WldyS2ZnPSJdfQ.eyJzdWIiOiJQUk9WQVgwMFgwMFgwMDBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImlzcyI6ImludGVncml0eTpTMSMxMTEjR0VOSVVTU1JMWFgiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiUG9jciIsInN1YmplY3RfYXBwbGljYXRpb25fdmVuZG9yIjoiR2VuaXVzU3JsIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiMS4wLjAuMCIsImxvY2FsaXR5IjoiMDkwNjM5OTEyMTFeXl5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4xLjMmSVNPXl5eXjE1MDIwNTEyMzQ1NSIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMTUwIiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb25lIENhbXBhbmlhIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwicGF0aWVudF9jb25zZW50IjoiVHJ1ZSIsImFjdGlvbl9pZCI6IkRFTEVURSIsInJlc291cmNlX2hsN190eXBlIjoiKCc2ODYwNC04Xl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsImp0aSI6IjEyMzQiLCJwZXJzb25faWQiOiJCTkNNUkE2N0UwOEQ4MTBJXl5eJmFtcDsyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImYW1wO0lTTyIsImF0dGFjaG1lbnRfaGFzaCI6IiIsImlhdCI6IjE3MzMyMTgwODIiLCJleHAiOiIxNzMzMjkwMDgyIn0.VDqJJyFKlTaa32y_GNNmq_TFhtU94y2kFFVj7mH8-d83lfUDkGM3XLsA73vMOw_UazDzgrj3NQfsWhAKUw-a4BmPKOaQVFB1puGtrgQWCJkE_dkEpvuXRjVimsk_ZLKoi7H8grNZ2nEkMD4IG2-cqnBBXBk9zOPjuAnlBDiuml8qSpGO80RWv7yNX62BL0UMkX0VIwc6A8JChY__wcvvr5PoHKHPEweM38m161m_we3p_QGJBIu-B0iYOoQNAcEIMNXcA5Gmgcs0Rp4wTaqVWdTBZ_WU0_W_yJyvXDvvO14sdk255u8MNuqQqkl1RXH9tEdtlebLEWqzFRodIHit1w 

Ma cosa va inserito nel campo purpose_of_use  ?  Non sono riuscito a trovare la documentaizone

**Comment by vigliottim** [comment]
Buongiorno,
di seguito le riportiamo le indicazioni relative al campo _purpose_of_use_:

![image](https://github.com/user-attachments/assets/f3d2bdb7-71c5-45e0-8acc-184c1f80f113)

Può trovare le informazioni sui campi contenuti nei JWT al link seguente: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt

Rimaniamo a disposizione per ulteriori chiarimenti.
