### ISSUE TITLE
Chiarimento sul versionNumber

### ISSUE THREAD

**Issue by danilo-camera** [ministero-salute/it-fse-support#1385]
Buongiorno, 

Avrei una domanda:
sul Patient Summary bisogna fare la gestione di versione in caso di replace o append?
Perchè da quel che vedo sull'esempio di [PSS](https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/PSS.xml) non c'è nulla di commentato mentre per gli altri esempi sembrebbe esserci.

Grazie in anticipo per la risposta

**Comment by vigliottim** [comment]
Buongiorno,
la invitiamo a consultare il paragrafo 3.1.10 della [guida HL7 Italia per PSS](https://www.hl7.it/wp-content/uploads/2024/04/HL7It-IG_CDA2_PSS-v1.4-S.pdf) per avere informazioni in merito al _versionNumber_:

![image](https://github.com/user-attachments/assets/8d967d4d-3444-4c3e-9ee2-4b0afcc65800)
![image](https://github.com/user-attachments/assets/559a47eb-06cf-42d7-8d95-b89041256cc0)
![image](https://github.com/user-attachments/assets/f9514982-3c08-4998-98c9-eb047e9e3a07)

Gli esempi di CDA2 presenti nella cartella [esempi/CDA](https://github.com/ministero-salute/it-fse-support/tree/main/doc/esempi/CDA) non sono esaustivi e hanno lo scopo di offrire un supporto per strutturare gli xml.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by danilo-camera** [comment]
Ok perfetto, si stavo guardando proprio quel paragrafo, però nel provare a fare un replace mi ritrovo a mandare il seguente pezzo di xml riguardante il versionaggio

```
<setId assigningAuthorityName="Regione Piemonte"
	       extension="671be891-8e98-4ae0-855b-9b01a17d0b7a"
	       root="2.16.840.1.113883.2.9.2.10.4.4"/>
<versionNumber value="2"/>
<relatedDocument typeCode="RPLC">
    <parentDocument>
	    <id assigningAuthorityName="Regione Piemonte"
			      extension="9001364e-bab4-408b-9415-fb9357858953"
			      root="2.16.840.1.113883.2.9.2.10.4.4"/>
    </parentDocument>
</relatedDocument>
```

però il vostro endpoint mi risponde "Id documento non presente", da cosa può essere portato?

9001364e-bab4-408b-9415-fb9357858953 è l'id del pdf che ho validato e pubblicato prima di fare il replace

**Comment by vigliottim** [comment]
Potrebbe gentilmente riportare la response completa con trace_id/govway_id?
Grazie per la collaborazione.

**Comment by danilo-camera** [comment]
Si certo. grazie a voi!

` {"traceID":"2239e2f706616fe4","spanID":"2239e2f706616fe4","type":"/err/resource","title":"Resource error","detail":"Id documento non presente","status":404,"instance":"/not-found"} `

**Comment by vigliottim** [comment]
> 9001364e-bab4-408b-9415-fb9357858953 è l'id del pdf che ho validato e pubblicato prima di fare il replace

Potrebbe riportare anche il trace_id/govway_id della chiamata al servizio di pubblicazione? Grazie.

**Comment by danilo-camera** [comment]
Scusa ma non ho salvato trace id e govway della pubblicazione precedente rifaccio la casistica da capo
questa è la risposta della validate and create
`{"traceID":"8fe9486f3bf52140","spanID":"8fe9486f3bf52140","workflowInstanceId":"2.16.840.1.113883.2.9.2.10.4.4.5578136418457a2458f6cb2a61975ccf61d5eb04c5d1a7fac41d299696f6d52a.fdc81507f8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

questa è la risposta della validate and replace

`{"traceID":"c925a4b7c379a6e2","spanID":"c925a4b7c379a6e2","type":"/err/resource","title":"Resource error","detail":"Id documento non presente","status":404,"instance":"/not-found"}`

**Comment by LucaRogledi** [comment]
Buonasera,
Dalle nostre verifiche risulta che per il la chiamata con "traceID":"2239e2f706616fe4" è stata effettuata una chiamata di replace con il seguente url:
`https://apicast-fse-gtw-msval.sogei.it/v1/documents/validate-and-replace/2.16.840.1.113883.2.9.2.10.4.4%5E01321ca4-3e93-4478-933d-041e995f8404`

La invitiamo gentilmente a verificare che l'identificativoDoc indicato nella url di Replace, corrisponda all'identificativoDoc utilizzato nella precedente pubblicazione e che all'interno del cda del pdf utilizzato in Replace:

![image](https://github.com/user-attachments/assets/1b6003e2-2c63-4930-9aae-b685d953521c)

gli attributi root ed extension del tag parentDocument siano valorizzati correttamente facendo riferimento al documento sostituito (utilizzato nella precedente pubblicazione). 

![image](https://github.com/user-attachments/assets/6dc75cc7-3a99-4b91-87b8-d8e25abb1f50)
https://www.hl7.it/wp-content/uploads/2024/04/HL7It-IG_CDA2_PSS-v1.4-S.pdf

Restiamo a disposizione per ulteriore supporto.
Grazie

**Comment by danilo-camera** [comment]
ok perfetto, credo di aver completato correttamente l'aggiornamento. 
praticamente L'ID del parent document deve essere inserito sia nell'URL, sia nei campi <ClinicalDocument/id/@extension> e <relatedDocument/parentDocument/id/@extension>. 
Per il campo <ClinicalDocument/setId/@extension>, invece, deve essere utilizzato l'ID della nuova versione del documento.

potete gentilmente verificare da voi, se vi arriva tutto corretto?

chiamata di pubblicazione:
`{"traceID":"356af75be14507aa","spanID":"356af75be14507aa","workflowInstanceId":"2.16.840.1.113883.2.9.2.10.4.4.313267fe3b4171dd8dac3e8317fafdce6f1ad9d9919b5ce8266bcd3669f261e3.91c733bb2f^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

chiamata di aggiornamento:
`{"traceID":"31177b2d24d24236","spanID":"31177b2d24d24236","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.10.4.4.313267fe3b4171dd8dac3e8317fafdce6f1ad9d9919b5ce8266bcd3669f261e3.86e6729e2e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

**Comment by LucaRogledi** [comment]
Buonasera,
Confermiamo che la chiamata di aggiornamento è avvenuta correttamente:

```
{
"eventType":"SEND_TO_INI",
"eventDate":"2024-12-04T16:28:04.983+01:00",
"eventStatus":"SUCCESS",
"message":"Regime di mock abilitato",
"workflowInstanceId":"2.16.840.1.113883.2.9.2.10.4.4.313267fe3b4171dd8dac3e8317fafdce6f1ad9d9919b5ce8266bcd3669f261e3.86e6729e2e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
"expiringDate":"2025-12-04T16:28:05.084+01:00"
}
```

La informiamo che è possibile effettuare la verifica in autonomia tramite il servizio di status per workflowInstanceId indicato in [documentazione - integrazione-gateway](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#10-servizio-di-recupero-stato-transazione-per-workflowinstanceid).
Procediamo con la chiusura della presente issue e restiamo a disposizione per ulteriore supporto.
Grazie

**Comment by danilo-camera** [comment]
Buonasera Angelo,

confermo che provando come ha descritto nel suo commento, creazione e aggiornamento funzionano correttamente
