### ISSUE TITLE
Versioni dei programmi accreditati

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#1386]
Buongiorno.
Tra gli altri, ho un programma accreditato con la versione 5 (e basta), che è quella pilota per gli equivalenti.
Apprendo oggi dal mio collega, che se utilizzo come versione 5 e non 5.0 i test vanno in errore nella Regione Puglia.
Vorrei capire come funziona, anche se potrei semplicemente dichiarare l'ennesima versione equivalente, credevo che le regioni fossero trasparenti verso il FSE nazionale, ma pare che così non sia, stando a quanto mi dicono.
Potete farmi capire come vengono gestite le versioni da voi e se le regioni sono obbligate a rispettarle (visto che le avete accreditate)?
Grazie mille.

**Comment by vigliottim** [comment]
Buongiorno,
le confermiamo che la versione del suo software che risulta accreditata è 5.
Potrebbe gentilmente darci maggiori dettagli sui test che andrebbero in errore e fornirci la response ricevuta?
Grazie.

**Comment by infoserviceonline** [comment]
Certo, appena il mio collaboratore riuscirà a farli ve li comunicherò.
Grazie.

**Comment by infoserviceonline** [comment]
La chiamata testata è addDocument. Se nella versione dell'applicativo inseriamo il valore 5, riceviamo l'errore riportano nella reponse allegata, se inseriamo 5.0 l'operazione va a buon fine.
Attendiamo riscontro.
Grazie.
[Response.txt](https://github.com/user-attachments/files/18024536/Response.txt)

**Comment by LucaRogledi** [comment]
Buonasera, 
Potrebbe indicarci l'ambiente utilizzato?
In produzione non ci sono controlli sui sistemi accreditati lato INI.
Grazie

**Comment by infoserviceonline** [comment]
L'ambiente di test della Regione Puglia, dove fra pochi giorni entrerà in vigore il FSE. Il problema è che stando così le cose dovrei usare una versione per la Puglia ed una per il resto d'Italia, cosa ovviamente assurda.

**Comment by vigliottim** [comment]
Buonasera,
non avendo controllo su ciò che viene fatto dalle regioni, le suggeriamo di contattare direttamente la regione Puglia.
Grazie.

**Comment by infoserviceonline** [comment]
Ci proverò, anche se non rispondono quasi mai. Credevo che, trattandosi, a mio modesto parere, di una difformità palese, l'organo superiore intervenisse su quello inferiore. Evidentemente mi sbagliavo, seguirò altre strade. 
Grazie.

**Comment by ds-tommaso** [comment]
Perdonate l’intromissione, ma vorrei approfittare di questa issue per chiedere informazioni sul FSE.

@infoserviceonline, sa se è confermato l’utilizzo di un repository distribuito e se sono già disponibili le specifiche tecniche?

P.S.: Confermo che è necessario mantenere la terna attualmente in uso per le operazioni di presa in carico ed erogazione delle ricette. Per utilizzare versioni successive, occorre darne comunicazione all’help-desk.
Suppongo che ci sia un utente “edotto” censito su GTW e TS che si occupa di accogliere i ns. invii e rimandarli al destinatario più corretto. (vedi l'utilizzo della piattaforma Iris per inviare i tamponi)

**Comment by infoserviceonline** [comment]
A questo punto è d'obbligo chiedere che sorte avranno le versioni accreditate come "Web", senza numero, tantomeno con i decimali.
Ribadisco, quindi, il concetto che, secondo me, voi o chi per voi dovrebbe intervenire presso le regioni non allineate alle vostre specifiche, con le quali avete accreditato gli applicativi, oppure comunicarci ufficialmente che le versioni devono essere numeriche e nel formato decimale.
Faccio presente che questo mancato allineamento causerà un blocco nell'alimentazione del FSE in fase di produzione nelle regioni con il problema esposto.
Attendo riscontro. Grazie.

**Comment by LucaRogledi** [comment]
Buonasera,
la invitiamo a inoltrare la sua richiesta alla seguente e-mail: FSE-PNRR@innovazione.gov.it che può agevolare la comunicazione con le regioni di riferimento.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
Grazie
