### ISSUE TITLE
Passaggio in produzione

### ISSUE THREAD

**Issue by kromixsoccoop** [ministero-salute/it-fse-support#1387]
Salve,
siamo una azienda che ha ottenuto la certificazione qualche mese fa - Kromix - Cognitio - V.1.0.

Stiamo per passare alla fase operativa di produzione in ambiente reale e abbiamo dei quesiti da porre, nella speranza siate voi gli interlocutori esatti.
 
Per la generazione dei due token JWT è necessario inserire le seguenti informazioni, sotto riportate.
In tal senso annoterò accanto alle informazioni il quesito su cui necessitiamo di info.
 
codice fiscale richiedente: deve essere riportato quello del richiedente che effettua l’accesso, ovvero noi che abbiamo sviluppato l’applicazione o quello del medico che carica il referto?
LOCALITY_NAME: qui in fase di prove abbiamo usato ASP CROTONE, deve restare questo?
LOCALITY_CODE: qui codice azienda 180202, e poi  il codice NSIS dell’ospedale di Crotone.  O va inserito il codice STS11?
ORGANIZATION_NAME:  qui abbiamo usato Regione Calabria, continua arrestare valido?
ORGANIZATION_CODE:  e qui 180, anche questo resta valido pure per la produzione?

Gli endpoint rimangono uguali anche per la produzione?
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1 con endpoint /documents/validation
 
Ultimo dubbio, i Certificati usati in fase di validazione per i test, restano validi anche per la produzione…?  o qualcuno deve darci dei certificati validi per la fase di produzione? Se si cosa bisogna fare per ottenerli?
E da tenere presente che a noi il servizio di invio ad FSE serve solo per la validazione del referto, perché nel nostro caso il referto generato verrà mandato all’aggregatore regionale che procederà all'invio a FSE. Il fatto di mandarlo noi prima in validazione serve solo ad avere verifica e certezza della sua correttezza e non essere respinto da parte dell’aggregatore.
 
Grazie mille per la disponibilità

**Comment by vigliottim** [comment]
Buon pomeriggio,
il gtw non è in produzione ma è in ambiente di test e le relative specifiche sono quelle esposte in documentazione: [integrazione-gateway](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway).
Riguardo la valorizzazione dei parametri per la generazione dei token (_sub_, _locality_, _organization_) può trovare le indicazioni al seguente link: [campi-contenuti-nei-jwt](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt)
Invece, per indicazioni sull'url, i certificati di produzione e altre informazione relative a questo ambiente, la invitiamo a monitorare il canale #fse su Slack.
Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, la presente viene chiusa come risolta. Per ulteriori segnalazioni sarà possibile procedere con l'apertura di un nuovo ticket. Grazie
