### ISSUE TITLE
VALIDAZIONE_CDA2_RSA_CT11_KO: codice di risposta HTTP atteso differente (HTTP422 invece che HTTP400)

### ISSUE THREAD

**Issue by verotoad** [ministero-salute/it-fse-support#139]
Nell'esecuzione dei test per accreditamento RSA, il caso di test in oggetto fallisce in quanto il codice di risposta HTTP non è coerente.
In particolare riceviamo:

`{
    "traceID": "49c66fad21280e6e",
    "spanID": "49c66fad21280e6e",
    "type": "/msg/semantic",
    "title": "Errore semantico.",
    "detail": "[ERRORE-33a| L'elemento ClinicalDocument/documentationOf/serviceEvent deve contenere l'elemento code e DEVE valorizzare il suo attributo code con uno dei seguenti valori: 'PROG'|'DIR' ]",
    "status": 422,
    "instance": "/validation/error",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.150.4.4.e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.63a3d3029c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}`

Il messaggio sembra coerente, ma con codice d'errore **HTTP422 - Unprocessable entity** rispetto al più generico **HTTP400 - Bad request** richiesto dal test case.
Si tratta di un errore della richiesta o un refuso del test case?

**Comment by IStacchiotti** [comment]
Buongiorno, grazie della segnalazione. Il messaggio di errore riportato è in linea con le aspettative poiché si sta riproducendo il caso di test 11 KO del Referto di Specialistica Ambulatoriale che prevede l'errata valorizzazione di quel determinato codice del documentationOf/serviceEvent. Grazie

**Comment by verotoad** [comment]
Grazie della risposta, giusto per conferma chiedo se possiamo ignorare la discrepanza di codice HTTP di risposta (HTTP422 anziché HTTP400) per il completamento del test case.

**Comment by IStacchiotti** [comment]
Sì confermiamo: può ignorare la discrepanza di codice HTTP. Grazie.

**Comment by verotoad** [comment]
Grazie, chiudo issue.
