### ISSUE TITLE
Valorizzazione locality - codifica da usare nei casi ci siano più produttori afferenti a stessa azienda

### ISSUE THREAD

**Issue by msettt** [ministero-salute/it-fse-support#1390]
Salve a tutti,
nel valorizzare il claim locality, all'interno di una stessa azienda tutti i produttori sono tenuti ad usare la medesima codifica?

Ossia se sono presenti due produttori per esempio HIS e LIS, questi nelle interlocuzioni sono obbligati ad usare la stessa per esempio HSP.11 o ogni produttore può usarne una a proprio piacimento purché ovviamente supportata, per esempio HSP.11 e STS.11?

Ci sono delle best practices in merito?

Grazie.
Buona serata

**Comment by IStacchiotti** [comment]
Buonasera, i produttori non sono tenuti ad utilizzare necessariamente la medesima codifica, purchè le codifiche siano supportate secondo quanto riportato in documentazione.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso in cui sia necessario ulteriore supporto.
Grazie.
