### ISSUE TITLE
crash-program. sostituzione documento del CF TRCTST70A01L378S ancora in elaborazione

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#1393]
buongiorno,
il 06/12 è stato sostituito un documento del CF TRCTST70A01L378S  (provincia di Trento)
Ad oggi risulta ancora in stato di elaborazione

questo il workflowInstanceId

`2.16.840.1.113883.2.9.2.130202.4.4.daaff8da4a1546f5a26d5879f73889d6d29a1afd8fbf42758b8b0aba5fcd4cf3.18c0fa2788^^^^urn:ihe:iti:xdw:2013:workflowInstanceId`

allego la request della comunicazione metadati
Grazie

[request_sostituzione_documento_trento.txt](https://github.com/user-attachments/files/18058815/request_sostituzione_documento_trento.txt)

**Comment by apsstn** [comment]
Salve, potreste per favore passarci uniqueid del documento da sostituire  e un timestamp dell'operazione? Con uuid riportato non troviamo nulla

**Comment by alessandropassamonti** [comment]
salve
2.16.840.1.113883.2.9.2.130.4.4^501092

**Comment by apsstn** [comment]
Salve. non troviamo alcun documento con l'uniqueId indicato. Troviamo invece 2.16.840.1.113883.2.9.2.130.4.4^501498 e 
2.16.840.1.113883.2.9.2.130.4.4^501481

**Comment by alessandropassamonti** [comment]
buongiorno,
provo a generare un nuovo documento

**Comment by alessandropassamonti** [comment]
buongiorno,
ho pubblicato un nuovo documento con questo uniqueId: 2.16.840.1.113883.2.9.2.130.4.4^501614
l'esito della pubblicazione è OK. Potete controllare se è indicizzato nei vostri sistemi?

**Comment by alessandropassamonti** [comment]
ok, procedo con la sostituzione

**Comment by alessandropassamonti** [comment]
buongiorno,
il nuovo documento ha questo uniqueId: 2.16.840.1.113883.2.9.2.130.4.4^501618 e sostituisce il 2.16.840.1.113883.2.9.2.130.4.4^501614
 Potete controllare se è indicizzato nei vostri sistemi?

**Comment by apsstn** [comment]
Confermo, sostituzione avvenuta con successo.

**Comment by alessandropassamonti** [comment]
ottimo,
grazie mille chiudo la issue
