### ISSUE TITLE
Regione FVG - Invio massivo ITI-57 - Errore congruenza id repository e organization-id

### ISSUE THREAD

**Issue by ivanot** [ministero-salute/it-fse-support#1398]
Durante i test massivi della ITI-75 abbiamo rilevato un’incongruenza nei metadati per due diverse casistiche che causano errore:
1.	Nella registrazione dei metadati (ITI-42 che precede la 57) viene imputato un ID repository appartenente alla nostra stessa regione, cosa che in interoperabilità non dovrebbe essere possibile
2.	Nell’aggiornamento dei metadati con ruolo APR viene imputata in asserzione una organization-id di una regione diversa dallo UID repository della prima indicizzazione

Nel primo caso chiedo se ha senso fare un tale controllo sull’OID del repository, nel secondo caso invece mi sento di affermare che con ruolo APR lo scenario non dovrebbe essere possibile.

**Comment by IStacchiotti** [comment]
Buonasera, ringraziamo per la segnalazione. In merito al punto 2, è stata appena apportata una correzione; in riferimento al punto 1., non abbiamo evidenze al momento che supportino o meno il controllo proposto. Rimaniamo a disposizione per ulteriori chiarimenti

**Comment by ivanot** [comment]
Confermo, ho verificato le transazioni di ieri sera, peraltro andate tutte a buon fine, e il problema è risolto.
Grazie e un saluto

**Comment by vigliottim** [comment]
Grazie per il suo gentile feedbaack.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
