### ISSUE TITLE
Schematron Referto Radiologia - Obbligatorietà della data nascita del paziente- Alert.

### ISSUE THREAD

**Issue by giuseppe-fasulo** [ministero-salute/it-fse-support#14]
Si segnala quanto segue. 
Il controllo di obbligatorietà di birthTime pur essendo previsto dalla linea guida HL7 Italia  (CONF RAD 27) , ed implementato in ottemperanza ad essa nello schematron relativo, indice le seguenti considerazioni:
1. Non si spiega come mai non sia stato previsto nell'header di altri documenti CDA (cfr LDO) . Ci aspettiamo che i controlli sull'header dei documenti siano uniformi ( a meno di gruppi di informazioni specifiche previste in un determinato CDA e non in altri)
2. Nello specifico l'obbligatorietà della data di nascita in casi di pazienti STP ed altre situazioni in cui risulti impossibile risalire al dato, 
può risultare bloccante, a meno di non introdurre un dato non significativo. 
Comprendo che non si tratta di una segnalazione diretta agli sviluppatori; potrebbero esserlo invece le possibili conseguenze

**Comment by LeonardoAlcaro** [comment]
Ciao Giuseppe,
ti rispondo in ordine di punti:

1. I controlli devono essere uniformi soprattutto per questi elementi del Header quindi hai ragione e ti ringraziamo della segnalazione.
2. Nello specifico dell'obbligatorietà, una miglioria potrebbe essere la condizionalità per casistica ovvero con CF sempre presente nel caso STP opzionale , ricoprendo le varie casistiche di patient.

Grazie 
Leonardo

**Comment by giuseppe-fasulo** [comment]
Ciao. Il problema è a monte. Non sono uniformi le specifiche HL7. Da quanto ho visto poi  guardando gli schematron LDO e RAD, (n particolare nella parte header) anche i programmatori ci mettono del  loro; ne risulta che anche laddove i controlli potrebbero essere implementati in modo uniforme, invece non lo sono, Ho aperto un paio di segnalazioni al riguardo. Servirebbe a  mio modo di vedere uno schematron HEADER, che effettua tutti i controlli comuni sui diversi CDA (invece di fare il copia incolla in diversi schematron individuali o peggio ancora di implementare gli stessi controlli in modo diverso) e lasciare a degli schematron dedicati solo i controlli specifici di ogni CDA particolare. Spero di esserti stato utile

**Comment by LeonardoAlcaro** [comment]
Ciao Giuseppe, sei stato preziosissimo e ti ringraziamo.
Sul discorso di uniformare le specifiche HL7 per tutti gli elementi del Header , non e' cosi semplice in quanto dipende anche dal contesto di utilizzo e scopo del documento, per esempio  l'elemento healthCareFacility e' molto piu' significativo per documenti come VPS  in quanto e' importante sapere il  Pronto Soccorso che ha preso in cura il paziente oppure a livello LDO, meno significativo in altri contesti come PSS.
Prendiamo comunque in riferimento il tuo suggerimento, ne approfitto per comunicarti che le prossime IG HL7 saranno realizzate tutte con il tool ART DECOR e quindi gli sch avranno sicuramente un comportamento più uniforme.

Grazie
Leonardo

**Comment by giuseppe-fasulo** [comment]
Ciao. Credo che il problema della obbligatorietà del dato si possa superare mediante l'utilizzo del nullFlavor, che mi pare sia sempre ammesso, a meno che espressamente vietato dalle regole di Conformità. In questo caso comunque il controllo deve lasciar ammettere l'attributo nullFlavor.
