### ISSUE TITLE
Errori: PDF_UNEXPECTED_CDA and "error code 013 "

### ISSUE THREAD

**Issue by stefanomastrogiacomo** [ministero-salute/it-fse-support#140]
"subject_application_id": "DNLAB_THEMIS"
"subject_application_vendor": "DEDALUS SPA"
"subject_application_version": "3.0.0"

Salve a tutti,
vi pongo alcune domande divise per punti per lo scenario LAB:
1 In riferimento all' errore "error" : "PDF_UNEXPECTED_CDA",
  "description" : "CDA contenuto nel PDF non conforme a quello associato al TraceID"
  Ho compreso che è un baco interno, ora risolto, non dipendente dai contenuti inviati.
  Ho compreso che va rifatta una pull request.
Domanda: Possiamo mantenere i traceid e workflowistanceid delle precedenti pull?
2  In riferimento all'errore
 "id" : 4,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='013' attribute='codeSystem' actual = '' expected = '2.16.840.1.113883.5.84'>ClinicalDocument/component/structuredBody/component/section/component/section/entry/act/entryRelationship/organizer[classCode='CLUSTER']/component/organizer[classCode='BATTERY']/component/observation/methodCode</error>"
Il methodCode è una informazione gestita dal prodotto, ma non è detto che sia disponibile in quanto il clinico responsabile potrebbe non aver definito il codice relativo alla operatività che utilizza all'interno di laboratorio. Questo è coerente con HL7Italia che prevede il campo come opzionale.
Domanda: Se non disponibile è da prevedere un valore di default? Che codice/descrizione è da inserire?
Grazie in anticipo
Stefano

**Comment by IStacchiotti** [comment]
Buongiorno, grazie della segnalazione.

- Per il punto 1 la invitiamo a eseguire nuovamente la validazione sul gtw, e di conseguenza per la fase di accreditamento a rieseguire una pull request con i nuovi workflowInstanceId e traceId generati;

- Per il punto 2 si richiede di far riferimento all'excel fornito per la corretta valorizzazione degli elementi presenti nel caso di test specifico. Nel caso da lei citato per la corretta valorizzazione del methodCode/code si chiede di considerare il vocabolario HL7 di riferimento per questo elemento che è HL7 ObservationMethod il cui OID associato è 2.16.840.1.113883.5.84.

Grazie

**Comment by IStacchiotti** [comment]
Buon pomeriggio, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
