### ISSUE TITLE
PA Trento - Errore UC7 verso Regione Puglia

### ISSUE THREAD

**Issue by apsstn** [ministero-salute/it-fse-support#1403]
Buongiorno, stiamo provando UC7 verso Regione Puglia. Ieri pomeriggio ci è stato tornato un primo errore `"Invalid response received from the API Implementation"`

Abbiamo riprovato questa mattina poco dopo le ore 9 e ci viene tornato un errore "Generic". Lo spanID è `c01224dc92253e39`

Potreste verificare per cortesia?

**Comment by vigliottim** [comment]
Buongiorno,
potrebbe cortesemente riportare la response completa comprensiva di traceID/workflowInstanceId?
Grazie.

**Comment by apsstn** [comment]
Salve, traceID è `09fb2b4efbc66c94`

**Comment by vigliottim** [comment]
Grazie.

@lninnova
Chiediamo gentilmente alla regione Puglia, RDA di riferimento, di effettuare delle verifiche.

**Comment by apsstn** [comment]
Salve, abbiamo appenariprovato. Unique ID è `2.16.840.1.113883.2.9.2.42.4.4^SIO.REF.2024.900002001.2`

**Comment by lninnova** [comment]
Buon pomeriggio, 
per il documento indicato risulta una richiesta di cancellazione andata a buon fine in data 10-DIC-2024 14:44:47.
Di conseguenza la successiva richiesta di recupero riferimento di oggi ha restituito l'errore Unavailable $XDSDocumentUniqueId.
Ho riportato il documento in stato Approved per consentirvi di riprovare la cancellazione.
