### ISSUE TITLE
Errata versione applicativo accreditato

### ISSUE THREAD

**Issue by avlp** [ministero-salute/it-fse-support#1404]
Salve,
si segnala che relativamente all'applicativo Ellipse AMB di Engineering Ingegneria Informatica S.p.A. è stata censita la versione 1.0.0 mentre la versione accreditata è 4.0.0

**Comment by IStacchiotti** [comment]
Buonasera, nella pr #1291, all'interno del file json contenuto al [link](https://github.com/ministero-salute/it-fse-accreditamento/pull/1291), la versione indicata per l'applicativo è la 1.0.0 anziché 4.0.0, per questo sul file degli accreditati risulta la prima versione. Pertanto vi inviteremmo ad eseguire una commit per correggere il json in questione e per uniformare la versione dichiarata all'interno della vostra cartella di riferimento nel main del ministero della salute. Specifichiamo inoltre che nel caso in cui le due versioni del software siano equivalenti nella gestione dei CDA2 e nel colloquio col gateway, è possibile dichiararne l'equivalenza secondo la procedura riportata in documentazione al [link]( https://github.com/ministero-salute/it-fse-accreditamento#gestione-equivalenza-versione-software). Rimaniamo a disposizione per chiarimenti, grazie

**Comment by vigliottim** [comment]
Grazie per il suo gentile feedback.
La sua PR è stata presa in carico.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
