### ISSUE TITLE
Prova Invio CDA generico

### ISSUE THREAD

**Issue by MedianetServiziSrl** [ministero-salute/it-fse-support#1405]
Buonasera,
abbiamo la necessità di inviare al sistema FSE dei CDA generici che non siano specifici come (RSA,LDO etc...) esistono degli esempi o template per i CDA generici da inviare al sistema?

Rimaniamo in attesa, saluti.

**Comment by vigliottim** [comment]
Buonasera,
non è possibile inviare CDA2 generici.
Essi dovranno necessariamente appartenere a una tipologia documentale tra quelle disponibili: https://github.com/ministero-salute/it-fse-support/tree/main/doc/esempi/CDA

**Comment by MedianetServiziSrl** [comment]
Buongiorno,
avendo visionato il file Excel dei vari campi del CDA2 nello specifico il PSS, nei campi inerenti al body xml è presente una dicitura Obbligatorietà da IG, cosa si intende? 
![image](https://github.com/user-attachments/assets/c53d722f-8ab7-42df-98d6-e963e930970b)


Saluti.

**Comment by vigliottim** [comment]
Buongiorno,
la colonna _"Obbligatorietà da IG"_ indica se l'elemento in esame è obbligatorio o meno secondo le linee guida HL7 Italia.
Per eseguire correttamente il caso di test dovrà far riferimento alla colonna _"Obbligatorietà per Test Case X"_.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
