### ISSUE TITLE
Report per Test Sogei

### ISSUE THREAD

**Issue by marco-volpe** [ministero-salute/it-fse-support#1406]
Buongiorno

è stato inviato il report dei test eseguiti e mostrati nella riunione di lunedi? Alla mia casella di posta non è arrivato e sullo sharepoint non mi è sembrato di vederlo

Grazie

**Comment by vigliottim** [comment]
Buongiorno,
la invitiamo gentilmente ad inoltrare la sua richiesta alla seguente e-mail: FSE-PNRR@innovazione.gov.it, indicando in maniera dettagliata a quale report fa riferimento.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
Grazie.
