### ISSUE TITLE
Errore in Pubblicazione di un documento validato: "il CDA non risulta validato"

### ISSUE THREAD

**Issue by rangeletti** [ministero-salute/it-fse-support#141]
Buongiorno,

effettuando la pubblicazione di un documento precedentemente validato abbiamo riscontrato il seguente errore: "Il CDA non risulta validato".

Questa la response ottenuta dalla validazione (2023-03-08 14:52:59):
{"traceID":"392cdfedc2915d5b","spanID":"392cdfedc2915d5b","workflowInstanceId":"2.16.840.1.113883.2.9.2.30.4.4.c8fb0b78f96b91a2ba0231192da92872b7a6d73d7e3d7a9754282fa9b9026668.ac9112c510^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

Questa la response della pubblicazione (2023-03-08 15:45:19):
{"traceID":"dd5a099cad5798ef","spanID":"dd5a099cad5798ef","type":"/msg/cda-match","title":"Errore in fase di recupero dell'esito della verifica.","detail":"Il CDA non risulta validato","status":400,"instance":"/cda-validation"}

Allego il .pdf del documento inviato.

C'è un limite temporale dopo il quale la validazione deve essere rifatta? Perchè sembra che la validazione abbia una durata temporale...
[SecondoCDA.pdf](https://github.com/ministero-salute/it-fse-support/files/10921878/SecondoCDA.pdf)

**Comment by masciamariotti** [comment]
Buon pomeriggio Rachele,
a conferma dell'errore riscontrato, le chiederei di verificare se:
- sta utilizzando un CDA tra quelli forniti come esempio;
- il CDA iniettato nel pdf di pubblicazione è lo stesso di quello utilizzato in validazione;
- dopo la validazione, ha chiamato una volta soltanto la pubblicazione, riscontrando l'errore sopra riportato.

**Comment by rangeletti** [comment]
Buonpomeriggio,

come CDA sto usando un CDA prodotto dall'appplicativo che viene validato correttamente dal GW.
Il CDA iniettato nel pdf di pubblicazione è lo stesso di quello utilizzato in configurazione.
Si , confermo che la validazione è stata chiamata solo una volta.

**Comment by rangeletti** [comment]
Ciao, confermiamo che la pubblicazione è avvenuta una sola volta.

**Comment by rangeletti** [comment]
Buongiorno,
volevo chiedere se per caso ci sono novità in merito.
Grazie,
un saluto,
Rachele

**Comment by IStacchiotti** [comment]
Buon pomeriggio Rachele, stiamo facendo delle verifiche in merito a sistema. Le chiediamo cortesemente di riprovare gli step di validazione e successiva pubblicazione, per poi farci sapere se l'errore si ripresenta. Grazie per la collaborazione.

**Comment by IStacchiotti** [comment]
Buonasera, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
