### ISSUE TITLE
Invio documenti di tipo lettera di invito allo screening

### ISSUE THREAD

**Issue by marco-volpe** [ministero-salute/it-fse-support#1410]
Buongiorno

avremmo necessità di sapere se i tipi di documento indicati in oggetto e che nell'A.D. 2.5 afferiscono al tipo LOINC 101134-5 (Promemoria di appuntamento) saranno pubblicabili tramite il Gateway.

Tale tipologia di documento è prevista dal decreto 07/09/2023 e il garante della privacy ne ha sollecitato l'acquisizione da parte delle regioni. 

Ad oggi non sembra esserci un CDA specifico che sia validabile da Gateway. L'elenco degli standard documentali a cui facciamo riferimento è a questo [link](https://www.fascicolosanitario.gov.it/standard-documentali)

Grazie

**Comment by vigliottim** [comment]
Buongiorno, al momento la tipologia documentale di CDA2 in oggetto non è disponibile. 
Le tipologie documentali disponibili sono quelle presenti al seguente link: https://github.com/ministero-salute/it-fse-support/tree/main/doc/esempi/CDA
La invitiamo a monitorare i canali dedicati per aggiornamenti. 
Grazie.

**Comment by marco-volpe** [comment]
Grazie

**Comment by vigliottim** [comment]
Grazie a lei per la segnalazione.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
