### ISSUE TITLE
Crash Program - nessun riscontro chiamate ITI-57 - Regione Lazio 

### ISSUE THREAD

**Issue by giosil** [ministero-salute/it-fse-support#1411]
Buongiorno,
a fronte dei test massivi delle transazioni ITI-57 annunciati per il 13/12/2024 non abbiamo rilevato alcun riscontro delle chiamate nei log. Avevamo già anticipato questo problema nel corso della scorsa call plenaria.
In attesa di un vostro gentile riscontro chiediamo, nel caso di errori riscontrati da parte di INI, ulteriori dettagli.
Grazie.

**Comment by g-maugeri-sogei** [comment]
Buonasera,
sui log di oggi troviamo chiamate andate a buon fine. Sotto un esempio.
[request.txt](https://github.com/user-attachments/files/18198873/request.txt)
[response.txt](https://github.com/user-attachments/files/18198878/response.txt)

**Comment by giosil** [comment]
Buongiorno, confermo l'esito positivo della chiamata. Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della presente issue. Grazie
