### ISSUE TITLE
Crash Program Lombardia - processo di creazione andato in errore 

### ISSUE THREAD

**Issue by EugenioGuagliardi** [ministero-salute/it-fse-support#1412]
Salve a seguito del test di creazione propedeutico alla fase 2 del crash program che prevede anche dei test fra regioni abbiamo ottenuto un errore lato INI.
Di seguito il dettaglio della transazione

org:v3\" status=\"urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure\"><ns3:RegistryErrorList><ns3:RegistryError codeContext=\"RDA generated an internal error.\" errorCode=\"CRF2\" severity=\"urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error\"/></ns3:RegistryErrorList></ns3:RegistryResponse></soapenv:Body></soapenv:Envelope>",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.c8bd471d83^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-12-13T15:59:29.442+0000"
        },
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-12-13T16:59:28.878+01:00",
            "eventStatus": "SUCCESS",
            "subject": "KRNBRS58M08B236S^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.c8bd471d83^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "e4dedfa27e4da952",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-12-13T16:59:28.934+01:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-12-13T16:59:29.355+01:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.35b5041e-b96b-11ef-96b2-0242882768fe",
            "subject": "KRNBRS58M08B236S^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "ERP",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.c8bd471d83^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "3c52205fe94853aa",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-12-13T16:59:29.363+01:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-12-13T16:59:30.105+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.c8bd471d83^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-12-13T16:59:30.184+01:00"
        }
    ]
}

**Comment by vigliottim** [comment]
Buongiorno,
potrebbe indicare cortesemente la regione RDA? 
Grazie.

**Comment by EugenioGuagliardi** [comment]
Si scusi, RDA=RDE=LOMBARDIA

**Comment by vigliottim** [comment]
Buonasera,
l'assistito risulta essere il seguente KRNLXD35E55I956K e appartiene alla Toscana.
L'assistito da adottare è il seguente: KRNLXD01R50A946E.
La preghiamo di verificare e darci riscontro.
Grazie.

**Comment by vigliottim** [comment]
Grazie per il gentile riscontro.
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per altre richieste di supporto.
