### ISSUE TITLE
Informazione - PIT13

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#1413]
Buongiorno

A cosa può essere dovuto l'errore Wrong attribute value of $SUBJECTIDURN$? Per cosa sta $SUBJECTIDURN$?

Qui, il messaggio completo che ricevo:
`Error ricevuto da INI: PIT13: Wrong attribute value of $SUBJECTIDURN$`.

**Comment by vigliottim** [comment]
Buonasera,
si riporta di seguito la descrizione dell'errore ricevuto secondo il documento [Framework e dataset dei servizi base - v2.5](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20interoperabilit%C3%A0/FrameworkEDatasetDeiServiziBase_v2-5_20231212_0.pdf):

<img width="414" alt="image" src="https://github.com/user-attachments/assets/54977aba-a856-4feb-9386-7df526470581" />

**Comment by ds-tommaso** [comment]
Sì, ho provato a cercare la descrizione online. E' la P. IVA della struttura, tripletta codice regione+asl+struttura?

**Comment by vigliottim** [comment]
Le chiediamo gentilmente di inoltrare la sua richiesta alla seguente e-mail: gestionets@sogei.it
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
Grazie.
