### ISSUE TITLE
Crash Program ITI-57 Regione Liguria: errore su codice fiscale autore documento

### ISSUE THREAD

**Issue by izamberlan** [ministero-salute/it-fse-support#1415]
In merito ai test ITI-57, eseguiti il 13/12:
le tipologie di documento certificato vaccinale, referto di laboratorio, referto di specialistica ambulatoriale, scheda di singola vaccinazione, verbale di PS sono fallite per il problema, segnalato durante il SAL di ieri, relativo alla valorizzazione del codice fiscale dell'autore (il nostro sistema regionale effettua una verifica della correttezza formale del codice fiscale con l'algoritmo messo a disposizione dall'AdE); la valorizzazione nelle request è la seguente:
`<ns2:Slot name="authorPerson">

    <ns2:ValueList>

        <ns2:Value>PROVAX00X00X000Y^^^^^^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</ns2:Value>

    </ns2:ValueList>

</ns2:Slot>`
PROVAX00X00X000Y non passa il controllo.
Il documento Profilo sanitario sintetico ha la stessa valorizzazione, la pubblicazione tuttavia è fallita per un nostro timeout interno.
Il documento Lettera di dimissione ospedaliera è fallito per lo stesso motivo (timeout interno), senza il timeout sarebbe probabilmente passato (l'autore è valorizzato con il codice fiscale del nostro paziente di prova).
Il documento referto di radiologia, con autore valorizzato come GTWGWY82B42G920M, è stato correttamente pubblicato e aggiornato.
Come le altre regioni non troviamo traccia del tentativo di pubblicazione del referto di anatomia patologica nei log.

Chiediamo, come concordato nel SAL, di riprovare con un codice fiscale formalmente corretto come autore.

**Comment by izamberlan** [comment]
Aggiugo che un test di ieri pomeriggio, con autore RSSGNN66C05A271Y, su documento LDO, dal lato nostro sembra correttamente eseguito (pubblicazione/ricerca/aggiornamento metadati).

**Comment by vigliottim** [comment]
Buon pomeriggio,
la informiamo che il codice fiscale che vedrà quando verrà rieseguita la batteria di test è: RSSGNN66C05A271Y.

**Comment by izamberlan** [comment]
grazie

**Comment by vigliottim** [comment]
Procediamo alla chiusura della presente issue e rimaniamo a disposizione qualora riscontrasse problemi durante la riesecuzione dei test.
Grazie.
