### ISSUE TITLE
CDA campi & codici da utilizzare

### ISSUE THREAD

**Issue by MedianetServiziSrl** [ministero-salute/it-fse-support#1416]
Buongiorno, compilando il CDA del PSS e guardando il documento di reference non siamo riusciti a capire come compilare i seguenti campi del tag <id> esiste una tabella con i codici standard per Regione? E sopratutto si fa riferimento alla regione del centro che produce il documento? :
![image](https://github.com/user-attachments/assets/1bb05a2f-6782-4d4c-b2c8-5112a60c4bff)

Saluti, in attesa di riscontro.

**Comment by vigliottim** [comment]
Buon pomeriggio,
il tag _root_ che al suo interno ha come valore [OID_STRUTTURA_COMPETENZA] può essere valorizzato come indicato di seguito:
`2.16.840.1.113883.2.9.2.[ASL/AO/REGIONE].4.4`
Ad esempio, nel caso della regione Piemonte, si avrà: 2.16.840.1.113883.2.9.2.**010**.4.4

![image](https://github.com/user-attachments/assets/84aaf516-183b-4578-a7e8-5b6ba5fd3bf8)
_Fonte:_ [Affinity Domain - v2.5](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20interoperabilit%C3%A0/AffinityDomainItalia_v2-5_v20231212.pdf)

Il tag _extension_ deve contenere l'identificativo del documento, come mostrato nel CDA2 di esempio:

![image](https://github.com/user-attachments/assets/f6f95508-fd51-4656-84b9-93ffa1108621)

Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by izamberlan** [comment]
scusate se mi permetto, ma lo 0 va tolto:
2.16.840.1.113883.2.9.2.10.4.4

(negli oid il gruppo non può iniziare per 0 a meno che non sia solo 0)

**Comment by vigliottim** [comment]
> scusate se mi permetto, ma lo 0 va tolto: 2.16.840.1.113883.2.9.2.10.4.4
> 
> (negli oid il gruppo non può iniziare per 0 a meno che non sia solo 0)

Grazie per la gentile correzione.

**Comment by MedianetServiziSrl** [comment]
Buongiorno, grazie per la pronta risposta volevo un altro chiarimento per quanto riguarda il tag id all'interno della sezione "Allergie ed intolleranze" nello specifico in quello che viene specificato all'interno di root, il codice da inserire deve essere casuale o devo seguire uno standard? E deve essere ricopiato per tutta la sezione Allergie ed intolleranze?

![image](https://github.com/user-attachments/assets/06499083-049d-4b12-b106-6341dba54551)

Saluti.

**Comment by vigliottim** [comment]
Buongiorno, 
come riportato sulla [guida HL7 Italia per PSS](https://www.hl7.it/wp-content/uploads/2024/04/HL7It-IG_CDA2_PSS-v1.4-S.pdf),
può fare riferimento ai due paragrafi indicati per strutturare correttamente l'elemento di tipo _observation_ del CDA2:

![image](https://github.com/user-attachments/assets/0e475f73-3f78-490a-b286-8e92fffd58be)

- _**paragrafo 4.3.3.1** “Assenza Allergie Note”_

![image](https://github.com/user-attachments/assets/99f214fe-c01b-4382-aed2-dfd040446118)

- _**paragrafo 4.3.3.2** “Presenza Allergia o Intolleranza”_

![image](https://github.com/user-attachments/assets/3235bb17-fbc8-4c73-9e22-776ed31cb807)

Rimaniamo a disposizione per ulteriori dubbi.

**Comment by LucaRogledi** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Potrà essere riaperta nel caso in cui abbia bisogno di ulteriore supporto.
Grazie.
