### ISSUE TITLE
REGIONE FRIULI VENEZIA GIULIA - TEST DI PUBBLICAZIONE REFERTO TRAMITE MIDDLEWARE REGIONALE VERSO GATEWAY NAZIONALE DI TEST

### ISSUE THREAD

**Issue by sahra-tesi** [ministero-salute/it-fse-support#1418]
Abbiamo effettuato dei test di pubblicazione di un referto in creazione tramite il Middleware Regionale verso il Gateway Nazionale di Test, ma riscontriamo sempre lo stesso errore, riportato di seguito:
> {
>        "traceID" : "5be8b26fe3c37102",
>        "spanID" : "5be8b26fe3c37102",
>        "type" : "/msg/document-hash",
 >        "title" : "Verifica hash fallita.",
 >        "status" : 400,
 >        "detail" : "Verifica hash fallita.",
 >        "instance" : "/jwt-hash-match",
 >        "classError" : "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
> }

Il flusso che stiamo utilizzando prevede:
1. Una chiamata di validazione del referto verso Gateway Nazionale in ambiente di test,
2. La firma del referto,
3. La pubblicazione.

La validazione avviene in due step, così come la pubblicazione: prima effettuiamo un'autenticazione generando i jwt token, seguita dalla rispettiva chiamata di validazione (per la validazione) o di pubblicazione (per la pubblicazione del referto).

Di seguito, alleghiamo:
- La chiamata di validazione, che restituisce esito positivo.
[Chiamata_Validazione_20241218.txt](https://github.com/user-attachments/files/18185096/Chiamata_Validazione_20241218.txt)
- La chiamata di pubblicazione per la creazione del referto, con l'esito negativo riportato sopra.
[Chiamata_Pubblicazione_20241218.txt](https://github.com/user-attachments/files/18185117/Chiamata_Pubblicazione_20241218.txt)

L'unica anomalia che abbiamo riscontrato è che, effettuando due autenticazioni, la prima per la validazione su referto non firmato e la seconda per la pubblicazione su referto firmato, si producono 2 attachment hash differenti. Non siamo sicuri se questo possa interferire, però a livello di flusso è corretto eseguire: prima la validazione, poi la firma e infine la pubblicazione.

Vi ringrazio per la disponibilità e resto in attesa di un vostro riscontro.

**Comment by vigliottim** [comment]
Buonasera,
le confermiamo che la firma PAdES del documento è prevista tra la validazione e la successiva pubblicazione dello stesso.
In merito all'errore da lei riscontrato, le chiediamo di controllare che il valore del campo _"attachment_hash"_ contenuto nei token corrisponda effettivamente all'hash (SHA256) del pdf passato in ingresso, come indicato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt):

![image](https://github.com/user-attachments/assets/ae81d4c6-503a-460e-8f5f-3b52efd0c76e)

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Potrà essere riaperta nel caso in cui abbia bisogno di ulteriore supporto.
Grazie.
