### ISSUE TITLE
REGIONE MARCHE - Errore non parlante in caso di invocazione del servizio per pazienti fuori regione 

### ISSUE THREAD

**Issue by Didi22515** [ministero-salute/it-fse-support#1419]
In fase di invocazione del servizio https://fseservice.sanita.finanze.it/FSEInteroperabilitaWeb/DocumentRegistry_Service, per pazienti fuori regione, riscontriamo un errore non parlante in risposta che rende difficoltosa l'individuazione del problema:
 
<env:Fault>
<env:Code>
<env:Value>env:Sender</env:Value>
</env:Code>
<env:Reason>
<env:Text xml:lang="en">General Failure</env:Text>
</env:Reason>
<env:Detail>
<wsrf-r:ResourceUnknownFault>
<wsrf-bf:Timestamp>2024-12-19T12:38:33.617Z</wsrf-bf:Timestamp>
<wsrf-bf:Description>Internal Server Error</wsrf-bf:Description>
</wsrf-r:ResourceUnknownFault>
</env:Detail>
</env:Fault>
</env:Body>
</env:Envelope>
 
Ad esempio è accaduto per il documento 2.16.840.1.113883.2.9.2.110.4.4^FB9127320230711, notificato alle 13:28 del giorno 19/12/2014.
Riuscireste a darci informazioni più dettagliare sulle possibili cause di errore?

**Comment by vigliottim** [comment]
Buon pomeriggio,
le chiediamo gentilmente se si sta riferendo a FSE 1.0.
Grazie.

**Comment by Didi22515** [comment]
Si, parliamo di FSE 1.0

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
per le richieste riguardanti FSE 1.0 le chiediamo gentilmente di inoltrare la sua richiesta alla seguente mail: gestionets@sogei.it.
Procediamo alla chiusura della issue, e la invitiamo a riaprirla in caso fosse necessario ulteriore supporto.
Grazie
