### ISSUE TITLE
Errori pull request 109 richiesta chiarimenti

### ISSUE THREAD

**Issue by Fusarolia** [ministero-salute/it-fse-support#142]
I seguenti errori si ripetono nei vari file di test OK
**Caso 1**
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='017' attribute='codeSystem' actual = '' expected = '2.16.840.1.113883.6.73'>ClinicalDocument/component/structuredBody/component/section[ID='Certificato_Vaccinale']/entry/substanceAdministration/consumable/manufacturedProduct/manufacturedMaterial/code/translation</error>"
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='018' attribute='codeSystemName' actual = '' expected = 'ATC'>ClinicalDocument/component/structuredBody/component/section[ID='Certificato_Vaccinale']/entry/substanceAdministration/consumable/manufacturedProduct/manufacturedMaterial/code/translation</error>"  
}
Ma nel nostro caso il tag manufacturedProduct/manufacturedMaterial/code/translation, che non è obbligatorio, non viene inserito in quanto non abbiamo il dato. Quindi non mi aspetterei errori sui suoi attributi

**Caso 2**
  "id" : 16,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='019' attribute='typeCode' actual = '' expected = 'LOC'>ClinicalDocument/component/structuredBody/component/section[ID='Certificato_Vaccinale']/entry/substanceAdministration/participant</error>"
  "id" : 16,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='020' attribute='classCode' actual = '' expected = 'ROL'>ClinicalDocument/component/structuredBody/component/section[ID='Certificato_Vaccinale']/entry/substanceAdministration/participant/participantRole</error>"

Anche in questo caso nel file non è presente substanceAdministration/participant/, che da specifiche non è obbligatorio . Quindi  non mi aspetto errore su attributi o dettagli

**Caso 3**
{
  "id" : 16,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='043' attribute='code' actual = '30973-2' expected = '85714-4 59784-9'>ClinicalDocument/component/structuredBody/component/section[ID='Certificato_Vaccinale']/entry/substanceAdministration/entryRelationship/observation/code</error>"
}, 
Non capiamo errore in quanto viene inviata una vaccinazione con dose (code 30973-2) e non un esonero 

**Caso 4** 
{
  "id" : 19,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='145' attribute='value' actual = '#id-c595af4d-3db1-412a-b765-f39b0509623f,#id-c595af4d-3db1-412a-b765-f39b0509623f,#id-c595af4d-3db1-412a-b765-f39b0509623f' expected = 'Malattia con presunta immunità'>ClinicalDocument/component/structuredBody/component/section[ID='Certificato_Vaccinale']/entry/substanceAdministration/entryRelationship/observation/value/originalText/reference</error>"
}
Chiediamo chiarimento: nel caso della vaccinazione non dobbiamo mettere il tag entryRelationship/observation/value/originalText/reference?
Negli esempi si diceva di specificare una reference della vaccinazione, in particolare la reference è verso il blocco narrativo. Nel nostro file abbiamo:
&lt;table&gt;
	&lt;tbody&gt;
		&lt;tr ID=&quot;id-ff222c60-ed90-42a7-934e-ceae95bd719b&quot;&gt;
			&lt;td&gt;TETANO&lt;/td&gt;
			&lt;td ID=&quot;id-1151ea28-d641-4e65-b553-581d8659e5a7&quot;&gt;1 - 22/01/2023&lt;br/&gt;1&lt;br/&gt;GD6791&lt;br/&gt;ANATETALL SOSPENSIONE INIETTABILE&lt;br/&gt;002238044&lt;/td&gt;
			&lt;td/&gt;
			&lt;td/&gt;
			&lt;td/&gt;
			&lt;td/&gt;
		&lt;/tr&gt;
	&lt;/tbody&gt;
&lt;/table&gt;
&lt;paragraph&gt;Esclusioni&lt;/paragraph&gt;
&lt;table&gt;
	&lt;tbody&gt;
		&lt;tr ID=&quot;id-af75b5b8-3115-4c2e-a6ad-2fe79fec024b&quot;&gt;
			&lt;td&gt;POLIOMIELITE&lt;/td&gt;
			&lt;td ID=&quot;id-678e913b-e561-481c-8d5d-4c6ac1ad702c&quot;&gt;malattia cardiaca&lt;/td&gt;
			&lt;td/&gt;
			&lt;td/&gt;
		&lt;/tr&gt;
	&lt;/tbody&gt;
&lt;/table&gt;
.......
&lt;originalText&gt;
	&lt;reference value=&quot;#id-1151ea28-d641-4e65-b553-581d8659e5a7&quot;/&gt;
&lt;/originalText&gt;
 
Mentre ci viene chiesto di sostituire #id-1151ea28-d641-4e65-b553-581d8659e5a7 con "Malattia con presunta immunità" 
Non capiamo errore potete darci indicazione?

**Caso 5**
 {
  "id" : 22,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='022' attribute='root' actual = '2.16.840.1.113883.2.9.10.1.11.4.3' expected = '2.16.840.1.113883.2.9.10.1.11.4.10 2.16.840.1.113883.2.9.10.1.11.4.7'>ClinicalDocument/component/structuredBody/component/section[ID='Singola_Vaccinazione']/entry/substanceAdministration/entryRelationship/observation/templateId</error>"
}, 
Nel caso specifico nel cda ci sono sia la sezione della dose (2.16.840.1.113883.2.9.10.1.11.4.3) che dell'esclusione (2.16.840.1.113883.2.9.10.1.11.4.10), ma la sezione della dose è riportata prima dell'esclusione. 
Nell'applicativo il numero dose è obbligatorio quindi viene inserito sempre. 

Dall'errore sembra che la sezione dell'esclusione manchi del tutto, invece è presente, ma successiva alla dose. Come dobbiamo comportarci

Attendiamo un riscontro il prima possibile, grazie.

**Comment by IStacchiotti** [comment]
Grazie della segnalazione, rispondiamo di seguito caso per caso:

CASO 1
-> È stata fatta una correzione, non dovrebbe più ripresentarsi l'errore.

CASO 2
-> È da inserire il classCode dell’elemento participant/participantRole valorizzato nell’excel per eseguire correttamente il caso d’uso

CASO 3
-> Nel caso di test eseguito, essendo un certificato vaccinale, vi è sia la somministrazione di un vaccino che l’esonero da un altro vaccino. Quindi per eseguire correttamente il caso d’uso in esame vanno inserite entrambe le entry che costituiscono il body dello specifico caso di test del Certificato Vaccinale eseguito.

CASO 4
-> Nel text relativo all’elemento segnalato va inserito Malattia con presunta immunità come esplicitato nell’excel fornito che consente di seguire l’inserimento corretto di tutti gli elementi che vengono richiesti nei casi d’uso creati per accreditarsi correttamente.

CASO 5
-> Dal messaggio di errore si evince che è stato eseguito il test di una singola vaccinazione e non del certificato vaccinale, come riporto di seguito: ClinicalDocument/component/structuredBody/component/section[ID='Singola_Vaccinazione']/entry/substanceAdministration/entryRelationship/observation/templateId</error>" Perciò si chiede di rieseguire il test per il Certificato Vaccinale.

Grazie

**Comment by IStacchiotti** [comment]
Buon pomeriggio, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
