### ISSUE TITLE
CrashProgram - Regione Molise - Errore InteroperabilityInvalidRequest con Create and Validate

### ISSUE THREAD

**Issue by marlagatta** [ministero-salute/it-fse-support#1420]
Salve.
Chiamando la 
POST /govway/rest/in/FSE/gateway/v1/documents/validate-and-create
otteniamo l'errore

HTTP/1.1 400 Bad Request
X-Backside-Transport: FAIL FAIL
Connection: Keep-Alive
Transfer-Encoding: chunked
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
Server: GovWay-SOGEI
Pragma: no-cache
GovWay-Message-ID: cb9703de-f583-443c-b5b5-3085e5605f85
GovWay-Transaction-ErrorType: InteroperabilityInvalidRequest
GovWay-Transaction-ID: eed077d7-be2d-11ef-a4d1-005056ae54fa
Date: Thu, 19 Dec 2024 17:26:53 GMT
Vary: *
X-Content-Type-Options: nosniff
Content-Type: application/problem+json
X-Global-Transaction-ID: 6026e6bc6764575d453fa88f

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"eed077d7-be2d-11ef-a4d1-005056ae54fa"}

Potreste cortesemente assisterci? 
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, 
L'errore riscontrato è generato dai Token contenenti un claim 'aud' non valido:
`"aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway"`

La invitiamo gentilmente a riprovare la chiamata dopo aver corretto la valorizzazione dei claim all'interno dei token con quanto riportato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt):
`"aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1"`

Restiamo a disposizione per ulteriore supporto.
Grazie

**Comment by marlagatta** [comment]
Corretta la configurazione, la chiamata funziona. Grazie per il support
