### ISSUE TITLE
Servizio di Sostituzione Documento

### ISSUE THREAD

**Issue by gruppomaxed** [ministero-salute/it-fse-support#1422]
Buongiorno ho difficoltà nell'utilizzo del servizio di sostituzione documento
ho inviato un primo documento con risposta 
Response Content: {"traceID":"fd992adcf84b886a","spanID":"fd992adcf84b886a","workflowInstanceId":"2.16.840.1.113883.2.9.2.80.3.1.4.4.775d9c74d99166c7696de3d8088ddda7fc60b0e8939a5eb129cbe08559468098.533a2b553a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}
Response Status: Created

poi provo a inviare al Servizio di Sostituzione Documento ma....
Response Content: {"traceID":"abfae939dd1683a7","spanID":"abfae939dd1683a7","type":"/err/resource","title":"Resource error","detail":"Id documento non presente","status":404,"instance":"/not-found"}
Response Status: NotFound

potreste indicarmi dove sbaglio ?
grazie

**Comment by vigliottim** [comment]
Buongiorno,
il documento che sta cercando di sostituire è stato validato ma non pubblicato.
Infatti, chiamando il servizio di recupero stato transazione con _"traceID":"fd992adcf84b886a"_, si ottiene la seguente risposta:

```
{
  "traceID": "2917f5da25f18fbe",
  "spanID": "c5ee56236b65ae34",
  "responseStatus": 200,
  "transactionData": [
    {
      "eventType": "VALIDATION",
      "eventDate": "2024-12-28T11:52:56.733+01:00",
      "eventStatus": "SUCCESS",
      "subject": "DNSFBA79A02F257X^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "organizzazione": "080",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.775d9c74d99166c7696de3d8088ddda7fc60b0e8939a5eb129cbe08559468098.533a2b553a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "fd992adcf84b886a",
      "issuer": "integrity:S1#111#GRUPPOMAXEDXX",
      "expiringDate": "2025-12-28T11:52:56.743+01:00"
    }
  ]
}
```

La invitiamo a riprovare dopo aver correttamente pubblicato il documento.
Inoltre, le facciamo presente che dovrà inserire lo stesso _identificativoDocumento_ utilizzato per la creazione in fase di sostituzione.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by gruppomaxed** [comment]
ho pubblicato il documento
Response Content TraceID: {"traceID":"1bd234f43e3d2471","spanID":"f06cb30e4ad97a64","transactionData":[{"eventType":"PUBLICATION","eventDate":"2024-12-30T11:42:55.564+01:00","eventStatus":"SUCCESS","identificativoDocumento":"2.16.840.1.113883.2.9.2.80.4.4^08010444001006922d51e7266V1","subject":"DNSFBA79A02F257X^^^&2.16.840.1.113883.2.9.4.3.2&ISO","tipoAttivita":"OBS","organizzazione":"080","workflowInstanceId":"2.16.840.1.113883.2.9.2.80.3.1.4.4.775d9c74d99166c7696de3d8088ddda7fc60b0e8939a5eb129cbe08559468098.7d0df6b98d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","traceId":"ae24a93ba4b37481","issuer":"integrity:S1#111#GRUPPOMAXEDXX","expiringDate":"2025-12-30T11:42:55.574+01:00"}]}
Response Status: OK    

poi ho ritentato la sostituzione ma 

Response Content: {"traceID":"72df9f4c9db387f8","spanID":"72df9f4c9db387f8","type":"/err/resource","title":"Resource error","detail":"Id documento non presente","status":404,"instance":"/not-found"}
Response Status: NotFound
Response Content TraceID: {"traceID":"71fb493be6a28cc8","spanID":"246db96c7b37a5a2","transactionData":[{"eventType":"REPLACE","eventDate":"2024-12-30T12:33:39.973+01:00","eventStatus":"BLOCKING_ERROR","message":"Id documento non presente","identificativoDocumento":"2.16.840.1.113883.2.9.2.80.4.4^08010444001006922d51e7266V1","subject":"DNSFBA79A02F257X^^^&2.16.840.1.113883.2.9.4.3.2&ISO","tipoAttivita":"OBS","organizzazione":"080","workflowInstanceId":"","traceId":"72df9f4c9db387f8","issuer":"integrity:S1#111#GRUPPOMAXEDXX","expiringDate":"2025-12-30T12:33:39.983+01:00"}]}
Response Status: OK

potreste indicarmi ora dove sbaglio...
Grazie

**Comment by vigliottim** [comment]
Buongiorno, le chiediamo se ha effettuato l'url encode all'_identificativoDocumento_ per costruire l'url, come indicato di seguito:
`/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.80.4.4%5E08010444001006922d51e7266V1`
Grazie.

**Comment by gruppomaxed** [comment]
ottimo mancava l'encode 
Risolto Grazie

**Comment by vigliottim** [comment]
Grazie a lei per il gentile riscontro.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
