### ISSUE TITLE
errore 404 MCA

### ISSUE THREAD

**Issue by Mcataranto** [ministero-salute/it-fse-support#143]
in allegato request e response di un invio con SWAGGER editor, ed anche il pdf con iniettato il CDA relativo.

La risposta di : err
[referto_2.16.840.1.113883.2.9.2.160160.4.4.94033.PSCBNR49L21Z368P.20230309184740.WLGYJ.PDF](https://github.com/ministero-salute/it-fse-support/files/10942817/referto_2.16.840.1.113883.2.9.2.160160.4.4.94033.PSCBNR49L21Z368P.20230309184740.WLGYJ.PDF)
[ResponseERequest URL.txt](https://github.com/ministero-salute/it-fse-support/files/10942818/ResponseERequest.URL.txt)
ore 404" e  "undefined operation" non è chiaro a cosa si riferisce.

**Comment by IStacchiotti** [comment]
Buon pomeriggio, le segnaliamo che non ci risulta corretto l'url invocato:
`'https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/v1/documents/validation'. In particolare si noti che l'url in questione contiene erroneamente due volte la stringa "/v1". Grazie

**Comment by Mcataranto** [comment]
Gent.mo,

l'invio è stato fatto tramite il tool SWAGGER, che autonomamente formatta e
invoca l'url e quindi non è dovuto ad un inserimento manuale.

Il giorno ven 10 mar 2023 alle ore 16:17 IStacchiotti <
***@***.***> ha scritto:
