### ISSUE TITLE
Incongruenza Documentazione - Accreditamento VPS - CASO DI TEST 9

### ISSUE THREAD

**Issue by PRAFFO72** [ministero-salute/it-fse-support#144]
Salve, abbiamo riscontrato un'incogruenza nelle istruzioni per l'accreditamento del [Verbale di Pronto Soccorso](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/2-Verbale%20di%20Pronto%20Soccorso) .

Nel file [casi di test VPS.docx](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/2-Verbale%20di%20Pronto%20Soccorso/casi%20di%20test%20VPS.docx), per il CASO DI TEST 9 è scritto:

_Durante la fase di compilazione dei dati inerenti al nominativo del paziente, viene indicato il cognome ma omesso il nome dello stesso (**patient/name/given**). Il risultato è un errore semantico._ 

Mentre nel file [CDA2_Verbale_Pronto_Soccorso_KO.xlsx](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/2-Verbale%20di%20Pronto%20Soccorso/CDA2_Verbale_Pronto_Soccorso_KO.xlsx), nel foglio "VPS - Caso di Test 9" (cella B61) si fa riferimento a _ClinicalDocument/recordTarget/patientRole/**patient/name/family**_

A quale delle due specifiche dobbiamo attenerci per superare il test?

**Comment by IStacchiotti** [comment]
Grazie della segnalazione.
Si chiede di eseguire il caso di test 9 del VPS seguendo le specifiche del VPS.docx ovvero il word che è stato fornito. Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
