### ISSUE TITLE
Errori request accreditamento / subject_application_vendor : ASL3 Genovese subject_application_id : SIVIS subject_application_version : v.1.0.0

### ISSUE THREAD

**Issue by danielepecoraro** [ministero-salute/it-fse-support#145]
Buongiorno,  a seguito dell'accreditamento dei test case abbiamo riscontrato il seguente errore:

```
}, {
  "id" : 24,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='001' attribute='classCode' actual = '' expected = 'DOCSECT'>ClinicalDocument/component/structuredBody/component/section[ID='Modalità_di_Trasporto']</error>"
}, {
```

L'errore si è generato a causa della mancanza del valore DOCSECT, e lo abbiamo risolto. Gli errori che si sono generati però successivamente

```
}, {
  "id" : 24,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='002' attribute='moodCode' actual = '' expected = 'EVN'>ClinicalDocument/component/structuredBody/component/section[ID='Modalità_di_Trasporto']</error>"
}, {
```

Ovvero l' error code = 002 per intenderci, sono da considerarsi attribuiti sempre all'errore generato nel precedente (lo 001)? Poichè questi errori successivi non hanno un riscontro effettivo. Grazie

subject_application_vendor : ASL3 Genovese
subject_application_id : SIVIS
subject_application_version : v.1.0.0

**Comment by IStacchiotti** [comment]
Grazie per la segnalazione. L'errore segnalato che si è generato a causa della mancanza del valore DOCSECT e che è stato risolto, ha comportato la generazione dei successivi. Quindi una volta risolto l'errore iniziale dell'attributo DOCSECT, i successivi verranno risolti automaticamente.

**Comment by danielepecoraro** [comment]
Ok grazie

**Comment by danielepecoraro** [comment]
```
{
  "id" : 6,
  "error" : "PDF_UNEXPECTED_CDA",
  "description" : "CDA contenuto nel PDF non conforme a quello associato al TraceID"
}, {
```

Per quanto riguarda invece questo errore, da cosa dipende? Non capiamo perchè non corrisponde il trace id e ci servirebbe una delucidazione in merito. Grazie in anticipo.

subject_application_vendor : ASL3 Genovese
subject_application_id : SIVIS
subject_application_version : v.1.0.0

**Comment by IStacchiotti** [comment]
Buon pomeriggio, l'errore segnalato dipende dal fatto che risultano delle incongruenze tra il cda con il quale ha invocato il gtw e quello con cui ha fatto la push su github.

**Comment by danielepecoraro** [comment]
Grazie mille
