### ISSUE TITLE
Errore Accreditamento INSIEL SEI/CLINICO

### ISSUE THREAD

**Issue by MarcoKnezevichInsiel** [ministero-salute/it-fse-support#146]
Buongiorno, 

stiamo tentando di accreditare i nostri software ed abbiamo ricevuto un errore apparentemente inspiegabile:

Nel file errors.json (in allegato) sono presenti molti errori, ne riporto alcuni:

...
```
{
  "id" : 24,
  "error" : "PDF_UNEXPECTED_CDA",
  "description" : "CDA contenuto nel PDF non conforme a quello associato al TraceID"
}, {
  "id" : 24,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='001' attribute='classCode' actual = '' expected = 'DOCSECT'>ClinicalDocument/component/structuredBody/component/section[ID='Modalità_di_Trasporto']</error>"
},
```
...

relativa al file pdf allaegato e relativo al traceId `e8221f83df6228a2`. Come si vede dal cda allegato, i campi richiesti sono correttamente presenti, quindi non capiamo dov'è l'errore.

L'accreditamento è relativo a:
```
subject_application_id:INSIEL	
subject_application_vendor: SEI	
subject_application_version: SEI 03.00.02.01	
```

Errori analoghi li rileviamo per l'altro sofrware in accreditamento:
```
subject_application_id:INSIEL	
subject_application_vendor: CLINICO	
subject_application_version: G4.3.0	
```

Potete darci Indicazione in merito?
[TEST_1_Doc_Vers_2.pdf](https://github.com/ministero-salute/it-fse-support/files/10944031/TEST_1_Doc_Vers_2.pdf)
[errors.json.txt](https://github.com/ministero-salute/it-fse-support/files/10944038/errors.json.txt)

**Comment by IStacchiotti** [comment]
Grazie della segnalazione. Confermiamo che devono essere inseriti sia gli attributi classCode e moodCode della sezione che l'ID nel seguente modo: <section ID="Modalità_di_Trasporto" classCode="DOCSECT" moodCode="EVN">.

**Comment by IStacchiotti** [comment]
Grazie della segnalazione.
Per quanto concerne la risoluzione degli altri errori , si deve procedere come indicato precedentemente per tutti i test case per tutte le sezioni inserendo l'ID e gli attributi classCode e moodCode con la sintassi corretta.
Per quanto riguarda l'esistenza di un endpoint che permett di testare le validazioni che vengono applicate dal vostro motore di verifica dei test, si attende un feedback lato tecnico.

**Comment by IStacchiotti** [comment]
Buon pomeriggio, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
