### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by afxgroup** [ministero-salute/it-fse-support#148]
Buona sera stiamo tentando di utilizzare il servizio di validazione con i dati di esempio ma riceviamo un errore 401

Questa è la risposta:

{
    "type": "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
    "title": "AuthorizationContentDeny",
    "status": 403,
    "detail": "Unauthorized request content",
    "govway_id": "e363b21d-c033-11ed-a9a6-005056ae7395"
}

Auth Token:

eyJ4NWMiOlsiTUlJRkt6Q0NBeE9nQXdJQkFnSVVBYWF0WHM5RTZmSFBaQkY0ZGluSmN1VUR4YTR3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TXpBek1Ea3lNalEwTURCYUZ3MHlOakF6TURreU1qUXpOVGxhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMweE1URk5RMEZUUVZOWVdGaFlXREVhTUJnR0ExVUVBd3dSVXpFak1URXhUVU5CVTBGVFdGaFlXRmd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2pxVGljNnNpdUtxcDR1VzBWMkc1RUhZbS9xdmpnaTRPSk9hZ0I1VGpaV2Q5UTUvMXlFOUpQcTB1MVVMcS9tNDN4aklxS01Hd1IwRTJ3cHhxTk5EK1puZ1N6Y2JhVDBjbGQ3RUx0aUx1QzRnSDBVdTlMZmxRbU03Uy9TN1dSNVlWU1NWUVRzc2xyNkpjenRTZzk5ZWpqdlIwL2VxV1JUZFMyVGZVZGlYRFlDQTVVWlhqKzM1V2JaR2hKSkFvZTRVbXAvTlNuK0VHY2ovVEc5YmpWczdNL0x0TmFzTm1aeldhWWhudXdDQlptM2hHY3IxdXdEZEVSYysyaVNMNCtoYW5EN2xEVDR2RkdrYS8yWkd0U0VrWThtT3E1S1lwRWlMZEtRZ2RwMUlYRFpnQmUweXk3UHMzQzFSM3c3TFZXWS9oYVhuRDNWYzJEWGpBdldKRmJ2MDZIQWdNQkFBR2pnZHd3Z2Rrd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3RWdZRFZSMGdCQXN3Q1RBSEJnVXJUQjBCQ3pCekJnTlZIUjhFYkRCcU1HaWdacUJraG1Kc1pHRndPaTh2WTJGa2N5NW1hVzVoYm5wbExtbDBMME5PUFVOQkpUSXdUV2x1YVhOMFpYSnZKVEl3WkdWc2JHRWxNakJUWVd4MWRHVWxNakJVWlhOMExFODlUV2x1YVhOMFpYSnZKVEl3WkdWc2JHRWxNakJUWVd4MWRHVXNRejFKVkRBZEJnTlZIUTRFRmdRVTV3elVlRzlreTl6V0lhREJrWnN0QXZXemtFQXdEZ1lEVlIwUEFRSC9CQVFEQWdaQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQXNyRDhCWmlSdVpVdnpRQXJrNkdUUEJiQStqUGpHcU1ybmFSM2RLdXBiNnhxVU1BdEJJL1doVkZUWU1EaHdpZndwOEFqdDZIM3JOTEJZbU5oc21LNytlMGxVdlNVTFM0T2NsWVgwV2dDVzhmaW55TzVlWW9na1V2MUtYR0NzVVJaMDVnZCttakpjZ0hYYlN2RFBnNFpEYmZNTFpkSXM4dnErL0haREpuckhCTXdFVXJZWHJiV3hRWVBVWkZGUFZFUytGNklPWEpvZG9QSkNpVFNkUFFjS3VmblVlSnJ2eWFWbmxFTCtaUjh0YUJEUmU5ZUN6T0FlaHAvNGRFTWlrMlkxOTJSZ29YSGFoVXZaWVVTbExnckxrVGFvT2NYVDFVZm1NdXlUT2VxZis4bXBRTk40SVFkcHpNWW1UTU9yZGZPQktVblZOcWpCa0hJYzJHSEdzc0NQbmR5Nkp1NW1tZU0ybEJta0VicC9BZlRIKytTSjJQQTNoTTRYNmJqZGpGaDlBTzJsQ1ZOWXJUaGgvZlpiRHEzSUs3QjlHUjVZUkNRdWRWWnRIL0pNR0NrSUovOHpEZzlYcUgxYW5heXRsNzBNODJWK1pPV2MwazBMaTNNbXZHR3lwanBTM2pWdERPRktFSmtqcGJtOGZmUzgwTGV4RE5vdmRpWWNoSUhLeXJBcW1JUXdpOThjR0tsTCswM0MwaW9oKzBjckU2c3J4MzE4REw4OTdoMWw0SloxWXJ6a2F3eHZlZ1UzWlJ1NHVlL2ZrVGQxclBjRGQxTDlQMGIvMEE2Z00wa2F1QVZSMUZyZDFKWDBZanF6aG1sZlI2MU9tQzF6N25JTGd3VjdTcG05NWVUazc3cVZ4S0l5bUpJTmZyZ0xLV3NKNERDaXQxM1BoOWRHUERTQ0RnPT0iXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJWUkRNUkM2N1QyMEkyNTdFXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJpc3MiOiJhdXRoOkExMTExTUNBU0FTWFhYWFgiLCJleHAiOjE2Nzg2NDg3MTksImlhdCI6MTY3ODU2MjMxOSwianRpIjoiMTIzNCJ9.SHlGWDX2mXMd2v-1x4ZZ0-1nKSo_1Sm1M1Vrm5gLJkZ_V2gOa3JbsggVcxJbwQUzKZ8bq-4FT6gump1U8OlEJtWZkoDseXPw4UzrtKiqBlsANf5nk8NQA6DgjNxAiwq561CsW5hmgYee_tIOK2ji1FwC8Y42GOf2EOBnepHhW-XoMBeUqoNeJ-Mnz8pSImtUzh23PsLQfdZ1kBBius-g7sSSEImNTH3DyS8VG2F_z-jTh4daSqu3v5NalN0h9DshB7zjX_e6qzcvTImNA38WZeyiZ0yhrOUZ4ofeiU11YtCr73YA-4DwO-a1k_yUaaDjGI0guGP3KYAnFRTfM4QLqA

Signature:

eyJ4NWMiOlsiTUlJRkt6Q0NBeE9nQXdJQkFnSVVBYWF0WHM5RTZmSFBaQkY0ZGluSmN1VUR4YTR3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TXpBek1Ea3lNalEwTURCYUZ3MHlOakF6TURreU1qUXpOVGxhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMweE1URk5RMEZUUVZOWVdGaFlXREVhTUJnR0ExVUVBd3dSVXpFak1URXhUVU5CVTBGVFdGaFlXRmd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2pxVGljNnNpdUtxcDR1VzBWMkc1RUhZbS9xdmpnaTRPSk9hZ0I1VGpaV2Q5UTUvMXlFOUpQcTB1MVVMcS9tNDN4aklxS01Hd1IwRTJ3cHhxTk5EK1puZ1N6Y2JhVDBjbGQ3RUx0aUx1QzRnSDBVdTlMZmxRbU03Uy9TN1dSNVlWU1NWUVRzc2xyNkpjenRTZzk5ZWpqdlIwL2VxV1JUZFMyVGZVZGlYRFlDQTVVWlhqKzM1V2JaR2hKSkFvZTRVbXAvTlNuK0VHY2ovVEc5YmpWczdNL0x0TmFzTm1aeldhWWhudXdDQlptM2hHY3IxdXdEZEVSYysyaVNMNCtoYW5EN2xEVDR2RkdrYS8yWkd0U0VrWThtT3E1S1lwRWlMZEtRZ2RwMUlYRFpnQmUweXk3UHMzQzFSM3c3TFZXWS9oYVhuRDNWYzJEWGpBdldKRmJ2MDZIQWdNQkFBR2pnZHd3Z2Rrd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3RWdZRFZSMGdCQXN3Q1RBSEJnVXJUQjBCQ3pCekJnTlZIUjhFYkRCcU1HaWdacUJraG1Kc1pHRndPaTh2WTJGa2N5NW1hVzVoYm5wbExtbDBMME5PUFVOQkpUSXdUV2x1YVhOMFpYSnZKVEl3WkdWc2JHRWxNakJUWVd4MWRHVWxNakJVWlhOMExFODlUV2x1YVhOMFpYSnZKVEl3WkdWc2JHRWxNakJUWVd4MWRHVXNRejFKVkRBZEJnTlZIUTRFRmdRVTV3elVlRzlreTl6V0lhREJrWnN0QXZXemtFQXdEZ1lEVlIwUEFRSC9CQVFEQWdaQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQXNyRDhCWmlSdVpVdnpRQXJrNkdUUEJiQStqUGpHcU1ybmFSM2RLdXBiNnhxVU1BdEJJL1doVkZUWU1EaHdpZndwOEFqdDZIM3JOTEJZbU5oc21LNytlMGxVdlNVTFM0T2NsWVgwV2dDVzhmaW55TzVlWW9na1V2MUtYR0NzVVJaMDVnZCttakpjZ0hYYlN2RFBnNFpEYmZNTFpkSXM4dnErL0haREpuckhCTXdFVXJZWHJiV3hRWVBVWkZGUFZFUytGNklPWEpvZG9QSkNpVFNkUFFjS3VmblVlSnJ2eWFWbmxFTCtaUjh0YUJEUmU5ZUN6T0FlaHAvNGRFTWlrMlkxOTJSZ29YSGFoVXZaWVVTbExnckxrVGFvT2NYVDFVZm1NdXlUT2VxZis4bXBRTk40SVFkcHpNWW1UTU9yZGZPQktVblZOcWpCa0hJYzJHSEdzc0NQbmR5Nkp1NW1tZU0ybEJta0VicC9BZlRIKytTSjJQQTNoTTRYNmJqZGpGaDlBTzJsQ1ZOWXJUaGgvZlpiRHEzSUs3QjlHUjVZUkNRdWRWWnRIL0pNR0NrSUovOHpEZzlYcUgxYW5heXRsNzBNODJWK1pPV2MwazBMaTNNbXZHR3lwanBTM2pWdERPRktFSmtqcGJtOGZmUzgwTGV4RE5vdmRpWWNoSUhLeXJBcW1JUXdpOThjR0tsTCswM0MwaW9oKzBjckU2c3J4MzE4REw4OTdoMWw0SloxWXJ6a2F3eHZlZ1UzWlJ1NHVlL2ZrVGQxclBjRGQxTDlQMGIvMEE2Z00wa2F1QVZSMUZyZDFKWDBZanF6aG1sZlI2MU9tQzF6N25JTGd3VjdTcG05NWVUazc3cVZ4S0l5bUpJTmZyZ0xLV3NKNERDaXQxM1BoOWRHUERTQ0RnPT0iXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ

Potete darci delle informazioni in più?

**Comment by afxgroup** [comment]
Anche questa che dovrebbe avere is subject_* corretti: 34ea0d32-c0b9-11ed-adb9-005056ae54fa

**Comment by afxgroup** [comment]
Ok, siamo riusciti ad andare avanti. Il problema era nel campo iss. Ora pero' riceviamo questo errore:

{
    "traceID": "441bdc839ec78b0c",
    "spanID": "441bdc839ec78b0c",
    "type": "/msg/jwt-validation",
    "title": "Campo token JWT non valido.",
    "detail": "JWT payload: Tipologia documento diversa dalla tipologia di CDA (code - codesystem)",
    "status": 403,
    "instance": "/jwt-document-type",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.160112.4.4.6f0cf6f28a2936daf51d132d61e4fde9f37de48cbb38d33abbff4ca835acd29f.07ab0ddd48^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

**Comment by IStacchiotti** [comment]
Buongiorno, da una prima verifica, è emerso che il paylod del secondo token risulta vuoto. 
<img width="323" alt="image" src="https://user-images.githubusercontent.com/122798799/224660861-ace4dacf-2568-4f4e-818c-7c00724b3162.png">

Potete averne evidenza voi stessi tramite il tool online disponibile a questo [link](https://jwt.io/). Potete verificare cortesemente? Grazie.

**Comment by afxgroup** [comment]
L'ultima richiesta che ho allegato (https://github.com/ministero-salute/it-fse-support/issues/148#issuecomment-1465172466) è completa e anche i token sono pieni (controllati con jwt.io)
Ne ho appena fatta un altra ed il risultato è lo stesso

```
{
    "traceID": "ed2d69b7d9493ea9",
    "spanID": "ed2d69b7d9493ea9",
    "type": "/msg/jwt-validation",
    "title": "Campo token JWT non valido.",
    "detail": "JWT payload: Tipologia documento diversa dalla tipologia di CDA (code - codesystem)",
    "status": 403,
    "instance": "/jwt-document-type",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.160112.4.4.6f0cf6f28a2936daf51d132d61e4fde9f37de48cbb38d33abbff4ca835acd29f.91c29e7e84^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```
Auth:
`eyJ4NWMiOlsiTUlJRkt6Q0NBeE9nQXdJQkFnSVVBYWF0WHM5RTZmSFBaQkY0ZGluSmN1VUR4YTR3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TXpBek1Ea3lNalEwTURCYUZ3MHlOakF6TURreU1qUXpOVGxhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMweE1URk5RMEZUUVZOWVdGaFlXREVhTUJnR0ExVUVBd3dSVXpFak1URXhUVU5CVTBGVFdGaFlXRmd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2pxVGljNnNpdUtxcDR1VzBWMkc1RUhZbS9xdmpnaTRPSk9hZ0I1VGpaV2Q5UTUvMXlFOUpQcTB1MVVMcS9tNDN4aklxS01Hd1IwRTJ3cHhxTk5EK1puZ1N6Y2JhVDBjbGQ3RUx0aUx1QzRnSDBVdTlMZmxRbU03Uy9TN1dSNVlWU1NWUVRzc2xyNkpjenRTZzk5ZWpqdlIwL2VxV1JUZFMyVGZVZGlYRFlDQTVVWlhqKzM1V2JaR2hKSkFvZTRVbXAvTlNuK0VHY2ovVEc5YmpWczdNL0x0TmFzTm1aeldhWWhudXdDQlptM2hHY3IxdXdEZEVSYysyaVNMNCtoYW5EN2xEVDR2RkdrYS8yWkd0U0VrWThtT3E1S1lwRWlMZEtRZ2RwMUlYRFpnQmUweXk3UHMzQzFSM3c3TFZXWS9oYVhuRDNWYzJEWGpBdldKRmJ2MDZIQWdNQkFBR2pnZHd3Z2Rrd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3RWdZRFZSMGdCQXN3Q1RBSEJnVXJUQjBCQ3pCekJnTlZIUjhFYkRCcU1HaWdacUJraG1Kc1pHRndPaTh2WTJGa2N5NW1hVzVoYm5wbExtbDBMME5PUFVOQkpUSXdUV2x1YVhOMFpYSnZKVEl3WkdWc2JHRWxNakJUWVd4MWRHVWxNakJVWlhOMExFODlUV2x1YVhOMFpYSnZKVEl3WkdWc2JHRWxNakJUWVd4MWRHVXNRejFKVkRBZEJnTlZIUTRFRmdRVTV3elVlRzlreTl6V0lhREJrWnN0QXZXemtFQXdEZ1lEVlIwUEFRSC9CQVFEQWdaQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQXNyRDhCWmlSdVpVdnpRQXJrNkdUUEJiQStqUGpHcU1ybmFSM2RLdXBiNnhxVU1BdEJJL1doVkZUWU1EaHdpZndwOEFqdDZIM3JOTEJZbU5oc21LNytlMGxVdlNVTFM0T2NsWVgwV2dDVzhmaW55TzVlWW9na1V2MUtYR0NzVVJaMDVnZCttakpjZ0hYYlN2RFBnNFpEYmZNTFpkSXM4dnErL0haREpuckhCTXdFVXJZWHJiV3hRWVBVWkZGUFZFUytGNklPWEpvZG9QSkNpVFNkUFFjS3VmblVlSnJ2eWFWbmxFTCtaUjh0YUJEUmU5ZUN6T0FlaHAvNGRFTWlrMlkxOTJSZ29YSGFoVXZaWVVTbExnckxrVGFvT2NYVDFVZm1NdXlUT2VxZis4bXBRTk40SVFkcHpNWW1UTU9yZGZPQktVblZOcWpCa0hJYzJHSEdzc0NQbmR5Nkp1NW1tZU0ybEJta0VicC9BZlRIKytTSjJQQTNoTTRYNmJqZGpGaDlBTzJsQ1ZOWXJUaGgvZlpiRHEzSUs3QjlHUjVZUkNRdWRWWnRIL0pNR0NrSUovOHpEZzlYcUgxYW5heXRsNzBNODJWK1pPV2MwazBMaTNNbXZHR3lwanBTM2pWdERPRktFSmtqcGJtOGZmUzgwTGV4RE5vdmRpWWNoSUhLeXJBcW1JUXdpOThjR0tsTCswM0MwaW9oKzBjckU2c3J4MzE4REw4OTdoMWw0SloxWXJ6a2F3eHZlZ1UzWlJ1NHVlL2ZrVGQxclBjRGQxTDlQMGIvMEE2Z00wa2F1QVZSMUZyZDFKWDBZanF6aG1sZlI2MU9tQzF6N25JTGd3VjdTcG05NWVUazc3cVZ4S0l5bUpJTmZyZ0xLV3NKNERDaXQxM1BoOWRHUERTQ0RnPT0iXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJWUkRNUkM2N1QyMEkyNTdFXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJpc3MiOiJhdXRoOlMxIzExMU1DQVNBU1hYWFhYIiwiZXhwIjoxNjc4NzA3ODIzLCJpYXQiOjE2Nzg2MjE0MjMsImp0aSI6IjEyMzQxIn0.VgxldXqMclAYsThVBqau0MPQnPmc6MSOVI7UAVlZfbCp_WRN-HbOjgwWlKQJ7dbSXkTs6VpYat6yI8-I31Cg6BKYnfMtfYl-sAMW9AKpTVplCp1d2q4l6fnSp5O-mOcK4IrFq_Py5nPzuAH5U0n5G_ooXP_CY0K5h3qp4MVimSFaz2-TtNz32ggcDxfnqQYbYC3LD_n5kcN7NudMqhna2sma6eFNlrHn5M844rop05Qwf1h2QCFRBGhohb65tHlnHqNSgMkoN7fMLDgFh5M8CM9yud_Pg3pAMxWVHOI-dxuIp1MCv4c3LH3sPe5TXPs0HpB57DYgwy006wm5-wwrmA`

JWT:
`eyJ4NWMiOlsiTUlJRkt6Q0NBeE9nQXdJQkFnSVVBYWF0WHM5RTZmSFBaQkY0ZGluSmN1VUR4YTR3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TXpBek1Ea3lNalEwTURCYUZ3MHlOakF6TURreU1qUXpOVGxhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMweE1URk5RMEZUUVZOWVdGaFlXREVhTUJnR0ExVUVBd3dSVXpFak1URXhUVU5CVTBGVFdGaFlXRmd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2pxVGljNnNpdUtxcDR1VzBWMkc1RUhZbS9xdmpnaTRPSk9hZ0I1VGpaV2Q5UTUvMXlFOUpQcTB1MVVMcS9tNDN4aklxS01Hd1IwRTJ3cHhxTk5EK1puZ1N6Y2JhVDBjbGQ3RUx0aUx1QzRnSDBVdTlMZmxRbU03Uy9TN1dSNVlWU1NWUVRzc2xyNkpjenRTZzk5ZWpqdlIwL2VxV1JUZFMyVGZVZGlYRFlDQTVVWlhqKzM1V2JaR2hKSkFvZTRVbXAvTlNuK0VHY2ovVEc5YmpWczdNL0x0TmFzTm1aeldhWWhudXdDQlptM2hHY3IxdXdEZEVSYysyaVNMNCtoYW5EN2xEVDR2RkdrYS8yWkd0U0VrWThtT3E1S1lwRWlMZEtRZ2RwMUlYRFpnQmUweXk3UHMzQzFSM3c3TFZXWS9oYVhuRDNWYzJEWGpBdldKRmJ2MDZIQWdNQkFBR2pnZHd3Z2Rrd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3RWdZRFZSMGdCQXN3Q1RBSEJnVXJUQjBCQ3pCekJnTlZIUjhFYkRCcU1HaWdacUJraG1Kc1pHRndPaTh2WTJGa2N5NW1hVzVoYm5wbExtbDBMME5PUFVOQkpUSXdUV2x1YVhOMFpYSnZKVEl3WkdWc2JHRWxNakJUWVd4MWRHVWxNakJVWlhOMExFODlUV2x1YVhOMFpYSnZKVEl3WkdWc2JHRWxNakJUWVd4MWRHVXNRejFKVkRBZEJnTlZIUTRFRmdRVTV3elVlRzlreTl6V0lhREJrWnN0QXZXemtFQXdEZ1lEVlIwUEFRSC9CQVFEQWdaQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQXNyRDhCWmlSdVpVdnpRQXJrNkdUUEJiQStqUGpHcU1ybmFSM2RLdXBiNnhxVU1BdEJJL1doVkZUWU1EaHdpZndwOEFqdDZIM3JOTEJZbU5oc21LNytlMGxVdlNVTFM0T2NsWVgwV2dDVzhmaW55TzVlWW9na1V2MUtYR0NzVVJaMDVnZCttakpjZ0hYYlN2RFBnNFpEYmZNTFpkSXM4dnErL0haREpuckhCTXdFVXJZWHJiV3hRWVBVWkZGUFZFUytGNklPWEpvZG9QSkNpVFNkUFFjS3VmblVlSnJ2eWFWbmxFTCtaUjh0YUJEUmU5ZUN6T0FlaHAvNGRFTWlrMlkxOTJSZ29YSGFoVXZaWVVTbExnckxrVGFvT2NYVDFVZm1NdXlUT2VxZis4bXBRTk40SVFkcHpNWW1UTU9yZGZPQktVblZOcWpCa0hJYzJHSEdzc0NQbmR5Nkp1NW1tZU0ybEJta0VicC9BZlRIKytTSjJQQTNoTTRYNmJqZGpGaDlBTzJsQ1ZOWXJUaGgvZlpiRHEzSUs3QjlHUjVZUkNRdWRWWnRIL0pNR0NrSUovOHpEZzlYcUgxYW5heXRsNzBNODJWK1pPV2MwazBMaTNNbXZHR3lwanBTM2pWdERPRktFSmtqcGJtOGZmUzgwTGV4RE5vdmRpWWNoSUhLeXJBcW1JUXdpOThjR0tsTCswM0MwaW9oKzBjckU2c3J4MzE4REw4OTdoMWw0SloxWXJ6a2F3eHZlZ1UzWlJ1NHVlL2ZrVGQxclBjRGQxTDlQMGIvMEE2Z00wa2F1QVZSMUZyZDFKWDBZanF6aG1sZlI2MU9tQzF6N25JTGd3VjdTcG05NWVUazc3cVZ4S0l5bUpJTmZyZ0xLV3NKNERDaXQxM1BoOWRHUERTQ0RnPT0iXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJWUkRNUkM2N1QyMEkyNTdFXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImlzcyI6ImludGVncml0eTpTMSMxMTFNQ0FTQVNYWFhYWCIsImxvY2FsaXR5IjoiMjAxMTIzNDU2Iiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiMi4wIiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb25lIFNpY2lsaWEiLCJzdWJqZWN0X29yZ2FuaXphdGlvbl9pZCI6IjE5MCIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInBhdGllbnRfY29uc2VudCI6dHJ1ZSwiYWN0aW9uX2lkIjoiQ1JFQVRFIiwicmVzb3VyY2VfaGw3X3R5cGUiOiIxMTUwMi0yXl4yLjE2Ljg0MC4xLjExMzg4My42LjEiLCJhdHRhY2htZW50X2hhc2giOiIwMDljYzE2ZDZiMmU4MjAzYjIwMWZiY2YzN2JkNmE2YjNmOWFhMzRiYmNlZTU1ZDQ2ZGRkMWVlN2E2MzliNzkxIiwic3ViamVjdF9hcHBsaWNhdGlvbl9pZCI6IkxBQjIwMDAiLCJleHAiOjE2Nzg3MDc4MjMsInN1YmplY3RfYXBwbGljYXRpb25fdmVuZG9yIjoiTUNBIFMuQS5TLiIsImlhdCI6MTY3ODYyMTQyMywianRpIjoiMTIzNDEiLCJwZXJzb25faWQiOiJSU1NNUkE3NUMwM0Y4MzlLXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08ifQ.izmFQSexFIPkrofOGQ_hT_wF-zqG_8hIijLrIyJnbXy0GmmJm4dGxjDALa_WfyWGlf626fHEAETyj1nyfv_Jfe9HuHDFtVxjAsmtMNZuixmiig7x1tzbMRup5rGo6PH3hrPvvuMy-FVnFYwPnUeQCFTTkvoZfKKSoRDAUMAIn8OOUc1nErfCYILdOPxyeyERrze7m4CrGa4jOEoScQ2jufzZHjgxVOFZocekBz89km1chiMLzNZENeNNqudevJ7o22NH1ICWXZu7BrEsx9g2FwK-jEMFH5tUTzwJ_BoUS_zBK2tmxv6tRAPpxR0oNMo6KJ7F1ufoPPbtqLLdL90lKA`

**Comment by IStacchiotti** [comment]
Grazie per il feedback, le segnaliamo che il formato del campo "resource_hl7_type" non ci risulta corretto. Potrebbe riprovare popolandolo come indicato di seguito?
` "resource_hl7_type": "('11502-2^^2.16.840.1.113883.6.1')",`

**Comment by afxgroup** [comment]
Ho verificato e sembra tutto corretto. Ho rigenerato i token ed ora ricevo un messaggio di errore diverso:

```
{
    "traceID": "fe3f1f39d368ecfe",
    "spanID": "fe3f1f39d368ecfe",
    "type": "/msg/jwt-validation",
    "title": "Campo token JWT non valido.",
    "detail": "JWT payload: Person id presente nel JWT differente dal codice fiscale del paziente previsto sul CDA",
    "status": 403,
    "instance": "/jwt-person-id",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.160112.4.4.6f0cf6f28a2936daf51d132d61e4fde9f37de48cbb38d33abbff4ca835acd29f.6e9b798488^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```
Ho provato a cambiare il person_id usando quello presente nel file PDF (ed anche quello presente nel nome del file che è diverso) che sto inviando ma ricevo sempre lo stesso errore.ù
Cosa devo specificare in quel campo?

**Comment by afxgroup** [comment]
Inserito il codice fiscale corretto e ora ricevo questo errore:

```
{
    "traceID": "b440cf8e76283557",
    "spanID": "b440cf8e76283557",
    "type": "/msg/syntax",
    "title": "Errore di sintassi.",
    "detail": "Schema with version POCD_HD000040 not found on database.",
    "status": 400,
    "instance": "/validation/error",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.160112.4.4.6f0cf6f28a2936daf51d132d61e4fde9f37de48cbb38d33abbff4ca835acd29f.a0f9dae05c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```

**Comment by afxgroup** [comment]
Stiamo continuando a correggere gli errori. Adesso abbiamo questo errore:

`{
    "traceID": "1f350addeede1917",
    "spanID": "1f350addeede1917",
    "type": "/msg/generic-error",
    "title": "Errore generico.",
    "detail": "BusinessException: Error while validate: ",
    "status": 500,
    "instance": ""
}`

**Comment by afxgroup** [comment]
Problema risolto e documento validato. Grazie
