### ISSUE TITLE
Schematron Referto radiologia - controlli legalAuthenticator

### ISSUE THREAD

**Issue by giuseppe-fasulo** [ministero-salute/it-fse-support#15]
Si segnala che l'elemento legalAuthenticator è obbilgatorio
CONF - RAD - 47 Il tag <legalAuthenticator> è un elemento OBBLIGATORIO che identifica il soggetto che ha legalmente autenticato il documento (firmatario del documento).
L'implementazione però ammette la sua assenza , in quanto i controlli  sono tutti del tipo:
assert test="count(hl7:legalAuthenticator)= 0 or count(hl7:legalAuthenticator/hl7:signatureCode[@code='S'])= 1", cioè sono applicati solo se count(hl7:legalAuthenticator)>0

**Comment by LeonardoAlcaro** [comment]
Ciao Giuseppe,
ti confermo anche qui la presenza di un refuso nel RAD, in  quanto negli altri sch e' obbligatorio il legalAuthenticator.
Occorre, inoltre come ci siamo detti negli issue precedenti uniformare il comportamento del header.

Grazie 
Leonardo
