### ISSUE TITLE
A1#111CIDSOFTWARE/CiD_Software_SpA/ADT/3.0 - Mancato accreditamento LDO

### ISSUE THREAD

**Issue by CidSoftwareDev** [ministero-salute/it-fse-support#152]
Buongiorno,
apriamo questa issue riportando le domande che abbiamo formulato tramite mail, nei giorni 3 e 6 marzo 2023, per le quali siamo ancora in attesa di riscontro.

In merito agli errori che ci avete segnalato per alcuni casi di test abbiamo bisogno di chiarimenti, in quanto, come si evince dai dati inseriti nel nostro `data.json`, il validatore del gateway di test non ci segnala errori o anomalie, restituendoci un riscontro positivo.

Ad esempio per il caso di test 6 abbiamo reinviato il cda al validatore stamattina (03/03/2023) ed abbiamo avuto anche oggi esito positivo. Ecco i dati ricevuti:

`
"ts": "2023-03-03T08:12:54Z",
"traceId": "487db52257690403",
"workflowInstanceId": "2.16.840.1.113883.2.9.2.99.4.4.31e699c6847bc540fcbc08bf60015a5c429eb683ba763c00520f54279c32942f.7b81f2f6f8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
`

Anche controllando negli schematron, disponibili su github, non sembrano essere presenti i controlli ulteriori che hanno generato le suddette segnalazioni.

Vorremmo quindi capire come mai il validatore del sistema di test accetti i nostri dati per poi ricevere un riscontro negativo da parte vostra.

Come possiamo eseguire dei test veritieri che ci permettano di riscontrare tutti gli errori in modo da assicurarci che non ci siano ulteriori problematiche nell' accreditamento?

Ad integrazione di quanto già detto, vorremmo chiedere come mai ci sono state segnalate:

* anomalie sulla base degli id delle sezioni (il vostro gateway di test non esegue le verifiche sulla base degli id, per quanto possiamo capire, dato che non ci segnala errori) 

* anomalie relative a sezioni opzionali per noi non valorizzabili 

Per quanto concerne il secondo punto, infatti, ci è stata contestata (per la LDO) la mancanza delle seguenti sezioni (che non gestiamo nel software):

| **Sezione**                                       | **In Software ADT**                                      |  Obbligatorietà (HL7 Italia)  |
|---------------------------------------------------|----------------------------------------------------------|----------------------------------|
| Allergie                                          | Non presente/gestita nel software                        | Opzionale                        |
| Complicanze                                       | Non presente/gestita nel software                        | Opzionale                        |
| Consulenza                                        | Non presente/gestita nel software                        | Opzionale                        |
| Esami_eseguiti_durante_il_ricovero                | Non presente/gestita nel software                        | Opzionale                        |
| Istruzioni_followup                               | Non presente/gestita nel software                        | Opzionale                        |
| Riscontri_accertamenti_significativi              | Non presente/gestita nel software                        | Opzionale                        |
| Terapia_farmacologica_dimissione                  | Non presente/gestita nel software in maniera strutturata | Opzionale                        |
| Terapia_farmacologica_effettuata_durante_ricovero | Non presente/gestita nel software                        | Opzionale                        |
|                                                   |                                                          |                                  |

Nel canale Slack è stato chiarito che i casi di test avrebbero dovuto essere relativi alle sole informazioni effettivamente gestite dagli applicativi.  E' il motivo per cui alcuni casi di test sono stati da noi indicati come non applicabili.

Non avendo modo di popolare le informazioni per le sezioni indicate, in quanto non attualmente gestite nel software, come possiamo procedere all'accreditamento?

Infine, ci preme segnalare che abbiamo problematiche analoghe anche per la validazione del `VPS`.

In attesa di un vostro cortese riscontro, porgiamo
Cordiali Saluti

**Comment by IStacchiotti** [comment]
Buongiorno, per quanto riguarda il primo punto, le segnaliamo che il processo di accreditamento prevede di analizzare alcune section opzionali dei cda al fine di controllare che il candidato sappia compilare il suddetto in tutte le forme richieste dal processo stesso.

In merito al secondo punto, per le anomalie relative agli id, si procede inserendo l'attributo id nel tag section con il nome della sezione per completezza di informazione. Si tratta di un attributo non obbligatorio da specifiche ma opzionale, nei nostri casi d'uso l'abbiamo considerato e inserito, mantenendo la corretta sintassi, esplicitata sul POCD ovvero: <section ID="nome_section">. Per le anomalie dovute alle sezioni opzionali, si chiede di fare riferimento al word e all'excel forniti per ciascun caos di test. Nel dettaglio, i casi di test pensati prevedono la presenza anche di sezioni opzionali da specifiche ma necessarie per come sono stati pensati i casi di test trattati e spiegati nel word con le corrette valorizzazioni riportate nell'excel.

**Comment by CidSoftwareDev** [comment]
Buongiorno,
alla luce della sua risposta, al fine di proseguire nelle fasi di accreditamento, l'unico modo che abbiamo è utilizzare dati hard-coded per i casi di test previsti, al fine di popolare le sezioni che non sono supportate dall'applicativo.
