### ISSUE TITLE
Errore 403 - Unauthorized request content durante validazione

### ISSUE THREAD

**Issue by medarchiver** [ministero-salute/it-fse-support#154]
Buongiorno,

durante il processo di validazione otteniamo l'errore 403 - Unauthorized request content:

`{
    "type": "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
    "title": "AuthorizationContentDeny",
    "status": 403,
    "detail": "Unauthorized request content",
    "govway_id": "c3e846a2-c2fc-11ed-a9a6-005056ae7395"
}
`

Alleghiamo il sign token e l'auth token.

[auth_token.txt](https://github.com/ministero-salute/it-fse-support/files/10977492/auth_token.txt)
[sign_token.txt.txt](https://github.com/ministero-salute/it-fse-support/files/10977494/sign_token.txt.txt)

Sapete indicarci cosa stiamo sbagliando?

Grazie mille.

Cordiali saluti.

**Comment by masciamariotti** [comment]
Buongiorno,
da una prima analisi sembrerebbe che stia inviando all'interno dell' auth token un parametro errato: "kyd" mentre dovrebbe essere "kid". Ma se non lo valorizza, in quanto opzionale, non lo dovrebbe inviare.
Inoltre le chiederemmo gentilmente di allegare di nuovo il sign_token in quanto il file sembra essere vuoto.
Grazie

**Comment by medarchiver** [comment]
Buongiorno,

chiedo scusa: ecco il sign token.

[sign_token.txt](https://github.com/ministero-salute/it-fse-support/files/10977709/sign_token.txt)

Controlliamo subito la chiave indicata.

Grazie.

**Comment by medarchiver** [comment]
Abbiamo eliminato il parametro "kyd" e riprovato. Riceviamo il medesimo errore.

`{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"134408de-c302-11ed-a9a6-005056ae7395"}`

**Comment by medarchiver** [comment]
Grazie! Abbiamo fatto una nuova richiesta con le correzioni che ci avete indicato:

`{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"b79b7b3c-c30b-11ed-a9a6-005056ae7395"}`

Questi i due token:


[20230315104906_auth_token.txt](https://github.com/ministero-salute/it-fse-support/files/10978251/20230315104906_auth_token.txt)
[20230315104906_sign_token.txt](https://github.com/ministero-salute/it-fse-support/files/10978252/20230315104906_sign_token.txt)

**Comment by masciamariotti** [comment]
Da ulteriore check dovrebbe correggere, nel sign_token, il parametro `subject_application_versions `--> il parametro corretto è `subject_application_version`

**Comment by IStacchiotti** [comment]
Buongiorno, la invitiamo a verificare il parametro _sub_ del bearer token. Questo valore infatti non risulta coerente con quanto atteso: 'VRDMRC67T20I257E^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO'.

Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, la invitiamo a verificare il parametro _sub_ del bearer token. Questo valore infatti non risulta coerente con quanto atteso: 'VRDMRC67T20I257E^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO'.

Grazie.

**Comment by medarchiver** [comment]
Buongiorno! Grazie! Ora ricevo 502 - Invalid response received from the API Implementation.

Apro un'altra issue o andiamo avanti su questa?

`{"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"d8b82252-c3e0-11ed-a9a6-005056ae7395"}`

**Comment by IStacchiotti** [comment]
Buon pomeriggio,
dalle analisi è emerso che nella requestBody non sta inviando il Content-Type (Content-Type: application/json). Può verificare cortesemente? Grazie

**Comment by medarchiver** [comment]
Salve!
Bug della libreria, risolto, ma ci deve essere ancora qualcos'altro che non va...

`{"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"f940851c-c40c-11ed-a9a6-005056ae7395"}`

**Comment by medarchiver** [comment]
Se avete il trace di una richiesta che va a buon fine, possiamo confrontare con la nostra e vedere se ci salta qualcosa all'occhio. Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, dalle verifiche è emerso che non viene letto correttamente il content type. Di seguito il messaggio d'errore riscontrato a sistema:
```
Validazione [interface] del contenuto applicativo della risposta fallita: Validation error(s) :
Content type 'null' is not allowed for body content. (code: 203)
```
Le suggeriamo di modificare la request eliminando i ";" evidenziati in grigio di seguito:

Content-Disposition: form-data; name="requestBody"`; `
Content-Type: application/json

{"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VERIFICA"}------------8db2644323d0457
Content-Disposition: form-data; name="file"; filename="test.pdf"`;` 
Content-Type: application/pdf

**Comment by medarchiver** [comment]
Perfetto! Abbiamo eliminato i ";" indicati. Il problema persisteva. Considerato però che ci avete detto che il problema era nel content-type, abbiamo configurato la procedura in modo da mettere un carriage return prima del boundary e ora siamo andati al passo successivo (problema nell'estrazione del cda) ma questa issue è chiusa. La richiesta accettata è questa:

`Content-Disposition: form-data; name="requestBody"
Content-Type: application/json

{"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VERIFICA"}
------------8db26ef28398ede
Content-Disposition: form-data; name="file"; filename="test.pdf"
Content-Type: application/pdf
`

Grazie mille per le indicazioni.
