### ISSUE TITLE
ERRORE-47 e ERROR-48 per representedOrganization

### ISSUE THREAD

**Issue by stefanomastrogiacomo** [ministero-salute/it-fse-support#156]
Salve a tutti,
abbiamo notato un aggiornamento sullo schematron FSE_LAB che introduce almeno due nuovi controlli:
ERRORE-47 e ERRORE-48.
<rule context="//hl7:name[not(parent::hl7:informationRecipient) and not(parent::hl7:patient) and not(contains(local-name(..), 'Person'))]"><assert test="count(hl7:delimiter)=0 and count(hl7:prefix)=0 and count(hl7:suffix)=0">ERRORE-47| L’elemento 'name' di un'organizzazione non deve contenere i sotto elementi 'delimiter', 'prefix', 'suffix'.</assert></rule><rule context="//hl7:name"><assert test="count(hl7:delimiter)=0">ERRORE-48| L’elemento 'name' del soggetto non deve contenere il sotto elemento 'delimiter'.</assert></rule>
Vi chiediamo se è confermato il senso di questi controlli.
In specifici contesti, infatti, puo' presentarsi come sistematica la situazione sotto indicata nell'immagine: la valorizzazione dei tag delimiter, prefix e suffix.

Se pero', nel legalAuthenticator nel tag representedOrganization, non possiamo usare i campi delimiter prefix e suffix - previsti dallo schema xsd generico - i campi rimanenti, utili allo scopo di descrivere representedOrganization, rimarrebbero family e given.
Questi campi ci sembrano poco rappresentativi per descrivere una representedOrganization
Segue estratto di esempio:
 
![image](https://user-images.githubusercontent.com/124671051/225376403-16872bf6-ac4d-44e9-a284-cb87e87c4a86.png)

Grazie in anticipo
Stefano

**Comment by IStacchiotti** [comment]
Grazie della segnalazione. 
Nei controlli 47 e 48 sono stati vincolati i name delle organizzazioni alla non presenza di quei sotto elementi, quali delimiter, prefix e suffix. E' possibile però considerare il name come un elemento con dataType="ST" ovvero una stringa, quindi all'interno dello stesso tag name inserire le informazioni di interesse ovvero: <name>Nome_Azienda, Codice, Dettaglio</name>.

**Comment by IStacchiotti** [comment]
Buon pomeriggio, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
