### ISSUE TITLE
[BAD REQUEST] - Additional property 'descriptions' is not allowed

### ISSUE THREAD

**Issue by apsstn** [ministero-salute/it-fse-support#157]
Buongiorno,
abbiamo aggiornato le chiamate aggiungendo i due nuovi campi (descriptions e administrativeRequest) ma danno errore (come se non venissero accettate dal GTW).

ESEMPIO:

CHIAMATA (mandiamo solo i requestBody per semplicità)

```
Content-Disposition: form-data; name="requestBody"

{
  "healthDataFormat": "CDA",
  "mode": "ATTACHMENT",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.f0fc2f5b2b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "tipologiaStruttura": "Ospedale",
  "attiCliniciRegoleAccesso": [
    "PUBLICPOL"
  ],
  "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^111113",
  "identificativoRep": "ID_REPOSITORY",
  "tipoDocumentoLivAlto": "WOR",
  "assettoOrganizzativo": "AD_PSC001",
  "tipoAttivitaClinica": "PHR",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.4.3.2",
  "priorita": true,
  "descriptions": [
    "019655^Bentelan^2.16.840.1.113883.2.9.6.1.5"
  ]
}
```

RISPOSTA
`{
  "type": "https://govway.org/handling-errors/400/InvalidRequestContent.html",
  "title": "InvalidRequestContent",
  "status": 400,
  "detail": "Request content not conform to API specification: Validation error(s) :\nbody.requestBody: Additional property 'descriptions' is not allowed. (code: 1000)\nFrom: body.requestBody.<#/components/schemas/PublicationCreationReqDTO>.<additionalProperties>\n",
  "govway_id": "a55783ea-c3bb-11ed-adb9-005056ae54fa"
}`

Abbiamo inoltre notato che la documentazione di github è diversa rispetto al PDF di affinity aggiornato (https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20tecniche%20per%20l%E2%80%99interoperabilita%CC%80%20tra%20i%20sistemi%20regionali%20di%20FSE%20AffinityDomainItalia_Versione%202.4.1%20%28Errata%20Corrige%20del%2021.02.2023%29.pdf)

Nello specifico sul PDF viene indicato che il campo

XDSDocumentEntry.Slot – administrativeRequest

è la concatenazione di 2 valori 

[CODICE]^[Descrizione]

SSN^Regime SSN

Mentre su github (https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#22-processo-di-autenticazione3) sembvra essere una stringa contenente solo SSN (codice).

Attendiamo chiarimenti per entrambi i dubbi,
Grazie

**Comment by apsstn** [comment]
Buongiorno, novità?
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, potrebbe riprovare cortesemente? Il problema non dovrebbe più ripresentarsi, grazie.

**Comment by apsstn** [comment]
Ciao @IStacchiotti 

No ci sono 2 errori:

1) `Valorizzare correttamente il campo descriptions rispettando la forma: [CODICE]^[Descrizione]^[OID]`

    ma noi inviamo esattamente quanto indicato nella documentazione ovvero  un array con la concatenazione dei 3 valori
    
    ```
{
  "codFiscaleRichiedente": "SSSMNN75B01F257L",
  "idOrganizzazione": "190",
  "descOrganizzazione": "Regione Sicilia",
  "codStrutturaUtente": "201123456",
  "ruoloRichiedente": "AAS",
  "codFiscaleAssistito": "GTWGWY82B42G920M",
  "presaInCarico": true,
  "tipoDocDaRegistrare": "('11502-2^^2.16.840.1.113883.6.1')",
  "idApplicativoUtente": "120",
  "vendorApplicativoUtente": "Regione Lazio",
  "versioneApplicativoUtente": "R2",
  "tipoInjection": "ATTACHMENT",
  "formatoDatiSanitari": "CDA",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.6c2f18b42c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "tipologiaStruttura": "Ospedale",
  "attiCliniciRegoleAccesso": [
    "PUBLICPOL"
  ],
  "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^290701",
  "identificativoRep": "ID_REPOSITORY",
  "tipoDocumentoLivAlto": "WOR",
  "assettoOrganizzativo": "AD_PSC001",
  "tipoAttivitaClinica": "PHR",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.4.3.2",
  "priorita": true,
  "descriptions": [
    "019655^test^2.16.840.1.113883.2.9.6.1.11"
  ]
}
```
    

2)  Request content not conform to API specification: Validation error(s) :\nbody.requestBody.administrativeRequest: Value 'SSN^Regime SSN' is not defined in the schema. (code: 1006)\nFrom: body.requestBody.<#/components/schemas/PublicationCreationReqDTO>.administrativeRequest.<enum>\n


che è il secondo punto di cui chiedevo spiegazioni, ovvero la documentazione ufficiale  ( https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20tecniche%20per%20l%E2%80%99interoperabilita%CC%80%20tra%20i%20sistemi%20regionali%20di%20FSE%20AffinityDomainItalia_Versione%202.4.1%20%28Errata%20Corrige%20del%2021.02.2023%29.pdf) 

dice che il valore administrativeRequest è la concatenazione di 2 valori ed è quello che inviamo

```
{
  "codFiscaleRichiedente": "SSSMNN75B01F257L",
  "idOrganizzazione": "190",
  "descOrganizzazione": "Regione Sicilia",
  "codStrutturaUtente": "201123456",
  "ruoloRichiedente": "AAS",
  "codFiscaleAssistito": "GTWGWY82B42G920M",
  "presaInCarico": true,
  "tipoDocDaRegistrare": "('11502-2^^2.16.840.1.113883.6.1')",
  "idApplicativoUtente": "120",
  "vendorApplicativoUtente": "Regione Lazio",
  "versioneApplicativoUtente": "R2",
  "tipoInjection": "ATTACHMENT",
  "formatoDatiSanitari": "CDA",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.6c2f18b42c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "tipologiaStruttura": "Ospedale",
  "attiCliniciRegoleAccesso": [
    "PUBLICPOL"
  ],
  "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^290701",
  "identificativoRep": "ID_REPOSITORY",
  "tipoDocumentoLivAlto": "WOR",
  "assettoOrganizzativo": "AD_PSC001",
  "tipoAttivitaClinica": "PHR",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.4.3.2",
  "priorita": true,
  "administrativeRequest": "SSN^Regime SSN"
}
```
    

Grazie

**Comment by apsstn** [comment]
@IStacchiotti @zukka77  Novità?

**Comment by IStacchiotti** [comment]
Buon pomeriggio, la issue è relativa al fatto che si sta tentando di invocare il gtw utilizzando una stringa piuttosto che un enumerativo. La documentazione a cui si fa riferimento è quella per l'integrazione verso INI e non verso il gtw. Dal seguente [swagger]( https://github.com/ministero-salute/it-fse-support/blob/main/openapi/gateway/swagger_gtw.yaml) si evincono i valori enumerativi con cui l'utente può invocare il gtw

**Comment by apsstn** [comment]
Buongiorno @IStacchiotti , 

e per quanto riguarda il primo punto?

Mi può rispondere al punto1?

Grazie

**Comment by apsstn** [comment]
Ciao @IStacchiotti 

Per quanto riguarda il punto1 invece?E`da 3 settimane che da errore. 

Ho riprovato ora ad inviare la description ma da errore

`{"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"d94a9c7e-d1d8-11ed-8570-005056ae7395"}`

Grazie

**Comment by apsstn** [comment]
Ciao @IStacchiotti 
Novità?

**Comment by masciamariotti** [comment]
Buongiorno @apsstn,
da analisi più approfondite sembrerebbe che stia chiamando il servizio di validazione
`https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation`
 (e non quello di pubblicazione
`https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents`
 per il quale è stato aperto il ticket).
Potrebbe cortesemente riprovare e/o confermare che l'errore è effettivamente in validazione?

**Comment by apsstn** [comment]
Buongiorno @masciamariotti 
no il problema era sulla pubblicazione (non abbiamo la logica implementata sulla validazione).

Ho fatto delle prove e ora sembra funzionare.

Grazie
