### ISSUE TITLE
Errori accreditamento non chiari

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#159]
Buongiorno,
ho ricevuto il file contenente errori di validazione
Cosa si intende per "CDA contenuto nel PDF non conforme a quello associato al TraceID"?

- questo errore

`"id" : 7,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='074' attribute='code' actual = '491.2' expected = '300.01'>ClinicalDocument/component/structuredBody/component/section[ID='Motivo_Ricovero']/entry/observation/value</error>"
`
perchè viene segnalato? riguarda il caso OK 02 della LDO che indica come motivo del ricovero la BPCO. il codice 300.01 si riferisce al disturbo di panico.

- Gli errori `ClinicalDocument/component/structuredBody/component/section[ID='Inquadramento_clinico_iniziale']` perchè sono segnalati? il caso OK 02 della LDO indica che la sezione "può essere utilizzata" e nel test la sezione non è stata utilizzata.

- Gli errori relativi a Test con Id 8 sono dello stesso tipo . 

- Errori relativi a Id 24:

errore `"<error code='030' attribute='displayName' actual = 'Problema all’accesso' expected = 'Problema all'accesso Ragione della visita'>ClinicalDocument/component/structuredBody/component/section[ID='Motivo_Visita']/entry/observation/code</error>"` 
nella documentazione HL7 Italia è riportato "Problema all’accesso"

Errore `<error code='067' attribute='classCode' actual = '' expected = 'ENC'>ClinicalDocument/component/structuredBody/component/section[ID='Dimissione']/entry/act/entryRelationship/encounter</error>` perchè viene segnalato? non c'è ricovero.

Errore `"<error code='102' attribute='codeSystemName' actual = 'ICD9CM' expected = 'ICD9-CM EsitoTrattamento_VPS'>ClinicalDocument/component/structuredBody/component/section[ID='Dimissione']/entry/act/entryRelationship/observation/value</error>"` . Non c'è traccia nella documentazione HL7 Italia e neanche nel file Excel "Casi KO" del valore "ICD9-CM EsitoTrattamento_VPS". Invece nella documentazione HL7 è presente "EsitoTrattamento_VPS"

Spero in un sollecito riscontro
Grazie

Allego file errori
[errors.zip](https://github.com/ministero-salute/it-fse-support/files/10989542/errors.zip)

**Comment by IStacchiotti** [comment]
Grazie della segnalazione. Chiariamo tutti i dubbi segnalati:

1. "id" : 7, "error" : "VERIFICA_NON_SUPERATA", "description" : "<error code='074' attribute='code' actual = '491.2' expected = '300.01'>ClinicalDocument/component/structuredBody/component/section[ID='Motivo_Ricovero']/entry/observation/value</error>" ->Inserire il codice che è presente nell’excel fornito e che consente la riproduzione del caso di test in esame

2. ClinicalDocument/component/structuredBody/component/section[ID='Inquadramento_clinico_iniziale'] perchè sono segnalati? il caso OK 02 della LDO indica che la sezione "può essere utilizzata" e nel test la sezione non è stata utilizzata. -> inserire la sezione Inquadramento Clinico Iniziale che da specifiche è opzionale, ma nel caso d’uso pensato è necessaria per completezza di informazioni

3. Gli errori relativi a Test con Id 8 sono dello stesso tipo. -> Correzione degli errori nel modo sopra citato

Errori relativi a Id 24:
4. errore "<error code='030' attribute='displayName' actual = 'Problema all’accesso' expected = 'Problema all'accesso Ragione della visita'>ClinicalDocument/component/structuredBody/component/section[ID='Motivo_Visita']/entry/observation/code</error>"
nella documentazione HL7 Italia è riportato "Problema all’accesso" -> provvediamo a rendere più parlante il messaggio poiché in base al codice associato o si riferisce al problema all’accesso o alla ragione della visita ma si chiede di correggere la scrittura del displayName con il carattere speciale corretto

5. Errore <error code='067' attribute='classCode' actual = '' expected = 'ENC'>ClinicalDocument/component/structuredBody/component/section[ID='Dimissione']/entry/act/entryRelationship/encounter</error> perchè viene segnalato? non c'è ricovero. -> inserire encounter perché riguarda la collocazione dell'assistito post ricovero e quindi l’elemento deve essere inserito come riportato nell’excel fornito

6. Errore "<error code='102' attribute='codeSystemName' actual = 'ICD9CM' expected = 'ICD9-CM EsitoTrattamento_VPS'>ClinicalDocument/component/structuredBody/component/section[ID='Dimissione']/entry/act/entryRelationship/observation/value</error>" . Non c'è traccia nella documentazione HL7 Italia e neanche nel file Excel "Casi KO" del valore "ICD9-CM EsitoTrattamento_VPS". Invece nella documentazione HL7 è presente "EsitoTrattamento_VPS" -> provvediamo a rendere più parlante il messaggio poiché è possibile associare al code del value sia un codice presente nel dizionario EsitoTrattamento_VPS sia del dizionario ICD9-CM. Si chiede di modificare la scrittura del dizionario con il trattino ovvero, anziché ICD9CM, ICD9-CM.

**Comment by alessandropassamonti** [comment]
Grazie per le risposte

1. "id" : 7, "error" : "VERIFICA_NON_SUPERATA", "description" : "ClinicalDocument/component/structuredBody/component/section[ID='Motivo_Ricovero']/entry/observation/value" ->Inserire il codice che è presente nell’excel fornito e che consente la riproduzione del caso di test in esame

**ma nel file "CDA2_Lettera di Dimissione Ospedaliera_OK" non trovo nessuna evidenza che il codice da utilizzare sia il 300.01. C'è scritto invece "L'attributo code deve essere valorizzato con una codifica ICD9-CM ". Devo necessariamente utilizzare questo codice? e La descrizione?** 


2. ClinicalDocument/component/structuredBody/component/section[ID='Inquadramento_clinico_iniziale'] perchè sono segnalati? il caso OK 02 della LDO indica che la sezione "può essere utilizzata" e nel test la sezione non è stata utilizzata. -> inserire la sezione Inquadramento Clinico Iniziale che da specifiche è opzionale, ma nel caso d’uso pensato è necessaria per completezza di informazioni

**l'applicativo non gestisce Inquadramento_clinico_iniziale**

4. errore "<error code='030' attribute='displayName' actual = 'Problema all’accesso' expected = 'Problema all'accesso Ragione della visita'>ClinicalDocument/component/structuredBody/component/section[ID='Motivo_Visita']/entry/observation/code"
nella documentazione HL7 Italia è riportato "Problema all’accesso" -> provvediamo a rendere più parlante il messaggio poiché in base al codice associato o si riferisce al problema all’accesso o alla ragione della visita ma si chiede di correggere la scrittura del displayName con il carattere speciale corretto

**Devo ripetere il test e inserire "Problema all'accesso Ragione della visita"?**

5. Errore ClinicalDocument/component/structuredBody/component/section[ID='Dimissione']/entry/act/entryRelationship/encounter perchè viene segnalato? non c'è ricovero. -> inserire encounter perché riguarda la collocazione dell'assistito post ricovero e quindi l’elemento deve essere inserito come riportato nell’excel fornito

**anche qui non si capiva l'obbligatorietà del dato. Devo inserire dei valori particolari? da quale fonte?**

6. Errore "ClinicalDocument/component/structuredBody/component/section[ID='Dimissione']/entry/act/entryRelationship/observation/value" . Non c'è traccia nella documentazione HL7 Italia e neanche nel file Excel "Casi KO" del valore "ICD9-CM EsitoTrattamento_VPS". Invece nella documentazione HL7 è presente "EsitoTrattamento_VPS" -> provvediamo a rendere più parlante il messaggio poiché è possibile associare al code del value sia un codice presente nel dizionario EsitoTrattamento_VPS sia del dizionario ICD9-CM. Si chiede di modificare la scrittura del dizionario con il trattino ovvero, anziché ICD9CM, ICD9-CM.

**quindi devo correggere il valore in "ICD9-CM EsitoTrattamento_VPS"?**

**Sono questi i soli errori riscontrati ne 49 test case che ho prodotto?**

Grazie

**Comment by PRAFFO72** [comment]
Ci intromettiamo, avendo avuto gli stessi problemi (risolti), sperando di essere di aiuto.

>     4. 
> **Devo ripetere il test e inserire "Problema all'accesso Ragione della visita"?**
Il messaggio di errore riporta (in maniera poco leggibile) i due valori possibili per le due sezione contigue.
I valori accettati nel **displayName** sono "Problema all'accesso" e "Ragione della visita", a seconda di quale sezione si sta popolando.
Attenzione che la grafia sia corretta (nel vostro esempio dovete sostituire l’apostrofo con l'apice).
 
>     5. 
> **anche qui non si capiva l'obbligatorietà del dato. Devo inserire dei valori particolari? da quale fonte?**
Salvo refusi, i valori corretti da inserire sono descritti minuziosamente nei file xlsx reperibili in [questa](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/2-Verbale%20di%20Pronto%20Soccorso) pagina.

>     6. 
> **quindi devo correggere il valore in "ICD9-CM EsitoTrattamento_VPS"?**
Come per il caso 4, si tratta di due valori possibili in **codeSystemName**: "ICD9-CM" e "EsitoTrattamento_VPS".
Inserite quello relativo al **codeSystem** utilizzato, facendo anche qui attenzione alla grafia corretta (con il trattino).

**Comment by alessandropassamonti** [comment]
Grazie mille
Ho scaricato i nuovi file di VPS (aggiornati 16 ore fa) e ora vedo che ci sono tutti i dati
attendo risposta dal team FSE per gli altri quesiti.

grazie ancora

**Comment by alessandropassamonti** [comment]
I test  con Id 7 e 8 (casi OK LDO) da quello che ho capito necessitano delle sezioni opzionali che l'applicativo non gestisce .  Per questi test indicherò la non applicabilità
Per il test con id 24 (caso OK VPS) , ripeterò il test con le correzioni suggerite.

**Potete indicarmi se gli errori riscontrati sono solo questi?**

grazie

**Comment by IStacchiotti** [comment]
Grazie per la segnalazione.
Per quanto concerne il dubbio 1 è necessario inserire il codice 300.01 per riprodurre il caso d'uso e potersi accreditare.
Mentre per il dubbio 2 se l'applicativo non gestisce la sezione Inquadramento Clinico Iniziale, bisogna riportare NO nell'apposita colonna di APPLICABILITA'.

Mentre per i casi di test con Id 7 e 8 (casi OK LDO) che necessitano delle sezioni opzionali che l'applicativo non gestisce , bisogna inserire NO nell'apposita colonna APPLICABILITA'.

Per il test con id 24 (caso OK VPS) , bisogna ripetere il test con le correzioni che sono state richieste per la fase di accreditamento.

**Comment by alessandropassamonti** [comment]
grazie 
è possibile sapere se questi sono tutti gli errori rilevati e quindi gli altri sono positivi?

**Comment by IStacchiotti** [comment]
Buongiorno, sì, le confermiamo che si tratta di tutti gli errori rilevati dalla procedura automatica.

**Comment by alessandropassamonti** [comment]
grazie
