### ISSUE TITLE
Schematron RAD /LDO Dubbio relativo a observation relativa a Reazioni in sezione Allergie

### ISSUE THREAD

**Issue by giuseppe-fasulo** [ministero-salute/it-fse-support#16]
Si segnala quanto segue con riferimento alla linea guida HL7 RAD , NON alla vostra implementazione. 
A pag 81 della linea guida RAD , la codifica LOINC per le descrizione della reazione, nella COnf  rad 127 è indicata come 75321-0 Obiettività clinica e la stessa codifica viene usata nell'esempio della implementazione codificata. 
MA, nell'esempio pag 82 dell'implementazione non codificata, sempre relativa alla descrizione della reazione, viene impiegato il codice LOINC 5321-0 Clinical finding.  A me sembra un refuso. Voi come lo state interpretando?

**Comment by gndibiase** [comment]
Si tratta, come viene correttamente evidenziato, di un refuso presente sulla guida. Il codice esatto relativo al valore della codifica LOINC in questione è  “75321-0” con displayName “Obiettività clinica”. Tale codice è utilizzato sia nella descrizione della reazione avversa in forma codificata che non codificata.
