### ISSUE TITLE
Errore Validazione VPS - Valutazione Acutezza (Dimissione) in caso di decesso

### ISSUE THREAD

**Issue by PRAFFO72** [ministero-salute/it-fse-support#165]
Salve, durante un test di validazione VPS, viene generato un errore di vocabolario :
_Almeno uno dei seguenti vocaboli non è censito: [CodeSystem: 2.16.840.1.113883.2.9.6.1.54.4, Codes: N]_

L'errore riguarda l'attributo "code" dell'elemento :
_ClinicalDocument/component/structuredBody/component/section[@ID="Dimissione"]/entry[@ID="Valutazione_Acutezza"]/observation/value_

Secondo la [documentazione](http://www.hl7italia.it/sites/default/files/Hl7/SuperUser/docs/pubblicati/IG-CDA2-VPS/1.1.1/HL7IT-IG_CDA2_VPS-v1.1.1-S.pdf) il CodiceTriage_VPS (descritto a pag.203) è derivato da quello del tracciato di P.S. consultabile in [questa](https://www.salute.gov.it/portale/temi/p2_6.jsp?lingua=italiano&id=2992&area=sistemaInformativo&menu=emergenza) pagina.

Tale [documento](https://www.salute.gov.it/imgs/C_17_pagineAree_2992_6_file.pdf) descrive a pag. 110 proprio il Livello di Appropriatezza alla Dimissione.
Tra valori ammessi (evidenziati in blu), oltre ai cinque numerici, è presente anche il valore "N" (deceduto).

È dunque un problema di dizionario incompleto per il codSystem 2.16.840.1.113883.2.9.6.1.54.4 ?
In caso invece fossero ammessi solo i cinque valori numerici, come dobbiamo compilare questa sottosezione in caso di decesso?

**Comment by IStacchiotti** [comment]
Grazie della segnalazione. Si richiede gentilmente il CDA2 - VPS usato per il test di validazione.

**Comment by PRAFFO72** [comment]
[CDA_decesso.zip](https://github.com/ministero-salute/it-fse-support/files/11000964/CDA_decesso.zip)

Grazie per la risposta. Ecco il file, in versione semplificata (genera comunque lo stesso errore).

**Comment by PRAFFO72** [comment]
Per informazione, anche gli esempim caricati oggi in [questa ](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/Documenti%20XML%20Casi%20OK/2%20-%20Casi%20OK%20Verbale%20di%20Pronto%20Soccorso) pagina generano un errore analogo (Per il valore "R", codice rosso dei vecchi tracciati P.S.)

**Comment by IStacchiotti** [comment]
Grazie per aver allegato il cda2.
Abbiamo apportato la modifica nel dizionario Codice Triage_VPS, a seguito della segnalazione, con tutti i codici presenti nelle specifiche funzionali EMUR.
Si prega di ripetere la validazione del CDA2 che ci è stato inviato.

**Comment by PRAFFO72** [comment]
Grazie: la validazione è stata eseguita con successo.
