### ISSUE TITLE
Errore Validazione VPS

### ISSUE THREAD

**Issue by vvarratta** [ministero-salute/it-fse-support#166]
Buonasera, 
sto eseguendo dei test con il container docker.
Ho il seguente errore nella validazione di un CDA del VPS:
"Sezione Parametri Vitali: l'elemento entry/organizer/component/observation/code DEVE essere valorizzato con gli attributi code='86678-0' e @codeSystem='2.16.840.1.113883.6.1'" 
relativo appunto all'elemento " ClinicalDocument/component/structuredBody/component/section[@ID="Parametri_Vitali"]/code/@code " della sezione "Parametri Vitali".
Questo vuol dire che il codice può assumere soltanto il valore "86678-0" **per tutti** i parametri vitali? 
Ringrazio anticipatamente,
Saluti,
Valentina Varratta

**Comment by IStacchiotti** [comment]
Buongiorno, grazie della segnalazione. Sì, per eseguire il caso di test in esame correttamente è necessario mettere il codice che è stato inserito nell'excel fornito.

**Comment by vvarratta** [comment]
Buongiorno, grazie per la risposta.
Ancora un dubbio. relativamente all'elemento di dettaglio dei parametri vitali "ClinicalDocument/component/structuredBody/component/section[@ID="Parametri_Vitali"]/entry/organizer/component/observation/code/@code" nell'excel e nella documentazione viene detto che tale campo deve essere valorizzato con un parametro derivato da "2.16.840.1.113883.6.1". 
I valori che quindi può assumere il codice di dettaglio sono ricavabili dall'elenco https://loinc.org/8716-3 ? ad esempio '11289-6' per la temperatura corporea?
Valentina Varratta

**Comment by IStacchiotti** [comment]
Grazie per la sua domanda. Si, se non è esplicitato alcun code nell'excel fornito ma solamente il sistema di codifica a cui far riferimento, è possibile inserire un codice che al meglio valorizzi il campo in esame.

**Comment by vvarratta** [comment]
Grazie, 
saluti
