### ISSUE TITLE
Errori accreditamento campi opzionali

### ISSUE THREAD

**Issue by Log80-svi** [ministero-salute/it-fse-support#168]
Buongiorno,
nel file Excel con la lista dei campi da valorizzare per i test delle lettere di dimissione ci sono alcuni campi del CDA che hanno obbligatorietà "OPZIONALE". Nel risultato dei test però ci sono stati restituiti errori causati dal non avere valorizzato campi "figli" di campi opzionali, che non sono presenti nel CDA in quanto non è stato inserito il campo "padre", che pensavamo fosse opzionale.

Per esempio nel file Execel "CDA2_Lettera di Dimissione Ospedaliera_OK" nella sezione "LDO - Caso di Test 1":

1. ClinicalDocument/component/structuredBody/component /section[\@ID="Condizioni_paziente_diagnosi_dimissione"]/entry -> **OPZIONALE**
2. ClinicalDocument/component/structuredBody/component /section[\@ID="Condizioni_paziente_diagnosi_dimissione"]/entry/observation -> **OBBLIGATORIO**

Viene restituito errore se non viene inserito il campo 2 (obbligatorio) che è figlio del campo 1, che però è opzionale, e non era stato inserito.

E' obbligatorio quindi inserire nel CDA anche tutti i campi che nei file Excel hanno obbligatorietà "OPZIONALE" per superare l'accreditamento? O sono obbligatori solo quei campi opzionali che hanno sfondo verde (presenti solo nei casi 2 e 3)?

Nel file Word "casi di test LDO.docx" per i casi 2 e 3 c'è scritto "Le sezioni opzionali che in questo caso d’uso **possono** essere utilizzate", cioè quelle colorate di verde, che quindi ci aspettiamo siano opzionali.

Per quanto riguarda invece i casi di test con CDA2 non validi (casi 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 per le LDO), nei file con la lista degli errori restituiteci dall'accreditamento non ci sono errori per questi casi. Questo vuol dire che abbiamo passato l'accreditamento per questi casi oppure verranno verificati successivamente?

Grazie
Stefano Rasi

**Comment by IStacchiotti** [comment]
Grazie per la segnalazione. Chiariamo di seguito i dubbi:

"E' obbligatorio quindi inserire nel CDA anche tutti i campi che nei file Excel hanno obbligatorietà "OPZIONALE" per superare l'accreditamento? O sono obbligatori solo quei campi opzionali che hanno sfondo verde (presenti solo nei casi 2 e 3)?"
**Si per superare l’accreditamento è necessario inserire tutti i campi opzionali riportati nell’excel che servono a completare il contenuto informativo di quello specifico caso d’uso**

"Nel file Word "casi di test LDO.docx" per i casi 2 e 3 c'è scritto "Le sezioni opzionali che in questo caso d’uso possono essere utilizzate", cioè quelle colorate di verde, che quindi ci aspettiamo siano opzionali."
**Nel word sono scritte le sezioni da inserire con la distinzione di quelle obbligatorie da specifiche e quindi presenti di default e quelle opzionali da specifiche ma rese obbligatorie per quello specifico caso d’uso che si sta riproducendo**

"Per quanto riguarda invece i casi di test con CDA2 non validi (casi 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 per le LDO), nei file con la lista degli errori restituiteci dall'accreditamento non ci sono errori per questi casi. Questo vuol dire che abbiamo passato l'accreditamento per questi casi oppure verranno verificati successivamente?"
**I casi sopra citati sono casi d’uso KO e quindi per la loro riproduzione bisogna eseguire correttamente quello che viene esplicitato nel file word fornito ovvero o la totale assenza dell’elemento o l’errata valorizzazione di un determinato valore.**

**Comment by Log80-svi** [comment]
Grazie per la risposta.

Non ci è chiaro però l'ultimo punto, per quanto riguarda l'accreditamento dei casi KO.

Il nostro dubbio era questo:

Nel file "errors.json" con la lista degli errori relativi all'accreditamento che ci è stato restituito, gli id dei casi d'uso KO non sono presenti (ci sono solo i 3 casi d'uso OK, per i quali quindi faremo le correzioni necessarie)

1. Questo vuol dire che abbiamo superato la verifica per i casi KO, visto che non sono presenti nel file "errors.json" che ci è stato restuito?
2. Oppure i casi d'uso KO non sono stati ancora verificati e li verificherete dopo che abbiamo superato la verifica dei casi OK, o comunque in un secondo momento?

Grazie
Stefano

**Comment by IStacchiotti** [comment]
Il json è comprensivo di tutti gli errori rilevati nella fase preliminare del processo di accreditamento. A conclusione di quest'ultimo, seguirà ulteriore comunicazione da parte del Dipartimento per la Trasformazione Digitale (DTD).

**Comment by IStacchiotti** [comment]
Buonasera, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
