### ISSUE TITLE
Informazioni Pull Request #121 EBIT Srl

### ISSUE THREAD

**Issue by EbitFSE** [ministero-salute/it-fse-support#169]
Buonasera, la settimana scorsa abbiamo sottomesso i documenti con la Pull Request "Accreditamento Ebit Srl (invio TestCases https://github.com/ministero-salute/it-fse-accreditamento/pull/121)",
dobbiamo fare altre attività o attendere un feedback via mail?
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, dovrebbe aver ricevuto una email con le istruzioni per andare avanti con la richiesta di accreditamento. Per necessità di supporto, può scrivere in questo thread. Grazie.

**Comment by EbitFSE** [comment]
Buongiorno, in seguito all' email con le istruzioni abbiamo provveduto a fare un nuovo upload del file report-checklist.xlsx,
ora attendiamo l'esito dopo la nuova sottomissione.
Grazie

**Comment by IStacchiotti** [comment]
Buon pomeriggio, confermiamo l'avvenuta ricezione della commit, seguiranno aggiornamenti via email. Non avendo avanzato richieste di supporto al momento, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso di necessità. Grazie
