### ISSUE TITLE
Riscontro standard HL7

### ISSUE THREAD

**Issue by danielepecoraro** [ministero-salute/it-fse-support#170]
Buongiorno,
dopo aver analizzato gli errori dell'accreditamento del gateway, abbiamo riscontrato una discrepanza tra i valori richiesti e il documento per gli standard di HL7: per i componenti dello structured body manca l'obbligatorietà dell'ID (sia nel documento del VPS che del LDO). Ci potete dare conferma di questa situazione o darci un risponso in merito? Grazie.

subject_application_vendor : ASL3 Genovese
subject_application_id : SIVIS
subject_application_version : v.1.0.0

**Comment by IStacchiotti** [comment]
Grazie della segnalazione.
La presenza dell'ID della sezione è resa obbligatoria per i casi d'uso
creati per completezza di informazione poiché esplicita in titolo della sezione.
Quindi è un attributo opzionale da POCD ma non è vietato l'inserimento nel cda2 purché venga scritto
in maniera corretta dal punto di vista della sintassi e poiché non è obbligatorio da specifiche,
non vi è alcun controllo lato schematron.
