### ISSUE TITLE
Errore Validazione CDA2 VPS

### ISSUE THREAD

**Issue by vvarratta** [ministero-salute/it-fse-support#171]
Buongiorno.
Tentando la validazione di un CDA2 di VPS ottengo questo errore:
[ERRORE-b171| Sezione Interventi Prestazioni Consulenze e Richieste: l'elemento entry/act/code DEVE essere valorizzato con gli attributi @code='76645-1' e @codeSystem='2.16.840.1.113883.6.1'.]

Da documentazione tale campo specifica la tipologia di prestazione, intervento, consulenza specialistica eseguita e può essere valorizzato secondo il codice LOINC ma utilizzando codici diversi da '76645-1' non passa la validazione. 
Per i test sto utilizzando la versione lite di it-fse-gtw-test-container.
si deve quindi impostare il solo codice indicato nell'errore per passare la validazione? 
Grazie,
Saluti,
Valentina Varratta

**Comment by IStacchiotti** [comment]
Grazie della segnalazione.
Abbiamo provveduto ad effettuare le modifiche, causa refuso, sullo schematron poiché non vi è alcun vincolo sul code dell'entry/act.
Consultando anche le specifiche HL7, vi è la CONF-VPS-206 che sottolinea solo l'obbligatorietà dell'elemento code che specifica la tipologia di prestazione ma non lo vincola a nessuna valorizzazione.
A valle del deploy con il caricamento dei nuovi file, l'errore non dovrebbe più verificarsi.

**Comment by vvarratta** [comment]
Grazie, saluti.
