### ISSUE TITLE
Response errore 400 - MCA

### ISSUE THREAD

**Issue by Mcataranto** [ministero-salute/it-fse-support#174]
A seguito di un ennesimo invio in ambiente di test per la validazione di un referto di laboratorio riceviamo l'errore 

Received request is not conform to interoperability profile

che non abbiamo capito se addebitare al contenuto o altro.

di seguito il print screen della response.

![WhatsApp Image 2023-03-20 at 19 57 40](https://user-images.githubusercontent.com/124721774/226546224-6e1f1401-79d9-4bef-9166-15fb23de725e.jpeg)

Grazie

**Comment by masciamariotti** [comment]
Buongiorno, dalle analisi è emerso che l'errore è dovuto al fatto che il token era scaduto al momento del test.
Come indicato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#23-note-su-autenticazione-e-token-jwt), è necessario generare nuovi JWT per ogni chiamata alle API.

**Comment by IStacchiotti** [comment]
Buonasera, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
