### ISSUE TITLE
Errore Gateway

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#177]
Buongiorno,
da ieri pomeriggio il Gateway risponde con l'errore sotto riportato anche per chiamate che fino a ieri mattina erano "success".
Si tratta di una modifica temporanea? 
Grazie

"code": "ERROR",
"userMessage": "Errore generico.",
"systemMessage": "Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.impl.FileSizeLimitExceededException: The field file exceeds its maximum permitted size of 1048576 bytes.",
"traceID": "4ac901f6102bdab6",
"spanID": "4ac901f6102bdab6",

**Comment by IStacchiotti** [comment]
Buongiorno, grazie per la segnalazione. Un chiarimento: nelle chiamate precedenti che andavano a buon fine, aveva impiegato lo stesso pdf? Le chiediamo inoltre la cortesia di allegare il pdf che ha prodotto l'errore, grazie

**Comment by Elisabetta-Tecchio-GPI** [comment]
Buongiorno,
 abbiamo compreso la motivazione dell'errore dovuta a una nostra implementazione ed abbiamo risolto. Non eravamo a conoscenza del limite di dimensione dei file, Maximum upload size exceeded.

Grazie

**Comment by IStacchiotti** [comment]
Buonasera, grazie per il feedback. La presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
