### ISSUE TITLE
Mancato accreditamento

### ISSUE THREAD

**Issue by domenico-capezzuto** [ministero-salute/it-fse-support#178]
Buongiorno,

riporto qui la medesima richiesta di chiarimenti inviata via mail circa il mancato accreditamento.

Dal log degli errori sembrerebbe che il sistema di verifica non sia stato in grado di estrarre il file cda.xml dal PDF,
sennò non si spiegano i numerosi valori “actual” vuoti.

Si tratta di un problema di iniezione del CDA?
Gli strumenti e le tecniche utilizzare sono le medesime messe a disposizione qui:

https://github.com/ministero-salute/it-fse-gtw-tools

Evidenzio inoltre che i PDF condivisi sono tutti stati sottoposti con successo al processo di validazione del gateway.

Allego per comodità il log degli errori ed i PDF oggetto dell’analisi.

Grazie.

[S3K_MancatoAccreditamento_20230314.zip](https://github.com/ministero-salute/it-fse-support/files/11038195/S3K_MancatoAccreditamento_20230314.zip)

**Comment by IStacchiotti** [comment]
Buonasera, da una prima analisi è emerso che i diversi actual vuoti dipendono dal fatto che nei cda condivisi non sono stati inseriti gli ID per alcune section come da richiesta excel. Potrebbe verificare? Grazie

**Comment by IStacchiotti** [comment]
Buonasera, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
