### ISSUE TITLE
Schematron RAD - Errore 76-  Dubbi sul controllo implementato

### ISSUE THREAD

**Issue by giuseppe-fasulo** [ministero-salute/it-fse-support#18]
ERRORE-76| Sezione Storia Clinica: L'elemento entry/organizer/component/observation deve avere al più 2 elementi 'entryRelationship' di tipo observation: - Età di insorgenza (OBBLIGATORIO) - Età di decesso (OPZIONALE)

Salve.  Segnalo che ho qualche dubbio su questo controllo.  La conf -rad 106, pag 72 dice che PER fornire informazioni relative all'età di insorgenza o morte del soggetto si deve usare una entryRelationship/observation dentro component/observation. Ma NON mi sembra che ci sia scritto che si debbano necessariamente fornire tali informazioni. In altre parole io interpreto che component/observation/entryRelationship/observation  sia  opzionale  (nella pratica mi pare anche plausibile che il paziente possa non ricordare quando un familiare sia morto a  causa di una patologia, oppure non ricordi quale età avesse il familiare quando è insorta la patologia) .  Inoltre non mi è chiaro perchè dovrebbe avere sino a due entryRelationship/observation: se occorre indicare che un familiare ha avuto una malattia e poi di quella malattia è anche deceduto mi pare sufficiente ripetere un altro elemento component/observation/entryRelationship/observation  sotto entry/organizer

**Comment by LeonardoAlcaro** [comment]
Ciao Giuseppe, come sempre grazie della segnalazione ti confermo che la sezione stessa Anamnesi Familiare e' opzionale , inoltre come evidenziato da te nell'esempio delle specifiche RAD sono entrambi opzionali. Rilasseremo il controllo e grazie
