### ISSUE TITLE
VALIDAZIONE CDA2 RAD - errore generico token

### ISSUE THREAD

**Issue by synlabsdn** [ministero-salute/it-fse-support#180]
Buongiorno,

stiamo predisponendo il file cda2 per la radiologia cercando di validarlo utilizzando il relativo schematron a disposizione.

durante la validazione otteniamo il seguente messaggio di errore che sembra indicare un problema relativo al tag ENTRY

'/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][1]' has an invalid token.

Non riusciamo a capire a cosa faccia riferimento l'errore e quale sia il token a cui fa riferimento
Potreste darci qualche indicazione in merito?

[cda RAD.txt](https://github.com/ministero-salute/it-fse-support/files/11038657/cda.RAD.txt)

**Comment by ponsilva** [comment]
Buongiorno, 
condivido un elemento che forse può essere utile.

Nella verifica dei CDA si può aggiungere un passo preliminare che è la validazione con l'XSD 
https://github.com/ministero-salute/it-fse-support/tree/main/validazione/xsd

In genere è di aiuto per ottenere un CDA con struttura corretta.
Poi si può utilizzare lo schematron, che esegue dei controlli più specifici.

**Comment by IStacchiotti** [comment]
Buon pomeriggio @synlabsdn, grazie della segnalazione. Si chiede gentilmente di effettuare una verifica sulla struttura del cda2 che si vuole validare poiché strutturalmente non è in linea con l'XSD e quindi non valido sintatticamente.
