### ISSUE TITLE
Errore di sintassi MCA

### ISSUE THREAD

**Issue by Mcataranto** [ministero-salute/it-fse-support#182]
Riceviamo errore di sintassi come da risposta

{
    "traceID": "f9a355befaac1a67",
    "spanID": "f9a355befaac1a67",
    "type": "/msg/syntax",
    "title": "Errore di sintassi.",
    "detail": "ERROR: -1,-1 cvc-complex-type.3.2.2: Attribute 'value' is not allowed to appear in element 'value'.,ERROR: -1,-1 cvc-complex-type.3.2.2: Attribute 'value' is not allowed to appear in element 'value'.,ERROR: -1,-1 cvc-complex-type.3.2.2: Attribute 'value' is not allowed to appear in element 'value'.,ERROR: -1,-1 cvc-complex-type.3.2.2: Attribute 'value' is not allowed to appear in element 'value'.,ERROR: -1,-1 cvc-complex-type.3.2.2: Attribute 'value' is not allowed to appear in element 'value'.,ERROR: -1,-1 cvc-complex-type.3.2.2: Attribute 'value' is not allowed to appear in element 'value'.,ERROR: -1,-1 cvc-complex-type.3.2.2: Attribute 'value' is not allowed to appear in element 'value'.,ERROR: -1,-1 cvc-complex-type.3.2.2: Attribute 'value' is not allowed to appear in element 'value'.,ERROR: -1,-1 cvc-complex-type.3.2.2: Attribute 'value' is not allowed to appear in element 'value'.,ERROR: -1,-1 cvc-complex-type.3.2.2: Attribute 'value' is not allowed to appear in element 'value'.",
    "status": 400,
    "instance": "/validation/error",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.160112.4.4.6d803024b2d4f8d4845b4ce9636dc0e5f067ead9a1ebb8da5f47e13d2e7d9d90.c114ea84f5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

**Comment by IStacchiotti** [comment]
Buongiorno, potrebbe cortesemente allegare il cda? Grazie.

**Comment by Mcataranto** [comment]
Buonasera

Allego come da accordi file cda.xml

Grazie

[cda.zip](https://github.com/ministero-salute/it-fse-support/files/11041937/cda.zip)

**Comment by Mcataranto** [comment]
Buongiorno

Risolto 

Grazie sempre per la preziosa collaborazione

**Comment by IStacchiotti** [comment]
Buona pomeriggio, grazie per il feedback, la presente viene chiusa come risolta allora. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
