### ISSUE TITLE
Correzioni effettuate

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#185]
Buongiorno,
comunichiamo che abbiamo effettuato le correzioni indicate da fse_support@sogei.it ieri per 
NGH PS (VPS)
IE-OPERA (VPS)
CCE Cartella Clinica Elettronica (LDO)

e caricato una nuova pull request: https://github.com/ministero-salute/it-fse-accreditamento/pull/166

con anche la soluzione software NGH ADT (LDO).

Grazie

**Comment by IStacchiotti** [comment]
Buonasera @Elisabetta-Tecchio-GPI, le confermiamo che la pull request è stata presa in carico. Procediamo pertanto alla chiusura del presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Sarà possibile procedere con la riapertura per ricevere supporto mirato. Grazie.
