### ISSUE TITLE
ERRORE-b204| Sezione Terapia Farmacologica in Pronto Soccorso: l'elemento entry/substanceAdministration/effectiveTime deve avere l'elemento 'low' valorizzato

### ISSUE THREAD

**Issue by vvarratta** [ministero-salute/it-fse-support#186]
Buonasera,
sto facendo dei test di validazione per un VPS.
Come da oggetto, il servizio restituisce l'errore semantico "Sezione Terapia Farmacologica in Pronto Soccorso: l'elemento entry/substanceAdministration/effectiveTime deve avere l'elemento 'low' valorizzato" 
in realtà nell'elemento indicato non manca l'elemento 'low' ma l'elemento 'high', che comunque è opzionale. 
Da documentazione
CONF-VPS-251: L’elemento substanceAdministration/effectiveTime/high è un elemento OPZIONALE
Allego il cda in questione.
Attendo vostro cortese riscontro,
grazie,
Valentina Varratta
[CDA.xml.txt](https://github.com/ministero-salute/it-fse-support/files/11054951/CDA.xml.txt)

**Comment by IStacchiotti** [comment]
Buon pomeriggio @vvarratta, grazie per la segnalazione. Le confermiamo che è stata rilasciata una modifica sul controllo dell'elemento `effectiveTime` nello schematron del VPS. L'errore pertanto non dovrebbe più verificarsi.

**Comment by vvarratta** [comment]
Buonasera, ho eseguito un test e ora è ok. grazie mille. saluti
