### ISSUE TITLE
Invio documento - Errore validazione CDA LDO

### ISSUE THREAD

**Issue by ivanot** [ministero-salute/it-fse-support#19]
Nell'invio per validazione al gateway di una Lettera di Dimissione Ospedaliera ricevo il seguente errore di validazione:
`    "title": "Errore vocabolario.",
    "status": 400,
    "detail": "Almeno uno dei seguenti vocaboli non sono censiti : [Dizionario : 2.16.840.1.113883.6.103 ,Vocaboli:2251,2251]",
    "instance": "/msg/vocabulary",`

riferito in particolare a questo blocco del CDA:
`<entry>
                        
                        <observation classCode="OBS" moodCode="EVN">
                            <code code="8651-2"   codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"  displayName="Diagnosi di Dimissione" />
                            <value xsi:type="CD" code="2251" codeSystem="2.16.840.1.113883.6.103" codeSystemName="ICD9CM" displayName="Etmoidotomia">
                            </value>
                        </observation>
                    </entry>
                    <entry>
                        
                        <observation classCode="OBS" moodCode="EVN">
                            <code code="8651-2"   codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"  displayName="Diagnosi di Dimissione" />
                            <value xsi:type="CD" code="2251" codeSystem="2.16.840.1.113883.6.103" codeSystemName="ICD9CM" displayName="Tumori benigni dei nervi cranici">
                            </value>
                        </observation>
                    </entry>`

Ho verificato l'esistenza su ICD9 CM sia del codice di diagnosi che di procedura ed è corretto, chiedo pertanto se è possibile avere qualche indicazione in più sul possibile problema di invio. Aggiungo inoltre che se elimino le due "entry" l'invio va a buon fine col seguente messaggio di warning "_[W003|  Sezione Condizioni del paziente e diagnosi alla dimissione: La sezione PUO' contenere l'elemento 'entry'_"

**Comment by gndibiase** [comment]
@ivanot è stata pubblicata un nuova lista ICD9CM sul portale del Ministero della Salute che riporta correttamente i punti separatori. La nuova lista è stata riportata sul gateway. E' possibile ripetere un test ?

**Comment by MarcoKnezevichInsiel** [comment]
Riscontriamo ancora il problema, otteniamo l'errore:

`{
  "message": null,
  "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException",
  "responseGatewayDto": {
    "traceID": "f700421160a46684",
    "spanID": "f700421160a46684",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.2a5e5acddd3576b41e1038feda93e40b020b9d0bb3ca0b3c2d16f705714575c1.e313d02878^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
    "type": "/msg/vocabulary",
    "title": "Errore vocabolario.",
    "status": 400,
    "detail": "Almeno uno dei seguenti vocaboli non sono censiti : [Dizionario : 2.16.840.1.113883.6.103 ,Vocaboli:724.02,722.10]",
    "instance": "/msg/vocabulary",
    "govwayId": null,
    "warning": null
  }
}
`

In riferimento all'ICD9CM del ministero [qui](https://www.salute.gov.it/portale/temi/p2_6.jsp?id=1278&area=ricoveriOspedalieri&menu=classificazione), ad edempio la diagnosi `724.02` afferente a `Stenosi del canale vertebrale lombare` risulta censita.
[LDO826691495Cda2.xml.txt](https://github.com/ministero-salute/it-fse-support/files/9811854/LDO826691495Cda2.xml.txt)

**Comment by MarcoKnezevichInsiel** [comment]
Riscontriamo ancora il problema, otteniamo l'errore:

`{
  "message": null,
  "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException",
  "responseGatewayDto": {
    "traceID": "f700421160a46684",
    "spanID": "f700421160a46684",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.2a5e5acddd3576b41e1038feda93e40b020b9d0bb3ca0b3c2d16f705714575c1.e313d02878^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
    "type": "/msg/vocabulary",
    "title": "Errore vocabolario.",
    "status": 400,
    "detail": "Almeno uno dei seguenti vocaboli non sono censiti : [Dizionario : 2.16.840.1.113883.6.103 ,Vocaboli:724.02,722.10]",
    "instance": "/msg/vocabulary",
    "govwayId": null,
    "warning": null
  }
}
`

In riferimento all'ICD9CM del ministero [qui](https://www.salute.gov.it/portale/temi/p2_6.jsp?id=1278&area=ricoveriOspedalieri&menu=classificazione), ad edempio la diagnosi `724.02` afferente a `Stenosi del canale vertebrale lombare` risulta censita.
[LDO_Cda2.xml.txt](https://github.com/ministero-salute/it-fse-support/files/9812203/LDO_Cda2.xml.txt)

**Comment by LeonardoAlcaro** [comment]
Ciao Marco,
abbiamo risottomesso il CDA2 LDO da te allegato ottenendo 201 Success , quindi la parte  relativa al dizionario è stata aggiornata.
Non dovresti più avere la problematica

Grazie della segnalazione
Leonardo
