### ISSUE TITLE
valorizzazione prestazioni nel CDA2

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#190]
Buongiorno,
ripropongo una domanda che avevo formulato su Slack
https://developersitalia.slack.com/archives/C03RDT88FSM/p1677158970823239

Riguardo all'utilizzo della codifica LOINC per le prestazioni, le Linee guida per l'attuazione FSE 2.0 ne prevedono l'adozione entro 24 mesi.
Quindi a tendere nel caso di RSA - Prestazioni Amministrative Eseguite si avrà `<act>/<code>` valorizzato con LOINC ed eventuali elementi `<translation>` per ulteriori codifiche, ad esempio:
•	Nomenclatore Nazionale
•	Nomenclatore o Catalogo Regionale
•	Dizionario prestazioni ASR o struttura

Nel periodo transitorio, è prevista un'indicazione di come valorizzare l'elemento `<act>/<code>`?

La specifica RSA prevede Nomenclatore Nazionale/Regionale delle prestazioni amministrative.
Potrebbe essere utile definire a livello nazionale una modalità di compilazione omogenea in modo da agevolare l'interoperabilità dei dati che progressivamente alimenteranno il data repository centrale?

Inoltre nel caso di Regione Piemonte, l’elemento `<translation>` viene usato all'interno di component/section/entry/act/code per veicolare le codifiche del Catalogo Regionale delle Prestazioni: si potrà continuare a usarlo cn questa modalità?

Grazie

**Comment by IStacchiotti** [comment]
Grazie della segnalazione.
Si consiglia di valorizzare l'elemento act/code nel periodo di transitorio, ove possibile, con la medesima modalità riportata nelle guide implementative adottate anche nel contesto del FSE2.0. Restiamo a disposizione per ulteriori chiarimenti.

**Comment by ponsilva** [comment]
Buongiorno, grazie per la risposta.

Chiedo ancora conferma che sull’elemento `<code><translation>` non sono posti da parte del gateway vincoli ulteriori rispetto alle specifiche HL7 e che quindi gli attributi code, codeSystem, displayName possono essere valorizzati in base allo schema di codifica locale utilizzato per l'elemento specifico.

**Comment by IStacchiotti** [comment]
Buongiorno.
Si confermo che non vi è alcun vincolo di valorizzazione sull'elemento `<code><translation>` e di conseguenza possono essere valorizzati in base allo schema di codifica locale in uso.

**Comment by ponsilva** [comment]
Grazie per la conferma.
