### ISSUE TITLE
valorizzazione confidentialityCode nel CDA2

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#191]
Buongiorno,
ripropongo una domanda che avevo formulato su Slack
https://developersitalia.slack.com/archives/C03RDT88FSM/p1677159352952209

Riguardo alla valorizzazione dell'elemento `<confidentialityCode>`, la specifica RSA prevede 2 valori: “N” (valore di default) oppure “V”
C'è qualche indicazione valida in modo trasversale a livello nazionale sui casi in cui utilizzare il valore “V”?
Ad esempio, se dati soggetti a Leggi Speciali a maggior tutela dell’anonimato?
Oppure se c'è necessità di mediazione?

Grazie

**Comment by IStacchiotti** [comment]
Buongiorno.
Le tipologie documentali pubblicate sul sito di HL7 Italia, hanno un elemento obbligatorio da POCD ovvero il confidentialityCode, che indica il livello di riservatezza del documento stesso assegnato al momento della sua creazione.
Per i documenti contenenti dati a maggior tutela dell’anonimato, l’elemento `<ClinicalDocument>/<confidentialityCode>/@code `DEVE essere valorizzato con il valore “V”.
Questo valore "V" indica il livello di protezione richiesto da circostanze atipiche per salvaguardare informazioni potenzialmente dannose o dannose, che se divulgate senza autorizzazione:
(1) presenterebbero un rischio estremamente elevato di danno alla reputazione, al senso di privacy e possibilmente alla sicurezza di un individuo;
(2) influire sulle questioni legali di un individuo o di un'organizzazione.
Le politiche sulla privacy e legali che impongono il massimo livello di protezione, limitando rigorosamente l'accesso alle informazioni, prevengono politiche sulla privacy meno protettive quando le informazioni vengono utilizzate nella fornitura e nella gestione dell'assistenza sanitaria, compresi i procedimenti legali relativi all'assistenza sanitaria.
Il livello V include ad esempio informazioni su una vittima di abuso, sensibilità alle informazioni richieste dal paziente e argomenti tabù relativi allo stato di salute che devono essere discussi con il paziente da un fornitore di assistenza prima di condividerli con il paziente. Può anche includere informazioni detenute sotto una conservazione legale o privilegio avvocato-cliente.

**Comment by ponsilva** [comment]
Buongiorno, grazie per il chiarimento.
