### ISSUE TITLE
formato identificativo del documento nel CDA2

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#192]
Buongiorno,
ripropongo una domanda che avevo formulato su Slack
https://developersitalia.slack.com/archives/C03RDT88FSM/p1676965603023759

Guardando le specifiche del documento RSA (cap 4.1.4 Identificativo del documento) e quanto indicato nell'affinity domain 2.4.1 (cap 2.20 XDSDocumentEntry.uniqueId), sono emersi alcuni interrogativi.
Nel caso di un documento prodotto da un'ASR NNN della Regione Piemonte, nel CDA si avrebbe
ClinicalDocument/id/root = 2.16.840.1.113883.2.9.2.10NNN.4.4
cioè l'OID associato all'ASR per il dominio di identificazione dei documenti

Nell'affinity domain lo stesso documento verrebbe indicizzato con
2.16.840.1.113883.2.9.2.10.4.4^X (10 codice Regione e X identificativo del documento)
quindi ci si troverebbe nel dominio di identificazione dei documenti di Regione Piemonte.

Il fatto che ci si riferisca a enti diversi (nel CDA l'ASR e nei metadati la Regione) può generare incongruenze nel processo di validazione e pubblicazione del documento?

Esistono inoltre relazioni o vincoli tra l'attributo extension del documento CDA e l'identificativo del documento X di uniqueId? 
Ad esempio, possono/devono essere uguali?
Ci sono indicazioni valide in modo trasversale a livello nazionale da parte di chi ha redatto le specifiche CDA e frame su come valorizzare questi elementi?

Grazie

**Comment by IStacchiotti** [comment]
Grazie della segnalazione.
L'oid, inseriti per valorizzare la root dell'elemento id, deve rappresentare l'ente che garantisce l'univocità dell'istanza. Se tale univocità è rispettata dall'id inserito per valorizzare i metadati, tale valore potrà essere riportato anche all'interno del cda. Se la root degli identificativi, presenti rispettivamente nel cda e nei metadati sono differenti, non restituisce errore in validazione sintattica, semantica e terminologica lato cda2.

**Comment by ponsilva** [comment]
Buongiorno, grazie per la risposta
