### ISSUE TITLE
VALIDAZIONE_CDA2_RSA_CT15_KO: il gateway valida erroneamente il documento?

### ISSUE THREAD

**Issue by SeemoneB** [ministero-salute/it-fse-support#194]
Buongiorno,
Come richiesto dal test case 15 dell'RSA, ho lasciato vuoto il tag <text> della sezione obbligatoria "Referto". Il risultato atteso è un errore semantico, ma il gateway mi valida il documento.

`{"traceID":"33ae2979988e23cb","spanID":"33ae2979988e23cb","workflowInstanceId":"2.16.840.1.113883.2.9.2.10.4.4.8b4826fc860c5c74e62ab4402d484841b0a42d9a3b46888e4a2067f77607fabf.76c45d5645^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

Allego il CDA
[TC15_RSA.txt](https://github.com/ministero-salute/it-fse-support/files/11061591/TC15_RSA.txt)

**Comment by masciamariotti** [comment]
Buongiorno Simone,
quando viene richiesto di omettere dei dati, va eliminato tutto il tag/sezione, altrimenti il sistema lo riconosce e lo interpreta come vuoto. Pertanto la invitiamo a riprovare modificando il cda, eliminando tutta la section relativa al Referto

**Comment by SeemoneB** [comment]
Si, confermo che togliendo tutto il tag sezione, il gateway non valida il documento.
Sarebbe possibile precisare che bisogna eliminare tutto il tag sezione e non solo il contenuto, nel documento "casi di test RSA.docx"?

Attualmente la descrizione è la seguente
"La mancata compilazione dei dati relativi al Referto della sezione obbligatoria “Referto” che genera un errore semantico."

Mancata compilazione dei dati fa intendere che il tag sezione sia presente, ma vuoto

Grazie
