### ISSUE TITLE
status per referto sostituito

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#198]
Buongiorno,
ho eseguito delle chiamate ai servizi del gateway con questa sequenza:

1) validazione e pubblicazione referto1
"workflowInstanceId": "2.16.840.1.113883.2.9.2.10.4.4.5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5.01f3048204^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"

2) aggiornamento metadati referto1
"workflowInstanceId": "b4618eb5b569c6a4a25a379b9fb8da61240a10daa8e9f30a8b8537c1b8815bb7.de83c7a37f^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"

3) validazione e sostituzione documento (referto2 sostituisce referto1)
"workflowInstanceId": "2.16.840.1.113883.2.9.2.10.4.4.5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5.5011cbc511^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"

Le chiamate hanno avuto esito positivo.

Successivamente usando il servizio status non riesco ad avere evidenza del fatto che referto2 ha sostituito referto1

Se chiamo status con workflowInstanceId del punto 3) vedo che referto2 ha un "eventType": "REPLACE" ma non c'è l'indicazione di quale referto ha sostituito.
Invece se chiamo status con workflowInstanceId del punto 1) o 2) non risulta che referto1 sia stato sostituito.

Potete dirmi se c'è modo di ottenere questa informazione dai servizi del gateway?
Grazie

**Comment by IStacchiotti** [comment]
Buon pomeriggio Silvana, dovrebbe far riferimento alla response ricevuta in sostituzione: un esito positivo, come in questo caso, è indice del fatto che la sostituzione è avvenuta con successo. Grazie

**Comment by ponsilva** [comment]
Grazie per la risposta
