### ISSUE TITLE
Codifica LOINC delle prestazioni e alternative

### ISSUE THREAD

**Issue by marcodevanna** [ministero-salute/it-fse-support#20]
Nelle attuali specifiche sui CDA2, in quasi tutti i punti in cui è da riportare il valore codificato delle prestazioni, è riportata la seguente indicazione: "Per la codifica possono essere utilizzati i sistemi di codifica (LOINC, ICD9-CM) e possono essere inserite eventuali altre codifiche derivanti da Nomenclatura Ministeriale e/o Regionale mediante l’elemento <translation>. "

Si tratta di un'indicazione ahimè non sempre presente in questi termini, manca ad esempio nel VPS, nella sezione Prestazioni del RSA, nella sezione Consulenza della LDO.

Ad ogni modo, non essendoci vincolo di obbligatorietà sull'utilizzo del LOINC a livello di code (recentemente leggevo appunto conferma in tal senso in uno degli issue chiusi di recente), mi chiedo se possiamo quindi utilizzare codici regionali/locali sia nel code che nella translation, senza infrangere alcun controllo.

**Comment by gndibiase** [comment]
Grazie della segnalazione, verifichiamo

**Comment by LeonardoAlcaro** [comment]
Ciao Marco, nella nuova release degli schematronV3 rilasciati è stato rilassato il controllo sul code.
Sarà quindi possibile, come da IG HL7 Italia, usare sia le codifiche(LOINC, ICD9-CM) che quelle derivanti da Nomenclatura Ministeriale e/o Regionale.
