### ISSUE TITLE
Mancato ko

### ISSUE THREAD

**Issue by synlabsdn** [ministero-salute/it-fse-support#200]
Buongiorno,
il sistema dovrebbe fornirmi il messaggio KO, ma continua a pubblicarmi i dati correttamente anche inserendo il suffisso CRASH_INI nel campo IdentificativoDoc.
Di seguito il risultato:
{
      "id": 233,
      "ts": "2023-03-27T15:55:44Z",
      "traceId": "a12e61ae89f32dcb",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.8fe46b71d98546dc779f4a7f4859b056b254bbe56b59baa550333b2c46441c87.776bb8c832^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
    }

**Comment by IStacchiotti** [comment]
Buonasera, il messaggio 200 OK deriva dal fatto che CRASH_INI è uno stato asincrono restituito dal Gateway (messaggio acquisito con successo). Per verificare l'esito della chiamata, dovrebbe eseguire una chiamata al servizio di get status con il WorkflowInstanceId ottenuto in pubblicazione. Grazie
