### ISSUE TITLE
Test case accreditamento

### ISSUE THREAD

**Issue by sistemiinformativi-aocz** [ministero-salute/it-fse-support#201]
Salve,
procedendo con i test case relativi alla pubblicazione, nello specifico il 362, riscontriamo un errore non conforme con quanto atteso.
La risposta dal GW è la sequente:
```
{
"type": "https://govway.org/handling-errors/400/InvalidRequestContent.html", 
"title": "InvalidRequestContent", 
"status": 400, 
"detail": "Request content not conform to API specification: Validation error(s) :\nbody: Field 'tipoDocumentoLivAlto' is required. (code: 1026)\nFrom: body.<required>\n", 
"govway_id": "608c0dbb-cca3-11ed-a9a6-005056ae7395"
}
```

Ci aspetteremmo quanto citato al seguente link 
[https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#722-esempio-di-messaggio-di-risposta-con-esito-ko-400](url)

Grazie

**Comment by sistemiinformativi-aocz** [comment]
Ps. Si segnala che anche il successivo test case, il 363, non segue quanto indicato.
Effettuando la seguente richiesta:
```
{
    "tipologiaStruttura":"Ospedale",
    "tipoDocumentoLivAlto":"VRB",
    "assettoOrganizzativo":"AD_PSC106",
    "dataFinePrestazione":"20220407112426",
    "conservazioneANorma":"CONS^^^&2.16.840.1.113883.2.9.3.3.6.1.7&ISO",
    "tipoAttivitaClinica":"DIS",
    "identificativoSottomissione": "2.16.840.1.113883.2.9.2.180.4.3.1",
    "dataInizioPrestazione": "2022-05-09-07:30+00"
}
```

Restituisce 200 invece di 400 con la seguente risposta:
```
{
    "traceID": "df6898d1555cf0fd",
    "spanID": "df6898d1555cf0fd",
    "workflowInstanceId": "a1a0d223292308f1583bfb288c83859bd3487808a5ba693ef4f9b1d90c20eb1a.6e5e45a878^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```

**Comment by sistemiinformativi-aocz** [comment]
Si chiede cortesemente inoltre di verificare tutti i test case relativi a PUBBLICAZIONE_SOSTITUZIONE per VPS e LAB (193, 206, 273, 286, 322, 323, 342, 343), in quanto nessuno di questi risulta congruo tra documentazione, file di test e body di richiesta e tutti restituiscono risposte inattese.
Cordiali saluti.

**Comment by masciamariotti** [comment]
Buongiorno,
per quanto riguarda i test 323/343/363 dovrebbe modificare il formato del campo "dataInizioPrestazione" da 2022-05-09-07:30+00 a così: 2022:05:09-07:30+00.
Per tutte le altre segnalazioni seguiranno aggiornamenti quanto prima.

**Comment by sistemiinformativi-aocz** [comment]
Effettuo un riepilogo dato che il problema è comunque presente, ma con errori diversi.
Caso di test 353 - Risposta (si verifica errore simile per 363):
```
{
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "status": 502,
    "detail": "Invalid response received from the API Implementation",
    "govway_id": "e20e3b2c-cd4e-11ed-a9a6-005056ae7395"
}
```

Caso di test 352 - Risposta (si verifica errore simile per 362):
```
{
    "type": "https://govway.org/handling-errors/400/InvalidRequestContent.html",
    "title": "InvalidRequestContent",
    "status": 400,
    "detail": "Request content not conform to API specification: Validation error(s) :\nbody: Field 'tipoDocumentoLivAlto' is required. (code: 1026)\nFrom: body.<required>\n",
    "govway_id": "3a759c2c-cd4f-11ed-a9a6-005056ae7395"
}
```

**Comment by sistemiinformativi-aocz** [comment]
Buon pomeriggio,
proseguo con il test case 273 (errore simile test case 193) in cui mi viene restituito il seguente errore:
```
{
    "traceID": "7c836dade0742d46",
    "spanID": "7c836dade0742d46",
    "type": "/msg/jwt-validation",
    "title": "Campo token JWT non valido.",
    "detail": "JWT payload: Tipologia documento diversa dalla tipologia di CDA (code - codesystem)",
    "status": 403,
    "instance": "/jwt-document-type"
}
```

Grazie

**Comment by sistemiinformativi-aocz** [comment]
Buon pomeriggio,
procedendo con i test, il 206 e 286, non vanno in errore come avrebbero dovuto, ma danno risposta 200:
Risposta test case 206
```
{
"traceID": "a580ef085421e3d7", 
"spanID": "a580ef085421e3d7", 
"workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.e099922b690ba6f641689478cd8956e793d18736aa177264908d991a62a5b740.56dfc5f39d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```

**Comment by sistemiinformativi-aocz** [comment]
Buongiorno,
rimaniamo in attesa di avere sviluppi in merito alle seguenti problematiche.
Grazie.
Cordiali saluti

> Effettuo un riepilogo dato che il problema è comunque presente, ma con errori diversi. Caso di test 353 - Risposta (si verifica errore simile per 363):
> 
> ```
> {
>     "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
>     "title": "InvalidResponse",
>     "status": 502,
>     "detail": "Invalid response received from the API Implementation",
>     "govway_id": "e20e3b2c-cd4e-11ed-a9a6-005056ae7395"
> }
> ```
> 
> Caso di test 352 - Risposta (si verifica errore simile per 362):
> 
> ```
> {
>     "type": "https://govway.org/handling-errors/400/InvalidRequestContent.html",
>     "title": "InvalidRequestContent",
>     "status": 400,
>     "detail": "Request content not conform to API specification: Validation error(s) :\nbody: Field 'tipoDocumentoLivAlto' is required. (code: 1026)\nFrom: body.<required>\n",
>     "govway_id": "3a759c2c-cd4f-11ed-a9a6-005056ae7395"
> }
> ```
> 
> Grazie




> Buon pomeriggio, procedendo con i test, il 206 e 286, non vanno in errore come avrebbero dovuto, ma danno risposta 200: Risposta test case 206
> 
> ```
> {
> "traceID": "a580ef085421e3d7", 
> "spanID": "a580ef085421e3d7", 
> "workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.e099922b690ba6f641689478cd8956e793d18736aa177264908d991a62a5b740.56dfc5f39d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
> }
> ```

**Comment by masciamariotti** [comment]
Buongiorno,
per quanto riguarda i test:
- 353: dovrebbe valorizzare la dataiInizioPrestazione con 2022:05:09-07:30+00;
- 352: invece di eliminare tipoDocumentoLivAlto dovrebbe valorizzare "attiCliniciRegoleAccesso" con "XXX";
- 206 e 286: seguiranno aggiornamenti quanto prima.

**Comment by sistemiinformativi-aocz** [comment]
Salve, 
guardi per quanto riguarda il test 353 l'ultima risposta riportata si riferisce ad una richiesta effettuata con la data indicata.
Per il test 352 il file excel riporta testuale descrizione:
```
Per tutti i fornitori è necessario eliminare dal json il campo tipoDocumentoLivAlto.
```
Rimaniamo in attesa,
Grazie

**Comment by nturri1306** [comment]
test 353 ricevo errore diverso
```

{
  "tipologiaStruttura": "Ospedale",
  "tipoDocumentoLivAlto": "REF",
  "assettoOrganizzativo": "AD_PSC101",
  "dataInizioPrestazione": "2022:05:09-07:30+00",
  "dataFinePrestazione": "20220324102426",
  "conservazioneANorma": "CONS^^^\u00262.16.840.1.113883.2.9.3.3.6.1.7\u0026ISO",
  "tipoAttivitaClinica": "ERP",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.2.120.4.3^74328652"
}
```
```

{
  "status": "BAD_GATEWAY",
  "headers": {},
  "body": {
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "detail": "Invalid response received from the API Implementation",
    "status": 502
  }
}
```

**Comment by sistemiinformativi-aocz** [comment]
Buongiorno @masciamariotti,
questa mattina non avendo avuto alcun riscontro abbiamo riprovato ad eseguire tutti i test segnalati.
Per quanto riguarda i **353** e **363** sono andati a buon fine.
I test cases: **352, 362, 206 e 286** continuano ad andare in errore.
Visto che da richiesta avevamo segnalato come fine dei test giorno **15 aprile** potremmo avere un riscontro?

Cordiali saluti

**Comment by IStacchiotti** [comment]
Buon pomeriggio, per la risoluzione degli errori relativi ai test cases **206** e **286** si rende necessaria una fix, le daremo evidenza non appena questa sarà rilasciata. Per quanto riguarda invece gli uc **352** e **362**, nonostante la checklist fa riferimento al campo tipoDocumentoLivAlto, invece di eliminare tipoDocumentoLivAlto dovrebbe valorizzare **"attiCliniciRegoleAccesso"** con "XXX": è presente infatti una incongruenza nella checklist che verrà aggiornata nella prossima versione.

**Comment by IStacchiotti** [comment]
Buonasera, Le confermiamo che è stata rilasciata la fix correttiva di cui al commento precedente. La invitiamo cortesemente a riprovare gli uc 206 e 286, il problema non dovrebbe più presentarsi. Rimaniamo a completa disposizione in caso contrario. Grazie

**Comment by sistemiinformativi-aocz** [comment]
Buongiorno @IStacchiotti ,
prima di andare avanti con i test gli uc **352** e **362** ho capito che la descrizione era scorretta, ma la corretta descrizione da lei indicata era stata svolta per gli uc **320** e **340**. 
Con quest'ultimi come dobbiamo comportarci ? 
Sono gli stessi uc, ma con riferimenti differenti ? 
Grazie

**Comment by masciamariotti** [comment]
Buon pomeriggio @sistemiinformativi-aocz,
i casi di test 352 e 362 sono relativi al servizio di AGGIORNAMENTO_METADATI, mentre 320 e 340 a quello di PUBBLICAZIONE_CREAZIONE.
Quindi pur avendo gli stessi step per replicarli, si trattano effettivamente di test differenti.

**Comment by sistemiinformativi-aocz** [comment]
Perfetto.
Grazie
