### ISSUE TITLE
Chiarimento su differenza tra OID dell'identificativo documento dentro il CDA e su quello inviato nei metadati di INI

### ISSUE THREAD

**Issue by ngaudenzi** [ministero-salute/it-fse-support#202]
Buongiorno,
guardando le specifiche dei documenti CDA (ad esempio RSA cap 4.1.4 Identificativo del documento) e quanto indicato nell'affinity domain 2.4.1 (cap 2.20 XDSDocumentEntry.uniqueId), avremmo una domanda da porvi.
Nel caso di un documento prodotto da un'ASR NNN della Regione Piemonte, nel CDA si avrebbe
ClinicalDocument/id/root = 2.16.840.1.113883.2.9.2.10NNN.4.4
cioè l'OID associato all'ASR per il dominio di identificazione dei documenti 
Nell'affinity domain lo stesso documento verrebbe indicizzato con
2.16.840.1.113883.2.9.2.10.4.4^X (10 codice Regione e X identificativo del documento), quindi ci si troverebbe nel dominio di identificazione dei documenti di Regione Piemonte.
L’oid del documento riportato dentro il CDA e sui metadati inviati a INI non dovrebbe coincidere?
Grazie

**Comment by IStacchiotti** [comment]
Grazie della segnalazione.
L'oid, inserito per valorizzare la root dell'elemento id, deve rappresentare l'ente che garantisce l'univocità dell'istanza. Se tale univocità è rispettata dall'id inserito per valorizzare i metadati, tale valore potrà essere riportato anche all'interno del cda. Se la root degli identificativi, presenti rispettivamente nel cda e nei metadati sono differenti, non restituisce errore in validazione sintattica, semantica e terminologica lato cda2.

**Comment by IStacchiotti** [comment]
Buongiorno, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
