### ISSUE TITLE
Richiesta Dettagli su administrationUnitCode VPS

### ISSUE THREAD

**Issue by vvarratta** [ministero-salute/it-fse-support#203]
Buonasera,
avrei bisogno di dettagli relativamente alla creazione di un VPS, in particolare in merito all'elemento "administrationUnitCode" del substanceAdministration relativo alla Sezione Terapia Farmacologica in Pronto Soccorso. Nella documentazione si legge che l'elemento include l’informazione inerente alla forma farmaceutica associata all’elemento &lt;consumable>/&lt;manufacturedProduct&gt;. da https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/VPS.xml ho notato che la codifica usata per la forma farmaceutica è la codifica SNOMED. vorrei sapere se è l'unica codifica utilizzabile o se, in alternativa, è possibile caratterizzare l'elemento solo con l'attributo displayName (i.e. &lt;administrationUnitCode  displayName="Injection solution"/&gt;). da un primo test il servizio non ha restituito errore sull'obbligatorietà degli altri attributi.

Ringrazio anticipatamente.

**Comment by IStacchiotti** [comment]
Buongiorno.
Da specifiche HL7, l'elemento administrationUnitCode del substanceAdministration
è opzionale, include l'informazione associata alla codifica presente nell'elemento consumable/manufacturedProduct. Questo elemento ha dataType CE, non sono obbligatori gli attributi quali code, codeSystem, codeSystemName e displayName, quindi se non vengono inseriti non vi è alcun errore ne sintattico ne semantico ne terminologico.
Non vi è alcun vincolo neanche sull'uso specifico della codifica SNOMED, quindi è possibile usare anche un altro sistema di codifica, però è consigliabile inserire il code e il codeSystem poiché completano l'informazione che l'elemento vuole fornire, inserire solamente il displayName.

**Comment by vvarratta** [comment]
Grazie mille per la Vs risposta.
Cordiali saluti.
