### ISSUE TITLE
Info certificato chiamate fse

### ISSUE THREAD

**Issue by mmaggi69** [ministero-salute/it-fse-support#204]
Salve una info. Per effettuare le chiamate ad fse dovrò acquistare ed installare un certificato per forza di primo o anche di terzo livello ?

**Comment by IStacchiotti** [comment]
Buongiorno @mmaggi69, la invito a continuare a scrivere in questo thread in relazione allo stesso "topic", questo per evitare entropia e facilitare l'indirizzamento delle problematiche. Grazie per la collaborazione. 

Riepiloghiamo di seguito le richieste, tenendo conto anche della domanda posta con il ticket #205, che verrà chiuso: 

1.  Per effettuare le chiamate ad fse dovrò acquistare ed installare un certificato per forza di primo o anche di terzo livello ?
2.  Quanto tempo di solito si deve aspettare per ricevere i certificati di test per fse ? Ho inviato email ad [fse_support@sogei.it](mailto:fse_support@sogei.it) il 24/03 ma ad oggi non ho ricevuto risposta.

Abbiamo preso in carico le domande, le risponderemo appena possibile. Grazie

**Comment by mmaggi69** [comment]
Ho reinviato email con i 2 certificati CSR allegati il 3/04/2023 ad oggi non ho ancora ricevuto risposta è normale ?

**Comment by mmaggi69** [comment]
Ho reinviato email con i 2 certificati CSR allegati il 3/04/2023 ad oggi non ho ancora ricevuto risposta è normale ?

**Comment by mmaggi69** [comment]
Buongiorno vorrei  avere dettagli su alcuni field presenti nel file data.json da utilizzare come parametro jwt-generator 

	"sub": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",    
        sub - cosa indica ? il Codice Fiscale del medico ? 

	"resource_hl7_type": "('11502-2^^2.16.840.1.113883.6.1')",
        resource_hl7_type - cosa indica ? dove posso reperire questa informazione ?

	"jti": "1234",
        jti - cosa indica ? un UUID da generare al momento della chiamata ?

	"person_id":"RSSMRA22A01A399Z^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO",
        person_id - cosa indica ? codice fiscale autore ?

	"pem_path": "../../certpem.pem",
         pem_path - equivale al path certificato che mi è stato inviato da sogei ? 
	"p12_path": "../../certp12.p12"
        p12_path - a cosa si riferisce ? quale certificato è ? 

Aspetto vostre info.

**Comment by IStacchiotti** [comment]
Buongiorno, la rimandiamo alla documentazione disponibile a questo [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway).
Per quanto riguarda invece l'impiego dei certificati, la rimandiamo a [questo ](https://developersitalia.slack.com/archives/C03RDT88FSM/p1671467530530709)thread su Slack.

**Comment by IStacchiotti** [comment]
Buongiorno, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
