### ISSUE TITLE
Richiesta certificati di test a fse_support@sogei.it

### ISSUE THREAD

**Issue by mmaggi69** [ministero-salute/it-fse-support#205]
quanto tempo di solito si deve aspettare per ricevere i certificati di test per fse ? Ho inviato email ad fse_support@sogei.it il 24/03 ma ad oggi non ho ricevuto risposta.

**Comment by IStacchiotti** [comment]
Buongiorno @mmaggi69, la presente viene chiusa come riportato nel ticket #204, nel quale la invitiamo a continuare a scrivere in relazione al medesimo "topic" (in questo caso i certificati). Grazie
