### ISSUE TITLE
Merge visibili solo su fork rangeletti

### ISSUE THREAD

**Issue by rangeletti** [ministero-salute/it-fse-support#207]
Buongiorno, a seguito di  email in risposta alla pull request #136 che richiedeva delle modifiche sulle cheklist relative a
A1#111EXPRIVIA000\EXPRIVIA\ERIS
A1#111EXPRIVIA000\EXPRIVIA\AURORA
abbiamo provveduto ad aggiornare i file cheklist ed effettuato il merge del branch nel main. Ora le nostre modifiche non sono visibili nel percorso https://github.com/ministero-salute/it-fse-accreditamento/tree/main/GATEWAY.
Un nostro collega con il suo account github ha provveduto ad effettuare una pull #173 relativa ad un altro prodotto Exprivia "A1#111EXPRIVIA000\EXPRIVIA\EDOTTO" il 24/03/2023. Questa pull request risulta chiusa e nel main branch risulta visibile.
Non capiamo se dobbiamo fare qualcosa noi per completare la merge nel main oppure se dobbiamo solo attendere.
Grazie,
 Rachele

**Comment by IStacchiotti** [comment]
Buongiorno Rachele, questo ticket ci sembra superato dal momento che sono stati aperti da voi dei ticket successivi per gli applicativi ERIS e AURORA. Pertanto procediamo alla chiusura del presente e vi invitiamo a monitorare i successivi ticket ai quali riceverete risposta non appena possibile. Grazie
