### ISSUE TITLE
Mancato accreditamento displayName Decorso_ospedaliero

### ISSUE THREAD

**Issue by insielFse** [ministero-salute/it-fse-support#208]
Buongiorno,
abbiamo ricevuto una mail di mancato accreditamento:
Con la presente si comunica il mancato superamento dei seguenti test [6] per il servizio [validazione/pubblicazione] del Fornitore [S1#060000000000XX] - Vendor:[INSIEL] - ID: [CLINICO] - Version: [G4.3.0] in data odierna. 

nel JSON con gli errori viene richiesto di valorizzare l'attributo 'displayName' con il valore "Decorso_ospedaliero" che però è difforme dalle specifiche HL7 Italia. 
{
  "id" : 6,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "&lt;error code='066' attribute='displayName' actual = 'Decorso ospedaliero' expected = 'Decorso_ospedaliero'&gt;ClinicalDocument/component/structuredBody/component/section[ID='Decorso_ospedaliero']/code</error>"
}

![immagine](https://user-images.githubusercontent.com/123183182/228178877-ed7d7bf0-49b9-4605-9b83-0a4e1e009bce.png)

Possiamo avere un riscontro in merito?

**Comment by IStacchiotti** [comment]
Buon pomeriggio. La parte di guida che è stata allegata è un possibile esempio di implementazione dell'elemento code con i relativi attributi, ma non è vincolante la scrittura del displayName riportata nella guida. Però per facilitare la compilazione del campo è stato allentato il controllo permettendo di poterlo scrivere in entrambi i modi. Grazie
