### ISSUE TITLE
Comunicazione identificativi (WorkflowInstanceId/TraceId/SpanId) gestiti dal Gateway e indicizzazione INI

### ISSUE THREAD

**Issue by yvonne-carpegna** [ministero-salute/it-fse-support#209]
Buongiorno,
vorremmo sapere se i messaggi di indicizzazione dei documenti che saranno inviati da INI ai sistemi FSE delle Regioni riportano gli identificativi (WorkflowInstanceId/TraceId/SpanId) che vengono gestiti dal Gateway in modo tale che sia possibile ricondurre i messaggi generati dai sistemi informatici delle aziende sanitarie con quelli provenienti da INI.

In caso affermativo, vorremmo sapere in quali campi della ComunicazioneMetadati e CancellazioneMetadati vengono inviati tali identificativi

Grazie
Yvonne Carpegna

**Comment by IStacchiotti** [comment]
Buongiorno, la informiamo che INI non prevede questi campi, non essendo annoverati nelle specifiche AGID. Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
