### ISSUE TITLE
Incongruenza valore tabella "Organizzazione"

### ISSUE THREAD

**Issue by xenergy33** [ministero-salute/it-fse-support#21]
Ciao, segnalo che un valore della [tabella riportata al paragrafo 8.3.7](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#837-organizzazione) non è congruente con le specifiche Affinity Domain Italia in versione 2.3. 
Nella tabella sopra citata viene riportato "001 SASN", nelle specifiche AGID (pagina 50, tabella 6.4-3 - Value set per l’attributo urn:oasis:names:tc:xspa:1.0:subject:organization-id)  "001 Sistema TS".
Saluti.

Raffaele Pagliari

**Comment by LeonardoAlcaro** [comment]
Ciao, grazie innanzitutto per la segnalazione.
Provvederemo subito a modificare le specifiche AgID di affinity2.3 in quanto il codice 001 è corretto sia associato ai SASN.
