### ISSUE TITLE
Richiesta informazioni e richiesta dei certificati 

### ISSUE THREAD

**Issue by VitalianoG** [ministero-salute/it-fse-support#210]
Buongiorno, in data 20/03 vi abbiamo mandato una mail per richiedere i certificati x509 per poter effettuare i test ma non abbiamo ancora ricevuto risposta, in più abbiamo chiesto maggiori informazioni riguardo la documentazione che non ci è molto chiara per quanto riguarda il VPS.

Questi sono i nostri dubbi:

Per effettuare le chiamate al GATEWAY si richiede la creazione di due token JWT, uno per l'autorizzazione e uno per la firma. Nel paragrafo in cui viene spiegata la struttura del JWT Token vi è scritto : “si afferma che entrambi i token devono essere firmati con il certificato di signature.”
Questo vuol dire che il JWT token Authorization va creato con il certificato Signature? Oppure va fatto in modo diverso?
Sempre riguardo il JWT token abbiamo visto che nel payload sono richiesti alcuni campi,  (come il codice fiscale codificato secondo le specifiche IHE (ITI  TF-3)) che attualmente il nostro sistema non dispone.  Potreste fornirci informazioni in merito?

Durante lo sviluppo delle funzionalità per richiamare i vari servizi (VALIDATION, PUBBLICAZIONE, ELIMINAZIONE, SOSTITUZIONE) abbiamo riscontrato dei punti sui quali vorremmo avere maggiori informazioni:
1. locality: Può essere anche solo in HSP.11?
2. subject_role: Nel nostro caso può essere medico di pronto soccorso, medico di reparto (nel caso in cui il paziente venga inserito nel percorso Fast Track) o direttore., dobbiamo inserire DRS?
3. person_id: Oltre al codice fiscale del medico che effettua la dimissione va concatenata questa stringa  "^^^&2.16.840.1.113883.2.9.4.3.2&ISO" è sempre fissa?
4. patient_consent: Se il paziente desidera rimanere nell'anonimato si imposta a false?
5. resource_hl7_type: Dobbiamo inserire il dato indicato nelle specifiche?
6. subject_application_id, subject_application_vendor, subject_application_version: si riferiscono a dei dati del nostro applicativo o devono essere censiti da voi prima che vengano effettuati i vari servizi?
7 l’OID è un valore che dobbiamo inserire noi nel file xml e può essere generato in modo random o dobbiamo seguire delle specifiche precise?

Inoltre, nel body della chiamata di pubblicazione ci vengono richiesti questi dati su cui vorremmo avere maggiori informazioni:
1. IdentificativoRep: Dove lo reperiamo?
2. identificativoSottomissione": " 2.16.840.1.113883.2.9.2.180.4.3 " 
4. priorità:  Siccome riguarda il pronto soccorso dobbiamo inserire TRUE per priorità massima?

Riguardo alla creazione dell'XML:

1. Per il codice del Triage, nel test uno fa riferimento al codice vecchio con i colori mentre nel nostro sistema utilizziamo i codici nuovi che vanno da 1 a 5. Quale va inserito?  
2. Può capitare che in fase di accettazione siano presenti 2 record. Dobbiamo prendere l’ultimo oppure vanno inseriti entrambi? (Attualmente per le prove abbiamo inserito l’ultimo) 
3. Se il paziente si allontana dal Triage, bisogna inviare lo stesso il documento al FSE? 
4. Nel VPS a pagina 70 nell’ OBSERVATION abbiamo il Valore come effettivo valore dell’elemento mentre alla riga n° 303 del primo caso di test fa riferimento all’attributo. (vale sia per problema principale che causa accesso) 
5. I codici Team chi li va ad assegnare per noi, la Regione oppure l’ASP? 
6. Se il paziente è straniero e viene registrato momentaneamente nel nostro sistema, nel VPS ci chiede di inserire l' ISTITUZIONE ESTERA che ha rilasciato la tessera, da dove reperiamo questo dato? 
7. Se il paziente dovesse essere spostato in Osservazione Breve Intensiva, tutte le informazioni andrebbero aggiunte in una nuova sezione oppure dovrebbero essere inserite nella stessa sezione delle attività svolte oppure una nuova creazione del documento?
8. Per il legalAuthenticator può non avere il datagroup Address? O bisogna inserire per forza tutto quello che ci sta scritto nell’esempio? 

Riguardo il file PDF se il file viene firmato dopo la validazione dobbiamo inserire all’interno un nuovo xml con il legalAuthenticator quindi dobbiamo eliminare il vecchio all’interno e inserire l’xml nuovo con il legalAuthenticator o possiamo fare firmare il documento pdf originale e poi rifare la injection? Vorremmo avere maggiori dettagli al riguardo per non generare un file errato.

Attendiamo un Vostro riscontro e Vi porgiamo cordiali saluti.

**Comment by IStacchiotti** [comment]
Buongiorno, rispondiamo di seguito punto per punto **in grassetto**:

Buongiorno, in data 20/03 vi abbiamo mandato una mail per richiedere i certificati x509 per poter effettuare i test ma non abbiamo ancora ricevuto risposta, in più abbiamo chiesto maggiori informazioni riguardo la documentazione che non ci è molto chiara per quanto riguarda il VPS.
**--> è stato sollecitato il rilascio dei certificati, li riceverà quanto prima tramite email**

Questi sono i nostri dubbi:

Per effettuare le chiamate al GATEWAY si richiede la creazione di due token JWT, uno per l'autorizzazione e uno per la firma. Nel paragrafo in cui viene spiegata la struttura del JWT Token vi è scritto : “si afferma che entrambi i token devono essere firmati con il certificato di signature.”
Questo vuol dire che il JWT token Authorization va creato con il certificato Signature? Oppure va fatto in modo diverso?
Sempre riguardo il JWT token abbiamo visto che nel payload sono richiesti alcuni campi,  (come il codice fiscale codificato secondo le specifiche IHE (ITI  TF-3)) che attualmente il nostro sistema non dispone.  Potreste fornirci informazioni in merito?
**--> Riguardo la generazione dei token la rimandiamo ai seguenti link:
	- tool di jwt generator https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator#token-customization
	- supporto slack https://app.slack.com/client/T6C27AXE0/C03RDT88FSM/thread/C03RDT88FSM-1671467530.530709**

Durante lo sviluppo delle funzionalità per richiamare i vari servizi (VALIDATION, PUBBLICAZIONE, ELIMINAZIONE, SOSTITUZIONE) abbiamo riscontrato dei punti sui quali vorremmo avere maggiori informazioni:

locality: Può essere anche solo in HSP.11?
subject_role: Nel nostro caso può essere medico di pronto soccorso, medico di reparto (nel caso in cui il paziente venga inserito nel percorso Fast Track) o direttore., dobbiamo inserire DRS?
person_id: Oltre al codice fiscale del medico che effettua la dimissione va concatenata questa stringa  "^^^&2.16.840.1.113883.2.9.4.3.2&ISO" è sempre fissa?
patient_consent: Se il paziente desidera rimanere nell'anonimato si imposta a false?
resource_hl7_type: Dobbiamo inserire il dato indicato nelle specifiche?
subject_application_id, subject_application_vendor, subject_application_version: si riferiscono a dei dati del nostro applicativo o devono essere censiti da voi prima che vengano effettuati i vari servizi?
**--> Può far riferimento alla documentazione al link: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt**

7 l’OID è un valore che dobbiamo inserire noi nel file xml e può essere generato in modo random o dobbiamo seguire delle specifiche precise?
Inoltre, nel body della chiamata di pubblicazione ci vengono richiesti questi dati su cui vorremmo avere maggiori informazioni:

IdentificativoRep: Dove lo reperiamo?
identificativoSottomissione": " 2.16.840.1.113883.2.9.2.180.4.3 " 
priorità:  Siccome riguarda il pronto soccorso dobbiamo inserire TRUE per priorità massima?
**--> può far riferimento alla documentazione al link https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#4-servizio-di-creazione. Per ogni campo, dove necessario, è indicata la specifica da seguire dell'Affinity Domain (colonna AFFINITY DOMAIN/IHE).**

Riguardo alla creazione dell'XML:

Per il codice del Triage, nel test uno fa riferimento al codice vecchio con i colori mentre nel nostro sistema utilizziamo i codici nuovi che vanno da 1 a 5. Quale va inserito?  
Può capitare che in fase di accettazione siano presenti 2 record. Dobbiamo prendere l’ultimo oppure vanno inseriti entrambi? (Attualmente per le prove abbiamo inserito l’ultimo) 
Se il paziente si allontana dal Triage, bisogna inviare lo stesso il documento al FSE? 
Nel VPS a pagina 70 nell’ OBSERVATION abbiamo il Valore come effettivo valore dell’elemento mentre alla riga n° 303 del primo caso di test fa riferimento all’attributo. (vale sia per problema principale che causa accesso) 
I codici Team chi li va ad assegnare per noi, la Regione oppure l’ASP? 
Se il paziente è straniero e viene registrato momentaneamente nel nostro sistema, nel VPS ci chiede di inserire l' ISTITUZIONE ESTERA che ha rilasciato la tessera, da dove reperiamo questo dato? 
Se il paziente dovesse essere spostato in Osservazione Breve Intensiva, tutte le informazioni andrebbero aggiunte in una nuova sezione oppure dovrebbero essere inserite nella stessa sezione delle attività svolte oppure una nuova creazione del documento?
Per il legalAuthenticator può non avere il datagroup Address? O bisogna inserire per forza tutto quello che ci sta scritto nell’esempio? 
**-->  Chiariamo di seguito tutti i dubbi in merito al VPS e alle valorizzazioni dell'xml.
Per quanto concerne il codice Triage, deve essere inserito il codice presente nell'excel ed è il seguente: code="54094-8".
Nel caso in cui si hanno due record in fase di accettazione, va inserito l'ultimo record ottenuto in quanto l'entry della sezione triage da speicifiche ha caridinalità 1...1
Se il paziente dovesse allontanarsi dal triage, deve essere lo stess inviato il documento al FSE.
Nel VPS il value vale sia per motivo ricovero che causa accesso.
I codici TEAM vengono rilasciati o dalle ASL o dalle ASP.
L'informazione relativa all'accesso in OBI è possibile inserirla nell'entry della section ENCOUNTERS con il codice presente nelle Specifiche Funzionali EMUR e il link alle specifiche è presente nella guida del VPS caricata su HL7 Italia.
In generale per la fase di accreditamento bisogna inserire tutto quello presente nell'esempio e nell'excel fornito, comprese le informazioni del legalAuthenticator su cui vi erano dubbi in merito.**

Riguardo il file PDF se il file viene firmato dopo la validazione dobbiamo inserire all’interno un nuovo xml con il legalAuthenticator quindi dobbiamo eliminare il vecchio all’interno e inserire l’xml nuovo con il legalAuthenticator o possiamo fare firmare il documento pdf originale e poi rifare la injection? Vorremmo avere maggiori dettagli al riguardo per non generare un file errato.
**--> come riportato al link (https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#4-servizio-di-creazione): "La verifica della corrispondenza verrà fatta calcolando l’hash del CDA2 estrapolato dal PDF. Il processo di Pubblicazione procederà soltanto se l’hash coincide con quello calcolato nel flusso di validazione"**

**Comment by VitalianoG** [comment]
Buon pomeriggio,
dalla Vostra risposta in merito alla verifica della corrispondenza in fase di validazione dobbiamo inviare il pdf già firmato e con il CDA iniettato inclusi  i dati del legalAuthenticator? Perché c'era stato detto di validare senza la firma e solo in fase di pubblicazione inserire il legalAuthenticator nella Cda e inviarvi il pdf firmato.
In merito al codice triage mi sarò spiegato male,  il codice a cui facevo riferimento non era riferito al codice Loinc, bensì al codice triage che noi adottiamo. Nel file di esempio l'attributo code è R mentre il nostro sistema attua il codice con il numero 5, 
dobbiamo inserire il codice con il colore oppure il  codice 5? 

Fateci sapere quale procedura dobbiamo seguire al riguardo.
Saluti

**Comment by greglombardi** [comment]
Buongiorno, mi allego alla richiesta del mio collega. Ho letto la documentazione al link https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator#token-customization ma qui indica che il campo iss (ISSUER) del JWT token **Issuer of the token as ISTAT code of the organization concatenated with HSP.11 - HSP.11bis - STS.11 - RIA.11 code** però nella pagina di integrazione indica **Stringa che contiene il nome identificativo dell’entità che ha generato il token. Valorizzato con “auth:” seguito dal “Common Name del certificato di firma”**  il common name è il nome dell'organizzazione e può essere anche solo in HSP.11? e dal certificato di firma cosa dovremmo prendere a questo punto?

**Comment by IStacchiotti** [comment]
Buongiorno @VitalianoG, in merito al primo punto riguardo il legalAuthenticator, la rimandiamo a questo [link ](https://developersitalia.slack.com/archives/C03RDT88FSM/p1679579035786489?thread_ts=1672820224.087699&cid=C03RDT88FSM) su Slack in cui si è discusso di questa tematica tematica.

Mentre per la valorizzazione del codice triage è da inserire come valorizzazione dell'attributo code, il codice R.

**Comment by IStacchiotti** [comment]
Buonasera, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
