### ISSUE TITLE
Errore "Colonna K da valorizzare solo se Applicabilità NO", ma colonna Applicabilità a SI e colonna K vuota.

### ISSUE THREAD

**Issue by medarchiver** [ministero-salute/it-fse-support#211]
Salve,

nel corso della validazione dell'LDO, abbiamo ricevuto il seguente messaggio di errore:

• 63: Il razionale di applicabilità (colonna K) deve essere valorizzato solo se l'applicabilità è 'NO'.

Questo messaggio è stato riportato per tutti i test con ID maggiore o uguale a 63.

Nel nostro foglio Excel, la colonna "Applicabilità" (colonna J) è impostata a SI e la colonna "Razionale di Applicabilità" (colonna K) è sempre vuoto. Allegato il file excel.

Cordiali saluti.
[accreditamento-checklist.xlsx](https://github.com/ministero-salute/it-fse-support/files/11089284/accreditamento-checklist.xlsx)

**Comment by medarchiver** [comment]
Salve,

se può essere utile, abbiamo notato che i test per i quali viene segnalato l'errore, hanno la colonna "Note" (colonna S) valorizzata.
Questa è l'unica apparente differenza con gli altri record.

Cordiali saluti.

**Comment by IStacchiotti** [comment]
Buon pomeriggio @medarchiver, abbiamo verificato che c'è uno spazio in corrispondenza del campo "razionale applicabilità" per gli id indicati, che fa sì che il campo non sia interpretato come vuoto. Dovreste eseguire una nuova commit per correggere la checklist. Grazie

**Comment by medarchiver** [comment]
Salve! Grazie mille, abbiamo corretto e fatto commit e push.

**Comment by IStacchiotti** [comment]
Le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
