### ISSUE TITLE
Errore Validazione VPS: elemento <effectiveTime>/<high> non presente 

### ISSUE THREAD

**Issue by PRAFFO72** [ministero-salute/it-fse-support#213]
Salve, in fase di validazione ci viene restituito un <details><summary>errore semantico (-b105)</summary>
<p>{"traceID":"79db6d5896acd057","spanID":"79db6d5896acd057","type":"/msg/semantic","title":"Errore semantico.","detail":"[ERRORE-b105| Sotto-sezione Anamnesi: l'elemento entry/observation/effectiveTime deve essere presente e deve avere l'elemento 'high' valorizzato]","status":422,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.70.4.4.b8a94729688480590c90a8f1465282237c5d2ed760ac61783627461658867f66.2bc2a98151^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}</p>
</details> 

Il riferimento è alla sottosezione Anamnesi Patologica Prossima (in Inquadramento Clinico Iniziale).
Come descritto a pagina 83 della [documentazione](http://www.hl7italia.it/sites/default/files/Hl7/SuperUser/docs/pubblicati/IG-CDA2-VPS/1.1.1/HL7IT-IG_CDA2_VPS-v1.1.1-S.pdf):

_**CONF-VPS-125**: L’elemento \<effectiveTime\>/\<high\> DEVE essere sempre presente quando il problema dettagliato nell’\<observation\> non è più presente._

Essendo in questo caso il problema ancora presente, ci aspettavamo che l'elemento NON dovesse essere inserito.
A riprova di questo, la validazione di un analogo CDA per le LDO restituisce il responso "CDA corretto".

Abbiamo provato anche ad inserire l'elemento con valore "sconosciuto", ma ci restituisce un altro errore semantico
(_ERROR-52: il valore dell'elemento effectiveTime/high deve essere maggione di quello di effectiveTime/low_):

`<effectiveTime xsi:type="IVL_TS">
  <low value="20221221155700+0200"/>
  <high nullFlavor="UNK"/>
</effectiveTime>`

Come ci dobbiamo comportare in questi casi?
[CDA_VPS_errore.zip](https://github.com/ministero-salute/it-fse-support/files/11090307/CDA_VPS_errore.zip)

**Comment by IStacchiotti** [comment]
Buonasera, visionando il cda2 che è stato gentilmente fornito, è stata riscontrata la mancanza dell'elemento `effectiveTime/high nell'entry/observation` che contiene l'`entryRelationship/observation` con il `code=33999-4` e il value con `code=LA18632-2`. L'inserimento dell'`effectiveTime/high` deve rispettare il controllo b52 che esplicita la necessità di una valorizzazione corretta ovvero il value dell'`effectiveTime/high` deve essere maggiore del value dell'`effectiveTime/low`.

**Comment by PRAFFO72** [comment]
Quindi confermate che i vostri controlli sono in contrasto con le specifiche e differiscono dai medesimi controlli che applicate all'analoga sezione delle LDO?
Ci dobbiamo adeguare?

**Comment by PRAFFO72** [comment]
Grazie per la risposta, ma identifica semplicemente il problema che già conoscevamo, non risolve i nostri dubbi.

Non entra nel merito delle specifiche e non spega l'incoerenza dei controlli tra il CDA VPS e il CDA LDO.
Per le LDO, la medesima Sezione "Inquadramento Clinico Iniziale" (sottosezione "Anamnesi"), in questo caso specifico, passa correttamente la validazione anche se priva dell'elemento `effectiveTime/high` (a nostro avviso giustamente, in quanto conforme alle specifiche, identiche per VPS e LDO per questa specifica sezione).
Ci lasciava perplessi questa disparità di comportamento.
Alleghiamo come esempio un CDA LDO che passa la validazione, nonostante la mancanza dell'elemento `effectiveTime/high` (riga 139).

In fase di accreditamento possiamo risolvere inserirendo una data fittizia aggiungendo 1s a `effectiveTime/low`, ma non potremo applicare la stessa logica in produzione.

[oasis_LDO_Test02.zip](https://github.com/ministero-salute/it-fse-support/files/11109814/oasis_LDO_Test02.zip)

**Comment by IStacchiotti** [comment]
Buongiorno, dopo un'accurata analisi, si procederà con la modifica del controllo sullo schematron del Verbale di Pronto Soccorso. Grazie

**Comment by PRAFFO72** [comment]
Grazie della risposta.
