### ISSUE TITLE
Errore validazione LAB, elemento section/code

### ISSUE THREAD

**Issue by rafsind** [ministero-salute/it-fse-support#214]
Errore validazione LAB, elemento section/code

Buongiorno,
in fase di validazione mi viene restituito un errore:

[ERRORE-b1| L'elemento code della section DEVE essere valorizzato con uno dei seguenti codici LOINC individuati:
						18717-9 BANCA DEL SANGUE
						18718-7 MARCATORI CELLULARI 
						18719-5 CHIMICA
						18720-3	COAGULAZIONE
						18721-1 MONITORAGGIO TERAPEUTICO DEI FARMACI
						18722-9 FERTILITÀ
						18723-7 EMATOLOGIA
						18724-5 HLA
						18725-2 MICROBIOLOGIA
						18727-8 SEROLOGIA
						18728-6 TOSSICOLOGIA
						18729-4 ESAMI DELLE URINE
						18767-4 EMOGASANALISI
						18768-2 CONTE CELLULARE+DIFFERENZIALE
						18769-0 SUSCETTIBILITÀ ANTIMICROBICA
						26435-8 PATOLOGIA MOLECOLARE
						26436-6 ESAMI DI LABORATORIO
						26437-4 TEST DI SENSIBILITÀ A SOSTANZE CHIMICHE
						26438-2 CITOLOGIA
						18716-1 ALLERGOLOGIA
						26439-0 PATOLOGIA CHIRURGICA]

L'errore credo si riferisca al tag section/code che valorizzo con il codice 18728-6 che mi sembra corretto ed e' anche riportato tra i valori ammissibili nel testo dell'errore.

Potreste darmi indicazioni in merito?
Grazie.

<section>
   <code code="18728-6" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="TOSSICOLOGIA">
</code>

**Comment by IStacchiotti** [comment]
Buonasera, grazie per la segnalazione. Apportiamo la modifica sullo schematron per la mancanza del codice segnalato sul controllo che genera l'errore b1.

**Comment by IStacchiotti** [comment]
Buongiorno, è stata rilasciata la modifica. Le chiediamo cortesemente di riprovare. Grazie

**Comment by rafsind** [comment]
Buongiorno,
confermo che adesso funziona.

Grazie

**Comment by IStacchiotti** [comment]
Buonasera, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
