### ISSUE TITLE
Test case 199 - FALLITO

### ISSUE THREAD

**Issue by cbslucalanzano** [ministero-salute/it-fse-support#215]
Buongiorno,

pur avendo utilizzato un "identificativoDoc" già utilizzanto in una precedente pubblicazione, il servizio non torna l'errore voluto nel test-case, ma bensì uno status code 201.

Riporto di seguito il mio token FSE:

`eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGS3pDQ0F4T2dBd0lCQWdJVUM3M3hjM3VReG1wL0tuNHNVT2JBaGg5UE95QXdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekF6TVRZeU1qQXhNelphRncweU5qQXpNVFl5TWpBeE16VmFNR2t4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVIwd0d3WURWUVJoREJSRFJqcEpWQzB4TVRGRFFsTkpVMVJGVFVsWVdERWFNQmdHQTFVRUF3d1JVekVqTVRFeFEwSlRTVk5VUlUxSldGZ3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFESFVHamx6THpScmMvUDM3aGkzWGt1QUFWOHNZV3pFN1JJWlRMdURUU3F0bzhYbFhzZjczSlhEeGZnK3phbmliQmhEWXQzbmZCNUM4Vkw2RXZXY0ZUY0pGL3JNM1VPS3RrRTNVQzBocnQzdEs0YXZRMkNtMTMyQnlua0xJUUZiOEVmOHhRekVQUFc0bW9YdTZwSGxEb3g1K0J4Q0tsczRMSk1UTmlTaEFTMnZyRnNRTWFTTHNoNWs3VjcyQmE2cHlpWVh1VjVGU1J6LzNZOCtqWXVPK0VUc3p0dGltM2RNdUZTK21LT1Jxb3RRVStPejFBOUhlWTNKeC9BZ1FxNC9LbHJETytZWnlHVk1UZHdVOG1QRTcwK0tGVVVIU2dtNnFUYmYweGphc05nSGF3anBzRkRZa1BPblo4dURmQzNnaFVERk5WRktNZHlTSzYxd2FCRXgvV1hBZ01CQUFHamdkd3dnZGt3SHdZRFZSMGpCQmd3Rm9BVUZqbXBHZ1dKdHc4dHNqWHR3Z21heFFPRElqOHdFZ1lEVlIwZ0JBc3dDVEFIQmdVclRCMEJDekJ6QmdOVkhSOEViREJxTUdpZ1pxQmtobUpzWkdGd09pOHZZMkZrY3k1bWFXNWhibnBsTG1sMEwwTk9QVU5CSlRJd1RXbHVhWE4wWlhKdkpUSXdaR1ZzYkdFbE1qQlRZV3gxZEdVbE1qQlVaWE4wTEU4OVRXbHVhWE4wWlhKdkpUSXdaR1ZzYkdFbE1qQlRZV3gxZEdVc1F6MUpWREFkQmdOVkhRNEVGZ1FVdTJOaE9FdHRrSUFjc1lLUlFUQnRwb2g1U21vd0RnWURWUjBQQVFIL0JBUURBZ1pBTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFCL2V1TTNVUEh3ejcvV2xPSWV4aHR1TERqZ1I5WXlMa2E2Y25jVDNjVXUyOHU3YkhkcTBmM2NlS0VZMTl6dWthaHVvQUZWT0Y1UVJnN25iTERqVnp2WlpqTFlDdVNaVjhaNmFzTytsb0YrOGlGb0dJTkMzR2lud1diMFh2Wmh4REx0eUU2enFRS015RWFCdlVxcHYvK0lQMzkzeE96RVIxYkk1YldHYmFydVdzUk85dm9laS9OMnNZTU1ZNjdGRGpHWUpqcEYxSXNnM0VDYkcyZGZaQ3lzU0ZiUXNUb2w3RVpQVUxQNDI0bnhFNDVUclRyRkYwRzhvVjZqc1F6bkdVTTJKNFdFV3hRRnU0Ym5DUmt0NGwrWTcvK3FGWFZOaUZqaFBSUm5QSFVMaUpjZkN2VnVDTTdUYndQVmtVTzB5MFlqNVA4cW5aV2xxZXlYYlM0cml4ZlZTTjBYcVNyd2Q2UDQvejZDOE91eEwwQndmMFg4T0NXcDRuR3lJcFpabXd1YkVsOGU5OEdURVZ0OExHRno0d2MzVElvTkpBNjB2bnRteDBIRGwrVzMweUhBbjNQUWVQQ2Z6czQyTlFJV0tQS2MzUUtiblI3T0tBNDNrbXMyUDM4K0x0UEluNzB5dXdqdEZDdTh5VWtDWlk4RXFyQTc5Z2pGelBva2hSNDFyZkZiUjMrUUxQc0lFUXBPN0VKVllxdlYydWVvbU10cU5oaHBrM1pXUThKbTN3YXlGVlVYNG9ncXd3eUYwQ2ptdERFdHFJM2J2c2VJWDVJSEdraTNVR09Sd1FTcWhKWmJINnhVTFRKR3hBRDV6bFAzVW9xd3llN0RGMkZrVFFOUlR0dlJ3TzY5T1lkK0FOWmwrUjB4a3cwcnFhVmd2ZVoxM2FuRlFDMVhkU0tQdUE9PSJdfQ.eyJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExQ0JTSVNURU1JWFgiLCJqdGkiOiJlOTA1NTMyMi01NDhjLTQ3MzEtYTY2MC05NmE2MWU5NThkNjgiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJzdWIiOiJWUkRNUkM2N1QyMEkyNTdFXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X29yZ2FuaXphdGlvbl9pZCI6IjE1MCIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBDYW1wYW5pYSIsImxvY2FsaXR5IjoiMjAxIiwic3ViamVjdF9yb2xlIjoiQUFTIiwicGVyc29uX2lkIjoiUFJPVkFYMDBYMDBYMDAwWV5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsInJlc291cmNlX2hsN190eXBlIjoiKCcxMTUwMi0yXl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsImFjdGlvbl9pZCI6IkNSRUFURSIsImF0dGFjaG1lbnRfaGFzaCI6IjJkM2M0ZTc1MGI2NDc0ODJkZDY3M2UyNTU3NmIyMjIzYzZiMmE0MTQ0MGY2NGIxMDM4NDYyYmZjODI5OGY0NDEiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiU3R1ZGlvTEFCIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZW5kb3IiOiJDQiBTaXN0ZW1pIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiMy4zLjAuMCIsImlhdCI6MTY4MDA3NDQxNSwiZXhwIjoxNjgwMDc4MDE1fQ.teB6qM9pogoAGlPNgHCB1kW_PUl5JBN0EmsZAIYsjDXMCQiZgEqt69pc-ukzuiDKisV7zrDiScofsDpjF46wckfJS_aR9Lcs-NpitXSh6fQ9HvRIzueT2NbCisfQz82MiaPqyy3RYtzeznmam6Rc1TjFh2ZXPqhtaWsdOgYqBcVPcIh4KjvVVleA8v2VnWEVIePns12xIzswFLmbmZ9WDqpFvYuEYEAXA9mUiGkbFXAKP3d3fTOMLFwHe7GL_qfD0z6oRD09Nw4dNpDmP4bl2LOhpGlp7Xf4relczAFuf7YW-WzxfOc7vxOi5nah3HRv7CcvCY5vwmUGT6VpXRxkTA`

**Comment by masciamariotti** [comment]
Buongiorno,
potrebbe cortesemente allegare la requestBody utilizzata e la response ricevuta? Grazie

**Comment by cbslucalanzano** [comment]
Di seguito la requestBody:

`{ "tipologiaStruttura":"Ospedale", "tipoDocumentoLivAlto":"REF", "assettoOrganizzativo":"AD_PSC101", "dataInizioPrestazione":"20220324112426", "dataFinePrestazione":"20220324112426", "conservazioneANorma":"CONS^^^&2.16.840.1.113883.2.9.3.3.6.1.7&ISO", "tipoAttivitaClinica":"ERP", "identificativoSottomissione": "2.16.840.1.113883.2.9.2.150.4.3.514782", "healthDataFormat": "CDA", "mode": "ATTACHMENT", "identificativoDoc": "SKIP_VALIDATION_2.16.840.1.113883.2.9.2.150.4.4^514782", "identificativoRep": "2.16.840.1.113883.2.9.2.150.4.5.514782", "priorita": false }`

E la response ricevuta:

`{
    "traceID": "f1bf98cf5a743126",
    "spanID": "f1bf98cf5a743126",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.5b113552cd^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}`

**Comment by cbslucalanzano** [comment]
Qualche novità?

**Comment by masciamariotti** [comment]
Buongiorno,
il messaggio 201 OK è corretto, deriva dal fatto che questo tipo di controllo viene effettuato in modo asincrono dal Gateway. Per verificare l'esito della chiamata, dovrebbe eseguire una chiamata al servizio di get status con il WorkflowInstanceId ottenuto in pubblicazione. Grazie

**Comment by cbslucalanzano** [comment]
@masciamariotti ho provato a fare la chiamata a "get status" passando il workflowInstanceId ritornatomi, ma mi viene ritornato un errore 400 - Bad Request.

Di seguito i dettagli della response ricevuta nell'esecuzione del suddetto test:

`{
      "ts": "2023-03-28T14:29:44Z",
      "traceId": "69279763f68151d1",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.1067f90b2d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
    }`

**Comment by cbslucalanzano** [comment]
Il servizio sembra essere stato ripristinato.
