### ISSUE TITLE
validazione RAD - warning codeSystem prestazioni

### ISSUE THREAD

**Issue by gfoini** [ministero-salute/it-fse-support#217]
Buongiorno, nella sezione Prestazioni del tipo documento RAD
otteniamo un Warning in merito al valore <codeSystem> che sembra accettare solamente 
una codifica LOIC oppure ICD9CM

Vi risulta corretto questo controllo ?
Vi ringrazio in anticipo, buona giornata

          <entry>
            <act moodCode="EVN" classCode="ACT">
              <code code="8823.2" codeSystem="2.16.840.1.113883.2.9.2.10.6.11" codeSystemName="Catalogo prestazioni Regione Piemonte" displayName="RADIOGRAFIA (RX) MANO DX (2 PROIEZIONI)" />
              <text>
                <reference value="RADIOGRAFIA (RX) MANO DX (2 PROIEZIONI)" />
              </text>
              <statusCode code="active" />
              <effectiveTime value="20230312231300+0100" />
            </act>
          </entry>

{"traceID":"93c1e53b273f0e34","spanID":"93c1e53b273f0e34","workflowInstanceId":"2.16.840.1.113883.2.9.2.10908.4.4.2.0d0002200a27e9ead4de0891c19736a630eab68fb09f7851561bbfeed7389948.bca03eab73^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","warning":"[W005 | Sezione Esame Eseguito: l'entry/act/code può essere valorizzato secondo i sistemi di codifica\n\t\t\tLOINC @codeSystem='2.16.840.1.113883.6.1'\n\t\t\tICD-9-CM @codeSystem='2.16.840.1.113883.6.103']"}

**Comment by IStacchiotti** [comment]
Buonasera, come eplicitato nella guida di RAD per la sezione Esame Eseguito, l'elemento act/code è obbligatorio e le codifiche consigliate sono LOINC o ICD9-CM ma possono essere anche inserite eventuali codifiche derivanti da Nomenclatura Ministeriale e/o Regionale mediante l'elemento translation.
E' stato aggiunto perciò sullo schematron un controllo non bloccante ovvero il warning perché consiglia, come da specifiche, determinate codifiche ma non esclude la possibilità di usarne altre.

**Comment by gfoini** [comment]
> Buonasera, come eplicitato nella guida di RAD per la sezione Esame Eseguito, l'elemento act/code è obbligatorio e le codifiche consigliate sono LOINC o ICD9-CM ma possono essere anche inserite eventuali codifiche derivanti da Nomenclatura Ministeriale e/o Regionale mediante l'elemento translation. E' stato aggiunto perciò sullo schematron un controllo non bloccante ovvero il warning perché consiglia, come da specifiche, determinate codifiche ma non esclude la possibilità di usarne altre.

Buongiorno, la ringrazio per i chiarimenti. 
buona giornata
