### ISSUE TITLE
Mancato accreditamento A1#111EXPRIVIA000 - EXPRIVIA - EDOTTO - 29722

### ISSUE THREAD

**Issue by rangeletti** [ministero-salute/it-fse-support#218]
Buongiorno, abbiamo ottenuto il seguente errore come risposta dell'accreditamento dell'applicativo in oggetto:
      [ {
        "error" : "TEST_NON_PRESENTE",
        "description" : "Test mancanti rispetto alla checklist:[51]"
      } ]

Nella checklist fornita il caso di test è presente, come di seguito mostrato:
![Edotto_Checklist](https://user-images.githubusercontent.com/125476691/228470651-09219610-c984-41b9-9d71-09a8095128d9.png)

Nelle checklist inviate per gli altri applicativi da noi gestiti questo errore non è stato segnalato, e il caso di test è stato compilato allo stesso modo.
Potreste fornirci un chiarimento rispetto all’errore segnalato? 

Grazie
Rachele

**Comment by rangeletti** [comment]
E' stata fatta una nuova pull request (#214) a correzione di quanto segnalato.

**Comment by IStacchiotti** [comment]
Buongiorno @rangeletti, le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
