### ISSUE TITLE
RSA - "Errore-40" su schematron "schematron_RSA_v7.2.sch" - elemento id non obbligatorio

### ISSUE THREAD

**Issue by MarcoKnezevichInsiel** [ministero-salute/it-fse-support#22]
Buongiorno, analizzando le [specifiche](http://www.hl7italia.it/sites/default/files/Hl7/SuperUser/docs/pubblicati/IG-CDA2-RSA/1.1/HL7IT-IG_CDA2_RSA-v1.1-S.pdf) relative al CDA2 per il Referto di Specialistica Ambulatoriale (RSA), nelle pagine 55-57 l'elemento id è obbligatorio solo nel caso di prestazione associata a un ricovero mentre l'assert sullo schematron "schematron_RSA_v7.2.sch" alla riga 203 esegue tale controllo sempre.
Potete fare una verifiche in merito?   

rileviamo un errore qualore sia presente un elemento del tipo:

`...
<componentOf>
		<encompassingEncounter>
			<effectiveTime value="20220227143650+0200"/>
			<location>
				<healthCareFacility>
					<location>
						<name>Chirurgia Vertebro-Midollare Udine</name>
					</location>
					<serviceProviderOrganization>
						<id root="2.16.840.1.113883.2.9.4.1.3" extension="14VP13" assigningAuthorityName="Ministero della Salute"/>
						<asOrganizationPartOf>
							<id root="2.16.840.1.113883.2.9.4.1.1" extension="060206" assigningAuthorityName="Ministero della Salute"/>
						</asOrganizationPartOf>
					</serviceProviderOrganization>
				</healthCareFacility>
			</location>
		</encompassingEncounter>
	</componentOf>
...`

che sembrerebbe conforme alle specifiche.

Grazie.

**Comment by gndibiase** [comment]
@MarcoKnezevichInsiel grazie della segnalazione, confermiamo la presenza di un errore nella validazione, stiamo apportando una correzione al sistema.
