### ISSUE TITLE
Mancato accreditamento A1#111EXPRIVIA000 - EXPRIVIA - AURORA - 2

### ISSUE THREAD

**Issue by rangeletti** [ministero-salute/it-fse-support#220]
Buongiorno,
avremmo necessità di un chiarimento rispetto all'esito dell'accreditamento dell'applicativo in oggetto. Nella mail ricevuta in data 28/03/2023 alle 19.41 è riportato il json contenente le segnalazioni di errori per i test  [24],[35]. Abbiamo verificato e le segnalazioni di errore non risultano coerenti con quanto presente nei documenti inviati. 
In particolare:
•	[24] nell’esito della validazione allegato risultano mancanti una serie di tag che nei CDA iniettati nei pdf caricati ed utilizzati per i test sono presenti e correttamente valorizzati. Potreste fare una verifica?
•	[35] L’errore segnalato è questo: “Test KO non superato. Assicurarsi che il traceId fornito abbia restituito in fase di validazione un errore bloccante.” Il traceID è valorizzato correttamente nel json fornito. E’ richiesto che nella colonna “ERRORE BLOCCANTE” della checklist venga riportato SI ?

Grazie,
Rachele

**Comment by IStacchiotti** [comment]
Buon pomeriggio @rangeletti, rispondiamo di seguito per punti.

- Per il punto 24: dall'analisi svolta sembra che i cda all'interno del pdf non abbiano gli identificativi delle section per cui riceve quei molteplici errori di validazione.

- Per il punto 35: le chiediamo cortesemente di riprovare e di verificare in seguito che, svolgendo la seguente chiamata v1/status/search/<traceIdRicevuto>, la transazione sia stata scritta correttamente.

Ci faccia sapere se il problema persiste, grazie

**Comment by IStacchiotti** [comment]
Buongiorno. Per completezza di informazione, devono essere inseriti gli ID delle sezioni che riportano il nome delle medesime. Grazie

**Comment by rangeletti** [comment]
Grazie per la risposta, abbiamo provveduto a valorizzare il tag ed effettuato una nuova pull request,
