### ISSUE TITLE
Mancato accreditamento A1#111DEDALUS0000 - Dedalus - ER4H - 2.7.1

### ISSUE THREAD

**Issue by filippoluchini** [ministero-salute/it-fse-support#221]
Buongiorno,
nella mail ricevuta in data odierna ci viene segnalato il seguente errore per i test case con id 35 e 43:
"Test KO non superato. Assicurarsi che il traceId fornito abbia restituito in fase di validazione un errore bloccante."
I traceId riportati nel data.json e nel report-checklist.xlsx sono corretti, entrambi i casi sono marcati come errori bloccanti.
E' possibile avere ulteriori informazioni sul significato dell'errore e sulla relativa correzione?
Grazie

Filippo Luchini

**Comment by IStacchiotti** [comment]
Buon pomeriggio @filippoluchini , le chiediamo cortesemente di riprovare e di verificare in seguito che, svolgendo la seguente chiamata `v1/status/search/<traceId>`, la transazione sia stata scritta correttamente. Grazie

**Comment by filippoluchini** [comment]
Buonasera @IStacchiotti , abbiamo riprovato e verificato la correttezza della transazione. Di seguito quanto ritornato dal servizio indicato:
Caso 35:
`{
    "traceID": "d560583673e2a551",
    "spanID": "e9fc8e5a5895e8b0",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2023-04-03T16:13:51.714+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "Il campo purpose_of_use non è valorizzato",
            "workflowInstanceId": "UNKNOWN_WORKFLOW_ID",
            "traceId": "44db828adcd72fa6",
            "issuer": "UNDEFINED_JWT_ISSUER",
            "expiringDate": "2024-04-02T16:13:51.727+00:00"
        }
    ]
}
`
Caso 43:
`{
    "traceID": "dff71f365b80f380",
    "spanID": "561d3666ae01c32e",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2023-04-03T16:47:41.002+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "Il campo action_id non è corretto",
            "workflowInstanceId": "UNKNOWN_WORKFLOW_ID",
            "traceId": "22b6050d3a1f227d",
            "issuer": "UNDEFINED_JWT_ISSUER",
            "expiringDate": "2024-04-02T16:47:41.017+00:00"
        }
    ]
}`

Abbiamo provveduto ad aggiornare la nostra pull request.
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
