### ISSUE TITLE
TEST case 206 - FALLITO

### ISSUE THREAD

**Issue by cbslucalanzano** [ministero-salute/it-fse-support#222]
Salve,

pur seguendo le indicazioni riportate nel test di cui in oggetto, continuo a ricevere lo status code 201 al posto del 404.

Il mio token FSE:

`eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGS3pDQ0F4T2dBd0lCQWdJVUM3M3hjM3VReG1wL0tuNHNVT2JBaGg5UE95QXdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekF6TVRZeU1qQXhNelphRncweU5qQXpNVFl5TWpBeE16VmFNR2t4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVIwd0d3WURWUVJoREJSRFJqcEpWQzB4TVRGRFFsTkpVMVJGVFVsWVdERWFNQmdHQTFVRUF3d1JVekVqTVRFeFEwSlRTVk5VUlUxSldGZ3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFESFVHamx6THpScmMvUDM3aGkzWGt1QUFWOHNZV3pFN1JJWlRMdURUU3F0bzhYbFhzZjczSlhEeGZnK3phbmliQmhEWXQzbmZCNUM4Vkw2RXZXY0ZUY0pGL3JNM1VPS3RrRTNVQzBocnQzdEs0YXZRMkNtMTMyQnlua0xJUUZiOEVmOHhRekVQUFc0bW9YdTZwSGxEb3g1K0J4Q0tsczRMSk1UTmlTaEFTMnZyRnNRTWFTTHNoNWs3VjcyQmE2cHlpWVh1VjVGU1J6LzNZOCtqWXVPK0VUc3p0dGltM2RNdUZTK21LT1Jxb3RRVStPejFBOUhlWTNKeC9BZ1FxNC9LbHJETytZWnlHVk1UZHdVOG1QRTcwK0tGVVVIU2dtNnFUYmYweGphc05nSGF3anBzRkRZa1BPblo4dURmQzNnaFVERk5WRktNZHlTSzYxd2FCRXgvV1hBZ01CQUFHamdkd3dnZGt3SHdZRFZSMGpCQmd3Rm9BVUZqbXBHZ1dKdHc4dHNqWHR3Z21heFFPRElqOHdFZ1lEVlIwZ0JBc3dDVEFIQmdVclRCMEJDekJ6QmdOVkhSOEViREJxTUdpZ1pxQmtobUpzWkdGd09pOHZZMkZrY3k1bWFXNWhibnBsTG1sMEwwTk9QVU5CSlRJd1RXbHVhWE4wWlhKdkpUSXdaR1ZzYkdFbE1qQlRZV3gxZEdVbE1qQlVaWE4wTEU4OVRXbHVhWE4wWlhKdkpUSXdaR1ZzYkdFbE1qQlRZV3gxZEdVc1F6MUpWREFkQmdOVkhRNEVGZ1FVdTJOaE9FdHRrSUFjc1lLUlFUQnRwb2g1U21vd0RnWURWUjBQQVFIL0JBUURBZ1pBTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFCL2V1TTNVUEh3ejcvV2xPSWV4aHR1TERqZ1I5WXlMa2E2Y25jVDNjVXUyOHU3YkhkcTBmM2NlS0VZMTl6dWthaHVvQUZWT0Y1UVJnN25iTERqVnp2WlpqTFlDdVNaVjhaNmFzTytsb0YrOGlGb0dJTkMzR2lud1diMFh2Wmh4REx0eUU2enFRS015RWFCdlVxcHYvK0lQMzkzeE96RVIxYkk1YldHYmFydVdzUk85dm9laS9OMnNZTU1ZNjdGRGpHWUpqcEYxSXNnM0VDYkcyZGZaQ3lzU0ZiUXNUb2w3RVpQVUxQNDI0bnhFNDVUclRyRkYwRzhvVjZqc1F6bkdVTTJKNFdFV3hRRnU0Ym5DUmt0NGwrWTcvK3FGWFZOaUZqaFBSUm5QSFVMaUpjZkN2VnVDTTdUYndQVmtVTzB5MFlqNVA4cW5aV2xxZXlYYlM0cml4ZlZTTjBYcVNyd2Q2UDQvejZDOE91eEwwQndmMFg4T0NXcDRuR3lJcFpabXd1YkVsOGU5OEdURVZ0OExHRno0d2MzVElvTkpBNjB2bnRteDBIRGwrVzMweUhBbjNQUWVQQ2Z6czQyTlFJV0tQS2MzUUtiblI3T0tBNDNrbXMyUDM4K0x0UEluNzB5dXdqdEZDdTh5VWtDWlk4RXFyQTc5Z2pGelBva2hSNDFyZkZiUjMrUUxQc0lFUXBPN0VKVllxdlYydWVvbU10cU5oaHBrM1pXUThKbTN3YXlGVlVYNG9ncXd3eUYwQ2ptdERFdHFJM2J2c2VJWDVJSEdraTNVR09Sd1FTcWhKWmJINnhVTFRKR3hBRDV6bFAzVW9xd3llN0RGMkZrVFFOUlR0dlJ3TzY5T1lkK0FOWmwrUjB4a3cwcnFhVmd2ZVoxM2FuRlFDMVhkU0tQdUE9PSJdfQ.eyJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExQ0JTSVNURU1JWFgiLCJqdGkiOiIwZjBiZTQyNi02Y2JhLTQ5MjgtOWFmZi0yY2I2ZmU3OWU0YjAiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJzdWIiOiJWUkRNUkM2N1QyMEkyNTdFXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X29yZ2FuaXphdGlvbl9pZCI6IjE1MCIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBDYW1wYW5pYSIsImxvY2FsaXR5IjoiMjAxIiwic3ViamVjdF9yb2xlIjoiQUFTIiwicGVyc29uX2lkIjoiVk5BQ01OOTNIMTlINTAxS15eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsInJlc291cmNlX2hsN190eXBlIjoiKCcxMTUwMi0yXl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsImFjdGlvbl9pZCI6IkNSRUFURSIsImF0dGFjaG1lbnRfaGFzaCI6ImYxODAxMGZlZDBlZjk4ZTkwZjExZTQyNDY0Mzc0YmIwZjk5MDYxZWUyYzA3MTEwOTU1OWJjNWY1M2Q2NTZiYjgiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiU3R1ZGlvTEFCIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZW5kb3IiOiJDQiBTaXN0ZW1pIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiMy4zLjAuMCIsImlhdCI6MTY4MDA4MjI1MiwiZXhwIjoxNjgwMDg1ODUyfQ.aV8OA3EEu0sUjXh0ryUUyUt78lm-_cDBl0wnZR2CHWJA0H39Tbw_1J9qIOBhBsYxwcNAscV0RVlqJHk71pdkqgvzVmt4Ltq2-8LvB7n_eOyoaju9NnKz313ih4LAuMEM7Mgc58wwd3oeh6MTEqWKCNRDLBJZavELq1lLvn2NZ7Kf8Z9dUzYhpYQKvH6b24MqXtVWNcvsB1k-TxwlozUIPzOM5tCQ55DGgzzP0oBXO1FcgnR7vP0LoQ0ITur_p_VM_NAyTFpBnTCdFP2XfWINq-fvYV4YEkfAnFDNvZ1FamGWy0fQDttg4snXjTtsvHJ69vAW8UTNMMTn1K5mmsYztA`

La requestBody:

`{"tipologiaStruttura": "Ospedale", "tipoDocumentoLivAlto": "REF", "assettoOrganizzativo": "AD_PSC101", "dataInizioPrestazione": "20220324102426", "dataFinePrestazione": "20220324102426", "conservazioneANorma": "CONS^^^&2.16.840.1.113883.2.9.3.3.6.1.7&ISO", "tipoAttivitaClinica": "ERP", "identificativoSottomissione": "2.16.840.1.113883.2.9.2.150.4.3.9383776353488", "healthDataFormat": "CDA", "mode": "ATTACHMENT", "identificativoDoc": "SKIP_VALIDATION_2.16.840.1.113883.2.9.2.150.4.4^9383776353488", "identificativoRep": "2.16.840.1.113883.2.9.2.150.4.5.9383776353488"}`

La response ricevuta:

`{
    "traceID": "4451bb562da8ea03",
    "spanID": "4451bb562da8ea03",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.64b9fc635d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}`

Ed infine, l'endpoint invocato in PUT:

https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/9383776353488

**Comment by nturri1306** [comment]
salve ho lo stesso problema ho messo un idDoc sconosciuto ma ricevo un 201 

```
{
  "status": "OK",
  "headers": {},
  "body": {
    "traceID": "b8af12df18e03fbf",
    "spanID": "b8af12df18e03fbf",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.e099922b690ba6f641689478cd8956e793d18736aa177264908d991a62a5b740.ad528856e3^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
  }
}
```

**Comment by nturri1306** [comment]
segnalo problema ancora presente nel 206  ```
 "healthDataFormat": "CDA",
  "mode": "ATTACHMENT",
  "tipologiaStruttura": "Ospedale",
  "attiCliniciRegoleAccesso": [
    "P99"
  ],
  "identificativoDoc": "SKIP_VALIDATION_2.16.840.1.113883.2.9.2.120.4.4^85601381",
  "identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5^39627337",
  "tipoDocumentoLivAlto": "REF",
  "assettoOrganizzativo": "AD_PSC101",
  "dataInizioPrestazione": "20220324102426",
  "dataFinePrestazione": "20220324102426",
  "conservazioneANorma": "CONS^^^\u00262.16.840.1.113883.2.9.3.3.6.1.7\u0026ISO",
  "tipoAttivitaClinica": "ERP",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.2.120.4.3^39627337"
}
```
```
{
  "status": "OK",
  "headers": {},
  "body": {
    "traceID": "f0f89e9f28845857",
    "spanID": "f0f89e9f28845857",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.e099922b690ba6f641689478cd8956e793d18736aa177264908d991a62a5b740.a1d577a678^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
  }
}
```

**Comment by cbslucalanzano** [comment]
@IStacchiotti avete novità? Perchè continuiamo ad avere come risposta uno status code 200.

Vi chiederei di aiutarci quanto prima per evitare ulteriori ritardi sull'accreditamento.

**Comment by IStacchiotti** [comment]
Buon pomeriggio @cbslucalanzano, le confermiamo che la richiesta è stata presa in carico. Si rende necessaria una fix, le daremo evidenza non appena questa sarà rilasciata. Grazie.

**Comment by IStacchiotti** [comment]
Buonasera, Le confermiamo @cbslucalanzano che è stata rilasciata una fix correttiva. La invitiamo cortesemente a riprovare, il problema non dovrebbe più presentarsi. Rimaniamo a completa disposizione in caso contrario. Grazie

**Comment by cbslucalanzano** [comment]
@IStacchiotti Buongiorno, vi confermo che il test ora è andato a buon fine. Grazie del supporto.

Una domanda: 
avendo voi già fatto il merge su main di quanto avevo caricato, per queste ultime modifiche occorre solamente che io aggiorni il mio fork, oppure dovrei creare una nuova pull request?

Attendo vostre. Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno @cbslucalanzano, grazie per il riscontro. 
Essendo già stato fatto il merge della pr, dovrebbe crearne una nuova per il caricamento dei file correttivi.

**Comment by cbslucalanzano** [comment]
Perfetto. Fatto quanto suggerito.

Grazie ancora del supporto.

**Comment by cbslucalanzano** [comment]
Perfetto. Fatto quanto suggerito.

Grazie ancora del supporto.
