### ISSUE TITLE
Test case 194 - FALLITO (Aggiornamento Metadati

### ISSUE THREAD

**Issue by cbslucalanzano** [ministero-salute/it-fse-support#223]
Buongiorno,

il test di cui in oggetto ci torna indietro un messaggio dall'apparato di frontiera così descritto:

`{
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "status": 502,
    "detail": "Invalid response received from the API Implementation",
    "govway_id": "a4b47aff-ce20-11ed-93ec-005056ae54fa"
}`

Abbiamo conformato la chiamata a quanto indicato.
Sapete aiutarci a capire il problema?

Grazie

**Comment by nturri1306** [comment]
salve ricevo stesso errore `502 (bad gateway)` premetto che 2 giorni fà stava funzionando

`idDocumento = SKIP_VALIDATION_2.16.840.1.113883.2.9.2.120.4.4^44490224` (pubblicato e sostituito correttamente)

```
{
  "tipologiaStruttura": "Ospedale",
  "tipoDocumentoLivAlto": "REF",
  "assettoOrganizzativo": "AD_PSC101",
  "dataInizioPrestazione": "20220324102426",
  "conservazioneANorma": "CONS^^^\u00262.16.840.1.113883.2.9.3.3.6.1.7\u0026ISO",
  "tipoAttivitaClinica": "ERP",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.2.[REGIONE oppure INI].4.3.X"
}
```

**Comment by cbslucalanzano** [comment]
Avete qualche novità in merito?

**Comment by cbslucalanzano** [comment]
Il servizio sembra essere tornato a funzionare.
