### ISSUE TITLE
coerenza tra CDA2 e PDF - template di trasformazione 

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#224]
Buongiorno, 
le specifiche tecniche di Iniezione di un CDA in un PDF nel cap 7 riportano quanto segue:

> Il processo per la formazione del documento DEVE prevedere come primo passo la generazione del documento CDA2 dal quale generare il documento PDF applicando una trasformazione che DEVE essere basata su template, quale XSL-FO.
L'incapsulamento della componente CDA2 all'interno del documento PDF DEVE essere effettuata contestualmente alla trasformazione al fine non compromettere la robustezza del processo.
Si sottolinea che il template e il processo di generazione dei documenti DEVONO assicurare la coerenza tra quanto presente nei dati XML del documento CDA2, la loro rappresentazione testuale/grafica nel PDF e la componente XML incapsulata.

E' disponibile un template di riferimento da utilizzare per questa trasformazione o si prevede di realizzarne uno?
Il gateway eseguirà qualche controllo di coerenza tra CDA2 e PDF?
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno Ponsilva, attualmente non è disponibile un template con questa funzionalità, inoltre non abbiamo evidenza che attualmente siano in corso sviluppi in questo senso. In caso di aggiornamenti alla documentazione, verrà data comunicazione su Slack nel canale ufficiale #fse. Per quanto riguarda invece la seconda domanda, segnaliamo che il Gateway non prevede controlli di congruenza tra cda2 e pdf. Grazie

**Comment by ponsilva** [comment]
Grazie per il riscontro
