### ISSUE TITLE
Errore Validazione CERT_VAC: Codice AIC non disponibile

### ISSUE THREAD

**Issue by PRAFFO72** [ministero-salute/it-fse-support#225]
Salve, in fase di validazione ci viene restituito un <details><summary>errore semantico (-b14)</summary>
<p>{"traceID":"4f59e0d6f8143986","spanID":"4f59e0d6f8143986","type":"/msg/semantic","title":"Errore semantico.","detail":"[ERRORE-b14| L'elemento entry/substanceAdministration/consumable/manufacturedProduct/manufacturedMaterial (Dati vaccinazione) DEVE contenere un elemento 'code' valorizzato secondo AIC - @codeSystem='2.16.840.1.113883.2.9.6.1.5'.]","status":422,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.70.4.4.797e00150ca986cbe8ec42721ba96a3272280b54046cf476ef6a0bc8ff4fd3f7.e293ab1b9b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}</p>
</details> 

L'esempio specifico riguarda la generazione di un Certificato con vaccinazioni piuttosto datate,
per cui sono disponibili dati incompleti, tra cui manca il codice AIC.
Tale codice risulta OBBLIGATORIO, ma come si evince dalla tabella a pag. 73 della [documentazione](http://www.hl7italia.it/sites/default/files/Hl7/SuperUser/docs/pubblicati/IG-CDA2-VAC/1.1.1/HL7It-IG_CDA2_VAC-v1.1.1-S.pdf)
il **CONF** è di tipo **R** (Required) con **CARD** **1 ... 1**. A pag 31 dello stesso documento viene specificato:

_Nel caso in cui la cardinalità minima è 1 deve essere fornito o un valore valido o se manca l’informazione è consentito utilizzare un nullFlavor ("elemento vuoto")_

Avevamo dunque optato per inserire comunque la vaccinazione nel CDA del Certificato, ma con codice sconosciuto:
```
         <manufacturedMaterial>
          <code nullFlavor="UNK"/>
         </manufacturedMaterial>
```
Questa soluzione, però, non passa la validazione.
Come ci dobbiamo comportare in questi casi?
Possiamo generare un Certificato includendo i dati della vaccinazione solo nella parte testuale, ma non in quella codificata?
Ci sono altre soluzioni tecniche? 
[CDA_noAIC.zip](https://github.com/ministero-salute/it-fse-support/files/11101362/CDA_noAIC.zip)

**Comment by PRAFFO72** [comment]
Grazie per la risposta.
Ci siamo posti il problema perché il problema era già sorto in passato per nell'invio dei flussi all'Anagrafe Nazionale Vaccini.ell'invio dei flussi l'AIC può essere considerato obbligatorio.

**Comment by izamberlan** [comment]
Buongiorno, intervengo perché sono stato io (sono di Liguria Digitale) a suggerire ai colleghi di ASL 4 Chiavarese l'utilizzo del nullFlavor in questo caso.
La convenzione in CDA 2 è che il nullFlavor sia ammesso eccettuato nei casi in cui il valore è definito "M" (mandatory), non R (Required) nelle tabelle e nel caso in cui le CONF non lo escludano esplicitamente. Per le CONF, faccio riferimento a quanto scritto in IG CDA 2 per le vaccinazioni (conformemente alle specifiche generali CDA 2), pag. 30:
"Qualora non sia stato specificato altrimenti nell’asserzione di conformità, o non previsto dal modello del CDA , si assume che gli elementi/attributi possano essere sempre valorizzati con i nullFlavor. In pratica la specifica di un particolare binding con un value set in una asserzione di conformità (e.g l’elemento .. DEVE essere derivato dal Value Set …), non preclude l’uso del nullFlavor per quel particolare elemento, se non altrimenti specificato"

Un esempio di "altrimenti specificato", sempre prendendo in considerazione la IG delle vaccinazioni, è la CONF-VAC-41, nella quale è esplicitamente negato l'utilizzo del nullFlavor: "Non PUÒ essere utilizzato il nullFlavor per indicare l’indisponibilità del dato."

Quindi si assume che, anche se nella CONF un dato è indicato come obbligatorio, possa essere sempre utilizzato un nullFlavor (eccettuati i casi nei quali il dato sia indicato come Mandatory nelle relative tabelle).

Qui siamo di fronte al caso in cui, a specifica, il nullFlavor può essere utilizzato: non c'è negazione esplicita nella CONF e il dato è obbligatorio, ma con forza di obbligatorietà di tipo R.

D'altra parte, in caso di vaccinazione "antica" (es. pediatrica, per la quale chi come me  è un po' attempato potrebbe non avere un AIC indicato), se il dato del codice AIC è assolutamente obbligatorio e non è noto, per ovvi motivi, all'anagrafe vaccinale o al sistema che genera il certificato vaccinale, ci troveremmo di fronte a due alternative:
- omettere la vaccinazione
- inserire un codice a caso fra quelli possibili per quello specifico vaccino
In ogni caso avremmo informazioni false o carenti. Personalmente non credo sia l'idea.

**Comment by paolo-casillo** [comment]
@PRAFFO72 chiedo scusa, ovviamente c'è una **u** di troppo:
`<manufacturedMaterial> <code nullFlavor="NI" codeSystem="2.16.840.1.113883.2.9.6.1.5" codeSystemName="AIC" displayName="Info non disponibile" /> </manufacturedMaterial>`

**Comment by PRAFFO72** [comment]
> Ovviamente anche la valorizzazione con UNK passa i test.

In che modo siete riusciti a validare un CDA con quell'attributo?
Abbiamo provato ogni possibile valore di [nullFlavor](http://hl7.org/fhir/DSTU2/v3/NullFlavor/index.html),
ma la risposta del Gateway è sempre la stessa:
```
[...]
"type":"/msg/vocabulary"
"title":"Errore vocabolario."
"detail":"Almeno uno dei seguenti vocaboli non è censito: [CodeSystem: 2.16.840.1.113883.2.9.6.1.5, Codes: null]"
"status":400
"instance":"/validation/error"
[...]
```

**Comment by paolo-casillo** [comment]
Premesso che, seguendo solo l'analisie non lo sviluppo, posso effettuare i test solo col gtw certifier, Schematron e XSD, probabilmente il pezzo di XML completo prevede il nullFlavor anche sul traslation.
Incollo quindi una parte più ampia di XML che supera i tre test che ho citato:
`<consumable typeCode="CSM">
                <manufacturedProduct>
                  <manufacturedMaterial>
                    <code nullFlavor="NI" codeSystem="2.16.840.1.113883.2.9.6.1.5" codeSystemName="AIC" displayName="Nessuna informazione">
                            <translation nullFlavor="NI" codeSystem="2.16.840.1.113883.6.73" codeSystemName="ATC" displayName="Nessuna informazione"/>
                    </code>
                  </manufacturedMaterial>
                </manufacturedProduct>
              </consumable>`
Concordo, comunque, con l'analisi sopra esposta da Liguria Digitale.

**Comment by IStacchiotti** [comment]
Buonasera, abbiamo apportato la modificato lato schematorn relativa al controllo del code, prevedendo anche la valorizzazione UNK nel caso in cui non si abbia un codice AIC che valorizzi l'attributo @code dell'elemento code. Si consiglia pertanto di effettuare nuovamente la validazione del cda con lo schematron attuale.
Grazie

**Comment by PRAFFO72** [comment]
Grazie, ma , ad oggi non ci risultano variazioni.
Abbiamo provato questa sintassi:
```
<manufacturedMaterial>
 <code nullFlavor="UNK"/>
</manufacturedMaterial>
```
Il messaggio di ritorno è rimasto questo:
```
{
"traceID":"f7b7e7dc5c08ae2f"
"spanID":"f7b7e7dc5c08ae2f"
"type":"/msg/semantic"
"title":"Errore semantico."
"detail":"[ERRORE-b14| L'elemento entry/substanceAdministration/consumable/manufacturedProduct/manufacturedMaterial (Dati vaccinazione) DEVE contenere un elemento 'code' valorizzato secondo AIC - @codeSystem='2.16.840.1.113883.2.9.6.1.5'.]"
"status":422
"instance":"/validation/error"
"workflowInstanceId":"2.16.840.1.113883.2.9.2.70.4.4.797e00150ca986cbe8ec42721ba96a3272280b54046cf476ef6a0bc8ff4fd3f7.ee7492af31^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```

**Comment by PRAFFO72** [comment]
Abbiamo eseguito un secondo tentativo con questa sintassi:
```
<manufacturedMaterial>
 <code nullFlavor="UNK" codeSystem="2.16.840.1.113883.2.9.6.1.5" codeSystemName="AIC" displayName="Info non disponibile"/>
</manufacturedMaterial>
```
La risposta del Gateway è rimasta quella della scorsa settimana:
```
{
"traceID":"d75a6f57ce36ee0d"
"spanID":"d75a6f57ce36ee0d"
"type":"/msg/vocabulary"
"title":"Errore vocabolario."
"detail":"Almeno uno dei seguenti vocaboli non è censito: [CodeSystem: 2.16.840.1.113883.2.9.6.1.5, Codes: null]"
"status":400
"instance":"/validation/error"
"workflowInstanceId":"2.16.840.1.113883.2.9.2.70.4.4.797e00150ca986cbe8ec42721ba96a3272280b54046cf476ef6a0bc8ff4fd3f7.3be13c2234^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```

**Comment by paolo-casillo** [comment]
@IStacchiotti Nella cartella degli schematron (https://github.com/ministero-salute/it-fse-support/tree/main/validazione/schematron) non risultano commit da due settimane: ci sfugge qualcosa?

**Comment by IStacchiotti** [comment]
Buongiorno a tutti. @paolo-casillo, è stato pubblicato di recente un aggiornamento dello schematron: nell'history al link riportato è visibile la data della commit, ma non la data in cui l'aggiornamento è stato pubblicato. @PRAFFO72, le chiediamo cortesemente di allegare il cda2 che sta tentando di validare. Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che è stata rilasciata una fix correttiva. La invitiamo cortesemente a riprovare, il problema non dovrebbe più presentarsi. Rimaniamo a completa disposizione in caso contrario. Grazie

**Comment by PRAFFO72** [comment]
Grazie, Il CDA con `code nullFlavor="UNK"` è ora considerato valido.
