### ISSUE TITLE
errori 502 su validate-and-replace

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#226]
Buongiorno,
sto provando a chiamare i 2 servizi validate-and-create e validate-and-replace

Il primo ha risposto con esito 
201 Created
{"traceID":"5a53984271e5b879","spanID":"5a53984271e5b879","workflowInstanceId":"2.16.840.1.113883.2.9.2.10.4.4.5b2eb9fb3a04cfdd7e22c14dc7bb94597ce0c47ffc36a4d63cc727ea4dff4946.11aba1b570^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}
però nello status compare SEND_TO_EDS  BLOCKING_ERROR  Connection timed out

Le successive chiamate a validate-and-replace restituiscono sempre errore 502
con response di questo tipo:
{"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"88c621e9-ce38-11ed-8570-005056ae7395"}

Potete darmi qualche indicazione su come risolvere il problema?
Grazie

**Comment by IStacchiotti** [comment]
Gentile utente,
l'errore sembra dovuto a delle recenti problematiche infrastrutturali che abbiamo avuto.
La invitiamo a riprovare. Se il problema dovesse persistere, ci alleghi il payload della richiesta e il CDA utilizzato.

Saluti

**Comment by ponsilva** [comment]
Grazie per la risposta, riprovo l'operazione
