### ISSUE TITLE
GW full vedo errori in alcuni container 

### ISSUE THREAD

**Issue by nturri1306** [ministero-salute/it-fse-support#227]
fatal: failed to clone branch 'main' at url 'https://github.com/ministero-salute/it-fse-gtw-fhir-mapping-engine.git'
fatal: failed to clone branch 'main' at url 'https://github.com/ministero-salute/it-fse-gtw-fhir-mapping-engine.git'
fatal: destination path '.' already exists and is not an empty directory.
fatal: destination path '.' already exists and is not an empty directory.
fatal: failed to clone branch 'main' at url 'https://github.com/ministero-salute/it-fse-gtw-fhir-mapping-engine.git'

fatal: failed to clone branch 'main' at url 'https://github.com/ministero-salute/it-fse-datarepo-data-quality.git'
fatal: destination path '.' already exists and is not an empty directory.
fatal: failed to clone branch 'main' at url 'https://github.com/ministero-salute/it-fse-datarepo-data-quality.git'

**Comment by ponsilva** [comment]
Buongiorno, 
mi era capitato questo errore provando il gateway lite.
Avevo risolto rimuovendo le immagini e rieseguendo docker-compose up.

**Comment by nturri1306** [comment]
salve, ho fatto lo stesso giorni fà ma poi l'errore si ripresenta

**Comment by IStacchiotti** [comment]
Buonasera, si richiede di procedere con una pulizia completa del container, in questo modo l'errore non dovrebbe più riscontrarsi.

Di seguito gli step da eseguire tramite l'app Docker.
1. Eliminare su 'Containers' tutti i container relativi a FSE (full e lite)
2. Eliminare su 'Images' le seguenti immagini: 1. It-fse-ms-runner, 2. confluentinc/cp-kafka
3. Eliminare su 'Volumes' i volumi non più in uso, con Status '-'

Eseguire nuovamente un docker-compose up per avviare nuovamente il container.

**Comment by IStacchiotti** [comment]
Buon pomeriggio, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
