### ISSUE TITLE
errori 500 e 502 in Validazione

### ISSUE THREAD

**Issue by PRAFFO72** [ministero-salute/it-fse-support#230]
Salve, almeno da un paio di giorni stiamo ricevendo dal Gateway di validazione una serie di errori , con frequenza crescente, indipendentemente dal CDA che viene inviato.
Si tratta dell'errore 500 o, molto più spesso, dell'errore 502. 

Ecco due esempi di risposta:

`{"traceID":"eb7952036ddf3490","spanID":"eb7952036ddf3490","type":"/msg/connection-refused","title":"Connection refused","detail":"Connection refused","status":500,"instance":"/msg/connection-refused"}`

`{"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"fca3e15c-cec9-11ed-93ec-005056ae54fa"}`

**Comment by IStacchiotti** [comment]
Buongiorno @PRAFFO72,
l'errore sembra dovuto a delle recenti problematiche infrastrutturali che abbiamo avuto.
La invitiamo a riprovare. Se il problema dovesse persistere, ci alleghi il payload della richiesta e il CDA utilizzato.

Saluti
