### ISSUE TITLE
Validazione Documento: InvalidResponse

### ISSUE THREAD

**Issue by ZucchettiCentroSistemi** [ministero-salute/it-fse-support#232]
Buongiorno,
in fase di validazione del documento sto ricevendo il seguente messaggio di errore:
{
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "status": 502,
    "detail": "Invalid response received from the API Implementation",
    "govway_id": "2128aca6-cf8f-11ed-93ec-005056ae54fa"
}

Request body:
{
  "mode" : "ATTACHMENT",
  "activity" : "VALIDATION"
}

Allego i due token.
[Sign_toren.txt](https://github.com/ministero-salute/it-fse-support/files/11119411/Sign_toren.txt)
[Auth_token.txt](https://github.com/ministero-salute/it-fse-support/files/11119412/Auth_token.txt)

**Comment by masciamariotti** [comment]
Buongiorno,
da una prima analisi abbiamo notato le seguenti incongruenze:
Sign_token (JWT):
nel payload mancano i campi obbligatori
- subject_application_id
- subject_application_vendor
- subject_application_version.

Auth_token:
nel payload gli unici campi presenti dovrebbero essere:
- iss
- iat
- exp
- jti
- aud
- sub

Per qualsiasi dubbio può far riferimento alla [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt)

**Comment by masciamariotti** [comment]
L'errore riportato si riferisce al templateId utilizzato.
Occorre infatti far riferimento al POCD_MT000040UV02 perchè è quello in uso in FSE2.0. I controlli presenti sugli integration kit fanno riferimento all’ultima versione del POCD, ovvero @extension=POCD_MT000040UV02. I CDA2 valorizzati con la precedente versione restituiscono appunto un esito negativo.

[Link](https://github.com/HL7/cda-core-2.1) di dettaglio delle specifiche FSE 2.0 che riporta l’ultima versione del POCD.
[Link](https://github.com/ministero-salute/it-fse-support/tree/main/validazione/xsd) agli xsd usati dal gateway

**Comment by IStacchiotti** [comment]
Buonasera, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
