### ISSUE TITLE
Test 353 - FALLITO (Aggiornamento Metadati)

### ISSUE THREAD

**Issue by cbslucalanzano** [ministero-salute/it-fse-support#233]
Non riusciamo ad eseguire il test poiché ci viene tornato il seguente messaggio di errore dall'apparato di frontiera:

`{
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "status": 502,
    "detail": "Invalid response received from the API Implementation",
    "govway_id": "879da01d-cf9e-11ed-8570-005056ae7395"
}`

**Comment by nturri1306** [comment]
ho lo stesso problema ricevo spesso
```
 {
  "status": "BAD_GATEWAY",
  "headers": {},
  "body": {
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "detail": "Invalid response received from the API Implementation",
    "status": 502
  }
}
```

**Comment by cbslucalanzano** [comment]
Sembra che ora sia tornato a funzionare, ma utilizzando questo tipo di data scorretta: "2022:05:09-07:30+00".
