### ISSUE TITLE
Test 196 - FALLITO (Oscuramento)

### ISSUE THREAD

**Issue by cbslucalanzano** [ministero-salute/it-fse-support#234]
Nonostante abbiamo verificato la presenza del documento pubblicato in precedenza mediante la chiamata "GET Status", effettuando il suddetto test, continuiamo a ricevere un 404:

`{
    "traceID": "3defae9090c2c587",
    "spanID": "3defae9090c2c587",
    "type": "/msg/eds-error",
    "title": "Eds error.",
    "detail": "Document cannot be found on the Server FHIR",
    "status": 404,
    "instance": "/msg/eds-document-missing"
}`

Di seguito invece la risposta alla chiamata GET Status che conferma la pubblicazione del documento:

`{
    "traceID": "ee08ca2eb043802e",
    "spanID": "64b76832b4c164a2",
    "transactionData": [
        {
            "eventType": "PUBLICATION",
            "eventDate": "2023-03-28T12:43:45.040+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "SKIP_VALIDATION_2.16.840.1.113883.2.9.2.150.4.4^514782",
            "subject": "VRDMRC67T20I257E^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "ERP",
            "organizzazione": "150",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.f34c9828c5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "b6b56d5151e2b2ed",
            "issuer": "integrity:S1#111CBSISTEMIXX",
            "expiringDate": "2024-03-27T12:43:45.069+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2023-03-28T12:43:45.066+00:00",
            "eventStatus": "SUCCESS",
            "message": "{\"esito\":true,\"errorMessage\":\"Regime di mock abilitato\",\"traceID\":\"2cb1f489a46a5641\",\"spanID\":\"2cb1f489a46a5641\"}",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.f34c9828c5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2024-03-27T12:43:45.824+00:00"
        },
        {
            "eventType": "SEND_TO_EDS",
            "eventDate": "2023-03-28T12:43:45.125+00:00",
            "eventStatus": "SUCCESS",
            "message": "{\"esito\":true}",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.f34c9828c5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2024-03-27T12:43:46.578+00:00"
        },
        {
            "eventType": "EDS_WORKFLOW",
            "eventDate": "2023-03-28T13:00:00.006+00:00",
            "eventStatus": "SUCCESS",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.f34c9828c5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2024-03-27T13:00:00.024+00:00"
        }
    ]
}`

**Comment by IStacchiotti** [comment]
Buongiorno, la transazione non è stata finalizzata correttamente a causa dei disservizi degli ultimi giorni segnalati su Slack. Vi chiediamo cortesemente di riprovare. Se il problema persiste, ci alleghi cortesemente il payload della nuova richiesta e il CDA utilizzato. Grazie

**Comment by cbslucalanzano** [comment]
Buongiorno, il problema persiste tornandomi 404 (documento non trovato), pur verificando la sua presenza attraverso la chiamata GET Status.

Il CDA utilizzato è quello contenuto nel file da voi fornito "SIGNED_LAB1.pdf".

Questo il test 192 in cui avevamo eseguito la precedente pubblicazione:

`{
      "id": 192,
      "ts": "2023-03-28T11:43:45Z",
      "traceId": "b6b56d5151e2b2ed",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.f34c9828c5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "files": ["SIGNED_LAB1.pdf"]
    },`

Per quanto invece riguarda l'esecuzione di questo test, di seguito il body utilizzato:

`{
"tipologiaStruttura":"Ospedale",
"attiCliniciRegoleAccesso":["P99"],
"tipoDocumentoLivAlto":"REF",
"assettoOrganizzativo":"AD_PSC101",
"dataInizioPrestazione":"20220324112426",
"dataFinePrestazione":"20220324112426",
"conservazioneANorma":"CONS^^^&2.16.840.1.113883.2.9.3.3.6.1.7&ISO",
"tipoAttivitaClinica":"ERP",
"identificativoSottomissione": "2.16.840.1.113883.2.9.2.150.4.3.514782"
}`

Attendo vostre.
Grazie per la collaborazione.

**Comment by cbslucalanzano** [comment]
Ripubblicando un nuovo documento ed eseguendo nuovamente questo test, tutto sembra funzionare.
