### ISSUE TITLE
Validazione CERT_VACC (caso di test 13): discrepanza tra file doc e excel

### ISSUE THREAD

**Issue by PRAFFO72** [ministero-salute/it-fse-support#235]
Salve, per il caso di test 13 del CERT_VACC, abbiamo rilevato un'incongruenza tra le indicazioni scritte nel documento di [testo](https://github.com/ministero-salute/it-fse-accreditamento/raw/main/Test%20Case/Validazione/4-Certificato%20Vaccinale/casi%20di%20test%20CERT_VACC.docx) e il corrispondente foglio del file [excel](https://github.com/ministero-salute/it-fse-accreditamento/raw/main/Test%20Case/Validazione/4-Certificato%20Vaccinale/CDA2_Certificato%20Vaccinale_KO.xlsx).

Nel file docx è scritto:
 ```
CASO DI TEST 13
Il mancato inserimento dei dati relativi al vaccino somministrato (code) genera un errore semantico.
```
Mentre nel corrispondente foglio della cartella xlsx (cella F52) il testo evidenziato in giallo dice:
`valorizzazione errata del codice del farmaco somministrato`
Questo ultima indicazione, però, genererebbe un errore _**terminologico**_ ("Errore vocabolario.").

Confermate che per eseguire correttamente il test dobbiamo attenerci alle indicazione del documento testuale?

**Comment by IStacchiotti** [comment]
Buongiorno.
Grazie della segnalazione. Vi confermiamo che per eseguire correttamente il test case 13 KO è necessario attenersi alle indicazioni riportate nel word.

**Comment by PRAFFO72** [comment]
Grazie
