### ISSUE TITLE
test 194 errore

### ISSUE THREAD

**Issue by nturri1306** [ministero-salute/it-fse-support#237]
mi ha richiesto dataFinePrestazione e attiCliniciRegoleAccesso che prima non chiedeva nell originale  del test case 
ma scatta cmq errore

```
{
  "tipologiaStruttura": "Ospedale",
  "attiCliniciRegoleAccesso": [
    "P99"
  ],
  "tipoDocumentoLivAlto": "REF",
  "assettoOrganizzativo": "AD_PSC101",
  "dataInizioPrestazione": "20220324102426",
  "dataFinePrestazione": "20220324102426",
  "conservazioneANorma": "CONS^^^\u00262.16.840.1.113883.2.9.3.3.6.1.7\u0026ISO",
  "tipoAttivitaClinica": "ERP",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.2.120.4.3^18984991"
}


{
  "status": "BAD_GATEWAY",
  "headers": {},
  "body": {
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "detail": "Invalid response received from the API Implementation",
    "status": 502,
    "govway_id": "14a47503-d1f8-11ed-8570-005056ae7395"
  }
}

```

**Comment by nturri1306** [comment]
aggiungo la nuova risposta di errore: ```
{
  "status": "BAD_GATEWAY",
  "headers": {},
  "body": {
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "detail": "Invalid response received from the API Implementation",
    "status": 502,
    "govway_id": "2da33b2f-d2bc-11ed-8570-005056ae7395"
  }
}
```

**Comment by nturri1306** [comment]
confermo che lo stesso errore si ripete per il 196 oscuramento

**Comment by nturri1306** [comment]
salve sono riuscito a ripetere tutta la sequenza 192, 193, 194, 196, 195 credo che il problema sia il token  nel metodo delete mi aveva segnalato che adesso voleva personId che prima mi chiedeva lo rimesso anche per i metadati e adesso sono passati tutti.

**Comment by IStacchiotti** [comment]
Buongiorno @nturri1306, la presente viene chiusa come risolta dal momento che sono stati superati i problemi relativi ai token. Per l'altro problema segnalato, riceverà quanto prima risposta nel ticket #236, grazie.
