### ISSUE TITLE
informazioni su PullRequest #121 per l'iter di Accreditamento

### ISSUE THREAD

**Issue by EbitFSE** [ministero-salute/it-fse-support#238]
Buongiorno, la settimana scorsa abbiamo visto che è stato eseguito il merge della PullRequest #121 https://github.com/ministero-salute/it-fse-accreditamento/pull/121 (Accreditamento Ebit), 
quali passaggi sono necessari adesso?
Grazie per l'attenzione

**Comment by EbitFSE** [comment]
buonasera, abbiamo ricevuto la mail di mancato superamento dei test per il servizio di validazione di Ebit Srl ( A1#111EBITSRLXXXX ). 
Limitandoci al caso di test 11, ci risulta che il CDA2 contenga i valori contestati nel file error.json, ad esempio alla prima riga l'errore è: "<error code='001' attribute='code' actual = '' expected = '55111-9'> ClinicAlDocument/component/structuredBody/component/section[ID='Esame_eseguito']/code</error>".
Nel file CDA.xml il contenuto per quella parte è:
<code code="55111-9"
		      codeSystem="2.16.840.1.113883.6.1"
		      codeSystemName="LOINC"
		      displayName="Descrizioni attuale procedure di imaging"/>
<title>Esame Eseguito</title>.
è possibile che ci sia un problema nell'apertura del cda o nel match tra il report-checklist.xlsx e il data.jason?

**Comment by IStacchiotti** [comment]
Buongiorno, le chiediamo cortesemente di allegare il cda in questione, grazie.

**Comment by EbitFSE** [comment]
[CDA_EBIT_TEST11.zip](https://github.com/ministero-salute/it-fse-support/files/11148771/CDA_EBIT_TEST11.zip)
Buondì, allego il CDA zippato, 
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, dalle verifiche è emerso che gli errori che ricevete sono dovuti alla mancata valorizzazione degli ID delle diverse section. Fateci sapere se il problema persiste, grazie.

**Comment by EbitFSE** [comment]
Buonasera, abbiamo provveduto ad aggiungere gli ID all'interno dei tag Section e abbiamo aggiornato e sottomesso nuovamente il caso 11. Attendiamo l'esito.
Grazie

**Comment by EbitFSE** [comment]
Buongiorno, nel caricare il caso di test 12 e aggiornare data.json e report-chckelist abbiamo un errore che ci impedisce di fare il push verso il repository remoto. Alleghiamo qui il pdf firmato e i due files, in attesa di risolvere il problema.
[A1#111EBITSRLXXXX-EBITSRL-SUITESTENSA-2.1b34.x.zip](https://github.com/ministero-salute/it-fse-support/files/11177441/A1.111EBITSRLXXXX-EBITSRL-SUITESTENSA-2.1b34.x.zip)
Grazie

**Comment by masciamariotti** [comment]
Buongiorno,
purtroppo affinchè il processo di verifica di accreditamento funzioni, è necessario che i file vengano pushati sul repository.

**Comment by EbitFSE** [comment]
Buongiorno, abbiamo aperto una segnalazione, siamo in attesa.
[https://github.com/ministero-salute/it-fse-support/issues/260](url)

**Comment by EbitFSE** [comment]
> Buongiorno, purtroppo affinchè il processo di verifica di accreditamento funzioni, è necessario che i file vengano pushati sul repository.

Buongiorno, dovremmo aver risolto il problema, a questo punto aspettiamo che venga eseguito il merge.
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, grazie per il riscontro. La presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
