### ISSUE TITLE
Errore vocabolari validazione Verbale di Pront Soccorso (VPS)

### ISSUE THREAD

**Issue by MarcoKnezevichInsiel** [ministero-salute/it-fse-support#24]
Buongiorno, abbiamo rilevato un nuovo problema con i vocabolari, in questo caso il problema è relativo al Verbale di Pronto Soccorso ed in particolare alla "causa d'accesso" (vedi 2.16.840.1.113883.2.9.1.11.1.2.12 nel CDA VPS [qui](http://www.hl7italia.it/sites/default/files/Hl7/SuperUser/docs/pubblicati/IG-CDA2-VPS/1.1/HL7IT-IG_CDA2_VPS-v1.1-S.pdf) ).

Per il CDA allegato riceviamo l'errore:
`{
	"message": null,
	"classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException",
	"responseGatewayDto": {
		"traceID": "ed3edaad3550014e",
		"spanID": "ed3edaad3550014e",
		"workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.1a4567ed9fc6b0f33c58a44bbd37e8a9e4d8808c4c15f05e628690277a9e5025.78717aa711^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
		"type": "/msg/vocabulary",
		"title": "Errore vocabolario.",
		"status": 400,
		"detail": "Almeno uno dei seguenti vocaboli non sono censiti : [Dizionario : 2.16.840.1.113883.2.9.1.11.1.2.12 ,Vocaboli:34]",
		"instance": "/msg/vocabulary",
		"govwayId": null,
		"warning": null
	}
}`

Il CDA è conforme rispetto allo schematron `schematron_VPS_v 2.7.sch`.

Aggiungo che sarebbe utile avere l'elenco degli errori presenti in un CDA, qualora ci siano più errori nel CDA stesso per non iterare i tentativi più volte. Abbiamo provato a validare documenti con più errori ma viene restituito un messaggio di errore afferente solo al primo errore riscontato.

Esiste un repository ove verificare i vocabolari che utilizzate nel gateway?

Grazie.

[Originale_CDA2_PN_Verbale_firmato.xml.txt](https://github.com/ministero-salute/it-fse-support/files/9811409/Originale_CDA2_PN_Verbale_firmato.xml.txt)

**Comment by pFonziSogei** [comment]
Salve, alcuni code appartenenti ai dizionari inseriti non sono corretti. A breve verranno pubblicati tutti i dizionari da usare su GitHub. Riporto i dizionari che vanno in errore: [CodeSystem: 2.16.840.1.113883.2.9.6.1.54.5, Codes: DIM], [CodeSystem: 2.16.840.1.113883.2.9.6.1.54.6, Codes: 512], [CodeSystem: 2.16.840.1.113883.2.9.6.1.54.4, Codes: 103, MODERATAMENTE_CRITICO], [CodeSystem: 2.16.840.1.113883.2.9.6.1.54.1, Codes: 63], [CodeSystem: 2.16.840.1.113883.2.9.6.1.54.2, Codes: 40267], [CodeSystem: 2.16.840.1.113883.6.103, Codes: 4568]

**Comment by stellariAbstract** [comment]
Buonasera.
Sto approntando i primi test di validazione di VPS ed ho un problema similare, se non il medesimo.

Almeno uno dei seguenti vocaboli non è censito: 
[CodeSystem: 2.16.840.1.113883.2.9.6.1.54.6, Codes: 3 ], 
[CodeSystem: 2.16.840.1.113883.2.9.6.1.54.1, Codes: 6 ], 
[CodeSystem: 2.16.840.1.113883.6.103, Codes: 519.72]

Per quanto riguarda i primi due, sono identici al vostro VPS di esempio al link [https://github.com/ministero-salute/it-fse-support/blob/3179a3ca1347b4675ff1f59a37f6f4b06d51359f/doc/esempi/CDA/VPS.xml](url)

Relativamente alla sua precedente risposta al collega, dove dice " A breve verranno pubblicati tutti i dizionari da usare su GitHub", gentilmente chiedo se sono stati pubblicati i suddetti dizionari e dove potrei reperirli. 

Inoltre, dovendo rispettare anche le specifiche regionali imposte dal servizio SOLE dell'Emilia Romagna, mi chiedo come questi dizionari non vengano accettati da SOGEI e come rendere i due compatibili, dovendo validare su SOGEI e pubblicare su SOLE.

Allego PDF del documento in fase di test di validazione.

Grazie,
Stefano.

[PDF_test_VPS.pdf](https://github.com/ministero-salute/it-fse-support/files/11654376/PDF_test_VPS.pdf)
