### ISSUE TITLE
Problema nell'effetuare la chiamata al server

### ISSUE THREAD

**Issue by greglombardi** [ministero-salute/it-fse-support#240]
Buongiorno stiamo cercando di effettuare una chiamata con NodeJS utilizzando i certificati fornitici, tuttavia non siamo in grado di connetterci a causa dell'utilizzo di un algoritmo di firma debole o obsoleto. Infatti, stiamo ricevendo il seguente errore: "0A00018E: SSL routines::ca md too weak".

Non siamo a conoscenza se altri clienti abbiano riscontrato la stessa problematica. Dopo aver effettuato alcune ricerche su Internet, sembra che l'unica soluzione sia quella di aggiornare il certificato utilizzando un algoritmo di firma più sicuro e moderno, come SHA-256. Abbiamo tentato diverse soluzioni, ma non abbiamo riscontrato alcun miglioramento.

Desideriamo gentilmente richiedere se è possibile rigenerare i certificati utilizzando un algoritmo di firma più moderno e sicuro.

Fateci sapere, grazie.

**Comment by IStacchiotti** [comment]
Buongiorno @greglombardi, dal canale #fse su Slack ci risulta che è riuscito a procedere nell'integrazione con il Gateway. Ci conferma che la richiesta è ancora bloccante? In caso contrario procederemo alla chiusura del presente. Si può sempre procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto. Grazie.

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
