### ISSUE TITLE
Errore PDF_UNEXPECTED_CDA nel report di accreditamento

### ISSUE THREAD

**Issue by davidecasiraghi** [ministero-salute/it-fse-support#241]
Buongiorno, abbiamo avuto i seguenti errori nel report di accreditamento

[ {
  "id" : 11,
  "error" : "PDF_UNEXPECTED_CDA",
  "description" : "CDA contenuto nel PDF non conforme a quello associato al TraceID"
}, {
  "id" : 12,
  "error" : "PDF_UNEXPECTED_CDA",
  "description" : "CDA contenuto nel PDF non conforme a quello associato al TraceID"
} ]

Abbiamo già fatto due ulteriori pull request ripetendo i test e verificando di avere caricato su GitHub gli stessi file inviati al sevizio di validazione, ma l'esito è sempre lo stesso.
Non capiamo quale sia il problema.

**Comment by davidecasiraghi** [comment]
Aggiungo i dati identificativi dell'applicativo:
subject_application_id: PriamoRIS
subject_application_vendor: BCS
subject_application_version: 4.14.0.0

**Comment by IStacchiotti** [comment]
Buonasera, sia per il test 11 che per il test 12 sembrebbe che vi sia un'incongrunza tra il cda pushato su git e quello registrato dal gtw (in particolare dagli screen in allegato si nota la presenza di spazi in più).
![test11](https://user-images.githubusercontent.com/122798799/231514590-49210d55-f67a-4366-8039-714138c68b64.png)
![test12](https://user-images.githubusercontent.com/122798799/231514599-438d0b9d-4d96-48ad-af5f-9bb6eee3bc9b.png)

**Comment by IStacchiotti** [comment]
Buongiorno @davidecasiraghi, dal momento che avete fatto una nuova pull request, la presente viene chiusa come risolta. Nel caso in cui la fix proposta non sia stata risolutiva (se doveste ricevere quindi nuova comunicazione di errore tramite email), vi invitiamo a procedere con la riapertura per ricevere ulteriore supporto. Grazie
