### ISSUE TITLE
Delucidazioni mancato accreditamento

### ISSUE THREAD

**Issue by BiMind** [ministero-salute/it-fse-support#242]
Buongiorno,
Abbiamo ricevuto risposta da fse_support@sogei.it a seguito della nostra PR per l'accreditamento in validazione.
Ci notificano i seguenti errori nel file “report-checklist.xlsx”:
•	29: E' necessario valorizzare le seguenti colonne:F, G, H, I, L, M, O, P
•	32: E' necessario valorizzare le seguenti colonne:F, G, H, I, L, M, O, P
•	37: E' necessario valorizzare le seguenti colonne:F, G, H, I, L, M, O, P
•	40: E' necessario valorizzare le seguenti colonne:F, G, H, I, L, M, O, P

Da un controllo interno ci risulta che le colonne indicate sono tutte valorizzate ad eccezione della I (WORKFLOWINSTANCEID), per la quale è esplicitato nelle "Istruzioni Compilazione" che può essere lasciata vuota nel caso in cui questo dato non ci venga ritornato dal Gateway

Linko la PR https://github.com/ministero-salute/it-fse-accreditamento/pull/180

Di seguito i nostri identificativi
subject_application_id: Human	
subject_application_vendor: BiMind	
subject_application_version: 10.6

Grazie

**Comment by BiMind** [comment]
Buongiorno, ci sono novità?

**Comment by IStacchiotti** [comment]
Buonasera @BiMind, ci risulta che dovrebbe esserle arrivata oggi pomeriggio una mail con i nuovi esiti dei test svolti. La invitiamo a proseguire il thread nel caso in cui dovesse essere necessario supporto ulteriore. Grazie.

**Comment by BiMind** [comment]
Buonasera @IStacchiotti, grazie per il riscontro.
Per i test KO dei JWT (32, 40, 37, 29) ci viene notificato un errore del tipo "Test KO non superato. Assicurarsi che il traceId fornito abbia restituito in fase di validazione un errore bloccante.".
Questo errore è dato dal fatto che nel report-checklist.xlsx abbiamo settato la colonna "Errore bloccante" a NO?

Se fosse questo il problema, allora ci viene un dubbio: per errore bloccante ci si riferisce a un errore bloccante lato utente o lato gateway? Perchè in questo caso, se il JWT è errato, lato utente non risulta essere un errore bloccante, in quanto si riproverà l'invio verso il gateway in background. Se invece ci si riferisce al gateway, allora si è bloccante

Grazie per il supporto

**Comment by BiMind** [comment]
Buongiorno,
Abbiamo effettuato nuovamente i test, aggiorneremo la PR appena avremo risposta all'altra issue che abbiamo aperto (che linkiamo per completezza https://github.com/ministero-salute/it-fse-support/issues/245)

Grazie
