### ISSUE TITLE
Cda Bilingue: compatibilità fra cda e PDF

### ISSUE THREAD

**Issue by Fusarolia** [ministero-salute/it-fse-support#243]
Buongiorno,
a seguito di confronto con la provincia autonoma di Bolzano è emerso che per una normativa provinciale i documenti (certificato vaccinale e scheda giornaliera) devono essere conferiti a FSE in modalità bilingue.
La strategia dai noi pensata sarebbe quella di mantenere il CDA2 in lingua italiana e il pdf riportante le descrizioni delle vaccinazioni in lingua italiana e tedesca. 
E' corretto che il cda2 abbia solo i dati in italiano e il pdf anche le traduzioni in tedesco?
La nostra ipotesi si fonda sul fatto che l'informazione non cambia, ma cambia solo la relativa rappresentazione. 
Ci potete dare conferma?

Cordiali saluti.
Alessandro Fusaroli
Onit Group

**Comment by Fusarolia** [comment]
Buongiorno 
vorremmo sapere se problematica indicata ci sono delle novità in merito

Cordiali Saluti
Alessandro Fusaroli

**Comment by masciamariotti** [comment]
Buongiorno Alessandro,
possiamo confermare che, a livello di CDA2, se questo è conforme alle specifiche HL7 italiane, il processo di validazione sintattica, semantica e terminologica andrà a buon fine, indipendentemente dalla lingua utilizzata nelle descrizioni all'interno del PDF

**Comment by Fusarolia** [comment]
Buongiorno, 
verificando specifiche hl7 italia, non ho visto tag per utilizzare la traduzione in altra lingua. 
E' possibile avere indicazioni più specifiche per la gestione dei tag della seconda lingua?

Distinti Saluti, buona giornata

**Comment by masciamariotti** [comment]
Buongiorno, è possibile includere la traduzione in tedesco anche nel CDA2 utilizzando il tag 'translation' nei campi codificati riportando nell'attributo @displayName la traduzione, mentre per i campi testuali è possibile inserire le informazioni in entrambe le lingue senza nessun vincolo. Inoltre, si specifica che nell'elemento

`substanceAdministration/consumable/manufacturedProduct/manufacturedMaterial/code`

possono essere inseriti più elementi 'translation' di cui almeno uno richiede la mappatura nel sistema di codifica ATC il codice AIC del vaccino presente nel 'code', come da specifiche.
