### ISSUE TITLE
Schematron del certificato vaccinale – author e legalAuthenticator per documento prodotto e firmato da dispositivo

### ISSUE THREAD

**Issue by paolalup** [ministero-salute/it-fse-support#247]
Buongiorno, vi chiedo cortesemente una verifica sullo schematron del certificato vaccinale.

Da specifiche HL7 dei documenti di vaccinazione Versione 1.1.1 è previsto che:
1. Il campo legalAuthenticator / assignedEntity / id possa essere valorizzato con CF di persona fisica (OID 2.16.840.1.113883.2.9.**4**.3.2) o con p.IVA di azienda (OID 2.16.840.1.113883.2.9.**6**.3.2). Tuttavia lo schematron verifica che ci sia l’OID 2.16.840.1.113883.2.9.**4**.3.2, quindi ammette solo il caso della persona fisica. 
2. Il campo author / assignedAuthor / id possa essere valorizzato con CF di persona fisica (OID 2.16.840.1.113883.2.9.4.3.2) o con p.IVA di azienda (di cui non viene specificato l’OID ma assumiamo sia 2.16.840.1.113883.2.9.6.3.2 come per legalAuthenticator e come da Affinity Domain) o con nullFlavor. Tuttavia lo schematron verifica che ci sia l’OID 2.16.840.1.113883.2.9.4.3.2 oppure nullFlavor, quindi ammette solo il caso della persona fisica o di autore ignoto. Inoltre non è chiaro, nel caso di autore valorizzato con p.IVA dell’Azienda, come vada compilato il campo <name>, che da schematron è obbligatorio e richiede di valorizzare anche <family> e <given>: inseriamo nullFlavor in family e given?

Grazie mille del supporto
Paola

**Comment by IStacchiotti** [comment]
Buon pomeriggio.
Per entrambi gli elementi author e legalAuthenticator nello schematron di Certificato Vaccinale è previsto il controllo sull'id, che può essere valorizzato o con il CF di persona fisica (OID 2.16.840.1.113883.2.9.4.3.2) o con p.IVA di azienda (OID 2.16.840.1.113883.2.9.6.3.2).
Per quanto concerne l'elemento name, è obbligatoria la presenza del family e given ma non è obbligatoria una specifica valorizzazione dei sotto elementi.

**Comment by paolalup** [comment]
Buongiorno e grazie. Recepisco le vostre indicazioni sull'elemento name e i sotto elementi.

Per quanto riguarda gli altri punti invece vi chiedo cortesemente ancora una verifica. Ho provato a validare un cda2 in cui author e legalAuthenticator sono valorizzati con la p.IVA (OID 2.16.840.1.113883.2.9.6.3.2) e ottengo questi errori:

`"ERRORE-25| L'elemento ClinicalDocument/legalAuthenticator/assignedEntity DEVE contenere almeno un elemento id valorizzato con l'attributo @root='2.16.840.1.113883.2.9.4.3.2'" 
"ERRORE-18| L'elemento author/assignedAuthor DEVE contenere almeno un elemento 'id' con il relativo attributo @root='2.16.840.1.113883.2.9.4.3.2'" `

che sono coerenti con lo schematron pubblicato [su github ](https://github.com/ministero-salute/it-fse-support/blob/main/validazione/schematron/schematron_certificato_VACC.sch) e da cui ho dedotto che non sia supportata la p. IVA. 
Allego il cda2 ed il pdf con cda2 in attachment utilizzati per i test: 
[cda_vac_dispositivo_1.zip](https://github.com/ministero-salute/it-fse-support/files/11167807/cda_vac_dispositivo_1.zip)
Potete cortesemente verificare?

Vi ringrazio nuovamente

**Comment by IStacchiotti** [comment]
Buonasera, è stata rilasciata una modificato sullo schematron del certificato vaccinale, per cui l'errore non dovrebbe più presentarsi. La invitiamo pertanto a riprovare. Ci faccia sapere se il problema persiste. Grazie.

**Comment by paolalup** [comment]
Buonasera e grazie!

Abbiamo provato a validare il cda2 direttamente sullo schematron aggiornato disponibile [su github](https://github.com/ministero-salute/it-fse-support/blob/main/validazione/schematron/schematron_certificato_VACC.sch) e confermiamo che questa volta la validazione è andata a buon fine!

Interrogando i servizi di validazione esposti per l'accreditamento, continuiamo però a ottenere errore:
[ERRORE-25| L'elemento ClinicalDocument/legalAuthenticator/assignedEntity DEVE contenere almeno un elemento id valorizzato con l'attributo @root='2.16.840.1.113883.2.9.4.3.2'],
ERRORE-18| L'elemento author/assignedAuthor DEVE contenere almeno un elemento 'id' con il relativo attributo @root='2.16.840.1.113883.2.9.4.3.2'],

Potete cortesemente effettuare anche questa verifica?
Allego i file usati per la validazione.
[certificato vaccinale dispositivo.zip](https://github.com/ministero-salute/it-fse-support/files/11334342/certificato.vaccinale.dispositivo.zip)

Vi ringrazio nuovamente
Paola

**Comment by paolalup** [comment]
Buongiorno, confermo che il problema ora non si presenta più. Grazie ancora!

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Schematron del certificato vaccinale – author e legalAuthenticator per documento prodotto e firmato da dispositivo (Issue #247)" inviata il 12/05/2023 11:52:45. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Schematron del certificato vaccinale – author e legalAuthenticator per documento prodotto e firmato da dispositivo (Issue #247)" inviata il 12/05/2023 14:22:30. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Schematron del certificato vaccinale – author e legalAuthenticator per documento prodotto e firmato da dispositivo (Issue #247)" inviata il 12/05/2023 14:22:28. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.
