### ISSUE TITLE
Mancato accreditamento A1#111EXPRIVIA000 - EXPRIVIA - EDOTTO - 29722

### ISSUE THREAD

**Issue by vvarratta** [ministero-salute/it-fse-support#248]
Buonasera,
dal file degli errori ricevuti riscontriamo il seguente errore:
{
  "id" : 24,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='067' attribute='classCode' actual = '' expected = 'ENC'>ClinicalDocument/component/structuredBody/component/section[ID='Dimissione']/entry/act/entryRelationship/encounter</error>"
}.
Dalle specifiche "CDA2_Verbale_Pronto_Soccorso_OK.xlsx" tale elemento risulta opzionale.
Inoltre la specifica del documento "casi di test VPS.docx" il caso d'uso (Caso di test 1) fa riferimento ad un esempio di CDA2 semplice in cui sono presenti le section e le entry obbligatorie da specifiche nazionali HL7 Italia. 
Abbiamo inviato un episodio semplice con esito trattamento "Dimissione a domicilio", pertanto la sezione enunciata nell'errore non è stata compilata.

Lo stesso errore è stato segnalato per la sezione relativa alle informazioni sul trasferimento Post Dimissione (opzionale)

Vorremmo chiarimenti in merito.
Attendiamo riscontro il prima possibile.
Cordiali saluti.

**Comment by vvarratta** [comment]
Buongiorno,
grazie per la celere risposta.
Dopo averla letta attentamente non ci spieghiamo il motivo per cui dovremmo necessariamente compilare la sezione entryRelationship/encounter dell'elemento entry/act quando trattasi di un episodio dimesso a domicilio, poichè è un'informazione incoerente con l'esito della dimissione. Pertanto vorremmo sapere se per ottenere l'accreditamento dovremo produrre un CDA che nella realtà non verrà mai generato.
Attendiamo riscontro il prima possibile.

**Comment by IStacchiotti** [comment]
Buongiorno.
E' richiesta quella determinata valorizzazione per come è stato pensato il test case e quindi per l'accreditamento deve essere riprodotto come viene riportato nell'excel con quelle specifiche valorizzazioni e come viene descritto nel word fornito.

**Comment by IStacchiotti** [comment]
Buon pomeriggio, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
