### ISSUE TITLE
Mancato Accreditamento

### ISSUE THREAD

**Issue by synlabsdn** [ministero-salute/it-fse-support#250]
Buongiorno, 
nella mail di mancato accreditamento mi è stato indicato che per alcuni test di KO non è possibile lasciare vuoto il campo traceid.
Alcuni risultati per testcase KO non restituiscono traceid.
Inserisco la stringa "undefined"?

**Comment by synlabsdn** [comment]
Buongiorno,
vi ringrazio per l'ulteriore segnalazione, ma ho bisogno di sapere se nei casi di KO(per cui non è presente il traceid) visto che il traceid è obbligatorio, se va bene che inserisco "undefined"
Saluti

**Comment by synlabsdn** [comment]
Buongiorno,
le riporto il test case 330 per radiologia in cui il sistema mi risponde senza traceid.

Chiamata:
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/12345678900112233

Request:
{"tipologiaStruttura":"Prevenzione","tipoDocumentoLivAlto":"REF","assettoOrganizzativo":"AD_PSC069","conservazioneANorma":"CONS^^^&2.16.840.1.113883.2.9.3.3.6.1.7&ISO","tipoAttivitaClinica":"ERP","identificativoSottomissione":"2.16.840.1.113883.2.9.2.150.4.3.12345678900112233","healthDataFormat":"CDA","mode":"ATTACHMENT","identificativoDoc":"SKIP_VALIDATION_2.16.840.1.113883.2.9.2.150.4.4^12345678900112233"}

Response:
{
    "type": "https://govway.org/handling-errors/400/InvalidRequestContent.html",
    "title": "InvalidRequestContent",
    "status": 400,
    "detail": "Request content not conform to API specification: Validation error(s) :\nbody.requestBody: Field 'identificativoRep' is required. (code: 1026)\nFrom: body.requestBody.<#/components/schemas/PublicationUpdateReqDTO>.<required>\n",
    "govway_id": "d756acdd-d513-11ed-93ec-005056ae54fa"
}

**Comment by masciamariotti** [comment]
Buongiorno,
come indicato sopra, riguardo il test 330, dovrebbe rieseguirlo valorizzando nel json il campo attiCliniciRegoleAccesso con il seguente valore non ammesso da Affinity Domain v2.4.1:
"attiCliniciRegoleAccesso":[
        "XXX"
    ]
e non eliminando dal json il campo identificativoRep, come erroneamente indicato nella checklist.
Potrebbe riprovare?

**Comment by synlabsdn** [comment]
Grazie per il riscontro
