### ISSUE TITLE
Errore 404 

### ISSUE THREAD

**Issue by synlabsdn** [ministero-salute/it-fse-support#252]
Buongiorno,
stiamo eseguendo il test case 302 per RSA.
Il sistema si aspetta 404 ma noi continuiamo ad avere risposta 200(OK).
Questa è la RequestBody che inviamo:
{"tipologiaStruttura":"Ospedale","tipoDocumentoLivAlto":"REF","assettoOrganizzativo":"AD_PSC043","dataInizioPrestazione":"20220509063000","conservazioneANorma":"CONS^^^&2.16.840.1.113883.2.9.3.3.6.1.7&ISO","tipoAttivitaClinica":"ERP","identificativoSottomissione":"2.16.840.1.113883.2.9.2.150.4.3.125123456789","healthDataFormat":"CDA","mode":"ATTACHMENT","identificativoDoc":"SKIP_VALIDATION_2.16.840.1.113883.2.9.2.150.4.4^125123456789","identificativoRep":"2.16.840.1.113883.2.9.2.150.4.5.125123456789"}

Il link a cui ci colleghiamo è il seguente in PUT:
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/125123456789XXX

Stiamo eseguendo quindi la sostituzione di un referto non esistente ma il sistema continua a restituirci ok con la relativa Response:
{
    "traceID": "c48a188f5ec35df0",
    "spanID": "c48a188f5ec35df0",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.151b9dd94e95204e3af2cb6a73fbbbea9fd3d2ba7cf17d819f24c51fff52b41c.3002fa7fbd^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Ci indicate dove sbagliamo?

**Comment by synlabsdn** [comment]
Buongiorno, ci sono aggiornamenti alla richiesta?

**Comment by IStacchiotti** [comment]
Buon pomeriggio, le confermiamo che la richiesta è stata presa in carico. Si rende necessaria una fix, le daremo evidenza non appena questa sarà rilasciata. Grazie.

**Comment by IStacchiotti** [comment]
Buonasera, Le confermiamo che è stata rilasciata una fix correttiva. La invitiamo cortesemente a riprovare, il problema non dovrebbe più presentarsi. Rimaniamo a completa disposizione in caso contrario. Grazie

**Comment by synlabsdn** [comment]
Buongiorno, con la fix che avete rilasciato il sistema restituisce correttamente errore 404.
Grazie
