### ISSUE TITLE
Errore in Pubblicazione Cerificato Vaccinale 

### ISSUE THREAD

**Issue by Fusarolia** [ministero-salute/it-fse-support#253]
Buongiorno
Provando a pubblicare il file SIGNED_CERT_VACC1.pdf messo a disposizione nella sezione pubblicazione ottengo il seguente errore:
title=InvalidRequestContent, status=400.0, detail=Request content not conform to API specification: Validation error(s) :
body.requestBody: Additional property 'tipologiaStruttura' is not allowed. (code: 1000)
From: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.<additionalProperties>
body.requestBody: Additional property 'tipoDocumentoLivAlto' is not allowed. (code: 1000)
From: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.<additionalProperties>
body.requestBody: Additional property 'assettoOrganizzativo' is not allowed. (code: 1000)
From: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.<additionalProperties>
body.requestBody: Additional property 'conservazioneANorma' is not allowed. (code: 1000)
From: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.<additionalProperties>
body.requestBody: Additional property 'tipoAttivitaClinica' is not allowed. (code: 1000)
From: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.<additionalProperties>
body.requestBody: Additional property 'identificativoSottomissione' is not allowed. (code: 1000)
From: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.<additionalProperties>
body.requestBody: Additional property 'identificativoDoc' is not allowed. (code: 1000)
From: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.<additionalProperties>
body.requestBody: Additional property 'identificativoRep' is not allowed. (code: 1000)
From: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.<additionalProperties>
body.requestBody: Additional property 'priorita' is not allowed. (code: 1000)
From: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.<additionalProperties>
body.requestBody: Field 'activity' is required. (code: 1026)
From: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.<required>
, govway_id=1b3c4125-d471-11ed-8570-005056ae7395,

Questi sono i parametri utilizzati come suggeriti dagli esempi:
{"healthDataFormat":"CDA","mode":"ATTACHMENT","tipologiaStruttura":"Territorio","tipoDocumentoLivAlto":"VAC","assettoOrganizzativo":"AD_PSC130","conservazioneANorma":"CONS^^^\u00262.16.840.1.113883.2.9.3.3.6.1.7\u0026ISO","tipoAttivitaClinica":"OBS","identificativoSottomissione":"2.16.840.1.113883.2.9.2.10.4.3.1234","identificativoDoc":"2.16.840.1.113883.2.9.2.10.4.4^030702.LCNLDE90L47H501Q.20220420112426.Q123E456","identificativoRep":"2.16.840.1.113883.2.9.2.10.4.5.1234","priorita":"false"}

Potete darmi qualche indicazione per errore restituito,
Grazie

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
