### ISSUE TITLE
Mancato Accreditamento .../component/section[ID='Motivo_Ricovero']/entry/observation/value

### ISSUE THREAD

**Issue by dinelliascom** [ministero-salute/it-fse-support#254]
Buongiorno,

abbiamo ricevuto il file json per il mancato accreditamento. In particolare per quanto riguarda la sezione specificata in oggetto
non abbiamo capito il motivo dei seguenti errori:
```
{
  "id" : 9,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='074' attribute='code' actual = '410.9' expected = '300.01'>ClinicalDocument/component/structuredBody/component/section[ID='Motivo_Ricovero']/entry/observation/value</error>"
}
```

```
{
  "id" : 6,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='074' attribute='code' actual = '' expected = '300.01'>ClinicalDocument/component/structuredBody/component/section[ID='Motivo_Ricovero']/entry/observation/value</error>"
}
```
volevamo conoscere per quale ragione dobbiamo specificare costantemente il valore '300.01' visto che in tutti i test case "OK" non è specificato che debba essere inserito tale valore nell'attributo "code" dell'elemento indicato dall'errore.

**Comment by IStacchiotti** [comment]
Buongiorno @dinelliascom, ci risulta che è riuscito a procedere nel processo di accreditamento (dovrebbe aver ricevuto una comunicazione il 21 aprile). Pertanto in assenza di conferma da parte sua che la richiesta è ancora bloccante, procederemo alla chiusura del presente. Si può sempre procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto. Grazie.

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
