### ISSUE TITLE
Mancato Errore 404

### ISSUE THREAD

**Issue by synlabsdn** [ministero-salute/it-fse-support#255]
Buongiorno, 
per il testcase 238 per la radiologia continuiamo ad avere invece che 404 (quindi KO), la risposta 200 anche se stiamo eseguendo la sostituzione di un documento non precedentemente caricato.
Di seguito la RequestBody e la Response:

Chiamata: https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/12345678900112233

RequestBody:
{"tipologiaStruttura":"Prevenzione","tipoDocumentoLivAlto":"REF","assettoOrganizzativo":"AD_PSC069","dataInizioPrestazione":"20220331112426","conservazioneANorma":"CONS^^^&2.16.840.1.113883.2.9.3.3.6.1.7&ISO","tipoAttivitaClinica":"ERP","identificativoSottomissione":"2.16.840.1.113883.2.9.2.150.4.3.12345678900112233","healthDataFormat":"CDA","mode":"ATTACHMENT","identificativoDoc":"SKIP_VALIDATION_2.16.840.1.113883.2.9.2.150.4.4^12345678900112233","identificativoRep":"2.16.840.1.113883.2.9.2.150.4.5.12345678900112233"}

Response:
{
    "traceID": "6070a86c90cab5ff",
    "spanID": "6070a86c90cab5ff",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.c005f76b6babf7ce30307ca05a4221726c471b516f8d9c172530efdbf799712c.5d56842c12^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

**Comment by synlabsdn** [comment]
Buongiorno, ci sono aggiornamenti alla richiesta?

**Comment by IStacchiotti** [comment]
Buon pomeriggio, le confermiamo che la richiesta è stata presa in carico. Si rende necessaria una fix, le daremo evidenza non appena questa sarà rilasciata. Grazie.

**Comment by IStacchiotti** [comment]
Buonasera, Le confermiamo che è stata rilasciata una fix correttiva. La invitiamo cortesemente a riprovare, il problema non dovrebbe più presentarsi. Rimaniamo a completa disposizione in caso contrario. Grazie

**Comment by synlabsdn** [comment]
Buongiorno,
con la fix correttiva il sistema restituisce l'errore indicato.
Grazie
