### ISSUE TITLE
workflowInstanceId non presente

### ISSUE THREAD

**Issue by synlabsdn** [ministero-salute/it-fse-support#256]
Buongiorno,
nella mail mancato accreditamento che ci è stata inviata mi si richiede per alcuni testcase di KO di inserire in modo obbligatorio la colonna I (WORKFLOWINSTANCEID).
Visto che per i test case di KO non ho questo valore inserisco UNKNOWN_WORKFLOW_ID?
Oppure c'è un errore nella valutazione dei testcase e posso tranquillamente lasciare il carattere vuoto(blank) come indicato nella documentazione?
Attendo riscontro a riguardo
Grazie

**Comment by masciamariotti** [comment]
Buongiorno,
potrebbe cortesemente indicare quali sono gli ID dei testcase per cui riscontra questa problematica?
Grazie.

**Comment by synlabsdn** [comment]
Buongiorno, ci sono aggiornamenti a riguardo?

**Comment by IStacchiotti** [comment]
Buongiorno, ci risulta che è stata inviata una mail lo scorso venerdì per comunicare il KO su una precedente versione della checklist. Riceverà aggiornamenti quanto prima via email con gli esiti sui controlli relativi all'ultima versione, committata sabato 15 aprile.

**Comment by synlabsdn** [comment]
Buongiorno,
grazie alle fix rilasciate al GATEWAY abbiamo degli aggiornamenti per quanto riguarda la checklist e il file data.json.
Possiamo pubblicare gli aggiornamenti o dobbiamo aspettare il resoconto degli esiti della versione pubblicata sabato 15 aprile?

**Comment by IStacchiotti** [comment]
Buonasera @synlabsdn, le abbiamo risposto nel ticket #262, dove può continuare a scrivere nel caso in cui le dovesse servire ulteriore supporto. Chiudiamo invece il presente in quanto duplicato. Grazie
