### ISSUE TITLE
Domanda accreditamento nuovo tipo di documento

### ISSUE THREAD

**Issue by cap-nic** [ministero-salute/it-fse-support#257]
Buongiorno,
per accreditarci su di un nuovo tipo di documento occorre ricompilare il form di richiesta accreditamento anche se verrà gestito dallo stesso applicativo che è già accreditato per un altro tipo di documento?

Grazie.

**Comment by IStacchiotti** [comment]
Buonasera, nel caso in cui non avesse già avuto comunicazioni su altri canali la informiamo che il form dovrebbe essere compilato con tutti i CDA - Servizi che il software gestisce. Nel caso in cui si sia fatta, erroneamente, una richiesta parziale è necessario sottomettere una nuova richiesta.

**Comment by cap-nic** [comment]
Buongiorno,
la richiesta è stata fatta correttamente al tempo, in accordo con quanto specificato nel `Piano di adeguamento degli applicativi a FSE 2.0` inviatoci, potrebbe essere però necessario in futuro dover aggiungere altri tipi di documenti con l'integrazione delle strutture private, nel qual caso provvederemo a sottomettere una nuova richiesta. Grazie

**Comment by IStacchiotti** [comment]
Procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
