### ISSUE TITLE
Errore in pubblicazione "Il CDA non risulta validato"

### ISSUE THREAD

**Issue by domenico-capezzuto** [ministero-salute/it-fse-support#258]
Buongiorno,

non riesco a pubblicare un documento VPS appena validato.

Riporto la request:
```
{
	"traceID": "b4066e10bdc0a72e",
	"spanID": "b4066e10bdc0a72e",
	"type": "/msg/cda-match",
	"title": "Errore in fase di recupero dell'esito della verifica.",
	"detail": "Il CDA non risulta validato",
	"status": 400,
	"instance": "/cda-validation"
}
```

e la response del gateway:
```
{
	"mode": "ATTACHMENT",
	"workflowInstanceId": "2.16.840.1.113883.2.9.2.10.4.4.562b1412a3c74d678dd244e91f5e4ed9de46354e702fe6d86ab46a8eb8879e58.8783865909^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
	"tipologiaStruttura": "Ospedale",
	"identificativoDoc": "95eafb82-ceb4-4b90-8ed9-bc8ec7ea6c1e",
	"identificativoRep": "2.16.840.1.113883.2.9.2.10.4.5.205",
	"tipoDocumentoLivAlto": "VRB",
	"assettoOrganizzativo": "AD_PSC106",
	"tipoAttivitaClinica": "PHR",
	"identificativoSottomissione": "2.16.840.1.113883.2.9.2.10.4.3.205"
}
```

Per completezza nell'ultimo tentativo ho incluso il campo `workflowInstanceId`,
contenente il risultato della precedente validazione,
ma ho provato anche senza valorizzarlo ottenendo però il medesimo risultato.

Grazie,
Domenico

**Comment by IStacchiotti** [comment]
Buongiorno.
Il cda2 non risulta valido poiché non è corretto il formato dell'attributo value dell'elemento effectiveTime. Si chiede di inserire il formato corretto presente anche nella guida pubblicata su HL7 Italia. La CONF di riferimento è la seguente:
CONF-VPS-10: L'elemento `<ClinicalDocument>/<effectiveTime>` DEVE riportare
l'attributo @value valorizzato nel formato [YYYYMMDDHHMMSS+|-ZZZZ].
E' possibile trovarla a pag 26 della guida implementativa del Verbale di Pronto Soccorso v1.1.1

**Comment by IStacchiotti** [comment]
Buongiorno, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
