### ISSUE TITLE
Richiesta informazioni su come valorizzare il claims subject_role

### ISSUE THREAD

**Issue by andreasantori** [ministero-salute/it-fse-support#259]
Buongiorno,
la creazione del JWT-Signature prevede un claims chiamato subject_role da valorizzare con una costante definita nella tabella RUOLO.
Nell'ambito di una specialistica ambulatoriale per malati cronici ove è il medico specialista che produce il referto, quale sarebbe il valore corretto da impostare?

AAS	        Personale di assistenza ad alta specializzazione	Medico / Dirigente sanitario
DRS	        Dirigente sanitario	Medico / Dirigente sanitario
MRP	Medico Rete di Patologia	Medico Rete di Patologia

mi viene da dire uno dei tre presi da tale tabella.....

**Comment by andreasantori** [comment]
Buongiorno,
vi vorrei riportare in evidenza il ticket, ad oggi non abbiamo avuto alcun tipo di riscontro.
Grazie.

**Comment by Ser-ena** [comment]
Buongiorno, se la richiesta è ancora valida, il valore da utilizzare nella casistica indicata potrebbe essere  AAS poiché identifica personale specializzato

**Comment by andreasantori** [comment]
Grazie per l'informazione.
Chiudiamo la segnalazione
