### ISSUE TITLE
Errore pull su Windows

### ISSUE THREAD

**Issue by EbitFSE** [ministero-salute/it-fse-support#260]
Buongiorno, da alcuni giorni non riusciamo più a fare né fetch, né merge, né a rieseguire il clone del repository, pertanto non possiamo più aggiornare i file per l'accreditamento. Sembra che a dare il problema sia una cartella contenente il punto finale (non consentito su windows). 
![image](https://user-images.githubusercontent.com/124879055/231101175-dce90a79-e4bc-4c72-930a-909dfe75fbed.png)
Dovrebbero essere bloccate tutte le attività dei vari fornitori o esiste un workaround?
Grazie
Saluti

**Comment by EbitFSE** [comment]
Buongiorno, dovremmo aver risolto da soli, rimaniamo in attesa del merge e della verifica sui casi inviati.
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, grazie per il feedback. La presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
