### ISSUE TITLE
TestCase 356

### ISSUE THREAD

**Issue by synlabsdn** [ministero-salute/it-fse-support#262]
Buongiorno,
stiamo eseguendo il Test Case di aggiornamento metadati:
**Chiamata**:
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/12345678900456/metadata

**Request**:
{"tipologiaStruttura":"Prevenzione","attiCliniciRegoleAccesso":["P99"],"assettoOrganizzativo":"AD_PSC069","dataInizioPrestazione":"20220330112426","dataFinePrestazione":"20220330112426","conservazioneANorma":"CONS^^^&2.16.840.1.113883.2.9.3.3.6.1.7&ISO","tipoAttivitaClinica":"ERP","identificativoSottomissione": "2.16.840.1.113883.2.9.2.150.4.3.12345678900456","tipoDocumentoLivAlto":""
}

**Response**:
{
    "type": "https://govway.org/handling-errors/400/InvalidRequestContent.html",
    "title": "InvalidRequestContent",
    "status": 400,
    "detail": "Request content not conform to API specification: Validation error(s) :\nbody.tipoDocumentoLivAlto: Value '' is not defined in the schema. (code: 1006)\nFrom: body.tipoDocumentoLivAlto.<enum>\n",
    "govway_id": "3718273b-d84b-11ed-93ec-005056ae54fa"
}

Come si evince dalla Request e Response abbiamo il codice di errore 400 ma non ci viene fornito il traceid.
E' stata provata anche la soluzione eliminando del tutto il campo "tipoDocumentoLivAlto" ma abbiamo lo stesso risultato
Come dobbiamo procedere?
Grazie

**Comment by masciamariotti** [comment]
Buon pomeriggio,
dovrebbe rieseguire il test valorizzando nel json il campo attiCliniciRegoleAccesso con il seguente valore non ammesso da Affinity Domain v2.4.1:
"attiCliniciRegoleAccesso":[
        "XXX"
    ]
e non eliminare dal json il campo identificativoRep, come erroneamente indicato nella checklist.
Grazie

**Comment by synlabsdn** [comment]
Buongiorno,
ma il testcase è completamente diverso da quello che lei mi indica.

Viene richiamato il servizio di Aggiornamento Metadati "https://<HOST>:<PORT>/v<major>/documents/<identificativoDocUpdate>/metadata" al fine di testare l'aggiornamento dei metadati con errore a causa di una valorizzazione dei metadati non corretta (status code 400).

Per  la richiesta è necessario:
▪per l'utente che è in grado di procedere in autonomia, comporre i metadati della RequestBody conformemente a quanto descritto in https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway;
▪per l'utente che non è in grado di procedere in autonomia, comporre i metadati contenente la RequestBody utilizzando il json "RAD - Caso di Test 4 - Update" presente al path "https://github.com/ministero-salute/it-fse-accreditamento".

Per tutti i fornitori è necessario eliminare dal json il campo tipoDocumentoLivAlto.

**Comment by masciamariotti** [comment]
Buongiorno,
sì siamo a conoscenza delle incongruenze, ma come già indicato, purtroppo, il test indicato nella checklist era errato e necessita di un aggiornamento.
Quanto prima ne verrà pubblicata una nuova con questa correzione.

**Comment by synlabsdn** [comment]
Buongiorno,
comprendo che ci sono incongruenze sul file delle checklist, ma per testare questo testcase cosa devo fare?
Se il testcase mi restituisce il codice di errore 400(come richiesto) e non il traceid come risolvo?
Cosa inserisco nel campo traceid?

**Comment by IStacchiotti** [comment]
Buon pomeriggio @synlabsdn, ottiene errore 400 anche valorizzando nel json il campo attiCliniciRegoleAccesso con il valore "XXX"? Questo test può essere svolto in sostituzione dell'eliminazione dal json del campo identificativoRep (erroneamente indicato nella checklist).
Grazie

**Comment by synlabsdn** [comment]
Buongiorno, 
eseguendo il test in questo modo mi viene fornito l'errore 400 ma nella risposta viene compilato il traceid correttamente.
Posso già aggiornare i file data.json e checklist o attendo il resoconto dell'accreditamento?

**Comment by IStacchiotti** [comment]
Buonasera @synlabsdn, le confermiamo che può già procedere con la correzione tramite nuova commit. Riceverà gli esiti in merito al solo servizio di validazione, essendo stato posticipato l'accreditamento per il servizio di pubblicazione (come da [direttive ](https://developersitalia.slack.com/archives/C03RDT88FSM/p1681742586275089?thread_ts=1681495556.656929&cid=C03RDT88FSM) su Slack).

**Comment by IStacchiotti** [comment]
Buongiorno, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
