### ISSUE TITLE
Accreditamento - Errore campi OPZIONALI

### ISSUE THREAD

**Issue by rangeletti** [ministero-salute/it-fse-support#263]
Buonasera,
Avrei necessità di un chiarimento per i casi di test così descritti nei rispettivi file Word "**Il caso d’uso fa riferimento ad un esempio di CDA2 semplice in cui sono presenti le section e le entry obbligatorie da specifiche nazionali HL7 Italia**.” 
Rispetto a questi test quali sono i campi Obbligatori da mettere nel CDA? 
1 - Quelli definiti da specifiche HL7 Italia?
2 - Quelli specificati nell'excel relativo (sia OBBLIGATORI che OPZIONALI)?
Per il caso 2, avrei altre due domande:
2.1 -  Se  la sezione è opzionale e i sotto campi obbligatori (ovviamente sono obbligatori se presente la sezione, in base al caso d'uso), come in questo caso, deve essere comunque inserita la sezione nel CDA, anche se non obbligatoria da specifiche HL7 italia?

![image](https://user-images.githubusercontent.com/125476691/231235858-7978853e-f944-4579-896a-ec2629a2f637.png)

2.2 Inoltre, in riferimento a quest ultimo caso, relativo ad un verbale di PS in cui è stata effettuata la dimissione a domicilio, quindi la section in questione NON può essere presente nel CDA, in quanto, come descritto nella descrizione riguarda il caso di RICOVERO, sia il test di accreditamento che il tool GTW-validator segnalano l'errore di mancanza della section in oggetto.

Vorrei precisare, in questo caso che la section è opzionale proprio perchè dipende dai casi d'uso di PS che possono verificarsi nella realtà:
- Il paziente viene dimesso a domicilio
- il paziente viene ricoverato
- il paziente è deceduto in PS
Questi tre casi sono mutuamente esclusivi nella realtà così come le section nel CDA.
Chiedere la presenza contemporanea delle 3 section in uno stesso CDA equivale a chiedere di simulare un caso che nella realtà non può verificarsi e che magari applicativamente non viene gestito.

Si deve segnalare quindi anche il caso 1 di test come "Non applicabile"?
In tal caso non si avrebbe alcun caso di test OK applicabile.

Segnalo inoltre che la validazione tramite GW viene superata.

Resto in attesa di un celere riscontro,
cordiali saluti,
Rachele

**Comment by rangeletti** [comment]
Buongiorno, 
sarebbe possibile avere un riscontro? La seguente problematica sta bloccando il processo di accreditamento, mettendoci in difficoltà con i piani di aggiornamento.

Grazie mille,
un saluto,
Rachele

**Comment by IStacchiotti** [comment]
Buongiorno.
Negli excel forniti, ogni caso di test ha determinate sezioni che devono essere inserite per riprodurre il caso di test pensato.
Il caso di test 1 è quello che comprende solo le sezioni obbligatorie da specifiche e tutti gli elementi riportati nell'excel di quelle sezioni devono essere inseriti nel cda2.
I casi di test 2, 3 e 4 invece prevedono sia le sezioni obbligatorie da specifiche che le sezioni opzionali ma che devono essere inserite per quei casi di test, poiché completerebbero il contenuto informativo descritto anche nel word per quello specifico test case, con tutti gli elementi riportati nell'excel.
Per cui se per quel determinato caso di test pensato con tutte quelle caratteristiche inserite nell'excel e con quelle valorizzazioni, non si è in grado di riprodurlo fedelmente, significa che bisognerà inserire nella colonna applicabilità NO. Ovviamente la validazione lato GW avviene poiché vengono non si hanno errori ne sintattici ne semantici ne terminologici però non si riproduce il caso di test in esame come richiesto e perciò non si supererà la fase di accreditamento in validazione.

**Comment by rangeletti** [comment]
Buongiorno,
la ringrazio per la risposta. Procediamo, come indicato, ad inserire nella colonna applicabilità "NO".
Le chiedo a questo punto: è un problema non aver alcun caso OK applicabile?
Vorrei inoltre segnalare che NON è vero quanto da lei indicato "_Il caso di test 1 è quello che comprende solo le sezioni obbligatorie da specifiche_".  Questo è quanto riportato nel documento word, che descrive  i test, ma non rispecchia quanto richiesto nell'excel.
Inoltre, per poter verificare correttamente e realisticamente le 3 modalità di dimissione, che corrispondo a section opzionali presenti nel file excel, sarebbero dovuti essere creati 3 casi di test OK, specificando per ognuno la modalità di dimissione richiesta per il caso specifico (ricovero, a domicilio o deceduto).

**Comment by masciamariotti** [comment]
Buonasera,
per poter chiarire la problematica rispetto al non avere alcun caso OK applicabile, le chiederemmo di allegare qui il caso più completo che riuscite a coprire, indicando esattamente quali tag a partire dal test 1.

**Comment by IStacchiotti** [comment]
Buonasera Rachele, procediamo alla chiusura del ticket, dal momento che alla presente è stato fatto seguito via email. Si può procedere con l'apertura di un nuovo ticket nel caso fosse necessario ulteriore supporto. Grazie
