### ISSUE TITLE
Accreditamento - errori su mancanza campi opzionali via GTW-CERTIFIER

### ISSUE THREAD

**Issue by dmonti76** [ministero-salute/it-fse-support#264]
Buonasera,
oggi abbiamo utilizzato il tool GTW-CERTIFIER per testare i casi di test 1 OK per LDO, VPS, RSA e RAD e abbiamo ottenuto alcuni errori relativi alla mancanza di campi/attributi che, però, non sono presenti perché parte di sottosezioni opzionali.

Faccio un esempio relativo a RSA (Test 147):
 _<error code="009" attribute="classCode expected = "Valorizzare con uno dei seguenti valori: PROC actual = "">ClinicalDocument/component/structuredBody/component/section[ID='Prestazioni']/entry/act/entryRelationship/procedure</error>_

La questione non è aver dimenticato di inserire la stringa fissa PROC, è che la componente padre **ClinicalDocument/component/structuredBody/component/section[@ID=Prestazioni]/entry/act/entryRelationship**
non è gestita in quanto l'informazione veicolata è marcata come OPZIONALE. 

A questo punto, vorremmo un chiarimento sui Test 1:
- se anche i campi opzionali siano da considerarsi obbligatori e, se possibile, il razionale di averli indicati come opzionali (n.b. come d'altra parte sono da specifiche HL7 Italia)
- se questi "errori" del GTW-CERTIFIER sono falsi positivi e non verranno considerati in fase di accreditamento 

Grazie, 
cordiali saluti

**Comment by IStacchiotti** [comment]
Buonasera, in merito alla prima affermazione, il caso di test 1 per tutte le tipologie documentali prevede solamente sezioni obbligatorie da specifiche HL7 Italia. Quindi nel caso di test 1 non vi sono sezioni opzionali.
L'errore riportato è relativo alla sintassi errata dell'attributo ID della sezione poiché è un elemento opzionale da POCD ma per completezza di informazione è stato inserito però per passare la validazione sintattica deve essere scritto correttamente ovvero in maiuscolo. Di seguito riporto la componente padre a cui fa riferimento l'errore e che è scritto in maniera sbagliata:
[`ClinicalDocument/component/structuredBody/component/section[@id=Prestazioni]/entry/act/entryRelationship`], dove l'ID è scritto minuscolo.
Per quanto riguarda l'ultimo quesito, il caso di test 1 prevede sola,mente le sezioni e le entry obbligatorie, quindi gli elementi presenti nell'excel, fornito per tutte le tipologie documentali, devono essere inseriti per rispecchiare il caso di test pensato.

**Comment by dmonti76** [comment]
Buonasera,

La ringrazio per la risposta ma credo ci sia un malinteso di fondo.

Provo a fare una domanda secca:
- nel file di checklist CDA2_Referto_Specialistica_Ambulatoriale_OK.xlsx, tab RSA - Caso di Test 1, il tag di cui allo screenshot è indicato come OPZIONALE
![image](https://user-images.githubusercontent.com/65120663/231522602-40c7a9c1-da94-4740-878a-7bdd4cc27ebd.png)

Per essere accreditati il tag (e tutto il suo contenuto OBBLIGATORIO e OPZIONALE) deve essere incluso o no?

Grazie mille

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che devono essere inclusi per il corretto svolgimento del test tutti gli elementi che, anche se sono opzionali da guida, per il nostro caso d’uso sono necessari per completezza di informazione. Bisogna fare riferimento all’excel fornito con le giuste valorizzazioni dei campi da inserire. Nel caso particolare in cui i dati non siano disponibili a sistema oppure nel caso in cui non si possa completare il test case correttamente, è possibile indicare NO nell’apposita colonna "Applicabilità", avendo cura di giustificarlo opportunamente nella colonna "razionale di applicabilità". Grazie

**Comment by dmonti76** [comment]
Grazie mille, chiudo l'issue
