### ISSUE TITLE
Output gtw-certifier

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#265]
Salve.
Ho utilizzato il gtw-certifier e ho questo output:

[TEST SUPERATI]
Test case OK con ids: [6, 11, 12, 24, 147]
[TEST NON VERIFICABILI]
Test case KO con ids: [29, 31, 32, 35, 37, 39, 40, 43, 64, 65, 66, 67, 68, 69, 70, 73, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 92, 93, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 137, 139, 140, 142, 143, 144, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 168, 169]
[TEST FALLITI]
Test case KO con ids: []

come devo considerare questi risultati?
Grazie

**Comment by masciamariotti** [comment]
Buonasera Alessandro,
questo risultato sta ad indicare che gli unici casi di test che il tool poteva verificare (come indicato nella relativa pagina [Github](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/gtw-certifier)) sono stati superati.

**Comment by alessandropassamonti** [comment]
Buonasera,
per i casi KO non ci sono tool?
Ci potrebbero essere errori dai casi KO o quelli che ho ricevuto oggi dal sistema di accreditamento sono gli unici riscontrati? 
Lo chiedo perché tra la pull-request e la verifica passa veramente molto molto tempo.
Grazie

**Comment by masciamariotti** [comment]
Purtroppo non c'è modo di verificare i casi KO offline.
Gli errori che ha ricevuto (ed eventualmente riceverà) sono tutti quelli riscontrati.

**Comment by alessandropassamonti** [comment]
Grazie, per essere più preciso: 
I casi KO sono stati controllati?
Perché se lo sono stati e il  gtw-certifier non ha prodotto errori posso attendermi che l'accrediatamento avrà esito positivo con la nuova pull-request?
Grazie

**Comment by masciamariotti** [comment]
Il tool lavorando offline offre delle funzionalità limitate. Non avendo ricevuto alcun KO dal gtw-certifier le confermiamo che può risottomettere la richiesta di accreditamento.

**Comment by alessandropassamonti** [comment]
grazie mille
