### ISSUE TITLE
Chiarimenti sul processo di accreditamento

### ISSUE THREAD

**Issue by davidecasiraghi** [ministero-salute/it-fse-support#267]
Buongiorno,
avrei alcune domande riguardo al processo di accreditamento:
1. Dopo la richiesta di accreditamento è possibile modificare i valori di application_id, application_vendor o application_version del software accreditato?
2. Il valore da indicare in application_version è la major release, che viene modificata solo in caso di modifiche sostanziali al programma, o la versione specifica che viene aggiornata ad ogni minima modifica?
3. Le versioni successive a quella accreditata come vengono gestite? Si ritengono accreditate o deve essere rifatto l'accreditamento?
4. gli attributi ID dei tag <section> del CDA indicati nei file excel che descrivono i casi di test (esempio ClinicalDocument/component/structuredBody/component/section[@ID="Esame_eseguito"]) sono da utilizzare solo per il processo di accreditamento o vanno mantenuti anche nei CDA rilasciati in produzione?

Grazie e saluti

**Comment by IStacchiotti** [comment]
Rispondiamo di seguito per il primo e per l'ultimo punto. Per gli altri seguiranno ulteriori aggiornamenti.

"Buongiorno,
avrei alcune domande riguardo al processo di accreditamento:

1. Dopo la richiesta di accreditamento è possibile modificare i valori di application_id, application_vendor o application_version del software accreditato? **> Non è possibile modificare la tripletta in seguito. Essa infatti individua univocamente il software nel processo di accreditamento.**
2. ....
3. ....
4. gli attributi ID dei tag
del CDA indicati nei file excel che descrivono i casi di test (esempio `ClinicalDocument/component/structuredBody/component/section[@id="Esame_eseguito"]`) sono da utilizzare solo per il processo di accreditamento o vanno mantenuti anche nei CDA rilasciati in produzione? **> Confermiamo che gli attributi ID presenti nel tag della sezione verranno mantenuti anche nei CDA rilasciati in produzione poiché consentono una maggiore completezza di informazione.**


Grazie e saluti"

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
