### ISSUE TITLE
requisiti memoria it-fse-container-full

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#268]
Buongiorno, 
provando a installare it-fse-container-full abbiamo rilevato che solo l'avvio dei container richiede 27 GB di RAM invece dei 16 indicati nella documentazione.

E' corretto? 
Ci sono stime sulla crescita dell'occupazione di memoria quando il gateway viene utilizzato per validazioni e pubblicazioni?

Grazie

**Comment by IStacchiotti** [comment]
Buonasera,
per il container full sono consigliati 32 GB di RAM rispetto ai 16 necessari per il container lite. Abbiamo aggiornato la documentazione.

Per quanto riguarda l'occupazione di memoria:
* La RAM si assesta dopo la prima validazione e pubblicazione,
* Lo Storage cresce di circa 25KB per ogni validazione e di circa 40KB per ogni pubblicazione.

**Comment by ponsilva** [comment]
Grazie per le precisazioni
