### ISSUE TITLE
Merge"Revisione accreditamento A1#111EXPRIVIA000 - EXPRIVIA - AURORA - 2 / ERIS -5 #221"

### ISSUE THREAD

**Issue by rangeletti** [ministero-salute/it-fse-support#269]
Buongiorno la scorsa settimana abbiamo committato un aggiornamento dei file relativi alla richiesta di accreditamento per i nostri prodotti Eris ed Aurora che non risultano ancora visibili nella main.
Vorremmo sapere se dobbiamo fare altro oltre alla richiesta di merge e quanto occorre affinché vengano recepiti i nostri aggiornamenti.
Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, ci risulta che le sono state inviate comunicazioni via email riguardo l'accreditamento per gli applicativi indicati e che il processo sta proseguendo. La invitiamo a continuare il presente thread nel caso in cui vi necessiti supporto, in caso contrario procederemo alla chiusura del presente. Specifichiamo che sarà sempre possibile procedere con l'apertura di un nuovo ticket.

**Comment by rangeletti** [comment]
Salve,

purtroppo il merge ancora non è stato effettuato, e sul branch nazionale vedo le modifiche risalenti a 2 mesi fa quando la pull request di cui si fa riferimento nel presente issue è stata aperta successivamente

![image](https://user-images.githubusercontent.com/125476691/235969470-7760faf7-6bc8-492b-bf17-efb20093ae5c.png)

**Comment by rangeletti** [comment]
Salve,
purtroppo il merge ancora non è stato effettuato, e sul branch nazionale vedo le modifiche risalenti a 2 mesi fa quando la pull request di cui si fa riferimento nel presente issue è stata aperta successivamente
***@***.***
Sarebbe possibile un riscontro?

Grazie mille,
Rachele

Rachele Angeletti
Functional Analyst (DFEH-MS-PS)
Business Unit Healthcare
email: ***@***.******@***.***>
M. +39 3458001208
***@***.***
Exprivia S.p.A.
Via Ludovico Lazzaro Zamenhof, 200 - 36100 Vicenza (VI)
T. 0444 564114-201
F. 0444 566686
www.exprivia.it<http://www.exprivia.it/>
Exprivia Group

Da: IStacchiotti ***@***.***>
Inviato: mercoledì 3 maggio 2023 17:33
A: ministero-salute/it-fse-support ***@***.***>
Cc: Angeletti Rachele ***@***.***>; Author ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Merge"Revisione accreditamento A1#111EXPRIVIA000 - EXPRIVIA - AURORA - 2 / ERIS -5 #221" (Issue #269)


Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.

—
Reply to this email directly, view it on GitHub<https://eu-central-1.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL21pbmlzdGVyby1zYWx1dGUvaXQtZnNlLXN1cHBvcnQvaXNzdWVzLzI2OSNpc3N1ZWNvbW1lbnQtMTUzMzI1NjU3Ng==&p=m&i=NjIyNzcxMjZkNmU3MDExMGZmNDM4NzMw&t=N1dDVjhPc2ZhbXRIY2xPWDFDNkxDdzhnL2RyVHBtRTJOc1R4Vk05VzdWbz0=&h=317dc8e42ed947d2b913bfc40318913b&s=AVNPUEhUT0NFTkNSWVBUSVY6K0T94M0wPyDMzKN9BocAHrXlbSFJ3THbbw-AzQ3TEw>, or unsubscribe<https://eu-central-1.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL25vdGlmaWNhdGlvbnMvdW5zdWJzY3JpYmUtYXV0aC9BNTVKNlVZUUxKQlhOQU5SRjdHUDVPVFhFSjNEM0FOQ05GU002QUFBQUFBVzZMSkc0SQ==&p=m&i=NjIyNzcxMjZkNmU3MDExMGZmNDM4NzMw&t=TSttVkQyZFJMT2JWOHY0SEF2eEdpODlEQUorNUthUXNKcGpVemNjYklmcz0=&h=317dc8e42ed947d2b913bfc40318913b&s=AVNPUEhUT0NFTkNSWVBUSVY6K0T94M0wPyDMzKN9BocAHrXlbSFJ3THbbw-AzQ3TEw>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

Internet Email Confidentiality Footer ** La presente comunicazione, con le informazioni in essa contenute e ogni documento o file allegato, è rivolta unicamente alla/e persona/e cui è indirizzata ed alle altre da questa autorizzata/e a riceverla. Se non siete i destinatari/autorizzati siete avvisati che qualsiasi azione, copia, comunicazione, divulgazione o simili basate sul contenuto di tali informazioni è vietata e potrebbe essere contro la legge (art. 616 C.P., Regolamento UE 2016/679 (GDPR) e D.Lgs n. 196/2003 Codice in materia di protezione dei dati personali). Se avete ricevuto questa comunicazione per errore, vi preghiamo di darne immediata notizia al mittente e di distruggere il messaggio originale e ogni file allegato senza farne copia alcuna o riprodurne in alcun modo il contenuto. Titolare del trattamento dei dati personali, eventualmente contenuti nella comunicazione, è Exprivia SpA - Partita IVA: 09320730154– ai sensi del GDPR, a cui può rivolgersi per reclami o per esercitare i diritti degli interessati artt. 15-22 del GDPR. Al link seguente e' disponibile l'informativa Privacy: https://www.exprivia.it/it/132/cookie-and-privacy-policy.php This communication, with the information contained therein and any attached document or file, is meant solely for the person(s) to whom it is addressed and others authorised by the latter to receive it. If you are not one of the recipients or those authorised, you are advised that any action, copying, communication, disclosure or similar based on the content of such information is prohibited and could be against the law (Article 616 of the Penal Code, EU Regulation 2016/679 (GDPR) and Legislative Decree no. 196/2003 Code regarding the protection of personal data). If you have received this communication in error, please notify the sender immediately and destroy the original message and any attached file, without copying or reproducing any of its contents in any way. The Data Controller, contained in the communication where appropriate, is Exprivia SpA - VAT number: 09320730154 - pursuant to the GDPR, which you can contact for complaints or to exercise the rights of the interested parties Articles 15-22 of the GDPR. The Privacy Policy is available at the following link: https://www.exprivia.it/it/132/cookie-and-privacy-policy.php
