### ISSUE TITLE
Errore "connection refused" per CDA RAD in validazione

### ISSUE THREAD

**Issue by MarcoKnezevichInsiel** [ministero-salute/it-fse-support#27]
Buongiorno,

provando a inviare il referto di radiologia (**RAD_icd9.xml.txt**) riceviamo il seguente errore di **Connection refused** :
`{
  "message": null,
  "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException",
  "responseGatewayDto": {
    "traceID": "3adeb0e2e3e36277",
    "spanID": "3adeb0e2e3e36277",
    "workflowInstanceId": null,
    "type": "/msg/connection-refused",
   "title": "Connection refused",
    "status": 500,
    "detail": "Connection refused",
    "instance": "/msg/connection-refused",
    "govwayId": null,
    "warning": null
  }
}`
per la seguente richiesta:

`{ "validationDto": { "healthDataFormat": "CDA", "mode": "ATTACHMENT", "activity": "VALIDATION" }, "claimsDto": { "sub": "PRVNSL48A01L483P", "subject_role": "AAS", "purpose_of_use": "TREATMENT", "iss": "060000000000XX", "locality": "Regione Friuli Venezia Giulia", "subject_organization_id": "060", "subject_organization": "Regione Friuli Venezia Giulia", "patient_consent": true, "action_id": "CREATE", "resource_hl7_type": "('68604-8^^2.16.840.1.113883.6.1')", "person_id": "PRVNSL48A01L483P^^^&2.16.840.1.113883.2.9.4.3.2&ISO" } }`

La cosa strana è che inviando lo stesso CDA e sostituendo le diagnosi ICD9CM (esistenti e censite) con le diagnosi del nomenclatore regionale del Friuli Venezia Giulia (in allegato il file **RAD_nom_fvg.xml.txt**) viene restituito il `workflowInstanceId `con dei warning:

`{
  "traceID": "fa55695cc9fe568a",
  "spanID": "fa55695cc9fe568a",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.78a12a28f573392244a9e1569b63f8120c930fce60840961896e9f2d1c2dd01e.1b69b1d807^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "type": null,
  "title": null,
  "status": null,
  "detail": null,
  "instance": null,
  "govwayId": null,
  "warning": "[W005 | Sezione Esami eseguiti durante il ricovero: l'entry/act/code può essere valorizzato secondo i sistemi di codifica\n\t\t\tLOINC @codeSystem='2.16.840.1.113883.6.1'\n\t\t\tICD-9-CM @codeSystem='2.16.840.1.113883.6.103'],[W005 | Sezione Esami eseguiti durante il ricovero: l'entry/act/code può essere valorizzato secondo i sistemi di codifica\n\t\t\tLOINC @codeSystem='2.16.840.1.113883.6.1'\n\t\t\tICD-9-CM @codeSystem='2.16.840.1.113883.6.103']."
}`

[RAD_icd9.xml.txt](https://github.com/ministero-salute/it-fse-support/files/9837185/RAD_icd9.xml.txt)
[RAD_nom_fvg.xml.txt](https://github.com/ministero-salute/it-fse-support/files/9837190/RAD_nom_fvg.xml.txt)

**Comment by zukka77** [comment]
Ciao, il file xml icd9cm non è ben formato:
```xml
 <code code="88.71 
  displayName=""DIAGNOSTICA ECOGRAFICA DEL CAPO E DEL COLLO" 
  codeSystem="2.16.840.1.113883.6.103" 
  codeSystemName="ICD-9-CM">
```
ci sono dei problemi con l'apice del code.
dovrebbe essere:
```xml
 <code code="88.71" 
  displayName="DIAGNOSTICA ECOGRAFICA DEL CAPO E DEL COLLO" 
  codeSystem="2.16.840.1.113883.6.103" 
  codeSystemName="ICD-9-CM">
```
Indagheremo comunque la causa dell'errore errato
