### ISSUE TITLE
Campo id documento non valido

### ISSUE THREAD

**Issue by insielFse** [ministero-salute/it-fse-support#271]
Buongiorno,

abbiamo sottomesso una request di pubblicazione in cui il campo `identificativoDoc` è del tipo:

`2.16.840.1.113883.2.9.2.60.4.4^SCHEDA123456789_87273-9_XXXXXXXXX`

e riceviamo l'errore sotto riportato, sembra che il **trattino** dopo 87273 generi il problema. Dalla documentazione non risultano delle regex per validare il campo  `identificativoDoc` e il comportamento sembrebbe non essere standard.
```
"traceID": "704bf920fda902ab", 
"spanID": "704bf920fda902ab", 
"warning": null, 
"type": "/msg/id-doc", 
"title": "Campo id documento non valido", 
"status": 400, 
"detail": "L'identificativo documento non è valido", 
"instance": "/invalid-id", 
"govwayId": null, 
"workflowInstanceId": null, 
"message": null
```

**Comment by IStacchiotti** [comment]
Buongiorno, grazie mille per la segnalazione. Abbiamo riportato il bug al team di competenza, forniremo aggiornamenti non appena la fix sarà resa disponibile.

**Comment by IStacchiotti** [comment]
Buongiorno, Le confermiamo che è stata rilasciata una fix correttiva. La invitiamo cortesemente a riprovare, il problema non dovrebbe più presentarsi. Rimaniamo a completa disposizione in caso contrario. Grazie

**Comment by IStacchiotti** [comment]
Buonasera, procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
