### ISSUE TITLE
Documenti con standard HL7 ma senza schematron

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#272]
Buongiorno,
come ci si deve comportare per i tipi di documento che non sono compresi nella lista per l'accreditamento?

Ad esempio, per il Documento di Esenzione che ha
templateId root="2.16.840.1.113883.2.9.10.1.10.1"
il gateway ovviamente restituisce 
Schematron with template id root 2.16.840.1.113883.2.9.10.1.10.1 not found on database

Sembra quindi che per questi documenti non si debba effettuare la validazione. 
E' corretto?

Grazie

**Comment by IStacchiotti** [comment]
Buon pomeriggio, si conferma che la validazione viene effettuata per i documenti presenti nella lista per accreditamento. Grazie

**Comment by ponsilva** [comment]
Grazie per il riscontro
