### ISSUE TITLE
Errore PDF_UNEXPECTED_CDA nel report di accreditamento

### ISSUE THREAD

**Issue by davidecasiraghi** [ministero-salute/it-fse-support#274]
Buongiorno, abbiamo modificato il contenuto del CDA come da indicazioni sulla issue #241, ma continuiamo ad avere i seguenti errori:

[ {
  "id" : 11,
  "error" : "PDF_UNEXPECTED_CDA",
  "description" : "CDA contenuto nel PDF non conforme a quello associato al TraceID"
}, {
  "id" : 12,
  "error" : "PDF_UNEXPECTED_CDA",
  "description" : "CDA contenuto nel PDF non conforme a quello associato al TraceID"
} ]

Non campiamo come può essere sollevato questo errore in quanto i file caricati su GitHub sono gli stessi che sono stati inviati al gateway per la validazione.

Identificativi dell'applicativo
subject_application_id: PriamoRIS
subject_application_vendor: BCS
subject_application_version: 4.14.0.0

Grazie e saluti

**Comment by davidecasiraghi** [comment]
Buongiorno, è possibile avere un riscontro?

**Comment by Ser-ena** [comment]
Salve, stiamo analizzando le differenze segnalate sui CDA delle pull 275 e 305. Le daremo riscontro non appena terminata l'analisi.

**Comment by Ser-ena** [comment]
Buonasera, abbiamo effettuato una fix e visualizzato la nuova pull request #360. Entro domani elaboreremo il contenuto della nuova pull.

**Comment by davidecasiraghi** [comment]
Grazie, attendiamo l'esito dell'elaborazione

**Comment by IStacchiotti** [comment]
Buonasera, procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
