### ISSUE TITLE
Pubblicazione: campo JWT attachment_hash è case sensitive

### ISSUE THREAD

**Issue by cap-nic** [ministero-salute/it-fse-support#275]
Buongiorno,
stiamo facendo delle prove per quanto riguarda la pubblicazione, però sia con il nostro documento che con il documento "SIGNED_LAB1.pdf" presente al path [https://github.com/ministero-salute/it-fse-accreditamento](https://github.com/ministero-salute/it-fse-accreditamento) ci viene risposto il seguente errore:
```
{
  "traceID": "c0f02dda2c8ef1cc",
  "spanID": "c0f02dda2c8ef1cc",
  "type": "/msg/document-hash",
  "title": "Verifica hash fallita.",
  "detail": "Verifica hash fallita.",
  "status": 400,
  "instance": "/jwt-hash-match"
}
```

Di seguito il body della richiesta:
```
{
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.e932cae83dd7f32d9bc74277861d37c63f6f1ca471070fe0523d9538f067b774.8107d7f0ad^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "healthDataFormat": "CDA",
  "mode": "ATTACHMENT",
  "tipologiaStruttura": "Territorio",
  "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^230220_0004_230306130617",
  "identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.0",
  "tipoDocumentoLivAlto": "REF",
  "assettoOrganizzativo": "AD_PSC100",
  "tipoAttivitaClinica": "ERP",
  "identificativoSottomissione": ".16.840.1.113883.2.9.2.120.4.3.230220_0004_230306130617"
}
```

Abbiamo anche provato ad utilizzare il prefisso `SKIP_VALIDATION_` per il campo `identificativoDoc` ma sempre con lo stesso esito.

In allegato i token utilizzati:
[PUB_AUTH_TOKEN.txt](https://github.com/ministero-salute/it-fse-support/files/11260148/PUB_AUTH_TOKEN.txt)
[PUB_SIGNATURE_TOKEN.txt](https://github.com/ministero-salute/it-fse-support/files/11260150/PUB_SIGNATURE_TOKEN.txt)

In attesa di riscontro.
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, grazie mille per la segnalazione. Abbiamo riportato il bug al team di competenza, forniremo aggiornamenti non appena la fix sarà resa disponibile.

**Comment by IStacchiotti** [comment]
Buongiorno, Le confermiamo che è stata rilasciata una fix correttiva. La invitiamo cortesemente a riprovare, il problema non dovrebbe più presentarsi. Rimaniamo a completa disposizione in caso contrario. Grazie

**Comment by cap-nic** [comment]
Si confermo che ora funziona anche con hash upper case, chiudo l'issue. Grazie
