### ISSUE TITLE
Accreditamento EBIT - richiesta di feedback

### ISSUE THREAD

**Issue by EbitFSE** [ministero-salute/it-fse-support#276]
Buongiorno, avremmo necessità di ricevere dei feedback riguardo i test case sottoposti da settimane,
sembra che il processo di accreditamento sia bloccato e non abbiamo modo di procedere.
In risposta alla precedente issue, ci avete assicurato che il merge al main era stato preso in carico, ma ad oggi non sembra essere così,
non vediamo nessun aggiornamento perciò rimaniamo in attesa di un'urgente risposta da parte vostra.
Gli ultimi commits a cui mi riferisco sono:
[https://github.com/ministero-salute/it-fse-accreditamento/pull/241/commits](url)
riguardanti la richiesta per l'accreditamento per il software Suitestensa:
[https://github.com/ministero-salute/it-fse-accreditamento/tree/main/GATEWAY/A1%23111EBITSRLXXXX/EBITSRL/SUITESTENSA/2.1b34.x](url)
Grazie

**Comment by IStacchiotti** [comment]
Buonasera, ci risulta che vi dovrebbe essere arrivata una mail proprio oggi pomeriggio con i risultati dei test automatici rlativi alla pr #241.

**Comment by EbitFSE** [comment]
Buongiorno, abbiamo adeguato i files secondo quanto riportato nella mail e abbiamo creato una nuova pull request [,](https://github.com/ministero-salute/it-fse-accreditamento/pull/311)
rimaniamo in attesa dei risultati.
Grazie
Saluti

**Comment by IStacchiotti** [comment]
Buonasera, la presente viene chiusa come risolta dal momento che eventuali aggiornamenti saranno recapitati via email. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
