### ISSUE TITLE
Mancato Accreditamento (SING_VACC  - Caso di Test 3) - pull request #247

### ISSUE THREAD

**Issue by PRAFFO72** [ministero-salute/it-fse-support#277]
Salve, chiediamo un riscontro in quanto non riusciamo a l'interpretare uno degli errori a seguto dell'ultima [pull request](https://github.com/ministero-salute/it-fse-accreditamento/pull/247).

Si tratta del test con ID 22 (SING_VACC - Caso di Test 3).
Gli errori che non riusciamo a comprendere sono i seguenti:
```
 <error code="022" attribute="root" expected="Valorizzare con uno dei seguenti valori: 2.16.840.1.113883.2.9.10.1.11.4.10/2.16.840.1.113883.2.9.10.1.11.4.7" actual="2.16.840.1.113883.2.9.10.1.11.4.3">
  ClinicalDocument/component/structuredBody/component/section[ID='Singola_Vaccinazione']/entry/substanceAdministration/entryRelationship/observation/templateId
 </error>
 <error code="023" attribute="code" expected="Valorizzare con uno dei seguenti valori: 85714-4/59784-9" actual="30973-2">
  ClinicalDocument/component/structuredBody/component/section[ID='Singola_Vaccinazione']/entry/substanceAdministration/entryRelationship/observation/code
 </error>
```
Entrambi gli errori si riferiscono alla mancanza nel _substanceAdministration_ di due _entryRelationship_ :
- "ragione esonero/omissione o differimento" (templateId **2.16.840.1.113883.2.9.10.1.11.4.10**, code **85714-4**)
- "malattia con presunta immunità" (templateId **2.16.840.1.113883.2.9.10.1.11.4.7**, code **59784-9**)

La nostra perplessità nasce dal fatto che nel nostro CDA le due _entryRelationship_ sono entrambe presenti, ma viene individiata ("actual") solo la _entryRelationship_ "numero di dose" (templateId **2.16.840.1.113883.2.9.10.1.11.4.3**, code **30973-2**).

Come indicato nel [file excel](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/3-Scheda%20Singola%20Vaccinazione/CDA2_Scheda_Singola%20Vaccinazione_OK.xlsx) (da F54 in poi) abbiamo generato tutte e quattro le _entryRelationship_ richieste per il test.

Dove sbagliamo?
C'è un ordine specifico in cui le _entryRelationship_ devono comparire?
Come dobbiamo sistemare per passare il test?
Allegiamo per completezza il CDA (validato, ma) che genera gli errori di accreditamento.

[022_SING_VAC_CT3.zip](https://github.com/ministero-salute/it-fse-support/files/11261705/022_SING_VAC_CT3.zip)

**Comment by IStacchiotti** [comment]
Buonasera, ci risulta che è riuscito ad andare avanti con la pull request #279. Le chiediamo pertanto la cortesia di chiudere il presente ticket, non essendo più necessario. Grazie

**Comment by PRAFFO72** [comment]
Siamo riusciti a passare il test,  ma solo dopo una serie di tentativi empirici con il [tool offline](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/gtw-certifier).

Per quello che abbiamo capito, la differenza tra i due CDA
(quello allegato precedentemente e quello che ha passato il test)
sta esclusivamente nell'ordine in cui vengono inserite le _entryRelationship_ .
In questo caso specifico (scheda di ESONERO o SOSPENSIONE),
 le _entryRelationship_  devono essere inserite in questo ordine:
- "Ragione esonero/omissione o differimento" 
- "Malattia per cui si effettua la Vaccinazione"
- "Malattia con presunta immunità"
- "Numero di Dose"

Confermate la nostra deduzione?

Alleghiamo per completezza anche il CDA che ha passato il test:
[022_SING_VAC_CT3_ok.zip](https://github.com/ministero-salute/it-fse-support/files/11344945/022_SING_VAC_CT3_ok.zip)

**Comment by IStacchiotti** [comment]
Buongiorno, grazie per la segnalazione. Confermiamo che prima effettivamente contava l'ordine: era presente un'anomalia che è stata risolta. Ora il problema non dovrebbe più ripresentarsi. Rimaniamo a disposizione per ulteriori segnalazioni.

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto. Grazie
