### ISSUE TITLE
TEST CASE Validazione - Possibile refuso in CDA2_Lettera di Dimissione Ospedaliera_OK.xlsx

### ISSUE THREAD

**Issue by PRAFFO72** [ministero-salute/it-fse-support#278]
Salve, a seguito del mancato accreditamento per errori nei CDA della LDO,
segnaliamo un possibile refuso nel [file excel](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/6-Lettera%20di%20Dimissione%20Ospedaliera/CDA2_Lettera%20di%20Dimissione%20Ospedaliera_OK.xlsx) che indica come valorizzare i vari elementi e attributi.

Nel foglio "LDO - Caso di Test 2" (cella F113) dove si fa riferimento al contenuto del
 _displayName_ per il _code_ della _section_ con **ID="Terapia_Farmacologica_Ingresso"** è scritto quanto segue:
 `Deve essere valorizzata con "Terapia Farmacologica all’ingresso".`
Tuttavia, se ci si attiene strettamente a questa indicazione, il tentativo di accreditamento restituisce questo errore:
```
 <error code="124" attribute="displayName" expected="Terapia Farmacologica all'ingresso" actual="Terapia Farmacologica allâ€™ingresso">
  ClinicalDocument/component/structuredBody/component/section[ID='Inquadramento_clinico_iniziale']/component/section[ID='Terapia_Farmacologica_Ingresso']/code
 </error>
```
Tale refuso (sostituzione del carattere _apice_ con il carattere _apostrofo_)
compare anche nei fogli "LDO - Caso di Test 3" (cella F113) e "LDO - Caso di Test 4" (cella F115).

**Comment by IStacchiotti** [comment]
Buongiorno, grazie per la segnalazione. Verrà rilasciata una fix per risolvere l'anomalia. Le daremo evidenza non appena sarà resa disponibile. Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che è stata rilasciata una fix correttiva. La invitiamo cortesemente a riprovare, il problema non dovrebbe più presentarsi. Rimaniamo a completa disposizione in caso contrario. Grazie

**Comment by PRAFFO72** [comment]
Grazie, anche se non vediamo nessuna modifica recente al [file excel](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/6-Lettera%20di%20Dimissione%20Ospedaliera/CDA2_Lettera%20di%20Dimissione%20Ospedaliera_OK.xlsx).
Non potendolo provare direttamente (abbiamo già passato i test) confidiamo che sia stato rilassato il controllo sui _displayName_ nel vostro sistema di verifica accreditamento.
Del resto si tratta di una differenza grafica minima (apice ' al posto di apostrofo ’) in un etichetta testuale:
 a nostro giudizio non dovrebbe pregiudicare la correttezza dell'intero test.

Segnalimo che il [tool offline](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/gtw-certifier) genera ancora il medesimo errore.

**Comment by IStacchiotti** [comment]
Buon pomeriggio, le confermiamo che abbiamo evidenza che è stata rilasciata un fix per correggere i controlli automatici. Non sono state apportate modifiche alla documentazione. Quanto prima verrà riportato l'aggiornamento anche nel tool offline gwt-certifier, nel frattempo procediamo alla chiusura del presente. Grazie
