### ISSUE TITLE
400 Bad Request in validazione

### ISSUE THREAD

**Issue by nspazzoli** [ministero-salute/it-fse-support#28]
Buongiorno,

sto provando a validare un documento inviando la seguete post 
[richiesta_validazione.txt](https://github.com/ministero-salute/it-fse-support/files/9858528/richiesta_validazione.txt)
[filename.pdf](https://github.com/ministero-salute/it-fse-support/files/9858522/filename.pdf)

ma ricevo in risposta 
```
"HTTP/1.1 400 Bad Request[\r][\n]"
"X-Backside-Transport: FAIL FAIL[\r][\n]"
"Connection: Keep-Alive[\r][\n]"
"Transfer-Encoding: chunked[\r][\n]"
"Set-Cookie: 894d46ecfc124039ee218b63c12a3329=9c67f12c45b3db67bf54bbc206e49b4a; path=/; HttpOnly; Secure; SameSite=None[\r][\n]"
"Server: GovWay-SOGEI[\r][\n]"
"GovWay-Message-ID: cf1547d4-9ada-4bad-8fc5-afac78ee7826[\r][\n]"
"GovWay-Transaction-ID: 4c6048c6-543d-11ed-8d8c-005056ae7395[\r][\n]"
"Content-Type: application/problem+json[\r][\n]"
"Date: Tue, 25 Oct 2022 08:16:17 GMT[\r][\n]"
"X-Global-Transaction-ID: 3f7e3e2d63579b506d20c52d[\r][\n]"
```

I Jwt mi sembra contengano tutti claim. 

Grazie

**Comment by zukka77** [comment]
ciao @nspazzoli , come ci siamo detti controlla il body della risposta http, verificato che contiene l'errore di validazione del CDA, direi che possiamo chiudere l'issue.
