### ISSUE TITLE
Dubbi su mancato accreditamento (CERT_VACC - Casi di Test 16 e 19) - pull request #262

### ISSUE THREAD

**Issue by DavideGuidotti** [ministero-salute/it-fse-support#280]
Buongiorno, chiedo riscontro rigurdo a un paio di dubbi riguardo alcuni errori restituiti in seguito alla nostra ultima pull request per l'accreditamento di AriannaVaccinazioni ( https://github.com/ministero-salute/it-fse-accreditamento/pull/262 )

Il caso di test con id 16 (caso d'uso 1 per il certificato vaccinale) è stato scartato in quanto non sono presenti le sezioni con codici 2.16.840.1.113883.5.112 e 2.16.840.1.113883.5.1052, relativi rispettivamente alla via di simministrazione (routeCode) e al sito inoculazione (approachSiteCode)
```
{
  "id" : 16,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='012' attribute='codeSystem' actual = '' expected = '2.16.840.1.113883.5.112'>ClinicalDocument/component/structuredBody/component/section[ID='Certificato_Vaccinale']/entry/substanceAdministration/routeCode</error>"
}

{
  "id" : 16,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='014' attribute='codeSystem' actual = '' expected = '2.16.840.1.113883.5.1052'>ClinicalDocument/component/structuredBody/component/section[ID='Certificato_Vaccinale']/entry/substanceAdministration/approachSiteCode</error>"
}
```

La richiesta nel caso id=16 era di inserire solamente i dati minimi previsti da specifiche nazionali HL7 italia, ma appunto per le specifiche nazionali questi due tag non sono obbligatori.
Perchè quindi la verifica automatica li prevede?

Lo stesso discorso vale per il tag "participant", anch'esso assente nel nostro cda perchè non obbligatorio nelle specifiche nazionali.
```
{
  "id" : 16,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='036' attribute='typeCode' actual = '' expected = 'LOC'>ClinicalDocument/component/structuredBody/component/section[ID='Certificato_Vaccinale']/entry/substanceAdministration/participant</error>"
}
```

Analogamente, è stato restituito errore in quanto non è stata inclusa nessuna entryRelationship, ma anche queste da specifiche relazionali sono opzionali.
```
{
  "id" : 16,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='038' attribute='typeCode' actual = '' expected = 'SUBJ RSON'>ClinicalDocument/component/structuredBody/component/section[ID='Certificato_Vaccinale']/entry/substanceAdministration/entryRelationship</error>"
}
```

Ho inoltre un secondo dubbio riguardo il caso di test con id 19, vale a dire il caso d'uso 4 per il certificato vaccinale.
abbiamo ricevuto un errore perchè non è stato trovato un tag reference con il value impostato a "Malattia con presunta immunità"
```
{
  "id" : 19,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='145' attribute='value' actual = '#id-64f7c44a-c74b-4c28-b434-f0f526175fcc,#id-26d0f09a-3742-4468-99f0-b4558ee43ee1,#id-9ec8ebd5-79f9-44f8-a572-fa2a0672d9d2' expected = 'Malattia con presunta immunità'>ClinicalDocument/component/structuredBody/component/section[ID='Certificato_Vaccinale']/entry/substanceAdministration/entryRelationship/observation/value/originalText/reference</error>"
}
```
Tuttavia, nel documento word con i casi d'uso non era richiesto di indicare anche la entryRelationship relativa alla mallattia con presunta immunità (che è un dato facoltativo).
Inoltre, il value di un tag reference da specifiche nazionali dovrebbe contenere il riferimento incrociato alla parte narrativa, perchè viene richiesto di inserire "Malattia con presunta immunità"?

**Comment by IStacchiotti** [comment]
Buongiorno.
In merito al primo punto relativo alla non presenza di due elementi, quali `'routeCode'` e `'approachSiteCode'`, opzionali da specifiche, è necessario inserirli per completezza di informazioni e per riprodurre correttamente il caso di test 1.
Anche per i successivi punti relativi al caso d'uso 1, fa fede l'excel che è stato fornito con tutti i casi d'uso e tutti gli elementi da inserire (nello specifico i @typeCode da associare o al tag `'participant'` o `'entryRelationship'` opzionali da specifiche ma obbligatori per riprodurre correttamente il caso di test).
Per quanto riguarda l'entryRelationship "Malattia con presunta immunità" è necessario inserire l'attributo @value dell'elemento `originalText/reference`.

**Comment by DavideGuidotti** [comment]
Al di la delle specifiche nazionali, facevo riferiemnto anche al file [CDA2_Certificato Vaccinale_OK.xlsx](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/4-Certificato%20Vaccinale/CDA2_Certificato%20Vaccinale_OK.xlsx)

Per il caso di test 1 anche nell'excel i campi `'routeCode'`, `'approachSiteCode'`, `participant` e `entryRelationship` risultano tutti opzionali, per questo ero perplesso.

Per quanto riguarda il caso 19, il vostro controllo mi impone di inserire il testo `"Malattia con presunta immunità"` a prescindere, ma quello che mi aspetterei è che in quel campo ci vada il riferimento al tag che contiene l'informazione nella parte narrativa piuttosto che un testo fisso, come scritto sia nelle specifiche nazionali che nell'excel.

**Comment by IStacchiotti** [comment]
Buongiorno, grazie per la segnalazione. Verrà rilasciata una fix per risolvere l'anomalia. Le daremo evidenza non appena sarà resa disponibile. Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, Le confermiamo che è stata rilasciata una fix correttiva. La invitiamo cortesemente a riprovare, il problema non dovrebbe più presentarsi. Rimaniamo a completa disposizione in caso contrario. Grazie

**Comment by DavideGuidotti** [comment]
Sembra che il problema sussista ancora. nell'ultima pull request abbimo caricato nuovamente il caso 16 rimuovendo gli elementi che dovrebbero essere facoltativi (routeCode, approachSiteCode, participant e entryRelationship), ma ci è stato restituito un json di errore in cui viene sostanzialmente detto che questi dati sono necessari.

Cosa è stato corretto esattmente? quli sono i dati che possono essere omessi e quali devono necessariamente essere presenti?
