### ISSUE TITLE
Problema validation FSE

### ISSUE THREAD

**Issue by mmaggi69** [ministero-salute/it-fse-support#282]
Buongiorno sto effettuando la Richiesta per validazione Referto ma ottengo il seguente errore:

{
    "type": "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
    "title": "AuthorizationContentDeny",
    "status": 403,
    "detail": "Unauthorized request content",
    "govway_id": "c8971aff-df5a-11ed-80ae-005056ae7395"
}

I token che sto utilizzando sono i seguenti: 

------------- Authorization Bearer Token ---------------

eyJ4NWMiOlsiTUlJRmFEQ0NBMUNnQXdJQkFnSVVhVXBaSWFaaWFnVURIK0xNTHptcFk3T1pUREF3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHV
hWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TX
pBME1URXlNVEkzTVRGYUZ3MHlOakEwTVRFeU1USTNNVEJhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SM
HdHd1lEVlFSaERCUkRSanBKVkMweE1URkZWVkpQVFVWRVNVTkJUREVhTUJnR0ExVUVBd3dSVXpFak1URXhSVlZTVDAxRlJFbERRVXd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVB
QTRJQkR3QXdnZ0VLQW9JQkFRQzU1SHpiQTY2bTFYbFhkN0NKV3ZZOEYwVHZoTUJYaXJQRWFiaDIwWUZzemVlMmFTT1ZwZ3ZOak4zdEhEYW02Q0Q5ckJiM011c2s2dXI2eGxFUnd
SdmJqNUkwd3UyTUw0R2ZWU3dvYmhick80aHBnK0txbFdRNEExb1pWUzlMUXlLTGZBSFF1NmplRW9WYmZLK1Ntb3BCZWlyeWtEUmVKUTlGbSsyditKSzhzVkhuRVA5Uy95dFNFcU
9NamN0TmJ1TFMrMlc1NWZ4RDR2ZlZLS0Nybk56ZVJPNm1YVU9UZDJxK3Rsb2ZEQ1dEY3pBK3pmaUF6ZE1xaHJ6Ly8zNGExUE1KWHJVQy81MnVBZnZ6WnpIZTEwUWtjRHgzS1dRb
210dVFUOTN5cVI5bjdHYkt1REkrbkZFWnN6MlBQYmtyWmNQU0I2c1BvaHJXazQzZjFrTUNtSTNmQWdNQkFBR2pnZ0VZTUlJQkZEQWZCZ05WSFNNRUdEQVdnQlFXT2FrYUJZbTNE
eTJ5TmUzQ0NackZBNE1pUHpBU0JnTlZIU0FFQ3pBSk1BY0dCU3RNSFFFTE1JR3RCZ05WSFI4RWdhVXdnYUl3Z1orZ2daeWdnWm1HZ1pab2RIUndjem92TDJOaGMyOW5aV2x6ZG1
sc0xuTnZaMlZwTG1sMEwyVnFZbU5oTDNCMVlteHBZM2RsWWk5M1pXSmthWE4wTDJObGNuUmthWE4wUDJOdFpEMWpjbXdtYVhOemRXVnlQVU5PSlRORVEwRXJUV2x1YVhOMFpYSn
ZLMlJsYkd4aEsxTmhiSFYwWlN0VVpYTjBKVEpEVHlVelJFMXBibWx6ZEdWeWJ5dGtaV3hzWVN0VFlXeDFkR1VsTWtOREpUTkVTVlF3SFFZRFZSME9CQllFRkUrZnFpWnkrcmFEW
nlwYUpvWXFOWlI1QkU5cU1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQU5UV0ZYOW16c2Z2ejJYTzRqL0gvUGVQdmQ5Y0Q3WFZIcFl5OEkr
Z2dxVU5TWVZhUkhpeVdGcVdrWDN2bDgyemhDeW1KS2hic2tFcGV3NktZbjYxYzdTeFNRb1hNdU01cjFYZ0VGaTg0MXpwYURoN2huT3diRkpHeVlSZVVrVFFmM3k1VDdrTmozWkR
TWmZBMmtZajBQdFJ5ZjVEUnRPZEtuMVc1ay8zUlJNSWxVRFVjQ1FTSEg5TlJVZndWVENxZnZFUjNSZTJlYmVtWGRkNnFIY0lwaDJrODVnOFZ5RlZYY1BGVHp6YUl1US92QSttUE
VWVldXeXlFV1o4NWQ2RVphNS8yODV0dEtpOENDN1VEazZJZGNjSjBsREhvNVZIVmJidEFxejFuTzVpRDN2ejg1ejE4WHdlb3h3aHhBem1SYzBFTXNHanJPaFJVTHg0ZHprUzJme
Us0VFlYSTQ0K0U2THlDenV0bWVYSmNLNjZrVVA0RCs0WmEzRnNITjJkT3RlbHkxMzIxZnZhMjE4cGZ0MFZhenYwdFJ2ZDgzZlU2NDBBS3E0bmswY3d2aFEzZnYvN3VoTXFwYkQ0
VWdHZERFVE5pNzVqa3Z5bTlqUHl1M2dWQjBiQVNxMFBiakkvZ2d4VmUzRk5VbHpzQzI2OTZGVTZqYk1WeVA4ZHM5bm0wWUVMV3M2N3Y3RGNWOUhGQkFodmFiZW1rNExOU1IvVXl
IVWtZS2wyUXNQcnlxdDloVEZFR1V0ZWxtMXo0d3NnRTJUcEJscHVyejRkNDVrQkV1YlZqdC9QSFlXZnZxTjhhTHhWU2kwYU9lMW5iMEdMb1VzQ3JaY0poeTRIQ1N0THcxSlhjWE
JyYlg3OWdkd1hwaXpQVXRkK2lOZEJJcW1mcCtFM0R6YUpNZHFNPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJETFNQTEE2N0QwNEYyMDVHXl5eJjIuMTYu
ODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjE
iLCJpc3MiOiJhdXRoOlMxIzExMTFFVVJPTUVESUNBTCIsImV4cCI6MTY4MTk4OTMzNiwiaWF0IjoxNjgxOTg1NzM2LCJqdGkiOiI1NmZhNmMwYy00NmY2LTM2NDAtODFlZC0yZj
g3NjAwNWEyNzIifQ.Y5O4pDMEi5FSfsBUPXOdeX_s4BmZvo8w3L_YX4a4-_BrLU1GrS7ceWY01wYraUCsqs49fk6KX6bHXVr8t7Sg1OXgeypdHJFp3HZ1F_P_yNHOLVK3Syxp6d
C9emb4x3Reqf14bab29JpCmdjY_vgDVZ0nX2LUu9Mc8Bz5s_nCsbKJqoujcqVhm9YBalfkt46xi8dU7F9Hd_KKrNUkAy5cFO4saB210xKqRn5ckcN_ZvO22aTK-WFk69EIgysxe
kLdDc0Nfw3DjPS3juaQwX0COeuVQ2gOX2lv6Ec4Gj5paAZ8wfswtYRJ4FHw0MLLuZGT6wsfxH0vopmJ5oX4iXUEbA

------------- FSE-JWT-Signature ---------------

eyJ4NWMiOlsiTUlJRmFEQ0NBMUNnQXdJQkFnSVVhVXBaSWFaaWFnVURIK0xNTHptcFk3T1pUREF3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHV
hWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TX
pBME1URXlNVEkzTVRGYUZ3MHlOakEwTVRFeU1USTNNVEJhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SM
HdHd1lEVlFSaERCUkRSanBKVkMweE1URkZWVkpQVFVWRVNVTkJUREVhTUJnR0ExVUVBd3dSVXpFak1URXhSVlZTVDAxRlJFbERRVXd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVB
QTRJQkR3QXdnZ0VLQW9JQkFRQzU1SHpiQTY2bTFYbFhkN0NKV3ZZOEYwVHZoTUJYaXJQRWFiaDIwWUZzemVlMmFTT1ZwZ3ZOak4zdEhEYW02Q0Q5ckJiM011c2s2dXI2eGxFUnd
SdmJqNUkwd3UyTUw0R2ZWU3dvYmhick80aHBnK0txbFdRNEExb1pWUzlMUXlLTGZBSFF1NmplRW9WYmZLK1Ntb3BCZWlyeWtEUmVKUTlGbSsyditKSzhzVkhuRVA5Uy95dFNFcU
9NamN0TmJ1TFMrMlc1NWZ4RDR2ZlZLS0Nybk56ZVJPNm1YVU9UZDJxK3Rsb2ZEQ1dEY3pBK3pmaUF6ZE1xaHJ6Ly8zNGExUE1KWHJVQy81MnVBZnZ6WnpIZTEwUWtjRHgzS1dRb
210dVFUOTN5cVI5bjdHYkt1REkrbkZFWnN6MlBQYmtyWmNQU0I2c1BvaHJXazQzZjFrTUNtSTNmQWdNQkFBR2pnZ0VZTUlJQkZEQWZCZ05WSFNNRUdEQVdnQlFXT2FrYUJZbTNE
eTJ5TmUzQ0NackZBNE1pUHpBU0JnTlZIU0FFQ3pBSk1BY0dCU3RNSFFFTE1JR3RCZ05WSFI4RWdhVXdnYUl3Z1orZ2daeWdnWm1HZ1pab2RIUndjem92TDJOaGMyOW5aV2x6ZG1
sc0xuTnZaMlZwTG1sMEwyVnFZbU5oTDNCMVlteHBZM2RsWWk5M1pXSmthWE4wTDJObGNuUmthWE4wUDJOdFpEMWpjbXdtYVhOemRXVnlQVU5PSlRORVEwRXJUV2x1YVhOMFpYSn
ZLMlJsYkd4aEsxTmhiSFYwWlN0VVpYTjBKVEpEVHlVelJFMXBibWx6ZEdWeWJ5dGtaV3hzWVN0VFlXeDFkR1VsTWtOREpUTkVTVlF3SFFZRFZSME9CQllFRkUrZnFpWnkrcmFEW
nlwYUpvWXFOWlI1QkU5cU1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQU5UV0ZYOW16c2Z2ejJYTzRqL0gvUGVQdmQ5Y0Q3WFZIcFl5OEkr
Z2dxVU5TWVZhUkhpeVdGcVdrWDN2bDgyemhDeW1KS2hic2tFcGV3NktZbjYxYzdTeFNRb1hNdU01cjFYZ0VGaTg0MXpwYURoN2huT3diRkpHeVlSZVVrVFFmM3k1VDdrTmozWkR
TWmZBMmtZajBQdFJ5ZjVEUnRPZEtuMVc1ay8zUlJNSWxVRFVjQ1FTSEg5TlJVZndWVENxZnZFUjNSZTJlYmVtWGRkNnFIY0lwaDJrODVnOFZ5RlZYY1BGVHp6YUl1US92QSttUE
VWVldXeXlFV1o4NWQ2RVphNS8yODV0dEtpOENDN1VEazZJZGNjSjBsREhvNVZIVmJidEFxejFuTzVpRDN2ejg1ejE4WHdlb3h3aHhBem1SYzBFTXNHanJPaFJVTHg0ZHprUzJme
Us0VFlYSTQ0K0U2THlDenV0bWVYSmNLNjZrVVA0RCs0WmEzRnNITjJkT3RlbHkxMzIxZnZhMjE4cGZ0MFZhenYwdFJ2ZDgzZlU2NDBBS3E0bmswY3d2aFEzZnYvN3VoTXFwYkQ0
VWdHZERFVE5pNzVqa3Z5bTlqUHl1M2dWQjBiQVNxMFBiakkvZ2d4VmUzRk5VbHpzQzI2OTZGVTZqYk1WeVA4ZHM5bm0wWUVMV3M2N3Y3RGNWOUhGQkFodmFiZW1rNExOU1IvVXl
IVWtZS2wyUXNQcnlxdDloVEZFR1V0ZWxtMXo0d3NnRTJUcEJscHVyejRkNDVrQkV1YlZqdC9QSFlXZnZxTjhhTHhWU2kwYU9lMW5iMEdMb1VzQ3JaY0poeTRIQ1N0THcxSlhjWE
JyYlg3OWdkd1hwaXpQVXRkK2lOZEJJcW1mcCtFM0R6YUpNZHFNPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJETFNQTEE2N0QwNEYyMDVHXl5eJjIuMTYu
ODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJEUlMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImlzcyI6ImludGVncml0eTpTMSMxMTE
xRVVST01FRElDQUwiLCJsb2NhbGl0eSI6IjIwNDUyMDMwNyIsInN1YmplY3RfYXBwbGljYXRpb25fdmVyc2lvbiI6IjEuMCIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW
9uZSBDYW1wYW5pYSIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMTUwMjA0NTIwMzA3IiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvd
ndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJhY3Rpb25faWQiOiJDUkVBVEUiLCJyZXNvdXJjZV9obDdfdHlwZSI6IignMTE1MDIt
Ml5eMi4xNi44NDAuMS4xMTM4ODMuNi4xJykiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiTUVESVdFQiIsImV4cCI6MTY4MTk4OTMzNiwic3ViamVjdF9hcHBsaWNhdGlvbl9
2ZW5kb3IiOiJFVVJPTUVESUNBTCIsImlhdCI6MTY4MTk4NTczNiwianRpIjoiNTZmYTZjMGMtNDZmNi0zNjQwLTgxZWQtMmY4NzYwMDVhMjcyIiwicGVyc29uX2lkIjoiUlNTTV
JBMjJBMDFBMzk5Wl5eXiZhbXA7Mi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJmFtcDtJU08ifQ.YzIXnYNajjyB26i4MiZXnJmADqPpr31bFWYd6vYVda27VPG9EDOM9XvTkj
k9ZjYclyt2AvYo53sOht_YOsmhC95Ggy0vTv0KaflkF9P4fCUoX-2XWyF70JRXOhdaJpfgb4dRyGSaXb6E_BkMGYbzY5x_OZ1cdSGyYrhyN1_RPj7P1OEooQiAiAQ9osauRoxZ4
2pPNIrnVmY4UOOIDco839Sh_pMFcjARsVpSouYXjxOyBKVfL1662sAWh06BKNpHHDhI3y6EgfqkcPDtoF7S77kzf8LDDJKr67I4kkk03-_XZbpvL0umwQYHTBLSE8Y0Am1846Qk
EhmVULKJus-WPw

Potreste indicarmi qual'è il problema ?

**Comment by masciamariotti** [comment]
Buonasera,
da una prima analisi sembrerebbe che nei 2 JWT stia inviando un common name errato:
"iss": "auth:S1#1111EUROMEDICAL"
"iss": "integrity:S1#1111EUROMEDICAL",

1111EUROMEDICAL --> mentre dovrebbe essere 111EUROMEDICAL

**Comment by mmaggi69** [comment]
Buongiorno,
adesso utilizzando i seguenti token 

------------- Authorization Bearer Token ---------------

eyJ4NWMiOlsiTUlJRmFEQ0NBMUNnQXdJQkFnSVVhVXBaSWFaaWFnVURIK0xNTHptcFk3T1pUREF3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHV
hWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TX
pBME1URXlNVEkzTVRGYUZ3MHlOakEwTVRFeU1USTNNVEJhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SM
HdHd1lEVlFSaERCUkRSanBKVkMweE1URkZWVkpQVFVWRVNVTkJUREVhTUJnR0ExVUVBd3dSVXpFak1URXhSVlZTVDAxRlJFbERRVXd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVB
QTRJQkR3QXdnZ0VLQW9JQkFRQzU1SHpiQTY2bTFYbFhkN0NKV3ZZOEYwVHZoTUJYaXJQRWFiaDIwWUZzemVlMmFTT1ZwZ3ZOak4zdEhEYW02Q0Q5ckJiM011c2s2dXI2eGxFUnd
SdmJqNUkwd3UyTUw0R2ZWU3dvYmhick80aHBnK0txbFdRNEExb1pWUzlMUXlLTGZBSFF1NmplRW9WYmZLK1Ntb3BCZWlyeWtEUmVKUTlGbSsyditKSzhzVkhuRVA5Uy95dFNFcU
9NamN0TmJ1TFMrMlc1NWZ4RDR2ZlZLS0Nybk56ZVJPNm1YVU9UZDJxK3Rsb2ZEQ1dEY3pBK3pmaUF6ZE1xaHJ6Ly8zNGExUE1KWHJVQy81MnVBZnZ6WnpIZTEwUWtjRHgzS1dRb
210dVFUOTN5cVI5bjdHYkt1REkrbkZFWnN6MlBQYmtyWmNQU0I2c1BvaHJXazQzZjFrTUNtSTNmQWdNQkFBR2pnZ0VZTUlJQkZEQWZCZ05WSFNNRUdEQVdnQlFXT2FrYUJZbTNE
eTJ5TmUzQ0NackZBNE1pUHpBU0JnTlZIU0FFQ3pBSk1BY0dCU3RNSFFFTE1JR3RCZ05WSFI4RWdhVXdnYUl3Z1orZ2daeWdnWm1HZ1pab2RIUndjem92TDJOaGMyOW5aV2x6ZG1
sc0xuTnZaMlZwTG1sMEwyVnFZbU5oTDNCMVlteHBZM2RsWWk5M1pXSmthWE4wTDJObGNuUmthWE4wUDJOdFpEMWpjbXdtYVhOemRXVnlQVU5PSlRORVEwRXJUV2x1YVhOMFpYSn
ZLMlJsYkd4aEsxTmhiSFYwWlN0VVpYTjBKVEpEVHlVelJFMXBibWx6ZEdWeWJ5dGtaV3hzWVN0VFlXeDFkR1VsTWtOREpUTkVTVlF3SFFZRFZSME9CQllFRkUrZnFpWnkrcmFEW
nlwYUpvWXFOWlI1QkU5cU1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQU5UV0ZYOW16c2Z2ejJYTzRqL0gvUGVQdmQ5Y0Q3WFZIcFl5OEkr
Z2dxVU5TWVZhUkhpeVdGcVdrWDN2bDgyemhDeW1KS2hic2tFcGV3NktZbjYxYzdTeFNRb1hNdU01cjFYZ0VGaTg0MXpwYURoN2huT3diRkpHeVlSZVVrVFFmM3k1VDdrTmozWkR
TWmZBMmtZajBQdFJ5ZjVEUnRPZEtuMVc1ay8zUlJNSWxVRFVjQ1FTSEg5TlJVZndWVENxZnZFUjNSZTJlYmVtWGRkNnFIY0lwaDJrODVnOFZ5RlZYY1BGVHp6YUl1US92QSttUE
VWVldXeXlFV1o4NWQ2RVphNS8yODV0dEtpOENDN1VEazZJZGNjSjBsREhvNVZIVmJidEFxejFuTzVpRDN2ejg1ejE4WHdlb3h3aHhBem1SYzBFTXNHanJPaFJVTHg0ZHprUzJme
Us0VFlYSTQ0K0U2THlDenV0bWVYSmNLNjZrVVA0RCs0WmEzRnNITjJkT3RlbHkxMzIxZnZhMjE4cGZ0MFZhenYwdFJ2ZDgzZlU2NDBBS3E0bmswY3d2aFEzZnYvN3VoTXFwYkQ0
VWdHZERFVE5pNzVqa3Z5bTlqUHl1M2dWQjBiQVNxMFBiakkvZ2d4VmUzRk5VbHpzQzI2OTZGVTZqYk1WeVA4ZHM5bm0wWUVMV3M2N3Y3RGNWOUhGQkFodmFiZW1rNExOU1IvVXl
IVWtZS2wyUXNQcnlxdDloVEZFR1V0ZWxtMXo0d3NnRTJUcEJscHVyejRkNDVrQkV1YlZqdC9QSFlXZnZxTjhhTHhWU2kwYU9lMW5iMEdMb1VzQ3JaY0poeTRIQ1N0THcxSlhjWE
JyYlg3OWdkd1hwaXpQVXRkK2lOZEJJcW1mcCtFM0R6YUpNZHFNPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJETFNQTEE2N0QwNEYyMDVHXl5eJjIuMTYu
ODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjE
iLCJpc3MiOiJhdXRoOlMxIzExMUVVUk9NRURJQ0FMIiwiZXhwIjoxNjgyMzMxMjEwLCJpYXQiOjE2ODIzMjc2MTAsImp0aSI6IjU2ZmE2YzBjLTQ2ZjYtMzY0MC04MWVkLTJmOD
c2MDA1YTI3MiJ9.NbjbNQ-tqz7IbWTDYT0zZSBCkeb1dOOHxwhJeMNAYiBwqU_kjehW8OpmegOBq5XK-GhLRN0hRfxKNqvM-ZDzz6wiwjI67Adik-4jicLNkYswNaMsLjwSJR8n
HMMuy0UBo4G20cTqGEEcK57wqQJu8VyRAf318Vsq9I-6wtjAFnwXXIa1CE1BsR6p-S37jBs5xEYNGi1Sr4Urw4rtTE3C73FYb3A7WQApvn15YLmy86iKXOGh3luxJhQkSOxRrNv
MMmBX6tYiCoKT6IBJzdhYYnVh7dRgtJsfYGCBV2xGvRkqln3dCUTBRboACD1p1RxxiRp7Tkp0mQk15jmaoj9u9A

------------- FSE-JWT-Signature ---------------

eyJ4NWMiOlsiTUlJRmFEQ0NBMUNnQXdJQkFnSVVhVXBaSWFaaWFnVURIK0xNTHptcFk3T1pUREF3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHV
hWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TX
pBME1URXlNVEkzTVRGYUZ3MHlOakEwTVRFeU1USTNNVEJhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SM
HdHd1lEVlFSaERCUkRSanBKVkMweE1URkZWVkpQVFVWRVNVTkJUREVhTUJnR0ExVUVBd3dSVXpFak1URXhSVlZTVDAxRlJFbERRVXd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVB
QTRJQkR3QXdnZ0VLQW9JQkFRQzU1SHpiQTY2bTFYbFhkN0NKV3ZZOEYwVHZoTUJYaXJQRWFiaDIwWUZzemVlMmFTT1ZwZ3ZOak4zdEhEYW02Q0Q5ckJiM011c2s2dXI2eGxFUnd
SdmJqNUkwd3UyTUw0R2ZWU3dvYmhick80aHBnK0txbFdRNEExb1pWUzlMUXlLTGZBSFF1NmplRW9WYmZLK1Ntb3BCZWlyeWtEUmVKUTlGbSsyditKSzhzVkhuRVA5Uy95dFNFcU
9NamN0TmJ1TFMrMlc1NWZ4RDR2ZlZLS0Nybk56ZVJPNm1YVU9UZDJxK3Rsb2ZEQ1dEY3pBK3pmaUF6ZE1xaHJ6Ly8zNGExUE1KWHJVQy81MnVBZnZ6WnpIZTEwUWtjRHgzS1dRb
210dVFUOTN5cVI5bjdHYkt1REkrbkZFWnN6MlBQYmtyWmNQU0I2c1BvaHJXazQzZjFrTUNtSTNmQWdNQkFBR2pnZ0VZTUlJQkZEQWZCZ05WSFNNRUdEQVdnQlFXT2FrYUJZbTNE
eTJ5TmUzQ0NackZBNE1pUHpBU0JnTlZIU0FFQ3pBSk1BY0dCU3RNSFFFTE1JR3RCZ05WSFI4RWdhVXdnYUl3Z1orZ2daeWdnWm1HZ1pab2RIUndjem92TDJOaGMyOW5aV2x6ZG1
sc0xuTnZaMlZwTG1sMEwyVnFZbU5oTDNCMVlteHBZM2RsWWk5M1pXSmthWE4wTDJObGNuUmthWE4wUDJOdFpEMWpjbXdtYVhOemRXVnlQVU5PSlRORVEwRXJUV2x1YVhOMFpYSn
ZLMlJsYkd4aEsxTmhiSFYwWlN0VVpYTjBKVEpEVHlVelJFMXBibWx6ZEdWeWJ5dGtaV3hzWVN0VFlXeDFkR1VsTWtOREpUTkVTVlF3SFFZRFZSME9CQllFRkUrZnFpWnkrcmFEW
nlwYUpvWXFOWlI1QkU5cU1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQU5UV0ZYOW16c2Z2ejJYTzRqL0gvUGVQdmQ5Y0Q3WFZIcFl5OEkr
Z2dxVU5TWVZhUkhpeVdGcVdrWDN2bDgyemhDeW1KS2hic2tFcGV3NktZbjYxYzdTeFNRb1hNdU01cjFYZ0VGaTg0MXpwYURoN2huT3diRkpHeVlSZVVrVFFmM3k1VDdrTmozWkR
TWmZBMmtZajBQdFJ5ZjVEUnRPZEtuMVc1ay8zUlJNSWxVRFVjQ1FTSEg5TlJVZndWVENxZnZFUjNSZTJlYmVtWGRkNnFIY0lwaDJrODVnOFZ5RlZYY1BGVHp6YUl1US92QSttUE
VWVldXeXlFV1o4NWQ2RVphNS8yODV0dEtpOENDN1VEazZJZGNjSjBsREhvNVZIVmJidEFxejFuTzVpRDN2ejg1ejE4WHdlb3h3aHhBem1SYzBFTXNHanJPaFJVTHg0ZHprUzJme
Us0VFlYSTQ0K0U2THlDenV0bWVYSmNLNjZrVVA0RCs0WmEzRnNITjJkT3RlbHkxMzIxZnZhMjE4cGZ0MFZhenYwdFJ2ZDgzZlU2NDBBS3E0bmswY3d2aFEzZnYvN3VoTXFwYkQ0
VWdHZERFVE5pNzVqa3Z5bTlqUHl1M2dWQjBiQVNxMFBiakkvZ2d4VmUzRk5VbHpzQzI2OTZGVTZqYk1WeVA4ZHM5bm0wWUVMV3M2N3Y3RGNWOUhGQkFodmFiZW1rNExOU1IvVXl
IVWtZS2wyUXNQcnlxdDloVEZFR1V0ZWxtMXo0d3NnRTJUcEJscHVyejRkNDVrQkV1YlZqdC9QSFlXZnZxTjhhTHhWU2kwYU9lMW5iMEdMb1VzQ3JaY0poeTRIQ1N0THcxSlhjWE
JyYlg3OWdkd1hwaXpQVXRkK2lOZEJJcW1mcCtFM0R6YUpNZHFNPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJETFNQTEE2N0QwNEYyMDVHXl5eJjIuMTYu
ODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJEUlMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImlzcyI6ImludGVncml0eTpTMSMxMTF
FVVJPTUVESUNBTCIsImxvY2FsaXR5IjoiMjA0NTIwMzA3Iiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiMS4wIiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb2
5lIENhbXBhbmlhIiwic3ViamVjdF9vcmdhbml6YXRpb25faWQiOiIxNTAyMDQ1MjAzMDciLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d
2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJwYXRpZW50X2NvbnNlbnQiOnRydWUsImFjdGlvbl9pZCI6IkNSRUFURSIsInJlc291cmNlX2hsN190eXBlIjoiKCcxMTUwMi0y
Xl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsInN1YmplY3RfYXBwbGljYXRpb25faWQiOiJNRURJV0VCIiwiZXhwIjoxNjgyMzMxMjEwLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3Z
lbmRvciI6IkVVUk9NRURJQ0FMIiwiaWF0IjoxNjgyMzI3NjEwLCJqdGkiOiI1NmZhNmMwYy00NmY2LTM2NDAtODFlZC0yZjg3NjAwNWEyNzIiLCJwZXJzb25faWQiOiJSU1NNUk
EyMkEwMUEzOTlaXl5eJmFtcDsyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImYW1wO0lTTyJ9.MqZEiHpt9baSV81siW_3CTN7s4qqswSioQSEGvQVrB-Ffc-E5rSkZy9fRgDM
VUKAxInKbaY58PuMSlE2WzsQOfFDg_68mSzxxybLNL7OJMEjSelsmBaTWDvoEarwZpb32TyZTMfByI3_Qyg9zWHcDqdhG3QD47_uJfoYday0G7Es24_z4V7-TmC8z65sGmvKGVF
daYErJFA5Q4XlOMUZ6YBU48YSEIa0URwf_0ROoh1-ZslHk65jKR6pfF2j7UochqBbkN_ErK64E2lmXGgvcG0oeRHb_n5eIz_DAh-4weyP96ucoalLWjs3ECryNhMcZnSclewwbs
6ixvFA-y1VWA



ricevo questa risposta:

{
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "status": 502,
    "detail": "Invalid response received from the API Implementation",
    "govway_id": "4a52f33d-e273-11ed-80ae-005056ae7395"
}

Quale è il motivo ?

**Comment by IStacchiotti** [comment]
Buongiorno, dalle verifiche risulta che non ha allegato il pdf nel request. Potreste verificare? Grazie
