### ISSUE TITLE
Indicazione valorizzazione campi Request Body e JWT

### ISSUE THREAD

**Issue by sistemiinformativi-aocz** [ministero-salute/it-fse-support#283]
Buongiorno,
ma per le regioni sussidiarietà totale come facciamo a valorizzare i seguenti campi essendo sicuri di non entrare in conflitto con altri software regionali?
• Identificativo Documento
• Identificativo Repository
• Identificativo Sottomissione
Grazie

[Slack Message](https://developersitalia.slack.com/archives/C03RDT88FSM/p1681377463220299?thread_ts=1681377463.220299&cid=C03RDT88FSM)

**Comment by calcomsrl** [comment]
Buongiorno,
possiamo avere sviluppi in merito?

**Comment by sistemiinformativi-aocz** [comment]
Buongiorno,
possiamo avere sviluppi in merito?

**Comment by masciamariotti** [comment]
Buongiorno,
può scrivere alla mail [gestionets@sogei.it](mailto:gestionets@sogei.it).

**Comment by IStacchiotti** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
