### ISSUE TITLE
Errore {"type":"https://govway.org/handling-errors/401/TokenAuthenticationFailed.html","title":"TokenAuthenticationFailed","status":401,"detail":"Invalid token","govway_id":"35a59ff9-e047-11ed-80ae-005056ae7395"}

### ISSUE THREAD

**Issue by E-SC** [ministero-salute/it-fse-support#284]
Buongiorno,
il sistema restituisce errore autenticazione.

I nostri token sono:

Auth:
eyJ0eXAiOiJKV1QiLCJ4NWMiOlsiTUlJRmFEQ0NBMUNnQXdJQkFnSVVPTEJobmxneWJMZHpwbGR4Z1x1MDAyQnJvT1dMQjlUb3dEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekEwTVRFeU1UTTBNakZhRncweU5qQTBNVEV5TVRNME1qQmFNR2t4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVIwd0d3WURWUVJoREJSRFJqcEpWQzB4TVRGRlUwTllXRmhZV0ZoWVdERWFNQmdHQTFVRUF3d1JVekVqTVRFeFJWTkRXRmhZV0ZoWVdGZ3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDbHZXb3N3QkVML0dKMXlKU1E0ZXBSbWdKcnlWL0Zpclx1MDAyQkpGWEtGNllRTXdwd2g2dWwyV0hNMm1PQlhCXHUwMDJCMEV6RTdadElYWUhYanNvelNGbW1RakxPQjFyamJJNlpPVkUvZldIYjBjcDI3OW54ZkJxNDRsYUNYMlFDXHUwMDJCM1J0eXBoaEpSRjhFREp2dGltVXZwYlFlRTRSd0plbEh4TEV1MWFJb2pYQzFHbFM1YTh2djc0dXVvNEZFZmZFcGZ2Uk1xNVU3NE9RU0NjMWFmcXgwckxWTHlvcWozbVFQcG1WMTRIMjFzUkV4cFVBMUcyMjRiWkVRVGZ1NEFFSnJuTzFWWjhqNmlHekZVSXNCVHl0ZWFIVjJkS3NhclY2RVZvSlhxRFRrUkNvelpPVjFULzBER1NXYnV4ZktLNjBoMzc2UG85R3VJbUc5Zzc4WVg5cUQ5N3libXVSZ1BBZ01CQUFHamdnRVlNSUlCRkRBZkJnTlZIU01FR0RBV2dCUVdPYWthQlltM0R5MnlOZTNDQ1pyRkE0TWlQekFTQmdOVkhTQUVDekFKTUFjR0JTdE1IUUVMTUlHdEJnTlZIUjhFZ2FVd2dhSXdnWlx1MDAyQmdnWnlnZ1ptR2daWm9kSFJ3Y3pvdkwyTmhjMjluWldsemRtbHNMbk52WjJWcExtbDBMMlZxWW1OaEwzQjFZbXhwWTNkbFlpOTNaV0prYVhOMEwyTmxjblJrYVhOMFAyTnRaRDFqY213bWFYTnpkV1Z5UFVOT0pUTkVRMEVyVFdsdWFYTjBaWEp2SzJSbGJHeGhLMU5oYkhWMFpTdFVaWE4wSlRKRFR5VXpSRTFwYm1semRHVnlieXRrWld4c1lTdFRZV3gxZEdVbE1rTkRKVE5FU1ZRd0hRWURWUjBPQkJZRUZCa2JoRFFRd2xuQldSSVAwcVBrSG5YYW8zTlVNQTRHQTFVZER3RUIvd1FFQXdJR1FEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFNOFQ1cW9oTC9DTzNtSzVqNVNsWXZxdk9hSG44OWtiRHBKSURHU1BkTWVqNzZlalhGMExOejM0bGhha2R2d2wxVDJwZ3MzaTdkUXFLaU5XSzZjR3dcdTAwMkJsajlidmVlalhNMlx1MDAyQjVlY3ljVEZGMkk4UEhDQlBnQ29KWkZIZkIwQkFZcVZCMUpwVTEzajNmbTNINkNXVEhwb25lQ1d2WXI1N2FcdTAwMkJkelx1MDAyQnM5dWFGNjlmU1NzZnRjbTJzSWRJOWRENFRKZy8yZTV3UzN0WFpJZGtDUVVtWi9cdTAwMkI4S0lTbTEyak1GYWpRUGlpMWVYNFY4blFkUzU0XHUwMDJCYThtSEh6ck5CQmtsaE5yeUU1S0ZDaEZhOHhkVVNncmx6a2Y1OTVxRllOa1h0XHUwMDJCczhWVWlJT0xZaVdwQzVrN0t2OUNQSXBCN1V2c1hiM0lEY3pFTTRTd3FUT0lidzJPWDU0c2NTTnkzRDVuS25mOHNSME9wZWVXdXRvVVNXUG95RVQxekdYdnN6M3VRRmNyeGczZTlsellNTlNvZDZWeTBudjFUWmF0d2RBaXJIWVZCVEVvb0lHbGlKelhEMjFXT2w5N0UyY1RGOWZ5d3p1RVljVWJLL0VaOUJoOWhRVnFRaFx1MDAyQlBVWkJoWHpYRlpjSHhqZGZTXHUwMDJCeUhPZUgvaDJHTER5Ulx1MDAyQmlOTVVzaURNU0JXZUZEVkY5eDd0NFBDZTBpR2tza2ZaMjBQOGVQNXpmQ2JUN0QwZ25GdkJVZFBqNTUvZ1M1Ly9PNGNtZk5JOGwzci9XaFh2SFx1MDAyQkx5WWxwOS9HZHNwYzRhVElPRVd5Y0FZUG9qM3RFRzRSRlJ3UWdidzZuV2dWeHU0ZEYxRzFDTkc0UFVEQWh6aWs3THlNd0lLb0UvaHpVamF5N0FKWC9EZ05xUmtiNVpCOHpLQ1ZTRU5WRDQ9Il0sImFsZyI6IlJTMjU2In0.eyJpc3MiOiJhdXRoOlMxIzExMUVTQ1hYWFhYWFhYIiwiaWF0IjoxNjgyMDg3MTUxLCJleHAiOjE2ODIwOTA3NTEsImp0aSI6IjE2ODIwODcxNTEiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJzdWIiOiJSUExWQ043NUQwOUg3MDNRXl5eXHUwMDI2Mi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yXHUwMDI2SVNPIn0.M3pmsDaY6EUF1iAcR-Tt5-vkqVJ6ua2KD148-lJDYq-7feGxBhPKcYEwoAvsOSkAE_dyFjqW-aDZGjBCyMX-7VborVJAF88A9h8w_jTi3ZWw0950lWQSy7Ctd18Yl1OSwNyAk3bj4EKEvnqVpGA2gGrZ4XJsyUKQtXfC9YF9ANAJ64YYVa-VEb89PFV91zES-HAIsoML2Nwf8ydNBpSFReVPFRIEyJdn23lFPJWpJYr4jNbmSkTD_SWz5pfh9INxC5BuXq93l2Qf-ibakzew0dZ78kMF4G4117ta9AwKgPu0D1KWPUbcBqBQ85730FjDBktd5xTBFItmeklhnFU31A

JWT-sign: 
eyJ0eXAiOiJKV1QiLCJ4NWMiOlsiTUlJRmFEQ0NBMUNnQXdJQkFnSVVPTEJobmxneWJMZHpwbGR4Z1x1MDAyQnJvT1dMQjlUb3dEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekEwTVRFeU1UTTBNakZhRncweU5qQTBNVEV5TVRNME1qQmFNR2t4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVIwd0d3WURWUVJoREJSRFJqcEpWQzB4TVRGRlUwTllXRmhZV0ZoWVdERWFNQmdHQTFVRUF3d1JVekVqTVRFeFJWTkRXRmhZV0ZoWVdGZ3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDbHZXb3N3QkVML0dKMXlKU1E0ZXBSbWdKcnlWL0Zpclx1MDAyQkpGWEtGNllRTXdwd2g2dWwyV0hNMm1PQlhCXHUwMDJCMEV6RTdadElYWUhYanNvelNGbW1RakxPQjFyamJJNlpPVkUvZldIYjBjcDI3OW54ZkJxNDRsYUNYMlFDXHUwMDJCM1J0eXBoaEpSRjhFREp2dGltVXZwYlFlRTRSd0plbEh4TEV1MWFJb2pYQzFHbFM1YTh2djc0dXVvNEZFZmZFcGZ2Uk1xNVU3NE9RU0NjMWFmcXgwckxWTHlvcWozbVFQcG1WMTRIMjFzUkV4cFVBMUcyMjRiWkVRVGZ1NEFFSnJuTzFWWjhqNmlHekZVSXNCVHl0ZWFIVjJkS3NhclY2RVZvSlhxRFRrUkNvelpPVjFULzBER1NXYnV4ZktLNjBoMzc2UG85R3VJbUc5Zzc4WVg5cUQ5N3libXVSZ1BBZ01CQUFHamdnRVlNSUlCRkRBZkJnTlZIU01FR0RBV2dCUVdPYWthQlltM0R5MnlOZTNDQ1pyRkE0TWlQekFTQmdOVkhTQUVDekFKTUFjR0JTdE1IUUVMTUlHdEJnTlZIUjhFZ2FVd2dhSXdnWlx1MDAyQmdnWnlnZ1ptR2daWm9kSFJ3Y3pvdkwyTmhjMjluWldsemRtbHNMbk52WjJWcExtbDBMMlZxWW1OaEwzQjFZbXhwWTNkbFlpOTNaV0prYVhOMEwyTmxjblJrYVhOMFAyTnRaRDFqY213bWFYTnpkV1Z5UFVOT0pUTkVRMEVyVFdsdWFYTjBaWEp2SzJSbGJHeGhLMU5oYkhWMFpTdFVaWE4wSlRKRFR5VXpSRTFwYm1semRHVnlieXRrWld4c1lTdFRZV3gxZEdVbE1rTkRKVE5FU1ZRd0hRWURWUjBPQkJZRUZCa2JoRFFRd2xuQldSSVAwcVBrSG5YYW8zTlVNQTRHQTFVZER3RUIvd1FFQXdJR1FEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFNOFQ1cW9oTC9DTzNtSzVqNVNsWXZxdk9hSG44OWtiRHBKSURHU1BkTWVqNzZlalhGMExOejM0bGhha2R2d2wxVDJwZ3MzaTdkUXFLaU5XSzZjR3dcdTAwMkJsajlidmVlalhNMlx1MDAyQjVlY3ljVEZGMkk4UEhDQlBnQ29KWkZIZkIwQkFZcVZCMUpwVTEzajNmbTNINkNXVEhwb25lQ1d2WXI1N2FcdTAwMkJkelx1MDAyQnM5dWFGNjlmU1NzZnRjbTJzSWRJOWRENFRKZy8yZTV3UzN0WFpJZGtDUVVtWi9cdTAwMkI4S0lTbTEyak1GYWpRUGlpMWVYNFY4blFkUzU0XHUwMDJCYThtSEh6ck5CQmtsaE5yeUU1S0ZDaEZhOHhkVVNncmx6a2Y1OTVxRllOa1h0XHUwMDJCczhWVWlJT0xZaVdwQzVrN0t2OUNQSXBCN1V2c1hiM0lEY3pFTTRTd3FUT0lidzJPWDU0c2NTTnkzRDVuS25mOHNSME9wZWVXdXRvVVNXUG95RVQxekdYdnN6M3VRRmNyeGczZTlsellNTlNvZDZWeTBudjFUWmF0d2RBaXJIWVZCVEVvb0lHbGlKelhEMjFXT2w5N0UyY1RGOWZ5d3p1RVljVWJLL0VaOUJoOWhRVnFRaFx1MDAyQlBVWkJoWHpYRlpjSHhqZGZTXHUwMDJCeUhPZUgvaDJHTER5Ulx1MDAyQmlOTVVzaURNU0JXZUZEVkY5eDd0NFBDZTBpR2tza2ZaMjBQOGVQNXpmQ2JUN0QwZ25GdkJVZFBqNTUvZ1M1Ly9PNGNtZk5JOGwzci9XaFh2SFx1MDAyQkx5WWxwOS9HZHNwYzRhVElPRVd5Y0FZUG9qM3RFRzRSRlJ3UWdidzZuV2dWeHU0ZEYxRzFDTkc0UFVEQWh6aWs3THlNd0lLb0UvaHpVamF5N0FKWC9EZ05xUmtiNVpCOHpLQ1ZTRU5WRDQ9Il0sImFsZyI6IlJTMjU2In0.eyJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExRVNDWFhYWFhYWFgiLCJpYXQiOjE2ODIwODcxNTMsImV4cCI6MTY4MjA5MDc1MywianRpIjoiMTY4MjA4NzE1MyIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInN1YiI6IlJQTFZDTjc1RDA5SDcwM1FeXl5cdTAwMjYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjJcdTAwMjZJU08iLCJzdWJqZWN0X29yZ2FuaXphdGlvbl9pZCI6IjE1MCIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBDYW1wYW5pYSIsImxvY2FsaXR5IjoiMjA3MTExMTExIiwic3ViamVjdF9yb2xlIjoiRFJTIiwicGVyc29uX2lkIjoiQk5YTlhYMzRDMTRGMjA1U15eXlx1MDAyNjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMlx1MDAyNklTTyIsInBhdGllbnRfY29uc2VudCI6dHJ1ZSwicHVycG9zZV9vZl91c2UiOiJUUkVBVE1FTlQiLCJhY3Rpb25faWQiOiJDUkVBVEUiLCJyZXNvdXJjZV9obDdfdHlwZSI6IihcdTAwMjc2ODYwNC04Xl4yLjE2Ljg0MC4xLjExMzg4My42LjFcdTAwMjcpIiwiYXR0YWNobWVudF9oYXNoIjoiaUJhRjBJYllra3paWkVEb1x1MDAyQjdsTTJsZmNBRkN2dlNSL3lvb1kxMlBFQlZjPSIsInN1YmplY3RfYXBwbGljYXRpb25faWQiOiJSQURYIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZW5kb3IiOiJFLVNDIFNSTCIsInN1YmplY3RfYXBwbGljYXRpb25fdmVyc2lvbiI6IlYuOSJ9.VuOuGZOgpf9bwFolPVTTrEWLF6a_2OMYVkjSEKSnd5445skQCWmHzjP514RKe3xUGgzz4hdROIFy7ya8lfwDtqyZWkfJU0N4WfEjdliYDsZW-sgji2ACB2tDW1GJC3fMEFVOXOxBwBLQjAXxecmCA5g-qJALJ79tY3rDLB2UEMoZrbUz5ZairYTIDs9MGCC7IvTUfK4iVMRz5BhVmKcsGMmyYloKIWo_JPhtiAUC48Pm0rFcFAVUr3L1m2PUG6Fh0EdZOI-5TIvvPOlSUWb58u3Mjk5UGI5ueOxosNa2V-4drP8ZCE15f7L9PRNmvn-xa7oOSLcrjbfLimriEql-CQ

I token risultano validi su jwt.io

Grazie di un vostro supporto

**Comment by IStacchiotti** [comment]
Buon pomeriggio, di seguito riportiamo l'errore registrato a sistema nei log: "Process 'x5c' error: parsing issue: long form definite-length more than 31 bits". Ci conferma inoltre che per la generazione dei token state utilizzando il tool messo a disposizione sul portale? Grazie

**Comment by E-SC** [comment]
Buongiorno,
grazie per la risposta.

Abbiamo generato i token con i vostri appplicativi.
Da un confronto del certificato trasferito nel tag x5c e ricavato dal token in jwt.io con quello da voi ottenuto via email non si nota alcuna differenza nel confronto:
![image](https://user-images.githubusercontent.com/127778539/235139323-9edc481f-45dc-40f8-b2de-237a6b363b29.png)

Grazie di un supporto

**Comment by IStacchiotti** [comment]
Buongiorno, potrebbe verificare che sta utilizzando i certificati p12 generati a partire dai pem ricevuti via email? La rimandiamo a questo [link ]( https://developersitalia.slack.com/archives/C03RDT88FSM/p1681817149022559)su Slack, in cui sono stati spiegati gli step passo passo.

**Comment by E-SC** [comment]
Buongiorno,
vi comunichiamo che dalle ore 9.30 circa di stamattina l'autenticazione viene eseguita da tutte e tre le nostre interfacce applicative che utilizzano librerie differenti ma che fino alla scorsa settimana ricevevano tutte lo stesso errore di autenticazione.
Ora vengono segnalati warning sui dati CDA ma non più l'errore di autenticazione e pertanto riteniamo risolto il task.
Solo per capire: siccome da parte nostra nulla è stato modificato dalla settimana scorsa in merito ai certificati ed alla firma dei token c'erano problemi sui certificati?
Grazie del supporto

Saluti
