### ISSUE TITLE
Problema in fase di pubblicazione dopo validazione

### ISSUE THREAD

**Issue by greglombardi** [ministero-salute/it-fse-support#285]
Buongiorno stiamo effettuando i test sulla pubblicazione pre accreditamento, ma stiamo riscontrando un errore:

 Invalid date/time format: "19041950": Expected character '-' at index 4 but found 1
 
Il campo che contiene questo dato è <birthTime value="19041950"/> ma cambiandolo come lo vuole la pubblicazione non ci passa più la validazione.

Attualmente il procedimento che facciamo è questo:

1. Creazione XML (Con legalAuth)
2. Passaggio dati dentro Validazione
3. Firma del documento (Utilizziamo un nome fittizio di test)
4. Chiamata a Pubblicazione 

Abbiamo scritto anche su SLACK https://developersitalia.slack.com/archives/C03RDT88FSM/p1682089657018879 e avremmo bisogno di una risposta risolutiva il prima possibile.

Grazie

**Comment by IStacchiotti** [comment]
Buongiorno @greglombardi, come indicato su Slack, la invitamo a modificare il formato del campo _birthTime_ come riportato di seguito: "yyyyMMdd", in coerenza con i CDA di esempio. Ci faccia sapere se il problema persiste, grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, abbiamo evidenza da Slack che l'errore è stato risolto con il formato indicato. Pertanto procediamo con la chiusura del presente. Grazie
