### ISSUE TITLE
Mancato accreditamento per obbligatorietà di campi opzionali

### ISSUE THREAD

**Issue by domenico-capezzuto** [ministero-salute/it-fse-support#286]
Buongiorno,

relativamente al mancato accreditamento a seguito della pull-request [223](https://github.com/ministero-salute/it-fse-accreditamento/pull/223), avremmo bisogno di chiarimenti circa i campi obbligatori.

Ad esempio, per il test case 1 OK del VPS viene contestata l'assenza delle sezioni

- `ClinicalDocument/component/structuredBody/component/section[@ID="Triage"]/entry/observation/performer`
- `ClinicalDocument/component/structuredBody/component/section[@ID="Dimissione"]/entry/act/entryRelationship` (encounter post dimissione)
- `ClinicalDocument/component/structuredBody/component/section[@ID="Dimissione"]/entry/observation`

che da specifiche HL7 sono opzionali, così come risultano opzionali sull'Excel,
ma la loro assenza pregiudica l'accreditamento.
Opzionalità peraltro giustificata perché un paziente inviato al curante non è né ricoverato, né trasferito ad altra struttura,
rendendo di fatto impossibile compilare l'encounter 2.16.840.1.113883.2.9.10.1.6.67.

Come ci dobbiamo comportare?
Grazie.

**Comment by IStacchiotti** [comment]
Buonasera, le confermiamo che può indicare come non applicabile il test in questione. Nel caso in cui non riusciste ad indicare come applicabile alcun caso di test OK, al fine di verificare la corretta comunicazione con il Gateway per il processo di accreditamento, sarebbe necessario che ci forniste timestamp-traceid-workflowinstanceid di una invocazione recente effettuata verso il Gateway e che abbia ricevuto un esito positivo.
Si comunica inoltre che, per ovviare in futuro a tale problematica, sarà pubblicata una nuova checklist con l'introduzione di un caso di test OK che non richieda il popolamento di dati opzionali secondo HL7 Italia.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Mancato accreditamento per obbligatorietà di campi opzionali (Issue #286)" inviata il 15/05/2023 14:50:39. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, grazie per il riscontro. Le confermiamo che risulta coerente quanto condiviso. Chiudiamo pertanto il presente ticket, dal momento che riceverà aggiornamenti via email riguardo alla richiesta di accreditamento. Grazie.
