### ISSUE TITLE
Chiarimento specifiche CDA Referto di Radiologia

### ISSUE THREAD

**Issue by rangeletti** [ministero-salute/it-fse-support#288]
Buongiorno,

Avremmo necessita di un chiarimento in merito alle specifiche per la generazione del CDA del referto di Radiologia. 

Consultando i test case relativi all'accreditamento FSE 2.0 abbiamo questa situazione. 

**Radiologia** 

[https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/1-Referto%20di%20Radiologia/CDA2_Referto_di_Radiologia_OK.xlsx](https://eu-central-1.protection.sophos.com/?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL21pbmlzdGVyby1zYWx1dGUvaXQtZnNlLWFjY3JlZGl0YW1lbnRvL2Jsb2IvbWFpbi9UZXN0JTIwQ2FzZS9WYWxpZGF6aW9uZS8xLVJlZmVydG8lMjBkaSUyMFJhZGlvbG9naWEvQ0RBMl9SZWZlcnRvX2RpX1JhZGlvbG9naWFfT0sueGxzeA==&p=m&i=NjIyNzcxMjZkNmU3MDExMGZmNDM4MmZl&t=MS9oR2lqM2h5OFFZR1JNT0dKdUVCTTRnN0J6T3NlMTlDOFFkdmVrRCtQUT0=&h=9d382bd9072b46339970312b1fac0fcf&s=AVNPUEhUT0NFTkNSWVBUSVaibKL2HsjukKz97CZduiWGWHXCUYQhg40JsfsTQoTLzw)   

La sezione delle prestazioni ci risulta essere: 

ClinicalDocument/component/structuredBody/component/section[@ID=Esame_eseguito] 

**Il codice prestazione dovrebbe essere inserito nei campi dell'oggetto entry su ClinicalDocument/component/structuredBody/component/section[@ID=Esame_eseguito]/ entry, la cui cardinalità è 1...1** 

Sembra quindi che non possano esserci più entry per la sezione Esame_Eseguito.

**Nella radiologia si verifica però sovente che si co-refertino due esami, per cui ad oggi si producono CDA contenenti più di una /entry, una per ogni esame co-refertato.**

**Abbiamo verificato che il Gateway di test valida correttamente i CDA contenenti più entry, pertanto riteniamo che ci sia un errore nelle specifiche e che la cardinalità dell'elemento debba essere n:**
ClinicalDocument/component/structuredBody/component/section[@ID=Esame_eseguito]/entry debba essere 1...*.

Segnalo inoltre che per i referti ambulatoriali le specifiche prevedono la presenza di più prestazioni, come di seguito riportato:

Ambulatorio 
[https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/7-Referto%20Specialistico%20Ambulatoriale/CDA2_Referto_Specialistica_Ambulatoriale_OK.xlsx](https://eu-central-1.protection.sophos.com/?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL21pbmlzdGVyby1zYWx1dGUvaXQtZnNlLWFjY3JlZGl0YW1lbnRvL2Jsb2IvbWFpbi9UZXN0JTIwQ2FzZS9WYWxpZGF6aW9uZS83LVJlZmVydG8lMjBTcGVjaWFsaXN0aWNvJTIwQW1idWxhdG9yaWFsZS9DREEyX1JlZmVydG9fU3BlY2lhbGlzdGljYV9BbWJ1bGF0b3JpYWxlX09LLnhsc3g=&p=m&i=NjIyNzcxMjZkNmU3MDExMGZmNDM4MmZl&t=M3lGZzRaWFZRL1FtNEFKZkNPRUNOWnVBeEdMVHNiTkVUbk1PRlpLWE9RRT0=&h=9d382bd9072b46339970312b1fac0fcf&s=AVNPUEhUT0NFTkNSWVBUSVaibKL2HsjukKz97CZduiWGWHXCUYQhg40JsfsTQoTLzw) 

La sezione delle prestazioni ci risulta essere: 
ClinicalDocument/component/structuredBody/component/section[@ID=Prestazioni] 

I codici prestazione dovrebbero essere inseriti nei campi dell'oggetto  entry  su ClinicalDocument/component/structuredBody/component/section[@ID=Prestazioni]/entry, la cui cardinalità è  1...* quindi possiamo gestirne n per referto.

**Sarebbe possibile un riscontro?**

Grazie,
un saluto,
Rachele

**Comment by IStacchiotti** [comment]
Buonasera, grazie della segnalazione.
Si conferma che da specifiche è possibile inserire più entry relative alla sezione "Esame Eseguito", e al fine di riprodurre correttamente i casi di test OK è stato pensato l'inserimento di una entry con la relativa descrizione dell'esame in oggetto per quello specifico test case.

**Comment by IStacchiotti** [comment]
Buonasera, procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
