### ISSUE TITLE
CDA2 di laboratorio alberatura XML consentita

### ISSUE THREAD

**Issue by AndreaLev84** [ministero-salute/it-fse-support#29]
Buongiorno,
la mia domanda è in merito all'alberatura proposta del XML CDA2, quella mostrata nel file è l'unica valida?
Perché prendendo come riferimento le linee guida HL7 Italia per una CDA2 di laboratorio di Marzo 2022 per quanto riguarda il campo structuredBody per esempio viene lasciata libertà se mettere i campi section come foglie o meno.

Nel codice condiviso vedo che vengono messe come foglie e non capisco se questo esempio è il punto di riferimento che integra le linee guida HL7 o vale ancora quando indicato e quindi la possibilità di aggiungere le section non come foglie?

Grazie,
Andrea

**Comment by LeonardoAlcaro** [comment]
Buongiorno Andrea, 
la guida HL7 Italia è una guida standard HL7 CDA Rel 2.0 valida nel contesto italiano come riportato e non solo per FSE2.0 ma per cooperare con quest'ultimo occorre rispettare la sintassi prevista nei coreschemas e  schematron che rispettano la guida, per quanto concerne invece gli esempi sono soltanto esempi di CDA2 validi che rispettano la sintassi.

Leonardo
