### ISSUE TITLE
Accreditamento EBIT SRL

### ISSUE THREAD

**Issue by EbitFSE** [ministero-salute/it-fse-support#291]
Buongiorno, abbiamo apportato le correzioni come richiesto via mail e creato la PR [https://github.com/ministero-salute/it-fse-accreditamento/pull/335](url).
Rimaniamo in attesa di un feedback,
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che la pull request è stata presa in carico. Procediamo pertanto alla chiusura del presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
