### ISSUE TITLE
Accreditamento soluzione HCSUITE

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#292]
Buongiorno,
volevamo notificare il caricamento completato dei test case per la soluzione HCSUITE:

https://github.com/ministero-salute/it-fse-accreditamento/pull/340

Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che la pull request #340 è stata recepita e presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
