### ISSUE TITLE
file data.json per gtw-certifier

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#293]
Buongiorno,
la struttura del file data.json per gtw-certifier è la stessa dell'accreditamento?

Non avendo fatto chiamate al gateway di test, non mi è chiaro come valorizzare traceId e workflowInstanceId.
Si possono omettere queste chiavi o usare valori "fake"?
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che la struttura del file data.json rimane invariata e che può utilizzare valori "fake" oppure in alternativa può lasciare i campi _blank_.

**Comment by ponsilva** [comment]
Molte grazie per il chiarimento
