### ISSUE TITLE
Dubbi su mancato accreditamento (CERT_VACC - Caso di Test 16) - pull request #317

### ISSUE THREAD

**Issue by DavideGuidotti** [ministero-salute/it-fse-support#296]
In seguito alla nostra ultima pull request ci è stato restituito questo errore:
```
[ {
  "id" : 16,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='043' attribute='code' actual = '30973-2' expected = '85714-4 59784-9'>ClinicalDocument/component/structuredBody/component/section[ID='Certificato_Vaccinale']/entry/substanceAdministration/entryRelationship/observation/code</error>"
} ]
```

Cioè, la procedura di validazione si aspettava un caso relativo a una vaccinazione non erogata.
Il caso d'uso 16 (vale a dire il caso 1 nel documento "casi di test CERT_VACC.docx" però non richiede specificatamente che venga mandata una vaccinazione di questo tipo, mi chiedevo quindi se il meccanismo automatico avesse fatto confusione per l'assenza di altri dati.

Sottolineo che si tratta di uno dei due casi già discussi in #280, nella ultima pull request abbiamo aggiunto i campi che da specifiche risultavano facoltativi e per cui abbiamo ricevuto errori, ma poi ci è stato restituito questo nuovo errore che in precedenza non era stato segnalato.

**Comment by DavideGuidotti** [comment]
Chiudo la segnalazione in quanto presumo che il problema non sussista più in seguito alla risoluzione di #280

**Comment by DavideGuidotti** [comment]
Riapro la segnalazione, in quanto, come scritto nella issue #314 il problema segnalato in questo issue sussuste ancora ed è in via di risoluzione.

**Comment by IStacchiotti** [comment]
Buonasera Davide, abbiamo analizzato la situazione del suo applicativo e ci risulta che solo il caso di test 16 è andato in errore. I test dovrebbero soddisfare esattamente i requisiti riportati nell'excel, anche gli opzionali. Dal momento che l'applicativo in questione presenta altri casi di test OK conclusi con successo, può dichiarare il 16 come non applicabile e risottomettere la pull request. Prossimamente verrà introdotto un nuovo caso di test, con cui verrà risolta l'anomalia segnalata. Grazie

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Dubbi su mancato accreditamento (CERT_VACC - Caso di Test 16) - pull request #317 (Issue #296)" inviata il 15/05/2023 18:18:10. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Dubbi su mancato accreditamento (CERT_VACC - Caso di Test 16) - pull request #317 (Issue #296)" inviata il 15/05/2023 20:10:10. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
