### ISSUE TITLE
400 - Verifica hash fallita.

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#299]
Buongiorno

Stiamo integrando le funzionalità messe a disposizione.
Dopo l'ok della validazione riscontriamo l'errore in oggetto in fase di pubblicazione. E' possibile avere delucidazioni in merito?

Di base, abbiamo il referto e il documento cda.
Il cda viene iniettato nel documento pdf e quest'ultimo inviato.
Il jwt di pubblicazione aggiunge il campo attachment_hash, valorizzato con l'hash del documento CDA, tutto minuscolo.

C# è il linguaggio di programmazione, dotnet5 il framework.
Segue la funzione utilizzata per il calcolo dell'hash.

```
using (var sha256 = new SHA256Managed())
{
    var hash = sha256.ComputeHash(File.ReadAllBytes(cdaFilename));

    var sb = new StringBuilder(hash.Length * 2);
    foreach (byte b in hash) sb.Append(b.ToString("X2"));

    return sb.ToString();
}
```

documents/validation (nel _req, presenti i due jwt)
status: 201
traceID: d738ef757b959292
spanID: d738ef757b959292

[T1V1_validation_req.txt](https://github.com/ministero-salute/it-fse-support/files/11365142/T1V1_validation_req.txt)
[T1V1_validation_res.txt](https://github.com/ministero-salute/it-fse-support/files/11365143/T1V1_validation_res.txt)

documerts (nel _req, presenti i due jwt)
status: 400
traceID: e3d93b12eb7a1111
spanID: e3d93b12eb7a1111

GovWay-Message-ID: bb8d2575-85eb-4aff-b59a-cbf7ec2ca607
GovWay-Transaction-ID: 9998d785-e803-11ed-8882-005056ae54fa

[T1V1_publication_res.txt](https://github.com/ministero-salute/it-fse-support/files/11365146/T1V1_publication_res.txt)
[T1V1_publication_req.txt](https://github.com/ministero-salute/it-fse-support/files/11365147/T1V1_publication_req.txt)

**Comment by IStacchiotti** [comment]
Buongiorno, il campo attachment_hash nel jwt va valorizzato con l'hash del pdf fornito in input. Ci faccia sapere se il problema persiste. Grazie mille

**Comment by ds-tommaso** [comment]
Ok, immaginavo venisse controllato il documento CDA.

Tutto ok ora.

{"traceID":"5cbfd610bc7aa1ec","spanID":"5cbfd610bc7aa1ec","status":201,"workflowInstanceId":"2.16.840.1.113883.2.9.2.160.4.4.91f6bd2e0b406dfa346c69d32ca671dfcd14efb3499e663aaf33a0ecac4bbafc.6c985f62e5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

**Comment by ds-tommaso** [comment]
Chiudo l'issue
