### ISSUE TITLE
Schematron LDO - riga 93 Messaggio errore 14

### ISSUE THREAD

**Issue by giuseppe-fasulo** [ministero-salute/it-fse-support#3]
Salve. Probabilmente il messaggio di errore 14 nella sua seconda parte è errato laddove dice .. "mentre @codeSystem delve essere uguale a 2.16.840.1.113883.5.1", perché l'asserzione testa solo i valori dell'attributo administrativeGenderCode. 
Inoltre il controllo sul valore corretto dell'OID è testato nella successiva asserzione che genera il messaggio di errore 15.

**Comment by zukka77** [comment]
Grazie della segnalazione, faremo un controllo agli esperti di schematron

**Comment by gndibiase** [comment]
Si tratta di un refuso nel testo del messaggio associato all’errore in questione. Verrà corretto il messaggio dell’errore, cercando di essere più puntuali e distinguendo la valorizzazione degli attributi associati ad un elemento.
Grazie per la segnalazione
