### ISSUE TITLE
Errore di validazione su campi multipli 

### ISSUE THREAD

**Issue by AndreaLev84** [ministero-salute/it-fse-support#30]
Buongiorno,

facendo una verifica su un CDA2 usando lo schematron proposto ottengo degli errori che non dovrebbero esserci.
Faccio degli esempi in merito:
1 Almeno un elemento 'templateId' DEVE essere valorizzato attraverso l'attributo @root='2.16.840.1.113883.2.9.10.1.1
2 L'elemento 'telecom' DEVE contenere l'attributo @use

Per il primo punto il CDA2 validato contiene più elementi templateId (come consentito dalle linee guida) di cui uno ha la root richiesta, però la validazione torna comunque questo errore.
Mentre per il secondo caso (telecom) sembra che la verifica controlli anche gli elementi non associati al paziente (es author)

Il problema è noto?

Grazie,
Andrea

**Comment by LeonardoAlcaro** [comment]
Ciao Andrea,
il template a cui fai riferimento è Identificativo del template HL7 obbligatorio da guida hl7.
Tale template è importante anche per motivi di interoperabilità identificando anche il metadato di affinity Domain XDSDocumentEntry.formatCode.
Per l’aderenza alla guida HL7 laboratorio, l’attributo @root di almeno un elemento ClinicalDocument/templateId DEVE essere valorizzato con 2.16.840.1.113883.2.9.10.1.1 ed il relativo attributo @extension DEVE essere valorizzato con “1.3”.
Essa e' una CONF nella guida e quindi va rispettata.
Per il punto relativo al campo telecom secondo la guida implementativa Header HL7 Italia i numeri di telefono,
codificati con il tag telecom, sono caratterizzati dall’attributo use, occore rispettarla.

Leonardo
