### ISSUE TITLE
CDA2 Radiologia: Problema con sezione "entry" Esami Eseguiti

### ISSUE THREAD

**Issue by fabiodap** [ministero-salute/it-fse-support#304]
buongiorno,

ho generato un CDA di Radiologia.
In allegato il file completo:
[CDA2_8037988.txt](https://github.com/ministero-salute/it-fse-support/files/11373227/CDA2_8037988.txt

Validandolo con lo schematron (schematronFSE_RAD.sch) restituisce il seguente errore:

_'/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][4]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][1]' has an invalid token._

Non riesco a capire cosa non gli piaccia.

La sezione interessata é questa, in particolare la "entry":

			<component>
				<section>
					<code code="55111-9" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" codeSystemVersion="2.19" displayName="Descrizioni attuale procedure di imaging"/>
					<title>Esame Eseguito</title>
					<text>
						<table>
							<thead>
								<tr>
									<th>Codice Esame Eseguito</th>
									<th>Descrizione Esame Eseguito</th>
									<th>Dose Assorbita</th>
									<th>Data Esame Eseguito</th>
								</tr>
							</thead>
							<tbody>
								<tr ID="Esame1">
									<td ID="EsameDesc1">117</td>
									<td>RX RINOFARINGE (ES. DIRETTO)</td>
									<td/>
									<td>20/04/2023 09:54</td>
								</tr>
							</tbody>
						</table>
					</text>
					<entry typeCode="DRIV">
						<act classCode="ACT" moodCode="EVN">
							<code code="117" codeSystem="2.16.840.1.113883.2.9.2.42101.6.11" codeSystemName="RIS" displayName="RX RINOFARINGE (ES. DIRETTO)">
								<originalText>
									<reference value="#EsameDesc1"/>
								</originalText>
							</code>
							<text>
								<reference value="#Esame1"/>
							</text>
							<statusCode code="completed"/>
							<effectiveTime value="20230420215427+0200"/>
						</act>
					</entry>
				</section>
			</component>

Cordialmente,
Fabio

**Comment by fabiodap** [comment]
buongiorno,

nel frattempo ho proceduto a fare alcune modifiche. Non avendo una codifica ICDM-9 per gli esami, ma solo la codifica dell'ente, ho tolto i dati dell'esame dal  e ho messo solo la translation.

Ho fatto alcuni altri aggiustamenti.

      <component>
        <section>
          <code code="55111-9" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" codeSystemVersion="2.19" displayName="Descrizioni attuale procedure di imaging"/>
          <title>Esame Eseguito</title>
          <text>
            <table>
                <thead>
                    <tr>
                        <th>Codice Esame Eseguito</th>
                        <th>Descrizione Esame Eseguito</th>
                        <th>Dose Assorbita</th>
                        <th>Data Esame Eseguito</th>
                    </tr>
                </thead>
                <tbody>
                    <tr ID="Esame1">
                        <td ID="EsameDesc1">117</td>
                        <td>RX RINOFARINGE (ES. DIRETTO)</td>
                        <td/>
                        <td>20/04/2023 09:54</td>
                    </tr>
                </tbody>
            </table>
          </text>
          <entry typeCode="DRIV">
            <act classCode="ACT" moodCode="EVN">
              <code>
                <originalText><reference value="#EsameDesc1"/></originalText>
                <translation code="117" codeSystem="2.16.840.1.113883.2.9.2.42101.6.11" codeSystemName="RIS" displayName="RX RINOFARINGE (ES. DIRETTO)"/>
              </code>
              <text><reference value="#Esame1"/></text>
              <statusCode code="active"/>
              <effectiveTime value="20230420215427+0200"/>
            </act>
          </entry>
        </section>
      </component>

quando valido con lo schematron ottengo:

<?xml version="1.0" encoding="UTF-16"?>
<log>

  <file done="true" is_schema="false" path="C:\Progetti SVN\intgr_trento\doc\CDA-Repository\CDA_8037988.xml" schema_dtd_ref="false" time="Wed May  3 15:46:41 2023" valid="false">
    <general>Checked against C:\Progetti SVN\intgr_trento\doc\CDA-Repository\schematronFSE_RAD.sch</general>
    <results>
      <result type="message">
        <position col="0" line="0"/>
        <description><![CDATA[W005 | Sezione Esame Eseguito: l'entry/act/code può essere valorizzato secondo i sistemi di codifica
                  LOINC @codeSystem='2.16.840.1.113883.6.1'
                  ICD-9-CM @codeSystem='2.16.840.1.113883.6.103']]></description>
        <xpath>/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][4]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][1]</xpath>
      </result>
    </results>
  </file>

</log>

Ma che a questo punto da quello che ho capito dovrebbe essere solo una warning.

**Comment by IStacchiotti** [comment]
Buonasera, in relazione al primo messaggio, a seguito di un'analisi dell'xml fornito, abbiamo verificato che l'errore che restituisce sul token non dipende dallo schematron ma potrebbe dipendere dal mancato tag di apertura "ClinicalDocument" nella riga 2. Potrebbe verificare? Grazie

**Comment by fabiodap** [comment]
Buonasera, l'xml validato con lo schematron aveva il tag clinicaldocument. ho fatto un errore nel copiarlo nel file poi qui postato.
Gli errori erano altrove. comunque il problema è risolto.
Saluti,
Fabio

**Comment by IStacchiotti** [comment]
Buongiorno, grazie per il feedback. La presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
