### ISSUE TITLE
Accreditamento soluzione IM-LISA

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#305]
Buongiorno,
volevamo notificare il caricamento completato dei test case per la soluzione IM-LISA:

https://github.com/ministero-salute/it-fse-accreditamento/pull/347

Grazie

**Comment by IStacchiotti** [comment]
Buonasera Elisabetta, le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
