### ISSUE TITLE
Errore PDF_UNEXPECTED_CDA in accreditamento

### ISSUE THREAD

**Issue by medarchiver** [ministero-salute/it-fse-support#309]
Buongiorno,

riceviamo l'errore PDF_UNEXPECTED_CDA in accreditamento:

`[ {
  "id" : 6,
  "error" : "PDF_UNEXPECTED_CDA",
  "description" : "CDA contenuto nel PDF non conforme a quello associato al TraceID"
}, {
  "id" : 7,
  "error" : "PDF_UNEXPECTED_CDA",
  "description" : "CDA contenuto nel PDF non conforme a quello associato al TraceID"
}, {
  "id" : 8,
  "error" : "PDF_UNEXPECTED_CDA",
  "description" : "CDA contenuto nel PDF non conforme a quello associato al TraceID"
}, {
  "id" : 9,
  "error" : "PDF_UNEXPECTED_CDA",
  "description" : "CDA contenuto nel PDF non conforme a quello associato al TraceID"
} ]`

Non riusciamo a capire quale sia il problema. Potete verificare? Ci riferiamo alla pull request #345:

[https://github.com/ministero-salute/it-fse-accreditamento/pull/345](url)

Grazie.

Cordiali saluti.

**Comment by IStacchiotti** [comment]
Buongiorno, questo genere di errore si verifica quando il CDA nel pdf pushato su GitHub tramite pull request, non corrisponde a quello associato al trace id del relativo test eseguito. Potete verificare che i pdf caricati siano effettivamente quelli utilizzati nei test e che nel file json pushato su GitHub i pdf in questione siano referenziati correttamente? Grazie

**Comment by medarchiver** [comment]
Buongiorno, spero tanto che il problema non sia questo, ma guardando i file ho notato che nel data.json l'estensione dei file era ".pdf" (minuscolo) mentre i file nella cartella del repository avevano estensione ".PDF" (maiuscolo) sebbene nella cartella di sviluppo avessero l'estensione ".pdf" (minuscolo). Non ho rilevato altre anomalie. Nel dubbio ho provato a fare una nuova pull request correggendo le estensioni. E' comunque probabile che il problema sia questo perchè abbiamo cambiato il case delle estensioni per far funzionare il tool Java di prevalidazione.

**Comment by IStacchiotti** [comment]
Le confermiamo che la pull request è stata presa in carico. Lasciamo il presente ticket aperto temporaneamente, in attesa dell'esito delle verifiche automatiche sulla nuova pr. Grazie.

**Comment by medarchiver** [comment]
Salve,

abbiamo ricevuto lo stesso errore. Non riusciamo a capire quale possa essere il problema.

Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno @medarchiver, ci scusiamo per l'attesa.
Dalle analisi è emerso che per gli id 6,7,8,9 i CDA a sistema hanno il tag `</code>`, mentre quelli su GitHub hanno il tag `/>`.
Alleghiamo degli screenshot esemplificativi. Fateci sapere se riuscite a risolvere, grazie.

![Immagine 2023-05-12 101122](https://github.com/ministero-salute/it-fse-support/assets/122798799/fe69d956-8f8c-4f93-a58f-f9e818fd5e5a)
![Immagine 2023-05-12 101144](https://github.com/ministero-salute/it-fse-support/assets/122798799/d0f3b2e4-3f5c-4b04-a935-4bcadb602104)

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Errore PDF_UNEXPECTED_CDA in accreditamento (Issue #309)" inviata il 12/05/2023 10:28:42. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by medarchiver** [comment]
Buongiorno,

siete certi di aver guardato i file corretti? Noi non abbiamo in nessun documento nell'elemento "<title>" la stringa "LETTERADIDIMISSIONEOSPEDALIERA" (senza spazi) ma abbiamo invece sempre la stringa "LETTERA DI DIMISSIONE OSPEDALIERA" (con gli spazi). Non rileviamo questa differenza tra file validato e file su github. Potete inviarci cortesemente i due CDA che state confrontando?

Grazie!

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Errore PDF_UNEXPECTED_CDA in accreditamento (Issue #309)" inviata il 12/05/2023 11:02:49. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by IStacchiotti** [comment]
@medarchiver, gli spazi sono stati rimossi ai fini della verifica. L'errore riscontrato "PDF_UNEXPECTED_CDA" con ogni probabilità è dovuto alla differenza dei tag, come mostrato negli screen allegati nel mio messaggio precedente. Alleghiamo come richiesto anche i cda che sono stati oggetto di confronto. Siamo a disposizione nel caso in cui dovesse essere necessario un ulteriore supporto.
[CDA.zip](https://github.com/ministero-salute/it-fse-support/files/11463348/CDA.zip).

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Errore PDF_UNEXPECTED_CDA in accreditamento (Issue #309)" inviata il 12/05/2023 13:30:57. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by medarchiver** [comment]
Salve, in attesa di ricevere anche il file PDF utilizzato in validazione, abbiamo fatto una nuova pull request modificando il file cda2 in modo da avere la chiusura esplicita del tag <code>.

**Comment by IStacchiotti** [comment]
Buonasera, non possiamo allegare il pdf dal momento che questi non vengono salvati dal sistema. Le confermiamo comunque che la pull request è stata presa in carico. Procediamo pertanto alla chiusura del presente, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Se dovesse servirvi ulteriore supporto, c'è la possibilità riaprire il presente o in alternativa aprire una nuova segnalazione. Grazie.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Errore PDF_UNEXPECTED_CDA in accreditamento (Issue #309)" inviata il 12/05/2023 17:43:26. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.
