### ISSUE TITLE
Servizio di validazione con solo file CDA2

### ISSUE THREAD

**Issue by barbavitto** [ministero-salute/it-fse-support#31]
Il servizio di validazione descritto alla sezione 3 prevede che il  Request Body  abbia due parametri. Il primo "file" deve essere un file PDF con iniettato un Clinical Document in formato XML. Visto che ad essere validato è il CDA2 e ad essere salvato è l’hash del CDA2 non è possibile passare al servizio di validazione il solo file CDA2 al posto del pdf con iniettato il CDA"?
Grazie

**Comment by pFonziSogei** [comment]
Salve, da linee guida non è possibile inviare CDA2 diretto, accogliamo comunque l'osservazione che instaderemo verso i giusti canali

**Comment by barbavitto** [comment]
Buonasera, volevo sapere se è stato dato un seguito alla mia richiesta.
Grazie
