### ISSUE TITLE
Merge"Revisione accreditamento A1#111EXPRIVIA000 - EXPRIVIA - AURORA - 2 / ERIS -5 #221"

### ISSUE THREAD

**Issue by rangeletti** [ministero-salute/it-fse-support#310]
Buongiorno,

vorrei avere chiarimenti in merito alla Pull-request 221 (precedente issue #269) effettuata ormai un mese fa e per il quale non risulta sia stato effettuato il merge sul branch nazionale. 

![image](https://user-images.githubusercontent.com/125476691/236143674-ab3aac64-f05f-4b8a-8f0f-8c61516bc4d3.png)

La pull in questione è stata effettuata a fronte di segnalazioni di mancato accreditamento di una prima pul-request effettuata il 15-17/03. 
**Ad oggi sono passati quasi due mesi, e questa dipendenza esterna sta bloccando le attività necessarie all'adeguamento delle installazioni presso i clienti, con il rischio di non riuscire a rispettare quanto comunicato nel piano di aggiornamento.**

Restiamo in attesa di un rapido riscontro.

Un saluto,
Rachele

**Comment by IStacchiotti** [comment]
Buongiorno Rachele,
Non è stato effettuato ancora il merge dal momento che la pr in questione, la #221, contiene più applicativi e uno di questi in particolare, exprivia/aurora-adt/2, richiede una commit correttiva.
Si specifica che per rendere disgiunti i processi di accreditamento di applicativi diversi appartenenti allo stesso fornitore, sarebbe buona prassi aprire più pull request diverse, una per applicativo, seguendo le indicazioni riportate al [link](https://github.com/ministero-salute/it-fse-accreditamento).

**Comment by rangeletti** [comment]
Buongiorno,

dal link che mi ha girato non si ha evidenza di come sia possibile aprire più pull-request diverse per applicativo. Git-hub non permette di aprire più pull-request distinte ma permette di fare solo merge.

Pe quanto riguarda la commit correttiva, non è stata effettuata in quanto sono in attesa di un riscontro alla domanda inviata in risposta alla mail con oggetto: 
Mancato accreditamento (checklist) 

Relativa a cosa si intende per l'errore:

**"in seguito alla richiesta di accreditamento per exprivia/aurora-adt/2, abbiamo verificato che nei file “report-checklist.xlsx”  sono presenti degli errori che elenchiamo:

•	Occorre effettuare i check anche sui documenti di tipo VPS"**

- L'errore richiede che le checklist e il data.json della LDO e VPS siano unte in un unico file?
- Occorre unificare le due cartelle /EXPRIVIA/AURORA/2 e EXPRIVIA/AURORA-ADT/2

Restiamo in attesa di un riscontro,

Un saluto,
Rachele

**Comment by IStacchiotti** [comment]
Le daremo supporto in questo thread per consentirle di procedere nel processo di accreditamento. 
In primo luogo occorre chiarire se EXPRIVIA/AURORA/2 e EXPRIVIA/AURORA-ADT/2 sono lo stesso applicativo o se si tratta di applicativi diversi (specifichiamo infatti che la tripletta azienda-applicativo-versione rappresenta chiave nel processo di accreditamento, per cui questi applicativi al momento vengono interpretati come distinti).
Per farli procedere nel processo di accreditamento nel caso in cui siano lo stesso applicativo (supponendo che gestisca Aurora sia VPS che LDO) dovrebbe eseguire una commit per l'aggiornamento della checklist, avendo cura di: - unire le checklist popolando sia la parte di VPS che di LDO, - unire le cartelle con i file e caricare un file json cumulativo, - correggere l'errore segnalato in precedenza nei test automatici: "ID 37: E' necessario valorizzare le seguenti colonne:F, G, H, L, M, O, P;
ID 73: E' necessario valorizzare le seguenti colonne:F, G, H, I, L, M, O, P".
Ci faccia sapere se invece si tratta di due software distinti. Grazie

**Comment by rangeletti** [comment]
Buongiorno,

trattandosi di un unico applicativo abbiamo provveduto a unificare le informazioni, effettuato le correzioni come indicato ed effettuato la commit.

Resto in attesa di un riscontro,
un saluto,
Rachele

**Comment by IStacchiotti** [comment]
Perfetto, confermiamo la ricezione della commit. Quanto prima riceverà aggiornamenti sull'esito delle verifiche.  Grazie
