### ISSUE TITLE
Mancato accreditamento per data.json malformato

### ISSUE THREAD

**Issue by dmonti76** [ministero-salute/it-fse-support#311]
Buongiorno,
vorremmo chiedere aiuto per capire quale sia il problema sul data.json presentato per l'accreditamento INTERSYSTEMS TrakCare ITXX.
In seguito al primo mancato accreditamento abbiamo riverificato il file e rilevato un problema con il nome del parametro traceId (scritto con la I minuscola).
L'abbiamo corretto e risottomesso ed ora siamo sorpresi da questo nuovo problema rilevato.
Con gli strumenti che abbiamo a disposizione il file risulta corretto (validato json e Gateway Verifier).
Potreste aiutarci a capire qual è il problema così da poter procedere con la verifica dell'accreditamento vero e proprio. Oppure potete fornirci il tool da usare per verificarne la correttezza? 
In questo modo minimizzeremmo le perdite di tempo per noi ma anche e soprattutto per voi.
Grazie,
Cordiali saluti,
Daniele Monti

**Comment by dmonti76** [comment]
Buongiorno,
in attesa di gentile riscontro quanto prima, ecco gli screenshot che indicano come il data.json risulti valido:
- dal punto di vista strutturale 
![Screenshot - 08_05_2023 , 10_00_45](https://user-images.githubusercontent.com/65120663/236770270-d94554d8-330a-4d0a-ac4b-e2fdea0283c6.png)
- dal punto di vista del GTW Certifier
![Screenshot - 08_05_2023 , 09_57_51](https://user-images.githubusercontent.com/65120663/236770361-1bf5a6a4-d789-4250-9d4f-2b8a25853731.png)

Cordiali saluti,
Daniele Monti

**Comment by dmonti76** [comment]
Buona sera, 
purtroppo vedo ancora la label ON HOLD. C'è qualcosa che dobbiamo fare per sbloccare la situazione?
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, il problema sembrerebbe legato alla codifica del file pushato su git: esso non risulta essere UTF8 , ma UTF8-Bom. Potrebbe verificare? Grazie

**Comment by dmonti76** [comment]
Buongiorno, 
grazie, convertito il data.json e incluso in https://github.com/ministero-salute/it-fse-accreditamento/pull/416.
A presto
