### ISSUE TITLE
ValidationTest Error

### ISSUE THREAD

**Issue by dtsconsulting** [ministero-salute/it-fse-support#312]
Buongiorno 
risolto il problemi precedenti stiamo eseguendo i test di validazione

otteniamo questa response:
{"type":"https://govway.org/handling-errors/400/InvalidRequestContent.html","title":"InvalidRequestContent","status":400,"detail":"Request content not conform to API specification: Validation error(s) :\nbody.requestBody: Type expected 'object', found 'string'. (code: 1027)\nFrom: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.<type>\nbody.requestBody: Field 'activity' is required. (code: 1026)\nFrom: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.<required>\n","govway_id":"2da8cbd7-ea55-11ed-8882-005056ae54fa"}. Ho verificato che il body è corretto.
 Stiamo fermi non riusciamo ad andare avanti.

**Comment by IStacchiotti** [comment]
Buongiorno @dtsconsulting, segnalazioni analoghe (come quella del ticket #50) sono arrivate da utenti che utilizzavano SOAPUI per simulare le chiamate. Potreste ritentare utilizzando Postman eventualmente? Grazie

**Comment by dtsconsulting** [comment]
Grazie per la risposta.
Ho fatto il test con Postman e Funzione.
Ma dovendo sviluppare una soluzione Dts ho replicato la stessa chiamato con C#, utilizzando restSharp.

**Comment by IStacchiotti** [comment]
Ok, grazie per il riscontro. Ci conferma che è riuscito a risolvere quindi?

**Comment by dtsconsulting** [comment]
no.
Funziona solo con postMan.
In qualsiasi altro modo non Funziona.
Vi ho scritto che ho replicato quanto fatto su PostMan con c# e restSharp e non va.

**Comment by masciamariotti** [comment]
Buongiorno,
da una prima analisi ci risulta che non sta effettuando correttamente la richiesta, infatti quanto di seguito è quello che ci risulta stia inviando:
```
--b5105ff2-5552-4e89-97a9-01e20851872d
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=requestBody

{"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VALIDATION"}
--b5105ff2-5552-4e89-97a9-01e20851872d--
```
per quanto riguarda la requestBody dovrebbe correggere il content-type in application/json.
Anche il pdf non è corretto, in quanto dovrebbe avere il content-type=application/pdf
```
--b5105ff2-5552-4e89-97a9-01e20851872d
Content-Type: application/octet-stream
Content-Disposition: form-data; name="file"; filename="CDA1.pdf"
```
Potrebbe verificare e riprovare?

**Comment by dtsconsulting** [comment]
Grazie per la celere risposta.
Ho riprovato e ad funzionato.{"traceID":"c7f0d1a46af32f7e","spanID":"c7f0d1a46af32f7e","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.fe0879c68e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

**Comment by dtsconsulting** [comment]
Grazie per la celere risposta.
Ho riprovato e ad funzionato.{"traceID":"c7f0d1a46af32f7e","spanID":"c7f0d1a46af32f7e","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.fe0879c68e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}
