### ISSUE TITLE
chiarimento su sequenza pubblicazione-cancellazione documento

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#313]
Buongiorno,
vi chiedo un chiarimento riguardo a come si prevede di gestire eventuali situazioni di errore relative alla pubblicazione che avviene in modalità asincrona.

Ad esempio in questo scenario:
- un repository richiama il servizio di pubblicazione per un documento precedentemente validato dal sistema produttore
- non ci sono errori bloccanti e quindi il gateway restituisce un acknowledgment di presa in carico
- per qualche motivo la comunicazione verso INI subisce dei ritardi
- nel frattempo viene richiamato il servizio di eliminazione per lo stesso documento

Le 2 chiamate di pubblicazione ed eliminazione sono accodate? Cioè viene mantenuta la sequenza temporale in cui sono state effettuate le chiamate?
Oppure potrebbe essere che la chiamata di eliminazione del documento passi prima dell'altra? In questo caso si potrebbero creare situazioni inconsistenti.
O è invece il sistema chiamante che deve verificare lo stato della transazione di pubblicazione e accertarsi che sia in uno stato concluso prima di effettuare ulteriori chiamate di servizi relative allo stesso documento?

Grazie per le indicazioni che potrete fornire in proposito.

**Comment by masciamariotti** [comment]
Buonasera,
le confermiamo che è sempre buona prassi che sia il sistema chiamante a verificare lo stato della transazione di pubblicazione prima di procedere con ulteriori azioni sul medesimo documento.

**Comment by ponsilva** [comment]
Grazie per la precisazione.

Ci sarebbe utile poter discriminare quali sono le buone pratiche (sempre consigliate) e quali i vincoli (requisiti obbligatori) per l'utilizzo del gateway in questi scenari un po' complessi.

Forse queste indicazioni non sono ancora state esplicitate, poiché al momento il flusso previsto è quello della fase transitoria (in cui il gateway non è in produzione)?

**Comment by ponsilva** [comment]
Grazie per il riscontro
