### ISSUE TITLE
Mancato accreditamento CERT_VACC caso di test 16

### ISSUE THREAD

**Issue by DavideGuidotti** [ministero-salute/it-fse-support#314]
Apro nuovamente un ticket come siccome i problemi segnalati in #280 e #296 sembrano sussistere ancora.
Siccome #280 è stata marcata come bug ed è stata succesivamente segnalata la sua risoluzione, nella nostra nostra ultima pull request (https://github.com/ministero-salute/it-fse-accreditamento/pull/365) abbiamo impostato il CDA2in modo da omettere i 4 campi facoltativi di cui si è discusso (routeCode, approachSiteCode, participant e entryRelationship), tuttavia la procedura di validazione ha restituito errore lamentandone l'assenza.

Il recente fix quindi cosa trattava esattamente?

Sottolineo che avevamo anche provato a includere questi dati ma il sistema di validazione ha restituito errore perchè si aspettava le codifiche 85714-4 e 59784-9, utilizzate per le vaccinazioni non eseguite, che in questo caso non dovrebbero essere previste (che appunto è quanto segnalato in #296)

**Comment by IStacchiotti** [comment]
Buonasera, nel ticket [#280](https://github.com/ministero-salute/it-fse-support/issues/280) facevamo riferimento alla fix sull'elemento "`ClinicalDocument/component/structuredBody/component/section[@id] = [Certificato_Vaccinale]/entry/substanceAdministration/entryRelationship/observation/value/originalText/reference/[@value]`", dal momento che questo dovrebbe essere presente solo in caso di "Malattia con presunta immunità", quando invece i controlli automatici verificavano che il campo in questione fosse valorizzato con "Malattia con presunta immunità".

Non sono state svolte invece fix che abbiano coinvolto i 4 campi facoltativi (routeCode, approachSiteCode, participant e entryRelationship). Specifichiamo che tutti e quattro i campi sono da popolare per svolgere il test con successo.

In merito infine alle codifiche 85714-4 e 59784-9, utilizzate per le vaccinazioni non eseguite, attese erroneamente nel test, è in corso una fix per la correzione del dominio del campo `ClinicalDocument/component/structuredBody/component/section[ID='Certificato_Vaccinale']/entry/substanceAdministration/entryRelationship/observation/code</error`. Le daremo evidenza non appena sarà rilasciata in ambiente di test. Grazie

**Comment by IStacchiotti** [comment]
Buonasera Davide, le abbiamo risposto in corrispondenza del ticket #296. La rimandiamo a quel thread. Grazie

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Mancato accreditamento CERT_VACC caso di test 16 (Issue #314)" inviata il 15/05/2023 18:21:03. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by IStacchiotti** [comment]
Buonasera @DavideGuidotti, come già segnalato nel ticket #296, le confermiamo che la sua nuova pull request è stata presa in carico. Per quanto riguarda la specifica segnalazione avanzata con il presente ticket, in merito ai quattro campi opzionali (routeCode, approchSiteCode, participant e entryRelationship) di cui il tool di accreditamento controllava la valorizzazione  (sebbene opzionali da specifiche), le segnaliamo che verrà aggiunto un nuovo caso di test che prevederà solo l'inserimento degli elementi obbligatori come indicato nelle specifiche HL7; inoltre la documentazione con i casi di test verrà prossimamente meglio dettagliata. Procediamo pertanto alla chiusura del presente. Grazie per la collaborazione
