### ISSUE TITLE
Accreditamento soluzione AMICO

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#315]
Buongiorno,
volevamo notificare il caricamento completato dei test case per la soluzione AMICO:

https://github.com/ministero-salute/it-fse-accreditamento/pull/376

Grazie

**Comment by IStacchiotti** [comment]
Buonasera, le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
