### ISSUE TITLE
Urgent! 422 Errore semantico.

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#318]
Buongiorno

E' possibile avere delucidazioni in merito l'errore in oggetto?
I documenti CDA trattati passano la validazione Notepad++.
Allego il log di una transazione e 3 pdf con documento CDA iniettato che danno errore.

[LAB_CT_2withCda.pdf](https://github.com/ministero-salute/it-fse-support/files/11418885/LAB_CT_2withCda.pdf)
[LAB_CT_3withCda.pdf](https://github.com/ministero-salute/it-fse-support/files/11418886/LAB_CT_3withCda.pdf)
[LAB_CT_5withCda.pdf](https://github.com/ministero-salute/it-fse-support/files/11418889/LAB_CT_5withCda.pdf)

```
{
  "timestamp": "2023-05-08T09:25:23.9900255+02:00",
  "traceID": "9796b757f4431ca9",
  "spanID": "9796b757f4431ca9",
  "type": "/msg/semantic",
  "title": "Errore semantico.",
  "detail": "Error while executing validation on sch schematron",
  "status": 422,
  "instance": "/validation/error", 
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.150.4.4.0c3c892d239b943b3e05c0b06a5f552652de31d45f5ddb2fb96ed1a7c1c1b990.16b599cf99^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```

**Comment by ds-tommaso** [comment]
Dispongo però di altri documenti CDA che passano la validazione

**Comment by IStacchiotti** [comment]
Buongiorno Tommaso, come suggerito da Ponsilva, per escludere che si tratti di un problema di encoding, potrebbe provare a convertire i CDA in questione in UTF-8? Grazie

**Comment by ds-tommaso** [comment]
Ho creato un nuovo file e copiato il contenuto. L'esito è positivo ora.
