### ISSUE TITLE
"Record non trovato" su test PUBBLICAZIONE_SOSTITUZIONE_CDA2_VPS_CT1

### ISSUE THREAD

**Issue by fbassoPRAEZISION** [ministero-salute/it-fse-support#319]
Buon giorno, 

chiediamo chiarimenti riguardo al caso di test in oggetto.
Nel tentativo di effettuare il test, otteniamo sempre l'errore citato di cui riportiamo esempio con id di tracciamento.

```
{
	"Result": "KO",
	"Detail": {
		"traceID": "3e1927872249cb3a",
		"spanID": "3e1927872249cb3a",
		"type": "/msg/record-not-found",
		"title": "Record non trovato.",
		"detail": "No Record Found",
		"status": 404,
		"instance": "",
		"workflowInstanceId": "",
		"warning": ""
	}
}
```

Alleghiamo files relativi al documento originale ed al documento in sostituzione con relative risposte.

[cdaCreate.xml.txt](https://github.com/ministero-salute/it-fse-support/files/11419607/cdaCreate.xml.txt)
[requestBodyCreate.json.txt](https://github.com/ministero-salute/it-fse-support/files/11419612/requestBodyCreate.json.txt)
[responseCreate.txt](https://github.com/ministero-salute/it-fse-support/files/11419616/responseCreate.txt)

[cdaReplace.xml.txt](https://github.com/ministero-salute/it-fse-support/files/11419610/cdaReplace.xml.txt)
[requestBodyReplace.json.txt](https://github.com/ministero-salute/it-fse-support/files/11419614/requestBodyReplace.json.txt)
[eesponseReplace.txt](https://github.com/ministero-salute/it-fse-support/files/11419615/eesponseReplace.txt)

**Comment by fbassoPRAEZISION** [comment]
Buon giorno, 

ecco l'URL chiamato con metodo PUT
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/030702.LCNLDE90L47H501Q.20220420112426.ABCD33

**Comment by masciamariotti** [comment]
Buon pomeriggio,
da una prima analisi sembrerebbe che stia invertendo l'identificativoDoc da sostituire con quello del nuovo documento. In particolare:
- identificativoDoc presente nella requestBodyCreate:
`"identificativoDoc": "SKIP_VALIDATION_2.16.840.1.113883.2.9.2.170105.4.4^030702.LCNLDE90L47H501Q.20220420112426.ABCD33"`
- identificativoDoc presente nella requestBodyReplace:
`"identificativoDoc": "SKIP_VALIDATION_2.16.840.1.113883.2.9.2.170105.4.4^030702.LCNLDE90L47H501Q.20220420112426.ABCD33"`
- identificativoDocUpdate presente nella url del servizio di sostituzione (/v1/documents/{identificativoDocUpdate}):
`030702.LCNLDE90L47H501Q.20220420112426.ABCD33`

Da [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#6-servizio-di-sostituzione-documento): `Il parametro identificativoDocUpdate corrisponde all’OID (Object Identifier) del documento da sostituire e al parametro identificativoDoc utilizzato precedentemente nel servizio di creazione.`

Per cui l'identificativoDocUpdate presente nella url del servizio di sostizione deve essere uguale al valore dell' identificativoDoc presente nella requestBodyCreate, mentre l' identificativoDoc presente nella request del servizio di sosituzione deve essere relativo a quello del nuovo documento.

**Comment by fbassoPRAEZISION** [comment]
Buon giorno, 

abbiamo provato di nuovo:

identificativoDoc  **requestBodyCreate**:
"SKIP_VALIDATION_2.16.840.1.113883.2.9.2.170105.4.4^19710619"
[requestBodyCreate2.json.txt](https://github.com/ministero-salute/it-fse-support/files/11421930/requestBodyCreate2.json.txt)
[responseCreate2.txt](https://github.com/ministero-salute/it-fse-support/files/11421933/responseCreate2.txt)


identificativoDoc  **requestBodyReplace**:
"SKIP_VALIDATION_2.16.840.1.113883.2.9.2.170105.4.4^19710620"
[requestBodyReplace2.json.txt](https://github.com/ministero-salute/it-fse-support/files/11421932/requestBodyReplace2.json.txt)


Chiamando il metodo di replace (/v1/documents/{identificativoDocUpdate})
Con identificativoDocUpdate 19710619

https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/19710619

Otteniamo
[responseReplace2.txt](https://github.com/ministero-salute/it-fse-support/files/11421936/responseReplace2.txt)

```
{
	"Result": "KO",
	"Detail": {
		"traceID": "464ab84eda3ef05f",
		"spanID": "464ab84eda3ef05f",
		"type": "/msg/record-not-found",
		"title": "Record non trovato.",
		"detail": "No Record Found",
		"status": 404,
		"instance": "",
		"workflowInstanceId": "",
		"warning": ""
	}
}
```


Da notare che il metodo di update dei metadata ne di cancellazione del documento recepiscono l'identificativoDocUpdate da URL.

**Comment by masciamariotti** [comment]
Il valore completo dell 'identificativoDocUpdate da utilizzare è `SKIP_VALIDATION_2.16.840.1.113883.2.9.2.170105.4.4^19710619`, e non soltanto la parte finale (avendo cura di effettuare l'urlEncoding di eventuali caratteri speciali quali `^`)

Per quanto riguarda i servizi con identificativoDocUpdate in URL la rimandiamo alla documentazione al [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#2-contesto-di-riferimento).

**Comment by fbassoPRAEZISION** [comment]
Ecco il pezzo che ci mancava.

Siamo riusciti a effettuare una chiamata con successo. Grazie
