### ISSUE TITLE
ervizio di Eliminazione Documento - status": 404, "detail": "Unknown API",

### ISSUE THREAD

**Issue by glotito77** [ministero-salute/it-fse-support#320]
Buongiorno dopo la validazione documento, creazione (ma una domanda per creazione intendiamo la pubblicazione sul Repository corretto?

Request creazione:

{
   "workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.a9f4347f79cf3e1cf2ff4d79eaf6d0cf8d4a82cf3fb4e942adcc54e7fc27772e.3ee4890b67^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
   "mode":"ATTACHMENT",
   "tipologiaStruttura":"Ospedale",
   "identificativoDoc":"972",
   "identificativoRep":"2.16.840.1.113883.2.9.2.120.4.5.1234",
   "tipoDocumentoLivAlto":"REF",
   "assettoOrganizzativo":"AD_PSC029",
   "tipoAttivitaClinica":"CON",
   "identificativoSottomissione":"1726103770"
}

ack della creazione:

{
   "traceID":"4ad216640fbbd218",
   "spanID":"4ad216640fbbd218",
   "workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.a9f4347f79cf3e1cf2ff4d79eaf6d0cf8d4a82cf3fb4e942adcc54e7fc27772e.3ee4890b67^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

), 

tentando il Servizio di Eliminazione Documento, riceviamo il seguente errore: 

{
   "type":"https://govway.org/handling-errors/404/UnknownAPI.html",
   "title":"UnknownAPI",
   "status":404,
   "detail":"Unknown API",
   "X-Global-Transaction-ID":"3f7e3e2d6455408087178bfd"
}

La request si compone:
Method: DELETE
Url: https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/972
con Header:
  accept: application/json

  Authorization: Bearer eyJ4NWMiOlsiTUlJRkZ6Q0NBditnQXdJQkFnSVVDT2VLSmFRa0ZtQSs0R3YwendSR0MvSms0c1l3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TWpFeE16QXlNakkyTXpaYUZ3MHlOVEV4TXpBeU1qSTJNelZhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMweE1URkVSVVJCVEZWVE1EQXdNREVhTUJnR0ExVUVBd3dSVXpFak1URXhSRVZFUVV4VlV6QXdNREF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzREeVo5QjdMeXF6ZjdMV25YTlkzRmVIZDhjc295TzVXRlRvQlZIYkphV3Q3aTlKWkYwcmtsbnFzeEJTb2U3UmFNU2FEbFRFUGEwQU5HUGI0TkY2YzZPTDJ6VUN6akNvYkhaK1YrVUVNSXJkRC9BdU8rNldVd0tKVEI3T213ZVpkODNmb1VwY2xOdWhhVUFWcGRKa3ZRNmt0dVR6azErbCt3M2pEcWcyZDlZL1hheEtJTCt5MUNoNFROdlFLeFZQbG12MFVWNUZ4VnJjQ3BFZDBSNnluOC9laExYSjZ0NFNmQmxGY2hldURpazNZV1lvaStzeFgrdzRzQmFvWDhtb3FuRmRTNDh6aDUzRmtMMDR1b3I3WXB2VFIzQ3gyamFsZGRzM0pLRmpUOWhVckFROUw5aGc4L01FMGpQaXBWVElucXBRWFlDcEJ1S3JSTVdUay9hQWdQQWdNQkFBR2pnY2d3Z2NVd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3Y3dZRFZSMGZCR3d3YWpCb29HYWdaSVppYkdSaGNEb3ZMMk5oWkhNdVptbHVZVzU2WlM1cGRDOURUajFEUVNVeU1FMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbEpUSXdWR1Z6ZEN4UFBVMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbExFTTlTVlF3SFFZRFZSME9CQllFRlBGYS8zQzB5ODFYMVZaaUp2c21ubisyTDJsSE1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQWtSTVFKQkVkNXFVUEJ5cEtObVl4TVNBMEMvYm1LL0lweVJza2xxeEZUQ1BTeGVUNUlsTnZSRFN2Q2szMVF6YXcrb0NyMDZhaW9nU3VaQnkvT3ZBUWNqVzU0aWFsSXNVMDM5QllHaDZmTW9vN3p5RjE4L0Y3RnZjZk15K0h2all2QU1JQ3lzMk1QU3FURXQ4Y2hKcENkOFAyQWdpR0ZZWVFVdWxjZzV1NU1JdTNxdkE2ZjZRQTVwU2VyV2ExeFdEZmZtR1dQV1BEU3k5QkFIUnpTRXRoKzdPU2ZhdzVqQ0pUWS9NbDZhd0dlM3FKWjBzN0hycENzSThZbE14d1BSWG5md0pveTFWVW53RENDWDJ0K0NnVjFxa1dmZXlFaFdXWWU1dk43ZGJBYjltQVRjTklXRmQwR3RTakJOS1A3dEhTdk1vQkdJSGNxY21rSWtCRERjNUtJMHJ2RFRIdCtOUkNYeDJQNDIwcjFLNEs4K0s2T09WUXMvK2s5eUszdUVZZUlIYmZvR3FFd09BT1JpdGRNOVlkclhLL0dTQmpCbFE5TnQ0NU90d3VUQ2JKY2hVdmVacEZqdFhMS2Vpcm4wam9JTUovL1I2Ny9LZjRRa2ZRMC9xMExEdzhMdTA2dDRtT25BNExIN1FpVVEvclE5RnA2dTVWMGZrcDBRZWtleHdCUW1PeTE0T1RjeXNDM3pEMXN3ZUhWdkJvdlA1VDhsZURyWWtjSEU2WXc5SGVocU8veHcvckJjMDNtRFJxTWZXblVxTUhzVExnQnZLeHNPNG1FbGcxSGM3M0c5QzBLcXZ0NEVGNzZoczhKZE9Rdld5Q280WVdOZ1BjM1BzVnNRaHBYck1EUXVkbHBXOUxKVE9Fa0F3QWZud2tmNXhQNVhEeHpUb0ZtZHlrOEFJPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJQUlZQUlY4MEEwMUgyNTVNXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJpc3MiOiJhdXRoOlMxIzExMURFREFMVVMwMDAwIiwiZXhwIjoxNjgzMzk1MDcxLCJpYXQiOjE2ODMzMDg2NzEsImp0aSI6InVybjp1dWlkOjU2YWRjNjk5LTM2YWItNGU4Mi1hYzdiLTgzNzhiOTliZmRhZSJ9.G4URtMDhMfdqod_W1FzezriwcMSQnQmjkCaM73Ex7yi2KtiXIcjxvEi2bDTVUmBzYW7n0Vk3sFcLvq2gu9KJS2aN16Wr_RE6wYAPWEVIqbnHB8Gk-dEopiWj3wGJaCK2midO_psD9Isb4bF5PHnxkU8mTMQPZlrTbjIJLB0OFnVDxpZTlCC7pMBTJzDJI7zGydwar9YOvfSwYTDeKg2SKa09GGvq8_u0YTesXSR0GTdZtF4yn_-4aMv9SljE4RQVgQlIVL5u7f8NGRQH73yQ8jtDGjty31ivhr5238Go8d3cK79_1i-WghOtm9aFhz-6O7RprDCbktJ637w5uwZm4w

  FSE-JWT-Signature: eyJ4NWMiOlsiTUlJRkZ6Q0NBditnQXdJQkFnSVVDT2VLSmFRa0ZtQSs0R3YwendSR0MvSms0c1l3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TWpFeE16QXlNakkyTXpaYUZ3MHlOVEV4TXpBeU1qSTJNelZhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMweE1URkVSVVJCVEZWVE1EQXdNREVhTUJnR0ExVUVBd3dSVXpFak1URXhSRVZFUVV4VlV6QXdNREF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzREeVo5QjdMeXF6ZjdMV25YTlkzRmVIZDhjc295TzVXRlRvQlZIYkphV3Q3aTlKWkYwcmtsbnFzeEJTb2U3UmFNU2FEbFRFUGEwQU5HUGI0TkY2YzZPTDJ6VUN6akNvYkhaK1YrVUVNSXJkRC9BdU8rNldVd0tKVEI3T213ZVpkODNmb1VwY2xOdWhhVUFWcGRKa3ZRNmt0dVR6azErbCt3M2pEcWcyZDlZL1hheEtJTCt5MUNoNFROdlFLeFZQbG12MFVWNUZ4VnJjQ3BFZDBSNnluOC9laExYSjZ0NFNmQmxGY2hldURpazNZV1lvaStzeFgrdzRzQmFvWDhtb3FuRmRTNDh6aDUzRmtMMDR1b3I3WXB2VFIzQ3gyamFsZGRzM0pLRmpUOWhVckFROUw5aGc4L01FMGpQaXBWVElucXBRWFlDcEJ1S3JSTVdUay9hQWdQQWdNQkFBR2pnY2d3Z2NVd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3Y3dZRFZSMGZCR3d3YWpCb29HYWdaSVppYkdSaGNEb3ZMMk5oWkhNdVptbHVZVzU2WlM1cGRDOURUajFEUVNVeU1FMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbEpUSXdWR1Z6ZEN4UFBVMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbExFTTlTVlF3SFFZRFZSME9CQllFRlBGYS8zQzB5ODFYMVZaaUp2c21ubisyTDJsSE1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQWtSTVFKQkVkNXFVUEJ5cEtObVl4TVNBMEMvYm1LL0lweVJza2xxeEZUQ1BTeGVUNUlsTnZSRFN2Q2szMVF6YXcrb0NyMDZhaW9nU3VaQnkvT3ZBUWNqVzU0aWFsSXNVMDM5QllHaDZmTW9vN3p5RjE4L0Y3RnZjZk15K0h2all2QU1JQ3lzMk1QU3FURXQ4Y2hKcENkOFAyQWdpR0ZZWVFVdWxjZzV1NU1JdTNxdkE2ZjZRQTVwU2VyV2ExeFdEZmZtR1dQV1BEU3k5QkFIUnpTRXRoKzdPU2ZhdzVqQ0pUWS9NbDZhd0dlM3FKWjBzN0hycENzSThZbE14d1BSWG5md0pveTFWVW53RENDWDJ0K0NnVjFxa1dmZXlFaFdXWWU1dk43ZGJBYjltQVRjTklXRmQwR3RTakJOS1A3dEhTdk1vQkdJSGNxY21rSWtCRERjNUtJMHJ2RFRIdCtOUkNYeDJQNDIwcjFLNEs4K0s2T09WUXMvK2s5eUszdUVZZUlIYmZvR3FFd09BT1JpdGRNOVlkclhLL0dTQmpCbFE5TnQ0NU90d3VUQ2JKY2hVdmVacEZqdFhMS2Vpcm4wam9JTUovL1I2Ny9LZjRRa2ZRMC9xMExEdzhMdTA2dDRtT25BNExIN1FpVVEvclE5RnA2dTVWMGZrcDBRZWtleHdCUW1PeTE0T1RjeXNDM3pEMXN3ZUhWdkJvdlA1VDhsZURyWWtjSEU2WXc5SGVocU8veHcvckJjMDNtRFJxTWZXblVxTUhzVExnQnZLeHNPNG1FbGcxSGM3M0c5QzBLcXZ0NEVGNzZoczhKZE9Rdld5Q280WVdOZ1BjM1BzVnNRaHBYck1EUXVkbHBXOUxKVE9Fa0F3QWZud2tmNXhQNVhEeHpUb0ZtZHlrOEFJPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJQUlZQUlY4MEEwMUgyNTVNXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJEUlMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImlzcyI6ImludGVncml0eTpTMSMxMTFERURBTFVTMDAwMCIsImxvY2FsaXR5Ijoiand0LWxvY2F0aW9uIiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb25lIFZlbmV0byIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMDUwIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJhY3Rpb25faWQiOiJDUkVBVEUiLCJyZXNvdXJjZV9obDdfdHlwZSI6IignNjA1OTEtNV5eMi4xNi44NDAuMS4xMTM4ODMuNi4xJykiLCJhdHRhY2htZW50X2hhc2giOiJiYjMwM2IzZjExNTVhMmMyY2RiNjI3MDcwMmZhNjM1OGM2MmQ1OTQ2YjUxNmU3MGEwM2RkYzU0OTlkNDc0MjRmIiwiZXhwIjoxNjgzMzk1MDcxLCJpYXQiOjE2ODMzMDg2NzEsImp0aSI6InVybjp1dWlkOjU2YWRjNjk5LTM2YWItNGU4Mi1hYzdiLTgzNzhiOTliZmRhZSIsInBlcnNvbl9pZCI6IkdUV0dXWTgyQjQyRzkyME1eXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyJ9.mOTr_i2jCqIPxAuR1i_M_OHsDk4Hb0pyKsQe2ydCVwqpVMSOJ9BXXDG94RTNcczlDAP355hUTSKV4RB789GOg6MeA9TXqKu76yI5cRLY8cxo0vVYVFUqNQkBZYJM5m0rbPoW8cdhVVpCqswO-z_fqaWsy3lzVHE-5CiCp-Q3SqEYWr_QNqckPQeFmeZRnaTHzN2JlK4W6Jpj3SAnVVdoqLWuUEDspb5mGblK0fpXqiYkkQkrGHjBdwgtiBDzhchjmuLMNecGOWTbfbPysRsFkP8l3ZsPtyRsbN_hMfod7zlVMAjaYu3empFF_RCkLN_A1eulh0nC5ZpVm_uyNshssw

Potreste dirci come risolvere?

**Comment by masciamariotti** [comment]
Buon pomeriggio,
potrebbe verificare se l' url che sta invocando sia effettivamente quella sopra riportata (https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/972)?
Sebbene l'url riportata sia corretta, l' errore sembra indicare che l'api richiamata non esiste.

**Comment by glotito77** [comment]
confermo che l'errore era un'errata url, soltanto che abbiamo il seguente problema adesso: Il campo purpose_of_use non coerente con operazione richiesta, potresti indicarmi il link di come valorizzare la request al token jwt a seconda del tipo di evento?

**Comment by masciamariotti** [comment]
La documentazione su come valorizzare i campi contenuti nei token la può trovare al seguente [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt).
In particolare, al [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#1336-contesto-operativo) sono indicati i valori che può assumere il campo purpose_of_use.

**Comment by IStacchiotti** [comment]
Buongiorno, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] ervizio di Eliminazione Documento - status": 404, "detail": "Unknown API", (Issue #320)" inviata il 12/05/2023 11:53:57. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] ervizio di Eliminazione Documento - status": 404, "detail": "Unknown API", (Issue #320)" inviata il 12/05/2023 11:53:58. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.
