### ISSUE TITLE
Mancato accreditamento A1111ESTARTOSCANA - ESTAR - PLEIADE - 3

### ISSUE THREAD

**Issue by diedo42** [ministero-salute/it-fse-support#323]
Avremmo bisogno di un chiarimento abbiamo ricevuto il mancato accreditamento per i seguenti problemi

Questo e' il file error.json ottenuto via email
[ {
  "id" : 63,
  "error" : "TEST_KO_NON_SUPERATO",
  "description" : "Test KO non superato. Assicurarsi che il traceId fornito abbia restituito in fase di validazione un errore bloccante."
}, {
  "id" : 64,
  "error" : "TEST_KO_NON_SUPERATO",
  "description" : "Test KO non superato. Assicurarsi che il traceId fornito abbia restituito in fase di validazione un errore bloccante."
} ]

Response del caso id 63
{
    "traceID": "6e286eaa6639f22d",
    "spanID": "6e286eaa6639f22d",
    "type": "/msg/syntax",
    "title": "Errore di sintassi.",
    "detail": "ERROR: -1,-1 cvc-complex-type.2.4.a: Invalid content was found starting with element 'languageCode'. One of '{\"urn:hl7-org:v3\":confidentialityCode}' is expected.",
    "status": 400,
    "instance": "/validation/error",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.b0f3ffcf25ce2aafc7dc901e2febc51f43837f4ca0fe3b6d1b02194e9047b6db.6b981b6800^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
    "ts": "2023-04-27T14:04:45Z"
  }

Response del caso id 64
{
  "traceID": "20bc35dc8f1d3191",
  "spanID": "20bc35dc8f1d3191",
  "type": "/msg/jwt-validation",
  "title": "Campo token JWT non valido.",
  "detail": "Il codice fiscale nel campo person_id non è corretto",
  "status": 403,
  "instance": "/jwt-mandatory-field-malformed",
  "workflowInstanceId": "UNKNOWN_WORKFLOW_ID",
  "ts": "2023-04-27T14:22:59Z"
}

Non ci e' chiaro il problema, per la nostra procedura sia l'errore 400 Bad Request che il 403 JWT Token error sono bloccanti ai fini del processo di validazione.

**Comment by masciamariotti** [comment]
Buon pomeriggio,
controllando il [data.json](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/GATEWAY/A1111ESTARTOSCANA/ESTAR/PLEIADE/3/data.json) nella sua PR di accreditamento abbiamo notato che probabilmente sono stati erroneamente invertiti i valori dei campi `ts` e `traceId` per i 2 casi di test citati:

```
        {
            "id": 63,
            "ts": "6e286eaa6639f22d",
            "traceId": "2023-04-27T14:04:45Z",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.b0f3ffcf25ce2aafc7dc901e2febc51f43837f4ca0fe3b6d1b02194e9047b6db.6b981b6800^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "files": [
                "VALIDAZIONE_CDA2_LDO_CT5_KO.pdf"
            ]
        },
        {
            "id": 64,
            "ts": "20bc35dc8f1d3191",
            "traceId": "2023-04-27T14:22:59Z",
            "workflowInstanceId": "UNKNOWN_WORKFLOW_ID",
            "files": [
                "VALIDAZIONE_CDA2_LDO_CT6_KO.pdf"
            ]
        },
```

Dovrebbe quindi effettuare PR correttiva.

**Comment by diedo42** [comment]
Effettuata la PR correttiva

https://github.com/ministero-salute/it-fse-accreditamento/pull/395

Grazie del supporto

Il giorno lun 8 mag 2023 alle ore 17:33 masciamariotti <
***@***.***> ha scritto:

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che la pull request è stata presa in carico in seguito alla nuova commit. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
