### ISSUE TITLE
Accreditamento soluzione IE-DEA

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#324]
Buongiorno,
volevamo notificare il caricamento completato dei test case per la soluzione IE-DEA:

https://github.com/ministero-salute/it-fse-accreditamento/pull/386

Grazie

**Comment by IStacchiotti** [comment]
Buonasera, le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
