### ISSUE TITLE
typeId extension="POCD_MT000040UV02"

### ISSUE THREAD

**Issue by marcomontelatfujifilm** [ministero-salute/it-fse-support#325]
Una volta predisposti i CDA aderenti alle specifiche HL7Italia e validati da FSE, sorge il problema che le specifiche regionali sono differenti. Nello specifico il CDA validato da FSE deve avere <typeId root="2.16.840.1.113883.1.3" extension="POCD_MT000040UV02"/> mentre il tool di validazione Arsenàl (https://testing.consorzioarsenal.it/EVSClient/cda/validator.seam?extension=ARSENAL&standard=CDA-ARSENAL) vuole <typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040"/>. 

In partica i CDA validati da FSE non vengono accettati dal regionale.

Visto che come fornitore abbiamo l'obbligo di aderire alla specifica FSE e ai requisiti qui definiti come dobbiamo comportarci con la regione ?

**Comment by ds-tommaso** [comment]
Mi aggiungo alla discussione. 


Regione Puglia
Immaginando di dover inviare i referti al repository regionale, il referto con cda iniettato deve essere comunque inviato alla validazione? Se si, cosa ne è del worflowf e traceid? Se la validazione fallisce, si prosegue comunque con la firma?

**Comment by marcomontelatfujifilm** [comment]
Buongiorno, ci sono aggiornamenti in merito al quesito posto: "In partica i CDA validati da FSE non vengono accettati dal regionale." ?

**Comment by Ser-ena** [comment]
Buonasera [marcomontelatfujifilm], al fine di un'analisi piu' approfondita potrebbe cortesemente esplicitare quali siano le specifiche del CDA non congruenti con le specifiche regionali?

**Comment by masciamariotti** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
