### ISSUE TITLE
info sul certificatore offline

### ISSUE THREAD

**Issue by DATASOFTNA** [ministero-salute/it-fse-support#326]
Buongiorno, vorrei sapere qual e' il grado di affidabilita' del verificatore offline (FseCertifier) , dato che qualche cda che passa la verifica, viene rilevato come errato da quello online.
Grazie.

**Comment by masciamariotti** [comment]
Buongiorno,
come indicato in [documentazione](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/gtw-certifier), lo scopo del gtw-certifier (FseCertifier) è quello di consentire di `eseguire offline la verifica dei test case di validazione ok richiesti durante la fase di accreditamento.` Pertanto è corretto che non rilevi alcuni errori, in quanto implementa una logica differente rispetto al Gateway online.
Quindi, per una corretta esecuzione, le consigliamo di effettuare prima le chiamate al servizio di validazione (`https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation`) secondo quanto richiesto dai test case di validazione OK di accreditamento, e, una volta ottenuto il risultato atteso, procedere con la verifica tramite il gtw-certifier.

**Comment by DATASOFTNA** [comment]
A dire la verita' ho letto piu' volte il file reame.md , ma non mi sembra che dichiari che il certificatore offline segua una logica diversa da quello online.
Peccato, sarebbe stato l'ideale poter effettuare i controlli fuori linea e solo una volta che vanno a buon fine sottoporre i dati al gwateway con la certezza di successo; un po' come accade per il tool xsd che da' la possibilita' di fare il controllo sintattico **prima** di trasferire l'XML creato.
Comunque e' uno strumento utile.
Grazie, cordiali saluti.

**Comment by IStacchiotti** [comment]
Buongiorno @DATASOFTNA, cerchiamo di chiarire meglio di seguito:
Come riportato in documentazione, lo scopo dell'API di validazione (Gateway) è validare da un punto di vista sintattico, semantico e terminologico i dati forniti dal Sistema Produttore. Il gtw-certifier (FseCertifier) ha uno scopo diverso che è quello di verificare offline il materiale caricato dai sistema produttore (test case di validazione ok) richiesto per l'accreditamento e implementa delle logiche specifiche

**Comment by DATASOFTNA** [comment]
Ok, grazie della risposta.
Se mi e' consentito vorrei porre un'altra domanda.
Tra i tool di sviluppo ne esiste uno che consente di avviare istanze locali di Gateway ed EDS del Fascicolo Sanitario 2.0.
Se capisco bene si tratterebbe di un "simulatore" del Gateway che puo' essere installato in locale.
Se e' cosi', anche in quel caso varrebbe la considerazione che e' indirizzato solo ai test di validazione ?

**Comment by IStacchiotti** [comment]
Buongiorno, per quanto riguarda l'EDS, non sono disponibili tool per svolgere test in locale. Per quanto riguarda il Gateway invece la rimandiamo ai container disponibili a questo [link](https://github.com/ministero-salute/it-fse-gtw-test-container).
La rimandiamo anche a [questo ](https://developersitalia.slack.com/archives/C03RDT88FSM/p1676309123572219) thread su Slack per la risoluzione di eventuali dubbi/problemi. Grazie

**Comment by DATASOFTNA** [comment]
`Per quanto riguarda il Gateway invece la rimandiamo ai container disponibili a questo [link]`
Si', quindi mi conferma che e' un simulatore del gateway in locale ?
Il passaggio della verifica su questo tool, sarebbe garanzia dell'accettazione da parte del gateway on line ?
Se mi permette avrei un'altra domanda.
Il superamento di tutti i test prescritti sul gateway online, da' la certezza di certificazione ?
Forse ho letto un po' superficialmente oppure ho interpretato male delle issue, ma mi e' sembrato che per alcuni utenti 
la certificazione non sia stata accordata, sebbene avessero passato i test perche' sono state rilevat delle incongruenze.
Grazie per l'attenzione, chiedo scusa per il disturbo, spero di non dovervi piu' importunare.
Cordiali saluti.

**Comment by IStacchiotti** [comment]
Nessun disturbo. I container full piuttosto che lite (in locale), non forniscono garanzia di accettazione da parte del Gateway online, dal momento che mancano alcuni componenti presenti nella versione online (infrastruttura di sicurezza, etc). In ogni caso si tratta di un tool valido per svolgere i primi test.

Specifichiamo infine che per l'accreditamento vengono svolti dei test specifici (più stringenti rispetti ai controlli previsti in validazione), pertanto non è detto che un esito positivo da parte del Geteway online, corrisponderà ad un esito positivo del gtw-certifier.
Rimaniamo a disposizione per ulteriori chiarimenti

**Comment by IStacchiotti** [comment]
Buonasera, La presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
