### ISSUE TITLE
VALIDAZIONE - HTTP 404

### ISSUE THREAD

**Issue by MassimoBussadori** [ministero-salute/it-fse-support#327]
Buongiorno.
Sto tentando di effettuare la validazione invocando
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v/documents/validation

Purtroppo mi ritorna questo JSON:
{
  "type":"https://govway.org/handling-errors/404/UndefinedOperation.html",
  "title":"UndefinedOperation",
  "status":404,
  "detail":"Operation undefined in the API specification",
  "govway_id":"2984a850-ee74-11ed-8882-005056ae54fa"
}

Per aggiungere il file PDF uso:
restRequest.AddBody(buffer);
dove <buffer> è un vettore di byte

Metto nell'header della chiamata quanto segue:
   restRequest.AddHeader("Content-Type", "multipart/form-data");
   restRequest.AddHeader("Authorization", "Bearer " + bearerToken);
   restRequest.AddHeader("FSE-JWT-Signature", jwtSignatureTocken);
   restRequest.AddHeader("Accept", "application/json");

Allego il PDF inviato:
[5006550501_R001.pdf.pdf](https://github.com/ministero-salute/it-fse-support/files/11444402/5006550501_R001.pdf.pdf)

Sono disponibile a fornirvi qualsiasi altra informazione per agevolarvi nel determinare la causa dell'HTTP404.

Grazie!
_Massimo Bussadori_

**Comment by DATASOFTNA** [comment]
Se mi e' consentito vorrei suggerire una soluzione.

L'endpoint e' errato, deve essere ......./gateway/**v1**/documents/validation

**Comment by masciamariotti** [comment]
Buongiorno,
confermiamo che l'endpoint corretto è con il v1, quindi 
`https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation`.
Potrebbe effettuare un nuovo tentativo ed in caso di errore inviarci la response ottenuta? Grazie

**Comment by MassimoBussadori** [comment]
Buongiorno!

Allego info riguardanti la Response appena ottenuta:

***@***.***

Il content vale questo:
{
"type":https://govway.org/handling-errors/404/UndefinedOperation.html,
"title":"UndefinedOperation",
"status":404,
"detail":"Operation undefined in the API specification",
"govway_id":"2ff2d54a-efd1-11ed-80ae-005056ae7395"
}

Grazie!

Massimo Bussadori

**Comment by MassimoBussadori** [comment]
Confermo che utilizzo l'endpoint da voi indicato, cioè:

https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation

e che l'errore HTTP404 "Operation undefined in the API specification" proviene invocando tale endPoint.

**Comment by MassimoBussadori** [comment]
Abbiamo superato l'errore HTTP404, grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
