### ISSUE TITLE
Accreditamento soluzione PIESSE

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#328]
Buongiorno,
volevamo notificare il caricamento completato dei test case per la soluzione PIESSE:

[ministero-salute/it-fse-accreditamento#386](https://github.com/ministero-salute/it-fse-accreditamento/pull/402)

Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, Le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
