### ISSUE TITLE
VALIDAZIONE - ERRORE 403 - AuthorizationContentDeny

### ISSUE THREAD

**Issue by explorasalerno** [ministero-salute/it-fse-support#329]
Salve a tutti. Durante la prova request per la validazione ricevo il seguente errore:

Type: https://govway.org/handling-errors/403/AuthorizationContentDeny.html
Status: 403
Title: AuthorizationContentDeny
Detail: Unauthorized request content
Govway_id: 99041ee8-efd5-11ed-8882-005056ae54fa

Qualcuno può gentilmente verificare dove stiamo sbagliando?

**Comment by explorasalerno** [comment]
Salve.

**Comment by explorasalerno** [comment]
> Salve.

**Comment by explorasalerno** [comment]
Salve. Ho effettuato ulteriori prove sempre con lo stesso errore 403. Per completezza allego i dettagli della mia request:

Content-Lenght: 35666
Content-Type: multipart/form-data; boundary=e507955dddfb40dc869f70170eeca7d8
--e507955dddfb40dc869f70170eeca7d8
Content-Disposition: form-data; name="requestBody"
{"healthDataFormat": "CDA", "mode": "ATTACHMENT", "activity": "VALIDATION"}
--e507955dddfb40dc869f70170eeca7d8
Content-Disposition: form-data; name="file"; filename="CDA_OK.pdf"
Content-Type: application/pdf
%PDF-1.4......
.....
--e507955dddfb40dc869f70170eeca7d8--


questo è il file data.json che utilizzo per generare i 2 JTW:
{
"sub": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
"subject_role": "AAS",
"purpose_of_use": "TREATMENT",
"iss": "S1111EXPLORACONS",
"subject_application_id": "VLFSE",
"subject_application_vendor": "EXPLORA CONSULTING SRL",
"subject_application_version": "1.40",
"locality": "150123456",
"subject_organization_id": "150",
"subject_organization": "Regione Campania",
"aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
"patient_consent": True,
"action_id": "CREATE",
"resource_hl7_type": "('11502-2^^2.16.840.1.113883.6.1')",
"jti": "c1213ade590c40ffab372ac503161949",
"person_id": "RSSMRA22A01A399Z^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO",
"pem_path": "S1111EXPLORACONS_sign.pem",
"attachment_hash":"",
"p12_path": "Sign.p12"
}

questo invece è il comando che utilizzo con il jwt-generator:
java -jar jwt-generator.jar -d data.json -a S1111EXPLORACONS -p 1234 -t 1


mentre il p12 lo genero con questo comando:
openssl pkcs12 -export -name S1111EXPLORACONS -out Certificati\Sign.p12 -inkey Certificati\Privata_firma.key -in Certificati\S1111EXPLORACONS_sign.pem

Non ho idea di dove sia l'errore ....

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] VALIDAZIONE - ERRORE 403 - AuthorizationContentDeny (Issue #329)" inviata il 12/05/2023 13:17:44. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] VALIDAZIONE - ERRORE 403 - AuthorizationContentDeny (Issue #329)" inviata il 12/05/2023 13:17:27. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] VALIDAZIONE - ERRORE 403 - AuthorizationContentDeny (Issue #329)" inviata il 12/05/2023 13:19:39. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] VALIDAZIONE - ERRORE 403 - AuthorizationContentDeny (Issue #329)" inviata il 12/05/2023 14:41:11. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] VALIDAZIONE - ERRORE 403 - AuthorizationContentDeny (Issue #329)" inviata il 12/05/2023 14:57:38. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by masciamariotti** [comment]
Grazie per il feedback. La presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] VALIDAZIONE - ERRORE 403 - AuthorizationContentDeny (Issue #329)" inviata il 12/05/2023 15:51:11. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.
