### ISSUE TITLE
HTTP 502 Bad Gateway (Invalid response received from the API Implementation)

### ISSUE THREAD

**Issue by EnzoMaietta** [ministero-salute/it-fse-support#33]
Buongiorno, è tutto il pomeriggio che stiamo ricevendo dal gateway errori di tipo "HTTP 502" anche utilizzando dei cda che in passato venivano correttamente validati. Vi risultano problemi tra il frontend "govway" ed il suo backend ? Inviamo di seguito l'errore completo:

< HTTP/1.1 502 Bad Gateway
HTTP/1.1 502 Bad Gateway
< X-Backside-Transport: FAIL FAIL
X-Backside-Transport: FAIL FAIL
< Connection: Keep-Alive
Connection: Keep-Alive
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< Server: GovWay-SOGEI
Server: GovWay-SOGEI
< GovWay-Message-ID: 1234
GovWay-Message-ID: 1234
< GovWay-Transaction-ErrorType: InvalidResponse
GovWay-Transaction-ErrorType: InvalidResponse
< GovWay-Transaction-ID: ab61c4e0-7002-11ed-8b1b-005056ae54fa
GovWay-Transaction-ID: ab61c4e0-7002-11ed-8b1b-005056ae54fa
< Content-Type: application/problem+json
Content-Type: application/problem+json
< Date: Tue, 29 Nov 2022 16:27:08 GMT
Date: Tue, 29 Nov 2022 16:27:08 GMT
< X-Global-Transaction-ID: 3f7e3e2d638632dce502b38f
X-Global-Transaction-ID: 3f7e3e2d638632dce502b38f

< 
* Connection #0 to host modipa-val.fse.salute.gov.it left intact
{"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"ab61c4e0-7002-11ed-8b1b-005056ae54fa"}

In allegato il cda: 
[cda.xml.txt](https://github.com/ministero-salute/it-fse-support/files/10115106/cda.xml.txt)

Grazie in anticipo e a disposizione per qualsiasi integrazione/chiarimento.

**Comment by pFonziSogei** [comment]
interruzione momentanea dei servizi di test. Chiusura issue
