### ISSUE TITLE
Processo di Accreditamento

### ISSUE THREAD

**Issue by dtsconsulting** [ministero-salute/it-fse-support#331]
Buonasera Volevo sapere se per ottenere l'accreditamento
i test da eseguire possono essere solo quelli di validazione?

Altra cosa volvevo sapere se per l'accreditamento, visto che noi dovremmo ottenerlo per :
1)Referto di Medicina di Laboratorio
2)Verbale di Pronto Soccorso
3)Lettera di Dimissione Ospedaliera
4)Referto di Radiologia
5)Referto di Specialistica Ambulatoriale
Possiamo inviare di volta in volta, oppure dobbiamo eseguire prima tutti i test 
e poi pubblichiamo?

In quanto avendo completato il Laboratorio di analisi vorrei chiedere l'accreditamento.

Per poi proseguire con le altre tipologie di referti.
Grazie mille

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Processo di Accreditamento (Issue #331)" inviata il 12/05/2023 10:24:34. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura per richiedere ulteriore supporto. Grazie
