### ISSUE TITLE
Mancato Accreditamento per TEST non presenti - No di nostra Tipologia RAD

### ISSUE THREAD

**Issue by E-SC** [ministero-salute/it-fse-support#333]
Buongiorno,
abbiamo ricevuto il seguente mancato accreditamento per:
{
"error" : "TEST_NON_PRESENTE",
"description" : "Test mancanti rispetto alla checklist:[6, 24, 29, 32, 35, 37, 40, 43, 63, 64, 65, 66, 67, 68, 69, 70, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 137, 139, 140, 142, 143, 144, 147, 151, 152, 153, 154, 155, 156, 159, 160, 161, 163, 172]"
} ]

Dal file accreditemento-checklist_V8.1.2.xlsx, i seguenti ID sopra riportati non riguardano la nostra applicazione per solo RAD, ma ad altro. Vedi immagine:
![image](https://github.com/ministero-salute/it-fse-support/assets/127778539/8fb4b27a-9011-4bc0-9e86-f21a6ec76441)

Restiamo in attesa di un riscontro.
Grazie.
E-SC S.r.l.

**Comment by IStacchiotti** [comment]
Buongiorno @E-SC, abbiamo analizzato la checklist caricata e ci risultata compilata per vari CDA, e non solo per RAD. Posteste verificare? Eventualmente vi invitiamo ad aprire una nuova pr per correggere la checklist.
Grazie

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Mancato Accreditamento per TEST non presenti - No di nostra Tipologia RAD (Issue #333)" inviata il 12/05/2023 10:53:16. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by E-SC** [comment]
Buongiorno,
come da indicazioni, abbiamo corretto il file checklist ed abbiamo aperto un nuovo pr.
Grazie.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Mancato Accreditamento per TEST non presenti - No di nostra Tipologia RAD (Issue #333)" inviata il 12/05/2023 11:08:47. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che la pull request è stata presa in carico. Procediamo quindi alla chiusura del presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Mancato Accreditamento per TEST non presenti - No di nostra Tipologia RAD (Issue #333)" inviata il 12/05/2023 11:55:40. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.
