### ISSUE TITLE
Richiesta creazione test case per il referto Tipizzazione HLA

### ISSUE THREAD

**Issue by osinfocer** [ministero-salute/it-fse-support#334]
E' possibile contemplare dei test di validazione per un applicativo che genera referti di **tipizzazione HLA** ?

Purtroppo la checklist di laboratorio trasfusionale ("9-Trasfusionale" ) (che è quella che più si avvicina come ambito operativo) non è applicabile al nostro contesto in quanto il nostro programma si occupa solamente di esami sull'HLA, per cui Fenotipo Rh, Tipizzazione eritrocitaria, Test di Coombs diretto e indiretto e Ricerca crioglobuline sono esami che non vengono gestiti dal nostro programma.  

Il referto principale che il programma produce è quello che riporto di seguito  dove ci sono le 11 observations indicate, che nel nostro CDA2 le abbiamo inserite in un contesto entryRelationship/organizer[@classCode=”BATTERY”]

![image](https://github.com/ministero-salute/it-fse-support/assets/100203966/cb01ece0-0dd8-4574-9cab-c9096ad32458)

**Comment by IStacchiotti** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
