### ISSUE TITLE
Ottengo errore 400 a richieste che fino a poche ore fa funzionavano

### ISSUE THREAD

**Issue by DATASOFTNA** [ministero-salute/it-fse-support#335]
Fino a qualche ora fa ho trasmesso correttamente dei file da validare (almeno fino alle ore 19:29 del 12.05)
[esito_ok4.txt](https://github.com/ministero-salute/it-fse-support/files/11468327/esito_ok4.txt) (a questo proposito vorrei sapere se le warning sono ostative per la certificazione).
Adesso, da qualche ora, a qualsiasi richiesta, anche la piu' semplice (tipo status/search) , ottengo l'errore 404
[errx.txt](https://github.com/ministero-salute/it-fse-support/files/11468339/errx.txt)
Non saprei proprio che ipotesi fare, potreste darmi una indicazione ?
Grazie.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "[ministero-salute/it-fse-support] Ottengo errore 400 a richieste che fino a poche ore fa funzionavano (Issue #335)" inviata il 13/05/2023 01:48:26. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, grazie per le segnalazione. Come da [comunicazione ](https://developersitalia.slack.com/archives/C03RDT88FSM/p1684141804383579)su Slack, ci sono attualmente delle problematiche di connessione. Verrà fornita nuova comunicazione appena conclusa l'analisi sul problema.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Ottengo errore 400 a richieste che fino a poche ore fa funzionavano (Issue #335)" inviata il 15/05/2023 12:19:46. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by masciamariotti** [comment]
Buongiorno,
come comunicato su canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM/p1684220702804659), il problema è stato risolto.
Vi chiediamo pertanto di riprovare e di monitorare il canale per aggiornamenti in merito.
Procediamo quindi alla chiusura del presente ticket. Sarà possibile procedere con l' apertura di un nuovo ticket nel caso in cui fosse necessario ulteriore supporto, grazie.
