### ISSUE TITLE
Rilascio certificati per ambienti di produzione 

### ISSUE THREAD

**Issue by marsardit** [ministero-salute/it-fse-support#337]
Buongiorno,

la Regione Sardegna è pronta per andare in produzione con la nuova infrastruttura regionale di FSE 2.0.
La soluzione tecnica presentata dalla Sardegna nel proprio Piano di Adeguamento Tecnologico approvato dal DTD prevede che i sistemi producer e consumer si autentichino verso il FSE regionale con gli stessi certificati rilasciati per la connessione col Gateway EDS.
Pertanto, per andare in produzione avremo bisogno di certificati espressamente rilasciati per questo ambiente.
Era previsto che le Regioni/Aziende Sanitarie sarebbero state autonome nella gestione del rilascio dei certificati ai sistemi di competenza attraverso il sistema di Provisioning Certificati: questo sistema è già disponibile per l’utilizzo da parte delle Regioni?
In assenza del sistema di Provisioning Certificati, a chi si deve fare riferimento per il rilascio di certificati di produzione?

Grazie in anticipo per la collaborazione.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "[ministero-salute/it-fse-support] Rilascio certificati per ambienti di produzione  (Issue #337)" inviata il 15/05/2023 11:37:55. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by Ser-ena** [comment]
Buonasera ci risulta che la segnalazione è già stata elaborata con la seguente mail inviata domenica 21/05:

"Buongiorno,
il sistema di provisioning per l’ambiente di test è in fase di rilascio, faremo comunicazione non appena rilasciata. 

Per la produzione si utilizzerà il sistema di provisioning, quindi sarete autonomi. "
