### ISSUE TITLE
InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by dtsconsulting** [ministero-salute/it-fse-support#338]
Buongiorno
stamattina stavamo proseguendo i test per la validazione e improvvisamente è ricomparso questo errore nelle response.
Nulla è cambiato tranne i file,  che inviamo per la validazione che vengono prodotti di volta in volta in funzione del test che dobbiamo 
svolgere.
Sono Forse scaduti i certifica? 
se è questa la problematica come possiamo proseguire?

questa è la response:
 "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "1308486c-f301-11ed-8882-005056ae54fa"

Bearer JWT:
eyJhbGciOiJSUzI1NiIsIng1YyI6WyJNSUlGYURDQ0ExQ2dBd0lCQWdJVU42V29JSFBjOE5HMHRlbXFLaEU1VWxwVS92OHdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekEwTWpReE56STRNRGxhRncweU5qQTBNalF4TnpJNE1EaGFNR2t4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVIwd0d3WURWUVJoREJSRFJqcEpWQzB4TVRGRVZGTkRUMDVUVlV4VVNURWFNQmdHQTFVRUF3d1JVekVqTVRFeFJGUlRRMDlPVTFWTVZFa3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEQ3Z4VG5PaUZCVVVheWNtNCt4d04rWHhTTkgzMXhjNStHdWVsWFk0Z1V3KytJUnpudGRpSmxaanVaVzA3eXhKWUZ4SE1uRDdzNUUyVFVKUHNjYkdaUWJ2QVNiMUhlaFpYdndQbVZRTmJrdjZuUkJZS1duNjQ3YzMyYnNTemdKMUdqT1MrUDBwelBiMU9iVHE2ai9DY2xSUkJzZXZVRVhwZzVHZC8rT1lHZFcxYncxZktpSWxPUTRjUlR6OEszc1lma2J4dmNtM2dDczI5L25nSUZlRmlxZ1dvdWl1UmhKWldsWm1sWDltZVpBL0pURHZ4SG13SExKR2dJMU5lOGVYMFA2aWh3QTloZWx5b3lxWHp6SmhCNSt2Z3hCcGdlWnhDNm9sVTNYT3lyMVFkTmQxYzlzQXBpWFJxRkhGbEkxV0ZyRm9LS3NiMWZBblJuUGJnZWFFdTFBZ01CQUFHamdnRVlNSUlCRkRBZkJnTlZIU01FR0RBV2dCUVdPYWthQlltM0R5MnlOZTNDQ1pyRkE0TWlQekFTQmdOVkhTQUVDekFKTUFjR0JTdE1IUUVMTUlHdEJnTlZIUjhFZ2FVd2dhSXdnWitnZ1p5Z2dabUdnWlpvZEhSd2N6b3ZMMk5oYzI5blpXbHpkbWxzTG5OdloyVnBMbWwwTDJWcVltTmhMM0IxWW14cFkzZGxZaTkzWldKa2FYTjBMMk5sY25Sa2FYTjBQMk50WkQxamNtd21hWE56ZFdWeVBVTk9KVE5FUTBFclRXbHVhWE4wWlhKdksyUmxiR3hoSzFOaGJIVjBaU3RVWlhOMEpUSkRUeVV6UkUxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVWxNa05ESlRORVNWUXdIUVlEVlIwT0JCWUVGR04wUzZ4MUYyVkhUa1kwcGdKNmEzU0ZadEJwTUE0R0ExVWREd0VCL3dRRUF3SUdRREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBQUNvRy91NlRWNzdkbUhneUNLczJybGRQSnB1WnRDVVVLWXBJOEFEQ3Npd2hua2pHTG13NWtOUmR1NVZRNjBJTjFaVHlIb0RodDF3M3cvbVA5RUZYdWdFRDZ2UERrQTA5b0J3bDc3NkcvRnBtRW5QK1N0VDE1VStyVVZNYlM4Z09qOXBxYXJoQ0xPdURMUEQvUjErUGFrL1RWWU5OUFI0YWwxNGlCUGF5ZjYra3d2MlE2c3NHK0I0ajQ5ZElIemZWZk1CMmZkTHlMcTdGQ3pIejc5RUFtOTRJWTk5RU1MeUR0WllneElyNzlqdUNxYnM3dzJ5enlBamJyU2g2WThxeC9BMVZNa3dSdDRqV01DUitPRUVLVVJ5ZWgxWjgzN3BYcC9JLzFseTZ1RDdEWUZ0VmU0RWd3bk82L0E1ZmZ3K1hYY1Y2c0o1L2lWaFh5Q0c0b1ZIc2xYWlV2S3hpYXRTU3FSTmFkc3F3RVdDR2IyTTFjNm0wekV3a20rd0JQaFp1MzRITFJwOGpsdnhvbXRWR1BlbE9QUU9kak1kczR1M1RHOGpPNGJYQUNhU20xdkFZTHhFRHd1WEJGS3NDaVRaU0wxY2g0S0x5aTBmQjc2b2NWNUhsd1VNOVJmUFlDLytoNXo4T3h6b3dVVEN0MkhoZG5wSkN6V0RsZEg0VHlTTktBUFc0K1drSDltRGhFTUQyaUdFNE00NlRleGoxSFg4NjVsU0dpN0VYWDRHYXlXbTVMdlJxSXFxaTdmVGZ3VW1nMUdIUHJEc2k0NVg4S2gvN2xMOTYyRzBHQjc3alFXVkZ1VXlSZnh5TW1LU0dqUTlCYjZXNU5RMWpsaXJwbFp4b3djbjN5dGw3bzFZeG4rT25ySjd1alYrcytncFZyQ3BZUzJUMVI3RzNWR009Il0sInR5cCI6IkpXVCJ9.eyJzdWIiOiJQUk9WQVgwMFgwMFgwMDBZXl5eXHUwMDI2Mi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yXHUwMDI2SVNPIiwiaXNzIjoiYXV0aDpTMSMxMTFEVFNDT05TVUxUSSIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsImp0aSI6ImM3OTUxYTNiLTg1MWMtNDRkZi1hMjRkLTk3NzJiZmEwYWFlNCIsImlhdCI6MTY4NDE0NjcwMSwiZXhwIjoxNjg0MjMzMTAxfQ.Wyj9gl7iifI_IRpIB3rjhNA0NPikNb4xMRwICHkPkq1VuL9sL7g8StFcRXr4wmZwaA1YG1Sj3-bb9aGcOtjQHzAhGDKikL2CQsMKnE5jXjNML7AtvYBTTFtK5zxtH6txdDpZsTLKb5-btPScxAx2K0cw_Ghv8eQ1VD3NIHsVWsFy7hFAn9lxlSstqoVMMsIWwTUtId2TlvCX0qVqGZbQ2Rk7i5R5murT6y5xM0x-Av2IkRSH-w0UXfQsCMq4x9dclIRg7UQeGEHx9XfY8jvTk6OLEDG6C2xHLzpnvQgOVMKSnQzElqDSOycxg5Kmi175o6rJ-tQOWR__rArmIYPuhA

FSE-JWT-Signature:
eyJhbGciOiJSUzI1NiIsIng1YyI6WyJNSUlGYURDQ0ExQ2dBd0lCQWdJVU42V29JSFBjOE5HMHRlbXFLaEU1VWxwVS92OHdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekEwTWpReE56STRNRGxhRncweU5qQTBNalF4TnpJNE1EaGFNR2t4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVIwd0d3WURWUVJoREJSRFJqcEpWQzB4TVRGRVZGTkRUMDVUVlV4VVNURWFNQmdHQTFVRUF3d1JVekVqTVRFeFJGUlRRMDlPVTFWTVZFa3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEQ3Z4VG5PaUZCVVVheWNtNCt4d04rWHhTTkgzMXhjNStHdWVsWFk0Z1V3KytJUnpudGRpSmxaanVaVzA3eXhKWUZ4SE1uRDdzNUUyVFVKUHNjYkdaUWJ2QVNiMUhlaFpYdndQbVZRTmJrdjZuUkJZS1duNjQ3YzMyYnNTemdKMUdqT1MrUDBwelBiMU9iVHE2ai9DY2xSUkJzZXZVRVhwZzVHZC8rT1lHZFcxYncxZktpSWxPUTRjUlR6OEszc1lma2J4dmNtM2dDczI5L25nSUZlRmlxZ1dvdWl1UmhKWldsWm1sWDltZVpBL0pURHZ4SG13SExKR2dJMU5lOGVYMFA2aWh3QTloZWx5b3lxWHp6SmhCNSt2Z3hCcGdlWnhDNm9sVTNYT3lyMVFkTmQxYzlzQXBpWFJxRkhGbEkxV0ZyRm9LS3NiMWZBblJuUGJnZWFFdTFBZ01CQUFHamdnRVlNSUlCRkRBZkJnTlZIU01FR0RBV2dCUVdPYWthQlltM0R5MnlOZTNDQ1pyRkE0TWlQekFTQmdOVkhTQUVDekFKTUFjR0JTdE1IUUVMTUlHdEJnTlZIUjhFZ2FVd2dhSXdnWitnZ1p5Z2dabUdnWlpvZEhSd2N6b3ZMMk5oYzI5blpXbHpkbWxzTG5OdloyVnBMbWwwTDJWcVltTmhMM0IxWW14cFkzZGxZaTkzWldKa2FYTjBMMk5sY25Sa2FYTjBQMk50WkQxamNtd21hWE56ZFdWeVBVTk9KVE5FUTBFclRXbHVhWE4wWlhKdksyUmxiR3hoSzFOaGJIVjBaU3RVWlhOMEpUSkRUeVV6UkUxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVWxNa05ESlRORVNWUXdIUVlEVlIwT0JCWUVGR04wUzZ4MUYyVkhUa1kwcGdKNmEzU0ZadEJwTUE0R0ExVWREd0VCL3dRRUF3SUdRREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBQUNvRy91NlRWNzdkbUhneUNLczJybGRQSnB1WnRDVVVLWXBJOEFEQ3Npd2hua2pHTG13NWtOUmR1NVZRNjBJTjFaVHlIb0RodDF3M3cvbVA5RUZYdWdFRDZ2UERrQTA5b0J3bDc3NkcvRnBtRW5QK1N0VDE1VStyVVZNYlM4Z09qOXBxYXJoQ0xPdURMUEQvUjErUGFrL1RWWU5OUFI0YWwxNGlCUGF5ZjYra3d2MlE2c3NHK0I0ajQ5ZElIemZWZk1CMmZkTHlMcTdGQ3pIejc5RUFtOTRJWTk5RU1MeUR0WllneElyNzlqdUNxYnM3dzJ5enlBamJyU2g2WThxeC9BMVZNa3dSdDRqV01DUitPRUVLVVJ5ZWgxWjgzN3BYcC9JLzFseTZ1RDdEWUZ0VmU0RWd3bk82L0E1ZmZ3K1hYY1Y2c0o1L2lWaFh5Q0c0b1ZIc2xYWlV2S3hpYXRTU3FSTmFkc3F3RVdDR2IyTTFjNm0wekV3a20rd0JQaFp1MzRITFJwOGpsdnhvbXRWR1BlbE9QUU9kak1kczR1M1RHOGpPNGJYQUNhU20xdkFZTHhFRHd1WEJGS3NDaVRaU0wxY2g0S0x5aTBmQjc2b2NWNUhsd1VNOVJmUFlDLytoNXo4T3h6b3dVVEN0MkhoZG5wSkN6V0RsZEg0VHlTTktBUFc0K1drSDltRGhFTUQyaUdFNE00NlRleGoxSFg4NjVsU0dpN0VYWDRHYXlXbTVMdlJxSXFxaTdmVGZ3VW1nMUdIUHJEc2k0NVg4S2gvN2xMOTYyRzBHQjc3alFXVkZ1VXlSZnh5TW1LU0dqUTlCYjZXNU5RMWpsaXJwbFp4b3djbjN5dGw3bzFZeG4rT25ySjd1alYrcytncFZyQ3BZUzJUMVI3RzNWR009Il0sInR5cCI6IkpXVCJ9.eyJzdWIiOiJQUk9WQVgwMFgwMFgwMDBZXl5eXHUwMDI2Mi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yXHUwMDI2SVNPIiwic3ViamVjdF9yb2xlIjoiRFJTIiwicHVycG9zZV9vZl91c2UiOiJUUkVBVE1FTlQiLCJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExRFRTQ09OU1VMVEkiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiRFRTSElTIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZW5kb3IiOiJEVFMgQ09OU1VMVElORyBTUkwiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlcnNpb24iOiIxLjAiLCJsb2NhbGl0eSI6IjIwMTEyMzQ1NiIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMTUwIiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb25lIENhbXBhbmlhIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJhY3Rpb25faWQiOiJDUkVBVEUiLCJyZXNvdXJjZV9obDdfdHlwZSI6IihcdTAwMjcxMTUwMi0yXl4yLjE2Ljg0MC4xLjExMzg4My42LjFcdTAwMjcpIiwianRpIjoiN2VmNjRmZmUtZmI0MC00ZmFkLWJlODQtOGM1YTM1MTgwZDcyIiwicGVyc29uX2lkIjoiUFJPVkFYMDBYMDBYMDAwWV5eXlx1MDAyNjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMlx1MDAyNklTTyIsImlhdCI6MTY4NDE0NjcwMSwiZXhwIjoxNjg0MjMzMTAxfQ.NjofF4RO-XH7CaXXWclUYIBrE66ebI4JcpI6wJ5UiancponQTwM6OC0zp92QjykULEsqwfZzY5FLituxEV23MTsLD1ZaGm-buRQD9Njl2ysuJ0su-qLmG5OBHUQaoGExzP5Bpf_eoqsJ4chuUxIX27z6Gjtdw-XgPPVlAOINJHchhhUakZN75OluJBxUfkHk16y4tagN7l4sbTvE6gysntbQOhR-swgrewvA4j9-dRTqCELgOh9xHvSdPLYD6Ze2GiqawCEJvnHYOQcbF0igNU-hymEKKV5SydKtMv65NwbpIDzdZ1xwM_s6sUhNbMxM-m7G4v8VzyKdLi3VZwWK2g

**Comment by IStacchiotti** [comment]
Buongiorno, grazie per le segnalazioni. Come da [comunicazione ](https://developersitalia.slack.com/archives/C03RDT88FSM/p1684141804383579)su Slack, ci sono attualmente delle problematiche di connessione. Verrà fornita nuova comunicazione appena conclusa l'analisi sul problema.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] InteroperabilityInvalidRequest (Issue #338)" inviata il 15/05/2023 12:37:33. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "[ministero-salute/it-fse-support] InteroperabilityInvalidRequest (Issue #338)" inviata il 15/05/2023 12:35:36. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by GiuseppePicciano** [comment]
Buongiorno a tutti, confermate che ancora e' il sistema che continua a dare questo problema e che e' inutile continuare a fare delle prove prima che risolvete?

 * Server GovWay-SOGEI is not blacklisted
< Server: GovWay-SOGEI
< Pragma: no-cache
< GovWay-Message-ID: 1234
< GovWay-Transaction-ErrorType: InteroperabilityInvalidRequest
< GovWay-Transaction-ID: dc494e2e-f39d-11ed-8882-005056ae54fa
< Date: Tue, 16 May 2023 05:42:45 GMT

**Comment by masciamariotti** [comment]
Buongiorno,
come comunicato su canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM/p1684220702804659), il problema è stato risolto.
Vi chiediamo pertanto di riprovare e di monitorare il canale per aggiornamenti in merito.
