### ISSUE TITLE
Accreditamento soluzione NEOCARE

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#339]
Buongiorno,
volevamo notificare il caricamento completato dei test case per la soluzione NEOCARE:

https://github.com/ministero-salute/it-fse-accreditamento/pull/435

Grazie

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "[ministero-salute/it-fse-support] Accreditamento soluzione NEOCARE (Issue #339)" inviata il 15/05/2023 13:56:15. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.

**Comment by IStacchiotti** [comment]
Buonasera,  Le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.

**Comment by davidecasiraghi** [comment]
Sono fuori dall'ufficio fino a 16/05/2023per assistenza sul software Priamo contattare il servizio di helpdesk:mail: ***@***.***: 031647647per altre comunicazioni contattare i colleghi del gruppo di sviluppo all'indirizzo ***@***.*** SalutiNota: Questa è una risposta automatizzata al messaggio  "Re: [ministero-salute/it-fse-support] Accreditamento soluzione NEOCARE (Issue #339)" inviata il 15/05/2023 14:59:58. Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.




BCS, sensibile all'esigenza di assicurare condizioni di correttezza e di trasparenza nello svolgimento delle proprie attività, a tutela dell'immagine e della propria posizione, a tutela dei propri dipendenti e terzi correlati, ha adottato in data 12 Dicembre 2014 il Modello di Organizzazione Gestione e Controllo, ha nominato l'Organismo di Vigilanza e redatto il Codice Etico ex D.Lgs 231/2001. I documenti sono consultabili sul sito web all'indirizzo www.bcs.it. 





Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 ? GDPR-  e quindi ne è proibita l?utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.
