### ISSUE TITLE
Validazione CDA2 con schematronFSE_LAB.sch

### ISSUE THREAD

**Issue by luciatrama** [ministero-salute/it-fse-support#34]
Buongiorno,
sto effettuando la validazione di referti CDA2 di laboratorio utilizzando lo schematronFSE_LAB.sch.
Riscontro uno strano errore sulla sezione degli inFulfillmentOf: da specifiche posso averne più di uno e per ognuno di essi potrei doverne definire la priorità, ma inserendo due inFulfillmentOf ognuno con il proprio priorityCode, ottengo il seguente errore: "ERRORE-37 /infulfillmentOf/order/priorityCode DEVE avere l'attributo '@codeSystem='2.16.840.1.113883.5.7' e @code valorizzato con uno dei seguenti valori: 'R'|'P'|'UR'|'EM'"

Sono costretta a eliminare la priorità dal secondo raggruppamento per evitare l'assert; in pratica posso avere più di un raggruppamento inFulfillmentOf ma solo per uno di essi posso definirne la priorità?

Vi ringrazio

**Comment by LeonardoAlcaro** [comment]
Buonasera,
si conferma da schematron e da POCD che si può avere più di un elemento inFulfillmentOf.
<assert test ="count(hl7:inFulfillmentOf)>=1">ERRORE-36| In ClinicalDocuemnt DEVE essere presente almeno un elemento 'inFulfillmentOf'. </assert>
Il problema come evidenziato è legato alla priorità dunque elemento priorityCode per il quale da POCD ha cardinalità 0..1 ma può essere utilizzato in più inFulfillmentOf , correggeremo <assert test ="count(hl7:inFulfillmentOf/hl7:order/hl7:priorityCode)=0 or 
			count(hl7:inFulfillmentOf/hl7:order/hl7:priorityCode[@codeSystem='2.16.840.1.113883.5.7'][@code='R' or @code='P' or @code='UR' or @code='EM'])=1"
            >ERRORE-37| <name/>/infulfillmentOf/order/priorityCode DEVE avere l'attributo '@codeSystem='2.16.840.1.113883.5.7' e @code valorizzato con uno dei seguenti valori: 'R'|'P'|'UR'|'EM' </assert>
					
Grazie della segnalazione

**Comment by pFonziSogei** [comment]
Salve, abbiamo da poco introdotto una modifica che dovrebbe risolvere il problema. Potrebbe effettuare un test?

**Comment by luciatrama** [comment]
Buongiorno,
potrebbe dirmi dove recuperare lo schematron aggiornato?
Non sono ancora predisposta per la validazione tramite gateway, effettuo verifiche interne del CDA2 prodotto utilizzando lo schematron fornito, ma tra la documentazione continuo a vedere quello originario.

La ringrazio.


Lucia Trama
Sviluppo Software
T. 
E. ***@***.******@***.***>
www.dedalus.com<https://www.dedalus.com/>

Da: pFonziSogei ***@***.***>
Inviato: lunedì 16 gennaio 2023 20:23
A: ministero-salute/it-fse-support ***@***.***>
Cc: Lucia Trama ***@***.***>; Author ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Validazione CDA2 con schematronFSE_LAB.sch (Issue #34)


Salve, abbiamo da poco introdotto una modifica che dovrebbe risolvere il problema. Potrebbe effettuare un test?

**Comment by zukka77** [comment]
@luciatrama gli schematron sono appena stati aggiornati
