### ISSUE TITLE
InteroperabilityInvalidRequest status 400, Received request is not conform to the required interoperability profile

### ISSUE THREAD

**Issue by GiuseppePicciano** [ministero-salute/it-fse-support#340]
Spett.li Signori

Gia' da ieri sperimentiamo questo errore nella spedizione, e poi ci siamo accorti che era presente un avviso che rilevava un malfunzionamento del sito.

Questa mattina avete segnalato che il sistema era tornato funzionante ma il nostro sistema continua a rilevare lo stesso problema.

Si tratta di una rilevazione solo nostra o ancora persistono delle condizioni di difficolta'?

Response:
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"b4c63e0b-f3be-11ed-8882-005056ae54fa"}

**Comment by masciamariotti** [comment]
Buongiorno Giuseppe,
da una prima analisi sembra stia inviando dei dati non corretti all'interno dei token:
Authorization:
- "aud": "FSE_Gateway" --> il valore corretto deve essere "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1"
- "iss": "auth:jwt-issuer" --> al posto di "jwt-issue" deve inserire il common name. esempio: "iss": "auth:S1#190201123456XX"

FSE-JWT-Signature:
- "aud": "FSE_Gateway" --> il valore corretto deve essere "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1"
- "iss": "integrity:jwt-issuer" --> al posto di "jwt-issue" deve inserire il common name. esempio: "iss": "integrity:S1#190201123456XX"
- "locality": "jwt-location" --> va valorizzato per esempio con 201123456 (caso struttura) o 201 (caso ruolo APR)

Al seguente [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt) può trovare i riferimenti alla documentazione.

**Comment by GiuseppePicciano** [comment]
Perfetto. Grazie per il supporto.

**Comment by IStacchiotti** [comment]
Buonasera, grazie per il feedback. La presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
