### ISSUE TITLE
Identificativi paziente in patientRole

### ISSUE THREAD

**Issue by marcomontelatfujifilm** [ministero-salute/it-fse-support#342]
Nella documentazione HL7 Italia HL7IT-IG_CDA2_RAD-v1.1-S, relativamente agli identificativi del paziente, nella sezione patientRole si definisce:

4.1.12.1 Paziente soggetto del referto: <patientRole>
`
Nel caso di Cittadino Italiano o straniero residente in Italia, <patientRole> DEVE riportare un elemento di tipo <id> contenente il Codice Fiscale (OBBLIGATORIO) e un ulteriore elemento <id> (OBBLIGATORIO) contenente il numero di identificazione dell’assistito nel sistema PACS in cui sono custodite le immagini (come indicato tra le premesse il @nullFlavour è ammesso ove l’informazione non sia disponibile).
`
Quindi si dovrebbero avere almeno 2 id. Corretto ?

Il gateway di validazione non si accorge dell'assenza del secondo id, quello relativo al PACS e la validazione va a buon fine.

Non vi è una incongruenza tra quanto definito nella specifica CDA HL7Italia e il comportamento del Gateway ?

**Comment by IStacchiotti** [comment]
Buonasera, grazie della segnalazione. Si conferma che viene richiesto da specifiche l'inserimento di un secondo id che riporta il numero di identificazione dell'assistito nel sistema PACS. Pertanto verrà effettuata una modifica allo schematron affinchè venga segnalata l'eventuale assenza di quest'ultimo. Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
