### ISSUE TITLE
ANOMALIA IN INVOCAZIONE GATEWAY

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#344]
Buongiorno,
riscontriamo il seguente errore in fase di invocazione del Gateway:

{
    "code": "ERROR",
    "userMessage": "Campo token JWT non valido.",
    "systemMessage": "Il campo subject_application_id non è valorizzato",
...
}

Si tratta di una anomalia temporanea o è cambiata qualche specifica di invocazione?

Grazie

**Comment by masciamariotti** [comment]
Buongiorno Elisabetta,
come da [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt), i campi relativi all' applicativo contenuti nel JWT di Signature sono obbligatori.

**Comment by Elisabetta-Tecchio-GPI** [comment]
Confermiamo di aver inserito tutti i campi previsti nel JWT ma il gateway ritorna sempre il seguente errore:
{
    "code": "ERROR",
    "userMessage": "Campo token JWT non valido.",
    "systemMessage": "Il campo subject_application_id non è valorizzato",
...
}

Si tratta di una anomalia temporanea?

Grazie

**Comment by masciamariotti** [comment]
Potrebbe allegare la risposta completa, comprensiva di traceId/govway-id?
Grazie

**Comment by Elisabetta-Tecchio-GPI** [comment]
Buongiorno, 
di seguito la response:
{
  "traceID" : "95c689dfb353caaa",
  "spanID" : "95c689dfb353caaa",
  "type" : "/msg/jwt-validation",
  "title" : "Campo token JWT non valido.",
  "detail" : "Il campo subject_application_id non è valorizzato",
  "status" : 403,
  "instance" : "/jwt-mandatory-field-missing",
  "workflowInstanceId" : "UNKNOWN_WORKFLOW_ID"
}

questo errore ci viene restituito dalla 10.00 di oggi circa.

Questa la request che effettuiamo:

{
  "sub" : "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "person_id" : "TSTPRV22H01F839G^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "subject_organization_id" : "120",
  "iss" : "S1#111GRUPPOGPI00",
  "subject_role" : "AAS",
  "resource_hl7_type" : "('34105-7^^2.16.840.1.113883.6.1')",
  "locality" : "jwt-location",
  "aud" : "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
  "purpose_of_use" : "TREATMENT",
  "subject_organization" : "Regione Lazio",
  "patient_consent" : "true",
  "action_id" : "CREATE",
  "exp" : 1684405655163,
  "iat" : 1684319255163,
  "jti" : "41434ed8-0854-43b2-845a-5bdd1b85aa34",
  "pem_path" : "./S1111GRUPPOGPI00_sign.pem",
  "p12_path" : "./keystore_s.p12",
  "attachment_hash" : "85fe3c7c35b67460845695015a7a13acbfd95a46",
  "subject_application_id" : "NGH CCA",
  "subject_application_vendor" : "GPI S.P.A.",
  "subject_application_version" : "8.0"
}

Grazie

**Comment by nbssrl** [comment]
Riscontriamo anche noi problemi relativi alla validazione del token :
{
 "title" : "Campo token JWT non valido.",
  "detail" : "Il codice fiscale nel campo sub non è corretto",
  "status" : 403,
}
il tali problemi non erano presenti nel tardo pomeriggio di ieri e tale campo era analogo alle precedenti generazione  c'è qualche anomali?

**Comment by masciamariotti** [comment]
@Elisabetta-Tecchio-GPI da ulteriori verifiche abbiamo notato che nel JWT di Signature non stanno arrivando i campi
```
"subject_application_id" : "NGH CCA",
"subject_application_vendor" : "GPI S.P.A.",
"subject_application_version" : "8.0"
```
Potrebbe verificare come sta generando i token? Se ha necessità di verificare il contenuto dei token generati, può usufruire del tool online https://jwt.io/

**Comment by Elisabetta-Tecchio-GPI** [comment]
La generazione del token non è cambiata, e l'ultima risposta positiva del gateway con la stessa tipologia di request è stata alle 2023-05-17 09:41:18.120

{
  "traceID" : "988d158ff4908790",
  "spanID" : "988d158ff4908790",
  "workflowInstanceId" : "2.16.840.1.113883.2.9.2.70.4.6.edd59f661bc89cd0d0ed564bf4526278004472069be08be872306741768bc066.50f63212c4^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Abbiamo anche provato da un altro ambiente di test e ci dà lo stesso errore.
E' cambiato qualche controllo a livello di Gateway Nazionale durante la mattinata?

**Comment by Elisabetta-Tecchio-GPI** [comment]
Buongiorno, abbiamo compilato il jwt-generator ed ora non riscontriamo l'anomalia.
Chiudo la issue, grazie
