### ISSUE TITLE
Processo di aggiornamento del certificato vaccinale

### ISSUE THREAD

**Issue by giacintogirelli** [ministero-salute/it-fse-support#345]
Non è chiaro quale sia il flusso operativo giusto per inviare un aggiornamento del certificato vaccinale di un soggetto che effettua una vaccinazione in una regione diversa da quella che ha inviato il precedente certificato

Esempio:
Nel caso di un residente della regione X, che effettui una vaccinazione in Puglia e per il quale la stessa regione X abbia già inviato al FSE il certificato vaccinale; quale di queste opzioni di conferimento è corretta?

1. sovrascrittura del precedente certificato con le sole informazioni relative alla vaccinazione effettuata in Puglia (perdendo così le informazioni relative alle somministrazioni effettuate nella regione di residenza)
2. acquisizione del certificato vaccinale pre-esistente (in questo caso vorremmo sapere in che modalità) inserendo la nuova vaccinazione effettuata in aggiunta a quelle pre-esistenti ed effettuando l'invio sovrascrivendo il certificato vaccinale pre-esistente

**Comment by vigliottim** [comment]
Buonasera, l'opzione corretta è la numero 2. Seguiranno aggiornamenti sulle relative specifiche. Restiamo a disposizione nel caso avesse bisogno di ulteriori chiarimenti.

**Comment by giacintogirelli** [comment]
Alla luce di quanto avete asserito, attendiamo le specifiche tecniche per capire come procedere con l'acquisizione del certificato vaccinale pre-esistente al fine di aggiornarlo

**Comment by valerio1982** [comment]
Gentili
non abbiamo ricevuto ulteriori riscontri circa il rilascio delle specifiche tecniche per il recupero e l'aggiornamento del certificato vaccinale (nella fattispecie riportata nell'esempio citato nella issue).
Potreste fornirci un riscontro in merito?

Grazie

**Comment by giacintogirelli** [comment]
Gentili
non abbiamo ricevuto ulteriori riscontri circa il rilascio delle specifiche tecniche per il recupero e l'aggiornamento del certificato vaccinale (nella fattispecie riportata nell'esempio citato nella issue).
Potreste fornirci un riscontro in merito?

Grazie
