### ISSUE TITLE
Accreditamento applicativo WINGLA

### ISSUE THREAD

**Issue by AcsFSE** [ministero-salute/it-fse-support#348]
Buongiorno.
Notifichiamo il carichiamo dei test effettuati sull' applicativo.

Saluti

[ministero-salute/it-fse-accreditamento/pull/461]

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che la pull request è stata presa in carico. Chiudiamo il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
