### ISSUE TITLE
accesso a slack #fse

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#35]
Buongiorno, 
chiedo istruzioni su come effettuare l'accesso al canale slack #fse

Sono già registrata su slack.com con l'email silvana.ponsero@csi.it e vorrei poter accedere anche all'area di lavoro FSE

Grazie

**Comment by ponsilva** [comment]
Scusate, il problema è stato risolto

**Comment by delx** [comment]
I tried to get access to the Slack #fse channel to ask a couple of questions. However, when trying to register a Slack account, it seems that Slack is only allowed for certain email domains. How is it possible to get Slack access for a third-party email address? Thanks a ton!

**Comment by vigliottim** [comment]
> I tried to get access to the Slack #fse channel to ask a couple of questions. However, when trying to register a Slack account, it seems that Slack is only allowed for certain email domains. How is it possible to get Slack access for a third-party email address? Thanks a ton!

Hi,
you can access to the Slack channel #fse using the following link:
https://join.slack.com/t/developersitalia/shared_invite/zt-2nars6ctt-vB5yHIEK_nd~5RsvDQ4RDA
