### ISSUE TITLE
Accreditamento soluzione IE-DEGENTI

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#350]
Buongiorno,
volevamo notificare il caricamento completato dei test case per la soluzione IE-DEGENTI:

[ministero-salute/it-fse-accreditamento#435](https://github.com/ministero-salute/it-fse-accreditamento/pull/471)

Grazie

**Comment by IStacchiotti** [comment]
Buonasera, Le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
