### ISSUE TITLE
Verifica_Non_Superata

### ISSUE THREAD

**Issue by salvatore-schiavottiello** [ministero-salute/it-fse-support#353]
Salve,
a seguito di una verifica abbiamo ottenuto il seguente feedback:

`{
  "id" : 147,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='005' attribute='' actual = '' expected = 'Prestazioni'>ClinicalDocument/component/structuredBody/component/section[ID='Prestazioni']/title</error>"
}`

Vorrei sapere se ciò è dovuto al fatto che nel cda.xml allegato al pdf la section delle prestazioni contiente PRESTAZIONI e non Prestazioni:
`<structuredBody classCode="DOCBODY" moodCode="EVN">
            <component typeCode="COMP">
                <section ID="PRESTAZIONI">
                </section>
            </component>`

Se il problema dovesse invece dipendere dalla mancanza del tag title, la sua assenza è dovuta al fatto che non sembra essere obbligatorio ed in ogni caso non siamo in grado di inserirlo in quanto l'oggetto di tipo POCDMT000040UV02Section prevede si il metodo setTitle che accetta un oggetto di tipo ST e quest'ultimo non prevede il set di un valore di tipo stringa.

Allego il pdf con il cda.xml allegato.
[RSA_CT1.pdf](https://github.com/ministero-salute/it-fse-support/files/11518373/RSA_CT1.pdf)

**Comment by IStacchiotti** [comment]
Buongiorno @salvatore-schiavottiello, per riprodurre correttamente il caso di test 1 è necessario l'inserimento dell'elemento 'title'. Qualora non fosse possibile inserirlo, si può definire il caso di test "Non Applicabile".
