### ISSUE TITLE
Incongruenza validazione FSE 2.0 attributo ClinicalDocument.templateId

### ISSUE THREAD

**Issue by marcomontelatfujifilm** [ministero-salute/it-fse-support#354]
Secondo specifica CDA HL7 Italia l'attributo templateId deve:

```
CONF - RAD - 3 Il documento DEVE contenere almeno un elemento <ClinicalDocument>/<templateId>. Per l’aderenza a questa guida, l'attributo @root di almeno un elemento <ClinicalDocument>/<templateId> DEVE essere valorizzato con "2.16.840.1.113883.2.9.10.1.7.1 " ed il relativo attributo @extension DEVE essere valorizzato con “1.1”.
```

La validazione FSE 2.0 accetta anche il valore 1.0. 

Si tratta di una incongruenza con la specifica oppure è una cosa voluta ?

**Comment by IStacchiotti** [comment]
Buongiorno. La scelta è voluta, con il controllo si vuole limitare la verifica alla valorizzazione dell'attributo root e alla presenza dell'extension per non rendere il controllo troppo stringente nel caso in cui la versione del template a cui fanno riferimento le specifiche dovesse cambiare.

**Comment by IStacchiotti** [comment]
Buongiorno, procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
