### ISSUE TITLE
Richiesta certificati di test FSE

### ISSUE THREAD

**Issue by fabiopileri** [ministero-salute/it-fse-support#355]
in riferimento alla Vostra risposta, apro un ticket per la richiesta dei certificati di test per accedere al gateway di pre-produzione del fornitore OLOMEDIA S.R.L. per l’accreditamento dei software.

Il software da accreditare è oloHEALTH e per le seguenti tipologie documentali: 

- Lettera di Dimissione Ospedaliera (LDO)
- Referto di Specialistica Ambulatoriale (RSA)
- Verbale di Pronto Soccorso (VPS)

Vi ringraziamo per la vostra attenzione e collaborazione.

**Comment by IStacchiotti** [comment]
Buonasera Fabio, grazie. Stiamo sollecitando il rilascio dei certificati. Le faremo sapere quanto prima.

**Comment by IStacchiotti** [comment]
Buon pomeriggio. Ci risulta che ha ricevuto i certificati via email. Chiudiamo pertanto il presente ticket, in caso contrario è possibile procedere con la riapertura. Grazie.
