### ISSUE TITLE
Validazione Documento: InvalidResponse

### ISSUE THREAD

**Issue by cravell** [ministero-salute/it-fse-support#36]
Ciao,
in fase di validazione del documento sto ricevendo il seguente messaggio di errore:
{"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"ec3ceec6-8126-11ed-b06a-005056ae7395"}

**Comment by pFonziSogei** [comment]
Salve, state inserendo null in molti campi del token (subject_role, purpose_of_use, subject_organization, subject_organization_id, action_id, person_id). Può vedere i campi da inserire su https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#111-campi-contenuti-nei-jwt

**Comment by cravell** [comment]
Salve,
ho apportato le modifiche ed ora il token risulta popolato, vedi attach, ma restituisce sempre l'errore:

- response token1:
`{\"type\":\"https://govway.org/handling-errors/502/InvalidResponse.html\",\"title\":\"InvalidResponse\",\"status\":502,\"detail\":\"Invalid response received from the API Implementation\",\"govway_id\":\"317cb63c-85a8-11ed-b21d-005056ae54fa\"}`
- response token2
`{
    "timestamp": "##json-date##1672127894229",
    "status": 500,
    "error": "Internal Server Error",
    "message": "{\"type\":\"https://govway.org/handling-errors/502/InvalidResponse.html\",\"title\":\"InvalidResponse\",\"status\":502,\"detail\":\"Invalid response received from the API Implementation\",\"govway_id\":\"fcefc65e-85aa-11ed-b21d-005056ae54fa\"}",
    "path": "/api/bridge/fse/validate/fse20"
}
`

[token_prova1.txt](https://github.com/ministero-salute/it-fse-support/files/10306771/token_prova1.txt)

[token_prova2.txt](https://github.com/ministero-salute/it-fse-support/files/10306803/token_prova2.txt)

**Comment by zukka77** [comment]
Buongiorno `resource_hl7_type` ha una sintassi errata, dovrebbe essere, come da documentazione,
`('11502-2^^2.16.840.1.113883.6.1')` , non *11502-2^^2.16.840.1.113883.6.1*.
Lato nostro cercheremo di migliorare il messaggio d'errore.

**Comment by cravell** [comment]
Ciao,
ho eseguito la modifica mi restituisce comunque l'errore:
`{"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"0913583f-85de-11ed-b06a-005056ae7395"}`

[token_prova3.txt](https://github.com/ministero-salute/it-fse-support/files/10308504/token_prova3.txt)

**Comment by cravell** [comment]
Ciao, ci sono novità relativamente all'ultimo commento?

**Comment by cravell** [comment]
Ciao è possibile avere un riscontro a riguardo?
Grazie

**Comment by pFonziSogei** [comment]
Salve, dovrebbe inserire il filename:

Attuale
	Content-Disposition: form-data; name="file"
	Content-Type: application/pdf
	
Desiderata:	
	Content-Disposition: form-data; name="file"; filename="filename.pdf" 
	Content-Type: application/pdf

La invito, inoltre, ad aprire una nuova issue se la problematica precedente risulta risolta

**Comment by cravell** [comment]
Grazie per il supporto ora ricevo un ack positivo
