### ISSUE TITLE
Error 400 InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by PentaSistemi-DEVteam** [ministero-salute/it-fse-support#361]
Buongiorno,
riceviamo questo errore in fase di Validazione:
{
    "type": "[https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html"](https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html%22),
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "a01e3064-f956-11ed-8882-005056ae54fa"
}

In allegato i 2 Token utilizzati:
[VALIDATION_JWS.txt](https://github.com/ministero-salute/it-fse-support/files/11544342/VALIDATION_JWS.txt)
[VALIDATION_JWT.txt](https://github.com/ministero-salute/it-fse-support/files/11544343/VALIDATION_JWT.txt)

Grazie per il supporto.
Penta Sistemi DEV Team

**Comment by masciamariotti** [comment]
Buon pomeriggio,
da una prima analisi dovrebbe correggere i seguenti parametri:

Authentication Bearer Token:
- gli unici parametri richiesti nel payload sono: `iss` / `iat` / `exp` / `jti` / `aud`, pertanto i restanti vanno rimossi;
- il valore del campo `aud` è errato: valore corretto --> `https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1`.

FSE-JWT-Signature:
- il valore del campo `aud` è errato: valore corretto --> `https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1`.

**Comment by PentaSistemi-DEVteam** [comment]
Grazie mille, provvederemo a fare le correzioni.

Un saluto
Il DEV Team di Penta Sistemi

**Comment by masciamariotti** [comment]
Buon pomeriggio,
l'errore riscontrato è il seguente
`Content type 'null' is not allowed for body content`

Dovrebbe verificare se sta effettuando correttamente la chiamata, infatti nell' header vediamo
`boundary="19524488-4ee3-4dc8-8155-aa1a945ec081"`
mentre la request contiene
`--19524488-4ee3-4dc8-8155-aa1a945ec081`
`Content-Type: application/json; charset=utf-8`
`Content-Disposition: form-data; name=requestBody`

`{"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VALIDATION"}`
`--19524488-4ee3-4dc8-8155-aa1a945ec081`
`Content-Type: application/pdf`
`Content-Disposition: form-data; filename=479694_001.pdf; name=479694_001`

Dovrebbe provare a rimuovere le `"` dal boundary nell' header

**Comment by PentaSistemi-DEVteam** [comment]
Abbiamo raccolto il vostro suggerimento di eliminare i doppi apici ["] ma nonostante ciò continuiamo a ricevere questo errore:

{"type":https://govway.org/handling-errors/502/InvalidResponse.html,"title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"9e58fab9-fb9a-11ed-80ae-005056ae7395"}

Rimaniamo in attesa di un suggerimento per la correzione.

**Comment by PentaSistemi-DEVteam** [comment]
Grazie mille, funziona!
