### ISSUE TITLE
PlayingEntity prefix del dottore ottiene errore : ERRORE-47 

### ISSUE THREAD

**Issue by stefanomastrogiacomo** [ministero-salute/it-fse-support#363]
Salve a tutti e buon pomeriggio,
facendo i test di validazione dall'impianto di test di un cliente è emerso un errore di validazione per cui vorremmo un chiarimento.
Scenario LAB
Referto di un paziente contenente i dati dei validatori (dottori e dottoresse) collegati agli esami nei tag previsti
/ClinicalDocument/component[1]/structuredBody[1]/component[5]/section[1]/component[1]/section[1]/entry[1]/act[1]/entryRelationship[2]/observation[1]/participant[1]/participantRole[1]/playingEntity[1]/name[1]
Il tag in questo esempio contiene i sottotag family,given,prefix e sono valorizzati con i dati di Cognome Nome e titolo della dottoressa o del dottore che ha validato l'esame
Nella risposta del gateway il prefix risulta non permesso.
Se configuro il sistema omettere i prefix, il referto finale non conterrà il titolo della dottoressa o del dottore.
Il cliente chiede di visualizzare questa informazione
Come possiamo fare?
Grazie e saluti
Stefano.
 
![image](https://github.com/ministero-salute/it-fse-support/assets/124671051/19b6808f-7cb2-4d43-b049-18fe0431efd6)

Estratto del json:
...
[ERRORE-47| L’elemento 'name' di un'organizzazione non deve contenere i sotto elementi 'delimiter', 'prefix', 'suffix'.]

**Comment by IStacchiotti** [comment]
Buonasera, le confermiamo che è stata rilasciata una modifica allo schematron. La invitiamo cortesemente a riprovare, la segnalazione dovrebbe essere ora risolta. Rimaniamo a completa disposizione in caso contrario. Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
