### ISSUE TITLE
OID AccessionNumber radiologia

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#364]
Buonasera,
sapreste indicarmi OID da utilizzare per indicare Accession Number nel CDA di Radiologia?
é corretto questo formato? :
2.16.840.1.113883.2.9.2.[CODICE_STRUTTURA_STS11].4.13.1

Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, per riportare correttamente il codice STS11, è necessario valorizzare l'attributo root tramite l'OID 2.16.840.1.113883.2.9.4.1.3 e riportare il codice della struttura all'interno dell'attributo extension, come indicato da specifiche HL7.

**Comment by alessandropassamonti** [comment]
Buongiorno,
nelle specifiche Hl7 viene riportato questo esempio:
`<inFulfillmentOf >
	<order> 
		<id extension="[ACCESSION_NUMBER]"
			root="[OID_ACCESSION_NUMBER]"/>
			<priorityCode code="R" codeSystem="2.16.840.1.113883.5.7" codeSystemName="HL7 ActPriority" displayName="Normale"/>
	</order>
</inFulfillmentOf>`

non è chiaro il valore da inserire in  [OID_ACCESSION_NUMBER]

grazie

**Comment by IStacchiotti** [comment]
Buonasera, da specifiche l'OID associato all'Accession Number non è vincolato, pertanto è possibile valorizzare il campo come proposto.

**Comment by IStacchiotti** [comment]
Buongiorno, procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
