### ISSUE TITLE
Impossibile accedere al servizio di test: https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1

### ISSUE THREAD

**Issue by dinelliascom** [ministero-salute/it-fse-support#365]
Buongiorno,

premetto che abbiamo già effettuato l'accreditamento, stiamo effettuando alcune prove in ambiente di test all'url indicato in oggetto, ma stiamo ricevendo il seguente messaggio di errore:

Error calling Validate: { "type": "https://govway.org/handling-errors/503/GatewayError.html", "title": "GatewayError", "status": 503, "detail": "The gateway is currently unable to handle the response", "X-Global-Transaction-ID": "3f7e3e2d646dc0a01347f8ff" } 

potete indicarci il motivo?
Grazie in anticipo.

**Comment by IStacchiotti** [comment]
Buongiorno @dinelliascom, non ci risultano interventi in corso, inoltre abbiamo verificato il corretto funzionamento del sistema. Potrebbe cortesemente riprovare? Le chiediamo di farci sapere se l'errore persiste. Grazie

**Comment by dinelliascom** [comment]
Buongiorno,

purtroppo stiamo riscontrando questo problema da quando i files pdf, a differenza di quelli che abbiamo utilizzato per l'accreditamento, sono di grosse dimensioni (ad es. > 10MB).

**Comment by IStacchiotti** [comment]
Buondì, potrebbe allegarci il file utilizzato cortesemente, in modo da consentirci di condurre una verifica? Grazie

**Comment by dinelliascom** [comment]
[Test.pdf](https://github.com/ministero-salute/it-fse-support/files/11564705/Test.pdf)
Buongiorno,
In allegato un es. di file pdf, che stiamo provando ad inviare e che produce l'errore riscontrato. 
Abbiamo notato inoltre che se la dimensione è intorno a 3/4 MB la risposta invece è la seguente:
{
    "detail": "Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.impl.FileSizeLimitExceededException: The field file exceeds its maximum permitted size of 1048576 bytes.",
    "instance": "",
    "spanID": "11353ef6df30fe52",
    "status": 500,
    "title": "Errore generico.",
    "traceID": "11353ef6df30fe52",
    "type": "/msg/generic-error"
}  
Il servizio in produzione sarà limitato a 1MB come quello di test?

Grazie in anticipo.

**Comment by IStacchiotti** [comment]
Buonasera, la informiamo che sono in corso le analisi al momento, riceverà un riscontro quanto prima. 
Seguirà anche un aggiornamento del documento di specifiche fornitori con questa informazione.

Grazie
