### ISSUE TITLE
Mancato accreditamento MethodCode

### ISSUE THREAD

**Issue by ZucchettiCentroSistemi** [ministero-salute/it-fse-support#367]
Buongiorno,
abbiamo ricevuto notifica di mancato accreditamento per il seguente problema:
{
  "id" : 4,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='013' attribute='codeSystem' actual = '' expected = '2.16.840.1.113883.5.84'>ClinicalDocument/component/structuredBody/component/section/component/section/entry/act/entryRelationship/organizer[classCode='CLUSTER']/component/organizer[classCode='BATTERY']/component/observation/methodCode</error>"
}
il tag methodCode però nelle specifiche è riportato come opzionale e il gateway non aveva dato problemi in fase di validazione.
Cosa devo fare per risolvere?
Grazie

**Comment by IStacchiotti** [comment]
Buon pomeriggio, grazie della segnalazione. Specifichiamo che bisogna inserire tutti gli elementi che, anche se sono opzionali da guida, per il nostro caso d’uso sono necessari per completezza di informazione. Bisogna fare riferimento all’excel fornito con le giuste valorizzazioni dei campi da inserire. Nel caso particolare in cui i dati non siano disponibili a sistema oppure nel caso in cui non si possa completare il test case correttamente, è possibile indicare NO nell’apposita colonna "Applicabilità", avendo cura di giustificarlo opportunamente nella colonna "razionale di applicabilità".

**Comment by IStacchiotti** [comment]
Buongiorno, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
