### ISSUE TITLE
Pubblicazione Test Case 

### ISSUE THREAD

**Issue by dtsconsulting** [ministero-salute/it-fse-support#369]
Buongiorno 
abbiamo ripostato tutto 
potreste effettuare una verifica grazie mille

https://github.com/ministero-salute/it-fse-accreditamento/pull/495#

commonName: S1#111DTSCONSULTI
subject_application_vendor: DTSCONSULTINGSRL
subject_application_id: DTSHIS
subject_application_version: 1.0

**Comment by IStacchiotti** [comment]
Buongiorno @dtsconsulting, purtroppo ci risultano 3107 file nella nuova pr, come da screen allegato.
![image](https://github.com/ministero-salute/it-fse-support/assets/122798799/3aa37422-c118-408c-a4ff-00f4939f63e2).

Dovreste fare fork del repository, nella vostra copia aggiungere tutta l'alberatura e i file necessari, fare commit delle modifiche e infine fare una pull request per integrare le modifiche nel repository principale. Nella pull requeste devono risultare solo i file di vostra competenza.

**Comment by dtsconsulting** [comment]
Buongiorno il repository contiene solo i nostri file che sono 192 il restante 3000 file sono Changed ovvero eliminati.
Questra è l'immagine del repository.
![image](https://github.com/ministero-salute/it-fse-support/assets/130453673/ea5bc1df-43af-45d1-a63a-df683dbfd122)

**Comment by masciamariotti** [comment]
Buongiorno,
così facendo, una volta mergiata la pull request, andrà a cancellare tutti i file del repository che ha contrassegnato come eliminati.
La PR deve contenere soltanto la sua folder

**Comment by dtsconsulting** [comment]
Ho eliminato la fork preesistente
ora faccio una nuova fork!

**Comment by dtsconsulting** [comment]
ho fatto la nuova fork 
sto provando ad aprire la fork con visual studio ma mi compare quest errore

È stato rilevato un errore durante la clonazione del repository remoto: Git failed with a fatal error.
unable to checkout working tree
Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by IStacchiotti** [comment]
Buongiorno, Le confermiamo che la pull request risulta ora corretta e che è stata presa in carico. Chiudiamo il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
