### ISSUE TITLE
Validazione documento: AuthorizationContentDeny

### ISSUE THREAD

**Issue by davidetau** [ministero-salute/it-fse-support#37]
Quando contattiamo il gateway di test per la validazione del CDA otteniamo la seguente response di errore:
`{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"1f497211-8135-11ed-b21d-005056ae54fa"}`
Abbiamo firmato i jwt di autenticazione e di firma con il certificato di signature. Grazie

**Comment by pFonziSogei** [comment]
Salve, sembra che l'issuer abbia degli slash aggiuntivi: "integrity:S1\\#NOMEFORNITORE
