### ISSUE TITLE
Laboratorio Test case 1 - Errore JWT payload: Tipologia documento diversa dalla tipologia di CDA  (code - codesystem)

### ISSUE THREAD

**Issue by gsdefender** [ministero-salute/it-fse-support#372]
Salve,  cerchiamo di trasmettere il test case n° 1 di laboratorio analisi. Il payload del token integrityToken è
```
{  "iss": "integrity:S1#111INNOGEASRLX",
  "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
  "iat": 1685095672,
  "exp": 1685099272,
  "sub": "CPLMNL87R07G273N^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "jti": "c30795ee-9d7d-49a4-b2c5-459e15e20665",
  "subject_organization_id": "190",
  "subject_organization": "Regione Sicilia",
  "locality": "190202401",
  "subject_role": "DRS",
  "person_id": "DLRLDI61M45G273Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "patient_consent": true,
  "purpose_of_use": "TREATMENT",
  "resource_hl7_type": "11502-2^^2.16.840.1.113883.6.1",
  "action_id": "CREATE",
  "attachment_hash": "f90ddda251affd771825622f1d412b168978236f951a840ae1886b9ea0131bb4",
  "subject_application_id": "CareMed",
  "subject_application_vendor": "Innogea srl",
  "subject_application_version": "1.0"
}
```

Il documento che proviamo a trasmettere è questo:
[D000016198.pdf](https://github.com/ministero-salute/it-fse-support/files/11574237/D000016198.pdf)

L'errore riportato dal servizio di validazione è:

JWT payload: Tipologia documento diversa dalla tipologia di CDA 
(code - codesystem)

L'allegato CDA2 del PDF a noi sembra corretto, non è chiaro a cosa sia dovuto il messaggio d'errore. 
Grazie dell'attenzione

**Comment by masciamariotti** [comment]
Buon pomeriggio,
dovrebbe correggere il valore del campo resource_hl7_type nel JWT
da:
`"resource_hl7_type": "11502-2^^2.16.840.1.113883.6.1"`
a:
`"resource_hl7_type": "('11502-2^^2.16.840.1.113883.6.1')"`

**Comment by gsdefender** [comment]
Salve, anche effettuando la correzione (che non sarebbe coerente con l'esempio di token decodificato riportato nelle specifiche) non cambia nulla.

**Comment by gsdefender** [comment]
Mi correggo: effettivamente passando (' e ') l'errore non viene restituito; viene restituito un errore (coerente con il validatore Lantana) di validazione del CDA2. Bisogna però correggere l'esempio di token decodificato nella documentazione, dove il resource_hl7_type è riportato senza apici e parentesi. Grazie
