### ISSUE TITLE
Processo accreditamento

### ISSUE THREAD

**Issue by dtsconsulting** [ministero-salute/it-fse-support#373]
Buongiorno ho modificato i file come da vostra comunicazione Email,
ho provveduto a eseguire la commit sulla mia fork.
volevo sapere se devo eseguire una nuova pull request?
oppure va bene

**Comment by masciamariotti** [comment]
Buon pomeriggio,
essendo la precedente pull request ancora aperta, è sufficiente la commit già effettuata.

**Comment by dtsconsulting** [comment]
buongiorno ho committato il nuovo file report_cecklist

**Comment by IStacchiotti** [comment]
Buongiorno, grazie per il riscontro, le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
