### ISSUE TITLE
Accreditamento S1#111ONIT0000000 OnitGroup SIRVa V.4.43.0.0

### ISSUE THREAD

**Issue by Fusarolia** [ministero-salute/it-fse-support#376]
Abbiamo rilasciato la versione 4.43 dell'applicativo SIRVa, visto che la versione accreditata è  V.4.42.0.0, ma il cda non ha subito variazioni, chiediamo che anche la versione in oggetto venga accreditata come minor release

In attesa di riscontro, distinti saluti

**Comment by IStacchiotti** [comment]
Buongiorno @Fusarolia, è possibile dichiarare l'equivalenza della versioni. La rimandiamo alla documentazione disponibile al seguente [link ](https://github.com/ministero-salute/it-fse-accreditamento#gestione-equivalenza-versione-software) in cui è dettagliata la procedura da seguire.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
