### ISSUE TITLE
Dizionario per CausaAccesso_VPS

### ISSUE THREAD

**Issue by adal72** [ministero-salute/it-fse-support#377]
Nel verbale di Pronto Soccorso non riusciamo a trovare il dizionario dei possibili valori per il campo "Causa Accesso", che dovrebbero essere invece reperibili in 
https://art-decor.org/art-decor/decor-valuesets--vpsee-?id=2.16.840.1.113883.2.9.1.11.1.2.12

Trattasi di chiarimento necessario per far fronte alla seguente segnalazione di verifica non superata (mancato accreditamento)

{  "id" : 24,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='033' attribute='codeSystemName' actual = '' expected = 'ProblemaPrincipale_VPS CausaAccesso_VPS'>ClinicalDocument/component/structuredBody/component/section[ID='Motivo_Visita']/entry/observation/value</error>"
}

Grazie

**Comment by IStacchiotti** [comment]
Buonasera, abbiamo svolto le verifiche del caso e ci risulta che l'errore segnalato è dovuto all'errata valorizzazione della section di seguito nel cda:
- [@ID="Motivo_Visita"] (to be)
- [@ID="MOTIVO_DELLA_VISITA"] (as is).
Potreste verificare? Rimaniamo a disposizione per ulteriore supporto. Grazie

**Comment by ponsilva** [comment]
Anche a me risulta la stessa cosa, CausaAccesso_VPS non è codificata.

Nell'implementation guide VPS, cap 4.2.5.2 Causa di accesso: entry/observation 
value ST

e anche nell'esempio su github
`<value xsi:type="ST">[DESC_CAUSA]</value>`

**Comment by IStacchiotti** [comment]
Buongiorno a tutti, confermiamo che l'elemento `entry/observation/value` di Causa Accesso non è più un elemento codificato ma un campo di tipo stringa.

**Comment by adal72** [comment]
grazie a tutti, chiudo la issue
