### ISSUE TITLE
Richiesta certificati di test FSE2.0

### ISSUE THREAD

**Issue by GrecoStefano** [ministero-salute/it-fse-support#378]
Salve,
si fa richiesta, a seguito di mail,  dei certificati di test per accedere al gateway di pre-produzione del fornitore POLIS-NET S.R.L per l’accreditamento dei software SIS4CARE

Grazie in anticipo

**Comment by IStacchiotti** [comment]
Buongiorno @GrecoStefano, ci risulta che abbia già ricevuto i certificati pem via email dall'indirizzo [fse_support@sogei.it](mailto:fse_support@sogei.it). Se il suo dubbio riguarda la generazione dei certificati p12, specifichiamo che vanno costruiti a partire dai pem. La rimandiamo ai seguenti link: [1](https://developersitalia.slack.com/archives/C03RDT88FSM/p1671519797974139?thread_ts=1671467530.530709&cid=C03RDT88FSM); [2](https://developersitalia.slack.com/archives/C03RDT88FSM/p1681817149022559). Ci faccia sapere se il problema persiste, grazie.

**Comment by GrecoStefano** [comment]
Buongiorno @IStacchiotti, i certificati richiesti in precedenza e ricevuti da fse_support@sogei.it sono stati generati a partire da file crs

**Comment by masciamariotti** [comment]
Buongiorno,
Le confermiamo che il canale corretto per la richiesta di certificati è la mail che ha già provveduto ad inviare.
Pertanto chiudiamo il presente ticket in quanto seguiranno aggiornamenti via mail.
