### ISSUE TITLE
Errore 500 in fase di pubblicazione documento

### ISSUE THREAD

**Issue by gmarzi** [ministero-salute/it-fse-support#38]
In fase di pubblicazione documenti (scheda vaccinale - certificato vaccinazione) ricevo il seguente messaggio di errore:
500{"traceID":"3c794575104fb08a","spanID":"3c794575104fb08a","type":"/msg/generic-error","title":"Errore generico.","detail":"BusinessException: Error while running create fhir resources : ","status":500,"instance":""} "

**Comment by pFonziSogei** [comment]
Salve, le chiederei di fare un test con scheda vaccinale e certificato vaccinazione e dare feedback sull'esito. Grazie

**Comment by pFonziSogei** [comment]
Salve, attendiamo esito del test e, in caso negativo, le chiederei di aprire una nuova issue collegandola a questa con il numero 38
