### ISSUE TITLE
ERRORE-46| codice fiscale '' cittadino ed operatore: 16 cifre [A-Z0-9]{16}

### ISSUE THREAD

**Issue by gsdefender** [ministero-salute/it-fse-support#381]
Salve,
abbiamo provato a validare con il validatore Lantana l'allegato cda2.xml a [questo documento PDF](https://github.com/ministero-salute/it-fse-support/files/11625849/D000016198.pdf) che mandiamo come test case 1 di laboratorio. La validazione viene effettuata con successo quindi pensiamo che il nostro XML vada bene.
Il validatore in uso in modipa-val.fse.salute.gov.it invece restituisce l'errore in oggetto.
Cosa stiamo sbagliando?

**Comment by masciamariotti** [comment]
Buon pomeriggio,
l'errore riscontrato è dovuto al fatto che non sta inviando l' attributo extension nel campo id del legalAuthenticator/assignedEntity:

`  <legalAuthenticator>`
`    <time value="20230531184324+0200"/>`
`    <signatureCode code="S"/>`
`    <assignedEntity>`
`      <id root="2.16.840.1.113883.2.9.4.3.2"/>`

**Comment by gsdefender** [comment]
Confermata regressione nella generazione del CDA2 in legalAuthenticator nel ns. software.

Grazie

**Comment by gsdefender** [comment]
Confermata regressione nella generazione del CDA2 in legalAuthenticator nel ns. software.

Grazie
