### ISSUE TITLE
Codici Loinc-Codici Ministeriali

### ISSUE THREAD

**Issue by emarano74** [ministero-salute/it-fse-support#383]
Buongiorno
Esiste una mappatura tra i codici loinc e i codici ministeriali per le analisi cliniche? Se si dove la posso trovare?

**Comment by IStacchiotti** [comment]
Buongiorno, vorremmo sapere a quali codici ministeriali si fa riferimento in quanto per le prestazioni di laboratorio si utilizza la codifica LOINC, e qualora non fossero presenti vengono utilizzati i codici regionali/locali.

**Comment by emarano74** [comment]
Buongiorno, potete chiudere ho risolto.
