### ISSUE TITLE
Controllo errato - bloccante - in schematron del Certificato Vaccinale

### ISSUE THREAD

**Issue by giuseppe-fasulo** [ministero-salute/it-fse-support#384]
Buongiorno. Si segnala quanto segue: 
ai fini del test di accreditamento stiamo generando dei CDA del certificato vaccinale; durante le prove  è emersa una incompatibilità rispetto ad uno dei controlli dello schematron.
All’interno dell’elemento author, l’assignedAuthor può contenere assignedPerson oppure assignedAuthoringDevice a seconda che l’autore sia una persona fisica oppure un applicativo software; 
**nel nostro caso adoperiamo** assignedAuthoringDevice.
Ora, nello schematron è presente il seguente controllo: 

<let name="name_author" value="hl7:assignedAuthor/hl7:assignedPerson"/>
<assert test="(count(hl7:assignedAuthor/hl7:id/@nullFlavor)=1 or  count(hl7:assignedAuthor/hl7:id[@root='2.16.840.1.113883.2.9.6.3.2'])=1) or count($name_author/hl7:name)=1">

Verifica che sia presente l’id dell’assignedAuthor o il name dell’assignedPerson. 
Dato che nel nostro CDA forniamo  assignedAuthoringDevice anziché assignedPerson, la validazione rispetto allo schematron restituisce erroneamente l’errore associato al controllo suddetto: “ERRORE-26| L'elemento <name/>/assignedAuthor/assignedPerson DEVE contenere un elemento 'name'”,
aspettandosi un elemento name anche in assenza dell’assignedPerson (assignedauthor e assignedAuthoringDevice infatti non possono contenere un elemento name). 
Bisognerebbe modificare il controllo creando due distinti check,  uno per verificare la presenza di assignedAuthor/id ed un altro per la presenza di assignedPerson/name, in modo che lo schematron non si aspetti un name se non all’interno di assignedPerson.
L'errore è bloccante nello scenario di applicazione  per cui,

Restiamo in attesa di un vs riscontro
Grazie

**Comment by giuseppe-fasulo** [comment]
[TC_CERT_VACC_1.zip](https://github.com/ministero-salute/it-fse-support/files/11664560/TC_CERT_VACC_1.zip)
Buongiorno.
In allegato il file di test utilizzato

**Comment by IStacchiotti** [comment]
Buongiorno @giuseppe-fasulo, dalle analisi svolte, risulta che il CDA2 fornito passi la validazione semantica e che non venga generato l'errore segnalato (errore 26).
In ogni caso confermiamo che nel caso in cui l'autore sia l'applicativo, assignedPerson diventa un elemento opzionale, mentre è obbligatorio nel caso in cui l'id dell'author è un codice fiscale, generando così l'errore 26 se assignedPerson non è presente.
Le chiediamo cortesemente di riprovare e, nel caso in cui l'errore dovesse persistere, di fornirci il pdf con allegato il cda utilizzato e la risposta restituita dal sistema. Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.

**Comment by giuseppe-fasulo** [comment]
Buongiorno. Va bene. Non ho avuto ulteriori feedback dallo sviluppo. Grazie
