### ISSUE TITLE
Vocabolari validazione Verbale di Pront Soccorso (VPS) 

### ISSUE THREAD

**Issue by stellariAbstract** [ministero-salute/it-fse-support#385]
Buonasera.
Sto approntando i primi test di validazione di VPS ed ho un problema similare, se non il medesimo.

_Almeno uno dei seguenti vocaboli non è censito:
[CodeSystem: 2.16.840.1.113883.2.9.6.1.54.6, Codes: 3 ],
[CodeSystem: 2.16.840.1.113883.2.9.6.1.54.1, Codes: 6 ],
[CodeSystem: 2.16.840.1.113883.6.103, Codes: 519.72]_

Per quanto riguarda i primi due, sono identici al vostro VPS di esempio al link [https://github.com/ministero-salute/it-fse-support/blob/3179a3ca1347b4675ff1f59a37f6f4b06d51359f/doc/esempi/CDA/VPS.xml](url)

Relativamente ad una vostra precedente risposta alla issue #24 , dove viene risposto" A breve verranno pubblicati tutti i dizionari da usare su GitHub", gentilmente chiedo se sono stati pubblicati i suddetti dizionari e dove potrei reperirli.

Inoltre, dovendo rispettare anche le specifiche regionali imposte dal servizio SOLE dell'Emilia Romagna, mi chiedo come questi dizionari non vengano accettati dal GATEWAY FSE (mentre lo siano da SOLE) e come rendere i due compatibili, dovendo validare sul GATEWAY FSE e pubblicare su SOLE.

Grazie,
Stefano.

**Comment by stellariAbstract** [comment]
Allego il PDF ed il CDA.

Ne approfitto per segnalare inoltre che lo schematron messo a disposizione non rileva il problema che poi viene segnalato nella response della chiamata.

Grazie.

[PDF_v5.pdf](https://github.com/ministero-salute/it-fse-support/files/11690066/PDF_v5.pdf)
[cda_v5.txt](https://github.com/ministero-salute/it-fse-support/files/11690075/cda_v5.txt)

**Comment by vigliottim** [comment]
Buongiorno, la informiamo che è stato rilasciato un aggiornamento. La invitiamo cortesemente a riprovare. Rimaniamo a disposizione in caso fosse necessario ulteriore supporto. Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
