### ISSUE TITLE
Richiesta verifica #545 Euromedical

### ISSUE THREAD

**Issue by mmaggi69** [ministero-salute/it-fse-support#387]
Ho aggiornato il file data.json potreste effettuare verifiche ?

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che la pull request è stata presa in carico. Procediamo alla chiusura del presente ticket dal momento che eventuali aggiornamenti saranno comunicati via email. Per eventuali ulteriori richieste di supporto, sarà possibile procedere con l'apertura di un nuovo ticket.
