### ISSUE TITLE
processo convalida nuova tipologia di documento (VPS)

### ISSUE THREAD

**Issue by gfoini** [ministero-salute/it-fse-support#388]
Buongiorno. Abbiamo ricevuto la conferma del completamento Fase 1 del processo di convalida sul tipo documento RAD
con la PL :
[https://github.com/ministero-salute/it-fse-accreditamento/pull/468]
che risulta ancora in stato "DEEP DIVE"

Qualche giorno fà abbiamo uploadato i file relativi al tipo documento VPS , è corretto? come dobbiamo procedere?
grazie e buon lavoro

**Comment by IStacchiotti** [comment]
Buongiorno @gfoini, le confermiamo che la pull request è stata recepita. La label "DEEP DIVE" identifica il fatto che ha ricevuto delle richieste di chiarimenti via email da parte del DTD. Abbiamo notato che nella pr #468 però sono presenti file che si riferiscono ad un diverso applicativo afferente a FUJIFILM, potreste verificare? Inoltre segnaliamo che la cartella padre non dovrebbe essere il "GATEWAY", ma dovrebbe essere la sottocartella che contraddistingue il vostro applicativo specifico. Grazie
<img width="611" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/122798799/82f5eb06-e1ef-4848-9b9d-951a328ba2c9">

**Comment by gfoini** [comment]
già.. credo la problematica sia dovuta ad un "Sync fork" + "Update Branch" che in qualche modo ha coinvolto file della cartella Fujifilm, cosa ovviamente non voluta.
Non siamo molto pratici nella gestione su github, chiedo scusa, ma come possiamo ovviare alla problematica? 
Facciamo una discard dei 6 commit o ... altro?
grazie in anticipo

**Comment by IStacchiotti** [comment]
Buongiorno @gfoini, vi suggeriamo di procedere con il discard delle commit e con il successivo nuovo caricamento dei soli file di vostra competenza nella pull request. Una nota: con il discard potreste perdere i file caricati, quindi eventualmente salvateli preventivamente in assenza di altre copie. Rimaniamo a disposizione nel caso in cui fosse necessario ulteriore supporto. Grazie

**Comment by gfoini** [comment]
> Buongiorno @gfoini, vi suggeriamo di procedere con il discard delle commit e con il successivo nuovo caricamento dei soli file di vostra competenza nella pull request. Una nota: con il discard potreste perdere i file caricati, quindi eventualmente salvateli preventivamente in assenza di altre copie. Rimaniamo a disposizione nel caso in cui fosse necessario ulteriore supporto. Grazie

grazie, abbiamo proceduto come da Vs suggerimento.
Abbiamo aperto la pull request per il nuovo tipo di documento.
https://github.com/ministero-salute/it-fse-accreditamento/pull/562
buona giornata
