### ISSUE TITLE
Controlli bloccanti in schematron Certificato Vaccinale - ICD9-CM vs. codifica AVN

### ISSUE THREAD

**Issue by giuseppe-fasulo** [ministero-salute/it-fse-support#389]
Buongiorno. 
A seguito di test eseguiti in fase di produzione del certificato vaccinale, si riporta quanto segue:

### Contesto di riferimento
_Value codificati presenti all’interno della entry relativa a Dati della vaccinazione_  
 
**Codifica del value di “Condizioni sanitarie a rischio”** 

L’elemento: ClinicalDocument/component/structuredBody/component/section/entry/substanceAdministration/entryRelationship/observation/value 

relativo alle Condizioni sanitarie a rischio deve contenere gli attributi @code, @codeSystem @codeSystemName, @displyName che devono essere valorizzati da specifiche HL7 secondo il sistema di codifica ICD9-CM (OID del sistema di codifica =2.16.840.1.113883.6.103);  è presente un controllo bloccante sullo schematron. 
Tuttavia, per tale valorizzazione sono a disposizione i dati provenienti dal flusso omonimo di AVN “Condizioni sanitarie a rischio” (OID del sistema di codifica = 2.16.840.1.113883.2.9.6.1.56.1) 
 
**Codifica del value di “Reazioni avverse”** 
L’elemento: ClinicalDocument/component/structuredBody/component/section/entry/substanceAdministration/entryRelationship/observation/value 

relativo alle Reazioni avverse deve contenere gli attributi @code, @codeSystem @codeSystemName, @displyName che devono essere valorizzati da specifiche HL7 secondo il sistema di codifica ICD9-CM (OID del sistema di codifica =2.16.840.1.113883.6.103); è presente un controllo bloccante sullo schematron. 

Tuttavia, per tale valorizzazione sono a disposizione i dati provenienti dal flusso omonimo di AVN “Classificazione reazioni avverse” (OID del sistema di codifica = 2.16.840.1.113883.2.9.6.1.32) 

Value codificati presenti all’interno sia della entry relativa a Dati della vaccinazione che a Dati di esonero, omissione, differimento 

**Codifica del value di “Malattie per cui si effettua la vaccinazione”** 

L’elemento: ClinicalDocument/component/structuredBody/component/section/entry/substanceAdministration/entryRelationship/observation/value 

relativo alle Malattie per cui si effettua la vaccinazione deve contenere gli attributi @code, @codeSystem @codeSystemName, @displyName che devono essere valorizzati da specifiche HL7 secondo il sistema di codifica ICD9-CM (OID del sistema di codifica =2.16.840.1.113883.6.103); è presente un controllo bloccante sullo schematron.  
Tuttavia, per tale valorizzazione sono a disposizione i dati provenienti dal flusso di AVN con la lista delle Vaccinazioni (OID del sistema di codifica = 2.16.840.1.113883.2.9.2.30.6.2) 

 

Value codificati presenti all’interno della entry relativa a Dati di esonero, omissione, differimento 

**Codifica del value di “Malattia con presunta immunità”** 

L’elemento: ClinicalDocument/component/structuredBody/component/section/entry/substanceAdministration/entryRelationship/observation/value 

relativo alla Malattia con presunta immunità deve contenere gli attributi @code, @codeSystem @codeSystemName, @displyName che devono essere valorizzati da specifiche HL7, secondo il sistema di codifica ICD9-CM (OID del sistema di codifica =2.16.840.1.113883.6.103); è presente un controllo bloccante sullo schematron. 
Tuttavia, per tale valorizzazione sono a disposizione i dati provenienti dal flusso di AVN "Antigeni/principi vaccinali" (OID del sistema di codifica = 2.16.840.1.113883.2.9.6.1.56.4) 

 

### Proposta di modifica dello schematron 

 Sullo schematron del certificato vaccinale, sono presenti dei controlli, i quali stabiliscono che, ogni elemento observation/value appartenente alle seguenti entryRelationship: 

Condizioni sanitarie a rischio 
Reazioni avverse 
Malattia per la quale si effettua la vaccinazione 
Malattia con presunta immunità 
deve avere l’attributo @codesystem = “2.16.840.1.113883.6.103”, ovvero la codifica dell’elemento value deve appartenere al sistema di codifica ICD9CM. Tali controlli sono bloccanti e non permettono di valorizzare l’elemento con le codifiche dei sistemi di codifica resi disponibili invece da AVN. Poiché i dati che si hanno a disposizione nel contesto regionale non sono quelli codificati secondo ICD9CM ma secondo AVN, si richiede di poter rilassare il controllo, sostituendolo con un warning, oppure ammettere le codifiche AVN,in modo da evitare di dover omettere tali informazioni solo perché non corrispondenti al dizionario indicato. 
Infatti, pur non essendo obbligatori gli elementi entryRelationship in questione, essi sono importanti al fine di costituire un documento vaccinale completo ed esaustivo.

**Comment by IStacchiotti** [comment]
Buongiorno, la ringraziamo per le segnalazioni. Lo schematron verrà modificato per permettere la valorizzazione delle entryRelationship anche tramite i sistemi di codifica provenienti dal flusso AVN. Le daremo evidenza non appena l'evolutiva sarà rilasciata.
Per quanto riguarda la entryRelationship inerente alle "Malattie per cui si effettua la vaccinazione", l'OID proposto è un oid regionale, e da specifiche non viene fatto alcun riferimento al flusso AVN ma solo al sistema di codifica ICD-9-CM. Per tale motivo non verrà effettua la modifica a questa sezione.

**Comment by giuseppe-fasulo** [comment]
Buona sera. 
In effetti, in merito alla entryRelationship delle "Malattie per cui si effettua la vaccinazione", abbiamo commesso un errore in fase di test  riguardo al sistema di codifica da adottare, riportando una codifica regionale.
In effetti però,  abbiamo verificato  che per la codifica dell’elemento ClinicalDocument/component/structuredBody/component/section/entry/substanceAdministration/entryRelationship/observation/value inerente alla "Malattia per cui si effettua la vaccinazione", sono disponibili i dati provenienti dal flusso di AVN "Antigeni/principi vaccinali" (OID del sistema di codifica = 2.16.840.1.113883.2.9.6.1.56.4). Si potrebbe quindi, utilizzare questo sistema di codifica, alternativo a ICD9-CM, per popolare gli attributi [@code](https://github.com/code), [@codesystem](https://github.com/codesystem) @codeSystemName, @displayName del value, come tra l’altro è stato confermato per la entryRelationship relativa alla “Malattia con presunta immunità”.
  
Si richiede pertanto di rilassare il controllo dello schematron secondo cui l’attributo codeSystem deve essere valorizzato con l’OID di ICD9CM, sostituendolo con un warning oppure di ammettere le codifiche AVN per la entryRelationship relativa alla Malattia per cui si effettua la vaccinazione, come già concordato per le altre entryRelationship (Condizioni sanitarie a rischio, Reazioni avverse, Malattia con presunta immunità). 

Saluti.

**Comment by IStacchiotti** [comment]
Buongiorno, verranno modificati i controlli dando la possibilità di valorizzare l'elemento value inerente alla entryRelationship "Malattie per cui si effettua la vaccinazione" anche tramite l'OID del sistema di codifica = 2.16.840.1.113883.2.9.6.1.56.4

**Comment by IStacchiotti** [comment]
Buongiorno, Le confermiamo che è stata rilasciato un aggiornamento (gli schematron aggiornati sono disponibili ora a questo [link](https://github.com/ministero-salute/it-fse-support/tree/main/validazione/schematron)). La invitiamo cortesemente a riprovare. Rimaniamo a disposizione in caso fosse necessario ulteriore supporto. Grazie

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.

**Comment by giuseppe-fasulo** [comment]
Buongiorno. Continuiamo ad avere l'errore. Probabilmente lo schematron non è stato installato sul gateway ?

**Comment by IStacchiotti** [comment]
Buongiorno, grazie per il riscontro, procediamo allora alla riapertura del ticket. Potrebbe specificare a quale errore si riferisce? Le chiediamo inoltre di allegare in risposta il CDA e la response restituita dal sistema.

**Comment by giuseppe-fasulo** [comment]
Buongiorno. A fronte di altri test in fase di accreditamento per il certificato vaccinale  si segnala inoltre che il controllo di validazione richiede obbligatoriamente (**ma solo in alcuni casi di test**i) gli attributi del primo elemento <component>, quello che precede <structuredBody> . Gli attributi obbligatori richiesti sono   typeCode impostato a COMP e contextConductionInd impostato a true.  Si segnala pertanto che il controllo non è uniforme. [ {
  "id" : 16,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='148' attribute='typeCode' actual = '' expected = 'COMP'>ClinicalDocument/component</error>"
}, {
  "id" : 16,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='149' attribute='contextConductionInd' actual = '' expected = 'true'>ClinicalDocument/component</error>"
},

**Comment by giuseppe-fasulo** [comment]
Si allega a proposito della precedente segnalazione il file xml del CDA

**Comment by giuseppe-fasulo** [comment]
[cda.txt](https://github.com/ministero-salute/it-fse-support/files/11966801/cda.txt)

Si allega a proposito della precedente segnalazione il file xml del CDA

**Comment by vigliottim** [comment]
Buongiorno, il presente ticket è stato chiuso. Si tratta di un errore oppure non ha bisogno di supporto? Restiamo in attesa di un suo gentile riscontro.

**Comment by giuseppe-fasulo** [comment]
Buongiorno. E' stato un errore. E' ancora aperto. Ho aggiunto una ulteriore segnalazione a quella iniziale.

**Comment by vigliottim** [comment]
Grazie per la sua risposta. Le chiediamo gentilmente di aprire una nuova issue per rispondere alla sua nuova richiesta sull'accreditamento. Le daremo aggiornamenti al più presto in merito alla presente.

**Comment by vigliottim** [comment]
Buongiorno, le chiediamo di inviarci il dettaglio dell'errore ricevuto. Grazie.

**Comment by giuseppe-fasulo** [comment]
Buongiorno.  Riporto che 
per quanto concerne le codifiche AVN non si riscontrano più errori. Abbiamo corretto il problema relativo all'ID della section. Pe r cui questa segnalazione si può ritenere chiusa. Grazie
