### ISSUE TITLE
Aggiornato report checklist #553

### ISSUE THREAD

**Issue by mmaggi69** [ministero-salute/it-fse-support#390]
S1#111EUROMEDICAL
EUROMEDICAL
MEDIWEB
1.0

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che la pull request è stata presa in carico. Procediamo pertanto alla chiusura del presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
