### ISSUE TITLE
Chiarimenti sul processo di creazione pull request per accreditamento

### ISSUE THREAD

**Issue by Mcataranto** [ministero-salute/it-fse-support#391]
Avendo difficoltà nel generare le pull request vorremmo ripercorrere il processo premettendo che:
abbiamo creato il nostro repository partendo dalla cartella Gateway in cui abbiamo creato le cartelle appid/.../.. secondo lo schema richiesto. Nella cartella gateway sono stati creati i files data.json ed il report check list, nella cartella files/signed sono stati inseriti i file pdf firmati PADES.
Le operazioni per creare la pull request sono state 
1.abbiamo creato una fork con il repository Ministero-salute/it-fse-accreditamento
2.abbiamo tentato di aprire la pull request sul repository del ministero con il tasto "new pull request" ma la risposta è stata la schermata "Compare changes" con la scritta "Choose different branches or forks above to discuss and review changes. [Learn about pull requests](https://docs.github.com/articles/using-pull-requests)" ed i tasto verde di "create pull request" disabilitato, come da file allegato.

Dove sbagliamo? 

![Immagine 2023-06-08 112754](https://github.com/ministero-salute/it-fse-support/assets/124721774/1ec7dc3b-6d92-48a6-bf18-c92e8ad07014)

**Comment by IStacchiotti** [comment]
Buongiorno @Mcataranto, le suggeriamo di ripetere la procedura dall'inizio, seguendo le indicazioni presenti a questo
[link](https://developersitalia.slack.com/archives/C03RDT88FSM/p1678891023248609?thread_ts=1678890193.371019&cid=C03RDT88FSM).

**Comment by IStacchiotti** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
