### ISSUE TITLE
Aggiornato File report-checklist

### ISSUE THREAD

**Issue by mmaggi69** [ministero-salute/it-fse-support#392]
S1#111EUROMEDICAL
EUROMEDICAL
MEDIWEB
1.0

**Comment by IStacchiotti** [comment]
Buongiorno, Le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
