### ISSUE TITLE
Prefisso del documento non corrispondente al nodo invocato

### ISSUE THREAD

**Issue by ivocaturo** [ministero-salute/it-fse-support#393]
Ciao
ottengo questo warning a termine della validazione:
{"traceID":"f07ffa9b6ba24b06","spanID":"f07ffa9b6ba24b06","workflowInstanceId":"2.16.840.1.113883.2.9.2.80.3.1.4.4.a76abe6f7eece67b64964d50fa90b1ac5852384a939d9ce62a4155df565da37e.cada919817^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","warning":"--middlewarewarning-- Warning: Prefisso del documento non corrispondente al nodo invocato: 13p"}

A cosa si riferisce il "prefisso"?

**Comment by IStacchiotti** [comment]
Buongiorno, dalle analisi svolte risulta che il warning non si sia originato dai nostri sistemi. Pertanto La invitiamo a verificare se è presente un middleware regionale che si interpone tra il suo sistema e quelli nazionali, che possa averlo scatenato. Rimaniamo a disposizione nel caso in cui fosse necessario supporto ulteriore. Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.

**Comment by IStacchiotti** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
