### ISSUE TITLE
accreditamento 

### ISSUE THREAD

**Issue by dtsconsulting** [ministero-salute/it-fse-support#394]

**Comment by dtsconsulting** [comment]
https://github.com/ministero-salute/it-fse-accreditamento/pull/569

creata nuova pull request.
inviati i test modificati e i pdf Firmati, il DataJson contenente tutti i test e il report_checKList totale 14 file

**Comment by IStacchiotti** [comment]
Buon pomeriggio. Le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
