### ISSUE TITLE
Problema nell' invio al gateway del Referto di Specialistica Ambulatoriale

### ISSUE THREAD

**Issue by nbssrl** [ministero-salute/it-fse-support#395]
Buon pomeriggio,

stiamo svolgendo dei test sull'invio dei referti di specialistica ambulatoriale verso il gateway ma riceviamo il seguente errore:
{
  "traceID" : "5c2d4ee960c69ce4",
  "spanID" : "5c2d4ee960c69ce4",
  "type" : "/msg/semantic",
  "title" : "Errore semantico.",
  "detail" : "[ERRORE-5| L'elemento ClinicalDocument/code deve essere valorizzato con l'attributo @code='59258-4' e il @codeSystem='2.16.840.1.113883.6.1'],[ERROR-52| Il valore dell'elemento effectiveTime/high : '20230612000000' \n\t\t\tdeve essere maggione di quello di effectiveTime/low : '20230612000000'.],[ERRORE-b1| Sezione Modalità di Trasporto: la sezione DEVE essere presente],[ERRORE-b2| Sezione Modalità di Trasporto: la sezione deve contenere l'elemento templateId valorizzato con l'attributo @root='2.16.840.1.113883.2.9.10.1.6.20'],[ERRORE-b3| Sezione Modalità di Trasporto: la sezione DEVE contenere un elemento 'text' e un solo elemento 'entry'],[ERRORE-b4| Sezione Motivo della Visita: la sezione DEVE essere presente],[ERRORE-b5| Sezione Motivo della Visita: la sezione deve contenere l'elemento templateId valorizzato con l'attributo @root='2.16.840.1.113883.2.9.10.1.6.42'],[ERRORE-b6| Sezione Motivo della Visita: la sezione DEVE contenere l'elemento 'text'],[ERRORE-b7| Sezione Motivo della visita: la sezione DEVE contenere almeno una 'entry' relativa al Problema Principale e può contenere una seconda 'entry' relativa alla Causa di Accesso],[ERRORE-b8| Sezione Motivo della visita: l'elemento entry/observation relativo al \"Problema Principale\" DEVE contenere l'elemento templateId valorizzato con l'attributo @root='2.16.840.1.113883.2.9.10.1.6.37'],[ERRORE-b9| Sezione Motivo della visita: l'elemento entry/observation/code relativo al \"Problema Principale\" deve avere l'attributo @code valorizzato con '56817-0' e l'attributo @codeSystem con '2.16.840.1.113883.6.1'],[ERRORE-b10| Sezione Motivo della visita: l'elemento entry/observation/statusCode relativo al \"Problema Principale\" DEVE  assumere il valore 'completed'],[ERRORE-b11| Sezione Motivo della visita: l'elemento entry/observation/value relativo al \"Problema Principale\" DEVE essere valorizzato col value set ProblemaPrincipale_VPS],[ERRORE-b16| Sezione Triage: la sezione DEVE essere presente],[ERRORE-b17| Sezione Triage: la sezione deve contenere l'elemento templateId valorizzato con l'attributo @root='2.16.840.1.113883.2.9.10.1.6.21'],[ERRORE-b18| Sezione Triage: la sezione DEVE contenere un elemento 'text' e almeno un elemento 'entry'.],[ERRORE-b19| Sezione Dimissione: la sezione DEVE essere presente],[ERRORE-b63| Sezione Interventi, Prestazioni, Consulenze e Richieste: la sezione deve contenere l'elemento templateId valorizzato con l'attributo @root='2.16.840.1.113883.2.9.10.1.6.26'],[ERRORE-b170| Sezione Interventi Prestazioni Consulenze e Richieste: l'elemento entry/act DEVE contenere l'elemento templateId valorizzato con l'attributo @root='2.16.840.1.113883.2.9.10.1.6.62'.],[ERRORE-b172| Sezione Interventi Prestazioni Consulenze e Richieste: l'elemento entry/act DEVE contenere un elemento statusCode valorizzato con l'attributo @code='completed' o @code='aborted'.  ],[ERRORE-b75| Il codice '47045-0' non è corretto. La sezione deve essere valorizzata con uno dei seguenti codici:\n\t\t\t11459-5 Sezione Motivo di trasporto\n\t\t\t46239-0\tSezione Motivo della visita\n\t\t\t54094-8\tSezione Triage\n\t\t\t78337-3 Sezione Inquadramento clinico iniziale\n\t\t\t46240-8 Sezione Encounters\n\t\t\t8648-8  Sezione Decorso ospedaliero\n\t\t\t55109-3 Sezione Complicanze\n\t\t\t62387-6 Sezione Interventi, prestazioni, consulenze e richieste\n\t\t\t30954-2 Sezione Accertamenti\n\t\t\t8716-3  Sezione Parametri vitali\n\t\t\t29549-3 Sezione Terapia farmacologica in pronto soccorso\n\t\t\t28574-2 Sezione Dimissione\n\t\t\t18776-5 Sezione Piano di cura alla dimissione\n\t\t\t75311-1 Sezione Terapia farmacologica alla dimissione\n\t\t\t],[W001| Si raccomanda di valorizzare gli attributi dell'elemento ClinicalDocument/code nel seguente modo: @codeSystemName ='LOINC' e @displayName ='Verbale di Pronto Soccorso'.--> ]",
  "status" : 422,
  "instance" : "/validation/error",
  "workflowInstanceId" : "2.16.840.1.113883.2.9.2.110.586fb00a6b984ea3820aaf7fbe0b5db817e1eec25510f947b46f5ec53dfb89e4.6094a7d379^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

il token jwt che generiamo è il seguente:
eyJ4NWMiOlsiTUlJRkt6Q0NBeE9nQXdJQkFnSVVJN0R2MVRNbW5IdFg4d3h3V2ozU2QyUzd1bmN3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TXpBek16QXlNVFE1TVRWYUZ3MHlOakF6TXpBeU1UUTVNVFJhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMweE1URk9RbE5UVWt4WVdGaFlXREVhTUJnR0ExVUVBd3dSVXpFak1URXhUa0pUVTFKTVdGaFlXRmd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGtPdTNYVGxJNTJ0VFlrVDR0MVlETk5kaUZEK3hhaGZ6NXVHaHRpb0J4RVFHRk0zQTFDQnlNVGU4MDRpNXVNajNPQUJMSzdIWEppck4xaTdUNnZLUUtHZEsvT01JUXprU1oyeHJwbnJJenZHcTlDZ0NEeHh1SnVnbmQybUtZdkNNVFFSeUFRTGlpNUVobUU0MmljT3l3NFM3bEo2c25aa0F6cFFhUUROR3pFNnJiVldvSGFqTEdiNnp0S3g5Qjk0b0dUZ3hsOEVicUZINHRzMUtWalE4Tjh4K2V6SVZkdEJMbFFlWHFiUStLK0JIRlhIZXlpQzluOElyeXZKempZOXRIZXpBNThDNDJxeXZEWjVWVk02U2ZRUndWMVI4QUNqZ1lMMGRuS2diK1U4YkpLczcwaTFVNmdaTWh1ek5pT2IweWdrYmlIdDVyZjlvRkgvUWt2em9EQWdNQkFBR2pnZHd3Z2Rrd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3RWdZRFZSMGdCQXN3Q1RBSEJnVXJUQjBCQ3pCekJnTlZIUjhFYkRCcU1HaWdacUJraG1Kc1pHRndPaTh2WTJGa2N5NW1hVzVoYm5wbExtbDBMME5PUFVOQkpUSXdUV2x1YVhOMFpYSnZKVEl3WkdWc2JHRWxNakJUWVd4MWRHVWxNakJVWlhOMExFODlUV2x1YVhOMFpYSnZKVEl3WkdWc2JHRWxNakJUWVd4MWRHVXNRejFKVkRBZEJnTlZIUTRFRmdRVUQ2N2VkbFZuTFg2K0JvSlpXV0J2WEZ5WHM0NHdEZ1lEVlIwUEFRSC9CQVFEQWdaQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQmhpckFQeWRqQS9JY01VQnFRV1FETGErbzB5Q2hHdld1TG1SZUJmZExhUC9pZ25Eak5KTGdzdXN1UStteCtvWG9raTUyQjE4OW9TNlZaL3EwMjhWWklYQzBwUDQ1azk2SFI4Z3BoZHo4Z1NWT3BCcERYRHIwUkpxMWxQVGJtK2hyaTh4MzQ2aHhDSFg2dU9iZDdlaHFhMGVlUW5ZMXVzZXV3U0hlaW5Qc1hydjRCeFJsSjB5aWxxMFNpcVBBMis4TE1MbEJwTnZnc083L1EyVTFYZkRRQWViNUIxWFg0bXJLS1l2ZWJaT0tpcWZNbUlpaHN4WG5YOHZCNEdrV2EwK2QrY2lxZXVPM3JvZlhMU1pjcTl0SEF2ckVDdmVzQ1EyQ2NEN2JsbFFKUUxjeXZya0ZZV2YzRGFvNVZ0ZXFvdWtmcEwxM3Y5ZXY2b05QbG5mL2Nja3lUaWJ4YzhMbGpjTXV2NUFsRlZYdk1xa1ZkVkowL0t3V1g4K2VTRE5UR085SmtLQ1RBU01JTWdGOHdnM2NaZFRCMGdEOGVORkQrNEpEV2JnMUs2SWhNZkhWZktJZE1lK0JlZHNZSGtyd2VTY3BlU3cwek93eU4vUnZqYS9SZGtaSzdpYUdQMFFFRXVYZ3VSdGNQZExCNlF1UExIdmY5OHMvU0JheFBQYmU3UVV2Vmx5R3pnYlhCSlpYN0xkenh5a0JTdkpIdUlkNkxYT2QxMVJCV2VVQi96SWM5SzFlM1VLQ1YzVXloSDh4VVV6eXJ2M2FScTNETWM1YzFCenZnYlE0aXhBWnU4SnczKzlPVlN5UC85NDlqbExDMW9yek14QmIrc1BqeC9hazMveXZYOFNERVd1R3NEeVRzZUZEWjMxdkRjNUN2eHVqQWZLYWFTRWozRUZMdmtBPT0iXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJETU5NVFQ5NEMyMkg3NjlRXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImlzcyI6ImludGVncml0eTpTMSMxMTFOQlNTUkxYWFhYWCIsImxvY2FsaXR5IjoiMTEwMDA1MDIiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlcnNpb24iOiJ2LjQuMTAuMTA2Iiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb25lIE1hcmNoZSIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMTEwIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJhY3Rpb25faWQiOiJDUkVBVEUiLCJyZXNvdXJjZV9obDdfdHlwZSI6IignMTE0ODgtNF5eMi4xNi44NDAuMS4xMTM4ODMuNi4xJykiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoibmV0d29ya3Nhbml0YXJpbyIsImV4cCI6MTY4NjU4NjA5NCwic3ViamVjdF9hcHBsaWNhdGlvbl92ZW5kb3IiOiJOQlMiLCJpYXQiOjE2ODY1Nzg4OTQsImp0aSI6Il8yMDIzMDYxMjE2MDgxNF8iLCJwZXJzb25faWQiOiJQUlZQUlYyMFMyNUE0NjJXXl5eJmFtcDsyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImYW1wO0lTTyJ9.unVynQ4ZNusAYtIGAlSPbvwWN-cG6jm5GvSRM1rhpj-M7_bhEDR5wJnZBl2_4Rda_c9n6ezoXS-WP8pFcfQGXSd02VjAKVcE2ShR_rnTBtu0ppc5yGJm_x5LmaXZI8T8XMJBXhvD-SBVlyGN5aaQkX4LWC4q-fvOkbTYfFaZ2PA82TbOyhdZtEK7HkZ7HgwLtjC7B1P12iozPSMpNapFIkZAfdL8NfHb_mytlpLJFgECMM-gZkQSznmtb9LtrnPdWogDx7M26Kzfl1FbRVnTcqRogdt3KHsad7NAHTA_DJgP8GthxX9G4hf2K2c-iiJqBCTXXgRO-gWgwK7CVCB2Jg

sarebbe possibile svolere una verifica in merito al motivo per cui il gateway continua vedere il messaggio inviato come un VPS e non come un RSA?

**Comment by IStacchiotti** [comment]
Buonasera @nbssrl, potreste cortesemente allegare anche il cda in questione? Grazie

**Comment by nbssrl** [comment]
<ClinicalDocument xmlns="urn:hl7-org:v3" xmlns:sdtc="urn:hl7-org:sdtc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:hl7-org:v3 CDA.xsd">
	<realmCode code="IT"/>
	<typeId extension="POCD_MT000040UV02" root="2.16.840.1.113883.1.3"/>
	<templateId extension="1.1" root="2.16.840.1.113883.2.9.10.1.9.1"/>
	<id assigningAuthorityName="Regione Marche" extension="NBS_RSA_00000000000001667074" root="2.16.840.1.113883.2.9.2.1104.4"/>
	<code code="11488-4" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Nota di consulto"/>
	<title>Referto di Specialistica Ambulatoriale</title>
	<effectiveTime value="20230612163340"/>
	<confidentialityCode code="N" codeSystem="2.16.840.1.113883.5.25" codeSystemName="Confidentiality"/>
	<languageCode code="it-IT"/>
	<setId assigningAuthorityName="Regione Marche" extension="NBS_RSA_00000000000001667074" root="2.16.840.1.113883.2.9.2.80.3.1.4.4"/>
	<versionNumber value="1"/>
	<recordTarget>
		<patientRole classCode="PAT">
			<id assigningAuthorityName="Ministero Economia e Finanze" extension="PRVPRV20S25A462W" root="2.16.840.1.113883.2.9.4.3.2"/>
			<patient>
				<name>
					<family>PROVA</family>
					<given>PROVA</given>
				</name>
				<administrativeGenderCode code="M" codeSystem="2.16.840.1.113883.5.1" codeSystemName="HL7 AdministrativeGender" displayName="Maschio"/>
				<birthTime value="20201125"/>
				<birthplace>
					<place>
						<addr>
							<country/>
							<city/>
							<censusTract/>
						</addr>
					</place>
				</birthplace>
			</patient>
		</patientRole>
	</recordTarget>
	<author>
		<time value="20230612163340"/>
		<assignedAuthor classCode="ASSIGNED">
			<id assigningAuthorityName="Ministero Economia e Finanze" extension="DMNMTT94C22H769Q" root="2.16.840.1.113883.2.9.4.3.2"/>
			<telecom use="HP" value="prova_prova@gmail.com"/>
			<assignedPerson>
				<name>
					<family>DAMIANI</family>
					<given>MATTEO</given>
				</name>
			</assignedPerson>
		</assignedAuthor>
	</author>
	<custodian>
		<assignedCustodian>
			<representedCustodianOrganization>
				<id assigningAuthorityName="Ministero della Salute" extension="110113" root="2.16.840.1.113883.2.9.4.1.1"/>
				<name>OSPEDALE ASCOLI PICENO</name>
			</representedCustodianOrganization>
		</assignedCustodian>
	</custodian>
	<legalAuthenticator typeCode="LA">
		<time value="20230612163340"/>
		<signatureCode code="S"/>
		<assignedEntity>
			<id extension="DMNMTT94C22H769Q" root="2.16.840.1.113883.2.9.4.3.2"/>
			<assignedPerson>
				<name>
					<family>DAMIANI</family>
					<given>MATTEO</given>
				</name>
			</assignedPerson>
		</assignedEntity>
	</legalAuthenticator>
	<componentOf>
		<encompassingEncounter>
			<id extension="00000000000001667074" root="2.16.840.1.113883.2.9.2.110.4.6"/>
			<effectiveTime xsi:type="IVL_TS">
				<low value="20230612000000"/>
				<high value="20230612000000"/>
			</effectiveTime>
			<location>
				<healthCareFacility>
					<id extension="CARDIOLOGIA" root="2.16.840.1.113883.2.9.4.1.6"/>
					<location>
						<name>CARDIOLOGIA</name>
					</location>
					<serviceProviderOrganization>
						<id extension="110005.03" root="2.16.840.1.113883.2.9.4.1.1"/>
						<asOrganizationPartOf>
							<id extension="110113" root="2.16.840.1.113883.2.9.4.1.1"/>
						</asOrganizationPartOf>
					</serviceProviderOrganization>
				</healthCareFacility>
			</location>
		</encompassingEncounter>
	</componentOf>
	<component>
		<structuredBody classCode="DOCBODY" moodCode="EVN">
			<component typeCode="COMP">
				<section ID="PRESTAZIONI">
					<code code="62387-6" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Interventi"/>
					<title>Prestazioni</title>
					<text>
						<paragraph>Prestazione eseguita:VISITA CARD.UC</paragraph>
						<list>
							<item ID="PRESTAZIONE-1">
								<table>
									<thead>
										<tr>
											<th>PRESTAZIONE-1</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<th>Codice Prestazione</th>
											<td>0654UC</td>
										</tr>
										<tr>
											<th>Descrizione Prestazione eseguita</th>
											<td>VISITA CARD.UC</td>
										</tr>
										<tr>
											<th>Data Prestazione eseguita</th>
											<td>20230612000000</td>
										</tr>
									</tbody>
								</table>
								<paragraph>
									<caption>Procedure Operative Eseguite</caption>
								</paragraph>
								<list>
									<item ID="Procedura-1">
										<table border="1">
											<thead>
												<tr>
													<th>PRESTAZIONE-1</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<th>Codice Prestazione eseguita</th>
													<td>0654UC</td>
												</tr>
												<tr>
													<th>Codice Procedura Operativa</th>
													<td/>
												</tr>
												<tr>
													<th>Descrizione Procedura Operativa</th>
													<td/>
												</tr>
												<tr>
													<th>"Quantità"</th>
													<td/>
												</tr>
												<tr>
													<th>"Modalità Esecuzione Procedura Operativa"</th>
													<td/>
												</tr>
												<tr>
													<th>Strumentazione Utilizzata</th>
													<td/>
												</tr>
												<tr>
													<th>Parametri descrittivi della Procedura</th>
													<td/>
												</tr>
												<tr>
													<th>Note</th>
													<td/>
												</tr>
											</tbody>
										</table>
									</item>
								</list>
							</item>
						</list>
					</text>
					<entry>
						<act classCode="ACT" moodCode="EVN">
							<code code="89.7" codeSystem="2.16.840.1.113883.2.9.2.110113.6.11" codeSystemName="Catalogo Regione Marche" displayName="VISITA CARD.UC"/>
							<effectiveTime value="20230612000000"/>
							<entryRelationship typeCode="COMP">
								<procedure classCode="PROC" moodCode="EVN">
									<code code="0654UC" codeSystemName="Catalogo Regione Marche" displayName="VISITA CARD.UC"/>
									<text>VISITA CARD.UC</text>
									<effectiveTime value="20230612000000"/>
								</procedure>
							</entryRelationship>
						</act>
					</entry>
				</section>
			</component>
			<component typeCode="COMP">
				<section>
					<code code="47045-0" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Referto"/>
					<title>Referto</title>
					<text>
						<paragraph>prova da sforzo con cicloergometro avvenuta correttamente</paragraph>
					</text>
				</section>
			</component>
		</structuredBody>
	</component>
</ClinicalDocument>

**Comment by nbssrl** [comment]
Buon pomeriggio ci sono novità in merito alla segnalazione ?

**Comment by IStacchiotti** [comment]
Buon pomeriggio, Le confermiamo che analisi sono in corso. Riceverete un riscontro a conclusione delle attività di indagine. Grazie

**Comment by IStacchiotti** [comment]
Buongiorno @nbssrl, il cda condiviso sopra non risulta lo stesso inviato in chiamata per la validazione. In particolare per il traceId presente nella response il cda ottenuto ha come valorizzazione del templateId = "2.16.840.1.113883.2.9.10.1.6.1". Tale valore è relativo a un VPS e non un RSA, ed è questo il motivo per cui otteneva quell'errore semantico. Le chiediamo cortesemente di riprovare e di farci sapere se il problema persiste, grazie

**Comment by nbssrl** [comment]
Buongiorno abbiamo provveduto a svolgere la modifica adesso funziona grazie
