### ISSUE TITLE
Struttura Xml per Centri specialistici

### ISSUE THREAD

**Issue by medsofsas** [ministero-salute/it-fse-support#397]
Buongiorno, non riesco a trovare la struttura XML per i centri specialistici (quali Fisioterapici e Ortopedici), dove posso trovarli. Grazie

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
