### ISSUE TITLE
Timeout connessione

### ISSUE THREAD

**Issue by ivocaturo** [ministero-salute/it-fse-support#398]
{"traceID":"20230613142239205-1504246509773332349","spanID":"20230613142239205-1504246509773332349","type":"mw/io_error","title":"Errore di comunicazione con il gtw nazionale","detail":"Timeout connessione","status":"504","instance":"mw/io_error"}

vi risultano problemi ?

**Comment by masciamariotti** [comment]
Buon pomeriggio @ivocaturo,
il problema dovrebbe essere rientrato. Potrebbe riprovare cortesemente? Grazie.

**Comment by ivocaturo** [comment]
Confermo
Grazie




Ilaria Vocaturo

Divisione Pubblica Amministrazione e Sanità
Direzione Consulenza Applicativa
Area Sanitaria
***@***.******@***.***>***@***.***>***@***.***>

Engineering Ingegneria Informatica spa
Via Marconi, 10 - 40122 Bologna

mob. +39 342 5082815

www.eng.it<http://www.eng.it/>


________________________________
Da: masciamariotti ***@***.***>
Inviato: martedì 13 giugno 2023 16:53
A: ministero-salute/it-fse-support ***@***.***>
Cc: Ilaria Vocaturo ***@***.***>; Mention ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Timeout connessione (Issue #398)

Buon pomeriggio @ivocaturo, il problema dovrebbe essere rientrato. Potrebbe riprovare cortesemente? Grazie. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: 
ZjQcmQRYFpfptBannerStart
Security Warning: This email originated from outside of the organization. Do not click links or open attachments unless you verified the sender mail address and know the content is safe!

ZjQcmQRYFpfptBannerEnd

Buon pomeriggio @ivocaturo<https://urldefense.com/v3/__https://github.com/ivocaturo__;!!LQkDIss!SDN_6AG623PZVerBjpY79QZdCQjUSZIiWy5_77_qCRJiVcxYgJ1_KfDJOEsLCsCg1ba8QpJIhkVVrD3BUNLAVymkkSuZ$>,
il problema dovrebbe essere rientrato. Potrebbe riprovare cortesemente? Grazie.

**Comment by masciamariotti** [comment]
Grazie per il feedback, procediamo alla chiusura della presente issue.
