### ISSUE TITLE
Errore 502 nel richiamare il servizio di validazione

### ISSUE THREAD

**Issue by giosil** [ministero-salute/it-fse-support#399]
Si segnala che a fronte di una invocazione del servizio di validazione in modalità di verifica otteniamo un errore 502:

{"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"31936613-0a7c-11ee-8882-005056ae54fa"}

Nella giornata di ieri invece abbiamo registrato tempi di risposta elevati (circa 2 minuti!).
Grazie.

**Comment by masciamariotti** [comment]
Buongiorno,
come comunicato su [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM/p1686733220444459), attualmente ci sono dei disservizi.
Daremo evidenza non appena saranno risolti.

**Comment by IStacchiotti** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
