### ISSUE TITLE
SHEMATRON LDO righe 519-521 Errore 79

### ISSUE THREAD

**Issue by giuseppe-fasulo** [ministero-salute/it-fse-support#4]
Buongiorno.  Credo che il controllo sia errato per due motivi:
1. L'asserzione testa che il valore di @code sia uguale a 34820-1, ma nel messaggio richiede che il valore di @code sia 75321-0
2. La specifica HL7 V. 1.2 PAG 87 riporta che nel campo observation/code/@code sia indicato il codice della consulenza secondo un sistema di nomenclatura Ministeriale o Regionale.  

Riporto la porzione di controllo da riguardare.
----------------------------------------------------------------------------------------------------------------------------------
<rule context="hl7:ClinicalDocument/hl7:component/hl7:structuredBody/hl7:component/hl7:section[hl7:code[@code='34104-0']]/hl7:entry">	
			<assert test="count(hl7:observation/hl7:code[@code='34820-1'][@codeSystem='2.16.840.1.113883.6.1'])=1"
			>ERRORE-79| Sezione Consulenza: l'elemento entry DEVE contenere al suo interno un observation che valorizza  l'elemento 'code' con gli attributi @code='75321-0' e @codeSystem='2.16.840.1.113883.6.1'</assert>

**Comment by zukka77** [comment]
grazie, verificheremo anche questo

**Comment by gndibiase** [comment]
Grazie dell’osservazione. C’è un primo refuso per quanto riguarda la discordanza tra il code riportato nel messaggio associato alla descrizione dell’errore, e l’asserzione del controllo. 
Inoltre, come riportato sulla guida il code ed il codeSystem sono variabili, si provvederà alla correzione.
