### ISSUE TITLE
NON FUNZIONA ERRORE 502 ESISTEMATICO

### ISSUE THREAD

**Issue by DATASOFTNA** [ministero-salute/it-fse-support#400]
COME DA OGGETTO OTTENGO SISTEMATICAMENTE ERRORE 502 PER DELLE TRASMISSIONI CHE HANNO SEMPRE FUNZIONATO

**Comment by masciamariotti** [comment]
Buongiorno,
come comunicato su [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM/p1686733220444459), attualmente ci sono dei disservizi.
Daremo evidenza non appena saranno risolti.

**Comment by masciamariotti** [comment]
Buon pomeriggio @DATASOFTNA,
il problema dovrebbe essere rientrato. Potrebbe riprovare cortesemente? Grazie.
