### ISSUE TITLE
Errore 502 in Validazione

### ISSUE THREAD

**Issue by PrismaEU** [ministero-salute/it-fse-support#401]
Buongiorno,
da ieri ho iniziato ad effettuere le verifiche per l'accreditameto dei documenti LDO e RSA ma ricevo la seguente risposta
{
	"type":"https://govway.org/handling-errors/502/InvalidResponse.html",
	"title":"InvalidResponse",
	"status":502,
	"detail":"Invalid response received from the API Implementation",
	"govway_id":"a92bbb01-0a79-11ee-80ae-005056ae7395"
}
L'applicazione che effettua la richiesta e i documenti, già validati nei test interni, non sono cambiati.
L'unica differenza consiste nei parametri subject_application per generare i token, prima erano

	"subject_application_id": "Middleware150",
	"subject_application_vendor": "Regione Campania",
	"subject_application_version": "0.1",

ora contengono i dati dell'applicativo da accreditare

saltuariamente ricevo anche l'errore
{
	"traceID":"e099f557dd484a77",
	"spanID":"e099f557dd484a77",
	"type":"/msg/generic-error",
	"title":"Errore generico.",
	"detail":"it.finanze.sanita.fse2.ms.gtw.dispatcher.exceptions.BusinessException: it.finanze.sanita.fse2.ms.gtw.dispatcher.exceptions.BusinessException: java.util.concurrent.ExecutionException: org.springframework.kafka.core.KafkaProducerException: Failed to send; nested exception is org.apache.kafka.common.errors.NotEnoughReplicasException: Messages are rejected since there are fewer in-sync replicas than required.",
	"status":500,
	"instance":""
}
Effettuando più tentativi alcuni documenti (6) sono stati validati.
Resto in attesa di riscontro

**Comment by bgmatteo** [comment]
buongiorno, mi aggiungo anche io all'issue, per i verbali di PS

**Comment by ivocaturo** [comment]
Buongiorno
nei test di validazione della LDO oggi sto ottenendo lo stesso errore:
Validazione CDA non riuscita
it.finanze.sanita.fse2.ms.gtw.dispatcher.exceptions.BusinessException: it.finanze.sanita.fse2.ms.gtw.dispatcher.exceptions.BusinessException: java.util.concurrent.ExecutionException: org.springframework.kafka.core.KafkaProducerException: Failed to send; nested exception is org.apache.kafka.common.errors.NotEnoughReplicasException: Messages are rejected since there are fewer in-sync replicas than required.

Non è chiaro quale sia il rpoblema.

Grazie

**Comment by masciamariotti** [comment]
Buongiorno,
come comunicato su [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM/p1686733220444459), attualmente ci sono dei disservizi.
Daremo evidenza non appena saranno risolti.

**Comment by masciamariotti** [comment]
Buon pomeriggio @PrismaEU,
il problema dovrebbe essere rientrato. Potrebbe riprovare cortesemente? Grazie.

**Comment by PrismaEU** [comment]
Richieste Validazione e recupero WorkFlow andati a buon fine.

**Comment by bgmatteo** [comment]
Questa response può essere considerata esito positivo? Non vedo errori ma neanche uno status 200/201...

{
"traceID":"78a22b9b11949712",
"spanID":"78a22b9b11949712",
"workflowInstanceId":"2.16.840.1.113883.2.9.2.30.4.4.2914fdff8be5462b720bc7eb160040fc258bf9edc3eb76ab3d4b0eb92823bf6b.6037e934cc^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Grazie mille
