### ISSUE TITLE
Accreditamento soluzione AIRO

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#402]
Buongiorno,
volevamo notificare il caricamento completato dei test case per la soluzione AIRO:

https://github.com/ministero-salute/it-fse-accreditamento/pull/573

Grazie

**Comment by IStacchiotti** [comment]
Buonasera, Le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
