### ISSUE TITLE
Richiesta accreditamento DATASOFT

### ISSUE THREAD

**Issue by DATASOFTNA** [ministero-salute/it-fse-support#403]
Buonasera,
Credo di avere creato nell'ambiente privato la struttura di cartelle prevista nelle specifiche.
Credo di avere richiesto una operazione di PULL per aggiornare la repository generale.
Siccome ho fatto un po' le cose "ad intuito" (questo sito e' user-enemy, per creare una cartella bisogna far finta di caricare un file), non so se poi l'effetto e' quello voluto.
Potreste dirmi in che stato si trova la mia richiesta  e caso mai quali sono le azioni da intraprendere per ottenere il caricamento della cartella con i test ?
Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, Le confermiamo che la pull request è stata eseguita correttamente e presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
