### ISSUE TITLE
Aggiornato file report-checklist e data.json

### ISSUE THREAD

**Issue by mmaggi69** [ministero-salute/it-fse-support#404]
S1#111EUROMEDICAL
EUROMEDICAL
MEDIWEB
1.0

**Comment by masciamariotti** [comment]
Buongiorno,
Le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
