### ISSUE TITLE
Cambio mail

### ISSUE THREAD

**Issue by DATASOFTNA** [ministero-salute/it-fse-support#406]
Buongiorno.
Siccome LIBERO non funziona da un paio di giorni, ho cambiato l'indirizzo mail nella configurazione utente.
Ovemai ci fossero  stati "eventuali aggiornamenti relativi alla richiesta di accreditamento che sono notificati via email", vi chiederei la cortesia di rimandarli, perche' dal 14.06 non posso ricevere posta al precedente indirizzo.
Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
