### ISSUE TITLE
Lentezza Gateway Test

### ISSUE THREAD

**Issue by giosil** [ministero-salute/it-fse-support#408]
Nel chiamare oggi 19/06/2023 il servizio di validazione del Gateway in ambiente di test riscontriamo tempi di risposta oltre i 120 secondi.

**Comment by IStacchiotti** [comment]
Buongiorno @giosil, non abbiamo evidenze attualmente di disservizi lato Gateway. Le chiediamo cortesemente di riprovare e farci sapere se il problema persiste, in modo tale da indirizzare tempestivamente la problematica, avendo cura di indicare eventualmente il tempo di latenza, il servizio invocato e il timestamp della chiamata.

**Comment by giosil** [comment]
Questa mattina abbiamo riscontrato un tempo di risposta di oltre i 120 secondi.
Di seguito la risposta dalla quale estrapolare i riferimenti.
Purtroppo i client talvolta impostano timeout più restrittivi e oggettivamente tali tempi di risposta non sono accettabili.
Abbiamo fatto una ulteriore prova con validazione ok il servizio risponde in tempi congrui.

{"traceID":"f1699d0e5164589d","spanID":"f1699d0e5164589d","type":"/msg/semantic","title":"Errore semantico.","detail":"[ERRORE-10a| L'elemento ClinicalDocument/recordTarget/patientRole/id  deve avere l'attributo @root valorizzato tramite uno dei seguenti identificatori Nazionanli:\n\t\t\tCF 2.16.840.1.113883.2.9.4.3.2 (Nel caso di Cittadino Italiano o straniero residente in Italia, patientRole DEVE riportare un elemento di tipo id contenente il Codice Fiscale e un ulteriore elemento id OBBLIGATORIO contenente il numero di identificazione dell’assistito nel sistema PACS (@nullFlavour è ammesso ove l’informazione non sia disponibile).)\n\t\t\tTEAM 2.16.840.1.113883.2.9.4.3.7 e 2.16.840.1.113883.2.9.4.3.3\n\t\t\tENI 2.16.840.1.113883.2.9.4.3.18\n\t\t\tSTP 2.16.840.1.113883.2.9.4.3.17 oppure un identificativo regionale \n\t\t\tANA 2.16.840.1.113883.2.9.4.3.15\n\t\t\tOppure tramite gli identificatori regionali generati per rappresentare l'id del paziente.\n\t\t\t],[W005 | Sezione Esame Eseguito: l'entry/act/code può essere valorizzato secondo i sistemi di codifica\n\t\t\tLOINC @codeSystem='2.16.840.1.113883.6.1'\n\t\t\tICD-9-CM @codeSystem='2.16.840.1.113883.6.103']","status":422,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed83d12c1df6a06925762218b20d494b4eba08dc9d98b6158311578f4f9da2ee.27437093a4^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

**Comment by IStacchiotti** [comment]
Buongiorno @giosil, grazie per i dettagli comunicati.
Dalle nostre verifiche è emerso che i nostri sistemi hanno impiegato 12 secondi circa per rispondere, quindi ipotizziamo un problema di latenza di rete a noi esterno
Dal momento che, comunque, l'ultima chiamata ha dato luogo ad una risposta in tempi ragionevoli, e tenendo in considerazione del fatto che si tratta di un ambiente non di produzione, chiudiamo il presente, rinnovando però la richiesta di segnalare eventuali chiamate con tempi di latenza eccessivi, riportando i dati indicati sopra nel precedente messaggio, se queste dovessero verificarsi frequentemente. Grazie
