### ISSUE TITLE
accrefditamento 

### ISSUE THREAD

**Issue by dtsconsulting** [ministero-salute/it-fse-support#409]
creata nuova Pull Request con le modifiche richieste

https://github.com/ministero-salute/it-fse-accreditamento/pull/598

**Comment by masciamariotti** [comment]
Buonasera, Le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
