### ISSUE TITLE
Validazione documento: errore 403 jwt-validation 

### ISSUE THREAD

**Issue by davidetau** [ministero-salute/it-fse-support#41]
Buongiorno, invocando il gatway di test per la validazione otteniamo il seguente errore:
`{"traceID":"076c7a1d1ed7b299","spanID":"076c7a1d1ed7b299","type":"/msg/jwt-validation","title":"Campo token JWT non valido.","detail":"Codice fiscale nel campo person non valido","status":403,"instance":"/jwt-mandatory-field-malformed","workflowInstanceId":"UNKNOWN_WORKFLOW_ID"}`
Utilizziamo il person_id fornito negli esempi.
`RSSMRA75C03F839K^^^&2.16.840.1.113883.2.9.4.3.2&ISO`
In allegato i token di autenticazione e firma. Potete indicarci cosa sbagliamo?
grazie
[signatureToken.txt](https://github.com/ministero-salute/it-fse-support/files/10313615/signatureToken.txt)
[authToken.txt](https://github.com/ministero-salute/it-fse-support/files/10313617/authToken.txt)

**Comment by zukka77** [comment]
decodificando il token pare che molte chiavi  terminino con degli spazi che sono da eliminare
```json
{
  "sub": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "person_id ": "RSSMRA75C03F839K^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "subject_organization_id ": "120",
  "iss": "integrity:S1#111SCSCOMPUTERS",
  "subject_role ": "AAS",
  "resource_hl7_type ": "('11502-2^^2.16.840.1.113883.6.1')",
  "locality ": "jwt-location",
  "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
  "purpose_of_use  ": "TREATMENT",
  "subject_organization ": "Regione Lazio",
  "attachment_hash ": "0a9b8df12f706df62397dbfa436d2f3335211e5f3327e6aad3a18f0592aa66fe",
  "patient_consent ": "true",
  "action_id ": "CREATE",
  "exp": 1672309128,
  "iat": 1672222728,
  "jti": 1672222728610
}
```
