### ISSUE TITLE
S1#111EUROMEDICAL Richiesta dettaglio problema report-checklist 

### ISSUE THREAD

**Issue by mmaggi69** [ministero-salute/it-fse-support#410]
S1#111EUROMEDICAL
EUROMEDICAL
MEDIWEB
1.0

Buonasera mi è stata notificato mancato accreditamento per problema: "E' necessario che la checklist contenga almeno un caso applicabile OK per ogni CDA affinchè sia ritenuta valida".
Nel file report-checklist sono presenti 20 righe con applicabilità = SI.  Potreste indicarmi più specificatamente il problema qual'è ?

**Comment by IStacchiotti** [comment]
Buongiorno @mmaggi69, l'errore segnalato deriva dal fatto che ha valorizzato la colonna applicabilità con "NO", e ha popolato il campo razionale di applicabilità anche per i casi d'uso non pertinenti per il suo applicativo. Specifichiamo infatti che non sono da valorizzare le righe che si riferiscono a CDA/servizi non gestiti dall'applicativo in questione.

**Comment by mmaggi69** [comment]
Quindi le righe che hanno applicabilità 'NO' devono essere  eliminate da report-chekclist ? Oppure bisogna eliminare il dato presente nella colonna  "razionale applicabilità" per righe con applicabilità = NO ?
