### ISSUE TITLE
Correzione files Pull Request

### ISSUE THREAD

**Issue by PrismaEU** [ministero-salute/it-fse-support#412]
Buonasera,
ho apportato, come richiesto, alcune modifiche al file report-checklist.xlsx (Pull request #605) e fatto l'upload nel Fork.
Poiché ho notato che la commit di aggiornamento è stata aggiunta alla Pull request, è sufficiente così o bisogna creare un'altra PR?
Grazie

**Comment by vigliottim** [comment]
Buongiorno, le confermo che non è necessario creare una nuova PR. Le correzioni sono state ricevute e la PR è stata ripresa in carico. Riceverà aggiornamenti via e-mail con l'esito delle elaborazioni. Chiudo la presente issue e la invito ad aprire un nuovo ticket per eventuali nuove richieste di supporto.
