### ISSUE TITLE
Accreditamento - Id 59

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#415]
**infulfilldocument/order/id**

È chiaro che qui vanno indicati i riferimenti delle ricette, bianche o rosse che siano. Dal caso di test, pare non sia possibile inviare il referto di soli privati (dato l’errore sintattico che ne deriverebbe). È corretta l’interpretazione? 

Oppure, il caso di test si riferisce all’inserimento del tag infulfilldocument, senza gli Order? O con gli Order ma senza l’id?

**Premessa**
Con FSE 1.0, attivo da tempo, ho la possibilità di inviare cda privi del tag infulfilldocument. Solo con il Referto Radiologico, il dato è obbligatorio (qui, però, posso mettere l’identificativo univoco del referto)

**Comment by IStacchiotti** [comment]
Buonasera, per quanto riguarda il caso di test da lei riferito, precisiamo che per generare l'atteso KO è previsto il mancato inserimento del tag id nel path ClinicalDocument/inFulfillmentOf/order/id, quindi l'inserimento di order senza il tag id.

**Comment by ds-tommaso** [comment]
D’accordo
