### ISSUE TITLE
ACCREDITAMENTO A1#111DATASOFTNA

### ISSUE THREAD

**Issue by DATASOFTNA** [ministero-salute/it-fse-support#416]
Credo di avere aggiornato il file report-checklist.xlsx come da mail ricevuta, potrei avere conferma che cio' sia davvero avvenuto ?
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, la sua PR è stata presa in carico e riceverà aggiornamenti via e-mail. Chiudo il presente ticket e resto a disposizione per ulteriore supporto.

**Comment by vigliottim** [comment]
Buongiorno, le modifiche effettuate risultano visibili ma presenti su un branch esterno. Dovrà effettuare una PR in modo che sia possibile fare il merge con il main. Grazie.

**Comment by DATASOFTNA** [comment]
Credo di avere eseguito la pull request

**Comment by vigliottim** [comment]
La PR risulta presa in carico, riceverà aggiornamenti via e-mail. Buona giornata.
