### ISSUE TITLE
Errore validazione CDA2 iniettato in modalità RESOURCE

### ISSUE THREAD

**Issue by domenico-capezzuto** [ministero-salute/it-fse-support#417]
Iniettando il CDA2 in modalità `RESOURCE` il PDF non passa la fase di validazione, ottenendo il seguente errore:

`ERROR: -1,-1 cvc-datatype-valid.1.2.1: 'Modalit��_di_Trasporto' is not a valid value for 'NCName'.,ERROR: -1,-1 cvc-attribute.3: The value 'Modalit��_di_Trasporto' of attribute 'ID' on element 'section' is not valid with respect to its type, 'ID'.****
`
Impiegando invece la modalità `ATTACHMENT`, con il medesimo CDA2, la validazione viene superata con successo.

**Comment by vigliottim** [comment]
Buonasera, per procedere ad analisi più approfondite avremmo bisogno del PDF e del CDA che sta utilizzando in modalità "resource" e la response completa dell'errore. Grazie.

**Comment by vigliottim** [comment]
Buonasera, è stata effettuata una fix correttiva. La invitiamo a riprovare, il problema dovrebbe essere rientrato. Grazie.

**Comment by vigliottim** [comment]
In seguito alla sua risposta procediamo alla chiusura del presente ticket e la invitiamo a riaprirlo nel caso avesse bisogno di ulteriore supporto. Grazie.

**Comment by marcodellavall3** [comment]
Salve, sto riscontrando il medesimo errore in data odierna.
In allegato il CDA e il PDF utilizzato per la richiesta.
[VPS_CT11.pdf](https://github.com/ministero-salute/it-fse-support/files/12859307/VPS_CT11.pdf)
[ct11.txt](https://github.com/ministero-salute/it-fse-support/files/12859305/ct11.txt)

Questa la risposta del servizio

`{"traceID":"14b2473379d161bd","spanID":"14b2473379d161bd","type":"/msg/syntax","title":"Errore di sintassi.","detail":"ERROR: -1,-1 cvc-datatype-valid.1.2.1: 'ModalitÃ _di_Trasporto' is not a valid value for 'NCName'.,ERROR: -1,-1 cvc-attribute.3: The value 'ModalitÃ _di_Trasporto' of attribute 'ID' on element 'section' is not valid with respect to its type, 'ID'.","status":400,"instance":"/validation/error","workflowInstanceId":".c8a5681e5c6e538766d0ac6a40a40fe267e5d9149907cd4c8e396ca83cc37d51.cd542ff2f7^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}
`
è possibile una verifica in merito ?

**Comment by vigliottim** [comment]
Buongiorno, le chiediamo di modificare il cda utilizzando **ID="Modalita_di_trasporto"** al posto di **ID="ModalitÃ _di_Trasporto"** e riprovare. Grazie.

**Comment by marcodellavall3** [comment]
Salve,
sono riuscito a validare correttamente il documento , vi ringrazio per il supporto.

**Comment by vigliottim** [comment]
Grazie per il feedback. Procediamo alla chiusura del presente ticket e rimaniamo a disposizione per ulteriori richieste di supporto.
