### ISSUE TITLE
Errore relativo al tipo di documento tra Token e CDA in fase di verifica

### ISSUE THREAD

**Issue by giovannicatucci88** [ministero-salute/it-fse-support#419]
Salve,
in fase di verifica del CDA ricevo come errore:
{"traceID":"d3aeb2b73b852e3f","spanID":"d3aeb2b73b852e3f","type":"/msg/jwt-validation","title":"Campo token JWT non valido.","detail":"JWT payload: Tipologia documento diversa dalla tipologia di CDA (code - codesystem)","status":403,"instance":"/jwt-document-type","workflowInstanceId":"2.16.840.1.113883.2.9.2.160.4.4.76f8e12ed760b91124e18b82e7a43955d140a69bbe0fa4590a87edcb50612048.6e20a53ac2^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

Come resource_hl7_type ho usato 11369-6^^2.16.840.1.113883.6.1 essendo una singola vaccinazione ed è lo stesso LOINC code presente in component/structuredBody/component/section/code
<code code="11369-6" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Storia delle immunizzazioni"/>

Grazie in anticipo per il supporto che riceverò

**Comment by masciamariotti** [comment]
Buongiorno @giovannicatucci88,
il resource_hl7_type usato nel JWT deve corrispondere al code presente in ClinicalDocument/code, che nel caso specifico di singola vaccinazione dovrebbe essere valorizzato con "87273-9".
La invitiamo inoltre a verificare che il formato del valore dello stesso sia coerente alle specifiche:
`"resource_hl7_type": "('87273-9^^2.16.840.1.113883.6.1')"`
Potrebbe verificare?

**Comment by giovannicatucci88** [comment]
Ho eseguito il test modificato il resource_hl7_type come suggerito ed è passato allo step successivo. Grazie
