### ISSUE TITLE
validazione 403 Unauthorized request content

### ISSUE THREAD

**Issue by gabriele-stenico-gpi** [ministero-salute/it-fse-support#42]
in fase di validazione otteniamo sempre il seguente errore

{
  "type" : "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
  "title" : "AuthorizationContentDeny",
  "status" : 403,
  "detail" : "Unauthorized request content",
  "govway_id" : "697e4aec-880d-11ed-b06a-005056ae7395"
}

**Comment by gabriele-stenico-gpi** [comment]
Ho notato che avevamo degli spazi nel json alla fine delle chiavi. Togliendoli però ho sempre lo stesso errore:

{
  "type" : "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
  "title" : "AuthorizationContentDeny",
  "status" : 403,
  "detail" : "Unauthorized request content",
  "govway_id" : "e23ee6cd-8d01-11ed-b21d-005056ae54fa"
}

**Comment by pFonziSogei** [comment]
Salve, 

sta usando il certificato che inizia con "S1" al posto di quello che inizia con "A1".

segnaliamo che vediamo nel token "iss" : "integrity:integrity:S1#************", che sicuramente darà problemi, va tolto il secondo "integrity:"

**Comment by GianlucaCallegari-GPI** [comment]
abbiamo modificato il token passando questa iss:
"iss" : "integrity:a1#111gruppogpi00",

ma otteniamo ancora l'errore:
{
  "type" : "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
  "title" : "AuthorizationContentDeny",
  "status" : 403,
  "detail" : "Unauthorized request content",
  "govway_id" : "d8887bac-90ca-11ed-b06a-005056ae7395"
}

**Comment by zukka77** [comment]
come già scritto sull'altro issue:
per i token bisogna usare il certificato di signature, non di autorizzazione che si usa solo per l'https.
Quindi
`integrity:S1#111gruppogpi00` per il token di signature  e 
`auth:S1#gruppogpi00` per quello di autorizzazione.
**controllate il case del common name**

**Comment by explorasalerno** [comment]
Stesso errore anche per me:
Type: https://govway.org/handling-errors/403/AuthorizationContentDeny.html
Status: 403
Title: AuthorizationContentDeny
Detail: Unauthorized request content
Govway_id: f8bbf591-ef3b-11ed-8882-005056ae54fa
