### ISSUE TITLE
Informazione sul test di accreditamento per il VPS

### ISSUE THREAD

**Issue by greglombardi** [ministero-salute/it-fse-support#420]
Buongiorno,
abbiamo effettuato i test con il tool gtw-certifier.
Abbiamo riscontrato 0 errori, ma vorrei chiedervi delle informazioni riguardo all'operato e alla corretta validazione.
Ci siamo accorti che durante l'accreditamento, il CDA deve essere popolato sia con gli "encounters" relativi al trasferimento in un altro istituto, sia con quelli riguardanti il ricovero. Se provo ad eliminare uno dei due, il servizio mi restituisce degli errori.
Per quanto riguarda il nostro pronto soccorso, quando un paziente viene ricoverato in un reparto, viene eseguita la dimissione dal pronto soccorso.
Potreste gentilmente indicarci le modalità corrette per effettuare l'accreditamento?
Distinti saluti

**Comment by masciamariotti** [comment]
Buongiorno,
potrebbe allegare il CDA usato e indicare quale caso di test sta eseguendo?
Grazie

**Comment by greglombardi** [comment]
Stiamo eseguendo il test case n° 24.
Le mando il CDA con tutti e due gli encounters inseriti.
[549626_cdasigned.txt](https://github.com/ministero-salute/it-fse-support/files/11865961/549626_cdasigned.txt)

**Comment by greglombardi** [comment]
Buonasera,
non abbiamo ricevuto ancora riscontro per quanto riguarda il test case n° 24.
Abbiamo notato che un paio di settimane fa è stato aggiunto il Caso di Test n° 0. In caso di problemi possiamo effettuare nuovamente  le prove con il Test Case 0 e mandarvi quello? 
Grazie per la disponibilità, attendo Vostre.

**Comment by greglombardi** [comment]
Buongiorno,
per i case Test Ko vanno  inseriti i PDF che hanno tornato l'errore nella chiamata di validazione?
Abbiamo provato il Tool gtw-certifier per l'ID 373, ma risulta non verificabile, possiamo inviarlo ugualmente?
Grazie per la disponibilità.

**Comment by IStacchiotti** [comment]
Buonasera @greglombardi, sì, le confermiamo che vanno inseriti nella cartella "FILES" anche i pdf che sono stati utilizzati per i test KO. Segnaliamo che i test case di tipo KO non sono verificabili tramite il tool gtw-certifier (come indicato al [link](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/gtw-certifier#gtw-certifier)), per questo ottenete errore. Rimaniamo a disposizione per ulteriori chiarimenti. Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, confermiamo che per i test 0 non è necessario eseguire i test tramite il gtw-certifier. Le verifiche che potete fare prima di eseguire una pull request per la richiesta di accreditamento, sono le seguenti:
1. verificare, tramite il tool gtw-certifier, che non ci siano errori sui test case OK al netto dei casi di test 0;
2. verificare che il Gateway non restituisca errori in validazione nel momento in cui viene invocato con l'url sopra riportato, (corretto), per l'esecuzione dei casi di test 0.

**Comment by greglombardi** [comment]
Buonasera, 
inizialmente nel form da compilare avevamo inserito sia la validazione che la pubblicazione.
Per effettuare l'accreditamento dobbiamo inserire solamente  i test case della Validazione?

**Comment by IStacchiotti** [comment]
Buonasera, le confermiamo che la pubblicazione è momentaneamente ferma, come da comunicazione su Slack a questo [link](https://developersitalia.slack.com/archives/C03RDT88FSM/p1681490960524259). Al momento può procedere sottomettendo la checklist relativamente al solo servizio di validazione.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
