### ISSUE TITLE
Scadenza keystore

### ISSUE THREAD

**Issue by ZucchettiCentroSistemi** [ministero-salute/it-fse-support#421]
Buongiorno,
sono Claudia Artini dalla Zucchetti Centro Sistemi s.p.a. e siamo già stati accreditati.
I certificati di Autenticazione e Firma che abbiamo generato e inviato a Sogei sono scaduti qualche giorno fa.
Dobbiamo generarli di nuovo e reinviarli a Sogei?

**Comment by masciamariotti** [comment]
Buonasera,
potrebbe indicarci se i certificati scaduti sono i file .pem che sono stati precedentemente forniti dal support?
Inoltre potrebbe cortesemente riportare la data di scadenza che le risulta e inviare evidenza dell'errore riscontrato (es. screenshot)?
Grazie

**Comment by ZucchettiCentroSistemi** [comment]
Buonasera, no i file scaduti non sono i .pem forniti dal support.
Risulta scaduta la chiave privata del certificato che abbiamo creato noi e poi inviata al support. Quando si crea il certificato se non si dichiara la validità, viene impostata di default a 3 mesi. I 3 mesi sono scaduti.
Non abbiamo difficoltà nell' invocare il servizio di validazione, lo abbiamo nel fare i test con la regione Sardegna che necessita del certificato di firma per firmare l'asserzione. Allego request e response dell'errore.
[requestAndResponse.txt](https://github.com/ministero-salute/it-fse-support/files/11880668/requestAndResponse.txt)

**Comment by masciamariotti** [comment]
Buongiorno,
confermiamo che deve ripetere la procedura di creazione delle CSR e inviare mail a `fse_support@sogei.it`.
Grazie

**Comment by ZucchettiCentroSistemi** [comment]
Devo generarli di nuovo anche se già accreditati?

**Comment by masciamariotti** [comment]
Buongiorno,
al fine di avere dei certificati validi, se lo ritiene opportuno per la sua operatività, la procedura prevedere che sia fatta una nuova richiesta tramite e-mail.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
