### ISSUE TITLE
Aggiornato file report-checklist.xlsx

### ISSUE THREAD

**Issue by DATASOFTNA** [ministero-salute/it-fse-support#422]
Buonasera, credo di avere aggiornato il file report-checklist.xlsx.
Per cortesia vorrei sapere se ogni volta che effettuo un aggiornamento viene automaticamente rilevato o 
e' necessario evidenziare l'evento tramite questa zona di messaggistica (Il timore e' che passi inosservato o non sia stata effettuata correttamente la richiesta di pull).
Oppure se c'e' qualcosa da fare per essere certi che l'aggiornamento sia sottoposto a chi di dovere.
Grazie.

p.s.
Probabilmente il mio e' un caso isolato, ma sarebbe stato bello per quelli non avvezzi ad utilizzare excel per una finalita' che non sia  il reparto millesimale delle spese di condominio , poter fare un controllo istantaneo (tramite un'applicazione locale o una pagina web)  della correttezza del file report-checklist.xlsx.
Vi avrei fatto perdere meno tempo.

**Comment by vigliottim** [comment]
Buongiorno, in questo caso non è necessario aprire una issue su Github. Dopo l'apertura della pull request riceverà i relativi aggiornamenti via e-mail. Chiudo la presente che potrà essere riaperta se necessita di ulteriore supporto.
