### ISSUE TITLE
Assenza codice AIC 037045109 

### ISSUE THREAD

**Issue by infonext-it** [ministero-salute/it-fse-support#423]
Salve, durante alcune prove di validazione del certificato vaccinale, abbiamo ricevuto errore per il codice AIC 037045109 che fa riferimento al vaccino denominato ROTARIX.
L'errore nello specifico è
`Almeno uno dei seguenti vocaboli non è censito: [CodeSystem: 2.16.840.1.113883.2.9.6.1.5, Codes: 037045109]`
Si tratta di un vaccino somministrato di frequente e quindi spesso presente sia nelle schede ma soprattutto nei certificati vaccinali.

Grazie

**Comment by vigliottim** [comment]
Buongiorno, la informiamo che è stato rilasciato un aggiornamento. La invitiamo cortesemente a riprovare. Rimaniamo a disposizione in caso fosse necessario ulteriore supporto. Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
