### ISSUE TITLE
Test accreditamento

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#424]
Buongiorno, sono previsti dei dati di test riferiti al dottore, struttura e paziente da innestare nel cda?

**Comment by vigliottim** [comment]
Buongiorno, può trovare esempi di CDA al seguente [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/esempi/CDA). Restiamo a disposizione per ulteriori richieste di supporto.
