### ISSUE TITLE
Accreditamento e non applicabilità dello use case

### ISSUE THREAD

**Issue by giovannicatucci88** [ministero-salute/it-fse-support#425]
Buongiorno, nella fase di accreditamento ho letto la nota:
**NB Per i test "KO" è possibile autocertificare la non applicabilità dei casi che non possono darsi nell'utilizzo del software specifico.**
Questo significa che posso indicare la non applicabilità con relativa motivazione per esempio nel test case di codice fiscale minuscolo? perchè nel sistema ho doppia verifica sul CF sia sul database che sul software per fare uppercase quindi dovrei smontare il software per forzarne il minuscolo ed eseguire il relativo test di KO.
Sempre sulla non applicabilità, nei casi di OK per le vaccinazioni è possibile indicare la non applicabilità di casi di test che non possono essere eseguiti causa mancata gestione delle operazioni indicate nel test nel sistema? o bisogna eseguire comunque il test costruendo a mano il cda e inviandolo tramite software?

Grazie in anticipo per la risposta

**Comment by vigliottim** [comment]
Buongiorno, per evitare forzature è possibile indicare NO nell’apposita colonna "Applicabilità", avendo cura di giustificarlo opportunamente nella colonna "razionale di applicabilità". Nel caso in cui non ci sia nessun test OK applicabile anche solo per un CDA, dovrà fare riferimento alla checklist presente al [link](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/accreditamento-checklist_V8.1.3.xlsx) e compilare il caso di test 0 (sempre applicabile) che prevede i campi obbligatori secondo HL7 Italia.
