### ISSUE TITLE
Problemi con il gateway per la validazione 

### ISSUE THREAD

**Issue by acabutto** [ministero-salute/it-fse-support#426]
Buongiorno,

tentando di contattare il gateway all'indirizzo https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation

e valorizzando opportunamente i token di autorizzazione e firma nella chiamata: 

curl -X 'POST' \    
  --cert "/certificates/auth/A1#111WECONSTUDIOXX.pem:<PASS>" \
  --key "/certificates/auth/fse_auth_cdcsm_pk.key" \
  'https://<HOST>:<PORT>/v1/documents/validation' \
  -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5c ... iZPqKv3kUbn1qzLg' \
  -H 'FSE-JWT-Signature: eyJdWIiOiIxMjM0NTY3ODkw … Ok6yJV_adQssw5c' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'requestBody={
  "healthDataFormat": "CDA",
  "activity": "VERIFICA",
}' \
  -F 'file=@CDA_OK.pdf;type=application/pdf'

Otteniamo questo messaggio di errore di difficile interpretazione:

{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "d0a457d7-158c-11ee-8882-005056ae54fa"
}

Cosa significa questo messaggio?

**Comment by masciamariotti** [comment]
Buongiorno,
per velocizzare l'analisi sull'errore, potrebbe inviarci i 2 token?
Grazie

**Comment by acabutto** [comment]
> Buongiorno, per velocizzare l'analisi sull'errore, potrebbe inviarci i 2 token? Grazie

Grazie per la pronta risposta. Eccoli in allegato.

[bearer.txt](https://github.com/ministero-salute/it-fse-support/files/11893453/bearer.txt)
[fse-jwt.txt](https://github.com/ministero-salute/it-fse-support/files/11893454/fse-jwt.txt)

**Comment by masciamariotti** [comment]
Buonasera,
i seguenti parametri risultano non corretti:
bearer:
- "aud": "FSE_Gateway" --> da correggere in "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1"
- "iss": "auth:WECONSTUDIO SRL" --> deve essere valorizzato con “auth:” seguito dal “Common Name del certificato di firma”. esempio "auth:S1#111XXXXXXXXXXXXX"

fse-jwt:
- "aud": "FSE_Gateway" --> da correggere in "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1"
- "iss": "integrity:WECONSTUDIO SRL" --> deve essere valorizzato con “integrity:” seguito dal “Common Name del certificato di firma”. esempio "integrity:S1#111XXXXXXXXXXXXX"

La rimandiamo alla [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt) per ulteriori dettagli.

**Comment by garaznico** [comment]
> Buonasera, i seguenti parametri risultano non corretti: bearer:
> 
> * "aud": "FSE_Gateway" --> da correggere in "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1"
> * "iss": "auth:WECONSTUDIO SRL" --> deve essere valorizzato con “auth:” seguito dal “Common Name del certificato di firma”. esempio "auth:S1#111XXXXXXXXXXXXX"
> 
> fse-jwt:
> 
> * "aud": "FSE_Gateway" --> da correggere in "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1"
> * "iss": "integrity:WECONSTUDIO SRL" --> deve essere valorizzato con “integrity:” seguito dal “Common Name del certificato di firma”. esempio "integrity:S1#111XXXXXXXXXXXXX"
> 
> La rimandiamo alla [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt) per ulteriori dettagli.

Il tool per la generazione dei JWT riceve in input un unico JSON e restituisce in output sia il bearer che il fse-jwt. Considerando che il campo iss deve cambiare è necessario eseguire due volte il tool scartando di volta in volta il token "sbagliato"?

**Comment by IStacchiotti** [comment]
Buongiorno @garaznico, se sta utilizzando il tool jwt-generator disponibile al [link](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator), è sufficiente riportare il **common name** (S1#111XXXXXXXXXXXXX) in corrispondenza del campo "iss" presente nel data json che prende in ingresso il tool in questione: sarà poi lo strumento infatti a differenziare il campo iss nei due token anteponendo la stringa "auth" piuttosto che "integrity" al common name. Per svolgere una verifica, è possibile decriptare i token tramite questo [web-service](https://jwt.io/). Rimaniamo a disposizione nel caso in cui dovesse essere necessario ulteriore supporto, grazie

**Comment by garaznico** [comment]
Grazie per la risposta. Si, stavo utilizzando il tool jwt-generator ed effettivamente controllando il contenuto dei jwt i campi sono valorizzati nel modo corretto.

Purtroppo provando nuovamente la chiamata ricevo ancora come errore 'Received request is not conform to the required interoperability profile'
Allego di seguito i 2 token utilizzati, sapete darmi qualche indicazione a riguardo?

[bearer.txt](https://github.com/ministero-salute/it-fse-support/files/11905100/bearer.txt)
[fse-jwt.txt](https://github.com/ministero-salute/it-fse-support/files/11905101/fse-jwt.txt)


Grazie

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
