### ISSUE TITLE
Problemi in fase di accreditamento

### ISSUE THREAD

**Issue by GrecoStefano** [ministero-salute/it-fse-support#427]
Buongiorno a tutti, durante i test per l'accreditamento ho riscontrato un problema con gli id 217, 218,219. Nel test bisogna inserire nella requestBody dei prefissi nel campo identificativoDoc ma se faccio come riportato il servizio non riconosce più la precedente validazione del CDA iniettato nel PDF. Come ci si deve comportare in questo caso? Vi aggiungo la requestBody e la response che riceviamo (specifico ancora che la validazione è stata effettuata con esisto 201)

```
{
  "tipologiaStruttura": "Ospedale",
  "tipoDocumentoLivAlto": "LDO",
  "assettoOrganizzativo": "AD_PSC001",
  "tipoAttivitaClinica": "DIS",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.2.120.4.3.12345",
  "identificativoDoc": "CRASH_INI_2.16.840.1.113883.2.9.2.120.4.4^87251",
  "identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.97128",
  "healthDataFormat": "CDA",
  "mode": "ATTACHMENT"
}
```
```
{
  "traceID": "0bdef38c5c6d818e",
  "spanID": "0bdef38c5c6d818e",
  "type": "/msg/cda-match",
  "title": "Errore in fase di recupero dell'esito della verifica.",
  "detail": "Il CDA non risulta validato",
  "status": 400,
  "instance": "/cda-validation"
}
```

i prefix che non funzionano sono :

- "CRASH_INI_"
- "CRASH_EDS_"
- "CRASH_WF_EDS_"

**Comment by masciamariotti** [comment]
Buonasera @GrecoStefano,
potrebbe allegare il file pdf che sta validando, e quello che sta utilizzando in pubblicazione?
Grazie

**Comment by GrecoStefano** [comment]
Buonasera @masciamariotti , 
il pdf è quello fornito nel repository [it-fse-accreditamento](https://github.com/ministero-salute/it-fse-accreditamento). Per comodità lo riporto qui di seguito. 
[SIGNED_LDO1.pdf](https://github.com/ministero-salute/it-fse-support/files/11897769/SIGNED_LDO1.pdf)

**Comment by GrecoStefano** [comment]
Buongiorno, si hanno novità per la problematica segnalata?

**Comment by vigliottim** [comment]
Buongiorno, le comunichiamo che è stata rilasciata una fix correttiva e la invitiamo cortesemente a riprovare: il problema non dovrebbe più presentarsi. Rimaniamo a completa disposizione in caso contrario. Grazie.
