### ISSUE TITLE
Errore durante accreditamento per LDO: è richiesta diagnosi di accettazione codificata?

### ISSUE THREAD

**Issue by gsdefender** [ministero-salute/it-fse-support#428]
Salve,
tra gli errori che ci vengono notificati nel tentativo di passare il test case con id 6 per la LDO con 
[questo documento](https://github.com/ministero-salute/it-fse-support/files/11903291/LDO1.pdf) è presente il seguente:

{
  "id" : 6,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='073' attribute='code' actual = '' expected = '8646-2'>ClinicalDocument/component/structuredBody/component/section[ID='Motivo_Ricovero']/entry/observation/code</error>"
}

Non riusciamo a capire il motivo di questo specifico errore: è vero che la section non ha l'ID Motivo_Ricovero, e questo possiamo farlo generare, ma da specifiche entry/observation è opzionale. Dal momento che il nostro software CareMed non implementa ancora la diagnosi di accettazione codificata, ma solo quella a testo libero, non generiamo entry/observation. C'è un problema nel validatore o sto leggendo male l'errore?

**Comment by IStacchiotti** [comment]
Buongiorno @gsdefender, 
Le confermiamo che l'assenza del tag section ID="Motivo_Ricovero" è responsabile di alcuni degli errori che si sono originati.

La rimandiamo a questo [link](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/6-Lettera%20di%20Dimissione%20Ospedaliera), e in particolare al documento "[CDA2_Lettera di Dimissione Ospedaliera_OK.xlsx](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/6-Lettera%20di%20Dimissione%20Ospedaliera/CDA2_Lettera%20di%20Dimissione%20Ospedaliera_OK.xlsx)", sheet "LDO - Caso di Test 1", in cui sono riportate le indicazioni per la compilazione del CDA di LDO in riferimento al particolare caso di test. Per rispondere alla sua domanda, specifichiamo che nella colonna "D" è riportata l'obbligatorietà secondo le specifiche nazionali, mentre nella colonna "F", in rosa, è riportata l'obbligatorietà per lo specifico caso di test.

Le segnaliamo infine che è disponibile a questo [link ](https://github.com/ministero-salute/it-fse-gtw-tools) il tool "gwt-certifier", che consente di riprodurre in locale le verifiche dei test case di validazione OK richiesti durante la fase di accreditamento.

Rimaniamo a disposizione per ulteriore supporto, grazie

**Comment by gsdefender** [comment]
Grazie.
Mi sembra di capire, consultando [CDA2_Lettera di Dimissione_Ospedaliera_OK.xlsx](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/6-Lettera%20di%20Dimissione%20Ospedaliera/CDA2_Lettera%20di%20Dimissione%20Ospedaliera_OK.xlsx), che allo stato attuale non potremo soddisfare i test case 1, 2, 3, 4 della lettera di dimissione.
Qualche settimana fa è stato introdotto il test case 0, che prevedendo solo le sezioni obbligatorie da CDA2 riteniamo di poter passare.
La domanda è: è sufficiente passare il solo test case 0 della lettera di dimissione (ma a questo punto il ragionamento vale per tutte le altre tipologie di documenti conferibili) per conseguire l'accreditamento per la specifica tipologia di documento? 
Lo chiedo per orientare il nostro lavoro nell'immediato.
Grazie

**Comment by vigliottim** [comment]
Buonasera, se non è possibile eseguire alcuni test case a meno di forzature potete dichiararli come "non applicabili". In questo caso, però, è necessario indicare quali sono gli impedimenti tecnici. Inoltre, le confermiamo che è sufficiente anche un solo test case applicabile (ad esempio, includendo esclusivamente il caso di test 0) per conseguire l'accreditamento per la specifica tipologia di documento. Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by gsdefender** [comment]
Perfetto. Grazie

**Comment by gsdefender** [comment]
Devo riaprire la issue.
I test case 0 OK di validazione per LDO, RAD, RSA hanno rispettivamente ID 369, 370, 374.
Se proviamo ad eseguire gtw-certifier, però, sembra che questi siano riconosciuti come test case KO e non vengono valutati.
gtw-certifier è stato scaricato e compilato ieri dal repository github.
Cosa stiamo sbagliando?

**Comment by IStacchiotti** [comment]
Buonasera @gsdefender, con i test case 0 non è necessario eseguire il gtw-certifier: è sufficiente l'OK dal Gateway come evidenza positiva per procedere con il processo di accreditamento.

**Comment by gsdefender** [comment]
OK grazie
