### ISSUE TITLE
nuova Pull request

### ISSUE THREAD

**Issue by dtsconsulting** [ministero-salute/it-fse-support#430]
abbiamo provveduto a risottomettere la check-list  psecondo le indicazioni.
per l'accreditamento

**Comment by IStacchiotti** [comment]
Buonasera, Le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email. Grazie.
