### ISSUE TITLE
Servizio status

### ISSUE THREAD

**Issue by DATASOFTNA** [ministero-salute/it-fse-support#432]
Buonasera, provando a testare il servizio status ottengo la risposta 404
Il comando e' questo (copiato da editor.swagger.io)

curl -s -k -X 'GET' **https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/status** --cert-type P12 --cert keystore_auth.p12:*********** -H 'accept: application/json' -H "Authorization: Bearer ${AUTB}"

**Il token AUTB e' corretto**
Stessa cosa con
curl -s -k -X 'GET' **https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/status/** --cert-type P12 --cert keystore_auth.p12:*********** -H 'accept: application/json' -H "Authorization: Bearer ${AUTB}"

L'esito e' questo
{"type":"https://govway.org/handling-errors/404/UndefinedOperation.html".
"title":"UndefinedOperation".
"status":404.
"detail":"Operation undefined in the API specification".
"govway_id":"da94d282-1776-11ee-8674-005056ae54fa"}

**Comment by DATASOFTNA** [comment]
Si', gli altri due servizi li ho testati e funzionano, ma siccome quello in oggetto e' tra i servizi illustrati in editor.swagger.io , devo dedurre che e' **momentaneamente** non disponibile ?
Non e' un servizio fondamentale, ma potrebbe tornare utile in caso di interruzione del funzionamento del server (cosa che per FSE attuale capita ogni tanto e gli utenti si allarmano...).

**Comment by IStacchiotti** [comment]
Buongiorno @DATASOFTNA, il servizio al momento è riportato nello swagger per vincoli tecnici. Verrà fornita comunicazione nel caso in cui il servizio [v1/status](https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/status) dovesse essere esposto esternamente prossimamente. Grazie
