### ISSUE TITLE
Validazione - FileSizeLimitExceededException: The field file exceeds its maximum permitted size of 1048576 bytes.

### ISSUE THREAD

**Issue by MarcoKnezevichInsiel** [ministero-salute/it-fse-support#433]
Buongiorno,

stiamo eseguendo dei test di validazione dal nostro middleware regionale con una terza parte (log80).
Riceviamo un errore anomalo dovuto alla dimensione del file, esistono dei limiti legati alla dimensione del documento?

Errore rilevato:
```
{
  "traceID": "7ca048c121156c4d",
  "spanID": "7ca048c121156c4d",
  "type": "/msg/generic-error",
  "title": "Errore generico.",
  "status": 500,
  "detail": "Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.impl.FileSizeLimitExceededException: The field file exceeds its maximum permitted size of 1048576 bytes.",
  "instance": ""
}
```
Alleghiamo il file.

[LOG80_LETTERA_TEST_3.pdf](https://github.com/ministero-salute/it-fse-support/files/11936302/LOG80_LETTERA_TEST_3.pdf)

**Comment by IStacchiotti** [comment]
Buonasera, chiudiamo il presente in quanto duplicato del ticket #365, che vi invitiamo a monitorare. Grazie
