### ISSUE TITLE
Mail da fse_support

### ISSUE THREAD

**Issue by DATASOFTNA** [ministero-salute/it-fse-support#435]
Buonasera,
Un volta caricati i file di test si riceve da fse_support una mail con l'esito del controllo.
Per interagire con il verificatore, si puo' utilizzare questo ambiente oppure si puo' rispondere alla mail ?
Nel json con gli errori ricevuto, c'e' la segnalazione "**CDA contenuto nel PDF non conforme a quello associato al TraceID**", cosa significa ?

**Comment by IStacchiotti** [comment]
Buongiorno @DATASOFTNA, la invitiamo ad aprire sempre un ticket per richiedere supporto: è il sistema che garantisce un riscontro in manera più rapida. Per quanto riguarda l'errore in segnalato, "CDA contenuto nel PDF non conforme a quello associato al TraceID", questo genere di errore si verifica quando il CDA nel pdf pushato su GitHub tramite pull request, non corrisponde a quello associato al trace id del relativo test eseguito. Potete verificare che i pdf caricati siano effettivamente quelli utilizzati nei test e che nel file json pushato su GitHub i pdf in questione siano referenziati correttamente? Grazie

**Comment by DATASOFTNA** [comment]
> Potete verificare che i pdf caricati siano effettivamente quelli utilizzati nei test e che nel file json pushato su GitHub i pdf in questione siano referenziati correttamente? Grazie
Forse ho fatto qualche errore a riportare i traceId nel file json e nel report xls , percio' ho ricostruito la cartella da capo , rilanciato i test ed editato il json ed il report.
Resta il fatto che il controllo viene effettuato un file alla volta e si interrompe una volta trovato un errore, per cui se si fa un errore a compilare sia il report che il json, occorrono 2 giorni per mandare una correzione.
Il mio probabilmente e' un caso particolare, ma sarebbe auspicabile fare il controllo di correttezza di tutti e due i file in una sola volta.

**Comment by IStacchiotti** [comment]
Buongiorno @DATASOFTNA, il processo prevede che vengano svolte delle verifiche preliminari sulla corretta compilazione della checklist di accreditamento e che, solo a valle e in seguito a esito positivo, si svolgano le verifiche successive sugli altri file contenuti nella pr.

**Comment by DATASOFTNA** [comment]
**il processo prevede che vengano svolte delle verifiche preliminari sulla corretta compilazione della checklist di accreditamento e che, solo a valle e in seguito a esito positivo, si svolgano le verifiche successive sugli altri file contenuti nella pr.**
Questo l'avevo capito, ma sarebbe piu' rapido verificare il json anche se la checklist presenta degli errori.
Ad esempio nel json che avevo mandato il tag traceID era scritto traceiD, ma questo l'ho potuto scoprire solo due invii della checklist e nel frattempo sono passati due giorni.

**Comment by IStacchiotti** [comment]
Buongiorno, prendiamo atto della richiesta, che verrà riportata al team di competenza.
Nel frattempo procediamo con la chiusura del presente. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto in relazione alla stessa tematica. Grazie
