### ISSUE TITLE
Info su CDA iniettato nel PDF 

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#437]
Buongiorno,
sono disponibili delle specifiche che descrivono come si deve realizzare un file PDF con CDA iniettato come allegato (EmbeddedFiles)?

Guardando la documentazione delle Interfacce REST del Gateway si evince che
- il documento deve avere il formato standard HL7 CDA2
- il documento CDA deve essere iniettato in un PDF come allegato (1 CDA in 1 PDF)
- il nome CDA allegato deve essere cda.xml

Invece nel readme di pdf-generator si trova il nome CDA.xml
Qual è il nome corretto da usare? cda.xml o CDA.xml?

Per quanto riguarda il formato del file PDF, nelle Linee Guida per l’Attuazione del Fascicolo Sanitario Elettronico è indicato il formato PDF/A
Quindi si possono usare tutti gli ulteriori sottolivelli? 
es: PDF/A-2, PDF/A-2a, PDF/A-2b, PDF/A-3, PDF/A-3b, ...
Oppure ci sono dei vincoli sui formati accettati dal gateway?

Grazie

**Comment by IStacchiotti** [comment]
Buonasera @ponsilva, per il primo punto la invitiamo ad utilizzare la stringa "cda.xml" per il cda iniettato nel pdf, come riportato in documentazione. Per il secondo punto, lato Gateway non c'è un controllo sulla tipologia/contenuto di PDF, ma solo che sia un PDF (i.e. magic number).

**Comment by ponsilva** [comment]
grazie per la precisazione
