### ISSUE TITLE
Quesito in merito a Reazioni Avverse in CDA2 Certificato vaccinale.

### ISSUE THREAD

**Issue by giuseppe-fasulo** [ministero-salute/it-fse-support#439]
Buongiorno. Ho un quesito in merito al CDA2 del certificato vaccinale. A pag 74 della specifica HL7It-IG_CDA2_VAC-v1.1-S, come pure nella CONF-VAC- 83 a pag 83 si afferma che è ammessa opzionalmente al più UNA entryRelationship per indicare le Reazioni avverse. La stessa specifica a pag 165 indica invece cardinalità 0..N. Dal punto di vista clinico mi segnalano che sono possibili più reazioni avverse. In questo caso  si porrebbe un problema. In attesa di vs riscontro. Grazie

**Comment by vigliottim** [comment]
Buongiorno, grazie per la segnalazione. 
E' stata modificata la guida HL7 Italia di Vaccinazioni (reperibile al seguente link http://www.hl7italia.it/hl7italia_D7/node/2343/), che consente di inserire più entryRelationship relative alle Reazioni avverse. Pertanto, verrà pubblicata la versione aggiornata dello schematron.

**Comment by vigliottim** [comment]
Buongiorno, la informiamo che è stato effettuato l'aggiornamento degli schematron. Chiudiamo il presente ticket e restiamo a disposizione per ulteriore supporto.
