### ISSUE TITLE
Una LDO senza ClinicalDocument/recordTarget/patientRole/id passa la validazione del GTW

### ISSUE THREAD

**Issue by g-polverini** [ministero-salute/it-fse-support#44]
Il caso di test 5 per la LDO (VALIDAZIONE_CDA2_LDO_CT5_KO, ID 63), che consiste nel mandare un documento senza specificare ClinicalDocument/recordTarget/patientRole/id, dà un risultato inatteso:
offline ho giustamente errore di validazione usando lo schema
```
L'elemento "patientRole" nello spazio dei nomi "urn:hl7-org:v3" ha un elemento figlio non valido "patient" nello spazio dei nomi "urn:hl7-org:v3". Elenco di possibili elementi previsti: "realmCode, typeId, templateId, id" nello spazio dei nomi "urn:hl7-org:v3".
```
ma inviando il documento al GTW non ho alcun errore (il che significa che la validazione utilizza soltanto lo schematron, perché anche a me offline con lo schematron passa)
Inserisco i dati di risposta
```
Status Code: 200
Response:
{
	"traceID": "8e1166c40904d612",
	"spanID": "8e1166c40904d612",
	"workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.381401432ba219569cff19e9055ed952eb6b33378031d4ea13a29cb3d4d3c124.6b44d7c8f3^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
	"warning": "[W003|  Sezione Condizioni del paziente e diagnosi alla dimissione: La sezione PUO' contenere l'elemento 'entry' ]"
}
```

**Comment by LeonardoAlcaro** [comment]
Buon pomeriggio,
abbiamo preso in carico la segnalazione appena possibile aggiorneremo gli schematron del GTW relativamente alla problematica segnalata.

**Comment by g-polverini** [comment]
Ho verificato, e la risposta è stata questa:
```json
{
  "traceID": "c79beeb8959b7ab6",
  "spanID": "c79beeb8959b7ab6",
  "type": "/msg/jwt-validation",
  "title": "Campo token JWT non valido.",
  "detail": "JWT payload: non è stato possibile verificare il codice fiscale del paziente presente nel CDA",
  "status": 403,
  "instance": "/jwt-person-id",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.cfa181894f5e65f5d428426ea0bf7de76562b14efb37c5bfc823a8fe787fdb97.c54d39ba25^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```
Naturalmente l'id del paziente è stato tolto, ma devo comunque specificare il CF nel campo "person_id" del json usato per invocare l'utility `jwt-generator`
È questo l'errore atteso?

**Comment by g-polverini** [comment]
Chiedo se sia questo l'errore atteso, perché casi di test LDO.docx recita:
> **CASO DI TEST 5**
Prendendo in esame la fase di compilazione dei dati anagrafici dell’assistito, il test case riguarda la generazione di un errore sintattico dovuto al mancato inserimento dell’identificativo univoco del paziente (recordTarget/patientRole/id).

Però qua l'errore è un 403, che indica "Token jwt mancante o non valido" - vedere https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#32-response - che è anche giusto in questo caso, ma non corrisponde secondo me a quanto richiesto nel documento.

**Comment by Ser-ena** [comment]
Buonasera, sono stati aggiornati i controlli, potrebbe cortesemente effettuare un nuovo test.

**Comment by g-polverini** [comment]
Buongiorno,
continuo ad avere il comportamento precedente.
```
{
  "traceID": "0278ce14116f88c7",
  "spanID": "0278ce14116f88c7",
  "type": "/msg/jwt-validation",
  "title": "Campo token JWT non valido.",
  "detail": "JWT payload: non è stato possibile verificare il codice fiscale del paziente presente nel CDA",
  "status": 403,
  "instance": "/jwt-person-id",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.fbf1ddd181bd69d8f78f755c5601f6b4866d1f4df93ce19d92aedccbfdaff8ce.471d13c828^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```

**Comment by g-polverini** [comment]
Secondo me il problema è che il test 5, così come è espresso, non è fattibile.
> CASO DI TEST 5
> Prendendo in esame la fase di compilazione dei dati anagrafici dell’assistito, il test case riguarda la generazione di un errore sintattico dovuto al mancato inserimento dell’identificativo univoco del paziente (recordTarget/patientRole/id).

Se non inserisco nell'xml il campo `recordTarget/patientRole/id`, non arriverò mai comunque alla validazione della CDA, perché il GTW controlla prima il token, e se lo genero senza campo `person_id`, avrò come errore
```json
{
  "traceID": "8965b0559b9d671f",
  "spanID": "8965b0559b9d671f",
  "type": "/msg/jwt-validation",
  "title": "Campo token JWT non valido.",
  "detail": "Il campo person_id non è valorizzato",
  "status": 403,
  "instance": "/jwt-mandatory-field-missing",
  "workflowInstanceId": "UNKNOWN_WORKFLOW_ID"
}
```
Se invece lo genero
```javascript
// data.json per jwt-generator
{
  "sub": "...",
  ...
  "person_id": "RSSMTS70A01G157Y^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO",
  "pem_path": "...",
  "p12_path": "...",
  ...
}
```
poi la prima validazione è di mismatch (l'errore del mio precedente messaggio)

**Comment by IStacchiotti** [comment]
Buongiorno @g-polverini, può eseguire il test eliminando il campo _confidentialityCode_ invece che _patientRole/id_.

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
