### ISSUE TITLE
400 Bad Request - Verifica con resources

### ISSUE THREAD

**Issue by federicolau** [ministero-salute/it-fse-support#440]
Ciao,

sto tentando di chiamare l'API "v1/documents/validation" ma ottengo il seguente errore:

**400 Bad Request: "{"traceID":"af12108d983cdd77","spanID":"af12108d983cdd77","type":"/msg/cda-element","title":"Errore in fase di estrazione del CDA.","detail":"Error while extracting CDA from PDF document","status":400,"instance":"/cda-extraction","workflowInstanceId":"UNKNOWN_WORKFLOW_ID"}"**

In allegato la request che invio (headers+body) e il pdf che allego.

Grazie per il supporto.

[request.txt](https://github.com/ministero-salute/it-fse-support/files/11980316/request.txt)
[cda_sample.pdf](https://github.com/ministero-salute/it-fse-support/files/11980328/cda_sample.pdf)

**Comment by masciamariotti** [comment]
Buongiorno,
analizzando il file .pdf ci risulta che il cda sia iniettato in modalità ATTACHMENT, e non RESOURCE.
Pertanto, per ovviare all' errore riportato sopra, dovrebbe modificare il parametro mode in requestBody
da "mode": "RESOURCE"
a "mode": "ATTACHMENT".
Rimaniamo a disposizione in caso fosse necessario ulteriore supporto. Grazie

**Comment by federicolau** [comment]
Grazie per il celere riscontro.

Qui sul vostro GitHub dove posso trovare un esempio di CDA iniettato in modalità RESOURCE in maniera tale da non cambiare la request ma esclusivamente l'allegato?

**Comment by federicolau** [comment]
Ok, grazie per la delucidazione.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri chiudiamo il presente ticket e la invitiamo a riaprirlo nel caso in cui avesse bisogno di ulteriore supporto.
