### ISSUE TITLE
Accreditamento:

### ISSUE THREAD

**Issue by dtsconsulting** [ministero-salute/it-fse-support#441]

**Comment by dtsconsulting** [comment]
Buongiorno
il 06 luglio ho aggiornato il file Check List per l'accreditamento.
non ho potuto creare una nuova Pull Request in quanto ne esisteva già una aperta e l'unica cosa che mi ha consentito di fare è stata la commit dell' upload del File.
Potete darmi aggiornamenti.

**Comment by vigliottim** [comment]
Buonasera, dovrebbe aver ricevuto comunicazione via e-mail sull'esito della verifica. Pertanto, chiudiamo il presente ticket e la invitiamo a riaprirlo nel caso in cui avesse bisogno di ulteriori informazioni.
