### ISSUE TITLE
Errore BadRequest 400

### ISSUE THREAD

**Issue by giosil** [ministero-salute/it-fse-support#444]
Si segnala di ricevere un generico errore di BadRequest a fronte di una richiesta che inviata da un client diverso (mantenendo inalterato il contenuto) invece va a buon fine. Non avendo ulteriori dettagli dalla risposta ottenuta non riusciamo a comprenderne il motivo.
Di seguito la risposta (contenente i riferimenti) ottenuta da una richiesta eseguita il 30/06/2023 alle 11.02 circa:

{"type":"https://govway.org/handling-errors/400/BadRequest.html","title":"BadRequest","status":400,"detail":"Bad request","govway_id":"4bc380d6-1720-11ee-8674-005056ae54fa"}

Grazie.

**Comment by vigliottim** [comment]
Buongiorno, potrebbe provare ad effettuare una nuova request ed inviare nuovamente il govway_id? Grazie.

**Comment by giosil** [comment]
Il 18/07/2023 alle 16.43 abbiamo replicato la richiesta ottenendo:

{"type":"https://govway.org/handling-errors/400/BadRequest.html","title":"BadRequest","status":400,"detail":"Bad request","govway_id":"2eed74e2-2571-11ee-8674-005056ae54fa"}

**Comment by masciamariotti** [comment]
Buonasera,
potrebbe cortesemente inviarci il dettaglio della chiamata che sta effettuando (url, request, header e pdf)?
Grazie

**Comment by giosil** [comment]
[request.txt](https://github.com/ministero-salute/it-fse-support/files/12083725/request.txt)

**Comment by masciamariotti** [comment]
Potrebbe riprovare rimuovendo (o facendo in modo che non ci sia) i `:` dal seguente parametro nell' header?
_Content-Type: multipart/form-data; boundary=uuid`:`10c942fd-6ca5-4307-959e-87f3ad4626a5_

**Comment by giosil** [comment]
Le spiego la situazione. Abbiamo realizzato un middleware che inoltra la richiesta al Gateway lasciando inalterato il contenuto ma modificando soltanto le intestazioni relative ai Json Web Token per firmarli in maniera appropriata. Sta funzionando con diversi fornitori, tranne uno che utilizza la libreria Apache CXF forse di una versione non recente. Tuttavia se tale fornitore prova ad effettuare una chiamata diretta al Gateway (nella quale viene utilizzato un boundary analogo) essa viene accolta. Nella segnalazione chiediamo se dai log riscontrate un errore in particolare. Altrimenti proviamo a replicare le chiamate modificando a tentativi le parti che presentano diversità rispetto ad una chiamata andata a buon fine. Grazie.

**Comment by masciamariotti** [comment]
Buongiorno,
purtroppo l'errore sta ad indicare che la chiamata è sintatticamente errata, per cui non abbiamo i log.
Le chiediamo pertanto di modificare quanto indicato e riprovare, e fornire eventualmente il nuovo govway-id e request/header inviati.
Grazie

**Comment by masciamariotti** [comment]
Buon pomeriggio, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
