### ISSUE TITLE
Attesa accreditamento

### ISSUE THREAD

**Issue by DATASOFTNA** [ministero-salute/it-fse-support#445]
Buongiorno,
Credo di avere affettuato l'ultima pull request il 10 Luglio, ma finora non ho ricevuto nessuna comunicazione sullo stato dell'accreditamento, e' normale ?
Se eventualmente dovessi ripetere la richiesta di PULL, potrebbe essere controproducente ?
Grazie.

**Comment by masciamariotti** [comment]
Buongiorno,
Le confermiamo che dovrebbe aver ricevuto una mail sull' esito delle verifiche il giorno stesso (10 Luglio).
La preghiamo di verificare se la stessa sia finita erroneamente nello spam. In caso contrario provvederemo a farLe inoltrare la comunicazione.
Grazie

**Comment by masciamariotti** [comment]
Purtroppo non ci risultano nuove pull request aperte il 10 Luglio (o comunque successive alla PR #673).
Potrebbe verificare? Nel caso non risulti nemmeno a Lei, dovrebbe procedere con l'apertura di una nuova PR con le correzioni effettuate.

**Comment by DATASOFTNA** [comment]
Ok, ho eseguito di nuovo la PR, ho ricevuto anche la mail di conferma.

**Comment by vigliottim** [comment]
Procediamo alla chiusura del presente ticket e la invitiamo a riaprirlo nel caso in cui avesse bisogno di ulteriore supporto.
