### ISSUE TITLE
Errore validazione LDO e VPS "Error while searching signature for file with name"

### ISSUE THREAD

**Issue by stellariAbstract** [ministero-salute/it-fse-support#446]
Buongiorno,
  i primi test di validazione sembravano essere andati a buon fine ma ora che sto eseguendo i test per l'accreditamento ottengo quasi sempre l'errore "Error while searching signature for file with name" (troncato così, senza nulla dopo "name") sia per LDO che per VPS.

L'ultimo inviato in ordine cronologico ha traceId = 4815d86176cb9de1
Allego il PDF.

[VPS_ABSTRACT_00.pdf](https://github.com/ministero-salute/it-fse-support/files/12069051/VPS_ABSTRACT_00.pdf)

Da cosa potrebbe dipendere l'errore?

Grazie,
Stefano.

**Comment by vigliottim** [comment]
Buonasera, la invitiamo a riprovare e segnalarci se l'errore si ripresenta. Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto aggiornamenti, procediamo alla chiusura del presente ticket e la invitiamo a riaprirlo nel caso in cui avesse bisogno di ulteriore supporto. Grazie.

**Comment by stellariAbstract** [comment]
Buongiorno,
  chiedo di riaprire la issue in quanto il problema "Error while searching signature for file with name" si ripresenta nuovamente ogni volta che cerco di validare un documento (in questo caso un VPS).

Sarebbe possibile sapere quali siano le cause scatenanti?

Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno @stellariAbstract, le suggeriamo di ritentare provando a chiamare il servizio di validazione online, nel caso in cui non lo abbia già fatto. Ci faccia sapere se il problema persiste, in modo da poterle fornire ulteriore supporto. Grazie

**Comment by stellariAbstract** [comment]
Potrei avere un link a tale servizio?
Grazie

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by IStacchiotti** [comment]
Certamente, le condivido di seguito il link alla [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway), con le specifiche per invocare i servizi esposti dal Gateway **online**. Se dovesse riscontrare degli errori, può chiedere supporto tramite questo canale, avendo cura di allegare, ove disponibili, govway_id, traceid, workflowinstanceId e il messaggio di errore tornato, insieme al pdf utilizzato nell'invocazione. Grazie

**Comment by stellariAbstract** [comment]
Ringrazio per la risposta ma chiedo un chiarimento.
Vedo che “online” è in grassetto, come ad indicare un modo diverso da quello che sto utilizzando attualmente.  Forse mi sta sfuggendo qualcosa, ma io sto effettivamente mandando la richiesta a :
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation
quindi non capisco se intende questo o se intende “un altro” servizio di validazione di qualche tipo.

Se cortesemente potesse darmi un chiarimento, sarebbe gradito.

Grazie,
Stefano.


Da: IStacchiotti ***@***.***>
Inviato: lunedì 7 agosto 2023 13:11
A: ministero-salute/it-fse-support ***@***.***>
Cc: Stellari Stefano ***@***.***>; Mention ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Errore validazione LDO e VPS "Error while searching signature for file with name" (Issue #446)


Certamente, le condivido di seguito il link alla documentazione<https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway>, con le specifiche per invocare i servizi esposti dal Gateway online. Se dovesse riscontrare degli errori, può chiedere supporto tramite questo canale, avendo cura di allegare, ove disponibili, govway_id, traceid, workflowinstanceId e il messaggio di errore tornato, insieme al pdf utilizzato nell'invocazione. Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.

**Comment by stellariAbstract** [comment]
Chiedo scusa per non aver risposto in tempo ma è un periodo di migrazione dei server presso il cliente e non ho avuto modo di farlo.

Vi inoltro un nuovo caso generato, ditemi se possibile riaprire la issue.

TraceID: ea281e3a159f1dfc
SpanID: ea281e3a159f1dfc
Error Detail: "Error while searching signature for file with name"
[Caso_test_VPS.pdf](https://github.com/ministero-salute/it-fse-support/files/12511241/Caso_test_VPS.pdf)

Grazie,
Stefano.

**Comment by IStacchiotti** [comment]
Buongiorno @stellariAbstract,
Abbiamo provveduto alla riapertura del ticket. 
Ricercando l'esito della vostra chiamata attraverso il servizio status, otteniamo ancora 404 - "Record non trovato", che sembrerebbe indicare il mancato tracciamento nei log della vostra invocazione.
Potreste cortesemente allegare la risposta completa restituita dal sistema, comprensiva del codice status dell'errore (es. 400) e ove disponibili, govway_id, traceid, workflowinstanceId. Grazie

**Comment by stellariAbstract** [comment]
Salve,
  ho provato a validare nuovamente il documento e la risposta che ottengo è la seguente:

{"traceID":"cc29dd0ab721996b","spanID":"cc29dd0ab721996b","type":"/msg/generic-error","title":"Errore generico.","detail":"Error while searching signature for file with name","status":500,"instance":""}


Da: IStacchiotti ***@***.***>
Inviato: lunedì 4 settembre 2023 10:40
A: ministero-salute/it-fse-support ***@***.***>
Cc: Stellari Stefano ***@***.***>; Mention ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Errore validazione LDO e VPS "Error while searching signature for file with name" (Issue #446)


Buongiorno @stellariAbstract<https://github.com/stellariAbstract>,
Abbiamo provveduto alla riapertura del ticket.
Ricercando l'esito della vostra chiamata attraverso il servizio status, otteniamo ancora 404 - "Record non trovato", che sembrerebbe indicare il mancato tracciamento nei log della vostra invocazione.
Potreste cortesemente allegare la risposta completa restituita dal sistema, comprensiva del codice status dell'errore (es. 400) e ove disponibili, govway_id, traceid, workflowinstanceId. Grazie

**Comment by IStacchiotti** [comment]
Grazie per il rapido riscontro. Dalle verifiche risulta che nell'invocazione è stato referenziato il file "**CDA.pdf**", invece del file allegato nei messaggi precedenti "**Caso_test_VPS.pdf**". Potreste verificare e fornirci evidenza in seguito? Grazie mille

**Comment by vigliottim** [comment]
Buongiorno, potrebbe gentilmente fornirci altri file pdf utilizzati in fase di validazione? Quelli allegati in precedenza hanno errori sintattici. Grazie.

**Comment by stellariAbstract** [comment]
L’errore per il quale ho aperto la issue potrebbe dipendere da questi errori sintattici?


Da: Michela Vigliotti ***@***.***>
Inviato: martedì 5 settembre 2023 10:18
A: ministero-salute/it-fse-support ***@***.***>
Cc: Stellari Stefano ***@***.***>; Mention ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Errore validazione LDO e VPS "Error while searching signature for file with name" (Issue #446)


Buongiorno, potrebbe gentilmente fornirci altri file pdf utilizzati in fase di validazione? Quelli allegati in precedenza hanno errori sintattici. Grazie.

**Comment by IStacchiotti** [comment]
Buonasera, per consentire la prosecuzione delle analisi, potrebbe allegare esattamente il file pdf che è stato utilizzato nell'invocazione? Grazie

**Comment by stellariAbstract** [comment]
Salve, il file utilizzato nell’invocazione è il primo che avevo mandato.
Lo allego nuovamente.
Potrei chiedere quale sia il problema di sintassi che mi era stato segnalato nella mail precedente?
Inoltre, come chiedevo in precedenza, è il problema di sintassi  a causare l’errore “Error while searching signature for file with name” ?
A differenza della mail precedente ho rinominato il file allegato in “CDA.pdf” per evitare equivoci.

Grazie.


Da: IStacchiotti ***@***.***>
Inviato: martedì 5 settembre 2023 15:19
A: ministero-salute/it-fse-support ***@***.***>
Cc: Stellari Stefano ***@***.***>; Mention ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Errore validazione LDO e VPS "Error while searching signature for file with name" (Issue #446)


Buonasera, per consentire la prosecuzione delle analisi, potrebbe allegare esattamente il file pdf che è stato utilizzato nell'invocazione? Grazie

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
L'errore sintattico riscontrato nelle analisi ci aspettiamo che si verifichi in una fase successiva rispetto a quello da lei segnalato "Error while searching signature for file with name", pertanto escludiamo al momento che possa esserne la causa.
La ringraziamo per aver chiarito quale file abbia utilizzato nelle invocazioni. Sono in corso al momento le analisi per risalire all'origine dell'errore "Error while searching signature for file with name", le faremo sapere il prima possibile.

Grazie.

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi eseguite risulta che il file usato in validazione è differente da quello allegato al presente ticket, come mostra lo screenshot seguente:
![screenshot](https://github.com/ministero-salute/it-fse-support/assets/134372089/a790940b-cd98-42d0-a2c5-39b099f059fb)
Inoltre, è emerso che il file pdf utilizzato in validazione è corrotto (non viene aperto con Adobe). 
La invitiamo ad utilizzare un file integro e riprovare, grazie. 
Infine, le segnaliamo che il messaggio di errore restituito dal sistema "Error while searching signature for file with name" non è pertinente in questo caso, è stato svolto il deploy di una fix per evitare che sia originato in situazioni analoghe a questa.
Rimaniamo a disposizione per eventuali ulteriori richieste di supporto.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
