### ISSUE TITLE
patientRole SSN

### ISSUE THREAD

**Issue by ftallaro** [ministero-salute/it-fse-support#447]
Buongiorno,

nel documento "Implementation Guide Clinical Document Architecture (CDA) Rel. 2" viene riportato l'obbligatorietà dell'inserimento di un secondo id così fatto:

root="[OID_SPAZIO_IDENTIFICAZIONE__AZIENDA_CUSTODE_PACS]"
extension="[NUMERO_IDENTIFICATIVO__PERSONALE]"
assigningAuthorityName="[NOME_SPAZIO_IDENTIFICAZIONE_AZIENDA_CUSTODE_PACS]"

Nel caso di Cliniche private queste devono richiedere il rilascio di un oid nel sito web http://www.hl7.org/Oid/ ?

In caso contrario cosa dobbiamo inserire? In un esempio di Dicembre rilasciato dalla regione Sicilia venivano riportate la seguente riga:

id assigningAuthorityName="Regione Sicilia" extension="190206123456" root="2.16.840.1.113883.2.9.2.190.4.1"

l'extension in entrambi i casi è cod.reg+cod. asp+STS11 ?

Vi ringrazio

**Comment by vigliottim** [comment]
Buongiorno, da specifiche HL7 l'inserimento di un secondo id per il patientRole è obbligatorio solamente nel caso di un assistito assicurato da istituzioni estere (tessera TEAM) oppure nel caso di Referto di Radiologia dove viene richiesto l'inserimento di un secondo id che riporta l'identificativo dell'assistito nel sistema PACS. 
Per tutte le altre tipoligie documentali ed esclusi i casi citati in precedenza, il secondo id è opzionale. 
Inoltre, l'attributo estension di un identificativo regionale o locale è univoco per ogni paziente, non ha una valorizzazione vincolata da specifiche, a differenza ad esempio del codice fiscale o del codice STP.
Infine, le chiediamo di gentilmente di esplicitare l'oid che cita nella frase: "l'inserimento di un secondo id così fatto:". 
Grazie.

**Comment by ftallaro** [comment]
Buonasera,

mi scuso se non si vedeva il secondi id ma avevo fatto copia ed incolla lasciando i tag xml.

Si mi riferivo al Referto di radiologia. Il pezzo mancante l'id contenete le 3 seguenti informazioni:

OID dello spazio di identificazione usato nell’Azienza che custodisce il PACS nel quale sono contenute le immagini:
root="[OID_SPAZIO_IDENTIFICAZIONE__AZIENDA_CUSTODE_PACS]"

Il numero di identificazione dell’assistito nel sistema PACS in cui sono custodite le immagini:
extension="[NUMERO_IDENTIFICATIVO__PERSONALE]"

Nome dello spazio di identificazione usato nell’Azienza che custodisce il PACS nel quale sono contenute le immagini:
assigningAuthorityName="[NOME_SPAZIO_IDENTIFICAZIONE_AZIENDA_CUSTODE_PACS]"

Come vi chiedevo non capisco bene quali informazioni inserire.

**Comment by ftallaro** [comment]
Ok grazie.

**Comment by LucaRogledi** [comment]
Salve, grazie per il feedback, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
