### ISSUE TITLE
Vocabolari

### ISSUE THREAD

**Issue by ftallaro** [ministero-salute/it-fse-support#448]
Buongiorno,

mi potreste indicare dove reperire le tabelle di associazione per i valori LOINC e ICD9CM per le varie casisitiche di CDA2?

Inoltre inserendo le traslation nazionale e regione SICILIA quali OID bisogna rispettivamente utilizzare?

Infine, la codifca principale degli esami, ad esempio nel CDA2 di RAD, qual'è? Dalle specifiche HL7 Italia sembrerebbe che sia LOINC o ICD9CM ma dagli esempi e dai test case non sembra siano quest'ultimi.

Grazie.

**Comment by masciamariotti** [comment]
Buongiorno,
per i primi due punti Le chiediamo di far riferimento alla Implementation Guide di HL7 Italia presente al presente [link](http://www.hl7italia.it/hl7italia_D7/node/2359).
Riguardo l'ultimo punto, potrebbe cortesemente riportare qualche esempio/codifiche nello specifico?
Grazie

**Comment by ftallaro** [comment]
I documenti del link che mi ha indicato li ho presi tutti e dice soltanto di utilizzare le codifiche LOINC o ICD9-DM ma non c'è nessun riferimento su dove prendere questi codici e su come accoppiarli agli esami.

Riguardo l'ultimo punto ho semplicemente guardato il CDA2 di esempio [https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/RAD.xml](link) ed in questo ad esempio l'entry=>act=> code è la seguente:

<code code="113014" codeSystem="1.2.840.10008.2.16.4" codeSystemName="DCM" displayName="Study"/>

e come sistema di codifica indica DCM che non è  nessuno dei 2 precedenti segnalati nel documento HL7 Italia presente nel link che lei mi ha indicato.

Grazie a lei.

**Comment by vigliottim** [comment]
Buongiorno, per codificare gli esami di RAD si consiglia di utilizzare le codifiche LOINC o ICD-9-CM che comunque non vengono regolati da linee guida.
Nel caso della entry/act di Dicom Object Catalog, viene utilizzato il sistema di codifica DCM (1.2.840.10008.2.16.4) a titolo di esempio come anche riportato nelle linee guida di RAD. 
Qualora si ritenesse opportuno si può utilizzare anche un altro sistema di codifica.

**Comment by ftallaro** [comment]
Ok grazie.

**Comment by vigliottim** [comment]
Buongiorno, chiudiamo il presente ticket e la invitiamo a riaprirlo nel caso in cui avesse bisogno di ulteriori informazioni. Grazie.
