### ISSUE TITLE
CDA Anatomia

### ISSUE THREAD

**Issue by StefanoFalcioni** [ministero-salute/it-fse-support#450]
buongiorno,
abbiamo eseguito un test per validazione cda Anatomia e riceviamo il seguente errore dovuto al template id di anatomia

{

    "traceID": "a94b6e7e16b05d7d",

    "spanID": "a94b6e7e16b05d7d",

    "type": "/msg/semantic",

    "title": "Errore semantico.",

    "detail": "Schematron with template id root 2.16.840.1.113883.2.9.10.1.8.1 not found on database.",

    "status": 422,

    "instance": "/validation/error",

    "workflowInstanceId": "2.16.840.1.113883.2.9.2.30967.7d764c73caadae059488a29c9c4fa158cc224cfc94fb457e228117dd5c7ddc6c.d913e1bd0d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"

}

**Comment by vigliottim** [comment]
Buongiorno, il CDA "Referto di Anatomia Patologica" non è ancora disponibile. La invitiamo a consultare gli schematron utilizzabili al seguente [link](https://github.com/ministero-salute/it-fse-catalogs/tree/main/schematron). Restiamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Chiudiamo il presente ticket e la invitiamo a riaprirlo nel caso avesse bisogno di ulteriore supporto. Grazie.
