### ISSUE TITLE
Cda contenuto nel pdf non conforme a quello associato al traceID

### ISSUE THREAD

**Issue by DATASOFTNA** [ministero-salute/it-fse-support#451]
Buonasera, ho ricevuto questa segnalazione di errore per tutti i test e vorrei sapere  qual e' la corrispondenza che non viene soddisfatta.
Siccome gia' una volta ho rilanciato i test e cambiato tutti i riferimenti nel file excel e nel file json (ottenendo lo stesso effetto) , vorrei capire bene dove sbaglio prima di rifare tutto da capo nuovamente.

Ad esempio per quanto riguarda il caso 1, questi sono i riferimenti

	"id": 1,
        "ts":"2023-07-03T21:03:04Z",
	"traceId":"4b64210e50ffbc4d",		"workflowInstanceId":"2.16.840.1.113883.2.9.2.150.4.4.ca0326b86b8bdf39f9c84e63d207c0479e13dd7921d8bdd206b55515e7c883cd.62b6dc114c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
	"files": [ "TEST_CASE_OK1.PDF" ]

Il file che ho utlizzato per la prova ha il crc **628C41D9** e lunghezza  **651251** 
Il file xml iniettato ha il crc **F87D2A29** lunghezza **7964**

Riguardo a questo file ricevo l'errore Cda contenuto nel pdf non conforme a quello associato al traceID
Potrei sapere quale file risulta dal lato del verificatore, perche' sono abbastanza sicuro di avere utilizzato questo file.
Ho controllato che nella mia cartella in GitHub che questo file sia lo stesso che ho utilizzato sulla mia macchina per fare la chiamata al Gateway e mi risulta che sia quello.
Sapendo quale file risulta al verificatore almeno potrei capire se ho fatto la prova con un file diverso, ho sbagliato il traceid o qualcosa che mi sfugge.

**Altro errore:** WRONG_CLAIMS_ON_LOG (appId,appVersion,Appvendor) nella chiamata al gtw differenti da quelli dichiarati nel data.json , immagino che c'e' un dato tra appVendor, appID, appVersione che non e' piaciuto , ma vorrei sapere rispetto quali parametri vengono confrontati e magari sapere anche qual e' quello errato.
Io sospetterei dei parametri nel  JWT 

**"subject_application_id":"LABGUI",
"subject_application_vendor":"DATASOFT SRL",
"subject_application_version":"3.0"**
pero' sono gli stessi valori riportati nel data.json e anche nel file xlsx
Per caso non ci vuole lo spazio prima di SRL ?

Potreste darmi qualche delucidazione ?

Grazie.

p.s.
Ho "pushato" data.json e report relativi ad una nuova chiamata fatta oggi alle 20:59 per il TEST_CASE1 per verificare l'effetto che fa.

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Riguardo all'errore "Cda contenuto non conforme a quello associato al traceID" trova in allegato il file lato verificatore.
Invece riguardo all'errore "WRONG_CLAIMS_ON_LOG" analizzando i valori contenuti nel token abbiamo riscontrato una disuguaglianza rispetto ai valori nel data.json:

valore dal token - "subject_application_vendor": "DATASOFT"
valore dal data.json - "appVendor": "DATASOFT SRL"

[CDA_4b64210e50ffbc4d.txt](https://github.com/ministero-salute/it-fse-support/files/12096139/CDA_4b64210e50ffbc4d.txt)

**Comment by DATASOFTNA** [comment]
Ok, grazie, credo di avere risolto, ho lanciato di nuovo i test e cambiato data.json e report-checklist.xlsx.
Spero di non dovervi disturbare di nuovo.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura del presente ticket. Restiamo a disposizione nel caso in cui avesse bisogno di ulteriore supporto. Grazie.
