### ISSUE TITLE
Chiarimento campi JSON per token di autenticazione

### ISSUE THREAD

**Issue by leocogno** [ministero-salute/it-fse-support#452]
Buongiorno,
Vi scrivo per chiedere un chiarimento su alcuni campi necessari per la compilazione del JSON di autenticazione.
- "sub": bisogna comporre questo campo con il codice fiscale della persona che effettua l'invio concatenato all'OID della struttura di competenza?
- "person_id": bisogna comporre questo campo con il codice fiscale del paziente concatenato all'OID della struttura di competenza?
- "patient_consent": questo campo fa riferimento alla richiesta di oscuramento presente anche nell'xml CDA2?
Grazie in anticipo e cordiali saluti.

**Comment by vigliottim** [comment]
Buonasera, può trovare le informazioni richieste consultando la documentazione al seguente [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#111-campi-contenuti-nei-jwt).

**Comment by vigliottim** [comment]
Buongiorno, chiudiamo il presente ticket e la invitiamo a riaprirlo nel caso avesse bisogno di ulteriore supporto. Grazie.
