### ISSUE TITLE
Richiesta supporto per l’accreditamento accreditamento con il Gateway/FSE 2.0

### ISSUE THREAD

**Issue by LeoRizzoli-4wardPRO** [ministero-salute/it-fse-support#453]
Buongiorno, 
richiedo supporto per l’accreditamento accreditamento con il Gateway/FSE 2.0
 
Stiamo provando a collegarci ai ws per la validazione del CDA.
Abbiamo generato 2 Chiavi private e i 2 relativi CSR e abbiamo ottenuto i due certificati in formato PEM.
 
Il problema è il seguente:
se eseguiamo la chiamata verso l’url: https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation
viene restituito sempre un errore di SSL: 
System.Net.Http.HttpRequestException: 'The SSL connection could not be established, see inner exception.'
Win32Exception: The message received was unexpected or badly formatted.
 
Se invece utilizziamo il proxy della regione ([https://soleproxytest.progetto-sole.it/sole-proxy-services/v1/documents/validation Emilia-](https://soleproxytest.progetto-sole.it/sole-proxy-services/v1/documents/validation%20Emilia-)romanga) viene restituito il seguente errore:
                403: AuthorizationContentDeny
 
Cosa stiamo facendo:
Framework: .net 6 | OS: Windows 11
 
Impostiamo il client http con il certificato A1#1114WARDPROXX.pem per eseguire l’autenticazione al servizio, di seguito
creiamo i due token JWT, nel campo dell’header x5c mettiamo il certificato S1#1114WARDPROXX.pem e firmiamo il token tramite la chiave privata del certificato S1 (quella generata in fase di creazione del CSR).
 
Vi allego due token di esempio, confrontandoli con la doc mi sembra tutto coerente
 
Authorization: Bearer eyJ4NWMiOlsiTUlJRmFUQ0NBMUdnQXdJQkFnSVVOL0pUQnBORVE5ZEZ3ZmhFTy9YaytETW80Qm93RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TXpBMk1qQXhPVFE0TUROYUZ3MHlOakEyTWpBeE9UUTRNREphTUdveEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVJrd0Z3WURWUVFEREJCVE1TTXhNVEUwVjBGU1JGQlNUMWhZTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyWEo2VGcwUjM0M1ljbS9rOHN6REFJUHFWYVJ2SFBtc0JDRlI0WHBiUDR2d1Y0QXhJMjhiZlFGNFZseEJIUzY3RnFGUjhRM2hTN25CaVVCUDhqSHlyVURpTnV0anNwUHE0MGlCQmVBUVBlR0tBa3dDRUZJbUZaUk9NZ2YycW5jTG9YL2V0ZjdoNS94enhOeUpaSzIwS0RiaGtocVhvTTJuejl6SGdaZ3JsNnRvTUhkVkZnd2xmamFmNWxRR3IrSTVBeG5uU2t4d1c4NXo0ZVRyQ0JVTjd4RDhqTE1kcEJ3SFVETUdaNGg2Nnk3WSt6VW5uVjczWGtqcGt1elorVUVKUXJDS3REbjBMZUlNVlZiejFGUFFPZlNiaEFQYVRFVW50bllJVm9QWFN4RUsrcHhTYmJJM1ZlVC9UdklLemtGaHM3Wlk5K3draFZmWUZnMi82YzNFZHdJREFRQUJvNElCR0RDQ0FSUXdId1lEVlIwakJCZ3dGb0FVRmptcEdnV0p0dzh0c2pYdHdnbWF4UU9ESWo4d0VnWURWUjBnQkFzd0NUQUhCZ1VyVEIwQkN6Q0JyUVlEVlIwZkJJR2xNSUdpTUlHZm9JR2NvSUdaaG9HV2FIUjBjSE02THk5allYTnZaMlZwYzNacGJDNXpiMmRsYVM1cGRDOWxhbUpqWVM5d2RXSnNhV04zWldJdmQyVmlaR2x6ZEM5alpYSjBaR2x6ZEQ5amJXUTlZM0pzSm1semMzVmxjajFEVGlVelJFTkJLMDFwYm1semRHVnlieXRrWld4c1lTdFRZV3gxZEdVclZHVnpkQ1V5UTA4bE0wUk5hVzVwYzNSbGNtOHJaR1ZzYkdFclUyRnNkWFJsSlRKRFF5VXpSRWxVTUIwR0ExVWREZ1FXQkJUckJQbmFvVXFxaFdJa3dNZy8zMHRJdGx6Uk1UQU9CZ05WSFE4QkFmOEVCQU1DQmtBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFGQklqUkp5bGVPOFkxOWhVUHR4bzhEOWNwVkhzcGpxa3FESmhJT28rUjJJdEp5VzlDOENqMGc2eG1LRytESjZxQ2c5MWJnZ21jRGVCYWxlWGlzOC9xbGZaZTV3MDNBcmpnaGRQMTBnUEszVDZ6ZENFTWU2a2VGSUJxdkFYVlJRN3ZjbnJrYUJtTW9kcFhvVDJJbHVNTzZCZGFkRkVtcVU1a1J2QmFhLzRyRkIwL3RWTy9DZXBYMkpRMURWSXdtbEJIRlZFamNWYUNIdDFLQ1U5ZExFSmM5OGRnNUZFblR5WlJZM3NaeXNSb0JxR3c5dE1mTit1SUduWDZucHViQ21iTEZ4cTYwWE9VcWVocnNNdlR5aWh4V044dU5DNTM1S0tBbXFhWUtEdHYxTkhPV05pbEZZQW5jMUV4Ymt0SUZwbXpTeWlFNHI2Y2I5RXZQUHNjNVo1Z3FuOTVFUHRqVEl6OXdQczNXSjQ4UGl6YmdpSzd3Mmc0eFNKWTRwUjVVVlcrR2Uwbk9iZE1ZbytERnQ4ek5yMi8xaFpZQ0FwY2RwQzdBaXBOYS9weldmWERscDdMTGVIVDQ1cFF6NDNhZDBSWGxxUlpvc1BhZ1BHbit6M0k4aFc2L0d4RkVtLzJIYnVzV3ErQlBZa3VLL2xFZDAvTjFNd0lMTlRJV1hNcUNpcmowd1AyRmJSWmRJdHBOQm15OHhTbUViRlBESGlYMTc1Yk1RTGhESTVPMjNtYmF0MDJIUEpLTDZPTldhc0hKeEJYUEp5eXVSWERDWmljYU1HVUdqS0s2c1NQejcxSnBiSk5xN204VEYzL0dNdjllYllQSUI0azV6b2xXVHJUbFZ3Z3o4dnFZTEZTL3Nic0tvTFVIN2NISkVsR0VQS2x2dmhzMkdPazFyYklsaiJdLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODk4NDQ3OTgsImlhdCI6MTY4OTg0Mjk5OCwiaXNzIjoiYXV0aDpTMSMxMTE0V0FSRFBST1hYIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwianRpIjo4NDcxN30.LBTSULYnb78V1ZxnOuRgxO0S3oQO6CnSIvc00frWdaFi7v6bm0nXLgzs8ld1j8yROZl3A3fVAWTRlZNS5165ANlc9qH3VxjKKJw1ZoBsUDXtzJYRoTFeE7zpbAUAz1A3GnkfARMprXzzsUM23pTZsZ7YMtsQfEHzcr_LvWI7OqtpW_lb9xsoZ0harmsWLTT-mrMRQWcTi6xDcpuOM0fQJWXvzy4mqqpgrSgoBsLDpJUXqNVqCSZ8901SCRmDnqVxx6Ez5OBa0qS-IFSaNMg4KgVdyH1sG-wWeYrgBpoWvvMe8Ca5rvRQlGv7h8DrLsiqeCXA0JgsS43XCsE7GUPmrg
 
FSE-JWT-Signature: eyJ4NWMiOlsiTUlJRmFUQ0NBMUdnQXdJQkFnSVVOL0pUQnBORVE5ZEZ3ZmhFTy9YaytETW80Qm93RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TXpBMk1qQXhPVFE0TUROYUZ3MHlOakEyTWpBeE9UUTRNREphTUdveEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVJrd0Z3WURWUVFEREJCVE1TTXhNVEUwVjBGU1JGQlNUMWhZTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyWEo2VGcwUjM0M1ljbS9rOHN6REFJUHFWYVJ2SFBtc0JDRlI0WHBiUDR2d1Y0QXhJMjhiZlFGNFZseEJIUzY3RnFGUjhRM2hTN25CaVVCUDhqSHlyVURpTnV0anNwUHE0MGlCQmVBUVBlR0tBa3dDRUZJbUZaUk9NZ2YycW5jTG9YL2V0ZjdoNS94enhOeUpaSzIwS0RiaGtocVhvTTJuejl6SGdaZ3JsNnRvTUhkVkZnd2xmamFmNWxRR3IrSTVBeG5uU2t4d1c4NXo0ZVRyQ0JVTjd4RDhqTE1kcEJ3SFVETUdaNGg2Nnk3WSt6VW5uVjczWGtqcGt1elorVUVKUXJDS3REbjBMZUlNVlZiejFGUFFPZlNiaEFQYVRFVW50bllJVm9QWFN4RUsrcHhTYmJJM1ZlVC9UdklLemtGaHM3Wlk5K3draFZmWUZnMi82YzNFZHdJREFRQUJvNElCR0RDQ0FSUXdId1lEVlIwakJCZ3dGb0FVRmptcEdnV0p0dzh0c2pYdHdnbWF4UU9ESWo4d0VnWURWUjBnQkFzd0NUQUhCZ1VyVEIwQkN6Q0JyUVlEVlIwZkJJR2xNSUdpTUlHZm9JR2NvSUdaaG9HV2FIUjBjSE02THk5allYTnZaMlZwYzNacGJDNXpiMmRsYVM1cGRDOWxhbUpqWVM5d2RXSnNhV04zWldJdmQyVmlaR2x6ZEM5alpYSjBaR2x6ZEQ5amJXUTlZM0pzSm1semMzVmxjajFEVGlVelJFTkJLMDFwYm1semRHVnlieXRrWld4c1lTdFRZV3gxZEdVclZHVnpkQ1V5UTA4bE0wUk5hVzVwYzNSbGNtOHJaR1ZzYkdFclUyRnNkWFJsSlRKRFF5VXpSRWxVTUIwR0ExVWREZ1FXQkJUckJQbmFvVXFxaFdJa3dNZy8zMHRJdGx6Uk1UQU9CZ05WSFE4QkFmOEVCQU1DQmtBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFGQklqUkp5bGVPOFkxOWhVUHR4bzhEOWNwVkhzcGpxa3FESmhJT28rUjJJdEp5VzlDOENqMGc2eG1LRytESjZxQ2c5MWJnZ21jRGVCYWxlWGlzOC9xbGZaZTV3MDNBcmpnaGRQMTBnUEszVDZ6ZENFTWU2a2VGSUJxdkFYVlJRN3ZjbnJrYUJtTW9kcFhvVDJJbHVNTzZCZGFkRkVtcVU1a1J2QmFhLzRyRkIwL3RWTy9DZXBYMkpRMURWSXdtbEJIRlZFamNWYUNIdDFLQ1U5ZExFSmM5OGRnNUZFblR5WlJZM3NaeXNSb0JxR3c5dE1mTit1SUduWDZucHViQ21iTEZ4cTYwWE9VcWVocnNNdlR5aWh4V044dU5DNTM1S0tBbXFhWUtEdHYxTkhPV05pbEZZQW5jMUV4Ymt0SUZwbXpTeWlFNHI2Y2I5RXZQUHNjNVo1Z3FuOTVFUHRqVEl6OXdQczNXSjQ4UGl6YmdpSzd3Mmc0eFNKWTRwUjVVVlcrR2Uwbk9iZE1ZbytERnQ4ek5yMi8xaFpZQ0FwY2RwQzdBaXBOYS9weldmWERscDdMTGVIVDQ1cFF6NDNhZDBSWGxxUlpvc1BhZ1BHbit6M0k4aFc2L0d4RkVtLzJIYnVzV3ErQlBZa3VLL2xFZDAvTjFNd0lMTlRJV1hNcUNpcmowd1AyRmJSWmRJdHBOQm15OHhTbUViRlBESGlYMTc1Yk1RTGhESTVPMjNtYmF0MDJIUEpLTDZPTldhc0hKeEJYUEp5eXVSWERDWmljYU1HVUdqS0s2c1NQejcxSnBiSk5xN204VEYzL0dNdjllYllQSUI0azV6b2xXVHJUbFZ3Z3o4dnFZTEZTL3Nic0tvTFVIN2NISkVsR0VQS2x2dmhzMkdPazFyYklsaiJdLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODk4NDQ3OTgsImlhdCI6MTY4OTg0Mjk5OCwiaXNzIjoiaW50ZWdyaXR5OlMxIzExMTRXQVJEUFJPWFgiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJqdGkiOjU3MTU5LCJzdWIiOiJQUk9WQVgwMFgwMFgwMDBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X29yZ2FuaXphdGlvbl9pZCI6IjA4MCIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBFbWlsaWEtUm9tYWduYSIsImxvY2FsaXR5IjoiMTAzNDYiLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwZXJzb25faWQiOiJSU1NNUkEyMkEwMUEzOTlaXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJwYXRpZW50X2NvbnNlbnQiOnRydWUsInB1cnBvc2Vfb2ZfdXNlIjoiVFJFQVRNRU5UIiwicmVzb3VyY2VfaGw3X3R5cGUiOiInNjg2MDQtOF5eMi4xNi44NDAuMS4xMTM4ODMuNi4xJykiLCJhY3Rpb25faWQiOiJDUkVBVEUiLCJhdHRhY2htZW50X2hhc2giOiI0M2NlMTA0NjkyYzY3YmViYmJmNGJmYjEyMzIxM2I3MGFmN2Y0OGU4MzI5OGQ0MGU2NTc2NDVmYTJhYTk5ZDE5Iiwic3ViamVjdF9hcHBsaWNhdGlvbl9pZCI6IjR3YXJkUFJPIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZW5kb3IiOiJIU2lnbiIsInN1YmplY3RfYXBwbGljYXRpb25fdmVyc2lvbiI6IjEuMCJ9.izprvnueJUwOVo0khu5h3YtGVYRO1de6WlXg800UFjgVWq3jsQG_EgRtCLTvwx7eJo1CG9Eks4VUw6wCb4KEEM7b2XwC3G_7RdXORx7QxJ-0BX_OcUylM-AnNNFtInn09hRkEIE8wh78tVkHMNHfSxzXUV6zio-T2rVQF_LwfW8zwm1rYa4rhi-0ODwvGfeMnpiLbhnz0ZiiYeI31CPt0NvRxPAYq2YcCXIG7DT2gnPVKrhmXlG1YIun5OB9y3tO7N5awQ1ccCc2c9MoGpRDXwbunWvv-3sjBBDWKHnue5sUkt3FNnf4YUzYDA4hZC0pEZwY0-p3OiYa1WCmfIvtYQ
 
Ho confrontato i token con quelli presenti su altre issue github usando https://jwt.io/. Inoltre ho visto che fornite un programma per generare token ma non è una soluzione valida usando l’ambiente .net, l’interoperabilità non è una cosa facile e preferiremmo rimanere in ambiente .net

VI chiedo un rapido riscontro
se vi occorrono altre informazioni sarò felice di collaborare
Grazie

**Comment by LucaRogledi** [comment]
Buonasera, 
Dopo aver analizzato i token che ci ha inviato, riguardo ai campi all'interno del Bearer abbiamo notato:
- mancanza del campo "sub". 
- il campo "jti" va inserito come stringa.
Potrebbe gentilmente rivedere questi campi seguendo la documentazione e riprovare la chiamata?

https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt

Grazie

**Comment by LucaRogledi** [comment]
Buongiorno,
Dopo l'analisi sembra che non stiate presentando il certificato di autenticazione a livello trasporto, è possibile verificare se state utilizzando il certificato ssl di auth come certificato client della connessione https?
Grazie

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri chiudiamo il presente ticket e la invitiamo a riaprirlo nel caso in cui avesse bisogno di ulteriore supporto. Grazie.
