### ISSUE TITLE
Bad Request 400 Received request is not conform to the required interoperability profile

### ISSUE THREAD

**Issue by fsemelograno** [ministero-salute/it-fse-support#454]
Buongiorno, stiamo provando la validazione LDO ma abbiamo qualche problema di conformità con le specifiche, perché otteniamo l'errore in oggetto.
Riporto di seguito il messaggio di errore con il govwai_id, e allego i relativi token utilizzati, per una vostra verifica.

grazie in anticipo per l'aiuto

{
   "type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
   "title":"InteroperabilityInvalidRequest",
   "status":400,
   "detail":"Received request is not conform to the required interoperability profile",
   "govway_id":"eac47759-2ae7-11ee-8674-005056ae54fa"
}
[JWT_SIGNATURE_TOKEN.txt](https://github.com/ministero-salute/it-fse-support/files/12161915/JWT_SIGNATURE_TOKEN.txt)
[AUTH_BEARER_TOKEN.txt](https://github.com/ministero-salute/it-fse-support/files/12161919/AUTH_BEARER_TOKEN.txt)

**Comment by LucaRogledi** [comment]
Buongiorno,
Da un'analisi approfondita risulta che all'interno del headers nella richiesta manca la keyword "Bearer" di fronte al jwt di Authorization. 
Per maggiori informazioni può fare riferimento al seguente link della [Documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#23-note-su-autenticazione-e-token-jwt).

**Comment by fsemelograno** [comment]
Abbiamo aggiunto la keyword Bearer... ci era sfuggita!

Grazie per il supporto.

Abbiamo ora un altro problema, ma apriremo un nuovo ticket dato che sembra un problema non collegato a questo.
