### ISSUE TITLE
Ospedali Civili Brescia - Ambiente Test - Errore in fase di estrazione del CDA

### ISSUE THREAD

**Issue by bocci66** [ministero-salute/it-fse-support#455]
traceID: 4985ed80753f1108

Non riusciamo a capire il motivo dell'errore, che si verifica aggiungendo una diagnosi codificata ICD9CM nella sezione 'Condizioni_paziente_diagnosi_dimissione'

Saluti

**Comment by vigliottim** [comment]
Buongiorno, potrebbe cortesemente allegare il CDA in oggetto? Grazie.

**Comment by bocci66** [comment]
[95403090623000111V4.txt](https://github.com/ministero-salute/it-fse-support/files/12172015/95403090623000111V4.txt)

**Comment by bocci66** [comment]
CDA allegato, saluti

**Comment by vigliottim** [comment]
Buongiorno, per favore potrebbe allegare il file PDF che sta usando per la validazione? Grazie.

**Comment by bocci66** [comment]
[HBS Test prova.pdf](https://github.com/ministero-salute/it-fse-support/files/12183052/HBS.Test.prova.pdf)

**Comment by bocci66** [comment]
Ecco il pdf richiesto, saluti

**Comment by LucaRogledi** [comment]
Buonasera,
potrebbe gentilmente verificare che il pdf che ha allegato sia lo stesso usato in validazione?
Abbiamo notato che il pdf allegato nel commento è "HBS.Test.prova.pdf" mentre quello usato in validazione "CDA_OK.pdf".
Grazie.

**Comment by bocci66** [comment]
Buonasera,
confermo che trattasi del medesimo file, nominato semplicemente in maniera differente dopo download da ambiente dell'Ente.

**Comment by bocci66** [comment]
Buongiorno, 
dal 27/07 non ho più ricevuto alcuna vs risposta : sono a sollecitare la issue, grazie

**Comment by LucaRogledi** [comment]
Buongiorno,
Il pdf ricevuto dal gateway risulta malformato dando problemi di estrazione del CDA, suggeriamo di riprovare utilizzando un nuovo pdf valido.
Rimaniamo a disposizione nel caso in cui fosse necessario ulteriore supporto. 
Grazie

**Comment by bocci66** [comment]
Buongiorno,
non mi risulta ciò che mi sta dicendo, allego screenshot del medesimo file aperto con Acrobat Reader senza alcun problema.
Potrebbe dettagliarmi cosa non vi torna ?

**Comment by bocci66** [comment]
<img width="800" alt="HBS" src="https://github.com/ministero-salute/it-fse-support/assets/135051565/71632def-496c-4f3a-be0b-e2883d62073b">

**Comment by LucaRogledi** [comment]
Buonasera,
abbiamo verificato effettivamente che il pdf allegato nei messaggi precedenti in questo thread si apre correttamente e anche che passa la validazione del Gateway.
Sembrerebbe però che il pdf ricevuto effettivamente dal gateway sia diverso, e che abbia generato problemi durante l'estrazione del CDA.
Potrebbe ritentare la validazione con il pdf che ha allegato in precedenza e farci sapere se il problema persiste?
Grazie.

**Comment by bocci66** [comment]
Buongiorno,
siamo riusciti ad inviare con successo la LDO incriminata, modificando all'interno della request il dato 'Content-Disposition: filename' settandolo come il nome del file xml iniettato nel pdf.
Questo non era necessario quando abbiamo effettuato i test per ottenere l'accreditamento, e continua a non esserlo in assenza di una diagnosi di dimissione ICD9CM.
Vi risulta quanto qui asserito ?
Riporto queste osservazioni a supporto di Fornitori che possano riscontrare il medesimo problema.

**Comment by Ser-ena** [comment]
Buongiorno,
il dato 'Content-Disposition: filename' dovrebbe essere valorizzato con il nome del pdf, e non con quello del cda in esso contenuto.

Dalle verifiche è emerso che il file "HBS Test prova.pdf", anche in presenza della sezione "diagnosi di dimissione",supera correttamente la fase di estrazione e in fase di validazione riceve 403 "Il codice fiscale nel campo person_id non è corretto".

Rimaniamo a disposizione per eventuali richieste di supporto ulteriori.

**Comment by IStacchiotti** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto, grazie.
