### ISSUE TITLE
Chiarimento su Gateway ed elemento Association

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#456]
Buongiorno,
nell'integrazione con il gateway FSE 2.0 non sono riuscita a capire come viene gestito l'elemento Association previsto dall'Affinity Domain Italia per indicare le relazioni tra documenti.

In particolare facendo riferimento alla Tabella 2.25-1 dell'Affinity Domain Italia Vers. 2.4.1
"Value set per il metadato XDSDocumentEntry.Slot per le Association"
non mi è chiaro come viene realizzato il tipo di associazione urn:ihe:iti:2007:AssociationType:APND per l'aggiunta (addendum).

Potete darmi qualche indicazione riguardo a questo scenario?
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno @ponsilva,
Le association a cui fa riferimento non sono a cura dei Sistemi Produttori che, pertanto, non occorre si preoccupino della loro gestione.
Rimaniamo a disposizione in caso fosse necessario altro suppporto, grazie

**Comment by ponsilva** [comment]
Grazie per la precisazione.
Verifico internamente se sono necessari ulteriori approfondimenti
