### ISSUE TITLE
Richiesta supporto - Errore 405 Not Allowed 

### ISSUE THREAD

**Issue by DedaloSoftware** [ministero-salute/it-fse-support#457]
Buongiorno, 

siamo in fase di validazione e stiamo procedendo a completare i Case Tests sia OK che KO.
Da ieri riceviamo questo errore: 

HTTP/1.1 405 Not Allowed
Server: nginx/1.18.0 (Ubuntu)
Date: Thu, 27 Jul 2023 08:26:29 GMT
Content-Type: text/html
Content-Length: 166
Connection: keep-alive

<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

Ecco la Nostra request:

POST /fse-middleware/gateway/v1/documents/validation HTTP/1.1
Host: fse-services-test.regione.lazio.it
Accept: application/json
Authorization: Bearer eyJ4NWMiOlsiTUlJRnFEQ0NCQkNnQXdJQkFnSVVHV3V4TG8rV1F4T3V1NytiVkRwWWZWeFloaW93RFFZSktvWklodmNOQVFFTEJRQXdSakVoTUI4R0ExVUVBd3dZVEVGYVNVOURjbVZoSUZKdmIzUWdRMEVnTFNCRFQweE1NUlF3RWdZRFZRUUtEQXREYjJ4c1lYVmtieUJEUVRFTE1Ba0dBMVVFQmhNQ1NWUXdIaGNOTWpNd016RTFNakkxTXpVeldoY05NalV3TXpFME1qSTFNelV5V2pDQjFERTZNRGdHQTFVRURRd3hRMlZ5ZEdsbWFXTmhkRzhnUm1seWJXRWdMU0JGYm5SbElERXlNREl3TUNoVVJWTlVLU0F0SUVGd2NGUmxjM1F3TVRFb01DWUdBMVVFQXd3ZlUwbEhNVEl3TWpBd1h6QXdPVGczTmpVME16SXhMVUZ3Y0ZSbGMzUXdNVEVvTUNZR0ExVUVDd3dmUm1GelkybGpiMnh2SUZOaGJtbDBZWEpwYnlCRmJHVjBkSEp2Ym1samJ6RVdNQlFHQTFVRUNnd05VbVZuYVc5dVpTQk1ZWHBwYnpFTk1Bc0dBMVVFQnd3RVVtOXRZVEVPTUF3R0ExVUVDQXdGVEdGNmFXOHhDekFKQmdOVkJBWVRBa2xVTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUE1TitqYXhFV3gyUWJQQmxqb3VtOWhPTkhUakR5cktXc2JrQ09aRzVzcS9MM3pycXNvMVlFSGxPSnI0L1BwMEZqVTlYbit3Q0tDaTEvV2ZxSkJYaFhGU1JtM3dBM1JCRU5jL0xCVUh0bGhVK0U1N2JoVkZHN2FXUFpGbW5xbzg0cDJJU3MwTjhnQ2k4YWVZT0t5T2tqbmRIaDlpVWRmR0dHQnViL2VscTlZZG9pbVFDRWl0Tmp3YVYrVDFKYUpnamhwbk5OV2x6ZHphTHBMT2Vlc3dodHlHSVBWbXkxSzNOZGVNbDdhZGpHb1Z1dDAvV3EvbWV4U1FUMmpReWVYdWRpK0ZReStmT0VXSmxDeDFSd3F5SnRIbEl3MVJwZGFNbjJqdTc3QjlaVDJwL29ONmZzY05hdytncGYzd003TGtrTkxJUmxRSjNld1JZNXV0dDlBdGE4Uy9QcGUxQS9hSnNDL2t5cEpPNFVDUkpYcjdOMER3bFRtMkZqcW5WTDN5aW5qR3dPZSsrcnBsazJmLzhVTU5BVTJZSjh6MENoaVp5N2pWdmNWL1NEVnhteEJsKzFxMG8zMFZla0h1eS8vRzk1N1FBNCtzQnU4NzB1QVRXVXl6bDNHaEZuSTkwZ2ZKWUI0cFpmZHErTWY1bGFHdjQzcTN4UjF4TUZHWGdlSW0xUWVIcDUxS3lCZ1ZoM1lhNkhCcnRQeUNDVEZxejc2OEh5dTBNaTlLSERFVUw4L3hkazhmd3N4dnJRKzVDUmtpc2VvcWROUlVWT0Z2amg4WlhaTVRkZTdZZ2FJRFVpY3VQdXB6UjNHLzBYSlQxTlErc2xLVk9WSWhRV09HV3UzMzIyMTM2SmlvaS8wZzRpWkdHNVpCWEhJOG85L0lwOWdiYmoydHdJWU9JUXExMENBd0VBQWFOL01IMHdEQVlEVlIwVEFRSC9CQUl3QURBZkJnTlZIU01FR0RBV2dCUlMvdUZLYkdQcldiTUlmOVNPbXA3T2Z5eVdZakFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQWdZSUt3WUJCUVVIQXdRd0hRWURWUjBPQkJZRUZOMWtLN1U5emlKZ0tQcDJ2TzA5ajZudkdDVnFNQTRHQTFVZER3RUIvd1FFQXdJRjREQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FZRUFtVUVkNmVmT1YwM2pIZTNtem5wNkZ2OEdYOW51WWRRSThPYU9iMFBnZzJFRUsxOFhYTC9mRmNaSGlPN091NjMxekZ5NmVxRlZRNXYrYjZTc2RkQWFBUzRVelZtNURDcFdpaXU0c1lWeEZGenFqK1ZoZjc3T3JnTks0WURKK2ZhdTZwVjVoTmszRG54UmlYT0pJSUI4V3hFQWFvTzRmOHNzZlZ3b0FFOXpuYkMvODJHK2F6d0ZEKzg3OThiQWd6cm8zU3lVSk1XWFlIUFBZOWVFZ3NpdjJOVExCaTlFTG92K1RwQnhhOWZHK2tzaTJoVlFLb1ZZY2VlaHd4VUVkSmRYOVprc2cwQ0FGNnBJWmJMRFE2SmcwK2JMUzZkcStLMVlreWxqUkF6bFU2RzRuUkxGQk9rbi8vdEJzV2dIS3R0MlN1Z1VCR0lMY0NXRkRwckZCTlpvZGVDZ0FIenYyMlEveVNxbjUrOTdjQkdOV25nQXB2RStDUWFHcUVJTzdsdDFaTVc2STc0VVBTQUU3VS83L1VXNnJ6RkRoV1E2Unc2WEt6VGIwRDlNNTQwSUFhV2VwTVd6T21YV0NncFBEaUx2MDNvL3FzbVdBOWRpVTRwNVhKbUpsc0lKU0tGcGVjYnBlTTVEUy9zeHAySVZuN0RsN21HY3ZEQkQydktvRU5iMyJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJHVFdHV1k4MkI0Mkc5MjBNXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL2ZzZS1zZXJ2aWNlcy10ZXN0LnJlZ2lvbmUubGF6aW8uaXQvZnNlLW1pZGRsZXdhcmUvZ2F0ZXdheS92MS8iLCJpc3MiOiJhdXRoOlNJRzEyMDIwMF8wMDk4NzY1NDMyMS1BcHBUZXN0MDEiLCJleHAiOjE2OTA1MzI3MDksImlhdCI6MTY5MDQ0NjMwOSwianRpIjoiMTIzNCJ9.VVk-4477YnTgBaIW5QktmYjjYsK9GokQZir258GpaJA6NrYyX3VPNUO538D-grpBQZUQl50aVnzevYcz5JKSCa2xRy1asV5W0HnSz7fbT2vdHyCgWheEilBdSZve1qlsSMkddTz_9IgVdNXV530kDRSEpFsWnQ2WBdcbGQxu7Sv7Cl8QfXLkS4jyBATXD3JEJO2Dm0cBtM7SSFofzd_pUh-o1HPfHV9rzKTA3lQKx4ylaDqIBolyArhZJo2EynCb77Piy-MWZA9vnaXE7eoWfg3Sf7shCc1-VEt6CUCbEIOtTBVEt179_ApCYPqFpI_9sKsDmKPAWIsZMT35klXTfw_v-jLnXuhJPRtKl7MZuND37UPI8hIizk9Oo8UAS54wmjSwQitPHq5I0rtBIpABXWyWsDIPqxJBclnbWLdpIyDHmkSDgM_YWyOPqXGfNrTCd0jyYdOoRBngxFHdNVPmPnFQiJMr5-WyAN-VLhVKKY9sD5kmlsnJ1Q_pAgcQrWQeykEHThalxjQJ3V-l3cu0Q51DgKjnsG1S1Fcq1u7xrrpeftK_SbxS4JE0HGprs4_tJHoH_9c8NggnFeDK3p-lt6fX4toUvBtikgTiRR9POTyFCyzGEE-GFXndcX5DbIJltub3xsKY6RKR_a_s9Lf2wq1EPqYzkOai2qZ7Lb4Depk
FSE-JWT-Signature: eyJ4NWMiOlsiTUlJRnFEQ0NCQkNnQXdJQkFnSVVHV3V4TG8rV1F4T3V1NytiVkRwWWZWeFloaW93RFFZSktvWklodmNOQVFFTEJRQXdSakVoTUI4R0ExVUVBd3dZVEVGYVNVOURjbVZoSUZKdmIzUWdRMEVnTFNCRFQweE1NUlF3RWdZRFZRUUtEQXREYjJ4c1lYVmtieUJEUVRFTE1Ba0dBMVVFQmhNQ1NWUXdIaGNOTWpNd016RTFNakkxTXpVeldoY05NalV3TXpFME1qSTFNelV5V2pDQjFERTZNRGdHQTFVRURRd3hRMlZ5ZEdsbWFXTmhkRzhnUm1seWJXRWdMU0JGYm5SbElERXlNREl3TUNoVVJWTlVLU0F0SUVGd2NGUmxjM1F3TVRFb01DWUdBMVVFQXd3ZlUwbEhNVEl3TWpBd1h6QXdPVGczTmpVME16SXhMVUZ3Y0ZSbGMzUXdNVEVvTUNZR0ExVUVDd3dmUm1GelkybGpiMnh2SUZOaGJtbDBZWEpwYnlCRmJHVjBkSEp2Ym1samJ6RVdNQlFHQTFVRUNnd05VbVZuYVc5dVpTQk1ZWHBwYnpFTk1Bc0dBMVVFQnd3RVVtOXRZVEVPTUF3R0ExVUVDQXdGVEdGNmFXOHhDekFKQmdOVkJBWVRBa2xVTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUE1TitqYXhFV3gyUWJQQmxqb3VtOWhPTkhUakR5cktXc2JrQ09aRzVzcS9MM3pycXNvMVlFSGxPSnI0L1BwMEZqVTlYbit3Q0tDaTEvV2ZxSkJYaFhGU1JtM3dBM1JCRU5jL0xCVUh0bGhVK0U1N2JoVkZHN2FXUFpGbW5xbzg0cDJJU3MwTjhnQ2k4YWVZT0t5T2tqbmRIaDlpVWRmR0dHQnViL2VscTlZZG9pbVFDRWl0Tmp3YVYrVDFKYUpnamhwbk5OV2x6ZHphTHBMT2Vlc3dodHlHSVBWbXkxSzNOZGVNbDdhZGpHb1Z1dDAvV3EvbWV4U1FUMmpReWVYdWRpK0ZReStmT0VXSmxDeDFSd3F5SnRIbEl3MVJwZGFNbjJqdTc3QjlaVDJwL29ONmZzY05hdytncGYzd003TGtrTkxJUmxRSjNld1JZNXV0dDlBdGE4Uy9QcGUxQS9hSnNDL2t5cEpPNFVDUkpYcjdOMER3bFRtMkZqcW5WTDN5aW5qR3dPZSsrcnBsazJmLzhVTU5BVTJZSjh6MENoaVp5N2pWdmNWL1NEVnhteEJsKzFxMG8zMFZla0h1eS8vRzk1N1FBNCtzQnU4NzB1QVRXVXl6bDNHaEZuSTkwZ2ZKWUI0cFpmZHErTWY1bGFHdjQzcTN4UjF4TUZHWGdlSW0xUWVIcDUxS3lCZ1ZoM1lhNkhCcnRQeUNDVEZxejc2OEh5dTBNaTlLSERFVUw4L3hkazhmd3N4dnJRKzVDUmtpc2VvcWROUlVWT0Z2amg4WlhaTVRkZTdZZ2FJRFVpY3VQdXB6UjNHLzBYSlQxTlErc2xLVk9WSWhRV09HV3UzMzIyMTM2SmlvaS8wZzRpWkdHNVpCWEhJOG85L0lwOWdiYmoydHdJWU9JUXExMENBd0VBQWFOL01IMHdEQVlEVlIwVEFRSC9CQUl3QURBZkJnTlZIU01FR0RBV2dCUlMvdUZLYkdQcldiTUlmOVNPbXA3T2Z5eVdZakFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQWdZSUt3WUJCUVVIQXdRd0hRWURWUjBPQkJZRUZOMWtLN1U5emlKZ0tQcDJ2TzA5ajZudkdDVnFNQTRHQTFVZER3RUIvd1FFQXdJRjREQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FZRUFtVUVkNmVmT1YwM2pIZTNtem5wNkZ2OEdYOW51WWRRSThPYU9iMFBnZzJFRUsxOFhYTC9mRmNaSGlPN091NjMxekZ5NmVxRlZRNXYrYjZTc2RkQWFBUzRVelZtNURDcFdpaXU0c1lWeEZGenFqK1ZoZjc3T3JnTks0WURKK2ZhdTZwVjVoTmszRG54UmlYT0pJSUI4V3hFQWFvTzRmOHNzZlZ3b0FFOXpuYkMvODJHK2F6d0ZEKzg3OThiQWd6cm8zU3lVSk1XWFlIUFBZOWVFZ3NpdjJOVExCaTlFTG92K1RwQnhhOWZHK2tzaTJoVlFLb1ZZY2VlaHd4VUVkSmRYOVprc2cwQ0FGNnBJWmJMRFE2SmcwK2JMUzZkcStLMVlreWxqUkF6bFU2RzRuUkxGQk9rbi8vdEJzV2dIS3R0MlN1Z1VCR0lMY0NXRkRwckZCTlpvZGVDZ0FIenYyMlEveVNxbjUrOTdjQkdOV25nQXB2RStDUWFHcUVJTzdsdDFaTVc2STc0VVBTQUU3VS83L1VXNnJ6RkRoV1E2Unc2WEt6VGIwRDlNNTQwSUFhV2VwTVd6T21YV0NncFBEaUx2MDNvL3FzbVdBOWRpVTRwNVhKbUpsc0lKU0tGcGVjYnBlTTVEUy9zeHAySVZuN0RsN21HY3ZEQkQydktvRU5iMyJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJHVFdHV1k4MkI0Mkc5MjBNXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImlzcyI6ImludGVncml0eTpTSUcxMjAyMDBfMDA5ODc2NTQzMjEtQXBwVGVzdDAxIiwibG9jYWxpdHkiOiIxMTIxMjM0NTYiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlcnNpb24iOiIxLjAiLCJzdWJqZWN0X29yZ2FuaXphdGlvbiI6IlJlZ2lvbmUgTGF6aW8iLCJzdWJqZWN0X29yZ2FuaXphdGlvbl9pZCI6IjEyMCIsImF1ZCI6Imh0dHBzOi8vZnNlLXNlcnZpY2VzLXRlc3QucmVnaW9uZS5sYXppby5pdC9mc2UtbWlkZGxld2FyZS9nYXRld2F5L3YxLyIsInBhdGllbnRfY29uc2VudCI6dHJ1ZSwiYWN0aW9uX2lkIjoiQ1JFQVRFIiwicmVzb3VyY2VfaGw3X3R5cGUiOiIoJzExNTAyLTJeXjIuMTYuODQwLjEuMTEzODgzLjYuMScpIiwic3ViamVjdF9hcHBsaWNhdGlvbl9pZCI6IkhTIExBQk8iLCJleHAiOjE2OTA1MzI3MDksInN1YmplY3RfYXBwbGljYXRpb25fdmVuZG9yIjoiSFMgSU5GT1JNQVRJQ0EiLCJpYXQiOjE2OTA0NDYzMDksImp0aSI6IjEyMzQiLCJwZXJzb25faWQiOiJHVFdHV1k4MkI0Mkc5MjBNXl5eJmFtcDsyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImYW1wO0lTTyJ9.czUVFRGPDG0g6Icw8F_7FNibT-GQcFq1G2xsSAcoL0MUaOIYr-8yUX-jdy8Q6L55vry4WWxiIrSQskAsTRgpXFsNkjvhQZB_mZGxRQox6T9ItzMUzB37xTyZ_-mpcAjwZACP26YbHrm8R6K39xIEoCCK4IGiYz6-x6c0PzAulP8z1KfS8bAoqdYoTrkMnGIdrOUKD617cCq4ilskvWPZMAa1Xd1Mi-SAj5HDLSbfmdLtU55gu4vXW_avnHeauJVhi4AsdnZ3ZapBItJ5Xecfyxq3v0lKOfbapLZZ5mn5ZXUDNUh1KMVYEy5Ww1BeMCVfG3XOa7VDLSr8_QKnNr1t-RtmNBfZygR7uOU0tEE7i9450q2NHWiPWnVorkHFjcLPUvB_958OmWTfqdIf5Gxh1SfMWs7v0ykKxA1xzB7F_AJSCj-vsu08AsJdXTdinfElW0rpFD9Xq538m_4XKX4JOkQ41evJLCscI960tJOVqCFwWVJPpmnMJjuU9NIYStmN_N05ZUA9wsKi88h4c8upLRu2XAS-rsPQ_AdBoryx_JciCB_5YmIrRXJGLEi7OhHqZ6hxw49aUn1FjMZR3wAJv9qfrbMPS-rP-IY3O75P0YNkC_BVnozAnSoTq59w_2keP000tinbZYNHnVB6tmsgiDAZREF45Yz-1h77lCN-ztY
Content-Length: 29033
Content-Type: multipart/form-data; boundary=------------------------d9620cf7bf3d5db8

{"healthDataFormat":"CDA","activity":"VALIDATION","mode":"ATTACHMENT"}

**Comment by IStacchiotti** [comment]
Buongiorno, dalle verifiche è emerso che in chiamata state passando per il middleware della regione Lazio. Vi invitiamo a verificare con loro, dal momento che la risposta restituita dal sistema sembra riconducibile proprio a questo layer intermedio.
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
