### ISSUE TITLE
Richiesta supporto su test validazione LAB - MCA SAS

### ISSUE THREAD

**Issue by Mcataranto** [ministero-salute/it-fse-support#458]
Abbiamo avuto un ritorno non ok sui test 2 e 4 che non riusciamo a spiegarci.

L'errore segnalato (003) in entrambi i casi viene segnalato come da testo seguente:

 **"error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='003' attribute='code' actual = '' expected = 'completed active aborted'>ClinicalDocument/component/structuredBody/component/section/component/section/entry/act/statusCode</error>"**

La parte del CDA interessato è allegata di seguito

[StructureBody.txt](https://github.com/ministero-salute/it-fse-support/files/12184487/StructureBody.txt)

rileggendo le specifiche HL7 non riusciamo a notare incoerenze
Grazie...

**Comment by LucaRogledi** [comment]
Buongiorno,
L'errore è dovuto alla mancanza di qualche tag all'interno della struttura xml.
Specifichiamo che bisogna inserire tutti gli elementi che, anche se sono opzionali da guida, per il nostro caso d’uso sono necessari per completezza di informazione. Bisogna fare riferimento all’excel fornito con le giuste valorizzazioni dei campi da inserire. 
La rimandiamo al link di [Documentazione](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/5-Referto%20di%20Medicina%20di%20Laboratorio/CDA2_Referto%20Medicina%20di%20Laboratorio_OK.xlsx) e in particolare al documento "CDA2_Referto Medicina di Laboratorio_OK.xlsx", sheet "LAB - Caso di Test 2" e "LAB - Caso di Test 4", in cui sono riportate le indicazioni per la compilazione del CDA di LAB in riferimento al particolare caso di test.
Specifichiamo che nella colonna "Obbligatorietà da IG" è riportata l'obbligatorietà secondo le specifiche nazionali, mentre nella colonna "Obbligatorietà per Test case 2" e "Obbligatorietà per Test case 4", in rosa, è riportata l'obbligatorietà per lo specifico caso di test.
Nel caso particolare in cui i dati non siano disponibili a sistema oppure nel caso in cui non si possa completare il test case correttamente, è possibile indicare NO nell’apposita colonna "Applicabilità", avendo cura di giustificarlo opportunamente nella colonna "razionale di applicabilità".
Le segnaliamo infine che è disponibile a questo link il tool "gwt-certifier", che consente di riprodurre in locale le verifiche dei test case di validazione OK richiesti durante la fase di accreditamento.
Rimaniamo a disposizione per ulteriore supporto. 
Grazie.

**Comment by Mcataranto** [comment]
Grazie per le indicazioni.
Purtroppo dove viene segnalato il gwt-certifier non c'è il link per
accedere...

Grazie ancora..

B.Pisicchio
MCA SAS

Il giorno ven 28 lug 2023 alle ore 11:22 LucaRogledi <
***@***.***> ha scritto:

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Di seguito il link per scaricare offline tutti i tool disponibili, tra cui il gtw-certifier. 

[Tools](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main)

![tools](https://github.com/ministero-salute/it-fse-support/assets/139234602/af1fce1e-191f-4deb-884c-38ef73304dd3)

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
