### ISSUE TITLE
Mancato accreditamento per Wrong Claims

### ISSUE THREAD

**Issue by DedaloSoftware** [ministero-salute/it-fse-support#459]
Salve,

abbiamo fatto delle verifiche dopo aver ricevuto la mail di segnalazione di mancato accreditamento per un test case specifico ( che abbiamo corretto date le indicazioni sull'errore) e dei wrong claims che però non riusciamo a risolvere.

Questo perché l'unica incongruenza che abbiamo trovato è che nel json il nome  e' in minuscolo mentre nella richiesta e nel token è in maiuscolo. Abbiamo controllato tutte le request e le response, verificando quelle immesse nel file excel report-checklist. L'unica differenza è quella. C'è forse una verifica case-sensitive? 

Rimaniamo in attesa di chiarimenti
Qui di seguito la traccia dell'errore:
{
  "id" : 2,
  "error" : "WRONG_CLAIMS_ON_LOG",
  "description" : "Claims(appId,appVersion,appVendor) della chiamata al gtw differenti da quelli dichiarati nel data.json"
},

**Comment by IStacchiotti** [comment]
Buon pomeriggio,
le confermiamo che il controllo in questione è case sensitive. Pertanto La invitiamo ad aprire una nuova pull request con le dovute correzioni. Grazie

**Comment by DedaloSoftware** [comment]
Perfetto
