### ISSUE TITLE
Una LDO senza la sezione "Condizioni_paziente_diagnosi_dimissione" passa la validazione

### ISSUE THREAD

**Issue by g-polverini** [ministero-salute/it-fse-support#46]
Il caso di test 11 per la LDO (VALIDAZIONE_CDA2_LDO_CT11_KO, ID 69), che consiste nel mandare un documento senza specificare ClinicalDocument/component/structuredBody/component /section[@ID="Condizioni_paziente_diagnosi_dimissione"], dà un risultato inatteso, sia offline che online.
Inserisco i dati di risposta inviando al gateway
```
Status Code: 200
Response:
{
  "traceID": "2c57a0e2cf961071",
  "spanID": "2c57a0e2cf961071",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.96788c5d4aeb30083edca9e9bb2fc3afc931eaee1a320bd957464e84d8164b0f.e6c71a6d9a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```

**Comment by LeonardoAlcaro** [comment]
Buon pomeriggio,
grazie per la segnalazione, si potrebbe avere il file CDA2 utilizzato per la validazione, effettivamente il controllo sulla section Condizioni_paziente_diagnosi_dimissione e' previsto da schematron e dovrebbe riportare l'errore relativo.
Riporto per chiarezza la parte di schematron relativa:

			<assert test="count(hl7:component/hl7:section/hl7:code[@code='11535-2'][@codeSystem='2.16.840.1.113883.6.1'])=1"
			>ERRORE-b5| Sezione Condizioni del paziente e diagnosi alla dimissione: la sezione DEVE essere presente</assert>

**Comment by g-polverini** [comment]
Errore mio, mi scuso per la segnalazione: procedo sempre con un doppio controllo, prima con un CDA esatto, poi modificandolo eliminando o modificando i dati a seconda dei test, ma per errore ho fatto:
```
// C#
var components = (doc.component.Item as POCD_MT000040UV02StructuredBody).component;
components = components.Where(c => c.section.code.code != "11535-2").ToArray();
```
senza quindi riassegnare l'array al nodo parent... quindi il documento non veniva modificato.
Aggiustato il "decurtamento" dell'array, ora i test passano.
