### ISSUE TITLE
File con più allegati oltre al CDA

### ISSUE THREAD

**Issue by michele01b** [ministero-salute/it-fse-support#460]
Buonasera,
è possibile produrre e validare file con più allegati?
I documenti presenterebbero vari files allegati tra cui il CDA da validare.
Grazie

**Comment by Ser-ena** [comment]
Buongiorno,
è possibile produrre pdf con molteplici allegati; Tuttiavia è necessario sempre che il cda che si intende validare si chiami cda.xml;
Saluti

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
