### ISSUE TITLE
Errore validazione LDO e VPS "Error while searching signature for file with name" 

### ISSUE THREAD

**Issue by stellariAbstract** [ministero-salute/it-fse-support#461]
Buongiorno,
chiedo di riaprire la issue #446  in quanto il problema "Error while searching signature for file with name" si ripresenta nuovamente ogni volta che cerco di validare un documento (in questo caso un VPS).

Sarebbe possibile sapere quali siano le cause scatenanti?

Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, grazie per il riscontro. Per evitare duplicati, procediamo alla chiusura del presente e alla riapertura del ticket originale, il #466. Riceverà un riscontro appena possibile, grazie
