### ISSUE TITLE
procedura di accreditamento

### ISSUE THREAD

**Issue by ftallaro** [ministero-salute/it-fse-support#462]
Buongiorno,

volevo capire come procedere per la certificazione. Io dovrò certificarmi per il Referto di Medicina di Laboratorio, Referto di Radiologia, Referto di Specialistica Ambulatoriale (nota di consulto), Lettera di Dimissione Ospedaliera sia per la validazione che per la pubblicazione.

Volevo capire se fare la richiesta completa nel sito https://ec.europa.eu/eusurvey/runner/FSE-raccolta-id-applicativo e man mano inviare i vari file per i controlli dovuti oppure creare richiesta diverse per ogni tipologia che viene completata. Ad esempio, prima richiedo Radiologia, poi Laboratorio, etc.

Vi ringrazio.

**Comment by IStacchiotti** [comment]
Buongiorno @ftllaro,
Per velocizzare il processo, le suggeriamo di:
1. censire fin da subito tutti i cda nell'Eu Survey indicando entrambi i servizi (validazione e pubblicazione),
2. sottomettere una unica checklist per tutte le tipologie di cda, comprensiva del set completo di casi di test gestiti dall'applicativo. Specifichiamo inoltre che al momento verranno valutati i soli casi di test riferiti a validazione, essendo la parte di pubblicazione momentaneamente sospesa fino a nuova comunicazione.
Rimaniamo a disposizione per ulteriori richieste di supporto.

**Comment by ftallaro** [comment]
Ma la richiesta nell'Eu Survey la posso fare oggi e man mano che sono pronti inviare i vari casi nell pull request?

**Comment by IStacchiotti** [comment]
Nell'eu survey le suggeriamo di censire sin da subito tutti i servizi e cda gestiti dal suo applicativo.
Per il caricamento dei file nelle pull request può procedere con entrambe le modalità: inviarli mano a mano oppure inviarli tutti insieme una volta pronti. Noi le consigliamo, per velocizzare il processo, di seguire la seconda strategia. Questo per evitarle di dover ripetere i test per i cda per i quali avrà già conseguito l'esito finale di validazione: ciò viene richiesto infatti nel momento in cui si aggiunge una nuova tipologia documentale, come riportato a questo [link](https://github.com/ministero-salute/it-fse-accreditamento#nuova-tipologia-documentale-per-applicativo-gi%C3%A0-presente-nella-lista-dei-software-convalidati).

Un ultimo consiglio per avere dei riscontri "in itinere": le segnaliamo che è disponibile a questo [link ](https://github.com/ministero-salute/it-fse-gtw-tools)il tool "gwt-certifier", che consente di riprodurre in locale le verifiche dei soli test case di validazione OK richiesti durante la fase di accreditamento.

**Comment by ftallaro** [comment]
Si ho già provato ad utilizzare il "gwt-certifier" e mi sono accorto che anche se l'invio di test va a buon fine segnala ulteriori possibili errori.

Abbiamo intenzione di gestire tutti i KO da codice, quindi non invieremo nessun test di KO segnalando nel report-list.xls che saranno bloccanti e verranno segnalati all'utente finale, anzi se mi può indicare bene come li devo compilare la ringrazio. Va bene?

Nella richiesta all'eu survey che farò oggi i campi:

-) Common name nel certificato di accesso: devo mettere il nome del certificato PEM relativo all'autenticazione ricevuto, giusto?
-) Data di inizio del test di accreditamento e Data prevista di fine del test di accreditamento che influenza hanno? Cioè se metto inizio oggi e fine a novembre (volutamente molto avanti nel tempo per essere sicuro di aver completato tutto) va bene?

Grazie.

**Comment by IStacchiotti** [comment]
Specifichiamo che per l'accreditamento vengono svolti dei test specifici (con controlli più stringenti rispetto a quelli previsti in validazione), pertanto non è detto che ad un esito positivo da parte del Gateway corrisponderà un esito positivo in fase di accreditamento ed è per questo che il gwt-certifier segnala degli errori in più.

In merito alle modalità di compilazione, nel caso in cui alcuni use case non siano replicabili è necessario indicarne sulla checklist l'applicabilità a NO e valorizzare RAZIONALE DI APPLICABILITA' con le motivazioni per cui il test non è applicabile; in generale si suggerisce di seguire la guida riportata nella scheda "Istruzioni Compilazione" presente all'interno del file excel accreditamento-checklist_V8.1.3.xlsx.

E' corretto inserire nel common name il nome del certificato PEM di Authentication; relativamente alle date ricordiamo che la data di fine è una data prevista, mentre quella di inizio test indica il giorno in cui si inizia con il processo. Per ulteriori informazioni puo' far riferimento al documento presente al [link ](https://github.com/ministero-salute/it-fse-support/tree/main/doc/accreditamento).

**Comment by ftallaro** [comment]
ok grazie

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
