### ISSUE TITLE
Errore Validazione/pubblicazione - EffectiveTime value errato

### ISSUE THREAD

**Issue by GitHsinformatica** [ministero-salute/it-fse-support#463]
Salve, è la seconda volta che riceviamo un mancato accreditamento per il seguente errore:

[ {
  "id" : 4,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='007' attribute='value' expected = 'Valorizzare con data valida'>ClinicalDocument/component/structuredBody/component/section/component/section/entry/act/entryRelationship/organizer[classCode='CLUSTER']/component/organizer[classCode='BATTERY']/effectiveTime</error>"
} ]

Ma la data che inseriamo è corretta. 
Di seguito uno stralcio del nostro xml:

									<entryRelationship typeCode="COMP">
										<observation moodCode="EVN" classCode="OBS">
											<code code="11553-5" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Esame microscopico"/>
										    <statusCode code="completed"/>
											<effectiveTime value="20230630181000"/>
											<value xsi:type="ST">alcuni leucociti, bacilli gram negativi, cocchi gram positivi, carica batterica maggiore 100.000 UFC/mL</value>
											<methodCode code="0240" codeSystem="2.16.840.1.113883.5.84" codeSystemName="ObservationMethod" displayName="Antibiotic sensitivity, disk" />
										</observation>
									</entryRelationship>
									
									<entryRelationship typeCode="COMP">
										<organizer moodCode="EVN" classCode="CLUSTER">
											<statusCode code="completed"/>
											<effectiveTime value="20230630200101"/>
											<specimen typeCode="SPC">
...

	<component typeCode="COMP">
												<organizer moodCode="EVN" classCode="BATTERY">
													<code code="29576-6" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Suscettibilità batterica, panel"/>
													<statusCode code="completed"/>
													<component typeCode="COMP">
														
														<observation moodCode="EVN" classCode="OBS">
															<code code="18965-4" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Penicillina G"/>
															<statusCode code="completed"/>
															<effectiveTime value="20230630181000"/>
															<value xsi:type="ST"> R </value>
															<methodCode code="0240" codeSystem="2.16.840.1.113883.5.84" codeSystemName="ObservationMethod" displayName="Antibiotic sensitivity, disk" />
														</observation>
													</component>
													<component typeCode="COMP">
														
														<observation moodCode="EVN" classCode="OBS">
															<code code="18906-8" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Ciprofloxacina"/>
															<statusCode code="completed"/>
															<effectiveTime value="20230630181000"/>
															<value xsi:type="ST"> R </value>
															<methodCode code="0240" codeSystem="2.16.840.1.113883.5.84" codeSystemName="ObservationMethod" displayName="Antibiotic sensitivity, disk" />
														</observation>
													</component>
												</organizer>
											</component>
										</organizer>
									</entryRelationship>

Chiediamo supporto: forse la data e l'orario dev'essere inserito diversamente. Esempio: 202300630181000+0100 ?

**Comment by Fran31415926535** [comment]
Buongiorno,
le confermiamo che ,come anche riportato negli esempi al link https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/Documenti%20XML%20Casi%20OK/5%20-%20Casi%20OK%20Referto%20di%20Medicina%20di%20Laboratorio,  la data dovrebbe essere valorizzata nel formato da lei indicato (es. 20220330112426+0100)

**Comment by GitHsinformatica** [comment]
Ok grazie
