### ISSUE TITLE
Error: impossibile estrarre il CDA dal PDF - status 400

### ISSUE THREAD

**Issue by ValerioCremoniniProgel** [ministero-salute/it-fse-support#465]
Salve, inviando sia un referto LDO che RPS ricevo l'errore 'Error: impossibile estrarre il CDA dal PDF - status 400'
traceid 20230809163720646
Potete verificare per favore?

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
