### ISSUE TITLE
Errore Validazione Laboratorio Analisi

### ISSUE THREAD

**Issue by ftallaro** [ministero-salute/it-fse-support#466]
Buongiorno,

sto procedendo con i test per la validazione del laboratorio analisi. Ma vengono ritornati tutta una serie di errori.

Controllandoli non mi sembrano corretti come segnalazioni. In cosa sto sbagliando?

Allego il Pdf inviato e questo è il json di risposta ricevuto:

{"traceID":"0dda7ce639e0cd75","spanID":"0dda7ce639e0cd75","type":"/msg/semantic","title":"Errore semantico.","detail":"[ERRORE-b1| L'elemento code della section DEVE essere valorizzato con uno dei seguenti codici LOINC individuati:\n\t\t\t\t\t\t18717-9 BANCA DEL SANGUE\n\t\t\t\t\t\t18718-7 MARCATORI CELLULARI \n\t\t\t\t\t\t18719-5 CHIMICA\n\t\t\t\t\t\t18720-3\tCOAGULAZIONE\n\t\t\t\t\t\t18721-1 MONITORAGGIO TERAPEUTICO DEI FARMACI\n\t\t\t\t\t\t18722-9 FERTILITÀ\n\t\t\t\t\t\t18723-7 EMATOLOGIA\n\t\t\t\t\t\t18724-5 HLA\n\t\t\t\t\t\t18725-2 MICROBIOLOGIA\n\t\t\t\t\t\t18727-8 SEROLOGIA\n\t\t\t\t\t\t18728-6 TOSSICOLOGIA\n\t\t\t\t\t\t18729-4 ESAMI DELLE URINE\n\t\t\t\t\t\t18767-4 EMOGASANALISI\n\t\t\t\t\t\t18768-2 CONTE CELLULARE+DIFFERENZIALE\n\t\t\t\t\t\t18769-0 SUSCETTIBILITÀ ANTIMICROBICA\n\t\t\t\t\t\t26435-8 PATOLOGIA MOLECOLARE\n\t\t\t\t\t\t26436-6 ESAMI DI LABORATORIO\n\t\t\t\t\t\t26437-4 TEST DI SENSIBILITÀ A SOSTANZE CHIMICHE\n\t\t\t\t\t\t26438-2 CITOLOGIA\n\t\t\t\t\t\t18716-1 ALLERGOLOGIA\n\t\t\t\t\t\t26439-0 PATOLOGIA CHIRURGICA],[ERORE-b3| L'elemento component/structuredBody/component/section/text DEVE essere presente nel caso in cui non è riportata la sezione foglia. ],[ERORE-b6| L'elemento entry deve essere di tipo 'act'],[ERORE-b7| L'elemento entry/act DEVE contenere un elemento 'statusCode' che deve essere valorizzato come segue: completed | active | aborted.],[W003 | Si consiglia di utilizzare il sistema di codifica LOINC per la valorizzazione dell'elemento observation/code.--> ]","status":422,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.190.4.4.557600e1caa7c5b29bd931c55e582189e5733467eb364f3f22c4405d9b9a0148.6456fd0744^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

Grazie.

[ref_845569_fse20.pdf](https://github.com/ministero-salute/it-fse-support/files/12311832/ref_845569_fse20.pdf)

**Comment by IStacchiotti** [comment]
Buongiorno, a seguito dell'analisi del suo CDA2, sono emersi i seguenti errori, relativi alla seconda component/section inserita all'interno dell'elemento structuredBody:

1. Errore b1:  secondo linee guida HL7 Italia, DEVE essere utilizzato un code per indicare il tipo di specialità di laboratorio che si sta trattando nella section in oggetto.
2. Errore b3: secondo linee guida HL7 Italia, se structuredBody/component/section non contiene l’elemento component/section allora structuredBody/component/section DEVE contenere l’elemento section/text.
3. Errore b6: secondo linee guida HL7 Italia, l'elemento entry inserito Deve essere un elemento di tipo entry/act di conseguenza l’elemento component/section/entry/act DEVE contenere l’elemento act/code che DEVE coincidere con l’elemento section/code della section a cui entry/act è associato.
4. Errore b7, secondo linee guida HL7 Italia, l'elemento statusCode all'interno dell'entry/act Deve essere inserito è può avere una delle seguenti valorizzazioni completed, active, aborted. 

Per quanto riguarda il Warning non è un controllo bloccante al fine della validazione del CDA2, ma solo un suggerimento.

**Comment by ftallaro** [comment]
Buongiorno, 

mi permangono dei bussi:

1. A pagina 56 si parla della prima section "structuredBody/component/section" quindi perchè mi dice che devo indicarlo nella seconda section?
2. Ma nel cda che ho inviato la structuredBody/component/section contiene una component/section quindi non dovrebbe segnalarmi l'errore
3. Non ho capito cosa si intende
4. Lo statuscode è presente

Tra l'altro ho fatto una comparazione tra quello che ho inviato e l'esempio di CDA di laboratorio e negli errori indicati è uguale.

Continuo a non capire perchè mi torna questo errore.

**Comment by IStacchiotti** [comment]
Buongiorno. A seguito dell'analisi del suo CDA2, gli errori sono relativi alla seconda component/section inserita all'interno dell'elemento structuredBody.
- Per quanto riguarda l'errore b1, come riportato nella CONF-73, tutti gli elementi` structuredBody/component/section` devono contenere l'elemento `section/code` dove l'attributo @code assume uno dei valori costanti contenuti nella tabella di specialità riportato nel paragrafo 7.2.1 della guida. Nel CDA2 da lei inviato, la seconda section di specialità ha un elemento code che non è valorizzato con uno dei valori contenuti in questa tabella.
- Per quanto riguarda l'errore b3, come specificato nella CONF-75, se `structuredBody/component/section` non contiene l’elemento `component/section` allora `structuredBody/component/section` DEVE contenere l’elemento `section/text` non vuoto. Nell'esempio da lei inviato, non risulta presente l'elemento text.
- Per quanto riguarda l'errore b6, come specificato nella CONF-77 e nella CONF-78, se `structuredBody/component/section` non contiene nessun elemento` component/section`, allora `structuredBody/component/section` DEVE contenere uno ed un solo elemento entry, e l’elemento entry DEVE contenere uno ed un solo act (vedi 5.2.7) con `section/entry/@typeCode` che DEVE assumere il valore costante DRIV. Nell'esempio da lei inviato, l'elemento entry non è di tipo act.
- Per quanto riguarda l'errore b7, come specificato nella CONF-87, l’elemento `component/section/entry/act` DEVE contenere l’elemento `act/statusCode`, il cui attributo @code deve assumere uno dei seguenti valori: completed, active, aborted. Nell'esempio da lei inviato, l'elemento code non è presente.

**Comment by ponsilva** [comment]
Buongiorno,
mi inserisco in questa analisi perché mi sembra che ci sia un disallineamento tra quanto indicato nelle IG CDA2 LAB di HL7 e quanto definito nello schematron.

Le IG nel cap 5.1.1 riportano
Il Referto di Medicina di Laboratorio DEVE contenere almeno una section di specialità (ossia almeno un elemento del tipo structuredBody/component/section)
In questo caso deve essere presente l’elemento section/code con la codifica LOINC della specialità di laboratorio (come definito nel paragrafo 7.2.1)

E' però possibile che nel CDA2 LAB siano presenti **altre** section **non** di specialità, e per queste i controlli sopra indicati non dovrebbero essere eseguiti.

Sembra invece che lo schematron nel CDA2 LAB si aspetti tutte e solo section di specialità, implementando quindi una logica più restrittiva di quanto indicato nelle IG HL7

E' effettivamente così? 
In questo caso sarebbe utile avere un'indicazione di questi vincoli specifici del gateway, in modo tale da non ricevere errori imprevisti a fronte di CDA2 che sono corretti rispetto alle IG HL7
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
