### ISSUE TITLE
Errore 400 in test validazione

### ISSUE THREAD

**Issue by efrael** [ministero-salute/it-fse-support#468]
Buongiorno,
testando oggi il nostro applicativo client, in corso di accreditamento, riceviamo sempre l’errore che vi allego nonostante non abbiamo modificato nulla sul client e stiamo inviando uno dei test già precedentemente superati (il 2, ad esempio).
Sapete darci maggiori informazioni al riguardo? Grazie
 
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"700e8fed-3fef-11ee-8674-005056ae54fa"}

**Comment by LucaRogledi** [comment]
Grazie della segnalazione. Al fine di darvi supporto, vi chiediamo gentilmente di allegare i token utilizzati per l'invocazione.

**Comment by efrael** [comment]
Grazie a voi per la solerte risposta.

Mi scuso se non ho capito bene la richiesta, intendete i due certificati o proprio le stringhe dei token authJWT e signatureJWT passati con la specifica request?

 

Grazie!

 

Da: LucaRogledi ***@***.***> 
Inviato: lunedì 21 agosto 2023 17:07
A: ministero-salute/it-fse-support ***@***.***>
Cc: efrael ***@***.***>; Author ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Errore 400 in test validazione (Issue #468)

 

Grazie della segnalazione. Al fine di darvi supporto, vi chiediamo gentilmente di allegare i token utilizzati per l'invocazione.

**Comment by LucaRogledi** [comment]
La seconda: facciamo riferimento proprio alle stringhe dei due token (bearer e signature).
Grazie.

**Comment by efrael** [comment]
Ok, allora ho riprovato ora l’invio in quanto non li avevo loggati e adesso funziona tutto correttamente.

Non so cosa fosse successo, avevamo provato più volte negli ultimi giorni.

In caso di ulteriori problemi vi farò sapere, grazie!

**Comment by LucaRogledi** [comment]
Salve, grazie per il feedback, la presente viene chiusa come risolta. Può procedere con l'apertura di un nuovo ticket nel caso fosse necessario ulteriore supporto. Grazie
