### ISSUE TITLE
Profilo sanitario sintetico - formatCode non corretto

### ISSUE THREAD

**Issue by MarcoKnezevichInsiel** [ministero-salute/it-fse-support#469]
Buongiorno,
segnalamo quello che sembra essere un errore relativamente al [cda di esempio](https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/PSS.xml) del profilo sanitario sintetico.

In base alla [documentazione ](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/AffinityDomainItalia_v2-4-1.pdf) relativa all'affinity domain in versione 2.4.1, il _format code_ corretto per il PSS dovrebbe essere:

`2.16.840.1.113883.2.9.10.2.4.1.1`

mentre nel CDA di esempio viene riportato:

`<templateId root="2.16.840.1.113883.2.9.10.1.4.1.1" extension="1.4" assigningAuthorityName="HL7 Italia"/>`

quindi c'è la parte finale con un 1 al posto del 2, ovvero `....1.4.1.1` invece di  `....2.4.1.1`

Potreste indicarci se è un errore ed eventualmente correggere il file di esempio?

Grazie e buona giornata.

**Comment by IStacchiotti** [comment]
Buongiorno. Come indicato nelle LG del Profilo Sanitario Sintetico Versione 1.4, l'elemento templateId deve contenere l'attributo @root valorizzato con "2.16.840.1.113883.2.9.10.1.4.1.1", come riportato nel cda di esempio.

**Comment by MarcoKnezevichInsiel** [comment]
Grazie, confermiamo infatti che occorre il templateid con "1" affinché il cda2 risulti valido per il gateway.

Tuttavia in uno scenario di pubblicazione del documento nel fse, le [specifiche tecniche dell'affinity domain 2.4.1](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/AffinityDomainItalia_v2-4-1.pdf) (e versioni precedenti) indicano (pagina 15) per il metadato obbligatorio XDSDocumententry.formatCode quanto segue:

_**"Se il documento è in formato HL7 CDA Release 2.0, questo metadato deve veicolare il valore dell’attributo /ClinicalDocument/templateId/@root. "**_

![PSS_affinity_domain](https://github.com/ministero-salute/it-fse-support/assets/111368774/edeb25cf-c1cf-45fd-91e1-cb5ea6f448c4)

È necessario aggiornare l'affinity domain in modo che le specifiche siano coerenti tra cda2 e pubblicazione?

Grazie

**Comment by IStacchiotti** [comment]
Buonasera, grazie per la segnalazione.
Al momento la invitiamo a fare riferimento alla valorizzazione, indicata nel messaggio precedente, per l'attributo root in questione. Appena disponibili, seguiranno aggiornamenti in merito al disallineamento segnalato.

**Comment by vigliottim** [comment]
Buonasera, 
Le confermiamo che può far riferimento al file di esempio: la documentazione relativa all'affinity domain verrà corretta con il prossimo aggiornamento.
Grazie.
