### ISSUE TITLE
Test per Codice Aic Influenza errore Almeno uno dei seguenti vocaboli non è censito

### ISSUE THREAD

**Issue by Fusarolia** [ministero-salute/it-fse-support#47]
Buon giorno sto provando ad inviare un certificato vaccinale con vaccinazione influenza.
Ho già provato vari codici aic utilizzati per le vaccinazioni, ma ottengo sempre il seguente errore
traceID=38e5a3a0e0fa5267, spanID=38e5a3a0e0fa5267, type=/msg/vocabulary, title=Errore vocabolario., detail=Almeno uno dei seguenti vocaboli non è censito: [CodeSystem: 2.16.840.1.113883.2.9.6.1.5, Codes: 047475037], status=400.0, instance=/validation/error, workflowInstanceId=2.16.840.1.113883.2.9.2.114.4.4.f0b18c4b62d493d3847fac4d743720e6d72dc8e77f2e671962e165069f328292.1762f46ec5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

Potete indicarmi  codice aic valido per il test o se il problema è di altro genere.

**Comment by Fusarolia** [comment]
Buon giorno,
è possibile avere un riscontro.

Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, le chiederei cortesemente di riprovare, l'errore non dovrebbe più verificarsi. Grazie.
