### ISSUE TITLE
Stato di processamento di una PR

### ISSUE THREAD

**Issue by o3enterprise** [ministero-salute/it-fse-support#471]
Salve,
vorremmo sapere se ci sono novità sullo stato di processamento di questa PR che è in attesa di essere evasa.
https://github.com/ministero-salute/it-fse-accreditamento/pull/741
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, ci risulta che è stata inviata il 24 luglio, all'indirizzo comunicato in Eu Survey, una email con le indicazioni per lo svolgimento di una correzione necessaria. Vi invitiamo a verificare (eventualmente avendo cura di controllare anche nello spam), grazie. Rimaniamo a disposizione per ulteriori chiarimenti

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
