### ISSUE TITLE
Errore chiamate Gateway

### ISSUE THREAD

**Issue by fnicoletti** [ministero-salute/it-fse-support#472]
Salve abbiamo un problema con la verifica sul gateway, chiamando il servizio di validazione riceviamo sempre l'errore Received request is not conform to the required interoperability profile. C'è qualche problema sul Gateway? abbiamo provato anche il template d'esempio ma il risultato non cambia. 
Inserisco la risposta completa ottenuta:
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"b2d8983b-4732-11ee-b966-005056ae7395"}
Grazie

**Comment by vigliottim** [comment]
Buonasera, le chiediamo gentilmente di allegare i token utilizzati per la chiamata. Grazie.

**Comment by fnicoletti** [comment]
Buongiorno allego i due token inviati. Invio anche il nuovo govway di risposta.
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"5a5ee904-47c6-11ee-8674-005056ae54fa"}

Grazie
[jwt auth.txt](https://github.com/ministero-salute/it-fse-support/files/12483931/jwt.auth.txt)
[jwt Signature.txt](https://github.com/ministero-salute/it-fse-support/files/12483932/jwt.Signature.txt)

**Comment by fnicoletti** [comment]
il problema era un duplicato nel campo aud del token authorization. Ora funziona perfettamente. Grazie
