### ISSUE TITLE
Piano di adeguamento

### ISSUE THREAD

**Issue by DATASOFTNA** [ministero-salute/it-fse-support#473]
Buonasera.
Ho ricevuto la richiesta di compilare il modulo di "Piano di adeguamento degli applicativi a FSE 2.0......".
Siccome tra i campi obbligatori sono presenti Azienda Sanitaria e Presidio, non saprei come compilarli in quanto il sw e' installato solo presso strutture accreditate private.
Inoltre il sw si occupa della gestione della refertazione dei laboratori di analisi cliniche e nel campo "ambito applicativo/tipologia documentale" questa voce non esiste oppure va considerata la voce "Referto di Specialistica Ambulatoriale" ?

**Comment by vigliottim** [comment]
Buongiorno, le sono state inviate indicazioni a riguardo tramite il canale e-mail. La invitiamo a controllare e darci un riscontro in caso di mancata ricezione. Grazie.

**Comment by DATASOFTNA** [comment]
Ok, ricevuti chiarimenti.
