### ISSUE TITLE
generazione dei token ( JWT ) 

### ISSUE THREAD

**Issue by giacomosandroni** [ministero-salute/it-fse-support#476]
come ambiente di sviluppo noi utilizziamo vb.net ( .net framework 4.5 o superiori ) è forse possibile avere esempi per la generazione dei token ( JWT )in tale ambiente ?

vedi allegato per problemi generazione token
[ProblemiGEnerazioneToken.pdf](https://github.com/ministero-salute/it-fse-support/files/12645691/ProblemiGEnerazioneToken.pdf)

**Comment by LucaRogledi** [comment]
Buongiorno,
Come indicato in [documentazione](https://github.com/ministero-salute/it-fse-gtw-tools) il comando "mvn clean package" andrebbe eseguito all'interno della directory "*/it-fse-gtw-tools-main", che contiene una sottocartella specifica per ciascun tool messo a disposizione. 
In alternativa, il comando in questione può essere utilizzato per eseguire la build anche di un singolo tool:  in questo caso il comando andrà eseguito nella sottocartella relativa al tool di interesse (es. "*/it-fse-gtw-tools-main/jwt-generator").
La invitiamo a riprovare e a fornirci un ulteriore riscontro in caso di problemi.
Grazie

**Comment by vigliottim** [comment]
Buon pomeriggio, non avendo ricevuto ulteriori feedback, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie.
