### ISSUE TITLE
Errore in fase di recupero dell'esito della verifica

### ISSUE THREAD

**Issue by federicolau** [ministero-salute/it-fse-support#477]
Ciao,

stiamo effettuando alcuni test di carico invocando il servizio "validate-and-create" tramite JMeter (configurato con un certo numero di threads).
Il CDA che inviamo è sempre lo stesso e la request è la seguente:

```
{
   "healthDataFormat":"CDA",
   "mode":"ATTACHMENT",
   "tipologiaStruttura":"Ospedale",
   "attiCliniciRegoleAccesso":[
      "PUBLICPOL"
   ],
   "identificativoDoc":"2.16.840.1.113883.2.9.2.120.4.4^111113",
   "identificativoRep":"ID_REPOSITORY",
   "tipoDocumentoLivAlto":"WOR",
   "assettoOrganizzativo":"AD_PSC001",
   "tipoAttivitaClinica":"PHR",
   "identificativoSottomissione":"2.16.840.1.113883.2.9.4.3.2",
   "priorita":true,
   "descriptions":[
      "019655^Bentelan^2.16.840.1.113883.2.9.6.1.5"
   ]
}
```

Spesso, però, riceviamo il seguente errore:

**{"traceID":"01878ab04387df2b","spanID":"01878ab04387df2b","type":"/msg/cda-match","title":"Errore in fase di recupero dell'esito della verifica.","detail":"Il CDA non risulta validato","status":400,"instance":"/cda-validation"}**

Tale errore, lo abbiamo anche ricevuto chiamando il servizio di validazione e pubblicazione singolarmente.
In questo caso, però, leggendo qui tra le varie issues di GitHub, ce lo aspettavamo in quanto la pubblicazione che andava in errore non faceva riferimento alla corrispettiva validazione lanciata.
Ma il servizio "validate-and-create" non dovrebbe evitare proprio questo, ossia assicurare il sincronismo tra i due servizi?

**Comment by vigliottim** [comment]
Buongiorno,
le chiederemmo cortesemente di ripetere una singola invocazione del servizio "validate-and-create" per verificare se l'errore si presenta anche in questa casistica. In generale, i servizi dovrebbero essere richiamati con CDA diversi. Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori feedback, la presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie.
