### ISSUE TITLE
Received request is not conform to the required interoperability profile

### ISSUE THREAD

**Issue by EliaMenoni** [ministero-salute/it-fse-support#478]
Salve, come richiesto su slack questa e' la issue.

```json
{
 "detail": "Received request is not conform to the required interoperability profile",
 "govway_id": "76288897-585b-11ee-a4d5-005056ae54fa",
 "status": 400,
 "title": "InteroperabilityInvalidRequest",
 "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html"
}
```

La richiesta risulta, a mio avviso, conforme:

```HTTP
POST /test HTTP/1.1
Host: fsetest.requestcatcher.com
Accept: application/json
Accept-Encoding: gzip, deflate
Authorization: Bearer <BEARER-TOKEN>
Connection: keep-alive
Content-Length: 21245
Content-Type: multipart/form-data; boundary=83f479c7c0ae5dd441f972931967fa84
Fse-Jwt-Signature: <JWT-TOKEN>
User-Agent: python-requests/2.31.0

--83f479c7c0ae5dd441f972931967fa84
Content-Disposition: form-data; name="requestBody"

{"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VALIDATION"}
--83f479c7c0ae5dd441f972931967fa84
Content-Disposition: form-data; name="type"

application/pdf
--83f479c7c0ae5dd441f972931967fa84
Content-Disposition: form-data; name="file"; filename="definitivo.pdf"
Content-Type: application/pdf

<PDF-DATA>
--83f479c7c0ae5dd441f972931967fa84--
```
_**alcune informazioni sono state rimosse per snellire il codice**_

**Comment by IStacchiotti** [comment]
Buongiorno @EliaMenoni, potreste verificare cortesemente che non sia scaduta la chiave privata del certificato?

**Comment by EliaMenoni** [comment]
Di firma o di autenticazione?

**Comment by IStacchiotti** [comment]
Vi inviteremmo a controllarle entrambe. Rimaniamo in attesa di un vostro gentile riscontro, grazie

**Comment by EliaMenoni** [comment]
Ho controllato, entrambi i certificati
Per il certificato di firma
```bash
notAfter=Mar  9 22:40:47 2026 GMT-in S1111TOPGATEXXXX_sign.pem
```
Per il certificato di autenticazione
```bash
notAfter=Mar  9 22:40:20 2026 GMT
```
Tuttavia non mi risulta che la chiavi presentino una scadenza
```bash
openssl x509 -enddate -noout -in xxx.pem
...
```
```bash
openssl x509 -enddate -noout -in xxx.key
ERRORE
```

**Comment by EliaMenoni** [comment]
Ho a disposizione solo il .p12 che utilizzo per la generazione dei token
```bash
openssl x509 -enddate -noout -in firmaTopgate.p12
Enter pass phrase for PKCS12 import pass phrase:
notAfter=Mar  9 22:40:47 2026 GMT

```

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate il token di authorization risulta errato.
Infatti, decodificandolo con il tool [jwt.io](jwt.io), compare il seguente messaggio di errore:

![MicrosoftTeams-image (4)](https://github.com/ministero-salute/it-fse-support/assets/134372089/70933a33-f779-4f24-a688-5d9fdff2c5fa)

Potrebbe ricontrollare il processo di rigenerazione del token? Grazie.

**Comment by EliaMenoni** [comment]
Salve, grazie del aiuto. Uno dei caratteri del bearer venuta perso durante il salvataggio del token dal tool. Il problema è stato risolto.

Grazie ancora.
