### ISSUE TITLE
Errore "Unauthorized request content"

### ISSUE THREAD

**Issue by GianlucaCallegari-GPI** [ministero-salute/it-fse-support#48]
abbiamo modificato il token passando questa iss:
"iss" : "integrity:a1#111gruppogpi00",

ma otteniamo ancora l'errore:
{
  "type" : "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
  "title" : "AuthorizationContentDeny",
  "status" : 403,
  "detail" : "Unauthorized request content",
  "govway_id" : "d8887bac-90ca-11ed-b06a-005056ae7395"
}

_Originally posted by @GianlucaCallegari-GPI in https://github.com/ministero-salute/it-fse-support/issues/42#issuecomment-1377099192_

**Comment by zukka77** [comment]
per i token bisogna usare il certificato di signature, non di autorizzazione che si usa solo per l'https.
Quindi
`integrity:S1#111gruppogpi00` per il token di signature  e 
`auth:S1#gruppogpi00` per quello di autorizzazione.
**controllate il case del common name**

**Comment by GianlucaCallegari-GPI** [comment]
Grazie mille per la risposta, abbiamo fatto le modifiche utilizzando il certificato di signature, ma otteniamo ancora l'errore:

{
  "type" : "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
  "title" : "AuthorizationContentDeny",
  "status" : 403,
  "detail" : "Unauthorized request content",
  "govway_id" : "4886f5b9-90e8-11ed-b21d-005056ae54fa"
}

**Comment by zukka77** [comment]
Ho controllato il vostro CN dovrebbe essere `S1#111GRUPPOGPI00` usate questa stringa (maiuscola) ?

**Comment by GianlucaCallegari-GPI** [comment]
sì, utilizziamo S1#111GRUPPOGPI00 (la copio qui dalle nostre configurazioni per sicurezza)

**Comment by pFonziSogei** [comment]
Salve, ci sembra che all'interno del certificato di firma ci sia una dicitura non corretta per quanto riguarda l'issuer: "111GRUPPOGPI000". Potete verificare questo particolare e ritornarci un nuovo GovWayId in caso il problema persista?

**Comment by pFonziSogei** [comment]
Salve, da analisi più approfondita sembrerebbe che stiate usando come certificato di Autorizzazione lo stesso certificato che usate per la firma. Sarebbe possibile una verifica in tal senso? @GianlucaCallegari-GPI

**Comment by IStacchiotti** [comment]
Non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
