### ISSUE TITLE
Validazione VPS - Chieirmento nome file CDA

### ISSUE THREAD

**Issue by stellariAbstract** [ministero-salute/it-fse-support#480]
Buongiorno,
dopo aver concluso il collaudo con Lepida (Regione Emilia Romagna) per la nuova versione FSE2022, ho riscontrato difficoltà relativamente al nome del file CDA allegato al PDF.

Se chiamo il file "cda2.xml" come richiesto dal validatore, Lepida non è in grado di estrarlo, poichè vuole che si chiami "cda.xml". Ovviamente se chiamo il file "cda.xml", il validatore non lo estrae dando errore: "Error while extracting CDA from PDF document".

Come posso procedere?

Grazie.

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Potrebbe gentilmente allegare il pdf che è stato usato per effettuare la richiesta?
Inoltre le chiederemmo cortesemente di specificare la modalità con cui è stato inserito il cda nel pdf (Attachment o Resource), insieme al govway_id/trace_id ricevuti in risposta dal sistema.
Grazie.

**Comment by LucaRogledi** [comment]
Buonasera, non vediamo il pdf allegato. Potrebbe controllare e in caso riallegarlo?
Grazie

**Comment by stellariAbstract** [comment]
La risposta diretta alla mail evidentemente non lo mantiene.

Provo direttamente da GitHub.
[CDA.pdf](https://github.com/ministero-salute/it-fse-support/files/12735777/CDA.pdf)

**Comment by stellariAbstract** [comment]
Salve, grazie per la precisazione.
Potrebbe aver funzionato.
Ho ottenuto:
{"traceID":"c865969ce646b176","spanID":"c865969ce646b176","workflowInstanceId":"2.16.840.1.113883.2.9.2.80.3.1.4.4.6423afe41cf82f4bba3d21d8a0405d6319ff347d82d4a2c7becaa9046cc04676.eeabf324f2^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

Conferma che sia corretto?

**Comment by stellariAbstract** [comment]
Buon pomeriggio,
  dopo il precedente invio andato a buon fine, abbiamo inviato un altro documento e, nonostante il relativo CDA sia in utf-8, continua a dare il medesimo errore: "Error while extracting CDA from PDF document".
TraceId 1e99a0c155722ed1
Allego il file.
[VPS_CASO_0.pdf](https://github.com/ministero-salute/it-fse-support/files/12749457/VPS_CASO_0.pdf)

Potreste verificare?
Grazie,
Stefano.

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate risulta che il file che sta allegando è "CDA.pdf". Può controllare se corrisponde al file che ha allegato al ticket "VPS_CASO_0.pdf"? Grazie.

**Comment by stellariAbstract** [comment]
Salve,
  si, il file corrisponde. Non c'è relazione tra il nome del file che io salvo sul mio PC per poter allegarlo alla issue ed il "nome" indicato sulla chiamata http che è fisso a "CDA.pdf". Quando lo slavo per poterlo allegare gli do un nome diverso.
Non credo che la differenza nel nome sia la causa del problema, visto che questo cambio avviene solo dopo, quando devo allegare il PDF su GitHub...

**Comment by vigliottim** [comment]
La invitiamo a consultare il seguente [ticket](https://github.com/ministero-salute/it-fse-support/issues/131). L'utente aveva ricevuto un errore analogo al suo che ha risolto modificando la libreria usata per la creazione della request HTTP multipart. Potrebbe verificare se l'errore persiste anche adottando un'altra libreria? Restiamo in attesa di un suo gentile riscontro.

**Comment by stellariAbstract** [comment]
Buongiorno,
  il software gestionale sul quale sviluppo la soluzione non ha il concetto di "librerie" come per esempio si potrebbe avere in Java o similari. Precedentemente aveva già cambiato la modalità con la quale allegavo il PDF al messaggio HTTP, ma evidentemente potrebbe essere cambiato qualcosa che non riesco ad identificare. 
Potreste cortesemente analizzare la http request inviata e darmi una indicazione più precisa di cosa potrebbe esserci di sbagliato?
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, Le confermiamo che analisi sono attualmente in corso. Le faremo sapere il prima possibile. Grazie

**Comment by IStacchiotti** [comment]
Buongiorno,

Le facciamo presente che dalle analisi non sono emerse anomalie nella chiamata http.

Inoltre, le segnaliamo che non sono stati riscontrati problemi nel validare il documento PDF allegato in questo thread (rif. VPS_CASO_0.pdf).

Al contrario, il PDF ricevuto in ingresso dal sistema, estratto dai log della chiamata, risulta illeggibile\corrotto (in allegato).

In conclusione, la invitiamo ad accertarsi che il file inviato al momento della richiesta sul gateway sia integro, leggibile e ben codificato.

Rimaniamo a disposizione per eventuali ulteriori richieste di supporto, grazie
[output.pdf](https://github.com/ministero-salute/it-fse-support/files/12781273/output.pdf)

**Comment by stellariAbstract** [comment]
Trovato... durante la creazione della multiform part c'era una conversione di charset. Il bello è che non tutti i PDF ne risentivano (questo spiega come sporadicamente andasse). Ora quello è risolto.
Tuttavia ho ottenuto un errore semantico relativo ai campi di versione che ora verificherò.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, la ringraziamo per il feedback.
Procediamo alla chiusura del presente ticket e la invitiamo ad aprirne uno nuovo nel caso avesse bisogno di ulteriore supporto.
