### ISSUE TITLE
Errore 400 Bad Request /documents/validation

### ISSUE THREAD

**Issue by ascozzarro** [ministero-salute/it-fse-support#481]
Segnaliamo un errore 400 Bad Request in risposta al servizio di validazione di test, endpoint:
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation

L'ultima richiesta di questo tipo è stata fatta oggi 27 settembre alle ore 10:47:00.
Nel file allegato i dati della richiesta (effettuata in locale in http per recuperarne i parametri, ma identica a quella effettuata in https verso il vostro servizio):
[netcat.txt](https://github.com/ministero-salute/it-fse-support/files/12736778/netcat.txt)

Allego anche il verbale di prova inviato:
[VPS_CDA2.pdf](https://github.com/ministero-salute/it-fse-support/files/12736962/VPS_CDA2.pdf)

Vorremmo quindi sapere quali parametri della richiesta causano l'errore 400.

Segnalo anche che effettuando la richiesta tramite curl utilizzando token generati con gli stessi dati, stessi header, stesso file, ecc, questa va a buon fine, con la restituzione di un errore applicativo di validazione del documento, es (detail omesso):
{"traceID":"0635b3b3c330b92c","spanID":"0635b3b3c330b92c","type":"/msg/semantic","title":"Errore semantico.","detail":"***","status":422,"instance":"/validation/error","workflowInstanceId":".e282a36d89322440ab170850345e94e8a9bd1ff21a1c594ee30d58f44dc05e38.df776617de^^^^urn:ihe:iti:xdw:2013::workflowInstanceId"}

**Comment by vigliottim** [comment]
Buongiorno, potrebbe cortesemente condividerci il govway_id o il trace_id della chiamata che restituisce errore 400? Grazie.

**Comment by ascozzarro** [comment]
Salve, ho riprovato e adesso l'errore è: "Errore in fase di estrazione del CDA."

{"traceID":"3d47065c9e71e9d4","spanID":"3d47065c9e71e9d4","type":"/msg/cda-element","title":"Errore in fase di estrazione del CDA.","detail":"Error while extracting CDA from PDF document","status":400,"instance":"/cda-extraction","workflowInstanceId":"UNKNOWN_WORKFLOW_ID"}

Il documento inviato è sempre VPS_CDA2.pdf, che ho allegato nella prima richiesta.

**Comment by LucaRogledi** [comment]
Buongiorno,
Dalle verifiche è emerso che l'errore in questione potrebbe essere dovuto all'encoding. 
Abbiamo verificato che l'encoding del cda inserito nel pdf corrisponde come atteso all'utf-8. 
Vi invitiamo cortesemente a ritentare la chiamata esplicitando il charset sia per la requestBody che per il pdf, come indicato di seguito.

- requestBody: `Content-Type: application/json; charset=utf-8`

- pdf: `Content-Type: application/pdf; charset=utf-8`

Grazie.

**Comment by ascozzarro** [comment]
Aggiungendo il charset per requestBody e file la chiamata è andata a buon fine.

Grazie del supporto.
