### ISSUE TITLE
Errore accreditamento per il CDA di Specialistica

### ISSUE THREAD

**Issue by ValerioCremoniniProgel** [ministero-salute/it-fse-support#482]
Salve,

ottengo una risposat che non mi aiuta a capire quale sia il problema.
Inoltre il CDA è validato correttamente dal validatore LantaGroup

In allegato il CDA

Potreste verificare?

Grazie

Response:
StatusCode: 422, ReasonPhrase: '422', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Mon, 25 Sep 2023 13:30:03 GMT
  Server: Apache
  Content-Type: application/problem+json
  Content-Length: 217
}
{"traceID":"18f2a1fa9fce50f5","spanID":"18f2a1fa9fce50f5","type":"/msg/semantic","title":"Errore semantico.","detail":"Error while executing validation on sch schematron","status":"422","instance":"/valida
tion/error"}

Errore: UnprocessableEntity

[esValErr.txt](https://github.com/ministero-salute/it-fse-support/files/12750251/esValErr.txt)

**Comment by LucaRogledi** [comment]
Buongiorno,
Dalle verifiche è emerso che l'errore in questione potrebbe essere dovuto all'encoding.
Abbiamo verificato che l'encoding del cda inserito nel pdf corrisponde come atteso all'utf-8.
Vi invitiamo cortesemente a ritentare la chiamata esplicitando il charset per il pdf, come indicato di seguito.

- `Content-Type: application/pdf; charset=utf-8`

Grazie

**Comment by ValerioCremoniniProgel** [comment]
Ciao Luca,

il CDA è UTF-8

dall'immagine allegata vedi che non ha BOM in testa

![image](https://github.com/ministero-salute/it-fse-support/assets/65
![esValErr_Encoding](https://github.com/ministero-salute/it-fse-support/assets/65277136/c3f6c4eb-fc13-44db-883a-d524cd93a1e4)
277136/1afb6e27-8612-440e-b516-222f053207c3)

**Comment by LucaRogledi** [comment]
Buongiorno,
Confermiamo che il cda condiviso da lei in precedenza in questo thread risulta con encoding utf-8, ma nel nostro messaggio precedente ci riferivamo al cda inserito nel pdf ricevuto in ingresso dal gateway (in allegato).
Potreste cortesemente verificare che in fase di iniezione del cda nel pdf non venga modificato inavvertitamente l'encoding?
[message.pdf](https://github.com/ministero-salute/it-fse-support/files/12763246/message.pdf)
Grazie.

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
