### ISSUE TITLE
Errore accreditamento FSE 2.0 - PSS Test Case 14 - CDA2_Profilo_Sanitario_Sintetico_KO

### ISSUE THREAD

**Issue by ludovicofunari** [ministero-salute/it-fse-support#483]
Salve, il test case KO 14 [prevede](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/8-Profilo%20Sanitario%20Sintetico/CDA2_Profilo_Sanitario_Sintetico_KO.xlsx) il mancato inserimento del campo `ClinicalDocument/component/structuredBody/component/section[@ID=Vaccinazioni]/text`, che dovrebbe generare un errore semantico. Però l'omissione di questo campo non genera alcun errore. In particolare, il servizio risponde con 201 created.

Il file XML necessario per questo test case, lo abbiamo generato a partire da [PSS - Caso di Test 4.xml](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/Documenti%20XML%20Casi%20OK/8%20-%20Casi%20OK%20Profilo%20Sanitario%20Sintetico/PSS%20-%20Caso%20di%20Test%204.xml) rimuovendo le righe 417-419.

**Comment by vigliottim** [comment]
Buongiorno, abbiamo preso in carico la modifica della documentazione per risolvere la issue in oggetto. Grazie per la segnalazione.

**Comment by IStacchiotti** [comment]
Buongiorno, le confermiamo che le modifiche sono state concluse, siamo in attesa al momento che vengano pubblicate. Le daremo evidenza in questo thread non appena saranno visibili gli aggiornamenti sulla documentazione disponibile in GitHub. Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, Le comunichiamo che è stata pubblicata la documentazione aggiornata. Per questo procediamo alla chiusura del presente, rimanendo comunque disponibili per ulteriori richieste di supporto. Grazie
