### ISSUE TITLE
Errore accreditamento FSE 2.0 - PSS Test Case 20 - CDA2_Profilo_Sanitario_Sintetico_KO

### ISSUE THREAD

**Issue by ludovicofunari** [ministero-salute/it-fse-support#484]
Salve, il test case KO 20 [prevede](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/8-Profilo%20Sanitario%20Sintetico/CDA2_Profilo_Sanitario_Sintetico_KO.xlsx) la valorizzazione errata del codice (observation/value) nella sezione `ClinicalDocument/component/structuredBody/component/section[@ID=Stato_funzionale_del_Paziente]/entry/organizer/component/observation/value`.

L'errore attesto è terminologico, mentre modificando il campo in questione avviene un "Errore semantico". Forse va inserito un altro `observation/value` ma non saprei quale.

**Comment by vigliottim** [comment]
Buongiorno, potrebbe cortesemente allegare il CDA utilizzato? Grazie.

**Comment by ludovicofunari** [comment]
Certamente, eccolo in allegato.

[PSS_testcase_KO_20.pdf](https://github.com/ministero-salute/it-fse-support/files/12762831/PSS_testcase_KO_20.pdf)

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate nel cda.xml risulta errato l'id utilizzato della section "Stato funzionale del paziente", per questo ottiene un errore semantico. Potrebbe riprovare sostituendo ID="STATO_FUNZIONALE_PAZIENTE" con ID="Stato_funzionale_del_Paziente"? Restiamo a disposizione in caso l'errore dovesse ripresentarsi. Grazie.

**Comment by ludovicofunari** [comment]
Grazie per la risposta ma purtroppo il problema non è stato risolto.
Cambiando da ID="STATO_FUNZIONALE_PAZIENTE" a ID="Stato_funzionale_del_Paziente" e sostituendo l'intera riga `ClinicalDocument/component/structuredBody/component/section[@ID=Stato_funzionale_del_Paziente]/entry/organizer/component/observation/value` (come specificato dal `PSS - caso di test 20` dal file "CDA2_Profilo_Sanitario_Sintetico_KO.xlsx"), il risultato è sempre un errore semantico e non terminologico, questo è il risultato:

```
{"traceID":"e3a3d52745001a4e","spanID":"e3a3d52745001a4e","type":"/msg/semantic","title":"Errore semantico.","detail":"[ERRORE-b201| Sezione Stato funzionale del paziente: entry/organizer/component/observation (Capacità motoria) DEVE contenere un elemento 'value' valorizzato secondo i seguenti code system:\n\t\t\t- LOINC (@codeSystem: 2.16.840.1.113883.6.1)\n\t\t\t- CapacitàMotoria_PSSIT  (@codeSystem=2.16.840.1.113883.2.9.77.22.11.15). ],[ERRORE-b201a| Sezione Stato funzionale del paziente: entry/organizer/component/observation (Capacità motoria) DEVE contenere un elemento 'value' il cui attributo @code può assumere uno dei seguente valori:\n\t\t\t- \"LA21285-4\" per la condizione \"autonomo\";\n\t\t\t- \"LA21286-5\" per la condizione \"assistito\";\n\t\t\t- \"LA6743-4\" per la condizione \"su sedia a rotelle\";\n\t\t\t- \"LA4270-0\" per la condizione \"allettato\".\n\t\t\t]","status":422,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.a9f4347f79cf3e1cf2ff4d79eaf6d0cf8d4a82cf3fb4e942adcc54e7fc27772e.988d9a070d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}
```

In allegato il [PDF](https://github.com/ministero-salute/it-fse-support/files/12765925/PSS_testcase_KO_20_2.pdf) usato.

**Comment by vigliottim** [comment]
Buongiorno, nel secondo CDA2 fornito, l'errore semantico è dovuto alla valorizzazione errata del sistema di codifica associato all'elemento _component/observation/value_ relativo alla Capacità Motoria. Il value set corretto da utilizzare per tale sezione è "2.16.840.1.113883.2.9.77.22.11.15". 
Tuttavia si conferma che, sbagliando il codice associato a tale sistema di codifica, l'errore generato è sempre semantico anziché terminologico, pertanto verrà effettuata una fix allo schematron.
Nell'attesa che venga apportata la modifica, è possibile generare l'errore terminologico valorizzando in modo errato il campo _component/observation/value/@code_ inerente al code system Assistenza domiciliare.
Grazie per segnalazione.

**Comment by vigliottim** [comment]
Buonasera, la informiamo che è stato modificato lo schematron del PSS come anticipato. Le chiediamo gentilmente di riprovare e segnalarci se riscontra anomalie. Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario. Grazie.
