### ISSUE TITLE
Errori DATE_BEFORE su LDO già validati rif. Pull Request #851 

### ISSUE THREAD

**Issue by giampietrozamparo** [ministero-salute/it-fse-support#485]
Tutti i test LDO già precedentemente validati, sono andati in errore come ad esempio:
 {
  "id" : 68,
  "error" : "DATE_BEFORE",
  "description" : "Data test antecedente all'ultimo test accreditato"
}

Nonostante che i file non siano mai stati modificati
[errors.json.txt](https://github.com/ministero-salute/it-fse-support/files/12762873/errors.json.txt)

Grazie

**Comment by IStacchiotti** [comment]
Buongiorno @giampietrozamparo,
Come riportato in documentazione a questo [link](https://github.com/ministero-salute/it-fse-accreditamento#nuova-tipologia-documentale-per-applicativo-gi%C3%A0-presente-nella-lista-dei-software-convalidati), nel momento in cui si aggiunge una nuova tipologia documentale (RSA nel caso specifico) in seguito al conseguimento della validazione per una diversa tipologia di documento (LDO in questo caso), occorre ripetere la procedura per entrambe le tipologie documentali. Per velocizzare il processo, consigliamo di sottomettere la checklist compilata per tutte le tipologie di documentali gestite dall'applicativo per cui si intende accreditarsi. Rimaniamo a disposizione per chiarimenti. Grazie

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
