### ISSUE TITLE
CT1 VPS

### ISSUE THREAD

**Issue by sandroaresu23** [ministero-salute/it-fse-support#487]
Buongiorno, vorrei avere informazioni relative al CT1 di VPS descritto nel documento CDA2_Verbale_Pronto_Soccorso_OK.xlsx.
Vengono indicati come obbligatori gli entryRelationship relativi a dimissioni con ricovero ospedaliero e dimissione con trasferimento verso altra struttura (rispettivamente alle righe 146 e 190 del documento).Queste due casistiche però sono mutualmente esclusive, in PS o si dimette con ricovero o si dimette con trasferimento e non è possibile generare da applicativo un CDA che li contenga entrambi.
Mi potete dare informazioni in merito? Sto forse interpretando male il CT?

**Comment by marsardit** [comment]
Buongiorno,
sollecitiamo cortesemente un riscontro
Grazie,

**Comment by vigliottim** [comment]
Buongiorno, grazie della segnalazione. Si conferma che le 2 entryRelationship sono mutuamente esclusive, pertanto verrà modificato il controllo sul test case. Restiamo a disposizione per ulteriori richieste di supporto.

**Comment by sandroaresu23** [comment]
Buongiorno, il controllo sul test case segnalato è già stato modificato? In caso negativo, entro quando pensate di modificarlo?
Grazie

**Comment by vigliottim** [comment]
Buongiorno, il controllo sul test case segnalato è stato modificato. Le daremo evidenza non appena verrà pubblicata la documentazione aggiornata su GitHub. Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, Le comunichiamo che è stata pubblicata la documentazione aggiornata. Per questo procediamo alla chiusura del presente, rimanendo comunque disponibili per ulteriori richieste di supporto. Grazie
