### ISSUE TITLE
Mancato accreditamento per A1#111GRUPPOGPI00 - TESI_SPA - DECIA - 4.0

### ISSUE THREAD

**Issue by elia-tesi** [ministero-salute/it-fse-support#488]
Salve,
in base alla mail automatica ricevuta ieri, 28/9, non abbiamo superato l'accreditamento per l'applicativo DECIA.
Il motivo è il seguente: 
[ {
  "id" : 374,
  "error" : "WII_UNKNOWN_LOG",
  "description" : "WorkflowInstanceID non presente nella collection dei log.Assicurarsi di aver eseguito correttamente la validazione per il wii segnalato"
} ]

Il workflowinstaId che avevamo comunicato è il seguente: 2.16.840.1.113883.2.9.2.50504.4.4.18.bb355b9fbc2500f6135c3e9b283f8eb397957ad0ee20ca4615269d3944e6166b.8bf992fa98^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

Dopo i nostri controlli, non ci risulta niente di anomalo. Ci potete fornire un'indicazione sull'errore presente?
Grazie

**Comment by elia-tesi** [comment]
Buongiorno @vigliottim, avete novità in merito a questa issue?

**Comment by vigliottim** [comment]
Salve,
è stato riscontrato un disservizio che ha generato l'errore di "WII_UNKNOWN_LOG" causando il mancato accreditamento.
Le chiederemmo cortesemente di effettuare nuovamente i test previsti e di sottometterli nella relativa PR.

In caso di ulteriori problemi la invitiamo ad aprire un nuovo ticket.

Grazie.
