### ISSUE TITLE
Mancato accreditamento A1#111EBITSRLXXXX - EBITSRL - SUITESTENSA - 2.1b34.x

### ISSUE THREAD

**Issue by EbitFSE** [ministero-salute/it-fse-support#489]
Buongiorno,
il file errors.json contiene il seguente errore:
{
  "id" : 6,
  "error" : "WII_UNKNOWN_LOG",
  "description" : "WorkflowInstanceID non presente nella collection dei log.Assicurarsi di aver eseguito correttamente la validazione per il wii segnalato"
},

Il workflowID da noi comunicato nei file data.json e report-checklist.xlsx era il seguente:
"workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.97882b29e1e1a8634253aae9af10816b882260dfbc671c1010ee55c69868af42.1dd9958328^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"

Sottoponiamo nuovamente il caso rimuovendo le virgolette e il trattino contestati, chiediamo che vengano presi in considerazione solo i casi per l'accreditamento della Lettera di Dimissione (LDO) e non quelli già validati mesi fa riguardanti la radiologia (RAD).
Grazie
Saluti

**Comment by vigliottim** [comment]
Salve,
è stato riscontrato un disservizio che ha generato l'errore di "WII_UNKNOWN_LOG" causando il mancato accreditamento.
Le chiederemmo cortesemente di effettuare nuovamente i test previsti e di sottometterli nella relativa PR.

In caso di ulteriori problemi la invitiamo ad aprire un nuovo ticket.

Grazie.
