### ISSUE TITLE
Errato OID VPS

### ISSUE THREAD

**Issue by MarcoKnezevichInsiel** [ministero-salute/it-fse-support#49]
buongiorno, 
segnalo un errore nel documento del  [CDA del pronto soccorso](http://www.hl7italia.it/hl7italia_D7/Implementation%20Guide%20CDA%202%20-%20Verbale%20di%20Pronto%20Soccorso%20%28VPS%29), alla riga 480 l'esempio presenta un oid errato:
`2.16.840.1.113883.2.9.2.4.3.2`
invece di
`2.16.840.1.113883.2.9.4.3.2`

il problema è che inserendo l'oid sbagliato, viene passata la validazione dello [schematron](https://github.com/ministero-salute/it-fse-support/blob/main/validazione/schematron/schematron_VPS.sch) perchè la parte relativa è commentata pur essendo il dato (da specifiche) obbligatorio

**Comment by LeonardoAlcaro** [comment]
Buongiorno ,
grazie della segnalazione , si mette in evidenza che la tabella delle convenzioni Header contiene nella colonna valore l'oid corretto ovvero :2.16.840.1.113883.2.9.4.3.2 , solo l'esempio che è appunto un esempio ha la valorizzazione segnalata.
Si dovrebbe prendere di solito in una IG il valore della tabella convenzione Header. Il passaggio del documento da parte dello schematron e' dovuto ad altra problematica che si sta risolvendo ovvero che non c'e' un controllo puntuale sugli OID del path _ClinicalDocument/recordTarget/patientRole/id
