### ISSUE TITLE
Mancato accreditamento A1#111GIOTTOINFOR 

### ISSUE THREAD

**Issue by giottopalermo** [ministero-salute/it-fse-support#490]
Salve,

A seguito della pull request del 28/09/2023 abbiamo ricevuto la risposta per mancato accreditamento con 6 errori analoghi a questo 

```javascript
 {
  "id" : 1,
  "error" : "WII_UNKNOWN_LOG",
  "description" : "WorkflowInstanceID non presente nella collection dei log.Assicurarsi di aver eseguito correttamente la validazione per il wii segnalato"
}
```
L'esecuzione dell'applicativo per la generazione dei casi di test è avvenuto il 28/09/2023 intorno alle 21,30 .

Da parte nostra sembrerebbe tutto corretto. 
Come dobbiamo procedere ?

Cordiali saluti

**Comment by vigliottim** [comment]
Salve,
è stato riscontrato un disservizio che ha generato l'errore di "WII_UNKNOWN_LOG" causando il mancato accreditamento.
Le chiederemmo cortesemente di effettuare nuovamente i test previsti e di sottometterli nella relativa PR.

In caso di ulteriori problemi la invitiamo ad aprire un nuovo ticket.

Grazie.
