### ISSUE TITLE
Mancato accreditamento A1#111LOGO80X00000 - Log80_s.r.l - MEDICAL_80 - 1.0

### ISSUE THREAD

**Issue by Log80-svi** [ministero-salute/it-fse-support#491]
Buongiorno,
per quanto riguarda l'errore "WorkflowInstanceID non presente nella collection dei log. Assicurarsi di aver eseguito correttamente la validazione per il wii segnalato", noi abbiamo verificato di avere inviato i messaggi all'endpoint[ "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation"](https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation), e di avere inserito nel file "data.json" l'id workflow che ci è stato restituito, come per gli altri accreditamenti già fatti.

Per esempio per il caso 6, abbiamo inserito il workflowInstanceId del messaggio inviato il 2023-09-25 12:33:25:

{"traceID":"9c25a39758ff8419","spanID":"9c25a39758ff8419","workflowInstanceId":"2.16.840.1.113883.2.9.2.80.3.1.4.4.d432d578260b3769f32d852d1f1fe3f24f26f5cfbe1cc19af51f5f998e152bfe.741ce9882a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

{
            "id": 6,
            "ts": "2023-09-25T12:33:25Z",
            "traceId": "9c25a39758ff8419",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.d432d578260b3769f32d852d1f1fe3f24f26f5cfbe1cc19af51f5f998e152bfe.741ce9882a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "files": [ "T1_VALIDATION.pdf" ]
},

Vi chiediamo quindi il motivo per cui il workflowInstanceId non sia presente nei vostri log.

Grazie
Stefano

**Comment by vigliottim** [comment]
Salve,
è stato riscontrato un disservizio che ha generato l'errore di "WII_UNKNOWN_LOG" causando il mancato accreditamento.
Le chiederemmo cortesemente di effettuare nuovamente i test previsti e di sottometterli nella relativa PR.

In caso di ulteriori problemi la invitiamo ad aprire un nuovo ticket.

Grazie.
