### ISSUE TITLE
S1#111ONIT0000000 OnitGroup Errore invalid token per chiamate da server cliente

### ISSUE THREAD

**Issue by Fusarolia** [ministero-salute/it-fse-support#492]
Buongiorno
facendo la prova di validazione di un documento da un server di un cliente/regione
otteniamo il seguente errore
{
	"type": "https://govway.org/handling-errors/401/TokenAuthenticationFailed.html",
	"title": "TokenAuthenticationFailed",
	"status": 401.0,
	"detail": "Invalid token",
	"govway_id": "b8a48425-53a6-11ee-8e64-005056ae7395",
	"Hash": "85ed0135cfc9d3bf7725f7e39f64006232b004a8cc49f254523a86dc8832af8f",
}
Ma utilizzando lo stesso messaggio dalle nostre macchine di sviluppo non ci viene restituito nessun errore.
{
	"traceID": "e85fac0399e972b3",
	"spanID": "e85fac0399e972b3",
	"workflowInstanceId": "2.16.840.1.113883.2.9.2.50.4.4.8fb6d88bd2c561c60e29c70928e2f1d10f4cb0bfd484bb08ed8cb285980a8e67.359c5148ce^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
	"Hash": "45aa58d994769b128e6e60e29d7374fb92df445341e52f4bfe67dba41ddfba63",
}

Da che cosa può essere dato la differenza di comportamento?

Attendiamo un riscontro, distinti saluti

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate è emerso che il campo "x5c" dei token utilizzati nella chiamata che va in errore presenta dei carriage return (\r), come mostrato nella seguente immagine: 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/661a60db-018f-4e9c-b199-4406f67ce42b)
La presenza di tali caratteri speciali potrebbe compromettere la decodifica dell'informazione contenuta nel campo. 
Qualora non lo stesse già utilizzando, le suggeriamo di ricorrere al tool _jwt-generator_ scaricabile a questo [link](https://github.com/ministero-salute/it-fse-gtw-tools) la generazione dei token.
Rimaniamo a disposizione in caso avesse bisogno di ulteriori chiarimenti. Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario. Grazie.
