### ISSUE TITLE
Health check Status Actuator - GET /status

### ISSUE THREAD

**Issue by federicolau** [ministero-salute/it-fse-support#494]
Ciao,

sto cercando di richiamare il seguente servizio: **Health check Status Actuator - GET /status**

![image](https://github.com/ministero-salute/it-fse-support/assets/138868941/f0b4f10a-c5c2-43a5-9e28-3056c8547f6f)

ma ottengo la seguente response:

**{"type":"https://govway.org/handling-errors/404/UndefinedOperation.html","title":"UndefinedOperation","status":404,"detail":"Operation undefined in the API specification","govway_id":"459dbfc2-6355-11ee-a4d5-005056ae54fa"}**

La request ha ovviamente un'operazione di GET, dove sto sbagliando?

Grazie.

**Comment by vigliottim** [comment]
Buongiorno, come indicato nel ticket [432](https://github.com/ministero-salute/it-fse-support/issues/432) per conoscere lo stato della transazione dovrebbe invocare o l'endpoint */v1/status/{wii} oppure */v1/status/search/{traceId}. Non è possibile al momento invocare l'endpoint citato sopra, che fornisce in output lo stato del microservizio. Al momento il servizio è riportato nello swagger per vincoli tecnici, in futuro verrà fornita comunicazione nel caso in cui dovesse essere esposto esternamente. Grazie.
