### ISSUE TITLE
Errore nell'avvio dell'ambiente locale it-fse-container-lite

### ISSUE THREAD

**Issue by luco5826** [ministero-salute/it-fse-support#495]
Buongiorno,
Provando a lanciare in locale il `docker-compose.yml` contenuto in `it-fse-container-lite`, ottengo il seguente errore (con container che continuano a riavviarsi senza arrivare ad un punto fisso (le andate a capo sono per leggibilità):
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoPropertiesCFG': 
Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: 
Could not resolve placeholder 'MONGO_DBNAME' in value "${MONGO_DBNAME}"
```

Ho copiato il file `.env-sample` e rinominato in `.env` e provato anche con il troubleshooting indicato nel readme (riscaricare le immagini e riavviare i container)

**Comment by LucaRogledi** [comment]
Buongiorno,
Potrebbe cortesemente provare ad eseguire i seguenti comandi per la pulizia e messa in esecuzione dei container?

- `docker-compose down -v`

- `docker-compose up`

Grazie

**Comment by IStacchiotti** [comment]
Grazie per il feedback. Potrebbe descrivere cortesemente l'output che ottiene eseguendo il comando riportato in documentazione a questo link: https://github.com/ministero-salute/it-fse-gtw-test-container/blob/main/it-fse-container-lite/README.md#troubleshooting, indicando quali container continuano a riavviarsi?

**Comment by luco5826** [comment]
Riporto l'output
```
CONTAINER ID   NAMES                                                    IMAGE                              STATE
ad853a0462f4   it-fse-container-lite-it-fse-gtw-status-manager-1        it-fse-ms-runner                   created
636f9f638680   it-fse-container-lite-it-fse-gtw-dispatcher-1            it-fse-ms-runner                   created
80a09fc91e31   it-fse-container-lite-it-fse-gtw-fhir-mapping-engine-1   it-fse-ms-runner                   created
cfab26f10f9f   it-fse-container-lite-it-fse-gtw-status-check-1          it-fse-ms-runner                   created
aabd1b8cc162   it-fse-container-lite-it-fse-gtw-validator-1             it-fse-ms-runner                   created
1f423ebe874d   it-fse-container-lite-zookeeper-1                        confluentinc/cp-zookeeper:latest   running
829cfc2a003f   it-fse-container-lite-kafka-ui-1                         provectuslabs/kafka-ui             running
0077d5340c1c   it-fse-container-lite-kafka-1                            confluentinc/cp-kafka:6.2.1        running
8aaa690f9a57   it-fse-container-lite-mongo-1                            mongo:4.2                          running
532b986818fd   it-fse-container-lite-it-fse-gtw-rules-manager-1         it-fse-ms-runner                   running
2fb3f908d043   it-fse-container-lite-it-fse-srv-log-ingestion-1         it-fse-ms-runner                   restarting
```

Come detto prima, i container che si alternano in `restarting` sono gli ultimi due, ovvero `it-fse-container-lite-it-fse-gtw-rules-manager-1` e `it-fse-container-lite-it-fse-srv-log-ingestion-1`. 
Non riesco a includere un output che li includa entrambi perchè non ripartono esattamente nello stesso momento e quindi dando il comando fornito al link, ogni tanto è in stato restarting solo log-ingestion, ogni tanto solo rules-manager.

**Comment by luco5826** [comment]
Buongiorno, ci sono aggiornamenti riguardo a questo issue?
Se non riusciamo a creare l'ambiente in locale non possiamo iniziare l'integrazione con FSE a meno di non andare direttamente sull'ambiente di test online

**Comment by vigliottim** [comment]
Buongiorno, sono state rilasciate delle fix correttive.
Le chiediamo gentilmente di procedere seguendo le istruzioni riportate di seguito:

1. Rimuovere completamente tutti i vecchi container docker
2. Aggiornare la repository "it-fse-gtw-test-container" attraverso "git pull"
3. Eseguire nuovamente la procedura di installazione con ambiente pulito

Se dovesse riscontrare ulteriori problemi non esiti a contattarci. Grazie.

**Comment by luco5826** [comment]
Continua a non funzionare, l'errore è diverso. Ora è:

```
org.springframework.data.mongodb.UncategorizedMongoDbException: 
Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='mongoadmin', source='fse', password=<hidden>, mechanismProperties=<hidden>}; 
nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='mongoadmin', source='fse', password=<hidden>, mechanismProperties=<hidden>}
```

Ho visto la fix, ma non può risolvere il problema cambiare il nome del DB da "fse" a "FSE_GTW", il file `mongo-init.js` punta ancora al DB vecchio (e cambiandolo continua a non funzionare).

Tutte le variabili di Spring in [questa cartella](https://github.com/ministero-salute/it-fse-gtw-rules-manager/tree/main/src/main/resources) (prendiamo rules-manager come esempio) puntano al vecchio DB

**Comment by vigliottim** [comment]
Buongiorno,
le chiediamo nuovamente di accertarsi di aver eliminato tutto ciò che concerne la vecchia configurazione come i _container_, i _volumi_ e le _immagini_ generate.
Le chiediamo, inoltre, di verificare che lo script _mongo-init.sh_ sul suo sistema adotti come terminatore di riga una codifica LF invece che CRLF.
Le alleghiamo uno screen dell'attuale configurazione up e running.
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/d3c37c31-4a31-4397-926f-1f3d1b952190)
Se avesse ancora problemi, ci alleghi il log completo di avvio dell'immagine di mongo-db su docker.

**Comment by vigliottim** [comment]
Buongiorno. Non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
