### ISSUE TITLE
Accreditamento A1#111EBITSRLXXXX - EBITSRL

### ISSUE THREAD

**Issue by EbitFSE** [ministero-salute/it-fse-support#496]
Buongiorno,
in riferimento all'issue "Mancato accreditamento A1#111EBITSRLXXXX - EBITSRL - SUITESTENSA - 2.1b34.x #489", riguardante il disservizio che ha generato l'errore di "WII_UNKNOWN_LOG, nella stessa issue ci veniva chiesto di sottoporre nuovamente i casi di test, cosa che avevamo già fatto dopo quell'errore.
Dobbiamo comunque sottometterli nuovamente?
Grazie
Saluti

**Comment by IStacchiotti** [comment]
Buongiorno @EbitFSE, le confermiamo che la vostra ultima pr, la #863, è attualmente in lavorazione e che non sono richieste al momento attività da parte vostra. Seguiranno aggiornamenti in merito all'esito delle verifiche via email.
Pertanto procediamo alla chiusura del presente ticket, ma rimaniamo a disposizione nel caso fossero necessari ulteriori chiarimenti.
Grazie
