### ISSUE TITLE
Esito dell'invio file report

### ISSUE THREAD

**Issue by DATASOFTNA** [ministero-salute/it-fse-support#498]
Buonasera, 
Il 2 Ottobre scorso ho effettuato l'ultimo aggiornamento del file report, dopo che mi era stato richiesto di modificarlo.
Da allora non ho ricevuto nessuna segnalazione, quindi non so se il file e' stato ritenuto corretto.
Devo attendere una mail di conferma ?

Inoltre nella cartella home, potrei sapere cosa significa questo messaggio 
This branch is **19 commits** ahead of and **72 commints** behind ministero-salute/it-fse-accreditamento:main 
e se devo attivare la richiesta di pull che compare sotto il pulsante Contribute.

Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario. Grazie.
