### ISSUE TITLE
Schematron LDO riga 545 messaggio ERRORE 85

### ISSUE THREAD

**Issue by giuseppe-fasulo** [ministero-salute/it-fse-support#5]
Il messaggio di errore è errato perchè la sezione controllata è quella delle Consulenze e non quella degli Esami eseguiti durante il ricoveo

ERRORE-85| Sezione **Esami eseguiti durante il ricovero**: se presente section/entry/observation/participant/participantRole/playingEntity/name deve contenere gli elementi "given" e "family" </assert>

**Comment by zukka77** [comment]
grazie anche per questa segnalazione.

**Comment by gndibiase** [comment]
Grazie della nota, si tratta di un refuso e la sezione corretta è, come indicato, quella della Consulenza. Provvederemo a sostituire il nome corretto della sezione nel messaggio. L’errore non incide sulla validazione, non è presente infatti sul controllo vero e proprio ma solo sulla descrizione dello stesso al livello del messaggio dell’errore.
