### ISSUE TITLE
Error1027 Type expected 'object', found 'string' \nFrom: body.requestBody.<#/components/schemas/ValidationCDAReqDTO

### ISSUE THREAD

**Issue by ruggj** [ministero-salute/it-fse-support#50]
"govway_id": "d11292e5-9269-11ed-b21d-005056ae54fa"

Testando il servizio di validazione di CDA2 con SoapUI ottieniamo  il seguente errore:
```
{"type": "https://govway.org/handling-errors/400/InvalidRequestContent.html["](https://govway.org/handling-errors/400/InvalidRequestContent.html%22),
  "title": "InvalidRequestContent",
  "status": 400,
  "detail": "Request content not conform to API specification: Validation error(s) :\nbody.requestBody: Type expected 'object', found 'string'. (code: 1027)\nFrom: body.requestBody.<#/components
[dump_request.txt](https://github.com/ministero-salute/it-fse-support/files/10402097/dump_request.txt)
/schemas/ValidationCDAReqDTO>.<type>\nbody.requestBody: Field 'activity' is required. (code: 1026)\nFrom: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.<required>\n",
  "govway_id": "ed0d9a76-9264-11ed-b21d-005056ae54fa"
}
```

**Comment by ruggj** [comment]
****
[dump_request.txt](https://github.com/ministero-salute/it-fse-support/files/10402131/dump_request.txt)
![SoapUI_Configuration](https://user-images.githubusercontent.com/122540135/212084264-07d69d52-ceb6-41a1-a239-7ef9186f9fe3.png)

**Comment by pFonziSogei** [comment]
Salve, dovrebbe essere un problema noto di SOAPUI. Potrebbe fare un test utilizzando postman?

**Comment by ruggj** [comment]
Ciao, abbiamo provato anche con una request ad Postman allegando il .pem di autenticazione ma ci ritorna un errore di autenticazione. allego Configurazione più errore.Grazie

**Comment by ruggj** [comment]
![PostmanConfiguration](https://user-images.githubusercontent.com/122540135/212108797-3df95662-b0a7-4ace-8723-f9d1971e0f3e.JPG)


![RequestResponse_Postman](https://user-images.githubusercontent.com/122540135/212108832-ac500462-8a4b-4875-a235-ed8830ffa57b.JPG)

**Comment by zukka77** [comment]
il certificato e la sua chiave vanno messi come client certificate non come CA
