### ISSUE TITLE
Anomalia aggiornamento metadati

### ISSUE THREAD

**Issue by gabriele-stenico-gpi** [ministero-salute/it-fse-support#500]
Buongiorno,
abbiamo implementato la chiamata di aggiornamento metadati secondo le specifiche [definite qui](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#71-request)

Mandando una request di test però abbiamo la seguente risposta:

`{
"traceID" : "776c43eadea23313",
"spanID" : "776c43eadea23313",
"type" : "/msg/generic-error",
"title" : "Errore generico.",
"detail" : "Required request part 'file' is not present",
"status" : 400,
"instance" : ""
}`

Ho notato che nell'[esempio di messaggio](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#711-esempio-messaggio-di-richiesta), che c'è sotto alla definizione dei campi della request, è presente un file come ultimo parametro: `-F 'file=@CDA_OK.pdf;type=application/pdf'` .

La cosa sembra strana perché per aggiornare i metadati del documento mandiamo già l'id del documento, per quale motivo devo ricaricare anche il referto?

Mi potete far sapere?

Grazie
Gabriele

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Potrebbe riportare la richiesta completa che ha usato per chiamare il servizio?
Nell'esempio è erroneamente riportato il file pdf, ma come indicato nella sezione 7.1 Tabella 25, il servizio non accetta alcun file in input. 
Grazie.

**Comment by gabriele-stenico-gpi** [comment]
Ho sbagliato io il content-type, avevo messo multipart/form-data al posto di application/json
