### ISSUE TITLE
Mancato accreditamento A1#111HITECHSPAXX - Hi.Tech - PS3 - 3.0.0

### ISSUE THREAD

**Issue by marcodellavall3** [ministero-salute/it-fse-support#502]
`Salve,
Con la presente si comunica il mancato superamento dei seguenti test [24] per il servizio [validazione/pubblicazione] del Fornitore [A1#111HITECHSPAXX] - Vendor:[Hi.Tech] - ID: [PS3] - Version: [3.0.0] - Sha: [bcf7471d80252f8f67813716504d6d0499146eb8] in data odierna.
`
Salve,
vorrei chiedere spiegazioni su questo mancato accreditamento.
I campi segnalati nell'error.json mi sembrano correttamente compilati cosa stiamo sbagliando ? 
Grazie in anticipo del supporto.
[errors.json](https://github.com/ministero-salute/it-fse-support/files/12912838/errors.json)
[VPS_CT1.pdf](https://github.com/ministero-salute/it-fse-support/files/12912839/VPS_CT1.pdf)
[data.json](https://github.com/ministero-salute/it-fse-support/files/12912840/data.json)
[report-checklist.xlsx](https://github.com/ministero-salute/it-fse-support/files/12912841/report-checklist.xlsx)

**Comment by vigliottim** [comment]
Buongiorno, ai fini dell'accreditamento il dominio da seguire per la corretta valorizzazione dei campi presenti nell'XML  è quello riportato negli excel disponibili a questo link: [Test Case Accreditamento](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case). In particolare, dalle analisi effettuate risulta che non è stato adottato l'ID corretto per la section _Modalità di trasporto_. La invitiamo a riprovare sostituendo **ID="Modalità_di_Trasporto"** a ID="Modalita_di_Trasporto". Inoltre, per velocizzare il processo di accreditamento, le facciamo presente che può ricorrere al _gtw-certifier_ per simulare i risultati delle verifiche e correggere eventuali errori. Restiamo a disposizione per chiarimenti. Grazie.

**Comment by marcodellavall3** [comment]
Buongiorno,
la ringrazio per il riscontro.
Nella issue  #417  mi avevate indicato di utilizzare la dicitura Modalita_di_Trasporto  a seguito di un errore ricevuto tentando di validare il documento,se imposto ID="Modalità_di_Trasporto"  il GTW mi restituisce errore come indicato nella issue, se setto l'ID con Modalita_di_Trasporto non supera l'accreditamento, come mi devo regolare?

**Comment by marcodellavall3** [comment]
Sono riuscito ad identificare il problema, l'applicativo non teneva conto della codifica utilizzata prima di iniettare il CDA nel PDF.
Il ticket può essere chiuso.

**Comment by vigliottim** [comment]
Grazie per il gentile riscontro. Procediamo alla chiusura del presente ticket e rimaniamo a disposizione per ulteriori richieste di supporto.
