### ISSUE TITLE
Errore durante la conversione da json a oggetto it.finanze.sanita.fse2.ms.gtw.dispatcher.dto.request.ValidationCDAReqDTO

### ISSUE THREAD

**Issue by luco5826** [ministero-salute/it-fse-support#503]
Come da titolo, ottengo questo messaggio in fase di invio di uno dei PDF di esempio forniti da voi.
L'oggetto ottenuto in risposta è
```json
{
    "traceID": "54ca74bb0e58c282",
    "spanID": "54ca74bb0e58c282",
    "type": "/msg/mandatory-element",
    "title": "Campo obbligatorio non presente.",
    "detail": "Errore durante la conversione da json a oggetto it.finanze.sanita.fse2.ms.gtw.dispatcher.dto.request.ValidationCDAReqDTO",
    "status": 400,
    "instance": "/request-missing-field",
    "workflowInstanceId": "UNKNOWN_WORKFLOW_ID"
}
```

Ma analizzando la richiesta, trovo il campo `requestBody` correttamente formattato:
```
Content-Type: application/json; charset=utf-8
Content-Disposition: form-data; name=requestBody

{"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VERIFICA"}
```

**Comment by IStacchiotti** [comment]
Buonasera @luco5826,

Riportiamo di seguito quanto emerso dalle analisi preliminari:

1. Per quanto riguarda la section dedicata al file pdf allegato alla richiesta, la invitiamo a controllare la valorizzazione del campo filename, che andrebbe popolato con il nome del file pdf (comprensivo di estensione) con il cda iniettato.

      _--548698d1-f7b8-4707-b1f6-0e09a9718904
      Content-Type: application/pdf
      Content-Disposition: form-data; name="file"; **filename**="file"_

2. Relativamente alla section con la request body, la invitiamo ad omettere la parte in grassetto, non prevista.

      _--548698d1-f7b8-4707-b1f6-0e09a9718904
      Content-Type: application/json; charset=utf-8
      Content-Disposition: form-data; name="requestBody"**; filename="requestBody"**
      {"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VERIFICA"}_

Nel caso in cui possa essere utile, la rimandiamo alla [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#311-messaggio-di-richiesta-esempio-validation-con-attachment). Rimaniamo a disposizione per chiarimenti, grazie.

**Comment by luco5826** [comment]
Grazie della risposta, 
rimuovere il campo `filename="requestBody"` ha effettivamente risolto il problema, veniva aggiunto in automatico dalla libreria che utilizziamo per le richieste HTTP
