### ISSUE TITLE
 Validazione. Parametro Activity

### ISSUE THREAD

**Issue by marcodevanna** [ministero-salute/it-fse-support#506]
Buongiorno,
abbiamo un dubbio relativo al parametro Activity, nella chiamata di Validazione.
Può essere valorizzato con "Validation" o "Verifica", a seconda se la validazione sia rispettivamente seguita da una pubblicazione o meno.
Esiste una qualche regola per la gestione di un eventuale transitorio in cui una Regione non sia in grado di effettuare Pubblicazioni ma solo Validazioni?

**Comment by IStacchiotti** [comment]
Buongiorno, il servizio di validazione va invocato con il parametro activity valorizzato con "Validation" nel caso in cui l'intenzione sia quella di pubblicare in seguito il documento (entro 5 giorni); viceversa, eseguendo la validazione con "Verifica" non sarà possibile procedere con la pubblicazione dello stesso.
Nel caso in cui sia necessario un transitorio perché possiate predisporvi a richiamare la pubblicazione, segnaliamo che, a transitorio concluso, sarà necessario svolgere le pubblicazioni rimandate: per farlo, sarà possibile pubblicare i documenti validati entro 5 giorni; oppure, nel caso di documenti per cui la validazione è scaduta, occorrerà invocare validazione e pubblicazione (eventualmente anche tramite il servizio validate-and-create che esegue validazione e pubblicazione contestuale).

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario. Grazie.
