### ISSUE TITLE
Documenti pubblicati dopo più di 5 giorni dalla creazione

### ISSUE THREAD

**Issue by marcodevanna** [ministero-salute/it-fse-support#507]
Buongiorno,
abbiamo un dubbio relativo a come gestire il caso in cui un documento pubblicato dopo più di 5 giorni dalla sua creazione.
In tal caso avremmo un workflowInstanceId più vecchio di 5 giorni che determina lo scarto di un documento quando se ne effettua la pubblicazione.
Tuttavia ci sono casi in cui per motivi organizzativi si è scelto di non pubblicare subito un documento, rendendolo di conseguenza subito disponibile al cittadino sul proprio FSE. Ad esempio referti prodotti nell'ambito di un ricovero, sono resi visibili e quindi pubblicabili solo dopo la dimissione, che può avvenire ben più di 5 giorni dopo la creazione dei referti stessi.
In questi casi, con le attuali regole, nessun referto sarebbe pubblicabile. 

Come possiamo gestire questo caso d'uso?

**Comment by IStacchiotti** [comment]
Buon pomeriggio, 
Se per questioni di processo, avete la necessità di pubblicare oltre la scadenza prevista per la validazione (5 giorni), dovreste rieseguire la validazione e poi la pubblicazione, oppure in alternativa richiamare il servizio di validazione e pubblicazione contestuale.
Vi segnaliamo inoltre che, come indicato a questo [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#1334-event-code), esiste un tipo di oscuramento che oscura il documento all'assistito, il P98: pertanto, se i vostri processi lo consentono, potreste anche validare e pubblicare con il P98 subito e poi, una volta dimesso l'assistito, fare l'update dei metadati rimuovendo questo tipo di oscuramento.
Rimaniamo a disposizione per chiarimenti, grazie

**Comment by marcodevanna** [comment]
Buon pomeriggio,
quindi un documento creato in data T può essere rivalidato in data T+5 e poi successivamente pubblicato?
Il controllo quindi è solo sulla data di generazione del workflowInstanceId?

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario. Grazie.















































































Buongiorno
