### ISSUE TITLE
errore eliminazione documento

### ISSUE THREAD

**Issue by robyc2023** [ministero-salute/it-fse-support#508]
Buongiorno stiamo compilando il documento di collaudo per l'integrazione con FSE attraverso il middleware di Regione lazio.
Da un paio di giorni abbiamo problemi con l'annullamento del documento inviato. 
l'errore restituito è il seguente:
"type":"/msg/eds-error","title":"Eds error.","detail":"Document cannot be found on the Server FHIR","status":404,"instance":"/msg/eds-document-missing"

Le precedenti risposte ad issues simili non hanno risolto il mio problema.
E' possibile controllare se la pubblicazione del documento originario è andata a buon fine?

Riporto le tracce delle richieste effettuate:
**Pubblicazione:**
requestBody:
{"workflowInstanceId":"2.16.840.1.113883.2.9.2.120110.4.4.618fdb8a4100aab08c81d5e6b21e0767ebb330abea2fad065f820124446fea08.25174c7142^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
"mode":"ATTACHMENT",
"tipologiaStruttura":"Ospedale",
"identificativoDoc":"2.16.840.1.113883.2.9.2.120.4.4^2023000000411.1",
"identificativoRep":"2.16.840.1.113883.2.9.2.120.4.5.120110",
"tipoDocumentoLivAlto":"VRB",
"assettoOrganizzativo":"AD_PSC106",
"tipoAttivitaClinica":"CON",
"identificativoSottomissione":"2.16.840.1.113883.2.9.2.120.4.3.20231019092822997766"}

con la seguente risposta:
{"traceID":"c7a4dd43b914df0c",
"spanID":"c7a4dd43b914df0c",
"warning":"",
"workflowInstanceId":"2.16.840.1.113883.2.9.2.120110.4.4.618fdb8a4100aab08c81d5e6b21e0767ebb330abea2fad065f820124446fea08.25174c7142^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

in allegato il documento pdf:
[doc_2023000000411.1.zip](https://github.com/ministero-salute/it-fse-support/files/13040796/doc_2023000000411.1.zip)

**Eliminazione**
identifier di eliminazione: 
/v1/documents/2.16.840.1.113883.2.9.2.120.4.4^2023000000411.1

risposta:
{"traceID":"008bad3b1018569c","spanID":"008bad3b1018569c","type":"/msg/eds-error","title":"Eds error.","detail":"Document cannot be found on the Server FHIR","status":404,"instance":"/msg/eds-document-missing"}

Grazie

**Comment by IStacchiotti** [comment]
Buon pomeriggio,

Come si evince dai log di seguito, ottenuti richiamando il servizio status con il workflowInstanceId fornito, l'errore riscontrato sull'eliminazione del documento dipende dal fatto che la pubblicazione non era andata a buon fine (nello stato delle transazioni si evidenzia un errore bloccante nella fase EDS_WORKFLOW). Rimaniamo a disposizione per eventuali ulteriori richieste di chiarimento, grazie.

```
{
    "traceID": "3ac2563a30f99058",
    "spanID": "755da59d5f550e8c",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2023-10-19T07:28:22.188+00:00",
            "eventStatus": "SUCCESS",
            "subject": "CLVRRT73A45D612C^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "120",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120110.4.4.618fdb8a4100aab08c81d5e6b21e0767ebb330abea2fad065f820124446fea08.25174c7142^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "ac1879f226ad5e51",
            "issuer": "integrity:S1#120000000000XX",
            "expiringDate": "2024-10-18T07:28:22.198+00:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2023-10-19T07:28:25.502+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.120.4.4^2023000000411.1",
            "subject": "CLVRRT73A45D612C^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "CON",
            "organizzazione": "120",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120110.4.4.618fdb8a4100aab08c81d5e6b21e0767ebb330abea2fad065f820124446fea08.25174c7142^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "c7a4dd43b914df0c",
            "issuer": "integrity:S1#120000000000XX",
            "expiringDate": "2024-10-18T07:28:25.532+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2023-10-19T07:28:25.599+00:00",
            "eventStatus": "SUCCESS",
            "message": "{\"esito\":true,\"errorMessage\":\"Regime di mock abilitato\",\"traceID\":\"fd29b12f0beb483b\",\"spanID\":\"fd29b12f0beb483b\"}",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120110.4.4.618fdb8a4100aab08c81d5e6b21e0767ebb330abea2fad065f820124446fea08.25174c7142^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2024-10-18T07:28:25.632+00:00"
        },
        {
            "eventType": "SEND_TO_EDS",
            "eventDate": "2023-10-19T07:28:25.696+00:00",
            "eventStatus": "SUCCESS",
            "message": "{\"esito\":true}",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120110.4.4.618fdb8a4100aab08c81d5e6b21e0767ebb330abea2fad065f820124446fea08.25174c7142^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2024-10-18T07:28:25.706+00:00"
        },
        {
            "eventType": "EDS_WORKFLOW",
            "eventDate": "2023-10-19T07:28:35.755+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "Error: failed to publish bundle",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120110.4.4.618fdb8a4100aab08c81d5e6b21e0767ebb330abea2fad065f820124446fea08.25174c7142^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2024-10-18T07:28:35.769+00:00"
        }
    ]
}
```

**Comment by robyc2023** [comment]
Grazie del chiarimento,
è possibile sapere da cosa dipende l'errore bloccante nella pubblicazione visto che la validazione ha avuto successo?

**Comment by pbazzoli** [comment]
Anch'io ho avuto lo stesso problema, quando ieri ho richiesto un servizio status per questo workflowInstanceId

```
2.16.840.1.113883.2.9.2.120.4.4.d1013566bf131182faa5ff76eecdd381dfe6aa2d21cdee64bfbf0a83b0aecbed.9dabe32e24^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
```

e ho ricevuto lo stesso messaggio di errore per l'eventType "EDS_WORKFLOW".

E anche l'eliminazione mi dà lo stesso errore ""Document cannot be found on the Server FHIR""

[Il documento usato per il test](https://github.com/ministero-salute/it-fse-support/files/13051850/document.zip)


Grazie per l'attenzione

**Comment by vigliottim** [comment]
Buongiorno, vi chiediamo di riprovare e informarci qualora il problema persista. Grazie.

**Comment by robyc2023** [comment]
Salve,
confermo che adesso le pubblicazioni e le successive eliminazioni vanno a buon fine (verificate con il servizio di status.
Grazie.

**Comment by rg-08** [comment]
Buongiorno,
potete confermare che l'eliminazione funziona correttamente?
Abbiamo fatto un test poco fa e otteniamo l'errore indicato nell'apertura della issue:
{
  "traceID" : "7986c53ce2dea80f",
  "spanID" : "7986c53ce2dea80f",
  "type" : "/msg/eds-error",
  "title" : "Eds error.",
  "detail" : "Document cannot be found on the Server FHIR",
  "status" : 404,
  "instance" : "/msg/eds-document-missing"
}

Verificando la transazione di pubblicazione effettivamente otteniamo l'errore:
{
  "traceID" : "f82ecee6dfff8925",
  "spanID" : "5250f717b17b0f98",
  "transactionData" : [
    {
      "eventType" : "VALIDATION",
      "eventDate" : "2023-12-07T13:50:22.940+00:00",
      "eventStatus" : "SUCCESS",
      "subject" : "PSTNNZ76P18E783T^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "organizzazione" : "120",
      "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.0c8b4804f5e16b3cbe761745d2e4fe93175c78e66a4a368cebb8ba575afd2c8e.f971d16d8b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId" : "d19dc06c11b9846c",
      "issuer" : "integrity:S1#120000000000XX",
      "expiringDate" : "2024-12-06T13:50:22.950+00:00"
    },
    {
      "eventType" : "REPLACE",
      "eventDate" : "2023-12-07T13:50:37.114+00:00",
      "eventStatus" : "SUCCESS",
      "identificativoDocumento" : "2.16.840.1.113883.2.9.2.120.4.4^0BECA2FC-4DCE-2B96-E063-959FEA0A82E0",
      "subject" : "PSTNNZ76P18E783T^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "tipoAttivita" : "ERP",
      "organizzazione" : "120",
      "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.0c8b4804f5e16b3cbe761745d2e4fe93175c78e66a4a368cebb8ba575afd2c8e.f971d16d8b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId" : "e85b66e6948eda6c",
      "issuer" : "integrity:S1#120000000000XX",
      "expiringDate" : "2024-12-06T13:50:37.123+00:00"
    },
    {
      "eventType" : "SEND_TO_INI",
      "eventDate" : "2023-12-07T13:50:37.144+00:00",
      "eventStatus" : "SUCCESS",
      "message" : "{\"esito\":true,\"errorMessage\":\"Regime di mock abilitato\",\"traceID\":\"b4b0ad5871325c95\",\"spanID\":\"b4b0ad5871325c95\"}",
      "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.0c8b4804f5e16b3cbe761745d2e4fe93175c78e66a4a368cebb8ba575afd2c8e.f971d16d8b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate" : "2024-12-06T13:50:37.230+00:00"
    },
    {
      "eventType" : "SEND_TO_EDS",
      "eventDate" : "2023-12-07T13:50:37.307+00:00",
      "eventStatus" : "BLOCKING_ERROR",
      "message" : "500 : \"{\"traceID\":\"b23991ae213173aa\",\"spanID\":\"fc91364791f0c505\",\"type\":\"/err/server\",\"title\":\"Server error\",\"detail\":\"Generic error while call EDS Srv Query ep :org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : \\\"{\\\"traceID\\\":\\\"b23991ae213173aa\\\",\\\"spanID\\\":\\\"ae1622100c6adc49\\\",\\\"type\\\":\\\"/err/server\\\",\\\"title\\\":\\\"Server error\\\",\\\"detail\\\":\\\"The id string is malformed\\\",\\\"status\\\":500,\\\"instance\\\":\\\"/internal\\\"}\\\"\",\"status\":500,\"instance\":\"/internal\"}\"",
      "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.0c8b4804f5e16b3cbe761745d2e4fe93175c78e66a4a368cebb8ba575afd2c8e.f971d16d8b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate" : "2024-12-06T13:50:37.371+00:00"
    }
  ]
}

Ma questo errore lo otteniamo praticamente per tutti i test di pubblicazione che abbiamo eseguito.

**Comment by vigliottim** [comment]
Buongiorno, le confermiamo che non abbiamo evidenza di anomalie per il servizio di eliminazione. La invitiamo a riprovare e aprire un nuovo ticket nel caso avesse bisogno di supporto. Grazie.
