### ISSUE TITLE
Accreditamento soluzione IE-OPERA

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#509]
Buongiorno,
volevamo notificare il caricamento completato dei test case per la soluzione IE-OPERA :

https://github.com/ministero-salute/it-fse-accreditamento/pull/919

questa pull request contiene LDO,VPS,RSA.

Grazie

**Comment by vigliottim** [comment]
Buongiorno, le confermiamo che la pull-request è stata presa in carico. Seguiranno aggiornamenti via e-mail. Grazie.
