### ISSUE TITLE
Caso di test RAD_KO_11

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#51]
eseguendo il caso di test RAD_KO_11, viene restituito un errore semantico e non terminologico.

**CASO DI TEST 11**
_Si prende in esame il caso in cui la tipologia di accesso che ha determinato la prestazione (documentationOf) venga valorizzato con codice errato, non appartenente quindi al dizionario associato, generando un errore terminologico (se il valore assegnato non deriva dal sistema di codifica utilizzato)._ 

questo l'elemento del CDA utilizzato:

`<documentationOf typeCode="DOC">
    <serviceEvent moodCode="EVN">
	    <code code="XXX" codeSystem="2.16.840.1.113883.2.9.5.1.4" codeSystemName="ActCode" />
	    <effectiveTime value="20230108091023+0100" />
    </serviceEvent>
</documentationOf>`

questa la risposta:
 
`{
  "spanID": "32aabce0f792f9b4",
  "status": "422",
  "detail": "[ERRORE-40| L'elemento ClinicalDocument/documentationOf/serviceEvent deve contenere l'elemento code e DEVE valorizzare il suo attributo code con uno dei seguenti valori: 'PROG'|'DIR'|'RAD_PROG|'RAD_DIR' ]",
  "title": "Errore semantico.",
  "traceID": "32aabce0f792f9b4",
  "type": "/msg/semantic",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.130202.4.4.d5b6f4892274d92b43d5faa5752ecf0eb6fcf6dcb043bb20e4bd6de01fefab26.b8457e4460^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}`

giustamente non passa la validazione dello schematron
come eseguire il test?

**Comment by LeonardoAlcaro** [comment]
Buon pomeriggio,
l'esecuzione del test, essendo un test KO e' coerente in quanto viene restituito l'errore sch ovvero ERRORE-40| L'elemento ClinicalDocument/documentationOf/serviceEvent deve contenere l'elemento code e DEVE valorizzare il suo attributo code con uno dei seguenti valori: 'PROG'|'DIR'|'RAD_PROG|'RAD_DIR'

**Comment by alessandropassamonti** [comment]
Grazie,
alla fine è lo stesso risultato del test KO 23 con la differenza che il codice è valido all'interno del dizionario.

**CASO DI TEST 23**
_Si prende in esame il caso in cui la tipologia di accesso che ha determinato la prestazione (documentationOf) venga valorizzata con codice previsto dal sistema di codifica utilizzato, ma non accettabile dallo schematron cioè con un valore diverso da quelli ammessi che corrispondono a ‘Accesso Programmato’, ’Accesso Diretto’, ’Accesso Programmato Radiologia’, ‘Accesso Diretto Radiologia’. Così facendo, viene generato un errore semantico._

`<documentationOf typeCode="DOC">
		<serviceEvent moodCode="EVN">
			<code code="EL30" codeSystem="2.16.840.1.113883.2.9.5.1.4" codeSystemName="ActCode" />
			<effectiveTime value="20230108091023+0100" />
		</serviceEvent>
	</documentationOf>
`
