### ISSUE TITLE
Richiesta Chiarimenti per Test Case KO

### ISSUE THREAD

**Issue by sandroaresu23** [ministero-salute/it-fse-support#512]
Buongiorno,
vi scrivo in merito al mancato superamento dei seguenti test [37, 6, 369, 7, 29, 8, 9] per il servizio [validazione/pubblicazione] del Fornitore [A1#111DEDALUSXXX] - Vendor:[Regione_Sardegna] - ID: [ADTWEB_SISaR_RAS] - Version: [20.14] - Sha: [9afd3bac6307dc8ff5844dd35f29d01066b1d46c].
In particolare mi riferisco al mancato accreditamento per i casi di test KO [29, 37], in cui abbiamo ricevuto come esito quanto segue:

{
"id" : 29,
"error" : "TEST_KO_NON_SUPERATO",
"description" : "Test KO non superato. Assicurarsi che il traceId fornito abbia restituito in fase di validazione un errore bloccante."
}, {
"id" : 37,
"error" : "TEST_KO_NON_SUPERATO",
"description" : "Test KO non superato. Assicurarsi che il traceId fornito abbia restituito in fase di validazione un errore bloccante."
}

Le response ricevute dal servizio sono rispettivamente per il test 29 e 37 le seguenti:

"id" : 29
{
"traceID": "31f638c32b22aeb4",
"spanID": "31f638c32b22aeb4",
"type": "/msg/jwt-validation",
"title": "Campo token JWT non valido.",
"detail": "Il campo purpose_of_use non è valorizzato",
"status": 403,
"instance": "/jwt-mandatory-field-missing",
"workflowInstanceId": "UNKNOWN_WORKFLOW_ID"
}
Per cui nella checklist di accreditamento era richiesto esattamente questo: Al fine di rendere non valido il token è necessario non valorizzare nel JWT il campo "purpose_of_use".

"id" : 37
{
"traceID": "e09785018ee672e9",
"spanID": "e09785018ee672e9",
"type": "/msg/jwt-validation",
"title": "Campo token JWT non valido.",
"detail": "Il campo action_id non è corretto",
"status": 403,
"instance": "/jwt-mandatory-field-malformed",
"workflowInstanceId": "UNKNOWN_WORKFLOW_ID"
}
Per cui nella checklist di accreditamento era richiesto esattamente questo: Al fine di rendere non valido il token è necessario valorizzare il campo "action_id" con la stringa "TEST" (valore non ammesso).

Possiamo avere chiarimenti in merito?
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno @sandroaresu23, in primo luogo le chiediamo cortesemente di confermarci che, in fase di validazione, è stato richiamato il **Gateway online**, come da specifiche riportate a questo [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway). Grazie

**Comment by sandroaresu23** [comment]
Sì, confermo. Si tratta dello stesso gateway utilizzato per tutti e 24 i test

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, il presente ticket viene chiuso. Si può procedere alla riapertura nel caso in cui abbia bisogno di ulteriore supporto. Grazie.
