### ISSUE TITLE
Invalid path durante il checkout - Impossibile caricare ulteriori file oltre il data.json

### ISSUE THREAD

**Issue by Reev83** [ministero-salute/it-fse-support#513]
Buongiorno,

ho tentato di creare come da istruzioni un fork del repository e creare la nostra sottocartella per poter caricare i risultati per l'accreditamento.

Al momento l'unica operazione che sono riuscito a fare è il caricamento sulla mia branch del data.json.

Ho tentato invano di caricare il file excel con i report dall'interfaccia web. Il file rimane in caricamento senza dare ulteriori informazioni.
Ho successivamente provato a installare github desktop, dove ho clonato con successo il repository ma tentando di spostarmi sulla mia branch (patch-1) mi viene restituito questo errore :

![278064060-621a618d-5931-4273-80d3-509eb277d6b1](https://github.com/ministero-salute/it-fse-support/assets/129532249/a78abb22-ba35-4eba-ba00-10b6279eb6dd)

Grazie per il supporto,

cordiali saluti
Paolo

**Comment by IStacchiotti** [comment]
Buongiorno @Reev83, 
Le confermiamo che la pull request #937, contenente al momento unicamente il file data.json, ci risulta corretta.
Le suggeriamo in primo luogo di riprovare, tramite interfaccia web, a caricare un file txt vuoto nella PR, al fine di verificare la procedura di upload con un file di minima dimensione.
Ci faccia sapere se anche in questo caso l'errore persiste, grazie

**Comment by Reev83** [comment]
Buongiorno, grazie per la rapida risposta.

Ho provato a caricare da web un .txt come suggerito ma permane il problema (ho riprovato anche con il .xslx per completezza)

![image](https://github.com/ministero-salute/it-fse-support/assets/129532249/66690713-7814-465c-809c-8940845cf56e)

Qui rimane la voce "uploading 1 of 1 files" (negli scorsi giorni l'ho lasciato lì anche per alcune decine di minuti e lo stato non cambiava).

Correttamente se provo a premere commit changes mi notifica di aggiungere almeno 1 file : 

![image](https://github.com/ministero-salute/it-fse-support/assets/129532249/38bf9149-c960-4a6b-9d68-f0636a36f7cd)

Purtroppo è la prima volta che uso questo strumento quindi non so bene come muovermi.

Grazie per il supporto.

**Comment by IStacchiotti** [comment]
Grazie per il riscontro. I lunghi tempi di upload ci fanno pensare ad una connessione lenta. Potrebbe eseguire uno speed test per verificarla ed eventualmente provare a sostituirla?
Se il problema persiste ancora, potrebbe provare a chiudere la pr in questione, la #937 e ad aprirne una nuova, ripetendo la procedura che ha usato per il caricamento del file data.json. Ci faccia sapere, grazie

**Comment by Reev83** [comment]
I test di connessione interna sono ok, non ho riscontrato problemi.
Ho riprovato come consigliato a ricreare tutto da zero, ci dovrebbe essere una nuova PR #948 creata poco fa.

Grazie del supporto
