### ISSUE TITLE
Problema in pubblicazione

### ISSUE THREAD

**Issue by nspazzoli** [ministero-salute/it-fse-support#514]
Salve,

ho publlicato un documento ed ho avuto risposta http=201.

Provando il servizio di recupero ottengo però il seguente dettaglio di risposta:
[pubblicazione.json](https://github.com/ministero-salute/it-fse-support/files/13251733/pubblicazione.json)

Sembra però che la pubblicazione in realtà abbia incontrato un problema sulla EDS. 

Inoltre come ci si deve comportare in cancellazione e sostituizione? Affinchè un documento possa essere cancellato o sostituito occorre attendere che la pubblicaizone si a effettivamente completa? Ed esempio la cancellazione del documento sopra non riesce perché il documento non risulta pubblicato.

Grazie

**Comment by vigliottim** [comment]
Buonasera, le chiediamo di confermarci di aver usato il metodo POST per la pubblicazione. Inoltre, le confermiamo che affinché cancellazione e sostituzione abbiano successo, deve andare a buon fine la pubblicazione. Grazie.

**Comment by nspazzoli** [comment]
Salve,

confermo di aver usato una POST come indicato da specifiche (e credo che altrimenti non avrei avuto un HTTP201 in risposta).
Il fatto che in questo momento la pubblicazione non si concluda per il problema su EDS, fa si che la seccessiva richiesta di cancellazione riceva invece la seguente risposta:
HTTP 404
{
	"traceID": "2f4a86d92aa3bb0c",
	"spanID": "2f4a86d92aa3bb0c",
	"type": "/msg/eds-error",
	"title": "Eds error.",
	"detail": "Document cannot be found on the Server FHIR",
	"status": 404,
	"instance": "/msg/eds-document-missing"
}
Se ho capito bene quindi, uan richiesta di cancellazione/sostituzione viene accettata solo se il documento in cancella/sostituzione ha consluso il percorso di pubblicazione (in sostanza la rispota 201 alla richiesta di pubblicazione non è sufficiente).

Potrei avere qualche problema nei casi in cui la richiesta di cancellazione/sostituzione mi arriva subito a ridosso della pubblicazione, poiché devo attendere un esisto del GTW.
Tutto questo si complica da fatto che non sappiamo di quanti step si compone il percorso di pubblicazione (che forse in futuro potrebbero anche cambiare) ed entrarne nel merito dei vari stati.

**Comment by IStacchiotti** [comment]
Buongiorno @nspazzoli,

Confermiamo quanto da lei riportato nel messaggio precedente. Come si evince dal sequence riportato in documentazione a questo [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#22-processo-di-autenticazione3), il servizio di pubblicazione si compone di due parti, una sincrona (il cui esito viene restituito nella response dal sistema) e una asincrona (il cui esito si deduce dal servizio status, da voi correttamente interrogato).
Pertanto, sostituzione e cancellazione non andranno a buon fine se anche la parte asincrona di pubblicazione non si sarà conclusa con successo.

Per consentirci di procedere con le verifiche, le chiederemmo cortesemente la risposta completa restituita in seguito alla chiamata di pubblicazione che è andata in errore su EDS.
La ringraziamo per la collaborazione.

**Comment by nspazzoli** [comment]
Buongiorno,

ho riprovato un nuovo invio.
Ottengo la risposta seguente:
 RISPOSTA PUBBLICAZIONE
 HTTP 201,  {"traceID":"b023193179a33421","spanID":"b023193179a33421","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.80.3.1.4.4.ac7d4a9f51e313fc58d0c395642b5961f67ac8d219ce987d8119a86a2ce3b6ec.706d126e62^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"} 

Grazie

**Comment by LucaRogledi** [comment]
Buonasera,
Dalle verifiche svolte è emerso che l'errore nella parte asincrona della pubblicazione è dovuto alla mancanza dell'id valorizzato in corrispondenza dell'elemento CDA2 asOrganizationPartOf, come mostrato di seguito.

As is (dalla riga 248 del cda utilizzato):

```
<asOrganizationPartOf>
	<wholeOrganization>
		<id root="2.16.840.1.113883.2.9.4.1.1" extension="080105"/>  <!-- dovrei introdurre il nuovo controllo -->
	</wholeOrganization>
</asOrganizationPartOf>
```

To be:

```
<asOrganizationPartOf>
	<id root="2.16.840.1.113883.2.9.4.1.1" extension="080105"/>  <!-- da valorizzare opportunamente -->
	<wholeOrganization>
		<id root="2.16.840.1.113883.2.9.4.1.1" extension="080105"/> 
	</wholeOrganization>
</asOrganizationPartOf>

```

Restiamo a disposizione per ulteriori chiarimenti. Grazie.

**Comment by nspazzoli** [comment]
Buonasera,

confermo che la correzione fa fatto completare la pubblicazione.
Però quindi è un problema che doveva essere rilevato nella fase di validazione, giusto? (apro altra issue?)

Inoltre faccio presente che nella risposta per sapere tutti i dettagli degli stati la sezione con eventType='EDS_WORKFLOW' non è più presente. E' corretto? E' previsto solo in caso di errore?

Grazie

**Comment by vigliottim** [comment]
Buongiorno, non ha ricevuto l'errore in fase di validazione poiché inerente alla trasformata FHIR che viene calcolata durante il processo asincrono. Se non compaiono errori nella _status_ relativi alla pubblicazione, questo è indice che la pubblicazione è avvenuta con successo. Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Chiudiamo il presente. Abbiamo ricevuto l'issue [517](https://github.com/ministero-salute/it-fse-support/issues/517) e riceverà risposta appena possible. Grazie.
