### ISSUE TITLE
Informazioni richiesta accreditamento LDO EBIT Srl

### ISSUE THREAD

**Issue by EbitFSE** [ministero-salute/it-fse-support#515]
Buongiorno,
in riferimento alla PR "Accreditamento LDO EBIT Srl https://github.com/ministero-salute/it-fse-accreditamento/pull/946", abbiamo visto che è stato fatto il merge ed è in stato closed.
Vorremmo capire in quale stato si trova ora e se dobbiamo fare ulteriori attività per l'accreditamento LDO.
Grazie
Cordiali Saluti

**Comment by IStacchiotti** [comment]
Buonasera, dovreste aver ricevuto una mail il 31/10, all'indirizzo comunicato nell'EuSurvey, con l'esito delle elaborazioni sulla PR in questione. In particolare, via email vi sono stati segnalati alcuni errori rilevati in maniera automatica durante le analisi: dovreste aprire una nuova PR con cui sottomettere le correzioni indicate. Grazie

**Comment by EbitFSE** [comment]
Grazie, abbiamo visto la mail e avremmo un dubbio su come procedere:
avendo eseguito 3 richieste di accreditamento distinte, una per RAD, una per LDO e una per RSA, come possiamo sottomettere solo i casi relativi a LDO? 
è possibile avere un contatto telefonico?
grazie 
Buona serata

**Comment by IStacchiotti** [comment]
Buongiorno @EbitFSE,

dagli ultimi test sottomessi (riferimento PR #946), ci risulta che le tipologie documentali trattate siano unicamente LDO e RAD, mentre non ci risulta che siano stati compilati dei casi di test per RSA all'interno della checklist fornita.

Specifichiamo inoltre che, se state svolgendo l'accreditamento per un unico applicativo (EBITSRL/SUITESTENSA/2.1B34.X) che gestirà tutti i cda in questione, allora dovreste compilare una sola checklist per tutti i cda, come state già facendo. Per correggere i casi di test segnalati, sarà sufficiente aprire una nuova pull request, per l'aggiornamento dei file che è stato necessario correggere.

In aggiunta segnaliamo che, come riportato in documentazione a questo [link](https://github.com/ministero-salute/it-fse-accreditamento#nuova-tipologia-documentale-per-applicativo-gi%C3%A0-presente-nella-lista-dei-software-convalidati), nel momento in cui si aggiunge una nuova tipologia documentale in seguito al conseguimento della validazione per una diversa tipologia di documento, occorre ripetere la procedura per tutte le tipologie documentali. Per velocizzare il processo di accreditamento pertanto, consigliamo di sottomettere la checklist compilata per tutti i cda gestiti dall'applicativo per cui si intende accreditarsi. 

Non è disponibile un canale telefonico tra i quelli di supporto previsti, ma è possibile ricevere supporto tramite i canali preposti, Slack (canale #fse) e [GitHub](https://github.com/ministero-salute/it-fse-support). 

Rimaniamo a disposizione per chiarimenti. 
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, il presente ticket viene chiuso come risolto. Si può procedere alla riapertura in caso contrario. Grazie.

**Comment by EbitFSE** [comment]
abbiamo provveduto a modificare i file creando una PR per LDO, RSA e RAD:
Accreditamento EBIT Srl per LDO, RSA e re-invio casi RAD #976
