### ISSUE TITLE
Errore in Pubblicazione "EDS_WORKFLOW" Error: failed to publish bundle"

### ISSUE THREAD

**Issue by Fusarolia** [ministero-salute/it-fse-support#516]
Buongiorno,
ho già fatto varie prove modificando il messaggio di pubblicazione seguendo issue precedenti, ma continuo ad avere errore  "EDS_WORKFLOW". Potette indicarmi il problema che c'è nel cda?
Inserisco richiesta status.
Attendo un vostro cortese riscontro, distinti saluti

{
	"traceID": "4cbdc3bdb185f22e",
	"spanID": "51b9b625369977f3",
	"transactionData": [
		{
			"eventType": "VALIDATION",
			"eventDate": "2023-11-07T16:11:16.682+00:00",
			"eventStatus": "SUCCESS",
			"subject": "RSPRPN80A01A390V^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"organizzazione": "060",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.1506bb6ce2320bef4bc040be26be9f4e9d0d85767f9a193d41383380d1c97325.b5cc01fa7b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "2621116c6d2e3a1a",
			"issuer": "integrity:S1#111ONIT0000000",
			"expiringDate": "2024-11-06T16:11:16.695+00:00"
		},
		{
			"eventType": "PUBLICATION",
			"eventDate": "2023-11-07T16:11:20.253+00:00",
			"eventStatus": "SUCCESS",
			"identificativoDocumento": "2.16.840.1.113883.2.9.2.60.4.4^20230000000135_82593-5_ONIT",
			"subject": "RSPRPN80A01A390V^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"tipoAttivita": "ERP",
			"organizzazione": "060",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.1506bb6ce2320bef4bc040be26be9f4e9d0d85767f9a193d41383380d1c97325.b5cc01fa7b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "a111b40d6c23da4a",
			"issuer": "integrity:S1#111ONIT0000000",
			"expiringDate": "2024-11-06T16:11:20.283+00:00"
		},
		{
			"eventType": "SEND_TO_INI",
			"eventDate": "2023-11-07T16:11:20.288+00:00",
			"eventStatus": "SUCCESS",
			"message": "{\"esito\":true,\"errorMessage\":\"Regime di mock abilitato\",\"traceID\":\"148f015688a8a98e\",\"spanID\":\"148f015688a8a98e\"}",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.1506bb6ce2320bef4bc040be26be9f4e9d0d85767f9a193d41383380d1c97325.b5cc01fa7b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"expiringDate": "2024-11-06T16:11:20.317+00:00"
		},
		{
			"eventType": "SEND_TO_EDS",
			"eventDate": "2023-11-07T16:11:20.602+00:00",
			"eventStatus": "SUCCESS",
			"message": "{\"esito\":true}",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.1506bb6ce2320bef4bc040be26be9f4e9d0d85767f9a193d41383380d1c97325.b5cc01fa7b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"expiringDate": "2024-11-06T16:11:20.611+00:00"
		},
		{
			"eventType": "EDS_WORKFLOW",
			"eventDate": "2023-11-07T16:11:20.633+00:00",
			"eventStatus": "BLOCKING_ERROR",
			"message": "Error: failed to publish bundle",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.1506bb6ce2320bef4bc040be26be9f4e9d0d85767f9a193d41383380d1c97325.b5cc01fa7b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"expiringDate": "2024-11-06T16:11:20.733+00:00"
		}
	]
}

**Comment by LucaRogledi** [comment]
Buonasera,
Per consentirci di procedere con le verifiche, le chiederemmo cortesemente la risposta completa restituita in seguito alla chiamata di pubblicazione che è andata in errore su EDS.
La ringraziamo per la collaborazione.

**Comment by Fusarolia** [comment]
Vi inoltro la risposta ottenuta a seguito della riposta
{
	"traceID": "a111b40d6c23da4a",
	"spanID": "a111b40d6c23da4a",
	"warning": "",
	"workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.1506bb6ce2320bef4bc040be26be9f4e9d0d85767f9a193d41383380d1c97325.b5cc01fa7b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
	"status": "201"
}

**Comment by Fusarolia** [comment]
Buon giorno
non ho avuto riscontri è possibile avere qualche informazione

Grazie

**Comment by vigliottim** [comment]
Buongiorno, è stata rilasciata una fix correttiva. Potrebbe gentilmente riprovare? Grazie.

**Comment by Fusarolia** [comment]
Buongiorno, fatto prova. Ora non si verifica più il problema. Se non errore non viene fatto più lo step EDS_WORKFLOW. Vedi risposta del tracciato. 
{
	"traceID": "358c6d5494f4671a",
	"spanID": "61da56494637d834",
	"transactionData": [
		{
			"eventType": "VALIDATION",
			"eventDate": "2023-11-13T10:32:12.821+00:00",
			"eventStatus": "SUCCESS",
			"subject": "RSPRPN80A01A390V^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"organizzazione": "060",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.bd49185b2f10f4c9f5a720652d902e135b69a2d474e0bae5917f6a127769a955.88109ea8a9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "93ce73fdf7fe0931",
			"issuer": "integrity:S1#111ONIT0000000",
			"expiringDate": "2024-11-12T10:32:12.832+00:00"
		},
		{
			"eventType": "PUBLICATION",
			"eventDate": "2023-11-13T10:32:21.987+00:00",
			"eventStatus": "SUCCESS",
			"identificativoDocumento": "2.16.840.1.113883.2.9.2.60.4.4^20230000000136_82593-5_ONIT",
			"subject": "RSPRPN80A01A390V^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"tipoAttivita": "ERP",
			"organizzazione": "060",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.bd49185b2f10f4c9f5a720652d902e135b69a2d474e0bae5917f6a127769a955.88109ea8a9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "93d7a4053ad34725",
			"issuer": "integrity:S1#111ONIT0000000",
			"expiringDate": "2024-11-12T10:32:21.998+00:00"
		},
		{
			"eventType": "SEND_TO_INI",
			"eventDate": "2023-11-13T10:32:22.071+00:00",
			"eventStatus": "SUCCESS",
			"message": "{\"esito\":true,\"errorMessage\":\"Regime di mock abilitato\",\"traceID\":\"27ab76d04143a2d8\",\"spanID\":\"27ab76d04143a2d8\"}",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.bd49185b2f10f4c9f5a720652d902e135b69a2d474e0bae5917f6a127769a955.88109ea8a9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"expiringDate": "2024-11-12T10:32:22.100+00:00"
		},
		{
			"eventType": "SEND_TO_EDS",
			"eventDate": "2023-11-13T10:32:22.171+00:00",
			"eventStatus": "SUCCESS",
			"message": "{\"esito\":true}",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.bd49185b2f10f4c9f5a720652d902e135b69a2d474e0bae5917f6a127769a955.88109ea8a9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"expiringDate": "2024-11-12T10:32:22.219+00:00"
		}
	]
}

**Comment by Fusarolia** [comment]
Avrei bisogno di un chiarimento facendo la cancellazione del documento ho verificato che mi viene restituito un workflowInstanceId diverso dalla validazione e pubblicazione. E' corretto?

Il doc pubblicato ha 2.16.840.1.113883.2.9.2.60.4.4.bd49185b2f10f4c9f5a720652d902e135b69a2d474e0bae5917f6a127769a955.88109ea8a9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
mentre la cancellazione mi restituisce come workflowInstanceId
be091e835997631971f28444a2495192d92162d7c866158f958cfd0fe09a427d.b9ff75c9d1^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

**Comment by vigliottim** [comment]
Buongiorno, confermiamo che in caso di cancellazione il workflowInstanceId ha un valore diverso rispetto a quello di validazione e pubblicazione. 
Procediamo alla chiusura della issue riguardante l'errore in pubblicazione precedente dal momento che non si presenta più in seguito alla fix. Rimaniamo a disposizione in caso di ulteriori richieste di supporto. Grazie.
