### ISSUE TITLE
Validazione: campo id non rilevato

### ISSUE THREAD

**Issue by nspazzoli** [ministero-salute/it-fse-support#517]
Buongiorno,

come da issue #514 credo ci sia un problema in validazione.

Come fa vostra rispsota dovrebbe mancare il controllo sul campo
```
<asOrganizationPartOf>
	<id root="2.16.840.1.113883.2.9.4.1.1" extension="080105"/>  <!-- MANCA CONTROLLO SU QUESTO ??-->
	<wholeOrganization>
		<id root="2.16.840.1.113883.2.9.4.1.1" extension="080105"/> 
	</wholeOrganization>
</asOrganizationPartOf>
```

Omettando il campo id la validazione viene accettata, ma poi fallisce la successiva pubblicazione. 
Grazie

**Comment by marcodevanna** [comment]
Buongiorno,
non è chiaro da cosa derivi l'obbligatorietà dall'id all'interno dell'elemento asOrganizationPartOf.
Riporto lo stralcio di interesse della specifica CDA del referto di Laboratorio:

_
In serviceEvent/performer/assignedEntity/representedOrganization, inoltre, viene gestito il laboratorio di analisi che ha prodotto il risultato delle analisi che sono documentate nel Referto di Medicina di Laboratorio stesso quindi in representedOrganization/id viene riportato l’identificativo dell’entità laboratorio
[...]
Nel caso in cui il laboratorio faccia parte di una organizzazione/struttura (ad esempio l’ASL oppure la struttura privata a cui appartiene il laboratorio), per indicare l’identificativo del laboratorio assegnato da questa organizzazione/struttura l’elemento di riferimento è serviceEvent/performer/assignedEntity/representedOrganization/asOrganizationPartOf/id.
Per indicare l’organizzazione di cui il laboratorio fa parte (ad esempio l’ASL oppure la struttura privata a cui appartiene il laboratorio), l’elemento di riferimento è serviceEvent/performer/assignedEntity/representedOrganization/asOrganizationPartOf/wholeOrganization in cui PUÒ essere indicato l’identificativo dell’organizzazione wholeOrganization/id e/o il nome dell’organizzazione wholeOrganization/name._

In nessun passaggio è indicata l'obbligatorietà dell'elemento asOrganizationPartOf/id.

Il laboratorio in cui è stato effettuato l'esame è identificato nell'elemento representedOrganization/id, secondo ad esempio codifica STS11. L'Azienda Sanitaria di cui il Lab fa parte, può andare nella WholeOrganization ma non vedo obblighi nel replicare l'id del laboratorio in asOrganizationPartOf/id.

Di fondo, resta il dubbio sul perchè l'assenza di un elemento ritenuto obbligatorio (a torto o a ragione) garantisca la validazione positiva e il fallimento dei controlli deferred di pubblicazione.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso fosse necessario ulteriore supporto. Grazie.
