### ISSUE TITLE
Dubbio in cancellazione

### ISSUE THREAD

**Issue by nspazzoli** [ministero-salute/it-fse-support#518]
Buongiorno,

dopo aver corretto come issue #514 (già chiusa) sono riuscito a cancellare corretatmente il documento.
Il dubbio è: in una successiva richiesta ti dipo query, non c'è nessun eventType che mi confermi lo stato 'cancellato' del documento.
Mi confermate che non esiste un EventType dedicato alle informaizoni di cancellazione?

Questa informazione sarebbe comoda (oltre per un mero fatto di completezza delle informazioni) soprattutto nei casi di network error o di timeout. 

Riprovando infatti la cancellazione, ottengo, correttamente) un 
> HTTP 404, 
>  {"traceID":"1c47a8b54baae00a","spanID":"1c47a8b54baae00a","type":"/msg/eds-error","title":"Eds error.","detail":"Document cannot be found on the Server FHIR","status":404,"instance":"/msg/eds-document-missing"}
> 
Quindi in questo caso questa risposta significa "documento cancellato", ma è fondamentalemte identica alla risposta alla richiesta di cancellazione di un doc mai esistito o la cui pubblicazione è andata in errore in qualche passaggio.
Giusto?

Infine: dalla documentazione non mi è chiaro:
1) quanti siano gli eventType che mi posso aspettare
2) i valori possibili degli eventStatus: SUCCESS, BLOCKIN_ERROR (etc) e loro siginificato

**Comment by IStacchiotti** [comment]
Buongiorno @nspazzoli, per accertare l'esito della cancellazione è possibile interrogare a valle il servizio status. Se è presente nella response l'eventStatus "SUCCESS" in corrispondenza degli eventType "EDS_DELETE" e "INI_DELETE", allora la cancellazione precedente è andata a buon fine. Specifichiamo infatti che "SUCCESS" indica che non si sono originati errori,
BLOCKING_ERROR viceversa indica che si è originato un errore bloccante.

**Comment by nspazzoli** [comment]
Salve,

riposto l'esito della chiamta "SErvizio recupero stato per WorkflowInstanceID" 
HTTP 200
{
	"traceID": "98247e959503f5a8",
	"spanID": "8d0ce056befab161",
	"transactionData": [
		{
			"eventType": "VALIDATION",
			"eventDate": "2023-11-07T16:28:46.969+00:00",
			"eventStatus": "SUCCESS",
			"subject": "ACBDEF62S28H501M^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"organizzazione": "080",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.99cfdc45d063969cd9e9bb4f81bb66dd4562fc49f343dee0dff1a8f559a96952.9a362296c6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "d0d295e9d2664e55",
			"issuer": "integrity:S1#111080XXXXXXXX",
			"expiringDate": "2024-11-06T16:28:46.980+00:00"
		},
		{
			"eventType": "PUBLICATION",
			"eventDate": "2023-11-07T16:32:06.500+00:00",
			"eventStatus": "SUCCESS",
			"identificativoDocumento": "2.16.840.1.113883.2.9.2.80.4.4^105LAB1699374484082SKMRGZ",
			"subject": "ACBDEF62S28H501M^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"tipoAttivita": "ERP",
			"organizzazione": "080",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.99cfdc45d063969cd9e9bb4f81bb66dd4562fc49f343dee0dff1a8f559a96952.9a362296c6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "3b96dc0cdef329ce",
			"issuer": "integrity:S1#111080XXXXXXXX",
			"expiringDate": "2024-11-06T16:32:06.530+00:00"
		},
		{
			"eventType": "SEND_TO_INI",
			"eventDate": "2023-11-07T16:32:06.658+00:00",
			"eventStatus": "SUCCESS",
			"message": "{\"esito\":true,\"errorMessage\":\"Regime di mock abilitato\",\"traceID\":\"606ce88676bba79b\",\"spanID\":\"606ce88676bba79b\"}",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.99cfdc45d063969cd9e9bb4f81bb66dd4562fc49f343dee0dff1a8f559a96952.9a362296c6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"expiringDate": "2024-11-06T16:32:06.740+00:00"
		},
		{
			"eventType": "SEND_TO_EDS",
			"eventDate": "2023-11-07T16:32:06.862+00:00",
			"eventStatus": "SUCCESS",
			"message": "{\"esito\":true}",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.99cfdc45d063969cd9e9bb4f81bb66dd4562fc49f343dee0dff1a8f559a96952.9a362296c6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"expiringDate": "2024-11-06T16:32:06.874+00:00"
		},
		{
			"eventType": "EDS_WORKFLOW",
			"eventDate": "2023-11-07T17:00:00.006+00:00",
			"eventStatus": "SUCCESS",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.99cfdc45d063969cd9e9bb4f81bb66dd4562fc49f343dee0dff1a8f559a96952.9a362296c6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"expiringDate": "2024-11-06T17:00:00.035+00:00"
		}
	]
}

non vedo traccia della "EDS_DELETE" o "INI_DELETE", eppure la cancellazioen aveva avuto esito  200... tanto più che se riprovo ad inviarla ottengo un 404.
Grazie

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Per ricevere una risposta con gli eventi "EDS_DELETE" e "INI_DELETE" in questione, occorre effettuare la chiamata di status tramite WorkflowInstanceID. Evidenziamo che il WorkflowInstanceID da utilizzare nella chiamata di status deve essere il valore ricevuto in risposta dal esecuzione con successo del servizio di delete. 
Restiamo a disposizione per ulteriori chiarimenti. Grazie.

**Comment by nspazzoli** [comment]
Buonasera,

Grazie della precisazione che dalla documentazione non avevo colto.

Ma comunque trovo un caso critico. Se per qualche problema nella chiamata di delete (esempio in timeout, errore di rete, ecc .) non ricevo il workflowid da usare. Non posso quindi chiamare ed avere i dettagli del servizio, Giusto?

**Comment by LucaRogledi** [comment]
Buongiorno,
In caso di problemi di timeout o problemi di rete suggeriamo di procedere chiamando il servizio di status per valutare la situazione utilizzando il workflowInstanceId o il traceID, se disponibile.
In caso di mancanza di workflowInstanceId/traceID per accedere ai dettagli del servizio di delete, suggeriamo di richiamare il nuovamente servizio di delete, che restituirà un messaggio di errore con codice 404 "Document cannot be found on the Server FHIR" nel caso in cui la richiesta precedente sia andata a buon fine.
Nel caso opposto in cui il servizio di delete non sia andato a buon fine, con una nuova richiesta sarà possibile ritentare la cancellazione.
Restiamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto riscontri, il presente ticket viene chiuso. Si può procedere alla riapertura nel caso in cui abbia bisogno di ulteriore supporto. Grazie.
