### ISSUE TITLE
AuthorizationContentDeny Errore 403

### ISSUE THREAD

**Issue by AndreaNannicini** [ministero-salute/it-fse-support#519]
Buongiorno,
abbiamo qualche problema con le chiamate all'endpoint per i test pre accreditamento fase 1
per FSE.

Il sistema risponde con 403
[nanno_rad.pdf](https://github.com/ministero-salute/it-fse-support/files/13296269/nanno_rad.pdf)

Vi allego secondo  le indicazioni avute su slack:
File .pdf contenente il file CDA.xml prelevato tra gli esempi di supporto ed allegato al pdf.

La Response alla chiamata è la seguente:
<Response [403]>
{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"ba71b2c0-7e24-11ee-91c5-005056ae54fa"}
<bound method Response.json of <Response [403]>>

Sempre in allegato i due JWT generati dalla nostra procedura.
[jwt1.txt](https://github.com/ministero-salute/it-fse-support/files/13296294/jwt1.txt)
[jwt2.txt](https://github.com/ministero-salute/it-fse-support/files/13296295/jwt2.txt)

Non sembra un errore sintattico.
Vi chiedo cortesemente aiuto per risolvere la problematica.

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate è emerso che il campo "sub" utilizzato nei token non risulta correttamente valorizzato. 
La invitiamo a correggerlo come indicato di seguito: 
_As is:_ 'NNNNDR78E01D612S^^^&amp;2.16.840.1.113883.6.1&amp;ISO' -> _To be:_ 'NNNNDR78E01D612S^^^
&2.16.840.1.113883.2.9.4.3.2&ISO'
Può consultare la relativa documentazione al seguente link:
https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt
Restiamo a disposizione per ulteriori chiarimenti.

**Comment by AndreaNannicini** [comment]
Abbiamo cambiato il valore del campo _sub_ nel JWT1 secondo le indicazioni ma il response è sempre lo stesso:

<Response [403]>
{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"c088e79c-7e38-11ee-82d6-005056ae7395"}
<bound method Response.json of <Response [403]>>

Il file iniettato è sempre lo stesso:
[nanno_rad.pdf](https://github.com/ministero-salute/it-fse-support/files/13297813/nanno_rad.pdf)


i due JWT utilizzati sono i seguenti:
----> Valore JWT 1 <-------
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1YyI6WyJNSUlGYlRDQ0ExV2dBd0lCQWdJVUlxYW01OU1mZ0pOSi9BalhNcjJFWUcycm9NTXdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekV3TWpZd09ESTVNREphRncweU5qRXdNall3T0RJNU1ERmFNRzR4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVI4d0hRWURWUVJoREJaRFJqcEpWQzFRVWs5V1FWZ3dNRmd3TUZnd01EQlpNUjB3R3dZRFZRUUREQlJUTVNNeE1URkRUMDVUVDFKYVNVOVBSRTFZV0RDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVNTWGtlUW9lOFlXYkNLT1gvTFI4MkZuSzQzQnBjU1hGa0NXMUlCVm9Na0JoMVF1YkNSR004YW4wUmh3a2FOTHRITzhHTTZjUmsvYkhGVExqSDczSU01UGZZa3d0cmtmQWFDcGx5Z2ptMjdNaXo2eTVmUWZaa29rTFVqN3NBbHZhbGg0L3hOU0pHQTVYOUdsVzJNSHB0QWx1OHRuMEtWRXJKcGJGSTdqQ3RGOWNsUFRnc0JFdTdWRXlBbXdRc1kwMTVpNmxCNU1oMVpiN1FBcktiWlJiS1VVZGlZaUNXWWQxMXBMNlNBcG9QMEkyUTh4QVVoZU9xcFAvT1AzMldlOURoWkVuaDU5ck1EK05yWiszb1pmV3hjNFBUTHZjQ1pwTHJadVpLTkYvNGJEbHQzS1FaTzBvTUx4VzEwRjNJbGNpS05xNkdwekh1Q3gwODNVMjZtMmw4Q0F3RUFBYU9DQVJnd2dnRVVNQjhHQTFVZEl3UVlNQmFBRkJZNXFSb0ZpYmNQTGJJMTdjSUptc1VEZ3lJL01CSUdBMVVkSUFRTE1Ba3dCd1lGSzB3ZEFRc3dnYTBHQTFVZEh3U0JwVENCb2pDQm42Q0JuS0NCbVlhQmxtaDBkSEJ6T2k4dlkyRnpiMmRsYVhOMmFXd3VjMjluWldrdWFYUXZaV3BpWTJFdmNIVmliR2xqZDJWaUwzZGxZbVJwYzNRdlkyVnlkR1JwYzNRL1kyMWtQV055YkNacGMzTjFaWEk5UTA0bE0wUkRRU3ROYVc1cGMzUmxjbThyWkdWc2JHRXJVMkZzZFhSbEsxUmxjM1FsTWtOUEpUTkVUV2x1YVhOMFpYSnZLMlJsYkd4aEsxTmhiSFYwWlNVeVEwTWxNMFJKVkRBZEJnTlZIUTRFRmdRVUVMc3c1ZWNKa2RoYTNMTllqemcwbCswbG5oMHdEZ1lEVlIwUEFRSC9CQVFEQWdaQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQXdkMGxMajJoWjJEV2V1bmlXL00vOUxWWGlhWFJFRHkrenFoRk9iMzBGNHJMZEVZcUFWSG5seUhJWVVERkUvQkRxUE1ka0NlSSswRHhsbVRHbzUrTER4L21PTWtTZW92RlJUb2wwZXR1R3J2RFBKS244Mlc2bXBWNkJTSXovMFh4U1Q1aUZPYUhROUZjV1pWN0dxOEl5K1VIUXVMaWlJckhaQ1YvQmFlMFVlLzltQzZWQS9LOFUxU3BZcjRJWEJBYk1wa3RKa0pHRjRVZ3FVNE84K2U4QXhBRmNqQ3NYTmYyZ1JQOVlmS1I4Qk1TZFlxN09namtQdVFwNEhCSEtWWWRITGNwaUthT1pybS9LMFQxR3ZGK1BhUmp2OUtuV0E0STRvNU1hNFB6Z0d1M2VqUmxjdlVIVG16bkd0UmVPZ01zcUdBZ1lKaHc5VkZRL2RDaXFRYWpDeXdnSlhuVlBEZjhILzNLK1FUNk4rSlA0ajJaVHZtMVVuM2FWRnl0ZTI5TXEvZFpmVVJNUXBOelF0cFhjWkk4M1dmNUwxT1F2QWhNbjhScUxSV1dvMWJKZkNQNlFwS29KUTVhUXFlS3hsOUlnZzFxVDdNYUJFSkJkYVVRaUd5K2dJNUZjdUlxV2t3em1vWVl3OVZsYThoSnpLMElSMzdjS04zYVlZNzRsblFKdmZNaTFVcUdwSFdCVTFMWVExSFpGc2IvOGdraVljankzUnIxNWxRK2ROMDFtbTVrNEZpaWpGRUkyNWN5S0ZSbVoyODVCd3VodXQ1TnNKM1p3S1U2R2lpRTFtRThuSlBmeE82ajZPTnVhNmsxaVlMTGk2RzAwUU5MUFJPWWpPT0VWVG1PaGlGeDgvK3JLRWJHVlVGb2VXL21WbEpRUnJCbTZtekVaZkVtT3VBPT0iXX0.eyJpc3MiOiJhdXRoOlMxIzExMUNPTlNPUlpJT09ETVhYIiwiaWF0IjoxNjk5NDUzNzEyLCJleHAiOjE2OTk0NTQzMTIsImp0aSI6MTIzNDU2LCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJzdWIiOiJOTk5ORFI3OEUwMUQ2MTJTXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08ifQ.kaRNAs0nGzihqadIrC5uV1wRzM4DPBr0S4CMi6uKotKpJR4dsPDthc9FgVwFMMMNW7e_GlQC-lhBBruJtcysjOcMsnTPP5ykTUynrYL-FwtQ-10djzu506RQxYCaoywULLP1FYEs5KD5khQfcSphvNBB7MkulxWc-NUZQPFzmyb29vXa3tfApSggw6ccZ79q_Rs8U33WS1X-5M-RPyGpMWQPExzIAlgmjPgxeNwZkw99hQqHhwmthroOiRxx_hmTgNJ76zw1zpVDwYip9jNRYJlxGxQmysaNiyB9DA-FkNJNATYgPNuA_C9-dZ4PQHkxPrgMpNEQcQOy0CpjW8P_XA
#####################
----> Valore JWT 2 <-------
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1YyI6WyJNSUlGYlRDQ0ExV2dBd0lCQWdJVUlxYW01OU1mZ0pOSi9BalhNcjJFWUcycm9NTXdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekV3TWpZd09ESTVNREphRncweU5qRXdNall3T0RJNU1ERmFNRzR4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVI4d0hRWURWUVJoREJaRFJqcEpWQzFRVWs5V1FWZ3dNRmd3TUZnd01EQlpNUjB3R3dZRFZRUUREQlJUTVNNeE1URkRUMDVUVDFKYVNVOVBSRTFZV0RDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVNTWGtlUW9lOFlXYkNLT1gvTFI4MkZuSzQzQnBjU1hGa0NXMUlCVm9Na0JoMVF1YkNSR004YW4wUmh3a2FOTHRITzhHTTZjUmsvYkhGVExqSDczSU01UGZZa3d0cmtmQWFDcGx5Z2ptMjdNaXo2eTVmUWZaa29rTFVqN3NBbHZhbGg0L3hOU0pHQTVYOUdsVzJNSHB0QWx1OHRuMEtWRXJKcGJGSTdqQ3RGOWNsUFRnc0JFdTdWRXlBbXdRc1kwMTVpNmxCNU1oMVpiN1FBcktiWlJiS1VVZGlZaUNXWWQxMXBMNlNBcG9QMEkyUTh4QVVoZU9xcFAvT1AzMldlOURoWkVuaDU5ck1EK05yWiszb1pmV3hjNFBUTHZjQ1pwTHJadVpLTkYvNGJEbHQzS1FaTzBvTUx4VzEwRjNJbGNpS05xNkdwekh1Q3gwODNVMjZtMmw4Q0F3RUFBYU9DQVJnd2dnRVVNQjhHQTFVZEl3UVlNQmFBRkJZNXFSb0ZpYmNQTGJJMTdjSUptc1VEZ3lJL01CSUdBMVVkSUFRTE1Ba3dCd1lGSzB3ZEFRc3dnYTBHQTFVZEh3U0JwVENCb2pDQm42Q0JuS0NCbVlhQmxtaDBkSEJ6T2k4dlkyRnpiMmRsYVhOMmFXd3VjMjluWldrdWFYUXZaV3BpWTJFdmNIVmliR2xqZDJWaUwzZGxZbVJwYzNRdlkyVnlkR1JwYzNRL1kyMWtQV055YkNacGMzTjFaWEk5UTA0bE0wUkRRU3ROYVc1cGMzUmxjbThyWkdWc2JHRXJVMkZzZFhSbEsxUmxjM1FsTWtOUEpUTkVUV2x1YVhOMFpYSnZLMlJsYkd4aEsxTmhiSFYwWlNVeVEwTWxNMFJKVkRBZEJnTlZIUTRFRmdRVUVMc3c1ZWNKa2RoYTNMTllqemcwbCswbG5oMHdEZ1lEVlIwUEFRSC9CQVFEQWdaQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQXdkMGxMajJoWjJEV2V1bmlXL00vOUxWWGlhWFJFRHkrenFoRk9iMzBGNHJMZEVZcUFWSG5seUhJWVVERkUvQkRxUE1ka0NlSSswRHhsbVRHbzUrTER4L21PTWtTZW92RlJUb2wwZXR1R3J2RFBKS244Mlc2bXBWNkJTSXovMFh4U1Q1aUZPYUhROUZjV1pWN0dxOEl5K1VIUXVMaWlJckhaQ1YvQmFlMFVlLzltQzZWQS9LOFUxU3BZcjRJWEJBYk1wa3RKa0pHRjRVZ3FVNE84K2U4QXhBRmNqQ3NYTmYyZ1JQOVlmS1I4Qk1TZFlxN09namtQdVFwNEhCSEtWWWRITGNwaUthT1pybS9LMFQxR3ZGK1BhUmp2OUtuV0E0STRvNU1hNFB6Z0d1M2VqUmxjdlVIVG16bkd0UmVPZ01zcUdBZ1lKaHc5VkZRL2RDaXFRYWpDeXdnSlhuVlBEZjhILzNLK1FUNk4rSlA0ajJaVHZtMVVuM2FWRnl0ZTI5TXEvZFpmVVJNUXBOelF0cFhjWkk4M1dmNUwxT1F2QWhNbjhScUxSV1dvMWJKZkNQNlFwS29KUTVhUXFlS3hsOUlnZzFxVDdNYUJFSkJkYVVRaUd5K2dJNUZjdUlxV2t3em1vWVl3OVZsYThoSnpLMElSMzdjS04zYVlZNzRsblFKdmZNaTFVcUdwSFdCVTFMWVExSFpGc2IvOGdraVljankzUnIxNWxRK2ROMDFtbTVrNEZpaWpGRUkyNWN5S0ZSbVoyODVCd3VodXQ1TnNKM1p3S1U2R2lpRTFtRThuSlBmeE82ajZPTnVhNmsxaVlMTGk2RzAwUU5MUFJPWWpPT0VWVG1PaGlGeDgvK3JLRWJHVlVGb2VXL21WbEpRUnJCbTZtekVaZkVtT3VBPT0iXX0.eyJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExQ09OU09SWklPT0RNWFgiLCJpYXQiOjE2OTk0NTM3MTIsImV4cCI6MTY5OTQ1NDMxMiwianRpIjoxMjM0NTYsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInN1YiI6IlBST1ZBWDAwWDAwWDAwMFleXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMDkwIiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb25lIFRvc2NhbmEiLCJsb2NhbGl0eSI6IjIwMTcwMjExQSIsInN1YmplY3Rfcm9sZSI6IkFBUyIsInBlcnNvbl9pZCI6IlBST1ZBWDAwWDAwWDAwMFleXl4mMi4xNi44NDAuMS4xMTM4ODMuNi4xJklTTyIsInBhdGllbnRfY29uc2VudCI6InRydWUiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsInJlc291cmNlX2hsN190eXBlIjoiKCc2ODYwNC04Xl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsImFjdGlvbl9pZCI6IkNSRUFURSIsInN1YmplY3RfYXBwbGljYXRpb25faWQiOiJDT05TT1JaSU9PRE0iLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlbmRvciI6IkhTRzYiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlcnNpb24iOiIyMi4xIn0.EmRwBVJ52wPY93Lv6VvQv49m0Qum4qyse4WWxUUYyG5CYeLXzdNGWkMJTCt-AwD0Hj7UFBWJ-zbGu83MAdrwd6y3BGgezCAl_TUH8wHIX43sETkK3-Zxg3Smg3ivdlHPllKaLo2YXxsNy1Aart7lO_xUvHazyZ4kSXg4EyUvvb-sz5dcmwKBZpJpJQJs-n21sALEg1gb91_LhPWFhwCOXGtQdll9ytS4vHhPiaPHv4W3pGlt1SFPga33YgZ49-QDgl3O4s9rAPkIa7-omVb8FYcwkHeJcuwjGGyxus9i5wo4d2nld2y5UXlqEm0MaiP9UPxtwjOGCk2TO8OtuoZFGQ
#####################

Provando a decodificare i due JWT ci viene resa la seguente struttura dati:
**********TEST DECODE JWT 1**********************
{'iss': 'auth:S1#111CONSORZIOODMXX', 'iat': 1699453712, 'exp': 1699454312, 'jti': 123456, 'aud': 'https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1', 'sub': 'NNNNDR78E01D612S^^^&2.16.840.1.113883.2.9.4.3.2&ISO'}
**********TEST DECODE JWT 2**********************
{'iss': 'integrity:S1#111CONSORZIOODMXX', 'iat': 1699453712, 'exp': 1699454312, 'jti': 123456, 'aud': 'https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1', 'sub': 'PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO', 'subject_organization_id': '090', 'subject_organization': 'Regione Toscana', 'locality': '20170211A', 'subject_role': 'AAS', 'person_id': 'PROVAX00X00X000Y^^^&2.16.840.1.113883.6.1&ISO', 'patient_consent': 'true', 'purpose_of_use': 'TREATMENT', 'resource_hl7_type': "('68604-8^^2.16.840.1.113883.6.1')", 'action_id': 'CREATE', 'subject_application_id': 'CONSORZIOODM', 'subject_application_vendor': 'HSG6', 'subject_application_version': '22.1'}

Il campo sub in entrambi i casi è formattato secondo le indicazioni.

**Comment by vigliottim** [comment]
Buonasera, i token forniti hanno valori differenti per il campo sub. Vi segnaliamo, se può essere utile, che è stato messo a disposizione un il tool jwt-generator per generare i token. Può trovare il pacchetto di installazione con relativa documentazione al seguente link:
https://github.com/ministero-salute/it-fse-gtw-tools/tree/167cc20298c15c512e6366ba8751f32de02c0805/jwt-generator

**Comment by vigliottim** [comment]
Chiudiamo il presente ticket e rimaniamo a disposizione per ulteriori richieste di supporto. Buona serata.
