### ISSUE TITLE
Errore 400 - invalidRequestContent

### ISSUE THREAD

**Issue by cravell** [ministero-salute/it-fse-support#52]
Salve [#fse](https://developersitalia.slack.com/archives/C03RDT88FSM) ho eseguito una prova di validazione che stamattina ritornava con ack positivo.
Ora il servizio restituisce l'errore:
{
	"type": "https://govway.org/handling-errors/400/InvalidRequestContent.html",
	"title": "InvalidRequestContent",
	"status": 400,
	"detail": "Request content not conform to API specification: UTF-8;boundary=HMby7edetn2g8fLsl_dzIXXLkVX7gwP4ObDwmseR",
	"govway_id": "5997040a-9288-11ed-b06a-005056ae7395"
}

**Comment by cravell** [comment]
Oggi ho riprovato:
 {"type":"https://govway.org/handling-errors/400/InvalidRequestContent.html","title":"InvalidRequestContent","status":400,"detail":"Request content not conform to API specification: UTF-8;boundary=Ok8io_e3co5GbVFkIu-r6-ey-ltqm0EcR","govway_id":"a050014e-9585-11ed-b06a-005056ae7395"}

Alegor gli header jwt per completezza

[HeaderSignature.txt](https://github.com/ministero-salute/it-fse-support/files/10425281/HeaderSignature.txt)

[HeaderAuthorization.txt](https://github.com/ministero-salute/it-fse-support/files/10425279/HeaderAuthorization.txt)

**Comment by pFonziSogei** [comment]
Salve,

può provare a rimuovere "charset=UTF-8" dal content-type? In alternativa dovrebbe far in modo di inserirlo in fondo al content type es. request.contentType("multipart/form-data;charset=UTF-8");

**Comment by cravell** [comment]
Rimuovendo il "charset=UTF-8" dal content-type ha risolto il problema.
Grazie

**Comment by nturri1306** [comment]
salve posso chiedere che libreria java hai usato?
