### ISSUE TITLE
Mancato accreditamento A1#200000SWHCGMXX-COMPUGROUP_MEDICAL_ITALIA_S.p.a-PROFIM-6.05 #957

### ISSUE THREAD

**Issue by CGM-Daniele-Romanazzi** [ministero-salute/it-fse-support#520]
Salve, in merito all'accreditamento [qui ](https://github.com/ministero-salute/it-fse-accreditamento/pull/957) riportato, vorremmo avere chiarimenti e riscontro su queste casistiche.

> Test: 173 - Errori: 337,338,339,340,341,342,343,344,345,346,347,348,349,350,351 
> Sono dovuti all'assenza della sezione 'Reti_Patologia' che come indicato nelle note del file XLS di controllo non è una sezione gestita in nostra prodotto e non risulta essere sezione obbligatoria

> Test: 171,172,173 - Errori: 152,153,154,155,156,157,158,159,160,161,162,163,164,165,166
> Test: 172 - Errori: 234,235,236,237,238
> Test: 173 - Errori: 301,302
> Sono dovuti all'assenza della sezione 'Piani_cura' che come indicato nelle note del file XLS di controllo non è una sezione gestita in nostra prodotto e non risulta essere sezione obbligatoria

> Test: 171,172,173 - Errori: 129,130,131
> Test: 173 - Errori: 254,255
> Test: 170 - Errori: 036,037,038
> Sono dovuti all'assenza di annotazioni in sezione 'Allergie_Intolleranze': attualmente le annotazioni non sono gestite in nostro prodotto per tale sezione e non risultano essere informazioni obbligatorie 

> Test: 173 - Errori: 256,257
> Sono dovuti all'assenza di informazioni relative a via e sito di somministrazione farmaco nella sezione 'Terapie_Farmacologiche': attualmente tali informazioni non sono gestite in nostro prodotto per tale sezione e non risultano essere informazioni obbligatorie 

> Test: 171,172,173 - Errori: 134,135,136,137,138,139,140,141,142
> Test:  170 - Errori: 075,076,077,078,079,080,081,082
> Sono dovuti all'assenza di annotazioni in sezione 'Lista_Problemi': attualmente le annotazioni non sono gestite in nostro prodotto per tale sezione e non risultano essere informazioni obbligatorie 

> Test: 172,173 - Errori: 181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202
> Test: 173 - Errori: 290,291,292,293,294
> Sono dovuti alla mancata gestione strutturata delle informazioni relative ad 'Anamnesi_Familiare': attualmente tali informazioni sono gestite solo in modo testuale nel nostro prodotto; non risultano obblighi relativi ad indicazioni strutturate per tale sezione

> Test: 170,171,172,173 - Errori: 103
> Test: 170,172,173 - Errori: 102,104
> Test: 173 - Errori: 304,305
> Sono dovuti all'assenza di informazioni su diagnosi relative alla sezione 'Trattamenti_procedure_terapeutiche_chirurgiche_diagnostiche': attualmente tali informazioni non sono gestite in nostro prodotto per tale sezione e non risultano essere informazioni obbligatorie

> Test: 173 - Errori: 329,330,331,332,333,334,335,336
> Sono dovuti all'assenza di annotazioni in sezione 'Esenzioni': attualmente le annotazioni non sono gestite in nostro prodotto per tale sezione e non risultano essere informazioni obbligatorie 

> Test: 170,171,172,173 - Errori: 083,084
> Sono dovuti all'assenza di riferimenti interni per la sezione 'Lista_Problemi': non risulta obbligatoria l'indicazione di riferimenti interni

In attesa di riscontro,
Cordiali saluti.

**Comment by vigliottim** [comment]
Buongiorno, 
Le segnaliamo che occorre inserire tutti gli elementi che, anche se sono opzionali da guida, per il caso d’uso sono necessari per completezza di informazione. 
La invitiamo a far riferimento alla colonna evidenziata in rosa _"Obbligatorietà per Test case *"_ (con l'indicazione di obbligatorietà per il caso di test) degli excel contenuti al [link](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/8-Profilo%20Sanitario%20Sintetico), in cui sono riportate le istruzioni per la compilazione dei CDA a seconda degli use case di PSS.

A titolo esemplificativo, le riportiamo di seguito i razionali di uno degli errori riscontrati nei test automatici:

**Test 173 Error code 254**: L'errore indica che è richiesto l'attributo _"code"_, all'interno del tag _"ClinicalDocument/component/structuredBody/component/section[ID='Allergie_Intolleranze']/entry/act/entryRelationship/observation/entryRelationship/act/code"_, valorizzato con _"48767-8"_. 
Notiamo che all'interno del cda usato per il _test 173_ i tag evidenziati sono mancanti:
_ClinicalDocument/component/structuredBody/component/section[ID='Allergie_Intolleranze']/entry/act/entryRelationship/observation/entryRelationship/**act**/**code_**.
Come riportato in [documentazione](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/8-Profilo%20Sanitario%20Sintetico/CDA2_Profilo_Sanitario_Sintetico_OK.xlsx) nell'excel dei requisiti a linea 96 dello sheet _"PSS - Caso di Test 4"_, questi tag risultano obbligatori e sono specificati gli attributi mandatori e opzionali da valorizzare.

In aggiunta, nel caso particolare in cui i dati non siano disponibili a sistema oppure nel caso in cui non si possa completare il test case correttamente, è possibile indicare _NO_ nell’apposita colonna _"Applicabilità"_, avendo cura di giustificarlo opportunamente nella colonna _"razionale di applicabilità"_.

Le segnaliamo infine che è disponibile a questo [link](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/gtw-certifier) il tool _"gwt-certifier"_, che consente di riprodurre in locale le verifiche dei test case di validazione OK richiesti durante la fase di accreditamento.

**Comment by vigliottim** [comment]
Buongiorno, non avendo avuto ulteriori riscontri, procediamo alla chiusura del presente ticket. Può riaprirlo in caso fosse necessario. Restiamo a disposizione per altre richieste di supporto. Grazie.
