### ISSUE TITLE
Problema in validazione PSS    A1#200000SWHMEDIWARE - ADVMEDNET

### ISSUE THREAD

**Issue by danielito64** [ministero-salute/it-fse-support#521]
Buongiorno, stiamo tentando la validazione per un PSS inviando il PDF con CDA2 in modalità ATTACHMENT.
In allegato Request e Response per le oppotune valutazioni.
Grazie

Daniele Riefoli
[validation_request.txt](https://github.com/ministero-salute/it-fse-support/files/13373303/validation_request.txt)
[validation_response.txt](https://github.com/ministero-salute/it-fse-support/files/13373304/validation_response.txt)

**Comment by vigliottim** [comment]
Buongiorno, le chiediamo gentilmente di allegare anche il file pdf con cda. Grazie.

**Comment by danielito64** [comment]
Buonasera,

eccolo in allegato.
 
Grazie
Daniele Riefoli
[ProfiloSanitarioSintetico.zip](https://github.com/ministero-salute/it-fse-support/files/13382256/ProfiloSanitarioSintetico.zip)

**Comment by vigliottim** [comment]
Buongiorno, grazie per aver condiviso il cda. Ai fini delle analisi ci sarebbe utile avere anche il pdf con il cda iniettato. Potrebbe inviarlo? Grazie.
