### ISSUE TITLE
Errore 400 in publicazione

### ISSUE THREAD

**Issue by nspazzoli** [ministero-salute/it-fse-support#525]
Buongiorno,

vi scrivo per avere informazioni su un caso di errore avuto oggi.

- 2023-11-24 11:59:46.359: valido documento ed ottenendo esito OK e workflowInstaId = 2.16.840.1.113883.2.9.2.80.3.1.4.4.83d5b51d20d912d983dd287a00e10f980fa0d5aa76f76baba340acef25bee6cd.8081c62892^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
- 2023-11-24 12:00:34.720 pubblicazione documento che invece riceve KO con la seguente risposta
 HTTP 400, 
 {"traceID":"bb4aaf4164234aaf","spanID":"bb4aaf4164234aaf","type":"/msg/cda-match","title":"Errore in fase di recupero dell'esito della verifica.","detail":"Il CDA non risulta validato","status":400,"instance":"/cda-validation"}

Dovrebbe essere il primo tentativo di pubblicazione quindi il workflowInstaceId non dobrebbe essere "bruciato".
Visto che, se ho capito bene, la validazione è un servizio immediato, qual è il motivo dell'errore?

Grazie
Cordiali saluti

**Comment by vigliottim** [comment]
Buonasera, le chiediamo gentilmente di verificare se:
- sta utilizzando un CDA tra quelli forniti come esempio;
- il CDA iniettato nel pdf di pubblicazione è lo stesso di quello utilizzato in validazione;
- dopo la validazione, ha chiamato una volta soltanto la pubblicazione, riscontrando l'errore sopra riportato."
Grazie.

**Comment by nspazzoli** [comment]
Salve,

il documento visto che valida dovrebbe essere conforme alle specifiche CDA.
Il documento non è cambiato fra validazione e pubblicazione (non è stato fatto a mano la prova), ma è da applicativo che valida e poi pubblica.
Mi risulta essere il primo tentativo.

Grazie

**Comment by vigliottim** [comment]
Grazie per il riscontro. Chiariamo meglio il primo punto del messaggio precedente: potrebbe confermare che il cda utilizzato non rientra tra quelli che sono stati messi a disposizione su github per gli utenti a titolo di esempio? Se così fosse, la validazione conseguita potrebbe essere stata "bruciata" dalla pubblicazione di un altro utente.

**Comment by nspazzoli** [comment]
Il "modello" del cda è stato preso dal quelli di esempio, ma viene generato dinamicamente, camviando gli effectiveTime, il codice del documento ecc.. Quendi dovrebbe essere univoco.

**Comment by IStacchiotti** [comment]
Grazie per il riscontro. Le suggeriamo di ripetere le chiamate di validazione e pubblicazione (invocazione singola) utilizzando il medesimo pdf, possibilmente svolgendo chiamate manuali senza ricorrere all'applicativo (questo per escludere che l'errore riscontrato sia riconducibile all'orchestrazione delle chiamate gestite dall'applicativo che avete sviluppato per interfacciarvi con il gateway).
Ci faccia sapere se così facendo l'errore persiste.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto riscontri, procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
