### ISSUE TITLE
CT1 VPS ID=MODALITA_DI_TRASPORTO

### ISSUE THREAD

**Issue by sandroaresu23** [ministero-salute/it-fse-support#526]
Buon pomeriggio,
utilizzando il gtw-certifier abbiamo ricevuto un errore per una errata valorizzazione di una delle seziona del VPS: "id = 'Modalita_di_trasporto'" (rif. VALIDAZIONE_CDA2_VPS_CT1 1.pdf).
Abbiamo utilizzato la stessa valorizzazione che abbiamo preso dal link https://github.com/ministero-salute/it-fse-support/tree/main/doc/esempi/CDA, in cui sono riportati gli esempi di CDA che hanno superato la validazione (rif. IMG_VPS_MODALITA_TRASPORTO.png).

Per scrupolo abbiamo modificato (à anziché a) la valorizzazione con "id = 'Modalità_di_trasporto'" e abbiamo superato il test.

Quali delle 2 specifiche prendiamo in considerazione, in vista della pull request per l'accreditamento?

![IMG_VPS_MODALITA_TRASPORTO](https://github.com/ministero-salute/it-fse-support/assets/128618821/fec39ba2-f450-42e0-99a9-e1f8d491ab93)
[VALIDAZIONE_CDA2_VPS_CT1 1.pdf](https://github.com/ministero-salute/it-fse-support/files/13460991/VALIDAZIONE_CDA2_VPS_CT1.1.pdf)

**Comment by LucaRogledi** [comment]
Buonasera,
Le specifiche a cui fare riferimento per l'accreditamento sono riportate nel foglio excel contenente il caso di test in questione (es. "VPS - Caso di Test 1").
Segnaliamo che è corretto l'utilizzo della stringa "Modalità_di_Trasporto" come riportato nella [documentazione](
https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/2-Verbale%20di%20Pronto%20Soccorso/CDA2_Verbale_Pronto_Soccorso_OK.xlsx).
Restiamo a disposizione in caso di ulteriori chiarimenti, grazie.

**Comment by sandroaresu23** [comment]
Buonasera,
ditemi se preferite una nuova issue, però vorrei segnalare che, se facciamo riferimento alla documentazione da voi sopra riportata, per la sezione ID="Inquadramento_clinico_iniziale", abbiamo ricevuto un KO perché vi aspettavate ID="Inquadramento_clinico" (descrizione in questo caso presente, nel file di esempio CDA).

Grazie

**Comment by IStacchiotti** [comment]
Buongiorno @sandroaresu23,
La ringraziamo per la segnalazione: la prendiamo in carico e vi forniremo un riscontro appena possibile. 
Grazie.

**Comment by LucaRogledi** [comment]
Buon pomeriggio, Le confermiamo che è stato rilasciato un aggiornamento. 
La invitiamo cortesemente a riprovare utilizzando il tool aggiornato all'ultima versione disponibile al [link](
https://github.com/ministero-salute/it-fse-gtw-tools
). 
Rimaniamo a disposizione in caso fosse necessario ulteriore supporto, grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto riscontri, procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
