### ISSUE TITLE
compilazione accreditamento-checklist_V8.1.3 e compialzione form accreditamento

### ISSUE THREAD

**Issue by ftallaro** [ministero-salute/it-fse-support#527]
Buongiorno,

stavo procedendo ad analizzare la compilazione del documento in oggetto per la validazione.

Nel caso del Laboratorio Analisi ci sono 2 righe, 191 e 376, che non ho capito bene cosa riguardano anche guardando come suggerito al link https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway.

Mi potreste dire a cosa si riferiscono?

Stavo procedendo con la richiesta di validazione ma il forma al link https://ec.europa.eu/eusurvey/runner/FSE-raccolta-id-applicativo non è più accessibile. Come mai?
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno,
In merito al primo punto, la rimandiamo a questo [link](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/9-Trasfusionale), in cui troverà il file word con la descrizione dei casi di test 191 e 376, e un excel con le istruzioni per la compilazione dei relativi cda.  
In merito al secondo, la invitiamo a riprovare ad accedere al form: il link dovrebbe essere attivo.
Rimaniamo a disposizione per ulteriori chiarimenti, grazie

**Comment by ftallaro** [comment]
Perfetto, grazie.

Una volta che compilo il form per la certificazione devo attendere una comunicazione oppure posso procedere con l'invio?
Inoltre ho letto a questo indirizzo le istruzioni https://github.com/ministero-salute/it-fse-accreditamento ma ho qualche dubbio:

1) Il fork lo devo fare di questo indirizzo, corretto?
2) Quando eseguo il fork devo dare un qualche nome particolare al fork? 
3) Da qualche parte ci sono i comandi su come eseguire la pull request?
4) Oltre ad inviare i file devo anche creare la cartella degli stessi file firmati in PADES?

Grazie

**Comment by vigliottim** [comment]
Buonasera,
In merito alla prima domanda, le confermiamo che, una volta compilato il form, è possibile procedere con la sottomissione della pull request ai fini dell'accreditamento.

Rispondiamo in linea alle domande successive:
1. Il fork lo devo fare di questo indirizzo (https://github.com/ministero-salute/it-fse-accreditamento), corretto? Il fork deve essere effettuato a partire dal branch main del repository centrale: https://github.com/ministero-salute/it-fse-accreditamento/tree/main
2. Quando eseguo il fork devo dare un qualche nome particolare al fork? No, non ci sono indicazioni in merito al nome da utilizzare.
3. Da qualche parte ci sono i comandi su come eseguire la pull request? No, la invitiamo a far riferimento ai seguenti step per l'esecuzione dei comandi: https://github.com/ministero-salute/it-fse-accreditamento#pull-request
4. Oltre ad inviare i file devo anche creare la cartella degli stessi file firmati in PADES? Come riportato in documentazione, in caso di validazione, se pertinente (il software ha la funzionalità di firma e la firma è oggetto di adeguamento), devono essere allegati anche i file pdf utilizzati nell'invocazione dei servizi firmati PADES (all'interno della directory FILES/SIGNED).
Restiamo a disposizione per ulteriori chiarimenti.

**Comment by ftallaro** [comment]
Ho fatto la pull request però mi sono appena accorto di aver inserito la cartella SIGNED nella stessa directory di FILES e non annidandola dentro.

Cosa devo fare per ovviare al problema? Inoltre come seguo l'iter della validazione?

Grazie

**Comment by LucaRogledi** [comment]
Buonasera,
può effettuare una commit correttiva con gli aggiustamenti necessari.
Successivamente verranno effettuate le opportune verifiche e riceverà l'esito delle analisi svolte alla email comunicata in EuSurvey.
Grazie

**Comment by ftallaro** [comment]
Io dal mio fork ho eliminato la cartella e l'ho uplodata nuovamente nella posizione corretta.

Guardando la pull request sembrerebbe che abbia recepito le modifiche:

![immagine](https://github.com/ministero-salute/it-fse-support/assets/135626660/28bc0a1f-114a-4ffd-8cd9-0f76ca5bbbef)

Mi potrebbe dare conferma?

La ringrazio.

**Comment by ftallaro** [comment]
Buongiorno,

ho ricevuto l'email che il data.json era malformato. 

Ho sistemato il data.json ed una cosa nel report. ho uplodato entrambi nel fork ed ho fatto un sync fork.

Va bene così oppure devo fare altro? Devo rispondere all'email dicendo che li ho sistemati?

Grazie.
