### ISSUE TITLE
Errore sostituzione documento tramite middleware di Regione Lazio

### ISSUE THREAD

**Issue by rg-08** [ministero-salute/it-fse-support#528]
Buongiorno,
stiamo completando i test per l'integrazione con FSE attraverso il middleware di Regione Lazio per referti RAD.
Siamo riusciti ad eseguire la validazione e successiva pubblicazione ed eventuale annullamento, ma ad oggi non riusciamo a completare la sostituzione di un documento.

L'errore restituito è il seguente:
{
  "traceID" : "6b7dd93d17271791",
  "spanID" : "6b7dd93d17271791",
  "type" : "/msg/record-not-found",
  "title" : "Record non trovato.",
  "detail" : "No Record Found",
  "status" : 404,
  "instance" : "/record-not-found"
}

La pubblicazione della prima versione del documento era andata a buon fine:
POST su https://fse-services-test.regione.lazio.it/fse-middleware/gateway/v1/documents
requestBody:
{
    "administrativeRequest": "SSN",
    "assettoOrganizzativo": "AD_PSC069",
    "attiCliniciRegoleAccesso": [
    ],
    "dataFinePrestazione": "20231121165123",
    "dataInizioPrestazione": "20231121165123",
    "descriptions": [
        "88.27^RADIOGRAFIA DEL FEMORE, GINOCCHIO E GAMBA\nRadiografia (2 proiezioni) di: femore, ginocchio, gamba^2.16.840.1.113883.2.9.6.1.11"
    ],
    "healthDataFormat": "CDA",
    "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^0AAC7BB7-9C39-ABF2-E063-959FEA0AAB77",
    "identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.200",
    "identificativoSottomissione": "2.16.840.1.113883.2.9.2.120.4.3.20231121165130704",
    "mode": "ATTACHMENT",
    "tipoAttivitaClinica": "ERP",
    "tipoDocumentoLivAlto": "REF",
    "tipologiaStruttura": "Ospedale",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.413e4ac7aca5c65f0972b27918c2c8efd5dd47ac7fa594703b68f590b42a26d1.fd8ba17cad^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Response:
{
  "traceID" : "84b323d3616d6b45",
  "spanID" : "84b323d3616d6b45",
  "warning" : "",
  "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.413e4ac7aca5c65f0972b27918c2c8efd5dd47ac7fa594703b68f590b42a26d1.fd8ba17cad^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

E anche verificando lo stato della transazione tramite GW, risulta tutto corretto:
GET su https://fse-services-test.regione.lazio.it/fse-middleware/gateway/v1/status/2.16.840.1.113883.2.9.2.120.4.4.413e4ac7aca5c65f0972b27918c2c8efd5dd47ac7fa594703b68f590b42a26d1.fd8ba17cad%5E%5E%5E%5Eurn%3Aihe%3Aiti%3Axdw%3A2013%3AworkflowInstanceId
{
  "traceID" : "ad42d98cf171ddca",
  "spanID" : "25d4e9afebc10704",
  "transactionData" : [
    {
      "eventType" : "VALIDATION",
      "eventDate" : "2023-11-21T15:51:27.524+00:00",
      "eventStatus" : "SUCCESS",
      "subject" : "PSTNNZ76P18E783T^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "organizzazione" : "120",
      "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.413e4ac7aca5c65f0972b27918c2c8efd5dd47ac7fa594703b68f590b42a26d1.fd8ba17cad^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId" : "c4b0ec0471c50d06",
      "issuer" : "integrity:S1#120000000000XX",
      "expiringDate" : "2024-11-20T15:51:27.535+00:00"
    },
    {
      "eventType" : "PUBLICATION",
      "eventDate" : "2023-11-21T15:51:32.397+00:00",
      "eventStatus" : "SUCCESS",
      "identificativoDocumento" : "2.16.840.1.113883.2.9.2.120.4.4^0AAC7BB7-9C39-ABF2-E063-959FEA0AAB77",
      "subject" : "PSTNNZ76P18E783T^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "tipoAttivita" : "ERP",
      "organizzazione" : "120",
      "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.413e4ac7aca5c65f0972b27918c2c8efd5dd47ac7fa594703b68f590b42a26d1.fd8ba17cad^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId" : "84b323d3616d6b45",
      "issuer" : "integrity:S1#120000000000XX",
      "expiringDate" : "2024-11-20T15:51:32.407+00:00"
    },
    {
      "eventType" : "SEND_TO_INI",
      "eventDate" : "2023-11-21T15:51:32.479+00:00",
      "eventStatus" : "SUCCESS",
      "message" : "{\"esito\":true,\"errorMessage\":\"Regime di mock abilitato\",\"traceID\":\"f6e0b1736883ce88\",\"spanID\":\"f6e0b1736883ce88\"}",
      "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.413e4ac7aca5c65f0972b27918c2c8efd5dd47ac7fa594703b68f590b42a26d1.fd8ba17cad^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate" : "2024-11-20T15:51:32.596+00:00"
    },
    {
      "eventType" : "SEND_TO_EDS",
      "eventDate" : "2023-11-21T15:51:32.911+00:00",
      "eventStatus" : "SUCCESS",
      "message" : "{\"esito\":true}",
      "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.413e4ac7aca5c65f0972b27918c2c8efd5dd47ac7fa594703b68f590b42a26d1.fd8ba17cad^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate" : "2024-11-20T15:51:33.034+00:00"
    },
    {
      "eventType" : "EDS_WORKFLOW",
      "eventDate" : "2023-11-21T16:00:00.006+00:00",
      "eventStatus" : "SUCCESS",
      "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.413e4ac7aca5c65f0972b27918c2c8efd5dd47ac7fa594703b68f590b42a26d1.fd8ba17cad^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate" : "2024-11-20T16:00:00.029+00:00"
    }
  ]
}

Poi quando si invia il sostitutivo (dopo averlo validato):
PUT su https://fse-services-test.regione.lazio.it/fse-middleware/gateway/v1/documents/2.16.840.1.113883.2.9.2.120.4.4%5E0AAC7BB7-9C39-ABF2-E063-959FEA0AAB77
requestBody:
{
    "administrativeRequest": "SSN",
    "assettoOrganizzativo": "AD_PSC069",
    "attiCliniciRegoleAccesso": [
    ],
    "dataFinePrestazione": "20231121171006",
    "dataInizioPrestazione": "20231121171006",
    "descriptions": [
        "88.27^RADIOGRAFIA DEL FEMORE, GINOCCHIO E GAMBA\nRadiografia (2 proiezioni) di: femore, ginocchio, gamba^2.16.840.1.113883.2.9.6.1.11"
    ],
    "healthDataFormat": "CDA",
    "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^0AACC153-7AEE-AE4C-E063-959FEA0AC0D0",
    "identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.200",
    "identificativoSottomissione": "2.16.840.1.113883.2.9.2.120.4.3.20231121171025835",
    "mode": "ATTACHMENT",
    "tipoAttivitaClinica": "ERP",
    "tipoDocumentoLivAlto": "REF",
    "tipologiaStruttura": "Ospedale"
}

otteniamo la risposta di errore
Response:
{
  "traceID" : "6b7dd93d17271791",
  "spanID" : "6b7dd93d17271791",
  "type" : "/msg/record-not-found",
  "title" : "Record non trovato.",
  "detail" : "No Record Found",
  "status" : 404,
  "instance" : "/record-not-found"
}

E' possibile verificare cosa non va?

Grazie.

**Comment by LucaRogledi** [comment]
Buonasera,
Notiamo che il valore del parametro "identificativoDoc" all'interno della requestBody del servizio di Sostituzione è "2.16.840.1.113883.2.9.2.120.4.4^0AACC153-7AEE-AE4C-E063-959FEA0AC0D0", ma come mostrato dal servizio di Status, il documento pubblicato e da sostituire è identificato con "2.16.840.1.113883.2.9.2.120.4.4^0AAC7BB7-9C39-ABF2-E063-959FEA0AAB77".
La rimandiamo al seguente link in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#6-servizio-di-sostituzione-documento) e restiamo a disposizione per ulteriori chiarimenti.
Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno @rg-08, potreste confermarci che, prima di tentare la sostituzione del vecchio documento ("2.16.840.1.113883.2.9.2.120.4.4^0AAC7BB7-9C39-ABF2-E063-959FEA0AAB77") con il nuovo ("2.16.840.1.113883.2.9.2.120.4.4^0AACC153-7AEE-AE4C-E063-959FEA0AC0D0"), il primo non sia stato cancellato?

**Comment by IStacchiotti** [comment]
Buonasera, dalle verifiche svolte è emerso che il Gateway riceve nell'url il seguente identificativo `2.16.840.1.113883.2.9.2.120.4.4%5E0AACC153-7AEE-AE4C-E063-959FEA0AC0D0`, al posto di quello del documento da sostituire che avete inserito come path variable nella request (`2.16.840.1.113883.2.9.2.120.4.4%5E0AAC7BB7-9C39-ABF2-E063-959FEA0AAB77`): questo spiegherebbe l'errore in risposta "Record non trovato".
Vi suggeriamo di accertare la corretta integrazione tra middleware e Gateway per il servizio di sostituzione, e di tentare eventualmente un'invocazione bypassando il middleware (se ne avete la possibilità) chiamando direttamente il Gateway, al fine di verificare se in questo modo la chiamata va a buon fine. Rimaniamo a disposizione per ulteriori richieste di supporto. Grazie

**Comment by rg-08** [comment]
Buongiorno,
abbiamo fatto presente ai gestori del middleware.

Nel frattempo abbiamo provato la transazione direttamente verso Gateway, ma otteniamo errore:
{
  "type" : "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
  "title" : "InteroperabilityInvalidRequest",
  "status" : 400,
  "detail" : "Received request is not conform to the required interoperability profile",
  "govway_id" : "da5dc797-8e9e-11ee-91c5-005056ae54fa"
}

Invio del sostitutivo (dopo averlo validato):
PUT su https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.120.4.4%5E0AAC7BB7-9C39-ABF2-E063-959FEA0AAB77

requestBody
{
	"healthDataFormat": "CDA",
	"mode": "ATTACHMENT",
	"tipologiaStruttura": "Ospedale",
	"attiCliniciRegoleAccesso": [],
	"identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^0AACC153-7AEE-AE4C-E063-959FEA0AC0D0",
	"identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.200",
	"tipoDocumentoLivAlto": "REF",
	"assettoOrganizzativo": "AD_PSC069",
	"dataInizioPrestazione": "20231129113609",
	"dataFinePrestazione": "20231129113609",
	"tipoAttivitaClinica": "ERP",
	"identificativoSottomissione": "2.16.840.1.113883.2.9.2.120.4.3.20231129115255151",
	"descriptions": [
		"88.27^RADIOGRAFIA DEL FEMORE, GINOCCHIO E GAMBA\nRadiografia (2 proiezioni) di: femore, ginocchio, gamba^2.16.840.1.113883.2.9.6.1.11"
	],
	"administrativeRequest": "SSN"
}

otteniamo la risposta di errore
Response:
{
  "type" : "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
  "title" : "InteroperabilityInvalidRequest",
  "status" : 400,
  "detail" : "Received request is not conform to the required interoperability profile",
  "govway_id" : "da5dc797-8e9e-11ee-91c5-005056ae54fa"
}

**Comment by vigliottim** [comment]
Buongiorno, potrebbe cortesemente allegare i token utilizzati? Grazie.

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
dalle nostre verifiche è emerso una valorizzazione errata del parametro "aud" nel data.json utilizzato per la generazione dei token.
As-is: `https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents`
To-be: `https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1`

Le chiediamo gentilmente di riprovare utilizzando la valorizzazione corretta.
Grazie.

**Comment by rg-08** [comment]
Salve,
grazie per la pronta risposta.
Abbiamo modificato il parametro "aud" e ora la pubblicazione del sostitutivo verso Gateway ha funzionato.
Questa la response:
{
  "traceID" : "e6cdd47bff57186b",
  "spanID" : "e6cdd47bff57186b",
  "warning" : "",
  "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.6d134cf1d7c2a5d15cd3cff228a92db7db2aabc5834ff6567c905db71151e0a7.01e0781747^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Verificando però lo stato tramite il workflowInstanceId viene segnalato un errore di "SEND_TO_EDS":
{
  "traceID" : "bd74b979cc08f65d",
  "spanID" : "bb868f438272a06c",
  "transactionData" : [
    {
      "eventType" : "VALIDATION",
      "eventDate" : "2023-11-29T14:05:25.150+00:00",
      "eventStatus" : "SUCCESS",
      "subject" : "PSTNNZ76P18E783T^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "organizzazione" : "120",
      "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.6d134cf1d7c2a5d15cd3cff228a92db7db2aabc5834ff6567c905db71151e0a7.01e0781747^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId" : "7a73b4c403fb4f96",
      "issuer" : "integrity:S1#120000000000XX",
      "expiringDate" : "2024-11-28T14:05:25.163+00:00"
    },
    {
      "eventType" : "REPLACE",
      "eventDate" : "2023-11-29T14:05:53.801+00:00",
      "eventStatus" : "SUCCESS",
      "identificativoDocumento" : "2.16.840.1.113883.2.9.2.120.4.4^0AACC153-7AEE-AE4C-E063-959FEA0AC0D0",
      "subject" : "PSTNNZ76P18E783T^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "tipoAttivita" : "ERP",
      "organizzazione" : "120",
      "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.6d134cf1d7c2a5d15cd3cff228a92db7db2aabc5834ff6567c905db71151e0a7.01e0781747^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId" : "e6cdd47bff57186b",
      "issuer" : "integrity:S1#111AGFAHEALTHC",
      "expiringDate" : "2024-11-28T14:05:53.813+00:00"
    },
    {
      "eventType" : "SEND_TO_INI",
      "eventDate" : "2023-11-29T14:05:53.986+00:00",
      "eventStatus" : "SUCCESS",
      "message" : "{\"esito\":true,\"errorMessage\":\"Regime di mock abilitato\",\"traceID\":\"908bbfd787cb91b8\",\"spanID\":\"908bbfd787cb91b8\"}",
      "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.6d134cf1d7c2a5d15cd3cff228a92db7db2aabc5834ff6567c905db71151e0a7.01e0781747^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate" : "2024-11-28T14:05:54.071+00:00"
    },
    {
      "eventType" : "SEND_TO_EDS",
      "eventDate" : "2023-11-29T14:05:54.110+00:00",
      "eventStatus" : "BLOCKING_ERROR",
      "message" : "500 : \"{\"traceID\":\"31382290cb23b4a5\",\"spanID\":\"a2ae2cc8b636ba0c\",\"type\":\"/err/server\",\"title\":\"Server error\",\"detail\":\"Generic error while call EDS Srv Query ep :org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : \\\"{\\\"traceID\\\":\\\"31382290cb23b4a5\\\",\\\"spanID\\\":\\\"69e5ac263d7d27ab\\\",\\\"type\\\":\\\"/err/server\\\",\\\"title\\\":\\\"Server error\\\",\\\"detail\\\":\\\"The id string is malformed\\\",\\\"status\\\":500,\\\"instance\\\":\\\"/internal\\\"}\\\"\",\"status\":500,\"instance\":\"/internal\"}\"",
      "workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.6d134cf1d7c2a5d15cd3cff228a92db7db2aabc5834ff6567c905db71151e0a7.01e0781747^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate" : "2024-11-28T14:05:54.174+00:00"
    }
  ]
}

**Comment by rg-08** [comment]
Buon pomeriggio,
aggiungo che abbiamo tentato di inviare un sostitutivo del sostitutivo e in quel caso abbiamo ricevuto errore:
{
  "traceID" : "abc48c72746c0adf",
  "spanID" : "abc48c72746c0adf",
  "type" : "/msg/record-not-found",
  "title" : "Record non trovato.",
  "detail" : "No Record Found",
  "status" : 404,
  "instance" : "/record-not-found"
}

PUT su https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.120.4.4%5E0AACC153-7AEE-AE4C-E063-959FEA0AC0D0
(dove 2.16.840.1.113883.2.9.2.120.4.4%5E0AACC153-7AEE-AE4C-E063-959FEA0AC0D0 è l'ID documento del primo sostitutivo, ovviamente con l'escape del carattare ^ trasformato quindi in %5E)

requestBody:
{
	"healthDataFormat": "CDA",
	"mode": "ATTACHMENT",
	"tipologiaStruttura": "Ospedale",
	"attiCliniciRegoleAccesso": [],
	"identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^0B4D4562-2817-DA54-E063-959FEA0AD17D",
	"identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.200",
	"tipoDocumentoLivAlto": "REF",
	"assettoOrganizzativo": "AD_PSC069",
	"dataInizioPrestazione": "20231129164122",
	"dataFinePrestazione": "20231129164122",
	"tipoAttivitaClinica": "ERP",
	"identificativoSottomissione": "2.16.840.1.113883.2.9.2.120.4.3.20231129164145486",
	"descriptions": [
		"88.27^RADIOGRAFIA DEL FEMORE, GINOCCHIO E GAMBA\nRadiografia (2 proiezioni) di: femore, ginocchio, gamba^2.16.840.1.113883.2.9.6.1.11"
	],
	"administrativeRequest": "SSN"
}

response:
{
  "traceID" : "4c4c775a681ae21d",
  "spanID" : "4c4c775a681ae21d",
  "type" : "/msg/record-not-found",
  "title" : "Record non trovato.",
  "detail" : "No Record Found",
  "status" : 404,
  "instance" : "/record-not-found"
}

**Comment by IStacchiotti** [comment]
Buonasera, prima di tentare una nuova sostituzione sul documento sostitutivo, dovreste assicurarvi che la prima chiamata di sostituzione sia andata a buon fine (parte asincrona inclusa). Al momento stiamo verificando l'origine dell'errore riscontrato su EDS, vi forniremo aggiornamenti appena disponibili. Grazie

**Comment by rg-08** [comment]
Buongiorno,
ci sono novità riguardo l'errore su EDS?
Grazie.

**Comment by LucaRogledi** [comment]
Buon pomeriggio, sono ancora in corso le verifiche riguardanti l'errore che ha segnalato, riceverà un aggiornamento appena saranno concluse.
Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, Le confermiamo che è stata rilasciato un aggiornamento. La invitiamo cortesemente a riprovare. Rimaniamo a disposizione in caso fosse necessario ulteriore supporto. Grazie

**Comment by vigliottim** [comment]
Buongiorno, le confermiamo che è stata rilasciato un aggiornamento. La invitiamo cortesemente a riprovare. Rimaniamo a disposizione in caso fosse necessario ulteriore supporto. Grazie.

**Comment by rg-08** [comment]
Buongiorno,
abbiamo tentato di nuovo la transazione relativa ad un sostitutivo del sostitutivo e continuiamo a ricevere errore, sia pubblicando tramite middleware di Regione Lazio, sia direttamente vero GW.

Questa la risposta da middleware Lazio:
{
  "traceID" : "cf1225caae69e1ed",
  "spanID" : "cf1225caae69e1ed",
  "type" : "/msg/record-not-found",
  "title" : "Record non trovato.",
  "detail" : "No Record Found",
  "status" : 404,
  "instance" : "/record-not-found"
}
workflowInstanceId della prima pubblicazione:
2.16.840.1.113883.2.9.2.120.4.4.b5cb6bd75f1e8c459945c8fd899a4757b413dab4ce730787aa0e8df2d707e214.865d5bfdb7^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

workflowInstanceId del sostitutivo:
2.16.840.1.113883.2.9.2.120.4.4.c558e2e769c7b47e34c254687233d2eb64a4c65206ea30075c19eaafe88a0614.ba636da34b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId


Questa la risposta da GW:
{
  "traceID" : "79a35936d041efab",
  "spanID" : "79a35936d041efab",
  "type" : "/msg/record-not-found",
  "title" : "Record non trovato.",
  "detail" : "No Record Found",
  "status" : 404,
  "instance" : "/record-not-found"
}
workflowInstanceId della prima pubblicazione:
2.16.840.1.113883.2.9.2.120.4.4.3c6a1867bb17e4362e7c9aa914315ac6b95482401837bf4299b58ae248454b9d.2000c0e84c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

workflowInstanceId del sostitutivo:
2.16.840.1.113883.2.9.2.120.4.4.1ef7f28e76bb194df874d3b001f795e782efe79cd65fb197103d90972ddb1155.ef943eb7d6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

**Comment by LucaRogledi** [comment]
Buongiorno, Le confermiamo che è stata rilasciato un aggiornamento. La invitiamo cortesemente a riprovare. Rimaniamo a disposizione in caso fosse necessario ulteriore supporto. Grazie

**Comment by rg-08** [comment]
Buongiorno, confermiamo che ora la pubblicazione del sostitutivo del sostitutivo va a buon fine.
Grazie

**Comment by vigliottim** [comment]
Grazie per il feedback, procediamo alla chiusura della presente issue e rimaniamo a disposizione per ulteriori chiarimenti.
