### ISSUE TITLE
Error 403 AuthorizationContentDeny in documents/validation

### ISSUE THREAD

**Issue by rbsoftwaresrl** [ministero-salute/it-fse-support#529]
Buongiorno,
una volta messo apposto i Token, sto cercando di invocare il servizio di Validazione utilizzando l'URL 
**https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation** ed un documento CDA scaricato dagli esempi.
Purtroppo ricevo l'errore:
X-Backside-Transport: FAIL FAIL
Connection: Keep-Alive
Transfer-Encoding: chunked
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
Server: GovWay-SOGEI
Pragma: no-cache
GovWay-Transaction-ErrorType: AuthorizationContentDeny
GovWay-Transaction-ID: 9f581969-8d38-11ee-91c5-005056ae54fa
Date: Mon, 27 Nov 2023 16:19:38 GMT
Vary: *
X-Content-Type-Options: nosniff
Content-Type: application/problem+json
X-Global-Transaction-ID: 3f7e3e2d6564c19a5099e60d{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"9f581969-8d38-11ee-91c5-005056ae54fa"}

Questi i 2 Token:
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGZFRDQ0ExMmdBd0lCQWdJVUtCYnZBRHdjdTJ0UHVuTCtIOFVpREdQakxLSXdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekV4TWpJeE5qRTVNREZhRncweU5qRXhNakl4TmpFNU1EQmFNSFl4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVI4d0hRWURWUVJoREJaRFJqcEpWQzFRVWs5V1FWZ3dNRmd3TUZnd01EQlpNU1V3SXdZRFZRUUREQnhUTVNNeE1URWpVa0pUVDBaVVYwRlNSVU5GVGxSRlVsTlNURmhZTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1SnRzd0FwWUQwRkpGTVBUYjRxbWw4VFUzdE1HSDBBbmcrRVFsVVdQSHRPK3JucVJQRnFJYlRJT0kxY0hyRjJkSlNlSVFEdW9pRzNZajY3bTRuSWFsRlJPanVkUFozMGUrS0tFQ3lWNWV3MlRhV3ZsYU91blZtQ2dGNVZYbU5PRWkzOUhrVTBRQzNWUTg3T29ucnFYYXkzYno3ZDB3b0ZuYytIdUV1RkFTMjYrWmluMVJOUFdJaFIzYzZYZW9pUDBSYXBYK2wxV0V2aVE4M2s3bnlMeFhLUjNXVGtQYlhXOFVheS82cjFTbFA5MWllRm14ZTBFcE82NTJmazdYTitpbW04ZmdUTmhWUzdHNCtyTnJyTmc3ay9CekhrTnhDNHlBQ0lXd083TWduMTB6bFdsblN2RFdPQUQ0L1dJQnZRc0NVb3BKTVpVSGRENXdnYkhqb3NNalFJREFRQUJvNElCR0RDQ0FSUXdId1lEVlIwakJCZ3dGb0FVRmptcEdnV0p0dzh0c2pYdHdnbWF4UU9ESWo4d0VnWURWUjBnQkFzd0NUQUhCZ1VyVEIwQkN6Q0JyUVlEVlIwZkJJR2xNSUdpTUlHZm9JR2NvSUdaaG9HV2FIUjBjSE02THk5allYTnZaMlZwYzNacGJDNXpiMmRsYVM1cGRDOWxhbUpqWVM5d2RXSnNhV04zWldJdmQyVmlaR2x6ZEM5alpYSjBaR2x6ZEQ5amJXUTlZM0pzSm1semMzVmxjajFEVGlVelJFTkJLMDFwYm1semRHVnlieXRrWld4c1lTdFRZV3gxZEdVclZHVnpkQ1V5UTA4bE0wUk5hVzVwYzNSbGNtOHJaR1ZzYkdFclUyRnNkWFJsSlRKRFF5VXpSRWxVTUIwR0ExVWREZ1FXQkJTZlRaVWFJWldySGwzZjB6azJuck1SWW9rNlN6QU9CZ05WSFE4QkFmOEVCQU1DQmtBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFIdE01UDFYN3h2eGJsT3UxK3hpRDZIWWlvT0xUL0hxUWtvVG1XTElmMFVkNjRSdklIcE10T2FDUFRCdHoxcTFBdWIvbGk2OTE2N0JTT21abnlXY2xJOUVFYnlLWDNXdWRuYWhiL0N6VTh4ci9McUsrcWJUTU5KTnAweFQ0cWFFTzR5U2tHYWs3VnNnMlNEY2NtendzcEJ4ajRrZ1UwTmhqeTJKTkw5MDZzT3VWK2N1QzdIcTFuWWg5dURmcTR6RmNDN1VZa054d0xlMWlhVzdQSVNIYnJYeURoNGZSTjIxRVlrSHJHUW1NbU9Cb0dTdzl6aHIwdGNyMW9UdytyQWI2UXhCWVpyWDFZbHF2TDJnMUNBSHRqdGNLMDYxU2tZS1FRNXdzS3hrZjkrKytoRzR3TjZJVzZzSk1pYVhtVU5pT3JOYlVaVVBkRzNvL3ZUVzhOSnBKbWRJendocHd6b1M5N2lPYjZwMWkrMWRHYlNja2hRQTBuYi8yZzE1MG1ueUVobDhrL3JmTTh5TittUHRBY0lmUzY4ZUwxZ2dzaTY5QXlVbXA1MDBJdCtlQVBaS0pXWUxoK0xJMThkQ00yTjR0b1BDQTlFWlcxczlhenVUWVpIaEo1SWpVZU9paG44bjNFQS9PaW14YUkxNEVrcENWN2pTM1NLZ3RGZklwZWZLWG1nTFBKOVlkclBVaGtRZVg0Z2ozaHhteFRWOWZWQlgvYzlucWpnV3F3YTUzK3MzYldpODNnUXJKZE83S2V4MGkwM29rMm5SY04zdG9JNFUwS1N6K3JtZGNuWldmdHN1d3dTWjlyaG9QMk80N21XYnFLM2w4WGxMTDd5WWsvZUJrWE1iNkkvZnZVTzNrQkNYTlhqNFJlZkRKcWUzNHRHV0toQVFzcHhjWFkveCJdfQ.eyJpc3MiOiJhdXRoOlMxIzExMVJCU09GVFdBUkVDRU5URVJTUkxYWCIsImlhdCI6MTcwMTEwMTk3NywiZXhwIjoxNzAxMTA1NTc3LCJqdGkiOiIyMTg0YTljOS1hMTAxLTRmNjAtYjE0OS1iNGVlYjI0YmRmNmEiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJzdWIiOiJQUk9WQVgwMFgwMFgwMDBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08ifQ.bLtaycrM680hhu7nF58iI3WBGY9Sr9rJh0Xkc_HI7uHQYbIMOEv3uuqXeHIr6S0Rfd1yRTmjrcyZKAwA_NOCnk1enm4oQ2mXjMxThMEg0DEj1y5MLYz6wRzPWjOllL0o2kpoxAWViUeMNP_VAGwYNl5TadWEONi4gvtdQKLUnFon269Q6ofZJQzK73nlbNRU-6VgIJsd4ynL5rgI3QeyDZArpOwZucuArgRQTobvCme5geJbIauhsiU5jcKJA_6llS0-JZ1sBKBKB9L3Vy9swQryLw4rAOpLuBH8to0C1vBOr04_uILo3UTZekZ4GU4izlJOxyyreV9zYvzmybADKQ

FSE-JWT-Signature: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGZFRDQ0ExMmdBd0lCQWdJVUtCYnZBRHdjdTJ0UHVuTCtIOFVpREdQakxLSXdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekV4TWpJeE5qRTVNREZhRncweU5qRXhNakl4TmpFNU1EQmFNSFl4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVI4d0hRWURWUVJoREJaRFJqcEpWQzFRVWs5V1FWZ3dNRmd3TUZnd01EQlpNU1V3SXdZRFZRUUREQnhUTVNNeE1URWpVa0pUVDBaVVYwRlNSVU5GVGxSRlVsTlNURmhZTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1SnRzd0FwWUQwRkpGTVBUYjRxbWw4VFUzdE1HSDBBbmcrRVFsVVdQSHRPK3JucVJQRnFJYlRJT0kxY0hyRjJkSlNlSVFEdW9pRzNZajY3bTRuSWFsRlJPanVkUFozMGUrS0tFQ3lWNWV3MlRhV3ZsYU91blZtQ2dGNVZYbU5PRWkzOUhrVTBRQzNWUTg3T29ucnFYYXkzYno3ZDB3b0ZuYytIdUV1RkFTMjYrWmluMVJOUFdJaFIzYzZYZW9pUDBSYXBYK2wxV0V2aVE4M2s3bnlMeFhLUjNXVGtQYlhXOFVheS82cjFTbFA5MWllRm14ZTBFcE82NTJmazdYTitpbW04ZmdUTmhWUzdHNCtyTnJyTmc3ay9CekhrTnhDNHlBQ0lXd083TWduMTB6bFdsblN2RFdPQUQ0L1dJQnZRc0NVb3BKTVpVSGRENXdnYkhqb3NNalFJREFRQUJvNElCR0RDQ0FSUXdId1lEVlIwakJCZ3dGb0FVRmptcEdnV0p0dzh0c2pYdHdnbWF4UU9ESWo4d0VnWURWUjBnQkFzd0NUQUhCZ1VyVEIwQkN6Q0JyUVlEVlIwZkJJR2xNSUdpTUlHZm9JR2NvSUdaaG9HV2FIUjBjSE02THk5allYTnZaMlZwYzNacGJDNXpiMmRsYVM1cGRDOWxhbUpqWVM5d2RXSnNhV04zWldJdmQyVmlaR2x6ZEM5alpYSjBaR2x6ZEQ5amJXUTlZM0pzSm1semMzVmxjajFEVGlVelJFTkJLMDFwYm1semRHVnlieXRrWld4c1lTdFRZV3gxZEdVclZHVnpkQ1V5UTA4bE0wUk5hVzVwYzNSbGNtOHJaR1ZzYkdFclUyRnNkWFJsSlRKRFF5VXpSRWxVTUIwR0ExVWREZ1FXQkJTZlRaVWFJWldySGwzZjB6azJuck1SWW9rNlN6QU9CZ05WSFE4QkFmOEVCQU1DQmtBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFIdE01UDFYN3h2eGJsT3UxK3hpRDZIWWlvT0xUL0hxUWtvVG1XTElmMFVkNjRSdklIcE10T2FDUFRCdHoxcTFBdWIvbGk2OTE2N0JTT21abnlXY2xJOUVFYnlLWDNXdWRuYWhiL0N6VTh4ci9McUsrcWJUTU5KTnAweFQ0cWFFTzR5U2tHYWs3VnNnMlNEY2NtendzcEJ4ajRrZ1UwTmhqeTJKTkw5MDZzT3VWK2N1QzdIcTFuWWg5dURmcTR6RmNDN1VZa054d0xlMWlhVzdQSVNIYnJYeURoNGZSTjIxRVlrSHJHUW1NbU9Cb0dTdzl6aHIwdGNyMW9UdytyQWI2UXhCWVpyWDFZbHF2TDJnMUNBSHRqdGNLMDYxU2tZS1FRNXdzS3hrZjkrKytoRzR3TjZJVzZzSk1pYVhtVU5pT3JOYlVaVVBkRzNvL3ZUVzhOSnBKbWRJendocHd6b1M5N2lPYjZwMWkrMWRHYlNja2hRQTBuYi8yZzE1MG1ueUVobDhrL3JmTTh5TittUHRBY0lmUzY4ZUwxZ2dzaTY5QXlVbXA1MDBJdCtlQVBaS0pXWUxoK0xJMThkQ00yTjR0b1BDQTlFWlcxczlhenVUWVpIaEo1SWpVZU9paG44bjNFQS9PaW14YUkxNEVrcENWN2pTM1NLZ3RGZklwZWZLWG1nTFBKOVlkclBVaGtRZVg0Z2ozaHhteFRWOWZWQlgvYzlucWpnV3F3YTUzK3MzYldpODNnUXJKZE83S2V4MGkwM29rMm5SY04zdG9JNFUwS1N6K3JtZGNuWldmdHN1d3dTWjlyaG9QMk80N21XYnFLM2w4WGxMTDd5WWsvZUJrWE1iNkkvZnZVTzNrQkNYTlhqNFJlZkRKcWUzNHRHV0toQVFzcHhjWFkveCJdfQ.eyJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExUkJTT0ZUV0FSRUNFTlRFUlNSTFhYIiwiaWF0IjoxNzAxMTAxOTc3LCJleHAiOjE3MDExMDU1NzcsImp0aSI6IjU5ZmY5ZjMwLWQ3NjQtNGJjMi05NTI4LTM0MDYzMjU1MjFjOCIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInN1YiI6IlBST1ZBWDAwWDAwWDAwMFleXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMTgwIiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb25lIENhbGFicmlhIiwibG9jYWxpdHkiOiIxODAwODAwMzIiLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwZXJzb25faWQiOiJTU1NNTk43NUIwMUYyNTdMXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJwYXRpZW50X2NvbnNlbnQiOnRydWUsInB1cnBvc2Vfb2ZfdXNlIjoiVFJFQVRNRU5UIiwiYWN0aW9uX2lkIjoiQ1JFQVRFIiwicmVzb3VyY2VfaGw3X3R5cGUiOiIoMTE1MDItMl5eMi4xNi44NDAuMS4xMTM4ODMuNi4xKSIsImF0dGFjaG1lbnRfaGFzaCI6IiIsInN1YmplY3RfYXBwbGljYXRpb25faWQiOiIxIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZW5kb3IiOiJSQlNvZnR3YXJlIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiMSJ9.Fp5EQUBr2IlaEim--hegQkxheOVH5ZmB9Vs7OIrkRbpUO4WA2B4o43LBeIMAQbvE6AZUPystkaT-HhrrGMYxAqhEeW60n1-CFGkTsvrmKXyfGIW4HPkvnyuyzMF0_JDoR2GP92dB8n9pu1JmISC6p1GrVu5nUw4Bs48z4-gHE3NT61QGUj4WiqhZw426TsKpcjZ8x81QZS5vnIV17sGdz8ZeFeWUeQ2YeishQSHTlwvl_g8U8oZDYpvjj7AJbpWVGpbNHsyJaMzge6Mi91jLHtvmEkaC0UIroU8ewRS6DePcY6y02qsBANKQTrdc8a3Vni2ljytngcU1pUH-yIHYCQ

Ho settato nel Token JWT ho settato il valore del campo "person_id" uguale a quello del PDF che allego ("SSSMNN75B01F257L^^^&2.16.840.1.113883.2.9.4.3.2&ISO")

[CDA_ATTACHMENT.pdf](https://github.com/ministero-salute/it-fse-support/files/13477677/CDA_ATTACHMENT.pdf)

Quale potrebbe essere l'errore?

**Comment by rbsoftwaresrl** [comment]
CN = A1#111#RBSOFTWARECENTERSRLXX
2.5.4.97 = CF:IT-PROVAX00X00X000Y
O = Ministero della Salute
C = IT

Questi sono i dati presenti nel certificato che mi è stato inviato in seguito all'invio della CSR

**Comment by LucaRogledi** [comment]
Buongiorno, confermiamo che ora la richiesta va a buon fine.
Procediamo con la chiusura della issue e restiamo a disposizione in caso di ulteriore supporto.
Grazie.
