### ISSUE TITLE
serizio status - TokenAuthenticationRequired error

### ISSUE THREAD

**Issue by MarcoKnezevichInsiel** [ministero-salute/it-fse-support#53]
Buongiorno,

tentando di invocare il servizio di `status` con il seguente `workflowInstanceId`:
`2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.3bee7074d8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId`

viene restituito il seguente errore:
`
"responseGatewayDto": {
    "traceID": null,
    "spanID": null,
    "workflowInstanceId": null,
    "type": "https://govway.org/handling-errors/401/TokenAuthenticationRequired.html",
    "title": "TokenAuthenticationRequired",
    "status": 401,
    "detail": "A token is required",
    "instance": null,
    "govwayId": null,
    "warning": null
  }`
```
anche se il token di autorizzazione è stato inviato ed è il seguente:
Authorization: Bearer eyJ4NWMiOlsiTUlJRkZ6Q0NBditnQXdJQkFnSVVEb1RTNGVUalZhYzdOS3NzZ0tXbWI0SXRaVlF3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TWpBNE1Ea3lNekkxTXpGYUZ3MHlOVEE0TURreU16STFNekJhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMwd05qQXdNREF3TURBd01EQllXREVhTUJnR0ExVUVBd3dSVXpFak1EWXdNREF3TURBd01EQXdXRmd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ0VFVTVNQkJ4Z0pQVnQrWjhOSDNDeldUZFFHdGt6Z1BKbWlJdnk1L3Y1M3NJZVorWVJvcDdtTG13ZlJFY25BTGFBYVpNczROUkVOdTFZT1czSWc1T1pPc2l4U3N4blJOUW5OaStienVQaGNGeHd0NWhaSFlUNktHMEYwUUdqT1NBbkxLNm5xc2NOTm1FOVk0MXJDd3pmdWtDb3hXZ0tLSnRpTjdBL2RwQ0YvWlNJbFh0Yk9aK2s1cmUrTVZOOGJFOWQ4RmJicnM2UnhPdXNueCt1enVvMERqUlpMOEsrMnhuY3gzSUxFQUw5V2RoTmtWMUJtKys0Yys5TERnSTAwRVRjQlRtUU04SXdqN0pOV3dOT2dhcVRTdFFrMi9aVWtSWWRmQUI5SzBPQ2pVVlJyVHBBZzdsUlJPbEF0VGxFWjV5SFJlbnJhSVlnM0xFdlpaYlo1OHRmQWdNQkFBR2pnY2d3Z2NVd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3Y3dZRFZSMGZCR3d3YWpCb29HYWdaSVppYkdSaGNEb3ZMMk5oWkhNdVptbHVZVzU2WlM1cGRDOURUajFEUVNVeU1FMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbEpUSXdWR1Z6ZEN4UFBVMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbExFTTlTVlF3SFFZRFZSME9CQllFRkVjMDEvL1M4eUovL3RkSCs0cDVnN1JUK1Rnb01BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQVBudGRvQlpDcU1hWHkyT3plWGhQYTZQbHNBUHphVDhLTVVjY2VKYy9PNXNEaDZ2RnRIbVJZdUNOOGV2MDZFd0ZreW5DS3dwRHFlanVrR0pwbTRLNXpSc21xTHNmZk0wTUszSVVLMFg4QVZ2R1RXaUFBSWRSNitRTEphR0ZaSHJIZk9tTU4xSGc1S3AxYUI1ZmlBVytrSjNRSkZLeS9EY3Nab2Q3REFBM0dZNVQzSVpvQ2RUVERpU2gyUXE2MG9NZ3RaTGtnMG9XWTNEUzAwMTVhandwRldhN3Fjd1h4YnNaa2huNTZ1VVdGaUExdzV1TEJ2ajVPdWlaOExJWnlWRWJ0RFo2TTBpMEhudVJhdHRpWGdzckJUZmVFb0VwR21kblg0MUxUbXVSNEIwb2JqdlVxTkNIY21ONGs3RndqL0R5SnVsdlQyYkVHc0VhbXg4d3RSOGtwcGphMG9mcnBzTkkySGhkZjkzUWZzcW5JemZ5QnE0bG0xTmp2VlRwZHc5b3FIZmtqKzhGd1Z5WVROUGxEeDhKN2pYNWNjcUNQUHVSZGh1d2plYTFjY3hic0g4Ty9nak5kQmhya2JFRWdyUGRMckRTMjlqQlAvZk56MHVlRmxia29xZjRMNTdWWDd4WitOTUQ4U2pmNDMvUmpMQ3NWSEpWQndkQ2p5SVgybWlXZ3NoYU0vVmlQUk9yOHhKa3o0UFFwTTkvWkdyOFJ3NktoWXhDVVp5blp4UGxvRGM2MThUNzgyQXZqNmNsTmZEQWZlWkpTa1BXUGVjMHlGV2tHZEVLRUwyMk1ram9IcnVvMEt2K3NVUGlwNDhJUDJQa1NzRGNRYjI3dEJtYnB6aG00b0UyR09Mc2RZQk5KdjVpeDBGUnVDellEeXpIb3kzQ2FJdDV1SmtRV1JRPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOm51bGwsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsIm5iZiI6MTY3MzYyNTc0MSwiaXNzIjoiYXV0aDpTMSNudWxsIiwiZXhwIjoxNjczNzEyMTQxLCJpYXQiOjE2NzM2MjU3NDEsImp0aSI6IjdiMzZkNTljLTc0NTMtNDNlZC1iODhhLTRjNTExZThhMWZkYiJ9.dQuwu7oAnpDDOyyEAxGRaz9bAzdKYKqQyOphDiixrltY9bVo49xVgQBnleQ2cVcE6ypMyNOS0j50qZYfzoqBLSqGiMNfdEi1yJKVIqwmiIR0CvwHhIrTsqPVvYZchC_RJSbdQxq6Otn6RE6l7UrZTQ35yXg4q4uRBIIcUFe467n3fPfJqsx6uz9yKvrE80n0Hs7Y_jBWt9VpRF0HX-4hooTfO3lMFAOVDD5pOHc2seUL1P1hZ8wkM4rOqbVuNaD4A-D-OU6u4ki6P7Og8kfhMjUzp8tms2xKmD5E5WWCI7xXHGjEFPvSBWKVo1hcFV8n3aT6OE5JF7LTDbzI5aadKQ

Dai log emerge anche il seguente errore, sembra che sia richiesto il token `FSE-JWT-Signature` ma non dovrebbe essere previsto per questa transazione:
"HTTP/1.1 401 Unauthorized[\r][\n]" 
"X-Backside-Transport: FAIL FAIL[\r][\n]" 
"Connection: Keep-Alive[\r][\n]" 
"Transfer-Encoding: chunked[\r][\n]" 
"Expires: 0[\r][\n]" 
"Cache-Control: no-cache, no-store, must-revalidate[\r][\n]" 
"Server: GovWay-SOGEI[\r][\n]" 
"Pragma: no-cache[\r][\n]" 
"GovWay-Transaction-ErrorType: TokenAuthenticationRequired[\r][\n]" 
"GovWay-Transaction-ID: 65724eb7-9350-11ed-b06a-005056ae7395[\r][\n]" 
"Date: Fri, 13 Jan 2023 16:02:41 GMT[\r][\n]" 
"WWW-Authenticate: Bearer realm="FSE-JWT-Signature", error="invalid_request", error_description="The request is missing a required token parameter"[\r][\n]" 
"Vary: *[\r][\n]" 
"X-Content-Type-Options: nosniff[\r][\n]" 
"Content-Type: application/problem+json[\r][\n]" 
"X-Global-Transaction-ID: 3f7e3e2d63c180a021e49edd[\r][\n]"

**Comment by zukka77** [comment]
@MarcoKnezevichInsiel riapro perchè controlliamo coerenza tra le specifiche e i controlli fatti da govway, ti facciamo sapere

**Comment by IStacchiotti** [comment]
Buongiorno Marco, le chiediamo cortesemente di ritentare. L'errore infatti non dovrebbe più verificarsi non essendo più necessario fornire il FSE-JWT-Signature all'endpoint "status". Grazie mille.

**Comment by MarcoKnezevichInsiel** [comment]
Abbiamo ritentato, ma otteniamo un errore diverso legato al content-type, da specifica dovrebbe essere `application/json`
ma viene restituito:
```
{
  "traceID": null,
  "spanID": null,
  "warning": null,
  "type": "https://govway.org/handling-errors/400/InvalidRequestContent.html",
  "title": "InvalidRequestContent",
  "status": 400,
  "detail": "Request content not conform to API specification: Content-Type 'application/json' unsupported",
  "instance": null,
  "govwayId": null,
  "workflowInstanceId": null,
  "message": null,
  "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}
```

**Comment by MarcoKnezevichInsiel** [comment]
Buongiorno, nuovo errore eliminando il content-type. Adesso viene restituito 403 e AuthorizationContentDeny.
l'auth token viene passato nella request.

Allego i log della transazione:


`org.apache.hc.client5.http.wire - http-outgoing-1 >> "GET /govway/rest/in/FSE/gateway/v1/status/2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.91519de9a7%5E%5E%5E%5Eurn:ihe:iti:xdw:2013:workflowInstanceId HTTP/1.1[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 >> "Accept: application/json, application/*+json[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 >> "Authorization: Bearer eyJ4NWMiOlsiTUlJRkZ6Q0NBditnQXdJQkFnSVVEb1RTNGVUalZhYzdOS3NzZ0tXbWI0SXRaVlF3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TWpBNE1Ea3lNekkxTXpGYUZ3MHlOVEE0TURreU16STFNekJhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMwd05qQXdNREF3TURBd01EQllXREVhTUJnR0ExVUVBd3dSVXpFak1EWXdNREF3TURBd01EQXdXRmd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ0VFVTVNQkJ4Z0pQVnQrWjhOSDNDeldUZFFHdGt6Z1BKbWlJdnk1L3Y1M3NJZVorWVJvcDdtTG13ZlJFY25BTGFBYVpNczROUkVOdTFZT1czSWc1T1pPc2l4U3N4blJOUW5OaStienVQaGNGeHd0NWhaSFlUNktHMEYwUUdqT1NBbkxLNm5xc2NOTm1FOVk0MXJDd3pmdWtDb3hXZ0tLSnRpTjdBL2RwQ0YvWlNJbFh0Yk9aK2s1cmUrTVZOOGJFOWQ4RmJicnM2UnhPdXNueCt1enVvMERqUlpMOEsrMnhuY3gzSUxFQUw5V2RoTmtWMUJtKys0Yys5TERnSTAwRVRjQlRtUU04SXdqN0pOV3dOT2dhcVRTdFFrMi9aVWtSWWRmQUI5SzBPQ2pVVlJyVHBBZzdsUlJPbEF0VGxFWjV5SFJlbnJhSVlnM0xFdlpaYlo1OHRmQWdNQkFBR2pnY2d3Z2NVd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3Y3dZRFZSMGZCR3d3YWpCb29HYWdaSVppYkdSaGNEb3ZMMk5oWkhNdVptbHVZVzU2WlM1cGRDOURUajFEUVNVeU1FMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbEpUSXdWR1Z6ZEN4UFBVMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbExFTTlTVlF3SFFZRFZSME9CQllFRkVjMDEvL1M4eUovL3RkSCs0cDVnN1JUK1Rnb01BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQVBudGRvQlpDcU1hWHkyT3plWGhQYTZQbHNBUHphVDhLTVVjY2VKYy9PNXNEaDZ2RnRIbVJZdUNOOGV2MDZFd0ZreW5DS3dwRHFlanVrR0pwbTRLNXpSc21xTHNmZk0wTUszSVVLMFg4QVZ2R1RXaUFBSWRSNitRTEphR0ZaSHJIZk9tTU4xSGc1S3AxYUI1ZmlBVytrSjNRSkZLeS9EY3Nab2Q3REFBM0dZNVQzSVpvQ2RUVERpU2gyUXE2MG9NZ3RaTGtnMG9XWTNEUzAwMTVhandwRldhN3Fjd1h4YnNaa2huNTZ1VVdGaUExdzV1TEJ2ajVPdWlaOExJWnlWRWJ0RFo2TTBpMEhudVJhdHRpWGdzckJUZmVFb0VwR21kblg0MUxUbXVSNEIwb2JqdlVxTkNIY21ONGs3RndqL0R5SnVsdlQyYkVHc0VhbXg4d3RSOGtwcGphMG9mcnBzTkkySGhkZjkzUWZzcW5JemZ5QnE0bG0xTmp2VlRwZHc5b3FIZmtqKzhGd1Z5WVROUGxEeDhKN2pYNWNjcUNQUHVSZGh1d2plYTFjY3hic0g4Ty9nak5kQmhya2JFRWdyUGRMckRTMjlqQlAvZk56MHVlRmxia29xZjRMNTdWWDd4WitOTUQ4U2pmNDMvUmpMQ3NWSEpWQndkQ2p5SVgybWlXZ3NoYU0vVmlQUk9yOHhKa3o0UFFwTTkvWkdyOFJ3NktoWXhDVVp5blp4UGxvRGM2MThUNzgyQXZqNmNsTmZEQWZlWkpTa1BXUGVjMHlGV2tHZEVLRUwyMk1ram9IcnVvMEt2K3NVUGlwNDhJUDJQa1NzRGNRYjI3dEJtYnB6aG00b0UyR09Mc2RZQk5KdjVpeDBGUnVDellEeXpIb3kzQ2FJdDV1SmtRV1JRPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOm51bGwsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsIm5iZiI6MTY3NjMwODY4NSwiaXNzIjoiYXV0aDpTMSNudWxsIiwiZXhwIjoxNjc2Mzk1MDg1LCJpYXQiOjE2NzYzMDg2ODUsImp0aSI6ImVlNzkxYjAzLWNkNGMtNGRmOC1iZDU5LTE2NTRlZDVkMzI0OSJ9.ZXZmFpc9-eVeeUtNJL54ixzLpl1FzybU-HAEfKiAtXLz1vyWz18eZRqjb4upXPnnXemJXgatJtuFtulhETim2YqLLFAoF_CvALkSKDZt556i-OqLAVdoseC-2Sp3N495MXKzCDhZfZhE57EHxuHMbMUNJibR4u1P8XmuEOvmPYk3KCIiEKAJ038nnjKJuxNfmaR3gXQTNhQ5fWyAIMpPMIYBRVWLSwjv1-n1prRvYCq8uP2ztRZQ61Csj6W-CuXiFOvztTIFJTeGJpNwbScg4rkXlJ3-PXIGdwpReuNxh6LN0ZJD3OPpSpLa-WD_SZFl5sZ7ddbxaPSt75KztJMvoA[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 >> "UUIDToken: 803b7f2398e9477a9bb2138146d57da6[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 >> "Accept-Encoding: gzip, x-gzip, deflate[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 >> "Content-Length: 0[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 >> "Host: modipa-val.fse.salute.gov.it[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 >> "Connection: keep-alive[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 >> "User-Agent: Apache-HttpClient/5.1.4 (Java/17.0.2)[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 >> "[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "HTTP/1.1 403 Forbidden[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "X-Backside-Transport: FAIL FAIL[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "Connection: Keep-Alive[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "Transfer-Encoding: chunked[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "Expires: 0[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "Cache-Control: no-cache, no-store, must-revalidate[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "Server: GovWay-SOGEI[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "Pragma: no-cache[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "GovWay-Transaction-ErrorType: AuthorizationContentDeny[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "GovWay-Transaction-ID: c084ffe2-abb7-11ed-9627-005056ae7395[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "Date: Mon, 13 Feb 2023 17:18:43 GMT[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "Vary: *[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "X-Content-Type-Options: nosniff[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "Content-Type: application/problem+json[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "X-Global-Transaction-ID: 3f7e3e2d63ea70f33f26370d[\r][\n]" 
org.apache.hc.client5.http.wire - http-outgoing-1 << "[\r][\n]" 
org.apache.hc.client5.http.headers - http-outgoing-1 << HTTP/1.1 403 Forbidden 
org.apache.hc.client5.http.headers - http-outgoing-1 << X-Backside-Transport: FAIL FAIL 
org.apache.hc.client5.http.headers - http-outgoing-1 << Connection: Keep-Alive 
org.apache.hc.client5.http.headers - http-outgoing-1 << Transfer-Encoding: chunked 
org.apache.hc.client5.http.headers - http-outgoing-1 << Expires: 0 
org.apache.hc.client5.http.headers - http-outgoing-1 << Cache-Control: no-cache, no-store, must-revalidate 
org.apache.hc.client5.http.headers - http-outgoing-1 << Server: GovWay-SOGEI 
org.apache.hc.client5.http.headers - http-outgoing-1 << Pragma: no-cache 
org.apache.hc.client5.http.headers - http-outgoing-1 << GovWay-Transaction-ErrorType: AuthorizationContentDeny 
org.apache.hc.client5.http.headers - http-outgoing-1 << GovWay-Transaction-ID: c084ffe2-abb7-11ed-9627-005056ae7395 
org.apache.hc.client5.http.headers - http-outgoing-1 << Date: Mon, 13 Feb 2023 17:18:43 GMT 
org.apache.hc.client5.http.headers - http-outgoing-1 << Vary: * 
org.apache.hc.client5.http.headers - http-outgoing-1 << X-Content-Type-Options: nosniff 
org.apache.hc.client5.http.headers - http-outgoing-1 << Content-Type: application/problem+json 
org.apache.hc.client5.http.headers - http-outgoing-1 << X-Global-Transaction-ID: 3f7e3e2d63ea70f33f26370d 
o.a.h.c.h.i.classic.MainClientExec - ex-0000000002 connection can be kept alive for 3 MINUTES `

**Comment by masciamariotti** [comment]
Buonasera Marco,
da una prima analisi risultano delle incongruenze nei seguenti parametri contenuti nel JWT:
- sub: è valorizzato a null;
- nbf: non previsto da documentazione;
- iss: non valorizzato correttamente "auth:S1#null".

**Comment by MarcoKnezevichInsiel** [comment]
Buongiorno, grazie della segnalazione, ma sarebbero utili nella restituzioe degli errori un po' più parlanti. Per altro, in questo caso cosa sarebbe corretto porre nel campo `sub`? Grazie

**Comment by masciamariotti** [comment]
Buongiorno Marco,
per la corretta valorizzazione dei campi contenuti nel JWT la rimando al [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#111-campi-contenuti-nei-jwt),
in particolare:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/103249382/218690322-82b2c51c-20bf-46da-bd4c-2a647a75cf7d.png">

**Comment by MarcoKnezevichInsiel** [comment]
Buongiorno, siamo riusciti a far funzionare il servizio. Grazie
