### ISSUE TITLE
CT3 VPS ID="Terapia_Farmacologica_in_Pronto_Soccorso"

### ISSUE THREAD

**Issue by sandroaresu23** [ministero-salute/it-fse-support#531]
Buongiorno,
utilizzando il gtw-certifier abbiamo ricevuto un errore per una errata valorizzazione di una delle seziona del VPS: "id = "Terapia_Farmacologica_in_Pronto_Soccorso" (rif. VALIDAZIONE_CDA2_VPS_CT4.pdf).

Abbiamo utilizzato le specifiche riportate nel foglio excel contenente il caso di test in questione (es. "VPS - Caso di Test 4") - [documentazione](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/2-Verbale%20di%20Pronto%20Soccorso/CDA2_Verbale_Pronto_Soccorso_OK.xlsx).

Da specifiche l'id sezione è da valorizzare come "Terapia_Farmacologica_in_Pronto_Soccorso" (vedi img. sotto) mentre il Gateway si aspetta la valorizzazione come "Terapia_Farmacologica_in_PS", restituendo un'errore.
![image](https://github.com/ministero-salute/it-fse-support/assets/128618821/9e8942b1-16d0-4676-929c-0a70cb37f16c)

Potete verificare?
Grazie

**Comment by LucaRogledi** [comment]
Buon pomeriggio, Le confermiamo che è stato rilasciato un aggiornamento.
La invitiamo cortesemente a riprovare utilizzando il tool aggiornato all'ultima versione disponibile al [link](https://github.com/ministero-salute/it-fse-gtw-tools).
Rimaniamo a disposizione in caso fosse necessario ulteriore supporto, grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto riscontri, procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
