### ISSUE TITLE
Errore di validazione assignedAuthoringDevice nella SSV

### ISSUE THREAD

**Issue by ManuelATP** [ministero-salute/it-fse-support#534]
Salve,

si segnala che, ai fini dei test per l’accreditamento stiamo generando dei CDA2 delle schede di vaccinazione ed è emersa una incompatibilità rispetto ad uno dei controlli dello schematron:

all’interno dell’elemento _author, l’assignedAuthor_ può contenere assignedPerson oppure assignedAuthoringDevice a seconda che l’autore sia una persona fisica oppure un applicativo software; **nel nostro caso adoperiamo assignedAuthoringDevice**.
Ora, nello schematron è presente il seguente controllo:

<let name="name_author" value="hl7:assignedAuthor/hl7:assignedPerson"/>

<assert test="count(hl7:assignedAuthor/hl7:id/@nullFlavor)=1 or count(hl7:assignedAuthor/hl7:id[@root='2.16.840.1.113883.2.9.6.3.2'])=1 or count($name_author/hl7:name)=1">

ma dato che nel nostro CDA forniamo assignedAuthoringDevice anziché assignedPerson, la validazione rispetto allo schematron restituisce erroneamente l’errore associato al controllo suddetto: [ERRORE-27| L'elemento author/assignedAuthor/assignedPerson DEVE avere l'elemento 'name' ] **aspettandosi un elemento name anche in assenza dell’assignedPerson.**

L’errore è bloccante per cui bisognerebbe modificare il controllo creando due distinti check, uno per verificare la presenza di assignedAuthor/id ed un altro per la presenza di assignedPerson/name, in modo che lo schematron non si aspetti un name se non all’interno di un assignedPerson.

**Comment by vigliottim** [comment]
Buongiorno, l'errore che ottiene è dovuto alla valorizzazione dell'elemento _author/assignedAuthor/id_ tramite un codice fiscale e la non presenza dell'elemento _assignedPerson_. Se  l’autore coincide con un dispositivo che genera il documento, l'elemento _author/assignedAuthor/id_ deve essere valorizzato o tramite una p.iva o tramite l'attributo _@nullFlavor_. In questo caso può quindi essere inserito l'elemento _assignedAuthoringDevice_.
Qualora l'errore dovesse persistere, le chiediamo di fornirci il CDA2 per ulteriori analisi. Grazie.

**Comment by ponsilva** [comment]
Buongiorno,
mi inserisco in questo thread perché in alcuni test avevo incontrato un errore simile.

L'errore generico 
"Error while executing validation on sch schematron"
può essere causato da un encoding non corretto del CDA2.

L'encoding previsto e accettato per CDA2 deve essere UTF-8
Se nel CDA2 sono usati altri encoding (ANSI, UTF-8-BOM, ...) si può ricevere l'errore

**Comment by ManuelATP** [comment]
Ciao,

ringrazio entrambe per l'aiuto. Ho appena risottomesso con la codifica corretta ed ottenuto un esito positivo.

Grazie mille.


Manuel Infantino

Healthy Reply
Via Bensi, 1/2
20152 - Milano - ITALY
phone: +39 02 535761
***@***.******@***.***>
www.reply.it<http://www.reply.it> <http://>

[Healthy Reply]
________________________________
Da: Silvana Ponsero ***@***.***>
Inviato: lunedì 11 dicembre 2023 14:54
A: ministero-salute/it-fse-support ***@***.***>
Cc: Manuel Infantino ***@***.***>; Manual ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Errore di validazione assignedAuthoringDevice nella SSV (Issue #534)


Buongiorno,
mi inserisco in questo thread perché in alcuni test avevo incontrato un errore simile.

L'errore generico
"Error while executing validation on sch schematron"
può essere causato da un encoding non corretto del CDA2.

L'encoding previsto e accettato per CDA2 deve essere UTF-8
Se nel CDA2 sono usati altri encoding (ANSI, UTF-8-BOM, ...) si può ricevere l'errore

**Comment by vigliottim** [comment]
Buon pomeriggio, grazie per il riscontro. Procediamo alla chiusura del presente ticket e rimaniamo a disposizione per ulteriori richieste di supporto.
