### ISSUE TITLE
Domande su accreditamento per documento RSA (software procreazione medicalmente assistita)

### ISSUE THREAD

**Issue by Itamedical** [ministero-salute/it-fse-support#535]
Buonasera,

Stiamo controllando le specifiche per l'accreditamento, abbiamo notato che ci sono 4 test case OK (CDA2_RSA OK.xlsx). 

Per procedere ad una prima valutazione delle informazioni richieste nel CDA2 per l'RSA abbiamo filtrato tutti campi obbligatori nella colonna "Obbligatorietà per Test case 4" supponendo che queste fossero tutte le informazioni che devono essere inserite in un RSA. 
Premettendo che noi siamo software per reparti di PMA e che quindi le info documentate sono specifiche a questo scenario medico, abbiamo notato che :

- per alcune di queste informazioni obbligatorie noi abbiamo un singolo campo note mentre voi richiedete un livello di specificità molto più elevato oppure proprio non abbiamo modo di tracciare queste informazioni. 
In allegato un esempio del nostro referto e la sezione del nostro software dove viene generato. Come potete notare sono dei semplici campi note di refertazione della specifica prestazione senza indicazioni riguardanti anamnesi/farmaci/...
Come dobbiamo comportarci per i test di validazione ? 

- secondo le specifiche nazionali di HL7 Italia, nel caso in cui la produzione del documento sia avvenuta contestualmente ad un accesso ambulatoriale, il numero nosologico è facoltativo. Ci conferma questa cosa ? Oppure il numero nosologico è obbligatorio anche per RSA come nella lettera di dimissione ? 

Attendiamo un vostro cortese riscontro e porgo cordiali saluti

![esempio_RSA_schermata_software](https://github.com/ministero-salute/it-fse-support/assets/152193041/16d40416-c278-453d-a684-0120e4a89e90)

[esempio_RSA.pdf](https://github.com/ministero-salute/it-fse-support/files/13548828/esempio_RSA.pdf)

**Comment by IStacchiotti** [comment]
Buongiorno, rispondiamo di seguito al primo punto: filtrando i campi obbligatori nella colonna "Obbligatorietà per Test case 4", si ottiene il set di elementi richiesti per superare lo specifico caso di test (il 4 in questo caso). Se il vostro applicativo non gestisce le informazioni necessarie per completare il test case secondo le indicazioni riportate nel file excel, è possibile dichiararlo "non applicabile" nella checklist richiesta per l'accreditamento (sarà sufficiente indicare "NO" nell’apposita colonna "applicabilità", giustificandolo opportunamente nella colonna "razionale di applicabilità").

In merito al secondo punto, abbiamo preso in carico la richiesta, le faremo sapere appena possibile.

Grazie

**Comment by LucaRogledi** [comment]
Buongiorno,
Riguardo il secondo punto, confermiamo quanto riportato nella documentazione HL7. 
In caso di produzione di un documento contestualmente ad un accesso ambulatoriale, la sezione `<componentOf>/<encompassingEncounter>/<id>` è opzionale.
Restiamo a disposizione per ulteriori chiarimenti.

Grazie

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto riscontri, procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
