### ISSUE TITLE
Accreditamento A1#111HTINFORMATICAXX

### ISSUE THREAD

**Issue by ftallaro** [ministero-salute/it-fse-support#536]
Buonasera,

abbiamo ricevuto l'email del mancato accreditamento. Nel motivo c'è scritto che "Claims(appId,appVersion,appVendor) della chiamata al gtw differenti da quelli dichiarati nel data.json"

Io ho controllato gli invii che ho fatto e non mi risulta questo errore oppure ho capito male io qualcosa.

Potete aiutarmi dandomi una evidenza anche di 1 solo caso?

Ad esempio un intestazione json utilizzato era il seguente:

{"sub":"TLLFBA73E16A494C^^^&2.16.840.1.113883.2.9.4.3.2&ISO","subject_role":"AAS","purpose_of_use":"TREATMENT","iss":"S1#111HTINFORMATICAXX","subject_application_id":"HTSANg","subject_application_vendor":"HTINFORMATICA SRL","subject_application_version":"3.1.0","locality":"206123456","aud":"https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1","subject_organization_id":"190","subject_organization":"Regione Sicilia","patient_consent":"true","action_id":"CREATE","resource_hl7_type":"('34105-7^^2.16.840.1.113883.6.1')","jti":"231128144400","person_id":"TSTTTN71A01H501B^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO","pem_path":"/usr/htsan/jar/S1#111HTINFORMATICAXX.pem","p12_path":"/usr/htsan/jar/signature.p12"}

e nel data.json ho inserito le seguenti informazioni:

"appVendor": "HTINFORMATICA SRL",
"appID": "HTSANg",
"appVersion": "3.1.0"

Inoltre mi è venuto un altro dubbio che vi chiedo visto che forse dovrò rifare gli invii una volta capito dove possa risiedere l'attuale errore.

Nel data.json nel campo "ts" ho inserito la data e l'orario d'invio al minuto. Serve indicare fino al secondo? Se si qual'è l'orario esatto che si aspetta ricevere?

Grazie.

**Comment by ftallaro** [comment]
Buongiorno,

ok. quando eseguirete il test?

Grazie a lei

**Comment by LucaRogledi** [comment]
Confermiamo che i test sono stati rieseguiti, ma l'errore persiste.
Stiamo procedendo con le analisi riguardanti la causa dell'errore.
Riceverà un riscontro, appena saranno terminate le verifiche.
Grazie

**Comment by ftallaro** [comment]
ok rimango in attesa, con la speranza che i tempi non siano troppo lunghi.

Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno,
da ulteriori analisi è emerso che, il workflowInstanceId inserito nel data.json per l'accreditamento risulta: "2.16.840.1.113883.2.9.2.190.4.4.a4615b2511b151a89b72258025fa10c8c0c0ca8c1a5ab3a5b4bb94c7790c47a1.**b29b32a13f**^^^^urn:ihe:iti:xdw:2013:workflowInstanceId", 
quindi errato in quanto non abbinato al traceId: "e1eeaf97393dae6f".

Il workflowInstanceId ricevuto in risposta in seguito alla chiamata associata al caso di test id: "9" e traceId: "e1eeaf97393dae6f" corrisponde invece a: "2.16.840.1.113883.2.9.2.190.4.4.a4615b2511b151a89b72258025fa10c8c0c0ca8c1a5ab3a5b4bb94c7790c47a1.**327a6c47b3**^^^^urn:ihe:iti:xdw:2013:workflowInstanceId".

La invitiamo pertanto ad effettuare le dovute correzioni al file data.json e a sottomettere una nuova Pull Request per la sottomissione delle medesime, prestando sempre attenzione (se doveste eseguire nuove invocazioni ai fini dell'accreditamento) che la tripletta identificativa del software nei token corrisponda esattamente alla tripletta dichiarata nel data.json contenuto nella pull request.
Grazie

**Comment by ftallaro** [comment]
Buongiorno,

ho rincrontrollato tutto il data.json e sembrerebbe che quello sia l'unico caso in cui ho trascritto il numero di workflowInstanceId  in modo errato. Non ho modificato il report in quanto li era stato riportato in modo corretto.

Ho già fatto la nuova pull request https://github.com/ministero-salute/it-fse-accreditamento/pull/1046

Pensa che riusciate per oggi ad eseguire un nuovo test?

Grazie.

**Comment by ftallaro** [comment]
Ok, rimango in attesa.

La pull request comunque è ancora li, spero venga fatto il merge per oggi prima delle varifiche automatiche.

**Comment by ftallaro** [comment]
Buongiorno, abbiamo ricevuto la conferma che i test sono stati superati.

Adesso il passi da effettuare per la pubblicazione quali sono? Possiamo inviare già adesso i documenti in formato 2.0 utilizzando i canali dell'FSE 1.0 nella regione Sicilia?

**Comment by IStacchiotti** [comment]
Buongiorno, in merito all'accreditamento per il servizio di pubblicazione, le segnaliamo che al momento è sospeso.
La invitiamo a seguire il canale #fse su Slack per ricevere eventuali aggiornamenti.
Dal momento che i test automatici sono stati superati con successo, chiudiamo il presente ticket.
Sarà possibile aprire una nuova issue per ulteriori richieste di supporto, grazie.
