### ISSUE TITLE
Problemi accesso https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1 (HTTP 401)

### ISSUE THREAD

**Issue by mlacamera** [ministero-salute/it-fse-support#537]
Salve,
stiamo effettuando i test di integrazione (A1#111#HLTMANAGEMENTSRLXX) ma nonostante produciamo correttamente il token jwt di accesso la piattaforma (https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1) continua a darci accesso non autorizzato (HTTP401 TokenAuthenticationFailed). Potreste verificare se a livello di accesso le nostre impostazioni sono valide?

**Comment by LucaRogledi** [comment]
Buongiorno,
Potrebbe gentilmente allegare i token utilizzati nell'invocazione e la risposta completa ricevuta dal sistema contenente "govway_id" e "traceId" se disponibili.
Grazie.

**Comment by mlacamera** [comment]
In allegato
[JWTToken_inchiaro.txt](https://github.com/ministero-salute/it-fse-support/files/13579322/JWTToken_inchiaro.txt)
[JWTToken_sigend.txt](https://github.com/ministero-salute/it-fse-support/files/13579323/JWTToken_sigend.txt)

trace_id è nullo gateway_id non è presente nella risposta

**Comment by LucaRogledi** [comment]
Buongiorno,
Come riportato dal tool online allegando i token forniti: https://jwt.io/ , il campo x5c risulta malformato (è valorizzato con un array di valori).
Le chiederemmo di verificare che i token siano stati generati utilizzando il certificato di firma del fornitore (che dovrebbe iniziare per "S11").
In caso possano esservi utili, ricordiamo che sono disponibili i tool in questo [repository](https://github.com/ministero-salute/it-fse-gtw-tools), in particolare il tool "jwt-generator" per la generazione dei token.
Restiamo a disposizione in caso il problema dovesse persistere.
Grazie

**Comment by mlacamera** [comment]
Grazie risolto
