### ISSUE TITLE
Accreditamento Fornitore A1#111DEDALUSXXX - Regione_Sardegna - PSWEB_SISaR_RAS - 20.14

### ISSUE THREAD

**Issue by sandroaresu23** [ministero-salute/it-fse-support#538]
Buongiorno,

vi scriviamo in merito alla comunicazione da voi inviata a valle delle Pull Request https://github.com/ministero-salute/it-fse-accreditamento/pull/1024 e https://github.com/ministero-salute/it-fse-accreditamento/pull/1029.

In allegato la mail ricevuta.
[Re_ Accreditamento Fornitore A1#111DEDALUSXXX - Regione_Sardegna - PSWEB_SISaR_RAS - 20.14.zip](https://github.com/ministero-salute/it-fse-support/files/13588176/Re_.Accreditamento.Fornitore.A1.111DEDALUSXXX.-.Regione_Sardegna.-.PSWEB_SISaR_RAS.-.20.14.zip)

Facendo riferimento alle istruzioni su come valorizzare la checklist (https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case#come-valorizzare-la-checklist-tab-testcases) pensiamo di non aver commesso errori nella compilazione, pertanto vi chiediamo chiarimenti su come andrebbero compilati i campi indicati.

grazie

**Comment by vigliottim** [comment]
Buonasera, eventuali chiarimenti relativi a richieste provenienti dall'email progettofse2.0@teamsupportofse.it, possono essere avanzati rispondendo direttamente alla e-mail ricevuta, tenendo in copia
[fse_support@sogei.it](mailto:fse_support@sogei.it). Chiudiamo, pertanto, la presente issue e restiamo a disposizione per ulteriori richieste di supporto. Grazie.
