### ISSUE TITLE
Test4 LDO

### ISSUE THREAD

**Issue by danielepecoraro** [ministero-salute/it-fse-support#54]
Buongiorno, scrivo per conto dell'azienda I.T.Svil.

In merito ai  test4 della LDO, volevo chiedere: fino a che livello è richiesta la presenza di elementi opzionali?
Solo le sezioni, o anche i loro sotto elementi?

Riporto da un esempio trovato sul canale Slack che riporta la stessa problematica:

ClinicalDocument/component/structuredBody/component/section[@ID="Inquadramento_clinico_iniziale"] (riga 31 del file xlsx) è opzionale, ma per il test deve esserci.
La sua sottosezione ClinicalDocument/component/structuredBody/component/section[@ID="Inquadramento_clinico_iniziale"]/component/section[@ID="Anamnesi"] (riga 39) è opzionale, ma in questo specifico test la devo inserire per forza o la posso comunque omettere?

Grazie mille.

**Comment by danielepecoraro** [comment]
Ok la ringrazio.
Le volevo chiedere, il nostro applicativo però non gestisce tutti i campi opzionali, poichè non sono previsti.
In questa casistica, come dobbiamo gestire la situazione?

**Comment by g-polverini** [comment]
Salve, mi unisco alle domande qua, tanto la mia issue #55 è un doppione di questa, e aggiungo:

1. ok per sezioni e sottosezioni (purtroppo dobbiamo un po' adattare il codice per i test, neanche noi abbiamo sempre tutti i dati richiesti), ma fino a che punto di dettaglio dobbiamo arrivare? Penso a certe "minuzie" che riguardano le terapie farmacologiche, ad esempio, che in `ClinicalDocument/component/structuredBody/component /section[@ID="Terapia_farmacologica_effettuata_durante_ricovero"]/entry` arrivano a dei livelli di dettaglio molto fini. Le <entry> devono esserci per forza? (vedere anche domanda 3.)
2. anche per gli altri test le sottosezioni devono sempre essere presenti? Intendo quelle delle sezioni richieste. In caso affermativo, sempre con tutti i dettagli della domanda 1? (nel caso si debba arrivare per forza al massimo dettaglio)
3. a regime come funzionerà? HL7IT-IG_CDA2_LDO-v1.2-S.pdf, al punto 4 (pag. 59), dice
> ... si fornirà una linea guida che si focalizzi al massimo livello di dettaglio disponibile, cioè il terzo livello. Occorre comunque sottolineare che gli elementi del terzo livello (entry codificate) restano **OPZIONALI** e che il documento sarà comunque considerato well-formed anche se dettagliato al livello due (sezioni senza entry codificate)

spero che la cosa rimanga così, altrimenti saremmo costretti a veri e propri stravolgimenti del nostro software.

Mi scuso per la lungaggine, ma preferisco dare subito una visione d'insieme dei miei dubbi, anziché rischiare di fare lunghissimi botta e risposta che fanno perder tempo a tutti.

**Comment by IStacchiotti** [comment]
Buongiorno.
Il punto ultimo di dettaglio è esplicitato nei vari excel forniti ovvero tutte le sezioni e tutti gli elementi presenti in ciascuna sezione devono essere inseriti, poiché completano il caso di test in esame. Anche elementi opzionali da specifiche per i test case vengono resi obbligatori per lo specifico caso di test pensato. Quindi il dettaglio che si vuole è esplicitato dagli excel e tutto ciò che viene menzionato nell'excel deve essere inserito nel cda che viene usato nella fase di accreditamento.
Ciascun caso di test richiede detemrinate sezioni ovvero:
- il caso di test 1 solo le sezioni obbligatorie da specifiche e tutti gli elementi presenti nell'excel devono essere inseriti, anche elementi opzionali da specifiche ma necessari per il caso 1;
- il caso di test 2 e 3 vanno inserite le sezioni riportate nell'excel, obbligatorie e alcune opzionali, quelle necessarie per completare i casi in esame:
- il caso 4 tutte le sezioni sia opzionali che obbligatorie e tutti gli elementi in esse.

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
