### ISSUE TITLE
Test validazione errore generico

### ISSUE THREAD

**Issue by mlacamera** [ministero-salute/it-fse-support#542]
Buongiorno,
stiamo provando ad inviare (in test) un test case (il primo della LDO) ma l'API di validazione ritorna un errore generico che non riusciamo ad interpretare:

'{"traceID":"7e59e051b59714cc","spanID":"7e59e051b59714cc","type":"/msg/generic-error","title":"Errore generico.","detail":"Index: 0, Size: 0","status":500,"instance":""}'

Potreste darci indicazioni in merito
Grazie

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
dalle analisi effettuate è emerso quanto segue:
- sembrerebbe mancare il parametro "Accept": "application/json" dell'header indicato come "Required" in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#31-request) all'interno della "Tabella 6: Parametri Richiesta di Validazione".
- il valore del parametro "filename" andrebbe inserito tra virgolette (filename="esempio.pdf").
- all'interno della sezione contenente il pdf sembrerebbe mancare il parametro "Content-Type: application/pdf"

La invitiamo gentilmente ad apportare le dovute correzioni e riprovare.
Restiamo a disposizione in caso il problema persista.
Grazie

**Comment by mlacamera** [comment]
Abbiamo provato più volte seguendo le indicazioni fornite ma nulla, di seguito la richiesta

--43159aad-b4d0-46c0-90b8-49565ca0cd4d
Content-Type: application/json
Content-Length: 70
Content-Disposition: form-data; name="requestBody"

{"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VALIDATION"}
--43159aad-b4d0-46c0-90b8-49565ca0cd4d
Content-Type: application/pdf
Content-Disposition: form-data; name="file"; filename="LDO - Caso di Test 1_injected-signed.pdf"

%PDF-1.4
%����
2 0 obj
<</Length 10/Filter/FlateDecode>>stream
x�+�

e questa la risposta

{
    "traceID": "72e91757198aaeb2",
    "spanID": "72e91757198aaeb2",
    "type": "/msg/generic-error",
    "title": "Errore generico.",
    "detail": "Index: 0, Size: 0",
    "status": 500,
    "instance": ""
}

**Comment by LucaRogledi** [comment]
Buongiorno,
La invitiamo gentilmente ad effettuare un'altra prova seguendo le modifiche suggerite in seguito:

- rimozione del parametro Content-Length: 70

      AS-IS:
      Content-Type: application/json
      Content-Length: 70
      Content-Disposition: form-data; name="requestBody"
      {"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VALIDATION"}
      
      TO-BE:
      Content-Type: application/json
      Content-Disposition: form-data; name="requestBody"
      {"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VALIDATION"}

- aggiunta dell'encoding utilizzato

      AS-IS:
      Content-Type: application/pdf
      Content-Disposition: form-data; name="file"; filename="LDO - Caso di Test 1_injected-signed.pdf"
      
      TO-BE:
      Content-Type: application/pdf; charset=utf-8
      Content-Disposition: form-data; name="file"; filename="LDO - Caso di Test 1_injected-signed.pdf"

La ringraziamo per la collaborazione e restiamo a disposizione il problema dovesse persistere.
Grazie

**Comment by mlacamera** [comment]
Ho apportato le modifiche riportate

--8ddb15e7-6a84-49cf-b7c1-5d7fdf67a216
Content-Type: application/json
Content-Disposition: form-data; name="requestBody"

{"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VALIDATION"}
--8ddb15e7-6a84-49cf-b7c1-5d7fdf67a216
Content-Type: application/pdf; charset=utf-8
Content-Disposition: form-data; name="file"; filename="LDO - Caso di Test 1_injected-signed.pdf"

ma continua a dare errore generico

'{"traceID":"dc3be793ff43d59f","spanID":"dc3be793ff43d59f","type":"/msg/generic-error","title":"Errore generico.","detail":"Index: 0, Size: 0","status":500,"instance":""}'

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate risulta che il CDA allegato al pdf, alla prima riga, ha l'elemento "encoding" valorizzato con "utf-16":
<img width="229" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/f6cac3a1-1295-449e-851c-e15807a0f0ae">
La invitiamo a correggere l'encoding con "utf-8" e riprovare. Grazie.

**Comment by mlacamera** [comment]
Risolto 
Grazie
