### ISSUE TITLE
Errore Tipologia documento su referto Trasfusionale

### ISSUE THREAD

**Issue by sandroaresu23** [ministero-salute/it-fse-support#546]
Buongiorno, riceviamo il seguente errore nell'invio del CT id=191  del Trasfusionale:

{
    "traceID": "264c46d31f62c812",
    "spanID": "264c46d31f62c812",
    "type": "/msg/jwt-validation",
    "title": "Campo token JWT non valido.",
    "detail": "JWT payload: Tipologia documento diversa dalla tipologia di CDA (code - codesystem)",
    "status": 403,
    "instance": "/jwt-document-type",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.c1779303a5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

code e codeSystem nel CDA inviato sono così valorizzati come da esempio gitHub:
code="11502-2"	codeSystem="2.16.840.1.113883.6.1"  codeSystemName="LOINC" displayName="Referto di Laboratorio"

Lo stesso referto inviato al gtw-certifier ottiene esito positivo.
Chiediamo quindi supporto per capire quale sia la problematica e la corretta valorizzazione.

**Comment by vigliottim** [comment]
Buongiorno,
il campo _resource_hl7_type_ del JWT è ottenuto dal concatenamento dei campi _code_ e _codesystem_ secondo il seguente formato:
`"resource_hl7_type": "('CODE^^CODESYSTEM')"`
Dovrebbe controllare che il valore del campo _CODE_ inserito in _resource_hl7_type_ del JWT sia coerente con quello inserito nel tag _code_ contenuto all'interno del CDA (relativo alla tipologia di documento in esame): `code="11502-2"`
Restiamo a disposizione nel caso in cui il problema persista. Grazie.

**Comment by sandroaresu23** [comment]
Il tag è valorizzato come da voi indicato:
  "resource_hl7_type": "('11502-2^^2.16.840.1.113883.6.1')"
quindi come possiamo procedere?

**Comment by vigliottim** [comment]
Le chiediamo gentilmente di allegare il CDA utilizzato, grazie.

**Comment by sandroaresu23** [comment]
Abbiamo notato che sono state fatte delle modifiche, abbiamo provato a risottomettere gli stessi 2 CDA che stamattina andavano in errore e ora vengono processati con esito positivo.
Grazie del supporto

**Comment by vigliottim** [comment]
Grazie per la segnalazione, rimaniamo a disposizione per ulteriori richieste di supporto.
