### ISSUE TITLE
CDA RAP - Validazione fallita incongruente a specifiche (encompassingEncounter/responsibleParty)

### ISSUE THREAD

**Issue by joGrim65** [ministero-salute/it-fse-support#547]
Buongiorno,
sto effettuando dei test di validazione per CDA RAP (Anatomia Patologica) utilizzando gli ultimi schematron.
Tra gli errori ottengo questo:

_ERRORE-27| L'elemento ClinicalDocument/componentOf/encompassingEncounter/responsibleParty/assignedEntity deve contenere almeno un elemento id valorizzato tramite il CF -  è obbligatorio @root='2.16.840.1.113883.2.9.4.3.2'.]_

Basandomi sulle specifiche HL7 RAP di settembre 2023 (l'ultimo draft), l'attributo "responsibleParty" risulta essere in cardinalità 0..1 e nel mio CDA non è valorizzato.
Quindi l'errore prodotto dalla validazione è palesemente incongruente, in quanto la non obbligatorietà di un elemento non può comportare errori su elementi/attributi da esso derivati.

Pertanto, o vi sono altre specifiche/reference di riferimento (nel qual caso chiedo la cortesia di indicarmele), oppure deve essere corretto lo schematron per evitare questa segnalazione.

**Comment by LucaRogledi** [comment]
Buongiorno, grazie della segnalazione. Si conferma che, in conformità alle specifiche Nazionali HL7, l'elemento responsibleParty è un tag opzionale. Pertanto, verrà eseguità una modifica del controllo schematron al fine di consentire la corretta validazione del CDA2. Vi daremo evidenza non appena la modifica sarà rilasciata. 
Grazie

**Comment by vigliottim** [comment]
Buonasera, le confermiamo che è stata rilasciata una fix correttiva. 
La invitiamo cortesemente a riprovare, il problema non dovrebbe più presentarsi. 
Rimaniamo a completa disposizione in caso contrario. 
Grazie.

**Comment by joGrim65** [comment]
Confermo che il nuovo schematron risolve il bug.
Grazie

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
La ringraziamo per il feedback e procediamo con la chiusura della issue.
Restiamo a disposizione in caso fosse necessario ulteriore supporto.
Grazie.
