### ISSUE TITLE
Chiarimenti checklist Trasfusionale

### ISSUE THREAD

**Issue by sandroaresu23** [ministero-salute/it-fse-support#548]
Buongiorno, vorremmo avere chiarimenti in merito alla checklist di accreditamento per il referto trasfusionale, in particolare vengono indicate come obbligatorie le seguenti sezioni: **ClinicalDocument/component/structuredBody/component/section/component/section/entry/act/entryRelationship/organizer/component/observation/code/@code** valorizzate con i codici:

- 14579-7
- 92551-1
- 50670-9
- 1007-4
- 1008-2
- 40628-0 oppure 40582-9 oppure 40581-1

Essendo obbligatorie ne deduciamo che vadano inserite tutte nel CT1_OK ma presso i nostri centri non tutti questi esami vengono effettuati e quindi non sono censiti, oppure sono codificati con tipologia di esito differente da quella che voi richiedete.
Come dobbiamo comportarci per superare il caso di test? possiamo inserire i soli esami da noi effettuati ed escludere le altre sezioni?

Inoltre vorremmo avere conferma anche del fatto che il caso di test OK-HLA possa essere omesso in quanto non applicabile presso i nostri centri.

In attesa di un vostro riscontro vi ringraziamo.

**Comment by vigliottim** [comment]
Buongiorno,
In merito al TC OK del trasfusionale, l'obbligatorietà si riferisce alla presenza di almeno uno dei component/observation/code elencati, aderenti al tipo di informazione che si vuole riportare nel documento CDA2.
Infine confermiamo che il TC OK-HLA può essere omesso se non applicabile presso il centro di interesse.
Restiamo a disposizione in caso di ulteriore supporto.
Grazie

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario. Grazie.
