### ISSUE TITLE
Presenza di sezioni opzionali per Test 4 LDO

### ISSUE THREAD

**Issue by g-polverini** [ministero-salute/it-fse-support#55]
In `casi di test LDO.docx` è scritto
> Nel caso di test 4 è esplicitato un esempio completo che prevede sia le section obbligatorie che le section opzionali. 

Fino a che livello è richiesta la presenza di elementi opzionali, in questo caso?
Solo le sezioni, o anche i loro sottoelementi?
Prendo ad esempio due righe di `CDA2_Lettera di Dimissione Ospedaliera_OK.xlsx` (tab `LDO - Caso di Test 4`)
- `ClinicalDocument/component/structuredBody/component/section[@ID="Inquadramento_clinico_iniziale"]` (riga 31)
- `ClinicalDocument/component/structuredBody/component/section[@ID="Inquadramento_clinico_iniziale"]/component/section[@ID="Anamnesi"]` (riga 39)

La  prima è una sezione di primo livello, ed è ovvio che debba essere presente, mentre la seconda è una sua sottosezione. Deve comparire anche quest'ultima nel .xml, per passare il test?

**Comment by g-polverini** [comment]
Aggiungo: per come è scritto il docx, nei casi di test 2 e 3 sono esplicitate le sezioni obbligatorie e quelle opzionali per i singoli casi d'uso, il che mi farebbe pensare che sia sufficiente il primo livello, ma vorrei essere sicuro

**Comment by IStacchiotti** [comment]
Buongiorno, il caso di test 4 della LDO, è un caso completo.
Sarebbe necessario includere sezioni e sottosezioni opzionali e obbligatorie, come riportato anche nel dataset associato: dovrebbero quindi comparire, per poter passare il test, anche le sottosezioni opzionali.

**Comment by Ser-ena** [comment]
Si chiude la segnalazione poichè duplicata della #54.
