### ISSUE TITLE
valori di <HOST> e <PORT> nella chiamata https al Gateway per la validazione del CDA2

### ISSUE THREAD

**Issue by Itamedical** [ministero-salute/it-fse-support#550]
Buongiorno,
nella sezione relativa alla request del servizio di validazione del CDA2 viene indicato l'Endpoint generico:

https://<HOST>:<PORT>/v1/documents/validation

Quali sono i valori di <HOST> e <PORT> da inserire per comunicare con il Gateway ?

Cordiali saluti

**Comment by vigliottim** [comment]
Buongiorno, può raggiungere il servizio di validazione tramite l'endpoint: 
`https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation`
Ulteriori informazioni sono disponibili in documentazione al link: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#2-contesto-di-riferimento
Restiamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
