### ISSUE TITLE
Richiesta Chiarimenti per Accreditamento AMBWEB_SISaR_RAS

### ISSUE THREAD

**Issue by sandroaresu23** [ministero-salute/it-fse-support#551]
Buongiorno, chiedo una verifica in merito al mancato accreditamento del modulo AMBWEB_SISaR_RAS richiesto tramite pull request https://github.com/ministero-salute/it-fse-accreditamento/pull/1055. 

Gli errori da voi segnalati indicano la mancanza dei file 6, 7, 8, 9, 29, 37, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 369:

[ {
  "error" : "TEST_NON_PRESENTE",
  "description" : "Test mancanti rispetto alla checklist:[6, 7, 8, 9, 29, 37, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 369]"
} ]

Questi casi di test sono relativi alla tipologia documento LDO, e non a quella RSA per cui l'accreditamento era stato richiesto. Infatti, per il modulo AMBWEB_SISaR_RAS nel relativo file json gli id dei casi di test sono: 147, 148, 149, 150, 32, 40, 165, 166, 167, 168, 169, 374; confermiamo anche la presenza dei files all'interno del path atteso.

Vi chiediamo una verifica in merito

**Comment by vigliottim** [comment]
Buongiorno, la colonna _"Applicabilità"_ della checklist relativa all'applicativo _AMBWEB_SISaR_RAS_ risulta compilata con _"SI"_ per i casi di test per i quali riceve errore (relativi alla tipologia documentale LDO): 

![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/77d2f5a9-3bb4-4470-9f40-82f53de8f1d0)

Dovrebbe lasciare vuota la colonna di applicabilità in corrispondenza dei CDA non gestiti dall'applicativo. Restiamo a disposizione nel caso in cui non risolvesse il problema dopo aver effettuato la correzione suggerita. Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
