### ISSUE TITLE
CDA RAP - Validazione sezione "procedure" - incongruenze "code", "methodCode"

### ISSUE THREAD

**Issue by joGrim65** [ministero-salute/it-fse-support#554]
Buongiorno,
sto effettuando dei test di validazione per CDA RAP (Anatomia Patologica) utilizzando gli ultimi schematron.

Il CDA in validazione contiene una sezione "procedure" in il valore dell'elemento "code" è un "nullFlavor":

&lt;code nullFlavor="OTH" /&gt;

Questo è compatibile con quanto riportato nelle specifiche HL7 (ballot 09-2023):
![image](https://github.com/ministero-salute/it-fse-support/assets/16781489/336fd008-cf9c-4533-9408-5cec11c0a078)

In presenza di "nullFlavor", l'elemento "methodCode" può essere assente, come asserito dalle specifiche:
![image](https://github.com/ministero-salute/it-fse-support/assets/16781489/04351813-3747-4c2f-aa68-fd6d0969c891)

Tuttavia, validando il CDA con l'item "code" sopra indicato, ottengo il seguente errore di validazione:

_Pattern 'all' Failed : ERRORE-b160| Sezione Procedura: l'elemento entry/procedure/code deve contenere l'elemento code valorizzato tramite @codeSystem='2.16.840.1.113883.6.1'..

Pattern 'all' Failed : ERRORE-b162| Sezione Procedura: l'elemento entry/procedure/methodCode deve contenere l'elemento code valorizzato tramite @codeSystem='2.16.840.1.113883.6.96'.._

Il primo errore  non dovrebbe essere presente, poichè vi è "nullFlavor".
Il secondo non dovrebbe essere presente poichè "nullFlavor" rende "methodCode" non obbligatorio.

Se le mie considerazioni non sono errate, le specifiche regole dello schematron dovrebbero essere aggiornate.

Grazie

**Comment by LucaRogledi** [comment]
Buon pomeriggio, per procedere con le analisi Le chiederemmo gentilmente di allegare il pdf (con il CDA iniettato) utilizzato per la richiesta di validazione. Grazie

**Comment by joGrim65** [comment]
In allegato il pdf con cda iniettato.
[doc-issue-554.pdf](https://github.com/ministero-salute/it-fse-support/files/13729926/doc-issue-554.pdf)

**Comment by vigliottim** [comment]
Buongiorno, grazie per la segnalazione. Effettueremo una modifica allo schematron coerenti con le Linee Guida HL7 per permettere la corretta validazione del documento CDA2 di RAP.

**Comment by vigliottim** [comment]
Buonasera, le confermiamo che è stata rilasciata una fix correttiva. 
La invitiamo cortesemente a riprovare, il problema non dovrebbe più presentarsi. 
Rimaniamo a completa disposizione in caso contrario. 
Grazie.

**Comment by joGrim65** [comment]
Confermo che il nuovo schematron risolve il bug.
Grazie

**Comment by vigliottim** [comment]
Grazie per il feedback. Procediamo alla chiusura della presente issue e rimaniamo a disposizione per ulteriori richieste di supporto.
