### ISSUE TITLE
errore nell'utilizzo del tool FSECertifier?

### ISSUE THREAD

**Issue by Itamedical** [ministero-salute/it-fse-support#555]
Buongiorno,
dal documento HL7IT-IG_CDA2_RSA-v1.1-S par. 5.5.4.1 l'elemento <act> è obbligatorio. 

Nel documento allegato tale elemento è stato commentato in modo da eliminarlo, ma utilizzando il tool di debug "FSECertifier" l'anomalia non viene riscontrata mentre invece (se ho interpretato correttamente lo schematron relativo al documento RSA)  mi sarei aspettato di ricevere l'errore "<assert test="count(hl7:act)=1"

>ERRORE-b78| Sezione Prestazioni: l'elemento entry DEVE contenere un elemento act</assert> "

 

Cosa stiamo sbagliando?

Cordiali Saluti
Itamedical S.r.l.

**Comment by Itamedical** [comment]
allego il documento utilizzato, per il quale era atteso l'errore.
[376421562.zip](https://github.com/ministero-salute/it-fse-support/files/13739699/376421562.zip)
cordiali saluti

**Comment by IStacchiotti** [comment]
Buongiorno @Itamedical, potrebbe specificare a quale servizio sta facendo riferimento con il termine "FSECertifier"? In particolare, intende il servizio online di validazione del Gateway (endpoint: https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation), oppure il tool di accreditamento offline [gtw-certifier](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/gtw-certifier)? Grazie

**Comment by Itamedical** [comment]
Mi riferisco al tool offline gtw-certifier

**Comment by IStacchiotti** [comment]
"`ERRORE-b78| Sezione Prestazioni: l'elemento entry DEVE contenere un elemento act`" è previsto nello schematron di RSA. Le segnaliamo che gli schematron pubblicati al [link](https://github.com/ministero-salute/it-fse-catalogs/tree/main/schematron) sono utilizzati per le verifiche sul contenuto dei cda da parte del Gateway online (endpoint: https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation).
La invitiamo pertanto a richiamare il servizio in questione per verificare se l'errore atteso (ERRORE-b78) si origina con il cda allegato.
Specifichiamo infine che il gtw-certifier invece è un tool messo a disposizione per la simulazione dei test automatici che verranno effettuati durante la procedura di accreditamento, e che implementa dei controlli diversi da quelli previsti ai fini della validazione da parte del Gateway online. Rimaniamo a disposizione per ulteriori chiarimenti, grazie
