### ISSUE TITLE
WRONG_CLAIMS_ON_LOG

### ISSUE THREAD

**Issue by embrunoR** [ministero-salute/it-fse-support#556]
Buongiorno, 
in merito alla PR #1063 ho ricevuto una mail con il seguente json: 
[ {
  "id" : 374,
  "error" : "WRONG_CLAIMS_ON_LOG",
  "description" : "Claims(appId,appVersion,appVendor) della chiamata al gtw differenti da quelli dichiarati nel data.json"
}, {
  "id" : 374,
  "error" : "WRONG_CLAIMS_ON_LOG",
  "description" : "Claims(appId,appVersion,appVendor) della chiamata al gtw differenti da quelli dichiarati nel data.json"
}, {
  "id" : 374,
  "error" : "WRONG_CLAIMS_ON_LOG",
  "description" : "Claims(appId,appVersion,appVendor) della chiamata al gtw differenti da quelli dichiarati nel data.json"
} ]

Il token utilizzato è il seguente: 
{
  "sub": "PRVCNT19A01F205A^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "subject_role": "AAS",
  "purpose_of_use": "TREATMENT",
  "iss": "integrity:S1#111REPLY000000",
  "locality": "03091300",
  "subject_application_version": "${project.version}",
  "subject_organization": "Regione Lombardia",
  "subject_organization_id": "030",
  "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
  "patient_consent": true,
  "action_id": "CREATE",
  "resource_hl7_type": "('11488-4^^2.16.840.1.113883.6.1')",
  "attachment_hash": "1c97945cd7e626d1ccb779d283767ebbec78d22c483fb217d529c5bc13dc7803",
  "subject_application_id": "NPRI-GESTAMB",
  "exp": 1702600853,
  "subject_application_vendor": "ARIA",
  "iat": 1702572053,
  "jti": "958",
  "person_id": "PRVCNT19A01F205A^^^&2.16.840.1.113883.2.9.4.3.2&ISO"
}
nel data.json ho questi dati 
"appVendor": "ARIA_SPA",
"appID": "GESTAMB",
"appVersion": "1.11.2",

sono queste 3 informazioni differenti  a causare l'errore ? 
Inoltre questo problema si presenta solo per il test case indicato ? 
Grazie

**Comment by embrunoR** [comment]
{
  "sub": "PRVCNT19A01F205A^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "subject_role": "AAS",
  "purpose_of_use": "TREATMENT",
  "iss": "integrity:S1#111REPLY000000",
  "locality": "03091300",
  "subject_application_version": "1.11.2",
  "subject_organization": "Regione Lombardia",
  "subject_organization_id": "030",
  "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
  "patient_consent": true,
  "action_id": "CREATE",
  "resource_hl7_type": "('11488-4^^2.16.840.1.113883.6.1')",
  "attachment_hash": "1c97945cd7e626d1ccb779d283767ebbec78d22c483fb217d529c5bc13dc7803",
  "subject_application_id": "GESTAMB",
  "exp": 1703191578,
  "subject_application_vendor": "ARIA_SPA",
  "iat": 1703162778,
  "jti": "9646",
  "person_id": "PRVCNT19A01F205A^^^&2.16.840.1.113883.2.9.4.3.2&ISO"
}
In questo modo risulterebbe corretto ?

**Comment by vigliottim** [comment]
Buongiorno, l'errore ricevuto relativo al Test Case con id = 374 è causato dal fatto che i valori inseriti per i parametri appId, appVersion, appVendor del data.json della PR #1063 non sono coerenti con quelli inseriti per nella generazione dei token:

- _data.json_: "appVendor": "ARIA_SPA" -> _token_: "subject_application_vendor": "ARIA"
- _data.json_: "appID": "GESTAMB" -> _token_: "subject_application_id": "NPRI-GESTAMB"
- _data.json_: "appVersion": "1.11.2" -> _token_: "subject_application_version": "${project.version}"

La invitiamo ad uniformare i valori corrispondenti, facendole presente che i controlli sono case sensitive, e riprovare. Grazie.

**Comment by embrunoR** [comment]
Grazie per la risposta, 
per quanto riguarda il data.json, posso modificare quello già presente modificando l'ultimo test-case con i relativi workflowId, traceId, e il file, cambiando anche il contenuto di quest'ultimo nella cartella dei FILES ? 

Grazie

**Comment by vigliottim** [comment]
Può effettuare una nuova PR con le correzioni indicate (dovrebbe essere sufficiente rendere coerente nel nuovo _data.json_ la tripletta dei campi identificativi del software con quella riportata nei token). Restiamo a disposizione nel caso avesse bisogno di ulteriori chiarimenti.

**Comment by embrunoR** [comment]
Ho effettuato una chiamata modificando il contenuto del token allineandolo ai dati già presenti nel data.json.
Segue PR di aggiornamento. 
Grazie
