### ISSUE TITLE
Errore InteroperabilityInvalidRequest in seguito alla chiamata https al Gateway

### ISSUE THREAD

**Issue by Itamedical** [ministero-salute/it-fse-support#557]
Buonasera,

abbiamo elaborato la chiamata https all'URL di test: https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation e inviato un file .pdf di un RSA con cda iniettato (allego il pdf e il cda).

Dal file .log che ci viene ritornato (vedi allegato) sembrerebbero non esserci problemi con la comunicazione con il Gateway e l'invio del file, alla fine del .log però compare l'errore:

{"type":"https://govway.org/handling-errors/400/Interoperability
0040: InvalidRequest.html","title":"InteroperabilityInvalidRequest","s
0080: tatus":400,"detail":"Received request is not conform to the requ
00c0: ired interoperability profile","govway_id":"6987d1dd-a015-11ee-8
0100: 2d6-005056ae7395"}

Tale errore può essere dovuto ad una strutturazione sbagliata del cda? Oppure abbiamo formulato male la chiamata https ?

Inoltriamo il file .log ritornatoci in cui viene precisato l' errore di InteroperabilityInvalidRequest

Cordiali saluti,

[runGTWHttpsCall.log](https://github.com/ministero-salute/it-fse-support/files/13744112/runGTWHttpsCall.log)

[628363765.zip](https://github.com/ministero-salute/it-fse-support/files/13744124/628363765.zip)

[628363765.pdf](https://github.com/ministero-salute/it-fse-support/files/13744146/628363765.pdf)

**Comment by vigliottim** [comment]
Buongiorno, 
dalle analisi effettuate è emerso che i token utilizzati contengono diversi campi errati:
 
**Authentication Bearer Token/FSE-JWT Signature**
- _"sub": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO"_: deve essere valorizzato con il codice fiscale dell’utente che fa richiesta del servizio di interoperabilità con formato codifica conforme alle specifiche IHE (es. `CODICEFISCALE^^^&2.16.840.1.113883.2.9.4.3.2&ISO`)
- _"aud": "FSE_Gateway"_: deve essere valorizzato con la url del servizio: https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1
 
**Authentication Bearer Token**
- _"iss": "auth:jwt-issuer"_: deve essere valorizzato con "auth:" seguito dal "Common Name del certificato di firma"

**FSE-JWT-Signature**
- _"iss": "integrity:jwt-issuer"_: deve essere valorizzato con "integrity:" seguito dal "Common Name del certificato di firma"
- _"locality": "jwt-location"_: deve essere valorizzato l'identificativo della struttura utente
- _"person_id": "DD68^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO"_: rappresente il codice identificativo dell’assistito a cui si riferisce la richiesta o del genitore/tutore che ha richiesto l’operazione o il codice identificativo dell’assistito, del genitore o del tutore, codificato secondo il tipo di dato CX HL7 V2.5 (es. `CODICEFISCALE^^^&2.16.840.1.113883.2.9.4.3.2&ISO`)

Per ulteriori informazioni può consultare la documentazione al link: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt
La invitiamo a riprovare correggendo i campi errati. 
Rimaniamo a disposizione nel caso avesse bisogno di chiarimenti.

**Comment by Itamedical** [comment]
GRazie per il suo prezioso supporto. Buone feste
