### ISSUE TITLE
Info Richiesta accreditamento S1#111RBSOFTWARECENTERSRLXX LAB

### ISSUE THREAD

**Issue by rbsoftwaresrl** [ministero-salute/it-fse-support#558]
Buongiorno,
ho eseguito la Pull Request per come indicato nella documentazione.
Volevo sapere se era possibile verificare il corretto caricamento ed avere info circa i tempi di risposta alla verifica?

Di seguito il percorso di caricamento.

GATEWAY/S1#111RBSOFTWARECENTERSRLXX/RBSoftware/WGesLaAn/1

Grazie anticipatamente

Cordiali saluti

**Comment by IStacchiotti** [comment]
Buongiorno, la sua pull request [#1076](https://github.com/ministero-salute/it-fse-accreditamento/pull/1076)
risulta in stato "Closed", pertanto non è possibile procedere con le analisi. La invitiamo ad aprirne una nuova, o in alternativa a riaprire la medesima pr (se possibile), e a lasciarla aperta: verrà eseguito il merge della pull a valle di alcune verifiche preliminari e eventuali aggiornamenti saranno recapitati via email. Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario. Grazie.
