### ISSUE TITLE
Mancata registrazione workflowInstanceId

### ISSUE THREAD

**Issue by federicoveccegruppoinformatico** [ministero-salute/it-fse-support#559]
Salve abbiamo eseguito i vari test case, per i test case KO abbiamo ricevuto il seguente errore:

{
  "id" : 152,
  "error" : "TEST_KO_NON_SUPERATO",
  "description" : "Test KO non superato. Assicurarsi che il traceId fornito abbia restituito in fase di validazione un errore bloccante."
}

Andando a verificare nel nostro file JSON

Abbiamo:
    {
      "id": 152,
      "ts": "2023-12-29T17:01:34Z",
      "traceId": "881e2bb0a2b3a654",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.2149fb78666c205ac20b9bd2d882af037f0819429c691196eaa8054488c56c20.1c7f72ec02^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "files": [
        "VALIDAZIONE_CDA2_RSA_CT6_KO.PDF"
      ]
    }
    
    e dove non si presenta l'errore
    {
      "id": 374,
      "ts": "2024-01-04T11:48:40Z",
      "traceId": "937b3ff0847034f4",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.2149fb78666c205ac20b9bd2d882af037f0819429c691196eaa8054488c56c20.495a729b92^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "files": [
        "VALIDAZIONE_CDA2_RSA_CT0.PDF"
      ]
    }
    
    Utilizzando il servizio di verifica otteniamo che per il primo effettivamente non c'è registrazione
    
2.16.840.1.113883.2.9.2.120.4.4.2149fb78666c205ac20b9bd2d882af037f0819429c691196eaa8054488c56c20.1c7f72ec02^^^^urn:ihe:iti:xdw:2013:workflowInstanceId  

HTTP Status Code: 404
{
  "traceID": "c7b4f0a1ec11aa26",
  "spanID": "c7b4f0a1ec11aa26",
  "type": "/msg/record-not-found",
  "title": "Record non trovato.",
  "detail": "No Record Found",
  "status": 404,
  "instance": "/record-not-found"
}

Mentre per il secondo si

HTTP Status Code: 200
{
  "traceID": "03e0f9b052e40772",
  "spanID": "6b9e92ebdb129066",
  "transactionData": [
    {
      "eventType": "VALIDATION",
      "eventDate": "2024-01-04T10:48:40.209+00:00",
      "eventStatus": "SUCCESS",
      "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "organizzazione": "090",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.2149fb78666c205ac20b9bd2d882af037f0819429c691196eaa8054488c56c20.495a729b92^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "937b3ff0847034f4",
      "issuer": "integrity:S1#111GRUPPOINFORMATICOXX",
      "expiringDate": "2024-01-09T10:48:40.220+00:00"
    }
  ]
}

Non riesco a capire il motivo della mancata registrazione potete darmi dei suggerimenti?

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Il messaggio di errore ricevuto:
```
"error" : "TEST_KO_NON_SUPERATO",
"description" : "Test KO non superato. Assicurarsi che il traceId fornito abbia restituito in fase di validazione un errore bloccante."
```
È causato dall'inserimento di un traceId non corretto o scaduto avendo superato la data contenuta nel parametro "expiringDate" presente nella risposta del servizio di [status](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#10-servizio-di-recupero-stato-transazione-per-workflowinstanceid).
Può procedere con una nuova PR con le dovute correzioni e restiamo a disposizione in caso fosse necessario ulteriore supporto.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. 
Si può procedere con la riapertura nel caso sia necessario ulteriore supporto. Grazie.
