### ISSUE TITLE
Errore quando si elimina un documento pubblicato in precedenza

### ISSUE THREAD

**Issue by dinelliascom** [ministero-salute/it-fse-support#56]
Dopo aver provato ad eliminare un documento precedentemente pubblicato ritorna il seguente errore:
`{"traceID":"11781544101b826a","spanID":"11781544101b826a","type":"/msg/eds-error","title":"Eds error.","detail":"Document cannot be found on the Server FHIR","status":404,"instance":"/msg/eds-document-missing"}`

**Comment by IStacchiotti** [comment]
Buon pomeriggio, le chiediamo cortesemente di riprovare. Se l'errore si ripresenta, dovrebbe per favore inviarci: 
- il file (pdf) e il requestBody (json) forniti in pubblicazione,
- identifier passato all'endpoint di eliminazione.
Grazie

**Comment by dinelliascom** [comment]
Buongiorno 
purtroppo adesso non funziona neppure la validazione, l'errore è il seguente:
`Error calling Validate: {"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"531b6226-a929-11ed-b068-005056ae54fa"}`

**Comment by zukka77** [comment]
@dinelliascom in questo momento ci sono problemi al servizio, verrà data comunicazione lì quando il sistema tornerà operativo https://developersitalia.slack.com/archives/C03RDT88FSM/p1676021060488839
per iscriversi al canale slack puoi usare questo link  https://slack.developers.italia.it/

**Comment by dinelliascom** [comment]
Buonasera, purtroppo continua a dare lo stesso errore:
`{"traceID":"cc84be391ec497ec","spanID":"cc84be391ec497ec","type":"/msg/eds-error","title":"Eds error.","detail":"Document cannot be found on the Server FHIR","status":404,"instance":"/msg/eds-document-missing"}`

Questa la response durante la fase di pubblicazione:
TraceID: 02ae7017e49e0952
SpanID: 02ae7017e49e0952
WorkflowInstanceId: 2.16.840.1.113883.2.9.3.120915.4.4.32.11072433273.11.24aab23e81715b12cde8e57124f7bd6e9d3893e99899585f0a138148a086e1c7.dd4a165a8d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
Warning: 

Al seguente link il file json della requestBody e il pdf di test: https://github.com/dinelliascom/FilesTestFSE_LDO

**Comment by masciamariotti** [comment]
Buonasera,
per facilitare la verifica, potrebbe fornirci anche l' identifier passato all'endpoint di eliminazione?
Grazie

**Comment by dinelliascom** [comment]
Questo l'identifier passato: "2.16.840.1.113883.2.9.3.120915.4.4.32.11072433273.11^11072433273"

**Comment by osinfocer** [comment]
Ciao. 
Ho un problema simile e temo che nonostante l'esito della creazione sia positivo il problema sia dovuto al fatto che c'è un errore nelle fasi di pubblicazione.
Puoi controllare con la funzione di getstatus  se alla fine hai un json come il seguente?

```
    {
      "eventType": "EDS_WORKFLOW",
      "eventDate": "2023-02-16T15:10:10.500+00:00",
      "eventStatus": "BLOCKING_ERROR",
      "message": "Error: failed to publish bundle",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.50502.4.4.1.c8e50e1957586fd4b90477e0ad0d3cf4e6b834211297ae45a4441978ce2dbe07.15bb89adc4^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2024-02-16T15:10:10.510+00:00"
    }
```
In tal caso secondo me il documento non è stato "veramente" creato, cioè non è arrivato alla fine del processo e per questo motivo non si può cancellare in quanto non esiste.
Temo (idea del tutto personale) che il problema sia il contenuto del CDA2 che pur essendo formalmente valido poi in qualche modo non viene letto correttamente).

**Comment by Ser-ena** [comment]
Salve @dinelliascom ,comunichiamo che  l'errore non è sulla delete, ma sulla create che non finalizza. Può verificare l'errore bloccante tramite la chiamata /status/{workflowInstanceId}. Stiamo analizzando la problematica sulla finalizzazione della pubblicazione, le faremo sapere non appena abbiamo degli aggiornamenti.

**Comment by osinfocer** [comment]
Salve cortesemente, la finalizzazione della pubblicazione è una fase che implica la lettura del CDA2 e se qualcosa non va viene bloccata o non è coinvolto il parsing del CDA2 in tale fase?  Scusate l'insistenza ma senza la risoluzione di questo problema non riusciamo a provare né la sostituzione né la eliminazione.

**Comment by IStacchiotti** [comment]
Buon pomeriggio @dinelliascom, potrebbe provare cortesemente ad aggiungere l'ID mancante all'elemento represented Organization di Legal Authenticator.

**Comment by dinelliascom** [comment]
Buongiorno,
ho aggiunto l'elemento 'representedOrganization' in questo modo all'interno di Legal Authenticator
```
<legalAuthenticator typeCode="LA" contextControlCode="OP">
         <assignedEntity classCode="ASSIGNED">
                        ...
                        <representedOrganization>
				<id root="2.16.840.1.113883.2.9.3.120915.4.4.32.11072433273.11" extension="11072433273" />
			</representedOrganization>
         </assignedEntity>
</legalAuthenticator>
```

ed effettivamente la prima volta ha funzionato.
Riprovando sembra che funzioni alternativamente in base alla verifica dello stato workflow ID

se presente EventType: EDS_WORKFLOW,EventStatus: BLOCKING_ERROR allora l'eliminazione funziona
se questo non è presente mostra l'errore "Document cannot be found on the Server FHIR", status 404

Sto forse sbagliando qualcosa per come ho aggiunto l'elemento "representedOrganization"? Nella documentazione HL7 è solo scritto che è opzionale e che va inserito il tag id al suo interno ma non ho trovato nessun esempio esplicito per come deve essere fatto l'id.

**Comment by IStacchiotti** [comment]
Buon pomeriggio, dopo le modifiche che Lei stesso ha apportato come ci ha indicato nella risposta precedente, riusciamo con successo a caricare ed eliminare il CDA fornito. Abbiamo testato più volte l'inserimento e la rimozione del documento con esito positivo. Non riscontriamo il comportamento che descrive in relazione all'EventType, la invitiamo dunque a riprovare. Grazie

**Comment by dinelliascom** [comment]
Si confermo, adesso funziona in tutti i casi.
Grazie del supporto!

**Comment by IStacchiotti** [comment]
Grazie per il gentile riscontro. La presente viene chiusa come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto.
