### ISSUE TITLE
Mancato accreditamento A1#111GRUPPOGPI00 - TESI_SPA - ENDOXWEB - 25.0

### ISSUE THREAD

**Issue by filippo-tesi** [ministero-salute/it-fse-support#560]
Buongiorno,
dopo aver caricato i fle per l'accreditamento del nostro applicativo in oggetto (ENDOXWEB - VERS. 25.0) ieri 04/01/24 abbiamo ricevuto questa mail:

------------------------------------------------
Salve,
Con la presente si comunica per il Fornitore [A1#111GRUPPOGPI00] - Vendor:[TESI_SPA] - ID: [ENDOXWEB] - Version: [25.0] - Sha: [a18fbc9ee7474ec0212611750a7cb4b775b64711] la fase preliminare per il processo di accreditamento non è stata rispettata.
Si prega di effettuare una nuova push correttiva.
Saluti,
Il Team FSE 2.0

-----------------------------------------------

l'errors.json riportava questo:

[ {
  "error" : "TEST_NON_PRESENTE",
  "description" : "Test mancanti rispetto alla checklist:[32, 40, 48, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 162, 163, 164, 165, 166, 167, 168, 169]"
} ]

A seguito di questa mail, stamattina ho eseguito la seguente Pull Request:
 
ENDOXWEB - Test 32 e 40 #1087
 
Ho aggiunto i test case 32 e 40, gli altri test case segnalati come non presenti nel vs file errors.json in realtà erano già stati indicati come NON APPLICABILI, quindi non ci è chiaro il motivo dell’errore “NON PRESENTE”.
Abbiamo già completato la FSE 1 di Accreditamento per altri due nostri applicativi RSA ("ECOPLUS" e "DECIA") e il file "report-checklist.xlsx" era molto simile a quello caricato per ENDOXWEB, nel senso che i test che ci avete indicato come NON PRESENTI mancavano anche per ECOPLUS e DECIA.

Restando in attesa di vs gentile riscontro, porgo cordiali saluti.

Filippo Gatto

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Le confermiamo che gli id da Lei indicati risultano non applicabili, pertanto chiediamo cortesemente di non tenere in considerazione l'esito della email inviata in data 04/01. Seguiranno aggiornamenti in merito ai risultati della nuova PR #1087.
Restiamo a disposizione in caso di ulteriore supporto,
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. 
Si può procedere con la riapertura nel caso sia necessario ulteriore supporto. Grazie.
