### ISSUE TITLE
Errore "AuthorizationContentDeny" in seguito alla chiamata https al Gateway (validazione CDA per RSA)

### ISSUE THREAD

**Issue by Itamedical** [ministero-salute/it-fse-support#562]
Buongiorno,

in seguito all'errore di Interoperability segnalato in un precedente ticket abbiamo corretto la valorizzazione dei campi dei JWT come da voi suggerito (vedi file data_jwt_template.json allegato). 
Abbiamo quindi elaborato una nuova chiamata https al Gateway di test e inviato un file pdf di un RSA con CDA iniettato (alleghiamo file pdf con cda iniettato e .zip del cda singolo).

Dal file log che ci viene ritornato (vedi allegato) alla fine compare l'errore:

0000: {"type":"https://govway.org/handling-errors/403/AuthorizationCon
0040: tentDeny.html","title":"AuthorizationContentDeny","status":403,"
0080: detail":"Unauthorized request content","govway_id":"cdea6b8f-a0d
00c0: e-11ee-91c5-005056ae54fa"}
== Info: Connection #0 to host modipa-val.fse.salute.gov.it left intact

Tale errore è sempre dovuto ad una valorizzazione sbagliata dei campi dei token ? Oppure ad una formulazione errata della chiamata https al Gateway? 

Cordiali saluti,

[data_jwt_template.json](https://github.com/ministero-salute/it-fse-support/files/13871341/data_jwt_template.json)

[runGTWHttpsCall.log](https://github.com/ministero-salute/it-fse-support/files/13871320/runGTWHttpsCall.log)

[713862296.pdf](https://github.com/ministero-salute/it-fse-support/files/13871325/713862296.pdf)

[713862296.zip](https://github.com/ministero-salute/it-fse-support/files/13871326/713862296.zip)

**Comment by vigliottim** [comment]
Buongiorno, da una prima analisi i seguenti campi nel data.json risultano non compilati correttamente:

- _"person_id": "@patientRole_extention^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO"_: tale campo deve avere il formato `CODICEFISCALE^^^&2.16.840.1.113883.2.9.4.3.2&ISO`

- _"pem_path": ".\\cert\\auth.pem"_,_"p12_path": ".\\cert\\auth.p12"_: in questi campi devono essere inseriti i path assoluti dei rispettivi certificati 

La invitiamo a correggere gli errori riportati e riprovare, grazie.

**Comment by Itamedical** [comment]
Buongiorno,

abbiamo provato a compilare i campi come da voi consigliato ma l'errore si ripresenta: allego il file .log e il file .json aggiornato. Ci sono altri campi che possono essere errati o campi obbligatori mancanti ?

Grazie.

[runGTWHttpsCall.log](https://github.com/ministero-salute/it-fse-support/files/13885536/runGTWHttpsCall.log)

[data_jwt_template.json](https://github.com/ministero-salute/it-fse-support/files/13885578/data_jwt_template.json)

**Comment by LucaRogledi** [comment]
Buongiorno,
Dall'analisi del file "data_jwt_template.json" notiamo che i certificati referenziati nei seguenti campi:
```
"pem_path": "C:\\CRITEX\\MedITEX IVF_FB2\\FSE2\\cert\\auth.pem",
"p12_path": "C:\\CRITEX\\MedITEX IVF_FB2\\FSE2\\cert\\auth.p12"
```
non presentano un common name nel nome.
Per effettuare la chiamata correttamente, La invitiamo a verificare che stia utilizzando i certificati identificati dal "Common Name" che sono stati condivisi via email.
Grazie

**Comment by Itamedical** [comment]
Buon pomeriggio,

siamo riusciti a risolvere l'errore AuthorizationDeny. Inoltro qui un nuovo errore di sintassi del CDA che si presenta e che riguarda l'elemento <id> del file .xml (trovate file log e xml associati in allegato). Abbiamo valorizzato i diversi attributi in questo modo:
- root= "2.16.840.1.113883.2.9.2.120.4.4"
- extension="2.16.840.1.113883.2.9.2.120.4.4_213608" 
- assigningAuthorityName= "Regione Veneto"

Abbiamo dei dubbi sull'elemento <extension>, come deve essere valorizzato? Nel file CDA di esempio per l'RSA viene riportato il valore "030702.LCNLDE90L47H501Q.20220509102426.Q123E456" (per assigningAuthorityName = "Regione Lazio"), da dove deriva? 

Ringraziamo in anticipo del supporto.

**Comment by LucaRogledi** [comment]
Buonasera, 
dal CDA2 che ci ha fornito, gli errori di sintassi non sono dovuti ad una valorizzazione errata dell'attributo extension dell'elemento ClinicalDocument/id, ma sono una serie di mancate valorizzazioni di alcuni elementi, ad esempio campi codificati, campi di tipo ts (time stamp), e altri id ai quali non è associato alcun valore. 
Questo non è conforme allo schema del CDA2.
Infine, per la corretta valorizzazione dell'extension del ClinicalDocument/id come specificato nelle linee guida HL7, non esiste un vincolo di valorizzazione.

**Comment by Itamedical** [comment]
Perfetto grazie.

Cordiali Saluti
