### ISSUE TITLE
Mancato accreditamento A1#111GRUPPOGPI00 - TESI_SPA - ENDOXWEB - 25.0 - Test KO non superati

### ISSUE THREAD

**Issue by filippo-tesi** [ministero-salute/it-fse-support#564]
Buongiorno abbiamo ricevuto in data 10/01/24 la seguente mail:

Salve,
Con la presente si comunica il mancato superamento dei seguenti test [160, 40, 161, 32] per il servizio [validazione/pubblicazione] del Fornitore [A1#111GRUPPOGPI00] - Vendor:[TESI_SPA] - ID: [ENDOXWEB] - Version: [25.0] - Sha: [2306db3c7af02a2127e33e3ebc6150a258c804d6] in data odierna.
Saluti,
Il Team FSE 2.0

Allego errors.json ricevuto:

[errors.json](https://github.com/ministero-salute/it-fse-support/files/13918927/errors.json)

Nel file errors.json, per tutti i 4 test oggetto della segnalazione, l'errore è il seguente:
"Test KO non superato. Assicurarsi che il traceId fornito abbia restituito in fase di validazione un errore bloccante."

Ho verificato le varie transazioni eseguite durante i test, e i traceId riportati nella checklist e nel data.jason corrispondono a quelli ricevuti da Gateway.

Risposta ricevuta da GW per il test 32:

{
"traceID" : "28480377a3611f73",
"spanID" : "28480377a3611f73",
"type" : "/msg/jwt-validation",
"title" : "Campo token JWT non valido.",
"detail" : "Il campo purpose_of_use non Ã¨ valorizzato",
"status" : 403,
"instance" : "/jwt-mandatory-field-missing",
"workflowInstanceId" : "UNKNOWN_WORKFLOW_ID"
}

Risposta ricevuta da GW per il test 40:

{
"traceID" : "d99f5c579c63a383",
"spanID" : "d99f5c579c63a383",
"type" : "/msg/jwt-validation",
"title" : "Campo token JWT non valido.",
"detail" : "Il campo action_id non Ã¨ corretto",
"status" : 403,
"instance" : "/jwt-mandatory-field-malformed",
"workflowInstanceId" : "UNKNOWN_WORKFLOW_ID"
}

Risposta ricevuta da GW per il test 160:

{
"traceID" : "23afd723061e4346",
"spanID" : "23afd723061e4346",
"type" : "/msg/syntax",
"title" : "Errore di sintassi.",
"detail" : "ERROR: -1,-1 cvc-pattern-valid: Value '' is not facet-valid with respect to pattern '[^\\s]+' for type 'cs'.,ERROR: -1,-1 cvc-attribute.3: The value '' of attribute 'code' on element 'code' is not valid with respect to its type, 'cs'.",
"status" : 400,
"instance" : "/validation/error",
"workflowInstanceId" : "2.16.840.1.113883.2.9.2.50504.4.4.18.56d1da87befe2b4e343b040253682ab96774e267e084581f6d511f6485171e6b.9d8d1320a0^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Risposta ricevuta da GW per il test 161:

{
"traceID" : "18203a19a407f970",
"spanID" : "18203a19a407f970",
"type" : "/msg/semantic",
"title" : "Errore semantico.",
"detail" : "[ERRORE-b4| Sezione Referto: la sezione DEVE essere presente],[ERRORE-b5| Sezione Referto: la sezione DEVE contenere un elemento 'text']",
"status" : 422,
"instance" : "/validation/error",
"workflowInstanceId" : "2.16.840.1.113883.2.9.2.50504.4.4.18.8b5783d7291cb3213d104c0fb9af24903614858af615ec435c06fb02e9277195.556ac4ad6f^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Non riusciamo a capire cosa non vada bene, potete darci maggiori informazioni per favore?

Filippo Gatto

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
Al momento sono in corso le analisi per la risoluzione della presente issue. Le faremo sapere il prima possibile non appena le analisi saranno terminate.
Grazie

**Comment by vigliottim** [comment]
Buongiorno, a causa di un problema tecnico ora risolto, è necessario ripetere le chiamate identificate dagli id per cui è stato segnalato l'errore "TEST_KO_NON_SUPERATO" ed effettuare una nuova PR con le dovute correzioni. 
La ringraziamo per la collaborazione e ci scusiamo per l'inconveniente. Siamo a disposizione per ulteriori richieste di chiarimento.

**Comment by filippo-tesi** [comment]
Buongiorno, ho ripetuto i test case 32,40,160 e 161 e caricato una nuova PR #1118

https://github.com/ministero-salute/it-fse-accreditamento/pull/1118

Saluti.
Filippo Gatto

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Può procedere alla riapertura nel caso avesse bisogno di supporto. Grazie.
