### ISSUE TITLE
Mancato Accreditamento A1#111ABSTRACTXXX - Richiesta dettaglio motivazioni

### ISSUE THREAD

**Issue by stellariAbstract** [ministero-salute/it-fse-support#565]
Buongiorno,
   dopo il tentativo precedente, per i casi KO indicati sono state seguite le indicazioni (Ad esempio per il caso 35 è stato forzatamente svuotato il “purpose_of_use” ottenendo l’errore “Il campo purpose_of_use non Ã¨ valorizzato”).
Cio nonostante sono comunque stati scartati i casi KO con ID 29,35,37 e 43.

In particolare ecco i risultati ricevuti in fase di validazione per i relativi 4 traceID:
43: bdddad9ef467ce4f                  Il campo action_id non Ã¨ corretto
37: e027cd5427651e98                  Il campo action_id non Ã¨ corretto
35: 6316192bb2ed16a3                 Il campo purpose_of_use non Ã¨ valorizzato
29: 2a31a57f069e51ad                  Il campo purpose_of_use non Ã¨ valorizzato

L'ultima pull reqeust è la: "Richiesta accreditamento A1#111ABSTRACTXXX per LDO e VPS #1105".

Posso chiedere una spiegazione dei motivi per i quali questi casi sono stati nuovamente rifiutati?

Grazie.

**Comment by vigliottim** [comment]
Buongiorno, a causa di un problema tecnico ora risolto, è necessario ripetere le chiamate identificate dagli id per cui è stato segnalato l'errore "TEST_KO_NON_SUPERATO" ed effettuare una nuova PR con le dovute correzioni. 
La ringraziamo per la collaborazione e ci scusiamo per l'inconveniente. Siamo a disposizione per ulteriori richieste di chiarimento.

**Comment by stellariAbstract** [comment]
Grazie per la precisazione.
Provvederemo a ripetere i casi.

Stefano.

________________________________
Da: Michela Vigliotti ***@***.***>
Inviato: giovedì, gennaio 18, 2024 9:18:48 AM
A: ministero-salute/it-fse-support ***@***.***>
Cc: Stellari Stefano ***@***.***>; Author ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Mancato Accreditamento A1#111ABSTRACTXXX - Richiesta dettaglio motivazioni (Issue #565)

Non si ricevono spesso messaggi di posta elettronica da ***@***.*** Informazioni sul perché è importante<https://aka.ms/LearnAboutSenderIdentification>

Buongiorno, a causa di un problema tecnico ora risolto, è necessario ripetere le chiamate identificate dagli id per cui è stato segnalato l'errore "TEST_KO_NON_SUPERATO" ed effettuare una nuova PR con le dovute correzioni.
La ringraziamo per la collaborazione e ci scusiamo per l'inconveniente. Siamo a disposizione per ulteriori richieste di chiarimento.

**Comment by stellariAbstract** [comment]
Salvo, ho appena caricato la pull request: "Richiesta accreditamento A1#111ABSTRACTXXX per LDO e VPS #269 
Potete verificare?

Grazie.

**Comment by vigliottim** [comment]
Buongiorno, le confermiamo che la sua PR è stata presa in carico. Riceverà aggiornamenti via e-mail con l'esito delle elaborazioni. Grazie.

**Comment by stellariAbstract** [comment]
Grazie


________________________________

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Può procedere alla riapertura nel caso avesse bisogno di supporto. Grazie.
