### ISSUE TITLE
"Invalid response received from the API Implementation" in risposta a validate-and-create

### ISSUE THREAD

**Issue by davidecasiraghi** [ministero-salute/it-fse-support#568]
Buongiorno,
stiamo testando i metodi di pubblicazione verso il gateway e volevo chiedere un supporto perchè in tutti i nostri tentativi abbiamo questo errore:
{
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "status": 502,
    "detail": "Invalid response received from the API Implementation",
    "govway_id": "f28faeda-b5fd-11ee-9fa8-005056ae7395"
}
Il metodo utilizzato è il ValidateAndCreate a questo url
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validate-and-create
con questi parametri:
--form 'requestBody="{
    \"healthDataFormat\": \"CDA\",
    \"mode\": \"ATTACHMENT\",
    \"tipologiaStruttura\": \"Ospedale\",
    \"identificativoDoc\": \"2.16.840.1.113883.2.9.2.90.3.1.4.4^20230000290\",
    \"identificativoRep\": \"2.16.840.1.113883.2.9.2.90.4.5.1\",
    \"tipoDocumentoLivAlto\": \"REF\",
    \"assettoOrganizzativo\": \"AD_PSC069\",
    \"tipoAttivitaClinica\": \"ERP\",
    \"identificativoSottomissione\": \"2.16.840.1.113883.2.9.2.90.4.3.534455634\"
}"'
Il file del referto inviato viene correttamente validato dal metodo Validate.
I tokens JWT sono i seguenti:
Authorization Token
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGS3pDQ0F4T2dBd0lCQWdJVVpzbzkvN3hrbDJ4NE1YMXVENWlYbWhkOVRjRXdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekF4TWpZeU16RXdNakJhRncweU5qQXhNall5TXpFd01UbGFNR2t4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVIwd0d3WURWUVJoREJSRFJqcEpWQzB4TVRGQ1ExTlRVa3d3TURBd01ERWFNQmdHQTFVRUF3d1JVekVqTVRFeFFrTlRVMUpNTURBd01EQXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNnRJaUpHQXBmYnpmbmU4NE8rdUl2bzJIUXd2Zzd1WFYyM2RubTRkaE40aGtlMEMxNVNKSzNjM2NUTTZHb1lJbXJnbnFuVkRDdW1hQ1lRK3oxTFI0TmRScUFKTlBUNmg1a2M3akZsRmtzclA2T0o0SWRlV2NrQ1NEN25sOFoxdjRjZnNaZ0h3cHFIU1JxUUxHNjIzak1FTjdDMFZURHUyTlJnNm1JT1hCR0t3WFdXMUk0NGhSMHloUUFSVGVDcnlqOXRkQXptNmwvTDJ3MkI4RmlGUS81S3V4VytvakVBdG55QjRJZ1JXbkl2Zk5Vb1BHZlYrdktEZlVjc3RQOHJValo0QTZLZDdaaFk4eEpCWm1xVGZmWjRzOG5VWnUyVldZaFArSXdOVWYrSjVWS3JmLzdiazhxNGJoYmRPdGM0b01zNkNTcDhubUJSalhiY0tNU2lKYXJBZ01CQUFHamdkd3dnZGt3SHdZRFZSMGpCQmd3Rm9BVUZqbXBHZ1dKdHc4dHNqWHR3Z21heFFPRElqOHdFZ1lEVlIwZ0JBc3dDVEFIQmdVclRCMEJDekJ6QmdOVkhSOEViREJxTUdpZ1pxQmtobUpzWkdGd09pOHZZMkZrY3k1bWFXNWhibnBsTG1sMEwwTk9QVU5CSlRJd1RXbHVhWE4wWlhKdkpUSXdaR1ZzYkdFbE1qQlRZV3gxZEdVbE1qQlVaWE4wTEU4OVRXbHVhWE4wWlhKdkpUSXdaR1ZzYkdFbE1qQlRZV3gxZEdVc1F6MUpWREFkQmdOVkhRNEVGZ1FVbFNWU0ZkQ2lWMmVHdmh6YndQT2hJVHBUQytVd0RnWURWUjBQQVFIL0JBUURBZ1pBTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFDT2RYOUZPVHVmS1lnVEw3QmpyRFcybEFlL3RyYklLK1lGRW1VZnI4U2lCbnMyTEl1TFZNaHhWOEZDL1FFYXV0bG9IbW9tYjlBc1hiS21FNlVTSHVCOG94cGhIV0x2NXIzSFhxczNIYTg4bVlEd1RicTJXcHNZQ2FLYm5HcFVBTlpVYzJYQ1p6Y2d3d2x1ellhQ2pKZFhPdnhoS283ZVBTa25IN0E0SHd1Tzl6alNZbHcva2JERCtJS1FZWnRZRHQzUWd2VXhjc3plSzNSbnVVNWI3eUFwbFdQcjhIMFZxMGh6Z1ZMSFdnUlRnZEJxT0NERFJsd0d1cFFzbGlYSWpCWTFENW02Yi9XR1B4UGFXaDA3ei9vK1Q5R0JnS3REYTMyK1dhd1JMTWlZZG03TkFXOXVKVFBzV25Lb2dVdkJvMEdWUSs0RXhvMDVLZFY3QVdTUzIrMXVIM1lTZUNaQ0hxQVJkK056Zmp3Q3lLZ3pVQWtOMHJHbGRtWUVuTHhVeG1FclhmcENkcmNVSUdMb3gxcWxkWEdjeVlCTnE1eEpUK3IxelVHQ3BvUGdyNjlDOXZKM0hDY1BlQ0V0aUNGNzZsV25uWDM1eFE5VlVQRmpUNXhDMWxlMjBqYkVid3d4bngraU9WeFJGSW4yeVpoYlZYSkRoNi9QSVY3SzZqYnUxaGZVaE9HUE4zV1B3dUdQTTJxVkJYMjdzZ1VXekl2VHArTmFFZnJzM2NFZjJURGNEOFJicXhReGI4SUdML1VPamxmbDh5aUc0M25hUVo0ZXJZSXJ3WW4yOUdwVitVaE9YYlpwaGVNZnVJM2p3cnhteGRZSm5zNDljamZheUY3aWhuK0c5MWFQQmNDQ2NHd0QzMDN6WGNuY1drUTV4WHVWd0MybDlEcGlyREVrUHc9PSJdfQ.eyJpc3MiOiJhdXRoOlMxIzExMUJDU1NSTDAwMDAwIiwiaWF0IjoxNzA1NTgyMzcyLCJleHAiOjE3MDU1ODQxNzIsImp0aSI6IjE3MDU1ODIzNzI6MTI2IiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwic3ViIjoiVkRTVFRPNjhNMDhGMjA1Wl5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIn0.M2y5kle1093Pv753Cj3Ya6zgnZ-doRxojo9flVpRNfQ2qmUlKbzf-I6IthjXX08PlzqjEC3pB4zO5KN_cSngCt6j-QFUCf5KzCIMljdfPWB80SgSjy5Lo1tQ144KgcA3cWGCS9iaY1Ajb2OOETD2Wqhx2mQ7P0OBdFm5yI2ZD334iHVIHbsTPpRkEQbcOsRTSDMPe6Q4NMfivxXcf1P_RQ_xOhk1hblpf0o2S0m1QMrppO5AgIZTZHyyTFw5Yqo8eYnwcMhFnlRS8nWxMACTKuJ4L5FUfxIE_ORbu95t4qt6RK5utl3NMgyDb7xdRObyxYd5OXP1wKQR13ZHefM1IA
Signature Token
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGS3pDQ0F4T2dBd0lCQWdJVVpzbzkvN3hrbDJ4NE1YMXVENWlYbWhkOVRjRXdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekF4TWpZeU16RXdNakJhRncweU5qQXhNall5TXpFd01UbGFNR2t4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVIwd0d3WURWUVJoREJSRFJqcEpWQzB4TVRGQ1ExTlRVa3d3TURBd01ERWFNQmdHQTFVRUF3d1JVekVqTVRFeFFrTlRVMUpNTURBd01EQXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNnRJaUpHQXBmYnpmbmU4NE8rdUl2bzJIUXd2Zzd1WFYyM2RubTRkaE40aGtlMEMxNVNKSzNjM2NUTTZHb1lJbXJnbnFuVkRDdW1hQ1lRK3oxTFI0TmRScUFKTlBUNmg1a2M3akZsRmtzclA2T0o0SWRlV2NrQ1NEN25sOFoxdjRjZnNaZ0h3cHFIU1JxUUxHNjIzak1FTjdDMFZURHUyTlJnNm1JT1hCR0t3WFdXMUk0NGhSMHloUUFSVGVDcnlqOXRkQXptNmwvTDJ3MkI4RmlGUS81S3V4VytvakVBdG55QjRJZ1JXbkl2Zk5Vb1BHZlYrdktEZlVjc3RQOHJValo0QTZLZDdaaFk4eEpCWm1xVGZmWjRzOG5VWnUyVldZaFArSXdOVWYrSjVWS3JmLzdiazhxNGJoYmRPdGM0b01zNkNTcDhubUJSalhiY0tNU2lKYXJBZ01CQUFHamdkd3dnZGt3SHdZRFZSMGpCQmd3Rm9BVUZqbXBHZ1dKdHc4dHNqWHR3Z21heFFPRElqOHdFZ1lEVlIwZ0JBc3dDVEFIQmdVclRCMEJDekJ6QmdOVkhSOEViREJxTUdpZ1pxQmtobUpzWkdGd09pOHZZMkZrY3k1bWFXNWhibnBsTG1sMEwwTk9QVU5CSlRJd1RXbHVhWE4wWlhKdkpUSXdaR1ZzYkdFbE1qQlRZV3gxZEdVbE1qQlVaWE4wTEU4OVRXbHVhWE4wWlhKdkpUSXdaR1ZzYkdFbE1qQlRZV3gxZEdVc1F6MUpWREFkQmdOVkhRNEVGZ1FVbFNWU0ZkQ2lWMmVHdmh6YndQT2hJVHBUQytVd0RnWURWUjBQQVFIL0JBUURBZ1pBTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFDT2RYOUZPVHVmS1lnVEw3QmpyRFcybEFlL3RyYklLK1lGRW1VZnI4U2lCbnMyTEl1TFZNaHhWOEZDL1FFYXV0bG9IbW9tYjlBc1hiS21FNlVTSHVCOG94cGhIV0x2NXIzSFhxczNIYTg4bVlEd1RicTJXcHNZQ2FLYm5HcFVBTlpVYzJYQ1p6Y2d3d2x1ellhQ2pKZFhPdnhoS283ZVBTa25IN0E0SHd1Tzl6alNZbHcva2JERCtJS1FZWnRZRHQzUWd2VXhjc3plSzNSbnVVNWI3eUFwbFdQcjhIMFZxMGh6Z1ZMSFdnUlRnZEJxT0NERFJsd0d1cFFzbGlYSWpCWTFENW02Yi9XR1B4UGFXaDA3ei9vK1Q5R0JnS3REYTMyK1dhd1JMTWlZZG03TkFXOXVKVFBzV25Lb2dVdkJvMEdWUSs0RXhvMDVLZFY3QVdTUzIrMXVIM1lTZUNaQ0hxQVJkK056Zmp3Q3lLZ3pVQWtOMHJHbGRtWUVuTHhVeG1FclhmcENkcmNVSUdMb3gxcWxkWEdjeVlCTnE1eEpUK3IxelVHQ3BvUGdyNjlDOXZKM0hDY1BlQ0V0aUNGNzZsV25uWDM1eFE5VlVQRmpUNXhDMWxlMjBqYkVid3d4bngraU9WeFJGSW4yeVpoYlZYSkRoNi9QSVY3SzZqYnUxaGZVaE9HUE4zV1B3dUdQTTJxVkJYMjdzZ1VXekl2VHArTmFFZnJzM2NFZjJURGNEOFJicXhReGI4SUdML1VPamxmbDh5aUc0M25hUVo0ZXJZSXJ3WW4yOUdwVitVaE9YYlpwaGVNZnVJM2p3cnhteGRZSm5zNDljamZheUY3aWhuK0c5MWFQQmNDQ2NHd0QzMDN6WGNuY1drUTV4WHVWd0MybDlEcGlyREVrUHc9PSJdfQ.eyJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExQkNTU1JMMDAwMDAiLCJpYXQiOjE3MDU1ODIzNzIsImV4cCI6IjE3MDU1ODQxNzIiLCJqdGkiOiIxNzA1NTgyMzcyOjM2OSIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInN1YiI6IlZEU1RUTzY4TTA4RjIwNVpeXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMDkwIiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb25lIFRvc2NhbmEiLCJsb2NhbGl0eSI6IjY5MDI3MiIsInN1YmplY3Rfcm9sZSI6IkFBUyIsInBlcnNvbl9pZCI6IlBSRENRTjgwQjY4TDMzMUpeXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyIsInBhdGllbnRfY29uc2VudCI6dHJ1ZSwicHVycG9zZV9vZl91c2UiOiJUUkVBVE1FTlQiLCJyZXNvdXJjZV9obDdfdHlwZSI6IignNjg2MDQtOF5eMi4xNi44NDAuMS4xMTM4ODMuNi4xJykiLCJhY3Rpb25faWQiOiJDUkVBVEUiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiUHJpYW1vUklTIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZW5kb3IiOiJCQ1MiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlcnNpb24iOiI0LjE0LjAuMCJ9.Ui0uFpudmezpsIYpyHhA6SyAiHJ89O0JiBdXLr2FOki9BW65R-Jto0ucw5DYqthJSEbvF6lK325qbqq1L_WE2J-lvZkQuIRRFcmoFHQM6QEOb_Bmi8uuaRNVul5ESjfwrnodOaGAM7U8VD_1t87ya0L8-0Dn0dLukBrZ7lxnNf8OSe3jz9Cm43ckARimvdj5GAKjWqZUtWRf5L8YzKFqKKMnCynEkqi27bu_rubIs1cqADlACPkL90vtBLiWK2BRlcshy9-LI-34I90_hvUBFEUUX475-zOhXmotzPF5QN_cu5d197Pw0FdcsKQqvFLj0SmgDfMusc5Nk4UQBJzPGw

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate è emerso che il documento allegato non viene correttamente validato. 
Le riportiamo di seguito l'errore ricevuto:
 
```
{
  "traceID": "5c9f4f28693883cf",
  "spanID": "5c9f4f28693883cf",
  "type": "/msg/semantic",
  "title": "Errore semantico.",
  "detail": "[ERRORE-10a| L'elemento ClinicalDocument/recordTarget/patientRole/id  deve avere l'attributo @root valorizzato tramite uno dei seguenti identificatori Nazionanli:\n\t\t\tCF 2.16.840.1.113883.2.9.4.3.2 (Nel caso di Cittadino Italiano o straniero residente in Italia, patientRole DEVE riportare un elemento di tipo id contenente il Codice Fiscale e un ulteriore elemento id OBBLIGATORIO contenente il numero di identificazione dell’assistito nel sistema PACS (@nullFlavour è ammesso ove l’informazione non sia disponibile).)\n\t\t\tTEAM 2.16.840.1.113883.2.9.4.3.7 e 2.16.840.1.113883.2.9.4.3.3\n\t\t\tENI 2.16.840.1.113883.2.9.4.3.18\n\t\t\tSTP 2.16.840.1.113883.2.9.4.3.17 oppure un identificativo regionale \n\t\t\tANA 2.16.840.1.113883.2.9.4.3.15\n\t\t\tOppure tramite gli identificatori regionali generati per rappresentare l'id del paziente.\n\t\t\t],[W005 | Sezione Esame Eseguito: l'entry/act/code può essere valorizzato secondo i sistemi di codifica\n\t\t\tLOINC @codeSystem='2.16.840.1.113883.6.1'\n\t\t\tICD-9-CM @codeSystem='2.16.840.1.113883.6.103']",
  "status": 422,
  "instance": "/validation/error",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.a6ab80be41e70737b6ebef75e3bf01fe2397365dedd9df266013e166315728ef.ee81649eab^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
 
```
La invitiamo a correggere gli errori riportati in "detail" e, in seguito, ad effettuare una nuova chiamata al servizio validate-and-create. 
La informiamo che stiamo verificando perché il messaggio ricevuto (errore di invalid response) sia diverso dal messaggio riportato sopra (errore di tipo semantico).
Grazie.

**Comment by davidecasiraghi** [comment]
Buongiorno,
grazie, abbiamo corretto il problema e la pubblicazione è riuscita correttamente
E' possibile avere in risposta l'errore di validazione invece che un generico "Invalid response received from the API Implementation" ?

**Comment by vigliottim** [comment]
Buonasera, il team tecnico di competenza sta verificando mai non riceva l'errore di validazione al posto dell'errore generico "Invalid response received from the API Implementation". Le riporteremo eventuali aggiornamenti non appena saranno disponibili. Grazie.

**Comment by LucaRogledi** [comment]
Buonasera, 
Le confermiamo che è stato rilasciato un aggiornamento. 
La invitiamo cortesemente a riprovare e rimaniamo a disposizione in caso fosse necessario ulteriore supporto. 
Grazie

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori aggiornamenti, procediamo alla chiusura della presente issue. 
Può procedere alla riapertura in caso avesse bisogno di ulteriore supporto. Grazie.
