### ISSUE TITLE
disallineamento tra specifiche interfacce e comportamento gateway per CDA allegato

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#569]
Buongiorno,
le specifiche delle Interfacce REST del Gateway 
https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#2-contesto-di-riferimento
indicano che 
il nome CDA allegato deve essere “cda.xml”.

Eseguendo alcuni test risulta però che il gateway accetta anche file con nome CDA.XML (tutto in maiuscolo).

La response del Gateway non risulta allineata con le specifiche dato che a fronte di un allegato con nome CDA.XML dovrebbe essere restituito un errore.

**Comment by vigliottim** [comment]
Buongiorno, le chiediamo di inviarci cortesemente la response completa ricevuta (comprensiva di trace id/govway), per consentirci indagini più approfondite. Grazie.

**Comment by ponsilva** [comment]
Buongiorno,
ho effettuato poco fa una chiamata di validation e ricevo in risposta

HTTP/1.1 201 Created

{
	"traceID": "5c0a0fde46ea76c7",
	"spanID": "5c0a0fde46ea76c7",
	"workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.e617136e36^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

**Comment by vigliottim** [comment]
Buongiorno, la informiamo che la documentazione al link [integrazione-gateway](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway) è stata aggiornata in seguito alla sua segnalazione. Restiamo a disposizione per ulteriori richieste di supporto.
