### ISSUE TITLE
Test 4 LDO sezione "Storia_Clinica" assente  

### ISSUE THREAD

**Issue by dinelliascom** [ministero-salute/it-fse-support#57]
dalla specifiche per l'accreditamento alla riga "265" è riportato: `ClinicalDocument/component/structuredBody/component/section[@ID=Storia_Clinica]/component/section[@ID=Allergie]/entry/act/entryRelationship/observation/entryRelationship/observation/text ma nella documentazione HL7 la sezione "Storia_Clinica" non è presente`
ma nella documentazione HL7 la sezione non è presente.

**Comment by Ser-ena** [comment]
Buongiorno, grazie per la segnalazione. E' stato aggiornato il file del caso di test 4 per LDO, trova la documentazione al link https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/6-Lettera%20di%20Dimissione%20Ospedaliera
