### ISSUE TITLE
Jwt Generator

### ISSUE THREAD

**Issue by simeds** [ministero-salute/it-fse-support#570]
Buongiorno,

 

stiamo procedendo con la procedura di accreditamento.

 

Durante la creazione del JWT- GENERATOR abbiamo questo errore relativo alla mancanza della key. 
![image](https://github.com/ministero-salute/it-fse-support/assets/157040429/f0002144-2f8c-4997-934f-c804b0886a6c)

Noi però abbiamo inserito i dati nel data.json come qua riportato:

 

{
	"sub": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",    
	"subject_role": "AAS",
	"purpose_of_use": "TREATMENT",
	"iss": "jwt-issuer",
	"subject_application_id": "CCT",
	"subject_application_vendor": "Simeds",
	"subject_application_version": "1",
	"locality": "jwt-location",
	"subject_organization_id": "120",
	"subject_organization": "Regione Lazio",
	"aud": "FSE_Gateway",
	"patient_consent": true,
	"action_id": "CREATE",
	"resource_hl7_type": "('11502-2^^2.16.840.1.113883.6.1')",
	"jti": "1234",
	"person_id":"RSSMRA22A01A399Z^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO",
	"pem_path": "./A1#111SIMEDSSRLCXX.pem",
	"p12_path": "./A1#111SIMEDSSRLCXX.p12"
}

Sapete darci assistenza?
 
Grazie

**Comment by ponsilva** [comment]
Buongiorno,
mi inserisco in questo thread perché in alcuni test avevo incontrato un errore simile.

jwt-generator usa parametri e dati che fanno riferimento a un certificato
-a   Alias of p12 cert used to execute the JWT signature
-p   Password of p12 cert used to execute the JWT signature
pem_path   pem certificate path
p12_path   p12 certificate path

Il certificato a cui ci si riferisce è quello di firma (**signature**) e anche il p12 deve essere creato a partire dal certificato di firma seguendo queste istruzioni:
https://github.com/ministero-salute/it-fse-support/issues/499#issuecomment-1754950460

jwt-generator usa solo il certificato di firma per generare i JWT, mentre quello di autenticazione viene utilizzato nel client http per il trasporto (quindi all'atto della chiamata al servizio).

**Comment by simeds** [comment]
Buongiorno,
ho creato il file p12 partendo dal file S1#111SIMEDSSRLCXX.pem che dovrebbe essere quello di signature ma ottengo il solito errore descritto nell'apertura della issue.

**Comment by simeds** [comment]
Sono ad aggiungere che il problema che riscontro è nell'utilizzo del tool jwt-generator. Non riesco infatti a generare il token diper l'autorizzazione configurando nel file data.json, sia il file generato partendo dal file A1#111SIMEDSSRLCXX.pem (file di autorizzazione), sia utilizzando il file di signature (S1#111SIMEDSSRLCXX). Leggendo la documentazione ho capito che per effettuare le chiamate agli end-point devo utilizzare il token generato dal tool ma non riesco ad ottenerlo. Lo sto utilizzando in maniera errata?

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Ringraziamo in primo luogo @ponsilva per il tempestivo supporto e Le confermiamo @simeds che i certificati da utilizzare per la generazione dei token sono quelli di firma che sono riconoscibili dalla stringa "S1".
La invitiamo gentilmente ad effettuare un'ulteriore verifica utilizzando lo stesso comando openssl, integrando il parametro -name, per la generazione di un alias del certificato:

`openssl pkcs12 -export -name cert -out client_sign.p12 -inkey client_sign.key -in client_sign.pem `

Il parametro "-name" definisce il nome dell'alias da passare poi al jar tramite il parametro -a.

Restiamo a disposizione in caso l'errore dovesse persistere.
Grazie

**Comment by igcomsrl** [comment]
identificato il problema: abbiamo dimenticato gli apicetti singoli. Grazie

**Comment by IStacchiotti** [comment]
Buonasera @igcomsrl, forse si riferiva al thread del ticket #572? Grazie

**Comment by igcomsrl** [comment]
chiedo scusa
ho sbagliato thread

**Comment by simeds** [comment]
Buongiorno, 
grazie per avermi suggerito l'utilizzo del paramentro -name. Ma il problema persisteva e sono riuscito a risolvere solo oggi  reimpostanto il metodo KeyStore.getInstance contenuto all'interno della funzione extractKeyByAliasFromP12. Impostanto il metodo come segue:
KeyStore.getInstance("PKCS12") senza specificare il parametro provider.
Cosi facendo e ricompilando il programma l'esecuzione del jar in ambiente java 17 va a buon fine.
