### ISSUE TITLE
Errore Validazione

### ISSUE THREAD

**Issue by igcomsrl** [ministero-salute/it-fse-support#572]
Buongiorno, stiamo eseguendo un test di validazione per controllare le nostre impostazioni,
ma otteniamo il seguente errore:
{
  "type": [https://govway.org/handling-errors/403/AuthorizationContentDeny.html](https://cas5-0-urlprotect.trendmicro.com/wis/clicktime/v1/query?url=https%3a%2f%2fgovway.org%2fhandling%2derrors%2f403%2fAuthorizationContentDeny.html&umid=fcf57805-3cd6-459c-b43a-d3383cec0b77&auth=71a13bea07be23dc94f0190f69b0bbb0f54ab581-f0bd95cd1c96e2e6f4639a1803f9a3974b96e6cc),
  "title": "AuthorizationContentDeny",
  "status": 403,
  "detail": "Unauthorized request content",
  "govway_id": "5656c8d6-b90f-11ee-9fa8-005056ae7395"
}
 
di seguito quello che facciamo:
 
eseguiamo la chiamata al servizio : https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation
l’auth. Token è il seguente:
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGYURDQ0ExQ2dBd0lCQWdJVUxiUFl4R2MzSjFPNDQ1d0JpbDJiNngrNDBVVXdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekExTVRZeU1UVTNNRGhhRncweU5qQTFNVFl5TVRVM01EZGFNR2t4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVIwd0d3WURWUVJoREJSRFJqcEpWQzB4TVRGSlIwTlBUVk5TVEZoWVdERWFNQmdHQTFVRUF3d1JVekVqTVRFeFNVZERUMDFUVWt4WVdGZ3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDajlYTnFZSHNDc2pIdjVWWXpqWWtDMEhlUzArNThNL1NlV1Frd2lNTHhwTXVOelgzTXhVazNGQ2lTNjRYbVl0cW80WlcyRWF0UmNrVUlVd0ZqbUZiMUUwMy9vR2FBWlEzUktQemlFM05ueHk0UHIrY3BnNUEwZTY1MUl1UkpFMGlvckVIZUxhQWtYdVlaMVlhdHlkQWhtaktCZHpPWURoS1hSdWg0OHBNUStuTmdTVEwvREdqRUJmMHNUZkw0R3VqTld2ZHA3Ym9ZQnVNbW9YeW51ZW5iTEJJNzR0YlR5NDk2UVN6bXBPaFpCTTF1MXpFSDJmOVRjdzVNTk1oVGVxS3ljRHRDT1pmVktQNGdyNitjaWZFa05GTWVNNWNmWURZaWFRbXhQT09DeXoyMXpxcld0ZTFzb3pVRkNtSVRDVnBVcmVScGVqNmRhU3ltdHRxRUNEdjdBZ01CQUFHamdnRVlNSUlCRkRBZkJnTlZIU01FR0RBV2dCUVdPYWthQlltM0R5MnlOZTNDQ1pyRkE0TWlQekFTQmdOVkhTQUVDekFKTUFjR0JTdE1IUUVMTUlHdEJnTlZIUjhFZ2FVd2dhSXdnWitnZ1p5Z2dabUdnWlpvZEhSd2N6b3ZMMk5oYzI5blpXbHpkbWxzTG5OdloyVnBMbWwwTDJWcVltTmhMM0IxWW14cFkzZGxZaTkzWldKa2FYTjBMMk5sY25Sa2FYTjBQMk50WkQxamNtd21hWE56ZFdWeVBVTk9KVE5FUTBFclRXbHVhWE4wWlhKdksyUmxiR3hoSzFOaGJIVjBaU3RVWlhOMEpUSkRUeVV6UkUxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVWxNa05ESlRORVNWUXdIUVlEVlIwT0JCWUVGUEhWbW9jRTk1ZFRFTmZRVmt2bDl2aHk1alJmTUE0R0ExVWREd0VCL3dRRUF3SUdRREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBZ0p4UlY1UEFadEZ3OFM5SXlFK2JmcVcrTVkvOHlCOTBtWE9hZ3FhN3VEeU9vVDlqT2RRUmw4bWhwN0tuNTNDMGJLeFVhc2Z0eXRzS0t6bnRia3pBakh4ZldtWlJvTFBtS2tyajNWazNWK3dIOGE5WTBRRHpPSFNYdDdHejJwUjZXTUphVzB4Wll1R0drSjFuTjlGaXgxTTBLMkZYVFdvTDY3bjBETGxCSEs2SlQ2WVdCTVArVnR6MkI0aVNrcW5FdFhLay9TU1h6MTNBQm5ObjR2NmJWaWUyRXk5Z1dVWkcxWFFJQ1gxY1Bnd0tybnM5UGZpQ3FpcElEOWJIeDRqZ2o5MTArZVBZODhPZ0NEWFhNdDhtMk9qS1RYb3JBZ0dvQVNONmRqQU9uYkNnbHNyU1A5WU1hemNtMnI1SFdneDFlcjZMbzFhODVUc1lJdWVEUFlWUG5ZWkRBM2R6dWYwS3VqUjVDdXVYRG9hYmU5Q25aaHFSdnE4UEd2RGJpa3I5eFlZUitOeWRiNDdpY2dGZXJ5bXQ3b09yWFk1cE50WjB4T1FKOExiL1ExSHJwYmpmcy8yYTJLSEdjSlhUc2JOL01WZEFGdTBtdmMvRlpSQzNDWG9KanFHWUdMNWZtMDg0ZFByTDNFa29RcTFkNklSajVnY1ZuSlZTc2w1Mk9KamRVS3dBWkxlN2toMm1GMTZkSUpidmRhMGRUNCtkVFlOVFFxMFpsYnFoWXZaYjNTNEJVaTkwSE04b3g1U3pkT1ZkUFNRc2g3Qk84Qjl3VzdYQ0ZqNWk5dlhvR2N3MzY5T01yajJVYkJjRjVSUmYvR1k3S3hTTDQ0QXZYeldsUmJOUXhlOXVDcENSdFkzSmRuNWUyZE51OVdZTmJQZUhNTEM0MHIzUXlwT3R5Ujg9Il19.eyJuYmYiOjE3MDU5MjA0MDUsImV4cCI6MTcwNjAwNjgwOCwiaWF0IjoxNzA1OTIwNDA1LCJpc3MiOiJhdXRoOlMxIzExMSNJR0NPTVNSTFhYWCIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsImp0aSI6IjgzMzRlNGI3LWQ0ODYtNDNkZC05YWVhLTNjMTAzOGQ4MGY4OCIsInN1YiI6IlBST1ZBWDAwWDAwWDAwMFleXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyJ9.Fpq0NzrNJZLw6ZEkhZw7oHkh0t9L7SNnb_d4h0E72eeL0dzosLD-dIkBwdoFipzi4ZOkfuy9RzZty_H9mbbwhG-FFBwXkbjdfPso0x-iZqGoONmmh6axr56K8A1BuN4rDjM6V2YiD_S9vmujX5infp-OeS1Q9WNsHUUkKFar9LPotk-dbo4Ov2zBHzDL5SB73OpDPDY-RYiChMHEBHTMdkWvwJ99qQWQYafZkvl4gZ-dVsSQrbJzIR-NpWhp7tNboxk0bqef4qifY9-AMEaKsDZkjx6CmQLxK8sEOsYVFfmzw2dZQ1EDtuH9D0qyfEHEqHqNRnc4Aq5JWTITI1-sJg
 
mentre il sign.token è il seguente:
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGYURDQ0ExQ2dBd0lCQWdJVUxiUFl4R2MzSjFPNDQ1d0JpbDJiNngrNDBVVXdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekExTVRZeU1UVTNNRGhhRncweU5qQTFNVFl5TVRVM01EZGFNR2t4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVIwd0d3WURWUVJoREJSRFJqcEpWQzB4TVRGSlIwTlBUVk5TVEZoWVdERWFNQmdHQTFVRUF3d1JVekVqTVRFeFNVZERUMDFUVWt4WVdGZ3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDajlYTnFZSHNDc2pIdjVWWXpqWWtDMEhlUzArNThNL1NlV1Frd2lNTHhwTXVOelgzTXhVazNGQ2lTNjRYbVl0cW80WlcyRWF0UmNrVUlVd0ZqbUZiMUUwMy9vR2FBWlEzUktQemlFM05ueHk0UHIrY3BnNUEwZTY1MUl1UkpFMGlvckVIZUxhQWtYdVlaMVlhdHlkQWhtaktCZHpPWURoS1hSdWg0OHBNUStuTmdTVEwvREdqRUJmMHNUZkw0R3VqTld2ZHA3Ym9ZQnVNbW9YeW51ZW5iTEJJNzR0YlR5NDk2UVN6bXBPaFpCTTF1MXpFSDJmOVRjdzVNTk1oVGVxS3ljRHRDT1pmVktQNGdyNitjaWZFa05GTWVNNWNmWURZaWFRbXhQT09DeXoyMXpxcld0ZTFzb3pVRkNtSVRDVnBVcmVScGVqNmRhU3ltdHRxRUNEdjdBZ01CQUFHamdnRVlNSUlCRkRBZkJnTlZIU01FR0RBV2dCUVdPYWthQlltM0R5MnlOZTNDQ1pyRkE0TWlQekFTQmdOVkhTQUVDekFKTUFjR0JTdE1IUUVMTUlHdEJnTlZIUjhFZ2FVd2dhSXdnWitnZ1p5Z2dabUdnWlpvZEhSd2N6b3ZMMk5oYzI5blpXbHpkbWxzTG5OdloyVnBMbWwwTDJWcVltTmhMM0IxWW14cFkzZGxZaTkzWldKa2FYTjBMMk5sY25Sa2FYTjBQMk50WkQxamNtd21hWE56ZFdWeVBVTk9KVE5FUTBFclRXbHVhWE4wWlhKdksyUmxiR3hoSzFOaGJIVjBaU3RVWlhOMEpUSkRUeVV6UkUxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVWxNa05ESlRORVNWUXdIUVlEVlIwT0JCWUVGUEhWbW9jRTk1ZFRFTmZRVmt2bDl2aHk1alJmTUE0R0ExVWREd0VCL3dRRUF3SUdRREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBZ0p4UlY1UEFadEZ3OFM5SXlFK2JmcVcrTVkvOHlCOTBtWE9hZ3FhN3VEeU9vVDlqT2RRUmw4bWhwN0tuNTNDMGJLeFVhc2Z0eXRzS0t6bnRia3pBakh4ZldtWlJvTFBtS2tyajNWazNWK3dIOGE5WTBRRHpPSFNYdDdHejJwUjZXTUphVzB4Wll1R0drSjFuTjlGaXgxTTBLMkZYVFdvTDY3bjBETGxCSEs2SlQ2WVdCTVArVnR6MkI0aVNrcW5FdFhLay9TU1h6MTNBQm5ObjR2NmJWaWUyRXk5Z1dVWkcxWFFJQ1gxY1Bnd0tybnM5UGZpQ3FpcElEOWJIeDRqZ2o5MTArZVBZODhPZ0NEWFhNdDhtMk9qS1RYb3JBZ0dvQVNONmRqQU9uYkNnbHNyU1A5WU1hemNtMnI1SFdneDFlcjZMbzFhODVUc1lJdWVEUFlWUG5ZWkRBM2R6dWYwS3VqUjVDdXVYRG9hYmU5Q25aaHFSdnE4UEd2RGJpa3I5eFlZUitOeWRiNDdpY2dGZXJ5bXQ3b09yWFk1cE50WjB4T1FKOExiL1ExSHJwYmpmcy8yYTJLSEdjSlhUc2JOL01WZEFGdTBtdmMvRlpSQzNDWG9KanFHWUdMNWZtMDg0ZFByTDNFa29RcTFkNklSajVnY1ZuSlZTc2w1Mk9KamRVS3dBWkxlN2toMm1GMTZkSUpidmRhMGRUNCtkVFlOVFFxMFpsYnFoWXZaYjNTNEJVaTkwSE04b3g1U3pkT1ZkUFNRc2g3Qk84Qjl3VzdYQ0ZqNWk5dlhvR2N3MzY5T01yajJVYkJjRjVSUmYvR1k3S3hTTDQ0QXZYeldsUmJOUXhlOXVDcENSdFkzSmRuNWUyZE51OVdZTmJQZUhNTEM0MHIzUXlwT3R5Ujg9Il19.eyJuYmYiOjAsImV4cCI6MTcwNjAwNjgwNywiaWF0IjoxNzA1OTIwNDA1LCJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExI0lHQ09NU1JMWFhYIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwianRpIjoiYTBmMTcxNTYtMzNlYS00ZWUyLTlhMTYtNjA1Nzk1MTk5MTQyIiwic3ViIjoiUFJPVkFYMDBYMDBYMDAwWV5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIiwic3ViamVjdF9vcmdhbml6YXRpb25faWQiOiIxMjAiLCJzdWJqZWN0X29yZ2FuaXphdGlvbiI6IlJlZ2lvbmUgTGF6aW8iLCJsb2NhbGl0eSI6IjEyMDIwNSIsInN1YmplY3Rfcm9sZSI6IkFBUyIsInBlcnNvbl9pZCI6IlNTU01OTjc1QjAxRjI1N0xeXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyIsInBhdGllbnRfY29uc2VudCI6dHJ1ZSwicHVycG9zZV9vZl91c2UiOiJUUkVBVE1FTlQiLCJhY3Rpb25faWQiOiJDUkVBVEUiLCJyZXNvdXJjZV9obDdfdHlwZSI6IigxMTUwMi0yXl4yLjE2Ljg0MC4xLjExMzg4My42LjEpIiwiYXR0YWNobWVudF9oYXNoIjoiIiwic3ViamVjdF9hcHBsaWNhdGlvbl9pZCI6IklHU1VJVEUiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlbmRvciI6IklHQ09NIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiNC4wIn0.B9lmwJb6W_r1vgFMd6UAIOwU49EU7CFVXLL0vPhKaWDleXyBtmlEhZQoAc8jEX1S_l33ZWlIDaSGwsLlS0XZK5aDayNvueJi94e8Y__vyENLSvYZcaCjEB5aP8hAeNVzpGP9jrTXdYqRTo-PMfxtGxSFM-zLXDEQ0TdttumE0EeOsCPV_LuyM9wFXaUs65pQIJkBRtrJoYJvuiEB39xZqqH2EO97BqpmfAauWgKbrwRDHvTrzM6hNUFUg6HOp7N7VU0yZWE9OSVqGNv8ONGV0xqxtbhCENVw6JGq9qH_TKHQYyOqPZOwT8Z8H-qbdQb79WFABXL-JMMmbFBjcAAsXA
 
che mediante verifica su jwt risultano:
 
auth:
{
  "nbf": 1705920405,
  "exp": 1706006808,
  "iat": 1705920405,
  "iss": "auth:S1#111#IGCOMSRLXXX",
  "aud": https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1,
  "jti": "8334e4b7-d486-43dd-9aea-3c1038d80f88",
  "sub": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO"
}
Sign:
 
{
  "nbf": 0,
  "exp": 1706006807,
  "iat": 1705920405,
  "iss": "integrity:S1#111#IGCOMSRLXXX",
  "aud": https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1,
  "jti": "a0f17156-33ea-4ee2-9a16-605795199142",
  "sub": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "subject_organization_id": "120",
  "subject_organization": "Regione Lazio",
  "locality": "120205",
  "subject_role": "AAS",
  "person_id": "SSSMNN75B01F257L^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "patient_consent": true,
  "purpose_of_use": "TREATMENT",
  "action_id": "CREATE",
  "resource_hl7_type": "(11502-2^^2.16.840.1.113883.6.1)",
  "attachment_hash": "",
  "subject_application_id": "IGSUITE",
  "subject_application_vendor": "IGCOM",
  "subject_application_version": "4.0"
}

[Test_Case_Referto.pdf](https://github.com/ministero-salute/it-fse-support/files/14011765/Test_Case_Referto.pdf)

Potete darci indicazioni in merito, grazie mille

**Comment by vigliottim** [comment]
Buonasera, al fine di fornirvi supporto, potreste cortesemente indicare il common name che vi è stato assegnato nel momento in cui vi sono stati condivisi i certificati? Grazie.

**Comment by igcomsrl** [comment]
di seguito i dati richiesti  :
A1#111IGCOMSRLXXX
S1#111IGCOMSRLXXX

**Comment by vigliottim** [comment]
Buonasera, il common name fornito non è coerente con quello utilizzato nei token. 
Le chiediamo di correggere il campo _"iss"_ come indicato di seguito:

- _"iss": "integrity:S1#111IGCOMSRLXXX"_ (FSE-JWT-Signature)
- _"iss": "auth:S1#111IGCOMSRLXXX"_ (Authentication Bearer Token)

e riprovare. 
Grazie.

**Comment by igcomsrl** [comment]
Buonasera,
abbiamo rieseguito il test seguendo le vostre indicazioni ed usando un nuovo file ma otteniamo il seguente errore:
{
  "traceID": "90ffbe84475f4df2",
  "spanID": "90ffbe84475f4df2",
  "type": "/msg/jwt-validation",
  "title": "Campo token JWT non valido.",
  "detail": "JWT payload: Tipologia documento diversa dalla tipologia di CDA (code - codesystem)",
  "status": 403,
  "instance": "/jwt-document-type",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.10.4.4.7102.dac9e1b01f5e466584a0e83207291a98c34a78363d0f508858f10b78c9c90e18.e773ef305b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

ma nel CDA allegato al file è presente lo stesso tipo di documento:
dentro CDA: <code code="68604-8" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Referto Radiologico" />

mentre nel token abbiamo:
"resource_hl7_type": "(68604-8^^2.16.840.1.113883.6.1)"

il file usato è il seguente: 
[Test_referto.pdf](https://github.com/ministero-salute/it-fse-support/files/14013036/Test_referto.pdf)
mentre il token è il seguente:
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGYURDQ0ExQ2dBd0lCQWdJVUxiUFl4R2MzSjFPNDQ1d0JpbDJiNngrNDBVVXdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekExTVRZeU1UVTNNRGhhRncweU5qQTFNVFl5TVRVM01EZGFNR2t4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVIwd0d3WURWUVJoREJSRFJqcEpWQzB4TVRGSlIwTlBUVk5TVEZoWVdERWFNQmdHQTFVRUF3d1JVekVqTVRFeFNVZERUMDFUVWt4WVdGZ3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDajlYTnFZSHNDc2pIdjVWWXpqWWtDMEhlUzArNThNL1NlV1Frd2lNTHhwTXVOelgzTXhVazNGQ2lTNjRYbVl0cW80WlcyRWF0UmNrVUlVd0ZqbUZiMUUwMy9vR2FBWlEzUktQemlFM05ueHk0UHIrY3BnNUEwZTY1MUl1UkpFMGlvckVIZUxhQWtYdVlaMVlhdHlkQWhtaktCZHpPWURoS1hSdWg0OHBNUStuTmdTVEwvREdqRUJmMHNUZkw0R3VqTld2ZHA3Ym9ZQnVNbW9YeW51ZW5iTEJJNzR0YlR5NDk2UVN6bXBPaFpCTTF1MXpFSDJmOVRjdzVNTk1oVGVxS3ljRHRDT1pmVktQNGdyNitjaWZFa05GTWVNNWNmWURZaWFRbXhQT09DeXoyMXpxcld0ZTFzb3pVRkNtSVRDVnBVcmVScGVqNmRhU3ltdHRxRUNEdjdBZ01CQUFHamdnRVlNSUlCRkRBZkJnTlZIU01FR0RBV2dCUVdPYWthQlltM0R5MnlOZTNDQ1pyRkE0TWlQekFTQmdOVkhTQUVDekFKTUFjR0JTdE1IUUVMTUlHdEJnTlZIUjhFZ2FVd2dhSXdnWitnZ1p5Z2dabUdnWlpvZEhSd2N6b3ZMMk5oYzI5blpXbHpkbWxzTG5OdloyVnBMbWwwTDJWcVltTmhMM0IxWW14cFkzZGxZaTkzWldKa2FYTjBMMk5sY25Sa2FYTjBQMk50WkQxamNtd21hWE56ZFdWeVBVTk9KVE5FUTBFclRXbHVhWE4wWlhKdksyUmxiR3hoSzFOaGJIVjBaU3RVWlhOMEpUSkRUeVV6UkUxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVWxNa05ESlRORVNWUXdIUVlEVlIwT0JCWUVGUEhWbW9jRTk1ZFRFTmZRVmt2bDl2aHk1alJmTUE0R0ExVWREd0VCL3dRRUF3SUdRREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBZ0p4UlY1UEFadEZ3OFM5SXlFK2JmcVcrTVkvOHlCOTBtWE9hZ3FhN3VEeU9vVDlqT2RRUmw4bWhwN0tuNTNDMGJLeFVhc2Z0eXRzS0t6bnRia3pBakh4ZldtWlJvTFBtS2tyajNWazNWK3dIOGE5WTBRRHpPSFNYdDdHejJwUjZXTUphVzB4Wll1R0drSjFuTjlGaXgxTTBLMkZYVFdvTDY3bjBETGxCSEs2SlQ2WVdCTVArVnR6MkI0aVNrcW5FdFhLay9TU1h6MTNBQm5ObjR2NmJWaWUyRXk5Z1dVWkcxWFFJQ1gxY1Bnd0tybnM5UGZpQ3FpcElEOWJIeDRqZ2o5MTArZVBZODhPZ0NEWFhNdDhtMk9qS1RYb3JBZ0dvQVNONmRqQU9uYkNnbHNyU1A5WU1hemNtMnI1SFdneDFlcjZMbzFhODVUc1lJdWVEUFlWUG5ZWkRBM2R6dWYwS3VqUjVDdXVYRG9hYmU5Q25aaHFSdnE4UEd2RGJpa3I5eFlZUitOeWRiNDdpY2dGZXJ5bXQ3b09yWFk1cE50WjB4T1FKOExiL1ExSHJwYmpmcy8yYTJLSEdjSlhUc2JOL01WZEFGdTBtdmMvRlpSQzNDWG9KanFHWUdMNWZtMDg0ZFByTDNFa29RcTFkNklSajVnY1ZuSlZTc2w1Mk9KamRVS3dBWkxlN2toMm1GMTZkSUpidmRhMGRUNCtkVFlOVFFxMFpsYnFoWXZaYjNTNEJVaTkwSE04b3g1U3pkT1ZkUFNRc2g3Qk84Qjl3VzdYQ0ZqNWk5dlhvR2N3MzY5T01yajJVYkJjRjVSUmYvR1k3S3hTTDQ0QXZYeldsUmJOUXhlOXVDcENSdFkzSmRuNWUyZE51OVdZTmJQZUhNTEM0MHIzUXlwT3R5Ujg9Il19.eyJleHAiOjE3MDYwMjgwNDEsImlhdCI6MTcwNTk0MTY0MCwiaXNzIjoiaW50ZWdyaXR5OlMxIzExMUlHQ09NU1JMWFhYIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwianRpIjoiOTY5YmM4MzAtM2E2ZS00ODBmLWEwZWItYzZhODg4MTZiNjhmIiwic3ViIjoiRFRTRFRSNzBBMjBINTAxSl5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIiwic3ViamVjdF9vcmdhbml6YXRpb25faWQiOiIxMjAiLCJzdWJqZWN0X29yZ2FuaXphdGlvbiI6IlJlZ2lvbmUgTGF6aW8iLCJsb2NhbGl0eSI6IjEyMDIwNSIsInN1YmplY3Rfcm9sZSI6IkFBUyIsInBlcnNvbl9pZCI6IkRUU0RUUjcwQTIwSDUwMUpeXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyIsInBhdGllbnRfY29uc2VudCI6dHJ1ZSwicHVycG9zZV9vZl91c2UiOiJUUkVBVE1FTlQiLCJhY3Rpb25faWQiOiJDUkVBVEUiLCJyZXNvdXJjZV9obDdfdHlwZSI6Iig2ODYwNC04Xl4yLjE2Ljg0MC4xLjExMzg4My42LjEpIiwiYXR0YWNobWVudF9oYXNoIjoiIiwic3ViamVjdF9hcHBsaWNhdGlvbl9pZCI6IklHU1VJVEUiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlbmRvciI6IklHQ09NIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiNC4wIn0.UtsDO2TQ6xVala3cXfkxlkF7lF97wba8Z8Fhe4bqLVqY4_EjQMcwb9f9WfwVEjqfLh9NbRxqqJdY7naDCnUvRiQG5vXHfEInkLg_nQDznln9QN_DyzgOQsxXWks1Ff3OQCkhdMbwavkWR6nH6_xDNGyV-2TJMOuGuj8PaJa4j2ASZzeVxigG0e8N4nJh7Gslzgg3KVLIhoZ_0CT9ichtMRxN80L9yqZu8fI5mjBSkpwgvfFI_x_9Ls9IcqHUqv5uhp8iu0jjtmtw810KR6et5symktuEQxfLQSVdpVZz_Mochu4RS4Lb-CSnDuosCwGEmH4T-UGB3S0RiXaLcrve9A

**Comment by vigliottim** [comment]
Buonasera, in virtù del commento postato probabilmente per errore nel thread https://github.com/ministero-salute/it-fse-support/issues/570:
<img width="683" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/e08af64d-5a63-407d-a159-25cd5bdfeb40">
presumiamo che l'anomalia sia stata risolta aggiungendo gli apici al campo _resource_hl7_type_.
Pertanto, chiudiamo il presente ticket e rimaniamo a disposizione per ulteriori richieste di supporto.
