### ISSUE TITLE
Mancato accreditamento A1#111GRUPPOGPI00 - TESI_SPA - ENDOXWEB - 25.0 - Test 32 e 40

### ISSUE THREAD

**Issue by filippo-tesi** [ministero-salute/it-fse-support#573]
Buongiorno abbiamo ricevuto in data 22/01/24 la seguente mail:

Salve,
Con la presente si comunica il mancato superamento dei seguenti test [40, 32] per il servizio [validazione/pubblicazione] del Fornitore [A1#111GRUPPOGPI00] - Vendor:[TESI_SPA] - ID: [ENDOXWEB] - Version: [25.0] - Sha: [b3cf280089d3bad6e7d152fa8750f1d3c6cd9fd7] in data odierna.
Saluti,
Il Team FSE 2.0

Allego errors.json ricevuto:

[errors_20240122.json](https://github.com/ministero-salute/it-fse-support/files/14019852/errors_20240122.json)

Nel file errors.json, per tutti i n. 2 test oggetto della segnalazione, l'errore è il seguente:
"Test KO non superato. Assicurarsi che il traceId fornito abbia restituito in fase di validazione un errore bloccante."

Ho verificato le varie transazioni eseguite durante i test, e i traceId riportati nella checklist e nel data.jason corrispondono a quelli ricevuti da Gateway.

Risposta ricevuta da GW per il **test 32**  ("timestamp" : "2024-01-18T09:27:08.548Z) :

{
  "traceID" : "16f852b1fe511be3",
  "spanID" : "16f852b1fe511be3",
  "type" : "/msg/jwt-validation",
  "title" : "Campo token JWT non valido.",
  "detail" : "Il campo purpose_of_use non Ã¨ valorizzato",
  "status" : 403,
  "instance" : "/jwt-mandatory-field-missing",
  "workflowInstanceId" : "UNKNOWN_WORKFLOW_ID"
}

Risposta ricevuta da GW per il **test 40** ( "timestamp" : "2024-01-18T09:29:02.023Z" ):

{
  "traceID" : "728558af440259b3",
  "spanID" : "728558af440259b3",
  "type" : "/msg/jwt-validation",
  "title" : "Campo token JWT non valido.",
  "detail" : "Il campo action_id non Ã¨ corretto",
  "status" : 403,
  "instance" : "/jwt-mandatory-field-malformed",
  "workflowInstanceId" : "UNKNOWN_WORKFLOW_ID"
}

Avevo già ripetuto questi e altri due test per lo stesso errore, che poi era dovuto ad un vs problema tecnico, vedi issue #564 dove mi avete risposto:

"_Buongiorno, a causa di un problema tecnico ora risolto, è necessario ripetere le chiamate identificate dagli id per cui è stato segnalato l'errore "TEST_KO_NON_SUPERATO" ed effettuare una nuova PR con le dovute correzioni.
La ringraziamo per la collaborazione e ci scusiamo per l'inconveniente. Siamo a disposizione per ulteriori richieste di chiarimento._"

Devo quindi ripetere nuovamente i test 32 e 40 ???

Restando in attesa di vs gentile riscontro, porgo cordiali saluti.
Filippo Gatto

**Comment by filippo-tesi** [comment]
Buongiorno, ho fatto alcune verifiche e mi sono accorto che le chiamate di validazione per i test case 32-40-160-161 erano state fatte con l'applicatiionID errato ("OPTINET" invece che "ENDOXWEB"), ecco perchè non le trovavate. Ho appena ripetuto i n. 4 test ed eseguito il commit "**A1#111GRUPPOGPI00-TESI_SPA-ENDOXWEB-25.0 - Ripetuti Test 32-40-160-161**"
https://github.com/ministero-salute/it-fse-accreditamento/commit/d87f2754f2f9594e0f8bb9bac58e6d7434422ce4

che trovate dentro alla PR #1156

Restando in attesa di vs gentile riscontro, porgo cordiali saluti.
FG

**Comment by vigliottim** [comment]
Buongiorno,
la ringraziamo per il suo feedback.
Chiudiamo il presente ticket e la invitiamo a riaprirlo nel caso in cui il problema dovesse ripresentarsi.
Restiamo a disposizione per ulteriori richieste di supporto.
