### ISSUE TITLE
Referto Radiologia CASO DI TEST 6  

### ISSUE THREAD

**Issue by igcomsrl** [ministero-salute/it-fse-support#574]
Buongiorno, stiamo cercando di eseguire il test case 6 KO (id 76) per i referti RADDIOLOGIA,

nel documento "Casi di test RAD.docx" viene riportato:
"CASO DI TEST 6 
Durante la fase di compilazione dei dati anagrafici dell’assistito, il test case riguarda la generazione di **un errore semantico** scatenato dell’inserimento nel campo relativo al CF di un codice con caratteri minuscoli.  
"
noi abbiamo eseguito i test in  2 modi:

modo 1:
 come richiesto nel CDA di test abbiamo inserito come codice fiscale del paziente il valore : DTspnT827h501z anziché DTSPNT85B27H501Z
se nel Token inseriamo  in person_id il valore errato otteniamo il seguente errore:
_"Il codice fiscale nel campo person_id non è corretto"_

modo 2: 
  sempre nel CDA di test abbiamo inserito come codice fiscale del paziente il valore : DTspnT827h501z anziché DTSPNT85B27H501Z

e nel  campo person_id  per la generazione del Token  inseriamo il valore corretto, otteniamo il seguente errore:
_"JWT payload: Person id presente nel JWT differente dal codice fiscale del paziente previsto sul CDA"_.

Per il test case in oggetto quale dei 2 casi dobbiamo applicare?

**Comment by LucaRogledi** [comment]
Buongiorno,
Per la corretta esecuzione del caso di test 6, la invitiamo a:

- Inserire lo stesso codice fiscale sia all'interno del cda che del campo "person_id" nel token.

- Utilizzare un codice fiscale valido contenente almeno un carattere minuscolo.

Restiamo a disposizione in caso fosse necessario ulteriore supporto.
Grazie

**Comment by igcomsrl** [comment]
Abbiamo rieseguito il test inserendo sia nel campo person_id che nel cda il valore "DTspnT85B27h501Z"


ed otteniamo l'errore:"[Errore-46| codice fiscale 'DTspnT85B27h501Z' cittadino ed operatore: 16 cifre [A-Z0-9]{16}]"

penso che possiamo considerare che l'esito è quello atteso, giusto?

**Comment by LucaRogledi** [comment]
Si, confermiamo che è l'esito atteso.
Procediamo alla chiusura della issue e restiamo a disposizione in caso di ulteriori chiarimenti.
Grazie
