### ISSUE TITLE
TypeCode da utilizzare per i documenti di screening

### ISSUE THREAD

**Issue by angeloceloni** [ministero-salute/it-fse-support#576]
Buongiorno,
in Regione Umbria stiamo attivando l'acquisizione dei documenti di screening per il momento come semplici PDF in modalità FSE1.0 in attesa della definizione dei CDA2. I documenti che inizieremo ad acquisire sono le lettere di invito e le lettere di risposta.
Ci servirebbe supporto per l'individuazione del corretto typeCode per i due tipi di documento indicati:
per le lettere di invito, possiamo utilizzare 101134-5 (Promemoria di appuntamento)?
per le lettere di risposta non ci sembra che sia già stato definito il typeCode da utilizzare, è possibile definire il codice in modo da iniziare l'indicizzazione nel modo corretto?

**Comment by IStacchiotti** [comment]
Buondì @angeloceloni, grazie mille per la segnalazione. Per l'invio dei documenti di screening (lettere di invito e di risposta) sia fascicolo 1.0 che al 2.0, dovrebbe aspettare che queste specifiche tipologie di documento siano introdotte tra quelle gestite. La invitiamo a monitorare il canale #fse su Slack per eventuali aggiornamenti in merito. Chiudiamo il presente, ma rimaniamo a disposizione per ulteriori richieste di supporto, grazie.
