### ISSUE TITLE
Accreditamento soluzione CCE Cartella Clinica Elettronica

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#577]
Buongiorno,
volevamo notificare il caricamento completato dei test case per la soluzione CCE Cartella Clinica Elettronica :

https://github.com/ministero-salute/it-fse-accreditamento/pull/1133

questa pull request contiene LDO,RSA.

Grazie

**Comment by vigliottim** [comment]
Buon pomeriggio,
le confermiamo che la pull request è stata presa in carico, procediamo pertanto alla chiusura della presente issue.
Ricevera l'esito delle verifiche via email.
Restiamo a disposizione per ulteriore supporto.
Grazie.
