### ISSUE TITLE
Campo "administrativeRequest" ripetibile

### ISSUE THREAD

**Issue by daniele-gubellini** [ministero-salute/it-fse-support#579]
In affinity 2.5 è stato reso ripetibile il campo administrativeRequest. 
Le specifiche di integrazione del GTW fanno ancora riferimento alle specifiche 2.4.1: qual è la sintassi da usare per indicare più valori?

Grazie

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri procediamo alla chiusura del presente ticket. 
Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto.
Grazie.
