### ISSUE TITLE
certificato di test per generare il token?

### ISSUE THREAD

**Issue by nturri1306** [ministero-salute/it-fse-support#58]
salve volevo sapere se esistono dei certificati di test da utilizzare con il gateway di test https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1 per fare delle prove prima della fase ufficiale di accreditamento

**Comment by Ser-ena** [comment]
Buonasera, è necessario richiedere i certificati di test mediante email all’indirizzo fse_support@sogei.it.
