### ISSUE TITLE
Accreditamento nuovo software 

### ISSUE THREAD

**Issue by ZucchettiCentroSistemi** [ministero-salute/it-fse-support#580]
Buongiorno,
siamo la Zucchetti Centro Sistema s.p.a e abbiamo già accreditato il software JLAB v.9.0 per il referto di Laboratorio.
Abbiamo la necessità di accreditare un altro software per i centri Trasfusionali, volevamo sapere se dovevamo procedere alla compilazione del modulo di richiesta di accreditamento generando nuovi certificati di autorizzazione e firma o possiamo utilizzare i certificati già utilizzati per il sw precedentemente accreditato.

**Comment by vigliottim** [comment]
Buongiorno, è possibile utilizzare i certificati utilizzati per il software già accreditato ma è necessario procedere alla compilazione del modulo di richiesta di accreditamento (EuSurvey) per richiedere l'accreditamento di un nuovo software. Restiamo a disposizione per ulteriori chiarimenti. Grazie.

**Comment by ZucchettiCentroSistemi** [comment]
Buongiorno,

grazie per la spiegazione. 
Necessitiamo di un ulteriore chiarimento, abbiamo compilato il form per la richiesta di accreditamento, inserendo i vari campi richiesti.
Il nuovo software, per il quale stiamo effettuando la nuova richiesta di accreditamento, si occupa di centri Trasfusionali.
Però, alla voce "Tipo di documento:", non c'è quella corrispettiva al referto Trasfusionale. Però esistono i test-case, per tale referto (https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/9-Trasfusionale).
Al momento la richiesta è stata fatta, selezionando la voce "Referto di Medicina di Laboratorio".
Abbiamo commesso qualche errore?

Grazie per la collaborazione

**Comment by vigliottim** [comment]
Buongiorno, le confermiamo che nel caso di referti trasfusionali è corretto indicare "Referto di Medicina di Laboratorio" come tipo di documento. Non esiti a contattarci per altri dubbi. Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente issue viene chiusa come risolta. 
Si può procedere alla riapertura nel caso avesse bisogno di ulteriore supporto. Grazie.
