### ISSUE TITLE
Struttura utente - Locality

### ISSUE THREAD

**Issue by marcodevanna** [ministero-salute/it-fse-support#581]
Buongiorno,
nelle specifiche del gateway, il campo Struttura Utente (locality) è definito come segue:
"_Identificativo della struttura utente.
Codifica ISTAT della Azienda (ASL) concatenato alla codifica HSP.11 - HSP.11bis - STS.11 - RIA.11. \ Nel caso di ruolo APR assume il valore del codice ISTAT dell’Azienda (ASL)
Le codifiche saranno ampliate per coprire tutte le casistiche mancanti.
Riferimento: urn:oasis:names:tc:xspa:1.0:environment:locality_"

L'analogo campo nell'Affinity Domain è così definito:
"_Codifica HSP.11, HSP.11bis, STS.11, RIA.11 ovvero codifica ISTAT della Azienda (ASL) o codifica Tabella 6.4-3_"

In un caso si parla di codice AUSL concatenato al codice del presidio o della struttura, nell'altro, sembra che i valori siano alternativi. Poichè si tratta evidentemente della stessa informazione, quale è il formato esatto atteso?

Inoltre, nel caso di documenti prodotti in Azienda Ospedaliera, è sempre da inserire il codice AUSL territoriale di riferimento? 

Grazie.

**Comment by marsardit** [comment]
Buongiorno,
mi associo alla segnalazione. 
In accordo alla definizione, l'attributo locality dovrebbe essere valorizzato concatenando l'OID del catalogo specifico alla rispettiva codifica della struttura. Segnalo che bisognerebbe allineare anche l'elenco dei cataloghi in affinity domain: HSP.11 - HSP.11bis - STS.11 - RIA.11, ma anche FLS.11 (per le Aziende Sanitarie) e UNI per le strutture trasfusionali.
Se valesse la definizione data nelle specifiche Gateway: come si dovrebbe valorizzare la locality per una struttura privata autorizzata (ma non accreditata) che come si sa non afferiscono a nessuna ASL?
Grazie

**Comment by vigliottim** [comment]
Buonasera,
come comunicato sul canale Slack dedicato, è stato rilasciato un nuovo aggiornamento che riguarda il claim _locality_.
La invitiamo a consultare le specifiche aggiornate in documentazione al link:
https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt
Rimaniamo a disposizione per chiarimenti.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Potrà riaprila nel caso le servisse ulteriore supporto.
Grazie.

**Comment by mariogoodbread** [comment]
Buongiorno, quando è previsto il passaggio in produzione per questa modifica?

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso fosse necessario ulteriore supporto. Grazie.

**Comment by mariogoodbread** [comment]
Buongiorno,
devo effettuare una fix sulla componente in produzione che si interfaccia con il FSE, ma non mi è chiaro come testarla, dato che nell'ambiente di test è stata rilasciata la versione che richiede la nuova impostazione del campo Locality.
Esiste un ambiente di test con la versione del software FSE attualmente presente in produzione?

**Comment by LucaRogledi** [comment]
Buongiorno, per le richieste riguardanti FSE 1.0 le chiediamo di inoltrare la sua richiesta alla seguente mail: gestionets@sogei.it. Grazie
