### ISSUE TITLE
UNKNOWN_WORKFLOW_ID

### ISSUE THREAD

**Issue by igcomsrl** [ministero-salute/it-fse-support#582]
Buongiorno, nei diversi test case relativi a "VALIDAZIONE_TOKEN_JWT_CAMPO_XXX_KO" e "VALIDAZIONE_TOKEN_JWT_XXX_KO" otteniamo nella risposta un "workFlowIstanceId" con il valore "UNKNOWN_WORKFLOW_ID", è corretto?
quindi Sia in data.json che nel file Excel come valore ineriremo questo valore?
Grazie

**Comment by vigliottim** [comment]
Buongiorno, in questo caso dovrà riempire la colonna _WORKFLOWINSTANCEID_ del file excel _report-checklist_ e i campi _workflowInstanceId_ del _data.json_ con _UNKNOWN_WORKFLOW_ID_. 
Restiamo a disposizione per ulteriori chiarimenti.

**Comment by igcomsrl** [comment]
ok, perfetto, Grazie mille

**Comment by vigliottim** [comment]
Grazie a lei. Procediamo alla chiusura della presente issue e rimaniamo a disposizione per ulteriori richieste di supporto.
