### ISSUE TITLE
Errore in eliminazione documento: 404 - Document cannot be found on the Server FHIR

### ISSUE THREAD

**Issue by davidecasiraghi** [ministero-salute/it-fse-support#583]
Buongiorno,
ogni volta che tentiamo chiamare il servizio di eliminazione di un documento riscontriamo l'errore "Document cannot be found on the Server FHIR".
Abbiamo verificato la correttezza degli id e lo stato di pubblicazione del documento da eliminare ma ci sembra tutto corretto.

Riporto uno dei nostri tentativi come esempio:

1. Chiamata alla api validation-and-create per pubblicare il documento:

REQUEST BODY
{
"assettoOrganizzativo":"AD_PSC008",
"healthDataFormat":"CDA",
"identificativoDoc":"2.16.840.1.113883.2.9.2.120.4.4^BCS.2710.2710_10_2024000008_0",
"identificativoRep":"2.16.840.1.113883.2.9.2.120.4.5.1234",
"identificativoSottomissione":"2.16.840.1.113883.2.9.2.120.4.3.d5c53781-4397-4ba6-8cfd-5089195dea5f",
"mode":"ATTACHMENT",
"tipoAttivitaClinica":"ERP",
"tipoDocumentoLivAlto":"REF",
"tipologiaStruttura":"Ospedale"
}

RESPONSE OK:
{
"traceID":"982918989e98c85e",
"spanID":"982918989e98c85e",
"workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.52a5eb0a91c680b89a169452c23abb4861e0f08667c8a97194c2156dbccdcade.9704e5d39a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

2. verifica dello stato di pubblicazione
{
    "traceID": "792dd1dca4d69a92",
    "spanID": "f2f192f6f53e2742",
    "transactionData": [
        {
            "eventType": "VALIDATION_FOR_PUBLICATION",
            "eventDate": "2024-01-26T10:34:03.694+00:00",
            "eventStatus": "SUCCESS",
            "subject": "VDSTTO68M08F205Z^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "120",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.52a5eb0a91c680b89a169452c23abb4861e0f08667c8a97194c2156dbccdcade.9704e5d39a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "982918989e98c85e",
            "issuer": "integrity:S1#111BCSSRL00000",
            "expiringDate": "2025-01-25T10:34:03.704+00:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-01-26T10:34:05.594+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.120.4.4^BCS.2710.2710_10_2024000008_0",
            "subject": "VDSTTO68M08F205Z^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "ERP",
            "organizzazione": "120",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.52a5eb0a91c680b89a169452c23abb4861e0f08667c8a97194c2156dbccdcade.9704e5d39a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "982918989e98c85e",
            "issuer": "integrity:S1#111BCSSRL00000",
            "expiringDate": "2025-01-25T10:34:05.604+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-01-26T10:34:05.684+00:00",
            "eventStatus": "SUCCESS",
            "message": "{\"esito\":true,\"errorMessage\":\"Regime di mock abilitato\",\"traceID\":\"991088ea25367543\",\"spanID\":\"991088ea25367543\"}",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.52a5eb0a91c680b89a169452c23abb4861e0f08667c8a97194c2156dbccdcade.9704e5d39a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-01-25T10:34:05.693+00:00"
        },
        {
            "eventType": "SEND_TO_EDS",
            "eventDate": "2024-01-26T10:34:05.775+00:00",
            "eventStatus": "SUCCESS",
            "message": "{\"esito\":true}",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.52a5eb0a91c680b89a169452c23abb4861e0f08667c8a97194c2156dbccdcade.9704e5d39a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-01-25T10:34:05.784+00:00"
        }
    ]
}

3. Eliminazione del documento:
DELETE  https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.120.4.4%5eBCS.2710.2710_10_2024000008_0

RESPONSE: 
{
    "traceID": "2cd69a61f538eea0",
    "spanID": "2cd69a61f538eea0",
    "type": "/msg/eds-error",
    "title": "Eds error.",
    "detail": "Document cannot be found on the Server FHIR",
    "status": 404,
    "instance": "/msg/eds-document-missing"
}

Grazie e saluti

**Comment by LucaRogledi** [comment]
Buonasera,
Abbiamo verificato che l'encoding del carattere  "^" dovrebbe essere generato in maiuscolo "%5E", questo potrebbe aver determinato il mancato riconoscimento del documento da eliminare.
Pertanto la invitiamo gentilmente a riprovare dopo la seguente modifica all'interno dell'URL:

**AS-IS:**
2.16.840.1.113883.2.9.2.120.4.4%5**e**BCS.2710.2710_10_2024000008_0

**TO-BE:**
2.16.840.1.113883.2.9.2.120.4.4%5**E**BCS.2710.2710_10_2024000008_0

Restiamo a disposizione per ulteriore supporto.
Grazie

**Comment by davidecasiraghi** [comment]
Buongiorno,
abbiamo riprovato mettendo %5E al posto di %5e ma abbiamo lo stesso errore:

DELETE https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.120.4.4%5EBCS.2710.2710_10_2024000008_0

{
    "traceID": "4556df2faa361aed",
    "spanID": "4556df2faa361aed",
    "type": "/msg/eds-error",
    "title": "Eds error.",
    "detail": "Document cannot be found on the Server FHIR",
    "status": 404,
    "instance": "/msg/eds-document-missing"
}

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
dalle analisi effettuate sui log della vostra chiamata le confermiamo che il file pubblicato è stato referenziato correttamente.
In seguito ad alcuni test effettuati, ci risulta che il servizio di eliminazione funziona correttamente. 
La invitiamo a riprovare chiamando prima il servizio di validate-and-create e, una volta terminata la parte asincrona, chiamando il servizio di eliminazione una sola volta (l'errore segnalato infatto può essere originato in caso di eliminazioni consecutive oppure in seguito ad una sostituzione e successiva eliminazione del sostituito).
Restiamo a disposizione in caso l'errore dovesse persistere.
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, 
non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. La invitiamo cortesemente a riaprirla in caso il problema dovesse ripresentarsi o fosse necessario ulteriore supporto.
Grazie.
