### ISSUE TITLE
Mancato accreditamento A1#111080XXXXXXXX - Lepida - Lepida_CVPI - 1.0.0

### ISSUE THREAD

**Issue by Axloide** [ministero-salute/it-fse-support#584]
Buongiorno,
abbiamo appena ricevuto la notifica per il mancato superamento dei test [22, 23, 20, 21] (in pratica 4 su 5 dei test OK).

Abbiamo verificato la composizione del CDA e risultano rispettare i parametri richiesti dai test e anche i campi che nel file di report vengono dichiarati assenti in realtà sono presenti.

Potete verificare?
Allego errors.json ricevuto per mail: [errors.json](https://github.com/ministero-salute/it-fse-support/files/14082376/errors.json)

Grazie

**Comment by IStacchiotti** [comment]
Buongiorno @Axloide, gli errori in questione sembrerebbero riconducibili alla mancanza dell'ID della section:

**AS IS**:
`<section classCode="DOCSECT" moodCode="EVN">`

**TO BE**:
`<section ID="Singola_Vaccinazione" classCode="DOCSECT" moodCode="EVN">`

Vi invitiamo pertanto ad aprire una nuova pr per sottomettere le modifiche necessarie. Inoltre, nel caso possa esservi utile, vi segnaliamo che è disponibile a questo [link ](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/gtw-certifier)il tool "gwt-certifier", che consente di riprodurre in locale le verifiche dei test case di validazione OK eseguiti durante la fase di accreditamento.
Rimaniamo a disposizione per ulteriori richieste di supporto, grazie
