### ISSUE TITLE
Errore "Impossibile creare un canale sicuro SSL/TLS" in fase test validazione 

### ISSUE THREAD

**Issue by penny66** [ministero-salute/it-fse-support#586]
Buongiorno,
stiamo testando il metodo di validazione verso il gateway e volevo chiedere un supporto perchè in tutti i nostri tentativi abbiamo questo errore: "WebException: Richiesta annullata: Impossibile creare un canale sicuro SSL/TLS". 

Token di autorizzazione:
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJpZkNoaWF2ZSIsIng1YyI6Ik1JSUwvd0lCQXpDQ0M3VUdDU3FHU0liM0RRRUhBYUNDQzZZRWdndWlNSUlMbmpDQ0JoSUdDU3FHU0liM0RRRUhCcUNDQmdNd2dnWC9BZ0VBTUlJRitBWUpLb1pJaHZjTkFRY0JNRmNHQ1NxR1NJYjNEUUVGRFRCS01Da0dDU3FHU0liM0RRRUZEREFjQkFqVXI3czVaVkpDY3dJQ0NBQXdEQVlJS29aSWh2Y05BZ2tGQURBZEJnbGdoa2dCWlFNRUFTb0VFSU1JTG9tYmlKeFpQbkRyV3Nmdkc4aUFnZ1dRaDROUk5xOTJvQkhmbUV4NmpLQXVDNVNNaHJ0SlI1VHJkOTVhSUErc1p6eDIyWUh0aG5ybXIranZpT0wzU2JtKzRpMUlsSjY0NU9QMzAxQlltcGJrdlJDTjZ6dW1HZitnZmpqbitaV1hRQ2pYUjQrN2MwQlhKQ1VxRXJlR0JvWHMwem1acXVLU0NKcE1jNmNSWnh2MjVqdWpGdjZVWEpuTUVldkZQQ0RKWGdsMzlWWUVudjRTQUJ0V0RSNFFqRzRabGFLU1J2Wit6a3JsajMyODZXaEwzQmR3V3d0TjhCcjUyd1pUVWZLU3dkUFBvK01ibFVlRG9iYURPNFZvTEY3dHFnOThoNzg2QnlCL2F0R0hkQVQvRGl6T211dnA3OGpHUENGSFlVbzdodWNJWnZNQkd1SjMyYnhmbGFLdkIwT2ZjS2tEOGtQMG9wRUg4dExOTHlGa0s3cTA1S2d4U1lsSGlraWVUU0xZdjViTVRvZnFXeDNxaDFLY3Z1WEo3OWRrcW15MlJaaVBNUkpUMUIzcXhRZDVvUHVWZ3FXRHMxWmJTMWpsWklnNEQvZWFPeFRIVzltT3FDd2ZuZzA4SDRobWNRaUcwNjhoU1N1NzZpWlJyVlFScU85aU9qVjNYeDBBbVptQXlkY2N6c3RHTG9VcmNqYnN2RURHaXZvTmVSVEFNM2cvdTdFMXZqd2g0YTRaVDJjY0Vrei9yc0szTjM1SitUTHhaRkZicHB6ZnVsR2pWQXd1amMxV1BKYm05b3R5cExtNDdWZlBrYkdodmZGcWc1N3dVUmRYL2xjWkl5aFk0WTV0QmQzaEo0NXdkSHo2aGthN29PSGozT3dRSGg3YzdzZ2tpbVl3NTlwUVBOT1ZPY21jZHJiYW5vN25ubVFQNnFNQ1B0MThpcHVZQXdZYVFiUHZvcXdLMW5scndjektUUUltTkUxRGlTMUdnbjBpS1ZsNmdYMWJhWWtKLzNMM1hBcVZQYlA3R3VDUnFtNCswWE01OXRkUGR5UXNTdlpjcE9qR0pqL01KNVN4L3ZERmVZVUEyeEdyam9QRGlXczh3cW8yNXI3NExtdnNadmN1aWlZMmdDVFJrM0hQejB1SWdNTDFsTlJqMWhkYnJHczQ1QjNJa0VtWkdjK0VDeG5hdjF1bzdLRkc4V09qbTIzMG9RNjkxZ0tUcFJicVhQV0VVZWc2NStxcjJERnVwaHpLZ2lZNFkzZGlSa1pkRFJDWVhXbXg0dkd6Y1pxMWdFbk9wYXVHVEkrMFl2amZ1S3Y5clp4cHBKNXlGQ2h6TG51b2llYW1PTjY5R1BWWEkxckgyTm1VU0xnMERjdCtzaElvMFpwdjJqd2R4V3g1QXFUSlRScFdtM2FJS1Y5N2NTd3c3NHdlZ1Y1Y2FremNTSS9LRkxTZFV2Yk5SRzBNRHViSXp4QmczUmNyWCtNalJaSDhzSUhxSnNWS3hldm10Nk5KZ1p5b0crUUl2MFp2YVp3eVhxYUdoZkoyYjNFVDh1U3Q3dEh5dUNRdTFDRDlZa0RXYTd2V09Nc3Y2UnJFWXdSMnh2c0Z3ZmVIN1hGU1Z0RG9td3hnais2SStvTnBmdE5XajBlYlR2dGlYaGw3cUpGNG40aTlCdW4zVVRzWDZUTDg3Y1c3MDFvd2ZmLytWaWt4S1dPOWZIL2NxbmRBWjRMSXhpaU1NdTJ1QnArbWVNVk9mNVhvY2hsTnFkdlZkZEZidlhmV1p6ZTUxU1BjM3VnNzU3UkVDMUw5SGZmbXRiVG1mRjdoRDArRitnMkx3Y1FTYlg2bDcweFVaYTd2OFN3U3NUNGlpYkRJcGRndEVSWUphNlZPaXhWYVl3Y0JJZEpGaHh4ajFyWXZibnphTEkzTk90NGhHNkdrcDUyYkd1Z1dNK01URDJ4Vm03Sk56MVJSdnRXVUNlL1JjTVMyN1lIa05jY0pNcXJtZFl6cE9ROTRSK1BYWW5oaFA2bnUwUUJMYmxEVDdkNW9wQk5vUlBvK3kzTVZ5aWhTRFI5aDBzaG80ejMzTHVMUW02MFhTckZ2MHZtczJRcUdJLytabG9lWG5ycnR0eDVTbW85UCttRzdtOVVOWkZCR09nVHcrS1FjV1VvaVBnSXFyWDlGdndEa1dySi9yTHlhYW16T2pFZmhRWTQyN3RDWUdLTFpQTDJoand5RlVxYmMyZFQ5Um9LMnM5cWdORjdOY2EwbGIwbncwNXhmWmhoTmYrbzg1Y1ZWRU9Rek01R2cvQ2s3eHN6TkNkNzZCQmhFdk1PZHUvMFpkVDNYRno4RW55VVk4WUJoeW9tVUJQZjAzeVQ1ckQ5cUVsa0tKV0JiNVpZbkFUU0xYR3IwUERpM3JQZGZFclNBRXNHdlNlMjlrZHFSMjJjdXVDN1UyTk9meWZ0Ti9pY3hnSXNORmlyZ1NjYTg2UnN3ZDMvcitvWG9UYTRRalBqYzBTaTVSdE1Cd0FCemRmaUFiblVJM0poRWJqQXpRQ0p2ZmZhYmhHQTlwKzJlMlZXcVZFNEJJdmV5RS9Zd2dnV0VCZ2txaGtpRzl3MEJCd0dnZ2dWMUJJSUZjVENDQlcwd2dnVnBCZ3NxaGtpRzl3MEJEQW9CQXFDQ0JURXdnZ1V0TUZjR0NTcUdTSWIzRFFFRkRUQktNQ2tHQ1NxR1NJYjNEUUVGRERBY0JBaVU2WmNCMWZ1WUxBSUNDQUF3REFZSUtvWklodmNOQWdrRkFEQWRCZ2xnaGtnQlpRTUVBU29FRVBQcExjaFVza3hRdDJPMmRydDZFM2NFZ2dUUTgyUnYxa3E1aVNoYmNaTVFQaGNibnJtV1Y4S3gxOXRZTWVIcFkwTFJxVC9hUU9iU0c3eHpYbkM1blExN0NqS2FaV2k3YnJzNmY2dzJEUnNWWUIrakJoNmkxR2ZtelZPOGFPazlCVm51UytDaFEyZUVyMjl0U1ZqY29Ua2pSL1FxWXlreFJFSUpMdEtUM0QzVVZLcXNKajIvMTQxTmJ6aG9UdHlKb2UxSDRBT1dhbjh2KytQdWZERFd4enBBczQ0MUtZT2wyMWdsN0V6aVRXOWJMaXFnZzBNQmNoa09ZQ2xzeldpbzQ1a09yRWN5akdkRy85T0t5ZUkrOVBQem1MOHRUVFhiNGRldjhXTGxIR3RpU2UwMStObnpsMUthdU5JMjNBaU11MVBML25LRWg0T2MzR09RbkJMaDE4Z0FtWTBMTUtvbjFmeExBWmt3Nm0vWFd0ajZaaTBMREpIZzJPeWh0dCtPcmRsSmszcFFmODlJZmFZeGVjVmhMNU5oWjNqWEtJTTJqb1VFNlhFbU82U0VuSlhPN1ZLUm1rV3VSQlNsbUo2Mlc3VFIrVjZzZEJmbVRqVWYxUWNMSzBCbnFXQnBRekFDZzBEWGhEZmFnN2kydnJqSlVGN25wY0xYY1lBMkpKZVpHb2ExUUlTOEJQRmgyRGZPYVNmSVlVL1RxS2dWRk5iWXhRL1pUZDMwTjdHS2laVXo1U1JISmYzQ2MvY2dPT0Z4T2hka1llMVFWS0RhQXU2cFFUbmZ5eHdWd1lQM2M4NHJvdkx5VWdIK3F2VDFjcFByRUc1eWtTUGRBRm53R0J1anNvSWZXdFNBeTEwRWk3VWZUZkQxWXFIOXBmd0lzNVIzZVN3d3I4cnhTS0U5VzhVOW1HcDNFVHNuQ3NIT1ZyK05PVlNWOGdpeHhnaGxwUEtUVTY1eHExUDJFWjNxYmJBM1R5dExsRThyQnBTMG1ncHpvQmllczZJRmxHdWg1UENIVmRyVUFvTk4zZndoWmc2ZkxwRzhScDBibnRZSk1TZ295QTFwWmYvaTliUWgwdlB3Z0ZiZVpUMGYwSnpXN1lwRzdEN3QzUEEraTByMVRhNVAvOVoxY29EdE0xSUdXZzFaOXZKMXJxd3VtWFZPclBRekNBNmVKazJhWllqWVRkWWFPUlZtR2FPaW1kSjdXM1RXajYwOFlOeXJOSDc2aVZDR0JjQWRpVW5XcElvKzRmR1VlTHNYQndXNVg2V1JsWEM0dkM4cGs1bFFvZEg5Nm1Qd2lQQTd3N0pSamIrd2FvWE5KSWs5MXQ4RGV2UlNDSFNQdHVURnRNdjdnN2I2Zm1lWTJsK3RVU0NDM0hsbDUybVlsTkdnNEZHMThDWGFVQ1R4U09lcnFRa1RRM3plcWJJcXc4V3pvMHFyeHNEcmUzNDFmc2x5a3pITHJCSDg3S3EzQTdIZ0ZhTktqT1cyRy9idjdsMms3aHU2RE12VkhJWGlIbkc4REd3eDVDVG02Smc1cTlDU0l3M3gvL3NPUE1zRkVNcUFDbEE4em9hck8zSHRUOUFmc0EwblhpbnRpbytjZVRFZ0U4VnhVL0VRZTF0bGVlb2ZHWVF3T0xqTHpMMGFubXY3cWM2R0lmQm5MTCtLTEI3Qm9HclVocXVJNUNBRjIxL1RKQks3YzdGOHFYdGdqblJSNDJocmVrN3hNbFhhQzEzM2lpTmRTL3ZXVlRpQjJzVGl0R1cvWHJIUFdOR0NQZmJzQ2FKcDAzbGhlbDN3QURCWkxTSXArRjVGejUyYlJ2Ykp1Sy83cUlSYmZYUFlQNWlKZmNwZ0tCcndPRGFERWY2M3NVTHhiY21ndlVweUlxZ3pDaDN0ZWxqQzdMc3I0dTBjMDNlTVhlTVMybmhabHhlV1dVaWtsYWZ2MjZ4RWxZaW1DUDlnTy9pQXRndVJoUlFIVDQ4d1lnY1Z3U1BWaGxTdWo3VmtxR1NMMlhzdGVmRXFDME8wS2FWbzhHUHc2TWFBRWVGbFplN0RheU1UdFNnaDlmODJVL1YyT2tzaTRtaHBGdmhRRnR3ZlI5QVdSZVVJbEkzZTZOVkdQb3dkcU8rRXNwcnJnMDlzTWdGV2hwbys3aE9jUEQzRzVPUG1FZTNiaDZLc2Y4LzJkd2R2K3lIQnBDKzR6WnF2a05vV1NQcEsxbEpPc2Ryd2VlQU4zWjMrQTgweEpUQWpCZ2txaGtpRzl3MEJDUlV4RmdRVUloSTBkNm5GMnpzVUJJNW1OdUc4UHVwN2tYVXdRVEF4TUEwR0NXQ0dTQUZsQXdRQ0FRVUFCQ0JJaHZDM3N3QXM1VXh6OUN3VzBhMUVSUHlYVUJPeDF2ZjlkUkFubFdGUHJ3UUltMjI1MWpXcUYwUUNBZ2dBIn0.eyJpc3MiOiJpc3N1ZXIiLCJpYXQiOjE3MDY1Mjg4MDUsImV4cCI6MTcwNjUzMjQwNSwianRpIjoiNGU3MTM2ZTgtNzVjNC00MTA2LWJkNDEtMjg5YjQzZjcxZWE1IiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwic3ViIjoiSVQtMTExTUVESUFHUk9VUFNeXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMTUwIiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb25lIENhbXBhbmlhIiwibG9jYWxpdHkiOiIyMDExMjM0NTYiLCJzdWJqZWN0X3JvbGUiOiJEUlMiLCJwZXJzb25faWQiOiJJVC0xMTFNRURJQUdST1VQU15eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsInJlc291cmNlX2hsN190eXBlIjoiKCcxMTQ4OC00Xl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsImFjdGlvbl9pZCI6IkNSRUFURSIsImF0dGFjaG1lbnRfaGFzaCI6ImQ1YTUzNWFjN2FlY2E1OWNjODA1NmJlYTZlZTlmY2M2NDM0ZWI4MzFjNmFlY2U1NjVhOTMxYTA5YjdhOWI1NDQiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiZ2VzTGFiTmV0X01lZGlhR3JvdXBANjRfNjYiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlbmRvciI6Ik1lZGlhZ3JvdXAgc25jIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiMi40LjAiLCJuYmYiOjE3MDY1Mjg4MDV9.vCX3XSn3z_mEidkimynjFeKvtfseLRo0DkpCBAPcbNDtwC7RWQRKl5t9JnMbV8l9Zxot9kGOH3Mamu7HDL3owr9PorORVhxT1NNR17LUF965PW5Bl6F5ogr4Fgm4ldjJcHMd_ZZYYRfg2sU7G3QSOJEBpoGvitsQjbq_JGfOKO36Y6HSuCEivIjga8gGtig9GXJUpYKoY2XExVuy7cUXJIUFGhff0nGSTxuZpfc66wWaijrQ1wSf2HOyXyj1M4u0flUDRTTu5EWukmc_dfBw9TWC4lmvl5Wq6_ktGA7bxji-XQFtnUBTeySUfdT1a3QIPpyRPyvO40z4lFDnYDzPMw

Token di firma:
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJpZkNoaWF2ZSIsIng1YyI6Ik1JSUwvd0lCQXpDQ0M3VUdDU3FHU0liM0RRRUhBYUNDQzZZRWdndWlNSUlMbmpDQ0JoSUdDU3FHU0liM0RRRUhCcUNDQmdNd2dnWC9BZ0VBTUlJRitBWUpLb1pJaHZjTkFRY0JNRmNHQ1NxR1NJYjNEUUVGRFRCS01Da0dDU3FHU0liM0RRRUZEREFjQkFqVXI3czVaVkpDY3dJQ0NBQXdEQVlJS29aSWh2Y05BZ2tGQURBZEJnbGdoa2dCWlFNRUFTb0VFSU1JTG9tYmlKeFpQbkRyV3Nmdkc4aUFnZ1dRaDROUk5xOTJvQkhmbUV4NmpLQXVDNVNNaHJ0SlI1VHJkOTVhSUErc1p6eDIyWUh0aG5ybXIranZpT0wzU2JtKzRpMUlsSjY0NU9QMzAxQlltcGJrdlJDTjZ6dW1HZitnZmpqbitaV1hRQ2pYUjQrN2MwQlhKQ1VxRXJlR0JvWHMwem1acXVLU0NKcE1jNmNSWnh2MjVqdWpGdjZVWEpuTUVldkZQQ0RKWGdsMzlWWUVudjRTQUJ0V0RSNFFqRzRabGFLU1J2Wit6a3JsajMyODZXaEwzQmR3V3d0TjhCcjUyd1pUVWZLU3dkUFBvK01ibFVlRG9iYURPNFZvTEY3dHFnOThoNzg2QnlCL2F0R0hkQVQvRGl6T211dnA3OGpHUENGSFlVbzdodWNJWnZNQkd1SjMyYnhmbGFLdkIwT2ZjS2tEOGtQMG9wRUg4dExOTHlGa0s3cTA1S2d4U1lsSGlraWVUU0xZdjViTVRvZnFXeDNxaDFLY3Z1WEo3OWRrcW15MlJaaVBNUkpUMUIzcXhRZDVvUHVWZ3FXRHMxWmJTMWpsWklnNEQvZWFPeFRIVzltT3FDd2ZuZzA4SDRobWNRaUcwNjhoU1N1NzZpWlJyVlFScU85aU9qVjNYeDBBbVptQXlkY2N6c3RHTG9VcmNqYnN2RURHaXZvTmVSVEFNM2cvdTdFMXZqd2g0YTRaVDJjY0Vrei9yc0szTjM1SitUTHhaRkZicHB6ZnVsR2pWQXd1amMxV1BKYm05b3R5cExtNDdWZlBrYkdodmZGcWc1N3dVUmRYL2xjWkl5aFk0WTV0QmQzaEo0NXdkSHo2aGthN29PSGozT3dRSGg3YzdzZ2tpbVl3NTlwUVBOT1ZPY21jZHJiYW5vN25ubVFQNnFNQ1B0MThpcHVZQXdZYVFiUHZvcXdLMW5scndjektUUUltTkUxRGlTMUdnbjBpS1ZsNmdYMWJhWWtKLzNMM1hBcVZQYlA3R3VDUnFtNCswWE01OXRkUGR5UXNTdlpjcE9qR0pqL01KNVN4L3ZERmVZVUEyeEdyam9QRGlXczh3cW8yNXI3NExtdnNadmN1aWlZMmdDVFJrM0hQejB1SWdNTDFsTlJqMWhkYnJHczQ1QjNJa0VtWkdjK0VDeG5hdjF1bzdLRkc4V09qbTIzMG9RNjkxZ0tUcFJicVhQV0VVZWc2NStxcjJERnVwaHpLZ2lZNFkzZGlSa1pkRFJDWVhXbXg0dkd6Y1pxMWdFbk9wYXVHVEkrMFl2amZ1S3Y5clp4cHBKNXlGQ2h6TG51b2llYW1PTjY5R1BWWEkxckgyTm1VU0xnMERjdCtzaElvMFpwdjJqd2R4V3g1QXFUSlRScFdtM2FJS1Y5N2NTd3c3NHdlZ1Y1Y2FremNTSS9LRkxTZFV2Yk5SRzBNRHViSXp4QmczUmNyWCtNalJaSDhzSUhxSnNWS3hldm10Nk5KZ1p5b0crUUl2MFp2YVp3eVhxYUdoZkoyYjNFVDh1U3Q3dEh5dUNRdTFDRDlZa0RXYTd2V09Nc3Y2UnJFWXdSMnh2c0Z3ZmVIN1hGU1Z0RG9td3hnais2SStvTnBmdE5XajBlYlR2dGlYaGw3cUpGNG40aTlCdW4zVVRzWDZUTDg3Y1c3MDFvd2ZmLytWaWt4S1dPOWZIL2NxbmRBWjRMSXhpaU1NdTJ1QnArbWVNVk9mNVhvY2hsTnFkdlZkZEZidlhmV1p6ZTUxU1BjM3VnNzU3UkVDMUw5SGZmbXRiVG1mRjdoRDArRitnMkx3Y1FTYlg2bDcweFVaYTd2OFN3U3NUNGlpYkRJcGRndEVSWUphNlZPaXhWYVl3Y0JJZEpGaHh4ajFyWXZibnphTEkzTk90NGhHNkdrcDUyYkd1Z1dNK01URDJ4Vm03Sk56MVJSdnRXVUNlL1JjTVMyN1lIa05jY0pNcXJtZFl6cE9ROTRSK1BYWW5oaFA2bnUwUUJMYmxEVDdkNW9wQk5vUlBvK3kzTVZ5aWhTRFI5aDBzaG80ejMzTHVMUW02MFhTckZ2MHZtczJRcUdJLytabG9lWG5ycnR0eDVTbW85UCttRzdtOVVOWkZCR09nVHcrS1FjV1VvaVBnSXFyWDlGdndEa1dySi9yTHlhYW16T2pFZmhRWTQyN3RDWUdLTFpQTDJoand5RlVxYmMyZFQ5Um9LMnM5cWdORjdOY2EwbGIwbncwNXhmWmhoTmYrbzg1Y1ZWRU9Rek01R2cvQ2s3eHN6TkNkNzZCQmhFdk1PZHUvMFpkVDNYRno4RW55VVk4WUJoeW9tVUJQZjAzeVQ1ckQ5cUVsa0tKV0JiNVpZbkFUU0xYR3IwUERpM3JQZGZFclNBRXNHdlNlMjlrZHFSMjJjdXVDN1UyTk9meWZ0Ti9pY3hnSXNORmlyZ1NjYTg2UnN3ZDMvcitvWG9UYTRRalBqYzBTaTVSdE1Cd0FCemRmaUFiblVJM0poRWJqQXpRQ0p2ZmZhYmhHQTlwKzJlMlZXcVZFNEJJdmV5RS9Zd2dnV0VCZ2txaGtpRzl3MEJCd0dnZ2dWMUJJSUZjVENDQlcwd2dnVnBCZ3NxaGtpRzl3MEJEQW9CQXFDQ0JURXdnZ1V0TUZjR0NTcUdTSWIzRFFFRkRUQktNQ2tHQ1NxR1NJYjNEUUVGRERBY0JBaVU2WmNCMWZ1WUxBSUNDQUF3REFZSUtvWklodmNOQWdrRkFEQWRCZ2xnaGtnQlpRTUVBU29FRVBQcExjaFVza3hRdDJPMmRydDZFM2NFZ2dUUTgyUnYxa3E1aVNoYmNaTVFQaGNibnJtV1Y4S3gxOXRZTWVIcFkwTFJxVC9hUU9iU0c3eHpYbkM1blExN0NqS2FaV2k3YnJzNmY2dzJEUnNWWUIrakJoNmkxR2ZtelZPOGFPazlCVm51UytDaFEyZUVyMjl0U1ZqY29Ua2pSL1FxWXlreFJFSUpMdEtUM0QzVVZLcXNKajIvMTQxTmJ6aG9UdHlKb2UxSDRBT1dhbjh2KytQdWZERFd4enBBczQ0MUtZT2wyMWdsN0V6aVRXOWJMaXFnZzBNQmNoa09ZQ2xzeldpbzQ1a09yRWN5akdkRy85T0t5ZUkrOVBQem1MOHRUVFhiNGRldjhXTGxIR3RpU2UwMStObnpsMUthdU5JMjNBaU11MVBML25LRWg0T2MzR09RbkJMaDE4Z0FtWTBMTUtvbjFmeExBWmt3Nm0vWFd0ajZaaTBMREpIZzJPeWh0dCtPcmRsSmszcFFmODlJZmFZeGVjVmhMNU5oWjNqWEtJTTJqb1VFNlhFbU82U0VuSlhPN1ZLUm1rV3VSQlNsbUo2Mlc3VFIrVjZzZEJmbVRqVWYxUWNMSzBCbnFXQnBRekFDZzBEWGhEZmFnN2kydnJqSlVGN25wY0xYY1lBMkpKZVpHb2ExUUlTOEJQRmgyRGZPYVNmSVlVL1RxS2dWRk5iWXhRL1pUZDMwTjdHS2laVXo1U1JISmYzQ2MvY2dPT0Z4T2hka1llMVFWS0RhQXU2cFFUbmZ5eHdWd1lQM2M4NHJvdkx5VWdIK3F2VDFjcFByRUc1eWtTUGRBRm53R0J1anNvSWZXdFNBeTEwRWk3VWZUZkQxWXFIOXBmd0lzNVIzZVN3d3I4cnhTS0U5VzhVOW1HcDNFVHNuQ3NIT1ZyK05PVlNWOGdpeHhnaGxwUEtUVTY1eHExUDJFWjNxYmJBM1R5dExsRThyQnBTMG1ncHpvQmllczZJRmxHdWg1UENIVmRyVUFvTk4zZndoWmc2ZkxwRzhScDBibnRZSk1TZ295QTFwWmYvaTliUWgwdlB3Z0ZiZVpUMGYwSnpXN1lwRzdEN3QzUEEraTByMVRhNVAvOVoxY29EdE0xSUdXZzFaOXZKMXJxd3VtWFZPclBRekNBNmVKazJhWllqWVRkWWFPUlZtR2FPaW1kSjdXM1RXajYwOFlOeXJOSDc2aVZDR0JjQWRpVW5XcElvKzRmR1VlTHNYQndXNVg2V1JsWEM0dkM4cGs1bFFvZEg5Nm1Qd2lQQTd3N0pSamIrd2FvWE5KSWs5MXQ4RGV2UlNDSFNQdHVURnRNdjdnN2I2Zm1lWTJsK3RVU0NDM0hsbDUybVlsTkdnNEZHMThDWGFVQ1R4U09lcnFRa1RRM3plcWJJcXc4V3pvMHFyeHNEcmUzNDFmc2x5a3pITHJCSDg3S3EzQTdIZ0ZhTktqT1cyRy9idjdsMms3aHU2RE12VkhJWGlIbkc4REd3eDVDVG02Smc1cTlDU0l3M3gvL3NPUE1zRkVNcUFDbEE4em9hck8zSHRUOUFmc0EwblhpbnRpbytjZVRFZ0U4VnhVL0VRZTF0bGVlb2ZHWVF3T0xqTHpMMGFubXY3cWM2R0lmQm5MTCtLTEI3Qm9HclVocXVJNUNBRjIxL1RKQks3YzdGOHFYdGdqblJSNDJocmVrN3hNbFhhQzEzM2lpTmRTL3ZXVlRpQjJzVGl0R1cvWHJIUFdOR0NQZmJzQ2FKcDAzbGhlbDN3QURCWkxTSXArRjVGejUyYlJ2Ykp1Sy83cUlSYmZYUFlQNWlKZmNwZ0tCcndPRGFERWY2M3NVTHhiY21ndlVweUlxZ3pDaDN0ZWxqQzdMc3I0dTBjMDNlTVhlTVMybmhabHhlV1dVaWtsYWZ2MjZ4RWxZaW1DUDlnTy9pQXRndVJoUlFIVDQ4d1lnY1Z3U1BWaGxTdWo3VmtxR1NMMlhzdGVmRXFDME8wS2FWbzhHUHc2TWFBRWVGbFplN0RheU1UdFNnaDlmODJVL1YyT2tzaTRtaHBGdmhRRnR3ZlI5QVdSZVVJbEkzZTZOVkdQb3dkcU8rRXNwcnJnMDlzTWdGV2hwbys3aE9jUEQzRzVPUG1FZTNiaDZLc2Y4LzJkd2R2K3lIQnBDKzR6WnF2a05vV1NQcEsxbEpPc2Ryd2VlQU4zWjMrQTgweEpUQWpCZ2txaGtpRzl3MEJDUlV4RmdRVUloSTBkNm5GMnpzVUJJNW1OdUc4UHVwN2tYVXdRVEF4TUEwR0NXQ0dTQUZsQXdRQ0FRVUFCQ0JJaHZDM3N3QXM1VXh6OUN3VzBhMUVSUHlYVUJPeDF2ZjlkUkFubFdGUHJ3UUltMjI1MWpXcUYwUUNBZ2dBIn0.eyJpc3MiOiJpc3N1ZXIiLCJpYXQiOjE3MDY1Mjg4MDUsImV4cCI6MTcwNjUzMjQwNSwianRpIjoiNGU3MTM2ZTgtNzVjNC00MTA2LWJkNDEtMjg5YjQzZjcxZWE1IiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwic3ViIjoiSVQtMTExTUVESUFHUk9VUFNeXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMTUwIiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb25lIENhbXBhbmlhIiwibG9jYWxpdHkiOiIyMDExMjM0NTYiLCJzdWJqZWN0X3JvbGUiOiJEUlMiLCJwZXJzb25faWQiOiJJVC0xMTFNRURJQUdST1VQU15eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsInJlc291cmNlX2hsN190eXBlIjoiKCcxMTQ4OC00Xl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsImFjdGlvbl9pZCI6IkNSRUFURSIsImF0dGFjaG1lbnRfaGFzaCI6ImQ1YTUzNWFjN2FlY2E1OWNjODA1NmJlYTZlZTlmY2M2NDM0ZWI4MzFjNmFlY2U1NjVhOTMxYTA5YjdhOWI1NDQiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiZ2VzTGFiTmV0X01lZGlhR3JvdXBANjRfNjYiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlbmRvciI6Ik1lZGlhZ3JvdXAgc25jIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiMi40LjAiLCJuYmYiOjE3MDY1Mjg4MDV9.vCX3XSn3z_mEidkimynjFeKvtfseLRo0DkpCBAPcbNDtwC7RWQRKl5t9JnMbV8l9Zxot9kGOH3Mamu7HDL3owr9PorORVhxT1NNR17LUF965PW5Bl6F5ogr4Fgm4ldjJcHMd_ZZYYRfg2sU7G3QSOJEBpoGvitsQjbq_JGfOKO36Y6HSuCEivIjga8gGtig9GXJUpYKoY2XExVuy7cUXJIUFGhff0nGSTxuZpfc66wWaijrQ1wSf2HOyXyj1M4u0flUDRTTu5EWukmc_dfBw9TWC4lmvl5Wq6_ktGA7bxji-XQFtnUBTeySUfdT1a3QIPpyRPyvO40z4lFDnYDzPMw

**Comment by vigliottim** [comment]
Buongiorno, potrebbe cortesemente allegare anche la request completa? Grazie.

**Comment by vigliottim** [comment]
Buonasera, la invitiamo ad assicurarsi di utilizzare il certificato pem di autenticazione corretto (A1XXXXXXX.p12). 
Attendiamo un suo riscontro. Grazie.

**Comment by penny66** [comment]
Salve, i certificati utilizzati sono i seguenti:

CN = A1#111MEDIAGROUPS
2.5.4.97 = CF:IT-111MEDIAGROUPS
O = Ministero della Salute
C = IT

CN = S1#111MEDIAGROUPS
2.5.4.97 = CF:IT-111MEDIAGROUPS
O = Ministero della Salute
C = IT

**Comment by penny66** [comment]
problema risolto grazie
