### ISSUE TITLE
Accreditamento soluzione IM-PATIDOK

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#588]
Buongiorno,
volevamo notificare il caricamento completato dei test case per la soluzione IM-PATIDOK :

[ministero-salute/it-fse-accreditamento#1133](https://github.com/ministero-salute/it-fse-accreditamento/pull/1154)

questa pull request contiene LDO,RSA,VPS.

Grazie

**Comment by vigliottim** [comment]
Buongiorno, la ringraziamo per la notifica. Procediamo alla chiusura della presente issue e rimaniamo a disposizione per ulteriori richieste di supporto.
