### ISSUE TITLE
Test validazione VPS - errore 502 Invalid response received from the API Implementation

### ISSUE THREAD

**Issue by davidetau** [ministero-salute/it-fse-support#59]
Durante l'invocazione del servizio di validazione del verbale di pronto soccorso otteniamo il seguente response di errore:
`{"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"7d14db5f-95a3-11ed-b21d-005056ae54fa"}`
E' possibile avere maggiore dettaglio sulla causa dell'errore?
grazie

**Comment by pFonziSogei** [comment]
Salve, il sistema riceve errori per più di 10K di dimensione; stiamo allargando questa grandezza ma intanto dovrebbe gentilmente rivedere l'invio basandosi sugli esempi forniti e diffusi

**Comment by IStacchiotti** [comment]
Non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
