### ISSUE TITLE
Errore 401 (Unauthorized) in fase di test di validazione

### ISSUE THREAD

**Issue by penny66** [ministero-salute/it-fse-support#590]
Buongiorno, in fase di validazione ricevo errore 401 - Unauthorized di seguito le specifiche dei token JWT

[Token_Auth.txt](https://github.com/ministero-salute/it-fse-support/files/14096448/Token_Auth.txt)
[Token_Sign.txt](https://github.com/ministero-salute/it-fse-support/files/14096449/Token_Sign.txt)

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate è emerso che i token utilizzati non risultano corretti. 
In particolare, le riportiamo di seguito alcuni errori:
 
**FSE-JWT-Signature**

- _"iss": "issuer"_ -> campo che va valorizzato con "integrity:" seguito dal "Common Name del certificato di firma" (es.  "issuer": "integrity:S1#110201234567XX") 
- _patient_consent: True_ -> campo che contiene un valore booleano, da inserire in lower case (es. true)
- _resource_hl7_type: '11488-4^^2.16.840.1.113883.6.1'_ -> il formato è sbagliato poiché mancano le parentesi tonde: **(**'11488-4^^2.16.840.1.113883.6.1'**)**
- _"x5c"_ -> campo non valorizzato correttamente (dovrebbe contenere una stringa all'interno di un array)

**Authentication Bearer Token**

- _"iss": "issuer"_ -> campo che va valorizzato con "auth:" seguito dal "Common Name del certificato di firma" (es.  "issuer": "auth:S1#110201234567XX") 
- _"nbf"_: 1706610928 -> campo non previsto
- _"x5c"_ -> campo non valorizzato correttamente (dovrebbe contenere una stringa all'interno di un array)

La invitiamo a consultare la documentazione al link: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt per trovare informazioni sui campi da inserire nei token e la loro valorizzazione. 
Rimaniamo a disposizione per chiarimenti.

**Comment by penny66** [comment]
Buongiorno,
modifiche apportate , ma il problema persiste, sempre errore 401, di seguito i nuovi token
[Token_Auth.txt](https://github.com/ministero-salute/it-fse-support/files/14097619/Token_Auth.txt)
[Token_Sign.txt](https://github.com/ministero-salute/it-fse-support/files/14097620/Token_Sign.txt)

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
potrebbe gentilmente riportare anche la risposta completa ricevuta (compreso govway_id, traceid e il messaggio di errore ricevuto, in caso siano disponibili) ? 
Grazie

**Comment by penny66** [comment]
di seguito la risposta completa:

StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  X-Backside-Transport: FAIL FAIL
  Connection: Keep-Alive
  Transfer-Encoding: chunked
  Pragma: no-cache
  GovWay-Transaction-ErrorType: TokenAuthenticationFailed
  GovWay-Transaction-ID: 1408afae-bf70-11ee-9fa8-005056ae7395
  Vary: *
  X-Content-Type-Options: nosniff
  X-Global-Transaction-ID: 3f7e3e2d65b8fefaa150d92d
  Cache-Control: no-store, must-revalidate, no-cache
  Date: Tue, 30 Jan 2024 13:51:55 GMT
  Server: GovWay-SOGEI
  WWW-Authenticate: Bearer realm="FSE-JWT-Signature", error="invalid_token", error_description="Token invalid"
  Content-Type: application/problem+json
  Expires: 0
}

**Comment by LucaRogledi** [comment]
Buonasera,
ci risulta che il campo x5c non è valorizzato correttamente non essendo all'interno all'interno di un array come riportato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt):

"Esempio di token decodificato, sezione header"
```
{
 
"alg": "RS256",
 
 "typ": "JWT",
 
 "x5c": [
 
   "MIIDXjCCAkagAwIBAgIBAjANBgkqhkiG9w ... 779BM4SOI="
 
 ]
 
}
```
La invitiamo gentilmente ad effettuare la correzione e utilizzare il tool online [jwt.io](https://jwt.io/) per la verifica della validità dei token se può esserle di aiuto.
Restiamo a disposizione in caso di ulteriore supporto.
Grazie

**Comment by vigliottim** [comment]
Buongiorno, potrebbe cortesemente allegare la response completa dell'ultima chiamata effettuata con i nuovi token? Grazie.

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate il campo _"iat"_ contenuto nei token è errato: 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/e92ac0db-2430-4116-b079-75f4714fff45)
Come riportato in [documentazione ](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt), _"iat"_ è un numero intero (timestamp in secondi) - non una stringa come nei token forniti da lei - che indica il momento in cui il token è stato generato e serve per conoscerne l’età. 
La preghiamo di correggerlo mettendo una data valida in formato intero e riprovare. Grazie.
