### ISSUE TITLE
Accreditamento soluzione G2 WEB

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#594]
Buongiorno,
volevamo notificare il caricamento completato dei test case per la soluzione G2 WEB :

https://github.com/ministero-salute/it-fse-accreditamento/pull/1162

questa pull request contiene RSA.

Grazie

**Comment by vigliottim** [comment]
Buongiorno, la ringraziamo per la notifica. Procediamo alla chiusura della presente issue e rimaniamo a disposizione per ulteriori richieste di supporto.
