### ISSUE TITLE
ASP Siracusa - VPS - Errore in estrazione CDA

### ISSUE THREAD

**Issue by bocci66** [ministero-salute/it-fse-support#597]
Buonasera,
non riusciamo a capire la causa dell'errore relativo a "traceID":"e22875a76591e5ca"
( Error while extracting CDA from PDF document,status:400 ).

Allego PDF con CDA iniettato relativo a tale chiamata : 
[742023_in_errore.pdf](https://github.com/ministero-salute/it-fse-support/files/14114686/742023_in_errore.pdf)

Riporto un invio correttamente da Voi ricevuto, dal cui confronto non riusciamo a dedurre il motivo dello scarto :
"traceID":"c05455b00dcaee12" - "workflowInstanceId":"2.16.840.1.113883.2.9.2.190.4.4.e8b79cb7ff8ffdfcd66e60fb57c26b003ebb8999b5cece22acbecb02befe2d31.a4be186df8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
[742036_ok.pdf](https://github.com/ministero-salute/it-fse-support/files/14114852/742036_ok.pdf)

Grazie

**Comment by IStacchiotti** [comment]
Buongiorno,
Per prima cosa le segnaliamo che il nome del pdf ricevuto dal sistema (2086010340000000240152573801V105.pdf), non coincide con quello da lei riportato (742023_in_errore.pdf): potrebbe accertarsi che i file corrispondano?

In secondo luogo, le facciamo presente il file PDF ricevuto in ingresso dal sistema, estratto dai log della chiamata, risulta corrotto/illeggibile (quando si tenta di aprirlo compare "Errore durante l'elaborazione di una pagina. ColorSpace non valido"), e il cda allegato appare vuoto. Il file inviato nella richiesta al gateway deve essere integro, leggibile e ben codificato: nel caso possa esserle utile, la invitiamo a controllare i ticket #480 e #131, in cui altri fornitori hanno segnalato un problema analogo, corretto rispettivamente risolvendo un'incongruenza sul charset del pdf e con una modifica di una libreria utilizzata per la creare la richiesta http.

Specifichiamo infine che l'indicazione del charset (in bold), nella sezione dedicata al pdf, non è obbligatoria: potreste ritentare la chiamata rimuovendola?  

Content-Disposition: form-data; name="file"; filename="2086010340000000240152573801V105.pdf"
Content-Type: application/pdf; **charset=utf-8**
Content-Transfer-Encoding: binary

Rimaniamo in attesa di un vostro gentile riscontro.
Grazie

**Comment by bocci66** [comment]
Buonasera,
continuiamo a ricevere svariati errori,

**Comment by IStacchiotti** [comment]
Buonasera, al fine di supportarvi nella risoluzione, potreste specificare che tipo di errori ricevete e allegare le response complete? Grazie

**Comment by bocci66** [comment]
Buonasera,
dalle 15 odierne circa, qualsiasi request di qualsiasi modulo di qualsiasi nostro impianto in produzione, stanno dando il medesimo errore : Error while extracting CDA from PDF document,status:400
E' plausibile ci sia un disservizio ?
E' plausibile che questo eventuale problema non sia nato oggi, ma sia progredito nel tempo ?
Questa vs segnalazione (generica) , è possibile che venga da Voi fornita quando non ricevete completamente la request, a causa ad esempio di un timeout ?
In definitiva, il vs ambiente di pre-produzione risulta adeguato a ricevere la moltitudine di documenti nazionali, provenienti dagli ambienti di produzione degli Enti ? Avete avuto altre issues in merito ?
Grazie, Distinti Saluti

**Comment by vigliottim** [comment]
Buongiorno, le chiediamo cortesemente di allegare la risposta completa, comprensiva di traceId/govway-id, delle ultime chiamate effettuate. Grazie per la collaborazione.

**Comment by bocci66** [comment]
Buongiorno :

gateway : https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1

{
	"traceID": "84dd669999be5bc1",
	"spanID": "84dd669999be5bc1",
	"type": "/msg/cda-element",
	"title": "Errore in fase di estrazione del CDA.",
	"detail": "Error while extracting CDA from PDF document",
	"status": 400,
	"instance": "/cda-extraction",
	"workflowInstanceId": "UNKNOWN_WORKFLOW_ID"
}

{
	"traceID": "f379f7b798e954ab",
	"spanID": "f379f7b798e954ab",
	"type": "/msg/cda-element",
	"title": "Errore in fase di estrazione del CDA.",
	"detail": "Error while extracting CDA from PDF document",
	"status": 400,
	"instance": "/cda-extraction",
	"workflowInstanceId": "UNKNOWN_WORKFLOW_ID"
}

{
	"traceID": "1b2408c5d2a8d7e4",
	"spanID": "1b2408c5d2a8d7e4",
	"type": "/msg/cda-element",
	"title": "Errore in fase di estrazione del CDA.",
	"detail": "Error while extracting CDA from PDF document",
	"status": 400,
	"instance": "/cda-extraction",
	"workflowInstanceId": "UNKNOWN_WORKFLOW_ID"
}

ecc., ecc. : il problema persiste dalle 15 circa di venerdì 2 febbraio.

Saluti

**Comment by LucaRogledi** [comment]
Buonasera, 
La ringraziamo per la segnalazione e le confermiamo che è stata rilasciata una fix.
Segnaliamo che il cda iniettato nel pdf deve essere nominato come "cda.xml" come indicato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#2-contesto-di-riferimento) .
Restiamo a disposizione in caso di ulteriore supporto.
Grazie

**Comment by bocci66** [comment]
Buongiorno,
Vi informo che la fix da Voi installata non ha risolto il problema.
Inoltre, come si evince da issue #131 e #60, il vincolo del nome "cda.xml" per il file iniettato pare non essere la causa di errore.
Saluti

**Comment by IStacchiotti** [comment]
Buongiorno, le issue citate non tengono conto di sviluppi recenti. Se ci conferma pertanto che il test è stato condotto allegando un pdf con iniettato un cda con il naming atteso "cda.xml", le chiediamo cortesemente di allegare la response completa ricevuta dal sistema e di allegare il pdf utilizzato a scopo di test. In caso contrario la invitiamo gentilmente a riprovare seguendo le indicazioni riportate nel messaggio precedente. Grazie

**Comment by bocci66** [comment]
Buonasera,
sottopongo altro caso per il medesimo problema, effettuato su un assistito di prova, di cui posso allegare il pdf salvato su DB.
Saluti

{
	"traceID": "7d08473c2b53d67d",
	"spanID": "7d08473c2b53d67d",
	"type": "/msg/cda-element",
	"title": "Errore in fase di estrazione del CDA.",
	"detail": "Error while extracting CDA from PDF document",
	"status": 400,
	"instance": "/cda-extraction",
	"workflowInstanceId": "UNKNOWN_WORKFLOW_ID"
}

[2086010340000000240152573801V122.pdf](https://github.com/ministero-salute/it-fse-support/files/14184179/2086010340000000240152573801V122.pdf)

**Comment by bocci66** [comment]
Buongiorno,
allego le prove effettuate sul medesimo verbale di test, il cui esito passa da FAILURE a SUCCESS, variando sostanzialmente la sola parte testuale della section Parametri_Vitali : esistono per caso limiti sul num. di caratteri o di righe ?
Grazie, Saluti

{
	"traceID": "4760ad808eb769a1",
	"spanID": "4760ad808eb769a1",
	"type": "/msg/cda-element",
	"title": "Errore in fase di estrazione del CDA.",
	"detail": "Error while extracting CDA from PDF document",
	"status": 400,
	"instance": "/cda-extraction",
	"workflowInstanceId": "UNKNOWN_WORKFLOW_ID"
}

{
	"traceID": "55e9dba77b568d89",
	"spanID": "55e9dba77b568d89",
	"workflowInstanceId": "2.16.840.1.113883.2.9.2.190.4.4.fc8b5cf1cc69aa0b2bd25d9eede2a0a3c65e4c032fd5e67df95ca0b4f786b293.c6e5a1b819^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

[2086010340000000240152573801V128.pdf](https://github.com/ministero-salute/it-fse-support/files/14194339/2086010340000000240152573801V128.pdf)

[2086010340000000240152573801V129.pdf](https://github.com/ministero-salute/it-fse-support/files/14194343/2086010340000000240152573801V129.pdf)

**Comment by LucaRogledi** [comment]
Buonasera,
Le confermiamo che i pdf allegati su GitHub nei sui ultimi due messaggi (2086010340000000240152573801V122.pdf, 2086010340000000240152573801V128.pdf, 2086010340000000240152573801V129.pdf) superano correttamente la validazione.
Dalle nostre analisi è emerso che, l'errore che riceve, è riconducibile al fatto che il pdf che viene effettivamente acquisito dal sistema risulta diverso da quello da lei allegato al thread. Alleghiamo a titolo di esempio il pdf che risulta a sistema associato alla chiamata "traceId"= "7d08473c2b53d67d": nel tentativo di visualizzarlo noterà l'errore "Invalid ColorSpace" e la validazione sul file in questione genera in effetti l'errore segnalato ("Errore in fase di estrazione del CDA.").
La invitiamo a ritentare l'invocazione del servizio di validazione utilizzando un altro client, come Postman, per verificarne la correttezza.
Restiamo a disposizione in caso di ulteriore supporto.
Grazie

[issue597.pdf](https://github.com/ministero-salute/it-fse-support/files/14196970/issue597.pdf)

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto riscontri, procediamo alla chiusura del presente ticket. 
Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
