### ISSUE TITLE
Error while extracting CDA from PDF document

### ISSUE THREAD

**Issue by fabiodap** [ministero-salute/it-fse-support#598]
buongiorno,

da oggi pomeriggio tutti i nostri test di validazione fallicono nel modo seguente:

gateway                  : https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1
traceId                  : 522ddc5ce08b6640
WorkflowInstanceId       : UNKNOWN_WORKFLOW_ID
response                 : Error while extracting CDA from PDF document
type                     : /msg/cda-element
application/problem+json : 
{
    "detail": "Error while extracting CDA from PDF document",
    "instance": "/cda-extraction",
    "spanID": "522ddc5ce08b6640",
    "status": 400,
    "traceID": "522ddc5ce08b6640",
    "type": "/msg/cda-element",
    "workflowInstanceId": "UNKNOWN_WORKFLOW_ID"
}

Potreste gentilemente dirci se è cambiato qualcosa sul Validatore?

Saluti,
Fabio

**Comment by fabiodap** [comment]
Buongiorno,

sono test che effettuiamo ad ogni build del nostro prodotto e sono sempre passati correttamente.
Non capiamo perchè adesso falliscono.

Saluti,
Fabio

**Comment by fabiodap** [comment]
questo un altro esempio di stamattina:

----------- FAIL -----------
gateway                  : https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1
traceId                  : f5e8151b9292b69e
WorkflowInstanceId       : UNKNOWN_WORKFLOW_ID
response                 : Il campo person_id non Ã¨ valorizzato
type                     : /msg/jwt-validation
application/problem+json : 
{
    "detail": "Il campo person_id non Ã¨ valorizzato",
    "instance": "/jwt-mandatory-field-missing",
    "spanID": "f5e8151b9292b69e",
    "status": 403,
    "traceID": "f5e8151b9292b69e",
    "type": "/msg/jwt-validation",
    "workflowInstanceId": "UNKNOWN_WORKFLOW_ID"
}

In allegato il file PDF generato.
[TEST-JWT-WRONG-VALUE-KO.pdf](https://github.com/ministero-salute/it-fse-support/files/14162003/TEST-JWT-WRONG-VALUE-KO.pdf)

**Comment by fabiodap** [comment]
Segnalo che aprendo lo stesso pdf con Adobe Reader il CDA viene correttamente estratto.

**Comment by joGrim65** [comment]
Anche i nostri sviluppatori hanno evidenziato lo stesso problema.
Validiamo da diverse settimane e tutto è sempre andato liscio.
Inoltre, lato nostro, non abbiamo modificato nulla circa l'embedding del cda nel pdf e anche per noi, l'apertura in Acrobat funziona senza problemi

**Comment by vigliottim** [comment]
> joGrim65
Buon pomeriggio, potrebbe gentilmente fornirci il pdf utilizzato nelle chiamate? Grazie.

**Comment by fabiodap** [comment]
E possibile che abbiate attivato un controllo sul fatto che la dimensione dell'attachment cda.xml risulti essere maggiore di zero?

**Comment by vigliottim** [comment]
> E possibile che abbiate attivato un controllo sul fatto che la dimensione dell'attachment cda.xml risulti essere maggiore di zero?

Buongiorno @fabiodap, le comunichiamo che stiamo effettuando delle verifiche in merito al problema evidenziato. 
Le daremo un riscontro quanto prima. 
Grazie per la collaborazione.

**Comment by joGrim65** [comment]
@vigliottim 
Il pdf che racchiude il CDA, ripeto NON è variato ed è un semplice PDF con una pagina "blank", usato in decine di test da fine dicembre.
Cioè, cambia il cda contenuto, ma l'involucro pdf non varia.
Un tale pdf con CDA embedded era già stato allegato in una issue precedente (non ricordo se 547 o 554).

**Comment by vigliottim** [comment]
Buonasera, vi confermiamo che è stata rilasciata una fix correttiva. 
Vi invitiamo cortesemente a riprovare, il problema non dovrebbe più presentarsi. 
Rimaniamo a completa disposizione in caso contrario. 
Grazie.

**Comment by fabiodap** [comment]
Buonasera,

sembra che il problema sia risolto. Effetuerò maggiori test domani mattina.

Saluti,
Fabio

**Comment by joGrim65** [comment]
In allegato un file che inviamo a FSE Gateway
[file-envelope-1234.pdf](https://github.com/ministero-salute/it-fse-support/files/14183445/file-envelope-1234.pdf)

Questo file viene aperto correttamente da Acrobat Reader, è visibile il CDA e viene correttamente estratto/visualizzato.
Inoltre tale file viene correttamente aperto ed il relativo CDA viene estratto usando differenti librerie (iText, PdfBox).

E' palese che il problema non può essere questo artifatto...

Rimango in attesa di riscontri

Grazie

**Comment by LucaRogledi** [comment]
Buonasera @joGrim65 ,
Dalle verifiche è emerso che il cda iniettato nel pdf non segue la naming convention stabilita.
Segnaliamo che il cda iniettato nel pdf deve essere nominato come "cda.xml" come indicato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#2-contesto-di-riferimento) .
Se il problema persiste la invitiamo ad aprire un ticket dedicato, avendo cura di allegare la response completa restituita dal sistema.
Grazie

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. 
Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.

**Comment by fabiodap** [comment]
Buongiorno,

per quanto ci riguarda il problema è risolto.

Saluti,
Fabio

**Comment by mimma81** [comment]
Buingiorno,
in fase di validazione dei nostri pdf otteniamo questo errore: 
Gateway response body: {"traceID":"1f1324fbb8c36c5a",
"spanID":"1f1324fbb8c36c5a",
"type":"/msg/cda-element",
"title":"Errore in fase di estrazione del CDA.",
"detail":"Error while extracting CDA from PDF document",
"status":400,"instance":"/cda-extraction",
"workflowInstanceId":"UNKNOWN_WORKFLOW_ID"}

lo stesso pdf con Adobe Reader il CDA viene correttamente estratto
in allegato il pdf utilizzato.

potreste gentilmente dirmi quel è il problema?

grazie 
Mimma
[aaaaa.pdf](https://github.com/user-attachments/files/15836607/aaaaa.pdf)

**Comment by vigliottim** [comment]
> Buingiorno, in fase di validazione dei nostri pdf otteniamo questo errore: Gateway response body: {"traceID":"1f1324fbb8c36c5a", "spanID":"1f1324fbb8c36c5a", "type":"/msg/cda-element", "title":"Errore in fase di estrazione del CDA.", "detail":"Error while extracting CDA from PDF document", "status":400,"instance":"/cda-extraction", "workflowInstanceId":"UNKNOWN_WORKFLOW_ID"}
> 
> lo stesso pdf con Adobe Reader il CDA viene correttamente estratto in allegato il pdf utilizzato.
> 
> potreste gentilmente dirmi quel è il problema?
> 
> grazie Mimma [aaaaa.pdf](https://github.com/user-attachments/files/15836607/aaaaa.pdf)

Buongiorno, le chiediamo gentilmente di aprire una nuova issue. Grazie.
