### ISSUE TITLE
Info Accreditamento Publicazione

### ISSUE THREAD

**Issue by igcomsrl** [ministero-salute/it-fse-support#599]
Buonasera, una volta implementati i diversi servizi relativi alla  publicazione ed eseguiti i test come da 
accreditamento-checklist_V8.1.3.xlsx, la procedura di accreditamento è la stessa?
cioè facciamo sempre una pull request con una cartella dei test case di publicazione?
Hrazie mille

**Comment by IStacchiotti** [comment]
Buonasera @igcomsrl, le confermiamo che la procedura sarà la stessa. Le segnaliamo però che l'accreditamento per il servizio di pubblicazione momentamente è sospeso. La invitiamo a seguire il canale #fse su Slack per eventuali aggiornamenti in merito.
Procediamo alla chiusura del presente e rimaniamo a disposizione nel caso fosse necessario ulteriore supporto, grazie
