### ISSUE TITLE
Schematron LDO riga 556 Errore 87. Possibile problema BLOCCANTE- Esami eseguiti durante ricovero

### ISSUE THREAD

**Issue by giuseppe-fasulo** [ministero-salute/it-fse-support#6]
Il controllo mi pare verifichi in maniera assertiva che i sistemi di codifica impiegati siano LOINC o ICD9-CM, non consentendo altri sistemi di codifica; ma il messaggio  recita:
ERRORE-87| Sezione Esami eseguiti durante il ricovero: l'entry/observation/code **può** essere valorizzato secondo i sistemi di codifica
			LOINC @codeSystem='2.16.840.1.113883.6.1'
			ICD-9-CM @codeSystem='2.16.840.1.113883.6.103

assert test="count(hl7:observation/hl7:code[@codeSystem='2.16.840.1.113883.6.1'])=1 or 
			count(hl7:observation/hl7:code[@codeSystem='2.16.840.1.113883.6.103'])=1"

Questo controllo, così implementato risulterebbe bloccante, in caso di adozione di codifiche ministeriali o regionali, pure previste nello specifico. 
Evidenzio che nel contesto degli esami eseguiti durante il ricovero lo schema ICD9 **non è pertinente** ( l'errore discende dalla linea guida HL7 che impropriamente cita ICD9  a pag  90) in quanto afferisce alle diagnosi/patologie.

**Comment by zukka77** [comment]
Grazie, queste segnalazioni sono preziose.

**Comment by gndibiase** [comment]
Le codifiche Ministeriali o Regionali possono essere inserite attraverso l’elemento translation, come riportato sulla guida a pagina 90. Per conformità alla guida, visto che i 2 sistemi di codifica (LOINC o ICD-9-CM) sono entrambi opzionali, sarà necessaria una modifica sul controllo, il quale dovrà essere di tipo warning e non assert.
Inoltre, si sottolinea che le codifiche afferenti al sistema ICD-9-CM, sono inserite per valorizzare eventuali procedure di indagine all’interno della sezione Esami eseguiti durante il ricovero.
Grazie per la segnalazione.
