### ISSUE TITLE
Errore in fase di estrazione del CDA

### ISSUE THREAD

**Issue by NunzioAgfa** [ministero-salute/it-fse-support#60]
Buongiorno,
il servizio web di validazione mi restituisce l'errore:
"Errore in fase di estrazione del CDA. - Error while extracting CDA from PDF document"
Il file allegato al pdf, ha nome "cda.xml", come richiesto dalle vostre specifiche.
Ho fatto poi la seguente prova con il vostro applicativo PdfGenerator e il cda viene invece estratto senza problemi dall'applicativo.
Per fare questa prova, ho modificando il codice della classe Launcher del vostro PdfGenerator, in modo tale da ricevere in ingresso il pdf con cda allegato già allegato, e ho quindi provato con l'applicativo PdfGenerator solo a validarlo (con il parametro -v) e l'estrazione del cda viene effettuata (viene visualizzato il cda nella console dos).
Sapete dirmi quale può essere il problema nel servizio web se con PdfGenerator viene estratto?
Allego un pdf di esempio, dove come pdf ho utilizzato proprio il vostro pdf di esempio al quale ho poi allegato il cda creato dal mio applicativo.
[test.pdf](https://github.com/ministero-salute/it-fse-support/files/10433940/test.pdf)

**Comment by zukka77** [comment]
Buongiorno, puoi fornire il traceId dell'errore? e se disponibile l'header http del multipart che invia il file pdf.

grazie

**Comment by NunzioAgfa** [comment]
Ecco la risposta completa, con traceId:
{
  "traceID" : "01f9e74a85a42003",
  "spanID" : "01f9e74a85a42003",
  "type" : "/msg/cda-element",
  "title" : "Errore in fase di estrazione del CDA.",
  "detail" : "Error while extracting CDA from PDF document",
  "status" : 400,
  "instance" : "/cda-extraction",
  "workflowInstanceId" : "UNKNOWN_WORKFLOW_ID"
}

**Comment by NunzioAgfa** [comment]
In allegato il json dell'header http
[intestazioneHttp.txt](https://github.com/ministero-salute/it-fse-support/files/10434147/intestazioneHttp.txt)

**Comment by IStacchiotti** [comment]
Buonasera.
Il comportamento non desiderato dovrebbe essere causato dal contenuto dell'allegato:
<typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040" />
la versione di riferimento dovrebbe essere la POCD_MT000040UV02.

**Comment by NunzioAgfa** [comment]
Buonasera, il problema sembra però legato ad altro. Ho fatto ora una prova, allegando al pdf il vostro cda di esempio, ma ottengo lo stesso errore richiamando l'endpoint.
Allego il pdf con relativo cda.
[testA.pdf](https://github.com/ministero-salute/it-fse-support/files/10438437/testA.pdf)

**Comment by pFonziSogei** [comment]
Salve, l'errore sembra legato al metodo con cui si estrae il CDA2 (sembra che stia inserendo il PDF come attachment e provando ad estrarlo come resource). Potrebbe provare a modificare la request body per rendere coerenti iniezione ed estrazione?

**Comment by NunzioAgfa** [comment]
Buongiorno, l'errore mi viene restituito quando viene richiamato il vostro servizio di validazione, che non riesce appunto ad estrarre il cda dal pdf (perlomeno l'errore restituito è questo: "Errore in fase di estrazione del CDA. - Error while extracting CDA from PDF document"), ma aprendo il file pdf con acrobat reader, il cda risulta correttamente allegato ed estraibile e l'estrazione si riesce a fare anche utilizzando il vostro tool pdf-generator (vedere immagini allegate).
Per modificare il request body cosa intende? Nella chiamata http, nel requestBody dell'intestazione, il campo mode è già valorizzato con "ATTACHMENT"
![Acrobat](https://user-images.githubusercontent.com/122875169/213137549-229c05ad-3136-42a7-b772-f076e67940bc.png)
![pdf-Generator](https://user-images.githubusercontent.com/122875169/213137556-a8c8d341-316b-40bd-8618-281600ed56ee.jpg)

**Comment by NunzioAgfa** [comment]
Buongiorno, sapete indicarmi qualche dettaglio sul problema che viene riscontrato nell'estrazione del cda dal pdf?

**Comment by Ser-ena** [comment]
Buongiorno: per il file "test.pdf" l'errore che riceve è 
Schema with version POCD_HD000040 not found on database. (Tale errore è dato dal fatto che si sta usando un  POCD non conforme a quello accettato dal GTW)

Per il file "testA.pdf" invece la validazione và a buon fine. Ci servirebbe cortesemente, se fosse possibile, avere
un esempio di curl o requestBody che sta usando per chiamare il gtw.

**Comment by NunzioAgfa** [comment]
Sotto il requestBody legato alla chiamata del file "testA.pdf", dal quale ottengo l'errore "Errore in fase di estrazione del CDA.".
Ho appena fatto la chiamata e mi ha restituito questo "traceID" : "d1b710b8a834624d"


--9febce95-5367-42c7-80c7-7eaf08564d06
Content-Disposition: form-data; name="requestBody"

{"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VALIDATION"}
--9febce95-5367-42c7-80c7-7eaf08564d06
Content-Disposition: form-data; name="file"; filename="cda.pdf"
Content-Type: application/pdf

%PDF-1.7
...(file pdf)

%%EOF

--9febce95-5367-42c7-80c7-7eaf08564d06-

**Comment by Ser-ena** [comment]
Buongiorno, nella request body il filename è cda.pdf: ci puo' cortesemente confermare che il content di "testA.pdf" sia lo stesso di "cda.pdf"?

**Comment by NunzioAgfa** [comment]
sì, il content ha all'interno il contenuto del file testA.pdf, stesso identico contenuto. Nel filename della requestBody mettiamo il valore predefinito "cda.pdf", ma ovviamente il content è il contenuto del documento pdf per il quale deve essere validato il CDA, in questo caso il contenuto di testA.pdf

**Comment by NunzioAgfa** [comment]
allego il file cda.pdf, ma come dicevo ha lo stesso contenuto del file che avevo già mandato
[cda.pdf](https://github.com/ministero-salute/it-fse-support/files/10490699/cda.pdf)

**Comment by pFonziSogei** [comment]
Salve, il file che vediamo all'interno della transazione inviata è differente da quello che allega qui; in particolare nel PDF non ci sono righe di testo e l'allegato è di 0Kb. Può verificare?

**Comment by NunzioAgfa** [comment]
Sì, giusto, nell'ultimo test abbiamo erroneamente inviato un pdf con un cda vuoto. In ogni caso, abbiamo poi continuato ad analizzare internamente il problema e abbiamo trovato la causa, era legato all'encoding utilizzato nella chiamata. Grazie comunque del supporto. Ora siamo riusciti a validare il cda, questo l'id di una risposta positiva appena ottenuta:
"workflowInstanceId" : "2.16.840.1.113883.2.9.2.160112.fd21b415bb234d3bd1f10ae72e862f87d737ed0bdb8e1b181c5fdacea703dcf0.ed3e361cad^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"

**Comment by EbitFSE** [comment]
Buongiorno @NunzioAgfa abbiamo anche noi lo stesso problema. Potreste gentilmente indicarci la soluzione che avete adottato per l'encoding? Grazie mille

**Comment by giorgiotorchiana** [comment]
Buongiorno @NunzioAgfa, ho lo stesso problema: posso sapere come lo hai risolto ? 
Grazie mille

**Comment by NunzioAgfa** [comment]
abbiamo corretto un nostro errore nel codificare il messaggio in uscita
