### ISSUE TITLE
Servizio di validazione ERRORE: InvalidRequestContent

### ISSUE THREAD

**Issue by githubeht** [ministero-salute/it-fse-support#601]
Buongiorno,
l'invocazione del servizio di validazione:
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation/
attraverso il comando CURL da Mirth Connect restituisce una risposta con errore:

REQUEST
curl -X POST -H "Authorization: Bearer eyJ4NWMiOlsiTUlJRmF6Q0NBMU9nQXdJQkFnSVVNSGVRS1NTOGNlYjN5ZDhvaHBjbjErSzNPbHd3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TXpBNU1EVXhNelEwTURGYUZ3MHlOakE1TURVeE16UTBNREJhTUd3eEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVJzd0dRWURWUVFEREJKVE1TTXhNVEZUU1UxRlJGTlRVa3hEV0Znd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURGRkQ2RnpSWE14ZXhlMnlSM01odzZjM3NTc0xKUGdEcCtTWWdDVjZrR0VPL2Z4UlRqL1BoNUhpMUV5TS9jd3VCZzNlajcxR2hWU28zbkM4RWt6RzFKa1IyUThsVmYrV1FqUTlnS1FVZVI1L2dmMkY2OEhucTV4QnpoZUYwOXhFQ3dkTkJ6alZES1MyVnlmTkpNQVFoR0dEeFdpd0lsbEdKbVpQMFZpLzZKd2dGS2xlZXBrSW1CZDZ3OHhzRFFPWlRYSmRLaUJTVmhNdE5OTTlPdEoxMkJncnJEeXBWbVEyajNBbWhjWDM2bHNqS0ZQK2svYkl1UmYwRFkxY2tMb3J2Uk10dU9OTlJzTjFFYVA2M3AwcXRLb3BVQW1VZUVWZHhGT1Z5QlU2b2J1ZlRWVVV5SlZ5Y0xjbkYyVXZ0MUdtcWtKd1pwbEdta2ZIMktta09uWVB5dEFnTUJBQUdqZ2dFWU1JSUJGREFmQmdOVkhTTUVHREFXZ0JRV09ha2FCWW0zRHkyeU5lM0NDWnJGQTRNaVB6QVNCZ05WSFNBRUN6QUpNQWNHQlN0TUhRRUxNSUd0QmdOVkhSOEVnYVV3Z2FJd2daK2dnWnlnZ1ptR2daWm9kSFJ3Y3pvdkwyTmhjMjluWldsemRtbHNMbk52WjJWcExtbDBMMlZxWW1OaEwzQjFZbXhwWTNkbFlpOTNaV0prYVhOMEwyTmxjblJrYVhOMFAyTnRaRDFqY213bWFYTnpkV1Z5UFVOT0pUTkVRMEVyVFdsdWFYTjBaWEp2SzJSbGJHeGhLMU5oYkhWMFpTdFVaWE4wSlRKRFR5VXpSRTFwYm1semRHVnlieXRrWld4c1lTdFRZV3gxZEdVbE1rTkRKVE5FU1ZRd0hRWURWUjBPQkJZRUZLRDRIUmY5TWRFbXYwTlR5MEl2QisyS005amFNQTRHQTFVZER3RUIvd1FFQXdJR1FEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFHNVRNMkg5KzdkSk54N2FFZFl2NDllUkZLMWllNjRGSzY0R0R6UXg4V2dTWkx5dWcyb0tUeEtRcmRtYUIwcUpRQnh1eWJ2YVZ1TU5wZWhheXV5VE1UTmJUaXJTK1R0bmZjY2tYaEZOaU1qOGtaWTlBQThZSkdudXYva2pFVkNLSDdFaklpYXRhbnV4Mkh6UGxCdkk3Y1NjVWU2Vk5aU3E2SDBTVzlTVXhRcGU5K0VqbndyempqWTNRYWtPNDN1ZkhkdHhOYzdEZFpLa2Y5Njh3YWZMVkMvM0pPOXBocFBDd0pmOHFiNlpJcVBMbCtlaWF4WnBVTkxjbHFmRnBjZVllVWxpOTlpL2VtcDFaSWZaSTJCMnNKUGNCR3FBalcybEEzdHBUelVRRUc5ZkR3R0g0RlNEU0J2RElUOUhQdzRpZTVMdHNrMDh6ZGtEOWJqVzc2SklBcGtDa3BFVmpuL3B6MmRsZE0wZHJlNDB3TFF3d09OT2tyM1htazJ3SXNXUWtsWVRtcit0ZG1wQVFkanR2V1E4VEM4WHQ0Mk5MQXlMSXNBK2loS0RJSVM3SVRiMXY1TGJZcVZtQnZua1VucU1LUjA5M3BkdG5lUzMrWjVvQklMdEZBWDhhOVRLbDc5cmQ2Z3BPaGdQeHN1S2kvVHBhL0IrNUhSYnQzbkRXQVBNZkVVUnlvU0h2MHNHMzliVW44VmEzQzVBV2NHbVhSMkh2TFZ6ZmNiTDVxTVNBQ1RoRDhiZU40d1V3anE2SFlLcFhETW41SGxBc1ZNc0tpZmtiTTRBYTFTWm8xSjlWZUZ2czN0SGRKVkVacTZ3a2krTGdLamQ5ckF4Y3V4MldheTgyaFNpU283c3JGSEFDZVE0MUQxY3VWY0t4L3U2VWNhTXU1WFNMTisvWE5zcz0iXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJUTlRDU1Q4NVI0MUEzOTBYXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJpc3MiOiJhdXRoOiMxMTFTSU1FRFNTUkxDWFgiLCJleHAiOjE3MDcyMzgyMTUsImlhdCI6MTcwNzIzNDYxNSwianRpIjoiMTcwNzIzNDYxNDQ1NSJ9.Kn91ttocOyXUhuSqA5oGYsni3X8zAFIoKc2Aosseoh6HLKG8w9L1ehq0GjIDGINA6ihjHRaeV1Z6t4OPux_T8dqoj0WgHafysubFwpc_9DmPE39VXTTiq3Fw-II7yu3-BkADUyWmggXv2rogpIN5qgiidaYTCrPuEtarej-8kFo1fIvlrgr2goTzbo6vroYs8jXLUNnPceAJ5RVx6nROV2u_Gol4amVg4u6Xlwml8vclx-tWPoG1h7kBFDGCNYaJLbASxjrimaOkMo9PWxb3BwTgsHeoT-XJw_OA5KopEfZU9aIzF4mGEVwsnVvybCXCYK1nTuzzlTRJHj58zK-8kA" -H "FSE-JWT-Signature: eyJ4NWMiOlsiTUlJRmF6Q0NBMU9nQXdJQkFnSVVNSGVRS1NTOGNlYjN5ZDhvaHBjbjErSzNPbHd3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TXpBNU1EVXhNelEwTURGYUZ3MHlOakE1TURVeE16UTBNREJhTUd3eEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVJzd0dRWURWUVFEREJKVE1TTXhNVEZUU1UxRlJGTlRVa3hEV0Znd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURGRkQ2RnpSWE14ZXhlMnlSM01odzZjM3NTc0xKUGdEcCtTWWdDVjZrR0VPL2Z4UlRqL1BoNUhpMUV5TS9jd3VCZzNlajcxR2hWU28zbkM4RWt6RzFKa1IyUThsVmYrV1FqUTlnS1FVZVI1L2dmMkY2OEhucTV4QnpoZUYwOXhFQ3dkTkJ6alZES1MyVnlmTkpNQVFoR0dEeFdpd0lsbEdKbVpQMFZpLzZKd2dGS2xlZXBrSW1CZDZ3OHhzRFFPWlRYSmRLaUJTVmhNdE5OTTlPdEoxMkJncnJEeXBWbVEyajNBbWhjWDM2bHNqS0ZQK2svYkl1UmYwRFkxY2tMb3J2Uk10dU9OTlJzTjFFYVA2M3AwcXRLb3BVQW1VZUVWZHhGT1Z5QlU2b2J1ZlRWVVV5SlZ5Y0xjbkYyVXZ0MUdtcWtKd1pwbEdta2ZIMktta09uWVB5dEFnTUJBQUdqZ2dFWU1JSUJGREFmQmdOVkhTTUVHREFXZ0JRV09ha2FCWW0zRHkyeU5lM0NDWnJGQTRNaVB6QVNCZ05WSFNBRUN6QUpNQWNHQlN0TUhRRUxNSUd0QmdOVkhSOEVnYVV3Z2FJd2daK2dnWnlnZ1ptR2daWm9kSFJ3Y3pvdkwyTmhjMjluWldsemRtbHNMbk52WjJWcExtbDBMMlZxWW1OaEwzQjFZbXhwWTNkbFlpOTNaV0prYVhOMEwyTmxjblJrYVhOMFAyTnRaRDFqY213bWFYTnpkV1Z5UFVOT0pUTkVRMEVyVFdsdWFYTjBaWEp2SzJSbGJHeGhLMU5oYkhWMFpTdFVaWE4wSlRKRFR5VXpSRTFwYm1semRHVnlieXRrWld4c1lTdFRZV3gxZEdVbE1rTkRKVE5FU1ZRd0hRWURWUjBPQkJZRUZLRDRIUmY5TWRFbXYwTlR5MEl2QisyS005amFNQTRHQTFVZER3RUIvd1FFQXdJR1FEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFHNVRNMkg5KzdkSk54N2FFZFl2NDllUkZLMWllNjRGSzY0R0R6UXg4V2dTWkx5dWcyb0tUeEtRcmRtYUIwcUpRQnh1eWJ2YVZ1TU5wZWhheXV5VE1UTmJUaXJTK1R0bmZjY2tYaEZOaU1qOGtaWTlBQThZSkdudXYva2pFVkNLSDdFaklpYXRhbnV4Mkh6UGxCdkk3Y1NjVWU2Vk5aU3E2SDBTVzlTVXhRcGU5K0VqbndyempqWTNRYWtPNDN1ZkhkdHhOYzdEZFpLa2Y5Njh3YWZMVkMvM0pPOXBocFBDd0pmOHFiNlpJcVBMbCtlaWF4WnBVTkxjbHFmRnBjZVllVWxpOTlpL2VtcDFaSWZaSTJCMnNKUGNCR3FBalcybEEzdHBUelVRRUc5ZkR3R0g0RlNEU0J2RElUOUhQdzRpZTVMdHNrMDh6ZGtEOWJqVzc2SklBcGtDa3BFVmpuL3B6MmRsZE0wZHJlNDB3TFF3d09OT2tyM1htazJ3SXNXUWtsWVRtcit0ZG1wQVFkanR2V1E4VEM4WHQ0Mk5MQXlMSXNBK2loS0RJSVM3SVRiMXY1TGJZcVZtQnZua1VucU1LUjA5M3BkdG5lUzMrWjVvQklMdEZBWDhhOVRLbDc5cmQ2Z3BPaGdQeHN1S2kvVHBhL0IrNUhSYnQzbkRXQVBNZkVVUnlvU0h2MHNHMzliVW44VmEzQzVBV2NHbVhSMkh2TFZ6ZmNiTDVxTVNBQ1RoRDhiZU40d1V3anE2SFlLcFhETW41SGxBc1ZNc0tpZmtiTTRBYTFTWm8xSjlWZUZ2czN0SGRKVkVacTZ3a2krTGdLamQ5ckF4Y3V4MldheTgyaFNpU283c3JGSEFDZVE0MUQxY3VWY0t4L3U2VWNhTXU1WFNMTisvWE5zcz0iXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJUTlRDU1Q4NVI0MUEzOTBYXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImlzcyI6ImludGVncml0eTojMTExU0lNRURTU1JMQ1hYIiwibG9jYWxpdHkiOiJqd3QtbG9jYXRpb24iLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlcnNpb24iOiIxIiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb25lIExhemlvIiwic3ViamVjdF9vcmdhbml6YXRpb25faWQiOiIxMjAiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJwYXRpZW50X2NvbnNlbnQiOnRydWUsImFjdGlvbl9pZCI6IkNSRUFURSIsInJlc291cmNlX2hsN190eXBlIjoiKCcxMTUwMi0yXl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsInN1YmplY3RfYXBwbGljYXRpb25faWQiOiJzaWNsYW1tIiwiZXhwIjoxNzA3MjM4MjE1LCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlbmRvciI6InNpbWVkcyIsImlhdCI6MTcwNzIzNDYxNSwianRpIjoiMTcwNzIzNDYxNDQ1NSIsInBlcnNvbl9pZCI6IkNNTk1OTDU2UDY3QTM5ME1eXl4mYW1wOzIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZhbXA7SVNPIn0.gw-nTz3BuELJQvwk_kvzGNgPb8MgSZfi7m5QcwtNzs6h82p1gO7g2zDb4rwMgqnitAxrglU3h6F8QA2tFlF2ychsCKTMeYcEoZT0Qu_ZMxOvVRHsQKkWBi9VSzviaxOgIqIgg0z2CokCFk_T6NajbC9CqamnsWG7359MAICic5-sN6n6-9arqpPEk88ePcBM3Vr9aoU0TH6P0rYPkXe4Yfk_DXSEkxnKJvRCoGDtWR8YcXkhyIMRNU5YQ1L2DjDWbYfeYLmD0HwSJu8Z8kRZt1LVfnkLR0KCTpoSVc-HerSxWW4VlVNBoKx6q62NIWrL1DeRnOjqzrBBjyjH1rzIKg" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "requestBody={"healthDataFormat": "CDA", "mode": "ATTACHMENT", "activity": "VALIDATION",}"  -F "file=@C:\RC\FSE2.0\CDA_OK.pdf;type=application/pdf" http://localhost:9091/govway/rest/in/FSE/gateway/v1/documents/validation/ -o "C:\RC\FSE2.0\outFSE.txt"

RESPONSE
{"type":"https://govway.org/handling-errors/400/InvalidRequestContent.html","title":"InvalidRequestContent","status":400,"detail":"Request content not conform to API specification: Validation error(s) :\nAn error occurred when getting the body content from type 'multipart/form-data; boundary=------------------------f3f46e43aa31b034'.\ncom.fasterxml.jackson.core.JsonParseException: Unexpected character ('h' (code 104)): was expecting double-quote to start field name\n at [Source: (org.apache.commons.fileupload.MultipartStream$ItemInputStream); line: 1, column: 3] (code: 201)\n","govway_id":"30f99d59-c504-11ee-9fa8-005056ae7395"}

A disposizione per chiarimenti ed informazioni, in attesa di un vs. cortese riscontro.

Grazie

**Comment by vigliottim** [comment]
Buongiorno, 
analizzando la richiesta curl da lei effettuata è emerso un uso improprio delle virgolette.
Per verificare dove occorrono i singoli apici e dove quelli doppi, la invitiamo a consultare la documentazione al link:
https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#311-messaggio-di-richiesta-esempio-validation-con-attachment, dove è riportato un esempio di request valida.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto riscontri, procediamo alla chiusura del presente ticket. 
Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
