### ISSUE TITLE
Pubblicazione - Creazione: perché identificativoDoc é REQUIRED?

### ISSUE THREAD

**Issue by gsdefender** [ministero-salute/it-fse-support#602]
Salve, sto esaminando la documentazione del servizio di pubblicazione.
Nel corpo della richiesta del servizio di creazione ([punto 4.1](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#41-request)) trovo che identificativoDoc è REQUIRED.

identificativoDoc non dovrebbe essere assegnato a seguito dell'avvenuta pubblicazione, e quindi _non_ essere REQUIRED in questo scenario?
Noto la stessa problematica nel punto 8.1 (validazione e pubblicazione). Non ho visto se questa discrasia apparente si presenti anche in altri casi.

**Comment by vigliottim** [comment]
Buongiorno, l'_identificativoDoc_ è un parametro che viene valorizzato dall'utente nella request body in fase di invocazione, per identificare il documento da pubblicare. Per questo motivo si tratta di un parametro obbligatorio.
Rimaniamo a disposizione per chiarimenti.

**Comment by gsdefender** [comment]
Salve, mi spiego meglio. Nell'attuale flusso di pubblicazione di un nuovo documento (referti in formato FSE 2.0, pubblicazione secondo le modalità dell'FSE 1.0 con autenticazione tramite tessera sanitaria) il codice LOINC del documento viene _assegnato_ a seguito del superamento dei controlli di conformità sul PDF+XML: inizialmente viene assegnato un codice del tipo TEMP_[codice regione]_[numero progressivo]. La mia perplessità verte sul numero progressivo: ^0123456789. Se il progressivo è scelto dall'inviante, come sembra trasparire dalla documentazione e dalla sua risposta, non ci sono garanzie sul fatto che si stia scegliendo un valore già utilizzato da un altro documento inviato. Mi sto perdendo qualcosa?

**Comment by IStacchiotti** [comment]
Buongiorno,
Segnaliamo che la pubblicazione viene eseguita in produzione da parte del document repository, che stacca l'identificativoDoc associato al documento.
Da [affinity domain 2.5](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20interoperabilit%C3%A0/AffinityDomainItalia_v2-5_v20231212.pdf), l'identificativoDoc (XDSDocumentEntry.uniqueId) è obbligatorio e univoco a livello nazionale.
Specifichiamo inoltre che, in pubblicazione, vengono applicati dei controlli sul campo in questione: la chiamata non avrebbe esito positivo nel caso in cui fosse inviato un documento con identificativoDoc uguale a quello di un documento pubblicato in precedenza.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by gsdefender** [comment]
OK. Io mi sto ponendo nell'ottica di fornitore di software che genera e trasmette referti e che dovrà completare la certificazione della fase di pubblicazione, avendo ottenuta quella per la validazione.
Mi ha forse fuorviato la lettura della documentazione prima di aver guardato la lista dei test case e altre issue  (come [questa](https://github.com/ministero-salute/it-fse-support/issues/589) dove sembra che _in area test_ e quindi ai fini della certificazione l'identificativoDoc sia sostanzialmente arbitrario, non esistendo l'equivalente del repository locale (che invece nell'area test FSE 1.0 esiste) e si contatti direttamente il gateway chiedendo il servizio di pubblicazione, mentre _in area produzione_ si contatta il repository locale, secondo API che dovranno ancora essere pubblicate.
Se mi date conferma possiamo chiudere l'issue. Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, 
Le confermiamo invece che in ambiente di produzione, sarà necessario predisporre l'integrazione tra il document repository e il FSE 2.0, tramite le API di pubblicazione, di cui saranno resi disponibili gli endpoint tramite opportuni canali.
Restiamo a disposizione in caso ulteriore supporto.
Grazie
