### ISSUE TITLE
Errore sintattico validazione cda LAB

### ISSUE THREAD

**Issue by Itamedical** [ministero-salute/it-fse-support#603]
Buongiorno,

scriviamo per chiedere supporto circa la risposta che mi viene fornita dal Gateway (allegato .log e riportata qui di seguito): 

{"traceID":"c3f9b9bba335ec96","spanID":"c3f9b9bba335ec96","type"
:"/msg/syntax","title":"Errore di sintassi.","detail":"Error whi
le executing validation on xsd schema","status":400,"instance":"
/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2
.120.4.4.9235223109f01bc97b8a054d7b6f0bf66709a19485e84dfc0b71e4c
309ee3595.d09c66a023^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Il sistema indica la presenza di un errore generico di sintassi nell'.xml, abbiamo ricontrollato la struttura e ci sembra che tutte le sezioni (obbligatorie) siano state valorizzate nel modo corretto, avete gentilmente modo di effettuare un controllo incrociato per verificare un eventuale difetto nella struttura che potrebbe esserci sfuggito (allego .xml) ?

Ringrazio del supporto e auguro una buona giornata,

[cda.zip](https://github.com/ministero-salute/it-fse-support/files/14207888/cda.zip)
[runGTWHttpsCall.log](https://github.com/ministero-salute/it-fse-support/files/14207892/runGTWHttpsCall.log)

**Comment by vigliottim** [comment]
Buongiorno,
il file cda.xml allegato al pdf non risulta ben formato. In particolare, è presente un doppio tag di chiusura </section> alle righe 1219-1221:
<img width="295" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/386605da-bf70-4b19-ab85-2c3edf80f61e">
La invitiamo a rimuoverne uno e riprovare. 
Restiamo in attesa di un suo gentile riscontro.

**Comment by Itamedical** [comment]
Buongiorno,

confermo che rimuovendo il tag consigliato l'errore non si ripresenta, ringrazio del supporto. Avrei un'ulteriore domanda: nel caso in cui l'utente non inserisca un valore nel nostro gestionale, nel campo xml della sezione <entry>/<act>/<entryRelationship>/<value> l'attributo 'value' non verrà valorizzato, riporto di seguito un esempio:

<entryRelationship typeCode="COMP">
     <observation moodCode="EVN" classCode="OBS">
<code code="18722-9" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="TEMPO DI LIQUEFAZIONE"/>
		<statusCode code="completed"/>
		<effectiveTime value="20190613100900"/>
		<value xsi:type="PQ" value="" unit="min"/>
    </observation>
</entryRelationship>

Il sistema in questo caso ritorna l'errore:

ERROR: -1,-1 cvc-datatype-valid.1.2.3: '' is not a valid value of union type 'real'.,
ERROR: -1,-1 cvc-attribute.3: The value '' of attribute 'value' on element 'value' is not valid with respect to its type, 'real'.,

La domanda che pongo è: che valore posso far inserire al gestionale nell'attributo value, nel caso in cui l'operatore non compili questo campo, in modo che il sistema non ritorni questo errore? Ho provato inserendo '-' o 'null' ma l'errore è il medesimo e inserire 0 non penso sia opportuno.

Ringrazio del supporto, 

Cordiali saluti.

**Comment by vigliottim** [comment]
Buonasera, da specifiche HL7 la valorizzazione del risultato dell'osservazione diventa obbligatoria nel caso in cui lo _statusCode_ dell'observation è "completed". 
Pertanto, se presente l'elemento _value_, è obbligatorio valorizzare l'attributo _value_ conformemente al corrispondente datatype, riportando, quindi, il risultato rilevato dell'osservazione effettuata.
Restiamo a disposizione per chiarimenti.
