### ISSUE TITLE
Errore nella creazione del requestboby

### ISSUE THREAD

**Issue by simeds** [ministero-salute/it-fse-support#605]
Salve,
abbiamo difficoltà a capire la corretta sintassi da usare nella composizione del requestboby.

Questo è quello che inviamo con CURL:

curl -X POST 
-H "Authorization: Bearer eyJ4NWMiOlsiTUlJRmF6Q..." 
-H "FSE-JWT-Signature: eyJ4NWMiOlsiTUlJRmF6Q0NB..." 
-H "accept: application/json" 
-H "Content-Type: multipart/form-data" 
-F "requestBody={"healthDataFormat": "CDA", "mode": "ATTACHMENT", "activity": "VALIDATION"}"  
-F "file=@C:\RC\FSE2.0\CDA_OK.pdf;type=application/pdf" http://localhost:9091/govway/rest/in/FSE/gateway/v1/documents/validation/

e otteniamo l'indicazione che prima della 'h' di healtDataFormat vuole una  double-quote 

{"type":"https://govway.org/handling-errors/400/InvalidRequestContent.html","title":"InvalidRequestContent","status":400,"detail":"Request content not conform to API specification: Validation error(s) :\nAn error occurred when getting the body content from type 'multipart/form-data; boundary=------------------------2b73ee93e73aae90'.\ncom.fasterxml.jackson.core.JsonParseException: Unexpected character ('h' (code 104)): was expecting double-quote to start field name\n at [Source: (org.apache.commons.fileupload.MultipartStream$ItemInputStream); line: 1, column: 3] (code: 201)\n","govway_id":"60eeca12-c671-11ee-9fa8-005056ae7395"}

Grazie per l'aiuto.

Simeds srl.

**Comment by vigliottim** [comment]
Buongiorno, 
analizzando la richiesta curl da lei effettuata è emerso un uso improprio delle virgolette.
Per verificare dove occorrono i singoli apici e dove quelli doppi, la invitiamo a consultare la documentazione al link:
https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#311-messaggio-di-richiesta-esempio-validation-con-attachment
dove è riportato un esempio di request valida.
Rimaniamo a disposizione per ulteriori chiarimenti.
