### ISSUE TITLE
Errore Validazione 400

### ISSUE THREAD

**Issue by sandroaresu23** [ministero-salute/it-fse-support#608]
Salve, 
vorrei sapere se è cambiato qualcosa nel validatore di test in quanto da qualche giorno il validatore mi restituisce il seguente errore, anche su documenti già validati in precedenza:
{
    "traceID": "ed02b295896e0bb1",
    "spanID": "ed02b295896e0bb1",
    "type": "/msg/cda-element",
    "title": "Errore in fase di estrazione del CDA.",
    "detail": "Error while extracting CDA from PDF document",
    "status": 400,
    "instance": "/cda-extraction",
    "workflowInstanceId": "UNKNOWN_WORKFLOW_ID"
}

Vi allego anche il file pdf già validato in precedenza.
[VALIDAZIONE_CDA2_VPS_CT1.pdf](https://github.com/ministero-salute/it-fse-support/files/14220442/VALIDAZIONE_CDA2_VPS_CT1.pdf)

Potete cortesemente verificare?
Grazie anticipatamente

Saluti

**Comment by LucaRogledi** [comment]
Buongiorno,
Dalle verifiche è emerso che il cda iniettato nel pdf non segue la naming convention stabilita.
Segnaliamo che il cda iniettato nel pdf deve essere nominato come "cda.xml" come indicato in
[documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#2-contesto-di-riferimento).
Restiamo a disposizione in caso di ulteriore supporto.
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto. Grazie
