### ISSUE TITLE
Test 10 KO LDO attributo "code" 'administrativeGenderCode'

### ISSUE THREAD

**Issue by dinelliascom** [ministero-salute/it-fse-support#61]
Per quanto riguarda la generazione dell'errore in seguito ad una valorizzazione errata dell'elemento nel caso del test 10 LDO qualunque valore viene assegnato all'attributo "code" dell'elemento 
`ClinicalDocument/recordTarget/patientRole/patient/administrativeGenderCode `
la validazione risulta sempre corretta.

**Comment by pFonziSogei** [comment]
Salve, abbiamo introdotto una modifica che dovrebbe risolvere il problema. Può riprovare?

**Comment by dinelliascom** [comment]
Salve, adesso mi restituisce sempre questo errore, in tutti i cda anche quelli che precedentemente sono stati validati correttamente:
`{"traceID":"d70a6ff279d4bb8e","spanID":"d70a6ff279d4bb8e","type":"/msg/vocabulary","title":"Errore vocabolario.","detail":"È stata trovata almeno una versione non gestita di un dizionario: [2.16.840.1.113883.5.25 v1]","status":400,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.3.120915.4.4.32.11072433273.11.24aab23e81715b12cde8e57124f7bd6e9d3893e99899585f0a138148a086e1c7.e23315700c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

**Comment by dinelliascom** [comment]
Adesso il controllo funziona per code="M" ("maschio") e "F" ("femmina") con il codice "U" ("undifferentiated") mi restituisce il seguente errore: 
`{"traceID":"d1e937c281f8039a","spanID":"d1e937c281f8039a","type":"/msg/vocabulary","title":"Errore vocabolario.","detail":"Almeno uno dei seguenti vocaboli non è censito: [CodeSystem: 2.16.840.1.113883.5.1 v2.1.0, Codes: U]","status":400,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.3.120915.4.4.32.11072433273.11.24aab23e81715b12cde8e57124f7bd6e9d3893e99899585f0a138148a086e1c7.f1438d1610^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

**Comment by Ser-ena** [comment]
Salve, per il caso "undifferentiated" sarebbe necessario inserire il codice "UN".
Potrebbe cortesemente riprovare?

**Comment by dinelliascom** [comment]
Si adesso è corretto. Grazie per il vostro supporto.
