### ISSUE TITLE
Valorizzare Correttamente l'attributo "assigningAuthorityName" del nodo "ClinicalDocument.recordTarget.patientRole.id"con OID 2.16.840.1.113883.2.9.4.3.2

### ISSUE THREAD

**Issue by Saxos-Simone** [ministero-salute/it-fse-support#610]
Nel _CDA_ valido di esempio che fornite (https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/RSA.xml) l'attributo _**assigningAuthorityName**_ del nodo _**ClinicalDocument.recordTarget.patientRole.id**_ con _OID_ "_**2.16.840.1.113883.2.9.4.3.2**_" è valorizzato come "**MEF**" (come era in _FSE1.0_), nel documento [HL7IT-IG_CDA2_RSA-v1.1-S.pdf](http://www.hl7italia.it/sites/default/files/Hl7/SuperUser/docs/pubblicati/IG-CDA2-RSA/1.1/HL7IT-IG_CDA2_RSA-v1.1-S.pdf) però è scritto che l'attributo _**assigningAuthorityName**_  dello stesso nodo deve essere valorizzato come "**Ministero Economia e Finanze**", pertanto mi chiedo se sia indifferente o meno valorizzarlo come "**MEF**" piuttosto che "**Ministero Economia e Finanze**".

**Comment by vigliottim** [comment]
Buonasera, 
le confermiamo che l'attributo _assigningAuthorityName_ del _ClinicalDocument.recordTarget.patientRole.id_ può essere valorizzato in entrambi i modi.
Restiamo a disposizione per ulteriori chiarimenti.

**Comment by Saxos-Simone** [comment]
Grazie tante per il chiarimento.
