### ISSUE TITLE
Errore in fase di accreditamento RSA  (caso di test 8)

### ISSUE THREAD

**Issue by DSantonastaso** [ministero-salute/it-fse-support#614]
Buonasera,
Se ho inteso bene il test serve per verificare cosa succede se il COMUNE di RESIDENZA dell’assistito risulta vuoto.

Il nostro sistema NON ha tolto il TAG ClinicalDocument/recordTarget/patientRole/addr/city ma semplicemente lo ha lasciato vuoto:
```
<addr use="HP">
<country>100</country>
                <county/>
                <city/>
                <censusTract/>
                <postalCode/>
                <streetAddressLine/>
</addr>
```

In questo caso il gateway ci ha risposto validando il referto.

E’ necessario prevedere un test dove il tag relativo agli indirizzi venga completamente eliminato?

Simulando un CDA senza tag la risposta del gateway sarebbe questa:

{"traceID":"9189bcff11fd57c3","spanID":"9189bcff11fd57c3","type":"/msg/semantic","title":"Errore semantico.","detail":"[ERRORE-11| L'elemento ClinicalDocument/recordTarget/patientRole/addr DEVE riportare i sotto-elementi 'country', 'city' e 'streetAddressLine' ]","status":422,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.30.4.4.fa2a0a21161dd2a1d63f2f8e6b5783db19749ef10493400f374d2f2cca149581.2a84fded5e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

E' necessario prevedere anche questa casistica?

**Comment by vigliottim** [comment]
Buongiorno, 
Il caso da test specificato, come riportato in [documentazione](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/6-Lettera%20di%20Dimissione%20Ospedaliera/CDA2_Lettera%20di%20Dimissione%20Ospedaliera_KO.xlsx), prevede l'inserimento dell'indirizzo senza l'indicazione del comune di residenza del paziente.
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/31137648-309d-46fb-8bbf-895a6b5189b1)
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/e761bdf4-95c6-40b2-aa9c-2fb0b74f8203)
Pertanto, per superare il test, dovreste eliminare unicamente il tag _ClinicalDocument/recordTarget/patientRole/addr/city_ e verificare di ottenere un errore semantico.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by DSantonastaso** [comment]
Buongiorno!
Grazie del feed-back,
Ho rifatto il caso e aperto la PR 1198 https://github.com/ministero-salute/it-fse-accreditamento/pull/1198.

Grazie

**Comment by vigliottim** [comment]
Grazie per il feedback. 
La sua PR è stata presa in carico. Riceverà aggiornamenti via e-mail con l'esito delle elaborazioni.
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per altre richieste di supporto.
