### ISSUE TITLE
Errore 422 in fase di validazione

### ISSUE THREAD

**Issue by penny66** [ministero-salute/it-fse-support#616]
Buonasera, in fase di validazione ricevo il seguente errore:

Response Content: {
"traceID":"2901f74be3d1925d","spanID":"2901f74be3d1925d",
"type":"/msg/semantic",
"title":"Errore semantico.",
"detail":"Error while executing validation on sch schematron",
"status":422,
"instance":"/validation/error",
"workflowInstanceId":"2.16.840.1.113883.2.9.2.150.4.4.035b7a71bced6766ecf4945c232c37a63a2874e6f285e864461fa79b133153ec.1170ac228b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
allego file pdf con cda

non riesco a capire dov'è l'errore
[cda_ok.pdf](https://github.com/ministero-salute/it-fse-support/files/14247712/cda_ok.pdf)
[cda.zip](https://github.com/ministero-salute/it-fse-support/files/14247773/cda.zip)

**Comment by ponsilva** [comment]
Buongiorno,
mi inserisco in questo thread perché in alcuni test avevo incontrato un errore simile.

L'errore generico
"Error while executing validation on sch schematron"
può essere causato da un encoding non corretto del CDA2.

L'encoding previsto e accettato per CDA2 deve essere UTF-8
Se nel CDA2 sono usati altri encoding (ANSI, UTF-8-BOM, ...) si può ricevere l'errore

**Comment by vigliottim** [comment]
Buongiorno, confermiamo quanto riportato da @ponsilva, che ringraziamo.
Come mostrato nello screen di seguito, il cda allegato è in formato in _UTF-8 BOM_, anziché in _UTF-8_.

<img width="358" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/cfde6114-7114-476d-b5c8-497c35342802">

Potreste cortesemente eseguire questa correzione e riprovare? Grazie.

**Comment by penny66** [comment]
grazie ha funzionato
