### ISSUE TITLE
Accreditamento soluzione EMOLIFE

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#617]
Buongiorno,
volevamo notificare il caricamento completato dei test case per la soluzione EMOLIFE :

[ministero-salute/it-fse-accreditamento#1162](https://github.com/ministero-salute/it-fse-accreditamento/pull/1200)

Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, la ringraziamo per la notifica.
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per ulteriori richieste di supporto.
