### ISSUE TITLE
Accreditamento soluzione EMONET

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#618]
Buongiorno,
volevamo notificare il caricamento completato dei test case per la soluzione EMONET :

(https://github.com/ministero-salute/it-fse-accreditamento/pull/1201)

Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, la ringraziamo per la notifica.
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per ulteriori richieste di supporto.
