### ISSUE TITLE
Valorizzazione dei dati obbligatori dell'indirizzo paziente in caso manchino

### ISSUE THREAD

**Issue by fabiodap** [ministero-salute/it-fse-support#619]
Buongiorno,

non so se sia l'ambito giusto questo per porre questa domanda.

In molti siti le anagrafiche di molti pazienti mancano di alcuni dati che per il CDA sono obbligatori.
Si parla del CDA di Radiologia.

Per esempio per quanto riguarda l'indirizzo di Residenza del Paziente.
Il tag 'addr' nel suo complesso è opzionale, ma alcuni dei suoi sotto-tag no.

La documentazione di HL7 Italia a riguardo dice:

_4.1.12.1.1 Indirizzo del paziente 'addr'
Il tag 'addr' è OPZIONALE ed è utilizzato per codificare l’indirizzo del paziente. Se presente all’interno del seguente tag PUÒ essere inserito l’indirizzo di residenza, domicilio o l’indirizzo temporaneo indicato dal paziente.

La struttura del tag <addr> prevede:
.......
un tag 'streetAddressLine' identifica l’indirizzo di residenza o domicilio o indirizzo temporaneo del paziente. L’elemento è OBBLIGATORIO._

Nel caso questo dato, il 'streetAddressLine', non sia valorizzato sull'anagrafica è possibile comunque valorizzarlo con un  nullFlavor?
La documentazione non dà nessuna indicazione a riguardo.

Ringraziandovi in anticipo,
porgo cordiali saluti.

Saluti,
Fabio

**Comment by ponsilva** [comment]
Buongiorno, 
a me risulta che l'elemento addr sia opzionale, ad esempio per il Referto Medicina Lab la specifica è questa

![image](https://github.com/ministero-salute/it-fse-support/assets/44020426/47d017c6-e32d-4d68-912b-648a3d8482ea)

In quale specifica compare l'obbligatorietà per l'indirizzo del paziente?

Mi sarebbe utile saperlo per poter fare dei controlli.
Grazie!

**Comment by fabiodap** [comment]
L'indirizzo nel suo insieme è opzionale.
Ma se valorizzato alcuni dei suoi tag sono obbligatori.

Il docuemento è: 
Implementation Guide
Clinical Document Architecture (CDA) Rel. 2
Referto di Radiologia

Qui l'estratto della documentazione:

_4.1.12.1.1 Indirizzo del paziente <addr>
Il tag <addr> è OPZIONALE ed è utilizzato per codificare l’indirizzo del paziente. Se presente all’interno del seguente tag PUÒ essere inserito l’indirizzo di residenza, domicilio o l’indirizzo temporaneo indicato dal paziente.

La struttura del tag <addr> prevede:
• un tag <country> identifica il codice ISTAT dello stato di residenza o domicilio o indirizzo temporaneo del paziente. L’elemento è OBBLIGATORIO.
• un tag <state> identifica il codice della regione; di residenza o domicilio o indirizzo temporaneo del paziente. L’elemento è OPZIONALE. 665
• un tag <county> identifica la sigla automobilistica della provincia; di residenza o domicilio o indirizzo temporaneo del paziente. L’elemento è OPZIONALE.
• un tag <city> identifica la descrizione del comune di residenza o domicilio o indirizzo temporaneo del paziente. L’elemento è OBBLIGATORIO.
• un tag <censusTract> identifica il codice ISTAT del comune di residenza o domicilio o 670 indirizzo temporaneo del paziente. L’elemento è OPZIONALE
• un tag <postalCode> identifica il CAP di residenza o domicilio o indirizzo temporaneo del paziente. L’elemento è OPZIONALE
• un tag <streetAddressLine> identifica l’indirizzo di residenza o domicilio o indirizzo temporaneo del paziente. L’elemento è OBBLIGATORIO._

Per tanto come si vede se viene inserito l'<addr> alcuni dei suoi sotto-tag sono obbligatori.
La domanda è se è possibile valorizzarli con un nullflavor in caso non siano disponibili.

Saluti,
Fabio

**Comment by vigliottim** [comment]
Buongiorno, le confermiamo che può procedere come ha fatto. 
Chiudiamo il presente ticket e rimaniamo a disposizione per ulteriori richieste di supporto. 
Grazie.
