### ISSUE TITLE
Error 400 - InvalidRequestContent

### ISSUE THREAD

**Issue by mrepu** [ministero-salute/it-fse-support#62]
Ciao, sono Marina Epure di Werfen. Sto provando a fare una chiamata al servizio di validazione mediante una classe java ma restituisce l'errore "400 InvalidRequestContent". Purtroppo non riesco ad ottenere maggiori informazioni su quale possa essere il motivo dell'errore, sarebbe possibile controllare se la forma della request è corretta o meno?

GovWay-Transaction-ID 6a00591b-9649-11ed-b21d-005056ae54fa

Grazie

**Comment by pFonziSogei** [comment]
Salve, 

da una prima analisi sembrerebbe mancare "Content-Type: application/json" nell'header della request (associato all'attributo "requestBody")

**Comment by mrepu** [comment]
Salve,
Potrebbe mostrarmi cosa intende? Ho fatto diverse prove con risultato sempre negativo.

prova 1: aggiunta Content-Type in corrispondenza dell'attributo requestBody
GovWay-Transaction-ID 043200e4-9e0e-11ed-b7ba-005056ae54fa

prova 2: aggiunto anche nel header 
GovWay-Transaction-ID 1e1edb02-9e0f-11ed-84b0-005056ae7395


Eseguendo la chiamata con Postman non c'è la sezione Content-Type:application/json 

POSTMAN
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="requestBody"

{"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VERIFICA"}
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="/C:/Work/it-fse-gtw-tools-main/pdf-generator/target/output.pdf"
Content-Type: application/pdf

(data)
----WebKitFormBoundary7MA4YWxkTrZu0gW


e con POSTMAN la chiamate hanno successo e riceviamo la risposta attesa

Potrebbe fornirmi un esempio o qualche informazione in più?

Grazie

**Comment by mrepu** [comment]
Mi trovo a dover sollecitare una risposta in quanto questo problema è bloccante...

**Comment by IStacchiotti** [comment]
Buon pomeriggio, nella request fornita non è corretta la posizione dell'elemento "Content-Type: application/json;" che risulta essere posizionato sotto il JSON del requestBody. In questo modo l'elemento verrà preso come parte del contenuto del requestBody
