### ISSUE TITLE
Accreditamento Validazione RSA: Caso di Test 3 OK

### ISSUE THREAD

**Issue by fabiodap** [ministero-salute/it-fse-support#621]
Buongiorno,

riguardo al test in oggetto il caso viene descritto cosi:

_Il referto contiene, oltre alle sezioni obbligatorie:
-	“Prestazioni”, descrive le prestazioni effettivamente eseguite e le procedure operative di esame.
-	“Referto”, descrive quanto emerso nel corso della/e prestazione/i, riporta quindi al proprio interno una descrizione delle valutazioni del medico e dell’esito della prestazione.

E deve contenere la seguente sezione opzionale:
-	“Quesito Diagnostico”, rappresenta la diagnosi già accertata o sospettata oppure il sintomo prevalente. Serve allo specialista per conoscere il motivo della richiesta dell’esame allo scopo di formulare delle risposte clinicamente precise al paziente o al medico che ha prescritto l’accertamento.  
-	“Confronto con precedenti esami eseguiti”, riporta un confronto tra quanto emerso nel corso di precedenti esami eseguiti e quanto rilevato nel corso della/e procedura/e oggetto del referto.
-	“Diagnosi”, rappresenta la conferma o la confutazione del sospetto diagnostico.
-	“Conclusioni”, riporta la valutazione conclusiva redatta dal medico specialista e generalmente destinata al medico richiedente.
-	“Accertamenti e controlli consigliati”, riporta le prestazioni che il medico specialista ritiene opportuno consigliare al paziente.
-	“Terapia Farmacologica Consigliata”, riporta le terapie che il medico specialista ritiene opportuno consigliare al paziente a seguito della prestazione._

La domanda è: cosa significa "E deve contenere la seguente sezione opzionale"?

Una di quelle elencate? O tutte quelle elencate?

Il ns. applicativo non gestisce per esempio il "Confronto con precedenti esami eseguiti" o la "Terapia Farmacologica Consigliata".

Saluti,
Fabio

**Comment by vigliottim** [comment]
Buongiorno, 
le seguenti sezioni relative al Caso di Test 3 per RSA: 

- “Quesito Diagnostico”
- “Confronto con precedenti esami eseguiti”
- “Diagnosi”
- “Conclusioni”
- “Terapia Farmacologica Consigliata”

sono opzionali secondo le Linee Guida HL7 Italia ma risultano obbligatorie per lo specifico caso di test in esame, come riportato nell'excel [CDA2_Referto_Specialistica_Ambulatoriale_OK.xlsx](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/7-Referto%20Specialistico%20Ambulatoriale/CDA2_Referto_Specialistica_Ambulatoriale_OK.xlsx): 

![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/0dff2090-9bc8-412a-92b9-4832c74cd5fc)

Qualora non fosse possibile inserire tali sezioni, si può definire il caso di test "Non Applicabile".
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by fabiodap** [comment]
grazie mille.
Saluti,
Fabio

**Comment by vigliottim** [comment]
Grazie a lei per la segnalazione.
Procediamo alla chiusura del presente ticket e rimaniamo a disposizione per ulteriori richieste di supporto.
