### ISSUE TITLE
Gestione risultati precedenti dei risultati correnti

### ISSUE THREAD

**Issue by Furbessem** [ministero-salute/it-fse-support#622]
Buongiorno a tutti,
 vi pongo una domanda sul posizionamento di risultati clinici precedenti nel xmlcda di Laboratorio.
Se un cliente richiede la stampa di
 "Risultati clinici precedenti dei Risultati clinici della richiesta corrente"
 è corretto utilizzare i nodi  "observation/entryRelationship" typecode REFR in modo come indicato qui di seguito ?
 
![image](https://github.com/ministero-salute/it-fse-support/assets/6109634/a1b0a3c6-1226-4db9-b441-a00ee3199c5d)

I campi sono indicati nel documento IHE_LAB_TF_Rev6.0_Vol3_FT_2015-07-14.pdf a pagina 63 sez 2.3.5.10
Grazie in anticipo
Stefano.

**Comment by vigliottim** [comment]
Buongiorno, le confermiamo che è possibile riportare tante _entryRelationship/observation_ con _typeCode=REFR_ all'interno della _entry/act_ strutturato come nell'immagine da voi allegata.
Restiamo a disposizione per ulteriori chiarimenti.

**Comment by Furbessem** [comment]
Grazie !
Buon lavoro
Stefano.

**Comment by Furbessem** [comment]
Chiudo
S.
