### ISSUE TITLE
Verifica tripletta da usare per i documenti

### ISSUE THREAD

**Issue by dmonti76** [ministero-salute/it-fse-support#624]
Buongiorno,
ci segnalano problemi nella verifica della tripletta con cui inviamo i documenti ai repository regionali.
Come da mail di certificazione stiamo usando Vendor:[InterSystems_Italia_S.r.l] con gli _ mentre da prove informali parrebbe che la chiave corretta sia senza _ ma con gli spazi.
Potreste cortesemente verificare e darci riscontro su quali sono le chiavi esatte da usare per i documenti prodotti dal nostro prodotto Trakcare versione ITXX?
Grazie mille,
Daniele Monti

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura del presente ticket. 
Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto. 
Grazie.
