### ISSUE TITLE
Probabile errore in schematron schematron_VPS_v3.5.sch

### ISSUE THREAD

**Issue by MarcoKnezevichInsiel** [ministero-salute/it-fse-support#626]
Buongiorno,

a seguito di un errore in cui siamo incappati nelle pubblicazione di un documento di Pronto Soccorso (VPS) ci siamo accorti di un probabile errore nello schematron [schematron_VPS_v3.5.sch](https://github.com/ministero-salute/it-fse-catalogs/blob/main/schematron/schematron_VPS_v3.5.sch).

Nel documento relativo alla [produzione del CDA2](http://www.hl7italia.it/sites/default/files/Hl7/SuperUser/docs/pubblicati/IG-CDA2-VPS/1.1.1/HL7IT-IG_CDA2_VPS-v1.1.1-S.pdf) per il VPS, nel paragrafo 3.1.15 a pagina 44 nel punto CONF-VPS-46 viene indicato che i campi `id` e `name` devono essere popolati obbligatoriamente.

Nello schematron [schematron_VPS_v3.5.sch](https://github.com/ministero-salute/it-fse-catalogs/blob/main/schematron/schematron_VPS_v3.5.sch)  la regola relativa a tale punto alla riga 162 (ERRORE-24) verifica solo che il campo `name `sia presente ma non che sia popolato, un CDA2 così fatto

```
...
<representedCustodianOrganization>
       <id assigningAuthorityName="Ministero della Salute" root="2.16.840.1.113883.2.9.4.1.1" extension="060205"/>
       <name/>
</representedCustodianOrganization>
...
```

passa la validazione dello schemtron ma non è conforme alle specifiche CDA2.

**Comment by vigliottim** [comment]
Buongiorno,
dal momento che semanticamente non è possibile applicare un controllo sul contenuto di un elemento di tipo stringa, lo schematron effettua il controllo solo sulla presenza dell'elemento. 
Dovrà essere l'applicativo a verificare che l'elemento non sia associato a nessuna valorizzazione.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto riscontri, il presente ticket viene chiuso. 
Si può procedere alla riapertura nel caso in cui abbia bisogno di ulteriore supporto. 
Grazie.
