### ISSUE TITLE
Accreditamento nuova tipologia CDA (RSA) su Prodotto già accreditato per altre tipologie (nella fattispecie RAD)

### ISSUE THREAD

**Issue by fabiodap** [ministero-salute/it-fse-support#627]
Buongiorno,

al link: https://github.com/ministero-salute/it-fse-accreditamento#nuova-tipologia-documentale-per-applicativo-gi%C3%A0-presente-nella-lista-dei-software-convalidati

si legge quanto segue:

_Nuova tipologia documentale per applicativo già presente nella Lista dei software convalidati
Nel caso un applicativo abbia superato la Fase 1 per una particolare tipologia documentale (per es. LDO) e il fornitore sottometta una nuova richiesta di accreditamento per un’altra tipologia documentale (per es. RSA), l’applicativo ripeterà l’intera Fase 1 per le due tipologie documentali.

I fornitori dovranno sottomettere una nuova pull request contenente tutti i casi di test (e relativo data.json) eseguiti per le due tipologie documentali ( LDO+RSA ).

All’interno della Lista dei software convalidati la soluzione applicativa sarà riportata due volte: nella prima riga si riporterà l’esito relativo al LDO, nella seconda l’esito relativo a LDO, RSA.

Ai fini del conteggio dei documenti trasmessi dalle Regioni/PA si terrà presente la data di conclusione della Fase 1 di ciascuna tipologia documentale._

Per evitare di rifare il lavoro 2 volte, chiedo una precisazione:

Per la tipologia già accreditata (RAD) vanno ri-utilizzati i FILES PDF, le entry nel file data.json e le entry nella checklist.xslx generati per il precedente accreditamento?

Oppure i test  vanno ri-eseguiti con di conseguenza nuove entry nel data.json, nuove entry (traceid, timestamp, workflowinstanceid) e nuovi files PDF?

Saluti,
Fabio

**Comment by IStacchiotti** [comment]
Buonasera, nel momento in cui si aggiunge una nuova tipologia documentale in seguito al conseguimento della validazione per un diverso CDA, è necessario ripetere i casi di test per i quali è stato già conseguito l'accreditamento.

Per velocizzare il processo di accreditamento, consigliamo di sottomettere fin dall'inizio la checklist compilata per tutti i cda gestiti dall'applicativo per cui si intende accreditarsi. Rimaniamo a disposizione per chiarimenti, grazie

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura del presente ticket. 
Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto. 
Grazie.
