### ISSUE TITLE
Diagrammi non raggiungibili

### ISSUE THREAD

**Issue by marsardit** [ministero-salute/it-fse-support#628]
Buongiorno, si segnala che i diagrammi richiamati all'interno delle specifiche in https://github.com/ministero-salute/it-fse-support/tree/main/doc, in particolare per integrazione-gateway e middleware-regionale, non sono raggiungibili.

**Comment by vigliottim** [comment]
Buongiorno, al link che ci ha fornito è presente la documentazione con diagrammi sequence allegati come immagini. 
Ci può confermare che il problema è che non riesce a visualizzare correttamente le immagini dei diagrammi? 
In tal caso la invitiamo a cambiare browser o scaricarle direttamente dalla cartella img:
<img width="210" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/15816d27-f3f9-4a53-a562-07c8de640096">
<img width="685" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/7dcfa82f-4f6a-4641-bf90-e2636a962528">
Grazie.

**Comment by marsardit** [comment]
Buongiorno,
ho provato con vari browser (chrome, Edge , firefox), vedo i link ma le immagini non ci sono
***@***.***
Saluti

Da: Michela Vigliotti ***@***.***>
Inviato: mercoledì 21 febbraio 2024 10:00
A: ministero-salute/it-fse-support ***@***.***>
Cc: Marino Congiu ***@***.***>; Author ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Diagrammi non raggiungibili (Issue #628)


Buongiorno, al link che ci ha fornito è presente la documentazione con diagrammi sequence allegati come immagini.
Ci può confermare che il problema è che non riesce a visualizzare correttamente le immagini dei diagrammi?
In tal caso la invitiamo a cambiare browser o scaricarle direttamente dalla cartella img:
image.png (view on web)<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fministero-salute%2Fit-fse-support%2Fassets%2F134372089%2F15816d27-f3f9-4a53-a562-07c8de640096&e=6df20d48&h=730d96f1&f=y&p=n>
image.png (view on web)<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fministero-salute%2Fit-fse-support%2Fassets%2F134372089%2F7dcfa82f-4f6a-4641-bf90-e2636a962528&e=6df20d48&h=6f43bd28&f=y&p=n>
Grazie.

—
Reply to this email directly, view it on GitHub<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fministero-salute%2Fit-fse-support%2Fissues%2F628%23issuecomment-1956178445&e=6df20d48&h=62853975&f=y&p=n>, or unsubscribe<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA2OD7HWJBFURIMATR3MCQEDYUWZR3AVCNFSM6AAAAABDSQYFDKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNJWGE3TQNBUGU&e=6df20d48&h=41c852d5&f=y&p=n>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

--
Messaggio analizzato da Libraesva ESG.
Segnala come spam.<http://mxer2.regione.sardegna.it/action/001C04008C.A62EF/learn-spam>
Mettilo in blacklist.<http://mxer2.regione.sardegna.it/action/001C04008C.A62EF/blacklist>

**Comment by vigliottim** [comment]
Buongiorno, 
le chiediamo di inviarci cortesemente uno screenshot in modo da darle supporto al meglio.
Inoltre, la informiamo che sono presenti due cartelle che contengono le immagini contenute nella documentazione, raggiungibili ai seguenti link:

- https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway/img
- https://github.com/ministero-salute/it-fse-support/tree/main/doc/middleware-regionale/img

E' possibile scaricare direttamente le immagini sul proprio pc tramite il tasto "download":
<img width="942" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/a632d5f8-726c-4919-9cb4-ea794522d975">

Rimaniamo in attesa di un suo riscontro. Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, si procede alla chiusura della presente issue. 
Può riaprirla nel caso avesse bisogno di ulteriore supporto. 
Grazie.
