### ISSUE TITLE
La firma del pdf non risulta valida

### ISSUE THREAD

**Issue by simeds** [ministero-salute/it-fse-support#629]
Salve,
Sono riuscito a pubblicare da riga di comando, ma avendo una struttura che si avvale di Mirth per le comunicazione avrei necessità di capire dove è il problema.

Quale tipo di supporto possiamo richiedere e che tipo di informazioni dobbiamo fornirvi per venirne a capo?

_Originally posted by @simeds in https://github.com/ministero-salute/it-fse-support/issues/620#issuecomment-1956382029_

**Comment by vigliottim** [comment]
Buongiorno, come già indicato nel ticket #620, le suggeriamo cortesemente di verificare in che modo il client "trasforma" il pdf in input (in riferimento alle nostre evidenze fornite nel ticket #620).
Eventualmente può scrivere un messaggio su Slack sul canale #fse rivolto alla community: se altri fornitori hanno riscontrato errori analoghi con il medesimo client, potrebbe ricevere indicazioni specifiche da parte loro.
Procediamo pertanto alla chiusura del presente, ma rimaniamo a disposizione per ulteriori richieste di supporto. 
Grazie.
