### ISSUE TITLE
401: TokenAuthenticationFailed

### ISSUE THREAD

**Issue by aleuzzi** [ministero-salute/it-fse-support#63]
Ciao, 
sto provando ad invocare il servizio di verifica all'endpoint
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation
ed ottengo il seguente messaggio di errore: 
{"type":"https://govway.org/handling-errors/401/TokenAuthenticationFailed.html","title":"TokenAuthenticationFailed","status":401,"detail":"Invalid token","govway_id":"4865b213-9708-11ed-b06a-005056ae7395"}

Ho verificato di aver utilizzato il certificato di signature per la generazione dei JWT, il common name "S1#111ADSFINMATIC" in upper case come indicato nel certificato, di aver impostato
"iss":"auth:S1#111ADSFINMATIC" per il Bearer 
"iss":"integrity:S1#111ADSFINMATIC" per il jwt FSE
Inoltre non mi sembra ci siano spazi in più nei payload. Quali altre verifiche potrei fare?

Grazie in anticipo, 
Alessandro

**Comment by millenniumsrl** [comment]
Ciao,
anche noi riceviamo il medesimo errore:
{"type":"[https://govway.org/handling-errors/401/TokenAuthenticationFailed.html","title":"TokenAuthenticationFailed","status":401,"detail":"Invalid](https://govway.org/handling-errors/401/TokenAuthenticationFailed.html%22,%22title%22:%22TokenAuthenticationFailed%22,%22status%22:401,%22detail%22:%22Invalid) token","govway_id":"bce022dd-a5e6-11ed-84b0-005056ae7395"}

Grazie in anticipo

**Comment by IStacchiotti** [comment]
Buon pomeriggio, analizzando il token jwt risulta che il campo patient_consent sia errato (dovrebbe essere un boolean invece di una stringa). Inoltre manca il campo action_id.

**Comment by aleuzzi** [comment]
Buonasera, ho corretto le segnalazioni su patient_consent e su action_id ma l'errore permane, da cosa potrebbe dipendere?
Allego response: 
{"type":"https://govway.org/handling-errors/401/TokenAuthenticationFailed.html","title":"TokenAuthenticationFailed","status":401,"detail":"Invalid token","govway_id":"041fc4bd-a7c5-11ed-84b0-005056ae7395"}
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, sembrerebbe che i token "Authorization" e "FSE-JWT-Signature" non abbiano una firma valida, quindi la request viene bloccata da GovWay. Copiando infatti i token su jwt.io, compare la dicitura "Invalid Signature". Le suggeriamo di controllare che i certificati siano stati generati correttamente e che stia utilizzando quello corretto per la firma. Infine, le consigliamo di verificare i token ottenuti sul sito jwt.io prima di procedere nuovamente con la richiesta. Grazie.

**Comment by aleuzzi** [comment]
Buonasera, in effetti avevamo un problema nella generazione della sezione x5c che abbiamo risolto. Adesso i token sono validi su jwt.io, ma permane l'errore 401: 
{"type":"https://govway.org/handling-errors/401/TokenAuthenticationFailed.html","title":"TokenAuthenticationFailed","status":401,"detail":"Invalid token","govway_id":"d1a0d71f-a88c-11ed-84b0-005056ae7395"}
Grazie ancora

**Comment by masciamariotti** [comment]
Buonasera Alessandro,
per velocizzare l'analisi sull'errore, potrebbe inviarci i 2 token?
Grazie

**Comment by aleuzzi** [comment]
Eccoli, grazie
bearer: eyJhbGciOiJSUzI1NiIsInR5cGUiOiJKV1QiLCJraWQiOiJDbGllbnQxMSIsIng1YyI6WyJNSUlGS3pDQ0F4T2dBd0lCQWdJVUVBRDZ1cGJ0akF3QVljN2phV1J0LzdSOEt4SXdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekF4TURReE5UVXpOVFJhRncweU5qQXhNRFF4TlRVek5UTmFNR2t4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVIwd0d3WURWUVJoREJSRFJqcEpWQzB4TVRGQlJGTkdTVTVOUVZSSlF6RWFNQmdHQTFVRUF3d1JVekVqTVRFeFFVUlRSa2xPVFVGVVNVTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFER041RUJMempnU3d6MzBpY2NQZVhNNXlvcnpYR2pCc0U5dkMwanBySkRxVnlJODJXWDEvVmhNTHFVRVhiR0xjVE4yUVpGWXRSWkMrYm02cFlsR1BOT1pNSWtsaU1XcThBZW1aOTN3aFQ0cU4zQlY2MUVzd2RWRXR5YmxMVFl4T29HSENSK05RTW1SbHlpdkZpZ2ZmbEE0WWpMekVtQ0UxM3FMQ29KbEpIdUFuNzJ3M084Y0UxM2pkNGJJUVd2YWU1bmc3RDcwRjJmZWxtNXJYM1JNQzJaSlFtNTBZYW1ueTNONDBkY2Z5d0Q0WjhhTlRlbklvdnpSRlZCanJOZnJ1cDVybXZreVdteFh6Z0tPY3dOQkNJMlhoL3lSMFVKdFp0eWdJdXl3U0FOb01xeDFJRlZCaGJqaEFoQ3U1MFVnUWVSWFU0WmY5czlqQVFQaDhheUNZdnpBZ01CQUFHamdkd3dnZGt3SHdZRFZSMGpCQmd3Rm9BVUZqbXBHZ1dKdHc4dHNqWHR3Z21heFFPRElqOHdFZ1lEVlIwZ0JBc3dDVEFIQmdVclRCMEJDekJ6QmdOVkhSOEViREJxTUdpZ1pxQmtobUpzWkdGd09pOHZZMkZrY3k1bWFXNWhibnBsTG1sMEwwTk9QVU5CSlRJd1RXbHVhWE4wWlhKdkpUSXdaR1ZzYkdFbE1qQlRZV3gxZEdVbE1qQlVaWE4wTEU4OVRXbHVhWE4wWlhKdkpUSXdaR1ZzYkdFbE1qQlRZV3gxZEdVc1F6MUpWREFkQmdOVkhRNEVGZ1FVTHVCWDI5NUltVkl4ZHk2MmkveGlDWnlZWVFRd0RnWURWUjBQQVFIL0JBUURBZ1pBTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFCaTB0KzF1L2FjRmYxaGVDc3NEUCt6SS9LR051U0JGZGJGTUxCOTdpZWUwN0lJT1E5K1FmelZVSUErclpnUGxFRzFlZER4dHhCZEttRHRoQ2JYS29Ib2FDL1JhM2p3amNZNzJSbnI4aXprRy9ZWGE1NkJ4Z3I1RThjcTFvSmZGUno0OFdxcVJkdGFNbmRndG1mRnA2Qm1aSTYzZ0toZ3I3QWV4ZTNLUE9GbldPK3ZyRGg1KytHL1lnSldGR3EwcEZqT2ZXOTFwU29UalBnTkdGcVlKMy9Ec1BtWVNybVo4NzhObEI4Y3pLYmM2cWo2WVIyVnd1T0ZoTHVvNnhydFdsZ1NDT0VVRytySWttNDE5Y2NuLzgyYmpjanJyY1EzSlg0L0dialgvV1E3eGR4eEFSSVVVRWtMZ0ljQURxQkx0S2ZlaExCNFcyd2pnSm9aSEx1NnYydHl5S2tGYXVXUkRTRFB1MWdWLzNVMDZTQ3p1YmJ2aHpLL3BXRVRIUXQ5dHkyTHRMTHd0ZTd0bmsxd2E2MWJuV1JFdWJSTUhuaGE4eFBheWR5MlRRcDQxdXR2bWt5YmhhVmJrbDByN0NxVUIvaWtYVS84MmJMMndyakQ4QTlrN2JGYVRtUEt5c014MGZzM1ptaDVxaEdXRFpQTWx6RTUwTFU3U3MzZkZGMnY3NWYrV3pFL29IVHIzWExEY2wrQ1lSUzh4SGJkYWZUZ1k5ZlJFQjF1KzFBNGd5UjhDaUZ3ei95MjdkSEZkZldIMkZCU2I2U29ZT0QxSHRVOXJTNkE0VlZTNjlrRFRWRFRnN0tFVVhsWm1OanNTdmMwY21WSUhNSlZvSlBycGpsY0RaRXZkNlNHUmljeHZFUTNGUDQ1UnF0eUl5SVFibk9VQ3hhZUtaVnh3bDJLSmc9PSJdfQ.eyJpc3MiOiJhdXRoOlMxIzExMUFEU0ZJTk1BVElDIiwiaWF0IjoxLjY3NTk2NTgxNEU5LCJleHAiOjEuNjc2MDUyMjE0RTksIkp0aSI6IjI1MTA1OCIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInN1YiI6IlZSRE1SQzY3VDIwSTI1N0VeXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyJ9.SwhmPzXYUqFJHbDEGnnmQya0rjTCHiJKCc3UHeDu5AOPJvQXjO7VzCI_uSkmKc-G-y3Nuv_NlUKrEI91nfDz0Hkmqgp4WnGlmLAN_TNlkjJcXNHOLZZTvKWh2rRHf5dwBGeQwmugRYuvORcGMVhuwaiM08MhdsSQ6d1Ra8L-CfEVAJhg9LaGTB-B9xdyRCnDr1UnydOnqxe1kKfVHy0H0mqIaz4QrSgOtemUVFUwJrlOnW64-GmhWoNN_PAf_Z9w9HyNNF5VVKz9O7Hu9xDs6E6Jp3jMsFi1wE5ANEnVPcN8O3RvHp-bSa-tFfuCJ30t7TivQGKBkKd1HeqCc0-I7g

jwtFSE: eyJhbGciOiJSUzI1NiIsInR5cGUiOiJKV1QiLCJ4NWMiOlsiTUlJRkt6Q0NBeE9nQXdJQkFnSVVFQUQ2dXBidGpBd0FZYzdqYVdSdC83UjhLeEl3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TXpBeE1EUXhOVFV6TlRSYUZ3MHlOakF4TURReE5UVXpOVE5hTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMweE1URkJSRk5HU1U1TlFWUkpRekVhTUJnR0ExVUVBd3dSVXpFak1URXhRVVJUUmtsT1RVRlVTVU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREdONUVCTHpqZ1N3ejMwaWNjUGVYTTV5b3J6WEdqQnNFOXZDMGpwckpEcVZ5STgyV1gxL1ZoTUxxVUVYYkdMY1ROMlFaRll0UlpDK2JtNnBZbEdQTk9aTUlrbGlNV3E4QWVtWjkzd2hUNHFOM0JWNjFFc3dkVkV0eWJsTFRZeE9vR0hDUitOUU1tUmx5aXZGaWdmZmxBNFlqTHpFbUNFMTNxTENvSmxKSHVBbjcydzNPOGNFMTNqZDRiSVFXdmFlNW5nN0Q3MEYyZmVsbTVyWDNSTUMyWkpRbTUwWWFtbnkzTjQwZGNmeXdENFo4YU5UZW5Jb3Z6UkZWQmpyTmZydXA1cm12a3lXbXhYemdLT2N3TkJDSTJYaC95UjBVSnRadHlnSXV5d1NBTm9NcXgxSUZWQmhiamhBaEN1NTBVZ1FlUlhVNFpmOXM5akFRUGg4YXlDWXZ6QWdNQkFBR2pnZHd3Z2Rrd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3RWdZRFZSMGdCQXN3Q1RBSEJnVXJUQjBCQ3pCekJnTlZIUjhFYkRCcU1HaWdacUJraG1Kc1pHRndPaTh2WTJGa2N5NW1hVzVoYm5wbExtbDBMME5PUFVOQkpUSXdUV2x1YVhOMFpYSnZKVEl3WkdWc2JHRWxNakJUWVd4MWRHVWxNakJVWlhOMExFODlUV2x1YVhOMFpYSnZKVEl3WkdWc2JHRWxNakJUWVd4MWRHVXNRejFKVkRBZEJnTlZIUTRFRmdRVUx1QlgyOTVJbVZJeGR5NjJpL3hpQ1p5WVlRUXdEZ1lEVlIwUEFRSC9CQVFEQWdaQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQmkwdCsxdS9hY0ZmMWhlQ3NzRFArekkvS0dOdVNCRmRiRk1MQjk3aWVlMDdJSU9ROStRZnpWVUlBK3JaZ1BsRUcxZWREeHR4QmRLbUR0aENiWEtvSG9hQy9SYTNqd2pjWTcyUm5yOGl6a0cvWVhhNTZCeGdyNUU4Y3Exb0pmRlJ6NDhXcXFSZHRhTW5kZ3RtZkZwNkJtWkk2M2dLaGdyN0FleGUzS1BPRm5XTyt2ckRoNSsrRy9ZZ0pXRkdxMHBGak9mVzkxcFNvVGpQZ05HRnFZSjMvRHNQbVlTcm1aODc4TmxCOGN6S2JjNnFqNllSMlZ3dU9GaEx1bzZ4cnRXbGdTQ09FVUcrcklrbTQxOWNjbi84MmJqY2pycmNRM0pYNC9HYmpYL1dRN3hkeHhBUklVVUVrTGdJY0FEcUJMdEtmZWhMQjRXMndqZ0pvWkhMdTZ2MnR5eUtrRmF1V1JEU0RQdTFnVi8zVTA2U0N6dWJidmh6Sy9wV0VUSFF0OXR5Mkx0TEx3dGU3dG5rMXdhNjFibldSRXViUk1IbmhhOHhQYXlkeTJUUXA0MXV0dm1reWJoYVZia2wwcjdDcVVCL2lrWFUvODJiTDJ3cmpEOEE5azdiRmFUbVBLeXNNeDBmczNabWg1cWhHV0RaUE1sekU1MExVN1NzM2ZGRjJ2NzVmK1d6RS9vSFRyM1hMRGNsK0NZUlM4eEhiZGFmVGdZOWZSRUIxdSsxQTRneVI4Q2lGd3oveTI3ZEhGZGZXSDJGQlNiNlNvWU9EMUh0VTlyUzZBNFZWUzY5a0RUVkRUZzdLRVVYbFptTmpzU3ZjMGNtVklITUpWb0pQcnBqbGNEWkV2ZDZTR1JpY3h2RVEzRlA0NVJxdHlJeUlRYm5PVUN4YWVLWlZ4d2wyS0pnPT0iXX0.eyJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExQURTRklOTUFUSUMiLCJpYXQiOjEuNjc1OTY1ODE0RTksImV4cCI6MS42NzU5NjQyNTdFOSwiSnRpIjoiMjUxMDU5IiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwic3ViIjoiVlJETVJDNjdUMjBJMjU3RV5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIiwic3ViamVjdF9vcmdhbml6YXRpb25faWQiOiIxOTAiLCJzdWJqZWN0X29yZ2FuaXphdGlvbiI6IlJlZ2lvbmUgU2ljaWxpYSIsImxvY2FsaXR5IjoiMjAxMTIzNDU2Iiwic3ViamVjdF9yb2xlIjoiQUFTIiwicGVyc29uX2lkIjoiUlNTTVJBNzVDMDNGODM5S15eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIiwicGF0aWVudF9jb25zZW50IjpmYWxzZSwicHVycG9zZV9vZl91c2UiOiJUUkVBVE1FTlQiLCJhY3Rpb25faWQiOiJDUkVBVEUiLCJyZXNvdXJjZV9obDdfdHlwZSI6IjExNTAyLTJeXjIuMTYuODQwLjEuMTEzODgzLjYuMSIsInN1YmplY3RfYXBwbGljYXRpb25faWQiOiJTQTRXRUJfU0E0QURUIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZW5kb3IiOiJEYXRhIFByb2Nlc3NpbmcgU1BBIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiU0E0V0VCX1NBNEFEVCJ9.nvtM8JV2LpjrhPludOQL38g0x2mgayzN144LDmKc9Z1gV7xCXRTZdFP7IqWAQkI3N8QgvoSTMMm7ib04Z6K2F1HBorpWZ09kj4JinyPpXuP6hRG06o3rQ0tqcKgjWJAX61h28byTgfvDOaJLkeu4MCPOyjJWFX2tw3rr37iH5JoaGz2CmyXUOj6M8UML9XMOeY9hEQFVFndhDlScmCDSLu7EJxxRtuUUyfyFEDbp_eCiqG051xygKJ5dygl6kHtitadLMU337oeNyy1-vsWhTauG9uEzUA-wv_RgfWqpmDqzyOaNn6POE9p-kpuRZOwyi3mRe9iX_VJw1SblfwdEGw

**Comment by IStacchiotti** [comment]
Buongiorno, da una verifica preliminare è emerso che il parametro jti, nel vostro json, riportava la prima lettera in maiuscolo: "Jti": "251059". Potreste riprovare scrivendo il parametro con tutte le lettere in minuscolo? 
Grazie

**Comment by aleuzzi** [comment]
Buongiorno, ho impostato il parametro "jti" tutto in minuscolo ma ho avuto lo stesso esito:

**Comment by IStacchiotti** [comment]
Ok, grazie. Abbiamo appena notato che il parametro resource_hl7_type non risulta formattato correttamente. Dovreste modificarlo come indicato di seguito: "('11502-2^^2.16.840.1.113883.6.1')". Grazie

**Comment by IStacchiotti** [comment]
Ok, grazie. Ci conferma che l'errore è sempre lo stesso (["title":"TokenAuthenticationFailed","status":401,"detail":"Invalid])? Le chiedo anche la cortesia di mandarci il nuovo identificativo della transazione (govway_id) per contentirci verifiche più approfondite. Grazie

**Comment by aleuzzi** [comment]
Si, confermo che l'errore è lo stesso, ecco il messaggio ottenuto in risposta: 

{"type":"https://govway.org/handling-errors/401/TokenAuthenticationFailed.html","title":"TokenAuthenticationFailed","status":401,"detail":"Invalid token","govway_id":"2ea19673-a921-11ed-9627-005056ae7395"}

**Comment by IStacchiotti** [comment]
Buongiorno, dalle analisi è emerso che i campi 'iat' e 'exp' non sono popolati nel giusto formato:
- "iat":1.676022805E9
- "exp":1.676109205E9
invece di, ad esempio, 1676302585. Potrebbe verificarli? Grazie mille

**Comment by aleuzzi** [comment]
Buongiorno, ho verificato i token che avevo inviato in questa segnalazione
https://github.com/ministero-salute/it-fse-support/issues/63#issuecomment-1425501758
sul sito che mi avete indicato per la verifica https://jwt.io/ , e vedo che i campi citati sono valorizzati così:
"iat": 1676022805,
  "exp": 1676109205
dove avete riscontrato il formato errato di quei campi?

**Comment by IStacchiotti** [comment]
Potrebbe riprovare cortesemente fornendoci a valle gli estremi della chiamata (trace_id e govway_id)? Grazie mille.

**Comment by aleuzzi** [comment]
Adesso siamo arrivati ad avere un errore di tipo applicativo: 
{"traceID":"d1ff2ee6ed43c59b","spanID":"d1ff2ee6ed43c59b","type":"/msg/syntax","title":"Errore di sintassi.","detail":"Schema with version POCD_HD000040 not found on database.","status":400,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.80.3.1.4.4.bbfd1d2006fa3dba3d29bbe0fe72385d99a6e81e32d48830d7e08331d8ab1f25.8b7eb3f866^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}
che credo sia imputabile al CDA che abbiamo utilizzato che non passa la validazione Schematron, procediamo alle verifiche in autonomia, se necessario apriremo altra issue su questo argomento. 
A cosa era dovuto il problema? Dobbiamo mantenere "jti" in minuscolo? "resource_hl7_type" è quindi obbligatorio?

**Comment by masciamariotti** [comment]
Buongiorno Alessandro,
il problema era dovuto, come già anticipato, ad un errato formato dei campi iat ed exp, che in questo caso è stato fixato lato server.
Per quanto riguarda il campo jti le confermo che è corretto mantenerlo in minuscolo, mentre il campo resource_hl7_type non è obbligatorio, ma se inviato deve rispettare il formato definito in documentazione.
Grazie

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
