### ISSUE TITLE
Errore in fase di pubblicazione Referto

### ISSUE THREAD

**Issue by avlp** [ministero-salute/it-fse-support#630]
Salve,
si chiede supporto circa il seguente errore ricevuto dal gateway in fase di pubblicazione:

`{"traceID":"e027c91379b723f2","spanID":"e027c91379b723f2","type":"/msg/fhir-mapping-type","title":"Mapping fhir fallito.","detail":"Cannot set property perfomed on resource","status":400,"instance":"/fhir-resource"}`

**Comment by vigliottim** [comment]
Buongiorno, grazie per la segnalazione, faremo un aggiornamento del StructureMap di RSA correggendo l'espressione che ha prodotto l'errore. 
Inoltre, abbiamo notato che nel path cda2: _"ClinicalDocument/componentOf/EncompassingEncounter/location/healthCareFacility"_ l'elemento _healthCareFacility_ non ha un Identificativo.
Per evitare che vi troviate errori di trasformazione dovuti a quanto annotato, vi consigliamo l'inserimento di un elemento _id_ per _healthCareFacility_.

**Comment by avlp** [comment]
Buongiorno, grazie. Quando sarà disponibile tale correzione?

**Comment by vigliottim** [comment]
La fix è in lavorazione. Le daremo aggiornamenti non appena saranno disponibili. Grazie.

**Comment by vigliottim** [comment]
Buongiorno, l'aggiornamento è stato rilasciato. 
Le chiediamo gentilmente di riprovare. 
Rimaniamo a disposizione qualora il problema persista. 
Grazie.

**Comment by avlp** [comment]
Salve abbiamo riprovato ma otteniamo:
`EXCEPTION FATAL, traceID:e027c91379b723f2, spanID:e027c91379b723f2, "Mapping fhir fallito.; Cannot set property perfomed on resource"`

**Comment by vigliottim** [comment]
Buongiorno, il _traceid_ fornito è identico a quello nel primo messaggio del thread. 
Potrebbe gentilemente fornirci il nuovo _traceid_ con l'errore ricevuto relativo alla chiamata al servizio di pubblicazione dopo la fix? 
Grazie.

**Comment by avlp** [comment]
Sì, corretto. Ho provato a riprocessare lo stesso referto ottenendo:
`EXCEPTION FATAL, traceID:9bf88ca771fc28bb, spanID:9bf88ca771fc28bb, "Errore in fase di recupero dell'esito della verifica.; Il CDA non risulta validato"`
nonostante sia già stato validato con 
`2.16.840.1.113883.2.9.2.150.4.4.b57f4a438f7524ac346c16e07bf6516ac42f6aa7e1e2134fce2cd7657a8fad41.783f3f60af^^^^urn:ihe:iti:xdw:2013:workflowInstanceId`

Gli altri referti, applicando la correzione suggerita, sono stati accettati, ad esempio:
`traceID:5833808141cf51f5,spanID:5833808141cf51f5`

**Comment by LucaRogledi** [comment]
Buonasera,
Il messaggio di errore da lei riportato, potrebbe essere dovuto al fatto che la validazione effettuata per quel cda è scaduta o bruciata da un'altra pubblicazione dello stesso documento.
Per evitare che si verifichi tale messaggio di errore la invitiamo gentilmente a procedere con una nuova validazione del documento, assicurandosi che il workflowInstanceId ricevuto dal servizio corrisponda a quello inserito successivamente nel parametro "workflowInstanceId", se utilizzato, all'interno della requestBody della nuova chiamata di pubblicazione. 
Ricordiamo infine di avere cura nella chiamata del servizio di pubblicazione una volta soltanto, poiché tale invocazione brucerà il workflowInstanceId utilizzato non rendendolo più disponibile per ulteriori chiamate di pubblicazione.
Restiamo a disposizione per ulteriori chiarimenti.
Grazie

**Comment by avlp** [comment]
Salve,
abbiamo inviato correttamente con i seguenti id:
`traceID:6eac10b9e81b517f,spanID:6eac10b9e81b517f`
