### ISSUE TITLE
Errore CF nell'invio di un RSA

### ISSUE THREAD

**Issue by ciampysara** [ministero-salute/it-fse-support#631]
Stiamo invocando il servizio https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1 "action_id": "CREATE"
La Request ci ritorna "Codice fiscale non trovato in anagrafe" ma stiamo usando dei CF di persone reali (nell'esempio c'è il mio CF) il CART id è X-CART-id: 3c096e84-d16f-11ee-9e39-00505686f633

**Comment by vigliottim** [comment]
Buongiorno,
potrebbe allegare cortesemente la response completa ricevuta? Grazie.

**Comment by ciampysara** [comment]
{
  "header": {
    "HTTPVersion": "HTTP/1.1",
    "StatusCode": "400",
    "StatusReason": "Bad Request",
    "Date": "Fri, 23 Feb 2024 10:03:36 GMT",
    "Server": "GovWay-PDA",
    "X-Frame-Options": "SAMEORIGIN",
    "Strict-Transport-Security": "max-age=0;",
    "Expires": "0",
    "Cache-Control": "no-cache, no-store, must-revalidate",
    "Pragma": "no-cache",
    "Vary": "*",
    "X-Content-Type-Options": "nosniff",
    "X-CART-id": "23ad6cfd-d232-11ee-9e39-00505686f633",
    "Content-Type": "application/problem+json",
    "Connection": "close",
    "Transfer-Encoding": "chunked"
  },
  "body": {
    "traceID": "R3VERR",
    "spanID": "R3VERR",
    "type": "/msg/cda-element",
    "title": "Error anonymizing cda.",
    "detail": "Codice fiscale non trovato in anagrafe: *****",
    "status": 400,
    "instance": "/msg/cda-anonymizaton"
  },
  "curl_command": {
    "cert-type": "PEM",
    "cert": "****",
    "key": "****",
    "cacert": "cert/ca_certificates/testcert/Actalis.chain",
    "method": "POST",
    "endpoint": "https://fse20gwstage.regione.toscana.it/gateway/v1/documents/validate-and-create",
    "Authorization-Bearer-Token": "eyJ4NWMiOlsiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tTUlJRXZnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2d3Z2dTa0FnRUFBb0lCQVFDLzZKTnVTNE5sTEh5ZGl3L2xFRk5mM2xzeExHemZQKzErRUhjQ3loZmt3UzhJdjM4Q3R4U2dYQm14NmRtamQzbExjdXhOWm5LcUVyeFF5REhJTmUvdVVnVVBRbXp4c1BVTXZzU3Y5ejBkQ2FFUTRmcWVXa0hjNzFnQkh1aXpDaUp5VDlRbTJVbjlySlk4dXR5OU1tOHVTK28yVVgyTHp3RU5adXlkcTFGK0dzUEEwanZ0T0FFYk5YT0ZwOE9lRlV3K0d4RUxGT2hPaXBwdzNDdzVJbjEzTVFMM2I5SDVzd2orVEJJMHBxS0pWN3Q0OWtWNEVGNy9YL1Z1SGcybm1zenBJTDc2eXowenVqc3h6c3ZMUXRSMy84ZUFOM1RoNHlNZGwwMzZ0NnNUOEdleVBsTUtJY3dCZzFEdi9sYlB2bW5qV2JqKzRJNXJqU0o5bUxzQUk1WlBBZ01CQUFFQ2dnRUJBS0E3ME4yR3IyOEtkZ0lVMm5DbjhQVmE4MGxiam92WkZMTHRqSEVIekd0ejRaR3NVcUF4dlVjbm4weXR0TXFJTnY2SU5rVnFCTk44VVVBaDUyOERtaEdpNmhhVG4rTXRuVzNHMnZNUnZEVkNsUGxEdGI0Q0hud2FXNkNUN2plUGZyTnpjKy83L1l1UlR0L21KZWpTODRIMFlOcDVzQm5ML1ZUeld4MUtyZ0JiWmY3WGN6a2FrekR3Y1dsVHZKRS9XSFI3RE9sTlVaaWZtSXBZckpiZVBkbWpqS1JmUng1QjN0Zlo1Y2grUnBpNHRrSVQ3dHRWakxodG9HMlp3Z1BFbUxYdG54STA2VHhiNlNoZDFvdE85aUQ1VEMzL0s4Uk9nZTg2dGVvWUFhbzQ5ZitNQUxEUmpaeE0zTU9wNmhCbTV5WTJFb2o0NVJOZFpWbnRMTEhvOGdFQ2dZRUE2TzRwUWI1Q1B3d0lONUoyUWRjOE1WYURYOVBKbjJjY2ljOXZDdWliTUx3MkxNdm1PVXdoWU9wc2F0aTYxNk83TCtqeEJ0eVIrQ2xhUlVodUd2OFRpWUxDYVlmTTdXMXA3OTUzQy9BUlhPZWJOWDNJRWhOcVY4ZTdmR2dWdTNabWxOMjVueGtObjYyVWVyQ0o5RG5Mb1kvU0tmbmNtbGR0V1JsMlM5QzFlTXNDZ1lFQTB1cFRhT08rQW1FekQ5Qzhqc2NxcG4wMWVrREFyZTNKZEwwS3FqbHNRV1ArUUNCQTd6aDBvSGpQZnhPWDRyNFhpT1JvYStXNlpaS3VKSDRLdjFIM2FTYmM0MTl3SEZnYTBxUW04eW5Ea3k5MXVhWGMyZlVmaWhMT0s5THhFNGpuWThnN3BQeGZDTWhJR0ZkZ2FPWnBZL1g1cTNmditnSnlkWmh5RER1YTNBMENnWUJna0VNNFJ3aXRuRzVYbzNjMUNtYWd5WTNERDBpNXRZUm1PVUYra3ptcTlZdTcvSGVmNzBpekpkdjJXNHp4MHFYS1VkYUNFclRNM1UvWUF4UHFTeTZ0UmpFVWtNREsrUjMrM0FvY1A5VGkzLzAvS3Jyamkzcjlrd2JOcDFUREYyMmxiMW9CYytCcS93bmI1dzM1Mm0vcHRYYmFBZ1NMVTQwNGI4N1QxVjAyQ3dLQmdFNUl4VDdJVVMxRzhKSHRNeDkzazBBS2R6L3lLdElqMFVOd0t6WTFiQlgxVEZoMjRFTXFYRGQzditSMTNFay9yektUUEtMWHVOQ2NtZUJYbkJ1WkM5RE9xT3dINzIvRnorYmhJTWZlZDRYNDlxUTZpUGVwUU5TWjJFWngzQ01aREhGL3o0dVVWSjNJNE9HUUJPdktvZEdGYWU4WDdFMktmUHRpNHVuaGNjQTlBb0dCQUwwWjJtS1pJeWgvNGl4bitPdGMrbnBuTkQyYitOS2N4OVFjNmJZd2M4d1FJTGhvL0JDNzh3UmhHdHBHSEZzN3R4cXY4VDhoZHJGclVBeGJEM0x5NC93N2VHNFVOYWhrWWFWRjQ3K0p1ajZ0dXIzNmk3aVpLdXdYVm5pdG12U0poQXp4ZmcxYWR1S1hndEJDSkE5bHljTEhBMCt1MktlL1Y5cnpaMStHaTI0Qy0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0iXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJHTk5MUkk4MEU2MEU2MjVPXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEvIiwiaXNzIjoiYXV0aDpBMSMwOTA5MDFSU0FFU1RBUjAwMDAwMCIsImV4cCI6MTcwODY4NjIxMSwiaWF0IjoxNzA4NjgyNjExLCJqdGkiOiJiMTU5YTA2NS0wZDYxLTQ5OGMtYWY5ZS00ZDczYzg2MDE3Y2QifQ.Bp3d8LLn2priSC_7hRj17IXp-WLmOaZiSfmQrupVq1A5lhwLrK0oC2zYfr6H8IBaxGUMOwIithT_9gbWRg_GzQgQeiYHU5pLe1WQ489Je-9ZNBlHf89D4BDnEI_8BR13GPInMEKsfdaGFBqeFWZE2KPE4xBW2Egs5zU3nhLY8QVBArNDd7d1n-VEUMB1sbSEEIPIn1eERybKj0FgpTxc6VlSZhpG27S0n0moxOC-O49T289KNnxCFa6EpViRwdS6PeHnOwQTrmqitPDvxQyHAgtsbImNESrVm2uLjjSge4pENCiXDzF_B5b1u8aeT8lY_hhaWnmiNeGydAW54MkTDg",
    "FSE-JWT-Signature": "eyJ4NWMiOlsiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tTUlJRXZnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2d3Z2dTa0FnRUFBb0lCQVFDLzZKTnVTNE5sTEh5ZGl3L2xFRk5mM2xzeExHemZQKzErRUhjQ3loZmt3UzhJdjM4Q3R4U2dYQm14NmRtamQzbExjdXhOWm5LcUVyeFF5REhJTmUvdVVnVVBRbXp4c1BVTXZzU3Y5ejBkQ2FFUTRmcWVXa0hjNzFnQkh1aXpDaUp5VDlRbTJVbjlySlk4dXR5OU1tOHVTK28yVVgyTHp3RU5adXlkcTFGK0dzUEEwanZ0T0FFYk5YT0ZwOE9lRlV3K0d4RUxGT2hPaXBwdzNDdzVJbjEzTVFMM2I5SDVzd2orVEJJMHBxS0pWN3Q0OWtWNEVGNy9YL1Z1SGcybm1zenBJTDc2eXowenVqc3h6c3ZMUXRSMy84ZUFOM1RoNHlNZGwwMzZ0NnNUOEdleVBsTUtJY3dCZzFEdi9sYlB2bW5qV2JqKzRJNXJqU0o5bUxzQUk1WlBBZ01CQUFFQ2dnRUJBS0E3ME4yR3IyOEtkZ0lVMm5DbjhQVmE4MGxiam92WkZMTHRqSEVIekd0ejRaR3NVcUF4dlVjbm4weXR0TXFJTnY2SU5rVnFCTk44VVVBaDUyOERtaEdpNmhhVG4rTXRuVzNHMnZNUnZEVkNsUGxEdGI0Q0hud2FXNkNUN2plUGZyTnpjKy83L1l1UlR0L21KZWpTODRIMFlOcDVzQm5ML1ZUeld4MUtyZ0JiWmY3WGN6a2FrekR3Y1dsVHZKRS9XSFI3RE9sTlVaaWZtSXBZckpiZVBkbWpqS1JmUng1QjN0Zlo1Y2grUnBpNHRrSVQ3dHRWakxodG9HMlp3Z1BFbUxYdG54STA2VHhiNlNoZDFvdE85aUQ1VEMzL0s4Uk9nZTg2dGVvWUFhbzQ5ZitNQUxEUmpaeE0zTU9wNmhCbTV5WTJFb2o0NVJOZFpWbnRMTEhvOGdFQ2dZRUE2TzRwUWI1Q1B3d0lONUoyUWRjOE1WYURYOVBKbjJjY2ljOXZDdWliTUx3MkxNdm1PVXdoWU9wc2F0aTYxNk83TCtqeEJ0eVIrQ2xhUlVodUd2OFRpWUxDYVlmTTdXMXA3OTUzQy9BUlhPZWJOWDNJRWhOcVY4ZTdmR2dWdTNabWxOMjVueGtObjYyVWVyQ0o5RG5Mb1kvU0tmbmNtbGR0V1JsMlM5QzFlTXNDZ1lFQTB1cFRhT08rQW1FekQ5Qzhqc2NxcG4wMWVrREFyZTNKZEwwS3FqbHNRV1ArUUNCQTd6aDBvSGpQZnhPWDRyNFhpT1JvYStXNlpaS3VKSDRLdjFIM2FTYmM0MTl3SEZnYTBxUW04eW5Ea3k5MXVhWGMyZlVmaWhMT0s5THhFNGpuWThnN3BQeGZDTWhJR0ZkZ2FPWnBZL1g1cTNmditnSnlkWmh5RER1YTNBMENnWUJna0VNNFJ3aXRuRzVYbzNjMUNtYWd5WTNERDBpNXRZUm1PVUYra3ptcTlZdTcvSGVmNzBpekpkdjJXNHp4MHFYS1VkYUNFclRNM1UvWUF4UHFTeTZ0UmpFVWtNREsrUjMrM0FvY1A5VGkzLzAvS3Jyamkzcjlrd2JOcDFUREYyMmxiMW9CYytCcS93bmI1dzM1Mm0vcHRYYmFBZ1NMVTQwNGI4N1QxVjAyQ3dLQmdFNUl4VDdJVVMxRzhKSHRNeDkzazBBS2R6L3lLdElqMFVOd0t6WTFiQlgxVEZoMjRFTXFYRGQzditSMTNFay9yektUUEtMWHVOQ2NtZUJYbkJ1WkM5RE9xT3dINzIvRnorYmhJTWZlZDRYNDlxUTZpUGVwUU5TWjJFWngzQ01aREhGL3o0dVVWSjNJNE9HUUJPdktvZEdGYWU4WDdFMktmUHRpNHVuaGNjQTlBb0dCQUwwWjJtS1pJeWgvNGl4bitPdGMrbnBuTkQyYitOS2N4OVFjNmJZd2M4d1FJTGhvL0JDNzh3UmhHdHBHSEZzN3R4cXY4VDhoZHJGclVBeGJEM0x5NC93N2VHNFVOYWhrWWFWRjQ3K0p1ajZ0dXIzNmk3aVpLdXdYVm5pdG12U0poQXp4ZmcxYWR1S1hndEJDSkE5bHljTEhBMCt1MktlL1Y5cnpaMStHaTI0Qy0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0iXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJHTk5MUkk4MEU2MEU2MjVPXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImlzcyI6ImludGVncml0eTpBMSMwOTA5MDFSU0FFU1RBUjAwMDAwMCIsImxvY2FsaXR5Ijoiand0LWxvY2F0aW9uIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiMyIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBUb3NjYW5hIiwic3ViamVjdF9vcmdhbml6YXRpb25faWQiOiIwOTAiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEvIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJhY3Rpb25faWQiOiJDUkVBVEUiLCJyZXNvdXJjZV9obDdfdHlwZSI6IignJycxMTQ4OC00Xl4yLjE2Ljg0MC4xLjExMzg4My42LjEnJycpIiwiYXR0YWNobWVudF9oYXNoIjoiOTg2ZDA3YTU3MWNiYTlhZjMxYzVhYThhMWE5MTJjNzBiZWZhNDdhODdkNWRiZTI4MzRiNWJkYjRlOThlOTg2MSIsInN1YmplY3RfYXBwbGljYXRpb25faWQiOiJQTEVJQURFIiwiZXhwIjoxNzA4Njg2MjExLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlbmRvciI6IkVTVEFSIiwiaWF0IjoxNzA4NjgyNjExLCJqdGkiOiJiMTU5YTA2NS0wZDYxLTQ5OGMtYWY5ZS00ZDczYzg2MDE3Y2QiLCJwZXJzb25faWQiOiJDTVBTUkE4OUg2NEUzMzVEXl5eJmFtcDsyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImYW1wO0lTTyJ9.GeGlU_hmgALL3OWAnTS4iFr5dpKjJuKT917-ENs7V1REK7ycN5Y5hd6f3vViW2RE1w1uikQ5UU9NHLpM1Yc71VywQV2xGN1pHMmN_R5EOXVsmTuMJsvmcI77AuU6QLNnC-0oxLw8vLoXqBZu9esfxl7M7HLpYNsMz9WA7BBBIUaAlo7E8VElPANnC4Vn0WT4G64dbwYiGkgB86vOTq0uruvpVfUx5LBmqiBV05RbK1RYMu4d4MeG0rvUavYggpzufGrNpeUwH31dEId2Tn2Mfh7HApgqN2kijkql_w2hDGoKfA7JRRaNIZSFNTL0g5q_HJzWv3VQE94FADHvnYEKSg",
    "accept": "application/json",
    "Content-Type": "multipart/form-data",
    "Request-Body": {
      "administrativeRequest": "SSN",
      "assettoOrganizzativo": "AD_PSC014",
      "conservazioneANorma": "CONS^^^&2.16.840.1.113883.2.9.3.3.6.1.7&ISO",
      "healthDataFormat": "CDA",
      "identificativoDoc": "2.16.840.1.113883.2.9.2.90.4.4^09090101.RSA.901.000001",
      "identificativoRep": "2.16.840.1.113883.2.9.2.90.4.5.901",
      "identificativoSottomissione": "2.16.840.1.113883.2.9.2.909587",
      "mode": "ATTACHMENT",
      "tipoAttivitaClinica": "ERP",
      "tipoDocumentoLivAlto": "REF",
      "tipologiaStruttura": "Ospedale"
    },
    "pdf_filepath": "/tmp/tmpjjpkmkeg"
  }
}

**Comment by vigliottim** [comment]
Buongiorno, la invitiamo a rivolgersi ai gestori del middleware regionale per accertare in primo luogo quale sia l'endpoint finale, richiamato dal middleware della regione Toscana. Inoltre, specifichiamo che questo canale è dedicato a fornire supporto in merito all'integrazione con l'architettura digitale 2.0 del fascicolo. Pertanto, se il middleware in questione si interfaccia con un servizio esposto dall'architettura digitale 1.0 del fascicolo, le chiediamo di rivolgersi a fse_support@sogei.it per eventuali richieste di supporto. Grazie.

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura del presente ticket e la invitiamo a riaprirlo nel caso in cui avesse bisogno di ulteriore supporto. Grazie.
