### ISSUE TITLE
Gestione risultati di richieste precedenti della richiesta corrente 

### ISSUE THREAD

**Issue by Furbessem** [ministero-salute/it-fse-support#632]
Salve a tutti, 
antefatto: questa richiesta è differente dalla precedente https://github.com/ministero-salute/it-fse-support/issues/622 

Il cliente richiede di stampare nel referto di laboratorio i risultati di richieste precedenti la richiesta corrente.
In tal senso serve che sia stampato, oltre i risultati precedenti, anche:

- il codice identificativo delle richieste precedenti
- la data di accettazione delle richieste precedenti  

in modo da dare all'utente un'informazione formattata per richiesta precedente e con maggior dettaglio rispetto alla issue/622.

In che modo è possibile inserire queste informazioni nel xmlcda? 
La soluzione proposta e da voi approvata per la issue 622 (che risolve una domanda differente) non ha spazio per tale informazioni.

Grazie in anticipo.
Stefano

**Comment by Furbessem** [comment]
aggiorno indicando che il cliente ritiene l'informazione dell'identificativo richiesta precedente e la data, indispensabile.
Se potete darci aggiornamento in quanto siamo in attesa di completare delle attività.

**Comment by LucaRogledi** [comment]
Buongiorno, secondo le specifiche di HL7 Italia, è possibile inserire più volte l'elemento "inFulfillmentOf", consentendo così di riportare il codice identificativo delle richieste precedenti. Inoltre, l'elemento "participant/time" può essere utilizzato per indicare la data e l'orario di inoltro della richiesta al laboratorio di analisi. Una precisazione in merito anche alla issue #622, i risultati precedenti devono riguardare la stessa specialità di laboratorio di quelli della richiesta corrente.

**Comment by Furbessem** [comment]
Buongiorno, non ci è chiaro come poter abbinare - ai fini della rappresentazione grafica - il corretto codice richiesta inserto nel "inFulfillmentOf" con i risultati clinici precedenti inseriti in entryRelationship con typecode="REFR" .
Nel caso più generico la richiesta corrente potrebbe contenere risultati con precedenti in diverse richieste ma con insiemi disgiunti:
Esempio:
Richiesta corrente con Esame1 , Esame2, Esame3 
Richiesta precedente1 con Esame1 , Esame3
Richiesta precedente2 con Esame 2 , Esame3

La struttura xmlcda avrebbe una lista di richieste in "inFulfillmentOf" e separatamente delle liste di entryRelationship con typecode="REFR":
Esame1  -> REFR Esame1
Esame2 -> REFR Esame2
Esame3 -> REFR Esame3 , REFR Esame3

In riferimento all'ultima frase: 
grazie della precisazione, la riteniamo implicitamente soddisfatta dalla nostra implementazione in quanto nella issue #622 i precedenti sono -da noi- intesi come "risultati precedenti del risultato corrente" quindi appartengono allo stesso esame, per cui alla stessa specialità.

**Comment by Furbessem** [comment]
Buongiorno, 
non ci è quindi possibile inserire i dati richiesti dal cliente in modo strutturato tale da abbinare il codice richiesta precedente ai rispettivi risultati precedenti. 
Grazie. 
Stefano.

**Comment by vigliottim** [comment]
Esatto. 
Procediamo alla chiusura del presente ticket e restiamo a disposizione per altre richieste di supporto. 
Grazie.
