### ISSUE TITLE
Mancato riscontro a : Questionario per richiesta accreditamento applicativo FSE 2.0

### ISSUE THREAD

**Issue by ZucchettiCentroSistemi** [ministero-salute/it-fse-support#633]
Buongiorno,

la presente per avere informazioni riguardo la richiesta di accreditamento per il nostro applicativo, inviata in data 25/01.
Dato che non abbiamo ricevuto alcun tipo di comunicazione, riguardo tale richiesta, volevamo sapere se c’era stato qualche tipo di problema oppure se avevamo commesso qualche errore nella compilazione del questionario.

A disposizione per ulteriori informazioni,

Un saluto

**Comment by IStacchiotti** [comment]
Buongiorno, Le segnaliamo che non risultano pull request recenti aperte da Zucchetti Centro Sistemi.
La compilazione dell'EuSurvey è uno dei primi passi da percorre ai fini dell'accreditamento, il cui processo è descritto in dettaglio al seguente [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/accreditamento#fase-1-processo-di-accreditamento). La rimandiamo anche a questo [link](https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#accreditamento-fse-20-draft) della documentazione in cui sono riportate delle indicazioni per l'apertura delle pull request.
Rimaniamo a disposizione per eventuali chiarimenti

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura del presente ticket e la invitiamo a riaprirlo nel caso in cui avesse bisogno di ulteriore supporto. Grazie.
