### ISSUE TITLE
Domande per i Test Case da eseguire

### ISSUE THREAD

**Issue by ZucchettiCentroSistemi** [ministero-salute/it-fse-support#634]
Buongiorno,

siamo la Zucchetti Centro sistema s.p.a, stiamo effettuando i test case per accreditare il nostro software di Medicina Trasfusionale, JAB0 v.9.
Stiamo svolgendo i test case, relativi alla cartella "Trasfusionale".
La presente per chiedervi se, sono da eseguire anche quelli relativi al "Referto di medicina di Laboratorio", nonostante il nostro software non produce referti relativi ai "casi di test", che sono presenti del file "casi di test LAB.docx".

a disposizione per qualsiasi chiarimento, 

un saluto

**Comment by LucaRogledi** [comment]
Buongiorno,
in questo caso potete eseguire i test case all'interno della cartella ["Trasfusionale"](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/9-Trasfusionale) (gli id dei casi di test sono: 191 e 376), mentre riguardo agli altri casi di test relativi a "Referto di medicina di Laboratorio" (non Trasfusionale) è possibile indicare NO nell’apposita colonna "Applicabilità", avendo cura di giustificarlo opportunamente nella colonna "razionale di applicabilità".
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto riscontri, il presente ticket viene chiuso. 
Si può procedere alla riapertura nel caso in cui abbia bisogno di ulteriore supporto. 
Grazie.
