### ISSUE TITLE
Jwt-Generator

### ISSUE THREAD

**Issue by enzocap** [ministero-salute/it-fse-support#635]
Buongiorno,
sono alle prese con la generazione dei due jwt token per effettuare delle prove di chiamata al FSE2.0-Gateway.
Ho personalizzato il data.json seguendo l'esempio in documentazione, digitando i percorsi dei due certificati ricevuti 

ma intanto non è chiaro cosa digitare come alias e password nel comando:

java -jar jwt-generator.jar -d data.json -a {alias} -p {password} -t 1

in ogni caso ricevo l'errore:

 _____  _____  ___       __  _ _ _  _____    _____       _
|   __||   __||_  |   __|  || | | ||_   _|  |     | ___ | |_  ___  ___
|   __||__   ||  _|  |  |  || | | |  | |    | | | || .'|| '_|| -_||  _|
|__|   |_____||___|  |_____||_____|  |_|    |_|_|_||__,||_,_||___||_|

An error occur while trying to generate JWT, hope this can help:
EXCEPTION: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 18 column 24 path $.
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 18 column 24 path $.

Il file data.json è il seguente:

{
"sub": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",    
"subject_role": "AAS",
"purpose_of_use": "TREATMENT",
"iss": "jwt-issuer",
"subject_application_id": "LABNET",
"subject_application_vendor": "DEC Sistemi Srl",
"subject_application_version": "1.4",
"locality": "jwt-location",
"subject_organization_id": "190",
"subject_organization": "Regione Sicilia",
"aud": "FSE_Gateway",
"patient_consent": true,
"action_id": "CREATE",
"resource_hl7_type": "('11502-2^^2.16.840.1.113883.6.1')",
"jti": "1234",
"person_id":"RSSMRA22A01A399Z^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO",
"pem_path": "d:\fse20\A1#111#DECSISTEMISRLXX.pem",
"pem_path": "d:\fse20\S1#111#DECSISTEMISRLXX.pem"
}

In attesa di riscontro invio cordiali saluti.

**Comment by vigliottim** [comment]
Buongiorno, 
_{password}_ è la password della chiave privata utilizzata per la generazione delle CRM.
_{alias}_ è l'alias del certificato di firma ed è necessario impostarlo per utilizzare il tool _jwt-generator_. 
Può essere definito tramite il parametro` -name` nel comando: 
`openssl pkcs12 -export -name alias_cert -out client_sign.p12 -inkey client_sign.key -in client_sign.pem`
`Enter Import Password:`
In seguito, verrà richiesto l'inserimento della password della chiave privata scelta in precedenza per la generazione CSR, e, successivamente, di una nuova password per visualizzare la chiave privata cifrata con quest'ultima. 
Nel caso si voglia vedere la chiave in chiaro è possibile aggiungere l'opzione` -nodes`.
 
In merito all'errore riscontrato sulla generazione dei token, questo potrebbe essere causato dal carattere **\** usato nel campo _pem_path_. 
Per risolverlo può provare a sostituire **\** con **/** oppure **\\**. 
Inoltre, il campo _pem_path_ è duplicato e il campo _p12_path_ (obbligatorio) non è presente. 
La invitiamo ad effettuare le correzioni indicate e riprovare. 
Rimaniamo a disposizione per chiarimenti.

**Comment by enzocap** [comment]
Buongiorno e grazie per la celere risposta,
purtroppo non è ancora chiaro quale è la la password della chiave privata utilizzata per la generazione delle CRM in quanto, seguendo la vs. documentazione ho usato il comando:

openssl req -new -newkey rsa:2048 -nodes -keyout nome_chiave.key -out nome_csr.csr

e non ho dato alcun valore alla richiesta "A challenge password []:" ... si tratta di tale password? Se si, come procedo?

Inoltre, premesso che mi avete inviato i certificati con nome A1#111#xxxxxxxxx.pem ed S1#111#xxxxxxx.pem mi confermate che per utilizzarli devo rinominarli eliminando o sostituendo i caratteri #?

Grazie.

Saluti.

**Comment by IStacchiotti** [comment]
Buongiorno, relativamente al primo punto, la password è quella con cui è stata cifrata la chiava privata.
Se voi non l'aveve definita in precedenza, vi invitiamo a eseguire il comando indicato nel commento precedente (openssl pkcs12 -export -name alias_cert -out client_sign.p12 -inkey client_sign.key -in client_sign.pem), facendo click su enter quando compare il prompt che chiede l'inserimento della password. Se ciò non dovesse essere risolutivo per la generazione dei p12, consigliamo di ripetere il processo dall'inizio, creando delle chiavi private cifrate tramite password da salvare opportunamente e da non condividere.
In merito all'ultimo punto, specifichiamo che non è necessario rinominare i certificati. 
Segnaliamo infine che, ai fini dell'invocazione dei servizi del Fascicolo 2.0, sarà necessario referenziare nel file data.json per la generazione dei token i file pem e p12 di firma (S1), mentre per la predisposizione della connessione http, sarà necessario referenziare il p12 di autenticazione (A1). Rimaniamo a disposizione per ulteriori richieste di supporto

**Comment by enzocap** [comment]
Buongiorno,
ho effettuato nuovamente la richiesta dei certificati .pem in quanto anche ricavando il certificato di Alias come da vs. istruzioni, alla generazione dei token ricevo il seguente errore:

Please check for malformed input; please remember that password p12 and json data are mandatory.

Nel frattempo, vorrei maggiori chiarimenti (o riferimenti di doumentazione) su alcuni campi del file data.json, in particolare nel caso di validazione di Referti di Laboratorio Analisi:

"subject_role": "AAS",
"purpose_of_use": "TREATMENT",
"iss": "jwt-issuer",

"resource_hl7_type": "('11502-2^^2.16.840.1.113883.6.1')",
"jti": "1234", 

Grazie. Saluti.

**Comment by LucaRogledi** [comment]
Buongiorno, 
Lasciamo di seguito il [link]( https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt ) alla documentazione dove può trovare le informazioni richieste relative ai campi contenuti nel JWT.
Restiamo a disposizione per ulteriori chiarimenti.
Grazie.

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. 
Si può procedere con la riapertura in caso fosse necessario ulteriore supporto. 
Grazie.

**Comment by enzocap** [comment]
Buongiorno,
in merito alla nuova richiesta di certificati (fatta in data 01/03) di cui al mio precedente post, volevo solo sollecitare l'invio degli stessi in quanto ancora non pervenuti.

Grazie Saluti

**Comment by vigliottim** [comment]
> DEC Sistemi Srl

Buongiorno, le comunichiamo che i certificati le sono stati inviati in data odierna. 
Restiamo a disposizione per ulteriori richieste di supporto.
Grazie.

**Comment by enzocap** [comment]
Buongiorno e grazie per i nuovi certificati,

che per comodità di manipolazione ho rinominato Auth_Cert.pem e Sign_Cert.pem.

Ho generato il file p.12 tramite il comando: openssl pkcs12 -export -name Alias_cert -out Sign_Cert.p12 -inkey Sign_Cert.key -in Sign_Cert.pem (mi viene richiesta una password che digito e confermo)
Ho modificato il file data.json con i due path:

		"pem_path": "d:\fse20\Sign_Cert.pem",
		"p12_path": "d:\fse20\Sign_Cert.p12"

Eseguo il comando: java -jar jwt-generator.jar -d data.json -a Alias_cert -p ******* -t 1   (dove ******* è la password impostata nel comando precedente)

ma ottengo lo stesso errore che ottenevo con le precedenti prove (ed i precedenti certificati):

An error occur while trying to generate JWT, hope this can help:
EXCEPTION: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 18 column 24 path $.
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 18 column 24 path $.

Faccio notare che la riga 18 è quella che contiene il pat con Sign_Cert.pem.

Grazie. Saluti.

**Comment by vigliottim** [comment]
Buongiorno, la invitiamo a sostituire nei campi _p12_path_ e _pem_path_ il carattere \ con \\ oppure / e riprovare.

**Comment by vigliottim** [comment]
Buonasera, la invitiamo a consultare l'issue [#413](https://github.com/ministero-salute/it-fse-support/issues/413) con le soluzioni proposte. Rimaniamo a disposizione nel caso in cui non riuscisse a risolvere il problema.

**Comment by enzocap** [comment]
Buonasera,
in merito al post di riferimento, vorrei capire se la versione della jdk 17.0.3 è la minima richiesta o è tassativa (io ho la 21.0.2) e quella di Apache Maven è la 3.9.6.
Inoltre, il certificato da me utilizzato per ottenere il .p12 e quello di firma e non di autenticazione.
A questo punto dovrebbe essere anche nel mio caso la mancanza del bouncy castle nella jdk? se si, come verificare la cosa ed eventualmente effettuare l'integrazione?
Grazie. Saluti.

**Comment by IStacchiotti** [comment]
Buongiorno, 
Per quanto riguarda i certificati, dovreste aver ricevuto via email due pem, uno di firma (#S1%), e l'altro di autenticazione (#A1%): vanno ricavati da questi **due** certificati p12, rispettivamente uno di firma a partire dal primo, e uno di autenticazione a partire dal secondo. Il p12 di autenticazione andrà referenziato per la crazione del canale http da parte del client, il p12 di firma (da referenziare nel json insieme al pem di firma) va usato invece per firmare i token.
 
Inoltre, la invitiamo ad utilizzare le versioni indicate in [documentazione](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator#token-customization) per Maven e JDK: dalla nostra esperienza abbiamo appreso che altre versioni, in particolare per JDK, potrebbero originare errore.
 
La invitiamo pertanto a riprovare seguendo le indicazioni riportate e rimaniamo in attesa di un gentile riscontro sull'esito della chiamata, grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, 
Le suggeriamo di provare aggiungendo la seguente parte di comando evidenziata in bold:
(comando di esecuzione jwt-generator) **>> output_jwt.log 2>&1**
Dal momento che l'errore riscontrato con il tool è risolto, procediamo alla chiusura.
Grazie
