### ISSUE TITLE
Mancato riscontro al questionario per richiesta accreditamento

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#636]
Buongiorno,
in data 16.2.2024 abbiamo compilato il questionario per richiesta di accreditamento, di cui abbiamo conservato copia completa di id, ma a tutt'oggi non abbiamo ricevuto nessun tipo di riscontro. Vorremmo sapere quantomeno se la richiesta è andata a buon fine, trattandosi di un semplice modulo web.
Grazie.
Infoservice di Francesco Leo

**Comment by IStacchiotti** [comment]
Buongiorno, Le segnaliamo che non risultano pull request recenti aperte per Infoservice.
La compilazione dell'EuSurvey è uno dei primi passi da percorre ai fini dell'accreditamento, il cui processo è descritto in dettaglio al seguente [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/accreditamento#fase-1-processo-di-accreditamento). La rimandiamo anche a questo [link](https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#accreditamento-fse-20-draft) della documentazione in cui sono riportate delle indicazioni per l'apertura delle pull request.
Rimaniamo a disposizione per eventuali chiarimenti

**Comment by infoserviceonline** [comment]
Quindi, secondo quanto leggo, io, che mi trovo in Puglia, non devo utilizzare il Middleware per operare in ambiente di test, cosa che finora ho fatto, ricevendo tra l'altro tutti riscontri positivi agli invii. Devo invece utilizzare il Gateway nazionale? Potete chiarirmi questo dubbio? Per essere ancora più chiaro: io credo i Pdf con CDA2 interno, li firmo Pades, li rendo conformi e poi? Dove li devo inviare, al Middleware o al Gateway? Grazie per l'attenzione.

**Comment by vigliottim** [comment]
Buonasera, 
se la regione Puglia vi mette a disposizione un middleware per richiamare i servizi del FSE 2.0, è possibile utilizzarlo come intermediario per effettuare le chiamate.
Infatti, come riportato in documentazione al link https://github.com/ministero-salute/it-fse-support/tree/main/doc/middleware-regionale., sono due i modelli architetturali attuabili: 
Modello 1: prevede l'inserimento di un componente intermedio, quale il middleware regionale, che si interfaccia con il Gateway e che sarà trasparente rispetto ai workflow definiti da specifica:
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/18c31bea-bdbd-41fd-9746-1e77187e1552)

Modello 2: non prevede nessun componente intermedio ma il sistema produttore si interfaccia direttamente con il Gateway. 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/565b3925-5bd5-480c-a837-51ce3fd9fc92)

In merito al processo, questo prevede la validazione da parte del sistema produttore dei pdf conformi con CDA2 iniettati, la firma e, a seguire, la pubblicazione da parte del repository documentale locale. 
In funzione del modello adottato, le chiamate in questione avverrano direttamente verso il Gateway, anziché usando il middleware come intermediario.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by infoserviceonline** [comment]
E' esattamente quello che dico io, ho visionato la stessa documentazione ed inviato al referente lo stesso grafico, ma attualmente pare che il Middleware non sia operativo per il nuovo CDA2, mentre per il vecchio continua a darci esito positivo ed URI valido ad ogni invio di referto. Considerando che avevamo già integrato quasi tutto tramite i "vecchi" servizi esposti dal SIST, se dobbiamo "solo" cambiare i CDA2 con i nuovi requisiti il lavoro sarebbe minore, se invece saremo costretti anche a rifare tutte le chiamate, duplicando quelle al web service con quella al Gateway, ovviamente perderemo un bel po' di tempo, che potremmo risparmiare utilizzando il Middleware. Sinceramente non capisco perchè non possiamo usare, come previsto, il Middleware, ma immagino non dipenda da voi.

**Comment by LucaRogledi** [comment]
Buonasera,
La invitiamo a verificare che il middleware si stia interfacciando con il sistema FSE2.0.
In caso contrario, il middleware in questione non può essere usato per l'integrazione con il sistema FSE2.0 e l'accreditamento.
Restiamo a disposizione per ulteriori chiarimentil.
Grazie.

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto riscontri, il presente ticket viene chiuso. 
Si può procedere alla riapertura nel caso in cui abbia bisogno di ulteriore supporto. 
Grazie.
