### ISSUE TITLE
info accreditamento - pubblicare repo

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#638]
buongiorno, in questi giorni abbiamo ricevuto mail dai clienti in puglia per fse 2.0
Ci siamo attivati in tal senso quanto prima e abbiamo predisposto i file pdf, json e xls per l'accreditamento.

E' disponibile una guida per il caricamento di tali file su "it-fse-accreditamento/tree/main/GATEWAY" ?
Ho predisposto i file sul mio desktop, nonché creato la repo sul mio account. Manca la copia sulla vs. archivio

Se può essere utile, https://github.com/ds-tommaso/fse2_0---2024.02.28 è il link alla mia repo

**Comment by LucaRogledi** [comment]
Buongiorno,
Di seguito può trovare il link alla guida contenente le indicazioni per effettuare la pull request: [Pull Request Accreditamento](https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#pull-request)
Restiamo a disposizione per eventuali chiarimenti.
Grazie.

**Comment by ds-tommaso** [comment]
Ho scaricato git hub desktop. E' un'oretta che clona la repo del gateway. Lo lascio fare, altresì ci sono alternative ?

**Comment by LucaRogledi** [comment]
Confermiamo che deve attendere il completamento, dopodiche può procedere effettuando la pull request.
Grazie

**Comment by ds-tommaso** [comment]
Buonasera, ad ora il processo di clonazione sta continuando: siamo a circa 3 ore.
C'è la possibilità di inviarvi questo primo accreditamento tramite metodi alternativi? Lascerei continuare il download, così da rendermi indipendente per le prossime volte.

Mi faccia sapere..

**Comment by LucaRogledi** [comment]
Buonasera,
purtroppo non sono presenti alternative, l'unico modo previsto è quello già segnalato, riportato precedentemente in documentazione.
Restiamo a disposizione in caso di ulteriore supporto.
Grazie

**Comment by ds-tommaso** [comment]
Buonasera, segue uno screenshot dove è evidenziato l'errore _invalid path_ per il fornitore A1#200000swmediatetec.
Avete modo di risolvere ? Eventualmente, sarebbe possibile un contatto telefonico ?

In Puglia, qualche cliente deve indicare all'asl di riferimento la terna ID - Vendor - Version.
Grazie sempre. 

![Screenshot 2024-02-28 173129](https://github.com/ministero-salute/it-fse-support/assets/58989593/ca6aba94-0adc-4909-99a5-9fd17b4d7f7d)

**Comment by vigliottim** [comment]
Buongiorno, non risulta aperta nessuna PR a suo nome. 
Può aprirla cliccando sul bottone "New pull request" al link https://github.com/ministero-salute/it-fse-accreditamento/pulls e, dopo aver selezionato i branch corretti, cliccando il bottone "Create pull request".
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/261f5521-4913-41bb-800c-608eac6fe99c)
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/1c1e9fab-1919-4223-a5dc-d156751469eb)

La rimandiamo al link https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#accreditamento-fse-20-draft dove è presente la documentazione relativa.
Rimaniamo a disposizione per chiarimenti.

**Comment by ds-tommaso** [comment]
buongiorno, dovrebbe essere la pull 1230, dal titolo "Richiesta Accreditamento A1#111DATASOFTWARE - Referto di Laboratorio"

https://github.com/ministero-salute/it-fse-accreditamento/pull/1230

**Comment by vigliottim** [comment]
Buongiorno, la pull-request è stata creata correttamente e presa in carico. Riceverà aggiornamenti via e-mail. 
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
