### ISSUE TITLE
Certificati per l'ambiente di test

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#639]
Buongiorno, credo ci sia un malinteso in atto. Abbiamo mandato una prima richiesta di certificati, sbagliando, perchè anzichè inserire solo la CSR abbiamo inserito dei certificati autoprodotti. Successivamente ci siamo accorti dell'errore ed abbiamo inviato la CSR corretta, ma abbiamo ricevuto riscontro solo alla mail errata e non a quella corretta.
A quanto ci è dato di capire dalle indicazioni noi inviamo due richieste, una per autenticazione ed una per firma, e VOI ci rilasciate i certificati. Quindi non dobbiamo utilizzare certificati autoprodotti nè tantomeno acquistare certificati SSL che sarebbero inutili.
Premesso che ci scusiamo per l'equivoco, potete verificare lo stato della nostra richiesta?
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, le chiediamo gentilmente di confermarci di aver ricevuto l'e-mail con i certificati richiesti. Grazie.

**Comment by infoserviceonline** [comment]
Buongiorno, ho ricevuto qualche minuto fa i certificati. Vi ringrazio per la celerità e mi scuso ancora per il nostro errore.
Saluti.

**Comment by vigliottim** [comment]
Grazie per la sua risposta. 
Rimaniamo a disposizione per ulteriori richieste di supporto.
