### ISSUE TITLE
Replacement documento - non conformità rispetto alle specifiche

### ISSUE THREAD

**Issue by MarcoKnezevichInsiel** [ministero-salute/it-fse-support#64]
Buongiorno,
ho effettuato la seguente sequenza di operazioni:
- validazione di un documento (in allegato)  con esito `OK` e workflowInstanceId `2.16.840.1.113883.2.9.2.60.4.4.de7acf114d14592aa41ae1c77bcc862e8200238c633ecba63afaf7bd38a6c6d3.c2b3d53f83^^^^urn:ihe:iti:xdw:2013:workflowInstanceId`
- pubblicazione del documento  con esito `OK` e request body in allegato (PUBBLICAZIONE_LDO_TEST_1.txt)
- replacement del documento con esito `KO`, request body in allegato (REPLACEMENT_LDO_TEST_1.txt), `idDoc=2.16.840.1.113883.2.9.2.60.4.4^TEST_0002`  ed errore: 

 {
  "traceID": null,
  "spanID": null,
  "warning": null,
  "type": "https://govway.org/handling-errors/400/InvalidRequestContent.html",
  "title": "InvalidRequestContent",
  "status": 400,
  "detail": "Request content not conform to API specification: Validation error(s) :\nbody.requestBody: **Additional property 'priorita' is not allowed.** (code: 1000)\nFrom: body.requestBody.<#/components/schemas/PublicationUpdateReqDTO>.<additionalProperties>\nbody.requestBody: **Additional property 'workflowInstanceId' is not allowed**. (code: 1000)\nFrom: body.requestBody.<#/components/schemas/PublicationUpdateReqDTO>.<additionalProperties>\n",
  "instance": null,
  "govwayId": null,
  "workflowInstanceId": null
}

credo ci sia una non conformità rispetto alle [specifiche di replacement](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#611-messaggio-di-richiesta-esempio-pubblicazione-sostituzione-documento-con-attachment)
[LDO_FVG_TEST.pdf](https://github.com/ministero-salute/it-fse-support/files/10445343/LDO_FVG_TEST.pdf)
[PUBBLICAZIONE_LDO_TEST_1.txt](https://github.com/ministero-salute/it-fse-support/files/10445370/PUBBLICAZIONE_LDO_TEST_1.txt)
[REPLACEMENT_LDO_TEST_1.txt](https://github.com/ministero-salute/it-fse-support/files/10445394/REPLACEMENT_LDO_TEST_1.txt)

**Comment by IStacchiotti** [comment]
Buongiorno Marco, grazie mille per la segnalazione. In effetti nella chiamata di REPLACE 'priorita' e 'workflowInstanceId' non sono ammessi. Procederemo con l'adeguamento del documento.

**Comment by IStacchiotti** [comment]
Buon pomeriggio, come da comunicazione su Slack, è stata aggiornata la documentazione. Per questo motivo procediamo con la chiusura del ticket, facendo presente che è possibile procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie
