### ISSUE TITLE
accreditamento: Mancato Accreditamento

### ISSUE THREAD

**Issue by fabiodap** [ministero-salute/it-fse-support#640]
Buongiorno,

in data odierna abbiamo ricevuto la seguente risposta alla nostra richiesta di accreditamento per CDA RSA:

_Con la presente si comunica il mancato superamento dei seguenti test [147] per il servizio [validazione/pubblicazione] del Fornitore [A1#111FUJIFILM000] - Vendor:[Fujifilm_Italia_S.p.A] - ID: [Synapse_Value] - Version: [1.6] - Sha: [430b7161a78f176333b0e1cf164d30d40dd8bb9b] in data odierna._

in allegato la lista degli Errori.

Non mi tornano alcune cose:

riportate i seguenti errori:

  _"id" : 147,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "error code='001' attribute='code' actual = '' expected = '62387-6' 
 ClinicalDocument/component/structuredBody/component/section[ID='Prestazioni']/code /error"

  "id" : 147,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "error code='002' attribute='codeSystem' actual = '' expected = '2.16.840.1.113883.6.1' ClinicalDocument/component/structuredBody/component/section[ID='Prestazioni'] code /error"

  "id" : 147,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "error code='005' attribute='' actual = '' expected = 'Prestazioni' ClinicalDocument/component/structuredBody/component/section[ID='Prestazioni']/title /error"_

ho estratto il CDA dal PDF che è allegato a questo messaggio. 

[TEST-01_RSA.pdf](https://github.com/ministero-salute/it-fse-support/files/14445835/TEST-01_RSA.pdf)
[errors (1).json](https://github.com/ministero-salute/it-fse-support/files/14445843/errors.1.json)

Qui l'estratto concernente le Prestazioni eseguite:

      _<component>
        <section>
          <code code="62387-6" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Interventi"/>
          <title>Interventi</title>_

L'unico vero errore è il <title> della sezione.

Per quanto riguarda il displayName il documento di HL7Italia: HL7IT-IG_CDA2_RSA-v1.1-S.pdf, al punto 5.5.1 dice che:

_Attributo                       Tipo                   Valore            Dettagli

displayName                 ST                      **Interventi**       Nome della section._

Mentre voi riportate un errore:

_{
  "id" : 147,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "error code='004' attribute='displayName' actual = '' expected = 'Interventi' ClinicalDocument/component/structuredBody/component/section[ID='Prestazioni']/code /error"
}_

Allego imagine della pagina del documento:
 
![Estratto_prestazioni](https://github.com/ministero-salute/it-fse-support/assets/93272944/5b91f5ca-e5a6-446b-9e50-2af2554a4995)

Come mai?
 
Riportate anche i seguenti errori:

}, {
  "id" : 147,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "error code='006' attribute='classCode' actual = '' expected = 'ACT' ClinicalDocument/component/structuredBody/component/section[ID='Prestazioni']/entry/act/error"
}, {
  "id" : 147,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='007' attribute='moodCode' actual = '' expected = 'EVN' ClinicalDocument/component/structuredBody/component/section[ID='Prestazioni']/entry/act<  /error "
}, {
  "id" : 147,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "error code='008' attribute='value' expected = 'Valorizzare con data valida' ClinicalDocument/component/structuredBody/component/section[ID='Prestazioni']/entry/act/effectiveTime /error"
}, 

qui l'estratto del CDA in questione:

          _<entry typeCode="DRIV">
            <act classCode="ACT" moodCode="EVN">
              <code code="E56938363" codeSystem="2.16.840.1.113883.2.9.2.10.6.11" codeSystemName="Nomenclatore Prestazioni Regione Piemonte" displayName="E56938363">
                <originalText><reference value="#PrestazioneDesc1"/></originalText>
                <translation code="294" codeSystem="2.16.840.1.113883.2.9.2.1090301.6.11" codeSystemName="Dizionario delle prestazioni sanitarie OSPEDALE SANT'ANNA" displayName="ANGIO TC DELLE ARTERIE CORONARIE"/>
              </code>
              <text><reference value="#Prestazione1"/></text>
              <statusCode code="active"/>
              <effectiveTime value="20221107113710+0100"/>
            </act>
          </entry>_

Mi risulta che tutto quello che voi riportate come errore sia invece correttamente valorizzato.
Mi spiegate per cortesia, forse non capisco io il senso degli errori che riportate.

Saluti,
Fabio

**Comment by fabiodap** [comment]
Per quanto riguarda le procedure Operative, che al momento i ns. applicativi non gestiscono, e possibile popolare la relativa sezione con gli stessi dati della Prestazione eseguita?

Nella documentazione di HL7Italia l'esempio indicato fa esattamente cosi.
Oppure mettiamo il caso di test come non applicabile? Il validatore non ha dato alcun errore quando è stato eseguito il test.

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate risulta che il CDA di RSA da lei utilizzato per il Caso di Test 1 presenta i seguenti errori secondo la [documentazione](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/7-Referto%20Specialistico%20Ambulatoriale/CDA2_Referto_Specialistica_Ambulatoriale_OK.xlsx): 

- le seguenti section _ClinicalDocument/component/structuredBody/component/section[@ID=Prestazioni]_ e _ClinicalDocument/component/structuredBody/component/section[@ID=Referto]_ non hanno gli attributi obbligatori _id_ correttamente valorizzati (<section id="Prestazioni"...>, <section id="Referto"...>)

![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/efd91b90-4d72-4221-b521-2dcf0eb44a3a)
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/8a1ad536-ef85-4187-8a8e-a879b4bf6c8e)

- l'elemento _ClinicalDocument/component/structuredBody/component/section[@ID=Prestazioni]/title_ deve essere valorizzato con "Prestazioni" 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/1ecff257-a87b-4113-b90f-67a2f21fc744)

- l'elemento _ClinicalDocument/component/structuredBody/component/section[@ID=Prestazioni]/entry/act/entryRelationship/procedure_
e i relativi attributi _classCode_ e _moodCode_, indicati come obbligatori, non risultano presenti

La invitiamo ad effettuare le correzioni indicate e riprovare.
La informiamo che è stato messo a disposizione il tool gtw-certifier per eseguire offline la verifica dei test case di validazione ok richiesti durante la fase di accreditamento: https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/gtw-certifier
In aggiunta, le inviamo il link di esempio per il CDA "RSA - Caso di Test 1" che può esserle utile: https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/Documenti%20XML%20Casi%20OK/7%20-%20Casi%20OK%20Referto%20Specialistico%20Ambulatoriale/RSA%20-%20Caso%20di%20Test%201.xml

> Per quanto riguarda le procedure Operative, che al momento i ns. applicativi non gestiscono, e possibile popolare la relativa sezione con gli stessi dati della Prestazione eseguita?
> 
> Nella documentazione di HL7Italia l'esempio indicato fa esattamente cosi. Oppure mettiamo il caso di test come non applicabile? Il validatore non ha dato alcun errore quando è stato eseguito il test e ha restituito status 201.

In merito alla sua ultima domanda, nel caso particolare in cui non siano disponibili i dati relativi alle Procedure Operative, indicati come obbligatori all'interno dello specifico caso di test contenuto nel file excel dei requisiti, è possibile indicare _NO_ nell’apposita colonna _"Applicabilità"_, avendo cura di giustificarle opportunamente tale scelta nella colonna _"Razionale di applicabilità"_.

Restiamo a disposizione per chiarimenti.

**Comment by vigliottim** [comment]
Buongiorno, la informiamo che i test case di tipo KO non sono verificabili tramite il tool _gtw-certifier_ (come indicato in [documentazione](https://github.com/ministero-salute/it-fse-gtw-tools/blob/main/gtw-certifier/README.md), per questo è presente la lista `TEST NON VERIFICABILI` nell'output. 
Dai risultati ottenuti si evince che gli unici casi di test che il tool poteva verificare sono stati superati con successo.
Per conoscere l'esito finale del processo di accreditamento è necessario procedere con l'apertura di una pull-request come da [indicazioni](https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#procedura-di-caricamento-dei-risultati) e attendere aggiornamenti via e-mail. 
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by fabiodap** [comment]
Grazie.
La issue può essere chiusa.
