### ISSUE TITLE
Errore validazione Gateway

### ISSUE THREAD

**Issue by vittorioveneziano** [ministero-salute/it-fse-support#641]
Buongiorno,
in riferimento a quanto in Oggetto, vi segnaliamo il seguente messaggio di errore ricevuto dal Gateway successivamente all'invio del documento Ambulatoriale prodotto nel formato PDF/A-3B tramite iniezione del CDA2 come EmbeddeFiles (attach):

- validazioneGatewayFSE - Risposta validazione: (IDEN_VERSIONE = 42787985) -> {traceID=8b6ec0ae1e0c5a58, spanID=8b6ec0ae1e0c5a58, type=/msg/cda-element, title=Errore in fase di estrazione del CDA., detail=Error while extracting CDA from PDF document, status=400, instance=/cda-extraction, workflowInstanceId=UNKNOWN_WORKFLOW_ID}

Attualmente, per aggirare il problema, inviamo i documenti nel formato PDF/A-3B tramite iniezione del CDA nell'elemento XFAResource.

Restiamo in attesa di un gentile riscontro in merito.
Grazie
Cordiali saluti

**Comment by LucaRogledi** [comment]
Buonasera,
Dalle analisi effettuate risulta che nella request al servizio di validazione è stata scelta la modalità "RESOURCE" ({"healthDataFormat":"CDA","mode":"RESOURCE","activity":"VALIDATION"}), anziché la modalità "ATTACHMENT" dal momento che il cda è iniettato all'interno del pdf.
La invitiamo gentilmente a riprovare modificando il parametro mode della requestBody della chiamata come segue:
{"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VALIDATION"}
Restiamo a disposizione per ulteriore supporto.
Grazie.

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. 
Si può procedere con la riapertura in caso fosse necessario ulteriore supporto. Grazie.
