### ISSUE TITLE
Errore cvc-datatype-valid.1.2.3

### ISSUE THREAD

**Issue by mrepu** [ministero-salute/it-fse-support#643]
Buongiorno,

abbiamo un referto in cui è presento come valore di un esame ">90"
![image](https://github.com/ministero-salute/it-fse-support/assets/122879493/5b770450-7a71-4259-8aeb-9aa68315cf33)

che nel xml del cda è costruito nel seguente modo 

<value xsi:type="PQ" value="&gt;90" />

durante la pubblicazione di un referto riceviamo l'errore

{"type":"
[https://govway.org/handling-errors/400/InvalidRequestContent.html","title":"InvalidRequestContent","status":400,"detail":"cvc-datatype-valid.1.2.3:](https://govway.org/handling-errors/400/InvalidRequestContent.html%22,%22title%22:%22InvalidRequestContent%22,%22status%22:400,%22detail%22:%22cvc-datatype-valid.1.2.3:)
'>90' is not a valid value of union type 'real'.","cart_id":"0142b925-d6f7-11ee-a7b0-0050568608d8"}'

Come devono essere configurati nel xml i risultati che hanno valori contenenti > < >= o <= ? è una casistica frequente e necessaria, non possono essere cancellati i simboli

Grazie,
Marina

**Comment by vigliottim** [comment]
Buongiorno, l'errore viene generato in quanto il valore inserito non è conforme al tipo di dato assegnato all'elemento value. 
Per inserire valori con quantificatori del tipo (>, <, >=, <=), si consiglia di utilizzare un value di tipo ST (stringa).

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto aggiornamenti, procediamo alla chiusura del presente ticket. 
La invitiamo a riaprirlo nel caso in cui avesse bisogno di ulteriore supporto. 
Grazie.
