### ISSUE TITLE
Mancato accreditamento (checklist)

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#644]
faccio seguito la pull datasoftware_srl/intellilab/3 e il messaggio "in seguito alla richiesta di accreditamento per datasoftware_srl/intellilab/3, abbiamo verificato che nel file “report-checklist.xlsx”  sono presenti degli errori che elenchiamo: Impossibile effettuare le analisi sul file fornito. Il file risulta essere corrotto"

non so se la mail è controllata, dunque apro l'issue (ditemi pure se scrivere qui)
qual è il file che risulta corrotto? ho aperto tranquillamente il file excel e i documenti pdf, anche riscaricandoli da git

**Comment by IStacchiotti** [comment]
Buongiorno,

Le confermiamo che questo è il canale corretto per avanzare richieste di supporto, anche in merito a errori riscontrati nel processo di accreditamento. L'errore in questione è relativo al file "report-checklist.xlsx": nel momento in cui proviamo ad aprirlo avendolo scaricato da GitHub, si apre la finestra mostrata di seguito, che indica che il file è stato corrotto.
<img width="622" alt="Screenshot 2024-03-01 091556" src="https://github.com/ministero-salute/it-fse-support/assets/122798799/82ff01ea-0089-41e3-9f56-af6bffd3d19f">
Le suggeriamo di ripartire dal template pulito della checklist caricato in documentazione, e di ripopolarlo nuovamente. Sarà possibile sostituire il nuovo file excel al precedente nella medisima pr #1230, tramite una commit correttiva.

Rimaniamo a disposizione per ulteriori richieste di supporto, grazie.

**Comment by ds-tommaso** [comment]
potete riprovare: dovreste trovare due commit

**Comment by IStacchiotti** [comment]
Abbiamo verificato ma purtroppo l'errore persiste. La invitiamo a seguire il suggerimento fornito nel messaggio precedente, avendo cura di copiare eventualmente come valori i dati nel template vuoto (al [link](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/accreditamento-checklist_V8.1.3.xlsx)), e a procedere nuovamente con il caricamento. Grazie

**Comment by ds-tommaso** [comment]
Ho riscaricato il file e modificato con "WPS Office", senza portare modifiche al layout (colori, dimensioni ecc.)
Ho eseguito la commit e provato con successo il download dal link che segue:

https://github.com/ministero-salute/it-fse-accreditamento/blob/983b3f6b77ad0cb69252cec4170bb0116a9fbe1a/GATEWAY/A1%23111DATASOFTWARE/DATASOFTWARE_SRL/INTELLILAB/3/report-checklist.xlsx

**Comment by IStacchiotti** [comment]
Grazie. La pull request è stata presa in carico per le successive elaborazioni. Si procede pertanto alla chiusura del ticket, seguiranno aggiornamenti via email con l'esito delle verifiche. Sarà possibile procedere con l'apertura di una nuova segnalazione, in caso di ulteriori richieste di supporto.

**Comment by ds-tommaso** [comment]
corretto il caso 55
