### ISSUE TITLE
Documento XML di test mancante

### ISSUE THREAD

**Issue by medinformatica** [ministero-salute/it-fse-support#645]
Buongiorno,
in questa cartella:
https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/Documenti%20XML%20Casi%20OK/7%20-%20Casi%20OK%20Referto%20Specialistico%20Ambulatoriale

non vedo il documento XML per il caso di test 0 (precisamente quello con ID 374 nella checklist).

E' possibile averlo a disposizione?
Grazie

**Comment by vigliottim** [comment]
Buongiorno, gli esempi relativi al Caso di Test 0 non sono disponibili per nessuna tipologia documentale.
Può fare riferimento a questo documento per la predisposizione del CDA: https://hl7itig.art-decor.pub/hl7itig-html-20231222T103411/dataset.html, tenendo presente che i Casi di Test 0 prevedono solo le sezioni obbligatorie per HL7 Italia. 
Rimaniamo a disposizione per chiarimenti.

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. 
Si può procedere con la riapertura in caso fosse necessario ulteriore supporto. 
Grazie.
