### ISSUE TITLE
Inserimento erogazioni nel FSE

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#646]
Buongiorno, leggo nella documentazione che, tra i documenti da inviare, ci sono anche le erogazioni specialistiche.
A parte che negli esempi dei CDA non trovo niente sull'argomento, non c'è nemmeno il CDA nelle specifiche di riferimento che leggo su HL7: http://www.hl7italia.it/hl7italia_D7/node/2359
Potete cortesemente aiutarmi a capire se si devono inviare e come?
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, tra le tipologie documentali disponibili per l'accreditamento non è ancora stata introdotta "Erogazione Specialistica (erogS)": https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione 
La invitiamo a monitorare la relativa pagina in attesa di aggiornamenti sulle specifiche di HL7 Italia: https://hl7itig.art-decor.pub/hl7itig-html-20230524T122643/index.html
Chiudiamo il presente ticket e rimaniamo a disposizione per ulteriori richieste di supporto.
