### ISSUE TITLE
FileSizeLimitExceededException + url produzione gateway di validazione

### ISSUE THREAD

**Issue by snewels** [ministero-salute/it-fse-support#647]
Buonasera, 
in ambiente di produzione, per la "pre-validazione" delle LDO, stiamo utilizzando il seguente url: 
"https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1".
Pur essendo un url di test, considerato lo scopo puramente validativo (della pubblicazione si occupa un altro applicativo), la soluzione adottata è efficace.

Come già segnalato da altri, c'è però un limite di upload di 1048576 bytes; riporto infatti un esempio di errore.
{
  "traceID": "28e05f8ecb09862a",
  "spanID": "28e05f8ecb09862a",
  "type": "/msg/generic-error",
  "title": "Errore generico.",
  "detail": "Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.impl.FileSizeLimitExceededException: The field file exceeds its maximum permitted size of 1048576 bytes.",
  "status": 500,
  "instance": ""
}

Ho provato a cercare l'indirizzo di produzione del succitato servizio di validazione ma non sono riuscito a trovarlo, è possibile avere informazioni in merito?

Grazie.

**Comment by LucaRogledi** [comment]
Buonasera,
La ringraziamo per la segnalazione, siamo a conoscenza di questo vincolo e sono in corso al memento della analisi sul sizing da prevedere (la rimandiamo alla issue [#365](https://github.com/ministero-salute/it-fse-support/issues/365)). 
il servizio non è ancora in produzione, la invitiamo a monitorare il canale Slack per aggiornamenti riguardo l'indirizzo di produzione. 
Grazie
