### ISSUE TITLE
Ottenere i token di autenticazione e firmma.

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#648]
Buonasera, perdonate l'ignoranza, ma finora ho usato poco le chiamare Rest ed ho difficoltà a capire come ottenere i Token per l'FSE (ovviamente ho già i certificati).
Di solito, in altri ambienti, uso una chiamata all'url tipo questa: [http://000.000.0.0:1122/LXX/api/a/Authenticate/requestAuth], e ricevo un Json di questo genere con il token:
{"sRequestStatus":"Success","sMessage":"","auth":"eNpLsjBPSzY0MDJLTrYwTE21ME82MDc1MDdKNjcxNzQwNQEAkA8IMw=="}
ma nel caso del FSE non trovo da nessuna parte l'Url di riferimento e la chiamata per ottenere i token. Mi sfugge qualcosa? 
Grazie per l'attenzione.

**Comment by vigliottim** [comment]
Buonasera, la invitiamo a consultare la documentazione al link https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway, dove potrà trovare le informazioni richieste. Inoltre, la informiamo che al link https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator è disponibile il tool JWT generator che consente di generare il JWT per effettuare le chiamate ai servizi.

**Comment by infoserviceonline** [comment]
Quindi non sono il risultato di una chiamata, come credevo, ma devo crearli io, ho capito bene? 
Mi scuso ancora per il disturbo ma non vorrei sbagliare, abbiamo tutti tempi molto stretti.
Grazie ancora per il supporto.

**Comment by vigliottim** [comment]
Esatto, può generarli usando il tool JWT generator disponibile al link: https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by infoserviceonline** [comment]
Grazie ancora, non so come chiudere il post, ammesso che possa farlo io, ma lo consideri chiuso.
