### ISSUE TITLE
Eliminazione documento - Content-Type 'application/json' unsupported

### ISSUE THREAD

**Issue by MarcoKnezevichInsiel** [ministero-salute/it-fse-support#65]
Buongiorno,
ho effettuato la seguente sequenza di operazioni:

- validazione di un documento (in allegato) con esito OK e workflowInstanceId `2.16.840.1.113883.2.9.2.60.4.4.de7acf114d14592aa41ae1c77bcc862e8200238c633ecba63afaf7bd38a6c6d3.26ef426f78^^^^urn:ihe:iti:xdw:2013:workflowInstanceId`
- pubblicazione del documento con esito OK e request body in allegato (PUBBLICAZIONE_LDO_TEST_2.txt)
- eliminaizone del documento con idDoc=2.16.840.1.113883.2.9.2.60.4.4^TEST_0003 ed errore:

{
  "traceID": null,
  "spanID": null,
  "warning": null,
  "type": "https://govway.org/handling-errors/400/InvalidRequestContent.html",
  "title": "InvalidRequestContent",
  "status": 400,
  "detail": "Request content not conform to API specification: **Content-Type 'application/json' unsupported**",
  "instance": null,
  "govwayId": null,
  "workflowInstanceId": null
}

l'errore sembra non coerente con le [specifiche di eliminazione di un documento](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#5-servizio-di-eliminazione-documento) in cui viene richesto come content-type `application/json`
[LDO_FVG_TEST.pdf](https://github.com/ministero-salute/it-fse-support/files/10445814/LDO_FVG_TEST.pdf)
[PUBBLICAZIONE_LDO_TEST_2.txt](https://github.com/ministero-salute/it-fse-support/files/10445825/PUBBLICAZIONE_LDO_TEST_2.txt)

**Comment by nturri1306** [comment]
salve sto avendo lo stesso problema con GW lite di test su docker
 it-fse-container-lite-it-fse-gtw-dispatcher-1           | java.lang.IllegalArgumentException: Invalid character found in the request target [/v1/documents/2.16.840.1.113883.2.9.2.110.4.4^12345 ]. The valid characters are defined in RFC 7230 and RFC 3986 (modificato)

**Comment by IStacchiotti** [comment]
Buongiorno, potrebbe riprovare omettendo il Content-Type? Grazie mille

**Comment by MarcoKnezevichInsiel** [comment]
Buongiorno, siamo riusciti a far funzionare il servizio.
