### ISSUE TITLE
Testare la correttezza dei Token

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#650]
Buongiorno,
esiste un modo per testare la correttezza dei token generati? Come, per esempio, è possibile testare i CDA con gli schemi Xsd.
Chiedo perchè alcuni parametri non mi sono chiari, ad esempio, nell'Header del token di autenticazione, alla voce iss, trovo come esempio il valore **auth:190201123456XX**, ma nel certificato da voi fornito la CN è **CA Ministero della Salute Test**, mi sembrano troppo diversi per essere compatibili, a meno che non vi riferiate alla CN del soggetto, che è tutt'altra cosa, che nel mio caso sarebbe S1#111#INFOSERVICEONLINEXX.
Grazie per l'attenzione.

**Comment by vigliottim** [comment]
Buongiorno, 
non esistono tool o metodi per testare la correttezza dei token generati ma deve necessariamente effettuare la chiamata. 
Può consultare le informazioni esposte in documentazione al link: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt per verificare se la valorizzazione dei campi in essi contenuti è corretta. 
Nell’esempio da lei citato il campo **_“iss”_** del token di Authorization deve essere valorizzato con _auth_ seguito dal common name assegnato via e-mail contestualmente alla condivisione dei certificati, facendo attenzione al case:  **_“iss”:”auth:S1#111#INFOSERVICEONLINEXX”_**. 
Infine, le consigliamo di validare i token ottenuti utilizzando il sito jwt.io (comparirà il messaggio "Signature Verified"/"Invalid Signature"). 
Restiamo a disposizione per chiarimenti.

**Comment by infoserviceonline** [comment]
Grazie per la risposta, in effetti stavo già usando jwt.io per i controlli. Vi ho chiesto della validazione perchè non trovo corrispondenza tra un JWT creato seguendo pedissequamente lo schema indicato nel vostro link e l'esempio che è presente a fine schema. Faccio un esempio, questo è l'Header del mio JWT, estratto da jwt.io:
{
  "alg": "http://www.w3.org/2001/04/xmldsig-more#hmac-sha256",
  "typ": "JWT",
  "x5c": "LS0tLS1CRUdJTiBQUklWQVRF.........",
  "iss": "auth:S1#111#INFOSERVICEONLINEXX",
  "iat": "1709539704",
  "exp": "1709541504",
  "Jti": "51739807",
  "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
  "sub": "VRDMRC67T20I257E^^^&2.16.840.1.113883.2.9.4.3.2&ISO"
}
Mentre questo è il vostro esempio:
{
  "alg": "RS256",
  "typ": "JWT",
  "x5c": [
    "MIIDXjCCAkagAwIBAgIBAjANBgkqhkiG9w ... 779BM4SOI="
  ]
}
Eppure tutti i campi che ho inserito risultano essere obbligatori, mentre ho omesso quelli opzionali. C'è qualcosa che mi è sfuggito?
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, l'esempio da lei riportato, presente in documentazione, si riferisce solo alla sezione _header_ del token decodificato:
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/bd5abbb9-27b6-451a-abcc-17ce9a4b07e0)
Infatti, non comprende le altre sezioni relative al payload, come i _reserved claims_ e i _custom claims_. 
Pertanto, i campi obbligatori da documentazione non sono tutti presenti.

**Comment by infoserviceonline** [comment]
Ha perfettamente ragione, non l'avevo capito e me ne scuso. Un'ultima domanda: vedo il valore vostro "x5c" racchiuso tra parentesi quadre, mentre le classi che utilizzo, .NET me lo inseriscono come tutti gli altri valori, come si vede nell'esempio sopra. Può rappresentare un problema? Se servono le inserisco io da codice. Non vorrei avere soprese quando finalmente riuscirò ad utilizzare i Token.
Grazie ancora per la rapidità e pazienza.

**Comment by LucaRogledi** [comment]
Buongiorno, 
Le confermiamo che il campo "x5c" deve essere racchiuso tra parentesi quadre come indicato, altrimenti riceverà un errore.
Le segnaliamo inoltre se può esserle di aiuto, che può generare i token usando il tool JWT generator disponibile link: https://github.com/ministero-salute/it-fse-gtw-tools/tree/main

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto aggiornamenti, procediamo alla chiusura del presente ticket. 
La invitiamo a riaprirlo nel caso in cui avesse bisogno di ulteriore supporto. 
Grazie.
