### ISSUE TITLE
Mancato accreditamento CHECKLIST.XLSX

### ISSUE THREAD

**Issue by LibraSistemi** [ministero-salute/it-fse-support#651]
Buongiorno, vi scrivo per il mancato accreditamento per errata compilazione del report
"È necessario NON valorizzare le colonne F, G, H, I poiché il caso di test non è applicabile"

Ho provveduto a modificare il file
GATEWAY/A1#111#LIBRASISTEMISRLXX/LIBRA SISTEMI SRL/Geslab/2.0/report-checklist.xlsx

,ma mi è arrivata una mail identica riportante gli stessi errori di compilazione.

Ho sbagliato qualcosa nell'invio ? Perchè anche ricontrollando ora il file mi sembra corretto
Grazie

**Comment by IStacchiotti** [comment]
Buonasera, abbiamo verificato che gli errori segnalati erano dovuti a dei caratteri sporchi nell'excel: la invitiamo pertanto a non considerare l'ultimo riscontro ricevuto via email. Le confermiamo inoltre che la pull request #1226 è stata ripresa in carico: seguiranno via email gli esiti delle elaborazioni. Chiudiamo pertanto il presente ticket, ma rimaniamo a disposizione per ulteriori richieste di supporto, grazie.
