### ISSUE TITLE
CDA2 paziente assicurato da istituzioni estere (TEAM)

### ISSUE THREAD

**Issue by francesca-medas** [ministero-salute/it-fse-support#652]
Buongiorno, 
Nel tentativo di chiamare il servizio di validazione per un CDA2 RSA riferito a un paziente straniero provvisto di TEAM, otteniamo in risposta il seguente errore:

```
{
	"traceID": "fd15954e4f89dc19",
	"spanID": "fd15954e4f89dc19",
	"type": "/msg/jwt-validation",
	"title": "Campo token JWT non valido.",
	"detail": "JWT payload: non è stato possibile estrarre il codice fiscale del paziente presente nel CDA",
	"status": 403,
	"instance": "/jwt-person-id",
	"workflowInstanceId": "2.16.840.1.113883.2.9.2.30.3.1.4.4.72b74e5ccfe5733f80452fef24df23ab0286e8f0e10188101bba89169f5cf86e.059f63eb61^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```

L'elemento patientRole del CDA2 contiene i seguenti identificativi:
```
<id extension="FRA.80250070070000001" root="2.16.840.1.113883.2.9.4.3.7" assigningAuthorityName="Ministero della Salute"/>
<id extension="FRA.4637465980125364" root="2.16.840.1.113883.2.9.4.3.3" assigningAuthorityName="Ministero della Salute"/>
```
Il primo id rappresenta il numero della tessera TEAM mentre il secondo è il numero di identificazione personale TEAM, come richiesto nel paragrafo 4.1.12.1 delle specifiche **HL7IT-IG_CDA2_RSA-v1.1-S**. Trattandosi di un soggetto assicurato da istituzioni estere, non dispone quindi di codice fiscale.

L'identificativo del paziente trasmesso nel payload del FSE-JWT-Signature è il seguente:
`"person_id": "FRA.80250070070000001^^^&2.16.840.1.113883.2.9.4.3.7&ISO"`

Potreste gentilmente effettuare una verifica per capire la causa del problema?
Grazie,
Francesca

**Comment by fabiodap** [comment]
buongiorno,

mi associo a questa domanda avendo avuto lo stesso tipo di problematica.

**Comment by IStacchiotti** [comment]
Buonasera, è stata appena rilasciata un'evolutiva. Potreste cortesemente riprovare? Rimaniamo a disposizione nel caso in cui l'errore dovesse persistere. Grazie.

**Comment by medas-integrazioni** [comment]
Buongiorno, confermo che ora funziona correttamente e ottengo esito positivo. Vi ringrazio per il supporto.

Colgo l'occasione per segnalare che all'interno dello Schematron del Referto di Specialistica Ambulatoriale _schematron_RSA.sch_ sono riportate come root valide che identificano l'STP in recordTarget/patientRole/id solo quelle di tipo **2.16.840.1.113883.2.9.2.[regione].4.1**. Mancano gli OID **2.16.840.1.113883.2.9.2.[regione].4.1.1** presenti invece negli altri schematron.

**Comment by vigliottim** [comment]
Buongiorno, grazie per la segnalazione. 
La informiamo che gli schematron sono stati aggiornati con gli OID indicati. 
Chiudiamo il presente ticket e rimaniamo a disposizione per ulteriori richieste di supporto.

> Buongiorno, confermo che ora funziona correttamente e ottengo esito positivo. Vi ringrazio per il supporto.
> 
> Colgo l'occasione per segnalare che all'interno dello Schematron del Referto di Specialistica Ambulatoriale schematron_RSA.sch sono riportate come root valide che identificano l'STP in recordTarget/patientRole/id solo quelle di tipo 2.16.840.1.113883.2.9.2.[regione].4.1. Mancano gli OID 2.16.840.1.113883.2.9.2.[regione].4.1.1 presenti invece negli altri schematron.
