### ISSUE TITLE
Compilazione questionario di richiesta accreditamento

### ISSUE THREAD

**Issue by mghi-sined** [ministero-salute/it-fse-support#653]
Buongiorno,

il 16 febbraio u.s. abbiamo compilato il questionario per la richiesta di accreditamento, ma non abbiamo ancora ricevuto 
nessun riscontro in merito.

Volevamo fare anche una ulteriore puntualizzazione. 

Quando, nel questionario,  abbiamo compilato il campo “**Common name nel certificato di accesso**” , abbiamo indicato il common name  utilizzato nella fase di generazione dei documenti CSR di richiesta dei certificati di firma e autenticazione di test che vi abbiamo spedito qualche mese fa.

È corretto? O dobbiamo compilare questo campo specificando il common name del certificato di autenticazione test  (certificato A1#*.pem) che ci avete  rilasciato qualche mese fa ?

Grazie.

Cordiali Saluti,
Massimo Ghirardello
Sined S.r.l.

**Comment by vigliottim** [comment]
Buongiorno, il _common name_ da utilizzare è quello assegnato via e-mail contestualmente alla condivisione dei certificati. Inoltre, le facciamo presente che la compilazione dell'EuSurvey è uno dei primi passi da percorre ai fini dell'accreditamento, il cui processo è descritto in dettaglio al seguente [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/accreditamento#fase-1-processo-di-accreditamento). 
Inoltre, la rimandiamo a questo [link](https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#accreditamento-fse-20-draft) della documentazione in cui sono riportate delle indicazioni per l'apertura delle pull-request.
Rimaniamo a disposizione per eventuali chiarimenti.

**Comment by vigliottim** [comment]
Buongiorno, 
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura del presente ticket.
Potrà riaprirlo nel caso avesse bisogno di ulteriori chiarimenti. 
Grazie.
