### ISSUE TITLE
Problemi con invocazione gateway

### ISSUE THREAD

**Issue by lorenzonet** [ministero-salute/it-fse-support#654]
Salve,
Riscontro un problema con le chiamate Http, facendo delle prove ottengo l'errore **Fail Fail** senza altre indicazioni utili, in allegato il file della risposta con la relativa chiamata.
[postman_result.txt](https://github.com/ministero-salute/it-fse-support/files/14522596/postman_result.txt)

**Comment by lorenzonet** [comment]
Salve, ottengo sempre il solito errore, in allegato la chiamata che viene effettuata, i token sono generati tramite il tool messo a disposizione
[postman_result.txt](https://github.com/ministero-salute/it-fse-support/files/14536459/postman_result.txt)

**Comment by LucaRogledi** [comment]
Buongiorno,
la invitiamo a riprovare rimuovendo il campo "key" e assicurandosi che il certificato utilizzato all'interno del campo "pfx" sia il certificato p12 di trasporto (A1#....).
Grazie

**Comment by lorenzonet** [comment]
Eliminato il campo **key** e inserito nel campo **pxf** il file **A1#111#WEPSERVICESX1.pem** ma ottengo l'errore **BAD_PKCS12_DATA**

**Comment by LucaRogledi** [comment]
Ringraziamo per il rapido riscontro, il campo "pxf" deve contenere il file .p12 ( A1#111#WEPSERVICESX1.p12 ) generato a partire dal file .pem da lei attualmente utilizzato ( A1#111#WEPSERVICESX1.pem ).   
La invitiamo a correggere e riprovare.
Grazie

**Comment by lorenzonet** [comment]
In effetti conteneva già il file p12, gli avevo cambiato nome, non penso che sia un problema, comunque l'ho riestratto con il nome originale, ma il problema rimane, adesso l'errore è **read ECONNRESET**

**Comment by LucaRogledi** [comment]
La invitiamo a verificare che i certificati .p12 siano stati generati correttamente seguendo le indicazioni riportate nella seguente issue: https://github.com/ministero-salute/it-fse-support/issues/591
Restiamo a disposizione in caso l'errore dovesse ripresentarsi.

**Comment by lorenzonet** [comment]
Confermo che il certificato è generato come indicato e che contiene la chiave privata come evidenziato nell'allegato (ho eliminato la parte di chiave privata).
[chiave_p12.txt](https://github.com/ministero-salute/it-fse-support/files/14539166/chiave_p12.txt)

**Comment by LucaRogledi** [comment]
Buonasera,
Analizzando la sua chiamata ricevuta dal sistema, notiamo che il campo "aud" all'interno del token Bearer non è corretto: 
`"aud": "FSE_Gateway"`
La invitiamo ad applicare la seguente correzione e riprovare:
`"aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1"`
Grazie

**Comment by lorenzonet** [comment]
Grazie, mi ero infatti accorto che c'erano due campi (sub, aud) che non andavano bene leggendo questo [thread](https://github.com/ministero-salute/it-fse-support/issues/557), come avevo fatto presente è dovuto al fatto che purtroppo la documentazione del tool di [generazione Token](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator) riporta un esempio con valori non corretti, presumo che altri cadranno in questo tranello.

Detto questo ora l'errore adesso è il seguente:
```
{
    "traceID": "bbf6cee8d3eb36ee",
    "spanID": "bbf6cee8d3eb36ee",
    "type": "/msg/jwt-validation",
    "title": "Campo token JWT non valido.",
    "detail": "JWT payload: Tipologia documento diversa dalla tipologia di CDA (code - codesystem)",
    "status": 403,
    "instance": "/jwt-document-type",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.2149fb78666c205ac20b9bd2d882af037f0819429c691196eaa8054488c56c20.0cb22de11f^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
} 
```
Messaggio abbastanza criptico, non viene indicato se si tratta del JWT di autorizzazione o di firma, in entrambi i casi nel payload non riesco ad individuare un campo _tipologia documento_, nel requestbody è presente il campo "healthDataFormat": "CDA".

**Comment by vigliottim** [comment]
Buonasera,
il campo _resource_hl7_type_ contenuto nel JWT è ottenuto dal concatenamento dei campi _code_ e _codesystem_ secondo il seguente formato:
`"resource_hl7_type": "('CODE^^CODESYSTEM')"`
Il valore del campo `CODE `inserito in _resource_hl7_type_ del JWT (`"resource_hl7_type": "('11502-2^^2.16.840.1.113883.6.1')"`) deve essere coerente con quello inserito nel tag _code_ contenuto all'interno del CDA (relativo alla tipologia di documento in esame): `code="11488-4"`
Restiamo a disposizione nel caso in cui il problema persista. Grazie.

**Comment by lorenzonet** [comment]
Penso di aver reperito il file CDA.xml da qualche parte perché non è presente fra i files nel tool di generazione PDF, ecco il motivo dell'incongruenza dei valori. 
Comunque adesso funziona, grazie per il supporto.
