### ISSUE TITLE
Validazione CDA

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#655]
Buongiorno, sto provando a validare i CDA prodotti, ma non riesco a farlo nè con Visual Studio, che mi dà errori nello schema, nè con Notepad++ che non funziona. Avete per caso uno strumento valido da suggerirmi?
Grazie per l'attenzione.

**Comment by vigliottim** [comment]
Buongiorno, per effettuare la validazione di un CDA può chiamare il servizio di validazione, trova endpoint e relativa documentazione al link: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#3-servizio-di-validazione 
Inoltre, nel caso voglia fare una richiesta di accreditamento in futuro, le facciamo presente che per l'accreditamento vengono svolti dei test specifici (con controlli più stringenti rispetto a quelli previsti in validazione).
Pertanto, non è detto che ad un esito positivo da parte del Gateway corrisponderà un esito positivo in fase di accreditamento.
Per eseguire la verifica offline dei test case di validazione OK richiesti durante la fase di accreditamento può utilizzare il tool _gtw-certifier_ scaricabile al link: https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/gtw-certifier
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Buongiorno, può avvalersi del tool _[gtw-certifier](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/gtw-certifier)_ per eseguire offline la verifica dei test case di validazione OK richiesti durante la fase di accreditamento. 
Per i test di validazione KO non è disponibile nessun tool specifico ma potrà fare riferimento ai documenti contenenti le descrizioni dei test case con le relative specifiche: https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione. 
L'esito della richiesta di accreditamento viene inviato con l'eventuale dettaglio degli errori riscontrati: essi potranno essere corretti effettuando una nuova pull request. 
Rimaniamo a disposizione per chiarimenti.
