### ISSUE TITLE
Validazione per Nazionale - LAB: problema effectiveTime 

### ISSUE THREAD

**Issue by MasCol75** [ministero-salute/it-fse-support#656]
Stiamo cercando di eseguire un test case positivo per Il CDA Nazionali LAB, ma riscontriamo un problema sul quale chiediamo il vostro aiuto.

Il file xml allegato (abbiamo solo cambiato l'estenzione), risulta essere correttamente formattato ma con due errori di validazione:

1. Line:Col[213:48]:cvc-complex-type.2.4.a: Invalid content was found starting with element 'effectiveTime'. One of '{"urn:hl7-org:v3":realmCode, "urn:hl7-org:v3":typeId, "urn:hl7-org:v3":templateId, "urn:hl7-org:v3":id, "urn:hl7-org:v3":code}' is expected.
2. Line:Col[222:48]:cvc-complex-type.2.4.a: Invalid content was found starting with element 'effectiveTime'. One of '{"urn:hl7-org:v3":realmCode, "urn:hl7-org:v3":typeId, "urn:hl7-org:v3":templateId, "urn:hl7-org:v3":id, "urn:hl7-org:v3":code}' is expected.

togliendo i due
<effectiveTime value="200711301556"/>
risulta  uno schema valido ma al parser schematron restituisce due errori:

1.
/ClinicalDocument/component/structuredBody/component/section/component/section/entry/act/entryRelationship[2]/organizer/component[3]/organizer/component/observation
ERRORE-b23| L?elemento observation DEVE contenere un elemento 'effectiveTime'

2.
/ClinicalDocument/component/structuredBody/component/section/component/section/entry/act/entryRelationship[2]/organizer/component[3]/organizer/component[2]/observation
ERRORE-b23| L?elemento observation DEVE contenere un elemento 'effectiveTime'

Sicuramente l'errore è altrove, ma non riusciamo a capirlo/trovarlo.
Dove stiamo sbagliando?

[01319531008_XXXKLJ70B48Z222R_345678901.txt](https://github.com/ministero-salute/it-fse-support/files/14525890/01319531008_XXXKLJ70B48Z222R_345678901.txt)

**Comment by ponsilva** [comment]
Buongiorno,
mi inserisco in questo thread perché in alcuni test avevo incontrato un errore simile.

I CDA devono seguire le specifiche HL7, nel caso del documento LAB la specifica è
http://www.hl7italia.it/hl7italia_D7/Implementation%20Guide%20CDA%202%20-%20Referto%20di%20Medicina%20di%20Laboratorio

Il problema potrebbe essere sui 2 elementi observation che hanno effectiveTime come primo tag

<observation moodCode="EVN" classCode="OBS">
	<effectiveTime value="200711301556"/>

<observation moodCode="EVN" classCode="OBS">	
	<effectiveTime value="200711301556"/>

mentre invece, come indicato negli errori di validazione, ci si aspetta uno di questi tag:
realmCode, typeId, templateId, id, code

Una modalità per validare i CDA in locale è applicare manualmente l'XSD disponibile su 
https://github.com/ministero-salute/it-fse-catalogs/tree/main/schema/POCD_MT000040UV02

**Comment by vigliottim** [comment]
Buongiorno, ringraziamo @ponsilva per il suo intervento.
Si segnala che l'errore che sta avendo è dovuto al posizionamento errato dell'elemento _effectiveTime_  ovvero, secondo lo schema CDA R.2, l'elemento _<effectiveTime>_ deve essere riportato dopo il tag _<statusCode>_.

**Comment by MasCol75** [comment]
Grazie a @ponsilva  e @vigliottim 

Lo stralcio corretto diventa:

```xml
<component typeCode="COMP">
	<observation moodCode="EVN" classCode="OBS">
		<code code="18906-8" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Ciprofloxacina"/>
		<statusCode code="completed"/>
		<effectiveTime value="200711301556"/>
		<value xsi:type="ST">R</value>
		<interpretationCode code="R" codeSystem="2.16.840.1.113883.5.83" codeSystemName="ObservationInterpretation" displayName="R"/>
	</observation>
</component>
```
Grazie.
