### ISSUE TITLE
UNKNOWN_WORKFLOW_ID - Errore in fase di estrazione del CDA

### ISSUE THREAD

**Issue by ElisaGerosa** [ministero-salute/it-fse-support#658]
Buongiorno, sto provando a validare diversi documenti ma ricevo sempre questo errore che riporto di seguito:

Error calling Validate: {"traceID":"ee836916df0d4e3f","spanID":"ee836916df0d4e3f","type":"/msg/cda-element","title":"Errore in fase di estrazione del CDA.","detail":"Error while extracting CDA from PDF document","status":400,"instance":"/cda-extraction","workflowInstanceId":"UNKNOWN_WORKFLOW_ID"}

Dal momento che avevamo effettuato una serie elevata di prove precedenti, tutte andate a buon fine  e non abbiamo modificato nulla nella modalità di generazione del pdf + cda2, vorrei chdervi gentilmente se è stato modificiato qualcosa lato gateway.

In allegato l'ultimo pdf sottomesso.

[TEST_BETTINA_20240307_v1.pdf](https://github.com/ministero-salute/it-fse-support/files/14556967/TEST_BETTINA_20240307_v1.pdf)

Grazie,
Elisa

**Comment by LucaRogledi** [comment]
Buongiorno,
in seguito alla seguente issue https://github.com/ministero-salute/it-fse-support/issues/598 sono stati modificati i controlli sul nome del file iniettato all'interno del pdf, che deve rispettare la nomenclatura "cda.xml" come riportato in documentazione al seguente [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#2-contesto-di-riferimento).
Dal pdf da lei allegato risulta che il cda iniettato sia stato rinominato "cda2.xml", pertanto la invitiamo a rinominarlo "cda.xml" e riprovare con la chiamata del servizio.
Grazie

**Comment by ElisaGerosa** [comment]
Grazie mille, effettuiamo la modifica e riproviamo il giro
