### ISSUE TITLE
Caricati tutti i file necessari per l'accreditamento

### ISSUE THREAD

**Issue by S2INFORMATICA-NA** [ministero-salute/it-fse-support#659]
Buongiorno,
Ho appena popolato la cartella di lavoro di S2INFORMATICA-NA con i file necessari per l'accreditamento.
Dovrebbe essere questa https://github.com/S2INFORMATICA-NA/it-fse-accreditamento/tree/main/GATEWAY/A1%23111%23S2INFORMATICASRLXX
ma non so se all'atto della creazione ho seguito la procedura corretta, ne' ho capito bene se devo eseguire qualche azione specifica per richiedere la sottomissione dei dati per ottenere l'accreditamento.
Inoltre non ho potuto eseguire la registrazione sulla pagina web https://ec.europa.eu/eusurvey/runner/FSE-raccolta-id-applicativo perche' il browser si blocca senza riuscire a visualizzare i campi di input (ne ho provati diversi con diverse versioni di Windows, ma l'effetto e' sempre lo stesso).
Grazie dell'attenzione.

**Comment by vigliottim** [comment]
Buongiorno, 
La ringraziamo per la segnalazione in merito all'EuSurvey: abbiamo già provveduto ad avvisare il team competente. 
Inoltre, dal link che ha condiviso (https://github.com/S2INFORMATICA-NA/it-fse-accreditamento/tree/main/GATEWAY/A1%23111%23S2INFORMATICASRLXX) abbiamo notato che non è stato effettuato il fork del repository.
La rimandiamo a questo link della documentazione in cui sono riportate le indicazioni per il caricamento dei risultati tramite pull request: https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#pull-request).
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by DATASOFTNA** [comment]
Ok, ho capito dove ho sbagliato: non ho effettuato il fork della cartella fse-accreditamento.
Adesso pero' se tento di farlo, ottengo la segnalazione che la cartella gia' esiste e non so  come cancellarla.
Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno,
Prima di effettuare il fork, La invitiamo ad eliminare il repository locale https://github.com/S2INFORMATICA-NA/it-fse-accreditamento tramite le impostazioni presenti nella pagina del repository come nello screenshot. 
Infine può procedere riprovando il fork come descritto di seguito https://github.com/ministero-salute/it-fse-accreditamento/tree/main?tab=readme-ov-file#pull-request.
Restiamo a disposizione in caso di ulteriore supporto.

**Comment by S2INFORMATICA-NA** [comment]
Grazie per la celere risposta.
Siccome non sono riuscito a cancellare la precedente fse-accreditamento, l'ho rinominata Errore-fse-accreditamento, quindi sono riuscito ad effettuare il fork.
Chiedo scusa del disturbo, ho cercato tra le varie opzioni, ma proprio non riesco a cancellare la cartella errore-fse-accreditamento.
Mi potrebbe indicare come fare ?
Ho effettuato anche la richiesta pull della cartella dopo avere caricato (spero) tutti i file.
A questo punto credo che debba attendere solo l'analisi dei file forniti.

**Comment by vigliottim** [comment]
Le confermiamo che la pull request è stata presa in carico. 
Pertanto, chiudiamo il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via e-mail. 
Grazie.
