### ISSUE TITLE
refusi documentazione CDA VPS

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#66]
Buongiorno,
non so se questo è il canale giusto ma volevo far notare dei refusi nella documentazione del VPS (HL7IT-IG_CDA2_VPS-v1.1.1-S.pdf)
ad esempio alla pagina 130:

`@moodCode
“EVN” – Elemento erogato / eseguito
o RQO per le prestazioni richieste`

l'esempio della pagina 131 non è coerente con quanto descritto sopra. il valore REQ non è ammesso.
Invece nel CDA di esempio fornito nel caso di prestazione eseguita è inserito un valore errato: RQO al posto del corretto ENV

Grazie

**Comment by Ser-ena** [comment]
Buongiorno, per precisione di informazione il CDA di esempio a cui fa riferimento è quello presente a questo path: https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/VPS.xml?

**Comment by alessandropassamonti** [comment]
si
grazie

**Comment by IStacchiotti** [comment]
Buongiorno, abbiamo verificato. Grazie della segnalazione, le daremo evidenza appena sarà caricato l'esempio XML con la correzione del refuso.

**Comment by IStacchiotti** [comment]
Buongiorno, Le confermiamo che è stata rilasciata una fix correttiva. La invitiamo cortesemente a riprovare, il problema non dovrebbe più presentarsi. Rimaniamo a completa disposizione in caso contrario. Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
