### ISSUE TITLE
Errore su tentativo di Validazione

### ISSUE THREAD

**Issue by enzocap** [ministero-salute/it-fse-support#660]
Buonasera,
sono al mio primo tentativo di validazione di un referto di laboratorio, dopo la creazione dei token.
Ho creato la stringa di parametri secondo la documentazione (i token sono abbreviati):

curl -X 'POST' 'https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation' -H 'Authorization: Bearer eyJ4NWMiOlsiTUlJRmJ6Q0NBM ... Vi47JBBWv7puGQMfsSbw' -H 'FSE-JWT-Signature: eyJ4NWMiOlsiTUlJRmJ6Q0NBMWVnQXdJQkFnS ...... jDt2yKhnJ0KIqpzvKXvqeLaQ9sdA' -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -F 'requestBody={ "healthDataFormat": "CDA", "mode": "ATTACHMENT", "activity": "VALIDATION",}' -F 'file=@RefertoCDA.pdf;type=application/pdf'

La risposta:

curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (6) Could not resolve host: Bearer
curl: (3) URL rejected: Bad hostname
curl: (3) URL rejected: Bad hostname
curl: (6) Could not resolve host: application
curl: (6) Could not resolve host: multipart
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) URL rejected: Bad hostname
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) URL rejected: Bad hostname
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) unmatched close brace/bracket in URL position 12:
VALIDATION,}'
           ^

Grazie. Saluti.

**Comment by vigliottim** [comment]
Buonasera, potrebbe cortesemente riprovare rimuovendo la virgola dopo il campo "activity"?
`"activity": "VALIDATION",`
Rimaniamo a disposizione se l'errore si dovesse ripresentare. 
Grazie.

**Comment by enzocap** [comment]
... avevo già provato ... il carattere di segnalazione errore si sposta una carattere più avanti:

curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (6) Could not resolve host: Bearer
curl: (3) URL rejected: Bad hostname
curl: (3) URL rejected: Bad hostname
curl: (6) Could not resolve host: application
curl: (6) Could not resolve host: multipart
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) URL rejected: Bad hostname
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) URL rejected: Bad hostname
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) unmatched close brace/bracket in URL position 11:
VALIDATION}'
          ^

ma l'errore più ricorrente che riguarda il "Port number was not a decimal number between 0 and 65535" ?

Grazie. Saluti.

**Comment by vigliottim** [comment]
Buongiorno, potrebbe gentilmente dirci quale tipo di terminal/command prompt sta usando per effettuare la chiamata? Grazie.

**Comment by enzocap** [comment]
Buongiorno, scusi ma non capisco la domanda ... ho creato un comando batch con la riga di comando e la eseguo dal prompt di windows ... (in allegato, rinominato .txt)

Grazie. Saluti.

[Validate.txt](https://github.com/ministero-salute/it-fse-support/files/14584898/Validate.txt)

**Comment by ponsilva** [comment]
Buongiorno,
mi inserisco in questo thread perché in alcuni test avevo incontrato un errore simile.

Nella chiamata https si deve usare il certificato di autenticazione (certificato client per le chiamate https), ad esempio i comandi curl che ho usato avevano i parametri cert e key

curl -X 'POST' --cert certificato_auth.crt --key chiave_auth.key 'https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation' ecc...

Poi in effetti è un po' strano l'errore "Port number was not a decimal number between 0 and 65535" (senza certificato di autenticazione a me ritornava "handshake failure") quindi magari c'è qualche altro problema nella chiamata.

**Comment by enzocap** [comment]
Buongiorno e grazie per il suo feedback.
Avevo visto degli esempi che riportavano questa sintassi ... ma se è così come mai non è riportato in documentazione (domanda per il servizio tecnico)?

Ad ogni modo, ho provato ad inserire il certificato (sia .crt che .pem??) e .key ma non cambia nulla ...

Grazie. Saluti.

**Comment by LucaRogledi** [comment]
Buonasera @enzocap ,
ringraziamo come sempre @ponsilva per i precisi riscontri.
In documentazione a questo [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#23-note-su-autenticazione-e-token-jwt) è indicato che il client necessita di un certificato di autenticazione per le chiamate http: si tratta del certificato p12, da ricavare a partire dal pem di autenticazione (#A1) condiviso via email dal support, secondo le indicazioni contenute al [link](https://github.com/ministero-salute/it-fse-support/issues/591).

Di seguito la sintassi di riferimento che può essere utilizzata sul prompt di Windows per effettuare la chiamata del servizio di validazione:

`curl --url "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation" --cert-type P12 --cert {path_certificato_A1.p12}:{password_certificato} -H "Authorization:Bearer {token_bearer}" -H "FSE-JWT-Signature: {token_signature}" -H 'accept:application\/json' -H "Content-Type:multipart/form-data" -F "requestBody={\"activity\": \"VALIDATION\", \"healthDataFormat\": \"CDA\", \"mode\": \"ATTACHMENT\"}" -F "file=@RefertoCDA.pdf"`

Si noti che le variabili da valorizzare all'interno dell'esempio riportato sono indicate tra parentesi graffe.
Rimaniamo a disposizione in caso di ulteriori richieste.

**Comment by enzocap** [comment]
Buongiorno,
ricomponendo la stringa come da esempio, ora ottengo il seguente errore:

curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - La funzione di revoca non è riuscita a controllare la revoca del certificato.
curl: (6) Could not resolve host: application

curl --url "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation" --cert-type P12 --cert Auth_cert.p12:******** -H "Authorization:Bearer eyJ4NWMiOlsiTUlJRmJ6Q0NBMWVnQXdJQkFnSVVYOVdmRkN ....sieSScEUiwPcowEupYMRWDjyu0Jd2PI9w" -H "FSE-JWT-Signature: eyJ4NWMiOlsiTUlJRmJ6Q0NBMWVn .... 1TCNbk-WRSJiBkdQ1VcLQ" -H 'accept: application/json' -H "Content-Type: multipart/form-data" -F "requestBody={\"activity\":\"VALIDATION\", \"healthDataFormat\": \"CDA\", \"mode\": \"ATTACHMENT\"} -F "file=@RefertoCDA.pdf"

Grazie. Saluti.

**Comment by LucaRogledi** [comment]
Buongiorno,
Sembrerebbe che l'errore potrebbe essere dovuto all'antivirus se presente.
Cercando in rete abbiamo trovato le seguenti possibili soluzioni: 
1) disattivare momentaneamente l'antivirus,
2) utilizzare il parametro -k invece di --url come mostrato di seguito,

`curl -k "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation" --cert-type P12 --cert {path_certificato_A1.p12}:{password_certificato} -H "Authorization:Bearer {token_bearer}" -H "FSE-JWT-Signature: {token_signature}" -H 'accept:application\/json' -H "Content-Type:multipart/form-data" -F "requestBody={\"activity\": \"VALIDATION\", \"healthDataFormat\": \"CDA\", \"mode\": \"ATTACHMENT\"}" -F "file=@RefertoCDA.pdf"`

Infine abbiamo notato qualche disallineamento dall'esempio riportato in precedenza:
1)  AS-IS: `'accept: application/json'` --> TO-BE: `'accept:application\/json'`
2)  AS-IS: `"requestBody={"activity":"VALIDATION", "healthDataFormat": "CDA", "mode": "ATTACHMENT"}` --> TO-BE: `"requestBody={\"activity\": \"VALIDATION\", \"healthDataFormat\": \"CDA\", \"mode\": \"ATTACHMENT\"}"`

Restiamo a disposizione in caso l'errore dovesse ripresentarsi.
Grazie

**Comment by enzocap** [comment]
Buongiorno e grazie per i feedback tempestivi,
ho cambiato --url in -k, disattivato l'antivirus, e applicato il 1° AS-IS in TO-BE (il secondo era corretto ed avevo sbagliato ad incollare la parte relativa).
Ora l'errore è il seguente:

 {"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"a4c191b0-e1ea-11ee-8bf1-005056ae54fa"}curl: (3) URL rejected: Bad hostname

Riporto il comando abbreviato:
curl -k "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation" --cert-type P12 --cert Auth_cert.p12:******** -H "Authorization:Bearer eyJ4NWMiOlsiTUlJRmJ6Q0NBMWVn ... HJUGpd_yNdhNleBViGN7FaWr5O8hGg" -H "FSE-JWT-Signature: eyJ4NWMiOlsiTUlJ .... HY-xpnLryxniyDAimOuAoclA" -H 'accept: application\/json' -H "Content-Type: multipart/form-data" -F "requestBody={\"activity\":\"VALIDATION\", \"healthDataFormat\": \"CDA\", \"mode\": \"ATTACHMENT\"} -F "file=@RefertoCDA.pdf"

Grazie. Saluti.

**Comment by enzocap** [comment]
... l'ultima parte del comando è la seguente:

-H 'accept: application\/json' -H "Content-Type: multipart/form-data" -F "requestBody={\"activity\":\"VALIDATION\", \"healthDataFormat\": \"CDA\", \"mode\": \"ATTACHMENT\"} -F "file=@RefertoCDA.pdf"

**Comment by enzocap** [comment]
... non so perchè ma quello che digito viene cambiato in fase di invio ... provo con l'allegato ...
[Validate.txt](https://github.com/ministero-salute/it-fse-support/files/14601142/Validate.txt)

**Comment by LucaRogledi** [comment]
Buongiorno,
abbiamo adattato il comando al prompt da lei utilizzato e dalle prove effettuate la sintassi corretta risulta quella indicata nel messaggio precedente.

> Buongiorno, Sembrerebbe che l'errore potrebbe essere dovuto all'antivirus se presente. Cercando in rete abbiamo trovato le seguenti possibili soluzioni:
> 
> 1. disattivare momentaneamente l'antivirus,
> 2. utilizzare il parametro -k invece di --url come mostrato di seguito,
> 
> `curl -k "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation" --cert-type P12 --cert {path_certificato_A1.p12}:{password_certificato} -H "Authorization:Bearer {token_bearer}" -H "FSE-JWT-Signature: {token_signature}" -H 'accept:application\/json' -H "Content-Type:multipart/form-data" -F "requestBody={\"activity\": \"VALIDATION\", \"healthDataFormat\": \"CDA\", \"mode\": \"ATTACHMENT\"}" -F "file=@RefertoCDA.pdf"`
> 
> Infine abbiamo notato qualche disallineamento dall'esempio riportato in precedenza:
> 
> 1. AS-IS: `'accept: application/json'` --> TO-BE: `'accept:application\/json'`
> 2. AS-IS: `"requestBody={"activity":"VALIDATION", "healthDataFormat": "CDA", "mode": "ATTACHMENT"}` --> TO-BE: `"requestBody={\"activity\": \"VALIDATION\", \"healthDataFormat\": \"CDA\", \"mode\": \"ATTACHMENT\"}"`
> 
> Restiamo a disposizione in caso l'errore dovesse ripresentarsi. Grazie

Inoltre, abbiamo notato che nel comando da lei riportato all'interno del file "Validate.txt" è assente il doppio apice di chiusura per il parametro requestBody (può trovare il comando corretto nel nostro ultimo messaggio).
La invitiamo a verificare la sintassi e riprovare.
Grazie.

**Comment by enzocap** [comment]
Buon pomeriggio,
ho aggiunto gli apici a chiusura del requestBody, disattivato l'antivirus (non cambia se attivato) e la risposta è la seguente

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"a6b313a5-e20d-11ee-8bf1-005056ae54fa"}curl: (3) URL rejected: Bad hostname

Allego la richiesta abbreviata.

[Validate.txt](https://github.com/ministero-salute/it-fse-support/files/14604076/Validate.txt)


Grazie. Saluti.

**Comment by vigliottim** [comment]
Buonasera, dalle analisi effettuate risultano degli errori nella valorizzazione dei campi dei token.
In particolare:

**Authentication Bearer Token:**
`"iss": "auth:jwt-issuer"`: deve essere valorizzato con "auth:" seguito dal common name del certificato di firma
`"aud": "FSE_Gateway"`: indica il destinatario per cui è stato creato il token, da valorizzare con la base URL del servizio, comprensivo della versione `"aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1"`

**FSE-JWT-Signature:**
`"iss": "integrity:jwt-issuer"`: deve essere valorizzato con "integrity:" seguito dal common name del certificato di firma
`"aud": "FSE_Gateway"`: indica il destinatario per cui è stato creato il token, da valorizzare con la base URL del servizio, comprensivo della versione `"aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1"`
`"locality": "jwt-location"`: deve contenere l'identificativo della struttura utente

Di seguito può trovare il link con la documentazione relativa ai campi contenuti nei jwt: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt
La preghiamo di riprovare effettuando le correzioni suggerite.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by LucaRogledi** [comment]
Buonasera,
Se sta utilizzando il tool messo a disposizione online [jwt-generator](https://github.com/ministero-salute/it-fse-gtw-tools) il campo iss all'interno del file data.json deve essere valorizzato come riportato nel seguente esempio, sostituendo {COMMON_NAME} con il common name del certificato di firma (S1#...):
"iss": "{COMMON_NAME}"
Il tool aggiungerà in automatico i prefissi "auth:" e "integrity:" a seconda del token generato.
Restiamo a disposizione in caso di ulteriori chiarimenti.

**Comment by enzocap** [comment]
Buonasera,
ho seguito le vs. indicazioni e riprovato, ma ora l'errore è cambiato come segue:

{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"202a14aa-e225-11ee-8bf1-005056ae54fa"}curl: (3) URL rejected: Bad hostname

Grazie. Saluti.

**Comment by vigliottim** [comment]
Buongiorno, il _common name_ nel campo _iss_ del data.json non è valorizzato correttamente. 
`"iss": "DECSISTEMI"` ->` "iss": "S1#190201234567XX"`

Effettuando tale correzione, i campi iss dei token diventeranno:

**Authentication Bearer Token:**
- `"iss": "auth:DECSISTEMI"`: deve essere valorizzato con "auth:" seguito dal common name del certificato di firma ossia nel suo caso:
`"iss": "auth:S1#111#DECSISTEMISRLX1"`

**FSE-JWT-Signature:**
- `"iss": "integrity:DECSISTEMI"`: deve essere valorizzato con "integrity:" seguito dal common name del certificato di firma ossia nel suo caso:
`"iss": "integrity:S1#111#DECSISTEMISRLX1"`

La invitiamo a riprovare dopo aver effettuato la correzione suggerita.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by enzocap** [comment]
Buongiorno,,
ho effettuato la modifica come da vs. indicazioni, ma non sembra essere cambiato l'errore.
Vorrei far notare, se può essere utile, che "S1#111#DECSISTEMISRLX1" è il nome del file .pem da voi inviatomi, ma il common name da me indicato nella richiesta (.csr) è DECSISTEMI.

{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"a2171c2d-e2b7-11ee-b06f-005056ae54fa"}curl: (3) URL rejected: Bad hostname

Grazie. Saluti.

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate risulta un problema di certificato. 
Se il _common name_ da lei indicato nella richiesta è _DECSISTEMI_ come riportato nel messaggio precedente, la invitiamo a riprovare sostituendolo nel campo _"iss"_ che diventerà: `"iss":"S1#DECSISTEMI"`. 
Rimaniamo a disposizione nel caso in cui l'errore dovesse ripresentarsi. Grazie.

**Comment by enzocap** [comment]
Buongiorno,
niente da fare ... l'errore è sempre lo stesso (a parte il govway_id):

{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"02bc0d9a-e535-11ee-93a7-005056ae54fa"}curl: (3) URL rejected: Bad hostname

Preciso anche che alla prima chiamata del comando ricevo la seguente risposta:

curl: (56) Recv failure: Connection was reset
curl: (3) URL rejected: Bad hostname

Allego ultimo data.json sperando possa esservi d'aiuto.
[data.json](https://github.com/ministero-salute/it-fse-support/files/14638432/data.json)


Grazie. Saluti.

**Comment by enzocap** [comment]
"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"42c09835-e6d3-11ee-9223-005056ae7395"}curl: (3) URL rejected: Bad hostname

**Comment by enzocap** [comment]
Buongiorno,
in effetti avevo seguito l'esempio del link da voi indicato in data 13/03 dove veniva utilizzato il certificato di firma.
Ad ogni modo ho ricreato il .p12 partendo da quello di autenticazione, ma il risultato (se va bene) è quello del post di sopra, altrimenti in altri tentativi, dopo circa un minuto di attesa, ottengo:

curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed
curl: (3) URL rejected: Bad hostname.

In altri casi mi si è bloccato internet e ho dovuto riavviare il PC.

Grazie. Saluti.

**Comment by LucaRogledi** [comment]
Buongiorno,
Le confermiamo che ora i certificati di autenticazione e di firma risultano correttamente referenziati. Tuttavia dalle nuove verifiche ci risulta che il common name da utilizzare all'interno del campo iss contenuto nel file data.json per la generazione dei token è:
 
`iss: S1#111#DECSISTEMISRLX1`
 
La invitiamo gentilmente a riprovare e restiamo a disposizione in caso di ulteriore supporto.
Grazie.

**Comment by enzocap** [comment]
Buongiorno,
credo che abbiamo finalmente superato i problemi di autenticazione in quanto mi sembra che ora l'errore restituito sia riferito all'estrazione del CDA:

{"traceID":"5d350ccf083d5732","spanID":"5d350ccf083d5732","type":"/msg/cda-element","title":"Errore in fase di estrazione del CDA.","detail":"Error while extracting CDA from PDF document","status":400,"instance":"/cda-extraction","workflowInstanceId":"UNKNOWN_WORKFLOW_ID"}curl: (3) URL rejected: Bad hostname

A tal proposito vorrei specificare che si tratta di un CDA.XML inserito tramite una nostra libreria e non tramite il vostro pdf-generator e quindi vorrei sapere se si tratta di un problema di lettura fisica dell'XML o del contenuto del CDA che è solo un esempio casuale messo solo per prova. 

Grazie. Saluti.

**Comment by LucaRogledi** [comment]
Buongiorno,
Dalle analisi effettuate sul file CDA.xml estratto dalla chiamata "govway_id":"42c09835-e6d3-11ee-9223-005056ae7395" da lei effettuata in precedenza, confermiamo che non è un problema del cda, in quanto utilizzando tale cda iniettato in un pdf tramite tool pdf-generator la chiamata del servizio di validazione avviene con successo riportando il codice 422. 
La invitiamo pertanto a rivedere la libreria utilizzata per l'iniezione del cda o utilizzare il tool messo a disposizione online [pdf-generator](https://github.com/ministero-salute/it-fse-gtw-tools).
Restiamo a disposizione per eventuali chiarimenti.
Grazie

**Comment by enzocap** [comment]
Buongiorno,
ho effettuato alcune variazioni ed ora sembra che abbia letto il CDA:

{"traceID":"6ce8cb56acc1192b","spanID":"6ce8cb56acc1192b","type":"/msg/semantic","title":"Errore semantico.","detail":"Schematron with template id root 2.16.840.1.113883.2.9.2.80.3.1.10.1 not found on database.","status":422,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.80.3.1.4.4.d047b41155037a75334568d761554e8153b1ff451ac2aec97f5d0b1f840e2b5c.6a2c103021^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}curl: (3) URL rejected: Bad hostname

se mi confermate che il CDA è stato letto posso passare ad esaminare la parte di documentazione relativa.

Grazie. Saluti.

**Comment by vigliottim** [comment]
Buonasera, le confermiamo che la chiamata al servizio di validazione è stata effettuata correttamente. 
L'errore semantico è causato dall'elemento `<templateId root="2.16.840.1.113883.2.9.2.80.3.1.10.1" extension="2018.05" />` presente nel CDA, come indicato nel dettaglio dell'errore.
`"detail": "Schematron with template id root 2.16.840.1.113883.2.9.2.80.3.1.10.1 not found on database."`
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/57c641a4-91c4-476a-b969-e894bd4ac75d)
La invitiamo a correggerlo e riprovare.
Restiamo a disposizione per ulteriori chiarimenti.

**Comment by enzocap** [comment]
Buonasera e grazie per il supporto veloce e puntuale sin qui ricevuto,
ho effettuato la correzione suggerita ma mi ha dato tutta una serie di altre segnalazioni relative agli elementi del CDA, nonostante questo sia stato precedentemente testato sulle specifiche (FSE 1.0) della regione Emilia Romagna.
Credo il prossimo passo sia quello di generare dei CDA conformi alle specifiche FSE 2.0, sperando che, una volta superati i test di validazione, non dovremo poi adeguarli alle varie regioni. 
Se avete da suggerire un link alla documentazione da seguire per il prossimo step sarebbe gradito.

Grazie ancora. Saluti

**Comment by vigliottim** [comment]
Buonasera, di seguito le indichiamo alcuni link che possono esserle utili:

- _Esempi CDA per ogni tipologia documentale:_ https://github.com/ministero-salute/it-fse-support/tree/main/doc/esempi/CDA
- _Schematron per verifica dei CDA:_ https://github.com/ministero-salute/it-fse-catalogs/tree/main/schematron
- _Implementation guide per la tipologia documentale di interesse da ricercare_ su http://www.hl7italia.it/

Procediamo alla chiusura del presente ticket e rimaniamo a disposizione per ulteriori richieste di supporto.

**Comment by enzocap** [comment]
Buongiorno,
ho sostituito il CDA in attachment con quello di esempio da voi indicato nel link del precedente post, sostituito nel data.json i codici fiscali:
"sub": "sub": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO"
"person_id":"GTWGWY82B42G920M^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO"
 ma l'invio mi restituisce il seguente messaggio di errore:

{"traceID":"b3846d0994cf3545","spanID":"b3846d0994cf3545","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.9c317c5723^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}curl: (3) URL rejected: Bad hostname

Grazie. Saluti.

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Il messaggio ricevuto non riporta un messaggio di errore, come indicato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#321-messaggio-di-risposta-esempio-validation-con-attachment-con-esito-success-201)  nell' esempio di risposta, la validazione sembra essere avvenuta con successo.
Restiamo a disposizione per eventuali chiarimenti.
Grazie

**Comment by enzocap** [comment]
Perfetto !! Grazie Saluti.

**Comment by PieroDal** [comment]
Buona sera, ora devo proseguire io il lavoro cominciato da enzocap.
Ho provato a generare un CDA più complesso, con più prestazioni ed anche multi risposta, ottenendo la validazione.
Quindi adesso bisogna procedere con i compiti per ottenere l'accreditamento.
Potreste gentilmente guidarmi ?

**Comment by vigliottim** [comment]
> Buona sera, ora devo proseguire io il lavoro cominciato da enzocap. Ho provato a generare un CDA più complesso, con più prestazioni ed anche multi risposta, ottenendo la validazione. Quindi adesso bisogna procedere con i compiti per ottenere l'accreditamento. Potreste gentilmente guidarmi ?

Buonasera,
le lasciamo di seguito alcuni link che possono tornarle utili in merito al processo di accreditamento:

- **_Fase 1 del processo di accreditamento:_** https://github.com/ministero-salute/it-fse-support/tree/main/doc/accreditamento#fase-1-processo-di-accreditamento
- **_Procedura di caricamento dei risultati:_** https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#accreditamento-fse-20-draft
- _**Documentazione Integrazione Gateway:**_ https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway
- **_Tool utili:_** https://github.com/ministero-salute/it-fse-gtw-tools/tree/main

Se riscontra delle difficoltà o dei problemi, può aprire una nuova issue indicandone i dettagli.
Grazie.
