### ISSUE TITLE
Validazione del CDA con gwt-certifier

### ISSUE THREAD

**Issue by sviluppoTServe** [ministero-salute/it-fse-support#661]
Buongiorno
Ho iniziato l'integrazione del nostro sw di cartella clinica per l'invio da parte del MMG del PSS.
Ho generato il token con jwt-generato, ho iniettato il CDA di test nel pdf di test con pdf-generator  e ora vorrei testare la validazione con gwt-certifier prima di passare al CDA da noi prodotto.
Sarebbe possibile avere un esempio del data.json che deve puntare ai files da certificare?
grazie, saluti

**Comment by IStacchiotti** [comment]
Buongiorno, se lo scopo è quello di testare la validazione, il gwt-certifier non è il tool più indicato: le suggeriamo piuttosto di invocare il servizio di validazione online in ambiente di test, secondo le specifiche riportarte al seguente [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway). 
Specifichiamo infine che il gwt-certifier è uno strumento utile ai fini dell'accreditamento: consente di riprodurre in locale le verifiche sui test case di validazione OK, prima della sottomissione della pull request.

**Comment by sviluppoTServe** [comment]
grazie!! saluti

**Comment by vigliottim** [comment]
Grazie a lei. 
Chiudiamo la presente issue e rimaniamo a disposizioni per ulteriori richieste di supporto.
