### ISSUE TITLE
LDO: nodo "<healthCareFacility>/<serviceProviderOrganization>/<id>" possibile utilizzo codifica STS11?

### ISSUE THREAD

**Issue by Saxos-Simone** [ministero-salute/it-fse-support#662]
Buongiorno,
nelle specifiche del _CDA_ di **RSA** ([HL7IT-IG_CDA2_RSA-v1.1-S.pdf](http://www.hl7italia.it/sites/default/files/Hl7/SuperUser/docs/pubblicati/IG-CDA2-RSA/1.1/HL7IT-IG_CDA2_RSA-v1.1-S.pdf)) viene specificato che per il nodo _\<componentOf\>/\<encompassingEncounter\>/\<location\>/\<healthCareFacility\>/\<serviceProviderOrganization\>/\<id\>_ è possibile utilizzare la codifica **STS11** per specificare l’identificativo della struttura sanitaria erogante.
Invece, nelle specifiche del _CDA_ di **LDO** ([HL7IT-IG_CDA2_LDO-v1.2-S.pdf](http://www.hl7italia.it/sites/default/files/Hl7/SuperUser/docs/pubblicati/IG-CDA2-LDO/1.2/HL7IT-IG_CDA2_LDO-v1.2-S.pdf)) non viene specificato, per lo stesso nodo (_\<componentOf\>/\<encompassingEncounter\>/\<location\>/\<healthCareFacility\>/\<serviceProviderOrganization\>/\<id\>_), pertanto è comunque possibile utilizzare la codifica **STS11** per specificare l’identificativo della struttura sanitaria in questo nodo del _CDA_ di **LDO**?

**Comment by vigliottim** [comment]
Buonasera, si segnala che da specifiche HL7 Italia viene riportato nella CONF-LDO-89 che l'elemento _componentOf/encompassingEncounter/location/healthCareFacility/serviceProviderOrganization/id_ viene valorizzato con l’identificativo del Presidio e della Struttura (stabilimento) di dimissione, ovvero tramite codici HSP.11 o HSP.11bis.

**Comment by Saxos-Simone** [comment]
Buongiorno,
quindi nel _CDA_ di **LDO**, a differenza del _CDA_ di **RSA**, non è proprio possibile utilizzare il codice **STS11** per identificare il Presidio e la Struttura (stabilimento) di dimissione, nell'elemento _componentOf/encompassingEncounter/location/healthCareFacility/serviceProviderOrganization/id_?
Inviando al _Gateway_ un _CDA_ di **LDO**, che utilizza un codice **STS11** per identificare il Presidio e la Struttura (stabilimento) di dimissione, vedo che viene accettato comunque, senza errori.

**Comment by vigliottim** [comment]
Buongiorno, sebbene l'utilizzo della codifica non è vincolato, il campo deve essere valorizzato con HSP.11 e HSP.11bis in quanto, trattandosi di una lettera di dimissione ospedaliera, occorre riportare il codice relativo ad una struttura di ricovero.

**Comment by Saxos-Simone** [comment]
Ok, grazie mille.
