### ISSUE TITLE
Chiusura Pull request per validazione senza indicazioni

### ISSUE THREAD

**Issue by simeds** [ministero-salute/it-fse-support#663]
Buongiorno,

in relazione alla Pull Request [https://github.com/ministero-salute/it-fse-accreditamento/pull/1243]
potremmo avere evidenza di cosa non ci ha permesso di ottenere l’accreditamento?

Nei giorni passati avevamo avuto comunicazione di non aver compilato alcune celle obbligatorie del file checklist.xlsx, che abbiamo provveduto a sistemare, ma adesso non capiamo cosa non sia conforme.

Guardando tra le issue di git abbiamo visto che altri hanno ricevuto una mail simile ma con allegato un file di tipo json dove sono indicati eventuali anomalie.

Vi chiediamo di aiutarci a capire come risolvere il problema.

Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, dalle nostre verifiche è emerso che i casi di test con id 29, 37, 369 non sono stati referenziati nel file json caricato tramite la pull request #1243, nonostante tali casi di test siano stati dichiarati come applicabili nella checklist. Pertanto dovreste procedere all'apertura di una nuova pull request per rendere coerenti le informazioni contenute nel file data.json rispetto a quanto dichiarato nella checklist. Grazie

**Comment by simeds** [comment]
Salve, 
abbiamo di nuovo ricevuto una chiusura della PR senza indicazione, è possibile conoscere i motivi?
[](https://github.com/ministero-salute/it-fse-accreditamento/pull/1271)
grazie.
