### ISSUE TITLE
Errore 403 AuthorizationContentDeny / Unauthorized request content

### ISSUE THREAD

**Issue by Beatrice164** [ministero-salute/it-fse-support#664]
Gent.mi buongiorno

Sto effettuando varie prove di invio verso l'url 
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation/govway/rest/in/FSE/gateway/v1/documents/validation
, sia da applicativo che da software client come postman.

In particolare nel secondo caso, riutilizzando i seguenti token, generati dal applicativo inviante

Authorization:
eyJ4NWMiOlsiTUlJRkxEQ0NBeFNnQXdJQkFnSVVJc2NscE9tU1RUVFZvM2lBb2lFTE5GSG5kYVV3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TWpFeE16QXlNakUyTWpaYUZ3MHlOVEV4TWpreU1qRTJNalZhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMweE1URkZUa2RKVGs1RlVrbE9SekVhTUJnR0ExVUVBd3dSUVRFak1URXhSVTVIU1U1T1JWSkpUa2N3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGRVQmVJY3dvSXdBRFhVZFpaQlR0b1JQL2tTNjBiZDA0TkpwcjlCVXBrTDBvRms1WU9oaVg2cUlYQWFEVzJyMnZaallFUlVaTlgzVkc4cExuQWhnWm5TY090OE5hWWo4ODBEUGhmWThhNkY1aW5lZVloN21MdklZQmZURFZra1BQOSs5RmdSeUx3R05VdXNzbjN4T2Zya0FvbytmK3RDNGxTcHdEOGZvaUZhTWF0SkJZRWx4N0dGU1loM2R6UEgrRXFpejU0SUlwdU5pZk1xTUovTUJuRlpSSzB0c3VndGRhZzFKb3Z6S3JyQXNrM0kvUkg3cjF2Z3MxczNCRlR0MEg5NFJxZkhoWWZHRit3U2tTMFVzREE1QnBjSXpaMlNVakZBM1RmWktuKzNTcTJtQ09hVDBrOHpwT0FJalVVbVBTOTNwbXNqdzNGQ25nMldBMmQ5K3JEQWdNQkFBR2pnZDB3Z2Rvd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdJd2N3WURWUjBmQkd3d2FqQm9vR2FnWklaaWJHUmhjRG92TDJOaFpITXVabWx1WVc1NlpTNXBkQzlEVGoxRFFTVXlNRTFwYm1semRHVnlieVV5TUdSbGJHeGhKVEl3VTJGc2RYUmxKVEl3VkdWemRDeFBQVTFwYm1semRHVnlieVV5TUdSbGJHeGhKVEl3VTJGc2RYUmxMRU05U1ZRd0hRWURWUjBPQkJZRUZOK1BDQnB1MkZPa28zVnZTOS94V0haa2hiVjlNQTRHQTFVZER3RUIvd1FFQXdJRm9EQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFmclVPWWRZU2FJUWNPSDFXeGx0OEZrVzkxUFkyYUpqUFJqKzJTRlh3RVMxZk5zMWVkSU5Oc1VYcUdtMHVySm5XUEtmM2FLSWNhdVo1Y0JzUkYwN3Bnb1ZrTW5IN0wxSGs3TWRFTWpva3FEZzNaL2c5aDBnMmlJTG9TMEVXV2h1UTYxNHh4RFFTMlpKdGlsRjh2TUtCY0gvYVZIUHppSXRmcHBDakVyT2NGQlljbjdwRDNETHpoK1BadW0xY1JMMzl2Z2VUUkNNUk9LTmh4Y3dYdkowbDdLMitCZndBZ0hJSjVsaHpsV25WOGIwZUVHL0RBMlVPWGQwV3ljeWN3QWpYdm1vbzFBNGZ2Y2psZnZndEpyTDZSRHdUbFpXVkNsdkNROVF0UjRjSlBUYzVqQTBkekZ0Nk45cTBtR0hyZTlmclNOeEhoRkw3RVd3emo3aE1iUUtqTDh3WEQ2OThmcTZJck9ldEF2bzV4M0RGOHhMRFNlSnV0cnRic3NSYU1EcmxPVVN4eksrQk0vRVZJazN1RTBtMEFSMVY0cXJLUG5pLzVOcWtnV3dTQWREUjFBRGZEQWV5ckQ0SU43ZFdMMWFzdllyVW9GTnBkYld3SENRdFJuOVdGYnVOMzRETkczM1JOMU1KUm1lSnAvTEpZcHZTL29jb0pBZ1NNMlM1SGF0bEl0VjU4YUQ0V0c3c1NGZXZLdFlOZjBxOVg3K3BmR29FYjJQc2FaQ05GY0loTUU0QW9oeU9HOG93Nm0wd012YWFtKzYrb0VpVmh5K2RxVm54NU9YNU9wUFlhVWd0R29LUFlhSllVUnlrUXU4TjNtWmtyMGxnRWd4b1FIMDUrbFBUdWV2UFFvS3U0c09zbCt3bXZHb3NKbmpGQWJ4SzJINXhQMTRhVzNHeTZPMD0iXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJQUk9WQVgwMFgwMFgwMDBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJuYmYiOjE3MTAzMjMwNTgsImlzcyI6ImF1dGg6QTEjMTExRU5HSU5ORVJJTkciLCJleHAiOjE3MTAzMzAyNTgsImlhdCI6MTcxMDMyMzA1OCwianRpIjoiMTIzNCJ9.wn8m0ns6j_nhxs7Vtm7PXVRuVRuh2m-H7OvPy6xqOendxItGrqGYwmTSmzbMaZfGHETYIh39Vdhj2orL_ChNr_-szWbb862fmgrZY-qAgNvT9iaUVcLkJ_S6wyx2MigxQj4czk3-ogzH8N8iJ11kzt2RGOYSU425GkO1tyvryUzhMl-P_FAFyWuNLubPV1izCNcEwML5JM4poRYgCIDz9uka4sI0puQBiJKmeHWcd4jt1dXcwJmmIx0vWN6ot-g1vO11Ynj1-e8z3Sr-O89VQEpbzq6ZU31JpO_Sx371XlKAcCoX6jsIIk6bKb2C9lCVkTqCeL--6FTGmCwgyvx5jQ

Signature
eyJ4NWMiOlsiTUlJRkZ6Q0NBditnQXdJQkFnSVVDZGwreVNlVTMwNHhIWnd0YUw1Y1ppUjUydGt3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TWpFeE16QXlNakUyTkRaYUZ3MHlOVEV4TXpBeU1qRTJORFZhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMweE1URkZUa2RKVGs1RlVrbE9SekVhTUJnR0ExVUVBd3dSVXpFak1URXhSVTVIU1U1T1JWSkpUa2N3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRG4xRHp5NEcvQUI0ZGU4WFNQNjlvcXlxNzB0R01DODA5blN1MG9PYnIzbURHcHNaNy9Ea0ljRUdrRkhCbkFyQ1ZRUUZhVEJsbDR1K0tzTDBXUFRyZ2d2QmhFZUsvT2xzTExuM2g3TzBKUVJwUnBiME10RUdNZ2hCR0lyRHcwYWNKZ3RrOUlTekljL3d2TDA1V3h5K3BvV3lFZ2RaWXp6MDB1blZsbzk3TzN1dVE0Z3ZDUHRpSkN2N0JwNWFOMS9PbEJFQW5VaFhoUlRaZG16cGxRWm9YK1gvdkIwNkpWMHN0dGJoWmljT0RHQWYvVjlWQnlpdW4vdmpybkkvOElvNTlPVVJoNjdNcVdFdDFSTmpkMFgzL05lSktMakZudDNIMUlETS9ERVI3U1UyVU9ZcWZUNzNUdTNQaVVaRWdXdEx5a1hzNlJQc2htUzFkNjdwWlJoY1R6QWdNQkFBR2pnY2d3Z2NVd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3Y3dZRFZSMGZCR3d3YWpCb29HYWdaSVppYkdSaGNEb3ZMMk5oWkhNdVptbHVZVzU2WlM1cGRDOURUajFEUVNVeU1FMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbEpUSXdWR1Z6ZEN4UFBVMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbExFTTlTVlF3SFFZRFZSME9CQllFRk1VM29KNFA0SEF4VkhPTkVGTlNQMzZEVFFIaE1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQWE4dHJ4VFk4U2RwRFI4bXlHMlM5UE5xWStldW41REdydEpmVFlMWFo0MEZDWWxHb2luMjJWNTAweVZOL0R0cktibmM5SFIxem1yanpDeFkycDI0WCtPUCtZWGYzTnRqVXUvN2hNeDA4TUJGcm96czZIMFkxanJJR0ZtNlR2UUJiU3ZEZCs3S3hjNWduK1RPUXpna0UzaWJwcWZ0azFDRjVpbWNWRmZyd0JMT0x1TENQYkloTnlra0pqKzdFWEdmWGhIMmRIYWorNGVtUGhyY3JPZC9GM1JsTXhtNVhoeUU0RmJqWklLaGxhZE9rNFlZdzJoL0wyRHpxemthMHMvcG5WODVHS09FT2s0M25BTi9Ld0JFRkVTOEJBZlBreFJ6SXByaU9iVGRjWjlYb3JWY25ObmRaTjlDREdXcU9jdk9HaUVZWEkxOXhJYStsMFF1SlQyRzlBdFd6Q3ZtS05nNy9JTDBlM3RNWHh3WFRaTWVhL0tIajFDTGZqYys2L1JhK1dtZmtqbWNBbzRJY1N6dzN6MkpXNWRZU1d6SWtTSjZHYm5RdEhhYWhJZXdXMll5VHJnb0VxeTBpQXpWUGlEdllYVVVtNXhIRGJmZThPMll6R09YR25qTFlxOTJvVVFnVnRVNW4vNVlvVFVZNXdjRVdNVkxvTGVRMUxPUUlKaFdGbk5QTmpNRjVRYUNqMitUUGlVSGFndFBTSGx4Y2VkazJzbGtkdU9LOUw3cUM5RGx6R0dZaFgwYU42RTNiNlFRbDRxMTRDRzJtMi9iUWo0YXJURS9uZ2o4U1AzWEduN0w1WkJOb0lmU2p0c0FjRFpMY2ZlYTgrL1NKV1MwM3lFSGZKdHlrWUtGbHRGRnl4bytjaXNnRmt0SDA2d0owRFdWcVRSS1c2WU4vWEg0PSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJQUk9WQVgwMFgwMFgwMDBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImxvY2FsaXR5IjoiMTIwODA1MTAiLCJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExRU5HSU5ORVJJTkciLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlcnNpb24iOiIyMC4xNS4wMCIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBMYXppbyIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMTIwIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwibmJmIjoxNzEwMzIzMDU4LCJhY3Rpb25faWQiOiJDUkVBVEUiLCJwYXRpZW50X2NvbnNlbnQiOnRydWUsInJlc291cmNlX2hsN190eXBlIjoiKCcxMTQ4OC00Xl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsImF0dGFjaG1lbnRfaGFzaCI6IjJhNjBiMzI5YjQxZGNkZDcwMmExYmJlYjk1YTA4MDYxNTNhMjNkZmNkNmIzM2IyNWY2M2IwNzdjN2M4YzY4NGEiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiQVJFQVMgQU1CV0VCIiwiZXhwIjoxNzEwMzMwMjU4LCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlbmRvciI6IkVuZ2luZWVyaW5nIEluZ2VnbmVyaWEgSW5mb3JtYXRpY2EgUy5wLkEuIiwiaWF0IjoxNzEwMzIzMDU4LCJqdGkiOiI1Njc4IiwicGVyc29uX2lkIjoiQ0NSUE5UNjNTMDFHMzE3QV5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIn0.d122LNy3hAJ5YKCDl6RK6Kk0ICdkvWUGEbyWlLoneQmVPf0uM1VgmNr5POevactnHpCxRYgzZEcFhJ60kU-d2hRwTRZu6UXYS0Hlj5FzYnNW0Fjl2Hg2lYlfnsdm0zgNmZ0372RaOMr1tEAS740-XCib5hxHwIbEs-S2WSJHGBxgltAyfwJEcZOK2ScpgN3dxnJwgUjWvAfAJZwMZKlWbpwHtgcgpuyFxLtQgY_Mvihe2pYSiYdxMmcIsrdQN5HiH7mT7uk7KtsAr9UrMkpnwfLmqai6ZeeN8jiGxGi71CiYy1pRlSQVP7GOdhjmDFOhRz7e01zEAKf5XWSNGMPBcw

insieme al pdf

ottengo come errore:
{
    "type": "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
    "title": "AuthorizationContentDeny",
    "status": 403,
    "detail": "Unauthorized request content",
    "govway_id": "64b0bd62-e10e-11ee-b1d5-005056ae7395"
}

Grazie mille in anticipo per l'attenzione e per ogni eventuale riscontro.

**Comment by IStacchiotti** [comment]
Buongiorno, in primo luogo potreste confermarci di aver utilizzato questo url nelle chiamate: https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation? Abbiamo notato che nel suo precedente messaggio l'url non corrisponde, forse per un errore nel copia incolla. Grazie

**Comment by Beatrice164** [comment]
Salve l’url è corretto
Cordiali saluti, Beatrice

Da: IStacchiotti ***@***.***>
Inviato: mercoledì 13 marzo 2024 12:12
A: ministero-salute/it-fse-support ***@***.***>
Cc: Beatrice Clemente ***@***.***>; Author ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Errore 403 AuthorizationContentDeny / Unauthorized request content (Issue #664)

Buongiorno, in primo luogo potreste confermarci di aver utilizzato questo url nelle chiamate: https: //modipa-val. fse. salute. gov. it/govway/rest/in/FSE/gateway/v1/documents/validation? Abbiamo notato che nel suo precedente messaggio l'url non
ZjQcmQRYFpfptBannerStart
Security Warning: This email originated from outside of the organization. Do not click links or open attachments unless you verified the sender mail address and know the content is safe!
ZjQcmQRYFpfptBannerEnd

Buongiorno, in primo luogo potreste confermarci di aver utilizzato questo url nelle chiamate: https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation<https://urldefense.com/v3/__https:/modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation__;!!LQkDIss!UVJSJ9OFEIPiXHXHLPeYsFH9xY3U5loqhl-KRvtHWig8vSU6GkV14cRn0frZFJke2JXfH0wBAz4T_bvlVae3lxbfOMFntw$>? Abbiamo notato che nel suo precedente messaggio l'url non corrisponde, forse per un errore nel copia incolla. Grazie

**Comment by IStacchiotti** [comment]
Nel Bearer token il campo iss risulta così valorizzato: `"iss": "auth:A1#111ENGINNERING"`.
Il valore atteso per il campo in questione è invece `"iss": "auth:S1#111ENGINNERING"`, dal momento che per la generazione dei token deve essere utilizzato il certificato di firma (#S1). Potreste cortesemente riprovare? Rimaniamo a disposizione nel caso in cui l'errore dovesse ripresentarsi, grazie.

**Comment by Beatrice164** [comment]
Gent.mi
anche da postman ricevo il medesimo errore
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "fd2e70fc-e14b-11ee-b1d5-005056ae7395"
}

di seguito allego i token generati

Auth
eyJ4NWMiOlsiTUlJRkxEQ0NBeFNnQXdJQkFnSVVJc2NscE9tU1RUVFZvM2lBb2lFTE5GSG5kYVV3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TWpFeE16QXlNakUyTWpaYUZ3MHlOVEV4TWpreU1qRTJNalZhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMweE1URkZUa2RKVGs1RlVrbE9SekVhTUJnR0ExVUVBd3dSUVRFak1URXhSVTVIU1U1T1JWSkpUa2N3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGRVQmVJY3dvSXdBRFhVZFpaQlR0b1JQL2tTNjBiZDA0TkpwcjlCVXBrTDBvRms1WU9oaVg2cUlYQWFEVzJyMnZaallFUlVaTlgzVkc4cExuQWhnWm5TY090OE5hWWo4ODBEUGhmWThhNkY1aW5lZVloN21MdklZQmZURFZra1BQOSs5RmdSeUx3R05VdXNzbjN4T2Zya0FvbytmK3RDNGxTcHdEOGZvaUZhTWF0SkJZRWx4N0dGU1loM2R6UEgrRXFpejU0SUlwdU5pZk1xTUovTUJuRlpSSzB0c3VndGRhZzFKb3Z6S3JyQXNrM0kvUkg3cjF2Z3MxczNCRlR0MEg5NFJxZkhoWWZHRit3U2tTMFVzREE1QnBjSXpaMlNVakZBM1RmWktuKzNTcTJtQ09hVDBrOHpwT0FJalVVbVBTOTNwbXNqdzNGQ25nMldBMmQ5K3JEQWdNQkFBR2pnZDB3Z2Rvd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdJd2N3WURWUjBmQkd3d2FqQm9vR2FnWklaaWJHUmhjRG92TDJOaFpITXVabWx1WVc1NlpTNXBkQzlEVGoxRFFTVXlNRTFwYm1semRHVnlieVV5TUdSbGJHeGhKVEl3VTJGc2RYUmxKVEl3VkdWemRDeFBQVTFwYm1semRHVnlieVV5TUdSbGJHeGhKVEl3VTJGc2RYUmxMRU05U1ZRd0hRWURWUjBPQkJZRUZOK1BDQnB1MkZPa28zVnZTOS94V0haa2hiVjlNQTRHQTFVZER3RUIvd1FFQXdJRm9EQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFmclVPWWRZU2FJUWNPSDFXeGx0OEZrVzkxUFkyYUpqUFJqKzJTRlh3RVMxZk5zMWVkSU5Oc1VYcUdtMHVySm5XUEtmM2FLSWNhdVo1Y0JzUkYwN3Bnb1ZrTW5IN0wxSGs3TWRFTWpva3FEZzNaL2c5aDBnMmlJTG9TMEVXV2h1UTYxNHh4RFFTMlpKdGlsRjh2TUtCY0gvYVZIUHppSXRmcHBDakVyT2NGQlljbjdwRDNETHpoK1BadW0xY1JMMzl2Z2VUUkNNUk9LTmh4Y3dYdkowbDdLMitCZndBZ0hJSjVsaHpsV25WOGIwZUVHL0RBMlVPWGQwV3ljeWN3QWpYdm1vbzFBNGZ2Y2psZnZndEpyTDZSRHdUbFpXVkNsdkNROVF0UjRjSlBUYzVqQTBkekZ0Nk45cTBtR0hyZTlmclNOeEhoRkw3RVd3emo3aE1iUUtqTDh3WEQ2OThmcTZJck9ldEF2bzV4M0RGOHhMRFNlSnV0cnRic3NSYU1EcmxPVVN4eksrQk0vRVZJazN1RTBtMEFSMVY0cXJLUG5pLzVOcWtnV3dTQWREUjFBRGZEQWV5ckQ0SU43ZFdMMWFzdllyVW9GTnBkYld3SENRdFJuOVdGYnVOMzRETkczM1JOMU1KUm1lSnAvTEpZcHZTL29jb0pBZ1NNMlM1SGF0bEl0VjU4YUQ0V0c3c1NGZXZLdFlOZjBxOVg3K3BmR29FYjJQc2FaQ05GY0loTUU0QW9oeU9HOG93Nm0wd012YWFtKzYrb0VpVmh5K2RxVm54NU9YNU9wUFlhVWd0R29LUFlhSllVUnlrUXU4TjNtWmtyMGxnRWd4b1FIMDUrbFBUdWV2UFFvS3U0c09zbCt3bXZHb3NKbmpGQWJ4SzJINXhQMTRhVzNHeTZPMD0iXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJQUk9WQVgwMFgwMFgwMDBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJuYmYiOjE3MTAzNDA5MjcsImlzcyI6ImF1dGg6UzEjMTExRU5HSU5ORVJJTkciLCJleHAiOjE3MTAzNDgxMjcsImlhdCI6MTcxMDM0MDkyNywianRpIjoiMTIzNCJ9.tleAoFMLevKnOzM-fJQymMmeDOQnM9UMFJJcbPwPuPGrExvfudB5DW-5WC8HYMAI9fLPi81cS8claU8kJORwweMa3QEKzVbkDChtz3SAhaxf0lgqvwhAyYBAuaSW20xxwgaaLO4XPg5iSqaYPTD8mcEG-cUJQKYCftVcsuOJtfcwsmMUcRnLIxd3fzKsZhjQIMgB9I3tKSlyHyxjzmuWzZ_qDdt8wFJ7uuQpCdCIXWfHMOTx83IcVEtW003RYc-7dm7T10xngcdmeUq1D7PDn2-RI2PB4U50NjFmuoU6DO-ufgk8_zjdBgmTaVgt3PlgU7jzXboVmT8Sxj0M1T12Yg

Sign
eyJ4NWMiOlsiTUlJRkZ6Q0NBditnQXdJQkFnSVVDZGwreVNlVTMwNHhIWnd0YUw1Y1ppUjUydGt3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TWpFeE16QXlNakUyTkRaYUZ3MHlOVEV4TXpBeU1qRTJORFZhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMweE1URkZUa2RKVGs1RlVrbE9SekVhTUJnR0ExVUVBd3dSVXpFak1URXhSVTVIU1U1T1JWSkpUa2N3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRG4xRHp5NEcvQUI0ZGU4WFNQNjlvcXlxNzB0R01DODA5blN1MG9PYnIzbURHcHNaNy9Ea0ljRUdrRkhCbkFyQ1ZRUUZhVEJsbDR1K0tzTDBXUFRyZ2d2QmhFZUsvT2xzTExuM2g3TzBKUVJwUnBiME10RUdNZ2hCR0lyRHcwYWNKZ3RrOUlTekljL3d2TDA1V3h5K3BvV3lFZ2RaWXp6MDB1blZsbzk3TzN1dVE0Z3ZDUHRpSkN2N0JwNWFOMS9PbEJFQW5VaFhoUlRaZG16cGxRWm9YK1gvdkIwNkpWMHN0dGJoWmljT0RHQWYvVjlWQnlpdW4vdmpybkkvOElvNTlPVVJoNjdNcVdFdDFSTmpkMFgzL05lSktMakZudDNIMUlETS9ERVI3U1UyVU9ZcWZUNzNUdTNQaVVaRWdXdEx5a1hzNlJQc2htUzFkNjdwWlJoY1R6QWdNQkFBR2pnY2d3Z2NVd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3Y3dZRFZSMGZCR3d3YWpCb29HYWdaSVppYkdSaGNEb3ZMMk5oWkhNdVptbHVZVzU2WlM1cGRDOURUajFEUVNVeU1FMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbEpUSXdWR1Z6ZEN4UFBVMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbExFTTlTVlF3SFFZRFZSME9CQllFRk1VM29KNFA0SEF4VkhPTkVGTlNQMzZEVFFIaE1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQWE4dHJ4VFk4U2RwRFI4bXlHMlM5UE5xWStldW41REdydEpmVFlMWFo0MEZDWWxHb2luMjJWNTAweVZOL0R0cktibmM5SFIxem1yanpDeFkycDI0WCtPUCtZWGYzTnRqVXUvN2hNeDA4TUJGcm96czZIMFkxanJJR0ZtNlR2UUJiU3ZEZCs3S3hjNWduK1RPUXpna0UzaWJwcWZ0azFDRjVpbWNWRmZyd0JMT0x1TENQYkloTnlra0pqKzdFWEdmWGhIMmRIYWorNGVtUGhyY3JPZC9GM1JsTXhtNVhoeUU0RmJqWklLaGxhZE9rNFlZdzJoL0wyRHpxemthMHMvcG5WODVHS09FT2s0M25BTi9Ld0JFRkVTOEJBZlBreFJ6SXByaU9iVGRjWjlYb3JWY25ObmRaTjlDREdXcU9jdk9HaUVZWEkxOXhJYStsMFF1SlQyRzlBdFd6Q3ZtS05nNy9JTDBlM3RNWHh3WFRaTWVhL0tIajFDTGZqYys2L1JhK1dtZmtqbWNBbzRJY1N6dzN6MkpXNWRZU1d6SWtTSjZHYm5RdEhhYWhJZXdXMll5VHJnb0VxeTBpQXpWUGlEdllYVVVtNXhIRGJmZThPMll6R09YR25qTFlxOTJvVVFnVnRVNW4vNVlvVFVZNXdjRVdNVkxvTGVRMUxPUUlKaFdGbk5QTmpNRjVRYUNqMitUUGlVSGFndFBTSGx4Y2VkazJzbGtkdU9LOUw3cUM5RGx6R0dZaFgwYU42RTNiNlFRbDRxMTRDRzJtMi9iUWo0YXJURS9uZ2o4U1AzWEduN0w1WkJOb0lmU2p0c0FjRFpMY2ZlYTgrL1NKV1MwM3lFSGZKdHlrWUtGbHRGRnl4bytjaXNnRmt0SDA2d0owRFdWcVRSS1c2WU4vWEg0PSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJQUk9WQVgwMFgwMFgwMDBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImxvY2FsaXR5IjoiMTIwODA1MTAiLCJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExRU5HSU5ORVJJTkciLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlcnNpb24iOiIyMC4xNS4wMCIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBMYXppbyIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMTIwIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwibmJmIjoxNzEwMzQwOTI3LCJhY3Rpb25faWQiOiJDUkVBVEUiLCJwYXRpZW50X2NvbnNlbnQiOnRydWUsInJlc291cmNlX2hsN190eXBlIjoiKCcxMTQ4OC00Xl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsImF0dGFjaG1lbnRfaGFzaCI6IjJhNjBiMzI5YjQxZGNkZDcwMmExYmJlYjk1YTA4MDYxNTNhMjNkZmNkNmIzM2IyNWY2M2IwNzdjN2M4YzY4NGEiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiQVJFQVMgQU1CV0VCIiwiZXhwIjoxNzEwMzQ4MTI3LCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlbmRvciI6IkVuZ2luZWVyaW5nIEluZ2VnbmVyaWEgSW5mb3JtYXRpY2EgUy5wLkEuIiwiaWF0IjoxNzEwMzQwOTI3LCJqdGkiOiI1Njc4IiwicGVyc29uX2lkIjoiQ0NSUE5UNjNTMDFHMzE3QV5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIn0.ZuqhOpgPu2Jz_aKoSEKzDi1zosRp-qg2HV7UEovsmL3IS-1y3zIQ_2C8QuaO232O52SoLhpwn7avVBJpfnnv1oAYMmMqBPvViFlswoUm1AA21OLaKqsYaJsl9j3IonmMdH2U7BBD5e5RT9a1sAMy9Yh93hwkwUsbISiVWrTQmYL1QWYrNFYDv3MAjhEAjBrxQZtsCPsVv3lAWRJEy_w436w1NdYD0BjG_jvb8924UGd37aJFQW6Isz-sWksoa1RX-Lzh9O1mOgIsIh_zcEfE-UN7ynDv45fZ0UNprTl_IV7HSlY86fJBb4KCnPwhkA1PU5O1mtZUga3swjQURV2IiA

grazie mille
Cordiali saluti

**Comment by vigliottim** [comment]
Buonasera, chiudiamo il presente ticket per comodità. Le risponderemo in merito all'ultimo errore nel thread [#665](https://github.com/ministero-salute/it-fse-support/issues/665). Grazie.
