### ISSUE TITLE
File PDF

### ISSUE THREAD

**Issue by Saxos-Simone** [ministero-salute/it-fse-support#666]
Buongiorno, al sistema di test devono essere inviati dei nostri _PDF_ di prova iniettati col _CDA_ generato da noi? Oppure dobbiamo utilizzare i _PDF_ che si trovano al link [link](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Pubblicazione/PDF_PER_PUBBLICAZIONE) iniettati col _CDA_ generato da noi?

Nel caso in cui debbano essere inviati i nostri _PDF_ di prova, tali _PDF_, quale **versione** e **livello di conformità** _PDF/A_ devono avere?

**Comment by Saxos-Simone** [comment]
Grazie della delucidazione.
Ma non mi è ancora chiaro un aspetto: a livello di specifica, quale **versione** _PDF/A_, e quale **livello di conformità** _PDF/A_, devono avere i file _PDF_ che produco?

**Comment by vigliottim** [comment]
Non esistono specifiche in merito alla versione e al livello di conformità PDF/A.
Non vengono effettuati controlli sulla tipologia/contenuto del PDF, ma viene verificato solo che si tratti di un PDF (i.e. magic number).

**Comment by Saxos-Simone** [comment]
Capito, grazie mille.
