### ISSUE TITLE
Errore nel file data.json in fase di accreditamento

### ISSUE THREAD

**Issue by penny66** [ministero-salute/it-fse-support#667]
Buongiorno, mi è stato comunicato che il file data.json contiene degli errore, avrei la necessita di capire quali siano gli errori e come proseguire con l'accreditamento.

**Comment by vigliottim** [comment]
Buongiorno, l'errore ricevuto è dovuto al fatto che il data.json non risulta well-formed.
Infatti, mancano le virgole di separazione tra un elemento e l'altro (a partire dall'id 150), come può notare nel seguente screenshot:
<img width="767" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/b1b0a371-9b1a-4342-8e7d-f5c25fb847da">
La preghiamo di correggere e riprovare.
Grazie.

**Comment by penny66** [comment]
La ringrazio dell'indicazione, volevo chiedere, eseguite le correzioni , il file deve essere inviato sempre tramite una nuova pull request?

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
può procedere effettuando le correzioni tramite commit sulla PR già aperta  [#1256](https://github.com/ministero-salute/it-fse-accreditamento/pull/1256)
Grazie

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri procediamo alla chiusura del presente ticket. 
La invitiamo a riaprirlo nel caso in cui avesse bisogno di ulteriore supporto. Grazie.

**Comment by penny66** [comment]
Salve, 

ho provveduto al reinvio del file data.json ma ad oggi non ho avuto riscontro

 

 



Mediagroup snc

Pennacchio Vincenzo

 

Tel. 081 7281343

Mob. 335 7752431

 

 ***@***.***> ***@***.***

www.mediagroupnet.com

 

Le informazioni contenute nella presente comunicazione e i relativi allegati possono essere riservate e sono, comunque, destinate esclusivamente alle persone o alla Societa' sopraindicati.La diffusione, distribuzione e/o copiatura del documento trasmesso 

da parte di qualsiasi soggetto diverso dal destinatario e' proibita, sia ai sensi dell'art. 616 c.p. , che ai sensi del D.Lgs. n. 196/2003.

Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo e di informarci immediatamente per telefono allo

0817281343 o inviando un messaggio all'indirizzo e-mail ***@***.*** ***@***.***> 

 

 

 

 

Da: Michela Vigliotti ***@***.*** 
Inviato: martedì 19 marzo 2024 16:03
A: ministero-salute/it-fse-support ***@***.***>
Cc: Vincenzo Pennacchio ***@***.***>; Author ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Errore nel file data.json in fase di accreditamento (Issue #667)

 

Buonasera, non avendo ricevuto ulteriori riscontri procediamo alla chiusura del presente ticket.
La invitiamo a riaprirlo nel caso in cui avesse bisogno di ulteriore supporto. Grazie.

**Comment by vigliottim** [comment]
Buonasera, la informiamo che la sua pull request è stata presa in carico. 
Riceverà aggiornamenti via e-mail. Grazie.

**Comment by penny66** [comment]
Grazie per la risposta

 



Mediagroup snc

Pennacchio Vincenzo

 

Tel. 081 7281343

Mob. 335 7752431

 

 ***@***.***> ***@***.***

www.mediagroupnet.com

 

Le informazioni contenute nella presente comunicazione e i relativi allegati possono essere riservate e sono, comunque, destinate esclusivamente alle persone o alla Societa' sopraindicati.La diffusione, distribuzione e/o copiatura del documento trasmesso 

da parte di qualsiasi soggetto diverso dal destinatario e' proibita, sia ai sensi dell'art. 616 c.p. , che ai sensi del D.Lgs. n. 196/2003.

Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo e di informarci immediatamente per telefono allo

0817281343 o inviando un messaggio all'indirizzo e-mail ***@***.*** ***@***.***> 

 

 

 

 

Da: Michela Vigliotti ***@***.*** 
Inviato: martedì 19 marzo 2024 16:42
A: ministero-salute/it-fse-support ***@***.***>
Cc: Vincenzo Pennacchio ***@***.***>; Author ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Errore nel file data.json in fase di accreditamento (Issue #667)

 

Buonasera, la informiamo che la sua pull request è stata presa in carico.
Riceverà aggiornamenti via e-mail. Grazie.
