### ISSUE TITLE
Errore AuthorizationContentDeny

### ISSUE THREAD

**Issue by rantole** [ministero-salute/it-fse-support#668]
Buongiorno,
richiamando l'url di test per la validazione (https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation) otteniamo il seguente errore:
{
    "type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
    "title":"AuthorizationContentDeny",
    "status":403,
    "detail":"Unauthorized request content",
    "govway_id":"fdb019e7-e14a-11ee-8bf1-005056ae54fa"
}
Come possiamo risolvere la problematica?
Di seguenti riportiamo una parte della richiesta inviata
Grazie

POST /govway/rest/in/FSE/gateway/v1/documents/validation HTTP/1.1
Host: modipa-val.fse.salute.gov.it
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1YyI6WyJMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VaaVZFTkRRVEZYWjBGM1NVSkJaMGxWU3padmRHWkJjbFJuT0ZwdVNUQlNRMVZWV0ZsR09HaEtWbEkwZDBSUldVcExiMXBKYUhaalRrRlJSVXdLUWxGQmQxWjZSVzVOUTFWSFFURlZSVUYzZDJWUk1FVm5WRmRzZFdGWVRqQmFXRXAyU1VkU2JHSkhlR2hKUms1b1lraFdNRnBUUWxWYVdFNHdUVkk0ZHdwSVVWbEVWbEZSUzBSQ1drNWhWelZ3WXpOU2JHTnRPR2RhUjFaellrZEZaMVV5Um5Oa1dGSnNUVkZ6ZDBOUldVUldVVkZIUlhkS1NsWkVRV1ZHZHpCNUNrNUVRWGxOUkZsNFRWUlZlVTFFUm1GR2R6QjVUbnBCZVUxRVdYaE5WRlY1VFVSQ1lVMUhOSGhEZWtGS1FtZE9Wa0pCV1ZSQmEyeFZUVkk0ZDBoUldVUUtWbEZSUzBSQ1drNWhWelZ3WXpOU2JHTnRPR2RhUjFaellrZEZaMVV5Um5Oa1dGSnNUVkk0ZDBoUldVUldVVkpvUkVKYVJGSnFjRXBXUXpGUlZXczVWd3BSVm1kM1RVWm5kMDFHWjNkTlJFSmFUVkl3ZDBkM1dVUldVVkZFUkVKU1ZFMVRUWGhOVkVWcVVWWlNUVkZXVGs1U1ZWSktVVEJHV1ZkRVEwTkJVMGwzQ2tSUldVcExiMXBKYUhaalRrRlJSVUpDVVVGRVoyZEZVRUZFUTBOQlVXOURaMmRGUWtGUFVtMUxkbkozUkdnMWNXaFFNVTFvZEhrclVHOVRVbUpuY1ZRS1kxRkdOek01U21KMFQzVnlURmh2V0ZkQ1FqZFViR2xaV25aelUwbERjMEpDWmpZcldrRktOVUpyZFZoU2NraHhNWFo1VjFFNFpIUlBRMmszVUdJeWF3cDBRV1JwUVVaRlEyczFNa015T1VoeVNFdHFNRTA0VEVSMlpETkVZVUpoZVdsUldHOWljVlZqVXpKV2JXUk5jR1ZUUWs5dk1FbFVSM2Q1UTFOWFVscHNDbXhPWkZaVldteG5ZbkZ0UmpKcFF6WkdSME5xU2pCWWNYSkZNaTlOTkhsbFJEbENVM1JVWjJOblUzTkhVMDFJTmtsUVQydFpjRkpDWlhnMmRXVmlVR2tLZEhSMWIyOTJVRVJLY0dNNFEyVTJibWRZWmpablUydEJZMlJvYm5wWVNVbEhZbXhrUmtab04ySjViVmROYlhGdlRETlFSVmg0UWxkWGFIVlRORVp3YWdwQmFVVXJPU3QzY0RGbmFIZFhaaTl0Vm5sYVpYcFhSMmxJU1ZOeGRFSnZiRmxXUWpKak5GRjNTemsyTVU1UGEwWjVkRWhxWW5KSGVGZDVWVU5CZDBWQkNrRmhUME5CVW1kM1oyZEZWVTFDT0VkQk1WVmtTWGRSV1UxQ1lVRkdRbGsxY1ZKdlJtbGlZMUJNWWtreE4yTkpTbTF6VlVSbmVVa3ZUVUpKUjBFeFZXUUtTVUZSVEUxQmEzZENkMWxHU3pCM1pFRlJjM2RuWVRCSFFURlZaRWgzVTBKd1ZFTkNiMnBEUW00MlEwSnVTME5DYlZsaFFteHRhREJrU0VKNlQyazRkZ3BaTWtaNllqSmtiR0ZZVGpKaFYzZDFZekk1YmxwWGEzVmhXRkYyV2xkd2FWa3lSWFpqU0ZacFlrZHNhbVF5Vm1sTU0yUnNXVzFTY0dNelVYWlpNbFo1Q21SSFVuQmpNMUV2V1RJeGExQlhUbmxpUTFwd1l6Tk9NVnBZU1RsUk1EUnNUVEJTUkZGVGRFNWhWelZ3WXpOU2JHTnRPSEphUjFaellrZEZjbFV5Um5NS1pGaFNiRXN4VW14ak0xRnNUV3RPVUVwVVRrVlVWMngxWVZoT01GcFlTblpMTWxKc1lrZDRhRXN4VG1oaVNGWXdXbE5WZVZFd1RXeE5NRkpLVmtSQlpBcENaMDVXU0ZFMFJVWm5VVlZwVDFVeE0wUlpXVXgxVjFCSVNYSmxlRFJpY2xkWVYybHpkbEYzUkdkWlJGWlNNRkJCVVVndlFrRlJSRUZuV2tGTlFUQkhDa05UY1VkVFNXSXpSRkZGUWtOM1ZVRkJORWxEUVZGRFlteEdZMkV5SzI5MVRrTk1TamQ2VkZjcllVUjJjMGxUT1VKVVZYQnVMMmd2VTBaWVdrMWxPRmNLTUdwdlZFaHlNVzh5ZDJGRFVXeHRaMGhWZVVGbWFHd3dUM1JvVEc1c01HbFdXVTUzTnpsQ1ZFNVFhSGhWZUhOME4zaHNkWFZzV0V0WWVrOUplVWx3WkFvd1UwcDBXVmRVTDFGR1RtRTFibTh6VkV0TWFDOVFXblZ2VUZWbk5sSnZTbFJ5UjNGTlVHTlVjakZVTkM5V1pGQjRiM1ZwWnpaSmNEUkRhbkJrWVhKU0NtZGlVMFJzYkVKNlREQlNWa1ZKTUdOd1RISjZjMUJGZUROU1FWVk9hRWhaV0VGM1QyaDVTVnBZUVhkWWIxZFFNbE5JVDNWWlJXRTRkR2RKT0U1bWMzb0tWMWQwWVVRemVEUXJPRkZUZFVkRFJqWlphMUJMVjJ4U00wZDBhMll2VjNWclQxVTFURlZhYnpNMlVrMU5UVlpXZGtSdVRrTllUM0Z2VVZRNGEwRXJXZ3AyUlRCTGJucHRTRWhGUmtoVlptMDFTWFpUYW5sdlptUTRaVGx1Y0UwelpUaHRTa3BhWjA1TGJWQlFOazVpWlVSS1dEaENaM0Y0T0VoWEsyRndSMWgwQ2xFMFJtRlJRekkxYUU1V2VrbGxZVTR5UTBoTVJFRmtPVXByTUZJck5XTlFPSHBMY0VWQmRuaFpjazlVVjNaYVJqTnVaa2tyWVUxdmFrOXpMMlo0U0RJS1NrWnJOVE5MV0ZSc0sySXlaVEF3U2k5SFducHJlUzlWTWpSRk9WVXJkVU5XYVhOV1RHTndaMjlsVlZwc01tYzFWbVE0U0ZvMmEwNUJUbXhpVWxaWFNRcHVNM2xtYVZwcmRUVkdiMUZSWlhGbU1qUkhabWMyZHpkWWVUTlZTbXcxWmt0bVdHNDVjMmRDWnpsM0x6bDFLeXM0ZEUxT09XbElNV0ZIVUhVeU9YTnBDa1ZPUlhGYWQwOW9VMFl2ZUhabUszSlZWVnBHWlcxeFVreENNbE5FVDNabWRUVXZVakpIVVN0M00wWnFabVJTTVVSVVFUVm1Lemw1V0RGeU0zVmtlazRLYWxsTmFHZHlibkY1VW5wQ1JqTTJMMnR5VkVWMWQyUTJkMVJ5V1hOS2VFRmhlREZJZDBwWlZVTkdiMncwYjI5dllqRnJXRlZUU1V3dk1UUXlWM2xUVFFwNGR6MDlDaTB0TFMwdFJVNUVJRU5GVWxSSlJrbERRVlJGTFMwdExTMCJdfQ.eyJpc3MiOiJhdXRoOlMxIzExMSNBVExBU01FRElDQVhYIiwiaWF0IjoxNzEwMzQ0NzgzLCJleHAiOjE3MTAzNzM1ODMsImp0aSI6MTcxMDM0NDc4MywiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwic3ViIjoiWFhYWF5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIn0.J-UUg8OVijhlESDfWtWlDmzu6rV0BiD-K_6DyWo3kk2wYv6JNZ6EnTllLvvVe98usX0ChMoI9dcvCvinolx0VSXoVc84xSMMlkGFWadGrJ7eHrnnrIi_xzGSvMc6Mjexmogbw-bfZqY1Kik0G2G7W9Yhb4hjF3hwVBSsLHugo6IF2rrDEBiYGaKnEVrsgN06Z6rG97AZrJNg8CxC71JX3GxC5QvohO-vOxGhsUptIvI__wS6WNThz6VGKx5hIcO14O6Yud8NCIXfukBpqay34nlCWWfHsYO5Kwflz1wgMZJZZwUs001Mt5cOfdf8eVzKWhc__rDXS0TiiRADOVldWQ
FSE-JWT-Signature: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1YyI6WyJMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VaaVZFTkRRVEZYWjBGM1NVSkJaMGxWU3padmRHWkJjbFJuT0ZwdVNUQlNRMVZWV0ZsR09HaEtWbEkwZDBSUldVcExiMXBKYUhaalRrRlJSVXdLUWxGQmQxWjZSVzVOUTFWSFFURlZSVUYzZDJWUk1FVm5WRmRzZFdGWVRqQmFXRXAyU1VkU2JHSkhlR2hKUms1b1lraFdNRnBUUWxWYVdFNHdUVkk0ZHdwSVVWbEVWbEZSUzBSQ1drNWhWelZ3WXpOU2JHTnRPR2RhUjFaellrZEZaMVV5Um5Oa1dGSnNUVkZ6ZDBOUldVUldVVkZIUlhkS1NsWkVRV1ZHZHpCNUNrNUVRWGxOUkZsNFRWUlZlVTFFUm1GR2R6QjVUbnBCZVUxRVdYaE5WRlY1VFVSQ1lVMUhOSGhEZWtGS1FtZE9Wa0pCV1ZSQmEyeFZUVkk0ZDBoUldVUUtWbEZSUzBSQ1drNWhWelZ3WXpOU2JHTnRPR2RhUjFaellrZEZaMVV5Um5Oa1dGSnNUVkk0ZDBoUldVUldVVkpvUkVKYVJGSnFjRXBXUXpGUlZXczVWd3BSVm1kM1RVWm5kMDFHWjNkTlJFSmFUVkl3ZDBkM1dVUldVVkZFUkVKU1ZFMVRUWGhOVkVWcVVWWlNUVkZXVGs1U1ZWSktVVEJHV1ZkRVEwTkJVMGwzQ2tSUldVcExiMXBKYUhaalRrRlJSVUpDVVVGRVoyZEZVRUZFUTBOQlVXOURaMmRGUWtGUFVtMUxkbkozUkdnMWNXaFFNVTFvZEhrclVHOVRVbUpuY1ZRS1kxRkdOek01U21KMFQzVnlURmh2V0ZkQ1FqZFViR2xaV25aelUwbERjMEpDWmpZcldrRktOVUpyZFZoU2NraHhNWFo1VjFFNFpIUlBRMmszVUdJeWF3cDBRV1JwUVVaRlEyczFNa015T1VoeVNFdHFNRTA0VEVSMlpETkVZVUpoZVdsUldHOWljVlZqVXpKV2JXUk5jR1ZUUWs5dk1FbFVSM2Q1UTFOWFVscHNDbXhPWkZaVldteG5ZbkZ0UmpKcFF6WkdSME5xU2pCWWNYSkZNaTlOTkhsbFJEbENVM1JVWjJOblUzTkhVMDFJTmtsUVQydFpjRkpDWlhnMmRXVmlVR2tLZEhSMWIyOTJVRVJLY0dNNFEyVTJibWRZWmpablUydEJZMlJvYm5wWVNVbEhZbXhrUmtab04ySjViVmROYlhGdlRETlFSVmg0UWxkWGFIVlRORVp3YWdwQmFVVXJPU3QzY0RGbmFIZFhaaTl0Vm5sYVpYcFhSMmxJU1ZOeGRFSnZiRmxXUWpKak5GRjNTemsyTVU1UGEwWjVkRWhxWW5KSGVGZDVWVU5CZDBWQkNrRmhUME5CVW1kM1oyZEZWVTFDT0VkQk1WVmtTWGRSV1UxQ1lVRkdRbGsxY1ZKdlJtbGlZMUJNWWtreE4yTkpTbTF6VlVSbmVVa3ZUVUpKUjBFeFZXUUtTVUZSVEUxQmEzZENkMWxHU3pCM1pFRlJjM2RuWVRCSFFURlZaRWgzVTBKd1ZFTkNiMnBEUW00MlEwSnVTME5DYlZsaFFteHRhREJrU0VKNlQyazRkZ3BaTWtaNllqSmtiR0ZZVGpKaFYzZDFZekk1YmxwWGEzVmhXRkYyV2xkd2FWa3lSWFpqU0ZacFlrZHNhbVF5Vm1sTU0yUnNXVzFTY0dNelVYWlpNbFo1Q21SSFVuQmpNMUV2V1RJeGExQlhUbmxpUTFwd1l6Tk9NVnBZU1RsUk1EUnNUVEJTUkZGVGRFNWhWelZ3WXpOU2JHTnRPSEphUjFaellrZEZjbFV5Um5NS1pGaFNiRXN4VW14ak0xRnNUV3RPVUVwVVRrVlVWMngxWVZoT01GcFlTblpMTWxKc1lrZDRhRXN4VG1oaVNGWXdXbE5WZVZFd1RXeE5NRkpLVmtSQlpBcENaMDVXU0ZFMFJVWm5VVlZwVDFVeE0wUlpXVXgxVjFCSVNYSmxlRFJpY2xkWVYybHpkbEYzUkdkWlJGWlNNRkJCVVVndlFrRlJSRUZuV2tGTlFUQkhDa05UY1VkVFNXSXpSRkZGUWtOM1ZVRkJORWxEUVZGRFlteEdZMkV5SzI5MVRrTk1TamQ2VkZjcllVUjJjMGxUT1VKVVZYQnVMMmd2VTBaWVdrMWxPRmNLTUdwdlZFaHlNVzh5ZDJGRFVXeHRaMGhWZVVGbWFHd3dUM1JvVEc1c01HbFdXVTUzTnpsQ1ZFNVFhSGhWZUhOME4zaHNkWFZzV0V0WWVrOUplVWx3WkFvd1UwcDBXVmRVTDFGR1RtRTFibTh6VkV0TWFDOVFXblZ2VUZWbk5sSnZTbFJ5UjNGTlVHTlVjakZVTkM5V1pGQjRiM1ZwWnpaSmNEUkRhbkJrWVhKU0NtZGlVMFJzYkVKNlREQlNWa1ZKTUdOd1RISjZjMUJGZUROU1FWVk9hRWhaV0VGM1QyaDVTVnBZUVhkWWIxZFFNbE5JVDNWWlJXRTRkR2RKT0U1bWMzb0tWMWQwWVVRemVEUXJPRkZUZFVkRFJqWlphMUJMVjJ4U00wZDBhMll2VjNWclQxVTFURlZhYnpNMlVrMU5UVlpXZGtSdVRrTllUM0Z2VVZRNGEwRXJXZ3AyUlRCTGJucHRTRWhGUmtoVlptMDFTWFpUYW5sdlptUTRaVGx1Y0UwelpUaHRTa3BhWjA1TGJWQlFOazVpWlVSS1dEaENaM0Y0T0VoWEsyRndSMWgwQ2xFMFJtRlJRekkxYUU1V2VrbGxZVTR5UTBoTVJFRmtPVXByTUZJck5XTlFPSHBMY0VWQmRuaFpjazlVVjNaYVJqTnVaa2tyWVUxdmFrOXpMMlo0U0RJS1NrWnJOVE5MV0ZSc0sySXlaVEF3U2k5SFducHJlUzlWTWpSRk9WVXJkVU5XYVhOV1RHTndaMjlsVlZwc01tYzFWbVE0U0ZvMmEwNUJUbXhpVWxaWFNRcHVNM2xtYVZwcmRUVkdiMUZSWlhGbU1qUkhabWMyZHpkWWVUTlZTbXcxWmt0bVdHNDVjMmRDWnpsM0x6bDFLeXM0ZEUxT09XbElNV0ZIVUhVeU9YTnBDa1ZPUlhGYWQwOW9VMFl2ZUhabUszSlZWVnBHWlcxeFVreENNbE5FVDNabWRUVXZVakpIVVN0M00wWnFabVJTTVVSVVFUVm1Lemw1V0RGeU0zVmtlazRLYWxsTmFHZHlibkY1VW5wQ1JqTTJMMnR5VkVWMWQyUTJkMVJ5V1hOS2VFRmhlREZJZDBwWlZVTkdiMncwYjI5dllqRnJXRlZUU1V3dk1UUXlWM2xUVFFwNGR6MDlDaTB0TFMwdFJVNUVJRU5GVWxSSlJrbERRVlJGTFMwdExTMCJdfQ.eyJpc3MiOiJhdXRoOlMxIzExMSNBVExBU01FRElDQVhYIiwiaWF0IjoxNzEwMzQ0NzgzLCJleHAiOjE3MTAzNzM1ODMsImp0aSI6MTcxMDM0NDc4MywiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwic3ViIjoiU1NTTU5ONzVCMDFGMjU3TF5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIiwic3ViamVjdF9vcmdhbml6YXRpb25faWQiOiIwNDEiLCJzdWJqZWN0X29yZ2FuaXphdGlvbiI6IlAuQS4gQm9semFubyIsImxvY2FsaXR5IjoiMjAxIiwic3ViamVjdF9yb2xlIjoiQVBSIiwicGVyc29uX2lkIjoiR1RXR1dZODJCNDJHOTIwTV5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsInJlc291cmNlX2hsN190eXBlIjoiKCc2MDU5MS01Xl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsImFjdGlvbl9pZCI6IkNSRUFURSIsInN1YmplY3RfYXBwbGljYXRpb25faWQiOiJhdGxhc21lZGljYS5jb20iLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlbmRvciI6ImF0bGFzbWVkaWNhLmNvbSIsInN1YmplY3RfYXBwbGljYXRpb25fdmVyc2lvbiI6IjcuMCJ9.ByO7AU9kz49I5umCgBE00jyK1EPL6SQs0C4jg3UqzUL0k9sNlNv8MiqTZa0xxgkAOhJm-i66GddV8OE03DpvHx5Qvwq2Gyxm32DE9Dcoscfsy3Cg-dQfYV_uGOJbZZw3Rb5xBuxQfv83cTLBoDoR3hNqp4AKeHysZaCpM6XuUKaVGS_CIGuQ7Horexg-YDse9pOQCw__6Qw8VUFafGVMhjuWosX8PzLzae4Cop-FYnqvcjDlVjRI3sPyTYsYbsPI4t7dM3BfHhrAzL7nX8uH2E0GQiuYL-nnh2uw5KZHZL05-nXLaxBZF4Aznti-HfLUAWBJ-qzzQ9e4C_5LIr4TEw
Accept: application/json
Content-Type: multipart/form-data; boundary=--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Length: 60597

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="requestBody";
Content-Type: application/json

{
    "healthDataFormat": "CDA",
    "mode": "ATTACHMENT",
    "activity": "VALIDATION"
}

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file/PSS.pdf"
Content-Type: application/octet-stream

%PDF-1.4
%����
1 0 obj
<<
/Type /Catalog
...

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate risulta che entrambi i token non hanno signature valida. 
In particolare i seguenti campi non risultano corretti:

**Authentication Bearer Token:**

- "sub": "XXXX^^^&2.16.840.1.113883.2.9.4.3.2&ISO": al posto di XXXX va inserito il codice fiscale dell’utente che fa richiesta del servizio di interoperabilità

**FSE-JWT-Signature:**

- "iss": "auth:S1#111#ATLASMEDICAXX": deve essere valorizzato con “integrity:” seguito dal common name del certificato di firma, come indicato di seguito "iss": "integrity:S1#111#ATLASMEDICAXX"

Di seguito può trovare il link con la documentazione relativa alla valorizzazione dei campi contenuti nei jwt: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt
Inoltre, la informiamo che al link https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator è disponibile il tool JWT generator che consente di generare il JWT per effettuare le chiamate ai servizi.
 
La preghiamo di riprovare effettuando le correzioni suggerite.
Rimaniamo a disposizione per ulteriori chiarimenti.
