### ISSUE TITLE
Implementazione Gateway

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#669]
Buongiorno, terminate le validazioni interne vorremmo passare alla fase delle pull request. 
Purtroppo non ci è chiara la procedura da seguire. Abbiamo creato un fork: https://github.com/infoserviceonline/it-fse-accreditamento.
Ma ora come dobbiamo proseguire? Mi sembra di aver capito che dovremmo creare delle cartelle ma non so come procedere. Vedo dei repository singoli ed un Gateway che contiene tutte le pull request in generale. Quale dovrebbe interessarci?
Grazie per l'attenzione.

**Comment by vigliottim** [comment]
Buongiorno, le indichiamo di seguito i link alla documentazione dove trovare le informazioni richieste sia sulla struttura dei risultati che sulla creazione della pull-request per l'invio:

- _Procedura di caricamento dei risultati:_ https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#procedura-di-caricamento-dei-risultati
- _Struttura dei risultati:_ https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#struttura-dei-risultati-datajson
- _File riassuntivo:_ https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#file-riassuntivo-report-checklistxlsx
- _Pull-request:_ https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#pull-request

Rimaniamo a disposizione per chiarimenti.

**Comment by infoserviceonline** [comment]
Buongiorno, riapro il ticket perchè continuo ad avere difficoltà, sicuramente dovute alla mia inesperienza con GitHub, mai usato prima.
Seguendo le vostre indicazioni (Procedura di caricamento dei risultati) ho creato un repository:
https://github.com/infoserviceonline/it-fse-accreditamento/new/main/GATEWAY/A1%23111%23INFOSERVICEONLINE/INFOSERVICE/FLY/2.0
Ma quando tento di creare all'interno la cartella FILES, come richiesto, ricevo un errore e non vado oltre:
**There was an error committing your changes: File could not be edited**
Potete suggerirmi una soluzione?
Grazie mille.

**Comment by vigliottim** [comment]
Buongiorno,
l'errore ricevuto è causato dal fatto che FILES non è una cartella, bensì un file, come può notare dall'icona:
<img width="920" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/7d0dd708-462f-43f9-b910-85dab0366fbf">
Pertanto, la invitiamo a cancellarlo e creare una directory.
Per farlo può seguire una delle seguenti opzioni:

1. Click su "Add file" -> Click su "Create new file" -> quando inserisce il nome da dare alla cartella deve aggiungere lo slash finale "/" (altrimenti verrà creato un file, anziché una cartella):

<img width="300" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/65cf88d9-3f70-4a26-925a-a8482bb7f840">
<img width="587" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/31a00872-ed76-4672-bc78-ba85791cd4c8">

2. Se ha già preparato la cartella FILES in locale, può caricarla direttamente con il suo contenuto tramite drag&drop, dopo aver cliccato su "Add new file".

Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by infoserviceonline** [comment]
Grazie per l'aiuto, ma qualcosa non quadra. Sapevo di dover mettere lo slash finale, ma proprio quando lo metto vuole per forza un nome di file, non accetta la creazione senza file, ecco perchè avevo creato quel file, cosciente del fatto che non fosse una cartella. Ora ha cancellato SOLO il file ed è sparita l'intera cartella, tant'è che se provo ad aprirla ricevo un bel 404. Ho provato, quando ancora esisteva la cartella a fare un upload, ma accetta solo file e non cartelle. Ora ricomincio tutto daccapo, spero di avere maggior fortuna.

**Comment by vigliottim** [comment]
Le suggeriamo di riprovare con il metodo 2.
Chiudiamo il presente ticket e, nel caso in cui avesse bisogno di supporto, la invitiamo ad aprire una nuova issue.
Grazie.
