### ISSUE TITLE
Warning su richiesta di validazione

### ISSUE THREAD

**Issue by masmel** [ministero-salute/it-fse-support#670]
Salve, a seguito i un test di validazione nel json di risposta appare anche il seguente campo:
"warning": "[SIGN_WARN - Attenzione il documento risulta firmato in validazione]"
Che cosa significa ?
Il documento pdf allegato alla richiesta risulta firmato.
Grazie.

**Comment by vigliottim** [comment]
Buonasera,
Il warning _"[SIGN_WARN - Attenzione il documento risulta firmato in validazione]"_ indica che il file pdf utilizzato in validazione risulta già firmato. 
Specifichiamo che è previsto che la firma PADES venga applicata tra la validazione e la pubblicazione, pertanto la firma applicata ad un file allegato in validazione, sebbene non produca un errore bloccante, determina il warning in questione.
Rimaniamo a disposizione per chiarimenti.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura del presente ticket. 
La invitiamo a riaprirlo nel caso in cui avesse bisogno di ulteriore supporto. 
Grazie.
