### ISSUE TITLE
Validazione PSS

### ISSUE THREAD

**Issue by DavidBrenko** [ministero-salute/it-fse-support#671]
Buongiorno a fronte di una request di validazione ci viene contestato questo errore:

`{
  "id" : 173,
  "error" : "VERIFICA_NON_SUPERATA",
  "description" : "<error code='301' attribute='root' actual = 'b7e4c151-5210-442b-bc30-d7b56f049a03' expected = '9a6d1bac-17d3-4195-89a4-1121bc809b4a'>ClinicalDocument/component/structuredBody/component/section[ID='Piani_cura']/entry/observation/id</error>"
}`

sul seguente pezzo di xml:
`<entry>
  <observation classCode="OBS" moodCode="RQO">
    <templateId root="2.16.840.1.113883.2.9.10.1.4.3.10.1"/>
    <id root="b7e4c151-5210-442b-bc30-d7b56f049a03"/>
    <code code="V57.1" codeSystem="2.16.840.1.113883.2.9.2.60.6.11" displayName="Altra fisioterapia"/>
    <text>
    <reference value="pdc_prest9"/>
    </text>
    <effectiveTime value="20240213024140+0100"/>
  </observation>
</entry>`

Ci chiedavamo se era un baco di validazione oppure no ?

**Comment by vigliottim** [comment]
Buongiorno, si segnala che, rispetto all'estratto xml fornito, risulta che l'id assume un valore (`id root="b7e4c151-5210-442b-bc30-d7b56f049a03"`) diverso da quello richiesto, ovvero `id root= '9a6d1bac-17d3-4195-89a4-1121bc809b4a'`, generando così l'errore.
Restiamo a disposizione per ulteriori chiarimenti.
