### ISSUE TITLE
validazione e pubblicazione in caso di hub & spoke

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#672]
Buongiorno, 
vi sottopongo un paio di domande relative allo scenario di validazione e pubblicazione in caso di hub & spoke.

Il meccanismo di hub & spoke per la refertazione di esami di laboratorio analisi prevede che lo spoke accetti il paziente e quindi sia il titolare del referto complessivo ma poi invii all'hub alcune prestazioni da eseguire perché non ha i mezzi per farlo in autonomia; hub e spoke sono due laboratori analisi di ASR diverse (potenzialmente l'hub potrebbe anche essere un centro privato convenzionato con lo spoke)

Nello scenario FSE 2.0 il flusso del documento sarebbe il seguente:
- l'hub produce il referto e lo invia al Gateway per la validazione
- a valle della validazione l'operatore dell'hub lo firma e lo invia al repository dello spoke
- lo spoke riceve il referto e lo invia al Middleware Regionale "come se" fosse stato prodotto dall'azienda in cui risiede lo spoke
- il Middleware Regionale esegue la pubblicazione sul Gateway

Nei controlli che esegue il Gateway:

- c'è la verifica, su un determinato documento, che l'azienda che ha inviato in validazione sia la stessa che invia in pubblicazione?
- c'è un controllo che l'azienda che invia in pubblicazione sia la stessa che ha prodotto il CDA2?

Grazie per le indicazioni che potrete fornire in merito.

**Comment by IStacchiotti** [comment]
Buongiorno @ponsilva, le confermiamo che i controlli in questione non sono previsti. Infatti è stato tenuto conto del fatto che gli attori che chiamano la validazione e la pubblicazione (rispettivamente il sistema produttore e il repository documentale locale) possano essere coincidenti (in questo caso è possibile ricorrere al servizio di validazione e pubblicazione contestuale) o meno (nel caso specifico, i due attori invocano in maniera indipendente le api di validazione e di pubblicazione). Rimaniamo a disposizione per ulteriori chiarimenti

**Comment by ponsilva** [comment]
Grazie per il tempestivo riscontro, buona giornata
