### ISSUE TITLE
Accreditamento per Libra Sistemi Pull request #1270

### ISSUE THREAD

**Issue by LibraSistemi** [ministero-salute/it-fse-support#674]
Buongiorno ho fatto una nuova Pull Request #1270 per inviare le modifiche richieste.
Potete darmi un cenno se ho fatto tutto correttamente o meno  e con che tempi vengono rianalizzate le richieste ? 
Grazie

**Comment by LucaRogledi** [comment]
Buonasera, Le confermiamo che la pull request è stata presa in carico. Chiudiamo pertanto il presente ticket, dal momento che eventuali aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email entro qualche giorno lavorativo. Grazie.
