### ISSUE TITLE
Errore semantico nell'invio di un referto di laboratorio

### ISSUE THREAD

**Issue by masmel** [ministero-salute/it-fse-support#675]
Salve, nell'inviare un referto di laboratorio ricevo il seguente errore:
   "title": "Errore semantico.",
    "detail": "[ERRORE-5| L'elemento ClinicalDocument/code deve essere valorizzato con l'attributo @code='68604-8' e il @codeSystem='2.16.840.1.113883.6.1'],[ERRORE-b1| Sezione Esame Eseguito: la sezione DEVE essere presente.],[ERRORE-b2| Sezione Esame Eseguito: La sezione deve contenere l'elemento 'text'.],[ERRORE-b3| Sezione Esame Eseguito: La sezione deve contenere un elemento 'entry'.],[ERRORE-b4| Sezione Referto: DEVE essere presente la sezione \"Referto\".],[ERRORE-b5| Sezione Referto: La sezione deve contenere l'elemento 'text'.],[ERRORE-b6| Il codice '18729-4' non è corretto. La sezione deve essere valorizzata con uno dei seguenti codici:\n\t\t\t121181   Sezione DICOM Object Catalog\n\t\t\t18785-6  Sezione Quesito Diagnostico\n\t\t\t11329-0\t Sezione Storia Clinica\n\t\t\t55114-3\t Sezione Precedenti Esami Eseguiti\n\t\t\t55111-9\t Sezione Esame Eseguito\n\t\t\t18782-3\t Sezione Referto\n\t\t\t55110-1\t Sezione Conclusioni\n\t\t\t55107-7\t Sezione Informazioni Aggiuntive\n\t\t\t55109-3\t Sezione Complicanze\n\t\t\t18783-1  Sezione Suggerimenti per il medico prescrittore\n\t\t\t],[W001| Si raccomanda di valorizzare gli attributi dell'elemento ClinicalDocument/code nel seguente modo: @codeSystemName ='LOINC' e @displayName ='Referto Radiologico'.--> ]",
Nel file data.json utilizzato per generare i token è stato posto
"resource_hl7_type": "('11502-2^^2.16.840.1.113883.6.1')",
ed il PDF e il file CDA xml sono relativi ad un referto di laboratorio.
Perchè la risposta fa riferimento ad un referto di radiologia ?
Grazie.

**Comment by vigliottim** [comment]
Buonasera, potrebbe cortesemente allegare il file pdf utilizzato? Grazie.

**Comment by masmel** [comment]
[referto.pdf](https://github.com/ministero-salute/it-fse-support/files/14647513/referto.pdf)

Salve, in allegato il file pdf utilizzato.
Grazie

**Comment by vigliottim** [comment]
Buongiorno, l'errore ricevuto è causato dall'errata valorizzazione degli attributi _root_ e _extension_ dell'elemento _templateId_. Come riportato nella [guida HL7 Italia](http://www.hl7italia.it/sites/default/files/Hl7/SuperUser/docs/pubblicati/IG-CDA2-RefertoMedicinaLab/1.3/HL7IT-IG_CDA2_RefertoMedicinaLab-v1.3-S.pdf) per la tipologia documentale "Referto di Medicina di Laboratorio (LAB)", essi devono avere i seguenti valori: 

![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/dfe7fab3-9c27-4f19-9792-3e2ae21ca52f)
`<templateId root="2.16.840.1.113883.2.9.10.1.1" extension="1.3" assigningAuthorityName="HL7 Italia" />`

Nel cda iniettato nel pdf in allegato essi sono stati valorizzati con i valori indicati nella relativa [guida HL7 Italia](http://www.hl7italia.it/sites/default/files/Hl7/SuperUser/docs/pubblicati/IG-CDA2-RAD/1.1/HL7IT-IG_CDA2_RAD-v1.1-S.pdf) per la tipologia documentale "Referto di Radiologia (RAD)": 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/8f1463ce-f913-4196-9fe3-4dd55c907a30)
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/01755729-9379-4a2a-8862-627b2f4024e4)

La preghiamo di effettuare le correzioni indicate e riprovare. 
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by masmel** [comment]
Salve, per il test case 3 per Referti di Laboratorio ricevo il seguente errore:
{
    "traceID": "90ada579caa7fb42",
    "spanID": "90ada579caa7fb42",
    "type": "/msg/semantic",
    "title": "Errore semantico.",
    "detail": "[ERRORE-b10| L'elemento specimen deve contenere l'elemento specimenRole/specimenPlayingEntity ],[ERRORE-b11| L'elemento specimen/specimenRole/specimenPlayingEntity deve contenere l'elemento 'code']",
    "status": 422,
    "instance": "/validation/error",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.150.4.4.a213b0da1d2cf1df75173d61f114047823a39cf93a59d56d18b68a39bb37e39e.5938b59e50^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Di seguito allego il file del referto.
Potrei sapere dove è il problema ?
Grazie.

[referto.pdf](https://github.com/ministero-salute/it-fse-support/files/14670088/referto.pdf)

**Comment by LucaRogledi** [comment]
Buongiorno,
Dalle analisi risulta che nella seguente sezione del cda non è riportata la sezione obbligatoria "specimenPlayingEntity" (in caso la sezione "specimen" sia presente) 
![image](https://github.com/ministero-salute/it-fse-support/assets/139234602/78d375fe-6d00-4273-9913-045775f93cbc)

La invitiamo a compilare correttamente il cda seguendo quanto riportato nel file excel dei requisiti "LAB - Caso di Test 3" che può trovare al seguente [link](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/5-Referto%20di%20Medicina%20di%20Laboratorio/CDA2_Referto%20Medicina%20di%20Laboratorio_OK.xlsx)
![image](https://github.com/ministero-salute/it-fse-support/assets/139234602/53afe71e-2351-400f-9b77-b3867a61a008)

Restiamo a disposizione per ulteriori chiarimenti.
Grazie
