### ISSUE TITLE
Risposta alla richiesta di accreditamento

### ISSUE THREAD

**Issue by S2INFORMATICA-NA** [ministero-salute/it-fse-support#676]
Buongiorno,
Dopo avere caricato i file necessari, Il giorno 03/03/2024 ho ricevuto via mail la richiesta di cancellare alcuni file per poter far partire la procedura di accreditamento.
I file sono stati cancellati lo stesso giorno , ma ancora non c'e' stata riposta.
Potrei avere il sospetto di dovere effettuare una richiesta PULL che ho appena effettuato.
Come posso assicurarmi che abbia svolto correttamente le azioni richieste ?
Grazie.

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Le segnaliamo che al momento non risultano presenti PR aperte da S2INFORMATICA-NA. 
La invitiamo a riaprire la PR che è stata chiusa: https://github.com/ministero-salute/it-fse-accreditamento/pull/1273 o effettuare una nuova PR, dopodiché gli aggiornamenti relativi alla richiesta di accreditamento le saranno notificati via email entro qualche giorno lavorativo. 
Rimaniamo a disposizione per eventuali chiarimenti.
Grazie
