### ISSUE TITLE
Le cartelle che son al di sotto di GATEWAY nella repository di lavoro

### ISSUE THREAD

**Issue by S2INFORMATICA-NA** [ministero-salute/it-fse-support#677]
Buonasera,
Mi sembra di capire che nell'ambiente di lavoro di S2INFORMATICA (generato da un fork della cartella principale) , sotto GATEWAY, esistano sia la sua cartella di lavoro che tutte le altre facenti parte della repository generale e non saprei se questa e' la condizione normale o dipende da un errore fatto in fase di creazione. 
Sarebbe consigliabile/opportuno/utile/inutile/dannoso cancellare sotto la cartella GATEWAY della propria repository le cartelle che non sono di competenza ?
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, come descritto in [documentazione]( https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#procedura-di-caricamento-dei-risultati), la struttura del repository per ciascun software deve essere la seguente:
`GATEWAY/{commonName auth}/{subject_application_vendor}/{subject_application_id}/{subject_application_version}
` 
Quindi, per ogni software bisognerà creare la rispettiva directory di sottomissione rispettando lo schema riportato. 
Pertanto, è corretto che all'interno della cartella GATEWAY siano presenti le cartelle relative a tutti i software, le modifiche che lei effettuerà saranno all'interno della sua directory di sottomissione.
Rimaniamo a disposizione per ulteriori chiarimenti.
