### ISSUE TITLE
Errore di validazione InvalidResponse

### ISSUE THREAD

**Issue by bocci66** [ministero-salute/it-fse-support#678]
Buongiorno, 
da ieri sera alle 22.40 riscontriamo in tutte le nostre installazioni l'errore 

{"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"47f73c33-e693-11ee-93a7-005056ae54fa"}

Vi chiediamo indicazioni al fine di riscontrare il problema evidenziato dai nostri clienti.

Cordiali saluti

**Comment by simeds** [comment]
Mi aggiungo alla segnalazione, anche se da una ricerca pare un disservizio interno temporaneo.

In validazione ottengo: 
```
{
  "type" : "https://govway.org/handling-errors/502/InvalidResponse.html",
  "title" : "InvalidResponse",
  "status" : 502,
  "detail" : "Invalid response received from the API Implementation",
  "govway_id" : "1996237b-e6ab-11ee-9223-005056ae7395"
}
```

**Comment by LucaRogledi** [comment]
Buongiorno,
La ringraziamo per la segnalazione, al momento stiamo registrando dei temporanei disservizi. Seguiranno aggiornamenti sul canale Slack dedicato, non appena i servizi saranno ripristinati. 
Pertanto chiudiamo il presente ticket e restiamo a disposizione per ulteriore supporto.
Grazie.
