### ISSUE TITLE
Password certificati di test

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#679]
Buongiorno, il mio sistemista mi dice che per poter proseguire nell'integrazione ha bisogno di una password per i certificati che io non ho perchè la richiesta è stata fatta senza password. Mi sembra di aver letto che esiste una soluzione ma non la trovo, potete essermi di aiuto o devo rifare nuovamente la richiesta CSR?
Grazie mille.

**Comment by LucaRogledi** [comment]
Buongiorno, 
In caso non sia stata definita una password durante la generazione delle CSR, è necessario ripetere il processo dall'inizio.
Per maggiori informazioni sulla generazione dei certificati può consultare la issue https://github.com/ministero-salute/it-fse-support/issues/591
Restiamo a disposizione per eventuali chiarimenti.
Grazie

**Comment by vigliottim** [comment]
Buongiorno, 
In caso non sia stata definita una password durante la generazione delle CSR, è necessario ripetere il processo dall'inizio.
Per maggiori informazioni in merito alla generazione dei certificati può consultare la seguente issue:
https://github.com/ministero-salute/it-fse-support/issues/591
Restiamo a disposizione per eventuali chiarimenti.
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, 
In caso non sia stata definita una password durante la generazione delle CSR, è necessario ripetere il processo dall'inizio.
Per maggiori informazioni nella generazione dei certificati può consultare la issue https://github.com/ministero-salute/it-fse-support/issues/591
Restiamo a disposizione per eventuali chiarimenti.
Grazie

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri procediamo alla chiusura della presente issue. 
Potrà sempre riaprirla nel caso avesse bisogno di ulteriore supporto. 
Grazie.
