### ISSUE TITLE
Errore in fase di pubblicazione con valorizzato la Ragione esonero/omissione o differimento

### ISSUE THREAD

**Issue by gmarzi** [ministero-salute/it-fse-support#68]
Buongiorno
abbiamo effettuato i test_ok per il certificato vaccinale e la singola scheda .
La fase di validazione e' stata effettuata con successo su tutti i test (code 201) (ad eccezione del vaccino covid per mancanza di AIC valido)
mentre per la pubblicazione solo per i cda  con valorizzato la Ragione esonero/omissione o differimento da il seguente errore ;
500{"traceID":"14d116b359ba8b67","spanID":"14d116b359ba8b67","type":"/msg/generic-error","title":"Errore generico.","detail":"BusinessException: Error while insert ini invocation item : ","status":500,"instance":""} "
Da cosa puo' dipendere?
Grazie

**Comment by IStacchiotti** [comment]
Buon pomeriggio, potrebbe riprovare cortesemente? L'errore non dovrebbe ripresentarsi. Grazie.

**Comment by gmarzi** [comment]
Si funziona grazie.Puo' chiudere issue

**Comment by gmarzi** [comment]
Si funziona grazie.Puo' chiudere issue
