### ISSUE TITLE
Errore di validazione CDA

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#682]
Buongiorno, ho creato un CDA per un referto radiologico e l'ho validato con i vostri schemi. L'ho inserito regolarmente in un pdf ed ho firmato il pdf, ma quando lo sottopongo alla validazione offline ottengo degli errori sul CDA che di fatto non esistono, altrimenti il vostro xsd me li avrebbe segnalati. Quale può essere il problema? Allego di seguito il messaggio ricevuto.
Grazie.
{
  "traceID": "6dd29d759e8b2031",
  "spanID": "6dd29d759e8b2031",
  "type": "/msg/syntax",
  "title": "Errore di sintassi.",
  "detail": "ERROR: -1,-1 cvc-minLength-valid: Value '' with length = '0' is not facet-valid with respect to minLength '1' for type 'st'.,ERROR: -1,-1 cvc-attribute.3: The value '' of attribute 'assigningAuthorityName' on element 'typeId' is not valid with respect to its type, 'st'.,ERROR: -1,-1 cvc-type.2: The type definition cannot be abstract for element value.,ERROR: -1,-1 cvc-complex-type.2.1: Element 'value' must have no character or element information item [children], because the type's content type is empty.",
  "status": 400,
  "instance": "/validation/error",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.160114.4.110.f26c4ddecc741bcf8b4c1dc004b0c7644c046943e2603479b4fe94ff1fba9614.a4704ee0e0^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "warning": null
}

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Potrebbe gentilmente allegare il pdf utilizzato per questa chiamata? 
Grazie

**Comment by infoserviceonline** [comment]
Certamente, eccolo
[testsigned.pdf](https://github.com/ministero-salute/it-fse-support/files/14696583/testsigned.pdf)

**Comment by vigliottim** [comment]
Buongiorno, le chiediamo gentilmente di dirci quale tool sta usando per effettuare la validazione. 
Dai nostri test risulta che il pdf allegato dà un errore generico causato dall'elemento duplicato 
`<id root="2.16.840.1.113883.9.9.9.9.9.9" extension="NULL" assigningAuthorityName= "INFOSERVICE"/>` 
nella struttura del CDA:

<img width="465" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/26bd0213-321e-418c-885d-d59873deb2d7">
 
In alternativa, le suggeriamo di utilizzare un API client come Postman per effettuare le chiamate. 
Grazie.

**Comment by infoserviceonline** [comment]
Notepad++, Visual Studio con codice proprietario, che usiamo da anni, ed Altova. Tutti non segnalano niente di anomalo, abbinati agli schemi scaricati dal vostro sito. A questo punto forse è meglio utilizzare le chiamate direttamente nell'ambiente di test, appena possibile, come suggerito.Inviato dal mio Galaxy
-------- Messaggio originale --------Da: Michela Vigliotti ***@***.***> Data: 21/03/24  15:58  (GMT+01:00) A: ministero-salute/it-fse-support ***@***.***> Cc: Paco ***@***.***>, Author ***@***.***> Oggetto: Re: [ministero-salute/it-fse-support] Errore di validazione CDA
  (Issue #682) 
Buongiorno, le chiediamo gentilmente di dirci quale tool sta usando per effettuare la validazione.
Dai nostri test risulta che il pdf allegato dà un errore generico causato dall'elemento duplicato
<id root="2.16.840.1.113883.9.9.9.9.9.9" extension="NULL" assigningAuthorityName= "INFOSERVICE"/>
nella struttura del CDA:
image.png (view on web)
In alternativa, le suggeriamo di utilizzare un API client come Postman per effettuare le chiamate.
Grazie.

**Comment by vigliottim** [comment]
Chiudiamo il presente ticket e la invitiamo a riaprirlo nel caso in cui abbia bisogno di ulteriore supporto. Grazie.
