### ISSUE TITLE
Mancata validazione da Regione Lombardia

### ISSUE THREAD

**Issue by EugenioGuagliardi** [ministero-salute/it-fse-support#683]
Stiamo testando il metodo di Validazione verso il gateway (usando i nuovi certificati indicati per il CP FSE 2.0) e volevo chiedere un supporto perchè in tutti i nostri tentativi abbiamo questo errore:

[2024 - 03 - 22 09](tel:2024 - 03 - 22 09): 13: 41.832 INFO[fsegtw.fsegtw, eb71cf8de2a2e1c9, eb71cf8de2a2e1c9]4154449-- - [sendMessageListenerContainer - 1]piClient$ApiClientHttpRequestInterceptor: Response Body: {
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "9b435cde-e81e-11ee-9223-005056ae7395"
}

nella chiamata:

2024-03-22 09:13:41.454 DEBUG [fsegtw.fsegtw,,] 4154449 --- [sendMessageListenerContainer-1] i.a.c.f.g.c.g.rest.FseGtwRestTemplate    : HTTP POST https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation

Lo stesso documento lo riuscivamo a validare in passato.
Potete darci  @indicazioni?

In allegato il file con Header e Body
[Header e Body.txt](https://github.com/ministero-salute/it-fse-support/files/14722684/Header.e.Body.txt)

**Comment by vigliottim** [comment]
Buon pomeriggio,
dall'analisi dei token risulta che il campo _"aud"_ è stato valorizzato come array, anziché come stringa: 
<img width="345" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/1a77bb6c-39cb-4618-acf9-caee2dd995ca">
Come descritto in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt), il suddetto campo va valorizzato come segue:
`"aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1"`
Le chiediamo di correggere l'errore segnalato e riprovare. 
Grazie.

**Comment by org035** [comment]
Buon pomeriggio, 
grazie per il riscontro.
Scriviamo dal team di sviluppo in merito a questa segnalazione. 

Le specifiche RFC 7519 https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3 indicano che comunicare questo valore all'interno di un array di un solo elemento è comunque valido. 
Noi, per generare il suddetto token, utilizziamo la libreria auth0 https://github.com/auth0/java-jwt, la quale è indicata come RFC compliant all'interno dell'elenco delle librerie java consigliate su https://jwt.io/libraries,  questo è stato confermato dagli sviluppatori della stessa libreria qui https://community.auth0.com/t/audience-value-in-returned-bearer-token-jwt-is-a-list/6418/2. 

Inoltre, il meccanismo di generazione dei due headers è stato preso da questa documentazione https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator che utilizza la stessa libreria adottata da noi.

Generando, quindi, un token conforme allo standard ci chiediamo come mai questo venga rigettato dal gtw. 

Grazie ancora per il riscontro

**Comment by vigliottim** [comment]
Buonasera, dovreste far riferimento alla [documentazione ufficiale](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt) per il corretto popolamento dei campi contenuti nei JWT. 
Inoltre, se persistono errori relativi ai token, vi consigliamo di utilizzare il tool [jwt-generator](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator) per generarli.
Grazie.

**Comment by org035** [comment]
Buongiorno, in effetti il nostro codice è un riadattamento del tool [jwt-generator](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator), inserito come libreria all'interno dell'applicativo poiché la versione fornita è invece un tool.

Il token generato, con il valore "aud: ["https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1"] rispetta gli standard definiti dalla RFC quindi ci aspettiamo venga processato

**Comment by org035** [comment]
Abbiamo incluso nel nostro codice l'aggiornamento effettuato sul tool jwt-generator e ci siamo adeguati alla jdk 17.0.2, in questo modo abbiamo superato il problema. Grazie per il supporto

**Comment by vigliottim** [comment]
Grazie a lei per il feedback. 
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
