### ISSUE TITLE
Errore di autenticazione durante la validazione

### ISSUE THREAD

**Issue by michelebukovitz** [ministero-salute/it-fse-support#684]
Buongiorno,
sto provando a validare un referto di test per l'accreditamento nazionale. Da un po' ricevo continuamente il seguente errore:
RISPOSTA : 401 - Unauthorized
govway_id : 5498447b-e840-11ee-9223-005056ae7395
detail : Invalid token
type : https://govway.org/handling-errors/401/TokenAuthenticationFailed.html
title : TokenAuthenticationFailed
status : 401
C'è modo di capire quale sia il problema nel token?
Grazie.

**Comment by vigliottim** [comment]
Buon pomeriggio, 
dalle analisi effettuate sui token decodificati su [jwt.io](jwt.io), risulta che il campo _"x5c"_ non è un array, ma una stringa:
<img width="389" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/7e706be7-4019-43d9-a884-6c041f604a89">
Inoltre, non è presente nell'_header_ ma nel _payload_. 
Per maggiori informazioni può consultare la documentazione al link: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt
La preghiamo di correggere gli errori segnalati e riprovare.
Grazie.

**Comment by EugenioGuagliardi** [comment]
Grazie per la pronta risposta, riproveremo dopo la correzione.

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente issue viene chiusa.
Potrà riaprila nel caso in cui avesse bisogno di ulteriore supporto.
Grazie.
