### ISSUE TITLE
Certificazione nuovo software 

### ISSUE THREAD

**Issue by simeds** [ministero-salute/it-fse-support#685]
Buongiorno,
dopo aver ricevuto l'accreditamento per il nostro software SiClamm, stiamo procedendo per l'accreditamento di un altro dei nostri prodotti: SiCenter.

Abbiamo eseguito la registrazione al DTD e abbiamo fatto i test e creato la pull request, ma ci è stato comunicato che i test sono falliti per
```
"error" : "WRONG_CLAIMS_ON_LOG",
"description" : "Claims(appId,appVersion,appVendor) della chiamata al gtw differenti da quelli dichiarati nel data.json"
```

Eppure nel data.json abbiamo questi valori:

```
        "subject_application_id": "sicenter",
        "subject_application_vendor": "simeds",
        "subject_application_version": "1",
```

Come indicato nella richiesta a DTD

[Contributionce946e04-8eb4-456c-882a-5939e4c8d1af.pdf](https://github.com/ministero-salute/it-fse-support/files/14730996/Contributionce946e04-8eb4-456c-882a-5939e4c8d1af.pdf)

Cosa stiamo sbagliando?

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente issue viene chiusa. Si può procedere con la riapertura nel caso avesse bisogno di ulteriore supporto.
