### ISSUE TITLE
CDA RAD: OID dello spazio di identificazione usato nell’Azienza che custodisce il PACS nel quale sono contenute le immagini

### ISSUE THREAD

**Issue by Saxos-Simone** [ministero-salute/it-fse-support#686]
Buongiorno, nel documento del _CDA_ di _RAD_ ([HL7IT-IG_CDA2_RAD-v1.1-S.pdf](http://www.hl7italia.it/sites/default/files/Hl7/SuperUser/docs/pubblicati/IG-CDA2-RAD/1.1/HL7IT-IG_CDA2_RAD-v1.1-S.pdf)) viene detto che nell'elemento **_<patientRole>_**, è necessario indicare 2 **_<id>_**, il primo riportante il codice fiscale del paziente, mentre il secondo riportante il numero di identificazione dell’assistito nel sistema _PACS_ in cui sono custodite le immagini associate al referto, in quest'ultimo è necessario indicare nell'attributo root l'_OID_ dello spazio di identificazione usato nell’Azienza che custodisce il _PACS_ nel quale sono contenute le immagini, dove è possibile consultare la lista di questi _OID_?

**Comment by vigliottim** [comment]
Buongiorno, sulle linee guida fornite da HL7 il valore non è vincolato ma nel campo va riportato l'OID dello spazio di identificazione usato nell’Azienza che custodisce il PACS nel quale sono contenute le immagini.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto riscontri, procediamo alla chiusura del presente ticket. 
Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto.
Grazie.
