### ISSUE TITLE
Problemi pubblicazione con interazione con INI 

### ISSUE THREAD

**Issue by xenergy33** [ministero-salute/it-fse-support#687]
Buongiorno,
in Emilia-Romagna stiamo provando ad effettuare delle pubblicazioni verso il GTW per un nostro assistito, ma non riceviamo i metadati relativi all'indicizzazione da INI. 
Utilizzando il servizio di verifica degli stati abbiamo questa risposta:

{
    "traceID": "8eadf3526a1631b3",
    "spanID": "ab425a7ae3324529",
    "transactionData": [{
            "eventType": "VALIDATION",
            "eventDate": "2024-03-25T10:12:12.515+00:00",
            "eventStatus": "SUCCESS",
            "subject": "MDCBGN54A01A944D^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "080",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.198bb9a407c32b41e3cb70613df101cba20053329268b403cd03a9ab3286a91f.0a9744787e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "c56d685e299e703b",
            "issuer": "integrity:S1#080#EMILIAROMAGNA",
            "expiringDate": "2025-03-25T10:12:12.525+00:00"
        }, {
            "eventType": "PUBLICATION",
            "eventDate": "2024-03-25T10:12:45.721+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.80.4.4^105LAB17113615296895IVA3E",
            "subject": "MDCBGN54A01A944D^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "ERP",
            "organizzazione": "080",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.198bb9a407c32b41e3cb70613df101cba20053329268b403cd03a9ab3286a91f.0a9744787e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "81788b333e1343cd",
            "issuer": "integrity:S1#080#EMILIAROMAGNA",
            "expiringDate": "2025-03-25T10:12:45.731+00:00"
        }, {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-03-25T10:12:48.092+00:00",
            "eventStatus": "SUCCESS",
            "message": " SEVERITY : urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning ERROR_CODE : R220",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.198bb9a407c32b41e3cb70613df101cba20053329268b403cd03a9ab3286a91f.0a9744787e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-03-25T10:12:48.219+00:00"
        }, {
            "eventType": "SEND_TO_EDS",
            "eventDate": "2024-03-25T10:12:48.297+00:00",
            "eventStatus": "SUCCESS",
            "message": "{\"esito\":true}",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.198bb9a407c32b41e3cb70613df101cba20053329268b403cd03a9ab3286a91f.0a9744787e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-03-25T10:12:48.530+00:00"
        }
    ]
}

nel SEND TO INI riscontriamo l'anomalia che ci fa pensare che INI si comporti ancora con la logica precedente all'introduzione del GTW (Warning ERROR_CODE : R220).

Vi chiediamo di verificare.

Grazie.
Raffaele

**Comment by IStacchiotti** [comment]
Buongiorno, il warning in questione (errore non bloccante) è previsto nell'ultima versione del [documento](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20interoperabilit%C3%A0/FrameworkEDatasetDeiServiziBase_v2-5_20231212_0.pdf) con le specifiche di interoperabilità e indica quanto indicato di seguito: 
![image](https://github.com/ministero-salute/it-fse-support/assets/122798799/777fcf6b-ee19-4977-a052-caa0b39bac1a)
Rimaniamo a disposizione per ulteriori richieste  di chiarimento.

**Comment by xenergy33** [comment]
Certo, l'errore non è bloccante, ma INI non mi invia i dati per l'indicizzazione. Attenzione le verifiche che stiamo effettuando non sono relative al percorso così detto "transitorio", ma a come dovrebbe funzionare il tutto a regime, vedi Crash Program.

**Comment by IStacchiotti** [comment]
Buonasera, può confermarci che quando scrive
> INI non mi invia i dati per l'indicizzazione. 

si riferisce alla "notifica avvenuta comunicazione metadati" che INI manda alla RDE (rappresentata nel Capitolo 6, pg.183 delle [Specifiche di Interoperabilità](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20interoperabilit%C3%A0/FrameworkEDatasetDeiServiziBase_v2-5_20231212_0.pdf), nel sequence contenuto in Figura 42 – Scenario 1: Indicizzazione nuovo documento)?

![image](https://github.com/ministero-salute/it-fse-support/assets/122798799/c5efaf72-a1c2-4970-928b-7e0f01069d31)
 
Grazie mille

**Comment by xenergy33** [comment]
Si, confermo il caso d'uso è questo.
Buona serata.
Raffaele

**Comment by pFonziSogei** [comment]
La segnalazione dovrebbe essere risolta, chiedo gentilmente riscontro per quanto riguarda la ricezione dei metadati

**Comment by pFonziSogei** [comment]
Come condiviso durante l'incontro con le regioni, la notifica è stata sbloccata e vi chiediamo di effettuare un altro test

**Comment by daniele-gubellini** [comment]
Riceviamo la notifica, ho aperto una nuova issue #728 ..Direi che questa issue si puo' chiudere

**Comment by vigliottim** [comment]
Grazie per il suo gentile feedback. 
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per ulteriori richieste di supporto.
