### ISSUE TITLE
AuthorizationContentDeny

### ISSUE THREAD

**Issue by ciampysara** [ministero-salute/it-fse-support#688]
Buongiorno stiamo provando a inviare una richiesta di validazione e creazione ma ci ritorna il seguente errore

{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"96343846-ea97-11ee-93a7-0050

**Comment by LucaRogledi** [comment]
Buongiorno,
Potrebbe gentilmente riportare la response completa ricevuta? 
Grazie

**Comment by ciampysara** [comment]
Questo è l'errore che mi da ora

HTTP/1.1 502 Bad Gateway
X-Backside-Transport: FAIL FAIL
Connection: Keep-Alive
Transfer-Encoding: chunked
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
Server: GovWay-SOGEI
Pragma: no-cache
GovWay-Message-ID: b159a065-0d61-498c-af9e-4d73c86017cd
GovWay-Transaction-ErrorType: InvalidResponse
GovWay-Transaction-ID: e6e09332-ea98-11ee-9223-005056ae7395
Date: Mon, 25 Mar 2024 11:38:13 GMT
Vary: *
X-Content-Type-Options: nosniff
Content-Type: application/problem+json
X-Global-Transaction-ID: 3f7e3e2d6601622516d73fed

{"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"e6e09332-ea98-11ee-9223-005056ae7395"}

**Comment by ciampysara** [comment]
curl -i \
  --cert-type PEM \
  --cert XXXXX
  -X 'POST' \
  'https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validate-and-create'\
  -H 'accept: application/json' \
  -H 'Authorization: Bearer XXX' \
  -H 'FSE-JWT-Signature: XXX' \
  -H 'Content-Type: multipart/form-data' \
  -F 'requestBody={
  "healthDataFormat": "CDA",
  "mode": "ATTACHMENT",
  "tipologiaStruttura": "Ospedale",
  "attiCliniciRegoleAccesso": [
  "P99"
  ],
  "identificativoDoc": "2.16.840.1.113883.2.9.2.90.4.4^09090101.RSA.901.000002",
   "identificativoRep": "2.16.840.1.113883.2.9.2.90.4.5.901",
  "tipoDocumentoLivAlto": "REF",
  "assettoOrganizzativo": "AD_PSC001",
  "dataInizioPrestazione": "20240109103000",
  "dataFinePrestazione": "20240109103000",
  "tipoAttivitaClinica": "ERP",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.2.909587",
  "priorita": false,
  "administrativeRequest": ["SSN"]
}' \
 -F 'file=@RSA_TEST_1_signed.pdf;type=application/pdf'

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate risultano presenti i seguenti errori nella chiamata:

- _FSE-JWT-Signature token_: nel campo `"resource_hl7_type": "('''34105-7^^2.16.840.1.113883.6.1''')"` sono presenti tre apici anziché un singolo apice come mostrato di seguito: `"resource_hl7_type": "('34105-7^^2.16.840.1.113883.6.1')"`

- _FSE-JWT-Signature token_: `"locality":"jwt-location"` deve essere valorizzato con l'identificativo della struttura utente come indicato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt).

- Nella Request Body non è presente `Content-Type: application/json`, come previsto in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway).

- Il CDA2 non è stato iniettato nel PDF.

La preghiamo di correggere gli errori riportati e riprovare. Grazie.

**Comment by ciampysara** [comment]
tutto ok Grazie
