### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by michelebukovitz** [ministero-salute/it-fse-support#689]
Buongiorno, 
sto ricevendo la seguente risposta dal gateway di test.

RISPOSTA : 502 - Bad Gateway
TraceID : null
WorkflowInstanceID : null
SpanID : Warning : null
govway_id : 260e8c21-ea98-11ee-93a7-005056ae54fa
detail : Invalid response received from the API Implementation
type : https://govway.org/handling-errors/502/InvalidResponse.html
title : InvalidResponse
status : 502
Questo dopo aver corretto il content-type relativo al PDF con CDA.

**Comment by vigliottim** [comment]
> Grazie ora funziona. Per un problema di estrazione cda posso scrivere qui?

Grazie per il suo gentile feedback. Abbiamo riaperto l'issue, così da darle supporto in questo thread per la sua nuova richiesta.

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente issue viene chiusa.
Potrà riaprila nel caso in cui avesse bisogno di ulteriore supporto.
Grazie.
