### ISSUE TITLE
Errore validazione CDA VPS

### ISSUE THREAD

**Issue by alessandropassamonti** [ministero-salute/it-fse-support#69]
Buongiorno.
Tentando la validazione di un CDA di VPS ottengo questo errore:
`[ERRORE-b171| Sezione Interventi Prestazioni Consulenze e Richieste: l'elemento entry/act/code DEVE essere valorizzato con gli attributi @code='76645-1' e @codeSystem='2.16.840.1.113883.6.1'.],[ERRORE-b194| Sezione Parametri Vitali: l'elemento entry/organizer/component/observation/code DEVE essere valorizzato con gli attributi @code='86678-0' e @codeSystem='2.16.840.1.113883.6.1']`

utilizzando altri codici non passa la validazione dello schematron. 
é necessario mettere solo i codici indicati negli esempi per passare la validazione? solo per il test?
Grazie

**Comment by IStacchiotti** [comment]
Grazie della segnalazione, in entrambi i casi è possibile inserire dei codici diversi da quelli riportati nell'esempio e lo schematron non dovrebbe restituire questo errore. Pertanto verrà modificato il controllo. Le daremo evidenza appena sarà caricata la nuova versione.

**Comment by Ser-ena** [comment]
Buonasera, sono stati aggiornati i controlli, potrebbe cortesemente effettuare un nuovo test.

**Comment by alessandropassamonti** [comment]
Buonasera. 
Test positivo.
Grazie
