### ISSUE TITLE
Problama replace

### ISSUE THREAD

**Issue by nspazzoli** [ministero-salute/it-fse-support#690]
Salve,

ricevo un errore usando il servizio di replace.
 
Richiesta:
PUT /govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.80.4.4%5E105LAB1711374627357GLBQFA HTTP/1.1

  HTTP 500, {
     "traceID": "4fab3a83a761e0ec",
     "spanID": "4fab3a83a761e0ec",
     "type": "/msg/ini-error",
     "title": "Ini error.",
     "detail": "{\"traceID\":\"00000000000000004fab3a83a761e0ec\",\"spanID\":\"85482639492a4c1a\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"Errore riscontrato su INI\",\"instance\":\"error/generic\"}",
     "status": 500,
     "instance": "/msg/service-error/ini"
 }
 
Il documento che sto tentando di sostituire era stato invece correttamente pubblicato.
Sapreste darmi qualche indicazione?

Grazie

**Comment by EugenioGuagliardi** [comment]
Anche da Regione Lombardia abbiamo lo stesso problema sulla replace, la delete ed aggiornamento metadati

Inserisco la risposta ottenuta per la Delete https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/0eeff554-edd9-11ee-a9d8-0242a89a8ac7`:

dataOra=2024-03-29 15:31:53:114|server=null|ID_DC=136f7ccf-4c1f-40ec-bbc6-dce0c80f3e4c|ID_COOP=null|elapsed=1053|DIR=CLI|OUT=/govway/rest/in/FSE/gateway/v1/documents/0eeff554-edd9-11ee-a9d8-0242a89a8ac7#null#{"traceID":"b41ac8a099ef9483","spanID":"b41ac8a099ef9483","type":"/msg/ini-error","title":"Ini error.","detail":"{\"traceID\":\"0000000000000000b41ac8a099ef9483\",\"spanID\":\"c52a8c5caf732113\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"Errore riscontrato su INI\",\"instance\":\"error/generic\"}","status":500,"instance":"/msg/service-error/ini"}


Inserisco la chiamata per l'aggiornamento

```
2024-03-29 12:38:04.954 DEBUG [fsegtw.fsegtw,,] 1750423 --- [sendMessageListenerContainer-3] i.a.c.f.g.c.g.rest.FseGtwRestTemplate    : HTTP PUT https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/fcf2ad08-ece6-11ee-a9d8-0242a89a8ac7/metadata
2024-03-29 12:38:04.954 DEBUG [fsegtw.fsegtw,,] 1750423 --- [sendMessageListenerContainer-3] i.a.c.f.g.c.g.rest.FseGtwRestTemplate    : Accept=[application/json, application/*+json]
2024-03-29 12:38:04.955 DEBUG [fsegtw.fsegtw,,] 1750423 --- [sendMessageListenerContainer-3] i.a.c.f.g.c.g.rest.FseGtwRestTemplate    : Writing [class PublicationMetadataReqDTO {
    tipologiaStruttura: Territorio
    attiCliniciRegoleAccesso: [P99]
    tipoDocumentoLivAlto: REF
    assettoOrganizzativo: AD_PSC100
    dataInizioPrestazione: 20240329123804
    dataFinePrestazione: 20240329123804
    conservazioneANorma: S
    tipoAttivitaClinica: ERP
    identificativoSottomissione: 2.16.840.1.113883.2.9.2.30.4.3.1711712284748
    descriptions: []
    administrativeRequest: []
}] as "application/json"
```


Risposta aggiornamento:

`2024-03-29 12:38:07.017  INFO [fsegtw.fsegtw,0378b0362d6fa1a6,0378b0362d6fa1a6] 1750423 --- [sendMessageListenerContainer-3] APP                                      : |dataOra=2024-03-29 12:38:07:013|server=null|ID_DC=80d9036f-be78-45fe-b8ee-38449fa12394|ID_COOP=null|elapsed=2058|DIR=CLI|OUT=/govway/rest/in/FSE/gateway/v1/documents/fcf2ad08-ece6-11ee-a9d8-0242a89a8ac7/metadata#null#{"traceID":"0378b0362d6fa1a6","spanID":"0378b0362d6fa1a6","type":"/msg/ini-error","title":"Ini error.","detail":"{\"traceID\":\"00000000000000000378b0362d6fa1a6\",\"spanID\":\"112d3b2d7add13c3\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"Index: 0, Size: 0\",\"instance\":\"error/generic\"}","status":500,"instance":"/msg/service-error/ini"}`



Grazie

**Comment by pFonziSogei** [comment]
@nspazzoli  sarebbe possibile eseguire una prova ulteriore?

**Comment by pFonziSogei** [comment]
@EugenioGuagliardi  da una prima analisi sembrerebbe esserci una risposta Failure da Regione Lombardia

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
	<soap:Header>
		<Action xmlns="http://www.w3.org/2005/08/addressing">urn:ihe:iti:xds-b:2007:DocumentRegistry_PortType:DocumentRegistry_RegistryStoredQueryResponse</Action>
		<MessageID xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:50c5385e-66ff-4ca2-8d9f-a9bdbac46780</MessageID>
		<To xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</To>
		<RelatesTo xmlns="http://www.w3.org/2005/08/addressing">827bbfe4-52a8-4e9e-b9de-6800b202e58e</RelatesTo>
	</soap:Header>
	<soap:Body>
		<ns3:AdhocQueryResponse startIndex="0" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns="urn:hl7-org:v3" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns4="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0">
			<ns4:RegistryErrorList>
				<ns4:RegistryError codeContext=": " errorCode="EA0001" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"/>
			</ns4:RegistryErrorList>
			<ns2:RegistryObjectList/>
		</ns3:AdhocQueryResponse>
	</soap:Body>
</soap:Envelope>

**Comment by EugenioGuagliardi** [comment]
Buongiorno, abbiamo rifatto il test ed ora la risposta di Regione Lombardia è corretta ma il GATEWAY risponde con errore http 404.
Apriremo una dioversa Issue con i dettagli

**Comment by vigliottim** [comment]
Buongiorno, procediamo alla chiusura del presente ticket in seguito all'apertura della nuova issue [#712](https://github.com/ministero-salute/it-fse-support/issues/712).

**Comment by IStacchiotti** [comment]
Buonasera, dal momento che l'errore riscontrato dalla Lombardia, ora superato, era lo stesso della Regione Emilia-Romagna che ha aperto il ticket, abbiamo provveduto alla chiusura del presente. Chiediamo cortesemente alla Regione Emilia-Romagna di riaprire o chiedere l'apertura del presente nel caso in cui l'errore persista. Grazie mille
