### ISSUE TITLE
Errore su schema

### ISSUE THREAD

**Issue by michelebukovitz** [ministero-salute/it-fse-support#691]
Buongiorno, 
sto ricevendo l'errore  Schema with version [POCD_HD000040] not found on database.
TraceID : 61d9e0e554cc8e06
WorkflowInstanceID : 0.1.2.3.4.9ae2bdd7beedc2e766c6b76585530e16925115707dc7a06ab5ee4aa2776b2c7b.fbcdaaeaeb^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

Dove posso trovare un riferimento per il valore in questione, se dovesse essere errato? 
Grazie.

**Comment by LucaRogledi** [comment]
Buonasera,
I controlli presenti sugli integration kit fanno riferimento all’ultima versione del POCD, ovvero @extension=POCD_MT000040UV02. I CDA2 valorizzati con la precedente versione restituiranno un esito negativo.
A seguire i link ufficiali che riporta l’ultima versione del POCD:
[GitHub - HL7/CDA-core-2.1](https://github.com/HL7/cda-core-2.1)
Restiamo a disposizione per eventuali chiairimenti.
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno,
Potrebbe gentilmente riportare la risposta completa ricevuta dalla nuova chiamata, riportando anche i dettagli compreso govwayId/traceId ? 
Grazie

**Comment by LucaRogledi** [comment]
Buonasera,
Dalle analisi effettuate sul cda iniettato nel pdf ricevuto dal sistema, risulta che il campo `typeId/@extension` non è valorizzato correttamente, quindi non viene riconosciuto.

As-is:
`<typeId extension="[POCD_MT000040UV02]" root="2.16.840.1.113883.1.3"/>`

To-be:
`<typeId extension="POCD_MT000040UV02" root="2.16.840.1.113883.1.3"/>`

La invitiamo gentilmente a correggere e riprovare.
Grazie

**Comment by vigliottim** [comment]
Buonasera,
di seguito trova le risposte alle sue domande:

> 1 - Sto simulando un RSA e mi chiede il codice di un RAD 

L'attributo dell'elemento _code_ è valorizzato correttamente con il codice corrispondente alla tipologia documentale RAD: `code="11488-4"`

<img width="462" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/0d4258b5-4c1a-4dd5-83f9-14ddb9ff365a">

Tuttavia, l'elemento _templateId_ non ha l'attributo _root_ valorizzato coerentemente con la tipologia documentale RSA ma con la tipologia documentale RAD:
<img width="398" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/1deef749-36c8-467c-bbb0-2de14b965125">
Pertanto, dovrebbe effettuare la seguente correzione:
<templateId **root="2.16.840.1.113883.2.9.10.1.9.1"** extension="1.1" assigningAuthorityName="HL7 Italia"/>
Per maggiori informazioni può consultare la guida HL7 Italia per RSA: [HL7IT-IG_CDA2_RSA-v1.1-S.pdf](http://www.hl7italia.it/sites/default/files/Hl7/SuperUser/docs/pubblicati/IG-CDA2-RSA/1.1/HL7IT-IG_CDA2_RSA-v1.1-S.pdf )

> 2 - Se metto il solo codice fiscale ottengo questo errore: detail : [ERRORE-5| L'elemento ClinicalDocument/code deve essere valorizzato con l'attributo @code='68604-8' e il @codesystem='2.16.840.1.113883.6.1'],[ERRORE-10a| L'elemento ClinicalDocument/recordTarget/patientRole/id deve avere l'attributo @root valorizzato tramite uno dei seguenti identificatori Nazionanli: CF 2.16.840.1.113883.2.9.4.3.2 (Nel caso di Cittadino Italiano o straniero residente in Italia, patientRole DEVE riportare un elemento di tipo id contenente il Codice Fiscale e un ulteriore elemento id OBBLIGATORIO contenente il numero di identificazione dell’assistito nel sistema PACS (@nullFlavour è ammesso ove l’informazione non sia disponibile).) TEAM 2.16.840.1.113883.2.9.4.3.7 e 2.16.840.1.113883.2.9.4.3.3 ENI 2.16.840.1.113883.2.9.4.3.18 STP 2.16.840.1.113883.2.9.4.3.17 oppure un identificativo regionale ANA 2.16.840.1.113883.2.9.4.3.15 Oppure tramite gli identificatori regionali generati per rappresentare l'id del paziente. ] Dalla documentazione mi risultava che per un cittadino residente fosse sufficiente il codice fiscale. 

Tale errore, che riporta le indicazioni da seguire nel caso in cui si abbia come paziente un soggetto assicurato da istituzioni estere (TEAM), non comparirà se corregge quanto riportato nel punto precedente.

Gli altri errori si riferiscono al fatto che:
- deve essere presente almeno un elemento _telecom_ all'interno di _author/assignedAuthor_
- deve essere presente un elemento _inFulfillmentOf_ all'interno di _ClinicalDocument_

Sperando le possa essere d'aiuto, le inviamo il link contenente un esempio di CDA2 per RSA:
https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/RSA.xml

Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Buongiorno, può far riferimento all'esempio presente al link https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/RSA.xml per i valori da riportare nell'elemento _inFullfillmentOf_ nel caso in cui non è presente una ricetta:
<img width="653" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/82c48e56-1831-4056-9fc7-8a0a8434c2ee">

**Comment by vigliottim** [comment]
Può riportare esattamente il testo dell'esempio: extension="[NRE]"
Poiché l'elemento è obbligatorio ai fini dell'accreditamento, sarà necessario mettere un placeholder.

**Comment by vigliottim** [comment]
L'elemento _ClinicalDocument/inFulfillmentOf_ è obbligatorio nel caso di CDA di tipo RAD sia nella guida HL7 Italia che ai fini dell'accreditamento, come riportato nel file excel [CDA2_Referto_di_Radiologia_OK](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/1-Referto%20di%20Radiologia/CDA2_Referto_di_Radiologia_OK.xlsx):
<img width="760" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/cb8cf950-1566-43c8-957b-d481057daabc">
<img width="576" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/cca70aea-b4fc-4ec9-b894-37759ebd3a5d">

Poiché in origine, a causa dell'errata valorizzazione di _templateId/root_, il suo CDA veniva letto come RAD ha ricevuto l'errore: 
`[ERRORE-38| In ClinicalDocuemnt DEVE essere presente almeno un elemento 'inFulfillmentOf'. ]`

Tale elemento non risulta obbligatorio per CDA di tipo RSA, né ai fini dell'accreditamento, né nella guida HL7 Italia.
<img width="565" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/bb363f92-8156-4962-9496-4ee9d97a22e8">

Grazie.

**Comment by vigliottim** [comment]
> Grazie mille. Un'ultima domanda: in fase di pubblicazione ricevo i seguenti errori:
body.requestBody: Field 'assettoOrganizzativo' is required. (code: 1026)
From: body.requestBody.<#/components/schemas/PublicationCreationReqDTO>.
body.requestBody: Field 'identificativoDoc' is required. (code: 1026)
From: body.requestBody.<#/components/schemas/PublicationCreationReqDTO>.
body.requestBody: Field 'identificativoRep' is required. (code: 1026)
From: body.requestBody.<#/components/schemas/PublicationCreationReqDTO>.
body.requestBody: Field 'identificativoSottomissione' is required. (code: 1026)
From: body.requestBody.<#/components/schemas/PublicationCreationReqDTO>.
body.requestBody: Field 'tipoAttivitaClinica' is required. (code: 1026)
From: body.requestBody.<#/components/schemas/PublicationCreationReqDTO>.
body.requestBody: Field 'tipoDocumentoLivAlto' is required. (code: 1026)
From: body.requestBody.<#/components/schemas/PublicationCreationReqDTO>.
body.requestBody: Field 'tipologiaStruttura' is required. (code: 1026)
From: body.requestBody.<#/components/schemas/PublicationCreationReqDTO>.
Sono relativi al CDA o alla request? Inoltre, dopo la validazione devo riportare il workflowID per la pubblicazione?

Buonasera, come descritto in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#41-request), nella request body del servizio di pubblicazione è necessario inserire tutti i parametri indicati nella tabella 10 per i quali REQUIRED = true.
Il workflowistanceid non rientra tra quelli obbligatori:
<img width="558" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/a101f2a0-c558-4cca-a34a-70e6781ba498">
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Grazie a lei. Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
