### ISSUE TITLE
errore in cancellazione documento

### ISSUE THREAD

**Issue by nspazzoli** [ministero-salute/it-fse-support#692]
Salve,

provando a cancellare un documento correttamente ricevuto (in precedenza), ottengo il seguente errore 

{
		"traceID": "752c8468c96a5f4b",
		"spanID": "752c8468c96a5f4b",
		"type": "/msg/ini-error",
		"title": "Ini error.",
		"detail": "{\"traceID\":\"0000000000000000752c8468c96a5f4b\",\"spanID\":\"92426c5090ce3260\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"Client received SOAP Fault from server: Patient consent cannot be false in case of purpose of use TREATMENT Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}",
		"status": 500,
		"instance": "/msg/service-error/ini"
	}

Potreste darmi gentilmente qualche suggerimento?
Grazie

**Comment by LucaRogledi** [comment]
Buonasera,
Come riportato sul documento delle [specifiche di interoperabilità](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20interoperabilit%C3%A0/FrameworkEDatasetDeiServiziBase_v2-5_20231212_0.pdf) l'errore riportato indica che in caso il file data.json utilizzato per la generazione dei token contenga "purpose_of_use" valorizzato con "TREATMENT", non è possibile valorizzare "patient_consent" con `false`. 

![image](https://github.com/ministero-salute/it-fse-support/assets/139234602/7fce342c-d2c5-47ae-81e9-b39582276c48)

La invitiamo a popolare il campo "patient_consent" con `true` e riprovare. 
Rimaniamo a disposizione in caso di eventuali chiarimenti.
Grazie

**Comment by nspazzoli** [comment]
Buongiorno,

seguento le indicazioni sulla compilazione dei JWT https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway

![immagine](https://github.com/ministero-salute/it-fse-support/assets/19858511/f1bb448c-6d14-4757-b53d-a6b66c798439)

In pubblicazione ho usato "purpose_of_use": "TREATMENT", "patient_consent": true;
Mentre in cancellazione "purpose_of_use": "UPDATE", senza indicare il patient_consent.

Ed è la cancellazione che da errore.
Grazie

**Comment by vigliottim** [comment]
Buonasera, 
la informiamo che è stato rilasciato un aggiornamento: il campo _patient_consent_ è ora obbligatorio anche in cancellazione.
Le chiediamo gentilmente di riprovare inserendo il campo _patient_consent_ opportunamente valorizzato.
Rimaniamo a disposizione qualora il problema si ripresentasse. Grazie.

**Comment by daniele-gubellini** [comment]
Buonasera, aggiungendo il "patient_consent" la richiesta viene accettata. 

Riceviamo da INI la prima richiesta di query "GET" ([RICHIESTA_METADATI_GTW_CANCELLAZIONE.txt](https://github.com/ministero-salute/it-fse-support/files/14792308/RICHIESTA_METADATI_GTW_CANCELLAZIONE.txt)) necessaria ad ottenere l'UUID del documento.
Faccio due segnalazioni:

1. Per quale motivo viene fatta una query di tipo _LeafClass_ e non una _ObjectRef_ ?
2. Il parametro di query è giustamente l'identificativo del documento ('2.16.840.1.113883.2.9.2.80.4.4^105LAB17116205705191KLYET'), tuttavia è stato inserito in uno slot _$XDSDocumentEntryEntryUUID_ invece che _$XDSDocumentEntryUniqueId_

**Comment by pFonziSogei** [comment]
Provo a rispondere per punti:

1 è corretto utilizzare ObjectRef, semplicemente avevamo fatto una sola config per tutti i servizi, correggiamo anche se non inficia i vostri test
2 possiamo avere il traceId?

**Comment by pFonziSogei** [comment]
Rilascio delle modifiche effettuate, potreste fare un nuovo test?

**Comment by daniele-gubellini** [comment]
Buongiorno, ora la richiesta di INI mi sembra corretta:  query di tipo ObjectRef e il codice del documento nello slot XDSDocumentEntryUniqueId

**Comment by LucaRogledi** [comment]
Ringraziamo per il gentile riscontro e procediamo alla chiusura della presente come risolta. 
Rimaniamo a disposizione per altre richieste di supporto.
Grazie
