### ISSUE TITLE
info produzione

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#693]
Buongiorno, nel canale slack un utente parla di anomalie in fase di "pubblicazione in produzione".
Il sistema è già attivo per gli invii effettivi? Ero fermo alla sola validazione (in test).

Per i clienti in Sicilia che mandano con FSE 1.0 - 2.4.1 (url ComunicazioneMetadati) viene indicata la terna del sw accreditato.
E' sufficiente questo o si deve fare dell'altro ?

**Comment by IStacchiotti** [comment]
Buongiorno @ds-tommaso, abbiamo appena risposto su Slack: presumiamo che l'utente stesse facendo riferimento all'architettura digitale 1.0 del fascicolo. Le confermiamo infatti che al momento l'ambiente di produzione non è ancora disponibile, ma è disponibile un ambiente di test che espone un set di servizi, compresa la pubblicazione, come indicato in documentazione a questo [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway). Per quanto riguarda l'accreditamento, questo è aperto al momento limitatamente al solo servizio di validazione. 
Le segnaliamo infine che se necessita di supporto tecnico relativamente al fascicolo 1.0, può inoltrare la sua richiesta di supporto alla seguente mail: [gestionets@sogei.it](mailto:gestionets@sogei.it)
Rimaniamo a disposizione per ulteriori chiarimenti, grazie

**Comment by ds-tommaso** [comment]
nono, non è necessario. chiudo l'issue, un saluto
