### ISSUE TITLE
TEST CASE Validazione - Possibili refusi in **VPS - Caso di Test 4.xml**

### ISSUE THREAD

**Issue by PRAFFO72** [ministero-salute/it-fse-support#694]
Salve, segnaliamo possibili refusi nel file [VPS - Caso di Test 4.xml ](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/Documenti%20XML%20Casi%20OK/2%20-%20Casi%20OK%20Verbale%20di%20Pronto%20Soccorso/VPS%20-%20Caso%20di%20Test%204.xml).

Tale file non rispetta i requisiti descritti nel [file excel](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/2-Verbale%20di%20Pronto%20Soccorso/CDA2_Verbale_Pronto_Soccorso_OK.xlsx) e dunque non passerebbe la procedura di accreditamento.

In particolare, l'attibuto ID alla riga [1047](https://github.com/ministero-salute/it-fse-accreditamento/blob/7f6f327e2d8bb134af40a3b4c7feef3fe71c06b7/Test%20Case/Validazione/Documenti%20XML%20Casi%20OK/2%20-%20Casi%20OK%20Verbale%20di%20Pronto%20Soccorso/VPS%20-%20Caso%20di%20Test%204.xml#L1047C52-L1047C81) è ""TERAPIA_FARMACOLOGICA_IN_PS"" invece di "Terapia_Farmacologica_in_Pronto_Soccorso"
e alla riga [357](https://github.com/ministero-salute/it-fse-accreditamento/blob/7f6f327e2d8bb134af40a3b4c7feef3fe71c06b7/Test%20Case/Validazione/Documenti%20XML%20Casi%20OK/2%20-%20Casi%20OK%20Verbale%20di%20Pronto%20Soccorso/VPS%20-%20Caso%20di%20Test%204.xml#L357) è "INQUADRAMENTO_CLINICO" invece di "Inquadramento_Clinico_Iniziale"
 
Quest ultimo refuso compare anche nel file [VPS - Caso di Test 3.xml ](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/Documenti%20XML%20Casi%20OK/2%20-%20Casi%20OK%20Verbale%20di%20Pronto%20Soccorso/VPS%20-%20Caso%20di%20Test%203.xml).

**Comment by vigliottim** [comment]
Buongiorno, grazie per la segnalazione. Verrà apportata una modifica sulla documentazione.

**Comment by LucaRogledi** [comment]
Buongiorno, la documentazione è stata aggiornata. Procediamo alla chiusura della presente issue e rimaniamo a disposizione per eventuale supporto. Grazie
