### ISSUE TITLE
Prima pull request

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#695]
Buongiorno, ho provato ad eseguire la mia prima pull request per validazione, ma non sono per niente sicuro di aver fatto tutto correttamente, nè capisco dove posso andare a verificare se quantomeno è andata a buon fine.
In prativa ho caricato nel mio repository il file data,json con i dati per il test da validare:
https://github.com/infoserviceonline/it-fse-accreditamento/tree/main/GATEWAY/A1%23111%23INFOSERVICEONLINE/INFOSERVICE/FLY/2.0
Dopo di che ho caricato il file pdf utilizzato per il test nella cartella FILES del suddetto repository.
Sono andato a vedere sul link: https://github.com/ministero-salute/it-fse-accreditamento/pulls?q=is%3Aopen+is%3Apr ma non vedo niente.
Ho sbagliato qualcosa? Come posso controllare?
Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno @infoserviceonline, 

La pull request in questione è stata aperta verso il main del vostro repository interno come da screen di seguito 
![image](https://github.com/ministero-salute/it-fse-support/assets/122798799/806a7410-7fd9-4444-aaee-3468e23cf1ee)
e non verso il main del repository di ministero della salute (https://github.com/ministero-salute/it-fse-accreditamento/tree/main). Per questo motivo la pull request non risulta visibile e non può essere analizzata.

Vi invitiamo ad effettuare una nuova pull request, avendo cura di selezionare come base repository il main di ministero della salute, come indicato nel seguente screenshot esemplificativo: 
![image](https://github.com/ministero-salute/it-fse-support/assets/122798799/47c8ab33-098c-493b-8576-279a5dc76a4c)


Rimaniamo a disposizione per ulteriore supporto.

**Comment by infoserviceonline** [comment]
Grazie per la celerità, io ci ho provato a fare quello che mi dite, ma sicuramente nel modo sbagliato.
Sono andato dove mi avete indicato: https://github.com/ministero-salute/it-fse-accreditamento/tree/main ma non mi dà la possibilità di inserire una pull request, ma sono inserire un file.
Ho provato allora ad andare dove ci sono le altre pool: https://github.com/ministero-salute/it-fse-accreditamento/pulls e provare ad inserire una nuova pool, ma mi trovo davanti ad una schermata che non comprendo:
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/637cc0d2-b873-4c3b-abad-395f47c49a35)
Come è evidente, non sono pratico di questa tipologia di procedure, abbiate pazienza.

**Comment by vigliottim** [comment]
Buon pomeriggio.
Per creare una nuova pull-request può cliccare sul bottone verde "New pull request": 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/868bcfd0-c86c-48f1-b78d-88cf64071835)

Nella pagina seguente dovrà selezionare i branch corretti (se non trova il suo, può cliccare su "compare across forks" e ricercarlo nel menu a tendina che apparirà in seguito) e cliccare "Create new pull request": 
 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/0619a697-c377-42fd-8d3f-904f82e3ecfe)
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/63768c66-a20f-41e2-a896-ab8d9530bf4d)

Successivamente apparirà "Able to merge" e potrà procedere cliccando "Create pull request":
<img width="934" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/d329a7db-03c8-4086-8b2c-17592963f6e1">

Le consigliamo di ripetere l'intero processo da capo, eliminando la PR creata erroneamente sul suo repository locale (visibile a questo link
[Pull requests · infoserviceonline/it-fse-accreditamento](https://github.com/infoserviceonline/it-fse-accreditamento/pulls)) ed eseguire nuovamente il commit per il caricamento delle cartelle e dei file di vostra pertinenza:
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/f5878bbd-e54d-46a8-a1e4-1cf4ed434466)
All'apertura di una nuova pull request potrà seguire le indicazioni riportate qui sopra.
Rimaniamo a sua disposizione.
Grazie.

**Comment by infoserviceonline** [comment]
Buongiorno, credo di aver fatto tutto correttamente ieri, ma ora non so cosa aspettarmi, una conferma, degli errori (quasi certamente) o altro, su quale canale ed in che tempi.
Grazie

**Comment by vigliottim** [comment]
Buongiorno, la pull request è stata creata correttamente. Riceverà l'esito delle elaborazioni via e-mail nel giro di qualche giorno lavorativo. Grazie.
