### ISSUE TITLE
Controlli su identificativo del documento

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-support#696]
Buongiorno,
mi servirebbe sapere se il gateway esegue (o prevede di eseguire) dei controlli sulla corrispondenza tra identificativo del documento contenuto nel CDA e identificativoDoc (XDSDocumentEntry.uniqueId) del requestBody della pubblicazione.

In genere si ha un sistema che crea il documento (sistema produttore) e un altro che lo pubblica (repository documentale locale), e il repository documentale locale può ricevere documenti da più sistemi produttori.
E' possibile che il repository documentale locale esegua una ri-codifica a livello di metadati, e quindi l'identificativo del documento contenuto nel CDA (generato dal sistema produttore) potrebbe essere diverso dall'identificativoDoc generato dal repository documentale locale e utilizzato nel requestBody della pubblicazione.

Grazie per le indicazioni che potrete fornire in merito.

**Comment by IStacchiotti** [comment]
Buonasera @ponsilva, le confermiamo che non è previsto un controllo di congruenza sull'identificativo del documento indicato nel cda rispetto a quello riportato nei metadati per la pubblicazione. Rimaniamo a disposizione per eventuali chiarimenti, grazie

**Comment by ponsilva** [comment]
Grazie a voi per il tempestivo riscontro
