### ISSUE TITLE
File report-checklist.xlsx

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#699]
Buongiorno, non riesco a trovare un link per scaricare il file report-checklist.xlsx. Potreste cortesemente indicarmelo?
Grazie

**Comment by vigliottim** [comment]
Buongiorno, al seguente link può trovare il file report-checklist: https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case
Grazie.

**Comment by infoserviceonline** [comment]
Avevo già esaminato la pagina indicata ma non trovo il file, o meglio lo trovo solo come citazione ma non come download, ho guardato anche nelle cartelle ma trovo sempre e solo il file accreditamento-checklist_V8.1.3.xlsx. Dove dovrebbe essere?
Grazie mille.
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/6019a546-a974-4ffc-91ed-41b68a7b4478)

**Comment by vigliottim** [comment]
Il file di checklist corrisponde al file [accreditamento-checklist_V8.1.3.xlsx](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/accreditamento-checklist_V8.1.3.xlsx). Dovrà modificarlo e rinominarlo report-checklist.xlsx per poi caricarlo nella directory di sottomissione.

**Comment by infoserviceonline** [comment]
Grazie mille, chiudo.
