### ISSUE TITLE
Gateway validation error - 400 Bad Request

### ISSUE THREAD

**Issue by MarcoKnezevichInsiel** [ministero-salute/it-fse-support#7]
Buongiorno, sono Marco Knezevich, uno sviluppatore dell'azienda Insiel spa del Friuli Venezia Giulia.

Sto cercando di invocare l'api del gatway per la validazione di un CDA2, effettuando una POST all'url:
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation

i token di autorizzazione sono nell'allegato _tokens.txt_ (validi per il giorno 16/08/2022) mentre i log della chiamata sono nell'allegato _logs_fvg_request_getway_validation_cda2.txt_ 

la parte di mutua authenticazione va a buon fine ma ricevo un errore 400 BAD_REQUEST con govay_id = b674bd85-1d70-11ed-931a-005056ae7395.

La request è stata effettuata con un'applicazione spring boot, tramite rest template e sembra essere conforme alle specifiche. Infatti ha:

- tutti gli header richiesti, compreso l'header  _Content-Type: multipart/form-data_
- viene passato un oggetto JSON con nome _requestBody_ (riga 45 del log) conforme alle specifiche
- viene passato un oggetto con nome _file_ contenente il file CDA2 

Nell'errore restituito non ci sono indicazioni specifiche di cosa non è corretto, quindi è un po' difficile capire cosa non va.

Avete qualche suggerimneto in merito?

Grazie

[tokens.txt](https://github.com/ministero-salute/it-fse-support/files/9352031/tokens.txt)
[logs_fvg_request_getway_validation_cda2.txt](https://github.com/ministero-salute/it-fse-support/files/9351995/logs_fvg_request_getway_validation_cda2.txt)

**Comment by zukka77** [comment]
Buongiorno nel jwt di autenticazione non vedo "aud" che va valorizzato a:
https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1
