### ISSUE TITLE
Accreditamento - Validazione [RSA + RAD + LDO] - Saxos Informatica S.R.L. - ProgettoOsp

### ISSUE THREAD

**Issue by Saxos-Simone** [ministero-salute/it-fse-support#700]
Buongiorno,
vi notifichiamo il caricamento completato dei test cases per l'accreditamento dei documenti di _RSA_, _RAD_ e _LDO_ della nostra soluzione:

[Accreditamento Validazione [RSA + RAD + LDO]: A1#111#SAXOSXX/Saxos_Informatica_S.R.L./ProgettoOsp/11.108](https://github.com/ministero-salute/it-fse-accreditamento/pull/1296)

Grazie.

**Comment by vigliottim** [comment]
Buongiorno, la ringraziamo per la notifica e procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
