### ISSUE TITLE
Firma PaDES PDF

### ISSUE THREAD

**Issue by michelebukovitz** [ministero-salute/it-fse-support#701]
Buongiorno, 
per la gestione della firma PDF è possibile utilizzare il certificato di firma, oppure va usato un token in possesso dell'utente?
Questo può valere anche in produzione?

**Comment by LucaRogledi** [comment]
Buongiorno,
La firma PaDES può essere applicata al PDF utilizzando il certificato di firma tramite il tool messo a disposizione online [pdf-generator](https://github.com/ministero-salute/it-fse-gtw-tools).

Esempio:
`java -jar pdf-generator.jar -c CDA_OK.xml -s Certificato_Firma_S1.p12 -pwd password`

Resitiamo a disposizione per eventuali chiarimenti.
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno,
Il messaggio di errore ricevuto viene generato dal sistema quando non è stato chiamato il servizio di validazione precedente alla chiama di pubblicazione/sostituzione o quando all'interno della requestBody utilizzata per la chiamata di pubblicazione/sostituzione viene specificato il workflowInstanceId di un documento non validato.
La invitiamo gentilmente a verificare quanto riportato e riprovare.
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno,
Dalle analisi effettuate risulta che sta chiamando il servizio di validazione con verifica, come si evince dalla chiamata al servizio status:
```
{
    "spanID": "95ed3deff45eff21",
    "traceID": "e9e564f160039fe1",
    "transactionData": [
        {
            "eventDate": "2024-03-29T10:29:05.228+00:00",
            "eventStatus": "SUCCESS",
            "eventType": "VALIDATION",
            "expiringDate": "2025-03-29T10:29:05.240+00:00",
            "issuer": "integrity:S1#111#CGMXX",
            "message": "Attenzione - è stato chiamato l'endpoint di validazione con VERIFICA",
            "organizzazione": "090",
            "subject": "BKVMHL78P21G224I^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "traceId": "810fc8e3c4ac5aa8",
            "workflowInstanceId": "0.1.2.3.4.9ae2bdd7beedc2e766c6b76585530e16925115707dc7a06ab5ee4aa2776b2c7b.46dda29018^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
        }
    ]
}
```
 
Come riportato in documentazione (https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#312-messaggio-di-richiesta-esempio-verifica-con-attachment), la validazione con VERIFICA è una validazione che non sarà seguita da pubblicazione.
Pertanto, la invitiamo a verificare che all'interno della requestBody del servizio di validazione il parameter activity sia correttamente valorizzato come "activity": "VALIDATION" invece di "activity": "VERIFICA" e riprovare.
Restiamo a disposizione per eventuali chiarimenti.
Grazie.
