### ISSUE TITLE
Errore nel rientro da INI - Pubblicazione (RL)

### ISSUE THREAD

**Issue by org035** [ministero-salute/it-fse-support#702]
Salve,
scriviamo dal team di sviluppo di Regione Lombardia. 
a seguito del test di validazione e successiva  pubblicazione sul GTW riceviamo l'indicizzazione da INI .
Questa la transazione 
{
    "traceID": "711e4ca6677f7fab",
    "spanID": "a3f69b8af8ef2cc3",
    "transactionData": [{
            "eventType": "VALIDATION",
            "eventDate": "2024-03-28T14:19:41.798+00:00",
            "eventStatus": "SUCCESS",
            "message": null,
            "identificativoDocumento": null,
            "subject": "KRNBRS58M08B236S^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "subjectRole": null,
            "tipoAttivita": null,
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.a8fb30b31a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "9683e876fd452a07",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-03-28T14:19:41.809+00:00",
            "extra": null
        }, {
            "eventType": "PUBLICATION",
            "eventDate": "2024-03-28T14:19:43.221+00:00",
            "eventStatus": "SUCCESS",
            "message": null,
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.30d55946-ed0e-11ee-a9d8-0242a89a8ac7",
            "subject": "KRNBRS58M08B236S^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "subjectRole": null,
            "tipoAttivita": "ERP",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.a8fb30b31a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "6b84a0faba87ff68",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-03-28T14:19:43.232+00:00",
            "extra": null
        }, {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-03-28T14:19:46.880+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": " SEVERITY : urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error ERROR_CODE : XDSRepositoryError",
            "identificativoDocumento": null,
            "subject": null,
            "subjectRole": null,
            "tipoAttivita": null,
            "organizzazione": null,
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.a8fb30b31a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": null,
            "issuer": null,
            "expiringDate": "2025-03-28T14:19:47.031+00:00",
            "extra": null
        }
    ]
}

Abbiamo ricevuto una RegisterDocumentSet-b da INI con il TAG authorInstitution cosi valorizzato .

                                    <ns2:Slot name="authorInstitution">
                                          <ns2:ValueList>
                                                <ns2:Value>AUTHOR_INSTITUTION_NOT_PRESENT</ns2:Value>
                                          </ns2:ValueList>
                                    </ns2:Slot>

che crea problemi alla nostra applicazione.

Vi chiediamo un riscontro sul motivo di tale valore se dovuto alla Pubblica verso il Gateway e alla mancata valorizzazione di tag in input o un errore nell'invio da INI al nostro FSE.

**Comment by nspazzoli** [comment]
Salve,

anche dai nostri Test (Emilia - Romagna) emerge lo stesso problema. 
Aggiungo la precisazione che il documento era stato corretamente validato e quindi credo ci sia una incoerenza fra i controlli in validazione e quanto poi necessario in pubblicazione.

Aggiungo inoltre che inserendo nel cda all'inteno del segmento _author_

```
<representedOrganization>
                <id root="2.16.840.1.113883.2.9.4.1.2" extension="080104" assigningAuthorityName="Ministero della Salute"/>    
                <name>Ausl Modena</name>
            </representedOrganization>
```

il TAG authorInstitution viene valorizzato. 
Mi risulta però che _representedOrganization_ sia dichiarato opzionale nelle specifiche CDA.

**Comment by EugenioGuagliardi** [comment]
Buongiorno, 
abbiamo seguito il consiglio dei colleghi dell'Emilia Romagna , inserendo nel CDA2 il tag non obbligatorio "representedOrganization"  con i seguenti valori :

<author> 
		<time value="20220325110000+0100"/>
		<assignedAuthor classCode="ASSIGNED"> 
			<id root="2.16.840.1.113883.2.9.4.3.2" extension="PROVAX00X00X000Y" assigningAuthorityName="MEF"/> 
			<addr>
				<country>100</country>
				<state>120</state>
				<county>RM</county> 
				<city>Roma</city> 
				<censusTract>058091</censusTract> 
				<postalCode>00184</postalCode> 
				<streetAddressLine>Via Milano 7</streetAddressLine>
			</addr>
			<telecom use="HP" value="mailto:prova.provax@example.com"/> 
			<telecom use="WP" value="mailto:prova.provax@example.com"/> 
			<telecom use="MC" value="tel:3340000000"/>
			<assignedPerson> 
				<name> 
					<family>Test</family> 
					<given>Matteo</given> 
					<prefix>Dr</prefix>
				</name> 
			</assignedPerson>
			<representedOrganization>
				<id root="2.16.840.1.113883.2.9.2.30.4.11" extension="030703" assigningAuthorityName="Regione Lombardia" />
				<id root="2.16.840.1.113883.2.9.4.1.2" extension="03091600" assigningAuthorityName="Ministero della Salute" />
				<id root="2.16.840.1.113883.2.9.4.1.6" extension="0801" assigningAuthorityName="Ministero della Salute" />
			</representedOrganization>
		</assignedAuthor> 
	</author>

ed effettuando una nuova prova di test il risultato non cambia, infatti  riceviamo 
una RegisterDocumentSet-b da INI con il TAG authorInstitution cosi valorizzato:

 <ns2:Slot name="authorInstitution">
       ns2:ValueList
           ns2:ValueAUTHOR_INSTITUTION_NOT_PRESENT</ns2:Value>
  </ns2:ValueList>
 </ns2:Slot>


Questo è quanto ci risulta sullo stato della richiesta dal Gateway

| dataOra = 2024 - 03 - 29 10: 27: 12: 509 | server = null | ID_DC = null | ID_COOP = null | elapsed = 1711704432509 | DIR = SRV | OUT = {
    "traceID": "c52dc14c880b2f4b",
    "spanID": "1f3865a53ac1ce6a",
    "transactionData": [{
            "eventType": "VALIDATION",
            "eventDate": "2024-03-29T09:25:48.661+00:00",
            "eventStatus": "SUCCESS",
            "message": null,
            "identificativoDocumento": null,
            "subject": "KRNBRS58M08B236S^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "subjectRole": null,
            "tipoAttivita": null,
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.8c4e05fe16^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "b9ead28b0cc4dba7",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-03-29T09:25:48.672+00:00",
            "extra": null
        }, {
            "eventType": "PUBLICATION",
            "eventDate": "2024-03-29T09:25:50.066+00:00",
            "eventStatus": "SUCCESS",
            "message": null,
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.4d8bb3d2-edae-11ee-a9d8-0242a89a8ac7",
            "subject": "KRNBRS58M08B236S^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "subjectRole": null,
            "tipoAttivita": "ERP",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.8c4e05fe16^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "f5df1aa9c594490f",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-03-29T09:25:50.077+00:00",
            "extra": null
        }, {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-03-29T09:25:50.837+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": " SEVERITY : urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error ERROR_CODE : XDSRepositoryError",
            "identificativoDocumento": null,
            "subject": null,
            "subjectRole": null,
            "tipoAttivita": null,
            "organizzazione": null,
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.8c4e05fe16^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": null,
            "issuer": null,
            "expiringDate": "2025-03-29T09:25:50.953+00:00",
            "extra": null
        }
    ]
}


Cortesemente ci potete supportare?
Siamo Bloccati.

**Comment by pFonziSogei** [comment]
@EugenioGuagliardi  dovete aggiungere il tag "name" nel representedOrganization, di seguito un esempio completo:

<representedOrganization>
				<id root="2.16.840.1.113883.2.9.4.1.1" extension="030325" assigningAuthorityName="Ministero della Salute"/>	
				<name>ATS DELLA CITTA' METROPOLITANA DI MILANO</name>
				<telecom use="WP" value="mailto:prova.provax@example.com"/>
				<addr>
					<country>100</country>
					<state>30</state>
					<county>MI</county>
					<city>Milano</city>
					<censusTract>15146</censusTract>
					<postalCode>20129</postalCode>
					<streetAddressLine>via Goffredo Mameli 2</streetAddressLine>
				</addr>
			</representedOrganization>

Noi comunque prendiamo solo il primo valore della lista di ID che ci avete inviato

**Comment by EugenioGuagliardi** [comment]
@pFonziSogei : abbiamo riprocessato positivamente la transazione di pubblicazione e relativa indicizzazione. 
Tuttavia non vediamo ancora arrivare la notifica, chiediamo cortesemente di verificare e di abilitarla quanto prima.

Grazie per la collaborazione

**Comment by g-maugeri-sogei** [comment]
Buonasera, chiedo alla regione Lombardia di svolgere un nuovo tentativo al fine di verificare il funzionamento del messaggio di notifica.

**Comment by EugenioGuagliardi** [comment]
Abbiamo effettuato un nuovo test ma non vediamo ancora nulla per il servizio di notifica. Inserisco il "workflowInstanceId":

2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.abe48bcd62^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

**Comment by g-maugeri-sogei** [comment]
Ancora su argomento notifica metadati.
Allego sotto il messaggio in uscita dal socket utilizzato dall'applicazione e relativa risposta. Chiedo se lato vostro siete in grado di verificare velocemente se il messaggio arriva in ingresso alla LAN su cui sta in LISTEN il vostro server. In caso contrario provvediamo noi ad inseguire il messaggio tra gli apparati intermedi presenti tra il client chiamante e il router di frontiera dell' AS Sogei per capire se il problema dipende da noi o voi.
SOAP outbound Message :<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><NotifySub
mitObjectsRequest xmlns="http://www.fascicolosanitario.gov.it/schema/typeSchemaNotifySubmitObjects"><HomeCommunityId>030</HomeCommunityId><RepositoryUniqueId>2.16.840.1.1138
83.2.9.2.30.4.5.030703</RepositoryUniqueId><DocumentUniqueId>2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.dfc51f36-edcc-11ee-a9d8-0242a89a8ac7</DocumentUniqueId><PatientId>K
RNBRS53A21L817D</PatientId></NotifySubmitObjectsRequest></soapenv:Body></soapenv:Envelope>
2024-03-29 14:58:13.926 ERROR :  SOAP fault :<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsrf-bf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:w
sa="http://www.w3.org/2005/08/addressing" xmlns:wsrf-r="http://docs.oasis-open.org/wsrf/r-2"><env:Header>
<wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
<wsa:Action>http://www.w3.org/2005/08/addressing/soap/fault</wsa:Action>
<wsa:MessageID>urn:uuid:91fc030c-65e7-4c62-93b0-c30022f8ae22</wsa:MessageID>
<wsa:RelatesTo/></env:Header><env:Body>
<env:Fault><faultcode>env:Client</faultcode><faultstring>
                                        wsse:FailedAuthentication
                                </faultstring><detail>
<wsrf-r:ResourceUnknownFault>
<wsrf-bf:Timestamp>2024-03-29T13:58:13.918Z</wsrf-bf:Timestamp>
<wsrf-bf:Description>
                                                        Non e&apos; possibile autenticare l&apos;utente o verificare la validita&apos; dell&apos;asserzione
                                                </wsrf-bf:Description></wsrf-r:ResourceUnknownFault></detail></env:Fault></env:Body></env:Envelope>
2024-03-29 14:58:13.926 ERROR : ==========> INIZIO STACK TRACE
Exception: javax.xml.ws.soap.SOAPFaultException

**Comment by EugenioGuagliardi** [comment]
Abbiamo verificato anche nel RP ma non vediamo arrivare nessuna chiamata.

**Comment by EugenioGuagliardi** [comment]
Va bene, vi aggiorniamo appena fatto!
Grazie


___________________________________________________

Eugenio Guagliardi

Responsabile
Fascicolo Sanitario Elettronico
Struttura Prevenzione, FSE, Socio Sanità e Sistemi di Settore
Divisione Servizi per il Welfare Regionale

Ufficio: +39 02 39331.181
Cell.: +39 334 666.07.59
Mail: ***@***.******@***.***>

ARIA S.p.A. - Azienda Regionale per l’Innovazione e gli Acquisti
Via Torquato Taramelli, 26
20124 Milano
www.ariaspa.it<http://www.ariaspa.it/>
____________________________________________________


Da: g-maugeri-sogei ***@***.***>
Inviato: venerdì 29 marzo 2024 15:55
A: ministero-salute/it-fse-support ***@***.***>
Cc: Guagliardi Eugenio ***@***.***>; Mention ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Errore nel rientro da INI - Pubblicazione (RL) (Issue #702)


Abbiamo abilitato delle sonde. Potete riprovare entro 60 minuti?

**Comment by EugenioGuagliardi** [comment]
Eseguita prova ma ancora non vediamo nulla sulla notifica.
Inserisco il "workflowInstanceId":
2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.91ef23dc01^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

**Comment by EugenioGuagliardi** [comment]
Buongiorno,
non abbiamo avuto nessuna comunicazione a riguardo, nel caso servisse abbiamo appena rifatto una prova di pubblicazione andata a buon fine ma non vediamo arrivare ancora la notifica per il servizio "Notify Communication Metadata".
Di seguito Inserisco il "workflowInstanceId":
2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.5ccf117209^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

**Comment by pFonziSogei** [comment]
Come condiviso durante l'incontro con le regioni, la notifica è stata sbloccata e vi chiediamo di effettuare un altro test

**Comment by EugenioGuagliardi** [comment]
@pFonziSogei dalle verifiche fatte sui log di oggi abbiamo effettivamente trovato delle transazioni sulla notifica ,  abbiamo trovato circa 10 transazioni tutte inerenti allo stesso UniqueID e tutte con esito success
2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.c655319a-f258-11ee-a9d8-0242a89a8ac7  comunicato una sola volta.
Perché viene re-inviata la transazione se ha esito positivo?
Come orari delle transazioni: dalle 10:55 alle 11:55 circa.
Segnalo inoltre che ci aspettavamo anche le notifiche dei precedenti test già effettuati per il Crash Program (UC1,UC9,UC11).
Vi chiediamo di verificare per i seguenti ID dei precedenti test
identificativo doc UC1   : 2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.5cc5e60a-f1b5-11ee-a9d8-0242a89a8ac7
identificativo doc UC9   : 2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.8af3a2a4-f1c1-11ee-a9d8-0242a89a8ac7
identificativo doc UC11 : 2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.f9f30fd0-f1c8-11ee-a9d8-0242a89a8ac7

Grazie

**Comment by pFonziSogei** [comment]
Ciao Eugenio, lato INI è stata introdotta una fix che dovrebbe risolvere il problema, potresti fare un giro pulito?

**Comment by IStacchiotti** [comment]
Salve, per le chiamate pregresse potrebbero non arrivare le notifiche poiché il giro non era pulito, essendo stata effettuata la chiamata prima del rilascio della fix.
