### ISSUE TITLE
Vs. comunicazione: Mancato accreditamento (checklist)

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#703]
Buongiorno,
ho ricevuto la vostra e-mail di riscontro alla mia pull request ed avrei bisogno di un chiarimento.
A parte la mancanza del valore nella colonna T, non mi è chiaro il meccanismo di esecuzione delle chiamate.
A quanto ho capito dalla vostra segnalazione io devo obbligatoriamente fare una pull request con tutti i test case di validazione inerenti al tipo documento LAB e non posso invece fare una pull request solo per alcuni casi.
Noto anche che nel vostro elenco dei test mancanti, non sono presenti i test 191, 368 e 376, pur se assegnati al tipo LAB.
Immagino che ciò valga anche per i test RAD e quelli RSA, per i quali ho chiesto l'accreditamento.
Mi confermate la correttezza del mio ragionamento?
Grazie mille.
(Non so se devo allegare il testo dell'e-mail)

**Comment by IStacchiotti** [comment]
Buongiorno,
 
riportiamo in un elenco puntato i chiarimenti richiesti.
 

1. Confermiamo che è necessario eseguire una pull request contenente tutti i casi di test per la/le tipologia/e documentale/i per cui si intente effettuare il processo di accreditamento (non è possibile inviare solo alcuni dei casi di test), avendo cura di valorizzare il campo applicabilità con "SI" laddove il test sia per voi replicabile e con "NO" laddove invece il test non possa essere riprodotto. Ricordiamo, inoltre, che per i casi di test non applicabili, è necessario compilare anche il campo "Razionale di applicabilità" con le motivazioni per le quali il test non è applicabile.

2. La lista dei test mancanti non è completa, in quanto sono state cancellate molte righe nel file caricato rispetto al template. Consigliamo, quindi, di riprendere la versione originale del template e di ricompilarlo ex-novo avendo cura di mantenere tutte le righe relative alle coppie di servizio/CDA di interesse ai fini dell'accreditamento.
3. Per quanto riguarda le tipologie documentali RAD e RSA, esse non sono state prese in considerazione nell'analisi in quanto totalmente assenti dalla checklist sottomessa. Nel caso in cui vogliate procedere con la sottomissione di queste tipogie documentali, è necessario che compiliate i relativi casi di test all'interno della checklist, che carichiate i file pdf utilizzati nell'invocazione dei servizi e che aggiungiate nel file data.json i riferimenti di tracciatura dei risultati dei test.

Rimaniamo a disposizione per chiarimenti

**Comment by infoserviceonline** [comment]
Grazie per i chiarimenti, solo pochi altri dubbi, per non sbagliare nuovamente: 
cosa intendete per "replicabile"? Ovviamente saremo in grado di riprodurre il caso, se necessario, o forse il senso è questo che leggo nelle istruzioni?
**4) Se il   test NON è applicabile la colonna APPLICABILITA' riporterà NO e dovrà essere   compilata esclusivamente la colonna RAZIONALE DI APPLICABILITA' con le   motivazioni per cui il test non è applicabile**
E' almeno possibile suddividere i test per tipo (LAB, RAD, RSA)? Agevolerebbe molto il lavoro di equipe.
La documentazione dei test case sembra incompleta, ad esempio sul file casi di test LAB.docx non riporta nulla sui test 368 e 376, quella nel file casi di test RAD.docx riporta numeri di casi che non corrispondono a quelli presenti nel file excel accreditamento-checklist_V8.1.3. Lo stesso dicasi per i casi di RSA. Stesso problema nei vari file excel KO ed OK, i cui casi di test non corrispondono alla checklist.
C'è qualcosa che mi sfugge nell'associazione dei test nei file docx/xlsx ed i casi del file accreditamento-checklist_V8.1.3?
Grazie mille per la pazienza e disponibilità.

**Comment by IStacchiotti** [comment]
Buongiorno, rispondiamo nuovamente di seguito per punti:

- Per test replicabile si intende un test che possa essere riprodotto come da specifiche riportate in documentazione a questo [link](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione). Per tali casi di test il campo applicabilità deve essere sempre valorizzato con "SI".

- Le segnaliamo che la checklist deve essere una sola per ogni applicativo. Eventualmente, è possibile procedere con l'accreditamento di una sola tipologia documentale per volta. Sottolineamo, però, che, come indicato a questo [link](https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#nuova-tipologia-documentale-per-applicativo-gi%C3%A0-presente-nella-lista-dei-software-convalidati) della documentazione, una volta ottenuta la convalida per una prima tipologia documentale (es. LAB), per procedere nell'accreditamento di un seconda tipologia (es. RAD), sarà necessario sottomettere una nuova pull request contenente tutti i casi di test (e relativo data.json) eseguiti per le due tipologie documentali (LAB + RAD). Di solito, in ogni caso, consigliamo di inviare fin da subito una checklist comprensiva di tutti i CDA per i quali si intende accreditarsi, poichè altrimenti sarebbe necessario ripetere tutti i casi di test ogni qualvolta si intenda aggiungere una nuova tipologia documentale. 

- Per ricondurre l'id dei casi di test presenti nella checklist ai casi di test elencati nel documento word, suggeriamo di fare riferimento alla colonna "NOME CASO TEST" del template, valorizzata secondo l'espressione `{servizio}_CDA2_{CDA}_CT{#numero CT}`, dove `#numero CT` corrisponde alla numerazione assegnata ai casi di test all'interno del file docx per la tipologia documentale in questione. Ad esempio, per l'id 368 di LAB, la colonna NOME CASO TEST contiene "CT0":
<img width="926" alt="Screenshot 2024-03-29 125816" src="https://github.com/ministero-salute/it-fse-support/assets/122798799/fe386185-f8b4-4ea3-a0c7-3ab5c9425986">quindi, il caso di test a cui fare riferimento nel word di LAB sarà il CASO DI TEST 0.
<img width="935" alt="Screenshot 2024-03-29 125540" src="https://github.com/ministero-salute/it-fse-support/assets/122798799/bb6c77f5-81d4-439c-b0ea-b673773569d8"> Una volta individuato il caso di test sul file word, sarà necessario aprire l'opportuno file `CDA2_{CDA}_{OK/KO}.xlsx` e posizionarsi sul tab con nome corrispondente a quello presente nel word. Ad esempio, per il CASO DI TEST 0 di LAB (corrispondente all'id 368 della checklist), lo sheet da prendere in considerazione sul file CDA2_Referto Medicina di Laboratorio_OK.xlsx sarà LAB - Caso di test 0:<img width="935" alt="Screenshot 2024-03-29 130436" src="https://github.com/ministero-salute/it-fse-support/assets/122798799/d2ae2739-6e3d-42d6-b3f0-4890b3eaea25">

**Comment by infoserviceonline** [comment]
Grazie mille e scusatemi se ho fatto troppe domande.
Saluto e chiudo.
