### ISSUE TITLE
Errore aggiornamento documento

### ISSUE THREAD

**Issue by ciampysara** [ministero-salute/it-fse-support#704]
Buongiorno non riusciamo ad aggiornare un documento precedentemente pubblicato con riscontro positivo (2.16.840.1.113883.2.9.2.90.4.4.22ce456e634a236cbd96bbcd5b6aa7a20af14caf549fd7cf7c986f54b2368ea7.af0864efe2^^^^urn:ihe:iti:xdw:2013:workflowInstanceId)

HTTP/1.1 404 Not Found
X-Backside-Transport: FAIL FAIL
Connection: Keep-Alive
Transfer-Encoding: chunked
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
set-cookie: 894d46ecfc124039ee218b63c12a3329=89abaebb3027dd249ad669fefaf335ad; path=/; HttpOnly; Secure; SameSite=None
Server: GovWay-SOGEI
Pragma: no-cache
GovWay-Message-ID: b159a065-0d61-498c-af9e-4d73c86017cd
GovWay-Transaction-ID: 6dca395f-edbf-11ee-93a7-005056ae54fa
server-timing: intid;desc=f046823a04e26bf3
content-disposition: inline;filename=f.txt
Date: Fri, 29 Mar 2024 12:01:41 GMT
Vary: *
X-Content-Type-Options: nosniff
Content-Type: application/problem+json
X-Global-Transaction-ID: 3f7e3e2d6606ada11c46027d

{"traceID":"5296ec86489bf215","spanID":"5296ec86489bf215","type":"/msg/record-not-found","title":"Record non trovato.","detail":"No Record Found","status":404,"instance":"/record-not-found"}

**Comment by vigliottim** [comment]
Buon pomeriggio, dalle analisi effettuate risulta che il campo _identificativoDocumento_ non è stato correttamente valorizzato durante la chiamata al servizio di pubblicazione (2.16.840.1.113883.2.9.2.90.4.4.22ce456e634a236cbd96bbcd5b6aa7a20af14caf549fd7cf7c986f54b2368ea7.af0864efe2^^^^urn:ihe:iti:xdw:2013:workflowInstanceId). 
Esso deve essere valorizzato con la stringa completa utilizzata per tale parametro nel servizio di creazione dopo aver effettuato l'url encode:
_As is:_ 09090101.RSA.901.000150 
_To be:_ 2.16.840.1.113883.2.9.2.90.4.4%5E09090101.RSA.901.000150

Per effettuare l'url encode la informiamo che al link https://www.urlencoder.org/ è presente un tool online che può esserle utile. Rimaniamo a disposizione per ulteriori chiarimenti.
