### ISSUE TITLE
caso PUBBLICAZIONE_CREAZIONE_CDA2_RSA_CT4_KO

### ISSUE THREAD

**Issue by ciampysara** [ministero-salute/it-fse-support#705]
Buongiorno anche sottomettendo più volte la pubblicazione dello stesso documento, il sistema continua a darmi riscontro positivo
HTTP/1.1 201 Created
X-Backside-Transport: OK OK
Connection: Keep-Alive
Transfer-Encoding: chunked
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
set-cookie: 894d46ecfc124039ee218b63c12a3329=89abaebb3027dd249ad669fefaf335ad; path=/; HttpOnly; Secure; SameSite=None
Server: GovWay-SOGEI
Pragma: no-cache
GovWay-Message-ID: b159a065-0d61-498c-af9e-4d73c86017cd
GovWay-Transaction-ID: 2dd6bca9-edc2-11ee-93a7-005056ae54fa
server-timing: intid;desc=d9289b07d630ca41
Date: Fri, 29 Mar 2024 12:22:13 GMT
Vary: *
X-Content-Type-Options: nosniff
Content-Type: application/json
X-Global-Transaction-ID: 3f7e3e2d6606b2741c4a321d

{"traceID":"342e7a194d54f050","spanID":"342e7a194d54f050","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.90.4.4.22ce456e634a236cbd96bbcd5b6aa7a20af14caf549fd7cf7c986f54b2368ea7.c3e4c7811e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

**Comment by LucaRogledi** [comment]
Buonasera,
Confermiamo che la chiamata va a buon fine nella parte sincrona, mentre nella parte asincrona, come si può notare dal messaggio restituito dal servizio di status utilizzando il workflowInstanceId da lei riportato, si riceve un errore bloccante dovuto al documento già esistente:
 
```
{
            "eventDate": "2024-03-29T12:22:13.640+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "eventType": "EDS_WORKFLOW",
            "expiringDate": "2025-03-29T12:22:13.650+00:00",
            "message": "Documento già esistente",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.22ce456e634a236cbd96bbcd5b6aa7a20af14caf549fd7cf7c986f54b2368ea7.c3e4c7811e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
 }
```

Restiamo a disposizione per eventuali chiarimenti.
Grazie
