### ISSUE TITLE
Problemi in fase di validazione

### ISSUE THREAD

**Issue by sviluppoTServe** [ministero-salute/it-fse-support#708]
Buongiorno
In fase di invio del CDA a scopo di validazione ottengo l'errore

curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.

In allegato il messaggio curl completo.

Mi aiutate per cortesia a capire l'errore?

grazie, saluti

[Validazione.txt](https://github.com/ministero-salute/it-fse-support/files/14805246/Validazione.txt)

**Comment by vigliottim** [comment]
Buongiorno, nella curl che ci ha inviato non è presente il riferimento al certificayto p12 di autenticazione, necessario per la predisposizione del canale http. 
Se sta utilizzando il command prompt di Windows, può fare riferimento a questo messaggio nel ticket #660 in cui abbiamo riportato un template di riferimento per la curl: 
[#660](https://github.com/ministero-salute/it-fse-support/issues/660#issuecomment-1994589825)
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by sviluppoTServe** [comment]
Grazie, era quello che mancava ...

ora la risposta è:

{
	"type": "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
	"title": "AuthorizationContentDeny",
	"status": 403,
	"detail": "Unauthorized request content",
	"govway_id": "f1cf6061-ede4-11ee-9223-005056ae7395"
}

Il certificato è quello di autenticazione ed è lo stesso usato per creare i JWT.  Cosa potrebbe mancare ?

saluti

**Comment by LucaRogledi** [comment]
Buonasera,
In merito a quanto riportato nel suo ultimo messaggio:

> Il certificato è quello di autenticazione ed è lo stesso usato per creare i JWT. Cosa potrebbe mancare ?

Le segnaliamo che il certificato da utilizzare per la generazione dei token è il certificato di firma S1**.p12, non il certificato di autenticazione A1**.p12 che viene utilizzato invece per la chiamata del servizio.
La invitiamo gentilmente a rigenerare i token utilizzando il certificato corretto e riprovare.
Restiamo a disposizione per eventuali chiarimenti,
Grazie.

**Comment by sviluppoTServe** [comment]
Buonasera e  grazie per le  info precedenti

Sistemato tutto la richiesta di verifica del CDA produce questa risposta:

{"traceID":"d65050f347cf9056","spanID":"d65050f347cf9056","type":"/msg/generic-error","title":"Errore generico.","detail":"Index: 0, Size: 0","status":500,"instance":""}

in allegato il log completo

grazie, saluti

[RichiestaVerifica.txt](https://github.com/ministero-salute/it-fse-support/files/14855802/RichiestaVerifica.txt)

**Comment by vigliottim** [comment]
Buonasera, nel messaggio di richiesta utilizzato risultano mancanti di doppi apici di apertura nel parametro _file_:
<img width="442" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/b2f1bd0b-3d56-4f94-ae09-56847f403499">
Le chiediamo di effettuare la correzione indicata e riprovare. Grazie.

**Comment by sviluppoTServe** [comment]
Buongiorno e grazie della risposta
Ho sistemato il punto indicato e la risposta è stata

	"type": "https://govway.org/handling-errors/400/InvalidRequestContent.html",
	"title": "InvalidRequestContent",
	"status": 400,
	"detail": "Request content not conform to API specification: Validation error(s) :\nAn error occurred when getting the body content from type 'multipart/form-data; boundary=------------------------0nk5awxQvLiJsErwNIgOp0'.\ncom.fasterxml.jackson.core.JsonParseException: Unexpected character ('h' (code 104)): was expecting double-quote to start field name\n at [Source: (org.apache.commons.fileupload.MultipartStream$ItemInputStream); line: 1, column: 3] (code: 201)\n",
	"govway_id": "69833666-f256-11ee-9223-005056ae7395"

Allora ho modificato il body inserendo i doppi apici ma resta ancora un errore;

{"traceID":"8b55a254ca01016a","spanID":"8b55a254ca01016a","type":"/msg/generic-error","title":"Errore generico.","detail":"Index: 0, Size: 0","status":500,"instance":""}

in allegato il log
[RichiestaVerifica_1.txt](https://github.com/ministero-salute/it-fse-support/files/14864083/RichiestaVerifica_1.txt)

grazie, buona giornata

**Comment by vigliottim** [comment]
Buongiorno, 
le chiediamo di effettuare la seguente correzione nel parametro _file_ e riprovare:
_As is:_ 
`-F "file=@"G:\sorgenti\ProgettiVS2022\TSCreaFSE\bin\Debug\FSETools\output\CDA-2024040212264692.pdf;type=application/pdf"`
_To be:_ 
`-F "file=@G:\sorgenti\ProgettiVS2022\TSCreaFSE\bin\Debug\FSETools\output\CDA-2024040212264692.pdf;type=application/pdf"`
Rimaniamo a disposizione nel caso in cui il problema dovesse ripresentarsi. 
Grazie.

**Comment by sviluppoTServe** [comment]
Salve

Mi spiace ... ma anche questa modifica non risolve il problema. L'errore è sempre

{"traceID":"f016226146888e41","spanID":"f016226146888e41","type":"/msg/generic-error","title":"Errore generico.","detail":"Index: 0, Size: 0","status":500,"instance":""}

saluti

**Comment by vigliottim** [comment]
Per consentirci di effettuare analisi più approfondite potrebbe gentilmente allegare il PDF utilizzato? Grazie.

**Comment by sviluppoTServe** [comment]
eccolo: 
[CDA-2024040212264692.pdf](https://github.com/ministero-salute/it-fse-support/files/14872899/CDA-2024040212264692.pdf)
grazie, saluti

**Comment by vigliottim** [comment]
Buonasera, il pdf inviato risulta corrotto: 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/4f900b86-79e8-4312-8ecd-f286f84e0b6b)
La invitiamo a rigenerarlo utilizzando l'encoding UTF-8 per il CDA2 e ad effettuare nuovamente la chiamata. 
Se può esserle d'aiuto, è disponibile il tool pdf-generator al seguente link: 
https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/pdf-generator 
Grazie.

**Comment by sviluppoTServe** [comment]
Buonasera
Strano.. qui si apre normalmente, potrebbe essersi corrotto nell'invio, riprovo nel formato .zip
Per generarlo ho usato lo strumento pdf-generator come indicato.

[PDFscreeshot.docx](https://github.com/ministero-salute/it-fse-support/files/14873683/PDFscreeshot.docx)
.zip
[CDA-2024040212264692.zip](https://github.com/ministero-salute/it-fse-support/files/14873640/CDA-2024040212264692.zip)

grazie nuovamente...saluti

**Comment by vigliottim** [comment]
Buonasera,
purtroppo anche estraendo il file pdf dalla cartella zip, otteniamo lo stesso errore.
Come detto in precedenza, la invitiamo a riprovare modificando l'encoding del CDA2 da **utf-16** a **utf-8**:
<img width="253" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/b7efbdf4-a749-4fd9-8c69-c5b543709628">
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto riscontri, il presente ticket viene chiuso. 
Può procedere alla riapertura nel caso in cui abbia bisogno di ulteriore supporto. 
Grazie.

**Comment by sviluppoTServe** [comment]
D'accordo, grazie.

   buona giornata
   [TServe_64.jpg]

   TS23 di Laura Livolsi
   Fulvio Modesto
   3481577677
   ***@***.***
   www.tserve.info
   Da "Michela Vigliotti" ***@***.***
   A "ministero-salute/it-fse-support" ***@***.***
   Cc "sviluppoTServe" ***@***.***,"Author" ***@***.***
   Data Tue, 09 Apr 2024 23:49:06 -0700
   Oggetto Re: [ministero-salute/it-fse-support] Problemi in fase di validazione (Issue #708)

   Buongiorno, non avendo ricevuto riscontri, il presente ticket viene chiuso.
   Può procedere alla riapertura nel caso in cui abbia bisogno di ulteriore supporto.
   Grazie.
