### ISSUE TITLE
PUBBLICAZIONE_CREAZIONE_CDA2_RSA_CT8_KO non ci ritorna errore bloccante nella parte asincrona

### ISSUE THREAD

**Issue by ciampysara** [ministero-salute/it-fse-support#709]
Buongiorno per il caso 

PUBBLICAZIONE_CREAZIONE_CDA2_RSA_CT8_KO

Abbiamo inviato una richiesta con "workflowInstanceId":"2.16.840.1.113883.2.9.2.90.4.4.22ce456e634a236cbd96bbcd5b6aa7a20af14caf549fd7cf7c986f54b2368ea7.b991eea3ec^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"

Il servizio di status non ritorna un errore bloccante nonostante sia stata inserita la stringa per far scattare l'errore

HTTP/1.1 200 OK
X-Backside-Transport: OK OK
Connection: Keep-Alive
Transfer-Encoding: chunked
cache-control: private
set-cookie: 894d46ecfc124039ee218b63c12a3329=6caa4f1bda74e3b3b757b7fa19072d6f; path=/; HttpOnly; Secure; SameSite=None
Server: GovWay-SOGEI
GovWay-Message-ID: b159a065-0d61-498c-af9e-4d73c86017cd
GovWay-Transaction-ID: f3d4bc4b-f0c6-11ee-93a7-005056ae54fa
server-timing: intid;desc=43f4df0daecd8fad
content-disposition: inline;filename=f.txt
Date: Tue, 02 Apr 2024 08:21:59 GMT
X-Content-Type-Options: nosniff
Content-Type: application/json
X-Global-Transaction-ID: 3f7e3e2d660bc0272811f8cf

{"traceID":"cf76306114d72fbe","spanID":"26629e3700118208","transactionData":[{"eventType":"PUBLICATION","eventDate":"2024-03-29T12:37:44.219+00:00","eventStatus":"SUCCESS","identificativoDocumento":"CRASH_WF_EDS_2.16.840.1.113883.2.9.2.90.4.4^09090101.RSA.901.000150","subject":"RSSLBT72B44D077Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO","tipoAttivita":"ERP","organizzazione":"090","workflowInstanceId":"2.16.840.1.113883.2.9.2.90.4.4.22ce456e634a236cbd96bbcd5b6aa7a20af14caf549fd7cf7c986f54b2368ea7.b991eea3ec^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","traceId":"9499f6c1e3f41800","issuer":"integrity:S1#111ESTARTOSCANA","expiringDate":"2025-03-29T12:37:44.229+00:00"},{"eventType":"SEND_TO_INI","eventDate":"2024-03-29T12:37:44.307+00:00","****eventStatus":"SUCCESS","message":"Regime di mock abilitato**"**,"workflowInstanceId":"2.16.840.1.113883.2.9.2.90.4.4.22ce456e634a236cbd96bbcd5b6aa7a20af14caf549fd7cf7c986f54b2368ea7.b991eea3ec^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","expiringDate":"2025-03-29T12:37:44.317+00:00"},{"eventType":"EDS_WORKFLOW","eventDate":"2024-03-29T12:37:44.473+00:00","eventStatus":"BLOCKING_ERROR","message":"Crash eds workflow exception","workflowInstanceId":"2.16.840.1.113883.2.9.2.90.4.4.22ce456e634a236cbd96bbcd5b6aa7a20af14caf549fd7cf7c986f54b2368ea7.b991eea3ec^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","expiringDate":"2025-03-29T12:37:44.622+00:00"},{"eventType":"SEND_TO_EDS","eventDate":"2024-03-29T12:37:44.478+00:00","eventStatus":"SUCCESS","message":"{\"esito\":true}","workflowInstanceId":"2.16.840.1.113883.2.9.2.90.4.4.22ce456e634a236cbd96bbcd5b6aa7a20af14caf549fd7cf7c986f54b2368ea7.b991eea3ec^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","expiringDate":"2025-03-29T12:37:44.543+00:00"}

**Comment by IStacchiotti** [comment]
Buongiorno @ciampysara, il caso di test ci risulta svolto correttamente: segnaliamo infatti che il prefix dell'identificativo del documento "CRASH_WF_EDS_" non genera un errore su INI, che al momento è in regime di mock, ma piuttosto su "EDS_WORKFLOW", che, come potete osservare, è andato in errore come da attese con il seguente messaggio: `"Crash eds workflow exception"`.  Rimaniamo a disposizione per ulteriori chiarimenti, grazie
