### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by euritech** [ministero-salute/it-fse-support#710]
Buongiorno,
in fase di validazione il sistema restituisce: {"type":"https://govway.org/handling-errors/401/TokenAuthenticationFailed.html","title":"TokenAuthenticationFailed","status":401,"detail":"Invalid token","govway_id":"bf30f9e0-f0c7-11ee-9223-005056ae7395"}

Vi chiediamo gentilmente supporto in merito

**Comment by vigliottim** [comment]
Buongiorno, le chiediamo gentilmente di allegarci i token utilizzati per effettuare la chiamata? Grazie.

**Comment by euritech** [comment]
[isaac.sign.txt](https://github.com/ministero-salute/it-fse-support/files/14834290/isaac.sign.txt)
[isaac.auth.txt](https://github.com/ministero-salute/it-fse-support/files/14834291/isaac.auth.txt)

i file txt contengono i token (Bearer and JWT Authentication) generati col certificato S1xxxxxx.p12

Per la chiamata cURL è stato usato invece il certificato A1xxxxxxx.p12

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate sui token utilizzati, i seguenti campi non risultano corretti:

**Authentication Bearer Token:**

- _"aud": "FSE_Gateway"_: indica il destinatario per cui è stato creato il token, da valorizzare con la base URL del servizio, comprensivo della versione: `"aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1"`

- _"iss": "auth:jwt-issuer"_: deve essere valorizzato con "auth:" seguito dal "Common Name del certificato di firma"

**FSE-JWT-Signature:**

- _"aud": "FSE_Gateway"_: indica il destinatario per cui è stato creato il token, da valorizzare con la base URL del servizio, comprensivo della versione: `"aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1"`

- _"iss": "integrity:jwt-issuer"_: deve essere valorizzato con "integrity:" seguito dal "Common Name del certificato di firma"

- _"locality": "jwt-location"_: deve essere valorizzato con l'identificativo della struttura utente

- _"subject_application_version": "subject-application-version"_: deve essere valorizzato con la versione applicativo dell’utente

- _"subject_application_id": "subject-application-id"_: deve essere valorizzato con l'ID dell'applicativo dell’utente

- _"subject_application_vendor": "subject-application-vendor"_: deve essere valorizzato con il vendor applicativo dell’utente

Per la generazione dei token, qualora non lo stia giù utilizzando, può ricorrere al tool jwt-generator: https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator
Per maggiori informazioni sui campi contenuti nei JWT può consultare la documentazione al link: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt
La preghiamo di correggere gli errori segnalati e riprovare.
Grazie.

**Comment by euritech** [comment]
Buongiorno abbiamo ottenuto nuovamente il seguente errore: {"type":"https://govway.org/handling-errors/401/TokenAuthenticationFailed.html","title":"TokenAuthenticationFailed","status":401,"detail":"Invalid token","govway_id":"6685983c-f0d7-11ee-93a7-005056ae54fa"}%    


il json per generare i token con i jwt tools è stato così valorizzato:
{
	“sub”: “PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO”,
	“subject_role”: “AAS”,
	“purpose_of_use”: “TREATMENT”,
	“iss”: “[isaac4.it](http://isaac4.it/)”,
	“subject_application_id”: “1",
	“subject_application_vendor”: “isaac4",
	“subject_application_version”: “1.0",
	“locality”: “072006160",
	“subject_organization_id”: “160",
	“subject_organization”: “Regione Puglia”,
	“aud”: “https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1”,
	“patient_consent”: true,
	“action_id”: “CREATE”,
	“resource_hl7_type”: “(‘11502-2^^2.16.840.1.113883.6.1’)“,
	“jti”: “1234",
	“person_id”:“RSSMRA22A01A399Z^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO”,
	“pem_path”: “C:/Users/User/Downloads/it-fse-gtw-tools-main/it-fse-gtw-tools-main/jwt-generator/target/S1#111#EURITECHX1.pem”,
	“p12_path”: “C:/Users/User/Downloads/it-fse-gtw-tools-main/it-fse-gtw-tools-main/jwt-generator/target/S1#111#EURITECHX1.p12"
}

Questi i token generati:
[isaac.auth.txt](https://github.com/ministero-salute/it-fse-support/files/14835150/isaac.auth.txt)
[isaac.sign.txt](https://github.com/ministero-salute/it-fse-support/files/14835151/isaac.sign.txt)

Questa la richiesta di accreditamento compilata:
[richiesta_accreditamento_Contributionfc117041-1ee2-4038-9276-ffe0db9062d6.pdf](https://github.com/ministero-salute/it-fse-support/files/14835159/richiesta_accreditamento_Contributionfc117041-1ee2-4038-9276-ffe0db9062d6.pdf)

Questi i dati nelle CSR:

Country Name (2 letter code) [AU]:IT
State or Province Name (full name) [Some-State]:Italy
Locality Name (eg, city) []:Bari
Organization Name (eg, company) [Internet Widgits Pty Ltd]:Eurisko Technology
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:isaac4.it
Email Address []:matrixlab@euritech.eu



Vi ringraziamo per il supporto

**Comment by vigliottim** [comment]
Buongiorno, il campo _iss_ non è stato valorizzato correttamente. Esso deve contenere il common name del certificato di firma assegnato quando vi sono stati condivisi i certificati pem, al netto dell'estensione (S1#XXXXXXXXXXXX). 
Le chiediamo di effettuare la correzione indicata e riprovare, grazie.

**Comment by euritech** [comment]
Buonasera,
abbiamo nuovamente errore: {"type":"https://govway.org/handling-errors/401/TokenAuthenticationFailed.html","title":"TokenAuthenticationFailed","status":401,"detail":"Invalid token","govway_id":"8cc4c348-f0eb-11ee-93a7-005056ae54fa"}

di seguito il json usato per generare i token col tool apposito:

{
	“sub”: “PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO”,
	“subject_role”: “AAS”,
	“purpose_of_use”: “TREATMENT”,
	“iss”: “S1#111#EURITECHX1",
	“subject_application_id”: “1",
	“subject_application_vendor”: “isaac4",
	“subject_application_version”: “1.0",
	“locality”: “072006160",
	“subject_organization_id”: “160",
	“subject_organization”: “Regione Puglia”,
	“aud”: “https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1”,
	“patient_consent”: true,
	“action_id”: “CREATE”,
	“resource_hl7_type”: “(‘11502-2^^2.16.840.1.113883.6.1’)“,
	“jti”: “1234",
	“person_id”:“RSSMRA22A01A399Z^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO”,
	“pem_path”: “C:/Users/User/Downloads/it-fse-gtw-tools-main/it-fse-gtw-tools-main/jwt-generator/target/S1#111#EURITECHX1.pem”,
	“p12_path”: “C:/Users/User/Downloads/it-fse-gtw-tools-main/it-fse-gtw-tools-main/jwt-generator/target/S1#111#EURITECHX1.p12"
}

**Comment by vigliottim** [comment]
Le chiediamo di riprovare sostituendo i backticks con le double quote nel _data.json_ come indicato di seguito:

{
"sub": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
"subject_role": "AAS",
"purpose_of_use": "TREATMENT",
"iss": "S1#111#EURITECHX1",
"subject_application_id": "1",
"subject_application_vendor": "isaac4",
"subject_application_version": "1.0",
"locality": "072006160",
"subject_organization_id": "160",
"subject_organization": "Regione Puglia",
"aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
"patient_consent": true,
"action_id": "CREATE",
"resource_hl7_type": "(‘11502-2^^2.16.840.1.113883.6.1’)",
"jti": "1234",
"person_id":"RSSMRA22A01A399Z^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
"pem_path": "C:/Users/User/Downloads/it-fse-gtw-tools-main/it-fse-gtw-tools-main/jwt-generator/target/S1#111#EURITECHX1.pem",
"p12_path": "C:/Users/User/Downloads/it-fse-gtw-tools-main/it-fse-gtw-tools-main/jwt-generator/target/S1#111#EURITECHX1.p12"
}

Rimaniamo a disposizione se il problema non dovesse essere risolto.
Grazie.

**Comment by euritech** [comment]
Il risultato è lo stesso: {"type":"https://govway.org/handling-errors/401/TokenAuthenticationFailed.html","title":"TokenAuthenticationFailed","status":401,"detail":"Invalid token","govway_id":"3c57ba68-f0f5-11ee-93a7-005056ae54fa"}

alleghiamo il file data.json per vostra verifica
[data.json](https://github.com/ministero-salute/it-fse-support/files/14837517/data.json)

**Comment by euritech** [comment]
Di seguito la chiamata cURL (<PASSWORD> lo sostituiamo con la password del certificato di autenticazione



curl --cert-type P12 --cert A1#111#EURITECHX1.p12:<PASSWORD>  -X POST "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation" -H 'accept: application/json' -H 'Authorization: Bearer eyJ4NWMiOlsiTUlJRmFqQ0NBMUtnQXdJQkFnSVVkNi9DQlU1cXZBVWRaeGRPaCsrUndhWHAvT2t3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TkRBek1qa3hNVE0wTURGYUZ3MHlOekF6TXpBeE1UTTBNREJhTUdzeEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVJvd0dBWURWUVFEREJGVE1TTXhNVEVqUlZWU1NWUkZRMGhZTVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3dDRE5SbHQ0Z0hMTUsrV0RCZ0h2QURtdXN5YXhyY2lnenAvN1FPZTNqc0JnSzNRdGxDNmlhK3ZuQlNpQmQ4MG5GUzNSTTNXRE50Z09jU0FZemNjMTBWUkVLbWNXcDB6d3N0cExQUHZ0VENqUHZqNWZmaWFFR2U3VlZGZmNWSURGblVQMFd1WjUxRldtZ0dGVklKNWw4Z3AyaUdLVVF4Ym4weC9xRmVjWFZ0R2s5L3BUOExOd2Y3UHRldUFEMXJQQ3JoWDE2aWh1RWlIOUxqeFc2UnlTbkh4aVZoYkh2bkx3eTArK1pxaFlST0ZXRk1peUlLRTFvNDFkcXRCdWdpbk1YSDg3TEtGTzdTNzkwNHUvci9KREdhWWVTT0c3cmhkd1l6TjFLbzJmWmcxbXlOR1hHYVliRko2NnpzMnY3OCtURFhCcy9vMVR5UkwxOXBzN2pYUndrQ0F3RUFBYU9DQVJnd2dnRVVNQjhHQTFVZEl3UVlNQmFBRkJZNXFSb0ZpYmNQTGJJMTdjSUptc1VEZ3lJL01CSUdBMVVkSUFRTE1Ba3dCd1lGSzB3ZEFRc3dnYTBHQTFVZEh3U0JwVENCb2pDQm42Q0JuS0NCbVlhQmxtaDBkSEJ6T2k4dlkyRnpiMmRsYVhOMmFXd3VjMjluWldrdWFYUXZaV3BpWTJFdmNIVmliR2xqZDJWaUwzZGxZbVJwYzNRdlkyVnlkR1JwYzNRL1kyMWtQV055YkNacGMzTjFaWEk5UTA0bE0wUkRRU3ROYVc1cGMzUmxjbThyWkdWc2JHRXJVMkZzZFhSbEsxUmxjM1FsTWtOUEpUTkVUV2x1YVhOMFpYSnZLMlJsYkd4aEsxTmhiSFYwWlNVeVEwTWxNMFJKVkRBZEJnTlZIUTRFRmdRVURyQnVKb2U1WWI3cDV4R1RIYTRnVkpxSU9YOHdEZ1lEVlIwUEFRSC9CQVFEQWdaQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQVM0ZDdXYkp3bmFnSERnRTZRMEk5OUQxODl1NURiQzVSYnhLMm9xeVA2RDRaS1lJY1VBNnM2ZVIvM3FMdlZMVWwvRXU5dVV3QWhpMHV3UTlIelBFUG1sMnRDN21KYUZvWU8rTGkza2tjVmNwWnhvcSswS2thaVZOTUwzTFk5d3hCcVVtUUpReFdMZ2F6ejBwa1YvY2RYOFBRRUNVYTczbWVXaEVZTFMrTDM5NkJZWWVCQzUzMlo1U1hiV2txT2gwOFRvdUEyZUxXZGRlTU4zalQwdTVaRVpURW5RSitKQzFSRnUzMmFZdDVIOTBuZWZ1L3o3cjRZT0ZTdUJmeTFTVzl2ZFJIM0hzeEFXU3hPUTlIMEhIVWlqdHpiUDFtTWVjTHhYN293NDQxOXFrVnRNM1Y4MXRWcHdsZTdpRkpmQkRwdU01QUxlU3VNUmRreU55T29DS3g0Ym82aFh0UXpxcitFaXhmVjNNamx6dDJ2Smoyc0ZFcSsydzlZcksyZmlGL2FMOWdJZmhBb2pNMmcySUZRTWx6cGZEd1k0MTk0RlAwTFV5b2d1OTZLelUvYjZ3ZlpvKzhJK3NYQTdKTGRGT2NkdngwSWFFejhJd3JqcGVIV1piVXV3Ym4vVTdXcEZOUXZHM2h3ZDhnenZlblp0anBiYnBIZlU2a1R0b1NCdVE4M3puUjNNRUllUTloNTh6Y1gyMW5rVHM1RlZobnZKRTdBaEIxRmVNcDI1SW5QdjZ6Sy9uNHZFMC8rSWZZM290bWxycUtyTGhnKy93MHVpZG5zbWFUd0lGLzdGYzZSRGpsdEhMYWllQ0NaOTZIbHgzaG1mMzljbVFBaE9DTXBqMXcxejZNRTFGRWxrZ0lTK1lzekU1T2tzdUF6cFhWWVZ5QTRsMWtQa0xsTWtnPT0iXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJQUk9WQVgwMFgwMFgwMDBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJpc3MiOiJhdXRoOlMxIzExMSNFVVJJVEVDSFgxIiwiZXhwIjoxNzEyMTUyMDA2LCJpYXQiOjE3MTIwNjU2MDYsImp0aSI6IjEyMzQifQ.dtbswmQuaykgXYT9WncFGhfZlsOrA6eUI772s2i012BWl9233buwlH9OZejCC9q6KqWtYlBl1Ebus3eodaGd6YoNArB1Gi6PFR96px6wsTwz7sNqGfnRVqnVEGqaWehPpOTjim0t57EPuSN7hkArOZGLlWpQj3N1d0Cv9YhY2YVdpMcrReqPrM47uoZ8GS40Y_j2K_CJVimrMcM79eBriz9KvA6BhVOsGGMwjSBwMxxfiNTTpeXEG6dwiU0WUL4HbTKLQcoAJDn4X_XxdigI9g1t6nxgAAs7RAjKp3843jPMDERN8ltXcVdyyfdkX_rxx3Y9lptYTnPjzCYgB5kXQA' -H 'FSE-JWT-Signature: eyJ4NWMiOlsiTUlJRmFqQ0NBMUtnQXdJQkFnSVVkNi9DQlU1cXZBVWRaeGRPaCsrUndhWHAvT2t3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TkRBek1qa3hNVE0wTURGYUZ3MHlOekF6TXpBeE1UTTBNREJhTUdzeEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVJvd0dBWURWUVFEREJGVE1TTXhNVEVqUlZWU1NWUkZRMGhZTVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3dDRE5SbHQ0Z0hMTUsrV0RCZ0h2QURtdXN5YXhyY2lnenAvN1FPZTNqc0JnSzNRdGxDNmlhK3ZuQlNpQmQ4MG5GUzNSTTNXRE50Z09jU0FZemNjMTBWUkVLbWNXcDB6d3N0cExQUHZ0VENqUHZqNWZmaWFFR2U3VlZGZmNWSURGblVQMFd1WjUxRldtZ0dGVklKNWw4Z3AyaUdLVVF4Ym4weC9xRmVjWFZ0R2s5L3BUOExOd2Y3UHRldUFEMXJQQ3JoWDE2aWh1RWlIOUxqeFc2UnlTbkh4aVZoYkh2bkx3eTArK1pxaFlST0ZXRk1peUlLRTFvNDFkcXRCdWdpbk1YSDg3TEtGTzdTNzkwNHUvci9KREdhWWVTT0c3cmhkd1l6TjFLbzJmWmcxbXlOR1hHYVliRko2NnpzMnY3OCtURFhCcy9vMVR5UkwxOXBzN2pYUndrQ0F3RUFBYU9DQVJnd2dnRVVNQjhHQTFVZEl3UVlNQmFBRkJZNXFSb0ZpYmNQTGJJMTdjSUptc1VEZ3lJL01CSUdBMVVkSUFRTE1Ba3dCd1lGSzB3ZEFRc3dnYTBHQTFVZEh3U0JwVENCb2pDQm42Q0JuS0NCbVlhQmxtaDBkSEJ6T2k4dlkyRnpiMmRsYVhOMmFXd3VjMjluWldrdWFYUXZaV3BpWTJFdmNIVmliR2xqZDJWaUwzZGxZbVJwYzNRdlkyVnlkR1JwYzNRL1kyMWtQV055YkNacGMzTjFaWEk5UTA0bE0wUkRRU3ROYVc1cGMzUmxjbThyWkdWc2JHRXJVMkZzZFhSbEsxUmxjM1FsTWtOUEpUTkVUV2x1YVhOMFpYSnZLMlJsYkd4aEsxTmhiSFYwWlNVeVEwTWxNMFJKVkRBZEJnTlZIUTRFRmdRVURyQnVKb2U1WWI3cDV4R1RIYTRnVkpxSU9YOHdEZ1lEVlIwUEFRSC9CQVFEQWdaQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQVM0ZDdXYkp3bmFnSERnRTZRMEk5OUQxODl1NURiQzVSYnhLMm9xeVA2RDRaS1lJY1VBNnM2ZVIvM3FMdlZMVWwvRXU5dVV3QWhpMHV3UTlIelBFUG1sMnRDN21KYUZvWU8rTGkza2tjVmNwWnhvcSswS2thaVZOTUwzTFk5d3hCcVVtUUpReFdMZ2F6ejBwa1YvY2RYOFBRRUNVYTczbWVXaEVZTFMrTDM5NkJZWWVCQzUzMlo1U1hiV2txT2gwOFRvdUEyZUxXZGRlTU4zalQwdTVaRVpURW5RSitKQzFSRnUzMmFZdDVIOTBuZWZ1L3o3cjRZT0ZTdUJmeTFTVzl2ZFJIM0hzeEFXU3hPUTlIMEhIVWlqdHpiUDFtTWVjTHhYN293NDQxOXFrVnRNM1Y4MXRWcHdsZTdpRkpmQkRwdU01QUxlU3VNUmRreU55T29DS3g0Ym82aFh0UXpxcitFaXhmVjNNamx6dDJ2Smoyc0ZFcSsydzlZcksyZmlGL2FMOWdJZmhBb2pNMmcySUZRTWx6cGZEd1k0MTk0RlAwTFV5b2d1OTZLelUvYjZ3ZlpvKzhJK3NYQTdKTGRGT2NkdngwSWFFejhJd3JqcGVIV1piVXV3Ym4vVTdXcEZOUXZHM2h3ZDhnenZlblp0anBiYnBIZlU2a1R0b1NCdVE4M3puUjNNRUllUTloNTh6Y1gyMW5rVHM1RlZobnZKRTdBaEIxRmVNcDI1SW5QdjZ6Sy9uNHZFMC8rSWZZM290bWxycUtyTGhnKy93MHVpZG5zbWFUd0lGLzdGYzZSRGpsdEhMYWllQ0NaOTZIbHgzaG1mMzljbVFBaE9DTXBqMXcxejZNRTFGRWxrZ0lTK1lzekU1T2tzdUF6cFhWWVZ5QTRsMWtQa0xsTWtnPT0iXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJQUk9WQVgwMFgwMFgwMDBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImlzcyI6ImludGVncml0eTpTMSMxMTEjRVVSSVRFQ0hYMSIsImxvY2FsaXR5IjoiMDcyMDA2MTYwIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiMS4wIiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb25lIFB1Z2xpYSIsInN1YmplY3Rfb3JnYW5pemF0aW9uX2lkIjoiMTYwIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJhY3Rpb25faWQiOiJDUkVBVEUiLCJyZXNvdXJjZV9obDdfdHlwZSI6IignMTE1MDItMl5eMi4xNi44NDAuMS4xMTM4ODMuNi4xJykiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiMSIsImV4cCI6MTcxMjE1MjAwNiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZW5kb3IiOiJpc2FhYzQiLCJpYXQiOjE3MTIwNjU2MDYsImp0aSI6IjEyMzQiLCJwZXJzb25faWQiOiJSU1NNUkEyMkEwMUEzOTlaXl5eJmFtcDsyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImYW1wO0lTTyJ9.NotOvv7T0k_-h0RPya7rr-fLQGTBV9w1CLdRk_-IDq_2vIThj_JFgYtOGUOXjB1e804o480USiBllVlh59eF6-Ki5Y1ZpWxnpiZyjB_Kt7P_iYzdhWLqsyQOzSF77VSddh8FhzhL7QuGHyNq_aOLSaOM7KHc1GcKa1cR17cQT63KmgUPXAeNTapJiI-bK_YLglWIupNhA9Pd4NfjxJ6veZKdCgUSAS9HBsBwag2IzT-Fwm-S-ohX5XX_Y9KcBPscwKJzmE_0BqzVrb5wW8ChN5v62AYdQPfAhnQLXam14aO0XYL9OpO8MX3qnZQdt9qeMh-JWOu5e3Q94wWslwmTQA'  -H 'Content-Type: multipart/form-data' -F 'requestBody={  "healthDataFormat": "CDA", "mode": "ATTACHMENT", "activity": "VERIFICA"}' -F 'file=@output.pdf;type=application/pdf'

**Comment by euritech** [comment]
Aggiorniamo l'issue.

Utilizzando Postman per effettuare la stessa chiamata otteniamo un errore differente

{
    "traceID": "2bdb3da965ef3127",
    "spanID": "2bdb3da965ef3127",
    "type": "/msg/jwt-validation",
    "title": "Campo token JWT non valido.",
    "detail": "JWT payload: Tipologia documento diversa dalla tipologia di CDA (code - codesystem)",
    "status": 403,
    "instance": "/jwt-document-type",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.8fe46b71d98546dc779f4a7f4859b056b254bbe56b59baa550333b2c46441c87.2873406662^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

**Comment by vigliottim** [comment]
Buonasera,
il campo _resource_hl7_type_ contenuto nel JWT è ottenuto dal concatenamento dei campi _code_ e _codesystem_ secondo il seguente formato:
`"resource_hl7_type": "('CODE^^CODESYSTEM')"`
Il valore del campo `CODE` inserito in _resource_hl7_type_ del JWT deve essere coerente con quello inserito nel tag _ClinicalDocument/code_ contenuto all'interno del CDA (relativo alla tipologia di documento in esame).
La preghiamo di verificare ed eventualmente effettuare la correzione.
Grazie.

**Comment by euritech** [comment]
Ok, abbiamo risolto seguendo le vostre indicazioni.
Grazie
