### ISSUE TITLE
AGGIORNAMENTO METADATI

### ISSUE THREAD

**Issue by ciampysara** [ministero-salute/it-fse-support#711]
Buongiorno stiamo provando ad aggiornare i metadati ma ci torna il seguente errore:

HTTP/1.1 404 Not Found
X-Backside-Transport: FAIL FAIL
Connection: Keep-Alive
Transfer-Encoding: chunked
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
set-cookie: 894d46ecfc124039ee218b63c12a3329=89abaebb3027dd249ad669fefaf335ad; path=/; HttpOnly; Secure; SameSite=None
Server: GovWay-SOGEI
Pragma: no-cache
GovWay-Message-ID: b159a065-0d61-498c-af9e-4d73c86017cd
GovWay-Transaction-ID: ebdcb2b7-f0cf-11ee-9223-005056ae7395
server-timing: intid;desc=8ace4d2c86572665
Date: Tue, 02 Apr 2024 09:28:21 GMT
Vary: *
X-Content-Type-Options: nosniff
Content-Type: application/problem+json
X-Global-Transaction-ID: 3f7e3e2d660bcfb520cdb24d

{"traceID":"d1a64048f93a79ef","spanID":"d1a64048f93a79ef","type":"/msg/eds-error","title":"Eds error.","detail":"Document cannot be found on the Server FHIR","status":404,"instance":"/msg/eds-document-missing"}

**Comment by LucaRogledi** [comment]
Buongiorno, 
il messaggio di errore ricevuto può verificarsi in caso di mancata pubblicazione o mancata corrispondenza dell'identificativoDoc tra chiamata di pubblicazione e aggiornamento metadati. La invitiamo pertanto a verificare che:

- La pubblicazione del documento di cui si intende aggiornare i metadati sia avvenuta con successo, anche utilizzando il servizio di status; 

- L'identificativoDoc utilizzato nell'URL della chiamata del servizio di aggiornamento metadati presenti l'url encode (se può essere utile per l'url encode del identificativo doc è disponibile online il seguente servizio: https://www.freeformatter.com/url-encoder.html#before-output)

- L'identificativoDoc utilizzato dall'URL della chiamata del servizio di aggiornamento metadati, corrisponda all'identificativoDoc inserito all'interno della requestBody durante la chiamata di pubblicazione del documento (url encode non richiesto nella requestBody di pubblicazione). 

Se dovesse riscontrare nuovamente l'errore la invitiamo a fornirci la request completa utilizzata per la chiamata. 
Grazie

**Comment by ciampysara** [comment]
Lo status mi da riscontro positivo
L'OID è 2.16.840.1.113883.2.9.2.90.4.4%5E09090101.RSA.901.000150 usato per il caso precedente (289) di sostituzione del documento e nella requestBody è specificato l'identificativoDoc 
"identificativoDoc": "2.16.840.1.113883.2.9.2.90.4.4^09090101.RSA.901.001150",

HTTP/1.1 200 OK
X-Backside-Transport: OK OK
Connection: Keep-Alive
Transfer-Encoding: chunked
cache-control: private
set-cookie: 894d46ecfc124039ee218b63c12a3329=89abaebb3027dd249ad669fefaf335ad; path=/; HttpOnly; Secure; SameSite=None
Server: GovWay-SOGEI
GovWay-Message-ID: b159a065-0d61-498c-af9e-4d73c86017cd
GovWay-Transaction-ID: 27856682-f0d8-11ee-9223-005056ae7395
server-timing: intid;desc=efe8edb20e23dfa1
content-disposition: inline;filename=f.txt
Date: Tue, 02 Apr 2024 10:28:19 GMT
X-Content-Type-Options: nosniff
Content-Type: application/json
X-Global-Transaction-ID: 3f7e3e2d660bddc320ee70ad

{"traceID":"9112c1d481bfb09b","spanID":"0c885049d7c542dc","transactionData":[{"eventType":"VALIDATION","eventDate":"2024-03-29T11:54:07.815+00:00","eventStatus":"SUCCESS","subject":"RSSLBT72B44D077Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO","organizzazione":"090","workflowInstanceId":"2.16.840.1.113883.2.9.2.90.4.4.36f71ba1ebc5fd2a203739b946fb7edf9648b6ea8bfcbd22c8ab44e9cc6f2508.9af74df646^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","traceId":"71251f8c52e09e87","issuer":"integrity:S1#111ESTARTOSCANA","expiringDate":"2025-03-29T11:54:07.825+00:00"},{"eventType":"REPLACE","eventDate":"2024-04-02T08:31:07.449+00:00","eventStatus":"SUCCESS","identificativoDocumento":"2.16.840.1.113883.2.9.2.90.4.4^09090101.RSA.901.001150","subject":"RSSLBT72B44D077Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO","tipoAttivita":"ERP","organizzazione":"090","workflowInstanceId":"2.16.840.1.113883.2.9.2.90.4.4.36f71ba1ebc5fd2a203739b946fb7edf9648b6ea8bfcbd22c8ab44e9cc6f2508.9af74df646^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","traceId":"d2f742c563ea325d","issuer":"integrity:S1#111ESTARTOSCANA","expiringDate":"2025-04-02T08:31:07.459+00:00"},{"eventType":"SEND_TO_INI","eventDate":"2024-04-02T08:31:07.623+00:00","eventStatus":"SUCCESS","message":"Regime di mock abilitato","workflowInstanceId":"2.16.840.1.113883.2.9.2.90.4.4.36f71ba1ebc5fd2a203739b946fb7edf9648b6ea8bfcbd22c8ab44e9cc6f2508.9af74df646^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","expiringDate":"2025-04-02T08:31:07.754+00:00"},{"eventType":"SEND_TO_EDS","eventDate":"2024-04-02T08:31:07.969+00:00","eventStatus":"SUCCESS","message":"{\"esito\":true}","workflowInstanceId":"2.16.840.1.113883.2.9.2.90.4.4.36f71ba1ebc5fd2a203739b946fb7edf9648b6ea8bfcbd22c8ab44e9cc6f2508.9af74df646^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","expiringDate":"2025-04-02T08:31:08.125+00:00"},{"eventType":"EDS_WORKFLOW","eventDate":"2024-04-02T09:00:00.051+00:00","eventStatus":"SUCCESS","workflowInstanceId":"2.16.840.1.113883.2.9.2.90.4.4.36f71ba1ebc5fd2a203739b946fb7edf9648b6ea8bfcbd22c8ab44e9cc6f2508.9af74df646^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","expiringDate":"2025-04-02T09:00:00.073+00:00"}]}

**Comment by LucaRogledi** [comment]
Buongiorno, 
Chiamando il servizio di status tramite traceId fornito nel suo primo messaggio (`d1a64048f93a79ef`) è stato riscontrato l'utilizzo dell'identificativoDoc "`2.16.840.1.113883.2.9.2.90.4.4^09090101.RSA.901.000150`":
```
{
            "eventDate": "2024-04-02T09:28:21.582+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "eventType": "EDS_UPDATE",
            "expiringDate": "2025-04-02T09:28:21.592+00:00",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.90.4.4^09090101.RSA.901.000150",
            "issuer": "integrity:S1#111ESTARTOSCANA",
            "message": "Update EDS fallito",
            "organizzazione": "090",
            "subject": "RSSLBT72B44D077Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "traceId": "d1a64048f93a79ef",
            "workflowInstanceId": "a9d92a5da5fff8f561ff00dca93259e7f13c53a3f502a83b21ba9440e06abb92.f4023517af^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```
Tale identificativoDoc genera l'errore "Document cannot be found on the Server FHIR" in quanto è stato poi aggiornato tramite la chiamata del servizio di sostituzione da lei indicata. Pertanto la invitiamo a riprovare la chiamata di aggiornamento metadati utilizzando l'identificativoDoc contenuto nella requestBody della chiamata di Replace:  `2.16.840.1.113883.2.9.2.90.4.4^09090101.RSA.901.001150` avendo cura di verificare che l'url encode sia presente.
Rimaniamo a disposizione per eventuali chiarimenti.
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
