### ISSUE TITLE
Crash program Regione Toscana

### ISSUE THREAD

**Issue by OmarLorenzini** [ministero-salute/it-fse-support#713]
salve staimo tentando di invocare una create ma otteniamo il seguente errore
{

  "traceID" : "3bbfa1b5192fee6e",

  "spanID" : "3bbfa1b5192fee6e",

  "type" : "/msg/jwt-validation",

  "title" : "Campo token JWT non valido.",

  "detail" : "JWT payload: Tipologia documento diversa dalla tipologia di CDA (code - codesystem)",

  "status" : 403,

  "instance" : "/jwt-document-type"

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevurto ulteriori riscontri, procediamo alla chiusura del presente ticket. Potrà riaprirlo nel caso in cui avesse bisogno di ulteriore supporto. Grazie.
