### ISSUE TITLE
Problema SEND_TO_INI durante esecuzione Status del workflowInstanceId

### ISSUE THREAD

**Issue by rserrano73** [ministero-salute/it-fse-support#717]
Buongiorno. Stiamo effettuando il CRASH TEST per Regione Toscana e dopo l'esecuzione dello Status del workflowInstanceId viene mostrato un **Errore 500** all'interno del risultato:

{
    "traceID": "d7a407ba8e34036d",
    "spanID": "0b5adf303540a634",
    "transactionData": [
        {
            "eventType": "VALIDATION_FOR_PUBLICATION",
            "eventDate": "2024-04-02T15:19:58.843+00:00",
            "eventStatus": "SUCCESS",
            "subject": "BLRNDR68L13G920R",
            "organizzazione": "090",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.a2a1897ee4^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "9412c65e123b2bae",
            "issuer": "integrity:S1#090#090REGIONETOSCANA-TEST",
            "expiringDate": "2025-04-02T15:19:58.853+00:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-04-02T15:19:59.832+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.90.4.4^9999.LAB.910.9131",
            "subject": "BLRNDR68L13G920R",
            "tipoAttivita": "DIS",
            "organizzazione": "090",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.a2a1897ee4^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "9412c65e123b2bae",
            "issuer": "integrity:S1#090#090REGIONETOSCANA-TEST",
            "expiringDate": "2025-04-02T15:19:59.842+00:00"
        },
        **{
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-04-02T15:20:00.850+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "500 : \"{\"traceID\":\"0000000000000000178c8231e0755b09\",\"spanID\":\"178c8231e0755b09\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: Wrong attribute value or authority not known of $RESOURCEIDURN$ Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}\"",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.a2a1897ee4^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-04-02T15:20:00.921+00:00"
        }**
    ]
}

Si chiede pertanto di verificare e fornirci la soluzione perché il problema è bloccante per i nostri test.
Grazie e buon lavoro.

**Comment by pFonziSogei** [comment]
Per quanto riguarda lo status, non si tratta di un errore. Il servizio di Status serve proprio a segnalare cosa è andato ok e cosa ko. La risposta alla chiamata al servizio è in OK, poi viene segnalata la problematica durante la chiamata ad INI, che ora analizziamo

**Comment by rserrano73** [comment]
Grazie per la risposta. Attendiamo una soluzione al problema il prima possibile perché non ci permette di proseguire nei test del CRASH PROGRAM. Infatti anche provando richieste di Aggiornamento Metadata e Aggiornamento Documento restituiscono entrambi il medesimo errore (ovviamente con traceID differente):

{
    "traceID": "7f1134f260952059",
    "spanID": "7f1134f260952059",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "detail": "{\"traceID\":\"00000000000000007f1134f260952059\",\"spanID\":\"9739d45928f0e23a\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"Client received SOAP Fault from server: Wrong attribute value or authority not known of $RESOURCEIDURN$ Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}",
    "status": 500,
    "instance": "/msg/service-error/ini"
}

**Comment by pFonziSogei** [comment]
L'errore è non aver inserito all'interno del JWT il campo Subject in modo corretto nella richiesta al GTW.

Vediamo solo la presenza del CF mentre la formulazione dovrebbbe essere conforme alle specifiche IHE (ITI TF-3)

Esempio: CF^^^&2.16.840.1.113883.2.9.4.3.2&ISO

Riferimenti alle specifiche:

https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway

Tabella 39: Campi contenuti in Authentication Bearer Token

Campo SUBJECT

**Comment by rserrano73** [comment]
Grazie per la risposta.
Abbiamo modificato il sub come da indicazioni della richiesta:

{
"sub":"BLRNDR68L13G920R^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
"subject_role":"AAS",
"purpose_of_use":"TREATMENT",
"locality":"201123456",
"patient_consent":true,
"action_id":"CREATE",
"resource_hl7_type":"('11502-2^^2.16.840.1.113883.6.1')",
"attachment_hash":"a33d3d415804fb3a8813363702680fe93681065f4abe4ef5808b6e1e90d88ec6",
"person_id":"RMSLSO31M04Z404R"
}

Dopo una richiesta di validazione e poi di creazione correttamente sottomessa, il problema persiste per quanto riguarda la richiesta di STATUS con errore **BLOCKING_ERROR** nell'evento **SEND_TO_INI**:
{
    "traceID": "18ead7ba1c0ad40f",
    "spanID": "7acdaf5301008a96",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-04-03T10:11:20.337+00:00",
            "eventStatus": "SUCCESS",
            "subject": "BLRNDR68L13G920R^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "090",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.458c169d56^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "8ad701af01236f7d",
            "issuer": "integrity:S1#090#090REGIONETOSCANA-TEST",
            "expiringDate": "2025-04-03T10:11:20.349+00:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-04-03T10:11:36.838+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.90.4.4^9999.LAB.910.9131",
            "subject": "BLRNDR68L13G920R^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "DIS",
            "organizzazione": "090",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.458c169d56^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "f15ff783474d715c",
            "issuer": "integrity:S1#090#090REGIONETOSCANA-TEST",
            "expiringDate": "2025-04-03T10:11:36.848+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-04-03T10:11:48.676+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "500 : \"{\"traceID\":\"000000000000000011f8106b99a3e127\",\"spanID\":\"11f8106b99a3e127\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: Wrong attribute value or authority not known of $RESOURCEIDURN$ Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}\"",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.458c169d56^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-04-03T10:11:48.750+00:00"
        }
    ]
}

Allego il token utilizzato: FSE-JWT-Signature e GovWay-Integration
[FSE-JWT-Signature.txt](https://github.com/ministero-salute/it-fse-support/files/14850587/FSE-JWT-Signature.txt)
[GovWay-Integration.txt](https://github.com/ministero-salute/it-fse-support/files/14850588/GovWay-Integration.txt)

**Comment by pFonziSogei** [comment]
è errato anche il "person_id", dovete seguire le specifiche.

Di seguito i riferimenti tecnici da leggere:

https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway

Tabella 40: Campi contenuti in FSE-JWT-Signature

campo "person_id", specifiche IHE TF-3

Esempio: CF^^^&2.16.840.1.113883.2.9.4.3.2&ISO

**Comment by rserrano73** [comment]
Ok, abbiamo modificato opportunamente anche il person_id ma persiste il problema dell'evento **SEND_TO_INI**. Questo il risultato mostrato dallo Status del WorkFlowID:

{
    "traceID": "4fe162ecf984614e",
    "spanID": "1dfd23cab444ef8a",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-04-03T10:57:49.839+00:00",
            "eventStatus": "SUCCESS",
            "subject": "BLRNDR68L13G920R^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "090",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.bb9be2dde6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "6b76c5c32a4edcc8",
            "issuer": "integrity:S1#090#090REGIONETOSCANA-TEST",
            "expiringDate": "2025-04-03T10:57:49.850+00:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-04-03T10:57:56.290+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.90.4.4^9999.LAB.910.9131",
            "subject": "BLRNDR68L13G920R^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "DIS",
            "organizzazione": "090",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.bb9be2dde6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "657065ab132deae1",
            "issuer": "integrity:S1#090#090REGIONETOSCANA-TEST",
            "expiringDate": "2025-04-03T10:57:56.302+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-04-03T10:57:59.265+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "500 : \"{\"traceID\":\"0000000000000000854d562fb3cd9018\",\"spanID\":\"854d562fb3cd9018\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: Missing upload consent Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}\"",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.bb9be2dde6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-04-03T10:57:59.329+00:00"
        }
    ]
}

**Comment by pFonziSogei** [comment]
Mancano i consensi al cittadino, potete inviarli?

**Comment by rserrano73** [comment]
> Mancano i consensi al cittadino, potete inviarli?

ci sono:
{
"sub":"BLRNDR68L13G920R^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
"subject_role":"AAS",
"purpose_of_use":"TREATMENT",
"locality":"090",
"patient_consent":true,
"action_id":"CREATE",
"resource_hl7_type":"('11502-2^^2.16.840.1.113883.6.1')",
"attachment_hash":"a33d3d415804fb3a8813363702680fe93681065f4abe4ef5808b6e1e90d88ec6",
"person_id":"RMSLSO31M04Z404R^^^&2.16.840.1.113883.2.9.4.3.2&ISO"
}

da cui abbiamo create l'hash:
ewoic3ViIjoiQkxSTkRSNjhMMTNHOTIwUl5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIiwKInN1YmplY3Rfcm9sZSI6IkFBUyIsCiJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsCiJsb2NhbGl0eSI6IjA5MCIsCiJwYXRpZW50X2NvbnNlbnQiOnRydWUsCiJhY3Rpb25faWQiOiJDUkVBVEUiLAoicmVzb3VyY2VfaGw3X3R5cGUiOiIoJzExNTAyLTJeXjIuMTYuODQwLjEuMTEzODgzLjYuMScpIiwKImF0dGFjaG1lbnRfaGFzaCI6ImEzM2QzZDQxNTgwNGZiM2E4ODEzMzYzNzAyNjgwZmU5MzY4MTA2NWY0YWJlNGVmNTgwOGI2ZTFlOTBkODhlYzYiLAoicGVyc29uX2lkIjoiUk1TTFNPMzFNMDRaNDA0Ul5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIgp9

**Comment by pFonziSogei** [comment]
Quella è la presa in carico. Parlavo dei consensi classici del fascicolo, quelli che si danno con la comunicazione consensi (C1, C2 e C3)

**Comment by rserrano73** [comment]
> Quella è la presa in carico. Parlavo dei consensi classici del fascicolo, quelli che si danno con la comunicazione consensi (C1, C2 e C3)

Ok, come possiamo provvedere a rettificare questa informazione?

**Comment by rserrano73** [comment]
> Con il servizio di Comunicazione Consensi contenuti nelle specifiche di interoperabilità. Per velocizzare lo abbiamo fatto eccezionalmente noi, per i prossimi sprint assicuratevi di avere la possibilità di comunicare i consensi

grazie mille per il supporto

**Comment by pFonziSogei** [comment]
Su INI riceviamo la seguente risposta da 090:

<soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"><soapenv:Header/><soapenv:Body><ns3:RegistryResponse status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure" xmlns:ns6="urn:hl7-org:v3" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns4="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0"><ns3:RegistryErrorList><ns3:RegistryError codeContext="Parallel processing failed for number 0. Exchange[ID-rt-sanita-tc11-s1-rt-tix-it-56414-1707909440455-2-1806]. Caused by: [java.lang.reflect.InvocationTargetException - null]" errorCode="XDSRegistryError" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"/></ns3:RegistryErrorList></ns3:RegistryResponse></soapenv:Body></soapenv:Envelope>

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto riscontri, il presente ticket viene chiuso. 
Può procedere alla riapertura nel caso in cui abbia bisogno di ulteriore supporto. 
Grazie.
