### ISSUE TITLE
Problema Servizio Notifica INI verso RDE - Regione Emilia-Romagna

### ISSUE THREAD

**Issue by xenergy33** [ministero-salute/it-fse-support#718]
Segnaliamo che anche noi di Regione Emilia-Romagna non riceviamo le notifiche che INI dovrebbe provvedere ad inoltrare alla RDE, per comunicare la corretta creazione (anche nel caso di RDE=RDA). 
Per sapere lo stato della transazione utilizziamo il servizio per recuperare lo stato. Si veda anche la segnalazione #702 della Regione Lombardia. Per verificare l'esito della creazione invochiamo a tentativi il servizio di verifica stato. 
Il WII del documento è: 2.16.840.1.113883.2.9.2.80.3.1.4.4.b541dcce44fa3dd14414d4f34b5a349827bc26e09539418835bb83bc8cb3c201.a702de1d7c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

In allegato il PDF.

Restiamo in attesa di un riscontro.
 
[Lab_crashtest.pdf](https://github.com/ministero-salute/it-fse-support/files/14849444/Lab_crashtest.pdf)

**Comment by pFonziSogei** [comment]
Salve, la problematica della Notifica è stata sbloccata. Potete effettuare un nuovo test?

**Comment by vigliottim** [comment]
Grazie per il suo gentile feedback.
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per ulteriori richieste di supporto.
