### ISSUE TITLE
Errore query di recupero riferimenti per replace 

### ISSUE THREAD

**Issue by daniele-gubellini** [ministero-salute/it-fse-support#719]
Buongiorno,

in modo analogo alla issue #692 , anche la richiesta di recupero riferimenti propedeutico alla sostituzione ci sembra anomalo: l'identificativo del documento da sostituire è stato inserito in uno slot $XDSDocumentEntryEntryUUID invece che $XDSDocumentEntryUniqueId.  Per noi questo è un problema bloccante anche per la sostituzione.

**Comment by pFonziSogei** [comment]
Potrebbe girarci il traceID e/o alcuni dettagli del test? Grazie

**Comment by daniele-gubellini** [comment]
Il traceid ottenuto durante la richiesta di replace è **352debf1c520e5c6**
Il nuovo documento ha codice  '2.16.840.1.113883.2.9.2.80.4.4^105800053001000124TESTLAB3593695' 
Il documento sostituito ha codice  '2.16.840.1.113883.2.9.2.80.4.4^105800053001000124TESTLAB7970033' (la query viene fatta quindi con questo valore)

**Comment by pFonziSogei** [comment]
Salve, abbiamo introdotto una fix che risolve la problematica. Potete effettuare un test?

**Comment by daniele-gubellini** [comment]
Buongiorno, ora la richiesta di INI mi sembra corretta:  query di tipo ObjectRef e il codice del documento nello slot XDSDocumentEntryUniqueId
