### ISSUE TITLE
VPS - incongruenza tra specifiche e schematron

### ISSUE THREAD

**Issue by marcokappa** [ministero-salute/it-fse-support#72]
Nel documento di specifiche [HL7IT-IG_CDA2_VPS-v1.1.1-S.pdf](http://www.hl7italia.it/sites/default/files/Hl7/SuperUser/docs/pubblicati/IG-CDA2-VPS/1.1.1/HL7IT-IG_CDA2_VPS-v1.1.1-S.pdf), riguardante il CDA2 del Verbale di PS, si riporta a pag. 28:

> Anche l'elemento <setId>, come l'elemento <id>, DEVE essere globalmente unico. È
> CONSIGLIATO, pertanto, valorizzare, alla prima creazione del documento, i campi <setId>
> e <id> allo stesso modo, modificando successivamente nelle diverse revisioni solo
> l'elemento <id> con un nuovo IUD e lasciando costante il valore dell'elemento <setId>

Si noti il termine “**CONSIGLIATO**”.

Nel CDA2 in allegato, riguardante un verbale di versione 1, gli elementi di `<id`> e `<setId>` hanno valori diversi, rispettivamente `SEI_24830810_1` e `SEI_24830810`.

Pur non avendo infranto la specifica, la validazione rispetto allo schematron fornisce il seguente errore:

`ERRORE-8| Se ClinicalDocument.id e ClinicalDocument.setId usano lo stesso dominio di identificazione (@root identico) allora l’attributo @extension del\n\t\t\tClinicalDocument.id deve essere diverso da quello del ClinicalDocument.setId a meno che ClinicalDocument.versionNumber non sia uguale ad 1; cioè i valori di setId ed id per un documento clinico possono coincidere solo per la prima versione di un documento`

Si noti che anche nel messaggio d’errore, si riporta “i valori di setId ed id per un documento clinico **possono** coincidere solo per la prima versione di un documento”.

In altri termini si dice che l’extension di ID e SETID devono essere diversi in generale, ma possono coincidere solamente per la prima versione del documento;  quindi se sono diversi sempre la specifica **dovrebbe essere rispettata**.

[cda2_Test1_Doc_Vers_1.txt](https://github.com/ministero-salute/it-fse-support/files/10491210/cda2_Test1_Doc_Vers_1.txt)

**Comment by Ser-ena** [comment]
Buonasera, in conformità alla regola CONF-VPS-16 riportata a pagina 28: Se l'elemento <ClinicalDocument>/<relatedDocument> manca (ovvero nella prima versione del documento)
l'attributo <ClinicalDocument>/<setId>/@root DEVE essere valorizzato come 
425 <ClinicalDocument>/<id>/@root, l'attributo @extension come 
<ClinicalDocument>/<id>/@extension, l'attributo @assigningAuthorityName come 
<ClinicalDocument>/<id>/@assigningAuthorityName.  Pertanto gli elementi di <id> e <setId>, in questo caso, devono avere valori identici

**Comment by IStacchiotti** [comment]
Non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
