### ISSUE TITLE
Domande per accreditamento nuovo software

### ISSUE THREAD

**Issue by ZucchettiCentroSistemi** [ministero-salute/it-fse-support#721]
Buongiorno,

abbiamo caricato i file dei test per ottenere l'accreditamento per l' applicativo dei trasfusionali JAB0.
Avevo compilato il questionario su "https://ec.europa.eu/eusurvey/runner/FSE-raccolta-id-applicativo"  in data : "25/01/2024 10:09:09" dicendo che avrei previsto di terminare i test in data 31/03/24. 
Devo ricompilare il questionario per far correggere i test oppure non è necessario?
Colgo l'occasione per chiedervi se il "Questionario per richiesta accreditamento applicativo FSE 2.0" vi risulta arrivato (anche se ho la copia della richiesta inviata in pdf) e se i test sono stati caricati correttamente nella nostra path : "https://github.com/ZucchettiCentroSistemi/it-fse-accreditamento/tree/main/GATEWAY/A1%23111ZUCCHETTIXX/Zucchetti_Centro_Sistema_s.p.a/JAB0/v.9".

Ringraziandovi anticipatamente per la vostra collaborazione, 
Cordiali Saluti.

**Comment by vigliottim** [comment]
Buongiorno,
 
Le confermiamo che il questionario per la richiesta di accreditamento risulta correttamente sottomesso e che non è necessario compilarne uno nuovo. 
Confermiamo, inoltre, che la pull-request è stata correttamente aperta. 
Tuttavia, al suo interno è stato caricato un solo file, come mostra il seguente screenshot:
 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/e342f1a1-85bc-490e-b972-39903793ae98)

Come riportato al link: https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#procedura-di-caricamento-dei-risultati, per procedere con le verifiche della pull-request è necessario che carichiate i seguenti file:
 
- file data.json contenente i riferimenti di tracciatura dei risultati dei test;
- file pdf usati nelle invocazioni dei servizi (all'interno della directory FILES);
- in caso di validazione, se pertinente (il software ha la funzionalità di firma e la firma è oggetto di adeguamento), i file pdf utilizzati nell'invocazione dei servizi firmati PADES (all'interno della directory FILES/SIGNED);
- file riassuntivo (foglio di calcolo) report-checklist.xlsx di tutti i test case eseguiti.
 
Rimaniamo in attesa di una commit da parte vostra.
Grazie.

**Comment by ZucchettiCentroSistemi** [comment]
Buongiorno,

grazie per la risposta.
Non mi risulta che non siano stati caricati i vari file. Questo è quanto vedo io dalla schermata :
![Screenshot 2024-04-04 101735](https://github.com/ministero-salute/it-fse-support/assets/128477871/b4965fed-89e2-4fb0-9692-fe58582b96fb)
presente al link : https://github.com/ZucchettiCentroSistemi/it-fse-accreditamento/tree/main/GATEWAY/A1%23111ZUCCHETTIXX/Zucchetti_Centro_Sistema_s.p.a/JAB0/v.9

**Comment by vigliottim** [comment]
Buongiorno,
i file mostrati nello screenshot sono stati committati unicamente in locale sul vostro repository e per questo motivo non compaiono all'interno della pull-request: https://github.com/ministero-salute/it-fse-accreditamento/pull/1312. 
Pertanto, le chiediamo di eseguire una commit correttiva al fine di inserire tutti file necessari per il processo di accreditamento all'interno della pull request #1312. Grazie

**Comment by ZucchettiCentroSistemi** [comment]
Perfetto grazie.
Ho creato la nuova pull request numero 1319, dovrei aver caricato i vari file presenti al link : https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#procedura-di-caricamento-dei-risultati.
Vi chiedo se adesso risultano correttamente "inviati" con la nuova pull request.

Ringraziando in anticipo, grazie ancora!

**Comment by vigliottim** [comment]
Grazie, le confermiamo che la pull-request 1319 è stata correttamente creata con tutti i file necessari.
Riceverà l'esito delle elaborazioni via e-mail nel giro di qualche giorno lavorativo.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
