### ISSUE TITLE
CRASH PROGRAM - Regione Lombardia: Servizi "Regime di mock abilitato" su INI per scenari UC9 e UC11

### ISSUE THREAD

**Issue by EugenioGuagliardi** [ministero-salute/it-fse-support#722]
Segnaliamo che gli scenari di test C9_ValidazionePubblicazioneCreazioneContestuale e UC11_ValidazionePubblicazioneSostituzioneContestuale rileviamo "Regime di mock abilitato" 

per UC9 workflowInstanceId" : "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.4770d20a40^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

...
STATUS WORKFLOW
{
    "traceID": "f7d6112480ccd181",
    "spanID": "5edb9c2d590635af",
    "transactionData": [{
            "eventType": "VALIDATION_FOR_PUBLICATION",
            "eventDate": "2024-04-03T13:54:54.376+00:00",
            "eventStatus": "SUCCESS",
            "subject": "PRPSSO80T15F205H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.4770d20a40^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "745cd7048c025f2a",
            "issuer": "integrity:S1#030000000000XX",
            "expiringDate": "2025-04-03T13:54:54.387+00:00"
        }, {
            "eventType": "PUBLICATION",
            "eventDate": "2024-04-03T13:54:55.229+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.8af3a2a4-f1c1-11ee-a9d8-0242a89a8ac7",
            "subject": "PRPSSO80T15F205H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "ERP",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.4770d20a40^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "745cd7048c025f2a",
            "issuer": "integrity:S1#030000000000XX",
            "expiringDate": "2025-04-03T13:54:55.241+00:00"
        }, {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-04-03T13:54:55.485+00:00",
            "eventStatus": "SUCCESS",
            "message": "Regime di mock abilitato",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.4770d20a40^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-04-03T13:54:55.560+00:00"
        }, {
            "eventType": "SEND_TO_EDS",
            "eventDate": "2024-04-03T13:54:55.798+00:00",
            "eventStatus": "SUCCESS",
            "message": "{\"esito\":true}",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.4770d20a40^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-04-03T13:54:55.862+00:00"
        }, {
            "eventType": "EDS_WORKFLOW",
            "eventDate": "2024-04-03T14:00:00.038+00:00",
            "eventStatus": "SUCCESS",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.4770d20a40^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-04-03T14:00:00.064+00:00"
        }
    ]
}
...

per UC11 workflowInstanceId" :
2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.43d1db9cdb^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

STATUS WORKFLOW
...
{ 
   "traceID": "8eaffe6ca6e5a375",
    "spanID": "1fc1801e43b72e99",
    "transactionData": [{
            "eventType": "VALIDATION_FOR_REPLACE",
            "eventDate": "2024-04-03T14:49:20.618+00:00",
            "eventStatus": "SUCCESS",
            "subject": "PRPSSO80T15F205H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.43d1db9cdb^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "d72d601e1d9d442d",
            "issuer": "integrity:S1#030000000000XX",
            "expiringDate": "2025-04-03T14:49:20.629+00:00"
        }, {
            "eventType": "REPLACE",
            "eventDate": "2024-04-03T14:49:21.565+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.f9f30fd0-f1c8-11ee-a9d8-0242a89a8ac7",
            "subject": "PRPSSO80T15F205H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "ERP",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.43d1db9cdb^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "d72d601e1d9d442d",
            "issuer": "integrity:S1#030000000000XX",
            "expiringDate": "2025-04-03T14:49:21.575+00:00"
        }, {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-04-03T14:49:21.739+00:00",
            "eventStatus": "SUCCESS",
            "message": "Regime di mock abilitato", 
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.43d1db9cdb^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-04-03T14:49:21.748+00:00"
        }, {
            "eventType": "SEND_TO_EDS",
            "eventDate": "2024-04-03T14:49:21.961+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "404 : \"{\"traceID\":\"ae5bed03c14ca0a7\",\"spanID\":\"3cdeaae094ffbd9e\",\"type\":\"/err/resource\",\"title\":\"Resource error\",\"detail\":\"Error: document not found!\",\"status\":404,\"instance\":\"/not-found\"}\"",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.43d1db9cdb^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-04-03T14:49:22.021+00:00"
        }
    ]
}
...

Questi test (che sono stati anche inseriti negli excel dello sprint1) sono da ritenersi completi oppure devono essere ripetuti dopo aver tolto il regime di Mock?

Grazie

**Comment by amarconS** [comment]
Salve,

analizzando le chiamate sembra che state utilizzando il vecchio certificato della regione Lombardia "S1#030000000000XX".

Per fare le chiamate fuori dal regime di mock vi chiediamo di utilizzare i certificati chi vi abbiamo fornito per il crash program.
I nuovi certificati ci risultato essere stati inviati tramite email "fse_support@sogei.it" il giorno mercoledì 20/03/2024 alle 17:30.

**Comment by EugenioGuagliardi** [comment]
Buongiorno, abbiamo verificato ed in questi scenari (UC9 e UC11) effettivamente non avevamo cambiato il certificato, effettuando un nuovo test con il nuovo certificato otteniamo un esito positivo.
Grazie per la collaborazione.
