### ISSUE TITLE
CRASH PROGRAM - Regione Lombardia : Caso d'uso UC11_ValidazionePubblicazioneSostituzioneContestuale

### ISSUE THREAD

**Issue by EugenioGuagliardi** [ministero-salute/it-fse-support#723]
Buongiorno, ricollegandoci alla issue #722 indichiamo che dopo una attenta analisi sui dati inviati riscontriamo una incongruenza rispetto alle specifiche AGID 2.5 che vorremmo chiarire.

workflowInstanceId del test :
2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.56cab676dd^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

MessageID: 8581edd3-7bd0-4f1c-a4c4-327c53182152

Osservazioni sul servizio Comunicazione Metadati per registrazione documento aggiornato:

**Asserzione**:

- Action-id: viene valorizzato con ‘CREATE’ invece di ‘UPDATE’

**Nel BODY**

**ExtrinsicObject**: 

- Gli slot dell’autore dovrebbero essere presenti solo nei propri blocchi Classification invece sono presenti anche direttamente nel tag ExtrinsicObject

**Association:**

- Non è presente il blocco Association [HasMember]
- Il blocco SubmissionSetStatus, valorizzato con ‘Original’ è presente nel blocco Association [RPLC] invece di essere nel blocco Association [HasMember], in questo caso assente

Potete cortesemente verificare se le nostre osservazioni sono corrette oppure sbagliamo Noi ad interpretare le specifiche Agid?

Grazie

**Comment by EugenioGuagliardi** [comment]
inserisco il WORKFLOW STAUS della transazione
...
{
    "traceID": "b60f09314405b106",
    "spanID": "d28d700ebe6dedc5",
    "transactionData": [
        {
            "eventType": "VALIDATION_FOR_REPLACE",
            "eventDate": "2024-04-05T07:28:35.546+00:00",
            "eventStatus": "SUCCESS",
            "subject": "KRNBRS58M08B236S^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.56cab676dd^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "176b208df626d58e",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-04-05T07:28:35.557+00:00"
        },
        {
            "eventType": "REPLACE",
            "eventDate": "2024-04-05T07:28:41.596+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.eaf00b18-f31d-11ee-a9d8-0242a89a8ac7",
            "subject": "KRNBRS58M08B236S^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "ERP",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.56cab676dd^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "176b208df626d58e",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-04-05T07:28:41.605+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-04-05T07:28:45.511+00:00",
            "eventStatus": "SUCCESS",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.56cab676dd^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-04-05T07:28:45.570+00:00"
        },
        {
            "eventType": "SEND_TO_EDS",
            "eventDate": "2024-04-05T07:28:45.659+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "404 : \"{\"traceID\":\"e01ebdcdfc043e66\",\"spanID\":\"180073fcc2b6d1c5\",\"type\":\"/err/resource\",\"title\":\"Resource error\",\"detail\":\"Error: document not found!\",\"status\":404,\"instance\":\"/not-found\"}\"",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.56cab676dd^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-04-05T07:28:45.813+00:00"
        }
    ]
}
...

**Comment by pFonziSogei** [comment]
Buonasera,

introdurremo una fix per risolvere le problematiche segnalate, che riporto di seguito:

1)Asserzione:
Action-id: viene valorizzato con ‘CREATE’ invece di ‘UPDATE’
Nel BODY
2)ExtrinsicObject:
Gli slot dell’autore dovrebbero essere presenti solo nei propri blocchi Classification invece sono presenti anche direttamente nel tag ExtrinsicObject
3)Association:
Non è presente il blocco Association [HasMember]
Il blocco SubmissionSetStatus, valorizzato con ‘Original’ è presente nel blocco Association [RPLC] invece di essere nel blocco Association [HasMember]

**Comment by Ser-ena** [comment]
Buonasera, è stata rilasciata una modifica, è possibile riprovare

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto riscontri, procediamo alla chiusura del presente ticket. Sarà possibile procedere con la riapertura nel caso in cui fosse necessario ulteriore supporto, grazie.
