### ISSUE TITLE
Crash Program | Recupero Riferimenti Documento

### ISSUE THREAD

**Issue by EugenioGuagliardi** [ministero-salute/it-fse-support#725]
Buongiorno,
nel test case UC11_ValidazionePubblicazioneSostituzioneContestuale, precisamente negli step 2 e 3 relativi a quando il Gateway e successivamente INI devono effettuare il "Recupero Riferimenti" rileviamo delle incongruenze che vorremmo verificare.

di seguito le incongruenze rilevate per il servizio recupero riferimenti documento.

Chiamata analizzata:
•	Servizio: Recupero Riferimenti Documento
•	Caso d’uso: aggiornamento per sostituzione
•	Data ora: 2024-04-05 09:28:38:584
•	MessageID: 6249e43f-1095-4e2a-ad1a-ab5f3ecc4d21

Asserzione:
purposeofuse: viene valorizzato con ‘TREATMENT’ invece di ‘UPDATE’

Body - Slot $XDSDocumentEntryUniqueId:
Nel valore passato, non è presente l’OID della regione di creazione: 
Valore passato: ('030703.RRDOCU.eaf00b18-f31d-11ee-a9d8-0242a89a8ac7')
Valore atteso: (‘2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.eaf00b18-f31d-11ee-a9d8-0242a89a8ac7')

di seguito il workflowInstanceId:
2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.56cab676dd^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

Grazie per la collaborazione.

**Comment by pFonziSogei** [comment]
Per la parte dell'Asserzione introdurremo una fix migliorativa. Per XDSDocumentEntryUniqueId da una prima analisi ci aspetteremmo che fosse la regione chiamante a popolare il valore direttamente con 2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.eaf00b18-f31d-11ee-a9d8-0242a89a8ac7 nella request (Il Gateway poi ribalta il valore nel metadato

**Comment by Ser-ena** [comment]
Buonasera, è stata rilasciata una modifica, è possibile riprovare
