### ISSUE TITLE
XDSDocumentEntry.typeCode -100971-1 Cartella Clinica

### ISSUE THREAD

**Issue by EorruSardIT** [ministero-salute/it-fse-support#726]
Buon pomeriggio,

nell'ambito dei test di consultazione dei FSE da parte dei sw di CC MMG/PLS, in ambiente di collaudo, stiamo riscontrando degli errori impostando come filtro di ricerca per tipologia documento: Cartella Clinica Ospedaliera.

Il codice passato nella request è quello previsto nella versione 2.5 dell’Affinity Domain: 100971-1.

l'errore ricevuto è: wrong attribute value of $typeurn$

Potete supportarci?

Grazie

**Comment by vigliottim** [comment]
Buonasera, le chiediamo gentilmente di indicarci se si sta interfacciando con FSE 1.0 oppure FSE 2.0 e di fornirci le seguenti informazioni:
- endpoint della chiamata
- request e response completa
Grazie.

**Comment by EorruSardIT** [comment]
Buongiorno,

L'endpoint richiamato è quella della ITI18 ovvero:
https://apigw2-test-fse.sardegnasalute.it/documentregistry/1<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fapigw2-test-fse.sardegnasalute.it%2Fdocumentregistry%2F1&e=6df20d48&h=dbcb9ccc&f=y&p=n>

le request sono quelle in allegato.

Grazie

Saluti

Elena


Elena Orrù
Servizio Progettazione Sanità

[Immagine che contiene Elementi grafici, grafica, testo, Carattere  Descrizione generata automaticamente]
cell. +39 3316171041
***@***.******@***.***>

via Dei Giornalisti 6, 09122 Cagliari
www.sardegnait.it

“Messaggio riservato attinente l’attività di Sardegna IT e contenente informazioni di natura professionale. Le eventuali risposte potranno essere conosciute da altri soggetti nell’ambito dell’organizzazione del mittente. Se ricevuto per errore, o non delegati dal destinatario, Vi preghiamo di comunicarcelo e di eliminarlo definitivamente”.

Da: Michela Vigliotti ***@***.***>
Inviato: venerdì 5 aprile 2024 17:42
A: ministero-salute/it-fse-support ***@***.***>
Cc: Elena Orrù ***@***.***>; Author ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] XDSDocumentEntry.typeCode -100971-1 Cartella Clinica (Issue #726)

Questa è la prima volta che ricevi un'email da questo mittente. Assicurati che sia qualcuno di cui ti fidi.

Buonasera, le chiediamo gentilmente di indicarci se si sta interfacciando con FSE 1.0 oppure FSE 2.0 e di fornirci le seguenti informazioni:

  *   endpoint della chiamata
  *   request e response complete
Grazie.

—
Reply to this email directly, view it on GitHub<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fministero-salute%2Fit-fse-support%2Fissues%2F726%23issuecomment-2040125291&e=6df20d48&h=efeb376d&f=y&p=n>, or unsubscribe<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FBHTRLXDCXS264MQZ6G6GQUDY33A4NAVCNFSM6AAAAABFZHKAS2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBQGEZDKMRZGE&e=6df20d48&h=4be62602&f=y&p=n>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

--
Messaggio analizzato da Libraesva ESG.
Segnala come spam.<http://mxer2.regione.sardegna.it/action/32B1740138.A30EB/learn-spam>
Mettilo in blacklist.<http://mxer2.regione.sardegna.it/action/32B1740138.A30EB/blacklist>

**Comment by LucaRogledi** [comment]
Buongiorno, 
Non sono visilibili gli allegati, potrebbe gentilmente inserirli tramite GitHub?
Grazie.

**Comment by EorruSardIT** [comment]
Certo,

ecco gli allegati:
[Request CC Ospedaliera.zip](https://github.com/ministero-salute/it-fse-support/files/14904379/Request.CC.Ospedaliera.zip)

Saluti

Elena

**Comment by vigliottim** [comment]
Buon pomeriggio, la invitiamo a inoltrare la sua richiesta di supporto alla seguente mail: [gestionets@sogei.it](mailto:gestionets@sogei.it).
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
