### ISSUE TITLE
Comportamento diverso rispetto alle specifiche, servizio sostituzione documento Regione Emilia-Romagna

### ISSUE THREAD

**Issue by xenergy33** [ministero-salute/it-fse-support#727]
Rileviamo una modifica dei valori dei campi action ID e purpose_of_use nel servizio di sostituzione di un documento, nelle specifiche è richiesto l'utilizzo dei valori CREATE nel primo campo e TREATMENT nel secondo, invece adesso viene accettato solo UPDATE per entrambi.
![image](https://github.com/ministero-salute/it-fse-support/assets/103534714/a9806804-657e-4e73-8313-832322758900)
![image](https://github.com/ministero-salute/it-fse-support/assets/103534714/3d9b79c4-4a36-4c90-8c14-3649aea746ef)

**Comment by IStacchiotti** [comment]
Buonasera, le confermiamo che è stata aggiornata la [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#6-servizio-di-sostituzione-documento). Chiudiamo pertanto il presente e rimaniamo a disposizione in caso di ulteriori segnalazioni.
