### ISSUE TITLE
Aggiornamento file report-checklist.xlsx

### ISSUE THREAD

**Issue by mghi-sined** [ministero-salute/it-fse-support#729]
Buongiorno,
ho aggiornato il file report-checklist.xlsx come da voi richiesto, aggiungendo le indicazioni a colonna P per i test 45 e 48 .
Poichè non utilizzo abitualmente GITHUB, spero che l'aggiornamento sia andato a buon fine.
Questi sono i dati che identificano la procedura in validazione:

- commonName auth: A1#111SINEDXX
- subject_application_vendor: Sined S.r.l.
- subject_application_id: MedWare
- subject_application_version: 24.02.12

Grazie.
Massimo Ghirardello

**Comment by vigliottim** [comment]
Buon pomeriggio, la ringraziamo per il suo gentile feedback.
La informiamo che le modifiche correttive sono state ricevute, riceverà gli esiti delle elaborazioni via e-mail nel giro di qualche giorno lavorativo.
Chiudiamo il presente ticket e rimaniamo a disposizione per ulteriori richieste di supporto.
