### ISSUE TITLE
Error Validation CDA with tag <RelatedDocument>

### ISSUE THREAD

**Issue by ruggj** [ministero-salute/it-fse-support#73]
In vase di validazione CDA2 si verifica un errore in caso di CDA di REPLACE  In particolare il problema è sul tag sul tag <RelatedDocument>. Dopo vari tentativi abbiamo scoperto l'errore era dovuto alla posizione del tag <relatedDocument>: va posto sotto il tag <inFulfillmentOf> prima di <component>. In questo modo: 
```
<inFulfillmentOf>
	<order>
	<id root="2.16.840.1.113883.2.9.4.3.9" extension="null" assigningAuthorityName="Ministero delle Finanze"/>
	<priorityCode code="R" codeSystem="2.16.840.1.113883.5.7" codeSystemName="Hl7 ActPriority"/>
	</order>
</inFulfillmentOf>
<relatedDocument typeCode="RPLC">
	<parentDocument>
		<id root="2.16.840.1.113883.2.9.2.10.4.1" extension="2.16.840.1.113883.2.9.2.10.4.1_246465323" assigningAuthorityName="Regione Piemonte"/>
		<setId root="2.16.840.1.113883.2.9.2.10.4.1" extension="2.16.840.1.113883.2.9.2.10.4.1_24646531" assigningAuthorityName="Regione Piemonte"/>
		<versionNumber value="24"/>
	</parentDocument>
</relatedDocument>
```

Si allega xml del CDA corretto e del CDA errato
[Cda_corretto_tag_RelatedDocument.txt](https://github.com/ministero-salute/it-fse-support/files/10500195/Cda_corretto_tag_RelatedDocument.txt)
[Cda_errato_tag_RelatedDocument.txt](https://github.com/ministero-salute/it-fse-support/files/10500196/Cda_errato_tag_RelatedDocument.txt)

**Comment by Ser-ena** [comment]
Buonasera, ci conferma che la problematica da analizzare non è relativa alla descrizione di cui sopra, ma a quanto riportato "Il Gateway ci risponde col seguente errore:   "detail": "ERROR: -1,-1 cvc-complex-type.2.4.a: Invalid content was found starting with element 'relatedDocument'. One of '{\"urn:hl7-org:v3\":copyTime, \"urn:hl7-org:v3\":recordTarget}' is expected.
Abbiamo provato ad aggiugnere i due elementi richiesti "copyTime" e "recordTarget" ma dà altri errori. Dalle specifiche il formato e contenuto del tag <relatedDocument> non è chiaro. Riusciresti a dare una mano ? Grazie anticipatamente". Inoltre ci conferma che il CDA che sta dando l'errore è quello Cda_corretto_tag_RelatedDocument.txt

**Comment by Ser-ena** [comment]
Buonasera, come da documentazione "https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/LAB.xml" il tag <inFulfillmentOf> deve essere posto prima del tag <relatedDocument>. Modificando l'ordine si genera l'errore poichè non conforme alla struttura del documento.

**Comment by IStacchiotti** [comment]
Non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
