### ISSUE TITLE
Documento non trovato in procedura di pubblicazione e sostituzione

### ISSUE THREAD

**Issue by lucaerrani** [ministero-salute/it-fse-support#730]
Buongiorno, abbiamo un problema in fase di sostituzione di un documento.

Pubblichiamo un documento precedentemente validato e otteniamo correttamente il workflowInstanceId

```
2.16.840.1.113883.2.9.2.80.3.1.4.4.b23570567a83b6a6f630734d8c33d291f7ea5d4c4bcc71b6115ef232bdd591c9.56e06c64ef^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
```

La chiamata alla get status per workflowInstanceId comunica che è andato tutto a buon fine, ma provando a sostituire il documento, riceviamo l'errore:

```json
{
  "traceID":"75ff9b261c1a9308",
  "spanID":"75ff9b261c1a9308",
  "type":"/msg/record-not-found",
  "title":"Record non trovato.",
  "detail":"No Record Found",
  "status":404,
  "instance":"/record-not-found"
}
```

La validazione del documento sostitutivo avviene correttamente con workflowInstanceId

```
2.16.840.1.113883.2.9.2.80.3.1.4.4.b23570567a83b6a6f630734d8c33d291f7ea5d4c4bcc71b6115ef232bdd591c9.4255aa54c2^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
```

Cosa stiamo sbagliando?

**Comment by IStacchiotti** [comment]
Buonasera, dalle analisi sono emersi i seguenti due errori:
1.  l'errore "No Record Found" è dovuto al fatto che nell'url dell'invocazione 
(`[PUT] https:..../v1/documents/2.16.840.1.113883.2.9.2.90.4.4%5E9ed26556-ccdd-4b96-924d-54d543a9eb1b`) non è stato referenziato correttamente l'identificativo del documento pubblicato in precedenza (9ed26556-ccdd-4b96-924d-54d543a9eb1b): la stringa iniziale infatti "2.16.840.1.113883.2.9.2.90.4.4%5E" non è inclusa nell'id del documento da sostituire

2. l'identificativo del documento da sostituire dichiarato in pubblicazione non rispetta le specifiche tecniche riportate in documentazione al [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway): 
<img width="478" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/122798799/96248ad2-4ac0-4722-ac8c-2df252f4f6fe">

Rimaniamo a disposizione per chiarimenti

**Comment by lucaerrani** [comment]
Buonasera,
Grazie mille della risposta. 
Quindi avevamo sbagliato nell'invocare l'endpoint di CREAZIONE fornendo come ID solo il GUID invece che OID^GUID, ho capito bene?

Verifichiamo subito

**Comment by IStacchiotti** [comment]
Corretto, se aveste utilizzato la convenzione riportata in documentazione, la sostituizione sarebbe andata a buon fine (l'id del doc da sostituire deve coincidere a quello dichiarato in pubblicazione). A disposizione per chiarimenti.

**Comment by lucaerrani** [comment]
Verificato e corretto, grazie mille della disponibilità, chiudo l'issue
