### ISSUE TITLE
Comunicazione Metadati - campo HealthcareFacilityTypeCode

### ISSUE THREAD

**Issue by daniele-gubellini** [ministero-salute/it-fse-support#733]
Buongiorno,

ci siamo accorti di un errore nel messaggio di comunicazione che riceviamo da INI che ha impatti significativi sulla capacità di interpretare il dato (come se non fosse stato trasmesso)

```
 <ns2:Classification 
classificationScheme="urn:uuid:f33fb8ac-18af-42cc-ae0eed0b0bdb91e1" 
classifiedObject="Documento01"
id="IdHealthcareFacilityTypeCode" 
nodeRepresentation="Ospedale" 
objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification">
            <ns2:Slot name="codingScheme">
              <ns2:ValueList>
                <ns2:Value>2.16.840.1.113883.2.9.3.3.6.1.1</ns2:Value>
              </ns2:ValueList>
            </ns2:Slot>
            <ns2:Name>
              <ns2:LocalizedString charset="UTF-8" value="Ospedale" xml:lang="en-US"/>
            </ns2:Name>
</ns2:Classification>
```

L'attributo classificationScheme dovrebbe essere valorizzato con  **urn:uuid:f33fb8ac-18af-42cc-ae0e-ed0b0bdb91e1**  (manca un trattino)

**Comment by IStacchiotti** [comment]
Buonasera, potrebbe cortesemente riprovare? Rimaniamo a disposizione nel caso in cui l'errore dovesse persistere, grazie

**Comment by daniele-gubellini** [comment]
Confermo ora il dato arriva correttamente, grazi
