### ISSUE TITLE
Pubblicazione: mancata valorizzazione nome e cognome autore 

### ISSUE THREAD

**Issue by nspazzoli** [ministero-salute/it-fse-support#736]
Buongiorno,

a seguito dell'invio di un CDA di laboratorio dove invio i dati nel seguente modo

```
<author> 
		<time value="20240409150534+0200"/>
		<assignedAuthor classCode="ASSIGNED"> 
			<id root="2.16.840.1.113883.2.9.4.3.2" extension="MDCBGN54A01A944D" assigningAuthorityName="MEF"/> 
			<addr>
				<country>100</country>
				<state>120</state>
				<county>RM</county> 
				<city>Roma</city> 
				<censusTract>058091</censusTract> 
				<postalCode>00184</postalCode> 
				<streetAddressLine>Via Milano 7</streetAddressLine>
			</addr>
			<telecom use="HP" value="mailto:prova.provax@example.com"/> 
			<telecom use="WP" value="mailto:prova.provax@example.com"/> 
			<telecom use="MC" value="tel:3340000000"/>
			<assignedPerson>
				<name>
					<family>MEDICOPROVA</family>
					<given>BOLOGNA UNO</given>
					<prefix>Dr</prefix>
				</name>
			</assignedPerson>
			<representedOrganization>
				<id root="2.16.840.1.113883.2.9.4.1.1" extension="080105" assigningAuthorityName="Ministero della Salute"/>	
				<name>Ausl Bologna</name>
			</representedOrganization> 
		</assignedAuthor>

```

non li riceviamo in indicizzazione
```
<ns2:Slot name="authorPerson">
              <ns2:ValueList>
                <ns2:Value>MDCBGN54A01A944D^^^^^^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</ns2:Value>
              </ns2:ValueList>
            </ns2:Slot>
```

workflowInstaceId=2.16.840.1.113883.2.9.2.80.3.1.4.4.4cc0e55a6f76f6b72062439bbe9ced4d517f83702d1feb56d417f269c4ed11da.41ecde35f7^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
traceId = 90ca1abde2052aa2

Da specifiche sono opzionali, ma quando popolate non dovrebbero essere inviate?

Grazie

**Comment by IStacchiotti** [comment]
Buonasera, potreste fornirci la lista completa di campi attesi, per i quali non riceve l'indicizzazione?

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri procediamo alla chiusura del presente ticket. 
La invitiamo a riaprirlo nel caso in cui avesse bisogno di ulteriore supporto. Grazie.

**Comment by nspazzoli** [comment]
Buongiorno,

sulle specifiche io trovo queste indicaizoni

![immagine](https://github.com/ministero-salute/it-fse-support/assets/19858511/71c602b9-82c6-49f0-953f-1333dc8afccd)

**Comment by IStacchiotti** [comment]
Buonasera,
Dalle prove effettuate, valorizzando l'AuthorPerson come indicato di seguito:
<img width="686" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/122798799/f5c8e975-1ed3-49bd-b4b1-e44ada6f9aea">, 
si ottiene un errore da parte di INI: 
<img width="552" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/122798799/2dd4c834-d390-457a-b129-9aa2bac1c379">

Potrebbe gentilmente indicarci il formato atteso per l'AuthorPerson, riportando anche un esempio?
Segnaliamo che attualmente il formato con cui è valorizzato attualmente l’authorPerson deriva dall’IHE ITI-42

Grazie per la collaborazione.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
