### ISSUE TITLE
SEND_TO_INI :  Patient validation error

### ISSUE THREAD

**Issue by cdezorzi** [ministero-salute/it-fse-support#737]
Buonasera, stiamo effettuando il CRASH TEST - SPRINT2 per Regione Toscana 
dopo aver eseguito gli step di validazione e creazione del documento, andando ad eseguire il comando di status utilizzando il workflowistanceid otteniamo un messaggio di errore nell'"eventType": "SEND_TO_INI" 

{
    "traceID": "4e4894264f3c46dc",
    "spanID": "dea3a2371a70ab0a",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-04-09T13:30:43.785+00:00",
            "eventStatus": "SUCCESS",
            "subject": "BLRNDR68L13G920R^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "090",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.73aedbf26a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "4ef05ae664755f71",
            "issuer": "integrity:S1#090#090REGIONETOSCANA-TEST",
            "expiringDate": "2025-04-09T13:30:43.797+00:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-04-09T13:30:51.970+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.90.4.4^9999.LAB.910.9131",
            "subject": "BLRNDR68L13G920R^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "DIS",
            "organizzazione": "090",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.73aedbf26a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "b5a6cea3ebafde94",
            "issuer": "integrity:S1#090#090REGIONETOSCANA-TEST",
            "expiringDate": "2025-04-09T13:30:52.000+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-04-09T13:30:54.497+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "500 : \"{\"traceID\":\"00000000000000006bba573518d8a4ab\",\"spanID\":\"6bba573518d8a4ab\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: Patient validation error Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}\"",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.73aedbf26a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-04-09T13:30:54.636+00:00"
        }
    ]
}

potete darci un riscontro ?
Grazie

**Comment by cdezorzi** [comment]
Buonasera,
facendo una verifica sulla "Specifica di interoperabilità" abbiamo visto che è presente il codice di errore 
"PFC7   Patient validation error Questo errore è generato nel caso in cui fallisce l’operazione di identificazione del paziente. Quest’errore può essere generato dall’INI, nel caso in cui il sistemaTS/ANA non identifica il paziente."

Forse il CF TZZFNC70A02H501C utilizzato per il test non è stato censito ? 
Grazie

**Comment by vigliottim** [comment]
Buonasera, la informiamo che Gestione Ts ha assegnato l'RDA all'utente indicato ed è in attesa che vengano comunicati i consensi. Per concludere il censimento sarà necessario inviare i dati richiesti in risposta alla e-mail del thread. Grazie.

**Comment by OmarLorenzini** [comment]
abbiamo superato il problema grazie

**Comment by vigliottim** [comment]
Grazie a lei per il gentile riscontro.
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
