### ISSUE TITLE
Problema aggiornamento metadati

### ISSUE THREAD

**Issue by nspazzoli** [ministero-salute/it-fse-support#738]
Buongiorno,

sto provando un aggiornamento metadati di un documento precedentemente in indicizzato

```
PUT /govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.80.4.4%5E105LAB1712670035661LNB5CZ/metadata HTTP/1.1
sign paylod
{
  "jti": "2c1699bf-acb2-4125-b2d1-a3f904920c1b",
  "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
  "iat": 1712670146,
  "exp": 1712671946,
  "nbf": 1712670146,
  "iss": "integrity:S1#080#EMILIAROMAGNA",
  "sub": "MDCBGN54A01A944D^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "subject_role": "AAS",
  "purpose_of_use": "UPDATE",
  "locality": "080",
  "subject_organization_id": "080",
  "subject_organization": "Regione Emilia-Romagna",
  "patient_consent": true,
  "action_id": "UPDATE",
  "resource_hl7_type": "('11502-2^^2.16.840.1.113883.6.1')",
  "person_id": "CRSPGR01T01H501N^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "subject_application_id": "TEST_SOLE",
  "subject_application_vendor": "LEPIDA",
  "subject_application_version": "1"
}

BODY
{
    "tipologiaStruttura": "Ospedale",
    "tipoDocumentoLivAlto": "REF",
    "assettoOrganizzativo": "AD_PSC100",
    "tipoAttivitaClinica": "ERP",
    "identificativoSottomissione": "2.16.840.1.113883.2.9.2.80.4.3.202404091542151118107104361985145325",
    "administrativeRequest": ["SSN"]
}
```

Ottengo la seguente risposta:

```
HTTP 404, 
 {
     "traceID": "43f21614e58ed63c",
     "spanID": "43f21614e58ed63c",
     "type": "/msg/record-not-found",
     "title": "Record non trovato.",
     "detail": "IniException: Error while merge metadati:BusinessException: Error while perform build submit object request : ",
     "status": 404,
     "instance": ""
 }
```
 
In allegato la  nostra risposta ad una query di tipo getLeaf

[getleaf.txt](https://github.com/ministero-salute/it-fse-support/files/14919577/getleaf.txt)

Grazie

**Comment by cdezorzi** [comment]
REGIONE TOSCANA
Buongiorno, riscontriamo un errore a seguito di una richiesta di aggiornamento metadati di seguito errore
{
    "traceID": "6158489eb048d624",
    "spanID": "6158489eb048d624",
    "type": "/msg/record-not-found",
    "title": "Record non trovato.",
    "detail": "IniException: Error while merge metadati:BusinessException: Error while perform build submit object request : ",
    "status": 404,
    "instance": ""
}

URL PUT: https://apistage.regione.toscana.it/C02/rest/out/RegioneToscana/MinisteroSalute/FSEGateway/v1/documents/2.16.840.1.113883.2.9.2.90.4.4^9999.LAB.910.9135/metadata

Body
{
  "tipologiaStruttura": "Ospedale",
  "attiCliniciRegoleAccesso": [
    "90768-3"
  ],
  "tipoDocumentoLivAlto": "REF",
  "assettoOrganizzativo": "AD_PSC007",
  "dataInizioPrestazione": "20240306101120",
  "dataFinePrestazione": "20240306101120",
  "conservazioneANorma": "NO",
  "tipoAttivitaClinica": "ERP",
  "identificativoSottomissione": "2.16.840.1.113883.2.9.2.90907",
  "administrativeRequest": ["INPATIENT"]
}

Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
