### ISSUE TITLE
verifica documento

### ISSUE THREAD

**Issue by gruppomaxed** [ministero-salute/it-fse-support#739]
potete dirmi cosa non va,  se ottengo questa risposta dal servizio nel tentativo di verifica di un documento ? 

Response Status: BadRequest
Response Content: {"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"eddb35f5-f68a-11ee-93a7-005056ae54fa"}

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate sono emersi i seguenti errori:

- Il CDA2 iniettato ha encoding UTF-16, anziché UTF-8: 
`<?xml version="1.0" encoding="utf-16"?>`

**_Request:_**

- _As is:_ Content-Type: text/plain;        _To be:_ Content-Type: application/json;
- _As is:_ name=file; filename=CDA_OK.pdf; filename*=utf-8''CDA_OK.pdf
_To be:_ name="file"; filename="CDA_OK.pdf" Content-Type: application/pdf

La invitiamo a correggerli e riprovare.
Grazie.

**Comment by gruppomaxed** [comment]
ho provato a effettuare le modifiche proposte ma ho ancora
Response Content: {"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"7f608412-f72b-11ee-9223-005056ae7395"}

Response Status: BadRequest

potreste  darmi ulteriori suggerimenti ?
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno,
Le riportiamo di seguito quanto emerso dalle anailisi sulla chiamata ricevuta e la invitiamo ad effettuare le correzioni indicate e riprovare.
 
Riguardo la sezione requestBody:

**AS-IS:**
```
Content-Type: application/json; charset=utf-8
Content-Disposition: form-data; name="application/json"
Content-Length: 116
 
{
 "requestBody": {
   "healthDataFormat": "CDA",
   "mode": "ATTACHMENT",
   "activity": "VERIFICA"
 }
}
```

**TO-BE:**
```
Content-Disposition: form-data; name="requestBody"
Content-Type: application/json
Content-Transfer-Encoding: binary
 
{
 "healthDataFormat": "CDA",
 "mode": "ATTACHMENT",
 "activity": "VERIFICA"
} 
```
 
Riguardo la sezione di caricamento del documento pdf:
 
**AS-IS:**
```
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=file
Content-Length: 18464
 
Content-Disposition: form-data; name="file"; filename="CDA_OK.pdf" Content-Type: application/pdf
```

**TO-BE:**
```
Content-Disposition: form-data; name="file"; filename="CDA_OK.pdf"
Content-Type: application/pdf
Content-Transfer-Encoding: binary
```

Restiamo a disposizione per eventuali chiarimenti.
Grazie

**Comment by gruppomaxed** [comment]
purtroppo ho ancora Response Content: {"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"b950aa80-f81f-11ee-93a7-005056ae54fa"}  potreste indicarmi dove sbaglio 
Grazie

**Comment by vigliottim** [comment]
Buongiorno,
dalle analisi effettuate sono emersi i seguenti errori:

- **As-is:**
Content-Disposition: form-data; name=requestBody
Content-Disposition: form-data; name="requestBody"
**To be:**
Content-Disposition: form-data; name="requestBody"

- **As is:**
Content-Disposition: form-data; name=file; filename=CDA_OK.pdf
**To be:**
Content-Disposition: form-data; name="file"; filename="CDA_OK.pdf"

Le chiediamo di riprovare eseguendo le correzioni riportate. Grazie.

**Comment by LucaRogledi** [comment]
Buonasera,
dalle analisi tramite il tool [jwt.io](https://jwt.io) è emerso che il bearer utilizzato contiene una firma non valida.
![image](https://github.com/ministero-salute/it-fse-support/assets/139234602/0085f0c9-4af2-46a1-adde-019793d5665d)
La invitiamo gentilmente a verificare che all'interno del bearer la firma sia valida e il campo x5c sia corretto restituendo "Signature Verified" tramite il tool [jwt.io](https://jwt.io).
Se può esserle utile è disponibile il tool [jwt-generator](https://github.com/ministero-salute/it-fse-gtw-tools) per la generazione dei token jwt.
Restiamo a disposizione per eventuali chiarimenti.
Grazie

**Comment by gruppomaxed** [comment]
Corretto la generazione dei Token e ora sono correttamente verificati da sito jwt.io  ma purtroppo ottengo un'altro  tipo di errore

Response Content: {"type":"https://govway.org/handling-errors/400/InvalidRequestContent.html","title":"InvalidRequestContent","status":400,"detail":"Request content not conform to API specification: Validation error(s) :\nbody: Field 'requestBody' is required. (code: 1026)\nFrom: body.<required>\n","govway_id":"14f7411e-f942-11ee-93a7-005056ae54fa"}

Response Status: BadRequest

potete ricontrollare  e indicarmi i nuovi errori ? grazie

**Comment by vigliottim** [comment]
Buonasera, come indicato in [documentazione](![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/466b27b2-b2d5-45fe-ab0a-d3738e8cc561)), il request body prevede l'inserimento del parametro requestBody, che dovrà contenere l’oggetto json con i parameter di input.
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/fc212b53-efe8-45fb-bbc1-efa418f83941)
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/dc375d69-b864-4c0a-9302-5c4ba9e804c0)
Le chiediamo di riprovare aggiungendo tale parametro mancante. Grazie.

**Comment by gruppomaxed** [comment]
adesso invece ottengo  Response Content: {"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"011fd108-fade-11ee-9223-005056ae7395"}

Response Status: Forbidden

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate è emerso che il campo "sub" dei JWT non è valorizzato in maniera conforme alle specifiche IHE (ITI TF-3) come riportato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt):
_As is:_ `"sub": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.6.3.2&ISO"`
_To be:_ `"sub": "CODICEFISCALE^^^&2.16.840.1.113883.2.9.4.3.2&ISO"`: al posto di `CODICEFISCALE` va inserito il codice fiscale dell’utente che fa richiesta del servizio di interoperabilità.
Le chiediamo di effettuare la correzione riportata e riprovare, grazie.

**Comment by gruppomaxed** [comment]
Adesso sono fermo a Response Content: {"traceID":"9c6cb39e89debeb9","spanID":"9c6cb39e89debeb9","type":"/msg/cda-element","title":"Errore in fase di estrazione del CDA.","detail":"Error while extracting CDA from PDF document","status":400,"instance":"/cda-extraction","workflowInstanceId":"UNKNOWN_WORKFLOW_ID"}

Response Status: BadRequest

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate è emerso che l'errore ricevuto è causato dal file pdf utilizzato. 
Iniettando lo stesso CDA in un nuovo pdf non abbiamo riscontrato anomalie. 
La preghiamo di riprovare rigenerando il pdf. Nel caso non lo stesse già usando, le suggeriamo di utilizzare il tool pdf-generator disponibile al link:
https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/pdf-generator
Restiamo in attesa di un suo gentile riscontro.

**Comment by gruppomaxed** [comment]
Ok risolto 
Grazie

Response Content: {"traceID":"42fa9998cac23827","spanID":"42fa9998cac23827","workflowInstanceId":"2.16.840.1.113883.2.9.2.80.3.1.4.4.80ef7f0628f29f108314f5899b51358e860865c47cfad414cf28c42308326ab4.3976022d4c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

Response Status: OK
