### ISSUE TITLE
Received request is not conform to the required interoperability profile

### ISSUE THREAD

**Issue by nturri1306** [ministero-salute/it-fse-support#74]
se provo da postman a fare una chiamata validation su https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1

torna questo errore

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"89b36ae8-9caf-11ed-b21d-005056ae54fa"}

**Comment by Ser-ena** [comment]
Buonasera, ci conferma cortesemente che l'errore sopra riportato è stato superato e adesso la problematica è invece quella segnalata su slack (https://developersitalia.slack.com/archives/C03RDT88FSM/p1674659563668929?thread_ts=1674648921.824669&cid=C03RDT88FSM)? ho cambiato il file json per generare il token ho inserito solamente {
	"aud" : "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
    "pem_path": "C:/fse2/certificati/sign.pem",
	"p12_path": "C:/fse2/certificati/sign.p12"
} mi ritorna un errore diverso adesso {
    "type": "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
    "title": "AuthorizationContentDeny",
    "status": 403,
    "detail": "Unauthorized request content",
    "govway_id": "2e06da72-9cb8-11ed-b06a-005056ae7395"
} (edited)

**Comment by nturri1306** [comment]
si adesso ricevo un errore diverso avendo cambiato il file json per generare il token

{
    "type": "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
    "title": "AuthorizationContentDeny",
    "status": 403,
    "detail": "Unauthorized request content",
    "govway_id": "8a684903-9cbf-11ed-b06a-005056ae7395"
}

**Comment by nturri1306** [comment]
salve ho risolto il problema era dovuto al campo "iss" che deve contenere le informazioni contenute nel certificato dove dice rilasciato a:
