### ISSUE TITLE
Errore validazione LDO vocabolari

### ISSUE THREAD

**Issue by ilariagiannetti1980** [ministero-salute/it-fse-support#741]
Buongiorno, 
nella validazione (https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation) della LDO ottengo il seguente errore:

HTTP/1.1 400 Bad Request
X-Backside-Transport: FAIL FAIL
Connection: Keep-Alive
Transfer-Encoding: chunked
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
set-cookie: 894d46ecfc124039ee218b63c12a3329=6caa4f1bda74e3b3b757b7fa19072d6f; path=/; HttpOnly; Secure; SameSite=None
Server: GovWay-SOGEI
Pragma: no-cache
GovWay-Message-ID: b159a065-0d61-498c-af9e-4d73c86017cd
GovWay-Transaction-ID: 2f202da4-f731-11ee-9223-005056ae7395
server-timing: intid;desc=83808decfa118a07
Date: Wed, 10 Apr 2024 12:22:30 GMT
Vary: *
X-Content-Type-Options: nosniff
Content-Type: application/problem+json
X-Global-Transaction-ID: 3f7e3e2d661684862f6a5b0d

{"traceID":"7c654881ac81e850","spanID":"7c654881ac81e850","type":"/msg/vocabulary","title":"Errore vocabolario.","detail":"Almeno uno dei seguenti vocaboli non è censito: [CodeSystem: 2.16.840.1.113883.6.1 v2.73, Codes:  11329-0]","status":400,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.90.4.4.46b382a30747a18e60f0824f38318dc669745d7b4e04f4ff90476d6134f371b3.20fbf08116^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

Il codice 11329-0 corrisponde all'Anamnesi Generale come indicato nel documento di specifica CDA2 LDO.

Quale potrebbe essere il problema? Grazie

**Comment by vigliottim** [comment]
Buongiorno, potrebbe cortesemente allegare il pdf utilizzato per effettuare la validazione? Grazie.

**Comment by vigliottim** [comment]
La invitiamo a riprovare rimuovendo lo spazio inserito all'interno dell'attributo _code_ prima del codice _11329-0_ nella sezione "Anamnesi":
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/a3e70b38-931d-4a8a-bd7f-ecd756aa725c)
Restiamo in attesa di un suo riscontro. Grazie.

**Comment by ilariagiannetti1980** [comment]
Buonasera,
confermo che togliendo lo spazio funziona.

Adesso ricevo l'OK, ma con il seguente Warning:
{"traceID":"26dbde5a571f7d81","spanID":"26dbde5a571f7d81","workflowInstanceId":"2.16.840.1.113883.2.9.2.90.4.4.46b382a30747a18e60f0824f38318dc669745d7b4e04f4ff90476d6134f371b3.11a271aada^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","warning":"[SIGN_WARN - Attenzione il documento risulta firmato in validazione][W003|  Sezione Condizioni del paziente e diagnosi alla dimissione: La sezione PUO' contenere l'elemento 'entry' ]"}

**Comment by vigliottim** [comment]
Grazie per il gentile feedback. Procediamo alla chiusura del presente ticket e rimaniamo a disposizione per altre richieste di supporto.
