### ISSUE TITLE
Crash Program FSE 2.0  Regione Lombardia - Errore nel UC16_EliminazioneDocumento

### ISSUE THREAD

**Issue by EugenioGuagliardi** [ministero-salute/it-fse-support#744]
Si chiede una verifica inerente all'errore ricevuta per il caso d'uso UC16_EliminazioneDocumento.

invocazione del servizio :
HTTP DELETE https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.30.4.4%5E030703.RRDOCU.ac0d1ec8-f73b-11ee-a9d8-0242a89a8ac7

effettuata in data:  2024-04-10 15:12:01.624 

Risposta ottenuta dal Gateway:
#{"traceID":"f9b261fd908ad549","spanID":"f9b261fd908ad549","type":"/msg/eds-error","title":"Eds error.","detail":"Document cannot be found on the Server FHIR","status":404,"instance":"/msg/eds-document-missing"}

Output servizio di Status:

```
{
    "traceID": "f3e17f51e9a3b200",
    "spanID": "b7ab3bfb5613b661",
    "transactionData": [
        {
            "eventType": "RIFERIMENTI_INI",
            "eventDate": "2024-04-10T13:12:02.123+00:00",
            "eventStatus": "SUCCESS",
            "message": "Riferimenti trovati: urn:uuid:17e1cd9f-f5be-44eb-9723-644fcb075856",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.ac0d1ec8-f73b-11ee-a9d8-0242a89a8ac7",
            "subject": "KRNBRS58M08B236S^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "030",
            "workflowInstanceId": "d16c0bc208779d7e2d847e31efeaaf096504c10039b0776cc1d42f80e89155d9.9d910e0e4a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "f9b261fd908ad549",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-04-10T13:12:02.133+00:00"
        },
        {
            "eventType": "EDS_DELETE",
            "eventDate": "2024-04-10T13:12:02.163+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "404 : \"{\"traceID\":\"f9b261fd908ad549\",\"spanID\":\"0b78f30be7ce8686\",\"type\":\"/err/resource\",\"title\":\"Resource error\",\"detail\":\"Error: document not found!\",\"status\":404,\"instance\":\"/not-found\"}\"",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.ac0d1ec8-f73b-11ee-a9d8-0242a89a8ac7",
            "subject": "KRNBRS58M08B236S^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "030",
            "workflowInstanceId": "d16c0bc208779d7e2d847e31efeaaf096504c10039b0776cc1d42f80e89155d9.9d910e0e4a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "f9b261fd908ad549",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-04-10T13:12:02.172+00:00"
        }
    ]
}
```

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Potrebbe gentilmente indicarci il workflowInstanceId ricevuto in risposta dalla chiamata di `pubblicazione` del documento che si intende eliminare?
Grazie

**Comment by EugenioGuagliardi** [comment]
Buongiorno, abbiamo eseguito un test con esito negativo! Restiamo in attesa di un vostro riscontro.
Di seguito le informazioni sulle transazioni del test:

Pubblicazione di un nuovo DCE esito OK 
risposta al servizio:
`{"tipologiaStruttura":"Ospedale","tipoDocumentoLivAlto":"LDO","assettoOrganizzativo":"AD_PSC026","tipoAttivitaClinica":"DIS","identificativoSottomissione":"2.16.840.1.113883.2.9.2.30.4.3.1713426190900","descriptions":[],"administrativeRequest":[],"identificativoDoc":"2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.430b1660-fd57-11ee-a9d8-0242a89a8ac7","identificativoRep":"2.16.840.1.113883.2.9.2.30.4.5.30703","mode":"RESOURCE","healthDataFormat":"CDA","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.1ba134d3d7^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","priorita":false}`

Servizio STATUS per la pubblicazione
...
{
    "traceID": "62d66bbd171357c1",
    "spanID": "a21f5846f0fefec3",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-04-18T07:43:15.228+00:00",
            "eventStatus": "SUCCESS",
            "subject": "KRNBRS58M08B236S^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.1ba134d3d7^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "765d958ba524d91f",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-04-18T07:43:15.239+00:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-04-18T07:43:17.053+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.430b1660-fd57-11ee-a9d8-0242a89a8ac7",
            "subject": "KRNBRS58M08B236S^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "DIS",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.1ba134d3d7^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "bd39bb4631133358",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-04-18T07:43:17.062+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-04-18T07:43:17.508+00:00",
            "eventStatus": "SUCCESS",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:WarningERROR_CODE:R222CODE CONTEXT:Patient temporarily managed by INI",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.1ba134d3d7^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-04-18T07:43:17.516+00:00"
        },
        {
            "eventType": "SEND_TO_EDS",
            "eventDate": "2024-04-18T07:43:17.630+00:00",
            "eventStatus": "SUCCESS",
            "message": "{\"esito\":true}",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.1ba134d3d7^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-04-18T07:43:17.640+00:00"
        },
        {
            "eventType": "EDS_WORKFLOW",
            "eventDate": "2024-04-18T07:43:22.458+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "Documento già esistente",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.1ba134d3d7^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-04-18T07:43:22.624+00:00"
        }
    ]
}
...


Eliminazione Documento Esito KO:

```
09: 44: 12: 533 | server = null | ID_DC = 01e7fd2c - 3881 - 4ac4 - 97ef - a9b7eb56353b | ID_COOP = null | elapsed = 422 | DIR = CLI | OUT = /govway/rest / in / FSE / gateway / v1 / documents / 2.16.840.1.113883.2.9.2.30.4.4 % 5E030703.RRDOCU.430b1660 - fd57 - 11ee - a9d8 - 0242a89a8ac7 # null # {

    "traceID": "cde3da13aeeb6dee",

    "spanID": "cde3da13aeeb6dee",

    "type": "/msg/ini-error",

    "title": "Ini error.",

    "detail": "{\"traceID\":\"0000000000000000cde3da13aeeb6dee\",\"spanID\":\"28e23ffcb0a59779\",\"type\":\"/errors/fields\",\"title\":\"Missing\",\"detail\":\"Non è stato possibile recuperare i riferimenti con i dati forniti in input\",\"instance\":\"/ini\"}",

    "status": 404,

    "instance": "/msg/service-error/ini"

}


  "traceID": "cde3da13aeeb6dee",
{
    "traceID": "3f3560a0bf13ec64",
    "spanID": "41695a167c55a4ec",
    "type": "/msg/record-not-found",
    "title": "Record non trovato.",
    "detail": "No Record Found",
    "instance": "/record-not-found"
}
```

**Comment by IStacchiotti** [comment]
Buonasera, potrebbe cortesemente riprovare eseguendo un giro pulito (partendo quindi da un documento che non sia mai stato pubblicato in precedenza). Rimaniamo a disposizione nel caso l'errore si ripresenti, grazie

**Comment by EugenioGuagliardi** [comment]
Buongiorno,
nell'esempio del test precedente abbiamo agito esattamente rispetto alla vostra indicazione, siamo partiti da un nuovo documento pubblicato (esito OK) e poi abbiamo eseguito la cancellazione che è andata in KO. 
Cosa intendete per giro pulito?

Rimaniamo in attesa di vostre indicazioni.

Grazie 
.

**Comment by LucaRogledi** [comment]
Buongiorno,
con l'esecuzione di un "giro pulito" intendiamo l'esecuzione della validazione di un nuovo documento mai pubblicato in precedenza e successivamente la pubblicazione dello stesso utilizzando un `identificativoDoc` originale, in modo da evitare messaggi di errore ( `"message": "Documento già esistente"` ) nello step `"eventType": "EDS_WORKFLOW"`.  
Le chiediamo cortesemente di riprovare così, rimaniamo in attesa di un vostro gentile riscontro e a disposizione per ulteriori richieste di chiarimento/supporto.
Grazie

**Comment by EugenioGuagliardi** [comment]
Salve, abbiamo riprovato ed il test è positivo!
Grazie per il supporto!

**Comment by LucaRogledi** [comment]
Ringraziamo per il feedback e procediamo alla chiusura della presente issue.
