### ISSUE TITLE
Errore validazione RAD

### ISSUE THREAD

**Issue by michelebukovitz** [ministero-salute/it-fse-support#746]
Buongiorno, 
sto ricevendo un errore di validazione RAD, ma non riesco a capire cosa lo provochi. 
Allego i dettagli in coda. 

Nel ringraziarvi vi saluto cordialmente.

ERRORE Validazione Documento
RISPOSTA : 400 - Bad Request
TraceID : 53a6634d84b638e6
WorkflowInstanceID : 0.1.2.3.4.8e612bd1f5d132a339575b8dafb7842c64614e56bcf3d5ab65a0bc4b34329407.3935833649^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
SpanID : 53a6634d84b638e6
Warning : null
Timestamp : 2024-04-11T10:29:49Z
instance : /validation/error
detail : ERROR: -1,-1 cvc-complex-type.2.4.a: Invalid content was found starting with element 'statusCode'. One of '{"urn:hl7-org:v3":activityTime, "urn:hl7-org:v3":availabilityTime, "urn:hl7-org:v3":priorityCode, "urn:hl7-org:v3":confidentialityCode, "urn:hl7-org:v3":uncertaintyCode, "urn:hl7-org:v3":reasonCode, "urn:hl7-org:v3":languageCode, "urn:hl7-org:v3":subject, "urn:hl7-org:v3":specimen, "urn:hl7-org:v3":performer, "urn:hl7-org:v3":author, "urn:hl7-org:v3":informant, "urn:hl7-org:v3":participant, "urn:hl7-org:v3":entryRelationship, "urn:hl7-org:v3":reference, "urn:hl7-org:v3":precondition}' is expected.
type : /msg/syntax
title : Errore di sintassi.
status : 400

**Comment by pantareisrl** [comment]
Ecco il pdf, grazie.

[rptSiHL7.pdf](https://github.com/ministero-salute/it-fse-support/files/14944344/rptSiHL7.pdf)

**Comment by vigliottim** [comment]
Buongiorno,
la invitiamo a riprovare modificando il posizionamento degli elementi _statusCode_ e _effectiveTime_ come indicato di seguito:

```
<entry>
    <act classCode="ACT" moodCode="EVN">
        <code code="87.11.3" codeSystem="2.16.840.1.113883.2.9.2.90.6.12"
            codeSystemName="NomenclatoreTariffario_SAN_RegToscana"
            displayName="Ortopantomografia">
            <originalText>
                <reference value="#Esame1Desc" />
            </originalText>
        </code>
        <statusCode code="active" />
        <effectiveTime value="20240410161314+0200" />
    </act>
</entry>
```

Restiamo in attesa di un suo gentile riscontro. Grazie.

**Comment by vigliottim** [comment]
Sì, le confermiamo che è possibile usare entrambe, come indicato nella guida HL7 Italia per RSA consultabile al link http://www.hl7italia.it/hl7italia_D7/node/2316: 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/79efa4e2-9bde-48b0-ae9f-606adb15431d)

**Comment by vigliottim** [comment]
Grazie a lei, procediamo alla chiusura del presente ticket e rimaniamo a disposizione per altre richieste di supporto.
