### ISSUE TITLE
Aggiornamento file data.json

### ISSUE THREAD

**Issue by mghi-sined** [ministero-salute/it-fse-support#747]
Come da vostra segnalazione, ho provveduto ad aggiornare il campo appVendor all'interno del file data.json ,
sostituendo il carattere " " con il carattere "_" .   

Se non ho commesso errori, il tutto dovrebbe essere già presente nel repository GITHUB .

Questi sono i dati che identificano la procedura in validazione:

commonName auth: A1#111SINEDXX
subject_application_vendor: Sined_S.r.l.
subject_application_id: MedWare
subject_application_version: 24.02.12

Grazie.
Massimo Ghirardello

**Comment by IStacchiotti** [comment]
Buonasera Massimo, le abbiamo dato un'indicazione all'interno della stessa pull request (tab conversation), di cui riporto di seguito il [link](https://github.com/ministero-salute/it-fse-accreditamento/pull/1334#issuecomment-2049622257) per comodità. La invitiamo a far riferimento a questo canale per la richiesta di riscontri sulla bontà dei contenuti contenuti nella pull request relativa. Procediamo alla chiusura del presente, ma rimaniamo a disposizione per eventuali richieste di supporto ulteriori
