### ISSUE TITLE
SINED: Nuova pull request (20240410.2) 

### ISSUE THREAD

**Issue by mghi-sined** [ministero-salute/it-fse-support#749]
Buongiorno,

verso le 16:45 di oggi 11/aprile, ho effettuato una nuova pull request che andava a ricaricare tutti i file nella nuova directory che dovrebbe essere (spero) in linea con le indicazioni che mi avevate fornito qualche ora fa. 

In pratica :

- il PATH  è diventato ".../A1#111SINEDXX/Sined_S.r.l./MedWare/24.02.12".
- il campo "appVendor" nel file "data.json" diventa "Sined_S.r.l." 

Spero di non aver tralasciato nulla per strada.

I dati identificativi della applicazione in accreditamento sono i seguenti :

commonName auth: A1#111SINEDXX
subject_application_vendor: Sined_S.r.l.
subject_application_id: MedWare
subject_application_version: 24.02.12

Grazie.

**Comment by vigliottim** [comment]
Buonasera, le confermiamo che la pull request è stata effettuata correttamente.
Riceverà aggiornamenti sulle elaborazioni via e-mail.
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
