### ISSUE TITLE
VALIDAZIONE CDA VPS -  CASO DI TEST 26

### ISSUE THREAD

**Issue by cravell** [ministero-salute/it-fse-support#75]
Salve,
In merito all'operazione di VALIDAZIONE CDA, stiamo eseguendo il test "CASO DI TEST 26" previsto per il VPS impostando nel CDA un codice triage non corretto ("V"), ma la validazione ha restituito un ack positivo mentre ci aspettavamo un errore di validazione.
La sezione CDA in questione è:
`<component><section classCode="DOCSECT" moodCode="EVN"><templateId root="2.16.840.1.113883.2.9.10.1.6.21" /><code code="54094-8" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Triage note" /><title>TRIAGE</title><text><paragraph><caption>TRIAGE</caption><content ID="triage_ref_id1">VERDE</content></paragraph></text>             <entry><observation classCode="OBS" moodCode="EVN"><templateId root="2.16.840.1.113883.2.9.10.1.6.39" /><code code="11283-9" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Valutazione Acutezza" /><text/><statusCode code="completed"/><effectiveTime value="20230126121000" /><value xsi:type="CD" code="V" codeSystem="2.16.840.1.113883.2.9.6.1.54.4" displayName="Codice Triage"/></observation></entry></section></component>`
La risposta del gateway è la seguente:
`{"traceID":"8067759b9f1f8474","spanID":"8067759b9f1f8474","workflowInstanceId":"2.16.840.1.113883.2.9.2.150.4.1.d3bf42254389477af67903d628efac921cde034bbed7c54c4b937103e518b995.7df033a14f^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

**Comment by Ser-ena** [comment]
Buongiorno,  è corretto che passi la validazione terminologica in quanto, da un controllo del dizionario (CodiceTriage_VPS - 2.16.840.1.113883.2.9.6.1.54.4), risulta che il codice "V" sia un valore ammesso.
V | Verde - Poco critico |   | active. 
Sarebbe necessario provare un altro codice.

**Comment by cravell** [comment]
Dalle specifiche andando sul dizionario a questo link:
https://hl7itig.art-decor.pub/hl7itig-html-20221221T144251/voc-2.16.840.1.113883.3.1937.777.63.11.8-2018-03-19T000000.html
Vedo che i valori possibili sono:
1 Rosso EMERGENZA
2 Arancione URGENZA
3 Azzurro URGENZA DIFFERIBILE
4 Verde URGENZA MINORE
5 Bianco NON URGENZA
