### ISSUE TITLE
Servizio Status risponde con 404

### ISSUE THREAD

**Issue by avlp** [ministero-salute/it-fse-support#750]
Salve,
nell'ambito del Crash program si è pubblicato un documento con workflowinstanceid pari a 2.16.840.1.113883.2.9.2.150.4.4.8ceecad7d107db78ae84aeb5b19fe0be1d2cf440902a0911b44404d2f09168d0.2cb02e24a6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId. Il servizio status risponde però con 404.
"traceID":"c2cfa3beed61784d","spanID":"c2cfa3beed61784d"

**Comment by IStacchiotti** [comment]
Buonasera, per chiamare la status passando il workflowinstanceid, occorre eseguire l'url encode dello stesso prima che venga inserito nell'url. Ci conferma di aver eseguito questo passaggio? In caso contrario la invitiamo a riprovare così (le segnaliamo che è possibile ricorrere a questo [tool](https://www.urlencoder.io/) online per la conversione).

URL atteso: `https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/status/2.16.840.1.113883.2.9.2.150.4.4.8ceecad7d107db78ae84aeb5b19fe0be1d2cf440902a0911b44404d2f09168d0.2cb02e24a6%5E%5E%5E%5Eurn%3Aihe%3Aiti%3Axdw%3A2013%3AworkflowInstanceId
`

**Comment by IStacchiotti** [comment]
Buongiorno, il workflowInstanceId che è stato inserito da voi nell'url non ci risulta corretto. La invitiamo a riprovare inserendo nell'url questa stringa, che deriva dalla conversione del parametro workflowInstanceId tramite questo [tool](https://www.urlencoder.io/)  : `2.16.840.1.113883.2.9.2.150.4.4.8ceecad7d107db78ae84aeb5b19fe0be1d2cf440902a0911b44404d2f09168d0.2cb02e24a6%5E%5E%5E%5Eurn%3Aihe%3Aiti%3Axdw%3A2013%3AworkflowInstanceId`
- AS-IS: <img width="454" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/122798799/90ead196-4e5f-414a-ba37-8fc45225b4a0">
- TO-BE: <img width="457" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/122798799/922f9b0d-0007-4214-8333-f69cf23ab21e">

**Comment by avlp** [comment]
Salve,
correggendo l'url come suggerito si ottiene risposta positiva:
`[2024-04-12 10:13:13,652]  "GET /govway/rest/in/FSE/gateway/v1/status/2.16.840.1.113883.2.9.2.150.4.4.8ceecad7d107db78ae84aeb5b19fe0be1d2cf440902a0911b44404d2f09168d0.2cb02e24a6%5E%5E%5E%5Eurn:ihe:iti:xdw:2013:workflowInstanceId HTTP/1.1"
`
"traceID":"10150951ef1acee6"

Grazie del supporto
