### ISSUE TITLE
Sezione DICOM Object Catalog

### ISSUE THREAD

**Issue by michelebukovitz** [ministero-salute/it-fse-support#751]
Buongiorno, 
analizzando il test case 17 per il RAD verificando la documentazione leggo: 

CONF - RAD - 81 La sezione DICOM Object Catalog DEVE contenere un elemento <entry>/<act> il quale DEVE a sua volta avere la seguente struttura: una o più <entry>/<act>, atte ad identificare lo Studio DICOM (Study Act); una o più <entryRelationship>/<act>, atte ad identificare le Serie (Series Act); una o più <entryRelationship>/<observation>, atte a identificare le istanze SOP (SOP Instance) e a contenere i riferimenti alle immagini DICOM.

Mi chiedevo: 
1 - vedo che la pubblicazione va a buon fine anche in mancanza della sezione (effettivamente è segnata opzionale)
2 - Nella valorizzazione è obbligatorio scendere a livello di SOPInstanceUID? Oppure è sufficiente fermarsi alle serie?

**Comment by vigliottim** [comment]
Buongiorno, rispondiamo di seguito alle sue domande:

1. La sezione DICOM Object Catalog è opzionale secondo la guida HL7 Italia e anche ai fini dell'accreditamento: 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/e1778e3e-4146-4f6c-8b70-7255d7919f53)
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/f9cc6558-1bfa-487f-9435-1c78403a7128)
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/117e137f-889f-43b2-b472-03df9c8bc220)
Pertanto, è corretto che non riceva errori in fase di pubblicazione.
2. Nel caso di test 17, che è un caso di test KO, il blocco da lei menzionato non deve essere presente, come indicato nel file excel https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/1-Referto%20di%20Radiologia/CDA2_Referto_di_Radiologia_KO.xlsx: 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/8ff37dc7-a72d-4aea-a380-31e6f32a6af6)
Pertanto, non è necessario inserire le informazioni relative al SOP Instance UID.

Rimaniamo a disposizione per chiarimenti.
