### ISSUE TITLE
Mancata validazione del CDA

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#753]
Buongiorno, ho un problema con la validazione API di un CDA.
Se invio il vostro file di esempio, RAD.pdf (in allegato) va tutto bene.
Se da quel pdf estraggo il CDA dagli allegati, lo inserisco in un mio pdf firmato testsigned.pdf (in allegato) e tento la validazione ricevo quest'errore:
{
  "traceID": "98fd80aa430ceb03",
  "spanID": "98fd80aa430ceb03",
  "type": "/msg/syntax",
  "title": "Errore di sintassi.",
  "detail": "Error while executing validation on xsd schema",
  "status": 400,
  "instance": "/validation/error",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.8fe46b71d98546dc779f4a7f4859b056b254bbe56b59baa550333b2c46441c87.fd2e24dc07^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "warning": null
}
Il messaggio sembrerebbe voler dire che c'è un errore di sintassi nel CDA, ma se è lo stesso (vostro) che ho inviato prima e non mi ha dato nessun errore, com'è possibile? Visto che l'unica differenza risiede nel pdf che lo contiene mi verrebbe da pensare che il problema si trovi lì, ma non è quello che leggo nel messaggio e soprattutto non ho idea di quale possa essere, visto che a me non sembra ci sia niente di irregolare.
Potete aiutarmi a capire?
Grazie mille
[RAD.pdf](https://github.com/ministero-salute/it-fse-support/files/14957673/RAD.pdf)
[testsigned.pdf](https://github.com/ministero-salute/it-fse-support/files/14957683/testsigned.pdf)

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Dalle analisi risulta che il pdf da lei indicato "testsigned.pdf" differisce da quello ricevuto dal gateway, contenendo un cda diverso.
Dalle nostre prove risulta che la validazione utilizzando il pdf "testsigned.pdf" funziona correttamente, mentre quello inviato al gateway origina l'errore segnalato. 
 
Di seguito il confronto tra il cda contenuto in "testsigned.pdf" (sinistra) e il cda contenuto nel documento inviato al gateway (destra)
![image](https://github.com/ministero-salute/it-fse-support/assets/139234602/6fb5b3e7-f92b-413b-a396-b3cb5a119bbb)

La invitiamo pertanto a verificare le informazioni contenute e riprovare.
Restiamo a disposizione per eventuali chiarimenti.
Grazie

**Comment by infoserviceonline** [comment]
E' vero, c'è stato uno scambio di percorsi, chiedo scusa e chiudo il posto.
