### ISSUE TITLE
Recupero PDF

### ISSUE THREAD

**Issue by michelebukovitz** [ministero-salute/it-fse-support#754]
Buongiorno, a causa di un inconveniente sono andati persi i PDF, per caso è possibile effettuare il recupero dal servizio di test?

**Comment by vigliottim** [comment]
Buongiorno, purtroppo non è possibile recuperare i file PDF. 
Le suggeriamo di consultare le issue aperte da lei, qualora abbia condiviso i file potrà scaricarli: https://github.com/ministero-salute/it-fse-support/issues/created_by/michelebukovitz
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
