### ISSUE TITLE
Campania - Sprint 1 - Verfica stato replace

### ISSUE THREAD

**Issue by avlp** [ministero-salute/it-fse-support#755]
Buongiorno,
nell'ambito dello Sprint 1 del Crash Program di Regione Campania si è proceduto ad inviare una replace lo scorso venerdì ai servizi di sussidiarietà ottenendo l'id TEMP_150_816389. Ad oggi risulta ancora in stato ELAB: è possibile sbloccare l'elaborazione per conoscere lo stato della trasazione?

**Comment by g-maugeri-sogei** [comment]
Buonasera, sembrerebbe esserci un problema con l'identificativo del documento da sostituire.
Potete fornirci la request relativa alla richiesta di replace?

**Comment by g-maugeri-sogei** [comment]
Sulla base dati non trovo documenti identificati da urn:uuid:0369d8bb-2080-4620-a9c6-b84e2750406c. Suppongo state provando a sostituire il documento urn:uuid:a2cb35f9-ed86-46b2-91d0-6661c1600cae.
Potete verificare se coincide con l'id usato nella richiesta di pubblicazione?

**Comment by avlp** [comment]
Request ricerca doc da sostituire:
`<ric:RicercaDocumentiRichiesta xmlns:ric="http://ricercadocumentirichiesta.xsd.fse.ini.finanze.it">
	<ric:IdentificativoUtente>PROVAX00X00X000Y</ric:IdentificativoUtente>
	<ric:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</ric:pinCode>
	<ric:IdentificativoOrganizzazione>150</ric:IdentificativoOrganizzazione>
	<ric:StrutturaUtente>201123456</ric:StrutturaUtente>
	<ric:RuoloUtente>DRS</ric:RuoloUtente>
	<ric:ContestoOperativo>UPDATE</ric:ContestoOperativo>
	<ric:IdentificativoAssistito>DCRNTN00M25F839J</ric:IdentificativoAssistito>
	<ric:PresaInCarico>true</ric:PresaInCarico>
	<ric:StatoDocumento>Approved</ric:StatoDocumento>
	<ric:IdentificativoDocumento>2.16.840.1.113883.2.9.2.150.4.4^469639</ric:IdentificativoDocumento>
	<ric:IdentificativoApplicativoRichiedente>Ellipse AMB</ric:IdentificativoApplicativoRichiedente>
	<ric:FornitoreApplicativoRichiedente>Engineering Ingegneria Informatica S.p.A.</ric:FornitoreApplicativoRichiedente>
	<ric:VersioneApplicativoRichiedente>1.0.0</ric:VersioneApplicativoRichiedente>
	<ric:OpzioniRisposta>ObjectRef</ric:OpzioniRisposta>
</ric:RicercaDocumentiRichiesta>`

Response:


`      <a:RicercaDocumentiRicevuta xmlns="http://tipodatiricercadocumenti.xsd.fse.ini.finanze.it" xmlns:b="http://ricercadocumentirichiesta.xsd.fse.ini.finanze.it" xmlns:a="http://ricercadocumentiricevuta.xsd.fse.ini.finanze.it">
         <a:Esito>0000</a:Esito>
         <a:Metadato>
            <VersioneOggettoDocumento>1</VersioneOggettoDocumento>
            <IdentificativoUnivocoDocumento>urn:uuid:0369d8bb-2080-4620-a9c6-b84e2750406c</IdentificativoUnivocoDocumento>
            <DocumentoFirmato>true^Documento firmato</DocumentoFirmato>
         </a:Metadato>
         <a:ElencoErrori>
            <Errore>
               <codEsito>0000</codEsito>
               <esito>Operazione eseguita correttamente</esito>
               <tipoErrore>Success</tipoErrore>
               <fonte>FSE-INS-BE</fonte>
            </Errore>
         </a:ElencoErrori>
      </a:RicercaDocumentiRicevuta>
`

**Comment by g-maugeri-sogei** [comment]
Potete aggiungere anche la request relativa al messaggio di pubblicazione?

**Comment by avlp** [comment]
Salve questa è la v1
`[2024-04-12 15:33:02,848] 
<com:ComunicazioneMetadatiRichiesta xmlns:com="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it" xmlns:tip="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it">
	<com:IdentificativoUtente>PROVAX00X00X000Y</com:IdentificativoUtente>
		<com:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</com:pinCode>
	<com:IdentificativoOrganizzazione>150</com:IdentificativoOrganizzazione>
	<com:StrutturaUtente>201123456</com:StrutturaUtente>
	<com:RuoloUtente>DRS</com:RuoloUtente>
	<com:ContestoOperativo>TREATMENT</com:ContestoOperativo>
	<com:TipoDocumento/>
	<com:IdentificativoAssistito>DCRNTN00M25F839J</com:IdentificativoAssistito>
	<com:PresaInCarico>true</com:PresaInCarico>
	<com:TipoAttivita>CREATE</com:TipoAttivita>
	<com:Metadato>
		<tip:TipologiaStrutturaProdDoc>Ospedale</tip:TipologiaStrutturaProdDoc>
		<tip:TipoMime>application/pdf+text/x-cda-r2+xml</tip:TipoMime>
		<tip:LivelloConfidenzialita>N</tip:LivelloConfidenzialita>
		<tip:TipologiaDocumentoAlto>REF</tip:TipologiaDocumentoAlto>
		<tip:TipologiaDocumentoMedio>11488-4</tip:TipologiaDocumentoMedio>
		<tip:TipologiaDocumentoBasso>PDF</tip:TipologiaDocumentoBasso>
		<tip:RiferimentoDocumento/>
		<tip:DataValidazioneDocumento>20240412153046</tip:DataValidazioneDocumento>
		<tip:RuoloAutore>DRS</tip:RuoloAutore>
		<tip:IstituzioneAutore>150201123456</tip:IstituzioneAutore>
			<tip:CodiceFiscaleAutore>PROVAX00X00X000Y</tip:CodiceFiscaleAutore>
		<tip:AssettoOrganizzativo>AD_PSC026</tip:AssettoOrganizzativo>
		<tip:TipoAttivitaClinica>DIS</tip:TipoAttivitaClinica>
		<tip:DataInizioPrestazione>20240412110047</tip:DataInizioPrestazione>
		<tip:DataFinePrestazione>20240412112047</tip:DataFinePrestazione>
	</com:Metadato>
	<com:IdentificativoApplicativoRichiedente>Ellipse AMB</com:IdentificativoApplicativoRichiedente>
	<com:FornitoreApplicativoRichiedente>Engineering Ingegneria Informatica S.p.A.</com:FornitoreApplicativoRichiedente>
	<com:VersioneApplicativoRichiedente>1.0.0</com:VersioneApplicativoRichiedente>
	<com:OpzioniRequest>
		<tip:chiave>GATEWAY</tip:chiave>
		<tip:valore>true</tip:valore>
	</com:OpzioniRequest>
		<com:OpzioniRequest>
			<tip:chiave>WORKFLOWINSTANCEID</tip:chiave>
			<tip:valore>2.16.840.1.113883.2.9.2.150.4.4.a1f6ce951e493c2af709e5430ea8d912d3613f72e9200729715a4d41f811f45c.4368d8a3f9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId</tip:valore>
		</com:OpzioniRequest>
		<com:OpzioniRequest>
			<tip:chiave>MODE</tip:chiave>
			<tip:valore>ATTACHMENT</tip:valore>
		</com:OpzioniRequest>
</com:ComunicazioneMetadatiRichiesta>`

La request della v2 è più su

**Comment by g-maugeri-sogei** [comment]
Nella request di replace i campi tip:sourceObject e tip:IdentificativoUnivocoDocumento dovrebbero contenere il riferimento al documento da sostituire, in questo caso 2.16.840.1.113883.2.9.2.150.4.4^469639.
Potete rifare un giro completo modificando il messaggio di replace come suggerito?


<tip:RiferimentoDocumento>urn:uuid:0369d8bb-2080-4620-a9c6-b84e2750406c</tip:RiferimentoDocumento>
      <tip:Associazione>
         <tip:associationType>urn:ihe:iti:2007:AssociationType:RPLC</tip:associationType>
         **<tip:sourceObject>doc1</tip:sourceObject>**
         <tip:targetObject>urn:uuid:0369d8bb-2080-4620-a9c6-b84e2750406c</tip:targetObject>
         <tip:submissionSetStatus>Original</tip:submissionSetStatus>
         <tip:previousVersion/>
      </tip:Associazione>
      **<tip:IdentificativoUnivocoDocumento>doc1</tip:IdentificativoUnivocoDocumento>**

**Comment by avlp** [comment]
Come condiviso nella call col DTD si provvede ad inviare un nuovo referto lab.
Request:
`[2024-04-16 15:58:03,382] [-1234] [] [http-nio-9443-exec-34@fb980019c4ea] DEBUG {it.eng.cct.carbon.mediator.freemarker.transform.FreemarkerMediator} -  Freemarker output:

<com:ComunicazioneMetadatiRichiesta xmlns:com="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it" xmlns:tip="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it">
	<com:IdentificativoUtente>PROVAX00X00X000Y</com:IdentificativoUtente>
		<com:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</com:pinCode>
	<com:IdentificativoOrganizzazione>150</com:IdentificativoOrganizzazione>
	<com:StrutturaUtente>201123456</com:StrutturaUtente>
	<com:RuoloUtente>DRS</com:RuoloUtente>
	<com:ContestoOperativo>TREATMENT</com:ContestoOperativo>
	<com:TipoDocumento/>
	<com:IdentificativoAssistito>DFLDRD99T25F839H</com:IdentificativoAssistito>
	<com:PresaInCarico>true</com:PresaInCarico>
	<com:TipoAttivita>CREATE</com:TipoAttivita>
	<com:Metadato>
		<tip:TipologiaStrutturaProdDoc>Ospedale</tip:TipologiaStrutturaProdDoc>
		<tip:TipoMime>application/pdf+text/x-cda-r2+xml</tip:TipoMime>
		<tip:LivelloConfidenzialita>N</tip:LivelloConfidenzialita>
		<tip:TipologiaDocumentoAlto>REF</tip:TipologiaDocumentoAlto>
		<tip:TipologiaDocumentoMedio>11488-4</tip:TipologiaDocumentoMedio>
		<tip:TipologiaDocumentoBasso>PDF</tip:TipologiaDocumentoBasso>
		<tip:RiferimentoDocumento/>
		<tip:DataValidazioneDocumento>20240416151050</tip:DataValidazioneDocumento>
		<tip:RuoloAutore>DRS</tip:RuoloAutore>
		<tip:IstituzioneAutore>150201123456</tip:IstituzioneAutore>
			<tip:CodiceFiscaleAutore>PROVAX00X00X000Y</tip:CodiceFiscaleAutore>
		<tip:AssettoOrganizzativo>AD_PSC026</tip:AssettoOrganizzativo>
		<tip:TipoAttivitaClinica>DIS</tip:TipoAttivitaClinica>
		<tip:DataInizioPrestazione>20240415151050</tip:DataInizioPrestazione>
		<tip:DataFinePrestazione>20240416051050</tip:DataFinePrestazione>
	</com:Metadato>
	<com:IdentificativoApplicativoRichiedente>Ellipse AMB</com:IdentificativoApplicativoRichiedente>
	<com:FornitoreApplicativoRichiedente>Engineering Ingegneria Informatica S.p.A.</com:FornitoreApplicativoRichiedente>
	<com:VersioneApplicativoRichiedente>1.0.0</com:VersioneApplicativoRichiedente>
	<com:OpzioniRequest>
		<tip:chiave>GATEWAY</tip:chiave>
		<tip:valore>true</tip:valore>
	</com:OpzioniRequest>
		<com:OpzioniRequest>
			<tip:chiave>WORKFLOWINSTANCEID</tip:chiave>
			<tip:valore>2.16.840.1.113883.2.9.2.150.4.4.76bfd831e625b9a71d688faaca89210aa112bc26355753e3c70bd42e8ae5a74a.1bbef529f0^^^^urn:ihe:iti:xdw:2013:workflowInstanceId</tip:valore>
		</com:OpzioniRequest>
		<com:OpzioniRequest>
			<tip:chiave>MODE</tip:chiave>
			<tip:valore>ATTACHMENT</tip:valore>
		</com:OpzioniRequest>
</com:ComunicazioneMetadatiRichiesta>`

ID ottenuto: TEMP_150_817210

**Comment by IStacchiotti** [comment]
Buonasera, vi comunichiamo che verrà rilasciata una fix, seguiranno aggiornamenti appena disponibili, grazie.

**Comment by g-maugeri-sogei** [comment]
Fix rilasciata.

**Comment by avlp** [comment]
Salve si è provveduto ad inviare un nuovo documento ricevendo l'id TEMP_150_819366 . Si resta in attesa della verifica per procedere alla sostituzione

**Comment by g-maugeri-sogei** [comment]
Buongiorno, confermo che la richista di pubblicazione e' stata completata con successo. Potete procedere con la replace.

**Comment by avlp** [comment]
Salve, replace inviata correttamente, TEMP_150_819589

**Comment by lGiulianiSogei** [comment]
Salve,
abbiamo riscontrato un errore: "Struttura dell'utente diversa da quella del documento", cioè indica che la struttura dell'autore nel CDA inviato, è diversa da quella della request in quanto è assente nel cda interno al PDF. 
Infatti manca l'elemento recuperato da XPATH «author/representedOrganization» nel CDA.
Attualmente tale metadato non è obbligatorio da specifiche, per effettuare il test ora potete riprovare valorizzando il campo nel CDA.

**Comment by avlp** [comment]
Buongiorno è stao inviato un nuovo referto con TEMP_150_822099

**Comment by lGiulianiSogei** [comment]
Il test di questa ultima  replace ci risulta essere andato a buon fine. Grazie

**Comment by LucaRogledi** [comment]
Grazie per il feedback, procediamo con la chiusura della presente issue come risolta. Si può procedere con la riapertura nel caso fosse necessario ulteriore supporto. Grazie

**Comment by paolo-casillo** [comment]
@LucaRogledi c'è stato un qui pro quo, il giro di test sta proseguendo: chiedo la cortesia di riaprie la issue.

**Comment by avlp** [comment]
Buongiorno è stata inviata una replace ricevendo l'identificativo TEMP_150_822148, risulta ancora in elaborazione è possibile avere riscontro?

**Comment by avlp** [comment]
E' possibile avere un dettaglio della correzione da applicare?

**Comment by g-maugeri-sogei** [comment]
La struttura indicata nel CDA deve corrispondere a quella indicata nel messaggio.

**Comment by avlp** [comment]
Potreste confermare che la correzione è:
CDA2`	<author>
		<time value="20240508113834+0200"/>
		<assignedAuthor>
			<id assigningAuthorityName="Ministero Economia e Finanze" extension="SMTMZK93E25A818O" root="2.16.840.1.113883.2.9.4.3.2"/>
			<telecom nullFlavor="NA" use="HP"/>
			<telecom nullFlavor="NA" use="HP"/>
			<telecom nullFlavor="NA" use="HP"/>
			<assignedPerson>
				<name>
					<prefix>dott.</prefix>
					<family>SISTEMA</family>
					<given>AMMINISTRATORE</given>
				</name>
			</assignedPerson>
			<representedOrganization>
				<id assigningAuthorityName="Regione Campania" extension="150201123456" root="2.16.840.1.113883.2.9.4.1.1"/>
				<name>Ambulatorio test</name>
			</representedOrganization>
		</assignedAuthor>
	</author>`

request:
`<tip:IstituzioneAutore>150201123456</tip:IstituzioneAutore>`

**Comment by g-maugeri-sogei** [comment]
Salve,
adesso dovrebbe andare. Potete riprovare partendo dalla pubblicazione di un nuovo documento e provando poi la replace sempre con RDA=RDE?

**Comment by avlp** [comment]
Salve è stato inviato un nuovo referto ottenendo TEMP_150_822562. E' possibile avere conferma del buon esito dell'operazione?

**Comment by g-maugeri-sogei** [comment]
La transazione e' andata a buon fine.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente issue viene chiusa. Sarà possibile riaprirla nel caso in cui sia necessario ulteriore supporto. Grazie.

**Comment by avlp** [comment]
Salve si invia un nuovo documento TEMP_150_824983 . Si attende conferma per procedere con la replace

**Comment by g-maugeri-sogei** [comment]
Pubblicazione ok.

**Comment by avlp** [comment]
Il servizio StatoPubblicazione risponde con identifier 2.16.840.1.113883.2.9.2.150.4.4^474625
Provando la sostituzione utilizzando l'identifier si ottiene l'errore 
1144-Riferimento documento non valido

Ecco la request inviata:

`<com:ComunicazioneMetadatiRichiesta xmlns:com="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it" xmlns:tip="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it">
	<com:IdentificativoUtente>PROVAX00X00X000Y</com:IdentificativoUtente>
		<com:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</com:pinCode>
	<com:IdentificativoOrganizzazione>150</com:IdentificativoOrganizzazione>
	<com:StrutturaUtente>201123456</com:StrutturaUtente>
	<com:RuoloUtente>DRS</com:RuoloUtente>
	<com:ContestoOperativo>TREATMENT</com:ContestoOperativo>
	<com:TipoDocumento/>
	<com:IdentificativoAssistito>DCRNTN00M25F839J</com:IdentificativoAssistito>
	<com:PresaInCarico>true</com:PresaInCarico>
	<com:TipoAttivita>CREATE</com:TipoAttivita>
	<com:Metadato>
		<tip:TipologiaStrutturaProdDoc>Ospedale</tip:TipologiaStrutturaProdDoc>
		<tip:TipoMime>application/pdf+text/x-cda-r2+xml</tip:TipoMime>
		<tip:LivelloConfidenzialita>N</tip:LivelloConfidenzialita>
		<tip:TipologiaDocumentoAlto>REF</tip:TipologiaDocumentoAlto>
		<tip:TipologiaDocumentoMedio>11488-4</tip:TipologiaDocumentoMedio>
		<tip:TipologiaDocumentoBasso>PDF</tip:TipologiaDocumentoBasso>
		<tip:RiferimentoDocumento>2.16.840.1.113883.2.9.2.150.4.4^474625</tip:RiferimentoDocumento>
			<tip:Associazione>
				<tip:associationType>urn:ihe:iti:2007:AssociationType:RPLC</tip:associationType>
				<tip:sourceObject>doc1</tip:sourceObject>
				<tip:targetObject>2.16.840.1.113883.2.9.2.150.4.4^474625</tip:targetObject>
				<tip:submissionSetStatus>Original</tip:submissionSetStatus>
				<tip:previousVersion/>
            </tip:Associazione>
          <tip:IdentificativoUnivocoDocumento>doc1</tip:IdentificativoUnivocoDocumento>
		<tip:DataValidazioneDocumento>20240523153545</tip:DataValidazioneDocumento>
		<tip:RuoloAutore>DRS</tip:RuoloAutore>
		<tip:IstituzioneAutore>150201123456</tip:IstituzioneAutore>
			<tip:CodiceFiscaleAutore>PROVAX00X00X000Y</tip:CodiceFiscaleAutore>
		<tip:AssettoOrganizzativo>AD_PSC026</tip:AssettoOrganizzativo>
		<tip:TipoAttivitaClinica>DIS</tip:TipoAttivitaClinica>
		<tip:DataInizioPrestazione>20240523153545</tip:DataInizioPrestazione>
		<tip:DataFinePrestazione>20240523153545</tip:DataFinePrestazione>
	</com:Metadato>
	<com:IdentificativoApplicativoRichiedente>Ellipse AMB</com:IdentificativoApplicativoRichiedente>
	<com:FornitoreApplicativoRichiedente>Engineering Ingegneria Informatica S.p.A.</com:FornitoreApplicativoRichiedente>
	<com:VersioneApplicativoRichiedente>1.0.0</com:VersioneApplicativoRichiedente>
	<com:OpzioniRequest>
		<tip:chiave>GATEWAY</tip:chiave>
		<tip:valore>true</tip:valore>
	</com:OpzioniRequest>
		<com:OpzioniRequest>
			<tip:chiave>WORKFLOWINSTANCEID</tip:chiave>
			<tip:valore>2.16.840.1.113883.2.9.2.150.4.4.9a64f254c1ce1bdb76a84c7d0b1a4609a4db1233825eb611005e75c491fa6342.8cfb608282^^^^urn:ihe:iti:xdw:2013:workflowInstanceId</tip:valore>
		</com:OpzioniRequest>
		<com:OpzioniRequest>
			<tip:chiave>MODE</tip:chiave>
			<tip:valore>ATTACHMENT</tip:valore>
		</com:OpzioniRequest>
</com:ComunicazioneMetadatiRichiesta>`

**Comment by g-maugeri-sogei** [comment]
Va usato tip:IdentificativoDocumento per passare 2.16.840.1.113883.2.9.2.150.4.4^474625

**Comment by avlp** [comment]
Si riceve InternalError, ecco la request:
`<?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><com:ComunicazioneMetadatiRichiesta xmlns:com="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it" xmlns:tip="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it">
	<com:IdentificativoUtente>PROVAX00X00X000Y</com:IdentificativoUtente>
		<com:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</com:pinCode>
	<com:IdentificativoOrganizzazione>150</com:IdentificativoOrganizzazione>
	<com:StrutturaUtente>201123456</com:StrutturaUtente>
	<com:RuoloUtente>DRS</com:RuoloUtente>
	<com:ContestoOperativo>TREATMENT</com:ContestoOperativo>
	<com:TipoDocumento/>
	<com:IdentificativoAssistito>DCRNTN00M25F839J</com:IdentificativoAssistito>
	<com:PresaInCarico>true</com:PresaInCarico>
	<com:TipoAttivita>CREATE</com:TipoAttivita>
	<com:Metadato>
		<tip:TipologiaStrutturaProdDoc>Ospedale</tip:TipologiaStrutturaProdDoc>
		<tip:TipoMime>application/pdf+text/x-cda-r2+xml</tip:TipoMime>
		<tip:LivelloConfidenzialita>N</tip:LivelloConfidenzialita>
		<tip:TipologiaDocumentoAlto>REF</tip:TipologiaDocumentoAlto>
		<tip:TipologiaDocumentoMedio>11488-4</tip:TipologiaDocumentoMedio>
		<tip:TipologiaDocumentoBasso>PDF</tip:TipologiaDocumentoBasso>
		<tip:IdentificativoDocumento>2.16.840.1.113883.2.9.2.150.4.4^474625</tip:IdentificativoDocumento>
			<tip:Associazione>
				<tip:associationType>urn:ihe:iti:2007:AssociationType:RPLC</tip:associationType>
				<tip:sourceObject>doc1</tip:sourceObject>
				<tip:targetObject>2.16.840.1.113883.2.9.2.150.4.4^474625</tip:targetObject>
				<tip:submissionSetStatus>Original</tip:submissionSetStatus>
				<tip:previousVersion/>
            </tip:Associazione>
          <tip:IdentificativoUnivocoDocumento>doc1</tip:IdentificativoUnivocoDocumento>
		<tip:DataValidazioneDocumento>20240523153545</tip:DataValidazioneDocumento>
		<tip:RuoloAutore>DRS</tip:RuoloAutore>
		<tip:IstituzioneAutore>150201123456</tip:IstituzioneAutore>
			<tip:CodiceFiscaleAutore>PROVAX00X00X000Y</tip:CodiceFiscaleAutore>
		<tip:AssettoOrganizzativo>AD_PSC026</tip:AssettoOrganizzativo>
		<tip:TipoAttivitaClinica>DIS</tip:TipoAttivitaClinica>
		<tip:DataInizioPrestazione>20240523153545</tip:DataInizioPrestazione>
		<tip:DataFinePrestazione>20240523153545</tip:DataFinePrestazione>
	</com:Metadato>
	<com:IdentificativoApplicativoRichiedente>Ellipse AMB</com:IdentificativoApplicativoRichiedente>
	<com:FornitoreApplicativoRichiedente>Engineering Ingegneria Informatica S.p.A.</com:FornitoreApplicativoRichiedente>
	<com:VersioneApplicativoRichiedente>1.0.0</com:VersioneApplicativoRichiedente>
	<com:OpzioniRequest>
		<tip:chiave>GATEWAY</tip:chiave>
		<tip:valore>true</tip:valore>
	</com:OpzioniRequest>
		<com:OpzioniRequest>
			<tip:chiave>WORKFLOWINSTANCEID</tip:chiave>
			<tip:valore>2.16.840.1.113883.2.9.2.150.4.4.9a64f254c1ce1bdb76a84c7d0b1a4609a4db1233825eb611005e75c491fa6342.8cfb608282^^^^urn:ihe:iti:xdw:2013:workflowInstanceId</tip:valore>
		</com:OpzioniRequest>
		<com:OpzioniRequest>
			<tip:chiave>MODE</tip:chiave>
			<tip:valore>ATTACHMENT</tip:valore>
		</com:OpzioniRequest>
</com:ComunicazioneMetadatiRichiesta></soapenv:Body></soapenv:Envelope>`

**Comment by g-maugeri-sogei** [comment]
Occorre valorizzare sia <tip:RiferimentoDocumento> che <tip:targetObject> con il registry uuid.

**Comment by g-maugeri-sogei** [comment]
Come richiesto aggiungo un esmepio di replace:
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:com="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it" xmlns:tip="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it">
   <soapenv:Header/>
   <soapenv:Body>
      <com:ComunicazioneMetadatiRichiesta>
         <com:IdentificativoUtente>PROVAX00X00X000Y</com:IdentificativoUtente>
         <com:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</com:pinCode>
         <com:IdentificativoOrganizzazione>130</com:IdentificativoOrganizzazione>
         <com:StrutturaUtente>202123456</com:StrutturaUtente>
         <com:RuoloUtente>DRS</com:RuoloUtente>
         <com:ContestoOperativo>TREATMENT</com:ContestoOperativo>
         <com:TipoDocumento>11502-2</com:TipoDocumento>
         <com:IdentificativoAssistito>MRCLSN97C14H501J</com:IdentificativoAssistito>
         <com:PresaInCarico>true</com:PresaInCarico>
         <com:TipoAttivita>CREATE</com:TipoAttivita>
         <com:Metadato>
         		<tip:TipologiaStrutturaProdDoc>Territorio</tip:TipologiaStrutturaProdDoc>
         		<tip:TipoMime>application/pdf+text/x-cda-r2+xml</tip:TipoMime>
         		<tip:LivelloConfidenzialita>N</tip:LivelloConfidenzialita>
        		<tip:TipologiaDocumentoAlto>REF</tip:TipologiaDocumentoAlto>
            	<tip:TipologiaDocumentoMedio>11502-2</tip:TipologiaDocumentoMedio> 
            	<tip:TipologiaDocumentoBasso>2.16.840.1.113883.2.9.10.1.11.1.2</tip:TipologiaDocumentoBasso>
			<tip:RuoloAutore>DRS</tip:RuoloAutore>
			<tip:IstituzioneAutore>130202123456</tip:IstituzioneAutore>
			<tip:CodiceFiscaleAutore>PROVAX00X00X000Y</tip:CodiceFiscaleAutore>
			<tip:AssettoOrganizzativo>AD_PSC100</tip:AssettoOrganizzativo>
			<tip:TipoAttivitaClinica>CON</tip:TipoAttivitaClinica>		
			<tip:DataInizioPrestazione>20240205123000</tip:DataInizioPrestazione>
			<tip:DataFinePrestazione>20240205150000</tip:DataFinePrestazione>
            <tip:IdentificativoDocumento>2.16.840.1.113883.2.9.2.130.4.4^475633</tip:IdentificativoDocumento>   
			<tip:RiferimentoDocumento>urn:uuid:78672738-195a-40b9-a35a-c3b2c79eea45</tip:RiferimentoDocumento>	
			<tip:Associazione>
				<tip:associationType>urn:ihe:iti:2007:AssociationType:RPLC</tip:associationType>
				<tip:sourceObject>doc1</tip:sourceObject>
				<tip:targetObject>urn:uuid:78672738-195a-40b9-a35a-c3b2c79eea45</tip:targetObject>
				<tip:submissionSetStatus>Original</tip:submissionSetStatus>
				<tip:previousVersion></tip:previousVersion>         
			</tip:Associazione>
			<tip:IdentificativoUnivocoDocumento>doc1</tip:IdentificativoUnivocoDocumento>			
         </com:Metadato>
        <com:documento>cid:ALE_130_LAST.pdf</com:documento>
		<com:IdentificativoApplicativoRichiedente>Middleware980</com:IdentificativoApplicativoRichiedente>
		<com:FornitoreApplicativoRichiedente>Regione Sicilia</com:FornitoreApplicativoRichiedente>
		<com:VersioneApplicativoRichiedente>1.0</com:VersioneApplicativoRichiedente>
		<com:OpzioniRequest>
		  <tip:chiave>GATEWAY</tip:chiave>	
		  <tip:valore>true</tip:valore>
		</com:OpzioniRequest>
		<com:OpzioniRequest>
		  <tip:chiave>WORKFLOWINSTANCEID</tip:chiave>	
 <tip:valore>2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.fc68fdb689^^^^urn:ihe:iti:xdw:2013:workflowInstanceId</tip:valore>
		</com:OpzioniRequest>
		<com:OpzioniRequest>
		  <tip:chiave>MODE</tip:chiave>	
		  <tip:valore>ATTACHMENT</tip:valore>
		</com:OpzioniRequest>
      </com:ComunicazioneMetadatiRichiesta>
   </soapenv:Body>
</soapenv:Envelope>

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
