### ISSUE TITLE
Notifica operazione metadati -  HomeCommunityId

### ISSUE THREAD

**Issue by daniele-gubellini** [ministero-salute/it-fse-support#756]
Buongiorno,

stiamo ricevendo le notifiche di operazioni su metadati con il campo HomeCommunityId difforme dagli esempi.

Riceviamo:
  <HomeCommunityId>2.16.840.1.113883.2.9.2.80</HomeCommunityId>

Atteso da specifiche:
<HomeCommunityId>urn:oid:2.16.840.1.113883.2.9.2.80</HomeCommunityId>

Grazie

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
abbiamo corretto il problema.

**Comment by daniele-gubellini** [comment]
Buongiorno,
ora riceviamo 
`<HomeCommunityId>urn:oid:2.16.840.1.113883.2.9.2.80.3.1</HomeCommunityId>`

Le specifiche Affinity di HomeCommunityId sembrano indicare una granularità "RDA"  mentre qui sono stati aggiungi ".3.1" che non so come interpretare in questo contesto. 
Verrà adeguata la documentazione per indicare questa possibilità?

Grazie

**Comment by daniele-gubellini** [comment]
Avete fatto un aggiornamento? Ora ci arriva il valore "urn:oid:2.16.840.1.113883.2.9.2.80" e quindi le notifiche vengono accettate

**Comment by g-maugeri-sogei** [comment]
Confermo.
