### ISSUE TITLE
Request content not conform to API specification: UTF-8

### ISSUE THREAD

**Issue by angeloLSys** [ministero-salute/it-fse-support#757]
Buongiorno,
sono alle prese con i servizi di validazione ma da qualche giorno sto riscontrando problemi nella creazione della request. Mi da questo errore:

400 Bad Request: [{"type":"https://govway.org/handling-errors/400/InvalidRequestContent.html","title":"InvalidRequestContent","status":400,"detail":"Request content not conform to API specification: UTF-8;boundary=ojteUWfv1DZAp6cdIlBi0M2Zzhf69c_cbLgH9in","govway_id":"12f85756-fb04-11ee-93a7-005056ae54fa"}]

In allegato il codice con i relativi settaggi degli headers e del body.
![Screenshot 2024-04-15 110251](https://github.com/ministero-salute/it-fse-support/assets/167071660/96492fff-7180-4733-8687-ea1f7ecca35d)

Grazie in anticipo

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate è emerso che la request non è stata correttamente creata:
 
_Request ricevuta dal gateway:_

<img width="902" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/071e77c9-e67e-46db-86be-ece6eb4f0a78">


_Esempio messaggio di richiesta "Validazione con attachment"_

![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/2b64b68e-0fae-4759-a26a-08f71eb3a06e)

La invitiamo a consultare la documentazione al seguente link https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#3-servizio-di-validazione e modificare il codice in modo che la request rispetti le specifiche descritte.

**Comment by angeloLSys** [comment]
Buongiorno, ho aumentato la versione di springboot e l'errore non si ripresenta ma da errore sulla sintassi del CDA che provvederò a risolvere da solo, ma volevo chiedere se c'è modo di capire se la request ricevuta dal gateway adesso arriva formattata bene.

Di seguito l'errore:
422 Unprocessable Entity: "{"traceID":"829848849fff7407","spanID":"829848849fff7407","type":"/msg/semantic","title":"Errore semantico.","detail":"[ERRORE-20| L'elemento author/assignedAuthor DEVE contenere almeno un elemento 'telecom'],[W001| Si raccomanda di valorizzare gli attributi dell'elemento ClinicalDocument/code nel seguente modo: @codeSystemName ='LOINC' e @displayName ='Nota di consulto'--> ]","status":422,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.180.4.4.474e1037e52cf31d7581959a77d454aecbeebc7d3bf69e641478eced1ff956cb.f58706473b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}"

**Comment by vigliottim** [comment]
Buongiorno,
la request è stata costruita correttamente. Infatti, il file è stato validato e riceve un errore semantico.
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
