### ISSUE TITLE
Sprint 2 - richiesta verifica stato

### ISSUE THREAD

**Issue by avlp** [ministero-salute/it-fse-support#758]
Salve,
nell'ambito crash program di Regione Campania, Sprint 2, è stato inviato un nuovo documento per il paziente di test concordato ottenendo TEMP_150_816675. Si chiede elaborazione di tale referto in quanto in stato ELAB per proseguire con i successivi casi di test.

**Comment by IStacchiotti** [comment]
Buonasera, vi comunichiamo che verrà rilasciata una fix, seguiranno aggiornamenti appena disponibili, grazie.

**Comment by g-maugeri-sogei** [comment]
Fix rilasciata.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
