### ISSUE TITLE
Errore sul tentativo di validazione CDA 

### ISSUE THREAD

**Issue by rondellimediam** [ministero-salute/it-fse-support#759]
Buongiorno,
sto provando a validare un file xml CDA innestato in un pdf. Sto provando a lanciare il seguente comando da prompt di dos (i token sono abbreviati):

C:\Windows\System32\curl.exe 
-v -k https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation/ 
--cert-type P12 --cert C:/A1#111#MEDIAMX1.p12:*****    
-H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGaHpD..."   
-H "FSE-JWT-Signature: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGYURDQ0ExQ2..."   
-H "accept: application/json"   
-H "Content-Type: multipart/form-data"   
-F "requestBody={"healthDataFormat": "CDA", "mode": "ATTACHMENT", "activity": "VALIDATION"}"   
-F "file=@C:/provaCDA.pdf;type=application/pdf"

e mi viene restituito questo errore: SEC_E_CERT_UNKNOWN (0x80090327) - Errore sconosciuto durante l'elaborazione del certificato
Il certificato è stato generato da noi utilizzando il file di autenticazione .pem che ci è stato fornito da Sogei.

Potreste per favore aiutarmi?

**Comment by IStacchiotti** [comment]
Buonasera, per verificare la validità del certificato ottenuto, Le suggeriamo di fare un test con Postman seguendo le indicazioni riportate in questo [commento](https://github.com/ministero-salute/it-fse-support/issues/654#issuecomment-1985853383) nell'issue #654. Rimaniamo a disposizione, grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, 
Per verificare che i certificati siano stati generati correttamente la invitiamo ad effettuare una prova tramite postman come indicato nel messaggio precedente seguendo la guida indicata nel [commento](https://github.com/ministero-salute/it-fse-support/issues/654#issuecomment-1985853383). Restiamo a disposizione in caso l'errore dovesse persistere.
Grazie

**Comment by vigliottim** [comment]
Buongiorno, dall'errore ricevuto sembra che il certificato non sia stato creato correttamente.
La invitiamo a riprovare seguendo le istruzioni per generare i certificati p12 con _openssl_ riportate nel seguente screenshot:
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/b8e81178-0aac-466e-ab69-6e0d40695249)
Rimaniamo a disposizione per chiarimenti.

**Comment by rondellimediam** [comment]
Buongiorno, ho provato a eseguire il comando con openssl, ma mi viene richiesto il file .key, mentre io ho il file .jks. Non riesco a convertire il file .jks in .key. 
Devo quindi rifare la procedura di generazione dei file csr tramite openssl, in modo da avere poi i file .key oppure c'è un modo per utilizzare i file .jks?
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno,
per ottenere il .key la invitiamo a provare partendo dal p12 da lei generato in precedenza:

`openssl pkcs12 -in file.p12 -nocerts -out file.key`
 
Successivamente, può utilizzare il .key per la genreazione dei nuovi P12 tramite openssl:

`openssl pkcs12 -export -name alias_cert -out client_sign.p12 -inkey client_sign.key -in client_sign.pem`
 
Dove **alias_cert** è l'alias del certificato di firma ed è necessario impostarlo per utilizzare il tool jwt-generator.
In caso non dovesse funzionare la invitiamo a ripetere la procedura di generazione dei certificati utilizzando il file. key e openssl come indicato in [documentazione](https://github.com/ministero-salute/it-fse-support#richiesta-certificati-x509).
Grazie

**Comment by rondellimediam** [comment]
**Buongiorno, ho provato a seguire la procedura che mi ha indicato, mi viene restituito il seguente messaggio:**

 Trying 217.175.50.111:443...
* Connected to modipa-val.fse.salute.gov.it (217.175.50.111) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* ALPN: server did not agree on a protocol. Uses default.
* using HTTP/1.x
> POST /govway/rest/in/FSE/gateway/v1/documents/validation HTTP/1.1
> Host: modipa-val.fse.salute.gov.it
> User-Agent: curl/8.4.0
> Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGaHpDQ0EyK2dBd0lCQWdJVVA5d29ITGZlekNKaXFscWVhdXAybDk2ejNaNHdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlOREEwTURNeE5EQTRNREZhRncweU56QTBNRFF4TkRBNE1EQmFNR2t4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVI4d0hRWURWUVJoREJaRFJqcEpWQzFRVWs5V1FWZ3dNRmd3TUZnd01EQlpNUmd3RmdZRFZRUUREQTlCTVNNeE1URWpUVVZFU1VGTldERXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDdVRHb2piVHI3VDkzVGVuK1h3ODRxb2VKVm9pWVQzMUZHQzVYaCtUQ2I4aHFoSjhYdDNqakI1a0Qrb1g2RHJuWkR5QjhmY0R0WllTZ2NTQzlWZ2hibGp5RnNocHBIbW9FVEhHMCthcFNVQkdtWElVOVpDWk5ZZ0FhcHNISmNvdDVPaWVydENxWWRycnd2UGxnNVhkbDFJWEkyeElPakpaNjZybk00UXJwWWo2eFFWYVE4TG1YTHRrZlNsTTNJVC9IV1JBVWIxUDNFTzBCZWU3NkhVY2xIT1pJVzdNajNZbitxc01vK1JuYWYvTDQ1WnF0QXNzMGVjcWxGU3hvWThwUFE3dDJNcVdxemN3b1ZBS1B6ak9RajVJQ2xaVks1QXBhVkRJcy8zck1aa21icFd3VmdXdmdsQVZtM2pxWDJJVkxBVjFWNmh5djZQRVJNeGV6TDkxR1RBZ01CQUFHamdnRTNNSUlCTXpBZkJnTlZIU01FR0RBV2dCUVdPYWthQlltM0R5MnlOZTNDQ1pyRkE0TWlQekFTQmdOVkhTQUVDekFKTUFjR0JTdE1IUUVLTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQ0JnZ3JCZ0VGQlFjREFUQ0JyUVlEVlIwZkJJR2xNSUdpTUlHZm9JR2NvSUdaaG9HV2FIUjBjSE02THk5allYTnZaMlZwYzNacGJDNXpiMmRsYVM1cGRDOWxhbUpqWVM5d2RXSnNhV04zWldJdmQyVmlaR2x6ZEM5alpYSjBaR2x6ZEQ5amJXUTlZM0pzSm1semMzVmxjajFEVGlVelJFTkJLMDFwYm1semRHVnlieXRrWld4c1lTdFRZV3gxZEdVclZHVnpkQ1V5UTA4bE0wUk5hVzVwYzNSbGNtOHJaR1ZzYkdFclUyRnNkWFJsSlRKRFF5VXpSRWxVTUIwR0ExVWREZ1FXQkJSK1VRcXMvWmNxdkt4NlRDOUducDVybE9CU2N6QU9CZ05WSFE4QkFmOEVCQU1DQmFBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFFaHVvZTJrWEtuSXkzUFg0RXlkSnhlYUVUSG10em9FYVdzeml2RmFJZU9HemZ2Rklsb21Ia1l1THFRNkhTWHFnUUVuMDhBNzhTaGJHbld5VmI5Z1ZmS2FzeTBzeTZrNGtubnNEU3BhNk80QktZVnB3RGZNS2pBZzJHR3VKSlBYdFhlbzlOVDlVMDAwZ0RRRGE4RWo2d2FCUzF1TVpZU2Y2YlVwMjBBem9SdWVWMkJHa0F6WWZOUWh0T1M1V2dkNFUyRW5rVlQ3Szd0T2hKZXVqVnhXbnBWSW5GNy8yWmRsOVpTUUk5cW9QVC95bERicmd3Q295VnhGREtIWXRJTEFud0JKMDMxZTNmMjdpTndOWEFFWlk4Q0JJMW1veWlMUzFaTythdFNSNkZaRFBya1VaejhIRXNzbnVLSDJTektDbUtxSVA1NXdCR29FMnVUelB3ZkNkWXhyVEJJQUczTjJHSTRyWTlkU2hFd2liSXBwS0VZQTg5T010MVdBdndWcnNORDAyK1NlaEc2SDA0YW1hQzhzazBIZHlIVTRBQWtrVkRqUHRHSXJnZExSMUNMTHNjTHFpZHpTcHZBTWo5eWF3TFNJT1J6SGJVN3lsa1NzNTEwam4waHdHRXVNbXRidGlzOWJRcS9WVis3OEFrdlFhR0tuK21XNWZsL2N2MnBmVW1nRXBGR0J0dHRYb3g0S051eG4vL3BiaSs5bWlqZUwzOTNEOUJIWGJXNWVkMFFLZGpzMW4yWXVpeDBGYXFpYWs5NjV4aHBBN2UzL1V4WUV4OFJzU1hiOTlRMHUySjMrVzZOTXNWZ21INjF5VXFuUTdGOU8zemFHMVVBYXVDZ0pQdnpJVzMreDM0S05jMFl5U2l6ZjhybEFueHVsR2UxYVljS0dTMVpQRjB5SCJdfQ.eyJpc3MiOiJhdXRoOkExIzExMSNNRURJQU1YMSIsImp0aSI6IjEyMzQiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEvIiwic3ViIjoiUFJWVE5UOTdSMTREOTY5RF5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIiwibmJmIjoxNzEzMzM5ODIwLCJleHAiOjE3MTU5MzE4MjAsImlhdCI6MTcxMzMzOTgyMH0.M9f6Ak_soR1NteghNvBL4xj5FBeNwAK1r9vsWpKjWwRXhtbBx4ZhkcdLMGx6EX6lPXJQTfpsO3KYRNtm92p3QSZvKbfeVvOPQNN-9snVyvtGDyezPRYK-RRJpEzByKvqYtoVKmHGrxompEhfeChleNbu9owpFzYDLkRIubqBt8wU9QSDbX9sX6tVsADO7oIeleGNxMBEi_s-qk0sdXfFjB-qNhf3wE63GArfDpAXDcvO-HMDvPu8pldZIsoGcuILI-IAH7OUl28PsVuCIOVAFayc8mPLkiWEGn3bPw14uVz3tjfRG-sp0TilxOt6XpE5OgHJ9zOk2AAHugveZviDIw
> FSE-JWT-Signature: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGYURDQ0ExQ2dBd0lCQWdJVUNmNStIS0lLZHNEcVZzamNrYnd4QzR6RFpjZ3dEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlOREEwTURNeE5EQTRNREZhRncweU56QTBNRFF4TkRBNE1EQmFNR2t4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVI4d0hRWURWUVJoREJaRFJqcEpWQzFRVWs5V1FWZ3dNRmd3TUZnd01EQlpNUmd3RmdZRFZRUUREQTlUTVNNeE1URWpUVVZFU1VGTldERXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDSUVFMWxrQzBQMmZsTUp2aStxRDJjdjZxT3hXWG1XZDRGd09Vdmpzd1J1WFlldEY5dDNKS2kxMjEyWW1PcXp0RHBWMDVQdkFrb3lWMlBpc2RObnFVaXZIbFhTZk5ZNkNkT2JGWnByR2YvdVdlSDFYUHhwdUtXZU85V2JwWFNxRkZpU0NXMGJUdTlkcHhsby9SYnQxZVN2TkRYMmsvd0NmUWMxc1lqNnZKMkszQUJRZ1NyYXd1a0VndTZyQ1YxNGdsSlBoQ2RDRm5UNi8zcCsyMmloU2pVMS9hZHVDYjhGbU5najJFVlFVaFU2YTMvWG40NlB6VHJoR0IvK21MeXNEcTBYM0RoMXB4Mms5TUFpdGIzQlFoWGZZL0g5ZDh6Y2U0TW5PN3FtcGJmc3YzZ3BzNVQ2a2dLTG1RN2h2cUkrMFprb09vYlhwTmIzVVJnOG9rRDN1NTNBZ01CQUFHamdnRVlNSUlCRkRBZkJnTlZIU01FR0RBV2dCUVdPYWthQlltM0R5MnlOZTNDQ1pyRkE0TWlQekFTQmdOVkhTQUVDekFKTUFjR0JTdE1IUUVMTUlHdEJnTlZIUjhFZ2FVd2dhSXdnWitnZ1p5Z2dabUdnWlpvZEhSd2N6b3ZMMk5oYzI5blpXbHpkbWxzTG5OdloyVnBMbWwwTDJWcVltTmhMM0IxWW14cFkzZGxZaTkzWldKa2FYTjBMMk5sY25Sa2FYTjBQMk50WkQxamNtd21hWE56ZFdWeVBVTk9KVE5FUTBFclRXbHVhWE4wWlhKdksyUmxiR3hoSzFOaGJIVjBaU3RVWlhOMEpUSkRUeVV6UkUxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVWxNa05ESlRORVNWUXdIUVlEVlIwT0JCWUVGSm83WnFxY0FadGV1dndHWjVZYURJUTJaYXc2TUE0R0ExVWREd0VCL3dRRUF3SUdRREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBYnliYVdFZDdvSGxsQ1FML2o5eStkeTJ0NkJZSDJ0bmNlbmUwd1M0eS9ydE91SW51Njc4b3l1aDE2SWV3VjFMWDQ0ZjNERTA0bHlWY1lPaXljZm1Jd1hFb1dRVGR6R1BOZlhDY1hJcWVOK0EvM2ljQ2xNeWFVdWRiY1hnMEpMYTFWMm8zQVFha1Y0VVNCT3lGTHQwdy9raVVRN0xpQUs2aCtFemo1NjQyOFdnaTBLSWp5V1NmaWNsNksvUkp6S3dWeDlaMHk1WG1jdnlMcHYxeHl6b0ZVQmZuQ3A3MWowUG1GOTFyNHM5cUphOHdXZWkybmVzYkxDU1RDSEhMME4zTzdBbFZTc0VUMFVpMEJ3M0gwUjNkcXZocEs2NnJETkFhTkdOV0taWFNyUjBCbk91aklIck5KeThwQXZ0TlQzaGxvUFZIM1RhWS9aS3ZsS3VjOW9WeHNyYnZGaHdsZU5UTG9QU01hSldleEFrWlhwcWNMSkVSaEUrQTQzbzk0UTNqSHgxZHErVzZ4WjQybFlmaDNDeHJuSCt6WHpuVHBXVk1OSjBseEd1Z1h6eU0yM2VTRDRIZE4xQWRYTFdPWnk3WndaS2Zla1h5NExDODV6bUhVWDlDOUdOcmN0SXV1cENwc0g2RFdFY2twdEpIbjdYd0ZTck1aSDVUMzBLTk42S2pQUUowdmwxL1NGMnJ4Vy9YZFZNcmpTV3JSU0JVZkM2ZTBoNzdVdW51YjRRRUZIdjJhaFFDdzVlUWVKTzdCeDZ1S2h4Z0ZTS2JQQ09GV2kyZzNraEozT1BERkZ3WXJUb2g2cmpXRURxRWRDWWNlekxWcUZycEs1SmxSRXNab0ljcElIQit5S3dtU3QwVHZLNWZ4YWIxdytLNHpnNXgzTTc2RlVCdnpDVzhwdUU9Il19.eyJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExI01FRElBTVgxIiwianRpIjoiMTIzNCIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MS8iLCJzdWIiOiJQUlZUTlQ5N1IxNEQ5NjlEXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X29yZ2FuaXphdGlvbl9pZCI6IjA3MCIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBMaWd1cmlhIiwibG9jYWxpdHkiOiJqd3QtbG9jYXRpb24iLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsInBhdGllbnRfY29uc2VudCI6dHJ1ZSwicGVyc29uX2lkIjoiU01CUlBUNDNSNjlaMjQwUF5eXiZhbXA7Mi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJmFtcDtJU08iLCJhY3Rpb25faWQiOiJUUkVBVE1FTlQiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiTGluZmEiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlbmRvciI6Ik1lZGlhbSBTZXJ2aXppIHNybCIsInN1YmplY3RfYXBwbGljYXRpb25fdmVyc2lvbiI6IjEuNy4wLjAiLCJuYmYiOjE3MTMzMzk4MjEsImV4cCI6MTcxNTkzMTgyMSwiaWF0IjoxNzEzMzM5ODIxfQ.zUZ_MZdFxYjrRu0277xfsN6_4Ti3UhcXXjmtmfPVBG373DqJimjGl0tSn0QkCyY_TnWBQni7tRoojzTVbqVsOuJMxZhv9JRC_hcgeeEy91iq_py5v8nG9icQ9CAtZMdPtxSgq3l9IluuyWxCzEVRSUVyGptQWZbwBGGPyIb-QxIV6dM7H4a2ZoCyi-3PuVWvZzqPC_vYny5vQt5xuvE_q-nvPtiVHpzsUNqps5mgiiSmo07b-SOIO47XaHkNm5fuD-VpmQOgnbsh-RWw1etI6fmO807gtR9i6XHh8aIQMfrWFvkJ5Ta99mZVAYVA0T87aOvnMwtnlAPsJg7-YmoGHg
> accept: application/json
> Content-Length: 366
> Content-Type: multipart/form-data; boundary=------------------------sxq5jun2dvg0lWcMnpBpKD
>
* We are completely uploaded and fine
* Recv failure: Connection was reset
* schannel: recv returned CURLE_RECV_ERROR
* Closing connection
* schannel: shutting down SSL/TLS connection with modipa-val.fse.salute.gov.it port 443
* Send failure: Connection was reset
* schannel: failed to send close msg: Failed sending data to the peer (bytes written: -1)
curl: (56) Recv failure: Connection was reset

**In particolare mi lascia perplesso il messaggio " schannel: disabled automatic use of client certificate"** 
**Sapreste aiutarmi per favore a capire l'errore?**

**Comment by LucaRogledi** [comment]
Buongiorno, 
Per verificare la validità dei certificati utilizzati la invitiamo ad effettuare una chiamata tramite postman.
Restiamo a disposizione per eventuale ulteriore supporto.
Grazie

**Comment by rondellimediam** [comment]
Buongiorno, ho richiesto a Sogei dei nuovi certificati, dopo aver creato i file .csr e .key con openssl.

**Comment by LucaRogledi** [comment]
Buongiorno,
procediamo alla chiusura della presente issue. La invitiamo gentilmente ad aprire una nuova issue in caso di nuove richieste di supporto. Grazie
