### ISSUE TITLE
Errore in verifica cda

### ISSUE THREAD

**Issue by Jack19650524** [ministero-salute/it-fse-support#760]
Buongiorno,
quando tento di verificare un cda con versione superiore ad uno, mi viene segnalato questo errore
traceID: "ba3d535d759a3b8a"
spanID: "ba3d535d759a3b8a"
type: "/msg/syntax"
title: "Errore di sintassi."
detail: "ERROR: -1,-1 cvc-complex-type.2.4.a: Invalid content was found starting with element 'code'. One of '{"urn:hl7-org:v3":templateId, "urn:hl7-org:v3":id}' is expected."
status: 400
instance: "/validation/error"
workflowInstanceId: "2.16.840.1.113883.2.9.4.3.2.cd20836b0e6a0f493b214db3a1cf752d028899fcda65ff93784ed103b9763383.5b928f104d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
Grazie.

**Comment by Jack19650524** [comment]
Buonasera,
[CDA-2024041504172691.pdf](https://github.com/ministero-salute/it-fse-support/files/14980337/CDA-2024041504172691.pdf)

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate è emerso che l'elemento _<ClinicalDocument>/<id>_, obbligatorio secondo la guida HL7 Italia per PSS (http://www.hl7italia.it/hl7italia_D7/Implementation%20Guide%20CDA%202%20-%20Profilo%20Sanitario%20Sintetico), non è presente nel CDA2 da lei utilizzato: 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/8439d06a-fc31-4c5c-835d-b875a02eb4c5)
La invitiamo ad aggiungerlo e riprovare.
Inoltre, le inviamo il link di un esempio di CDA2 per PSS che può esserle d'aiuto per strutturare correttamente l'xml: https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/PSS.xml
Rimaniamo a disposizione per chiarimenti.

**Comment by Jack19650524** [comment]
Grazie molte.

**Comment by vigliottim** [comment]
Grazie a lei per il suo gentile feedback.
Rimaniamo a disposizione per altre richieste di supporto.
