### ISSUE TITLE
Errore 403 in validazione

### ISSUE THREAD

**Issue by embrunoR** [ministero-salute/it-fse-support#762]
Buongiorno,
Stiamo provando ad invocare il servizio di validazione con "govway_id": "90efbc26-fbca-11ee-9223-005056ae7395". Stiamo invocando il servizio sia tramite postman, che con CURL. Per entrambe le risposte riceviamo un 403.
L'appId utilizzato nel token è "Gestione Ambulatoriale", e il vendor "Santer Reply".
Potete fornirmi supporto ? Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, 
dalle analisi è emerso che all'interno del "X-Security-Token" è stato utilizzato il certificato di firma S1 invece di quello di trasporto A1.
La invitiamo a verificare l'utilizzo del certificato di autenticazione A1 come certificato di trasporto e il certificato S1 per la generazione dei token Bearer e Signature.
Restiamo a disposizione per eventuali chiarimenti.
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
