### ISSUE TITLE
validazione del referto di Radioterapia come sistema RSA

### ISSUE THREAD

**Issue by FSEMosaiq** [ministero-salute/it-fse-support#767]
Buongiorno,

- confrontando la lista dei campi obbligatori presenti nel caso di test 1, i campi che descrivono le procedure operative (ClinicalDocument/component/structuredBody/component/section[@id=Prestazioni]/entry/act/entryRelationship) risultano obbligatori. Nella Radioterapia, il referto prodotto riguarda soltanto le visite, per cui non abbiamo strutturalmente questo tipo di informazioni.
- riferendomi alle specifiche dei casi di test 2 (test da sforzo-cicloergometro), caso di test 3 (colposcopia) e caso di test 4 , essi prevedono delle casistiche e metodiche che non sono contemplate nella Radioterapia. Per questi test é necessario attenersi a queste specifiche? 

Grazie
Saluti

**Comment by vigliottim** [comment]
Buongiorno, i campi obbligatori da specifiche non possono essere omessi. 
Pertanto, nel caso particolare in cui i dati non siano disponibili a sistema oppure nel caso in cui non si possa completare il test case correttamente, è possibile indicare NO nell’apposita colonna _"Applicabilità"_, avendo cura di giustificarlo opportunamente nella colonna _"razionale di applicabilità"_. 
Nel caso in cui non ci sia nessun test OK applicabile anche solo per un CDA, dovrà fare riferimento alla [checklist](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/accreditamento-checklist_V8.1.3.xlsx) e compilare il _caso di test 0_ (sempre applicabile) che prevede esclusivamente i campi obbligatori secondo HL7 Italia.
Infine, le segnaliamo che è disponibile il tool [gwt-certifier](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/gtw-certifier) che consente di riprodurre in locale le verifiche dei test case di validazione OK richiesti durante la fase di accreditamento.
Rimaniamo a disposizione per ulteriore supporto.

**Comment by FSEMosaiq** [comment]
Grazie per la celere risposta. 
Analizzando gli altri 'modelli', forse la refertazione della Radioterapia, potrebbe essere più simile a quella della Radiologia RAD. Al limite potremmo cambiare il modello di riferimento per i test? 
Saluti

**Comment by LucaRogledi** [comment]
Buonasera,
per il referto della radioterapia è più corretto utilizzare la tipologia documentale RSA piuttosto che il RAD. 
Per i casi di test che non riesce a riprodurre, si consiglia di indicarli come "Non Applicabili".
Restiamo a disposizione per eventuali chiarimenti.
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
