### ISSUE TITLE
Errore InteroperabilityInvalidRequest servizio di validazione

### ISSUE THREAD

**Issue by MerialdoElco** [ministero-salute/it-fse-support#768]
Buongiorno,
stiamo provando ad invocare il gateway per effettuare la validazione di un documento, ma riceviamo in risposta questo messaggio di errore:
`{
	"type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
	"title": "InteroperabilityInvalidRequest",
	"status": 400,
	"detail": "Received request is not conform to the required interoperability profile",
	"govway_id": "0f0cd821-fc7f-11ee-93a7-005056ae54fa"
}`
potete indicarci cosa non va? In passato riuscivamo ad effettuare correttamente la validazione

**Comment by vigliottim** [comment]
Buongiorno, dalle analisi effettuate sui log, è emerso che sta utilizzando il token prima della sua data di validità: 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/106e9918-acf8-4172-9735-96976786588b)
Inoltre, le segnaliamo la presenza del campo _nbf_ nell'_Authentication Bearer Token_, non previsto secondo le specifiche (https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt).
La invitiamo ad utilizzare un token valido e riprovare. Grazie.

**Comment by MerialdoElco** [comment]
Buongiorno, abbiamo corretto e abbiamo effettuato dei nuovi tentativi con esito positivo. Grazie
