### ISSUE TITLE
CRASH PROGRAM - Sostituzione documento - Missing metadata - association of type HasMember is mandatory

### ISSUE THREAD

**Issue by cdezorzi** [ministero-salute/it-fse-support#769]
Buongiorno, 
stiamo testando l a Sostituzione del documento prediamo un errore nel SEND_TO_INI " XDSMissingDocumentMetadataCODE CONTEXT:Missing metadata - association of type HasMember is mandatory"

di seguito la response dello status:

{
    "traceID": "ac26e3ed6e1acf57",
    "spanID": "8688fc9e54a6e03d",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-04-16T10:40:25.870+00:00",
            "eventStatus": "SUCCESS",
            "subject": "BLRNDR68L13G920R^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "090",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.5ba9017bdb^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "ef54919d3f5ff081",
            "issuer": "integrity:S1#090#090REGIONETOSCANA-TEST",
            "expiringDate": "2025-04-16T10:40:25.881+00:00"
        },
        {
            "eventType": "REPLACE",
            "eventDate": "2024-04-16T10:40:59.465+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.90.4.4^9999.LAB.910.3974",
            "subject": "BLRNDR68L13G920R^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "DIS",
            "organizzazione": "090",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.5ba9017bdb^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "ea2fc8c3290ea399",
            "issuer": "integrity:S1#090#090REGIONETOSCANA-TEST",
            "expiringDate": "2025-04-16T10:40:59.476+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-04-16T10:41:00.039+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSMissingDocumentMetadataCODE CONTEXT:Missing metadata - association of type HasMember is mandatory",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.5ba9017bdb^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-04-16T10:41:00.048+00:00"
        }
    ]
}
Grazie per il supporto.

**Comment by vigliottim** [comment]
Buonasera,
è stata rilasciata una nuova fix.
Le chiediamo gentilmente di riprovare.
Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
