### ISSUE TITLE
PUBBLICAZIONE - Errore in fase di recupero dell'esito della verifica

### ISSUE THREAD

**Issue by cravell** [ministero-salute/it-fse-support#77]
Salve,
nel pubblicare un CDA2 validato verso il gateway otteniamo il messaggio di errore 'CDA2 non validato' Riporto i dati di dettaglio:

- DATI VALIDAZIONE
`{
	"traceID": "5ad12c25b3cb8309",
	"spanID": "5ad12c25b3cb8309",
	"workflowInstanceId": "2.16.840.1.113883.2.9.2.150.4.1.a86d58489a3e274727346c7b0f19e02d7891db4849c83c7af354dc109ce8d369.cb1cff98c6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}`
- DATI PUBBLICAZIONE
`workflowInstanceId": "2.16.840.1.113883.2.9.2.150.4.1.a86d58489a3e274727346c7b0f19e02d7891db4849c83c7af354dc109ce8d369.cb1cff98c6
"traceID":"fe9ab30f2f0ae31f","spanID":"fe9ab30f2f0ae31f"`

**Comment by Ser-ena** [comment]
Buonasera, l'errore sembrerebbe generato da una non coincidenza degli hash tra validazione e pubblicazione; al fine di poter condurre un'analisi piu' approfondita potrebbe cortesemente allegare sia il pdf di validazione che quello di pubblicazione utilzzato nelle chiamate?  Grazie mille

**Comment by cravell** [comment]
In Allegato i verbali,
abbiamo eseguito un nuovo test e riporto le info aggiornate:
DATI VALIDAZIONE
`{"traceID":"4840b7fca68c7665","spanID":"4840b7fca68c7665","workflowInstanceId":"2.16.840.1.113883.2.9.2.150.4.1.273bf24b0a2ab0e62e83d0053d823e94131b8f22c9a7760b1baa3ade29d80fae.b82277215e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`
DATI PUBBLICAZIONE:
`traceID: "6911fff7f8c8d1cb"
spanID: "6911fff7f8c8d1cb"
Detail: "Errore in fase di recupero dell'esito della verifica.; Il CDA non risulta validato"`

In allegato i documenti utilizzati per l'invio
[Uploading VERBALE_PS_20230000027_Pubblicato.pdf…]()

**Comment by Ser-ena** [comment]
Salve, potrebbe cortesemente ri-allegare il file? Non si riesce a scaricare.

**Comment by cravell** [comment]
In allegato i file:

[VERBALE_PS_20230000027_Pubblicato.pdf](https://github.com/ministero-salute/it-fse-support/files/10569745/VERBALE_PS_20230000027_Pubblicato.pdf)
[VERBALE_PS_20230000027_Validato.pdf](https://github.com/ministero-salute/it-fse-support/files/10569747/VERBALE_PS_20230000027_Validato.pdf)

**Comment by cravell** [comment]
Per info il doc pdf validato non ha la firma digitale.
Una volta ricevuto ack positivo dalla validazione del gateway procediamo alla firma ed al successivo invio per la pubblicazione.
Quindi l'hash del pdf è sicuramente diverso mentre quello del cda è lo stesso.

**Comment by cravell** [comment]
Salve,
l'errore che viene segnalato in fase di pubblicazione è il seguente:
`{"traceID":"b638b9637f776e19","spanID":"b638b9637f776e19","type":"/msg/fhir-mapping-type","title":"Mapping fhir fallito.","detail":"Error while perform transform cda to bundle:Rule \"time\": target context not known: note","status":400,"instance":"/fhir-resource"}`

é leggermente diverso da quello segnalato nel thread #94, è possibile avere un dettaglio su questo errore?

**Comment by Ser-ena** [comment]
Salve, potreste cortesemente allegare il CDA2 utilizzato per l'ultimo test?

**Comment by IStacchiotti** [comment]
Buongiorno @cravell, il problema dovrebbe essere rientrato. Potrebbe riprovare cortesemente? Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
