### ISSUE TITLE
SINED : aggiornamento application vendor (20240417.2)

### ISSUE THREAD

**Issue by mghi-sined** [ministero-salute/it-fse-support#772]
Buongiorno,

come da vostra indicazione, abbiamo aggiornato l'application vendor nel PATH . Ora c'è la stringa "Sined S.r.l." ( con lo spazio) al posto di "Sined_S.r.l." .   Ora la terna appId,appVersion,appVendor è la seguente; 

appId : MedWare
appVersion: 24.02.12
appVendor: Sined S.r.l.

Questa terna è presente:

1. nel PATH su GITHUB;
2. nel file data.json
3. nel file report-checklist.xlsx
4. nella costruzione del token JWT in fase di chiamata al GATEWAY.

Cordiali Saluti,
Massimo Ghirardello

**Comment by vigliottim** [comment]
Buongiorno, la ringraziamo per l'aggiornamento e le confermiamo che le modifiche sono state correttamente effettuate. Riceverà aggiornamenti sull'esito delle elaborazioni via e-mail.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
