### ISSUE TITLE
Info su 4. Servizio di Creazione

### ISSUE THREAD

**Issue by enzocap** [ministero-salute/it-fse-support#773]
Buongiorno,
ho effettuato delle Validazioni con Attachment che hanno avuto riscontro positivo (workflowInstanceId): vorrei capire le differenze con Verifica con Attachment e Verifica con resource (quali sono i casi di utilizzo).
Inoltre, dovendo passare ai test di Pubblicazione, vorrei sapere come valorizzare i campi obbligatori relativi alla Tabella 10, con particolare riferimento e/o esempi relativi ai Referti di Laboratorio Analisi.

Grazie. Saluti.

**Comment by enzocap** [comment]
Buonasera,
purtroppo il documento indicato riporta solo dei rimandi ad altra documetazione.

Per esempio, nel caso di XDSDocumentEntry.uniqueId rimanda a:
"Codifica OID, come specificato al paragrafo 2.20 del documento Affinity Domain " 

Nel documento "Specifiche tecniche per l’interoperabilità tra i sistemi regionali di FSE" al paragrafo 2.0 leggo:

[CONF-18] L’OID da utilizzare per il metadato uniqueId deve essere strutturato nel seguente modo: per i documenti gestiti da un sistema di FSE regionale, il valore deve essere 2.16.840.1.113883.2.9.2.[REGIONE].4.4^X, dove X rappresenta una specifica istanza di documento presente in regione; per i documenti gestiti da Sistema TS, il valore deve essere 2.16.840.1.113883.2.9.4.3.8^Y, dove Y rappresenta una specifica istanza di documento presente nel Sistema TS (ad esempio Y è pari al NRE per la prescrizione dematerializzata). Il valore [REGIONE] è il valore corrispondente alla regione indicato in Tabella 6.4-3 (la prima cifra numerica pari a 0 va omessa).

Ma se sto pubblicando un nuovo documento ex novo (p.e. un referto di laboratorio analisi), dove trovo queste informazioni?

Grazie. Saluti.

**Comment by IStacchiotti** [comment]
Buongiorno, segnaliamo che in produzione la X viene staccata dal Repository documentale.
Ai fini dell'accreditamento, per lo svolgimento dei test previsti, la X può essere valorizzata con un codice numerico, come riportato nello sheet "Prerequisiti", cella B11 della checklist. Segnaliamo tuttavia che l'accreditamento per il servizio di pubblicazione è sospeso attualmente: la invitiamo a monitorare il canale #fse su Slack per aggiornamenti in merito. Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
