### ISSUE TITLE
tentativo accreditamento

### ISSUE THREAD

**Issue by ciampysara** [ministero-salute/it-fse-support#774]
Salve stiamo provando a superare i test di accreditamento ma nel log ci dice per i test dell'altra tipologia documentale già accreditata
{
  "id" : 65,
  "error" : "DATE_BEFORE",
  "description" : "Data test antecedente all'ultimo test accreditato"
},

come facciamo per risolvere il problema?

**Comment by IStacchiotti** [comment]
Buongiorno,
 
gli errori legati ai CDA già accreditati (LDO in questo caso) sono dovuti al fatto che i file report-checklist e data.json riportano i dati relativi ai test eseguiti in precedenza: nel momento in cui si aggiunge un nuovo CDA da accreditare, invece, è necessario ripetere i test per tutte quante le tipologie di documento accreditate, come indicato in [documentazione ](https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#nuova-tipologia-documentale-per-applicativo-gi%C3%A0-presente-nella-lista-dei-software-convalidati).
Di solito consigliamo di inviare fin da subito una checklist comprensiva di tutti i CDA per i quali si intende accreditarsi, poichè altrimenti sarebbe necessario ripetere tutti i casi di test ogni qualvolta si intenda aggiungere una nuova tipologia documentale.

Rimaniamo a disposizione per ulteriori chiarimenti o richieste di supporto, grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
