### ISSUE TITLE
Notifica operazione metadati - semantica campo HomeCommunityID

### ISSUE THREAD

**Issue by daniele-gubellini** [ministero-salute/it-fse-support#775]
Buongiorno,

L'empio del messaggio di notifica operazione metadati presente nelle specifiche è il seguente:

`<HomeCommunityId>urn:oid:2.16.840.1.113883.2.9.2.80</HomeCommunityId>   <RepositoryUniqueId>2.16.840.1.113883.2.9.2.150.4.5.113883</RepositoryUniqueId><DocumentUniqueId>2.16.840.1.113883.2.9.2.150.4.4^012345</DocumentUniqueId>`

Come si vede, viene indicato un documento prodotto dalla regione 150, ovviamente in un repository della regione 150 e quindi questa notifica è destinata alla regione RDE 150.
Il campo HomeCommunityId riporta invece la regione 080,  e noi abbiamo inteso che in questo campo ci fosse la RDA verso cui è stato indicizzato/aggiornato il documento.

Ricevendo le notifiche di avvenuta pubblicazione sull'indice temporaneo (Sprint 2), riceviamo come HomeCommunityId noi stessi (080) e non INI (980)
 
Abbiamo interpretato male le specifiche?

**Comment by pFonziSogei** [comment]
Salve, al massimo per la giornata del 6/05 verrà rilasciata la Fix che inserisce il valore corretto da Tabella 4.1-2 dell'Affinity Domain

**Comment by g-maugeri-sogei** [comment]
Fix rilasciata.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto riscontri, procediamo alla chiusura del presente ticket. 
Sarà possibile riaprirlo nel caso in cui abbia bisogno di ulteriore supporto. Grazie.
