### ISSUE TITLE
SINED: Aggiornamento casi di test 45,48,37,40 (20240418.1)

### ISSUE THREAD

**Issue by mghi-sined** [ministero-salute/it-fse-support#776]
Buongiorno, 

abbiamo provveduto ad aggiornare e ripubblicate i casi di test 45,48,37,40, come indicato nella vostra ultima mail.
In particolare:

1. abbiamo aggiornato il file report-checklist.xlsx in corrispondenza dei casi di test 45 e 48 , andando a dettagliare meglio nella colonna "GESTIONE ERRORE" ( colonna P del file report-checklist.xlsx)  l'iter di gestione dell'errore di TIMEOUT 
2. abbiamo rieseguito i test 37 e 40, compilando il campo "action_id" all'interno del token JWT con il valore "TEST", come da istruzioni indicate nella colonna "DESCRIZIONE CASO TEST" (colonna E) del file report-checklist.xlsx . In precedenza, avevamo erroneamente pubblicato il messaggio di errore che si riferiva ad una errata compilazione del campo "purpose_of_use" sempre del token JWT . Poichè abbiamo rieseguito oggi i test, sono stati aggiornati:
- il file report-checklist.xls ;  
- il llfile data.json 
- sono stati rispediti di due PDF associati a questo test 

I dati identificativi della applicazione in accreditamento sono:

commonName auth: A1#111SINEDXX
subject_application_vendor: Sined S.r.l.
subject_application_id: MedWare
subject_application_version: 24.02.12

Cordiali Saluti,
Massimo Ghirardello

**Comment by LucaRogledi** [comment]
Buonasera, grazie per l'aggiornamento. Perde di validità allora la mail condivisa ieri 17/04 in cui veniva confermato il superamento dei test indicati come applicabili. Verranno eseguite nuovamente le verifiche e riceverà un nuovo riscontro a valle via email.
