### ISSUE TITLE
differenze tra validazione case 0 e case 1,2,3,4

### ISSUE THREAD

**Issue by FSEMosaiq** [ministero-salute/it-fse-support#778]
buongiorno,

potreste chiarire la differenza tra le validazioni tra i case 0, 1, 2,3, 4 e la loro validità.
Quale è la modalità corretta per attribuire il modello corretto alla disciplina? Nel caso specifico si parla della radioterapia.

grazie

**Comment by LucaRogledi** [comment]
Buongiorno,
Come indicato nel ticket #767 La tipologia documentale più corretta da utilizzare per radioterapia è RSA - Referto di Specialistica Ambulatoriale. 
I test case 0, 1, 2, 3 e 4 sono test di validazione OK che si distinguono tra loro per le specifiche relative al CDA. Può trovare le istruzioni per compilare correttamente i test al seguente link, all'interno dei rispettivi fogli "RSA - Caso di Test X": [CDA2_Referto_Specialistica_Ambulatoriale_OK.xlsx](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/7-Referto%20Specialistico%20Ambulatoriale/CDA2_Referto_Specialistica_Ambulatoriale_OK.xlsx).
Restiamo a disposizione per eventuali chiarimenti.
Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
