### ISSUE TITLE
Errore "Duplicate key 2.16.840.1.113883.2.9.4.3.2" servizio di validazione

### ISSUE THREAD

**Issue by vittorioveneziano** [ministero-salute/it-fse-support#779]
Buongiorno,
stiamo provando ad invocare il gateway per effettuare la validazione di un documento, ma riceviamo in risposta questo messaggio di errore:
"Duplicate key 2.16.840.1.113883.2.9.4.3.2"

Potreste gentilmente indicarci cosa c'è che non va?

Grazie
Cordiali saluti

V. E. Veneziano

**Comment by LucaRogledi** [comment]
Buonasera,
Dalle  nostre verifiche l'errore sembrerebbe essere dovuto dalla presenza del tag a linea 17 del cda:
`<id root="2.16.840.1.113883.2.9.2.10202.4.1" extension="VNTFLV67R07L113D" assigningAuthorityName="PACS"/> `
Rimuovendo l'intera linea la validazione funziona correttamente, la invitiamo a riprovare dopo la correzione.
Grazie
