### ISSUE TITLE
Errore in Validazione - Valorizzazione ClinicalDocument.id e ClinicalDocument.setId

### ISSUE THREAD

**Issue by NunzioAgfa** [ministero-salute/it-fse-support#78]
Nella validazione della prima versione di un referto (referto originale), se ClinicalDocument.id e ClinicalDocument.setId sono diversi viene visualizzato il seguente errore:
[ERRORE-8|: Se ClinicalDocument.id e ClinicalDocument.setId usano lo stesso dominio di identificazione (@root identico) allora l’attributo @extension del ClinicalDocument.id deve essere diverso da quello del ClinicalDocument.setId a meno che ClinicalDocument.versionNumber non sia uguale ad 1; cioè i valori del setId ed id per un documento clinico possono coincidere solo per la prima versione di un documento.]

In realtà anche nella stessa descrizione dell'errore che viene restituito è scritto che i due campi setId e id "possono coincidere" solo per la prima versione, ma se nella prima versione non vengono impostati con lo stesso valore non riesco a validare. Devono quindi essere categoricamente uguali per la prima versione? Nel nostro applicativo utilizziamo questa convenzione (validata in molte integrazioni):

Prima versione:
id: accessionNumber + "R1"
setId: accessionNumber
Versioni successive
id: accessionNumber + "Rn" (n >=2)
setId: accessionNumber

Riporto i dati di una chiamata effettuata:
{
  "traceID" : "31fb0f811a08f856",
  "spanID" : "31fb0f811a08f856",
  "type" : "/msg/semantic",
  "title" : "Errore semantico.",
  "detail" : "[ERRORE-8|: Se ClinicalDocument.id e ClinicalDocument.setId usano lo stesso dominio di identificazione (@root identico) allora l'attributo @extension del ClinicalDocument.id deve essere diverso da quello del ClinicalDocument.setId a meno che ClinicalDocument.versionNumber non sia uguale ad 1; cioè i valori del setId ed id per un documento clinico possono coincidere solo per la prima versione di un documento.]",
  "status" : 422,
  "instance" : "/validation/error",
  "workflowInstanceId" : "2.16.840.1.113883.2.9.2.160112.02af19b890d84113b45a6c4b4fe69c3f0a3c02f4d5f48c02d9f02c379d7c5fff.f2908a4ce9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

**Comment by Ser-ena** [comment]
Buonasera, nella guida viene riportata la seguente conformance rule, che esplicita come deve essere valorizzato l'elemento setId alla prima versione del documento:

CONF-: Se l'elemento ClinicalDocument/relatedDocument manca, l'attributo ClinicalDocument/setId/@root DEVE essere valorizzato come ClinicalDocument/id/@root, l'attributo @extension come ClinicalDocument/id/@extension, l'attributo @assigningAuthorityName come ClinicalDocument/id/@assigningAuthorityName.

**Comment by IStacchiotti** [comment]
Non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
