### ISSUE TITLE
CRASH PROGRAM - FVG - UC3_Aggiornamento_Metadati - Errori XDS

### ISSUE THREAD

**Issue by ChiaraCeccottiFVG** [ministero-salute/it-fse-support#780]
Buongiorno,
abbiamo riprovato ad eseguire il test UC3_Aggiornamento_Metadati per lo sprint 1

Riferimento documento: 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LAB1713528638498
CF: PRVNSL72B68L101R
"workflowInstanceId": "2.16.840.1.113883.2.9.2.60207.3.1.4.4.8ff073d4f6e01db38991629257b185b0647c467e6e9286604f6de06f6114d382.2d1e418392^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
"traceId": "f3a429dc023facfa"

Otteniamo i seguenti errori legati allo standard XDS:

```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
	<soap:Header>
		<Action xmlns="http://www.w3.org/2005/08/addressing">urn:ihe:iti:2007:RegisterDocumentSet-bResponse</Action>
		<MessageID xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:bfb0b312-c733-41fe-be9b-c91032a84b64</MessageID>
		<To xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</To>
		<RelatesTo xmlns="http://www.w3.org/2005/08/addressing">6a4ae528-fa64-422b-a379-117d432633b0</RelatesTo>
	</soap:Header>
	<soap:Body>
		<ns2:RegistryResponse xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns4="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure">
			<ns2:RegistryErrorList>
				<ns2:RegistryError codeContext="RegistryPackage urn:uuid:072d3a0f-6647-41fd-9166-d1d185001c63 : is not Classified as either a Submission Set or Folder: Submission Set must have classification urn:uuid:a54d6aa5-d40d-43f9-88c5-b4633d873bdd and Folder must have classification urn:uuid:d9d542f3-6cc4-48b6-8870-ea235fbc94c2" errorCode="XDSRegistryMetadataError" location="Attribute.java" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"/>
				<ns2:RegistryError codeContext="ExtrinsicObject urn:uuid:020c6620-ca76-4573-94b2-9b6496e63f91 has a author type classification (classificationScheme=urn:uuid:93606bcf-9494-43ec-9b4e-a7748d1a838d) with no nodeRepresentation attribute.  It is required and must be the empty string." errorCode="XDSRegistryMetadataError" location="Attribute.java" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"/>
				<ns2:RegistryError codeContext="Classification (classificationScheme=urn:uuid:6c955772-ab84-4bf1-b6bd-a31eaad5f7dd codingScheme=2.16.840.1.113883.2.9.3.3.6.1.3) of object urn:uuid:020c6620-ca76-4573-94b2-9b6496e63f91: The code, P99, is not found in the configuration for the Affinity Domain" errorCode="XDSRegistryMetadataError" location="CodeValidation.java" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"/>
				<ns2:RegistryError codeContext="Metadata Validation Errors:&#10; Classification &lt;Classification Name=&quot;Oscuramento del documento&quot; id=&quot;IdEventCodeList&quot;&gt;&#10;   is nested inside &lt;ExtrinsicObject id=&quot;urn:uuid:020c6620-ca76-4573-94b2-9b6496e63f91&quot;&gt;&#10;   but classifies object &lt;Unknown object urn:uuid:2c6b8cb7-8b2a-4051-b291-b1ae6a575ef4&gt;" errorCode="XDSRegistryMetadataError" location="&#10;&#9;it.fvg.santer.xds.common.registry.validation.Validator.validate_internal_classifications(Validator.java:106)&#10;&#9;it.fvg.santer.xds.common.registry.validation.Validator.run(Validator.java:83)&#10;&#9;it.fvg.santer.xds.rgy.ws.SubmitObjectsRequest.SubmitObjectsRequestInternal(SubmitObjectsRequest.java:301)&#10;&#9;it.fvg.santer.xds.rgy.ws.SubmitObjectsRequest.submitObjectsRequest(SubmitObjectsRequest.java:156)&#10;&#9;it.fvg.santer.xds.rgy.ws.serviceclasses.AbstractRegistry.SubmitObjectsRequest(AbstractRegistry.java:69)&#10;&#9;sun.reflect.GeneratedMethodAccessor378.invoke(Unknown Source)&#10;&#9;sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#10;&#9;java.lang.reflect.Method.invoke(Method.java:498)&#10;&#9;it.fvg.santer.xds.common.service.AbstractXDSRawXMLINoutMessageReceiver.invokeBusinessLogic(AbstractXDSRawXMLINoutMessageReceiver.java:146)&#10;&#9;org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40)&#10;&#9;org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:106)&#10;&#9;org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:169)&#10;&#9;org.apache.axis2.transport.http.HTTPTransportUtils.processHTTPPostRequest(HTTPTransportUtils.java:178)&#10;&#9;org.apache.axis2.transport.http.AxisServlet.doPost(AxisServlet.java:163)&#10;&#9;javax.servlet.http.HttpServlet.service(HttpServlet.java:648)&#10;" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"/>
			</ns2:RegistryErrorList>
		</ns2:RegistryResponse>
	</soap:Body>
</soap:Envelope>
```

In particolare abbiamo notato che:

1. Il registryPackage e l’extrinsicObject hanno id valorizzato con un identificativo strutturato come uuid (anziché con il nome simbolico). E' necessario poi riportare la corenza in tutti gli oggetti che contengono (Association e Classification e ExternalIdentifier) in modo opportuno.
2. Nell'extrinsticObject l'id e il lid devono essere diversi. Nel caso di test il lid = "urn:uuid:020c6620-ca76-4573-94b2-9b6496e63f91" è corretto, mentre l'id deve essere diverso (simbolico tipo Document01 e poi riportato coerentemente. Si veda punto1)
3. Nell'ExtrinsicObject urn:uuid:020c6620-ca76-4573-94b2-9b6496e63f91 ha un author type classification ma manca l'attributo nodeRepresentation che è obbligatorio e deve essere impostato a stringa vuota (nodeRepresentation="")
4. il classificationScheme della classification DocumentEntry.IdEventCodeList deve essere "urn:uuid:2c6b8cb7-8b2a-4051-b291-b1ae6a575ef4" (P99) mentre nella metadata update è: "urn:uuid:6c955772-ab84-4bf1-b6bd-a31eaad5f7dd"
5. il submissionSet.uniqueId ha attributo registryObject="registryObject" anzichè l'id del registryPackage.
6. il submissionSet.SourceId ha attributo registryObject="d9475e93-1547-491f-b471-6163a14a457a" anzichè l'id del registryPackage.
7. il submissionSet.SourceId ha attributo registryObject="4daf3438-dcf6-440b-9024-d95d03477892" anzichè l'id del registryPackage.
8. Il Submission Set deve avere la classification urn:uuid:a54d6aa5-d40d-43f9-88c5-b4633d873bdd attualmente mancante. Esempio:
```
<ns2:Classification classificationNode="urn:uuid:a54d6aa5-d40d-43f9-88c5-b4633d873bdd"
classifiedObject="Submission01"
id="Classification1"
objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification"/>
```
9. Non ci deve essere l'association con RPLC
10. Lo slot <ns2:Slot name="intendedRecipient"> presenta OID 2.16.840.1.113883.2.9.2.060 ma va impostato 2.16.840.1.113883.2.9.2.60

Riuscireste a verificare?
Ringraziando molto per la collaborazione auguriamo un buon pomeriggio.

**Comment by IStacchiotti** [comment]
Buongiorno,

è stata rilasciata una nuova fix. Le chiediamo gentilmente di riprovare. Grazie.

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
abbiamo eseguito un test e confermiamo anche l'aggiornamento metadati è avvenuta con successo (Id documento: 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LAB1713776749315).
Ringraziamo per la collaborazione e auguriamo una buona giornata.

**Comment by IStacchiotti** [comment]
Buongiorno, grazie mille per il riscontro. Procediamo alla chiusura del presente, rimanendo a disposizione per eventuali ulteriori richieste di supporto.
