### ISSUE TITLE
WRONG_CLAIMS_ON_LOG

### ISSUE THREAD

**Issue by embrunoR** [ministero-salute/it-fse-support#781]
Buongiorno, in merito alla PR con ID #1355 ho ricevuto un errors.json di errore. 
Per quanto riguarda il test con ID 150, mi sembra di capire che abbiamo valorizzato male delle section obbligatorie e/o opzionali, ricreando l'xml il problema dovrebbe risolversi. 

Per quanto riguarda i test con ID 374  che appId,appVersion,appVendor ricevete voi  ? A me sembra di averli valorizzati correttamente. 
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno,
Le confermiamo che per il caso di test con id `150` gli errori sono dovuti alla valorizzazione dei campi del cda. Può effettuare la correzione dei campi seguendo le indicazioni presenti nello sheet "RSA - Caso di Test 4" del documento scaricabile dal seguente link: [CDA2_Referto_Specialistica_Ambulatoriale_OK.xlsx]( https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/7-Referto%20Specialistico%20Ambulatoriale/CDA2_Referto_Specialistica_Ambulatoriale_OK.xlsx ).

Riguardo il caso di test con id `374` tramite il servizio di status, risulta che il `"workflowInstanceId": "2.16.840.1.113883.2.9.2.30.4.4.b93f00453fbe188731188972855624651b00baa1e7e39919a341105583ba3899.f63d41e64a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"` (effettuato in data 2023-12-21) utilizzato nel data.json, non corrisponda al test effettuato con `"traceId": "f57ed398f8358023"` (effettuato in data 2024-04-16). La invitiamo gentilmente a verificare ed inserire, tramite nuova pr, sia nella checklist che nel json, la coppia traceId-workflowInstanceId corrispondente allo stesso test effettuato.
Grazie

**Comment by embrunoR** [comment]
Correggo i file e risottometto una PR. 
Se dovessero essere problemi successivi aprirò un'altra segnalazione ? 
 
Io ritengo chiusa la segnalazione attuale.
Ringrazio per il supporto.

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Rigraziamo per il feedback e procediamo alla chiusura della presente issue.
Rimaniamo a disposizione e può procedere con l'apertura di una nuova issue in caso di ulteriore supporto.
Grazie
