### ISSUE TITLE
Sprint 3 - cancellazione - RDE Emilia-Romagna

### ISSUE THREAD

**Issue by xenergy33** [ministero-salute/it-fse-support#782]
Abbiamo provato a cancellare il documento con identificativoDoc  2.16.840.1.113883.2.9.2.80.4.4^105800053000080124TESTSPS3144176, prodotto per l'utente CF: CRSFCN90D41A944T, traceId dell'operazione: 10db243365f39f82.

In risposta riceviamo questo:
{"traceID":"000000000000000010db243365f39f82","spanID":"28e6621032669846","type":"/errors","title":"Generic","detail":"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: javax.transaction.TransactionRolledbackException:  ; nested exception is: \n\tjavax.transaction.SystemException Please see the server log to find more detail regarding exact cause of the failure.","instance":"error/generic"}

Restiamo in attesa di informazioni.
Grazie.
Raffaele

**Comment by IStacchiotti** [comment]
Buonasera, dalle verifiche è emerso che problema del rollback sembrerebbe riconducibile alla Regione stessa.
Potreste fare una verifica?
Rimaniamo in attesa di un gentile riscontro, grazie

**Comment by xenergy33** [comment]
Buongiorno,
abbiamo verificato e non riscontriamo anomalie dal nostro lato, ricordo che in questo caso siamo solo RDE, la RDA è la Regione Campania che è in sussidiarietà e quindi gestita da SOGEI. Aggiungo che non abbiamo problemi a cancellare documenti dove siamo anche RDA. Vi chiediamo pertanto un'ulteriore verifica lato regione RDA.
Restiamo in attesa del vostro riscontro. 
Grazie.
Raffaele

**Comment by bborruso** [comment]
Buongiorno, come specificato nella email di gestioneTS, la transazione di cancellazione sulla RDA Campania è stata eseguita con successo. Al fine di verificare come mai avete visualizzato uno status non congruente con il valore atteso, ci servirebbe che provaste a replicare il test in modo da poter analizzare i trace in tempo reale.
Grazie

**Comment by xenergy33** [comment]
Buongiorno, abbiamo creato un nuovo documento traceid: 8d6b6b8afd214719 
2.16.840.1.113883.2.9.2.80.3.1.4.4.beb9cf4b2079f414540ea4d4e3c4052deac001a1698d7f0bcc2c9f1f2c64180f.efefb1a5e8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
ma riceviamo lo stesso errore in cancellazione con http 500: {"traceID":"0000000000000000395017202fe08257","spanID":"415b0dc49c64da29","type":"/errors","title":"Generic","detail":"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: javax.transaction.TransactionRolledbackException:  ; nested exception is: \n\tjavax.transaction.SystemException Please see the server log to find more detail regarding exact cause of the failure.","instance":"error/generic"}

Restiamo in attesa.
Grazie.
Raffaele

**Comment by g-maugeri-sogei** [comment]
Ci confermate che sul client che chiama il GTW avete un read timeout di 15 secondi?

**Comment by xenergy33** [comment]
Attualmente il time out impostato è di 20 secondi.

**Comment by g-maugeri-sogei** [comment]
Buongiorno, sul nostro ambiente di test abbiamo riscontrato problemi di latenza su alcuni apparati che causano il problema descritto. In attesa di risolverlo, visto che si tratta di test funzionali, potreste ovviare al problema lato vostro aumentando il timeout di lettura nelle chiamate tra il vostro client e il gateway.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso in cui sia necessario ulteriore supporto. Grazie.
