### ISSUE TITLE
Middleware - Scenario trasporto regionale, firma produttore

### ISSUE THREAD

**Issue by ntrave** [ministero-salute/it-fse-support#783]
Buongiorno,
stiamo eseguendo alcune prove di integrazione con un produttore locale per verificare lo scenario 
**2.1. Caso 1 (trasporto regionale, firma produttore)** delle specifiche (https://github.com/ministero-salute/it-fse-support/tree/main/doc/middleware-regionale), nel quale i JWT sono firmati con i certificati dei produttori, mentre il certificato di autenticazione mTLS è quello del Middleware regionale.

Abbiamo eseguito diverse invocazioni, tuttavia riscontriamo alcuni problemi in quanto otteniamo una risposta "403 AuthorizationContentDeny".

Una delle chiamate è stata eseguita alle 11:02:50 di oggi 22/04/2024 con risposta: 
`{type=https://govway.org/handling-errors/403/AuthorizationContentDeny.html, title=AuthorizationContentDeny, status=403, detail=Unauthorized request content, govway_id=b3cff2a7-0083-11ef-93a7-005056ae54fa}`
Nel file 
[Token.txt](https://github.com/ministero-salute/it-fse-support/files/15063807/Token.txt)
allegato i token utilizzati.

Se invece si invoca il Gateway con i certificati dei produttori sia per la firma dei token che per la mTLS, la chiamata va a buon fine.

Rimaniamo a disposizione per eventuali chiarimenti.
Grazie.

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
segnaliamo che l’errore dipende dal fatto che si sta utilizzando un certificato di trasporto (`A1#070000000000XX.p12`) non corretto per la chiamata tramite Middleware: è necessario chiedere un certificato regionale sotto la regione fittizia 111 (`A1#111***`) facendo richiesta via email a fse_support@sogei.it. 
Vi invitiamo pertanto a riprovare con il nuovo certificato e a darci un gentile riscontro a valle.
Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.

**Comment by ntrave** [comment]
Buongiorno, abbiamo aggiornato i certificati ed ora riusciamo a comunicare correttamente con il Gateway.
Grazie.
