### ISSUE TITLE
Possibili scenari per la validazione/accreditamento

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#784]
Buongiorno, abbiamo concluso con successo la produzione dei CDA di RAD,LAB ed RSA, tutti validati dalle vostre API, ora dobbiamo preparare i test case. Mi avete già detto che è preferibile inviarli tutti insieme (142!!!) ma, sebbene il programma sia unico, le versioni sono differenti per branca specialistica, mi chiedo se non sia più opportuno (e semplice) procedere per branca.
Giusto per chiarire, il nostro applicativo, FLY, si divide in FLY LAB, FLY RX e FLY POLI/FKT).
Se volessimo procedere a differenziare gli accreditamenti, quale sarebbe la procedura da seguire? Basta inviare 3 richieste separate variando solo il nome del programma? (FKT e POLI utilizzano la stessa tipologia di referto, RSA).
Grazie per l'attenzione.

**Comment by IStacchiotti** [comment]
Buongiorno,
 
il processo di accreditamento deve essere affrontato per tripletta identificativa software_vendor/software_application/software_version. Di conseguenza, se il vostro applicativo supporta funzionalità diverse ma mantiene i riferimenti INFOSERVICE/FLY/2.0, non è possibile procedere all'accreditamento dei diversi CDA in maniera atomica.
Ad ogni modo, come indicato in documentazione (https://github.com/ministero-salute/it-fse-accreditamento/blob/main/README.md#nuova-tipologia-documentale-per-applicativo-gi%C3%A0-presente-nella-lista-dei-software-convalidati), è possibile sottomettere un CDA (ad esempio RSA)in un primo momento e, una volta ottenuta la convalida, procedere all'accreditamento di un nuovo CDA (ad esempio LDO). Sottolineamo tuttavia, che quando viene aggiunta una nuova tipologia documentale, occorre rieseguire le chiamate e risottomettere tutti i file relativi alla tipologia documentale già accreditata (RSA). 
Rinnoviamo dunque il consiglio di inviare fin da subito una checklist comprensiva di tutti i CDA per i quali si intende accreditarsi.
 
Un saluto, 
il team FSE 2.0

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
