### ISSUE TITLE
CRASH PROGRAM - RT- Aggiornamento_Metadati - Sprint 3

### ISSUE THREAD

**Issue by cdezorzi** [ministero-salute/it-fse-support#786]
Buongiorno, 
abbiamo eseguito il test UC4_Aggiornamento_Metadati per lo sprint 3 , ma riscontriamo il seguente errore:
{
    "traceID": "df3b3e2d837a7c87",
    "spanID": "df3b3e2d837a7c87",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "detail": "{\"traceID\":\"0000000000000000df3b3e2d837a7c87\",\"spanID\":\"86ae91b7c5c6a592\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error\",\"instance\":\"error/generic\"}",
    "status": 500,
    "instance": "/msg/service-error/ini"
}

E' possiile avere un riscontro?
Grazie per la collaborazione

**Comment by EugenioGuagliardi** [comment]
Buonasera,
lato Lombardia vediamo arrivare una transazione di aggiornamento che va in Errore.
La transazione che vediamo è la seguente:

<ns2:ExternalIdentifier id="urn:uuid:f9dfd805-b4cd-410d-836e-9108c4b2a79b" identificationScheme="urn:uuid:2e82c1f6-a085-4c72-9da3-8640a32e42ab" lid="urn:uuid:f9dfd805-b4cd-410d-836e-9108c4b2a79b" registryObject="Document1" value="2.16.840.1.113883.2.9.2.90.4.4^9999.LAB.910.3930">
<ns2:Name>
<ns2:LocalizedString charset="UTF-8" value="XDSDocumentEntry.uniqueId" xml:lang="en-US"/>
</ns2:Name>
<ns2:VersionInfo versionName="1"/>
</ns2:ExternalIdentifier> 

Stiamo verificando l'errore , vi aggiorniamo appena abbiamo novità.

Grazie

**Comment by EugenioGuagliardi** [comment]
Buongiorno, abbiamo verificato e risolto l'anomalia. Potete effettuare un nuovo Test?
Grazie

**Comment by cdezorzi** [comment]
Buongiorno, abbiamo eseguito nuovo test
riscontriamo il seguente errore:

idDocumento : 2.16.840.1.113883.2.9.2.90.4.4^9999.LAB.910.3938

{
    "traceID": "dfbaf1ad0f53197c",
    "spanID": "dfbaf1ad0f53197c",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "detail": "{\"traceID\":\"0000000000000000dfbaf1ad0f53197c\",\"spanID\":\"f900ad94a76cdb36\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error\",\"instance\":\"error/generic\"}",
    "status": 500,
    "instance": "/msg/service-error/ini"
}

Grazie

**Comment by EugenioGuagliardi** [comment]
Salve, cortesemente vi chiediamo di riprovare perché abbiamo avuto problemi sulla registrazione dei log, adesso abbiamo una situazione pulita su cui poter fare delle verifiche puntuali.

Grazie

**Comment by vigliottim** [comment]
Buonsera,
procediamo alla chiusura della presente issue poiché non più attuale essendo terminato il Crash Program.
Grazie.
