### ISSUE TITLE
CRASH PROGRAM - Messaggio creazione metadati da INI

### ISSUE THREAD

**Issue by daniele-gubellini** [ministero-salute/it-fse-support#789]
Come Emilia-Romagna facciamo periodicamente test di non regressione indicizzando su noi stessi ( RDE=RDA=Emilia Romagna )

Dal 23/04 pomeriggio dai messaggi che riceviamo da INI, all'interno dell'elemento _RegistryPackage_ , sono scomparsi gli elementi _Classification_ per _authorRole_, _authorInstitution_, _authorPerson_, che invece sono presenti all'interno dell'elemento _ExtrinsicObject_

Potreste verificare?

Grazie

**Comment by Ser-ena** [comment]
Buonasera, è stata rilasciata una fix per correggere la segnalazione.
Potreste cortesemente effettuare una verifica?

**Comment by daniele-gubellini** [comment]
Siamo riusciti a indicizzare su noi stessi (RDE=RDA=Emilia Romagna)
 Grazie
