### ISSUE TITLE
dubbi sul  match del codice fiscale del cda e del token jwt

### ISSUE THREAD

**Issue by nturri1306** [ministero-salute/it-fse-support#79]
salve un dubbio sul codice fiscale nel xml del cda che genera il pdf c'è 

```
	<patientRole classCode="PAT">
			<id root="2.16.840.1.113883.2.9.4.3.2" extension="RSSMRA75C03F839K" assigningAuthorityName="MEF"/>
```

 e nel token che viene passato

` "person_id":"RSSMRA75C03F839K^^^&2.16.840.1.113883.2.9.4.3.2&ISO"`

 se provo a validarlo nel servizio di test ricevo 

{
    "traceID": "312db1546a3bfd8d",
    "spanID": "312db1546a3bfd8d",
    "type": "/msg/jwt-validation",
    "title": "Campo token JWT non valido.",
    "detail": "JWT payload: Person id presente nel JWT differente dal codice fiscale del paziente previsto sul CDA",
    "status": 403,
    "instance": "/jwt-person-id",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.cd148013b3^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

**Comment by nturri1306** [comment]
salve ho cambiato tipologia di documento sono passato da referto di laboratorio a certificato vaccinale singolo e il test è passato probabili che sia legato al CDA del documento come errore

**Comment by IStacchiotti** [comment]
Ci risulta che il codice fiscale all'interno del JWT è il seguente:
- "person_id": "**RSSMRA75C03F839K**^^^&2.16.840.1.113883.2.9.4.3.2&ISO"
Mentre nel PDF viene specificato il seguente patient id:
- id root="2.16.840.1.113883.2.9.4.3.2" extension="**GTWGWY82B42G920M**" assigningAuthorityName="MEF".
L'errore era dovuto con tutta probabilità all'incongruenza dei due. Grazie.

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
