### ISSUE TITLE
Errore sostituzione documento PSS

### ISSUE THREAD

**Issue by ciampysara** [ministero-salute/it-fse-support#790]
Salve stiamo provando ad eseguire il caso 305 (PUBBLICAZIONE E SOSTITUZIONE) ma riceviamo un errore per il quale non capiamo il moitvo 

HTTP/1.1 403 Forbidden
X-Backside-Transport: FAIL FAIL
Connection: Keep-Alive
Transfer-Encoding: chunked
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
Server: GovWay-SOGEI
Pragma: no-cache
GovWay-Transaction-ErrorType: AuthorizationContentDeny
GovWay-Transaction-ID: caf78727-06c8-11ef-9223-005056ae7395
Date: Tue, 30 Apr 2024 08:33:19 GMT
Vary: *
X-Content-Type-Options: nosniff
Content-Type: application/problem+json
X-Global-Transaction-ID: 3f7e3e2d6630accf16700c7d

{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"caf78727-06c8-11ef-9223-005056ae7395"}

**Comment by LucaRogledi** [comment]
Buongiorno,
dalle analisi è emerso che all'interno della chiamata ricevuta dal gateway è stato utilizzato il Bearer token sia come Bearer che come Signature token. La invitiamo gentilmente a riprovare correggendo i due token utilizzati.
Grazie

**Comment by ciampysara** [comment]
Abbiamo riprovato e ci torna il seguente errore
Nonostante il file sia stato precedentemente pubblicato

HTTP/1.1 404 Not Found
X-Backside-Transport: FAIL FAIL
Connection: Keep-Alive
Transfer-Encoding: chunked
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
set-cookie: 894d46ecfc124039ee218b63c12a3329=6caa4f1bda74e3b3b757b7fa19072d6f; path=/; HttpOnly; Secure; SameSite=None
Server: GovWay-SOGEI
Pragma: no-cache
GovWay-Message-ID: b159a065-0d61-498c-af9e-4d73c86017cd
GovWay-Transaction-ID: 7acb4553-06d4-11ef-93a7-005056ae54fa
server-timing: intid;desc=6a9cf9415d845c69
content-disposition: inline;filename=f.txt
Date: Tue, 30 Apr 2024 09:54:01 GMT
Vary: *
X-Content-Type-Options: nosniff
Content-Type: application/problem+json
X-Global-Transaction-ID: 3f7e3e2d6630bfb61680d8cd

{"traceID":"cfe0041fc7f2f45e","spanID":"cfe0041fc7f2f45e","type":"/msg/record-not-found","title":"Record non trovato.","detail":"No Record Found","instance":"/record-not-found"}

**Comment by LucaRogledi** [comment]
Buongiorno,
La invitiamo a verificare che all'interno dell'url della chiamata di `Sostituzione` cosi composta:
`https://<HOST>:<PORT>/v<major>/documents/<identificativoDocUpdate>`
il parametro `<identificativoDocUpdate>` sia stato valorizzato con lo stesso valore utilizzato per il parametro `"identificativoDoc"` presente all'interno della requestBody della chiamata di `Pubblicazione` (facendo attenzione ad applicare l'urlencode - [tool online utilizzabile per urlencode](https://www.freeformatter.com/url-encoder.html#before-output) ).

- Esempio di "identificativoDoc" in requestBody di Pubblicazione **(urlencode non applicato)**: 
`"2.16.840.1.113883.2.9.2.60.4.4^123TEST"`

- Esempio di url per la chiamata di Sostituzione del documento pubblicato "2.16.840.1.113883.2.9.2.60.4.4^123TEST" **(urlencode applicato all'identificativo documento)**:
 `https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.60.4.4%5E123TEST`

In caso dovesse riscontrare nuovamente l'errore la invitiamo gentilmente a riportare la risposta ricevuta da entrambe le chiamate di Pubblicazione e Sostituzione.
Restiamo a disposizione per ulteriore supporto.
Grazie

**Comment by ciampysara** [comment]
Buongiorno abbiamo capito il motivo, era necessario riportare nell'url come identificativoDocUpdate anche la parola chiave SKIP_VALIDATION
