### ISSUE TITLE
Crash Program  - Sprint3 - RDE Lombardia , RDA Toscana - UC6 - Errore in pubblicazione pre Sostituzione

### ISSUE THREAD

**Issue by EugenioGuagliardi** [ministero-salute/it-fse-support#791]
Salve,
eseguendo il test previsto in UC6 CP Sprint3 in cui si ha RDE Lombardia , RDA Toscana otteniamo un errore nella fase pubblicazione del DCE da sostituire 

di seguito lo STATUS:

```
{
    "traceID": "0534038de74cc7b7",
    "spanID": "0519290b65510aa4",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-05-02T09:45:30.379+00:00",
            "eventStatus": "SUCCESS",
            "subject": "MDCMRZ90A41F205Q^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.58077cae41^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "df112dd9ee62f365",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-05-02T09:45:30.390+00:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-05-02T09:45:31.592+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.ae5b90b8-0868-11ef-a9d8-0242a89a8ac7",
            "subject": "MDCMRZ90A41F205Q^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "ERP",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.58077cae41^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "8ac6c564b0bcd20d",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-05-02T09:45:31.602+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-05-02T09:45:35.275+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R159CODE CONTEXT:Wrong value of entryUUID",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.58077cae41^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-05-02T09:45:35.337+00:00"
        }
    ]
}
```

Rimaniamo in attesa di vostre verifiche.

Grazie

**Comment by cdezorzi** [comment]
Buongiorno, la issue è stata presa in carico la stiamo analizzando.
Grazie

**Comment by OmarLorenzini** [comment]
abbiamo fatto un deploy potete riprovare?

**Comment by EugenioGuagliardi** [comment]
Salve, abbiamo riprovato ma otteniamo ancora un errore nella sostituzione.
Di seguito l'output della transazione del Gateway:

| dataOra = 2024 - 05 - 03 14: 41: 18: 765 | server = null | ID_DC = 76baddc9 - a477 - 4f07 - 8e10 - ee9d7a3179f7 | ID_COOP = null | elapsed = 7489 | DIR = CLI | OUT = /govway/rest / in / FSE / gateway / v1 / documents / 2.16.840.1.113883.2.9.2.30.4.4 % 5E030703.RRDOCU.1581ae76 - 094a - 11ef - a9d8 - 0242a89a8ac7 # null # {
    "traceID": "57fa251d0cf890ba",
    "spanID": "57fa251d0cf890ba",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "detail": "{\"traceID\":\"000000000000000057fa251d0cf890ba\",\"spanID\":\"16240a8ea677cf35\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"RDA generated an internal error.\",\"instance\":\"error/generic\"}",
    "status": 500,
    "instance": "/msg/service-error/ini"
}

Potete verificare?
Grazie

**Comment by rserrano73** [comment]
Abbiamo preso in carico la segnalazione. 
Dai log si evince l'errore: "Nessun documento del tipo richiesto è registrato per il paziente indicato"
Stiamo risolvendo. Vi aggiorniamo asap.

**Comment by rserrano73** [comment]
Abbiamo aggiornato la situazione per il CF dell'Assistito KRNLXD35E55I956K. Potete procedere con riprovare il test.

**Comment by EugenioGuagliardi** [comment]
Salve,
abbiamo riprovato oggi ma abbiamo lo stesso errore:

| dataOra = 2024 - 05 - 06 09: 42: 31: 024 | server = null | ID_DC = cca4e8a8 - 66ff - 4a7d - b813 - bb8004f1ad6e | ID_COOP = null | elapsed = 7417 | DIR = CLI | OUT = /govway/rest / in / FSE / gateway / v1 / documents / 2.16.840.1.113883.2.9.2.30.4.4 % 5E030703.RRDOCU.0f120fde - 0b7c - 11ef - a9d8 - 0242a89a8ac7 # null # {
    "traceID": "8902038683cb4ceb",
    "spanID": "8902038683cb4ceb",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "detail": "{\"traceID\":\"00000000000000008902038683cb4ceb\",\"spanID\":\"27f8a7f15aad39e1\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"RDA generated an internal error.\",\"instance\":\"error/generic\"}",
    "status": 500,
    "instance": "/msg/service-error/ini"
}

**Comment by EugenioGuagliardi** [comment]
Salve,
oggi abbiamo effettuato un nuovo test ottenendo sempre lo stesso errore.
Potete verificare?
Restiamo in attesa di un vostro riscontro per completare le nostre attività di test.

Grazie
