### ISSUE TITLE
Crash Program - Sprint3 - RDE Lombardia , RDA Toscana - Errore in pubblicazione Prerequisito Cancellazione UC8 

### ISSUE THREAD

**Issue by EugenioGuagliardi** [ministero-salute/it-fse-support#792]
Salve,
eseguendo il test previsto in UC8 CP Sprint3 in cui si ha RDE Lombardia ed RDA Toscana, 
otteniamo un errore nella fase di pubblicazione del DCE da cancellare

di seguito lo STATUS:

```
{
    "traceID": "b6bd1dd711a145c3",
    "spanID": "b0d7a5cb5c1ab154",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-05-02T12:34:44.374+00:00",
            "eventStatus": "SUCCESS",
            "subject": "MDCMRZ90A41F205Q^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.5a8ecf5e24^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "3f6a2b49edcff28f",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-05-02T12:34:44.383+00:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-05-02T12:34:45.731+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.551968a0-0880-11ef-a9d8-0242a89a8ac7",
            "subject": "MDCMRZ90A41F205Q^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "ERP",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.5a8ecf5e24^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "ff41d12234693fba",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-05-02T12:34:45.742+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-05-02T12:35:36.187+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R159CODE CONTEXT:Wrong value of entryUUID",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.5a8ecf5e24^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-05-02T12:35:36.253+00:00"
        }
    ]
}
```

Cortesemente potete verificare?
Grazie

**Comment by cdezorzi** [comment]
Buongiorno, la issue è stata presa in carico la stiamo analizzando.
Grazie

**Comment by OmarLorenzini** [comment]
abbiamo fatto un deploy potete riprovare?

**Comment by EugenioGuagliardi** [comment]
Salve, abbiamo riprovato ma otteniamo ancora un errore nella Cancellazione.
Di seguito l'output della transazione del Gateway:

| dataOra = 2024 - 05 - 03 15: 00: 03: 972 | server = null | ID_DC = e5436931 - f549 - 443b - b14a - 63044901e428 | ID_COOP = null | elapsed = 1309 | DIR = CLI | OUT = /govway/rest / in / FSE / gateway / v1 / documents # null # {
    "traceID": "9252c704c012744f",
    "spanID": "9252c704c012744f",
    "warning": "",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.0d30601be1^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Potete verificare cortesemente?
Grazie

**Comment by rserrano73** [comment]
Abbiamo preso in carico la segnalazione. 
Dai log si evince l'errore: "Nessun documento del tipo richiesto è registrato per il paziente indicato"
Stiamo risolvendo. Vi aggiorniamo asap.

**Comment by rserrano73** [comment]
Abbiamo aggiornato la situazione per il CF dell'Assistito KRNLXD35E55I956K. Potete procedere con riprovare il test.

**Comment by vigliottim** [comment]
Buonsera,
procediamo alla chiusura della presente issue poiché non più attuale essendo terminato il Crash Program.
Grazie.
