### ISSUE TITLE
Richiesta accreditamento applicativi WINGSR e MEDICALSUITE

### ISSUE THREAD

**Issue by AcsFSE** [ministero-salute/it-fse-support#793]
Buonasera.

Abbiamo generato una pull request per l' accreditamento al servizio di Validazione per 2 appilcativi, entrambi per i documenti di Radiologia.

I dati che identificano la procedura in validazione dell' applicativo WINGSR:

commonName auth: A1#111ACSINFORMAT
subject_application_vendor: ACSINFORMATICA
subject_application_id: WINGSR
subject_application_version: V1

I dati che identificano la procedura in validazione dell' applicativo MEDICALSUITE:

commonName auth: A1#111ACSINFORMAT
subject_application_vendor: ACSINFORMATICA
subject_application_id: MEDICALSUITE
subject_application_version: 1

Grazie.

Buona serata.

**Comment by LucaRogledi** [comment]
Buongiorno,
Abbiamo notato che la PR è formata correttamente ma si trova all'interno del [vostro repository](https://github.com/AcsFSE/it-fse-accreditamento/pulls) e non risulta aperta sul repository di [ministero-salute](https://github.com/ministero-salute/it-fse-accreditamento/pulls).
Probabilmente in fase di creazione della PR, non ha selezionato il base-repository corretto, che deve essere quello centrale, mentre l'head repository è quello creato da lei. Si veda la figura riportata di seguito con un head repository di esempio:

![image](https://github.com/ministero-salute/it-fse-support/assets/139234602/adf03c0a-32a3-446a-9c26-ed9e6fd8b40d)

Le chiediamo di selezionare il base repository e l'head repository corretti ed effettuare una nuova PR.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Potrà riaprirla nel caso in cui avesse bisogno di ulteriore supporto. Grazie.
