### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#794]
Buongiorno, ho effettuato una nuova Pull Request Sabato 4 c.m., ho inserito i file qui:
https://github.com/infoserviceonline/it-fse-accreditamento/tree/main/GATEWAY/A1%23111%23INFOSERVICEONLINE/INFOSERVICE/FLY/2.0, ma non vedo la pull request qui:
https://github.com/ministero-salute/it-fse-accreditamento/pulls
Vedo la prima, errata, ma non vedo la nuova. Ho forse sbagliato qualcosa?
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, la pull request da lei creata (https://github.com/infoserviceonline/it-fse-accreditamento/pull/2) è troppo grande come riporta il seguente warning: 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/f24ab249-f2e1-4ea9-bcb2-b6f71f94b5aa)
E' necessario ripetere l'operazione partendo da una situazione pulita e facendo commit solo dei nuovi file/dei file modificati altrimenti il merge non verrà effettuato. 
Inoltre, la pull request in esame non è visibile al link https://github.com/ministero-salute/it-fse-accreditamento/pulls poiché il merge è stato effettuato all'interno del vostro repository e non sul repository [ministero-salute](https://github.com/ministero-salute/it-fse-accreditamento/pulls): 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/37124f97-e5fc-48e4-9726-1a70542ee8fd)
Probabilmente, in fase di creazione della pull request, non ha selezionato il _base-repository_ corretto, che deve essere quello centrale, mentre l'_head-repository_ sarà quello creato da lei. 
Si veda la figura riportata di seguito con un _head-repository_ di esempio:
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/a1fc367c-d14e-4647-982a-a8a65fff971a)
La invitiamo a seguire tutte le correzioni riportate e riprovare. 
Grazie.

**Comment by infoserviceonline** [comment]
Perdonatemi ma non capisco, io ho inserito solo 20 file qui:
https://github.com/infoserviceonline/it-fse-accreditamento/tree/main/GATEWAY/A1%23111%23INFOSERVICEONLINE/INFOSERVICE/FLY/2.0/FILES
e i due canonici json e xls qui:
https://github.com/infoserviceonline/it-fse-accreditamento/tree/main/GATEWAY/A1%23111%23INFOSERVICEONLINE/INFOSERVICE/FLY/2.0
ma mi ritrovo file di altri integratori qui: https://github.com/infoserviceonline/it-fse-accreditamento/pull/2.
Non capisco cosa succede. E' ovvio, come ho già detto, che non sono pratico di questo sistema, ma ho seguito le istruzioni.
A questo punto mi chiedo cosa ci fanno tutti quei file nella mia Pull Request e sopratutto mi chiedo come devo fare a non sbagliare di nuovo. 
Tra l'altro la prima Pull era andata bene, quantomeno formalmente: https://github.com/ministero-salute/it-fse-accreditamento/pull/1297
Ed ancora mi arrivano messaggi riferiti a file di Dedalus, non miei, che davvero non capisco:
https://github.com/infoserviceonline/it-fse-accreditamento/pull/2/files/43d2474d2edefba30f7db8eb22f6cb8bd0bd18c5..d4ac714f462d0d7b051a5a54232fa7ea05bebb82
Ora ho chiuso quella Pull Request piena di file non miei e sto cercando di farne una nuova, seguendo quello che mi indicate nell'immagine (il cui link è irraggiungibile) ma non mi consente di inserire alcuna nuova Pull, eppure a me sembra il repository corretto, o non è così?
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/329a734c-65e7-4b98-b7af-e044a6119b61)
Sinceramente non capisco dove sbaglio, visto che la prima volta è andato tutto bene.
Grazie per l'aiuto e la pazienza.

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
La invitiamo ad effettuare una nuova PR dopo aver provveduto ad una Sync del Fork per ottenere una situazione pulita ed aggiornata rispetto al repository [ministero della salute](https://github.com/ministero-salute/it-fse-accreditamento). 
Può procedere come indicato nel seguente screenshot tramite il dropdown "Sync fork":

![image](https://github.com/ministero-salute/it-fse-support/assets/139234602/82d8b5b1-0b0a-4830-9ec7-f999848e7e4b)
 
Una volta che il branch è aggiornato, può procedere aggiungendo le sue modifiche, in caso non siano presenti, ed effettuando una nuova PR come indicato precedentemente.
Prima di procedere la invitiamo inoltre ad assicurarsi di avere una copia delle sue nuove modifiche offline per evitare la perdita del lavoro svolto.
Grazie

**Comment by infoserviceonline** [comment]
Ho provveduto a chiudere tutte le pool request aperte ed effettuarne una nuova:
https://github.com/ministero-salute/it-fse-accreditamento/pull/1384
Ma all'interno non vedo i file caricati. Dal momento che mi avete detto di non caricare nuovamente i file se non modificati, non l'ho fatto. Vorrei capire se anche questa volta ho commesso errori.
Grazie.
