### ISSUE TITLE
Crash Program - Sprint4 - RDE Lombardia , RDA FVG - UC6 - Errore in pubblicazione pre Sostituzione

### ISSUE THREAD

**Issue by EugenioGuagliardi** [ministero-salute/it-fse-support#798]
Salve,
abbia eseguito il test UC6 Sprint 4 che prevede la Lombardia come RDE e il FVG come RDA. 
Segnaliamo un errore nella 
chiamata
|dataOra=2024-05-06 14:28:03:311|server=null|ID_DC=8b182241-cbfa-4215-8284-14609ad28087|ID_COOP=null|elapsed=0|DIR=CLI|IN=/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.30.4.4%5E030703.RRDOCU.b0f810f6-0ba3-11ef-a9d8-0242a89a8ac

Risposta
 | dataOra = 2024 - 05 - 06 14: 28: 08: 770 | server = null | ID_DC = 8b182241 - cbfa - 4215 - 8284 - 14609ad28087 | ID_COOP = null | elapsed = 5459 | DIR = CLI | OUT = /govway/rest / in / FSE / gateway / v1 / documents / 2.16.840.1.113883.2.9.2.30.4.4 % 5E030703.RRDOCU.b0f810f6 - 0ba3 - 11ef - a9d8 - 0242a89a8ac7 # null # {
    "traceID": "f26ce0e5a4705a3b",
    "spanID": "f26ce0e5a4705a3b",
    "warning": "",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.01fb802a22^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Errore
       ```
 {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-05-06T12:28:09.395+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryDeprecatedDocumentErrorCODE CONTEXT:XDS Deprecated Document Error:\n The following registry objects were referenced by this submission but are not present, as Approved documents, in the registry: [urn:uuid:80048b4c-a3ee-4c67-825b-32915ea03ead]",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.01fb802a22^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-05-06T12:28:09.448+00:00"
        }

```

di seguito lo STATUS della transazione

```
{
    "traceID": "e400a07b1de240ea",
    "spanID": "c406af35ddd38889",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-05-06T12:28:03.179+00:00",
            "eventStatus": "SUCCESS",
            "subject": "KRNBRS58M08B236S^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.01fb802a22^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "23f1d848b235a334",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-05-06T12:28:03.191+00:00"
        },
        {
            "eventType": "REPLACE",
            "eventDate": "2024-05-06T12:28:08.725+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.fd600dc2-0ba3-11ef-a9d8-0242a89a8ac7",
            "subject": "KRNBRS58M08B236S^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "DIS",
            "organizzazione": "030",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.01fb802a22^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "f26ce0e5a4705a3b",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-05-06T12:28:08.737+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-05-06T12:28:09.395+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryDeprecatedDocumentErrorCODE CONTEXT:XDS Deprecated Document Error:\n The following registry objects were referenced by this submission but are not present, as Approved documents, in the registry: [urn:uuid:80048b4c-a3ee-4c67-825b-32915ea03ead]",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.01fb802a22^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-05-06T12:28:09.448+00:00"
        }
    ]
}
```

Potete verificare cortesemente ?
Segnaliamo la stessa tipologia di errore anche per lo UC8 relativo alla Canellazione.

Grazie per la collaborazione

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
abbiamo verificato per il documento: 2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.fd600dc2-0ba3-11ef-a9d8-0242a89a8ac7 vediamo che ci sono 7 transazioni. 
La prima transazione con timestamp **06-MAG-24 14:27:42 ha eseguito la replace del documento con successo**.

Questa è la situazione che attualmente ci risulta:
- il documento con ID 2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.b0f810f6-0ba3-11ef-a9d8-0242a89a8ac7 risulta DEPRECATO
- il documento con ID 2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.fd600dc2-0ba3-11ef-a9d8-0242a89a8ac7 risulta in stato APPROVED (DOPO REPLACE).

Abbiamo visto che poi ci sono stati altri test di replace successivi con targetObject dell'association uuid 80048b4c-a3ee-4c67-825b-32915ea03ead che è quello del documento 2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.b0f810f6-0ba3-11ef-a9d8-0242a89a8ac7 deprecato in precedenza con successo da id 2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.fd600dc2-0ba3-11ef-a9d8-0242a89a8ac7 che risulta in stato Approved (urn:uuid:f69f62d9-af1e-4d9a-b4b2-660e14a1a6ab). 

Questo genera l'errore:
> "XDS Deprecated Document Error:&#10; The following registry objects were referenced by this submission but are not present, as Approved documents, in the registry: [**urn:uuid:80048b4c-a3ee-4c67-825b-32915ea03ead**]"
> 

Spero questa verifica possa chiarire l'errore ricevuto, fateci sapere se è necessario qualche ulteriore controllo o dettaglio ulteriore in merito.
Ringraziandovi molto per la collaborazione vi auguriamo una buona giornata.

**Comment by EugenioGuagliardi** [comment]
Buongiorno,
la vostra analisi è stata molto utile, abbiamo verificato nei nostri sistemi ed effettivamente abbiamo rilevato diverse chiamate sul caso d'uso ma soprattutto che la prima chiamata è andata a buon fine, quindi il test UC6 si conclude positivamente.  Stiamo verificando il motivo per cui abbiamo inviato più chiamate. In ogni caso la RDA del FVG in si comporta correttamente per cui la segnalazione può essere chiusa.

Grazie per la collaborazione e buona giornata anche a Voi.

**Comment by vigliottim** [comment]
Grazie per il gentile feedback.
Procediamo con la chiusura del presente ticket come richiesto. 
Rimaniamo a disposizione per altre richieste di supporto.
