### ISSUE TITLE
Vs. Mancato accreditamento (checklist) del 06/05/2024

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#799]
Salve,
ho provveduto a valorizzare i campi mancanti nel file report-checklist.xlsx, che per la verità erano solo alcuni tra quelli segnalati, ma forse è una segnalazione standard massiva, ora vorrei sapere come devo procedere per aggiornare il file.
Devo eseguire una nuova Pool Request, chiudendo la precedente, ormai ho imparato(!)  o è sufficiente caricare e sovrascrivere il file?
Pull request in questione: https://github.com/ministero-salute/it-fse-accreditamento/pull/1384Grazie.
Grazie.

**Comment by infoserviceonline** [comment]
Abbiamo provveduto ad eseguire una nuova pull request, dal momento che sembra essere la procedura corretta, con conseguente aggiornamento del file report-checklist.xlsx.
Restiamo in attesa di riscontro.
Saluti.
https://github.com/ministero-salute/it-fse-accreditamento/pull/1387

**Comment by LucaRogledi** [comment]
Buongiorno,
Le segnaliamo che è possibile sovrascrivere il file da lei indicato modificando la Pull Request finché è ancora aperta.
La PR è stata presa in carico, procediamo alla chiusura della issue e riceverà aggiornamenti riguardo l'esito dell'elaborazione via email.
Restiamo a disposizione per eventuale supporto.
Grazie.
