### ISSUE TITLE
403 AuthorizationContentDeny - Unauthorized request content

### ISSUE THREAD

**Issue by EnzoMaietta** [ministero-salute/it-fse-support#8]
Buongiorno, dalla Lombardia stiamo tendando di invocare l'api del gatway per la validazione di un CDA2 utilizzando i parametri curl riportati nella documentazione al link: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#312-messaggio-di-richiesta-esempio-verifica-con-attachment
Ma riceviamo errore: _"403 AuthorizationContentDeny - Unauthorized request content"_  (govway_id: 85e57701-1e2e-11ed-931a-005056ae7395)
Nell'errore restituito non ci sono indicazioni specifiche di cosa non è corretto, quindi è un po' difficile capire cosa non va. Avete qualche suggerimneto in merito? Grazie mille, riportiamo di seguito il log completo della chiamata:

curl -vvv -i -k --key private.key --cert A1030000000000XX.pem -X 'POST' 'https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation' -H 'Authorization: Bearer eyJ4NWMiOlsiTUlJRkZ6Q0NBditnQXdJQkFnSVVmajYrUXduS1VVZ2I5clpIeHFBMW5XdkRZd2N3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TWpBNE1USXdOakUxTURsYUZ3MHlOVEE0TVRJd05qRTFNRGhhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMwd016QXdNREF3TURBd01EQllXREVhTUJnR0ExVUVBd3dSVXpFak1ETXdNREF3TURBd01EQXdXRmd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2NoZDBRalNmUGVHc2FnNE51QjNJa2tlT3U3S0ZYM1dOMW5FR1g2ZjI1WTd2MlVOdmdKQkIrZE9rYldadVU2c1RSUk1BZ1JXb1ZRMWJEVHdSM3JkTFROVGttN2ZhSko1b0tBNUVHZmlIVytqQzNKRzllNlNidVYwTVAzaVBPOVVhNkEvSHBRUGNVaHRsMkd2ZVQxcVZwQVI2aUpwaDEzRGNNUzhnaWdFWDBjb1JtNEN2VUdEMlBwK2hVY0xpY3J5SjVPVC9GdW5TeHhId1QwVEdWMTY4SU1jSEd4Mkw2M1RJNitmZHdaSVdxM3FwRWxSNTl2VGw2bGVyWnpWSWVsN1psRUszbWQyYzVsVXF1TG9NSkhTUVR6Sjlud0RpYWxkL2U2b3p6TzBINTlTNlBaTitqVEliOHdmbmp6clZvQ0pIOUdjdVI4ZkJWYzVWMjBOZ2swS1duQWdNQkFBR2pnY2d3Z2NVd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3Y3dZRFZSMGZCR3d3YWpCb29HYWdaSVppYkdSaGNEb3ZMMk5oWkhNdVptbHVZVzU2WlM1cGRDOURUajFEUVNVeU1FMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbEpUSXdWR1Z6ZEN4UFBVMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbExFTTlTVlF3SFFZRFZSME9CQllFRkJTWHJhM0xIQjdJV1F6Zlo2TmtFMkp1emRkTU1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQUh0MGQrMno1RE5vNFVGNGYrK1NmWTlQaXdmbDNqbCsxTlJwckQxcFBxSGlBR0x0a0pGb1AwZUdKWWlQTWhJT0Z1U2ZoZGw1UUxHRVUwSUZSVjcxRU8zN2RnSVhocVBIaS9PaTJCdUJWR2RockF1b2w5dGVPQ0tUTFpqSE1vMWJZTGIwMzEwKzIzUm9lNkE4TVpueC8yOE9PWHk0dGw3U3poc0x6YzhkRmhwQjdJdGc3MjE3TERkVy9jRC9YRVUzQnZYNHk5cXlNVzN6YVpPMmN0L0NXYng4MkN3cnV0eXZiUkFjN1RrczMxL3VadzBxeGdPOTM2MHFkREZzNkp0UTduTGJjM2FocVc5c2N3R01TVDFKVGZiMXBZbUpRajNhUTRnTDBwaTFaK1pDT3BlMExMRjZqMkJ3ZnVXdkI1VW0wRnNVUGVRc2UwQWVxMnZGQ2p6dlhDbG9TRWtiZWpJM01ydGFwb1g3bVFuR1ZLaFdDNDFuK2w5aVlINkpZOHZEc0I4TTRLWEgrZDZieGRnT1pJVGFjQUV6WGVjTm4xUys5TWlUSVVoLzNWckRsVklHSmJ0bkNGdHZNb3IvNnBacGZQV2YyaVNzYTUwM3ZvcWpha1BTcElFVFpYc25PbFYxa3dSSTVKZGkvL2xha1JjeTZFblNDeHZac3A1elJDY3FkeitZSy81cFZtMitXN050cUJsK285YTdBbzhmb05LMEdvNVVMdTcvb3ZPWnAxUU9ub0YzQlBzWldWRXJYOTNNU3RBRTdXY0xKbkRDejNjb3d4YW5SYU41K2NHbXNBUDZpWUc5ZzRoR2YrVHZZUW02Q29DdHM3Rm43VHVNV1l4bjJkQnRVRzJRNG1xUmhOUmtvNzlEb0pVZ3ZlMjM1YWdoOGtvUlhFaEJpbS9VPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJLUk5CUlMwM1QwMUI0NjFXIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwiaXNzIjoiYXV0aDowMzAwMDAwMDAwMDBYWCIsImV4cCI6MTY2MDgyNzk4NCwiaWF0IjoxNjYwNzQxNTg0LCJqdGkiOiIxMjM0In0.DlcMG5p0mBsYIB9i0kDCVGNXZECjK-mPus_pU0_dPFq7tuWYr0ulKL_UNM4HfmWszvzE5jahfs7r1izA4Q5XcnfD70bjAHKLyj1bYLM1K853bXvd67DvqfhXSimg15BMmG80dk6t6HMqwOFIE6NLV4g4oiBLeOUCoV0Vd6FKKRxM9yZK7O6fc0DVM1W4lkJBqnGOQZQ0bLoTVpWNuKnGomfgncyezhch2cJy32F2mxjWfWxhZ9K1Z0Yadr_QtzO7rwNv0fS9BzEJ5Sv-TPqkVLqg5ra4obxEh1BmjIVGJPLe6pms6TfQ8Xgh7TLS5Fn7bLncKY13jEo58D4Wj_P9PA' -H 'FSE-JWT-Signature: eyJ4NWMiOlsiTUlJRkZ6Q0NBditnQXdJQkFnSVVmajYrUXduS1VVZ2I5clpIeHFBMW5XdkRZd2N3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TWpBNE1USXdOakUxTURsYUZ3MHlOVEE0TVRJd05qRTFNRGhhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMwd016QXdNREF3TURBd01EQllXREVhTUJnR0ExVUVBd3dSVXpFak1ETXdNREF3TURBd01EQXdXRmd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2NoZDBRalNmUGVHc2FnNE51QjNJa2tlT3U3S0ZYM1dOMW5FR1g2ZjI1WTd2MlVOdmdKQkIrZE9rYldadVU2c1RSUk1BZ1JXb1ZRMWJEVHdSM3JkTFROVGttN2ZhSko1b0tBNUVHZmlIVytqQzNKRzllNlNidVYwTVAzaVBPOVVhNkEvSHBRUGNVaHRsMkd2ZVQxcVZwQVI2aUpwaDEzRGNNUzhnaWdFWDBjb1JtNEN2VUdEMlBwK2hVY0xpY3J5SjVPVC9GdW5TeHhId1QwVEdWMTY4SU1jSEd4Mkw2M1RJNitmZHdaSVdxM3FwRWxSNTl2VGw2bGVyWnpWSWVsN1psRUszbWQyYzVsVXF1TG9NSkhTUVR6Sjlud0RpYWxkL2U2b3p6TzBINTlTNlBaTitqVEliOHdmbmp6clZvQ0pIOUdjdVI4ZkJWYzVWMjBOZ2swS1duQWdNQkFBR2pnY2d3Z2NVd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3Y3dZRFZSMGZCR3d3YWpCb29HYWdaSVppYkdSaGNEb3ZMMk5oWkhNdVptbHVZVzU2WlM1cGRDOURUajFEUVNVeU1FMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbEpUSXdWR1Z6ZEN4UFBVMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbExFTTlTVlF3SFFZRFZSME9CQllFRkJTWHJhM0xIQjdJV1F6Zlo2TmtFMkp1emRkTU1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQUh0MGQrMno1RE5vNFVGNGYrK1NmWTlQaXdmbDNqbCsxTlJwckQxcFBxSGlBR0x0a0pGb1AwZUdKWWlQTWhJT0Z1U2ZoZGw1UUxHRVUwSUZSVjcxRU8zN2RnSVhocVBIaS9PaTJCdUJWR2RockF1b2w5dGVPQ0tUTFpqSE1vMWJZTGIwMzEwKzIzUm9lNkE4TVpueC8yOE9PWHk0dGw3U3poc0x6YzhkRmhwQjdJdGc3MjE3TERkVy9jRC9YRVUzQnZYNHk5cXlNVzN6YVpPMmN0L0NXYng4MkN3cnV0eXZiUkFjN1RrczMxL3VadzBxeGdPOTM2MHFkREZzNkp0UTduTGJjM2FocVc5c2N3R01TVDFKVGZiMXBZbUpRajNhUTRnTDBwaTFaK1pDT3BlMExMRjZqMkJ3ZnVXdkI1VW0wRnNVUGVRc2UwQWVxMnZGQ2p6dlhDbG9TRWtiZWpJM01ydGFwb1g3bVFuR1ZLaFdDNDFuK2w5aVlINkpZOHZEc0I4TTRLWEgrZDZieGRnT1pJVGFjQUV6WGVjTm4xUys5TWlUSVVoLzNWckRsVklHSmJ0bkNGdHZNb3IvNnBacGZQV2YyaVNzYTUwM3ZvcWpha1BTcElFVFpYc25PbFYxa3dSSTVKZGkvL2xha1JjeTZFblNDeHZac3A1elJDY3FkeitZSy81cFZtMitXN050cUJsK285YTdBbzhmb05LMEdvNVVMdTcvb3ZPWnAxUU9ub0YzQlBzWldWRXJYOTNNU3RBRTdXY0xKbkRDejNjb3d4YW5SYU41K2NHbXNBUDZpWUc5ZzRoR2YrVHZZUW02Q29DdHM3Rm43VHVNV1l4bjJkQnRVRzJRNG1xUmhOUmtvNzlEb0pVZ3ZlMjM1YWdoOGtvUlhFaEJpbS9VPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJLUk5CUlMwM1QwMUI0NjFXIiwic3ViamVjdF9yb2xlIjoiQUFTIiwicHVycG9zZV9vZl91c2UiOiJUUkVBVE1FTlQiLCJpc3MiOiJpbnRlZ3JpdHk6MDMwMDAwMDAwMDAwWFgiLCJsb2NhbGl0eSI6IjIwMTEyMzQ1NiIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBMb21iYXJkaWEiLCJzdWJqZWN0X29yZ2FuaXphdGlvbl9pZCI6IjAzMCIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInBhdGllbnRfY29uc2VudCI6dHJ1ZSwiYWN0aW9uX2lkIjoiQ1JFQVRFIiwicmVzb3VyY2VfaGw3X3R5cGUiOiIoJzExNTAyLTJeXjIuMTYuODQwLjEuMTEzODgzLjYuMScpIiwiYXR0YWNobWVudF9oYXNoIjpudWxsLCJleHAiOjE2NjA4Mjc5ODQsImlhdCI6MTY2MDc0MTU4NCwianRpIjoiMTIzNCIsInBlcnNvbl9pZCI6IktSTkJSUzAzVDAxQjQ2MVdeXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyJ9.iRrBLwUHXLd87FzuL4_7YuVaoqXNikY6WgtiT7cM1pIF-A0qkTFJqTm0wZV12Om3PGXIGMUeISa01-l9qeUyTNppG5_JUU8WjxQykdqAiX9__ysmKUb232_zSPvHmkWYSkGM0CyUdGHLu6BLDBq8iNo2Usc-PCkSTENlY49R0uWo70xgDCiqKHhv93kgFOtnLzwFzEUXYGyiy8jOiYFiTtHJsw2YJG7qE0f2TnczTroNBpsIqmU5PzfEJBeH381AVSpZISxMMi2jhDJTa7mbCrMpGUG_X-cb5F6bCm6jrIUxR8MGeDVOlraENFXIwZlE1JxA63Zg6jR8KKMl0zE1lw' -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -F 'requestBody={"healthDataFormat":"CDA","activity":"VERIFICA"}' -F 'file=@output.pdf;type=application/pdf'
* About to connect() to modipa-val.fse.salute.gov.it port 443 (#0)
*   Trying 217.175.50.111...
* Connected to modipa-val.fse.salute.gov.it (217.175.50.111) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate from file
* 	subject: CN="A1#030000000000XX",OID.2.5.4.97=CF:IT-030000000000XX,O=Ministero della Salute,C=IT
* 	start date: ago 12 06:14:38 2022 GMT
* 	expire date: ago 11 06:14:37 2025 GMT
* 	common name: A1#030000000000XX
* 	issuer: C=IT,O=Ministero della Salute,CN=CA Ministero della Salute Test
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=modipa-val.fse.salute.gov.it,O=Sogei S.p.A.,L=Roma,ST=Roma,C=IT
* 	start date: giu 08 07:13:29 2022 GMT
* 	expire date: giu 08 07:13:20 2023 GMT
* 	common name: modipa-val.fse.salute.gov.it
* 	issuer: CN=Actalis Organization Validated Server CA G3,O=Actalis S.p.A.,L=Ponte San Pietro,ST=Bergamo,C=IT
> POST /govway/rest/in/FSE/gateway/v1/documents/validation HTTP/1.1
> User-Agent: curl/7.29.0
> Host: modipa-val.fse.salute.gov.it
> Authorization: Bearer eyJ4NWMiOlsiTUlJRkZ6Q0NBditnQXdJQkFnSVVmajYrUXduS1VVZ2I5clpIeHFBMW5XdkRZd2N3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TWpBNE1USXdOakUxTURsYUZ3MHlOVEE0TVRJd05qRTFNRGhhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMwd016QXdNREF3TURBd01EQllXREVhTUJnR0ExVUVBd3dSVXpFak1ETXdNREF3TURBd01EQXdXRmd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2NoZDBRalNmUGVHc2FnNE51QjNJa2tlT3U3S0ZYM1dOMW5FR1g2ZjI1WTd2MlVOdmdKQkIrZE9rYldadVU2c1RSUk1BZ1JXb1ZRMWJEVHdSM3JkTFROVGttN2ZhSko1b0tBNUVHZmlIVytqQzNKRzllNlNidVYwTVAzaVBPOVVhNkEvSHBRUGNVaHRsMkd2ZVQxcVZwQVI2aUpwaDEzRGNNUzhnaWdFWDBjb1JtNEN2VUdEMlBwK2hVY0xpY3J5SjVPVC9GdW5TeHhId1QwVEdWMTY4SU1jSEd4Mkw2M1RJNitmZHdaSVdxM3FwRWxSNTl2VGw2bGVyWnpWSWVsN1psRUszbWQyYzVsVXF1TG9NSkhTUVR6Sjlud0RpYWxkL2U2b3p6TzBINTlTNlBaTitqVEliOHdmbmp6clZvQ0pIOUdjdVI4ZkJWYzVWMjBOZ2swS1duQWdNQkFBR2pnY2d3Z2NVd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3Y3dZRFZSMGZCR3d3YWpCb29HYWdaSVppYkdSaGNEb3ZMMk5oWkhNdVptbHVZVzU2WlM1cGRDOURUajFEUVNVeU1FMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbEpUSXdWR1Z6ZEN4UFBVMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbExFTTlTVlF3SFFZRFZSME9CQllFRkJTWHJhM0xIQjdJV1F6Zlo2TmtFMkp1emRkTU1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQUh0MGQrMno1RE5vNFVGNGYrK1NmWTlQaXdmbDNqbCsxTlJwckQxcFBxSGlBR0x0a0pGb1AwZUdKWWlQTWhJT0Z1U2ZoZGw1UUxHRVUwSUZSVjcxRU8zN2RnSVhocVBIaS9PaTJCdUJWR2RockF1b2w5dGVPQ0tUTFpqSE1vMWJZTGIwMzEwKzIzUm9lNkE4TVpueC8yOE9PWHk0dGw3U3poc0x6YzhkRmhwQjdJdGc3MjE3TERkVy9jRC9YRVUzQnZYNHk5cXlNVzN6YVpPMmN0L0NXYng4MkN3cnV0eXZiUkFjN1RrczMxL3VadzBxeGdPOTM2MHFkREZzNkp0UTduTGJjM2FocVc5c2N3R01TVDFKVGZiMXBZbUpRajNhUTRnTDBwaTFaK1pDT3BlMExMRjZqMkJ3ZnVXdkI1VW0wRnNVUGVRc2UwQWVxMnZGQ2p6dlhDbG9TRWtiZWpJM01ydGFwb1g3bVFuR1ZLaFdDNDFuK2w5aVlINkpZOHZEc0I4TTRLWEgrZDZieGRnT1pJVGFjQUV6WGVjTm4xUys5TWlUSVVoLzNWckRsVklHSmJ0bkNGdHZNb3IvNnBacGZQV2YyaVNzYTUwM3ZvcWpha1BTcElFVFpYc25PbFYxa3dSSTVKZGkvL2xha1JjeTZFblNDeHZac3A1elJDY3FkeitZSy81cFZtMitXN050cUJsK285YTdBbzhmb05LMEdvNVVMdTcvb3ZPWnAxUU9ub0YzQlBzWldWRXJYOTNNU3RBRTdXY0xKbkRDejNjb3d4YW5SYU41K2NHbXNBUDZpWUc5ZzRoR2YrVHZZUW02Q29DdHM3Rm43VHVNV1l4bjJkQnRVRzJRNG1xUmhOUmtvNzlEb0pVZ3ZlMjM1YWdoOGtvUlhFaEJpbS9VPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJLUk5CUlMwM1QwMUI0NjFXIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwiaXNzIjoiYXV0aDowMzAwMDAwMDAwMDBYWCIsImV4cCI6MTY2MDgyNzk4NCwiaWF0IjoxNjYwNzQxNTg0LCJqdGkiOiIxMjM0In0.DlcMG5p0mBsYIB9i0kDCVGNXZECjK-mPus_pU0_dPFq7tuWYr0ulKL_UNM4HfmWszvzE5jahfs7r1izA4Q5XcnfD70bjAHKLyj1bYLM1K853bXvd67DvqfhXSimg15BMmG80dk6t6HMqwOFIE6NLV4g4oiBLeOUCoV0Vd6FKKRxM9yZK7O6fc0DVM1W4lkJBqnGOQZQ0bLoTVpWNuKnGomfgncyezhch2cJy32F2mxjWfWxhZ9K1Z0Yadr_QtzO7rwNv0fS9BzEJ5Sv-TPqkVLqg5ra4obxEh1BmjIVGJPLe6pms6TfQ8Xgh7TLS5Fn7bLncKY13jEo58D4Wj_P9PA
> FSE-JWT-Signature: eyJ4NWMiOlsiTUlJRkZ6Q0NBditnQXdJQkFnSVVmajYrUXduS1VVZ2I5clpIeHFBMW5XdkRZd2N3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TWpBNE1USXdOakUxTURsYUZ3MHlOVEE0TVRJd05qRTFNRGhhTUdreEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SMHdHd1lEVlFSaERCUkRSanBKVkMwd016QXdNREF3TURBd01EQllXREVhTUJnR0ExVUVBd3dSVXpFak1ETXdNREF3TURBd01EQXdXRmd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2NoZDBRalNmUGVHc2FnNE51QjNJa2tlT3U3S0ZYM1dOMW5FR1g2ZjI1WTd2MlVOdmdKQkIrZE9rYldadVU2c1RSUk1BZ1JXb1ZRMWJEVHdSM3JkTFROVGttN2ZhSko1b0tBNUVHZmlIVytqQzNKRzllNlNidVYwTVAzaVBPOVVhNkEvSHBRUGNVaHRsMkd2ZVQxcVZwQVI2aUpwaDEzRGNNUzhnaWdFWDBjb1JtNEN2VUdEMlBwK2hVY0xpY3J5SjVPVC9GdW5TeHhId1QwVEdWMTY4SU1jSEd4Mkw2M1RJNitmZHdaSVdxM3FwRWxSNTl2VGw2bGVyWnpWSWVsN1psRUszbWQyYzVsVXF1TG9NSkhTUVR6Sjlud0RpYWxkL2U2b3p6TzBINTlTNlBaTitqVEliOHdmbmp6clZvQ0pIOUdjdVI4ZkJWYzVWMjBOZ2swS1duQWdNQkFBR2pnY2d3Z2NVd0h3WURWUjBqQkJnd0ZvQVVGam1wR2dXSnR3OHRzalh0d2dtYXhRT0RJajh3Y3dZRFZSMGZCR3d3YWpCb29HYWdaSVppYkdSaGNEb3ZMMk5oWkhNdVptbHVZVzU2WlM1cGRDOURUajFEUVNVeU1FMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbEpUSXdWR1Z6ZEN4UFBVMXBibWx6ZEdWeWJ5VXlNR1JsYkd4aEpUSXdVMkZzZFhSbExFTTlTVlF3SFFZRFZSME9CQllFRkJTWHJhM0xIQjdJV1F6Zlo2TmtFMkp1emRkTU1BNEdBMVVkRHdFQi93UUVBd0lHUURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQUh0MGQrMno1RE5vNFVGNGYrK1NmWTlQaXdmbDNqbCsxTlJwckQxcFBxSGlBR0x0a0pGb1AwZUdKWWlQTWhJT0Z1U2ZoZGw1UUxHRVUwSUZSVjcxRU8zN2RnSVhocVBIaS9PaTJCdUJWR2RockF1b2w5dGVPQ0tUTFpqSE1vMWJZTGIwMzEwKzIzUm9lNkE4TVpueC8yOE9PWHk0dGw3U3poc0x6YzhkRmhwQjdJdGc3MjE3TERkVy9jRC9YRVUzQnZYNHk5cXlNVzN6YVpPMmN0L0NXYng4MkN3cnV0eXZiUkFjN1RrczMxL3VadzBxeGdPOTM2MHFkREZzNkp0UTduTGJjM2FocVc5c2N3R01TVDFKVGZiMXBZbUpRajNhUTRnTDBwaTFaK1pDT3BlMExMRjZqMkJ3ZnVXdkI1VW0wRnNVUGVRc2UwQWVxMnZGQ2p6dlhDbG9TRWtiZWpJM01ydGFwb1g3bVFuR1ZLaFdDNDFuK2w5aVlINkpZOHZEc0I4TTRLWEgrZDZieGRnT1pJVGFjQUV6WGVjTm4xUys5TWlUSVVoLzNWckRsVklHSmJ0bkNGdHZNb3IvNnBacGZQV2YyaVNzYTUwM3ZvcWpha1BTcElFVFpYc25PbFYxa3dSSTVKZGkvL2xha1JjeTZFblNDeHZac3A1elJDY3FkeitZSy81cFZtMitXN050cUJsK285YTdBbzhmb05LMEdvNVVMdTcvb3ZPWnAxUU9ub0YzQlBzWldWRXJYOTNNU3RBRTdXY0xKbkRDejNjb3d4YW5SYU41K2NHbXNBUDZpWUc5ZzRoR2YrVHZZUW02Q29DdHM3Rm43VHVNV1l4bjJkQnRVRzJRNG1xUmhOUmtvNzlEb0pVZ3ZlMjM1YWdoOGtvUlhFaEJpbS9VPSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJLUk5CUlMwM1QwMUI0NjFXIiwic3ViamVjdF9yb2xlIjoiQUFTIiwicHVycG9zZV9vZl91c2UiOiJUUkVBVE1FTlQiLCJpc3MiOiJpbnRlZ3JpdHk6MDMwMDAwMDAwMDAwWFgiLCJsb2NhbGl0eSI6IjIwMTEyMzQ1NiIsInN1YmplY3Rfb3JnYW5pemF0aW9uIjoiUmVnaW9uZSBMb21iYXJkaWEiLCJzdWJqZWN0X29yZ2FuaXphdGlvbl9pZCI6IjAzMCIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInBhdGllbnRfY29uc2VudCI6dHJ1ZSwiYWN0aW9uX2lkIjoiQ1JFQVRFIiwicmVzb3VyY2VfaGw3X3R5cGUiOiIoJzExNTAyLTJeXjIuMTYuODQwLjEuMTEzODgzLjYuMScpIiwiYXR0YWNobWVudF9oYXNoIjpudWxsLCJleHAiOjE2NjA4Mjc5ODQsImlhdCI6MTY2MDc0MTU4NCwianRpIjoiMTIzNCIsInBlcnNvbl9pZCI6IktSTkJSUzAzVDAxQjQ2MVdeXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyJ9.iRrBLwUHXLd87FzuL4_7YuVaoqXNikY6WgtiT7cM1pIF-A0qkTFJqTm0wZV12Om3PGXIGMUeISa01-l9qeUyTNppG5_JUU8WjxQykdqAiX9__ysmKUb232_zSPvHmkWYSkGM0CyUdGHLu6BLDBq8iNo2Usc-PCkSTENlY49R0uWo70xgDCiqKHhv93kgFOtnLzwFzEUXYGyiy8jOiYFiTtHJsw2YJG7qE0f2TnczTroNBpsIqmU5PzfEJBeH381AVSpZISxMMi2jhDJTa7mbCrMpGUG_X-cb5F6bCm6jrIUxR8MGeDVOlraENFXIwZlE1JxA63Zg6jR8KKMl0zE1lw
> accept: application/json
> Content-Length: 52036
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=----------------------------2be11273034f
> 
< HTTP/1.1 100 Continue
HTTP/1.1 100 Continue
< X-Note: Gateway Ack
X-Note: Gateway Ack

< HTTP/1.1 403 Forbidden
HTTP/1.1 403 Forbidden
< X-Backside-Transport: FAIL FAIL
X-Backside-Transport: FAIL FAIL
< Connection: Keep-Alive
Connection: Keep-Alive
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< Server: GovWay-SOGEI
Server: GovWay-SOGEI
< GovWay-Transaction-ErrorType: AuthorizationContentDeny
GovWay-Transaction-ErrorType: AuthorizationContentDeny
< GovWay-Transaction-ID: 85e57701-1e2e-11ed-931a-005056ae7395
GovWay-Transaction-ID: 85e57701-1e2e-11ed-931a-005056ae7395
< Content-Type: application/problem+json
Content-Type: application/problem+json
< Date: Wed, 17 Aug 2022 13:14:28 GMT
Date: Wed, 17 Aug 2022 13:14:28 GMT
< X-Global-Transaction-ID: 3f7e3e2d62fce9b31ce2391d
X-Global-Transaction-ID: 3f7e3e2d62fce9b31ce2391d

* HTTP error before end of send, stop sending
< 
* Closing connection 0
{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"85e57701-1e2e-11ed-931a-005056ae7395"}

**Comment by zukka77** [comment]
Buongiorno guardando il JWT di Autenticazione noto che manca il claim "kid" negli header e il valore dell claim "iss" dovrebbe essere **"auth:S1#030000000000XX"** (esattamente come il CN nel certificato) non "auth:030000000000XX"
Intanto correggerei questa cosa.

**Comment by EnzoMaietta** [comment]
Grazie, risolto come da suggerimento.
