### ISSUE TITLE
limite upload post max size

### ISSUE THREAD

**Issue by SimoneLepida** [ministero-salute/it-fse-support#800]
Buongiorno,
nel tentativo di validare un Patient Summary piuttosto corposo, ho ricevuto questo errore:
it.finanze.sanita.fse2.ms.gtw.dispatcher.exceptions.BusinessException: it.finanze.sanita.fse2.ms.gtw.dispatcher.exceptions.BusinessException: org.springframework.kafka.KafkaException: Send failed; nested exception is org.apache.kafka.common.errors.RecordTooLargeException: **The message is 2072138 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration**.
Considerando che i Patient Summary possono essere effettivamente corposi in caso di pazienti con tanti documenti, visite, stati, ecc, è possibile aumentare la dimensione della post di upload?
Grazie

**Comment by vigliottim** [comment]
Buongiorno, potrebbe cortesemente allegare la response completa? Grazie.

**Comment by SimoneLepida** [comment]
Certamente.
Eccola:
{
    "detail": "it.finanze.sanita.fse2.ms.gtw.dispatcher.exceptions.BusinessException: it.finanze.sanita.fse2.ms.gtw.dispatcher.exceptions.BusinessException: org.springframework.kafka.KafkaException: Send failed; nested exception is org.apache.kafka.common.errors.RecordTooLargeException: The message is 2072138 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration.",
    "instance": "",
    "spanID": "eda43d10ceede814",
    "status": 500,
    "title": "Errore generico.",
    "traceID": "eda43d10ceede814",
    "type": "/msg/generic-error"
}

**Comment by SimoneLepida** [comment]
Confermo che ora il documento viene accettato.
Grazie.
