### ISSUE TITLE
Crash Program - Sprint 4 - RDE FVG, RDA Lombardia - UC8-UC12 Errore: 500 - Ini Error

### ISSUE THREAD

**Issue by ChiaraCeccottiFVG** [ministero-salute/it-fse-support#801]
Buongiorno,
Stiamo eseguendo i test UC8_EliminazioneDocumento e UC12_ValidazionePubblicazioneSostituzioneContestuale per lo sprint4 RDE FVG e RDA regione Lombardia. CF: PRVNLM02A41L483Y

Otteniamo un errore:

```
{
    "traceID": "aff18ac067946d77",
    "spanID": "aff18ac067946d77",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "status": 500,
    "detail": "{\"traceID\":\"0000000000000000aff18ac067946d77\",\"spanID\":\"c03b4e4f2da12679\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\": \",\"instance\":\"error/generic\"}",
    "instance": "/msg/service-error/ini",
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}
```

```
"httpStatusCode": 500,
  "responseBody": "{\"traceID\":\"aff18ac067946d77\",\"spanID\":\"aff18ac067946d77\",\"type\":\"/msg/ini-error\",\"title\":\"Ini error.\",\"detail\":\"{\\\"traceID\\\":\\\"0000000000000000aff18ac067946d77\\\",\\\"spanID\\\":\\\"c03b4e4f2da12679\\\",\\\"type\\\":\\\"/errors\\\",\\\"title\\\":\\\"Generic\\\",\\\"detail\\\":\\\": \\\",\\\"instance\\\":\\\"error/generic\\\"}\",\"status\":500,\"instance\":\"/msg/service-error/ini\"}",
  "responseHeaders": {
    "Transfer-Encoding": "[chunked]",
    "GovWay-Transaction-ID": "[07ec87e1-0c60-11ef-9223-005056ae7395]",
    "Server": "[GovWay-SOGEI]",
    "X-Content-Type-Options": "[nosniff]",
    "X-Backside-Transport": "[FAIL FAIL]",
    "Connection": "[Keep-Alive]",
    "Pragma": "[no-cache]",
    "X-Global-Transaction-ID": "[3f7e3e2d663a0c571cefa70d]",
    "Date": "[Tue, 07 May 2024 11:11:20 GMT]",
    "Cache-Control": "[no-cache, no-store, must-revalidate]",
    "GovWay-Message-ID": "[f8c66184-4532-4312-a381-df3565ede7a4]",
    "content-disposition": "[inline;filename=f.txt]",
    "Vary": "[*]",
    "Expires": "[0]",
    "server-timing": "[intid;desc=179408d79397ca4f]",
    "Content-Type": "[application/problem+json]"
  },
  "uuid": "9e040260c908437dabe7901b1b17d11d",
  "dataInserimento": {
    "$date": "2024-05-07T11:11:20.236Z"
  }
```
Riuscireste ad eseguire una verifica lato INI/Gateway per aiutarci a capire qual è il problema?

Ringraziando molto per la collaborazione auguriamo un buon pomeriggio.
Regione FVG.

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
sperando sia utile, volevamo solamente condividere un aggiornamento riguardo questa issue.

Oggi abbiamo avuto modo di riprovare gli Use Case UC6_SostituzioneDocumento, UC8_EliminazioneDocumento e UC12_ValidazionePubblicazioneSostituzioneContestuale per una tipologia di documento diversa. 
Abbiamo utilizzato LDO anzichè PPS (PatientSummary). 

Con LDO siamo riusciti a procede con successo di seguito gli id dei documenti:
- UC6_SostituzioneDocumento: 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715242602423_NEW
- UC8_EliminazioneDocumento: 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715241621557 
- UC12_ValidazionePubblicazioneSostituzioneContestuale: 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715243228611

mentre con il PPS otteniamo ancora errore 500 Ini Error per tutte tre le casistiche.

_(per UC4_Aggiornamento_Metadati apriamo una nuova issue dedicata con i dettagli relativi per non creare confusione perchè l'errore è su entrambe le tipologie di documenti)._

Ringraziandovi molto per la collaborazione rimaniamo in attesa di un riscontro per aiutarci a capire quale potrebbe essere il problema relativo al PatientSummary.

Vi auguriamo una buona giornata.

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
per indagare il problema mi occorrono i riferimenti delle transazioni che vanno in errore.
Potete fornirmi i relativi workflowInstanceId ?

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
si mi scuso per non averlo fornito in precedenza.
Precisando che l'errore attualmente è presente per:

- i PatientSummary (per tutti gli sprint con PSS otteniamo errore ma con LDO la transazione va a buon fine) 
- per lo sprint5 - RDE FVG, RDA Campania per lo scenario UC8_Eliminazione sia per PatientSummary che per LDO

invio i dettagli dell'ultima transazione che ci ha restituito 500 INI Error:

 "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.7475b2434dbba98b3413e004b8bdae539220189ce4392786e433e7f3a3249b84.1d049bd0e3^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
  "traceId": "2b9fb806daaa3e36"

```
{
    "traceID": "8363fdaebf6b69a9",
    "spanID": "1e774ee1cf379684",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-05-15T07:02:11.883+00:00",
            "eventStatus": "SUCCESS",
            "subject": "BLUPLA57D20A794H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "060",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.7475b2434dbba98b3413e004b8bdae539220189ce4392786e433e7f3a3249b84.1d049bd0e3^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "2b9fb806daaa3e36",
            "issuer": "integrity:S1#060#FRIULIVENEZIAGIULIATEST",
            "expiringDate": "2025-05-15T07:02:11.898+00:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-05-15T07:02:19.778+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715756538323",
            "subject": "BLUPLA57D20A794H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "DIS",
            "organizzazione": "060",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.7475b2434dbba98b3413e004b8bdae539220189ce4392786e433e7f3a3249b84.1d049bd0e3^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "08f879ecfc78b42a",
            "issuer": "integrity:S1#060#FRIULIVENEZIAGIULIATEST",
            "expiringDate": "2025-05-15T07:02:19.788+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-05-15T07:02:20.239+00:00",
            "eventStatus": "SUCCESS",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.7475b2434dbba98b3413e004b8bdae539220189ce4392786e433e7f3a3249b84.1d049bd0e3^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-05-15T07:02:20.249+00:00"
        },
        {
            "eventType": "SEND_TO_EDS",
            "eventDate": "2024-05-15T07:02:20.335+00:00",
            "eventStatus": "SUCCESS",
            "message": "{\"esito\":true}",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.7475b2434dbba98b3413e004b8bdae539220189ce4392786e433e7f3a3249b84.1d049bd0e3^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-05-15T07:02:20.346+00:00"
        },
        {
            "eventType": "MIDDELWARE FVG - VALIDAZIONE",
            "eventDate": "2024-05-15T09:02:11.977+0200",
            "eventStatus": "SUCCESS",
            "subject": "BLUPLA57D20A794H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "subjectRole": "AAS",
            "organizzazione": "060",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.7475b2434dbba98b3413e004b8bdae539220189ce4392786e433e7f3a3249b84.1d049bd0e3^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "2b9fb806daaa3e36"
        },
        {
            "eventType": "MIDDELWARE FVG - PUBBLICAZIONE_GATEWAY",
            "eventDate": "2024-05-15T09:02:19.859+0200",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715756538323",
            "subject": "BLUPLA57D20A794H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "subjectRole": "AAS",
            "organizzazione": "060",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.7475b2434dbba98b3413e004b8bdae539220189ce4392786e433e7f3a3249b84.1d049bd0e3^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "08f879ecfc78b42a"
        }
    ]
}
```

**Comment by g-maugeri-sogei** [comment]
Salve, per le chiamate di cancellazione verso la Campania potrebbero esserci problemi di latenza che mandano in read time out il client (quindi il vostro peer) chiamate il GTW. Potete verificare lato vostro se questo e' il caso? Sui nostri log vedo solo tempi di risposta alti.

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
ringrazio per il riscontro.
Verifichiamo e facciamo sapere.
Buona giornata.

**Comment by g-maugeri-sogei** [comment]
Salve,
confermo che almeno per la Campania ci sono problemi di latenza. Il read timeout dovrebbe essere sul vostro client. In attesa che risolviamo, per completare i test funzionali vi suggerisco di aumentare il valore del timeout. Vi chiedo di confermarmi che trovate il timeout sul vostro client sulla chiamata con 

WIID = 2.16.840.1.113883.2.9.2.60.4.4.7475b2434dbba98b3413e004b8bdae539220189ce4392786e433e7f3a3249b84.1d049bd0e3^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

per escludere che sia generato da servizi intermedi interni alla nostra piattaforma.

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
abbiamo verificato i log ma non ci sembra un problema di timeout perchè otteniamo un errore del tipo fault.ServerSOAPFaultException.

Di seguito i dettagli del caso utilizzato per test.
Se possono essere utili ulteriori prove o verifiche fateci sapere.
Vi ringraziamo molto per la collaborazione e vi auguriamo una buona giornata.

```
{
    "traceID": "af0d2137752884fe",
    "spanID": "af0d2137752884fe",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "detail": "{\"traceID\":\"0000000000000000af0d2137752884fe\",\"spanID\":\"f8a51bd3ea8d74b8\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: javax.transaction.TransactionRolledbackException:  ; nested exception is: \\n\\tjavax.transaction.SystemException Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}",
    "status": 500,
    "instance": "/msg/service-error/ini"
}
```
```
responseHeaders = {
    Transfer - Encoding = [chunked],
    GovWay - Transaction - ID = [2979607d - 1287 - 11ef - 93a7 - 005056ae54fa],
    Server = [GovWay - SOGEI],
    X - Content - Type - Options = [nosniff],
    X - Backside - Transport = [FAIL FAIL],
    Connection = [Keep - Alive],
    Pragma = [no - cache],
    X - Global - Transaction - ID = [3f7e3e2d66445e0f24cec6fd],
    Date = [Wed, 15 May 2024 07: 02: 48 GMT],
    Cache - Control = [no - cache, no - store, must - revalidate],
    GovWay - Message - ID = [f1c2cd3f - 0bf2 - 4b44 - 9460 - 3f8e47f97f93],
    content - disposition = [inline;
        filename = f.txt],
    Vary = [ * ],
    Expires = [0],
    server - timing = [intid;
        desc = 8f1add43a6fcc9f9],
    Content - Type = [application / problem + json]
}
```

**Comment by g-maugeri-sogei** [comment]
Salve, abbiamo risolto il problema sulla delete relativo all'errore INI:
{
    "traceID": "af0d2137752884fe",
    "spanID": "af0d2137752884fe",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "detail": "{\"traceID\":\"0000000000000000af0d2137752884fe\",\"spanID\":\"f8a51bd3ea8d74b8\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: javax.transaction.TransactionRolledbackException:  ; nested exception is: \\n\\tjavax.transaction.SystemException Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}",
    "status": 500,
    "instance": "/msg/service-error/ini"
}
Potete riprovare e darci riscontro? Potrebbe esserci ancora un secondo errore legato alla tipologia del documento come avete indicato sopra che eventualmente dovremmo indagare.

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
confermiamo che siamo riusciti a cancellare con successo un documento di tipo LDO verso la Campania (ID: 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1716472302002).
Ringraziamo molto per il riscontro e auguriamo un buon pomeriggio.
