### ISSUE TITLE
Internal Error 1011: Richiesta supporto per documenti inviati da Regione Toscana a INI

### ISSUE THREAD

**Issue by rserrano73** [ministero-salute/it-fse-support#802]
Salve.
In ambiente di produzione, abbiamo rilevato diverse occorrenze di "Internal Error 1011" relative a documenti validati dal CART e sottomessi a INI.
Prendendo come esempio il documento firmato registrato con identificativo **2.16.840.1.113883.2.9.2.90.4.4^R3V201202400000099830**, inviato da Regione Toscana a INI in data 27 Aprile alle ore 15:18:57 (id transazione: ID-RT-SANITA-TC12-P8-rt-tix-it-54020-1713354788245-2-18235815), abbiamo riscontrato:

1. il codice di errore è cambiato da "Internal Error 1011" a "Wrong value of DocumentEntry.healthcareFacilityCode#R50" in data 3 Maggio 2024 alle ore 01:21:03
2. il codice di errore è cambiato da "Wrong value of DocumentEntry.healthcareFacilityCode#R50" a "The requestor is RDA for the patient#R220" in data 3 Maggio 2024 alle ore 14:50:07
3. il documento in esame è di tipo "Referto Radiologico", inviato da "RADIOLOGIA OSPEDALE DEL MUGELLO - FIRENZE" per un paziente della "Regione Toscana"

Ci serve comprendere come mai il documento subisce azioni per cui il "RegistryError codeContext" viene modificato, di fatto annullando l'errore bloccante "Internal Error 1011". 
Ci confermate che "R220" è un Warning per il salvataggio su INI? Ritrovate sul repository di INI questo messaggio inviato da Regione Toscana?

Abbiamo urgenza di un riscontro, data l'incidenza di queste occorrenze di errori "Internal Error 1011" in ambiente di produzione.

Saluti,
DXC

**Comment by vigliottim** [comment]
Buon pomeriggio, la invitiamo a inoltrare la sua richiesta di supporto alla seguente mail: gestionets@sogei.it.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
