### ISSUE TITLE
Creazione di due documenti con stesso idDoc

### ISSUE THREAD

**Issue by mariogoodbread** [ministero-salute/it-fse-support#804]
Salve,
ho effettuato due richieste di creazione dello stesso PDF e stesso idDoc e sono state elaborate entrambe con successo nonostante mi sarei atteso un errore nella seconda richiesta.

Di seguito i dettagli delle richieste:

**RICHIESTA 1**
_TS_: 2024-05-07T14:05:20.354Z
_requestBody_: {
        "mode": "ATTACHMENT",
        "healthDataFormat": "CDA",
        "attiCliniciRegoleAccesso": [],
        "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.afd7d2c68eeb3f477b8c4a48021bce55936b138a03252cb2926023d85398be76.1ae1eee1d9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
        "tipologiaStruttura": "Ospedale",
        "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^NISATEK-LDO-DUPLICATE",
        "identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.120201",
        "tipoDocumentoLivAlto": "LDO",
        "assettoOrganizzativo": "AD_PSC008",
        "tipoAttivitaClinica": "DIS",
        "identificativoSottomissione": "2.16.840.1.113883.2.9.2.120.4.3.4d8b74a0-7338-4650-9608-8d4ee6b67f64"
      }
_response_: {
      "traceID": "15e1dae95fc1f375",
      "spanID": "15e1dae95fc1f375",
      "warning": "",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.afd7d2c68eeb3f477b8c4a48021bce55936b138a03252cb2926023d85398be76.1ae1eee1d9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
    }

**RICHIESTA 2**
_TS_: 2024-05-07T14:05:27.293Z
_requestBody_: {
        "mode": "ATTACHMENT",
        "healthDataFormat": "CDA",
        "attiCliniciRegoleAccesso": [],
        "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.afd7d2c68eeb3f477b8c4a48021bce55936b138a03252cb2926023d85398be76.0dcc266b77^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
        "tipologiaStruttura": "Ospedale",
        "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^NISATEK-LDO-DUPLICATE",
        "identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.120201",
        "tipoDocumentoLivAlto": "LDO",
        "assettoOrganizzativo": "AD_PSC008",
        "tipoAttivitaClinica": "DIS",
        "identificativoSottomissione": "2.16.840.1.113883.2.9.2.120.4.3.067b2330-ceaf-4df6-822d-e70cedbdb7a0"
      }
_response_: {
      "traceID": "73a9e954e254af99",
      "spanID": "73a9e954e254af99",
      "warning": "",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.afd7d2c68eeb3f477b8c4a48021bce55936b138a03252cb2926023d85398be76.0dcc266b77^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
    }

In allegato il pdf utilizzato per entrambe le richieste.

[T4_CREATION.pdf](https://github.com/ministero-salute/it-fse-support/files/15236807/T4_CREATION.pdf)

**Comment by vigliottim** [comment]
Buonasera, dalle analisi effettuate è emerso che la seconda pubblicazione del documento non viene completata poiché risulta già esistente. 
Infatti, invocando il servizio status e inserendo il relativo workflow istance id nell'url (/v/status/{workflowInstanceId}), può notare la presenza del seguente errore bloccante: 

![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/65811557-5c12-4b95-ad50-534bf43f96af)

Pertanto, non è possibile effettuare due richieste di creazione dello stesso PDF con stesso identificativoDoc.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by mariogoodbread** [comment]
Chiedo scusa, ma non dovrei ricevere un errore dal servizio di pubblicazione?

Oltretutto sto avendo problemi con la get status.
L'url corretto è: https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/status/{workflowInstanceId}

**Comment by vigliottim** [comment]
L'esito ricevuto dalla pubblicazione si riferisce alla sola parte sincrona, ma le operazioni proseguono in maniera asincrona. Per verificare l'effettiva pubblicazione del documento deve essere utilizzato pertanto il servizio di _status_.
Per effettuare correttamente la chiamata di status è necessario applicare l'url encode alla parte finale dell'url contenente il _workflowInstanceId_.
Di seguito un esempio di url per la chiamata del servizio status sulla precedente "Richiesta" tramite workflowInstanceId:
[https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/status/2.16.840.1.113883.2.9.2.120.4.4.afd7d2c68eeb3f477b8c4a48021bce55936b138a03252cb2926023d85398be76.0dcc266b77^^^^urn:ihe:iti:xdw:2013:workflowInstanceId](https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/status/2.16.840.1.113883.2.9.2.120.4.4.afd7d2c68eeb3f477b8c4a48021bce55936b138a03252cb2926023d85398be76.0dcc266b77%5e%5e%5e%5eurn:ihe:iti:xdw:2013:workflowInstanceId)
Rimaniamo a disposizione nel caso in cui avesse ulteriori dubbi.

**Comment by mariogoodbread** [comment]
La risposta è esaustiva grazie 1000!
Mi ha tratto in inganno il comportamento del middleware della regione lazio che in caso di creazione di un documento già esistente il servizio di pubblicazione ritorna un ostatus 500 con il seguente payload:
{
        "govway_id": "20240507190206",
        "detail": "javax.xml.ws.soap.SOAPFaultException: [100] Documento 030702.LCNLDE90L47H501Q.20220509102426.Q123E4510 gia' presente nel registry",
        "title": "Internal error",
        "type": "midlleware-500",
        "status": 500
      }
