### ISSUE TITLE
CRASH PROGRAM Sprint 4 - Regione Toscana RDE

### ISSUE THREAD

**Issue by cdezorzi** [ministero-salute/it-fse-support#805]
Buonasera , stiamo eseguendo il test UC2_Creazione per lo sprint4
il servizio di pubblicazione risponde con il seguente messaggio
{
    "traceID": "fd31dc2c21d46018",
    "spanID": "fd31dc2c21d46018",
    "warning": "",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.7c7c289688^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

richiamando il seervizio di status per il workflowInstanceId ottenuto dalla pubblicazione abbiamo un errore nel "SEND_TO_INI" di seguito il messaggio completo

{
    "traceID": "9d3565563f17fed6",
    "spanID": "08b2c661fb59ee23",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-05-07T16:22:57.126+00:00",
            "eventStatus": "SUCCESS",
            "subject": "BLRNDR68L13G920R^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "090",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.7c7c289688^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "b4cdf20b8e4de75b",
            "issuer": "integrity:S1#090#090REGIONETOSCANA-TEST",
            "expiringDate": "2025-05-07T16:22:57.137+00:00"
        },
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-05-07T16:23:09.466+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.90.4.4^9999.VPS.910.44001",
            "subject": "BLRNDR68L13G920R^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "DIS",
            "organizzazione": "090",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.7c7c289688^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "fd31dc2c21d46018",
            "issuer": "integrity:S1#090#090REGIONETOSCANA-TEST",
            "expiringDate": "2025-05-07T16:23:09.479+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-05-07T16:23:11.610+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R18CODE CONTEXT:Wrong value of SubmissionSet.uniqueId",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.7c7c289688^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-05-07T16:23:11.751+00:00"
        }
    ]
}

Errore segnalato R18: Missing DocumentEntry.repositoryUniqueId, 
si fa presente che lo stesso formato del  messaggi di pubblicazione è stato utlizzato con esito positivo nei precedenti sprint.

Attendiamo Vs riscontro.
Grazie

**Comment by daniele-gubellini** [comment]
Buongiorno,
abbiamo scartato noi (Emilia-Romagna) il messaggio a causa del formato del campo SubmissionSet.uniqueId.

Secondo le specifiche Affinity dovrebbe essere:
_2.16.840.1.113883.2.9.2.[REGIONE oppure INI].4.3.X, dove X rappresenta una specifica istanza di XDSSubmissionSet._ 

Ricevuto: 2.16.840.1.113883.2.9.2.44001

Possibile valore corretto per Toscana: 2.16.840.1.113883.2.9.2.90.4.3.44001 

Noi abbiamo restituito "**R18** - Wrong value of SubmissionSet.uniqueId" mentre l'errore dovrebbe essere  "**R115** - Wrong value of SubmissionSet.uniqueId."  , entro breve l'ambiente di test verrà corretto per restituire il codice di errore corretto.

**Chiederei comunque a Sogei di introdurre il controllo sul formato prima della presa in carico del messaggio**, sia per questo campo che per gli altri campi che hanno un formato 'particolare' definito in Affinity 2.5

Grazie

**Comment by cdezorzi** [comment]
Buon pomeriggio,
abbiamo rieseguito il test UC2_Creazione per lo sprint4, con esito positivo.
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
