### ISSUE TITLE
Vostra comunicazione di test mancanti

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#806]
Facendo seguito alla vs. comunicazione in cui contestate la mancanza dei seguenti test:
31, 39, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 89, 93, 370
Abbiamo verificato e TUTTI i test risultano presenti sia nel file Excel che nella cartella, se il riferimento è all'ID del test e non ad altro:
https://github.com/infoserviceonline/it-fse-accreditamento/tree/main/GATEWAY/A1%23111%23INFOSERVICEONLINE/INFOSERVICE/FLY/2.0/FILES
Chiediamo delucidazioni circa la segnalazione ed alleghiamo alcuni esempi, **ricavati dal file pubblicato** a titolo esemplificativo, con l'esatta corrispondenza dei test case pdf, per capire se e dove avete rilevato l'errore.
Test 370:
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/ef4de6a9-93c0-4d0e-9a5f-e0755b2b7ac5)
Test case Pdf: 
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/cb94eafa-f9e1-44f3-8e16-8fefc9c91593)
Test 31:
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/23dff661-ba5f-45a1-9030-fa8e56444915)
Test case Pdf:
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/b5d6b1a2-17a3-4783-bfa1-5207758903c3)
Test 81:
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/c04c3feb-558e-42b4-bf5e-3c28404deb2e)
Test case pdf:
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/4d65f7ac-afda-4b5c-b545-74ac6d3ebf02)

Mi fermo qui perchè ritengo inutile farvi un elenco completo, i file, come ben sapete, sono pubblici e visibili qui:
https://github.com/infoserviceonline/it-fse-accreditamento/tree/main/GATEWAY/A1%23111%23INFOSERVICEONLINE/INFOSERVICE/FLY/2.0.
Vi ricordo che siete stati voi a dirmi di associare i test case utilizzando il NOME nel file Excel e non l'id.
Se c'è qualcosa che mi sfugge vi prego di comunicarmelo.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno.
Nel caso in cui stia facendo riferimento al messaggio da noi inviato all'interno dell'issue #703, le avevamo consigliato di fare riferimento al nome del caso di test unicamente al fine di ricondurre i casi di test presenti nella checklist, a quelli presenti nei file word di accreditamento. 
Invece, per quanto riguarda la compilazione del file _data.json_ è necessario, come indicato in [documentazione](
https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#struttura-dei-risultati-datajson), che il campo _ID_ riporti l'identificativo univoco del caso di test presente all'interno del piano di test, ossia la checklist.
L'errore ricevuto: 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/8bb06016-c4e7-4c7e-abe2-ebdf6104ad77)
si riferisce al fatto che i test indicati non sono correttamente referenziati nel file [data.json]( https://github.com/infoserviceonline/it-fse-accreditamento/blob/main/GATEWAY/A1%23111%23INFOSERVICEONLINE/INFOSERVICE/FLY/2.0/data.json). 
Ad esempio, il test con nome "VALIDAZIONE_TOKEN_JWT_RAD_KO" ha "id": "1" (che risulta duplicato) e non "31" come indicato sulla checklist. Lo stesso dicasi per il test con nome VALIDAZIONE_TOKEN_JWT_CAMPO_RAD_KO, che dovrebbe avere "id": "39":
 
<img width="245" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/9e09a22e-da40-4230-b072-241b1b0005d8">

![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/f4948158-fa77-43ec-9d38-54faceca1f75)

![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/142ebed6-76bf-4ed4-b318-e8c500863053)

La invitiamo ad effettuare le dovute correzioni verificando la corrispondenza tra _id_ e caso di test nel _data.json_. Grazie.

**Comment by infoserviceonline** [comment]
Grazie mille per il chiarimento, provvedo immediatamente, dopo di che immagino di dover fare una nuova pull request, visto che la precedente è stata chiusa, giusto?
Grazie.

**Comment by vigliottim** [comment]
Esatto, dovrà effettuare una nuova pull request. 
Riceverà aggiornamenti sull'esito delle elaborazioni come di consueto via e-mail.
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.

**Comment by infoserviceonline** [comment]
Riapro mio malgrado, per non creare troppi ticket, perchè non riesco più a fare nuove pull request. 
Ormai seguo sempre il solito percorso, ma stavolta ho risultati diversi, non capisco il perchè.
Partendo da qui: https://github.com/ministero-salute/it-fse-accreditamento/pulls
Premo questo:
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/c2c04f1e-72c9-4515-90c0-ab16f4c33404)
Mi esce, come sempre, questo:
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/3b205fb6-a38a-429b-a467-1605b19bae5c)
Premo questo: 
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/b5485737-6dc2-48cb-97f7-44876b28b6cb)
Ma quando seleziono il mio fork nella seconda casella, anzichè abilitare l'inserimento della pull, come le altre volte, mi si apre questa pagina:
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/6d837ea0-0c23-4407-91ee-7d30225dce13)
A questo punto non so che fare e non vorrei sbagliare e creare una pull nel posto sbagliato.
Potete aiutarmi?
Grazie.
