### ISSUE TITLE
Versione ICD9CM per CDA LDO

### ISSUE THREAD

**Issue by masieroandrea** [ministero-salute/it-fse-support#807]
Buongiorno,
ci sono più versioni del dizionario ICD9CM, nelle specifiche HL7 Italia non è indicata una versione in particolare.
Sono tutte valide o va utilizzata quella più recente?

Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, nelle Guide Implementative HL7 non vengono specificate le versioni dei dizionari in quanto bisogna sempre fare rifermento alla versione più aggiornata dello stesso.
Grazie

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso in cui sia necessario ulteriore supporto. Grazie.
