### ISSUE TITLE
Campania - Sprint 3

### ISSUE THREAD

**Issue by avlp** [ministero-salute/it-fse-support#808]
Buongiorno,
nell'ambito dello Sprint 3 del Crash Program di Regione Campania si è proceduto ad inviare un documento ai servizi di sussidiarietà ottenendo l'id TEMP_150_822119. Si richiede verifica affinché si possa procedere al passo Replace

**Comment by daniele-gubellini** [comment]
Alle 11:55 in ER abbiamo ricevuto un documento di specialistica con codice 470760 
(Il valore completo è "2.16.840.1.113883.2.9.2.150.4.4^470760")

**Comment by xenergy33** [comment]
Confermo la corretta gestione del referto sul nostro FSE

![image](https://github.com/ministero-salute/it-fse-support/assets/103534714/8025ab36-a7fc-4501-83e2-8230a4fab6d2)

![image](https://github.com/ministero-salute/it-fse-support/assets/103534714/c461efe8-f531-4c9a-930b-83f7ad21e273)

**Comment by g-maugeri-sogei** [comment]
potete verificare che nella replace i campi  <tip:targetObject> e <tip:RiferimentoDocumento>
contengono entrambi urn:uuid:8af748be-0c59-45d4-8353-f8f2fba56023?
La chiamata di recupero riferimenti va su target object che sembra contenere urn:uuid:61948047-beb6-4c4b-b18d-4f93ad17bfef  che pero' non trovo nella base dati.

**Comment by avlp** [comment]
Ecco la request:
`[2024-05-09 14:40:35,062] 
<com:ComunicazioneMetadatiRichiesta xmlns:com="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it" xmlns:tip="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it">
	<com:IdentificativoUtente>PROVAX00X00X000Y</com:IdentificativoUtente>
		<com:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</com:pinCode>
	<com:IdentificativoOrganizzazione>150</com:IdentificativoOrganizzazione>
	<com:StrutturaUtente>201123456</com:StrutturaUtente>
	<com:RuoloUtente>DRS</com:RuoloUtente>
	<com:ContestoOperativo>TREATMENT</com:ContestoOperativo>
	<com:TipoDocumento/>
	<com:IdentificativoAssistito>LRNSFO97R60F839V</com:IdentificativoAssistito>
	<com:PresaInCarico>true</com:PresaInCarico>
	<com:TipoAttivita>CREATE</com:TipoAttivita>
	<com:Metadato>
		<tip:TipologiaStrutturaProdDoc>Ospedale</tip:TipologiaStrutturaProdDoc>
		<tip:TipoMime>application/pdf+text/x-cda-r2+xml</tip:TipoMime>
		<tip:LivelloConfidenzialita>N</tip:LivelloConfidenzialita>
		<tip:TipologiaDocumentoAlto>REF</tip:TipologiaDocumentoAlto>
		<tip:TipologiaDocumentoMedio>11488-4</tip:TipologiaDocumentoMedio>
		<tip:TipologiaDocumentoBasso>PDF</tip:TipologiaDocumentoBasso>
		<tip:RiferimentoDocumento>urn:uuid:61948047-beb6-4c4b-b18d-4f93ad17bfef</tip:RiferimentoDocumento>
			<tip:Associazione>
				<tip:associationType>urn:ihe:iti:2007:AssociationType:RPLC</tip:associationType>
				<tip:sourceObject>doc1</tip:sourceObject>
				<tip:targetObject>urn:uuid:61948047-beb6-4c4b-b18d-4f93ad17bfef</tip:targetObject>
				<tip:submissionSetStatus>Original</tip:submissionSetStatus>
				<tip:previousVersion/>
            </tip:Associazione>
          <tip:IdentificativoUnivocoDocumento>doc1</tip:IdentificativoUnivocoDocumento>
		<tip:DataValidazioneDocumento>20240509144003</tip:DataValidazioneDocumento>
		<tip:RuoloAutore>DRS</tip:RuoloAutore>
		<tip:IstituzioneAutore>150201123456</tip:IstituzioneAutore>
			<tip:CodiceFiscaleAutore>PROVAX00X00X000Y</tip:CodiceFiscaleAutore>
		<tip:AssettoOrganizzativo>AD_PSC026</tip:AssettoOrganizzativo>
		<tip:TipoAttivitaClinica>DIS</tip:TipoAttivitaClinica>
		<tip:DataInizioPrestazione>20240509144003</tip:DataInizioPrestazione>
		<tip:DataFinePrestazione>20240509144003</tip:DataFinePrestazione>
	</com:Metadato>
	<com:IdentificativoApplicativoRichiedente>Ellipse AMB</com:IdentificativoApplicativoRichiedente>
	<com:FornitoreApplicativoRichiedente>Engineering Ingegneria Informatica S.p.A.</com:FornitoreApplicativoRichiedente>
	<com:VersioneApplicativoRichiedente>1.0.0</com:VersioneApplicativoRichiedente>
	<com:OpzioniRequest>
		<tip:chiave>GATEWAY</tip:chiave>
		<tip:valore>true</tip:valore>
	</com:OpzioniRequest>
		<com:OpzioniRequest>
			<tip:chiave>WORKFLOWINSTANCEID</tip:chiave>
			<tip:valore>2.16.840.1.113883.2.9.2.150.4.4.ba6cd57441962d1fa12e3a35c33d54cf64cec6e18f4a3ae8320399d3690391a8.bbc6d51d2b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId</tip:valore>
		</com:OpzioniRequest>
		<com:OpzioniRequest>
			<tip:chiave>MODE</tip:chiave>
			<tip:valore>ATTACHMENT</tip:valore>
		</com:OpzioniRequest>
</com:ComunicazioneMetadatiRichiesta>`

RESPONSE:
`TEMP_150_822230`

**Comment by vigliottim** [comment]
Buonasera,
procediamo alla chiusura della presente issue poiché non più attuale essendo terminato il Crash Program e essendo state rilasciate delle evolutive.
La presente verrà riaperta nel caso di nuove evidenze che confermino il persistere del problema.
Grazie.
