### ISSUE TITLE
Almeno uno dei seguenti vocaboli non è censito

### ISSUE THREAD

**Issue by Jack19650524** [ministero-salute/it-fse-support#809]
Buongiorno,
in verifica mi segnala il seguente errore
traceID: "053eeedf92001043"
spanID: "053eeedf92001043"
type: "/msg/vocabulary"
title: "Errore vocabolario."
detail: "Almeno uno dei seguenti vocaboli non è censito: [CodeSystem: 2.16.840.1.113883.2.9.6.1.5, Codes: 045489073, 045402031, 049706017, 048644049, 700058833], [CodeSystem: 2.16.840.1.113883.6.103, Codes: 0919, 4100, 4023, 90.01.2, 90.93.4, 90.01.3, 90.01.4, 90.05.3, 90.05.2, 04.81.1]"
status: 400
instance: "/validation/error"
workflowInstanceId: "2.16.840.1.113883.2.9.2.120.4.4.304ef67aa0ce91a93552b64b7863b21357b144c8bdfdb99d8ca6dbd26f01b697.2f6decccaf^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
per cortesia mi potete aiutare a risolvere questo problema.
grazie.

[cda.zip](https://github.com/ministero-salute/it-fse-support/files/15247007/cda.zip)

**Comment by vigliottim** [comment]
Buongiorno, la prima parte del messaggio di errore: _"Almeno uno dei seguenti vocaboli non è censito: [CodeSystem: 2.16.840.1.113883.2.9.6.1.5, Codes: 045489073, 045402031, 049706017, 048644049, 700058833]"_ si riferisce alla mancata corrispondenza tra _codeSystem_ e _code_ nelle sezioni _dettaglio farmaci_. 
Ad esempio, il seguente _code_ risulta errato per il farmaco LYRICA*75MG 14 CPS: 
`<code code="045402031" codeSystem="2.16.840.1.113883.2.9.6.1.5" codeSystemName="AIC" displayName="LYRICA*75MG 14 CPS" />`
Il codice corrispondente a _LYRICA*75MG 14 CPS_ risulta _036476113_.
Le suggeriamo di consultare il catalog disponibile al link: https://github.com/ministero-salute/it-fse-catalogs/blob/main/terminology/2.16.840.1.113883.2.9.6.1.5.csv, controllare che i codici AIC per i farmaci inseriti siano esatti ed eventualmente correggerli. 
Inoltre, le segnaliamo che gli errori relativi ai seguenti codeSystem e code indicati nella seconda parte del messaggio di errore [CodeSystem: 2.16.840.1.113883.6.103, Codes: 0919, 4100, 4023, 90.01.2, 90.93.4, 90.01.3, 90.01.4, 90.05.3, 90.05.2, 04.81.1] si riferiscono al fatto che nelle sezioni _procedura piano di cura_ i _codeSystemName_ e relativi _code_ sono scritti nel formato sbagliato:
_As is:_ `<code code="4100" codeSystem="2.16.840.1.113883.6.103" codeSystemName="ICD-9-CM" displayName="TRAPIANTO DI MIDOLLO OSSEO SAI" />`
_To be:_ `<code code="41.00" codeSystem="2.16.840.1.113883.6.103" codeSystemName="ICD9CM" displayName="TRAPIANTO DI MIDOLLO OSSEO SAI" />`
Di seguito le inseriamo il link del relativo catalog: https://github.com/ministero-salute/it-fse-catalogs/blob/main/terminology/2.16.840.1.113883.6.103.csv
La invitiamo a seguire le indicazioni riportate, effettuare le dovute correzioni e riprovare. 
Grazie.

**Comment by Jack19650524** [comment]
Buongiorno e grazie per la risposta
Il problema è che probabilmente la tabella https://github.com/ministero-salute/it-fse-catalogs/blob/main/terminology/2.16.840.1.113883.2.9.6.1.5.csv non è completa.
Gli AIC inseriti sono relativi a farmaci in commercio:
045489073  TRIMBOW*172/5/9MCG SOL 120ER
045402031 LYRICA*75MG 14CPS 
700058833  APEXXNAR*0,5ML 1 SIR. C/AGO ecc. ecc.
che non sono presenti nella tabella. In questi casi come possiamo comportarci?

saluti

**Comment by vigliottim** [comment]
Buon pomeriggio, grazie della segnalazione. 
I codici AIC mancanti verranno integrati per permettere la validazione del documento. 
Si precisa che il codice 700058833 non è presente nel dizionario AIC, ma è presente il codice 049965027 per il farmaco APEXXNAR.

**Comment by Jack19650524** [comment]
Grazie per l'aiuto.
