### ISSUE TITLE
CASO DI TEST 8 - Referto di Radiologia

### ISSUE THREAD

**Issue by NunzioAgfa** [ministero-salute/it-fse-support#81]
Buongiorno, nel caso di test 8, si richiede di generare un errore semantico, valorizzando soltanto l'indirizzo di residenza, senza valorizzare il Comune di residenza.
Ho provato, ma la validazione ha esito positivo.
Allego il cda in ingresso e riporto sotto i dati della vostra risposta.

{
  "traceID" : "9ac74644555091db",
  "spanID" : "9ac74644555091db",
  "workflowInstanceId" : "2.16.840.1.113883.2.9.2.160112.df18c0735bf6fcff829d04d4c6b1750c1c0c65df94d19e7d846bddacd7dcb7d0.cd35bc52c9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "warning" : "[W005 | Sezione Esame Eseguito: l'entry/act/code puÃ² essere valorizzato secondo i sistemi di codifica\n\t\t\tLOINC @codeSystem='2.16.840.1.113883.6.1'\n\t\t\tICD-9-CM @codeSystem='2.16.840.1.113883.6.103']"
}

[WEW808_IN.zip](https://github.com/ministero-salute/it-fse-support/files/10534858/WEW808_IN.zip)

**Comment by NunzioAgfa** [comment]
Stesso discorso per il TEST 9, nome del paziente non valorizzato, ma ottengo esito positivo della chiamata.
Allego il cda in ingresso e riporto sotto i dati della vostra risposta.

{
  "traceID" : "2ab5f5bf6919dba3",
  "spanID" : "2ab5f5bf6919dba3",
  "workflowInstanceId" : "2.16.840.1.113883.2.9.2.160112.6db573e64088e92a8e8f326edbe9b2dfe873d4e2657d807191e70061fc60872c.a070bcf3b3^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "warning" : "[W005 | Sezione Esame Eseguito: l'entry/act/code puÃ² essere valorizzato secondo i sistemi di codifica\n\t\t\tLOINC @codeSystem='2.16.840.1.113883.6.1'\n\t\t\tICD-9-CM @codeSystem='2.16.840.1.113883.6.103']"
}

[WEW805_IN_givenName.zip](https://github.com/ministero-salute/it-fse-support/files/10535040/WEW805_IN_givenName.zip)

**Comment by Ser-ena** [comment]
Buonasera, potrebbe cortesemente ripetere le casistiche sopra indicate eliminando dal CDA i tag corrispondenti, in particolare per il caso di test 8 eliminare <city>, per il 9 <given>

**Comment by NunzioAgfa** [comment]
Non ho capito bene la vostra risposta, forse è incompleta. Se si intende di fare un test eliminando completamente i due tag, cioè nel test 8 eliminando il tag "city" e nel test 9 eliminado il nodo "given", in questo caso per entrambi ottengo un errore semantico.
E' il risultato richiesto?

**Comment by Ser-ena** [comment]
Salve, sia il test 8 che il 9 riguardano  "la generazione di un errore semantico". Quindi è corretto che eliminando i tag sopracitati il risultato sia quello di un KO semantico.

**Comment by IStacchiotti** [comment]
Non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
