### ISSUE TITLE
Mancata creazione pull request

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#811]
Mi duole disturbare ancora, ma non riesco più a fare nuove pull request.
Ormai seguo sempre il solito percorso, ma stavolta ho risultati diversi, non capisco il perchè.
Partendo da qui: [[https://github.com/ministero-salute/it-fse-accreditamento/pulls]](https://github.com/ministero-salute/it-fse-accreditamento/pulls)
Premo questo:
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/bdd89473-2e17-47a9-8767-db7b1b899668)
Mi esce, come sempre, questo:
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/a7bf1687-64c9-4c9c-a2e0-3378e0b485c8)
Premo questo:
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/20b16b0f-18e8-47ae-b826-582c90f6ec9f)
Ma quando seleziono il mio fork nella seconda casella, anzichè abilitare l'inserimento della pull, come le altre volte, mi si apre questa pagina:
![image](https://github.com/ministero-salute/it-fse-support/assets/160219799/c8329724-8429-4321-b95f-78869b6789fa)

A questo punto non so che fare e non vorrei sbagliare e creare una pull nel posto sbagliato.
Potete aiutarmi?
Grazie.

**Comment by infoserviceonline** [comment]
"Magicamente" ha ripreso a funzionare.
Grazie.

**Comment by infoserviceonline** [comment]
Buongiorno, ci risiamo. Come due giorni fa non si riesce più a fare una pull request. Ormai il meccanismo è chiaro, ma di nuovo il sistema non risponde come dovrebbe, come descritto sopra e di nuovo non so che fare, aspetto e spero come l'ultima volta?
Grazie.

**Comment by infoserviceonline** [comment]
Mi rispondo da solo a beneficio di altri: se prima non si aggiungono o modificano file sul repository non si può effettuare una nuova pull request. Bastava dirlo...........GRAZIE DI NIENTE!

**Comment by vigliottim** [comment]
Buon pomeriggio, le confermiamo che non è possibile effettuare una pull request se prima non vengono caricati i file (i due branch selezionati risultano identici).
Rimaniamo a disposizione per altre richieste di supporto.
