### ISSUE TITLE
Anomalia per INI da Regione Emilia-Romagna

### ISSUE THREAD

**Issue by xenergy33** [ministero-salute/it-fse-support#812]
Utilizzando il servizio di recupero stato con questo workflowInstanceId:
2.16.840.1.113883.2.9.2.80.3.1.4.4.992fe25120deb6ea90d5f3661859cec29c2e25b869b235b71495c502a4ab352f.8594082886^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

abbiamo:
{
    "traceID": "c7d024125c93063c",
    "spanID": "29bb1e7608972934",
    "transactionData": [{
            "eventType": "VALIDATION",
            "eventDate": "2024-05-08T09:12:53.994+00:00",
            "eventStatus": "SUCCESS",
            "subject": "MDCFRR54A01D548J^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "080",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.992fe25120deb6ea90d5f3661859cec29c2e25b869b235b71495c502a4ab352f.8594082886^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "7c4f9ff1377c9669",
            "issuer": "integrity:S1#080#EMILIAROMAGNA",
            "expiringDate": "2025-05-08T09:12:54.005+00:00"
        }
    ]
}

ma se proviamo a pubblicare otteniamo:

{"traceID":"45767309b88a0e7e","spanID":"45767309b88a0e7e","type":"/msg/cda-match","title":"Errore in fase di recupero dell'esito della verifica.","detail":"Il CDA non risulta validato","status":400,"instance":"/cda-validation"}

Come mai si verifica questa anomalia su questo workflowInstanceId?
Restiamo in attesa di maggiori dettagli.

Grazie
Raffaele Pagliari

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Dalle analisi è emerso che sta effettuando una richiesta di sostituzione del seguente documento "identificativoDoc": `2.16.840.1.113883.2.9.2.80.4.4%5E109800053000080124TESTSPS3108679`.
Sembrerebbe, dal messaggio di errore ricevuto, che il nuovo documento che si vuole utilizzare per la sostituzione non sia stato validato.
Questo errore può verificarsi quando la validazione di un documento viene "bruciata" effettuando una pubblicazione o sostituzione dello stesso, ed in tal caso sarà necessario effettuare una nuova validazione del documento prima utilizzarlo per una nuova chiamata di pubblicazione/sostituzione.
La invitiamo a riprovare assicurandosi di eseguire la validazione del documento prima della chiamata di sostituzione.
Restiamo a disposizione in caso l'errore dovesse ripresentarsi.
Grazie

**Comment by nspazzoli** [comment]
Buongiono.

Il fatto che un workflow (che si tratti di una create o replace non cambia) venga bruciato dopo averlo usato ci è noto. 
Ma c'è comunqeu un problema nel caso che vi abbiamo esposto.

Il documento è stato validato (nostro ts=2024-05-08 11:12:53) ma poi il primo tentativo di pubblicazione è andato in timeout (ts=2024-05-08 11:28:31). 
A questo punto ci dovrebbero essere due possibilità.
- se il messagigo è stato recepito dal GTW: dovrebbe esserci eventType=REPLACE/PUBBLICATION e il workflow deve essere bruciato
- se il messaggio NON è stato recepito dal GTW: non non dovrebbe esserci eventType di tipo REPLACE/PUBBLICATION MA il workflow DEVE essere ancora valido.

Se questo è il comporttamento atteso, allora non ci torna quanto segue:

Facendo per la QRY per workflow otteniamo il solo eventType di validazione 
```
{
"traceID": "c7d024125c93063c",
"spanID": "29bb1e7608972934",
"transactionData": [{
"eventType": "**VALIDATION**",
"eventDate": "2024-05-08T09:12:53.994+00:00",
"eventStatus": "SUCCESS",
"subject": "MDCFRR54A01D548J^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
"organizzazione": "080",
"workflowInstanceId": "2.16.840.1.113883.2.9.2.80.3.1.4.4.992fe25120deb6ea90d5f3661859cec29c2e25b869b235b71495c502a4ab352f.8594082886^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
"traceId": "7c4f9ff1377c9669",
"issuer": "integrity:S1#080#EMILIAROMAGNA",
"expiringDate": "2025-05-08T09:12:54.005+00:00"
}
]
}
```

Quindi il worflow non dovrebbe essere bruviato, ma il successivo tentativo di invio REPLACE ottiene http=400 come se fosse stato invece recepito.
**In sostanza: dove è finita questa pubblicazione di questo documento?**

Grazie
Nicola Spazzoli

**Comment by LucaRogledi** [comment]
Buon pomeriggio, per verificare l'origine dell'problema le chiederemmo gentilmente di allegare la risposta completa (contenente govway_id/traceId) ricevuta dal sistema in seguito alla chiamata di validazione in questione effettuata prima della sostituzione.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, potrebbe fornirci la response completa della pubblicazione che va in timeout? Grazie.

**Comment by nspazzoli** [comment]
Buonasera, 

non ho una risposta nella richiesta di pubblicazione (replace), ma ho avuto errore
```
Errore IO verso il GTW NAZIONALE
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
```


Quindi non ho informazioni, se non il timestamp della tentativo 2024-05-08 11:28:31.843

Grazie

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Le segnaliamo che le pubblicazioni/sostituzioni in caso di timeout sono da considerarsi come pubblicazioni/sostituzioni andate in ko, bruciando le validazioni effettuate in precedenza. Sarà pertanto necessario rivalidare il documento per l'invocazione corretta della nuova chiamata di pubblicazione/sostituzione. Restiamo a disposizione per ulteriori richieste di supporto. Grazie.

**Comment by vigliottim** [comment]
Buongiorno, 
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue. 
Potrà riaprila nel caso in cui fosse necessario ulteriore supporto. 
Grazie.
