### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by mariogoodbread** [ministero-salute/it-fse-support#813]
Buonasera, 
ho creato la pull request "_Accreditamento A1#111#NISATEKXX_ #1394" con i seguenti dati:

commonName auth: A1#111#NISATEKXX
subject_application_vendor: nisatek
subject_application_id: adtweb
subject_application_version: 2.0

Potrei sapere se è corretta cortesemente?

**Comment by vigliottim** [comment]
Buonasera, le confermiamo che la pull request [1394](https://github.com/ministero-salute/it-fse-accreditamento/pull/1394) è stata creata correttamente. 
Riceverà l'esito delle elaborazioni via e-mail. 
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
