### ISSUE TITLE
Codici AIC di farmaci non riconosciuti per il PatientSummary.

### ISSUE THREAD

**Issue by SimoneLepida** [ministero-salute/it-fse-support#814]
Buongiorno,
validando un PAS ho ottenuto come risposta quanto segue:
{
    "detail": "Almeno uno dei seguenti vocaboli non è censito: [CodeSystem: 2.16.840.1.113883.2.9.6.1.5, Codes: 046345029, 047398019]",
    "instance": "/validation/error",
    "spanID": "4bac6511b6987a40",
    "status": 400,
    "title": "Errore vocabolario.",
    "traceID": "4bac6511b6987a40",
    "type": "/msg/vocabulary",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.80.4.4.3007cb8d9ea802c238b0f957449fff563cf8976ec89e44c0a9601587b7603c37.265d77c98d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
Analizzando il contenuto del CDA, ho visto che quei due codici AIC fanno riferimento a farmaci attualmente in commercio.
Potrebbe essere la vostra banca dati dei codici AIC non aggiornata?

**Comment by SimoneLepida** [comment]
Come richiesto:
[pas_cda2022.txt](https://github.com/ministero-salute/it-fse-support/files/15260497/pas_cda2022.txt)
Saluti.

**Comment by vigliottim** [comment]
Buongiorno, la informiamo che i codici AIC indicati sono stati aggiunti.
La preghiamo di riprovare e segnalarci eventuali anomalie.
Grazie.

**Comment by vigliottim** [comment]
Buon pomeriggio, 
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
