### ISSUE TITLE
LDO per strutture residenziali 

### ISSUE THREAD

**Issue by ub2012** [ministero-salute/it-fse-support#815]
Buongiorno, volevo richiedere conferma sull'implementazione del documento LDO per strutture sanitarie non ospedaliere (RSA, RSD, CP, DH, Hospice) o servizi non ospedalieri erogati da strutture di tipo ospedaliero.

**Comment by ub2012** [comment]
Buongiorno, intendo servizi ambulatoriali o di riabilitazione erogati da strutture socio-sanitarie

Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue. 
Sarà possibile riaprirla nel caso in cui avesse bisogno di ulteriore supporto. Grazie.
