### ISSUE TITLE
CRASH PROGRAM - Sprint 4 - RDE FVG - RDA Lombardia - UC6,UC8,UC12 Sostituzione e eliminazione: richiesta cortese verifica a regione Lombardia.

### ISSUE THREAD

**Issue by ChiaraCeccottiFVG** [ministero-salute/it-fse-support#818]
Buongiorno,
Oggi abbiamo avuto modo di riprovare gli Use Case 

- UC6_SostituzioneDocumento, 
- UC8_EliminazioneDocumento e 
- UC12_ValidazionePubblicazioneSostituzioneContestuale 

per una tipologia di documento diversa rispetto il PSS (per il quale otteniamo errore Ini 500 - riferimento issue 801 in corso di verifica). 
Per la lettera di dimissione ospedaliera la transazione va a buon fine con successo.

Abbiamo successivamente provato a interrogare i metadati per verifica e volevamo chiedervi un riscontro per capire se vi risulta tutto corretto lato nostro. 

**UC6_SostituzioneDocumento:** 
il documento ID 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715242602423_NEW sostituisce il documento con ID 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715242602423. 

Ci saremmo aspettati:
- il doc 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715242602423 in stato Deprecated
- il doc 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715242602423_NEW in stato Approved 

ma li vediamo entrambi in stato Approved 

**UC8_EliminazioneDocumento:** 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715241621557 
ci saremmo aspettati lo stato Deleted e lo vediamo in stato Approved

**UC12_ValidazionePubblicazioneSostituzioneContestuale:** 
2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715243228611_NEW sostituisce il documento 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715243228611 

ci saremmo aspettati:
- il 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715243228611_NEW Approved
- il 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715243228611 Deprecated 

ma li vediamo entrambi approved.

Vi chiederemmo cortesemente se potreste verificare se stiamo sbagliando qualcosa lato nostro e se la situazione lato vostro vi risulta coerente. 
Ringraziandovi molto per la collaborazione, vi auguriamo una buona giornata. 

Per completezza riportiamo anche la transazione di stato di uno dei casi di test eseguiti 
(UC6 - 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715242602423_NEW)
```
{
    "traceID": "0685420187393d26",
    "spanID": "52850a8684f5d1e6",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-05-09T08:16:57.354+00:00",
            "eventStatus": "SUCCESS",
            "subject": "BLUPLA57D20A794H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "060",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.c824909edef00711a2000af972d8ad3f83d8339ae8de21506c688a556c186511.f1bd6d195d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "4d87f9e63c716d49",
            "issuer": "integrity:S1#060#FRIULIVENEZIAGIULIATEST",
            "expiringDate": "2025-05-09T08:16:57.365+00:00"
        },
        {
            "eventType": "REPLACE",
            "eventDate": "2024-05-09T08:17:13.978+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715242602423_NEW",
            "subject": "BLUPLA57D20A794H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "DIS",
            "organizzazione": "060",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.c824909edef00711a2000af972d8ad3f83d8339ae8de21506c688a556c186511.f1bd6d195d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "3d15e4c81a7a8de1",
            "issuer": "integrity:S1#060#FRIULIVENEZIAGIULIATEST",
            "expiringDate": "2025-05-09T08:17:13.989+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-05-09T08:17:18.013+00:00",
            "eventStatus": "SUCCESS",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.c824909edef00711a2000af972d8ad3f83d8339ae8de21506c688a556c186511.f1bd6d195d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-05-09T08:17:18.023+00:00"
        },
        {
            "eventType": "SEND_TO_EDS",
            "eventDate": "2024-05-09T08:17:18.437+00:00",
            "eventStatus": "SUCCESS",
            "message": "{\"esito\":true}",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.c824909edef00711a2000af972d8ad3f83d8339ae8de21506c688a556c186511.f1bd6d195d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-05-09T08:17:18.447+00:00"
        },
        {
            "eventType": "MIDDELWARE FVG - VALIDAZIONE",
            "eventDate": "2024-05-09T10:16:57.449+0200",
            "eventStatus": "SUCCESS",
            "subject": "BLUPLA57D20A794H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "subjectRole": "AAS",
            "organizzazione": "060",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.c824909edef00711a2000af972d8ad3f83d8339ae8de21506c688a556c186511.f1bd6d195d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "4d87f9e63c716d49"
        }
    ]
}

```

**Comment by EugenioGuagliardi** [comment]
Buonasera, stiamo verificando le segnalazioni.
Vi aggiorniamo appena possibile!

Grazie

**Comment by EugenioGuagliardi** [comment]
Salve,
abbiamo verificato ed effettivamente abbiamo fatto una regressione nella restituzione dei metadati dopo l'ultima modifica fatta nei precedenti Sprint per risolvere altro problema.
Stiamo correggendo il nostro software, vi aggiorniamo appena fatto.

Grazie per la segnalazione

Eugenio

**Comment by ChiaraCeccottiFVG** [comment]
Grazie per l'aggiornamento e per le vostre verifiche.
Buon pomeriggio.

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
Grazie per le verifiche.
Abbiamo rieseguito gli use case.

Per lo use case UC8_EliminazioneDocumento ci risulta tutto corretto (ID documento: 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715680315595).

Per lo use case UC6_SostituzioneDocumento abbiamo provato a sostituire il documento 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715679671598 con 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715679671598_NEW.

Interrogando i due documenti il doc 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715679671598_NEW non lo troviamo invece per il 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715679671598 ci vengono restituiti i metadati e lo stato è Approved. 
Forse qualcosa è andato in errore perchè ci aspettavamo il contrario. Eventualmente fateci sapere se c'è qualcosa lato nostro che non vi torna.

Nella transazione di stato viene restituito Success per la replace:
```
{
    "traceID": "0fd499be15747876",
    "spanID": "e5892354b310895f",
    "transactionData": [
        {
            "eventType": "VALIDATION",
            "eventDate": "2024-05-14T09:41:16.271+00:00",
            "eventStatus": "SUCCESS",
            "subject": "BLUPLA57D20A794H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "organizzazione": "060",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.c824909edef00711a2000af972d8ad3f83d8339ae8de21506c688a556c186511.79f8e76fda^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "a8ecbf3e96333142",
            "issuer": "integrity:S1#060#FRIULIVENEZIAGIULIATEST",
            "expiringDate": "2025-05-14T09:41:16.282+00:00"
        },
        {
            "eventType": "REPLACE",
            "eventDate": "2024-05-14T09:41:31.937+00:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715679671598_NEW",
            "subject": "BLUPLA57D20A794H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "DIS",
            "organizzazione": "060",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.c824909edef00711a2000af972d8ad3f83d8339ae8de21506c688a556c186511.79f8e76fda^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "48c990e9b57d7028",
            "issuer": "integrity:S1#060#FRIULIVENEZIAGIULIATEST",
            "expiringDate": "2025-05-14T09:41:31.947+00:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-05-14T09:41:32.523+00:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:PIT16CODE CONTEXT:Wrong attribute value of $ACTIONIDURN$SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:PIT24CODE CONTEXT:Wrong type of $PURPOSEOFUSEURN$ attribute value",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.c824909edef00711a2000af972d8ad3f83d8339ae8de21506c688a556c186511.79f8e76fda^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-05-14T09:41:32.534+00:00"
        },
        {
            "eventType": "MIDDELWARE FVG - VALIDAZIONE",
            "eventDate": "2024-05-14T11:41:16.369+0200",
            "eventStatus": "SUCCESS",
            "subject": "BLUPLA57D20A794H^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "subjectRole": "AAS",
            "organizzazione": "060",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.60.4.4.c824909edef00711a2000af972d8ad3f83d8339ae8de21506c688a556c186511.79f8e76fda^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "a8ecbf3e96333142"
        }
    ]
}
```
Grazie per la collaborazione,
buona giornata.

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
abbiamo riprovato la Sostituzione (UC6) provando ad eseguire una replace del documento 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715765535643 con il
2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715765535643_NEW
interrogando i metadati il
2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715765535643_NEW non ci viene restituito
il 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715765535643 ci viene restituito in stato Approved.
(ci saremmo aspettati l'inverso ma magari stiamo interpretando male noi).

Grazie e buona giornata.

**Comment by EugenioGuagliardi** [comment]
Salve, crediamo di avere sistemato, potete riprovare adesso e dirci l'esito?
Grazie per la collaborazione.

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
abbiamo eseguito un test di REPLACE (UC6_SostituzioneDocumento) con **successo**.
Abbiamo sostituito il documento 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715927810140 con il 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715927810140_NEW. 
Interrogando il documento 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715927810140 non ci vengono restituiti i metadati (corretto) interrogando 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715927810140_NEW ci vengono restituiti i metadati e lo stato è Approved. (comportamento atteso).
Vi ringraziamo.
Buona giornata.

**Comment by vigliottim** [comment]
Buonasera, 
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso in cui sia necessario ulteriore supporto.
Grazie.
