### ISSUE TITLE
CRASH PROGRAM Sprint 4 - Regione Toscana - updateMetadata

### ISSUE THREAD

**Issue by cdezorzi** [ministero-salute/it-fse-support#819]
Buonasera,
durante il test UC4_Aggiornamento_Metadati
idDocumento 2.16.840.1.113883.2.9.2.90.4.4^9999.LAB.910.44004
prendiamo il seguente errore

{
    "traceID": "80ea211b489b1688",
    "spanID": "80ea211b489b1688",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "detail": "{\"traceID\":\"000000000000000080ea211b489b1688\",\"spanID\":\"40af0bf23213b1e9\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R219CODE CONTEXT:Missing SubmissionSet.authorSEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R175CODE CONTEXT:Wrong value of authorPerson: it is emptySEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R173CODE CONTEXT:Wrong value of authorInstitution: it is emptySEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R173CODE CONTEXT:different values for  value of authorInstitution in DocumentEntry and SubmissionSetSEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R177CODE CONTEXT:different values for  value of authorRole in DocumentEntry and SubmissionSet\",\"instance\":\"error/generic\"}",
    "status": 500,
    "instance": "/msg/service-error/ini"
}

Grazie

**Comment by daniele-gubellini** [comment]
Buongiorno, per esaminare le cause dell'errore vi dobbiamo chiedere di riprovare.
Grazie

**Comment by cdezorzi** [comment]
Buongiorno,
abbiamo rieseguito il test di seguito l'errore della response

{
    "traceID": "54002d178d6f61a3",
    "spanID": "54002d178d6f61a3",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "detail": "{\"traceID\":\"000000000000000054002d178d6f61a3\",\"spanID\":\"f0c5f8124e5166cc\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R219CODE CONTEXT:Missing SubmissionSet.authorSEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R175CODE CONTEXT:Wrong value of authorPerson: it is emptySEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R173CODE CONTEXT:Wrong value of authorInstitution: it is emptySEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R173CODE CONTEXT:different values for  value of authorInstitution in DocumentEntry and SubmissionSetSEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R177CODE CONTEXT:different values for  value of authorRole in DocumentEntry and SubmissionSet\",\"instance\":\"error/generic\"}",
    "status": 500,
    "instance": "/msg/service-error/ini"
}

Grazie

**Comment by daniele-gubellini** [comment]
All'interno del _RegistryPackage_ mancano _authorRole_, _authorInstitution_ e _authorPerson_.

**Comment by vigliottim** [comment]
Buongiorno, è stato rilasciato un aggiornamento. La preghiamo di riprovare. Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Potrà riaprirla nel caso in cui fosse necessario ulteriore supporto.
Grazie.
