### ISSUE TITLE
CodicI AIC covid mancanti

### ISSUE THREAD

**Issue by gmarzi** [ministero-salute/it-fse-support#82]
Nel test n.3 del certificato vaccinale  e' previsto nel CDA il vaccini anti covid.
Da errore di aic non presente (provati tutti gli 8 aic della regione lazio)

**Comment by IStacchiotti** [comment]
Buongiorno, le chiederei cortesemente di riprovare, l'errore non dovrebbe più verificarsi. Grazie.

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
