### ISSUE TITLE
Errore in fase di pubblicazione dei documenti

### ISSUE THREAD

**Issue by MerialdoElco** [ministero-salute/it-fse-support#821]
Buon pomeriggio,
stiamo provando ad invocare i servizi per la pubblicazione dei documenti con attachment, firmando i jwt con i certificati che ci erano stati rilasciati per l'accreditamento della fase di validazione.
Provando ad invocare il servizio riceviamo questo in risposta:
`{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"7f755609-0e0b-11ef-93a7-005056ae54fa"}`
Per la fase di pubblicazione dei documenti, possiamo utilizzare già i certificati in nostro possesso o ne dobbiamo richiedere degli altri?

Rimango a disposizione
Un saluto

Giuseppe Merialdo

**Comment by MerialdoElco** [comment]
Buongiorno,
ho effettuato la correzione che mi avete indicato, non ci viene più ritornato l'errore 403.
Ora in risposta riceviamo questo errore:
`{"traceID":"c56325593d409f0a","spanID":"c56325593d409f0a","type":"/msg/document-hash","title":"Verifica hash fallita.","detail":"Verifica hash fallita.","status":400,"instance":"/jwt-hash-match"}`

Grazie
Un saluto

**Comment by vigliottim** [comment]
Buongiorno, 
il nuovo errore da lei riscontrato sembra essere causato dall'errata valorizzazione del campo contenente l'hash del file pdf.
Pertanto, la preghiamo di controllare che il valore del campo _attachment_hash_ contenuto nei token nella chiamata al servizio corrisponda effettivamente all'hash (sha256) del pdf passato in ingresso, come indicato in documentazione:
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/88cc348c-3724-41eb-9a1f-a8de9801198a)
Rimaniamo a disposizione per ulteriori chiarimenti.
Grazie.

**Comment by MerialdoElco** [comment]
Buongiorno,

ho effettuato la correzione indicata e ho fatto ulteriori test.
Per l'ultimo tentativo ho ricevuto in risposta questo messaggio:
`{"traceID":"1ce0fed2fa63150a","spanID":"1ce0fed2fa63150a","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.10.4.4.12345.e916a69048bcae2a29995057bd2b48573c0c98ce926b0482ce098d42bed5e6cd.83ddf8edf1^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`
Ora l'invio è andato a buon fine.
Grazie ancora per il supporto.

Un saluto
