### ISSUE TITLE
Errore WRONG_CLAIMS_ON_LOG

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#822]
Buonasera, ho ricevuto l'errore WRONG_CLAIMS_ON_LOG per 5 su 21 test case, dalla descrizione (Claims(appId,appVersion,appVendor) della chiamata al gtw differenti da quelli dichiarati nel data.json) non riesco a risalire al problema, nel senso che tutti i test case sono stati eseguiti nello stesso modo e sono dichiarati nel file data.json tutti insieme all'inizio del file con gli stessi dati:
  "appVendor": "INFOSERVICE DI FRANCESCO LEO",
  "appID": "FLY",
  "appVersion": "2.0",
Com'è possibile che gli stessi dati vadano bene per alcuni test e male per altri? Sicuramente mi sfugge qualcosa, potete chiarirmi cosa genera l'errore?
Aggiungo che essendo tutti i test prodotti con la stessa identica chiamata ai token non è possibile che alcuni vadano bene ed altri no, inoltre perchè mi segnalate 3 volte per ogni caso lo stesso erroe? Allego json errori.
[errors.json](https://github.com/ministero-salute/it-fse-support/files/15271139/errors.json)
Ed infine: perchè durante la validazione non ho ricevuto gli errori che adesso vengono invece segnalati nei CDA? Esistono due tipi di validazione?
Grazie mille.

**Comment by vigliottim** [comment]
Buongiorno, 
l'errore ricevuto:
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/f83324d3-ec4a-4391-8dda-ac609ee3f07f)
indica che i valori contenuti nella tripletta _(appVendor, appID, appVersion)_ riportata nel _data.json_ della pull request: 
```
"appVendor": "INFOSERVICE DI FRANCESCO LEO",
"appID": "FLY",
"appVersion": "2.0"
```
non corrispondono a quelli contenuti nei token utilizzati nelle invocazioni: subject_application_vendor, subject_application_id, subject_application_version.
Infatti, i token contengono i seguenti campi:
<img width="286" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/b73918ab-c1c8-4cc2-b1ce-dcae46e6c686">
La preghiamo di riprovare dopo aver effettuato le opportune correzioni, rendendo coerenti tripletta e campi dei token.
Grazie.

**Comment by infoserviceonline** [comment]
Ok, provvedo, grazie
