### ISSUE TITLE
VERIFICA_NON_SUPERATA Test 13 e 14

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#823]
Buongiorno, sto controllando gli errori segnalati con VERIFICA_NON_SUPERATA ed ho notato che non corrispondono al vero, nel senso che i tag che nell'errore sarebbero vuoti sono in realtà correttamente validati. Inserisco solo un esempio ma ce ne sono molti:
"description" : "<error code='059' attribute='code' actual = '' expected = '**48765-2**'>ClinicalDocument/component/structuredBody/component/section[ID='Storia_Clinica']/component/section[ID='Allergie']/code</error>"
"description" : "<error code='060' attribute='codeSystem' actual = '' expected = '**2.16.840.1.113883.6.1**'>ClinicalDocument/component/structuredBody/component/section[ID='Storia_Clinica']/component/section[ID='Allergie']/code</error>"
"description" : "<error code='061' attribute='codeSystemName' actual = '' expected = '**LOINC**'>ClinicalDocument/component/structuredBody/component/section[ID='Storia_Clinica']/component/section[ID='Allergie']/code</error>"
"description" : "<error code='062' attribute='displayName' actual = '' expected = '**Allergie e/o reazioni avverse**'>ClinicalDocument/component/structuredBody/component/section[ID='Storia_Clinica']/component/section[ID='Allergie']/code</error>"
Tag Xml rilevato:
<code code="**48765-2**" codeSystem="**2.16.840.1.113883.6.1**" codeSystemName="**LOINC**" displayName="**Allergie e/o reazioni avverse**"/>

Premesso che il CDA è identico al vostro esempio ed è stato validato correttamente, ho notato, però, che gli errori fanno riferimento alla section con ID='Allergie', mentre nel vostro e nel nostro CDA la section ha come ID 'ALLERGIA_INTOLLERANZA'. Tra l'altro anche nella documentazione (HL7IT-IG_CDA2_RAD-v1.1-S.pdf, PAGINA 56) la section è indicata con **Allergie**. Non è che per caso non leggendo l'ID corretto manda in anomalia tutto, ma non segnala l'effettivo errore, ossia l'ID della section? 28 errori mi sembrano un po' troppi per un test case validato e non capisco come mai il validatore non abbia egnalato niente.
Allego json errori e CDA
[cda.zip](https://github.com/ministero-salute/it-fse-support/files/15272093/cda.zip)
[errors.json](https://github.com/ministero-salute/it-fse-support/files/15271959/errors.json)
Grazie.

**EDIT: ho modificato l'id della section in "Allergie" e mi è stato validato dall'API, ciò vuol dire che non c'è nessun controllo, ma prima di rifare tutti i test case attendo una vostra conferma alla mia ipotesi.**
Certo, potrei usare l'inapplicabilità, come praticamente tutti i miei colleghi, ma spero non sia necessario..........

**Comment by vigliottim** [comment]
Buongiorno, 
alcuni degli errori ricevuti inerenti al caso di test 13 sono causati dall'assenza nel CDA della section avente _id="Allergie"_, obbligatoria da documentazione: 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/0fcb7e33-8f98-4402-993b-0a0b153844db)
Per completare il processo di accreditamento, è necessario seguire **fedelmente** le indicazioni contenute nei file excel: https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/1-Referto%20di%20Radiologia. Esse presentano dei controlli più stringenti rispetto ad HL7 Italia. 
I file di esempio caricati sul portale non possono essere usati come modelli da cui partire per l'accreditamento in quanto non seguono tali linee guida. 
La preghiamo di correggere gli errori e riprovare.

**Comment by infoserviceonline** [comment]
Grazie per la conferma, nello specifico devo ricreare solo i pdf test case segnalati e fare una pull request, con upload, senza modificare tutto il resto? E' la prima volta quindi chiedo.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, 
poiché la precedente è stata chiusa, dovrà creare una nuova PR e aggiungere tutti i file necessari.
Procediamo alla chiusura del presente ticket e rimaniamo a disposizione per ulteriori richieste di supporto.
