### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by embrunoR** [ministero-salute/it-fse-support#824]
Buongiorno, stiamo riscontrando l'errore 403 per l'inivio di una richiesta di validazione.

appVersion=2.0
appVendor=Santer Reply
appId=Gestione Ambulatoriale

{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"50988ada-0ead-11ef-9223-005056ae7395"}

Cosa sto sbagliando ? 

Grazie.

**Comment by vigliottim** [comment]
Buongiorno, 
dalle analisi effettuate risulta che il campo _iss_ contenuto nei token non è stato correttamente popolato. 
Esso deve essere valorizzato con _auth:_/_integrity:_ seguito dal common name del certificato di firma, che non risulta quello da voi indicato:

**_Authorization Bearer:_**
_As is:_ "iss": "auth:S1#111REPLYXX"
_To be:_ "iss": "auth:S1#111#REPLYXX"

**_FSE-JWT-Signature_**
_As is:_ "iss": "integrity:S1#111REPLYXX"
_To be:_ "iss": "integrity:S1#111#REPLYXX"

Vi chiediamo di riprovare ed informarci se l'errore persiste. 
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue. 
Sarà possibile riaprirla nel caso in cui avesse bisogno di ulteriore supporto. Grazie.
