### ISSUE TITLE
TokenAuthenticationFailed - 401 - Invalid token - govway_id":"b86c4d9e-0ea6-11ef-9223-005056ae7395"

### ISSUE THREAD

**Issue by medimatic-italy** [ministero-salute/it-fse-support#825]
Buongiorno,
 
stiamo provando ad accedere ai servizi https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation ma otteniamo un errore nell'autenticazione dei token che non riusciamo ad identificare nonostante molteplici tentativi:
 
{"type":"https://cas5-0-urlprotect.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgovway.org%2fhandling%2derrors%2f401%2fTokenAuthenticationFailed.html%22%2c%22title%22%3a%22TokenAuthenticationFailed%22%2c%22status%22%3a401%2c%22detail%22%3a%22Invalid&umid=a8c902df-3e3a-4697-922b-d399c8695f70&auth=71a13bea07be23dc94f0190f69b0bbb0f54ab581-491cbcd86922890ab8a2d7d47a8e88d560d1851c token","govway_id":"b86c4d9e-0ea6-11ef-9223-005056ae7395"}
 
Potreste cortesemente indicarci il motivo dell’errore ? Entrambi i token, riportati qui di seguito, risultano corretti in JSON Web Tokens - jwt.io.
 
Grazie per l’assistenza.
 
Cordiali saluti.
 
MediMatic Srl 
 
Bearer token:
 
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNsaWVudDExIiwieDVjIjpbIk1JSUZhekNDQTFPZ0F3SUJBZ0lVSGJ6dkNNTjBxcjRBWmVvT2FEdXJVNmZ3cVowd0RRWUpLb1pJaHZjTkFRRUxCUUF3VnpFbk1DVUdBMVVFQXd3ZVEwRWdUV2x1YVhOMFpYSnZJR1JsYkd4aElGTmhiSFYwWlNCVVpYTjBNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1Rc3dDUVlEVlFRR0V3SkpWREFlRncweU5EQTFNRE14TkRRek1ERmFGdzB5TnpBMU1EUXhORFF6TURCYU1Hd3hDekFKQmdOVkJBWVRBa2xVTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUjh3SFFZRFZRUmhEQlpEUmpwSlZDMVFVazlXUVZnd01GZ3dNRmd3TURCWk1Sc3dHUVlEVlFRRERCSlRNU014TVRFalRVVkVTVTFCVkVsRFdERXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDY2Jmbkh3b1gxL3c0N0pcdTAwMkJuaWJDTGhpMGpDcEFWdTFIcE1hbE9uM3BaeDMxY3U0NWg1OWg3YkFPUTdUTVQzUmc0bjBUd1gzMXRUeHZNMDdkV01ZVXNJV0ZtTlg1NXZMTXRram1Lc0RTT0djVk5rNVhqbUtKV05TazZsMDJBR0xnWm15Nmk5Zzh1aWVqYk9RN2VLemVTVThnemFXRDVWTGpYWnZLblNkUGJhejBjSFExZTZtaU1mdUVCL1Vmd3pHQzhESGZKS3JoeENzS2VoQmJteE9temUwb3hjbVRka1pPcHhlclpPbWVaTmxsWDBNWlBpaDR5NEdxTHBRXHUwMDJCQWRLS3pVS0lOLzVxVEp6QzNIdldEY1ZCQlNSRnlrUW1QSHRlcUVnbDZWa09GUXo1RkM1ZW1Wb0Z3YXNRQVBickRzWTlBVDNqYk5hMVdPMklFd2RJZ1FaZ0hWQWdNQkFBR2pnZ0VZTUlJQkZEQWZCZ05WSFNNRUdEQVdnQlFXT2FrYUJZbTNEeTJ5TmUzQ0NackZBNE1pUHpBU0JnTlZIU0FFQ3pBSk1BY0dCU3RNSFFFTE1JR3RCZ05WSFI4RWdhVXdnYUl3Z1pcdTAwMkJnZ1p5Z2dabUdnWlpvZEhSd2N6b3ZMMk5oYzI5blpXbHpkbWxzTG5OdloyVnBMbWwwTDJWcVltTmhMM0IxWW14cFkzZGxZaTkzWldKa2FYTjBMMk5sY25Sa2FYTjBQMk50WkQxamNtd21hWE56ZFdWeVBVTk9KVE5FUTBFclRXbHVhWE4wWlhKdksyUmxiR3hoSzFOaGJIVjBaU3RVWlhOMEpUSkRUeVV6UkUxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVWxNa05ESlRORVNWUXdIUVlEVlIwT0JCWUVGSEcwYmQ2R05mODJzdGV3OXlmaDNZalVCYmpMTUE0R0ExVWREd0VCL3dRRUF3SUdRREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBaENLUVkxSUYzRDJmbENTd3VoM0c3TDV6cXlENHUxcWQ3OXVoSDV4NlFPaVBiZThOcExKdFx1MDAyQlBDSGYwRUdBRFFSL21ZMjVRdlZiUzRMdjFCaC9aXHUwMDJCalJxMUIyeGtrd012NDNDZzFuRm5KUWFRMGJyM0RwY0Zyb1JDbFNyd25kODVubm1HRURQL0poYnJuYjh4MkhwbTlESk5BXHUwMDJCZGtFbkxyL085ZXF1NXJiSjNTWWo4Yk9hSXpjWFJKQzA4ZlA1Ni9PT1FxQzV6b1BzbjZLXHUwMDJCMWxxd1FJV1FnV05kU20vQWFNQ09JVWdHRmxRTFJZZG9ld0JiY2VySG0wVldwSFdiN1RkbVdKdFh1MktVQTRXdGMva05LT2RUcUNza1c0ZkU1c2U5OWRjWWllZkM4TU9CZEwvVThKejlrbFU3dnZ6QWV0UDBrZkdDanZVVC9qUFh5aWF0bzlnekhORTkwSkhFZVF4eWQ4QXo2UzNhallzc2ZZMnMyS0lhbFgya2tyR1FHS1VmWUYxbVBtVVBORFFYSFFtUzBCNGp4YzdqaGtaVEcxQlYvRU9HbHJcdTAwMkJsMWpnYXFVNng5UXVsVmY2WHpNaVZBMTBaMndKYjdwN0wzVU9ZZ0RmUlx1MDAyQjB0dFx1MDAyQkcvRlpkWUpzRUNuY3lLNVx1MDAyQng2Q3o2dG1DZ2U3eE5HUjA5VVd2cFpZMmVKT0JITlk4RTNIaDVFa0NMaVp2UzJ5Y0p6MnAxcDlNdm1Lb05Wem5VbW5vbXpPRWdqblx1MDAyQkJYWGpCL0FQYjY5Y2I0SUhadkR4cjR3UGRnQ3ZQZmhDRXVCbTZxTEcxN0tuTkhWNVgxajNqUUtMTEh0VGh4dUlMbHkvNnJJMmtsOVhOSWhFTVBuRGhoM1h2WXNvUkpRaFIyd2RTRHZtWDUweERBbmxTOC9BQUdsTGc9Il19.eyJpc3MiOiJhdXRoOlMxIzExMSNNRURJTUFUSUNYMSIsImlhdCI6MTcxNTMyOTgzMCwiZXhwIjoxNzE1MzUxNDMwLCJqdGkiOiIxNzE1MzI5ODMwIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwic3ViIjoiUEdHTVJaNzBEMDFEOTY5T15eXlx1MDAyNjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMlx1MDAyNklTTyJ9.YyBaYW1nJcVstLzCZzOykyin06VNYndyryZ05tfE7_awaDPY-ATRW5_bIBA5j9PanR3rruIvIloPL-4S-d-N1IgLGVnRqkVObSvSUrGUZ5S5Iq4r9DUTraJb33G7g0Fkas3qwLaTSyO4KUiCOpyxwoUFKvZlsAPXUTLC63MTized5kMEnbXVPIA5BkLYp_yyHjmRfDp09S-pfgBvZCXTyMPXtt0DFJagw1gBN83GNiyTC52uZbiAIxIpczlN5qiJ-OvuDiyC4dcjUIxH1f0neoKCn7vSF3V3o5_pScAhC5T3Jpit01tED_IrtxqA0PeehpBBRvAqtIeU06h4Hu6ptw
 
Payload:
{
  "iss": "auth:S1#111#MEDIMATICX1",
  "iat": 1715329830,
  "exp": 1715351430,
  "jti": "1715329830",
  "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
  "sub": "PGGMRZ70D01D969O^^^&2.16.840.1.113883.2.9.4.3.2&ISO"
}
 
FSE-JWT-Signature:
 
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNsaWVudDExIiwieDVjIjpbIk1JSUZhekNDQTFPZ0F3SUJBZ0lVSGJ6dkNNTjBxcjRBWmVvT2FEdXJVNmZ3cVowd0RRWUpLb1pJaHZjTkFRRUxCUUF3VnpFbk1DVUdBMVVFQXd3ZVEwRWdUV2x1YVhOMFpYSnZJR1JsYkd4aElGTmhiSFYwWlNCVVpYTjBNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1Rc3dDUVlEVlFRR0V3SkpWREFlRncweU5EQTFNRE14TkRRek1ERmFGdzB5TnpBMU1EUXhORFF6TURCYU1Hd3hDekFKQmdOVkJBWVRBa2xVTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUjh3SFFZRFZRUmhEQlpEUmpwSlZDMVFVazlXUVZnd01GZ3dNRmd3TURCWk1Sc3dHUVlEVlFRRERCSlRNU014TVRFalRVVkVTVTFCVkVsRFdERXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDY2Jmbkh3b1gxL3c0N0pcdTAwMkJuaWJDTGhpMGpDcEFWdTFIcE1hbE9uM3BaeDMxY3U0NWg1OWg3YkFPUTdUTVQzUmc0bjBUd1gzMXRUeHZNMDdkV01ZVXNJV0ZtTlg1NXZMTXRram1Lc0RTT0djVk5rNVhqbUtKV05TazZsMDJBR0xnWm15Nmk5Zzh1aWVqYk9RN2VLemVTVThnemFXRDVWTGpYWnZLblNkUGJhejBjSFExZTZtaU1mdUVCL1Vmd3pHQzhESGZKS3JoeENzS2VoQmJteE9temUwb3hjbVRka1pPcHhlclpPbWVaTmxsWDBNWlBpaDR5NEdxTHBRXHUwMDJCQWRLS3pVS0lOLzVxVEp6QzNIdldEY1ZCQlNSRnlrUW1QSHRlcUVnbDZWa09GUXo1RkM1ZW1Wb0Z3YXNRQVBickRzWTlBVDNqYk5hMVdPMklFd2RJZ1FaZ0hWQWdNQkFBR2pnZ0VZTUlJQkZEQWZCZ05WSFNNRUdEQVdnQlFXT2FrYUJZbTNEeTJ5TmUzQ0NackZBNE1pUHpBU0JnTlZIU0FFQ3pBSk1BY0dCU3RNSFFFTE1JR3RCZ05WSFI4RWdhVXdnYUl3Z1pcdTAwMkJnZ1p5Z2dabUdnWlpvZEhSd2N6b3ZMMk5oYzI5blpXbHpkbWxzTG5OdloyVnBMbWwwTDJWcVltTmhMM0IxWW14cFkzZGxZaTkzWldKa2FYTjBMMk5sY25Sa2FYTjBQMk50WkQxamNtd21hWE56ZFdWeVBVTk9KVE5FUTBFclRXbHVhWE4wWlhKdksyUmxiR3hoSzFOaGJIVjBaU3RVWlhOMEpUSkRUeVV6UkUxcGJtbHpkR1Z5Ynl0a1pXeHNZU3RUWVd4MWRHVWxNa05ESlRORVNWUXdIUVlEVlIwT0JCWUVGSEcwYmQ2R05mODJzdGV3OXlmaDNZalVCYmpMTUE0R0ExVWREd0VCL3dRRUF3SUdRREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBaENLUVkxSUYzRDJmbENTd3VoM0c3TDV6cXlENHUxcWQ3OXVoSDV4NlFPaVBiZThOcExKdFx1MDAyQlBDSGYwRUdBRFFSL21ZMjVRdlZiUzRMdjFCaC9aXHUwMDJCalJxMUIyeGtrd012NDNDZzFuRm5KUWFRMGJyM0RwY0Zyb1JDbFNyd25kODVubm1HRURQL0poYnJuYjh4MkhwbTlESk5BXHUwMDJCZGtFbkxyL085ZXF1NXJiSjNTWWo4Yk9hSXpjWFJKQzA4ZlA1Ni9PT1FxQzV6b1BzbjZLXHUwMDJCMWxxd1FJV1FnV05kU20vQWFNQ09JVWdHRmxRTFJZZG9ld0JiY2VySG0wVldwSFdiN1RkbVdKdFh1MktVQTRXdGMva05LT2RUcUNza1c0ZkU1c2U5OWRjWWllZkM4TU9CZEwvVThKejlrbFU3dnZ6QWV0UDBrZkdDanZVVC9qUFh5aWF0bzlnekhORTkwSkhFZVF4eWQ4QXo2UzNhallzc2ZZMnMyS0lhbFgya2tyR1FHS1VmWUYxbVBtVVBORFFYSFFtUzBCNGp4YzdqaGtaVEcxQlYvRU9HbHJcdTAwMkJsMWpnYXFVNng5UXVsVmY2WHpNaVZBMTBaMndKYjdwN0wzVU9ZZ0RmUlx1MDAyQjB0dFx1MDAyQkcvRlpkWUpzRUNuY3lLNVx1MDAyQng2Q3o2dG1DZ2U3eE5HUjA5VVd2cFpZMmVKT0JITlk4RTNIaDVFa0NMaVp2UzJ5Y0p6MnAxcDlNdm1Lb05Wem5VbW5vbXpPRWdqblx1MDAyQkJYWGpCL0FQYjY5Y2I0SUhadkR4cjR3UGRnQ3ZQZmhDRXVCbTZxTEcxN0tuTkhWNVgxajNqUUtMTEh0VGh4dUlMbHkvNnJJMmtsOVhOSWhFTVBuRGhoM1h2WXNvUkpRaFIyd2RTRHZtWDUweERBbmxTOC9BQUdsTGc9Il19.eyJpc3MiOiJpbnRlZ3JpdHk6UzEjMTExI01FRElNQVRJQ1gxIiwiaWF0IjoxNzE1MzI5ODMwLCJleHAiOjE3MTUzNTE0MzAsImp0aSI6IjE3MTUzMjk4MzAiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJzdWIiOiJQR0dNUlo3MEQwMUQ5NjlPXl5eXHUwMDI2Mi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yXHUwMDI2SVNPIiwic3ViamVjdF9vcmdhbml6YXRpb25faWQiOiIwNTAiLCJzdWJqZWN0X29yZ2FuaXphdGlvbiI6IlJlZ2lvbmUgVmVuZXRvIiwibG9jYWxpdHkiOiI1MDUwODU3ODIiLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwZXJzb25faWQiOiJUTlRUS1Q0N00xMUE2MzdWXl5eXHUwMDI2Mi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yXHUwMDI2SVNPIiwicGF0aWVudF9jb25zZW50Ijp0cnVlLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImFjdGlvbl9pZCI6IkNSRUFURSIsInJlc291cmNlX2hsN190eXBlIjoiKFx1MDAyNzExNDg4LTReXjIuMTYuODQwLjEuMTEzODgzLjYuMVx1MDAyNykiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiQ09NUEFDUyIsInN1YmplY3RfYXBwbGljYXRpb25fdmVuZG9yIjoiTUVESU1BVElDIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZXJzaW9uIjoiVi40LjIuMCJ9.dSWpWG5Q9pemy2NqpVBvuVPwD_7blQpdD2m5_i-0H5wQWgrb6pqrbqa3-oKyGEbCXEg0BE7XGuVklPSxRFwJA7CnWeAnfEjf2oX34rLlxIyNWeo9PaC7-kJJFrvZdkWzpkQJRqwyQsheVnIGG2sf7QRn-GzqpnilVKZ84difGXkR8iC90hNp6YtMw1YI-AfSaXyp0YTJsHfGlUy3KESX-2pcXlmVA7W2B6KZAgMiSUkIs_Fc4SNA9D3e1hHESKncmXZ_4TD8AOQm_fyhONIsshjIhGoML27ccyucckeRkb4zIx5le22U0XOx4RAZz8c1JArw9ThUXowEVTuKi9ZIkA
 
Payload:
 
{
  "iss": "integrity:S1#111#MEDIMATICX1",
  "iat": 1715329830,
  "exp": 1715351430,
  "jti": "1715329830",
  "aud": "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1",
  "sub": "PGGMRZ70D01D969O^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "subject_organization_id": "050",
  "subject_organization": "Regione Veneto",
  "locality": "505085782",
  "subject_role": "AAS",
  "person_id": "TNTTKT47M11A637V^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
  "patient_consent": true,
  "purpose_of_use": "TREATMENT",
  "action_id": "CREATE",
  "resource_hl7_type": "('11488-4^^2.16.840.1.113883.6.1')",
  "subject_application_id": "COMPACS",
  "subject_application_vendor": "MEDIMATIC",
  "subject_application_version": "V.4.2.0"
}

**Comment by vigliottim** [comment]
Buonasera, dalle verifiche effettuate sembra esserci un problema di parsing del campo _x5c_:
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/d3d7782f-458d-476d-91d0-318bf460b158)
Può confermarci che sta usando il tool [jwt-generator](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator) per la generazione dei token? Grazie.
