### ISSUE TITLE
Informazione su segnalazione mancato accreditamento.

### ISSUE THREAD

**Issue by mariogoodbread** [ministero-salute/it-fse-support#828]
Buongiorno,
chiedo scusa se apro una segnalazione per una semplice domanda ma non saprei dove altro farla e a chi rivolgerla.
Ho ricevuto la seguente email:

_Salve,
Con la presente si comunica il mancato superamento dei seguenti test [369] per il servizio [validazione/pubblicazione] del Fornitore [A1#111#NISATEKXX] - Vendor:[nisatek] - ID: [adtweb] - Version: [2.0] - Sha: [3ece2568947fa67a756dde1f1de68f1f0fe66694] in data odierna._

Volevo sapere se il test 369 che mi è stato segnalato è l'unico errato o è il primo per il quale avete riscontrato un errore.

Nel secondo caso, sarei preoccupato per le tempistiche necessarie per ottenere l'accreditamento, soprattutto considerando che, fino ad ora, sembra che le mie richieste di merge siano elaborate solo dopo le 18:00.

Vi prego di considerare la mia richiesta come una semplice domanda e non come un'osservazione polemica.

Cordiali Saluti
M.

**Comment by LucaRogledi** [comment]
Buongiorno,
Il messaggio ricevuto via email contenente l'esito delle verifiche, indica che è stato riscontrato un solo errore sul test 369, mentre gli altri test risultano eseguiti correttamente. Restiamo a disposizione per chiarimenti.
Grazie.

**Comment by mariogoodbread** [comment]
Vi ringrazo per la codiale risposta.
