### ISSUE TITLE
Correzione eseguita del file report-checklist.xlsx 

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#829]
Buongiorno, solo per segnalare che è stato aggiornato il file come richiesto, ma non è stata effettuata una nuova pull request perchè l'originale è ancora aperta: 
https://github.com/ministero-salute/it-fse-accreditamento/pull/1401
Volevamo giusto una conferma di aver seguito la procedura corretta.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, le confermiamo che ha seguito la procedura corretta. 
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
