### ISSUE TITLE
Cortese richiesta di elaborare una request pull

### ISSUE THREAD

**Issue by mariogoodbread** [ministero-salute/it-fse-support#831]
Buonasera, ho appena creato una fix ed inserito una pull request per la seguente segnalazione:

Salve,
Con la presente si comunica il mancato superamento dei seguenti test [369] per il servizio [validazione/pubblicazione] del Fornitore [A1#111#NISATEKXX] - Vendor:[nisatek] - ID: [adtweb] - Version: [2.0] - Sha: [fc59616aadc888cd1df6ab04ae72f04db9a02a69] in data odierna.

Cortesemente potreste elaborarla questa sera?

Cordiali Saluti
M.

**Comment by IStacchiotti** [comment]
Buonasera, le confermiamo che sono state eseguite nuovamente le verifiche automatiche. Riceverà l'esito delle elaborazioni via email.

**Comment by mariogoodbread** [comment]
Buonasera, scusate ho effettuato una nuova pull request....
