### ISSUE TITLE
Richiesta informazioni su mancato accreditamento

### ISSUE THREAD

**Issue by mariogoodbread** [ministero-salute/it-fse-support#832]
Buonasera,
purtroppo non riesco a capire quale sia il problema per la seguente segnalazione di errore:

Con la presente si comunica il mancato superamento dei seguenti test [369] per il servizio [validazione/pubblicazione] del Fornitore [A1#111#NISATEKXX] - Vendor:[nisatek] - ID: [adtweb] - Version: [2.0] - Sha: [5095852b812e78ec98e3794f071b59195597c8a2] in data odierna.

Il file errors.json contiene il seguente messaggio:
[ {
  "id" : 369,
  "error" : "WII_UNKNOWN_TRANSACTION",
  "description" : "WorkflowInstanceID non presente nella collection delle transazioni.Assicurarsi di aver eseguito correttamente la validazione/pubblicazione per il wii segnalato"
} ]

Se ho comunicato bene il WorkflowInstanceID, questi dovrebbe essere: 2.16.840.1.113883.2.9.2.120.4.4.3c6eab64bea8c0b7b46060a335ab16cc930f78a6f183dd47d56870c35b6e6c02.5948e52ba5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId.

La risposta alla richiesta di validazione è la seguente:

{
      "traceID": "7b4688253f3e46fc",
      "spanID": "7b4688253f3e46fc",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.3c6eab64bea8c0b7b46060a335ab16cc930f78a6f183dd47d56870c35b6e6c02.5948e52ba5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "warning": "[SIGN_WARN - Attenzione il documento risulta firmato in validazione]"
    }

se richiedo la getStatus ottengo le seguenti informazioni:

{
    "traceID": "21da01e774889664",
    "spanID": "78c60163f6eb2a10",
    "transactionData": [
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-05-13T08:06:50.822+00:00",
            "eventStatus": "SUCCESS",
            "message": "Regime di mock abilitato",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.3c6eab64bea8c0b7b46060a335ab16cc930f78a6f183dd47d56870c35b6e6c02.5948e52ba5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-05-13T08:06:50.832+00:00"
        },
        {
            "eventType": "SEND_TO_EDS",
            "eventDate": "2024-05-13T08:06:50.966+00:00",
            "eventStatus": "SUCCESS",
            "message": "{\"esito\":true}",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.3c6eab64bea8c0b7b46060a335ab16cc930f78a6f183dd47d56870c35b6e6c02.5948e52ba5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-05-13T08:06:50.974+00:00"
        },
        {
            "eventType": "EDS_WORKFLOW",
            "eventDate": "2024-05-13T09:00:00.044+00:00",
            "eventStatus": "SUCCESS",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.3c6eab64bea8c0b7b46060a335ab16cc930f78a6f183dd47d56870c35b6e6c02.5948e52ba5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-05-13T09:00:00.069+00:00"
        }
    ]
}

Potreste aiutarmi a capire dove è il problema cortesemente?

Grazie
M.

**Comment by vigliottim** [comment]
Buongiorno, 
l'errore ricevuto dovrebbe essere stato causato da un'anomalia ora risolta. 
La invitiamo ad effettuare una nuova pull request. In particolare, per il test case con id = 369 dovrà effettuare una nuova chiamata e inserire il relativo workflowInstanceID.
Grazie.

**Comment by mariogoodbread** [comment]
Buongiorno,
ho inserito un nuova pull request come richiesto.

Grazie
M.
________________________________

**Comment by vigliottim** [comment]
Grazie per il suo gentile feedback.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
