### ISSUE TITLE
Crash Program - Sprint 5 - RDE FVG, RDA Campania - UC8_EliminazioneDocumento: 500 Ini Error

### ISSUE THREAD

**Issue by ChiaraCeccottiFVG** [ministero-salute/it-fse-support#833]
Buongiorno,
Per lo sprint 5 RDE FVG e RDA regione Campania abbiamo eseguito il test UC8_EliminazioneDocumento ma otteniamo il seguente errore:

```
{
    "traceID": "b8b4e90ba21b6c17",
    "spanID": "b8b4e90ba21b6c17",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "status": 500,
    "detail": "{\"traceID\":\"0000000000000000b8b4e90ba21b6c17\",\"spanID\":\"fa7db9281d81d741\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: javax.transaction.TransactionRolledbackException:  ; nested exception is: \\n\\tjavax.transaction.SystemException Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}",
    "instance": "/msg/service-error/ini",
    "classError": "it.insiel.sanita.fse2.invoker.adapter.rest.gateway.exception.GatewayException"
}
```
ID Documento: 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715673453754
CF anagrafica: PRVPRV12T12L424X

Vi chiediamo una verifica per aiutarci a capire il problema.
Ringraziando molto per la collaborazione auguriamo una buona giornata.

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
a seguito della vostra cortese risposta alla issue 801 dove ci avete chiesto di riprovare lo use case dopo la correzione eseguita confermiamo che siamo riusciti a cancellare con successo un documento di tipo LDO verso la Campania (ID: 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1716472302002).
Questa issue quindi può essere chiusa.
Ringraziamo molto e auguriamo un buon pomeriggio.

**Comment by LucaRogledi** [comment]
Buon pomeriggio, ringraziamo per il feedback e procediamo alla chiusura della issue.
Restiamo a disposizione in caso fosse necessario ulteriore supporto.
Grazie
