### ISSUE TITLE
Errore 404 in sostituzione

### ISSUE THREAD

**Issue by nspazzoli** [ministero-salute/it-fse-support#834]
Buongiorno,

sto provando a sostituire un documento precedentemente indicizzato, ma ottengo un 404 alla chiamata REPLACE

- Documento creato  Id= 105LAB17156747979537A6PVE, workflowInstantID= 2.16.840.1.113883.2.9.2.80.3.1.4.4.dd3bf5653f9416df002cc14c7256af2d1c6e18497fe39e89eb3ee3436b846796.14bcaca1cc^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

e per qeusto documento, la QRY per workflow resituisce:
```
HTTP 200, 
 {"traceID":"919abee03c40e71b","spanID":"780a39fa81548130","transactionData":[{"eventType":"SEND_TO_INI","eventDate":"2024-05-14T08:20:08.383+00:00","eventStatus":"SUCCESS","workflowInstanceId":"2.16.840.1.113883.2.9.2.80.3.1.4.4.dd3bf5653f9416df002cc14c7256af2d1c6e18497fe39e89eb3ee3436b846796.14bcaca1cc^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","expiringDate":"2025-05-14T08:20:08.395+00:00"},{"eventType":"SEND_TO_EDS","eventDate":"2024-05-14T08:20:08.543+00:00","eventStatus":"SUCCESS","message":"{\"esito\":true}","workflowInstanceId":"2.16.840.1.113883.2.9.2.80.3.1.4.4.dd3bf5653f9416df002cc14c7256af2d1c6e18497fe39e89eb3ee3436b846796.14bcaca1cc^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","expiringDate":"2025-05-14T08:20:08.564+00:00"}]} 
```

- Sostituto id = 105LAB1715674829447WT58ZQ, workflowInstanceID = 2.16.840.1.113883.2.9.2.80.3.1.4.4.745be54f2d4ba1ab812af9b2a76878c6ee8f2ba51abfb28ecc8038bda4775b7d.dd939b1e0d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

chiamata di sostituzione 
`PUT /govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.80.4.4%5E105LAB17156747979537A6PVE HTTP/1.1`
per la quale ottengo 
```
HTTP 404, 
 {"traceID":"f63b85369bd9e7e9","spanID":"f63b85369bd9e7e9","type":"/msg/record-not-found","title":"Record non trovato.","detail":"No Record Found","instance":"/record-not-found"} 

```

Potreste darci qualche indicazione in merito?
Grazie

**Comment by vigliottim** [comment]
Buongiorno, le chiediamo gentilmente di riprovare. Rimaniamo a disposizione nel caso in cui l'errore dovesse ripresentarsi. Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue. 
Sarà possibile riaprirla nel caso in cui avesse bisogno di ulteriore supporto. Grazie.
