### ISSUE TITLE
CRASH PROGRAM Aggiornamento metadati RDA Emilia-Romagna

### ISSUE THREAD

**Issue by daniele-gubellini** [ministero-salute/it-fse-support#835]
Segnalo che tutti gli aggiornamenti metadati che riceviamo come RDA Emilia-Romagna vengono scartati per la mancanza di alcuni campi nel  RegistryPackage: authorRole, authorInstitution e authorPerson.

**Comment by vigliottim** [comment]
Buonasera, le chiediamo gentilmente di riprovare e informarci qualora il problema persista. 
Grazie.

**Comment by daniele-gubellini** [comment]
Lo specifica anomalia è stata risolta. 
Il nostro servizio restituisce sempre un errore in quanto riteniamo il messaggio comunque non aderente alle specifiche (segnalazione #761 )

**Comment by vigliottim** [comment]
Grazie per il suo gentile feedback. La invitiamo a seguire il thread #761 per aggiornamenti in merito all'errore ricevuto.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
