### ISSUE TITLE
Crash Program - Sprint 5 - RDE FVG - RDA Campania - UC6_SostituzioneDocumento, UC12_ValidazionePubblicazioneSostituzioneContestuale: Errore 404 record-not-found

### ISSUE THREAD

**Issue by ChiaraCeccottiFVG** [ministero-salute/it-fse-support#836]
Buongiorno,
Stiamo testando gli use case UC6_SostituzioneDocumento e UC12_ValidazionePubblicazioneSostituzioneContestuale per lo sprint 5 con regione FVG come RDE e Regione Campania come RDA.
Otteniamo l'errore 404 - record-not-found

Riportiamo un esempio per uno dei test eseguiti:
ID documento: 2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715677693212_NEW che sostituisce il documento
2.16.840.1.113883.2.9.2.60.4.4^CRASH_TEST_LDO1715677693212
CF: PRVPRV12T12L424X

```
"responseBody": "{\"traceID\":\"ad59bba23b6896d2\",\"spanID\":\"ad59bba23b6896d2\",\"type\":\"/msg/record-not-found\",\"title\":\"Record non trovato.\",\"detail\":\"No Record Found\",\"instance\":\"/record-not-found\"}",
  "responseHeaders": {
    "Transfer-Encoding": "[chunked]",
    "GovWay-Transaction-ID": "[2fe60c47-11d0-11ef-93a7-005056ae54fa]",
    "Server": "[GovWay-SOGEI]",
    "X-Content-Type-Options": "[nosniff]",
    "X-Backside-Transport": "[FAIL FAIL]",
    "Connection": "[Keep-Alive]",
    "Pragma": "[no-cache]",
    "X-Global-Transaction-ID": "[3f7e3e2d66432a3f23cd592d]",
    "Date": "[Tue, 14 May 2024 09:09:25 GMT]",
    "Cache-Control": "[no-cache, no-store, must-revalidate]",
    "GovWay-Message-ID": "[0c288b37-17e5-4cb1-8801-2ca67b6f46ab]",
    "content-disposition": "[inline;filename=f.txt]",
    "Vary": "[*]",
    "Expires": "[0]",
    "server-timing": "[intid;desc=04882fa3131be043]",
    "Content-Type": "[application/problem+json]"
  },
  "uuid": "ad6a7d93758d4e559cc9510e580310a3",
  "dataInserimento": {
    "$date": "2024-05-14T09:09:25.224Z"
  }
```

Segnaliamo che da lo stesso errore anche per lo sprint4 - RDE FVG e RDA Lombardia per il quale venerdì 10/05 segnalava success.
Vi chiederemmo cortesemente se potreste verificare anche lato vostro per aiutarci a capire il problema.
Grazie e buona giornata.

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno, 
volevamo avvisare che riprovando i test oggi per gli use case Sprint 5 - RDE FVG - RDA Campania:
UC6_SostituzioneDocumento e UC12_ValidazionePubblicazioneSostituzioneContestuale
il problema segnalato risulta risolto e la replace avviene con successo.
Grazie e buona giornata.

**Comment by vigliottim** [comment]
Grazie per il suo gentile feedback. 
Procediamo alla chiusura della presente issue che potrà riaprire nel caso in cui il problema dovesse ripresentarsi.
