### ISSUE TITLE
Accreditamento FSE per referto RSA

### ISSUE THREAD

**Issue by rondellimediam** [ministero-salute/it-fse-support#839]
Buongiorno,
dopo aver terminato la fase di validazione del referto con CDA innestato, ci stiamo occupando di quella di accreditamento.
Nello specifico, dobbiamo accreditare un'applicazione che si occupa di nutrizione in ambito ospedaliero e che produce un referto di tipo RSA. Inoltre il nostro scopo è quello di ottenere l'accreditamento per la validazione e non la pubblicazione.
Abbiamo studiato la documentazione da produrre, ma avremmo una serie di dubbi da risolvere, facendo riferimento al file "casi di test RSA" (che alleghiamo), avremmo bisogno di risolvere i seguenti dubbi:

Caso test 2
perché dobbiamo occuparci di “test da sforzo – cicloergometro e nella misurazione della pressione arteriosa ogni due minuti durante l’esecuzione” se il nostro referto riguarderà la nutrizione clinica? Non abbiamo questi dati

Caso test 3
perché dobbiamo occuparci di “test di ginecologia colposcopia ovvero un esame ginecologico diagnostico di secondo livello che studia le cellule della cervice uterina” se il nostro referto riguarderà la nutrizione clinica? Non abbiamo questi dati

Caso test 7
non capiamo se il livello di riservatezza deve mancare (come espresso nel file excel CDA2_Referto_Specialistica_Ambulatoriale_KO) o se deve essere valorizzato come “Restricted”

Casi test 11, 17, 18, 19, 20, 21
Riguardano sezioni non obbligatorie. Bisogna comunque produrre ti test?

Grazie per l'attenzione!

[casi di test RSA.docx](https://github.com/ministero-salute/it-fse-support/files/15319370/casi.di.test.RSA.docx)
[CDA2_Referto_Specialistica_Ambulatoriale_KO.xlsx](https://github.com/ministero-salute/it-fse-support/files/15319371/CDA2_Referto_Specialistica_Ambulatoriale_KO.xlsx)

**Comment by LucaRogledi** [comment]
Buongiorno,

- riguardo ai caso di test 2,3: Se il vostro applicativo non gestisce le informazioni necessarie per completare il test case secondo le indicazioni riportate nel file excel, è possibile dichiararlo "non applicabile" nella checklist richiesta per l'accreditamento (sarà sufficiente indicare "NO" nell’apposita colonna "applicabilità", giustificandolo opportunamente nella colonna "razionale di applicabilità").

- riguardo al caso di test 7: Per ottenere l'errore semantico atteso dal caso di test 7, dovrebbe valorizzare l'attributo confidentialityCode/@code con un codice di riservatezza moderatamente sensibile ("Restricted") quindi "R".

- riguardo ai casi di test 11, 17, 18, 19, 20, 21: I casi di test specificati riguardano casi di test KO che introducono volutamente degli errori in compilazione e verificano che si ricevano specifici messaggi di errore in output. Specifichiamo che bisogna inserire tutti gli elementi che, anche se sono opzionali da guida, per il nostro caso d’uso sono necessari per completezza di informazione. Bisogna fare riferimento all’excel fornito ( [CDA2_Referto_Specialistica_Ambulatoriale_KO.xlsx](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/7-Referto%20Specialistico%20Ambulatoriale/CDA2_Referto_Specialistica_Ambulatoriale_KO.xlsx) ) con le giuste valorizzazioni dei campi da inserire. Nel caso particolare in cui i dati non siano disponibili a sistema oppure nel caso in cui non si possa completare il test case correttamente, è possibile indicare NO nell’apposita colonna "Applicabilità", avendo cura di giustificarlo opportunamente nella colonna "razionale di applicabilità".

Le segnaliamo infine che è disponibile il tool [gwt-certifier](https://github.com/ministero-salute/it-fse-gtw-tools), che consente di riprodurre in locale le verifiche dei test case di validazione OK richiesti durante la fase di accreditamento.
Rimaniamo a disposizione per ulteriore supporto, grazie

**Comment by rondellimediam** [comment]
Grazie per i chiarimenti!

**Comment by vigliottim** [comment]
Grazie a lei per il suo gentile feedback.
Chiudiamo il presente ticket e rimaniamo a disposizione nel caso in cui abbia bisogno di ulteriore supporto.

**Comment by rondellimediam** [comment]
Buongiorno, riapro la segnalazione per risolvere un paio di dubbi:

1) I test case di validazione dovranno essere inviati singolarmente con le stesse modalità utilizzate in fase di validazione del referto con CDA allegato? (e cioè: https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#3-servizio-di-validazione)

2) Non c'è una via che permetta solo di inviare i soli CDA senza token e referto pdf?

Grazie!

**Comment by vigliottim** [comment]
Buongiorno, 
per informazioni sul processo di accreditamento, che segue una specifica procedura, la invitiamo a consultare i seguenti link:

- Informazioni sul processo di accreditamento: https://github.com/ministero-salute/it-fse-support/tree/main/doc/accreditamento#fase-1-processo-di-accreditamento 

- Procedura di caricamento dei risultati: https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#procedura-di-caricamento-dei-risultati

Inoltre, la informiamo che i test case non possono essere inviati singolarmente ma vanno inseriti nel _data.json_ e nella _checklist_, associando le informazioni richieste, e che non è possibile inviare i soli CDA senza iniettarli in un pdf.
Restiamo a disposizione per ulteriori dubbi.

**Comment by rondellimediam** [comment]
Buongiorno, credo di essermi spiegato male. Mi è chiara la procedura di caricamento dei dati. Ma prima di caricare i dati, dobbiamo comunque eseguire i test di validazione (a noi interessa la sola validazione), corretto? 
Faccio riferimento a questo punto della procedura di accreditamento:
**Il fornitore accede alla lista dei test case ed esegue i test previsti nel piano di accreditamento.** 
Per eseguire i test case utilizziamo le stesse modalità usate per la validazione del CDA, giusto? (allego comando invio curl usato in fase di validazione come esempio).
[test invio curl.txt](https://github.com/ministero-salute/it-fse-support/files/15402297/test.invio.curl.txt)

Altrimenti non saremmo in grado di fornire alcuni dati che ci vengono restituiti dal gateway, quali "traceId" e "workflowInstanceId" e che dobbiamo poi inserire nel data.json.

Grazie per l'attenzione!

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Confermiamo che per eseguire i test può effettuare le validazioni con il comando da lei allegato, avendo cura di apportare le modifiche richieste a seconda del test case svolto.
Restiamo a disposizione per eventuali chiarimenti.
Grazie

**Comment by rondellimediam** [comment]
Grazie per la risposta, ma ho ancora il dubbio. Cerco di fare un esempio: 
**test case 20** "Durante la fase di compilazione dell’allergia contenuta nella sezione “Storia Clinica”, viene generato un errore semantico dovuto all’assenza della specifica riguardante l’intervallo di tempo in cui l’allergia o intolleranza è attiva (observation/effectiveTime).", quindi per forza questa sezione deve esserci, anche se non è obbligatoria. Ma un'altra sezione non obbligatoria, tipo "Terapia Farmacologica in atto", deve comunque esserci per lo stesso test case? 
Le faccio la domanda perchè per alcune delle sezioni non obbligatorie non ho modo di recuperare dei dati e quindi mi chiedevo se potevo ometterle, se non strettamente necessarie ai fini del test. Grazie!

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
come riportato nell'[excel dei requisiti](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/7-Referto%20Specialistico%20Ambulatoriale/CDA2_Referto_Specialistica_Ambulatoriale_KO.xlsx) per lo svolgimento del test case 20 tra i casi di test KO è necessario seguire le indicazioni riportate nella colonna "Note" non valorizzando l'intera sezione effectiveTime evidenziata di seguito, che risulta obbligatoria, con lo scopo di ottenere l'errore semantico atteso e descritto nel file [casi di test RSA.docx](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/7-Referto%20Specialistico%20Ambulatoriale/casi%20di%20test%20RSA.docx).

![image](https://github.com/ministero-salute/it-fse-support/assets/139234602/aebafa94-528c-4320-80e6-f6ba673f977a)
 
Le sezioni opzionali come per esempio quella da lei indicata ("Terapia Farmacologica in atto") non sono necessarie.
La invitiamo comunque a fare attenzione alla colonna "Note" dove può eventualmente essere richiesta la valorizzazione di una sezione opzionale in caso di determinate condizioni.
Grazie

**Comment by rondellimediam** [comment]
Grazie per la risposta!

**Comment by rondellimediam** [comment]
Buongiorno, facendo riferimento all'excel in allegato [accreditamento-checklist_V8.1.3.xlsx](https://github.com/ministero-salute/it-fse-support/files/15467811/accreditamento-checklist_V8.1.3.xlsx) e dovendo produrre dei test di sola validazione per un documento RSA, ho dei dubbi circa i test case seguenti:

- **Id test case 40**: quali e quanti campi errati bisogna inserire nei token?
- **Id test case 48**: il timeout deve essere prodotto nella chiamata di validazione al gateway e devo descrivere come risponde la mia applicazione?
- **Id test case 374:** non mi è chiaro come si debba produrre il test (è un test case OK)

Per sicurezza vi chiedo anche se tutti gli altri test case che mi riguardano, e cioè:
- OK: **147,148,149,150**
- KO: **151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169**
sono quelli descritti nel file: [casi di test RSA](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/7-Referto%20Specialistico%20Ambulatoriale/casi%20di%20test%20RSA.docx)

Grazie per il supporto!

**Comment by vigliottim** [comment]
Buongiorno, rispondiamo in linea alle sue domande:


> - Id test case 40: quali e quanti campi errati bisogna inserire nei token? 

Come suggerito nelle indicazioni corrispondenti al caso di test citato presenti nella colonna "Descrizione" del file excel [accreditamento-checklist_V8.1.3.xlsx](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/accreditamento-checklist_V8.1.3.xlsx), al fine di rendere non valido il token è necessario valorizzare il campo _"action_id"_ con la stringa _"TEST"_ (valore non ammesso).

> - Id test case 48: il timeout deve essere prodotto nella chiamata di validazione al gateway e devo descrivere come risponde la mia applicazione? 

Corretto.

> - Id test case 374: non mi è chiaro come si debba produrre il test (è un test case OK). 

Il caso di test in questione è un _caso di test 0_, sempre applicabile, che prevede la validazione di un CDA2 semplice in cui sono presenti esclusivamente le sezioni e gli elementi obbligatori secondo le specifiche nazionali HL7 Italia.

> - Per sicurezza vi chiedo anche se tutti gli altri test case che mi riguardano, e cioè:
OK: 147,148,149,150
KO: 151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169
sono quelli descritti nel file: [casi di test RSA](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/7-Referto%20Specialistico%20Ambulatoriale/casi%20di%20test%20RSA.docx)

Esatto, può far riferimento al documento al link riportato per maggiori dettagli sull'esecuzione dei casi di test menzionati.


Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by rondellimediam** [comment]
Grazie per la risposta! Quindi l'Id test case 374 corrisponde al CASO DI TEST 0 del file [casi di test RSA](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/7-Referto%20Specialistico%20Ambulatoriale/casi%20di%20test%20RSA.docx) ?

**Comment by vigliottim** [comment]
Esatto, lo può dedurre dal nome dato al caso di test (VALIDAZIONE_CDA2_RSA_**CT0**):

![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/d97ace61-a5b9-4659-91ec-912bc75f26cd)

Rimaniamo a disposizione nel caso avesse altri dubbi. 
Grazie.

**Comment by rondellimediam** [comment]
Grazie!

**Comment by rondellimediam** [comment]
Buongiorno, chiedo scusa ma ho un altro dubbio: secondo l'iter di validazione, la validazione deve avvenire prima della firma digitale. Mi chiedevo quindi se i referti che dovrò inviare nei vari test case dovranno essere firmati comunque o se posso inviare referti non firmati. In particolare, per il CASO DI TEST 23, basta compilare i dati nell'xml del CDA o il referto deve essere firmato? La firma deve essere per forza Pades? Grazie!

**Comment by vigliottim** [comment]
Buongiorno, 
è possibile inviare i referti sia firmati che non firmati. 
La suggeriamo di inviare i referti firmati qualora il software abbia la funzionalità di firma e la firma sia oggetto di adeguamento. 
La informiamo che la firma PaDES può essere applicata al PDF utilizzando il certificato di firma tramite il tool online messo a disposizione [pdf-generator](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/pdf-generator).
Per l'esecuzione del _caso di test 23_, non è necessario che il referto sia firmato. 
Basta valorizzare l’elemento signatureCode con un codice errato (diverso da “S”) per generare l'errore semantico.
Es. `<signatureCode code="X"/>`
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by rondellimediam** [comment]
Grazie per la risposta esauriente! La firma non è oggetto di adeguamento, quindi non manderò i referti firmati, per comodità nella loro creazione.

**Comment by rondellimediam** [comment]
Buongiorno, sto inviando i casi di validazione RSA da produrre per l'accreditamento. Il gateway mi risponde in questo modo:
**{ "type": "https://govway.org/handling-errors/503/GatewayError.html", "title": "GatewayError", "status": 503, "detail": "The gateway is currently unable to handle the response", "X-Global-Transaction-ID": "3f7e3e2d6656e4533327657d" }** 

Mi sapreste dire se al momento c'è un problema di raggiungibilità del gateway per favore? Per completezza allego il comando curl che invio (con password omessa) e il referto. Grazie!
[curl request.txt](https://github.com/ministero-salute/it-fse-support/files/15481148/curl.request.txt)
[Referto_00000054_00.pdf](https://github.com/ministero-salute/it-fse-support/files/15481150/Referto_00000054_00.pdf)

**Comment by vigliottim** [comment]
Al momento stiamo registrando dei temporanei disservizi.
La invitiamo a monitorare il canale Slack per aggiornamenti.
Grazie.

**Comment by rondellimediam** [comment]
Grazie per la pronta risposta!

**Comment by rondellimediam** [comment]
Scusi, mi sa dire dove posso trovare il canale Slack per gli aggiornamenti? Grazie

**Comment by LucaRogledi** [comment]
Salve, riportiamo di seguito il link del canale slack fse:
https://developersitalia.slack.com/archives/C03RDT88FSM

Presente nella sezione "Canali" della seguente pagina [FSE](https://developers.italia.it/it/fse/#resourcecontent-1)
Grazie.

**Comment by rondellimediam** [comment]
Per accedere alla pagina dovrei avere un account sul sito, ma non posso averlo se il mio indirizzo email non appartiene a determinati domini. L'unica altra possibilità è essere invitato. Potreste per favore invitarmi usando il mio indirizzo rondelli@mediam.it ? Grazie!

**Comment by vigliottim** [comment]
Può unirsi al canale cliccando sul seguente link:
https://join.slack.com/t/developersitalia/shared_invite/zt-2k1fbjqpc-y~TABm1dXLSf8oc0DkDQOw

**Comment by rondellimediam** [comment]
Grazie! Ci sono

**Comment by rondellimediam** [comment]
Buongiorno,
avrei alcuni dubbi sulla compilazione dell' excel che riepiloga i test case che invierò in particolare su alcune colonne del foglio "TestCase":

1. Con quale valore devo compilare la colonna Timestamp? Non è già sufficiente la Data di Esecuzione, in cui vengono riportate anche ore, minuti e secondi?
2. Nella colonna "Razionale di applicabilità" indico i motivi per i quali un test case non è applicabile alla nostra realtà?
3. I test case di tipo "KO", se restituiscono l'errore atteso, devono considerarsi con esito "Fail" o "Pass"?

Grazie come sempre per la disponibilità!

**Comment by LucaRogledi** [comment]
Buongiorno, 
Rispondiamo in linea sue domande:

1. > Con quale valore devo compilare la colonna Timestamp? Non è già sufficiente la Data di Esecuzione, in cui vengono riportate anche ore, minuti e secondi?

All'interno della colonna timestamp deve essere inserita la data di esecuzione della chiamata, seguendo il formato: 
`YYYY-MM-DDTHH:mm:ssZ` (es. `2024-05-04T11:43:25Z`)

2. > Nella colonna "Razionale di applicabilità" indico i motivi per i quali un test case non è applicabile alla nostra realtà?

Corretto.

3. > I test case di tipo "KO", se restituiscono l'errore atteso, devono considerarsi con esito "Fail" o "Pass"?

I test case KO che restituiscono l'errore atteso devono essere considerati come test "Pass" eseguiti correttamente.

Restiamo a disposizione per eventuali chiarimenti.
Grazie

**Comment by rondellimediam** [comment]
Grazie!

**Comment by LucaRogledi** [comment]
Ringraziamo per il feedback e procediamo alla chiusura del presente issue.
Restiamo a disposizione in caso fosse necessario ulteriore supporto.
Grazie.

**Comment by rondellimediam** [comment]
Buongiorno, sto preparando il file data.json da inviare per l'accreditamento. E' corretto non inserire nulla per i casi con id 148 e 149 (non applicabili) e con id 48 (caso di timeout, autocertificato)? Per questi casi non invierò neppure i file .pdf. Grazie per l'assistenza!

**Comment by vigliottim** [comment]
Buongiorno,
se un caso di test viene dichiarato _"non applicabile"_ nella checklist richiesta per l'accreditamento, dovrà indicare _"NO"_ nell’apposita colonna _"Applicabilità"_ e giustificare tale scelta nella colonna _"Razionale di applicabilità"_. 
Le confermiamo che non dovranno essere inserite informazioni ad essi relative nel file _data.json_.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by rondellimediam** [comment]
Grazie!
Chiedo anche una cosa circa la pull request: è possibile farla attraverso github? a quale indirizzo? grazie per l'attenzione

**Comment by LucaRogledi** [comment]
Buongiorno,
Si, dopo aver effettuato il fork del [repository di accreditamento](https://github.com/ministero-salute/it-fse-accreditamento) è possibile procedere con l'apertura della pull request seguendo le indicazioni riportate in [documentazione](
https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#procedura-di-caricamento-dei-risultati
). Restiamo a disposizione per eventuali chiarimenti. 
Grazie

**Comment by rondellimediam** [comment]
Buongiorno,
vi scrivo nuovamente perchè in fase di accreditamento mi vengono notificati gli errori in allegato 
[errors case150 2.json](https://github.com/user-attachments/files/15756810/errors.case150.2.json)

Allego il referto con il CDA allegato che invio 
[Referto_00000054_04.pdf](https://github.com/user-attachments/files/15756813/Referto_00000054_04.pdf)

Avrei un paio di domande:

1. Primo errore riportato: devo sostituire "Età diagnosi patologia" con "Età diagnosi patologia Età_decesso" alla riga 421? E come mi comporto alla riga 433? Cosa dovrei mettere, visto che viene indicata l'effettiva data del decesso?
2. Va bene se sostituisco, in fase di costruzione dell'xml, il carattere à con &#224; ? Non riesco a trovare altro modo, ma sembra non vada bene

Grazie per l'attenzione!

**Comment by vigliottim** [comment]
Buongiorno,
gli errori ricevuti sono dovuti all'errata valorizzazione degli attributi _displayName_ indicati.
Le chiediamo di correggerli come segue:
~~displayName="Et? diagnosi patologia"~~ _displayName="Età diagnosi patologia"_
~~displayName="Obiettivit? Clinica Clinical Finding Criticality Stato"~~ _displayName="Obiettività Clinica Clinical Finding Criticality Stato"_					
e riprovare.
Grazie.

**Comment by rondellimediam** [comment]
Grazie per la risposta. Ma continuo a non riuscire a trovare il giusto modo per fare l'encode della à. Ho provato con 
![image](https://github.com/ministero-salute/it-fse-support/assets/159120408/ffdb4426-149b-4d81-a287-8707be4e7ea3)
 o anche con ![image](https://github.com/ministero-salute/it-fse-support/assets/159120408/949fc9d4-1252-4925-8451-d959ce25be12) ma senza ottenere la conversione adeguata. Mi sapreste per favore dare un suggerimento?

**Comment by rondellimediam** [comment]
Grazie! credo di aver risolto

**Comment by vigliottim** [comment]
Grazie a lei per il gentile feedback.
Procediamo alla chiusura del presente ticket e rimaniamo a disposizione per altre richieste di supporto.

**Comment by rondellimediam** [comment]
Buongiorno, 
 in fase di accreditamento mi viene notificato l'errore in allegato. 
[errors.json](https://github.com/user-attachments/files/15798715/errors.json)

Non riesco a capire dove sia l'errore, i due testi mi sembrano uguale. Allego anche il referto con CDA che ho inviato 
[Referto_00000054_04.pdf](https://github.com/user-attachments/files/15798729/Referto_00000054_04.pdf)

Per favore mi aiutate a capire l'errore?

**Comment by vigliottim** [comment]
Buongiorno,
l'errore ricevuto potrebbe essere causato al fatto che l'elemento _displayName="Obiettività Clinica Clinical Finding Criticality Stato"_ non è stato valorizzato correttamente. 
Esso deve essere coerente al tag _code_ associato (_code="75321-0"_), pertanto dovrà modificarlo come segue:
_displayName="Obiettività Clinica"_
Rimaniamo a disposizione per ulteriori dubbi.

**Comment by rondellimediam** [comment]
Grazie, provo in quel modo

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione nel caso in cui avesse bisogno di ulteriore supporto.
Grazie.
