### ISSUE TITLE
Errore InteroperabilityInvalidRequest (400) validazione CDA

### ISSUE THREAD

**Issue by mtorromacco** [ministero-salute/it-fse-support#840]
Salve,
Stiamo cercando di effettuare dei test per la validazione di un referto con CDA ma riceviamo sempre un errore **400** di tipo **InteroperabilityInvalidRequest**.

```
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "6aaa975f-12b5-11ef-bebd-005056ae7395"
}
```

Potreste gentilmente eseguire un controllo più dettagliato e comunicarci quale sia il problema?
Grazie mille.

**Comment by vigliottim** [comment]
Buon pomeriggio,
dalle verifiche effettuate è emerso che sta usando un token non utilizzabile prima della data e orario indicati nel seguente messaggio di errore:
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/f407ed5a-da96-4f40-943d-efc7b8c079d8)
La preghiamo di controllare il periodo di validità del token e riprovare.
Grazie.

**Comment by mtorromacco** [comment]
Abbiamo risolto andando ad agire sulla validità del token, grazie mille per il supporto!
