### ISSUE TITLE
Error 403 validation

### ISSUE THREAD

**Issue by euritech** [ministero-salute/it-fse-support#841]
Buonasera,
stiamo effettuando dei test di validazione, ma stiamo riscontrando il seguente errore:
{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"a039e272-12c5-11ef-bebd-005056ae7395"}
Potreste darci maggiori informazioni?
Grazie

**Comment by LucaRogledi** [comment]
Buonasera,
Dalle analisi è emerso che l'errore riscontrato sembrerebbe essere causato dall'errata valorizzazione del campo iss contenuto nei token. Il campo _iss_ deve essere valorizzato utilizzando il _common name del certificato di firma_ come indicato di seguito:

Authentication Bearer Token:
AS-IS: `"iss": "auth:isaac4"` -> TO-BE: `"iss": "auth:S1#111#EURITECHX1"`

FSE-JWT-Signature Token:
AS-IS: `"iss": "integrity:isaac4"` -> TO-BE: `"iss": "integrity:S1#111#EURITECHX1"`

Rimaniamo a disposizione nel caso avesse bisogno di ulteriore supporto.

**Comment by euritech** [comment]
buongiorno, correggendo come indicato otteniamo questo errore: Response Text: {"traceID":"e6f8336acd14e142","spanID":"e6f8336acd14e142","type":"/msg/generic-error","title":"Errore generico.","detail":"Index: 0, Size: 0","status":500,"instance":""}

**Comment by LucaRogledi** [comment]
Buongiorno,
dalle analisi è emerso che all'interno del cda contenuto nel pdf non sono presenti informazioni, riportando solamente una linea commentata.
 
Contenuto CDA:
`b'<!--NEW_REFERTO_RADIOLOGIA--> <!-- Header Referto Radiolo'`
 
Di seguito può trovare:

- il pdf ricevuto dal gateway: [output.pdf](https://github.com/ministero-salute/it-fse-support/files/15333081/output.pdf).

- un esempio di cda RAD formato correttamente: [RAD.xml](https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/RAD.xml)

- il tool per l'iniezione del cda e la generazione del pdf: [pdf-generator](https://github.com/ministero-salute/it-fse-gtw-tools)  

 
La invitiamo a riprovare dopo aver corretto il cda e rigenerato il pdf.
Restiamo a disposizione per eventuale supporto.
Grazie

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue. Sarà possibile riaprirla nel caso in cui abbia bisogno di ulteriore supporto. Grazie.
