### ISSUE TITLE
Errore sui casi di test

### ISSUE THREAD

**Issue by danielepecoraro** [ministero-salute/it-fse-support#843]
Buongiorno,
tra le risposte ai casi dei test, è tornato il seguente errore:
```
{
  "id" : 147,
  "error" : "WII_UNKNOWN_TRANSACTION",
  "description" : "WorkflowInstanceID non presente nella collection delle transazioni.Assicurarsi di aver eseguito correttamente la validazione/pubblicazione per il wii segnalato"
}
```
Non riusciamo a capire il problema perchè abbiamo seguito la procedura indicata e abbiamo controllato che il WorkflowInstanceID fosse quello presente nella response FSE.
Potete segnalarci come risolvere il suddetto problema? Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno,
Nei giorni precedenti è stato segnalato un problema, ora rientrato, riguardante i workflowinstanceId generati durante il processo di validazione/pubblicazione. La invitiamo gentilmente a rieffettuare i test che riportavano l'errore "WII_UNKNOWN_TRANSACTION" ed aggiornare il workflowInstanceId all'interno del data.json ed excel di checklist con quello ottenuto dalla nuova chiamata. Infine può procedere con l'apertura di una nuova PR e attendere l'esito delle verifiche che riceverà via email.
Restiamo a disposizione in caso di ulteriore supporto.
Grazie

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue. Sarà possibile riaprirla nel caso in cui abbia bisogno di ulteriore supporto. Grazie.
