### ISSUE TITLE
WorkflowInstanceID non presente nella collection delle transazioni

### ISSUE THREAD

**Issue by FSEMosaiq** [ministero-salute/it-fse-support#845]
Salve
anche noi abbiamo ricevuto lo stesso messaggio di errore. Si tratta dello stesso problema della issue 843. Dobbiamo ripetere i test?

{
  "id" : 374,
  "error" : "WII_UNKNOWN_TRANSACTION",
  "description" : "WorkflowInstanceID non presente nella collection delle transazioni.Assicurarsi di aver eseguito correttamente la validazione/pubblicazione per il wii segnalato"
}

Un errore simile anche per i casi KO può avere la stessa origine?
{
  "id" : 151,
  "error" : "TEST_KO_NON_SUPERATO",
  "description" : "Test KO non superato. Assicurarsi che il traceId fornito abbia restituito in fase di validazione un errore bloccante."
}

Il traceid inserito ovviamente era quello restituito.
Per quanto riguarda la data da inserire, il processo di validazione dura circa 2 secondi, quale data va inserita?
Grazie

Silvio Taggi

**Comment by vigliottim** [comment]
Buonasera, l'errore da lei ricevuto è stato causato da un'anomalia ora risolta.
Le chiediamo di effettuare una nuova pull request dopo aver ripetuto tutti i test con l'errore riportato, inserendo i nuovi workflowistanceid nel data.json e nella checklist.
Chiudiamo il presente ticket e rimaniamo a disposizione per chiarimenti.
Grazie.
