### ISSUE TITLE
Aggiornamento files di test

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#847]
Salve, stamattina ho aggiornato i file pdf dei test case (come da voi richiesto, tra l'altro), ma mi sono stati segnalati di nuovo errori che non possono esistere.
Per esempio, nel CDA del test case n. 13, file VALIDAZIONE_CDA2_RAD_CT3.pdf, non c'è' la sezione **Storia_Clinica** segnalata con una marea di errori. (Potete tranquillamente verificarlo [QUI](https://github.com/infoserviceonline/it-fse-accreditamento/blob/main/GATEWAY/A1%23111%23INFOSERVICEONLINE/INFOSERVICE/FLY/2.0/FILES/VALIDAZIONE_CDA2_RAD_CT3.pdf))
Sullo stesso test case leggo: WII_UNEXPECTED_RESULT, errore impossibile visto che i dati li prendo, ovviamente, dalla richiesta di validazione.
Lo stesso dicasi altri test ed altre sezioni.
Mi spiegate com'è possibile segnalare errori di sezioni inesistenti? Cosa succede? Non è che ci sono di nuovo problemi nel sistema?
Allego CDA ed errori
[files.zip](https://github.com/ministero-salute/it-fse-support/files/15344218/files.zip)

Grazie.

**Comment by vigliottim** [comment]
Buongiorno, 
dalle analisi effettuate è emerso che il cda da lei allegato, estratto dal pdf _VALIDAZIONE_CDA2_RAD_CT3_ e riferito al caso di test con _id 13_ della checklist (caso di test 3 di tipo OK del file word) per cui ha ricevuto l'errore _WII_UNEXPECTED_RESULT_, non supera correttamente la validazione, come atteso dallo specifico caso di test:
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/568cb7c5-d354-4a76-994f-559a5aec8ade)
In particolare, non contiene la sezione `ClinicalDocument/component/structuredBody/component/section[@ID=Storia_Clinica]` che è obbligatoria da [specifiche](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/1-Referto%20di%20Radiologia/CDA2_Referto_di_Radiologia_OK.xlsx): 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/d26202b1-6928-4af4-bee5-4e5a71434797)
L'assenza di tale sezione obbligatoria e di altri suoi sottoelementi come il seguente: 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/d18ce66c-cccc-44c6-9030-97d98c7a3c5f)
genera, in cascata, gli errori successivi.
La preghiamo di controllare attentamente che tutte le section e gli elementi indicati come obbligatori nella colonna F del file excel CDA2_Referto_di_Radiologia_OK.xlsx siano presenti e di effettuare una nuova PR con le dovute correzioni. 
Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
