### ISSUE TITLE
Errore nella validazione in modalità RESOURCE

### ISSUE THREAD

**Issue by NunzioAgfa** [ministero-salute/it-fse-support#85]
Buongiorno,
sto facendo dei test di validazione in modalità RESOURCE, ma ottengo il seguente errore:
**Cannot find the declaration of element 'xfa:datasets'**
Sembra quindi che non viene trovato il tag xfa:datasets ma è il nodo root della struttura resource iniettata al pdf.
Allego il pdf inviato e sotto riporto la riposta completa.

{
  "traceID" : "ce08a421a84015ee",
  "spanID" : "ce08a421a84015ee",
  "type" : "/msg/syntax",
  "title" : "Errore di sintassi.",
  "detail" : "ERROR: -1,-1 cvc-elt.1: Cannot find the declaration of element 'xfa:datasets'.",
  "status" : 400,
  "instance" : "/validation/error",
  "workflowInstanceId" : "2.16.840.1.113883.2.9.2.160112.1c14a9fd4dfc4c29c88f1c5d3fd85a9e4cd7765217a25d1ae72cb00dd3afa9e5.7d3510b924^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

[WEW809_IN.pdf](https://github.com/ministero-salute/it-fse-support/files/10559050/WEW809_IN.pdf)

**Comment by SeemoneB** [comment]
Buongiorno,
ho lo stesso errore. Ci sono novità per questa issue?
Grazie

**Comment by NunzioAgfa** [comment]
Ciao SeemoneB, non ho avuto novità, sono ancora in attesa di risposta

**Comment by NunzioAgfa** [comment]
ciao SeemoneB, la modalità di iniezione del cda nel pdf, corrisponde con la mia? riusciresti ad allegare un tuo file di esempio, in modo tale da confrontarle, mentre attendiamo risposta?

**Comment by IStacchiotti** [comment]
Buon pomeriggio, è stato rilasciato un aggiornamento, l'errore non dovrebbe più aver luogo. Le chiediamo cortesemente di riprovare. Grazie

**Comment by NunzioAgfa** [comment]
Buongiorno, confermo che con il vostro aggiornamento, non viene più restituito l'errore e il cda viene letto correttamente. Grazie.

**Comment by NunzioAgfa** [comment]
Buongiorno, sto facendo altre prove sempre in modalità Resource e ottengo di nuovo l'errore nell'estrazione del cda:
Errore in fase di estrazione del CDA.
Sapete dirmi cosa può essere sbagliato?
Allego il file e sotto trovate la risposta completa:
{
  "traceID" : "7e6bf0e282c4db1a",
  "spanID" : "7e6bf0e282c4db1a",
  "type" : "/msg/cda-element",
  "title" : "Errore in fase di estrazione del CDA.",
  "detail" : "Error while extracting CDA from PDF document",
  "status" : 400,
  "instance" : "/cda-extraction",
  "workflowInstanceId" : "UNKNOWN_WORKFLOW_ID"
}

[WEW811.pdf](https://github.com/ministero-salute/it-fse-support/files/10721748/WEW811.pdf)

**Comment by masciamariotti** [comment]
Buon pomeriggio,
trattandosi di una problematica diversa, al fine di tracciare correttamente la risoluzione dei singoli ticket, le chiederei di aprire una nuova issue.
Grazie

**Comment by NunzioAgfa** [comment]
Ok, fatto: issue #99
