### ISSUE TITLE
Problema sul flusso del trasferimento fascicolo

### ISSUE THREAD

**Issue by GiuseppeMaiulli** [ministero-salute/it-fse-support#850]
Buongiorno,
 
Vi contatto per avere un chiarimento sulla procedura di trasferimento di un fascicolo. 
 
Secondo la nuova specifica Agid 2.5 (Framework e Dataset dei servizi di base) a pagina 93 è stata introdotta l’obbligatorietà, come per gli altri processi, della comunicazione del codice loinc del tipo documento in asserzione
“urn:oasis:names:tc:xspa:1.0:resourc e:hl7:type”.
 
Il flusso del trasferimento prevede prima il recupero dei riferimenti dei documenti, poi il recupero dei metadati stessi per il salvataggio sul FSE di destinazione, ed infine la cancellazione dei metadati dal FSE di partenza.
 
Il problema è che se nella cancellazione, avendo già ricevuto i metadati completi dalla chiamata precedente, la comunicazione del codice loinc del documento da cancellare non è un problema, negli altri due step non abbiamo ancora questa informazione.
 
La prima chiamata, generica, ritorna i riferimenti di tutti i documenti cercati, ma essendo “riferimenti” (ObjectRef) gli stessi non contengono l’informazione del codice loinc del documento in trasferimento.
Ne consegue che la successiva chiamata, di dettaglio, per recuperare i metadati del singolo documento in trasferimento, non può essere effettuata impostando questo attributo nell’asserzione.
 
Si tratta di una lacuna nelle specifiche o di una nostra errata interpretazione?

Cordiali saluti,
Giuseppe

**Comment by LucaRogledi** [comment]
Buongiorno,
Le segnaliamo che il trasferimento indice non è un servizio previsto nel FSE2.0.
Grazie

**Comment by vigliottim** [comment]
Buongiorno, 
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue. 
Potrà riaprila nel caso in cui fosse necessario ulteriore supporto. 
Grazie.
