### ISSUE TITLE
Informazioni accreditamento RAD e RSA per fornitore già censito

### ISSUE THREAD

**Issue by cbslucalanzano** [ministero-salute/it-fse-support#851]
Buongiorno,

in qualità di fornitore già accreditato (e censito) per i Referti di Medicina di Laboratorio, abbiamo oggi necessità di gestire RAD e RSA.

Ci chiedevamo quindi se era necessario compilare nuovamente il modulo al seguente indirizzo: https://ec.europa.eu/eusurvey/runner/FSE-raccolta-id-applicativo, oppure se c'è un modo per aggregare quanto ci occorre alla precedente richiesta.

Le chiavi in nostro possesso sono le seguenti:

**A1111CBSISTEMIXX_auth
S1111CBSISTEMIXX_sign**

Potreste verificare se tali sono autorizzate anche i documenti di tipo RAD e RSA?
In caso negativo, come potremmo utilizzare le stesse chiavi? (Considerate che utilizzeremo lo stesso applicativo con lo stesso numero di versione)

Grazie della collaborazione.
Un saluto

**Comment by vigliottim** [comment]
Buongiorno, 
è necessario compilare nuovamente il modulo [eu-survey](https://ec.europa.eu/eusurvey/runner/FSE-raccolta-id-applicativo) poiché la nuova tipologia documentale non è stata censita. 
Inoltre, le facciamo presente che, come riportato in [documentazione](https://github.com/ministero-salute/it-fse-accreditamento#nuova-tipologia-documentale-per-applicativo-gi%C3%A0-presente-nella-lista-dei-software-convalidati), nel momento in cui si aggiunga una nuova tipologia documentale in seguito al conseguimento della validazione per una diversa, occorre ripetere la fase 1 per tutte le tipologie documentali. 
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by cbslucalanzano** [comment]
Quindi ciò significa che siamo tenuti a rifare tutta la procedura di accreditamento?

Non sarebbe possibile fare una nuova richiesta solo per RAD e RSA e procedere solo per questi documenti con la fase 1?
Altra domanda: successivamente alla richiesta dovremmo quindi utilizzare certificati differenti?

**Comment by vigliottim** [comment]
Purtroppo è necessario ripetere l'intera procedura per tutte le tipologie documentali.
Per questo consigliamo di inviare fin da subito una checklist comprensiva di tutti i CDA per i quali si intende accreditarsi, altrimenti si dovranno ripetere tutti i casi di test ogni qualvolta si intenda aggiungere una nuova tipologia documentale.
La informiamo che può usare i certificati già in suo possesso.
Grazie.

**Comment by cbslucalanzano** [comment]
Quindi posso mantenere i certificati summenzionati e compilare una nuova richiesta spuntando tutti i CDA a cui siamo interessati accreditarci. Ho compreso bene?

Grazie del supporto

**Comment by vigliottim** [comment]
> Quindi posso mantenere i certificati summenzionati e compilare una nuova richiesta spuntando tutti i CDA a cui siamo interessati accreditarci. Ho compreso bene?
> 
> Grazie del supporto

Esatto.
Rimaniamo a disposizione qualora avesse altri dubbi.

**Comment by cbslucalanzano** [comment]
Grazie del supporto!

**Comment by cbslucalanzano** [comment]
Avrei un ultima domanda da farvi.

Essendo già in possesso dei vecchi files afferenti all'accreditamento per LAB (ad es. data.json, ecc.), posso integrare in questi ultimi i test che dovrò effettuare per RAD e RSA, senza dover nuovamente rifare anche quelli di LAB?

Grazie

**Comment by vigliottim** [comment]
Buongiorno, purtroppo non è possibile integrare i nuovi file con i precedenti. 
Nel momento in cui si aggiunge una nuova tipologia documentale in seguito al conseguimento della validazione per un diverso CDA, è necessario ripetere i casi di test per i quali è stato già conseguito l'accreditamento.

**Comment by cbslucalanzano** [comment]
Grazie della risposta, Michela.

Cerco di essere più specifico, allo scopo di comprendere meglio la questione.

Attualmente, come già accennato, siamo già accreditati per il CDA afferente a LAB.
All'interno della repository ministeriale è quindi già presente il nostro percorso personale, con all'interno i file già caricati nell'ultima pull request. (data.json, report-checklist, cartella FILES).

Dovendo utilizzare lo stesso software e la stessa versione dell'applicativo (poiché gestirà anche RAD e LAB), mi chiedevo se, per RAD e RSA, dovrò integrare il data.json presente con i nuovi test che andrò a fare e se, possibilmente, posso mantenere i test già effettuati in precedenza per LAB.

Spero di aver chiarito meglio la questione.

**Comment by vigliottim** [comment]
Può integrare il data.json usato in precedenza ma dovrà ripetere tutti i test per LAB - tipologia documentale per cui si è già accreditato - ed effettuare i nuovi test per RAD e RSA - le nuove tipologie documentali per cui deve ancora accreditarsi, aggiornando data.json e checklist con i dati delle nuove chiamate di validazione.
Rimaniamo a disposizione nel caso in cui avesse ulteriori dubbi.

**Comment by cbslucalanzano** [comment]
La ringrazio. Ora mi è chiaro il tutto.

Grazie nuovamente della disponibilità e gentilezza.
