### ISSUE TITLE
Problemi per creazione repository per accreditamento

### ISSUE THREAD

**Issue by Jack19650524** [ministero-salute/it-fse-support#853]
Buongiorno,
Abbiamo mandato la lettera per accreditamento la settimana scorsa ma, oggi non è stata ancora creata.
Se si può creare autonomamente il repository A1#111#TS23XX, in modo da poter procedere con i test, per l' accreditamento 
grazie.

**Comment by vigliottim** [comment]
Buon pomeriggio,
come indicato in [documentazione ](https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#procedura-di-caricamento-dei-risultati), il repository deve essere creato autonomamente e deve avere la seguente struttura per ogni software:
`GATEWAY/{commonName auth}/{subject_application_vendor}/{subject_application_id}/{subject_application_version}`
Per inviare i risultati dei test effettuati è necessario eseguire una pull request seguendo le indicazioni riportate al [link](https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#accreditamento-fse-20-draft).
Rimaniamo a disposizione per chiarimenti.

**Comment by Jack19650524** [comment]
Buongiorno,
scusate la mia scarsa conoscenza ma, mi potreste dare delle indicazioni più dettagliate per eseguire la creazione del repository.
Grazie per la pazienza.

**Comment by vigliottim** [comment]
Buongiorno, per creare il repository può procedere nel seguente modo:

1. Creare il proprio fork al repository centrale dalla pagina https://github.com/ministero-salute/it-fse-accreditamento cliccando su "Create new fork": 
<img width="922" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/b09b4aa0-1cc0-4304-822a-66542b0cfc6f">

2. Strutturare il repository come indicato cliccando sul bottone "Add file" -> "Create New File" nella pagina del proprio fork (per creare una folder è necessario mettere lo slash finale / quando si inserisce il nome nel breadcrump):

<img width="650" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/c7dbc395-9730-461a-b17f-a8bee9bee2f3">

![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/4ffc86c8-c5e3-4fb4-bc56-1c72b7b267ee)

3. Caricare i file nelle cartelle apposite create.

4. Effettuare la pull request.

Rimaniamo a disposizione per ulteriori dubbi.

**Comment by Jack19650524** [comment]
Buongiorno,
Grazie, per l'indicazioni ma, mi servirebbe un ulteriore precisazione.
Quando aggiungo il file  per poter premere il commit changes, devo mettere un carattere per poter eseguire la richiesta, cosa ci devo mettere?
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, potrebbe cortesemente allegare uno screenshot? Grazie.

**Comment by Jack19650524** [comment]
Buongiorno,
allego screenshot dopo aver premuto Add file.

![Screenshot 2024-05-23 112104](https://github.com/ministero-salute/it-fse-support/assets/166118664/364f99eb-05c5-4cc4-9801-67c9fffb4585)

**Comment by vigliottim** [comment]
Buongiorno, 
se inserisce il nome del file comprensivo di estensione nella textbox _"Name your file..."_ verrà creato un nuovo file vuoto, avente nome ed estensione scelti:

![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/35c60dd8-df8d-44f3-99cd-08fadf2db6ee)
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/5e826605-b31c-4c6b-94b2-5c9ed1ebe74e)

Le suggeriamo di creare prima la struttura del repository seguendo le indicazioni riportate in documentazione e di cliccare _"Commit changes..."_ dopo aver creato le cartelle (vuote):
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/8a380024-215d-4670-a11f-e5b83714196b)

In seguito, per effettuare il caricamento di file, invece, potrà cliccare su "Upload files" nel menù a tendina mostrato in figura:
<img width="656" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/de211c34-a1f3-43d8-b9be-1133a78e1778">
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/a1ef0dbb-bc37-484e-81c5-a0d1fa6dde93)
Rimaniamo a disposizione nel caso abbia ulteriori dubbi.
