### ISSUE TITLE
Problema cancellazione documento

### ISSUE THREAD

**Issue by nbssrl** [ministero-salute/it-fse-support#854]
Buon pomeriggio stiamo provando il servizio di cancellazione di un documento precedentemente pubblicato e revisionato. Nella delete inseriamo l' id che abbiamo inserito nel body della request in fase di sostituzione del documento ma continuiamo a ricever il seguente errore: "Document cannot be found on the Server FHIR". 
Abbiamo provato anche ad inserire nell'url della request l' identificativo del documento ripreso dal servizio di verifica status workflowInstaceId.
Il workflowInstaceId è:

**"2.16.840.1.113883.2.9.2.120.3.1.4.4.ce20d10e5c0d7f44d8756a6ecca7889c327981114847b800109759bf8e600c09.47e7ebb07c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"**

Il traceId è :"**ac27b3d689cab01d**",
Sapete come possiamo risolvere la problematica?

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Dalla chiamata del servizio di status tramite workflowInstanceId da lei indicato, contenente le informazioni riguardo la chiamata di Replace:
`2.16.840.1.113883.2.9.2.120.3.1.4.4.ce20d10e5c0d7f44d8756a6ecca7889c327981114847b800109759bf8e600c09.47e7ebb07c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId`
 
Risulta che, dopo la Replace, il documento stia utilizzando il seguente identificativoDoc:
`2.16.840.1.113883.2.9.2.120.4.4^15.120163.REF_2024000023534_1`

Mentre all'interno della chiamata di Delete con traceId `ac27b3d689cab01d` è stato indicato il documento con il seguente identificativoDoc:
`2.16.840.1.113883.2.9.2.120.4.4^15.120163.REF_2024000023534_0`

La invitiamo a riprovare utilizzando l'identificativoDoc aggiornato in seguito alla chiamata di Replace ( `2.16.840.1.113883.2.9.2.120.4.4^15.120163.REF_2024000023534_1` ) e rimaniamo a disposizione per ulteriore supporto. 
Grazie

**Comment by nbssrl** [comment]
appena svolta e ricevi il medesimo errore:
ID:2.16.840.1.113883.2.9.2.120.4.4^15.120163.REF_2024000023534_1

"traceID" : "90b673136128409a"

**Comment by LucaRogledi** [comment]
Buongiorno,
L'errore riscontrato potrebbe avere una delle seguenti cause: 

1. L'identificativoDoc è stato aggiornato prima della chiamata di delete da lei effettuata e non risulta più quello utilizzato (ad esempio potrebbe essere stata effettuata una nuova chiamata di sostituzione).

1. La chiamata di delete è stata invocata 2 volte consecutivamente.

Dalle nostre verifiche il sistema risulta funzionare correttamente e la sua chiamata risulta formalmente corretta. 
Le chiederemmo gentilmente se può riprovare effettuando un giro pulito partendo dalla pubblicazione con un nuovo identificativoDoc e assicurandosi durante la chiamata di delete che il servizio venga chiamato una volta soltanto.

In caso dovesse riscontrare nuovamente l'errore la invitiamo a condividere le risposte ricevute dalle chiamate di pubblicazione/sostituzione effettuate precedentemente alla delete per fornirle ulteriore supporto.
Grazie

**Comment by nbssrl** [comment]
Bungiorno,
grazie della risposta. Abbiamo provato a svolgere una  prova pulita e ad inviare una sola volta il messaggio di cancellazione.
Adesso riceviamo l' errore: 
 **"detail" : "javax.xml.ws.soap.SOAPFaultException: [400] Documento 15.120163.REF_2024000023664_0 inesistente".**

La chiamata è stata svolta col il seguente id 2.16.840.1.113883.2.9.2.120.4.4^15.120163.REF_2024000023664_0

**In allegato trovate i dati estrapolati dal servizio di status workflow dove l'id del referto è il medesimo della chiamata di delete e risulta pubblicato com' è possibile che in fase di cancellazione non trovi un referto che è stato appena pubblicato?**
[status_referto.txt](https://github.com/ministero-salute/it-fse-support/files/15400182/status_referto.txt)

**Comment by LucaRogledi** [comment]
Potrebbe gentilmente riportare le response complete ricevute dalle chiamate dei servizi di pubblicazione e delete (compreso traceId/govwayId) se disponibili? grazie!

**Comment by nbssrl** [comment]
La response che ricevo è la seguente:
  "message" : {
    "govway_id" : "20240522100248",
    "detail" : "javax.xml.ws.soap.SOAPFaultException: [400] Documento 15.120163.REF_2024000023664_0 inesistente",
    "title" : "Internal error",
    "type" : "midlleware-500",
    "status" : 500
  }
Non ho un ritorno del traceId

**Comment by LucaRogledi** [comment]
Grazie per le evidenze. 
L'errore in questione sembrerebbe essere originato dal Middleware che, ricevuto in input l'identificativoDoc corretto (quello utilizzato in pubblicazione: `2.16.840.1.113883.2.9.2.120.4.4^15.120163.REF_2024000023664_0`), tenta di eliminare il documento con identificativoDoc: `15.120163.REF_2024000023664_0`.

Segnaliamo che, come riportato in documentazione a questo [link](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#5-servizio-di-eliminazione-documento), l'url atteso dal Gateway per l'invocazione dell'eliminazione è:
`https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/{identificativoDocUpdate}`
ovvero: 
`https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.120.4.4%5E15.120163.REF_2024000023664_0` (in questo caso, in seguito a urlencode applicato all'identificativoDocUpdate inserito nell'url della chiamata). 

La invitiamo a rivolgersi ai gestori del middleware eventualmente per **verificare la corretta interpretazione dei dati all'origine**.
Restiamo a disposizione in caso fosse necessario ulteriore supporto.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Potrà riaprirla nel caso in cui avesse bisogno di ulteriore supporto.
Grazie.
