### ISSUE TITLE
github client: errore durante clone del repository

### ISSUE THREAD

**Issue by FSEMosaiq** [ministero-salute/it-fse-support#855]
error: invalid path 'GATEWAY/A1#111#SAXOSXX/Saxos_Informatica_S.R.L./ProgettoOsp/11.108/FILES/T0_VALIDATION_LDO.pdf'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

potete provvedere a correggere il problema?
grazie
Saluti

**Comment by vigliottim** [comment]
Buongiorno, l'errore che riceve potrebbe essere causato dal nome assegnato al file indicato nell'errore.
La invitiamo ad usare il comando:
`git config --global core.protectNTFS false`
prima di effettuare il clone, in modo da ignorare il naming NTFS.
In alternativa, può rinominare i file secondo le indicazioni riportate al link: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file
Restiamo a disposizione per ulteriori chiarimenti.

**Comment by FSEMosaiq** [comment]
sono riuscito a fare il clone, ma la nostra cartella https://github.com/ministero-salute/it-fse-accreditamento/tree/main/GATEWAY/A1%23111ELEKTA/ELEKTA/MOSAIQ/3 non é stata copiata.

**Comment by vigliottim** [comment]
La sua cartella non è presente sul repository centrale perché è necessario fare la pull request.
Per completare la procedura, la invitiamo ad eseguire le istruzioni al link seguente: https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#pull-request. 
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Potrà riaprirla nel caso in cui avesse bisogno di ulteriore supporto.
Grazie.
