### ISSUE TITLE
Aggiornamento Accreditamento Fornitore A1#111#INFOSERVICEONLINE - INFOSERVICE - FLY - 2.0

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#856]
Buongiorno,
due giorni fa ho ricevuto la conferma dell'accreditamento, ieri, invece, ho ricevuto una richiesta di chiarimenti, tutti incomprensibili tranne uno. Ho comunque provveduto a correggere il file di checklist e pubblicarlo come richiesto, ma a questo punto non so come procedere poichè mi è stato detto di comunicare l'avvenuto aggiornamento via e-mail, ma senza fornire alcun indirizzo. Io ho fatto una reply chiedendo questa volta io chiarimenti, ma non ho avuto risposta.
Cosa dovrei fare adesso di preciso?
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
la informiamo che ha passato con successo i test auto e che sono in corso le verifiche lato DTD.
La invitiamo a inoltrare la sua richiesta al seguente indirizzo e-mail: FSE-PNRR@innovazione.gov.it
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
Grazie.
