### ISSUE TITLE
Valorizzazione corretta healthCareFacility su referti RDA e RSA in ambito consulenza

### ISSUE THREAD

**Issue by msettt** [ministero-salute/it-fse-support#857]
Buongiorno,
avrei necessità di conoscere la valorizzazione delle varie extension all'interno del tag healthCareFacility per i referti RDA e RSA generati all'interno di episodi di Ricovero / PS.

Può capitare che il paziente sia ricoverato nel reparto 32.02 del presidio 010202.01.
Se viene chiesta una consulenza per esempio radiologica al reparto 69.01 del presidio 010202.02, sul relativo CDA2 RAD quali dati è più corretto inserire? 

In particolare sul:

healthCareFacility/id root="2.16.840.1.113883.2.9.4.1.6" -> va bene l'extension del reparto di ricovero? quindi extension="010202.01.32.02" o va inserito l'extension del reparto erogante? -> "010202.02.69.01"?

Le specifiche HL7 RDA indicato **"nel caso in cui l'incontro sia un ricovero ospedaliero, il tag <location>/<healthCareFacility> può rappresentare il reparto**" 

Le specifiche HL7 RSA parlano di **presidio di ricovero o struttura erogante** 

Le indicazioni sembrano un po ambigue quindi apparentemente vanno bene entrambe le valorizzazioni.

Potete darci qualche indicazione?
Vi ringrazio

**Comment by LucaRogledi** [comment]
Buongiorno, come da specifiche HL7 nel caso di ricovero l'elemento healthcareFacility/id viene valorizzato con "Codice Struttura + Sub Codice Struttura Interna + Codice Disciplina che rappresenta l’unità operativa interna a quel particolare dominio + opzionalmente il Codice".

**Comment by msettt** [comment]
Grazie per la risposta, quindi in sostanza nel caso specifico che ho indicato, sarà il presidio e unità operativa di ricovero 010202.01.32.02"?

**Comment by msettt** [comment]
Ho ricevuto un chiarimento in merito da HL7 Italia, che riporto per conoscenza di tutti:
Siccome qui va riportato il luogo in cui è avvenuto l'incontro da cui è scaturita la refertazione, va inserito il reparto erogante, non quello di ricovero: root="2.16.840.1.113883.2.9.4.1.6" extension="010202.02.69.01"

Potete chiudere la issue.
