### ISSUE TITLE
Lista accreditati

### ISSUE THREAD

**Issue by masieroandrea** [ministero-salute/it-fse-support#858]
Buongiorno,
il 17/05/2024 abbiamo ricevuto la mail di superamento dei test per la validazione della LDO.

_Salve,
Con la presente si comunica il superamento dei seguenti test [6,29,37,369] per il servizio [validazione/pubblicazione] del Fornitore [A1#111#ZUCCHETTIHEALTHCAREXX] - Vendor:[Zucchetti_Healthcare] - ID: [CSS2] - Version: [2024_10] - Sha: [4e16567f382e5558eeb5dfb6db66fcb580251075] in data odierna.Dal processo è stato escluso il controllo dei test: [7,8,9,45,63,64,65,66,67,68,69,70,71,72,73,74] per i quali si è ottenuto l'esonero.
A conclusione del processo, seguirà ulteriore comunicazione da parte del Dipartimento per la Trasformazione Digitale (DTD).
Saluti,
Il Team FSE 2.0_

Quando verremo aggiunti alla [lista degli accreditati](https://github.com/ministero-salute/it-fse-accreditati/tree/main/RESULTS) ?
Ci manca qualche passaggio?

Grazie,
Andrea

**Comment by vigliottim** [comment]
Buongiorno,
sono in corso alcune verifiche da parte del Dipartimento per la Trasformazione Digitale (DTD).
Riceverete ulteriori aggiornamenti non appena saranno concluse.
Grazie.

**Comment by masieroandrea** [comment]
Ok grazie.

In merito invece al piano di adeguamento applicativo ricevuto dopo l'esito positivo all'accreditamento, ho qualche dubbio sulla compilazione. Non so se magari anche questo file pregiudica l'inserimento nella lista degli accreditati.

1. il periodo temporale di adeguamento dell'applicativo si intente la data presunta di rilascio della versione validata dal processo di integrazione FSE, corretto? devo indicare quindi solo una cella con una data presunta (sia GTW nazionale che regionale)?
2. nel piando di adeguamento regionale, dobbiamo indicare tutti i nostri clienti che utilizzano la nostra applicazione per ogni regione che stiamo adeguando? E per gli eventuali prospect che potenzialmente potrebbero diventare nostri clienti dovremmo poi aggiornare questo documento?
3. al momento stiamo lavorando per adeguare solo i clienti di una regione, ma in futuro lavoreremo anche su altre regioni. Indichiamo nel piano di adeguamento solo la regione per la quale abbiamo effettivamente una pianificazione?

Grazie

**Comment by vigliottim** [comment]
Buongiorno,
può inoltrare la sua richiesta all'indirizzo e-mail: FSE-PNRR@innovazione.gov.it
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
