### ISSUE TITLE
Crash Program - Sprint 6 - RDE Lombardia, RDA Campania - UC8_EliminazioneDocumento: status":500,"instance":"/msg/service-error/ini"

### ISSUE THREAD

**Issue by EugenioGuagliardi** [ministero-salute/it-fse-support#859]
Salve , eseguendo il test UC8_EliminazioneDocumento otteniamo il seguente errore 

`{"traceID":"eec28c7666916c9e","spanID":"eec28c7666916c9e","type":"/msg/ini-error","title":"Ini error.","detail":"{\"traceID\":\"0000000000000000eec28c7666916c9e\",\"spanID\":\"d5ed46bc2d84b64c\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: javax.transaction.TransactionRolledbackException:  ; nested exception is: [\\n\\tjavax.transaction.SystemException](file://n/tjavax.transaction.SystemException) Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}","status":500,"instance":"/msg/service-error/ini"}
`

usando il trace id otteniamo:
```
{
    "traceID": "95e688efa648f84b",
    "spanID": "50f89a58ad3b28aa",
    "transactionData": [
        {
            "eventType": "RIFERIMENTI_INI",
            "eventDate": "2024-05-21T08:17:03.028+00:00",
            "eventStatus": "SUCCESS",
            "message": "Riferimenti trovati: urn:uuid:ed262aad-92ae-440e-b962-d17f02bab1b8",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.2ce7d492-174a-11ef-a9d8-0242a89a8ac7",
            "subject": "MDCMRZ90A41F205Q^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "030",
            "workflowInstanceId": "4f9c682d6e720269092a6a2ca4c433de2527e24012c2c160c718d09c7fbab770.716874cdaf^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "eec28c7666916c9e",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-05-21T08:17:03.038+00:00"
        },
        {
            "eventType": "EDS_DELETE",
            "eventDate": "2024-05-21T08:17:04.611+00:00",
            "eventStatus": "SUCCESS",
            "message": "Delete effettuata su eds",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.30.4.4^030703.RRDOCU.2ce7d492-174a-11ef-a9d8-0242a89a8ac7",
            "subject": "MDCMRZ90A41F205Q^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "PHR",
            "organizzazione": "030",
            "workflowInstanceId": "4f9c682d6e720269092a6a2ca4c433de2527e24012c2c160c718d09c7fbab770.716874cdaf^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "eec28c7666916c9e",
            "issuer": "integrity:S1#030#REGIONELOMBARDIA-TEST",
            "expiringDate": "2025-05-21T08:17:04.620+00:00"
        }
    ]
}
```
Cortesemente potete verificare?
Grazie per la collaborazione

**Comment by EugenioGuagliardi** [comment]
Salve, a valle della riunione di oggi dove ci è stata comunicata il rilascio lato SOGEI di una patch, abbiamo riprovato il test positivamente. 
Per Noi quindi la issue può essere chiusa.

Grazie per la collaborazione 
Eugenio

**Comment by vigliottim** [comment]
Grazie per il suo gentile feedback.
Procediamo alla chiusura della presente issue come richiesto.
Rimaniamo a disposizione per altre richieste di supporto.
