### ISSUE TITLE
Test KO vaccinazioni 

### ISSUE THREAD

**Issue by gmarzi** [ministero-salute/it-fse-support#86]
Questi test sia per la scheda vaccinazioni che per il certificato vaccinale vengono validati regolarmente
Test 7
livello di riservatezza del documento (confidentialityCode) con informazioni moderatamente sensibili (“Restricted”)
201{"traceID":"19422bbdec72af29","spanID":"19422bbdec72af29","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.f2206a49007bcbefd951b03cab0bbddac13fac3a5da3590d6701c86240f08f4a.f0a541916c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"} 
Test 8
Inserimento dell’indirizzo senza specifica del comune di residenza del paziente.
201{"traceID":"4b5cf3f8f4af5ad2","spanID":"4b5cf3f8f4af5ad2","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.f2206a49007bcbefd951b03cab0bbddac13fac3a5da3590d6701c86240f08f4a.3319a8ee80^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
 Test 9
Inserito il cognome ma omesso il nome 
201{"traceID":"ca15fae7690fecb9","spanID":"ca15fae7690fecb9","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.f2206a49007bcbefd951b03cab0bbddac13fac3a5da3590d6701c86240f08f4a.df88841ac1^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"

**Comment by Ser-ena** [comment]
Salve, relativamente ai test 8 e 9, come riportato anche nella legenda del file excel associato, per un campo "non valorizzato" si intende che non è presente all'interno del CDA2 l'elemento associato, qiuindi il tag <city> nel caso di test 8 e <given> nel caso di test 9.  Per il caso 7 stiamo effettuando le verifiche, le faremo sapere.

**Comment by Ser-ena** [comment]
Salve in merito al caso di test KO 7 viene generato un errore semantico dovuto ad una errata valorizzazione dell'attributo code dell'elemento confidentialityCode, ovvero valori presenti nel code system HL7 Confidentiality ma non quelli ammissibili da specifiche quali N e V:
<confidentialityCode code="R" codeSystem="2.16.840.1.113883.5.25" codeSystemName="HL7 Confidentiality" displayName="Restricted" />. Per i casi 8 e 9 precisiamo che i tag sono 'city' nel caso di test 8 e 'given' nel caso di test 9

**Comment by IStacchiotti** [comment]
Non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta.
