### ISSUE TITLE
Accreditamento soluzione PHI KLINIK

### ISSUE THREAD

**Issue by Elisabetta-Tecchio-GPI** [ministero-salute/it-fse-support#860]
Buongiorno,
volevamo notificare il caricamento completato dei test case per la soluzione PHI KILINK:

https://github.com/ministero-salute/it-fse-accreditamento/pull/1471

questa pull request contiene RSA.

Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, la ringraziamo per la notifica.
Procediamo alla chiusura della presente issue e rimaniamo a disposizione per ulteriori richieste di supporto.
