### ISSUE TITLE
Problemi in validazione: Codice versione LOINC non gestita

### ISSUE THREAD

**Issue by fabiodap** [ministero-salute/it-fse-support#861]
Buongiorno,
da questa mattina quando effettuiamo la validazione riceviamo di ritorno il seguente errore:

2024-05-23 12:03:51,792 SEVERE [com.ffi.swf.fse.cli.bus.tra.con.FSETrace] (main) FSE Response:
----------- FAIL -----------
gateway                  : https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1
traceId                  : b7e9b99d6d8f3be3
WorkflowInstanceId       : 2.16.840.1.113883.2.9.2.180205.4.4.807a44951e0d56c01b94e8bf6278bab5fd76ac092581dde9b0f28bf73f53adf5.e646c43110^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
response                 : Ãˆ stata trovata almeno una versione non gestita di un dizionario: [2.16.840.1.113883.6.1 v2.73]
type                     : /msg/vocabulary
application/problem+json :
{

Sapete dirmi che versione di LINC dobbiamo specificare visto che sembra che la 2.73 non è piu supportata?

Saluti,
Fabio

**Comment by fabiodap** [comment]
Questo un esempio di cme usiamo quel codice:

code code="18783-1" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" codeSystemVersion="2.73" displayName="Raccomandazione studio - Radiologia"

**Comment by fabiodap** [comment]
buongiorno. tuttavia valorizzandolo con 2.77 non da alcun errore in validazione

**Comment by fabiodap** [comment]
la domanda è, non essendo piu supportato il 2.73 qual'è il codice da usare?

**Comment by vigliottim** [comment]
Come indicato nel messaggio precedente, secondo la guida HL7 Italia l'attributo _codeSystemVersion_ è previsto solo all'interno dell'elemento _code_ di alcune sezioni, come ad esempio _"Motivo per lo studio - Radiologia"_: 

![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/96e55dd9-8575-4f1e-9309-7304f6dc5247)

In tal caso deve essere valorizzato con l'ultima versione disponibile del vocabolario: `codeSystemVersion="2.77"`
Laddove non è previsto (sezione "_Complicazioni"_, sezione _"Conclusioni"_, sezione _"Raccomandazione studio - Radiologia_", sezione _"Referto Radiologico"_, sezione _"Storia generale"_), è necessario rimuoverlo.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Buongiorno, rettifichiamo quanto scritto in precedenza.
E' sempre possibile inserire il _codeSystemVersion_ come da schema, anche se da specifiche non è sempre indicato in quanto un attributo del _code_ sempre opzionale.
Inoltre, le confermiamo che l'attributo codeSystemVersion è da valorizzare con l'attuale versione rilasciata da LOINC che è la 2.77.
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
Grazie.

**Comment by fabiodap** [comment]
Ok. grazie. l'ho comunque tolto senza avere problemi in validazione.
Piu tardi vi scrivo altre cose riguardo alla questione di questo codice LOINC
