### ISSUE TITLE
Prosecuzione accreditamento

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#863]
Salve,
avendo ottenuto l'accreditamento per la tipologia RAD, come da elenco:
https://github.com/ministero-salute/it-fse-accreditati/tree/main/RESULTS
Adesso vorremmo proseguire con le altre tipologie. Per non sbagliare chiediamo delucidazioni circa la procedura corretta da seguire.
Avete già chiarito che ogni volta vanno inviati tutti i test case. quindi, da quanto abbiamo capito, lo status quo non va alterato, mentre vanno aggiunti i vari test case nella tripletta Pdf, data.json e checklist.xml.
Confermate la correttezza di quanto sopra?
Grazie.

**Comment by vigliottim** [comment]
Buonasera, 
come indicato in [documentazione](https://github.com/ministero-salute/it-fse-accreditamento#nuova-tipologia-documentale-per-applicativo-gi%C3%A0-presente-nella-lista-dei-software-convalidati), nel caso in cui un applicativo abbia superato la fase 1 per una particolare tipologia documentale e il fornitore sottometta una nuova richiesta di accreditamento per un’altra tipologia documentale, sarà necessario ripetere la fase 1 per le tutte le tipologie documentali.
Pertanto, nel suo caso, dovrà ripetere tutti i test per RAD e aggiornare data.json e checklist con i dati relativi alle nuove chiamate.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by infoserviceonline** [comment]
Buongiorno, nel link indicato si legge: **I fornitori dovranno sottomettere una nuova pull request contenente tutti i casi di test (e relativo data.json) eseguiti per le due tipologie documentali ( LDO+RSA ).**
Ma non specifica se i case test da sottomettere per la tipologia già accreditata debbano essere necessariamente riprodotti o possono essere utilizzati gli stessi. Non che sia un grosso problema, dal momento che la procedura è automatizzata, ma comunque ci risparmierebbe un po' di lavoro che sembra essere superfluo.
Grazie.

**Comment by vigliottim** [comment]
I casi di test per la tipologia documentale già accreditata (nel suo caso RAD) possono essere gli stessi ma devono essere ripetute le chiamate relative.
Rimaniamo a disposizione nel caso in cui avesse ulteriori dubbi.

**Comment by infoserviceonline** [comment]
Ok, grazie mille, chiudo richiesta.
