### ISSUE TITLE
Errore vocabolario in validazione

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#865]
Buongiorno, nel ripetere la validazione di tutti i  test case già accreditati, quindi finora validi, ricevo su tutti questo errore:
{
  "traceID": "5afe6f551380c2b2",
  "spanID": "5afe6f551380c2b2",
  "type": "/msg/vocabulary",
  "title": "Errore vocabolario.",
  "detail": "È stata trovata almeno una versione non gestita di un dizionario: [2.16.840.1.113883.6.1 v2.73]",
  "status": 400,
  "instance": "/validation/error",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.8fe46b71d98546dc779f4a7f4859b056b254bbe56b59baa550333b2c46441c87.4c059ff605^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
  "warning": null
}
Cosa è cambiato e come risolvere?
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
dovrebbe verificare che l'attributo _codeSystemVersion_ dell'elemento _code_ sia valorizzato con l'ultima versione del vocabolario utilizzata, ossia 2.77.
Rimaniamo a disposizione nel caso in cui il problema dovesse ripresentarsi.

**Comment by infoserviceonline** [comment]
In effetti correggendo i cda l'errore scompare, ma ciò comporterà inevitabilmente la nuova creazione di tutti i test case, altrimenti non potrei fare le chiamate di validazione corrette. Pazienza.
Grazie.
