### ISSUE TITLE
Campania - Sprint 5 - Toscana

### ISSUE THREAD

**Issue by avlp** [ministero-salute/it-fse-support#866]
Buongiorno è stato inviato un reeferto ricevendo l'id TEMP_150_826000 . Si attende verifica per procedere con l'operazione REPLACE

**Comment by g-maugeri-sogei** [comment]
La richiesta va in errore PFC7 - Patient validation error. Aggiungo che il CF CRSNRC73B25F839K non risulta presente neppure nella nostra base dati.

**Comment by cdezorzi** [comment]
Buonasera, analizzando i nostri log non risulta transitato verso i ns sistemi l'id TEMP_150_826000 da voi utilizzato.

**Comment by g-maugeri-sogei** [comment]
Aggiornata base dati. Potete riprovare ?

**Comment by avlp** [comment]
Salve, inviato TEMP_150_826256

**Comment by g-maugeri-sogei** [comment]
Mancano i consensi sul CF. Li ho messi io. Potere procedere con una nuova richiesta. 
Rigurdo la verifica dell'esito, potete verificare in autonomia con utilizzando i servizi INS.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso fosse necessario ulteriore supporto. Grazie.

**Comment by avlp** [comment]
E' stato inviato un nuovo documento ricevendo TEMP_150_830377

**Comment by paolo-casillo** [comment]
@cdezorzi il documento TEMP_150_830377 risulta in stato ELAB: ci sono problemi con la piattaforma di staging?

**Comment by g-maugeri-sogei** [comment]
Buonasera, per la transazione TEMP_150_830377 l'RDA restituisce questo errore:
JAXRS operation failed invoking cxf://bean:xdsDocumentRegistryService?synchronous=true with statusCode: 500]"

**Comment by vigliottim** [comment]
Buonasera,
procediamo alla chiusura della presente issue poiché non più attuale essendo terminato il Crash Program e essendo state rilasciate delle evolutive.
La presente verrà riaperta nel caso di nuove evidenze che confermino il persistere del problema.
Grazie.
