### ISSUE TITLE
Campania - Sprint 5 - Lombardia

### ISSUE THREAD

**Issue by avlp** [ministero-salute/it-fse-support#867]
Buongiorno è stato inviato un referto ottenendo TEMP_150_824992 . Si attende conferma per la successiva REPLACA

**Comment by g-maugeri-sogei** [comment]
Pubblicazione completata correttamente.

**Comment by vigliottim** [comment]
Buongiorno, 
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue. 
Potrà riaprila nel caso in cui fosse necessario ulteriore supporto. 
Grazie.
