### ISSUE TITLE
Crash Program - Sprint 6 - RDE Toscana UC4_Aggiornamento_Metadati

### ISSUE THREAD

**Issue by cdezorzi** [ministero-salute/it-fse-support#868]
Buongiorno, durante l'esecuzione del test UC4_Aggiornamento_Metadati, abbiamo riscontrato il seguente errore:

idDoumento : 2.16.840.1.113883.2.9.2.90.4.4^9999.LAB.910.64004

{
    "traceID": "1772c43dd21b8417",
    "spanID": "1772c43dd21b8417",
    "type": "/msg/ini-error",
    "title": "Ini error.",
    "detail": "{\"traceID\":\"00000000000000001772c43dd21b8417\",\"spanID\":\"6b934f301bbb7599\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.\",\"instance\":\"error/generic\"}",
    "status": 500,
    "instance": "/msg/service-error/ini"
}

Potete verificare ? 
Grazie

**Comment by vigliottim** [comment]
Buonasera,
procediamo alla chiusura della presente issue poiché non più attuale essendo terminato il Crash Program e essendo state rilasciate delle evolutive.
La presente verrà riaperta nel caso di nuove evidenze che confermino il persistere del problema.
Grazie.
