### ISSUE TITLE
Errore in validazione se author non contiene nessun elemento "telecom"

### ISSUE THREAD

**Issue by fabiodap** [ministero-salute/it-fse-support#869]
Buongiorno,

stiamo riscontrando degli errori in validazione se l'author non contiene almeno un elemento telecom riguardante il telefono o la mail.
E corretto valorizzare gli elementi telecom con valore di default nullFlavor="UNK"

Per esempio:

<telecom nullFlavor="UNK" use="HP"/>

Oppure come va valorizzato un elemento telecom di default?

Saluti,
Fabio

**Comment by vigliottim** [comment]
Buongiorno, potrebbe gentilmente indicarci a quale tipologia documentale di CDA2 fa riferimento?
Grazie.

**Comment by fabiodap** [comment]
Mi riferisco al CDA di Radiologia.

**Comment by vigliottim** [comment]
Buongiorno, si precisa che è neccessario valorizzare un elemento telecom con un valore diverso da @nullFlavor. 
Grazie.

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
La invitiamo a riaprirla nel caso in cui avesse bisogno di ulteriore supporto.
Grazie.
