### ISSUE TITLE
Casi di test LDO e VPS

### ISSUE THREAD

**Issue by danielepecoraro** [ministero-salute/it-fse-support#87]
Buongiorno, stiamo effettuando i test di validazione di LDO e VPS, sui seguenti casi di test:
VALIDAZIONE_TOKEN_JWT_LDO_KO
VALIDAZIONE_TOKEN_JWT_VPS_KO
VALIDAZIONE_LDO_TIMEOUT
VALIDAZIONE_VPS_TIMEOUT

E' possibile sapere cosa va testato di preciso? Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, abbiamo risposto su Slack segnalando che le descrizioni dei casi di test sono riportate nello sheet "TestCases", colonna "E" della checklist. Qualora non fosse sufficiente, potrebbe chiarire meglio i dubbi eventualmente? 
Grazie mille

**Comment by danielepecoraro** [comment]
Buongiorno di nuovo,

Nel file per i casi specificati abbiamo visto la colonna specificata che rimanda alla sezione prerequisiti, nella quale troviamo gli step già effettuati per l'accreditamento ai test. Non ci è chiaro come procedere su questi test.

**Comment by IStacchiotti** [comment]
Nelle celle, oltre a "precondizioni", è riportato anche il testo che descrive nello specifico il caso di test. Per esempio, nella cella E29, relativa al test "VALIDAZIONE_TOKEN_JWT_LDO_KO" è riportato: 

"_Precondizioni:
Il fornitore utilizza un token jwt mancante di campi obbligatori, quindi non valido.
Descrizione di Business del caso di test: 
Viene richiamato il servizio di validazione "https://<HOST>:<PORT>/v<major>/documents/validation" con un token jwt non valido a causa della mancanza di uno o più campi obbligatori al fine di testare la gestione dell'errore sul token (status code 403), secondo quanto descritto in https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway._". Vi risulta?

**Comment by danielepecoraro** [comment]
No, dal file abbiamo controllato la cella indicata, la E29 e non ci risultano, così come nei campi indicati nel primo messaggio.

**Comment by IStacchiotti** [comment]
Ok, state considerando l'ultima versione della checklist, scaricabile a questo ([link](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/accreditamento-checklist_V4.1.xlsx))? In caso positivo, vi invito ad espandere la cella facendo doppio click in corrispondenza del numero di riga. Il testo inizia con una riga bianca, non vorrei che sia questa a trarvi in inganno! Grazie 
<img width="1090" alt="Immagine 2023-02-03 121138" src="https://user-images.githubusercontent.com/122798799/216589415-3c5f61f0-4f41-4dff-a75d-dc44dc5f226b.png">

**Comment by danielepecoraro** [comment]
Si adesso escono, grazie.
