### ISSUE TITLE
CRASH PROGRAM - Sprint 4 - RDE Emilia-Romagna, RDA Toscana - UC4

### ISSUE THREAD

**Issue by xenergy33** [ministero-salute/it-fse-support#870]
Buongiorno,
oggi abbiamo riprovato l'aggiornamento metadati per questo documento: 
2.16.840.1.113883.2.9.2.80.4.4^105800053000080124TESTSPS3659400
con traceID:
329b68ff24e870dc
L'esito è lo stesso che avevamo avuto in precedenza:

{"traceID":"329b68ff24e870dc","spanID":"329b68ff24e870dc","type":"/msg/ini-error","title":"Ini error.","detail":"{\"traceID\":\"0000000000000000329b68ff24e870dc\",\"spanID\":\"8e8cee52359f68e6\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"it.finanze.sanita.fse2.ms.iniclient.exceptions.base.BusinessException: SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:R1CODE CONTEXT:Wrong document id: document to update not existing\",\"instance\":\"error/ge

Buona serata.
Raffaele

**Comment by vigliottim** [comment]
Buonasera,
procediamo alla chiusura della presente issue poiché non più attuale essendo terminato il Crash Program e essendo state rilasciate delle evolutive.
La presente verrà riaperta nel caso di nuove evidenze che confermino il persistere del problema.
Grazie.
