### ISSUE TITLE
Campania - Sprint 6 - Verfica stato

### ISSUE THREAD

**Issue by avlp** [ministero-salute/it-fse-support#871]
Salve si comunica di aver inviato un documento per lo sprint 6, TEMP_150_826316 . Si richiede conferma  esito

**Comment by paolo-casillo** [comment]
@g-maugeri-sogei chiedo confermo che la chiamata da effettuare è la seguente:
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:esit="http://esitocaricamentodocumentorichiesta.xsd.fse.ini.finanze.it">
   <soapenv:Header/>
   <soapenv:Body>
      <esit:EsitoCaricamentoDocumentoRichiesta>
         <esit:IdentificativoUtente>PROVAX00X00X000Y</esit:IdentificativoUtente>
         <esit:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</esit:pinCode>
         <esit:IdentificativoOrganizzazione>150</esit:IdentificativoOrganizzazione>
         <esit:StrutturaUtente>------</esit:StrutturaUtente>
         <esit:RuoloUtente>APR</esit:RuoloUtente>
         <esit:IdentificativiTemporaneiDocumenti></esit:IdentificativiTemporaneiDocumenti>
         <esit:DataRicercaDA>20180430090000</esit:DataRicercaDA>
         <esit:DataRicercaA>20181231090000</esit:DataRicercaA>
      </esit:EsitoCaricamentoDocumentoRichiesta>
   </soapenv:Body>
</soapenv:Envelope>
Nel caso in esame il tag IdentificativiTemporaneiDocumenti va valorizzato con TEMP_150_826316.
È corretto?

**Comment by g-maugeri-sogei** [comment]
La chimata va bene. Va cambiata cambiato solo il filtro sulla data:
REQUEST:
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:esit="http://esitocaricamentodocumentorichiesta.xsd.fse.ini.finanze.it">
   <soapenv:Header/>
   <soapenv:Body>
      <esit:EsitoCaricamentoDocumentoRichiesta>
         <esit:IdentificativoUtente>PROVAX00X00X000Y</esit:IdentificativoUtente>
         <esit:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</esit:pinCode>
         <esit:IdentificativoOrganizzazione>150</esit:IdentificativoOrganizzazione>
         <esit:StrutturaUtente></esit:StrutturaUtente>
         <esit:RuoloUtente>APR</esit:RuoloUtente>
         <esit:IdentificativiTemporaneiDocumenti>TEMP_150_826316</esit:IdentificativiTemporaneiDocumenti>
         <esit:DataRicercaDA>20180430090000</esit:DataRicercaDA>
         <esit:DataRicercaA>20251231090000</esit:DataRicercaA>
      </esit:EsitoCaricamentoDocumentoRichiesta>
   </soapenv:Body>
</soapenv:Envelope>
RESPONSE:
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <a:EsitoCaricamentoDocumentoRicevuta xmlns:a="http://esitocaricamentodocumentoricevuta.xsd.fse.ini.finanze.it" xmlns:b="http://esitocaricamentodocumentorichiesta.xsd.fse.ini.finanze.it" xmlns="http://tipodatiesitocaricamentodocumento.xsd.fse.ini.finanze.it">
         <a:Esito>0000</a:Esito>
         <a:EsitoCaricamentoDocumento>
            <IdentificativoTemporaneoDocumento>TEMP_150_826316</IdentificativoTemporaneoDocumento>
            <StatoElaborazione>OK</StatoElaborazione>
            <IdentificativoDocumento>2.16.840.1.113883.2.9.2.150.4.4^476631</IdentificativoDocumento>
         </a:EsitoCaricamentoDocumento>
         <a:ElencoErrori>
            <Errore>
               <codEsito>0000</codEsito>
               <esito>Operazione eseguita correttamente</esito>
               <tipoErrore>Success</tipoErrore>
               <fonte>FSE-INS-FE</fonte>
            </Errore>
         </a:ElencoErrori>
      </a:EsitoCaricamentoDocumentoRicevuta>
   </soapenv:Body>
</soapenv:Envelope>

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
non so se poteva essere utile una verifica lato FVG ma volevo solamente avvisare che non vediamo una transazione RegisterDocumentSet-b per il documento TEMP_150_826316.
Ringrazio e auguro una buona giornata.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Potrà essere riaperta nel caso fosse necessario ulteriore supporto.
Grazie.

**Comment by avlp** [comment]
Salve si è inviata una replace ottenendo Internal Error. Sono stati inviati si UniqueId che UUID come richiesto:
`<com:ComunicazioneMetadatiRichiesta xmlns:com="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it" xmlns:tip="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it">
	<com:IdentificativoUtente>PROVAX00X00X000Y</com:IdentificativoUtente>
	<com:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</com:pinCode>
	<com:IdentificativoOrganizzazione>150</com:IdentificativoOrganizzazione>
	<com:StrutturaUtente>201123456</com:StrutturaUtente>
	<com:RuoloUtente>DRS</com:RuoloUtente>
	<com:ContestoOperativo>TREATMENT</com:ContestoOperativo>
	<com:TipoDocumento/>
	<com:IdentificativoAssistito>DLRGNN79C01F839O</com:IdentificativoAssistito>
	<com:PresaInCarico>true</com:PresaInCarico>
	<com:TipoAttivita>CREATE</com:TipoAttivita>
	<com:Metadato>
		<tip:TipologiaStrutturaProdDoc>Ospedale</tip:TipologiaStrutturaProdDoc>
		<tip:TipoMime>application/pdf+text/x-cda-r2+xml</tip:TipoMime>
		<tip:LivelloConfidenzialita>N</tip:LivelloConfidenzialita>
		<tip:TipologiaDocumentoAlto>REF</tip:TipologiaDocumentoAlto>
		<tip:TipologiaDocumentoMedio>11488-4</tip:TipologiaDocumentoMedio>
		<tip:TipologiaDocumentoBasso>PDF</tip:TipologiaDocumentoBasso>
		<tip:IdentificativoDocumento>2.16.840.1.113883.2.9.2.150.4.4^476631</tip:IdentificativoDocumento>
		<tip:RiferimentoDocumento>urn:uuid:9269c688-4ca7-498d-adf6-25a08a5e7598</tip:RiferimentoDocumento>
		<tip:Associazione>
			<tip:associationType>urn:ihe:iti:2007:AssociationType:RPLC</tip:associationType>
			<tip:sourceObject>doc1</tip:sourceObject>
			<tip:targetObject>urn:uuid:9269c688-4ca7-498d-adf6-25a08a5e7598</tip:targetObject>
			<tip:submissionSetStatus>Original</tip:submissionSetStatus>
			<tip:previousVersion/>
		</tip:Associazione>
		<tip:IdentificativoUnivocoDocumento>doc1</tip:IdentificativoUnivocoDocumento>
		<tip:DataValidazioneDocumento>20240604162024</tip:DataValidazioneDocumento>
		<tip:RuoloAutore>DRS</tip:RuoloAutore>
		<tip:IstituzioneAutore>150201123456</tip:IstituzioneAutore>
		<tip:CodiceFiscaleAutore>PROVAX00X00X000Y</tip:CodiceFiscaleAutore>
		<tip:AssettoOrganizzativo>AD_PSC026</tip:AssettoOrganizzativo>
		<tip:TipoAttivitaClinica>DIS</tip:TipoAttivitaClinica>
		<tip:DataInizioPrestazione>20240604162024</tip:DataInizioPrestazione>
		<tip:DataFinePrestazione>20240604162024</tip:DataFinePrestazione>
	</com:Metadato>
	<com:IdentificativoApplicativoRichiedente>Ellipse AMB</com:IdentificativoApplicativoRichiedente>
	<com:FornitoreApplicativoRichiedente>Engineering Ingegneria Informatica S.p.A.</com:FornitoreApplicativoRichiedente>
	<com:VersioneApplicativoRichiedente>1.0.0</com:VersioneApplicativoRichiedente>
	<com:OpzioniRequest>
		<tip:chiave>GATEWAY</tip:chiave>
		<tip:valore>true</tip:valore>
	</com:OpzioniRequest>
	<com:OpzioniRequest>
		<tip:chiave>WORKFLOWINSTANCEID</tip:chiave>
		<tip:valore>2.16.840.1.113883.2.9.2.150.4.4.55184efbb4cff5f93cf83270e490cd17d5d2348a2d5f3066d891f7a24075ba60.d0fb648140^^^^urn:ihe:iti:xdw:2013:workflowInstanceId</tip:valore>
	</com:OpzioniRequest>
	<com:OpzioniRequest>
		<tip:chiave>MODE</tip:chiave>
		<tip:valore>ATTACHMENT</tip:valore>
	</com:OpzioniRequest>
</com:ComunicazioneMetadatiRichiesta>`

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
lato Friuli Venezia Giulia per il documento 2.16.840.1.113883.2.9.2.150.4.4^476631 abbiamo ricevuto una pubblicazione che è andata a buon fine il giorno 28-MAG-24 16:43:12 e poi una richiesta di query (senza errori) il giorno 05-GIU-24 11:38:05.
Non troviamo evidenza della replace.
Rimaniamo a disposizione per verifiche ulteriori e auguriamo una buona giornata.

**Comment by avlp** [comment]
La ricerca del 05-GIU-24 11:38:05 era appunto finalizzata alla valorizzazione della request riportata alla quale si riceve Internal Error

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno, 
lato FVG abbiamo eseguito ulteriori verifiche e non abbiamo proprio ricevuto la request per la replace. 
Abbiamo ricevuto solamente una richiesta di query a cui è stato risposto senza errore.
Credo che la issue richieda una verifica lato Sogei per la validazione della request inviata dalla Campania.
Ringraziando per la collaborazione auguriamo un buon pomeriggio.

**Comment by avlp** [comment]
Salve,
confermo quanto riportato da @ChiaraCeccottiFVG, il mio post precedente era indirizzato a Sogei non a FVG.

**Comment by avlp** [comment]
Appena riprovato, stesso errore

**Comment by avlp** [comment]
Riporto la request utilizzata per la ricerca (va a buon fine):
`<ric:RicercaDocumentiRichiesta xmlns:ric="http://ricercadocumentirichiesta.xsd.fse.ini.finanze.it">
	<ric:IdentificativoUtente>PROVAX00X00X000Y</ric:IdentificativoUtente>
	<ric:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</ric:pinCode>
		 
	<ric:IdentificativoOrganizzazione>150</ric:IdentificativoOrganizzazione>
	<ric:StrutturaUtente>201123456</ric:StrutturaUtente>
	<ric:RuoloUtente>DRS</ric:RuoloUtente>
	<ric:ContestoOperativo>UPDATE</ric:ContestoOperativo>
	<ric:IdentificativoAssistito>DLRGNN79C01F839O</ric:IdentificativoAssistito>
	<ric:PresaInCarico>true</ric:PresaInCarico>
	<ric:StatoDocumento>Approved</ric:StatoDocumento>
	<ric:IdentificativoDocumento>2.16.840.1.113883.2.9.2.150.4.4^476631</ric:IdentificativoDocumento>
	<ric:IdentificativoApplicativoRichiedente>Ellipse AMB</ric:IdentificativoApplicativoRichiedente>
	<ric:FornitoreApplicativoRichiedente>Engineering Ingegneria Informatica S.p.A.</ric:FornitoreApplicativoRichiedente>
	<ric:VersioneApplicativoRichiedente>1.0.0</ric:VersioneApplicativoRichiedente>
	<ric:OpzioniRisposta>ObjectRef</ric:OpzioniRisposta>
</ric:RicercaDocumentiRichiesta>`

e quella per la replace (in errore):

`<com:ComunicazioneMetadatiRichiesta xmlns:com="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it" xmlns:tip="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it">
	<com:IdentificativoUtente>PROVAX00X00X000Y</com:IdentificativoUtente>
		<com:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</com:pinCode>
	<com:IdentificativoOrganizzazione>150</com:IdentificativoOrganizzazione>
	<com:StrutturaUtente>201123456</com:StrutturaUtente>
	<com:RuoloUtente>DRS</com:RuoloUtente>
	<com:ContestoOperativo>TREATMENT</com:ContestoOperativo>
	<com:TipoDocumento/>
	<com:IdentificativoAssistito>DLRGNN79C01F839O</com:IdentificativoAssistito>
	<com:PresaInCarico>true</com:PresaInCarico>
	<com:TipoAttivita>CREATE</com:TipoAttivita>
	<com:Metadato>
		<tip:TipologiaStrutturaProdDoc>Ospedale</tip:TipologiaStrutturaProdDoc>
		<tip:TipoMime>application/pdf+text/x-cda-r2+xml</tip:TipoMime>
		<tip:LivelloConfidenzialita>N</tip:LivelloConfidenzialita>
		<tip:TipologiaDocumentoAlto>REF</tip:TipologiaDocumentoAlto>
		<tip:TipologiaDocumentoMedio>11488-4</tip:TipologiaDocumentoMedio>
		<tip:TipologiaDocumentoBasso>PDF</tip:TipologiaDocumentoBasso>
		<tip:IdentificativoDocumento>2.16.840.1.113883.2.9.2.150.4.4^476631</tip:IdentificativoDocumento>
		<tip:RiferimentoDocumento>urn:uuid:9269c688-4ca7-498d-adf6-25a08a5e7598</tip:RiferimentoDocumento>
			<tip:Associazione>
				<tip:associationType>urn:ihe:iti:2007:AssociationType:RPLC</tip:associationType>
				<tip:sourceObject>doc1</tip:sourceObject>
				<tip:targetObject>urn:uuid:9269c688-4ca7-498d-adf6-25a08a5e7598</tip:targetObject>
				<tip:submissionSetStatus>Original</tip:submissionSetStatus>
				<tip:previousVersion/>
            </tip:Associazione>
          <tip:IdentificativoUnivocoDocumento>doc1</tip:IdentificativoUnivocoDocumento>
		<tip:DataValidazioneDocumento>20240604162024</tip:DataValidazioneDocumento>
		<tip:RuoloAutore>DRS</tip:RuoloAutore>
		<tip:IstituzioneAutore>150201123456</tip:IstituzioneAutore>
			<tip:CodiceFiscaleAutore>PROVAX00X00X000Y</tip:CodiceFiscaleAutore>
		<tip:AssettoOrganizzativo>AD_PSC026</tip:AssettoOrganizzativo>
		<tip:TipoAttivitaClinica>DIS</tip:TipoAttivitaClinica>
		<tip:DataInizioPrestazione>20240604162024</tip:DataInizioPrestazione>
		<tip:DataFinePrestazione>20240604162024</tip:DataFinePrestazione>
	</com:Metadato>
	<com:IdentificativoApplicativoRichiedente>Ellipse AMB</com:IdentificativoApplicativoRichiedente>
	<com:FornitoreApplicativoRichiedente>Engineering Ingegneria Informatica S.p.A.</com:FornitoreApplicativoRichiedente>
	<com:VersioneApplicativoRichiedente>1.0.0</com:VersioneApplicativoRichiedente>
	<com:OpzioniRequest>
		<tip:chiave>GATEWAY</tip:chiave>
		<tip:valore>true</tip:valore>
	</com:OpzioniRequest>
		<com:OpzioniRequest>
			<tip:chiave>WORKFLOWINSTANCEID</tip:chiave>
			<tip:valore>2.16.840.1.113883.2.9.2.150.4.4.55184efbb4cff5f93cf83270e490cd17d5d2348a2d5f3066d891f7a24075ba60.d0fb648140^^^^urn:ihe:iti:xdw:2013:workflowInstanceId</tip:valore>
		</com:OpzioniRequest>
		<com:OpzioniRequest>
			<tip:chiave>MODE</tip:chiave>
			<tip:valore>ATTACHMENT</tip:valore>
		</com:OpzioniRequest>
</com:ComunicazioneMetadatiRichiesta>`

Il CF è lo stesso

**Comment by g-maugeri-sogei** [comment]
Correggo quanto scritto prima. Si trattava di un'altra request. La request inviata dal client INS della Campania va in errore su INS
perche' manca il tag
  <com:documento> "NOME_DOCUMENTO"</com:documento>

Aggiungendolo passa. Non riesco a chidere il giro perche' non ho il documento. Riprovate correggendo la request.
Se dovesse andare ancora in errore giratemi assieme alla request pure il documento della replace cosi' provo tutto il giro dalla mia macchina.

**Comment by avlp** [comment]
Visto che il validatore è posizionale, potrebbe indicare in quale punto aggiungere il tag?

**Comment by g-maugeri-sogei** [comment]
</com:Metadato>
         <com:documento>cid:ALE_130_LAST.pdf</com:documento>
		<com:IdentificativoApplicativoRichiedente>Middleware980</com:IdentificativoApplicativoRichiedente>

**Comment by avlp** [comment]
Da verifiche l'allegato viene inviato come richiesto (cid in tag documento). Riuscite ad intercettare la request?

**Comment by g-maugeri-sogei** [comment]
Nella request allegata sopra non c'e' il tag documento.
Avete fatto una nuova request? Se si mi date l'id temporaneo (codice TEMP_XXXX) ?
Aggiungo che il documento non riesco a recuperarlo dalla request quindi nel caso occorre che lo forniate voi.

**Comment by avlp** [comment]
Ecco la request inviata:
`<?xml version='1.0' encoding='UTF-8'?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
	<soapenv:Body>
		<com:ComunicazioneMetadatiRichiesta xmlns:com="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it" xmlns:tip="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it">
			<com:IdentificativoUtente>PROVAX00X00X000Y</com:IdentificativoUtente>
			<com:pinCode>LsQiYtf7FcpMYVKvf+51V6t1BSUk+E/dGOB2vmwNl0DhirZ8QzvTI2Ay04p6+t+eH+DjzkJpXrlEEZvKRz6wKVNOt7uYSQUYKBIFcbcEQJnqT7zTgtz7jV3BK+QaEphfKRsOP1Iejv+vKvJ/3te2xNMHPkNYZIAjxEQHftw9Swk=</com:pinCode>
			<com:IdentificativoOrganizzazione>150</com:IdentificativoOrganizzazione>
			<com:StrutturaUtente>201123456</com:StrutturaUtente>
			<com:RuoloUtente>DRS</com:RuoloUtente>
			<com:ContestoOperativo>TREATMENT</com:ContestoOperativo>
			<com:TipoDocumento/>
			<com:IdentificativoAssistito>DLRGNN79C01F839O</com:IdentificativoAssistito>
			<com:PresaInCarico>true</com:PresaInCarico>
			<com:TipoAttivita>CREATE</com:TipoAttivita>
			<com:Metadato>
				<tip:TipologiaStrutturaProdDoc>Ospedale</tip:TipologiaStrutturaProdDoc>
				<tip:TipoMime>application/pdf+text/x-cda-r2+xml</tip:TipoMime>
				<tip:LivelloConfidenzialita>N</tip:LivelloConfidenzialita>
				<tip:TipologiaDocumentoAlto>REF</tip:TipologiaDocumentoAlto>
				<tip:TipologiaDocumentoMedio>11488-4</tip:TipologiaDocumentoMedio>
				<tip:TipologiaDocumentoBasso>PDF</tip:TipologiaDocumentoBasso>
				<tip:IdentificativoDocumento>2.16.840.1.113883.2.9.2.150.4.4^476631</tip:IdentificativoDocumento>
				<tip:RiferimentoDocumento>urn:uuid:9269c688-4ca7-498d-adf6-25a08a5e7598</tip:RiferimentoDocumento>
				<tip:Associazione>
					<tip:associationType>urn:ihe:iti:2007:AssociationType:RPLC</tip:associationType>
					<tip:sourceObject>doc1</tip:sourceObject>
					<tip:targetObject>urn:uuid:9269c688-4ca7-498d-adf6-25a08a5e7598</tip:targetObject>
					<tip:submissionSetStatus>Original</tip:submissionSetStatus>
					<tip:previousVersion/>
				</tip:Associazione>
				<tip:IdentificativoUnivocoDocumento>doc1</tip:IdentificativoUnivocoDocumento>
				<tip:DataValidazioneDocumento>20240604162024</tip:DataValidazioneDocumento>
				<tip:RuoloAutore>DRS</tip:RuoloAutore>
				<tip:IstituzioneAutore>150201123456</tip:IstituzioneAutore>
				<tip:CodiceFiscaleAutore>PROVAX00X00X000Y</tip:CodiceFiscaleAutore>
				<tip:AssettoOrganizzativo>AD_PSC026</tip:AssettoOrganizzativo>
				<tip:TipoAttivitaClinica>DIS</tip:TipoAttivitaClinica>
				<tip:DataInizioPrestazione>20240604162024</tip:DataInizioPrestazione>
				<tip:DataFinePrestazione>20240604162024</tip:DataFinePrestazione>
			</com:Metadato>
			<com:documento>
				<xop:Include xmlns:xop="http://www.w3.org/2004/08/xop/include" href="cid:1.a64b8bc5224d748dbae01b986bc35f42e34b792234df59b0@apache.org"/>
			</com:documento>
			<com:IdentificativoApplicativoRichiedente>Ellipse AMB</com:IdentificativoApplicativoRichiedente>
			<com:FornitoreApplicativoRichiedente>Engineering Ingegneria Informatica S.p.A</com:FornitoreApplicativoRichiedente>
			<com:VersioneApplicativoRichiedente>1.0.0</com:VersioneApplicativoRichiedente>
			<com:OpzioniRequest>
				<tip:chiave>GATEWAY</tip:chiave>
				<tip:valore>true</tip:valore>
			</com:OpzioniRequest>
			<com:OpzioniRequest>
				<tip:chiave>WORKFLOWINSTANCEID</tip:chiave>
				<tip:valore>2.16.840.1.113883.2.9.2.150.4.4.55184efbb4cff5f93cf83270e490cd17d5d2348a2d5f3066d891f7a24075ba60.d0fb648140^^^^urn:ihe:iti:xdw:2013:workflowInstanceId</tip:valore>
			</com:OpzioniRequest>
			<com:OpzioniRequest>
				<tip:chiave>MODE</tip:chiave>
				<tip:valore>ATTACHMENT</tip:valore>
			</com:OpzioniRequest>
		</com:ComunicazioneMetadatiRichiesta>
	</soapenv:Body>
</soapenv:Envelope>`

**Comment by g-maugeri-sogei** [comment]
Fallisce l'unmarshalling sul tag:
 <com:documento>
            <xop:Include href="cid:1.a64b8bc5224rg/2004/08/xop/include"/>
         </com:documento>

Provate a modificarlo in:
     <com:documento>cid:NOME_FILE_DOCUMENTO</com:documento>

**Comment by avlp** [comment]
L'allegato viene inserito nelle stesse modalità con cui è stata inviato il documento da sostituire. Inoltre in ambiente di produzione il messaggio è identico. Riporto uno stralcio dal log di produzione di oggi presso il cliente Caserta:
[2024-06-06 14:49:29,318]   >> "</com:Metadato><com:documento><xop:Include xmlns:xop="http://www.w3.org/2004/08/xop/include" href="cid:1.acf68a235e371e0ee25a6e8fdaf87d545c98a0301824ea9d@apache.org"/></com:documento>"
(in questo caso acquisito con TEMP_150_1760504579)

**Comment by g-maugeri-sogei** [comment]
Potete aggiungere su questo form il documento che state usando?

**Comment by g-maugeri-sogei** [comment]
Ho provato a caricarlo usando SOAP-UI. Il documento viene caricato. Voi ricevete indietro l'id temporaneo (TEMP_XXXX) o vi fermate prima?
Aggiungo uno screenshot con i parametri che ho su SOAP-UI
![1](https://github.com/ministero-salute/it-fse-support/assets/120471888/fcf543ce-424b-4efb-8c80-be70dff158b4)

**Comment by avlp** [comment]
No dal log leggo: unexpected_message, non si ottiene il TEMP

**Comment by ChiaraCeccottiFVG** [comment]
Buongiorno,
se può essere utile come indicazione, lato FVG abbiamo ricevuto una pubblicazione corretta per il documento 2.16.840.1.113883.2.9.2.150.4.4^476631 il giorno 28-MAG-24 16:43:12. I metadati sono presenti nel nostro registry e lo stato è Approved.
Buona giornata.

**Comment by g-maugeri-sogei** [comment]
Oltre a quando chiesto prima chiedo alla Campania di fornirmi pure l'URL che utilizzano per chiamare il nostro WS, cosi cerco di capire che giro fa prima di arrivare all'application server.

**Comment by avlp** [comment]
https://fseservicetest.sanita.finanze.it/FseInsServicesWeb/services/fseComunicazioneMetadati

**Comment by g-maugeri-sogei** [comment]
La richiesta di replace viene respinta dal proxy per un errore di validazione.
Il problema e' la posizione del campo IdentificativoDocumento. In allegato il txt della replace con il campo nella posizione attesa.
Aggiungo che la request cosi' modificata passa i controlli di validazione, arriva all'application server ma va in errore perche'
la firma del documento in  allegato risulta non corretta.
Il documento che ho allegato e' quello che mi avete fornito sopra.
Provate a rifare un nuovo giro partendo dalla pubblicazione.
[replace.txt](https://github.com/user-attachments/files/15758869/replace.txt)

**Comment by avlp** [comment]
E' stato inviato un nuovo referto, TEMP_150_827512

**Comment by avlp** [comment]
Si è inviato un aggiornamento metadati, traceId: 0362c64b11faf72c

**Comment by ChiaraCeccottiFVG** [comment]
> E' stato inviato un nuovo referto, TEMP_150_827512, accettato con 2.16.840.1.113883.2.9.2.150.4.4^477704. Si procede con replace --> Inviate Replace TEMP_150_827517 esito positivo con 2.16.840.1.113883.2.9.2.150.4.4^477706 . Si chiede a @ChiaraCeccottiFVG conferma della sostituzione

Buonasera, confermiamo che il documento 2.16.840.1.113883.2.9.2.150.4.4^477706 ha correttamente sostituito il documento 2.16.840.1.113883.2.9.2.150.4.4^477704 (ora in stato Deprecated).
