### ISSUE TITLE
Errore chiamata servizio di validazione CDA

### ISSUE THREAD

**Issue by snewels** [ministero-salute/it-fse-support#872]
Buongiorno, 
da questa mattina otteniamo degli errori nella chiamata al servizio di validazione (url di test "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1").
L'eccezione è la seguente: "Il certificato remoto non è stato ritenuto valido dalla procedura di convalida."

Inoltre chiedo se è già disponibile l'url di produzione, non avendo i riferimenti del canale Slack.

**Comment by vigliottim** [comment]
Buongiorno,
stiamo registrando dei temporanei disservizi.
La invitiamo a monitorare il canale Slack per aggiornamenti.
Grazie.

**Comment by vigliottim** [comment]
Buon pomeriggio, i servizi sono stati ripristinati. Rimaniamo a disposizione nel caso l'intervento non fosse risolutivo. Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto. Grazie.

**Comment by snewels** [comment]
Buongiorno,
confermo risoluzione.

Grazie.
Sandro

Da: Michela Vigliotti ***@***.***>
Inviato: lunedì 3 giugno 2024 09:50
A: ministero-salute/it-fse-support ***@***.***>
Cc: Sandro Novelli ***@***.***>; Author ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Errore chiamata servizio di validazione CDA (Issue #872)

  CAUTION - This e-mail originates outside of Dedalus. Be vigilant with content, links and attachments!

Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto. Grazie.

-
