### ISSUE TITLE
RSA - richiesta di chiarimento su Identificativo dell’incontro

### ISSUE THREAD

**Issue by gfoini** [ministero-salute/it-fse-support#873]
Salve, la domanda è questa:
se in un documento RSA legato ad un ricovero compilo la sezione < 4.1.21.2.1 Identificativo del ricovero >
nel relativo tag id.Extension devo indicare il semplice numero di nosologico o l'eventuale <ID> del documento LDO prodotto nel relativo episodio di ricovero ?
Ovvero: l'eventuale identificativo crea un link automatico fra i 2 documenti RSA/LDO ?
grazie in anticipo per la risposta, buona giornata.

**Comment by LucaRogledi** [comment]
Buon pomeriggio, confermiamo che come riportato nel requisito di conformità 92 (CONF-RSA-92) del documento HL7 relativo alla tipologia documentale [RSA](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Standard%20documentali/HL7IT-IG_CDA2_RSA-v1.1-S.pdf), l'attributo `id/@extension` deve essere valorizzato con il codice nosologico. Grazie

**Comment by gfoini** [comment]
grazie

**Comment by Nicol290** [comment]
Posso  sapere se il codice identificativo di RSAnumero 638684 appartiene a Jessica Clini?

**Comment by vigliottim** [comment]
Buongiorno @Nicol290 ,
la invitiamo a rimuovere immediatamente dati sensibili.
Questo canale è dedicato all'ambiente di test, per richieste in ambiente di produzione la invitiamo a contattare fse_support@sogei.it
Grazie.
