### ISSUE TITLE
401 - TokenAuthenticationRequired

### ISSUE THREAD

**Issue by ub2012** [ministero-salute/it-fse-support#874]
Buongiorno,
provando ad invocare il servizio di validazione ricevo il seguente messaggio di errore:

{
    "type": "https://govway.org/handling-errors/401/TokenAuthenticationRequired.html",
    "title": "TokenAuthenticationRequired",
    "status": 401,
    "detail": "A token is required",
    "govway_id": "4d031c7c-21a3-11ef-8aa0-005056ae54fa"
}

Nella request sono presenti gli headers "Authorization" e "FSE_JWT_Signature" e mi sembrano correttamente valorizzati. Quale può essere il problema ?

**Comment by vigliottim** [comment]
Buon pomeriggio,
l'errore ricevuto potrebbe essere causato dall'errata valorizzazione del nome del parametro dell'header contenente il token JWT. Infatti, esso risulta essere **FSE_JWT_Signature** ma, come riportato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#51-request), il nome corretto è: **FSE-JWT-Signature**. 
La preghiamo di effettuare la correzione suggerita e riprovare.
Restiamo in attesa di un suo gentile riscontro.
Grazie.

**Comment by ub2012** [comment]
Salve, sì l'errore era causato da questo, grazie.

Adesso però riceviamo un nuovo errore TokenAuthenticationFailed:

`{
    "type": "https://govway.org/handling-errors/401/TokenAuthenticationFailed.html",
    "title": "TokenAuthenticationFailed",
    "status": 401,
    "detail": "Invalid token",
    "govway_id":"0b4e298c-21ba-11ef-8aa0-005056ae54fa"
}`

**Comment by LucaRogledi** [comment]
Buonasera, l'errore riportato sembrerebbe essere dovuto dall'utilizzo di una firma non valida per i token "Authorization" e "FSE-JWT-Signature". Copiando infatti i token su [jwt.io](https://jwt.io/), compare la dicitura "Invalid Signature". 

![image](https://github.com/ministero-salute/it-fse-support/assets/139234602/9ab084af-0846-4bb5-beed-c31d074ddc49)

La invitiamo a generare nuovamente i token utilizzando un valore valido per il campo "x5c" e riprovare la chiamata dopo aver verificato la validità della firma su [jwt.io](https://jwt.io/).
Il certificato corretto da utilizzare per la firma è il certificato S1#... e se può esserle di aiuto è disponibile al seguente link il tool per la generazione dei token jwt: https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator.
Rimaniamo a disposizione per eventuali chiarimenti.
Grazie.

**Comment by ub2012** [comment]
Salve, abbiamo corretto l'errore, grazie. Adesso ricevo il seguente errore:

{
    "type": "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
    "title": "AuthorizationContentDeny",
    "status": 403,
    "detail": "Unauthorized request content",
    "govway_id":"b1d5e545-225e-11ef-a6bf-005056ae7395"
}

Può essere causato dal fatto che il documento inviato non è firmato ?

**Comment by ub2012** [comment]
Ok, adesso il problema è risolto.

Grazie.
