### ISSUE TITLE
CDA completi per LAB

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#877]
Buongiorno,
per ovvie ragioni di praticità utilizziamo gli esempi Xml per creare le classi base per poi implementare le varie tipologie di referto. Abbiamo notato, però, che il vostro esempio per la tipologia LAB, oltre a non essere utilizzabile, come da voi indicato, è incompleto e quindi non fruibile. Ovviamente potremmo scriverci le classi a mano, ma sarebbe auspicabile che esistesse un esempio completo, a livello di tag, section e quant'altro da poter utilizzare come schema. Purtroppo gli schemi xsd non sono adatti allo scopo.
Esiste quanto chiediamo?
Grazie mille.

**Comment by vigliottim** [comment]
Buongiorno, non sono presenti esempi completi di CDA2 di tipo LAB utilizzabili ai fini dell'accreditamento. 
Dovrà strutturare i file XML in autonomia, facendo riferimento alle specifiche contenute nei [file excel relativi](https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case/Validazione/5-Referto%20di%20Medicina%20di%20Laboratorio). Grazie.

**Comment by infoserviceonline** [comment]
Ovviamente i file a cui fate riferimento, che ho utilizzato finora per implementare i test, sono validi SOLO per i test a cui si riferiscono, immagino, ma correggetemi se sbaglio, di dover sempre far riferimento al pdf allegato, ammesso che sia sempre valido. Peccato che presenti alcune lacune che spero colmerete se necessario.
Grazie.
[HL7IT-IG_CDA2_RefertoMedicinaLab-v1.3-S.pdf](https://github.com/user-attachments/files/15584751/HL7IT-IG_CDA2_RefertoMedicinaLab-v1.3-S.pdf)

**Comment by vigliottim** [comment]
Il pdf da lei allegato contiene le linee guida HL7 Italia. L'accreditamento prevede controlli più stringenti rispetto a quelli contenuti in tale documento. Per cui, dovrà far riferimento all'excel riportato nel nostro commento precedente per eseguire correttamente i test case. 
Grazie.

**Comment by infoserviceonline** [comment]
Ok, grazie. Chiudo
