### ISSUE TITLE
Errore asincrono durante la pubblicazione

### ISSUE THREAD

**Issue by kelldc** [ministero-salute/it-fse-support#879]
Buongiorno,
verificando lo stato di una pubblicazione, ho riscontrato un errore nella fase "EDS_WORKFLOW" con il seguente errore "Assicurarsi che le risorse CDA rappresentanti Persone, Strutture e Location abbiano il campo 'id' valorizzato". Ho verificato la presenza del campo ID, come indicato nel ticket #514, su tutti gli elementi che riguardano persone, strutture o location.
C'è modo di sapere, più nel dettaglio, a cosa è dovuto l'errore?

Allego, per comodità, la risposta del servizio di pubblicazione (invio.json), di check(status.json) e il pdf che è stato inviato.

[invio.json](https://github.com/user-attachments/files/15759289/invio.json)
[Referto_n_59_del_10Giu2024.pdf](https://github.com/user-attachments/files/15759291/Referto_n_59_del_10Giu2024.pdf)
[status.json](https://github.com/user-attachments/files/15759292/status.json)

**Comment by LucaRogledi** [comment]
Buongiorno, attualmente si sta lavorando su un aggiornamento risolutivo per queste tipologie di issue. 
Dopo un controllo effettuato sul CDA2 abbiamo notato che mancano gli ID degli elementi `healthCareFacility` e `serviceProviderOrganization`, si consiglia di aggiungere questi dettagli per evitare l'errore in attesa che venga ultimata la soluzione individuata. 
Restiamo a disposizione per ulteriore supporto.
Grazie.

**Comment by kelldc** [comment]
Buongiorno,
si, effettivamente l'errore era dovuto alla mancanza dei due elementi da lei indicati. Non essendo obbligatori nella documentazione e avendo superato la validazione, non mi era venuto in mente di controllarli.
Il problema risulta risolto, chiudo il ticket.

La ringrazio per la disponibilità
