### ISSUE TITLE
Errore422 VALIDAZIONE_CDA2_SING_VAC_CT3

### ISSUE THREAD

**Issue by cm-sispc** [ministero-salute/it-fse-support#88]
Test Case VALIDAZIONE_CDA2_SING_VAC_CT3 (caso di esonero)
Riscontriamo il seguente errore semantico:
```
{
 "traceID": "9b394b9d0e859b64",
 "spanID": "9b394b9d0e859b64",
 "type": "/msg/semantic",
 "title": "Errore semantico.",
 "detail": "[ERRORE-b12|Lelemento entry/substanceAdministration/templateId[@root2.16.840.1.113883.2.9.10.1.11.4.1] se presente, DEVE contenere lelemento consumable/manufacturedProduct/manufacturedMaterial/code valorizzato secondo i seguenti sistemi di codifica: @codeSystem 2.16.840.1.113883.2.9.6.1.5 (AIC)]",
 "status": 422,
 "instance": "/validation/error",
 "workflowInstanceId": "2.16.840.1.113883.2.9.2.90.4.4.0c2580e2b4dc0966bdd358ee6a8f9441cb756a5275ca2940713fec573e9cfa45.233ed86398^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```

Ci risulta che il substanceAdministration/templateId@root  non sia quello segnalato, ma piuttosto: 2.16.840.1.113883.2.9.10.1.11.4.2 relativo all'esonero.
Inoltre il tag indicato come mancante:
`ClinicalDocument/component/structuredBody/component/section[@ID = Singola_Vaccinazione]/entry/substanceAdministration/consumable/manufacturedProduct/manufacturedMaterial/code`

risulta opzionale da file di riepilogo dei TC: CDA2_Scheda_Singola Vaccinazione_OK.xlsx
Non riusciamo a completare questo TC, ci potete indicare cosa sbagliamo?

**Comment by Ser-ena** [comment]
Buonasera, grazie della segnalazione. Si conferma che l'elemento code è opzionale nel caso di Esonero/omissione o differimento, per cui verrà effettuata una modifica sul controllo.

**Comment by IStacchiotti** [comment]
Salve, le comunichiamo che a questo [link]([schematron_certificato_VACC.sch](https://github.com/ministero-salute/it-fse-support/blob/main/validazione/schematron/schematron_certificato_VACC.sch)), sono stati appena caricati gli schematron aggiornati, a correzione del bug segnalato. Grazie

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
