### ISSUE TITLE
info - Servizio di Sostituzione Documento

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#880]
Buongiorno, dalle specifiche vedo che occorre validare un documento prima della validazione.
Vale la stessa cosa per l'aggiornamento, indicando i valori workflowInstanceId (requestBody) e attachment_hash (jwt) ?

**Comment by ds-tommaso** [comment]
Approfitto del thread per comprendere l'errore [ERRORE 8| Se ClinicalDocument.id e ClinicalDocument.setId usano lo stesso dominio di identificazione (@root identico) allora l’attributo @extension del\n\t\t\tClinicalDocument.id deve essere diverso da quello del ClinicalDocument.setId a meno che ClinicalDocument.versionNumber non sia uguale ad 1; cioè i valori del setId ed id per un documento clinico coincidono solo per la prima versione di un documento.]".

**Premessa**
L'indentificativo del Cda è dato dalla combinazione di [struttura] + [id] + [versione]
Dato il referto "0", avrò nel corso del tempo i valori 120200463600_0T1V1, 120200463600_0T1V2, 120200463600_0T1V3 ecc.

Alla prima versione, il cda sarà così composto:

```
<id root="2.16.840.1.113883.2.9.2.120.4.4" extension="120200463600_0T1V1" assigningAuthorityName="Regione Sicilia"/>
<setId root="2.16.840.1.113883.2.9.2.120.4.4" extension="120200463600_0T1V1" assigningAuthorityName="Regione Sicilia"/>
```

Alla seconda versione, il cda sarà composto come di seguito.
A differenza della prima versione, aggiungo relatedDocument, indicando id 120200463600_0T1V1, setId 120200463600_0T1V1 e versione 2)

```
<id root="2.16.840.1.113883.2.9.2.120.4.4" extension="120200463600_0T1V2" assigningAuthorityName="Regione Sicilia"/>
<setId root="2.16.840.1.113883.2.9.2.120.4.4" extension="120200463600_0T1V1" assigningAuthorityName="Regione Sicilia"/>
<relatedDocument typeCode="RPLC">
	<parentDocument>
		<id root="2.16.840.1.113883.2.9.2.120.4.4" extension="120200463600_0T1V1"/>
		<setId root="2.16.840.1.113883.2.9.2.120.4.4" extension="120200463600_0T1V1"/>
		<versionNumber value="2"/>
	</parentDocument>
</relatedDocument>

```

Alla terza versione, il cda sarà composto come di seguito.
A differenza della seconda versione, relatedDocument vedrà l'id 120200463600_0T1V2 e nuova versione 3 (setId è sempre uguale).
```
<id root="2.16.840.1.113883.2.9.2.120.4.4" extension="120200463600_0T1V2" assigningAuthorityName="Regione Sicilia"/>
<setId root="2.16.840.1.113883.2.9.2.120.4.4" extension="120200463600_0T1V1" assigningAuthorityName="Regione Sicilia"/>
<relatedDocument typeCode="RPLC">
	<parentDocument>
		<id root="2.16.840.1.113883.2.9.2.120.4.4" extension="120200463600_0T1V2"/>
		<setId root="2.16.840.1.113883.2.9.2.120.4.4" extension="120200463600_0T1V1"/>
		<versionNumber value="3"/>
	</parentDocument>
</relatedDocument>

```

[T1V2_CDA.xml.txt](https://github.com/user-attachments/files/15803371/T1V2_CDA.xml.txt)
[T1V2_validationCDA_res.json](https://github.com/user-attachments/files/15803372/T1V2_validationCDA_res.json)

**Comment by ds-tommaso** [comment]
risolto, grazie sempre

**Comment by vigliottim** [comment]
Buon pomeriggio, 
Le confermiamo che occorre effettuare una validazione del documento sostituente prima della chiamata al servizio di sostituzione.
Come riportato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#6-servizio-di-sostituzione-documento), non è richiesto il _workflowInstanceId_ ricevuto dalla validazione all'inteno della _requestBody_ dell'API di sostituzione, mentre è necessario valorizzare il correttamente il campo _attachment_hash_ del token JWT. 
Inoltre, si precisa che l'elemento che identifica le versioni successive del documento è il _ClinicalDocument/versionNumber_. Mentre _ClinicalDocument/relatedDocument/parentDocument/versionNumber_, invece, identifica la versione del documento che è stata sostituita, ovvero del documento padre.
Inoltre, si segnala che l'elemento _relatedDocument_ è opzionale alla prima versione del documento (_ClinicalDocument/versionNumber=1_) mentre obbligatoria nella versioni successive.
Restiamo a disposizione per eventuali chiarimenti.
