### ISSUE TITLE
Errore di sintassi

### ISSUE THREAD

**Issue by ub2012** [ministero-salute/it-fse-support#882]
Buongiorno,
provando ad invocare il servizio di validazione ricevo il seguente messaggio di errore che non mi risulta chiaro:

{
    "traceID": "ac767b2b488183e5",
    "spanID": "ac767b2b488183e5",
    "type": "/msg/syntax",
    "title": "Errore di sintassi.",
    "detail": "ERROR: -1,-1 cvc-complex-type.2.4.a: Invalid content was found starting with element 'addr'. One of '{"urn:hl7-org:v3":providerOrganization}' is expected.",
    "status": 400,
    "instance": "/validation/error",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.30.4.4.c5351c7c76069c7bebbcf0b890b2e8c8edbfdd3bdfb937564e3684e51224b6d2.e5e5f08491^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

**Comment by LucaRogledi** [comment]
Buongiorno, potrebbe gentilmente allegare il pdf utilizzato per la chiamata di validazione? Grazie

**Comment by ub2012** [comment]
Buongiorno, eccolo.
[injected.pdf](https://github.com/user-attachments/files/15816611/injected.pdf)

**Comment by vigliottim** [comment]
Buongiorno, la struttura del CDA2 fornito non risulta corretta. In particolare, il tag <addr>, che è opzionale e ed è utilizzato per codificare l’indirizzo del paziente, deve rispettare le regole definite nella guida HL7 Italia sia in termini di posizionamento che contenuto (https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Standard%20documentali/HL7IT-IG_CDA2_LDO-v1.2-S.pdf, pag 36-37).
Le riportiamo di seguito un esempio di implementazione che può esserle d'aiuto: 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/7f7ad427-a5ff-4cef-8f1e-5a8ea2698f5b)
Inoltre, le facciamo presente che il tag _<assignedAuthor>_ deve contenere almeno tre elementi _<telecom>_ in cui sono riportati i riferimenti (e-mail; PEC; telefono) necessari per contattare l’autore.
Rimaniamo a disposizione per ulteriori dubbi.

**Comment by ub2012** [comment]
Ok, grazie. Adesso ricevo questo:

{
    "traceID": "dca703e77db62faa",
    "spanID": "dca703e77db62faa",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.30.4.4.c5351c7c76069c7bebbcf0b890b2e8c8edbfdd3bdfb937564e3684e51224b6d2.18697fefc5^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Vuol dire che il cda2 è valido ?

**Comment by vigliottim** [comment]
Buongiorno,
le confermiamo che il cda2 ha superato la validazione con successo. 
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
