### ISSUE TITLE
Errore validazione RSA non chiaro

### ISSUE THREAD

**Issue by BiMind** [ministero-salute/it-fse-support#883]
Buonasera,
Stiamo validando un documento RSA, ma riceviamo questo errore dal gateway che non riusciamo a capire

`{"traceID":"0292d03829f1dc86","spanID":"0292d03829f1dc86","type":"/msg/syntax","title":"Errore di sintassi.","detail":"ERROR: -1,-1 cvc-minLength-valid: Value '' with length = '0' is not facet-valid with respect to minLength '1' for type 'st'.,ERROR: -1,-1 cvc-attribute.3: The value '' of attribute 'assigningAuthorityName' on element 'id' is not valid with respect to its type, 'st'.,ERROR: -1,-1 cvc-datatype-valid.1.2.3: '' is not a valid value of union type 'uid'.,ERROR: -1,-1 cvc-attribute.3: The value '' of attribute 'root' on element 'id' is not valid with respect to its type, 'uid'.,ERROR: -1,-1 cvc-minLength-valid: Value '' with length = '0' is not facet-valid with respect to minLength '1' for type 'st'.,ERROR: -1,-1 cvc-attribute.3: The value '' of attribute 'assigningAuthorityName' on element 'setId' is not valid with respect to its type, 'st'.,ERROR: -1,-1 cvc-datatype-valid.1.2.3: '' is not a valid value of union type 'uid'.,ERROR: -1,-1 cvc-attribute.3: The value '' of attribute 'root' on element 'setId' is not valid with respect to its type, 'uid'.,ERROR: -1,-1 cvc-complex-type.2.4.b: The content of element 'act' is not complete. One of '{\"urn:hl7-org:v3\":realmCode, \"urn:hl7-org:v3\":typeId, \"urn:hl7-org:v3\":templateId, \"urn:hl7-org:v3\":id, \"urn:hl7-org:v3\":code}' is expected.","status":400,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.110.4.4.b9c6730668cc0de40d7aa7bade6c1520d9a0d1a7e81c5c945a245174066abe8b.443f050480^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

Alleghiamo il file usato per la validazione.
[RSATest.pdf](https://github.com/user-attachments/files/15822117/RSATest.pdf)

**Comment by vigliottim** [comment]
Buonasera, potrebbe cortesemente allegare il file xml contenente il CDA2 utilizzato? Grazie.

**Comment by BiMind** [comment]
In allegato

[cda2RSATest.txt](https://github.com/user-attachments/files/15822473/cda2RSATest.txt)

Grazie per il supporto

**Comment by vigliottim** [comment]
Buonasera, 
dalle analisi svolte è emerso che il cda da lei utilizzato per chiamare il servizio di validazione presenta alcune sezioni non correttamente compilate. 

In particolare:
1. Gli attributi evidenziati in figura, obbligatori secondo le linee guida HL7 Italia, non sono stati valorizzati: 
<img width="455" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/57ee67d3-6125-46bb-a356-fc4945c7e3a7">

2. L'elemento _act_ non è stato strutturato correttamente: 
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/751864b0-3126-43bb-8768-0ba0824dc51e)
La invitiamo a consultare l'implementation guide HL7 Italia relativa a RSA, disponibile al link [HL7RSA](https://www.hl7.it/realm-italiano/referto-di-specialistica-ambulatoriale-rsa/), e ad avvalersi dell'esempio presente in documentazione: [RSA.xml](https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/RSA.xml)

Le chiediamo di effettuare le correzioni riportate e riprovare. Grazie.

**Comment by BiMind** [comment]
Grazie, la mancanza dei dati era dovuta a un errore di configurazione del nostro applicativo.
Abbiamo corretto la configurazione e ora il documento viene correttamente validato da parte del gateway.
