### ISSUE TITLE
certificato - password errata

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#884]
Buongiorno, una domanda sui certificati, forse insolita.

Dalla coppia csr / key, ho creato il certificato .p12 con il comando OpenSSL (in calce).
Da me, posso utilizzare il certificato tramite programma o, banalmente, riesco ad installarlo sul mio pc.
Stesso certificato, copiato su altri pc rileva l'errore "Password errata".

L'errore si presenta anche quando il certificato è creato direttamente sulla macchina del cliente.
Da lui ottengo 'Password errata'; tutto ok quando copio da me quello stesso certificato.

Lo stesso comportamento si presenta con le chiavi di LazioCrea.
Faccio presente che l'errore mi capita su **alcune** macchine WIN-Server (non ho problemi - per quello che posso constatare - su OS Windows non server).

Di seguito, il comando che utilizzo e - se può essere utile - il certificato .p12 incriminato.
L'ho generato diverse volte, anche nel formato pfx. Con e senza password; con password più o meno complesse,

`openssl pkcs12 -export -out ID120200_00987654321.p12 -inkey FSECOLL_ID120200_00987654321.key -in ID120200_00987654321.crt`

**Comment by LucaRogledi** [comment]
Buongiorno, per la generazione del certificato `.p12` tramite comando `openssl` suggeriamo l'utilizzo del file `.pem` all'interno del parametro di ingresso `-in`, come indicato nel commento della [issue 591](https://github.com/ministero-salute/it-fse-support/issues/591#issuecomment-1923419907). 

`openssl pkcs12 -export -name alias_cert -out client_sign.p12 -inkey client_sign.key -in client_sign.pem`  

La invitiamo a riprovare e restiamo a disposizione in caso il problema dovesse ripresentarsi.
Grazie

**Comment by ds-tommaso** [comment]
mm no, purtroppo non va... ho provato con la coppia A1_111DATASOFTWARE csr/key che mi avete girato in passato.

L'errore di 'password errata' si presenta quando creo da loro il certificato...

(ERR) pc server cliente, win server 2016, open ssl 3.3.1.4
![mioPc - winServer 2016 - bis](https://github.com/ministero-salute/it-fse-support/assets/58989593/76780974-6040-457b-9d29-da741ac41f27)

... e quando inoltro quello creato sul mio

(OK) mio pc, win 11, openssl v. 3.0.8.7
![Screenshot 2024-06-14 170506](https://github.com/ministero-salute/it-fse-support/assets/58989593/4c9978cf-50f9-476c-8030-a93fb103a9a6)

(ERR) pc server, win 2012 r2, openssl v. 3.0.8.7
![Screenshot 2024-06-14 170547](https://github.com/ministero-salute/it-fse-support/assets/58989593/0747ddf8-9178-4c3a-a764-71d9fbe00087)

(ERR) pc server cliente, win server 2016, open ssl 3.3.1.4
![mioPc - winServer 2016](https://github.com/ministero-salute/it-fse-support/assets/58989593/d4883384-da01-46ad-accb-129a8ca33bb4)

**Comment by ds-tommaso** [comment]
sono a precisare che il comando 'openssl pkcs12 -in client_sign.p12 -nodes' funziona su tutti i pc
dopo la password (1234), vedo gli attributi bag e key.

solo il doppio click non va ma questo pregiudica la mia applicazione

**Comment by LucaRogledi** [comment]
Buongiorno, 
Una volta generati i file .p12 funzionanti sulla macchina locale tramite .pem, Le chiederemmo gentilmente una verifica inviando direttamente questi certificati .p12 e .pem tramite archivio criptato per questioni di sicurezza ai WIN-Server in questione effettuando una prova utilizzandoli per una chiamata.
La invitiamo anche a rimuovere i file dei certificati e le informazioni riservate dalla presente segnalazione.
Grazie.

**Comment by ds-tommaso** [comment]
purtroppo no, non va...

ho copiato nella cartella c:\temp i file pem e key quindi creato il p12.
Ho poi creato il file zip, protetto da password, che contiene tutto (pem, key, p12). Estratto l'archivio, trovo sempre il messaggio 'la password immessa non è corretta'.

Posso pubblicare qui lo zip e volete provare voi la generazione? sarei disponibile anche per una teleassistenza

**Comment by LucaRogledi** [comment]
Non avendo modo di effettuare teleassistenza e troubleshooting su WIN Server La invitiamo gentilmente ad aprire un post su Slack rivolto alla community, nel caso un altro utente abbia riscontrato la medesima anomalia.
Grazie.
