### ISSUE TITLE
Error while extracting CDA from PDF document under validation

### ISSUE THREAD

**Issue by mimma81** [ministero-salute/it-fse-support#885]
Buingiorno,
in fase di validazione dei nostri pdf otteniamo questo errore:
Gateway response body: {"traceID":"1f1324fbb8c36c5a",
"spanID":"1f1324fbb8c36c5a",
"type":"/msg/cda-element",
"title":"Errore in fase di estrazione del CDA.",
"detail":"Error while extracting CDA from PDF document",
"status":400,"instance":"/cda-extraction",
"workflowInstanceId":"UNKNOWN_WORKFLOW_ID"}

lo stesso pdf con Adobe Reader il CDA viene correttamente estratto
in allegato il pdf utilizzato.

potreste gentilmente dirmi quel è il problema?

grazie
Mimma
[aaaaa.pdf](https://github.com/user-attachments/files/15836790/aaaaa.pdf)

**Comment by vigliottim** [comment]
Buon pomeriggio, 
dalle analisi svolte sulla chiamata da lei effettuata è emerso che il seguente parametro presente nella _requestBody_ non è stato valorizzato correttamente:
_As is:_ `Content-Type: application/octet-stream `
_To be:_ `Content-Type: application/pdf`
Le chiediamo di applicare la correzione suggerita e riprovare. 
Grazie.

**Comment by mimma81** [comment]
Buon Pomeriggio, 
stavamo facendo delle ulteriori verifiche e la cosa che non è chiara è come mai utilizzando un altro file (che allego) il problema non si presenta.
Viene utilizzata la stessa trasmissione, quindi sembra un problema non legato al Content-Type del requestbody ma al file, 
tuttavia il file verificando l'attachment sembra coerente.
come mai abbiamo un comportamento diverso utilizzando la stessa identica chiamata?
Ecco la risposta del Gateway con questo file: 
 Gateway response body: {"traceID":"971bddbd389ad615","spanID":"971bddbd389ad615","workflowInstanceId":"2.16.840.1.113883.1.2.3.4.5.6c2cd061101ced390ac1a0bc1ce83e54b32e4266a94c86e78345b2b72fed13a8.c3a971fe48^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","warning":"[W005 | Sezione Esame Eseguito: l'entry/act/code può essere valorizzato secondo i sistemi di codifica\n\t\t\tLOINC @codeSystem='2.16.840.1.113883.6.1'\n\t\t\tICD-9-CM @codeSystem='2.16.840.1.113883.6.103']"}
[822ConCda.pdf](https://github.com/user-attachments/files/15840748/822ConCda.pdf)
Grazie

**Comment by vigliottim** [comment]
Buonasera, potrebbe dirci se state utilizzando il tool [pdf generator](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/pdf-generator) per iniettare il CDA2 all'interno di un pdf? Grazie.

**Comment by mimma81** [comment]
Buongiorno,
in realtà il cda2 non viene allegato al documento manualmente ma viene fatto da un applicativo che utilizza la libreria Apache PDFBox.
E aprendo il pdf con Adobe il documento sembra conferme allo standard e il cda2 è perfettamente allegato.
Grazie

**Comment by vigliottim** [comment]
Buongiorno,
non avendo modo di effettuare operazioni di debug su librerie esterne, la invitiamo ad utilizzare il tool [pdf generator](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/pdf-generator) messo a disposizione e informarci se il problema persiste.
In alternativa, la invitiamo ad aprire un post su Slack rivolto alla community, nel caso un altro utente abbia riscontrato la medesima anomalia.
Grazie.
