### ISSUE TITLE
Problemi con la "Pull Request"

### ISSUE THREAD

**Issue by dampgithub** [ministero-salute/it-fse-support#886]
GATEWAY/A1#111#DAMPSOFTWAREXXX/DAMP sas/DAMP - Volare FSE - LIS - RSA/Ver. 02.00/

Buongiorno, seguendo passo passo l'iter da voi fornito, appena e cerco di aprire la PULL REQUEST mi da il messaggio di errore (Pull request creation failed. Validation failed: must be a collaborator) ...non è che è dato dal problema che è sorto in fase di censimento software house?

Good morning, following the steps you provided, as soon as I try to open the PULL REQUEST, I get the error message (Pull request creation failed. Validation failed: must be a collaborator)... Could this be caused by the issue that arose during the software house registration phase?

**Comment by vigliottim** [comment]
Buongiorno, la invitiamo a consultare le istruzioni riportate nei commenti seguenti per verificare se la procedura è stata correttaemmte eseguita:

- Esecuzione fork e commit:
https://github.com/ministero-salute/it-fse-support/issues/853#issuecomment-2124107085

- Pull request:
https://github.com/ministero-salute/it-fse-support/issues/695#issuecomment-2022834466

Rimaniamo a disposizione nel caso il problema dovesse ripresentarsi.
Grazie.

**Comment by dampgithub** [comment]
Buonasera, abbiamo seguito la procedura correttamente, potete confermare che è andato a buon fine?
rimango in attesa..
saluti
grazie

**Comment by vigliottim** [comment]
Buongiorno,
La informiamo che la pull request [1520](https://github.com/ministero-salute/it-fse-accreditamento/pull/1520)
è stata correttamente creata.
Tuttavia, la cartella creata non ha la struttura indicata in documentazione e non risulta completa di tutti i file.
La invitiamo ad effettuare una verifica seguendo le istruzioni riportate in documentazione al link:
https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#accreditamento-fse-20-draft. 
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, 
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Potrà riaprirla nel caso in cui avesse bisogno di ulteriore supporto.
Grazie.

**Comment by dampgithub** [comment]
Buonasera, non riesco a creare le cartelle dentro GATEWAY/
devo creare:
A1#111#DAMPSOFTWAREXXX/DAMP sas/DAMP - Volare FSE - LIS - RSA/Ver. 02.00, non trovo le specifiche tecniche per creare la struttura..
Grazie

**Comment by vigliottim** [comment]
> Buonasera, non riesco a creare le cartelle dentro GATEWAY/ devo creare: A1#111#DAMPSOFTWAREXXX/DAMP sas/DAMP - Volare FSE - LIS - RSA/Ver. 02.00, non trovo le specifiche tecniche per creare la struttura.. Grazie

Buonasera, risponderemo alla sua domanda nell'issue da lei creata: #904. Grazie.
