### ISSUE TITLE
fse-gateway - Errore 401  Unauthorized 

### ISSUE THREAD

**Issue by fsemelograno** [ministero-salute/it-fse-support#889]
Siamo fornitori di due strutture in Campania, accreditati per la fase di validazione FSE 2.0 con i seguenti riferimenti

    Fornitore: IL MELOGRANO DATA SERVICES
    Applicativi / versioni: 

        FSE-VPS / 1.0
        FSE-RAD / 1.0
        FSE-RSA / 1.0
        FSE-LDO / 1.0

Da diversi mesi inviamo al FSE documenti PDF con Cda2 Injected, secondo le direttive previste dal “crash program FSE 2.0” che vede coinvolta la Campania come una delle regione pilota.

Dalla mezzanotte di oggi,  ogni tentativo di verifica/validazione dei documenti tramite il Gateway FSE restituisce un errore 401 - Unhauthorized come nel seguente estratto di log:

2024-06-19 09:33:22,709 1711224796 [http-nio-8080-exec-8] DEBUG i.m.f.g.a.c.DocumentValidationClient - [DocumentValidationClient#validateDocument] ---> POST https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation HTTP/1.1

2024-06-19 09:33:23,000 1711225087 [http-nio-8080-exec-8] DEBUG i.m.f.g.a.c.DocumentValidationClient - [DocumentValidationClient#validateDocument] <--- HTTP/1.1 401 Unauthorized (290ms)

2024-06-19 09:33:23,001 1711225088 [http-nio-8080-exec-8] WARN  i.m.f.g.adapter.services.MyService -
feign.FeignException$Unauthorized: [401 Unauthorized] during [POST] to [https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation] [DocumentValidationClient#validateDocument(String,String,String,ValidationCDAReqDTO,MultipartFile)]: []

Per l'autenticazione e la signature, utilizziamo i certificati che ci sono stati consegnati il 21 Maggio scorso. 
I certificati sono comunque validi fino al 2026.

Potete aiutarci a capire l'origine del problema? Sul nostro fronte non abbiamo altre indicazioni specifiche sul problema di autorizzazione.

grazie per l'assistenza

**Comment by vigliottim** [comment]
Buongiorno, come comunicato sul canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM), stiamo registrando dei temporanei disservizi. Seguiranno aggiornamenti. Grazie.

**Comment by vigliottim** [comment]
Buonasera, i servizi sono stati ripristinati. 
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
Grazie.
