### ISSUE TITLE
Validazione Documento Errore 502 InvalidResponse

### ISSUE THREAD

**Issue by andreasantori** [ministero-salute/it-fse-support#89]
Buonasera,
ho inviato una richiesta di validazione di un documento ed ottengo il seguente messaggio di errore:
{
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "status": 502,
    "detail": "Invalid response received from the API Implementation",
    "govway_id": "87b87c2a-a3c6-11ed-84b0-005056ae7395"
}

i token JWT li ho ottenuti utilizzato il toolkit messo a disposizione da fse-support.

Potete verificare?
Grazie,
Andrea Santori

**Comment by andreasantori** [comment]
Buongiorno,
non riscontro più il problema evidenziato, forse era dovuto al fatto che con postman nella transazione non avevo specificato il file pdf.
Adesso ottengo il seguente errore (che mi fa intuire che il cda iniettato viene sbustato ed analizzato):

{
    "traceID": "daf5fd529b15758f",
    "spanID": "daf5fd529b15758f",
    "type": "/msg/vocabulary",
    "title": "Errore vocabolario.",
    "detail": "È stata trovata almeno una versione non gestita di un dizionario: [2.16.840.1.113883.6.1 v2.64]",
    "status": 400,
    "instance": "/validation/error",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.50502.4.4.17.f46284e7db23742c39bf3e0dffa54b2cc0edcd21fcdb555a313b3f4a191d4e72.43439fcb4a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

il problema dovrebbe essere dovuto alla valorizzazione dell'attributo codeSystemVersion (che abbiamo impostato a 2.64) nelle varie sezioni come ad esempio
<code code="30954-2" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" codeSystemVersion="2.64" displayName="Test diagnostici &amp;o dati di laboratorio rilevanti" />

Si può omettere la valorizzazione del codeSystemVersion, oppure potete indicarmi come valorizzarlo?

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.

**Comment by andreasantori** [comment]
Buongiorno,
grazie per il supporto, cambiando la versione loinc come indicato siamo riuscita ad avere una risposta positiva nella fase di validazione:

{
	"traceID": "70cfc175a1e34c94",
	"spanID": "70cfc175a1e34c94",
	"workflowInstanceId": "2.16.840.1.113883.2.9.2.50502.4.4.17.ac0829433a01ef633017371fc3e46e57c6c361975ea1b592d0c57d75421a83ba.6cd44f7c0c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Una ultima domanda in caso di risposta positiva, l'identificativo che poi deve essere comunicato al repository documentale aziendale deve essere "2.16.840.1.113883.2.9.2.50502.4.4.17.ac0829433a01ef633017371fc3e46e57c6c361975ea1b592d0c57d75421a83ba.6cd44f7c0c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId", oppure è sufficiente "2.16.840.1.113883.2.9.2.50502.4.4.17.ac0829433a01ef633017371fc3e46e57c6c361975ea1b592d0c57d75421a83ba.6cd44f7c0c"?

**Comment by IStacchiotti** [comment]
Buongiorno, dovrebbe prendere tutta la stringa compresa tra le "": 2.16.840.1.113883.2.9.2.50502.4.4.17.ac0829433a01ef633017371fc3e46e57c6c361975ea1b592d0c57d75421a83ba.6cd44f7c0c^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
