### ISSUE TITLE
Errrore 401 - Token Authentication Failed

### ISSUE THREAD

**Issue by giosil** [ministero-salute/it-fse-support#890]
Richiamando il metodo di verifica con i parametri e i certificati usuali che fino all'altro giorno hanno funzionato ora otteniamo

{"type":"https://govway.org/handling-errors/401/TokenAuthenticationFailed.html","title":"TokenAuthenticationFailed","status":401,"detail":"Invalid token","govway_id":"edab8247-2ed0-11ef-a6bf-005056ae7395"}

Si può avere un dettaglio maggiore rispetto al problema?
Grazie. Cordiali saluti,

**Comment by vigliottim** [comment]
Buongiorno, come comunicato sul canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM), stiamo registrando dei temporanei disservizi. Seguiranno aggiornamenti. Grazie.

**Comment by vigliottim** [comment]
Buonasera, i servizi sono stati ripristinati. 
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
Grazie.
