### ISSUE TITLE
401 - TokenAuthenticationFailed - Invalid token

### ISSUE THREAD

**Issue by andremaladeltainfo** [ministero-salute/it-fse-support#891]
Buongiorno,
da oggi stiamo ottenendo su diversi ambienti l'errore:
```
{
    "type": "https://govway.org/handling-errors/401/TokenAuthenticationFailed.html",
    "title": "TokenAuthenticationFailed",
    "status": 401,
    "detail": "Invalid token",
    "govway_id": "....."
}
```
Nei mesi e nelle settimane passate abbiamo sempre acceduto correttamente al servizio di validazione ma da oggi purtroppo sembra fornire un errore sistematico sui vari ambienti dai quali contattiamo il servizio.

Ecco alcuni govway_id legati al problema evidenziato:
f153c131-2f03-11ef-a6bf-005056ae7395
5ce5803f-2efe-11ef-8aa0-005056ae54fa
024a6f42-2f01-11ef-8aa0-005056ae54fa

Giusto a titolo di esempio, questo è un TraceID ottenuto qualche giorno fa (14/06/2024) con le stesse procedure di creazione JWT che stiamo utilizzando attualmente: **8bc3c55b4241b11d**

A cosa potrebbe essere dovuto il problema?

Grazie infinite.
Un cordiale saluto.

**Comment by vigliottim** [comment]
Buongiorno, come comunicato sul canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM), stiamo registrando dei temporanei disservizi. Seguiranno aggiornamenti. Grazie.

**Comment by vigliottim** [comment]
Buonasera, i servizi sono stati ripristinati. 
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
Grazie.
