### ISSUE TITLE
Informazione su validazione + pubblicazione

### ISSUE THREAD

**Issue by mariogoodbread** [ministero-salute/it-fse-support#892]
Buongiorno,

vi contatto perché avrei bisogno del vostro supporto per implementare il seguente requisito per la ASL Roma 1:

_È necessario creare un documento LDO con la firma e il CDA, che deve essere inviato al FSE in un secondo momento (tralascio le motivazioni e i dettagli di processo)._

Vorrei chiedervi se è possibile validare su FSE un documento per poi utilizzare il workflowInstanceId ottenuto per pubblicarlo anche qualche giorno dopo, oppure se esiste un tempo massimo per poter utilizzare quel workflowInstanceId tra validazione e pubblicazione.

Spero di essere stato chiaro.

Cordiali Saluti
M.

**Comment by vigliottim** [comment]
Buongiorno, la pubblicazione deve essere successiva alla validazione (nel caso dovesse essere scaduta, sarà necessario ripeterla ed utilizzare il nuovo workflowInstanceId per pubblicare il documento), come riportato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/34a44509c913c5a19aa341964bfe5b7b015bd60f/doc/faq#chi-pubblica). 
Pertanto, non è possibile validare il documento e pubblicarlo qualche giorno dopo. 
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by mariogoodbread** [comment]
Grazie per la risposta,
l'unica cosa che mi preoccupa è il seguente warning che inevitabilmente riceveremmo quando dovremmo rivalidare un documento già firmato:

_SIGN_WARN - Attenzione il documento risulta firmato in validazione_

E' possibile che, in futuro, un documento firmato possa impedire al vostro servizio di validazione di ritornare un risultato positivo?

**Comment by vigliottim** [comment]
Buonasera,
Il warning _"[SIGN_WARN - Attenzione il documento risulta firmato in validazione]"_ indica che il file pdf utilizzato in validazione risulta già firmato. 
Specifichiamo che è previsto che la firma PADES venga applicata tra la validazione e la pubblicazione.
Pertanto, la firma applicata ad un file allegato in validazione, sebbene non produca un errore bloccante, determina il warning in questione.
Rimaniamo a disposizione per risolvere ulteriori dubbi.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
Grazie.
