### ISSUE TITLE
Errore di validazione: UNKNOWN_WORKFLOW_ID

### ISSUE THREAD

**Issue by kiara94ch** [ministero-salute/it-fse-support#894]
Buongiorno, 

dopo aver generato l'xml ed averlo iniettato nel pdf se procedo alla validazione di quest'ultimo l'errore che ricevo è:
UNKNOWN_WORKFLOW_ID: Il codice fiscale nel campo sub non è corretto.

Se invece valido l'xml con lo schematron 1.3 non ho errori, riuscite a darmi supporto?
Allego xml e pdf
[plstemp.pdf](https://github.com/user-attachments/files/15929370/plstemp.pdf)
[cda.txt](https://github.com/user-attachments/files/15929380/cda.txt)

**Comment by LucaRogledi** [comment]
Buonasera, 
dalle analisi risulta un problema in fase di estrazione del cda, la invitiamo a riprovare utilizzando il tool messo a disposizione online [pdf-generator](https://github.com/ministero-salute/it-fse-gtw-tools) per l'iniezione del cda nel pdf. Restiamo a disposizione in caso di ulteriore supporto. Grazie

**Comment by kiara94ch** [comment]
Buonasera, 
il mio dubbio però è che a parità di codice la validazione del pdf funzionava nei mesi precedenti e ora non più. E' obbligatorio utilizzare il vostro tool? O sono stati aggiunti novi vincoli per l'estrazione dell'xml dal pdf che vanno rispettati in modo che il pdf sia conforme al validator?

**Comment by vigliottim** [comment]
Buonasera,
non è obbligatorio usare i [tool ](https://github.com/ministero-salute/it-fse-gtw-tools) messi a disposizione ma è consigliato. Infatti, non è possibile effettuare operazioni di debug su codice o tool esterni.
Inoltre, non sono stati introdotti nuovi vincoli da rispettare per l'estrazione dell'xml dal pdf.
Rimaniamo a disposizione per risolvere ulteriori dubbi.

**Comment by joGrim65** [comment]
Buongiorno,
mi riaggancio alla segnalazione della mia collega e ribadisco gli stessi concetti.
Abbiamo realizzato il software per la generazione di pdf con cda embedded tempo fa.
Fino a qualche mese fa tutto funzionava ed abbiamo quindi congelata la versione pronta per essere posta in QA (che stiamo svolgendo in questi giorni).
A parità di software (nostro), il vostro strato (FSE Gateway) non estrae più un cda da pdf.
Tale pdf con xml è tranquillamente apribile senza problemi da Acrobat Reader.
Direi che così non va bene... se le specifiche prevedono l'injection di un CDA con il solo vincolo che il nome sia "cda.xml" e nulla più, allora dovete fare in modo che esso possa essere estratto.
Viceversa, dovete impegnarvi a dichiarare delle specifiche funzionali molto più significative, che consentano a chiunque, **con qualsiasi software** di poter realizzare quanto di più banale possa esserci.
E non mi sta bene "allora utilizzate il nostro tool..." perchè è fornito per essere usato da una CLI, non come library, con una API documentata con i sacri crismi.
In secondo luogo è scritto in Java. E se qualcuno avesse sviluppato il tutto in Python? o in Perl? o in .NET? o in qualsiasi altro linguaggio?

Soprattutto, se qualcosa che funziona, poi non funziona più (a parità di codice), beh direi che non mi sembra affatto corretto scaricare l'onere sulle terze parti... come minimo avere la professionalità di dichiarare i breaking changes occorsi, così da poter consentire a noi "comuni mortali" di poter comprendere cosa possa essere variato e, se necessario, apportare le dovute modifiche.

Trovo troppo semplicista la risposta "usate il nostro tool".

Pertanto allego anche io un file prima funzionante che ora da il problema e mi aspetto che qualcuno del vostro team abbia la correttezza di dirmi perchè ora il cda non viene più estratto. Note le cause, apporterò le modifiche necessarie al mio software.

Grazie
[provasave.pdf](https://github.com/user-attachments/files/15983427/provasave.pdf)

**Comment by ponsilva** [comment]
Buongiorno,
mi inserisco in questo thread perché anch'io ho rilevato questo errore con alcuni file di test.

La situazione è analoga a quella già descritta: sono file pdf con cda.xml allegato e se li apro con Adobe Acrobat li vedo tutti uguali, cioè il file cda.xml compare nella finestra Allegati.
Però di questi pdf alcuni passano la validazione del gateway e per altri si verifica l'errore 400 "Errore in fase di estrazione del CDA".

Eseguendo un'analisi più dettagliata con pdfbox si vede che c'è una differenza nel Tree Path

Per i file pdf validati dal gateway il file cda.xml si trova in
Root/Names/EmbeddedFiles/Names/[1]/EF/F

Per i file pdf con errore il file cda.xml si trova in
Root/Names/EmbeddedFiles/Kids/[0]/Names/[1]/EF/F

Sembra quindi che un'alberatura sia accettata dal gateway e l'altra no, mentre invece da Adobe Acrobat questa differenza non viene rilevata.

Se effettivamente c'è questo vincolo per il gateway FSE 2.0 sarebbe necessario che fosse esplicitato nella documentazione.

Infatti dobbiamo considerare che ci sono numerosi applicativi in esercizio presso le strutture sanitarie che già producono documenti CDA e che per vari motivi (es tecnologie disomogenee) non tutti possono integrare il tool pdf-generator.

Grazie per le indicazioni che potrete fornire in proposito.

**Comment by vigliottim** [comment]
Buon pomeriggio,
è stato rilasciato un aggiornamento.
Le chiediamo gentilmente di riprovare.
Rimaniamo a disposizione qualora l'anomalia persista.
Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.

**Comment by LucaRogledi** [comment]
Buon pomeriggio @ponsilva @joGrim65 @kiara94ch , 
segnaliamo che la [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#2-contesto-di-riferimento) è stata aggiornata riportando i path all'interno del pdf in cui deve essere presente il `cda.xml`. Grazie
