### ISSUE TITLE
Errore 403 durante validazione RAD

### ISSUE THREAD

**Issue by Andr3a93** [ministero-salute/it-fse-support#899]
Buongiorno,
stiamo effettuando dei test di validazione per quanto riguarda referto di radiologia RAD ma riscontriamo il seguente errore:
{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"2a6f32ea-32d8-11ef-8aa0-005056ae54fa"}

Potreste darci maggiori informazioni?
Grazie

**Comment by vigliottim** [comment]
Buongiorno, analizzando i log della chiamata da lei effettuata, sembra che l'errore ricevuto sia causato dalla valorizzazione del campo _sub_ presente nei token: 

![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/3d5a86a2-9efc-4d2e-b428-24ae7b961f84)

Inoltre, verificando l'_Authorization Bearer Token_ tramite il tool [jwt.io](https://jwt.io/) compare il messaggio _"Invalid Signature"_:

<img width="453" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/9824ef51-819b-489d-b31d-f61e27946759">

Il campo _sub_ assume valori diversi all'interno dei due token mentre dovrebbe essere valorizzato con la stessa stringa: 

**Authorization Bearer Token:**
<img width="273" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/3f86f59a-e8e4-4acc-b3d3-ae7c19230257">

**FSE-JWT-Signature:**
<img width="290" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/26ce3f3a-f52d-46e1-aed3-8e64b5bab2bb">

In aggiunta, le segnaliamo la presenza del seguente campo inatteso nei JWT:
`"nbf": 1719310060`

Di seguito può trovare il link alla documentazione relativa alla valorizzazione dei campi contenuti nei JWT: [campi-contenuti-nei-jwt](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt)
La informiamo che al link [jwt-generator](https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator) è disponibile il tool _JWT generator_ che consente di generare i token per effettuare le chiamate ai servizi.
La invitiamo ad effettuare nuovamente la chiamata dopo aver applicato le correzioni riportate. 
Rimaniamo a disposizione per ulteriori chiarimenti.
Grazie.

**Comment by Andr3a93** [comment]
Grazie per la risposta, abbiamo sistemato i token. La validazione è andata a buon fine, sono stati restituiti i warning che seguono:
{"traceID":"82fc2efcbf3e1c99","spanID":"82fc2efcbf3e1c99","workflowInstanceId":"2.16.840.1.113883.2.9.2.200.4.4.2ec23cf0ecd7ae1512bd2c642ca46fbc8d9a7af72357b74a894229d5c88b1ae4.38eff29903^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","warning":"[W005 | Sezione Esame Eseguito: l'entry/act/code può essere valorizzato secondo i sistemi di codifica\n\t\t\tLOINC @codeSystem='2.16.840.1.113883.6.1'\n\t\t\tICD-9-CM @codeSystem='2.16.840.1.113883.6.103'],[W005 | Sezione Esame Eseguito: l'entry/act/code può essere valorizzato secondo i sistemi di codifica\n\t\t\tLOINC @codeSystem='2.16.840.1.113883.6.1'\n\t\t\tICD-9-CM @codeSystem='2.16.840.1.113883.6.103']"}

Riguardo la Sezione Esame Eseguito stiamo valorizzando gli entry/act/code code con il codice catalogo regionale con codesystem relativo all'oid del dizionario delle prestazioni sanitarie ,in questo caso Regione Sardegna, è corretta come procedura?

Grazie

**Comment by vigliottim** [comment]
Come indicato nella [guida HL7 Italia per RAD](https://www.hl7.it/realm-italiano/referto-di-radiologia-rad/), l'elemento _entry/act_ della sezione _Esame eseguito_ deve essere strutturato come indicato nella tabella di seguito:

![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/4adf9d5c-227a-45e0-9d8d-9a4e491ba951)

Si consiglia fortemente di utilizzare le codifiche LOINC o ICD-9-CM per valorizzare il campo _entry/act/code_, tuttavia queste non sono obbligatorie.
Pertanto, il campo _act/code_ va comunque valorizzato anche con codifiche diverse da LOINC e ICD9. 
Se presente l'elemento opzionale _translation_, in esso dovrà essere riportata la transcodifica.
Rimaniamo a disposizione per fornirle ulteriore supporto.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
La invitiamo a riaprirla nel caso in cui fosse necessario ulteriore supporto.
Grazie.
