### ISSUE TITLE
Schema with version POCD_HD000040 not found on database.

### ISSUE THREAD

**Issue by EnzoMaietta** [ministero-salute/it-fse-support#9]
Buongiorno, dalla Lombardia stiamo tentando di validare il cda2 in allegato
[cp.xml.txt](https://github.com/ministero-salute/it-fse-support/files/9363892/cp.xml.txt)
, ma riceviamo dal Gateway errore:

_{"traceID":"32256230049bbefb","spanID":"32256230049bbefb","type":"/msg/syntax","title":"Errore di sintassi.","detail":"**Schema with version POCD_HD000040 not found on database.**","status":400,"instance":"/msg/syntax","workflowInstanceId":"2.16.840.1.113883.2.9.2.80.3.1.4.4.4cab3992441e611fc9c405e9bb2a2db34d360268ec0f73cf3273e6904ca08f18.1ba11400cd^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}_

Ci potete supportare a capire cosa sbagliamo? Da documentazione HL7 non dovrebbe essere conforme? Fonte:

`2.3.1.2 ClinicalDocument/typeId
ClinicalDocument/typeId è un elemento OBBLIGATORIO. Tale elemento identifica i215
vincoli imposti dalle specifiche HL7 CDA Rel 2.0 ossia identifica la versione di
riferimento del CDA a cui il documento fa riferimento.
ClinicalDocument/typeId è un data type di tipo Instance Identifier (II) le cui
componenti root ed extension sono definite nel documento [7].
220
[CONF-ESE-3] Il documento DEVE contenere uno ed un solo elemento
ClinicalDocument/typeId, con l’attributo ClinicalDocument/typeId/@root
valorizzato a "2.16.840.1.113883.1.3" e con l’attributo
ClinicalDocument/typeId/@extension valorizzato a “POCD_HD000040”
Esempio di utilizzo:
<typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040"/>`

Grazie in anticipo, buona giornata.

**Comment by zukka77** [comment]
Buongiorno, stiamo verificando

**Comment by zukka77** [comment]
Nel frattempo per provare a invocare il servizio si puoi provare ad usare un cda di esempio:
https://github.com/ministero-salute/it-fse-support/tree/main/doc/esempi/CDA

**Comment by EnzoMaietta** [comment]
> 

Grazie Andrea. Innanzitutto ti confermiamo che con gli esempi forniti la validazione va a buon fine!
Ti segnaliamo però che se prendiamo l'esempio fornito e all'interno di esso modifichiamo soltanto la riga 4:

`<typeId root="2.16.840.1.113883.1.3" extension="POCD_MT000040UV02"/>`

con la riga:

`<typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040"/>`

La validazione che prima andava a buon fine continua a restituirci nuovamente l'errore in oggetto _"Schema with version POCD_HD000040 not found on database."_

Grazie ancora e buona serata.

**Comment by gndibiase** [comment]
I controlli presenti sugli integration kit fanno riferimento all’ultima versione del POCD, ovvero @extension=POCD_MT000040UV02. I CDA2 valorizzati con la precedente versione restituiranno un esito negativo.
A seguire i  link ufficiali  che riporta l’ultima versione del POCD:
[GitHub - HL7/CDA-core-2.1](https://github.com/HL7/cda-core-2.1)
