### ISSUE TITLE
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request con  UTF8

### ISSUE THREAD

**Issue by nturri1306** [ministero-salute/it-fse-support#90]
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: [{"type":"https://govway.org/handling-errors/400/InvalidRequestContent.html","title":"InvalidRequestContent","status":400,"detail":"Request content not conform to API specification: UTF-8;boundary=eyVXecouaytkMElBqez-C-8ITdtkfhMX","govway_id":"41d97b8f-a611-11ed-b7ba-005056ae54fa"}]   se provo a loggare la chiamata vedo che è presente  UTF-8 è questo lo manda in errore , una domanda il Goway oltre a gestire SSL fa anche delle validazioni?

sto usando RestTemplate con spring boot

**Comment by nturri1306** [comment]
DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Type: multipart/form-data;charset=UTF16LE;boundary=1SLwPNBZWMkS1KHqWSi1VUxnkq6M9Xi_

**Comment by nturri1306** [comment]
19:06:06.602 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> POST /govway/rest/in/FSE/gateway/v1/documents/validation HTTP/1.1
19:06:06.602 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept: 
19:06:06.603 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> FSE-JWT-Signature: eyJ4NWMiOlsiTUlJRkxUQ0NBeFdnQXdJQkFnSVVKcEM0SUExRC9UMVJ5UHVmSlhYTHFTSUVrK1l3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TXpBeE1qUXhOekEwTXpCYUZ3MHlOakF4TWpReE56QTBNamxhTUdzeEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SNHdIQVlEVlFSaERCVkRSanBKVkMweE1URkRUMDVUVDFKYVNVOURVMEV4R3pBWkJnTlZCQU1NRWxNeEl6RXhNVU5QVGxOUFVscEpUME5UUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS1hTVWtRNDFoRHpGYzNDZUtSRFZvamhBOHovSmxiYS9Fd1hZRlZZMEwxMU9QTkNmWHhtN1JENVhJcnhqNmxsYlNzSTRVejFwUmpvQzJrVnQxU1hxYkJXd0g1Ymd4c2JrN29rSkVLZkdZWXlZV1VITGJ5SWQ1V0hDdGI4cW9BcklLOFI5dEVCcUhqRUxjZWFsdm02OEVqR3M3SkJ0Z0ZMazZLY3BNWEdZcWFHbHFVb3o3WUkwK3hscENhZUlhd20yQmVKZjRLSDN0QllPT3Y4TjVsYlFmc28vcXpZWDZ4cHNsYWV3UE9UQTRPQnc1c2xlUzV2TjRLTUs4TENiK1d2b1dNMGdIblBibnozMjZRaVk3OHg4SFk4V3p3M0U0QUdBK1A5aGM5RmF0WFFSZjlRY2RXSWhIRGVWRk9hTXpmN3VVQ1hmUDhHbXc0V3VNeEZRNGtyZFVFQ0F3RUFBYU9CM0RDQjJUQWZCZ05WSFNNRUdEQVdnQlFXT2FrYUJZbTNEeTJ5TmUzQ0NackZBNE1pUHpBU0JnTlZIU0FFQ3pBSk1BY0dCU3RNSFFFTE1ITUdBMVVkSHdSc01Hb3dhS0Jtb0dTR1lteGtZWEE2THk5allXUnpMbVpwYm1GdWVtVXVhWFF2UTA0OVEwRWxNakJOYVc1cGMzUmxjbThsTWpCa1pXeHNZU1V5TUZOaGJIVjBaU1V5TUZSbGMzUXNUejFOYVc1cGMzUmxjbThsTWpCa1pXeHNZU1V5TUZOaGJIVjBaU3hEUFVsVU1CMEdBMVVkRGdRV0JCUVB6ZzlYOFVRQjh5a0M0N0ttN2FlNXRGWGRCREFPQmdOVkhROEJBZjhFQkFNQ0JrQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBQkVrZUNKamV4c01ZZ1g3UUJiUGJaYk5Ibk5xSHg2SGNkM2JhcTQ4MG5QUllMUEJyNjUwRk05RjhJN21wcy9IM0dGcU8yNVFQUjErOE1lSlFyTkx2TEhncUxaQXFzSmtyQWNqWmQ1WUhwRitLMVZmL1RvcmR3ZEhoWlRPNFRsaWl4UXVhVStXUWFnRnBGVi83cGFDSVg2Y0JtSzBzTlhlRFFkRzBiQ2RoQjB0My94YXI0Z3RMSFJOek5hbEY1NFlpL1o2ZWdpNmFXSWk3WnRyeUh6QlFWRjVVS1UwaTB3T1VaYytZcnVYaWFtT3RPQll5SVd1dXQrRGI5S09pSjhaV3JoQllieU5SVUVySFo1VXNyWU8yNTFvTStzZmNQNzl5NkJEd3gxMUhiNXJZcnU2Ulk1ZktnMkpkTVVqWlFXWVBRamFVeEtpSVZhQkxycENnMlBoazU0blJ4bzlkZURCcU53WjIwa29jVkhTY3MxQzRES1k3MXhUb2RrLzZwT1dWUUpRL1VHUjB3eklUbWZmaEliQ1BSZTVsNEZTbXkrcVJUR0xiSW50NmFQb1RvR0VBNTFKc0owWGYydWZXcjZuWGdkZXVhM3crWWVwSWpSTkl4aitaY2NRNEV4SXJ3cmRCR3pSelVqckkzV2g1cHozTzY0UFJVa2ZGdUg4TUQrL1E3aU1IYUdwWCt5UXV2UDF0RVZ2NDFxVjN4clJ1SnZyRWF6VEUvZ3ZodFVkWDBEQmQxTHJMYWZqMDlWSE5Vc3VKelZ4NExjcU1GTU1ibkNvV3h1SG5XL1QrNU4zZldNc09DY3hZdXFEZU1tcU0xWWVzcjBjSTVudlBNV0FWazNpbU5BVEhodjdWWEtNMDloaFRnRkh0bWcwbGwrbms3VHp0WGphTmZoOVlEMjciXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJQUk9WQVgwMFgwMFgwMDBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImlzcyI6ImludGVncml0eTpTMSMxMTFDT05TT1JaSU9DU0EiLCJsb2NhbGl0eSI6InJvbWUiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlcnNpb24iOiJWLjEuMC4wIiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb25lIExhemlvIiwic3ViamVjdF9vcmdhbml6YXRpb25faWQiOiIxMjAiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJwYXRpZW50X2NvbnNlbnQiOnRydWUsImFjdGlvbl9pZCI6IkNSRUFURSIsInJlc291cmNlX2hsN190eXBlIjoiKCcxMTUwMi0yXl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsImF0dGFjaG1lbnRfaGFzaCI6ImIwOGRmNzNkZDQwYTBlYTliY2RlNWNhN2VlZDgzZGQyMjljMTAzNWY0OWRhNWQ3YTgwYzgxYTk5MjBlNTcxYjIiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiZnNlYnJva2VyIiwiZXhwIjoyMDM1NzA2NzY1LCJpYXQiOjE2NzU3MDY3NjUsInN1YmplY3RfYXBwbGljYXRpb25fdmVuZG9yIjoiZnNlYnJva2VyIiwianRpIjoiMTgxNTIiLCJwZXJzb25faWQiOiJHVFdHV1k4MkI0Mkc5MjBNXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08ifQ.fMCPvkMNpTbxGakZH1wkQ8VzDdlO49MBk-OoguRqeGr9HVIFzcCL9JYK23UzPL531LyDpEzhB1hpqYe95e5Hw3x9skF8NQ23utTQ0ifFDcTcdXiO_5d9UTlDzuwNqWBhxvabQTPovLmCZjjq9RA0Y9PrDR_iHGG6ONsM5FeRjce01A8PCGeBmdQuk-O5ytReXbm8vT_qgZLOg6PAOde5_ZXUgaQ-vPqELggdtAMQ5ro-TftwzbFLE4-Z5od1ntL15_p43pCA_W_0CwDPKnOHcZdUoUXxUGoy1ta_6QlQe_HXNBf_TUaW4jMqs0CotsEqKACbQuIM575G7YNcJ0FDFA
19:06:06.604 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Authorization: Bearer eyJ4NWMiOlsiTUlJRkxUQ0NBeFdnQXdJQkFnSVVKcEM0SUExRC9UMVJ5UHVmSlhYTHFTSUVrK1l3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TXpBeE1qUXhOekEwTXpCYUZ3MHlOakF4TWpReE56QTBNamxhTUdzeEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SNHdIQVlEVlFSaERCVkRSanBKVkMweE1URkRUMDVUVDFKYVNVOURVMEV4R3pBWkJnTlZCQU1NRWxNeEl6RXhNVU5QVGxOUFVscEpUME5UUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS1hTVWtRNDFoRHpGYzNDZUtSRFZvamhBOHovSmxiYS9Fd1hZRlZZMEwxMU9QTkNmWHhtN1JENVhJcnhqNmxsYlNzSTRVejFwUmpvQzJrVnQxU1hxYkJXd0g1Ymd4c2JrN29rSkVLZkdZWXlZV1VITGJ5SWQ1V0hDdGI4cW9BcklLOFI5dEVCcUhqRUxjZWFsdm02OEVqR3M3SkJ0Z0ZMazZLY3BNWEdZcWFHbHFVb3o3WUkwK3hscENhZUlhd20yQmVKZjRLSDN0QllPT3Y4TjVsYlFmc28vcXpZWDZ4cHNsYWV3UE9UQTRPQnc1c2xlUzV2TjRLTUs4TENiK1d2b1dNMGdIblBibnozMjZRaVk3OHg4SFk4V3p3M0U0QUdBK1A5aGM5RmF0WFFSZjlRY2RXSWhIRGVWRk9hTXpmN3VVQ1hmUDhHbXc0V3VNeEZRNGtyZFVFQ0F3RUFBYU9CM0RDQjJUQWZCZ05WSFNNRUdEQVdnQlFXT2FrYUJZbTNEeTJ5TmUzQ0NackZBNE1pUHpBU0JnTlZIU0FFQ3pBSk1BY0dCU3RNSFFFTE1ITUdBMVVkSHdSc01Hb3dhS0Jtb0dTR1lteGtZWEE2THk5allXUnpMbVpwYm1GdWVtVXVhWFF2UTA0OVEwRWxNakJOYVc1cGMzUmxjbThsTWpCa1pXeHNZU1V5TUZOaGJIVjBaU1V5TUZSbGMzUXNUejFOYVc1cGMzUmxjbThsTWpCa1pXeHNZU1V5TUZOaGJIVjBaU3hEUFVsVU1CMEdBMVVkRGdRV0JCUVB6ZzlYOFVRQjh5a0M0N0ttN2FlNXRGWGRCREFPQmdOVkhROEJBZjhFQkFNQ0JrQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBQkVrZUNKamV4c01ZZ1g3UUJiUGJaYk5Ibk5xSHg2SGNkM2JhcTQ4MG5QUllMUEJyNjUwRk05RjhJN21wcy9IM0dGcU8yNVFQUjErOE1lSlFyTkx2TEhncUxaQXFzSmtyQWNqWmQ1WUhwRitLMVZmL1RvcmR3ZEhoWlRPNFRsaWl4UXVhVStXUWFnRnBGVi83cGFDSVg2Y0JtSzBzTlhlRFFkRzBiQ2RoQjB0My94YXI0Z3RMSFJOek5hbEY1NFlpL1o2ZWdpNmFXSWk3WnRyeUh6QlFWRjVVS1UwaTB3T1VaYytZcnVYaWFtT3RPQll5SVd1dXQrRGI5S09pSjhaV3JoQllieU5SVUVySFo1VXNyWU8yNTFvTStzZmNQNzl5NkJEd3gxMUhiNXJZcnU2Ulk1ZktnMkpkTVVqWlFXWVBRamFVeEtpSVZhQkxycENnMlBoazU0blJ4bzlkZURCcU53WjIwa29jVkhTY3MxQzRES1k3MXhUb2RrLzZwT1dWUUpRL1VHUjB3eklUbWZmaEliQ1BSZTVsNEZTbXkrcVJUR0xiSW50NmFQb1RvR0VBNTFKc0owWGYydWZXcjZuWGdkZXVhM3crWWVwSWpSTkl4aitaY2NRNEV4SXJ3cmRCR3pSelVqckkzV2g1cHozTzY0UFJVa2ZGdUg4TUQrL1E3aU1IYUdwWCt5UXV2UDF0RVZ2NDFxVjN4clJ1SnZyRWF6VEUvZ3ZodFVkWDBEQmQxTHJMYWZqMDlWSE5Vc3VKelZ4NExjcU1GTU1ibkNvV3h1SG5XL1QrNU4zZldNc09DY3hZdXFEZU1tcU0xWWVzcjBjSTVudlBNV0FWazNpbU5BVEhodjdWWEtNMDloaFRnRkh0bWcwbGwrbms3VHp0WGphTmZoOVlEMjciXSwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJQUk9WQVgwMFgwMFgwMDBZXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJpc3MiOiJhdXRoOlMxIzExMUNPTlNPUlpJT0NTQSIsImV4cCI6MjAzNTcwNjc2NSwiaWF0IjoxNjc1NzA2NzY1LCJqdGkiOiIxODE1MiJ9.cXLggUXOeXcCSeY_-2oxMETvcMUh71OyOixoDUIYfQH4x89XiPlo0UADA11l4Qsn1SAfTCDnClwf58NCTrPbM0uQTH1xWXo41nz6qFTSszeoXmpO8PfNROqXUxD51TZVHPLM1NG9jdQzbp9jSBKb32VpSkEhITVBVtlefwxKw5EjeHiOb-5r8UAlUvOT-A6J97SyiccMwKoIEAipF1OjFAp-HRZrl1gTg6QKPhWYdZhaQr4vsWnAq4KTH1Y3O-G7aLboGq9ku8qS6lcuoQA8NzcCB9r04qGyMHFMe56RK5aOC6C95iXBEdG_G_Om8L-tr6WEfBwr-ThpvkDr9fcgAg
19:06:06.605 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Type: multipart/form-data;charset=UTF-16LE;boundary=1SLwPNBZWMkS1KHqWSi1VUxnkq6M9Xi_
19:06:06.605 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Length: 16996
19:06:06.605 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: modipa-val.fse.salute.gov.it
19:06:06.605 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
19:06:06.605 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.17)
19:06:06.605 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
19:06:06.606 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "POST /govway/rest/in/FSE/gateway/v1/documents/validation HTTP/1.1[\r][\n]"

**Comment by IStacchiotti** [comment]
Chiudiamo in quanto duplicata dall'#83. Grazie.
