### ISSUE TITLE
Richiesta informazioni sul max numero caratteri nelle proprietà stringa della response del gateway

### ISSUE THREAD

**Issue by andreasantori** [ministero-salute/it-fse-support#901]
Buonasera,
in merito alla response del gateway, sotto un esempio

{
	"traceID": "01844fe7fd3f5deb",
	"spanID": "01844fe7fd3f5deb",
	"type": "/msg/vocabulary",
	"title": "Errore vocabolario.",
	"detail": "Almeno uno dei seguenti vocaboli non è censito: [CodeSystem: 2.16.840.1.113883.6.73, Codes: N02BF02]",
	"status": 400,
	"instance": "/validation/error",
	"workflowInstanceId": "2.16.840.1.113883.2.9.2.30.4.4.2cff726fdf5c5fae69624527528b0473681baba6d5fce8c18fdd9975220711f7.26261d82b6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

è possibile avere informazioni sul massimo numero di caratteri che può contenere ciascuna proprietà di tipo stringa?
"traceID", "spanID", "type", "title", "detail", "workflowInstanceId"

Grazie.

**Comment by vigliottim** [comment]
Buongiorno, 
le size dei diversi campi richiesti presenti nella response si trovano nello swagger pubblicato al seguente link: https://github.com/ministero-salute/it-fse-support/blob/main/openapi/gateway/swagger_gtw.yaml. 
Di seguito riportiamo un esempio:
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/7b9d6f56-c6fb-467d-a793-0ecfb6756c7a)
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
Grazie.

**Comment by andreasantori** [comment]
Buongiorno, va benissimo così.
Grazie per il riscontro fornito.
