### ISSUE TITLE
GATEWAY/

### ISSUE THREAD

**Issue by dampgithub** [ministero-salute/it-fse-support#904]
Buonasera, non riesco a creare le cartelle dentro GATEWAY/
devo creare:
A1#111#DAMPSOFTWAREXXX/DAMP sas/DAMP - Volare FSE - LIS - RSA/Ver. 02.00, non trovo le specifiche tecniche per creare la struttura..
Grazie

**Comment by vigliottim** [comment]
Buonasera,
può trovare la documentazione relativa alla procedura di caricamento dei risultati al seguente link: [accreditamento-fse-20](https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#accreditamento-fse-20-draft)
Per la creazione delle cartelle, nel caso in cui avesse problemi, la rimandiamo alla seguente issue con le istruzioni dettagliate: #853 
Rimaniamo a disposizione per chiarimenti. Grazie.

**Comment by dampgithub** [comment]
Salve, sono riuscito a creare seguendo le indicazioni #853 ma adesso mi ritrovo la mia struttura creata non su branches Main ma si è creata sotto la branches [patch-3](https://github.com/dampgithub/it-fse-accreditamento/tree/patch-3), non ce possibilita di spostare tutto sotto Main? tra le altre cose sono riuscito a caricare i tre file checklist.xlsx; data.json ed un file xml.. 
Grazie
Marcello Marino

**Comment by vigliottim** [comment]
Buongiorno, i file sono stati caricati sul branch _patch-3_. 
Per averli sul branch _main_ deve selezionarlo tramite il menu a tendina in figura e fare nuovamente l'upload: 

<img width="256" alt="image" src="https://github.com/ministero-salute/it-fse-support/assets/134372089/5fa5be49-cc32-4714-81f1-4f8764a4d9d9">

Rimaniamo a disposizione per chiarimenti.

**Comment by dampgithub** [comment]
Fatta altra pull request #1538 allego screenshot

**Comment by dampgithub** [comment]
![ScreenShot](https://github.com/ministero-salute/it-fse-support/assets/162481448/fb6f7280-0762-4b1e-ac49-5f74f60d492f)

**Comment by vigliottim** [comment]
Le confermiamo che la pull-request [#1538](https://github.com/ministero-salute/it-fse-accreditamento/pull/1538) è stata creata correttamente.
Tuttavia, è presente solo il seguente file:
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/40dacd16-ac5d-4c26-9e5c-0880b1dafa48)
La informiamo che i risultati devono essere caricati secondo le specifiche riportate in documentazione al link: [procedura-di-caricamento-dei-risultati](https://github.com/ministero-salute/it-fse-accreditamento?tab=readme-ov-file#procedura-di-caricamento-dei-risultati)
Riceverà l'esito delle elaborazioni via e-mail nel giro di qualche giorno lavorativo.
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
