### ISSUE TITLE
Domande sui codici OID, HSP11 per CDA2

### ISSUE THREAD

**Issue by masIorio** [ministero-salute/it-fse-support#906]
Buongiorno,
volevo chiedere dove trovare le informazioni necessarie per poter compilare correttamente i seguenti campi (ai quali pongo di fianco la descrizione in nostro possesso, riporto, per comodità anche le sezioni di riferimento):

OIDStrutturaCompetenza: Identificativo univoco del dominio di identificazione dei documenti (ad es. può indicare l'ASL di competenza del documento). Tale identificativo – riconosciuto pubblicamente – garantisce l'univocità dell'istanza dell'identificativo a livello globale.
`<id root="[OID_STRUTTURA_COMPETENZA]" extension="[EXTENSION_ID]" assigningAuthorityName="[NOME_STRUTTURA_COMPETENZA]"/>`

Codice ente custode documento: Per riportare gli identificativi delle Aziende Sanitarie, è possibile utilizzare la codifica ministeriale FLS11, e in tal caso l’attributo @root DEVE essere valorizzato con l’OID 2.16.840.1.113883.2.9.4.1.1”. Per riportare gli identificativi della struttura è possibile utilizzare le codifiche HSP11 e in tal caso l’attributo @root DEVE essere valorizzato con 2.16.840.1.113883.2.9.4.1.2 HSP11.
```
<representedCustodianOrganization>
          <id root="2.16.840.1.113883.2.9.4.1.1" extension="[COD_ENTE]"
          assigningAuthorityName="Ministero della Salute"/>
</representedCustodianOrganization>

```
RAMO:AZIENDALE.NOSOLOGICI: OID che identifica il numero nosologico (vocabolario da cui proviene il numero nosologico - Es. 2.16.840.1.113883.2.9.2.[RAMO:AZIENDALE.NOSOLOGICI].4.6) 
```
<componentOf>
    <encompassingEncounter>
              <id root="2.16.840.1.113883.2.9.2.[RAMO:AZIENDALE.NOSOLOGICI].4.6"
              extension="NUMERO_NOSOLOGICO"
              assigningAuthorityName="[NOME_AZIENDA]"/>
    </encompassingEncounter>
</componentOf>
```

OIDDominioPresidio e codEnte: per questi campi dovremmo utilizzare il codice "2.16.840.1.113883.2.9.4.1.2" accoppiato con il campo "extension" valorizzato con il CODICE_MINISTERIALE_HSP11-OSPEDALE?
```
<serviceProviderOrganization>
      <id root="[OID_DOMINIO_PRESIDIO]"
      extension="[COD_PRESIDIO]"
      assigningAuthorityName="Ministero della Salute"/>
      <name>[NOME_PRESIDIO]</name>
      <telecom value="tel:[NUM_TEL_PRESIDIO]"/>
      <asOrganizationPartOf>
              <id root="2.16.840.1.113883.2.9.4.1.1"
              extension="[COD_ENTE]"
              assigningAuthorityName="Ministero1470 della Salute"/>
      </asOrganizationPartOf>
</serviceProviderOrganization>
```

Ringrazio anticipatamente.

**Comment by LucaRogledi** [comment]
Buongiorno, rispondiamo per punti:

- **OIDStrutturaCompetenza**: La root dell'identificativo del documento <id> può essere valorizzata come segue: `2.16.840.1.113883.2.9.2.[ASL/AO/REGIONE di competenza].4.4`

- **Codice ente custode documento**: si consiglia di consultare il seguente link: [Anagrafi ASL e strutture e contesto demografico (salute.gov.it)](https://www.salute.gov.it/portale/temi/p2_6.jsp?id=3826&area=statisticheSSN&menu=vuoto)

- **RAMO:AZIENDALE.NOSOLOGICI**: si consiglia di consultare il seguente sito di HL7: [OID_Per_Stato.pdf (hl7.it)](https://www.hl7.it/wp-content/uploads/2024/04/OID_Per_Stato.pdf)

- **OIDDominioPresidio e codEnte**: si conferma che per l'OID  "2.16.840.1.113883.2.9.4.1.2" è possibile valorizzare il campo extension con il codice ministeriale HSP11.

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
Grazie.
