### ISSUE TITLE
Chiarimenti su iter di certificazione

### ISSUE THREAD

**Issue by GruppoSiges** [ministero-salute/it-fse-support#907]
Buongiorno, 

abbiamo avviato qualche giorno fa la procedura di accreditamento per l’integrazione con FSE 2.0 per alcune tipologie di documenti, compilando il form online, ma non abbiamo ancora ricevuto un feedback; dobbiamo comunque procedere con le richieste dei certificati? Nelle mail di richiesta, è necessario inserire qualche tipo di riferimento alla pratica che abbiamo aperto compilando il form?

Grazie, saluti.

**Comment by vigliottim** [comment]
Buon pomeriggio. 
Non riceverà alcun riscontro dopo la compilazione dell'EuSurvey.
Pertanto, può richiedere subito i certificati inviando una e-mail al seguente indirizzo: [fse_support@sogei.it](mailto:fse_support@sogei.it)
Le segnaliamo il seguente link per avere informazioni dettagliate sul processo di accreditamento:
[processo-di-accreditamento](https://github.com/ministero-salute/it-fse-support/tree/main/doc/accreditamento#fase-1-processo-di-accreditamento)
Rimaniamo a disposizione per chiarimenti.

**Comment by GruppoSiges** [comment]
Grazie mille.
Nella mail quali informazioni vanno indicate?

**Comment by LucaRogledi** [comment]
Buonasera, Nella mail può indicare il fornitore a cui saranno associati i certificati e allegare le CSR, necessarie per la creazione dei certificati, che può generare come indicato in documentazione al seguente link: https://github.com/ministero-salute/it-fse-support?tab=readme-ov-file#richiesta-certificati-x509
Grazie

**Comment by GruppoSiges** [comment]
Ora è chiaro grazie.

Saluti.

**Comment by vigliottim** [comment]
Grazie per il gentile feedback.
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
