### ISSUE TITLE
Chiarimento su repositoryUniqueId 

### ISSUE THREAD

**Issue by GruppoSiges** [ministero-salute/it-fse-support#908]
Buongiorno, 
 
vorremmo un chiarimento sul repositoryUniqueId necessario alla creazione dei JWT: se la struttura sanitaria non si appoggia ad un repository riconosciuto a livello nazionale, ma conserva i documenti sanitari nella propria infrastruttura informatica interna, quale codice va indicato?
 
Grazie, saluti.

**Comment by vigliottim** [comment]
Buon pomeriggio. 
Come indicato nel documento [AffinityDomainItalia-v2.5](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20interoperabilit%C3%A0/AffinityDomainItalia_v2-5_v20231212.pdf), il metadato _XDSDocumentEntry.repositoryUniqueId_ identifica in maniera univoca a livello nazionale il repository che custodisce il documento da indicizzare e deve essere valorizzato come indicato nel seguente paragrafo: 

![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/ec401fbf-3367-432c-9355-0caab9131eec)

Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by GruppoSiges** [comment]
Il mio dubbio era relativo al caso in cui non ci sia un repository propriamente detto, ovvero, ad esempio, un ambulatorio che memorizza i referti nel proprio DB senza mandarli in archiviazione documentale presso un soggetto riconosciuto a livello nazionale; in questi casi che tipo di codice va utilizzato? Esiste un codice per il repository del FSE nazionale?
Grazie, saluti.

**Comment by vigliottim** [comment]
Buongiorno, dovrebbe interfacciarsi con la sua Regione di riferimento per l'integrazione del vostro repository interno con quello regionale, al fine di garantire l'opportuna valorizzazione del parametro _X_ del campo _RepositoryUniqueId_ e il corretto recupero del documento. 
Rimaniamo a disposizione per ulteriori richieste di supporto.

**Comment by GruppoSiges** [comment]
Ok ho provveduto ad interfacciarmi con i referenti informatici regionali.
Grazie, saluti

**Comment by vigliottim** [comment]
Grazie a lei per il gentile feedback.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
