### ISSUE TITLE
Discrepanza tra verifica e documentazione HL7IT-IG_CRAD2-v1.1-S.pdf

### ISSUE THREAD

**Issue by RTirabassi-Eurochimica** [ministero-salute/it-fse-support#909]
Secondo il capitolo 4.1.13 del documento HL7IT-IG_CRAD2-v1.1-S.pdf l'elemento 'authorì deve contenere un elemento 'assignedAuthor' il quale a sua volta deve contenere almeno 3 elementi 'telecom' che devono riportare la mail, la pec ed il telefono dell'autore.

Nell'approfondire i test di accreditamento abbiamo notato che questa regola non sembra essere coerentemente implementata dal GateWay di test.
In data 2024-07-01 11:24:50 CEST, con "traceID":"e9a5420d616419e1", "spanID":"e9a5420d616419e1", "workflowInstanceId":"2.16.840.1.113883.2.9.2.190.4.4.0c2fe42140ba31337ad7aae7ea627267b2c432f2e1aa8ede9a3625da611f34ce.0a1c0805dc^^^^urn:ihe:iti:xdw:2013:workflowInstanceId" è stato inviato alla validazione un documento il cui CDAv2 è stato volutamente privato di uno dei tre valori (la pec).

Il referto risulta ugualmente validato anche se, da specifica, non dovrebbe.

Sempre nell'ambito della validazione si riscontra che quando l'elemento opzionale 'addr' di un paziente viene introdotto, il suo contenuto è parzialmente obbligatorio (elementi 'country', 'city' e 'streeAddressLine') ma la presenza dell'elemento anche vuoto risulta sufficiente ad ottenere la validazione. In altri termini il sistema di validazione considera giustamente non corretto l'elelemento mancante, ma considera "erroneamente corretto" l'elemento presente seppur privo di qualsiasi contenuto.

**Comment by LucaRogledi** [comment]
Buonasera, grazie della segnalazione.

Per quanto riguarda il campo "telecom", è stato scelto un approccio di controllo meno rigido. Questa scelta è stata dettata dalla considerazione che non sempre tutti i dati possono essere disponibili. Pertanto, il controllo è più flessibile per non escludere a priori le informazioni che possono risultare utili.

Inoltre, precisiamo che lo Schematron è in grado di verificare la presenza di un elemento specifico, come ad esempio "addr/country", all'interno di un documento CDA2. Tuttavia, è importante sottolineare che lo Schematron non è progettato per controllare la valorizzazione di alcuni campi come il "country". Questo tipo di verifica dovrebbe essere effettuata dall'applicativo che gestisce i dati, il quale dovrebbe assicurarsi che i campi siano correttamente valorizzati.

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
Grazie.
