### ISSUE TITLE
Versioni supportate sistemi di codifica

### ISSUE THREAD

**Issue by alessiomaggiori** [ministero-salute/it-fse-support#91]
Buongiorno,

otteniamo il seguente errore di Verifica CDA dal servizio di test:

{
   "traceID":"a2f9719a65558770",
   "spanID":"a2f9719a65558770",
   "type":"/msg/vocabulary",
   "title":"Errore vocabolario.",
   "detail":"È stata trovata almeno una versione non gestita di un dizionario: [2.16.840.1.113883.6.1 v2.19, 2.16.840.1.113883.5.1 v1.0]",
   "status":400,
   "instance":"/validation/error",
   "workflowInstanceId":"2.16.840.1.113883.2.9.2.100.4.4.79aa372021f31a7da129fb67e77706eee27a5117668183a6eff6bd2f9cfb3015.81a62ae805^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}

Omettendo le versioni dei due tag seguenti la validazione avviene correttamente.

<code code="11502-2" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" **codeSystemVersion="2.19"** displayName="Referto di Laboratorio" />

<administrativeGenderCode code="F" codeSystem="2.16.840.1.113883.5.1" codeSystemName="HL7 AdministrativeGender" **codeSystemVersion="1.0"** />

Potete indicarci quali versioni delle codifiche indicate possiamo utilizzare?

**Comment by IStacchiotti** [comment]
Buongiorno Alessio, le versioni dei dizionari attualmente gestite dal Gateway sono le seguenti: 
- 2.16.840.1.113883.6.1 v2.73; 
- 2.16.840.1.113883.5.1 v2.1.0. 

Se viene fornita la versione, il Gateway verifica che sia coerente con quella/e da lui gestite. Se viene omessa invece, il Gateway tratta il CodeSystem con l'ultima versione da lui conosciuta.
