### ISSUE TITLE
Modifica tipologia societaria

### ISSUE THREAD

**Issue by millenniumsrl** [ministero-salute/it-fse-support#910]
In data 14/06/24 è stata effettuata una modifica alla tipologia societaria, da Srl a Spa. Abbiamo necessità di sapere come procedere alla opportune modifiche, ad esempio relativamente ai dati profilo e a quelli inerenti l'accreditamento.

**Comment by millenniumsrl** [comment]
Sollecitiamo in riscontro in merito. Grazie

**Comment by millenniumsrl** [comment]
Buon pomeriggio,
la presente per comunicare che, a tutt'oggi, siamo ancora in attesa di riscontro.

Restiamo in attesa,

Cordiali saluti
Tonia De Vito
Delivery & QA Specialist

tel. +39 055 4554.41
fax. +39 055 4554.420
Email: ***@***.******@***.***>

***@***.***

Millennium S.p.A. | Via di Collodi 6/C | 50141 - Firenze (FI) | Italia

Mail disclaimer: Questa e-mail e tutti gli allegati possono contenere informazioni riservate e/o protette da diritti di proprietà intellettuale e sono destinati all'uso esclusivo del destinatario (o dei destinatari) sopra indicato. Qualsiasi uso delle informazioni qui contenute (incluso, ma non limitato a, riproduzione totale o parziale, comunicazione o distribuzione in qualsiasi forma) da parte di persone diverse dai destinatari designati è proibito. Se avete ricevuto questa e-mail per errore, vi preghiamo di avvisare il mittente per telefono o via e-mail e di cancellare il materiale da qualsiasi computer. Grazie per la vostra collaborazione.
[dont-print-email-small-green]  Pensa all'ambiente prima di stampare questo messaggio


Da: LucaRogledi ***@***.***>
Inviato: venerdì 19 luglio 2024 10:58
A: ministero-salute/it-fse-support ***@***.***>
Cc: Integrations Millennium ***@***.***>; Author ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Modifica tipologia societaria (Issue #910)


Buongiorno, le confermiamo che abbiamo segnalato il tema al team di competenza. Riceverà un riscontro in merito appena possibile, grazie.

-

**Comment by millenniumsrl** [comment]
Buongiorno,
restiamo in attesa di riscontro da parte del team di competenza, come indicatoci in data 19/07 u.s.


Cordiali saluti
Tonia De Vito
Delivery & QA Specialist

tel. +39 055 4554.41
fax. +39 055 4554.420
Email: ***@***.******@***.***>

***@***.***

Millennium S.p.A. | Via di Collodi 6/C | 50141 - Firenze (FI) | Italia

Mail disclaimer: Questa e-mail e tutti gli allegati possono contenere informazioni riservate e/o protette da diritti di proprietà intellettuale e sono destinati all'uso esclusivo del destinatario (o dei destinatari) sopra indicato. Qualsiasi uso delle informazioni qui contenute (incluso, ma non limitato a, riproduzione totale o parziale, comunicazione o distribuzione in qualsiasi forma) da parte di persone diverse dai destinatari designati è proibito. Se avete ricevuto questa e-mail per errore, vi preghiamo di avvisare il mittente per telefono o via e-mail e di cancellare il materiale da qualsiasi computer. Grazie per la vostra collaborazione.
[dont-print-email-small-green]  Pensa all'ambiente prima di stampare questo messaggio


Da: Integrations Millennium ***@***.***>
Inviato: lunedì 5 agosto 2024 15:39
A: ministero-salute/it-fse-support ***@***.***>; ministero-salute/it-fse-support ***@***.***>
Cc: Integrations Millennium ***@***.***>; Author ***@***.***>; Paola Di Marcello ***@***.***>
Oggetto: R: [ministero-salute/it-fse-support] Modifica tipologia societaria (Issue #910)

Buon pomeriggio,
la presente per comunicare che, a tutt'oggi, siamo ancora in attesa di riscontro.

Restiamo in attesa,

Cordiali saluti
Tonia De Vito
Delivery & QA Specialist

tel. +39 055 4554.41
fax. +39 055 4554.420
Email: ***@***.******@***.***>

***@***.***

Millennium S.p.A. | Via di Collodi 6/C | 50141 - Firenze (FI) | Italia

Mail disclaimer: Questa e-mail e tutti gli allegati possono contenere informazioni riservate e/o protette da diritti di proprietà intellettuale e sono destinati all'uso esclusivo del destinatario (o dei destinatari) sopra indicato. Qualsiasi uso delle informazioni qui contenute (incluso, ma non limitato a, riproduzione totale o parziale, comunicazione o distribuzione in qualsiasi forma) da parte di persone diverse dai destinatari designati è proibito. Se avete ricevuto questa e-mail per errore, vi preghiamo di avvisare il mittente per telefono o via e-mail e di cancellare il materiale da qualsiasi computer. Grazie per la vostra collaborazione.
[dont-print-email-small-green]  Pensa all'ambiente prima di stampare questo messaggio


Da: LucaRogledi ***@***.******@***.***>>
Inviato: venerdì 19 luglio 2024 10:58
A: ministero-salute/it-fse-support ***@***.******@***.***>>
Cc: Integrations Millennium ***@***.******@***.***>>; Author ***@***.******@***.***>>
Oggetto: Re: [ministero-salute/it-fse-support] Modifica tipologia societaria (Issue #910)


Buongiorno, le confermiamo che abbiamo segnalato il tema al team di competenza. Riceverà un riscontro in merito appena possibile, grazie.

-

**Comment by vigliottim** [comment]
Buonasera,
la informiamo che è stata modificata la tipologia societaria come richiesto.
Chiudiamo la presente issue e rimaniamo a disposizione.
Grazie.
