### ISSUE TITLE
Accreditamento secondo applicativo

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#911]
Buongiorno, vorremmo accreditare un altro nostro applicativo per la sola tipologia RSA. Per non commettere errori, potreste indicarci l'esatta procedura corretta?
Grazie mille.

P.S. Abbiamo provveduto ad eseguire la pull request correttiva richiesta.

**Comment by vigliottim** [comment]
Buongiorno, potrebbe gentilmente dirci se ha censito il nuovo applicativo su EuSurvey? Grazie.

**Comment by infoserviceonline** [comment]
Non ho ancora fatto assolutamente niente, prima di qualsiasi passo ho preferito chiedere.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, come primo passo è necessario sottomettere la richiesta di accreditamento su [EuSurvey](https://ec.europa.eu/eusurvey/runner/FSE-raccolta-id-applicativo) indicando tutti i servizi e cda gestiti dal nuovo applicativo. 
Successivamente, sarà necessario effettuare i test relativi alle tipologie documentali in esame. 
I risultati dei test eseguiti dovranno essere caricati su GitHub tramite una pull request in una cartella creata ad hoc per l'applicativo, che dovrà riflettere la struttura indicata in [documentazione](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/README.md#procedura-di-caricamento-dei-risultati): 
`GATEWAY/{commonName auth}/{subject_application_vendor}/{subject_application_id}/{subject_application_version}`
Poiché lei ha già creato tale cartella, sarà sufficiente inserire al suo interno le sottocartelle relative al secondo applicativo:
`GATEWAY/{commonName auth}/{subject_application_vendor}/{subject_application_id_app2}/{subject_application_version_app2}`

La pull request dovrà contenere:
- file _data.json_ contenente i riferimenti di tracciatura dei risultati dei test;
- file pdf usati nelle invocazioni dei servizi (all'interno della directory FILES);
- file riassuntivo (foglio di calcolo) _report-checklist.xlsx_ di tutti i test case eseguiti.

La informiamo, inoltre, che sarà necessario utilizzare l'ultima versione rilasciata del file report-checklist (V8.2), disponibile al link: https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/accreditamento-checklist_V8.2.xlsx
Rimaniamo a disposizione nel caso in cui avesse ulteriori dubbi.

**Comment by infoserviceonline** [comment]
Tutto chiarissimo, solo una domanda, se devo fare riferimento al nuovo file xlsx, vuol dire che sono cambiate anche le descrizioni dei test case contenute nei vari file Doc, e quindi devo scaricarli nuovamente?
Grazie.

**Comment by LucaRogledi** [comment]
Si, La informiamo che con il rilascio della nuova versione della checklist (v.8.2) sono stati modificati solamente i casi di test del PSS tenendo conto del decreto di settembre 2023, e sono state introdotte alcune migliorie alla struttura dati della checklist. Grazie

**Comment by infoserviceonline** [comment]
Ok, sarebbe anche così gentile da indicarmi il link? Ormai ci si perde per quanti ce ne sono.
Grazie.

**Comment by vigliottim** [comment]
Il link della nuova checklist è il seguente: https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/accreditamento-checklist_V8.2.xlsx
I casi di test per le varie tipologie documentali sono presenti sempre nella stessa cartella: https://github.com/ministero-salute/it-fse-accreditamento/tree/main/Test%20Case
Rimaniamo a disposizione per eventuali dubbi.

**Comment by infoserviceonline** [comment]
Ho effettuato la richiesta su EuSurvey. Devo attendermi un riscontro, positivo o negativo, o dò per scontato di aver fatto tutto bene?
Grazie.

**Comment by vigliottim** [comment]
La informiamo che non riceverà alcun riscontro in seguito all'invio della richiesta su EuSurvey.

**Comment by infoserviceonline** [comment]
Ok, grazie.
Chiudo

**Comment by vigliottim** [comment]
Buongiorno, la informiamo che ha eseguito correttamente tutte le indicazioni. Grazie.

**Comment by infoserviceonline** [comment]
Grazie, chiudo.
