### ISSUE TITLE
Problema accesso ai servizi

### ISSUE THREAD

**Issue by GruppoSiges** [ministero-salute/it-fse-support#912]
Buongiorno,

abbiamo ricevuto ieri i certificati, e sto provano a validare un CDA. Dopo aver generato i jwt, non riesco a validare il file in quanto ricevo questo errore:

error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

In rete non ho trovato indicazioni chiare sulla causa, potete suggerirmi qualche controllo da fare?

Grazie, saluti

**Comment by GruppoSiges** [comment]
Nel senso che oltre ai jwt va indicato il certificato come parametro (chiedo scusa se faccio domande scontate ma non sono propriamente un sistemista)?

**Comment by GruppoSiges** [comment]
Aggiornamento: ho modificato la chiamata ed ottengo un errore 401. E' plausibile che dipenda dai jwt?
Grazie

**Comment by vigliottim** [comment]
Buon pomeriggio, il certificato di autenticazione è necessario per effettuare le chiamate https. 
Qualora stia utilizzando un client come Postman, sarà possibile aggiungerlo nei settings come indicato qui: https://github.com/ministero-salute/it-fse-support/issues/654#issuecomment-1985853383
Nel caso in cui effettui una chiamata curl, esso andrà specificato come parametro:
`curl --cert-type P12 --cert A1#1XXXXXXX.p12: -X POST "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation" ...`
La invitiamo gentilmente ad aggiungerlo e riprovare. 
Grazie.

**Comment by vigliottim** [comment]
> Aggiornamento: ho modificato la chiamata ed ottengo un errore 401. E' plausibile che dipenda dai jwt? Grazie

Potrebbe cortesemente riportare la response completa? Grazie.

**Comment by GruppoSiges** [comment]
Eccola 
Ora ottengo un errore 403

{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"43077fcc-3ad3-11ef-a6bf-005056ae7395"}

**Comment by vigliottim** [comment]
Buonasera,
analizzando i log della chiamata da lei effettuata, è emerso che il campo _iss_ non è stato valorizzato correttamente:
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/1a26cc25-145c-414c-99e3-971718b5e3fd)
Come indicato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt), esso è rappresentato da una stringa composta da “integrity:”/“auth:” seguita dal “Common Name del certificato di firma”:
_**As-is:**_ "iss": "integrity:SYSCLINIQUE", "iss": "auth:SYSCLINIQUE"
_**To be:**_ "iss": "integrity:SYSDATSANITASRLXX", "iss": "auth:SYSDATSANITASRLXX"
Inoltre, la invitiamo a modificare il campo _sub_ eliminando il carattere **?**:
 "sub": "VDMQDC70D04F205I^^^ **?** 2.16.840.1.113883.2.9.4.3.2?ISO"
![image](https://github.com/ministero-salute/it-fse-support/assets/134372089/f9190212-e33f-4616-83b0-9b98f9c6e227)
La invitiamo a riprovare dopo aver applicato le correzioni suggerite.
Grazie.

**Comment by GruppoSiges** [comment]
Ho apportato le modifiche indicate, ma ottengo lo stesso errore. Allego l'ultima risposta ricevuta.

{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized request content","govway_id":"09695d9b-3ae0-11ef-a6bf-005056ae7395"}

**Comment by vigliottim** [comment]
Buongiorno,
Le chiediamo gentilmente di verificare di aver utilizzando il certificato di firma (S1XXXXXX) per la generazione dei JWT.
Inoltre, la invitiamo a riprovare valorizzando il campo _iss_ come riportato di seguito: 
**_As-is:_** "iss": "integrity:SYSDATSANITASRLXX", "iss": "auth:SYSDATSANITASRLXX"
**_To be:_** "iss": "integrity:S1#111#SYSDATSANITASRLXX", "iss": "auth:S1#111#SYSDATSANITASRLXX"
Restiamo a disposizione in caso l'errore dovesse ripresentarsi.
Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.

**Comment by GruppoSiges** [comment]
Confermo il superamento del problema del jwt.

Grazie, saluti.
