### ISSUE TITLE
Accreditamento A1#111#TS23XX

### ISSUE THREAD

**Issue by sviluppoTServe** [ministero-salute/it-fse-support#913]
Buongiorno,
volevo delle delucidazione inerenti allo stato avanzamento per accreditamento [A1#111#TS23XX]
Grazie.

**Comment by vigliottim** [comment]
Buonasera,
in virtù di quanto espresso all'interno del decredo 07 Settembre 2023, è stata pubblicata su GitHub una nuova versione della [checklist](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/accreditamento-checklist_V8.2.xlsx) (v8.2).
Essa comprende modifiche ad alcuni casi di test del PSS e, dal momento in cui l'applicativo TS23/TSERVE/V.1.4.46.0 gestisce proprio questa tipologia documentale, risulta necessario che compiliate la nuova versione della checklist e che la carichiate, tramite nuova PR, nella cartella di appartenenza dell'applicativo in sostituzione della precedente.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto. Grazie.
