### ISSUE TITLE
Accreditamento FLY

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#914]
Buongiorno, ho ricevuto la classica e-mail di avvenuto accreditamento a cui l'ultima volta ne sono seguite altre, una di richiesta di chiarimenti ed una di conferma di accreditamento.
Questa volta non ho ricevuto niente altro e vedo sul mio repository ben quattro file differenti di accreditamento automatico. 
https://github.com/infoserviceonline/it-fse-accreditamento/tree/main/GATEWAY/A1%23111%23INFOSERVICEONLINE/INFOSERVICE/FLY/2.0
Però sull'elenco accreditati, vedo solo la tipologia RAD e non anche RSA e LAB, come dovrebbe essere.
https://github.com/ministero-salute/it-fse-accreditati/blob/main/RESULTS/results.csv
Prima di proseguire vorrei capire qual è lo stato attuale.
Grazie mille.

**Comment by vigliottim** [comment]
Buongiorno, abbiamo effettuato delle verifiche e le confermiamo che al momento non sono necessarie azioni da parte sua. 
Pertanto, la invitiamo ad attendere nuove comunicazioni.
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
