### ISSUE TITLE
Verifica superamento test gateway per test per il Cliente Bolzano

### ISSUE THREAD

**Issue by Fusarolia** [ministero-salute/it-fse-support#916]
Nei giorni scorsi abbiamo fatto una validazione di certificato vaccinale per applicativo di Bolzano. 
Il cliente chiede se come sogei potete conferma se la validazione è stata fatta correttamente dandone evidenza con vostri messaggi interni di ricezione e risposta. 
Come riferimenti vi metto la risposta ottenuta dal vostro servizio.
  "traceID": "cc9d046129d26bd5",
  "spanID": "cc9d046129d26bd5",
   "workflowInstanceId": "2.16.840.1.113883.2.9.2.201.4.4.d3c9367ced3ca31c3a191a9dd34ca1613821ad097176f264ced83de2dd2f5e05.7ee2b66c60^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
               "Hash": "d0898d031c2f5a094e5680a09ffbaf54608d24dcd1401d5cb536858056d09aa6",

Attendo un vostro riscontro

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
Le confermiamo che la validazione è avvenuta correttamente. Le segnaliamo inoltre che è possibile verificare l'esito della chiamata tramite il servizio di status per [workflowInstanceId](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#10-servizio-di-recupero-stato-transazione-per-workflowinstanceid) o [TraceId](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#11-servizio-di-recupero-stato-transazione-per-traceid). Grazie

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
