### ISSUE TITLE
referto rad

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#918]
Buongiorno

Con FSE1.0 utilizzo il corpo destrutturato del cda per iniettare il pdf.
Con il cda strutturato, viene chiesto di compilare almeno le sezioni:
- 55111-9: esame eseguito
- 18782-3: referto

Da specifiche, la prima prevede una _table_ e un _entry/act_. Come mi comporto dinanzi un referto che si completa con due esami o più?
Per la table possa produrre tante righe (tr) quanti esami ma.. come mi comporto con _entry/act_? Qui, vedo i tag code, status e effectivetime. 

E' possibile avere un esempio o una soluzione? Il cliente esegue anche fino a 7 esami.

**Comment by vigliottim** [comment]
Buongiorno, 
nel caso in cui voglia inserire più esami all'interno della sezione _Esame eseguito_, deve aggiungere tanti elementi <tr> quanti sono gli esami all'interno della tabella _table_ di riferimento e posizionare i corrispondenti elementi _entry/act_ di seguito, in sequenza, prestando attenzione ai tag obbligatori. 
Le riportiamo uno schema di seguito che possa esserle d'aiuto nel creare la struttura del CDA2:

```
<section ID="ESAME_ESEGUITO">
<code code="XXXXXXXX" codeSystem="XXXXXXXXXX" codeSystemName="LOINC"
    displayName="XXXXXXXXXXXXX" />
<title>Esame Eseguito</title>
<text>
    <table>
        <thead>
            <tr>
                <th>Descrizione Esame</th>
                <th>Data Esecuzione</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Esame1</td>
                <td>Data1</td>
            </tr>
            <tr>
                <td>Esame2</td>
                <td>Data2</td>
            </tr>
            <tr>
                <td>Esame3</td>
                <td>Data3</td>
            </tr>
            <tr>
                <td>Esame4</td>
                <td>Data4</td>
            </tr>
        </tbody>
    </table>
</text>
<entry>
    <act moodCode="EVN" classCode="ACT">
     <code code="XXXX" codeSystem="XXXXXXXX" codeSystemName="XXXXXXX" displayName="XXXXX"/>
    <statusCode code="XXXX"/>
    <effectiveTime value="XXXXX" />
    </act>
</entry>
<entry>
    <act moodCode="EVN" classCode="ACT">
     <code code="XXXX" codeSystem="XXXXXXXX" codeSystemName="XXXXXXX" displayName="XXXXX"/>
    <statusCode code="XXXX"/>
    <effectiveTime value="XXXXX" />
    </act>
</entry>
<entry>
    <act moodCode="EVN" classCode="ACT">
    <code code="XXXX" codeSystem="XXXXXXXX" codeSystemName="XXXXXXX" displayName="XXXXX"/>
    <statusCode code="XXXX"/>
    <effectiveTime value="XXXXX" />
    </act>
</entry>
<entry>
    <act moodCode="EVN" classCode="ACT">
    <code code="XXXX" codeSystem="XXXXXXXX" codeSystemName="XXXXXXX" displayName="XXXXX"/>
    <statusCode code="XXXX"/>
    <effectiveTime value="XXXXX" />
        .......
    </act>
</entry>
```

Rimaniamo a disposizione nel caso in cui abbia bisogno di chiarimenti.
Grazie.

**Comment by ds-tommaso** [comment]
va benissimo così, grazie sempre per la disponibilità
