### ISSUE TITLE
Referto Radiologia

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#919]
Buongiorno

Ho aggiunto la branch ds-tommaso-rad per la validazione del referto di radiologia.
Per i referti di laboratorio ho già ottenuto l'accreditamento a marzo.

**Comment by vigliottim** [comment]
La ringraziamo per il gentile feedback.
Restiamo in attesa della sua pull-request per la nuova tipologia documentale per cui richiede l'accreditamento.
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
Grazie.
