### ISSUE TITLE
Livello di profondità codifiche loinc

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#92]
In accordo con i consulenti del DTD apro questa richiesta:

Il referto di laboratorio prevede la codifica degli esami secondo il nomenclatore LOINC. Qualora il CDA2 non contenga codici LOINC bensì altri codici o se i codici LOINC contenuti con fossero corretti, verrà fornito un warning o basterà un errore e l'intero documento verrà respinto? A quale livello di analisi si spingerà il validatore?

Grazie

**Comment by SonnyMate** [comment]
Grazie mille della risposta, ma evidentemente dobbiamo approfondire il contesto.
Le codifiche utilizzate nei vari laboratori non sono gestite da informatici o dal fornitore del LIS, bensi dai clinici. Pertanto sarebbe fondamentale avere un documento o una comunicazione per il business. Infatti, dobbiamo valutare eventuali impatti operativi all'interno dei reparti.
Vi chiederei quindi quali campi obbligatori prevedono le codifiche loinc e se questi sono controllati nel contenuto, ovvero se alcuni codici saranno scartati o è sufficiente che si usi quel dizionario.

**Comment by masciamariotti** [comment]
Buongiorno,
un campo obbligatorio che prevede la codifica LOINC è il codice della sezione di specialità di laboratorio (StructuredBody/component/section/code) il quale deve essere valorizzato con uno dei codici riportati nella tabella in appendice 7.2.1 della guida implementativa. Qualora questo campo non venisse valorizzato correttamente, si genera un errore bloccante.
Si consiglia inoltre di valorizzare con LOINC i codici inerenti alle obervation che riportano le informazioni sulla misurazione.

**Comment by SonnyMate** [comment]
"Si consiglia inoltre di valorizzare con LOINC i codici inerenti alle obervation che riportano le informazioni sulla misurazione."

Prendiamo atto che per i singoli risultati non è obbligatorio il codice LOINC, in particolare non ci saranno controlli bloccanti in tal senso. 

Contrariamente a quanto previsto dalle specifiche di HL7 italia al pragrafo 5.2.7.8.3 observation.

Se abbiamo compreso correttamente si può chiudere.

**Comment by masciamariotti** [comment]
Buongiorno,
si conferma che il controllo viene emesso come un warning e non come un'asserzione bloccante nel caso in cui il campo "code" dell'observation non venga valorizzato secondo la codifica LOINC, poiché, anche se consigliato, potrebbe essere possibile che tale sistema di codifica non copra tutte le possibili prestazioni ed esami che si vogliono rappresentare all'interno del referto.

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
