### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by Andr3a93** [ministero-salute/it-fse-support#921]
Buongiorno,
Da ieri l'endpoint di test sembra non raggiungibile , invocando il servizio di validazione otteniamo questa risposta:

StatusCode: 503, ReasonPhrase: 'Service Unavailable', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  X-Backside-Transport: FAIL FAIL
  Connection: Keep-Alive
  Transfer-Encoding: chunked
  Retry-After: 344
  Pragma: no-cache
  GovWay-Message-ID: 1720685727
  GovWay-Transaction-ErrorType: APIUnavailable
  GovWay-Transaction-ID: e6633679-3f5b-11ef-a6bf-005056ae7395
  Vary: *
  X-Content-Type-Options: nosniff
  X-Global-Transaction-ID: 3f7e3e2d668f94b960468bad
  Cache-Control: no-store, must-revalidate, no-cache
  Date: Thu, 11 Jul 2024 08:15:53 GMT
  Server: GovWay-SOGEI
  Content-Type: application/problem+json
  Expires: 0
}

Hanno funzionato correttamente nei giorni precedenti, sapete dirci di cosa si tratta.
Grazie per la disponibilità.

**Comment by LucaRogledi** [comment]
Buongiorno, come segnalato sul canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM) stiamo registrando dei disservizi temporanei. Seguiranno aggiornamenti non appena i servizi saranno ripristinati. Grazie

**Comment by Andr3a93** [comment]
Ok grazie.
