### ISSUE TITLE
RETI DI PATOLOGIA

### ISSUE THREAD

**Issue by sviluppoTServe** [ministero-salute/it-fse-support#922]
Buongiorno, mi servirebbero i codici delle varie reti di patologia.
Entry\Act\code\code=**??**
Entry\Act\code\CodeSystem="2.16.840.1.113883.2.9.2.30.3.1.3.6.10.1"
Entry\Act\code\DisplayName = "Rete IMA"
Grazie

**Comment by vigliottim** [comment]
Buongiorno, 
potrebbe cortesemente indicarci a quale tipologia documentale di CDA2 fa riferimento?
Grazie.

**Comment by sviluppoTServe** [comment]
Buongiorno,
scusate l'informazione mi serve per il PSS
Grazie

**Comment by vigliottim** [comment]
Buon pomeriggio, si segnala che il _codeSystem_ riportato come esempio è un dizionario regionale. 
A livello nazionale non esiste un vocabolario specifico per le Reti di Patologia. 
Possono essere utilizzate delle codifiche locali e/o regionali.

**Comment by vigliottim** [comment]
Buon pomeriggio, 
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
