### ISSUE TITLE
cda - inFulfillmentOf - ricetta rossa

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#924]
Buongiorno

Con FSE20, è possibile compilare l'attributo _inFulfillmentOf/order/id/@extension_ con il barcode della ricetta rossa (non dematerializzata)?

**Comment by vigliottim** [comment]
Buongiorno,
potrebbe cortesemente indicarci la tipologia di CDA2 a cui fa riferimento? 
Grazie.

**Comment by ds-tommaso** [comment]
LAB / RAD

**Comment by vigliottim** [comment]
Buongiorno, 
come descritto nelle rispettive guide HL7 Italia per [RAD ](https://www.hl7.it/wp-content/uploads/2024/04/HL7IT-IG_CDA2_RAD-v1.1-S.pdf) e [LAB](https://www.hl7.it/wp-content/uploads/2024/04/HL7IT-IG-CDA2_RefertoMedicinaLab-v1.3-S.pdf), all'interno di _inFulfillmentOf/order_ possono essere mappati gli identificativi di prescrizioni cartacee.
In particolare, l'elemento _inFulfillmentOf/order/id/extension_ deve essere valorizzato come segue:
- **CDA2 di tipo RAD**
![image](https://github.com/user-attachments/assets/4d73e831-5a03-4320-917a-804d9e2ca754)
- **CDA2 di tipo LAB**
![image](https://github.com/user-attachments/assets/684c758e-0164-491a-ac2c-eb758e49441a)

![image](https://github.com/user-attachments/assets/b5eecfc5-e6f0-4353-8a81-d6b1571d8f11)

Rimaniamo a disposizione per chiarimenti.
