### ISSUE TITLE
Problema SSL

### ISSUE THREAD

**Issue by mvolpe-fvg** [ministero-salute/it-fse-support#925]
Buongiorno,

Stiamo cercando di condurre il test di validazione con il gateway, ma al momento l'end-point di prova ricavato dalla documentazione it-fse-support: 

https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1

ritorna CONNECTION_RESET_ERROR, secondo noi dovuto alla mancanza di un certificato SSL valido. Esiste un altro end-point per le prove? Dobbiamo installare noi un certificato SSL sul nostro server di test infrastruttura di Aria (Policlinico di Milano)?

Anche provando dal browser riceviamo lo stesso errore.

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
L'url da lei riportato non corrisponde all'url del servizio di validazione: "https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation".

Per effettuare correttamente una chiamata al servizio di validazione messo a disposizione dal gateway è necessario:
- Utilizzare i certificati che può ottenere effettuando la richiesta alla casella di progetto  [fse_support@sogei.it](mailto:fse_support@sogei.it) inviando 2 CSR, una per il certificato di autenticazione e una per il certificato di firma , come indicato al seguente link: https://github.com/ministero-salute/it-fse-support?tab=readme-ov-file#richiesta-certificati-x509
- Generare correttamente i certificati .p12 a partire dai file .pem, come da indicazioni contenute a questo link: https://github.com/ministero-salute/it-fse-support/issues/591#issuecomment-1923419907
- Utilizzare un applicativo per effettuare la chiamata dei servizio [validazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#3-servizio-di-validazione), per esempio tramite Postman, per cui se possono esserle utili sono presenti le indicazioni per la configurazione nel seguente messaggio: https://github.com/ministero-salute/it-fse-support/issues/654#issuecomment-1985853383
 
La generazione dei token da utilizzare per la chiamata può essere fatta tramite l'utilizzo del tool "jwt-generator" scaricabile al link: https://github.com/ministero-salute/it-fse-gtw-tools. Ricordiamo infine che per stabilire la connessione https è necessario selezionare il certificato in formato p12 di autorizzazione (A1***) , mentre per la generazione dei token (Bearer e Signature) è necessario impiegare quello di firma (S1***).  
 
Restiamo a disposizione per eventuali chiarimenti.
Grazie

**Comment by mvolpe-fvg** [comment]
Anche con CURL si ottiene immediatamente lo stesso risultato: CONNECTION RESET
Mi potrebbe spiegare come esplicitare l'utilizzo del p12 durante la connessione con CURL o in Postman?
Il problema qui appare immediatamente, ben prima della verifica della correttezza della chiamata.

**Comment by vigliottim** [comment]
Buonasera, 
per avere supporto nell'utilizzo di Postman può consultare il seguente link (è spiegato anche come inserire il certificato p12 richiesto):
[654#issuecomment-1985853383](https://github.com/ministero-salute/it-fse-support/issues/654#issuecomment-1985853383)
Se preferisce effettuare le chiamata ai servizi tramite curl, può inserire il certificato di autenticazione tramite i due parametri riportati di seguito: 
`--cert-type P12 --cert A1***.p12:PASSWORD .........` 
dove `A1***.p12` è il suocertificato di Autenticazione e `PASSWORD` è la relativa password. 
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Buongiorno, 
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
