### ISSUE TITLE
Problema con test 40

### ISSUE THREAD

**Issue by GasNetGroup** [ministero-salute/it-fse-support#926]
ho riscontrato che il test 40 mi torna un risultato anomalo, di cui non capisco l’origine…
 
Come da specifiche eseguo una validazione inviando il valore di “TEST” al posto di “VALIDATION” nel payload:
 
{
    "activity": "TEST",
    "mode": "ATTACHMENT",
    "healthDataFormat": "CDA"
}
 
La risposta che ricevo riporta un errore, come atteso, ma si tratta di un 400 e non di un 403, e il json di risposta è privo delle proprietà  traceID e workflowInstanceId:
 

{
    "request_headers": {
        "User-Agent": "python-requests/2.31.0",
        "Accept-Encoding": "gzip, deflate",
        "Accept": "application/json",
        "Connection": "keep-alive",
        "Authorization": "Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "FSE-JWT-Signature": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "Content-Length": "87314",
        "Content-Type": "multipart/form-data; boundary=82a73c18244de853e5f201f421565559"
    },
    "status_code": 400,
    "text": "{\"type\":\"https://govway.org/handling-errors/400/InvalidRequestContent.html\",\"title\":\"InvalidRequestContent\",\"status\":400,\"detail\":\"Request content not conform to API specification: Validation error(s) :\\nbody.requestBody.activity: Value 'TEST' is not defined in the schema. (code: 1006)\\nFrom: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.activity.<enum>\\n\",\"govway_id\":\"3f389734-4445-11ef-a6bf-005056ae7395\"}"
}

Quindi non sono in grado di popolare in modo corretto report-checklist.xlsx e data.json

Allego i dump estratti in fase di validazione, non sono ancora riuscito a capire cosa sto sbagliando… potreste darmi un’indicazione?

[20240717160950_GASNET_RSA_CDA_CT_00_ID_040_KO_ACTIVITY_AS_TEST20240605_jwt_auth_data.json](https://github.com/user-attachments/files/16267893/20240717160950_GASNET_RSA_CDA_CT_00_ID_040_KO_ACTIVITY_AS_TEST20240605_jwt_auth_data.json)
[20240717160950_GASNET_RSA_CDA_CT_00_ID_040_KO_ACTIVITY_AS_TEST20240605_jwt_data.json](https://github.com/user-attachments/files/16267894/20240717160950_GASNET_RSA_CDA_CT_00_ID_040_KO_ACTIVITY_AS_TEST20240605_jwt_data.json)
[20240717160950_GASNET_RSA_CDA_CT_00_ID_040_KO_ACTIVITY_AS_TEST20240605_pdf.pdf](https://github.com/user-attachments/files/16267895/20240717160950_GASNET_RSA_CDA_CT_00_ID_040_KO_ACTIVITY_AS_TEST20240605_pdf.pdf)
[20240717160950_GASNET_RSA_CDA_CT_00_ID_040_KO_ACTIVITY_AS_TEST20240605_request_data.json](https://github.com/user-attachments/files/16267896/20240717160950_GASNET_RSA_CDA_CT_00_ID_040_KO_ACTIVITY_AS_TEST20240605_request_data.json)
[20240717160950_GASNET_RSA_CDA_CT_00_ID_040_KO_ACTIVITY_AS_TEST20240605_response.json](https://github.com/user-attachments/files/16267897/20240717160950_GASNET_RSA_CDA_CT_00_ID_040_KO_ACTIVITY_AS_TEST20240605_response.json)

**Comment by vigliottim** [comment]
Buonasera, il caso di test con id = 40 corrisponde ad un caso di test di tipo KO:

![image](https://github.com/user-attachments/assets/2204be69-53bd-4395-8b3c-8e92bdfc6de6)

Essi prevedono l'introduzione voluta di un errore per testare uno specifico comportamento.
Pertanto, è corretto che la validazione non vada a buon fine.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by GasNetGroup** [comment]
So che è corretto ricevere un errore, mi sembrava di aver letto dovesse essere un 403, potrei essermi sbagliato ed in fondo è secondario.

Quello invece che mi mette in difficoltà è che la risposta che mi viene tornata non contiene il traceId e il workflowInstanceId, che sono necessari per compilare il caso nella report-checklist xlsx:

{
  "type": "https://govway.org/handling-errors/400/InvalidRequestContent.html",
  "title": "InvalidRequestContent",
  "status": 400,
  "detail": "Request content not conform to API specification: Validation error(s) :\nbody.requestBody.activity: Value 'TEST' is not defined in the schema. (code: 1006)\nFrom: body.requestBody.<#/components/schemas/ValidationCDAReqDTO>.activity.<enum>\n",
  "govway_id": "3f389734-4445-11ef-a6bf-005056ae7395"
}

Vedo che altri fornitori hanno popolato le colonne con dei valori per il test case 40, e il relativo elemento nel data.json, quindi ritengo dovrei riceverli in risposta...

**Comment by vigliottim** [comment]
Buongiorno,
non riceve l'errore atteso (403) poiché il test prevede che il campo _"action_id"_ sia valorizzato con la stringa _"TEST"_ mentre lei ha valorizzato il campo _"activity"_ con la stringa _"TEST"_.
La invitiamo a effettuare la correzione suggerita e riprovare.
Grazie.

**Comment by GasNetGroup** [comment]
Perfetto, grazie, il test è andato a buon fine, scusate per la svista
