### ISSUE TITLE
Mancato accreditamento A1#111#TS23XX 

### ISSUE THREAD

**Issue by sviluppoTServe** [ministero-salute/it-fse-support#927]
Buongiorno,
ieri mi avete inviato una email di mancato accreditamento perché mancavano i seguenti test:
[ {
  "error" : "TEST_NON_PRESENTE",
  "description" : "Test mancanti rispetto alla checklist:[170, 171, 172, 375]"
} ]
I suddetti test non sono presenti nella vostra check accreditamento-checklist_V8.2, allego il file.
Vogliate darmi ulteriori informazioni.
[accreditamento-checklist_V8.2.xlsx](https://github.com/user-attachments/files/16279143/accreditamento-checklist_V8.2.xlsx)
Ringrazio anticipatamente per il vostro aiuto.

**Comment by IStacchiotti** [comment]
Buongiorno @sviluppoTServe, l'errore segnalato era dovuto ad un disallineamento interno nel censimento degli id di test, per il quale ci scusiamo, che è stato indirizzato nella giornata di ieri. In seguito, sono stati eseguiti nuovamente i test automatici, per cui dovrebbe aver ricevuto un nuovo riscontro via email, al quale la preghiamo di far riferimento. Rimaniamo a disposizione per ulteriori chiarimenti/esigennze di supporto, grazie.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
Grazie.
