### ISSUE TITLE
Json output GET status - Evento "EDS_WORKFLOW" in errore "Error: failed to publish bundle"

### ISSUE THREAD

**Issue by osinfocer** [ministero-salute/it-fse-support#93]
L'esito de l metodo  GET status di un Workflow Instance Id di un documento inviato con successo riporta l'errore per l'eventType "EDS_WORKFLOW""Error: failed to publish bundle".

Riporto un esempio per 
`2.16.840.1.113883.2.9.2.50502.4.4.e3f98985a76fb97bb809fa69144a960c6bd09c69fbb7c9cc84c598faa76082cc.1c5506970a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

ma lo rilevo per tutti i documenti che carico.

> 
{

	"traceID": "af1874e12669bcfd",
	"spanID": "cd2a62063af77ada",
	"transactionData": [
		{
			"eventType": "VALIDATION",
			"eventDate": "2023-02-08T15:23:21.287+00:00",
			"eventStatus": "SUCCESS",
			"subject": "VRDMRC67T20I257E^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"organizzazione": "190",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.50502.4.4.e3f98985a76fb97bb809fa69144a960c6bd09c69fbb7c9cc84c598faa76082cc.1c5506970a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "c3f19ac9dfbf0a4d",
			"issuer": "integrity:S1#111INFOCER0000",
			"expiringDate": "2024-02-08T15:23:21.350+00:00"
		},
		{
			"eventType": "PUBLICATION",
			"eventDate": "2023-02-08T15:23:23.891+00:00",
			"eventStatus": "SUCCESS",
			"identificativoDocumento": "2.16.840.1.113883.2.9.2.120.4.4^24978",
			"subject": "VRDMRC67T20I257E^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
			"tipoAttivita": "CON",
			"organizzazione": "190",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.50502.4.4.e3f98985a76fb97bb809fa69144a960c6bd09c69fbb7c9cc84c598faa76082cc.1c5506970a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"traceId": "6069f68b123d1fed",
			"issuer": "integrity:S1#111INFOCER0000",
			"expiringDate": "2024-02-08T15:23:23.900+00:00"
		},
		{
			"eventType": "SEND_TO_INI",
			"eventDate": "2023-02-08T15:23:24.043+00:00",
			"eventStatus": "SUCCESS",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.50502.4.4.e3f98985a76fb97bb809fa69144a960c6bd09c69fbb7c9cc84c598faa76082cc.1c5506970a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"expiringDate": "2024-02-08T15:23:24.652+00:00"
		},
		{
			"eventType": "SEND_TO_EDS",
			"eventDate": "2023-02-08T15:23:24.284+00:00",
			"eventStatus": "SUCCESS",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.50502.4.4.e3f98985a76fb97bb809fa69144a960c6bd09c69fbb7c9cc84c598faa76082cc.1c5506970a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"expiringDate": "2024-02-08T15:23:25.467+00:00"
		},
		{
			"eventType": "EDS_WORKFLOW",
			"eventDate": "2023-02-08T15:23:34.815+00:00",
			"eventStatus": "BLOCKING_ERROR",
			"message": "Error: failed to publish bundle",
			"workflowInstanceId": "2.16.840.1.113883.2.9.2.50502.4.4.e3f98985a76fb97bb809fa69144a960c6bd09c69fbb7c9cc84c598faa76082cc.1c5506970a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
			"expiringDate": "2024-02-08T15:23:34.892+00:00"
		}
	]
}

**Comment by IStacchiotti** [comment]
Buongiorno, per risolvere l'errore, è necessario aggiungere l'ID mancante all'elemento represented Organization di Legal Authenticator.

**Comment by osinfocer** [comment]
Salve. Purtroppo il problema permane. Ho provato a levare l'indicazione del represented Organization di Legal Authenticator (in quanto ho visto che nell'esempio LAB.xml del progetto non è stato specificato) ma il problema permane.
Il workflow instance id è il seguente: 

2.16.840.1.113883.2.9.2.50502.4.4.1.34558ad953893b88e77a42bb2740d1e58d01e552ef3c6979220a8e7afaf69dd2.411a4439ad^^^^urn:ihe:iti:xdw:2013:workflowInstanceId

Proverò a sostiture tag per tag il mio CDA2 con i dati dell'esempio del CDA2 di laboratorio LAB.xml e poi vi farò sapere.

**Comment by IStacchiotti** [comment]
Considerando il CDA2 che abbiamo ricevuto, se l'elemento legal authenticator viene modificato come segue: 
<legalAuthenticator>
<time value="20230208141025+0200"/>
<signatureCode code="S"/>
<assignedEntity>
<id root="2.16.840.1.113883.2.9.4.3.2" extension="SPNMRO76M24L483M" displayable="true"/>
<code displayName="SPANGARO OMAR"/>
<assignedPerson>
<name>
<family>SPANGARO</family>
<given>OMAR</given>
</name>
</assignedPerson>







</assignedEntity>
</legalAuthenticator>

quindi commentando il representedOrganization, il problema non si presenta.

Anche se si prova ad aggiungere un id al representedOrganization:
<legalAuthenticator>
<time value="20230208141025+0200"/>
<signatureCode code="S"/>
<assignedEntity>
<id root="2.16.840.1.113883.2.9.4.3.2" extension="SPNMRO76M24L483M" displayable="true"/>
<code displayName="SPANGARO OMAR"/>
<assignedPerson>
<name>
<family>SPANGARO</family>
<given>OMAR</given>
</name>
</assignedPerson>

<representedOrganization>
<id root="2.16.840.1.113883.2.9.4.1.9" extension="050113"/>
<name>
<delimiter>INFOCERT SPA</delimiter>
</name>
</representedOrganization>

</assignedEntity>
</legalAuthenticator>

il problema non si presenta.

**Comment by osinfocer** [comment]
Indicando quanto segue

![image](https://user-images.githubusercontent.com/100203966/221888421-61359b85-c5f4-4d5c-ac5e-f2f5a0619729.png)


 per il workflow instance id  

`2.16.840.1.113883.2.9.2.50502.4.4.1.089b6b65bb0d787c6f89e5ad741ca2f55bd830c4ff5cc445cb94d4c3a543fb07.c25e8c7007^^^^urn:ihe:iti:xdw:2013:workflowInstanceId`

l'esito è il medesimo. 

Ho però notato che il problema non si presenta se per il tag <participant> uso l'xml dell'esempio vale a dire :

```
<participant typeCode="REF" contextControlCode="OP">
		<functionCode code="PRE" codeSystem= "2.16.840.1.113883.2.9.5.1.88"/>  
		<time value="20220320110000+0100"/> 	
		<associatedEntity classCode="QUAL">
			<id root="2.16.840.1.113883.2.9.4.3.2" extension="PROVAX00X00X000Y" assigningAuthorityName="MEF"/>
			<addr>
				<country>100</country>
				<state>120</state>
				<county>RM</county> 
				<city>Roma</city> 
				<censusTract>058091</censusTract> 
				<postalCode>00187</postalCode> 
				<streetAddressLine>Via Vittorio Veneto 3</streetAddressLine>
			</addr>
			<telecom use="HP" value="mailto:prova.provax@example.com"/>
			<associatedPerson>
				<name>
					<family>Esempio</family>
					<given>Silvia</given>
				</name>
			</associatedPerson>
			<scopingOrganization>
				<id root="2.16.840.1.113883.2.9.4.1.2" extension="120148" assigningAuthorityName="Ministero della Salute"/><!-- STS11-->
				<name></name>
				<name>SAN RAFFAELE NOMENTANA</name>
				<telecom use="WP" value="tel:3340000000"/> 
				<addr> 
					<country>100</country>
					<state>120</state>
					<county>RM</county> 
					<city>Roma</city> 
					<censusTract>058091</censusTract>
					<postalCode>00137</postalCode> 
					<streetAddressLine>Via Emilio Praga 39</streetAddressLine> 
				</addr>	
			</scopingOrganization>
		</associatedEntity>
	</participant>

```
tag che valorizzo come da indicazioni delle linee guida regionali del Veneto per il referto di laboratoio

al posto di quello che indico io nel cda2 : 
```

  <participant typeCode="DEV" nullFlavor="MSK">
    <associatedEntity classCode="LIC" nullFlavor="MSK">
      <id displayable="false" extension="2.16.840.1.113883.2.9.2.50.4.5.00000" root="2.16.840.1.113883.2.9.2.50.4.5"/>
    </associatedEntity>
  </participant>
```

**Comment by IStacchiotti** [comment]
Ho notato che abbiamo commentato simultaneamente. Ci potrebbe far sapere se riesce a risolvere con le indicazioni riportate nel mio precedente messaggio, relative all'elemento _legal authenticator_? Grazie mille

**Comment by osinfocer** [comment]
No, non ha effetto la modifica al legalAuthenticator.
Se vuole verificare il workflow 2.16.840.1.113883.2.9.2.50502.4.4.1.d965d36c00460ecc361f22bfe51b506a51109bc74fc7fc02dd569b8436cbc70e.e8bed81b82^^^^urn:ihe:iti:xdw:2013:workflowInstanceId
che ho appena mandato dove ho  commentato la "representedOrganization"  (in allegato il cda inviato )
[cda2-001.txt](https://github.com/ministero-salute/it-fse-support/files/10851671/cda2-001.txt)

Se invece invio come da suo secondo esempoi (con la "representedOrganization" valorizzata mi fallisce il check di validazione indicandomi: [ERRORE-47| L’elemento 'name' di un'organizzazione non deve contenere i sotto elementi 'delimiter', 'prefix', 'suffix'.].

Tuttavia invece le confermo che l'errore non si presenta se valorizzo il participant come da vostro esempio al posto di quello che compilo io. In tal caso il problema non si presenta e la GetStatus non mi restituisce errori e inoltre riesco in questo modo anche a usare la funzione di DELETTE del documento. 

Tuttavia come le scrivevo sopra uso tale formato per il  participant per seguire le linee guida CDA2 lab del Veneto...

**Comment by osinfocer** [comment]
In aggiunta a quanto ho indicato le indico il workflow instance id di un documento mandato correttamente dove ho evitato di indicare il "participant":

`2.16.840.1.113883.2.9.2.50502.4.4.1.caeef808428f6e18c9c525012bd2d3e6f314ff657cb168175a74b4454affa752.4672f43d4e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId`

e l'esito della getstatus dove non c'è l'errore bloccante:

```
{
  "traceID": "c3df2fc599629db5",
  "spanID": "32e3059bb07243f1",
  "transactionData": [
    {
      "eventType": "VALIDATION",
      "eventDate": "2023-02-28T15:18:34.233+00:00",
      "eventStatus": "SUCCESS",
      "subject": "VRDMRC67T20I257E^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "organizzazione": "190",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.50502.4.4.1.caeef808428f6e18c9c525012bd2d3e6f314ff657cb168175a74b4454affa752.4672f43d4e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "62278883b4293f65",
      "issuer": "integrity:S1#111INFOCER0000",
      "expiringDate": "2024-02-28T15:18:34.294+00:00"
    },
    {
      "eventType": "PUBLICATION",
      "eventDate": "2023-02-28T15:18:37.568+00:00",
      "eventStatus": "SUCCESS",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.120.4.4^25202",
      "subject": "VRDMRC67T20I257E^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
      "tipoAttivita": "CON",
      "organizzazione": "190",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.50502.4.4.1.caeef808428f6e18c9c525012bd2d3e6f314ff657cb168175a74b4454affa752.4672f43d4e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "68a11e00ea1d7481",
      "issuer": "integrity:S1#111INFOCER0000",
      "expiringDate": "2024-02-28T15:18:37.577+00:00"
    },
    {
      "eventType": "SEND_TO_INI",
      "eventDate": "2023-02-28T15:18:37.595+00:00",
      "eventStatus": "SUCCESS",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.50502.4.4.1.caeef808428f6e18c9c525012bd2d3e6f314ff657cb168175a74b4454affa752.4672f43d4e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2024-02-28T15:18:38.428+00:00"
    },
    {
      "eventType": "SEND_TO_EDS",
      "eventDate": "2023-02-28T15:18:37.658+00:00",
      "eventStatus": "SUCCESS",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.50502.4.4.1.caeef808428f6e18c9c525012bd2d3e6f314ff657cb168175a74b4454affa752.4672f43d4e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2024-02-28T15:18:39.195+00:00"
    }
  ]
}
```

**Comment by osinfocer** [comment]
Buongiorno dal punto di vista prettamente tecnico penso che il bug possa essere ritenuto risolto con la conclusione che non posso passare il tag "participant" compilato come segue:

```
  <participant typeCode="DEV" nullFlavor="MSK">
    <associatedEntity classCode="LIC" nullFlavor="MSK">
      <id displayable="false" extension="2.16.840.1.113883.2.9.2.50.4.5.00000" root="2.16.840.1.113883.2.9.2.50.4.5"/>
    </associatedEntity>
  </participant>

```
che però come accennavo è compilato in tal modo in base alle linee guida "CDA2 Medicina di Laboratorio GDL-O Documenti Clinici v2.5" della Regione Veneto di cui porto l'estratto specifico: 

![image](https://user-images.githubusercontent.com/100203966/222099077-940569b6-5f51-4791-8804-6e180e9ad9eb.png)

**Comment by Ser-ena** [comment]
Buonasera, confermiamo quanto indicato nei commenti, infatti considerando quanto suggerito nella linea guida CDA2 del Referto di Laboratorio e valorizzando l'elemento id del participant con un Codice Fiscale l'errore non si presenta.

**Comment by osinfocer** [comment]
Sì, chiaro e confermo anche io con una prova che ho fatto quanto mi dice (2.16.840.1.113883.2.9.2.50502.4.4.1.d4aac42c2d5484994af59c3b5ce6febd556107cf94442440d2cd297320c7b620.66693f1701^^^^urn:ihe:iti:xdw:2013:workflowInstanceId)

 Come scrivevo sopra tuttavia le linee guida Regione Veneto mi impongono  di indicare
nell' _id_  gli estremi delll'applicativo generante il referto e in particolare di indicare:

| Attributo      | Valore | Descrizione     |
| :---        |    :----:   | :--- |
| root      | 2.16.840.1.113883.2.9.2.50.4.5       | root degli id per gli applicativi labellati per la Regione Veneto  |
| extension | '2.16.840.1.113883.2.9.2.50.4.5.xxxxx        |  Dove xxxxx è l'odentificativo del Sw rilasciato a seguito della sessione  di labeling |
| displayable | false       |  Dove xxxxx è l'odentificativo del Sw rilasciato a seguito della sessione  di labeling |

ragion per cui il codice fiscale non è attinente.
Per ora risolvo aggirando la problematica e indicando il participant come segue:

![image](https://user-images.githubusercontent.com/100203966/222471967-100e6195-0ac9-4032-90b7-06d885d2825f.png)


Alla base tuttavia mi avete chiarito il motivo per il quale il documento non veniva pubblicato e vi ringrazio.

**Comment by IStacchiotti** [comment]
Buonasera, la presente viene chiusa come risolta. Si può procedere con la riapertura del ticket se dovessero sorgere nuove problematiche. Grazie
