### ISSUE TITLE
ERRORE: L'elemento ClinicalDocument/componentOf è obbligatorio 

### ISSUE THREAD

**Issue by mvolpe-fvg** [ministero-salute/it-fse-support#930]
Salve,

Non capisco dove stia l'errore:

`{"traceID":"b28ac3e93eb32801","spanID":"b28ac3e93eb32801","type":"/msg/semantic","title":"Errore semantico.","detail":"[ERRORE-39| L'elemento ClinicalDocument/componentOf è obbligatorio ]","status":422,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.30925.4.4.deb1cef9d4f10cca87f3f01b9908266fc167f3b8c5902fe91e3f331ae1eacc72.eb44b895b9^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

PDF con il CDA:

[finalPDFA3.pdf](https://github.com/user-attachments/files/16284241/finalPDFA3.pdf)

**Comment by vigliottim** [comment]
Buongiorno,
nel CDA2 in allegato non è presente l'elemento obbligatorio _ClinicalDocument/componentOf_ secondo la guida HL7 Italia:

<img width="575" alt="image" src="https://github.com/user-attachments/assets/b396a3eb-605c-43ba-b583-05dccfd1fbdf">

Di seguito trova due link che possono esserle utili per strutturare correttaemente il documento:
- Guida HL7 Italia per RSA: https://www.hl7.it/wp-content/uploads/2024/04/HL7IT-IG_CDA2_RSA-v1.1-S.pdf
- Esempio di CDA2 per RSA: https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/RSA.xml

Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Buongiorno, 
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
