### ISSUE TITLE
Errore 400 in Recupero Stato Transazione per WorkflowInstanceId

### ISSUE THREAD

**Issue by GruppoSiges** [ministero-salute/it-fse-support#931]
Buongiorno, 

continuo a ricevere un errore 400 (senza altre informazioni) nella funzione di recupero stato transazione per workflowInstanceId. Ho provato ad utilizzare invece il recupero stato transazione per traceId e quello invece funziona (dopo avere modificato l'url per aggiungere /search).

Dato che le due funzioni sono praticamente identiche, non ho idea di cosa verificare. Potete darmi indicazioni?

Grazie, saluti.

**Comment by vigliottim** [comment]
Buongiorno,
l'errore potrebbe essere causato dal fatto non è stato fatto l'url encode del _workflowIstanceId_ quando si inserisce il parametro {workflowInstanceId} nell'url del servizio:
`/v1/status/{workflowInstanceId}`
![image](https://github.com/user-attachments/assets/ab79a0f3-f388-448c-a10a-0b829a631442)
Può usare il seguente tool online per effettuare l'encoding: https://www.urlencoder.org/
Nel caso non fosse questo il problema, le chiediamo di inviare la response completa. 
Grazie.

**Comment by GruppoSiges** [comment]
Immaginavo che potesse essere quello. Avevo provato a fare l'encoding, ma l'avevo fatto di tutto l'url e non funzionava lo stesso.
Proverò ad integrare il vostro suggerimento.

Grazie, saluti.

**Comment by GruppoSiges** [comment]
Così funziona. 

Grazie ancora.

**Comment by vigliottim** [comment]
Grazie a lei per il gentile feedback.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
