### ISSUE TITLE
Info pull request

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#933]
Buongiorno

Sono a chiedere informazioni circa la pull request, ormai aperta da una decina di giorni. 

https://github.com/ministero-salute/it-fse-accreditamento/pull/1562

**Comment by ds-tommaso** [comment]
Aggiungo.. ad un centro in Campania viene chiesto di inviare i referti FSE2.0. 

Immagino si parli del solo iniettare il Cda nel referto firmato Padrs. Scrivo qui perché ho risposta da GestioneTS da un mese e più. 

Quando invio un pdf con comunicazioneMetadati ottengo un codice temporaneo. A seguire, devo contattare EsitoCaricamento per ottenere l'OK effettivo. Con la chiamata al metodo, però, ottengo errore sul messaggio MTOM. 

Il metodo è ancora valido? Chiedo perché scaricando i nuovi kit non c'è traccia di questo metodo. 
Vedo solo RecuperoDocumento che però va utilizzo con le cancellazioni.

**Comment by IStacchiotti** [comment]
Buongiorno,
 
La PR da voi aperta non è stata lavorata dal momento che risulta contenere solo i test di VALIDAZIONE LAB, per i quali l'applicativo risulta già accreditato. 
Se l'intenzione è quella di aggiungere al perimetro di accreditamento anche RAD, vi inviteremmo a caricare nuovamente il file di checklist, dal momento che risulta corrotto, con possibile perdita dei contenuti.
Inoltre, le facciamo presente che, come riportato in [documentazione](https://github.com/ministero-salute/it-fse-accreditamento#nuova-tipologia-documentale-per-applicativo-gi%C3%A0-presente-nella-lista-dei-software-convalidati), nel momento in cui si aggiunga una nuova tipologia documentale in seguito al conseguimento dell'accreditamento per una diversa, occorre ripetere l'accreditamento per tutte le tipologie documentali.
Per questo consigliamo di inviare fin da subito una checklist comprensiva di tutti i CDA per i quali si intende accreditarsi, altrimenti si dovranno ripetere tutti i casi di test ogni qualvolta si intenda aggiungere una nuova tipologia documentale.

In merito al suo ultimo messaggio invece, le confermiamo riceverà un riscontro direttamente dall'email di GestioneTS.
 
Rimaniamo a disposizione per eventuali ulteriori richieste di supporto, grazie

**Comment by ds-tommaso** [comment]
Buongiorno

Ho sottoposto a nuova validazione i documenti CDA del referto di laboratorio.
Trovate una nuova commit per la pull in oggetto con i dati aggiornati (Excel, Json e PDF).

https://github.com/ministero-salute/it-fse-accreditamento/pull/1562/commits/3536200929945430b05d36f6c8a876c85e1cfaf0

**Comment by vigliottim** [comment]
Buongiorno, 
la informiamo che la pull request è stata creata correttamente.
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
