### ISSUE TITLE
Incongruenza validazione e pubblicazione di un documento

### ISSUE THREAD

**Issue by masIorio** [ministero-salute/it-fse-support#934]
Buongiorno, effettuando alcuni test ci siamo inbattituti nella seguente problematica:
abbiamo creato un documento, in particolare una Lettera di Dimissione Ospedaliera, ed iniettato il relativo CDA2. Successivamente, abbiamo invocato il servizio di validazione del documento senza riscontrare problemi e con esito positivo.
In un secondo momento, abbiamo provato la pubblicazione del medesimo documento su FSE e soltanto in questo momento è stato segnalato un errore relativo alla valorizzazione di un campo all'interno del CDA2 (si trattava del campo "Unità di misura" della posologia di un farmaco).

Vorrei quindi chiedere, il motivo di tale errore e se, come sembra, la validazione effettuata dal servizio di validazione è differente da quella effettuata in fase di pubblicazione e risulta quindi non attendibile.

Ringrazio anticipatamente.

**Comment by vigliottim** [comment]
Buongiorno, le chiediamo di inviarci cortesemente la response completa ricevuta (comprensiva di trace id/govway id) per effettuare indagini più approfondite. Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori aggiornamenti, procediamo alla chiusura della presente issue. 
Può procedere alla riapertura in caso avesse bisogno di ulteriore supporto. Grazie.
