### ISSUE TITLE
Annullamento documento Lettera di Dimissione Ospedaliera

### ISSUE THREAD

**Issue by masIorio** [ministero-salute/it-fse-support#936]
Effettuando alcuni test in merito all'annullamento di un documento di tipo Lettera di Dimissione Ospedaliera mi sono ritrovato il seguente errore:

{"response":{"phase":"FSE DELETE","errorCode":"ERR_BAD_RESPONSE","errorDescriptions":["javax.xml.ws.soap.SOAPFaultException: [400] Documento documenteID_fb15cb29-82e7-4815-a350-414146988ed6_v2 inesistente"],"FseErrorMessage":"Request failed with status code 500","FseErrorCode":"ERR_BAD_RESPONSE","FseHttpStatus":"500","FseResponseDetail":"javax.xml.ws.soap.SOAPFaultException: [400] Documento **documenteID_fb15cb29-82e7-4815-a350-414146988ed6_v2 inesistente**","FseResponseType":"midlleware-500"},"status":500,"message":"Error Payload Exception","name":"ErrorPayloadException"}

Questo errore si verifica esclusivamente quando provo ad annullare un documento con una versione successiva alla prima.

Vi ringrazio.

**Comment by vigliottim** [comment]
Buongiorno,
le chiediamo se sta chiamando i servizi FSE 2.0 o se sta passando tramite il middleware e di verificare che il nome del documento che intende cancellare sia corretto:
**documenteID_fb15cb29-82e7-4815-a350-414146988ed6_v2**
Inoltre, al fine di effettuare indagini più approfondite, le chiediamo il traceid/govwayid sia della chiamata di pubblicazione che di quella di cancellazione.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori aggiornamenti, procediamo alla chiusura della presente issue. 
Può procedere alla riapertura in caso avesse bisogno di ulteriore supporto. Grazie.
