### ISSUE TITLE
Accreditamento Repository Lazio: Errore Cancellazione Documento 

### ISSUE THREAD

**Issue by asja-git** [ministero-salute/it-fse-support#937]
Buongiorno, 

io e alcuni miei colleghi stiamo eseguendo il piano di test previsto per il collaudo per l'integrazione con FSE attraverso il middleware di Regione Lazio. La situazione è la seguente: riusciamo con successo a validare il documento e a pubblicarlo, tuttavia arrivati al momento della cancellazione riceviamo sempre lo stesso errore che riporto di seguito:

{
    "status": 500,
    "response": "{\"govway_id\":\"20240723124828\",\"detail\":\"javax.xml.ws.soap.SOAPFaultException: [400] Documento 2023070411_129 inesistente\",\"title\":\"Internal error\",\"type\":\"midlleware-500\",\"status\":500}"
}

Se riproviamo la cancellazione nuovamente, il tipo di messaggio di risposta che riceviamo è invece di questo tipo:

{
    "status": 404,
    "response": "{\"traceID\":\"a4e001200563814c\",\"spanID\":\"a4e001200563814c\",\"type\":\"/msg/eds-error\",\"title\":\"Eds error.\",\"detail\":\"Document cannot be found on the Server FHIR\",\"status\":404,\"instance\":\"/msg/eds-document-missing\"}"
}

Verificando la pubblicazione con il servizio status a cui passiamo il rispettivo workflowInstanceId (2.16.840.1.113883.2.9.2.120.4.4.a3abc849589614d598dc55b4d8043cb58fc489c0c006e2c753e92d374c057334.d73427e427^^^^urn:ihe:iti:xdw:2013:workflowInstanceId), a noi sembra che la pubblicazione del documento sia andata a buon fine. 

Gentilmente, sarebbe possibile ricevere supporto per capire il motivo per cui l'eliminazione del documento non va a buon fine?

Grazie mille in anticipo,
Restiamo in attesa!

**Comment by LucaRogledi** [comment]
Buon pomeriggio,
Confermiamo che la pubblicazione sembrerebbe essere avvenuta con successo, pubblicando come riportato all'interno della status per workflowInstanceId il documento: `2.16.840.1.113883.2.9.2.120.4.4^2023070411_129`

Dal messaggio di errore ricevuto:
`"detail":"javax.xml.ws.soap.SOAPFaultException: [400] Documento 2023070411_129 inesistente"`
sembrerebbe che sia stata effettuata la delete del documento: `2023070411_129`.

La invitiamo a riprovare effettuando la delete del documento pubblicato con id `2.16.840.1.113883.2.9.2.120.4.4^2023070411_129` ricordando di applicare l'url encode all'identificativo del documento da eliminare, ottenendo: `2.16.840.1.113883.2.9.2.120.4.4%5E2023070411_129`. 

Rimaniamo a disposizione in caso il problema non dovesse risolversi. 
Grazie

**Comment by asja-git** [comment]
Buongiorno, 

Grazie mille innanzitutto per il feedback, lato nostro abbiamo verificato ciò che inviamo attraverso uno sniffer di rete e quello che transita ci risulta essere di questo tipo:

DELETE /documents/2.16.840.1.113883.2.9.2.120.4.4%5E2023070411_129 HTTP/1.1
Accept: application/json
Authorization: Bearer X
FSE-JWT-Signature: X
Host: X
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.13 (Java/1.8.0_202)
Accept-Encoding: gzip,deflate

Dove i campi "Authorization: Bearer", "FSE-JWT-Signature" e "Host" sono stati censurati con una X per motivi di privacy. 

L'id del documento da cancellare (2.16.840.1.113883.2.9.2.120.4.4%5E2023070411_129) a noi sembra corretto, per cui non capiamo il motivo per cui poi, nel messaggio di risposta, sembri che l'id del documento di cui proviamo a effettuare la delete sia 2023070411_129. 

In attesa, 
grazie mille per la disponibilità!

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
L'identificativoDoc utilizzato per la chiamata di delete come da lei riportato sembra essere corretto.
Dalle nostre verifiche il servizio di delete funziona correttamente.
Le suggeriamo di verificare che il documento che state cercando di eliminare non sia stato sostituito in precedenza o eliminato, in tal caso la invitiamo ad utilizzare un nuovo identificativoDoc valido che può ottenere dalla validazione e pubblicazione di un nuovo documento.
Restiamo a disposizione in caso il problema dovesse ripresentarsi. Grazie

**Comment by asja-git** [comment]
Buongiorno, 

grazie mille per il feedback. 
Procederemo a verificare l'anomalia direttamente con il middleware del Lazio. 

Ringrazio nuovamente per la disponibilità!
Cordiali Saluti

**Comment by LucaRogledi** [comment]
Buongiorno,
Ringraziamo per il feedback e procediamo alla chiusura della presente issue.
La invitiamo a riaprire la segnalazione in caso fosse necessario ulteriore supporto.
Grazie
