### ISSUE TITLE
Codici LOINC

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#939]
Buongiorno, vorrei avere conferma se i codici Loinc che si trovano su https://www.loinc.it/, che poi rimanda al sito https://loinc.org/downloads/ sono quelli giusti da utilizzare nel FSE. Essendo un misto di italiano ed inglese mi è venuto un dubbio.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno, le confermiamo che può trovare i codici LOINC al link: [https://loinc.org](https://loinc.org)

**Comment by infoserviceonline** [comment]
Grazie mille, chiudo.
