### ISSUE TITLE
Error while perform transform cda to bundle:Rule \"line\": target context not known: line

### ISSUE THREAD

**Issue by abozzetto** [ministero-salute/it-fse-support#94]
Buongiorno, 
    dopo aver validato un documento abbiamo provato a pubblicarlo, ma il servizio ci risponde con un errore che non riusciamo a capire:
```json
{
    "traceID": "615bfec80d5560bb",
    "spanID": "615bfec80d5560bb",
    "type": "/msg/fhir-mapping-type",
    "title": "Mapping fhir fallito.",
    "detail": "Error while perform transform cda to bundle:Rule \"line\": target context not known: line",
    "status": 400,
    "instance": "/fhir-resource"
}
```
E' possibile avere qualche dettaglio in più ?
Grazie

**Comment by abozzetto** [comment]
Aggiungo che un altro documento ci ha dato ul seguente errore:
```

{
    "traceID": "5bc1f6c4f543142f",
    "spanID": "5bc1f6c4f543142f",
    "type": "/msg/fhir-mapping-type",
    "title": "Mapping fhir fallito.",
    "detail": "Error while perform transform cda to bundle:Exception executing transform e13.fullUrl = append('https://example/Practitioner/', uuid13) on Rule \"org\": Variable uuid13 not found (source variables [obs: (http://hl7.org/fhir/cda/StructureDefinition/Observation), participant: (http://hl7.org/fhir/cda/StructureDefinition/Participant2), participantRole: (http://hl7.org/fhir/cda/StructureDefinition/ParticipantRole), id: (http://hl7.org/fhir/cda/StructureDefinition/II), r: (string), ext: (string)], target variables [patient: (Patient), encounter: (Encounter), ob: (Observation), bundle: (Bundle), reference: (Reference), e12: (BackboneElement), practitionerRole: (PractitionerRole), uuid12: (string), participant1: (BackboneElement), referencepart: (Reference), e13: (BackboneElement), request: (BackboneElement), practitioner: (Practitioner), identifier: (Identifier), uuid4: (string)], shared variables [])",
    "status": 400,
    "instance": "/fhir-resource"
}
```
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, il problema dovrebbe essere rientrato. Potrebbe riprovare cortesemente? Grazie.

**Comment by abozzetto** [comment]
Si ora funziona. Grazie

**Comment by alessiomaggiori** [comment]
Buongiorno,

ho riprovato più volte ma ottengo lo stesso errore.

…
"traceID": "dab654c35501e841",
  "spanID":"dab654c35501e841",
…

Grazie per l’attenzione


--

Ing. Alessio Maggiori
Software Engineering
***@***.***
Mobile: +39 340 3753229
Email: ***@***.******@***.***>
Web: http://www.prometeonet.it<http://www.prometeonet.it/>

***@***.***  ***@***.***



Da: IStacchiotti ***@***.***>
Inviato: venerdì 17 febbraio 2023 11:28
A: ministero-salute/it-fse-support ***@***.***>
Cc: Alessio Maggiori ***@***.***>; Manual ***@***.***>
Oggetto: Re: [ministero-salute/it-fse-support] Error while perform transform cda to bundle:Rule \"line\": target context not known: line (Issue #94)


Buongiorno, il problema dovrebbe essere rientrato. Potrebbe riprovare cortesemente? Grazie.

**Comment by IStacchiotti** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
