### ISSUE TITLE
Crash program - Bolzano - Campo 'sub' token JWT

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#940]
Si chiede un chiarimento sul campo sub dei token JWT e Signature. 
Nel caso d'uso di un middleware regionale, questo campo poter assumere valori che identificano la Provincia autonoma di Bolzano, il middleware Regionale/Nodo Regionale.

In alternativa dovreste autorizzarci ad utilizzare uno dei CF presenti all'interno dei metadati o del documento.

**Comment by vigliottim** [comment]
Buongiorno,
il campo _sub_ presente nei JWT deve essere valorizzato con il codice fiscale dell'utente che fa richiesta del servizio, come indicato in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#131-campi-contenuti-nei-jwt):

![image](https://github.com/user-attachments/assets/c3a6e361-8360-419e-920b-71b8e00bcc85)

Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by SonnyMate** [comment]
Buongiorno,
quanto previsto in documentazione è chiaro. Tuttavia, la pubblicazione non è una richiesta effettuata da un utente, ma da un sistema. Suppongo quindi che la vostra risposta implichi necessariamente utilizzare il CF dell'autore del documento per procedere alla pubblicazione.

Se confermate si può chiudere.

Personalmente vi invito a riflettere sulla possibilità di gestire anche operatori virtuali o nodi regionali per eventuali operazioni massive. Negli ultimi anni ce ne sono state nel FSE1.0

**Comment by vigliottim** [comment]
Buongiorno,
le confermiamo che al momento è necessario un codice fiscale all'interno del campo _sub_.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
