### ISSUE TITLE
Richiesta supporto validazione e pubblicazione

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#942]
Buongiorno,
stiamo cercando di verificare il corretto funzionamento di base dei servizi prima di procedere con gli sviluppi.
Per questo motivo abbiamo fatto alcune chiamate manualmente, potreste verificare come mai otteniamo il seguente errore?

{
    "type": "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
    "title": "AuthorizationContentDeny",
    "status": 403,
    "detail": "Unauthorized request content",
    "govway_id": "8ac120da-4a7b-11ef-a6bf-005056ae7395"
}

**Comment by vigliottim** [comment]
Buongiorno,
dalle analisi effettuate sui log della chiamata con "govway_id": "8ac120da-4a7b-11ef-a6bf-005056ae7395", sono stati riscontrati i seguenti errori nella valorizzazione dei campi dei token indicati di seguito:

**Authorization Bearer:**
<table><tr><th>As is</th><th>To be</th></tr>
<tr>
<td>"Jti": 1721909041</td><td>"jti": 1721909041</td>
</tr>
<tr>
<td>"iss": "auth:A2#041#PABOLZANOTEST"</td><td>"iss": "auth:SXXXXXXXXXX"</td>
</tr>
</table>


**FSE-JWT-Signature:**
<table><tr><th>As is</th><th>To be</th></tr>
<tr>
<td>"Jti": 1721909041</td><td>"jti": 1721909041</td>
</tr>
<tr>
<td>"iss": "integrity:S2#041#PABOLZANOTEST"</td><td>"iss": "integrity:SXXXXXXXXXX"</td>
</tr>
</table>

La invitiamo a verificare di aver utilizzato il certificato di autenticazione (AXXXXXXXXXX) per il trasporto e il certificato di firma (SXXXXXXXXXX) per la generazione dei token Authorization Bearer e FSE-JWT-Signature.
Rimaniamo a disposizione nel caso in cui avesse bisogno di ulteriore supporto.

**Comment by SonnyMate** [comment]
Perfetto! grazie.
