### ISSUE TITLE
Errore servizio sostituzione documento: Wrong attribute value or authority not known of $RESOURCEIDURN$

### ISSUE THREAD

**Issue by federicolau** [ministero-salute/it-fse-support#943]
Ciao,

effettuando la seguente richiesta:

```
PUT https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation/2.16.840.1.113883.2.9.2.120.4.4%5E030702456

Content-Disposition: form-data; name="requestBody"
Content-Type: multipart/form-data; charset=UTF-8
Content-Transfer-Encoding: 8bit

{   "assettoOrganizzativo": "AD_PSC001",   "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^030702456",   "identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.1",   "identificativoSottomissione": "2.16.840.1.113883.2.9.4.3.2",   "tipoAttivitaClinica": "PHR",   "tipoDocumentoLivAlto": "WOR",   "tipologiaStruttura": "Ospedale",   "attiCliniciRegoleAccesso": [     "PUBLICPOL"   ],   "conservazioneANorma": "NormativaXYZ",   "descriptions": [     "019655^Bentelan^2.16.840.1.113883.2.9.6.1.5"   ],   "administrativeRequest": [     "SSN",     "INPATIENT"   ],   "mode": "ATTACHMENT",   "healthDataFormat": "CDA"}

Content-Disposition: form-data; name="file"; filename="output.pdf"
Content-Type: application/pdf
Content-Transfer-Encoding: binary
```

stiamo ottenendo il seguente errore:

**Client received SOAP Fault from server: Wrong attribute value or authority not known of $RESOURCEIDURN$ Please see the server log to find more detail regarding exact cause of the failure**

Allego:

- [PDF con CDA iniettato](https://github.com/user-attachments/files/16379561/output.pdf)
- [Authorization token](https://github.com/user-attachments/files/16379587/authorization_token.txt)
- [FSE-JWT-Signature token](https://github.com/user-attachments/files/16379586/fse_jwt_ignature_token.txt)

Come possiamo risolvere?

Grazie.

**Comment by LucaRogledi** [comment]
Buonasera,
L'url utilizzato durante la chiamata di sostituzione da lei riportata non risulta corretto. 
La invitiamo ad effettuare la correzione rimuovendo "validation" dall'url per effettuare la chiamata del [servizio di sostituzione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway#61-request) e riprovare:

`https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.120.4.4%5E030702456`

Restiamo a disposizione in caso l'errore dovesse ripresentarsi.
Grazie

**Comment by federicolau** [comment]
Erroneamente avevo incollato male la URL presa dalla nostra batteria di test. La chiamata effettuata è la seguente e l'errore è quello già anticipato:

```
PUT https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.120.4.4%5E030702456

PUT data:
--z6-xz5BEklnQSu9pHxp1oROjoIytVzRz4r
Content-Disposition: form-data; name="requestBody"
Content-Type: multipart/form-data; charset=UTF-8
Content-Transfer-Encoding: 8bit

{   "assettoOrganizzativo": "AD_PSC001",   "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^030702456",   "identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.1",   "identificativoSottomissione": "2.16.840.1.113883.2.9.4.3.2",   "tipoAttivitaClinica": "PHR",   "tipoDocumentoLivAlto": "WOR",   "tipologiaStruttura": "Ospedale",   "attiCliniciRegoleAccesso": [     "PUBLICPOL"   ],   "conservazioneANorma": "NormativaXYZ",   "descriptions": [     "019655^Bentelan^2.16.840.1.113883.2.9.6.1.5"   ],   "administrativeRequest": [     "SSN",     "INPATIENT"   ],   "mode": "ATTACHMENT",   "healthDataFormat": "CDA"}
--z6-xz5BEklnQSu9pHxp1oROjoIytVzRz4r
Content-Disposition: form-data; name="file"; filename="output.pdf"
Content-Type: application/pdf
Content-Transfer-Encoding: binary

<actual file content, not shown here>
--z6-xz5BEklnQSu9pHxp1oROjoIytVzRz4r--





[no cookies]
```


Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, potrebbe cortesemente condividere la risposta completa ricevuta dalla chiamata che restituisce l'errore, comprendendo _govway_id_ e _traceID_, in caso siano disponibili? Grazie

**Comment by federicolau** [comment]
A voi la risposta completa:

`{"traceID":"ba150120668c5db7","spanID":"ba150120668c5db7","type":"/msg/ini-error","title":"Ini error.","detail":"{\"traceID\":\"0000000000000000ba150120668c5db7\",\"spanID\":\"54594ed0bae63a06\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"Client received SOAP Fault from server: Wrong attribute value or authority not known of $RESOURCEIDURN$ Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}","status":500,"instance":"/msg/service-error/ini"}`

**Comment by izamberlan** [comment]
In test eseguiti recentemente abbiamo riscontrato anche noi il problema, superato eliminando l'url encoding degli ampersand.

**Comment by federicolau** [comment]
Ma io necesitto di fare l'escape perchè altrimenti mi va in errore il client da cui mando la richiesta.

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
Non avendo la possibilità di effettuare operazioni di debug sui client, la invitiamo ad aprire un post sul [canale Slack fse](https://developersitalia.slack.com/archives/C03RDT88FSM) rivolto alla community, nel caso un altro utente abbia riscontrato la medesima anomalia e possa fornirle supporto. 
Restiamo a disposizione per eventuale ulteriore supporto. Grazie

**Comment by federicolau** [comment]
Ciao @LucaRogledi,

l'issue **non** può passare in "completed".
Noi **dobbiamo** ovviamente fare l'escape dei caratteri speciali come anche voi, giustamente, riferite:

![image](https://github.com/user-attachments/assets/7976c9c6-57d8-425d-b85e-d32bcf200726)

_Riferimento issue_: https://github.com/ministero-salute/it-fse-support/issues/528

Riaprite l'issue altrimenti dovrò aprirne un altro.

Resto quindi sempre in attesa su come risolvere questo problema.


Grazie

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
non avendo modo di effettuare operazioni di debug sui client specifici utilizzati, la invitiamo

**Comment by LucaRogledi** [comment]
Buongiorno, 
Per facilitare le anailsi, potrebbe gentilmente condividere il dato che sembrerebbe generare l'errore in seguito all'url encode se disponibile? 
Ringraziamo per la collaborazione.

**Comment by izamberlan** [comment]
Se può essere utile, noi abbiamo superato l'errore non facendo l'encoding dei codici fiscali  (mettendo semplicemente & anziché &amp;)

**Comment by federicolau** [comment]
> Se può essere utile, noi abbiamo superato l'errore non facendo l'encoding dei codici fiscali (mettendo semplicemente & anziché "& amp;") (spazio aggiunto per evitare che appaia esattamente come l'altro &)

Ok grazie per l'informazione. Più precisamente quali codici fiscali dovrei controllare, quelli presenti nel CDA o quelli in fase di generazione del token?

@LucaRogledi inoltre, altra informazione importante che è emersa proprio adesso che stiamo conducendo ulteriori test, questo stesso errore ci viene resituito anche per il servizio di cancellazione di un documento e di aggiornamento metadati.

**Comment by federicolau** [comment]
> Quelli su cui abbiamo fatto la modifica sono i CF contenuti nei JWT (sub e person_id)

Grazie, ha funzionato!

**Comment by LucaRogledi** [comment]
Ringraziamo @izamberlan per l'intervento risolutivo e @federicolau per la collaborazione. Procediamo con la chiusura della issue e restiamo a disposizione per ulteriore supporto. Grazie
