### ISSUE TITLE
Referto Radiologia - Campania

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#946]
Buongiorno

Un cliente che pubblica referti FSE1.0 ci inoltra il documento (allegato).
In breve, si parla di adeguare il sw per 
- Invio dei documenti clinici in formato PDF/A, con HL7 CDA2 iniettato e firmati digitalmente con firma PaDES
- Integrazione con la nuova architettura FSE 2.0

Cosa si intende al secondo punto?

Occorre eseguire la validazione nel Gateway se pur pubblicato in ambiente di test?
So che sistema ts ha modificato i tracciati, consentendo la pubblicazione di referti fse2.0 compliant (in solo ambiente di test però), dovendo poi indicare il WorkflowInstanceId nelle opzioni request.

[Allegato-21122023112842_001_21122023112842 (1).pdf](https://github.com/user-attachments/files/16393032/Allegato-21122023112842_001_21122023112842.1.pdf)

**Comment by LucaRogledi** [comment]
Buonasera, 
Se intende pubblicare referti con FSE 1.0 non è richiesto il passaggio attraverso il gateway di FSE 2.0.
Con il secondo punto si intende che il software deve essere adeguato in modo da poter utilizzare le risorse e gli endpoint messi a disposizione dal FSE 2.0 indicati in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway). 
Restiamo a disposizione per ulteriori richieste di supporto.
Grazie.

**Comment by ds-tommaso** [comment]
Il gateway non è pubblicato in solo ambiente di test?
Sarebbe già possibile utilizzarlo per validazione ed pubblicazione, ovvero modifica e cancellazione?

La documentazione (che segue) asserisce che debba validare il CDA ma utilizzare sempre i servizi "FSE1.0 - fseComunicazioneMetadati" per la pubblicazione. La domanda vale anche per le altre due regioni in sussidiarietà Abruzzo e Sicilia (dove però mi sembra di capire non abbiano fatto il Crash Program).

[SpecificheTecniche-INI-Sussidiarietà_v20240703_Integrazione_Replace_SOGEI.docx](https://github.com/user-attachments/files/16394270/SpecificheTecniche-INI-Sussidiarieta_v20240703_Integrazione_Replace_SOGEI.docx)

**Comment by LucaRogledi** [comment]
Buongiorno, 
Confermiamo che il gateway per fse 2.0 è in ambiente di test e può essere utilizzato per le chiamate da lei indicate e riportate anche in [documentazione](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway); il fse 1.0 invece viene utilizzato per la pubblicazione in quanto disponibile in ambiente di produzione. 
Segnaliamo inoltre che, nel caso di Regioni in sussidiarietà come la Campania, occorre far riferimento ai servizi messi a disposizione da Sogei per la pubblicazione.
La invitiamo infine a rimuovere il documento a diffusione limitata lasciato in allegato nel suo ultimo commento e rimaniamo a disposizione per chiarimenti. Grazie

**Comment by ds-tommaso** [comment]
Sul documento "*_replace" si parla di inviare referti FSE 2.0 compliant utilizzando i servizi messi a disposizione di Sogei (dopo validazione del Gateway; alla ComunicazioneMetadatiRichiesta occorre aggiungere la terna GATEWAY, WORKFLOWINSTANCEID e MODE alle opzioni request)

"Per il colloquio con FSE 2.0, relativamente alla richiesta di aggiornamento metadati, deve essere invocato il servizio di aggiornamento metadati esposto dal Gateway."

REPLACE e DELELE passando dunque per il Gateway? Se è in test, comunque i referti saranno aggiornati nella realtà?

**Comment by LucaRogledi** [comment]
Buongiorno, Le confermiamo che i servizi esposti dal gateway fse2.0 sono disponibili in ambiente di test, dunque non possono essere utilizzati per aggiornare l'ambiente di produzione, contenente dati reali. 
Per agire in ambiente di produzione la invitiamo ad invocare le apposite API esposte dal fse 1.0 oppure, nel caso specifico della Campania (regione in sussidiarietà), i servizi dedicati messi a disposizione da Sogei.
La invitiamo a monitorare il canale [Slack fse](https://developersitalia.slack.com/archives/C03RDT88FSM) per aggiornamenti riguardo l'avvio in produzione del gateway fse 2.0 e restiamo a disposizione per eventuale supporto. 
 
Riguardo la pull request indicata https://github.com/ministero-salute/it-fse-accreditamento/pull/1562 riceverà aggiornamenti il prima possibile.
Grazie.

**Comment by ds-tommaso** [comment]
Ok allora il problema potrebbe essere la sola terna dell'applicativo (allo stato attuale, invio ancora "Middleware150 v. 1.0").

Presumo dunque che il documento "Regione Abruzzo" sia propedeutico per il futuro, con GTW in produzione.
e - forse - inutile aver chiesto a fse_support i certificati per il cliente, inviando loro le due CSR.

Rimango in attesa del riscontro della pull. A seguire, aggiorno il cliente.
Se non prevedete di rispondere a quest'ultimo commento, potete chiudere l'issue.

Grazie sempre per la disponibilità

**Comment by LucaRogledi** [comment]
Buon pomeriggio, ringraziamo per il feedback e procediamo alla chiusura. Seguiranno aggiornamenti via email riguardo l'esito dell'elaborazione della pull request https://github.com/ministero-salute/it-fse-accreditamento/pull/1562 . Grazie
