### ISSUE TITLE
CRASH PROGRAM - referenceIdList assente 

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#947]
Buon pomeriggio,
ho notato l'assenza nel body del messaggio del metadato referenceIdList. Questo è essenziale in particolare per la gestione dell'oscuramento a catena.

Lo recupera il gateway dal contenuto nel documento o lo inserisce tra i metadati?

Grazie

**Comment by SonnyMate** [comment]
Buongiorno,
avete per caso novità?

**Comment by vigliottim** [comment]
Buonasera,
è stato rilasciato un aggiornamento.
Potreste cortesemente riprovare e darci un riscontro?
Grazie.

**Comment by SonnyMate** [comment]
Ci vorrà un po'

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
La informiamo che sarà possibile riaprirla nel caso in cui abbia bisogno di ulteriore supporto.
Grazie.
