### ISSUE TITLE
403 "AuthorizationContentDeny"

### ISSUE THREAD

**Issue by mrepu** [ministero-salute/it-fse-support#95]
Buongiorno,
sto facendo chiamate per la cancellazione di un documento precedentemente pubblicato ma ricevo la seguente risposta. Cosa c'è di sbagliato?
{
    "type": "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
    "title": "AuthorizationContentDeny",
    "status": 403,
    "detail": "Unauthorized request content",
    "govway_id": "af910ee0-a851-11ed-b7ba-005056ae54fa"
}

**Comment by mrepu** [comment]
Buongiorno,
il campo iss nel  json con cui genero il JWT ha questa forma

"iss": "S1#111WERFEN00000"

e vedo che decodificando il JWT ottenuto, viene aggiunto "auth:" davanti al valore. Ma se lo aggiungo io al json utilizzato per la generazione del JWT viene generato in modo errato come "auth:auth:...."

Come posso compilare il json per poter ottenere il formato giusto?

**Comment by IStacchiotti** [comment]
Buongiorno, può ricorrere al tool jwt-generator (se non lo sta già utilizzando), scaricabile a questo [link](https://github.com/ministero-salute/it-fse-gtw-tools), per la generazione dei token. Se prova a decodificare con jwt.io i token così generati, vedrà in testa sul campo "iss" rispettivamente "auth" e "integrity" per il token bearer e signature. Grazie

**Comment by mrepu** [comment]
Ciao. Sto usando proprio il jwt-generator, per questo non mi è chiaro quale sia il punto in cui ci sono dati sbagliati.

**Comment by masciamariotti** [comment]
Buongiorno, da un'analisi più approfondita sembrerebbe che stia invertendo i 2 token: questi sembrano generati correttamente, ma quello di Authorization Bearer lo sta passando al posto del FSE-JWT-Signature, e viceversa.
Ci faccia sapere se il problema persiste

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
