### ISSUE TITLE
Errore servizio sostituzione documento: Non è stato possibile recuperare i riferimenti con i dati forniti in input

### ISSUE THREAD

**Issue by federicolau** [ministero-salute/it-fse-support#950]
Ciao,

effettuando la seguente richiesta:

```
PUT https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation/2.16.840.1.113883.2.9.2.120.4.4%5E030702456

Content-Disposition: form-data; name="requestBody"
Content-Type: multipart/form-data; charset=UTF-8
Content-Transfer-Encoding: 8bit

{   "assettoOrganizzativo": "AD_PSC001",   "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^030702456",   "identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.1",   "identificativoSottomissione": "2.16.840.1.113883.2.9.4.3.2",   "tipoAttivitaClinica": "PHR",   "tipoDocumentoLivAlto": "WOR",   "tipologiaStruttura": "Ospedale",   "attiCliniciRegoleAccesso": [     "PUBLICPOL"   ],   "conservazioneANorma": "NormativaXYZ",   "descriptions": [     "019655^Bentelan^2.16.840.1.113883.2.9.6.1.5"   ],   "administrativeRequest": [     "SSN",     "INPATIENT"   ],   "mode": "ATTACHMENT",   "healthDataFormat": "CDA"}

Content-Disposition: form-data; name="file"; filename="output.pdf"
Content-Type: application/pdf
Content-Transfer-Encoding: binary
```

stiamo ottenendo il seguente errore:

`{"traceID":"8313996e90c8bd89","spanID":"8313996e90c8bd89","type":"/msg/ini-error","title":"Ini error.","detail":"{\"traceID\":\"00000000000000008313996e90c8bd89\",\"spanID\":\"f3fec037f677ef00\",\"type\":\"/errors/fields\",\"title\":\"Missing\",\"detail\":\"Non Ã¨ stato possibile recuperare i riferimenti con i dati forniti in input\",\"instance\":\"/ini\"}","status":404,"instance":"/msg/service-error/ini"}`

Allego:

- [PDF con CDA iniettato](https://github.com/user-attachments/files/16429275/output.pdf)
- [Authorization token](https://github.com/user-attachments/files/16429302/authorization_token.txt)
- [FSE-JWT-Signature token](https://github.com/user-attachments/files/16429301/fse_jwt_ignature_token.txt)

Come possiamo risolvere?

Grazie.

**Comment by LucaRogledi** [comment]
Buongiorno,
L'errore ricevuto sembrerebbe dovuto al riferimento utilizzato nella chiamata. 

La invitiamo gentilmente a riprovare eseguendo un "giro pulito", dove per "giro pulito" intendiamo l'esecuzione della _Validazione_ di un nuovo documento mai pubblicato in precedenza; successivamente la _Pubblicazione_ dello stesso utilizzando un `identificativoDoc` originale, in modo da evitare messaggi di errore come ` "message": "Documento già esistente"`  in fase di pubblicazione nello step `"eventType": "EDS_WORKFLOW"` ed infine la _Sostituzione_ del documento pubblicato.

Le chiediamo cortesemente di riprovare così, rimaniamo in attesa di un vostro gentile riscontro e a disposizione per ulteriori richieste di chiarimento/supporto.
Grazie

**Comment by federicolau** [comment]
> Buongiorno, L'errore ricevuto sembrerebbe dovuto al riferimento utilizzato nella chiamata.
> 
> La invitiamo gentilmente a riprovare eseguendo un "giro pulito", dove per "giro pulito" intendiamo l'esecuzione della _Validazione_ di un nuovo documento mai pubblicato in precedenza; successivamente la _Pubblicazione_ dello stesso utilizzando un `identificativoDoc` originale, in modo da evitare messaggi di errore come ` "message": "Documento già esistente"` in fase di pubblicazione nello step `"eventType": "EDS_WORKFLOW"` ed infine la _Sostituzione_ del documento pubblicato.
> 
> Le chiediamo cortesemente di riprovare così, rimaniamo in attesa di un vostro gentile riscontro e a disposizione per ulteriori richieste di chiarimento/supporto. Grazie

Per `identificativoDoc` "originale", cosa intendete?

**Comment by LucaRogledi** [comment]
Per `identificativoDoc` originale intendiamo un nuovo identificativoDoc che quindi non è mai stato utilizzato in fase di pubblicazione o sostituzione. Grazie

**Comment by federicolau** [comment]
L'errore ricevuto adesso è:

`{"traceID":"de0cb31af42e0896","spanID":"de0cb31af42e0896","type":"/msg/record-not-found","title":"Record non trovato.","detail":"No Record Found","instance":"/record-not-found"}`

**Comment by LucaRogledi** [comment]
Buonasera,
potrebbe gentilmente fornirci la risposta completa ricevuta dalla chiamata del servizio di pubblicazione effettuata prima della chiamata di sostituzione?
Ringraziamo per la collaborazione.

**Comment by federicolau** [comment]
Non avevo effettuato la pubblicazione. Adesso l'ho richiamata ma per il servizio di sostituzione adesso ricevo:

`{"traceID":"81446641713db293","spanID":"81446641713db293","type":"/msg/cda-match","title":"Errore in fase di recupero dell'esito della verifica.","detail":"Il CDA non risulta validato","status":400,"instance":"/cda-validation"}`

Ma potrebbe tornarmi in quanto voi in primis riferite quanto segue:

![image](https://github.com/user-attachments/assets/8abefcb3-76f6-44f3-b941-15a71602dfe9)

Quindi gli step quali sarebbero precisamente? Dopo la pubblicazione del nuovo documento posso effettuare la sostituzione (se così fosse avrei l'errore menzionato nelle righe soprastanti) oppure dopo la pubblicazione del nuovo documento necesito di validarlo nuovamente per poi, solo successivamente, richiedere la sostituzione?

Grazie

**Comment by LucaRogledi** [comment]
Buonasera, 
Le confermiamo che come indicato nel messaggio da lei riportato, prima di una _Pubblicazione_ o _Sostituzione_ è necessario effettuare la _Validazione_, inoltre specifichiamo che la _Validazione_ viene bruciata dopo la chiamata dei servizi di _Pubblicazione_ o _Sostituzione_.
Pertanto, se si procede con il servizio di _Sostituzione_ utilizzando lo stesso documento utilizzato in fase di _Pubblicazione_ senza prima effettuare una validazione, oppure, utilizzando un nuovo documento non validato, si riceverà il messaggio di errore da lei riportato `"Il CDA non risulta validato"`.

Il processo corretto per effettuare una Sostituzione prevede: 

1. Validazione (documento)
2. Pubblicazione (documento)
3. Validazione (nuovo documento o documento modificato)
4. Sostituzione (nuovo documento o documento modificato).

Restiamo a disposizione per ulteriore supporto o chiarimenti. Grazie

**Comment by federicolau** [comment]
Ciao a seguire le seguenti risposte alle diverse chiamate:

> 1. Validazione (documento) 

`{"traceID":"b818a1981c4ef86a","spanID":"b818a1981c4ef86a","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.de644fcf10^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","warning":"[[SIGN_WARN - Attenzione il documento risulta firmato in validazione][WARNING_EXTRACT]Attenzione, non Ã¨ stata selezionata la modalitÃ  di estrazione del CDA]"}`

> 2. Pubblicazione (documento)

`{"traceID":"97e3627eaad64ec8","spanID":"97e3627eaad64ec8","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.de644fcf10^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`


> 3. Validazione (nuovo documento o documento modificato)

`{"traceID":"38f73fd151514c31","spanID":"38f73fd151514c31","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.a3eb87e140^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","warning":"[[SIGN_WARN - Attenzione il documento risulta firmato in validazione][WARNING_EXTRACT]Attenzione, non Ã¨ stata selezionata la modalitÃ  di estrazione del CDA]"}`


> 4. Sostituzione (nuovo documento o documento modificato).

`{"traceID":"2ae67f236142e2d4","spanID":"2ae67f236142e2d4","type":"/msg/ini-error","title":"Ini error.","detail":"{\"traceID\":\"00000000000000002ae67f236142e2d4\",\"spanID\":\"08111955c6999e9d\",\"type\":\"/errors/fields\",\"title\":\"Missing\",\"detail\":\"Non Ã¨ stato possibile recuperare i riferimenti con i dati forniti in input\",\"instance\":\"/ini\"}","status":404,"instance":"/msg/service-error/ini"}`


Come potete vedere la chiamata di sostituzione mi restituisce ancora l'errore per cui ho aperto l'issue.

**Comment by LucaRogledi** [comment]
Buonasera, 
Analizzando la chiamata di Pubblicazione tramite workflowInsanceId (`2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.de644fcf10^^^^urn:ihe:iti:xdw:2013:workflowInstanceId`), risulta che è stato utilizzato l'identificativoDoc "2.16.840.1.113883.2.9.2.120.4.4^290700" e un documento che sembrebbero essere gia stati pubblicati in precedenza generando il seguente messaggio nello step "SEND_TO_INI":

`"message":"SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:WarningERROR_CODE:R224CODE CONTEXT:DocumentEntry already saved in a previous communication"`

Come indicato nel nostro messaggio precedente: 

>per "giro pulito" intendiamo l'esecuzione della Validazione di un nuovo documento mai pubblicato in precedenza; successivamente la Pubblicazione dello stesso utilizzando un identificativoDoc originale

le chiederemmo gentilmente di effettuare un nuovo giro di chiamate utilizzando un nuovo documento e un identificativoDoc inutilizzato, assicurandosi se possibile, tramite il serviizio di stautus per workflowInstanceId di non aver ricevuto messaggi di errore in pubblicazione.
Grazie

**Comment by federicolau** [comment]
Riepilogo le chiamate aggiungendo la risposta del servizio "status" dopo la pubblicazione introducendo un nuovo idDocumento:

> 1. Validazione (documento)
>`{"traceID":"f04416903d26efc0","spanID":"f04416903d26efc0","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.586b75661b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","warning":"[[SIGN_WARN - Attenzione il documento risulta firmato in validazione][WARNING_EXTRACT]Attenzione, non Ã¨ stata selezionata la modalitÃ  di estrazione del CDA]"}`

> 2. Pubblicazione (documento)
>`{"traceID":"9ca290eac50b0ee5","spanID":"9ca290eac50b0ee5","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.586b75661b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

> 3. Status 
>`{"traceID":"d6f9ca7918e3af51","spanID":"2e1500de5210bc23","transactionData":[{"eventType":"VALIDATION","eventDate":"2024-08-02T12:33:05.502+00:00","eventStatus":"SUCCESS","subject":"GTWGWY82B42G920M","organizzazione":"160","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.586b75661b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","traceId":"f04416903d26efc0","issuer":"integrity:S1#160#REGIONEPUGLIATEST","expiringDate":"2025-08-02T12:33:05.511+00:00"},{"eventType":"PUBLICATION","eventDate":"2024-08-02T12:33:08.730+00:00","eventStatus":"SUCCESS","identificativoDocumento":"2.16.840.1.113883.2.9.2.120.4.4^320812","subject":"GTWGWY82B42G920M","tipoAttivita":"CON","organizzazione":"160","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.586b75661b^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","traceId":"9ca290eac50b0ee5","issuer":"integrity:S1#160#REGIONEPUGLIATEST","expiringDate":"2025-08-02T12:33:08.750+00:00"}]}`

> 4. Validazione (nuovo documento o documento modificato)
>`{"traceID":"56816dfda629ab62","spanID":"56816dfda629ab62","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.d7db5e1de1^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","warning":"[[SIGN_WARN - Attenzione il documento risulta firmato in validazione][WARNING_EXTRACT]Attenzione, non Ã¨ stata selezionata la modalitÃ  di estrazione del CDA]"}`

> 5. Sostituzione (nuovo documento o documento modificato)
> `{"traceID":"39b27992c4ec2e84","spanID":"39b27992c4ec2e84","type":"/msg/ini-error","title":"Ini error.","detail":"{\"traceID\":\"000000000000000039b27992c4ec2e84\",\"spanID\":\"a0814e4ee84632db\",\"type\":\"/errors/fields\",\"title\":\"Missing\",\"detail\":\"Non Ã¨ stato possibile recuperare i riferimenti con i dati forniti in input\",\"instance\":\"/ini\"}","status":404,"instance":"/msg/service-error/ini"}`


Come potete notare riscontro sempre lo stesso errore alla chiamata di sostituzione.

**Comment by g-maugeri-sogei** [comment]
Buonasera, in riferimento all'ultimo tentativo vedo che i metadati arrivano col codice P99. State di proposito provando questo test case? Mi confermate che senza oscuramento la sostituzione funziona correttamente?

**Comment by federicolau** [comment]
Buon pomeriggio,

in realtà non è voluto l'invio dei metadati con codice P99.
Ma l'oscuramento lato CDA dovrei verificarlo?

**Comment by federicolau** [comment]
> Buonasera, in riferimento all'ultimo tentativo vedo che i metadati arrivano col codice P99. State di proposito provando questo test case? Mi confermate che senza oscuramento la sostituzione funziona correttamente?

Per la richiesta di pubblicazione del primo documento effettivamente stavamo passando nel request body:

**"attiCliniciRegoleAccesso": [     "P99"   ]**


Ma adesso, pur effettuando la seguente pubblicazione:

`{    "healthDataFormat": "CDA",   "mode": "ATTACHMENT",   "tipologiaStruttura": "Ospedale",   "attiCliniciRegoleAccesso": [     "PUBLICPOL"   ],   "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^320812",   "identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.1",   "tipoDocumentoLivAlto": "REF",   "assettoOrganizzativo": "AD_PSC001",   "dataInizioPrestazione": "20141020110012",   "dataFinePrestazione": "20141020110012",   "tipoAttivitaClinica": "CON",   "identificativoSottomissione": "2.16.840.1.113883.2.9.2.120.4.3.489592",   "priorita": false,   "descriptions": [     "019655^Bentelan^2.16.840.1.113883.2.9.6.1.5"   ],   "administrativeRequest":[ "SSN"] }`


Abbiamo sempre lo stesso errore nella chiamata di sostituzione (in questa chiamata in "attiCliniciRegoleAccesso" abbiamo sempre passato "PUBLICPOL" e non "P99").

**Comment by g-maugeri-sogei** [comment]
Buonasera,
potete provare a svolgere un nuovo test di validazione - pubblicazione - validazione - sostituzione usando documenti non inviati in precedenza? 
Sulla base dati trovo diversi errori R224. Se anche cosi' ricevete errore, per indagare il problema mi servono per ogni chiamata la coppia request/respose dei messaggi inviati al GTW  e relativo rimestamp.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto. Grazie
