### ISSUE TITLE
Pull it-fse-accreditamento 1562 / 1588

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#951]
"il file data.json fornito in data odierna risulta essere malformato"
Modificato il data.json con particolare attenzione ai campi data.

https://github.com/ministero-salute/it-fse-accreditamento/pull/1588

**Comment by LucaRogledi** [comment]
Buon pomeriggio, ringraziamo per la notifica e procediamo alla chiusura della issue.
