### ISSUE TITLE
SEND_TO_INI con esito BLOCKING_ERROR

### ISSUE THREAD

**Issue by marco-volpe** [ministero-salute/it-fse-support#952]
Buongiorno

abbiamo fatto una prova di pubblicazione di un documento con assistito piemontese, codice fiscale **TRNLCU77B44L736O**

La pubblicazione è andata a buon fine, successivamente, utilizzando l'API per la verifica dello stato di pubblicazione, abbiamo visto questo evento

```
{
         "eventType":"SEND_TO_INI",
         "eventDate":"2024-07-31T09:42:22.404+00:00",
         "eventStatus":"BLOCKING_ERROR",
         "message":"SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 1295",
         "workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.50214974b1^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
         "expiringDate":"2025-07-31T09:42:22.549+00:00"
      }
```

Potete indicarci il motivo dell'errore?

Grazie

**Comment by g-maugeri-sogei** [comment]
Buonasera,
chiedo un chiarimento riguardo a come avete implementato l'integrazione col GTW.
Nel caso vi arrivi una chiamata da INI proveniente dal GTW quindi con l'attributo
 <saml2:Attribute Name="SubjectAuthenticator" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" xmlns:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                  <saml2:AttributeValue xsi:type="xs:string">GTW_950</saml2:AttributeValue>
               </saml2:Attribute>,
vi aspettate il semplice forward del messaggio o gestite tutto come le chiamate tradizionali e quindi vi aspettate la traduzione del messaggio da HL7 al formato definito per la sussidiarieta' ?

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto. Grazie
