### ISSUE TITLE
Mancato accreditamento

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#953]
**DATASOFTWARE SRL - INTELLILAB - 3**

"il file data.json fornito in data odierna risulta essere malformato"

Potrei avere delucidazioni in merito?

**Comment by ds-tommaso** [comment]
segue il json

```
{
    "appID": "INTELLILAB",
    "appVendor": "DATASOFTWARE SRL",
    "appVersion": "3",
    "results": [{
            "files": ["CDA2_LAB_CT0.pdf"],
            "id": 368,
            "traceId": "4b57573122b76f7a",
            "ts": "2024-02-28T09:29:52Z",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.190.4.4.9696a2b8e1e5cc003b23fe2f6e2144daa3cff2f48e7d28b3f5f657281a3098de.e44804b7cb^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
        }, {
            "files": ["CDA2_LAB_CT1.pdf"],
            "id": 1,
            "traceId": "c4606fe8777b5f6b",
            "ts": "2024-02-28T09:22:53Z",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.190.4.4.66a35ccbe4ac9a4420b1ac3011fd13b5b8acf2d87a4d4f74c772acf0c5581493.0c5b63673a^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
        }, {
            "files": ["CDA2_LAB_CT2.pdf"],
            "id": 2,
            "traceId": "9bf69a2a21f6fa04",
            "ts": "2024-02-28T09:22:55Z",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.190.4.4.a4fd527ca7c37e164b7d10be1c0e5e2fcb984f85c2b9c691e6ba933264b9fa2f.25b6e27874^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
        }, {
            "files": ["CDA2_LAB_CT15.pdf"],
            "id": 61,
            "traceId": "0da5b40bcf535993",
            "ts": "2024-02-28T09:22:53Z",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.190.4.4.52e740739e4ddc16c4226dbd7e244e9c82bf78461e7060fc27df7a0a56c40d81.4a249b74ba^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
        }
    ]
}
```

**Comment by LucaRogledi** [comment]
Buongiorno, 
Dalle analisi effettuate sul file [data.json](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/GATEWAY/A1%23111DATASOFTWARE/DATASOFTWARE_SRL/INTELLILAB/3/data.json) presente nella directory di accreditamento, è emerso che l'errore sembrerebbe essere generato dal carattere `,` aggiunto dopo:
`"workflowInstanceId": "2.16.840.1.113883.2.9.2.190.4.4.d7eefc7b8a503d0a01e7fee30565a19e23bb25a16cb91c59b98a1691ee0cebae.64e7acb3b7^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"`  del test con `"id": 446`.

![image](https://github.com/user-attachments/assets/79fe0119-ffa0-42ab-9cbe-f0c0ad6d3341)

La invitiamo gentilmente a sottomettere una nuova PR con la correzione riportata. Grazie

**Comment by ds-tommaso** [comment]
Corretto, grazie. Avevo lasciato una copia errata del file.
Potete trovare su _it-fse-accreditamento_ la pull 1590.

Scusate per l'inconveniente

https://github.com/ministero-salute/it-fse-accreditamento/pull/1590

**Comment by LucaRogledi** [comment]
Ringraziamo per la notifica e procediamo con la chiusura della issue restando a disposizione per ulteriore supporto.
