### ISSUE TITLE
Checklist referti RAD

### ISSUE THREAD

**Issue by GruppoSiges** [ministero-salute/it-fse-support#954]
Buongiorno, nelle istruzioni di compilazione della checklist di accreditamento compare questo punto:
"3) Nel caso in cui tra le tipologie documentali oggetto di accreditamento per l'applicativo figurino PSS, RAP e RAD, i relativi casi di test con id 444, 417, 446, che recepiscono quanto previsto dal Decreto 07 settembre 2023, devono essere obbligatoriamente eseguiti e compilati (la colonna APPLICABILITA' deve essere valorizzata con SI)".

Nel nostro caso, non abbiamo a disposizione le informazioni per compilare le sezioni previste dal test con id 446 (VALIDAZIONE_CDA2_RAD_CT1); come dobbiamo comportarci? Dobbiamo comunque crearle e lasciarle vuote (se si può usare il nullFlavor)?

Grazie, buona giornata.

**Comment by GruppoSiges** [comment]
Inoltre, sempre a proposito della checklist, è possibile utilizzare la colonna NOTE per specificare i motivi della non applicabilità o va lasciata vuota?

Grazie.

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
I casi di test indicati (444, 417, 446) relativi alla [checklist](
https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/accreditamento-checklist_V8.2.1.xlsx
), devono essere obbligatoriamente eseguiti e compilati riportando tutte le informazioni necessarie (con APPLICABILITA' valorizzata SI) per potere effettuare un accreditamento con successo. 

Infine, la invitiamo ad utilizzare le colonne "RAZIONALE DI APPLICABILITà" e "RAZIONALE DI APPLICABILITà - ALTRO", per specificare il motivo della non applicabilità. La colonna NOTE, invece, può essere sfruttata qualora ritenesse necessario aggiungere ulteriori dettagli sul caso di test.

Restiamo a disposizione per eventuali chiarimenti o richieste di supporto. Grazie

**Comment by LucaRogledi** [comment]
Buonasera,
Potrebbe gentilmente indicarci le sezioni a cui fa riferimento? Grazie

**Comment by GruppoSiges** [comment]
Mi riferisco nello specifico a Dicom object catalog e suggerimenti per il medico prescrittore

**Comment by LucaRogledi** [comment]
Buonasera,

Osservando l'excel dei requisiti per la tipologia RAD (https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/1-Referto%20di%20Radiologia/CDA2_Referto_di_Radiologia_OK.xlsx), le sezioni da lei indicate risultano obbligatorie da caso di test 1.

Pertanto come evidenziato negli screenshot di seguito bisogna fare riferimento alla colonna "Obbligatorietà per Test case 1" per valutare l'obbligatorietà dei dati richiesti per superare il caso di test.

![image](https://github.com/user-attachments/assets/456bc72b-5320-4a96-8026-38d849583a4f)

![image](https://github.com/user-attachments/assets/4ffa4059-4828-4235-9a4e-076bce0ba3eb)

Restiamo a disposizione per ulteriore supporto. Grazie

**Comment by GruppoSiges** [comment]
Buonasera, 
il problema è proprio che le sezioni vengono definite obbligatorie per quel test, ma si tratta di sezioni altrimenti opzionali, relative ad informazioni che NON gestiamo, non in modo strutturato quantomeno. Dato che il punto 3 delle istruzioni di compilazione sopracitate specificano che il test DEVE essere effettuato, quello che vi chiedo è COME posso farlo se non ho a disposizione (ed ho facoltà di non avere a disposizione) le informazioni per completarlo.

Grazie, saluti.

**Comment by vigliottim** [comment]
Buongiorno,
si segnala che da specifiche HL7 tali sezioni risultano opzionali.
Tuttavia, in riferimento al Decreto del 07 Settembre 2023, devono essere gestite. 
Pertanto, è opportuno rendere disponibile la riproducibilità del _Caso di Test 1_, tenendo in considerazione le cardinalità degli elementi riportati nel file excel [CDA2_Referto_di_Radiologia_OK](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/Validazione/1-Referto%20di%20Radiologia/CDA2_Referto_di_Radiologia_OK.xlsx) per poter superare l'accreditamento.

**Comment by alfadocs-nfr** [comment]
Abbiamo riscontrato la stessa situazione.

**Comment by GruppoSiges** [comment]
Va bene vedremo di arrangiarci in qualche modo.

Grazie, saluti.

**Comment by vigliottim** [comment]
Buongiorno, procediamo alla chiusura della presente issue e restiamo a disposizione per altre richieste di supporto.
