### ISSUE TITLE
Tripletta

### ISSUE THREAD

**Issue by ZucchettiCentroSistemi** [ministero-salute/it-fse-support#955]
Buonasera,
ormai da Giugno 2023 il nostro sw è accreditato ma purtroppo abbiamo fatto la richiesta di accreditamento con il nome dell'azienda errato.
Zucchetti Centro Sistema s.p.a | JLAB | v.9.0 quando invece dovrebbe essere
Zucchetti Centro Sistemi s.p.a | JLAB | v.9.0

E' possibile modificare il nome del fornitore? Cosa comporta?

Grazie

**Comment by ZucchettiCentroSistemi** [comment]
Potete farci sapere?

**Comment by Ser-ena** [comment]
Salve,
la chiediamo gentilmente di inoltrare la richiesta di informazioni a FSE-PNRR@innovazione.gov.it

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Rimaniamo a disposizione per altre richieste di supporto.
Grazie.
