### ISSUE TITLE
Test - VALIDAZIONE_CDA2_RSA_CT5_KO

### ISSUE THREAD

**Issue by acostablueday** [ministero-salute/it-fse-support#956]
Buongiorno,
stiamo proseguendo la fase di test, stiamo provando il test `VALIDAZIONE_CDA2_RSA_CT5_KO`, il quale richiede di non validare il campo `confidentialityCode`.
Abbiamo caricato questo xml:
[CDA_OK.txt](https://github.com/user-attachments/files/16467438/CDA_OK.txt)

Restituisce questo errore:
`{"traceID":"8dc010f6363fa32b","spanID":"8dc010f6363fa32b","type":"/msg/syntax","title":"Errore di sintassi.","detail":"ERROR: -1,-1 cvc-complex-type.2.4.a: Invalid content was found starting with element 'languageCode'. One of '{\"urn:hl7-org:v3\":confidentialityCode}' is expected.","status":400,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.e681f9ecb1ccad05edb23f4c98320d091eeee432aed80b37f5b54e49a3393d42.ddbcf1b16e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

Invocando l'API di check sul traceId abbiamo questa risposta:
`
{"traceID":"a9c46fa4f2a38fce","spanID":"d5d6993f1f93b3bb","transactionData":[{"eventType":"VALIDATION","eventDate":"2024-08-02T07:50:23.198+00:00","eventStatus":"BLOCKING_ERROR","message":"ERROR: -1,-1 cvc-complex-type.2.4.a: Invalid content was found starting with element 'languageCode'. One of '{\"urn:hl7-org:v3\":confidentialityCode}' is expected.","subject":"PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO","organizzazione":"050","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.e681f9ecb1ccad05edb23f4c98320d091eeee432aed80b37f5b54e49a3393d42.ddbcf1b16e^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","traceId":"8dc010f6363fa32b","issuer":"integrity:S1#111#TECHNOLOGYHEALTHSYSTEMSGROUPSRLXX","expiringDate":"2025-08-02T07:50:23.206+00:00"}]}
`

tale output è corretto per considerare il test `VALIDAZIONE_CDA2_RSA_CT5_KO` superato?

**Comment by LucaRogledi** [comment]
Buon pomeriggio, 
Confermiamo la corretta ricezione dell'output `"Errore di sintassi."` con codice in risposta `"400"` omettendo la valorizzazione del campo `confidentialityCode` come indicato dal Caso di Test 5. Procediamo alla chiusura della presente issue. Grazie
