### ISSUE TITLE
Errore in pubblicazione - Crash Program -  Regione Sardegna

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#957]
Buongiorno,
Stiamo effettuando delle verifiche preliminari di test del crash program. Nello specifico stiamo eseguendo una pubblicazione di un documento PDF con CDA2 iniettato.

Come primo step è stata eseguita la validazione del documento che ha dato esito positivo. Nello specifico, abbiamo ottenuto il seguente esito :  
`{"traceID":"15923eb2edf95dba","spanID":"15923eb2edf95dba","workflowInstanceId":"2.16.840.1.113883.2.9.2.200.4.4.dd196a6a26e2cc5a7f21c77473231471d6dadfc5adb4c3aef85790b4341a3f9f.d03f8b8177^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

Successivamente, è stato effettuata una pubblicazione e abbiamo ottenuto il seguente esito:
` {"traceID":"66b08d955eec70c65f387d65f367ba7b","spanID":"808fb2bc41d54078","type":"/msg/cda-element","title":"Errore in fase di estrazione del CDA.","detail":"Error while extracting CDA from PDF document","status":400,"instance":"/cda-extraction"}`

Vorremmo comprendere se l'errore riscontrato sia imputabile a noi oppure a modifiche nel servizio.

**Comment by vigliottim** [comment]
Buongiorno, le chiediamo gentilmente di allegare il pdf utilizzato per effettuare la chiamata al servizio di pubblicazione al fine di svolgere indagini più approfondite.
Grazie.

**Comment by FSESardegna** [comment]
Allego il documento,
Grazie.
[pdf_test_20240805102048_signed.pdf](https://github.com/user-attachments/files/16493451/pdf_test_20240805102048_signed.pdf)

**Comment by vigliottim** [comment]
Buongiorno,
dalle analisi svolte sui log della chiamata da lei effettuata, abbiamo riscontrato i seguenti errori:

1. _Sezione caricamento del file pdf_
Il nome del file da lei utilizzato va inserito completo di estensione nel campo filename e il Content-Type va corretto come indicato di seguito:
**Content-Disposition: form-data; name="file";<s>filename="document"</s> filename="NOMEFILE.pdf"
<s>Content-Type: application/octet-stream</s> Content-Type: application/pdf**

2. _Request Body_
E' stata indicata la modalità RESOURCE anziché ATTACHMENT. Pertanto il campo _mode_ è da correggere come segue: **{"tipologiaStruttura":"Territorio", ..., <s>"mode":"RESOURCE"</s> "mode":"ATTACHMENT" ...}**

La invitiamo a riprovare dopo aver effettuato le correzioni suggerite.
Rimaniamo a disposizione nel caso abbia bisogno di ulteriore supporto.

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue, che potrà riaprire se occorre, e restiamo a disposizione per altre richieste di supporto.
