### ISSUE TITLE
Errori di validazione testcases per accreditamento

### ISSUE THREAD

**Issue by StefanoV1989** [ministero-salute/it-fse-support#958]
Buongiorno,

stiamo ottenendo il seguente errore durante il tentativo di validazione del documento per il testcase 2 del referto RSA.

`{"traceID":"078868eeb4c1387e","spanID":"078868eeb4c1387e","type":"/msg/syntax","title":"Errore di sintassi.","detail":"ERROR: -1,-1 cvc-complex-type.2.4.a: Invalid content was found starting with element 'observation'. One of '{\"urn:hl7-org:v3\":activityTime, \"urn:hl7-org:v3\":availabilityTime, \"urn:hl7-org:v3\":priorityCode, \"urn:hl7-org:v3\":confidentialityCode, \"urn:hl7-org:v3\":uncertaintyCode, \"urn:hl7-org:v3\":reasonCode, \"urn:hl7-org:v3\":languageCode, \"urn:hl7-org:v3\":subject, \"urn:hl7-org:v3\":specimen, \"urn:hl7-org:v3\":performer, \"urn:hl7-org:v3\":author, \"urn:hl7-org:v3\":informant, \"urn:hl7-org:v3\":participant, \"urn:hl7-org:v3\":entryRelationship, \"urn:hl7-org:v3\":reference, \"urn:hl7-org:v3\":precondition}' is expected.","status":400,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.180.4.4.a9a4e607bdcdd70eba2400d1321ce0e15a19440a670956a94178dc4ee9c17697.71d8e0c745^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

Il problema è che ci sono 12 tag <observation> che sembrano valorizzati correttamente.
Il servizio non restituisce il percorso incriminato o la linea dell'xml da analizzare, quindi in questo modo sarà una caccia alle streghe ed un relativo ticket di supporto aperto.
Potreste darci una dritta su questo errore?

Inoltre chiedo una informazioni riguardo il tag <text>.
Nella documentazione viene indicato la possibilità di inserire tag come <paragraph> <item> <list> ecc.
Se però inserito qualcosa del genere, ottengo errore:
`<text><paragraph>Il paziente è affetto da scompenso cardiaco.</paragraph></text>`
L'errore dice che non si aspetta un tag paragraph nonostante sia esattamente come documentato.

Per bypassare il problema abbiamo inserisco il dato in questo modo nell'xml:
`<text>&lt;paragraph&gt;Il paziente è affetto da scompenso cardiaco.&lt;/paragraph&gt;</text>`

Volevamo sapere se è corretto o c'è qualcosa da modificare, perché ad esempio il testo delle prestazioni diventa come segue:
`<text>&lt;paragraph&gt;
	&lt;caption&gt;Prestazioni Eseguite&lt;/caption&gt;
&lt;/paragraph&gt;&lt;list&gt;
	&lt;item ID="Prestazione-1"&gt;
		&lt;table&gt;
			&lt;thead&gt;
				&lt;tr&gt;
					&lt;th&gt;Prestazione 1&lt;/th&gt;
				&lt;/tr&gt;
			&lt;/thead&gt;
			&lt;tbody&gt;
				&lt;tr&gt;
					&lt;th&gt;Codice Prestazione&lt;/th&gt;
					&lt;td&gt;89.43&lt;/td&gt;
				&lt;/tr&gt;&lt;tr&gt;
					&lt;th&gt;Descrizione Prestazione eseguita&lt;/th&gt;
					&lt;td&gt;Test cardiovascolare da sforzo con cicloergometro&lt;/td&gt;
				&lt;/tr&gt;&lt;tr&gt;
					&lt;th&gt;Data Prestazione eseguita&lt;/th&gt;
					&lt;td&gt;2024-08-05 09:04:46+02:00&lt;/td&gt;
				&lt;/tr&gt;
			&lt;/tbody&gt;
		&lt;/table&gt;
	&lt;/item&gt;
&lt;/list&gt;</text>`

E non vorrei che i tag della tabella in questo modo non vengano interpretati. Però se li mettiamo normali, il servizio ce li rimbalza indietro.

Grazie.

**Comment by StefanoV1989** [comment]
[case2.xml.txt](https://github.com/user-attachments/files/16494158/case2.xml.txt)

Ho estratto il file xml dal pdf. Rinominato txt perché XML non lo fa caricare.
Grazie

**Comment by vigliottim** [comment]
Buon pomeriggio,
dopo una prima analisi del CDA2 fornito si riportano le seguenti segnalazioni: 

- L'errore di natura sintattica che si ottiene è dovuto al mancato inserimento di un _ClinicalStatement_ all'interno della _entryRelationship_. Più precisamente, in riferimento al CDA fornito in allegato, le _observation_ delle righe 263 - 268, presenti all'interno di un _entryRelationship/act_ devono essere riportate all'interno di _entryRelationship_ distinte per ciascuna _observation_. 

- L'elemento _methodCode_, presente in _section[Prestazioni]/entry/act/entryRelationship/act,_ genera errore sintattico in quanto non previsto da schema per l'elemento _act_. 

Inoltre, a livello di _component/section_ l'elemento _text_ può contenere il tag _paragraph_, mentre, all'interno di un _ClinicalStatement_ (es. elemento _act/text_, in riga 261) da Schema non è previsto il tag _paragraph_.

Rimaniamo a disposizione per chiarimenti.

**Comment by StefanoV1989** [comment]
Salve,
mi sono appena reso conto che per la sola tipologia "osservazioni" nel componente "prestazioni", le relazioni di osservazione, modalità e note andavano messe nell'observation. Per questo il methodCode che mi avete segnalato era in posizione errata.
Riguardo paragraph abbiamo capito come fare. Grazie!

Nel testcase 3 invece abbiamo il seguente errore:
`{"traceID":"1b3de61fc6fea05b","spanID":"1b3de61fc6fea05b","type":"/msg/syntax","title":"Errore di sintassi.","detail":"ERROR: -1,-1 cvc-complex-type.3.2.2: Attribute 'unit' is not allowed to appear in element 'value'.","status":400,"instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.180.4.4.b9a1f03fcd0dd56617130a8e4e49cf1e1c46a87c6d185d5d58194bbc9054a5d5.61ff279166^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

[case3.xml.txt](https://github.com/user-attachments/files/16508127/case3.xml.txt)

Ma da quel che vedo l'attributo sull'elemento value è presente solo in 2 punti, entrambi presi dalla documentazione.

**Comment by StefanoV1989** [comment]
Salve,
siamo ancora bloccati su questo errore purtroppo.

**Comment by vigliottim** [comment]
Buon pomeriggio,
precisiamo che l'errore presente in riga 246 è dovuto all'assegnazione errata del Datatype _REAL_ all'elemento _value_.
Infatti, il datatype da Schema non ammmette l'utilizzo dell'attributo _unit_.  
Qualora si volesse rappresentare un _value_ che riporti una quantità si consiglia di utilizzare il Datatype _PQ_ (_Physical Quantit_y) che ammette l'utilizzo di _unit_. 
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by StefanoV1989** [comment]
Salve,
abbiamo terminato i test e fatto pull request nell'apposita zona.

Potete chiudere il ticket

**Comment by vigliottim** [comment]
Buongiorno,
grazie per il gentile feedback.
Procediamo alla chiusura del presente ticket e rimaniamo a disposizione per altre richieste di supporto.
