### ISSUE TITLE
GRACE period - SmartCard

### ISSUE THREAD

**Issue by francescobus83** [ministero-salute/it-fse-support#96]
Buongiorno, per trasferire durante il GRACE PERIOD un documento FSE 1.0, l'interfaccia è FSE 2.0 oppure 1.0? Se la seconda opzione è quella idonea, sono previsti ancora invii tramite smart card (attualmente in produzione)?

**Comment by Ser-ena** [comment]
Salve, durante il grace period, che presuppone il rilascio in produzione del GTW, I documenti saranno trasferiti attraverso l'interfaccia FSE 2.0 (rif. github.com/ministero-salute/it-fse-support/tree/main/doc/accreditamento#fase-3-deployment-in-produzione). Nella fase transitoria (in attesa del rilascio in produzione del GTW) di alimentazione del FSE  secondo le modalità di invio del FSE 1.0 ma con documenti adeguati alle specifiche documentali del FSE 2.0, gli applicativi software convalidati (fase 1) saranno installati in produzione mantenendo la modalità di conferimento dei documenti utilizzata per FSE 1.0, secondo le indicazioni della singola regione e in raccordo agli adeguamenti alla infrastruttura regionale (rif.https://github.com/ministero-salute/it-fse-support/tree/main/doc/transitorio)

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto. Grazie
