### ISSUE TITLE
AUTHOR_INSTITUTION_NOT_PRESENT

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#960]
Buongiorno,

Stiamo eseguendo una pubblicazione di un documento ottenendo in risposta quanto riportato di seguito
`{"traceID":"66b23a47891c8452bf40febe1ff2201c","spanID":"7eb8aa8b8abafd98","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.200.4.4.a8ac9e788884d7eadd357640ec624e07613d6471431c9807fc93a4f2dd600f5b.a7690ded13^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

`DocumentEntry.uniqueId "2.16.840.1.113883.2.9.2.200.4.4^200106CGNCTD93M22B354R20240805165346795167"`

A seguito della pubblicazione, otteniamo una request ITI-42 da parte del gateway con l'elemento authorInstitution valorizzato 
```
<ns2:Slot name="authorInstitution">
    <ns2:ValueList>
          <ns2:Value>AUTHOR_INSTITUTION_NOT_PRESENT</ns2:Value>
   </ns2:ValueList>
</ns2:Slot>
```
Nonostante da parte nostra sia stato inviato valorizzato nel seguente modo

<ns2:Slot name="authorInstitution">
    <ns2:ValueList>
          <ns2:Value>ASSL UNICA - REGIONE SARDEGNA^^^^^&amp;2.16.840.1.113883.2.9.4.1.3&amp;ISO^^^^200201</ns2:Value>
   </ns2:ValueList>
</ns2:Slot>

Possiamo avere delucidazioni in merito?
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, 
Potreste riprovare cortesemente aggiungendo l'elemento "representedOrganization" sotto "assignedAuthor" nel cda, avendo cura di popolare il tag "name" nel representedOrganization, come indicato [qua](https://github.com/ministero-salute/it-fse-support/issues/702#issuecomment-2027044681)?
Rimaniamo a disposizione nel caso in cui l'errore persista.

La sezione xml incollata, coerente con le [specifiche](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20interoperabilit%C3%A0/FrameworkEDatasetDeiServiziBase_v2-5_20231212_0.pdf) (es. sezione A1.2), fa parte di un messaggio che nell'fse 2.0 è in carico al Gateway verso INI. Dato che nel cda non è presente una corrispondenza con slot author institution, qual è l'origine della sezione xml riportata?

Grazie mille
