### ISSUE TITLE
Name Format Assertion

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#961]
Buongiorno,
a seguito del processo di pubblicazione, stiamo ricevendo da parte del Gateway delle request con gli attributi di asserzione SubjectApplicationId, SubjectApplicationVendor, SubjectApplicationVersion, SubjectAuthenticator con un `NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" `ma da specifiche tali attributi risultano essere di tipo stringa quindi ci aspetteremmo che il Name Format sia il seguente` NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"`.

Potremmo avere delucidazioni?
Grazie

**Comment by IStacchiotti** [comment]
Buongiorno, 
Rispetto alle [Specifiche tecniche per l’interoperabilità tra i sistemi regionali di FSE Framework e dataset dei servizi base Versione 2.5](https://www.fascicolosanitario.gov.it/sites/default/files/public/media/Specifiche%20interoperabilit%C3%A0/FrameworkEDatasetDeiServiziBase_v2-5_20231212_0.pdf), e in particolare al sequence in "Figura 42 – Scenario 1: Indicizzazione nuovo documento" (capitolo 6), potrebbe indicare a quale chiamata fa riferimento?
Grazie

**Comment by FSESardegna** [comment]
Buongiorno, 
analizzando il grafico, la ITI-42 la riceviamo dall'attore INI, in ogni caso noi riceviamo i parametri non corretti che non passano la validazione lato RDA.

<img width="487" alt="Pubblicazione doc" src="https://github.com/user-attachments/assets/614764cf-b728-49a7-9b5d-3f7ee79ab345">

Attendiamo un vostro riscontro,
Grazie.

**Comment by vigliottim** [comment]
Buon pomeriggio, grazie per la segnalazione.
E' stato rilasciato un aggiornamento. 
Le chiediamo gentilmente di riprovare.
Grazie.

**Comment by FSESardegna** [comment]
Buongiorno,
a seguito di una nuova prova, otteniamo sempre la stessa valorizzazione non corretta dei Name Format per gli attributi di asserzione SubjectApplicationId, SubjectApplicationVendor, SubjectApplicationVersion, SubjectAuthenticator.
Rimaniamo a disposizione,
Grazie.

**Comment by FSESardegna** [comment]
A seguito di una nuova prova, otteniamo i parametri dell'asserzione valorizzati correttamente.
Grazie.
