### ISSUE TITLE
Problema verifica asserzione INI

### ISSUE THREAD

**Issue by izamberlan** [ministero-salute/it-fse-support#963]
Buongiorno,
nel contesto del post crash program, ci siamo imbattuti in un problema nel passo della comunicazione da INI al nostro registry regionale, nella transazione ITI-42. La chiamata viene effettuata, ma la verifica della firma dell'asserzione, che il nostro nodo regionale esegue e che nelle normali invocazioni provenienti da INI funziona, in questo caso fallisce.
E' per caso cambiato qualcosa nelle modalità di firma di INI per queste richieste dal gateway?
L'errore riportato interrogando lo status è peraltro un CRF2 (noi restituiamo un PFC1).
Allego:
-asserzione ricevuta da INI
-nostro messaggio d'errore
-errore riportato dallo status
[err.json](https://github.com/user-attachments/files/16548140/err.json)
[assertion.zip](https://github.com/user-attachments/files/16548184/assertion.zip)
[response.zip](https://github.com/user-attachments/files/16548185/response.zip)

**Comment by g-maugeri-sogei** [comment]
Buonasera,
nel caso del gateway l'asserzione viene generata da un client differente che nel caso tradizionale.
Dovreste verificare sul vostro server la causa esatta che dell'errore sulla validazione dell'asserzione per capire se il problema dipende dal client o dal server.
Aggiungo che finora non abbiamo riscontrato problemi sulla validazione dell'asserzione nelle chiamate verso altre regioni.

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
