### ISSUE TITLE
Nuova Pull

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#965]
Buongiorno

Trovate la nuova pull https://github.com/ministero-salute/it-fse-accreditamento/pull/1597 relativo alla gestione degli errori in caso di timeout.

**Comment by LucaRogledi** [comment]
Buongiorno, la ringraziamo per la notifica. Procediamo alla chiusura della presente issue e rimaniamo a disposizione per ulteriori richieste di supporto.
