### ISSUE TITLE
Digest- assertion

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#966]
Stiamo eseguendo una pubblicazione di un documento ottenendo in risposta quanto riportato di seguito:
```
{
  "traceID": "66bc6516dab5bac4113d7881d4d79c78",
  "spanID": "81c2090c92dd357b",
  "warning": "",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.200.4.4.c014de422fee6de775a546529235200fd293a582ecf542b8ef0c139b7bf72f09.c653838a7d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```
A seguito della pubblicazione, otteniamo una request ITI-42 da parte di INI con un errore nella firma della request.

In particolar modo otteniamo un errore sulla valorizzazione dell'elemento digest. Il digest che troviamo all'interno della request è questo `EVOteQFDD1HOs4CeCv4HZwcyPKg=` mentre ricalcolando il digest otteniamo `c5kyh8uS+MqYZbDuIwPqfhO6bXg=`.

Alleghiamo la request di interesse [ITI-42_140824.txt](https://github.com/user-attachments/files/16609986/ITI-42_140824.txt)

**Comment by FSESardegna** [comment]
@izamberlan siete riusciti a risolvere in qualche modo?
@LucaRogledi avremo necessità di riscontro sulla issue in questione in quanto, non riuscendo a caricare un documento, siamo bloccati. Stiamo ricevendo un errore sulla validazione della signature non riscontrato nelle comunicazioni che normalmente riceviamo da INI.

**Comment by izamberlan** [comment]
buongiorno,

no, siamo in attesa di feedback

**Comment by FSESardegna** [comment]
Buongiorno sollecitiamo nuovamente un risposta in quanto l'errore sta bloccando l'esecuzione dei test, grazie

**Comment by marsardit** [comment]
Buongiorno, sollecito cortesemente una risposta.
Grazie

**Comment by vigliottim** [comment]
Buonasera,
le chiediamo gentilmente di riportare il calcolo che esegue per ottenere il digest: c5kyh8uS+MqYZbDuIwPqfhO6bXg=.
Grazie.

**Comment by FSESardegna** [comment]
Buongiorno,
non eseguiamo il calcolo manualmente ma sfruttiamo la classe SignatureValidator della libreria openSAML che si trova inclusa nella libreria spring-ws-security alla versione 3.1.8

Rimaniamo a disposizione,
grazie.

**Comment by vigliottim** [comment]
Buon pomeriggio, 
è stato rilasciato un aggiornamento.
Potrebbe gentilmente riprovare e darci un riscontro?
Grazie.

**Comment by izamberlan** [comment]
buongiorno, per noi ora l'asserzione viene correttamente verificata. Abbiamo un altro errore, ma al momento non necessitiamo di assistenza per risolverlo. Grazie.

**Comment by FSESardegna** [comment]
Buongiorno, 
l'asserzione viene correttamente verificata, la pubblicazione ha avuto esito positivo.
Grazie

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della issue come risolta. Grazie
