### ISSUE TITLE
Problema pubblicazione LDO su gateway regionale LAZIO

### ISSUE THREAD

**Issue by GrecoStefano** [ministero-salute/it-fse-support#967]
Buongiorno, da ieri stiamo ricevendo un errore per quanto riguarda la fase di pubblicazione di un documento di tipo LDO sul gateway regionale della regione Lazio. 

La fase di validazione del CDA viene passata senza problemi mentre nella pubblicazione riceviamo la seguente response:

2024-08-14T10:51:16.430877926Z     data: {
2024-08-14T10:51:16.430895536Z       traceID: 'f6ef7b20d17de1cb',
2024-08-14T10:51:16.430913253Z       spanID: 'f6ef7b20d17de1cb',
2024-08-14T10:51:16.430931540Z       type: '/msg/fhir-mapping-type',
2024-08-14T10:51:16.430949867Z       title: 'Mapping fhir fallito.',
2024-08-14T10:51:16.430968041Z       detail: 'multiple points',
2024-08-14T10:51:16.430986211Z       status: 400,
2024-08-14T10:51:16.431003815Z       instance: '/fhir-resource'
2024-08-14T10:51:16.431021566Z     }

Sarebbe possibile avere un supporto per capire come mai stiamo ricevendo questo errore?

Grazie in anticipo

**Comment by GrecoStefano** [comment]
Buona sera, 
questo è il cda iniettato dentro il pdf firmato che cerchiamo di pubblicare
[59647-20240463.txt](https://github.com/user-attachments/files/16662610/59647-20240463.txt)

qui a seguire la chiamata che ho appena effettuato per comodità tramite lo swagger che avete fornito in documentazione
curl -X 'POST' \
  'https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJ4NWMiOlsiTUlJRmFUQ0NBMUdnQXdJQkFnSVVDcnNZd3BUYmhUOTRsL3Z3dEw1YlRxcEQveXN3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TXpBMk1UWXhNalEzTUROYUZ3MHlOakEyTVRZeE1qUTNNREphTUdveEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVJrd0Z3WURWUVFEREJCVE1TTXhNVEZUU1ZNMFEwRlNSVmhZTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFvUGJSK05tZTBsN2xyazJyTzRRblltbmxLQitVb2t4NW91ZVFTRFExYm9mRFluWFNVL3VGSU4zNVFrb3hUNGZyUTh1WDhMUmsrRjdMdXhQQzU4SmlwVHE1aUpWYzVIa2RJbkR2OEJQZkNDR00wN3ZzT3A0VWdQVWZoMWNCRndtRmljMytweXpPR01qdmI4WEdqMzdXRStabW9ua1oyQ1ZNTlhrWDFJNnpmSVhxMTd3RFYzN1dKMHFWRmdrbS9Ucm82R3FiNitqdVdMdXo3QUZMUWVzVU5kWjJTQjZ2SHB0YW1QZmJFdzExNkpjUHAxRkJEaThlbUEybTRvdkRuK0NIMnpxZDYzamR1K0FFbjJiSFdaKys2VUorNUhLbForc2dTbGlqTkZqN1E5OG1RS2Joci9naG1LZUt4OUFaaXQ1bDZnekNMZmxhMEZNelExNHFLOXZ3SlFJREFRQUJvNElCR0RDQ0FSUXdId1lEVlIwakJCZ3dGb0FVRmptcEdnV0p0dzh0c2pYdHdnbWF4UU9ESWo4d0VnWURWUjBnQkFzd0NUQUhCZ1VyVEIwQkN6Q0JyUVlEVlIwZkJJR2xNSUdpTUlHZm9JR2NvSUdaaG9HV2FIUjBjSE02THk5allYTnZaMlZwYzNacGJDNXpiMmRsYVM1cGRDOWxhbUpqWVM5d2RXSnNhV04zWldJdmQyVmlaR2x6ZEM5alpYSjBaR2x6ZEQ5amJXUTlZM0pzSm1semMzVmxjajFEVGlVelJFTkJLMDFwYm1semRHVnlieXRrWld4c1lTdFRZV3gxZEdVclZHVnpkQ1V5UTA4bE0wUk5hVzVwYzNSbGNtOHJaR1ZzYkdFclUyRnNkWFJsSlRKRFF5VXpSRWxVTUIwR0ExVWREZ1FXQkJUMS8yVGgyL2kzSzJsY0xPYWZ2cWxMbVBTMnFEQU9CZ05WSFE4QkFmOEVCQU1DQmtBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFEZGg2ZEFScDBGMWZtMDl3M1JHQ3M1dGRXZnVBQ2Y0ZEtUay9yZkR1bmhhcDNzdyt6TE9LOC9Za09vVXluUkdFZFhtQWxpT2swQy9oQ1duTkpxYUR2TGJWN3U5Q2V6Tzc5N2cwL0F2Sml2MHl1SUcySTB3MjRPd01NWUgxa29ZdmRxYkkyWExOQ0U2Y2hvQlFFS1F2V3hzQTNNeGt1bjFvVm5QdGltSGdCaXRDMXJNK1J5cnZXemRySFNRMG1HSm5HdlRLMFYxcWNrY3oxSlRhUGZqU3VCNFV3Mm9zZk5zVGI1WU54SE4rOGx3b1dtc01INnQzQjhIVHdqRjdRSGtSTlZOWDFWTUptYWlFZVFqYndyRzlRNkh0ZFZST0gwaXk4a1BoUWZqNklZYUtwdTk4UHEzUTVrUGxydHREMmtQOUV0QkIvV3VpaUFsc1AvYlhwV1F4aUE0UVJKN2dhTTJyT3lyMnpINlBLRkwyRzZkbTVvd2xpdEZkdmhRUm45NjRhQ0tGYlBKZjRIQzU0OTExeXlZRzJtcDZyN1JzS1FZMWN6UnRvLzhjdmdoVThPWEFaRXh5Sjl4QitmcnArWStrYXl1azZQNFNGNEtHcUQwUkRIOXZBRG5LcHRBa3pVZXM4eERVanJxZWJHWW1vWXhKTE9Fa05mRDZpSUhIWGQreWdDMlFDOUxzMkFEUzBBNVNlNFJXeko4TlA4U3RDemJVYVY1OVZycXl1emJOdjJQTytlTWtiRE5KRXR2QmMybUlDa0x1VUJTemY5NDU1cStuN1pkYmhubUlNQmtwMENqVUhFcEtvckp0OGhvbDdTTlV1ejZXdCtXOEZvR0NIMVpOcGZCUDczODZWbTdzc2wzWjh0dUhmS2IxWXZZY05jODdnQmpmMzMxaFgzbSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJSU1NNQ0M4MEEwMUg1MDFUXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJpc3MiOiJhdXRoOlMxIzExMVNJUzRDQVJFWFgiLCJleHAiOjE3MjQxNjgzMzEsImlhdCI6MTcyNDA4MTkzMSwianRpIjoiYzMwNzk1ZWU5ZDdkNDlhNGIyYzU0NTllMTVlMjA2NjUifQ.AqobtiAFwO6Wy02THUR2zQBXvyRy7lpZ9KOwKhV3vOBXL0b9u7hbrtD_dVga6ZieJNab_GFeWSzGEoexO_lHLQVsQo5ghop6PK3iqzEoESpjVD2pM-etSDQwGBnLi8En9AheFAieiFp3q5YsKLx0aXuBvIAIaTmna43kmLFppGs207od9om0vHV904PS_rRkMa1kVPuwwxvrNcPP_LxwkMeTLsUfXzNlosG4KikgHoy3D9a0UkTVmjw09HoA_5-uixV0kx5m643ne5oBHBGBRJWvqr2No_riwoDOMl-aPwp3sFjRptiytT5bB9JC8-unlKRPCtm6nHD0oIXwRAGJLA' \
  -H 'FSE-JWT-Signature: eyJ4NWMiOlsiTUlJRmFUQ0NBMUdnQXdJQkFnSVVDcnNZd3BUYmhUOTRsL3Z3dEw1YlRxcEQveXN3RFFZSktvWklodmNOQVFFTEJRQXdWekVuTUNVR0ExVUVBd3dlUTBFZ1RXbHVhWE4wWlhKdklHUmxiR3hoSUZOaGJIVjBaU0JVWlhOME1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVFzd0NRWURWUVFHRXdKSlZEQWVGdzB5TXpBMk1UWXhNalEzTUROYUZ3MHlOakEyTVRZeE1qUTNNREphTUdveEN6QUpCZ05WQkFZVEFrbFVNUjh3SFFZRFZRUUtEQlpOYVc1cGMzUmxjbThnWkdWc2JHRWdVMkZzZFhSbE1SOHdIUVlEVlFSaERCWkRSanBKVkMxUVVrOVdRVmd3TUZnd01GZ3dNREJaTVJrd0Z3WURWUVFEREJCVE1TTXhNVEZUU1ZNMFEwRlNSVmhZTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFvUGJSK05tZTBsN2xyazJyTzRRblltbmxLQitVb2t4NW91ZVFTRFExYm9mRFluWFNVL3VGSU4zNVFrb3hUNGZyUTh1WDhMUmsrRjdMdXhQQzU4SmlwVHE1aUpWYzVIa2RJbkR2OEJQZkNDR00wN3ZzT3A0VWdQVWZoMWNCRndtRmljMytweXpPR01qdmI4WEdqMzdXRStabW9ua1oyQ1ZNTlhrWDFJNnpmSVhxMTd3RFYzN1dKMHFWRmdrbS9Ucm82R3FiNitqdVdMdXo3QUZMUWVzVU5kWjJTQjZ2SHB0YW1QZmJFdzExNkpjUHAxRkJEaThlbUEybTRvdkRuK0NIMnpxZDYzamR1K0FFbjJiSFdaKys2VUorNUhLbForc2dTbGlqTkZqN1E5OG1RS2Joci9naG1LZUt4OUFaaXQ1bDZnekNMZmxhMEZNelExNHFLOXZ3SlFJREFRQUJvNElCR0RDQ0FSUXdId1lEVlIwakJCZ3dGb0FVRmptcEdnV0p0dzh0c2pYdHdnbWF4UU9ESWo4d0VnWURWUjBnQkFzd0NUQUhCZ1VyVEIwQkN6Q0JyUVlEVlIwZkJJR2xNSUdpTUlHZm9JR2NvSUdaaG9HV2FIUjBjSE02THk5allYTnZaMlZwYzNacGJDNXpiMmRsYVM1cGRDOWxhbUpqWVM5d2RXSnNhV04zWldJdmQyVmlaR2x6ZEM5alpYSjBaR2x6ZEQ5amJXUTlZM0pzSm1semMzVmxjajFEVGlVelJFTkJLMDFwYm1semRHVnlieXRrWld4c1lTdFRZV3gxZEdVclZHVnpkQ1V5UTA4bE0wUk5hVzVwYzNSbGNtOHJaR1ZzYkdFclUyRnNkWFJsSlRKRFF5VXpSRWxVTUIwR0ExVWREZ1FXQkJUMS8yVGgyL2kzSzJsY0xPYWZ2cWxMbVBTMnFEQU9CZ05WSFE4QkFmOEVCQU1DQmtBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFEZGg2ZEFScDBGMWZtMDl3M1JHQ3M1dGRXZnVBQ2Y0ZEtUay9yZkR1bmhhcDNzdyt6TE9LOC9Za09vVXluUkdFZFhtQWxpT2swQy9oQ1duTkpxYUR2TGJWN3U5Q2V6Tzc5N2cwL0F2Sml2MHl1SUcySTB3MjRPd01NWUgxa29ZdmRxYkkyWExOQ0U2Y2hvQlFFS1F2V3hzQTNNeGt1bjFvVm5QdGltSGdCaXRDMXJNK1J5cnZXemRySFNRMG1HSm5HdlRLMFYxcWNrY3oxSlRhUGZqU3VCNFV3Mm9zZk5zVGI1WU54SE4rOGx3b1dtc01INnQzQjhIVHdqRjdRSGtSTlZOWDFWTUptYWlFZVFqYndyRzlRNkh0ZFZST0gwaXk4a1BoUWZqNklZYUtwdTk4UHEzUTVrUGxydHREMmtQOUV0QkIvV3VpaUFsc1AvYlhwV1F4aUE0UVJKN2dhTTJyT3lyMnpINlBLRkwyRzZkbTVvd2xpdEZkdmhRUm45NjRhQ0tGYlBKZjRIQzU0OTExeXlZRzJtcDZyN1JzS1FZMWN6UnRvLzhjdmdoVThPWEFaRXh5Sjl4QitmcnArWStrYXl1azZQNFNGNEtHcUQwUkRIOXZBRG5LcHRBa3pVZXM4eERVanJxZWJHWW1vWXhKTE9Fa05mRDZpSUhIWGQreWdDMlFDOUxzMkFEUzBBNVNlNFJXeko4TlA4U3RDemJVYVY1OVZycXl1emJOdjJQTytlTWtiRE5KRXR2QmMybUlDa0x1VUJTemY5NDU1cStuN1pkYmhubUlNQmtwMENqVUhFcEtvckp0OGhvbDdTTlV1ejZXdCtXOEZvR0NIMVpOcGZCUDczODZWbTdzc2wzWjh0dUhmS2IxWXZZY05jODdnQmpmMzMxaFgzbSJdLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJSU1NNQ0M4MEEwMUg1MDFUXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwdXJwb3NlX29mX3VzZSI6IlRSRUFUTUVOVCIsImlzcyI6ImludGVncml0eTpTMSMxMTFTSVM0Q0FSRVhYIiwibG9jYWxpdHkiOiIxMjAyMDUiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX3ZlcnNpb24iOiJWLjEuMS4wIiwic3ViamVjdF9vcmdhbml6YXRpb24iOiJSZWdpb25lIExhemlvIiwic3ViamVjdF9vcmdhbml6YXRpb25faWQiOiIxMjAiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuZnNlLnNhbHV0ZS5nb3YuaXQvZ292d2F5L3Jlc3QvaW4vRlNFL2dhdGV3YXkvdjEiLCJwYXRpZW50X2NvbnNlbnQiOnRydWUsImFjdGlvbl9pZCI6IkNSRUFURSIsInJlc291cmNlX2hsN190eXBlIjoiKCczNDEwNS03Xl4yLjE2Ljg0MC4xLjExMzg4My42LjEnKSIsImF0dGFjaG1lbnRfaGFzaCI6IjU4NmU0NmNiNmVhMGY3OTk5ZmY5Mjk5NWE5YWVlOTkxOTliYTQ4M2MzM2ZiY2E3ZDJmZGJkMTJjOWQ5YWU0NjMiLCJzdWJqZWN0X2FwcGxpY2F0aW9uX2lkIjoiU0lTNENBUkUiLCJleHAiOjE3MjQxNjgzMzEsInN1YmplY3RfYXBwbGljYXRpb25fdmVuZG9yIjoiUE9MSVMtTkVUIFNSTCIsImlhdCI6MTcyNDA4MTkzMSwianRpIjoiYzMwNzk1ZWU5ZDdkNDlhNGIyYzU0NTllMTVlMjA2NjUiLCJwZXJzb25faWQiOiJWVFRCQlI0NlA0N0M4NThQXl5eJmFtcDsyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImYW1wO0lTTyJ9.L9S6VMyWjB4j_p6KM8dLIV0S_13_ztfI48_7AQgwfOITtoucyNMPfJnzaTgqmwgFx5cnS2ATngDGVUNDOvZC8gtJonEk_jolgGul1VFU6gzCNpFSad9Ign88PuZOOzKDnnHbrwYXfBTVc0RXruN0LI3ksi97XA_649hluzFzbPul1dtS9vteGkGzqTO-OVWvA0AHnZIPKedas9Iu-l8hxNKrxv_7Ib7k38jGJkQwB6EFFMk4AFOPvDIgOT7aupOP3Rz3jLUX35J0JIPK0h1hZt7zYQaRLvGZG18ji-AN4HQ55NvXVxrDm3PP5DAXV-T8XwyurAdzM4BbDIknKrdBJQ' \
  -H 'Content-Type: multipart/form-data' \
  -F 'requestBody={"tipologiaStruttura":"Ospedale","tipoDocumentoLivAlto":"LDO","assettoOrganizzativo":"AD_PSC001","tipoAttivitaClinica":"DIS","identificativoSottomissione":"2.16.840.1.113883.2.9.2.120.4.3.12345","identificativoDoc":"2.16.840.1.113883.2.9.2.120.4.4^5548542","identificativoRep":"2.16.840.1.113883.2.9.2.120.4.5.97128","healthDataFormat":"CDA","mode":"ATTACHMENT","priorita":true}' \
  -F 'file=@ldo_59647_20240819_1_xml_signed.pdf;type=application/pdf'

**Comment by GrecoStefano** [comment]
l'errore che viene fornito è sempre il seguente 
{
  "traceID": "339eb23da7a5b5e0",
  "spanID": "339eb23da7a5b5e0",
  "type": "/msg/fhir-mapping-type",
  "title": "Mapping fhir fallito.",
  "detail": "multiple points",
  "status": 400,
  "instance": "/fhir-resource"
}

**Comment by GrecoStefano** [comment]
Buongiorno, abbiamo novità per questo problema?

**Comment by FAlessandroLC** [comment]
Buongiorno, ad integrazione lato gateway regionale non si riscontrano criticità. Restiamo in attesa di un vostro gentile riscontro al fine di poter finalizzare la procedura di accreditamento

**Comment by GrecoStefano** [comment]
Buon pomeriggio,

Vi scrivo per richiedere nuovamente un chiarimento riguardo alla problematica segnalata nel nostro primo messaggio. A quasi due settimane dalla nostra comunicazione iniziale, il prolungato ritardo nel ricevere una risposta sta causando l'inevitabile stop riguardo l'accreditamento ai servizi regionali di LazioCrea. Questa situazione sta generando notevoli inconvenienti.

**Comment by LucaRogledi** [comment]
Buongiorno, affinchè la trasformazione vada a buon a fine è necessario che il versionNumber/@value sia un numero intero positivo. Inoltre, consigliamo di non inserire tag vuoti (es. <text/>)
Grazie.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, chiudiamo la presente issue.
La invitiamo a riaprirla nel caso in cui avesse bisogno di ulteriore supporto.
Grazie.
