### ISSUE TITLE
Injection Mode chiarimenti

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#968]
Buongiorno,

Analizzando la documentazione, si è vista la possibilità di iniettare il CDA su PDF in due modalità, attraverso in modalità Attachment o in modalità Resource.  Vorremmo chiedere se fosse possibile avere degli esempi per le due modalità.

Grazie in anticipo.

**Comment by LucaRogledi** [comment]
Buongiorno, 
Di seguito può trovare due esempi di pdf con il cda iniettato:

modalità Attachment: [pdf-attachment.pdf](https://github.com/user-attachments/files/16658659/pdf-attachment.pdf)

modalità Resource: [pdf-resource.pdf](https://github.com/user-attachments/files/16658608/pdf-resource.pdf)

al seguente link di HL7 può trovare maggiori informazioni riguardo l'iniezione del cda all'interno del pdf: https://www.hl7.it/realm-italiano/iniezione-di-un-cda-in-un-pdf-per-la-firma-digitale/
