### ISSUE TITLE
Sezione DICOM Object Catalog in referti RAD

### ISSUE THREAD

**Issue by GruppoSiges** [ministero-salute/it-fse-support#969]
Buongiorno, 

devo tornare sulla questione già affrontata relativa al test 446 della checklist, che prevede la produzione di un cda2 comprensivo della sezione DICOM Object Catalog.
Dato che abbiamo già chiarito che il Decreto 07 settembre 2023 rende obbligatorio il test 446, avrei bisogno di informazioni su come compilare la sezione di cui sopra, o di indicazioni circa dove reperirle, dato che online non si trovano esempi significativi (nel senso che tutti gli esempi riportano dei codici senza specificarne il significato, e sembrano essere tutti un copia e incolla di uno stesso esempio preso chissà dove), e addirittura il test prevede tag che non sono documentati nel documento di hl7 (ad esempio, il tag "code" del nodo "observation", o i tag translation: per questi ultimi, nell'esempio riportato in https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/RSA.xml, sono indicati dei codici del catalogo SISS relativi ad esami di laboratorio, e lo stesso codice è utilizzato in contesti diversi, aumentando la confusione circa la natura dell'informazione che dovrebbe veicolare).
Grazie, buona giornata.

**Comment by GruppoSiges** [comment]
Chiedo scusa, l'esempio citato è https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/RAD.xml

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto.
