### ISSUE TITLE
Codice AIC non presente 023181050 (Voltaren)

### ISSUE THREAD

**Issue by CidSoftwareDev** [ministero-salute/it-fse-support#97]
Buongiorno,
nell'operazione di convalida al gateway di test, otteniamo questo errore per il farmaco 023181050 (Voltaren) (somministrazione in pronto soccorso).

```
{"status":400,"traceID":"1dc22eebb2737eb5","spanID":"1dc22eebb2737eb5","type":"/msg/vocabulary","title":"Errore vocabolario.","detail":"Almeno uno dei seguenti vocaboli non Ã¨ censito: [CodeSystem: 2.16.840.1.113883.2.9.6.1.5, Codes: 023181050]","instance":"/validation/error","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.379fcbf485692b6fc38c5751d841714ae9e1191cc5f4cfa44bfcbe4decc91a5a.41c6896a9d^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}}
Validazione in errore! Status Code: 400
error Almeno uno dei seguenti vocaboli non Ã¨ censito: [CodeSystem: 2.16.840.1.113883.2.9.6.1.5, Codes: 023181050]
```

E' solo il caso di questo farmaco o ci sono altri farmaci che non sono (e/o non saranno) censiti sul vostro sistema?

In produzione, in questi casi, immaginiamo che la validazione non possa comunque essere eseguita (così come la firma del documento) e dovremo necessariamente posticiparla o saltarla del tutto.

Grazie

**[EDIT]**
Problema identico durante un'altra prova. AIC: 035348010, 035619042 non presenti.

**Comment by IStacchiotti** [comment]
Buongiorno, le chiederei cortesemente di riprovare, l'errore non dovrebbe più verificarsi. Grazie.

**Comment by IStacchiotti** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso contrario.
