### ISSUE TITLE
Tag iat in jwt 

### ISSUE THREAD

**Issue by GruppoSiges** [ministero-salute/it-fse-support#971]
Buongiorno, sto ricevendo, nella validazione di un cda2, l'errore "401 - 'iat' token claim is in the future". 

Ho verificato sia il token di autenticazione che il token di firma e in entrambi i casi il valore del tag corrisponde all'orario di sistema (che è corretto). Ho comunque provato a forzare un jwt generato minuti prima (con il tag sicuramente non "futuro") ma ottengo lo stesso errore.

Grazie, saluti.

**Comment by GruppoSiges** [comment]
Ho scoperto che per qualche ragione il server della procedura era andato fuori sync di 6 secondi, quindi dovrebbe dipendere da questo. Nel test con il jwt creato minuti prima devo evidentemente aver sbagliato qualcosa.
Potete considerare chiuso l'argomento.

Grazie, saluti.

**Comment by LucaRogledi** [comment]
Buongiorno, confermiamo che non sono state riscontrate anomalie e il sistema risulta disponibile correttamente. Ringraziamo per la segnalazione e procediamo con la chiusura.
