### ISSUE TITLE
Accreditamento nuovo prodotto

### ISSUE THREAD

**Issue by fabiodap** [ministero-salute/it-fse-support#972]
Buongiorno,

come Fujifilm Italia siamo accreditati per i prodotti Synapse Value e Synapse workflow per CDA di radiologia e di specialistica ambulatoriale.

Adesso si aggiunge un nuovo prodotto a quelli sopra indicati da accreditare per il CDA di specialistica ambulatoriale.

Ci sono procedure semplificate per efettuare questa operazione? Oppure bisogna ripartire dall'inizio? Ovverosia da:

_Il fornitore, richiede a Sogei certificati di test associati al fornitore (mediante email all’indirizzo [fse_support@sogei.it](mailto:fse_support@sogei.it) fino a quando non sarà disponibile il sistema di provisioning che rilascerà anche i certificati di test) per accedere ai servizi esposti dalla piattaforma gateway di test in ambiente di pre produzione (esempio: un fornitore che avvia il processo di accreditamento per due applicativi può usare il medesimo certificato)._

Saluti,
Fabio

**Comment by LucaRogledi** [comment]
Buonasera, come indicato in [documentazione](https://developers.italia.it/it/fse/#resourcecontent-1) per la fase 1 di accreditamento, i certificati possono essere utilizzati per l'accreditamento di tutti gli applicativi del medesimo fornitore. 
Può procedere con l'accreditamento di un nuovo applicativo inviando la richiesta di accreditamento su [EuSurvey](https://ec.europa.eu/eusurvey/runner/FSE-2-validazione) indicando tutti i cda gestiti dal nuovo applicativo.

Successivamente, sarà necessario effettuare i test relativi alle tipologie documentali in esame.
I risultati dei test eseguiti dovranno essere caricati su GitHub tramite una pull request in una cartella creata ad hoc per l'applicativo, che dovrà riflettere la struttura indicata in [documentazione](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/README.md#procedura-di-caricamento-dei-risultati):
`GATEWAY/{commonName auth}/{subject_application_vendor}/{subject_application_id}/{subject_application_version}`
Poiché lei ha già creato tale cartella, sarà sufficiente inserire al suo interno le sottocartelle relative al nuovo applicativo:
`GATEWAY/{commonName auth}/{subject_application_vendor}/{subject_application_id_app2}/{subject_application_version_app2}`
 
La pull request dovrà contenere:
 
- file data.json contenente i riferimenti di tracciatura dei risultati dei test;
- file pdf usati nelle invocazioni dei servizi (all'interno della directory FILES);
- file riassuntivo (foglio di calcolo) report-checklist.xlsx di tutti i test case eseguiti.

La informiamo, inoltre, che sarà necessario utilizzare l'ultima versione rilasciata del file report-checklist (V8.2.1), disponibile al link: https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/accreditamento-checklist_V8.2.1.xlsx

Rimaniamo a disposizione nel caso in cui avesse ulteriori dubbi.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto alcun riscontro, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso in cui abbia bisogno di ulteriore supporto.
Grazie.
