### ISSUE TITLE
Info - Pull Request

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#973]
Buongiorno

La pull https://github.com/ministero-salute/it-fse-accreditamento/pull/1597 è ancora pendente.
Ne vedo altre nel medesimo stato e un'etichetta "deep" per la mia. Ci sono problemi?

Nel mio caso, avrei dovuto specificare la soluzione adottata in caso di timeout.
Nel breve, l'errore viene ignorato e il referto viene firmato con il CDA iniettato; prima della pubblicazione, il referto viene validato nuovamente (se l'errore è su 300 referti, evito al refertatore di ri-guardare e ri-firmare tutti i referti - tra le cose, non mi aspetto di creare CDA non validi). E' chiaro che l'eventuale errore determinato dalla seconda validazione sarà trattato e gestito.

**Comment by vigliottim** [comment]
Buon pomeriggio,
la label "DEEP DIVE" identifica il fatto che ha ricevuto delle richieste di chiarimenti via e-mail da parte del DTD.
La invitiamo ad attendere che le analisi relative alla sua successiva pull request correttiva vengano concluse.
Grazie.
