### ISSUE TITLE
Info Pull

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#974]
Buongiorno

Torno sempre alla pull 1597, ancora pendente.
Vedo sempre il label DEEP DIVE; delle altre è stato fatto il merge. 

L'accreditamento per il RAD è iniziato il 10 luglio: da allora, ho dovuto modificare 3 volte il documento xls (versione 8.2, poi 8.2.1, poi per la modifica dei casi di test). Nell'ultima mail, mi si chiedeva di specificare meglio il comportamento assunto dal programma a seguito del time-out (nulla più).

https://github.com/ministero-salute/it-fse-accreditamento/pull/1597

**Comment by vigliottim** [comment]
Buongiorno, 
la pull request da lei indicata è stata contrassegnata solo ieri con label _deep dive_: essa indica che sono in corso le verifiche conclusive sulla checklist da parte del DTD (Dipartimento di Trasformazione Digitale). 
Riceverà una e-mail con l'esito delle elaborazioni una volta concluse. 
Rimaniamo a disposizione per chiarimenti.
