### ISSUE TITLE
Accreditamento - Pull 1606

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#975]
Buongiorno, trovate una nuova pull per it-fse-accreditamento.
La modifica del file excel va a specificare il comportamento adottato in caso di timeout.

https://github.com/ministero-salute/it-fse-accreditamento/pull/1606

**Comment by LucaRogledi** [comment]
Buongiorno, la ringraziamo per la notifica. Procediamo alla chiusura della presente issue e rimaniamo a disposizione per ulteriori richieste di supporto.
