### ISSUE TITLE
GTW Lazio + Info

### ISSUE THREAD

**Issue by ds-tommaso** [ministero-salute/it-fse-support#977]
Buongiorno

// Referto LAB/RAD - Pull https://github.com/ministero-salute/it-fse-accreditamento/pull/1606

Di nuovo, sono a chiedere info sull'accreditamento della soluzione software per la radiologia (avviata il 10 luglio e ferma da un mesetto in DEEP - di nuovo, mi si era chiesto solo di specificare il comportamento a seguito di timeout).

Se ignorare il problema (posticipando la nuova validazione alla fase dell'invio) non può essere soluzione - almeno al momento - posso cambiare la mia gestione. Ho necessità di aggiornare un cliente RAD in Campania e inviare la terna del software (da due mesi)!

// LazioCrea - Errore aggiornamento (e cancellazione)

Riscontro l'errore 404 quando pubblico una nuova versione del referto su GTW laziale.
Ho sentito integrazioni.fse@laziocrea.it che però mi rimandano a scrivere l'issue.
Negli allegati, potete trovare i PDF, gli esiti delle due validazioni, della pubblicazione e del mancato aggiornamento.

Versione 1
id/@root = 2.16.840.1.113883.2.9.2.120.4.4
id/@extension=120201531618_129911T1V1
[referto-v1.zip](https://github.com/user-attachments/files/16836468/referto-v1.zip)

```
{
    "timestamp": "2024-08-30T23:48:46.8692398+02:00",
    "traceID": "9bddca20c602d6e4",
    "spanID": "9bddca20c602d6e4",
    "type": null,
    "title": null,
    "detail": null,
    "status": 201,
    "instance": null,
    "warning": "",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.5cb287be6f30feb10924157b7ed15a77480e4989219780b3eac7fb76a7e7727d.66dd054646^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
    "transactionData": null
}
```

Versione 2
id/@root = 2.16.840.1.113883.2.9.2.120.4.4
id/@extension=120201531618_129911T1V2
Endpoint [PUT] https://fse-services-test.regione.lazio.it/fse-middleware/gateway/v1/documents/2.16.840.1.113883.2.9.2.120201.4.4%5e120201531618_129911T1V1

[referto-v2.zip](https://github.com/user-attachments/files/16836469/referto-v2.zip)

```
{
    "timestamp": "2024-08-30T23:56:56.154543+02:00",
    "traceID": "3031be1a2346dc20",
    "spanID": "3031be1a2346dc20",
    "type": "/msg/record-not-found",
    "title": "Record non trovato.",
    "detail": "No Record Found",
    "status": 404,
    "instance": "/record-not-found",
    "warning": null,
    "workflowInstanceId": null,
    "transactionData": null
}
```

**Comment by LucaRogledi** [comment]
Buongiorno,
Riguardo alla prima richiesta di accreditamento confermiamo che la PR #1606 è stata presa in carico e che le opportune verifiche sono in corso di svolgimento, riceverà un riscontro via email appena possibile. Nel frattempo la invitiamo a non chiudere la PR #1606.
 
Riguardo la procedura di sostituzione documento fallita, sembrerebbe che l'errore ricevuto sia dovuto all'utilizzo di un identificativoDoc all'interno dell'URL errato, in quanto è stato utilizzato 
`https://fse-services-test.regione.lazio.it/fse-middleware/gateway/v1/documents/2.16.840.1.113883.2.9.2.120201.4.4%5e120201531618_129911T1V1` 
come riportato nello screenshot di seguito:

![image](https://github.com/user-attachments/assets/2dabfc4a-06fe-47bc-84cd-e849e3230ff8)
 
mentre il documento pubblicato in precedenza è identificato con:
`2.16.840.1.113883.2.9.2.120.4.4%5E120201531618_129911T1V1`

Come evidenziato dalla risposta del servizio di status per workflowInstanceId della chiamata di pubblicazione:

![image](https://github.com/user-attachments/assets/562c217f-2a3f-4960-b0b7-02861dee48ca)

Pertanto l'URL corretto per la chiamata di sostituzione dovrebbe risultare come:
`https://fse-services-test.regione.lazio.it/fse-middleware/gateway/v1/documents/2.16.840.1.113883.2.9.2.120.4.4%5E120201531618_129911T1V1`

Restiamo a disposizione per ulteriore supporto. Grazie

**Comment by ds-tommaso** [comment]
Risolto il problema con l'operazione di aggiornamento - ho pubblicato diverse versioni di uno stesso documento.

"404 - Document cannot be found on the Server FHIR"  è l'errore della cancellazione.
Di seguito, i LOG della chiamata ma.. mi riservo di far ulteriori verifiche

[T1V4_publicationDelete_req.json](https://github.com/user-attachments/files/16838951/T1V4_publicationDelete_req.json)
[T1V4_publicationDelete_res.json](https://github.com/user-attachments/files/16838952/T1V4_publicationDelete_res.json)

**Comment by ds-tommaso** [comment]
forse solo questione di tempo per indicizzare il documento: alcuni sono stati cancellati correttamente, altri no

**Comment by ds-tommaso** [comment]
Noto però che non tutti i referti vengono eliminati. 
La modifica è sempre disponibile invece.

Di seguito, un esempio di pubblicazione la cui cancellazione fallisce.

[T1V1_publicationCreateRequest_req.json](https://github.com/user-attachments/files/16840228/T1V1_publicationCreateRequest_req.json)
[T1V1_publicationCreate_req.json](https://github.com/user-attachments/files/16840229/T1V1_publicationCreate_req.json)
[T1V1_publicationCreate_res.json](https://github.com/user-attachments/files/16840230/T1V1_publicationCreate_res.json)

```
{
    "timestamp": "2024-09-02T19:33:20.1936812+02:00",
    "traceID": "911ab001bb3c4394",
    "spanID": "911ab001bb3c4394",
    "type": null,
    "title": null,
    "detail": null,
    "status": 201,
    "instance": null,
    "warning": "",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.2ce270c236bc4e3ec7d0bac9100b26360470429985f51918d43d6133b0b551b2.076759f171^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
    "transactionData": null
}
```
Ok la ricerca tramite traceId (SUCCESS)

[T1V2_searchStatusByTraceId_res.json](https://github.com/user-attachments/files/16840218/T1V2_searchStatusByTraceId_res.json)
[T1V2_searchStatusByTraceId_req.json](https://github.com/user-attachments/files/16840219/T1V2_searchStatusByTraceId_req.json)

Ok la ricerca tramite WorkflowInstanceId (SUCCESS per tutti gli attori coinvolti)

[T1V2_searchStatusByWorkflowInstanceId_res.json](https://github.com/user-attachments/files/16840223/T1V2_searchStatusByWorkflowInstanceId_res.json)
[T1V2_searchStatusByWorkflowInstanceId_req.json](https://github.com/user-attachments/files/16840224/T1V2_searchStatusByWorkflowInstanceId_req.json)

**Comment by vigliottim** [comment]
Buongiorno,
le chiediamo di fornirci la request e la response complete di una delle chiamate di cancellazione che vanno in errore.
Grazie.

**Comment by ds-tommaso** [comment]
**Qui, un esempio di cancellazione che solo oggi va a buon fine**

Immagino sia dovuto ai tempi di indicizzazione (se pur, abbia cancellato altri documenti dopo pochissimi minuti)

2024-09-03
[T1V2_publicationDelete_req.json](https://github.com/user-attachments/files/16846181/T1V2_publicationDelete_req.json)
[T1V2_publicationDelete_res.json](https://github.com/user-attachments/files/16846182/T1V2_publicationDelete_res.json)

2024-09-02
[T1V2_publicationDelete_req - 2024.09.02.json](https://github.com/user-attachments/files/16846201/T1V2_publicationDelete_req.-.2024.09.02.json)
[T1V2_publicationDelete_res - 2024.09.02.json](https://github.com/user-attachments/files/16846202/T1V2_publicationDelete_res.-.2024.09.02.json)

**Qui, una cancellazione che va in errore**

DELETE https://fse-services-test.regione.lazio.it/fse-middleware/gateway/v1/documents/2.16.840.1.113883.2.9.2.120.4.4%5e120201531618_129919T1V2

[T1V3_publicationDelete_res.json](https://github.com/user-attachments/files/16846309/T1V3_publicationDelete_res.json)
[T1V3_publicationDelete_req.json](https://github.com/user-attachments/files/16846310/T1V3_publicationDelete_req.json)

Esito prima pubblicazione (status OK)

id/@root = 2.16.840.1.113883.2.9.2.120.4.4; id/@extension = 120201531618_129919T1V1
POST https://fse-services-test.regione.lazio.it/fse-middleware/gateway/v1/documents

[T1V1_publicationCreate_req.json](https://github.com/user-attachments/files/16846462/T1V1_publicationCreate_req.json)
[T1V1_publicationCreate_res.json](https://github.com/user-attachments/files/16846463/T1V1_publicationCreate_res.json)
[T1V1_publicationCreateRequest_req.json](https://github.com/user-attachments/files/16846465/T1V1_publicationCreateRequest_req.json)

```
{
    "timestamp": "2024-09-02T19:33:14.5480163+02:00",
    "traceID": "796c710b2d3318db",
    "spanID": "796c710b2d3318db",
    "type": null,
    "title": null,
    "detail": null,
    "status": 201,
    "instance": null,
    "warning": "",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.242549a8fd698911b8b6a0095a552046a062a693b31ff7ef4d85901e707cef75.45f8b9b6eb^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
    "transactionData": null
}
```

Esito aggiornamento (status errore al SEND_TO_EDS per documento non trovato)

id/@root = 2.16.840.1.113883.2.9.2.120.4.4; id/@extension = 120201531618_129919T1V2
PUT https://fse-services-test.regione.lazio.it/fse-middleware/gateway/v1/documents/2.16.840.1.113883.2.9.2.120.4.4%5e120201531618_129919T1V1

[T1V2_publicationUpdateRequest_req.json](https://github.com/user-attachments/files/16846481/T1V2_publicationUpdateRequest_req.json)
[T1V2_publicationUpdate_req.json](https://github.com/user-attachments/files/16846482/T1V2_publicationUpdate_req.json)
[T1V2_publicationUpdate_res.json](https://github.com/user-attachments/files/16846483/T1V2_publicationUpdate_res.json)

```
{
    "timestamp": "2024-09-02T19:34:28.4248244+02:00",
    "traceID": "e0b95045a53a763d",
    "spanID": "e0b95045a53a763d",
    "type": null,
    "title": null,
    "detail": null,
    "status": 200,
    "instance": null,
    "warning": "",
    "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.ec17aa2e7cf3a17a219e8afd6864f58ece260cb7895fc08c334f1dee2494c086.4f73df84fd^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
    "transactionData": null
}
```

Anche qui, il problema può essere nei tempi di indicizzazione?
Provo ad ipotizzare... il documento è stato pubblicato con successo. Prima ancora dell'avvenuta di SEND_TO_INI (o SEND_TO_EDS o EDS_WORKFLOW) è stato aggiornato. Io ho ricevuto OK dall'aggiornamento ma - in realtà - il documento non è stato mai aggiornato (segue l'impossibilità di cancellare la versione 2 del documento).

**Comment by LucaRogledi** [comment]
Buon pomeriggio, l'errore riscontrato potrebbe essere dovuto dal fatto che la richiesta di delete è stata effettuata subito dopo la richiesta di pubblicazione/sostituzione. Per scongiurare errori di questo tipo la invitiamo a riprovare avendo cura di attendere almeno 15 minuti prima della richiesta di delete. In caso l'errore dovesse ripresentarsi la invitiamo a fornirci le response complete del flusso delle chiamate andato in errore da pubblicazione/sostituzione alla delete. Grazie
