### ISSUE TITLE
Document cannot be found on the Server FHIR ritornato dal servizio DELETE

### ISSUE THREAD

**Issue by giosil** [ministero-salute/it-fse-support#978]
Dopo aver creato il documento "identificativoDoc":"2.16.840.1.113883.2.9.2.120.4.4^120.20240903135916" con successo ottenendo:

{"traceID":"02caeae1ab51d544","spanID":"02caeae1ab51d544","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.3b2ec62ba8e9a4c44ce048ebe3c8cdffed09c705f42b6e6f49801054ea87f2c9.12ecb29040^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

nell'eseguire la delete con l'identificativo sopra riportato otteniamo:

{"traceID":"4b235c863d662424","spanID":"4b235c863d662424","type":"/msg/eds-error","title":"Eds error.","detail":"Document cannot be found on the Server FHIR","status":404,"instance":"/msg/eds-document-missing"}

**Comment by vigliottim** [comment]
Buon pomeriggio,
la chiamata al servizio di delete è stata effettuata subito dopo la chiamata di pubblicazione, a distanza di un minuto.
Le chiediamo di riprovare attendendo almeno un quarto d'ora prima di eseguire la chiamata al servizio di delete.
Rimaniamo a disposizione qualora il problema non dovesse risolversi.

**Comment by giosil** [comment]
Salve, eseguendo ora la chiamata otteniamo:

{"traceID":"213a842dc9a92e3e","spanID":"213a842dc9a92e3e","warning":"Attenzione, transazione presa in carico. Nuovo tentativo in corso","workflowInstanceId":"c150bc780df8ed5f8a89038ae6b78caa29a2424fece053e65d8d4ecabfbc7182.aa34e05256^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

**Comment by izamberlan** [comment]
Scusate se intervengo, ma la cancellazione non è sincrona? Cosa significa il warning di presa in carico in questo contesto?

**Comment by LucaRogledi** [comment]
Buongiorno, 
@giosil potrebbe gentilmente riportare la chiamata soap che viene effettuata verso INI se disponibile?
@izamberlan la transazione di delete è un servizio sincrono andato in OK solo su EDS e in KO su INI, quindi per assicurare coerenza tra INI ed EDS il Gateway riprova ad eseguire una cancellazione asincrona verso INI, ottenendo però, in questo caso un errore bloccante “Missing mandatory attributes in the attribute assertion”.
Grazie

**Comment by giosil** [comment]
Buongiorno, non abbiamo rilevato traccia della delete. Il messaggio da voi riscontrato non è stato restituito dai nostri servizi esposti ad INI.
Probabilmente la chiamata è stata bloccata da INI stessa a causa della mancanza di alcuni attributi nell'asserzione SAML.
Saluti.

**Comment by izamberlan** [comment]
@LucaRogledi grazie per la spiegazione, non mi era chiaro questo funzionamento

**Comment by g-maugeri-sogei** [comment]
Buongiorno, potreste effettuare un nuovo tentativo e in caso di errore fornirci il CF dell'assistito e il timestamp della chiamata ?

**Comment by giosil** [comment]
Buongiorno, ripetendo l'operazione ora non otteniamo più il warning. Di seguito i riferimenti ottenuti in risposta:

{"traceID":"a597804a1a4dc97a","spanID":"a597804a1a4dc97a","workflowInstanceId":"c150bc780df8ed5f8a89038ae6b78caa29a2424fece053e65d8d4ecabfbc7182.f5199545e6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}

Lato servizi XDS esposti verso INI ora abbiamo riscontrato anche la chiamata di delete.
Grazie. Saluti,

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo con la chiusura della segnalazione, Restiamo a disposizione in caso fosse necessario ulteriore supporto. Grazie
