### ISSUE TITLE
Codifica TipoEncounter_VPS

### ISSUE THREAD

**Issue by CidSoftwareDev** [ministero-salute/it-fse-support#98]
Buongiorno,
nella sezione "4.5 Encounters" del documento HL7API per il VPS, si fa riferimento ad una codifica di tipo "TipoEncounter_VPS" che, però, non ha riferimenti nella sezione "6.2.2 Vocabolari e Value Set".

Abbiamo provato a recuperare i valori da qui 
`http://art-decor.org/art-decor/decor-valuesets--vpsee-?id=2.16.840.1.113883.2.9.1.11.1.2.4`
ma anche qui non sono indicati.

Anche nell'esempio disponibile qui
`https://github.com/ministero-salute/it-fse-support/blob/main/doc/esempi/CDA/VPS.xml`
è indicato un generico valore "XXX" senza una valorizzazione specifica.

E' possibile avere un riferimento con l'elenco dei codici accettati?
Ad esempio, in caso di accesso in OBI, come dovremo valorizzare l'encounter?

Grazie

**Comment by IStacchiotti** [comment]
Grazie della segnalazione, vi suggeriamo per la valorizzazione del campo indicato di far riferimento alla nuova versione 1.1.1 della guida implementativa del Verbale di Pronto Soccorso pubblicata sul sito di HL7 Italia il 9/01/2023.
Nello specifico, nel VPS vengono esplicitate le possibili opzioni di valorizzazione dell'elemento encounter/code:
• gli interventi codificati secondo la classificazione ICD-9-CM;
• le prestazioni di specialistica ambulatoriale codificate nel nomenclatore nazionale;
• le prestazioni di specialistica ambulatoriale codificate nei nomenclatori regionali.

**Comment by CidSoftwareDev** [comment]
Buonasera, grazie della celere risposta. Avevamo però come dicevamo un dubbio. 
Nel caso in cui dovessimo segnalare un accesso in OBI, come dovremmo valorizzare l'Encounter essendo il campo 'Code' obbligatorio?

Grazie

**Comment by IStacchiotti** [comment]
Salve, se l'issue è associata alla valorizzazione del codice dell'elemento entry/encounter/code all'interno della section encounters, il valore del campo deve essere associato al dettaglio delle singole visite.

**Comment by CidSoftwareDev** [comment]
Perdonami, forse sono stato ancora poco felice nella richiesta. 
Se io volessi inserire in questa sezione che riporto in basso, l'accesso in OBI, al posto di **XXX** che valore devo mettere? (non mi riferisco alle prestazioni singole eseguite in PS o in OBI ma all'evento di accesso effettivo in OBI compreso di data ingresso e data di uscita in OBI):

```
<entry>
<encounter moodCode="EVN" classCode="ENC"> 
	<templateId root="2.16.840.1.113883.2.9.10.1.6.51"/>
	<code code="XXX" codeSystem="2.16.840.1.113883.2.9.1.11.1.2.4" codeSystemName="TipoEncounter_VPS" displayName="[DESC_VISITA]"/>
	<effectiveTime>
		<low value="20220415090909+0100"/>
		<high value="20220415160000+0100"/>
	</effectiveTime>
....
....
```

Oppure non va codificato l'accesso in OBI ?
Resto in attesa.

**Comment by IStacchiotti** [comment]
Buongiorno, se si vuole dettagliare nello specifico il percorso di OBI, e non il dettaglio della visita effettuata durante il periodo di ricovero in PS, si può utilizzare l'elemento code del tipo encounter con il valore associato all'OBI.
Sulla guida del VPS il code non viene vincolato a specifici dizionari, una possibile valorizzazione potrebbe derivare dalla tabella dei valori ammessi del campo Esito trattamento presente nel documento
EMUR (https://www.salute.gov.it/imgs/C_17_pagineAree_2992_6_file.pdf) a pag 108.

**Comment by CidSoftwareDev** [comment]
Ok, Grazie mille.
