### ISSUE TITLE
Errore servizio di eliminazione: com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: javax.transaction.TransactionRolledbackException:

### ISSUE THREAD

**Issue by federicolau** [ministero-salute/it-fse-support#982]
Ciao,

stiamo riscontrando problemi con la **chiamta al servizio di eliminazione**.
A seguire gli step che abbiamo conseguito.

**1. Chiamata al servizio di validazione:**

```
POST https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation

data:
--Y_CzLHbw3eFAxQsYsH1A0pQCfGwwOl2xIgwk7
Content-Disposition: form-data; name="requestBody"
Content-Type: application/json; charset=UTF-8
Content-Transfer-Encoding: 8bit

{"activity": "VALIDATION"}
--Y_CzLHbw3eFAxQsYsH1A0pQCfGwwOl2xIgwk7
Content-Disposition: form-data; name="file"; filename="output.pdf"
Content-Type: application/pdf
Content-Transfer-Encoding: binary

<actual file content, not shown here>
--Y_CzLHbw3eFAxQsYsH1A0pQCfGwwOl2xIgwk7--
```

 ottenendo la seguente la seguente risposta:

`{"traceID":"f5032fb0ca17fd9f","spanID":"f5032fb0ca17fd9f","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.ff77cd5bb8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","warning":"[[SIGN_WARN - Attenzione il documento risulta firmato in validazione][WARNING_EXTRACT]Attenzione, non Ã¨ stata selezionata la modalitÃ  di estrazione del CDA]"}`

**2. Chiamata al servizio di pubblicazione:**

```
POST https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents

POST data:
--rDEZiZrsyTU9yPAIhYYCaYkz9rUBky2wSL-sMD-Y
Content-Disposition: form-data; name="requestBody"
Content-Type: multipart/form-data; charset=UTF-8
Content-Transfer-Encoding: 8bit

{    "healthDataFormat": "CDA",   "mode": "ATTACHMENT",   "tipologiaStruttura": "Ospedale",   "attiCliniciRegoleAccesso": [     "PUBLICPOL"   ],   "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^464839",   "identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.1",   "tipoDocumentoLivAlto": "REF",   "assettoOrganizzativo": "AD_PSC001",   "dataInizioPrestazione": "20141020110012",   "dataFinePrestazione": "20141020110012",   "tipoAttivitaClinica": "CON",   "identificativoSottomissione": "2.16.840.1.113883.2.9.2.120.4.3.489592",   "priorita": false,   "descriptions": [     "019655^Bentelan^2.16.840.1.113883.2.9.6.1.5"   ],   "administrativeRequest":[ "SSN"] }
--rDEZiZrsyTU9yPAIhYYCaYkz9rUBky2wSL-sMD-Y
Content-Disposition: form-data; name="file"; filename="output.pdf"
Content-Type: application/pdf
Content-Transfer-Encoding: binary

<actual file content, not shown here>
--rDEZiZrsyTU9yPAIhYYCaYkz9rUBky2wSL-sMD-Y--
```

 ottenendo la seguente la seguente risposta:

`{"traceID":"7ce9ee34ed3ca0f2","spanID":"7ce9ee34ed3ca0f2","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.ff77cd5bb8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

**3. Chiamata al servizio di status:**

`GET https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/status/2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.ff77cd5bb8%5E%5E%5E%5Eurn%3Aihe%3Aiti%3Axdw%3A2013%3AworkflowInstanceId`

 ottenendo la seguente la seguente risposta:

`{"traceID":"0b3dd7805522c435","spanID":"75230b94fdeac77b","transactionData":[{"eventType":"VALIDATION","eventDate":"2024-09-05T10:42:25.437+00:00","eventStatus":"SUCCESS","subject":"GTWGWY82B42G920M","organizzazione":"160","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.ff77cd5bb8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","traceId":"f5032fb0ca17fd9f","issuer":"integrity:S1#160#REGIONEPUGLIATEST","expiringDate":"2025-09-05T10:42:25.447+00:00"},{"eventType":"PUBLICATION","eventDate":"2024-09-05T10:42:27.290+00:00","eventStatus":"SUCCESS","identificativoDocumento":"2.16.840.1.113883.2.9.2.120.4.4^464839","subject":"GTWGWY82B42G920M","tipoAttivita":"CON","organizzazione":"160","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.ff77cd5bb8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","traceId":"7ce9ee34ed3ca0f2","issuer":"integrity:S1#160#REGIONEPUGLIATEST","expiringDate":"2025-09-05T10:42:27.300+00:00"}]}`

4. **Chiamata al servizio di delete che va in errore (dopo aver atteso 15/20 minuti)** :

`DELETE https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.120.4.4%5E464839`

 ottenendo la seguente la seguente risposta:

`{"traceID":"562b186fe50cd4e2","spanID":"562b186fe50cd4e2","type":"/msg/ini-error","title":"Ini error.","detail":"{\"traceID\":\"562b186fe50cd4e2\",\"spanID\":\"8f499a3e491388fc\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: javax.transaction.TransactionRolledbackException:  ; nested exception is: \\n\\tjavax.transaction.SystemException Please see the server log to find more detail regarding exact cause of the failure.\",\"instance\":\"error/generic\"}","status":500,"instance":"/msg/service-error/ini"}`

**Abbiamo anche provato con un timeout di 60 secondi.**

In allegato:

[Authorization token.txt](https://github.com/user-attachments/files/16895845/Authorization.token.txt)
[FSE-JWT-Signature token.txt](https://github.com/user-attachments/files/16895846/FSE-JWT-Signature.token.txt)
[PDF con CDA Iniettato](https://github.com/user-attachments/files/16895847/output.1.pdf)

Come possiamo risolvere?

Grazie.

**Comment by g-maugeri-sogei** [comment]
Buongiorno, potete riprovare e darci riscontro?

**Comment by federicolau** [comment]
Adesso funziona, grazie.

**Comment by LucaRogledi** [comment]
Buongiorno, ringraziamo per il feedback e procediamo alla chiusura della segnalazione come risolta.
