### ISSUE TITLE
Errore 403 nuovo certificato

### ISSUE THREAD

**Issue by AlessioMaggioriGMED** [ministero-salute/it-fse-support#983]
Buongiorno,
stiamo testando la validazione di un documento con nuovi certificati emessi per un altro nostro applicativo. Con questo nuovo certificato otteniamo errore 403.

{"type":"https://govway.org/handling-errors/403/AuthorizationContentDeny.html","title":"AuthorizationContentDeny","status":403,"detail":"Unauthorized
 request content","govway_id":"7614094e-6c2c-11ef-8aa0-005056ae54fa"}

I nostri dati sono i seguenti:
subject_application_id: VirtuHIS[ESB]
subject_application_vendor: Gmed srl
subject_application_version: 1.2.0

Grazie per il supporto
Saluti

Alessio Maggiori

**Comment by vigliottim** [comment]
Buongiorno,
dalle analisi svolte sembrerebbe che l'errore sia causato dall'errata valorizzazione del campo _iss_ contenuto nei token:

![image](https://github.com/user-attachments/assets/1b9b8ae4-c4b2-4d39-8352-76917d977bc8)

La invitiamo a riprovare effettuando le modifiche indicate di seguito:

_**Authentication Bearer Token:**_
_As is:_ "iss": "auth:S1#111GMEDSRL" -> _To be:_ "iss": "auth:S1#111#GMEDSRL"

_**FSE-JWT-Signature Token:**_
_As is:_ "iss": "integrity:S1#111GMEDSRL" -> _To be:_ "iss": "integrity:S1#111#GMEDSRL"

Rimaniamo a disposizione per ulteriore supporto.
Grazie.

**Comment by AlessioMaggioriGMED** [comment]
Grazie della pronta risposta.
Corretto il parametro, funziona correttamente.

Saluti
