### ISSUE TITLE
Inserimento in lista dei software convalidati

### ISSUE THREAD

**Issue by mvalentini-onit** [ministero-salute/it-fse-support#986]
Buongiorno,
il 29/08/2024 abbiamo ricevuto la mail di superamento dei test per la validazione del software Klinika versione 1.2.0

> Salve,
> Con la presente si comunica il superamento dei seguenti test [6,29,37,63,64,65,67,68,69,70,73,369,31,39,75,76,77,79,80,81,82,83,84,85,446,32,40,151,152,153,155,156,158,159,160,161,163,169,374] per il servizio [validazione/pubblicazione] del Fornitore [A1#111#ONITSANITAXX] - Vendor:[Onit_Sanita] - ID: [Klinika] - Version: [1.2.0] - Sha: [63902cff5a905ccae29b5ed5e4be54ce10d471d1] in data odierna.Dal processo è stato escluso il controllo dei test: [7,8,9,45,66,71,72,74,47,78,86,87,88,89,90,91,92,93,447,48,147,148,149,150,154,157,162,164,165,166,167,168] per i quali si è ottenuto l'esonero. 
> A conclusione del processo, seguirà ulteriore comunicazione da parte del Dipartimento per la Trasformazione Digitale (DTD).
> Saluti,
> Il Team FSE 2.0

Lo stesso tipo di comunicazione lo abbiamo ricevuto per le versioni precedenti, ma non siamo stati inseriti nella lista dei software accreditati.
Dobbiamo fare o manca qualcosa?

Grazie,
Massimiliano Valentini

**Comment by vigliottim** [comment]
Buongiorno,
sono in corso alcune verifiche da parte del Dipartimento per la Trasformazione Digitale (DTD).
Riceverete ulteriori aggiornamenti non appena saranno concluse.
Chiudiamo il presente ticket e rimaniamo a disposizione per altre richieste di supporto.
Grazie.

**Comment by mvalentini-onit** [comment]
Salve,
Possiamo avere un riferimento per chiedere informazioni in merito alle tempistiche sulle verifiche in corso?
Grazie.
