### ISSUE TITLE
Campo Locality CDA

### ISSUE THREAD

**Issue by acostablueday** [ministero-salute/it-fse-support#989]
Buongiorno,
stiamo eseguendo le procedure di apprendimento per un nostro cliente il quale che però non è una struttura sanitaria certificata.

Nello specifico quando bisogna generare i JWT Token (https://github.com/ministero-salute/it-fse-gtw-tools/tree/main/jwt-generator) bisogna associare un file data.json che contiene tutte le informazioni per farsi “riconoscere”, una di queste informazione è il campo “locality” che se abbiamo capito correttamente è l’identificativo del medico/struttura sanitaria. Nel nostro caso però il nostro cliente non è ne un medico ne una struttura sanitaria certificata.
Come dobbiamo comportarci in questo caso? Il cliente deve per forza registrarsi come struttura sanitaria certificata?
Avevamo chiesto supporto tramite Issue e ci avevate fornito questo link: https://www.salute.gov.it/portale/temi/p2_6.jsp?id=3826&area=statisticheSSN&menu=vuoto , però ovviamente il nostro cliente non è presente in queste liste.
Cosa possiamo fare?

**Comment by vigliottim** [comment]
Buongiorno, può consultare al seguente link i codici delle strutture private: 
[Codici assegnati alle strutture di ricovero e alle altre strutture private  (salute.gov.it)](https://www.salute.gov.it/portale/documentazione/p6_2_2_1.jsp?lingua=italiano&id=1051).
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri procediamo alla chiusura della presente issue.
Sarà possibile riaprirlo nel caso in cui avesse bisogno di ulteriore supporto.
Grazie.
