### ISSUE TITLE
 Errore nella validazione in modalità RESOURCE

### ISSUE THREAD

**Issue by NunzioAgfa** [ministero-salute/it-fse-support#99]
Buongiorno, sto facendo altre prove sempre in modalità Resource e ottengo di nuovo l'errore nell'estrazione del cda:
Errore in fase di estrazione del CDA.
Sapete dirmi cosa può essere sbagliato?
Allego il file e sotto trovate la risposta completa:
{
"traceID" : "7e6bf0e282c4db1a",
"spanID" : "7e6bf0e282c4db1a",
"type" : "/msg/cda-element",
"title" : "Errore in fase di estrazione del CDA.",
"detail" : "Error while extracting CDA from PDF document",
"status" : 400,
"instance" : "/cda-extraction",
"workflowInstanceId" : "UNKNOWN_WORKFLOW_ID"
}
[WEW811.pdf](https://github.com/ministero-salute/it-fse-support/files/10722786/WEW811.pdf)

**Comment by IStacchiotti** [comment]
Buongiorno, ci risulta che sta inserendo nel requestBody la modalità ATTACHMENT
{"healthDataFormat":"CDA","mode":"ATTACHMENT","activity":"VALIDATION"}
invece che la modalità RESOURCE.

**Comment by NunzioAgfa** [comment]
Buongiorno, confermo che per errore in questa prova ho valorizzato il modo errato la modalità. Grazie.
