### ISSUE TITLE
 CRASH PROGRAM - authorInstitution non compilato

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#990]
Buongiorno,
Apriamo la seguente segnalazione di metadati errati.

Nel token JWT inseriamo
"locality": "OSPEDALE CENTRALE DI BOLZANO^^^^^&amp;2.16.840.1.113883.2.9.4.1.2&amp;ISO^^^^041001"
Ma nella richiesta di ini troviamo:
![image](https://github.com/user-attachments/assets/109c0ed9-39e4-4a2e-a1db-259400c0e59b)
e
![image](https://github.com/user-attachments/assets/3108857b-dce4-44f1-b385-7f1cda7947a1)

Potete verificare?

**Comment by vigliottim** [comment]
Buongiorno,
la invitiamo a riprovare dopo aver applicato le indicazioni riportate nel commento alla seguente issue: https://github.com/ministero-salute/it-fse-support/issues/981#issuecomment-2331863701
Rimaniamo a disposizione nel caso in cui il problema non dovesse risolversi.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
La invitiamo a riaprirla nel caso in cui abbia bisogno di ulteriore supporto.
Grazie.

**Comment by vigliottim** [comment]
Buonasera,
attualmente le specifiche del Gateway pubblicate al link [integrazione-gateway](https://github.com/ministero-salute/it-fse-support/tree/main/doc/integrazione-gateway) non corrispondono all'effettivo comportamento del sistema.
Questo disallineamento, risolvibile con un rilascio già pronto lato Gateway, era stato pianificato al fine di dare tempo a tutti gli attori interessati (Gateway stesso, INI, Regioni in interoperabilità e Regioni in sussidiarietà) di adeguarsi alle specifiche.
Seguiranno aggiornamenti non appena disponibili.
Grazie.

**Comment by vigliottim** [comment]
Buon pomeriggio, 
è stato rilasciato un aggiornamento.
Le chiediamo cortesemente di riprovare e darci un feedback. 
Grazie.

**Comment by SonnyMate** [comment]
Adesso non viene accettata la locality precedentemente utilizzata, stiamo verificando se è un nostro errore.
Quella attualmente OSPEDALE CENTRALE DI BOLZANO^^^^^&amp;2.16.840.1.113883.2.9.4.1.2&amp;ISO^^^^041001

Vi faccio sapere appena finita l'analisi

**Comment by LucaRogledi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, la presente viene chiusa come risolta. Si può procedere con la riapertura in caso fosse necessario ulteriore supporto. Grazie
