### ISSUE TITLE
Codici Loinc

### ISSUE THREAD

**Issue by infoserviceonline** [ministero-salute/it-fse-support#992]
Buongiorno, ho scaricato i file csv con i codici loinc da https://www.loinc.it/?p=727, versione 2.78, ma ho un problema.
Nelle more dell'integrazione reale (non test case) per RSA dovrei associare ad ogni prestazione un codice Loinc, ma non trovo, ad esempio, la Visita Fisiatrica, codice nomenclatore 89.7. Inoltre vedo che quasi tutti i termini sono in Inglese. Considerando che saranno gli utenti ad associare le prestazioni ad i codici loinc prevedo un disastro annunciato.
Potete darmi qualche indicazione utile?
Grazie mille.

**Comment by infoserviceonline** [comment]
Salve, io sapevo che i codici ICD9-CM individuano le patologie, non le prestazioni, come leggo anche qui:
https://www.fascicolosanitario.gov.it/sistema-di-codifica-icd-9-cm
Se ho capito bene, invece, esiste un nomenclatore anche per le prestazioni e devo utilizzare o LOINC (ma non ho le prestazioni che mi occorrono) o ICD9-CM, ma non trovo riferimenti utili. Ovviamente, per poter utilizzare le translations devo prima inserire un codice riconosciuto (LOINC o ICD9-CM), giusto? 
Potete darmi qualche indicazione su dove reperire i codici ICD9-CM per le prestazioni? Cercando in giro trovo come codici gli stessi del nomenclatore (89.7 ad esempio).
Grazie mille.

**Comment by vigliottim** [comment]
Condividiamo di seguito il link al sito Ministeriale dove poter scaricare il manuale ICD9CM:
https://www.salute.gov.it/portale/assistenzaOspedaliera/dettaglioContenutiAssistenzaOspedaliera.jsp?id=1278&area=ricoveriOspedalieri&menu=classificazione.

Per la codifica della prestazione nel caso in cui non vi sia un riferimento all'interno del dizionario LOINC o nel manuale ICD9CM è possibile utilizzare altri Nomenclatori Ministeriali/Regionali riconosciuti ufficialmente.

Infine, l'elemento _translation_ è opzionale e possono essere riportate codifiche ulteriori a qualsiasi sistema di codifica riconosciuto.

**Comment by infoserviceonline** [comment]
Ok, grazie, studierò la situazione.
Saluti.
