### ISSUE TITLE
Errore "Duplicate key Duplicate key 2.16.840.1.113883.2.9.2.690237"

### ISSUE THREAD

**Issue by NunzioAgfa** [ministero-salute/it-fse-support#993]
Nella validazione del cda ottengo l'errore descritto nel titolo.
Andando ad indagare, ho visto che l'errore è dovuto al fatto che nel PatientRole, ci sono due ripetizioni, che pur avendo un root diverso, hanno uno stesso valore nel campo extension:

Queste si riferiscono rispettivamente al codice MPI e al codice del paziente interno all'applicativo e in questa installazione i due codici corrispondono.

Come è possibile evitare questo errore?
Due codici uguali nel campo extension su due diverse ripetizioni, ma associati a valori di root diversi non dovrebbero comunque essere accettati?

Sotto riporto la risposta completa ottenuta dal gateway:

{
"traceID" : "3ab4a59b9805a4f2",
"spanID" : "3ab4a59b9805a4f2",
"type" : "/msg/generic-error",
"title" : "Errore generico.",
"detail" : "Duplicate key 2.16.840.1.113883.2.9.2.690237",
"status" : 500,
"instance" : ""
}

**Comment by vigliottim** [comment]
Buon pomeriggio,
secondo la guida HL7 Italia per RAD, disponibile al link [HL7IT-IG_CDA2_RAD-v1.1-S.pdf](https://www.hl7.it/wp-content/uploads/2024/04/HL7IT-IG_CDA2_RAD-v1.1-S.pdf), nel caso di Cittadino Italiano o straniero residente in Italia, l'elemento _patientRole_ deve contenere:
- un elemento _id_ contenente il Codice Fiscale (obbligatorio); 
- un elemento _id_ (obbligatorio) contenente il numero di identificazione dell’assistito nel sistema PACS in cui sono custodite le immagini.
Pertanto, non è possibile inserire un terzo elemento _id_.
Rimaniamo a disposizione per ulteriori chiarimenti.

**Comment by NunzioAgfa** [comment]
Ok grazie.

**Comment by LucaRogledi** [comment]
Buon pomeriggio, ringraziamo per il feedback e procediamo con la chiusura della issue come risolta. Grazie
