### ISSUE TITLE
Crash Program: mancata ricezione notifica comunica metadati

### ISSUE THREAD

**Issue by marco-volpe** [ministero-salute/it-fse-support#994]
Buongiorno

come Regione Piemonte e come RDE non riceviamo la notifica di avvenuta comunicazione metadati verso altra RDA
L'endpoint che dovrebbe ricevere le notifiche è il seguente

```
https://ts-cloud-interop.fsepiemonte.it/dmainimedpi/services/piFseNotifyCommunicationMetadata
```

Grazie, restiamo a disposizione

**Comment by g-maugeri-sogei** [comment]
Buonasera,
potete riprovare con una nuova pubblicazione e darci riscontro?

**Comment by marco-volpe** [comment]
Buongiorno

confermiamo la corretta ricezione della notifica

Grazie

**Comment by vigliottim** [comment]
Grazie per il gentile riscontro.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
