### ISSUE TITLE
CRASH PROGRAM - Aggiornamento metadati - XDSSubmissionSet.author

### ISSUE THREAD

**Issue by angeloceloni** [ministero-salute/it-fse-support#995]
A seguito di invio richiesta aggiornamento metadati al gateway la regione riceve una transazione ITI-57 con il Classification relativo all'XDSSubmissionSet.author con classifiedObject="Document1" invece di "SubmissionSet1"

**Comment by vigliottim** [comment]
Buongiorno,
è stato rilasciato un aggiornamento.
Le chiediamo gentilmente di riprovare e darci un feedback.
Grazie.

**Comment by angeloceloni** [comment]
Buongiorno
confermo la risoluzione del problema segnalato
