### ISSUE TITLE
CRASH PROGRAM - Aggiornamento metadati - Errore Classification del RegistryPackage

### ISSUE THREAD

**Issue by angeloceloni** [ministero-salute/it-fse-support#996]
A seguito di invio richiesta aggiornamento metadati al gateway la regione riceve una transazione ITI-57 con il Classification relativo al RegistryPackage è valorizzato con il classifiedNode ed id errato errato:
<ns2:Classification classificationNode="urn:uuid:907e714d-8cbf-4b1d-8049-6a771045192c" classifiedObject="SubmissionSet1" id="Document1"/>
mentre dovrebbe essere come nella ITI-42:
<ns2:Classification classificationNode="urn:uuid:a54d6aa5-d40d-43f9-88c5-b4633d873bdd" classifiedObject="SubmissionSet1" id="Classification1" objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification"/>

Per quanto riguarda l'attributo id il problema era già stato segnalato con la issue 970 chiusa con bugfix errato

**Comment by vigliottim** [comment]
Buongiorno,
è stato rilasciato un aggiornamento.
Le chiediamo gentilmente di riprovare e darci un riscontro.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso in cui avesse bisogno di ulteriore supporto.
Grazie.
