### ISSUE TITLE
CRASH PROGRAM - Bad Request 

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#997]
Buongiorno, 
abbiamo problemi ad eseguire la cancellazione dei metadati.
Potreste aiutarci a capire cosa sbagliamo?
 
 
DELETE https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_032656928463
400
170 ms
DELETE /govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_032656928463 HTTP/1.1
Accept: application/json
FSE-JWT-Signature: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGYlRDQ0ExV2dBd0lCQWdJVUdockVBVVM4ZDB3T0pzR3hDQXJLc2ptMTF3NHdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlOREEzTWpRd056TTBNRFZhRncweU56QTNNalV3TnpNME1EUmFNRzR4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVI4d0hRWURWUVJoREJaRFJqcEpWQzFRVWs5V1FWZ3dNRmd3TUZnd01EQlpNUjB3R3dZRFZRUUREQlJUTWlNd05ERWpVRUZDVDB4YVFVNVBWRVZUVkRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjBvV1A1L1NVSXlHaWJSeWQ3TkJZYUFiYnp4am9qSDJlR3l0RTVINnJrUExCVlkvUW5ja2tNTnRzYTdJcXhOeExBMENSM1gzbVZ3RjVXcy9OSXlFOVJ1UGY0MnZvZUNZb2d3bk9MOXljMXlJdzNZcm9icnF5MFJBZ3Y2elVmQ0VCZnNGM1l5S1ZxSXFjSTZwUmEwanhHdW5vOHdrTUtZUGZSMHhEWVovcU9aS0RqSUNhR0tSckVycndIcUNyUHJtdXI3ZkUwTHJtWXAxMTBXeU04UktTa1k2M0tsdGFmTkIvanR0VVBocVlaYkdtZlgyVXc3TFlwcURRZG5MdzVVb2JNOFhYa3g1TzFuRWd1TWMvQlhMNSt6ZjJ3ajhFVEEyWnp6cHJ1RDc1QnRPM3BiRE8vQjNJZjJYS3EzYzQ5QkJhNGxNZ0l0Y2lvbmFNOU01dWpoNzBFQ0F3RUFBYU9DQVJnd2dnRVVNQjhHQTFVZEl3UVlNQmFBRkJZNXFSb0ZpYmNQTGJJMTdjSUptc1VEZ3lJL01CSUdBMVVkSUFRTE1Ba3dCd1lGSzB3ZEFRc3dnYTBHQTFVZEh3U0JwVENCb2pDQm42Q0JuS0NCbVlhQmxtaDBkSEJ6T2k4dlkyRnpiMmRsYVhOMmFXd3VjMjluWldrdWFYUXZaV3BpWTJFdmNIVmliR2xqZDJWaUwzZGxZbVJwYzNRdlkyVnlkR1JwYzNRL1kyMWtQV055YkNacGMzTjFaWEk5UTA0bE0wUkRRU3ROYVc1cGMzUmxjbThyWkdWc2JHRXJVMkZzZFhSbEsxUmxjM1FsTWtOUEpUTkVUV2x1YVhOMFpYSnZLMlJsYkd4aEsxTmhiSFYwWlNVeVEwTWxNMFJKVkRBZEJnTlZIUTRFRmdRVVU3OTd6cWM2Q1ZWaERwODhORlpTSENVZ20vRXdEZ1lEVlIwUEFRSC9CQVFEQWdaQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQ3AySStPd1JmQzJPRnFvUEhENjdPU0VIclh2clZvOUJMTFl5eGJhTXpmaHJIdW9rRXNSb1FtNm5PNzR2WWp2citoY1BCRGFxV0ZGVzZqQlVZOGpBUkcyclZhY2JaQ3BSeENqcTlUZmUrTlNLbVVrdmd2bTdTVnZiUngxTXhJVldiL3J4ZzFvZDU3VThlNjI0d3U4ZTg1VkN4Vk5MSlNYaE0xaThKOFJMWFY2VEFIUENNU2FVRmdYYlRpRU96VEQzbUNsb3dlOENXbU5GejJSazBGU21pSWUrZmJabFRsSmR5anB6UDBmWFVzR1JXZ1krUERLYmdPdmhzd1Y1N1BndGg4aVZKcll2THlGaDFhOHZDTlZDZEVhSWhkdHg1QklkZ2QrOFdHL1p5SGxGbEJCc0RaeFdreWNyNkk4OTE0Z1JMNDFxZ2JZV2tLeFV5MlJhMW9tT014WTFxWFAxQWdPM2ZhQktBSmlsRGxTV2VscmNxTTVRMTY3NjNkbXhEUmVJTlNkOHhnUkdMTWtFTC85UHhPL2NLbkUyZ3NnVFNvaHBpQkVPbjlOZU0zeWdhWVlPVFVPZC9iRCs4dlBBUy9rTWxwN2g1WEh0SkxPQTBPQVUyLzVYTlRQNUs0UStCUzVPeUZVQUJoVGh5b3ZIZ3JZVnNvUGxHRS9xVmF1RHJEVG1WYTYxMXJTWExWVGM4YklRQUNYWjNSNDdHOFdQUXJLdm04ZDZCTGJnSURPODlzMWVmRXhPODdpMy9TbHRCZFRoeTI2U1BFZHRyR2hIMU9SeHBOOG1ZYWg1c3ZBbXdQS1JhcytBa25QQlY3S1Z0b0QxVWtvV3lyL1NQbVBBeDhack53T1d4SVYxdDJwZThQRS9kRE1SNU1qQkRtYUxHNjFuZHZENllWS0NIWnZBPT0iXX0.eyJpc3MiOiJpbnRlZ3JpdHk6UzIjMDQxI1BBQk9MWkFOT1RFU1QiLCJpYXQiOjE3MjY0OTU2NjAsImV4cCI6MTcyNjQ5OTI2MCwianRpIjoiZTczYjM0YzgtM2Y4My00OWI2LWI2ZDgtZTRmODViYWFkODA2IiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEtdmFsLmZzZS5zYWx1dGUuZ292Lml0L2dvdndheS9yZXN0L2luL0ZTRS9nYXRld2F5L3YxIiwic3ViIjoiVlZOTVNNNzVCMDFBNzAzRF5eXiYyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4zLjImSVNPIiwic3ViamVjdF9vcmdhbml6YXRpb25faWQiOiIwNDEiLCJzdWJqZWN0X29yZ2FuaXphdGlvbiI6IlAuQS4gQm9semFubyIsImxvY2FsaXR5IjoiT1NQRURBTEUgQ0VOVFJBTEUgREkgQk9MWkFOT15eXl5eJmFtcDsyLjE2Ljg0MC4xLjExMzg4My4yLjkuNC4xLjImYW1wO0lTT15eXl4wNDEwMDEiLCJzdWJqZWN0X3JvbGUiOiJBQVMiLCJwZXJzb25faWQiOiJQUlZGU043MFMwNEE5NTJaXl5eJjIuMTYuODQwLjEuMTEzODgzLjIuOS40LjMuMiZJU08iLCJwYXRpZW50X2NvbnNlbnQiOnRydWUsInB1cnBvc2Vfb2ZfdXNlIjoiVVBEQVRFIiwicmVzb3VyY2VfaGw3X3R5cGUiOiIoJzExNTAyLTJeXjIuMTYuODQwLjEuMTEzODgzLjYuMScpIiwiYWN0aW9uX2lkIjoiREVMRVRFIiwic3ViamVjdF9hcHBsaWNhdGlvbl9pZCI6IkNPTkNFUlRPIiwic3ViamVjdF9hcHBsaWNhdGlvbl92ZW5kb3IiOiJERURBTFVTIFNQQSIsInN1YmplY3RfYXBwbGljYXRpb25fdmVyc2lvbiI6IjIyLjEuMSIsImF0dGFjaG1lbnRfaGFzaCI6ImYzODU1M2FjMmE4YWM4NTExY2QzNDBlMTQ1OWZhNzcwYTg5ZTFiZTU0YzdhZmI4ODBlMGUwMzUyNWJlMWIxNmUifQ.1A9IneU1KT7z-SShIMeKYhC98PzpIx6vyGQecb2eCpxbW6L_qvq5Ecz_DSWhm-io2LxdmrhieeYiBCt8-CKtxMe35rV-L0wpZ6AnGiFAq96saATmQk_iY6gJGlshF_1r4jr4-ijG1yyDWNtIOpntKcnS0i0LfWKeDyi9O7Ybn0ORXwea5fqYBkAqXRMvAAoHgOAnk-ZYY4d4PLyw65uZVuzmHtSdCcc3iciI6BVew2e6yPYaFy_R8lK8FgZtPpkjOaLsWKmncm9MSRraPj-WF254hrl87c0lXeSQ7859b1uiNKOpXu8-iWxNAU88h_BWfHsTWIbDAgz8flFMITtPwA
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlGYlRDQ0ExV2dBd0lCQWdJVUdockVBVVM4ZDB3T0pzR3hDQXJLc2ptMTF3NHdEUVlKS29aSWh2Y05BUUVMQlFBd1Z6RW5NQ1VHQTFVRUF3d2VRMEVnVFdsdWFYTjBaWEp2SUdSbGJHeGhJRk5oYkhWMFpTQlVaWE4wTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiR0VnVTJGc2RYUmxNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlOREEzTWpRd056TTBNRFZhRncweU56QTNNalV3TnpNME1EUmFNRzR4Q3pBSkJnTlZCQVlUQWtsVU1SOHdIUVlEVlFRS0RCWk5hVzVwYzNSbGNtOGdaR1ZzYkdFZ1UyRnNkWFJsTVI4d0hRWURWUVJoREJaRFJqcEpWQzFRVWs5V1FWZ3dNRmd3TUZnd01EQlpNUjB3R3dZRFZRUUREQlJUTWlNd05ERWpVRUZDVDB4YVFVNVBWRVZUVkRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjBvV1A1L1NVSXlHaWJSeWQ3TkJZYUFiYnp4am9qSDJlR3l0RTVINnJrUExCVlkvUW5ja2tNTnRzYTdJcXhOeExBMENSM1gzbVZ3RjVXcy9OSXlFOVJ1UGY0MnZvZUNZb2d3bk9MOXljMXlJdzNZcm9icnF5MFJBZ3Y2elVmQ0VCZnNGM1l5S1ZxSXFjSTZwUmEwanhHdW5vOHdrTUtZUGZSMHhEWVovcU9aS0RqSUNhR0tSckVycndIcUNyUHJtdXI3ZkUwTHJtWXAxMTBXeU04UktTa1k2M0tsdGFmTkIvanR0VVBocVlaYkdtZlgyVXc3TFlwcURRZG5MdzVVb2JNOFhYa3g1TzFuRWd1TWMvQlhMNSt6ZjJ3ajhFVEEyWnp6cHJ1RDc1QnRPM3BiRE8vQjNJZjJYS3EzYzQ5QkJhNGxNZ0l0Y2lvbmFNOU01dWpoNzBFQ0F3RUFBYU9DQVJnd2dnRVVNQjhHQTFVZEl3UVlNQmFBRkJZNXFSb0ZpYmNQTGJJMTdjSUptc1VEZ3lJL01CSUdBMVVkSUFRTE1Ba3dCd1lGSzB3ZEFRc3dnYTBHQTFVZEh3U0JwVENCb2pDQm42Q0JuS0NCbVlhQmxtaDBkSEJ6T2k4dlkyRnpiMmRsYVhOMmFXd3VjMjluWldrdWFYUXZaV3BpWTJFdmNIVmliR2xqZDJWaUwzZGxZbVJwYzNRdlkyVnlkR1JwYzNRL1kyMWtQV055YkNacGMzTjFaWEk5UTA0bE0wUkRRU3ROYVc1cGMzUmxjbThyWkdWc2JHRXJVMkZzZFhSbEsxUmxjM1FsTWtOUEpUTkVUV2x1YVhOMFpYSnZLMlJsYkd4aEsxTmhiSFYwWlNVeVEwTWxNMFJKVkRBZEJnTlZIUTRFRmdRVVU3OTd6cWM2Q1ZWaERwODhORlpTSENVZ20vRXdEZ1lEVlIwUEFRSC9CQVFEQWdaQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQ3AySStPd1JmQzJPRnFvUEhENjdPU0VIclh2clZvOUJMTFl5eGJhTXpmaHJIdW9rRXNSb1FtNm5PNzR2WWp2citoY1BCRGFxV0ZGVzZqQlVZOGpBUkcyclZhY2JaQ3BSeENqcTlUZmUrTlNLbVVrdmd2bTdTVnZiUngxTXhJVldiL3J4ZzFvZDU3VThlNjI0d3U4ZTg1VkN4Vk5MSlNYaE0xaThKOFJMWFY2VEFIUENNU2FVRmdYYlRpRU96VEQzbUNsb3dlOENXbU5GejJSazBGU21pSWUrZmJabFRsSmR5anB6UDBmWFVzR1JXZ1krUERLYmdPdmhzd1Y1N1BndGg4aVZKcll2THlGaDFhOHZDTlZDZEVhSWhkdHg1QklkZ2QrOFdHL1p5SGxGbEJCc0RaeFdreWNyNkk4OTE0Z1JMNDFxZ2JZV2tLeFV5MlJhMW9tT014WTFxWFAxQWdPM2ZhQktBSmlsRGxTV2VscmNxTTVRMTY3NjNkbXhEUmVJTlNkOHhnUkdMTWtFTC85UHhPL2NLbkUyZ3NnVFNvaHBpQkVPbjlOZU0zeWdhWVlPVFVPZC9iRCs4dlBBUy9rTWxwN2g1WEh0SkxPQTBPQVUyLzVYTlRQNUs0UStCUzVPeUZVQUJoVGh5b3ZIZ3JZVnNvUGxHRS9xVmF1RHJEVG1WYTYxMXJTWExWVGM4YklRQUNYWjNSNDdHOFdQUXJLdm04ZDZCTGJnSURPODlzMWVmRXhPODdpMy9TbHRCZFRoeTI2U1BFZHRyR2hIMU9SeHBOOG1ZYWg1c3ZBbXdQS1JhcytBa25QQlY3S1Z0b0QxVWtvV3lyL1NQbVBBeDhack53T1d4SVYxdDJwZThQRS9kRE1SNU1qQkRtYUxHNjFuZHZENllWS0NIWnZBPT0iXX0.eyJpc3MiOiJhdXRoOlMyIzA0MSNQQUJPTFpBTk9URVNUIiwiaWF0IjoxNzI2NDk1NjYwLCJleHAiOjE3MjY0OTkyNjAsImp0aSI6IjM3M2NiNmFkLTQ0ZGQtNGJhNS1hNDRjLTg4NTE0NjAzYjA5YSIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5mc2Uuc2FsdXRlLmdvdi5pdC9nb3Z3YXkvcmVzdC9pbi9GU0UvZ2F0ZXdheS92MSIsInN1YiI6IlZWTk1TTTc1QjAxQTcwM0ReXl4mMi4xNi44NDAuMS4xMTM4ODMuMi45LjQuMy4yJklTTyJ9.ieuMWLhod9RgadmUgOg30QB5n5vo95kHQR6OVUAnzfEsYITIn0AepE7zgncvvVE1AUOOunhzLckeqlvSqrYouwTZhpw0DyFHaOD4HNBLkDqaiOOQs8yL5cqlCSvGrORl2sElGEYSvSeHDLPhSwzzd_P1GhygJ6JBWEowAjIj3-_xx5jWfYge5SMVIzt9T6EGVJIVVHLDnSpAIgOmcHFwD1ouCW2Z0kfber_HvCKJtxsqbdUTJULZJGDPEnvb_8kb6qE0sfM447VPUrRVKTSGlUrABh2C7SFZz4OP_SsZ1W3q-BVgvetSmDk4Ow-lwqLozUXOmkr6nO4qtDz9LYfW3w
User-Agent: PostmanRuntime/7.41.2
Cache-Control: no-cache
Postman-Token: 39f7cc18-2a5d-4673-ade4-73f2c9ed416d
Host: modipa-val.fse.salute.gov.it
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: 894d46ecfc124039ee218b63c12a3329=9c62788caf0fe4a977db8e11a8d1653d

**Comment by vigliottim** [comment]
Buonasera,
al fine di svolgere indagini più approfondite, potrebbe cortesemente inserire la response completa comprensiva di traceid/govwayid?
Grazie.

**Comment by SonnyMate** [comment]
Perfetto scusate grazie
