### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by FSESardegna** [ministero-salute/it-fse-support#998]
Buongiorno,
alleghiamo una ITI42 che riceviamo da INI in seguito a update mandata ad EDS.
Riscontriamo che all'interno del RegistryPackage c'è una classification (urn:uuid:cccf5598-8b07-4b77-a05e-ae952c785ead), il cui classifiedObject  fa riferimento all'extrinsicObject. Questo non permette di passare le nostre validazioni.

Grazie.

[ITI42-FROM-INI.txt](https://github.com/user-attachments/files/17015306/ITI42-FROM-INI.txt)

**Comment by vigliottim** [comment]
Buongiorno,
secondo le verifiche svolte, sembrerebbe corretto che, per il _classification_ urn:uuid:cccf5598-8b07-4b77-a05e-ae952c785ead, il _classifiedObject_ faccia riferimento all'_extrinsicObject_ identificato da _Document1_.
Può fornirci maggiori dettagli sui problemi riscontrati in validazione?
Grazie.

**Comment by FSESardegna** [comment]
Buongiorno,
ci scusiamo per aver riportato il classificationScheme della classification errata. Riportiamo il classificatioScheme corretto "urn:uuid:a7058bb9-b4e4-4307-ba5b-e3f0ab85e12d".

Per semplicità di lettura incolliamo qui  la classification con il classifiedObject errato:
```
<ns2:Classification classificationScheme="urn:uuid:a7058bb9-b4e4-4307-ba5b-e3f0ab85e12d"
					                    classifiedObject="Document1"
					                    id="urn:uuid:435f9142-9d62-4260-b603-dc9546f8e602"
					                    nodeRepresentation=""
					                    objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification">
						<ns2:Slot name="authorRole">
							<ns2:ValueList>
								<ns2:Value>AAS</ns2:Value>
							</ns2:ValueList>
						</ns2:Slot>
						<ns2:Slot name="authorInstitution">
							<ns2:ValueList>
								<ns2:Value>ASSL UNICA - REGIONE SARDEGNA^^^^^&amp;2.16.840.1.113883.2.9.4.1.3&amp;ISO^^^^200106</ns2:Value>
							</ns2:ValueList>
						</ns2:Slot>
						<ns2:Slot name="authorPerson">
							<ns2:ValueList>
								<ns2:Value>PROVAX00X00X000Y^^^^^^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</ns2:Value>
							</ns2:ValueList>
						</ns2:Slot>
					</ns2:Classification>
```
Rimaniamo in attesa di un riscontro,
Grazie.

**Comment by vigliottim** [comment]
Buonasera,
la chiamata da lei riportata è recente? Potreste gentilmente effettuare una nuova chiamata e darci un riscontro?
Grazie.

**Comment by FSESardegna** [comment]
Stiamo riscontrando dei problemi con la pubblicazione come anticipato nella Issue 1033. Appena possibile ri-eseguiremo una nuova chiamata.
Grazie

**Comment by vigliottim** [comment]
Buonasera, le comunichiamo che la issue #1033 è stata risolta. 
Potreste effettuare un nuovo test? Grazie.

**Comment by FSESardegna** [comment]
Buongiorno,
abbiamo eseguito una nuova prova ed è andata a buon fine, grazie.
