### ISSUE TITLE
Errore: "RDA generated an internal error"

### ISSUE THREAD

**Issue by federicolau** [ministero-salute/it-fse-support#999]
Ciao,

stiamo riscontrando problemi con la chiamta al servizio di **validazione e pubblicazione sostituzione contestuale** utilizzando il seguente codice fiscale **FSEPGL01E41A145J**.

A seguire gli step che abbiamo conseguito:

**1. Chiamata al servizio di validazione:**

```
POST https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/validation

POST data:
--utqFklQeo3C51kSrQoPpdKMfsI0N3r3jiWj
Content-Disposition: form-data; name="requestBody"
Content-Type: application/json; charset=UTF-8
Content-Transfer-Encoding: 8bit

{"activity": "VALIDATION"}
--utqFklQeo3C51kSrQoPpdKMfsI0N3r3jiWj
Content-Disposition: form-data; name="file"; filename="output.pdf"
Content-Type: application/pdf
Content-Transfer-Encoding: binary

<actual file content, not shown here>
--utqFklQeo3C51kSrQoPpdKMfsI0N3r3jiWj--
```

ottenendo la seguente la seguente risposta:

`{"traceID":"b4fc3d43e29d2f62","spanID":"b4fc3d43e29d2f62","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.847f1ce174^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","warning":"[[SIGN_WARN - Attenzione il documento risulta firmato in validazione][WARNING_EXTRACT]Attenzione, non Ã¨ stata selezionata la modalitÃ  di estrazione del CDA]"}`

**2. Chiamata al servizio di pubblicazione:**

```
POST https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents

POST data:
--1rQ8gzryGz1IkXvHbc7tcSSXbUca9oZ
Content-Disposition: form-data; name="requestBody"
Content-Type: multipart/form-data; charset=UTF-8
Content-Transfer-Encoding: 8bit

{   "assettoOrganizzativo": "AD_PSC001", "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^130702130",   "identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.1",   "identificativoSottomissione": "2.16.840.1.113883.2.9.4.3.2",   "tipoAttivitaClinica": "PHR",   "tipoDocumentoLivAlto": "WOR",   "tipologiaStruttura": "Ospedale",   "attiCliniciRegoleAccesso": [     "PUBLICPOL"   ],   "conservazioneANorma": "NormativaXYZ",   "descriptions": [     "019655^Bentelan^2.16.840.1.113883.2.9.6.1.5"   ],   "administrativeRequest": [     "SSN",     "INPATIENT"   ],   "mode": "ATTACHMENT",   "healthDataFormat": "CDA"}
--1rQ8gzryGz1IkXvHbc7tcSSXbUca9oZ
Content-Disposition: form-data; name="file"; filename="output.pdf"
Content-Type: application/pdf
Content-Transfer-Encoding: binary

<actual file content, not shown here>
--1rQ8gzryGz1IkXvHbc7tcSSXbUca9oZ--

```

ottenendo la seguente la seguente risposta:

`{"traceID":"22e906bfded8d7e3","spanID":"22e906bfded8d7e3","warning":"","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.847f1ce174^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"}`

**3. Chiamata al servizio di status:**

`GET https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/status/2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.847f1ce174%5E%5E%5E%5Eurn%3Aihe%3Aiti%3Axdw%3A2013%3AworkflowInstanceId`

ottenendo la seguente la seguente risposta:

`{"traceID":"f3553f12d2fb76b1","spanID":"88927e01c5940f2e","transactionData":[{"eventType":"VALIDATION","eventDate":"2024-09-16T14:16:10.205+00:00","eventStatus":"SUCCESS","subject":"FSEPGL01E41A145J","organizzazione":"160","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.847f1ce174^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","traceId":"b4fc3d43e29d2f62","issuer":"integrity:S1#160#REGIONEPUGLIATEST","expiringDate":"2025-09-16T14:16:10.215+00:00"},{"eventType":"PUBLICATION","eventDate":"2024-09-16T14:16:11.831+00:00","eventStatus":"SUCCESS","identificativoDocumento":"2.16.840.1.113883.2.9.2.120.4.4^130702130","subject":"FSEPGL01E41A145J","tipoAttivita":"PHR","organizzazione":"160","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.847f1ce174^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","traceId":"22e906bfded8d7e3","issuer":"integrity:S1#160#REGIONEPUGLIATEST","expiringDate":"2025-09-16T14:16:11.841+00:00"},{"eventType":"SEND_TO_INI","eventDate":"2024-09-16T14:16:12.442+00:00","eventStatus":"BLOCKING_ERROR","message":"SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:CRF2CODE CONTEXT:RDA generated an internal error.","workflowInstanceId":"2.16.840.1.113883.2.9.2.120.4.4.ed9ef196004e82b4b14f92144fac6398b20350b85c6955d3dadad99a7d0e1346.847f1ce174^^^^urn:ihe:iti:xdw:2013:workflowInstanceId","expiringDate":"2025-09-16T14:16:12.452+00:00"}]}`

**4. Chiamata al servizio di validate and replace che va in errore:**

```
PUT https://127.0.0.1:7070/ms-middleware/api/v1/documents/validate-and-replace/2.16.840.1.113883.2.9.2.120.4.4%5E130702130

PUT data:
--cuhsn10WQcaSEahmJdYCOIXwKippK14djyUq5
Content-Disposition: form-data; name="requestBody"
Content-Type: application/json; charset=UTF-8
Content-Transfer-Encoding: 8bit
```

```
{   "tipologiaStruttura": "Ospedale",   "attiCliniciRegoleAccesso": [     "PUBLICPOL"   ],   "tipoDocumentoLivAlto": "WOR",   "assettoOrganizzativo": "AD_PSC001",   "dataInizioPrestazione": "20230324112426",   "dataFinePrestazione": "20230324112426",   "conservazioneANorma": "string",   "tipoAttivitaClinica": "PHR",   "identificativoSottomissione": "SUBM112233",   "descriptions": [     "019655^Bentelan^2.16.840.1.113883.2.9.6.1.5"   ],   "administrativeRequest": ["SSN"],   "healthDataFormat": "CDA",   "mode": "ATTACHMENT",   "identificativoDoc": "2.16.840.1.113883.2.9.2.120.4.4^130702132",   "identificativoRep": "2.16.840.1.113883.2.9.2.120.4.5.1" }
--cuhsn10WQcaSEahmJdYCOIXwKippK14djyUq5
Content-Disposition: form-data; name="file"; filename="output.pdf"
Content-Type: application/pdf
Content-Transfer-Encoding: binary

<actual file content, not shown here>
--cuhsn10WQcaSEahmJdYCOIXwKippK14djyUq5--
```

ottenendo la seguente la seguente risposta:

`{"traceID":"13902f353290a9f1","spanID":"13902f353290a9f1","type":"/msg/ini-error","title":"Ini error.","detail":"{\"traceID\":\"13902f353290a9f1\",\"spanID\":\"13a13a1619dff898\",\"type\":\"/errors\",\"title\":\"Generic\",\"detail\":\"RDA generated an internal error.\",\"instance\":\"error/generic\"}","status":500,"instance":"/msg/service-error/ini"}`

In allegato:

- [Authorization token.txt](https://github.com/user-attachments/files/17015272/Authorization.token.txt)
- [FSE-JWT-Signature token.txt](https://github.com/user-attachments/files/17015268/FSE-JWT-Signature.token.txt)
- [output.pdf](https://github.com/user-attachments/files/17015287/output.pdf)

**NOTA BENE: Abbiamo riscontrato lo stesso errore anche sui servizi di "Aggiornamento Metadati"," Sostituzione Documento" ed "Eliminazione Documento" sempre per il codice fiscale comunicato.**

**Segnaliamo invece che utilizzando il codice fiscale "GTWGWY82B42G920M" il servizio sembrebbe funzionare correttamente.**

**Infine, precisiamo che abbiamo anche tentato di aumentare il timeout delle richieste ad 1 minuto.**

Come possiamo risolvere?

Grazie.

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
si tratta dello stesso problema dell'issue 1003. L'RDA=160 da soap  fauilt.
1) Confermate che l'endpoint chiamato e' corretto (sotto i log) ?
2) Se la risposta al punto 1) e' affermativa, trovate riscontro della chiamata sui log?

regione-rda : 160  
2024-09-16 16:16:12,350 INFO [it.finanze.sogei.fse.client.headerHandler.HeaderHandler] - endpoint-esterno : **https://138.66.186.221/FSE/DocumentRegistry_Service**  
2024-09-16 16:16:12,350 INFO [it.finanze.sogei.fse.client.headerHandler.HeaderHandler] - cache-control : no-store, no-cache, post-check=0, pre-check=0  
2024-09-16 16:16:12,350 DEBUG [it.finanze.sogei.fse.client.headerHandler.HeaderHandler] - Messaggio:

**Comment by federicolau** [comment]
Grazie per la risposta.

abbiamo comunicato i nuovi endpoint che dovranno essere richiamati (quelli che avevamo fornito non erano validi).
Tuttavia, stiamo riscontrando alcuni problemi di irraggiungibilità per i quali stiamo già lavorando interamente affinchè vengano risolti.

**Comment by LucaRogledi** [comment]
Buonasera, ringraziamo per il feedback e le chiediamo gentilmente un nuovo riscontro a problema risolto. Grazie

**Comment by vigliottim** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue. 
La informiamo che è possibile riaprirla nel caso in cui necessiti di ulteriore supporto. 
Grazie.
